### ISSUE TITLE
Custom hover: allow to move the mouse over it

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#115034] opened 2021-01-26 12:49 UTC
Refs: https://github.com/microsoft/vscode/issues/112490

I noticed this behavior both on Windows and macOS

1. Open the Pull Request view or some other view that uses the custom hover
2. Use the mouse to show the custom hover by hovering over some tree item for example
3. Try to move the mouse over the custom hover -> it hides immediatly

We should allow the user to move the mouse over the custom hover just like the native hover allows it. The reason for this is among others using Zoom programs for accessibility. Since users want to move the mouse over the hover so the zoom would show the content of the hover.
Destilled from https://github.com/microsoft/vscode/issues/112220 fyi @purplegranite

**Comment by Tyriar** [comment] 2021-01-26 13:42
We cannot do this by default, it would be incredibly annoying. Note that in the tree view it acts more like a `title` tooltip which is intentionally excluded from assistive technology. If anything a keybinding that matches the editor to show _and focus_ the hover could work for the active tree item:

![image](https://user-images.githubusercontent.com/2193314/105852325-2cbab280-5f99-11eb-9648-75c6e27aedfc.png)

**Comment by PurpleGranite** [comment] 2021-01-26 13:45
@Tyriar are you seriously saying that an inconvenience for others trumps accessibility for all?  I'm utterly shocked at that!!

**Comment by Tyriar** [comment] 2021-01-26 14:07
@PurpleGranite I'm saying we've already hit this issue before, so we need to consider another way to surface the hover to users.

If we wanted to stick to purely mouse interaction to access it, I saw a pretty nifty solution to this problem in the game Crusader Kings III which allows many levels of nesting tooltips. When you hover something, a spinner shows in the top right of the hover for ~2 seconds or so and when it's done you can mouse over the hover without it disappearing.

**Comment by isidorn** [comment] 2021-01-26 14:21
@Tyriar I like the idea to have the Show Hover use the same shortcut for showing the custom hover.

I like the game idea, but showing the spinner might be a bit distracting. For startes can't we just do it without the spinner, so after a timeout of ~2 seconds mouse would not cause it to hide

@PurpleGranite we appreciate the feedback, however let's try to be concise and reduce the drama if possible :)

**Comment by Tyriar** [comment] 2021-01-26 14:26
@isidorn the game also changes the border of the tooltip after the time has passed, we could do this fairly subtly to give a visual indication.

**Comment by isidorn** [comment] 2021-01-26 14:29
@Tyriar I like that idea a lot! So the border would show that the hover has become "stable".

Alternative idea: just allow the mouse to move over it when screen reader is detected. Since I believe that some of the zoom software is detected as a screen reader.

**Comment by Tyriar** [comment] 2021-01-26 14:39
@isidorn are we also targeting users that have difficulty with using a keyboard, would that be covered by the alt approach?

An extra benefit of the stable tooltip would be enabling selecting and copying text from the tooltip.

**Comment by PurpleGranite** [comment] 2021-01-26 14:41
@Tyriar I'd be much more in favour of the mechanism in the game you mention - however it would be important to ensure that any form of spinner or status indicator was not hidden by the mouse cursor - most users of magnifiers will have a cursor significantly larger than standard.  Testing with actual assistive software with real-world configurations will be key to ensure it works as expected.

If the border changes colour, that's fine too, though subtle isn't a good idea - again, many folk with sight impairments won't pick up on that change even when using assistive tools.  Colour selection would need to account for folk with various colour-differentiation issues as well, or at least be specified within the theme configuration somehow.

Overall though, that sounds like a much better approach than requiring a custom keybind to an obscure function that folk likely haven't discovered in the app.

@isidorn having consistently seen accessibility issues dismissed on this project and several others from Microsoft, I've become more than just a little distressed by the general approach ... after literally an entire lifetime of blocks being put in my way, my approach is very much a learned behaviour - I've been taught by those who don't take accessibility seriously that the only way to be heard is to shout long and loud.  I'm genuinely sorry you don't like that - but the only way to change that is in your hands, not mine!  Take an accessibility first approach to development and a significantly more positive approach towards accessibility issues across the entire team and demonstrate that openly!

**Comment by Tyriar** [comment] 2021-01-26 14:47
Perhaps an additional 1px outline on the hover would work better than changing the color, so the border gets a little larger/bolder after the timeout.

Before:

![image](https://user-images.githubusercontent.com/2193314/105860101-1533f780-5fa2-11eb-949e-245b2ec20ff3.png)

After:

![image](https://user-images.githubusercontent.com/2193314/105860140-1fee8c80-5fa2-11eb-8265-4d6aa7509101.png)

I think it would be great to also solve the problem of not being able to copy the text of the tooltip which can be frustrating sometimes.

**Comment by Tyriar** [comment] 2021-01-26 14:50
Tentatively assigning to February, don't want to rush in for Jan so it can get some testing/discussion.

**Comment by isidorn** [comment] 2021-01-26 14:58
@Tyriar makes sense to do this next milestone so we get feedback.
A thicker border looks great. I would just be interested in how the transition looks, from regular to thicker and if it is not distrurbing.

So far I have not heard feedback from users that use the keyboard. So for now let's go with the "stable" hover and see how it feels.
Also having the same keybinding shortcut makes sense in general so let's also do that.

**Comment by PurpleGranite** [comment] 2021-01-26 15:48
@Tyriar changing the border size does look like a good approach.  Would it be possible - at some point - to make that a configurable option, including specifying the number of pixels the border increases by?

That would give people who don't like it the option to turn it off, and would give people who use magnification tools like I do the option to increase the border by a larger (and therefore more easily discernible) amount too - I'm thinking an extra 3 or 4 pixels - which would definitely be too jarring for most users, but invaluable to magnifier users.

**Comment by Tyriar** [comment] 2021-01-26 16:05
@PurpleGranite seems reasonable, I'll bring this up in the UX sync next week and see what the rest of the team thinks.

**Comment by eamodio** [comment] 2021-02-01 18:14
It would be nice to also support holding down `alt` or `ctrl` or something, and then you can immediate hover over it with the mouse.

**Comment by Tyriar** [comment] 2021-02-03 22:19
Notes from UX sync:

- Would be nice to copy text in tooltip
- Holding down a key we could do it automatically
- Could also be useful for the editor hover
- General favor for adding
- Setting to drive this - also apply the timeout rule to hovers with links?

**Comment by irvnriir** [comment] 2021-04-02 21:26
i have this as issue, because can't use the links provided on description tooltips/hovers (in some cases they would save a lot of time) .

1 of the best solutions would be to keep the hover if mouse is moved right to it, and hide immediately if its moved outside/{to another direction} . for example, the hover opens upside of the cursor : if you move the cursor 1-2px downside, the tooltip closes, otherwise it'll stay open until you move the cursor outside of it ;. it also may hide on click onto the background of it .

**Comment by BenSeagrave** [comment] 2021-06-18 13:27
> i have this as issue, because can't use the links provided on description tooltips/hovers (in some cases they would save a lot of time) .
> 
> 1 of the best solutions is to make the tooltip stay if cursor is moved right to it, and hide immediately if its moved outside/{to another direction} . for example, the tooltip opens upside of the cursor : if you move the cursor 1-3px downside, the tooltip closes, otherwise it'll stay open until you move the cursor outside of it ;. it also may be made to hide on click onto the background of it .
> 
>  ScreenRecorderProject2.mp4 
> (prepositioning the cursor and using `editor.action.showHover` isn't the best workaround)

I am having the same issues seen here. I can't hover over any tooltips in vscode as they just instantly disappear when my mouse moves. Even if I use the 'Show hover' feature, when I move the mouse they disappear. I have tried disabling all extensions.

**Comment by isidorn** [comment] 2021-08-25 12:54
I encountered this again since we now show links in the extensions view using the custom hover. And these links can not be clicked upon. 
@Tyriar since we are using the custom hover in more and more places does it make sense to look into this issue?

fyi @sandy081 
![Screenshot 2021-08-25 at 14 52 33](https://user-images.githubusercontent.com/1926584/130793901-3315a92e-5550-4bf9-8344-e11869b9ce7a.png)

**Comment by sandy081** [comment] 2021-08-25 13:43
There is an issue already tracking it - https://github.com/microsoft/vscode/issues/128998

**Comment by setaskin** [comment] 2021-09-17 16:01
Hi @isidorn @Tyriar  , the accessibility team wants us to give fix date estimate on this ? Do you have an approx.. estimate when would it be fixed ?

**Comment by Tyriar** [comment] 2021-09-17 16:34
@setaskin there is no eta as it's unplanned and on the backlog right now.

**Comment by setaskin** [comment] 2021-09-17 16:41
@Tyriar , I understand , but for the  scorecard snapshot they absolutely want us to submit a date before September 22nd. Even a rough estimate would work.

**Comment by fsteffi** [comment] 2021-09-20 04:21
**GitHubTags:**#A11yMAS;#A11yTCS;#Win32;#DesktopApp;#A11y_VSCode;#WCAG1.4.13;#A11ySev2;#VisualStudioCode-Win32-Apr2021;#Benchmark;#Visual Studio Code Client;#Hover;#A11yWCAG2.1;

**Comment by isidorn** [comment] 2021-11-02 15:27
Optimistically assigning this to December just so we do not loose track of this. 
@Tyriar feel free to push out to January if you do not find time. Thanks!

**Comment by Tyriar** [comment] 2021-12-07 14:36
WIP looks great for large hovers:

![image](https://user-images.githubusercontent.com/2193314/145048294-4abdfbe8-d0c2-429e-8141-1865dfc6ae68.png)

It is triggered by waiting for 3 seconds currently or by hitting ctrl (or cmd for mac). Hovering shows the standard hover style, clicking will unlock it:

![image](https://user-images.githubusercontent.com/2193314/145048701-353e3950-1782-4362-82c8-114bdd559c1e.png)

Doesn't look great for smaller ones right now, but I want to avoid changing the hover size when it gets locked:

![image](https://user-images.githubusercontent.com/2193314/145048197-1aab78ce-501b-47c0-8e3c-4c2b495f2fc0.png)

Will bring to UX sync.

**Comment by Tyriar** [comment] 2021-12-22 19:27
Next round of feedback:

- The ux feels a bit cumbersome because the user has to manage the UI, would like for it to just work automatically without indications
- If the hover is a single line, you might want it to go away right away, and if it’s a rich hover that may take more time you might want it to stick around
- Should this locking mechanism be done in editor hovers too? otherwise it feels a bit inconsistent
- Pinning might be a better metaphor than locking?

I'm going to experiment with a more temporary state where ctrl would temporary lock the hover. That way you don't need to manage the state, just release ctrl. As for the editor hover point, that would be blocked on https://github.com/microsoft/vscode/issues/138617

**Comment by Tyriar** [comment] 2021-12-22 19:28
Also it feels weird in the terminal where you hover, then ctrl+click the link and the locked hover remains.

**Comment by Tyriar** [comment] 2021-12-22 19:38
This doesn't look great:

![image](https://user-images.githubusercontent.com/2193314/147146302-a9443f30-c73a-469c-94e1-e8a68020b614.png)
![image](https://user-images.githubusercontent.com/2193314/147146330-31c75580-00e6-47ae-a78a-a67eccd8ca1e.png)

**Comment by eamodio** [comment] 2021-12-23 20:56
@Tyriar Can you list the behavior/issues being tackled here?

Because for editor hovers, already allow the mouse to move over it and click links, etc. And for tree view hovers, the same is true if they contain links.

Now there are of course issues with both of the above. For example, the editor hover is sometime a little jumpy. It sometimes renders a little to high (or off right to left) and then moves closer to the cursor, which might be causing some of the phantom closes I see when moving the mouse into the hover.

![hover-jumpy](https://user-images.githubusercontent.com/641685/147289896-4dbdb508-37fc-4bc7-95b6-0531133bf982.gif)

And on tree views, the challenge is not getting in the way of the mouse pointer -- which is typically very good if the tooltip can render in the desired position (e.g. doesn't come up to an edge).

Good (arrow points to the cursor position):
![image](https://user-images.githubusercontent.com/641685/147290195-bfd94bfd-6ec1-4af4-8234-9cf1dbdaf5e0.png)

Not great (arrow points to the cursor position):
![image](https://user-images.githubusercontent.com/641685/147290150-ba4ca3cb-331b-4324-aa5d-34a409cdb072.png)

The tree view hovers are tricky as there is contention between moving the mouse to a different item vs moving into the hover. It seems like if the hover were always out of the way of the mouse moving vertically, but also allowing for diagonal movement into the hover it would help. Or maybe the hovers have threshold where if they've been visible for a very short time and the mouse moves close or over them) they will still hide, but if they've been visible longer they will be stickier. A shortcut key, like `ctrl` / `alt` might help here too (to make the hover sticky), though it requires more user interaction.

Alternatively, maybe rich hovers on tree items are always positioned outside the view itself (so it doesn't cover other items), and with that there could be more affordance to getting the mouse over to the hover (without it going away). Though that might be too awkward, as the mouse naturally will be further away from the hover.

**Comment by PurpleGranite** [comment] 2021-12-23 21:11
Focus has _clearly_ been lost on the original issue, which is specifically how the existing hovers - different depending on _what_ you’re hovering over - do not work well at all for users of _magnifier-based_ accessibility tools.  While it’s understandable that changes need to work for everyone not using such tools, can the Microsoft guys _please_ take the focus here back to solving the _accessibility_ issue and clean-up for everyone else later.

It would help significantly if those commenting would also spend at least one full working day coding using VS Code with a full-screen magnifier set to at least 3.5x zoom - you simply _cannot understand_ the magnitude nor scope of the originally reported issue until you do!

**Comment by Tyriar** [comment] 2022-01-04 17:52
@PurpleGranite @isidorn maybe I'm missing something, but using Magnifier on Windows 11 doesn't treat the native hover any differently from the custom hover. It still doesn't allow you to hover it and doesn't guarantee it will show up in the magnifier viewport?

**Comment by Tyriar** [comment] 2022-01-04 17:58
@eamodio the main goal is allowing the user to mouse over _any_ hover, regardless of its content, while not annoying users and regressions on problems that we've already fixed. This includes hovers that intentionally are lightweight like status bar items, activity bar, panels, etc. The hover position is a good point but we already do this, just not on the right sidebar it seems - can you create an issue to track this as I think we just need to invert the offset in the other direction?

Improving magnifiers is the other thing which admittedly I don't completely understand the problem as mentioned above.

**Comment by isidorn** [comment] 2022-01-06 15:08
@Tyriar I just double checked and you are correct, the native hover on Windwos behaves the same way as our custom hover with magnifiers.
The only hover that works well is the Editor one that allows mouse to be moved over it.

I also believe that the magnifier problem will go away as soon as we have a good mechanism for moving the mouse over the hover. So I suggest we focus on that first as we have so far.

**Comment by isidorn** [comment] 2022-03-31 13:48
Latest plan = will not be tackled in April. We will probably look into this in May. We will know more end of April once we create the May iteration plan.

**Closed** 2022-05-03 19:19 UTC
Labels: feature-request, accessibility, a11ymas, workbench-hover, a11y-partner, accessibility-sla

**Comment by Tyriar** [comment] 2022-05-03 19:46
Update: I merged in the alt to lock the hover idea, the main changes that have happened recently are the removal of the lock icon and improved reliability/hiding of the hover when alt is released.

![Recording 2022-05-03 at 11 33 54 (1)](https://user-images.githubusercontent.com/2193314/166554132-b69d2aa3-92e7-4e08-bfb8-c3fde66a479f.gif)

**Comment by isidorn** [comment] 2022-05-04 13:02
@Tyriar this is great, thanks a lot 👏 
I have pushed an update to the docs to make sure this is mentioned https://github.com/microsoft/vscode-docs/commit/cf616737f1a32fb99b32483db87cbb176c72b6cd

@setaskin try it out with VS Code insiders next week and let us know what you think. Thanks

**Comment by setaskin** [comment] 2022-05-04 15:58
thank you very much @Tyriar and @isidorn. I will test it next week :)
