### ISSUE TITLE
VS Code debug launch json is not working

### ISSUE THREAD

**Issue by Vineeth4420** [microsoft/vscode#118806] opened 2021-03-12 09:35 UTC
Issue Type: <b>Bug</b>

Hey I am trying to use express app in my project. I was able to debug all this while but after the recent update that is 1.54.2. I am not able to debug the application can someone resolve this soon.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.96GB free)|
|Process Argv|--crash-reporter-id c010e8b0-324a-416a-81a4-cd887df81b21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.5
salesforce-diff|chu|0.0.7
vscode-eslint|dba|2.1.17
gitlens|eam|11.3.0
prettier-vscode|esb|5.9.2
vscode-mocha-test-adapter|hbe|2.10.2
vscode-test-explorer|hbe|2.19.5
vscode-edit-csv|jan|0.5.5
vue|jcb|0.1.5
git-graph|mhu|1.29.0
compare-folders|mos|0.20.2
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
remote-wsl|ms-|0.54.3
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
bitbucket-pull-requests|Ram|0.3.10
vscode-data-preview|Ran|2.3.0
java|red|0.76.0
vscode-yaml|red|0.16.0
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|51.4.0
salesforcedx-vscode-apex|sal|51.4.0
salesforcedx-vscode-apex-debugger|sal|51.4.0
salesforcedx-vscode-apex-replay-debugger|sal|51.4.0
salesforcedx-vscode-core|sal|51.4.0
salesforcedx-vscode-lightning|sal|51.4.0
salesforcedx-vscode-lwc|sal|51.4.0
salesforcedx-vscode-visualforce|sal|51.4.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by Vineeth4420** [comment] 2021-03-12 09:41
"resolveSourceMapLocations": [
    "${workspaceFolder}/**",
    "!**/node_modules/**"
]
Adding this in launch json file and changing type to pwa-node solves it

**Comment by Oliverq755** [comment] 2021-03-12 09:46
@vscode-triage-bot @msftgits @Vineeth4420 

I am facing the same issue while debuging the express app. The sample of Launch.json is attached here. Looking for immediate fix for this issue since its a blocker for debuggers. 

Launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/${internal_link}/app.js"
        }
    ]
}
```

**System Details:**
Windows 10 Pro
Processor: Intel(R) Core(TM) i5-6440HQ CPU
System Type: 64-bit OS, X64-based processor

**VS Code version**: Code 1.54.2

**Comment by connor4312** [comment] 2021-03-12 16:29
Please describe what the issue is you're facing (what does "not able to debug" mean?) and collect a log file

/jsDebugLogs

**Closed** 2021-03-27 11:28 UTC
Labels: debug, needs more info
