### ISSUE TITLE
Really need a way to tell which extension is throwing notifications

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode#33039] opened 2017-08-23 17:13 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.3.10
ng-template|Ang|0.1.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|4.4.0
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.1.1
docthis|joe|0.4.8
angular-essentials|joh|0.2.0
Angular2|joh|2.4.2
MagicPython|mag|1.0.12
easy-less|mrc|1.4.5
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.1.8
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.2.0
vscode-icons|rob|7.12.0
python|tht|0.2.3
gitblame|wad|2.1.0
blade-runner|yuk|1.0.0

(18 theme extensions excluded)

---

I have an extension that is causing a lot of problems. One of them is that it keeps giving me a notification. But I don't know which extension is giving me this notification and is causing the other problems I'm facing. This notification comes at random so I can't reproduce it, nor can I disable the extensions 1 by 1 to find it if it will come again.

![image](https://user-images.githubusercontent.com/791996/29628810-726979ee-87eb-11e7-8014-8b841f52080b.png)

Edit: The above error message appears when I change themes. I can't change themes anymore because by user settings file has been corrupted by some extension. That extension throws an error notification that I submitted an issue for before [here](https://github.com/Microsoft/vscode/issues/31596). 

Reproduces without extensions: No

**Comment by Tyriar** [comment] 2017-08-23 18:03
@AskYous open up your settings file (ctrl+,) and press F8 to go to the next error. You may have left a trailing comma somewhere which is causing all changes to the settings.json file to fail.

**Comment by AskYous** [comment] 2017-08-23 18:11
@Tyriar, trust me. The usersettings file is completely different. It's not even JSON anymore. Here what happens at random times:

1. I'm editing a file, such as app.ts.
2. I change the theme of VS Code.
3. I receive the error posted #31596, and then I receive the notification from the screenshot above.
4. I open my user settings file, and I see the code of my app.ts file was pasted into my user settings file. Literally, I see my typescript code in my user settings file!

I'm confident it's caused by one of the extensions. More specifically, I'm confident it's caused by the extension that gave me the notification I received in #31596. I want to know which extension gave me that notification so I can know which extension to disable. If VSCode simply displays which extension is displaying the notification, I can find out which extension is causing me all these problems.

**Comment by ramya-rao-a** [comment] 2017-08-23 23:45
Until there is a solution from VS Code, try googling the part of the message with `site:github.com` at the end. Thats how I found https://github.com/Microsoft/vscode/issues/31596#issuecomment-324492745

**Comment by ramya-rao-a** [comment] 2017-08-23 23:46
@AskYous In case of #31596, I believe the extension that is giving that error is vscode-JS-CSS-HTML-formatter.

I found this: https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/blob/master/src/extension.ts#L56

**Comment by Tyriar** [comment] 2017-08-24 03:10
If an extension is mangling your settings, there isn't much that can be done other than finding out which one it is. It looks like @ramya-rao-a found where the notification is coming from though.

**Comment by Tyriar** [comment] 2017-08-24 03:11
I misclassified this, I'll move it to @joaomoreno about indicating the source extension for notifications.

**Comment by joaomoreno** [comment] 2017-08-24 08:25
This really seems to be about API call traceability which we never really tacked. @jrieken Do we have an issue for it already?

**Comment by jrieken** [comment] 2017-08-24 09:14
Glad you are asking. For August we have added https://github.com/Microsoft/vscode/issues/32766 and #21302. The latter adds a title/hover to the message showing which extension issued it. The former is about uncaught errors and identifying the extension throwing it.

**Comment by joaomoreno** [comment] 2017-08-24 09:28
Cool. Duplicate of #21302

**Closed by joaomoreno** 2017-08-24 09:28 UTC
Labels: extensions, needs more info, new release
