### ISSUE TITLE
Ctrl+Shift+I not working

### ISSUE THREAD

**Issue by nt4f04uNd** [microsoft/vscode#120380] opened 2021-04-01 20:57 UTC
The entry in the "Help" menu states it should work

![image](https://user-images.githubusercontent.com/39104740/113353278-1557c700-9346-11eb-9f59-45cb62d36bb7.png)

- VS Code Version: 1.55.0, c185983a683d14c396952dd432459097bc7f757f, x64
- OS Version: Windows 10 Pro 2004 19041.867

Steps to Reproduce:

1. press Ctrl + Shift + I

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2021-04-01 21:14
/duplicate of #89587

By default this keybinding is qualified by the `isDevelopment` context which means it only works when running VS Code out of source. If you want it to work unconditionally, use the keybinding editor to remove the when-clause.

**Closed** 2021-04-01 21:15 UTC
Labels: *duplicate, new release

**Comment by nt4f04uNd** [comment] 2021-04-01 21:20
why is this keybinding shown in the context menu entry without actually working?

**Comment by gjsjohnmurray** [comment] 2021-04-01 21:25
See https://github.com/microsoft/vscode/issues/40389#issuecomment-352404326 for an explanation from @alexdima of why `when` clauses don't get checked before menu entry keybindings get displayed.
