### ISSUE TITLE
VSCode doesn't launch if PC is offline or in airplane mode

### ISSUE THREAD

**Issue by sorenhan** [Microsoft/vscode#63790] opened 2018-11-26 16:54 UTC
Issue Type: <b>Bug</b>

Repro 10/10 times. Toggling wifi on fixes it, but disabling it, and problem reoccurs. Repros with all extensions disabled, too.

Actual: when laptop is not connected to wifi, or in airplane mode, clicking on icon, the cursor changes to busy for maybe 1/2 second, then changes back. no other visuals are on screen.

Expected: that the app launches

NOTE: I *think* this is new after I installed the Windows 1809 update.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
m68k|ste|0.0.1

</details>

**Comment by usernamehw** [comment] 2018-11-26 17:47
duplicate of #7570, fixed in Electron 3 #52629

**Closed** 2018-11-26 19:07 UTC
Labels: *duplicate, editor-contrib
