### ISSUE TITLE
CTRL-C copy on nothing clears clipboard

### ISSUE THREAD

**Issue by Habarodix** [Microsoft/vscode#24776] opened 2017-04-14 13:43 UTC
- VSCode Version: 1.11.2
- OS Version: win10

Steps to Reproduce:

1. Store text in clipboard
2. Accidenlaly hit CTRL-C instead of CTRL-V in editor (selected nothing) (empty line)
3. Clipboard content lost

editorHasSelection on kayboard shortcut neither editor.emptySelectionClipboard false setting work

**Comment by rylek90** [comment] 2017-04-14 17:06
I don't think it will be fixed, cause default behavior of CMD/CTRL+C when nothing in line is selected storing whole line in clipboard. So when you're prompt is on empty line this is the expected desired behavior.

**Comment by Habarodix** [comment] 2017-04-14 17:16
Sorry to hear that. I know the current behaviour, but I think it could be fixed easily by inserting only one row into the code: 
**if (!trim(event.selected)) prevent default;**
or something like that.

**Comment by rylek90** [comment] 2017-04-14 17:27
@Habarodix: I think I've managed to define keybinding you're looking for. Simply put it in your keybindings.json file. It'll replace the default behavior. Unfortunately you won't be able to copy the whole line now without selecting it. 
`{
        "key": "ctrl+c",
        "command": "editor.action.clipboardCopyAction",
        "when": "editorTextFocus && editorHasSelection"
    }`

**Comment by Habarodix** [comment] 2017-04-14 18:14
Looks good, but still copies even an empty row without selecting it.
Perhaps editorHasSelection returns true it I stand on a row.

**Comment by Bill-Stewart** [comment] 2017-04-14 19:58
Try setting `editor.emptySelectionClipboard` setting to `false`.

**Comment by Habarodix** [comment] 2017-04-14 20:22
Not works for me I changed issue vscode version exacly to 1.11.2 what I use.

**Comment by ajit-id** [comment] 2017-04-15 08:36
Developers of VS Code always try to do something which is obvious than being smart. Someone asked to redirect to the tab if its opened rather than opening a new tab for a file selected from file explorer, someone from VS Code said that they prefer it to do what's obvious than being smart and closed the issue. I believe your feature may be ignored too.

**Comment by Bill-Stewart** [comment] 2017-04-19 19:36
If you set `editor.emptySelectionClipboard` `false`, VS Code does not copy the current line to the clipboard if nothing is selected. Works just fine for me.

**Comment by Habarodix** [comment] 2017-04-20 09:01
It is set, still copies
![nevtelen](https://cloud.githubusercontent.com/assets/23343025/25222427/b5427f94-25b8-11e7-818b-f5610118050c.jpg)

**Comment by alexandrudima** [comment] 2017-04-26 10:48
`"editor.emptySelectionClipboard": false` was added for this case and it works fine for me on Windows.

@Habarodix Perhaps you have installed some extension that registers a different keybinding for `ctrl+c`. Can you reproduce when launching `code --disable-extensions` ?

**Comment by Habarodix** [comment] 2017-04-26 13:23
Still copies :(

**Comment by Bill-Stewart** [comment] 2017-04-26 14:25
Can't reproduce. The setting works fine for me - when nothing selected, <kbd>ctrl</kbd>+<kbd>c</kbd> does not copy the current line to the clipboard when `editor.emptySelectionClipboard` is set to `false`. Make sure this setting is not configured incorrectly in your `.vscode\settings.json` for the current open folder.

**Comment by Habarodix** [comment] 2017-04-26 14:41
It was in my user setting not in workspace, but finally I found the problem.
This setting and the previous I made
 (USER keyboad stting CTRL - C (editorTextFocus &&editorHasSelection))
are not working together.
I reset the key mapping to default, after that
_editor.emptySelectionClipboard: false_
wors fine. Thanks for you all.

**Closed** 2017-04-26 14:42 UTC
Labels: needs more info
