### ISSUE TITLE
The terminal screen is blank

### ISSUE THREAD

**Issue by NARUTOne** [Microsoft/vscode#43072] opened 2018-02-07 03:35 UTC
![image](https://user-images.githubusercontent.com/18441915/35897202-fa3d4916-0bfa-11e8-9a83-effebbd38866.png)
![image](https://user-images.githubusercontent.com/18441915/35897203-fa830b72-0bfa-11e8-9f75-ceb1b6b51b52.png)

- VSCode Version: 1.19.3   
- OS Version:   win10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by zigang93** [comment] 2018-02-07 03:57
restart vscode or pc agian.. if still same, please reinstall vscode. 
my window 10 vscode version 1.9.3 is working well.

**Comment by Bright0206** [comment] 2018-02-07 06:19
遇到相同的问题,系统是w7

**Comment by physihan** [comment] 2018-02-08 03:09
me too ，win 10

**Comment by Lenic** [comment] 2018-02-08 06:02
same to my workmate.

**Comment by Mandy997** [comment] 2018-02-08 09:04
折腾了半天了 整不了

**Comment by Tyriar** [comment] 2018-02-08 16:54
To get it showing again could you try:

- Hiding and showing the terminal (ctrl+\`, ctrl+\`)
- Resizing the window and back (ctrl++, ctrl+-)

**Comment by NARUTOne** [comment] 2018-02-10 05:27
@zigang93  I tried reinstalling, but still.

**Comment by NARUTOne** [comment] 2018-02-10 05:36
@Tyriar  That not, now I am the lastest version 1.2.0

**Comment by physihan** [comment] 2018-02-10 15:36
revert to last version，reinstall 1.19.2 
the terminal will show again

> 版本 1.19.2
> 提交 490ef761b76b3f3b3832eff7a588aac891e5fe80
> 日期 2018-01-10T15:55:03.538Z
> Shell 1.7.9
> 渲染器 58.0.3029.110
> Node 7.9.0
> 架构 x64

**Comment by imba-tjd** [comment] 2018-02-14 06:24
@Tyriar Duplicate of https://github.com/Microsoft/vscode/issues/43169?
although this one is earlier - -

**Comment by mikejf-pr** [comment] 2018-02-16 04:16
I'm able to induce this issue on Windows by dragging my VSCode window from one screen to another desktop. (if relevant, the screen have different DPI settings)

**Comment by Tyriar** [comment] 2018-02-18 21:39
People in this issue are likely experiencing one of the following issues:

- Terminal on Windows does not show any text #43169
- Dragging vscode maximized from one window to another can hide terminal #42999

**Closed by Tyriar** 2018-02-18 21:39 UTC
Labels: integrated-terminal

**Comment by han88829** [comment] 2018-02-23 01:19
me to win7

1.20
