### ISSUE TITLE
Adding node_modules folder to .vscode directory causes hang

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4781] opened 2016-03-29 22:32 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Open a Node.js project
2. If you haven't already, run npm install to generate the files under node_modules
3. In VS Code drag the node_modules directory to move it under .vscode directory
4. Wait a few seconds then the window will hang.

**Comment by Tyriar** [comment] 2016-04-07 04:29
Can't reproduce, anymore details on a repro?

**Comment by Tyriar** [comment] 2016-04-21 22:52
Closing off as cannot reproduce

**Closed by Tyriar** 2016-04-21 22:52 UTC
Labels: freeze-slow-crash, linux, v-test
