### ISSUE TITLE
Allow me to `x` out of kernels that I don't want

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#172292] opened 2023-01-24 21:28 UTC
Testing #172094

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2644648/214420172-1827a6bf-ef63-413a-92ed-1d1f68cfee58.png">

I added the Global one, and then realized that running a cell involves installing ipywidgets which I don't want to do globally. So now that item in this list is useless and I should be able to `x` it to get rid of it.

similar to MRU in the file picker:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/2644648/214421869-ab849e01-efd9-49c6-8381-9a3517544781.png">

**Comment by DonJayamanne** [comment] 2023-01-24 22:54
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12227

**Closed by DonJayamanne** 2023-01-24 22:54 UTC
