### ISSUE TITLE
[Accessibility] Magnifier Focus Tracking Not Working

### ISSUE THREAD

**Issue by daniahl** [Microsoft/vscode#29253] opened 2017-06-22 07:34 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java|redhat|0.6.0|;

---

For a screen magnifier user, it is important that text editors notify the accessibility API of caret position changes, so that the magnified view can follow the caret while e.g. writing code. This is not the case in VS Code, regardless of the editor.accessibility setting.

Steps to Reproduce:

1. Launch the Windows screen magnifier by pressing Win and +.
2. In magnifier settings, enable caret tracking if it isn't enabled - "have magnifier follow the text insertion point".
3. Open any file in VS Code.
4. Zoom in to say 4X magnification.
5. Type or use the arrow keys to move the caret off the screen.

What happens? The caret continues moving outside the visible magnified view.
What should happen? The magnified view should follow the caret so that it is never off-screen. For an example of correct behaviour, try the steps above in notepad.

**Comment by alexandrudima** [comment] 2017-06-23 06:57
Duplicate of #7394 . Interestingly, Chromium emits the correct accessibility events if a composition based language is used, like Chinese, etc . Please consider filing an upstream issue to Chromium, all the Chrome input boxes and textareas suffer from the same problem.

**Closed by alexandrudima** 2017-06-23 06:57 UTC
Labels: new release
