### ISSUE TITLE
@workspaceUnsupported search shows up too eagerly for fresh installations

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#125322] opened 2021-06-02 18:53 UTC
STR:
- Opening fresh VS Code instance
- Open Extensions in sidebar

STR 2: Same happens when opening a project folder; even though I didn't install any extensions yet.

`@workspaceUnsupported` shows up as default, without much context.

![image](https://user-images.githubusercontent.com/8599/120535499-e686bd00-c397-11eb-91b8-75a3ef907d57.png)

Given that users who freshly open VS Code want to set it up to their needs; not seeing the _Popular_/_Recommended_ sections doesn't help.

**Comment by lramos15** [comment] 2021-06-02 19:29
Not to jump on this issue, but it also remains there when you do trust the workspace and can be jarring why you don't see any extensions.

**Comment by digitarald** [comment] 2021-06-02 20:08
> Not to jump on this issue, but it also remains there when you do trust the workspace and can be jarring why you don't see any extensions.

Right, that one was harder to reproduce when I tried it; but it definitely shows up in many surprising occasions when I am not in a trusted/restricted.

**Comment by IllusionMH** [comment] 2021-06-02 22:17
This is duplicate of #125047 which is already in May 2021 milestone

**Closed** 2021-06-03 15:02 UTC
Labels: *duplicate, workspace-trust
