### ISSUE TITLE
vscode hangs by hitting <tab> in the editor (easily reproducible)

### ISSUE THREAD

**Issue by pavlos256** [Microsoft/vscode#8135] opened 2016-06-25 05:02 UTC
- VSCode Version: 1.2.1
- OS Version: Arch Linux

Steps to Reproduce:
1. Save the following as a .css file:

```
.test {
white-space: pre-line;"
}
```
1. Open the file in vscode.
2. Place the cursor at the beginning of the second line (before white-space).
3. Hit tab.

The editor hangs with 100% CPU on a core, needs kill -9 to die.

I am able to reproduce this every time without failure.

**Comment by rebornix** [comment] 2016-06-25 13:25
Reproduce on Mac with 1.3.0-Insider.

**Comment by dbaeumer** [comment] 2016-06-25 19:29
@aeschli FYI.

**Comment by alexandrudima** [comment] 2016-06-25 20:07
This is not a regression. Also happens in VS Code 1.2.1. Looks like emmet gets stuck in:

`C:\Alex\src\vscode\node_modules\emmet\lib\parser\css.js:186 - function eatString()`

Here are the locals I'm seeing in there, looks like that `while` loop never finishes:

![image](https://cloud.githubusercontent.com/assets/5047891/16358841/24e51e66-3b21-11e6-99b0-e59d99aa4588.png)

**Comment by alexandrudima** [comment] 2016-06-25 20:10
We use emmet@1.3.1. Just checked and emmet@1.3.2 also loops in there indefinitely.

**Comment by miparnisari** [comment] 2016-09-13 14:31
I can reproduce this as well using VS Code 1.5.2 on Windows 10. After 15 seconds I get the "The window is no longer responding" popup.

**Comment by neculaiandrei** [comment] 2016-10-27 08:22
@miparnisari Same here.

**Comment by alexandrudima** [comment] 2016-10-27 09:20
@miparnisari @neculaiandrei It is an issue with emmet -> emmetio/emmet#453

**Comment by pavlos256** [comment] 2016-10-27 09:33
If you don't use emmet, a workaround is to disable tab expansion with:

    "emmet.triggerExpansionOnTab": false

**Comment by gianpaj** [comment] 2017-01-30 16:38
OMG @pavlos256 !! you're a life saver!!

I had trouble with a `file.scss.liquid` file without any VSCode extensions enabled and manually setting the file language to sass. (Mac OSX 10.11.6 - VSCode 1.8.1)

It took days to find this workaround! No stacktrace, just hangs... No idea if there's a way to enable debugging to better find the root cause of this

**Comment by ramya-rao-a** [comment] 2017-02-07 16:57
Fixed with #19655
The upstream emmet library has been fixed. 
The fix will be available in the 1.10 insiders from tomorrow.

**Closed by ramya-rao-a** 2017-02-07 16:57 UTC
Labels: editor, emmet, freeze-slow-crash, important, upstream
