### ISSUE TITLE
My extensions marketplace does not load 

### ISSUE THREAD

**Issue by glezin97** [microsoft/vscode#115713] opened 2021-02-03 20:15 UTC
Issue Type: <b>Performance Issue</b>

I cannot connect to the extensions marketplace and no links on the welcome page work.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>Workspace Info</summary>

```
|  Window (vlads)
|    Folder (vlads): more than 20235 files
|      File types: pyi(8457) py(4102) pyc(2741) dll(243) json(240) txt(161)
|                  svg(103) js(96) toml(79) png(71)
|      Conf files: package.json(19) settings.json(4) launch.json(3)
|                  tasks.json(2) tslint.json(1) makefile(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.3
python-extension-pack|don|1.6.0
code-runner|for|0.11.2
MagicPython|mag|1.1.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.1
jupyter|ms-|2020.12.414227025
python|tht|0.2.3
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8

</details>

**Comment by 2sls** [comment] 2021-02-03 21:38
I have same problem  - just seeing the clock icon endlessly for hours so far.

**Comment by sandy081** [comment] 2021-02-04 13:02
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by 2sls** [comment] 2021-02-04 13:46
I was desperate and rebooted my machine and the problem went away before seeing the instructions from @sandy081 

Before I rebooted, I verified my DNS resolver was working and that there were no network failures in developer mode. 

Will take logs next time if it occurs.

**Comment by glezin97** [comment] 2021-02-06 20:45
My VSCode marketplace just started working after I didn't use it for
several days. My network works absolutely fine and there are no DNS issues.
However, the error messages are still there. When I go to Help --> Toggle
Developer tools --> Console     I get 8 errors, 5 warnings, and 2 info
messages:

  ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory,
stat '/Users/vlads/Desktop/Files/.vscode'
abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use
PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:829
abstractExtensionService.ts:717 [tht13.python]:
'configuration.jsonValidation.url' must be an absolute URL or start with
'./'  to reference schemas located in the extension.
_logMessageInConsole @ abstractExtensionService.ts:660
console.ts:137 [Extension Host] (node:9277) [DEP0005] DeprecationWarning:
Buffer() is deprecated due to security and usability issues. Please use the
Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:112
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for
scope source.python.
Old grammar file:
file:///private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file:
file:///Users/vlads/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ TMScopeRegistry.ts:43
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for
scope source.python.
Old grammar file:
file:///Users/vlads/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage.
New grammar file:
file:///Users/vlads/.vscode/extensions/tht13.python-0.2.3/syntaxes/python.tmLanguage
register @ TMScopeRegistry.ts:43
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for
scope source.regexp.python.
Old grammar file:
file:///private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicRegExp.tmLanguage.json.
New grammar file:
file:///Users/vlads/.vscode/extensions/tht13.python-0.2.3/syntaxes/Regular%20Expressions%20%28Python%29.tmLanguage
register @ TMScopeRegistry.ts:43
console.ts:137 [Extension Host] activate
console.ts:137 [Extension Host] Lintings failed on open
t.log @ console.ts:112
console.ts:137 [Extension Host] File:
file:///Users/vlads/Desktop/Files/hello.py
t.log @ console.ts:112
console.ts:137 [Extension Host] Message: TypeError: Cannot read property
'uri' of undefined
t.log @ console.ts:112
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property
'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'text' of
undefined
at PythonExtension._onChange
(/Users/vlads/.vscode/extensions/tht13.python-0.2.3/out/client/src/pythonMain.js:85)
at l.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
at t.ExtHostDocuments.$acceptDirtyStateChanged
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:735)
at m._doInvokeHandler
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892)
at m._invokeHandler
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892)
at m._receiveRequest
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:891)
at m._receiveOneMessage
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:890)
at
/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:888
at l.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
at v.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233)
at
/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1094
at l.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
at v.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233)
at t.PersistentProtocol._receiveMessage
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238)
at
/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235
at l.fire
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
at p.acceptChunk
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:231)
at
/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230
at Socket.t
(/private/var/folders/y8/y0cdcn3n6h3_j2hvvgsfn56h0000gn/T/AppTranslocation/2C868AEB-D650-4830-B210-4F548C9FB7C5/d/Visual
Studio
Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240)
at Socket.emit (events.js:223)
at addChunk (_stream_readable.js:309)
at readableAddChunk (_stream_readable.js:290)
at Socket.Readable.push (_stream_readable.js:224)
at Pipe.onStreamRead (internal/stream_base_commons.js:181)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
console.ts:137 [Extension Host] rejected promise not handled within 1
second: Canceled: Canceled
t.log @ console.ts:112
console.ts:137 [Extension Host] stack trace: Canceled: Canceled at
E.makeCancelError
(/Users/vlads/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:9:137841)
at
E.handleFailedRequest
(/Users/vlads/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:9:137692)
at
/Users/vlads/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:9:97408
t.log @ console.ts:112


However, when I go as you suggested to View --> Command Palette --> Toggle
Shared Process --> Console    there are no errors, but 47 warnings (please
let me know if I should post it as well).

Thank you sincerely for all your help.

**Comment by sandy081** [comment] 2021-02-09 17:58
Closing this as the issue is not reproducible

**Closed by sandy081** 2021-02-09 17:58 UTC
Labels: needs more info

**Comment by glezin97** [comment] 2021-02-09 20:00
I’m sorry, what do you mean not reproducible?

**Comment by sandy081** [comment] 2021-02-10 07:05
I mean it is working again and there are no steps to repro. If you see it again I would request to provide the logs I asked for.

**Comment by glezin97** [comment] 2021-02-10 07:07
Okay. Thank you so much for all your help.
