### ISSUE TITLE
NPM Scripts always visible

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#79700] opened 2019-08-23 09:56 UTC
Issue Type: <b>Bug</b>

Even if I uncheck enableScriptExplorer in settings, the NPM Scripts panel keeps remaining visible. I don't use it and it makes me have to take care where to click when I want to open another panel in the sidebar.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
favorites|kdc|2.4.5
vetur|oct|0.22.2

</details>

![image](https://user-images.githubusercontent.com/3931907/63584340-67027200-c5a5-11e9-863c-af78b57673c6.png)

**Comment by mattacosta** [comment] 2019-08-24 02:34
Duplicate of #78489.

**Comment by egamma** [comment] 2019-08-27 06:29
This is an intended recent change to improve discoverability of the npm explorer, pls see https://code.visualstudio.com/updates/v1_37#_npm-scripts-explorer-visible-by-default. The npm explorer is now shown when: `package.json at the root of the workspace || setting is enabled`. To hide the npm script explorer in a workspace that has a package.json at the root you can do so from the context menu. See below:

![image](https://user-images.githubusercontent.com/172399/63746027-007e9c00-c8a4-11e9-9793-ca5d43a06b37.png)

**Closed by egamma** 2019-08-27 06:29 UTC

**Comment by csicky** [comment] 2019-08-27 08:27
I understand, but it was not done properly. When enabling it by default the checkbox should have been set to true for everybody and unchecking it should have hide it as expected. What was done was actually a hack, an ugly hack.

**Comment by egamma** [comment] 2019-08-27 19:47
>When enabling it by default the checkbox should have been set to true for everybody and unchecking it should have hide it as expected. 

This is not correct, we did intentionally **not** want to enable the script explorer in all workspaces, but only in workspaces that have a 'package.json' at the root. If would have changed the default of the setting to true, then the script explorer would be always visible. This is something we absolutely do not want, think of a python developer that uses VS Code.

>What was done was actually a hack, an ugly hack.

I'm sorry if you do not like it, but the feedback from many users that have discovered the npm script explorer is really positive. Can you elaborate what you provide more details about what you do not like about it?

**Comment by csicky** [comment] 2019-08-27 20:38
There is a setting named enable script explorer. This was intended to show
or hide the panel. Regardless of package.json or not, that checkbox should
be the one controlling the visibility of the panel. If you enabled it for a
group of users based on some reasons, that checkbox should have been
checked from that point on for those users. And unchecking it should have
worked to hide the panel. It's that simple. Instead the checkbox is made
irrelevant and some other things make the panel visible or not. Right click
and hide also doesn't seem to affect the checkbox. I can't see it otherwise
than a hack or a bug what happened. The only thing left is to simply remove
the checkbox as it does nothing.

The feedback being positive or not for the script explorer, doesn't change
that the checkbox became useless.

It doesn't matter how we hide it, what I don't like is misleading UI. A
checkbox telling me it will hide something and failing to do that.

**Comment by egamma** [comment] 2019-08-27 20:56
>It doesn't matter how we hide it, what I don't like is misleading UI.

i agree on this one, I'll adjust the description of the setting so that it is consistent with the new behaviour. Thanks for pointing this out.
