### ISSUE TITLE
Add multi-select to Quick Pick extension API

### ISSUE THREAD

**Issue by SiXoS** [Microsoft/vscode#22853] opened 2017-03-19 14:34 UTC
It would be nice there was a QuickPickOption that enables the user to select multiple items by, for example, holding shift while navigating the item list or control-clicking items. This would be very useful for extensions which can generate getters/setters among others.

**Comment by jrieken** [comment] 2017-03-20 07:56
dupe of #238

**Closed by jrieken** 2017-03-20 07:56 UTC
Labels: api, feature-request
