### ISSUE TITLE
Slow Startup Performance

### ISSUE THREAD

**Issue by douglasparker** [microsoft/vscode#111328] opened 2020-11-25 22:31 UTC
VSCode has had really slow startup performance for many months now and I am not sure why.

## System Info
* Code: 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f)
* OS: win32(10.0.19042)
* CPUs: AMD Ryzen 7 2700X Eight-Core Processor         (16 x 3693)
* Memory(System): 63.92 GB(39.08GB free)
* Memory(Process): 160.19 MB working set(137.55MB private, 0.96MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Attachments
* [Startup Performance.txt](https://github.com/microsoft/vscode/files/5599528/Startup.Performance.txt)
* [prof-80be.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/5599518/prof-80be.extHost.cpuprofile.txt)
* [prof-80be.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/5599519/prof-80be.main.cpuprofile.txt)
* [prof-80be.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/5599520/prof-80be.renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2020-11-26 07:51
> | start => app.isReady                                            | 6720     | [main]           | initial startup: true     

This seems to be a problem with `appReady` which sometimes is delayed. Often AV software is causing this.

**Comment by jrieken** [comment] 2020-11-26 07:51
closing as duplicate of https://github.com/microsoft/vscode/issues/22087

fyi @deepak1556

**Closed by jrieken** 2020-11-26 07:51 UTC
Labels: perf-startup

**Comment by douglasparker** [comment] 2020-11-26 17:05
> > | start => app.isReady                                            | 6720     | [main]           | initial startup: true
> 
> This seems to be a problem with `appReady` which sometimes is delayed. Often AV software is causing this.

@jrieken, I only use Microsoft Defender. I disabled all of the following:

- Real-time protection
- Cloud-delivered [protection
- Automatic sample submission
- Tamper protection

Yet the startup performance is still awful. Please reopen this issue as it seems completely unrelated to AV software. Thank you.
