### ISSUE TITLE
 Cannot escape out of the search sidebar anymore

### ISSUE THREAD

**Issue by bruceoberg** [microsoft/vscode#76428] opened 2019-07-01 20:44 UTC
Issue Type: <b>Bug</b>

I want the Escape key to close the sidebar if it's open. Long ago (January 2018?) I added this shortcut key to do this:

```
{
    "key": "escape",
    "command": "workbench.action.toggleSidebarVisibility",
    "when": "sidebarVisible"
}
```
It worked great... for a while. As of today, this shortcut no longer works. I believe it's been broken since the Fall 2018 release.
I don't care about this specific shortcut... I just want to be able to close the sidebar with the Escape key. How can I do that?

UPDATE: The sidebar I'm mostly trying to escape from is the Search sidebar, not the workspace explorer sidebar. This used to work and now it doesn't.

UPDATE 2: the problem is that the `"sidebarVisible"` context was renamed to `"sideBarVisible"`. using the new name fixes the problem. but seriously vscode team, why rename something like this?

VS Code version: Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment] 2019-07-03 07:59
It works for me.
Just if the focus is in the tree, the first escape will clear the focus. And only the second escape will execute your command.
This happens because the tree is eating up the first escape key and this can not be customisable.
Thus forwarding this issue to @joaomoreno though I think we can close this as designed.

@bruceoberg I suggest that you simply use a different shortcut which is not already taken by the tree.

**Comment by bruceoberg** [comment] 2019-07-03 18:39
i am most concerned with the search sidebar, not the explorer sidebar/tree control. my shortcut used to work there and does not anymore.

**Comment by joaomoreno** [comment] 2019-07-04 06:55
We can (maybe) make <kbd>Escape</kbd> a contributable tree command instead of hardcoding it.

**Comment by bruceoberg** [comment] 2019-07-05 01:33
please remember that this is about escaping from the search sidebar, not from the workspace explorer.

**Comment by charliedua** [comment] 2019-07-11 00:15
# Reproduce the problem
Tried to Check if the Search sidebar looses focus on `escape` keypress.

- [x] Can confirm the focus retains in the search bar ever after multiple keypresses.

# Problem 
The problem is with how you have written the json file as the toggle doesn't require a when condition and hence removing it should fix the problem

# Solutiion
The new json looks like this and works. 
```json
{
    "key": "escape",
    "command": "workbench.action.toggleSidebarVisibility",
}
```

# Feedback
Please tell if this fixes your problem!

**Comment by bruceoberg** [comment] 2019-07-16 00:29
the `"when": "sidebarVisible"` clause is necessary because i don't want escape to reopen the sidebar if it is not open. i want escape with no sidebar to do nothing. there does not appear to be a "hideSidebar" command that does not toggle. this used to work and was broken.

**Comment by bruceoberg** [comment] 2019-07-16 01:02
and... the real problem is that `"sidebarVisible"` was renamed to `"sideBarVisible"` (note the capital B). the predicate names are case sensitive, and thus my shortcut was broken. with the new spelling it works again.

hey vscode team... don't rename `"when"` predicates!

**Closed** 2019-07-16 01:05 UTC
Labels: feature-request, help wanted, tree

**Comment by isidorn** [comment] 2019-07-29 12:52
Sorry about that!
Yes we renamed it, ti was mentioned in the release notes (I believe)

**Comment by bruceoberg** [comment] 2019-07-29 20:26
@isidorn, this is a classic case of why it is a very bad idea to rename things in passive environments (where misnamed items fail silently). you believe it was mentioned in the release notes. this is simply not good enough for a widely used product. the thing is, when my shortcut stopped working, _i did not know why_. to find out why, i had to troubleshoot it, ask for help, waste others time, and then finally stumble upon what had actually happened. all because someone thought one lower case b should be capitalized. i'm glad you're sorry about that. in the future, the vscode team should try to avoid making changes that silently break things.

**Comment by cb109** [comment] 2019-08-27 15:00
For anyone coming across this, this is the full keybinding (add to your `keybindings.json`) that will close the sidebar when pressing escape:
```json
    {
        "key": "escape",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "sideBarVisible"
    }
```
