### ISSUE TITLE
File associations

### ISSUE THREAD

**Issue by axelriet** [Microsoft/vscode#7637] opened 2016-06-14 02:12 UTC
With VSCode installed, both *.cs and *.xml are shown in Explorer as being of type "Visual Studio Code", so when sorting by type, XML and *.cs files are mixed up. Rinse and repeat with other formats I presume.

No, no, no.

Please fix that.

File associations has plagued Windows for more than 3 decades and still does... :-(

**Comment by rebornix** [comment] 2016-06-14 04:11
On my machine, the cs files are still using the system default icons instead of Visual Studio Code even if I installed both latest stable and nightly-build version. Wait for others' observation.

**Comment by sandy081** [comment] 2016-06-14 11:25
On Mac, I see them with Visual Studio Code icon. I am not sure if there is a setting for this.

**Comment by sandy081** [comment] 2016-06-14 11:28
@joaomoreno assigning this to you, assuming it is related to installation scripts. Please re-assign if you don't think so.

Thanks

**Comment by joaomoreno** [comment] 2016-06-14 13:46
Duplicate of #7196

**Closed by joaomoreno** 2016-06-14 13:46 UTC
