### ISSUE TITLE
Cannot set font 'JetBrains Mono'

### ISSUE THREAD

**Issue by bedo2991** [microsoft/vscode#212015] opened 2024-05-04 10:10 UTC
Type: <b>Bug</b>

Install the [JetBrains Mono](https://www.jetbrains.com/lp/mono/#how-to-install) font, restart VS-Code.

Set in User\settings.json
```
    "editor.fontFamily": "'JetBrains Mono', Consolas, 'Courier New', monospace",
    "editor.fontWeight": "300",
    "editor.lineHeight": 22,
    "editor.smoothScrolling": true,
    "editor.fontSize": 13,
    "editor.fontLigatures": true,
```

**Result:** the editor keeps using Consolas (the 0 have a cut inside them, they should have a dot).

**Expected:** the editor should use "Jetbrains Mono".

**Additional notes:** Restarting VS-Code does not help. Placing other Font Families after 'JetBrains Mono' like *Georgia* switches to that Font upon saving, so the configuration item is currently in use.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|29.89GB (13.53GB free)|
|Process Argv|--crash-reporter-id 1fee1463-9d9e-448a-a2d4-9bf856129579|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-model-snippets|ahi|2.0.0
laravel-extra-intellisense|ami|0.6.5
laravel-blade-spacer|aus|2.3.0
livewire-switcher|beb|0.1.1
vscode-intelephense-client|bme|1.10.4
livewire-vscode|cie|0.2.8
laravel-goto-view|cod|1.3.11
dbclient-jdbc|cwe|1.3.5
vscode-database-client2|cwe|7.3.1
vscode-eslint|dba|2.4.4
phpunit|ema|4.16.1
copilot|Git|1.186.0
copilot-chat|Git|0.15.0
npm|ide|1.7.4
latex-workshop|Jam|9.20.1
livewire-goto-updated-3|m4t|1.2.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.4.1
remote-containers|ms-|0.362.0
remote-wsl|ms-|0.88.2
php-docblocker|nei|2.7.0
laravel-blade|one|1.36.0
laravel-pint|ope|1.2.0
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.24.2
svelte-vscode|sve|108.4.1
pretty-ts-errors|Yoa|0.5.4
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by rzhao271** [comment] 2024-05-06 22:20
Potential duplicate of https://github.com/microsoft/vscode/issues/173543. Let me know if that thread mitigates your issue.

**Comment by rzhao271** [comment] 2024-05-08 22:19
Marking this issue as a duplicate of #173543.

Thanks for the clarification that installing the fonts system-wide works; I might have been confusing user-installed font with third-party font.

**Closed by rzhao271** 2024-05-08 22:19 UTC
Labels: info-needed
