### ISSUE TITLE
Search is not working properly -> spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by andywillekens** [Microsoft/vscode#49896] opened 2018-05-15 11:43 UTC
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro 

Steps to Reproduce:

1. Right click on Folder
2. Click 'Find in folder'
3. Search for something
4. spawn ENAMETOOLONG

![search__spawn-enametoolong](https://user-images.githubusercontent.com/5364383/40054620-cbd3cd92-5845-11e8-948e-7a8251d61a6c.gif)

Does this issue occur when all extensions are disabled?: Yes, in the preview above, i have alle extensions disabled. 

*UPDATE 15-05-18*

As seen in the preview, I have a lot of Project folders in my workspace. When searching it uses ./[projectname]/. to search in that project folder, wich returns the 'spawn ENAMETOOLONG' error message.

When I remove the project folder + /. at the end, it works but searches every project folder within the workspace...

**Comment by mjbvz** [comment] 2018-05-15 18:18
Duplicate of #39406

**Closed by mjbvz** 2018-05-15 18:18 UTC
Labels: new release

**Comment by roblourens** [comment] 2018-05-15 18:36
This should probably be fixed by https://github.com/Microsoft/vscode/issues/49928 which I'm working on this month.
