### ISSUE TITLE
Command palette search

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#1147] opened 2015-12-09 19:51 UTC
~~When searching the command palette, the search is based in exactly what you type, In essence, Code is checking if what's been typed is a substring of the command title.~~

It would be great if the command palette search were a bit more fuzzy, i.e. based on the individual words that are input, ignoring punctuation, etc.

Atom's command palette search works in this way:

![atom](https://cloud.githubusercontent.com/assets/2899448/11696714/054c5f40-9eb6-11e5-84b9-ed2b2eacbb11.png)

This would resolve an issue raised on one of my extensions: wmaurer/vscode-change-case#3, and provide a much nicer user experience.

EDIT: I've been playing with it more, and in fact Code's search is a bit fuzzier than I had thought, however it's not fuzzy enough. To be honest I can't even figure out the rules, sometimes a search matches something and then I try something similar and it doesn't match.
In any case, it would be great if it could be improved to approach Atom's level of fuzziness. For example with my change-case plugin, I would expect a search for *case sep* to find the a number of commands, but it doesn't.

**Comment by egamma** [comment] 2015-12-09 20:43
Duplicate of #968

**Closed by egamma** 2015-12-09 20:43 UTC
