### ISSUE TITLE
Ability to Customize Action Bar

### ISSUE THREAD

**Issue by Kenobi-the-2nd** [microsoft/vscode#133017] opened 2021-09-13 17:57 UTC
Good afternoon,

I frequently use custom buttons in the action/context toolbar in VS Code for file specific operations. For example, the [Shortcut Menu Bar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar) extension allows adding these custom buttons mapped to specific commands. It's an excellent feature that allows me to have button shortcuts for common commands such git repo file diffs, remote server diffs, run w/ debug, run w/o debug, and so forth. 

![image](https://user-images.githubusercontent.com/60623875/133129956-2035691b-2094-4283-bb64-ee772c5ffb18.png)

However, there are a couple of issues with the current action bar. One, as shown in the above screenshot, is that the built-in buttons like the git diff (far left) and split editor right (far right) cannot be removed. I don't need either of these buttons on the bar, which leads to the second issue. The maximum number of buttons allowed seems to cap at 9. I would like to increase it beyond this so that I can add more buttons. I realize the 9 button limit may be in the interest of still being able to display all the buttons at minimum editor width, but one solution to this would simply be to hide any buttons in excess of the 9 in the "More Actions..." dropdown at the far right. 

As other users have mentioned, I feel that the ability to customize the action bar is a significant feature since we already have the ability to customize other toolbars in the editor, such as the status bar, activity bar, terminal toolbar, and title/menu bar. Many users also appear to want the functionality to hide the action toolbar entirely (mentioned in #46403), which is also currently possible with the other toolbars. I can understand this from a minimalistic perspective and can see how this would be useful for eliminating any distracting UI features during a code review or presentation, for example. I believe this feature to hide the action bar would also fall under this request since it relates to toolbar customization. 

It would be very nice to have the ability to customize this bar and would make perfect sense, considering all the other toolbars are customizable. 

Thank-you for your time and all the thought and effort that you put into this tool. Please let me know if there are any questions! 

Thanks!

**Comment by sbatten** [comment] 2021-09-13 19:55
sounds like a dupe of https://github.com/microsoft/vscode/issues/46403

**Closed by sbatten** 2021-09-13 19:55 UTC
