### ISSUE TITLE
Output panel grabs focus when tsc is restarted

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12821] opened 2016-09-27 20:53 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

Related to #12814

I've had the integrated terminal open when I copied a .ts file in the workspace and that triggered a restart of tsc. At that point the Output panel grabed focus which is unexpected since I loose my context.

**Comment by dbaeumer** [comment] 2016-09-28 07:33
@isidorn assigning to you. All I do is to log stuff in the output panel via append line.

**Comment by isidorn** [comment] 2016-09-28 09:41
@dbaeumer please give me code pointer or @chrmarti reproducable steps
@dbaeumer are you sure you are not calling outputChannel.show() since I see 5 calls to that method in [tasks.contribution](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L218)

**Comment by dbaeumer** [comment] 2016-09-28 14:06
@isidorn yes I am pretty sure I call show(). Does that grab focus ?

**Comment by dbaeumer** [comment] 2016-09-28 14:14
I test this on my machine and I can't reproduce this. Here is what I see (watch the task spinner in the lower left corner which indicates the restart).

![cast](https://cloud.githubusercontent.com/assets/1931590/18916960/9bbe741e-8596-11e6-8485-7553394d1fdd.gif)

However if the copied file causes error output by the tsc compiler the Output window comes to front since in your tasks.json you configure `"showOutput": "silent"` which means 'show output if there are errors'. If you never want to see output set the setting to "never".

**Comment by dbaeumer** [comment] 2016-09-28 14:15
@isidorn sorry for bothering you. Got misleaded by grabs focus. Feel free to close if you think there is no focus problem.

**Comment by isidorn** [comment] 2016-09-28 14:17
[Show()](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputServices.ts#L79) takes a preserveFocus as an argument - so just pass true if you want to not pass focus

**Comment by chrmarti** [comment] 2016-09-28 14:47
See #12814 for the setup I'm seeing this. I was surprised when it switched from the Terminal to the Output panel because I was reading something in the Terminal. Maybe just a side-effect of #12814? That seems to restart tsc.

**Comment by dbaeumer** [comment] 2016-09-28 18:45
Correct the steps #12814 cause this. I think we need to go over all the output channel usages as soon as we have the panel switchers with the badges. The reason why we bring panels in front right now is that there is otherwise no indication that output happened. 

 @bpasero, @isidorn would it make sense to open an issue that everybody goes over their show calls. Most of them might not be needed anymore. Even strongly we should not have them anymore.

**Comment by dbaeumer** [comment] 2016-09-28 18:45
Move to October to correct the show in task land.

**Comment by bpasero** [comment] 2016-09-29 05:16
I also filed Pull Requests to ESLint and TSLint to correct their `show` calls to not steal focus. Focus should only be taken when the user triggers the action to make the output panel visible. Though, on a second thought I wonder if the output panel should ever take focus since it does not allow for input...

**Comment by dbaeumer** [comment] 2016-09-29 07:49
Agree that most of the show commands should go away except when user clicks actively on something to open the Output.

**Closed** 2016-10-26 17:17 UTC
