### ISSUE TITLE
Jupyter Notebook creates a .txt file - and doesn't let me save as .ipynb. Manually creating a .ipynb file doens't open a jupyter notebook. 

### ISSUE THREAD

**Issue by MindlessMachine** [microsoft/vscode#130948] opened 2021-08-14 11:03 UTC
## Environment data

-   VS Code version: 1.59.0
-   Extension version (available under the Extensions sidebar): Python v2021.8.1105858891, Jupyter v2021.8.1195043623
-   OS and version: Windows 10 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6 64bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour
Using command palette  'Jupyter: Create blank new Jupyter notebook' it should open a .ipynb file with all the features of a jupyter notebook.

(source: https://code.visualstudio.com/docs/datascience/jupyter-notebooks) 
![image](https://user-images.githubusercontent.com/88911526/129444262-6e261dba-1f30-4dd7-a461-b3712bddb191.png)

## Actual behaviour
Using command palette 'Jupyter: Create new blank notebook' it opens a jupyter notebook with all the features and the proper jupyter notebook layout, but with extension .txt.

![image](https://user-images.githubusercontent.com/88911526/129443573-88ce95ba-1ab7-4436-a15d-4734044b6461.png)

I tried to save it as .ipynb and returns this error and don't let me save it:

![image](https://user-images.githubusercontent.com/88911526/129444204-154d185b-e416-4eae-b65f-122e02ac3941.png)

When I create a file manually with 'filename.ipynb' it creates a file with the jupyter icon, but without all the features of a jupyter notebook.. it is a simple plain script file like a .py file. 

![image](https://user-images.githubusercontent.com/88911526/129443586-ee94baa5-d23c-4018-9745-8802fc1c01a3.png)

I already have done a lot of web search looking for some solution, but without success.

already tried reinstall vscode and downgrade some versions of the python and jupyter extensions, but all without success.

Any help to solve this would be appreciated.

**Comment by kateus65** [comment] 2021-08-17 09:36
@MindlessMachine if you are as annoyed but this as I am, I managed a work around to open existing .ipynb files- 
uninstall everything vscode cleaned all .vscode files everywhere.
Installed vscode version 1.58.2 (June). 
Then make sure that the auto-update is **switched off** - set to manual in the dropdown menu before you do anything else. 
Then install your extensions but roll back the Jupyter extension to v2021.6.999406279

I can now open my notebooks as before, and save them as before. 
However, creating a new .ipynb and saving it in vscode seems not to work:
"Unable to open 'Hellooooo.ipynb': Cannot register more than one working copy with the same resource vscode-notebook:file:///filepathfilepath/Hellooooo.ipynb and type." 

This may be a whole separate issue from the old version and is too much for me to investigate right now
so perhaps my work around wont help you :( sorry. 

I will wait to update to the latest version until this is fixed

**Comment by MindlessMachine** [comment] 2021-08-18 18:01
thank you @kateus65, it seemss a great turnaround,
let's see what the vscode/jupyter developers has to say about this and we hope they come with a solution or a update fix for this issue.

**Comment by rebornix** [comment] 2021-08-18 19:45
this is a duplicate of https://github.com/microsoft/vscode/issues/131040 and we have a fix for it coming soon.

**Closed by rebornix** 2021-08-18 19:45 UTC
Labels: notebook-ipynb
