### ISSUE TITLE
Editor not showing up 

### ISSUE THREAD

**Issue by RustyRaptor** [Microsoft/vscode#37787] opened 2017-11-07 21:29 UTC
![Screenshot](https://i.imgur.com/kVpoEpa.png)

- VSCode Version:

Version 1.19.0-insider
Commit 432b53bc3a263fda8db6ecca83d1ce89ede04bf2
Date 2017-11-06T06:22:36.757Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.7 (Gtk 2.24.30) dm: mdm Distro: Linux Mint 18.1 Serena

Steps to Reproduce:

1. Update to latest VS code Insiders edition as of this post
2. Open the application.

Reproduces without extensions: Yes 

It does this with any file I try to open unless the file is already empty.

**Comment by RustyRaptor** [comment] 2017-11-07 21:33
reinstalling with apt has not fixed this issue.

**Comment by bpasero** [comment] 2017-11-08 06:49
@alexandrudima I suspect this is a duplicate of uglify-js issue from yesterday.

**Comment by alexandrudima** [comment] 2017-11-13 15:28
Dup of #37698

**Closed by alexandrudima** 2017-11-13 15:28 UTC
