### ISSUE TITLE
Tab groups request

### ISSUE THREAD

**Issue by gokhanozgezer** [microsoft/vscode#87060] opened 2019-12-16 07:32 UTC
Hi,
When I open most tab does not fit on top and I'm getting lost between tabs
some times my files have same name.

My Request : 

If I open lot of tab I want tab groups like windows taskbar.

maybe groups by folder name
like this : 

----------------------------------------------------------------------------

components 
-> filters.js
 -> slider.js
-> cart.js

----------------------------------------------------------------------------

middleware 
-> seo.js
-> func.js

----------------------------------------------------------------------------

plugins 
-> bus.js
-> mask.js
->validate.js

**Comment by RMacfarlane** [comment] 2019-12-16 15:49
Duplicate of https://github.com/microsoft/vscode/issues/38889

**Closed by RMacfarlane** 2019-12-16 15:49 UTC
