### ISSUE TITLE
Problem with Unicode in Terminal of Visual Studio Code

### ISSUE THREAD

**Issue by theuserbl** [microsoft/vscode#212832] opened 2024-05-15 18:46 UTC
In Visual Studio 1.89.1 on Windows 21H1 Build 19043.1526 this file is wrong shown in terminal:
https://gist.githubusercontent.com/PhMajerus/3467813988c0bbff9de0e67e538d0206/raw/5539303c172ca0df82e1e87f3b5015d97ac7ca32/Demo%20screen.txt

For it is needed to install Cascadia Code 2404.23:
https://github.com/microsoft/cascadia-code/releases/tag/v2404.23
(on that side you can also see a screenhsot, where the "Demo screen.txt" file is displayed corrent)

Then go in Visual Studio Code on the left bottom to the "Manage" icon and select "settings".
Under ""Text Editor" -> "Font" change Font Family from "Consolas, 'Courier New', monospace" to "Cascadia Mono".

Then you can see the right font displays some parts right. But at the end it looks wrong.

<img width="918" alt="UnicodeVSCs" src="https://github.com/microsoft/vscode/assets/8337032/02b70735-1b0d-49d9-a46f-d4a15f3c913a">

In Windows-Terminal 1.19.11213.0 with used Cascadia Mono 2404.23, then it shows all right.
And in the terminal of Ubuntu, it shows it right, too, if Cascadia Mono 2404.23 is selected as font.

**Comment by meganrogge** [comment] 2024-05-15 19:24
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by theuserbl** [comment] 2024-05-15 19:35
No, don't help.
I have tested with "auto", "on", "off" and "canvas".
With "off" the font is widen a little but. But all other is exactly the same.

**Comment by Tyriar** [comment] 2024-06-03 17:51
What it looks like on macOS:

<img width="665" alt="Screenshot 2024-06-03 at 10 50 42 AM" src="https://github.com/microsoft/vscode/assets/2193314/5d09a53a-6524-41aa-a6ef-402ad6fe03a8">

This means that it's an issue with Conpty advancing the cursor the wrong amount. So you'll have to wait for the conpty component to be updated in Windows 11 to see this fixed.

**Comment by Tyriar** [comment] 2024-06-03 17:51
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue).

/label terminal terminal-conpty windows

**Closed by Tyriar** 2024-06-03 17:51 UTC
Labels: info-needed, terminal-rendering
