### ISSUE TITLE
deleting  folder wrongly disappears when permission is denied

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#61620] opened 2018-10-23 14:08 UTC
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Open a file in a folder on windows in such a way that you can't delete it. Or run an exe in that folder that does nothing
2. In vs code delete the folder.

The folder disappears in the explorer side panel but is still there on the file system. VS Code should popup a message box with an error such as permission denied.

Additionally VS Code was holding on to a file even after I closed it which prevented me from deleting it. I had to close VS Code and only then I could delete the file.

**Comment by bpasero** [comment] 2018-10-24 06:03
@graph there should be a notification in the lower right corner when delete fails, no?

**Comment by bpasero** [comment] 2018-10-24 06:04
@isidorn in this case the folder should maybe come back and not stay hidden. So, if delete fails, I guess we should refresh the explorer to show the thing again.

**Comment by isidorn** [comment] 2018-10-24 11:00
Somewhat connected to https://github.com/Microsoft/vscode/issues/43819
@bpasero is there some way to repro this on the mac. What is the easiest to make the file readonly on win so I repro?

**Comment by graph** [comment] 2018-10-24 11:57
On windows if you do fopen or the like on a file you can't delete it until fclose, or make an exe with infinite loop and run it. On mac you can change the permission to 600 and change the user to a different user like root.

**Comment by bpasero** [comment] 2018-10-24 16:04
I take it back, this is an issue with the Electron API not giving a proper return code for [`shell.moveItemToTash`](https://github.com/Microsoft/vscode/blob/2086ab0fc77b19ab7eb3e278bcc08ea6e3367b8e/src/vs/workbench/services/files/electron-browser/fileService.ts#L912). To reproduce:
* open a folder in the command prompt
* open the parent folder of that folder in a Code window
* delete that folder
* => it seems to work, but after a refresh of the explorer the folder is back

If you do the same with Shift+delete (delete permanently) you correctly get this experience:

![image](https://user-images.githubusercontent.com/900690/47441847-60eb0b80-d7b1-11e8-8611-edd21232cd23.png)

I have filed https://github.com/electron/electron/issues/15370

**Comment by bpasero** [comment] 2018-10-24 16:04
Duplicate of https://github.com/Microsoft/vscode/issues/43819

**Closed by bpasero** 2018-10-24 16:04 UTC
Labels: file-explorer, needs more info, windows
