### ISSUE TITLE
Extensions Commands Missing/Confusion from Marketplace (again). Support ext inst

### ISSUE THREAD

**Issue by HCanber** [Microsoft/vscode#18151] opened 2017-01-05 11:57 UTC
- VSCode Version: 1.8.1
- OS Version: OSX 10.11.6

The same problem as in #8024 (that was fixed and closed) but problem remains or has come back. Also see #7973

> 1. Marketplace has guidelines for installing i.e. type `ext inst...`
> 2. In the marketplace copy the link and guidance to install i.e.
> Cmd+P and paste
> 3. commands are missing so does nothing - need to add them back
>
> ![example](https://cloud.githubusercontent.com/assets/1051190/16284664/231b1faa-3887-11e6-986e-49e9774156d3.png "Example")

See https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs as an example

**Comment by sandy081** [comment] 2017-01-05 13:21
This looks to me a duplicate of #7973. As expected this will redirect to the extension viewlet and shows extensions with given name. But confusion is

- Viewlet shows more than one extension
- This command does not install the extension

@joaomoreno FYI

**Comment by joaomoreno** [comment] 2017-01-05 13:39
`ext install` is still supported. Although it's not ideal nor it is exact.

If you press <kbd>F1</kbd>, paste `ext install vscode-standardjs` and hit Enter, you will get a list of extensions which come back from querying the marketplace with `vscode-standardjs`.

One thing we can do is introduce a special syntax (ie `@id:vscode-standardjs`) which would make the viewlet only show extensions with that specific ID/name.

**Comment by joaomoreno** [comment] 2017-01-05 14:35
Sorry, I meant <kbd>Cmd P</kbd>, not <kbd>F1</kbd>.

**Comment by HCanber** [comment] 2017-01-05 15:26
Pretty sure I tried that as well, but apparently I didn't. :/
`ext inst ...` works as explained: it lists matching extensions. So from that point of view this issue could be closed.

It would, however, be better if marketplace could list the id under installation instructions, e.g. `ext install @id:chenxsan.vscode-standardjs` and when invoked, VSCode would show only the extension, or preferably, install it.

A link that can be clicked directly in marketplace, as mentioned in #7973, to install an extension would be even better. :)

**Comment by joaomoreno** [comment] 2017-01-05 16:29
@HCanber We did do some work to improve the driving from the Marketplace into VS Code itself, with a single click, but ended up postponing due to some issues. It can be revived in the future.

I'll close this one then.

**Closed by joaomoreno** 2017-01-05 16:29 UTC
Labels: bug, marketplace
