### ISSUE TITLE
spawn UNKNOWN when Find in files

### ISSUE THREAD

**Issue by LeThiHyVong** [Microsoft/vscode#37872] opened 2017-11-09 04:46 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
Bookmarks|ale|0.17.0
code-gnu-global|aus|0.2.2
macros|ged|1.2.1
gc-excelviewer|Gra|1.1.15
CppSnippets|har|0.0.13
output-colorizer|IBM|0.1.2
auto-comment-blocks|kev|1.0.1
cpptools|ms-|0.14.0
material-icon-theme|PKi|2.2.4
reloaded-cpp|rel|0.1.6
partial-diff|ryu|0.4.1
surrounding|sif|1.4.0
vscode-fileutils|sle|2.7.1

(1 theme extensions excluded)
![untitled](https://user-images.githubusercontent.com/19317679/32588785-991a83ea-c543-11e7-89d5-327acf92da25.png)

---

Steps to Reproduce:

1. Press CTRL+SHIFT+F to open File in Files pane
2. Enter any search string and press Enter

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-11-09 06:42
Dupe of #37863

**Closed by roblourens** 2017-11-09 06:42 UTC
Labels: search
