### ISSUE TITLE
Pills in user question that has already happened should also have the context menu of the pills in a response

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#229634] opened 2024-09-24 22:19 UTC
Testing #229436

<img width="392" alt="image" src="https://github.com/user-attachments/assets/7f445199-0a11-4344-bd71-dcd1f0a4c35d">

look at the context menu of this file reference I asked for.

Now look at it from the model response:
<img width="369" alt="image" src="https://github.com/user-attachments/assets/cbb37178-34fb-464b-aae6-4cb1a6f7316f">

They should include the same things (or at least most of the same)

**Comment by mjbvz** [comment] 2024-09-26 20:20
Duplicate of #228993

**Closed by mjbvz** 2024-09-26 20:20 UTC
