### ISSUE TITLE
New VSCode auto rename tag not typing after delete

### ISSUE THREAD

**Issue by danicunhac** [microsoft/vscode#112359] opened 2020-12-12 13:45 UTC
Issue Type: <b>Bug</b>

When renaming an html tag, it deletes on time, but when typing the desired name once again, it doesn't work. 
For example:

`<div></div>`  becomes `<div></>`

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.80GB (3.21GB free)|
|Process Argv|. --crash-reporter-id fb4ad505-c56c-4ddd-8561-58aeea298557|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment] 2020-12-14 09:38
Do you have by chance the `formulahendry.auto-rename-tag`  extension installed as well?

**Comment by aeschli** [comment] 2020-12-14 09:55
I'm not able to reproduce
- enable linked editing with `"editor.linkedEditing": true`
- new editor, set HTML as editor mode, set content `<div></div>`
- set the cursor in the `div`, after the `v`
- press backspace 3 times: `<></>`
- type `div` : `<div></div>`

Do you have by chance the `formulahendry.auto-rename-tag` installed as well?
-

**Comment by danicunhac** [comment] 2020-12-14 15:07
> I'm not able to reproduce
> 
> * enable linked editing with `"editor.linkedEditing": true`
> * new editor, set HTML as editor mode, set content `<div></div>`
> * set the cursor in the `div`, after the `v`
> * press backspace 3 times: `<></>`
> * type `div` : `<div></div>`
> 
> Do you have by chance the `formulahendry.auto-rename-tag` installed as well?

I've enabled the auto rename option in the settings tab, not directly inside the JSON file. I had no extension enabled while the error occurred. Followed exactly the steps you described to reproduce it.

**Comment by aeschli** [comment] 2020-12-15 09:11
Ok, strange. I close the issue then.

**Closed by aeschli** 2020-12-15 09:11 UTC
Labels: needs more info, new release
