### ISSUE TITLE
If no call stack is selected in the debug view, the REPL does nothing

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89669] opened 2020-01-29 23:31 UTC
I was confused for a minute about this a few days ago and @roblourens  just hit this as well. You can use the debug repl while you haven't selected a call stack, but you never get output. We should maybe disable the input or automatically select the first deepest child when data is entered.

gif:

![](https://memes.peet.io/img/2ba1d195-ac0e-4ae0-b4a1-5a1c871101ff.gif)

**Comment by isidorn** [comment] 2020-01-30 13:35
Yeah that is a bit funky. We should automatically select the first child or something and this should just work.
Anyways we have always behaved like this I believe, thus assigning to February so I look into it next week.

**Comment by isidorn** [comment] 2020-02-05 16:09
@connor4312 I believe this is happening due to the parent session and the child session you seem to have.
I believe the Debug Console sends the evaluation to the parent session before you explicitly focus the child.

Can you please just share simple reproducable steps so I also have the parent / child session setup? Thanks!

**Comment by connor4312** [comment] 2020-02-05 16:38
With the js-debug adapter, anything you debug will have a parent/child session ([why?](https://github.com/microsoft/vscode/issues/89475#issuecomment-579352573)). So you should be able reach this state with any program--launch a new debugger and, without hitting a breakpoint, try to type stuff into the debug console--there's no response. After you hit a breakpoint and the child gets selected, it works.

**Closed** 2020-02-06 17:25 UTC
Labels: debug, debug-console, under-discussion

**Comment by isidorn** [comment] 2020-02-06 17:27
@connor4312 pushed a fix for this.
I have decided that we automatically focus a child session when it is created if a parent session is focused. I believe this heuristic makes sense overall, especially for the js-debug adapter case.
