### ISSUE TITLE
Extension Host crashes and Debug Console output is lost when running test showing error messages in rapid succession

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode#102062] opened 2020-07-10 02:32 UTC
- VSCode Version: 1.47.0
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Checkout `vscode-extension-samples`
2. Open `helloworld-test-sample` project
3. Replace `extension.test.ts` with the following:

```ts
import * as vscode from 'vscode';

suite('Extension Test Suite', () => {
    vscode.window.showInformationMessage('Start all tests.');

    test('should', () => {
        vscode.window.showErrorMessage('1');
        vscode.window.showErrorMessage('2');
        vscode.window.showErrorMessage('3');
        vscode.window.showErrorMessage('4');
        vscode.window.showErrorMessage('5');
        vscode.window.showErrorMessage('6');
        vscode.window.showErrorMessage('7');
        vscode.window.showErrorMessage('8');
        vscode.window.showErrorMessage('9');
        vscode.window.showErrorMessage('10');
    });
    test('should', () => {
        vscode.window.showErrorMessage('1');
        vscode.window.showErrorMessage('2');
        vscode.window.showErrorMessage('3');
        vscode.window.showErrorMessage('4');
        vscode.window.showErrorMessage('5');
        vscode.window.showErrorMessage('6');
        vscode.window.showErrorMessage('7');
        vscode.window.showErrorMessage('8');
        vscode.window.showErrorMessage('9');
        vscode.window.showErrorMessage('10');
    });
    test('should', () => {
        vscode.window.showErrorMessage('1');
        vscode.window.showErrorMessage('2');
        vscode.window.showErrorMessage('3');
        vscode.window.showErrorMessage('4');
        vscode.window.showErrorMessage('5');
        vscode.window.showErrorMessage('6');
        vscode.window.showErrorMessage('7');
        vscode.window.showErrorMessage('8');
        vscode.window.showErrorMessage('9');
        vscode.window.showErrorMessage('10');
    });
});
```
4. `npm install`
5. Run Extension Tests launch task

Result: The extension host crashes.

On macOS, I get a popup confirming this:
<img width="1136" alt="Screen Shot 2020-07-09 at 10 27 19 PM" src="https://user-images.githubusercontent.com/9157833/87109790-8a70f280-c233-11ea-88d0-8e97d9b381e9.png">

On Windows, the window just closes without any warning or error message. This confused me at first because I thought all tests passed, but the Mocha test output in the **Debug Console** ends abruptly:
```
  Extension Test Suite
    ✓ should
    ✓ should
```

Expected debug output:
```
  Extension Test Suite
    ✓ should
    ✓ should
    ✓ should
  3 passing (5ms)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment] 2020-07-10 03:40
I always assumed console logs from the debug extension host came through js-debug like normal console.logs, but it looks like this is actually not the case (so not a duplicate of https://github.com/microsoft/vscode-js-debug/issues/161). Additionally, js-debug does not handle the teardown of the debug window. Thus I do not believe this is a problem with the new debugger.

**Comment by JeffreyCA** [comment] 2020-07-10 14:12
It looks like the later tests do execute, but not all the output is printed out:

```ts
import * as vscode from 'vscode';
import fs = require('fs');
import { assert } from 'console';

function showErrors() {
	vscode.window.showErrorMessage('1');
	vscode.window.showErrorMessage('2');
	vscode.window.showErrorMessage('3');
	vscode.window.showErrorMessage('4');
	vscode.window.showErrorMessage('5');
	vscode.window.showErrorMessage('6');
	vscode.window.showErrorMessage('7');
	vscode.window.showErrorMessage('8');
	vscode.window.showErrorMessage('9');
	vscode.window.showErrorMessage('10');
}

suite('Extension Test Suite', () => {
	test('1', () => {
		showErrors();
	});
	test('2', () => {
		showErrors();
	});
	test('3', () => {
		showErrors();
	});
	test('4', () => {
		showErrors();
	});
	test('5', () => {
		showErrors();
	});
	test('6', () => {
		showErrors();
	});
	test('7', () => {
		showErrors();
	});
	test('8', () => {
		showErrors();
	});
	test('9', () => {
		showErrors();
		fs.writeFile('/some/path/test.txt', 'Test', () => {
			return;
		});
		console.log('Reached end'); // <--- Set breakpoint
	});
});
```

If you set a breakpoint at the `console.log`, it does get triggered. I initially thought the test process just terminated unexpectedly. But if you hit **Continue** in the debugger, the rest of the Mocha output is properly printed out.

**Comment by alexdima** [comment] 2020-07-21 12:55
I can reliably reproduce the crashing of the renderer process. 

The steps in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues did not create a `.dmp` file for me. 

But after launching insiders via `/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron` from a terminal I got the following stack trace:

My insiders version is :
```
Version: 1.48.0-insider
Commit: 6c21258b65e4c9448323c930fabb1ac6b734c597
Date: 2020-07-20T05:27:28.503Z (1 day ago)
Electron: 8.3.3
```

```
Error: async hook stack has become corrupted (actual: 376, expected: 0)
 1: 0x107c24674 node::InternalCallbackScope::Close() [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x107c24529 node::InternalCallbackScope::Close() [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x107c2489b node::InternalCallbackScope::Close() [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x107c24ac1 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x107c590e5 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x107d9c6dd uv_check_stop [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x107d96ca9 uv_run [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10280a18e ElectronInitializeICUandStartNode [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10481f2bf v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x10482f63a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x10482f3d7 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10487df01 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x10487974a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x10487d7df v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x7fff3502cde2 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
16: 0x7fff3502cd81 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
17: 0x7fff3502cb9b __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
18: 0x7fff3502b8ca __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
19: 0x7fff3502aece CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
20: 0x7fff376c31c8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] [/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation]
21: 0x10487e411 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x10487d172 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x10482fef7 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x104807db7 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x107bc7c14 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x1031f7bfc ElectronInitializeICUandStartNode [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x1060d5e44 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x1031f72a4 ElectronInitializeICUandStartNode [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x1026ae294 ElectronMain [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
30: 0x10265ef85  [/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)]
31: 0x7fff6ee8ecc9 start [/usr/lib/system/libdyld.dylib]
[main 2020-07-21T12:52:28.819Z] [VS Code]: renderer process crashed!
```

@deepak1556 What would be next steps? Report the stack against Electron?

**Comment by deepak1556** [comment] 2020-07-21 17:34
The async stack corruption is actually hiding the renderer crash stack, we used to bypass the async hooks check with `export NODE_OPTIONS="--no-force-async-hooks-checks"` but that doesn't work for packaged apps since electron doesn't allow it. I will get a better stack trace with a debug build since I am also able to repro the crash.

**Comment by deepak1556** [comment] 2020-07-22 06:53
this one was not straight forward, although the render process reports crashing there was no crash dump generated. Turns out the crash was just a side effect of node in the renderer terminating on uncaught exception

```
[91373:0721/221939.251233:INFO:CONSOLE(208)] "[uncaught exception]: Error: write EPIPE", source: file:///Users/demohan/github/vscode/out/bootstrap-window.js (208)
[91373:0721/221939.251332:INFO:CONSOLE(211)] "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at NodeSocket.write (file:///Users/demohan/github/vscode/out/vs/base/parts/ipc/node/ipc.net.js:45:25)
    at ProtocolWriter._writeNow (file:///Users/demohan/github/vscode/out/vs/base/parts/ipc/common/ipc.net.js:258:26)
    at Immediate.<anonymous> (file:///Users/demohan/github/vscode/out/vs/base/parts/ipc/common/ipc.net.js:250:26)
    at processImmediate (internal/timers.js:439:21)", source: file:///Users/demohan/github/vscode/out/bootstrap-window.js (211)
[91373:0721/221939.251387:INFO:CONSOLE(200)] "Uncaught Error: write EPIPE", source: events.js (200)
```

Considering the EPIPE in renderer, it should be because of extension host process terminating early. When lldb is attached to the extension host process it doesn't terminate in unexpected way. Here is my flow

* ./scripts/code.sh --extensionDevelopmentPath=/Users/demohan/github/vscode-extension-samples/helloworld-test-sample/ --extensionTestsPath=/Users/demohan/github/vscode-extension-samples/helloworld-test-sample/out/test/suite/index.js --inspect-brk-extensions

* find the process with `--type=extensionHost` in the process tree

* `lldb /Users/demohan/github/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS/Electron Helper (Renderer)` 

* attach to the process and continue

out of ideas for next steps, any input is welcome.

**Comment by alexdima** [comment] 2020-07-22 08:09
:+1: Thank you @deepak1556 for figuring this out.

**Comment by JeffreyCA** [comment] 2020-07-22 15:39
Hi, thanks for the fix, but my original issue was more about the output of the tests not being printed to the Debug Console after the Extension Host window closed. I tested out the latest changes and the window does not crash anymore, but the rest of the Mocha output never gets printed despite the test code still got executed. It's still not clear from the Debug Console output why it suddenly stopped printing the test of the output.

![image](https://user-images.githubusercontent.com/9157833/88196950-cb8fdc00-cc0f-11ea-9684-73d85e132c9d.png)

**Comment by alexdima** [comment] 2020-07-22 21:02
This turned out to be a very old bug that wasn't fixed properly. b853633084b79db1c5a919ef084c9a53b6318224 attempted to fix this bug, but that attempt was by using a timeout of 500ms and hoping that 500ms is sufficient for the renderer process to drain the socket. But 500ms is not sufficient in this case, where a lot of messages are written from the extension host tests to the renderer process and they are not awaited. These messages fill up quite a lot the socket's buffer and oftentimes more than 500ms are needed for the renderer to catch up.

**Closed** 2020-07-22 21:52 UTC
Labels: bug, extension-host, freeze-slow-crash-leak

**Comment by JeffreyCA** [comment] 2020-07-23 00:43
I can confirm the rest of the output is printed now. Thanks for the quick turnaround 👍
