### ISSUE TITLE
Debugger: make completions play nicely with the bracket matching

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#79586] opened 2019-08-21 16:40 UTC
Follow up to https://github.com/microsoft/vscode/issues/79195

Precondition: debug adapter defines completion triggers to include `[` and `'`.

Steps:
- Type characters, one by one: `window['doc`
- On the screen you will see `window['doc<|>]`, where <|> is caret
- Notice the closing `]` that was created by bracket matching
- Hit enter to accept the `['document']` completion
- On the screen you will see `window['document']<|>]`
- Notice the extra bracket in the end, before the cursor

The solution seems to be to alter the logic of the completion subsystem itself to overwrite the closing bracket if it is immediately following the inserted one. That's exactly what would happen if I was typing `window['document']` using the keyboard. Basically treat inserted completion as if it was typed by the user character by character.

@isidorn , @jrieken, wdyt?

**Comment by jrieken** [comment] 2019-08-22 09:30
/duplicate of https://github.com/microsoft/vscode/issues/26012

**Closed** 2019-08-22 09:33 UTC
Labels: *duplicate, suggest
