### ISSUE TITLE
Messages not found

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#68393] opened 2019-02-11 08:23 UTC
I just updated my VS Code on Windows and this has popped up immediately after opening a `.ts` file:

![image](https://user-images.githubusercontent.com/5047891/52551891-9d815800-2dde-11e9-9ea5-443ae97056c5.png)

**Comment by mattacosta** [comment] 2019-02-11 10:27
Duplicate of #68259.

**Comment by alexandrudima** [comment] 2019-02-11 11:10
fyi @dbaeumer I wonder if this is nls related ?

**Comment by jrieken** [comment] 2019-02-11 11:24
Yes, to my knowledge this signals failure of loading nls bundles, but I don't know why. @alexandrudima do you have some language packs installed?

**Comment by IllusionMH** [comment] 2019-02-11 16:17
I've never uses language packs.
And starting from this weekend builds it started to spam console with errors about missing translations.

As I can see in DevTools it looks for
```
Messages for file c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\markdown-language-features\dist\features\previewContentProvider not found. See console for details.
Messages for file c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\features\rename not found. See console for details.
```

However there is no `features` folder in `resources\app\extensions\markdown-language-features\dist` or `resources\app\extensions\typescript-language-features\dist` folder.
Only `extension.js`, `nls.metadata.header.json`, and `nls.metadata.json`

**Comment by alexandrudima** [comment] 2019-02-11 16:39
Looks like `vscode-nls` replaces `\` with `/` when looking up in a map, but not when creating the map:

![image](https://user-images.githubusercontent.com/5047891/52578160-ef000600-2e23-11e9-8fe7-c1efdc3759fe.png)

**Comment by IllusionMH** [comment] 2019-02-11 16:39
Should `nls.metadata.json` file contain keys with `/` like `features/previewContentProvider` but keys with `\\` are published for Windows?

As I see now `h = _.nlsBundle[f]` (from minified file) is called with `features/previewContentProvider` but instead has `"features\\previewContentProvider"`, `"features\\preview"` in its keys.

**Comment by alexandrudima** [comment] 2019-02-11 16:42
Indeed, it looks like in the past, the files `nls.metadata.json` used to have `/` also on Windows, here is:
* `php-language-features\dist\nls.metadata.json` @ d9f81c831c
```
{"features/validationProvider":{"messages":["Do you allow {0} (defined as a workspace setting) to be executed to lint PHP files?","Allow","Disallow","Cannot validate since {0} is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.","Cannot validate since no PHP executable is set. Use the setting 'php.validate.executablePath' to configure the PHP executable.","Failed to run php using path: {0}. Reason is unknown."],"keys":["php.useExecutablePath","php.yes","php.no","wrongExecutable","noExecutable","unknownReason"]}}
```
* `php-language-features\dist\nls.metadata.json` on master:
```
{"features\\validationProvider":{"messages":["Do you allow {0} (defined as a workspace setting) to be executed to lint PHP files?","Allow","Disallow","Cannot validate since {0} is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.","Cannot validate since no PHP executable is set. Use the setting 'php.validate.executablePath' to configure the PHP executable.","Failed to run php using path: {0}. Reason is unknown."],"keys":["php.useExecutablePath","php.yes","php.no","wrongExecutable","noExecutable","unknownReason"]}}
```

**Comment by alexandrudima** [comment] 2019-02-11 16:45
This was introduced by `vscode-nls-dev` between 3.2.2 and 3.2.3 ... https://github.com/Microsoft/vscode-nls-dev/commits/master

I will downgrade to 3.2.2 until we fix it.

**Comment by IllusionMH** [comment] 2019-02-11 16:50
@alexandrudima when will restored `nls` files be available? Insiders build tomorrow?

**Comment by alexandrudima** [comment] 2019-02-11 16:50
@IllusionMH I am looking into it

**Comment by IllusionMH** [comment] 2019-02-11 16:53
@alexandrudima Thanks!

**Closed** 2019-02-11 17:28 UTC
Labels: important

**Comment by dbaeumer** [comment] 2019-02-18 10:10
@alexandrudima is there anything I need to catch up with?
