### ISSUE TITLE
Sticky scroll not aligned

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#190066] opened 2023-08-09 17:24 UTC
On the latest Insiders:

The sticky scroll labels at the top seem to be cut off even though I'm at the leftmost scroll point in the editor.
The problem occurs when I navigate to another file and then navigate back to the current one.

![Sticky scroll at top is cut off](https://github.com/microsoft/vscode/assets/7199958/73beabfb-a259-4294-9365-0e297b74b7da)

**Comment by aiday-mar** [comment] 2023-08-10 06:45
Hi @rzhao271, thanks for filing the issue. Could you paste here an example of the code where you saw this? I am currently not able to reproduce it.

**Comment by timar07** [comment] 2023-08-10 10:15
I found how to reproduce this bug:
1. open this file in vscode and navigate to line 358
https://github.com/microsoft/vscode/blob/6c683c327ca8656de700552a519927d9c7316226/src/vs/workbench/contrib/preferences/browser/settingsTreeModels.ts#L358C1-L358C1
2. switch to another file and then switch back

In my case, it is displayed as empty sticky line
<img width="1136" alt="Снимок экрана 2023-08-10 в 13 14 19" src="https://github.com/microsoft/vscode/assets/78262306/94221464-8d76-4318-8b2d-302078bb2d2d">

**Comment by aiday-mar** [comment] 2023-08-10 10:18
Hi thanks for filing this issue, the issue you mentioned @timar07 should be fixed with https://github.com/microsoft/vscode/pull/190138

The issue @rzhao271 mentions is perhaps different. Let me know if you continue seeing this error when the PR above is merged

**Closed** 2023-08-10 15:58 UTC
Labels: bug, editor-sticky-scroll
