### ISSUE TITLE
Allow extensions to get a LanguageConfiguration for a language

### ISSUE THREAD

**Issue by stkb** [microsoft/vscode#2871] opened 2016-02-09 23:08 UTC
As far as I can tell, extensions can set a `LanguageConfiguration` object for a language with `languages.setLanguageConfiguration()`, but they can't get an existing one. This would be very useful for getting information about the language of the current document.

**Comment by alexandrudima** [comment] 2016-02-12 08:48
fyi @jrieken

**Comment by wiggin77** [comment] 2016-12-27 18:02
I need this as well. I am writing an extension that enhances other language extensions and need to look up things like what autoclosing pairs are defined.

**Comment by renatodinhani** [comment] 2017-01-24 15:24
I also need this to retrieve information about the comments for the current language.

**Comment by SuyogSoti** [comment] 2017-05-08 07:05
A little hack that I have done is

        var ext;
        if(fs.existsSync("/usr/share/code/resources/app/extensions")){
            ext = fs.readFileSync("/usr/share/code/resources/app/extensions/" + editor.document.languageId + "/" + "language-configuration.json", "utf8");
        }else{
            ext = fs.readFileSync("C:///Program Files (x86)/Microsoft VS Code/resources/app/extensions" + editor.document.languageId + "/" + "language-configuration.json", "utf8");
        }

This little hack seems to work for all of the default languages for vscode. I would however love to have api to have access to this.

**Comment by IMFUZZ** [comment] 2017-10-21 03:58
I know it's been some time, but I have encountered the same problem. Fetching the "language-configuration.json" file using the "languageId" is not reliable since some languages uses "<languageId>-language-configuration.json" ("javascript" for example) or the folder of the extension itself does not correspond to the languageId ("dockerfile" being inside the "docker" extension folder for example).

Anybody found a good work-around?

**Comment by IMFUZZ** [comment] 2017-10-21 04:49
ok, I found a pretty good way:
```
const editor = vscode.window.activeTextEditor;
const documentLanguageId:string = editor.document.languageId;
var langConfigFilepath:string = null;
for (const _ext of vscode.extensions.all) {
  // All vscode default extensions ids starts with "vscode."
  if (
    _ext.id.startsWith("vscode.") &&
    _ext.packageJSON.contributes &&
    _ext.packageJSON.contributes.languages
  ) {
    // Find language data from "packageJSON.contributes.languages" for the languageId
    const packageLangData = _ext.packageJSON.contributes.languages.find(
      _packageLangData => (_packageLangData.id === documentLanguageId)
    );
    // If found, get the absolute config file path
    if (!!packageLangData) {
      langConfigFilepath = path.join(
        _ext.extensionPath,
        packageLangData.configuration
      );
      break;
    }
  }
}
// Validate config file existance
if (!!langConfigFilepath && fs.existsSync(langConfigFilepath)) {
  langConfig = require(langConfigFilepath);
  // PROFIT
}
```

__Note:__ I would recommend that you use an external node module that parses json containing comments ([comment-json](https://www.npmjs.com/package/comment-json) for example) instead of require(...), since some of vscode's language-configuration have some. Making them invalid JSON which breaks require() and JSON.parse.

**Comment by davidquinn** [comment] 2019-03-22 08:12
I was wondering if there is any plan to resolve this (expose the current document's language configuration)?  I don't like the workarounds above which are clever, but hacky and not guaranteed to work.

I am the author of the psioniq File Header extension, and at the moment, the only way to define the comment start/end/prefix is to include it in my extension's configuration.  This requires users to unnecessarily duplicate configuration settings that are already (and more safely) part of the language config.

**Comment by dbaeumer** [comment] 2021-03-19 12:26
I would also need this for ESLint.

**Comment by alexr00** [comment] 2021-11-10 15:54
Duplicate of https://github.com/microsoft/vscode/issues/109919

**Closed by alexr00** 2021-11-10 15:54 UTC
Labels: feature-request, api, languages-basic
