### ISSUE TITLE
Supply text argument to task when running it

### ISSUE THREAD

**Issue by mavanmanen** [Microsoft/vscode#40865] opened 2017-12-27 11:52 UTC
Right now if you have tasks that are almost the same with one different string for example, you will still need to have two separate tasks to be able to run them.

Example:
```json
  "version": "2.0.0",
  "tasks": [
    {
      "label": "make custom",
      "type": "shell",
      "command": "make",
      "args": [
        "--no-print-directory",
        "--directory=~/qmk_firmware",
        "niu_mini:custom"
      ],
      "group": "build",
      "problemMatcher": {
        "base": "$gcc",
        "fileLocation": ["relative","${workspaceRoot}"]
      }
    },
    {
      "label": "make default",
      "type": "shell",
      "command": "make",
      "args": [
        "--no-print-directory",
        "--directory=~/qmk_firmware",
        "niu_mini:default"
      ],
      "group": "build",
      "problemMatcher": {
        "base": "$gcc",
        "fileLocation": ["relative","${workspaceRoot}"]
      }
    }
  ]
}
```

It would be great if we could supply an argument to a task to eliminate this issue.

Example:
```json
{
  "label": "make",
  "type": "shell",
  "command": "make",
  "taskArgs": [ 
    {
      "name": "map",
      "required": true,
      "choices": [ "custom", "default" ],
      "default": "custom"
    }
  ],
  "args": [
    "--no-print-directory",
    "--directory=~/qmk_firmware",
    "niu_mini:${map}"
  ],
  "group": "build",
  "problemMatcher": {
    "base": "$gcc",
    "fileLocation": ["relative","${workspaceRoot}"]
  }
}
```

I think this will be a very welcome addition for a lot of people and hope to see it in the future.

**Comment by alexr00** [comment] 2018-10-22 09:07
@dbaeumer, duplicate of #4758?

**Comment by dbaeumer** [comment] 2018-10-24 10:06
@alexr00 yes. Closing as dup of #4758.

**Closed by dbaeumer** 2018-10-24 10:06 UTC
Labels: feature-request, tasks
