### ISSUE TITLE
Entering a specific regular expression can cause a crash

### ISSUE THREAD

**Issue by faxlet** [microsoft/vscode#108879] opened 2020-10-18 03:42 UTC
Issue Type: <b>Bug</b>

1. open a project

2. go to search  and input with regular expression

```
\b(.*?)+\(\)
```
![bug](https://user-images.githubusercontent.com/52160411/96358175-c53dcd00-1136-11eb-892e-586affdc5283.png)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

**Comment by judicaelandria** [comment] 2020-10-18 13:29
Hey @faxlet,
I'm using the same version as you, and I can't reproduce the error, it's work fine for me
try to restart you vs code or your computer, maybe you run many apps

**Comment by IllusionMH** [comment] 2020-10-19 00:05
/duplicate of #30874

@faxlet when you have opened tabs - global search will utilize JS based match on opened files. In your case its `(.*)+` that causes Catastrophic Backtracking which freezes main thread on files that are more than couple of short lines.

If there are no open tabs ripgrep will be used that doesn't have such problem.

@judicaelandria most likely you either don't have open tabs or open files are "small" enough to be processed.

**Closed** 2020-10-19 00:06 UTC
Labels: *duplicate
