### ISSUE TITLE
terminal.integrated.tabs.defaultIcon dropdown freeze UI

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162269] opened 2022-09-28 21:51 UTC
Type: <b>Bug</b>

1. In settings UI
1. Click the drop down for `terminal.integrated.tabs.defaultIcon`

**Bug**
The ui freezes for a second

VS Code version: Code - Insiders 1.72.0-insider (Universal) (835d39cfac9ede6c7c90678c8d6c3d4d0171ed6d, 2022-09-28T05:18:00.488Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment] 2022-09-28 21:52
Offending call stack ![Screen Shot 2022-09-28 at 2 50 22 PM](https://user-images.githubusercontent.com/12821956/192895332-fcb866c8-ed51-4a5c-b8f7-a895131d6cbb.png)

And profile:
[Profile-20220928T145000.json.zip](https://github.com/microsoft/vscode/files/9669133/Profile-20220928T145000.json.zip)

**Comment by gjsjohnmurray** [comment] 2022-09-28 23:47
It's loading **every** codicon, and not sorting them by name.

**Comment by rzhao271** [comment] 2022-10-26 17:57
Duplicate of https://github.com/microsoft/vscode/issues/156635

**Closed by rzhao271** 2022-10-26 17:57 UTC
Labels: perf, settings-editor
