### ISSUE TITLE
[folding] add the possibility to always show the fold/unfold indicator

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#3911] opened 2016-03-09 12:39 UTC
I think there should be a triple state value instead of a boolean in the settings.json. So one can choose between don't show folding, show folding on hover and alwasy show folding.

**Comment by ttn10** [comment] 2017-02-04 07:37
version 1.9 still not?

**Comment by ttn10** [comment] 2017-02-08 09:24
i need this featue, where?

**Comment by xttn** [comment] 2017-02-28 07:27
Hey @aeschli , almost 1 year, this feature is not yet complete?

**Comment by haisapan** [comment] 2017-04-12 15:39
I want it too, anyone help?

**Comment by xttn** [comment] 2017-04-13 07:57
Hi @weinand @aeschli , can someone give us your progress?

**Comment by aeschli** [comment] 2017-04-13 10:34
This feature is currently not planned. Please for it (with 👍 ) so it gets priority.

**Comment by aleksandaratanasov** [comment] 2017-05-18 09:11
+1 It was just pure accident that I move my mouse near the location where the line numbers are displayed to actually discover that the folding symbols are indeed there. In the `settings.json` the feature is enabled by default however there is no mention that even if enabled it will remain invisible until a specific location is hovered. If this feature is not included at least edit the comment to include HOW to actually make these things visible. Otherwise people will be forced to search on the internet or (as in my case) even post on SO. It's too much work for a feature that is de facto a standard nowadays with advanced editors.

A compromise between "hiding until location next to line numbers is hovered" and "displaying all the time" would be to display the folding symbols whenever a foldable section is hovered (the text itself or the space on both of its sides).

**Comment by aeschli** [comment] 2017-05-18 15:07
duplicate of #4812. 
For the May release I added a new setting so that the fold controls stay always visible:
`"editor.showFoldingControls": "always"`

**Closed by aeschli** 2017-05-18 15:07 UTC
Labels: editor-folding, feature-request
