### ISSUE TITLE
Mouse pointer doesn't flip direction in left margin of text editor

### ISSUE THREAD

**Issue by christofjans** [microsoft/vscode#90707] opened 2020-02-14 15:59 UTC
When placing the mouse pointer in the left margin of the text editor (where the line numbers are), it used to "flip direction" (pointing to the right, instead of left).

It doesn't appear to do that anymore.

**Comment by IllusionMH** [comment] 2020-02-14 17:06
This is intentional change in 1.42 see #85176 because there is not native way to provide "flipped" cursor except putting it as image which won't match system cursor. 

However I agree that now it's hard to discover location where click would select whole line (initially discovered thanks to this cursor flip).

/cc @misolori @alexdima

**Comment by misolori** [comment] 2020-02-14 17:20
Agreed that this was changed for the reasons that @IllusionMH mentioned, which also meant the cursors were blurry in HiDPI. Closing as designed.

**Closed by misolori** 2020-02-14 17:20 UTC

**Comment by Diggsey** [comment] 2020-02-18 16:32
Ugh, this change is surprisingly irritating for such a simple thing when you are used to the previous behaviour... Could we not still have the option for a reversed cursor? It worked perfectly fine for many people before.
