### ISSUE TITLE
Clone and paste a file, does not open the new file and activate

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#121966] opened 2021-04-22 20:39 UTC
I'm developing in typescript, and i always tend to edit the wrong file, not the cloned one.

The main problem here, that the cloned file name in the left side (in the tree) is in focus, like in the case when you open a file.
I do feel it's confusing, and it shouldn't be configurable, if there is any flag, which can fix it.

It works perfectly fine in IntelliJ, but not in VsCode.

**Comment by dalisoft** [comment] 2021-04-22 20:55
@fssrepository It's known bug (or feature?), see #120882

Duplicate of: #120882

**Closed** 2021-04-26 08:46 UTC
Labels: *duplicate
