### ISSUE TITLE
Format Document 中文翻译问题

### ISSUE THREAD

**Issue by anrip** [Microsoft/vscode#28854] opened 2017-06-16 03:14 UTC
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. 打开 TS 文件
2. 右键菜单 - “Format Document” 并未翻译为中文

**Comment by chenyeah** [comment] 2017-06-16 03:51
新建编码片段也没翻译， 但无所谓了 反正也看得懂

**Comment by danyeh** [comment] 2017-06-17 00:51
It was fixed by wangweixuan 8 days ago. Our final translation push of 1.13 was 10 days ago.
https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hans/$/111042394?q=Format document
Root cause is something wrong in translation memory. I have deleted the unloc entry.
Thanks @anrip for reporting the issue.

**Closed by danyeh** 2017-06-17 00:51 UTC
Labels: i18n, new release

**Comment by danyeh** [comment] 2017-06-17 00:56
Same for https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hans/$/111042548?q=formatting

**Comment by khoiph1** [comment] 2017-06-17 04:54
All languages were fixed. Thanks!
