### ISSUE TITLE
Microsoft Authentication logs out after update

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#122581] opened 2021-04-28 20:33 UTC
Issue Type: <b>Bug</b>

Repro steps:
1. Install an older version of VS Code like [1.52]9(https://code.visualstudio.com/updates/v1_52)
2. In VS Code, sign in using Microsoft authentication.
3. Check for updates and install the updates.
4. Note that on restarting the VS Code after update, the sign in menu does not show your identity. If there an extension dependent on that identity, you will get a sign in prompt again.

 I see following output in the Microsoft authentication pane:

`[Error  - 20:32:15.740] Getting token failed: Error: Decryption failed`

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (10.99GB free)|
|Process Argv|--crash-reporter-id 1e7fa2ad-4532-4c0a-9475-8f16bd6b778e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833cf:30267465
vshan820:30294714
vscus158cf:30286554

```

</details>

**Comment by RMacfarlane** [comment] 2021-04-28 21:10
This is expected when upgrading to 1.53 and shouldn't happen on future versions of VS Code: https://code.visualstudio.com/updates/v1_55#_encryption-update-on-windows

**Comment by RMacfarlane** [comment] 2021-04-28 21:12
Oh, oops, wrong version.

**Comment by RMacfarlane** [comment] 2021-05-07 21:48
I'm not able to reproduce this between version 1.55 and 1.56, are you still seeing it there?

**Comment by samrat-gavale** [comment] 2021-05-07 22:14
Hey @RMacfarlane, I indeed observed this during updating from 1.52 to 1.53. I have mentioned 1.52 in the original bug and also linked to the version that I used for repro'ing [https://code.visualstudio.com/updates/v1_52](https://code.visualstudio.com/updates/v1_52). I verified that it does not occur when updating from 1.55 to 1.56.

**Comment by RMacfarlane** [comment] 2021-05-07 22:15
Ok, thanks for confirming. Since this doesn't reproduce in the latest version, I'm going to go ahead and close this.

**Closed by RMacfarlane** 2021-05-07 22:15 UTC
Labels: needs more info
