### ISSUE TITLE
Reveal in Sidebar broken

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#83655] opened 2019-10-30 11:47 UTC
Issue Type: <b>Bug</b>

Note: This is with Remote-Containers.

Also Refresh in the Explorer used to reveal the current file:
![Oct-30-2019 12-46-40](https://user-images.githubusercontent.com/9205389/67855765-5c1f0d00-fb13-11e9-860e-bc5cb208d5b5.gif)

VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:36:49.155Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit
Remote OS version: Linux x64 4.9.184-linuxkit
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|-psn_0_3625845|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (0.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (0.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (0.31GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.12.0
vscode-docker|ms-|0.8.1
vscode-versionlens|pfl|0.24.0
vscode-open-in-github|sys|1.13.0
theme-karyfoundation-themes|kar|18.2.1
remote-containers|ms-|0.82.0
remote-wsl|ms-|0.40.0
ayu|tea|0.18.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2019-10-30 13:25
Cannot reproduce in web selfhost at least, which also uses a remote.

**Comment by joaomoreno** [comment] 2019-10-30 14:00
@chrmarti Can you repro after reload? If so, let me know the exact steps.

**Comment by chrmarti** [comment] 2019-10-30 15:07
I was able to reproduce after reload, but not anymore. There were no additional steps, the editor was already open after reload and the action did not work. 🤷‍♂

**Comment by bpasero** [comment] 2019-10-30 16:23
If this happens again, make sure to check for errors in the dev tools.

**Comment by chrmarti** [comment] 2019-10-31 08:02
There were none.

**Comment by isidorn** [comment] 2019-11-12 10:39
Yeah sounds like a duplicate of https://github.com/microsoft/vscode/issues/82290 and some other issues.
Since there are no steps here I am going ahead and closing this.

**Closed by isidorn** 2019-11-12 10:39 UTC
