### ISSUE TITLE
regression: copy/pasting HTML removes whitespace

### ISSUE THREAD

**Issue by patrickhulce** [Microsoft/vscode#28084] opened 2017-06-06 04:54 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (3a6eda74ead5b5b041da0bbc18b70218e8c95bba, 2017-05-31T05:06:36.650Z)
 9a107453944f25e6019b08615e20d63545584855 is still affected
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|vscode-new-file|dkundel|3.0.2|
|tslint|eg2|0.15.0|
|cpptools|ms-vscode|0.11.2|
|vscode-icons|robertohuertasm|7.8.1|
|vscode-open-in-github|sysoev|1.6.0|;

---

Steps to Reproduce:

1. Open an HTML document with the following code and select a line with its preceding whitespace
```
<html>
  <body>
    <span>hello!</span>
  </body>
</html>
```
2. Copy the code, and paste twice

| Selection | Actual | Expected |
| -- | -- | -- |
| ![image](https://cloud.githubusercontent.com/assets/2301202/26814244/e7c6601c-4a38-11e7-8e4d-b587b783045f.png) | ![image](https://cloud.githubusercontent.com/assets/2301202/26814266/190c8be2-4a39-11e7-8e7d-0ea43adcb631.png) | ![image](https://cloud.githubusercontent.com/assets/2301202/26814274/2fd7b9c8-4a39-11e7-802d-823a184aca42.png) |

Other languages seem to be unaffected (only tested JS and TS)
Known Good Version: Version 1.12.2 (1.12.2) 19222cdc84ce72202478ba1cec5cb557b71163de

**Comment by aeschli** [comment] 2017-06-07 09:53
This is caused by `"editor.formatOnPaste": true` by default.

**Comment by aeschli** [comment] 2017-06-07 10:52
duplicate of #28176

**Closed by aeschli** 2017-06-07 10:52 UTC
Labels: insiders
