### ISSUE TITLE
Support for project subfolders with their own git repo

### ISSUE THREAD

**Issue by slothbag** [Microsoft/vscode#4710] opened 2016-03-28 11:19 UTC
My project has one root folder with a bunch of related projects in subfolders each with their own git rep attached.

In Xamarin Studio it shows each project/subfolder with a description of which branch each repo is on.. i.e. "master". So instantly I can see each project is its own repo and which branch they are currently set to.

I deliberately avoided git submodules for other reasons.

Is it possible for VSCode to support different subfolders each with their own git repo?

**Comment by Tyriar** [comment] 2016-03-28 18:47
Related: https://github.com/Microsoft/vscode/issues/396

**Comment by joaomoreno** [comment] 2016-03-29 09:37
Yeah, closing as duplicate of #396

**Closed by joaomoreno** 2016-03-29 09:37 UTC
Labels: feature-request, git
