### ISSUE TITLE
Undo/Redo is Lost When Untitled File is Saved

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#103208] opened 2020-07-23 22:11 UTC
Issue Type: <b>Bug</b>

When a new file is saved for the first time, the undo/redo stack is merged into one.  It becomes an entire file undo/redo, instead of the individual steps.

(The gif looks slow, probably due to what was used to convert it.)
![Example](https://user-images.githubusercontent.com/52075362/88343396-ea24ce80-cd06-11ea-850e-3ddef0809c6d.gif)

VS Code version: Code - Insiders 1.48.0-insider (8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e, 2020-07-23T05:40:23.559Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (5.26GB free)|
|Process Argv|--crash-reporter-id 03f31147-8ebd-457f-9df0-cdf4b9cd93d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
dotenv|mik|1.0.1
vscode-wakatime|Wak|4.0.0

</details>

**Comment by alexdima** [comment] 2020-08-30 10:06
Duplicate of #17977

**Closed by alexdima** 2020-08-30 10:06 UTC
