### ISSUE TITLE
hue slider inconsistency

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31656] opened 2017-07-28 10:30 UTC
Testing #31457:

A nit...

Opening the color picker on a shade of grey, the colour spectrum field on the left shows no colour, but the hue field shows the "thumb" (the horizontal line) at red:

![2017-07-28_12-20-23](https://user-images.githubusercontent.com/1898161/28713470-6b2168f6-738f-11e7-8627-4793b48b9606.png)

moving the hue thumb a tiny bit adds colours to the colour spectrum:
 
![2017-07-28_12-24-38](https://user-images.githubusercontent.com/1898161/28713552-c2608606-738f-11e7-80ad-95c90fa6463b.png)

So it seems that initially there is no "hue" and the correct way to represent this would be to show no hue thumb at all.

A consequence of this behaviour is that once hue has been clicked, there is no way to go back to non-hue mode.

**Comment by michelkaporin** [comment] 2017-07-31 09:25
There is always a hue, but the point you select in the saturation box defines also color value and saturation. Those discard hue, because saturation is 0% and value is 100% at the example above. 

All colour pickers I've seen so far always show a hue no matter what value of saturation and colors are. Closing as designed, let me know if I misunderstood the problem.

**Closed by michelkaporin** 2017-07-31 09:25 UTC
