### ISSUE TITLE
Open folder does not work

### ISSUE THREAD

**Issue by robertorenesc** [microsoft/vscode#94475] opened 2020-04-05 17:59 UTC
Issue Type: <b>Bug</b>

I click in Open->Folder and this does not work

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by dustin-decker** [comment] 2020-04-05 22:48
I had this on Linux with 1.43.2, but downgrading to 1.43.1 fixed it.

For me the folder selector dialog comes up but selecting a folder does nothing.

**Comment by ipedrazas** [comment] 2020-04-06 10:45
I have the same issue:

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by duncanawoods** [comment] 2020-04-07 13:46
I think this also applies to supplying a folder on the command line e.g.

Running this:

```
code . --verbose
```

Now fails to open the current folder. This is the console output in code:

```
/usr/share/code/reso…otstrap-window.js:5 [uncaught exception]: Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/usr/share/code/resources/app/node_modules.asar/graceful-fs/polyfills.js:10:19)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6694:534)
    at Q.resolveWorkspaceInitializationPayload (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6693:850)
    at Q.initServices (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6693:310)
    at Q.open (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6691:20)
    at Object.t.main (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:6696:17)
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.js:8:763
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
/usr/share/code/reso…otstrap-window.js:6 Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/usr/share/code/reso…n_thread_only.js:42)
    at process.cwd (/usr/share/code/reso…-fs/polyfills.js:10)
    at Q.resolveSingleFolderWorkspaceInitializationPayload (/usr/share/code/reso…esktop.main.js:6694)
    at Q.resolveWorkspaceInitializationPayload (/usr/share/code/reso…esktop.main.js:6693)
    at Q.initServices (/usr/share/code/reso…esktop.main.js:6693)
    at Q.open (/usr/share/code/reso…esktop.main.js:6691)
    at Object.t.main (/usr/share/code/reso…esktop.main.js:6696)
    at workbench.js:8
    at processTicksAndRejections (/usr/share/code/reso…s/task_queues.js:85)
    at /usr/share/code/reso….desktop.main.js:46
﻿```

Version info:

```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-45-generic
```

**Comment by bpasero** [comment] 2020-04-07 14:23
@duncanawoods I think this happens when you:
* start VSCode on a folder
* delete this folder
* try to open another instance of VSCode

**Comment by duncanawoods** [comment] 2020-04-07 14:30
@bpasero 

Nope, nothing to do with deleted folders. For the example log above, I was in my home directory. I can understand that this bug is making code believe there is a problem with the folder when there isn't. 

I have downgraded to `1.43.1` and `code <path>` works again as it used to.

**Comment by bpasero** [comment] 2020-04-07 14:36
@sandy081 adding you fyi since you last touched this area I think (`resolveSingleFolderWorkspaceInitializationPayload`)

I see we have a try/catch block around it that is still there, so `process.cwd()` should not cause the opening to fail. But the fact that this works in the current stable version is a bit scary.

**Comment by bpasero** [comment] 2020-04-07 14:42
@duncanawoods to clarify, you see this with insiders but not stable? So you do `code-insiders <path>` and it fails? Does it fail when no other instance is running?

**Comment by sandy081** [comment] 2020-04-07 14:44
> I see we have a try/catch block around it that is still there, so process.cwd() should not cause the opening to fail. But the fact that this works in the current stable version is a bit scary.

We just log the error and open an empty window.

@duncanawoods Can you please let us know if an empty window is being opened for you?

**Comment by duncanawoods** [comment] 2020-04-07 14:44
`1.43.2` stable. Version info is in the comment above if you want to double-check I haven't installed the wrong thing!

**Comment by duncanawoods** [comment] 2020-04-07 14:46
@sandy081 

It opens the app with the doc pane and explorer. The exporer window says something along the lines of "no folder open" and has a blue button to open a folder that then does nothing.

**Comment by robertorenesc** [comment] 2020-04-07 14:49
I had to restart my PC (Mac) and the error stop, previously I closed an opened VS Code and the log just show the message "endpoint for listener 'com.apple.view-bridge': Connection interrupted" once.

I installed again VS Code, deleted all .vs-code folders and nothing worked.

**Comment by sandy081** [comment] 2020-04-07 14:50
Ok there is no crash and empty window opens and as user claims it happens on `1.43.2`.

**Comment by bpasero** [comment] 2020-04-07 14:51
@duncanawoods how about opening a folder from within VSCode, does that work? File > Open?

**Comment by bpasero** [comment] 2020-04-07 14:53
+ @deepak1556 for thoughts, especially given https://github.com/microsoft/vscode/issues/94475#issuecomment-609497865

**Comment by duncanawoods** [comment] 2020-04-07 14:57
@bpasero

Previously, yes, the menu did not work.

However, I have now reinstalled `1.43.2` to double-check and get you more logs... and there is now no longer any issue. Gah!

**Comment by bpasero** [comment] 2020-04-07 15:00
OK, maybe other people can try to reinstall, reboot and check if things are getting back to normal?

**Comment by duncanawoods** [comment] 2020-04-07 15:01
I can say that the problem persisted across reboots for me, but not across downgrade/upgrade (no reboot).

**Comment by bpasero** [comment] 2020-05-24 07:31
Closing as it seems related to the OS and not VSCode. If someone can find reproducible steps we can revisit this issue.

**Closed by bpasero** 2020-05-24 07:31 UTC
Labels: needs more info
