### ISSUE TITLE
No terminal tab title/icon when creating terminals in a container before container has started

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#125139] opened 2021-06-01 17:22 UTC
![recording - 2021-06-01T102201 321](https://user-images.githubusercontent.com/29464607/120365420-43fd0a00-c2c3-11eb-9830-0c1076624ebd.gif)

**Comment by Tyriar** [comment] 2021-06-02 13:02
I think this might be working as designed since it's awaiting the connection before showing the icons and titles. If they show up eventually after connected I think we can close this.

**Closed** 2021-06-30 18:45 UTC
Labels: remote, terminal, terminal-tabs, under-discussion
