### ISSUE TITLE
Intellisense Unusably Slow

### ISSUE THREAD

**Issue by keegandonley** [microsoft/vscode#72616] opened 2019-04-19 16:55 UTC
Issue Type: <b>Performance Issue</b>

Even with all extensions disabled, Intellisense and autocomplete are now too slow to be useful

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 7|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    82	  1483	code main
    1	    82	  1521	   gpu-process
    0	   246	  1529	   window (index.js — s2l)
    0	    98	  1532	     extensionHost
    0	   606	  1534	       electron_node tsserver.js 
    0	    66	  1560	         electron_node typingsInstaller.js typesMap.js 
    0	    49	  1578	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1532
    0	    33	  1533	     watcherService
    0	    33	  1551	     searchService
    0	     0	  1594	     /bin/zsh -l
    0	     0	  1860	       /bin/zsh -l
    0	    33	  1912	       npm
    0	     0	  1913	         /Applications/Xcode.app/Contents/Developer/usr/bin/make start
    0	    33	  1974	           npm
    0	    16	  1975	             node /Users/keegan/s2l/node_modules/.bin/react-scripts start
    0	   279	  1976	               node /Users/keegan/s2l/node_modules/react-scripts/scripts/start.js
    0	    66	  1550	   shared-process
    4	    66	  2040	   window (Issue Reporter)
    0	     0	  2042	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — s2l)
|    Folder (s2l): 169 files
|      File types: js(70) png(31) jpg(15) svg(8) json(6) map(4) css(3)
|                  DS_Store(3) bin(3) xml(2)
|      Conf files: makefile(1) package.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.2
vsc-material-theme|Equ|2.8.2
vscode-icons|vsc|8.5.0

</details>

**Comment by mjbvz** [comment] 2019-04-19 23:41
Please share information about your workspace and repo steps 

/needsMoreInfo

**Comment by scottmeschke** [comment] 2019-04-21 23:59
Downgrading to 1.30.1 solved this for me fyi @keegandonley while this get's sorted out.

**Comment by keegandonley** [comment] 2019-04-29 09:19
@mjbvz Issue is persistent no matter what I try - rebooting, reinstalling, or disabling plugins. Happy to provide more information if you let me know what will be useful; I did include all the system/workspace information from the bug reporting tool in VS Code. 

@scottmeschke downgrading solved for me as well, thanks for the info

**Comment by mjbvz** [comment] 2019-04-29 18:14
What language are you working in and what is the basic structure of your project? Does this happen in all workspaces, or just one in particular?

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by roniemeque** [comment] 2019-05-03 03:36
Can confirm I started having the same issue out of nowhere. Fresh install didn't work, going back to 1.30 solved the issue for now.

**Comment by mjbvz** [comment] 2019-05-10 18:47
Closing as there is not enough information to investigate this. My best guess is that this is duplicate of https://github.com/microsoft/TypeScript/issues/31302 but please share repo steps and information about your project to confirm

**Closed by mjbvz** 2019-05-10 18:47 UTC
Labels: needs more info

**Comment by montella1507** [comment] 2019-05-11 20:15
I have got big problems in 1.33.1  as well. Updated to Insider build (1.34.20-insider) and again fast as  hell
