### ISSUE TITLE
IntelliSense in line comments

### ISSUE THREAD

**Issue by mandarinx** [Microsoft/vscode#2149] opened 2016-01-21 11:03 UTC
After upgrading to VSCode 0.10.6 I've been getting IntelliSense suggestions when writing a line comment (starting the line with //) in C# projects. I use VScode for developing Unity3D projects on OSX 10.11.2.

It's an understatement to call it annoying when I write e.g. "will do" and "do" auto completes to a full do...while loop.

**Comment by smbkr** [comment] 2016-01-21 13:19
It's not just limited to C# either, I get the same thing when writing PHP, a commented line starting with // will still invoke IntelliSense when writing for example 'while', 'for' etc.

**Comment by Wosi** [comment] 2016-01-21 14:00
It's related to this issue https://github.com/Microsoft/vscode/issues/719

**Comment by weinand** [comment] 2016-01-21 20:00
closing this issue as a duplicate of #719

**Closed by weinand** 2016-01-21 20:00 UTC
