### ISSUE TITLE
vscode.window.register* alternative views options to registerTreeDataProvider

### ISSUE THREAD

**Issue by kevindiclemente** [Microsoft/vscode#68577] opened 2019-02-12 23:47 UTC
Are there any ways to present UI to a user in the views panel besides registerTreeDataProvider?

It specifically would be super nice to have access to a text box.

Sample use case is for  custom search provider that can be integrated with a TreeDataProvider.

**Comment by sandy081** [comment] 2019-02-13 09:58
@kevindiclemente What is the usecase?

**Comment by kevindiclemente** [comment] 2019-02-21 03:00
Sorry I missed your reply! 

One usecase would be a custom input field (like the text input in the search tab) that is inline so that dynamic results can be displayed in the tree view.

Another use case would be displaying rich context such as inline drop down menus to select configurations from a list of options, similar to right-click behavior but integrated.

**Comment by sandy081** [comment] 2019-02-21 18:36
Duplicate of https://github.com/Microsoft/vscode/issues/50062

**Closed by sandy081** 2019-02-21 18:36 UTC
Labels: explorer-custom, needs more info
