### ISSUE TITLE
Command Add/Remove Line Comment inserts an unwanted space

### ISSUE THREAD

**Issue by marekzelinka** [Microsoft/vscode#30800] opened 2017-07-16 09:57 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (47a49c7fb8138fd27e2a95259ae96e9ac49a65a5, 2017-07-14T07:45:27.194Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: All extensions have been disabled

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|0.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm-script|eg2|0.2.0
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
html-tag-wrapper|hwe|0.1.7
search-node-modules|jas|1.1.1
HTMLHint|mka|0.3.3
atom-keybindings|ms-|2.9.1
advanced-new-file|pat|0.5.0
vscode-icons|rob|7.10.1
stylelint|shi|0.27.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Set the Language Mode to CSS
2. write
```
body {
  color: #fff;
}
```
3. Use Add Line Comment command on an text selection, then Remove Line Comment command
4. See an extra space before and after the selection

Using Add/Remove Line Comment command  (with the  Language Mode set to CSS) on an text selection inserts a single space before and after. 

Reproduces without extensions: Yes

**Comment by spongessuck** [comment] 2017-07-18 04:19
Also seeing this in 1.14.1 when I just use the add comment shortcut (cmd+/ on macOS) on HTML.

**Comment by woncode** [comment] 2017-07-27 09:26
I'm also meet this issue

**Comment by kieferrm** [comment] 2017-08-07 20:51
Duplicate of #30800.

**Comment by alexandrudima** [comment] 2017-08-08 13:19
I think PR #30818 resolved this issue.

**Closed by alexandrudima** 2017-08-08 13:19 UTC
Labels: css-less-sass, html, insiders
