### ISSUE TITLE
Red warning line while editing file with the git control panel

### ISSUE THREAD

**Issue by WillAnd31** [Microsoft/vscode#3445] opened 2016-02-25 08:02 UTC
When editing merge changes in the git control panel when you edit the stash vs. updated upstream changes, if you remove code in the updated/stash code then undo and redo the changes there will be a red/orange bar on the code line that you edited. After than line of code is in orange/red bar you can only remove it by closing the file and reopening it.

Example:

```
var example = function () {
<<<<<<< Updated upstream           (this is a red/orange line)
    var updated;
=======                            (this is a red/orange line)
    var stashed;
>>>>>>> Stashed changes            (this is a red/orange line)
}
```
Then remove the git stashed/updated lines:
```
var example = function () {
    var stashed;
}
```
Then undo the changes:
```
var example = function () {
<<<<<<< Updated upstream           (this is a red/orange line)
    var updated;
=======                            (this is a red/orange line)
    var stashed;
>>>>>>> Stashed changes            (this is a red/orange line)
}
```
Then redo the changes, there will be a red/orange line: 
```
var example = function () {        (this is a red/orange line)
    var stashed;
}
```
Then the only way you can remove that red/orange line is to close the file you're editing and reopen it.

Gif example:
![vscode-bug-gif](https://cloud.githubusercontent.com/assets/11418316/13313394/be9d3dd0-db5a-11e5-8b84-7741e2e42a5e.gif)

**Comment by joaomoreno** [comment] 2016-02-25 08:25
Duplicate of #66. Fix will come next release.

**Closed by joaomoreno** 2016-02-25 08:25 UTC

**Comment by WillAnd31** [comment] 2016-02-25 08:27
@joaomoreno Awesome, thank you!
