### ISSUE TITLE
Version notes view is reset when come back from another document

### ISSUE THREAD

**Issue by miguelangelmy** [Microsoft/vscode#53703] opened 2018-07-06 12:11 UTC
Issue Type: <b>Bug</b>

1. Open version notes from Help -> Version Notes.
2. Scroll down over the content.
3. Open any other document.
4. Go back to version notes.

I've done it with all the extensions disabled.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-markdownlint|Dav|0.18.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
xml|Dot|2.3.1
nbpreviewer|jit|1.0.0
luaide|kan|0.7.1
MagicPython|mag|1.0.12
rainbow-csv|mec|0.4.2
vscode-language-pack-es|MS-|1.25.2
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
csharp|ms-|1.15.2
wordcount|ms-|0.1.0
autodocstring|njp|0.2.1
vscode-yaml|red|0.0.13
unity-tools|Tob|1.0.4
unity-debug|Uni|1.3.0
jinja|who|0.0.8
unity-snippets|Ycl|0.1.2
mono-snippets|zra|0.0.2

</details>

**Comment by mjbvz** [comment] 2018-07-06 21:21
duplicate of #53662

**Closed by mjbvz** 2018-07-06 21:21 UTC
Labels: new release
