### ISSUE TITLE
Custom snippet file should have a schema

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31514] opened 2017-07-27 08:27 UTC
Refs: #31324

Currently editing a javascript.json when editing custom snipets for javascript is a bit tricky because there is no schema.
Having a shema would make the user experience nicer and would make it easier to discover fields, defaults values and so on

**Comment by jrieken** [comment] 2017-07-27 09:24
closing as duplicate of #16702

**Closed** 2017-07-27 09:24 UTC
Labels: duplicate, feature-request, snippets
