### ISSUE TITLE
Error while turning on Settings Sync. No account available

### ISSUE THREAD

**Issue by fredyang** [microsoft/vscode#195532] opened 2023-10-13 03:47 UTC
Try to sync my github account in a new mac machine, got an error "Error while turning on Settings Sync. No account available".
But my github account works in other machines.
Nothing works

**Comment by fredyang** [comment] 2023-10-13 04:14
Find a solution.
1 first uninstall the latest Version: 1.83.1
2. install previous version version 1.82
3. sync your github version, it works
4. then upgrade to 1.83.1

**Comment by TylerLeonhardt** [comment] 2023-10-13 04:53
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Trace`, click the double check mark button. ✔️ ✔️ (enables trace logging as the default)
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Main)` Output channel
* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Info`, click the double check mark button. ✔️ ✔️ (to set the default back to info)

**Comment by gwinkless** [comment] 2023-10-14 12:35
I have the same issue but with MS account: not sure if this is relevant but I found it came about when I (incorrectly) signed into github first, then remembered that I had actually synched my settings with my Microsoft account, so I signed out of the github account, disabled sync, then signed in again with the Microsoft account, at which point this error occurred.

The developer log you requested:

From Main:
2023-10-14 13:22:50.307 [info] update#setState idle
2023-10-14 13:22:51.095 [info] WSL is not installed, so could not detect WSL profiles
2023-10-14 13:23:20.319 [info] update#setState checking for updates
2023-10-14 13:23:20.396 [info] update#setState idle

From Microsoft Authentication:
2023-10-14 13:23:35.757 [info] Getting sessions for all scopes...
2023-10-14 13:23:35.757 [info] Got 1 sessions for all scopes...
2023-10-14 13:23:35.759 [info] [email offline_access openid profile] Getting sessions
2023-10-14 13:23:35.759 [info] [email offline_access openid profile] Got 1 sessions
2023-10-14 13:23:39.689 [info] [email offline_access openid profile] Creating session
2023-10-14 13:23:42.175 [info] [email offline_access openid profile] '<redacted>/1:live.com:<redacted>' session successfully created!
2023-10-14 13:24:36.053 [info] [email offline_access openid profile] Getting sessions
2023-10-14 13:24:36.053 [info] [email offline_access openid profile] Got 2 sessions
2023-10-14 13:24:44.291 [info] [email offline_access openid profile] Getting sessions
2023-10-14 13:24:44.291 [info] [email offline_access openid profile] Got 2 sessions
2023-10-14 13:26:32.449 [trace] No pending tokens to store
2023-10-14 13:26:41.780 [trace] [email offline_access openid profile] Queued getting sessions
2023-10-14 13:26:41.781 [info] [email offline_access openid profile] Getting sessions
2023-10-14 13:26:41.781 [info] [email offline_access openid profile] Got 2 sessions
2023-10-14 13:26:41.781 [trace] [email offline_access openid profile] '<redacted>/1:live.com:<redacted>' Token available from cache, expires in 3572972 milliseconds.
2023-10-14 13:26:41.781 [trace] [email offline_access openid profile] '<redacted>/1:live.com:<redacted>' Token available from cache, expires in 4311394 milliseconds.
2023-10-14 13:26:53.557 [trace] No pending tokens to store
2023-10-14 13:28:07.996 [trace] No pending tokens to store
2023-10-14 13:28:16.942 [trace] No pending tokens to store
2023-10-14 13:30:06.682 [trace] No pending tokens to store

From Settings Sync:
2023-10-14 13:22:50.937 [info] Using settings sync service https://vscode-sync.trafficmanager.net/
2023-10-14 13:22:50.937 [info] Auto Sync is disabled.

Hope this is helpful. I will try installing previous version to try to resolve.

**Comment by andi1984** [comment] 2023-10-15 18:48
Same for me.

On MacOS I can only sync with Github account, on Ubuntu it is vice versa.

**Comment by thisisjaymehta** [comment] 2023-10-17 12:44
I also signed in with Github first, then signed in with Microsoft account (but staying signed in to Github as well).

![image](https://github.com/microsoft/vscode/assets/31812582/f300886f-8d1d-4de5-8cf6-86abe0bebaf9)

Then I tried to Backup my settings but it started giving "No account available" error.

I dont want to install previous version as I dont want to lose my settings. Hope it gets fixed in a update.

**Comment by sino1641** [comment] 2023-10-17 16:52
Hi Team, 
I have the same issue here with the latest insider 1840
## Reproduce
- A new vscode installation on win11
- Login GitHub account first and sync turned on automatically
- Turn off setting sync and log out
- Login MS account successfully (As above, no error in extension _MS account_ log)
- Turn on sync with MS account
- No new log printted in _Settings Sync_ log
- Error occurred: `Error while turning on Settings Sync. No account available`

## Workaround
But it seems we have figured a workaround to downgrade vscode version which also works here.

**Comment by TylerLeonhardt** [comment] 2023-10-17 22:41
@sandy081 any ideas? Auth side looks fine.

**Comment by parkeraddison** [comment] 2023-10-18 00:55
This seems to be related to only being able to log in to a single GitHub account.

Once you've logged in to GH you only have the option to "Sign in with Microsoft" for Settings Sync.
![image](https://github.com/microsoft/vscode/assets/33291380/16de3a2b-7174-4552-81a7-b08f4e453c1e)

I used to have two GitHub accounts logged in — one personal for Settings Sync, and other for my company's GitHub. Trying to replicate this same setup now is causing either:
1. Log in first to personal GH for Settings Sync, but this automatically logs you into all GH authentication and there's no way to switch over to the work account for proper repo access; or
2. Log in first to work GH for repo access, but then the only remaining option for Setting Sync is to sign in with Microsoft which leads to "No account available." (even if you sign into the MS account via GH credentials)

Hopefully this helps track down the cause!

**Comment by sandy081** [comment] 2023-10-19 13:31
May be related to the refactoring I did to fetch accounts lazily. But I cannot reproduce locally, would like to have repro steps or logs.

Can some one who is able to repro share the window log? Also please try our [insider](https://code.visualstudio.com/insiders/) and see if you can repro there too?

**Comment by kymckay** [comment] 2023-10-23 08:47
@sandy081  I can reproduce on 1.83.1 and window log seems empty:

```log
2023-10-23 09:38:08.278 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-23 09:38:08.287 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-23 09:38:11.387 [info] [perf] Render performance baseline is 17ms
```

GitHub Authentication for completeness:
```
2023-10-23 09:38:10.767 [info] Reading sessions from keychain...
2023-10-23 09:38:10.767 [info] Getting sessions for all scopes...
2023-10-23 09:38:10.767 [info] Got stored sessions!
2023-10-23 09:38:10.767 [info] Got 1 verified sessions.
2023-10-23 09:38:10.767 [info] Got 1 sessions for ...
2023-10-23 09:38:10.767 [info] Getting sessions for all scopes...
2023-10-23 09:38:10.767 [info] Got 1 sessions for ...
2023-10-23 09:38:10.767 [info] Getting sessions for read:user,repo,user:email,workflow...
2023-10-23 09:38:10.767 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2023-10-23 09:38:10.768 [info] Getting sessions for read:user,repo,user:email...
2023-10-23 09:38:10.768 [info] Got 0 sessions for read:user,repo,user:email...
2023-10-23 09:38:22.425 [info] Getting sessions for user:email...
2023-10-23 09:38:22.425 [info] Got 1 sessions for user:email...
2023-10-23 09:39:06.941 [info] Getting sessions for user:email...
2023-10-23 09:39:06.941 [info] Got 1 sessions for user:email...
```

**Comment by sandy081** [comment] 2023-11-01 09:37
Steps to Repro:

- Turn on Settings Sync using GitHub account
- Turn off Settings Sync
- Turn on Settings Sync using MSFT account
🐛 Error: No account available

**Closed** 2023-11-07 13:12 UTC
Labels: bug, candidate, settings-sync

**Comment by solagirl** [comment] 2023-11-08 02:21
> MacOS I can only s
Deleting the code folder works for me, thank you!

**Comment by kingma-sbw** [comment] 2023-11-08 17:50
Same here. Setup Windows 10 new installed vscode and signed in on my private microsoft (hotmail) account and my office/school account on github. The settings I want to sync with are setup on my private account but attmpts to sync result in the error message. My version 1.84.1. This problem is not solved

**Comment by James-Caesar** [comment] 2023-11-10 00:10
SAME HERE, Hi Anytime I launch VSCODE i get this message turn on sync settings but  i already did login with my github account already about three years ago until version 1.82 i get that message anytime i launch VSCODE Please Fix it it keeps bugging me down please. Thanks.

**Comment by James-Caesar** [comment] 2023-11-10 00:12
IS STILL KEEPS SHOWING AFTER I UPDATED TO VERSION  1.84.2

**Comment by sandy081** [comment] 2023-11-13 08:35
@James-Caesar Your issue seems to be different from here. Please file a separate issue with steps to reproduce.
