### ISSUE TITLE
Add way to open Markdown links in a different editor group

### ISSUE THREAD

**Issue by tedhudek** [microsoft/vscode#26659] opened 2017-05-15 14:51 UTC
Scenario:

Markdown file is open in left editor group.  This file has a lot of links to other .md files that I want to preview in the right editor group.  But  Markdown links can currently only be opened into the same editor.

Please consider.  Thanks!

**Comment by tedhudek** [comment] 2017-05-15 14:52
Adding @gregvanl per our discussion about this one

**Comment by mjbvz** [comment] 2017-05-16 18:05
@tedhudek Do you mean that you would like an option to make the `open preview to side` command to open the preview to the left instead of to the right of the current editor?

**Comment by tedhudek** [comment] 2017-05-16 20:30
@mjbvz No, sorry, I should have been more specific.  Here's what I mean:

1. Double-click to open a .md file in a persistent editor in Code, preferably a file with many links to other local .md files.
2. In the file, Ctrl+click a link to another .md file.
3. The other file opens in a new editor, in the same editor group.

Desired: open the link as a raw .md file in a new or existing (separate) editor group.
Then, when I go back to the original file and ctrl+click another .md link, open that raw .md into the same editor group the previous one opened into.  So I can quickly ctrl+click through a bunch of links and see the raw .md while my original file (the one with all the links) stays in view.

**Comment by mjbvz** [comment] 2017-05-17 18:24
Ok, thanks for explaining the expected behavior in more detail. Marking as help wanted if anyone wants to investigate this. To get started look at:

* [`normalizeLink` in `documentLinkProvider.ts`](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/documentLinkProvider.ts#L42) This is where we  map markdown links to `_markdown.openDocumentLink`  command links

* [The handler of `_markdown.openDocumentLink` in `extension.ts`](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts#L143) This is where we convert the command into an editor action. Instead of opening in the current editor, we would want to open in a new editor group here

**Closed** 2019-09-10 22:58 UTC
Labels: feature-request, help wanted, markdown

**Comment by mjbvz** [comment] 2019-09-10 23:59
For verification:

1. A new setting was added called `"markdown.links.openLocation"`
1. There are two options: `"currentGroup"` (the default) and `"beside"`
1. All links in md text files (not the preview) should respect this option
1. The default behavior should be to open links in the current group

**Comment by alexr00** [comment] 2019-10-02 15:00
Can't verify because of https://github.com/microsoft/vscode/issues/81849

**Comment by sandy081** [comment] 2019-10-02 15:04
I can verify this on Mac.

**Comment by tedhudek** [comment] 2019-10-02 16:36
Thanks for adding this!
