### ISSUE TITLE
Crash when using dev tools from VS Code

### ISSUE THREAD

**Issue by yasirs** [Microsoft/vscode#5628] opened 2016-04-21 21:25 UTC
- VSCode Version:1
- OS Version:10.9.5

Steps to Reproduce:
I am not sure, but I am attaching the crash report.
[vscode.crashreport.txt](https://github.com/Microsoft/vscode/files/230760/vscode.crashreport.txt)

**Comment by bpasero** [comment] 2016-04-21 21:40
@yasirs looks like you opened developer tools in VS Code, could that be true?

**Comment by yasirs** [comment] 2016-04-21 22:19
Yes. I'd just installed it and was exploring the interface.

**Comment by bpasero** [comment] 2016-04-22 06:02
This is https://github.com/electron/electron/issues/4261

**Comment by bpasero** [comment] 2016-09-16 05:16
Duplicate of https://github.com/Microsoft/vscode/issues/4430

**Closed by bpasero** 2016-09-16 05:16 UTC
Labels: bug, electron-update, upstream
