### ISSUE TITLE
TypeScript generic syntax highlighting is incorrect

### ISSUE THREAD

**Issue by tmct** [Microsoft/vscode#9130] opened 2016-07-12 14:26 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Type the following code into a VS code editor window:
 ```
    private myOtherMethod(argName: int) {
        console.log("?");
    }

    private myMethod(argName: Dictionary<int>) {
        console.log("?");
    }

    private myThird(argName: Number) {
        console.log("?");
    }
```
2. Set the syntax to "TypeScript React"
3. From the second function's body onwards, the syntax is highlighted incorrectly (I'm colourblind, but it's different to the first function body at the very least!)

**Comment by aeschli** [comment] 2016-07-13 09:40
duplicate of #8045

**Closed by aeschli** 2016-07-13 09:40 UTC
