### ISSUE TITLE
Error While Changing Settings Didnt Press Save But error appeared in invaild json

### ISSUE THREAD

**Issue by brianherman** [Microsoft/vscode#57562] opened 2018-08-30 03:42 UTC
```
[Error - 10:33:26 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 10:33:26 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 10:33:27 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
```

https://pbs.twimg.com/media/Dl0W_EpUwAEt9Hv.jpg
1. File >> Preferences >> Settings Ctrl-Comma
2. Paste the following into the Workpaces Settings Editor

```
  // Enable this workaround if scrolling is no longer smooth after restoring a minimized VS Code window. This is a workaround for an issue (https://github.com/Microsoft/vscode/issues/13612) where scrolling starts to lag on devices with precision trackpads like the Surface devices from Microsoft. Enabling this workaround can result in a little bit of layout flickering after restoring the window from minimized state but is otherwise harmless.
  "window.smoothScrollingWorkaround": false,

  // Controls whether to use .gitignore and .ignore files when searching for files.
  "search.useIgnoreFiles": true,

  // Whether auto fetching is enabled
  "git.autofetch": false,

  // Whether auto refreshing is enabled
  "git.autorefresh": true,

  // Whether repositories should be automatically detected
  "git.autoRepositoryDetection": true,

  // Controls what type of branches are listed when running `Checkout to...`. `all` shows all refs, `local` shows only the local branches, `tags` shows only tags and `remote` shows only remote branches.
  "git.checkoutType": "all",

  // Confirm before synchronizing git repositories
  "git.confirmSync": false,

  // Controls the git badge counter. `all` counts all changes. `tracked` counts only the tracked changes. `off` turns it off.
  "git.countBadge": "off",

  // Controls if Git contributes colors and badges to the explorer and the open editors view.
  "git.decorations.enabled": false,

  // The default location where to clone a git repository
  "git.defaultCloneDirectory": null,

  // Controls whether to automatically detect git submodules.
  "git.detectSubmodules": false,

  // Controls the limit of git submodules detected.
  "git.detectSubmodulesLimit": 10,

  // Enables commit signing with GPG.
  "git.enableCommitSigning": false,

  // Whether git is enabled
  "git.enabled": false,

  // Commit all changes when there are no staged changes.
  "git.enableSmartCommit": false,

  // Ignores the legacy Git warning
  "git.ignoreLegacyWarning": false,

  // Ignores the warning when there are too many changes in a repository
  "git.ignoreLimitWarning": false,

  // Ignores the warning when Git is missing
  "git.ignoreMissingGitWarning": false,

  // Controls when to show commit message input validation.
  "git.inputValidation": "warn",

  // Path to the git executable
  "git.path": null,

  // Controls whether Git should check for unsaved files before committing.
  "git.promptToSaveFilesBeforeCommit": false,

  // Controls whether to show an inline Open File action in the Git changes view.
  "git.showInlineOpenFileAction": true,

  // Configure editor settings to be overridden for [git-commit] language.
  "[git-commit]": {
    "editor.rulers": [
      72
    ]
  }

```
3. Get output error at the bottom.
4. T_T

**Comment by brianherman** [comment] 2018-08-30 03:49
Should I close this I didn't read the error it's actually in the vscode-json-languageservice repo not this one:
```
[Error - 10:33:26 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 10:33:26 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 10:33:27 PM] Error while computing hover for file:///c%3A/Users/bherman/AppData/Roaming/Code/User/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
```

**Comment by brianherman** [comment] 2018-08-30 03:54
```
	public doHover(document: TextDocument, position: Position, doc: Parser.JSONDocument): Thenable<Hover> {

		let offset = document.offsetAt(position);
		let node = doc.getNodeFromOffset(offset);
		if (!node || (node.type === 'object' || node.type === 'array') && offset > node.offset + 1 && offset < node.offset + node.length - 1) {
			return this.promise.resolve(null);
		}
		let hoverRangeNode = node;

		// use the property description when hovering over an object key
		if (node.type === 'string') {
			let parent = node.parent;
			if (parent && parent.type === 'property' && parent.keyNode === node) {
				node = parent.valueNode;
				if (!node) {
					return this.promise.resolve(null);
				}
			}
		}
```
Looks like the null check is there so I guess it will be fixed next month with the next update?

**Comment by aeschli** [comment] 2018-08-30 07:59
duplicate of https://github.com/Microsoft/vscode-json-languageservice/issues/25

I verified it's fixed in latest

**Closed by aeschli** 2018-08-30 07:59 UTC
