### ISSUE TITLE
Support multiple levels in TreeView menu

### ISSUE THREAD

**Issue by caadam** [Microsoft/vscode#66232] opened 2019-01-08 21:45 UTC
Just like the WPF/Win32 treeview I'd like to see support for multiple levels in the treeview context menu.

For example:

![image](https://user-images.githubusercontent.com/9862845/50860791-8bc52300-13e2-11e9-84a0-8a98149e80de.png)

**Comment by RMacfarlane** [comment] 2019-01-09 00:32
Duplicate of https://github.com/Microsoft/vscode/issues/9827

**Closed by RMacfarlane** 2019-01-09 00:32 UTC
