### ISSUE TITLE
Autocomplete on typing `(` - it should not assume a choice never made

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#139768] opened 2021-12-26 12:06 UTC
Assume a TypeScript node/express project and the following code:

```ts
function routeHandler(req: Request, res: Response){
  try {
    res.send('good')
  } catch (err){
    next|   // here | denotes the caret
  }
}

```
Let's note that at this point `next: NextFunction` is missing from the handler signature.
At this point, when typing `next`, the only available autocomplete suggestion is most probably something else, in my case it is `nextTick`. 

As long as `next` remains typed - suggesting `nextTick` is perfectly ok.
But the moment user continues to type `(` - `nextTick` should no longer be offered as an autocomplete option, furthermore, it should not be assumed that user has selected it - which is exactly what is happening.

`next(` !== `nextTick()`

The opening parenthesis should be treated as user's closing the text input and dismissing autocomplete if nothing matched.

Current behavior is very confusing and requires post-massaging of the generated code, I believe there should be a preference setting to control this flow.

**Comment by IllusionMH** [comment] 2021-12-26 22:10
Basically, duplicate of #62466
This is controlled by "Editor: Accept Suggestion On Commit Character" setting (`editor.acceptSuggestionOnCommitCharacter`) and `(` is one of these characters for JS/TS.

Same applicable for `re|` and typing `.` to accept `res` and start typing `send` without need to complete whole name and press <kbd>Tab</kbd>/<kbd>Enter</kbd> to accept.

In your case you'll need to disable auto accept with setting above or press <kbd>Esc</kbd> to dismiss suggestions.

**Closed** 2022-01-03 08:27 UTC
