### ISSUE TITLE
IW is not visually marked as unsaved

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#186368] opened 2023-06-27 16:44 UTC
Testing #186196 on Linux

In the last step, the IW prompts for a save before the editor exits. However, unlike normal files (or custom editors), its tab is not visually marked as being "unsaved". If it quacks like an unsaved file, should it look like an unsaved file?

![image](https://github.com/microsoft/vscode/assets/2230985/5f074280-974b-4c93-97af-82ce2c22c681)

**Comment by amunger** [comment] 2023-06-27 20:20
this is by design - scratchpads are never marked dirty. You also don't get a prompt when closing the tab manually for the same reason

**Closed by amunger** 2023-06-27 20:20 UTC
