### ISSUE TITLE
Allow themes to overwrite icons in suggest widget

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode#52606] opened 2018-06-21 12:46 UTC
I think enabling color theme extension developers to style Suggestions pane would improve the UI a lot. Current suggestions don't look bad, but there's a room for improvements. Making it configurable will also make themes look unique.  
As a reference:
[styled suggestions that look better](https://i.github-camo.com/c90b92e60288c36d664f03908ba025d6480b0c38/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f3734343734302f373635363836312f39666238626363342d666165612d313165342d393831342d3964636132313864656439332e706e67)
[styled suggestions that look better 2](https://i.imgur.com/M70Csn6.png)

**Comment by misolori** [comment] 2019-10-08 19:55
Duplicate of https://github.com/microsoft/vscode/issues/79130

**Closed by misolori** 2019-10-08 19:55 UTC
Labels: feature-request, suggest
