### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by mikiurbi** [microsoft/vscode#94980] opened 2020-04-11 08:56 UTC
Issue Type: <b>Bug</b>

After update to version 1.44, VS Code shows me the message "Extension host terminated unexpectedly". Even after un-install and re-install from scratch (without any extension), it shows me the same message. What can I do to solve this issue?

Thanks, -Michele-

This is the console output:

console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, open 'c:\Users\Michele\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js'
t.log @ console.ts:137
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
extensionHostProcessManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostProcessManager.ts:73
extensionHostProcessManager.ts:74 timeout
(anonymous) @ extensionHostProcessManager.ts:74
lifecycle.ts:133 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at e.add (lifecycle.ts:133)
    at e._register (lifecycle.ts:163)
    at extensionHostProcessManager.ts:80

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|4.2.0
latex-workshop|Jam|8.8.0
python|ms-|2020.3.71659
remote-wsl|ms-|0.44.2
indent-rainbow|ode|7.4.0
trailing-spaces|sha|0.3.1
vscodeintellicode|Vis|1.2.6

</details>

**Comment by gjsjohnmurray** [comment] 2020-04-11 09:56
/duplicate of #94807, please let us know if the discussion in #94858 (comment) does not solve the problem

**Closed** 2020-04-11 09:56 UTC
Labels: *duplicate, new release
