### ISSUE TITLE
Debugging is broken

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#41227] opened 2018-01-06 17:44 UTC
- VSCode Version: 1.20 insiders
- OS Version: Ubuntu 17.10 + Linux 4.14.12

Steps to Reproduce:

1. Try to debug a project that used to debug beforehand
2. Notice that breakpoints set are only listed in the viewlets, the editor does not show red circles in the gutter
3. Notice that breakpoints no longer hit

Does this issue occur when all extensions are disabled?: cannot test as debugger is an extension

**Comment by borgdylan** [comment] 2018-01-06 17:53
This was tested using the vscode-mono-debug extension. Used to work on the holiday themed builds of code-insiders.

**Comment by Eli-Goldberg** [comment] 2018-01-07 20:43
Reproduces
- VSCode Version: Code - Insiders 1.20.0-insider (c4065a8ba5261456338f850a37e67732d98bf57a, 2018-01-05T08:08:12.523Z)
- OS Version: Linux x64 4.10.0-42-generic

**Comment by auchenberg** [comment] 2018-01-07 23:02
This issue was moved to Microsoft/vscode-mono-debug#42

**Comment by weinand** [comment] 2018-01-08 09:48
This problem is independent from the mono debugger: I can reproduce this with JavaScript debugging too. There seems to be an issue with decorations on linux.

**Comment by isidorn** [comment] 2018-01-08 14:03
Duplicate of https://github.com/Microsoft/vscode/issues/41273

**Closed by isidorn** 2018-01-08 14:03 UTC
Labels: debug, insiders

**Comment by borgdylan** [comment] 2018-01-08 20:47
The not stopping on breakpoints was my fault, had swicth5d by compil5r to multi threaded parsing and it was not flowing paths right.

The GUI issues were fixed by the latest insiders updates. Thanks!

**Comment by isidorn** [comment] 2018-01-09 09:06
@borgdylan thanks for verifying, adding verified label
