### ISSUE TITLE
Editor cannot fold/unfold XML element if not properly indented

### ISSUE THREAD

**Issue by pL-2** [Microsoft/vscode#50455] opened 2018-05-25 12:41 UTC
Issue Type: <b>Bug</b>

Editing an xml file, the editor cannot fold/unfold xml start and end node if not properly indented:
```  
  <Root>
    <InnerElement /> 
</Root>
```

That is, `<Root>` is more indented than `</Root>`. 
Very annoying. Thank you.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-it|MS-|1.23.1
python|ms-|2018.4.0
csharp|ms-|1.15.2

</details>

**Comment by aeschli** [comment] 2018-05-28 09:31
duplicate of #46200

**Closed by aeschli** 2018-05-28 09:31 UTC
Labels: editor
