### ISSUE TITLE
opening files in command pallete on macOS is case-sensitive despite the OS file system isn't

### ISSUE THREAD

**Issue by ClovisIRex** [Microsoft/vscode#51079] opened 2018-06-04 12:08 UTC
- VSCode Version: 1.23.1
- OS Version: macOS High Sierra 10.13.4

Steps to Reproduce:

1. Inside vscode file viewer, create a file inside a folder, e.g "exampleFile.js"
2. Inside vscode file viewer, rename the file with different case letters, e.g "ExAmplefiLe.js"
3. Now both versions of the file appear when quick-navigating inside command pallete(cmd+shift+o) as two different files. When editing one, the "other" also gets updated(because obviously in the OS file system it is a single file).

Does this issue occur when all extensions are disabled?: Yes

Pretty annoying, if I rename a bunch of files and only updating their uppercase or lowercase I can still see the files before the change as separate files despite them being the same file.

**Comment by isidorn** [comment] 2018-06-04 12:18
Probably duplicate of some issue we have. Forwarding to @bpasero to decide

**Comment by bpasero** [comment] 2018-06-04 12:35
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-06-04 12:35 UTC
