### ISSUE TITLE
1.33 Massive performance issues

### ISSUE THREAD

**Issue by leeandher** [Microsoft/vscode#71751] opened 2019-04-05 01:07 UTC
- VSCode Version: 1.33
- OS Version: Windows 10 (v1809)

Steps to Reproduce:

1. Launch VSCode

Does this issue occur when all extensions are disabled?: Yes

After updating to the latest version of VSCode, it became pretty much unusable. I mainly work on web development, so that's all that I could speak on but things became measurably slower.

At idle it was consuming 45+% of CPU usage and ~1 GB RAM

Errors stopped dismissing/updating:
![image](https://user-images.githubusercontent.com/35509934/55597635-85fa8780-571c-11e9-84f5-2a6cb69406e7.png)

Suggestions/Intellisense stopped showing up (or took 3s+ to show up if at all):
![image](https://user-images.githubusercontent.com/35509934/55597755-29e43300-571d-11e9-9d91-126c94331fcb.png)

Emmet/Tag autocomplete stopped functioning:
![image](https://user-images.githubusercontent.com/35509934/55597784-4f713c80-571d-11e9-9b75-83509d21f9c1.png)

When I downgraded, it seemed to all go away, I tried reinstalling 3 times, everytime I selected the upgrade the problems came back. I also restarted VSCode and my computer multiple times. For now, I'm just staying at 1.32.3.

**Comment by mjbvz** [comment] 2019-04-05 01:09
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

Could be https://github.com/Microsoft/TypeScript/issues/30663

**Comment by leeandher** [comment] 2019-04-05 01:15
**`code --status` output**:
```
Version:          Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)
Memory (System):  15.87GB (8.62GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    1       85   14656  code main
    0      195    3560     window (Release Notes: 1.33.0 - leander.xyz - Visual Studio Code)
    0       34    5616       searchService
    0       14    7700       electron-crash-reporter
    0      110   14692       extensionHost
    0       53    5696         electron_node server.js
    0       32   13164         "C:\Users\leand\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\leand\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=14692
    0       73   13836         electron_node eslintServer.js
    8      433   16508         electron_node tsserver.js
    0       45   11968           electron_node typingsInstaller.js typesMap.js
    0       11   15216       watcherService
    0       11   10456         console-window-host (Windows internal process)
    0       65   15688     shared-process
    0       87   17900     gpu-process
    0       88   18324     window (undefined)

Workspace Stats:
|  Window (Release Notes: 1.33.0 - leander.xyz - Visual Studio Code)
|    Folder (leander.xyz): 480 files
|      File types: js(173) json(140) map(47) png(37) html(22) svg(12) md(11)
|                  gitkeep(9) yml(5) webmanifest(4)
|      Conf files: package.json(3) settings.json(1)
```

**Comment by leeandher** [comment] 2019-04-05 01:17
I might be incorrectly identifying this as a performance issue, but it's definitely disabling the above features in the editor some how.

The related issue seemed to be a TypeScript, which I'm not using. I am using `styled-components` at `^4.1.3` though.

**Comment by mjbvz** [comment] 2019-04-05 02:22
Thanks. Yes this is in all likelihood a duplicate of Microsoft/TypeScript#30663. Typescript also powers our JavaScript intellisense so this is the correct issue even though you are not writing typescript

Two possible workarounds:

* Downgrade your workspace to use `typescript@3.3` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

* Try to install `@types/styled-components@4.1.5` into your workspace. See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391 for more details

**Closed by mjbvz** 2019-04-05 02:22 UTC

**Comment by janosh** [comment] 2019-04-06 13:12
@mjbvz  Thanks for this advice! `rm -r ~/Library/Caches/TypeScript/3.4` (Mac) indeed solved the issue for me.

**Comment by mupkoo** [comment] 2019-04-08 22:06
This fixes the problem, but the performance is really bad...

**Comment by Daniel-Griffiths** [comment] 2019-04-09 09:11
I also have really bad performance after upgrading VS Code to 1.33

**Comment by grepug** [comment] 2019-04-11 06:01
downgrading typescript to 3.3.3 solved this problem

**Comment by ReaperTech** [comment] 2019-05-01 15:44
problem solved by: npm install --save-dev typescript@3.3 (which installed 3.3.4 into my workspace), then select the typescript version in the bottom of the vsc window and select "use workspace version 3.3.4"

**Comment by Daniel-Griffiths** [comment] 2019-05-01 16:24
Just upgraded to the latest version of VSCode and that workspace trick worked for me @ReaperTech 

Eventually it would be nice to have a real solution to this instead of downgrading though :sweat_smile:

**Comment by ReaperTech** [comment] 2019-05-01 16:32
I'm glad it worked for you @Daniel-Griffiths ! Maybe they will fix in the next release.

**Comment by ReaperTech** [comment] 2019-05-01 18:15
problem also caused by extension "angular language service 0.1.11"

**Comment by loolooii** [comment] 2019-05-09 11:18
@ReaperTech solution worked perfectly for me! Thanks!

**Comment by zjaml** [comment] 2019-05-14 13:10
I have a nodejs project and a react project both suffering from this problem, although there's no typescript in any of them.
by doing only the following seemed to fix both problem. (didn't have to choose TS version.)
`npm install --save-dev typescript@3.3 `

**Comment by janosh** [comment] 2019-05-15 12:02
If don don't want to have to do this on a per-project basis, you can also install TypeScript 3.3 globally
```sh
 yarn global add typescript@3.3
```
and then in your `settings.json` add the line
```json
{
  "typescript.tsdk": "~/.config/yarn/global/node_modules/typescript/lib/"
}
```

**Comment by natterstefan** [comment] 2019-05-16 06:23
Thank you @mjbvz, worked for me!

**Comment by antoinerousseau** [comment] 2019-05-19 18:31
Globally installing the next (dev) version of TypeScript (with `npm i -g typescript@next`),
and adding it to my settings solved the issue for me.

To add to your settings, go to preferences > settings, type `tsdk`, in User tab edit `settings.json` as suggested, add this line (if installed via npm, otherwise see @janosh's comment) :
```json
"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/",
```
And then in a TypeScript file, in the bottom right of the editor, click on the TypeScript version (like 3.x.x) and choose "Use VSCode's version (3.5.x)"
