### ISSUE TITLE
Bad notebook experience when switching to a profile without notebook extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#184496] opened 2023-06-07 11:51 UTC
The introduction of profiles has made it more likely that a user would switch to a different set of extensions in a different profile while notebook editors are opened. Notebook editors are sensitive in a sense that they require an extension providing the view type to be present in order to deal with the notebook editor.

If the profile you switch to does not provide the view type for the notebook editor, things get problematic.

In my testing I see 2 issues:

**1. Notebook editor shows up as dirty**

I can reproduce with the `ms-vscode.vscode-github-issue-notebooks` extension that the GH notebook immediately becomes dirty after switching the profile:

![Recording 2023-06-07 at 13 34 11](https://github.com/microsoft/vscode/assets/900690/41dc51cb-b7df-48d1-ad71-ab2724c81882)

This seems to be triggered from a change to the language. This is especially hard for the user to digest because the impression is made that user changes are unsaved but at the same time require the extension to save.

<details>
  <summary>Stacktrace</summary>

```
(anonymous) (workingCopyService.js:47)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
setDirty (storedFileWorkingCopy.js:128)
onModelContentChanged (storedFileWorkingCopy.js:418)
(anonymous) (storedFileWorkingCopy.js:383)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
(anonymous) (notebookEditorModel.js:162)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
(anonymous) (notebookTextModel.js:199)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
fire (event.js:949)
_bindCellContentHandler (notebookTextModel.js:249)
(anonymous) (notebookTextModel.js:222)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
set language (notebookCellTextModel.js:59)
(anonymous) (notebookCellTextModel.js:111)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
setLanguageId (tokenizationTextModelPart.js:217)
_setLanguage (textModel.js:1467)
(anonymous) (textModel.js:184)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
_evaluate (languageService.js:150)
(anonymous) (languageService.js:132)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
(anonymous) (languageService.js:23)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
_registerLanguages (languagesRegistry.js:99)
_initializeFromRegistry (languagesRegistry.js:73)
setDynamicLanguages (languagesRegistry.js:64)
(anonymous) (languageService.js:139)
_handle (extensionsRegistry.js:87)
acceptUsers (extensionsRegistry.js:80)
_handleExtensionPoint (abstractExtensionService.js:856)
_doHandleExtensionPoints (abstractExtensionService.js:804)
_deltaExtensions (abstractExtensionService.js:202)
_handleDeltaExtensions (abstractExtensionService.js:144)
await in _handleDeltaExtensions (async)
(anonymous) (abstractExtensionService.js:89)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
(anonymous) (event.js:1037)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
(anonymous) (event.js:98)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
whenProfileChanged (extensionManagementChannelClient.js:70)
await in whenProfileChanged (async)
(anonymous) (extensionManagementChannelClient.js:16)
invoke (event.js:660)
deliver (event.js:836)
fire (event.js:800)
updateCurrentProfile (userDataProfileService.js:42)
enterProfile (userDataProfileManagement.js:106)
await in enterProfile (async)
switchProfile (userDataProfileManagement.js:91)
await in switchProfile (async)
run (userDataProfile.js:125)
handler (actions.js:360)
invokeFunction (instantiationService.js:46)
_tryExecuteCommand (commandService.js:81)
executeCommand (commandService.js:50)
run (actions.js:340)
runAction (actions.js:114)
run (actions.js:106)
runAction (contextmenuService.js:203)
click (contextmenuService.js:179)
onClickChannelHandler (contextmenu.js:16)
onceWrapper (VM2302 sandbox_bundle:2)
emit (VM2302 sandbox_bundle:2)
onMessage (VM2302 sandbox_bundle:2)
```
</details>

**2. Notebook editor allows for editing**

The notebook editor does not close, nor does it turn readonly. As such, a user may continue to make edits, but will not be able to save that data, potentially resulting in data loss. I would suggest here to turn the notebook readonly and show a notification to the user if we know that the extension for the notebook is missing.

//cc @joaomoreno @kieferrm

**Comment by rebornix** [comment] 2023-06-07 17:25
The first issue was caused by language change, as the notebook model says the cell text model language should be `github-issues` but we didn't find any extension offering such language, thus it falls back to `plaintext`. This is one case where transferring the notebook editor model to the new profile will lead to unexpected issues.

Notebook component doesn't know if the same provider would exist after the EH restart (as it doesn't know why EH restarts), the only safe solution for notebook is saving the notebook and close the editor. If it also applies to Custom Editor, I wonder if it should be done by the editor service.

**Comment by bpasero** [comment] 2023-06-07 19:16
@amunger 

> We could probably handle both of these points by trying to follow the same experience as when you reload with that specific extension disabled:

Yes, I like that. It requires though that the notebook does not immediately turn dirty due to the language change. If that can be ensured I like the approach as it matches the behaviour after window reload 👍

**Comment by joaomoreno** [comment] 2023-06-09 12:08
Adding my 2 cents from the perspective of someone who doesn't know all implementation details:

- It's unexpected for the user to have their files saved whenever they switch profiles
- It's confusing for the user as to why some files are (notebooks) and others aren't (text files)

I argue we should provide the exact same experience for notebooks that we do for text files, and tactically address the spiky situations by using UX ingenuity. The spiky situation is: user tries to save a notebook when there's no extension around that can handle that notebook serialization. This is completely unrelated to profiles, as @amunger pointed out.

Let's try to contain the product decisions we're making to that very specific user action:

- Attempting to either save the notebook or reload/quit the workbench int hat state should always result in the same: modal dialog asking the user to either _discard changes_ or _install extension_. There's no way out of this.
- We can minimize the occurrences of this modal dialog by making the user aware of the situation they are in. One low hanging fruit idea is to use the editor banner. The banner would show as long as the user is in that situation and disappear as soon as the user switches to an environment in which there's an extension capable of handling the serialization of the notebook.

![image](https://github.com/microsoft/vscode/assets/22350/661b503e-0287-47ae-a789-7a6b8fe15cea)

Consider profile A (with notebook extension) and profile B (without notebook extension):

- Dirty notebooks would remain dirty as the user switches between profiles A and B.
- Switching to profile B and switching back to profile A and saving a dirty notebook should just work, independently whether the notebook got dirty when the user was originally in profile A or when the user was temporarily in profile B.

From what I can tell, this would produce a great user experience, minimize unexpected situation and remove confusion. Also, I believe all pieces of our infrastructure can be put together to correctly support this scenario. Please correct me if I'm wrong.

cc @sandy081

**Comment by amunger** [comment] 2023-06-09 15:13
I don't know if we would be able to detect dirty state changes without the serializer provided by the extension that is missing in profile B. So we'd probably have to be in a read-only dirty state, and that sounds pretty odd.

**Comment by joaomoreno** [comment] 2023-06-12 13:57
@amunger I don't understand what specific scenario you are referring to, nor what you mean by "detect". Can you elaborate?

**Comment by amunger** [comment] 2023-06-14 15:45
I believe so, we check if a provider has been registered for the specific viewtype [here](https://insiders.vscode.dev/github/microsoft/vscode/blob/aamunger/fileBackedIW/src/vs/workbench/contrib/notebook/browser/services/notebookServiceImpl.ts#L619).
We would just need to go into a read-only state on EH stop, since there is a gap of time between that and when we know that the extension isn't coming back.

**Comment by bpasero** [comment] 2023-06-14 15:48
It could turn read-only when the user makes an attempt to change the notebook no? I think this only works really well if there is also a information banner in the editor to educate the user how to make it editable.

**Comment by amunger** [comment] 2023-12-05 18:14
I think we handle most scenarios reasonably well at this point 
- we leave the language of the cell alone if we don't recognize it and visually indicate that it isn't supported
- we force the user to save dirty notebooks or block the profile switch operation
- If a notebook becomes dirty and we don't have a supporting extension, we show a notification:
![image](https://github.com/microsoft/vscode/assets/2019016/b2dde126-7538-42a1-b084-8e01ae14e81e)

**Closed by amunger** 2023-12-05 18:14 UTC
Labels: notebook, papercut :drop_of_blood:
