### ISSUE TITLE
Extension host terminates repeatedly (insiders)

### ISSUE THREAD

**Issue by tsabolov** [microsoft/vscode#118022] opened 2021-03-03 07:54 UTC
Issue Type: <b>Bug</b>

The extension host just crashes causing all the extensions to stop. It's possible to restart it from the popping alert, but it stops again after some time.

VS Code version: Code - Insiders 1.54.0-insider (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-02T19:14:33.180Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 14003d70-0772-4ffd-a913-83e3926021af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
macos-modern-theme|dav|2.1.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.23.1
gitlab-workflow|Git|3.13.0
todo-tree|Gru|0.0.199
vscode-favorites|how|1.8.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.600686576
cpptools|ms-|1.2.2
vetur|oct|0.33.0
rust|rus|0.7.8
vscode-icons|vsc|11.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15

(1 theme extensions excluded)

</details>

<details>
<summary>DevTools console contents</summary>

```
console.ts:137 [Extension Host] [vscode-icons] v11.1.0 activated! (at /Users/[redacted]/.vscode-insiders/extensions/vscode-icons-team.vscode-icons-11.1.0/dist/src/vscode-icons.bundle.js:9:209248)
abstractExtensionService.ts:466 Extension host terminated unexpectedly. Code:  null  Signal:  SIGBUS
_onExtensionHostCrashed @ abstractExtensionService.ts:466
log.ts:296   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git, CoenraadS.bracket-pair-colorizer-2, cssho.vscode-svgviewer, EditorConfig.EditorConfig, GitLab.gitlab-workflow, vscode-icons-team.vscode-icons, zhuangtongfa.material-theme, vscode.npm, yzhang.markdown-all-in-one, ms-vscode.js-debug, vscode.github-authentication, vscode.github, vscode.emmet, vscode.merge-conflict, vscode.testing-editor-contributions, dbaeumer.vscode-eslint, eamodio.gitlens, esbenp.prettier-vscode, GitHub.vscode-pull-request-github, Gruntfuggly.todo-tree, vscode.extension-editing, vscode.typescript-language-features, vscode.configuration-editing, vscode.json-language-features
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
bootstrap-window.js:259 [uncaught exception]: Error: This socket has been ended by the other party
g @ bootstrap-window.js:259
bootstrap-window.js:262 Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455)
    at b.write (ipc.net.ts:65)
    at b._writeNow (ipc.net.ts:338)
    at Immediate.<anonymous> (ipc.net.ts:329)
    at processImmediate (internal/timers.js:456)
g @ bootstrap-window.js:262
events.js:292 Uncaught Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455)
    at b.write (ipc.net.ts:65)
    at b._writeNow (ipc.net.ts:338)
    at Immediate.<anonymous> (ipc.net.ts:329)
    at processImmediate (internal/timers.js:456)
bootstrap-window.js:259 [uncaught exception]: Error: This socket has been ended by the other party
g @ bootstrap-window.js:259
bootstrap-window.js:262 Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455)
    at b.write (ipc.net.ts:65)
    at b._writeNow (ipc.net.ts:338)
    at b.flush (ipc.net.ts:293)
    at b.dispose (ipc.net.ts:279)
    at Object.S [as dispose] (lifecycle.ts:96)
    at i.dispose (ipc.net.ts:687)
    at localProcessExtensionHost.ts:623
g @ bootstrap-window.js:262
events.js:292 Uncaught Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455)
    at b.write (ipc.net.ts:65)
    at b._writeNow (ipc.net.ts:338)
    at b.flush (ipc.net.ts:293)
    at b.dispose (ipc.net.ts:279)
    at Object.S [as dispose] (lifecycle.ts:96)
    at i.dispose (ipc.net.ts:687)
    at localProcessExtensionHost.ts:623
notificationsAlerts.ts:38 Error: No authentication provider 'github' is currently registered.
    at A.getSessions (authenticationService.ts:718)
    at async d.openReporter (issueService.ts:72)
    at async EventEmitter.<anonymous> (window.ts:150)
onDidChangeNotification @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:622
addNotification @ notifications.ts:206
error @ notificationService.ts:58
(anonymous) @ window.ts:158
async function (async)
(anonymous) @ window.ts:150
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:117
```

</details>

**Comment by gjsjohnmurray** [comment] 2021-03-03 08:02
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

**Comment by MuminCelal** [comment] 2021-03-03 08:36
This problem is happing on stable versions too, not only insiders and there is an error log on console.

![Screen Shot 2021-03-03 at 11 34 59](https://user-images.githubusercontent.com/15386828/109777296-9e2ef600-7c14-11eb-93a7-d439950c3f94.png)

**Comment by tamuratak** [comment] 2021-03-03 11:48
It might be duplicate of CoenraadS/Bracket-Pair-Colorizer-2/issues/383.

**Comment by tsabolov** [comment] 2021-03-03 13:08
> It might be duplicate of [CoenraadS/Bracket-Pair-Colorizer-2/issues/383](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/383).

Could be. I have the extension installed and I am on M1. Disabled the extension and watching.

**Comment by MuminCelal** [comment] 2021-03-03 13:34
> It might be duplicate of [CoenraadS/Bracket-Pair-Colorizer-2/issues/383](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/383).

I am using this extension too but I don't have an M1. If this problem is about M1, it shouldn't be a problem on Windows. I will watch it on Windows too.

**Comment by gjsjohnmurray** [comment] 2021-03-03 13:38
@MuminCelal I recommend Extension Bisect as a good way of finding out what is crashing your Extension Host process. Read more about it at https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by tsabolov** [comment] 2021-03-03 14:31
So, the Bracket Colorizer seems to be the bad guy here. This is was I caught just after the crash:

<details>
<summary>Console</summary>

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2084 [[object Object]]Cannot read property 'getRuleStack' of undefined
$onExtensionRuntimeError @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2084
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2084 TypeError: Cannot read property 'getRuleStack' of undefined
	at DocumentDecoration.onDidChangeTextDocument (/Users/[redacted]/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.2.0/out/src/documentDecoration.js:42)
	at DocumentDecorationManager.onDidChangeTextDocument (/Users/[redacted]/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.2.0/out/src/documentDecorationManager.js:47)
	at /Users/[redacted]/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.2.0/out/src/extension.js:30
	at p.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at T.$acceptModelChanged (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87)
	at u._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90)
	at u._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90)
	at u._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90)
	at u._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90
	at p.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106
	at p.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at t._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at p.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at l.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at Socket.E (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106)
	at Socket.emit (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/events.js:315)
	at addChunk (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:295)
	at readableAddChunk (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:271)
	at Socket.Readable.push (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:212)
	at Pipe.onStreamRead (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/internal/stream_base_commons.js:186)
$onExtensionRuntimeError @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2084
```

</details>

**Comment by aeschli** [comment] 2021-03-03 16:16
Thanks for bisecting! Can you file a new issue against the Bracket Colorizer given that your stack trace is different? Thanks a lot!

**Closed by aeschli** 2021-03-03 16:16 UTC
Labels: needs more info

**Comment by naquiroz** [comment] 2021-03-08 12:14
Hi! Sorry for bringing it up here but maybe you can point me exactly where to post this but I'm having the same issue on vscode 1.54.1 with ms-pyhton extension.

**Comment by gjsjohnmurray** [comment] 2021-03-08 13:00
@naquiroz start at the Report Issue option on the Help menu.
