### ISSUE TITLE
Syntax highlighting for inline css in html

### ISSUE THREAD

**Issue by steen3d** [Microsoft/vscode#56272] opened 2018-08-13 19:38 UTC
Version 1.25.1

Syntax highlighting for inline styles in html documents. Currently the entire style attribute gets assigned one color. Separate colors for properties and values would make this much more readable.

**Comment by aeschli** [comment] 2018-08-13 20:06
duplicate of https://github.com/textmate/html.tmbundle/issues/88

**Closed by aeschli** 2018-08-13 20:06 UTC
Labels: html

**Comment by steen3d** [comment] 2018-08-13 23:41
Sorry for the duplication, and thanks for your work on the issue.

-Chris
