### ISSUE TITLE
CPU usage spikes with JS files, especially when opening several quickly from Search results

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#65229] opened 2018-12-17 19:29 UTC
Issue Type: <b>Bug</b>

1. Launch VS Code with a NodeJS project open (it's a create-react-app project).
2. Wait for initial CPU usage to come down after launch.
3. Perform a Search that results in about 10 JS files.
4. Double-click each JS file to open it, then close it, then proceed to the next one.
5. CPU usage spikes (see screenshots). Most of this is due to Code Helper processes, and can be seen in VS Code's Process Explorer, under the "electron_node tsserver.js" process.
6. Wait for CPU usage to come down; this takes over five minutes.
7. Repeat the same Search, and open each file again. CPU usage spikes again for over five minutes.
8. **During the spike, the message "Initializing JS/TS language features" appears in the status bar.** Sometimes it disappears then reappears.

I submitted log file ID 1846382240 privately. It was recorded while doing the steps above. The attached process-explorer.png image shows the Process Explorer during one of the spikes. The attached activity-monitor.png shows the CPU usage during the spikes (you can see the two points where CPU usage came down).

(I know you'd prefer a report with extensions disabled. I'll try to get one, but it's been hard to get a good reproduction, so I thought I'd submit this first.)

This is using the built-in TypeScript 3.2.2.

![activity-monitor](https://user-images.githubusercontent.com/542988/50110391-01c4d880-01ef-11e9-966d-ab3fbb86f96c.png)
![process-explorer](https://user-images.githubusercontent.com/542988/50110392-01c4d880-01ef-11e9-8fb6-8ce16038f15c.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 5|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.0.0
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
dart-code|Dar|2.21.1
mustache|daw|1.1.1
vscode-eslint|dba|1.7.2
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
svn-scm|joh|1.46.4
vs-script-commands|mkl|7.0.0
vscode-apache|mrm|1.1.1
python|ms-|2018.12.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
java|red|0.35.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1
jinja|who|0.0.8

</details>

**Comment by mareksuscak** [comment] 2018-12-19 15:19
Also having problems with the extension host hitting CPU hard although I'm not sure if it's related. Started happening two updates ago. No specific extension according to the process explorer:

<img width="912" alt="screen shot 2018-12-19 at 16 16 46" src="https://user-images.githubusercontent.com/613647/50229047-aee35080-03a9-11e9-874f-693c2a3b1a30.png">

Restarting VS code isn't helping. It stops after certain time. Can't even type source code when it's happening.

**Comment by mjbvz** [comment] 2018-12-19 19:19
@mareksuscak open a new issue

**Comment by godmar** [comment] 2019-01-21 03:14
Same here tsserver.js spiking for several seconds to 100% CPU - also happening with a create-react-app project with may 2,000 lines added (no Typescript, btw.)

I'm using the EditorConfig and the prettier plugin, otherwise it's a fresh VSCode download (1.30.2, Electron 2.0.12, Linux x64).

A possibly related effect: actions like ^K ^F for small blocks of code take 10s, and [auto import](https://code.visualstudio.com/docs/languages/typescript#_auto-imports) as advertised there doesn't work at all.

**Comment by mjbvz** [comment] 2019-04-09 22:04
@jacobweber Can you please test this again on the latest vscode insider build. I could not track down what the root cause was but it's possible that it may since have been fixed

**Comment by jacobweber** [comment] 2019-04-30 01:15
Yes and no. There are so many things that seem to cause the CPU to spike on a large JS/React project. I can't narrow it down. But I have seen what seems like the same issue on 1.33.1.

**Comment by mjbvz** [comment] 2019-04-30 17:49
@jacobweber Can please you upload a new copy of the logs using the latest VS Code insiders build

**Comment by mjbvz** [comment] 2019-05-17 23:46
Without more information, I'm closing this as possible the same issue that we see in https://github.com/microsoft/TypeScript/issues/31452

Please test this again with the latest `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions). If still see this issue and have good repo steps or can share a small example project, let me know

**Closed by mjbvz** 2019-05-17 23:46 UTC
Labels: javascript, needs more info, perf
