### ISSUE TITLE
terminal.integrated.shellintegration.enabled isn't running .zprofile on m1 MacBookPro

### ISSUE THREAD

**Issue by csirkin** [microsoft/vscode#145254] opened 2022-03-16 18:41 UTC
Issue Type: <b>Bug</b>

With terminal.integrated.shellintegration.enabled after upgrading to 12.3, launching a terminal would give me output about pyenv not found. 'which pyenv' returnned that the program couldn't be found. While troubleshooting I found that if I launched iTerm2 I wouldn't get that problem. If I manually sourced my .zprofile in the integrated terminal then I was able to find pyenv in my path. Turning off the referrenced setting fixed the problem for me.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:42:05.236Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 10, 9|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 6fd8bf0d-f0be-4980-a67c-ccdbcf99229e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
TextFSM-Syntax|and|1.1.0
markdown-preview-github-styles|bie|1.0.1
vscode-markdownlint|Dav|0.46.0
python-environment-manager|don|1.0.3
xml|Dot|2.5.1
gitlens|eam|12.0.4
copilot|Git|1.8.5320
go|gol|0.32.0
gc-excelviewer|Gra|4.2.53
todo-tree|Gru|0.0.215
terraform|has|2.20.0
cisco|jam|1.9.1
junos|jam|1.3.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-docker|ms-|1.20.0
gather|ms-|2022.3.0
python|ms-|2022.2.1924087327
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
jinjahtml|sam|0.17.0
gistfs|vsl|0.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30440023
pythonvsnew555:30450902
vsbas813:30436447
vscscmwlcmt:30438805
dockersurvey3cf:30446834
pynewfile477:30450038

```

</details>

<img width="1136" alt="Screen Shot 2022-03-16 at 12 39 56 PM" src="https://user-images.githubusercontent.com/1499802/158663953-79e2a470-21db-4aa7-bb8d-2fe490528f9e.png">
<img width="1136" alt="Screen Shot 2022-03-16 at 12 39 27 PM" src="https://user-images.githubusercontent.com/1499802/158663958-df18c704-0026-4aa3-b53c-5bf0833da57b.png">

**Comment by Tyriar** [comment] 2022-03-17 18:49
This problem may be fixed in [Insiders](https://code.visualstudio.com/insiders), could you try it out?

I can't reproduce personally, `~/.zprofile` correctly runs when the profile args contains `-l` and doesn't when it doesn't. Used these terminal profiles to test with an echo statement in zprofile:

```json
"terminal.integrated.profiles.osx": {
    "zsh (login)": {
      "path": "zsh",
      "args": ["-l"]
    },
    "zsh (non-login)": {
      "path": "zsh",
      "args": []
    },
}
```

**Closed by Tyriar** 2022-03-17 18:49 UTC
Labels: bug, terminal-shell-integration

**Comment by csirkin** [comment] 2022-03-19 20:12
I guess my interpretation of the problem was incorrect. Everything seems to be different today. I can’t recreate those screenshots. If I put an echo in my .zprofile it appears to run whether that Shell Integration setting is enabled or not. Sorry.
