### ISSUE TITLE
Links to other md cells in jupyter notebook are broken

### ISSUE THREAD

**Issue by Hkllopp** [microsoft/vscode#144161] opened 2022-03-01 10:20 UTC
Issue Type: <b>Bug</b>

I used this technique (https://stackoverflow.com/questions/28080066/how-to-reference-a-ipython-notebook-cell-in-markdown) to refer another cell. And when I clicked on it, I got redirected to another random(?) cell but not the one with the correct Id.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.04GB free)|
|Process Argv|--crash-reporter-id 104fcef8-3567-493a-809c-aa9dc134106d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
salesforcecodesnippets|Aud|3.2.2
armview|ben|0.4.6
vscode-eslint|dba|2.2.2
vscode-salesforce-toolkit|dro|1.2.4
prettier-vscode|esb|9.3.0
lana|Fin|1.4.1
code-runner|for|0.11.7
copilot|Git|1.7.5118
sfdx-autoheader|Hug|0.7.2
vscode-wrap-console-log|mid|1.7.2
azure-pipelines|ms-|1.195.0
vscode-azureappservice|ms-|0.23.1
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.4.1272
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.20.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.0.1814523869
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.0
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.6
vetur|oct|0.35.0
vscode-xml|red|0.19.1
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.2.0
salesforcedx-vscode-apex|sal|54.2.0
salesforcedx-vscode-apex-debugger|sal|54.2.0
salesforcedx-vscode-apex-replay-debugger|sal|54.2.0
salesforcedx-vscode-core|sal|54.2.0
salesforcedx-vscode-expanded|sal|54.2.0
salesforcedx-vscode-lightning|sal|54.2.0
salesforcedx-vscode-lwc|sal|54.2.0
salesforcedx-vscode-soql|sal|54.2.0
salesforcedx-vscode-visualforce|sal|54.2.0
vscode-icons|vsc|11.10.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by mjbvz** [comment] 2022-03-11 21:19
Duplicate of #141577 I believe

Give this a try in the next VS Code insiders build and let me know if you still see the issue

**Closed by mjbvz** 2022-03-11 21:19 UTC

**Comment by Hkllopp** [comment] 2022-03-15 10:34
It seems it wasn't fixed in the last version.
Here is a GIF of the issue.
Thanks for your help

![NotebookLinks](https://user-images.githubusercontent.com/9498111/158359193-6bb9f050-2507-46bf-8f75-26474e953a7b.gif)
