### ISSUE TITLE
No Autocomplete Inside webpack.config.js

### ISSUE THREAD

**Issue by adityapurwa** [Microsoft/vscode#42886] opened 2018-02-03 15:06 UTC
- VSCode Version: 1.19.3
- OS Version: Windows 10 Pro - 10.0.16299

Steps to Reproduce:

1. Open Visual Studio Code
2. Add **webpack** dependency (`$ npm install --save-dev webpack`).
3. Create webpack.config.js, see below.

```js
module.exports = {
  // Ctrl+Space here, no autocomplete for possible webpack configuration entries.
}
```

Does this issue occur when all extensions are disabled?: Yes

I am sure that I used to be able to have auto complete inside webpack config files

**Comment by mjbvz** [comment] 2018-02-06 02:32
Duplicate of #32108

**Closed by mjbvz** 2018-02-06 02:32 UTC
Labels: javascript
