### ISSUE TITLE
High CPU in mac - not an extension

### ISSUE THREAD

**Issue by jlubeck** [Microsoft/vscode#63998] opened 2018-11-29 16:31 UTC
Issue Type: <b>Performance Issue</b>

I can't seem to find a proper reproducible flow. But somehow it always happens after I move away from the window and focus back on it. It happens when I do that, but not every time I do. Hope that makes sense.

I tried disabling extensions already. And the Process Explorer is showing CPU 145 and Memory MB 524 on a window process (and going up). 

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   147	 42159	code main
    5	    82	 42161	   gpu-process
    0	   164	 42162	   window (started.rb — temp)
    0	    33	 42209	     extensionHost
    0	    16	 42216	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=42209
    0	    16	 42217	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=42209
    0	    49	 74301	       electron_node tsserver.js 
    0	    16	 74303	         electron_node typingsInstaller.js typesMap.js 
    0	    16	 42211	     watcherService
    0	    66	 42210	   shared-process
  145	   524	 84992	   window (index.js — temp.1.0)
    0	    33	 84995	     watcherService
    0	   115	 84996	     extensionHost
    0	   115	 85000	       electron_node tsserver.js 
    0	    16	 85012	         electron_node typingsInstaller.js typesMap.js 
    0	    16	 85121	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=84996
    2	    82	 91352	   window (Process Explorer)
    0	    98	 91587	   window (Issue Reporter)
    0	     0	 91593	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — temp.1.0)
|  Window (started.rb — temp)
|    Folder (temp): 0 files
|      File types:
|      Conf files:
|    Folder (temp.1.0): 20 files
|      File types: mx(4) cv(4) realm(2) lock(2) note(2) js(2) sh(1)
|                  gitignore(1) DS_Store(1) json(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none

**Comment by rebornix** [comment] 2018-11-29 17:05
@jlubeck can you please update to 1.29.1 first and see if you can still reproduce this issue? We have some performance related fixes lately.

**Comment by jlubeck** [comment] 2018-11-29 17:08
Just updated... will report back!

**Comment by jrieken** [comment] 2019-04-30 13:11
closing because no actionable information is present

**Closed by jrieken** 2019-04-30 13:11 UTC
Labels: needs more info
