### ISSUE TITLE
Background color for code

### ISSUE THREAD

**Issue by metalfox6383** [Microsoft/vscode#61332] opened 2018-10-19 15:34 UTC
Issue Type: <b>Feature Request</b>

Hi:

I'd like that "tokenColorCustomizations" would have background color, like:

"editor.tokenColorCustomizations": {
		"comments": {
			"fontStyle": "bold",
			"foreground": "#d0de32",
                       "background": "#ffffff"
		}
	}

Thanks!

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment] 2018-10-19 15:46
Duplicate of #3429

**Closed** 2018-10-22 22:48 UTC
Labels: *duplicate, themes
