### ISSUE TITLE
Terminal PS Cmd Prints Output on Same Line as the Cmd Itself

### ISSUE THREAD

**Issue by sgtoj** [Microsoft/vscode#13251] opened 2016-10-05 14:21 UTC
OS: Microsoft Windows [Version 10.0.14936]
Version 1.6.0-insider
Commit 602155bb781f509c7a4ddcd700b57cb9b9f5286d
Date 2016-10-01T00:36:55.469Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

![No new line breaks in terminal](http://i.imgur.com/nDizBka.png)

Steps to Reproduce:
1.  Change setting `terminal.integrated.shell.windows` to use PowerShell (default location)
2.  Reload VS Code
3.  Execute `echo test` several times in a row. 
   - Eventually, you will see a few of the output of the commands on the same line of the command. 

Note:
- Confirmed this issue doesn't affect the standard PS console.

**Comment by sgtoj** [comment] 2016-10-05 20:20
Same issue occurs if terminal is set to the defaults (eg cmd.exe) and `powershell` is executed to switch to the PS console.

**Comment by Tyriar** [comment] 2016-10-05 20:47
@daviwil have you seen this?

**Comment by daviwil** [comment] 2016-10-05 21:05
Looks like the PSReadline module might be responsible for this somehow.  Brian, can you run `Remove-Module PSReadline` and then try to reproduce the issue?

**Comment by Tyriar** [comment] 2016-10-05 21:13
If it's the "default location" for powershell it's probably the 32-bit version.

**Comment by sgtoj** [comment] 2016-10-06 10:43
- Seem to be resolved after removing PSReadLine module. Could not reproduce it.
- Same results with 32-bit and 64-bit (i.e. SysNative) PowerShell

**Comment by sgtoj** [comment] 2016-10-06 10:46
This means this issue is being moved to [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell)?

**Comment by Tyriar** [comment] 2017-04-21 04:08
I beleive this would have been fixed by the winpty upgrade.

**Closed by Tyriar** 2017-04-21 04:08 UTC
Labels: bug, integrated-terminal, windows
