### ISSUE TITLE
Preferred controller not getting set

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#122028] opened 2021-04-23 15:10 UTC
- VS Code Version: Insiders
- OS Version:Mac

Steps to Reproduce:

1. Install VS Code Insiders
2. Install latest Jupyter Extension
2. Open a notebook, change the kernel to Y, save the notebook.
3. Reload VS Code and notice that the kernel is set to A

This is because VS Code is setting the kernel to the first controller we give.

I think VS Code should change the kernel to the preferred (unless the user has changed it).
In this (above) case, the kernel was not set by me to `A`.

Note: We're calling the `targetController.updateNotebookAffinity(document, NotebookControllerAffinity.Preferred);` however this doesn't seem to have any effect.

@IanMatthewHuff @jrieken /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by DonJayamanne** [comment] 2021-04-23 15:24
This seems to work after setting the controller a few times.

**Comment by IanMatthewHuff** [comment] 2021-04-23 15:57
@DonJayamanne I'm tracking a similar issue, so I might fill in more info here. But what I'm currently seeing is that the first time a document is opened I'm not seeing a onDidChangeNotebookAssociation event being fired. It seems to have a NotebookController (one of ours) selected, but we never get a notification for the initial selection. Once the document has selected a kernel manually vscode seems to persist that setting and it works.

I think this is currently the issue with most of our tests (which I'm looking at). They open a new blank notebook and then wait for the kernel to get selected, and that notification is never happening.

**Comment by jrieken** [comment] 2021-04-23 16:27
> But what I'm currently seeing is that the first time a document is opened I'm not seeing a onDidChangeNotebookAssociation event being fired. 

That is to be expected. The event only ever fires after a notebook controller has been selected - either explicitly via the picker or implicitly when running a cell with a preselected/suggested controller. From then on we do remember the controller and send the event when the controller has been added again (after restart) or when a bound notebook is re-opened. We cannot send the event the very first time automatically because that would mean that the first controller is always the selected controller.

**Comment by jrieken** [comment] 2021-04-23 16:33
> Reload VS Code and notice that the kernel is set to A

Is at that time kernel Y available? I have a simple text-based notebook with multiple controllers and I don't reproduce that behaviour. 

fyi - I have also pushed a few small UI tweaks today. The tooltip in the status bar nows shows if kernel/controller is auto-picked/suggested

<img width="315" alt="Screenshot 2021-04-23 at 18 31 46" src="https://user-images.githubusercontent.com/1794099/115902121-5d0fd100-a462-11eb-9dea-f7b24c7de7fc.png">

**Comment by jrieken** [comment] 2021-04-23 16:43
> Reload VS Code and notice that the kernel is set to A

The only that is likely happening is:

* no explicit or implicit kernel selection happening
* window reloads
* kernel Y with normal affinity comes
* kernel A with high affinity comes
* :bug: status bar still shows kernel Y. that's because of a missing event

**Comment by jrieken** [comment] 2021-04-23 17:06
I have pushed a change that fixes what I have described in my previous comment. Optimistically closing this issue

**Closed by jrieken** 2021-04-23 17:06 UTC
