### ISSUE TITLE
Per-host / per-os settings

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#50754] opened 2018-05-30 00:37 UTC
Currently, settings can be customized per-language

```json
{
  "[cpp]": {
    "editor.codeLens": true
  }
}
```

It'd be great to extend this to also support hostname and os name, ie,

```json
{
  "[host:home]": {
    "cquery.launch.command": "cquery.exe"
  },

  "[os:linux]": {
    "editor.smoothScrolling": true
  }
}
```

Making this work with arbitrary context-keys would be great as well, but host/os should get most of the cases.

**Comment by sardorocket** [comment] 2018-05-30 05:52
what is the use case for this option?

**Comment by jacobdufault** [comment] 2018-05-30 06:06
Maintaining a single settings file for use across multiple computers

**Comment by sandy081** [comment] 2018-09-12 16:16
Duplicate of #17619

**Closed** 2018-09-12 16:16 UTC
Labels: *duplicate, config
