### ISSUE TITLE
CPU hogging is back

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#14222] opened 2016-10-23 11:13 UTC
- VSCode Version: Code - Insiders 1.7.0-insider (788caba5a3ca1c2b137353f4384bb0e026db1a31, 2016-10-21T23:35:35.321Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

| Extension | Author | Version |
| --- | --- | --- |
| ejs-language-support | QassimFarid | 0.0.1 |
| project-manager | alefragnani | 0.11.0 |
| htmltagwrap | bradgashler | 0.0.3 |
| githistory | donjayamanne | 0.1.0 |
| code-beautifier | michelemelluso | 1.4.1 |
| json2yaml | tuxtina | 0.2.0 |
| gitblame | waderyan | 1.3.0 |
| bootstrap-3-snippets | wcwhitehead | 0.0.7 |
| join-lines | wmaurer | 0.1.5 |

---

Steps to Reproduce:
1. Open 2 Nodejs expressjs projects
2. CPU starts climbing

I have 2 projects open, cannot figure out which one it is. The process info on mac does not tell me which file is open.
I tried Javasript cpu profiles with the developer tools, but the profile files ends up being zero.
How do I find where the problem is.

**Comment by bpasero** [comment] 2016-10-23 12:40
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by gerhardcit** [comment] 2016-10-24 08:17
@bpasero , nope sorry, without extensions the same thing happens.
Will the sample output from the Mac Activity Monitor help?

[Sample of Code - Insiders Helper.txt](https://github.com/Microsoft/vscode/files/547223/Sample.of.Code.-.Insiders.Helper.txt)

**Comment by gerhardcit** [comment] 2016-10-24 08:28
Also, this is the item I found from the process that runs up the CPU.

ps aux | grep 5031
gerhard           5031  78.7  1.4  3757812 238352   ??  R     8:25AM  17:16.66 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=renderer --no-sandbox --primordial-pipe-token=0B467B8515AFC17EFA20FA8C84D7F49E --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=90A63407877E03BE7F909DE0F69E7369 --mojo-application-channel-token=85F6FFA22362C90297D5F2D7EE29E835 --channel=4988.3.202003763

**Comment by bpasero** [comment] 2016-10-24 12:16
@gerhardcit Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line)
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by bpasero** [comment] 2016-10-31 13:54
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by gerhardcit** [comment] 2016-10-31 14:29
Yes @bpasero , I get it. Sorry, I have 5 projects open at any time, so each time this happens it just takes too much time and effort to then start debugging dev environments etc. So far its been fruitless, so now I am hoping the problem will go away at some point.
I do find it a little weird though that somehow finding a CPU processing running high cannot be pin pointed easier.
I have narrowed it down to one specific project it seems.. but even after doing this:
```files.watcherExclude": {
        "**/**": true
```}
it still went to the same CPU usage at 90%. 
I'll stick with release Code version for now.

**Comment by bpasero** [comment] 2016-10-31 14:34
@gerhardcit the reason we have to ask all these stupid questions is because most users are not able/willing to share their workspaces to us.

**Comment by bpasero** [comment] 2016-11-01 06:01
@gerhardcit so you say it does only reproduce in Insider and not in Stable?

**Comment by gerhardcit** [comment] 2016-11-02 05:34
I am trying the --verbose and will see if I can find something. But I rather you close this and when I have more info, I'll post it with that next time.
Thx for the efforts though, vscode is a fantastic editor.

**Comment by bpasero** [comment] 2016-11-02 05:38
I can leave it open and you can take your time to post more info if you find it.

**Comment by Velok** [comment] 2016-11-05 15:39
I also have issues with high CPU Load. 

VSCode Version: 1.7.1
OS Version: macOS 10.12.1 (16B2555)
Kernel Version: Darwin 16.1.0
Extensions: All disabled

Reproduce:

- open 2 VS Code Windows with simple textfiles
- change one of the Windows to Fullscreen Mode
- warm your Fingers on the MacBookPro

I've discovered that it only happens when at least one of the Windows are in Fullscreen Mode. It doesn't matter if you only have a simple file open or a whole project. It also doesn't matter if you have Extensions installed/activated.

![image](https://cloud.githubusercontent.com/assets/6967752/20031351/4f8f11ae-a376-11e6-8103-a7725d798c99.png)

**Comment by bpasero** [comment] 2016-11-05 16:29
@Velok To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by Velok** [comment] 2016-11-05 18:59
So I analyzed my issue further. I think there is another Tool involved. I use Contexts to switch between Windows with cmd + tab. The CPU Load only gets up when I switch from the Fullscreen Window with the shortcut. When swipe between the Desktops with my Touchpad it's all fine. Also when I deactivate the Contexts Tool and use the standard Switcher all is fine. However, in the Standard Switch Menu there is only one VS Code Symbol showing up and you cannot switch directly to a specific VS Code Window. But thats another story.

Heres the ps terminal output with 2 windows non fullscreen:

Pascal            6827   0.0  1.0  4216068 167432   ??  S     7:10PM   0:07.95 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=E5FB05DF730C64D4A55E895D1FF3DDF4 --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=1E048F29785F989C4A10FD62D7186672 --mojo-application-channel-token=C458BBE2ADD144F7EBD4B4ED8B2A4233 --channel=6444.2.1044949570
Pascal            6445   0.0  0.3  2820228  57456   ??  S     7:10PM   0:01.18 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=6444.0.674207481 --mojo-application-channel-token=D3CE106FAFB3C2FDAD87331FFF72A446 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=16,21,25,36,47,50,51,55,57,65,66,72,75 --gpu-vendor-id=0x10de --gpu-device-id=0x0fe9 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0d26 --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x0d26
Pascal            6444   0.0  0.7  3522520 110652   ??  S     7:10PM   3:19.37 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Pascal             333   0.0  0.1  2516444  14032   ??  S     3:54PM   0:00.03 /System/Library/Frameworks/CryptoTokenKit.framework/ctkd -tw
Pascal            8084   0.0  0.0  2432804   1972 s000  S+    7:16PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 6444
Pascal            8034   0.0  1.0  4232448 174164   ??  S     7:15PM   0:03.37 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=580FE4EFBAC74E1B18D6AB2B9E72DD27 --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=E2ED44EB04E5FE5C0E560F3AB5FBEB81 --mojo-application-channel-token=54367B3B279B1EF7FF43F5E394DB7123 --channel=6444.3.1680420554

and here with 1 Window in Fullscreen:

Pascal            6444  92.6  0.7  3567156 110980   ??  R     7:10PM   3:50.36 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Pascal            6827  85.1  1.0  3684820 168092   ??  R     7:10PM   0:34.62 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=E5FB05DF730C64D4A55E895D1FF3DDF4 --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=1E048F29785F989C4A10FD62D7186672 --mojo-application-channel-token=C458BBE2ADD144F7EBD4B4ED8B2A4233 --channel=6444.2.1044949570
Pascal            6445   0.0  0.3  2832644  57656   ??  S     7:10PM   0:01.39 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=6444.0.674207481 --mojo-application-channel-token=D3CE106FAFB3C2FDAD87331FFF72A446 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=16,21,25,36,47,50,51,55,57,65,66,72,75 --gpu-vendor-id=0x10de --gpu-device-id=0x0fe9 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0d26 --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x0d26
Pascal             333   0.0  0.1  2516444  14032   ??  S     3:54PM   0:00.03 /System/Library/Frameworks/CryptoTokenKit.framework/ctkd -tw
Pascal            8217   0.0  0.0  2444068   1948 s000  R+    7:18PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 6444
Pascal            8034   0.0  1.1  4244868 185104   ??  S     7:15PM   0:04.77 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=580FE4EFBAC74E1B18D6AB2B9E72DD27 --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=4 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=E2ED44EB04E5FE5C0E560F3AB5FBEB81 --mojo-application-channel-token=54367B3B279B1EF7FF43F5E394DB7123 --channel=6444.3.1680420554

**Comment by gerhardcit** [comment] 2016-11-06 09:35
@Velok , @bpasero , I also use Contexts to switch windows, and that has a window for every project open in In Code. Maybe there is a que in there somehow.
But I don't use full screens.

**Comment by JostCrow** [comment] 2016-11-15 09:52
I had the same. All my programs were lagging because of vscode. I am running Ubuntu 16.10

![screenshot from 2016-11-15 10-42-32](https://cloud.githubusercontent.com/assets/390575/20300851/48e6e388-ab21-11e6-991c-9feaf76aab11.png)

As you can see here every process was very high. I had to quit vscode. When I did there was a drop in cpu usage.

The only thing that I had was 2 projects open. I didn't even do anything with them. I didn't have this problem in previous versions.

**Comment by bpasero** [comment] 2016-11-16 18:07
@JostCrow 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by JostCrow** [comment] 2016-11-20 13:52
Oke, I have done what you said. this is wat happens when I start vscode normally.
![screenshot from 2016-11-20 14-50-13](https://cloud.githubusercontent.com/assets/390575/20463339/aee6ffca-af30-11e6-8c24-6916857114df.png)


This is what happens when I am starting it with `code --disable-extensions`
![screenshot from 2016-11-20 14-47-29](https://cloud.githubusercontent.com/assets/390575/20463328/8947137c-af30-11e6-8400-09a01299108e.png)

In both cases I did not do anything except staring visual studio code.

So I will report it at the extension repository

**Comment by bpasero** [comment] 2017-05-14 07:59
Closing this issue, please try things again with VS Code 1.12 and report CPU issues as individual issues. It is very hard for us to deal with issues where people jump in and say they have the same issue. In almost all cases the performance issue comes from very specific reasons (extensions, file watching, etc.).

**Closed by bpasero** 2017-05-14 07:59 UTC
Labels: freeze-slow-crash, needs more info, workbench
