### ISSUE TITLE
ESC leaves fullscreen

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83566] opened 2019-10-29 18:23 UTC
Testing #83296

Pressing ESC in fullscreen in firefox on windows leaves fullscreen. I remember this being a discussion point when working on keybindings in the web, but I don't remember if this was intended to be resolved so opening an issue.

**Comment by rebornix** [comment] 2019-11-06 22:32
Actually duplicate of https://github.com/microsoft/vscode/issues/83343.

**Closed** 2019-11-06 22:32 UTC
Labels: *duplicate, firefox, keybindings, upstream, web
