### ISSUE TITLE
Using mouse to interact with install specific version of extension closes menu rather than selecting item

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#64350] opened 2018-12-04 14:55 UTC
Issue Type: <b>Bug</b>

Use command palette to select install specific version of extension.
In the list of extensions to select from, click on one with the mouse.
The command palette/quick open disappears instead of showing the list of versions of the selected extension.

When using the keyboard everything works as expected. I can use the keyboard to arrow up and down through the list and use the return key to make a selection.

Testing https://github.com/Microsoft/vscode/issues/64203

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:34:30.209Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.27
python|ms-|2018.8.0
test-search-rg|rob|0.0.3

</details>

**Comment by sandy081** [comment] 2018-12-04 15:19
Good catch @stevencl 

Related to quick pick hence forwarding to @chrmarti

**Comment by chrmarti** [comment] 2018-12-06 10:48
Not a regression. The Run Task case reproduces in 1.29.1. /cc @dbaeumer

**Comment by dbaeumer** [comment] 2018-12-06 11:46
@chrmarti then we broke it somewhen before since this used to work :-). So IMO still a regression. If you think this needs to be fixed on our end please ping.

**Comment by chrmarti** [comment] 2018-12-06 15:21
@joaomoreno and I are looking into it in detail. It only reproduces when clicking with the mouse to pick the entry. And it also reproduces in 1.27.2.

**Closed** 2018-12-06 20:32 UTC
Labels: bug, extensions, quick-pick
