### ISSUE TITLE
extension host error

### ISSUE THREAD

**Issue by prabhat0206** [microsoft/vscode#177003] opened 2023-03-13 20:22 UTC
Type: <b>Bug</b>

extension host error

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 1397)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|15.05GB (3.73GB free)|
|Process Argv|. --crash-reporter-id 2a2b8044-3f76-4740-b2d1-1531199fc952|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
swagger-viewer|Arj|3.1.2
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.9.8
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
javascript-ejs-support|Dig|1.3.3
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
c-cpp-runner|fra|5.1.2
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
go|gol|0.37.1
gc-excelviewer|Gra|4.2.56
terraform|has|2.25.4
vscode-react-typescript|inf|1.3.1
solidity|Jua|0.0.141
package-plus-plus|jun|0.0.1
vsc-python-indent|Kev|1.18.0
vscode-lifeline|kjh|1.2.0
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-wsl|ms-|0.76.1
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5834
vscode-react-native|msj|1.10.0
csv-to-table|php|1.4.0
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.5.1
vscode-rapidapi-client|Rap|1.9.3
vscode-xml|red|0.24.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1435
ejs-snippets|Tao|0.1.0
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0
vscode-gradle|vsc|3.12.6
quokka-vscode|Wal|1.0.527
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(6 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-13 20:44
Please use the Start Extension Bisect command to investigate which extension may be causing this.

**Comment by isidorn** [comment] 2023-03-15 11:13
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:13 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host
