### ISSUE TITLE
Unknown configuration setting warning.

### ISSUE THREAD

**Issue by rhernandog** [microsoft/vscode#64441] opened 2018-12-05 17:10 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 7 64b

Steps to Reproduce:

1. Working on a regular React project, nothing too fancy. I updated the files associations in order to get the matching icon for the `.js` files.
2. After opening the `settings.json` file (from the preferences menu, not directly) I get a couple of warnings stating: **Unknown configuration setting**. Removing the changes in the settings file, doesn't clear the warning.

Does this issue occur when all extensions are disabled?: Yes

Here are a couple of captures:

![issue-1](https://user-images.githubusercontent.com/4622323/49530601-51bea980-f897-11e8-94cc-3d7cfd5a24c4.jpg)

![issue-2](https://user-images.githubusercontent.com/4622323/49530609-55eac700-f897-11e8-9382-238991c6e763.jpg)

**Comment by usernamehw** [comment] 2018-12-05 17:18
Location was renamed: `"workbench.panel.defaultLocation": "bottom",`
Suggest was renamed: `"typescript.suggest.insertParametersForFunctionCalls": true,`

**Comment by rhernandog** [comment] 2018-12-05 19:20
Ok, but the settings in the screenshots are the default settings. I never changed either of those.

Curious if VSCode auto-update does updates those properties?

**Comment by sandy081** [comment] 2018-12-06 11:19
@rhernandog I cannot reproduce this.. Can you please provide me a minimal steps to repro this issue?

**Comment by rhernandog** [comment] 2018-12-06 19:12
Well, beyond what I already described, there is no other way this happens.

I open VSCode, then I open the settings, then I click on files -> files associations. After the json file opens, the warnings appear.

I made a capture of it:

https://youtu.be/J9ZAd6M4HpQ

As I said before, I never touched the two settings being marked by VSCode as warnings. All I've done in the past months was to change from the system installer to the user installer. The extensions are the same. Again, I think that it could be something about the auto update. I don't recall if I installed version 1.27 or 1.28 when I made the switch to the user installer.

I wish I could provide more details, but unfortunately that is all I'm doing to get this warnings and is actually not breaking the software, everything works as expected.

Thanks for the answers and dedication to this.

Best,
Rodrigo.

**Comment by SovietFrontier** [comment] 2019-05-19 04:18
I cannot figure out what in the world happened to `"typescript.suggest.insertParametersForFunctionCalls"`. Did the auto complete function parenthesis move to another name again?"

**Comment by sandy081** [comment] 2019-05-21 20:33
@rhernandog It seems you had some settings which got renamed.

@isidorn @mjbvz Was not there migration when these [settings](https://github.com/microsoft/vscode/issues/64441#issuecomment-444567895) got renamed

**Comment by mjbvz** [comment] 2019-05-22 22:47
Yes, the setting was marked as deprecated for at least one release cycle with a message that pointed users to the new setting. After that, I deleted the deprecated setting a few iterations back because I did not want it showing up any more in the settings ui or settings json. Not sure if there's a better way to handle this

**Comment by isidorn** [comment] 2019-05-23 09:21
Same as @mjbvz I believe
The setting was depricated for a milestone and than removed.

**Comment by sandy081** [comment] 2019-05-28 07:38
@rhernandog Please remove that setting from your settings file as it is deprecated and removed.

**Closed by sandy081** 2019-05-28 07:38 UTC
Labels: needs more info

**Comment by SovietFrontier** [comment] 2019-05-28 12:38
@sandy081 so what is the replacement?

**Comment by sandy081** [comment] 2019-05-29 10:43
@mjbvz @isidorn I suppose above comment is meant for you.

**Comment by isidorn** [comment] 2019-05-29 10:47
@SovietFrontier replacement for `"workbench.panel.location": "bottom"` is ``workbench.panel.defaultLocation": "bottom"`

**Comment by SovietFrontier** [comment] 2019-05-29 12:39
What about `"typescript.suggest.insertParametersForFunctionCalls": true`?
