### ISSUE TITLE
Move debug toolbar to bottom

### ISSUE THREAD

**Issue by bittnkr** [Microsoft/vscode#57210] opened 2018-08-25 20:54 UTC
The debug toolbar is anchored at top of editor area.
![vsdebug1](https://user-images.githubusercontent.com/1910136/44622461-14598180-a88f-11e8-904f-aa3d9d4c9f3d.png)

This area us precious, it is at the first lines of file and it already ocupied by the search/replace toolbar and the tabs.

Please move it (or allow it to move) to the bottom of editor area, where it could stay harmoniously without annoying.
![vsdebug2](https://user-images.githubusercontent.com/1910136/44622488-b8dbc380-a88f-11e8-92ab-ec63cd83f7b0.png)
Thanks for all.

**Comment by isidorn** [comment] 2018-08-27 10:50
Custom positioning is a duplicate of an already open issue. Currently you can drag it a bit up (to the tabs are) and you can also dock it to the debug viewlet, set the debug toolbar setting to "docked".
Custom positioning we do not really want to do -> out of scope and there might already be a duplicate for this

**Closed by isidorn** 2018-08-27 10:50 UTC

**Comment by isidorn** [comment] 2018-09-17 14:50
@bittnkr "debug.toolBarLocation": "docked"

**Comment by bittnkr** [comment] 2018-09-21 17:37
It worked. Thank you!
