### ISSUE TITLE
Workspace storage directory name changes

### ISSUE THREAD

**Issue by sogerc1** [microsoft/vscode#107429] opened 2020-09-25 10:20 UTC
Some workspace directory settings are stored in a directory named:
~/.config/Code/User/workspaceStorage/<some_hash>
My problem is that sometimes vscode starts assigning a different hash to the same workspace directory, resulting in a loss of the previously opened files and a some other settings. I can find the old directory by looking into the workspace.json files and if I copy over the files into the new directory, my original settings reappear.
I can't tell you when and why vscode starts assigning a different directory, it's not every time, it's only once or twice a day if I keep changing workspace directories, my only guess was that the directory is on an autofs sshfs but if I manually restart autofs now (resulting in a remount) the hash does not change.

**Comment by sogerc1** [comment] 2020-09-25 10:31
I've also restarted my computer to test it but the hash did not change for my last opened workspace dir.

**Comment by bpasero** [comment] 2020-09-25 11:42
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sogerc1** [comment] 2020-09-25 11:54
I've installed code-insiders_1.50.0-1601012480_amd64.deb, I'll use it for a short while and report back.

**Comment by bpasero** [comment] 2020-09-25 11:59
Thanks. Also some exact steps how to reproduce would help.

**Comment by sogerc1** [comment] 2020-09-25 12:17
Really not much to tell, I open a workspace directory by selecting it from "File/Open Recent" or from the command "File: Open Recent..." and sometimes, I can't tell you a pattern when, my settings are not restored. It also happens sometimes when I start VSCode at the beginning of the workday. When this happens a new directory appears in ~/.config/Code/User/workspaceStorage but the old one is also present. These directories were originally opened using "File/Open Folder ..."

**Comment by bpasero** [comment] 2020-09-25 12:53
Basically our approach is to compute a MD5 hash sum of the absolute path of the folder (or workspace file) to use as storage file name.

**Comment by sogerc1** [comment] 2020-09-25 13:05
That is strange. For example right now I have two directories named 67e990ca66f6911da566e2a53e450127 and d9bd5780058b9f9f54492e9e9fed1ad4 containing the exact same workspace.json:
{
  "folder": "file:///mnt/ssh/dev/dev.zimplu.com/site"
}

**Comment by bpasero** [comment] 2020-09-25 13:26
@sogerc1 where exactly is that, what is the parent path?

**Comment by sogerc1** [comment] 2020-09-25 13:37
It's the exact path seen in the json file:
/mnt/ssh/dev/dev.zimplu.com/site
but as I said above it's not a real directory, /mnt/ssh is managed by autofs, the pathname never changes though.

**Comment by bpasero** [comment] 2020-09-25 13:39
@sogerc1 no I meant, the parent path of the `workspace.json` file. It is somewhere in a user data directory of VSCode and I would like to know the full path.

**Comment by sogerc1** [comment] 2020-09-25 13:42
This is a local file:
/home/soger/.config/Code/User/workspaceStorage/d9bd5780058b9f9f54492e9e9fed1ad4/workspace.json

**Comment by bpasero** [comment] 2020-09-25 15:53
@sogerc1 right, so `d9bd5780058b9f9f54492e9e9fed1ad4` is the hash of the currently opened folder OR `.code-workspace` file. If you change the path, you will get a new location. Maybe you move a `.code-workspace` file around?

**Comment by sogerc1** [comment] 2020-09-25 16:17
No, I don't even use .code-workspace files. And, as I said before, I also have a file:
/home/soger/.config/Code/User/workspaceStorage/67e990ca66f6911da566e2a53e450127/workspace.json
with the same content, they both point to the same folder (/mnt/ssh/dev/dev.zimplu.com/site). This one (the one starting with 67) has the older mtime, that one was the one abandoned by vscode. What would be correct hash? Because:
md5(/mnt/ssh/dev/dev.zimplu.com/site)=16f711d329574438bdf1f4aeac0f9770
md5(/mnt/ssh/dev/dev.zimplu.com/site/)=b2d2b853283d258614476e6b54aa24e6
md5(file:///mnt/ssh/dev/dev.zimplu.com/site)=25c52d83249a84d9ab8ed83bfec2e280
md5(file:///mnt/ssh/dev/dev.zimplu.com/site/)=41046ace136d8fc564a2a26197af8b80
Neither of these variants match either of my directories, something else is also included in the calculation.

**Comment by bpasero** [comment] 2020-09-25 16:34
@sogerc1 hm, maybe you are onto something, here is the algorithm and I just realized that the creation time of the folder plays into the hash. The reason is that if you delete the folder and then create it with same name, we do not want to restore the same state because the folder is different. Could it be that the `ctime` of this folder changes somehow?

Code:

https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/platform/resource/node/resourceIdentityServiceImpl.ts#L30-L53

**Comment by sogerc1** [comment] 2020-09-25 23:23
Okay, I think I got it and it's all bad. So I'm on debian linux so vscode wants to use fileStat.ino - correctly, because I've checked and the ctime of that directory is the same as it's mtime which is incorrect, it shows a value 15 days ago when in fact the directory was created years ago. The other problem is that according to this page: https://cs.uwaterloo.ca/twiki/view/CF/SshFs SSHFS uses fake inodes and indeed inode number 16797911 gets translated on my computer to 7 - which is probably some sort of on-disk scanning order and it probably changes when the containing directory gets changed, at least that's my guess. This is a real problem for me because some vscode features were disabled when I tried the vscode sshfs extension and I could only get curlFtpFS to work in read-only mode.

I get why this extra birthtime was added to the hash calculation but do you think adding an option to disable it would be reasonable? It doesn't have to have an UI select box, I could add something like
disableBirthtime: true,
to my settings.json and if it's set, you could force the ctime variable to undefined.

**Comment by bpasero** [comment] 2020-09-27 06:37
@sogerc1 good findings. I am not a big fan of changing this in VSCode, given that it seems to be an actual problem in the OS that should be fixed properly.

As an alternative: you could create a multi-root workspace file that is stored on your main disk (with proper `birthtime`) and point to the folder to open. More docs via https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Closed by bpasero** 2020-09-27 06:37 UTC
Labels: needs more info
