### ISSUE TITLE
vscode不能添加扩展了 1.26.1

### ISSUE THREAD

**Issue by angiens** [Microsoft/vscode#57927] opened 2018-09-05 03:25 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by beanlee** [comment] 2018-09-05 06:05
same with #57851

**Comment by mjbvz** [comment] 2018-09-05 06:39
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 06:39 UTC
Labels: extensions
