### ISSUE TITLE
[js] 'property declarations' can only be used in a .ts file.

### ISSUE THREAD

**Issue by jefflindholm** [Microsoft/vscode#9228] opened 2016-07-13 19:26 UTC
- VSCode Version:
1.3.1
- OS Version:
Windows 10

Steps to Reproduce:

1.  create a js file
2. create a class and add
static MY_VAR = 'foo';

Please do not close this and say it is a TS issue like you did with the one that uses => (fat arrow methods) since that does not work either. Please notice this is a JAVASCRIPT (js) file not a TYPESCRIPT (ts) file. 

I get that it works in ts files, maybe there is some way to make it work in js files, if so, maybe tell me how? 

This is pretty consistent when I use anything from the bable stage 0 stuff. 

This is by far one of the best editors out there, but this makes it pretty unusable when I am doing React code since I need to do 'static propTypes = {' etc. and use fat arrows so I don't have to do bind(this) all over the place.

Thanks

**Comment by DavyDeDurpel** [comment] 2016-07-15 06:04
+1

'static' members are allowed inside an ecma 6 class so the compiler should not complain about it.

**Comment by bloody-ux** [comment] 2016-07-15 06:20
+1

**Comment by jefflindholm** [comment] 2016-07-18 14:22
I got an answer on how to get this working.....

Install the typescript 2.0 beta and update the version in the typescript.tsdk file and you should be golden to have all this stuff working.

**Comment by JoV5** [comment] 2016-07-19 08:07
@jefflindholm how to update the version in the typescript.tsdk setting?

**Comment by jefflindholm** [comment] 2016-07-19 18:05
I did....
npm i -g typescript@beta
which tsc (for me was .nvm/versions/node/v6.3.0/bin)
so I opened code
menu = file - preferences - workspace settings
added this line
    "typescript.tsdk":
"/home/jeff.lindholm/.nvm/versions/node/v6.3.0/lib/node_modules/typescript/lib"

**Comment by dbaeumer** [comment] 2016-08-04 13:50
@jefflindholm I move issue to TS team / git repository since the TS compiler / language service powers both JS and TS inside VS Code. As you can see updating to the 2.0 beta of the TS compiler makes it work. 

Are there any objections to close this.

**Comment by DavyDeDurpel** [comment] 2016-08-04 14:01
no objections as I can confirm that it works with the 2.0 beta.

**Comment by dbaeumer** [comment] 2016-08-04 14:09
OK. Thanks. Closing then.

**Closed by dbaeumer** 2016-08-04 14:09 UTC
Labels: js, needs more info
