### ISSUE TITLE
Task command surround by single quite (') lead to syntax error on VSC 1.64.0

### ISSUE THREAD

**Issue by Massukio** [microsoft/vscode#142366] opened 2022-02-07 03:24 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.64.0
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Using the custom task.json to run task
```
"version": "2.0.0",
    "tasks": [
        {
            "label": "Run File - Robot Pure (CMD)",
            "windows": {
                "command": "${workspaceFolder}\\.venv\\Scripts\\activate && python -m robot",

            },
            "linux": {
                "command": "source ${workspaceFolder}/.venv/bin/activate && python -m robot"
            },
            "args": [
                "--loglevel", "TRACE:INFO",
                "--outputdir", "report",
                "${file}"
            ],
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "panel": "new",
                "focus": true
            },
            "options": {
                "cwd": "${workspaceFolder}",
                "env": {
                    "PYTHONIOENCODING": "UTF-8",
                    "PYTHONPATH": "${workspaceFolder}",
                    "PATH": "${workspaceFolder}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:"
                }
            }
        },
]
```
2. **The task run successfully on VSC 1.63.2** 
**But failed on VSC 1.64.0 and got syntax error**
```
File name, directory name or volume label syntax is incorrect
```

Investigating the commands VSC executed, and find the difference below
VSC 1.63.2:
The command surround by Double Quotes on 1.63.2  which can be run successfully
```
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c "...\.venv\Scripts\activate && python -m robot" --loglevel TRACE:INFO --outputdir report Test.robot"
```

VSC 1.64.0:
The command surround by Single Quotes on 1.64.0 which caused syntax error
```
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c '...\.venv\Scripts\activate && python -m robot' --loglevel TRACE:INFO --outputdir report Test.robot"
```

**Comment by alexr00** [comment] 2022-02-07 14:04
Duplicate of https://github.com/microsoft/vscode/issues/142196

**Closed by alexr00** 2022-02-07 14:04 UTC
Labels: *duplicate, new release
