### ISSUE TITLE
Terminal transforms characters

### ISSUE THREAD

**Issue by m-schuetz** [microsoft/vscode#117760] opened 2021-02-26 11:32 UTC
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Print something with tabs to terminal
2. The \t character will be replaced with spaces, which makes it impossible to copy&paste the results into an excel (or google sheets) sheet.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2021-02-26 19:45
I can't reproduce this issue. Can you pls attach a [gif](gifcap.dev) of this happening?

**Comment by potree** [comment] 2021-02-26 20:25
Is a screenshot ok? It shows that printing "test\tabc" looks like it's correct in the console, but the "\t" character actually gets printed as 4 spaces instead. When you copy&paste the result into notepad++, you can see that one of the spaces is selected. Because of that, i can't paste some debug output from the console into a google sheets document.

![image](https://user-images.githubusercontent.com/2094934/109351044-df23b500-7878-11eb-89f6-048ce1e5ba59.png)

**Comment by meganrogge** [comment] 2021-02-26 21:12
thanks -  I can reproduce this. this is as designed. we might do something to fix it upstream in xterm.js in the future. sorry it's causing you an inconvenience.

**Comment by meganrogge** [comment] 2021-02-26 21:16
Duplicate of #117760

**Closed by meganrogge** 2021-02-26 21:16 UTC
Labels: *as-designed, integrated-terminal, upstream-issue-linked
