### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by ilreddo** [microsoft/vscode#103180] opened 2020-07-23 17:00 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99915:161)
    at resolveModuleNamesWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100282:19)
    at processImportedModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101695:35)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101438:17)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100014:60
    at Object.forEach (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100014:16)
    at synchronizeHostData (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138753:26)
    at Object.getProgram (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146608:44)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147790:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.40-04224-g891a6cce2d44

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|14.21GB (14.18GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
vscode-deno|den|1.25.0
prettier-vscode|esb|5.1.3
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-07-23 17:43
Duplicate of https://github.com/denoland/vscode_deno/issues/89

Caused by the deno extension

**Closed by mjbvz** 2020-07-23 17:43 UTC
