### ISSUE TITLE
Copy line up/down key binding not working in Linux

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5363] opened 2016-04-15 21:14 UTC
- VSCode Version: 1.0.0 (present in release and latest alpha)
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Navigate to a line
2. Press Ctrl+Alt+Shift+UpArrow (or DownArrow)

Actual:
Nothing happens.

**Comment by Tyriar** [comment] 2016-04-17 22:43
Duplicate of https://github.com/Microsoft/vscode/issues/1782, I'll have another look at whether there are any available keybindings that don't conflict with Ubuntu's workspace defaults.

**Comment by Tyriar** [comment] 2016-05-14 02:46
Closing in favor of https://github.com/Microsoft/vscode/issues/509

**Closed by Tyriar** 2016-05-14 02:46 UTC
Labels: linux, v-test
