### ISSUE TITLE
Unable to open created files in vscode

### ISSUE THREAD

**Issue by kshitijzutshi** [microsoft/vscode#96830] opened 2020-05-02 13:19 UTC
Issue Type: <b>Bug</b>

Getting errors like this:

Unable to open 'package.json': Assertion Failed: argument is undefined or null.
Unable to open 'index.html': Assertion Failed: argument is undefined or null.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.12.0
emoji-snippets|dev|1.5.3
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.5.0
python|ms-|2020.4.76186
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2020-05-05 11:39
Duplicate of #94931

Here are steps to fix it locally -- https://github.com/microsoft/vscode/issues/94931#issuecomment-615000756

Otherwise, you can use the Insiders build which already has a fix.

**Closed by alexdima** 2020-05-05 11:39 UTC
