### ISSUE TITLE
Bug in cursor location within user snippets

### ISSUE THREAD

**Issue by richardruiter** [Microsoft/vscode#11742] opened 2016-09-09 05:30 UTC
- VSCode Version: 1.5.0 & 1.5.1
- OS Version: OS X 10.11.6 (15G1004)

Steps to Reproduce:

1. Add the following snippet to the javascript.json user snippets file:
```json
{
	 "Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');"
		],
		"description": "Log output to console"
	}
}
```
2. Then open an .js file and type "log" ENTER to insert the snippet.

Before the update of 1.5.0 the cursor appeared at $1 `console.log('|');` now at the end of the line  `console.log('');|`

**Comment by ramya-rao-a** [comment] 2016-09-09 06:49
@richardruiter I tried in OS X El Capitan 10.11.6 and Windows 10 with VS Code 1.5.1 and can't repro this. The cursor ends up in the right place.

Are you able to see this when extensions are disabled? Try running `code --disable-extensions`

**Comment by jrieken** [comment] 2016-09-09 07:25
same here - failing to reproduce. @richardruiter Please update your steps/sample

**Comment by ITSecMedia** [comment] 2016-09-09 08:04
This very annoying bug happens on my machine too.
Recognised in markdown snippets.
Windows x64 since Version 1.5.0 up to 1.5.1.

**Comment by jrieken** [comment] 2016-09-09 08:17
@ITSecMedia It would help if you include reproducible steps and the snippet you are completing

**Comment by jrieken** [comment] 2016-09-09 08:21
Just to make sure are talking about the same thing. This is what I see and believe is proper

![sep-09-2016 10-20-19](https://cloud.githubusercontent.com/assets/1794099/18380343/29c0d592-7677-11e6-81bb-439d51e90cad.gif)

![sep-09-2016 10-20-32](https://cloud.githubusercontent.com/assets/1794099/18380344/29db8144-7677-11e6-9470-f13d935e006a.gif)

**Comment by ITSecMedia** [comment] 2016-09-09 08:25
Sorry.

Just opened VSCode, started new markdown file using this snippet.

The tab-stops doesn't work anymore. When I have a text like this.

example [example](sc <-shortcode) example example example CURSOR HERE

The cursor is not placed at position $1 inside the place snippet but rather at the end of line.

```
{
	 "ShortCode": {
		"prefix": "sc",
		"body": [
			"{{% url_**$1** %}}"
		],
		"description": "Insert ShortCode"
	}
}
```

**Comment by jrieken** [comment] 2016-09-09 08:42
Thanks. I can reproduce now

**Comment by jrieken** [comment] 2016-09-09 08:45
As a workaround you can use tab completion (settings > ` "editor.tabCompletion": true`) which isn't affected by this.

**Comment by ITSecMedia** [comment] 2016-09-09 09:02
On my machine the bug occurs no matter if 
I press Enter after choosing the snippet 
or if I use the tab-completion feature with enabled setting ( "editor.tabCompletion": true ) 
The cursor is always send far behind the defined $1 tab-stop-cursor-position inside the placed snippet.
But I can wait, until it's fixed.
Thank you, we all LOVE VSCode  :-)

**Comment by rengare** [comment] 2016-09-09 09:10
Hello, i have the same issue, but on every snippets that I downloaded (angular 1, 2 html and my custom snippets). 
Greetings

**Comment by jrieken** [comment] 2016-09-09 14:29
My above workaround isn't valid - this only works when you are at column: 1 or with multiline snippets. I have pushed a fix now

**Comment by jrieken** [comment] 2016-09-09 14:35
To **verify**

* have a snippet like [above](https://github.com/Microsoft/vscode/issues/11742#issuecomment-245851307)
* type `foo foo sc` and complete the snippet
* make sure the cursor is between the \*\*-characters

**Comment by mrmlnc** [comment] 2016-09-09 14:38
@jrieken, hmm, broken case:

```json
{
    "after": {
        "prefix": "aftr",
        "body": [
            "afterEach((done) => {",
            "\t${1}test",
            "});"
        ],
        "description": "Mocha BDD: after() | afterEach()"
    }
}
```

![2016-09-09_17-37-44](https://cloud.githubusercontent.com/assets/7034281/18390750/281eafec-76b4-11e6-8686-2ba08c9fddf8.gif)

**Comment by jrieken** [comment] 2016-09-09 15:24
@mrmlnc This is with version *what*?

**Comment by mrmlnc** [comment] 2016-09-09 15:27
@jrieken, with latest commit (9606db116ce9a23cad7c577e4d3f1c679ca6ecf4) in a `release-1.5` branch.

**Comment by jrieken** [comment] 2016-09-09 15:28
I'll take a look

**Comment by jrieken** [comment] 2016-09-09 20:00
While fixing this I encountered a bigger underlying problem which is a more complex... Needs more thinking or we revert the change (simple snippets for multiple cursors) for 1.5 and revisit for Sept

**Closed** 2016-09-12 06:52 UTC
Labels: bug, important, snippets

**Comment by cauldyclark15** [comment] 2016-09-12 08:24
Hello, I am still having the issue same with #11782, cursor is not between quotes after autocomplete on HTML. I just updated to VS Code version 1.5.1, and using Windows 7. I am new here so if you need additional information from me, please advice.

**Comment by jrieken** [comment] 2016-09-12 08:58
@cauldyclark15 You need to wait for 1.5.2 or built from source

**Comment by cauldyclark15** [comment] 2016-09-12 09:01
@jrieken Thank you for your response, I understand now.

**Comment by dburles** [comment] 2016-09-20 01:46
Since this fix for some reason snippets only work once

**Comment by dburles** [comment] 2017-02-15 23:09
Still seeing the above issue

**Comment by ramya-rao-a** [comment] 2017-02-16 06:57
@dburles  I am able to confirm that the issue described above in https://github.com/Microsoft/vscode/issues/11742#issuecomment-245851307 and https://github.com/Microsoft/vscode/issues/11742#issuecomment-245932485 are working as expected.

Are you referring to these linked issues or your earlier comment of "snippets only work once" ?

**Comment by dburles** [comment] 2017-02-16 07:06
Sorry yeah the issue with snippets only working once. It's a strange one and I just haven't had time to dig into it. Basically I'll be able to write 'log[tab]' and have it expand to `console.log(...)` just fine but only one time, until I restart vscode.

**Comment by ramya-rao-a** [comment] 2017-02-16 07:07
@dburles Can you create a new issue for that since this issue is more about the cursor position after snippet expansion?

**Comment by dburles** [comment] 2017-02-16 07:12
Sure. Though I do recall that it wasn't a problem until this fix was released so it's possibly related.

**Comment by ramya-rao-a** [comment] 2017-02-16 09:00
@dburles In that case, do add a note about it in the new issue. Thanks!

**Comment by unChartedZone** [comment] 2017-02-16 22:39
This used to be an issue on osx, primarily with HTML files, this occurred right after a certain release of vscode, I think 1.7.0, but an update to 1.7.1 fixed it, I'm guessing Windows didn't get the same fix

**Comment by alandawkins** [comment] 2017-03-17 07:58
I have the same problem too, snippets only work for $1 and the it skip all next to the end of the snippet, if you've set $0, it will be $1 -> $0, all others will be skipped too. Both on Windows( my version is enterprise 10) and Ubuntu ( 16.04.2).
Since this issue I've give up snippets for a long time. : (
