### ISSUE TITLE
package.json git location mismatch

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#32553] opened 2017-08-15 14:20 UTC
- VSCode Version: 1.15
- OS Version: Manjaro Linux KDE Kernel 4.9

Steps to Reproduce:

1. Create a VSCode extension `yo code`
2. Create a `CHANGELOG.md` file
3. Use git diff view on `CHANGELOG.md`
4. `package.json` error is shown.

![screenshot_20170815_091556](https://user-images.githubusercontent.com/3067335/29319658-59ae2302-819a-11e7-873d-8e6f57ded256.png)

![ezgif-4-505714e317](https://user-images.githubusercontent.com/3067335/29319945-59c8744a-819b-11e7-9cd6-d95f72369a8f.gif)

Reproduces without extensions: Yes

**Comment by faustinoaq** [comment] 2017-08-15 14:30
Also this bug happens without user customized `settings.json`

![screenshot_20170815_092931](https://user-images.githubusercontent.com/3067335/29320270-40009ca8-819c-11e7-86d9-ae790e339672.png)

**Comment by joaomoreno** [comment] 2017-08-15 15:40
Duplicate of #20859, related to #24033

**Closed by joaomoreno** 2017-08-15 15:40 UTC
Labels: git, new release
