### ISSUE TITLE
Ctrl+Shift+E does not work

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#56473] opened 2018-08-15 14:16 UTC
Issue Type: <b>Bug</b>

Currently, `workbench.view.explorer` action is bound to `ctrl+shift+e` shortcut. After last update, this shortcut does not work anymore. I can assign `ctrl+e`, `shift+e`, but when I hit `ctrl+shift+e`, it will assign `ctrl+shift+undefined`. I also tried to manually override json file, but VSCode does not seem to understand this shortcut.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.17.14-arch1-1-ARCH

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.11.0
snapshot-tools|asv|0.0.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
prettier-vscode|esb|1.6.1
git-project-manager|fel|1.6.1
flow-for-vscode|flo|0.8.2
auto-close-tag|for|0.5.6
vscode-codemetrics|kis|1.17.1
vscode-gutter-preview|kis|0.13.1
graphql-for-vscode|kum|1.12.1
vscode-icons|rob|7.25.0
code-spell-checker|str|1.6.10

</details>

**Comment by sandy081** [comment] 2018-08-15 14:32
@tSte Can you please check by disabling all extensions?

Also open keybindings editor and see all Similar keybindings by right clicking on the entry and select `Find Similar Keybindings`

**Comment by miguelperes** [comment] 2018-08-15 14:44
It also happens to me. The shortcut works fine only if the code editor is **not** focused, showing/hiding the explorer properly.

**Comment by costela** [comment] 2018-08-15 14:50
It seems to be overridden by some lower-level textbox keybinding. Expanding on what @miguelperes noticed: the keybinding seems to be hijacked whenever a text-area has focus, including search boxes and the VCS commit textarea.

(I'm also on linux btw)

**Comment by sandy081** [comment] 2018-08-15 15:37
Works for me on Windows and Mac. Electron issue?

**Comment by bpasero** [comment] 2018-08-15 16:31
Duplicate of https://github.com/Microsoft/vscode/issues/48480

**Closed by bpasero** 2018-08-15 16:31 UTC
Labels: electron, electron-2.0.x-update, linux, new release, upstream

**Comment by GeorgeSapkin** [comment] 2018-08-16 10:51
This doesn't look like a duplicate of #48480 since this works perfectly fine on 1.25.x yet is broken on 1.26.x.

**Comment by costela** [comment] 2018-08-16 12:52
@GeorgeSapkin 1.26 [updated electron](https://code.visualstudio.com/updates/v1_26#_miscellaneous), which in turn [updated gtk2 to gtk3](https://electronjs.org/releases#2.0.0-beta.1).

**Comment by GeorgeSapkin** [comment] 2018-08-16 12:55
@costela sure, but the other issue is closed yet the problem is still here.

**Comment by m-thorsen** [comment] 2018-08-17 08:03
Possibly related:

https://developer.gnome.org/gtk3/stable/GtkIMContextSimple.html
> GtkIMContextSimple also supports entry of Emoji by their name. This works by first typing Ctrl-Shift-e, followed by an Emoji name.

Ctrl-shift-E in 1.26 on Linux DOES hijack the next few key presses (try ctrl+shift+e followed by `ctrl+z`, `ctrl+x`, `ctrl+c` and so on) and `ctrl+shift+e` into `:-)` does produce an unknown character (box).
