### ISSUE TITLE
Support to browse a workspace from a network address

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5681] opened 2016-04-23 00:00 UTC
it could be so cool to open a folder on a network by providing an address like `user@ip:address`

is there such functionality already or are ou planning to add ?

**Comment by dbaeumer** [comment] 2016-04-23 19:25
Suich a feature is not available right now.

@bpasero FYI.

**Comment by mjbvz** [comment] 2017-11-09 00:21
Duplicate of #29194

**Closed by mjbvz** 2017-11-09 00:21 UTC
Labels: explorer-files, feature-request, remote, workbench
