### ISSUE TITLE
Choosing workspace-enabled extensions explicitly in `extensions.json`

### ISSUE THREAD

**Issue by Rawieo** [Microsoft/vscode#61293] opened 2018-10-19 07:23 UTC
I use many different extensions to program in many different languages.

The problem is that some conflict with others.

For instance, if I would have Paredit enabled all the time, then, some crucial features of plain text editing become unavailable (i. e. `ctrl+right` to `cursorWordEndRight`).

This is partly solved by disabling extensions and then workspace-enabling it, but I suppose it would be even nicer to just specify enabled extensions per workspace (like, in `.vscode/extensions.json`)

I hope you'll like this idea. I personally find it very convenient.

**Comment by sandy081** [comment] 2018-10-23 08:07
Duplicate of #40239

**Closed** 2018-10-23 08:07 UTC
Labels: *duplicate, extensions
