### ISSUE TITLE
mark extention as installed

### ISSUE THREAD

**Issue by LaureKamalandua** [Microsoft/vscode#3456] opened 2016-02-25 14:52 UTC
Currently it is difficult to have an overview of which extensions have been installed. I would advise marking installed components in the command palette.

![extentions](https://cloud.githubusercontent.com/assets/12623827/13323000/ac6fc9d4-dbd7-11e5-94a7-f96ae282a8aa.jpg)

**Comment by egamma** [comment] 2016-02-25 20:34
There is the command "Extensions: Show Installed Extensions" does this address your needs?

**Comment by LaureKamalandua** [comment] 2016-02-25 20:40
As I said before, it would be nice to mark the installed components from the drop down. It's a hassle, having to manually take note of installed extensions. This should be marked from the drop down list.

**Comment by joaomoreno** [comment] 2016-02-25 21:37
Duplicate of #850

**Closed by joaomoreno** 2016-02-25 21:37 UTC
Labels: install-update
