### ISSUE TITLE
CSS @supports grammar check bug

### ISSUE THREAD

**Issue by Dwscdv3** [Microsoft/vscode#10944] opened 2016-08-25 11:48 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

When I use the @supports rule, the editor doesn't understand it and treat it as an error.
_By the way, is there anyway to make the editor ignores errors or warnings?_

**Comment by aeschli** [comment] 2016-08-26 15:48
duplicate of #1505

**Closed by aeschli** 2016-08-26 15:48 UTC

**Comment by aeschli** [comment] 2016-08-26 15:50
FYI, you can disable css validation with `css.validate: false` in the settings
