### ISSUE TITLE
Some Cascadia Code (specifically) Ligatures not working inside the editor

### ISSUE THREAD

**Issue by Ceebox** [microsoft/vscode#107539] opened 2020-09-27 12:38 UTC
- VSCode Version: Latest
- OS Version: Windows Latest (No insider)
- Font Version: Latest release from the GitHub repo

Steps to Reproduce:

1. Set Cascadia Code as the font
2. Enable ligatures

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/49747230/94365168-8e8c0e00-00c6-11eb-8105-d940e136f953.png)
^ As you can see here, != is recognised correctly, but not ==, which should join together.

**Comment by Ceebox** [comment] 2020-09-27 12:38
My settings.json file reads:
`{
  "glassit.alpha": 255,
  "workbench.colorTheme": "Monokai Pro",
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "variable.other.object",
        "settings": { "foreground": "#8bb4f7" }
      }
    ]
  }, //Makes objects a nicer colour
  "editor.fontFamily": "'Cascadia Code'",
  "editor.fontLigatures": "true",
  "editor.accessibilitySupport": "off",
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "window.zoomLevel": 1,
  "python.jediEnabled": false,
  "workbench.iconTheme": "ayu",
  "todo-tree.tree.showScanModeButton": false,
  "indentRainbow.includedLanguages": ["None"],
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.formatOnType": true,
  "python.languageServer": "Microsoft",
  "vsicons.dontShowNewVersionMessage": true,
  "code-runner.enableAppInsights": false,
  "code-runner.runInTerminal": true,
  "terminal.integrated.rendererType": "dom",
  "workbench.colorCustomizations": {} // for example ["nim", "nims", "python"]
}`

**Comment by alexdima** [comment] 2020-09-28 13:07
@Ceebox I think the problem is the usage of the string `"true"` instead of the boolean `true` in `"editor.fontLigatures": "true"`. Can you please try `"editor.fontLigatures": true` ?

**Comment by Ceebox** [comment] 2020-09-28 16:12
I have tried this, however, my situation remains the same.
![image](https://user-images.githubusercontent.com/49747230/94458376-c5891f00-01ad-11eb-9b2a-9cc5872e51b0.png)

**Comment by 7ranceaddic7** [comment] 2020-09-30 17:29
Can confirm.

```
    "editor.fontFamily": "'Cascadia Code', monospace",
    "editor.fontLigatures": true,
```
![image](https://user-images.githubusercontent.com/4062616/94719244-c7ff8c00-0307-11eb-89ff-867deb3db41f.png)

**Comment by alexdima** [comment] 2020-10-01 11:56
@Ceebox @7ranceaddic7 Are you certain you have installed the correct font? I see they call out explicitly that they offer two variants, one with ligatures, and one without ligatures and they are both called the same:

https://github.com/microsoft/cascadia-code#installation
<img width="704" alt="Screen Shot 2020-10-01 at 13 55 23" src="https://user-images.githubusercontent.com/5047891/94806146-cf00ca00-03ed-11eb-90d0-c67de349f191.png">

**Comment by Ceebox** [comment] 2020-10-01 14:03
Yes, I am using that exact version.

**Comment by alexdima** [comment] 2020-10-01 14:09
@Ceebox I have just tried on a fresh Windows VM as well, and I cannot reproduce:
* I downloaded https://github.com/microsoft/cascadia-code/releases/download/v2009.22/CascadiaCode-2009.22.zip
* I installed the font at `ttf\CascadioCode.ttf`
* I restarted VS Code:
* I configured vscode:
```
{
    "editor.fontFamily": "Cascadia Code",
    "editor.fontLigatures": true
    // =>
}
```
Ligatures work fine for me:

![image](https://user-images.githubusercontent.com/5047891/94820105-5a835680-0400-11eb-9d74-995d6e79a526.png)

**Comment by 7ranceaddic7** [comment] 2020-10-01 14:28
Yes, @alexdima, I have the latest version of Cascadia.

![image](https://user-images.githubusercontent.com/4062616/94821245-3bf86d80-03b6-11eb-9801-443394caa9cc.png)

This **IS NOT** and issue about **ALL** ligatures.  You keep using the same SINGLE ligature (=>) to prove nothing I haven't already helped proven ... that particular single ligature works.

![image](https://user-images.githubusercontent.com/4062616/94822281-51ba6280-03b7-11eb-8ede-dbf7ac1614c6.png)

Please stop using THAT ligature to prove all ligatures works.  THEY DO NOT.

**Comment by alexdima** [comment] 2020-10-01 15:05
It seems to me that you do not like the glyph that Cascadia Code has chosen to render for the `==` ligature. Please take a very close look at the following:

You can observe that `==` changes in rendering when the setting is on or off:

![Kapture 2020-10-01 at 17 03 41](https://user-images.githubusercontent.com/5047891/94826900-198f4000-0408-11eb-87d3-5fdb120948e2.gif)

Do you have another software on your machine where the ligature `==` is rendered differently in Cascadia Code or a screenshot from the project that shows how this ligature should render?

**Comment by Ceebox** [comment] 2020-10-01 15:06
This is bizarre. Looks like I will take this over to the Cascadia Code repo, which is weird because the font joins the == in atom. Thanks for the help.

**Comment by 7ranceaddic7** [comment] 2020-10-01 19:11
@alexdima 

Thank you for demonstrating that, it's not something readily noticeable and I completely missed that.

I have to agree that is the problem and it is on Cascadia, not VSCode.

You are absolutely correct about this.  I appreciate your indulgence and patience.

I agree @Ceebox that is bizarre, there's nothing gained but confusion.  Why bother forming a ligature that doesn't actually changing the representation.

**Comment by alexdima** [comment] 2020-10-01 19:27
I will close this issue here for now, we can reopen if we figure out the rendering in VS Code is bad.

**Closed by alexdima** 2020-10-01 19:27 UTC
Labels: font-rendering, needs more info
