### ISSUE TITLE
Terminal loses focus when switching SCM working sets

### ISSUE THREAD

**Issue by apaleslimghost** [microsoft/vscode#214209] opened 2024-06-04 09:01 UTC
Type: <b>Bug</b>

1. have `scm.workingSets` enabled
2. switch Git branches from the terminal (e.g. with `git switch`) 

the terminal will lose focus when the new working set is enabled (because one of the editors in the new working set steals focus)

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 94f921db-c973-4da5-acd8-7d0c93717c36|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-routes|aki|0.6.3
icons-carbon|ant|0.2.6
vscode-custom-css|be5|7.2.2
vscode-icontheme-nomo-dark|be5|1.3.6
github-markdown-preview|bie|0.3.0
lit-html|bie|1.11.1
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.0
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
file-browser|bod|0.2.11
mermaid-markdown-syntax-highlighting|bpr|1.6.6
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
macos-modern-theme|dav|2.3.19
vscode-eslint|dba|2.4.4
vscode-deno|den|3.37.1
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.0.4
EditorConfig|Edi|0.16.4
el-vsc-product-icon-theme|ElA|0.1.8
prettier-vscode|esb|10.4.0
file-icons|fil|1.1.0
vscode-firefox-debug|fir|2.9.10
vscode-pull-request-github|Git|0.88.1
vscode-graphql|Gra|0.11.0
vscode-graphql-execution|Gra|0.2.6
vscode-graphql-syntax|Gra|1.3.6
fuzzy-search|jac|0.0.3
search-editor-apply-changes|jak|0.1.1
better-cpp-syntax|jef|1.17.2
icons-octicons|joa|0.1.0
vscode-circuitpython|joe|0.1.20
magit|kah|0.6.61
endwise|kai|1.5.1
emoji-icons|mig|1.6.1
fluent-icons|mig|0.0.18
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-js-profile-flame|ms-|1.0.9
vscode-serial-monitor|ms-|0.11.0
vsliveshare|ms-|1.0.5918
vscode-jest|Ort|6.2.5
material-icon-theme|PKi|5.3.0
prisma|Pri|5.14.0
livescript|pse|0.1.1
multi-command|ryu|1.6.0
ruby-lsp|Sho|0.7.1
vscode-autohide|sir|1.0.10
fish-vscode|sky|0.2.1
shader|sle|1.1.5
vscode-mc-shader|Str|0.9.9
vscode-nushell-lang|The|1.9.0
vcl|tho|0.1.2
jest-snapshot-language-support|tle|1.1.1
pdf|tom|1.2.2
devicetree|tro|2.3.1
kconfig-lang|tro|1.2.0
vscode-arduino|vsc|0.6.0
vim|vsc|1.27.3
vspacecode|VSp|0.10.18
whichkey|VSp|0.11.4
vscode-mermaid-preview|vst|1.6.3
rails-buddy|wil|1.0.2
vscode-ruby|win|0.28.0
clang-format|xav|1.9.0
pretty-ts-errors|Yoa|0.5.4
vscode-open-in-github|ziy|1.3.6

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31064719
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecationcf:31061161
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by lszomoru** [comment] 2024-06-04 10:31
Duplicate of https://github.com/microsoft/vscode/issues/212048

**Closed by lszomoru** 2024-06-04 10:31 UTC
