### ISSUE TITLE
The autocomplete, suggestions and IntelliSense menu just shows "loading".

### ISSUE THREAD

**Issue by piotrjakobek** [microsoft/vscode#88694] opened 2020-01-15 16:19 UTC
Hi!
I got this problem with autocomplete and IntelliSense when working on a JS project.

Auto suggestions are off. When I hit Ctrl + Space the menu just shows loading. As shown on the screen below. A noticed that the "Initializing JS/TS Language feature" was working permanently but after disabling extensions it disappeared.

I'm just starting to learn JS and the project is rather simple from a course that I am following.
It appeared after going from opening index file in the browser to using a dev server and adding tools to the project environment(node, etc). Unfortunately now, this happens in the previous much simpler projects that I did at the beginning of the course. By simpler, I mean that they don't use node and dev tools that come with. 

As I am starting my journey with JS being somewhat dyslectic this is an essential feature. 
Please help!

![suggestions](https://user-images.githubusercontent.com/52453972/72447729-21458080-37b6-11ea-8a2d-fcbecb1f3e6b.png)

What I have tried with no success:
1. disabled all extensions
2. opened simpler projects not hosted on a dev node server 
3. downloaded Insiders and opened the same projects with no success. 
4. searched existing issues to avoid creating duplicates:
#47253
#3601
#72919

5. These look similar but are not resolved, I followed the suggestions mentioned in them and it didn't help.

**I followed the instructions to acquire the ts server.log from:**
#72919.
File attached below:
[tsserver.log](https://github.com/microsoft/vscode/files/4065690/tsserver.log)

**My system info:**

**Stable ver**
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Insiders**
Version: 1.42.0-insider (user setup)
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T09:36:35.018Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment] 2020-01-15 16:36
Thanks for the information and logs!

The is a duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-15 16:36 UTC
Labels: javascript

**Comment by doksara** [comment] 2020-01-16 18:45
I have the same issue. What does TypeScript have to do with this @mjbvz ? I don't even use TypeScript nor have it installed.
