### ISSUE TITLE
Images saved/updated outside of VS Code aren't updated in VS Code

### ISSUE THREAD

**Issue by forgottenleaf** [Microsoft/vscode#10577] opened 2016-08-16 09:53 UTC
- VSCode Version: 1.4.0
- OS Version: OS X El Capitan 10.11.1 (15B42)

Steps to Reproduce:

1.  Open a folder that has images in it.
2. Open the image in VS Code.
3. Change the contents of the image in an editor outside VS Code.
4. Image appears the same as it did in step 2 (even if you close and re-open it in VSCode).

The only way to get the image to show the new content is to completely close the folder from vscode and re-open it.

**Comment by bpasero** [comment] 2016-08-16 13:13
We are not an image editor :).

Duplicate of https://github.com/Microsoft/vscode/issues/7951

**Closed by bpasero** 2016-08-16 13:13 UTC
