### ISSUE TITLE
Selecting install extension then clicking Readme shows two conflicting dialogs

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4516] opened 2016-03-21 17:47 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. F1 -> Install extension
2. Click install button
3. Click Readme button
4. Click out of the command window

Actual:
Two notifications come up. One asking if you would like to install that extension (which you already have) and another that says you need to restart to enable the extension.

![installreadme](https://cloud.githubusercontent.com/assets/12900364/13928224/154649a0-ef52-11e5-97a2-9b4a4ffc60e8.JPG)

Expected:
Only the "restart to enable it." dialog to show up.

**Comment by joaomoreno** [comment] 2016-03-22 12:14
Duplicate of #4518

**Closed by joaomoreno** 2016-03-22 12:14 UTC
Labels: extensions, v-test
