### ISSUE TITLE
[Windows] Gettiing error "Cannot convert undefined or null to object"  while adding .Js or .cs file.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4526] opened 2016-03-21 20:21 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1.  Launch app and open any folder.
2. Try to add .js or .cs file by clicking on + sign.
3. Verify app behavior.
4. Try to add other file like go, css, ts and verify app behavior.

Actual: Getting error "Cannot convert undefined or null to object" when adding .js or .cs file.
Expected: It should not throw any error while adding .js or .cs file.

Note: I tried the same steps on MAC and it is working fine. 

![image](https://cloud.githubusercontent.com/assets/17735796/13932862/7a1fd8ae-ef67-11e5-9920-ede5e4781ea4.png)

**Comment by bpasero** [comment] 2016-03-22 08:46
Possibly a duplicate of https://github.com/Microsoft/vscode/issues/4536 ?

@v-pavanp having a hard time to reproduce, are you able to "break on error" in the developer console and try again? can you send me the workspace where this happens?

**Comment by bpasero** [comment] 2016-03-23 06:05
@v-pavanp so does it reproduce when you run "code --disable-extensions"?

**Comment by bpasero** [comment] 2016-03-23 07:13
Not reproducible according to @v-pavanp

**Closed by bpasero** 2016-03-23 07:13 UTC
Labels: bug, candidate, important, v-test
