### ISSUE TITLE
Context-menu to "Open in Integrated Terminal" doesn't respect terminal.integrated.defaultProfile

### ISSUE THREAD

**Issue by burritosoftware** [microsoft/vscode#132360] opened 2021-09-04 22:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Set a default terminal profile to one that is NOT PowerShell: https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles
2. Right-click in the working directory in the Explorer tab on the left, and choose to `Open in Integrated Terminal`.

The terminal should respect your default profile, but instead it will always open PowerShell. This doesn't happen when using ``CTRL + ` ``.

**Comment by gjsjohnmurray** [comment] 2021-09-04 22:24
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-04 22:25 UTC
Labels: *duplicate, new release
