### ISSUE TITLE
Find on big files does not highlight every match

### ISSUE THREAD

**Issue by williamokano** [Microsoft/vscode#32504] opened 2017-08-14 20:52 UTC
- VSCode Version: 1.15.0
- OS Version: Linux Mint 18.1

Steps to Reproduce:

1. Open "very big" dataset (mine have 50625 lines, and sorry, can't distribute)
2. Perform a search on this very big dataset.

The find window will show "1 of 999+" instead of highlighting every match. The minimap also show only a few results, although there's at least one match every single line.

![image](https://user-images.githubusercontent.com/5909442/29290708-7cd41630-8117-11e7-948e-5bcac3c71903.png)

Reproduces without extensions: Yes

Observations:
If I click to navigate to the previous match, it will show `? of 999+` but it work perfectly, setting the cursor on the correct position on the last line of the "very big" file, but still don't highligthing the match.

![image](https://user-images.githubusercontent.com/5909442/29290806-c9ff3dc2-8117-11e7-8d16-b774d2a8bfe7.png)

**Comment by rebornix** [comment] 2017-08-15 18:35
Duplicate of https://github.com/Microsoft/vscode/issues/496

**Closed by rebornix** 2017-08-15 18:35 UTC
Labels: editor, editor-find-widget, new release
