### ISSUE TITLE
File Explorer won't copy directories

### ISSUE THREAD

**Issue by michael-gracy** [microsoft/vscode#78992] opened 2019-08-12 22:44 UTC
Issue Type: <b>Bug</b>

Right clicking and selecting Copy on a subdirectory. Then right clicking and selecting Paste on a destination directory produces the error message: File to paste was deleted or moved meanwhile
I did not delete or move any files while performing these copy/paste operations.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|-psn_0_7960471|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
puppet|Bor|0.3.1
vscode-clock|Com|0.0.1
better-comments|aar|2.0.5
vscode-color-pick|ada|0.6.2
Bookmarks|ale|10.5.0
jenkins-status|ale|3.1.2
project-manager|ale|10.6.0
read-only-indicator|ale|3.0.3
aws-toolkit-vscode|ama|1.0.0
vscode-database|baj|2.2.0
git-easy|bib|1.11.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer-2|Coe|0.0.28
githistory|don|0.4.6
jupyter|don|1.1.5
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|1.9.0
code-runner|for|0.9.12
vscode-pull-request-github|Git|0.9.2
code-sync|gol|2.5.3
activitusbar|Gru|0.0.20
todo-tree|Gru|0.0.140
ansible|haa|0.2.8
beautify|Hoo|1.5.0
svn-scm|joh|1.54.4
puppet-vscode|jpo|0.19.0
aws-cli-configure|mar|0.3.0
terraform|mau|1.3.12
ecdc|mit|1.3.0
prettify-json|moh|0.0.3
perl-debug|mor|0.6.1
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
python|ms-|2019.8.29288
Go|ms-|0.11.4
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.8.1
aws-actions|Ple|1.0.0
vscode-yaml|red|0.4.1
perl|ric|0.9.0
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
trailing-spaces|sha|0.3.1
guides|spy|0.9.3
stackery|sta|1.0.3
code-spell-checker|str|1.7.17
ansible-autocomplete|tim|0.0.2
shellcheck|tim|0.8.1
terminal-tabs|Tyr|0.2.0
vscode-glide|vit|1.0.2
sync-rsync|vsc|0.36.0
vscode-icons|vsc|9.2.0

(7 theme extensions excluded)

</details>

**Comment by michael-gracy** [comment] 2019-08-12 22:52
Looked at https://github.com/microsoft/vscode/issues/78992#issuecomment-520622301 (Inconsistent file pasting in explorer between PWD and other directories). It is similar, but no mention of the error message I am encountering now and I am on the current stable version which the previous bug is for an older version.

**Comment by isidorn** [comment] 2019-08-13 08:56
I can not reproduce this.
Can you please give exact reproducable steps?
What repository do you use, do you always see this?

**Comment by bpasero** [comment] 2019-08-13 09:07
@isidorn I am not sure the error message is precise:

https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/files/browser/fileActions.ts#L1111

Why not add the actual file error in there too or at least log it?

**Comment by isidorn** [comment] 2019-08-13 10:33
@bpasero good find, I have added the actual file error.
@michael-gracy can you please try with VSCode insiders on Wednesday. Since that will have better error reporting so we might know better what the issue is. Thanks

**Comment by isidorn** [comment] 2019-08-20 09:02
Closing until more data is provided

**Closed by isidorn** 2019-08-20 09:02 UTC
Labels: file-explorer, needs more info
