### ISSUE TITLE
Welcome view: "window reload notification" even when not needed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121862] opened 2021-04-21 19:46 UTC
Refs: https://github.com/microsoft/vscode/issues/119463

1. Welcome view, click on extension to install, notice notification

The issue is that we:
* Show notification even if the extension install does not require a reload
* Wording is not that good. Button should be called "Reload"
* Consider just doing this automatically and not showing a notification since it is user intiated

![Screenshot 2021-04-21 at 21 43 57](https://user-images.githubusercontent.com/1926584/115611690-b1904080-a2ea-11eb-8343-c6a939731ba5.png)

**Comment by chrmarti** [comment] 2021-04-22 08:56
Duplicate of https://github.com/microsoft/vscode/issues/109423

**Closed by chrmarti** 2021-04-22 08:56 UTC
