### ISSUE TITLE
Have a shallower max "type expansion depth" to parameterHints

### ISSUE THREAD

**Issue by JobLeonard** [Microsoft/vscode#44928] opened 2018-03-02 14:44 UTC
My example applies to plain JavaScript, I don't know how this is with other languages.

Instead of the prototypical type, the parameter hints show the fully expanded objects. As far as I can tell it does this up to two or three levels deep. This basically makes the type hint size grow recursively, so pretty much exponentially I think?

Now, I have a bunch of objects with a large number of properties. They also all have functions with multiple parameters (say, four, five), each of which tends to be one of each other. 
Their types are [mutually recursive](https://en.wikipedia.org/wiki/Mutual_recursion), which means they blow up until the inferrence engine reaches a maximum depth.

Let's see how crazy this gets if you have half a dozen objects with a large number of properties, including functions that take four, five other objects as parameters:

![ridiculous types2](https://user-images.githubusercontent.com/259840/36901352-26d0df68-1e27-11e8-9712-ffcea0983c69.gif)

I don't even know if it has a real limit here, it looks like it simply checks for recursion and bails out. For example, `Update.update()` takes a `DerivedData` object, which contains all other objects. Each of those objects has a method called `update()` that takes, among other things, an `Update` object as a parameter. At this point, the type hint says `u: typeof Update`.

Same logic applies to each other parameter.

I figured this out by hovering over an `Update` instance and selecting the fully expanded type information:  fully inferred type: [u_full_inference.txt](https://github.com/Microsoft/vscode/files/1775352/u_full_inference.txt). Based on that, I also recreated the output of the pop-up for *just this one* parameter, white-spaces removed and all: [u_expanded.txt](https://github.com/Microsoft/vscode/files/1775328/u_expanded.txt). It adds up to **404 lines in total**, like so:

```
u: { scaleFactor: boolean; ascIndices: 
boolean; totalIndices: boolean; 
settings: boolean; x: { logScale: 
boolean; jitter: boolean; attr: 
boolean; }; y: { logScale: boolean; 
jitter: boolean; attr: boolean; }; 
color: { mode: boolean; logScale: 
boolean; clip: boolean; lowerBound: 
boolean; upperBound: boolean; attr: 
boolean; }; backingArrays: boolean; 
convertColorData: boolean; 
convertCoordinates: boolean; 
calcLayout: boolean; prerenderSprites: 
boolean; scaledXY: boolean; 
sortedData: boolean; blitSprites: 
boolean; width: boolean; height: 
boolean; pixelRatio: boolean; context: 
boolean; updateContext: (m: { 
backingArrays: { totalIndices: number; 
spriteLength: number; cIdx: 
Uint16Array; cIdxFull: Uint16Array; 
coordinates: { [x: string]: any; x: 
Float32Array; y: Float32Array; }; 
scaleToContext: { [x: string]: any; x: 
{ [x: string]: any; data: Float32Array;
iData: Float32Array; pData: 
Float32Array; }; y: { [x: string]: any;
data: Float32Array; iData:
...
... 404 lines of this type-inference soup
```

And that's *one* parameter, of *one* method.

Look... I know I may have made some dubious architectural choices here, but ignoring that for now, wouldn't this be solved by:

- not expanding the types at all if there is a prototype, instead just showing `u: typeof Update`
- having a check like "if the expanded type `Foo` would result in a string of more than 50 characters, use `foo: typeof Foo` instead"

**Comment by JobLeonard** [comment] 2018-03-02 14:58
I mean, in a way I'm pretty impressed by IntelliSense:

"Your type spans 1308 lines of code, not including bailed-out recursion? [No problem mate, here you go](https://github.com/Microsoft/vscode/files/1775523/scaletocontext.update.type.txt)!"

I dig your enthusiasm, IntelliSense, but you're kind of trying *too* hard now...

**Comment by mjbvz** [comment] 2018-03-06 05:02
Duplicate of https://github.com/Microsoft/TypeScript/issues/1510 and https://github.com/Microsoft/TypeScript/issues/14662 Currently we always return the full types. We need to think of smart way to shorten these so they are more readable

**Closed by mjbvz** 2018-03-06 05:02 UTC
