### ISSUE TITLE
Feature Request: Ability to drag the file-editing block into a separate window

### ISSUE THREAD

**Issue by nechar** [Microsoft/vscode#60703] opened 2018-10-11 23:56 UTC
Most of developer these days use 2 to 3 monitors for better productivity. (I personally use 3 monitors)
However, we are not able to take advantage of the second monitor while using VS-code because it  is designed so everything has to be confiend in one single screen. There are not much room to work in a screen.
Would appreciate if you could make it be able to divide the components into multiple screens.

**Comment by egamma** [comment] 2018-10-12 07:34
Duplicate of #10121

**Closed by egamma** 2018-10-12 07:34 UTC
