### ISSUE TITLE
Invalid position of cursor when changing zoom level

### ISSUE THREAD

**Issue by thorseye** [Microsoft/vscode#27442] opened 2017-05-29 12:51 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 3.10.0-514.16.1.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.5|
|html-css-class-completion|Zignd|1.2.0|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.2|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|tslint|eg2|0.15.0|
|prettier-vscode|esbenp|0.17.1|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|gitlab-mr|jasonn-porch|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.0|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.3.0|
|jenkinsfile-support|secanis|0.1.0|;

---

Steps to Reproduce:

1. Zoom in (`Ctrl +`)
2. Cursor is displayed at the wrong position:
![Wrong position of cursor](http://i.imgur.com/RZa1ZAC.png)

**Comment by alexandrudima** [comment] 2017-05-30 09:18
Duplicate of #26151

**Closed by alexandrudima** 2017-05-30 09:18 UTC
