### ISSUE TITLE
Markdown preview of untitled document fails to live update after saving it

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#41013] opened 2018-01-02 00:36 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.22
python|ms-|0.9.1
csharp|ms-|1.13.1
sublime-keybindings|ms-|3.0.3
vscode-input-sequence|tom|0.2.0

---

Steps to Reproduce:

1. Open new document
2. Set language to markdown
3. Open preview to side
4. Edit & observe live updates
5. Save document
6. Edit & observe preview no longer live updates

Closing & re-opening preview fixes the issue.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2018-01-02 18:23
Duplicate of #12033

**Closed by mjbvz** 2018-01-02 18:23 UTC
Labels: markdown
