### ISSUE TITLE
Code folding chevron icon is confusing

### ISSUE THREAD

**Issue by SirMaxxx** [microsoft/vscode#78024] opened 2019-07-27 01:04 UTC
The icons now used for code expansion in Insiders 1.37.0 are essentially a '>' or a '>' rotated through 90 degrees.

when looking at code that uses '>' (e.g. HTML) and code is collapsed, there is visual confusion as it can appear there is a misplaced '>' in code...

e.g. in the code below on line 10
![image](https://user-images.githubusercontent.com/39082538/61987931-486c9200-b05e-11e9-848d-f8aba30cd9d7.png)

IMHO the original icons used were fine and did not need changing... at the very least, could they be coloured differently to easily distinguish from code at a glance?

**Comment by kanlukasz** [comment] 2019-08-05 18:10
Oh, I see now where the problem is.
This is in fact problematic and it should undoubtedly be changed

**Comment by coaperator** [comment] 2019-08-08 23:00
### **Return +/- to collapse the code!**

**Comment by salembeats** [comment] 2019-08-09 02:50
This is someone creating confusing UX in their attempt to accomplish their idea of _"pretty UI"_.

It's also an example of solutionism; Putting forth solutions to problems that don't exist. There was never any usability issue with the old expand/close icons.

**Comment by Mitiko** [comment] 2019-08-09 06:58
The angle brackets are not cool looking. I like +/- better

**Comment by Cirieno** [comment] 2019-08-09 11:15
Or perhaps give the option to switch between new and old style icons.

I personally preferred the old style, as that is a convention used across many editors for many, many years.

**Comment by lisa-tong** [comment] 2019-08-09 18:44
If you're bringing back +/-, please keep the box outline! It was much more intuitive.

**Comment by ErikHumphrey** [comment] 2019-08-10 20:06
Oh, that's what they meant by +/- being changed to carets. Yeah, that's even worse than just using a solid triangle as an arrow.

**Comment by ShinRai1090** [comment] 2019-08-11 03:52
+1 to this, So many issues with the icons overall 😞. Best would be to give a opt-in for older set of icons or provide a way to make a selective change through either a set folder of icons or _settings.json_.

**Comment by MarkMcTernan** [comment] 2019-08-11 22:37
Yikes, how hard is it to make the choice configurable?  Yet here we are, stuck with these awful new icons that are even more inconsistent than the "problem" they were meant to fix.

At the very least give us the option to go back.

**Comment by ErikHumphrey** [comment] 2019-08-12 02:16
> Yikes, how hard is it to make the choice configurable? Yet here we are, stuck with these awful new icons that are even more inconsistent than the "problem" they were meant to fix.
> 
> At the very least give us the option to go back.

To be fair, limiting it to one option makes it easier to maintain if the system changes in the future. Technically, it is already configurable, you just have to source the icons yourself.

**Comment by Cirieno** [comment] 2019-08-12 13:27
> To be fair, limiting it to one option makes it easier to maintain if the system changes in the future. Technically, it is already configurable, you just have to source the icons yourself.

Looking at the icons through the devtools, it looks like they're SVGs.  You'd have to override them with other SVGs, and some sort of CSS override -- how would one go about doing that?

**Comment by dmvvilela** [comment] 2019-08-12 18:28
LOL what have they done??? All the icons is stupid and ugly.. Revert everything to what it was please! Definitely including on this left sido bar icons.. Please. Also.. how do i downgrade till then?

**Comment by gjsjohnmurray** [comment] 2019-08-12 18:43
> how do i downgrade till then?

https://github.com/microsoft/vscode/issues/78748#issuecomment-519795130 has links to 1.36.1 kits.

You may also want to change the `update.mode` setting to prevent an automatic upgrade.

**Comment by zkriszti** [comment] 2019-08-13 07:54
+1 for bringing back the "+" and "-" for code folding.

**Comment by noudAndi** [comment] 2019-08-13 18:40
+1 Please revert that change and bring back the old behavior, which was perfectly fine. There was no need to change it.

**Comment by nonoroazoro** [comment] 2019-08-14 09:01
Some times you should stick to the old ways.

**Comment by schwemmer** [comment] 2019-08-14 13:37
+1 for bringing back the old icons, at least for code folding.

**Comment by assuming** [comment] 2019-08-15 04:10
The problem is that it's not only the folding arrow icon looks bad, icons on the left bar make the whole editor even worse. They are too thin and, as someone said, the debug icon looks like a real spider and I have to hide this bar (people who have arachnophobia like me)

**Comment by eamodio** [comment] 2019-08-15 14:12
If you do change these to something other than the new ones please keep the current as an option. I really like the new ones! 😁

**Comment by lllopo** [comment] 2019-08-16 11:38
As I wrote on another thread, the problem is not the chevron, but the fact that you make your gutter the same color as the code background. This makes any content on the gutter confusing incl. the line numbers. Try setting a different gutter background and you'll see how everything will look perfectly normal immediately.

**Comment by SirMaxxx** [comment] 2019-08-16 12:51
Sorry but that's just not the case. I had no problem with the previous
icons ... Same colour scheme, just different icon.

So the single thing that has changed is the icon.

And it is causing me an issue.

Tbh it's not a huge issue, but the first time I opened an html page with
the new chevron, I genuinely spent time looking to see why the angle
brackets didn't line up.

So, no, it's not a colour issue, it is an icon issue.

**Comment by ErikHumphrey** [comment] 2019-08-16 13:08
> As I wrote on another thread, the problem is not the chevron, but **the fact that you make your gutter the same color as the code background**. This makes any content on the gutter confusing incl. the line numbers. Try setting a different gutter background and you'll see how everything will look perfectly normal immediately.

That is the default, and that's also how it is in Visual Studio. I think most people would agree that having a gutter colour different from the code background colour in Visual Studio Code would be quite abnormal, looking worse or at least archaic (NetBeans). By default, some editors only put a vertical hairline between the code and the gutter instead (Eclipse, IntelliJ IDEA, possibly VS). There's a sizeable margin between the code and the line numbers, which are all grey, right-aligned, and incrementing, so they're tough to confuse

**Comment by lllopo** [comment] 2019-08-16 13:24
> > As I wrote on another thread, the problem is not the chevron, but **the fact that you make your gutter the same color as the code background**. This makes any content on the gutter confusing incl. the line numbers. Try setting a different gutter background and you'll see how everything will look perfectly normal immediately.
> 
> That is the default, and that's also how it is in Visual Studio. I think most people would agree that having a gutter colour different from the code background colour in Visual Studio Code would be quite abnormal, looking worse or at least archaic (NetBeans). By default, some editors only put a vertical hairline between the code and the gutter instead (Eclipse, IntelliJ IDEA, possibly VS). There's a sizeable margin between the code and the line numbers, which are all grey, right-aligned, and incrementing, so they're tough to confuse

Well ... much, much more readable for sure, don't know if it is archaic or abnormal. But I don't want to get in the same trend of discussions which is modern or not. Just sharing the fact that different gutter color definitely leads to zero problems with readability of the chevrons. Still, though - the old +/- style was just fine too indeed. I'm only strongly against bringing back the triangles on the tree and breadcrumbs, where the chevrons are much better.

**Comment by Batalex** [comment] 2019-08-16 14:02
> you make your gutter the same color as the code background

Well actually I do not, VS Code color themes do it.

**Comment by ErikHumphrey** [comment] 2019-08-16 14:24
>I'm only strongly against bringing back the triangles on the tree and breadcrumbs, where the chevrons are much better.

Agreed, the chevrons are fine in the breadcrumbs and tree. Looks a little off with the Explorer section headers (Open Editors, Projectname, Outline, etc.), but I think I'll get used to it. They're not actually too bad for code folding either, since they only display when moused over, but it could be an option.

**Comment by dmvvilela** [comment] 2019-08-16 14:29
I hate it.. i prefer + and -.. Didnt exist the need to change that..

**Comment by lllopo** [comment] 2019-08-16 14:34
> > you make your gutter the same color as the code background
> 
> Well actually I do not, VS Code color themes do it.

To be honest, I've override these in settings, so the themes can't mess with it on my setup.

**Comment by Batalex** [comment] 2019-08-16 15:19
This means there is an issue either with the icons or with the color themes ;)

**Comment by jcklpe** [comment] 2019-08-16 22:25
I am personally neutral on whether the folding icons should be +/- or a caret, but I do think it's worth bringing this issue to people's attention: https://github.com/microsoft/vscode/issues/50359

While back I proposed that the code folding icons be more contextually placed in the editor. I did a quick mockup here: 
![image](https://user-images.githubusercontent.com/9451726/63201387-a6333f00-c04a-11e9-8d70-749f19c46e91.png)

I think there are quite a few ways that code folding could be improved on to improve their presentation, add more visual-semantic content, and clarify things like the hierarchy of given code. Just a thought.

**Comment by kanlukasz** [comment] 2019-08-17 10:12
> While back I proposed that the code folding icons be more contextually placed in the editor. I did a quick mockup here:
 
This look is too heavy, too thick lines. In addition, it will mix with the GIT lines in gutter. Bad idea imho.
By the way, what you have shown in the example is more about [Indent Guides ](https://github.com/microsoft/vscode/issues/49342#issuecomment-490048237) match than Code folding

**Comment by jcklpe** [comment] 2019-08-17 22:35
> 
> 
> > While back I proposed that the code folding icons be more contextually placed in the editor. I did a quick mockup here:
> 
> This look is too heavy, too thick lines. In addition, it will mix with the GIT lines in gutter. Bad idea imho.
> By the way, what you have shown in the example is more about [Indent Guides ](https://github.com/microsoft/vscode/issues/49342#issuecomment-490048237) match than Code folding

The mockup is not a final treatment for styling. It's just a copy paste move around of a screenshot that took me less than a minute to get across the idea of nesting. Some of the styling you're seeing, such as the thick yellow line or the pink highlighting isn't even part of the functionality I'm proposing, it's just other extensions that I happen to have installed on my personal version of vscode.

**Comment by jcklpe** [comment] 2019-08-17 23:24
Here's a neatened up version using the current chevron look and using a vanilla factory default styled version of vscode. 

![sketch](https://user-images.githubusercontent.com/9451726/63218209-0cd45d80-c11c-11e9-83cc-cf3864949bb2.jpg)
and with some code folded to show how it would look different. 
![sketch2](https://user-images.githubusercontent.com/9451726/63218210-0e9e2100-c11c-11e9-968a-7a587755265a.jpg)

**Comment by ErikHumphrey** [comment] 2019-08-18 01:53
I don't think that style would solve the problem,if there's HTML that happens to be the same colour as the chevron. It's more of an issue of how it looks when closed.

**Comment by QinBa** [comment] 2019-09-28 07:51
Of course, people have different tastes. And I personally prefer +/- over >. However, is it really so difficult to provide both as options for users to choose? Strange ...

**Comment by jcklpe** [comment] 2019-09-28 20:00
> 
> 
> I don't think that style would solve the problem,if there's HTML that happens to be the same colour as the chevron. It's more of an issue of how it looks when closed.

The colors for the chevron were chosen by me when I made the mockup. I made them match elements of the CSS syntax highlighting for the purposes of visual cohesiveness but if this kind of system were implemented it should obviously have [[theme token APIs]](https://code.visualstudio.com/api/references/theme-color) exposed to make it customizable, similar to how layering of color in brackets it's determined by setting in [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2).


>Of course, people have different tastes. And I personally prefer +/- over >. However, is it really so difficult to provide both as options for users to choose? Strange ...

I agree, I think it would be best to have both. I imagine the main MS devs are not prioritizing giving users the option to choose that due to their interest or prioritization of other features in vscode. This is an open source project so if you want you can always attempt to make those changes yourself too! Maybe an extension would be a good way to start. 

I should probably myself just build an extension to do the layered code folding the way I've suggested but I haven't because I'm not actually that good of a dev (I'm really more a designer who knows enough code to get themselves in trouble and annoy people on stack exchange lol). Maybe someday though!

**Comment by misolori** [comment] 2019-10-07 18:29
Thanks everyone for the feedback. I think this icon issue falls under #79130 which will allow you to configure the icons to your own liking, so **please upvote that issue**. In trying to keep our issue count on a manageable level, I'm going to close this as a duplicate. If you have any additional comments please leave them in that issue. Thanks!

**Closed by misolori** 2019-10-07 18:29 UTC
Labels: icons-product
