### ISSUE TITLE
`editor.formatOnType` corrupt the code in typescript

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#922] opened 2015-12-02 12:59 UTC
![gif](https://cloud.githubusercontent.com/assets/54468/11531393/929e77c2-9937-11e5-8161-d1cdbd1e29a5.gif)

**Comment by dbaeumer** [comment] 2015-12-08 11:28
Can't reproduce on the latest which will use TS 1.7.3. Closing for now. 

@heroboy please check with the next update which is planned for end of this year.

**Closed by dbaeumer** 2015-12-08 11:28 UTC
