### ISSUE TITLE
Source Control stalls 15 seconds or more

### ISSUE THREAD

**Issue by AsrielDewitt** [microsoft/vscode#162748] opened 2022-10-05 15:27 UTC
Type: <b>Performance Issue</b>

Any time the repo updated or anything that related to git. It often stalls for 15 seconds or more. When using git through an external terminal, It suffer no issue, So It must be with Visual studio.

This issue is present with and without extension

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (5.37GB free)|
|Process Argv|--crash-reporter-id 0480dfda-f8ba-4fe2-aabd-6c264ac50844|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	  4668	code main
    0	   118	   972	   extensionHost
    0	   265	 15672	     c:\Users\Hafiz\.vscode\extensions\rust-lang.rust-analyzer-0.3.1229-win32-x64\server\rust-analyzer.exe
    0	    11	 11872	       console-window-host (Windows internal process)
    0	     4	 18256	       "C:\Users\Hafiz\.rustup\toolchains\stable-x86_64-pc-windows-msvc\libexec\rust-analyzer-proc-macro-srv.exe"
    0	   126	  1464	   gpu-process
    0	    28	  7460	   crashpad-handler
    0	   170	 10572	   window (main.rs - hello - Visual Studio Code)
    0	    89	 12324	   issue-reporter
    0	    40	 18296	   utility-network-service
    0	   113	 20376	   shared-process
    0	    77	  6048	     fileWatcher
    0	    73	 22572	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.rs - hello - Visual Studio Code)
|    Folder (hello): 42 files
|      File types: bin(6) lock(3) json(3) timestamp(2) d(2) rmeta(2)
|                  gitignore(1) toml(1) rs(1) TAG(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
vscode-intelephense-client|bme|1.8.2
better-toml|bun|0.3.2
doxdocgen|csc|1.4.0
gdb-debug|Dam|1.0.7
better-cpp-syntax|jef|1.15.23
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
fabric8-analytics|red|0.3.6
java|red|1.11.0
vscode-xml|red|0.21.2022062916
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1229
cmake|twx|0.0.17
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
php-debug|xde|1.28.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vscccc:30566498
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by AsrielDewitt** [comment] 2022-11-19 22:15
> @AsrielDewitt, looking at the git output that you have shared I see several long-running commands:
> 
> ```
> [2022-10-05T15:22:07.477Z] > git check-ignore -v -z --stdin [15878ms]
> [2022-10-05T15:22:07.491Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [15510ms]
> [2022-10-05T15:22:22.408Z] > git cat-file -s 8d69429d2dbe891cdcf0fa6b8a90c26fbbc58752 [15038ms]
> [2022-10-05T15:23:24.358Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [15233ms]
> [2022-10-05T15:25:10.533Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [15128ms]
> ```
> 
> It seems that getting a complete list of all the references consistently takes about 15 seconds. This commands is executed very often as it is part of keeping the "model" up to date. Could you execute `git for-each-ref --sort -committerdate --format "%(refname) %(objectname) %(*objectname)"` in the terminal and see how long does this take? Is this a large repository?


hey, sorry for the late reply.

For your information, the repo is just the rust default new project with 1 file with Hello world

You can do it by just typing `cargo new Hello_world` in a folder


as for executing the command, it doesn't take more than a second.

however, when I was setting up a new project with git turned on

`2022-11-20 06:07:01.744 [info] Validating found git in: C:\Program Files\Git\cmd\git.exe
2022-11-20 06:07:02.292 [info] Using git 2.38.0.windows.1 from C:\Program Files\Git\cmd\git.exe
2022-11-20 06:07:17.924 [info] > git rev-parse --show-toplevel [510ms]
2022-11-20 06:07:33.580 [info] > git rev-parse --git-dir --git-common-dir [390ms]
2022-11-20 06:07:33.587 [info] Log level: Info
2022-11-20 06:07:33.588 [info] Open repository: c:\Users\(USER)\Desktop\Desktop Folder\Rust Program\hello_world2
2022-11-20 06:08:06.000 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [17261ms]
2022-11-20 06:08:06.000 [info] > git remote --verbose [2232ms]
2022-11-20 06:08:06.001 [info] > git status -z -uall [2146ms]
2022-11-20 06:08:06.004 [info] > git rev-parse --show-toplevel [2052ms]
2022-11-20 06:08:06.401 [info] > git config --get commit.template [1808ms]
2022-11-20 06:08:06.703 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [1222ms]
2022-11-20 06:08:06.750 [info] > git check-ignore -v -z --stdin [755ms]
2022-11-20 06:08:22.052 [info] > git rev-parse --show-toplevel [15654ms]
2022-11-20 06:08:22.904 [info] > git rev-parse --show-toplevel [757ms]
2022-11-20 06:08:22.956 [info] > git check-ignore -v -z --stdin [996ms]
2022-11-20 06:08:22.959 [info] > git show --textconv :src/main.rs [714ms]
2022-11-20 06:08:38.064 [info] > git ls-files --stage -- C:\Users\(USER)\Desktop\Desktop Folder\Rust Program\hello_world2\src\main.rs [15493ms]
2022-11-20 06:12:50.217 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [1133ms]
2022-11-20 06:12:50.601 [info] > git remote --verbose [1476ms]
2022-11-20 06:12:50.604 [info] > git status -z -uall [1399ms]
2022-11-20 06:12:50.605 [info] > git config --get commit.template [1088ms]
2022-11-20 06:13:05.671 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [15706ms]
2022-11-20 06:13:11.796 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [1073ms]
2022-11-20 06:13:12.212 [info] > git status -z -uall [1378ms]
2022-11-20 06:13:12.212 [info] > git remote --verbose [1451ms]
2022-11-20 06:13:12.260 [info] > git config --get commit.template [1111ms]
2022-11-20 06:13:27.321 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [15525ms]`

**Comment by lszomoru** [comment] 2022-11-22 13:24
@AsrielDewitt, thank you very much for getting back to me on this. Something strange is happening here as the output that you have shared, again indicates that there are several `git.exe` commands that take seconds to execute. Given that this is a simple repository, it's not clear to me what could cause this. Is there a chance that the Antivirus software interferes with git, or that the system is under IO pressure (ex: high CPU, high disk usage, etc.)?

**Comment by AsrielDewitt** [comment] 2022-11-22 13:56
> @AsrielDewitt, thank you very much for getting back to me on this. Something strange is happening here as the output that you have shared, again indicates that there are several `git.exe` commands that take seconds to execute. Given that this is a simple repository, it's not clear to me what could cause this. Is there a chance that the Antivirus software interferes with git, or that the system is under IO pressure (ex: high CPU, high disk usage, etc.)?

Sorry, email notif is a bit slow

And no, not really. Both times, I used a laptop that has a Ryzen 5 4600h and 16GB of DDR4 ram at 3200mhz speed

Both times I used it on it's m.2 SSD

And both times, the only thing I had was youtube on MS Edge and Discord with some chats

**Comment by PixelDuck** [comment] 2022-12-05 12:54
Samer for me on a large project 22s
```
2022-12-05 13:52:09.824 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22716ms]
```

**Comment by lszomoru** [comment] 2022-12-06 13:44
The `git for-each-ref` that is being executed is not related to the "Tags" window but it is one of the git commands that is being executed to keep the data model up-to-date. In the upcoming release of VS Code we have made some changes so that some of the core operations in the Source Control view (ex: stage, un-stage, discard changes, commit) optimistically update the state of the view **before** the data model is updated. That is the first steps in our effort to make the Source Control view snappier with more improvements on the way.

**Comment by lszomoru** [comment] 2023-05-17 10:46
Since this issue was related to the execution of `git for-each-ref` I will go ahead and close it as that has been resolved. @BryanHunt, if you are able to consistently reproduce the issue please file a separate issue so that I can investigate it further. Thanks!

**Closed by lszomoru** 2023-05-17 10:46 UTC
Labels: feature-request, git, perf
