### ISSUE TITLE
Always indents HTMLs with tabs

### ISSUE THREAD

**Issue by kutynko** [Microsoft/vscode#13725] opened 2016-10-14 05:26 UTC
- VSCode Version: 1.6.1
- OS Version: Win 10 x64

Steps to Reproduce:

1. add workspace settings.json 
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
2. open *.html file formatted with spaces
3. press alt+shift+f to format document -> spaces are converted to tabs which is wrong

**Comment by craxal** [comment] 2016-10-14 21:11
:+1: Also encountering this issue.

**Comment by aeschli** [comment] 2016-10-16 19:54
duplicate of #13563

**Closed by aeschli** 2016-10-16 19:54 UTC
