### ISSUE TITLE
Can't create terminal with a pseudo tty in the Web

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#160914] opened 2022-09-14 16:31 UTC
Here is my code snippet

```ts
		const ptyWriteEmitter = new vscode.EventEmitter<string>();
		const pty = {
			onDidWrite: this.ptyWriteEmitter.event,
			open: () => {
				this.ptyWriteEmitter.fire(`\x1b[31m${name}\x1b[0m\r\n\r\n`);
			},
			close: () => {
			},
			handleInput: (data: string) => {
				// Echo the data
				if (data === '\r') {
					data = '\n';
				}
				if (data.charCodeAt(0) === 127) {
					// Delete last character
					this.ptyWriteEmitter.fire('\x1b[D\x1b[P');
					this.inputBuffer.splice(this.inputBuffer.length - 1, 1);
				} else {
					this.ptyWriteEmitter.fire(data === '\n' ? '\r\n' : data);
					this.inputBuffer.push(data);
				}
				if (data === '\n' && this.lineAvailable !== undefined) {
					this.lineAvailable();
				}
			}
		};

		const terminal = window.createTerminal({ name: 'Python Terminal', pty: pty  });
		terminal.show();
```

Trying to run this creates:

```
ERR A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`: Error: A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`
    at Ui._open (https://main.vscode-cdn.net/insider/b3546b4bb5aff5254ef857cfd68a3da8534c068f/out/vs/workbench/workbench.web.main.js:3097:46503)
    at Ui.setVisible (https://main.vscode-cdn.net/insider/b3546b4bb5aff5254ef857cfd68a3da8534c068f/out/vs/workbench/workbench.web.main.js:3099:2561)
    at h.showPanel (https://main.vscode-cdn.net/insider/b3546b4bb5aff5254ef857cfd68a3da8534c068f/out/vs/workbench/workbench.web.main.js:3097:22123)
```

**Comment by Tyriar** [comment] 2022-09-15 15:54
I was using https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample

The only changes were these in package.json:

```
"vscode": "^1.71.0",
"browser": "./out/extension.js",
```

**Comment by dbaeumer** [comment] 2022-09-16 10:22
I can still reproduce this in my code. I ran out of source to see what might cause the problem and here is a detailed stack trace:

```
ERR A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`: Error: A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`
    at TerminalInstance._open (http://localhost:8080/static/sources/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:654:23)
    at TerminalInstance.setVisible (http://localhost:8080/static/sources/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1001:22)
    at TerminalGroupService.showPanel (http://localhost:8080/static/sources/out/vs/workbench/contrib/terminal/browser/terminalGroupService.js:150:30)
```

Might be some timing issue

**Comment by dbaeumer** [comment] 2022-09-16 11:07
More digging. Here are my findings:

- I do open the terminal from a debug adapter which brings the debugger viewlet to front right after I created the terminal
- if I wrap my code into a `setTimeout` everything works fine
```ts
		setTimeout(() => {
			this.terminal = window.createTerminal({ name: 'Python Terminal', pty: pty });
			this.terminal.show();
		}, 2000);
```

**Comment by dbaeumer** [comment] 2022-09-21 09:05
@Tyriar any tip or fix for this. I improved the performance on my end and a 2 sec delay is now very bad. My Python execution in the Web is now < 500 ms.

**Comment by dbaeumer** [comment] 2022-09-26 08:46
I need to reopen this. I tested it on todays insider and I still get

```
ERR A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`: Error: A container element needs to be set with `attachToElement` and be part of the DOM before calling `_open`
    at Ui._open (https://main.vscode-cdn.net/insider/eeaee503e902cd9cd202f071b8b635e923e24366/out/vs/workbench/workbench.web.main.js:3121:47569)
    at Ui.setVisible (https://main.vscode-cdn.net/insider/eeaee503e902cd9cd202f071b8b635e923e24366/out/vs/workbench/workbench.web.main.js:3123:2570)
    at h.showPanel (https://main.vscode-cdn.net/insider/eeaee503e902cd9cd202f071b8b635e923e24366/out/vs/workbench/workbench.web.main.js:3121:22192)
    at async a.$show (https://main.vscode-cdn.net/insider/eeaee503e902cd9cd202f071b8b635e923e24366/out/vs/workbench/workbench.web.main.js:2144:60049)
```

**Comment by dbaeumer** [comment] 2022-09-26 08:46
Build I used is: 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1931590/192233565-7ad3b79a-a904-48a2-9fcb-1fa3bde65ac9.png">

**Comment by dbaeumer** [comment] 2022-09-26 08:47
I will compile steps today on how to reproduce this.

**Comment by dbaeumer** [comment] 2022-09-26 13:11
Steps to reproduce:

- clone https://github.com/microsoft/vscode-python-web-wasm.git
- cd vscode-python-web-wasm
- git co dbaeumer/noTimeout
- npm install
- npm run compile
- npm run esbuild
- open VS Code
- run `npm run serve` as a task or in the terminal
- run `npm run tunnel` as a task or in the terminal
- click on the link in the tunnel terminal and press continue
- open a browser on `https://insiders.vscode.dev/github/dbaeumer/python-sample?vscode-coi=`
- Run command `Install Web extension`
- Use the link from the tunnel
- open developer tools
- open app.py in the browser window
- From the play menu in the editor run `Run Python File in WASM`

Observe: you get the above exception and the terminal is not showing the output

Run the action again

Observe: the terminal reveals correctly and shows the output

**Comment by Tyriar** [comment] 2022-09-26 18:56
Can reproduce with those steps, the only thing missing was enabling workspace trust and reloading after installing the web extension

**Comment by Tyriar** [comment] 2022-09-26 19:01
Debugging this section:

https://github.com/microsoft/vscode/blob/1a76ad9c8b03cd7d5a38e03d94facfd989471619/src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts#L179-L187

It's visible before `await instance.focusWhenReady(true);` so it doesn't do the extra open view, and not visible after it because the debug console steals the opened view.

**Comment by Tyriar** [comment] 2022-09-26 19:10
Even if this issue was fixed such that `instance.setVisible(true)` did not throw (eg. make an optionally synchronous version of `instance.focusWhenReady()` or just try `instance.focus()`), it would still set visible and then immediately show the debug console. So if you wanted to show the terminal, you would need to call it after the debug console shows (eg. via timeout as you have).

I don't think this is an issue that needs to be fixed in the terminal, but rather you should either prevent whatever is showing the debug console as it happens some time after the terminal is created, or move the `terminal.show()` call to after the debug console shows.

**Comment by dbaeumer** [comment] 2022-09-27 08:41
IMO there are two different things:

- the fact that the terminal is not in front because the debug terminal comes to front. I do agree that this is something I should address
- the fact that the terminal seems broken (e.g. it doesn't render the output for the first created terminal). This I agrue is a bug in the terminal. IMO the terminal should function correctly after a create even if I don't call show. So if a user later on clicks on the terminal the output is shown correctly.

**Comment by Tyriar** [comment] 2022-09-27 15:10
@dbaeumer 👍 the second issue should be fixed by https://github.com/microsoft/vscode/pull/161989, it won't fix your problem though

**Comment by dbaeumer** [comment] 2022-09-27 15:19
@Tyriar to understand it correctly. This will ensure that the terminal is functional after `createTerminal`. I can then ensure that I bring the terminal to front (`terminal.show()`) after the debugger is initialized.

**Comment by Tyriar** [comment] 2022-09-27 15:56
@dbaeumer yeah, removing that await should ensure the view is visible so the element will be there to attach which means no exception that ruins the state.

**Closed** 2022-09-27 23:24 UTC
Labels: bug, api, terminal
