### ISSUE TITLE
In Go To File... allow repeat of previous search

### ISSUE THREAD

**Issue by joeytwiddle** [microsoft/vscode#90114] opened 2020-02-06 03:56 UTC
An example use case:

- I hit <kbd>Cmd-P</kbd> and search for "`package.json`"

- Because I'm in a monorepo, there are many files with that name. I select the one I think I wanted.

- Oops I chose the wrong one! So I hit <kbd>Cmd-P</kbd> again, to look for the right one.

- **Problem:** I have to type "`package.json`" again.

- **Solution:** I should be able to press something to get the previous search text "`package.json`" back in the text box.

In the **Find In Files** search box, we can cycle previous search terms with <kbd>Up</kbd> and <kbd>Down</kbd> keys, but we cannot use those in **Go To File...** because they are already used to cycle through the visible list of files.

A keystroke like <kbd>Cmd-Up</kbd> would be fine for me.

Or any of the keys <kbd>Cmd-K / O / L</kbd> would be conveniently placed on US keyboards. They currently trigger completely separate features, but I think it might be reasonable to give them a different behaviour within this context. Complete keystroke: <kbd>Cmd-P Cmd-K</kbd>

(Alternatively, the <kbd>^</kbd> key could do this, instead of being entered as a literal character. I think that is rarely used to search filenames. Or the <kbd>!</kbd> key, which nods to `bash` history search, although it seems that is already doing something, but I'm not sure what exactly.)

**Comment by bpasero** [comment] 2020-02-06 06:09
Configurable in settings:

![image](https://user-images.githubusercontent.com/900690/73910435-a13fa180-48af-11ea-9826-1d9a8c3f41ea.png)

And duplicate of https://github.com/microsoft/vscode/issues/18232

**Closed** 2020-02-06 06:10 UTC
Labels: *duplicate
