### ISSUE TITLE
Inconsistent marketplace search results with pre-release extensions in VS Code Insiders

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode#143139] opened 2022-02-15 21:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider (50089c3f92c17584a4aca179f51f220b56c22020)
- OS Version: macOS 12.1

Steps to Reproduce:

1. Find an extension which publishes pre-releases and is not currently installed (I will be using `github.vscode-pull-request-github` for demo purposes)
2. See the correct behavior of a searched extension by going to the Extensions tab and searching for  `GitHub Pull Requests and Issues` and selecting the first result. Observe the version displayed there (for me it's `v0.37.2022021515`)
3. See the incorrect behavior by entering `@id:github.vscode-pull-request-github` in the search box, and again clicking the first (and now only) result (make sure the tab from the previous step is closed, otherwise it will not be reloaded). Now you can see that instead of getting the pre-release version, we get the latest stable version, which for me is `v0.36.1`.

**Comment by yume-chan** [comment] 2022-02-20 05:41
Duplicate of #143480

**Closed** 2022-02-21 14:11 UTC
Labels: *duplicate
