### ISSUE TITLE
Syntax highlighting broken for embedded languages other than JS in html script tags

### ISSUE THREAD

**Issue by agilbert201** [Microsoft/vscode#26037] opened 2017-05-05 14:00 UTC
- VSCode Version: April 2017 1.12
- OS Version: Windows

Steps to Reproduce:

1. Create <script type="text/html"> tag with inline html
2. Syntax highlighting defaults to Javascript?

Note can remove type="text/html" attribute and sorta of okay but this should be needed.

**Comment by egamma** [comment] 2017-05-05 15:30
duplicate of #25920

**Closed by egamma** 2017-05-05 15:30 UTC
Labels: duplicate
