### ISSUE TITLE
Folder picker adds back characters

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#73339] opened 2019-05-06 10:08 UTC
Issue Type: <b>Bug</b>

In the recording I hold down Backspace and then release it. After releasing a few characters are added back to the input field which is unexpected.

![May-06-2019 12-04-38](https://user-images.githubusercontent.com/9205389/57219195-9772d000-6ff7-11e9-9b36-5ce05fb646a9.gif)

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|-psn_0_16174956|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
vscode-eslint|dba|1.8.2
ghlink|dt|1.1.0
remotehub|eam|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
git-project-manager|fel|1.7.1
vscode-pull-request-github-insiders|Git|1.114.0
rest-client|hum|0.21.2
solidity|Jua|0.0.55
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.13.1
remote-containers|ms-|0.48.0
remote-ssh|ms-|0.34.0
remote-ssh-edit|ms-|0.34.0
remote-ssh-explorer|ms-|0.34.0
remote-wsl|ms-|0.32.0
vscode-remote-extensionpack|ms-|0.12.0
azure-account|ms-|0.8.2
azurecli|ms-|0.4.5
cpptools|ms-|0.22.2-insiders
github-issues-prs|ms-|0.9.1
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.23.0
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.12.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.1.5

</details>

**Comment by alexr00** [comment] 2019-05-06 11:09
Duplicate of https://github.com/Microsoft/vscode-remote-release/issues/4

**Closed** 2019-05-06 11:09 UTC
