### ISSUE TITLE
Option to save custom editor without reopenning

### ISSUE THREAD

**Issue by yuyichao** [microsoft/vscode#141810] opened 2022-01-29 22:16 UTC
Currently, when a custom document is saved, both the document and the view are closed for the old uri and reopened for the new one. This is quite inefficient (unnecessary IO and unnecessary re-rendering of the view) and also causes the state in the view, as well as the undo history to be lost. It'll be nice if there's an opt-in way to support save-as on the custom editor side and to have the document changes it's uri after save-as.

**Comment by mjbvz** [comment] 2022-12-05 17:42
Duplicate of #86146

**Closed by mjbvz** 2022-12-05 17:42 UTC
Labels: custom-editors
