### ISSUE TITLE
SCM: decorations are getting lost at random

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81467] opened 2019-09-26 09:00 UTC
I am seeing this ever since we added decorations to the tree and so far I seem to be the only one. Decorations randomly disappear from my SCM tree (using Web) and I have no clue why. We gotta get to the bottom of this (expecting a D(eleted) decoration for the removed ones):

![image](https://user-images.githubusercontent.com/900690/65674420-ce9c5900-e04c-11e9-82e7-e4627ddc2b0d.png)

CSS shows that a decoration class is applied:

![image](https://user-images.githubusercontent.com/900690/65674454-df4ccf00-e04c-11e9-81f9-e754fd73994c.png)

As I said, i doubt this is a recent regressions, I have this for at least 1 year I would say.

**Comment by bpasero** [comment] 2019-09-26 09:01
Proof, after window reload:

![image](https://user-images.githubusercontent.com/900690/65674518-05726f00-e04d-11e9-9ef2-de58a8a76185.png)

**Comment by bpasero** [comment] 2019-09-26 09:02
My settings:

```json
{
    // Editor
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.fontLigatures": true,
    "editor.wordWrap": "off",
    "editor.codeLens": true,
    "editor.dragAndDrop": false,
    "editor.folding": false,
    "editor.renderIndentGuides": false,
    "editor.minimap.enabled": false,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.mouseWheelScrollSensitivity": 6,
    "diffEditor.renderIndicators": false,
    "editor.smoothScrolling": false,
    "[json]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false
    },
    "[html]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false
    },
    "workbench.colorCustomizations": {
        "focusBorder": "#f3f3f3",
        "inputOption.activeBackground": "#007acc1f",
        "editorLineNumber.activeForeground": "#2b91af",
        "list.activeSelectionBackground": "#3399FF"
    },
    "workbench.editor.showTabs": false,
    "workbench.editor.enablePreview": false,
    "workbench.tips.enabled": false,
    "window.zoomLevel": 1,
    "workbench.startupEditor": "newUntitledFile",
    // Terminal
    "terminal.integrated.fontSize": 13,
    "terminal.integrated.lineHeight": 1.4,
    // Misc
    "git.confirmSync": false,
    "debug.inlineValues": true,
    "debug.internalConsoleOptions": "neverOpen",
    "extensions.autoUpdate": true,
    "git.enableSmartCommit": true,
    "files.autoSave": "afterDelay",
    "explorer.openEditors.visible": 0,
    "explorer.confirmDragAndDrop": false,
    "problems.decorations.enabled": true,
    "editor.renderWhitespace": "none",
    "git.autofetch": true,
    "workbench.activityBar.visible": true,
    "git.showInlineOpenFileAction": false,
    "diffEditor.ignoreTrimWhitespace": true,
    "workbench.iconTheme": null,
    "explorer.decorations.colors": false,
    "window.titleBarStyle": "custom",
    "html.format.wrapLineLength": 20,
    "html.format.wrapAttributes": "force-aligned",
    "workbench.settings.editor": "json",
    "window.restoreFullscreen": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "extensions.ignoreRecommendations": true,
    "workbench.colorTheme": "Default Light+",
    "editor.snippetSuggestions": "none",
    "breadcrumbs.enabled": false,
    "git.inputValidationSubjectLength": 500,
    "workbench.tree.renderIndentGuides": "none",
    "gulp.autoDetect": "off",
    "merge-conflict.codeLens.enabled": true
}
```

**Comment by joaomoreno** [comment] 2019-09-26 09:22
@bpasero Have you seen this on non-web?

**Comment by bpasero** [comment] 2019-09-26 09:28
@joaomoreno yes, from my memories I often had this on desktop too. How could web vs desktop play a role here? The only difference I can think of (besides browser engines) is, that the filesystem is a remote one.

**Comment by joaomoreno** [comment] 2019-09-26 10:06
Funny how in your example what happened was every decoration other than `M` disappeared. Did you notice that? @jrieken Does that maybe ring any bells on how this could occur? I'm betting this would happen as well in the Explorer decorations, since SCM just reuses the same widget.

**Comment by jrieken** [comment] 2019-09-30 12:57
Yeah, let's dig into this. Looking at @bpasero's screen capture it seems that models and providers work correctly and that this is a rendering issue (making this more weird). The capture only shows the title, not the icon (which uses `::after` pseudo class) but I assume that's there... 

This might be an issue in the service when it cleans up CSS rules. Things like "M", "U, 9+" are CSS rules and for each new combination a new rule is created. Every once in a while the service checks for unused rules which it then removes. If rules are removed illegally then this would happen. I will investigate.

**Comment by jrieken** [comment] 2019-10-01 16:16
Reviewed the code and found a condition under which css rules are illegally removed. I wasn't able to reproduce/verify (read lazy) but I am optimistically enough to close this 🤞

**Comment by bpasero** [comment] 2019-10-04 09:51
Will reopen if I see this again, for now optimistically verifying.

**Comment by jrieken** [comment] 2019-10-28 13:01
This has been seen again...

**Comment by jrieken** [comment] 2019-10-28 14:24
Next try... The automatic cleanup of styles, which has been a headache, is no gone and decoration needs to disposed, e.g. the one user of decorations must do this... Again, optimistically closing

**Comment by connor4312** [comment] 2019-10-31 18:56
I tried for a while and couldn't repro any issues. Marking as verified, for now.

**Comment by jrieken** [comment] 2019-11-08 16:25
And re-opening again... Turns out that this wasn't the automagic clean-up, but the [`removeCSSRulesContainingSelector`](https://github.com/microsoft/vscode/blob/dca100feaa8f3aa5899abdef0840c5c2b0f3228f/src/vs/base/browser/dom.ts#L818)-util we have - or my lack of understanding how it should work. 
Adding @alexandrudima to clarify because I believe you wrote that util.

Backstory: To add file decorations like `U`, `2,M`  I generate dynamic css rules using this pattern: `monaco-decorations-style-1`, `monaco-decorations-style-2` ... `monaco-decorations-style-10` and so on. Now, the `removeCSSRulesContainingSelector` defines containing selector has [`String.startsWith`](https://github.com/microsoft/vscode/blob/dca100feaa8f3aa5899abdef0840c5c2b0f3228f/src/vs/base/browser/dom.ts#L827) so when removing `monaco-decorations-style-1` it also removes `monaco-decorations-style-10` etc. With decorations get lost, without our internal data structures catching up which then forever refer to non-existent css rules.

I would opt to make this a candidate despite this not being new. That's because the changes I made last milestone made this more likely to happen and because only refresh gets you out of this.

**Comment by joaomoreno** [comment] 2019-11-08 16:31
![the witch is dead](http://giphygifs.s3.amazonaws.com/media/14fqKGzBNIPzji/giphy.gif)

**Comment by alexandrudima** [comment] 2019-11-08 16:44
@jrieken Yes, `removeCSSRulesContainingSelector` is doing a prefix search on the selector. We cannot change that method, as it would break the original users of it, i.e. it is intentional... Maybe you can left pad your numbers with `0`s or add another function to delete exact selector matches ...

**Comment by jrieken** [comment] 2019-11-08 16:55
Thanks - I leave the function untouched, maybe adding a jsdoc-warning ;-) Left padding will work - in fact I already have a key for the "outer" type which I could use to make them not overlap.

**Closed** 2019-11-09 13:51 UTC
Labels: bug, candidate, file-decorations

**Comment by jrieken** [comment] 2019-11-11 11:06
To verify: 

* have 2 untracked files without errors
* have 1 modified file without errors
* have 2 modified file *with* errors
* select the SCM viewlet, make sure it shows decoration `U`, `U`, `M`, `1,M`
* reload and make sure no decorations are missing
