### ISSUE TITLE
Remove folder from 'workspace' shouldn't run on folder-only-workspace

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37300] opened 2017-10-31 14:26 UTC
re #35221

* open just a folder
* run the remove folder from workspace command
* 🐛 the workbench is now empty

**Comment by bpasero** [comment] 2017-10-31 14:41
@jrieken yeah for a user command we should probably revisit it. But how about the `removeWorkspaceFolder` API, which would do the same currently?

**Comment by jrieken** [comment] 2017-10-31 14:43
>  But how about the removeWorkspaceFolder extension API, which would do the same currently?

😱

**Comment by bpasero** [comment] 2017-11-01 10:27
I would actually argue that the issue here is that we do a window reload, whereas the fact that the workspace folder is removed is fine. If the experience was to stay in the window (with all the UI state) and the explorer showing up empty I think we are fine.

**Comment by jrieken** [comment] 2017-11-01 10:51
Not sure... It does blur the lines between the folder and workspace case

**Comment by bpasero** [comment] 2017-11-01 11:04
Yeah agreed. Since this is a relatively new thing, I would want to hear user feedback on this before jumping in and changing it. If people get confused we should not show the action in the F1 list at all unless you are in workspace mode.

**Comment by bpasero** [comment] 2018-01-23 10:53
No complaints so far, closing as designed. What I will change though is that the window does not reload, you simply enter a workspace that has no folders.

**Closed** 2018-01-23 10:53 UTC
Labels: multi-root, under-discussion
