### ISSUE TITLE
Shortcut open menu bar and conflict with shortcut command (only with title bar style: custom)

### ISSUE THREAD

**Issue by kirit0s** [Microsoft/vscode#62398] opened 2018-11-01 17:22 UTC
- VSCode Version: 1.28.2 (user setup), also 1.29.0-insider (user setup) with zero extension
- OS Version: Windows 10 x64 1803

Steps to Reproduce: press `shift + alt + t`.
Actual: open menu bar.
Expecting: don't open menu bar (as it was in native title bar style).

Does this issue occur when all extensions are disabled?: Yes

For example: I have custom keyboard shortcut `shift+alt+r shift+alt+t` (equal `shift + alt + r + t`), and when I press them, vscode open menu bar on Terminal tab and conflict with shortcut command (for example, if I want to open the `run task` command with this shortcut, when the menu bar is open, the task list is closed). This because `alt + t` is shortcut for open Terminal tab in menu bar.

This problem in all shortcuts which use `shift+alt+[letter1] shift + alt + [letter2]`, where `letter2` is one of:
- **F** (file),
- **E** (edit),
- **S** (selection),
- **V** (view),
- **G** (go),
- **D** (debug),
- **T** (terminal),
- **H** (help).

`Ctrl + alt` **work** fine. If I change `title bar style` to `native`, `shift + alt` shortcuts **work** fine. If I change keyboard language from `EN` to `RU`, shortcuts also **work** fine.

**Important**: that problem only in shortcuts, which begin with `shift + alt` and use 2 letters after. But anyway, `shift + alt + t (any letters in the list above)` should't open menu bar.

p. s. `shift + alt + f` don't open menu bar, because vscode have default `shift + alt + f` shortcut. But it still feels like the menu bar opens and closes, just very quickly.

**Comment by sbatten** [comment] 2018-11-01 18:31
duplicate of https://github.com/Microsoft/vscode/issues/61644

**Closed by sbatten** 2018-11-01 18:31 UTC
Labels: insiders
