### ISSUE TITLE
Make hover scrollable when large contents are displayed (overflow case)

### ISSUE THREAD

**Issue by VijiVgsN** [Microsoft/vscode#7246] opened 2016-06-06 10:35 UTC
- VSCode Version:1.1.1
- OS Version: Microsoft windows 7-6.1.7601
  -Node -v4.4.5-x86
  Steps to Reproduce:
1. Hover on the object
2. the list of the object hover popup displayed top position only.
   3.I couldn't see the full list, even the scroll feature also not in the hover popup.
   ![actuallistwithissue](https://cloud.githubusercontent.com/assets/19775816/15819526/57f94cc0-2c01-11e6-927f-748b2ed17431.png)
   ![issueonfulllist](https://cloud.githubusercontent.com/assets/19775816/15819532/5d387eb8-2c01-11e6-8b9f-2989d1bb925f.png)

**Comment by DanTup** [comment] 2016-08-01 17:37
Possibly related to #2378? Also annoying me; some of Darts docs are huge!

![hover](https://cloud.githubusercontent.com/assets/1078012/17303033/e27eea6c-5816-11e6-9b2e-be3dd532c372.png)

**Comment by VijiVgsN** [comment] 2016-08-01 18:36
Can u try this by fix one medium size with scrolling option? is there any problem on using this approach?

**Comment by DanTup** [comment] 2016-08-01 19:08
I'm not sure I understand? Issue #2378 suggests scrolling should be added; I think this case is effectively a duplicate of that?

**Comment by VijiVgsN** [comment] 2016-08-02 09:18
Yes...

**Comment by alexandrudima** [comment] 2017-03-02 10:47
Do we want to make the hover scrollable @joaomoreno @jrieken

**Comment by jrieken** [comment] 2017-03-02 11:37
pretty sure @joaomoreno added that

**Comment by joaomoreno** [comment] 2017-03-02 13:29
It is!

**Closed by joaomoreno** 2017-03-02 13:29 UTC
Labels: editor-contrib, feature-request
