### ISSUE TITLE
Github signing issue - VSCode is not registered as vscode protocol handler

### ISSUE THREAD

**Issue by anddam** [microsoft/vscode#147915] opened 2022-04-22 10:59 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.Issue Type: <b>Bug</b>

1. call `Settings Sync: Turn On…` command, then  click the "Sign In & Turn On" button, then select "Sign in with Github".

A new tab opens in Chrome (that is already running) and a dialog titled "Open xdg-open?" says "https://vscode.dev wants to open this application."

The tab URI is:

    https://github.com/login/oauth/authorize?client_id=01ab8ac9400d4e429b23&redirect_uri=https://vscode.dev/redirect&scope=user:email&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D8e960733-cddd-4fcd-bf5d-de2d623fe643%2526windowId%253D1

2. click "Open xdg-open" at the Chrome dialog. This opens Firefox that for whatever reasons xdg-mime thinks is the appropriate handler for:
    vscode://vscode.github-authentication/did-authenticate?nonce=8e960733-cddd-4fcd-bf5d-de2d623fe643&windowId=1&code=8f80d5a0164bd090fed7&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D8e960733-cddd-4fcd-bf5d-de2d623fe643%2526windowId%253D1 

Firefox (pretty obviously) displays:

    The address wasn’t understood

    Firefox doesn’t know how to open this address, because one of the following protocols (vscode) isn’t associated with any program or is not allowed in this context.

      * You might need to install other software to open this address.
      
      
What protocol should VSCode be registered with in order for github authentication to work?

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.15.34_1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics (4 x 2031)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|13.66GB (3.36GB free)|
|Process Argv|--enable-proposed-api ms-python.python --enable-proposed-api ms-toolsai.jupyter --enable-proposed-api ms-vscode-remote.remote-ssh --enable-proposed-api ms-vsliveshare.vsliveshare --unity-launch --crash-reporter-id 43713bcb-185c-42f6-88f6-e9221378ebc3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ng-template|Ang|13.3.1
troff|ban|1.0.22
vscode-astyle|chi|0.9.0
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.5.0
vscode-graphviz|joa|0.0.6
xml-format|mik|1.1.2
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.10.0
hexeditor|ms-|1.9.6
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5527
vs-sequential-number|nep|1.1.0
java|red|1.5.0
alive|rhe|0.2.7
vscode-text-tables|Rom|0.1.5
code-settings-sync|Sha|3.4.3
rewrap|stk|1.16.3
sass-indented|syl|1.8.19
vscode-icons|vsc|11.11.0
org-mode|vsc|1.0.0
vscode-aspell|zap|0.1.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by TylerLeonhardt** [comment] 2022-04-22 14:03
@anddam can you tell me how you installed VS Code? Was it a package manager or did you download the standalone zip?

**Comment by anddam** [comment] 2022-04-22 16:38
> @anddam can you tell me how you installed VS Code? Was it a package manager or did you download the standalone zip?

I surely can.

I grab the x86_64 tarball  from [vscode alternative downloads page](https://code.visualstudio.com/#alt-downloads) and proceed to `tar zxvpf` it into ~/Applications.

I have a desktop entry calling

    Exec=/usr/bin/env GTK_IM_MODULE=xim /home/anddam/Applications/VSCode-linux-x64/bin/code --enable-proposed-api ms-python.python --enable-proposed-api ms-toolsai.jupyter --enable-proposed-api ms-vscode-remote.remote-ssh --enable-proposed-api ms-vsliveshare.vsliveshare --unity-launch %F

this is a legacy from my previous OSS usage and not entirely sure if the explicit API enabling are required with MS build.
Notice that I tried replaced the whole shebang with a simple `/home/anddam/Applications/VSCode-linux-x64/bin/code --disable-extensions` as required in the new issue placeholder, that resulted in no changes.

The fun bit is that I switched from OSS build to MS just to be able to use Settings Sync rather than a third party plugin, but syncing has not been working for weeks on my side. I had a setup issue with the keychain, that I was only able to address this morning, only to figure that I cannot sign in with github anyway.

IIRC there used to be an option in which github provided a token and that was manually inserted in vscode via a command, I cannot find that option since github only tries to call an external program due to the `vscode://` protocol.

**Comment by TylerLeonhardt** [comment] 2022-04-23 01:03
Ah yes.. the problem with the tar is that it doesn't setup our `vscode://` handler. This is a duplicate of https://github.com/microsoft/vscode/issues/146408#issuecomment-1095273737 (that comment also has context)

To combat this on auth side, we have fallback logic when you have trouble logging in... it will suggest using a different way to log in that doesn't use `vscode://`. That's in VS Code Insiders and will be in the next stable version.

**Closed** 2022-04-23 01:03 UTC
Labels: *duplicate
