### ISSUE TITLE
css @property breaking styling in html

### ISSUE THREAD

**Issue by elkolorado** [microsoft/vscode#210891] opened 2024-04-22 09:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Windows 10 Pro 22H2 19045.3516 1000.19052.1000.0

Steps to Reproduce:

```html
<style>
    @property --num {
        syntax: "<integer>";
        initial-value: 0;
        inherits: false;
    }
    ...
</style>

<div id="broken"></div>
```
![image](https://github.com/microsoft/vscode/assets/25396329/411ddccc-1e95-49be-89fc-0ed4fae8ed11)

**Comment by alexr00** [comment] 2024-04-22 12:50
Duplicate of upstream issue: https://github.com/microsoft/vscode-css/issues/9

**Closed by alexr00** 2024-04-22 12:50 UTC
