### ISSUE TITLE
Commenting html/xml doesn't escape previously commented characters

### ISSUE THREAD

**Issue by adrianviegas** [Microsoft/vscode#43774] opened 2018-02-15 18:28 UTC
### Issue Type
Bug

### Description

If I comment an a piece of html code, which has a comment, it doesn't escape the existing comment.
![vscode bug](https://imgur.com/u2yPZiV.gif)

**Expected Output:**
This is how it works in intellij
![intellij solution](https://imgur.com/nvfqdHD.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.90GB (3.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by aeschli** [comment] 2018-02-16 09:24
duplicate of https://github.com/Microsoft/vscode/issues/31087

**Closed by aeschli** 2018-02-16 09:24 UTC
Labels: new release

**Comment by adrianviegas** [comment] 2018-02-17 09:27
From #31087 
> This is a known but accepted limitation of our comment feature which does not escape anything inside the comment. The user has to do that.

Any reason as to why this is?

**Comment by aeschli** [comment] 2018-02-19 08:42
The idea is to keep the functionality simple and predictable and to avoid making changes inside the code that the user might not want that way (there are always several ways of escaping).
