### ISSUE TITLE
Support right click context menus in custom editors and web views.

### ISSUE THREAD

**Issue by lforst** [microsoft/vscode#121581] opened 2021-04-18 10:22 UTC
I am working on integrating a visual editor in vscode and would like to use the menu contribution `editor/context` in order to add native right click context menus. Sadly these context menus don't seem to work in custom editors and/or web views.

My request is to add a contribution point for right click context menus in custom editors and web views.

**Comment by mjbvz** [comment] 2021-04-20 01:39
Duplicate of #54285

**Closed by mjbvz** 2021-04-20 01:39 UTC
