### ISSUE TITLE
Auto-unindent for Ruby 'in' affects 'include'

### ISSUE THREAD

**Issue by awfulcooking** [microsoft/vscode#148637] opened 2022-05-03 14:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Debian Bullseye

Steps to Reproduce:

1. Type:
  ```ruby
  class Banana
    include Sweet
    include Tasty
  end
  ```
2. See:
  ```ruby
  class Banana
  include Sweet
  include Tasty
  end
  ```

`in` is likely unindented to support case statements with pattern matching in Ruby 3:
```ruby
case foo
in [:bar, ^qux]
  ...
in [:other, *]
end
```

But it disrupts flow when typing 'include'.

It looks similar to #83309, but I think it'll affect users much more frequently.

A fix might be to trigger on "in " instead of "in" - which wasn't possible for #83309.

**Comment by aiday-mar** [comment] 2024-03-27 17:49
duplicate of https://github.com/microsoft/vscode/issues/198350 and fixed

**Closed by aiday-mar** 2024-03-27 17:49 UTC
Labels: polish, editor-autoindent, ruby
