### ISSUE TITLE
Switching branches results in spurious TypeScript errors

### ISSUE THREAD

**Issue by danvk** [microsoft/vscode#7790] opened 2016-06-16 19:35 UTC
- VSCode Version: 1.2.1
- OS Version: 10.11.4

Steps to Reproduce:
1. Open a few files in a git TypeScript project
2. Modify two files (`a.ts` and `b.ts`) that depend on one another and commit them.
3. Switch to a different branch and reload all the files. Make sure only `a.ts` is visible.
4. Switch back to the first branch. `a.ts` reports errors.

Opening `b.ts`, either in a tab or split, will make the errors in `a.ts` go away. Even if you don't save. Running `tsc` from the command line never reports any errors. It seems like vscode isn't reloading files that aren't being actively edited when I switch branches.

This doesn't _always_ happen, just often enough to be noticeable.

**Comment by dbaeumer** [comment] 2016-06-20 08:50
@danvk in step 3 how do you reload all files. Do you reload the VS Code window?

**Comment by drayfar** [comment] 2018-08-01 19:06
@dbaeumer any update on this? It's very frustrating, especially when in complex projects. I have to open a lot of files to get back to a good state.

**Comment by gouldda76** [comment] 2019-02-12 20:21
+1 on that, I'm working on a very large project, regularly switching branches, and this problem makes the Problems tab almost unusable for me at times (unless I want to go trawl through dozens of files opening them to make the reported problems go away.  Note as well that closing and reopening VSCode does not make the problems go away - its still confused when you start it back up, so I'm guessing there is some file caching in play on the intellisense or whatever sub system does the problem scanning.  Really curious if anybody has even identified a workaround for this that doesn't involve opening all the files its complaining about?

**Comment by maxming2333** [comment] 2019-07-19 07:37
I also encountered this problem.
Vscode seems to be unable to detect file changes with external commands
Causes an error displayed in the editor

**Comment by joshden** [comment] 2020-02-11 03:11
> Note as well that closing and reopening VSCode does not make the problems go away - its still confused when you start it back up, so I'm guessing there is some file caching in play on the intellisense or whatever sub system does the problem scanning. Really curious if anybody has even identified a workaround for this that doesn't involve opening all the files its complaining about?

I notice  this problem regularly. It was especially noticeable after doing a large refactoring and switching between between a branch with the refactored code and one that didn't have the refactored code. 

But at least with the later versions of VS Code, the problem does resolve if I close and reopen VS Code. I've had to tell other team members to try restarting VS Code when seeing unexpected TypeScript errors.

**Comment by kepikoi** [comment] 2020-07-01 07:45
Seeing the same behavior for quite some time with WebStorm (e.g. 2020.1) on Win10 Pro (e.g. 1909 but). Restarting the IDE mitigates the issue

**Comment by rnemec-ng** [comment] 2020-07-01 16:22
Hi, restarting VSCode (or the TS lang server) works as a workaround, but ... does anybody have a less expensive workaround?
Anything perhaps with file watching settings?

**Comment by Haaxor1689** [comment] 2020-08-25 14:52
I would welcome an option to clear ts linter cache on demand. Still manual solution but much better than having to close VS Code and re-run yarn start, storybook etc.

**Comment by sergeijakovlev** [comment] 2020-09-17 17:23
Restarting TypeScript server also seems to help without restarting the IDE, although "initialization of JS/TS features" does take a bit of time.

**Comment by charleshimmer** [comment] 2021-04-12 16:23
Still seeing this issue today.

**Comment by kepikoi** [comment] 2021-04-15 10:16
> Restarting the IDE mitigates the issue

Found a better workaround using a key combination to restart the TS server. E.g. in Webstorm: 
![image](https://user-images.githubusercontent.com/12378498/114853749-6787f600-9de4-11eb-81de-95d5d747a5c5.png)

**Comment by charleshimmer** [comment] 2021-04-15 12:18
Looks like you can setup the same thing with VS Code. Good idea @kepikoi 
![image](https://user-images.githubusercontent.com/192403/114867735-c0db2f80-9dba-11eb-932b-9f0e30436757.png)

**Comment by misha15w** [comment] 2022-04-11 07:58
Is there any update about the issue? Quiet bad to switch between branches still

**Comment by aimad-majdou** [comment] 2022-07-29 11:45
Any updates on this issue? restarting the TS server doesn't fix the issue, you really need to restart vs code itself

**Comment by HaveSpacesuit** [comment] 2022-08-04 19:14
It looks like TypeScript 4.8 may be addressing this?
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-beta/#file-watching-fixes-especially-across-git-checkouts

**Comment by mjbvz** [comment] 2022-09-23 20:03
Thanks @HaveSpacesuit  I'm going to close this as now it would be more helpful for us to track individual cases where problems aren't updated properly. 

If you are still seeing this problem when switching branches on TypeScript 4.8+, please open a new issue with some example steps so that we can try debugging. Alternatively you can also share the TypeScript server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Closed by mjbvz** 2022-09-23 20:03 UTC
Labels: bug, typescript
