### ISSUE TITLE
Why does vscode not copy line breaks?

### ISSUE THREAD

**Issue by nailao** [microsoft/vscode#77043] opened 2019-07-10 03:47 UTC
- VSCode Version: 1.36.1
- OS Version: Windows 7

I've set `editor.emptySelectionClipboard` to true, but I can't copy blank lines, which was previously allowed.

**Comment by rebornix** [comment] 2019-07-17 22:59
Duplicate of https://github.com/microsoft/vscode/issues/69903

**Closed** 2019-07-17 22:59 UTC
Labels: *duplicate, bug
