### ISSUE TITLE
Underscores are invisible in the integrated terminal

### ISSUE THREAD

**Issue by LQR86** [Microsoft/vscode#41244] opened 2018-01-07 13:26 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
cpptools|ms-|0.14.5
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. open the integrated terminal (Ctrl + `), click on it
2. type an underscore, such as `_`

Reproduces without extensions: Yes

**Comment by usernamehw** [comment] 2018-01-07 17:04
Duplicate of https://github.com/Microsoft/vscode/issues/35901

**Closed** 2018-01-07 19:51 UTC
Labels: *duplicate, integrated-terminal
