### ISSUE TITLE
Settings Editor: Clicking behavior is not consistent

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55528] opened 2018-07-31 21:57 UTC
Sometimes when I click on a mega section, it expands, sometimes it doesn't:

![setting-click](https://user-images.githubusercontent.com/4033249/43489448-ea1da476-94d1-11e8-8fea-9e380b082f02.gif)

**Comment by roblourens** [comment] 2018-08-01 04:39
Related to #55527

**Comment by roblourens** [comment] 2018-08-10 00:46
Fixed with #54039

**Comment by bpasero** [comment] 2018-08-30 12:34
I can still reproduce this behaviour. Seamingly random nodes expand or just "bold".

**Comment by roblourens** [comment] 2018-09-05 17:43
Actually dupe of https://github.com/Microsoft/vscode/issues/57273, fixing there

**Closed by roblourens** 2018-09-05 17:43 UTC
Labels: bug, settings-editor, verification-found
