### ISSUE TITLE
Treating extensions description editor as regular editors?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7961] opened 2016-06-22 07:32 UTC
Currently the extensions description window is just like any other editor - which means I can quick open away from it, I can split editor it eg...

Do we want to allow all these actions or we need to treat it in some special way?
My argument is that the user never wants to see more than 1 and the user does not want to see this once he is not in the extensions viewlet.

If we treat them as regular editors - I would expect they do not pollute my quick open history and that I just see 1 instance of them

![screen shot 2016-06-22 at 09 32 19](https://cloud.githubusercontent.com/assets/1926584/16258053/3ee44066-385c-11e6-991e-428df137bb81.png)

**Comment by joaomoreno** [comment] 2016-06-23 14:56
I'm a bit lost in this world, need your help @bpasero

**Comment by bpasero** [comment] 2016-06-25 15:38
There is currently no way of excluding editors in the list of recently opened because that list is for editors that you open in a session.

It seems to me that we are starting to think about workarounds for UX issues that all originate from the fact that we use an editor for showing the extension description (see also https://github.com/Microsoft/vscode/issues/8060). 

I am arguing that if we feel that the extension description is not a real editor, we should not show it inside an editor but come up with different UI. 

As long as extensions are editors, we will have to live with some of these issues.

**Comment by bpasero** [comment] 2016-06-25 15:38
@joaomoreno at least I suggest to prefix the editor with something stable like "Extension: " so that people are not getting super confused.

**Comment by bpasero** [comment] 2016-06-26 07:17
@isidorn maybe we sit together next week to make a decision how to improve this 👍

**Comment by isidorn** [comment] 2016-06-27 10:13
@bpasero yeah let's look into this and #8060 together tomorrow / wednesday

**Comment by bpasero** [comment] 2016-06-27 11:33
@isidorn no matter the outcome, I do think you should already add some prefix to the editor title at least.

**Comment by isidorn** [comment] 2016-06-27 12:44
@bpasero added the 'Extension: ' prefix

**Comment by isidorn** [comment] 2016-06-29 12:16
Agreed with @bpasero that this is nothing we want to tackle in endgame week -> moving to July, joao

**Comment by joaomoreno** [comment] 2016-07-04 12:34
What can we do in July then?

**Comment by joaomoreno** [comment] 2016-07-13 09:07
Closing it as designed due to _As long as extensions are editors, we will have to live with some of these issues._ Also, with the `Extension:` prefix, things don't look so bad now.

**Closed by joaomoreno** 2016-07-13 09:07 UTC
Labels: bug, extensions
