### ISSUE TITLE
bash receives incorrect build path

### ISSUE THREAD

**Issue by v-andrew** [microsoft/vscode#83023] opened 2019-10-21 23:12 UTC
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set `bash` as default shell
2. Run build task for typescript project
```
> Executing task: tsc -p d:\node\test-slack-bot\tsconfig.json <

error TS5058: The specified path does not exist: 'd:nodetest-slack-bottsconfig.json'.
The terminal process terminated with exit code: 1
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by v-andrew** [comment] 2019-10-21 23:15
Build works when you set build task to us power-shell, however there is an annoying bug https://github.com/microsoft/vscode/issues/83021

**Comment by alexr00** [comment] 2019-10-22 07:08
We try to do some path manipulation to help with issues like this, but we can't reliably tell when a parameter should have this done. This is absolutely a bug, but not one that can be easily fixed. Would likely be helped by https://github.com/microsoft/vscode/issues/38381, so marking as a duplicate of that.

**Closed** 2019-10-22 07:08 UTC
Labels: *duplicate, tasks
