### ISSUE TITLE
JavaScript prototypes - Go to def, type def, implementations refs, peek and others don't work

### ISSUE THREAD

**Issue by stephen147** [microsoft/vscode#121423] opened 2021-04-15 21:53 UTC
- VS Code Version: Version: 1.55.2
- Windows: OS: Windows_NT x64 10.0.19042
- All extensions disabled and restarted VSC.

## Steps to Reproduce:

Save this code to **whatever.js**

```javascript
var mytime = 131639508000000000;
var date = new Date((mytime-116444736000000000)/10000);

Date.prototype.yyyymmddhhmmss = function() {
var yyyy = this.getFullYear().toString();
var mm = (this.getMonth()+1).toString(); // getMonth() is zero-based
var dd = this.getDate().toString();
var hh = this.getHours().toString();
var min = this.getMinutes().toString();
var ss = this.getSeconds().toString();
return yyyy + '-' + (mm[1]?mm:"0"+mm[0]) + '-' + (dd[1]?dd:"0"+dd[0]) + ' ' + (hh[1]?hh:"0"+hh[0]) + ':' + (min[1]?min:"0"+min[0]) + ':' + (ss[1]?ss:"0"+ss[0]);
};

console.log(date.yyyymmddhhmmss());
```

If you select anywhere in the `yyyymmddhhmmss ` and click on any of the things highlighted red here, they don't work.

This is really the only thing that'll prevent me from switching from Sublime Text.

![image](https://user-images.githubusercontent.com/14054664/114942790-f6c0f800-9e3c-11eb-8b42-fb3aafe2db2f.png)

## Screenshot of the problem
![image](https://user-images.githubusercontent.com/14054664/114941796-82d22000-9e3b-11eb-937c-1ee90ae296bd.png)

**Comment by mjbvz** [comment] 2021-04-17 01:04
Duplicate of https://github.com/microsoft/TypeScript/issues/36609

**Closed by mjbvz** 2021-04-17 01:04 UTC
Labels: new release

**Comment by stephen147** [comment] 2021-04-17 01:13
If that other thread is the same will the fix for that also resolve the issues outlined in my issue?
