### ISSUE TITLE
code --install-extension results in UnhandledPromiseRejectionWarning: Canceled: Canceled

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode#128854] opened 2021-07-16 14:38 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Yes

Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Run code.cmd --install-extension some_extension.vsix --force
2. This was initially produced with `code.cmd --install-extension rust-analyzer.vsix --force` from the rust-analyzer extension: https://github.com/rust-analyzer/rust-analyzer

CC rust-analyzer/rust-analyzer#9615

**Comment by sandy081** [comment] 2021-07-19 15:37
Can't repro it. Are there any steps/set up that is missing here?

**Comment by newlifewj** [comment] 2021-07-20 16:30
version: 1.58.1
Nodejs: v14.16.0
---------------------------------------------------------------------------------
The extension works sometimes, but it will not work in this warning:

... .0.0.vsix' was successfully installed.
(node:10856) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at Object.O [as canceled] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at T.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:62864)
    at T.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63004)
    at k.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63266)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:11:7229)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3634
    at Object.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3706)
    at Object.W [as dispose] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3567)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41195
    at Map.forEach (<anonymous>)
    at Ne.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41182)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at a.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at Object.g [as main] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:51594)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async k (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13756)

**Comment by newlifewj** [comment] 2021-07-20 18:25
It fixed after updated to v1.58.2

**Comment by sandy081** [comment] 2021-07-21 08:00
Can you also please check with our latest insiders - https://code.visualstudio.com/insiders/

**Comment by rbrisita** [comment] 2021-07-22 04:50
I'm still getting this error after forced install of an extension.

VS Code: 1.58.2
NPM: 7.15.1
Node: v14.2.0
Windows 10 Home: 19043.1110

**Comment by sandy081** [comment] 2021-07-22 20:14
@rbrisita I can't repro, please provide steps/

**Comment by rbrisita** [comment] 2021-07-26 18:46
@sandy081:

` code --extensions-dir .\.vscode\extensions --install-extension dbaeumer.vscode-eslint --force`

Hope this helps!

**Comment by sandy081** [comment] 2021-07-27 08:19
Cant repro it.

Can you please try our latest insiders and see if you can repro it?

**Comment by darklore** [comment] 2021-07-28 02:25
Reproduced in my environment.
It seems to occur when installing or uninstalling extensions one after another

- VS Code Version: 1.58.2
- OS Version: OSX 11.4

Steps to Reproduce:
1.  code --list-extensions | xargs -I{} code --uninstall-extension {}

**Comment by sandy081** [comment] 2021-07-30 10:20
I can repro this with following steps while running from sources

1. Download the extension vsix from https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
2. Install the vsix using command `./scripts/code-cli.sh --install-extension <vsix_path>`

Following error is printed

```
yarn run v1.22.4
$ node build/lib/electron
✨  Done in 0.51s.
[12:18:12] Syncronizing built-in extensions...
[12:18:12] You can manage built-in extensions with the --builtin flag
[12:18:12] [marketplace] ms-vscode.node-debug@1.44.32 ✔︎
[12:18:12] [marketplace] ms-vscode.node-debug2@1.42.10 ✔︎
[12:18:12] [marketplace] ms-vscode.references-view@0.0.80 ✔︎
[12:18:12] [marketplace] ms-vscode.js-debug-companion@1.0.14 ✔︎
[12:18:12] [marketplace] ms-vscode.js-debug@1.59.0 ✔︎
[12:18:12] [marketplace] ms-vscode.vscode-js-profile-table@0.0.18 ✔︎
Debugger listening on ws://127.0.0.1:5874/2ac72eb4-e7dc-4ac4-9b59-f5abd3f0eda9
For help, see: https://nodejs.org/en/docs/inspector
Installing extensions...
Extension 'ms-vscode-remote.remote-ssh-0.65.7.vsix' was successfully installed.
(node:39415) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at canceled (/Users/sandy081/work/vscode/out/vs/base/common/errors.js:109:23)
    at Delayer.cancel (/Users/sandy081/work/vscode/out/vs/base/common/async.js:247:57)
    at Delayer.dispose (/Users/sandy081/work/vscode/out/vs/base/common/async.js:259:18)
    at ThrottledDelayer.dispose (/Users/sandy081/work/vscode/out/vs/base/common/async.js:287:26)
    at dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:153:18)
    at FileWatcher.dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:195:25)
    at FileWatcher.dispose (/Users/sandy081/work/vscode/out/vs/platform/files/node/watcher/nodejs/watcherService.js:103:19)
    at dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:99:27)
    at /Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:121:43
    at /Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:130:17
    at Object.dispose (/Users/sandy081/work/vscode/out/vs/base/common/functional.js:18:25)
    at dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:115:17)
    at /Users/sandy081/work/vscode/out/vs/platform/files/common/fileService.js:899:76
    at Map.forEach (<anonymous>)
    at FileService.dispose (/Users/sandy081/work/vscode/out/vs/platform/files/common/fileService.js:899:33)
    at dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:160:17)
    at DisposableStore.dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:153:18)
    at CliMain.dispose (/Users/sandy081/work/vscode/out/vs/base/common/lifecycle.js:195:25)
    at Object.main (/Users/sandy081/work/vscode/out/vs/code/node/cliProcessMain.js:157:21)
    at async main (/Users/sandy081/work/vscode/out/vs/code/node/cli.js:38:13)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:39415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:39415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Assigning to @bpasero as this is coming from file service at following location

https://github.com/microsoft/vscode/blob/994a6c197b5a15d7b9523cb6dfd17f1dbbcb7772/src/vs/platform/files/common/fileService.ts#L1154-L1154

**Comment by bpasero** [comment] 2021-08-04 11:43
Even though I cannot reproduce, I noticed that the CLI process was missing to install handlers for unhandled rejections:

https://github.com/microsoft/vscode/blob/e007ca899cfc1db8edde0e959b6d8ad8a9694cf7/src/vs/code/node/cliProcessMain.ts#L194-L195

**Closed by bpasero** 2021-08-04 11:43 UTC
Labels: bug, file-watcher
