### ISSUE TITLE
The backspace key doesn't work except the editor

### ISSUE THREAD

**Issue by zeromniverse** [microsoft/vscode#76883] opened 2019-07-08 14:15 UTC
Issue Type: <b>Bug</b>

Hello,
I can use the backspace key in the editor and the search box,but I can't use it in the debug console or the extension store and other input area.If I open a file before,when I type words in the debug console then press the backspace key,then the code in the editor will be deleted.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment] 2019-07-08 14:58
I can not reproduce this.
Also please note that the debug console input is only editable while you are debugging
Can you reproduce this with vscode insiders? If yes can you please attach a short video showing this
https://code.visualstudio.com/insiders/

**Comment by zeromniverse** [comment] 2019-07-09 08:05
> I can not reproduce this.
> Also please note that the debug console input is only editable while you are debugging
> Can you reproduce this with vscode insiders? If yes can you please attach a short video showing this
> https://code.visualstudio.com/insiders/

Thanks a lot, I tried the vscode insiders and then this problem disappeared.And I have updated all the extensions of my vscode and then this problem is fixed.This problem seems to be caused by some extensions with old versions.

**Comment by isidorn** [comment] 2019-07-09 08:07
Ok. Thus closing this.
If you want you can identify what extension is the cause and you can file na issue against them.
Thanks

**Closed by isidorn** 2019-07-09 08:07 UTC
Labels: debug, debug-console, needs more info
