### ISSUE TITLE
Option to open links in external application

### ISSUE THREAD

**Issue by folcraed** [Microsoft/vscode#66797] opened 2019-01-20 04:40 UTC
I work with markdown that has many links to images and PDF files. When clicking on the links, some will open in VSCode, but most don't, instead showing a dialog saying the file is too large and asking if I'd like to open the file with and external app. What I'd really like is to _always_ open linked files in an external app, but there's no option to set that. I've searched through the extensions, and there doesn't seem to be any of those that do either.

I'd love to see an option in VSCode's settings to allow users to bypass Code trying to open linked image files and just use the system's default application. I've read that one reason larger images aren't opened in Code is due to the memory issues it would create. Considering that a dialog appears when I try to, and Code can then pass the job off to an external app, I would hope it wouldn't take much to expose that as a user setting, to automatically bypass Code trying to open it and use the external app by default.

**Comment by jrieken** [comment] 2019-01-21 21:57
closing as duplicate of #66741

**Closed** 2019-01-21 22:39 UTC
Labels: *duplicate, feature-request
