### ISSUE TITLE
link in JSONSchema tool-tip over-escaped

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#12406] opened 2016-09-21 20:39 UTC
- VSCode Version: Version 1.6.0 (1.6.0) (`master` 641121489ac45fb6588abc6ff6209e4943e9ff2e )
- OS Version: OSX 10.11.6

Steps to Reproduce:

[`test-schema.json`](https://gist.githubusercontent.com/Sequoia/e59bed17d5706e9f6fe07dc014b53e8a/raw/test-schema.json):

``` json
{
  "title": "JSON schema for testing VSCode",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
      "description": "If you don't like my schema let me know: http://sequoia.makes.software/contact"
    }
  }
}
```
1. Create the following JSON file in VSCode (referencing 
   
   ```
   {
       "$schema" : "https://gist.githubusercontent.com/Sequoia/e59bed17d5706e9f6fe07dc014b53e8a/raw/test-schema.json",
       "foo": "bar"
   }
   ```
2. Mouseover "foo"
3. Observe that link is improperly escaped
   1. Observe that clicking link does not work

![screenshot 2016-09-21 15 57 33](https://cloud.githubusercontent.com/assets/317498/18728094/a729556c-8019-11e6-8a3d-a6c841a876bb.png)

**Comment by aeschli** [comment] 2016-12-05 15:05
duplicate of #14968

**Closed by aeschli** 2016-12-05 15:05 UTC
Labels: bug, json
