### ISSUE TITLE
Failure to update within vscode.  Needed to download and install.

### ISSUE THREAD

**Issue by robertlugg** [Microsoft/vscode#52705] opened 2018-06-22 18:59 UTC
Issue Type: <b>Bug</b>
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2128801/vscode-inno-updater.log)

(I clicked on the popup that appeared in the lower right corner)

Please note that the version shown below is the *new* version that I needed to install manually after seeing a popup error message (also attached).

Manually downloading and installing worked just fine so no need to act on this issue, but I wanted to report it in any case.
![image 1777](https://user-images.githubusercontent.com/6054540/41794243-42d3fdce-764e-11e8-8377-8d995182a7e0.png)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
xml|Dot|2.3.1
sort-lines-by-selection|ear|0.0.3
rainbow-csv|mec|0.4.2
python|ms-|2018.6.0
unicode-latex|oij|1.1.1
progen-mtp|rob|0.0.1
tcl|ras|0.1.0
vscode-icons|rob|7.24.0
rust|rus|0.4.5
partial-diff|ryu|1.1.0
bash-beautify|sha|0.1.1

(3 theme extensions excluded)

</details>

**Comment by TomSputz** [comment] 2018-06-22 19:14
Dupe of #47841 - Cause is unknown atm, so no idea how long it is until a fix, in the meantime you can update without issue by clicking 'Install Update' in vscode, then once it pops up the 'Restart VSCode to load update' message (I'm paraphrasing), just close the application

The next time you start it, the update will have been applied.

**Comment by jbmonroe** [comment] 2018-06-24 17:06
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2131009/vscode-inno-updater.log)

As instructed by installer

**Comment by joaomoreno** [comment] 2018-06-26 07:48
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to try out our user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682

**Closed by joaomoreno** 2018-06-26 07:48 UTC
