### ISSUE TITLE
Clean file from Git view not reload it in file view

### ISSUE THREAD

**Issue by jgsqware** [Microsoft/vscode#7449] opened 2016-06-09 05:15 UTC
- VSCode Version: Version `0.10.10`
                               Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
- OS Version: `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux`

When a versioned file is **deleted** from ui, then clean from **Git view**, it's doesn't show up in **File view**.

Steps to Reproduce:

1. Delete a versioned file 
2. Clean it from Git view
3. The file doesn't come up in the file view

**Comment by joaomoreno** [comment] 2016-06-09 07:42
Can't reproduce, but sounds like a lack of file system events.

If you create a new file in the directory open in Code, does it appear in the file view?

**Comment by bpasero** [comment] 2016-06-19 07:45
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-06-19 07:45 UTC
Labels: needs more info
