### ISSUE TITLE
Underline key is invisible in terminal

### ISSUE THREAD

**Issue by wedsonlopes** [microsoft/vscode#81011] opened 2019-09-16 22:53 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by wedsonlopes** [comment] 2019-09-16 22:53
Underline key"_" is invisible in terminal of visual studio code.

**Comment by jeanp413** [comment] 2019-09-17 04:35
duplicate of #35901

@wedsonlopes read that post for a workaround like changing `terminal.integrated.fontFamily` or `terminal.integrated.fontSize`

**Closed** 2019-09-18 01:00 UTC
Labels: *duplicate
