### ISSUE TITLE
Some UI elements do not scale with window.zoomLevel

### ISSUE THREAD

**Issue by stackia** [Microsoft/vscode#24841] opened 2017-04-15 22:58 UTC
- VSCode Version: 1.11.2
- OS Version: Windows 10 (150% system scale) or macOS 10.12

Steps to Reproduce:

1. Set window.zoomLevel to any value (e.g. 1.4)
2. See screenshots

![image](https://cloud.githubusercontent.com/assets/5107241/25067317/ed4e76ee-2271-11e7-878f-2caabc5a1816.png)

![image](https://cloud.githubusercontent.com/assets/5107241/25067318/f33cdad2-2271-11e7-824b-a9d277e44ab6.png)

**Comment by stef-levesque** [comment] 2017-04-18 18:27
The same happen when zooming out (-1)
Markdown and previewHtml overflow is hidden, and not scrollable

**Comment by mjbvz** [comment] 2017-04-18 18:41
Duplicate of #5745. Should be fixed in current insiders

**Closed by mjbvz** 2017-04-18 18:41 UTC
Labels: duplicate, webview
