### ISSUE TITLE
Markdown preview occupies a small part of the editor window

### ISSUE THREAD

**Issue by cdoremus** [Microsoft/vscode#22252] opened 2017-03-08 21:06 UTC
- VSCode Version: 1.10.2 (but also occurred in versions 1.9-1.10.1)
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. Select ```Open Preview``` on a Markdown file.
2. Preview of markdown file occupies a small frame of the editor window. This happens with a full or split editor window.  This is what it looks like:
![screenshot from 2017-03-08 15-56-30](https://cloud.githubusercontent.com/assets/942174/23723913/ebeb7fd0-0418-11e7-92bc-ef6fc32a84a7.png)

**Comment by mjbvz** [comment] 2017-03-08 21:33
Duplicate of #5745

**Closed by mjbvz** 2017-03-08 21:33 UTC
Labels: duplicate, markdown, webview
