### ISSUE TITLE
Zooming out is settings cursor position off some pixels left in editor

### ISSUE THREAD

**Issue by nikunjbhatt** [Microsoft/vscode#27130] opened 2017-05-23 11:08 UTC
- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04 LTS x64

Steps to Reproduce:

1. Open editor and zoom out (using shortcut or from View menu)
2. On a blank line, type some text (example: 123456789012345...)
3. When typing, the cursor is shown shifting some pixel to the right than the actual position. (It is more noticeable after writing 10-15 characters).

Cursor is shifting proportionally to the actual cursor position; the higher the number of characters the cursor is away from left side, the cursor is shifting more to the right.

In the following image, the cursor is actually at the end of line but showing before the last character:
![image](https://cloud.githubusercontent.com/assets/4369071/26351622/fc3d45f0-3fd5-11e7-8b2f-6c17a827ff15.png)

**Comment by alexandrudima** [comment] 2017-05-24 08:49
Duplicate of #26151. The insiders channel should already contain a fix.

**Closed by alexandrudima** 2017-05-24 08:49 UTC
