### ISSUE TITLE
Incorrect file is selected and renamed when using keyboard arrows and keyboard context menu to select file for renaming

### ISSUE THREAD

**Issue by BartoszKlonowski** [microsoft/vscode#116063] opened 2021-02-07 22:42 UTC
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 10.0.19042

Steps to Reproduce:

1. Open folder with project containing *.gitmodules*
2. Rename one of any files (except *.gitmodules*) by clicking it directly with the cursor
3. Select any other file (except *.gitmodules*) by using arrows
4. Open context menu by using keyboard context menu key
5. Select *Rename* option and hit *Enter*

Does this issue occur when all extensions are disabled?: Yes

---

**Result**
No matter what file is selected using keyboard, the *.gitmodules* file is being selected and renamed.
Even though the focus **is** on the selected file.
See the following:
![VSCodeBug](https://user-images.githubusercontent.com/70535775/107161558-bc029580-699d-11eb-8459-cb53bbaea0ce.gif)

**Comment by gjsjohnmurray** [comment] 2021-02-07 22:58
/duplicate of #100151 and is fixed in 1.54 Insiders

**Closed** 2021-02-07 22:59 UTC
Labels: *duplicate
