### ISSUE TITLE
Blinking URLs in comments

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#75470] opened 2019-06-14 03:45 UTC
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Open two files, `test.ts` below and some other file.
2. Place the cursor at the end of one of the two lines above the link.
3. Select the second file.
4. Alt+Tab or click on another window.
5. Go back into VSCode.
6. Select the first file.
7. The underlined link now (partially) blinks for some reason.

**test.ts**
```ts
class Foo {

  protected get bar(): boolean {
    return true;
  }

  /**
   * http://www.example.com/#blah
   */
  protected baz(): void {
    return;
  }

}
```

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:19:34.516Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by rebornix** [comment] 2019-07-26 19:58
A potential duplicate of https://github.com/microsoft/vscode/issues/48321

**Closed** 2019-07-27 00:06 UTC
Labels: *duplicate, bug, editor-contrib
