### ISSUE TITLE
Feature Request: Multi Root Workspace Theme/Colors - use colors to visibly distinguish tabs

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/vscode#32830] opened 2017-08-19 16:55 UTC
- VSCode Version: 1.16.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create multi root workspace
2. observe the tab color, folder color etc.

Feature Request: 
I love the multi root feature. It would be nice to have visual indication of root folder for currently visible open file. 

options:
* Different color for tabs from same root. tabs may mix on tab bar
* tab groping for same root folder on tab bar - with color indication, like in internet explorer
* it would also be helpful to change the root in the "Open Editors" section, when you switch files from different group it changes text with  active root like "OPEN EDITORS - root folder 1" or "OPEN EDITORS - full path of root". reversing path (folder/paretnfolder/c: instead of c:\parentfolder\folder") may be helpful to correctly identify the actual root in case we have same name of folder from different folder hierarchy.

**Comment by bpasero** [comment] 2017-08-21 07:47
Marking as duplicate of https://github.com/Microsoft/vscode/issues/31308

**Closed by bpasero** 2017-08-21 07:47 UTC
Labels: insiders, multi-root, workbench
