### ISSUE TITLE
index.js file on top of folder

### ISSUE THREAD

**Issue by Chetan11-dev** [microsoft/vscode#111157] opened 2020-11-23 05:30 UTC
When browsing through the project I have a frequent need to go to  index file. 
For it 
 I need to search through Command Pallette(Ctrl + P)
 or 
 Look at multiple files to find index file 
It is not a problem when number of files < 3 but otherwise it is pain on brain. 
We could have a feautre when filesInFolder > 3 we bring the index file on top. 
What is your opinion on the Subject?

**Comment by Chetan11-dev** [comment] 2020-11-23 05:32
![Screenshot from 2020-11-23 10-55-59](https://user-images.githubusercontent.com/53407137/99931663-58dc6c00-2d7b-11eb-8099-f000a911820d.png)

**Comment by yume-chan** [comment] 2020-11-23 10:49
Duplicate of #108452

**Closed** 2020-11-23 11:33 UTC
Labels: *duplicate

**Comment by Chetan11-dev** [comment] 2020-11-24 08:25
Please it is definatly a useful feauture. Please give some thought to this feauture.
