### ISSUE TITLE
Popup Menu font has been changed to "Times New Roman"

### ISSUE THREAD

**Issue by gtim108** [microsoft/vscode#103593] opened 2020-07-29 22:59 UTC
![Screenshot_20200730_085722](https://user-images.githubusercontent.com/11308364/88862169-eaf7bc00-d242-11ea-8455-e944a905e793.png)

Version: 1.48.0-insider
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:39:40.074Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.7.9-100.fc31.x86_64
Steps to Reproduce:

1. In Extensions side bar click `Views and More Actions` button. 
2. `Views and More Actions` appears and all menu items have "Times New Roman" 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeancabral** [comment] 2020-07-30 01:39
same problem here

**Comment by jeancabral** [comment] 2020-07-30 01:41
Duplicate of #103342

**Comment by sbatten** [comment] 2020-07-30 15:56
closing as duplicate, tackling dupe today

**Closed by sbatten** 2020-07-30 15:56 UTC
