### ISSUE TITLE
VS Code in Microsoft Store (Verified App for Windows 10 in S Mode)

### ISSUE THREAD

**Issue by jebalert** [Microsoft/vscode#55761] opened 2018-08-03 14:01 UTC
Just picked up a Surface Go yesterday and I noticed there are no good code editors in the Microsoft Store. Do we know if there are any plans of porting VSCode to the Microsoft Store?

**Comment by V-ed** [comment] 2018-08-03 14:53
Duplicate of #10759

**Closed** 2018-08-25 14:15 UTC
Labels: *duplicate
