### ISSUE TITLE
Hard to discover edit sessions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#156348] opened 2022-07-26 19:09 UTC
Testing #156211

I think being able to store sessions across clients is a great feature, however, it is very hard to discover without knowing about the command. I kept expecting to see a command/option from the SCM view:

<img width="245" alt="CleanShot 2022-07-26 at 12 06 59@2x" src="https://user-images.githubusercontent.com/35271042/181091210-8417fbf9-df39-43a9-bf79-143def9af83e.png">

or even the remote repositories (this was a last-ditch effort as I normally don't ever visit this view)

<img width="515" alt="CleanShot 2022-07-26 at 12 07 20@2x" src="https://user-images.githubusercontent.com/35271042/181091372-8d368a8d-bc66-45ed-87ac-906955c6892b.png">

or the remote picker, which I do see there is a "continue working on" action but that doesn't sound like edit sessions:
<img width="632" alt="CleanShot 2022-07-26 at 12 08 28@2x" src="https://user-images.githubusercontent.com/35271042/181091594-79ccf5c1-f600-464d-a6db-489362bb3154.png">

**Comment by joyceerhl** [comment] 2022-07-27 17:54
Continue Working On's implementation will be replaced with Continue Edit Session. I also think it makes sense to include Store Current Edit Session in the SCM and Remote Repositories view actions.

**Comment by misolori** [comment] 2022-07-27 19:38
> Continue Working On's implementation will be replaced with Continue Edit Session

We should ensure that we use the same terminology if it will be replaced as it's not obvious those two are connected in any way. Even simply changing the command from "Continue Working On..." to "Continue Edit Session..." will go a long way.

**Comment by joyceerhl** [comment] 2022-07-27 20:57
Yeah, to clarify, I meant that Continue Working On will soon be updated to delegate to the Continue Edit Session command, and users will keep looking for 'Continue Working On'. Continue Edit Session isn't at parity with Continue Working On yet, so I kept the names separate to avoid confusion in the meantime.

**Comment by joyceerhl** [comment] 2022-08-24 16:43
Closing as a duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/231

**Closed by joyceerhl** 2022-08-24 16:43 UTC
Labels: feature-request
