### ISSUE TITLE
Prompt to install extension from external link re-appears after reloading editor window

### ISSUE THREAD

**Issue by jkjustjoshing** [Microsoft/vscode#33030] opened 2017-08-23 13:10 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-es-beautifier|dai|1.0.0
gitlens|eam|4.4.0
tslint|eg2|0.17.0
vscode-angular2-emmet|jak|2.0.3
vscode-text-pastry|jkj|1.1.1
debugger-for-chrome|msj|3.1.8
autoimport|ste|1.2.2

---

Steps to Reproduce:

1. Open VS Code
2. Go to marketplace.visualstudio.com, navigate to an extension, and click "Install". VS Code should come into focus with "Would you like to install XX extension?" prompt showing
3. Install the extension
4. Click the "Reload" button to reload the VS Code window and enable the extension.
5. When VS Code re-loads the "Would you like to install...." prompt re-appears. Expected behavior is that it would not re-appear.

Additionally, when you go through this process for multiple extensions, when VS Code reloads the prompts stack, showing multiple outdated prompts.

![image](https://user-images.githubusercontent.com/813192/29617425-d4769080-87e2-11e7-8152-fefe501e42a1.png)

**Comment by joaomoreno** [comment] 2017-08-30 13:20
Duplicate of #32610

**Comment by chrisdias** [comment] 2017-09-07 19:56
I'm still seeing the multiple prompts to install...

browse to https://code.visualstudio.com/tutorials/nodejs-deployment/create-website
install the azure cli extension
restart
uninstall the azure cli extension
restart

result: prompt to install the extension

**Comment by joaomoreno** [comment] 2017-09-08 07:18
Yeah... if you uninstall then you'll get the prompt once again... If you think it's worth the fix, can you create a separate issue? :+1:

**Closed** 2017-09-11 08:19 UTC
Labels: bug, duplicate, extensions
