### ISSUE TITLE
Update Commenting gutter icon

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#149085] opened 2022-05-09 12:54 UTC
When there are comments in a file, they show up as a diamond icon in the gutter.

![image](https://user-images.githubusercontent.com/485572/167413175-b1c741d7-3c5a-4fa6-a5cc-cd2fe2ec39b4.png)

- This is not very intuitive.
- It looks like the codicon debug-breakpoint-log, which is unrelated
- For consistency, we could reuse the icons from the Comments panel (`comment` or `comment-discussion`)

cc @albertelo, @misolori

**Comment by misolori** [comment] 2022-05-09 14:38
Related to this are https://github.com/microsoft/vscode/issues/115808 and https://github.com/microsoft/vscode/issues/143774. We don't have support for codicons in the gutter yet and that would be a pre-requisite.

**Comment by alexr00** [comment] 2022-06-14 14:03
Marking as a duplicate of https://github.com/microsoft/vscode/issues/115808 as it is older.

**Closed by alexr00** 2022-06-14 14:03 UTC
Labels: feature-request, ux, comments
