### ISSUE TITLE
editor.hover.enabled is annoying sometimes

### ISSUE THREAD

**Issue by n8crwlr** [microsoft/vscode#79601] opened 2019-08-21 20:58 UTC
Hello,

in relation to https://github.com/microsoft/vscode/issues/52821#issue-335448818 i feel that the **hover** popup options should be optimized.

Principially, **hover** popup can be enabled for mouse or with Key `CTRL+K`, `CTRL+I`

The first one, `"editor.hover.enabled": true` shows it after delay _every time mouse hovers_, the second one, `CTRL+K`, `CTRL+I`, opens the popup, but as far as i move the mouse cursor, the popup hides, even if `"editor.hover.sticky": true` is set.

There are dozens of popup places in code, so, permanently moving with mouse over them can be irritating and to wait a long delay is not best option. Keying `CTRL+K`, `CTRL+I` is sometimes ok, but cursor must be placed before.

My intention is to get **mouse cursor** plus `CTRL`:
- _clicking_ is `Go to definition`
- _holding over the word_ opens hover popup

Actually, `CTRL`|`CMD` + mouse cursor is only bound to `onclick` event, if i am correct.

That addition would feel good to me.

**Comment by RMacfarlane** [comment] 2019-08-22 04:00
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/43857, let me know if it's not quite the same. Thanks!

**Closed by RMacfarlane** 2019-08-22 04:00 UTC
Labels: editor-hover
