### ISSUE TITLE
Bad perf with monochrome theme?

### ISSUE THREAD

**Issue by tj** [microsoft/vscode#98738] opened 2020-05-28 14:34 UTC
- VSCode Version: 1.45.1
- OS Version: Mac 10.12.6

Steps to Reproduce:

1. Install this theme https://github.com/anotherglitchinthematrix/monochrome
2. Do pretty much anything, selecting chunks of code seems especially slow

Does this issue occur when all extensions are disabled?: Yes

With this theme in particular I'm getting ~4 fps on a 2014 MBP. I realize it's something to do with the theme (a few colors have opacity?) as others seem ok, but when I was profiling I noticed a 1000000x1000000 pixel layer. I'm wondering if this is a source of memory usage and css performance problems? I'm not sure how to get further information on how much impact a particular layer has.

<img width="1394" alt="Screen Shot 2020-05-28 at 3 27 00 PM" src="https://user-images.githubusercontent.com/25254/83154711-5fee2e80-a0f8-11ea-87c1-030edddb8055.png">

Looks like the source is from this:

```html
<div class="lines-content monaco-editor-background" style="position: absolute; overflow: hidden; width: 1e+06px; height: 1e+06px; transform: translate3d(0px, 0px, 0px); contain: strict; top: -1917px; left: 0px;"><div class="view-overlays" role="presentation" aria-hidden="true" style="position: absolute; height: 0px; width: 1556px;">
...
```

After poking around, seems like it's necessary. I'll close, it's still unclear why this theme is getting a few fps.

**Comment by tj** [comment] 2020-06-03 08:35
Re-opening because this makes no sense to me. This [monochrome theme](https://github.com/anotherglitchinthematrix/monochrome) performs dramatically worse than any other I have installed, but it's very unclear _why_, seeing as they are all just hex colors. This seems like potentially a fundamental issue with VS Code's DOM? I'm getting ~4 fps

**Comment by bpasero** [comment] 2020-06-09 06:54
`lines-content` seems to originate from the monaco editor, but I am not sure this is the source of the issue, moving to Alex.

Running with this theme, I am not seeing a huge slowdown to be honest, but I am on macOS 10.15.4, not sure that is relevant (you seem to be on a 3 year old macOS 10.12.x). 

Does it get any better if you run `code --disable-gpu` from the command line?

//cc @deepak1556

**Comment by tj** [comment] 2020-06-09 08:40
Yeah I can't upgrade my Mac OS for some reason, it doesn't like this old hardware. It seems a bit slower with `code --disable-gpu`, but if you and the team don't have any issues with it feel free to close, it's probably something weird with my machine

**Comment by fabiospampinato** [comment] 2020-08-01 20:48
I'm experiencing some issues because of that huge layer as well.

First of all the layers inspector in devtools just crashes for me.

Second I'm experiencing an issue where text is blurred under Windows, this only happens when:

- Monaco is involved
- Monaco instances are being rendered in floating things
- Those floating things are translated in the X axis
- The window of the app as a width that causes the floating thing to be positioned with decimal digits on the X axis (so like -300.5px)

It's a pretty weird issue but pretty important, one can't just show users blurry unusable text. I think this last issue originates from this massive layer that probably triggers some weird optimization or whatever in chromium.

Is this giant layer really necessary? Does it actually improve performance?

/cc @alexdima

**Comment by alexdima** [comment] 2020-08-05 13:15
@tj I could not reproduce the low FPS with the monochrome theme. I have tried "Monochrome Dark Subtle". AFAIK the very large layer is not problematic. I think browsers reduce the computations to the visible areas, otherwise compositing 1Mx1M pixels would take a very long time. I cannot say what would go wrong on your machine. Perhaps it is a bug of Chromium that occurs only on your GPU model. If you can check out vscode, it would be interesting to find out if the performance becomes 100 times better when replacing the `1000000` (1M) with `100000` (100k) in the editor here -- https://github.com/microsoft/vscode/blob/79e4925ae1e40d817ee148f131f000aa07482f70/src/vs/editor/browser/view/viewImpl.ts#L286-L287.

@fabiospampinato I don't think the lack of LCD text rendering (sub pixel anti aliasing) is caused by the large layer. IMHO this is most likely caused by your use of non-integer coordinates.
* See how long it took us to clean up our code and how we manage to constantly regress in this -- https://github.com/microsoft/vscode/issues?q=+label%3Alcd-text-rendering+
* See a good article about conditions which lead to Chromium to switch to gray-scale antialising --  https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/ :
  ![image](https://user-images.githubusercontent.com/5047891/67554251-4bcff200-f70f-11e9-9c92-4cbf4d26a692.png)
* If you have a lot of time, see https://bugs.chromium.org/p/chromium/issues/detail?id=1016062 and  https://github.com/w3c/csswg-drafts/issues/4560

**Comment by fabiospampinato** [comment] 2020-08-05 13:25
> @fabiospampinato I don't think the lack of LCD text rendering (sub pixel anti aliasing) is caused by the large layer. IMHO this is most likely caused by your use of non-integer coordinates.

@alexdima Yeah overriding the dimensions of the 1Mx1M layer via CSS didn't fix it for me. However I can't reproduce this same issue with other floating things if they don't have an instance of Monaco inside them too, I can see the issue very clearly when the floating thing is translated on the X axis by a non-integer amount, however that can't be the only factor at play here as I can't reproduce the issue when translating other floating things by the same amounts on the X axis, unless they have Monaco inside them.

I haven't been able to track down what other factor is tripping Chromium/Blink though 🤷 

Thank you for the pointers 👍

**Comment by alexdima** [comment] 2020-08-05 13:39
I think you are hitting https://bugs.chromium.org/p/chromium/issues/detail?id=1016062

In short, in order to fix https://bugs.chromium.org/p/chromium/issues/detail?id=934878 (where a transition animation would sometimes use LCD antialising and sometimes use grayscale antialising, which would cause a "wobble") , they have made it that if a layer uses `will-change: translate` or if a layer reaches a non-integer coordinate in its lifetime, it will be "locked" into grayscale anti-alising.

So it is not sufficient to have a layer at the beginning and at the end at integer coordinates, you need that animations avoid floats as well.

I'm also not 100% sure how long ago we shipped the Monaco Editor and if it avoid by now `will-change:`.

**Closed** 2020-08-12 16:51 UTC
Labels: freeze-slow-crash-leak, needs more info
