### ISSUE TITLE
Scrolling down does not work when cursor is over notebook output

### ISSUE THREAD

**Issue by lsoksane** [microsoft/vscode#174375] opened 2023-02-14 17:27 UTC
I can't scroll down using a trackpad in a Jupyter notebook when the cursor is over output of type application/vnd.code.notebook.stdout (as reported being currently active when I click change presentation). Scrolling up works, and scrolling both ways work when starting over image/png type output. 

Possibly related to this, scrolling using touch screen does not work up or down when starting dragging from an output of any of the above two types.  

Disabling/enabling all extensions does not affect the issue. 

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.0-60-generic
Sandboxed: No

**Comment by amunger** [comment] 2023-02-22 00:10
can you try creating an empty profile to and see if this still reproduces with default settings?
1. save a notebook that can repro the issue
2. `Profiles: create a temporary profile`
3. open that notebook and check if the issue persists
4. `Profiles: switch Profile` to get back to default and restore your settings

**Comment by lsoksane** [comment] 2023-02-22 06:57
Thanks a lot for looking into this! The issue does not reproduce with default settings. The setting that causes the issue is

``
    "editor.fontSize": 18,
 ``

This can not be reproduced with a temporary profile, it seems, since to reproduce the issue, Vscode needs to be restarted after changing the font size. To reproduce: 

1. Rename `~/.config/Code` to whatever to start with default settings
2. Change the font size (this does not affect the font size of output cells immediately)
3. Restart Vscode 

After the restart the font size of output cells has changed and scrolling stops working.

**Comment by amunger** [comment] 2023-02-22 16:41
thanks for the repro steps, that causes the issue for me, very strange.

It looks like this is already fixed in insiders though, at least I couldn't reproduce the issue there. So this should work fine if you download the latest insiders vs code, or when stable is released next week.

**Comment by amunger** [comment] 2023-02-22 17:03
never mind, just hit it in insiders

**Comment by amunger** [comment] 2023-02-22 23:50
It looks like the webview is not propagating the scroll event because of the check [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L364)

From debugging, it looks like we may have miscalcuated the scroll height or client height:
WillGoToParent is true - classList: output-stream | scrollTop: 0 | clientHeight: 285 | scrollHeight: 286

I noticed that I can only get this to repro when switching the font setting from 18 to 14, before reloading VS code, so this might not be the exact issue, but still very likely related.

**Comment by amunger** [comment] 2023-02-23 21:56
This should be improved in the next release (and already in insiders), but to fix it entirely we might just need to add a threshold as described here: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

**Closed** 2023-02-24 17:59 UTC
Labels: bug, notebook-builtin-renderers

**Comment by amunger** [comment] 2023-03-22 21:07
yes, just run a cell with something like
```
print(1)
print(2)
print(3)
```

and scroll with the mouse wheel while hovering over that output. Adjusting the editor.fontsize would be a good test as well, 14 to 18, then back to 14.

**Comment by andreamah** [comment] 2023-03-22 21:19
When changing the editor fontsize, should the output text also change in size? The scrolling seems to work well though!

**Comment by amunger** [comment] 2023-03-22 21:35
probably, but that's a different issue. The fact that it doesn't change was triggering this scrolling issue.

**Comment by andreamah** [comment] 2023-03-22 21:37
Should I create another issue for that? I notice that the font size for outputs is the same regardless of `editor.fontSize`

**Comment by amunger** [comment] 2023-03-22 21:42
https://github.com/microsoft/vscode/issues/178082
