### ISSUE TITLE
Changing language ID via javascript

### ISSUE THREAD

**Issue by AmitJoki** [Microsoft/vscode#40337] opened 2017-12-16 08:18 UTC
I am trying to develop an extension which requires me to change the language id in javascript. I did:
```
doc = vscode.window.activeTextEditor.document
doc.languageId = "html"
```

But seems like the doc.languageId remains unchanged. I tried searching the documentation but couldn't find a way to change the language id of the file.

How would I go about this?

**Comment by jrieken** [comment] 2018-01-03 10:17
dupe of #1800

**Closed by jrieken** 2018-01-03 10:17 UTC
Labels: api
