### ISSUE TITLE
Sections in Debug Viewlet not preserving height

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14719] opened 2016-10-30 20:44 UTC
- VSCode Version: 1.7 Insider
- OS Version: OS X 10.11.6

![debug](https://cloud.githubusercontent.com/assets/4033249/19839850/e95f66be-9ea6-11e6-90c3-badd5a47605c.gif)

**Comment by isidorn** [comment] 2016-10-31 07:11
I think this is by design of the split view, though assigning to @joaomoreno to get his input

**Comment by joaomoreno** [comment] 2016-10-31 08:39
Not necessarily by design, but by implementation. The previous time `Call Stack` was open it took up a bunch of space. So, when you expand it, it will try to return to that size, regardless of the other views. The rule is: _the view which the user just expanded will try to return to the size it has when it was about to be collapsed_.

**Closed by joaomoreno** 2016-10-31 08:39 UTC
Labels: debug
