### ISSUE TITLE
Put a picture in the code comments

### ISSUE THREAD

**Issue by heliocarbex** [microsoft/vscode#98194] opened 2020-05-19 18:04 UTC
It will be nice to add pictures in the code comments (base64 strings can be used).
Imagine that we can put more information in the code comments: "A picture is worth a thousand words" is a common phrase, to describe this. This feature can be used to clarify something etc. The VS Code editor must render the image to the developer.

**Comment by yume-chan** [comment] 2020-05-20 07:50
Duplicate of #41775 and #3220

**Closed** 2020-05-31 14:55 UTC
