### ISSUE TITLE
Invisible codicons on selected cell

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#126514] opened 2021-06-16 18:09 UTC
![image](https://user-images.githubusercontent.com/323878/122270338-0edfe280-ce93-11eb-8cf9-9e80c8da0e73.png)

Seems to come from https://github.com/microsoft/vscode/blob/97a719dd9b6f56ae724df1beb79944596d998eb6/src/vs/base/browser/ui/list/listWidget.ts#L759

Can this rule be more targeted?

**Comment by misolori** [comment] 2021-06-16 19:48
Yikes, this is inheriting from the list styles where our focus state inverts the foreground colors which we don't really use the same metaphor here. Let me see if I can override those styles in notebooks.

**Comment by misolori** [comment] 2021-06-16 20:31
I overwrote the default styles for `list.activeSelectionIconForeground` in notebook styles, similarly to how we override the default selection styles.

![image](https://user-images.githubusercontent.com/35271042/122288168-997e0d00-cea6-11eb-80cd-99153077bf01.png)


For verification: make sure that the icons (cell toolbar, folding, bottom toolbar) is visible when you have selection, focus, active, hover, and try all sorts of other combinations to break it.

**Comment by roblourens** [comment] 2021-06-18 23:36
This affects breakpoints

![image](https://user-images.githubusercontent.com/323878/122623905-ca9b4080-d052-11eb-9e1e-12e4e0d1666d.png)

which get their styling from a simpler rule:

https://github.com/microsoft/vscode/blob/f523f65f3985eb6493cae5d219de35f1d7ba6f7a/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L672-L672

Instead of finding different instances of codicons in lists and opting them out of this special rule, could we have lists opt into this behavior? Or, have a list opt out of this behavior but do it by setting or not setting a class on the list itself. Otherwise it feels like we will keep running into this

**Comment by misolori** [comment] 2021-06-19 20:02
@roblourens great point, just went and added a new options to the list, `useActiveIcons`, which is enabled by default and turned it off in the cases where we don't want this (notebooks & diff view, settings & toc).

@joaomoreno would love to know if this is the best way to do this, happy to tweak.

**Comment by joaomoreno** [comment] 2021-06-21 09:30
@misolori The list ctor already has a `overrideStyles` prop in the options. Can't those classes simply overload `listActiveSelectionIconForeground` to be `undefined`? That would remove the need for the strange `useActiveIcons` option, given that lists _should_ not know anything about icons or row's contents for that matter. Let me know what you think.

**Comment by misolori** [comment] 2021-06-22 04:17
Alright, I've gone ahead and removed the list option. Overriding the styles doesn't help in this case as it still picks up the default styles. 

For the cases where we style lists differently (notebooks ,settings editor) we'll just need to set `color: inherit` on the focus state icons instead. It's a trade off.

**Comment by roblourens** [comment] 2021-06-22 22:04
Another interesting case, the tree in the peek view

![image](https://user-images.githubusercontent.com/323878/123005450-ff690980-d36a-11eb-944f-1e57a3d08bb9.png)

This has a different background color, `peekViewResult.selectionBackground`

**Comment by misolori** [comment] 2021-06-22 23:01
I assume we want the peek view to match the default focus styling as well?

**Comment by roblourens** [comment] 2021-06-23 00:33
No idea

**Comment by roblourens** [comment] 2021-06-23 19:13
Also settings controls: https://github.com/microsoft/vscode/issues/127017

Why can't we make this an opt-in instead of an opt-out (I guess with styles, not a list option)? Whenever I implement something with a list, I have to add a special override style?

**Comment by misolori** [comment] 2021-06-23 19:50
IMO, it's more common to use the default list styles than it is to override them so it makes more sense to special case them in those situations. If there's a way to set these at the style level I'd be up to use that. Something like:

```ts
overrideStyles: {
    listActiveSelectionIconForeground: inherit,
    ...
},
```

@joaomoreno would something like this be possible?

**Comment by joaomoreno** [comment] 2021-06-24 13:26
What does inherit mean in that case? What foreground color would be used?

**Comment by misolori** [comment] 2021-06-24 13:46
That would simply set the color to "inherit" and ignores the focus state colors, which is what I'm currently doing via CSS in the cases where we override the default list styles. Would be nice to have that handled by the list widget.

**Comment by joaomoreno** [comment] 2021-06-24 14:55
Oh I see, literally `inherit`. Why exactly won't setting it to `undefined` work? Wouldn't that simply avoid creating the style altogether?

**Comment by misolori** [comment] 2021-06-24 16:46
I tried that, but the problem is there's a default list style (that is generic) that is still picked up:

<img width="700" src="https://user-images.githubusercontent.com/35271042/123300980-fa719a80-d4cf-11eb-9799-6b1e11c84309.png">

<hr>

Compared to a regular list item where a suffix overrides the default styles:

<img width="300" src="https://user-images.githubusercontent.com/35271042/123300760-be3e3a00-d4cf-11eb-9b00-576717b33172.png">

<hr>

So my thinking was if we introduced a way to cause the overrides to take a "inherit" property (or whatever name you'd want), it could fix these issues:


<img width="700" alt="CleanShot 2021-06-24 at 09 41 20@2x" src="https://user-images.githubusercontent.com/35271042/123301830-eda17680-d4d0-11eb-8270-a9d09489c3f6.png">

**Comment by joaomoreno** [comment] 2021-06-25 09:13
Ohh I see, let me reopen this so I don't lose it.

**Comment by joaomoreno** [comment] 2021-06-28 09:10
Hmm I couldn't find any low hanging fruit here. Maybe we need @aeschli's expertise... Given the bug is fixed, let's close it for now.

**Closed by joaomoreno** 2021-06-28 09:10 UTC
Labels: bug, list, notebook, themes

**Comment by misolori** [comment] 2021-06-28 22:56
For verification: 

Check that selecting/focusing a list item in the notebooks/settings editor/peek view properly shows the icons (test with breakpoints on notebooks)
