### ISSUE TITLE
WCO: black border under buttons

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150778] opened 2022-05-31 08:23 UTC
I see a black border under the WCO only in light themes:

![image](https://user-images.githubusercontent.com/900690/171127500-21a03f99-ad49-49f9-bb8c-5b51df316237.png)

**Comment by rzhao271** [comment] 2022-08-11 22:29
I'm unable to reproduce the issue on the latest Insiders. Are you still able to?

**Comment by bpasero** [comment] 2022-08-15 15:16
Weird, now seeing this again in my VM:

![image](https://user-images.githubusercontent.com/900690/184663116-10cf9b07-33ae-4e75-b902-ba0cd2879c9b.png)

But I still cannot really reproduce on my new Surface Laptop...

**Comment by deepak1556** [comment] 2022-08-15 15:24
Seems like an issue only when hw acceleration is disabled https://github.com/electron/electron/issues/31025

I could repro on windows hardware when running with `--disable-gpu`

**Comment by bpasero** [comment] 2022-08-15 15:26
Nice!

**Comment by bpasero** [comment] 2022-08-16 11:09
Actually I think I was also tricked by the fact that WCO was not enabled by default on Windows: https://github.com/microsoft/vscode/commit/2857051bb4e1bd7177c0d48b468b665c5a53b3c1

**Comment by Roundlay** [comment] 2022-08-24 02:38
Is this solely related to hardware acceleration?

I'm seeing the same black line under the window buttons in Code with GPU acceleration enabled, as well as in other Electron apps, namely Signal.

In Code's case, I see the black line under the window buttons in two situations:

- A permanent black line is visible when both `window.commandCenter` and `window.experimental.windowControlsOverlay.enabled` are set to `true`
- A temporary black line is visible for a brief moment, which disappears after restarting or launching Code, when `window.commandCenter` is set to `false` but `window.experimental.windowControlsOverlay.enabled` is set to `true`.

GPU acceleration was enabled when testing these parameters, but I am using 125% display scaling, which has been reported as a trigger by [others](https://github.com/electron/electron/issues/31025#issuecomment-939276974).

Here's the same issue in Signal:

![image](https://user-images.githubusercontent.com/4133752/186302937-ec2e06f3-89be-42fd-a05f-f5c081fa43aa.png)

**Comment by rzhao271** [comment] 2022-10-06 01:39
The upstream issue has been fixed by https://github.com/electron/electron/issues/35312.
VS Code also uses the change, so actually, this issue has been resolved.

Verification steps:
1. On Windows, enable WCO, and set the display scale to 125%
2. Use a light theme
3. Verify that under the WCO buttons, there's no black border

**Closed by rzhao271** 2022-10-06 01:39 UTC
Labels: bug, upstream, electron, titlebar, confirmed, upstream-issue-linked
