### ISSUE TITLE
Wrong references count

### ISSUE THREAD

**Issue by egorovsa** [microsoft/vscode#116650] opened 2021-02-14 15:05 UTC
- VS Code Version: Version: 1.53.2
- OS Version: MacOS Big Sur 11.2

Steps to Reproduce:

[https://prnt.sc/zhkq3w](https://prnt.sc/zhkq3w)

1. should be  "typescript.referencesCodeLens.enabled": true,
2. Create simple class like this
```
class A {
    public foo() {
        return void 0;
    }
}
```
2. Create instance of this class and call the `foo` method
```
const instance = new A();
instance.foo();

```
3. You will see that reference's counter become 1
4. now spread the instance and call the `foo` method again
```
const { foo } = instance;
foo();
```
5. no refs added

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2021-02-26 02:16
Duplicate of #117021

**Closed by mjbvz** 2021-02-26 02:16 UTC
