### ISSUE TITLE
[Bug] [TypeScript] Red "incorrect/error" angle bracket character with no reason

### ISSUE THREAD

**Issue by victoriaquasar** [microsoft/vscode#165029] opened 2022-10-31 02:56 UTC
## Summary

- **Does this issue occur when all extensions are disabled?**: Yes
- **VS Code Version**: 1.72.2
- **OS Version:** Windows_NT x64 10.0.19044

## Steps to reproduce

> **Note**
>
> Obs: There is no "generic" way to reproduce that behavior, I still can't figure the cause of the "error", but it is probably a thing with
> the method used by **VSCode** to deal with recursive types. All I could have is a exact, strutural remake of my function with different names.

> **Warning**
>
> This bug can produce undesired worst side effects and interactions. See the section **Interactions**.

**Step 1**:  Make a generic function (with at least one type argument), as the example:

![image](https://user-images.githubusercontent.com/70824102/198919137-6c4b140b-3aa4-4c3d-987b-855cf9998442.png)

**Step 2**:  Make an anonymous return type that returns the same method inside it, passing type arguments:

![image](https://user-images.githubusercontent.com/70824102/198920636-46d98754-db0e-4eb3-bbc9-a19494a4801a.png)

> **Note**
>
> There is no error, the character is just red. VSCode shows no problems, even in the scroll sidebar.
>
> <details>
> <br>
> 
> ![image](https://user-images.githubusercontent.com/70824102/198920850-97fbc262-ab88-4396-9362-fff6478fde3d.png)
>
> </details>

## Additional data

**That is my original code, where the bug appeared for the first time:**

```ts
function $<TInput, TReturn>(caller: ((a: TInput, ...args: any[]) => TReturn), ...args: any[]) {
    return caller(this, ...args) as TReturn & { 
        $: typeof $<TInput, TReturn> //<-- Bug location
    };
}

export { $ }
```

**The bug also occours in type declarations**:

![image](https://user-images.githubusercontent.com/70824102/198921460-15b277eb-6549-405c-ae28-76edaa6218a6.png)

> **Note**
>
> Also occours in these situations:
>
> ![image](https://user-images.githubusercontent.com/70824102/198921983-cad0c181-54f6-4cc6-963d-9f4cfe489098.png)
> ![image](https://user-images.githubusercontent.com/70824102/198922070-80efe5b5-3018-40d4-a4f0-75c9995fa8fc.png)

## Interactions

> **Warning**
>
> Jumping a line still occours and also remove the type highlight from the last type
>
> ![image](https://user-images.githubusercontent.com/70824102/198922189-3b120ea4-6702-4831-9289-c40e4b35df60.png)

> **Warning**
>
> Formating can give me unexcepted (or excepted, ignored by the first bug) errors
>
> ![image](https://user-images.githubusercontent.com/70824102/198922700-dfd74c60-c22b-404d-9eb4-50e53fe50dd4.png)

**Comment by wbt** [comment] 2022-11-11 18:28
Draft report I was going to file with title "Syntax highlighting: Failure to match angle brackets & parens with typeof parameterized function" using the TypeScript repo issue template, but which seems like a closer fit for this one, possibly as a duplicate of this (if you don't think so, it can be separated):

# Bug Report

### 🔎 Search Terms

syntax highlighting vscode match angle parens

### 🕗 Version & Regression Information, ⏯ Playground Link

- I am observing this in v1.73.1 of VSCode, and on v1.74.0-insider as seen [in this VSCode Playground link](https://insiders.vscode.dev/tsplay/#code/KYDwDg9gTgLgBDAnmYcAiwC2EAqzgA8AQgIxygzAB2AJgM5wBGEEANsAIZUA0cRATORCVaDZm05UAfHAC8AWABQACgFCR9OADMOrOqgD8cAK61gWgJZVgNOAC44ygErAYxqFTwoCypCghacACyiADyjABWAHSYiABiVMQkUgCUMgA+JmaW1jQpKQDcSkoAxhBUdPAh4RFycADeSgCQsQkOWqYlMBblxOrUmuLsXFLKsUQsrA5EKQ3NTVCu7lRw45NwRgAsgg4A5JVQVgDmLnSQFcC7RYpNAL7cxTexAMK67FDtnd29pP2iTJNJLw1BQBmJASMxogJmwSNMSLw1mx+NN+LNGjcmux4HQIJhgAA1XTGVAOVSCUH-HR6QxZGjmKw2eyOFxuDxeQi+fABYJhSIxeKJUipDJ0hm5fLXO4PRS3JRAA). 
- I was unable to test this on prior versions because I am not sure how to test different versions of TypeScript or VSCode in the VSCode version of the Typescript playground.

### 💻 Code


```ts
export type DemoType<B1 extends boolean, B2 extends boolean> =
(B2 extends false ? undefined : (ReturnType<(typeof MyObj.myFn<B1>)> | undefined));

const MyObj = {
	myFn: function<B extends boolean>(myBool: B) {
		return myBool ? 42 : 'stringResponse';
	},

	myCaller: function<B1 extends boolean, B2 extends boolean>(myBool1: B1, myBool2: B2) {
		let someValue : (B2 extends false ? undefined : (ReturnType<(typeof MyObj.myFn<B1>)> | undefined));
	},
}
```

### 🙁 Actual behavior
VSCode syntax highlighting for TypeScript fails to match the innermost angle-brackets around B1 (not recognizing the open-angle-bracket at all) and fails to correctly match parentheses, apparently as a result: 
![image](https://user-images.githubusercontent.com/563406/201402085-cb4a066b-7b16-4a6c-b2fe-9a146e9de3ae.png)


### 🙂 Expected behavior
The syntax highlighter recognizes the open angle bracket just before `B1` as matching the close angle bracket just after it, and provides better guidance if that syntax is actually wrong. 


See also: "[All greater-than signs (>) marked as "unmatched brackets" even when not part of a bracketed expression](https://github.com/microsoft/TypeScript-TmLanguage/issues/936)" filed 3 days ago on a repo with a bug report template referencing a broken link to an extension which doesn't show up as being installed in my VSCode environment.  Extensions vscode.typescript-language-features and vscode.typescript do show up, both at v1.0.0, under the search '@builtin typescript'.

**Comment by hediet** [comment] 2022-12-05 13:39
```
function test<A>() {
	return {} as {
		a: typeof test<A>
	}
}
```

![image](https://user-images.githubusercontent.com/2931520/205650898-0d78f475-501a-47e3-970f-aee2a5df13ff.png)


/duplicate #160115

**Closed by hediet** 2022-12-05 13:39 UTC
Labels: bug, editor-bracket-matching, bracket-pair-colorization
