### ISSUE TITLE
meteor occurs 'npm install error' while vscode insiders running

### ISSUE THREAD

**Issue by Dogyunjeong** [Microsoft/vscode#28013] opened 2017-06-05 02:03 UTC
- VSCode Version: 1.13.0-insider
- OS Version: windows 10

I'm using meteor and rocket.chat open source.

Steps to Reproduce:

1. Run vscode and editing files in meteor project
2. Do 'meter reset' on cm in meteor project  (I'm not sure it is necessary as sometimes error occured when doing just 'meteor run')
3. Put 'meteor run' on cmd in meteor proejct.
4. Meteor will occur 'error: couldn't install npm package @google-cloud/language@0.8.0: Command failed'. 

Before using vscode. It had been never appeared.
If I close vsocde and run meteor, it will work without error.

Thanks

**Comment by kieferrm** [comment] 2017-06-05 15:04
@Dogyunjeong Do you execute steps 2 and 3 in the integrated terminal in VS Code or outside?

**Comment by Dogyunjeong** [comment] 2017-06-05 15:08
Out side terminal.  I used cmd command

2017. 6. 6. 오전 12:05에 "Kai Maetzel" <notifications@github.com>님이 작성:

**Comment by bpasero** [comment] 2017-06-19 05:18
I suspect TS/JS locking folders due to file watching.

**Comment by Dogyunjeong** [comment] 2017-06-19 10:54
@bpasero Is lokcing by VS code?
  If I use atom or webstorm, Meteor works without any error.  What does makes this different?
  I do really want to solve this problem and use VS code as I feel it is much lighter than other editors.
  How I can figure out the solution or help you to solve it?

I found few more weird behaviors.
  1. If I modify only client side files in meteor project, Meteor refresh perfectly while running.  But not when I modify server side files.
  2. It takes much more times to refresh when I change server side files. Some times, it occurs error.

**Comment by bpasero** [comment] 2017-06-19 11:08
As far as I know, TypeScript is watching folders which can lock. I think the issue was reported as https://github.com/Microsoft/TypeScript/issues/7762

**Comment by Dogyunjeong** [comment] 2017-06-19 11:19
My meteor project has no TypeScript file. There is only one .ts file in '.vscode/typing/'.  Is my case included as well?

It seems VS code prevent that meteor build process as meteor always has problem due to 'building application' with Infinite running or errors.

Whenever I close VScode,  it work perfectly.

**Comment by Dogyunjeong** [comment] 2017-06-21 08:41
@bpasero 
  My project has no TypeScript file.  '.vscod' folder inside of the project has 'meteor.d.ts' file.
  Differently with #7762, I can change file name and add folders.

@kieferrm 
  What info should I give more?

I am newbie in programming as well. So if you tell me what info should I offer, I will happily do it.

**Comment by bpasero** [comment] 2017-06-21 08:46
@dbaeumer didn't you have a trick how to find out on Windows which process is locking a certain resource? Maybe we can find out by letting @Dogyunjeong run this tool to see what exactly locks the meteor files.

**Comment by dbaeumer** [comment] 2017-06-21 08:52
I used this tool https://technet.microsoft.com/en-ca/sysinternals/bb896655.aspx

**Comment by Dogyunjeong** [comment] 2017-06-26 02:20
`------------------------------------------------------------------------------
explorer.exe pid: 8228 DESKTOP-GLJDN6D\dogun
 282C: File          D:\Projects\ShouHan\web-app\packages\shouhan-ui-flextab\client\tabs
 2834: File          D:\Projects\ShouHan\web-app\packages\shouhan-ui-flextab\client\tabs
 2840: File          D:\Projects\ShouHan\web-app\packages\shouhan-lib\server\methods
 284C: File          D:\Projects\ShouHan\web-app\packages\shouhan-lib\server\methods
------------------------------------------------------------------------------
CodeHelper.exe pid: 8576 DESKTOP-GLJDN6D\dogun
   40: File          C:\Windows
   7C: File          C:\Program Files (x86)\Microsoft VS Code Insiders
  198: Section       \BaseNamedObjects\Cor_Private_IPCBlock_v4_8576
  19C: Section       \...\Cor_SxSPublic_IPCBlock
  2A0: File          C:\Windows\assembly\pubpol101.dat
  2CC: File          D:\Projects\ShouHan\web-app
  2F8: Section       \Sessions\3\BaseNamedObjects\NLS_CodePage_437_3_2_0_0
  328: Section       \BaseNamedObjects\__ComCatalogCache__
------------------------------------------------------------------------------
Code - Insiders.exe pid: 11396 DESKTOP-GLJDN6D\dogun
   40: File          C:\Windows
   7C: File          D:\Projects\ShouHan\web-app
   AC: File          C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_583b8639f462029f
  288: File          C:\Program Files (x86)\Microsoft VS Code Insiders\icudtl.dat
  2CC: File          C:\Program Files (x86)\Microsoft VS Code Insiders\snapshot_blob.bin
  2D4: File          C:\Program Files (x86)\Microsoft VS Code Insiders\natives_blob.bin
  2F8: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-11396
------------------------------------------------------------------------------
Code - Insiders.exe pid: 8816 DESKTOP-GLJDN6D\dogun
   40: File          C:\Windows
   7C: File          D:\Projects\ShouHan\web-app
   AC: File          C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_583b8639f462029f
   C0: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-8816
  280: File          C:\Program Files (x86)\Microsoft VS Code Insiders\icudtl.dat
  2C4: File          C:\Program Files (x86)\Microsoft VS Code Insiders\snapshot_blob.bin
  2CC: File          C:\Program Files (x86)\Microsoft VS Code Insiders\natives_blob.bin
  33C: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build\programs\.build406381.server
  40C: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build
  440: File          D:\Projects\ShouHan\web-app
  450: File          D:\Projects\ShouHan\web-app
  474: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build\programs\.build406381.server\assets\app\node_scripts
  478: File          D:\Projects\ShouHan\web-app\.meteor\local
  47C: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build\programs\.build406381.server\assets\app
  480: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build\programs
  484: File          D:\Projects\ShouHan\web-app\.meteor\local\.build681290.build\programs\.build406381.server\assets
  48C: File          D:\Projects\ShouHan\web-app\.meteor
  498: File          D:\Projects\ShouHan
  49C: File          D:\Projects
------------------------------------------------------------------------------
Code - Insiders.exe pid: 5860 DESKTOP-GLJDN6D\dogun
   40: File          C:\Windows
   7C: File          D:\Projects\ShouHan\web-app
   AC: File          C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_583b8639f462029f
   C0: File          C:\Program Files (x86)\Microsoft VS Code Insiders\snapshot_blob.bin
   CC: File          C:\Program Files (x86)\Microsoft VS Code Insiders\natives_blob.bin
  2A0: File          C:\Program Files (x86)\Microsoft VS Code Insiders\icudtl.dat
  2E8: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-5860
------------------------------------------------------------------------------
Code - Insiders.exe pid: 4328 DESKTOP-GLJDN6D\dogun
   40: File          C:\Windows
   7C: File          D:\Projects\ShouHan\web-app
   AC: File          C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_583b8639f462029f
  280: File          C:\Program Files (x86)\Microsoft VS Code Insiders\icudtl.dat
  2C4: File          C:\Program Files (x86)\Microsoft VS Code Insiders\snapshot_blob.bin
  2CC: File          C:\Program Files (x86)\Microsoft VS Code Insiders\natives_blob.bin
  2F0: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-4328
------------------------------------------------------------------------------
node.exe pid: 10040 DESKTOP-GLJDN6D\dogun
   44: File          C:\Windows
   8C: File          D:\Projects\ShouHan\web-app
  15C: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-10040
  30C: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db
  310: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db-wal
  314: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db-shm
------------------------------------------------------------------------------
cmd.exe pid: 880 DESKTOP-GLJDN6D\dogun
   44: File          C:\Windows
   80: File          D:\Projects\ShouHan\web-app
------------------------------------------------------------------------------
node.exe pid: 8020 DESKTOP-GLJDN6D\dogun
   44: File          C:\Windows
   80: File          D:\Projects\ShouHan\web-app
  164: Section       \Sessions\3\BaseNamedObjects\node-debug-handler-8020
  2A0: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db-shm
  2EC: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db
  2F0: File          C:\Users\dogun\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db-wal
------------------------------------------------------------------------------
mongod.exe pid: 11768 DESKTOP-GLJDN6D\dogun
   44: File          C:\Windows
   80: File          D:\Projects\ShouHan\web-app
  2A0: File          D:\Projects\ShouHan\web-app\.meteor\local\db\mongod.lock
  2CC: File          D:\Projects\ShouHan\web-app\.meteor\local\db\local.1
  2D0: File          D:\Projects\ShouHan\web-app\.meteor\local\db\local.ns
  2D8: File          D:\Projects\ShouHan\web-app\.meteor\local\db\local.0
  2E4: File          D:\Projects\ShouHan\web-app\.meteor\local\db\meteor.ns
  2EC: File          D:\Projects\ShouHan\web-app\.meteor\local\db\meteor.0
  2F4: File          D:\Projects\ShouHan\web-app\.meteor\local\db\meteor.1
  2FC: File          D:\Projects\ShouHan\web-app\.meteor\local\db\meteor.2
  4DC: File          D:\Projects\ShouHan\web-app\.meteor\local\db\diagnostic.data\metrics.2017-06-26T02-16-03Z-00000
------------------------------------------------------------------------------`

**Comment by Dogyunjeong** [comment] 2017-06-27 01:03
I think I made wrong click. I am coming to check and reopen it.

**Comment by mjbvz** [comment] 2017-07-07 23:06
I believe this is a duplicate of #28593

Please try out the [latest vscode insiders build](https://code.visualstudio.com/insiders) and let me know if you still see this issue

**Closed by mjbvz** 2017-07-07 23:06 UTC
Labels: duplicate, insiders, needs more info

**Comment by Dogyunjeong** [comment] 2017-07-08 14:39
It is working well. thank you!
