### ISSUE TITLE
Network using tasks hangup in integrated terminal

### ISSUE THREAD

**Issue by xen** [microsoft/vscode#232006] opened 2024-10-23 06:22 UTC
Does this issue occur when all extensions are disabled?: `Yes` and it can be reproduced on my environment 

- VS Code Version: Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

Steps to Reproduce:

1. Open terminal 
2. Run any task that require network connection
3. Very soon it hangup and connection is interrupted, timeout error shown

If I do the same task in any other terminal app on my laptop it runs smoothly until it is completed.

For me it little bit crazy as it sounds. I checked does it is related to CPU architecture, because I thought maybe I run Intel bash on silicon computer. But VS Code runs Apple processes. 

I tried this many times and was convinced that it is problem related to VS Code. If python or something needs to download a big file then 70% of the time connection will just drop and I get timeout. Feels like it allows to download only small files, if bigger than 10Mb then it will timeout. In other terminal apps it will run until the process completes its job.

VS Code task:

![Image](https://github.com/user-attachments/assets/8097b7d1-a1e4-42ac-b5d6-4e8a7c575077)

Same task in Terminal:

![Image](https://github.com/user-attachments/assets/181ee33e-ab0d-41be-b06d-a2cd33f71de2)

**Comment by xen** [comment] 2024-10-23 06:30
This is list of all installed extensions I have: 

```
adpyke.codesnap
adpyke.vscode-sql-formatter
ahmadalli.vscode-nginx-conf
amatlash.json-schema-validation-tool
attilabuti.vscode-mjml
batisteo.vscode-django
bradlc.vscode-tailwindcss
charliermarsh.ruff
cssho.vscode-svgviewer
davidanson.vscode-markdownlint
dionmunk.vscode-notes
donjayamanne.githistory
dotjoshjohnson.xml
editorconfig.editorconfig
equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
formulahendry.auto-rename-tag
github.copilot
github.copilot-chat
gitlab.gitlab-workflow
hangxingliu.vscode-systemd-support
humao.rest-client
jeffersonlicet.snipped
mechatroner.rainbow-csv
mikestead.dotenv
momoto.binary-viewer
ms-azuretools.vscode-docker
ms-python.autopep8
ms-python.black-formatter
ms-python.debugpy
ms-python.isort
ms-python.pylint
ms-python.python
ms-python.vscode-pylance
ms-toolsai.datawrangler
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.hexeditor
ms-vscode.remote-explorer
ms-vscode.remote-server
mtxr.sqltools
mtxr.sqltools-driver-pg
mtxr.sqltools-driver-sqlite
ninoseki.vscode-mogami
octref.vetur
pkief.material-icon-theme
quicktype.quicktype
raynigon.nginx-formatter
readbysearch.code2pdf
redhat.vscode-yaml
samuelcolvin.jinjahtml
tamasfe.even-better-toml
tchayen.markdown-links
tomblind.local-lua-debugger-vscode
tomoki1207.pdf
twolivesleft.codea-air-code
valentjn.vscode-ltex
visualstudioexptteam.intellicode-api-usage-examples
visualstudioexptteam.vscodeintellicode
vue.volar
waderyan.gitblame
wakatime.vscode-wakatime
yzhang.markdown-all-in-one

```

**Comment by xen** [comment] 2024-10-23 06:45
Just for explicitly: I disabled all extensions and inside VS Code getting timeouts, outside terminal app have no problems.

**Comment by meganrogge** [comment] 2024-12-11 16:49
If you're working in an environment with restricted network access, such as a corporate network or a secure VPN, it might be blocking the connection to files.pythonhosted.org.
The external terminal might not be subject to the same restrictions, or it may have different networking configurations.

Closing as I cannot reproduce so cannot investigate further

**Closed by meganrogge** 2024-12-11 16:49 UTC
Labels: bug, tasks

**Comment by xen** [comment] 2024-12-14 16:57
@meganrogge Difference is that the same command is working in system terminal like a charm. Only problem was in VS Code.
