### ISSUE TITLE
Dvorak-Qwerty Cmd binding is broken on Sierra

### ISSUE THREAD

**Issue by AnsonT** [Microsoft/vscode#24471] opened 2017-04-10 23:22 UTC
Dvorak-Qwerty Cmd keyboard layout maps Cmd/Alt/Ctrl keys to QWERTY layout so that shortcuts like Cmd-C/V/X/Z are laid out ergonomically. The latest VS Code breaks the cmd/ctrl/alt mapping - mapping these keys to their Dvorak layout rather than the QWERTY layout

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-dash|deerawan|1.4.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|vscode-npm-script|eg2|0.1.9|
|hive-sql|josephtbradley|0.0.2|
|Go|lukehoban|0.6.59|
|swagger-doc-viewer|mimarec|1.0.4|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|2.7.3|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1. Setup input source as Dvorak-QWERTY Cmd layout  in preferences
2. Cmd shortcuts are mapped to Dvorak layout and not QWERTY layout. (try Cmd+C (QWERTY location))

**Comment by alexandrudima** [comment] 2017-04-11 11:21
Duplicate of #23964

**Closed by alexandrudima** 2017-04-11 11:21 UTC
