### ISSUE TITLE
macOS full screen visual glitch when using VS Code

### ISSUE THREAD

**Issue by teki** [microsoft/vscode#68188] opened 2019-02-08 02:02 UTC
- VSCode Version: 1.31.0 
- OS Version: macOS 10.13.6, Intel UHD 630 and Radeon 560X (I think it uses the Intel one)

Steps to Reproduce:

1. do any editing in VS Code or switching tabs
2. the whole desktop flashes green/purple

Does this issue occur when all extensions are disabled?: Yes

Previous version of VS Code did this too occasionally, 1.31 made it happen all the time.

**Comment by bpasero** [comment] 2019-02-08 08:17
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by teki** [comment] 2019-02-10 22:18
@bpasero thanks for the response. I tried and it is better, but still produces the glitch. I have a suspicion that it is an Apple driver issue. I am not really sure that the error condition is reported back to Chromium, they might swallow it (or maybe the corruption is related to Thunderbolt, because the whole screen is glitching).

My usage case: MBPro with external display through USB-C->DP, lid closed. This is when the issue occurs. I can not screen record the issue, because that will "fix" it. An another way to avoid the issue is to open up the lid on my mac and use it as a second screen. (which I really don't want to, but at the moment this is the simplest workaround). I am planning to upgrade to Mojave soonish, I will report back from there too.

**Comment by teki** [comment] 2019-02-11 22:02
Okay, so I installed Mojave, nothing changed. But it is probably some low level problem, it happens in this combination: MBPro15 lid closed, USB-C -> Displayport cable, 4k Dell display, 60Hz output, scaling is set to 2560x1440.
The problem goes away if I do any of these: open the lid, change the Dell display to any of the MST streams (switching to 30Hz), change resolution scaling to any other value, start screen recording.

My guess would be that something misses a deadline in this combination and the output stream gets corrupted for 1-2 frames.

**Comment by methodbox** [comment] 2019-02-21 21:25
In my experience this issue occurs more often when Chrome is also running and seems less prevalent when VS Code is in full screen.

**Comment by cipri-tom** [comment] 2019-05-13 11:32
I can confirm @teki's findings ! 
I have the same setup, including cable and scaling rate. Just the display is different, I have an ASUS.

And indeed, opening the lid removes the problem, as does changing the scaling value. After all, choosing a scaled resolution is marked to imply some performance problems, but it is a shame that they only appear with VSCode 😢

**Comment by dlogik** [comment] 2019-05-29 11:27
I too have the same problem with lid closed. Opening rhe lid fixes the issue. 

Macbook Pro 2018 running Mojave 10.14.5 with external 4k display connected via USB-C
Radeon Pro 560X
VSCode 1.34.0

**Comment by methodbox** [comment] 2019-05-29 21:39
@bpasero Why is it that this same basic issue keeps having issues opened and closed and you reply to each with the exact same comment?

>We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:

- macOS: Download
- Linux: Download
- Windows: Download

It seems if you had actually fixed it at some point we wouldn't keep seeing this issue opened and users still confirming it's happening in the latest build.

I'm not trying to say you're avoiding it, but this has to be about the 10th or 11th thread I've seen for the same basic issue and your same response. I feel like maybe it's a bit of a cop-out to just point users to the latest version and close with no resolution.

**Comment by bpasero** [comment] 2019-05-30 06:59
@methodbox the truth is that we are not having sufficient resources to look into the issues that are reported which likely originate from Electron (or any dependent library actually) itself and not VSCode. We (as a team) can fix issues that originate from the source code that we (as a team) write. If an issue arises from code that we have not written we can only do an attempt to resolve the issue but we cannot give any guarantee to solve it.

Even though Electron is a major piece of VSCode, neither do we author any code in Electron, nor do we have a deep understanding of all the issues that can arise from using Electron. Best we can do is create issues in the [Electron repository](https://github.com/atom/electron) and hope for guidance from the Electron team.

Updating to newer Electron versions often means that there is a chance that some of the issues that fall into that category are resolved, so asking users to try out newer builds (VSCode Exploration) is the best strategy we currently have to deal with issues marked as "upstream" and "electron". That is because so much is changing in newer Electron versions, most specifically Chrome is changing.

I hope that clarifies my strategy for how I deal with these issues. I am open to discuss better ways of dealing with these issues. To give some numbers: I receive around 5-10 issues per day that possibly fall into this category (they all get assigned to me, yay). I mark these issues as [upstream](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aupstream) (often [electron](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron)) and my first question would always be to see if the issue is fixed in newer Electron versions. We have a label for that purpose (e.g. [fixed-in-electron-4](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afixed-in-electron-4.0.x)). If the issue still exists in latest exploration builds, then the issue is stuck. Best outcome is that someone from the community like you takes the lead on investigating the issue further and possibly reports it to Electron itself or finds the related issue in their repository.

**Comment by methodbox** [comment] 2019-05-30 12:49
@bpasero

Thank you for the clear and informative answer. I truly appreciate the honesty.

I 100% agree and believe this is an Electron issue, and actually specifically Chromium or their implementation of Chromium.

I started digging into bugs on both of those fronts yesterday and will post back here if any progress is made.

That said, your issue with them has been open for quite some time; why not prod them about this as it appears Electron is well aware it’s still an issue?

**Comment by alxgrtnstrngl** [comment] 2019-05-30 14:49
@bpasero I've been following this issue for a while. Is it possible to turn off specific GPU features like we can do in Chrome? I would be interested in seeing if you could selectively turn off something like 2d_canvas, flash_3d or rasterization and see if this is caused by a certain feature set.

```
GPU Status: 
                  2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
```

**Comment by methodbox** [comment] 2019-05-30 17:37
> @bpasero I've been following this issue for a while. Is it possible to turn off specific GPU features like we can do in Chrome? I would be interested in seeing if you could selectively turn off something like 2d_canvas, flash_3d or rasterization and see if this is caused by a certain feature set.
> 
> ```
> GPU Status: 
>                   2d_canvas:                    enabled
>                   checker_imaging:              disabled_off
>                   flash_3d:                     enabled
>                   flash_stage3d:                enabled
>                   flash_stage3d_baseline:       enabled
>                   gpu_compositing:              enabled
>                   multiple_raster_threads:      enabled_on
>                   native_gpu_memory_buffers:    enabled
>                   rasterization:                enabled
>                   surface_synchronization:      enabled_on
>                   video_decode:                 enabled
>                   webgl:                        enabled
>                   webgl2:                       enabled
> ```

I always reference this for Chrome flags; it's probably not the most up-to-date, but it has a great description of each. You **can** use these flags to disable rasterization, `--disable-gpu-rasterization`, and I've tried this with `--disable-gpu` but it doesn't seem to fix it for me.

I've posted this before, but to use this you can:

1. Windows - use it in the shortcut for VS Code on the "Target" field after the quotes, like this:
`"C:\Users\YourUserName\AppData\Local\Programs\Microsoft VS Code\Code.exe" --disable-gpu`

2. macOS - You have two options: run it at the command line every time, which gets old fast, or create an "app" with Automator which creates a "shortcut" that does this for you like this:
https://superuser.com/questions/16750/how-can-i-run-an-application-with-command-line-arguments-in-mac-os

I used option 2 for macOS and it clearly reduces the issue but it doesn't eliminate it entirely.

I've also experimented with `--cast-initial-screen-height` and `--cast-initial-screen-width` which does exactly as it sounds; the idea being that this issue seems to only occur on full-screen and appears to be related in some way to redrawing the window.

There's a number of GPU-related flags "disable-gpu-something" in that link I posted and any or all may affect performance positively or negatively; disabling 2D canvas is pretty bad actually and doesn't help.

**Comment by alxgrtnstrngl** [comment] 2019-05-30 22:38
Did some troubleshooting and testing and got some interesting results if I run `code-insiders --verbose --disable-accelerated-2d-canvas --disable-gpu-rasterization` using the latest Insider build I see a substantial improvement in flickers, still a few here and there but it's better. 

More stable:
```bash
$ code-insiders --version
1.35.0-insider
e9c50663154c369a06355ce752b447af5b580dc3
x64
$ code-insiders --verbose --disable-accelerated-2d-canvas --disable-gpu-rasterization
```

If I do the opposite and force enable rasterization and I see increased flickering even when not running in fullscreen and especially with native MacOS tabs turned on for some reason, not sure why.

Really bad:
```bash
$ code-insiders --verbose --force-gpu-rasterization --ignore-gpu-blacklist
```

I'm not sure `rasterization` is even needed because that's for faster image rendering right and `vscode` mainly renders text ? 

It also appears that getting GPU status is broken as these never change:
```bash
$ code-insiders --status
Version:          Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:18:06.502Z)
OS Version:       Darwin x64 18.6.0
Process Argv:     --verbose --disable-accelerated-2d-canvas --disable-gpu-rasterization
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

```



@bpasero Could you produce an Exploration build with Electron 4.0+ that disables `2d_canvas` and `rasterization`? I think narrowing this down by feature set is the key here. What's strange is that Slack and other Electron apps I run show none of these problems in fullscreen. So I think it has to be the way that `vscode` is using these features that's causing this.

**Comment by bpasero** [comment] 2019-05-31 04:54
**Re:** Could you produce an Exploration build with Electron 4.0+ that disables 2d_canvas and rasterization?

@deepak1556 @Tyriar  as far as I know it is possible to control GPU flags from the command line, no? Do you remember how to?

**Comment by methodbox** [comment] 2019-05-31 12:54
@deepak1556 @Tyriar

See my comment a few posts back for how to do what @bpasero is suggesting with command line arguments.

**Comment by alxgrtnstrngl** [comment] 2019-05-31 16:04
@bpasero @methodbox If these flags that applied earlier and today `--force-gpu-rasterization --ignore-gpu-blacklist` then I can confirm that today I'm not seeing any flickers or weird graphics glitches. Is there a way I confirm this within `vscode` developer tools or a logging flag that can show lower level logging other than the basic `--verbose`?

@bpasero What version of Electron is running in the latest Insiders build?

**Comment by bpasero** [comment] 2019-06-02 14:19
We are on `3.1.8` for Insiders and `4.2.2` for Exploration.

**Comment by cait08** [comment] 2019-09-11 14:12
I have encountered the same issue! At first I thought it was a problem with my graphics adapter, but I was able to get a screenshot of the issue, which suggests that things are being drawn to the display compositor incorrectly. It seems to come up for me when I have VS Code running and then open a second Terminal window- but only after I've been working for a while.

I'm using VS Code 1.38.0 on OSX Mojave 10.14.6. 

![Screen Shot 2019-08-14 at 09 10 01](https://user-images.githubusercontent.com/5309236/64704402-39aa3500-d47c-11e9-923a-e1845034e3c6.png)

**Comment by bpasero** [comment] 2019-10-10 06:02
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-10 06:02 UTC
Labels: electron, upstream
