### ISSUE TITLE
IME buffer texts blur on commit input

### ISSUE THREAD

**Issue by t7yang** [microsoft/vscode#166135] opened 2022-11-11 18:59 UTC
Type: <b>Bug</b>

1. install [Dark Lavender](https://marketplace.visualstudio.com/items?itemName=t7yang.dark-lavender) theme (this theme created by me).
2. open any git project.
3. start typing on the commit input using CJK IME.
4. the buffer texts are blur.

- this issue only occurs on "Dark Lavender", the built-in theme is fine.
- the issue only occurs on commit input, I tested on other inputs like global search input and extension search input, everything works fine.

as the theme creator, I can only provide UI and token colors, I don't know why only my theme has this issue and only happens on the commit input.

![vscode-ime-blur](https://user-images.githubusercontent.com/4502661/201411837-e018fcc5-c05c-4698-8574-4d87d4ed7997.png)

VS Code version: Code - Insiders 1.74.0-insider (ef415578d1b1019db585718968a303eeca4b8979, 2022-11-11T05:19:14.666Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (54.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.2
project-manager|ale|12.7.0
auto-add-brackets|ali|0.12.0
ignoregit|And|1.0.1
path-intellisense|chr|2.8.1
js-codeformer|cms|2.6.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
remotehub|Git|0.46.0
vscode-pull-request-github|Git|0.54.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
live-server|ms-|0.4.3
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.24.0
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5762
abracadabra|nic|6.16.0
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.22.0
toggle|reb|0.0.2
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
hyper-javascript-snippets|t7y|3.4.0
ghosttext|tok|1.1.0
errorlens|use|3.6.0
bracket-padder|via|0.3.0
vscode-conventional-commits|viv|1.24.3
gistfs|vsl|0.4.1
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment] 2022-11-25 21:08
Duplicate of #165682

**Closed by alexdima** 2022-11-25 21:08 UTC
Labels: editor-input-IME
