### ISSUE TITLE
Opening a terminal in Zenmode is jarring

### ISSUE THREAD

**Issue by SeamusConacher** [Microsoft/vscode#45265] opened 2018-03-08 08:40 UTC
- VSCode Version: 1.21
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Go into Zenmode (with center layout on)
2. Open the integrated terminal, configured to appear on the right
3. Observe that the editor shifts rather than staying centered.

Instead of filling in the empty space to the right of the editor, keeping the code I am looking at in the same place, it shifts the code to the left while keeping equal whitespace on the left and right of the editor. A similar thing happens if you open the explorer.

![zenmodeissue2](https://user-images.githubusercontent.com/16638857/37141138-00fdd4d8-22ac-11e8-9d4e-6b41ea896ba0.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-03-26 15:30
This is designed behavior, since otherwise the centered editor would grow shrink - which is not expected for some people. As they could file exactly the opposite bug.
For now closing as designed, if more people complained I will consder changing this

**Closed** 2018-03-26 15:30 UTC
Labels: as-designed
