### ISSUE TITLE
Commit name input focus changes in workspace

### ISSUE THREAD

**Issue by a2br** [microsoft/vscode#120505] opened 2021-04-04 13:41 UTC
- VS Code Version: 1.54.3
- OS Version: Windows 10

### Steps to Reproduce:

1. Open workspace
2. Stage changes
3. Start typing commit name
4. The changes are staged, the focus moves to the commit name input of the last folder of the workspace

Does this issue occur when all extensions are disabled?: **Can't check**: need 1 extension for WSL

### Footage of the bug

https://user-images.githubusercontent.com/62328077/113510604-eb77ed80-955b-11eb-8fa9-1f9a2e454e7a.mp4

#### Keywords
`git commit focus stage`

**Comment by eamodio** [comment] 2021-04-14 05:31
Duplicate of #116930

**Closed** 2021-04-14 05:32 UTC
Labels: *duplicate
