### ISSUE TITLE
Find with Selection steals keyboard focus

### ISSUE THREAD

**Issue by abhibeckert** [microsoft/vscode#69498] opened 2019-02-27 04:29 UTC
The "Find with Selection" command (which defaults to Command-E on Mac) opens the find panel and moves keyboard focus to the find panel's text field.

This is an operating system wide command on Macs and it should behave exactly the same as doing a "Copy" operation in copy/paste. Specifically:

1. It should not open the find panel or any other interface.
2. It should not move keyboard focus away from the text editing area.

Personally I'd be happy if just item 2 was resolved, but really they should both be fixed.

**Comment by briankendall** [comment] 2019-04-18 05:01
I came here to report the same thing. This is quite an irritating behavior for those of us who are used to the way Command-E works in every other app in macOS!

**Comment by nathany** [comment] 2019-06-07 22:26
This should also appear in the menu. Here are some examples -- also to portray how prevalent this feature is.

Xcode: Find > Use Selection for Find ⌘E
Sublime Text: Find > Use Selection for Find ⌘E
TextMate: Edit > Find > Use Selection for Find ⌘E
BBEdit: Search > Use Selection for Find ⌘E
Atom: appears to be missing this altogether
Day One: Edit > Find > Use Selection for Find
Apple Books: Edit > Find > Use Selection for Find ⌘E
(you get the idea)

Note that ⇧⌘E should be Use Selection for Replace to match other Mac apps.

**Comment by adrn** [comment] 2019-09-04 02:04
Also came here to report the same thing.

**Comment by rebornix** [comment] 2019-10-22 23:26
/duplicate of https://github.com/microsoft/vscode/issues/44093 and let's track it there.

**Closed by rebornix** 2019-10-22 23:26 UTC
Labels: editor-find, under-discussion
