### ISSUE TITLE
[html] format inside the script tag

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12972] opened 2016-09-29 05:21 UTC
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:
1. Select all the contents of an html file that has a script tag block somewhere in it (mine was at the bottom)
2. Run "Format Code"
3. Note that nothing inside the `<script>` tag was formatted.

This also is a problem in Stable, and Stable also has another problem where the selection no longer includes everything.

**Comment by dbaeumer** [comment] 2016-09-29 08:55
This never worked IMO.

**Comment by aeschli** [comment] 2016-10-11 13:22
Not a regression, the HTML formatter never touched the JavaScript.

**Comment by cliffkoh** [comment] 2016-10-20 07:52
This is a dupe of #5076.

**Comment by aeschli** [comment] 2017-02-07 10:10
Duplicate of #5076, implemented in the December build.

**Closed by aeschli** 2017-02-07 10:10 UTC
Labels: feature-request, html
