### ISSUE TITLE
Cannot list all the extensions currently installed in cmd

### ISSUE THREAD

**Issue by nizulzaim** [Microsoft/vscode#18480] opened 2017-01-13 01:17 UTC
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. run command `code-insiders --list-extensions`
2. it will only show up first line of extension and not all of currently installed extension

**Comment by mjbvz** [comment] 2017-01-13 01:29
Closing as a duplicate of #17343

**Closed by mjbvz** 2017-01-13 01:29 UTC
Labels: duplicate, extensions
