### ISSUE TITLE
dark overlay on top of sidebar

### ISSUE THREAD

**Issue by franzwcom** [Microsoft/vscode#68547] opened 2019-02-12 18:18 UTC
We have 
![vs_capture](https://user-images.githubusercontent.com/3803795/52658327-078f1f80-2efb-11e9-90e2-3e934822d6df.PNG)
Issue Type: <b>Bug</b>

dark overlay on top of sidebar

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:37:01.048Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.14GB free)|
|Process Argv|C:\webdev\franzwcom\franzwcom\pomegranate|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material-snippets|4tr|0.3.1
better-comments|aar|2.0.3
numbered-bookmarks|ale|6.1.0
markdown-preview-github-styles|bie|0.1.4
bracket-pair-colorizer|Coe|1.0.61
EditorConfig|Edi|0.12.8
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.8
Angular1|joh|0.2.0
Angular2|joh|7.0.1
dart|kev|0.1.0
Angular-BeastCode|Mik|7.2.2
mssql|ms-|1.4.0
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
quicktype|qui|12.0.46
meteorhelper|ram|0.1.5
vscode-icons|rob|8.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(11 theme extensions excluded)

</details>
e written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by isidorn** [comment] 2019-02-18 11:18
@franzwcom can you please provide exact reproducable steps for this? Thanks

**Comment by isidorn** [comment] 2019-02-18 14:05
Actually duplicate of https://github.com/Microsoft/vscode/issues/68494
But please provide steps tehre

**Closed by isidorn** 2019-02-18 14:05 UTC
Labels: file-explorer, needs more info
