### ISSUE TITLE
Decorated variables are marked as unused.

### ISSUE THREAD

**Issue by wYhooo** [Microsoft/vscode#51321] opened 2018-06-07 08:49 UTC
- VSCode Version: 1.24.0
- OS Version: Windows 10 17134

Decorated variables are marked unused and will be deleted after cleaning up code.

**Comment by mjbvz** [comment] 2018-06-07 22:21
Duplicate of https://github.com/Microsoft/TypeScript/issues/13120

**Closed by mjbvz** 2018-06-07 22:21 UTC
Labels: new release
