### ISSUE TITLE
why i can't edit write the vscode://defaultsettings/keybindings or defaultSettings??there is no such file on my disk!!!!!!

### ISSUE THREAD

**Issue by ShayCormac1963** [Microsoft/vscode#53218] opened 2018-06-28 08:10 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by V-ed** [comment] 2018-06-28 13:36
Duplicate of #51321

I'd suggest you to read the wiki page [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions), creating passive-aggressive issues isn't going to make your problem faster to resolve.

**Comment by roblourens** [comment] 2018-06-28 15:39
@ShayCormac1963 You can change keybindings and settings by changing your user keybindings.json and settings.json files. The defaults only exist in memory.

**Closed by roblourens** 2018-06-28 15:39 UTC
Labels: extensions
