### ISSUE TITLE
Configuring tab size independent of indention style, needed for Gnome code style

### ISSUE THREAD

**Issue by ebraminio** [microsoft/vscode#44438] opened 2018-02-26 20:05 UTC
Have a look at https://github.com/editorconfig/editorconfig-vscode/issues/190 also, it would be nice if VSCode could configure tab size independently from indention, which is needed for [Gnome mixed space/tab code style](https://github.com/GNOME/gtk/blob/master/docs/CODING-STYLE#L43-L54) (used on [harfbuzz](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-coretext.cc) project), consider this part of code,

```C
if (true) {
  if (true) {
    if (true) {
      if (true) {
	test();
      }
    }
  }
}
```

If you configure tab size to 8 in here viewing the code will be OK but if you try to insert a line in innermost `if` block, VSCode confuses the correct needed indention.

**Comment by ebraminio** [comment] 2018-10-13 17:15
Hey guys, anyone want to help on this? See https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-coretext.cc#L104 for example, it uses both tabs and spaces

**Comment by dlech** [comment] 2019-02-25 21:05
Duplicate of #10339

**Closed** 2019-10-24 16:50 UTC
Labels: *duplicate, editor-autoindent, feature-request
