### ISSUE TITLE
Keep suggestion widget open while cycling through options in "Tab Completion"

### ISSUE THREAD

**Issue by cBournhonesque** [microsoft/vscode#72999] opened 2019-04-28 14:28 UTC
(Related issues: https://github.com/Microsoft/vscode/issues/67795
is a related issue but it was simply not addressed. The answer given didn't address the problem.)

The "Tab Completion" mode for intellisense is very useful and does what most people expect when using autocompletion (and it is the setup used in all vim autocompletion plugins), i.e. to be able to select the best option + cycle through options using Tab.

This is independent from showing the suggestion widget while going through suggestions. The author of the TabCompletion future added as a side-effect the automatic closing of the suggestion widget while tabbing, which I personally find counter-intuitive because I like to be able to see how much I have to Tab to be able to reach the option I want.

I would like an option to keep the suggestion widget open while going through TabCompletion. Most autocomplete plugins work like this, so I find it weird that it is not possible to have the same behaviour in VSCode.

**Comment by jrieken** [comment] 2019-05-09 10:41
/duplicate of https://github.com/microsoft/vscode/issues/70532

**Closed** 2019-05-09 10:41 UTC
Labels: *duplicate, feature-request, suggest
