### ISSUE TITLE
Allow to customize word wrap for each language

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#2253] opened 2016-01-25 19:59 UTC
It would be interesting to have the ability to define different word wrap values for _different languages_, specially if you use **Code** for editing normal programming languages like JavaScript, Pascal and _non_ programming languages, like Markdown.

I tend to respect the word wrap values defined in the main IDE for a particular language (if exists/is used), and turn off word wrap for for Markdown/Log/Text files. But today, in **Code** I only have settings for the _Editor_  (`editor.wrappingColumn` and `editor.wrappingIndent`).

Thanks in advance

**Comment by axefrog** [comment] 2016-06-17 06:47
Agreed. This issue is also described in #6925.

**Comment by alexandrudima** [comment] 2016-06-17 07:42
@bpasero @aeschli Any thoughts here? The editor API can handle this as it's all dynamic anyways, we would need something in the configuration service.

**Comment by bpasero** [comment] 2016-06-17 09:57
Well, no further thinking has happening in this space. I think it boils down to finding a good syntax in our settings file so that you can express per language settings. We have not decided on a syntax to express this. Whatever we come up with also needs to support validation within, so it might be more tricky.

**Comment by jmm** [comment] 2016-06-24 15:34
@bpasero @alexandrudima I'm really confused: aren't keys named `{{language}}.something` in the settings file expressing per language settings? Example:

[JavaScript Configuration - Language specific settings](https://code.visualstudio.com/docs/customization/userandworkspace#_settings-file-sections)

```json
// Defines space handling after a comma delimiter
"javascript.format.insertSpaceAfterCommaDelimiter": true,
```

More specifically I saw an `html.format.wrapLineLength` prop in the default settings and tried to apply it to JS as `javascript.format.wrapLineLength` but it doesn't work. @nchammas also reported in #6925 that it doesn't even work for HTML.

```json
// Maximum amount of characters per line (0 = disable).
"html.format.wrapLineLength": 120,
```

**Comment by bpasero** [comment] 2016-06-25 15:29
That is true but we do not support this kind of configuration for other editor settings, hence this is a valid and still open feature request that needs thinking.

**Comment by micnic** [comment] 2016-10-09 20:46
It there any progress in this issue?

**Comment by mjbvz** [comment] 2016-11-11 23:28
Closing as a duplicate of #1587, which tracks a more general approach that would allow settings (including `editor.wrappingColumn` and `editor.wrappingIndent`) to be applied per language / file type.

**Closed by mjbvz** 2016-11-11 23:28 UTC
Labels: duplicate, feature-request, workbench
