### ISSUE TITLE
Task's Integrated Terminal Disappears On Completion If Opened In Editor WIndow

### ISSUE THREAD

**Issue by david-bakin** [microsoft/vscode#138682] opened 2021-12-09 00:21 UTC
Issue Type: <b>Bug</b>

GIven a task that looks like what I've pasted below: 

- If you have the setting `Terminal > Integrated: Default Location` set to `view` - then no problem; when task is complete the terminal hangs around and you get the "press any key" message to manually close it. 

- If, on the other hand, `Terminal > Integrated: Default Location` is `editor` then as soon as the task completes it closes its editor window and disappears with all its information.

- Expected behavior: Of course it should stick around even in the editor.

Task looks like this (also happens with different settings for `panel`, e.g., `shared`):

```
        {
            "label": "run tests",
            "type": "shell",
            "command": "./runTests",
            "args": ["debug"],
            "isBackground": false,
            "group": "test",
            "options": {
                "cwd": "${workspaceRoot}/test"
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": false
            },
            "problemMatcher": {
                   ... [elided] ...
                }
            }
        }
```

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.27GB (19.84GB free)|
|Process Argv|--crash-reporter-id 803341f5-7902-4a30-93f5-d1e0f2243486|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.86.241|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel(R) Xeon(R) CPU E3-1275 v3 @ 3.50GHz (8 x 1996)|
|Memory (System)|15.61GB (1.60GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.10
vscode-boost-jam|mlo|0.0.2
remote-containers|ms-|0.205.2
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.68.0
remote-wsl|ms-|0.58.5
doxdocgen|csc|1.3.2
githistory|don|0.6.19
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
better-cpp-syntax|jef|1.15.10
tws|jki|1.0.1
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0
vscode-print|pdc|0.9.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804:30404766
vscop453:30404998
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by alexr00** [comment] 2021-12-09 10:25
Duplicate of https://github.com/microsoft/vscode/issues/134533. With 1.63, task terminals are always forced to view until the terminal fix can be made.

**Closed by alexr00** 2021-12-09 10:25 UTC
