### ISSUE TITLE
Comments precondition not respected

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74554] opened 2019-05-29 13:19 UTC
Refs: https://github.com/microsoft/vscode/issues/74472

Have an extension (you can take the comment sample) that contribues the following in the `package.json`
```
{
					"command": "mywiki.startDraft",
					"group": "inline",
					"precondition": "commentThread == draft",
					"when": "commentThread != draft"
				}
```

Note that this action should always be disabled, since the precondition is the opposite of the when clause. However the action does not appear as disabled, but enabled

![Screenshot 2019-05-29 at 15 19 00](https://user-images.githubusercontent.com/1926584/58560293-1dfc8500-8225-11e9-8662-eb7a4433d677.png)

**Comment by RMacfarlane** [comment] 2019-05-29 17:00
Duplicate of https://github.com/microsoft/vscode/issues/74541, "precondition" should be "enablement"

**Closed by RMacfarlane** 2019-05-29 17:00 UTC
