### ISSUE TITLE
Cell overlap when dropping at top of notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119652] opened 2021-03-23 17:18 UTC
Testing https://github.com/microsoft/vscode/issues/119367

Drag cell 2 to become the first cell in the notebook. It overlaps with cell 1. Doesn't happen when not using the new markdown renderer.

![image](https://user-images.githubusercontent.com/323878/112189187-009a6700-8bc1-11eb-8aab-7218b4893e03.png)

**Comment by mjbvz** [comment] 2021-03-23 18:57
Duplicate of #119604

**Closed by mjbvz** 2021-03-23 18:57 UTC
