### ISSUE TITLE
specify tsconfig.json path

### ISSUE THREAD

**Issue by heartAndRain** [Microsoft/vscode#53639] opened 2018-07-06 03:32 UTC
Is it possible to specify the path of `tsconfig.json` if `tsconfig.json` is not in the root of the project?

**Comment by mjbvz** [comment] 2018-07-06 21:20
Duplicate of #12463

We detect `tsconfig.json` files in subdirectories as well (but they have to be named `tsconfig.json`)

**Closed by mjbvz** 2018-07-06 21:20 UTC
Labels: typescript
