### ISSUE TITLE
Focus on Terminal View on mouse hover

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#98475] opened 2020-05-24 18:59 UTC
I'm not sure if vscode already allows this or if it is already possible to focus on terminal view on mouse hover? And it would be nice to, **when you have multiple splitted terminals, you just change focus by hovering over them with the mouse.**

[Tilix](https://github.com/gnunn1/tilix) terminal has this feature.

Here are the settings for keybindings:

``` 
{
  "key": "",
  "command": "workbench.panel.terminal.focus"
}

{
  "key": "",
  "command": "workbench.action.terminal.focus"
}

```

Can i add something like a "mouse-hover" instead of "key"?

**Comment by Tyriar** [comment] 2021-02-02 15:05
The bot mishaved, it took 9 months to reach 20 upvotes whereas it's meant to only allow 2 months. Sorry to disappoint but I'm going to close the issue as it didn't reach that bar fast enough.

**Closed by Tyriar** 2021-02-02 15:05 UTC
Labels: feature-request, integrated-terminal

**Comment by phil-opp** [comment] 2021-02-02 15:55
@Tyriar Why do you think that it took 9 months? The announcement that 20 upvotes are needed was [made on Nov 5, 2020](https://github.com/microsoft/vscode/issues/98475#issuecomment-722085036) and less than three weeks later (on Nov 21, 2020) the [required number of upvotes was reached](https://github.com/microsoft/vscode/issues/98475#issuecomment-731493169). Or am I missing something?

**Comment by tifDev** [comment] 2021-02-02 22:30
> The bot mishaved, it took 9 months to reach 20 upvotes whereas it's meant to only allow 2 months. Sorry to disappoint but I'm going to close the issue as it didn't reach that bar fast enough.

Pls re-check this  @Tyriar 

Tyriar, we have reached the 20 upvotes well within the 2 months. I've been monitoring this close and there is also reddit to prove this.

**Comment by Tyriar** [comment] 2021-02-02 22:37
This actually duplicates https://github.com/microsoft/vscode/issues/44214, which was attempted and reverted in https://github.com/microsoft/vscode/pull/53963. We would only consider this as a workbench level feature, not just the terminal and it's closed as out of scope on that issue. Closing as duplicate.

**Comment by tifDev** [comment] 2021-02-02 23:55
> This actually duplicates #44214


Sorry but the justification that the bot gave for closing [#44214](https://github.com/microsoft/vscode/issues/44214) , for me it's not clear and valid (no wonder that it received 17 downvotes). 

> which was attempted and reverted in #53963


On that attempt that @alexdima  tried and reverted, was focus on hover for the **EditorGroup** not for the **terminal**.

Also, those references are from 2 years ago. Until now, what has been done taking into account this? Was there a change plan created for this or something? Because it looks like the community want this (not only from 2018, but also nowadays since my request received > 20 upvotes).

Can you pls re-check this and reopen **or** provide a more clear and valid justification?


If you need any help, pls tell me. 

@Tyriar

**Comment by Tyriar** [comment] 2021-02-03 12:55
I get you care about this but it's already been considered in https://github.com/microsoft/vscode/issues/44214#issue-299400073:

> Now that we can split editors and terminals I think it would be a good idea to have the ability to activate **editors/terminals** on mouse over.

As the owner of the terminal component I reject the idea that this should be a terminal only feature, it should apply to the editors as well at the very least. The PR revealed some usability issues with the feature and it was marked as out of scope by someone intimately familiar with the editor.

Realistically this would also not get prioritized for the team to work on so it would only come in via a PR, and we've already attempted and spent a bunch of time on it reviewing, testing and fixing in https://github.com/microsoft/vscode/pull/53963. It would also be a major feature in terms of work required to implement and maintain, but it would very rarely get used because it's an opt-in.

The bot helps us manage issues and it messed up here by not applying the feature request label and starting the timer in May, if it did maybe it would have reached 20 upvotes in time but I also made a mistake by not closing it out as a duplicate of https://github.com/microsoft/vscode/issues/44214 to begin with.
