### ISSUE TITLE
preserve scroll position is broken again

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#53662] opened 2018-07-06 07:22 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10 1803

Looks like preserve scroll position is broken again ( #22995 )

Steps to Reproduce:

1. Help / Release Notes
2. Scroll to the middle of document
3. File / Preferences / Settings
4. switch back to "Release Notes" tab

Expected: middle of document
Actual: begin of document

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-09-05 22:59
Duplicate of #45571

**Closed by mjbvz** 2018-09-05 22:59 UTC
Labels: bug
