### ISSUE TITLE
Focus should not auto switch to launch.json when resolveDebugConfiguration api returns undefined

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#56984] opened 2018-08-22 09:13 UTC
Currently, in `ConfigurationProvider#resolveDebugConfiguration` api, if it returns an empty value (e.g. undefined/null), VS Code will not continue the debug (i like this behavior), but in the meanwhile, it switches my focus to launch.json editor automatically. This is a little annoying.

In Java Debugger, we use `ConfigurationProvider` interface a lot. For example, force an incremental build before launching debug. If the build failed, and the user clicks `Abort` button, the debugger returns `undefined` to `resolveDebugConfiguration` api.  See the screenshot below. It switches my focus to newly opened launch.json automatically. The expected behavior is only stopping the debug, not changing my focus.

![launch json](https://user-images.githubusercontent.com/14052197/44453597-02c46f80-a62c-11e8-804c-988577048417.gif)

**Comment by octref** [comment] 2018-08-30 22:12
@isidorn How can I verify this? I tried making a failing `preLaunchTask` that runs tsc on an invalid ts file, but it's not the same thing.

@testforstephen It would be great if you could verify this is working for you in Insiders: https://code.visualstudio.com/insiders/

**Comment by testforstephen** [comment] 2018-08-31 02:04
this issue still exists in the insider version 2018-08-30 .

**Comment by isidorn** [comment] 2018-08-31 07:11
@testforstephen thanks for trying out, since the issue still exists, reopening and moving to september

**Comment by weinand** [comment] 2018-09-13 09:33
duplicate of #54213

**Closed by weinand** 2018-09-13 09:33 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2018-09-13 10:56
@testforstephen this should be fixed now in the next Insiders. See #54213.
If you return "undefined" nothing should happen with the editors. If you return "null" then the "launch.json" will be opened.

**Comment by testforstephen** [comment] 2018-09-14 01:42
The insider version below works as expected. Thanks for fix.
```
1.28.0-insider (system setup)
Commit: 8330a695712c43f861ce5c47533d82637d3cb374
Date: 2018-09-13T11:25:00.283Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
