### ISSUE TITLE
problems with the "live" replacement (search) in files

### ISSUE THREAD

**Issue by ZdurovAndrei** [Microsoft/vscode#12324] opened 2016-09-20 14:00 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:
1. Open the Search tab.
2. click the "sensitive"
3. To enter a word for search and replace
4. click the "Replace"
5. turn off the "sensitive"
6. No results found (but they exist). If you enter the word again, the search results there.

**Comment by chrmarti** [comment] 2016-09-20 16:29
Cannot reproduce on OSX or Windows 10. Could you provide text samples for which the problem is reproducible?

**Comment by chrmarti** [comment] 2016-10-31 17:00
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by chrmarti** 2016-10-31 17:00 UTC
Labels: needs more info
