### ISSUE TITLE
Autoimport/autocomplete not working after `yield` in generator functions.

### ISSUE THREAD

**Issue by inferusvv** [microsoft/vscode#97689] opened 2020-05-13 08:09 UTC
- Version: 1.45.0
- Commit: d69a79b73808559a91206d73d7717ff5f798f23c
- Date: 2020-05-07T15:57:33.467Z (5 days ago)
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0

Steps to Reproduce:

1. For example try to import automatically `take` function from `redux-saga` after `yield`:

<img width="423" alt="Снимок экрана 2020-05-13 в 11 04 29" src="https://user-images.githubusercontent.com/3227120/81787485-ccb6d580-9509-11ea-91a6-f137db857ccc.png">

While it works if no `yield` defined:

<img width="780" alt="Снимок экрана 2020-05-13 в 11 04 21" src="https://user-images.githubusercontent.com/3227120/81787513-da6c5b00-9509-11ea-8bb7-d235b7844520.png">

Does this issue occur when all extensions are disabled?:Yes

**Comment by mjbvz** [comment] 2020-05-19 02:21
Duplicate of https://github.com/microsoft/TypeScript/issues/36933

Fixes in VS Code insiders (1.46)

**Closed by mjbvz** 2020-05-19 02:21 UTC
