### ISSUE TITLE
scrolable element in jupyter notebook

### ISSUE THREAD

**Issue by Harshyduvnsi** [microsoft/vscode#190610] opened 2023-08-16 19:50 UTC
Type: <b>Bug</b>

when results of a jupyter notebook cell got bigger i tried to expand in scrolable element but that does not work and when sometimes i try to open in a text editor it says the file can't be opened.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.71GB (15.47GB free)|
|Process Argv|D:\\Projects\\AIW\\hard code --crash-reporter-id 54a3f11f-c4af-426c-8b00-ff4f4c1becce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-office|cwe|3.1.6
competitive-programming-helper|Div|5.13.0
prettier-vscode|esb|10.1.0
code-runner|for|0.12.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
vscode-language-babel|mgm|0.0.39
vscode-docker|ms-|1.26.0
csharp|ms-|2.0.376
vscode-dotnet-runtime|ms-|1.7.0
isort|ms-|2023.10.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.2
cpptools-extension-pack|ms-|1.3.0
vscode-thunder-client|ran|2.10.2
LiveServer|rit|5.7.9
wav-preview|suk|2.0.5
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscode-java-debug|vsc|0.53.0
vscode-java-dependency|vsc|0.23.1
vscode-maven|vsc|0.42.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by rebornix** [comment] 2023-08-22 20:12
/duplicate of https://github.com/microsoft/vscode/issues/189699

**Closed by rebornix** 2023-08-22 20:12 UTC
Labels: *duplicate
