### ISSUE TITLE
Flutter Auto child: Suggestion was not performed automatically

### ISSUE THREAD

**Issue by rajeshjeshar** [Microsoft/vscode#57433] opened 2018-08-28 15:16 UTC
Issue Type: <b>Bug</b>

Before updating Vs code 1.26.1 everything was working fine,after updating,i faced the follwoing issue while using flutter projects,

When i type "Row" then vscode will automatically show the next steps eg:
Row(<Widget>children[])

but after updating it started to show some white overlay rectangle highlights then i have to backspace the inside element from Row() then i have to retype Row(<Widget>Childre[])

this happened for all the widgets,  but after downgrading to  vscode 1.23.0 the issue is gone.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.14.0
flutter|Dar|2.14.0
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
php-debug|fel|1.12.5
php-intellisense|fel|2.3.4
php-pack|fel|1.0.2
python|ms-|2018.7.1
awesome-flutter-snippets|Nas|1.0.3

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment] 2018-08-29 09:35
@rajeshjeshar can you please provide a screen cast that demos this.

@bpasero could be an Electron issue since it appeared with VS Code 1.26.1 and it sounds like a rendering issue.

**Comment by rajeshjeshar** [comment] 2018-08-29 09:48
@dbaeumer  see this [video ](https://drive.google.com/open?id=1SSeHZ-E59OVaGyH0t0oLTdmAHgUSR0Q9)

**Comment by bpasero** [comment] 2018-08-29 09:55
@rajeshjeshar does it reproduce from this VSCode build that is a bit more up to date: https://az764295.vo.msecnd.net/exploration/94da7241d11facbcc6dcc551d9e63b6170b58525/VSCode-win32-x64-1.27.0-exploration.zip

**Comment by rajeshjeshar** [comment] 2018-08-29 10:12
@bpasero i faced this on 1.26.1,and i can't test with 1.27 as of now,
so when i test this above build i will update here!! thnks

**Comment by rajeshjeshar** [comment] 2018-08-29 12:09
@bpasero Sorry still the issue is still there in 1.27 explorer build,but not on 1.23 build

**Comment by dbaeumer** [comment] 2018-08-29 12:17
@rajeshjeshar can you provide us with a GitHub repository we can clone that demos this?

**Comment by bpasero** [comment] 2018-08-29 12:32
@rajeshjeshar to double check, you are talking about a visual glitch here not a functionality problem? hard to understand from the video

**Comment by rajeshjeshar** [comment] 2018-08-29 13:04
@dbaeumer Noooooooo....its a fucntionality problem only,

In the build of **1.23** if i tytpe `Row(C)`  then it will automatically show the Suggestion of `Row(Children<Widget>[])`

But after upgrading to both **1.26** and **1.27 Explorer version**, 
If i type `Row(C)` then it will not Show any Suggestion,
also i have to type the full word `Row(Children)` and i must have to delete the typed word `Children` 
Then Only it will show the Proper Suggestion for `Row()`


This HAPPENS For **All the Widgets**,not only for `Row` or `Column `compelete Flutter Code is Affected,
note:
I adjusted this issue for more than 15days,once i done my existing project immediately i gave a report (yesterday)
Now I've downgraded to 1.23 build It Has no problems it works smooth...
Pls Watch the Video which i  have provided above link for better Understanding

**Comment by rajeshjeshar** [comment] 2018-08-29 13:07
@dbaeumer This happens for all the Words i type in Vscode,not for a specific Project or file,if u need any more system informations,pls let me know,Now i'm working on 1.23 build without any issues

**Comment by bpasero** [comment] 2018-08-29 13:16
Ok, then this should be triaged again to someone else as it does not seem Electron related.

**Comment by dbaeumer** [comment] 2018-08-30 09:13
@rajeshjeshar does this happen for you in a fresh workspace folder with a single `TypeScript` file. What happens if you trigger code completer using `Ctrl+Space` after typing `C`. Will it bring up the list

**Comment by dbaeumer** [comment] 2018-08-30 10:09
@rajeshjeshar I will keep the issue open for a while to see if others complain.

**Comment by dbaeumer** [comment] 2018-09-04 09:38
I will close the issue. If someone sees this again please ping and we will reopen.

**Closed by dbaeumer** 2018-09-04 09:38 UTC
Labels: needs more info

**Comment by Larry-Liu2016** [comment] 2018-09-05 07:47
@rajeshjeshar I experienced the same issue after upgrading to version 1.26.1. It is solved after I reinstalled the latest version of flutter/dart extension.
