### ISSUE TITLE
Collapsed code shows misc characters

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#154835] opened 2022-07-11 17:43 UTC
Type: <b>Bug</b>

When using the down arrow to collapse nestings of code, odd characters appear at the end of line. 
To repro, take any indented chunk of code and collapse it, the same charactes will always appear at EOL. Images attached.
Only occurs when running inside OSS, cannot repro in stable or insiders. 

![image](https://user-images.githubusercontent.com/12552271/178324772-de854b97-c519-4b85-b194-fb917853e9db.png)
![image](https://user-images.githubusercontent.com/12552271/178324811-8c3c9337-013b-4744-957d-87d667776c10.png)

VS Code version: Code - OSS Dev 1.70.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.13GB free)|
|Process Argv|. --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --user-data-dir=C:\\Users\\t-mlively\\Documents\\_WORK\\vscode/.profile-oss --inspect=5875 --no-cached-data --crash-reporter-directory=C:\\Users\\t-mlively\\Documents\\_WORK\\vscode/.profile-oss/crashes --disable-features=CalculateNativeWinOcclusion --remote-debugging-port=9222|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment] 2022-07-12 07:56
@Yoyokrazy Yes, we are also puzzled, looks like a Chrome bug. We suspect it's related to the dev tools being open. Did you have the dev tools open?

Duplicate of https://github.com/microsoft/vscode/issues/145897

**Closed by aeschli** 2022-07-12 07:56 UTC

**Comment by Yoyokrazy** [comment] 2022-07-12 17:33
Yep, I was using the dev tools. I did notice that I couldn't repro on OSS a couple minutes later, I might've closed dev tools by then. Let me see about using dev tools and seeing if it happens again
