### ISSUE TITLE
split view content pushed down when content inserted above

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#32588] opened 2017-08-15 19:45 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gitlens|eam|4.3.3
macros|ged|1.2.0
mssql|ms-|1.1.0
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.7
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. open a file ( > 100 non-blank lines)
2. View->Split Editor
3. scroll left window to top, right window to bottom
4. insert new lines at top of left window: notice that right window content is pushed down
5. paste a large number of lines at top of left window: notice that the right window content has completely changed.

Visual Studio & Eclipse do the right thing here, scroll the other windows to keep the content stationary.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-04-27 10:08
Duplicate of #46455

**Closed by alexandrudima** 2018-04-27 10:08 UTC
Labels: editor-rendering, feature-request
