### ISSUE TITLE
Word Wrap Issue !

### ISSUE THREAD

**Issue by Znoy108x** [microsoft/vscode#172406] opened 2023-01-25 16:17 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

**Can anyone tell me how to solve this word wrap issue in line number 42 , 43 , 44 ??** 
![image](https://user-images.githubusercontent.com/75539409/214616776-6fb19610-2744-48bc-ba46-32ab61f69f74.png)

**Comment by alexdima** [comment] 2023-09-15 14:03
Duplicate of #32856

**Closed by alexdima** 2023-09-15 14:03 UTC
