### ISSUE TITLE
'Join Lines' triggers unexpected pasting of text

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#32775] opened 2017-08-18 10:45 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.1.14
python|don|0.7.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
blank-line-organizer|rin|0.1.2
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Start VS Code with no files open.
2. Ctrl + N to start a new plain text document.
3. Type some words on two lines.
4. Select all.
5. Issue the command 'Join Lines'.
6. With the text still selected, click on some other application window to give focus to that other application.
7. Click back in the whitespace of the editor of VS Code.
8. Notice that the selected text gets pasted for some reason, at the end of what was previously selected.
9. Thereafter (i.e. once this bug has been triggered), if you simply select text, click on some other window, and then click back in VS Code, that text will get pasted. Most times.

Starting with all extensions disabled makes no difference.

Reproduces without extensions: Yes

**Comment by Eldaw** [comment] 2017-09-15 10:25
I really hope it can be fixed soon. Getting unintended text pasted automatically into the current file is quite a problematic bug.

**Comment by mlimber** [comment] 2017-10-05 19:13
I occasionally see text pasted at the top of my file, overwriting some text there. It may be this same problem. I don't have great repo steps yet.

**Comment by Eldaw** [comment] 2017-11-10 20:03
Bug is still present in 1.18.0

**Comment by alexandrudima** [comment] 2017-11-13 11:46
I cannot reproduce:

![32775](https://user-images.githubusercontent.com/5047891/32724193-9c4d224a-c870-11e7-8efe-47d0276c64f8.gif)

**Comment by Eldaw** [comment] 2017-11-13 13:05
@alexandrudima 

No, nothing else on my machine is interacting with input. Looking at your animated gif, it looks like you are not doing the same thing as me though.

Once you've joined lines in VS Code, simply click the title bar of another application and then click into the whitespace in VS Code again, just after the existing text there which is still selected. Don't type anything or do anything in the other application.

When I do my test, on one monitor I have VS Code and on the other monitor I have a maximized Chrome window which I'm giving focus to before clicking back in VS Code.

I can reproduce the issue on all of my machines.

**Comment by Eldaw** [comment] 2017-11-13 13:40
@alexandrudima Further to my previous comment, I've created a GIF to demonstrate the problem. Note that I'm not copying or pasting at any time in this video -- I'm simply clicking on one window and then clicking on the other window.

![text](https://user-images.githubusercontent.com/3789849/32728337-dad32e7c-c877-11e7-9c01-423e52766aef.gif)

**Comment by alexandrudima** [comment] 2017-11-13 13:55
I see it, and I believe it happens, but even after doing the exact same steps as you, I still cannot reproduce:

Here I am doing it in a VSCode instance **with the default settings and without extensions**:
![32775-part2](https://user-images.githubusercontent.com/5047891/32728978-9aec4f9a-c882-11e7-9ecb-ce11dfc6ead6.gif)

Does this reproduce for you with out-of-the-box settings and without extensions? How about when disabling `"editor.dragAndDrop"` ?

**Comment by Eldaw** [comment] 2017-11-13 15:07
Hi @alexandrudima 

OK, I did some more tests:

Starting **without extensions and with default settings**: the same problem still occurs.

Setting **"editor.dragAndDrop": false**
solves the problem.

So it appears that the combination of the default setting '**"editor.dragAndDrop": true**' and **'Join Lines'** is what triggers the bug.

After doing 'Join Lines' the only way to get it to stop doing the unexpected pasting is to quit VS Code and restart it.

**Comment by rebornix** [comment] 2017-11-13 21:55
I can reproduce and I'm surprised to see it's a window only issue. Thanks @Eldaw , good catch.

**Comment by rebornix** [comment] 2018-09-07 23:05
I no longer see this issue anymore. Close it for now but if you can still reproduce, we can reopen it. Thanks!

**Closed by rebornix** 2018-09-07 23:05 UTC
Labels: bug, editor-drag-and-drop, windows
