### ISSUE TITLE
Extension host restarts

### ISSUE THREAD

**Issue by danieloi** [microsoft/vscode#176579] opened 2023-03-09 01:01 UTC
Type: <b>Bug</b>

I get an error that says my extension host has restarted 3 times in 5 minutes

Reloaded my window once with the command palette before it started happening

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (3.12GB free)|
|Process Argv|--crash-reporter-id 2464a9cb-77c0-4d84-b981-095ad2bce35a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
vscode-color|ans|0.4.5
vscode-zipfs|arc|3.0.0
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
vscode-expo|byC|0.9.2
doxdocgen|csc|1.4.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
composer-php-vscode|DEV|1.31.12740
phptools-vscode|DEV|1.31.12740
profiler-php-vscode|DEV|1.31.12740
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4
vscode-firefox-debug|fir|2.9.8
foam-vscode|foa|0.21.1
code-runner|for|0.12.0
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
go|gol|0.38.0
gc-excelviewer|Gra|4.2.56
vscode-graphql-execution|Gra|0.1.8
vscode-graphql-syntax|Gra|1.1.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
ts-debug|kak|0.0.6
vscode-codemetrics|kis|1.26.1
vscode-markdown-notes|kor|0.0.26
vscode-clangd|llv|0.1.23
Kotlin|mat|1.7.1
ruby-rubocop|mis|0.8.6
theme-monokai-pro-vscode|mon|1.2.0
vscode-docker|ms-|1.24.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5834
vsliveshare-audio|ms-|0.1.93
vscode-react-native|msj|1.10.2
prettier-standard-vscode|num|1.0.2
tachyons|oct|0.3.0
prisma|Pri|4.11.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
swift-lang|ssw|1.1.0
rewrap|stk|1.16.3
markdown-links|tch|0.8.0
serverless-ide-vscode|Thr|0.6.1
vscode-status-bar-format-toggle|tom|3.1.1
hosts|tom|1.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-maven|vsc|0.40.4
vscode-icons|vsc|12.2.0
vscode-ruby|win|0.28.0
eno|Wsc|2.3.53
markdown-all-in-one|yzh|3.5.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
6233i204:30672705
vsccsb:30677849

```

</details>

**Comment by jonodavis** [comment] 2023-03-09 02:22
+1, happening to me too on WSL

**Comment by isidorn** [comment] 2023-03-15 11:25
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:25 UTC
Labels: freeze-slow-crash-leak, extension-host
