### ISSUE TITLE
Ctrl + Click => Word Select

### ISSUE THREAD

**Issue by YunHeeCheol** [microsoft/vscode#130753] opened 2021-08-13 08:06 UTC
It was such a convenient function in visual studio, but it's too bad that visual code didn't support it.
The speed of code editing is too different.

**Comment by IllusionMH** [comment] 2021-08-17 12:16
/duplicate of #27905

Please upvote that issue.
Also VS Code has "select word" (but selection boundaries can be different) on double click, and select line on triple click already.

**Closed** 2021-08-17 12:17 UTC
Labels: *duplicate
