### ISSUE TITLE
Copy should give me the same action regardless of how I execute it

### ISSUE THREAD

**Issue by hakanai** [microsoft/vscode#167909] opened 2022-12-02 08:22 UTC
Whether I use copy:
- via the Edit menu
- via the context menu
- via hitting Ctrl-C

I should get exactly the same action and exactly the same behaviour.

The same presumably applies to things like Cut, Paste, ...

I had reported [an issue with Copy in the Hex Editor extension](https://github.com/microsoft/vscode-hexeditor/issues/355) which exposes dramatically different behaviour between Ctrl-C and Copy via the context menu.

I don't know what the fix looks like, because I don't know the application architecture, but letting extensions override Ctrl-C sounds like a bad idea to me and a good start to normalising this. Extensions should be able to override the context which gets copied, when the action is performed.

**Comment by mjbvz** [comment] 2022-12-02 20:25
Duplicate of #141080

**Closed by mjbvz** 2022-12-02 20:25 UTC
Labels: triage-needed
