### ISSUE TITLE
Find and replace all open/pinned files in current session

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#443] opened 2015-11-22 10:32 UTC
replace all in session might be a good option should you choose to keep it

**Comment by Tyriar** [comment] 2016-05-28 01:59
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/1690

**Comment by thewhitetulip** [comment] 2016-05-28 06:58
No it isn't, they were asking for a project level find and replace, I am asking find and replace on all open files @Tyriar

**Comment by Tyriar** [comment] 2016-05-28 20:38
Ah understood.

**Comment by roblourens** [comment] 2018-09-22 01:07
I think this is covered by https://github.com/Microsoft/vscode/issues/20530 - search in a particular set of files, such as just open files, and replace would work on the same subset. Let me know if I misunderstand.

**Closed by roblourens** 2018-09-22 01:07 UTC
Labels: feature-request, search
