### ISSUE TITLE
Drop event of file dragged from File Explorer lost when on secondary monitor

### ISSUE THREAD

**Issue by WasabiFan** [Microsoft/vscode#16453] opened 2016-12-04 07:39 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 Insider Preview build 14971

Steps to Reproduce:

1. Find a Windows 10 PC with dual monitors. I suspect that the two monitors must have different DPI/scaling settings.
2. Run VS Code on one monitor.
3. Drag a file from Windows' File Explorer into the explorer pane in Code.
4. Either:
    - The file is successfully copied to the open folder in Code and the application resets to normal. If so, move VS Code to the other monitor and restart at step 1.
    - The file is not copied, and the explorer pane maintains the light background that indicated that it was a drop surface. Clicking out of the pane or selecting other items does not resolve this state, and one must reload the workspace.

I have a primary 4K monitor at 150% DIP scaling and a 1080p monitor at 100%. I see this issue when Code is on my secondary monitor, but not when it's on my primary. It looks like some variety of coordinate translation isn't working correctly and as a result the drop event doesn't register; this leaves it in a "limbo" state waiting to receive an event.

It's worth noting that, when this bug is encountered, everything _looks_ normal until the drop doesn't register. The app successfully detects the drag beginning and highlights the drop area as expected. This is how it looks afterward:

![image](https://cloud.githubusercontent.com/assets/3310349/20864745/37df5bb8-b9b0-11e6-9ccb-f8a2f05bf9e8.png)

There are no useful log items in the dev console. Unfortunately, I can't get a GIF of this because the apps I normally use for that have issues with DPI transitions too :laughing:

**Comment by bpasero** [comment] 2016-12-04 07:59
@WasabiFan 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by WasabiFan** [comment] 2016-12-04 08:08
No problem! It still repros with the current insider build. I know the feeling, though -- no idea how to troubleshoot a bug so you hope that it goes away in a dev build :laughing:

**Comment by bpasero** [comment] 2016-12-04 08:45
@WasabiFan that is not true, our insider build contains an Electron update that specifically fixes many issues around DPI on Windows.

**Comment by WasabiFan** [comment] 2016-12-04 09:12
IIRC, all the DPI-related changes for the past few months were about pure scaling factors on single displays; in this case, it seems to be specifically caused by multiple displays, and it's on a monitor that _isn't_ scaled. Either way, the insider build with Electron 1.4.6 still exhibits the same behavior, so we know that it hasn't been fixed upstream as of that release.

**Comment by WasabiFan** [comment] 2016-12-04 09:46
Also, it's worth pointing out that this happens even if the Code window was started on the same display as this occurs (without moving it between displays) so this isn't an issue of missing transition messages. It seems like there's probably an assumption in either Electron or the VS Code codebase that the DPI of the "primary" screen == DPI of all screens. That's just an educated guess, though.

**Comment by alexandrudima** [comment] 2016-12-06 10:37
Assigning both of you since bugs need an owner

**Comment by joaomoreno** [comment] 2016-12-06 10:56
I meant to leave myself as an owner, sorry!

**Comment by joaomoreno** [comment] 2017-11-23 14:18
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Closed by joaomoreno** 2017-11-23 14:18 UTC
Labels: bug, tree, workbench-dnd
