### ISSUE TITLE
Ctl-Click no longer creates a new file for me

### ISSUE THREAD

**Issue by rich-fts** [microsoft/vscode#129262] opened 2021-07-23 18:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 Pro Build 19043.1110

Steps to Reproduce:

1. Create a markdown file with a link in it to another markdown file that does not exist
2. Ctrl-Click on the file name

This behavior used to offer to create a new file with the name that was clicked on.  Now it does nothing.  If the file exists, control transfers to that file which is the expected behaviour, but I used to create my files by following the above steps and that no longer works.

**Comment by lifez** [comment] 2021-07-26 04:56
I will work on this.

@mjbvz Do you have any clue?

**Comment by mjbvz** [comment] 2021-08-12 23:08
Duplicate of #113475

**Closed by mjbvz** 2021-08-12 23:08 UTC
Labels: help wanted, markdown
