### ISSUE TITLE
Intellisense for node modules shows one module multiple times

### ISSUE THREAD

**Issue by weeco** [Microsoft/vscode#36291] opened 2017-10-15 02:26 UTC
Well, this screenshot pretty much explains the issue I am experiencing with VSCode: https://i.imgur.com/S6bxFto.png

The intellisense for importing modules shows the installed modules a couple times and I am not sure why this is the case. I think I am experiencing it since 1.17.0

This is my vscode version: https://i.imgur.com/VdwUL2k.png

**Comment by mjbvz** [comment] 2017-10-15 18:48
Tracked by https://github.com/Microsoft/TypeScript/issues/13373 upstream

Closing as duplicate of https://github.com/Microsoft/TypeScript/issues/13373

**Closed by mjbvz** 2017-10-15 18:48 UTC
Labels: javascript, upstream
