### ISSUE TITLE
Application Hang

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#12866] opened 2016-09-28 07:40 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

I have no exact way to reproduce the hangs. I may have to do with active extensions as well. The only thing I can see that the code highlighting in javascript seems to stutter.
From the event log I get only this 

```
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Hang" /> 
  <EventID Qualifiers="0">1002</EventID> 
  <Level>2</Level> 
  <Task>101</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-09-26T14:50:18.012063900Z" /> 
  <EventRecordID>64935</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>redacted</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Code.exe</Data> 
  <Data>1.5.3.0</Data> 
  <Data>32e60</Data> 
  <Data>01d218052d7bd626</Data> 
  <Data>4294967295</Data> 
  <Data>C:\Program Files (x86)\Microsoft VS Code\Code.exe</Data> 
  <Data>892bc4a3-83f8-11e6-9c4c-5cf3706d09ba</Data> 
  <Data /> 
  <Data /> 
  <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary> 
  </EventData>
  </Event>
```

**Comment by con-ssc** [comment] 2016-09-28 07:46
I'm mostly working with .js files, the frequency of hangs increase if I have linters or codelenses on.

**Comment by joaomoreno** [comment] 2016-09-28 07:48
Can you reproduce when disabling all extensions?

**Comment by con-ssc** [comment] 2016-09-28 07:51
Maybe, but since I cannot force it to freeze this could take some time. Is there a way to better log those crashes other then the event viewer of windows?

**Comment by egamma** [comment] 2016-09-28 07:53
// @kieferrm since we have discussed serviceability for such scenarios.

**Comment by con-ssc** [comment] 2016-09-28 07:56
Would devtron help to maybe get more info out of vscode?

**Comment by con-ssc** [comment] 2016-09-28 08:00
Just to add this again, "Reopen" doesn't work in this scenario neither.

**Comment by bpasero** [comment] 2016-09-28 08:13
@con-ssc when it hangs, is the CPU of any process high? if so, can we find out which process goes high?

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx?f=255&MSPPError=-2147217396)** helps.

Once you have the information please update this issue with it. Thanks!

**Comment by con-ssc** [comment] 2016-09-28 08:16
I actually have a screen of that, here [Process Explorer Screenshot](https://github.com/Microsoft/TypeScript/issues/10133#issuecomment-247342197) but what info do you exactly need? And also, how can I identify the thread that is causing the issue since they all look the same?

**Comment by bpasero** [comment] 2016-09-28 08:18
@con-ssc best, the full command line of the process that has high CPU to find out if this is an issue with the renderer, extension host or other process. If you hover over the process in the tree with high CPU, I think process explorer would show you

**Comment by con-ssc** [comment] 2016-09-28 08:19
Do you also want a dump file?

**Comment by bpasero** [comment] 2016-09-28 08:26
@con-ssc lets start first by finding out which of the processes is running with high CPU load when this happens.

**Comment by con-ssc** [comment] 2016-09-28 08:27
I'm monitoring with sysinternals Process Monitor now.

**Comment by con-ssc** [comment] 2016-09-28 08:40
@bpasero is there a way to send the log, I don't want to put it here in public

**Comment by bpasero** [comment] 2016-09-28 08:49
benjpas@microsoft.com works

**Comment by bpasero** [comment] 2016-09-28 08:57
@con-ssc sorry, I was suggesting the wrong tool. Process Explorer (https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) is the one that shows a tree of processes and allows to see the full command line:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

**Comment by con-ssc** [comment] 2016-09-28 09:59
CPU usage is kinda low but Memory Usage of those two processes is high.

![image](https://cloud.githubusercontent.com/assets/8189808/18909156/ce172362-8572-11e6-89f3-fed6f2e37b99.png)

![image](https://cloud.githubusercontent.com/assets/8189808/18909144/c14e78b0-8572-11e6-9cc9-da45ce2405b1.png)

![image](https://cloud.githubusercontent.com/assets/8189808/18909160/d67ac90a-8572-11e6-8b4b-831f13d6d8df.png)

**Comment by bpasero** [comment] 2016-09-28 10:02
@con-ssc none of the two look bad to me though, memory can go as high as 1 GB before becoming an issue.

**Comment by bpasero** [comment] 2016-09-28 10:03
@con-ssc can you maybe have an eye on the CPU while you work with code and when it gets so slow and freezes see if the CPU is high or not?

**Comment by con-ssc** [comment] 2016-09-28 10:08
ok
This Process goes over 30% if I scroll a large js file

https://cloud.githubusercontent.com/assets/8189808/18909160/d67ac90a-8572-11e6-8b4b-831f13d6d8df.png

**Comment by bpasero** [comment] 2016-09-28 10:23
@con-ssc can you install our insider build (
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders) and select Help > Accessibility Options to see if accessibility is ON or OFF?

**Comment by con-ssc** [comment] 2016-09-28 10:31
We have some port restrictions so I won't be able to install extensions to force the problem with the insider build

**Comment by bpasero** [comment] 2016-09-28 13:46
@con-ssc I received the core dump and the procmon trace. Today we do not have a setup where we can easily debug VSCode from coredumps, but we should probably improve this in the future to get a better understanding. 

The high CPU during scrolling is suspicious so please try the insiders build. I assume the CPU drops when you stop scrolling?

**Comment by joaomoreno** [comment] 2017-04-26 08:44
Closing due to silence.

**Closed by joaomoreno** 2017-04-26 08:44 UTC
Labels: freeze-slow-crash, needs more info
