### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by chaicopadillag** [microsoft/vscode#208914] opened 2024-03-27 15:18 UTC
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.1.80-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.10GB (23.45GB free)|
|Process Argv|. --crash-reporter-id 33fca9ed-8ef3-4e03-9eb6-4a17e9d480b4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
nestjs-files|Abh|0.5.1
codesnap|adp|1.3.4
project-manager|ale|12.7.0
ng-template|Ang|17.3.1
vscode-intelephense-client|bme|1.10.4
vscode-tailwindcss|bra|0.10.5
simple-react-snippets|bur|1.2.7
path-intellisense|chr|2.8.5
vscode-css-modules|cli|0.5.1
postcss|css|1.0.9
dbclient-jdbc|cwe|1.3.4
vscode-mysql-client2|cwe|7.1.6
dart-code|Dar|3.84.0
flutter|Dar|3.84.0
vscode-eslint|dba|2.4.4
vscode-faker|dee|2.0.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-mysql|for|0.5.0
vscode-pull-request-github|Git|0.82.1
terraform|has|2.29.5
html-tag-wrapper|hwe|0.2.3
better-dockerfile-syntax|jef|1.0.2
pubspec-assist|jer|2.3.2
Angular2|joh|16.0.1
vscode-phpfmt|kok|1.1.39
php-namespace-resolver|Meh|1.1.9
Angular-BeastCode|Mik|17.0.4
dotenv|mik|1.0.1
mongodb-vscode|mon|1.5.0
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5918
awesome-flutter-snippets|Nas|4.0.1
angular2-inline|nat|0.0.17
color-highlight|nau|2.8.0
laravel5-snippets|one|1.18.0
dartgettersetter|Pet|1.0.2
material-icon-theme|PKi|4.34.0
tsimporter|pmn|2.0.1
prisma|Pri|5.11.0
quicktype|qui|12.0.46
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
fabric8-analytics|red|0.9.4
java|red|1.28.1
vscode-yaml|red|1.14.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
sass-indented|syl|1.8.29
ayu|tea|1.0.5
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.53.0
vscode-gradle|vsc|3.13.5
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2023070103
vscode-wakatime|Wak|24.4.0
Java-extension-pack|wal|1.0.0
quokka-vscode|Wal|1.0.634
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
snippets-next-13|yuz|0.2.1
markdown-all-in-one|yzh|3.6.2
php-intellisense|zob|1.3.3

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by mjbvz** [comment] 2024-03-27 16:28
Duplicate of #208915

**Closed by mjbvz** 2024-03-27 16:28 UTC
