### ISSUE TITLE
Exit on Integrated terminal with zsh.

### ISSUE THREAD

**Issue by ramonsan** [Microsoft/vscode#7525] opened 2016-06-10 10:38 UTC
- VSCode Version: 1.2.0
- OS Version: Ubuntu 16.04 x64
- Terminal: Using zsh as terminal by default.

Steps to Reproduce:

1. Toggle integrated terminal. 
2. Type `exit` to end session.

Terminal session  is closed, but panel is not. You can toggle many times terminal, but do not open new session, you can not use it until you restart VS Code.

Using Bash, `exit` closes the panel, and toggle it again brings a new session.

**Comment by Tyriar** [comment] 2016-06-10 19:36
I cannot reproduce this on 1.2.0 stable, is it consistently reproducing @ramonsan? Can you check the console in devtools to see if there are any errors (Help > Toggle Developer Tools)?

**Comment by ramonsan** [comment] 2016-06-13 07:05
I tried today and seems it work as expected.

Maybe was related with some comand used friday. I will investigate the posible cause of that behavior.

**Comment by Tyriar** [comment] 2016-07-05 18:53
Things in this area changed a lot in v1.3, closing this as resolved. Please reopen/comment if you can reproduce in the Insiders build.

**Closed by Tyriar** 2016-07-05 18:53 UTC
Labels: bug, integrated-terminal, needs more info
