### ISSUE TITLE
[Feature] Extending Panel with WebView

### ISSUE THREAD

**Issue by mateuspv** [Microsoft/vscode#71234] opened 2019-03-26 21:49 UTC
I'm looking for recreate [Which-key package](https://github.com/justbur/emacs-which-key) on vscode:
![which-key-bottom](https://user-images.githubusercontent.com/4995440/55035500-e55ae800-4ff6-11e9-8f18-82ca14eb7529.png)

Right now, the closest solution to recreate this package is using an WebView, 
unfortunately WebView's are located along the tabs, which is not my desired place.

While vscode does not offer something like [Atom Panel](https://atom.io/docs/api/v1.9.4/Panel), the closet place is the "Panel" that holds itens like "terminal" and "search"

![Screenshot from 2019-03-26 18-38-38](https://user-images.githubusercontent.com/4995440/55035398-a4fb6a00-4ff6-11e9-8b2e-5140f9c3abaa.png)

I would like to request/know if it's possible to extending this Panel adding my own WebView.
Best

**Comment by mjbvz** [comment] 2019-03-28 02:04
Duplicate of #43049

**Closed by mjbvz** 2019-03-28 02:04 UTC
Labels: feature-request
