### ISSUE TITLE
Extensions tab on Mac yields "Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#22706] opened 2017-03-16 00:52 UTC
- VSCode Version: 1.10.2
- OS Version: OSX Sierra 10.12.3

Steps to Reproduce:

1. Open VS Code
2. Click Extensions

```
Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,
    at e.onCommonRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:7:5404),
    at e.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:7:5241),
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:7:5034,
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:3372),
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:6904),
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:7:11558),
    at emitOne (events.js:96:13),    at Socket.emit (events.js:188:7),
    at readableAddChunk (_stream_readable.js:176:18),
    at Socket.Readable.push (_stream_readable.js:134:10),
    at Pipe.onread (net.js:543:20)
```

Running with `--disable-extensions` still produces the error.

**Comment by joaomoreno** [comment] 2017-03-20 11:52
Which extensions do you have installed?

Can you reproduce after a machine restart? What about after reinstalling Code?

**Comment by jdforsythe** [comment] 2017-03-25 00:29
The problem persists after machine restart and a fresh download of Code. 

Extensions in `~/.vscode/extensions` include:

```
alefragnani.numbered-bookmarks
christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
donjayamanne.python
glen-84.sass-lint
jakob101.RelativePath
ktriek.ng-bootstrap-snippets
mkaufman.HTMLHint
mrmlnc.vscode-puglint
msjsdiag.debugger-for-chrome
odubuc.mysql-inline-decorator
PeterJausovec.vscode-docker
pflannery.vscode-versionlens
robertohuertasm.vscode-icons
sequoia.loopback-json-schemas
vilicvane.es-quotes
```

Removing all the extensions from `~/.vscode/extensions` doesn't solve the problem, even after a fresh download.

**Comment by joaomoreno** [comment] 2017-03-27 08:15
This is quite strange. Are you behind a proxy?

**Comment by jdforsythe** [comment] 2017-03-27 14:08
No proxy - nothing out of the ordinary network-wise. This happens whether I'm at home or work with the Macbook.

**Comment by joaomoreno** [comment] 2017-03-27 14:53
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by joaomoreno** [comment] 2017-04-26 09:56
Closing due to silence.

**Closed by joaomoreno** 2017-04-26 09:56 UTC
Labels: needs more info
