### ISSUE TITLE
 Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#100286] opened 2020-06-16 12:54 UTC
Issue Id: <b>e85259db-8e69-737a-f9e6-fc52ba53838d</b><br /><br />*Versions* <br />- 1.46.0<br />*Stack* <br />TypeError: Cannot read property 'get' of undefined<br />[/vs/workbench/contrib/extensions/browser/extensionsViews.ts#162:39 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/contrib/extensions/browser/extensionsViews.ts#L162:39 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/base/common/event.ts#152:14 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L152:14 (call))<br />[/vs/base/common/event.ts#587:15 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (call))<br />[/vs/base/common/event.ts#74:96 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L74:96 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/platform/list/browser/listService.ts#542:26 (open)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/platform/list/browser/listService.ts#L542:26 (open))<br />[/vs/platform/list/browser/listService.ts#537:8 (onSelection)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/platform/list/browser/listService.ts#L537:8 (onSelection))<br />[/vs/platform/list/browser/listService.ts#498:65 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/platform/list/browser/listService.ts#L498:65 (call))<br />[/vs/base/common/event.ts#587:15 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (call))<br />[/vs/base/common/event.ts#56:83 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L56:83 (call))<br />[/vs/base/common/event.ts#587:15 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (call))<br />[/vs/base/common/event.ts#56:83 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L56:83 (call))<br />[/vs/base/common/event.ts#810:14](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L810:14)<br />    at e.fire (out/vs/workbench/workbench.desktop.mai<br />

**Comment by joaomoreno** [comment] 2020-07-01 09:32
Dupe of https://github.com/microsoft/vscode/issues/93308

**Closed by joaomoreno** 2020-07-01 09:32 UTC
Labels: bug, error-telemetry, list
