### ISSUE TITLE
Native Windows title bar does not respect dark mode setting

### ISSUE THREAD

**Issue by MolusMS** [microsoft/vscode#84453] opened 2019-11-11 05:46 UTC
Issue Type: <b>Bug</b>

I have the dark theme on VSCode, if I set the window.titleBarStyle to native, the title bar does not pick up the dark color.

VS Code version: Code - Insiders 1.41.0-insider (27cd33d891eb23e370b672e751be9fe8b3748ac1, 2019-11-08T19:12:35.358Z)
OS version: Windows_NT x64 10.0.19514

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (51.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|2.0.191107007
cpptools|ms-|0.26.1
powershell-preview|ms-|2019.11.0

</details>

**Comment by sbatten** [comment] 2019-11-11 18:37
@deepak1556, this is really an electron feature request

**Comment by deepak1556** [comment] 2019-11-12 01:08
@sbatten electron fixed this 7 and also exposed a new module to allow apps customize it https://github.com/electron/electron/pull/19656

**Comment by deepak1556** [comment] 2019-11-14 01:29
@MolusMS can you try the exploration builds from https://github.com/microsoft/vscode/issues/84214#issuecomment-551647767 to make sure this is fixed with electron 7. Thanks!

**Comment by deepak1556** [comment] 2019-11-27 20:59
Verified that this is not fixed in electron 7, we would have to listen to OS events using the above module and set the app color.

**Comment by deepak1556** [comment] 2019-12-13 02:34
After some investigation, this is a bug in chrome as well, launch chrome with `--disable-windows10-custom-titlebar` and the native title bar will not respect the dark mode for apps settings. Should be reported in upstream.

**Comment by LarsFosdal** [comment] 2020-11-02 07:53
This goes for the light theme as well.  The app does not use the Windows 10 Theme App Title colors for focused / non-focused.
Really annoying!

**Comment by Poopooracoocoo** [comment] 2020-11-05 11:25
*cough* [undocumented APIs for dark titlebars](https://github.com/microsoft/terminal/commit/bc7eb9611030aed3204aff4e662c318cbf9143a6#diff-e26a93b2aa9fea92ebf24336c4fe6412L19-L22) *cough*

**Comment by rzhao271** [comment] 2021-10-21 19:06
Adding upstream Chromium issue link https://bugs.chromium.org/p/chromium/issues/detail?id=1127795

**Comment by rzhao271** [comment] 2021-11-02 23:26
I tried setting some breakpoints and noticed that https://source.chromium.org/chromium/chromium/src/+/main:ui/views/window/non_client_view.cc;l=113;bpv=1;bpt=1 gets hit. But, I didn't find a corresponding `OnPaint` event handler. https://source.chromium.org/chromium/chromium/src/+/main:ui/views/window/custom_frame_view.cc;drc=cafa646efbb6f668d3ba20ff482c1f729159ae97;bpv=0;bpt=1;l=363 is the closest we get, but it's for the custom frame view rather than the native one.

I then noticed that other non-Chromium Windows app titlebars weren't picking up the system colour either, so I looked around and saw https://github.com/microsoft/microsoft-ui-xaml/issues/2484, which still hasn't been implemented.

**Comment by rzhao271** [comment] 2021-11-04 00:32
I just realized that the original issue is saying that if the user picks a dark mode theme, then the native titlebar colour should also be the dark mode colour. I'm not as sure about this. On macOS, for example, the native titlebar colour goes by the OS theme, and same with cmd.exe on Windows. Changing the issue scope so that we're going by OS theme instead.

**Comment by deepak1556** [comment] 2021-11-04 03:46
@rzhao271 https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/424514 will monitor OS theme changes and adjust the tiltebar theme accordingly.

**Comment by rzhao271** [comment] 2021-12-27 23:36
I confirmed the feature works on a custom Insiders build. This issue will be fixed once we're on Electron 16.

**Comment by joyceerhl** [comment] 2022-02-23 19:09
Still seems to repro in latest Insiders which uses Electron 16:

![image](https://user-images.githubusercontent.com/30305945/155390200-a4142b16-fa73-4dd9-a101-6dc1345912aa.png)

**Comment by rzhao271** [comment] 2022-02-23 19:20
Looks like I forgot to add steps.
1. On Windows, set the system theme to dark mode
2. Set VS Code to use the native titlebar
3. The titlebar should be black rather than white (it should be the same colour as the titlebar you get when opening a command prompt from the start menu)

**Comment by joyceerhl** [comment] 2022-02-23 20:27
1. System theme is dark mode 
![image](https://user-images.githubusercontent.com/30305945/155402254-3b04f740-d5e0-4d20-8154-e94f1beccf78.png)
2. VS Code is configured to use native titlebar with the `"window.titleBarStyle": "native"` setting
3. Title bar is still white

After also changing my app mode to dark mode, the title bar _is_ black. Is that expected @rzhao271?

![image](https://user-images.githubusercontent.com/30305945/155402551-02b1fc13-2f03-45c8-bc6f-f2847a53ab36.png)

**Comment by rzhao271** [comment] 2022-02-24 17:00
Reopening since we're switching back Electron versions.

**Closed** 2022-03-10 15:51 UTC
Labels: feature-request, upstream, windows, verification-needed, electron, titlebar, confirmed, upstream-issue-linked, upstream-issue-fixed, chromium, electron-16-update

**Comment by rzhao271** [comment] 2022-03-21 18:47
Verification steps:
See https://github.com/microsoft/vscode/issues/84453#issuecomment-1049128842.
