### ISSUE TITLE
Edit sessions seem to disappear

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#162100] opened 2022-09-28 02:29 UTC
Testing #161860

1. Open vscode-website and make a change to README.md
2. Store Current Edit Session
3. Run Show Edit Sessions

I can see the vscode-website edit session with the README file nested

4. Close VS Code and reopen on vscode-docs.
5. Run Show Edit Sessions

I can see the vscode-website Edit Session but without the nested README file

6. Close VS Code and reopen on vscode-website.
7. Run Show Edit Sessions

"You have no stored edit sessions to display"

![image](https://user-images.githubusercontent.com/12818376/192673931-f2215594-af5a-49be-b115-e07af231ca25.png)

**Comment by joyceerhl** [comment] 2022-09-28 04:05
Duplicate of https://github.com/microsoft/vscode/issues/162034

**Closed by joyceerhl** 2022-09-28 04:05 UTC
