### ISSUE TITLE
Unable to search for extensions, showing "Extension : Disabled"

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#85443] opened 2019-11-23 06:47 UTC
Issue Type: <b>Bug</b>

Unable to search for extensions, search results are "EXTENSIONS: Disabled"

![image](https://user-images.githubusercontent.com/13393959/69474762-c4ee6200-0dff-11ea-8371-e36a6cc3106e.png)

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (13.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by egamma** [comment] 2019-11-23 15:49
Duplicate of https://github.com/microsoft/vscode/issues/85178

**Closed by egamma** 2019-11-23 15:49 UTC
