### ISSUE TITLE
HiDPI Text rendering is completely broken at 125% scaling

### ISSUE THREAD

**Issue by cblichmann** [Microsoft/vscode#43251] opened 2018-02-08 20:56 UTC
Text rendering in both the UI and the editor is completely unusable when I have 125% scaling enabled in my GNOME session (Wayland):

![image](https://user-images.githubusercontent.com/213059/35997713-9e822c56-0d1a-11e8-8364-d4016f980101.png)

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.14.0-2-amd64, Debian Buster
- Desktop Environment: GNOME 3.26.2 on Wayland
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
Go|luk|0.6.73
cpptools|ms-|0.14.6
vim|vsc|0.10.13

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Launch Visual Studio Code

Reproduces without extensions: Yes

**Comment by aaronhalford** [comment] 2018-02-09 17:22
Those fonts do look bad. This is likely either a direct VSC issue with the HTML text rendering or a VSC conflict with your system font settings in GNOME.

What are your GNOME settings for system fonts? (hinting, scaling)
Does the problem persist if you use a different font? If not, do you have a link to the exact font you are using that causes the error?

**Comment by cblichmann** [comment] 2018-02-10 09:44
My settings are nothing special (i.e. GNOME defaults for the UI fonts). Output of `gnome-tweak-tool:`
![screenshot from 2018-02-10 10-35-44](https://user-images.githubusercontent.com/213059/36060680-6b9ff644-0e4e-11e8-9a64-0264e0115f8f.png)

Display settings:
![screenshot from 2018-02-10 10-39-23](https://user-images.githubusercontent.com/213059/36060692-bc419814-0e4e-11e8-9ada-763b24722c7a.png)

Also, the problem does persist when I change the font. I tried with the default _Droid Sans Mono_, with similar results. The font I'm normally using is [_Ricty Diminished_](https://github.com/edihbrandon/RictyDiminished).

Note that I'm pretty certain that the HiDPI scaling interferes with the rendering as everything looks normal when I disable the scaling (my corporate workstation has identical settings apart from the screen).

**Comment by maritz-ergo** [comment] 2018-02-26 16:45
I have the same issue, except that changing the scaling does not fix this for me.

The problem also does not appear to happen in the sidepane, but it does show in the top menu (file, edit, etc.) and the main editor 

VSCode: 1.20.1
OS: Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux (in a VM)
WM: Cinnamon 3.4.6-1 on Xorg 7.7+19

**Comment by bpasero** [comment] 2018-03-16 06:21
Duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by bpasero** 2018-03-16 06:21 UTC
Labels: electron, font-rendering, linux, upstream
