### ISSUE TITLE
Code Lens - Left Align (# references)

### ISSUE THREAD

**Issue by warrenwza** [Microsoft/vscode#15551] opened 2016-11-16 03:59 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.2|
|team|ms-vsts|1.108.0|
|vscode-icons|robertohuertasm|4.0.1|
|vscode-wakatime|WakaTime|1.0.6|
|wallaby-vscode|WallabyJs|1.0.30|

---

![image](https://cloud.githubusercontent.com/assets/2863682/20334329/4ca89344-ac0d-11e6-9cd3-d80edbc3881d.png)

Steps to Reproduce:

1. Removed C# extension
2. Added C# extension back
3. Code Lens is left aligned, please see orange rectangle

**Comment by ramya-rao-a** [comment] 2016-11-16 18:08
Closing as duplicate of #15389. The fix is already in the insiders build. You can use the insiders build until the next VS Code update

**Closed by ramya-rao-a** 2016-11-16 18:08 UTC

**Comment by warrenwza** [comment] 2016-11-16 22:17
Awesome, thanks :)
