### ISSUE TITLE
code-insiders: unable to move secondary and primary sidebar to the right

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#192039] opened 2023-09-02 12:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
$ code-insiders --version
1.82.0-insider
f1302be1e67e3af5fbeb8bbb2ea784de7bc96150
x64

- OS Version: ubuntu
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

Steps to Reproduce:

1.  open a file, the primary sidebar, and a secondary sidebar
3.  right click primary sidebar > `move to the right`
4.  right click secondary sidebar > `move to the right` 
  - this causes the primary and secondary sidebar to switch places
  

https://github.com/microsoft/vscode/assets/10324554/16a2388e-6dfc-4a92-aa46-87f9ac81de6e

**Comment by ArturoDent** [comment] 2023-09-04 02:30
Duplicate of https://github.com/microsoft/vscode/issues/142742

You can't move both side bars to the same side in Stable or Insiders by design right now.

**Closed** 2023-09-04 02:48 UTC
