### ISSUE TITLE
No option for go to defenition on right click

### ISSUE THREAD

**Issue by razielron** [microsoft/vscode#113598] opened 2020-12-30 17:33 UTC
- VSCode Version: 1.52.1
- OS Version: windows build version 18363.1256

More info:
- JS file
- no jsconfig.json / tsconfig.json

Steps to Reproduce:

1. right click - no go to defenition
2. ctr + click - nothing happens

Does this issue occur when all extensions are disabled?: YES

What we tried:
Disabling all extensoins didn't work,
Downgrade to 1.50 vs code version didn't work,
Delete all user settings didn't work

Please help, nothing works!!
This is unusable without this small feature...

![WhatsApp Image 2020-12-30 at 19 30 31](https://user-images.githubusercontent.com/6358166/103370573-ce073380-4ad5-11eb-8aaa-796f46b426a3.jpeg)

**Comment by IllusionMH** [comment] 2020-12-30 17:52
/needsMoreInfo

Is it JS or TS file? Context menu looks like plain text. Is it same if you try to click in other areas?

How `Home` is imported in this file?
Do you have `jsconfig.json`/`tsconfig.json` in workspace.

**Comment by razielron** [comment] 2020-12-30 18:07
> /needsMoreInfo
> 
> Is it JS or TS file? Context menu looks like plain text. Is it same if you try to click in other areas?
> 
> How `Home` is imported in this file?
> Do you have `jsconfig.json`/`tsconfig.json` in workspace?

JS file, no jsconfig.json/tsconfig.json.
when opening the project in another computer and right clicking on the exact same thing I have - go to defenition
with the same vscode version.

**Comment by razielron** [comment] 2021-01-01 19:04
On the same computer where I don't have 'go to defenition',
I installed 'VSCode-Insiders' and it works (I do have 'go to defenition').
Since I did try uninstall+ireinstall VSCode, is there anything else I should have done?
It feels like when I uninstall, something is still causing trouble on the new installation.

**Comment by mjbvz** [comment] 2021-01-04 20:35
Closing as not reproducible in insiders.  This suggests that either insiders fixes the issue or that your current VS Code version is being broken by an extension/setting

**Closed by mjbvz** 2021-01-04 20:35 UTC
Labels: needs more info
