### ISSUE TITLE
Terminal hides real exit code

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#31965] opened 2017-08-03 09:53 UTC
Steps:

- create a terminal using the internal API (e.g. like tasks does)
- register an onExit listener on the terminal instance
- execute a command in a terminal that returns an exit code !== 0 using the -c or /C option to exit the shell after the command has complete

Observe: the exit code passed to the listener is always 0. The underlying reason is that the exit code is the one of the node process we start to start the real terminal. And the node process always returns zero.

**Comment by Tyriar** [comment] 2017-08-03 17:36
`bash -c "command"` should return the exit code of the command just fine?

```
~
❯ bash -c "exit 12"

~
❯ echo $?
12
```

If the task is configured as `bash -c "foo"` it should return the exit code of `foo`.

Are you seeing a problem on Windows only? Windows exit code currently doesn't work, it needs a node-pty release. https://github.com/Microsoft/vscode/issues/31090 https://github.com/Tyriar/node-pty/issues/75

**Comment by dbaeumer** [comment] 2017-08-04 08:03
I saw the problem on Windows. Didn't test other OSes.

**Comment by Tyriar** [comment] 2017-08-04 08:43
Closing as duplicate of https://github.com/Microsoft/vscode/issues/31090 then, the exit code never worked on Windows. Did the work last iteration to get it going but haven't released node-pty yet.

**Closed by Tyriar** 2017-08-04 08:43 UTC
Labels: integrated-terminal, needs more info
