### ISSUE TITLE
Use link cursor instead of select for details section in Markdown preview

### ISSUE THREAD

**Issue by KvanTTT** [Microsoft/vscode#22462] opened 2017-03-11 21:55 UTC
- VSCode Version: 1.10.2
- OS Version: Windows7 x64.

Steps to Reproduce:

1. Add a `detail` section in markdown (.md) document

```
<details>
  <summary>Source Code</summary>
   
   Some text
</details>
```

2. Open Preview: ![details-section](https://cloud.githubusercontent.com/assets/1150330/23827173/56054926-06be-11e7-9a86-3c7dd6ddd106.png)
For this element a `link` cursor ![link](https://cloud.githubusercontent.com/assets/1150330/23827148/daaca094-06bd-11e7-895b-07ee2961a81f.png) should be used (same for common links) instead of `select` cursor ![select](https://cloud.githubusercontent.com/assets/1150330/23827151/e172e8b6-06bd-11e7-9ce1-e54aa2c273e7.png).

**Comment by mjbvz** [comment] 2017-03-13 18:06
I can also reproduce this in Chrome proper. The cause seems to be that the `details`/`summary` contains text. If you use an image or other element, you retrain the standard cursor

I believe the current behavior is by design so I'm closing this issue as upstream/as-designed. Try using ]custom css](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css) to alter the cursor style for this element

```css
summary {
    cursor: default
}
```

**Closed by mjbvz** 2017-03-13 18:06 UTC
Labels: as-designed, markdown, upstream
