### ISSUE TITLE
Git sync animiation not shown

### ISSUE THREAD

**Issue by pmadhur** [Microsoft/vscode#24108] opened 2017-04-06 17:31 UTC
When you click on "Synchonize Changes" in status bar, Git sync animiation in status bar not shown anymore with 1.11.1. Prior to 1.11.0 animation was shown. Is this intentional? Or is it a new setting now?

![image](https://cloud.githubusercontent.com/assets/16571328/24767533/907444ae-1aff-11e7-8611-b18386cac081.png)

**Comment by jsynowiec** [comment] 2017-04-06 17:39
Duplicate of #23975

**Closed** 2017-04-06 17:45 UTC
