### ISSUE TITLE
Allow access to the currently active 'when clauses' from the extension api

### ISSUE THREAD

**Issue by pancho111203** [Microsoft/vscode#26882] opened 2017-05-18 18:34 UTC
Hi, I couldn't find a way to access the currently active 'when clauses' from an extension. This could be useful to allow the extension to behave in a different way if some clauses are active or not. I have seen it requested multiple times in Gitter.

An example of a use case: http://stackoverflow.com/questions/43372232/a-method-to-expose-the-vscode-active-when-clause-contexts

**Comment by jrieken** [comment] 2017-05-22 07:51
dupe of #10471

**Closed by jrieken** 2017-05-22 07:51 UTC
Labels: api
