### ISSUE TITLE
Settings Sync.... Microsoft... Sign In... Localhost:56962... Connection not secure

### ISSUE THREAD

**Issue by alandraper** [microsoft/vscode#105021] opened 2020-08-19 19:00 UTC
Trying to enable Settings Sync. 

1. I go to Settings / Settings Sync
2. Click on "Turn on Settings Sync"
3. Click on "Sign in & Turn on"
4. Pick Microsoft
5. My browser (Edge) opens to https://localhost:56995/signin?nonce=mmS4IHFOeZK9xYwjkL2I3w==
6. "The connection for this site is not secure". 
![image](https://user-images.githubusercontent.com/13674761/90678404-801f1c80-e213-11ea-9c60-15ab36cd49d4.png)

**Comment by RMacfarlane** [comment] 2020-09-01 15:56
@alandraper Is this using the stable or insider's version of VSCode?

**Comment by alandraper** [comment] 2020-09-01 18:06
I think it's just the stable version.

Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by RMacfarlane** [comment] 2020-11-03 22:48
I'm having trouble reproducing this - do you still see this? Are you using any of the remote extensions?

**Comment by adexios** [comment] 2020-11-04 20:53
I'm getting a similar issue where it's going to localhost instead of login.microsoft.com

Getting it on 1.50.1 (user setup)

**Comment by bricker-mark** [comment] 2020-11-11 21:52
I'm experiencing this issue as well.

![image](https://user-images.githubusercontent.com/5522663/98868527-82b59a80-242d-11eb-9186-8a1014ddcd51.png)

**Comment by thomas81528262** [comment] 2020-12-10 23:06
I just found what is the problem.
The problem was caused by the Remote Explorer.

If you use ssh Remote Explorer and sync the setting through the Microsoft will cause the issue.

**Comment by cesarlaforet** [comment] 2021-01-04 10:24
I can't find a fix for this, even starting VS Code with all extensions disabled! I keep getting "https://localhost:55768/signin?nonce=a47l971JSkejv5mtlHCsgg==" my vs code version is:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Any ideias?

**Comment by MartenBE** [comment] 2021-02-13 12:00
This issue still exists on Fedora 33 KDE (fully upgraded)

**Comment by archiso7** [comment] 2021-03-14 18:54
Same problem on arch linux with version:
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:11.840Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.18-1-lts

**Comment by Kizmar** [comment] 2021-04-12 11:59
Same here. Been getting this error through several version of vscode. Still happening and I just updated to the following version.

URL it goes to: http://localhost:50056/signin?nonce=exws9OgoDb8PedviWVMYVw==

Version: 1.55.1 (system setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Kizmar** [comment] 2021-04-28 13:43
Is there some sort of work-around for this? I'm unable to use Azure Data Studio because of the same issue. The vscode issue isn't quite as critical. Pretty silent on both fronts.

I haven't tried using GitHub as the sign in method because I would like to keep this tied to my personal Microsoft account.

I don't use Remote Explorer (assuming that's an extension?).

**Comment by VeselovAndrey** [comment] 2021-05-02 02:34
Same for me. Getting "localhost".  Version: 1.55.2 (user setup)

**Comment by dotupNET** [comment] 2021-07-22 05:21
what about a fix?

**Comment by alandraper** [comment] 2021-07-29 17:31
Any ideas or workarounds to get this to work?

**Comment by Kizmar** [comment] 2021-07-29 17:33
Mine started working after the last update or two. I don't use it very often so I'm not sure at what point it started to work again.

**Comment by ynauls** [comment] 2021-09-14 18:42
I am getting the same issue, on window 10, code version 1.60.1

**Comment by dvd73** [comment] 2021-09-17 08:55
This is because you default browser is Edge, remove https://localhost from secure restriction edge://net-internals/#hsts

**Comment by AlanMcBee** [comment] 2021-09-24 00:24
@dvd73 I don't think I would have figured this out on my own. How did you know to do this?

**Comment by dvd73** [comment] 2021-09-24 07:59
> @dvd73 I don't think I would have figured this out on my own. How did you know to do this?

found on the github discussion

**Comment by fabiofer-br** [comment] 2021-10-19 18:28
So, @dvd73, I agree with @AlanMcBee: I would NEVER have figured out it on my own.
Thanks a lot, buddy! It worked perfectly & instantly. Microsoft should put this answer as official.

Just to add: inside companies' internal networks (like mine), or other secure environments (like VPNs), or wherever you see the message "Your browser is managed by yourcompanyname.com" at your browser, this is the DEFAULT situation. Neither me or any of my work colleagues were able to turn on VSCode settings sync. 
Thank you.

**Closed** 2022-01-16 11:26 UTC
Labels: bug, needs more info, authentication
