### ISSUE TITLE
Same editor appears twice in tabs

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#88551] opened 2020-01-13 14:40 UTC
1. Add a large-ish image to a repo (1080p)
2. Open SCM view
3. Click twice in untracked image

Two tabs will appears for that same file:

![image](https://user-images.githubusercontent.com/22350/72264403-0094f380-361b-11ea-86f4-b7a8e9ed3f69.png)

**Comment by bpasero** [comment] 2020-01-13 16:35
Git bisect shows me that the cause was this: https://github.com/microsoft/vscode/pull/88183

**Comment by bpasero** [comment] 2020-01-14 07:35
This was actually a bug in the text diff editor and the behaviour was right. I pushed a fix.

**Closed** 2020-01-14 07:35 UTC
Labels: bug, confirmed, workbench-editors
