### ISSUE TITLE
can't set the correct key shortcut

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#170052] opened 2022-12-26 18:14 UTC
Type: <b>Bug</b>

I use cmd+shift+'+' for font zoom in, cmd+shift+'-' for font zoom out, cmd+shift+'0'  for reset

and cmd+'+' for UI Zoom in, cmd+'-' for UI zoom out, and cmd+'0' for reset

this on a Portuguese Keyboard layout.

this was working fine till last week.
seems something in a recent nightly broke this and now cmd+shift+'+'  is stored as cmd+shift+'V' and I can't get my keyboards to work 

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:36:47.419Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
inline-hasher|ale|1.1.0
spellright|ban|3.0.112
better-toml|bun|0.3.2
vscode-github-actions|csc|0.24.4
terraform-preview|has|2022.11.2417
vscode-yaml-sort|Pas|6.0.1
vscode-yaml|red|1.10.1
vscode-gitweblinks|red|2.9.2
kubernator-vscode|smp|1.0.0
code-spell-checker|str|2.12.0
shellcheck|tim|0.29.2
sort-lines|Tyr|1.9.1
errorlens|use|3.6.0
vscode-icons|vsc|12.0.1

(1 theme extensions excluded)

</details>

**Comment by FernandoMiguel** [comment] 2022-12-26 18:15
![image](https://user-images.githubusercontent.com/168366/209574486-5c087a70-fbd9-49a5-8c9a-34bce8bc2968.png)

**Comment by FernandoMiguel** [comment] 2022-12-26 18:15
```json
// Place your key bindings in this file to overwrite the defaultsauto[]
[
	{
		"key": "cmd+0",
		"command": "workbench.action.zoomReset"
	},
	{
		"key": "cmd+w",
		"command": "-workbench.action.closeWindow",
		"when": "!editorIsOpen && !multipleEditorGroups"
	},
	{
		"key": "shift+cmd+-",
		"command": "editor.action.fontZoomOut"
	},
	{
		"key": "shift+cmd+0",
		"command": "editor.action.fontZoomReset"
	},
	{
		"key": "shift+cmd+[Equal]",
		"command": "editor.action.fontZoomIn"
	},
	{
		"key": "cmd+numpad_add",
		"command": "-workbench.action.zoomIn"
	},
	{
		"key": "cmd+numpad0",
		"command": "-workbench.action.zoomReset"
	},
	{
		"key": "cmd+numpad_subtract",
		"command": "-workbench.action.zoomOut"
	},
	{
		"key": "shift+cmd+-",
		"command": "-workbench.action.zoomOut"
	},
	{
		"key": "shift+cmd+0",
		"command": "-workbench.action.zoomIn"
	}
]
```

**Comment by FernandoMiguel** [comment] 2022-12-26 18:15
![image](https://user-images.githubusercontent.com/168366/209574548-baca6eaa-e2ca-463d-b5cd-17cadc8db234.png)

**Comment by FernandoMiguel** [comment] 2022-12-26 18:21
tried with `--disable-extensions` and it still happened

`code --disable-extensions --verbose --disable-gpu --sync off --wait --new-window`

**Comment by FernandoMiguel** [comment] 2023-02-06 17:40
this seems to be fixed in the latest nightly
```
Version: 1.76.0-insider
Commit: c9e3ef865539061b5602c6b9ac6030332aa1ce70
Date: 2023-02-06T05:39:44.179Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by alexdima** [comment] 2023-04-08 20:51
Duplicate of https://github.com/microsoft/vscode/issues/173325.

**Closed by alexdima** 2023-04-08 20:51 UTC
