### ISSUE TITLE
Add support for customizing context menus in webview title section

### ISSUE THREAD

**Issue by welove42** [microsoft/vscode#175406] opened 2023-02-25 03:48 UTC
I would like to suggest adding a feature to customize the context menu in the title section of a webview in vscode. Specifically, I am trying to add new content to the context menu for a webview of a specific viewType, using the "when" field in the context menu definition. However, it seems that the "when" context does not currently support this syntax.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/77881340/221334528-ab7adf77-ac8f-417f-b638-3b46e682cb4f.png">

**Comment by mjbvz** [comment] 2023-02-26 23:05
Duplicate of #174905

**Closed by mjbvz** 2023-02-26 23:05 UTC
