### ISSUE TITLE
"View: Toggle Panel" key bind does not move focus to Debug Console

### ISSUE THREAD

**Issue by makail** [microsoft/vscode#85406] opened 2019-11-22 18:15 UTC
Issue Type: <b>Bug</b>

Launch debug session.
Focus Debug Console (manually or automatically when session launches).
Press "View: Toggle Panel" keybind twice.
Attempt to input text.

Result:
Text will either appear in the file you have open or not at all if no file is open.

Expected:
Text will appear in the text edit in the Debug Console.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment] 2019-11-25 10:21
Fixed in latest vscode insiders.
Duplicate of an already opened issue

**Closed by isidorn** 2019-11-25 10:21 UTC

**Comment by makail** [comment] 2019-11-26 18:12
Is it possible to get a link to the original issue?

**Comment by isidorn** [comment] 2019-11-27 09:24
https://github.com/microsoft/vscode/issues/83387
