### ISSUE TITLE
Script tags inner html snippet format color is white

### ISSUE THREAD

**Issue by pjmccormack** [Microsoft/vscode#26072] opened 2017-05-05 19:31 UTC
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. Remove all extensions
2. Create script tags with type="text/ng-template"
2. Add Html

I reverted back to March 2017 and all is well.

--Paul

**Comment by vmilitello** [comment] 2017-05-05 21:26
Same problem here. Just updated to Version 1.12.1 and got the same issue.
![2017-05-05_14h25_34](https://cloud.githubusercontent.com/assets/6493615/25764880/ca9418a2-319e-11e7-91a1-7e98597c2b4e.png)

**Comment by kieferrm** [comment] 2017-05-05 22:49
Duplicate of #25920.

**Comment by egamma** [comment] 2017-05-08 09:39
Reopening. We will rollback the grammar to the previous version.

**Comment by aeschli** [comment] 2017-05-08 10:50
Using #25920 as the main bug for this issue.

**Closed by aeschli** 2017-05-08 10:50 UTC
Labels: bug, important
