### ISSUE TITLE
Explorer "greys out" when renaming folder or file

### ISSUE THREAD

**Issue by henrikfalck** [microsoft/vscode#116836] opened 2021-02-17 08:47 UTC
When renaming either a folder or file the explorer is practically disabled. I can't give the specified folder/file a new name, but can still open folders/files.

![image](https://user-images.githubusercontent.com/48733683/108178813-28e7ff00-7105-11eb-9a62-9fca4f8a63b5.png)

**Recorded use:**
https://user-images.githubusercontent.com/48733683/108178690-048c2280-7105-11eb-9ee3-52b9a4ee7cf2.mov

**Information**
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0

**Comment by isidorn** [comment] 2021-02-17 09:42
Closing as dupe of https://github.com/microsoft/vscode/issues/116625
Would be great if you can answer my questions from that issue. Thanks

**Closed by isidorn** 2021-02-17 09:42 UTC
