### ISSUE TITLE
Custom Editors/Webviews don't support context menus (right click).

### ISSUE THREAD

**Issue by lforst** [microsoft/vscode#121580] opened 2021-04-18 10:18 UTC
- VS Code Version: 1.55.2
- OS Version: Mac OS Big Sur (Darwin x64 20.3.0)

Steps to Reproduce:

1. Create an extension using a web view or a custom editor.
2. Register an editor context menu contribution using `editor/context`.
3. Rightclick in the web view or custom editor.
4. Nothing happens.

Now I was wondering wether this is intended and authors of custom editors should implement right click context menus themselves. If so I will happily convert this into a feature request.

**Comment by mjbvz** [comment] 2021-04-19 21:18
Duplicate of #54285

**Closed by mjbvz** 2021-04-19 21:18 UTC
