### ISSUE TITLE
VSCode entirely unusable when opening a large project that contains both JS and TS

### ISSUE THREAD

**Issue by davityle** [Microsoft/vscode#13781] opened 2016-10-14 20:03 UTC
- VSCode Version: 1.6.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open VSCode
2. Open a directory of large project that contains typescript and large js files
3. watch vscode crash and utterly die.
     - the errors that get thrown have been logged in many issues and closed many times (https://github.com/Microsoft/vscode/issues/4634, https://github.com/Microsoft/vscode/issues/762, https://github.com/Microsoft/vscode/issues/6375, https://github.com/Microsoft/vscode/issues/4438, https://github.com/Microsoft/vscode/issues/7238). This is obviously still a problem. I've tried all the workarounds that I could find posted in other issues and they never work.  Please don't close this until this is fixed.

Only workaround that actually works: 
1. open same directory in sublime and then edit code without any issues (albeit with inferior typescript and intellisense support)

![image](https://cloud.githubusercontent.com/assets/5864474/19401445/a868a11a-9218-11e6-8709-c912790250ed.png)

**Comment by bpasero** [comment] 2016-10-17 08:25
@davityle please make the folder you open available to us. the typical reason why many other issues got closed is due to us not being able to reproduce.

**Comment by bpasero** [comment] 2016-10-19 05:04
@davityle please?

**Comment by davityle** [comment] 2016-10-19 16:01
So now VSCode is crashing when I open a pure typescript project. It is an Angular 2 typescript project. 

Unfortunately I am unable to share my folders with you. However I will give you some more information. The first folder that I mentioned contains 4737860 lines of javascript and 1166460 lines of typescript. The largest js file is 11MB. The largest js.map file is 13 MB. However there are also other files that are other compressed files that are 14+ MB. There are 45,526 total files, 20697 js files, 6121 ts files, and 4104 js.map files.  JS files average 13KB  and ts files average 9 KB. 

It's totally understandable that vscode is crashing on ^ . But now starting yesterday I can't use VSCode for anything without it crashing immediately. Along with getting the `Extension host terminated unexpectedly. Please reload the window to recover.` and `Error from the extension host: channel closed` errors I also get these errors in the dev tools console: `Error from the extension host: channel closede.doShow @ messageService.ts:128` , `threadService.ts:271 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV(anonymous function) @ threadService.ts:271
messageService.ts:128 Error from the extension host: channel closede.doShow @ messageService.ts:128`, and `messageService.ts:128 Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ messageService.ts:128
threadService.ts:271 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV(anonymous function) @ threadService.ts:271`. If there is anywhere else that I should be looking for log files let me know and I will gather those as well.

**Comment by bpasero** [comment] 2016-10-19 17:06
@davityle sorry to hear that you cannot share the workspace. I took this as a chance to write up a check list to find out more:

Here is a checklist to find out more about the freeze/slow/crash
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code: **
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders: **
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by bpasero** [comment] 2016-10-22 05:27
@davityle ?

**Comment by davityle** [comment] 2016-10-22 18:04
So I started down your checklist and I found that it was the plugin `TypeScript Hero` that was causing it. I'm not going to close this issue however because I still think that this is also a bug in the editor itself. First, it was not happening in the previous major release although it did happen in the release before that. Second, extensions shouldn't be able to crash the editor. At the very least I would expect the editor to notify me that an extension had crashed but then still continue working as if that extension wasn't installed. If that is too much then detect the extension that is crashing the editor and recommend uninstalling the extension. After I found out that the problem was `TypeScript Hero` I uninstalled it and installed `Auto-Import` and immediately started running into [this bug](https://github.com/soates/Auto-Import/issues/24). which has caused me to lose work several times. Again, I would expect that an extension crashing should not be able to crash the editor or cause something as crucial as saving a file to stop working.

**Comment by bpasero** [comment] 2016-10-24 06:05
@davityle thanks for finding out more. I would like to close this issue since it is caused by an extension. However you raise good points in your comment and I feel you should report them separately. Though it seems https://github.com/Microsoft/vscode/issues/13492 is already reported.

**Closed by bpasero** 2016-10-24 06:05 UTC
Labels: freeze-slow-crash, important, needs more info
