### ISSUE TITLE
when i open a file, i have to run vscode first. that's a little annoying to me

### ISSUE THREAD

**Issue by RuomuYing** [Microsoft/vscode#26162] opened 2017-05-07 14:39 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|MagicPython|magicstack|1.0.10|
|python|tht13|0.2.3|
|vim|vscodevim|0.7.0|;

---

Steps to Reproduce:

1. double clicking  on a file won't open it, all I get is an untitled file
2. I have to run vscode before open a file

**Comment by egamma** [comment] 2017-05-07 21:24
Cannot reproduce given these steps. please provide more detailed steps as descrobed here https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by egamma** [comment] 2017-05-09 11:01
Closing please reopen the issue with more information so that we can act on it.

**Closed by egamma** 2017-05-09 11:01 UTC
Labels: needs more info
