### ISSUE TITLE
Unable to run extension development host on Ubuntu

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10094] opened 2016-08-03 19:57 UTC
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Create a new Ubuntu VM using 16.04 LTS
2.  `sudo apt-get install nodejs nodejs-legacy npm`
3. Install Code from the website
4. Clone an extension (eg. https://github.com/DanTup/Dart-Code/)

Extension fails to activate and the console in the main Code instance reports:

    bash: cannot set terminal process group (-1): Inappropriate ioctl for device
    bash: no job control in this shell

![ubuntu](https://cloud.githubusercontent.com/assets/1078012/17380026/dc288004-59bc-11e6-8190-1427055f2f12.png)

**Comment by aeschli** [comment] 2016-08-03 20:12
From the error in the console it appears that extension.js did not get created by TS compiled/
Can you please complete the steps. You clone the dart repo, then what?

I tried:
- cd to the cloned repo
- npm install
- npm run compile
- open vscode on the folder
- press F5 (launch extension).
The dart extension seems to come up properly.

**Comment by DanTup** [comment] 2016-08-03 20:27
Ok, so it worked after that. It still spewed the same error, but it did launch :)

So, is it something I did wrong? If I clone a repo with an extension should I be running `npm install` manually, or is there something that should've done this for me when I hit F5 in Code?

**Comment by aeschli** [comment] 2016-08-03 21:06
`npm install `normally needs to be called manually right after cloning.
What happens on launch depends on what's listed as 'preLaunch' task in launch.json.
In your case it calls the `npm` default task (defined in tasks.json) which runs `npm run compile`. 

Now, in my steps I ran `npm run compile` manually and that's why it worked. If not doing that, it seems that F5 does call the npm task, and the npm tasks calls npm run compile. I even get the message `10:52:32 PM - Compilation complete. Watching for file changes.` in the output window,
but no files get generated (out/src stays empty)

**Comment by DanTup** [comment] 2016-08-03 21:23
@aeschli Just to confirm (it's not clear to me from your message), this sounds like a bug and not something I did wrong?

**Comment by aeschli** [comment] 2016-08-04 07:04
There seems to be bug on our side that the launch preTask does not really compile the TS files. It says it does, but no files are created in out/src. We will investigate...

**Comment by dbaeumer** [comment] 2016-08-04 07:58
Was not able to reproduce this.

@aeschli are you sure that the out folder didn't get created. It is filtered in the .settings :-)

**Comment by aeschli** [comment] 2016-08-04 08:33
Yes I unfiltered it.
Trying it again:
- start vscode fresh, unfilter the out folder.
- delete the out/src folder, create a empty src folder again
- press F5.
- Extension Development Host starts, open a dart file, all works fine, files are compiled
- shutdown the Extension Development Host
- delete the out/src folder, create a empty src folder again
- press F5.
- Extension Development Host starts, open a dart file, error, out/src stays empty.
- Run 'terminate running task'
- press F5.
- Extension Development Host starts, open a dart file, all works fine, files are compiled

Is that the expected behaviour that the compile task stays running and prevents recompiles?

**Comment by dbaeumer** [comment] 2016-08-04 09:25
Yes, that is the current 'expected' behavior. The way how @bpasero sets this up in the vscode npm module is as a watching compile, which doesn't recompile if the output folder gets deleted (tsc behaves the same). A watching compile only runs if the input changes, not if the output gets deleted. 

I opt to close this issue. Any objections.

**Comment by aeschli** [comment] 2016-08-04 09:58
Wouldn't it be better to kill the task when the Extension Development Host is closed? It is not obvious to the user that there's still a task running and how to terminate it. Also I don't need to have my files compiled until I start the the Extension Development Host again.

But I guess I'd rather create a separate issue for that... I created #10118.

Closing this issue. It looks the main problem was that npm install was not called after cloning.

**Closed by aeschli** 2016-08-04 09:58 UTC
Labels: needs more info

**Comment by DanTup** [comment] 2016-08-04 16:37
Just to confirm - when I clone the repo to a clean machine, I should run `npm install` before opening it to avoid this, it's not expected for Code to do this?
(I'm not complaining, I just want to be sure I understand!)

**Comment by aeschli** [comment] 2016-08-04 18:36
Yes, correct, it's up to you to run npm install.

**Comment by DanTup** [comment] 2016-08-04 18:38
Thanks!
