### ISSUE TITLE
No function list?

### ISSUE THREAD

**Issue by fudashuai** [Microsoft/vscode#36190] opened 2017-10-13 03:21 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
code-gnu-global|aus|0.2.2
GBKtoUTF8|buk|0.0.2
vscode-markdownlint|Dav|0.10.1
githistory|don|0.2.3
python|don|0.7.0
prettier-vscode|esb|0.24.0
vscode-emacs|hir|0.1.1
changeEncode|lan|0.0.8
vs-color-picker|lih|0.7.0
vscode-clang|mit|0.2.2
atom-keybindings|ms-|3.0.2
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
java|red|0.11.0
vscode-icons|rob|7.15.0
vscode-hexdump|sle|1.4.0
python-extended-snippets|tus|0.0.1
vscode-arduino|vsc|0.2.9
vim|vsc|0.10.1
vscode-todo-highlight|way|0.5.11

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by fudashuai** [comment] 2017-10-13 03:22
No function list?

**Comment by smuuf** [comment] 2017-10-13 06:05
I don't think this is something included in Code by default.

But you can try something like [Code Outline plugin](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) which will display something like this in the sidebar:

![image](https://user-images.githubusercontent.com/6860713/31532374-34640ba8-afed-11e7-8c1f-db70ed3a4d67.png)

**Comment by egamma** [comment] 2017-10-13 07:13
@smuuf thanks for point out the extension.

The feature request to provide this in VS Code is a duplicate of #5605

**Closed by egamma** 2017-10-13 07:13 UTC
