### ISSUE TITLE
VS Code changes my git editor to itself every time it updates

### ISSUE THREAD

**Issue by yuslepukhin** [microsoft/vscode#142695] opened 2022-02-10 02:26 UTC
Issue Type: <b>Bug</b>

I noticed that time to time my .gitconfig editor setting changes all of the sudden to VS Code. 

This  has been happening consistently over a periond of months.
I then realized that it takes place everytime there is an update to VS Code.

VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (49.62GB free)|
|Process Argv|--crash-reporter-id 84eda910-b673-4114-8f5d-81f61b2df269|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.0
jupyter|ms-|2022.1.1001821375
jupyter-keymap|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360:30404995
vsrem710cf:30416617
vscscmwlcmt:30433761

```

</details>

**Comment by yuslepukhin** [comment] 2022-02-11 01:17
> Are you sure that this is related to VS Code updates and not Git for Windows updates (that has option to set VS Code as default git editor)?

I do not think so, but I will check for that. git does not update nearly as often.

**Comment by IllusionMH** [comment] 2022-02-11 09:02
It looks similar to https://github.com/git-for-windows/git/issues/3538

> Clicked Yes on the notification asking to update Git for Windows.

> * What actually happened instead?
>
> No prompt was received (other than the Windows UAC elevation prompt), and Git for Windows automatically initiated the installation on its own (without asking me to confirm) and added core.editor to ~/.gitconfig based on my original installation option even though the exact same value for the same config option is already set in the system gitconfig.

**Comment by lszomoru** [comment] 2022-03-29 13:14
@yuslepukhin, were you able to confirm that indeed this is caused by a VS Code update?

**Comment by yuslepukhin** [comment] 2022-03-29 17:14
It has not happened since I filed the issue. Even though there was an update for git. I just fired up `VSCode`, I use studio on everyday basis, and nothing happened either.

**Comment by lszomoru** [comment] 2022-03-29 18:18
@yuslepukhin, thanks for the update. Will close the issue for now. Please reopen it in case the issue resurfaces. Thanks!

**Closed by lszomoru** 2022-03-29 18:18 UTC
Labels: needs more info, git
