### ISSUE TITLE
VSCode crash on start after packages updated on kubuntu 21.10 (development branch)

### ISSUE THREAD

**Issue by zorn-v** [microsoft/vscode#132455] opened 2021-09-06 12:21 UTC
```bash
# /usr/share/code/code 
[main 2021-09-06T12:15:47.061Z] update#setState idle
[2930:0906/221547.065651:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[2930:0906/221547.373376:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[2930:0906/221547.534308:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3036:0906/221547.552065:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[2930:0906/221547.640368:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3040:0906/221547.648768:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[2930:0906/221547.743235:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3044:0906/221547.751366:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[2930:0906/221547.839606:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3048:0906/221547.843726:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[2930:0906/221547.952225:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3052:0906/221547.955907:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[2930:0906/221548.067570:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[3056:0906/221548.071281:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[2930:0906/221548.175118:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[2930:0906/221548.175137:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Server response: 
Server response: 
Недопустимая инструкция (стек памяти сброшен на диск)
```

Last message is "Unsupported instruction (stacktrace dumped to disk)"

**Comment by hadim** [comment] 2021-09-06 21:14
Same here using Ubuntu 21.10 dev.

**Comment by hadim** [comment] 2021-09-06 21:55
Traceback:

```
$ code --verbose
[main 2021-09-06T21:54:34.951Z] Starting VS Code
[main 2021-09-06T21:54:34.951Z] from: /usr/share/code/resources/app
[main 2021-09-06T21:54:34.951Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '634bea06-2fc3-4a0c-aa5c-d7fb1ef5d397',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/hadim/.config/Code/logs/20210906T175434'
}
[main 2021-09-06T21:54:34.953Z] Resolving machine identifier...
[main 2021-09-06T21:54:34.953Z] Resolved machine identifier: d2abc133a0442c638f626ba13c6747cc41ce11a92774dec98b2b99b81139aba3
[main 2021-09-06T21:54:34.953Z] Main->SharedProcess#connect
[main 2021-09-06T21:54:34.964Z] StorageMainService: creating global storage
[main 2021-09-06T21:54:34.965Z] lifecycle (main): phase changed (value: 2)
[main 2021-09-06T21:54:34.966Z] windowsManager#open
[main 2021-09-06T21:54:34.967Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '80a64860979efd1fcf8717876136a349', uri: [g] },
    exists: true
  }
]
[main 2021-09-06T21:54:34.969Z] IPC Object URL: Registered new channel vscode:006d9618-ae92-4209-a2b8-0c7aea3dcf59.
[main 2021-09-06T21:54:34.969Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 0, y: 102, width: 2289, height: 1288 }
[main 2021-09-06T21:54:34.969Z] window#validateWindowState: 1 monitor working area { x: 0, y: 27, width: 2560, height: 1363 }
[main 2021-09-06T21:54:34.969Z] window#ctor: using window state { mode: 1, x: 0, y: 102, width: 2289, height: 1288 }
[main 2021-09-06T21:54:35.001Z] StorageMainService: creating workspace storage (80a64860979efd1fcf8717876136a349)
[main 2021-09-06T21:54:35.002Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2021-09-06T21:54:35.003Z] lifecycle (main): phase changed (value: 3)
[main 2021-09-06T21:54:35.004Z] update#setState idle
[main 2021-09-06T21:54:35.004Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[5021:0906/175435.037401:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.037419:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 1 time(s)
[main 2021-09-06T21:54:35.071Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[5021:0906/175435.189392:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.189447:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 2 time(s)
[5021:0906/175435.381836:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.381850:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 3 time(s)
[5097:0906/175435.393328:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[5021:0906/175435.480713:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.480740:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 4 time(s)
[5101:0906/175435.493576:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[5021:0906/175435.578542:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.578606:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 5 time(s)
[5105:0906/175435.593475:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[5021:0906/175435.717234:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.717259:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 6 time(s)
[5109:0906/175435.721236:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[5021:0906/175435.817297:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.817339:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 7 time(s)
[5113:0906/175435.821641:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[5021:0906/175435.904632:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175435.904653:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 8 time(s)
[5117:0906/175435.908288:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[5021:0906/175436.000169:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[5021:0906/175436.000197:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 9 time(s)
[5021:0906/175436.000206:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

```

**Comment by zorn-v** [comment] 2021-09-07 05:59
Run with `code --disable-gpu --disable-software-rasterizer` as workaround

**Comment by hadim** [comment] 2021-09-07 13:50
Any chance to use VSCode without disabling the GPU? Is it something that should be fixed on the VSCode side or Ubuntu side?

**Comment by zorn-v** [comment] 2021-09-08 02:35
[e5334fb3-8432-413d-a5f5aa8e-3a076d3d.dmp.gz](https://github.com/microsoft/vscode/files/7125321/e5334fb3-8432-413d-a5f5aa8e-3a076d3d.dmp.gz)

**Comment by hadim** [comment] 2021-09-08 11:25
[b039eaa1-540a-4554-8e58f799-fc055e93.zip](https://github.com/microsoft/vscode/files/7128471/b039eaa1-540a-4554-8e58f799-fc055e93.zip)

**Comment by deepak1556** [comment] 2021-09-09 02:01
Thanks for the logs, can you also confirm your systemd versions `systemctl --version`, wondering if you are hitting https://github.com/microsoft/vscode/issues/132609

**Comment by zorn-v** [comment] 2021-09-09 03:05
```
systemd 248 (248.3-1ubuntu3)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid
```

**Comment by deepak1556** [comment] 2021-09-09 07:21
Since the gpu process exit codes are similar between https://github.com/microsoft/vscode/issues/132609 and here, will check if the runtime fix helps. I will update here once we have a new build to verify. Couldn't get enough detail from the crash dumps as they appear incorrect after symbolication for this particular crash.

**Comment by tkrafael** [comment] 2021-09-12 01:35
Hello, my vscode also suddenly started to crash on ubuntu + nvidia. Same systemd.
Tried to downgrade from 1.60 to 1.59, no success.
Also tested with nouveau driver, failing.
Nvidia driver 460 and 470, failing.

**Comment by deepak1556** [comment] 2021-09-12 02:59
If possible can anyone try the following steps,

* Download https://www.electronjs.org/fiddle
* Run with Electron v13.3.0 and it should fail
* Run with Electron v14.0.0 and it should work

It will help me confirm the fix I had backported addresses the issue.

**Comment by zorn-v** [comment] 2021-09-13 03:59
>  Run with Electron v13.3.0 and it should fail
    Run with Electron v14.0.0 and it should work

Confirm that

**Comment by deepak1556** [comment] 2021-09-13 12:28
Thanks for confirming!

**Comment by hadim** [comment] 2021-09-21 23:29
The latest insider does not work for me:

```bash
$ code-insiders --version
1.61.0-insider
1b9403cd461c9c975bcb9e48d84ba9e4ea86559e
x64
```

```bash
$ code-insiders --verbose
[main 2021-09-21T23:28:46.777Z] Starting VS Code
[main 2021-09-21T23:28:46.778Z] from: /usr/share/code-insiders/resources/app
[main 2021-09-21T23:28:46.778Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '5cbd6415-6ff7-4d74-a2a5-2d5be895a0e1',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/hadim/.config/Code - Insiders/logs/20210921T192846'
}
[main 2021-09-21T23:28:46.779Z] Resolving machine identifier...
[main 2021-09-21T23:28:46.780Z] Resolved machine identifier: d2abc133a0442c638f626ba13c6747cc41ce11a92774dec98b2b99b81139aba3
[main 2021-09-21T23:28:46.781Z] Main->SharedProcess#connect
[main 2021-09-21T23:28:46.792Z] StorageMainService: creating global storage
[main 2021-09-21T23:28:46.793Z] lifecycle (main): phase changed (value: 2)
[main 2021-09-21T23:28:46.795Z] windowsManager#open
[main 2021-09-21T23:28:46.795Z] windowsManager#open pathsToOpen [ [Object: null prototype] {} ]
[main 2021-09-21T23:28:46.797Z] IPC Object URL: Registered new channel vscode:8aa05db1-7415-439d-a5d4-98e7f6720eba.
[main 2021-09-21T23:28:46.797Z] window#validateWindowState: validating window state on 1 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 768,
  y: 336,
  hasDefaultState: true
}
[main 2021-09-21T23:28:46.797Z] window#validateWindowState: 1 monitor working area { x: 0, y: 27, width: 2560, height: 1363 }
[main 2021-09-21T23:28:46.797Z] window#ctor: using window state {
  width: 1024,
  height: 768,
  mode: 1,
  x: 768,
  y: 336,
  hasDefaultState: true
}
[main 2021-09-21T23:28:46.842Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 0, emptyToOpen: 1)
[main 2021-09-21T23:28:46.843Z] lifecycle (main): phase changed (value: 3)
[main 2021-09-21T23:28:46.844Z] update#setState idle
[main 2021-09-21T23:28:46.845Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[8249:0921/192846.879167:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192846.879190:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 1 time(s)
[main 2021-09-21T23:28:46.928Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[8249:0921/192847.076954:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.076974:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 2 time(s)
[8249:0921/192847.265894:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.265918:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 3 time(s)
[8326:0921/192847.279670:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[8249:0921/192847.407715:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.407737:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 4 time(s)
[8330:0921/192847.417157:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[8249:0921/192847.543457:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.543478:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 5 time(s)
[8334:0921/192847.552576:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[8249:0921/192847.682436:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.682455:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 6 time(s)
[8338:0921/192847.687252:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[8249:0921/192847.805284:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.805303:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 7 time(s)
[8342:0921/192847.808835:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[8249:0921/192847.928488:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192847.928502:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 8 time(s)
[8346:0921/192847.932100:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[8249:0921/192848.038422:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[8249:0921/192848.038456:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 9 time(s)
[8249:0921/192848.038465:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
/dev/fd/3: No such file or directory
Server response:
/dev/fd/3: No such file or directory
Server response:

```

**Comment by hadim** [comment] 2021-09-21 23:31
Using `--no-sandbox` works for both `code` and `code-insiders`.

**Comment by zorn-v** [comment] 2021-09-22 06:24
> If things still don't seem right, please ensure you're on version 1b9403c of Insiders

In message above, @hadim use exacly that version and it is not working as expected.

**Comment by deepak1556** [comment] 2021-09-22 06:41
Thanks for verifying, can you provide the following additional data to help debug further

1) Please attach the crash report from latest insiders based on https://github.com/microsoft/vscode/issues/132455#issuecomment-914822389
2) Please attach the log output from `code-insiders --verbose --enable-gpu-debugging`
3) Does the issue repro when you launch with `--disable-gpu-sandbox` ?

**Comment by hadim** [comment] 2021-09-22 12:42
> 1. Please attach the crash report from latest insiders based on [VSCode crash on start after packages updated on kubuntu 21.10 (development branch) #132455 (comment)](https://github.com/microsoft/vscode/issues/132455#issuecomment-914822389)

[crash.zip](https://github.com/microsoft/vscode/files/7210693/crash.zip)

> * Please attach the log output from `code-insiders --verbose --enable-gpu-debugging`

```bash
$ code-insiders --verbose --enable-gpu-debugging
Warning: 'enable-gpu-debugging' is not in the list of known options, but still passed to Electron/Chromium.
[main 2021-09-22T12:41:35.306Z] Starting VS Code
[main 2021-09-22T12:41:35.307Z] from: /usr/share/code-insiders/resources/app
[main 2021-09-22T12:41:35.307Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '5cbd6415-6ff7-4d74-a2a5-2d5be895a0e1',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/hadim/.config/Code - Insiders/logs/20210922T084135'
}
[main 2021-09-22T12:41:35.308Z] Resolving machine identifier...
[main 2021-09-22T12:41:35.308Z] Resolved machine identifier: d2abc133a0442c638f626ba13c6747cc41ce11a92774dec98b2b99b81139aba3
[main 2021-09-22T12:41:35.309Z] Main->SharedProcess#connect
[main 2021-09-22T12:41:35.317Z] StorageMainService: creating global storage
[main 2021-09-22T12:41:35.318Z] lifecycle (main): phase changed (value: 2)
[main 2021-09-22T12:41:35.319Z] windowsManager#open
[main 2021-09-22T12:41:35.319Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/hadim/.config/Code - Insiders/Backups/1632266998887',
    remoteAuthority: undefined
  }
]
[main 2021-09-22T12:41:35.320Z] IPC Object URL: Registered new channel vscode:c486bd22-4d9c-434f-ba45-715200186835.
[main 2021-09-22T12:41:35.321Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: 550, y: 217, width: 1024, height: 768 }
[main 2021-09-22T12:41:35.321Z] window#validateWindowState: multi-monitor working area { x: 0, y: 27, width: 2560, height: 1363 }
[main 2021-09-22T12:41:35.321Z] window#ctor: using window state { mode: 1, x: 550, y: 217, width: 1024, height: 768 }
[main 2021-09-22T12:41:35.360Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-09-22T12:41:35.361Z] lifecycle (main): phase changed (value: 3)
[main 2021-09-22T12:41:35.362Z] update#setState idle
[main 2021-09-22T12:41:35.362Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[9259:0922/084135.386123:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084135.386142:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 1 time(s)
[9259:0922/084135.585746:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084135.585762:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 2 time(s)
[9259:0922/084135.746237:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084135.746259:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 3 time(s)
[9337:0922/084135.757996:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[9259:0922/084135.881232:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084135.881252:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 4 time(s)
[9341:0922/084135.889835:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[9259:0922/084135.993059:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084135.993081:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 5 time(s)
[9345:0922/084136.000898:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[9259:0922/084136.096607:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084136.096628:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 6 time(s)
[9349:0922/084136.100686:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[9259:0922/084136.182529:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084136.182546:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 7 time(s)
[9353:0922/084136.186664:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[9259:0922/084136.275375:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084136.275433:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 8 time(s)
[9357:0922/084136.279006:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[9259:0922/084136.359687:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=159
[9259:0922/084136.359707:WARNING:gpu_process_host.cc(1321)] The GPU process has crashed 9 time(s)
[9259:0922/084136.359717:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
/dev/fd/3: No such file or directory
Server response:
/dev/fd/3: No such file or directory
Server response:

```




> 3\. Does the issue repro when you launch with `--disable-gpu-sandbox` ?

No I can't reproduce with that flag. Code works correctly.

**Comment by 3vi1** [comment] 2021-09-22 12:47
I just tested and got the same results as hadlm:  Same 159 exit codes and "GPU process isn't usable" s in the log when using --enable-gpu-debugging, whereas using --disable-gpu-sandbox causes it to work without crashing.

**Comment by zorn-v** [comment] 2021-09-22 13:15
> Run with code --disable-gpu --disable-software-rasterizer as workaround

By the way, sometimes need to run it several times to run code without crash.
With `--disable-gpu-sandbox` it run more stable, but I don't want to disable sandbox.

**Comment by deepak1556** [comment] 2021-09-23 11:39
Thanks for the logs, the root issue has been narrowed down. Merging to https://github.com/microsoft/vscode/issues/133593

**Closed by deepak1556** 2021-09-23 11:39 UTC
Labels: upstream, linux, gpu, chromium, fixed-in-electron-14
