### ISSUE TITLE
Show tooltip on QuickPick item's description

### ISSUE THREAD

**Issue by 1openwindow** [microsoft/vscode#128721] opened 2021-07-15 06:42 UTC
In our extension, we use QuickPick API to collect information. In some case, the description is long, which exceed the width of QuickPick. It is better that show the entire description as tooltip when hover on it.
 
![image](https://user-images.githubusercontent.com/26411726/125740138-914a7e86-e749-4ccf-8e68-3e780ff810a0.png)

**Comment by TylerLeonhardt** [comment] 2021-07-19 23:21
duplicate of https://github.com/microsoft/vscode/issues/99301

**Closed by TylerLeonhardt** 2021-07-19 23:21 UTC
