### ISSUE TITLE
Integrated terminal does not work well with zsh/oh-my-zsh

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#12590] opened 2016-09-26 01:09 UTC
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1

The integrated terminal has some weird behavior like suddenly jumping to a new line:

Steps to Reproduce:
1. Install zsh and oh-my-zsh and use default configuration
2. Open VSCode and integrated terminal
3. Type in commands like `ls -` then when pressing `l` the cursor suddenly jumps to a new line

![screenshot from 2016-09-26 09-07-41](https://cloud.githubusercontent.com/assets/4662568/18819744/dec0d4ca-83c8-11e6-81e7-662146aadc34.png)
![screenshot from 2016-09-26 09-08-03](https://cloud.githubusercontent.com/assets/4662568/18819745/dec1446e-83c8-11e6-8583-6846916406d3.png)

**Comment by czmecho** [comment] 2016-11-01 02:25
there have some problem too.
![screenshot from 2016-11-01 10-21-16](https://cloud.githubusercontent.com/assets/5077551/19877774/17649242-a01d-11e6-89a4-2c71b01de6c8.png)
the character is  hidden.
my environment is VSCode Version: 1.6.1
OS Version: Ubuntu 16.10
@chrmarti

**Comment by Tyriar** [comment] 2016-11-01 03:05
Duplicate of https://github.com/Microsoft/vscode/issues/13554

**Closed by Tyriar** 2016-11-01 03:05 UTC
Labels: bug, integrated-terminal
