### ISSUE TITLE
Proper conditional to "escape" clutter - dismiss build panel (or the like)

### ISSUE THREAD

**Issue by pbannister** [microsoft/vscode#124771] opened 2021-05-27 16:15 UTC
Wired into my brain is use of the ESCAPE key to dismiss the panel shown after a build.
Or to quote a guy on StackOverflow: for a common operation why do "... I have to keep grabbing my mouse like a muggle?" 

This is related to #47710 and #48122 (at least). 
Pretty sure this was present in Visual Studio (not Code). 
Pretty sure Sublime Text carried over this behavior, because ... _Hello?_ ... a common extremely useful operation.

I can see in the default keybindings that there is some attempt in this direction, if perhaps not recognized as an abstraction.
There is a theme here, if unrecognized (hence the messy default key bindings). 
When in the text editor panel, and I hit ESCAPE, what can it mean? 
I would suggest as a theme we are trying to ESCAPE from the current mode back to some sort of "normal" default.

Existing default behaviors: 
If there is a text-selection, cancel the selection (fair enough, and a default).
If in ... various side-activities (as captured piecemeal in the default key bindings), then de-clutter a bit.

(Not sure why the duplicate bindings - mostly? - for "escape" and "shift+escape", BTW.)

I have two asks.

1)  We could all use help defining an appropriate "when" condition for a User key binding. 
I do not know the vscode APIs well enough to craft an appropriate "when" condition.
My first cut, very likely wrong:
```
    {
        "key": "escape",
        "command": "workbench.action.closePanel",
        "when": "editorTextFocus && textInputFocus && !editorHasSelection"
    },
```

2)  I would suggest there is a missing abstraction in need of design and implementation.
ESCAPE should unwind us from a modal sub-state, and get us back (in steps) to a default un-cluttered primary view.

_(All the above text as this morning was bugged enough that ESCAPE does not work. :) )_

**Comment by alexdima** [comment] 2021-05-31 19:03
The problem is that keybinding rules are evaluated bottom-to-top, starting with the user defined keybindings and it is not possible to insert a keybinding at the right spot in the default keybindings. So if you define a new keybinding in user keybindings, which captures `"escape"` in more cases than strictly necessary, then it will shadow other default keybindings. 

In order to capture `"escape"` only when strictly necessary, we need to check if we have a context key for when the panel is visible. @isidorn do we have such a context key?

`shift+escape` is bound for our screen reader users. Oftentimes, `Escape` will have a certain meaning in the screen reader software, so we also bind `shift+escape` to give our screen reader users an alternative.

**Comment by isidorn** [comment] 2021-05-31 19:07
@alexdima yes, we have the `panelVisible` context key.
Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/common/panel.ts#L13

**Comment by alexdima** [comment] 2021-05-31 19:11
@pbannister Your keybinding could look like:
```
    {
        "key": "escape",
        "command": "workbench.action.closePanel",
        "when": "editorTextFocus && panelVisible"
    },
```

**Comment by pbannister** [comment] 2021-06-01 03:40
(Was back here as my first guess prevented unwinding from auto-complete suggestions and in-file "Find".)

Thanks @alexdima and @isidorn . Yes, that is indeed an improvement over my first guess. Your suggestion does indeed solve my immediate problem. Would suggest that you update #47710 and #48122 as this is a better answer.

Yes, I understood the ordered / short-circuit evaluation of key-bindings. Would also note the solution was less than immediately obvious to folk who are much more acquainted with the API than I. :)

This meets my first ask, so close this if you want.

Would suggest you track, somehow, my second.

**Comment by jespertheend** [comment] 2021-06-08 10:50
I also like to add `workbench.action.closePanel` to `terminal.integrated.commandsToSkipShell` so that I can close it even when it has focus.

**Closed** 2021-08-02 02:31 UTC
Labels: feature-request, keybindings
