### ISSUE TITLE
Some files in explorer show folder icons and vice versa

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79543] opened 2019-08-21 02:42 UTC
I saw this inside `vscode/node_modules/node-pty/build/Release` the other day as well:

Material icons:

![image](https://user-images.githubusercontent.com/2193314/63398433-7190f180-c382-11e9-87fc-dfe9b7634bc7.png)

Minimal (VS Code):

![image](https://user-images.githubusercontent.com/2193314/63398450-853c5800-c382-11e9-8e44-0af781820e77.png)

**Comment by Tyriar** [comment] 2019-08-21 02:43
I noticed just now that the icons are actually swapped, _sass and Gemfile.lock should be swapped and yarn.lock and _layouts should be swapped.

**Comment by gjsjohnmurray** [comment] 2019-08-21 03:54
Possibly a dup of #79469

**Comment by ddzy** [comment] 2019-08-22 00:46
Same issue
![vscode_issue_1](https://user-images.githubusercontent.com/33921398/63477764-4a890b80-c4b9-11e9-8b20-5b485ae66fa8.png)

**Comment by aeschli** [comment] 2019-08-22 07:23
![image](https://user-images.githubusercontent.com/6461412/63493555-2f6bcb00-c4bc-11e9-98d0-bff88787b006.png)

Looks like explorer or tree issue. The tree item has the classes of an unrelated item.

When setting a breakpoint on getIconClasses and expanding nodes in the tree I see that every icon create seems to be first a clone from an existing icon. Is suspect that this is where the wrong classes come from.

**Comment by isidorn** [comment] 2019-08-22 08:29
This is coming from the IconLabel class which was changed by @bpasero recently thus also assigning him.
@bpasero let me know if it you think this is unrelated to your change and I can investgate.

**Comment by bpasero** [comment] 2019-08-22 08:55
@isidorn please check if a change in getUriLabel would have a consequence in the icons. The only change I did is to not clear the icon when there is a change in uri label: https://github.com/microsoft/vscode/blob/9c39bf2/src/vs/workbench/browser/labels.ts#L359

**Comment by isidorn** [comment] 2019-08-22 15:45
@bpasero what I think was happening is that luckily due to the uri label change the icon label got updated and fixed the issue. Now that we do not update on uri label change, the icon label does not get updated and reveales a bug which was there all along. Maybe the explorer does not properly clear css classes [here](https://github.com/Microsoft/vscode/blob/6a2726755df3caa894380a7a97d2c7889b630712/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L164) on Tree templates - since templates get reused and wrong classes end up on wrong elements..

@aeschli do you have exact repro steps how to get into this state? I can not seem to get it.

**Comment by aeschli** [comment] 2019-08-22 16:18
- enable the minimal icon theme
- in the vscode repo collapse all nodes
- expand 'node_modules' and look at all the icons. There are plenty of folders with file icons

**Comment by bpasero** [comment] 2019-08-22 17:32
@aeschli are you sure you are on latest? I do not see that (running out of master with a fresh user data dir):

![before](https://user-images.githubusercontent.com/900690/63536257-8224a180-c513-11e9-8d23-ddc2172faf0b.gif)

@isidorn 

> Now that we do not update on uri label change, the icon label does not get updated and reveales a bug which was there all along

But that is only true if the icon is being resolved depending on the URI label from the label service which I doubt and asked for initially.

**Comment by isidorn** [comment] 2019-08-23 09:41
I also can not reproduce with latest vscode insiders.
@bpasero icon resolving is not dependent on URI label. I was just speculating in my previous comment that a refresh comming later might have fixed an unrelated issue.

**Comment by bpasero** [comment] 2019-08-26 08:11
Closing since I cannot reproduce. @aeschli please verify.

**Closed by bpasero** 2019-08-26 08:11 UTC
Labels: bug, file-decorations

**Comment by aeschli** [comment] 2019-08-26 09:08
Verified that it's fixed in 
Version: 1.38.0-insider
Commit: 0f73473c08055054f317c1c94502f7f39fdbb164
Date: 2019-08-23T05:38:24.197Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic
