### ISSUE TITLE
feature for source navigation

### ISSUE THREAD

**Issue by laoshaw** [microsoft/vscode#44881] opened 2018-03-02 02:04 UTC
is it possible to do source navigation in vscode, i.e. track a function's topology(caller, callee relationship etc), something like a built-in source navigator(https://github.com/rogerz/sourcenavigator)? that will be really powerful to study and debug source code. the current peek/goto of definition/declaration are wonderful, adding API relationships will be great.

**Comment by mjbvz** [comment] 2019-10-08 00:43
Duplicate of #70231

**Closed by mjbvz** 2019-10-08 00:43 UTC
Labels: feature-request
