### ISSUE TITLE
Kernel font rendering problem.

### ISSUE THREAD

**Issue by bingxio** [microsoft/vscode#146399] opened 2022-03-31 08:15 UTC
There is a problem upgrading to 1.66. I like Monaco font very much. Usually I set bold for it, and the effect is good. However, after upgrading, the edge of the font is blurred, which is very ugly.
My system is win11. The font should be set in bold to look good. This problem also exists in browsers, such as chrome and edge. I set the bold font of Monaco on the GitHub code page, but the display is also shaded and not good-looking. It may be the problem of kernel update.
I wonder if you can add an option to render fonts to users. thank you.

**Comment by bingxio** [comment] 2022-03-31 08:17
It was used normally last year, and the browser updated at the beginning of the year changed this rule.

**Comment by alexdima** [comment] 2022-03-31 09:37
Could you please post a screenshot of the bad font rendering?

**Comment by bingxio** [comment] 2022-03-31 10:21
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/1.png)
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/2.png)
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/3.png)
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/4.png)

**Comment by bingxio** [comment] 2022-03-31 10:22
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/3.jpg)
![](https://raw.githubusercontent.com/bingxio/learning-programming-languages/master/4.jpg)

**Comment by bingxio** [comment] 2022-03-31 10:23
> Could you please post a screenshot of the bad font rendering?

This is the bold Monaco font of edge browser and vscode. There is a circle of shadow around the font. At the same time, I feel that the font is a little round. It was not like this before. It was very clear before.

**Comment by clzoc** [comment] 2022-03-31 14:50
#146387 I think we are talking about the same problem.

**Comment by deepak1556** [comment] 2022-03-31 16:50
Very likely a regression from https://bugs.chromium.org/p/chromium/issues/detail?id=1258378, refs https://bugs.chromium.org/p/chromium/issues/detail?id=1272163. Need to be confirmed /cc @rzhao271

**Comment by rzhao271** [comment] 2022-03-31 18:08
There's definitely been a regression.
On the left is Insiders, and on the right is Stable 1.65.2.
![Screenshot showing the Monaco bold font used to render in a much clearer way](https://user-images.githubusercontent.com/7199958/161121202-b84410f8-3ccf-4314-a5e3-63583b8410f3.PNG)

The following snippet also results in a blurry font on Chrome M99 and M100 and Edge M99.
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
    </head>
    <body>
		<style>
		p {
			font-family: Monaco;
			font-weight: bold;
		}
		</style>
		
		<p>Hello world!</p>
    </body>
</html>
```

**Comment by bingxio** [comment] 2022-04-01 04:56
> There's definitely been a regression. On the left is Insiders, and on the right is Stable 1.65.2. ![Screenshot showing the Monaco bold font used to render in a much clearer way](https://user-images.githubusercontent.com/7199958/161121202-b84410f8-3ccf-4314-a5e3-63583b8410f3.PNG)
> 
> The following snippet also results in a blurry font on Chrome M99 and M100 and Edge M99.
> 
> ```
> <!DOCTYPE html>
> <html>
>     <head>
>         <meta charset="utf-8" />
>     </head>
>     <body>
> 		<style>
> 		p {
> 			font-family: Monaco;
> 			font-weight: bold;
> 		}
> 		</style>
> 		
> 		<p>Hello world!</p>
>     </body>
> </html>
> ```

Yes, I have been using Monaco programming fonts, and later found this problem. Your example can better see the differences.

**Comment by rzhao271** [comment] 2022-04-01 23:32
Finally got Electron built properly.
Reverting the following commit in Chromium fixes the issue: https://chromium.googlesource.com/chromium/src/+/7ab45f6cdacd48ee07c428174e39e7abc0b5c256%5E%21/#F0

**Comment by bingxio** [comment] 2022-04-03 05:40
> Finally got Electron built properly. Reverting the following commit in Chromium fixes the issue: https://chromium.googlesource.com/chromium/src/+/7ab45f6cdacd48ee07c428174e39e7abc0b5c256

Is this last year's version updated on the browser? Now there is no way to solve this problem.

**Comment by deepak1556** [comment] 2022-04-04 04:32
@rzhao271 as mentioned in https://bugs.chromium.org/p/chromium/issues/detail?id=1258378#c13 the flag was added so that skia generates synthetic bold variants for these fonts rather than windows simulating the bold variants. Can you try the example snippet from https://github.com/microsoft/vscode/issues/146399#issuecomment-1084939173 with `font-synthesis: none` and see how it behaves.

**Comment by rzhao271** [comment] 2022-04-06 17:07
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1313968

**Comment by rzhao271** [comment] 2022-04-28 15:43
The issue is when a user does not have a bold font variant specifically installed for a given font, such as Monaco or Fira Code, the program has to find a way to synthesize the bold look of the font. Chromium changed the way their bold font synthesis worked, so now it doesn't match Firefox or Notepad.

I've filed an issue upstream, but Chromium has labelled the issue as a wontfix stating the result is as expected https://bugs.chromium.org/p/chromium/issues/detail?id=1313968#c13
Since we rely on Chromium for font synthesis not just for VS Code Desktop but for vscode.dev on Chromium-based browsers, we're labelling this issue as as-designed.

**Closed** 2022-04-28 15:43 UTC
Labels: bug, upstream, windows, *as-designed, font-rendering, confirmed, upstream-issue-linked, chromium, electron-17-update
