### ISSUE TITLE
systematically freeze on php doc

### ISSUE THREAD

**Issue by budus** [microsoft/vscode#62894] opened 2018-11-10 15:40 UTC
Issue Type: <b>Bug</b>

With a php file, vscode freeze systematically when I open it. After many test, I have discovered the line that causes the problem.

I tried to disable all the plug-ins and the file put it alone in a folder, but the problem persists.

I paste the code:
```php
<?php
	$record_output = "cf_id	cf_created\tcf_created_by\tcf_ipaddress\tSTR_SESSION_CODE\tFLAG_REQUEST_CHECKED\tFLAG_REQUEST_CLOSED\tFLAG_REQUEST_BILLED\tSTR_INDIRIZZO_EMAIL\ttipologia_attivita_concatenata\tSTR_DGA_DEN_ATTIV\tSTR_DS_RAGIONE_SOCIALE\tSTR_DS_LEGALE_RAPPRESENTANTE\tSTR_DS_TELEFONO\tSTR_DS_EMAIL\tSTR_INDIRIZZO_ATTIVITA\tSTR_INDIRIZZO_SEDE_LEGALE\tindirizzo_spedizione\tRADIO_INVIO_MANUALE_POSTA_ORDINARIA\tFLAG_PAGAMENTO_CONTRASSEGNO_POSTALE\tSTR_NOTE_AGGIUNTIVE\tSTR_NOTE_INTERNE\tSTR_FILENAME_UPLOADED\tinput_submit";
?>
```
I tried to change it, thinking the length was the problem, but it is not.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|4.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
vscode-emacs-friendly|lfs|0.8.2
vscode-language-pack-it|MS-|1.28.2

</details>

**Comment by alexr00** [comment] 2018-11-12 10:50
@roblourens, is this something you know anything about?

**Comment by roblourens** [comment] 2018-11-12 18:03
Yeah there are some similar issues like https://github.com/Microsoft/vscode/issues/46907

**Comment by connor4312** [comment] 2019-10-11 20:43
This appears fixed in recent versions, likely the same root cause as #75468

**Closed** 2019-10-11 20:43 UTC
Labels: *duplicate, bug, freeze-slow-crash, php
