### ISSUE TITLE
search then navigateBack usually takes you to the wrong place

### ISSUE THREAD

**Issue by JasonWoof** [microsoft/vscode#107055] opened 2020-09-19 04:14 UTC
- VSCode Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.5.0-2-amd64
- OS Version: Linux x64 5.5.0-2-amd64

Steps to Reproduce:

1. turn on search.searchOnType (Edit: this probably doesn't matter)
2. Make a text file containing these lines: "a", "b", "c", "aa", "bb", "cc"
3. Put your cursor at the beginning of the first line
4. Do a search (ctrl-F on linux) type "cc" in the search. Press Esc to exit the search
5. Do workbench.action.navigateBack (ctrl-alt-minus on linux)

Expected result: cursor back to the beginning of the first line (where it was before searching for "cc".)

Actual result: cursor moves to the third line (the single "c") and highlights the "c"... well usually it does. sometimes it glitches out and moves my cursor to a different tab entirely.

When it doesn't wig out and move me to a different tab, it appears to be moving the cursor to the incremental search result where the cursor was for a tiny fraction of a second between when I typed the first "c" in the search box and the second.

Strangely, it seems to do this even if I type the characters much quicker than search.searchOnTypeDebouncePeriod.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2020-09-22 19:00
Those search settings are actually for search across files (ctrl+shift+f) not the editor's find

**Comment by JasonWoof** [comment] 2020-09-22 23:21
Ahh, OK, so then you should be able to skip step 1 and still reproduce. Sorry I didn't test that.

**Comment by roblourens** [comment] 2020-09-23 01:30
> Expected result: cursor back to the beginning of the line

Which line, the cc line? I don't have expert knowledge of this particular code but I would guess that there will only be one history entry on that line because the selection starts at the same location. Then my guess is that the `c` line doesn't get saved in history and the random tab is just whatever was in history before that? Maybe typing quickly prevents the `c` line from being saved, but I can't repro this.

**Comment by JasonWoof** [comment] 2020-09-23 03:54
Oh, sorry, I initially had all the text on one line, but then thought it'd be clearer to explain with multiple lines, and forgot to update that part of my initial report.

Correction:

Expected Results: the cursor goes back to where it was before I searched, ie at the beginning of the first line.

**Comment by JasonWoof** [comment] 2020-09-23 04:12
@roblourens where does your cursor go when you hit navigateBack?

For me the `c` line _does_ get saved into the history. The point of this bug report is that it should not be saved.

I'm not sure what the issue here is. Is it that for you navigateBack takes you to where you were before searching? Or that you don't understand why it is problematic that it doesn't do this. Below I make arguments for why it should.

My basic premise is that I want to be able to navigate somewhere with search, and then press a key combo to get back.

Rather than doing this thing that would be useful, I argue that the current behavior of navigateBack (eg navigating to the "c" line) is not useful. Nobody wants to navigate to the first occurrence of the first letter they typed while looking for something longer.

If you save every incremental search result into the cursor movement history then it makes navigateBack very distracting and time-consuming to use, to the point where I no longer find it useful.

By "distracting" I mean that I have to pay attention to what it's doing (to check if it has put the cursor back to where I was before searching yet).

By "time-consuming" I mean that I often have to repeat this process, sometimes several times, and that if I try to do it quickly, and press navigateBack once too many times then I have to waste yet more time getting forwards to where I was.

Also, distraction is time-consuming. Anything that takes my attention away from what I'm thinking about slows down my thinking. Programming is usually more thinking than typing/editing (at least if your editor is efficient). UI that acts in unpredictable ways in response to the same keyboard input is distracting. The behavior of searching for "cc" then hitting navigateBack should not depend on irrelevant information (in this case whether there happens to be a "c" character in my document between my cursor and the search result.)

**Comment by roblourens** [comment] 2020-09-23 13:55
I see, thanks. You might prefer to set `"editor.find.cursorMoveOnType": false` then, this will prevent you from moving on type until you press enter and adding that incremental search history result. @rebornix can fill in whether there is a bug here.

**Comment by JasonWoof** [comment] 2020-09-23 16:18
@roblourens I like the search-as-I-type behavior, I just don't want it to break the navigateBack behavior.

**Comment by rebornix** [comment] 2020-10-12 21:49
While doing issue grooming, I found this issue is a /duplicate of https://github.com/microsoft/vscode/issues/78000. let's track it there.

**Closed** 2020-10-12 21:50 UTC
Labels: *duplicate, editor-find, feature-request
