### ISSUE TITLE
Navigation/Cursor Position with High Surrogate Pairs

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/vscode#31963] opened 2017-08-03 09:33 UTC
- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Have a file with a high surrogate pair character in it
2. Keyboard navigate and notice that there are _two_ positions for the cursor before the cursor moves, which affects copying and other positional items, including the `Col` number in the IDE

For example, this text will exhibit the problem:

```
|✔️|
```

Which contains the codepoint `U+2714`.

Reproduces without extensions: **Yes**

**Comment by rebornix** [comment] 2017-08-15 17:47
Duplicate of https://github.com/Microsoft/vscode/issues/19390 , thanks for reporting this issue.

**Closed by rebornix** 2017-08-15 17:47 UTC
Labels: editor, editor-core
