### ISSUE TITLE
Current line number no longer highlighted

### ISSUE THREAD

**Issue by Eldaw** [microsoft/vscode#86840] opened 2019-12-12 19:26 UTC
I've upgraded from v1.39.2 to v1.41.0 and I notice that the current line number (i.e. the line where the cursor currently is), is no longer highlighted/bolded.

Screenshots below (in both cases, the cursor was on line 33).

Version 1.39.2:
![image](https://user-images.githubusercontent.com/3789849/70742252-05f9d800-1d15-11ea-89e5-22435897a62d.png)

Version 1.41.0:
![image](https://user-images.githubusercontent.com/3789849/70742317-232ea680-1d15-11ea-9004-ee9514b372ce.png)

Running on Windows 10.

**Comment by gjsjohnmurray** [comment] 2019-12-12 20:11
Do your settings include one for `editor.renderLineHighlight` ?

What color theme are you using?

**Comment by Eldaw** [comment] 2019-12-12 20:14
No, my settings don't include anything for edit.renderLineHighlight, so that's using whatever is default.

Color Theme: Dark+ (default dark)

**Comment by gjsjohnmurray** [comment] 2019-12-12 20:15
Please see https://github.com/microsoft/vscode/issues/84772#issuecomment-554053601 as I think yours is a duplicate of this issue.

**Comment by rebornix** [comment] 2020-01-28 00:17
The default value for rendering line highlight is `line`, which doesn't highlight the gutter. You can use `gutter` or `all` to turn it on.

**Comment by Eldaw** [comment] 2020-01-28 02:22
@rebornix It's not really the same thing though, is it? You've closed this issue too quickly.

With "editor.renderLineHighlight": "all", take a look at a word-wrapped lined, for example. Position your cursor on the 2nd or 3rd wrapped line and tell me if the number in the left gutter (for the physical line) gets bolded.

Also, look at my screenshot for how things were in v1.39.2. There, the physical line number is bolded without the need for the top-and-bottom lines that surround the text to be extended into the left gutter.

**Comment by rebornix** [comment] 2020-11-05 23:10
Let's track this in https://github.com/microsoft/vscode/issues/84772.

**Closed by rebornix** 2020-11-05 23:10 UTC
Labels: bug, editor-rendering
