### ISSUE TITLE
rxjs `switch()` method breaks syntax highlighting

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode#12258] opened 2016-09-19 09:30 UTC
- VSCode Version: 1.5.2
- OS Version: Windows

Steps to Reproduce:

1 Paste the following code into a new file `foo.ts`

```
declare const Observable: any;

const interval$ = Observable.interval(1000);

interval$
    .map(x => Observable.fromEvent(window, 'click').takeUntil(interval$.filter(x => x > 10000)))
    .switch()
    .subscribe(foobar);

function foobar(x) {
}
```

2 Notice syntax highlighting for the code after the `switch()` method call no longer works:

![image](https://cloud.githubusercontent.com/assets/2899448/18627539/c5386724-7e5b-11e6-95ad-63dc3f88e22f.png)

3 Uncomment the `switch()` method call and notice all is fine with the syntax highlighting:

![image](https://cloud.githubusercontent.com/assets/2899448/18627599/206f2df8-7e5c-11e6-9f10-2c671233bfbf.png)

I believe that VSCode is getting confused because `switch` is also a Javascript statement.

**Comment by chrmarti** [comment] 2016-09-20 03:57
Duplicate of Microsoft/TypeScript-TmLanguage#244 (A larger change with many fixes is being prepared. It's not clear yet which release it will make.)

**Closed by chrmarti** 2016-09-20 03:57 UTC
Labels: bug, duplicate

**Comment by wmaurer** [comment] 2016-09-20 06:56
@chrmarti I see, I didn't realise that it's a TS grammar issue. Thanks, I look forward to seeing the fix in VSCode sometime in the future.
