### ISSUE TITLE
[Feature request] Support 'always scroll' in output channel

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#64515] opened 2018-12-06 13:12 UTC
Current `Smart scrolling behavior` introduce some unexpected behavior, see https://github.com/Microsoft/vscode/issues/56974 .

Several [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) users complain about the output window does not automatically scroll down. In previous version of VS code, it works normally.

If current behavior is by design, then it would be a FR to add an option to support 'always scroll'. 😄

**Comment by isidorn** [comment] 2018-12-06 17:09
Assigning to @sandy081 since you closed that one as designed.
If you do not have time to look into this, assign back to me and I can check what is broken. And we should not introduce any new configuartion

**Comment by sandy081** [comment] 2018-12-07 10:40
@isidorn #56974 was marked as designed because of https://github.com/Microsoft/vscode/issues/49110 which is the PR you accepted. 

There is another issue https://github.com/Microsoft/vscode/issues/63525 where this is complained already. Hence marking as dup.

**Closed by sandy081** 2018-12-07 10:40 UTC
Labels: *duplicate, outline
