### ISSUE TITLE
Report issue button in a cramped spot

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64345] opened 2018-12-04 14:40 UTC
Refs: #64222

I did not want to create UX issues for running extensions view, for that I simply created this item https://github.com/Microsoft/vscode/issues/64344

This one I only created because it feels like a minor regression

Previosuly the report issue was aligned to the right. This I personally prefered because it was not in a cramped spot with everything else on the left. And because it was using the horizontal space which we have planty in this view.

I suggest to move it back to the right.

P.S I like that we now do not show this button for every extension

![screenshot 2018-12-04 at 15 40 33](https://user-images.githubusercontent.com/1926584/49449336-f4652280-f7da-11e8-83ba-04fb28d2be65.png)

**Comment by jrieken** [comment] 2018-12-05 07:51
closing as dupe of #64344. I also don't like it much but the code is a mess and it serves its purpose. Not keen on investing more into something we are going to nuke.

**Closed** 2018-12-05 07:51 UTC
Labels: *duplicate
