### ISSUE TITLE
window.restoreWindow isn't honored

### ISSUE THREAD

**Issue by SeanTAllen** [microsoft/vscode#77924] opened 2019-07-24 13:16 UTC
Issue Type: <b>Bug</b>

When using VSCode with remote WSL2 projects, the "window.restoreWindows" settings I have of "none" is ignored and editors for the previous session are restored. 

This also applies when code is started with the `-n` option. It is ignored and the previous session is restored.

This behavior is not seen when not using the Remote - WSL extension.

Extension version: 0.38.10
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18941
Remote OS version: Linux x64 4.19.43-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.48GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/sean/code/ponylang/pony-stable --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.43-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|14.58GB (14.37GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment] 2019-10-15 08:04
The current design is to only restore local windows. Opening a remote window can involve a download and building up a connection, so we thought to only do this if the user really wants it.

Are you suggesting that we remote local windows when the open comes from the remote itself (e.g. `code` from a WSL shell?

**Comment by Rynhho** [comment] 2020-04-01 16:48
When running version 1.43 freshly installed, setting window.restoreWindow to off doesn't work at all, it still restores previous windows.

Proof: https://www.youtube.com/watch?v=oi7vU5lUiZM&feature=youtu.be

**Comment by aeschli** [comment] 2020-04-01 20:33
@Rynhho The window with the 4 folders is an unsaved, untitled workspace. 
These are always restored as it would be a loss of data as they can't be restored in any other way.
Would you mind filing a new issue?

**Comment by aeschli** [comment] 2020-04-01 20:38
@SeanTAllen When `restoreWindows: none` is set, we still restore all unsaved and untitled workspaces as well as all empty windows with unsaved editors in them.
Is that what you are seeing?

As explained, the rational for that is that if they weren't restored there's no way to get them back again.

**Comment by Rynhho** [comment] 2020-04-03 20:43
> 
> 
> @Rynhho The window with the 4 folders is an unsaved, untitled workspace.
> These are always restored as it would be a loss of data as they can't be restored in any other way.
> Would you mind filing a new issue?

Oh okay I didn't knew that. Do I still fill a new issue? This seems like good behaviour actually.

**Comment by aeschli** [comment] 2020-04-05 10:47
No need to file an issue if you are fine with that behavior :smile:

**Comment by Rynhho** [comment] 2020-04-06 12:55
> 
> 
> No need to file an issue if you are fine with that behavior 😄
> What we could look into is to add an entry to the recent history as an alternative way to restore the workspace @bpasero

And display a message of recovery otherwise the user might forgot about that workspace :)

Thank you for your time.

**Comment by openingnow** [comment] 2020-08-04 16:54
Looks like bug filed by Sean is not fixed. Window is restored when I open same workspace in remote-WSL.

**Comment by aeschli** [comment] 2020-08-12 12:11
@openingnow Can you please give precice steps? What do you mean by 'open same workspace in remote-WSL` ?

**Comment by aeschli** [comment] 2020-08-12 13:13
From my testing, `"window.restoreWindows": "none"` now properly works (with the rule as explained here: https://github.com/microsoft/vscode/issues/77924#issuecomment-607477725)

If you still see issues, please give add steps to reproduce.

**Comment by openingnow** [comment] 2020-08-15 02:55
I mean 'restoring state when reopening workspace '. Found it also happens without WSL environment. Maybe it is a desired behavior, right?

**Comment by aeschli** [comment] 2020-08-17 08:15
@openingnow Do you mean using the `Reopen in WSL` command? The `window.restoreWindow` is for something different.
If you want the  `Reopen in WSL` command to be improved. please file an issue against https://github.com/microsoft/vscode-remote-release an describe how.

**Comment by aeschli** [comment] 2020-11-06 10:56
Closing as already fixed. Please file a new issue with steps if you still have trouble.

**Closed by aeschli** 2020-11-06 10:56 UTC
Labels: feature-request, remote
