### ISSUE TITLE
Clearing VS built-in terminal on macOS

### ISSUE THREAD

**Issue by iband** [Microsoft/vscode#11242] opened 2016-08-30 18:11 UTC
- VSCode Version: 1.4
- OS Version: macOS 10.11.6

With 1.3+ updates developers removed shortcut to clear integrated terminal output (previously it was Cmd+K). Is there any new shortcut for clearing output now?

**Comment by Tyriar** [comment] 2016-08-31 20:26
This was never implemented for the terminal, it exists for the output panel though. Duplicate of #6603

**Closed by Tyriar** 2016-08-31 20:26 UTC
Labels: integrated-terminal
