### ISSUE TITLE
Support preview a WorkspaceEdit

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#77728] opened 2019-07-22 02:30 UTC
For many refactoring actions (e.g. Move Java file, Rename Java class/package name), it possibly involves updating multiple files, which is especially true for refactoring some big projects.  If the VS Code supports preview the changes of a refactoring WorkspaceEdit before applying, this will help the user discover the potential refactor effects in advance and decide whether to continue the operation.

Generally a WorkspaceEdit contains text edits (Insert, Delete) and resource edits (CreateFile, DeleteFile, RenameFile), they are naturally diffs, and very suitable for preview.

**Comment by jrieken** [comment] 2020-01-13 08:40
I have merged https://github.com/microsoft/vscode/pull/88428 which implements a first version of this: 👇 

What's implemented

* Refactor preview shows all changes - currently only grouped by file
* Show diff view for each change
* Check/Uncheck individual changes or all changes per file
* Detect concurrent file changes 
* Restore previous view state when accepting/discarding changes

![Jan-13-2020 09-34-23](https://user-images.githubusercontent.com/1794099/72241766-fad1ea80-35e7-11ea-8fdf-f3075a30aaba.gif)

What's still missing and/or unclear

* There is no API yet to allow extension to suggest that a preview is necessary, for now the rename box allows the user to chose
* This is currently only enabled for rename as the UX flow for code actions isn't clear yet
* Changes are only grouped by files, e.g there is no support to group by change type like "change in a comment" etc. This will also require new API.

**Comment by jrieken** [comment] 2020-01-13 08:43
/cc @bobbrow

Wrt to knowing if a preview for rename is needed or not: Does C/CPP know this during the [`prepareRename`](https://github.com/microsoft/vscode/blob/5c02e4b2a149c1e2e9bb03b267d3b6727607cf72/src/vs/vscode.d.ts#L3031)-call? We could extend its return-type so that it can signal if a preview is required or optional

**Comment by bobbrow** [comment] 2020-01-13 15:56
Very cool.  @colengms should be able to help you answer your question.  I don't see an implementation of `prepareRename` currently.

**Comment by Colengms** [comment] 2020-01-13 21:17
Hi @jrieken .  Do you mean `provideRenameEdits`?  My understanding is that `prepareRename` is optional, and used to validate whether the target position of the rename is valid.

Currently, we are using only `provideRenameEdits`.  Could you clarify why we might want to use `prepareRename` as well?

In our current implementation, if all of the matches found are known to be associated with the selected symbol, we return results from `provideRenameEdits` immediately.  Otherwise, we present UI to allow the user to categorically and individually select what to rename (to opt into things such as matches in comments), and reissue the rename in order to complete it with the selected results.

Are you suggesting we leverage preview instead of our own UI, and make preview required in the scenarios in which we would otherwise have presented our own UI?  If so, yes, we would need a way to return that preview is required, but wouldn't that be when returning from `provideRenameEdits`, as we would discover whether preview is required in the process of scanning for all candidate locations?

**Comment by jrieken** [comment] 2020-01-14 07:55
> Are you suggesting we leverage preview instead of our own UI, and make preview required in the scenarios in which we would otherwise have presented our own UI? If so, yes, we would need a way to return that preview is required, but wouldn't that be when returning from provideRenameEdits, as we would discover whether preview is required in the process of scanning for all candidate locations?

Yes - the plan is to have one UX that works across different language extensions and across different code actions like rename but also for things like "extract function" etc. 

For this and to provide a honest rename input box we need to know upfront if a rename needs a preview or not. That's why I am bringing up `prepareRenameEdits`. We call that before showing the UX and with some extra information returned by it we can tell the user that a preview will be showing when renaming an element.

**Comment by akaroml** [comment] 2020-01-15 05:36
@jdneo will try this on Java projects and provide some feedback.

**Comment by jdneo** [comment] 2020-01-16 03:29
Some findings:

1. Depend on the `workspaceEdit` returned from the Language Server, sometimes the preview panel may contains several changes in one line
![image](https://user-images.githubusercontent.com/6193897/72490036-f3f9e080-3850-11ea-84e2-14ba9a7f12c9.png)
If the user's screen is not wide enough, some part of the changes cannot be seen in the `Refactor Preview` panel. But maybe this should be the language server's task to split the `workspaceEdit` instead of merging them into one? Or maybe VS Code can split the diff according to different lines?

2. If the user just close the preview editor instead of clicking the `Discard changes` button. He cannot rename from the preview panel anymore
![demo](https://user-images.githubusercontent.com/6193897/72490848-489e5b00-3853-11ea-9895-d118d22ed80c.gif)

**Comment by jrieken** [comment] 2020-01-16 09:18
> Depend on the workspaceEdit returned from the Language Server, sometimes the preview panel may contains several changes in one line

Yeah, that the design. The list will show each change as computed by the language service. Tbh, I wouldn't make the language service make the change be optimised for the list view as we expect most users to open the diff editor in such cases


> If the user just close the preview editor instead of clicking the Discard changes button. He cannot rename from the preview panel anymore

Good find. I will push a fix for that. Thanks

**Comment by jrieken** [comment] 2020-01-16 17:37
api ideas

```ts
interface WorkspaceEditMetadata {
	label: string
	icon: ThemeIcon | {light: Uri, dark: Uri};
	check: boolean;
}

export class WorkspaceEdit {
	appendTextEdit(uri: Uri, edit: TextEdit, metadata?: WorkspaceEditMetadata):void;
}
```

* Use `metadata#label` for grouping, e.g 'changes in strings' or 'inactive'
* Trigger preview when one metadata-object is `check = false`

**Comment by jrieken** [comment] 2020-01-16 17:38
For the next stable release: 

- [ ] add setting to enable/disable preview per language

**Comment by jdneo** [comment] 2020-01-17 05:27
> api ideas
> 
> ```ts
> interface WorkspaceEditMetadata {
> 	label: string
> 	icon: ThemeIcon | {light: Uri, dark: Uri};
> 	check: boolean;
> }
> 
> export class WorkspaceEdit {
> 	appendTextEdit(uri: Uri, edit: TextEdit, metadata?: WorkspaceEditMetadata):void;
> }
> ```
> 
> * Use `metadata#label` for grouping, e.g 'changes in strings' or 'inactive'
> * Trigger preview when one metadata-object is `check = false`

Hi @jrieken, Could you explain more about this? How will these APIs affect the preview?

**Comment by akaroml** [comment] 2020-01-17 07:04
I'm specifically interested in the role of the `check` field in the `WorkspaceEditMetadata`. Thanks.

**Comment by jrieken** [comment] 2020-01-17 09:05
Sure, these were merely meeting notes and not really fleshed out yet... 

We are working on supporting scenarios in which an extension can "classify" changes which won't be applied by default. Cpp already does that (with some custom UX) - the screen capture below shows how there are two candidate changes: one inside a string, one inside an inactive ifdef. The language service can suggest them but has low confidence and therefore human approval is needed. 

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1794099/72598213-a4c6b500-390f-11ea-9af0-7ffda0ce735b.png">

The api sketch above is to support this scenario, e.g `check: boolean` would set the state of the checkboxes that we are rendering. The label and icon property can then be rendered inline and/or drive a tree, e.g all changes in strings can become a tree-node all changes in ifdefs become another node etc.

Also, when a change is unchecked then that would be a signal for us to force show the preview. Otherwise we are likely making this depended on a user setting, e.g I have added `editor.rename.enablePreview` so that user can express their preference.

**Comment by jrieken** [comment] 2020-01-17 10:16
@bobbrow fyi - the setting to enable/disable preview is now called `editor.rename.enablePreview`

**Comment by bobbrow** [comment] 2020-01-17 16:29
Thanks @jrieken!  For the setting, I read this description in your commit:
`Enabe/disable the ability to preview changes before renaming`.  (also: typo with "Enable")

If it's disabled, does that mean you won't show the preview even if the language server requests it?  I'm thinking about what happens after we migrate to use this new feature and remove our language setting and our custom implementation.  If the developer disables the preview on their own, will you ever show it?  My guess is that vscode could still override the setting if the language server sends a metadata object with `check` = `false`.  The setting will only apply when "regular" WorkspaceEdits are sent in reponse to a rename request?

**Comment by jrieken** [comment] 2020-01-20 08:04
> f the developer disables the preview on their own, will you ever show it? My guess is that vscode could still override the setting if the language server sends a metadata object with check = false.

Yeah, that's that plan. The setting is your preferred behaviour but if via API uncertainty is expressed (internally I have now called the property `needsConfirmation`) then we will always show the preview

**Comment by jrieken** [comment] 2020-01-20 14:35
Current API proposal for annotating changes with metadata. The `WorkspaceEditMetadata#label` property is used to group item together, e.g all items with labels "string reference" etc

https://github.com/microsoft/vscode/blob/63142fc2cbb200c8ca8690ba680e4c4d054d749b/src/vs/vscode.proposed.d.ts#L1556-L1575

**Comment by akaroml** [comment] 2020-01-21 03:05
The proposed API looks good to me. @jdneo please also check it out.

**Comment by Colengms** [comment] 2020-01-22 00:09
Hi @jrieken .  I tried this out in cpptools and 1.42.0-insiders.  It looks like it'll be extremely easy to switch to using this API instead of our own UI for Rename.

I noticed a few issues: 
 - File nodes are initially checked even if they don't contain any checked children.  Although unchecking will disable child checkboxes, re-checking the file does not check child checkboxes.
 - The icon we specified doesn't appear to be used.
 - Should the group (based on label) have a checkbox?  It might be useful to enable/disable entire categories of changes.
 - Should groups have icons?
 - The edit is blocked if files are modified ("Cannot apply refactoring because # other files have changed in the meantime"), even if those files have nothing to do with the rename operation.  This happens even if the file type of the changed file is not handled by the same extension.  i.e. Adding a txt file to the folder causes this.  Removing a file causes this as well (and indicates that 3 files were changed, when only 1 was removed?).

**Comment by jrieken** [comment] 2020-01-22 15:09
Thanks for feedback. Some UX tweaks have already happened or are happening these days. Wrt to conflicts:

> even if those files have nothing to do with the rename operation. This happens even if the file type of the changed file is not handled by the same extension. i.e. Adding a txt file to the folder causes this.

There are some bugs that need to be ironed out but generally that's how it supposed to work. E.g if any file (truly) changes while a refactoring is pending then we potentially have a problem. It might be the your project file, it might be new references that have been introduced etc. That's why we at least need to show a warning, for rename specifically we might be able to guide you into re-trying

**Comment by jrieken** [comment] 2020-02-13 10:41
@Colengms @jdneo We are planning to finalise the `WorkspaceEditMetadata`-API for this milestone and it would boost our confidence if you can give some dry-run: 

https://github.com/microsoft/vscode/blob/760cb13de8205deb4131581b399f5d71830f9dce/src/vs/vscode.proposed.d.ts#L1414-L1452

For some tyre-kicking you can use my sample extension that has served us during testing: https://github.com/microsoft/vscode/issues/89335#issue-555528019

**Comment by Colengms** [comment] 2020-02-13 21:42
Hi @jrieken .  I tried it out again with our rename provider.  I still have the following feedback:

* The icon we specified is not used.  We are specifying `{ light, dark }` and using relative paths.  The same works properly with a TreeDataProvider.

* Should groups be sorted? It's unclear what the current sort order is, when sorting by group.  We'd like to put our 'confirmed' references at the top of the list. Perhaps we could get by with alphabetic sorting by prefixing our 'confirmed' label with a space.

* Should the group (based on label) have a checkbox? It might be useful to enable/disable entire categories of changes.  Currently, if the user knows they want to rename all occurrences, they need to check each file individually (there could be many).

**Comment by jrieken** [comment] 2020-02-14 08:58
> The icon we specified is not used. We are specifying { light, dark } and using relative paths. The same works properly with a TreeDataProvider.

Understood - I went with the usage of [`QuickInputButton#iconPath`](https://github.com/microsoft/vscode/blob/efb781e5becac763a91e7a7434aaef671b38d9a9/src/vs/vscode.d.ts#L8062) which only supports URI. You have have seen a compile error when passing light, dark as string only...


> Should groups be sorted? It's unclear what the current sort order is, when sorting by group. We'd like to put our 'confirmed' references at the top of the list. 

:+1: That was an oversight 

> Should the group (based on label) have a checkbox? It might be useful to enable/disable entire categories of changes. Currently, if the user knows they want to rename all occurrences, they need to check each file individually (there could be many).

We discussed that in UX call and was some push-back on having too many check boxes but I do agree with the use-case. That's also something we can easily tweak after the fact.


Overall, for the API proposal I see a thumbs up, right.

**Comment by jrieken** [comment] 2020-02-18 16:50
Suggestion to rename `WorkspaceEditMetadata ` to `WorkspaceEditEntryMetadata`

**Comment by Colengms** [comment] 2020-02-18 21:28
>>The icon we specified is not used.
>
>I went with the usage of QuickInputButton#iconPath which only supports URI. 

@jrieken .  Uri's don't seem to be working for me either.  The file referred to in the following image is present on disk: 

![image](https://user-images.githubusercontent.com/49173979/74778869-4e6fcd80-5251-11ea-81ce-584c089dda21.png)

When this happens, I see the following in the console log output (not sure if related) :

![image](https://user-images.githubusercontent.com/49173979/74779138-cb9b4280-5251-11ea-85e9-36a98973ffa7.png)

I see this error recur as I scroll through the refactor preview list.

Otherwise, the API is looking good to me.

**Comment by jrieken** [comment] 2020-02-19 09:15
Understood - I missed the single-icon case, had only the `{light, dark}`-case implemented... This should finally be working

**Closed** 2020-02-20 09:11 UTC
Labels: api-finalization, feature-request, workspace-edit

**Comment by jrieken** [comment] 2020-02-21 15:57
To verify: 

- make sure the API is in `vscode.d.ts` and works without enabling proposed API
- make sure refactor preview works

**Comment by Colengms** [comment] 2020-03-16 21:31
Hi @jrieken .  I see that this shipped, based on the release notes for VS Code 1.42.0.

What is the correct way to get the updated API?  I gather the `vscode` module is deprecated, as it hasn't been updated for 8 months.  Using `@types/vscode` version 1.42.0 (or 1.43.0), I do not see the new API.  Is there something else I need to do to get the latest shipping VS Code API?
