### ISSUE TITLE
Clicking to activate a window should not move the insertion point

### ISSUE THREAD

**Issue by abhibeckert** [microsoft/vscode#108151] opened 2020-10-06 01:19 UTC
- VSCode Version: 1.49.2
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open any document
2. Switch to some other window (e.g. a web browser)
3. Click somewhere in the source code on the VS Code document

The VS Code window will activate, and the insertion point will move to wherever you clicked.

At least on a Mac, this is improper behaviour. The insertion point should not move when activating a window. Moving the insertion point should require a second click. I'm unsure of the correct behaviour on Windows.

Having decades of learned habits, I find this extremely disruptive. I often click a window then start typing, only to find I'm editing the wrong line of code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2020-12-09 14:51
Actually, this looks like a generic Electron issue, if I focus on a different application and click in vscode, regardless where I click (like in the explorer, in the search viewlet input) the focus moves immediately to that location. This does not reproduce on Chrome, where there the first click focuses the window and only the second click goes to the actual dom content.

**Comment by autumnblazey** [comment] 2022-07-11 23:07
I find this disruptive too.

I believe this is known as "first click"? first click being the first click on the window since it is moved into the background. On windows the application typically handles the first click (Linux too I believe?), and on Mac applications typically do not handle the first click, and all the first click does is focus the window.

**Comment by autumnblazey** [comment] 2022-07-20 02:04
Thought: I do not believe it is a generic electron issue. I have a few other electron apps on here, and vscode is the _only_ one that does not respect first click. I have a feeling there is code somewhere in the codebase that specifically overrides this, but I have not looked

**Comment by deepak1556** [comment] 2022-12-12 17:55
This is a side-effect of focusing the WebContents to support our singleton instance implementation. Closing as not actionable.

**Closed by deepak1556** 2022-12-12 17:55 UTC
Labels: upstream, macos

**Comment by autumnblazey** [comment] 2023-01-24 00:26
I was idly browsing through settings (don't question it), and I stumbled upon a setting `window.clickThroughInactive` that is on by default, and when turned off, yeets this behaviour and makes it consistent with the rest of macOS! This appears to be exactly what I needed. Perhaps it can be considered to have this setting be off by default on macOS so it is consistent with the rest of the OS?
