### ISSUE TITLE
Right click menu does not stay open for markdown cells

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#134601] opened 2021-10-07 19:34 UTC
Issue Type: <b>Bug</b>

Open notebook
Add markdown cell
While editing try right clicking

Context menu flashes and closes

VS Code version: Code - Insiders 1.61.0-insider (2dc8b9580809148e312356852affc4b8d4feb7da, 2021-10-06T08:22:53.147Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (15.31GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.1
prettier-vscode|esb|9.0.0
better-cpp-syntax|jef|1.15.10
vscode-position|jtr|1.0.3
regexp-preview|Lou|0.1.5
Angular-BeastCode|Mik|10.0.3
python|ms-|2021.11.1317334950-dev
vscode-pylance|ms-|2021.10.1-pre.1
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools-extension-pack|ms-|1.0.0
rpa-eslint-snippets|rav|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis200:30374795
vsaa593:30376534

```

</details>

**Comment by roblourens** [comment] 2022-06-10 18:58
I can't repro on windows or mac. If it's still an issue, it's likely the same cause as https://github.com/microsoft/vscode/issues/125109

**Comment by rebornix** [comment] 2024-12-12 22:49
I'm not able to reproduce, closing for now.

**Closed by rebornix** 2024-12-12 22:49 UTC
Labels: bug, help wanted, notebook-markdown
