### ISSUE TITLE
files.excludes not work

### ISSUE THREAD

**Issue by iulo** [Microsoft/vscode#17284] opened 2016-12-15 09:36 UTC
- VSCode Version: 1.8.0
- OS Version: win10

![screenshot](https://cloud.githubusercontent.com/assets/6769037/21218758/c846e44c-c2ec-11e6-824a-60d50ea1e887.png)

**Comment by mjbvz** [comment] 2016-12-15 22:27
I believe this is a duplicate of #6502

**Closed by mjbvz** 2016-12-15 22:27 UTC
Labels: duplicate
