### ISSUE TITLE
iPad Pro support

### ISSUE THREAD

**Issue by galvesribeiro** [microsoft/vscode#83123] opened 2019-10-23 03:58 UTC
Hellow folks!

Assuming that we now have support for VSCode to run extensions on remote devices (thanks A LOT to the remote extensions feature!) we have a chance to run VSCode editor on iOS devices so we could leverage more "mobile" workstations like iPad Pro. We were limited before by able because everything should be AOT'ed and no code could be generated (i.e. JIT or compilers) on iOS. 

With the remote extensions support we could for example run OmniSharp on a remote device or Docker container and still use VSCode on iPad as it would be just editing the files remotely on the device/container filesystem.

So, with that in mind:

1. Is there any plans from MSFT to bring that support officially to iOS devices?
2. If not, or if it is not a priority on the roadmap, can someone from the team shed a light on what would take to get it to work so the community could lead this work and make it happen?

I'm pretty sure that it would for the best interest of the community to have this scenario enabled as more and more iPad Pros are getting used if not as main, as a very important secondary machines for developers.

Thanks! I really appreciate any comments on that and I really believe it is something that the community could quickly submit a PR and make it happen!

Best regards and keep the awesome work on this awesome product! 😄

**Comment by egamma** [comment] 2019-10-28 10:12
Duplicate of #70764

**Closed by egamma** 2019-10-28 10:12 UTC
Labels: *duplicate
