### ISSUE TITLE
Chain suggestions not working

### ISSUE THREAD

**Issue by Foscat** [microsoft/vscode#112669] opened 2020-12-16 17:44 UTC
On the previous versions you would get suggestions that displayed keys and methods on a object or valid attributes on a element. This no longer works I only see spelling suggestions of stuff close to the text in other open files. This is happening for me in JavaScript, HTML and CSS it seems that all suggestions outside of general text are broken.

**Comment by platon-rov** [comment] 2020-12-20 21:18
For me at the last version i see only one suggestion: 

![image](https://user-images.githubusercontent.com/20265336/102724601-5e48ba00-4319-11eb-9d5d-3e7a6d81aced.png)

What's strange - there exist another suggestions and i even can jump over them with the buttons:

![image](https://user-images.githubusercontent.com/20265336/102724622-89cba480-4319-11eb-8486-5c7d8f6d92f9.png)

So, the suggestion panel height set to 1 line only but why?

Info:
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-7630-generic
```

**Comment by jrieken** [comment] 2020-12-21 07:33
This information you have provided is insufficient and doesn't allow me to reproduce. Please provide: minimal but full code sample, what language is this, what extensions are you using

**Comment by platon-rov** [comment] 2020-12-21 09:12
For me it's reproducable in any `TypeScript React`/`Typescript`/`JavaScript` file.

That's my setting:
```
 {
  "git.autofetch": true,
  "git.confirmSync": false,
  "workbench.tree.indent": 20,
  "workbench.iconTheme": "material-icon-theme",
  "editor.fontLigatures": true,
  "editor.fontFamily": "Fira Code Retina",
  "editor.codeActionsOnSave": {
    "source.fixAll.tslint": true
  },
  "window.zoomLevel": 0,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "workbench.colorTheme": "Solarized Light",
  "editor.smoothScrolling": true,
  "editor.cursorSmoothCaretAnimation": true,
  "workbench.list.smoothScrolling": true,
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
}
```

And my extensions:
![image](https://user-images.githubusercontent.com/20265336/102759894-69cdcc80-437d-11eb-8796-836ddbe0337b.png)

**Comment by platon-rov** [comment] 2020-12-21 09:40
For me it's reproducable in any js/ts file.

My settings: 
```
{
  "git.autofetch": true,
  "git.confirmSync": false,
  "workbench.tree.indent": 20,
  "workbench.iconTheme": "material-icon-theme",
  "editor.fontLigatures": true,
  "editor.fontFamily": "Fira Code Retina",
  "editor.codeActionsOnSave": {
    "source.fixAll.tslint": true
  },
  "window.zoomLevel": 0,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "workbench.colorTheme": "Solarized Light",
  "editor.smoothScrolling": true,
  "editor.cursorSmoothCaretAnimation": true,
  "workbench.list.smoothScrolling": true,
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
}
```

And extensions:
![image](https://user-images.githubusercontent.com/20265336/102762570-24130300-4381-11eb-80a1-349d2c46847f.png)

VSCode: 
![image](https://user-images.githubusercontent.com/20265336/102762598-31c88880-4381-11eb-80ac-0b4039688bf3.png)
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-7630-generic
```

VSCode Insiders:
![image](https://user-images.githubusercontent.com/20265336/102762669-47d64900-4381-11eb-86fd-4414c24261da.png)
```
Version: 1.53.0-insider
Commit: c927a8015b9e26bd454d6e293bb0384aa1975d06
Date: 2020-12-18T05:27:50.274Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.8.0-7630-generic
```

**Comment by jrieken** [comment] 2020-12-21 11:30
Thanks for clarifiying. This is actually a duplicate

/duplicate of #110554 (comment)

**Comment by jrieken** [comment] 2020-12-21 11:30
see https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206

**Closed** 2020-12-21 11:30 UTC
Labels: *duplicate, needs more info, suggest
