### ISSUE TITLE
Explorer File/Folder Filter

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#17422] opened 2016-12-16 22:02 UTC
- VSCode Version: 1.8.0
- OS Version: Ubuntu 16

With npm 3, the `node_modules` folder gets fairly large, so it would be nice if there was an input box in the `explorer` menu that I could type into and it would hide items that don't match the search.

For example when I am looking for a particular folder such as `materialize-css` I could just type `material` into the search box and all matching files/folders would be left in the view and everything would get hidden.

**Comment by kieferrm** [comment] 2016-12-16 22:05
Duplicate of #11486.

**Comment by TheColorRed** [comment] 2016-12-16 22:07
@kieferrm I don't want to hide the folder though. I want it visible, I just want to have a quick find of a folder.

**Comment by bpasero** [comment] 2016-12-17 08:15
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Closed by bpasero** 2016-12-17 08:15 UTC
Labels: duplicate

**Comment by TheColorRed** [comment] 2016-12-17 15:32
@bpasero What I am asking for has not been reported, at least I can not find it. What @kieferrm reports is a duplicate is not what I am asking for either, as that is to toggle folders on/off that have been disabled.

What I would like is to be able to search through my massive list of folders in a similar way you search for a file `workbench.action.quickOpen`.

**Comment by kieferrm** [comment] 2016-12-17 15:46
@TheColorRed the overall topic of what you describe is currently being tracked in #10026. It's not your precise description (this would be #9373) which is also a dup of #10026.

**Comment by TheColorRed** [comment] 2016-12-17 15:52
Thank you!
