### ISSUE TITLE
The Solarized Dark theme can not show well

### ISSUE THREAD

**Issue by vitahlin** [microsoft/vscode#110703] opened 2020-11-16 07:20 UTC
- VSCode Version: visual-studio-code: 1.51.1 (auto_updates)
- OS Version: macOS Big Sur 11.0.1

Steps to Reproduce:

1. The Solarized Dark color theme looks unclearly in new version
![image](https://user-images.githubusercontent.com/6998610/99223125-e3264c80-281e-11eb-9f4e-fe47169d5b53.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment] 2020-11-16 14:07
Duplicate of #100840

**Closed by aeschli** 2020-11-16 14:07 UTC
