### ISSUE TITLE
I hope there're a new feature or a plugin to load plugins which I need it in a project

### ISSUE THREAD

**Issue by TremblingV5** [microsoft/vscode#120351] opened 2021-04-01 15:13 UTC
I always use VS Code to write different language: Python, Java etc. I found that some plugins are suitable for Python and some are suitble for Java. Load the extra pulgins will let me wait for more time and my UI will be dazzled.

So I hope there're are a new feature or plugin to solve it.

Suppose it can be done:
1. set information of plugins in this feature (plugins) and save it in .vscode folder
2. when I next load this project, VSCode read the saved file and load plugins which I set

**Comment by gjsjohnmurray** [comment] 2021-04-01 15:55
/duplicate of #40239 

But the following technique is already possible:

1. Begin with no folder or file open in VS Code.
2. For the File menu choose Save Workspace As... and use the dialog to set the name and path of the .code-workspace file this creates. Maybe use a naming convention to indicate this will be a template workspace for a particular language. For example `_Python.code-workspace`
3. From Command Palette run `Extensions: Disable All Installed Extensions for this Workspace`.
4. Run the `Developer: Reload Window` command.
5. In the Extensions view, find each extension that you want to be enabled in future workspaces created from this template. Use the gearwheel menu to choose `Enable (Workspace)`.
6. Close the workspace.
7. Optionally set the template .code-workspace file to be read-only In the filesystem. Doing this will make it harder for you to accidentally change your template workspace's settings or its set of root folders, but it won't stop you altering which extensions are enabled for the template.

To create a new workspace based on the template do this:
1. Open the template.
2. Immediately use `Save Workspace As...` from the `File` menu.
3. Enter the name and path of the new workspace.
4. Now start customizing your workspace, for example by adding the folder(s) you want to use in it.

**Closed** 2021-04-01 15:56 UTC
Labels: *duplicate
