### ISSUE TITLE
Hign CPU usage in vue.js project

### ISSUE THREAD

**Issue by chengxg** [microsoft/vscode#89398] opened 2020-01-28 03:06 UTC
Recently, when I opened my Vue project for less than 5 minutes, the CPU usage was too high, and the code prompt failed!

Then in vscode - > help - > open process manager, we find a process running abnormally - electron node tsserver.js

This problem is very strange. Sometimes it doesn't appear in a day. Sometimes it appears as soon as the project is opened

I'm in Qingdao, China. Is it related to the Internet?

**Comment by lamstutz** [comment] 2020-01-28 09:17
this issue is similar : https://github.com/microsoft/vscode/issues/89352

**Comment by mjbvz** [comment] 2020-01-29 17:59
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by chengxg** [comment] 2020-02-03 02:06
This problem is described as follows:
1. It has nothing to do with the extension. If an extension is not installed, this problem will still occur.
2. It is related to the folder node and modules, and may be related to a dependency of the project. Some projects have this problem, and some projects do not.
3. Trigger this problem when writing JavaScript code. Once this problem is triggered, the code prompt fails and the CPU share is high.
4. It is the problem of the vscode process "electronic node tsserver. JS".
5. There is no problem after reinstalling vscode.

My vscode is. Zip decompressed. When upgrading vscode, I will overwrite the new version of the file with the old version. There may be a problem. After I reinstall vscode, this problem will not appear for the time being.

**Comment by mjbvz** [comment] 2020-02-04 02:30
Thanks for checking. I am closing this issue since it is fixed in the current insiders build. That will be released as VS code 1.42 sometime this week

**Closed by mjbvz** 2020-02-04 02:30 UTC
Labels: needs more info
