### ISSUE TITLE
extension terminated host unexpectedly

### ISSUE THREAD

**Issue by pranavgupta701** [microsoft/vscode#94804] opened 2020-04-09 14:58 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by pranavgupta701** [comment] 2020-04-09 14:59
it occur when in both cases when extensions are disabled and when extensions are enabled.

**Comment by RMacfarlane** [comment] 2020-04-09 16:08
Actually, I'm going to collect these into one issue, there are a number of reports on this that likely have the same root cause. Since it happens when both extensions are disabled and not disabled, it sounds like it may be a problem with a built in extension

Duplicate of https://github.com/microsoft/vscode/issues/94807

**Closed** 2020-04-09 16:09 UTC
Labels: *duplicate, needs more info

**Comment by gjsjohnmurray** [comment] 2020-04-09 16:10
@pranavgupta701 I know you reported that the crash happens even with all extensions disabled. But I'd like to know if LiveServer is one of the extensions you have installed. Several other reports seem to have LiveServer as a common feature.
