### ISSUE TITLE
Source control error: No source control providers registered

### ISSUE THREAD

**Issue by DilipDalwadi** [microsoft/vscode#75487] opened 2019-06-14 08:14 UTC
Issue Type: <b>Bug</b>

I see "No source control providers registered" message in Source Control,
I tried suggested solution of "https://github.com/Microsoft/vscode/issues/61522" but this solution is not working.
I uninstall VS code insider and install again although facing same issues.

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:19:34.516Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6402P CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
githistory|don|0.4.6
material-icon-theme|PKi|3.8.0
vscode-scss-formatter|sib|1.4.1
sonarlint-vscode|Son|1.8.0

</details>

**Comment by DilipDalwadi** [comment] 2019-06-14 10:52
Sorry, these solution doesn't work.
![image](https://user-images.githubusercontent.com/17349864/59504442-9bc8bd80-8ec0-11e9-9c56-93e0f67d5d15.png)

**Comment by gjsjohnmurray** [comment] 2019-06-14 11:54
See #75411. Assuming it matches your situation, wait for the next Insiders to appear.

**Comment by joaomoreno** [comment] 2019-06-19 09:34
Dupe of https://github.com/microsoft/vscode/issues/75411

**Closed by joaomoreno** 2019-06-19 09:34 UTC

**Comment by DilipDalwadi** [comment] 2019-06-23 17:50
Above problem is solved. I shut down and restart the PC. I don't know what exactly the problem was. But it's solved now.
Thanks for your helps.
