### ISSUE TITLE
Optimize  the tasks experience of vscode

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#110998] opened 2020-11-20 05:58 UTC
Issue Type: <b>Feature Request</b>

vscode can customize the task to the tasks file，but it is very obscure and hard to use.
also, launch file need to refer tasks.json, but there is no intellisense.

please Optimize tasks experience with "intellisense","visualization","usability" and "Accessibility". eg: Tasks View for Mouse users or Newbies

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:37:52.577Z)
OS version: Windows_NT x64 10.0.14393

**Comment by alexr00** [comment] 2020-11-20 09:34
We already have intellisense in tasks.json. Providing a UI for tasks is a duplicate of https://github.com/microsoft/vscode/issues/28235

**Closed by alexr00** 2020-11-20 09:34 UTC
