### ISSUE TITLE
Markdown preview is empty

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#58219] opened 2018-09-07 20:31 UTC
Issue Type: <b>Bug</b>

Open a Markdown file, preview it and see nothing shown

BTW, the first three dependencies seem to not be packaged in the vscode distribution

![image](https://user-images.githubusercontent.com/7588612/45241660-2c94bc00-b2e5-11e8-8621-f9cf71a9779f.png)

![image](https://user-images.githubusercontent.com/7588612/45241505-a7a9a280-b2e4-11e8-903c-1a2e00c8039f.png)

---

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.18234

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.41GB free)|
|Process Argv|C:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.4.2

(1 theme extensions excluded)

</details>

**Comment by neilsustc** [comment] 2018-09-07 20:32
@mjbvz 😳

**Comment by mjbvz** [comment] 2018-09-07 20:38
Duplicate of #58203

**Closed by mjbvz** 2018-09-07 20:38 UTC
Labels: insiders
