### ISSUE TITLE
Debug: Show debug state in activity bar?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5841] opened 2016-04-26 13:54 UTC
We are not that aggressive anymore in opening the debug viewlet when you hit a breakpoint. Why not show the debug states as decoration on the debug viewlet itself? I could imagine a yellow pause icon when you are on a breakpoint and the green play icon when you are actually running or debugging a program.

@stevencl @chrisdias @bgashler1 thoughts?

**Comment by isidorn** [comment] 2016-05-06 08:26
ping @bgashler1 @stevencl 
silence I will take as approval and implement this on monday 😊

**Comment by stevencl** [comment] 2016-05-06 11:29
Sorry, take it as not keeping up :-)

In saying that, I am not opposed to the idea but I wonder why we changed the behaviour and don't switch to the debug viewlet when hitting a breakpoint now?

**Comment by bpasero** [comment] 2016-05-06 11:52
I am not sure if we should change the current behavior to always reveal the debug viewlet. I think we have a reason to not reveal it all the time because people got distracted. Thinking about viewlet indicators in general, I find it a good idea to show any viewlet state in the activity bar because these indicators are meant for exactly that purpose (the viewlet is not visible but has state that you might be interested in).

**Comment by isidorn** [comment] 2016-05-06 11:58
I like the arguments ben is making and that is the main reason why I would like to experiment with this to get feedback.

**Comment by bpasero** [comment] 2016-05-06 12:01
@stevencl or putting it the other way around, can you state concerns you have with showing the debug state in the viewlet? Would people maybe expect they could break/continue from the activity bar? Maybe we should start thinking of making the activity bar more powerful and allowing to invoke actions from it (e.g. the full debug toolbar).

**Comment by stevencl** [comment] 2016-05-06 16:11
I'm not opposed to the idea. If I had to think up a concern it would be the same one we have about icons in the explorer, that it becomes a bit of a Christmas tree effect. But that is just me trying to think of a concern. So definitely go ahead and experiment with it.

I see also that we switch to the debug viewlet until the user activates another viewlet during debug mode. That makes sense to me too.

**Comment by chrisdias** [comment] 2016-05-06 16:42
What are the badges that we would show in the activity bar? if we showed a play/pause badge it may feel like you can click on it to take an action. If it is multi color (e.g. orange when debugging) then i feel like it becomes a christmas tree very quickly.

**Comment by bpasero** [comment] 2016-05-06 17:25
Maybe @isidorn could attach screen shots if he has ideas how to present it. Also, I would maybe only show an indication when the execution is currently stopped in a breakpoint because otherwise we indicate debugging state in the status bar.

**Comment by bgashler1** [comment] 2016-05-06 17:48
![image](https://cloud.githubusercontent.com/assets/11839736/15081453/f6d98910-1377-11e6-891f-7aca018a687f.png)
Is this what you were thinking @isidorn ?

**Comment by chrisdias** [comment] 2016-05-06 18:08
@bgashler1 I want to click on that pause button!

**Comment by bgashler1** [comment] 2016-05-06 18:24
![image](https://cloud.githubusercontent.com/assets/11839736/15082509/ed4f00a0-137c-11e6-8095-ec3afca56be1.png)

Since we already have all the Debug buttons persist on top (no matter what viewlet we're in), are we certain this is a problem with users?

1. Are they often running their apps while working in the Explorer and wanting to be notified of hitting breakpoints?
2. If so, is the "Pause" button turning to a "Play" button not clear enough that they have stopped due to a breakpoint/terminating?

**Comment by bgashler1** [comment] 2016-05-06 18:49
@chrisdias: just an experiment.  Is this less clickable to you?
![image](https://cloud.githubusercontent.com/assets/11839736/15083154/8a31175c-1380-11e6-8596-4cf4a56877d2.png)

**Comment by chrisdias** [comment] 2016-05-06 19:01
No, its not :).  One thing to consider, we have a problem where the debug toolbar only shows up when the debug viewlet is visible/active.  i find this problematic if i switch to the explorer while at a break point, where did the toolbar go and why?  we've always discussed having the activity bar buttons be commands, perhaps now is the time to consider.

**Comment by bpasero** [comment] 2016-05-07 08:25
Yes I was thinking the same when we brought up the concern that the icon looks like you could click it.

**Comment by isidorn** [comment] 2016-05-09 10:19
@bgashler1 yes I had something in mind like the first picture you attached.
@chrisdias I understand the concern that you might want to click on that pause button, but once the user clicks once and figures it is only a state he will no longer try to click it imho. It looks like the other badges which are also not clickable.

I am fine with pushing this to the backlog and introducing it once we decide we want to move forward on making activity bar buttons be commands

**Comment by stevencl** [comment] 2016-05-09 13:56
Incidentally, @chrisdias, I don't see the debug toolbar disappear when switching to the explorer viewlet while in debug mode. As @bgashler1 mentions above, the debug toolbar might be enough feedback to communicate the state of the debugger as long as it doesn't disappear when switching to another viewlet when in debug mode?

**Comment by isidorn** [comment] 2016-05-09 13:59
The debug toolbar does not dissapear

**Comment by chrisdias** [comment] 2016-05-09 15:38
I'm sorry, I was wrong about the toolbar disappearing when you switch viewlets. The thing that I was thinking about was that you have to bring up the debug viewlet to be able to press the "Play" button. When I move away from the debug viewlet, there is no button to press, and I like to press the button rather than hit F5 for some reason. I apologize for the confusion.

Going back to the original question... the problem is that we don't bring up the debug viewlet when we hit a breakpoint as aggressively as before. As brad says we have the toolbar in view and we have the orange status bar.  Does the badge in the activity bar help us here?

**Comment by isidorn** [comment] 2016-09-05 21:29
Closing this as we have not reached a concenzus and I do not think adding this is solving any issue for the user.

**Closed by isidorn** 2016-09-05 21:29 UTC
Labels: debug, ux
