### ISSUE TITLE
Search inputs doesn't show text

### ISSUE THREAD

**Issue by DavAllFR** [microsoft/vscode#127009] opened 2021-06-23 16:49 UTC
Issue Type: <b>Bug</b>

Enter a text in the Search inputs fields, and the text won't appear.

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:15:24.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.51GB free)|
|Process Argv|--crash-reporter-id ab72b528-1c07-4203-8d27-de2758df0bc1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
lorem-barnak|HEC|1.2.1
discord-vscode|icr|5.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
notepadplusplus-keybindings|ms-|1.0.7
vscodeintellicode|Vis|1.2.14

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by IllusionMH** [comment] 2021-06-23 16:57
/duplicate of #126896

Fix already released in latest insiders build.

**Closed** 2021-06-23 16:58 UTC
Labels: *duplicate
