### ISSUE TITLE
Can't input chinese characters at terminal unless using Microsoft Pinyin

### ISSUE THREAD

**Issue by xiepeiyang** [microsoft/vscode#117337] opened 2021-02-23 09:18 UTC
- VS Code Version:1.53.2
- OS Version:Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open any project, press ctrl+~ to open terminal.
2. make sure your input method is Sogou Pinyin(or any other chinese input method, except Microsoft Pinyin).
3. try to type chinese, you would find that there is no chinese characters on the screen, but English letters would be OK.
4. change to use Microsoft Pinyin, all will be fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2021-02-23 09:29
Duplicate of #115814

**Closed** 2021-02-24 20:52 UTC
Labels: *duplicate
