### ISSUE TITLE
Support large image more than 1MB

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13325] opened 2016-10-07 04:50 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.1.0

I can't preview large image which more than 10M?    So I think it would be better to support preview  large image file.

**Comment by bpasero** [comment] 2016-10-07 05:30
Unlikely to happen. Opening images that are large causes a major hit on the memory consumption and closing an image does not free those resources in Chrome. That is why we set a limit of 1 MB per image.

**Comment by mjbvz** [comment] 2017-11-03 23:14
Duplicate of #25122

**Closed by mjbvz** 2017-11-03 23:14 UTC
Labels: duplicate, feature-request, upstream, workbench
