### ISSUE TITLE
Bringing up Terminal No Longer Changes Focus

### ISSUE THREAD

**Issue by bramankp** [microsoft/vscode#128265] opened 2021-07-09 00:51 UTC
Issue Type: <b>Bug</b>

Tried using the CTRL-` shortcut, bringing up the terminal no longer changes focus to the new terminal window that is now created. This is with the recent update:

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Happens on both Windows and WSL.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.50GB free)|
|Process Argv|--crash-reporter-id 26fa402c-7467-4284-b94f-2b7a8bf3c955|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2304)|
|Memory (System)|24.96GB (23.02GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
linkerscript|Zix|1.0.2
githistory|don|0.6.17
gitlens|eam|11.5.1
cpptools|ms-|1.5.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment] 2021-07-09 03:07
duplicate of #128255

**Closed by meganrogge** 2021-07-09 03:07 UTC
Labels: bug, new release, terminal
