### ISSUE TITLE
Call stack pane too small and does not retain adjusted size

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#39301] opened 2017-11-29 10:56 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.1.2
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|3.5.0
code-spell-checker|str|1.5.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Debug a Node process and pause.

![image](https://user-images.githubusercontent.com/1658949/33371736-ff756ec6-d4fb-11e7-8920-0a81c094747c.png)

The **Call Stack** pane is *always* way too small and collapsing *any* other pane does not increase the height of the call stack pane. The only way to get it larger is by manually resizing it. This is a cumbersome  operation that has to be repeated constantly.

This is especially frustrating since there is more than enough empty space there.

**Comment by isidorn** [comment] 2017-11-29 15:25
Duplicate of some issue assigned to @sandy081

**Comment by oliversalzburg** [comment] 2017-11-29 15:34
Please someone post a link to it so I can :+1: the hell out of it ;D

**Comment by isidorn** [comment] 2017-11-29 15:53
@oliversalzburg just look at issues assigned to @sandy081 and november, it is about split views and size

**Comment by oliversalzburg** [comment] 2017-11-29 17:00
No clue, but here's [the search](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+assignee%3Asandy081) if someone else wants to browse through it.

**Comment by sandy081** [comment] 2017-11-30 07:39
@oliversalzburg Will find it out and let you know.

**Comment by sandy081** [comment] 2017-11-30 15:46
@oliversalzburg Does this issue https://github.com/Microsoft/vscode/issues/35600 resembles your scenario?

**Comment by oliversalzburg** [comment] 2017-11-30 15:58
@sandy081 I think it does, at least partially. If the adjusted size was retained more reliably, I'm sure it would help a lot.

It would also help if you could resize them by dragging the pane header, instead of having to find the 4px high area of the actual splitter. :D

**Comment by sandy081** [comment] 2017-12-03 20:56
Will make sure your first request is fixed. But second request is kind of out of scope :)

I am reopening it, just to make sure this gets fixed.

**Comment by sandy081** [comment] 2017-12-12 15:53
This no longer happening in latest insiders. Please try out.

**Closed** 2017-12-12 15:54 UTC
Labels: bug, debug, workbench-layout
