### ISSUE TITLE
IntelliSense completion list is inaccurate

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/vscode#15146] opened 2016-11-08 07:25 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10 x64

Vscode fails to display IntelliSense of object`s property when the object's property name is more than one character. In the case when I use type define  as below.

Steps to Reproduce:

First, in index.d.ts, I define a function called test
``` typescript
// index.d.ts
export function test<Obj>(oldV: Obj, newV : Obj): string

```

Then, I use `test` function  in action.js. 
I pass a object with one-character and multi-character props to test , as follow
```typescript
// action.js
import { test } from './index'

let testObj = {
  a: 1,
  bb: 2
}

test(testObj, {
  //TODO
})

```
When I input `a`  at `//TODO`, IntelliSense runs well, as follow : 
![image](https://cloud.githubusercontent.com/assets/10753131/20089964/26427b5a-a5c5-11e6-82f0-a6a3905306fe.png)

But when I input `b`  at `//TODO`, IntelliSense fails to parse 'bb' as a property of testObj : 
![image](https://cloud.githubusercontent.com/assets/10753131/20090300/59c8d580-a5c7-11e6-8a5d-98e9253000fb.png)

Am I mistakenly writing index.d.ts, or are there some bugs with vscode ?

**Comment by waderyan** [comment] 2016-11-14 21:57
@dbaeumer do you have a thought on this issue? Is there anything special with writing to index.d.ts?

**Comment by dbaeumer** [comment] 2016-11-15 01:06
@waderyan I guess this is a TS issue. I would enable tsserver tracing and see what the response looks like. If it doesn't contain bb as a symbol then move to the TS team.

**Comment by waderyan** [comment] 2016-12-10 00:17
@mhegazy can you help me? I'm trying to figure out if this is a bug on VS Code's side or on TS's side. I'm having a hard time understanding what is coming through in the logs. 

@mjbvz you might have an insight as well. 

Here is the reproduction.

```typescript
// index.d.ts
export function test<Obj>(oldV: Obj, newV : Obj): string
```

```javascript
/// <reference path="index.d.ts" />

// action.js
import { test } from './index'

let testObj = {
  a: 1,
  bb: 2
}

test(testObj, {
    // TODO 
})
```

When triggering IntelliSense at `//TODO` I see this:

![image](https://cloud.githubusercontent.com/assets/2449568/21069026/ff048cd0-be2a-11e6-9da7-0b077b35e094.png)

And in the log:

```
[Trace - 4:13:55 PM] Sending request: completions (73). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:13:55 PM] Response received: completions (73). Request took 1 ms. Success: true 
Result: [
    {},
    {},
    {},
    {}
]
[Trace - 4:13:55 PM] Sending request: completionEntryDetails (74). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:13:55 PM] Response received: completionEntryDetails (74). Request took 1 ms. Success: true 
Result: []
```

This seems wrong to me. I don't see any property suggested in the IntelliSense window. 

If I type `a` in `//TODO`, I see this:

![image](https://cloud.githubusercontent.com/assets/2449568/21068970/99817e4a-be2a-11e6-95d8-17d007c38b4a.png)

And see this in the log:

```
[Trace - 4:14:57 PM] Sending request: change (82). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:14:57 PM] Sending request: completions (83). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:14:57 PM] Response received: completions (83). Request took 11 ms. Success: true 
Result: [
    {},
    {},
    {},
    {}
]
[Trace - 4:14:57 PM] Sending request: completionEntryDetails (84). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:14:57 PM] Response received: completionEntryDetails (84). Request took 1 ms. Success: true 
Result: [
    {}
]
[Trace - 4:14:58 PM] Sending request: geterr (85). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:14:58 PM] Event received: syntaxDiag (0).
Data: {}
[Trace - 4:14:58 PM] Event received: semanticDiag (0).
Data: {}
```

I would've expected to see `a` somewhere in the log. 

OP's issue is typing `bb` at `//TODO`. When I do that I see:

![image](https://cloud.githubusercontent.com/assets/2449568/21068986/bab46a6e-be2a-11e6-8608-a8661d617962.png)

And I see this in the log:

```
[Trace - 4:15:49 PM] Sending request: change (91). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:15:49 PM] Sending request: change (92). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:15:49 PM] Sending request: completions (93). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:15:49 PM] Response received: completions (93). Request took 13 ms. Success: true 
Result: [
    {},
    {},
    {},
    {}
]
[Trace - 4:15:49 PM] Sending request: completionEntryDetails (94). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 4:15:49 PM] Response received: completionEntryDetails (94). Request took 1 ms. Success: true 
Result: []
[Trace - 4:15:50 PM] Sending request: geterr (95). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 4:15:50 PM] Event received: syntaxDiag (0).
Data: {}
[Trace - 4:15:50 PM] Event received: semanticDiag (0).
Data: {}
```

**Comment by mhegazy** [comment] 2016-12-14 06:09
This behaving as expected. let me try to explain. the original generic function is defined as `function test<Obj>(oldV: Obj, newV: Obj): string ` with the generic type parameter `Obj` used in two parameter positions. when invoked with `test(testObj, { })` the type system tries to "infer" the generic type parameter from the actual arguments, so it comes up with two inferences, `type of testObj` and `{}`, and since `{}` is a super type of `typeof testObj`, the inference for `Obj` is `{}`. then completion kicks in, and tries to see if there are any known properties in the expected argument type to show, and it does not.

If the function use site was defined as `test<typeof testObj>(testObj, { })` you would be able to see `a` and `b` from the type of `testObj`. otherwise, i am afraid it is a chicken and egg problem.

**Comment by waderyan** [comment] 2016-12-16 19:06
I see. Thank you for explaining. We will close this as designed for now.

**Closed by waderyan** 2016-12-16 19:06 UTC
Labels: intellisense, needs more info, typescript
