### ISSUE TITLE
VSC polluting project root dir

### ISSUE THREAD

**Issue by rms95** [Microsoft/vscode#38835] opened 2017-11-21 04:06 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Visual Studio Code should not make the .vscode dir in directories added to the project, when working in a workspace. The projects I work on often have multiple toolchains (3 to 5+ is quite common). I usually use a "./project_name/Toolchains" folder, common in these scenarios. Which means VSC lives in "./project_name/Toolchains/Visual Studio Code" in my structure, which means I want temporary VSC data there as well. Currently the .vscode dir is polluting my project root directory, which is not favorable. Toolchains should live in their project directory, not in the project root in my opinion.

Steps to Reproduce:

1. I have a workspace in "./project_name/Toolchains/Visual Studio Code/my-project.Test My Environment.code-workspace"
2. I added my project root ("./project_name") as folder to my workspace
3. I save something related to a project (folder/workspace/etc)
4. .vscode dir appears in ./project_name

Reproduces without extensions: Yes

**Comment by sandy081** [comment] 2017-11-21 09:10
Duplicate of #29251

**Closed** 2017-11-21 09:10 UTC
Labels: *duplicate, config, new release
