### ISSUE TITLE
"DevTools failed to load source map" for VS Code extension

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode#145292] opened 2022-03-17 06:47 UTC
Issue Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version: 1.66.0-insider (user setup)

Steps to Reproduce:

1. Load an extension that has a webview, and where the webview's `.js` file has a corresponding `.js.map` source map
2. The browser shows the warning *DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-webview.net/c%3A/some/path/here/nameOfBundle.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED*
![image](https://user-images.githubusercontent.com/1588988/158750561-9bcebc28-b7d6-4230-aac4-14f2f9d55762.png)

---

Context:

While developing a VS Code extension, I would like to be able to debug any of the underlying code. This works well for the extension code itself, but I'm having issues having breakpoints in Webview code; breakpoints are not being bound. I'm trying to set breakpoints in the React TSX code of a webview of a VS Code extension. When I open webtools in the extension, I see the message mentioned above. This means that the sourcemap file is actually there, but DevTools seems to be trying to get it from the wrong context. I'm also wondering if there are any examples out there of extensions that have successfully set up for allowing setting breakpoints in Webpack-built webviews.

### Sidenote:
When I run
```
await (await fetch("https://file+.vscode-resource.vscode-webview.net/c%3A/some/path/here/nameOfBundle.bundle.js.map")).json()
```
from the devtools console from the `top` context, then I also see an `ERR_NAME_NOT_RESOLVED` error. However, if I set the console's scope to be one of the webviews, then this command does fetch the relevant source map file.

VS Code version: Code - Insiders 1.66.0-insider (6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f, 2022-03-16T05:17:27.938Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.55GB free)|
|Process Argv|--file-uri file:///c%3A/work/vscode-data-wrangler/vscode-data-wrangler.code-workspace --crash-reporter-id 30f4900b-5945-4b62-9bf1-4f80bdc87ba9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dotnet-runtime|ms-|1.5.0
jupyter|ms-|2022.3.1000771005

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vscscmwlcmt:30428973
vscgsvid1:30433757
dockersurvey3:30438168
pynewfile477:30451556

```

</details>

**Comment by jruales** [comment] 2022-03-18 23:09
For posterity: I managed to get breakpoints to work by using a devtool with  "inline-" prefix (I used "inline-cheap-module-source-map", but "inline-source-map" works too). This way, VS Code doesn't need to fetch the source map separately from the code.

Also, it's important to note that for Webviews, I'm only able to set breakpoints within DevTools itself (under Sources tab) and not within VS Code itself. Setting breakpoints in VS Code itself is only working for me for the core extension code itself and not for webviews. I hope that in the future it will be supported to set breakpoints in VS Code for Webviews, or if anyone knows how to set that up, please let me know.

**Comment by mjbvz** [comment] 2022-04-14 23:57
Duplicate of #145184 (which is about custom editors but both cases are using webview)

**Closed by mjbvz** 2022-04-14 23:57 UTC
