### ISSUE TITLE
Markdown preview often displays wrong file

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12335] opened 2016-09-20 19:10 UTC
- VSCode Version:1.5.2
- OS Version:Windows 10

I don't have a consistent repro for this but it happens at least once a day to me. I'm working on one Markdown file and then use the title bar preview button to display the Markdown preview. VS Code displays Markdown preview for a different file, not my active editor.

**Comment by gregvanl** [comment] 2016-09-26 20:57
The behavior seems to be to preview the first file in the editor group even when the file doesn't have focus. After closing the preview, the next preview correctly previews the active editor.

**Comment by mjbvz** [comment] 2016-09-27 01:13
This seems to happen pretty frequently when using the menu bar button. Repo steps for me:

1. Launch VSCode with a clean workspace with two markdown files.
2. Open one file and then the other.
3. Click the markdown preview button in the menu bar. This shows a preview of the first opened filed instead of the second.

From debugging, it seems that the `markdown.showPreview` event for the menu button click is sending us the wrong document, even if you change the focus to the second markdown document by clicking on it. I'll investigate this further.

**Comment by sdwheeler** [comment] 2016-10-06 23:19
I have this happen to me all the time in v1.5.3. The preview button creates a preview of a previously opened file. The file can be one of the open editors or it can be closed. I have had it happen when I only had one file open in the editor, then click the Preview button. It opens a previously edited file.

**Comment by bubifengyun** [comment] 2016-10-14 00:48
Solved? still in 1.6

**Comment by sdwheeler** [comment] 2016-10-14 22:05
Just upgraded VS Code and still have this problem.

Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T16:21:53.542Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

**Comment by mjbvz** [comment] 2016-12-01 00:30
Closing as duplicate of #12837, which seems to be the root cause of this problem and is not specific to markdown

**Closed by mjbvz** 2016-12-01 00:30 UTC
Labels: bug, markdown
