### ISSUE TITLE
statusBar colors do not match the value set by the current theme

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#178339] opened 2023-03-25 23:38 UTC
Type: <b>Bug</b>

When setting the status bar color vscode modifies it and does not respect the value set by the theme. It looks like it might be blending with another color, despite being opaque. This makes it impossible to set the status bar to an exact color.

This appears to apply to every `statusBar.*` color.

Steps to repro:
* Add these settings
    ```
    "workbench.colorCustomizations": {
        "statusBar.debuggingBackground": "#ff9800ff",
        "statusBar.background": "#ff9800ff",
        "statusBar.noFolderBackground": "#ff9800ff",
    }
    ```
* Notice the color of the status but is e49F2c, not ff9800

![image](https://user-images.githubusercontent.com/484784/227747214-854697e8-cd44-4ab3-a967-6411e1bacf5a.png)

VS Code version: Code - Insiders 1.77.0-insider (b9226e1ccc11625bcb42b55efb795e07ee533bb0, 2023-03-24T18:57:27.096Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.94GB free)|
|Process Argv|--crash-reporter-id 22cf4e37-a96e-4ad9-82f0-8715f8e2bf6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257
defaultazurewalk:30687958
pythonms35:30671666
j16hj152:30680472
ecj1e332:30687743

```

</details>

**Comment by nabeelkhan10** [comment] 2023-03-26 01:18
Hey @aeschli I would love to do this task but I am a newbie to coding currently learning OOP.
Can you help me get some basic tasks?

**Comment by bpasero** [comment] 2023-03-27 10:14
I cannot reproduce on macOS, so I suspect this is not an issue with VS Code:

![image](https://user-images.githubusercontent.com/900690/227913196-3b3f9229-13e1-4630-85d6-7dc461a25c1a.png)

**Comment by bpasero** [comment] 2023-03-27 10:16
Also fine on Windows for me:

![image](https://user-images.githubusercontent.com/900690/227913668-2b154889-5823-4a0d-bf67-5c086f904a91.png)

**Comment by bpasero** [comment] 2023-03-28 05:53
👍 , closing meanwhile

**Closed by bpasero** 2023-03-28 05:53 UTC
Labels: info-needed, themes, workbench-status, confirmation-pending

**Comment by akbyrd** [comment] 2023-03-28 05:55
Turns out Samsung was pulling some shenanigans and replacing the standard color profile on the machine. Sorry for the red herring.
