### ISSUE TITLE
Find in Terminal: Only scroll when necessary

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#59446] opened 2018-09-26 09:10 UTC
Issue Type: <b>Bug</b>

Testing #59267

Currently the current match is scrolled to the top. The scrolling behavior should align with the one in the editor.

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:28:12.336Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.77GB (0.68GB free)|
|Process Argv|--user-data-dir=tmp/usr --extensions-dir=tmp/ext|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by chrmarti** [comment] 2018-09-26 09:13
This also doesn't work well with how the find widget is positioned because that covers matches at the end of lines.

**Comment by alexr00** [comment] 2018-09-26 20:49
Duplicate of #50623

**Closed** 2018-09-26 20:49 UTC
Labels: *duplicate, insiders, integrated-terminal
