### ISSUE TITLE
Telemetry setting malware

### ISSUE THREAD

**Issue by 0xc0000007b** [microsoft/vscode#138004] opened 2021-11-28 11:39 UTC
This app is starting to remind me of that GPL page where they cover how [Microsoft's Software is Malware](https://www.gnu.org/proprietary/malware-microsoft.html). Today I started seeing problems in my `settings.json` and low and behold I see that `Rest-client: Enable Telemetry` is enabled and I can guarantee you it wasn't a user choice.

Please add an all or nothing telemetry setting and respect your user's privacy without them having to go out and discover VSCodium on their own.

related https://github.com/microsoft/vscode/issues/134660

**Comment by gjsjohnmurray** [comment] 2021-11-28 14:34
You haven't mentioned what version of VS Code you are using, perhaps because you don't want to share that. But assuming you are on the current Stable release (1.62.3) the information at https://code.visualstudio.com/docs/getstarted/telemetry should be applicable.

AFAIK (I'm not a member of the core team), as long as you set `"telemetry.telemetryLevel": "off"` *and* any of your 3rd-party extensions that send telemetry use the [`vscode-extension-telemetry`](https://www.npmjs.com/package/vscode-extension-telemetry) npm module to do this, then no telemetry should be being sent from your VS Code.

The `rest-client.enableTelemetry` setting is contributed by one of your extensions, [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client). To confirm that it uses the `vscode-extension-telemetry` module I suggest you either contact the author or examine the source code.

**Comment by yume-chan** [comment] 2021-11-29 08:33
![image](https://user-images.githubusercontent.com/1330321/143833688-d848f47a-6801-4d40-b472-95b1a84d2a42.png)

`rest-client.enableTelemetry` is from an extension you installed yourself. Please report to the extension author.

**Comment by lramos15** [comment] 2021-11-29 17:12
Hi. Sorry that your settings were changed without your knowledge. We aim for complete transparency here and to make it possible to configure the editor anyway you choose including what data we are allowed to collect. The core VS code team does not guarantee the integrity of any extensions which we do not own. The REST client is a third party extension with its own telemetry setting. If you want to turn telemetry off globally then set `"telemetry.telemetryLevel": "off"` in your settings.json. Any extension which implements our extension API and abides by `isTelemetryEnabled` will also respect this setting.

As for #134660 which you marked as related that was just a UI confusion and users were not actually opted into telemetry after previously opting out. You can use a packet sniffer to verify this if you do not trust us. We did push as a fix as soon as we realized the confusion to resolve this issue.

Let me know if you have any other telemetry questions as I would be happy to help. Happy coding! 🙂

**Closed by lramos15** 2021-11-29 17:12 UTC

**Comment by 0xc0000007b** [comment] 2021-11-30 02:49
I didn't realize the REST Client was responsible for the telemetry setting as it wasn't clear to me while updating to the latest version of VSCode (I'm running 1.6.2 for macOS built on 2021-11-17T07:59:13.865Z). Perhaps that's an area for improvement in the UX as the knee-jerk opinion is mistrust not just in Microsoft but Big Tech in general—especially considering the current geopolitical climate and state of surveillance capitalism.

@gjsjohnmurray @lramos15 I believe this this feature request is still valid so I'm not sure why this was closed because the core issue here is telemetry is slipping in and I don't want it to. It shouldn't matter if part of core or an extension as extensions are part of the product and are actively promoted by the product during development. Would you disagree?

**Comment by lramos15** [comment] 2021-11-30 15:07
Feature request is a duplicate of https://github.com/microsoft/vscode/issues/31891

**Comment by 0xc0000007b** [comment] 2021-11-30 19:51
@lramos15 thank you for the cross link and my apologies for not have having found that before opening this duplicate
