### ISSUE TITLE
Unrelated Code Actions shown if multiple diagnostics exist on same line

### ISSUE THREAD

**Issue by DudeNr33** [microsoft/vscode#177667] opened 2023-03-19 14:55 UTC
If multiple diagnostics exist for the same line, and at least one of the codes has a Code Action/Quick Fix available, this quick fix is shown for all codes on this line.

For example:
![image](https://user-images.githubusercontent.com/3929834/226184060-e8fbc342-071a-4052-81da-4e2edba52943.png)

`reimported`, `import-error` and `no-name-in-module` do not have a corresponding code action. However, for all of them the quick fix `Run organize imports` is shown, which is registered as quick fix for `ungrouped-imports` *only*.

![image](https://user-images.githubusercontent.com/3929834/226184161-52cb9506-efd2-4baf-8594-afcd8ae7a0ca.png)

I stumbled across this when trying to imlement a solution for https://github.com/microsoft/vscode-pylint/issues/205.

**Comment by mjbvz** [comment] 2023-03-20 20:17
Duplicate of #161331

**Closed by mjbvz** 2023-03-20 20:17 UTC
