### ISSUE TITLE
 internal links to other cells not working in latest version (1.64.2)

### ISSUE THREAD

**Issue by 4mkv** [microsoft/vscode#142915] opened 2022-02-12 09:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.2 
- OS Version: MacOS Monterey version: 12.2.1

Steps to Reproduce:

Support internal links to other cells #103519

```
Jupyter supports links to other cells in the same notebook using markdown syntax

[click to go to header](#header)
navigates to another cell

# header

```
But in the latest version clicking the link takes me to the end of notebook always.

**Comment by mjbvz** [comment] 2022-02-17 00:37
Duplicate of #142915

**Closed by mjbvz** 2022-02-17 00:37 UTC
