### ISSUE TITLE
1.86+ seems to have broken themes

### ISSUE THREAD

**Issue by sethvargo** [microsoft/vscode#204197] opened 2024-02-02 22:01 UTC
Does this issue occur when all extensions are disabled?: Yes, and it reproduces on vscode.dev too

```
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:11.933Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

Version 1.86+ seems to have changed the way themes are rendered. For example, this is the current screenshot from https://vscodethemes.com/e/akamud.vscode-theme-onedark/atom-one-dark?language=go:

![atom-one-dark](https://github.com/microsoft/vscode/assets/408570/5e418f91-ec36-4c48-aaf8-2d6339d03f9c)

However, here is the way it renders in a completely clean environment in vscode.dev:

![screenshot-20240202-ajlVCMoq@2x](https://github.com/microsoft/vscode/assets/408570/72fd9600-ec5e-40db-98c2-504a77e7577c)

---

I've noticed this issue happening across multiple themes, including GitHub-owned themes. This seems like a regression.

**Comment by PeepoFrog** [comment] 2024-02-03 18:34
same issue

**Comment by tomoyukikino** [comment] 2024-02-04 14:09
some issue

**Comment by starball5** [comment] 2024-02-05 11:12
Duplicate of #203998?

**Comment by a-hilaly** [comment] 2024-02-06 05:11
Unfortunately, i had to downgrade to vscode `1.85`. The new UX changes are too agressive 😞

**Comment by alexr00** [comment] 2024-02-06 10:46
Indeed a duplicate of https://github.com/microsoft/vscode/issues/203998

We updated to a new, better, and more maintained Go syntax highlighting grammar. As a general rule, a grammar should provide syntax highlighting scopes for all tokens. The old Go grammar did not, the new one does. You should almost never see uncolored tokens in Go now 🚀

If you happen to like uncolored tokens, you can get some of the old uncolored tokens back by doing something like the following: 


> *NOTE:* for users of other theme than the One Dark Pro theme, you may want to change `"foreground": "#ABB2BF"` to be `#fff` or whatever the default color is for your theme. I chose `#ABB2BF` specifically for One Dark Pro.

```jsonc
"editor.tokenColorCustomizations": {
		"[*Light*]": { // can change this to be the full name of your theme
			"textMateRules": [
				{
					"scope": [
						"variable.other.property.go",
						"variable.other.go", // add more scopes here if you care about light themes as you find them
					],
					"settings": {
						"foreground": "#000"
					}
				}
			]
		},
		"[*Dark*]": { // can change this to be the full name of your theme
			"textMateRules": [
				{
					"scope": [
						"variable.other.property.go",
						"variable.other.go", // add more scopes here if you care about dark themes as you find them
					],
					"settings": {
						"foreground": "#ABB2BF"
					}
				}
			]
		}
	},
```

**Closed by alexr00** 2024-02-06 10:46 UTC

**Comment by sethvargo** [comment] 2024-02-06 16:06
@alexr00 sorry, but introducing a breaking change that wasn't documented (without communicating anything to theme owners) is exceedingly hostile to end-users. Requiring end-users to add custom configuration (that's more than a boolean to restore the old behavior) degrades overall trust in the stability of VSCode.
