### ISSUE TITLE
"Run Task" does not load tsconfig from subfolder the first time

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#31880] opened 2017-08-02 00:42 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:10:12.703Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions: none
---

Testing #31232

Steps to Reproduce:

1. Open new window and add folder containing one subfolder
2. Run Task: only one tsconfig appears when there should be two
![image](https://user-images.githubusercontent.com/7109548/28851919-7e921324-76da-11e7-99bd-e7ac90a8d50d.png)
3. Run Task a second time: both tsconfigs appear
![image](https://user-images.githubusercontent.com/7109548/28852745-645c0aea-76e0-11e7-82b7-5d27906116b7.png)

This is also true for Run Build Task
![image](https://user-images.githubusercontent.com/7109548/28852784-a65ad160-76e0-11e7-88b5-7dc16b1d09bb.png)

**Comment by mjbvz** [comment] 2017-08-02 00:44
Thanks. I believe this is a duplicate of #31820

Should be fixed in master

**Closed by mjbvz** 2017-08-02 00:44 UTC
Labels: duplicate, insiders, tasks
