### ISSUE TITLE
VS Code freezes while opening Text file bigger than 5MB

### ISSUE THREAD

**Issue by d4libor** [microsoft/vscode#136834] opened 2021-11-10 07:42 UTC
Issue Type: <b>Bug</b>

VS Code freezes while opening Text file bigger than 5MB

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Does this issue occur when all extensions are disabled?: Yes/No
YES
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.31GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a81d7504-12e9-4252-a115-dd9abd3db3b6|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by snebjorn** [comment] 2021-11-10 20:51
Similar issue here when opening a 6MB json file

**Comment by jkellerer** [comment] 2021-11-10 21:23
Last working version is 1.61.2 in my case. 1.62.0 and 1.62.1 both have the issue (OSX 11.6)

**Comment by alexdima** [comment] 2021-11-11 07:30
@d4libor @snebjorn @jkellerer 

Do you have `editor.bracketPairColorization` or `editor.guides.bracketPairs` enabled ?

(This could be a duplicate of https://github.com/microsoft/vscode/issues/136470)

**Comment by d4libor** [comment] 2021-11-11 07:37
> @d4libor @snebjorn @jkellerer
> 
> Do you have `editor.bracketPairColorization` or `editor.guides.bracketPairs` enabled ?
> 
> (This could be a duplicate of #136470)

@alexdima  yep. after I disabled `editor.bracketPairColorization` everything works again. This issue is a duplicate

**Comment by hediet** [comment] 2021-11-11 07:50
This bug is already fixed in todays insider build and will be fixed in the next stable recovery release.

/duplicate #136470

**Closed** 2021-11-11 07:51 UTC
Labels: *duplicate
