### ISSUE TITLE
Deleting a file in the current editor while focus is in terminal will focus the editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9014] opened 2016-07-09 22:38 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (4c0676ab472a92f5269ac4995cdc81db8bc94896, 2016-07-08T15:13:23.068Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open and pin file `bar`
1. Open and pin file `foo`
2. Open integrated terminal
3. Run `rm foo`, notice focus is moved from the terminal to the `bar` editor

**Comment by bpasero** [comment] 2016-07-11 07:58
👍  a UI regression from having stacks because before when closing an editor we would not activate the next one in the stack, but now we do.

**Closed** 2016-07-11 07:57 UTC
Labels: bug
