### ISSUE TITLE
Quick open immediately dismisses when context menu is open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167758] opened 2022-11-30 18:54 UTC
1. Right click to open context menu in text editor
2. Ctrl+P to open quick open
3. :bug: both context menu and quick open are dismissed

![Recording 2022-11-30 at 10 45 18](https://user-images.githubusercontent.com/30305945/204882333-9fd8b06c-bce3-440c-b7a0-08a68259bfbe.gif)

**Comment by daviddossett** [comment] 2022-11-30 19:04
@sbatten re: context menu

**Comment by sbatten** [comment] 2022-11-30 19:12
This is not a regression so assigning to december

**Comment by TylerLeonhardt** [comment] 2022-12-13 19:40
@alexdima @hediet I'm going to pass to you for your take. Here's what I found out.

When we show the command palette that causes the editor context menu to trigger the hide:
https://github.com/microsoft/vscode/blob/174be21bbfd29d061dd8504147f5e445a24aa35f/src/vs/editor/contrib/contextmenu/browser/contextmenu.ts#L253

This hide, focuses the editor... but in doing so, that causes the Quick Pick's didBlur to hide:
https://github.com/microsoft/vscode/blob/174be21bbfd29d061dd8504147f5e445a24aa35f/src/vs/base/parts/quickinput/browser/quickInput.ts#L1365-L1368

which will hide the quick pick if `ignoreFocusOut` is set to `false` which is the default.

This behavior with context menus seems to repro:

* Always in context menus of the editor
* Only with custom menus (not native menus) in the rest of the product (tree views, Account/Gear menu, etc)

**Comment by TylerLeonhardt** [comment] 2022-12-13 19:45
Two actions here:

1. This `this._editor.focus();` needs to be removed or handled better (passing that to @alexdima or @hediet)
2. custom menus should follow the logic: if ESC/selection, focus what was previously focused. If dismissed due to focus lost, don't restore focus (this goes to @sbatten)

**Comment by sbatten** [comment] 2022-12-14 16:25
re-opening as we still have some work to do on the menu side

**Closed** 2022-12-14 18:30 UTC
Labels: bug, menus
