### ISSUE TITLE
Rendering issue with inline submenu on treeItem

### ISSUE THREAD

**Issue by sadlomaslox25** [microsoft/vscode#120242] opened 2021-03-31 13:44 UTC
- VS Code Version: 1.54.3
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a submenu with one command in the extension manifest package.json. Register this submenu as treeItem "inline" context menu. Example:
```
{
    "name": "mysoft-studio",
    "displayName": "mysoft Studio",
    "contributes": {
        "views": {
            "mysoft-environments-explorer": [
                {
                    "id": "mysoft.views.changes",
                    "name": "Changes"
                }
            ]
        },
        "commands": [
            {
                "command": "mysoft.changesView.pushChange",
                "title": "Publish",
                "icon": {
                    "light": "resources/light/boolean.svg",
                    "dark": "resources/dark/boolean.svg"
                }
            },
            {
                "category": "mysoft Studio",
                "command": "mysoft.changesView.publishAndLock",
                "title": "Publish And Lock",
                "icon": "$(cloud-upload)"
            }
        ],
        "menus": {
            "view/item/context": [
                {
                    "command": "mysoft.changesView.pushChange",
                    "when": "view == mysoft.views.changes && viewItem == mysoft:change",
                    "group": "inline"
                },
                {
                    "submenu": "changes.advancedContextMenu",
                    "group": "inline@2",
                    "when": "view == mysoft.views.changes && viewItem == mysoft:change"
                }
            ],
            "changes.advancedContextMenu": [
                {
                    "command": "mysoft.changesView.publishAndLock",
                    "when": "view == mysoft.views.changes && viewItem == mysoft:change",
                    "group": "1_concept-update"
                }
            ]
        },
        "submenus": [
            {
                "id": "changes.advancedContextMenu",
                "label": "Advanced options",
                "icon": "$(gear)"
            }
        ]
    }
}
```
2. Run your extension.
3. Try to open the submenu from treeView item.

**Actual result:**

Menu is rendered cropped (outside of treeView). When cursor is moved to menu item, the focus is lost (taken by another control) and the menu disappears.

Example: https://ibb.co/VYghgD1.

**Expected result:**

Menu is rendered correctly, submenu command title is readable and invokable.

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment] 2021-04-06 09:57
Duplicate of https://github.com/microsoft/vscode/issues/110083

**Closed** 2021-04-06 09:57 UTC
Labels: *duplicate
