### ISSUE TITLE
Source Control not scanning Github repos correctly. 

### ISSUE THREAD

**Issue by iwomack96** [microsoft/vscode#196031] opened 2023-10-19 18:46 UTC
Type: <b>Bug</b>

1. I am unable to find the root cause, but Source Control randomly stopped working. I am remote ssh connecting to server hosts and am signed in on github to our repos. 
2. I am unsure as to why this has happened, but I did update VS Code today and disable then reenebale all plugins. 
3. On a prior pull request that was still open in my workspace i now get this error: The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'pr:/home/models/Applications.php?%7B%22baseCommit%22%3A%22d8e49598dbbb09e357678f0cd0161cce144c4730%22%2C%22headCommit%22%3A%2218b6cd38663ba3d23cd70239a69b9fed9110c58c%22%2C%22isBase%22%3Atrue%2C%22fileName%22%3A%22app%2Finclime%2Fmodels%2FApplications.php%22%2C%22prNumber%22%3A17%2C%22status%22%3A3%2C%22remoteName%22%3A%22origin%22%7D'

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-1160.95.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.45GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bi_energizedelaware/home/energizedelaware/public_html/devgit/iw/energizedelaware/app/inclime --crash-reporter-id f8797925-4040-4717-9eaa-87f28381c6b9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: i_greengrb|
|OS|Linux x64 3.10.0-1160.95.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2099)|
|Memory (System)|59.38GB (46.00GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.16.0
remotehub|Git|0.62.0
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
pdf|tom|1.2.2
vscode-intelephense-client|bme|1.9.5
Function-List|che|1.0.5
vscode-eslint|dba|2.4.2
vscode-pull-request-github|Git|0.74.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by iwomack96** [comment] 2023-10-20 14:04
Source control also continuously runs and never finds my prior changes. 
<img width="157" alt="git" src="https://github.com/microsoft/vscode/assets/119884332/cccc297f-54bb-4040-ac5c-163d2d97e232">

**Comment by lszomoru** [comment] 2023-10-26 17:24
Closing as duplicate of #196632.

**Closed by lszomoru** 2023-10-26 17:24 UTC
