### ISSUE TITLE
Source Control Tab: show repos which are modified

### ISSUE THREAD

**Issue by atul-bajpai** [microsoft/vscode#123439] opened 2021-05-10 06:31 UTC
I wish to have a feature (config setting) in Source Control tab, so that if i have multiple repositories in my project then instead of showing all the repositories, show only those repositories which have any file modified or added..

**Comment by W3Dojo** [comment] 2021-07-14 10:51
Duplicate of #128618 

This issue is older by 2 months time, but Issue #128618 is better documented IMO.

**Closed** 2021-12-25 02:31 UTC
Labels: feature-request, scm
