### ISSUE TITLE
DeprecationWarning: `node --inspect --debug-brk` is deprecated

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#32529] opened 2017-08-15 08:41 UTC
Since VSCode version 1.15.0 F5 (starting debug) prints out the following message:
```
(node:31245) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
```
Any ideas how to prevent this warning?

---------------------------------------------------
Project/System details:

- VSCode Version: 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2)
- OS Version: Ubuntu 16.04.3 LTS
- node Version: v8.3.0

Steps to Reproduce:

1. see [https://github.com/ManfredSteiner/typescript/tree/master/console](https://github.com/ManfredSteiner/typescript/tree/master/console)
2. start in debugging mode (F5)

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-08-15 09:07
duplicate of https://github.com/Microsoft/vscode/issues/28223

**Closed by weinand** 2017-08-15 09:07 UTC
Labels: debug, new release

**Comment by ManfredSteiner** [comment] 2017-08-15 09:54
Nice to see that it's closed...
But what's the solution to prevent printing this warning?
Maybe I am blind, but I cannot see any hint in the referenced issue.

**Comment by weinand** [comment] 2017-08-15 10:00
Let me try to summarise this for you:

Currently there is no way to prevent this. 

The reason why we use the combination of "--inspect --debug-brk" is clearly explained in the (indirectly) linked issue https://github.com/Microsoft/vscode/issues/27731:

> This combination of args is the only way to enter debug mode across all node versions. At some point I'll switch to inspect-brk if we don't want to support node 6.x anymore, or will do version detection for it and do something for runtimeExecutable scenarios.

**Comment by ManfredSteiner** [comment] 2017-08-17 05:25
@weinand, thank you for summarizing. Maybe it is possible to check node version and to use the right combination, or to add an additional config option in launch.json.

**Comment by nocke** [comment] 2017-10-27 14:23
As advice to googlers coming here through google on this deprecation warning (this page ranks 1st or 2nd...). This feature now exists!

1. ensure your Node Version is ≥ 8.0

`node --version`

2. change in your `launch.json` from
```
< "protocol": "legacy",
> "protocol": "auto",
```
Problem solved (=feature activated). On your next run...
`Debugging with inspector protocol because Node.js v8.4.0 was detected...`

**Comment by weinand** [comment] 2017-10-27 14:27
Since `"protocol": "auto"` is the default anyway, there is no need to use an explicit `protocol` attribute.
