### ISSUE TITLE
Buttons on touchBar of Macbook pro have not accessibility label

### ISSUE THREAD

**Issue by TyflosAccessibleSoftware** [microsoft/vscode#120166] opened 2021-03-30 10:35 UTC
Issue Type: <b>Bug</b>

1. Run VoiceOver on MacOS 11 (You can run it as an assistive tool of the accessibility pannel)
2. Open VSCode
3. Try to use VoiceOver's focus on one of the buttons in the touch bar. The buttons are focused without any accessible text.

P.S: VoiceOver is the screenReader tool what blind developers use to read the screen in Mac and iPhone

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.91GB free)|
|Process Argv|--crash-reporter-id 912e1260-38a6-4c9b-83d6-286978f5077c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
debugger-for-chrome|msj|4.12.12
vscode-paste-and-indent|Rub|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythonvspyt943cf:30280190
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by isidorn** [comment] 2021-04-06 13:09
@TyflosAccessibleSoftware thanks for letting us know.
I have pushed a potential fix for this, however since I am not 100% sure how to focus the touch bar buttons with VoiceOver it would be great if you could verify with VS Code insiders from tomorrow if the issue is indeed fixed https://code.visualstudio.com/insiders/

fyi @bpasero for my fix

**Closed** 2021-04-06 13:09 UTC

**Comment by bpasero** [comment] 2021-04-06 13:22
@isidorn isn't this https://github.com/microsoft/vscode/issues/82154 ?

**Comment by isidorn** [comment] 2021-04-06 13:25
@bpasero you are correct, I was not aware of that issue.
So it seems like this will just not work. I will revert my commit. Though let's close this issue as duplicate

**Comment by TyflosAccessibleSoftware** [comment] 2021-04-06 15:23
Hi Isidor

To focus an element in the touchbar using VoiceOver you only have to tap one time on the element when VoiceOver is running.

VoiceOver will speak the title of the focused button if the button has a title.


Thanks for your effor 

Regards
