### ISSUE TITLE
Maximizing editor and reorganizing tabs doesn't respect original layout

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#196502] opened 2023-10-24 20:46 UTC
Testing #196289

First of all, nice feature!
Really enjoyed how easy and intuitive it was to double click through editors for maximizing, un-maximizing.

There was one little thing that bothered me, which was when I had multiple files opened, and maximized one, then tried to split the screen (which toggled the original layout with the newly requested split), it seems to break the proportion of original layout. 
Not sure if this was expected.. Here is how you get it: 

https://github.com/microsoft/vscode/assets/62267334/26e51549-9b6b-42d6-a362-85c195f14865

**Comment by benibenj** [comment] 2023-10-25 07:18
The reason this happens in your case is because the settings editor has a limit on how small it can become. When it restores the sizes it keeps the original layout but when it then adds the new view, the settings editor does not shrink much because of it's min-width. This causes the other editors to become smaller then you expected. If you try this with only code editors you will see it keep the layout. Closing as this is the expected behaviour.

**Closed by benibenj** 2023-10-25 07:18 UTC
