### ISSUE TITLE
vim unexpected restart

### ISSUE THREAD

**Issue by tonypingco** [microsoft/vscode#177146] opened 2023-03-15 00:10 UTC
Type: <b>Bug</b>

I have many extensions for my Mac OS VS Code, especially Vim, but everytime I try to type fast on my VS Code, I just receive a warning that extensions unexpectedly restart.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (2.08GB free)|
|Process Argv|. --crash-reporter-id 8e74bfcb-d78f-490f-b1c6-08504175cb51|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.9.8
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
parameter-hints|Dom|0.2.7
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
macros|ged|1.2.1
copilot|Git|1.77.9225
remotehub|Git|0.52.0
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.28.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
remote-repositories|ms-|0.30.0
color-highlight|nau|2.5.0
vscode-twoslash-queries|Ort|1.1.0
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.5.0
prisma|Pri|4.11.0
vscode-rapidapi-client|Rap|1.9.3
java|red|1.15.0
vscode-styled-components|sty|1.7.5
cmake|twx|0.0.17
errorlens|use|3.8.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vim|vsc|1.25.2
vscode-wakatime|Wak|24.0.7
vscode-todo-highlight|way|1.0.5
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
pythonb192cf:30669361
funwalk2:30682974
pythonms35cf:30686773

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-15 07:43
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

Based on other recent issues my guess is Copilot. See #176562

**Comment by isidorn** [comment] 2023-03-15 11:07
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:07 UTC
Labels: freeze-slow-crash-leak, extension-host
