### ISSUE TITLE
Open Editors Panel appears after re-launch

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#43651] opened 2018-02-14 11:41 UTC
### Issue Type
Bug

### Description

I had hidden the Open Editors panel, by right-clicking and choosing "Hide". All was good until the latest Insiders update ran. When the app reloaded, the Open Editors panel was showing again. I had to re-hide it.

If I hide that panel, I do not want to see it re-appear!

### VS Code Info

VS Code version: Code - Insiders 1.21.0-insider (135d4a5d5cecd82e9e4da7ede655fb09af0dac35, 2018-02-14T06:09:28.551Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.17GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
json-to-ts|Mar|1.5.4
material-icon-theme|PKi|3.2.2
vscode-database|baj|1.5.0
path-intellisense|chr|1.4.2
githistory|don|0.4.0
tslint|eg2|1.0.26
auto-rename-tag|for|0.0.15
csharpextensions|jch|1.3.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.1.0

(4 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by isidorn** [comment] 2018-02-15 08:52
Agree. Duplicate of https://github.com/Microsoft/vscode/issues/43594

**Closed by isidorn** 2018-02-15 08:52 UTC

**Comment by jtsom** [comment] 2018-02-15 11:17
How is it a duplicate of #43594 ? That one is about split views. This is about the Open Editors panel?

**Comment by isidorn** [comment] 2018-02-15 13:36
Open editors panel is a split view
