### ISSUE TITLE
[themes] Uninstall/Exclude from list the built-in color themes

### ISSUE THREAD

**Issue by freMea** [Microsoft/vscode#22934] opened 2017-03-21 03:48 UTC
Hi,

Currently _Code_ comes with some built-in color themes. It would be nice if users could just disable/exclude some of them or all of them from the list. So this list could only contain the themes the users really use.

**Comment by usernamehw** [comment] 2018-02-22 20:45
@aeschli, isn't this possible with #17068 ?

**Comment by aeschli** [comment] 2018-02-23 16:23
Yes, correct. Marking as duplicate of #17068

**Closed by aeschli** 2018-02-23 16:23 UTC
Labels: feature-request, themes
