### ISSUE TITLE
High CPU in terminalProcess.ts

### ISSUE THREAD

**Issue by tony19** [Microsoft/vscode#71417] opened 2019-03-28 21:12 UTC
Issue Type: <b>Bug</b>

### Description

Possibly related to #63723.

Somewhat randomly, I noticed high CPU usage from VS Code (100% from one core on my MacBook Pro). Code's UI was noticeably lagging but still responsive. I toggled Code's Developer Tools, jumped into *JavaScript Profiler*, and caught a sample (see attached below). The profiling showed a timer firing every 200ms in `_setupTitlePolling()` (in `terminalProcess.ts`). The terminal was indeed open, but I wasn't running any commands at the time. Closing the terminal panel resolved the issue, and I couldn't reproduce the problem even after re-opening the terminal.

### Steps to reproduce

*Unfortunately, I don't have **reliable** reproduction steps, but here's what I was doing (sometimes with multiple Code instances on different virtual desktops):*

1. Open Vue CLI generated project from command line (`cd project dir && code .`)
2. Open terminal in VS Code with <kbd>CTRL</kbd>+<kbd>`</kbd>
3. In terminal, run `yarn serve`
4. Click URL in terminal to open page in browser (Chrome)
5. Update `*.vue` source files

*Expected Results:*
Minimal CPU usage

*Actual Results:*
High CPU usage (macOS profiler showed 100% for one core, used by VS Code)

### System Info

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0 (macOS Mojave 10.14.2)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.43GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.0
vscode-toggle-quotes|Bri|0.3.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
auto-run-command|gab|1.5.0
todo-tree|Gru|0.0.125
python|ms-|2019.3.6139
debugger-for-chrome|msj|4.11.3
vetur|oct|0.17.1
tslint-vue|pro|1.5.6
vscode-paste-and-indent|Rub|0.0.8
wallaby-vscode|Wal|1.0.121

</details>

### Debug details

[CPU-20190326T210952.cpuprofile.zip](https://github.com/Microsoft/vscode/files/3020089/CPU-20190326T210952.cpuprofile.zip)

<details>
<summary><code>$ code --status</code></summary>
<pre>Version:          Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)
Memory (System):  16.00GB (1.22GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    1	   164	 81173	code main
    0	    66	 81183	   gpu-process
    0	    82	 81216	   shared-process
    0	   311	 81314	   window (Untitled-1 — vue-ts2)
    0	     0	 81318	     /bin/zsh -l
   99	    33	 81321	     extensionHost
    0	    33	 81386	       electron_node server.js 
    0	    33	 81387	       electron_node vueServerMain.js 
    0	    33	 81336	     watcherService
    0	   246	 81851	   window (modal-table.vue)
    0	   115	 81853	     extensionHost
    0	   115	 82069	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=81853
    0	    49	 82869	       electron_node server.js 
    0	    49	 82870	       electron_node vueServerMain.js 
    0	    33	 82887	       electron_node eslintServer.js 
    0	    98	 82888	       electron_node tsserver.js 
    0	    66	 82894	         electron_node typingsInstaller.js typesMap.js 
    0	     0	 82075	     /bin/zsh -l
Workspace Stats:
|  Window (Untitled-1 — vue-ts2)
|    Folder (vue-ts2): 35 files
|      File types: ts(8) js(6) json(3) vue(3) ico(2) map(2) png(2) md(2)
|                  html(2) browserslistrc(1)
|      Conf files: package.json(1) tsconfig.json(1)</pre>
</details>

**Comment by Tyriar** [comment] 2019-03-28 22:40
Yeah I think it's a duplicate of that, I made a note on that issue and assigned for May (can do then if there's time).

**Closed by Tyriar** 2019-03-28 22:40 UTC
Labels: integrated-terminal

**Comment by Tyriar** [comment] 2019-03-28 22:42
Well for the interval anyway, that shouldn't cause 100% CPU. Your code --status output actually calls our the extension host as the culprit which means one of your extensions is being the CPU hog, I don't think there's a way to know which one yet so you have to manually disable/enable until it no longer happens.

**Comment by tony19** [comment] 2019-03-29 23:22
I just encountered this bug again, and it's still in this state, so I could poke around in the DevTools. How do I determine which extension it is. Why does the extension host not show up in the JavaScript profiler?
