### ISSUE TITLE
Proposal: Extension auto update

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#390] opened 2015-11-21 04:13 UTC
VSCode support extension, that's good. but i found extension will not auto update. nor auto check update , nor notify us to update.

So i suggest can you please improve extension update?

1. Auto check update
2. Notify user to update or not 
3. User can setting check up frequency(every start? one day? one week?)
4. The check update can be put in background, not slow down the main VSCode window
5. Check update can be single/mutiple request. (If installed multiple extensions. check update may slow )
6. If user choose update, then download new extensions one by one and installed or down them simultaneouslyl and installed

**Comment by egamma** [comment] 2015-11-21 11:01
This is on our backlog.

**Comment by joaomoreno** [comment] 2015-11-21 13:53
Duplicate of #268

**Closed by joaomoreno** 2015-11-21 13:53 UTC
Labels: Feature Request
