### ISSUE TITLE
Marketplace: searching by an extension's name is practically broken

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#42890] opened 2018-02-03 16:12 UTC
There are a few major problems when searching by an extension's name. First of all, if I remember correctly, the marketplace had this thing on every extension's page:

![](https://cloud.githubusercontent.com/assets/2685357/25901135/734e34fc-359e-11e7-8a0b-a4ee9171ef4c.png)

So I've added an analogous message to all of my extensions' readme files, and I think other extension authors have done this too.

I have an extension called [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) (full id: `fabiospampinato.vscode-todo-plus`). This is what happens when the command `ext install vscode-todo-plus` is executed:

![](https://user-images.githubusercontent.com/17926167/35692049-868ae976-077a-11e8-8ecc-debf7c71c558.gif)

- `vscode-todo-plus` in an exact match of the id minus my username, and the extension is not even in the top 10 results.
- Searching for `fabiospampinato.vscode-todo-plus`, which is an exact match of the full id, leads to the same results.
- Searching for `@id:fabiospampinato.vscode-todo-plus` works, **but only inside VSC**, it doesn't work on [marketplace.visualstudio.com](https://marketplace.visualstudio.com)
- Where are these `ext install` and `@id:` commands documented anyway?

Let's try to search for another extension of mine, [Open in Browsers](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-browsers) (full id: `fabiospampinato.vscode-open-in-browsers`):

<img width="1102" alt="screen shot 2018-02-03 at 16 51 16" src="https://user-images.githubusercontent.com/1812093/35768894-f918c7e0-0902-11e8-8876-8386a2c52078.png">

- Not only `vscode-open-in-browsers` is an exact match of the extention id minus my username, but "Open in Browsers" is the extension's title, and "vscode" is practically a meaningless keyword, as is "in". What's the first result for this search? [vscode-ins-support](https://marketplace.visualstudio.com/items?itemName=wk-j.vscode-ins-support) 😕

I hope we do agree there's a problem here.

If I may suggest a few improvements: 

1. Always check if an extension's id (minus the username) is an exact match of the current query.
2. Implement [stop words](https://en.wikipedia.org/wiki/Stop_words).

_Please don't close this issue as "non actionable"._

**Comment by eamodio** [comment] 2018-02-03 22:36
This has been a long standing issue -- it is the reason I had to rename my extension to *Git Lens* rather than its actual name *GitLens* (no space), because when searching for git it would never show up. And even with that rename -- I had to pack in other words into the title (SEO hacking style) to even get it to show up on some other keywords -- even if those keywords were in the package.json keywords list.

**Comment by fabiospampinato** [comment] 2018-02-04 00:15
So those keywords I've been adding are actually useless you say? Nice...

I'm not sure if it's worse that the search engine works as badly as it does or that it hasn't been fixed already.

**Comment by eamodio** [comment] 2018-02-05 08:07
Not useless, but just ranked quite a lot below what is in the name -- at least that used to be the case

**Comment by joaomoreno** [comment] 2018-02-05 09:08
cc @viradhamMS @pkuma-msft

**Comment by joaomoreno** [comment] 2018-02-06 08:58
@fabiospampinato Disregarding the fact that the Marketplace doesn't return any results when searching for an extension's id, we have fixed the Marketplace instructions since a while. `ext install` was our way of guiding users to install extensions inside VS Code. Since we now have URL handlers for Mac and Windows, those instructions became irrelevant. We now only show them for Linux users:

![image](https://user-images.githubusercontent.com/22350/35850126-1510cbaa-0b24-11e8-88da-f21d798b53b3.png)

 and it should never have worked with the `name` format. The`id.name` is the unequivocal format that works.

**Comment by fabiospampinato** [comment] 2018-02-06 15:58
> we have fixed the Marketplace instructions since a while

I've only recently noticed the change (from `ext-name` to `owner.ext-name`) because somebody opened an issue about that in one of my repositories, has this change been mentioned in any changelog in the past?

> Since we now have URL handlers for Mac and Windows, those instructions became almost irrelevant

I would have replaced those `ext install (...)` instructions with URL handlers, but I've tried them once and after that, for a few days/weeks, a "Do you want to install (...)" message kept popping up every time I opened a new window. By the time that was fixed I guess I had forgotten about them.

> what if we showed in quick open a list of extensions which match that name? 

Why providing 2 different interfaces for discovering extensions?

Shouldn't searching "just work"?

**Comment by joaomoreno** [comment] 2018-02-07 16:39
> I've only recently noticed the change (from ext-name to owner.ext-name) because somebody opened an issue about that in one of my repositories, has this change been mentioned in any changelog in the past?

I guess it wasn't, since it was a Markeplace change... Sorry about that.

> Shouldn't searching "just work"?

It should. We've notified the Marketplace of the search issues.

**Comment by fabiospampinato** [comment] 2018-05-27 15:41
Just to reiterate on how bad the search engine works:

- I've just published an extension named `Open in node_modules`
- Searching for `open in node modules` (without the underscore) won't even show said extension within the first 60 results 🤷‍♂️

**Comment by gaurav42** [comment] 2018-05-28 15:02
@fabiospampinato, regarding the issue of searching your new extension:

While searching an extension, we also take into account the community inputs like number of downloads, number of ratings and average rating along with the string matching. Among the string matching, exact string matches carry a higher weight than prefix match. 

Since `node_modules` is one word in your extension name, word `node` in search text gets prefix match here. However, there are lot of extensions on Marketplace which have exact word 'node' in their extension name. So they carry a higher weight for matching the word 'node'. Additionally, since your extension is new, download count and ratings of other extensions are way higher, pushing their total score to the top.

One way to improve your extension rank is to break word `node_modules` into separate words `node modules`. This will increase the string matching score and push your extension up in the result.

**Comment by fabiospampinato** [comment] 2018-05-28 15:38
@gaurav42 Well, I would still consider whatever algorithm you guys are using broken because if I search for "open in node modules" I get these search results (some samples ~~randomly picked):

| Rank    | Ext. Name    | Ext. Description | My comments  |
|--------|-------------|-----------------|----------------|
| `#6`  | [Node Exec](https://marketplace.visualstudio.com/items?itemName=miramac.vscode-exec-node) | Execute the current file or your selected code with node.js. | 80k downloads, but no mention of "open" or "module(s)" anywhere.
| `#10` | [CSS Modules](https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules) | Visual Studio Code extension for CSS Modules | 22k downloads, but no mention of "open" or "node" anywhere.
| `#17` | [Node TDD](https://marketplace.visualstudio.com/items?itemName=prashaantt.node-tdd) | Ease test-driven development in Node and JavaScript | 9k downloads, no mention of "module(s)", but at least it has a few "opened" in its readme.
| `#64` | [Open in Vim](https://marketplace.visualstudio.com/items?itemName=jonsmithers.open-in-vim) | Opens current file in vim | 2k downloads, this is not even mentioning "node" anywhere, let alone "module(s)". But at least it has "open" and "in" in it's title.
| `#65` | [Open in node_modules](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-node-modules) | Open the current selection or arbitrary string in node_modules. | 2 downloads, it matches all the provided keywords, **in its title**.

If I had to guess what's wrong with your approach I'd say:

- Lack of stopwords, kind of meaningless keywords like "vscode" or "in" are given too much weight.
- Poor query parsing, if keywords are joined in some sort of another the whole thing falls apart (vscode-foo-bar, foo_bar, GitLens etc.)
- Maybe you're giving too much weight to downloads and ratings, the first thing to sort for is relevancy.

> One way to improve your extension rank is to break word node_modules into separate words node modules. This will increase the string matching score and push your extension up in the result.

I'm not going to rename the extension to something wrong (`node_modules` is a folder, I'm not talking about `node modules`, as in "NPM packages", here) just to work around this.

**Comment by Almenon** [comment] 2018-06-11 14:02
I agree, the search ranking seems wierd.

Some examples (when searching for "python"):

Py Files generator is above autoDocString, despite having about 50k less installs and 0 reviews
Same thing with ladieratheme - it is above autoDocString despite having about 49k less installs and 3 less reviews

Trustcode odo snippets and kvlang is above docker linter, despite having 47k less installs

Python paste and indent has 3 stars but apparently it's 2k extra downloads trumps Python (pydev)'s 5 star rating.  Seems like download count is weighted more heavily than rating in the ranking (or maybe python paste and indent has better keywords)

Python Coding Conventions has 773 downloads and is unrated, yet somehow is above magicpython (with 742 _thousand_ downloads and 3.5 stars) and several other extensions with far more downloads / good ratings.  So you could have a very popular or well-rated extension but if you don't have the right keywords you will still be ranked down.

Wait..,. but looking at the Python Coding Conventions package.json, it doesn't even have any keywords!

https://github.com/harip/python-coding-conventions/blob/master/package.json  🤔🤔🤔

> While searching an extension, we also take into account the community inputs like number of downloads, 

You mean the download count that is _also_ the update count?  This has been a outstanding issue ever since 2016 - when you release an update the marketplace shows your downloads as having increased.
The update count should not effect the search ranking.

> number of ratings and average rating 

That's good, but what algorithim are you using to calculate the weighted rating?  Not sure if that is open source but hopefully it isn't something like RatingA - RatingB or RatingA/RatingB

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

**Comment by fabiospampinato** [comment] 2018-06-11 14:22
> Python Coding Conventions has 773 downloads and is unrated, yet somehow is above magicpython 

This probably happens because of this:

> Poor query parsing, if keywords are joined in some sort of another the whole thing falls apart (vscode-foo-bar, foo_bar, GitLens etc.)

> You mean the download count that is also the update count? This has been a outstanding issue ever since 2016 - when you release an update the marketplace shows your downloads as having increased.
The update count should not effect the search ranking.

Yeah that's another major problem, one could automatically push a new update every day and downloads will go through the roof even though the same number of people are using it.

I guess technically those users are _downloading_ the update, but once this things are counted the downloads counter becomes less meaningful. 

The download counter for extensions on Chrome's store decreases when somebody uninstalls your extension and I think it doesn't increase just because the extension gets updated.

**Comment by pkuma-msft** [comment] 2018-06-14 05:02
Hey guys, I want to thank you for all the feedback. Please keep them coming. We are discussing this issue internally and I'll update this thread as soon as we have something to share.

**Comment by fabiospampinato** [comment] 2018-07-18 11:22
Here there's another weird one, searching for "monokai" and ordering by downloads returns those language packs at the top. The only place where those language packs mention "monokai" is inside their `package.json` as the value of some `contributes.localizations[0].translations[x].id` keys, why are you guys even indexing those fields?

<img width="1193" alt="screen shot 2018-07-18 at 13 09 36" src="https://user-images.githubusercontent.com/1812093/42878075-112f643c-8a8c-11e8-93a2-1c5f54f57589.png">

**Comment by fabiospampinato** [comment] 2018-09-20 16:34
I've just realized that the readmes aren't indexed at all. 

I searched for "cyclomatic" in the marketplace, and I've got this result:

<img width="674" alt="screen shot 2018-09-20 at 18 27 56" src="https://user-images.githubusercontent.com/1812093/45832685-ebe46c00-bd02-11e8-85ec-3cf9dc21ad82.png">

Then I tried searching for "marketplace cyclomatic" on Google, and this is the result:

<img width="846" alt="screen shot 2018-09-20 at 18 25 18" src="https://user-images.githubusercontent.com/1812093/45832583-95772d80-bd02-11e8-875b-473a56d814a1.png">

This is a bit ridiculous. 

I'm not saying that the search functionalities in the marketplace should be as good as Google's under **all** circumstances, but that's a full-word match in the readme, this query just can't return 0 results.

@pkuma-msft do you have any updates for us?

**Comment by pkuma-msft** [comment] 2018-09-21 21:11
@fabiospampinato Yes, unfortunately we do not index readme.md.. sorry about that. We use SQL FTS in our backend today are that's kind of the limiting factor. There' only so much custom logic we can run over the results returned by FTS to make it 'more' relevant. 

We are exploring moving our search platform to Azure Search or Bing which are techologies that are being actively developed and should provide us with more features and capabilities.

I'm afraid we are not going to invest more in trying to optimize search with FTS.

**Comment by Almenon** [comment] 2018-09-21 23:06
@pkuma-msft thanks for the update.  Any timeframe for when the move will happen?

**Comment by Almenon** [comment] 2018-09-22 15:50
Holy crap changing my extension name to "AREPL for python" moved it to the *third* position in the search rankings when searching for python.  Thanks for the tip @eamodio and @gaurav42  !

**Comment by pkuma-msft** [comment] 2018-09-26 07:42
@Almenon Sorry we are still in early exploration stages, cannot comment on a timeline.

**Comment by joaomoreno** [comment] 2019-01-04 07:52
From @octref 

> Previously: https://github.com/Microsoft/vscode/issues/24511
> 
> Now if you search for Vue, Vetur doesn't even show up in the first page despite being the most popular Vue extension. The install count of the 24 Vue extensions in first page combined is not even half of Vetur's install count.
> 
> ![image](https://user-images.githubusercontent.com/4033249/50652857-a6a81b00-0f3c-11e9-95e2-e2838082acfc.png)
> 
> A new Vue user coming to VS Code have a hard time finding Vetur by organic search. He might be misled to install a lot of the random extensions in Marketplace and believe VS Code has poor support for Vue files.

**Comment by octref** [comment] 2019-01-04 19:02
@kesane-msft

- Which

**Comment by octref** [comment] 2019-01-04 19:10
> our search algorithm gives more weightage to matches in the extension's display name. If you add the "vue" term in your display name your extension would start showing as the top result.

@kesane-msft Which I would refuse. What do I call it? `Vetur Vue`?

Another example: Searching for "Golang"

![image](https://user-images.githubusercontent.com/4033249/50705744-a2e5c880-1010-11e9-941e-5a1d68cc6848.png)

What should [Go extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) do? Renaming it to Golang? After which the query `Go` wouldn't return it as top result?

Maybe it's better to start a community curation of good extensions for each language/framework. http://howistart.org/ is a good example. At least it wouldn't be impossible for new users to find which extension to use, because the search results are not ranked helpfully.

**Comment by eamodio** [comment] 2019-01-04 19:24
Maybe there could be a keyword (maybe the first one?), that is ranked as if it was part of the title. So that way GitLens could have _git_, Vetur could have _vue_, Go could have _golang_, etc.

**Comment by fabiospampinato** [comment] 2019-01-04 19:36
> Maybe there could be a keyword (maybe the first one?), that is ranked as if it was part of the title. So that way GitLens could have git, Vetur could have vue, Go could have golang, etc.

This sounds too specific to me, IMHO the solution is transitioning from full-text search to a real search engine. Readmes, titles, descriptions and keywords should be properly indexed and the search query should be properly parsed too.

**Comment by eamodio** [comment] 2019-01-04 20:42
@fabiospampinato While I don't disagree -- I was just trying to offer an alternative that would hopefully be easy to implement but improves things somewhat and therefore likely to happen 😉

**Comment by bardware** [comment] 2019-02-27 21:07
Just wanted to open this as an issue. I often read `search for [xxx] and install the first result`.
I search the exact name of an extension and the one I'm looking for never is the first result :(

![image](https://user-images.githubusercontent.com/802702/53523036-073a7b00-3adc-11e9-8000-2b2b802ba1e5.png)

**Comment by jeff-hykin** [comment] 2019-03-31 10:31
I can confirm this is still a bad issue. 
### This isn't a 'bad' search algorithm, something is broken here.

When searching for "line endings" (picture below)<br>
The following 4 circles are all similar extensions. The red circles have MORE downloads, installs, and better ratings, and I checked the `package.json` all of them have "line endings" in the title and as keywords.<br>

How can 'Line Note' (4th result) which
- doesn't have 'endings' in the title
- has 203 downloads
- no reviews
- doesn't even have 'endings' in the package.json or readme 

Beat out both 'line-endings' and 'code-eol (2019) Line Endings'
- both contain the full search term in the title
- they have 4K and 6K downloads respectively
- they have 4 stars and 5 stars respectively
-  and have 'line endings', 'line', 'endings' in the keywords of the package.json and readme

And it's not like 'Line Note' is some anomaly, there are 25 just as bad results that come before the relevant one. 

<img width="1221" alt="Screen Shot 2019-03-31 at 5 02 32 AM" src="https://user-images.githubusercontent.com/17692058/55287759-c059d280-5372-11e9-8c99-21549a98d33f.png">

**Comment by jeff-hykin** [comment] 2019-03-31 10:39
My only theory to how these are being ranked, is that the marketplace has accidentally grabbed 200 results and accidentally sorted them by trending-ness instead of search-query relevance.

Since this is an upstream problem, is there a more direct repo we can reach out to @auchenberg. 

If not then I agree with @octref, its been 2 months, it's probably time for the community to start building their own solution. I don't understand how something this critical can fail without tests catching it and a rollback being issued.

**Comment by kesane-msft** [comment] 2019-04-01 12:21
@jeff-hykin , I am from the Marketplace team. Thanks for bringing this issue to our notice. We are looking into it and will get it fixed.

**Comment by jeff-hykin** [comment] 2019-04-18 03:45
Any updates after half a month?

If it hasn't been looked into, an estimate on when it will be looked into would be nice.
If it has been looked into, an update on what was found/not found would also be nice.

If the Marketplace team has higher priority tasks that's fine, I completely understand, I think we would just like to know that.

**Comment by kesane-msft** [comment] 2019-04-18 06:56
@jeff-hykin , we would have the fix for the issue you reported rolled out by next week or so.

**Comment by Almenon** [comment] 2019-04-18 07:06
@kesane-msft any details on what changes are being made exactly?

**Comment by kesane-msft** [comment] 2019-04-18 08:31
@Almenon , we are tweaking our index analyzers.

**Comment by kesane-msft** [comment] 2019-04-25 13:52
@jeff-hykin we have rolled out the change. You should see the better search results.
Thanks for bringing it to our notice and keep the feedback coming in!

**Comment by fabiospampinato** [comment] 2019-04-25 14:35
It seems that some issues have been addressed, but some things got even worse:

- Now searching for both `vscode-todo-plus` and `fabiospampinato.vscode-todo-plus` returns 0 results, IMHO that's unacceptable (and this was the original problem reported in this issue).

- Sometimes if I type `open in browsers` and then hit enter the query becomes `open in browser`, deleting the last character 🤷‍♂️.

- The marketplace doesn't search automatically until I hit enter, _unless_ I delete the query, IMHO that's pretty confusing (and that's also not what's happening in the homepage).

- If I clear the input field then the cursor disappears for a while until the results are returned.
  - There's probably no need to wait for those results to be returned in the first place, the top 55 extensions by downloads won't change very often, I'd just cache them (refreshing the cache once a day or so) and just ship them along with the rest of the page to the browser.

**Comment by Almenon** [comment] 2019-04-25 15:25
Yep things still aren't working right. Earlier gaurav42 said that "While searching an extension, we also take into account the community inputs like number of downloads, number of ratings and average rating along with the string matching". However, when I search for "python" "python extended" is above my extension despite having literally 0 reviews. In terms of download count we are very close (130k vs. 150k) so if the reviews were taken into account I would expect AREPL to be ranked higher. 

I would even go so far as to say that reviews should be _more_ important than download count in influencing search ranking (assuming you have enough reviews to be statistically valid). As a user when I search for things I want to find the best extensions, not the most downloaded extensions, but my extension has good reviews so I am biased on that front :P

@kesane-msft can you explain the change in more detail please? I don't know what "tweaking the index analyzers" means.

**Comment by Almenon** [comment] 2019-04-25 15:32
Oh and here's a really weird one - python (pydev) is ranked above python test explorer, despite having the same number of reviews, python mentioned in description of both, worse reviews on average, and ~45k less downloads.

**Comment by Almenon** [comment] 2019-04-25 15:34
I'm not sure what algorithm is being used but there's some existing ones that may be helpful:

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
https://stackoverflow.com/questions/1411199/what-is-a-better-way-to-sort-by-a-5-star-rating

**Comment by jeff-hykin** [comment] 2019-04-25 20:54
Thanks @kesane-msft, I appreciate it. The "Line endings" search seems to be fixed so I'm pretty happy about that, but after a few searches I agree with @Almenon the search is still pretty broken. I know there's probably reasons it can't be open sourced, but some transparency about how the search works/what is breaking it in the first place would go a long way.

Here's an example of the search still being really messed up (below). It's an improvement from the last 3 months; at least the relevant results are somewhere in the top 10, and the other results are popular. But on the other hand it is pretty sad that the students in my undergrad Info Storage and Retrieval class wrote better ranking systems than this in less than a month.

<img width="382" alt="Screen Shot 2019-04-25 at 3 36 20 PM" src="https://user-images.githubusercontent.com/17692058/56767016-64ffe200-6770-11e9-970e-2efb90a2e104.png">

If the marketplace team made an API that would allow for exact-name matches and regex matches I'm pretty confident the VS Code community could fix this within 48 hours.

**Comment by sandy081** [comment] 2019-04-29 14:24
Marketplace team has recently updated their search strategy to use Azure based search and which will expect to fix quiet a number of search related issues. There could be still some gaps which might exist and can be fixed. Since this issue is overwhelmed with lot of feedback and it is getting hard for us to understand what is fixed and what is not, I am locking this issue and ask users to create separate issues if they see any new bugs. At the same time, I would go through this complete issue and extract those which are not yet fixed into new issues which will help us and Marketplace team to better track and fix them. Thanks for the feedback provided here.

**Comment by octref** [comment] 2019-04-29 18:49
Took me quite a while to test, but **nothing was fixed** and search by author ID, extension ID, or combination of both are broken.

| Query | Marketplace Search | Expected | Actual | Regression |
|---|---|---|---|---|
|`fabiospampinato.vscode-todo-plus`| [Link](https://marketplace.visualstudio.com/search?term=fabiospampinato.vscode-todo-plus&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) and top-ranked | 0 result | N/A |
|`vscode-todo-plus` | [Link](https://marketplace.visualstudio.com/search?term=vscode-todo-plus&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) and top-ranked | 0 result | Used to at least hit but not top-ranked |
|`vscode-open-in-browsers` | [Link](https://marketplace.visualstudio.com/search?term=vscode-open-in-browsers&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit and top-ranked | 0 result | Used to at least hit but not top-ranked |
|`vue`| [Link](https://marketplace.visualstudio.com/search?term=vue&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) and top-ranked | Hit but not top-ranked | N/A |
|`golang`| [Link](https://marketplace.visualstudio.com/search?term=golang&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit [Go](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) and top-ranked | NOT in result | N/A |
| `octref` (publisher id) | [Link](https://marketplace.visualstudio.com/search?term=octref&target=VSCode&category=All%20categories&sortBy=Relevance) | Hit all extensions published by [octref](https://marketplace.visualstudio.com/publishers/octref) | 0 result | Used to hit all extensions published by [octref](https://marketplace.visualstudio.com/publishers/octref) |

**Comment by sandy081** [comment] 2019-04-30 08:43
@octref Thanks for consolidating already (I was planning to do it this week). These issues were already raised with Marketplace team and here is their explanation

### Searching by id: `GitHub.vscode-pull-request-github-insiders`

We don’t support search on id of the extension(Not supported in SqlFTS too). When we search for GitHub.vscode-pull-request-github-insiders, then we search for two words “GitHub” and “vscode-pull-request-github-inside”.  That’s why all the extension’s containing Github are coming at the TOP and results are looking better than SqlFTS.

**Tip**: You can search by extension id using the phrase `@id:GitHub.vscode-pull-request-github-insiders`. Issue: https://github.com/Microsoft/vscode/issues/69350. Let's track it there.

### Searching by publisher id: `dias`

Azure search provides us custom analyzer to control search relevance. We had done stemming during indexing. So when user searches for “dias”, it returns all the extensions containing “dia” or “dias” both. Here DialogScript is coming at the top, because it contains “dia” , while “dias” is matched in publisher display name of “Open Folder Context Menus for VS Code” extension.  Extension display name prefix match has more weight than publisher display name. That’s why “DialogScript” is  coming at the top.
We have fixed this issue. We are not doing stemming now. So if you will search for “dias”, it will return the extension’s containing “dias” only.

**Tip**: You can search by publisher using the phrase `publisher:"Pine Wu"`. You can also click on Publisher name in the extension editor. I think this is a good solution for searching by publisher.

### Vue

We do have weights on tags too, but it’s very less (1/100)  in compare to extension’s display name. That’s why Vetur extension’s is not coming at the top, when user searches for ‘Vue’. ‘Vue’ search term is a  special case, where we expect Vetur extension as top result, because it’s a popular extension of ‘Vue’ language. We were unbale to solve this problem using SqlFTS, but we can solve this using AzureSearch. We can add Synonym Maps property to the index field definition in AzureSearch.

@kesane-msft Please add any details if missing. After consolidating, one of the improvements we would like to see from you is with respect to `vue` phrase in which case giving weightage to tags might help.

**Comment by isidorn** [comment] 2021-08-19 15:17
Upstream issue https://github.com/microsoft/vsmarketplace/issues/154

**Closed** 2022-10-31 14:00 UTC
Labels: upstream, marketplace, upstream-issue-linked
