### ISSUE TITLE
"Open File" command often does not switch to the file but another one

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114274] opened 2021-01-13 13:14 UTC
![image](https://user-images.githubusercontent.com/900690/104456855-91ddd380-55a9-11eb-8e62-5a724417e9f9.png)

I often end up with a different file than I was clicking on "Open File" lately. Did something change here recently? It looks like a file is opening from the changeset but not from the active editor.

//cc @joaomoreno

**Comment by bpasero** [comment] 2021-01-13 13:16
Having a hard time reproducing with a fresh user data dir :-(

**Comment by alexdima** [comment] 2021-01-13 22:23
This has been driving me crazy since a couple of days. It happens on multiple machines. It just happens when doing development, like editing a file, looking at the diff, staging the file, editing the same file some more, looking at the diff some more, staging the file again, etc. When clicking the open editor action, it oftentimes opens the file in the wrong location. Once I close all open editors (I have a lot of diff editors leftover opened), the action begins to work correctly again.

**Comment by eamodio** [comment] 2021-01-14 03:23
Duplicate of #114192

**Closed by eamodio** 2021-01-14 03:23 UTC
Labels: bug, git
