### ISSUE TITLE
终端滚动条无法拖动，终端输出信息无法复制

### ISSUE THREAD

**Issue by stayfool** [Microsoft/vscode#26898] opened 2017-05-19 01:19 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-mocha|Compulim|0.1.1|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|beautify|HookyQR|1.0.2|
|vscode-icons|robertohuertasm|7.7.0|
|guides|spywhere|0.7.0|;

---

Steps to Reproduce:

1.终端的滚动条不能拖动，上下翻页只能靠滚动条
2.终端界面里的信息无法复制

**Comment by Tyriar** [comment] 2017-05-19 19:11
Likely a duplicate of https://github.com/Microsoft/vscode/issues/20505 or https://github.com/Microsoft/vscode/issues/19665

**Closed by Tyriar** 2017-05-19 19:11 UTC

**Comment by stayfool** [comment] 2017-05-22 07:25
@Tyriar sorry, I didn't use English to search for this
