### ISSUE TITLE
not opening terminal 

### ISSUE THREAD

**Issue by mayurBharodiya** [microsoft/vscode#93555] opened 2020-03-27 07:18 UTC
Issue Type: <b>Bug</b>

" The terminal shell path "cmd.exe" does not exist " error occured when trying to open terminal in vs code.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:36:51.261Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2

</details>

**Comment by mayurBharodiya** [comment] 2020-03-27 07:27
I am just trying to open a terminal by shortcut ctrl+shft+` or ctrl+`  , but the notification comes that The terminal shell path "cmd.exe" does not exist .

**Comment by sportshead** [comment] 2020-03-27 08:11
Duplicate of #1479

**Comment by Tyriar** [comment] 2020-04-05 16:40
Can you share your settings.json file?

**Comment by mayurBharodiya** [comment] 2020-04-21 14:56
settings.json  

`{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "typescript.check.npmIsInstalled": false,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 10000,
    "workbench.colorTheme": "Quiet Light",
    "terminal.integrated.automationShell.windows": "",
    "terminal.integrated.env.windows": {
    
    },
    "editor.fontSize": 18
}`

**Comment by Tyriar** [comment] 2020-04-21 15:21
Does removing `"terminal.integrated.automationShell.windows": ""` fix it?

**Closed** 2020-04-29 11:23 UTC
Labels: needs more info
