### ISSUE TITLE
VS Code doesn't remember the last folder's path, when the workspace area is empty

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#38739] opened 2017-11-20 02:57 UTC
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

Workspace is empty, you are adding a folder to it:

![image](https://user-images.githubusercontent.com/24613274/33000049-6231139e-cdae-11e7-9aba-b6816f071738.png)

You've added folder from the local disk D:
![image](https://user-images.githubusercontent.com/24613274/33000093-9750a346-cdae-11e7-9f7a-aba2fc69480d.png)

Then you are deleting the folder from workspace, trying to add another folder, and VS Code opens the default folder of snippets?..

> C:\Users\YourName\AppData\Roaming\Code - Insiders\User\snippets

It has to open the previous one ( D:\ ), don't you think?

PS: it remembers the "last folder path" only if the list is NOT empty.

**Comment by bpasero** [comment] 2017-11-20 06:31
@user3323 I think I cannot reproduce, is that what you are doing?

![before](https://user-images.githubusercontent.com/900690/33005144-d2aa59bc-cdc4-11e7-814e-c5184f6a70d2.gif)

**Comment by user3323** [comment] 2017-11-20 07:28
@bpasero, now I got how it works.

It takes the directory from the active editor tab. So, in my case - I've had "`C:\Users\YourName\AppData\Roaming\Code - Insiders\User\snippets\javascript.json`" in active tab, and that's why it was opening " ... User\snippets " for me.

Someone can say it is a feature. But I think it is wrong behavior.

**Comment by bpasero** [comment] 2017-11-20 07:52
@user3323 ah yeah that is intentional actually. Closing as designed.

**Closed by bpasero** 2017-11-20 07:52 UTC
Labels: multi-root, needs more info
