### ISSUE TITLE
Auto expand panel stopped working in v1.25.0

### ISSUE THREAD

**Issue by Sofianio** [Microsoft/vscode#54027] opened 2018-07-11 08:48 UTC
- VSCode Version: 1.25
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Split to 2 panels (2 columns)
2. Resize the right one to the minimum width
3. When you click inside the right one it doesn't expand automatically like it used to in v1.24

Does this issue occur when all extensions are disabled?: Yes

is this a bug? if so plz fix it
was it removed? if so plz bring it back.
was it disabled? if so is there's a setting to re-enable it?

Thanks

**Comment by bpasero** [comment] 2018-07-11 09:37
Duplicate of #51614

You can try out the insider release to verify the fix works for you: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2018-07-11 09:37 UTC

**Comment by Sofianio** [comment] 2018-07-11 11:13
Thanks for the reply.
I confirm, this is fixed in insider release.
I hope it goes into the next stable release without problems.
For now I went back to 1.24.1
