### ISSUE TITLE
Themes: Scoope Settings (Background)

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#35611] opened 2017-10-05 07:41 UTC
Hi there

I'm working on a theme vor Visual Studio Code for our devs.

According to [docs.sublimetext](http://docs.sublimetext.info/en/latest/reference/color_schemes.html#sub-elements-of-settings) it should be possible to define the background Color of "scooped settings"...

Somehow VSC seems to ignore this constantly .
Could it be, VSC isn't allowing background colors for specific code-blocks?

I searched the web for bout 4 hours now and it seems that i can't find any reasons why this should not work at all.

My Code in myTheme.theme.json (made with Yo Code)

```
		{
			"name": "Comments",
			"scope": "comment",
			"settings": {
				"fontStyle": "bold",
				"foreground": "#155230",
				"background" : "#FFFFFF"

			}

```

I'd appreshiate  help or advice on this topic.

Regards
Roman

P.S.: If I should ask this question at another Forum, please let me know.

**Comment by aeschli** [comment] 2017-10-05 19:48
That's a known limitation of VSCode: Duplicate of #3429

**Closed by aeschli** 2017-10-05 19:48 UTC
Labels: workbench
