### ISSUE TITLE
[debug] Variables with null values are not displayed.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#10215] opened 2016-08-05 19:00 UTC
- VSCode Version: 1.4
- OS Version: All

When a debug adapter returns `Variable`s with `value: null`, they are not displayed in the variables viewlet.
However, this is a legitimate situation in some cases:
- For compound objects, there may not a useful information to return as a value of the container itself (Okay, this may be worked around by returning some canned string such as "\<object\>")
- Primitive types may also lack values if, e.g. one is debugging an optimized build.  Here, returning a canned string is more problematic, because VSCode will allow editing it and will try storing it back.

IMO, null-valued variables should still be displayed.

**Comment by weinand** [comment] 2016-09-15 20:02
@isidorn let's discuss this.

**Comment by isidorn** [comment] 2016-09-19 08:33
@weinand I think github accidently closed this issue by you pushing a revert of the fix -> reopening

**Comment by isidorn** [comment] 2016-09-20 10:31
This works for me in latest, in the screenshot you can see that I modified the debug adapter to return null for variable values and they are all nicely displayed.
@vadimcn let me know if you can still reproduce this with latest

![screen shot 2016-09-20 at 12 29 30](https://cloud.githubusercontent.com/assets/1926584/18666800/fed4ea3e-7f2d-11e6-9f1e-876f73b7bdad.png)

**Closed by isidorn** 2016-09-20 10:31 UTC
Labels: debug
