### ISSUE TITLE
Terminal: git log -> Ctrl-C -> can't see entered commands (but they are executed)

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode#37069] opened 2017-10-28 04:33 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Set `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"` in settings
2. Open terminal inside a git repo
3. Enter `git log`
4. Press Ctrl-C to quit

After these steps it quits to the shell but I can't see what I'm typing anymore, though the commands that I'm typing are executed and I can see their output.

Reproduces without extensions: Yes

**Comment by adInfimum** [comment] 2017-11-06 21:58
Looks like a duplicate of #36812

**Closed** 2017-11-07 20:44 UTC
Labels: bug, help wanted, integrated-terminal, upstream, windows
