### ISSUE TITLE
Integrated Terminal fully Black 

### ISSUE THREAD

**Issue by RayyanNafees** [microsoft/vscode#187382] opened 2023-07-09 09:35 UTC
# There's nothing u can see in the Terminal

![image](https://github.com/microsoft/vscode/assets/59685062/239440c9-b173-41ef-a2e0-b10ea10759ec)

Things become visible if I hover over a terminal tab:

![image](https://github.com/microsoft/vscode/assets/59685062/ab417009-b7c8-4061-b9d9-6c576206875e)

Or if a Notification comes:
![image](https://github.com/microsoft/vscode/assets/59685062/3aaaeb24-6434-4832-96c1-f9964f445348)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.0
- OS Version: Github Codespace

Steps to Reproduce:

1. Start a codespace in Opera Developer Browser (which is a chrome derivative)
2. Open the integrated terminal

**Comment by starball5** [comment] 2023-07-09 23:36
Duplicate of #187367?

**Closed** 2023-07-10 12:17 UTC
