### ISSUE TITLE
Extra space added after pasting JSDoc comment

### ISSUE THREAD

**Issue by bencresty** [microsoft/vscode#121004] opened 2021-04-10 09:21 UTC
- VS Code Version: 1.55.1 (but also 1.55.0 and at least the last one or two minor versions of v1.54)
- OS Version: Windows 10

Code formatting in at least es6 is broken since last 2 or 3 minor versions of Vs Code. It happens a lot since that code aligns completely wrong and out of place while there is nothing wrong with the code. It's pretty frustrating. This was working fine and without issues before. This is not an issue with some extension as it's also the case when running without extensions.

The reason for this 'confused formatter' seems to be that after copying code with jsdoc, the alignment of the method name is wrong in the pasted fragment and that confuses the formatter for the rest of the code and every time it tries to format it after that paste. BTW in the example below the error-offset is only one space, but it also happens that the alignment skips 'tabs' (spaces here) and that makes the code even more misaligned and so unreadable and messed up.

See gif:

![Formatter-Issue](https://user-images.githubusercontent.com/69322733/114264983-78a0c380-99ee-11eb-9106-122960254235.gif)

Steps to Reproduce:

1. Copy code with jsdoc
2. Paste code with jsdoc
3. See that the method name isn't alligned as supposed to, but now is aligned to the jsDoc. See that the formatter is confused and keeps messing up.

Does this issue occur when all extensions are disabled?: Yes (see demo)

**Comment by bencresty** [comment] 2021-05-10 18:57
@mjbvz Hello Matt, I just see you changed the title to something different here, but what you changed it into is an assumption of yours that just isn't right.

1) It's clearly not only pasting a JSDoc comment
2) Also other parts of the formatter, without jsDoc, have issues since this update (as I wrote in the post)

I would appreciate it if you're not changing titles of issues I post without verifying first if what you make of it it is actually true.

**Comment by bencresty** [comment] 2021-05-14 10:45
> Your original title was too generic. The new one better describes the issue

Well, it's obvious I see that differently; it wasn't too generic, these issues are obviously related and now you narrowed the issue to something that it's not.

> Please open separate issues for any other formatting bugs you see

I'd rather not need to open any issues like this one at all. These are issues that could have been prevented by just simple tests IMO, and weren't there before so I don't get why they are here now in the first place. No offense, you guys create a great tool and you obviously work very hard. But as a daily user for years now it would be nice to see some issues getting fixed again as important issues we bump our heads to are piling up for some months now. Unfortunately lately more and more issues were introduced in VS Code and I don't see them getting fixed for a long time now unfortunately. Some of them are making working with VS Code more and more frustrating, while this was such a great and flawless experience before. Which is a shame as it's such a great tool with such a great base and I love. Just hoping for an update without new features, but making stuff reliable again! Keep up the great work

**Comment by ssigwart** [comment] 2021-12-17 04:19
I do think this is a duplicate of #119225.  I have PR #136579 open that should fix this.  @mjbvz, should I tag my PR as fixing this issue too?  I haven't been able to get anyone to review it yet, though.

**Comment by bencresty** [comment] 2022-01-16 09:03
Thanks @ssigwart . This issue is pretty annoying. So let's hope your PR gets this fixed and gets merged soon!

**Comment by bencresty** [comment] 2022-04-15 14:17
@ssigwart the issue is still there. Just tried the latest Insiders build (1.67.0-insider), but also there it isn't fixed yet.

This issue is around and annoying for over a YEAR!!!! now. When will this ever be fixed? It's annoying as hell. I also don't get why this wasn't fixed directly after it occured after breaking a working version of VS Code. Wouldn't that have been easier than to fix this a year later (if ever)?!

**Comment by ssigwart** [comment] 2022-04-15 14:20
@bencresty, I'm just a contributor with limited repo permissions.  I have the same feelings.  I have several unreviewed pull requests that I can't get any traction on.  At this point, I've stopped contributing because I was just wasting my time.  When someone starts responding to my PRs, I'll start contributing again.

**Comment by jespertheend** [comment] 2022-04-15 15:06
Is there a way we can bring this to the attention of the Microsoft team? Is it stuck in review because they're not aware of its existence or does this simply have a low priority?

**Comment by ssigwart** [comment] 2022-04-16 01:13
When I first started contributing, I did get a few fixes for other things through, so I think the process is to submit PRs and then someone from Microsoft will prioritize it.  I feel like if people who are affected start adding reactions and comments to the relevant issues (this, #127589, #119225, #140895), maybe it could raise the priority.

**Comment by bencresty** [comment] 2022-04-16 07:23
> @bencresty, I'm just a contributor with limited repo permissions. I have the same feelings.

Ok, sorry that I didn't look more closely into who you are. Thanks for letting me know.

> I feel like if people who are affected start adding reactions and comments to the relevant issues (this, #127589, #119225, #140895), maybe it could raise the priority.

Might be, but that's not the way it should work IMO. People at Microsoft building this are developers too so they know programming is not only picking the fun parts by making all kinds of cool stuff and sugar 99% of the people will never use and first make sure that what's actually important works and gets fixed if it's not working.

Last updates there are introduced a lot of annoying bugs that took forever (meaning at least a year) to fix or are still not fixed.

People at Microsoft surely know what priorities of its users are, but they have other priorities. It's the world upside down if we should do all kinds of tricks to get attention to bugs they introduce and are still not fixed after a year. That's just crazy to me.

**Comment by ssigwart** [comment] 2022-04-16 14:09
Yes, it's annoying. This bug is not the worst one that I have an open PR for in my opinion. However, Microsoft built a really good editor that they open sourced and offered for free. I don't think it's fair to make assumptions about what Microsoft's intentions are. Also, the individual developers likely are annoyed by similar bugs, but have other work responsibilities, so they can't choose to spend time on whatever bug they please. They do mention in https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request that up-voting features is part of their triaging, so I think the most constructive thing to do would be to have anyone that's affected by this and other bugs to up-vote them.

**Comment by Friksel** [comment] 2022-04-19 11:52
@ssigwart 

> Yes, it's annoying. This bug is not the worst one that I have an open PR for in my opinion. However, Microsoft built a really good editor that they open sourced and offered for free. 

I agree. This is a great editor and I'm working in it with a lot of pleasure every day. That doens't mean everything is perfect tho and if an issue is standing for over a year, while introduced in a before fine working program, we might expect action would be taken a little sooner instead of introducing all kinds of new features that I consider sugar.

Of course that's completely up to Microsoft and they have all rights to do so and I also get that's it's far more enjoyable to introduce new features than to fix issues. And I also understand they're fixing a lot (!!) of issues anyway and they have a massive user base. So I completely acknowledge how difficult that must be and think they do a great job at it still. Eventhough I don't agree on how they handled this particular issue.

> I don't think it's fair to make assumptions about what Microsoft's intentions are. Also, the individual developers likely are annoyed by similar bugs, but have other work responsibilities, so they can't choose to spend time on whatever bug they please. 

It looks like my point didn't come across as intended. I'm not at all mad ad Microsoft nor on its developers. Why would I? I'm only thinking in perspectives and imagine that Microsoft has a different perspective on things than its users have in deciding what to fix and/or when and what the priorities are. When a commercial company like Microsoft is investing lots of time and money into a project like VS Code you might expect something beneficial to be the reason in the end. That's just common sense to me, nothing offensive.

>> They do mention in https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request that up-voting features is part of their triaging, so I think the most constructive thing to do would be to have anyone that's affected by this and other bugs to up-vote them.

So lets' upvote ;)

Have a nice day!

**Comment by SomervilleTom** [comment] 2022-10-28 20:37
I appreciate the attention this bug has already received.

This has apparently been open for a year and a half -- since at least April of 2021 (I write this at the end of October 2022).

A new bug report that I opened has been closed as a duplicate of this. That's fine -- but does anybody at Microsoft care?

The impact of this bug is to break every Javascript file that includes a standard JSDoc header. The only workaround I've found is to edit the JSDoc block comment header (by hand, since there seems to be no way to specify or change the behavior of the "feature" that adds block comments) -- and thereby make each JSDoc header non-compliant with the widely accepted JSDoc specification.

This is is FAR more important to me than the pretty much every entry I've seen in the VSC changelog since April of 2021.

Who decides which of these open issues to address in any one release?

Is it REALLY that hard to make VSC handle this correctly?

My intent in adding this comment is help raise the awareness of this issue within the MS development team. I appreciate any attention that team can give to solving this issue. If nothing else, perhaps the team could provide guidance about a timeline for resolution.

**Comment by bencresty** [comment] 2022-10-28 21:26
>> Is it REALLY that hard to make VSC handle this correctly?

It's even worse: this was working perfectly fine before they messed this up and IMO they could've and should've just look in the changelog at the time to find out what would've caused this to fail when it was reported, because it was still freshly damaged at the time and wouldn't probably be too difficult to trace back than. But instead they added lots of new features... and introduced lots of new features instead.

Rule no 1 for developers IMO; when something is destroyed by a mistake, stop adding new features and fix the bug first. Especially a bug that has so much impact and is directly touching the core of the product: editing code.

**Comment by SomervilleTom** [comment] 2022-10-28 21:35
@bencresty: I've been on the developer's side of a big project like this, and I'm therefore sympathetic.

I mostly hope that the visibility of this bug can be raised enough to get it onto the list of things to fix -- perhaps even in the November update cycle.

**Comment by ssigwart** [comment] 2022-11-19 18:06
#136579 was merged yesterday, so I think this should be resolved by that when the next version comes out.

**Closed** 2024-03-18 15:25 UTC
Labels: bug, typescript, javascript, editor-autoindent
