### ISSUE TITLE
Double Tap Commands

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#68832] opened 2019-02-16 11:09 UTC
This is a wild suggestion, but maybe the ability to double tap certain non problematic keys can be used as shortcuts to some operations.

For instance, say you press ctrl and very quickly you press ctrl again, as some sort of double click but for a keyboard key. And doing this triggers a programmable action, like Go To Symbol or Toggle Sidebar for example.

I have implemented this myself, and it's actually not easy to do right, some things have to be taken into account as to reduce accidental triggers.

Just wanted to share the idea.

**Comment by usernamehw** [comment] 2019-02-16 13:42
Possible duplicate of #5280

**Comment by alexandrudima** [comment] 2019-02-18 16:02
:+1: Given the similarity (repeated modifier only keybinding) I would suggest to track in #5280 .

**Closed** 2019-02-18 16:03 UTC
Labels: *duplicate
