### ISSUE TITLE
Task "clear" doesn't work for "npm" task

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62404] opened 2018-11-01 18:01 UTC
From #30058

I don't know whether this is supposed to work. I modified the build task from https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/.vscode/tasks.json to clear the terminal before building, and to be a build task instead of watching. So it looks like this:

```json
{
    "label": "my build task",
    "type": "npm",
    "script": "build",
    "problemMatcher": "$gulp-tsc",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": true
    },
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
```

- I run `task my build task`
- I run it a second time
- It doesn't clear the terminal, the output from the first run is still visible

If I modify it to be a shell task then it does clear the terminal as I'd expect

```json
{
    "label": "my shell build task",
    "type": "shell",
    "command": "npm run build",
    "problemMatcher": "$gulp-tsc",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": true
    }
}
```

**Comment by alexr00** [comment] 2018-11-05 09:57
Thanks for filing! Duplicate of #62474

**Closed by alexr00** 2018-11-05 09:57 UTC
