### ISSUE TITLE
Add the case-sensitive text selection

### ISSUE THREAD

**Issue by wizard1989** [microsoft/vscode#43190] opened 2018-02-08 10:41 UTC
### Issue Type
Feature Request

### Description

Now, when I select the "text",  "TEXT" is also selected, like they are the same variables.
Please add the case-sensitive selection or option to choose the case-sensitive selection.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z)
OS version: Linux x64 4.4.0-53-generic

**Comment by rockerest** [comment] 2018-03-28 20:04
This particular bug is very nearly a dealbreaker for me using VSCode.

Changing text regardless of case should not be the default behavior; I have never worked in *any* programming language where variables or other strings are considered the same regardless of case.

**Comment by Morgy93** [comment] 2019-01-14 10:49
*push*

![image](https://user-images.githubusercontent.com/7961978/51108371-52315500-17f2-11e9-9785-ccc5e6fbd18d.png)

**Comment by rebornix** [comment] 2020-11-02 23:28
/duplicate of https://github.com/microsoft/vscode/issues/18239

**Closed by rebornix** 2020-11-02 23:28 UTC
Labels: editor-find, feature-request
