### ISSUE TITLE
massive d day bug! 

### ISSUE THREAD

**Issue by synerr** [microsoft/vscode#92977] opened 2020-03-19 00:30 UTC
Issue Type: <b>Bug</b>

I just wanted to let you guys know of a serious threat to your program VScode. It only makes sense that the people using your application would notice bugs on the very tool they use to fix them! 
If you click the settings gear, with the "Latest Updates" still window open and select "Color Theme" it will not display my Color Theme options until that "Latest Updates!" window is silenced...

Love you guys thanks for everything!

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment] 2020-03-19 10:25
Looks like all webviews are affected. Can be reproduced if Markdown preview is active.

Version: 1.44.0-insider (user setup)
Commit: 708b019bb4e20f07cf89df9f1d943af3d38d7a70
Date: 2020-03-18T06:30:46.175Z

**Comment by mjbvz** [comment] 2020-03-19 17:03
Duplicate of #75209

**Closed by mjbvz** 2020-03-19 17:03 UTC
Labels: new release
