### ISSUE TITLE
On the latest public Windows Insider Fast Ring build (16257) VS Code can't open OneDrive files

### ISSUE THREAD

**Issue by qmatteoq** [Microsoft/vscode#32982] opened 2017-08-22 21:12 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16257
- Extensions: none
---

Steps to Reproduce:

1. Upgrade your PC to the latest available Windows 10 Insider Fast Ring build (16257)
2. The new OneDrive client has the option to let you see like if they're local also files that are on the cloud.
3. Try to maintain a local copy of a text file or a folder from OneDrive but right clicking on it and choosing "Always keep on this device"
4. Right click on it and choose "Edit with Code"
5. Notice that an empty file is opened
6. Manually open Code and try to open the same file from File -> Open file.
7. You'll see an error claiming that the file doesn't exist.

If you try to do the same with any other editor (like notepad) the file is properly opened.

**Comment by primortal** [comment] 2017-08-23 13:56
I was just coming to report the same issue :D

**Comment by Tyriar** [comment] 2017-08-23 15:36
Duplicate of https://github.com/Microsoft/vscode/issues/27285

**Closed by Tyriar** 2017-08-23 15:36 UTC
Labels: new release, workbench
