### ISSUE TITLE
Windows: drop into application does not work if running as admin

### ISSUE THREAD

**Issue by felix-last** [Microsoft/vscode#11277] opened 2016-08-31 04:04 UTC
- VSCode Version: 1.5.0-insider (commit 92d3324e3d05a6d2b765c08651d89e9ec1d19f4c)
- OS Version: Windows 10

Steps to Reproduce:
1. Drag file from Windows Explorer
2. Drop anywhere onto VS Code

I expect that it opens the file. Instead, it shows a disabled icon.

**Comment by bpasero** [comment] 2016-08-31 07:50
@felix-last I cannot reproduce, can you share a video how this looks like?

**Comment by felix-last** [comment] 2016-09-01 00:53
Sure! Here you go.

![video-to-gif](https://cloud.githubusercontent.com/assets/783826/18151388/f9927202-7042-11e6-9c24-35f447f8002e.gif)

**Comment by bpasero** [comment] 2016-09-01 04:39
@felix-last wow that is super weird, and not expected! I wonder if the source of the operation has any impact, does it reproduce with any file and any folder?

Here is how it works for me:

![editors](https://cloud.githubusercontent.com/assets/900690/18155554/dbc37908-700e-11e6-81d0-042028eb3b11.gif)

**Comment by felix-last** [comment] 2016-09-01 10:51
Wow thats strange. I'm running the Insider build as administrator. Maybe
that's the reason? I can test some more tomorrow, but I observed this
behaviour with all files I tried.

**Comment by bpasero** [comment] 2016-09-01 11:35
@felix-last I can reproduce and this seems to be an issue with running as Administrator (which we STRONGLY advise against). I do not see a fix from our end this seems to be blocked on a much lower level in Chrome.

**Comment by UEDDarthVader** [comment] 2016-09-01 12:29
This issue has one more impact. If VS Code is already running with priveleged ritghts you can't open any file with it using "open with" option from context menu or using double-click.

I have some config files in system folders (for example in "C:\inetpub\wwwroot\...") and in such a case I have to run Code as an administrator in order to be able to edit them.

**Comment by bpasero** [comment] 2016-09-01 13:13
There are many issues running Code as admin in one way or the other...

**Comment by UEDDarthVader** [comment] 2016-09-02 10:39
So, if running as administrator is not recommended. Could you please advise what is recommended practice for editing files, which require admin rights to be edited?

**Comment by bpasero** [comment] 2016-09-02 12:25
Yup, we are aware of this and plan to improve this in the future.

**Comment by bpasero** [comment] 2016-09-18 07:16
Closing, this seems to be standard behaviour for Chrome and likely a security thing they would not change.

**Closed by bpasero** 2016-09-18 07:16 UTC
Labels: bug, upstream, workbench
