### ISSUE TITLE
Disabled trust state in extension view is inconsistent

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122401] opened 2021-04-27 16:56 UTC
Testing #122228

Very much a polish item, but:

1. Without trusting the workspace, install eslint
2. In the extension view, it's shown as

![](https://memes.peet.io/img/21-04-83e3c284-031d-484c-88ea-18a4c1db01a9.png)

3. Refresh the search. It then shows as disabled correctly

![](https://memes.peet.io/img/21-04-2da27911-1e59-4682-b928-08292d5d6cb5.png)

**Comment by lszomoru** [comment] 2021-04-28 11:15
@sandy081, this is the issue related to refreshing the extensions list that we discussed in the past.

**Comment by sandy081** [comment] 2021-04-28 11:58
No, Its new and you have to update enablement (following method) when extension enablement has changed. 

https://github.com/microsoft/vscode/blob/aec0921e5c21e1e806f833545acd6103b6f0d327/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L181-L181

**Comment by sbatten** [comment] 2021-10-07 21:41
closing as dupe of https://github.com/microsoft/vscode/issues/122303

**Closed by sbatten** 2021-10-07 21:41 UTC
Labels: bug, extensions, workspace-trust
