### ISSUE TITLE
Multiple cursors, autocomplete only works for first cursor

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#16406] opened 2016-12-02 20:42 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (daa71ca002722c2778dc30bba151d7316e3c5e54, 2016-12-02T07:05:15.686Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.4|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.3|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.2|
|tslint|eg2|0.6.7|
|vscode-great-icons|emmanuelbeziat|1.1.26|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.0.0|
|HTMLHint|mkaufman|0.0.3|
|vscode-stylefmt|mrmlnc|2.2.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.0.4|
|stylelint|shinnn|0.20.3|
|theme-tesla|smlombardi|5.3.5|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. HTML file, have 2 tags, e.g. `td`, you want to add an attribute to, e.g. `class="foo"`
2. Click  next to the first `td`
3. Option-click in the second `td`.  You now have 2 cursors.
4. Start typing `class`.  Intellisense comes up.  
5. Choose "class"
6. only the first cursor completes.

See animated GIF below:
![dec-02-2016 15-39-00](https://cloud.githubusercontent.com/assets/835148/20849682/d9c98f18-b8a5-11e6-9488-d291fb398359.gif)

*On an unrelated note, how can I control or theme those bracket matcher indicators?  I don't like the square, I'd prefer simple underlines.

**Comment by chrmarti** [comment] 2016-12-02 22:04
@jrieken Is this #16277?

**Comment by jrieken** [comment] 2016-12-05 09:15
dupe of #16037

**Closed** 2016-12-05 09:15 UTC
Labels: duplicate, intellisense
