### ISSUE TITLE
Autocompletition between HTML and CSS/SCSS

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#50476] opened 2018-05-25 18:51 UTC
Im really missing autocompletition / suggestion elements / identifikators / classes between HTML and CSS/SCSS languages , and vice versa of course.

All plugins which i tested works not very well, and i also think, that should be native behavior.

Is it planned in the near future?

**Comment by aeschli** [comment] 2018-05-28 09:33
duplicate of #46200

**Closed by aeschli** 2018-05-28 09:33 UTC
Labels: css-less-sass

**Comment by Kcko** [comment] 2018-05-28 09:35
Please? Its not duplicate. Its not about folding ...

**Comment by aeschli** [comment] 2018-05-28 12:41
sorry, wrong bug: duplicate of #47331
