### ISSUE TITLE
Have Title Attribute Suggested Before Title Tag in Intellisense Suggestion

### ISSUE THREAD

**Issue by NightfallAlicorn** [Microsoft/vscode#39846] opened 2017-12-07 03:15 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.0
code-spell-checker|str|1.5.1
vjass|vas|0.0.8
markdown-pdf|yza|0.1.7

When writing HTML. It is more common to have multiple title attributes than title tags. When starting the HTML document with "<!DOCTYPE". Intellisense will suggest a basic page content which also includes a default page title tag. Having title tag suggested first when writing attributes for tags is kinda tedious. I would suggest title attribute being first choice unless it's possible to have vscode suggest the attribute first when writing in a tag.

---

Steps to Reproduce:

1. Attempt typing "title" with intellisense enabled in, for example, an input tag for an attribute.
2. The first option is always title tag `<title></title>` and not the attribute title `title=""`.

Reproduces without extensions: Yes

**Comment by aeschli** [comment] 2017-12-07 09:51
@NightfallAlicorn Sorry, I don't quite get it. Can you add a screenshot of what you see, and write what you expect instead?

**Comment by NightfallAlicorn** [comment] 2017-12-08 04:18
I did a small recording here to help explain: https://streamable.com/czdlx

At the start I type "<!" and I can intellisense a HTML document ready with tab key. After, I highlight the title tag which is only used once in the head section of the document.

When I try making an input tag in the body of the document and write "title". Intellisense suggests to add a title tag `<title></title>` as the first option when I press tab. I delete and write title again and choose the second title option which is correct for the attribute `title=""`.

I'm suggesting that the title attribute should be suggested first before title since title tag is only used once in a HTML document. The title attribute is used for providing tooltips on the element that is being pointed at in a web page which often has more than one.

**Comment by aeschli** [comment] 2017-12-13 08:48
Thanks @NightfallAlicorn. Now I see, it's emmet that proposes the 'title' tag at an attribute location.

**Comment by ramya-rao-a** [comment] 2017-12-13 19:01
Duplicate of #35128
This is fixed in the latest Insiders which you can get from https://code.visualstudio.com/insiders
Or you can wait for the next release which should be out in the next few days.

**Closed by ramya-rao-a** 2017-12-13 19:01 UTC
Labels: emmet
