### ISSUE TITLE
Theming for descendant scopes not working per TextMate documentation

### ISSUE THREAD

**Issue by chaseadamsio** [Microsoft/vscode#34909] opened 2017-09-24 17:48 UTC
When attempting to use descendant scopes in a VS Code theme, the scopes aren't picked up.

- VSCode Version: 1.16.1
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. Edit a theme with no other `tokenColors` by adding:
```
"tokenColors": [
        {
            "name": "[VSCODE-CUSTOM] Import",
            "scope": "source.ts meta.import-equals.external.ts",
            "settings": {
                "foreground": "#D983F5"
            }
        }
    ]
```
2. run "Reload Window" & make sure you're using the current theme you're editing.

When using `"scope": "meta.import-equals.external.ts"`, the setting is applied:
![image](https://user-images.githubusercontent.com/1024544/30785073-54463568-a115-11e7-96f4-4ebab4f2e049.png)

When using `"scope": "source.ts meta.import-equals.external.ts" no settings are applied:
![image](https://user-images.githubusercontent.com/1024544/30785079-6c78bcb4-a115-11e7-8ea9-9c2a7a3f4e41.png)

I've tested this with a number of existing themes that have the TextMate descendant scopes and have found that none of them are being applied. It's not clear from the Code Theme creation documentation that it shouldn't work.

Reproduces without extensions: N/A (can't use themes with extensions disabled as far as I can tell)

Also to confirm with an existing example from the docs, I attempted to replicate `meta.selector.css entity.name.tag` from https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers:

```
 {
            "name": "Functions",
            "scope": [
                "entity.name.function",
                "meta.selector.css entity.name.tag",
                "entity.name.method - source.java"
            ],
            "settings": {
                "foreground": "#ff0000"
            }
        }
```
The descendant scope was not applied:

![image](https://user-images.githubusercontent.com/1024544/30792198-5195b214-a16d-11e7-8984-81576f342560.png)

The `entity.name.function` was applied:

![image](https://user-images.githubusercontent.com/1024544/30792209-689d85b8-a16d-11e7-882c-24b34cd36a2a.png)

**Resources**

[TextMate Scope Documentation](https://manual.macromates.com/en/scope_selectors)

**Comment by aeschli** [comment] 2017-09-26 19:23
duplicate of https://github.com/Microsoft/vscode-textmate/issues/52

**Closed by aeschli** 2017-09-26 19:23 UTC
Labels: new release, workbench
