### ISSUE TITLE
Search and replace in workspace doesn't return all regex matches when using $

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/vscode#9553] opened 2016-07-20 22:03 UTC
- VSCode Version: 1.3.1
- OS Version: OS X

Steps to Reproduce:

1. Open a VSCode workspace
2. Open the search and replace panel
3. Activate the `Use Regular Expressions` button
4. Enter a regular expression ending with $
5. Notice that it only results in matches for open editors

**Comment by sandy081** [comment] 2016-07-21 19:00
@Wenzil It works for me. Please see the attached picture. Can you please provide more detailed steps, like an example, to reproduce.

<img width="1246" alt="screen shot 2016-07-21 at 8 59 46 pm" src="https://cloud.githubusercontent.com/assets/10746682/17035134/15bf9cee-4f86-11e6-9183-1666244d0ce4.png">

**Comment by sandy081** [comment] 2016-07-29 10:37
I am closing this since it works for me and did not hear back from the author.

**Closed by sandy081** 2016-07-29 10:37 UTC
