### ISSUE TITLE
Renderer consumes CPU after update to latest Insiders version

### ISSUE THREAD

**Issue by kirusyaga** [Microsoft/vscode#47883] opened 2018-04-14 21:55 UTC
- VSCode Version: 1.23.0-insiders x64 commit 7c62e560a2e494a1b0b4d39561dc5c1d837a5263
- OS Version: Windows 8.1 x64

After update to latest version window is empty (only main menu bar is visible).
Renderer process consumes 16-20% CPU but nothing is changing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-04-16 08:45
@kirusyaga can you run "`code --verbose`" from the command line and see if any output is printed?

**Comment by kirusyaga** [comment] 2018-04-16 08:57
@bpasero The output is here:

```
Error: Failed opening file C:\Users\%username%\AppData\Roaming\Code - Insiders\logs\20180416T115148\main.log for writing: No such file or directory
    at RotatingLogger (C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\spdlog\index.js:16:3)
    at Object.t.createSpdLogService (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:218:588)
    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:492:254
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:82:572)
    at Object.enter (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:85:924)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:87:719)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:87:160)
    at Server.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:161:996)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[main 11:51:48] Starting VS Code
[main 11:51:48] from: c:\Program Files\Microsoft VS Code Insiders\resources\app
[main 11:51:48] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false }
[main 11:51:48] Resolving machine identifier...
[main 11:51:48] Resolved machine identifier: 9731b3fdb2c4ff69a63f12589d5e6bfa83aafc07a1ac452f1fd5cd90f74d5cbb
[main 11:51:48] update#setState idle
[main 11:51:50] windowsService#whenSharedProcessReady
[main 11:52:18] update#checkForUpdates, state =  idle
[main 11:52:18] update#setState checking for updates
[main 11:52:18] RequestService#request https://vscode-update.azurewebsites.net/api/update/win32-x64/insider/7c62e560a2e494a1b0b4d39561dc5c1d837a5263
[main 11:52:20] update#setState downloading
[main 11:52:20] RequestService#request https://az764295.vo.msecnd.net/insider/dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b/VSCodeSetup-x64-1.23.0-insider.exe
```

**Comment by bpasero** [comment] 2018-04-16 09:17
adding @joaomoreno for the (maybe unrelated) spdylog stacktrace that shows up.

@kirusyaga can you share a screenshot how VSCode looks after it started like this?

**Comment by kirusyaga** [comment] 2018-04-16 12:58
@bpasero
---
![default](https://user-images.githubusercontent.com/22245072/38810283-fd1e1600-418e-11e8-9609-93cbf3ef7857.png)

**Comment by bpasero** [comment] 2018-04-17 04:46
@kirusyaga does it make any difference if you run with "`code --disable-gpu`" from the command line?

**Comment by joaomoreno** [comment] 2018-04-17 08:37
`Error: Failed opening file C:\Users\%username%\AppData\Roaming\Code - Insiders\logs\20180416T115148\main.log for writing: No such file or directory`

That `%username%` is weird. It looks like the user has a problem in one of his variables, possibly `HOMEPATH`.

@kirusyaga Whats the value of your HOMEPATH variable?

**Comment by kirusyaga** [comment] 2018-04-17 08:50
@bpasero Visually nothing is changed. In console also nothing.
@joaomoreno ```HOMEPATH``` is not presented. Username is ```kirusyaga```, but profile folder named as ```Александр```.

**Comment by bpasero** [comment] 2018-04-17 09:13
@kirusyaga does it make any difference if you run "`code-insiders --user-data-dir <some new/empty folder>`" from the command line?

**Comment by kirusyaga** [comment] 2018-04-17 16:35
@bpasero Yes. Window is opening like normal new profile. My profile is broken. Nice.
![default](https://user-images.githubusercontent.com/22245072/38883709-6b0ec8ac-4276-11e8-9cbb-1a0d0a2b0195.png)

**Comment by bpasero** [comment] 2018-04-18 05:17
> So, trouble is Cyrillic symbols in path to profile folder.

@kirusyaga to verify that can you use the `--user-data-dir` argument with a folder that has the Cyrillic characters and see if you get the same results?

**Comment by kirusyaga** [comment] 2018-04-18 12:57
@bpasero Yes. Launch with Cyrillic characters in path give same result.

[default](https://s26.postimg.cc/fana48v2h/2018-04-18_15-50-45.png)

**Comment by bpasero** [comment] 2018-04-18 14:58
@kirusyaga it would be easier for me to reproduce if you could post the exact Cyrillic letters that you are using in here as text so that I can copy it.

**Comment by kirusyaga** [comment] 2018-04-18 15:15
@bpasero Here it is: ```абырвалг```.

**Comment by bpasero** [comment] 2018-04-20 14:40
@joaomoreno I can reproduce and the reason the workbench is not coming up is due to spdylog crashing very early. To reproduce run "`code --user-data-dir C:\Users\<name>\ абырвалг`"

```
  ERR Failed opening file c:\Users\bpasero\Desktop\абырвалг\logs\20180420T163901\output_1_20180420T163909\tasks.log for writing: No such file or directory: Error: Failed opening file c:\Users\bpasero\Desktop\абырвалг\logs\20180420T163901\output_1_20180420T163909\tasks.log for writing: No such file or directory
    at new RotatingLogger (C:\GitDevelopment\monaco\node_modules\spdlog\index.js:16:3)
    at OutputChannelBackedByFile [as constructor] (file:///C:/GitDevelopment/monaco/out/vs/workbench/parts/output/electron-browser/outputServices.js:186:34)
    at create (file:///C:/GitDevelopment/monaco/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:106:35)
    at InstantiationService.createInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:67:29)
    at OutputService.instantiateChannel (file:///C:/GitDevelopment/monaco/out/vs/workbench/parts/output/electron-browser/outputServices.js:499:45)
    at OutputService.createChannel (file:///C:/GitDevelopment/monaco/out/vs/workbench/parts/output/electron-browser/outputServices.js:465:32)
    at OutputService.onDidRegisterChannel (file:///C:/GitDevelopment/monaco/out/vs/workbench/parts/output/electron-browser/outputServices.js:439:32)
    at OutputService [as constructor] (file:///C:/GitDevelopment/monaco/out/vs/workbench/parts/output/electron-browser/outputServices.js:391:23)
    at create (file:///C:/GitDevelopment/monaco/out/vs/base/common/types.js:164:14)
    at InstantiationService._createInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:106:35)
    at InstantiationService._createAndCacheServiceInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:163:41)
    at InstantiationService._getOrCreateServiceInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:111:29)
    at InstantiationService._createInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:78:36)
    at InstantiationService.createInstance (file:///C:/GitDevelopment/monaco/out/vs/platform/instantiation/common/instantiationService.js:67:29)
    at ActionBarRegistry.createActionBarContributor (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/actions.js:219:54)
    at ActionBarRegistry.setInstantiationService (file:///C:/GitDevelopment/monaco/out/vs/workbench/browser/actions.js:215:22)
    at Workbench.initServices (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/workbench.js:384:68)
    at Workbench.startup (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/workbench.js:95:18)
    at WorkbenchShell.createWorkbench (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/shell.js:58:27)
    at WorkbenchShell.createContents (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/shell.js:39:35)
    at WorkbenchShell.open (file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/shell.js:326:43)
    at file:///C:/GitDevelopment/monaco/out/vs/workbench/electron-browser/main.js:46:23
    at Object.notifySuccess [as _notify] (file:///C:/GitDevelopment/monaco/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///C:/GitDevelopment/monaco/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///C:/GitDevelopment/monaco/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///C:/GitDevelopment/monaco/out/vs/base/common/winjs.base.js:1051:18)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by joaomoreno** [comment] 2018-04-23 15:00
@bpasero Just to confirm, you could reproduce by using cyrilic in a path provided to `--user-data-dir`?

**Comment by bpasero** [comment] 2018-04-24 04:43
@joaomoreno yes

**Comment by siewers** [comment] 2018-04-25 08:08
I can confirm I have an identical problem. My username contains the character 'ø', which now makes the insiders build fail to start. Changing the `--user-data-dir` to a path which does not contain that character fixes the issue.
The stable release (1.22.2) works as expected.

**Comment by bpasero** [comment] 2018-04-26 12:43
I pushed a workaround for now to not crash so badly when we fail to instantiate the spdylog writer. Turns out we already had code in place to protect from failing loads thanks to Alex, but the output channel was failing very early on.

@sandy081 fyi maybe you want to quickly check my changes via https://github.com/Microsoft/vscode/commit/594b8b8debc41caed0fb9a07a2c43dff7ceef2fd

**Comment by sandy081** [comment] 2018-04-26 13:56
@bpasero This will break Output channels when not writing into file. When user switches between output channels, they will become empty as there is no way to retrieve content now

**Comment by sandy081** [comment] 2018-04-26 14:01
I was falling back to old way of writing into channels if `spdlog` fails. I removed this fallback this milestone 1e5c0c3e4e11af82e82d7761d7875646d1c6336b. You can get that back. But I would really want to remove this fallback because for further enhancements to output channel which depends on spdlog.

**Comment by bpasero** [comment] 2018-04-26 14:57
@sandy081 this is not a real fix, I would expect some regressions. Previously VS Code would not start at all without my workaround. Do you think the current behaviour with my fix is worse than before? I think its clear that we will work on a fix for May.

**Comment by sandy081** [comment] 2018-04-26 15:17
@bpasero IMO The better workaround would be to bring back my fallback 1e5c0c3e4e11af82e82d7761d7875646d1c6336b. I was doing the same as you except that I fallback to old way of writing into Output channels. This will not have any regressions as it was there in last milestone. 

When we fix it in May, we can remove the workaround.

**Comment by sandy081** [comment] 2018-04-26 15:58
@bpasero Pushed the previous workaround I was using. As said, this will not break output channels if there is an issue creating spdlog logger.

**Comment by joaomoreno** [comment] 2018-08-06 14:03
@sandy081 I don't see issues running dev with a user-data-dir containing a non-ascii character (eg `ø`) any more. I do not understand if this is because of your workaround or if the new spdlog version actually fixed the issue. Moving it to you in order to check if the issue is fixed already, since I don't understand how to repro.

**Comment by sandy081** [comment] 2018-08-27 09:53
I too do not see any issues after removing the workaround I added before for the crash.

Hence removed the workaround.

To verify:

- Open VS Code using an user directory that has non-ascii character (eg ø)
- Verify that VS Code starts normally and the output channels are properly written
- Verify that there is no crash

**Comment by sandy081** [comment] 2018-09-06 06:09
Reopening this as the crash from spdlog is not fixed.

**Comment by sandy081** [comment] 2018-09-06 06:19
@joaomoreno I still see following error in the console with our log files

```
Error: Failed opening file C:\Work\abcd├╕\logs\20180906T081642\main.log for writing: No such file or direc
    at new RotatingLogger (C:\Work\vscode\node_modules\spdlog\index.js:16:3)
    at Object.createSpdLogService (C:\Work\vscode\out\vs\platform\log\node\spdlogService.js:24:26)
    at C:\Work\vscode\out\vs\code\electron-main\main.js:301:59
    at Object.notifySuccess [as _notify] (C:\Work\vscode\out\vs\base\common\winjs.base.js:1191:59)
    at Object.enter (C:\Work\vscode\out\vs\base\common\winjs.base.js:867:30)
    at Promise_ctor._run (C:\Work\vscode\out\vs\base\common\winjs.base.js:1089:29)
    at Promise_ctor._completed (C:\Work\vscode\out\vs\base\common\winjs.base.js:1057:18)
    at Server.<anonymous> (C:\Work\vscode\out\vs\base\parts\ipc\node\ipc.net.js:228:17)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Closed** 2018-09-06 15:41 UTC
Labels: bug, debt, freeze-slow-crash, important, log, windows

**Comment by sandy081** [comment] 2018-09-06 15:56
Updated node-spdlog library to support `w_char` in file names. Thanks to @gnaggnoyil for hinting it.

With this crash no longer occurs with non ascii or special characters (tested with all reported characters). Added a smoke test to launch VS Code with special characters in user data dir.
