### ISSUE TITLE
Fix CSS formatting as you type, like WebStorm does, and like VSCode does for Javascript

### ISSUE THREAD

**Issue by stevensacks** [Microsoft/vscode#55559] opened 2018-08-01 06:14 UTC
Here's a trivial example of how WebStorm "just works" and VSCode doesn't.

![code_vs_webstorm](https://user-images.githubusercontent.com/162252/43504082-eb73dc2a-959c-11e8-8a46-62d641d8e7f7.gif)

I have tried numerous plugins and settings, but none of them mimic this behavior for (S)CSS.

If I use the format code command (CMD+SHIFT+F, I think?), VSCode removes all the line breaks between the imports and css classes, even though my scss-lint rule requires them, which means that command is completely usuable or it will destroy my formatting, not fix it.

VSCode does this for Javascript. Why not CSS? I know everyone's hot for CSS-in-JS right now, but come on. ;)

**Comment by aeschli** [comment] 2018-08-02 10:42
In essence, this is a request to provide a built-css formatter.
Marking as duplicate of #19166

**Closed by aeschli** 2018-08-02 10:42 UTC
