### ISSUE TITLE
No squiggles on empty lines

### ISSUE THREAD

**Issue by limerickgds** [Microsoft/vscode#14568] opened 2016-10-27 02:53 UTC
- VSCode Version:  1.6.1
- OS Version:  macOS 10.12

Steps to Reproduce:
1.   i edit a js file : 
![image](https://cloud.githubusercontent.com/assets/9961514/19752842/d58568a8-9c32-11e6-905f-4cb0a3faba99.png)

![image](https://cloud.githubusercontent.com/assets/9961514/19752865/f631c65a-9c32-11e6-8113-d94127e0a139.png)
1.   npm run lint

![image](https://cloud.githubusercontent.com/assets/9961514/19752343/1dce2662-9c2f-11e6-9cab-083aa12593cd.png)
1.  in second empty line, add a space, it displays an error。
   ![image](https://cloud.githubusercontent.com/assets/9961514/19752904/4413f3c0-9c33-11e6-8ef1-9eb7f8f9c733.png)

I would like to direct an error message, not need add space

**Comment by sandy081** [comment] 2016-10-27 10:02
@jrieken Any idea why squiggles are not shown until typing?

**Comment by jrieken** [comment] 2016-10-27 12:53
yeah - there is nothing to render them with, they are added in the void and unless you type there is nothing we can underline. I'd say this is by design unless @alexandrudima know a trick how to show squiggles without text?

**Comment by alexandrudima** [comment] 2016-10-27 13:00
When I first added the glyphMargin I'd show an exclamation mark in there for all errors / warnings :) Valid bug, it is a usability problem, not sure how to fix it...

**Comment by jrieken** [comment] 2016-10-27 15:29
yeah - you still see the warning indication in the scrollbar, the markers view, and the F8-feature.

**Comment by limerickgds** [comment] 2016-10-28 06:23
@jrieken This F8-feature is not real-time monitoring.it's ok, i can see warning  in the scrollbar.

**Comment by alexandrudima** [comment] 2017-05-11 10:20
Fixed via the fix for #26446 i.e. cdac53445d378bb5f116dbaef9026b103caef7f7

**Closed by alexandrudima** 2017-05-11 10:20 UTC
Labels: accessibility, bug, editor
