### ISSUE TITLE
Unexpected priority given to suggestion with interrupted substring

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#14861] opened 2016-11-02 16:43 UTC
I would expect that the first entry gets selected.

![image](https://cloud.githubusercontent.com/assets/5047891/19938034/d669a32e-a123-11e6-860d-058fe00e15b0.png)

**Comment by jrieken** [comment] 2016-11-03 09:51
Actually dupe of (already fixed https://github.com/Microsoft/vscode/issues/14660)

**Closed** 2016-11-03 09:53 UTC
Labels: bug, duplicate, suggest
