### ISSUE TITLE
Extension without displayName isn't shown in "Running Extension"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#63881] opened 2018-11-27 23:44 UTC
Start debugging an extension that doesn't have displayName set in its package.json - lots of the sample extensions don't have this.

Row is empty in the "Running Extensions" page:

![image](https://user-images.githubusercontent.com/323878/49118957-4813c100-f25b-11e8-9ddc-87be7508c255.png)

It should fall back to the extension name.

**Comment by alexandrudima** [comment] 2018-11-28 14:14
@roblourens I could not reproduce. I have removed `displayName` from our built-in `emmet` extension and I still see the UI falls back to the `name` property.

![image](https://user-images.githubusercontent.com/5047891/49157544-54ae1d00-f320-11e8-816c-9e38b2e9c59d.png)


Can you please share a `package.json` that reproduces?

**Comment by roblourens** [comment] 2018-11-28 17:46
Sure, I see this with the lsp-sample extension: https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/package.json#L3

This is on MacOS

**Comment by alexandrudima** [comment] 2018-12-06 11:56
@roblourens I still cannot reproduce. I am creating an extension with `package.json`:

```js
{
	"name": "lsp-sample",
	"description": "A language server example",
	"author": "Microsoft Corporation",
	"license": "MIT",
	"version": "1.0.0",
	"repository": {
		"type": "git",
		"url": "https://github.com/Microsoft/vscode-extension-samples"
	},
	"publisher": "vscode-samples",
	"categories": [],
	"keywords": [
		"multi-root ready"
	],
	"engines": {
		"vscode": "^1.23.0"
	},
	"activationEvents": [
		"onLanguage:plaintext"
	],
	"main": "./extension"
}
```

This gets rendered in the running extensions editor with the name `lsp-sample`:

![image](https://user-images.githubusercontent.com/5047891/49582770-5d24da00-f956-11e8-82a1-930dc1a65308.png)

**Comment by roblourens** [comment] 2018-12-06 19:21
I can still repro, I tried on Windows and Mac. Just tell me where to set a breakpoint... 😁

**Comment by alexandrudima** [comment] 2018-12-07 08:39
Ok, there is one thing I was doing different... I was not pressing `F5`, but rather simply loading the extension. I can reproduce only when debugging the extension!

**Comment by roblourens** [comment] 2018-12-07 19:17
Oh, didn't realize it would be different debugging vs not

**Comment by isidorn** [comment] 2019-03-14 15:52
I do not plan to fix this.
Unassigning myself. I would just close this but leaving up to you two.

**Closed** 2019-10-11 13:34 UTC
Labels: *out-of-scope, bug
