### ISSUE TITLE
Right Click on Extension Search > Peek causes freeze

### ISSUE THREAD

**Issue by topherhoffman** [microsoft/vscode#104727] opened 2020-08-15 19:16 UTC
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.19041
![image](https://user-images.githubusercontent.com/11143721/90319700-755d4280-df08-11ea-8f5d-8cc39fc97157.png)

Steps to Reproduce:
![VSCODE Freeze 2020](https://user-images.githubusercontent.com/11143721/90319821-d0436980-df09-11ea-867e-fcd13d6ffbd7.gif)

1. Right Click 'Search Extension in Marketplace'
2. Goto Peek, **click on peek** (Before the Peak menu shows) [Edit 2020/08/18: added context]
3. Repeat 2&3 Until freeze (Might Take a couple of times.)
4. Wait for the Freeze Notice

![image](https://user-images.githubusercontent.com/11143721/90319805-a1c58e80-df09-11ea-901f-8d9e4dde939c.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes, Still happens
![image](https://user-images.githubusercontent.com/11143721/90319987-1ea53800-df0b-11ea-9007-0078633c78a1.png)

**Comment by heartacker** [comment] 2020-08-15 23:25
I have the same problem

**Comment by sandy081** [comment] 2020-08-17 12:04
This is also there in settings editor

<img width="898" alt="image" src="https://user-images.githubusercontent.com/10746682/90394188-7c17c100-e092-11ea-8809-1535ac558594.png">

Assigning to @roblourens since this is a bug in Suggest enabled input.

**Comment by roblourens** [comment] 2020-08-18 00:40
I'm not sure about the freeze, I don't repro that. But @jrieken can you just make sure that peek command won't show up in the simple editor input? I changed the Command Palette one to have `when: EditorContextKeys.editorSimpleInput.toNegated()`. You can add that or it looks like other peek menu registrations have some conditions on when they are valid.

**Comment by jrieken** [comment] 2020-08-18 07:18
Hm, this must be a regression from @joaomoreno's submenu changes as the Peek-menu is quite old already. Will look into a fix, also marking as candidate

**Comment by jrieken** [comment] 2020-08-18 10:22
I have pushed a change so that the sub menu doesn't show anymore. Tho, I cannot reproduce the freeze. Not on mac nor on windows. I wonder if that's related to the welcome page not showing recent entries... Can you try without the welcome page or with a different workspace?

**Comment by jrieken** [comment] 2020-08-18 12:31
Adding @sbatten for more insights and FYI. You might know more about the crash potential - it seems that sometimes the Peek menu doesn't expand and than the crash happens. In my testing (win/mac) I wasn't able to repro and got the menu with a single, disabled entry

**Comment by topherhoffman** [comment] 2020-08-19 00:56
@jrieken That is the cause,  You need to left click, then right click, don't wait for the peak to show.  I just realized that was the exact step to reproduce the error.

**Comment by topherhoffman** [comment] 2020-08-19 01:53
Yep, It doesn't have to be from the search bar, it can be anywhere.
![VSCODE 3](https://user-images.githubusercontent.com/11143721/90583008-2845ce80-e19d-11ea-937b-bda29b58d627.gif)

Not sure if this is it, but seems to be it.


from https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/peekView/peekView.ts
```
protected _onTitleClick(event: IMouseEvent): void {
		// implement me
	}
```

**Comment by jrieken** [comment] 2020-08-19 07:07
Thanks @topherhoffman 👏 Once I am fast enough I can reproduce. There is an endless loop creating the submenu and trying to [focus](https://github.com/microsoft/vscode/blob/ae040391de70b2f223c4662d62c3702fe336ddfe/src/vs/base/browser/ui/actionbar/actionbar.ts#L371-L379) an item. Not quite sure why this only happens when being fast...

**Comment by jrieken** [comment] 2020-08-19 07:13
I believe this was introduced via https://github.com/microsoft/vscode/commit/182db07de2745fe3a6369f4ad80ae930e006a99b because it adds the `preventLoopNavigation` which weakens the only loop abort condition. That you have to be fast is because 250ms after hovering an element is focused (via a different code path) and you need to click fast than that.

**Comment by jrieken** [comment] 2020-08-19 12:52
I have cherry-picked my commit fa4ee50 onto the release branch which should make this not happen anymore - tho the underlying issue and the potential for this endless loop remains

**Comment by isidorn** [comment] 2020-08-19 14:46
Thanks for cherry picking. Due to that closing this issue so we get it verified for the release.
As for the underlying issue and endless loop potential I suggest that either you or @sbatten create a new issue.

**Closed by isidorn** 2020-08-19 14:46 UTC
Labels: bug, candidate, freeze-slow-crash-leak, menus

**Comment by jrieken** [comment] 2020-08-20 08:28
To verify:

* open extensions viewlet (alternatively SCM or settings editor)
* right click into the editor/input
* make sure that there is no peek menu
