### ISSUE TITLE
New WSL Window shortcut in Windows' Jump List

### ISSUE THREAD

**Issue by pdrgnclvs** [microsoft/vscode#141934] opened 2022-02-01 10:35 UTC
Hey everyone, just wanted to share an idea with all of you 😉

In my opinion, I think adding a New WSL Window shortcut in Windows' Jump List feature would be a nice productivity touch, since we could instantly open a VS Code window directly connected to WSL...

![image](https://user-images.githubusercontent.com/46295920/151952824-329458e7-9c0a-429f-bda7-4e9b654a3ec0.png)

...instead of opening a normal VS Code window, then opening a WSL-connected window and finally closing the first one as this process basically creates two VS Code windows 🤔

Even though the New WSL Window option is tied to an extension, I think it could be really useful to have this shortcut 😃

Happy coding and have a great day 👍

**Comment by aeschli** [comment] 2022-02-03 13:04
duplicate of https://github.com/microsoft/vscode/issues/76535

**Closed by aeschli** 2022-02-03 13:04 UTC
