### ISSUE TITLE
"All exceptions" and skipFiles

### ISSUE THREAD

**Issue by xeor** [microsoft/vscode#72481] opened 2019-04-17 09:06 UTC
- VSCode Version: 1.3.3.0
- OS Version: Windows 10
- debugger: Chrome

Steps to Reproduce:

1. Use a debugger and enable exception on `All Exceptions`
2. Put the file inside `skipFiles` so it should be excluded
3. Start debugger, and make sure app thows an exception.
4. Exception is still there, even tho all files included in call stack is excluded.

I'm not able to upload a screenshot, but the callstack bar shows no entries, only a text that say: `Show 20 More: (skipped by 'skipFiles')`

**Comment by roblourens** [comment] 2019-10-07 18:34
Duplicate of https://github.com/microsoft/vscode/issues/33566

**Closed** 2019-10-07 18:34 UTC
Labels: *out-of-scope, debug
