### ISSUE TITLE
disable autocomplete in .txt files

### ISSUE THREAD

**Issue by dmahugh** [Microsoft/vscode#3137] opened 2016-02-18 20:58 UTC
The code completion functionality often gets in the way when typing prose into a text file. For example, if I were writing this comment in a .txt file with VS Code and tried to type the word fun immediately followed by the Enter key, I'd automatically have the word "functionality" instead, because Code "learned" from the first sentence above that "fun" might be the beginning of "functionality."

It's great that this is apparently turned off by default in Markdown files. Can the same default be applied to .txt files? It's unlikely that any useful word-completion heuristic can be deduced from the content of most text files.

**Comment by jrieken** [comment] 2016-03-07 11:35
duplicate of #2496

**Closed by jrieken** 2016-03-07 11:35 UTC
Labels: feature-request
