### ISSUE TITLE
Flickering menus

### ISSUE THREAD

**Issue by fornellas** [microsoft/vscode#97276] opened 2020-05-08 16:37 UTC
- VSCode Version: 1.45.0
- OS Version: Linux Mint 19.3 Tricia

Steps to Reproduce:

1. Open VSCode
2. Click the menus

This video better shows the issue: https://photos.app.goo.gl/R6cs3EdQqihjfqwR7.

Does this issue occur when all extensions are disabled?: Not sure, but it happens on a fresh install.

**Comment by Tyriar** [comment] 2020-05-09 13:02
The video doesn't play for me, looks like it's about the custom title bar though. You could try launch with --disable-gpu to see if that fixes it.

**Comment by Tyriar** [comment] 2020-05-09 13:03
Might be https://github.com/microsoft/vscode/issues/97270?

**Comment by fornellas** [comment] 2020-05-09 15:59
@Tyriar from the description, it seems the same as #97270 . There's a comment there about a fix potentially being ready.

Google Photos sometimes takes a bit to load the video, please try again. It worked fine for me now on a incognito window.

**Comment by deepak1556** [comment] 2020-05-09 23:20
@fornellas can you check if the issue is fixed with the exploration build https://az764295.vo.msecnd.net/exploration/7faa10cfc640a15751049cdc6e894c5d146ff7dd/code-exploration-1588920827.tar.gz ? Thanks!

**Comment by fornellas** [comment] 2020-05-10 09:49
@deepak1556 downloading and running binaries from domains unrelated to this project seems... fishy. Can you please point me to the source? Perhaps I can build it myself.

PS: `--disable-gpu` does not fix the issue.

**Comment by Tyriar** [comment] 2020-05-10 12:57
@fornellas that's our release server where all automatic and manually downloaded updates are served from.

**Comment by fornellas** [comment] 2020-05-10 19:42
@deepak1556 confirmed your exploration build fixes the issue. FYI, it can be repro at VirtualBox + fresh Ubuntu as well.

This issue is more noticeable with dark themes, but it is still fairly noticeable with white themes. It seems the root cause is that drawing a simple drop down menu is taking a **humongous** amount of time, during which, the area is white.

My machine runs Chrome just fine ("same" engine, isn't it?) with no performance issues. I'm curious how come VSCode struggles so much to draw such a simple UI element.

**Comment by deepak1556** [comment] 2020-05-10 23:02
Thanks for testing, VSCode is not responsible for drawing the menus, the issue stems from electron and it is being tracked under https://github.com/electron/electron/issues/18184 

> confirmed your exploration build fixes the issue. FYI, it can be repro at VirtualBox + fresh Ubuntu as well.

However, I am able to repro the issue with exploration build on my parallels vm. I haven't investigated this issue further.

You can workaround with `"window.titleBarStyle": "custom"` for now, the runtime in exploration build will be pushed to insiders soon. I am merging this to https://github.com/microsoft/vscode/issues/80798

**Closed by deepak1556** 2020-05-10 23:02 UTC
Labels: needs more info, new release
