### ISSUE TITLE
Delay after task process exits when Conpty is enabled

### ISSUE THREAD

**Issue by jingyu9575** [microsoft/vscode#189888] opened 2023-08-08 02:39 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.0-insider (39e5dafcd66adab6f2d2ba65f6d6bde5eeb3767e, 2023-08-07T18:31:10.893Z)
- OS Version: Windows 11 x64 10.0.22621

Steps to Reproduce:

1. Open an empty folder and trust it.
2. Configure a minimal task: (problemMatcher and group are just for convenience)
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "process",
            "command": "cmd",
            "args": [
                "/c",
                "echo OK"
            ],
            "problemMatcher": [],
            "group": "build",
        }
    ]
}
```
3. Ctrl+Shift+B to run the task.
4. The terminal shows `OK` then `Terminal will be reused by tasks`, but with ~1s delay between them.
5. Disable *Terminal › Integrated: Windows Enable Conpty* in setttings.
6. Run the task again. The delay becomes smaller.

The problem is with Conpty enabled (the default), there is a long delay after the process exits. If the task is a prelaunch task for debugging, it makes debugging start slow even if the build process is very fast.

Additional information:
Terminal log output with Conpty on:
```
2023-08-08 09:53:18.264 [trace] [47b29c7] Relaunching terminal instance 1 []
2023-08-08 09:53:18.341 [debug] [47b29c7] Terminal process ready (shellProcessId: 4008) []
2023-08-08 09:53:18.357 [debug] [47b29c7] parsing data "[6n" [[27,91,54,110]]
2023-08-08 09:53:18.358 [debug] [47b29c7] sending data "[13;1R" [[27,91,49,51,59,49,82]]
2023-08-08 09:53:18.360 [info] [47b29c7] Latency measurements for local backend
window<->ptyhost (message port): 1.30ms
window<->ptyhostservice<->ptyhost: 2.10ms
ptyhostservice<->ptyhost: 1.13ms []
2023-08-08 09:53:18.380 [debug] [47b29c7] parsing data "[m]0;C:\Windows\system32\cmd.exe[?25hOK
" [[27,91,109,27,93,48,59,67,58,92,87,105,110,100,111,119,115,92,115,121,115,116,101,109,51,50,92,99,109,100,46,101,120,101,7,27,91,63,50,53,104,79,75,13]]
2023-08-08 09:53:18.406 [debug] [47b29c7] parsing data "
" [[10]]
2023-08-08 09:53:19.672 [debug] [47b29c7] Terminal process exit ["instanceId",1,"code",0,"processState",6]
2023-08-08 09:53:19.677 [debug] [47b29c7] parsing data "[0m[7m * [0m ]633;D;0Terminal will be reused by tasks, press any key to close it. [0m
```
There is an ~1.3 seconds delay before `Terminal process exit`.

With Conpty off, the delay is ~0.3s:
```
2023-08-08 10:28:34.254 [trace] [47b29c7] Relaunching terminal instance 1 []
2023-08-08 10:28:34.361 [debug] [47b29c7] Terminal process ready (shellProcessId: 5532) []
2023-08-08 10:28:34.391 [info] [47b29c7] Latency measurements for local backend
window<->ptyhost (message port): 0.90ms
window<->ptyhostservice<->ptyhost: 2.20ms
ptyhostservice<->ptyhost: 1.08ms []
2023-08-08 10:28:34.437 [debug] [47b29c7] parsing data "[0m[0K" [[27,91,48,109,27,91,48,75]]
2023-08-08 10:28:34.453 [debug] [47b29c7] parsing data "OK[0K[?25l
[0K[?25h" [[79,75,27,91,48,75,27,91,63,50,53,108,13,10,27,91,48,75,27,91,63,50,53,104]]
2023-08-08 10:28:34.772 [debug] [47b29c7] Terminal process exit ["instanceId",1,"code",0,"processState",6]
2023-08-08 10:28:34.777 [debug] [47b29c7] parsing data "[0m[7m * [0m ]633;D;0Terminal will be reused by tasks, press any key to close it. [0m
```

**Comment by meganrogge** [comment] 2023-10-18 20:13
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-10-18 20:13 UTC
Labels: tasks, terminal-conpty, confirmation-pending
