### ISSUE TITLE
Variable type not used for IntelliSense of object literal when type is declared in comment

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#24285] opened 2017-04-07 23:33 UTC
- VSCode Version: 1.11.1

Test tour #23385

When declared in TypeScript this work, in JavaScript comments it doesn't:

<img width="530" alt="screen shot 2017-04-07 at 4 21 25 pm" src="https://cloud.githubusercontent.com/assets/9205389/24823048/3f6772f6-1baf-11e7-8ef3-599c83f0e4b0.png">

The variable has that type and it is used when accessing it:
<img width="527" alt="screen shot 2017-04-07 at 4 21 44 pm" src="https://cloud.githubusercontent.com/assets/9205389/24823058/4bb8866c-1baf-11e7-91c3-a9cff6fb46d8.png">

The source:
```js
var Vue = require('vue');

/** @type {vuejs.ComponentOption} */
var opt = {

};
opt.
```

/cc @roblourens

**Comment by mjbvz** [comment] 2017-04-12 01:00
The issue is unclear to me. Is it that when triggering suggestions inside of the `opts` object, you don't see any helpful suggestions for the type, but for `opts.|` you do?

I'm able to get either case working properly. Do I need to install the vue extension?

**Comment by chrmarti** [comment] 2017-04-12 14:45
I can reproduce it with extensions disabled and an otherwise empty folder.

**Comment by mjbvz** [comment] 2017-04-12 22:31
A few TS bugs around this:

* Old `@types/vue` from ATA being picked up: https://github.com/Microsoft/TypeScript/issues/15164
* No suggestions inside of object literal: https://github.com/Microsoft/TypeScript/issues/7158
* `require` types not working with jsdocs: https://github.com/Microsoft/TypeScript/issues/14056

Closing as upstream

**Closed by mjbvz** 2017-04-12 22:31 UTC
Labels: bug, needs more info, upstream

**Comment by chrmarti** [comment] 2017-04-12 23:17
Thanks @mjbvz !
