### ISSUE TITLE
renaming a file, loosing the history

### ISSUE THREAD

**Issue by sirber** [Microsoft/vscode#73227] opened 2019-05-03 12:12 UTC
Issue Type: <b>Bug</b>

if I rename a file, the ctrl+z history gets lost

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (8.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.14
todo-tree|Gru|0.0.130
vscode-sshfs|Kel|1.16.2
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2

</details>

**Comment by RMacfarlane** [comment] 2019-05-03 17:12
Duplicate of https://github.com/Microsoft/vscode/issues/17977. Thanks!

**Closed by RMacfarlane** 2019-05-03 17:12 UTC
