### ISSUE TITLE
Weird font articfacts between chars

### ISSUE THREAD

**Issue by gerroon** [Microsoft/vscode#45451] opened 2018-03-10 00:59 UTC
#
![selection_010](https://user-images.githubusercontent.com/8519469/37236334-0dce1eea-23cc-11e8-82fa-2987e0f9f4d6.jpg)
Hi

I am trying to use VS Code on Debian Testing X64. I installed it using the deb.

Please see the attached image for the issue. These artifacts are all over the interface and the Python file I was using. I changed the  editor font to Liberation Mono which seemed to help a bit but did not solve the issue fully.

The vertical line you see is not the cursor btw.

The interface has these all over, but I cant get a screenshot, the menus just go away when I try to take one with Shutter.

I have Droid sans fallback install via the Debian repository.

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

thanks

**Comment by tweakimp** [comment] 2018-03-10 06:08
Have you tried changing the theme?

**Comment by bpasero** [comment] 2018-03-10 09:36
@gerroon can you try to reproduce this from this build: https://az764295.vo.msecnd.net/insider/206928db3cd5b76a80847d55ec5c5abb9e3c0ac0/code-insider-1.22.0-1520613043_amd64.tar.gz

**Comment by gerroon** [comment] 2018-03-10 17:06
@bpasero 

Thanks for the follow up. That build seems to resolve the font renderin in the menus and the editor area.

**Comment by bpasero** [comment] 2018-03-11 05:26
@gerroon awesome, this build contains https://github.com/electron/libchromiumcontent/pull/387 which seems to help.

**Comment by bpasero** [comment] 2018-03-16 06:20
Duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by bpasero** 2018-03-16 06:20 UTC
Labels: font-rendering, linux
