### ISSUE TITLE
TypeScript Syntax Highlighting Issues

### ISSUE THREAD

**Issue by haugerbr** [microsoft/vscode#81708] opened 2019-10-01 07:39 UTC
Issue Type: <b>Bug</b>

I'm seeing two syntax highlighting issues with TypeScript in VSCode

1. Observed: An interface property is colored differently when followed by a lambda function. Expected: It matches the color of all other properties in the interface i.e. purple in this case.
2. Observed: The parenthesis within a template string match string coloring instead of the expression coloring when used inside placeholder syntax i.e. ${ }. Expected: The parenthesis match the same color as the placeholder syntax i.e. grey in this case. 

Code:
```
interface test {
    a: () => void;
    b: string;
}
const a = `${(1 + 1)}`;
```
Image:
![image](https://user-images.githubusercontent.com/660975/65942063-571a5100-e3e1-11e9-8bcf-c77e688eeaaf.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (13.61GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by usernamehw** [comment] 2019-10-01 08:30
Duplicate of #29866

**Comment by usernamehw** [comment] 2019-10-01 09:18
You shouldn't put multiple issues into one, yes?

**Comment by mjbvz** [comment] 2019-10-01 17:53
Please share the text of the code along with screenshots

What is the expected behavior in the first case?

**Comment by haugerbr** [comment] 2019-10-01 18:31
@mjbvz Added the code and made it more explicit in the description what I was expecting.

**Comment by usernamehw** [comment] 2019-10-01 18:48
This property has `entity.name.function` scope (which it is). You can overwrite it with the scope like `meta.field.declaration.ts entity.name.function.ts` in `editor.tokenColorCustomizations`.

Use this command to find scopes: **Developer: Inspect TM Scopes**.

**Comment by haugerbr** [comment] 2019-10-01 19:40
@usernamehw that may be a workaround but I don't think that is the solution to this issue. The field itself should not be marked as a name of a function. It is a type annotation that is being treated as a function declaration from what I can tell looking at the scope.

I also find it interesting that it is properly labeled/colorized when hovering over the property. 
![image](https://user-images.githubusercontent.com/660975/65994570-8021fc80-e448-11e9-8cd1-808aa4516075.png)

**Comment by mjbvz** [comment] 2019-10-01 23:35
The current highlighting is intentional. For the code:

```ts
interface test {
    a: () => void;
    b: string;
    c(): void;
}
```

With the current grammar most themes will highlight `a` and `c` the same way.

<img width="257" alt="Screen Shot 2019-10-01 at 4 33 04 PM" src="https://user-images.githubusercontent.com/12821956/66007993-6ba22c00-e469-11e9-8931-f5ba464aad6b.png">

The grammar itself comes from [this repo](https://github.com/microsoft/TypeScript-TmLanguage) if you would like to provide feedback on this

**Closed by mjbvz** 2019-10-01 23:35 UTC
Labels: needs more info
