### ISSUE TITLE
Call Stack: Collapse All Threads

### ISSUE THREAD

**Issue by dirkseidel** [microsoft/vscode#77799] opened 2019-07-23 07:25 UTC
Working with a lot of threads (250+) in a c++ project, during a debug session many breakpoints are hit in different threads. Each time a breakpoint is hit the corresponding stack trace for the thread is obtained and the thread is expanded in the stack view. After hitting bps in different threads, more and more threads are expanded and the corresponding stack traces are uselessly obtained, which is a performance issue.
The only way around this seems to be to scroll through all threads and collapse them one by one (which is very tedious) so that at the next breakpoint the stack traces are not obtained any more.

It would be very helpful to have the possibility to collapse all threads at once in the call stack view.

**Comment by weinand** [comment] 2019-07-23 08:27
Why is this a performance "regression". Was the behavior different in previous versions of VS Code?

**Comment by dirkseidel** [comment] 2019-07-23 09:06
Sorry, of course not a "regression". Previous versions were behaving the same way.

**Comment by isidorn** [comment] 2019-07-29 13:15
This is a fair feautre request. Collapse All in the callstack view. Thus renaming and assigning to backlog.

**Comment by isidorn** [comment] 2019-10-17 15:20
Actually does not make a lot of sense, since that area in the call stack is already occupied by the state label. Thus the place is not empty. Due to that closing as out of scope

**Closed** 2019-10-17 15:20 UTC
Labels: *out-of-scope, debug, feature-request

**Comment by dirkseidel** [comment] 2019-10-17 16:00
Hi Isidorn,
in the variables/watch sections there are "collapse all" buttons at the top right. Why does it not make sense to include this in the call stack? This is exactly what would be needed here...

**Comment by isidorn** [comment] 2019-10-17 18:38
You are right.
I have pushed a change such that when only one session and thread are being debugged we do not show the collapse all action.
However if you are in multi threaded / multi session mode we will show the collapse action (reason being that then we show the state label inline and there is space for an action).

To verify: start a multi threaded / or two debug sessions and make sure the collapse all action is in the call sttack ttitle and that clicking on it you can collapse all the elements
