### ISSUE TITLE
Font rendering degradation | High Contrast Issue after 1.39.2 [macOS Mojave]

### ISSUE THREAD

**Issue by solesensei** [microsoft/vscode#88847] opened 2020-01-17 13:44 UTC
Continue of #84261
I'm still on 1.39.2 VSCode since october 2019.

On 1.39.2
![image](https://user-images.githubusercontent.com/24857057/72616551-4833bc00-3948-11ea-9294-3d81982d3a57.png)
After 1.39.2
![image](https://user-images.githubusercontent.com/24857057/72616561-4c5fd980-3948-11ea-8f2b-9aced4d13b70.png)

Can't fix it with any suggested methods

Checked latest versiong of VSCode and VSCode Insiders - same results.

**Comment by solesensei** [comment] 2020-01-17 13:49
Not working for me #84154

**Comment by solesensei** [comment] 2020-01-17 13:50
Connect to #88847

**Comment by alexdima** [comment] 2020-01-20 14:37
@solesensei What OS do you use?

**Comment by solesensei** [comment] 2020-01-22 20:15
@alexdima macOS Mojave 10.14.6

**Comment by alexdima** [comment] 2020-01-23 09:36
@bpasero @deepak1556 From what I can tell, this issue really looks like a duplicate of https://github.com/microsoft/vscode/issues/84154

@bpasero What is the outcome of #84154 ? Users need to create a file for the argv with `disable-color-correct-rendering` ?

**Comment by bpasero** [comment] 2020-01-23 09:51
@alexdima we set `disable-color-correct-rendering` by default, the user does not have to configure anything. However the user may optionally decide to disable this flag via the runtime flags.

@solesensei what is the contents when you run 
![image](https://user-images.githubusercontent.com/900690/72973889-59f4e380-3dce-11ea-84a5-f5773829f379.png)

?

**Comment by solesensei** [comment] 2020-01-24 14:20
@bpasero 

```json
{
	"disable-color-correct-rendering": true 
}

```

**Comment by bpasero** [comment] 2020-01-24 15:15
That looks good to me. Does it help if you run `code-insiders --force-color-profile srgb`

**Comment by solesensei** [comment] 2020-01-27 16:04
@bpasero Done, also set `"disable-color-correct-rendering": true `
```bash
~$ code-insiders --force-color-profile srgb
Warning: 'force-color-profile' is not in the list of known options, but still passed to Electron/Chromium.
```
![image](https://user-images.githubusercontent.com/24857057/73190931-c1e15c00-4137-11ea-95d7-eaf38ade18ea.png)

![image](https://user-images.githubusercontent.com/24857057/73190731-7b8bfd00-4137-11ea-95b7-8f210f389e5e.png)

**Comment by bpasero** [comment] 2020-01-27 16:13
@solesensei so to be clear, you see no improvement?

**Comment by solesensei** [comment] 2020-01-27 16:20
> @solesensei so to be clear, you see no improvement?

`code-insiders "disable-color-correct-rendering": true`
![image](https://user-images.githubusercontent.com/24857057/73192055-91022680-4139-11ea-90c6-5ba39daffea9.png)
`code-insiders --force-color-profile srgb "disable-color-correct-rendering": true`
![image](https://user-images.githubusercontent.com/24857057/73192090-9cede880-4139-11ea-867e-e86ac417fd27.png)
`"disable-color-correct-rendering": false`
![image](https://user-images.githubusercontent.com/24857057/73192184-b8f18a00-4139-11ea-945f-1e6ea5cbbc77.png)
`code 1.39`
![image](https://user-images.githubusercontent.com/24857057/73192387-01a94300-413a-11ea-877c-e4b17dd9dcdc.png)

For me no difference switching `disable-color-correct-rendering`

**Comment by bpasero** [comment] 2020-01-27 16:32
@solesensei so to be clear, you see no improvement?

**Comment by solesensei** [comment] 2020-01-27 18:07
@bpasero yes, i don't see any improvement

**Comment by solesensei** [comment] 2020-01-30 10:36
> @MariuzM
> We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
> * Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
> * Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
> * Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)


![image](https://user-images.githubusercontent.com/24857057/73441884-cccd0400-4364-11ea-8e89-98301417a42e.png)
![image](https://user-images.githubusercontent.com/24857057/73441926-e66e4b80-4364-11ea-8bac-3ec91a170c6f.png)
![image](https://user-images.githubusercontent.com/24857057/73441953-f25a0d80-4364-11ea-933f-8ccd53ecee1c.png)

Tried to use the Electron 7 Exploration build. It's a little better

**Comment by solesensei** [comment] 2020-01-30 14:33
I fixed the issue

**Comment by MariuzM** [comment] 2020-01-30 14:45
I see no diff between exploration and 1.41.1 
1.41.1
<img width="1440" alt="argv false - 1 41 1" src="https://user-images.githubusercontent.com/36937039/73459620-1a4e6e80-436f-11ea-8b22-47436b96e878.png">

1.41.0 Exp
<img width="1440" alt="argv false - 1 41 0 Exp" src="https://user-images.githubusercontent.com/36937039/73459654-25a19a00-436f-11ea-8afc-b285fbb595c6.png">

**Comment by deepak1556** [comment] 2020-01-30 21:15
Thanks @solesensei 

@bpasero based on https://github.com/microsoft/vscode/issues/88847#issuecomment-580280709 it seems to an issue of font smoothing and not related to color profile. We have the fixes in electron for font smoothing on mojave, as @solesensei removed the workarounds to get the right behavior. We can close this issue as no further action needs to be taken on vscode end.

/duplicate https://github.com/microsoft/vscode/issues/59887

@MariuzM please open a new issue with the issue you are facing, the expected behavior and the fixes you have tried. Thanks!

**Closed** 2020-01-30 21:15 UTC
Labels: *duplicate, electron-6-update, mac, needs more info
