### ISSUE TITLE
'await' not shown in suggestion list when type letter 'a' in a .js file or .ts file

### ISSUE THREAD

**Issue by dogzhang** [Microsoft/vscode#61323] opened 2018-10-19 14:26 UTC
type letter 'a', the keyword 'await' will not be shown in suggestion list. the problem appeard since this version 1.28.2.
the keyword 'await' is the first item in suggestion list at the version 1.27.2, and this is what i expected.

**Comment by mjbvz** [comment] 2018-10-22 21:46
Duplicate of Microsoft/vscode#60133 / https://github.com/Microsoft/TypeScript/issues/27622

**Closed by mjbvz** 2018-10-22 21:46 UTC
Labels: javascript
