### ISSUE TITLE
Emmet expansions failing when certain lines of PHP are present in file

### ISSUE THREAD

**Issue by benjibee** [microsoft/vscode#129529] opened 2021-07-27 13:01 UTC
## Description

A PHP file containing the below lines of code (written as such) causes Emmet expansions for HTML elements to fail anywhere in the document.  I'm aware that the code is not well-written PHP and enclosing the evaluation of the `$i` variable in brackets re-enabled Emmet expansions.

### Code Snippet
```php
<?php for ($i=0; $i<3; $i++): $variable = $i < 2 ? true : false; ?>

<?php endfor;
```
### Error Message
"Command 'Emmet: Expand Abbreviation' resulted in an error (Running the contributed command: 'emmet.expandAbbreviation' failed.)"

## Info

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2 (Universal) / Version: 1.59.0-insider (Universal)
- OS Version: macOS 11.4 (20F71)

### Steps to Reproduce:

1. Open a new editor window.
2. Paste the above lines of PHP code into the editor window.
3. Attempt to expand any HTML element using either `tab` or running `Emmet: Expand Abbreviation` from the command palate.

**Comment by rzhao271** [comment] 2024-12-11 19:03
Duplicate of https://github.com/microsoft/vscode/issues/98357

**Closed by rzhao271** 2024-12-11 19:03 UTC
Labels: php, emmet, under-discussion, emmet-parse
