### ISSUE TITLE
Global git commands don't show errors

### ISSUE THREAD

**Issue by ronaldruzicka** [Microsoft/vscode#41519] opened 2018-01-12 08:34 UTC
Hi 👋,

Would it be possible to have notifications of successful/unsuccessful `git push`, `git pull`, etc?

It happens sometimes that `git push` or `git pull` is unsuccessful and I don't even know about it and don't even know what went wrong. There is just the small arrow in the bottom left of the screen that indicate pending `push`, but it's really easy to miss.

Thanks!

**Comment by joaomoreno** [comment] 2018-01-12 08:40
An unsuccessful push or pull should report an error message for sure. How do you run the actions themselves?

**Comment by ronaldruzicka** [comment] 2018-01-12 08:53
I'm using the integrated Git by VS Code from Command palette. If I use the terminal I see an error there, but I got used to the Command palette, it's faster.

<img width="597" alt="screen shot 2018-01-12 at 09 52 27" src="https://user-images.githubusercontent.com/20684387/34866871-5c6b3fee-f77e-11e7-8050-7c7502e683d5.png">

**Comment by lohxx** [comment] 2018-01-15 03:24
Thats is a great idea

**Comment by ronaldruzicka** [comment] 2018-04-13 15:09
Hi @joaomoreno, please are there any news about this issue? I see that even after the changes in notifications it still ignores Git actions.

**Comment by joaomoreno** [comment] 2018-04-16 08:33
I've added a couple tags, let's see if someone picks it up.

**Comment by chenhowa** [comment] 2018-04-22 05:49
@joaomoreno I'd like to pick this up as a first issue if possible.

@ronaldruzicka Is there a simple way to reproduce the issue of a push/pull failing without notification? It seems very simple to add a notification if the push did not throw any errors. But I'm not very experienced with git, so I haven't found a way to make push/pull fail silently -- for the "common" cases I've tried, I get an error message dialog.

**Comment by chenhowa** [comment] 2018-04-22 05:57
@joaomoreno Do you know where the cause of the silent errors might be? I don't know if there are cases where git.push/pull doesn't throw an error even though it should. It seems like the calling code is already set up to catch errors thrown by git.push/pull, and show a dialog displaying the error.

**Comment by ronaldruzicka** [comment] 2018-04-22 20:17
@chenhowa Well the most common case is, when you try to `push` something into `remote` but you have to `pull` changes first. When I use the integrated VS Code git, I don't get a notification, that my changes haven't been `push`ed and that I need to `pull` changes first. I just see on the bottom left that the `push` is still pending like this <img width="71" alt="screen shot 2018-04-22 at 22 04 33" src="https://user-images.githubusercontent.com/20684387/39099363-3b44a5da-467a-11e8-9121-f74d71e0299a.png">, although on this screenshot I don't have any remote changes to be pulled, but you know what I mean.

It would be nice to be notified that the `push`, or other actions, failed and why, like when you do it from the console.

**Comment by chenhowa** [comment] 2018-04-27 05:15
I'm not sure if this is your use case, but what I've found is that from Command Palette, Git: Push and Git: Pull will always warn you when they fail. However, Git: Push To and Git: Pull From do not always warn you when there is a conflict.

**Comment by chenhowa** [comment] 2018-04-27 05:27
@ronaldruzicka    ping

**Comment by ronaldruzicka** [comment] 2018-04-28 09:10
Hi, I'm using `pull rebase` and `push to`:

<img width="602" alt="pull-rebase" src="https://user-images.githubusercontent.com/20684387/39394639-91a4280c-4ad4-11e8-977b-dc08f5975622.png">
<img width="614" alt="push-to" src="https://user-images.githubusercontent.com/20684387/39394638-9189dd58-4ad4-11e8-8303-6b57bf358a85.png">

Next time I'll try just `pull` and `push` and let you know.

**Comment by chenhowa** [comment] 2018-04-29 04:13
Okay, thanks. But actually, let me know if Pull (Rebase) still fails to report Failure to you. I've fixed the issue for Push To and Pull From (at least on my machine), and based on my understanding of the fix, Pull (Rebase) _should_ report errors to the user.

If it isn't doing that for you, then I haven't found the actual source(s) of the problem.

Also, I don't know if you still want this, but I don't see a reason to add a notification for when the push/pull is successful. I think it would be more distracting than informative.

**Comment by ronaldruzicka** [comment] 2018-05-15 14:03
Hi @chenhowa , sorry for late reply.

So I have VS Code Version `1.23.1` and still have the issue. If I do `push` I have a notification, but not classic one on the bottom right, but some alert message on top. But if I do `push to` I don't get any notification, I can only see the small arrow on bottom left, that commit is still pending.

![git-push-no-notification](https://user-images.githubusercontent.com/20684387/40061404-1f067614-5859-11e8-87ad-ffc270e4a3ee.gif)

**Comment by chenhowa** [comment] 2018-05-16 03:55
@ronaldruzicka 
As far as I could tell, most if not all Git errors from the command palette are handled using the alert message on top, instead of the classic on on the bottom right. So in my commit, "Push to" handles errors using the alert message on top, to stay consistent.

Unfortunately, the commit hasn't been merged yet: it's in the Backlog. Hopefully it will make it to a future version of VS Code, but the timeline for that isn't clear.

**Closed** 2018-06-18 08:55 UTC
Labels: bug, git, good first issue, help wanted
