### ISSUE TITLE
Release notes reloaded when switching between tabs

### ISSUE THREAD

**Issue by JohannBlake** [Microsoft/vscode#23916] opened 2017-04-05 07:16 UTC
When reviewing the release notes of the latest version of VSC, if you scroll down to a section or click on a link to take you to a place in the release notes, then tap on a tab containing your source code and then switch back to the release notes, the release notes reload and you lose the position you were last at. Don't reload the release notes when switching between tabs.

**Comment by chrmarti** [comment] 2017-04-05 15:29
Reproduced in both 1.10.2 and latest insiders.

**Comment by mjbvz** [comment] 2017-04-05 18:27
This sounds like a duplicate of #15214

**Closed by mjbvz** 2017-04-05 18:27 UTC
Labels: bug, duplicate
