### ISSUE TITLE
Alt open editor to side action gets "stuck" after alt clicking

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50705] opened 2018-05-29 17:37 UTC
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

I split an editor to side using alt+click on the action and the action in the new window is stuck until I move focus to a different editor:

![image](https://user-images.githubusercontent.com/2193314/40675314-3d6c38cc-632c-11e8-9295-24f70471b077.png)

Note that alt is not pressed and the mouse is not anywhere near the lower editor in the screenshot.

**Comment by bpasero** [comment] 2018-05-30 04:27
Duplicate of https://github.com/Microsoft/vscode/issues/50581

**Closed by bpasero** 2018-05-30 04:27 UTC
Labels: bug, insiders, workbench-grid
