### ISSUE TITLE
CTRL+V & CTRL+C don't work properly

### ISSUE THREAD

**Issue by Nemzag** [Microsoft/vscode#60007] opened 2018-10-05 04:19 UTC
Issue Type: <b>Bug</b>

After reboot, ctrl+c & ctrl+v don't work many time ! I don't know why !

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q9650  @ 3.00GHz (4 x 3006)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (1.64GB free)|
|Process Argv|C:\Users\nemza\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
empty-indent|Dmi|0.2.0
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-indent-on-paste|gaz|2.2.1
beautify|Hoo|1.4.4
pgsql-html|hub|0.0.7
indent-rainbow|ode|7.2.4
sass-indented|rob|1.4.9
twig|wha|1.0.2

</details>

**Comment by Nemzag** [comment] 2018-10-05 15:29
Yes, of course, when trying to write simple HTML or CSS codes…
And "CTRL" sometime not work with any other combinations (not only CTR+C & CTRL+V),
I don't know why ?
Sometime it does ?
Very strange behavior.

**Comment by Tyriar** [comment] 2018-10-06 02:51
Can you try closing all windows and running `code --disable-extensions` and seeing if it still happens?

**Comment by Nemzag** [comment] 2018-10-06 05:48
I just tested, and after removing extension's, I didn't had that problem anypoly, but since it happen sporadically and sometime, it's not sure that one of extension's cause this trouble.
I re‑activated one by one extension's and I didn't had the bug, but as I said before, it happen sometime, after a reboot or a new launch…

**Comment by alexandrudima** [comment] 2018-10-10 10:51
@Nemzag The fact that sometimes copy/pasting works and sometimes it stops working makes me believe you have some sort of environmental problem. This might be caused by an external program that could be manipulating the OS clipboard.

**Comment by Nemzag** [comment] 2018-10-10 12:00
@alexandrudima May be, I use AutoHotKey in background, and the new Windows October 2018 update, added a clipboard history, I don't know… May be it's the cause of this. But I want to say that I never have this trouble elsewhere like in Brackets, PhpStorm, SublimeText and NotePad++ !

**Comment by alexandrudima** [comment] 2018-10-16 08:14
@dbaeumer I don't have the Windows October 2018 update yet, and for me this does not reproduce. Do you have it (to try to reproduce)?

**Comment by dbaeumer** [comment] 2018-10-16 08:17
@alexandrudima I do have it. Will try to reproduce

**Comment by dbaeumer** [comment] 2018-10-16 08:20
I have the October Update since ~3 weeks and I didn't experience any problems with Copy / Paste during that time.

**Closed** 2018-10-23 09:12 UTC
Labels: keybindings, needs more info, windows
