### ISSUE TITLE
Allow editor.scrollBeyondLastLine to specify number of lines past end 

### ISSUE THREAD

**Issue by superlevure** [microsoft/vscode#112474] opened 2020-12-14 13:47 UTC
Issue Type: Feature Request

The option editor.scrollBeyondLastColumn allows you to specify the number of additional characters worth of scrolling to allow and defaults to a sane value.

I'd like to be able to specify a value for editor.scrollBeyondLastLine similar to editor.scrollBeyondLastColumn.

**Comment by gjsjohnmurray** [comment] 2020-12-14 14:09
/duplicate of #97561 which needs upvoting to get onto Backlog

**Closed** 2020-12-14 14:10 UTC
Labels: *duplicate
