### ISSUE TITLE
Allow to print the editor contents

### ISSUE THREAD

**Issue by Denisov21** [Microsoft/vscode#7076] opened 2016-05-31 18:48 UTC
- VSCode Version:1.1
- OS Version: Win10

Please,
Can you add the print command

**Comment by catchmyfame** [comment] 2016-11-07 14:39
Dupe of https://github.com/Microsoft/vscode/issues/5953?

**Comment by bpasero** [comment] 2017-05-25 18:06
https://github.com/Microsoft/vscode/issues/5953

**Closed by bpasero** 2017-05-25 18:06 UTC
Labels: feature-request, upstream, workbench
