### ISSUE TITLE
Weird issue when the terminal's width is small?

### ISSUE THREAD

**Issue by namvt13** [Microsoft/vscode#63731] opened 2018-11-25 05:50 UTC
- VSCode Version: 1.29.1 (It's happened before, but still persists to this version)
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. "cd" to a really long path
2. Resize the window to the smallest (the bug happens depend on the length of the above path)

Does this issue occur when all extensions are disabled?: Yes

Please take a look at the terminal screen (This is after a 'clear' command has been executed).
![screenshot from 2018-11-25 12-48-42](https://user-images.githubusercontent.com/39618961/48975975-98025480-f0b0-11e8-9d62-8feb88fb2091.png)

**Comment by usernamehw** [comment] 2018-11-25 07:57
/duplicate of #26375 which is a duplicate of #45693

**Closed** 2018-11-25 07:58 UTC
Labels: *duplicate, integrated-terminal
