### ISSUE TITLE
Ctrl + Click = go to link shortcut === bad UX

### ISSUE THREAD

**Issue by Bram-Zijp** [Microsoft/vscode#27062] opened 2017-05-22 08:39 UTC
In Windows the key shortcut to go to a link is CTRL + Click. While editing you select code and CTRL + C to copy allot. While doing this you will go to a link instead if you already pressed CTRL while selecting.

**Comment by alexandrudima** [comment] 2017-05-24 14:36
Duplicate of #6910

**Closed by alexandrudima** 2017-05-24 14:36 UTC
