### ISSUE TITLE
Markdown preview doesn't apply transparency to linked transparent png image

### ISSUE THREAD

**Issue by xtbe** [Microsoft/vscode#7891] opened 2016-06-20 14:08 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:
1. Create a Markdown file with an image link to a transparent PNG file
2. Show the preview. 

If you're using the dark theme in visual studio code the transparency isn't applied

**Comment by rebornix** [comment] 2016-06-20 14:47
I've just tried PNG file with transparent background and find it Okay. Do you mind helping provide following info:

1. What's the real background colour of the image? A snapshot will be better, otherwise you may want to provide a sample image which breaks in your env.
2. Can you help verify this issue with our latest insider build? Our latest markdown feature is on the Insider version.

**Comment by xtbe** [comment] 2016-06-20 15:04
I re-created another image with less information as this couldn't be published and I saw it was displayed correctly. When I repeated the steps on the original image it wasn't correctly refreshed. After closing the MD preview and reopening it the image was displayed correctly.

**Comment by xtbe** [comment] 2016-06-20 15:09
I also found the refresh button now, so when replacing an image on the filesystem you need to press "refresh" as well in order to get the updated image.

**Comment by rebornix** [comment] 2016-06-20 15:16
@xtbe thanks for your detailed info and patience! The second issue you mentioned is already logged in https://github.com/Microsoft/vscode/issues/5687 , we will add local file monitor later on but for now I'm not sure whether we should keep an eye on local image links in markdown content. 

Besides, I'd like to keep this open for a while to see if we can reproduce the problem constantly.

**Comment by mjbvz** [comment] 2016-12-01 00:48
Closing since we have not see this issue reported recently.

@xtbe please let me know if you have a reliable repo and we can open this again for further investigation. Thanks.

**Closed by mjbvz** 2016-12-01 00:48 UTC
Labels: markdown

**Comment by ridgebackcap** [comment] 2017-02-24 15:18
FYI, this is still an issue
