### ISSUE TITLE
Add context filter to new feature

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#72675] opened 2019-04-21 10:49 UTC
I enjoy a lot this new feature 👍 
```js
"editor.suggest.filteredTypes": {
  "snippet": false,
  "class": false
}
```

But it will be awesome if we can manage some context for it, for example : 
```js
"editor.suggest.filteredTypes": {
  "snippet": {
    "inImportsStatement": false,
    "inFunction": false,
    "onRequest": true,

  },
  "class": false
}
```

The `onSuggest` is the natural intellisense while typing.
The `onRequest` is the explicit `ctrl+space` intellisense invocation.
The `inImportsStatement` could represent this cursor position : 
```js
import { | } from 'mylib';
```
The `inFunction` is explicit.

There may be a tons of useful filter for this feature, and it should really be considered.

**Comment by mjbvz** [comment] 2019-04-22 18:48
Duplicate of #72676

**Closed by mjbvz** 2019-04-22 18:48 UTC
Labels: javascript

**Comment by DavidBabel** [comment] 2019-04-22 19:59
Sorry, i don't know why it was posted twice
