### ISSUE TITLE
ATA Intellisense doesn't work

### ISSUE THREAD

**Issue by Teamop** [Microsoft/vscode#21877] opened 2017-03-03 10:48 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.1.5|
|EditorConfig|EditorConfig|0.4.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. I have the express in package.json, but when editing, get no intellisense for it.
![image](https://cloud.githubusercontent.com/assets/8519685/23547819/a7c785f6-003f-11e7-8b6c-5197dfa219ce.png)
I noticed the tsserver is running, and the tsserver trace:
---
>[Trace - 6:35:57 PM] Event received: telemetry (0).
Data: {
    "telemetryEventName": "typingsInstalled",
    "payload": {
        "installedPackages": "@types/finalhandler@ts2.2,@types/ms@ts2.2,@types/mocha@ts2.2,@types/benchmark@ts2.2,@types/istanbul@ts2.2,@types/seedrandom@ts2.2,@types/debug@ts2.2,@types/escape-html@ts2.2,@types/on-finished@ts2.2,@types/supertest@ts2.2,@types/inherits@ts2.2,@types/statuses@ts2.2,@types/expect.js@ts2.2,@types/depd@ts2.2,@types/http-errors@ts2.2,@types/mime@ts2.2,@types/range-parser@ts2.2,@types/parseurl@ts2.2,@types/send@ts2.2,@types/csv-parse@ts2.2,@types/stream-to-array@ts2.2,@types/ncp@ts2.2",
        "installSuccess": false,
        "typingsInstallerVersion": "2.2.1"
    }
}
[Trace - 6:35:57 PM] Event received: endInstallTypes (0).
Data: {
    "eventId": 2,
    "packages": [
        "@types/finalhandler@ts2.2",
        "@types/ms@ts2.2",
        "@types/mocha@ts2.2",
        "@types/benchmark@ts2.2",
        "@types/istanbul@ts2.2",
        "@types/seedrandom@ts2.2",
        "@types/debug@ts2.2",
        "@types/escape-html@ts2.2",
        "@types/on-finished@ts2.2",
        "@types/supertest@ts2.2",
        "@types/inherits@ts2.2",
        "@types/statuses@ts2.2",
        "@types/expect.js@ts2.2",
        "@types/depd@ts2.2",
        "@types/http-errors@ts2.2",
        "@types/mime@ts2.2",
        "@types/range-parser@ts2.2",
        "@types/parseurl@ts2.2",
        "@types/send@ts2.2",
        "@types/csv-parse@ts2.2",
        "@types/stream-to-array@ts2.2",
        "@types/ncp@ts2.2"
    ],
    "success": false
}
---

and I also have some questions:
1. where the ATA have downloaded the types in so that I can check the ATA works well?
2. I got the this message from [official document](https://code.visualstudio.com/docs/languages/javascript)
![image](https://cloud.githubusercontent.com/assets/8519685/23548182/34aa5ee8-0041-11e7-87f9-6f65a8e74ac3.png)
so now ATA supports bower without any configuration, right?
3. ATA should work without jsconfig.json, and intellisense can also work without jsconfig.json, right?

**Comment by mjbvz** [comment] 2017-03-08 02:46
To investigate the typings install issue, can you please enable TypeScript Server logging by:

* From cmd prompt, run: `set TSS_LOG=-level verbose -file c:\tmp\tsserver.log`
* From the same command prompt, start vscode: `code`
* Reproduce the issue
* Share the `tsserver.log` and the `ti-xxx.log` files in `c:\tmp`

This will help us investigate why typings installation is failing.

---

Answering the questions

**1. where the ATA have downloaded the types in so that I can check the ATA works well?**

Try checking `%localappdata%\TypeScript`

**2. ATA supports bower without any configuration, right?**

Yes, it should pick up packages from your `bower.json` automatically

**3. ATA should work without jsconfig.json, and intellisense can also work without jsconfig.json, right?**

Here's more info about the `jsconfig.json`: https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson

Basic intelliSense will work without one, but you may want to create one to define your JavaScript project

**Comment by Teamop** [comment] 2017-03-08 05:53
Hi @mjbvz 
1. attach the two log files for your investigation.

[log.zip](https://github.com/Microsoft/vscode/files/826736/log.zip)

2. For checking %localappdata%\TypeScript, I can't find this directory in my PC.

**Comment by mjbvz** [comment] 2017-03-08 23:19
Thanks. It looks like the `cookie-parser` typings fail to install. I've opened a bug against TS to track this: https://github.com/Microsoft/TypeScript/issues/14546

Also, the correct path for the typings install location is `%localappdata%\Microsoft\TypeScript`. Please try entering that into the windows explorer path bar 

Closing as upstream

**Closed by mjbvz** 2017-03-08 23:19 UTC
Labels: javascript, question, typescript, upstream
