### ISSUE TITLE
Copilot edits marks files as dirty after undoing

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#233795] opened 2024-11-13 20:44 UTC
I think this might be how I got into the bad state I was in before

1. Make some edits with Copilot edits
2. Accept them
3. Make another change in the file
4. Hit undo
5. Copilot edits brings you back to the accept/discard state

**Comment by jrieken** [comment] 2024-11-14 13:56
> Hit undo

@connor4312 editor-undo or /edit-undo?

**Comment by connor4312** [comment] 2024-11-14 16:32
ctrl+z undo

**Comment by jrieken** [comment] 2024-11-15 16:03
closing this as dupe of https://github.com/microsoft/vscode-copilot/issues/10516#issuecomment-2479066020 (which came later but has more steps and analysis)

**Closed** 2024-11-15 16:03 UTC
Labels: *duplicate, cross-file-editing
