### ISSUE TITLE
Operator Mono font rendering issue after May 2024 update (version 1.90)

### ISSUE THREAD

**Issue by jakeherp** [microsoft/vscode#214647] opened 2024-06-07 21:30 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90
- OS Version: macOS 14.5 (23F79)

Steps to Reproduce:

1. Use Operator Mono font
2. Upgrade VS Code to 1.90.0

I have confirmed the same issue across two devices. Before installing the VS Code May 2024 update the font renders just fine, after the update it only renders the bold version of the font.

Using `OperatorMono-Book` instead does work, but italics remain bold. 

I have tried switching to a different font and cannot reproduce the bug with any other fonts (I tried Fira Mono, Ghost Mono, Victor Mono, and the default `monospace` font). This seems to be an exclusive issue with Operator Mono.

Here is an example of the problem:

<img width="554" alt="Screenshot 2024-06-07 at 22 27 01" src="https://github.com/microsoft/vscode/assets/17340718/271957c9-73c1-4507-9483-973ed33b71dd">

**Comment by chantalgo** [comment] 2024-06-08 01:21
Same issue as @/jakeherp. Reverting to April 2024 update (version 1.89), the font works as excepted.

**Comment by rzhao271** [comment] 2024-06-10 15:03
Duplicate of #214390

**Closed** 2024-06-10 15:03 UTC

**Comment by wesbos** [comment] 2024-06-11 14:31
Also seeing this - as soon as I updated everything went bolder


"Operator Mono, Menlo, Monaco, 'Courier New', monospace"

Above is the latest update, below is before the update.

<img width="589" alt="Screenshot 2024-06-11 at 10 31 03 AM" src="https://github.com/microsoft/vscode/assets/176013/e48dd651-b18a-4e2a-b844-dadec54d2483">

**Comment by wesbos** [comment] 2024-06-11 14:33
looks like its been fixed and will be shipped soon: https://github.com/microsoft/vscode/issues/214390
