### ISSUE TITLE
Emmet expansion doesn't work with non-ascii characters

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27782] opened 2017-05-31 20:43 UTC
#27316

`div.foo` => `<div class="foo"></div>`
`div.fóó` => `no suggestions`
`div#漢字` => `no suggestions`

**Comment by ramya-rao-a** [comment] 2017-05-31 20:45
@sergeche Do the extract and expand abbreviation modules support non-ascii characters?

**Comment by sergeche** [comment] 2017-05-31 20:55
Partially. Currently, element name, id and class are ASCII-only, but I may sync with CSS specs and support non-ASCII chars in id and class

**Comment by ramya-rao-a** [comment] 2017-05-31 21:12
Thanks @sergeche 

@roblourens `div{fóó}` -> `<div>fóó</div>` still works. 
Given that non-ascii chars appear more in html content than html tag/attr, I'll close this issue as by design.

If we see more interest in this feature from the community, then we can re-visit it.

**Closed by ramya-rao-a** 2017-05-31 21:12 UTC
Labels: under-discussion, upstream
