### ISSUE TITLE
Context menu triggered when tree has focus selects an item

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#25354] opened 2017-04-26 00:09 UTC
- VSCode Version: 1.12.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

So you can have the same menu when you right click on the blank area, using the <kbd>Menu</kbd> key on the keyboard.

**Comment by bpasero** [comment] 2017-04-26 04:23
@Tekbr you can press the ESC key until you see a blue focus border around the explorer to get there 👍

**Comment by Tekbr** [comment] 2017-04-27 01:40
-- Sorry for the English, I used Google Translator --

@bpasero Sorry, but I could not.(Maybe it has some configuration)

Can you show me with a gif with empty keybindings file - default?

Can you show me with a gif with a second situation? In this situation configure this in your keybindings file:
`{ "key": "escape", "command": "workbench.action.focusActiveEditorGroup", "when": "explorerViewletFocus" }`

**Comment by bpasero** [comment] 2017-04-27 05:24
@Tekbr in your case the keybinding change you did will prevent this from happening. By default (without the keybinding overridden), ESC will eventually make the entire tree have focus, then it looks like this:

![screen shot 2017-04-27 at 07 24 25](https://cloud.githubusercontent.com/assets/900690/25469105/92e84700-2b1a-11e7-899e-45f939147f13.png)

**Comment by Tekbr** [comment] 2017-04-27 13:08
-- Sorry for the English, I used Google Translator --

@bpasero Well I agree that with the configuration it is not possible ... then there is a feature request - if possible !!

But if I have 3 or more sub folders and if one is open I can not access the menu in the main folder.

Or if you have 4 or more sub folders and if one of them is open or not I can not access the menu in the main folder either.

![explorererro](https://cloud.githubusercontent.com/assets/19866231/25484534/c2df92fe-2b30-11e7-99f0-09f225f5a706.gif)


Or it will depend on the size of my file tree with the size of the VSCode window.

![explorererro2](https://cloud.githubusercontent.com/assets/19866231/25484541/c6e553ca-2b30-11e7-9527-f8f6cb25fadb.gif)

**Comment by bpasero** [comment] 2017-04-27 14:57
@Tekbr you can redefine the command `list.clear` on a different keybinding and that will give you the same as ESC by default.

**Comment by Tekbr** [comment] 2017-04-27 16:09
@bpasero 
I think you did not understand. 🤔 

You can not create a new file or folder in the main folder by using the menu key.

![menu](https://cloud.githubusercontent.com/assets/19866231/25492863/b863c0e2-2b4a-11e7-8148-b3cea70387bf.png)


See the gifs ... the blue focus is on the whole file tree.

**Comment by bpasero** [comment] 2017-04-28 05:16
I can reproduce, this seems to me like a regression.

**Comment by bpasero** [comment] 2017-05-02 09:33
@joaomoreno there is some weird code around [here](https://github.com/Microsoft/vscode/blob/release/1.12/src/vs/base/parts/tree/browser/treeView.ts#L1239) that is triggered when you press the context menu key.

Steps:
* use Windows
* bring on screen keyboard on
* click in explorer
* press ESC often enough until explorer gets blue border
* press context menu key on the on screen keyboard
![image](https://cloud.githubusercontent.com/assets/900690/25612464/1ab16356-2f2b-11e7-9a8b-20cceb031555.png)
=> the previously focused item gets focus
=> the context menu targets that item

I would expect that the element I am getting around the context menu event is the root node.

This is the same behaviour in stable btw, so it must have changed quite a while ago.

**Comment by joaomoreno** [comment] 2017-11-23 14:19
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by Tekbr** [comment] 2017-11-27 02:45
-- Sorry for the English, I used Google Translator --

@joaomoreno , The fact that this is a problem, even if it does not have many returns. @bpasero  himself agrees that it is a regression.

I can not create a folder in the main tree by keyboard. See the above gifs. That does not depend on voting. The problem gets even worse with the multiple folders.

You do not even answer the question for John to the public to give a satisfaction. Yes you can be busy with other issues but stop talking "ok I'll check".

Sad for the new dish of yours. 😢 

PS: I did not see duplicate issues of the subject.

**Comment by joaomoreno** [comment] 2017-11-27 09:05
Don't think it's a regression... it was really never looked at properly.

Found the problem & pushed a fix.

@Tekbr Thanks for the persistence!

**Closed** 2017-11-27 09:05 UTC
Labels: bug, tree

**Comment by Tekbr** [comment] 2017-11-28 15:33
@joaomoreno Thanks for the quick fix. 😄  Now I do not depend on the mouse anymore.

If I knew it would be so fast, I would have called earlier. 😆 😂 

Whether it was a regression or not, I do not know .. I know it was a problem, it was annoying.

> @Tekbr Thanks for the persistence!

You're welcome!! I who have to have to apologize ... due to the difficulty of communication, and get a little hard to understand .. 😊

**Comment by ramya-rao-a** [comment] 2017-12-06 21:55
Marking as verified as @Tekbr confirms the issue has been fixed in the Insiders
