### ISSUE TITLE
Pasting text randomly in multiple files

### ISSUE THREAD

**Issue by sbiro** [Microsoft/vscode#38072] opened 2017-11-10 16:01 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.2

Problem:
Pasting into one spot also pastes the same text into other files in the same project random number of times 

Unfortunately I cannot reproduce it but it happens often. It happened in Ubuntu version 16 as well as 17.

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-11-11 11:22
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2017-11-24 06:05
Closing until further info is provided.

**Closed by bpasero** 2017-11-24 06:05 UTC
Labels: editor, needs more info
