### ISSUE TITLE
Jump to Bracket moves cursor but not the view

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#35355] opened 2017-09-29 04:41 UTC
- VSCode Version: 1.16.1
- OS Version: Fedora 26

Steps to Reproduce:

1. Ctrl-p Go to Bracket

Reproduces without extensions: Yes

Go to Bracket will jump the cursor to the matching bracket but not the view when the matching bracket is not on screen. 
One can move cursor with the arrow keys after jumping to matching bracket and the view would jump too.
Previous vscode versions would "scroll" to the matching bracket automatically.
Is this on purpose in the latest vscode version, seems like a bug.

Thanks.

**Comment by alexandrudima** [comment] 2017-09-29 05:56
Duplicate of #32597

**Closed by alexandrudima** 2017-09-29 05:56 UTC
Labels: editor, editor-brackets
