### ISSUE TITLE
Allow terminals to be re-used when running build task

### ISSUE THREAD

**Issue by boagz57** [Microsoft/vscode#45789] opened 2018-03-14 18:33 UTC
I have the latest VS Code installed on my Windows 10 machine. I currently have a task.json file setup like so:

   ```
 {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "build",
                "type": "shell",
                "windows": {
                    "command": "${workspaceRoot}\\build.bat"
                },
                "group": {
                    "kind": "build",
                    "isDefault": true
                },
                "presentation": {
                    "panel": "dedicated"
                }
            }
        ]
    }
```

I'm using this task to run my build.bat file which contains the following line:

    if not defined DevEnvDir ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" )

Which should only be calling "vcvars64.bat" upon the first execution of the terminal. 

The problem is I want the terminal that is being created by the build task to be reused upon subsequent builds, thus only calling vcvars64.bat once. Currently, each time I build, vcvars64.bat is called and executed  every time. When I just build from a regular, external cmd terminal, or when I build from VS Code's internal terminal (using cmd) everything works as expected when building subsequent times. It's only when trying to run the task does this problem occur. Is there an option I'm missing or is this not possible currently?

**Comment by dbaeumer** [comment] 2018-03-15 07:45
@boagz57 unfortunately implementing this is very hard and we discussed several approaches to do this and none seemed to be a good solution. The problem is that there is no reliable way to determine if a shell is idle (e.g can take the next command). So we start a new shell for every task we execute.

In your case your a better doing the following: open a terminal run vcvars64.bat and then start code from that terminal. Then all task runs will have the correct environment set.

I will close the issue since unless we find a way to detect when a shell is idle there is no good way to implement this.

**Closed by dbaeumer** 2018-03-15 07:45 UTC
Labels: tasks
