### ISSUE TITLE
Minimap dissapears when using references popup supplied by referencesCodeLens.enabled = true

### ISSUE THREAD

**Issue by Pizzahd88** [Microsoft/vscode#29095] opened 2017-06-20 09:37 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|Angular2|johnpapa|2.3.3|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Enable codelens in Preferences -> Settings:  "typescript.referencesCodeLens.enabled": true
2. The reference count will appear above methods and classes, click the gray x references link above the method/class, to see where it is referenced from.
3. Click above the popup that shows the references.
4. The minimap on the right will now be made into a normal vertical scrollbar.

A reboot of VSCode will show the minimap again instead of the vertical scrollbar, but only until the references popup is used again.

**Comment by alexandrudima** [comment] 2017-06-21 07:25
Duplicate of #28093

**Closed by alexandrudima** 2017-06-21 07:25 UTC
Labels: new release
