### ISSUE TITLE
Blurred files in explorer due to translate3d usage

### ISSUE THREAD

**Issue by bibendi** [microsoft/vscode#68556] opened 2019-02-12 19:33 UTC
Issue Type: <b>Bug</b>

After update to the latest version, I've seen blurred files in explorer.

![screenshot from 2019-02-12 22-19-37](https://user-images.githubusercontent.com/320886/52662751-0a4b3e00-2f16-11e9-8a28-3f9e7567adc3.png)

I'm using Ubuntu 18.04 Unity Wayland with text scaling factor 1.25

I've experienced the same blurring effect in Chrome two or three versions ago. It was fixed with the next version.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2744)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.53GB (1.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
pgsql|dou|0.1.3
gitlens|eam|9.5.0
vscode-great-icons|emm|2.1.46
rails-snippets|Hri|1.0.8
endwise|kai|1.4.2
ruby-symbols|mig|0.1.7
dotenv|mik|1.0.1
atom-keybindings|ms-|3.0.6
vetur|oct|0.15.0
vscode-docker|Pet|0.5.2
ruby|reb|0.21.0
sass-indented|rob|1.5.1
slim|sia|0.1.2
rails-go-to-spec|spo|0.0.1
guides|spy|0.9.3
haml|vay|1.0.1

(1 theme extensions excluded)

</details>

**Comment by bibendi** [comment] 2019-02-12 20:31
I've downgraded to 1.30.2. Now I see not blurred files. And I've discovered that the main text area was also a little bit blurred.

![screenshot from 2019-02-12 23-23-47](https://user-images.githubusercontent.com/320886/52666032-23f08380-2f1e-11e9-97ea-c3de35339d59.png)

**Comment by joaomoreno** [comment] 2019-02-18 11:31
> I've experienced the same blurring effect in Chrome two or three versions ago. It was fixed with the next version.

**Comment by bpasero** [comment] 2019-02-18 11:50
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by bibendi** [comment] 2019-02-19 06:06
I tried this exploration build today. The blur has disappeared now!

**Comment by bibendi** [comment] 2019-02-20 05:40
When vscode with electron 4 will be released?

**Comment by bibendi** [comment] 2019-06-10 08:12
Hi @bpasero 
Today I've upgraded my exploration build `code-exploration_1.31.0-1544686921_amd64.deb`
so I've got
```
Version: 1.35.0-exploration
Commit: 1158b7573b3444493ff5ee8355ad23350d76596a
Date: 2019-05-31T05:12:16.034Z
Electron: 4.2.2
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-51-generic
```

It looks like the bug come back. :crying_cat_face:  I again have blurred files tree when I scroll it down.

https://pasteboard.co/IiJNGS3.png

Maybe it is not because of the Electron?

**Comment by bpasero** [comment] 2019-06-11 06:51
@bibendi do you also see this in our insiders version? That one updated to Electron 4 meanwhile.

**Comment by bibendi** [comment] 2019-06-11 07:00
I've just installed the insiders' version. Yes, I see the same effect.

**Comment by bpasero** [comment] 2019-06-11 07:28
Ok too bad, not sure what this is then.

**Comment by bibendi** [comment] 2019-06-11 08:14
The blurred effect is definitely related to the fractional font scale factor. It isn't appear when I run VSCode with `--force-device-scale-factor=2` or `--force-device-scale-factor=1`.

**Comment by bibendi** [comment] 2019-06-13 07:49
@bpasero Maybe is it related to this issue? https://github.com/Microsoft/vscode/issues/24483
Also, I found this effect on the Settings tab.

**Comment by bpasero** [comment] 2019-10-08 14:05
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by bpasero** [comment] 2019-10-15 14:56
@bibendi I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue in either or both web and Electron?

**Comment by bibendi** [comment] 2019-10-17 08:22
I've reproduced the issue only for Web. You can get a screencast here https://drive.google.com/open?id=1zu1lWsJ5v42dKbSEQbZbl96bYPyroIOm 
Please, download the video file for the best quality. I'm scrolling the files explorer back and forth, and the blurring is appearing and disappearing.

As for Electron, I've only seen a white window and nothing more ¯\\\_(ツ)_/¯

Maybe it is essential; I have a system-wide fractional text scale at 1.25.
![image](https://user-images.githubusercontent.com/320886/66991114-1ce2cc00-f0d0-11e9-89d3-88f88c238dc5.png)

**Comment by bpasero** [comment] 2019-10-17 08:28
@bibendi awesome to hear that, would you be willing to report this as issue to https://bugs.chromium.org/p/chromium/issues/list and we go on from there?

**Comment by bibendi** [comment] 2019-10-17 09:39
> to report this as issue

I think it is a [similar problem](https://bugs.chromium.org/p/chromium/issues/detail?id=942277&q=translate3d&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
).

I go a little bit deeper. :slightly_smiling_face: 
I've found out the reason. It's because of `transform: translate3d()`. When I manually change the value of `y` axis then the blurring is blinking.

As I understand, the `editor-container` has implemented a different scrolling approach. It has the `will-change: transform`.

Maybe I can somehow disable using of translate3d? As I see [here](https://github.com/microsoft/vscode/blob/ab713cac34e15eaf4e2ac045376f09d9fe7f267b/src/vs/base/browser/ui/list/listView.ts#L534) and [here](https://github.com/microsoft/vscode/search?q=translate3d&type=Code) the option can be a problem.

**Comment by bpasero** [comment] 2019-10-17 10:00
@bibendi sorry, but where exactly are we using `translate3d()` can you show me in code?

**Comment by bibendi** [comment] 2019-10-17 10:07
![image](https://user-images.githubusercontent.com/320886/66999618-06903c80-f0df-11e9-9141-bf4f9c10db6b.png)

**Comment by bpasero** [comment] 2019-10-17 10:12
Ok thanks, moving to @joaomoreno and @isidorn to decide what to do here. We can still report this to Chrome, given that you can reproduce in the web version.

**Comment by joaomoreno** [comment] 2019-10-17 12:18
> As I understand, the editor-container has implemented a different scrolling approach. It has the will-change: transform.

Will do this.

**Comment by chrmarti** [comment] 2019-10-31 11:17
@joaomoreno Could you provide steps to verify?

**Comment by bpasero** [comment] 2019-10-31 11:29
I am not seeing a change (latest insiders, Ubuntu 18 Linux, Parallels VM):

![image](https://user-images.githubusercontent.com/900690/67943275-ff3a5a00-fbd9-11e9-92e6-b2a5cf66da25.png)

**Comment by joaomoreno** [comment] 2019-10-31 14:10
@bpasero I removed the `translate3d`, so whatever was affecting the tree shouldn't any longer.

In your screenshot you seem to be looking for subpixel antialiasing. Look at the screenshot below, subpixel antialiasing seems to be disable across the whole workbench on my Linux box, which seems to be another problem altogether. I don't think the lack of subpixel antialiasing was the reason behind this issue, but rather rounding errors in using `translate3d`.

![image](https://user-images.githubusercontent.com/22350/67953864-39165b00-fbf0-11e9-88f4-fc8eadad0da2.png)

**Closed by joaomoreno** 2019-10-31 14:10 UTC
Labels: bug, list, verification-found

**Comment by bpasero** [comment] 2019-10-31 16:33
@bibendi how about you verify this is fixed for you by trying our insiders build? I think then we have the best feedback on this issue:  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bibendi** [comment] 2019-10-31 17:59
Awesome! It works! Thank you, guys!
