### ISSUE TITLE
IntelliSense: signature flickers when broadening search

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1289] opened 2015-12-14 15:26 UTC
* type window.
* find the webkitconv... entry and complete it with enter
* backspace char by char and notice how the signature flickers

If you do the same while typing (narrowing down) the webkitconv entry and then broaden it, this does not happen.

**Comment by joaomoreno** [comment] 2015-12-14 15:34
Unfortunately nothing I can fix, since the list of suggestions I'm getting is not the same as you broaden; the suggestions themselves don't have the same ID. @jrieken introduced this with the concept of **suggestion details**.

**Comment by joaomoreno** [comment] 2015-12-14 15:35
Also, just closing since it's quite minor.

**Closed by joaomoreno** 2015-12-14 15:34 UTC
Labels: bug

**Comment by bpasero** [comment] 2015-12-14 15:37
I wanted to show that I test this because I am assigned ;)

**Comment by joaomoreno** [comment] 2015-12-14 15:37
Eheh. It's also not a regression, it has probably been like this foreva.

**Comment by jrieken** [comment] 2015-12-14 15:44
The concept of details is ~3years old. Tho if the flicker isn't we should probably reopen?

**Comment by joaomoreno** [comment] 2015-12-14 15:50
Flickr can't be recent. When you broaden, by definition you get a new suggestion list. Suggestion identity is not preserved, so we can't keep the details alive. The only bug fix here is to not set input on the tree widget before (1) all suggestions are received and (2) the focused one has its details resolved. This would introduced visible UI lag.

**Comment by jrieken** [comment] 2015-12-14 15:54
agree. or a fancy cross session object identify ;-)
