### ISSUE TITLE
TS deletes the end of identifiers when making member expressions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#202261] opened 2024-01-11 17:18 UTC
On the latest Insiders with an empty profile,

1. Have code like `const foo = { bar: { baz: true } }; foo.bar.baz;`
2. Delete the `bar.`'s so you get `foo.baz`
3. Place your cursor after `foo.` and type `baz.` -- exact characters, no need for anything else
4. The editor deletes the suffix and you're left with `foo.bar.` 🐛 

This doesn't happen with Python completions, only JS/TS

![Kapture 2024-01-11 at 09 15 57](https://github.com/microsoft/vscode/assets/2230985/cdc2173f-7880-499f-8288-9b20701d3cf1)

**Comment by mjbvz** [comment] 2024-01-11 20:48
Duplicate of #202153

**Closed by mjbvz** 2024-01-11 20:48 UTC
Labels: bug, papercut :drop_of_blood:
