### ISSUE TITLE
Always disabled preview button for HTML file

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#17589] opened 2016-12-20 07:05 UTC
- VSCode Version: 
![image](https://cloud.githubusercontent.com/assets/3082812/21340967/ea900b58-c69a-11e6-999a-ec7ce5de825b.png)

- OS Version: win7 pro

Steps to Reproduce:

1. Open HTML file;
2. Preview button is disabled, push to button, don`t open preview;
![image](https://cloud.githubusercontent.com/assets/3082812/21340990/140b3408-c69b-11e6-83a0-cfd621ef9e6e.png)

3. Press `Ctrl+Shift+V`, preview is opened.
![image](https://cloud.githubusercontent.com/assets/3082812/21341086/b95ff9de-c69b-11e6-9ff1-9efcfea9591d.png)

**Comment by egamma** [comment] 2016-12-20 09:23
see also #17592

**Comment by aeschli** [comment] 2017-01-30 21:07
marking as duplicate of #17589

**Closed by aeschli** 2017-01-30 21:07 UTC
Labels: html
