### ISSUE TITLE
iPadOS: can not go to full screen

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#106972] opened 2020-09-18 00:12 UTC
- VSCode Version: Codespaces
- OS Version: iPadOS 13

Steps to Reproduce:

1. Open Codespaces
2. Enter Zen Mode (Cmd K Z)
3. Try using any keyboard shortcut like Cmd Shift P (Command Palette), Delete Line (Cmd Shift K)
4. Result: Not working
5. I didn’t test on Deskopt (yet)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2020-09-18 08:00
On desktop this just works. Forwarding to @bpasero as he knows what is the proper thing to do with Codespaces issues.

**Comment by bpasero** [comment] 2020-09-18 08:05
@rebornix maybe has a clue

**Comment by alefragnani** [comment] 2020-09-18 14:59
Yes, it works on Desktop 👍 

But is it expected the `ESC` key, when pressed in `Command Palette`, to _leave the full screen mode_ instead of simply cancel the `Command Palette` and return to the editor?

I'm on MacOS, btw.

**Comment by bpasero** [comment] 2020-10-15 12:21
I cannot reproduce this. I added a Codespace to my homescreen and entering Zen mode seems to work fine and keys continue to work for me. Does it still fail?

**Comment by alefragnani** [comment] 2020-10-15 13:13
I just tested, and it is not failing, but it is not entering _Zen Mode_ too 😢 . At least not like it used to be, and like Desktop version does .

When activating `Zen Mode` now, it just removes the **Side Bar** and the **Status Bar**. It is not removing the Safari’s address bar and buttons, like it used to do. It misses the _Full screen_ appearance.

Then, I decided to run `View: Toggle Full Screen` command, expecting it to _merge_ the behavior, but the command fails. It starts to _enter_ the mode, hiding Safari address bar/buttons and adding a floating `Close` button at left, but then it stops and returns to the previous state. This seems exactly the same behavior I saw on `Zen Mode` a couple of days after I filled this issue, which was apparently a workaround to avoid the issue, until being properly addressed.

After running `View: Toggle Full Screen` command, the `Zen Mode` command starts to fail just like before. It appears it is trying to enter Full Screen as well. Even if I open another Codespace, the issue remains.

Thank you

**Comment by bpasero** [comment] 2020-10-16 05:50
Yeah I see the same when just trying in Safari without PWA mode, but can you please try PWA?

**Comment by alefragnani** [comment] 2020-10-16 14:05
Using PWA it indeed work (first time using a PWA on iPad TBH 😬). 

It’s a smart alternative, because in fact those Safari pieces are not there, already giving a full screen appearance. The downside, you end up with a PWA for each Codespace.

BTW, I just noted why you had to remove the `Predictive` Keyboard on #108111. It appears PWA works differently from the browser itself.

Thank you

**Comment by alefragnani** [comment] 2021-01-06 16:11
Unfortunately, the problem remains, but I would say, it’s “unstable”.

I mean, most of the time it does not work, but sometimes (I couldn’t detect if there is a pattern), it works, just like in PWA.

I’ve attached a screen recording, so you could see exactly what happens.

https://user-images.githubusercontent.com/3781424/103790845-7b230400-5020-11eb-9889-9413d7ca1b61.MP4

Thank you

**Comment by alefragnani** [comment] 2021-03-28 12:21
I just tested it again, and the problem remains. 

I’m not sure what kind of information do you need.

Thank you

**Comment by isidorn** [comment] 2021-05-10 12:46
Assigning to May to investigate

**Comment by isidorn** [comment] 2021-05-20 18:27
Okey I just tried this out and the only problem I am seeing is that
F1 > toggle full screen does not go into fullscreen

After I enter zen mode all the keyboard shortcuts work as expected and everything is fine.
So the gist of the issue at least for me is that we are not going into full screen on safari properly.
I am on latest Safari beta.

@alefragnani please let me know if there is something I am missing
@bpasero I saw we have this custom code for going into full screen on Safari [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/host/browser/browserHostService.ts#L417)
I tried experimenting with those various go into full screen mode tricks [from](https://stackoverflow.com/questions/25520119/how-do-you-get-full-screen-in-safari) and none seem to work. Maybe some ideas?

**Comment by bpasero** [comment] 2021-05-21 04:46
I think @rebornix added that fullscreen code.

**Comment by isidorn** [comment] 2021-05-21 17:52
I just spent too much time on this without any results.
It seems like as soon as we enter Full Screen mode we automatically exit it. I could not find out why, even though I commented out all the full screen "reaction code".
The best I can do is create a bad issue on the webkit list hoping Safari folks might have an idea https://bugs.webkit.org/show_bug.cgi?id=226094

The best workaround I can offer for now is that I disable full screen mode, and that zen mode does not go into fullscreen.

**Comment by alefragnani** [comment] 2021-05-21 23:06
@isidorn, nothing to add  👍. The behavior you experienced is exactly what I reported, as you can see in the video added in the comment above

Thank you

**Comment by alefragnani** [comment] 2021-05-21 23:07
Just to let you know, I’ll try to reproduce another _visual glitch_ I just found while playing it again to answer your question. 

After playing a bit with Zen Mode, Full Screen and Showing/Hiding the Side Bar, and switching between apps, while returning to Codespaces PWA, this happened. It doesn’t seems to be the width of the Side Bar, but I’m not entirely sure.

![IMG_0116](https://user-images.githubusercontent.com/3781424/119205851-d43f8180-ba6f-11eb-991e-c79535bb68c9.PNG)

If I can detect the steps to reproduce the error, I’ll open a separate issue.

Thank you

**Comment by isidorn** [comment] 2021-05-25 09:35
@alefragnani Okey so for now let's give the Safari people time to respond or maybe someone from the community. If there are no good ideas I will simply disable full screen mode on the ipad.

As for the layout issue I could not reproduce this. If you find steps please open a new issue and feel free to ping me @isidorn on it! Thanks a lot

**Comment by isidorn** [comment] 2021-05-26 14:29
I have disabled the full screen on iOS. For now leaving this one open as upstream and assigning to backlog if Safari provides a programatic way to enter full screen mode.

**Comment by butterflyhug** [comment] 2021-06-16 15:56
FYI #122319 was closed as a likely duplicate of this bug, but in that case the problem was reported when running VS Code as a PWA in Chrome for Mac.

**Comment by hkhking** [comment] 2021-09-15 10:33
i get it 😄

![IMG_685E2C362C23-1](https://user-images.githubusercontent.com/12771728/133417864-5cffd58b-f567-4c2d-82a6-491ae5687b76.jpeg)

os： ipados 15
device：ipad pro 2021 

step：
1、 pin icon to desktop
2、open & reload

**Comment by TylerLeonhardt** [comment] 2024-12-17 03:29
I think we can close this.

1. @isidorn fixed the Zen mode issue
2. You can almost get to "Full Screen" if you choose "Hide Toolbar" here:
<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/fe763bd6-e8fe-442f-8a39-714294872ee9" />
<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/0f1708f5-a8a3-441b-91ed-6b9e00f08193" />

3. You can always install the PWA to get even more screen space

**Closed by TylerLeonhardt** 2024-12-17 03:29 UTC
Labels: bug, upstream, web, upstream-issue-linked, ios-ipados

**Comment by TylerLeonhardt** [comment] 2024-12-17 03:34
Verification:
* Toggle Zen mode in insiders.vscode.dev
* Verify it does what is expected besides going Full Screen
