### ISSUE TITLE
Strange documentation dialog fickering

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#26654] opened 2017-05-15 12:42 UTC
- VSCode Version:

Version 1.13.0-insider
Commit f6ab171ab619a988b84fd1b91bb76e65847115a2
Date 2017-05-12T06:28:04.981Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

1. I somehow had an extra vscode running in the background, not sure how it became a zombie

Refer to the behaviour here
![anim](https://cloud.githubusercontent.com/assets/452518/26058122/0b893628-399a-11e7-85c2-d1d1d2505f50.gif)

**Comment by thekalinga** [comment] 2017-05-15 12:44
After I took the screenshot, I tried closing everything. Even after all instances of vscode are closed, still there was a vscode insiders instance running in the background, not sure why/how it was pushed to background

**Comment by mjbvz** [comment] 2017-05-18 01:23
First, can you please make sure an extension is not the root cause by starting code with the `--disable-extensions` command line flag

If you still see this issue, please try collecting the typescript server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

The trace may help us understand what is going on here

**Comment by mjbvz** [comment] 2017-05-24 21:30
Closing as we need more information to investigate this

**Closed by mjbvz** 2017-05-24 21:30 UTC
Labels: needs more info
