### ISSUE TITLE
Debugger not able to directly step into the function

### ISSUE THREAD

**Issue by m-salman-afzal** [microsoft/vscode#179781] opened 2023-04-12 14:01 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.77.2
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Start debugging from scripts in side-bar.
2. place breakpoint anywhere.
3. try going inside a function but clicking _step into_ 
4. You will get the following debug info on side panel and the function call is not invoked. You have to manually place breakpoint inside that function and play to stop.

![image](https://user-images.githubusercontent.com/53542416/231480969-e55becd0-f523-4217-b525-8fa7110711cb.png)

**Comment by connor4312** [comment] 2023-04-12 17:22
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1643, via the same underlying root cause. Fixed in [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) already!

**Closed by connor4312** 2023-04-12 17:22 UTC
