### ISSUE TITLE
Incorrect comment type for jsx 

### ISSUE THREAD

**Issue by ClimbYU** [Microsoft/vscode#38011] opened 2017-11-10 01:32 UTC
before：

```
{/* <div className="swiper-slide">slider1</div>
                        <div className="swiper-slide">slider2</div>
                        <div className="swiper-slide">slider3</div> */}
```

now

```
 // <div className='swiper-container swiper-pagination-bottom'>
                //   <div className='swiper-wrapper'>
                //         {navSwiper}
```

**Comment by mjbvz** [comment] 2017-11-10 01:46
Please describe:

1. What is that starting code?
1. What do you have selected when commenting it?
1. How do you comment it?

**Comment by Annaliang-web** [comment] 2017-11-10 05:00
I have this problem, too. Is it because React updated yesterday?

**Comment by h3w8529** [comment] 2017-11-10 07:11
@Annaliang-web no, is not cause by the yesterday update, i facing this issue since last month.

@mjbvz inside the react render function, i just select the component that i want to comment it. by using ctrl + / in windows and command + / in mac

**Comment by mjbvz** [comment] 2017-11-10 18:47
Please share the information requested so that I can investigate this

**Comment by blankPen** [comment] 2017-11-13 10:13
oops，I have this problem when i updated.
Example: 
```
// starting
class Demo extends Component {
  render() {
    return (
      <div>
        <Content>
          balabalabla...
        </Content>
      </div>
    )
  }
}
// Selected <Content/> and using  command + /


// result
class Demo extends Component {
  render() {
    return (
      <div>
        // <Content>
        //   balabalabla...
        // </Content>
      </div>
    )
  }
}
```

**Comment by mjbvz** [comment] 2017-11-13 20:54
Here's what I see in a js file:

![nov-13-2017 12-53-14](https://user-images.githubusercontent.com/12821956/32748611-a5cba30e-c871-11e7-87a8-07e895f33ed0.gif)

I just pasted the code into a blank js file (language mode `javascript`) and used cmd+/ to comment it. Anything I am missing? Also, can you please try disabling all extensions to make sure one of them is not causing this

**Comment by chuyinweilai** [comment] 2017-11-14 10:58
I have the same problem,
1. This is the all code in page
![image](https://user-images.githubusercontent.com/21523040/32776340-2e1beca4-c96d-11e7-9b86-480f6c7d74a9.png)

2.This is what I did
![2](https://user-images.githubusercontent.com/21523040/32776317-1f4eaf68-c96d-11e7-8437-31a4543e0ca0.gif)

3.And this is my System environment
![image](https://user-images.githubusercontent.com/21523040/32776515-c4a90990-c96d-11e7-887a-2bef854086e9.png)

**Comment by mjbvz** [comment] 2017-11-15 19:40
@chuyinweilai  What is the language mode of the file? Also does this still happen if you disable all extensions?

**Comment by KenFront** [comment] 2017-11-23 13:03
I remove the "Babel ES6/ES7" plugin to resolve this problem.

**Comment by chuyinweilai** [comment] 2017-11-24 06:06
@mjbvz I had solved the problem by @KenFront 's way. It's very useful!

**Comment by mjbvz** [comment] 2017-11-27 23:10
Ok, closing as caused by extension. Please file an issue against the babel extension to get this fixed

**Closed by mjbvz** 2017-11-27 23:10 UTC
Labels: javascript, languages basic, needs more info
