### ISSUE TITLE
Cannot find module 'lodash' after extension upgrade

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#44709] opened 2018-02-28 07:31 UTC
Vetur also uses lodash and this has been reported many times: https://github.com/vuejs/vetur/issues?utf8=%E2%9C%93&q=is%3Aissue+lodash+is%3Aclosed+

Earliest report is https://github.com/vuejs/vetur/issues/251 at 1.13.1.

So today I'm seeing this error in dev console, and Vim is not loading.
VS Code Insider: 3fec61014742dec894b3a31cdf8556bf533cb0e1
macOS 10.12.6.

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host]% Object (at Object.writeFile (/Users/pine/.vscode-insiders/extensions/Equinusocio.vsc-material-theme-1.4.2/extensions/helpers/fs.js:98:13))
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Activating extension 'vscodevim.vim' failed: Cannot find module 'lodash'. (at Object.showMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:690:704))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Activating extension `vscodevim.vim` failed:  Cannot find module 'lodash' (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:87)
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Here is the error stack:  Error: Cannot find module 'lodash'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:712)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/pine/.vscode-insiders/extensions/vscodevim.vim-0.11.0/out/src/taskQueue.js:11:11)
	at Object.<anonymous> (/Users/pine/.vscode-insiders/extensions/vscodevim.vim-0.11.0/out/src/taskQueue.js:85:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:712)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46) (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:155)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2839 Activating extension 'vscodevim.vim' failed: Cannot find module 'lodash'.
O._logMessageInConsole @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2839
```

![image](https://user-images.githubusercontent.com/4033249/36774899-ba1003ae-1c14-11e8-9645-a9b2b9bd2d96.png)

Vim is reporting 0.11.0. And I could find the lodash dependency installed correctly at `/Users/pine/.vscode/extensions/vscodevim.vim-0.11.0/node_modules/lodash`.

@sandy081 I'll be up early so let me know if you want to debug through this together.
@joaomoreno Does the `patchedRequire` give you any hint as to why this might happen?

**Comment by egamma** [comment] 2018-02-28 08:50
@octref can you check whether the extension is fully installed. This reminds me to issue #43813.

**Comment by sandy081** [comment] 2018-02-28 14:55
Yes this is a duplicate of #43813

**Closed** 2018-02-28 14:56 UTC
Labels: *duplicate, extensions
