### ISSUE TITLE
Improve startup performance

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#35955] opened 2017-10-10 05:33 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
xml|Dot|1.9.2
luaide|kan|0.4.8
MagicPython|mag|1.0.12
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
mysql-inline-decorator|odu|0.0.4
proto|pet|0.0.2
vscode-icons|rob|7.15.0
cmake|twx|0.0.17

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-10 06:37
Duplicate of #33859

**Closed by egamma** 2017-10-10 06:37 UTC
Labels: duplicate, perf
