### ISSUE TITLE
Load current color for color picker theme

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#91641] opened 2020-02-27 01:22 UTC
In setting when I want to set a color in `"workbench.colorCustomizations"` its load `"#ff0000"` not current color of theme.
Maybe I want to change the color a bit. I don't know exactly what the color is.

**Comment by roblourens** [comment] 2020-02-27 17:15
Sorry I don't quite understand what you're asking for, please explain more.

**Comment by fakhamatia** [comment] 2020-02-27 20:13
For example, I want to change `debugIcon.continueForeground` color, the default color is `#75BEFF`, But I don't know it before.
When I type `debugIcon.continueForeground` and pressed Enter its load `#ff0000` for default color. its load `#ff0000` for every color in `workbench.colorCustomizations`, not current color, I just wanted to change it a little bit.

![Peek 2020-02-27 23-41](https://user-images.githubusercontent.com/20030910/75482800-c14c1780-59ba-11ea-9691-27a3078fceb2.gif)

**Comment by roblourens** [comment] 2020-02-28 17:49
Oh ok so you want it to default to the current theme's color, got it

**Comment by aeschli** [comment] 2020-03-02 08:23
duplicate of https://github.com/microsoft/vscode/issues/25633

**Closed by aeschli** 2020-03-02 08:23 UTC
