### ISSUE TITLE
problemPattern endCharacter off by one

### ISSUE THREAD

**Issue by dlech** [microsoft/vscode#29959] opened 2017-06-30 16:44 UTC
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Write a problemMatcher for the vala compiler

  ```json 
      {
        "name": "valac",
        "owner": "vala",
        "fileLocation": "absolute",
        "pattern": {
          "regexp": "^(.*):(\\d+)\\.(\\d+)-(\\d+)\\.(\\d+):\\s+(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "endLine": 4,
          "endColumn": 5,
          "severity": 6,
          "message": 7
        }
      }
  ```

2. Write some vala code with an error and compile it using a task with the problem matcher above.

3. Observe that vscode marks one less character than the vala compiler output. For example, vscode only underlines `va` but the vala compiler underlines `var`.

  ![selection_014](https://user-images.githubusercontent.com/963645/27745356-9f50aa6e-5d88-11e7-9c63-4da9ee852c47.png)

Reproduces without extensions: Yes

---

Apparently, the vala compiler considers the end column inclusive while vscode considers it exclusive. It seems reasonable to add a bool parameter to allow handling of both cases.

**Comment by Gama11** [comment] 2017-07-08 16:42
This is similar to https://github.com/Microsoft/vscode/issues/7918 - problem matchers in general seem rather inflexible...

**Comment by alexr00** [comment] 2019-10-16 10:44
duplicate of https://github.com/microsoft/vscode/issues/7918

**Closed** 2019-10-16 10:45 UTC
Labels: *duplicate, feature-request, tasks
