### ISSUE TITLE
Duplicate entries shown in VS Code intellisense whenever type definitions (@types) are installed

### ISSUE THREAD

**Issue by rajeshramabathiran** [Microsoft/vscode#23180] opened 2017-03-24 20:58 UTC
- VSCode Version: 1.10.2
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Create a folder and open it in VS Code
2. Initialize npm, via npm init
3. Install a few packages, along with its type definition

`npm install --save-dev mocha chai chai-http`
`npm install --save-dev @types/mocha @types/chai @types/chai-http`

4. Create a typescript file, and import one of the modules. 

Current behavior:
VS Code intellisense shows duplicate entries while showing intellisense
<img width="666" alt="vscode intellisenseissue duplicates" src="https://cloud.githubusercontent.com/assets/4255513/24313301/8409a5da-1099-11e7-8e7c-4faf4ba98596.png">

Expected behavior: 
Avoid duplicate entries while showing intellisense.
(Note: This issue does not happen if @types packages isn't installed)

**Comment by mjbvz** [comment] 2017-03-24 21:43
Duplicate of this issue tracked upstream on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/13373

**Closed by mjbvz** 2017-03-24 21:43 UTC
Labels: duplicate, upstream
