### ISSUE TITLE
Scroll up/down with touchpad does not work

### ISSUE THREAD

**Issue by tiagotom** [Microsoft/vscode#25066] opened 2017-04-20 06:48 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Handlebars|andrejunges|0.2.0|
|ACF-Snippet|anthonydiametrix|1.7.2|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.12.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.5|
|php-pack|felixfbecker|1.0.1|
|vsc-ember-cli|felixrieseberg|0.3.3|
|laravel-blade|KTamas|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|searchdocsets-vscode|silverlakesoftware|0.5.2|
|wordpress-snippet|tungvn|1.1.2|;

---

Steps to Reproduce:

1.VS Code open
2.On any view with a scroll bar, using the touchpad with two fingers to scroll up/down, no action.

**Comment by CherryDT** [comment] 2017-04-21 09:53
Works fine for me. I don't think applications can really differentiate between touchpad, trackpoint, mouse wheel, other scroll events and such, unless the driver does something funky.

So it would be interesting to know what touchpad vendor and model you have and on what laptop (if any), plus your driver version.

**Comment by tiagotom** [comment] 2017-04-21 16:11
Hi. Yes, works great with the mouse. 

The touchpad drivers are from ASUS Smart Gesture and already updated to latest version (currently @4.0.18).

Hope to see if someone else here with Asus can comment.

**Comment by rasenplanscher** [comment] 2017-07-19 13:17
I just had a similar issue. In the process of writing a new issue (it only broke for scrolling upwards), I ran Code with this: `code --disable-extensions`

After that, it worked. Still working after restarting **with extensions**.

**Comment by keeed** [comment] 2017-11-04 05:08
I have an ASUS Smart Gesture as well and is also encountering the same problems :(

I tried @rasenplanscher 's approach but still broken for me :(

**Comment by keeed** [comment] 2017-11-05 05:24
[Update]

I tried installing vscode x64 and its now working :)

**Comment by bpasero** [comment] 2017-11-14 17:46
Still happening?

**Comment by keeed** [comment] 2017-11-14 20:02
Not sure if it is still hapening on vscode x32.

I gave up on the x32 one and updated to the vscode x64.

Scrolling works perfectly fine on x64.

If you need me to test it on x32 again, I’ll be happy to uninstall the x64 and try it on x32. :)

**Comment by hoetz** [comment] 2017-12-23 11:16
I often have the same issue on my Surface Book 2. As soon as I change the window size and switch back to maximize it starts working again.
![image](https://user-images.githubusercontent.com/3835948/34319158-14400658-e7db-11e7-9e04-5487f2654877.png)

**Comment by JoelLisenby** [comment] 2018-01-11 23:02
I am having the same issue where scrolling does not animate (appears to jump to the point where I release scrolling) when I start VSC maximized. Minimizing fixes the issue, and scrolling continues to work correctly upon maximizing after minimizing.

This is happening on an ASUS GL502VS laptop.

Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by karray** [comment] 2018-01-13 17:19
The touchpad on my Surface Pro scrolls jumpy after update to 1.19.2

**Comment by bpasero** [comment] 2018-02-06 14:25
Closing as duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by bpasero** 2018-02-06 14:25 UTC
Labels: needs more info, trackpad/scroll, upstream
