### ISSUE TITLE
Strange behavior in Links of md Files

### ISSUE THREAD

**Issue by herbertmeieriek** [microsoft/vscode#157515] opened 2022-08-08 13:52 UTC
Type: <b>Bug</b>

After Update to 1.70.0
Possible Bug

  Clicking on a Link without Keyboard STRG ist not possible anymore in md (markdown Files)

  Show Code Action ist new in Editor after marking a Text in md Files 

  After Following a Link in a markdown Link and change something in the File a new editor with the same name ist coming in the editor

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (11.18GB free)|
|Process Argv|--crash-reporter-id 796f2caf-87ff-469f-809e-0128facf6b32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
printcode|nob|3.0.0
pdf|tom|1.2.0

</details>

**Comment by mjbvz** [comment] 2022-08-08 18:22
Duplicate of #157260

**Closed by mjbvz** 2022-08-08 18:22 UTC
Labels: new release
