### ISSUE TITLE
JS incorrectly highlights template strings syntax

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#90821] opened 2020-02-17 13:16 UTC
- VSCode Version: 1.42.1; 1.43.0-insider
- OS Version: win7

### What

VSCode JS/TS syntax highlighter doesn't parse template strings correctly in special circumstances:

![image](https://user-images.githubusercontent.com/5153846/74657131-dee5d980-518f-11ea-83f4-edd72a08762b.png)

### Steps to Reproduce:

enter this JS code:

```
if ( !/\(/.test("a") ) {} // negation of a regex necessary

if ( true ) {
    obj[prop]; // obj property access inside a conditional necessary
}

const str = `template:string`;
//               \_ not recognized as template string (the colon is necessary)

// VSCode thinks *this* is template string
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-02-18 16:35
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-02-18 16:35 UTC
