### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by asontha** [microsoft/vscode#103134] opened 2020-07-23 05:45 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99888:161)
    at resolveModuleNamesWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:100255:19)
    at processImportedModules (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101668:35)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101411:17)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101638:21
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101633:16)
    at findSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101408:21)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101207:34)
    at processSourceFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101240:13)
    at processRootFile (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:101063:13)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:60
    at Object.forEach (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99987:16)
    at synchronizeHostData (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138726:26)
    at Proxy.getProgram (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146581:44)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:97
    at Object.flatMap (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147763:46)
    at /private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/private/var/folders/_8/xtfm34q179zc5vtfmn2t6n840000gn/T/AppTranslocation/B63365EE-43F0-4107-95B4-303243A27E0F/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 6|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1000.4
angulardoc-vscode|Ang|6.1.3
path-intellisense|chr|2.2.1
angular-schematics|cyr|4.3.0
vscode-eslint|dba|2.1.8
vscode-deno|den|1.25.0
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
json2ts|Gre|0.0.6
angular2-switcher|inf|0.3.3
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
angular-extension-pack|loi|0.7.1
Angular2Tests|Mar|0.7.3
vscode-docker|ms-|1.4.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
ng-fortytwo-vscode-extension|NG-|0.0.9
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.2.0
typescript-hero|rbb|3.0.0
simontest|Sim|1.8.8
autoimport|ste|1.5.3
move-ts|str|1.12.0
Angular2|UVB|0.4.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-07-23 18:00
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by asontha** [comment] 2020-07-24 04:42
Nope, doesn't seem to

**Comment by mjbvz** [comment] 2020-07-24 04:53
Thanks for checking. The deno extension in particular has been causing issues. Can you please check to see if it is the root cause of this crash? If so, please file an issue agains that extension so they can look into fixing this

**Comment by mjbvz** [comment] 2020-07-30 00:06
Closing as like caused by extension  based on feedback

**Closed by mjbvz** 2020-07-30 00:06 UTC
Labels: needs more info
