### ISSUE TITLE
Aux window disrupts command palette 

### ISSUE THREAD

**Issue by MrYuto** [microsoft/vscode#195870] opened 2023-10-18 06:11 UTC
Repro:
1. Open a text editor
2. Pop out
3. Close the editor from command palette command: `View: Close editor`

![Code_Vnl83t5xI4](https://github.com/microsoft/vscode/assets/75252297/ac760e4e-215a-4d5a-aec6-80ea2cc5d9a4)

Sometimes when I open (or close?) an aux window, it disrupts the functionality of the command palette. ~Unfortunately, I'm unable to provide precise steps to reproduce this issue, making it even more challenging to address.~

**Things I know:**
1. You can open the command palette, and navigate using arrow keys.
2. When you run a command, there is no response.
3. No errors in the console.

Given that I've encountered this problem while only spending a short time testing auxiliary windows, I suspect it could affect other users as well.

**Comment by bpasero** [comment] 2023-10-18 06:16
Can you clarify what you observe?

**Comment by MrYuto** [comment] 2023-10-18 06:21
I added a section for things I know and will update with more information if I can reproduce the bug again.

**Comment by bpasero** [comment] 2023-10-18 06:24
There have also been quite some changes around avoiding global `window` and `document` and rather pick the right ones based on the context, so its possible that this issue has been fixed in todays insider already.

**Comment by MrYuto** [comment] 2023-10-18 06:30
I encountered the bug while running 5cbc3f8 to test #195846

**Comment by bpasero** [comment] 2023-10-18 06:40
Oh ok, so you are running out of sources actually and not insiders. But yeah, that should not make any difference.

**Comment by MrYuto** [comment] 2023-10-18 07:18
Good news! I just found a **stable** way to reproduce the bug.

**Comment by bpasero** [comment] 2023-10-18 07:38
Thanks I can reproduce:
* pop up an editor
* just trigger quick commands once in float window
* close that window
* trigger quick command in main window
* 🐛 no action can be triggered

@Tyriar I suspect an issue with the change you did around moving the container of quick pick? Though I had thought that each time quick pick opens, the container would be updated, and it seems to be that way given it opens fine.

**Comment by IllusionMH** [comment] 2023-10-18 07:42
A bit off topic (but behavior observed in video): is there some public plan/to-do list of Aux Windows features? Because iteration plan links locked issue that has no updates.

As I've noticed problem to report (open recent called from aux window opens in main instead, Go to file works as expected) and feature request (close wit last editor closed), but not sure if they are already in to-do or should I create issues.

**Comment by bpasero** [comment] 2023-10-18 08:13
@IllusionMH thanks for bringing this up, we do have a private issue where we have just collected some random ideas how to proceed, but I think its not something that would be helpful to share in the public.

I would prefer if people report issues as they encounter them, similar to what MrYuto has been doing. We have the `workbench-auxwindow` label to triage.

One thing to keep in mind is that there are some larger items just not implemented yet:
* there is no custom title bar in floating windows
* there is no status bar in floating windows
* `iframe` based editors are unsupported currently: https://github.com/microsoft/vscode/issues/195715

So feel free to report anything you find! We will probably broaden the scope soon and invite people from the main issue to test too.

**Comment by bpasero** [comment] 2023-10-18 09:35
@IllusionMH I am now converting some of our internal notes to public issues, check out https://github.com/microsoft/vscode/labels/workbench-auxwindow

**Comment by alexandruavadanii** [comment] 2023-10-18 21:02
I don't want to hijack this ticket, but it would be nice to know what limitations to expect before creating new tickets - I assume some extensions will also require serious changes.
e.g. using `HoverProvider` on some text decorations (similar to what GitLens does with its inline blame/annotations) does not work in the Aux window.

**Comment by bpasero** [comment] 2023-10-19 04:17
@alexandruavadanii please go ahead and report it, that sounds like a bug to me. It is true that for extensions there is currently no new API to detect aux windows, but everything should work the same it did before.

I can only suspect that maybe GitLens uses a custom font or icons for some features and some Content-Security-Policy or CSS issue or similar prevents these to load from the aux window.

**Comment by alexandruavadanii** [comment] 2023-10-19 07:55
@bpasero thanks, I created https://github.com/microsoft/vscode/issues/195969

**Comment by bpasero** [comment] 2023-10-23 06:35
For some reason, when an `HTMLElement` is attached to a window that is closed, functionality is quite broken, I suspect that DOM event listeners might stop to work unrecoverably. Here is what happens:
* quick open is rooted in the child window
* child window closes
* quick open is still rooted in the child window (now detached?)
* listeners do not work anymore

I am pushing a change to have a `onWillUnregisterWindow` that fires from a `beforeunload` event of the child window to move the quick open container back into the main window.

**Closed** 2023-10-23 07:12 UTC
Labels: bug, confirmed, quick-open, workbench-auxwindow
