### ISSUE TITLE
Can't hit breakpoint in extension `activate` method

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#112052] opened 2020-12-07 23:18 UTC
Steps:
1. Using our yeoman generator, create a new typescript project (webpack or not doesn't matter)
1. Open the new folder in VS Code, and open `src/extension.ts`
1. Set a breakpoint at the first `console.log`
1. Press `F5`
1. :bug: No breakpoint will be hit

If you put a breakpoint in the command callback it works fine, its just that we seem to not be attaching fast enough.

This is not a great getting started experience.

**Comment by connor4312** [comment] 2020-12-07 23:19
What version of js-debug are you using, and can you grab logs? This should be fixed in recent versions provided outFiles is set up appropriately.

/jsDebugLogs

**Comment by eamodio** [comment] 2020-12-07 23:23
Built-in to today's insiders -- says `v1.52.1`. Can you grab the logs on this one? The steps are a clean setup from our generator.

**Closed** 2020-12-07 23:48 UTC
Labels: bug, candidate, debug

**Comment by weinand** [comment] 2020-12-08 10:48
@connor4312 I'm not hitting any breakpoint with latest macOS Insiders (1.52.0) on first run.

Here are my steps:
- Using yeoman generator, create a new typescript project (no webpack)
- Open the new folder in VS Code, and open src/extension.ts
- Set a breakpoint on both console.log
- Press F5
- in new VS Code instance press F1 and type "hello"; run "hello action"

Observe: No breakpoint is hit

- running "hello action" again does hit the second breakpoint.

**Comment by weinand** [comment] 2020-12-08 14:26
@connor4312 I've verified that version 1.52 of js-debug fixes the problem for me.

BTW, when running VS Code out of source I could not reproduce the problem. 
To verify the fix in js-debug 1.52, I have installed the vsix into Insiders.

**Comment by weinand** [comment] 2020-12-08 14:38
I will verify as soon as a build is out...

**Comment by connor4312** [comment] 2020-12-08 16:01
Yea, it appears to be timing related. I could not repro on my machine unless I inserted an artificial delay in a certain step in js-debug

**Comment by weinand** [comment] 2020-12-08 16:36
Could no longer reproduce issue in latest Insiders (6f933020e8dd4ea046eae2bcfc59a18edf2bc517) - verified!

**Comment by eamodio** [comment] 2020-12-08 16:42
Same for me!

**Comment by connor4312** [comment] 2020-12-08 16:42
Thanks for confirming!
