### ISSUE TITLE
Keyboard shortcut's fire intermittently when Webview's are active

### ISSUE THREAD

**Issue by bahung1221** [microsoft/vscode#112454] opened 2020-12-14 10:29 UTC
Hi,

I facing a problem that I can't open **command palette** by press `cmd + shift + p`, it usually happens after one or more keystrokes.
It happen when I opened a VSCode extension that use webview to render their content ([Git Graph](https://github.com/mhutchie/vscode-git-graph) for example).
Git Graph author has described this issue here: https://github.com/mhutchie/vscode-git-graph/issues/434#issuecomment-744312907

Steps to Reproduce:

1. Open Git Graph or any extension that use webview to render their content
2. Press `cmd + shift + p` (macOs)
3. Press `esc`
4. Press `cmd + shift + p` again (nothing appeared here)

![Screen-Recording-2020-12-14-at-1](https://user-images.githubusercontent.com/27690861/102070296-832cc100-3e31-11eb-8a25-f95ba544355b.gif)

- VSCode Version: 1.52.0
- OS Version: macOs 11.0.1 (Big Sur)

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment] 2020-12-18 00:06
Duplicate of #110276

**Closed by mjbvz** 2020-12-18 00:06 UTC
