### ISSUE TITLE
Multi threaded apps are now seeing a Stacktrace for each thread when stopping occurs

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#68648] opened 2019-02-13 19:34 UTC
Issue Type: <b>Bug</b>

Multithreaded app is now seeing a stacktrace request for each thread when a stopping event occurs, even when thread is not expanded in the callstack window. For a multithreaded app, this can be very expensive. This is a change in behavior from 1.30.2.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (10.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.8.0
cpptools|ms-|0.22.0-insiders
csharp|ms-|1.17.1
vscode-docker|Pet|0.5.2
azure-iot-edge|vsc|1.9.0
azure-iot-toolkit|vsc|2.2.0

</details>

**Comment by pieandcakes** [comment] 2019-02-13 19:38
[testapp.zip](https://github.com/Microsoft/vscode/files/2861864/testapp.zip)
* Compile app
* Add app args '-fThreading'
* Set a breakpoint on Threading.cpp:29
* Launch

Expected to stop at bp and only receive a stacktrace for the stopping thread. Actually getting a stack trace for all threads.

**Comment by pieandcakes** [comment] 2019-02-13 19:40
Customer's scenario has 250 threads and has seen a spike in time it takes when debugging hits a breakpoint.

**Comment by pieandcakes** [comment] 2019-02-13 19:43
@vscodebot that is not the same issue. Thanks

**Comment by isidorn** [comment] 2019-02-25 14:49
@pieandcakes thanks for reporting this issue. However please note that I am pretty clueless when it comes to c++, so the following step "Compile app" is giving me issues.
I am trying to compile with `g++ threading.cpp` and I get a bunch of errors

Can you please give me nice steps so I can follow them step by step and get into this situation. Please note that I am on the mac.

Also can you reproduce with latest vscode insiders since I could not reproduce this issue if I emulated it using node debugging?

```
In file included from threading.cpp:1:
./threading.h:24:28: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
    int runningThreadCount = 0;
                           ^
threading.cpp:55:12: error: no matching constructor for initialization of 'std::__1::thread'
    thread A(ThreadLoop, this, 3, "A-Blue");
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:408:9: note: candidate constructor template not viable: requires single argument '__f', but 4 arguments were provided
thread::thread(_Fp __f)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:289:5: note: candidate constructor not viable: requires 1 argument, but 4 were provided
    thread(const thread&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:296:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
    thread() _NOEXCEPT : __t_(_LIBCPP_NULL_THREAD) {}
    ^
threading.cpp:56:12: error: no matching constructor for initialization of 'std::__1::thread'
    thread B(ThreadLoop, this, 2, "B-Green");
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:408:9: note: candidate constructor template not viable: requires single argument '__f', but 4 arguments were provided
thread::thread(_Fp __f)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:289:5: note: candidate constructor not viable: requires 1 argument, but 4 were provided
    thread(const thread&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:296:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
    thread() _NOEXCEPT : __t_(_LIBCPP_NULL_THREAD) {}
    ^
threading.cpp:57:12: error: no matching constructor for initialization of 'std::__1::thread'
    thread C(ThreadLoop, this, 0, "C-Orange");
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:408:9: note: candidate constructor template not viable: requires single argument '__f', but 4 arguments were provided
thread::thread(_Fp __f)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:289:5: note: candidate constructor not viable: requires 1 argument, but 4 were provided
    thread(const thread&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:296:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
    thread() _NOEXCEPT : __t_(_LIBCPP_NULL_THREAD) {}
    ^
threading.cpp:58:12: error: no matching constructor for initialization of 'std::__1::thread'
    thread D(ThreadLoop, this, 1, "D-Red");
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:408:9: note: candidate constructor template not viable: requires single argument '__f', but 4 arguments were provided
thread::thread(_Fp __f)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:289:5: note: candidate constructor not viable: requires 1 argument, but 4 were provided
    thread(const thread&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:296:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
```

**Comment by isidorn** [comment] 2019-02-26 16:32
Thanks to @joaomoreno and @weinand I could compile
For future reference `clang++ -g -std=c++11 *.cpp -o sink.out` and `"MIMode": "lldb"` in `launch.json`

The issue here is that the Tree is calling getChildren on elements which are collapsed we refreshing the whole tree. Thus assigning this issue also to @joaomoreno 

@pieandcakes please confirm that the actual issue here is that the collapsed threads are sending a `stackTrace` request. Collapsed threads should not send out any request. And that is the actual regression.

**Comment by pieandcakes** [comment] 2019-02-26 17:24
@isidorn That is correct. We are getting a `stackTrace` request for all threads, including the collapsed ones, which seems to be a regression.

**Comment by joaomoreno** [comment] 2019-02-26 22:49
> The issue here is that the Tree is calling getChildren on elements which are collapsed when refreshing the whole tree. Thus assigning this issue also to @joaomoreno

@isidorn If you place the breakpoint in [here](https://github.com/Microsoft/vscode/blob/a9eeeab8d877914e1359a8d015d3dfb10e29addc/src/vs/workbench/contrib/debug/electron-browser/callStackView.ts#L596) you'll notice that the call stack data source only gets asked to `getChildren` for the debug model and the active thread. It never gets asked about the other, collapsed threads.

**Comment by joaomoreno** [comment] 2019-02-27 11:34
I was wrong. It is in the tree. I failed to press `Continue` once and notice all the stack traces expanded. Sorry @isidorn!

**Closed** 2019-02-27 11:36 UTC
Labels: bug, debug, regression

**Comment by isidorn** [comment] 2019-02-27 11:56
I confirm this is behaving better with the fix.
However there is still this case which we will not cover in the endgame https://github.com/Microsoft/vscode/issues/69526
So bascially if a user manually collapses something we would still fetch children for that element.
