### ISSUE TITLE
Not able to sync settings

### ISSUE THREAD

**Issue by Juggern4ut** [microsoft/vscode#92332] opened 2020-03-10 09:21 UTC
Issue Type: <b>Bug</b>

My settings don't sync and whenever I reopen VS Code Insiders it will reset my settings to default. 

I'll get the following output in the sync-output.

```
[2020-03-10 10:16:34.859] [userDataSync] [info] Auto Sync: Triggered.
[2020-03-10 10:16:35.232] [userDataSync] [error] TypeError: Cannot read property 'configurationSync.store' of null
    at h (file:///C:/Users/LukasMeier/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:433:842)
    at Object.t.merge (file:///C:/Users/LukasMeier/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:438:639)
    at e.generatePreview (file:///C:/Users/LukasMeier/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:446:831)
[2020-03-10 10:16:35.232] [userDataSync] [error] Settings: Cannot read property 'configurationSync.store' of null
[2020-03-10 10:16:35.549] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-03-10 10:16:35.554] [userDataSync] [info] UI State: No changes found during synchronizing ui state.
[2020-03-10 10:16:35.631] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-03-10 10:16:35.631] [userDataSync] [info] Sync done. Took 772ms
```

My settings.json includes only very basic settings so I don't think it should be a problem here.
```
{
    "telemetry.enableTelemetry": false,
    "editor.fontSize": 12,
    "workbench.editor.tabCloseButton": "off",
    "editor.wordWrap": "off",
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "editor.renderControlCharacters": false,
    "workbench.iconTheme": "vscode-icons",
    "sync.ignoredExtensions": [
        "box-of-hats.bemhelper"
    ]
}
```

VS Code version: Code - Insiders 1.44.0-insider (1876b51870e30e9ba8f35dc0dcfaf49a3799a8ef, 2020-03-09T19:46:29.230Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
bemhelper|Box|0.8.0
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
git-graph|mhu|1.21.0
sublime-keybindings|ms-|4.0.6
vscode-icons|vsc|10.0.0

</details>

**Comment by sandy081** [comment] 2020-03-11 16:25
Can you please enable log level to `trace` using command `Set Log Level` from command pallette and provide us the logs with trace data?

**Comment by JamieBriersSageCom** [comment] 2020-03-13 10:36
I am having the same problem, here are my logs @sandy081 
```
[2020-03-13 10:36:07.548] [userDataSync] [info] Auto Sync: Triggered.
[2020-03-13 10:36:07.548] [userDataSync] [trace] Sync started.
[2020-03-13 10:36:07.548] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","type":"GET","headers":{"Content-Type":"application/json"}}
[2020-03-13 10:36:07.718] [userDataSync] [trace] Request finished {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":200}
[2020-03-13 10:36:07.718] [userDataSync] [trace] Settings: Started synchronizing settings...
[2020-03-13 10:36:07.718] [userDataSync] [trace] Sending request to server {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","type":"GET","headers":{"Cache-Control":"no-cache","If-None-Match":"0"}}
[2020-03-13 10:36:07.875] [userDataSync] [trace] Request finished {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","status":304}
[2020-03-13 10:36:07.876] [userDataSync] [trace] Settings: Merging remote settings with local settings...
[2020-03-13 10:36:07.876] [userDataSync] [error] TypeError: Cannot read property 'configurationSync.store' of null
    at h (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:436:527)
    at Object.t.merge (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:441:310)
    at e.generatePreview (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:449:891)
[2020-03-13 10:36:07.876] [userDataSync] [error] settings: Cannot read property 'configurationSync.store' of null
[2020-03-13 10:36:07.876] [userDataSync] [trace] Keybindings: Started synchronizing keybindings...
[2020-03-13 10:36:07.877] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-03-13 10:36:07.877] [userDataSync] [trace] Keybindings: Finished synchronizing keybindings.
[2020-03-13 10:36:07.878] [userDataSync] [trace] GlobalState: Started synchronizing globalstate...
[2020-03-13 10:36:07.878] [userDataSync] [trace] GlobalState: Merging remote ui state with local ui state...
[2020-03-13 10:36:07.878] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-03-13 10:36:07.878] [userDataSync] [trace] GlobalState: Finished synchronizing globalstate.
[2020-03-13 10:36:07.878] [userDataSync] [trace] Extensions: Started synchronizing extensions...
[2020-03-13 10:36:07.913] [userDataSync] [trace] Extensions: Merging remote extensions with local extensions...
[2020-03-13 10:36:07.914] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-03-13 10:36:07.914] [userDataSync] [trace] Extensions: Finished synchronizing extensions.
[2020-03-13 10:36:07.914] [userDataSync] [info] Sync done. Took 366ms
[2020-03-13 10:36:09.169] [userDataSync] [info] Auto Sync: Triggered.
```

**Comment by jimseiwert** [comment] 2020-03-16 20:57
I had the same issue, turning sync off and back on worked for me. It asked if I wanted to replace my local file and I said yes.

**Comment by sandy081** [comment] 2020-04-01 20:37
@Juggern4ut @jimseiwert Did not find any root cause for this. Are you still able to repro it?

**Comment by jimseiwert** [comment] 2020-04-02 15:53
@sandy081 no, I was not able to find root cause or repo it. The fix was to turn off sync and set it back up. After that it continued to work just fine.

**Comment by sandy081** [comment] 2020-04-06 09:40
Ok. Since I can't repro it closing it for now. Please reopen it if you see it again and mention us the steps you did to get into this state.

**Closed by sandy081** 2020-04-06 09:40 UTC
Labels: needs more info, settings-sync

**Comment by AHBruns** [comment] 2020-04-18 13:14
I came across this same bug and followed the above steps to fix it. I was, of course, not able to repo it as a result. However, I did have VS Online open to the same remote that my VS Code Insiders was open to. @Juggern4ut did you have VS Online open at the time you ran into this bug? I know it was a while ago.
