### ISSUE TITLE
Building win32-ia32 succeeded, but Standalone executable doesn't manage to fully start (window opened, but empty)

### ISSUE THREAD

**Issue by OferRosenberg** [Microsoft/vscode#38808] opened 2017-11-20 18:44 UTC
- VSCode Version: 1.19.0
- OS Version: Windows 10 
- Git commit : f33a8b7b9ba903c5c15ccccf4af55ef8091fe263 (Sat Nov 18 08:30:46 2017)

Steps to Reproduce:

1. Run "yarn run watch" on one command line window
2. Wait for compilation to finish
3. Run "scripts\code.bat" on a second command line window
4. vscode window opens successfully, fully operational.
![vscode_via_code_bat](https://user-images.githubusercontent.com/33768003/33035151-02bda338-cddf-11e7-9601-c5b8cabf0717.PNG)

5. Close vscode window
6. From the second command line window, run "yarn run gulp vscode-win32-ia32"
7. gulp finishes without errors
[vscode_gulp_log.txt](https://github.com/Microsoft/vscode/files/1488734/vscode_gulp_log.txt)

8. Launching "Code - OSS.exe" from VSCode-win32-ia32 folder
9. vscode window opens empty (no content) and all File/Edit/etc menus don't work - menu opens up, but pressing on an option (like "Open File" doesn't do anything. BTW, some Help menu options like "about" does work :-)
![vscode_via_exe](https://user-images.githubusercontent.com/33768003/33035180-168fa44c-cddf-11e7-8a7f-38d7f9573112.PNG)

I've noticed the same issue opened few days ago and closed : https://github.com/Microsoft/vscode/issues/37575 
I looked at the solution that worked for chongchai (adding commit key to product.json) but this is not same as my issue, as in my product.json there is a commit key 
[product_json.txt](https://github.com/Microsoft/vscode/files/1488752/product_json.txt)

**Comment by OferRosenberg** [comment] 2017-11-21 00:06
An update to this issue : apparently, happening only for the win32-ia32 packaging. when building the win32-x64 package, the executable is working :-)

**Comment by joaomoreno** [comment] 2017-11-21 09:37
@OferRosenberg Try changing the commit ID to some other value. Does it work?

cc @jrieken for the `CachedData`

**Comment by OferRosenberg** [comment] 2017-11-22 17:40
Thanks. I've tried modifying the commit ID, it didn't help... 
BTW, the x64 version has the same json file (see comparison below) and its working. 
![product_json_compare](https://user-images.githubusercontent.com/33768003/33141768-083803cc-cf69-11e7-90c4-aea315701e8f.PNG)

**Comment by joaomoreno** [comment] 2017-11-23 08:40
Can you try using `--user-data-dir C:\some\directory`?

**Comment by chongchai** [comment] 2017-11-23 09:25
@OferRosenberg  Do you build x64 at first and then build ia32? Chane build target may need remove node_modules and .build folders. Just my guess.

**Comment by OferRosenberg** [comment] 2017-11-27 18:16
Thanks. I've tried both suggestions (change build order, and add user-data-dir). Either worked for me...
Maybe there some environment variable that I need to set ?

**Comment by joaomoreno** [comment] 2017-11-28 08:50
@OferRosenberg The problem is that the 32 and 64 bit releases are using the same user data dir and they use the same directory for [`CachedData`](https://github.com/Microsoft/vscode/blob/52c2843cc4fe44afe9e750b5713347c244e5d3d5/src/main.js#L134). You can either use a separate data dir, delete that previous `CachedData` folder or use `--no-cached-data`.

Closing since this doesn't affect us in production, since you can't install 32 and 64 bits simultaneously.

**Closed by joaomoreno** 2017-11-28 08:50 UTC
Labels: engineering, needs more info
