### ISSUE TITLE
Debug launching broken

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#58854] opened 2018-09-18 01:20 UTC
Issue Type: <b>Bug</b>

See also #58849

Version: 1.28.0-insider (user setup)
Commit: 7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef
Date: 2018-09-17T09:37:55.086Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Others on https://gitter.im/Microsoft/vscode reported the exact same issue, except that for them the fault occurred launching a C++ program, whereas for me it happened launching an aspnet core 2.1 application.

VS Code version: Code - Insiders 1.28.0-insider (7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef, 2018-09-17T09:37:55.086Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.44GB free)|
|Process Argv|C:\Users\PeterWone\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
gitlens|eam|8.5.6
dotnet-test-explorer|for|0.5.3
dotnet-core-essentials|Kis|0.0.5
tslens|Max|1.2.7
mssql|ms-|1.4.0
csharp|ms-|1.16.1
debugger-for-chrome|msj|4.10.1
debugger-for-edge|msj|1.0.5
html-preview-vscode|tht|0.1.1

</details>

![vscode1 28 0-insider](https://user-images.githubusercontent.com/5498936/45658864-e2a5a480-bb34-11e8-85ca-03a5169edb5e.PNG)

**Comment by octref** [comment] 2018-09-18 17:04
Duplicate of #58847

**Closed by octref** 2018-09-18 17:04 UTC
Labels: insiders
