### ISSUE TITLE
JSX linked editing breaks when modifying the tags too quickly

### ISSUE THREAD

**Issue by itsMapleLeaf** [microsoft/vscode#181769] opened 2023-05-07 19:02 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.79.0-insider (user setup)
Commit: 2c73d2651cc525b27fc697b820743098a204ec01
Date: 2023-05-04T22:11:08.187Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
Steps to Reproduce: Type a JSX opening or end tag very fast

https://user-images.githubusercontent.com/19603573/236697442-5f64c25c-017a-4f38-9629-f3fabd0e479a.mp4

**Comment by aeschli** [comment] 2023-05-09 21:36
duplicate of #180156

**Closed by aeschli** 2023-05-09 21:36 UTC
