### ISSUE TITLE
Selecting multiple files one of which is a shortcut

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#64501] opened 2018-12-06 10:16 UTC
Issue Type: <b>Bug</b>

* Create a shortcut to Desktop (Context menu => Send to => Desktop (create shortcut))
* Create ordinary file on Desktop `New Text Document.txt`
* Select both files
* Open with Code (From Context menu)

First try it tries to open the `.lnk` file: 
`The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?`

After the first try, all the next attempts it opens only 1 file (the shortcut).

---

Sublime Text handles it nicely.
Atom - has the same bug.

---

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment] 2018-12-06 13:18
Duplicate of https://github.com/Microsoft/vscode/issues/35085#issuecomment-332452409

**Closed by bpasero** 2018-12-06 13:18 UTC
