### ISSUE TITLE
Integrated terminal text is horionztally squished

### ISSUE THREAD

**Issue by Noitidart** [Microsoft/vscode#36068] opened 2017-10-11 14:02 UTC
- VSCode Version: 1.17.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open integrated terminal (Ctrl + `)

Reproduces without extensions: Yes

Image is attached showing squish.

## Here is how it looks now:

![how it looks now](https://user-images.githubusercontent.com/6372489/31444950-1710b354-ae52-11e7-8981-e7d7d84e64fc.jpg)

## This is how it used to look, expected look is this:

![how it used to look](https://i.imgur.com/zzSTc2c.png)

**Comment by gandhis1** [comment] 2017-10-11 14:17
I get this as well:

![image](https://user-images.githubusercontent.com/21064086/31445962-58bfacb8-ae6d-11e7-8fef-6f95e217f8e7.png)

The font looks extremely small and narrow. 

![image](https://user-images.githubusercontent.com/21064086/31445989-6b6fe77e-ae6d-11e7-8295-51fbb93ff735.png)

**Comment by Noitidart** [comment] 2017-10-11 14:19
I think it's related to the update, not sure, I updated a couple versions at once.

**Comment by carlosesilva** [comment] 2017-10-11 14:19
I am getting issues with my terminal setup as well.
![image](https://user-images.githubusercontent.com/6562179/31446084-aa873fd4-ae6d-11e7-99c8-758c2636f661.png)

**Comment by StanFisher** [comment] 2017-10-11 14:42
duplicate of #36059

**Comment by Tyriar** [comment] 2017-10-11 14:54
Duplicate Duplicate https://github.com/Microsoft/vscode/issues/35991

**Closed by Tyriar** 2017-10-11 14:54 UTC
Labels: integrated-terminal
