### ISSUE TITLE
VSCode crashes after snap update on Ubuntu 23.04

### ISSUE THREAD

**Issue by mischa-robots** [microsoft/vscode#214450] opened 2024-06-06 12:47 UTC
Does this issue occur when all extensions are disabled?: I don't know

- VS Code Version:
code --version
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64

- OS Version: Ubuntu 23.04 (6.2.0-39-generic)

Steps to Reproduce:

1. start computer, snap updates vscode automatically in the background
2. try to start vscode, it crashes
3. start from console with verbose:

```
...
[0606/143719.067897:ERROR:process_memory_range.cc(75)] read out of range
[10129:0606/143719.151781:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=133
[10129:0606/143719.151793:WARNING:gpu_process_host.cc(1364)] The GPU process has crashed 1 time(s)
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
[10245:0606/143719.217064:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[10129:0606/143719.218276:WARNING:gpu_process_host.cc(1015)] Reinitialized the GPU process after a crash. The reported initialization time was 49 ms
[0606/143719.227271:ERROR:process_memory_range.cc(75)] read out of range
...
```

Edit: I tried it also with `code --disable-extensions` but it has the same errors.
I think in the end this is the root cause:

```
[6449:0606/152418.533389:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
```

**Comment by jonnynux** [comment] 2024-06-06 13:10
Same problem here with Ubuntu 24.04, I just updated visual code and I cannot start it anymore, and cannot revert.

```
sudo snap revert code
error: cannot revert "code": no revision to revert to
```

**Comment by faabiopontes** [comment] 2024-06-06 13:11
Same with me, even with extensions disabled command. I removed the snap version and installed the deb one and it's working https://code.visualstudio.com/docs/setup/linux

**Comment by mischa-robots** [comment] 2024-06-06 13:29
> `sudo snap revert code` it works for me, ofc is a temporary solution

Thanks @rconautes  works for me.

**Comment by ooleon** [comment] 2024-06-06 13:39
in my case.
I download this version https://code.visualstudio.com/updates/v1_90
uninstall using app center.
sudo dpkg --install code_1.90.0-1717531825_amd64.deb 
and vualá.

**Comment by Duo3Rick** [comment] 2024-06-06 14:01
For me my snap auto updated too, but my ubuntu is 22.04.4 LTS

The suggestion of @ooleon and @AlefMemTav worked for me

**Comment by Rexogamer** [comment] 2024-06-06 14:18
I think this is a duplicate of #212494

**Comment by deepak1556** [comment] 2024-06-06 14:46
Merging to https://github.com/microsoft/vscode/issues/212494

**Closed by deepak1556** 2024-06-06 14:46 UTC
Labels: triage-needed

**Comment by RubTalha** [comment] 2024-06-09 10:37
https://stackoverflow.com/a/78588729/13086128

**Comment by manuito** [comment] 2024-06-10 08:27
Same problem here. Until fix it is still possible to start it with `code --in-process-gpu .`

**Comment by vandsonfalcao** [comment] 2024-06-10 17:35
> Same problem here. Until fix it is still possible to start it with `code --in-process-gpu .`

its works for me. thanks.

# System Details Report
---

## Report details
- **Date generated:**                              2024-06-10 14:35:22

## Hardware Information:
- **Hardware Model:**                              Lenovo Lenovo IdeaPad S145-15IIL
- **Memory:**                                      20,0 GiB
- **Processor:**                                   Intel® Core™ i5-1035G1 × 8
- **Graphics:**                                    Intel® UHD Graphics (ICL GT1)
- **Disk Capacity:**                               256,1 GB

## Software Information:
- **Firmware Version:**                            DKCN55WW
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.3.13-2-MANJARO

**Comment by mischa-robots** [comment] 2024-06-12 11:53
@deepak1556 please help me understand why this issue is closed:
- because there exist a similar issue for the "VS Code Version: 1.90.0-insider" ?
- because this issue has been solved with the next VSCode update ?

Just curious :)
