### ISSUE TITLE
Some icons are now displaying on VS Code

### ISSUE THREAD

**Issue by schallam** [Microsoft/vscode#10668] opened 2016-08-18 13:50 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Some of the icons like Extensions icon on left side, or when in debug mode, any of the icons next to debug dropdown are not displaying. IMP - The icons do exist as when I click on that point, the functionality works and also bubble text comes up if I pause curson for few seconds.

Steps to Reproduce:

1. Install VSC 1.3.1 (or previous versions)
2. Start VSC.

There is nothing special I am doing and this is the issue all the time. Other developers are not facing this issue. 

![image](https://cloud.githubusercontent.com/assets/16824651/17776096/c0caea94-6520-11e6-9552-c2b2a19b271e.png)

**Comment by mrmlnc** [comment] 2016-08-18 14:18
Have you tried this instruction http://code.visualstudio.com/docs/setup/windows#_common-questions?

**Comment by bpasero** [comment] 2016-08-18 14:24
And in 1.4?

**Comment by schallam** [comment] 2016-08-18 18:42
Thank you., This instruction worked. Appreciate your timely help.

**Comment by mrmlnc** [comment] 2016-08-18 19:12
@schallam,

If the issue is solved, then please close it.

**Closed** 2016-08-19 05:10 UTC
