### ISSUE TITLE
Glob regex is inefficient and can produce wrong results

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#5438] opened 2016-04-18 08:29 UTC
**Performance issue**:

`glob.match('**/bower.json',...)` results in:
 `/^(?:[\/\\]|[^\/\\]+[\/\\]|[\/\\][^\/\\]+)*?bower\.json$/`  which looks rather complicated.
It seems to work but runs in a timeout on a long content (I tried with the default content of http://regexr.com/)

So its a ('separator' or 'everything but a separator followed by a separator' or a 'separator followed by a everything but a separator') repeated and optional. A very complicated way of saying  /bower.json$/ 

**Updated comment from #6936**:

Then there other cases that are still far too complicated and inefficient. It looks like #5438 is not really fixed.
{**/*.ts,**/_.tsx__/_.js,**/*.jsx,**/_.es6} ->
(?:(?:[/\]._?|.+?[/\]|)[^/\]_?.ts|(?:[/\]._?|.+?[/\]|)[^/\]_?.ts|(?:[/\]._?|.+?[/\]|)[^/\]_?.tsx[^/\]_?[^/\]_?[/\][^/\]_?.js|(?:[/\]._?|.+?[/\]|)[^/\]_?.jsx|(?:[/\]._?|.+?[/\]|)[^/\]_?.es6)
It's correct, but `*.\.ts|*.\.tsx|*.\.js|*.\.tsx` would do it. The non-capturing groups also don't seem to be needed.

**Wrong results in some cases**:
`glob.match("**/project.json",...)` results in the regexp `(?:[/\\].*?|.+?[/\\]|)project\.json`

The or segment is strange `[/\\].*?`.
This results in `/rrproject.json` to be matched

**Updated comment from #19926**:
`server/**/**.js` should not match `server.js`

**Comment by bpasero** [comment] 2016-04-20 07:16
@aeschli good catch Martin, my regex ended up to do Catastrophic Backtracking (http://www.regular-expressions.info/catastrophic.html).

I pushed a change to simplify it. A "**" is now anything that starts with a path or ends with a path.

**Comment by bpasero** [comment] 2016-04-20 10:46
This caused a severe performance regression. Have to really add performance tests for the pattern we use to not get into this again...

**Comment by jrieken** [comment] 2016-04-20 10:55
This is the cause for  #5539

**Comment by bpasero** [comment] 2016-05-02 12:25
@aeschli pushed a simplification for the regex. we still need to test for more conditions than simply testing for `.*`. For example `**/.html` must not match on `foo/test.html`, but it would if `**` would simply translate to `.*`

**Comment by aeschli** [comment] 2016-05-26 20:16
"**/project.json" -> "(?:[/\\].*?|.+?[/\\]|)project\.json"  This matches /rrproject.json...
I created #6936

**Comment by bpasero** [comment] 2016-05-30 08:54
Reopening because the change makes the glob pattern match too much.

**Comment by NotWearingPants** [comment] 2019-10-21 03:09
VSCode can hang and crash on this glob regex when it tries to select a language (`languageSelector.ts`) on not-so-extreme conditions:

if I have a file at `C:\aaaa\aaaaa\aaaaaaa\aaaaa\aaaaaaaa\aaaaaa\aaaaaaaaaaa\aaa\aaaaaaaaaaaaa\aaaaaa\aaaaaaaaaaa` and I open it by pasting the following in the <kbd>Ctrl</kbd>+<kbd>P</kbd> palette:
`C:\\aaaa\\aaaaa\\aaaaaaa\\aaaaa\\aaaaaaaa\\aaaaaa\\aaaaaaaaaaa\\aaa\\aaaaaaaaaaaaa\\aaaaaa\\aaaaaaaaaaa`
(same path but with double backslashes)

This happened to me by accident, so this issue affects real world use cases and should be fixed.

**Comment by jrieken** [comment] 2019-10-21 07:03
@NotWearingPants Can you attach a profile so we know it's this or another issue? Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by NotWearingPants** [comment] 2019-10-21 14:15
@jrieken
I have debugged vscodethe devtools and saw it was stuck in the `regex.test(filepath)` inside the glob functionality called by `languageSelector.ts`.

I was also able to reproduce this in node.js using just `regex.test(filepath)` with the same regex and filepath.

I don't see a reason to attach a profile if I honed in on the problem. I might upload one later, not sure.

**Closed** 2020-10-23 12:17 UTC
Labels: *out-of-scope, debt, file-glob, perf
