### ISSUE TITLE
macos return stops working

### ISSUE THREAD

**Issue by kneufeld-pbp** [microsoft/vscode#123194] opened 2021-05-06 20:48 UTC
Hello,
Updated to the latest version, may `Return` key randomly stops working displaying the falling error:
`Cannot read property 'rename' of undefined`.

When the return key no longer works, I also noticed secondary delete key has been re-assigned to Open Terminal, no longer deleting text to the right of the cursor. 

When this happens I have to quit vscode and start it again. 
### vscode:
```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```
### System Info:
Description| Details
:--|:--
CPUs | Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 4, 4
Memory (System) | 16.00GB (0.34GB free)
Process Argv | --crash-reporter-id 423aae87-1ec6-483d-9f53-2a641677876a
Screen Reader | no
VM | 0%

### Enabled extensions
Extension | Author (truncated) | Version
-- | -- | --
project-manager | ale | 12.1.0
atlascode | atl | 2.8.6
vscode-zonefile | Com | 0.0.4
gitlens | eam | 11.4.1
EditorConfig | Edi | 0.16.4
json-tools | eri | 1.0.2
file-icons | fil | 1.0.29
gitlab-workflow | Git | 3.20.0
go | gol | 0.24.2
terraform | has | 2.10.2
mysql-syntax | jak | 1.3.1
python | ms- | 2021.4.765268190
jupyter | ms- | 2021.6.811652604
powershell | ms- | 2021.2.2
vsliveshare | ms- | 1.0.4131
vsliveshare-audio | ms- | 0.1.91
vsliveshare-pack | ms- | 0.4.0
material-icon-theme | PKi | 4.6.0
vscode-commons | red | 0.0.6
vscode-xml | red | 0.16.0
vscode-yaml | red | 0.18.0
trailing-spaces | sha | 0.3.1
rewrap | stk | 1.14.0
json2yaml | tux | 0.2.0
vscode-icons | vsc | 11.4.0
change-case | wma | 1.0.0
markdown-all-in-one | yzh | 3.4.0

### A/B experiment info
```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
```

**Comment by meganrogge** [comment] 2021-05-07 04:05
duplicate of https://github.com/microsoft/vscode/issues/123086

**Closed by meganrogge** 2021-05-07 04:05 UTC
