### ISSUE TITLE
SCM: Restore commit message on reload/reopen

### ISSUE THREAD

**Issue by AlansCodeLog** [microsoft/vscode#41232] opened 2018-01-06 22:15 UTC
Sometimes I'm half-way done typing a commit message and I end up doing something else, then for some reason or other reload/reopen the editor, and what I typed is gone. Obviously not the end of the world, but even the search keeps its state when reloading/reopening. I think the extension search is the only other thing doesn't.

**Comment by ryanolsonx** [comment] 2018-01-08 19:40
Hello!

I'd like to work on this issue. Has anyone already started work on this?

**Comment by niklabh** [comment] 2018-01-09 13:35
https://github.com/Microsoft/vscode/pull/41341

**Comment by joaomoreno** [comment] 2018-01-09 16:14
@niklabh So fast! ⚡️

**Comment by ambrop72** [comment] 2018-01-30 15:41
Hey,
I would like to point out that for me the commit message is lost after just switching to a different view (e.g. to Files and back to Source Control), and this seems to happen only if there are multiple source control providers (or folders open?).

**Comment by ADTC** [comment] 2018-02-21 23:59
Any update on this? I'm frustrated by this. Data loss is NEVER acceptable. I see there is already a crude PR for this. Hope someone can refine it so that it can be merged. (Sorry, I can't do TS yet.)

**Comment by RReverser** [comment] 2018-07-09 08:36
Unfortunately, commit is lost even when staying in the editor, but switching to another pane (like to quickly do find-in-files before committing).

**Comment by AlansCodeLog** [comment] 2018-07-09 18:08
> So apparently the Extension search keeps the state, so the above quoted statement is no longer true. If that was recently fixed, I think this should be too.

You sure? Because it doesn't for me.

@RReverser I'm on the latest stable version and everything is working fine for me. That sounds like a separate bug/regression.

Extensions and Source Control always lose what I wrote on reload and *only on reload* as I think was normal behavior, hence why this was a feature request (@joaomoreno not sure why that was changed?). I also have multiple git repos open sometimes and at least with this release, they keep their state just fine when switching between them or tabs.

**Comment by RReverser** [comment] 2018-07-09 22:23
@AlansCodeLog maybe a regression as I've started noticing this relatively recently but reproduces quite consistently for me.

**Comment by joaomoreno** [comment] 2018-07-10 09:30
Hey guys, I'm looking at this again. I can't really reproduce what you guys are seeing.

![peek 2018-07-10 11-29](https://user-images.githubusercontent.com/22350/42501733-a8f5970e-8434-11e8-9a2d-82cec7617fe6.gif)

The only issue I see here is the original one: the commit message doesn't get restored on window reload.

Can you confirm?

**Comment by RReverser** [comment] 2018-07-10 13:07
> Can you confirm?

Ok, looks like I can reproduce the commit message being lost on one repo but not the other. The only important difference between them I can think of is that the one where commit message is lost has this warning at the start:

> The '...' repository has 39 submodules which won't be opened automatically. You can still open each one individually by opening a file within.

Not sure if it can be related, but maybe?

**Comment by RReverser** [comment] 2018-07-10 13:10
I created an empty project to reproduce, and it's even simpler: apparently even if I have a single submodule, the commit message keeps getting lost when switching panes, if I don't, then it's preserved fine.

**Comment by joaomoreno** [comment] 2018-07-10 14:35
@RReverser Nop, still works for me. Do you have any commit template message defined?

**Comment by RReverser** [comment] 2018-07-10 22:33
@joaomoreno Nope. This is getting weird...

**Comment by joaomoreno** [comment] 2018-07-11 09:34
Can you reproduce with `--disable-extensions`?

**Comment by RReverser** [comment] 2018-07-11 11:22
@joaomoreno Ummm... I couldn't reproduce without extensions, then restarted Code with extensions, and now for the first time in a while can't reproduce it even with extensions on either repo. Either Code has updated in the meanwhile or it was some weird state issue, but seems to work now.

**Comment by joaomoreno** [comment] 2018-07-12 08:06
Anybody else can confirm?

**Comment by AlansCodeLog** [comment] 2018-09-14 17:02
Can I ask why this was closed?

**Comment by joaomoreno** [comment] 2018-09-17 09:04
> Anybody else can confirm?

@AlansCodeLog I received no reply since July 12. Since I can't reproduce and it works for me, I closed it. Can you still reproduce this? Can you reproduce with `--disable-extensions`?

**Comment by AlansCodeLog** [comment] 2018-09-17 16:56
Maybe I misunderstood, but I thought that your "can confirm" was regarding RReverser's issue, which was not the original issue. As I commented above (Jul 9), I could not replicate that. My issue I can still replicate  (without extensions as well).

To be clear, to replicate: Type something in source control -> Reload Window -> Doesn't remember what you typed.

**Comment by joaomoreno** [comment] 2018-09-18 08:09
You're absolutely right. Somehow along the way I mistake the issue for switching viewlets.

**Closed** 2020-09-25 23:38 UTC
Labels: feature-request, help wanted, scm
