### ISSUE TITLE
Cannot specify global problemMatcher in tasks.json

### ISSUE THREAD

**Issue by babramczyk** [microsoft/vscode#81237] opened 2019-09-20 15:03 UTC
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Specify `"problemMatcher": []` at top level of `tasks.json` object
2. Run a task (i.e. an npm task) that has no task config
3. VS Code still prompts you for how to scan the task output

Does this issue occur when all extensions are disabled?: No

### Other comments
Essentially, I want to be able to disable the problem matcher by default. Personally, I never use it, and it's just noise, because every time I run a task I haven't ran before, I have to select `Never scan the task output`, which opens up `tasks.json` and adds a new config for that task, just so it can specifiy `"problemMatcher": []`.

### Related issues
- https://github.com/Microsoft/vscode/issues/43003
  - This issue was closed, but I still have the problem

**Comment by alexr00** [comment] 2019-10-10 08:17
Duplicate of https://github.com/microsoft/vscode/issues/24865

**Closed** 2019-10-10 08:18 UTC
Labels: *duplicate, feature-request, tasks
