### ISSUE TITLE
tabCompletion not correctly set

### ISSUE THREAD

**Issue by fierval** [Microsoft/vscode#11808] opened 2016-09-09 23:32 UTC
- VSCode Version: 1.5.1
- OS Version: Win7

Steps to Reproduce:

1. Start from any Angular 2 project: e.g: https://github.com/spboyer/ng2-startingline
2.  Make sure workspace settings have editor.tabCompletion: true

At some point, perhaps not right away, tab completion stops working. Looking at default settings, editor.tabCompletion is set to false, despite workspace settings showing that it is set to true.

**Comment by jrieken** [comment] 2016-09-12 07:10
@fierval Please update with steps that allow to reproduce

**Comment by jrieken** [comment] 2016-09-27 12:26
Closing since this issue still lacks steps to reproduce

**Closed by jrieken** 2016-09-27 12:26 UTC
Labels: needs more info
