### ISSUE TITLE
Zoom reset not possible

### ISSUE THREAD

**Issue by StfBauer** [Microsoft/vscode#38730] opened 2017-11-19 20:00 UTC
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: 10.13.1 (17B48)

Steps to Reproduce:
1. Zoom accidentally in using Track Pad
2. Tried to come out hasn't worked
3. Reset Zoom hasn't worked either

Screen still looked like this:
<img width="1280" alt="screen shot 2017-11-19 at 20 50 27" src="https://user-images.githubusercontent.com/5503835/32994744-e85701e2-cd6b-11e7-92ee-f66557a111f3.png">

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-11-20 05:42
@StfBauer that is weird, we set some flags to explicitly prevent zooming via trackpad, how did you manage to get into this state, by pinch-zooming with the macOS touchpad?

**Comment by StfBauer** [comment] 2017-11-21 20:55
Tried it out now and figured it out under which circumstances this happens. It mostly happens when I come back from sleep mode and VS Code was still open.
After a period of time I then be able to swipe zoom / pinch zoom in. Seems like the blocking of this event got lost.
Happens as mentioned before in safe mode and normal mode.

**Comment by bpasero** [comment] 2017-11-22 09:08
I can reproduce and reported as https://github.com/electron/electron/issues/11216

**Comment by ldexterldesign** [comment] 2018-02-13 08:25
Hey @stfbauer,

> Reset Zoom hasn't worked either

<img width="403" alt="screen shot 2018-02-13 at 09 22 54" src="https://user-images.githubusercontent.com/1715809/36139877-809a3e4e-109f-11e8-9648-31fc478f672f.png">

+1

Regards

**Comment by StfBauer** [comment] 2018-03-27 22:37
@ldexterldesign In my case, it happens by accident the regular zoom worked as expected. Cannot test the cmdNumPad0 cause I don't have a NumPad on my notebook and never use a regular keyboard. 😀

**Comment by bpasero** [comment] 2018-04-04 15:01
I think Electron 2.0.x pulls in a fix for this, have to verify.

**Comment by ldexterldesign** [comment] 2018-04-04 15:27
Hey @StfBauer @bpasero,

Hope you're well

Thanks for replies

Since my previous post the toolbar/tooltip (i.e. "View > Reset Zoom") now works for me, however I still don't know a suitable keyboard shortcut using my Apple MBP - that would be useful!

Hope to hear back

Cheers

**Comment by StfBauer** [comment] 2018-04-14 19:56
@ldexterldesign have you tried to create a custom keyboard shortcut?

**Comment by ldexterldesign** [comment] 2018-04-14 22:14
@StfBauer sorry, I've just reread this issue and my issue is something different. I'll take my gripe here[0]. Hope you resolve *this* issue!

Regards

[0] https://github.com/Microsoft/vscode/issues/15840#issuecomment-268887968

**Comment by bpasero** [comment] 2018-08-06 08:50
Closing, as we pushed the Electron update.

**Closed by bpasero** 2018-08-06 08:50 UTC
Labels: bug, electron, upstream
