### ISSUE TITLE
F10 keeps showing debug view even when users hide it

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125967] opened 2021-06-10 20:52 UTC
Issue Type: <b>Bug</b>

I hide side bar during debug session somtimes but every F10 will bring it back

VS Code version: Code - Insiders 1.57.0-insider (c7119ae8b6390a5700f6b28f0f1511d676c96562, 2021-06-08T09:17:55.672Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (6.31GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment] 2021-06-11 12:30
You can control this via 	
```
"debug.openDebug": "openOnSessionStart"
```

The default is to open on `break`, we changed the default based on user feedback.
@rebornix do you have some ideas how to improve this? 

I think a setting is good enough for this?

**Comment by rebornix** [comment] 2021-06-11 17:34
@isidorn the setting is good enough for me, it's not clear that this feature can be controlled by a setting (that's why I didn't go the settings directly).

I'm not sure if we can have a way to detect that users keep doing

* F10
* hide sidebar
* F10 again
* hide sidebar

when `f10/hide` happens more than twice or three times, maybe we can ask users if they want to change the setting. Though I'm not sure if that contributes to the overload of notifications.

**Comment by rebornix** [comment] 2021-06-11 17:35
Feel free to close this issue.

**Comment by isidorn** [comment] 2021-06-22 07:40
Detecting that the sidebar got closed by the user might be a good signal.
I suggest that for now we move this to backlog and if other users hit this we can think about doing something here.

**Comment by isidorn** [comment] 2021-08-06 12:20
This should be better now :) We only open on breakpoint hit.
I did not perfectly understand your issue (did not understand that the issue is that bad), so sorry for the slow response here.

**Closed by isidorn** 2021-08-06 12:20 UTC
Labels: debug, under-discussion
