### ISSUE TITLE
PR view moves up on click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161042] opened 2022-09-16 06:39 UTC
![Recording 2022-09-16 at 08 39 28](https://user-images.githubusercontent.com/900690/190573076-cce8c5d2-ac4a-428d-b7f9-fbaf0d6aa6dc.gif)

Only seeing this starting with todays insider.

**Comment by alexr00** [comment] 2022-09-16 07:42
Duplicate of https://github.com/microsoft/vscode/issues/160721

**Closed by alexr00** 2022-09-16 07:42 UTC
