### ISSUE TITLE
Switch tabs, On Scroll jumps to end of file

### ISSUE THREAD

**Issue by Sankarrockzz** [microsoft/vscode#99362] opened 2020-06-04 12:00 UTC
Issue Type: <b>Bug</b>

1) Open any file in VS code, with scrollable lines of code, say >50.
2) Click on line no. 1
3) Now switch/open any other linux program, say a web browser.
4) Open any web  page there, scroll down, say half a way (Dont click anywhere).
5) Finally Switch back to VS code, and scroll down, suddenly it will jump from line 1 to half of the page.

NOTE:  You scroll 'x' amount in the browser/any othe app, you jump 'x' in the VS code. 

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-101-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2326)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.72GB (3.19GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
theme-monokai-pro-vscode|mon|1.1.15
python|ms-|2020.5.80290
sublime-keybindings|ms-|4.0.7
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0

</details>

**Comment by alexdima** [comment] 2020-06-05 07:02
Duplicate of #28795

**Closed by alexdima** 2020-06-05 07:02 UTC

**Comment by Sankarrockzz** [comment] 2020-06-09 11:47
Ok I find the workaround solution.

In Ubuntu 16.04 just install imwheel.

sudo apt-get install imwheel

then run $ imwheel

also you can add this command to startup items.

credit: https://github.com/microsoft/vscode/issues/28795#issuecomment-391258341
