### ISSUE TITLE
Don't include active file in quick open search result

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#64006] opened 2018-11-29 18:07 UTC
This issue #49607 was closed as a duplicate of #30770. But it's still not implemented.

`"search.quickOpen.includeHistory": false,` - not excluding active file
`"search.quickOpen.includeHistory": true,` - not excluding active file

**Comment by roblourens** [comment] 2018-11-29 18:32
#49607 as written is a duplicate of #30770 - that setting should exclude recent history when typing. It doesn't exclude recent history when there is no query in quick open. Do you want it to also not show recently opened when there is no query in quick open? Why not?

**Comment by usernamehw** [comment] 2018-11-29 18:37
This is unrelated to history. It's about a search match that doesn't make sense if the file is open and active.

Can you imagine looking for a car keys when you hold them in your hand? (I mean, that could happen but it's usually a user mistake).

**Comment by bpasero** [comment] 2018-11-30 05:51
I will close this as wont fix as I find this not a good behaviour. The file that is currently open might not be so obvious at the time you do a search and then it would be very frustrating not to find it. You might be jumping back to VSCode after a long time and start a search without even looking at the active file.

**Closed by bpasero** 2018-11-30 05:51 UTC
Labels: feature-request, search

**Comment by usernamehw** [comment] 2018-11-30 14:53
An option?
