### ISSUE TITLE
Regression: Auto import doesn't work for ES5 imports

### ISSUE THREAD

**Issue by laplacesdemon** [Microsoft/vscode#60577] opened 2018-10-11 01:31 UTC
- VSCode Version: Version 1.28.0 (1.28.0)
- OS Version: 10.14.1

Steps to Reproduce:

1. Create a `.js` or `.jsx` file
2. Start typing a component name in the `render` method of a `React.Component`: <AccordionTable
3. Intellisense will display 'auto import suggestion', choose it
4. The component is auto compoleted to `<import('../../../../common/AccordionTable').AccordionTable` but should have been `<AccordionTable` and the import on top of the file be `import AccordionTable from '/path/to'`.

This feature was working fine before `10.14.1`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-10-11 01:38
Duplicate of https://github.com/Microsoft/TypeScript/issues/27317

**Closed by mjbvz** 2018-10-11 01:38 UTC
Labels: javascript
