### ISSUE TITLE
Extension Devs: Extending an existing Icon Theme

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/vscode#17700] opened 2016-12-21 20:34 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro

I am building a super simple extension that associates a JSON Schema for my file `package.manifest` from SchemaStore.org and then with the `languages`  contributionPoint are able to ensure that the `json` language is applied to it & thus the Schema is immediately available.

Continuing this I thought it would be neat to have a custom icon for my file, my initial thought is that I could extend an already icon theme that the user has set/defined in VSCode. So when contributing an Icon set from an extension my assumption if providing a very limited/tiny JSON of associations in my case just for the filenames `package.manifest` it would display & work against my chosen/active icon theme.

Otherwise I have a tedious task of duplicating or extending this JSON file with say the default VSCode Icon JSON file.

My limited icon JSON file
```
{
    "iconDefinitions": {
        "_package_manifest_file": {
            "iconPath": "./my-icon.svg"
        }
    },
    "fileNames": {
        "package.manifest": "_package_manifest_file"
    }
}
```

**Comment by hoovercj** [comment] 2016-12-21 22:28
Somewhat related: https://github.com/Microsoft/vscode/issues/7669

**Comment by warrenbuckley** [comment] 2016-12-22 09:35
@hoovercj does this mean this will not be supported or considered for future?

**Comment by aeschli** [comment] 2016-12-30 02:49
duplicate of #14662.

We don't know yet if and when we can add such support.

**Closed by aeschli** 2016-12-30 02:49 UTC
