### ISSUE TITLE
import module intellisense working not well

### ISSUE THREAD

**Issue by mosluce** [Microsoft/vscode#14546] opened 2016-10-26 15:54 UTC
- VSCode Version: 1.6.1
- OS Version: macOS 10.12

Steps to Reproduce:
1.  Look [Youtube](https://youtu.be/ahit5tI_5XE)

**Comment by waderyan** [comment] 2016-10-31 16:31
@mosluce thank you for opening this. We have found this before. Duplicate of https://github.com/Microsoft/vscode/issues/14698

**Closed by waderyan** 2016-10-31 16:31 UTC
Labels: duplicate
