### ISSUE TITLE
Electron 2.0.x : extreme blur around the entire application (Windows 10)

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#51789] opened 2018-06-13 18:17 UTC
Issue Type: <b>Bug</b>

All views and their text is super blurred to the point that it makes things mostly unusable.

VS Code version: Code - Insiders 1.25.0-insider (583f1e4934c5fd3b62c2ca5bf177c728b31b9605, 2018-06-13T05:18:10.709Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (25.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe D:\Development\Schule\Testing|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
cake-vscode|cak|0.10.1
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
docs-authoring-pack|doc|0.0.3
docs-markdown|doc|0.0.3
xml|Dot|2.3.0
gitlens|eam|8.3.5
tslint|eg2|1.0.30
beautify|Hoo|1.3.2
rest-client|hum|0.18.4
theme-monokai-pro-vscode|mon|1.1.8
DocFX|ms-|0.1.3
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.6.0
gradle-language|nac|0.2.3
chef|Pen|0.7.0
vscode-docker|Pet|0.0.27
java|red|0.26.0
vscode-icons|rob|7.23.0
msbuild-project-tools|tin|0.2.38
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0

</details>

**Comment by MeikTranel** [comment] 2018-06-13 18:44
Here are some examples:

![CloseUp](https://user-images.githubusercontent.com/6466560/41371386-70ecb0ee-6f4a-11e8-942a-13d76d51f7ab.gif)

![Entire APP](https://user-images.githubusercontent.com/6466560/41371100-a36a46e0-6f49-11e8-85b6-7f3f3a7b36ee.gif)

**Comment by MeikTranel** [comment] 2018-06-13 18:56
The granular image is from the GIF converter. The blur itself is the real image i see in front of me.

**Comment by Tyriar** [comment] 2018-06-14 07:11
@MeikTranel do you have `window.zoomLevel` in your settings.json?

**Comment by bpasero** [comment] 2018-06-14 15:17
This seems to be like a nightly Windows 10 build if I am not mistaken (https://changewindows.org/build/17686/pc) so maybe this should also get reported to Windows team. Does it reproduce with Chrome too?

**Comment by MeikTranel** [comment] 2018-06-14 18:09
No. Havent seen this within chrome, yet.
What makes me think it's a vscode thing is that it's not happening at all in 0.24.0 (that's why i showed the non-insider version in the screencap too)

**Comment by bpasero** [comment] 2018-06-15 05:17
@MeikTranel @Mehgugs can you try out a bare Electron application to see if you see the blurrniness too. Just download and run: https://github.com/electron/electron/releases/download/v2.0.2/electron-v2.0.2-win32-x64.zip

**Comment by bpasero** [comment] 2018-06-15 06:33
@MeikTranel @Mehgugs also if you are up for a little experiment:

* quit any running VSCode Insiders
* open `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\main.js`
* find the place where it reads `app.commandLine.appendSwitch("disable-mojo-local-storage");`
right after paste this: `app.commandLine.appendSwitch('force-color-profile', 'srgb');`
* save (you will need to save as admin I guess)
* start VSCode Insiders again
=> does the issue still reproduce?

**Comment by MeikTranel** [comment] 2018-06-15 09:29
@bpasero from what i'm seeing electron itself doesn't show any symptoms (the bare electron client really doesn't have that much to test with tho)

Checking out the other thing now.

BTW.: I updated to 17692 yesterday from 17686, so that i can play csgo again 😄 https://changewindows.org/build/redstone5/17692/pc
Issue is persisting through

**Comment by bpasero** [comment] 2018-06-15 09:33
@MeikTranel thanks. to test another application that is similar to VS Code and uses the same Electron version, can you try with Atom beta too: https://atom.io/beta

**Comment by MeikTranel** [comment] 2018-06-15 09:35
I tested the electron srgb command line switch; Didn't help -___-
At first i thought it did but when i moved the window around it started right back again :/

**Comment by MeikTranel** [comment] 2018-06-15 09:44
Oh hell yeah, progress! Atom has the same issue @bpasero 
![gif2](https://user-images.githubusercontent.com/6466560/41461883-552602e6-7091-11e8-8322-664374866f45.gif)

Do both use Electron 2.0 ?

**Comment by bpasero** [comment] 2018-06-15 09:51
@MeikTranel good to know 👍. does it reproduce if you run `code-insiders --disable-gpu`

**Comment by MeikTranel** [comment] 2018-06-15 10:15
--disable-gpu seems to mitigate it.
i assume this disables hardware acceleration?

**Comment by bpasero** [comment] 2018-06-15 12:20
@MeikTranel yes it does. What kind of GPU are you running with?

**Comment by Tyriar** [comment] 2018-06-15 12:48
@MeikTranel yes. From your original report this is what GPU features were enabled:

```
2d_canvas: enabled
checker_imaging: disabled_off
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: enabled
video_decode: enabled
video_encode: enabled
webgl: enabled
webgl2: enabled
```

So one of these must be to blame.

**Comment by MeikTranel** [comment] 2018-06-15 13:41
@bpasero this machine runs a GTX1080 and a 6700k (which comes integrated with a Intel® HD Graphics 530)

**Comment by MeikTranel** [comment] 2018-06-15 13:42
It's running on the GTX 1080 tho
![image](https://user-images.githubusercontent.com/6466560/41471021-b70415d6-70b2-11e8-90fe-b45a94fd3ff3.png)

**Comment by bpasero** [comment] 2018-06-15 13:50
@MeikTranel does it reproduce when no editor is opened and maybe only the explorer?

**Comment by MeikTranel** [comment] 2018-06-15 14:10
<details>
<Summary>User Settings</Summary>

```json
{
    "workbench.iconTheme": "vscode-icons",
    "msbuildProjectTools": {
        "logging": {
            "level": "Information",
            "seq": {},
            "file": "",
            "trace": false
        },
        "language": {
            "disableFeature": {},
            "useClassicProvider": false,
            "disable": {
                "hover": false
            }
        },
        "nuget": {
            "newestVersionsFirst": true,
            "includePreRelease": true,
            "disablePrefetch": false
        },
        "schemaVersion": 1
    },
    "java.errors.incompleteClasspath.severity": "ignore",
    "rest-client.enableTelemetry": false,
    "rest-client.followredirect": false,
    "rest-client.includeAdditionalInfoInResponse": true,
    "gitlens.keymap": "none",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    }
}
```
</details>

<details>
<Summary>Workspace Settings (although irrelevant considering this isn't a workspace specific issue) </Summary>

```json
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/bin": true,
        "**/obj": true
    }
}
```
</details>

**Comment by MeikTranel** [comment] 2018-06-15 14:12
@bpasero by explorer you mean the vscode explorer? as in no code file open?

As for the other question: I tested and reproduced it specifically without chrome or other apps related also with only vscode running.

**Comment by Tyriar** [comment] 2018-06-15 14:13
@MeikTranel are your Nvidia drivers up to date? If that doesn't change anything then I'm guessing this is an issue in the version of Chromium under the hood.

**Comment by bpasero** [comment] 2018-06-15 14:15
@MeikTranel yeah I am trying to figure out which action in the UI triggers the blurriness. My understanding is that it only happens when you do something specific, like opening an editor?

**Comment by MeikTranel** [comment] 2018-06-15 14:17
I'm updating drivers right. But i don't think thats gonna help.
The current driver's from january.
![image](https://user-images.githubusercontent.com/6466560/41472691-73a05f98-70b7-11e8-99c1-57c313f9d85e.png)

**Comment by xLobito** [comment] 2018-06-16 03:50
I'm facing the same issue since a few days ago. I updated to latest nightly insiders build (back then) and the blurry display came out. 

It's been persistent between two new nightly updates. I just checked some options and the result is quite the same, no differences at all. 
I updated my GTX 970 drivers and now I'm checking out if this solves the issue. 

p.s: The blurry screen appeared in the GeforceExperience main screen application, which makes me think that my issue is most likely related to Windows rather than VSCode itself.

**Comment by bpasero** [comment] 2018-06-16 05:44
@xLobito so you are saying that the (same) blurry screen shows up for you also in other applications?

**Comment by xLobito** [comment] 2018-06-16 05:57
@bpasero 

Only GeforceExperience (which I don't know if anyone has been getting the same blurry screen like myself) when I was downloading the driver for installation. Although I think it got fixed when I allowed to Windows avoid blurriness (I have two monitors with different resolutions, so it could be that).

On the other hand, the VSCode still presents the blurry screen, when I create a new file or use the bash-like terminal. So, updating to latest driver didn't fix the issue.

**Comment by Mehgugs** [comment] 2018-06-16 15:34
I have had exactly the same issue, it occurs for me whenever I open a dialog except the top menus (File, Edit etc...) 
ShareX mp4 capture of it happening upon opening ctrl+f dialog:
https://streamable.com/wze59

I also have a nvidia card (a gtx 960M) has the latest drivers. This doesn't happen for me in other applications. This happens for me using my integrated card as well as my nvidia one.

**Comment by bpasero** [comment] 2018-06-16 16:15
@Mehgugs that video is interesting, I wonder if this could be related to having animations on the screen (the find widget box seems to animate in). Can you reproduce the blurriness when you work with VSCode but not use elements that cause animation (like the find box)?

**Comment by xLobito** [comment] 2018-06-17 08:16
Randomly, the issue appears. Right now, I closed and opened it three times and the blurriness is intact. 

The issue this time started right after I copied some text from the right side, pasting it in the left side. It was working fine before it during some hours. 

![image](https://user-images.githubusercontent.com/16466974/41506091-0399e0c8-71e5-11e8-88c3-d422a07a3460.png)

**Comment by bpasero** [comment] 2018-06-17 08:40
@xLobito I closed and opened it three times and the blurriness is intact.

What does "intact blurriness" mean? Is that good or bad?

**Comment by xLobito** [comment] 2018-06-17 09:05
@bpasero. Apologies for not being too accurate with my description. 

About the "intact blurriness" that I was talking about, refers the fact that it kept continued after even three attempts of opening the VSCode editor. 
And, about repro your suggestion. I can confirm it happens after re open the editor and right look for anything (Just by opening the search viewlet).

**Comment by bpasero** [comment] 2018-06-18 10:14
@MeikTranel @xLobito does it change anything if you change the "Let Windows try to fix apps so they are not blurry" from this Advanced Scaling page:

![image](https://user-images.githubusercontent.com/900690/41530643-1be35436-72f1-11e8-9a9b-b68651e7a817.png)

Was this setting on or off if changing it makes a change for you?

**Comment by MeikTranel** [comment] 2018-06-18 11:39
I tested all the other combinations with those Settings On and Off. It doesn't seem to have any impact. Same with the application specific settings inside the compatibility settings when right-clicking the app shortcut itself.

**Comment by xLobito** [comment] 2018-06-18 14:17
![image](https://user-images.githubusercontent.com/16466974/41541305-1f03c8be-72e0-11e8-8deb-97d6e5f2cc83.png)

Tested the same as @MeikTranel, but it doesn't work.

**Comment by Mehgugs** [comment] 2018-06-19 00:48
@bpasero I don't know how to describe the type of menus, but things like alert popups, command palette, theme picker. Any menu that is coloured using the editor's theme causes the issue for me (doesn't matter what theme it is either), so things like the right click context menu do not cause the bug.

**Comment by MeikTranel** [comment] 2018-06-30 19:31
FYI: I've since upgraded to RS6 Fast Ring Build 17704.1000 and the problem persists.

**Comment by MeikTranel** [comment] 2018-06-30 20:19
I hadn't updated vscode itself for some days on that machine.
I no longer can reproduce the issue.

@bpasero any changes? or did you guys unmigrate from electron 2.0 again?


VS Code version: Code - Insiders 1.25.0-insider (6ca99aca80e80224f1c0bd4370c6ec4941c3bc54, 2018-06-29T09:03:04.490Z)
OS version: Windows_NT x64 10.0.17704

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
cake-vscode|cak|0.10.1
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.1
docs-preview|doc|0.3.12
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
dotnet-test-explorer|for|0.3.1
beautify|Hoo|1.3.2
rest-client|hum|0.19.0
theme-monokai-pro-vscode|mon|1.1.8
DocFX|ms-|0.1.3
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.7.0
gradle-language|nac|0.2.3
chef|Pen|0.7.0
vscode-docker|Pet|0.0.27
java|red|0.27.0
vscode-icons|rob|7.24.0
vscode-coverage-gutters|rya|2.0.0
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.39
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0


</details>

**Comment by bpasero** [comment] 2018-07-01 06:32
@MeikTranel yes we did go back to Electron 1.7.x

**Comment by MeikTranel** [comment] 2018-07-01 13:40
Well damn, i was kinda hyped this got resolved. We are only moving back to 1.7 for june end game right? When current insider is being released we're moving back to electron 2.0 right?

**Comment by bpasero** [comment] 2018-07-01 16:48
@MeikTranel yes the idea is to ship with Electron 2.0 eventually. It is still unclear to me if this is a Windows 10 insiders issue or not. I plan to install Windows 10 insiders to find out more soon.

**Comment by bpasero** [comment] 2018-07-09 10:39
@MeikTranel do you still see this? I now installed a Windows Insiders (`Version 1803, OS Build 17711.1000`) and I do not see this issue when I try with this build: https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCodeSetup-x64-1.24.0-exploration.exe

**Comment by MeikTranel** [comment] 2018-07-09 17:29
Still have the issue. By now this is happening in more and more apps. The same effect happens to me in the regular Visual Studio Installer right now.

![2018-07-09_19-21-19](https://user-images.githubusercontent.com/6466560/42465801-51d99678-83ad-11e8-9d2d-49ffe6a9aecb.gif)

I fear it has something to do with my dpi/resolution setup. I use 2560x1440(125% scaling) and 1680x1050(100% scaling), if that helps.

**Comment by Tyriar** [comment] 2018-07-09 18:08
@MeikTranel i the regular installer? Are you still on Electron @? Can you check in the Help > About menu?

**Comment by MeikTranel** [comment] 2018-07-09 18:32
In VSCode or in the VS2017 Installer?

**Comment by MeikTranel** [comment] 2018-07-09 18:33
VS Code version: Code - Exploration 1.24.0-exploration (163e64ca7bbd0a69c727cfd9f5610e7546207a71, 2018-05-17T05:34:34.725Z)
OS version: Windows_NT x64 10.0.17711

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Exploration\Code - Exploration.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MeikTranel** [comment] 2018-07-09 21:20
Same effect in terminus... Has this issue been raised in electron yet?
![2018-07-09_19-21-19](https://user-images.githubusercontent.com/6466560/42476374-0a276a00-83ce-11e8-9a49-3ff1844a65b7.gif)

**Comment by bpasero** [comment] 2018-07-10 05:29
@MeikTranel yeah let's try to file this to them, but for that we need a repro in a simpler app. Can you try to reproduce with their standard application: https://github.com/electron/electron/releases/download/v2.0.4/electron-v2.0.4-win32-x64.zip

If that does not reproduce, can you try to reproduce with Electron Fiddle: 
* `git clone https://github.com/electron/fiddle.git`
* `cd fiddle`
* `npm install`
* `npm start`

**Comment by bpasero** [comment] 2018-07-12 07:44
@MeikTranel any luck?

**Comment by MeikTranel** [comment] 2018-07-12 12:58
Well the standalone electron has nothing to show this really. It looks a bit like the issue is visible but it's really hard to see.

As for the fiddle application, yes i can reproduce it there.
![2018-07-12_14-54-54](https://user-images.githubusercontent.com/6466560/42634475-9d3d7e4e-85e3-11e8-9b9a-5df953a7d8e2.gif)

**Comment by bpasero** [comment] 2018-07-12 13:04
@MeikTranel well the issue is clearly visible I would say. Can you report this as bug to https://github.com/atom/electron and state that you can reproduce with the Electron fiddle application?

**Comment by MeikTranel** [comment] 2018-07-12 14:40
@bpasero if you have anything to add, i created the issue here: https://github.com/electron/electron/issues/13646

**Comment by bpasero** [comment] 2018-07-12 14:57
@MeikTranel thanks, let's see what Electron folks have to say.

**Comment by MeikTranel** [comment] 2018-07-19 17:09
I don't think this should be closed :smile: @bpasero  help :D

**Comment by xLobito** [comment] 2018-08-04 03:08
Greetings.

I updated to latest version of VS Code Insiders which eventually ported Electron 2.0.5 and the issue remains the same. Even the blurriness is worse than before. Happens right after I open the VS Code Insiders. 
Also, the only way to prevent this behavior is by disabling GPU Acceleration (Like before). 

I posted the same thing into Electron's issue place, though no response was given or anything. So, in the meantime I just leave this report here with the respective screenshots.

![](https://user-images.githubusercontent.com/16466974/43361341-17655f62-929a-11e8-8b52-b1dc172f47c9.JPG)

![](https://user-images.githubusercontent.com/16466974/43361342-1785aa9c-929a-11e8-9692-b090be91598d.JPG)

Both screenshots were made with a Windows 10 / Compilation 17134.

**Comment by bpasero** [comment] 2018-08-10 16:59
@MeikTranel @xLobito would you be willing to give some feedback if you can still reproduce this issue with a newer build that uses a newer Chrome version? You can [download it from here](https://az764295.vo.msecnd.net/exploration/198d785facf747b1f26234807376c6b3da09ef7a/VSCodeUserSetup-x64-1.27.0-exploration.exe). You will notice a new "VS Code Exploration" application with an orange icon.

Thanks!

**Comment by xLobito** [comment] 2018-08-11 05:12
@bpasero.

I just install it, and this issue is not appearing anymore. I opened the same project as before and no rendering issue is found, not even if I look for anything (which was the first approach to the related issue). 

![imagen](https://user-images.githubusercontent.com/16466974/43988423-55988d54-9d03-11e8-9c42-98bb2d3d7b4d.png)

I will keep using this VS Code which it's based on Electron 3 for the time being. Thanks for this!

**Comment by hyrious** [comment] 2018-08-11 05:49
@bpasero I can still reproduce this issue with the new one in minutes.

OS: Windows10 1803 17134.191

Good: It looks like hovering some elements of the editor (like gifs above) won't trigger blur.
Bad: But losing focus for a while you can still observe the blur.

Here I'm sure it must be some issue between **the NVIDIA driver** and electron. Few days ago I just clean installed my laptop. Before that everything worked ok. The major difference is that I installed the latest display driver ([398.82 released at 8.1](https://www.nvidia.com/download/driverResults.aspx/136675/en-us)) for my 950M. Now Visual Studio Installer, Visual Studio 2017 Community, Visual Studio Code are all facing this same issue.

**Comment by bpasero** [comment] 2018-08-11 05:55
@xLobito thanks and you can still reproduce with our insiders version which is based on Electron 2.0.x right (you can give our preview releases a try from: https://code.visualstudio.com/insiders/)?

@hyrious yeah I do think it is GPU driver related

**Comment by xLobito** [comment] 2018-08-11 06:08
Well, by hovering or go to definition into C# (Xamarin.Forms) project doesn't trigger the issue in VS Code Exploration. Not even Visual Studio 2017 triggers the issue with my Nvidia Driver (I have one update to go, but I haven't updated yet). 

The issue persists on VS Code Insiders, though. So, I will keep on using Exploration which runs fine for now.

![imagen](https://user-images.githubusercontent.com/16466974/43988792-fa83cdb8-9d0a-11e8-8c65-b67ccbd4ab81.png)

![imagen](https://user-images.githubusercontent.com/16466974/43988806-1bb80cd8-9d0b-11e8-8a2d-c7fef9250d2a.png)

**Comment by michaeljblum** [comment] 2018-08-15 23:15
I just noticed this as well... Getting blurriness upon loss of focus in VSC and Github Desktop as well. Sometimes distinct sections of each application will blur separately, while I'm still actively working in the app. Any fix beyond disabling GPU acceleration yet?

**Comment by xLobito** [comment] 2018-08-16 16:26
@bpasero 

It seems the issue gets triggered if I open one extension to do anything with it (Install, Reload, Unistall, etc). If I don't do that, everything works as expected.

![imagen](https://user-images.githubusercontent.com/16466974/44221450-e7eb8a00-a157-11e8-8d2b-20d21f9c256c.png)

**Comment by DanaMW** [comment] 2018-08-19 10:01
Hi there,  having the same problem. I disabled the gpu but once i change files, move/resize  the window or breath to heavy (Sorry kidding) it comes back at me. It even blinks a bit bright. Any way I would be glad to share any information I have that you might require. Having said that,  i don't think at this point it will do to much good. I have found the latest Atom does it even worse.  So I suspect my settings won't fix  electron`
Onto the next subject,I see you shared a kink to VSCodeUserSetup-x64-1.27.0-exploration.exe  above. Would you happen to have the link to the 64 bit zip ?   Again feel free to boss me around and i will put up any items I have that will help .

**Comment by bpasero** [comment] 2018-08-19 16:08
@DanaMW Windows 64bits: https://az764295.vo.msecnd.net/exploration/57d01751b88c89046b33be3f1d55f860041fd27b/VSCodeUserSetup-x64-1.27.0-exploration.exe

**Comment by DanaMW** [comment] 2018-08-20 03:35
Thank you anyway.  I will continue to use the ZIP format portable version..

**Comment by eshack94** [comment] 2018-08-22 07:03
Having the same issue. Did @bpasero's fix help?

**Comment by djmisterjon** [comment] 2018-08-27 11:03
i just fix the issue on my side !!!! 
i try for 30 minute now, and no blur showed !!
I randomly test setting and i get it.
just active window vista compatibilty !!
it the only one make not blur screen ! .
![image](https://user-images.githubusercontent.com/24865815/44656545-42da7800-a9c7-11e8-8c2e-ae1d2cf08744.png)

**Comment by Tyriar** [comment] 2018-08-27 18:30
@djmisterjon beware that could break other things, the terminal may not work under compatibility mode for example.

**Comment by DanaMW** [comment] 2018-08-27 18:52
Tried it, the terminal doesn't work the language would not load ,,, gave up on that idea...

**Comment by djmisterjon** [comment] 2018-08-27 19:11
oh yes , it's true, am lucky , i don't use vscode terminal in my projet.
I also notice vscode seem run little slow down.
but it ok for temp fix, it allow me to work.
Waiting vscode team publish a update.

**Comment by xLobito** [comment] 2018-08-27 23:41
Just to notify. Visual Studio Live Share gets damaged if you change the compatibility mode. 

Besides, the issue is not triggered while coding or edit some settings/preferences. But, if you use continously the extension block (To install something), then the blurry appears. 

In the meantime, to avoid everything you should open vscode with gpu acceleration disabled.

**Comment by DanaMW** [comment] 2018-08-28 03:34
In my case it is blurry while in the editor only when the mouse is in the panel ON the text is it not. And GPU disabled foes not work completely. Unless something else is going on here, after a time it begins to blur again for me

**Comment by Lumenade** [comment] 2018-08-29 13:05
@djmisterjon This looks like it works. Make sure to set it for the right version, user vs system-wide (or both). 
![image 2](https://user-images.githubusercontent.com/4733331/44789266-2165c180-ab6a-11e8-9851-d5a69b7ff9dc.png)
Also, for me it didn't start getting blurry until there was an overlay, like a message or the command pallette.

**Comment by MeikTranel** [comment] 2018-08-29 14:36
I will try to confirm this on my machine later today and then update the electron issue if this proves to be related.
This should not be regarded as fixed though. Force disabling FXAA for certain apps isn't really handy in all situations.

**Comment by djmisterjon** [comment] 2018-08-29 15:02
this seem a issue for many engine with shadder.
http://pixijs.download/dev/docs/PIXI.filters.FXAAFilter.html
![image](https://user-images.githubusercontent.com/24865815/44796417-f3d54400-ab7a-11e8-9dd2-abc4eca1d765.png)

**Comment by DanaMW** [comment] 2018-08-29 20:09
After an hour of testing @djmisterjon 's fix is the most effective. It appears to have worked here (so far) thank you.
Note: On nvida card Control panel, Adding Code.exe Turning FXAA Off.

**Comment by ripvannwinkler** [comment] 2018-08-29 21:47
For me at least, the FXAA fix doesn't work. See screenshot:
![2018-08-29 16_46_33-form tsx - client - visual studio code](https://user-images.githubusercontent.com/130069/44817490-36167980-abab-11e8-83c8-dcd4cd9f16d1.png)

**Comment by Arcanemagus** [comment] 2018-08-29 22:00
@ripvannwinkler It looks like you set the global setting, try adding settings for `code.exe` explicitly as specified in the other comments.

**Comment by ripvannwinkler** [comment] 2018-08-30 09:27
It doesn't matter. Off is off, whether it's for one app or the whole system.

**Comment by djmisterjon** [comment] 2018-08-30 11:56
@ripvannwinkler 
Don't forget to click on **APPLY**, the button are _hidden bottom Right_ of the window panel.
Also reboot vscode after apply setting.
I dont test with global parameter! , so i don't know if nvidia know the vscode app and able to force change the native anti-aliasing setting of the app.

Also try to disable other anti-aliasing setting if this dont help you.

**Comment by gabaruga** [comment] 2018-12-21 22:02
Can confirm as of VS Code 1.30.1, Win 10.0.17763 and GeForce 960 with the latest drivers:
Disabling FXAA for VS Code specifically resolves blurrines on losing focus or context menus opening.

**Comment by why-does-ie-still-exist** [comment] 2019-01-05 05:54
Got a new laptop with a 1060 and intel integrated graphics, and the blurriness happened to me too. It's not vs code, because the blurriness also happens on [edex-ui](https://github.com/GitSquared/edex-ui), another electron project. However, after reading this thread, I turned off FXAA like @gabaruga did in Nvidia Control panel, and now both edex-ui and vs code work perfectly.

Help info:
```
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763
```

**Comment by Mrdapeng** [comment] 2019-01-14 05:57
if you are run vs-code on mac-os, please run npm install electron -g ,it will solve your problem

**Comment by bpasero** [comment] 2019-01-25 16:23
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:23 UTC
Labels: electron, electron-2.0.x-update, fixed-in-electron-3.0.x, font-rendering, upstream
