### ISSUE TITLE
Search: different results when editor is opened vs closed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39526] opened 2017-12-04 06:42 UTC
Steps to Reproduce:

0. check out vscode at https://github.com/Microsoft/vscode/commit/8a12b294de610aab61c32c02c7c148d981cf07e4
1. close all editors
2. search for `showMessageBox|showMessageBoxSync|confirmSync` with all three search options checked
3. notice number of results
4. open `src/vs/platform/windows/common/windows.ts`
5. search again

=> you see one less result

It looks like when the editor is opened, the `showMessageBoxSync` does not match, while it does when the editor is closed.

**Comment by roblourens** [comment] 2017-12-04 21:51
This is actually an interesting issue, only with local editor search. Simpler repro:

- Have a file with 
```
abc
abcd
```
- Cmd+f, search `abc|abcd` with the regex and whole word buttons toggled on
- Only one match, on abc. abcd should match too.

The problem is that we construct a regex like `abc|abcd`, and search, then the whole word check is a second pass on the regex match. But when searching the `abcd` line, the regex eagerly returns `abc` as the match, so it's flagged as an invalid match here: https://github.com/Microsoft/vscode/blob/20fc7885da8b30d07996a1e19dbddcc27b23058a/src/vs/editor/common/model/textModelSearch.ts#L504

I'm not sure what to do about that...

Whole word + regex search in general is hard. There are some bad cases for text search too.

**Comment by alexandrudima** [comment] 2017-12-06 10:46
@bpasero In the editor, whole word is a concept built by us on top of the JS regex engine. The JS regex engine does not support natively the concept of whole word.

In your case, you probably want to search for `\bshowMessageBox\b|\bshowMessageBoxSync\b`, but we "conceptionally" search for `\bshowMessageBox|showMessageBoxSync\b` because we don't parse the regex. 

We don't really search for `\bshowMessageBox|showMessageBoxSync\b`, but we search for `showMessageBox|showMessageBoxSync` and then validate the matches that they are whole words.

Since the editor find widget is implemented differently than the search across files, subtle differences might pop up

Since we don't want to search in the editor with the same code we search across files, and since we don't want to change the search across files solution, I will close this for now.

**Closed by alexandrudima** 2017-12-06 10:46 UTC
Labels: bug, search
