### ISSUE TITLE
Allow the configuration of the default npm query url

### ISSUE THREAD

**Issue by roemhildtg** [Microsoft/vscode#56397] opened 2018-08-14 19:50 UTC
I'd like to see a way to configure vs code to query a different npm repository. Many people are using private repositories to control access to their packages. For instance, a major provider is Verdaccio. https://verdaccio.org/ 

Allow us to configure the url to be something other than the default npm repository.

**Comment by sandy081** [comment] 2018-08-15 09:52
> I'd like to see a way to configure vs code to query a different npm repository.

Can you please explain why do you want to do it and when?

**Comment by roemhildtg** [comment] 2018-08-15 12:55
Hi @sandy081. VS code provides some automatic integration with package.json dependencies, for instance if I start typing a package name, vs code will auto populate the package name, and the latest version of that package. Also hovering over the package in package.json shows a tooltip with the latest version and package details. 

I'd like to be able to configure this because it would allow vs code integrate with any npm repository, not just the default one. I think this could be done easily using the user preferences json file, with a key that would be set to the user specified npm repository for vscode to use.

**Comment by sandy081** [comment] 2018-08-15 14:36
I suspect that you have an extension that  provides this feature.

**Comment by roemhildtg** [comment] 2018-08-15 14:50
I don't believe so. I think this is provided out of the box. 

See https://github.com/Microsoft/vscode/blob/e2a103434b0735055183425b12ae001919a94257/extensions/npm/package.nls.json#L10

**Comment by aeschli** [comment] 2018-08-16 14:50
`config.npm.fetchOnlinePackageInfo` is just to turn on off the feature.
We currently don't support private npm registries.

Duplicate of #54248

**Closed by aeschli** 2018-08-16 14:50 UTC
