### ISSUE TITLE
Dragging tab group edge in Markdown Preview is being grabbed by the preview window, stopping Preview from being resized.

### ISSUE THREAD

**Issue by kianryan** [microsoft/vscode#75256] opened 2019-06-11 10:50 UTC
Issue Type: <b>Bug</b>

After opening Markdown Preview (Open Preview To the Side), resizing the Preview window by grabbing the window split with the mouse and dragging has unexpected results.  Dragging to the left is mostly reliable, but dragging to the right jutters and stops or jumps.

It looks to be stopping when the mouse moves from the scroll bar over the preview window, before the window has had the opportunity to redraw, the preview window is grabbing the mouse event.  This stops further resizing without starting the process again.

It can be worked around by grabbing at the very top of the window at the tab.

I do not remember this being a problem on previous versions - it looks to be linked to https://github.com/microsoft/vscode/issues/32654, but may not have been prevelant until current releases.

Steps to Reproduce:

1. Open markdown document.
2. Click "Open Preview To the Side".
3. Click on window boundary between document and preview with mouse.
4. Drag to right.

VS Code version: Code - Insiders 1.36.0-insider (7bc29bf67c17608b11e23a8497c8f1de5a0922cf, 2019-06-11T08:32:47.289Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kianryan** [comment] 2019-06-11 10:56
![markdown_preview](https://user-images.githubusercontent.com/645069/59266623-fd2e2980-8c3f-11e9-8191-a75b5cd1fe9a.gif)

**Comment by mjbvz** [comment] 2019-06-11 15:31
Duplicate of #75090

**Closed by mjbvz** 2019-06-11 15:31 UTC
Labels: markdown
