### ISSUE TITLE
"Find in the selection" not activatable on find and replace

### ISSUE THREAD

**Issue by Mutton** [Microsoft/vscode#19910] opened 2017-02-04 07:34 UTC
- VSCode Version: 1.9.0
- OS Version: Windows 10 Pro (Build: 14393.693)

Steps to Reproduce:

1. select any range of text / code
2. press combination ctrl + h
3. try to press greyed out button with over-mouse description "Find in selection"

**Comment by bpasero** [comment] 2017-02-04 07:44
@Mutton it becomes enabled once you select text 👍

**Comment by Mutton** [comment] 2017-02-04 08:27
I selected text, sorry to not have it mentioned in the reproduction listing

**Comment by alexandrudima** [comment] 2017-02-06 15:07
Duplicate of #15125, which has a PR #15566

**Closed by alexandrudima** 2017-02-06 15:07 UTC
