### ISSUE TITLE
Missing menus in menu bar on Elementary (Loki)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55652] opened 2018-08-02 11:18 UTC
In the latest Insiders "File" and "Windows" and "Help" menu are missing from menubar:

![2018-08-02_13-16-55](https://user-images.githubusercontent.com/1898161/43580662-88a1ce58-9656-11e8-8d17-5860c1cbe892.png)

**Comment by alex-pex** [comment] 2018-08-02 12:25
Same issue : https://github.com/Microsoft/vscode/issues/55624

**Comment by Raydir** [comment] 2018-08-02 12:43
same problem here on a win 10 with german language Pack.

**Comment by neymanushka** [comment] 2018-08-02 13:13
same. Missing File,Windows,Help menu in latest vscode build. (windows 10)

**Comment by mjbvz** [comment] 2018-08-02 13:15
Duplicate of #55624

**Closed by mjbvz** 2018-08-02 13:15 UTC
Labels: bug
