### ISSUE TITLE
Support realtime adjustments of theme colors

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#20673] opened 2017-02-15 20:28 UTC
There are many great themes where the color and contrast don't fit the monitor or lighting conditions of the user.  

As example, the online theme editor allows adjusting overall colors under the 'color adjustments' button.
http://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai

**Comment by aeschli** [comment] 2017-02-16 08:12
duplicate of #11556

**Closed by aeschli** 2017-02-16 08:12 UTC
