### ISSUE TITLE
vscode web build instructions

### ISSUE THREAD

**Issue by vineelsai26** [microsoft/vscode#136361] opened 2021-11-03 14:33 UTC
I have tried to build vscode for the web with command 
```
 yarn gulp vscode-web
```
I got this folder as an output 

![Screenshot (2)](https://user-images.githubusercontent.com/52851879/140080318-c21eac15-4a5f-42ce-bf86-25585e2837ef.png)

But there are no instructions on how to run it or even build it for that matter please add instructions on how to run it and build it in your wiki and possibly here

**Comment by IllusionMH** [comment] 2021-11-03 16:10
Where you get that command?
Docs mention https://github.com/microsoft/vscode/wiki/How-to-Contribute#run (which should be launched after regular watch tasks)

This is not exactly same as vscode.dev

**Comment by vineelsai26** [comment] 2021-11-03 16:13
https://github.com/microsoft/vscode/wiki/How-to-Contribute#packaging

**Comment by joyceerhl** [comment] 2021-11-03 17:36
If you are looking to build vscode.dev from source, this is a duplicate of https://github.com/microsoft/vscode/issues/135856. If you are looking to build an extension for web, you can find instructions here: https://code.visualstudio.com/api/extension-guides/web-extensions

**Closed by joyceerhl** 2021-11-03 17:36 UTC
