### ISSUE TITLE
New keybinding complex commands don't have argument descriptions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#23709] opened 2017-03-30 23:59 UTC
When you run _generateCommandsDocumentation and look in the DevTools console output to get the complex command documentation (commands that can take arguments) for the [Complex Command](http://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) topic, there are 5 new commands for keybindings.editor.*

These commands are missing documentation for the arguments they take:

`keybindings.editor.defineKeybinding` - Define Keybinding
`keybindings.editor.removeKeybinding` - Remove Keybinding
`keybindings.editor.resetKeybinding` - Reset Keybinding
`keybindings.editor.searchKeybindings` - Search Keybindings
`keybindings.editor.copyKeybindingEntry` - Copy Keybindings

**Comment by sandy081** [comment] 2017-03-31 10:08
@gregvanl These commands do not take any args. Provided only `description` to give simple description of these commands. Also these are not complex commands :)

@jrieken Does the tool expects to always have args if `description` is provided.

**Comment by jrieken** [comment] 2017-03-31 10:16
Yeah, I think we have now overloaded the command description in an unhappy way. This feature was designed and used to generate the API doc page, not really as a utility for the new keybindings UX. We need to somehow differentiate these two use-cases.

**Comment by sandy081** [comment] 2017-03-31 10:45
I am not yet using the command description for new keybindings editor also did not add the description for that purpose.

I can remove the description from the above commands if it is meant for complex commands.

**Comment by jrieken** [comment] 2017-03-31 10:48
yeah, that would be favourable because otherwise more thing leak into the API commands page

**Comment by sandy081** [comment] 2017-03-31 12:39
Fixed by 2c2cf0bd313e4fcc6a59eb947659cb762f5d8607

**Closed by sandy081** 2017-03-31 12:39 UTC
