### ISSUE TITLE
WSL remote: High CPU from watcher service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119001] opened 2021-03-15 17:17 UTC
I am seeing an increasing number of people complaining about high CPU in remote scenarios from the `watcherService`. My understanding is that we run with polling in those environments because the file system capabilities do not allow for proper file watching.

We should at least try to figure out a better default to reduce high CPU loads or maybe allow the user to configure this.

Extracted from https://github.com/microsoft/vscode/issues/118613#issuecomment-799592291

**Comment by alimbada** [comment] 2021-03-15 17:22
@bpasero thanks for creating this. Just to add a bit more context, this has only become an issue since upgrading to 1.54.x. There were no problems prior to the upgrade.

**Comment by aeschli** [comment] 2021-03-15 22:31
It's already configurable: 
- `remote.WSL.fileWatcher.polling` (default true) to control whether polling is used or not
- `remote.WSL.fileWatcher.pollingInterval`: to change the default polling interval

But there has been many complaints of high CPU loads. So I'm going to change the default to false.

**Comment by aeschli** [comment] 2021-03-16 16:29
duplicate of https://github.com/microsoft/vscode-remote-release/issues/4637

**Closed by aeschli** 2021-03-16 16:29 UTC
Labels: file-watcher, freeze-slow-crash-leak, remote
