### ISSUE TITLE
Goto definition should jump to start of definition if used while inside of definition instead of saying "no definition found"

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#24480] opened 2017-04-11 05:53 UTC
I provide vscode a large definition range so the control-click tooltip shows the entire definition. The problem is, trying to navigate to the definition within the definition shows the 'no definition found' error. Instead, the cursor should jump to the start of the definition as normal.

Using peek definition (`Alt-F12`)
![image](https://cloud.githubusercontent.com/assets/356714/24894564/0bcc5cac-1e40-11e7-8c07-4b65375e0e57.png)

Using goto definition (`F12`)
![image](https://cloud.githubusercontent.com/assets/356714/24894583/2932ea2c-1e40-11e7-8936-545e94b6ef2d.png)

- VSCode Version: 1.11.1
- OS Version: Windows 10

**Comment by jacobdufault** [comment] 2017-04-11 06:04
I've worked around this by reducing the definition range if the definition request comes from within the entire type's definition range, but that's an ugly/hacky fix.

**Comment by jrieken** [comment] 2017-04-11 13:43
dupe of https://github.com/Microsoft/vscode/issues/22882

**Closed by jrieken** 2017-04-11 13:43 UTC
Labels: bug, editor-contrib

**Comment by jacobdufault** [comment] 2017-04-11 17:57
#22882 seems unrelated? That issue is about center positioning, this is about goto def while inside the def not working.
