### ISSUE TITLE
[TypeScript Quick Fix Bug] Global Typings for VSCode crashed after "define ..."

### ISSUE THREAD

**Issue by zero734kr** [microsoft/vscode#112687] opened 2020-12-16 22:46 UTC
- VSCode Version: 1.51.0 (hash: fcac248b077b55bae4ba5bab613fd6e9156c2f0c)
- OS Version: Linux Mint 20 Ulyana

![image](https://user-images.githubusercontent.com/51540538/102415237-97f68980-3fd6-11eb-9b60-6c12b537cb6c.png)

tsconfig.json used:
```json
{
    "extends": "@tsconfig/recommended/tsconfig.json",
    "compilerOptions": {
        "rootDir": "./",
        "moduleResolution": "node",
        "module": "CommonJS",
        "removeComments": false,
        "outDir": "dist",
        "resolveJsonModule": true
    },
    "exclude": ["node_modules", "dist", "test", "husky.config.js"]
}
```

Hello, I was using typescript, but the global typings apparently crashed after clicking on a quick vscode correction suggestion.
After clicking on ``Define ...``, VSCode is throwing ``Cannot find name error ...`` like ``Cannot find name 'Object'.`` in ``.ts`` files and  ``Cannot find global type 'Boolean'.`` in ``tsconfig.json`` files. 

I already knew that error can be fixed with ``compilerOptions.target`` option in tsconfig.json, but I clicked quick fix suggestion of vscode to fix faster than but there is a bug(i suppose it was bug).

All typings that I checked if had error ``Cannot find name error (or cannot find global type)`` are:
``Object``, ``Boolean``, ``Error (and the derivatives like TypeError)``, ``String``, ``Array``, ``Readonly``, ``Required``, ``parseInt``, ``encodeURI``, etc. 

Before that if it really is a bug and if I will receive updates to fix, there is some way to recover my typing file that it was before I clicked `` Define ... ''?

Steps to Reproduce:

1. Create a project with tsconfig.json above.
2. Type ``Object.values`` in index.ts and see quick fixes available.
3. Click on ``Define values ...`` (I don't remember what the correct alternative was, but it was the first option starting with ``Define values``)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/51540538/102415178-7f866f00-3fd6-11eb-85f6-fb178bc5020e.png)
![image](https://user-images.githubusercontent.com/51540538/102415197-8ad99a80-3fd6-11eb-8941-30cdb40b04dc.png)

**Comment by zero734kr** [comment] 2020-12-16 23:30
Also, when I run ``tsc`` in terminal it looks like there is no problem with global typings.

**Comment by mjbvz** [comment] 2020-12-17 00:07
TS 4.1+ should disable quick fixes for the standard library files. Let me know if you still see this after upgrading to VS Code 1.52+, which includes the new TS version

**Comment by mjbvz** [comment] 2020-12-17 00:08
Duplicate of https://github.com/microsoft/TypeScript/issues/29482

**Closed by mjbvz** 2020-12-17 00:07 UTC

**Comment by zero734kr** [comment] 2020-12-17 00:11
Ok I'll try after upgrading my vscode

**Comment by zero734kr** [comment] 2020-12-17 00:15
The problem was solved after upgrading. Thanks for your help and have a nice day(or night)
