### ISSUE TITLE
IPC "Search" crashed with exit code null and signal SIGKILL

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#57261] opened 2018-08-27 12:17 UTC
For the last few days I periodically see this in the Debug Console when working on my extension (Dart):

<img width="1253" alt="screen shot 2018-08-27 at 1 15 06 pm" src="https://user-images.githubusercontent.com/1078012/44659192-40921100-a9fb-11e8-99fb-629c04a4a3cd.png">

I don't know whether it's a VS Code (I can't see any other reports of it) issue or related to the Dart extension, but there's nothing useful in the dev console.

I'm not sure how I can get more information though, since it seems like something is sending SIGKILL to it so there's no error message :/

**Comment by joaomoreno** [comment] 2018-08-27 14:55
@roblourens Is this new?

**Comment by roblourens** [comment] 2018-08-27 15:00
I haven't seen it, I'll check it out

**Comment by roblourens** [comment] 2018-08-27 17:26
And if you see it while using code, does search stop working?

If the search process dies for some reason it should be restarted the next time a search happens. It's designed to time out and shut down anyway.

**Comment by DanTup** [comment] 2018-08-28 09:59
> or is it possible it just shows up when reloading the window?

Aha, that could be it - I do use the Restart button a lot while debugging the extension, and may even directly run the "Reload Window" command from within the instance running the extension. If that's likely all it is, it's probably expected so feel free to close. If I see it again, I'll pay more attention to what I'd done recently (usually I don't notice it until after).

**Comment by roblourens** [comment] 2018-08-28 21:38
No, it's still not expected for the search process to crash when reloading :)

Any more info would be helpful, most importantly, whether search still works after you notice that message

**Comment by DanTup** [comment] 2018-08-29 07:10
Oh, gotcha. I thought because it was a SIGKILL that it might be being deliberately killed as part of the restart. I'll post back if I can figure out any more info next time I see it though.

**Comment by DanTup** [comment] 2018-09-04 06:59
Ok, seen this a few times today, and each time it was when I clicked *Stop* to terminate the extension dev host. I don't know if that was always the case, but probably it's a good bet.

Does this make this by design? Maybe the message could be suppressed when you know you're killing the dev host to avoid confusion?

**Comment by DanTup** [comment] 2018-09-11 23:33
Haven't done much on the extension in the last week, so can't say. I don't ever attach though - I only ever launch by hitting F5 with my extension code open and letting it launch the dev extension host.

**Comment by roblourens** [comment] 2018-09-11 23:41
Ok, I'm going to close this since I've never been able to repro and nobody else seems to have seen it.

I meant the chrome developer tools (what you get from the "Toggle developer tools" command) because I was looking at an issue that sounded similar at first, that seems to come from the dev tools modifying vscode's environment. But I don't think it's the same.

**Closed by roblourens** 2018-09-11 23:41 UTC
Labels: bug, search

**Comment by DanTup** [comment] 2018-09-11 23:47
Oh, I see - I do sometimes open the dev tools (just to review the console, etc.).

I can try doing a little more debugging next week when back in the UK if I see it again and you think it's worthwhile.

**Comment by RMacfarlane** [comment] 2018-09-26 18:00
I've also just seen this while debugging, though with SIGPIPE instead of SIGKILL.

![screen shot 2018-09-26 at 10 55 58 am](https://user-images.githubusercontent.com/3672607/46099122-ccbe6200-c17a-11e8-874e-9fdd273ed969.png)

was using the "Launch VS Code" debug configuration in VSCode. I only see it for global search.

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 17.7.0

**Comment by RMacfarlane** [comment] 2018-09-26 18:07
This was while searching

**Comment by roblourens** [comment] 2018-09-26 18:13
Did it just happen once or does it happen again?

**Comment by RMacfarlane** [comment] 2018-09-26 18:16
It was happening consistently, even through reloads of the debug window. I've restarted and now can't reproduce it
