### ISSUE TITLE
Support custom markdown rendering in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#123021] opened 2021-05-05 20:59 UTC
In Classic Jupyter one can insert images into markdown cells. The images are stored as base64 encoded metadata in the corresponding notebook cell.

The value in the markdown is as follows:
```![Screen%20Shot%202021-05-04%20at%2016.23.48.png](attachment:Screen%20Shot%202021-05-04%20at%2016.23.48.png)```

Note the `attachment:Screen%` above

Is it possible via a custom markdown renderer, we (Jupyter Extension) can pull the contents from the notebook cell metadata & render the image in the markdown output?

@rebornix @mattbierner /cc

**Comment by mjbvz** [comment] 2021-05-06 19:33
@connor4312 How to renderers talk back to controllers?

**Comment by connor4312** [comment] 2021-05-06 19:35
Renderers talk back by way of the controller preloads, who have access to the `onDidReceiveKernelMessage` and `postKernelMessage` methods ([.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode-notebook-renderer/preload.d.ts))

**Comment by mjbvz** [comment] 2021-05-06 19:44
So the renderer could just call `postKernelMessage` and then wait for a response?  If that's the case, this pattern should work in markup renderers too (although it may not today since we hadn't thought this use case yet)

The bigger problem is that markdown-it plugins need to be synchronous, so you'd need to:

- Have synchronous access to the image data in your markup renderer plugin
- Hook into the markup rendering at a high level where you be async 
- Rewrite the markdown after it has been renderer (which would probably bad since it would result in the image flashing)

**Comment by connor4312** [comment] 2021-05-06 19:46
Renderers do not have access to this, _only_ controller preloads do. There's a discussion on this here: https://github.com/microsoft/vscode/issues/123160

**Comment by DonJayamanne** [comment] 2021-09-15 16:55
@connor4312 @mjbvz Do we have an update on this particular issue (I'm guessing this issue got lost/forgotten while looking into the renderer communication), we still have users running into this issue.

**Comment by mjbvz** [comment] 2021-09-16 18:48
We're just waiting for requests from people who want to use it :)

I think it should be enabled if you use proposed APIs though. Have you tried using a contribution similar to the built-in markdown math extension:

https://github.com/microsoft/vscode/blob/0ec3d48b703ff7abcd9028e2ad6052fcd81fbf8f/extensions/markdown-math/package.json#L62

**Comment by mjbvz** [comment] 2021-10-06 21:36
Duplicate of #121256 actually, which is also up for finalization this milestone

**Comment by mjbvz** [comment] 2021-10-06 21:38
@DonJayamanne Please test out the proposal in #121256. I don't think it provides everything you need to implement this specific feature, but it should be a good starting point we can built on

**Comment by DonJayamanne** [comment] 2022-03-02 09:47
@mjbvz im going to reopen this as the proposed api didn't provide what we need. i agree you have recognised this and have mentioned this.

however if we close this then the originally requested feature is never going to be addressed.

however if it's never going to be enabled that's a different matter.

**Comment by mjbvz** [comment] 2022-03-03 00:19
@DonJayamanne Can you explain the issues with #121256 ? I believe it should allow you to replace markdown image rendering  with a custom implementation that supports attachments

**Comment by DonJayamanne** [comment] 2022-03-03 03:21
@mjbvz Unless I've missed something there's no way for the renderer to access the metadata of the cell that's being rendered. I need access to the metadata as the image is encoded and stored in the cell metadata.

**Comment by mjbvz** [comment] 2022-03-04 00:07
Can you please add that as a comment on #121256. That's the issue tracking the api proposals

Closing this again as having two issue open for the same features makes it easier to overlook this specific request IMO

**Closed by mjbvz** 2022-03-04 00:07 UTC
Labels: api, *duplicate, under-discussion, api-finalization, notebook, notebook-markdown

**Comment by DonJayamanne** [comment] 2022-03-04 02:39
got it thanks
