### ISSUE TITLE
Keyboard shortcut for Copy Relative Path doesn work on Linux Debian 9

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#62480] opened 2018-11-02 14:40 UTC
- VSCode Version: 1.28.2, installed from Apt repos on Debian 9.5 amd64
- OS Version: Debian 9.5 amd64, KDE Plasma desktop

Steps to Reproduce:

1. When in some edited file press `ctrl+shift+alt+c` 

2. Paste clipboard content anywhere.

# Expected result:

Relative file path is copied to clipboard.

Copying via right-click on tab name, click Copy Relative path **works**.

# Actual result:

The path is not copied. This does not work even on changing the shortcut, e.g.:

```
    {
        "key": "ctrl+alt+0",
        "command": "copyRelativeFilePath",
        "when": "!editorFocus"
    },
    {
        "key": "ctrl+shift+alt+c",
        "command": "-copyRelativeFilePath",
        "when": "!editorFocus"
    }
```

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by kieferrm** [comment] 2018-11-02 15:53
@mrkafk the binding is defined to only work when the editor does not have focus. If you change your config to
```json
    {
        "key": "ctrl+alt+0",
        "command": "copyRelativeFilePath",
        "when": "editorFocus"
    }
```
it will work.

@isidorn it seems counterintuitive to only bind the shortcuts outside of the editor.

**Comment by isidorn** [comment] 2018-11-05 10:06
It is only when the editor does not have focus, because otherwise it triggers Toggle Vertical / Horizontal Editor Layout.
@bpasero imho the Toggle Vertical Horizontal Editor Layout no longer deserves a shprtcut. In fact I think that feature should be removed alltogether since we now support the grid.
Forwarding to @bpasero since he added this command

**Comment by bpasero** [comment] 2018-11-19 16:39
@isidorn I just checked and find >8000 people using this command over 7 days via keyboard. So I am having a hard time to just remove this keybinding.

As for having this command or not, I would not judge based on grid layout. It can be very convenient to quickly jump between vertical and horizontal layout with one command instead of having to remember 2 layout commands. Since you can currently not define when conditions based on grid layout state, this would mean you would have to type 2 different keys each time.

Moving back to you given this was moved to me to remove this keybinding.

**Comment by isidorn** [comment] 2018-11-19 17:08
No action needed, there is a workaround presented by Kai.
Closing as designed.
@bpasero I moved it to you since you added both commands that conflict here actually

**Closed by isidorn** 2018-11-19 17:08 UTC

**Comment by bpasero** [comment] 2018-11-19 17:11
@isidorn I did not add the keybinding `ctrl+alt+0` for "Copy Relative Path", the user did?

**Comment by isidorn** [comment] 2018-11-19 17:18
Oh, than we are good here.
