### ISSUE TITLE
Notebooks run icon and results are not aligned with other text in a cell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99165] opened 2020-06-02 17:45 UTC
Testing #98821

![image](https://user-images.githubusercontent.com/2193314/83552068-0bfb9500-a4be-11ea-9162-4946955df5cb.png)

**Comment by misolori** [comment] 2020-06-02 17:53
Duplicate of #99076. This was fixed today.

**Closed by misolori** 2020-06-02 17:53 UTC
