### ISSUE TITLE
Migrating deprecated terminal shell settings didn't do what I would expect

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125177] opened 2021-06-01 19:56 UTC
Testing #124836

With the following settings:
```
{
	"terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.shell.windows": "cmd.exe",
	// "terminal.integrated.shellArgs.windows": []
}
```

I saw the terminal migration notification and then clicked "Migrate", and my settings changed to:

```
{
    "terminal.integrated.defaultProfile.windows": "Generated",
	// "terminal.integrated.shellArgs.windows": []
}
```

Which is defintely not what I expected to happen.

**Comment by meganrogge** [comment] 2021-06-01 20:32
Perhaps if the shell/shellArgs match one of the detected profiles, the name of that profile can be used?

So in the sample above, `terminal.integrated.defaultProfile.windows: Command Prompt`

**Comment by TylerLeonhardt** [comment] 2021-06-01 23:41
I'm also kinda confused by this... here's what I had:

```json
{
    "terminal.integrated.shell.linux": "/snap/powershell/160/opt/powershell/pwsh",
    "terminal.integrated.shellArgs.linux": [
        "-Login"
    ],
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        }
    },
    "terminal.integrated.defaultProfile.linux": "pwsh"
}
```

and it turned it into:

```json
{
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        }
    },
    "terminal.integrated.defaultProfile.linux": "Generated"
}
```

**Comment by Tyriar** [comment] 2021-06-02 12:49
The behavior should be:

- If there is an exact match (eg. just `cmd.exe`), it should assign the existing profile as the default (`"Command Prompt"`).
- If there is not an exact match (eg. `pwsh -Login`), it should add the profile to the list and set it as the default. As for the name maybe something like `${basename(path)} (migrated)` would be best.

**Comment by meganrogge** [comment] 2021-06-03 02:16
To verify, see https://github.com/microsoft/vscode/pull/125352#issue-660462095 and try other combinations

**Comment by meganrogge** [comment] 2021-06-07 16:27
@eamodio or @TylerLeonhardt could you pls verify this?

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:14
@meganrogge with the following:

```json
"terminal.integrated.shell.osx": "/Users/tyleonha/.powershell-daily/pwsh",
    "terminal.integrated.shellArgs.osx": [
        "-Login"
    ],
    "terminal.integrated.profiles.osx": {
        "bash": {
            "path": "bash",
            "args": [
                "-l"
            ],
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh",
            "args": [
                "-l"
            ]
        },
        "fish": {
            "path": "fish",
            "args": [
                "-l"
            ]
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
        "pwsh (2)": {
            "path": "/Users/tyleonha/.powershell-daily/pwsh"
        }
    },
    "terminal.integrated.defaultProfile.osx": "pwsh (2)"
```

I don't get a notification. Is that expected?

**Comment by meganrogge** [comment] 2021-06-07 17:16
If you've already said don't show again to the notification in that workspace, yes.

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:16
@meganrogge ah... I hit the `x` which didn't show the notification until I reloaded the window.

**Comment by Tyriar** [comment] 2021-06-07 17:17
@TylerLeonhardt that was another fix that went in to make sure we're not annoying

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:21
Migration doesn't seem to be working for me. Here's a gif:

![repro](https://user-images.githubusercontent.com/2644648/121062494-faf0fe00-c779-11eb-9c47-1821e7aadd1c.gif)

These are the same settings as here https://github.com/microsoft/vscode/issues/125177#issuecomment-856115201

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:23
Ah looks like if I already define `terminal.integrated.profiles.osx` then this migration doesn't work. If I delete that setting (and use `zsh` instead as the default profile, the migration works.

**Comment by meganrogge** [comment] 2021-06-07 17:31
Meaning if you set the `defaultProfile` to the name of a profile that already exists within your `profiles.osx` it doesn't work? I think that's by design.

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:36
Gotcha. The only thing I'll mention is this, with a `terminal.integrated.profiles.osx` defined does _not_ prompt me:

```json
    "terminal.integrated.shell.osx": "/Users/tyleonha/.powershell-daily/pwsh",
    "terminal.integrated.shellArgs.osx": [
        "-Login"
    ],
    "terminal.integrated.profiles.osx": {
        "bash": {
            "path": "bash",
            "args": [
                "-l"
            ],
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh",
            "args": [
                "-l"
            ]
        },
        "fish": {
            "path": "fish",
            "args": [
                "-l"
            ]
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
        "pwsh (2)": {
            "path": "/Users/tyleonha/.powershell-daily/pwsh"
        }
    },
    "terminal.integrated.defaultProfile.osx": "bash",
```

but this without it defined _does_ prompt me:

```json
    "terminal.integrated.shell.osx": "/Users/tyleonha/.powershell-daily/pwsh",
    "terminal.integrated.shellArgs.osx": [
        "-Login"
    ],
    "terminal.integrated.defaultProfile.osx": "bash",
```

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:38
I guess I would expect the migration to still happen (and a new profile be added to my existing `terminal.integrated.profiles.osx`) but maybe that's out of scope.

**Comment by meganrogge** [comment] 2021-06-07 17:38
That seems wrong

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:40
@meganrogge ah... just opened dev tools:

```
ERR Cannot add property /Users/tyleonha/.powershell-daily/pwsh (migrated), object is not extensible: TypeError: Cannot add property /Users/tyleonha/.powershell-daily/pwsh (migrated), object is not extensible
    at Object.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2851:102800)
```

**Comment by meganrogge** [comment] 2021-06-07 17:41
it's working for me on Windows.

**Comment by meganrogge** [comment] 2021-06-07 17:42
https://github.com/microsoft/vscode/pull/125352/files#diff-8df911bf58ca35baec7e0c02b60c36c1dc33694f7a61089ba69adf888c98f466R385

**Comment by meganrogge** [comment] 2021-06-07 17:43
Hmm what does that mean?

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:45
Here's a repro on non-Windows without PowerShell:

```json
    "terminal.integrated.shell.osx": "zsh",
    "terminal.integrated.shellArgs.osx": [
        "-l", "-i"
    ],
    "terminal.integrated.defaultProfile.osx": "bash",
    "terminal.integrated.profiles.osx": {
        "bash": {
            "path": "bash",
            "args": [
                "-l"
            ],
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh",
            "args": [
                "-l"
            ]
        },
        "fish": {
            "path": "fish",
            "args": [
                "-l"
            ]
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        }
    },
```

**Comment by meganrogge** [comment] 2021-06-07 17:45
any errors in dev tools with that repro? or if you turn on trace logging?

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:49
Beyond this:

```
[2021-06-07 10:46:43.443] [renderer3] [error] Cannot add property zsh (migrated), object is not extensible: TypeError: Cannot add property zsh (migrated), object is not extensible
    at Object.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2851:102800)
```

I don't see anything... which Output should I dig into specifically?

**Comment by meganrogge** [comment] 2021-06-07 17:50
Run set log level -> trace -> open developer tools. you should see a migration message. migrated from shell/shellArgs...

**Comment by meganrogge** [comment] 2021-06-07 17:51
I wonder if this could be the issue https://github.com/microsoft/vscode/issues/125177#issuecomment-856135100 @Tyriar

**Comment by TylerLeonhardt** [comment] 2021-06-07 17:52
Hmmm I don't see that....only:

 ```
TRACE CommandService#executeCommand setContext
log.ts:272 TRACE KeybindingService#dispatch ⌃` workbench.action.terminal.toggleTerminal
log.ts:272 TRACE CommandService#executeCommand workbench.action.terminal.toggleTerminal
log.ts:272 TRACE terminalInstance#ctor (instanceId: 1) Objectargs: (2) ["-l", "-i"]color: undefinedexecutable: "zsh"icon: b {id: "terminal-bash", definition: {…}, description: undefined}useShellEnvironment: true__proto__: Object
log.ts:278 DEBUG Terminal process ready (shellProcessId: 94128)
log.ts:272 TRACE KeybindingService#dispatch ⇧⌘P workbench.action.showCommands
log.ts:272 TRACE CommandService#executeCommand workbench.action.showCommands
log.ts:272 TRACE CommandService#executeCommand workbench.action.toggleDevTools
log.ts:272 TRACE Layout#layout, height: 1415, width: 1289
log.ts:296   ERR Cannot add property zsh (migrated), object is not extensible: TypeError: Cannot add property zsh (migrated), object is not extensible
    at Object.run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2851:102800)
log.ts:272 TRACE CommandService#executeCommand setContext
```

**Comment by Tyriar** [comment] 2021-06-07 17:54
The fix here is probably:

```ts
const profiles = { ...this._configurationService.inspect<{ [key: string]: ITerminalProfileObject }>(TerminalSettingPrefix.Profiles + platform).userValue } || {};
```

**Comment by Tyriar** [comment] 2021-06-07 17:57
Even better is marking the type as readonly: `Readonly<{ [key: string]: ITerminalProfileObject }>`

**Comment by Tyriar** [comment] 2021-06-07 18:02
We might be able to catch this in the future with https://github.com/microsoft/vscode/issues/125690

**Comment by meganrogge** [comment] 2021-06-07 18:14
I don't understand what's going wrong here though - if userValue is undefined, profiles get set to `{}` already
```
const profiles = this._configurationService.inspect<{ [key: string]: ITerminalProfileObject }>(TerminalSettingPrefix.Profiles + platform).userValue || {};
```

**Comment by meganrogge** [comment] 2021-06-07 18:14
I'd think making it readonly would be even worse since then we can't add properties to it - such as the newly created profile

**Comment by Tyriar** [comment] 2021-06-07 18:15
Which works fine, the failure case was when @TylerLeonhardt had profiles set. The `Readonly` there just corrects the type we're receiving from the config service

**Comment by meganrogge** [comment] 2021-06-07 18:22
ok, should this be a candidate or moved to June?

**Comment by Tyriar** [comment] 2021-06-07 18:26
I think it meets the candidate bar, we really want migration to be solid

**Closed** 2021-06-07 19:52 UTC
Labels: bug, candidate, terminal, terminal-profiles, verification-found
