### ISSUE TITLE
can not open editor of any file.

### ISSUE THREAD

**Issue by gzx-miller** [microsoft/vscode#82218] opened 2019-10-10 08:12 UTC
Issue Type: <b>Bug</b>

bootstrap-window.js:215 TypeError: Cannot read property 'layout' of undefined
    at I.layout (textEditor.ts:223)
    at g.layout (editorControl.ts:233)
    at e.layout (editorGroupView.ts:1491)
    at f.layout (gridview.ts:631)
    at f.layout (splitview.ts:130)
    at t.SplitView.layoutViews (splitview.ts:855)
    at t.SplitView.layout (splitview.ts:423)
    at m.layout (gridview.ts:284)
    at v.layout (gridview.ts:774)
    at p.layout (grid.ts:249)
    at p.layout (grid.ts:596)
    at k.layout (editorPart.ts:73)
    at t.CenteredViewLayout.layout (centeredViewLayout.ts:84)
    at e.doLayout (editorPart.ts:977)
    at e.layout (editorPart.ts:970)
    at f.layout (gridview.ts:631)
    at f.layout (splitview.ts:130)
    at t.SplitView.layoutViews (splitview.ts:855)
    at t.SplitView.layout (splitview.ts:423)
    at m.layout (gridview.ts:284)
    at v.layout (splitview.ts:130)
    at t.SplitView.layoutViews (splitview.ts:855)
    at t.SplitView.layout (splitview.ts:423)
    at m.layout (gridview.ts:284)
    at f.layout (splitview.ts:130)
    at t.SplitView.layoutViews (splitview.ts:855)
    at t.SplitView.layout (splitview.ts:423)
    at m.layout (gridview.ts:284)
    at v.layout (gridview.ts:774)
    at p.layout (grid.ts:249)
    at p.layout (grid.ts:596)
    at t.Workbench.layout (layout.ts:826)
    at Q.onWindowResize (desktop.main.ts:166)
    at _register.c.addDisposableListener.t (desktop.main.ts:145)

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-apollo|apo|1.11.0
vscode-eslint|dba|1.9.1
auto-close-tag|for|0.5.6
python|ms-|2019.10.41019
csharp|ms-|1.21.4
vscode-react-native|msj|0.12.1
react-node-desktop-debugger|rea|2.0.0
vscode-multiclip|sle|0.1.5
json|Zai|1.0.2

</details>

**Comment by bpasero** [comment] 2019-10-10 08:41
Sounds like grid issue to me.

**Comment by bpasero** [comment] 2019-10-10 08:41
//cc @isidorn for centered layout

**Comment by isidorn** [comment] 2019-10-10 09:16
Looking at the callStack it seems like the [`textEditor.layout`](https://github.com/Microsoft/vscode/blob/3b473663d99e2b951bac456a6cb5b2d3fb786c2c/src/vs/workbench/browser/parts/editor/textEditor.ts#L229) is being called before the `TextEditor` is created. 
Centered editor layout is enabled in this case, however it seems to be just a middle man here.

**Comment by gzx-miller** [comment] 2019-10-10 10:01
Hello, @isidorn , when I can get the fixed version?

**Comment by isidorn** [comment] 2019-10-10 10:30
We are still looking into a fix. 
If you F1 > toggle centered layout do you still see this
Until we push a fix I suggest you use vscode insiders if you work is being blocked (sorry about that!)
https://code.visualstudio.com/insiders/

**Comment by isidorn** [comment] 2019-10-10 12:50
@gzx-miller can you please include a screenshot of vscode?

**Comment by mayeths** [comment] 2019-10-10 15:36
I meet similar error. vscode go to blank when I open folder in remote wsl(but everything is ok in windows)
![ok](https://user-images.githubusercontent.com/37110574/66583740-7752c880-ebb6-11e9-97de-b6a89123a0b6.png)
![crash](https://user-images.githubusercontent.com/37110574/66583739-76ba3200-ebb6-11e9-9899-7bb796ca55f5.png)

**Comment by isidorn** [comment] 2019-10-10 15:39
@mayeths that seems like an unrelated issue, please open a new one (unless you see the same exception in your debug console which I doubt is the case)
fyi @aeschli

**Comment by mayeths** [comment] 2019-10-10 15:44
> @mayeths that seems like an unrelated issue, please open a new one (unless you see the same exception in your debug console which I doubt is the case)
> fyi @aeschli

my mistake :)

**Comment by sbatten** [comment] 2019-10-10 18:23
is this 100% repro? @gzx-miller can you reproduce this issue in different workspaces?

The stack suggests the error is on window resize so I've tried the following variables:

1) Using and not using centered layout
2) Resizing the window and quickly opening and closing files
3) Adding editor groups to centered layout (which removes the centered layout as expected)
3) Reloading the window in various combinations

I was not able to repro yet.

**Comment by gzx-miller** [comment] 2019-10-11 01:39
![Snipaste_2019-10-11_09-38-41](https://user-images.githubusercontent.com/28978984/66618234-feca2700-ec0a-11e9-8a59-fec51729957c.png)

**Comment by gzx-miller** [comment] 2019-10-11 01:41
It's 100% repro in any project. now, I'm using vscode inside well, thank you.

**Comment by isidorn** [comment] 2019-10-11 07:49
@gzx-miller please answer all questions posted by @sbatten [here](https://github.com/microsoft/vscode/issues/82218#issuecomment-540711290) thanks!

Insiders can open multiple editors, what do you mean? Can you open another issue regarding this. Please note that insiders does not have all your extensions installed.

**Comment by gzx-miller** [comment] 2019-10-11 09:02
sbatten ask:
   is this 100% repro?  can you reproduce this issue in different workspaces?
my answer:
   It's 100% repro in any project.
insider version can not open multiple editors. I won't open another issue, because I find another way to recover my environment: install an old version of vscode, and config forbid upgrade. @isidorn

**Comment by joaomoreno** [comment] 2019-10-11 09:19
@gzx-miller Can you share a screenshot of Insiders as well?

Can you try running in a separate user data dir: `code --user-data-dir NEW_FOLDER`? Does it work then?

**Closed** 2019-10-18 12:53 UTC
Labels: freeze-slow-crash, important, needs more info, new release, workbench-editor-grid
