### ISSUE TITLE
Wrong JSDoc Parse

### ISSUE THREAD

**Issue by Hoto-Cocoa** [Microsoft/vscode#35413] opened 2017-09-30 07:01 UTC
- VSCode Version: 1.16.1
- OS Version: Windows 10 Pro (Build 15063.608)

Steps to Reproduce:

1. Install `jquery` from npm.
2. Require `jquery`, and use that as function.
3. Hover mouse on code that wrote on step 2.

![image](https://user-images.githubusercontent.com/21969938/31043512-09d7fc68-a5f8-11e7-9942-c7d25494a1e4.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-30 15:58
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/16498

Closing as duplicate of https://github.com/Microsoft/TypeScript/issues/16498

**Closed by mjbvz** 2017-09-30 15:58 UTC
Labels: duplicate, javascript, upstream
