### ISSUE TITLE
SCM: Add "stage ranges" action/button to diff view

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#26067] opened 2017-05-05 18:29 UTC
Inspired by [GitX](https://rowanj.github.io/gitx/), it would be useful to add a "stage lines" action/button for the selected lines in diff view. This would make the partial commit feature much more discoverable.

GitX:
![timey branch master 2017-05-05 11-26-15](https://cloud.githubusercontent.com/assets/173559/25759088/e220a5bc-3185-11e7-9814-8058ed04e5ea.png)

Mock:
![server js working tree - timey 2017-05-05 11-29-00](https://cloud.githubusercontent.com/assets/173559/25759178/20b0080e-3186-11e7-9f8b-bc2b8ca67f29.png)

**Comment by joaomoreno** [comment] 2017-05-08 06:23
We're gonna add them to the context menu for now: #25766

**Comment by michaeljota** [comment] 2017-05-16 20:31
I think this should work with selection as well, should switch to `Stage selected lines` when a selection it's done.

**Comment by danawoodman** [comment] 2017-10-05 22:54
This should at least be added to the right click context menu. A button would be nice as well.

**Comment by SgtPooki** [comment] 2017-11-05 20:45
Can we add an unstage(reset -p) and discard(checkout -p) button as well?

**Comment by felixvd** [comment] 2019-12-11 05:00
Staging ranges (hunks) is now available in the context menu, but the user in [this issue](https://github.com/microsoft/vscode/issues/43887) did not discover it. I believe the current UI makes this too hard to discover.

Consider this situation:

<img width="1089" alt="Screen Shot 2019-12-10 at 20 39 03" src="https://user-images.githubusercontent.com/4535737/70526568-39a9f600-1b8d-11ea-92c4-6e395656636a.png">

To stage the deleted hunk, the area that the user need to interact with is highlighted in green:

<img width="1089" alt="Screen Shot 2019-12-10 at 20 39 03_2" src="https://user-images.githubusercontent.com/4535737/70592549-93f29780-1c1d-11ea-983c-2d045ff22be5.png">

This affordance is exceedingly difficult to find, since interacting with the two most visible elements (highlighted in red) leads to failure: 
- right-clicking in the greyed-out area of a hunk of deleted lines does not open the context menu
- right-clicking in the left side of the diff view does not show the staging option (this behavior is apparently [by design](https://github.com/microsoft/vscode/issues/81912#issuecomment-538949953), although I can't follow the rationale)

To find this feature, the user has to right-click the line _above_ the deleted hunk, on the right side of the screen, which is not highlighted in any way. In short, this is not a well designed interface element and should be changed.

**Comment by timjs** [comment] 2020-04-16 05:11
Any progress on this? I read #3563 and an UI like GitHub desktop provides would aid a login discoverability! Atom does this in the same way.

**Comment by the0neWhoKnocks** [comment] 2020-08-04 15:08
I agree with @timjs. I'd never really used hunk or partial staging until I started using Atom. When committing changes, everything is visible and easy to understand.

![atom--staging-changes](https://user-images.githubusercontent.com/344140/89310477-9d57c680-d629-11ea-837a-ac1db6b91ef1.gif)

**Comment by felixvd** [comment] 2021-03-26 06:55
@joaomoreno Is this not going to happen? The vast majority of successful git GUIs have a button to stage ranges/hunks: Github Desktop, Gitkraken, Sourcetree, Atom. This is not a coincidence. Why is such a basic feature hidden behind an extra click in VSCode? And why is this not getting any attention? Is anyone happy with VSCode's version control interface? I really don't get it.

**Comment by niklaas** [comment] 2021-07-16 05:43
I would love this being implemented. Probably this feature is the last one that makes me switch from vim with fugitive without the feeling that something is missing. 

In fact, I don't need a UI button to click but an action I can trigger with a keystroke so that the hunk under the cursor gets staged. That would be so awesome! 🤩

**Comment by michaeljota** [comment] 2021-07-18 00:56
@niklaas There is a "Git Staged Selected Ranges" command, and it does have a keybinding, so you can trigger it with your keyboard.

**Comment by niklaas** [comment] 2021-09-03 13:46
@michaelchiche yep, I know about that, thank you! I want to circumvent selecting a range though. It would be super cool if it would be sufficient to just let the cursor reside on the hunk and then issue a command.

**Comment by technodrome** [comment] 2021-10-03 18:09
LOL, microsoft, 4 years and 5 months to show a couple of arrows? :laughing:  Way to go! How many users begging you to be user-friendly in the UI will it take for you to actually realize it is way easier to click a couple of arrows than fiddling around with some crazy complex keyboard shortcuts for BASIC git ops?!

And yes, don't forget to ignore such basic user tickets for another 4 years, because it must be so hard to implement. Laughable, terrible, unfathomable.

**Comment by brunovieira97** [comment] 2022-05-18 13:19
I often stage only parts of a file's changes, and when using IntelliJ IDEA I found a very nice UI for this use case:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/19749621/169046438-44eb3aae-0079-415b-a94a-3465538271d8.png">

Maybe it could serve as inspiration for a more user-friendly experience, adapting to the app's Design System of course.

Decorators around "hunks" (or change blocks) would be an awesome addition to Code, allowing us to more easily select the changes without needing to deal with context menus and not-so-obvious options.

**Comment by sanketwagh147** [comment] 2022-11-17 17:04
This would be helpfull

**Comment by Elijahh177** [comment] 2022-12-09 13:59
This functionality already exists for the "Diff Peek" in normal editor windows:

![grafik](https://user-images.githubusercontent.com/53260105/206716128-a8488540-c136-419c-8e54-2251e75b83a1.png)

The `+` Button triggers the "git.stageChange" action, which stages the whole chunk. The action can have a keybinding, **but it does not work in normal diff editors**.

IMO, supporting just the action in normal diff editors would be sufficient for a first iteration.

@lszomoru any chance, that this might be considered?

**Comment by ELLIOTTCABLE** [comment] 2023-04-04 18:31
The above came up in the conversation around #43887 ([several](https://github.com/Microsoft/vscode/issues/43887#issuecomment-535269691) times) was requested in #48965 and #48323; then again in #143945, which was closed. It's come up again (#118898), and again …

… oh, wow, _I_ literally opened one about this four years ago, wow: #69892
> I can't actually get this to work at the moment, but I think that's an unrelated issue on my end.

----

The OP of this Issue is basically satisfied, so IMO this one should be closed as complete, and a new one to track the _minor_ but _critical_ issue of there being no ability to keybind the _already implemented_ `git.stageChange` in places other than the inline editor (... and thus no reasonable/quick/interactive replacement for `git add -p`.)

**Comment by jsonMartin** [comment] 2023-08-08 19:53
I would also **love** a stage hunk button for VSCode. The nice SCM & diff editor features are the only reason that keeps me coming back to Webstorm.

**Comment by lszomoru** [comment] 2023-08-21 15:08
Adding @hediet as this is a feature request for the diff editor.

**Comment by hediet** [comment] 2024-03-22 10:05
Fixed in https://github.com/microsoft/vscode/issues/206808.

**Closed by hediet** 2024-03-22 10:05 UTC
Labels: help wanted, diff-editor, scm
