### ISSUE TITLE
Problem changing theme while the Readme MD Preview is open

### ISSUE THREAD

**Issue by DrBooty** [microsoft/vscode#72366] opened 2019-04-15 20:30 UTC
Issue Type: <b>Bug</b>

use an .md file to have access to a preview,  upon opened the preview try to open the change theme dialog through the gear button on the editor's lower left corner.

Sometimes it would blink and disappear, and other times it would not appear at all.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.87GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
sql-formatter|cym|1.0.2
xml|Dot|2.4.0
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
gc-excelviewer|Gra|2.1.32
vscode-power-mode|hoo|2.2.0
sftp|lix|1.12.2
vscode-apache|mrm|1.2.0
vscode-language-pack-es|MS-|1.33.2
mssql|ms-|1.5.0
java|red|0.42.1
highlight-matching-tag|vin|0.9.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
vscode-icons|vsc|8.5.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-05-10 18:48
Duplicate of #68019

**Closed by mjbvz** 2019-05-10 18:48 UTC
Labels: webview
