### ISSUE TITLE
Selecting Extension in list locks up VSCode

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#54414] opened 2018-07-16 20:14 UTC
Issue Type: <b>Bug</b>

1. switch to the "extensions" view in the activity bar.
2. click on an extension, which usually shows details on the right

Details are not shown, and the app locks up: you cannot click on anything.  Need to force quit

VS Code version: Code - Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:11:22.192Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.93GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
Bookmarks|ale|9.0.0
project-manager|ale|8.0.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.36
prettier-vscode|esb|1.5.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.12.0
svg|joc|0.1.1
Angular2|joh|6.1.1
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.8
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-versionlens|pfl|0.21.1
quicktype|qui|12.0.2
code-settings-sync|Sha|3.0.0
stylelint|shi|0.37.0
rewrap|stk|1.9.1
sort-lines|Tyr|1.7.0
change-case|wma|1.0.0

(4 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2018-07-17 01:50
Duplicate of #54375

**Closed** 2018-07-17 13:13 UTC
Labels: *duplicate, extensions
