### ISSUE TITLE
Windows Spdylog: changing date to the past makes window reload/open super slow

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#42752] opened 2018-02-01 16:29 UTC
Steps to Reproduce:

1. this reproduces out of sources
2. run and open just one window
3. go to date settings and go back in time 1 month
4. file > new window

=> this takes 10-20s on my system.

When I comment out `spdylog` in the `logService` as well as `outputService` I can no longer reproduce. 

![before](https://user-images.githubusercontent.com/900690/35690312-d63cf572-0775-11e8-8847-49aae2e58165.gif)

**Comment by joaomoreno** [comment] 2018-02-28 15:44
Investigating. Just by changing the month back, the CPU goes crazy:

![image](https://user-images.githubusercontent.com/22350/36796746-98ff3f58-1ca6-11e8-97d6-b258984499b4.png)

**Comment by joaomoreno** [comment] 2018-02-28 16:08
We're hitting this all the time, since `time_since_op` is negative in this case!

https://github.com/gabime/spdlog/blob/master/include/spdlog/details/async_log_helper.h#L364

So CPU just spins. 🐛

**Comment by bpasero** [comment] 2018-02-28 16:19
@joaomoreno wow

**Comment by joaomoreno** [comment] 2018-03-01 09:57
Moving to March due to high risk change. Sorry for taking so long to look at this. 😢

**Comment by joaomoreno** [comment] 2018-06-27 09:29
Snowplowed once again...

**Comment by joaomoreno** [comment] 2018-07-10 15:10
This mechanism seems to have changed in spdlog 0.17.0. Will create a new build based on that and test.

**Comment by joaomoreno** [comment] 2018-07-12 09:33
Yep, that version of spdlog fixes it! :fireworks:

**Closed** 2018-07-12 09:37 UTC
Labels: bug, freeze-slow-crash, log

**Comment by JacksonKearl** [comment] 2018-08-02 21:16
This can't be reproduced on managed computers as we aren't allowed to change the date. @sbatten can you change your date?
