### ISSUE TITLE
Slow scrolling search view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#190600] opened 2023-08-16 17:47 UTC
1. Create a workspace with this file: [Image](https://github.com/microsoft/vscode/assets/12821956/ff9d2355-8276-47bc-b2d1-1ce6db8bdad4) (this is the requests logo svg)
2. Search for `2.0` in the search view
3. Scroll through results and notice janky scrolling

I've attached the profile: [Trace-20230816T104602.json.txt](https://github.com/microsoft/vscode/files/12362127/Trace-20230816T104602.json.txt)

The `lcut` function seems to be the culprit 

![Image](https://github.com/microsoft/vscode/assets/12821956/31db78db-b0fb-4638-9f74-b69170375f00)

**Comment by osortega** [comment] 2024-12-19 04:12
Duplicate of https://github.com/microsoft/vscode/issues/166390
Closing this in favor of the older one

/duplicate

**Closed by osortega** 2024-12-19 04:12 UTC
Labels: bug, search, confirmed
