### ISSUE TITLE
Random order for git repositories in Source Control window and in git command popup

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#140512] opened 2022-01-11 18:22 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19042

Issue 1: Repositories are not sorted according to user preferences in Source Control window.

Issue 2: Repositories are sorted differently from the Source Control window, as well as from the user preferences.

Result: Both lists of repositories appear to be random. They are not consistent with each other, and they are not consistent with the settings: sort by name, sort by path, sort by status.

Steps to Reproduce:

1. Open 2 git repositories in the same window
2. Make a change to a repo
3. In the Source Control window, the repositories are in a random order.
4. Make a commitment.
5. Push with the command "git.push". A popup window appears, and the repositories are in a random order.

**Comment by lszomoru** [comment] 2022-03-21 19:51
Closing this as duplicate of https://github.com/microsoft/vscode/issues/133759.

**Closed by lszomoru** 2022-03-21 19:51 UTC
Labels: bug, git
