### ISSUE TITLE
'<center>' tag marked in red color when it shouldn't 

### ISSUE THREAD

**Issue by GustavoRodriguesdeBrito** [Microsoft/vscode#59947] opened 2018-10-04 05:59 UTC
Issue Type: <b>Bug</b>

the <center> tag keeps appearing in red as if it has been typed incorrectly even if it is created by the autocomplete feature itself, regardless where it is placed on the HTML document or the contents inside of it.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.1.1

</details>

**Comment by mjbvz** [comment] 2018-10-04 16:35
Duplicate of #56467

**Closed by mjbvz** 2018-10-04 16:35 UTC
Labels: editor
