### ISSUE TITLE
Possible dispute between the renderer process and the main process on new version installation "hot reload"

### ISSUE THREAD

**Issue by hemulin** [Microsoft/vscode#28600] opened 2017-06-13 08:55 UTC
- VSCode Version: 1.13.0
- OS Version: Lubuntu 16.04

Installed the new version in the background while working on the previous one (1.12).
Once the installation finished, reloaded the window (`ctrl` + `shift` + `p` => "reload window").
Apparently this caused some weird behavior where the "about" menu item shows v1.12, the release notes show v1.13 and tons of things didn't work (no debug, no integrated terminal, no go-to-definition, no multicursor).

After mentioning it in another [issue](https://github.com/Microsoft/vscode/issues/28324), I was [told](https://github.com/Microsoft/vscode/issues/28324#issuecomment-307705083) by @alexandrudima:

> Your problem stemmed I think from our multi-process architecture. When reloading a window, only the 
renderer process + extension host of that renderer process gets reload, while the main process survives. I think you've run into the case where the main process was running at version N and the renderer process was running at version N+1. That is something perhaps @bpasero  or @joaomoreno would want to hear about such that we can quit or give a good error message instead of running in this inconsistent state.

Eventually, completely closing the running vscode and reopen it (not via "reload window") fixed everything.

**Comment by joaomoreno** [comment] 2017-06-14 09:05
How did you install? Zip, deb, rpm?

**Comment by hemulin** [comment] 2017-06-14 09:20
deb

**Comment by Tyriar** [comment] 2017-06-14 16:01
Yes right now things will break if you update and don't close the window. If you try to open a new window for example you get an ENOENT error.

I don't think we could disallow the update to happen because the system updater can be launched without VS Code knowing and it cannot wait or the update will fail. Perhaps the deb pre-install steps could send SIGQUIT to each VS Code window? I'm not sure that's better situation though as they would lose their terminal sessions, undo stack, etc.

**Comment by hemulin** [comment] 2017-06-15 06:53
Putting aside the prevention of such incoherent state. The fact that the release notes showed version N+1 while the "about" showed N suggests that it is possible to identify this divergence. Can't the renderer process present the user a message saying something like "VScode update has been completed. Please close all the running VScode processes and relaunch", as @alexandrudima suggested?

**Comment by Tyriar** [comment] 2017-06-16 14:38
We probably could detect this by polling some file periodically. @bpasero what would you suggest as the best way to detect that the version has changed, checking exe size, package.json version?

**Comment by bpasero** [comment] 2017-06-16 17:00
I find the solution we have on Windows elegant where the installer checks for a mutex being set by the running application. And the installer basically preventing to run as long as that mutex is not cleared.

**Comment by joaomoreno** [comment] 2017-11-23 14:37
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by alexandrudima** [comment] 2017-11-24 13:53
I believe that we should fix this issue, as it leads to undefined behaviour.

**Comment by joaomoreno** [comment] 2017-11-24 17:38
Oh man, I didn't mean to close this one, that was definitely an oversight. Thanks @alexandrudima.

**Comment by Tyriar** [comment] 2018-06-22 01:02
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/45569

**Closed by Tyriar** 2018-06-22 01:02 UTC
Labels: bug, install-update, linux
