### ISSUE TITLE
incremental selection inside a string selects too much

### ISSUE THREAD

**Issue by slootzky** [Microsoft/vscode#34292] opened 2017-09-13 13:31 UTC
my issue is if I’m standing inside a string , first thing it will select is the whole string with the `'` 
so let’s say I’m in `'vscode'` , first thing that will get selected is `'vscode'` instead of just `vscode`

**Comment by jrieken** [comment] 2017-09-14 09:44
duplicate of #4795

**Closed by jrieken** 2017-09-14 09:44 UTC
Labels: duplicate, editor
