### ISSUE TITLE
Unexpected terminal related behaviour

### ISSUE THREAD

**Issue by dklunarian** [Microsoft/vscode#8087] opened 2016-06-24 06:44 UTC
- VSCode Version: 1.2.1
- OS Version: Win7 x64 Simplified Chinese

Steps to Reproduce:

1. Ctrl + ` won't work
2. In terminal, chinese characters are squeezed into a mess

**Comment by Tyriar** [comment] 2016-06-24 07:05
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-24 07:05 UTC
