### ISSUE TITLE
Explorer - canceling input box focus tree instead of previously focused item

### ISSUE THREAD

**Issue by frobinsonj** [Microsoft/vscode#70069] opened 2019-03-08 15:17 UTC
Issue Type: <b>Bug</b>

Creating in root instead of selected folder:
![2019-03-08_15-07-46](https://user-images.githubusercontent.com/16726902/54036616-f6f95e80-41b3-11e9-93b1-30e3bf8a7321.gif)
![2019-03-08_15-14-46](https://user-images.githubusercontent.com/16726902/54036994-f44b3900-41b4-11e9-9481-ccf4baa50be0.gif)

Duplicating Folder:
![2019-03-08_15-00-29](https://user-images.githubusercontent.com/16726902/54036328-48551e00-41b3-11e9-8a8a-4c8e4565d5f8.gif)

If you check the file system after, the folder was not actually created. If you go on to put a file in the duplicated folder, it works.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Ky6uk** [comment] 2019-03-08 15:20
Can be related https://github.com/Microsoft/vscode/issues/69368

**Comment by isidorn** [comment] 2019-03-11 14:33
@frobinsonj can you please post simple steps? As I am having a hard time figuring out from your gifs what you are doing and what is expected. Sorry

**Comment by frobinsonj** [comment] 2019-03-12 14:25
@isidorn No problem :)

Creating in root instead of selected folder:
1. Select a folder that contains at least one file
2. Click "New Folder" button
3. Click on a file in the selected folder (cancels input but leaves the folder selected)
4. Adding a new file/folder will place it in the root instead of the selected folder.

Duplicating Folder:
1. Select a folder: 
2. Click "New Folder" button
3. Click off to cancel input
4. Click "New File" or "New Folder" button
5. Open in the folder, it will show a folder instead with the same name.

**Comment by isidorn** [comment] 2019-03-14 10:32
@joaomoreno somehow the tree misteriously "looses focus" for me here.
Here's what happens: 
1. I say `tree.setFocus([element])` - tree nicely has element with focus
2. Some time later, I say `tree.getFocus()` I get back an empty array even though in the UX it is clear that the focus is in the tree on one of the elements (seen by the darker blue color)
3. I have also checked and nobody calls `tree.setFocus` between 1. and 2.

How is it possible that this focus trait just disaperas? Even though it is shown in the UX?

**Comment by joaomoreno** [comment] 2019-03-27 16:24
Yup, dupe of #69368

**Closed by joaomoreno** 2019-03-27 16:24 UTC
Labels: file-explorer, tree, under-discussion

**Comment by frobinsonj** [comment] 2019-03-27 16:30
@joaomoreno , what about the duplicating folder issue shown here?

**Comment by joaomoreno** [comment] 2019-03-27 16:35
That doesn't repro any more in `master`. Very likely was fixed by https://github.com/Microsoft/vscode/issues/70902

**Comment by frobinsonj** [comment] 2019-03-27 16:37
Great, thanks :)
