### ISSUE TITLE
 Timeline cannot display git history.

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#146605] opened 2022-04-02 07:11 UTC
Issue Type: <b>Bug</b>

I added the link of "/data - > /private/data" in the configuration file "/etc/synthetic.conf". Now I have a project "/data/path/to/project" in vscode. If I open it with "/data/path/to/project", the timeline cannot display the history of GIT. But it's normal when I open it with "/private/data/path/to/project"

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 420ee4bd-296a-49b6-b5ce-376cc93a21d5|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
php-cs-fixer|jun|0.2.10
php-server-vars-snippets|Mih|0.0.3
vscode-language-pack-zh-hans|MS-|1.65.3
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
php-docblocker|nei|2.7.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by huye** [comment] 2022-04-02 16:40
Not only git, but also formatting, syntax highlighting, etc. are not available.

**Comment by lszomoru** [comment] 2022-04-08 15:13
Duplicate of https://github.com/microsoft/vscode/issues/146611

**Closed** 2022-04-08 15:13 UTC
Labels: git, *duplicate
