### ISSUE TITLE
Selected tree icons hardly visible in light+ theme

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#70380] opened 2019-03-13 09:46 UTC
With the (default) Light+ color theme, icons in selected tree items in the Git view are black on dark blue. They should probably be inverted.

![image](https://user-images.githubusercontent.com/255637/54268974-aea7bb00-457c-11e9-8618-de894aaaa91a.png)

- VSCode Version: 1.32.1
- OS: Linux x64 4.15.0-46-generic

**Comment by usernamehw** [comment] 2019-03-13 10:10
Duplicate of #55857

**Closed** 2019-03-13 16:47 UTC
Labels: themes
