### ISSUE TITLE
AutoImport has change to es5 style after last update

### ISSUE THREAD

**Issue by ItamarShDev** [Microsoft/vscode#60482] opened 2018-10-10 09:17 UTC
- VSCode Version: 1.28.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Use React.js
2. Start typing a module name
3. select the auto import option

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/953371/46726112-492a6800-cc86-11e8-85f1-04761de1170d.png)

Result: 

![image](https://user-images.githubusercontent.com/953371/46726125-52b3d000-cc86-11e8-92ac-a78fe38cf97c.png)

**Comment by ItamarShDev** [comment] 2018-10-10 09:21
related to https://github.com/Microsoft/vscode/issues/60216

**Comment by mjbvz** [comment] 2018-10-10 19:01
Duplicate of Microsoft/TypeScript#27317

**Closed by mjbvz** 2018-10-10 19:01 UTC
Labels: javascript
