### ISSUE TITLE
Allow 100% height for panels with non-center alignment

### ISSUE THREAD

**Issue by avamsi** [microsoft/vscode#191959] opened 2023-09-01 06:20 UTC
I'm not quite sure why only center alignment lets panels occupy 100% of the height -- this means I can't have the integrated terminal occupy 100% of the available space as I either need to sacrifice width (for side panels in center alignment, which is WAI) or height (in non-center alignments, I don't know what for).

This is a subset of #42149, which asked for both height and width (but only got one at a time).

**Comment by sbatten** [comment] 2023-09-01 16:18
duplicate of https://github.com/microsoft/vscode/issues/150365

**Closed by sbatten** 2023-09-01 16:18 UTC

**Comment by avamsi** [comment] 2023-09-02 12:42
For posterity, I'm trying to work around this with an extension by closing both the sidebars (and the activity and status bars) and toggling the terminal in the same command. I have the following so far --

```TS
import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
  let disposable = vscode.commands.registerCommand("tmax.toggle", async () => {
    if (context.workspaceState.get("maximize")) {
      await vscode.commands.executeCommand("workbench.action.closeSidebar");
      await vscode.commands.executeCommand(
        "workbench.action.toggleActivityBarVisibility",
      );
      await vscode.commands.executeCommand(
        "workbench.action.closeAuxiliaryBar",
      );
      await vscode.commands.executeCommand(
        "workbench.action.toggleStatusbarVisibility",
      );
      vscode.window.activeTerminal?.show();
      await vscode.commands.executeCommand(
        "workbench.action.toggleMaximizedPanel",
      );
      context.workspaceState.update("maximize", false);
    } else {
      vscode.window.activeTerminal?.hide();
      await vscode.commands.executeCommand(
        "workbench.action.toggleStatusbarVisibility",
      );
      await vscode.commands.executeCommand(
        "workbench.action.toggleAuxiliaryBar",
      );
      await vscode.commands.executeCommand(
        "workbench.action.toggleActivityBarVisibility",
      );
      await vscode.commands.executeCommand(
        "workbench.action.toggleSidebarVisibility",
      );
      context.workspaceState.update("maximize", true);
    }
  });
  context.subscriptions.push(disposable);
}

export function deactivate() {}
```

AFAICT, there's no way for extensions to tell if the sidebars (and the activity and status bars) are currently visible -- it would be nice if that were possible, as then my custom command could reset them to as they were instead of always toggling.

@sbatten, any thoughts on this?

**Comment by sbatten** [comment] 2023-09-05 15:52
@avamsi if I understand correctly you are trying to hide everything and then maximize the panel. this will not work with the current grid implementation. you would need to re-center the panel as well before you run maximize

**Comment by avamsi** [comment] 2023-09-05 15:54
Yep, the whole reason I was using justify alignment was to let the terminal (panel) use 100% width, now that I'm minimizing the sidebars anyway, I just switched to center alignment 100% of the time.
