### ISSUE TITLE
$0 doesn't work with \U, \u, \L, \l in the global replace

### ISSUE THREAD

**Issue by coldner** [microsoft/vscode#148894] opened 2022-05-06 10:09 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0 57fd6d0195bb9b9d1b49f6da5db789060795de47
- OS Version: Windows 10 Pro 19044.1645

https://user-images.githubusercontent.com/35400886/167111990-2ed49c42-ee93-4a93-b887-21cdd5fdcf62.mp4

**Comment by pkawale** [comment] 2023-09-26 03:24
Hi @andreamah, is this issue still available and open for external PR? Thanks!

**Comment by andreamah** [comment] 2023-09-26 20:47
Yes! There's currently a community PR for this here: https://github.com/microsoft/vscode/pull/149990 but it's a bit stale - if you want to start with those commits and incorporate the feedback, that'd be great!

**Comment by pkawale** [comment] 2023-09-27 12:00
sure. Will do that. Thank you!

**Comment by osortega** [comment] 2024-12-19 22:50
Duplicate of https://github.com/microsoft/vscode/issues/153522 which indicates issues with replacing with capture groups

/duplicate

**Closed by osortega** 2024-12-19 22:50 UTC
Labels: bug, help wanted, search, confirmed
