### ISSUE TITLE
Don't like git push now being under a submenu

### ISSUE THREAD

**Issue by grmhay** [microsoft/vscode#105262] opened 2020-08-24 00:01 UTC
Issue Type: <b>Feature Request</b>

I use git push from the source control menu all the time. Recent release has put it under a submenu pull, push when it used to be in a longer single menu. Appreciate the effort to try to group, but keep frequently used menu items at the root please

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

**Comment by IllusionMH** [comment] 2020-08-24 02:54
/duplicate of #104762

Please add more info to that issue if something is missing there.

**Closed** 2020-08-24 02:54 UTC
Labels: *duplicate
