### ISSUE TITLE
Renaming a filename gets cancelled after about 1 second.

### ISSUE THREAD

**Issue by DavidBetteridge** [microsoft/vscode#139104] opened 2021-12-14 16:28 UTC
Issue Type: <b>Bug</b>

Copy an existing file in the folders pane

Press F2 to rename the file

Start changing the name of the file.

After about a second 1,  the file automatically comes out of edit mode and the focus jumps to a different file.

At first I thought it was due to some particular key press (for example left arrow key) but after a bit more experimenting I don't think that is the case.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
copilot|Git|1.7.4273
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.24.6
vscode-python-test-adapter|lit|0.7.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
test-adapter-converter|ms-|0.1.5
vsliveshare|ms-|1.0.5196
vscode-python-typehint|njq|1.4.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2

</details>

**Comment by gjsjohnmurray** [comment] 2021-12-14 16:47
Probably #112293

**Comment by DavidBetteridge** [comment] 2021-12-14 17:34
#112293 looks similar,  but I'm not seeing the issue when creating (naming) new files,  only renaming them.

**Comment by JacksonKearl** [comment] 2021-12-14 19:23
Fix for #112293 was to pause explorer updates while an edit is underway, if the underlying cause is the same (explorer refresh from file changes) that should fix this too. It'd help if you can test in tomorrow insiders.

**Comment by enricodias** [comment] 2021-12-16 19:07
Same issue here on both versions 1.63.1 and 1.63.2. Happens when creating a new file as well.

**Comment by JacksonKearl** [comment] 2021-12-16 19:09
@enricodias The latest insiders contains a fix for this, it'd help if you could test there and see if things are now working as expected.

**Comment by enricodias** [comment] 2021-12-16 20:04
@JacksonKearl It did, thanks.

I also managed to track what was causing the explorer to update here. It was a bash script running `git status` in the background.

**Comment by JacksonKearl** [comment] 2021-12-16 20:46
Cool thanks, I'll also close this as a duplicate of #112293 as the fix should be the same.

**Closed by JacksonKearl** 2021-12-16 20:46 UTC
