### ISSUE TITLE
Make TextMate scopes available for extensions.

### ISSUE THREAD

**Issue by svitalij** [Microsoft/vscode#11649] opened 2016-09-07 18:51 UTC
As far as I can see, currently VS Code flatten TextMate scopes and this is impossible to get all scopes from specified location. It would be cool to have TextDocument method like 'getScope(at: Position):string[]' which returns the syntax scope names assigned to the given position.

```
<html><head><style>
    .test { color: rgb(255, 255, 0); }
</style></head></html>
```
for Position(1,12) – into the ‘color’ token this method may return:
`['text.html.basic', 'source.css.embedded.html', 'meta.property-list.css', 'meta.property-name.css', 'support.type.property-name.css`']

**Comment by jrieken** [comment] 2016-09-08 07:11
closing as duplicate of #580

**Closed by jrieken** 2016-09-08 07:11 UTC
Labels: api
