### ISSUE TITLE
Reopening #214390 Font weight is permanently bold after latest update

### ISSUE THREAD

**Issue by lumotroph** [microsoft/vscode#225120] opened 2024-08-08 08:53 UTC
Does this issue occur when all extensions are disabled?: **Yes**

Reopening [this ticket](https://github.com/microsoft/vscode/issues/214390) as it's affecting me too. Same issue.

- VS Code Version:
```Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
```
- OS Version: 
 ```OS: Darwin arm64 23.0.0```

Steps to Reproduce:

1. Have system described above
2. `settings.json` includes the following line:
`  "editor.fontFamily": "Operator Mono, Menlo, Monaco, 'Courier New', monospace",`
3. As per original ticket, it's **Operator Mono** (the best font) that seems to be a common part of the problem.

**Comment by matkovsky** [comment] 2024-08-08 08:57
Yep, the issue is here again… :(

**Comment by gjsjohnmurray** [comment] 2024-08-08 09:09
/duplicate of https://github.com/microsoft/vscode/issues/224496 which is pinned to the top of this repo's Issues page and will be fixed in upcoming recovery release.

**Closed** 2024-08-08 09:09 UTC
Labels: *duplicate
