### ISSUE TITLE
go to type definition on click to type in popup

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#117125] opened 2021-02-20 11:05 UTC
![изображение](https://user-images.githubusercontent.com/28058268/108593403-8c339480-7384-11eb-9fbe-ee9f96e9ee2c.png)

In webStorm I can click on type in popup. But in vscode I can't do it. Please, add this feature.

**Comment by yume-chan** [comment] 2021-02-21 15:26
Duplicate of #109264 and #64566

**Closed** 2021-02-22 22:29 UTC
Labels: *duplicate, editor-hover, javascript
