### ISSUE TITLE
Alt+PrtScn under Windows does not capture only the VS Code window

### ISSUE THREAD

**Issue by marc2377** [Microsoft/vscode#46009] opened 2018-03-17 01:06 UTC
The keyboard combination <kbd>Alt</kbd>+<kbd>PrtScn</kbd> should take a screenshot of the currently active window. However, for a VS Code window, it does not work. Instead, the whole screen is captured.

Perhaps VS Code is "hijacking" the <kbd>Alt</kbd> key's default behavior?

- VSCode Version: 1.21.1
- OS Version: Windows 10 x64 build 16299.309

Issue is present with extensions disabled.

**Comment by tsalinger** [comment] 2018-03-17 07:43
I can't reproduce your issue on win10 with VS Code 1.21.1.

You mention that this only occurs with extensions disabled but maybe you didn't disable all extensions?
You can disable all extensions with CTRL+SHIFT+P --> 'Disable all installed extensions'. It's important to restart VS Code after this.
Then check if the problem still persists.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that trigger this behavior. For example: what component inside VS Code (editor, explorer, etc.) has the focus when you create the screenshot?

Do you have any other applications installed that might modify the ALT key behavior?

**Comment by marc2377** [comment] 2018-03-19 20:04
I did disable all extensions. At first, I was using the "Reload Window with Extensions Disabled". But now I've just tested with "Disable All Installed Extensions" as you said, and restarted VS Code manually. Issue persists.

Steps are simple:

1. Launch VS Code
2. Press the <kbd>Alt</kbd>+<kbd>PrtScn</kbd> combination.

It does not matter which component has focus (but the window has focus, I'm sure of it), nor whether a file is opened or not.

I must mention this is a Windows 10 installation within a QEMU/KVM virtual machine, managed with virt-manager, and using display SPICE with a qxl video device. SPICE guest agent is installed as well as necessary VIRTIO drivers.

But the problem is specific to VS Code, every other program I've tried works ok with <kbd>Alt</kbd>+<kbd>PrtScn</kbd> and I've been using this setup for over a year.

**Comment by bpasero** [comment] 2018-03-20 09:06
I am closing this as this does not seem to be under VSCode's control at all, rather it is a OS feature. As far as I know, VS Code is not using the PrintScreen key.

**Closed by bpasero** 2018-03-20 09:06 UTC
Labels: needs more info, new release

**Comment by marc2377** [comment] 2018-03-20 21:38
Well, but it uses the Alt key.

Now, I just booted Windows 10 natively, bypassing the virtual machine, and Alt+PrtScn works as expected there. Weird thing it is the _only_ program I ever tested for which it doesn't work through virt-manager - I just did some testing with a myriad of other applications.

Anyway, if it works natively I don't see a reason to reopen the issue. And sorry for not exhausting my options beforehand as I should have.
