### ISSUE TITLE
Color theme abruptly changes when editing an unrelated setting

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#139536] opened 2021-12-20 20:17 UTC
Version: 1.64.0-insider (Universal)
Commit: 807bf598bea406dcb272a9fced54697986e87768
Date: 2021-12-20T05:14:16.036Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:

1. Make sure you don't have the default theme (my theme is GitHub Light)
2. Edit `settings.json` (I started typing `remote`)
3. See weird color theme switch which stays until I delete the half written setting.

![recording (60)](https://user-images.githubusercontent.com/12758612/146827165-0ef04c59-a38d-40cc-b3f4-cb1c886c3c52.gif)

This happened both in the extension host and the main VS Code instance.

My theme comes back once I successfully complete the half-written setting or I delete it.

![recording (61)](https://user-images.githubusercontent.com/12758612/146827438-5d928c33-3f79-447b-9498-1fcbcc726a52.gif)

**Comment by roblourens** [comment] 2021-12-21 21:12
The settings file becomes broken and no settings are applied. But I think there is something that is supposed to prevent the settings from being reloaded in this scenario.

**Comment by sandy081** [comment] 2022-01-03 14:07
JSON parser tries its best to provide a valid JSON in case the file is syntactically not correct. It seems, complete content below that half entered setting is not parsed and the theme setting seems to be below and hence the theme switches. Once setting got fixed everything becomes normal.

I would say this is like this from beginning and the behaviour is understood and expected. Hence closing this as designed

**Closed** 2022-01-03 14:08 UTC
Labels: *as-designed
