### ISSUE TITLE
[Bug] Not encoded non-normative characters when in url or href, not seperate non-normative characters from English ones

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#70449] opened 2019-03-14 06:05 UTC
![Wrong](https://user-images.githubusercontent.com/40081831/54334607-7b8b2780-4661-11e9-8bb6-8b66d87d1c66.png)

---
Steps to Reproduce:

1. Create an 'md' file.
2. Write your href like this （mixed with Chinese characters）：

![image](https://user-images.githubusercontent.com/40081831/54334828-24398700-4662-11e9-9411-7407774dc51a.png)

The "汉字" (or other non-lartain characters) shouldn't be included as the part of Url or href, or mailto：

Ref：https://github.com/nodejs/nodejs.org/issues/1612

**Comment by Maledong** [comment] 2019-03-14 06:07
@vscodebot：Not a duplicate question.

**Comment by mjbvz** [comment] 2019-03-14 06:53
Please share the text of the code along with screenshots

**Comment by Maledong** [comment] 2019-03-14 07:03
@mjbvz：Thanks for your very quick reply, here's the text for your demo to reproduce this issue ——

1. Screenshots is in my 1st post (Non-Lartain Characters shouldn't be the part of the url or href, or mailto, so "汉字" and "我们" should be white instead of blue).

2. Here's the test file for you to download :)
[README.zip](https://github.com/Microsoft/vscode/files/2965057/README.zip)

**Comment by mjbvz** [comment] 2019-03-14 19:53
Thanks. Linked text for quick future reference:

```md
http://www.baidu.com。

http://www.baidu.com汉字。

mailto:m@abc.com。

mailto:m@abc.com我们。
```

**Comment by Maledong** [comment] 2019-03-15 02:44
@mjbvz：Suddenly got an idea of how to encode these non-normative characters？

According to [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt),  It says——
```
Octets MUST be encoded if they have no corresponding graphic
character within the US-ASCII coded character set, if the use of the
corresponding character is unsafe, or if the corresponding character
is reserved for some other interpretation within the particular URL
scheme.

No corresponding graphic US-ASCII:

URLs are written only with the graphic printable characters of the
US-ASCII coded character set. The octets 80-FF hexadecimal are not
used in US-ASCII, and the octets 00-1F and 7F hexadecimal represent
control characters; these must be encoded.
```
It seems that you can keep the Chinese characters but just do something like 'encodeURI' or 'encodeURIComponent'……What do you think of this？If you are OK with this idea, I'll change my topic.

^_^

**Comment by mjbvz** [comment] 2021-05-06 01:14
Closing since there hasn't been any further interest in this issue for two years. We'd still take a PR if someone want to try to fix this and the solution is reasonable enough

**Closed by mjbvz** 2021-05-06 01:14 UTC
Labels: editor-contrib, help wanted, markdown
