### ISSUE TITLE
Console scrollbar missing 

### ISSUE THREAD

**Issue by JCorrivo** [Microsoft/vscode#9806] opened 2016-07-26 17:54 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open console
2. execute something like npm install
3. there is no scroll bar

**Comment by kieferrm** [comment] 2016-07-26 18:08
Duplicate of #6602.

**Closed by kieferrm** 2016-07-26 18:08 UTC
Labels: duplicate, integrated-terminal
