### ISSUE TITLE
Ctrl + Z

### ISSUE THREAD

**Issue by SaneHe** [Microsoft/vscode#46527] opened 2018-03-26 08:11 UTC
Issue Type: <b>Bug</b>

我使用 ctrl + z的时候经常会返回到最顶部，why

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.86GB (8.02GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe V:\refactor_lara|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.2.0
githistory|don|0.4.0
EditorConfig|Edi|0.12.1
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.2
php-intellisense|fel|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
gc-excelviewer|Gra|2.0.20
beautify|Hoo|1.3.0
crane|Hvy|0.3.8
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.8.1
docthis|joe|0.6.0
typings-autoinstaller|jvi|1.2.0
vscode-colorize|kam|0.6.16
laravel-blade|KTa|0.0.1
vue|liu|0.1.5
php-namespace-resolver|Meh|1.0.3
code-beautifier|mic|1.7.2
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
vscode-apache|mrm|1.1.1
mssql|ms-|1.3.0
python|ms-|2018.2.1
debugger-for-chrome|msj|4.2.2
php-docblocker|nei|1.6.0
vetur|oct|0.11.7
laravel-blade|one|1.17.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.4.0
vuehelper|oys|0.1.0
emoji|Per|0.0.3
seti-icons|qin|0.1.3
laravel-helpers|raf|0.2.2
java|red|0.21.0
vscode-icons|rob|7.22.0
laravel-artisan|rya|0.0.16
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.3.4
topper|sid|0.3.2
php-formatter|Sop|0.2.4
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
JavaScriptSnippets|xab|1.5.0
markdown-pdf|yza|0.1.8

(5 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by dbaeumer** [comment] 2018-03-26 11:40
@SaneHe can you please provide the description in English.

@octref @rebornix

**Comment by octref** [comment] 2018-03-26 16:01
He's saying Ctrl + Z always goes back to top (of the file, I guess).

**Comment by shnewto** [comment] 2018-03-28 22:03
I'm also having as issue where Ctrl+z takes me to the top of the file. The behavior I'm seeing is that Ctrl+z once takes me to the top of the file, Ctrl+z again moves the cursor back to the last change and undoes it. Ctrl+z a third time takes me to the top of the file. Basically Ctrl+z is alternating between hopping the cursor to the top of the file and actually undoing the last change. 

`undo` is the only keyboard shortcut associated with `Ctrl+z` in my preferences. 

I'm unable to reproduce it easily though. It only seems to start happening in a file I've been working on for awhile (one that has a lot of recent history).

**Comment by shnewto** [comment] 2018-03-28 22:05
I'm also on Version 1.21.1, Commit 79b44aa

**Comment by dbaeumer** [comment] 2018-03-29 06:02
I can't reproduce this on 1.21.1.

@shnewto do you have any extension install. Can you try to reproduce when you start with all extensions disabled.

**Comment by alexandrudima** [comment] 2018-03-29 07:25
The root cause is the same as #45538

The symptom (undo going back to [1,1]) is fixed via #46208.

**Closed by alexandrudima** 2018-03-29 07:25 UTC
Labels: editor, needs more info
