### ISSUE TITLE
Workbench flashing on start

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#20710] opened 2017-02-16 09:34 UTC
1. Latest insiders, light theme, reload
2. Notice how parts of the workbench are getting colored from black to light. Feels broken

![flash](https://cloud.githubusercontent.com/assets/1926584/23015505/5f84df5e-f433-11e6-97fe-1a832632ae2f.gif)

**Comment by aeschli** [comment] 2017-02-16 13:55
duplicate of #20705

**Closed by aeschli** 2017-02-16 13:55 UTC
