### ISSUE TITLE
Extension info tab does not return to correct position when switching between tabs

### ISSUE THREAD

**Issue by macintacos** [Microsoft/vscode#33817] opened 2017-09-04 22:30 UTC
- VSCode Version: 1.15.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Open a sample file in a tab (e.g. test.txt)
2. Open the details of an extension in its own separate tab.
3. Scroll down the page of details (use case: editing user settings for that extension, finding out more information, etc.)
4. Switch back to the file (test.txt)
5. Switch back to the extension details.

**Result:** Extension page reloads and brings the user to the top of the page. This is especially frustrating when you are trying to tweak the settings of an extension by referring to the documentation available on their page and it is not at the top of the document, and are switching back and forth between the tabs.

I can provide a video if needed, but hopefully the steps above are enough to verify the behavior and potentially fix it.

Reproduces without extensions: Yes

**Comment by yume-chan** [comment] 2017-09-05 07:18
Duplicate of #27498

**Closed** 2017-09-05 09:54 UTC
Labels: extensions, new release
