### ISSUE TITLE
VS Code shows absolute paths in callstack when debugging with launch config in workspace file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96628] opened 2020-04-29 17:58 UTC
- Copy the normal "Launch VS Code" config into a workspace config file
- Debug
- Press pause
- See absolute paths in the callstack, when you should see workspace-relative paths

![image](https://user-images.githubusercontent.com/323878/80629685-d1af5b80-8a18-11ea-8953-e8420035755b.png)

For comparison
- Launch the "VS Code" config
- Press pause
- This works as expected, I see relative paths

![image](https://user-images.githubusercontent.com/323878/80629849-015e6380-8a19-11ea-9b8d-fdeeb2a9fad7.png)

So i assume that the workspace-level config is the key here.

**Comment by isidorn** [comment] 2020-04-30 09:39
Good catch. And yes the location of the launc configuration should not affect the display.
Opening up for PRs and assigning to May so if nobody jumps on this I can also look into this.

How I think this should be fixed:
`getSpecificSourceName` should be extracted to a helper function
https://github.com/microsoft/vscode/blob/791156d90f5a50e05236aec070166094186c01b1/src/vs/workbench/contrib/debug/common/debugModel.ts#L330
It should be covered by unit tests
And this issue sohuld be fixed in that method.

**Comment by isidorn** [comment] 2020-05-06 10:04
Ok, I have looked into this, and the problem is not with the `getSpecificSourceName`, but that simply in this case the [`name`](https://github.com/microsoft/vscode/blob/24fb57122a5673ba89a778735b6995379f00db2e/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L1670) of the source is the full path as set by the debug extension.

Thus assigning this to @connor4312 so he check on the extension side how he sets the `Source` name. My suspicion is that in the VS Code [`workspaceFolders`](https://github.com/microsoft/vscode/blob/24fb57122a5673ba89a778735b6995379f00db2e/src/vs/vscode.d.ts#L8920) api is not used properly .

Also fyi @weinand since potentially path conversions could also casue this, but I do not think that is the case.

**Comment by connor4312** [comment] 2020-11-02 23:24
This was fixed with better selection of the workspace folder. Before it was an empty string in this case, now it always resolves (or makes a best guess) at the correct folder to use, and shows relative paths for its children.

**Closed by connor4312** 2020-11-02 23:24 UTC
Labels: bug, debug
