### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by ChipNich** [microsoft/vscode#110516] opened 2020-11-12 19:33 UTC
Issue Type: <b>Bug</b>

When opening a cmd terminal in VS Code windows 10, the terminal window opens and there is just a blank character and no usable

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (2.33GB free)|
|Process Argv|C:\Users\User\Documents\GitHub\DiscordBot --crash-reporter-id 95abe816-f093-4f18-808b-762d42fc3250|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13

</details>

**Comment by usernamehw** [comment] 2020-11-12 19:39
Possible duplicate https://github.com/microsoft/vscode/issues/105431#issuecomment-680949825

**Comment by meganrogge** [comment] 2020-11-12 20:12
Duplicate of #105431

**Closed by meganrogge** 2020-11-12 20:12 UTC
Labels: new release
