### ISSUE TITLE
Code Helper doing something heavy when VSCode isn't executed

### ISSUE THREAD

**Issue by fzzr-** [Microsoft/vscode#37942] opened 2017-11-09 13:13 UTC
Code Helper doing something when VSCode isn't executed.
And when Code Helper is alive in background it eating from 30% to 200% (yes!) of CPU.

- VSCode Version: latest 1.17.2
- OS Version: 10.12.6 (16G29)

Steps to Reproduce:

1. Don't run vscode, wait...
2. open Activity Monitor

Reproduces without extensions: Yes

![screen shot 2017-11-07 at 15 38 48](https://user-images.githubusercontent.com/888526/32607094-c42643e2-c568-11e7-989b-ca79f271509c.png)

- - -

Additional question is _How to disable this crazy and spy-like behaviour?_

**Comment by bpasero** [comment] 2017-11-10 05:52
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by fzzr-** [comment] 2017-11-10 14:35
`ps aux | grep 43357`:
```log
ak               43357   0.0  2.9  3727164 123656   ??  S     5:01PM   1:46.56 /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_7993247
ak               45220   0.0  0.0  2423384    320 s006  R+    5:32PM   0:00.00 grep 43357
```

`ps aux | grep code`:
```log
ak               44101   0.0  0.5  3120492  19960   ??  S     5:10PM   0:00.58 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/ak/.vscode/extensions/mkaufman.htmlhint-0.4.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/ak/.vscode/extensions/mkaufman.htmlhint-0.4.0/server/server.js --stdio
ak               44099   0.0  0.5  3155224  20512   ??  S     5:10PM   0:01.74 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html/server/out/htmlServerMain.js --node-ipc --clientProcessId=43974
ak               44095   0.0  0.0  2523460   1080   ??  S     5:10PM   1:47.32 /Users/ak/.vscode/extensions/ms-vscode.cpptools-0.14.2/bin/Microsoft.VSCode.CPP.Extension.darwin
ak               43986   0.0  0.5  3202748  20316   ??  S     5:08PM   0:02.56 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/ak/.vscode/extensions/shinnn.stylelint-0.30.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/ak/.vscode/extensions/shinnn.stylelint-0.30.0/server.js --stdio --clientProcessId=43974
ak               43985   0.0  0.5  3128108  20356   ??  S     5:08PM   0:01.20 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css/server/out/cssServerMain.js --node-ipc --clientProcessId=43974
Alexander Kozlovskij               45273   0.0  0.0  2423384      8 s006  R+    5:33PM   0:00.00 grep code
```

![screen shot 2017-11-10 at 17 29 10](https://user-images.githubusercontent.com/888526/32662963-58b05618-c63d-11e7-8a1e-bb12e512cedf.png)
[Sample of Code Helper.txt](https://github.com/Microsoft/vscode/files/1461645/Sample.of.Code.Helper.txt)
[Opened Files and Ports.txt](https://github.com/Microsoft/vscode/files/1461646/Opened.Files.and.Ports.txt)

**Comment by fzzr-** [comment] 2017-11-10 14:59
I think I understand it...
Very "thanks" to exts:
- mkaufman.htmlhint-0.4.0 ;
- shinnn.stylelint-0.30.0 ;
- and to viscose because don't breaking that first two ext's servers.

**Comment by bpasero** [comment] 2017-11-12 17:30
The process with ID `43974` seems language client/server related.

**Comment by aeschli** [comment] 2017-11-13 15:12
`43974` seems to be the pid of the extension host. When the CSS or HTML language servers are started up, they get the extension host pid as parameter. 
`/Applications/Visual Studio Code.app/.../htmlServerMain.js --node-ipc --clientProcessId=43974`

So it looks like some normal extension is busy here. 

@fzzr Can you try with all extensions disabled?
Do you have this reproducible, e.g. when working on a specific file?

**Comment by Fzzr** [comment] 2017-11-13 18:15
@aeschli You almost certainly want @fzzr- Thanks to both of you for what you're doing!

**Comment by aeschli** [comment] 2017-12-05 07:20
@fzzr- if you have any additional information, that would be great
Closing until we have more information.

**Closed by aeschli** 2017-12-05 07:20 UTC
Labels: css-less-sass, freeze-slow-crash, html, needs more info
