### ISSUE TITLE
.prettierrc JSON schema not picked up automatically from https://www.schemastore.org/

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#158937] opened 2022-08-23 16:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.2
- OS Version: Windows 10.0.19044.0 x64

Steps to Reproduce:

1. Create a `.prettierrc` (In JSON format) or `.prettierrc.json`.
2. VS Code won't automatically pick the schema https://json.schemastore.org/prettierrc.json despite it being registered in the schema store appropriately with those file names. You will have to use `$schema` which I believe isn't supposed to be required for stuff that is registered in the schema store.................

**Comment by aeschli** [comment] 2022-08-26 15:03
JSON doesn't have the feature to automatically pick up the schema, instead the associations come from extensions and user settings. See https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings

The issue is a duplicate of https://github.com/microsoft/vscode/issues/26289

**Closed by aeschli** 2022-08-26 15:03 UTC
