### ISSUE TITLE
Cursor remains in the beginning after pressing comments shortcut

### ISSUE THREAD

**Issue by shreyas-a** [Microsoft/vscode#35928] opened 2017-10-09 20:04 UTC
- VSCode Version: 1.17.0
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Press `⌘ + /`
2. Notice that cursor is stuck at the beginning of the line, it should be at the end of the line.

**Comment by ajmichaels** [comment] 2017-10-10 08:37
I also have been experiencing this issue since the new release.

**Comment by ryan-lynch** [comment] 2017-10-10 10:16
A minor but quite irritating bug!

**Comment by trevren11** [comment] 2017-10-10 20:01
Also on Windows

**Comment by alexandrudima** [comment] 2017-10-12 13:06
Duplicate of #35673

**Closed by alexandrudima** 2017-10-12 13:06 UTC
Labels: editor, editor-contrib
