### ISSUE TITLE
Cannot run multiple debug sessons with the same launch config name

### ISSUE THREAD

**Issue by blumanfry** [microsoft/vscode#100589] opened 2020-06-19 16:35 UTC
When trying to run multiple debug sessions that are configured with the same launch name, the 2nd session will not start. In the example below, you cannot run both debuggers at the same time if the names are the same:

API/.vscode/launch.json:
`{
    configurations: [
        {
            "name": "Serve"
            ...
        }
    ]
}`

UI/.vscode/launch.json:
`{
    configurations: [
        {
            "name": "Serve"
            ...
        }
    ]
}`

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by sirlancelot** [comment] 2020-06-19 17:06
Related: #100583 

Same behavior on Mac.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by isidorn** [comment] 2020-06-22 14:48
This is currently not supporeted, however this is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by sirlancelot** [comment] 2020-06-22 17:53
As a workaround, It appears to be possible to use `compounds` in a workspace to launch multiple sessions under the same name:

![image](https://user-images.githubusercontent.com/71916/85319444-5b5a3300-b476-11ea-823e-ceb685550f80.png)

@isidorn, my team definitely recalls being able to launch multiple sessions with the same name. This feels like a regression.

**Comment by sirlancelot** [comment] 2020-06-22 18:00
Seeing as all the options are available with the project name being shown next to the task name, I'd consider this a bug at minimum. And since it was supported in previous versions, that would bump it up to a regression.
![image](https://user-images.githubusercontent.com/71916/85320152-7b3e2680-b477-11ea-95ff-87ddb5c461c2.png)

**Closed** 2020-10-30 14:15 UTC
Labels: *out-of-scope, debug, feature-request
