### ISSUE TITLE
Ability to disable GoToDefinition on Ctrl+LeftMouseClick

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/vscode#6853] opened 2016-05-25 03:39 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10 Pro

In Visual Studio (full version), I tend to turn off the Ctrl+LeftMouseClick go to definition feature. I personally prefer to have Ctrl+LeftMouseClick select the entire word under my mouse cursor.

From what I can see, mouse events are not configurable at the moment, and they are also not possible to override with extensions (to the best of my knowledge). It would be really nice to have a mouse mapping configuration file. Sublime Text has this (although it is sort of a hidden feature that is not exposed through the UI). Just as an example, my sublime text mousemap file looks like this:

```json
[
    {
        "button": "button1", "count": 1, "modifiers": ["ctrl"],
        "press_command": "drag_select",
        "press_args": {"by": "words"}
    }
]
```

**Comment by Tyriar** [comment] 2016-05-25 03:43
Duplicate of #3130, copied your comment over

**Closed by Tyriar** 2016-05-25 03:43 UTC

**Comment by ChristopherHaws** [comment] 2016-11-15 08:31
For anyone looking how to achieve what I wanted to do in my original post, you are able to do it with the following keyboard binding in VS Code:

```json
[
    { "key": "ctrl+[mouse button]",		"command": "cursorWordLeft",
                                           "when": "editorTextFocus" },
]
```
