### ISSUE TITLE
Extension's Markdown is garbled

### ISSUE THREAD

**Issue by KaierChou** [Microsoft/vscode#64407] opened 2018-12-05 04:38 UTC
**When I use MD locally and browse it, is OK.**
![image](https://myimage.kaier33.top/vsmd_ok2.png)
**but, when i browse extension , it garbled.**
![image](https://myimage.kaier33.top/vsmd_bad2.png)

It looks normal in here , but, when i browse extension's informattion , it garbled

Name | Description | Default 
| ------ | ------ | ------ |
CaringOtaku.defaultCity | CityName | 深圳
CaringOtaku.freeweatherAK | key | my key
CaringOtaku.lunchTime | 吃饭时间 | 11:50
CaringOtaku.getOffTime | 下班时间 | 18:00

** MD code**
```
Name | Description | Default 
| ------ | ------ | ------ |
CaringOtaku.defaultCity | CityName | 深圳
CaringOtaku.freeweatherAK | key | my key
CaringOtaku.lunchTime | 吃饭时间 | 11:50
CaringOtaku.getOffTime | 下班时间 | 18:00
```

i hopo to solve it , thanks. 🍭

**Comment by mjbvz** [comment] 2018-12-05 05:30
Duplicate of #26841

**Closed by mjbvz** 2018-12-05 05:30 UTC
Labels: markdown
