### ISSUE TITLE
Links not working from markdown preview

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#40397] opened 2017-12-18 00:44 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T06:08:07.643Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.0
cpptools|ms-|0.14.4
debugger-for-chrome|msj|4.0.0
autoimport|ste|1.5.3
vim|vsc|0.10.6
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a markdown file with internal links.
2. Switch to preview mode.
3. Click on a link to jump to a section.

This results in opening the ".md" file, switching out of preview mode and jumping to the section in the editor view.

![screen shot 2017-12-17 at 7 42 28 pm](https://user-images.githubusercontent.com/439226/34085716-892eff6e-e362-11e7-9114-a97fbbe5ba68.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-12-18 18:51
Please share the markdown source of the page

**Comment by rajinder-yadav** [comment] 2017-12-24 06:25
you create a markdown file and add an internal like, nothing special.

**Comment by rajinder-yadav** [comment] 2017-12-24 06:27
Use this: https://github.com/rajinder-yadav/dm-css/blob/master/README.md

**Comment by mjbvz** [comment] 2018-01-02 23:06
Duplicate of #40877

Should be fixed in the next insiders build

**Closed by mjbvz** 2018-01-02 23:06 UTC
Labels: insiders, markdown, needs more info
