### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by markasalinas** [microsoft/vscode#103969] opened 2020-08-04 17:45 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.8.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:112241:13)
    at Object.releaseDocument (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:112236:20)
    at c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:135319:45
    at Object.forEach (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:167:30)
    at Proxy.dispose (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:135318:20)
    at InferredProject.Project.close (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:139542:38)
    at InferredProject.close (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:140420:40)
    at ProjectService.removeProject (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:144260:46)
    at c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\Dev\THOR_Portal_UI\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.48.0-insider (459610f3ef11b956968afadff704bad3bc1a0de2, 2020-08-04T12:40:10.231Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.49GB free)|
|Process Argv|--file-uri file:///c%3A/Dev/THOR_Portal_UI/thor-portal-ui.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
Bookmarks|ale|11.3.1
ng-template|Ang|0.1000.7
turbo-console-log|Cha|1.4.0
jsrefactor|cms|2.20.6
angular-schematics|cyr|4.3.0
ng-prev-component|dan|1.0.1
git-diff-and-merge-tool|dav|1.0.4
vscode-eslint|dba|2.1.8
vscode-terminal-capture|dev|0.0.1
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.2
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
typescript-interface-to-builder-class|fra|0.1.9
todo-tree|Gru|0.0.178
NgRxSnippets|har|9.1.0
vscode-jasmine-test-adapter|hbe|1.7.0
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
vscode-git-tags|how|1.4.4
vscode-npm-dependency|how|1.2.2
rest-client|hum|0.24.1
angular2-switcher|inf|0.3.3
vscode-git-add-and-commit|iva|2.1.1
search-node-modules|jas|1.3.0
mark-as-excluded|jcm|0.2.6
docthis|joe|0.7.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
types-autoinstaller|jvi|2.4.0
favorites|kdc|2.4.5
quicktask|lky|3.5.6
CamelCase|Mar|1.0.4
git-graph|mhu|1.25.0
gitignore|mic|1.0.1
vscode-checkpoints|mic|1.3.1
Angular-BeastCode|Mik|8.1.2
vscode-goto-node-modules|mrl|1.2.1
vscode-azureappservice|ms-|0.18.0
python|ms-|2020.7.96456
azure-account|ms-|0.9.1
powershell-preview|ms-|2020.7.0
typescript-javascript-grammar|ms-|0.0.53
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
abracadabra|nic|4.6.0
angular-console|nrw|13.0.0
peep|nwa|0.0.5
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
quicktype|qui|12.0.46
fabric8-analytics|red|0.1.0
color-manager|roy|0.5.7
partial-diff|ryu|1.4.1
git-merger|sha|0.4.1
simontest|Sim|1.8.9
move-ts|str|1.12.0
terminal-zoom|try|1.7.1
create-index|tsu|0.1.5
sort-lines|Tyr|1.9.0
vscode-angular-support|vis|0.1.4
vscodeintellicode|Vis|1.2.9
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.5

(4 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-08-04 18:39
Duplicate of https://github.com/microsoft/TypeScript/issues/37500

Should be fixed in current versions of TypeScript, 3.9+

**Closed by mjbvz** 2020-08-04 18:39 UTC
