### ISSUE TITLE
Extension host terminated unexpectedly less than 5 minutes only on react native project

### ISSUE THREAD

**Issue by Deri-Kurniawan** [microsoft/vscode#176841] opened 2023-03-11 09:10 UTC
Type: <b>Bug</b>

Extension always terminated less than 5 minutes, only on react native project

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.15.0-67-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|3.58GB (1.73GB free)|
|Process Argv|. --crash-reporter-id d973878e-df3d-4d5c-9d0d-5f65d3b208f8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cpp-snippets|aga|1.0.1
vscode-javascript-snippet-pack|aka|0.1.6
laravel-extra-intellisense|ami|0.6.2
tsl-problem-matcher|amo|0.6.2
preview-mp4|ana|0.0.1
jsx-html-tags|ang|1.0.1
astro-vscode|ast|0.28.2
laravel-blade-spacer|aus|2.1.3
color-info|bie|0.7.2
vscode-styled-jsx|bla|2.1.1
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
vscode-expo|byC|0.9.2
npm-intellisense|chr|1.4.4
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.8
vscode-eslint|dba|2.4.0
composer-php-vscode|DEV|1.31.12740
phptools-vscode|DEV|1.31.12740
javascript-ejs-support|Dig|1.3.3
dotenv-vscode|dot|0.22.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.77.9225
remotehub|Git|0.52.0
vscode-pull-request-github|Git|0.60.0
headwind|hey|1.7.0
rest-client|hum|0.25.1
html-tag-wrapper|hwe|0.2.3
javascript-snippets|jab|4.0.1
vscode-placeholder-images|Jak|0.1.0
vsc-python-indent|Kev|1.18.0
remove-unused-imports|kus|1.2.3
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
csharp|ms-|1.25.4
isort|ms-|2022.8.0
python|ms-|2023.4.1
remote-containers|ms-|0.282.0
azure-repos|ms-|0.28.0
js-debug-nightly|ms-|2023.3.817
live-server|ms-|0.4.6
remote-repositories|ms-|0.30.0
vscode-typescript-next|ms-|5.1.20230310
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.10.2
nativescript|Nat|0.12.3
sftp|Nat|1.16.1
reload|nat|0.0.6
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
prisma|Pri|4.11.0
prisma-insider|Pri|31.0.1989
html-to-jsx|ria|0.0.1
format-html-in-php|rif|1.7.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.20.12
css-auto-prefix|spo|0.1.7
autoimport|ste|1.5.4
wav-preview|suk|2.0.5
svelte-vscode|sve|107.2.3
pdf|tom|1.2.2
vscode-mdx|uni|1.2.5
errorlens|use|3.7.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.6
vscode-icons|vsc|12.2.0
vscode-wakatime|Wak|24.0.7
vscode-nginx|wil|0.7.2
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30677849
pythonb192cf:30669361
funwalk2cf:30682975
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:22
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:22 UTC
Labels: freeze-slow-crash-leak, extension-host
