### ISSUE TITLE
Markdown preview text is missing after tabs are switched

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode#165188] opened 2022-11-01 19:25 UTC
I have a video! Recent vscode main@c60980ca7ae:

![vscode-senyai-md-issue](https://user-images.githubusercontent.com/76137/199317655-e5cd8e2f-d6fa-4e33-a6d2-9146d91ac47d.gif)

Text in the markdown preview from the modified file is missing after the tabs are switched. I'm writing my own preview extension and this behavior is not ideal. To fix it, I think the webview should "postMessage" when it's loaded and then the server should "postMessage" back with relevant content.

**Comment by DavidNaumann** [comment] 2022-11-02 15:02
Looking into the code for this functionality makes sense as the preview hooks into the text change of the markdown file and updates accordingly. However when the preview is no longer active it disposes the preview from memory and when active again constructs itself back up from the resource URI which has not updated yet.

**Comment by mjbvz** [comment] 2022-12-05 19:59
Duplicate of #147718

**Closed by mjbvz** 2022-12-05 19:59 UTC
Labels: bug, help wanted, markdown
