### ISSUE TITLE
Deleting 30+ folders is very slow and vscode hangs.

### ISSUE THREAD

**Issue by krasi-georgiev** [Microsoft/vscode#62945] opened 2018-11-12 12:12 UTC
Issue Type: <b>Bug</b>

It is easy to reproduce: 
 - create 30+ folders with few files in each and 
 - select all 
 - delete

this will hang for few minutes

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 4.15.14-300.fc27.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2107)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|30.80GB (3.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
gitlens|eam|8.5.6
python|ms-|2018.10.1
cpptools|ms-|0.20.1
Go|ms-|0.7.0
vsliveshare|ms-|0.3.925
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0

</details>

**Comment by isidorn** [comment] 2018-11-13 10:05
Can you reproduce this with latest vscode insiders 
https://code.visualstudio.com/insiders/

**Comment by krasi-georgiev** [comment] 2018-11-13 12:15
yes the same

**Comment by isidorn** [comment] 2018-11-13 12:48
Looks like a duplicate of this one https://github.com/Microsoft/vscode/issues/43508

**Closed by isidorn** 2018-11-13 12:48 UTC
Labels: needs more info

**Comment by krasi-georgiev** [comment] 2018-11-13 13:17
yes a duplicate. I did a search , but couldn't find this issue.

Thanks
