### ISSUE TITLE
Minimap rendering a partial preview of selection

### ISSUE THREAD

**Issue by nilox94** [microsoft/vscode#89244] opened 2020-01-24 17:31 UTC
Issue Type: <b>Bug</b>

In few hundred lines documents, I can see how the current line is not shown on the minimap when the cursor is placed (approximately) after the second half of the document (in terms of the number of lines). When I select the whole document I can see how only the first half of the minimap is highlighted. This behavior begins when the document has more than 123 lines. e.g. in a 124 lines document, all lines except the last one are highlighted on the minimap. The rate of highlighted-lines/total-lines decreases as documents grow and tends to resemble 1/2.

VS Code version: Code - OSS 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-20T11:11:01.597Z)
OS version: Linux x64 5.4.12-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2552)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.38GB (4.92GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-code-run|bra|1.0.2
latex-workshop|Jam|8.6.0
python|ms-|2020.1.58038
cpptools|ms-|0.26.3
Go|ms-|0.12.0
vsc-octave-debugger|pau|0.3.16
octave|toa|0.0.3

``
![photo_2020-01-24_18-30-29](https://user-images.githubusercontent.com/6260113/73089989-b5f75f00-3ed7-11ea-93a6-7a915e6675ef.jpg)

**Comment by RMacfarlane** [comment] 2020-02-03 18:02
Duplicate of https://github.com/microsoft/vscode/issues/89354, this should already be fixed

**Closed by RMacfarlane** 2020-02-03 18:02 UTC
