### ISSUE TITLE
ctrl+b(toggle sidebar visibility) twice on "Keyboard Shortcuts" tab

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#24162] opened 2017-04-07 02:23 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1. open two file with the same filename
2. on "Keyboard Shortcuts" tab, ctrl+b(toggle sidebar visibility) twice
3. then the current tab is not "Keyboard Shortcuts" tab
![1](https://cloud.githubusercontent.com/assets/11925432/24782876/9ffbbae8-1b7b-11e7-8f43-f28529531def.JPG)

and after switching tab , the search text on "Keyboard Shortcuts" is gone..

**Comment by sandy081** [comment] 2017-04-18 12:39
@bpasero Looks like toggling the sidebar visibility is switching to the current focused file in the explorer. May I know what to do to retain the current active editor?

**Comment by bpasero** [comment] 2017-04-18 12:41
There is no way currently (and no setting). The explorer always restores the last active file when becoming visible.

**Comment by sandy081** [comment] 2017-04-18 12:44
Not sure why restoring is part of toggling side bar functionality? Any reason?

**Comment by bpasero** [comment] 2017-04-18 13:18
Well restoring causes the explorer to become visible and as such this logic kicks in. This is the behaviour pretty much since the day we shipped.

I think the issue here is that the explorer does not treat the keybindings editor as an editor that shows a file. E.g. I cannot reproduce this issue when using settings where the right hand side is indeed a file.

One motivation for having this behaviour is that you might want to switch back to your previous task by either making the explorer visible or moving to it (e.g. from the git viewlet) and then it is quite nice to get the last opened file restored.

**Comment by sandy081** [comment] 2017-11-27 10:12
I do not think, I can do much from keybindings editor side as this is a limitation from workbench.

**Closed** 2017-11-27 10:12 UTC
Labels: *out-of-scope, bug, keybindings
