### ISSUE TITLE
Quick pick vertical alignment is off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124382] opened 2021-05-21 17:15 UTC
Notice how the icons seem aligned to the bottom, there is also a bunch of extra padding on the bottom.

![image](https://user-images.githubusercontent.com/2193314/119174434-6bc7b480-ba1d-11eb-8b47-c205e0468d34.png)

**Comment by Ashray123** [comment] 2021-05-23 17:23
Hello @TylerLeonhardt I would like to work on this issue, any guide from your side on how to reproduce this and what is required to be done will be great.

**Comment by TylerLeonhardt** [comment] 2021-05-25 02:33
Great @Ashray123! You can repro this issue by running the VS Code command: 

![image](https://user-images.githubusercontent.com/2644648/119429884-9c7d4780-bcc4-11eb-8c11-79a869be0cb0.png)

My best advice is to dig into the html and css of the quick pick, the best way to do this is to get VS Code building locally and setting a breakpoint here:
https://github.com/microsoft/vscode/blob/main/src/vs/base/parts/quickinput/browser/quickInput.ts#L1630

Then you can open up the Dev Tools (search for Dev Tools in the Command Palette), then run the command above and you should be able to inspect the html and css.

The CSS is defined here:
https://github.com/Microsoft/vscode/blob/main/src/vs/base/parts/quickinput/browser/media/quickInput.css

I think we just need to add a little bit of padding to the top of the separators... and the space at the bottom of the quick pick is always there and I don't think we need to get rid of it at this time.

**Comment by Ashray123** [comment] 2021-05-25 19:02
@TylerLeonhardt  Would you please let me know what do you mean by setting a breakpoint at https://github.com/microsoft/vscode/blob/main/src/vs/base/parts/quickinput/browser/quickInput.ts#L1630 ?

**Comment by codebytesfl** [comment] 2021-07-10 07:25
Hello @TylerLeonhardt , I would like to pick up on this issue if possible.

**Comment by rzhao271** [comment] 2021-07-30 23:25
It's a bit better than in the original picture. I still see some inconsistent widths, though.
![Screenshot showing some inconsistency in margin or padding](https://user-images.githubusercontent.com/7199958/127720566-f905cf1a-e41b-4a9b-8324-13fd5c786ece.PNG)

**Comment by yash112-lang** [comment] 2021-08-06 09:38
Hello @TylerLeonhardt, is this issue is still open? I would like to work on this issue.

**Comment by rzhao271** [comment] 2021-08-06 16:27
Even though the milestone got moved, this issue is still open @yash112-lang

**Comment by TylerLeonhardt** [comment] 2021-08-06 16:38
Yeah the PR that did get merged in didn't fix the extra padding at the bottom.

**Comment by yash112-lang** [comment] 2021-08-07 01:42
Thank You. I'll start working on this issue.

**Comment by yash112-lang** [comment] 2021-08-07 05:55
@TylerLeonhardt, so basically the issue is of extra padding at the last terminal profile?
> ![Screenshot showing some inconsistency in margin or padding](https://user-images.githubusercontent.com/7199958/127720566-f905cf1a-e41b-4a9b-8324-13fd5c786ece.PNG)

**Comment by yash112-lang** [comment] 2021-08-07 07:59
Hello @TylerLeonhardt, I had done the changes. Can you look at it?
![image](https://user-images.githubusercontent.com/56151779/128593262-d9075f2a-8364-4742-909b-8a44cff95381.png)

**Comment by TylerLeonhardt** [comment] 2021-08-07 14:59
@yash112-lang is the bottom of the quick pick cut off in your screenshot?

**Comment by yash112-lang** [comment] 2021-08-07 15:06
I had updated the screenshot hope you see the changes 😀.

**Comment by TylerLeonhardt** [comment] 2021-08-07 15:11
Looks good! Please send a PR so I can see the code.

**Comment by yash112-lang** [comment] 2021-08-07 15:23
I had opened a pull request, I'm new to open source so if any mistakes let me know?

**Closed** 2021-08-12 20:31 UTC
Labels: bug, verification-found, polish, good first issue, quick-pick
