### ISSUE TITLE
Acrolinx extension view constrained on 1.86 Insiders

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#200766] opened 2023-12-13 17:24 UTC
- VS Code Version: VS Code 1.86 Insiders
- OS Version: Windows 11
- Acrolinx extension version: v1.2.2

Steps to Reproduce:

1. Install the Acrolinx extension (https://marketplace.visualstudio.com/items?itemName=acrolinx.vscode-sidebar) on 1.86 insiders
2. Open VS Code Insiders on a vscode-docs local repo (Acrolinx is licensed and enabled per repo)
3. Open the Acrolinx view by selecting the Acrolinx Activity bar icon

Notice that the view is constrained. It is not cropped as if you run Check, there is output and it fills the view (scrollbar is available)

![image](https://github.com/microsoft/vscode/assets/12818376/3ceb263b-0d48-4320-a4b3-9236d1ac6330)
 
This does not repro on 1.85.0 or 1.85.1 stable

**Comment by justschen** [comment] 2023-12-14 22:16
is this @sandeep-sen?

**Comment by seesharprun** [comment] 2023-12-21 15:49
I can repo this on the same version of Insiders:

![image](https://github.com/microsoft/vscode/assets/5067401/d1189ad8-a9c6-4819-900f-26c32f113e67)

The extension was last updated in July 2022: https://marketplace.visualstudio.com/items?itemName=acrolinx.vscode-sidebar

**Comment by sandy081** [comment] 2024-01-03 11:20
This is web view and hence assigning to @mjbvz

**Comment by mjbvz** [comment] 2024-01-03 16:40
Please start by filing this issue against that extension. They may need to update their code to work with the newer versions of Chromium we now ship with

The extension authors can follow up with us if VS Code is the root cause

**Closed by mjbvz** 2024-01-03 16:40 UTC

**Comment by seesharprun** [comment] 2024-01-03 19:59
> Please start by filing this issue against that extension. They may need to update their code to work with the newer versions of Chromium we now ship with
> 
> The extension authors can follow up with us if VS Code is the root cause

Unfortunately, the extension is now closed source. I filed a bug, and they responded that I should not use Insiders version with their extension.

If this new Chromium version ships in Feb with the latest stable, they will be forced to fix it then.
