### ISSUE TITLE
Timeline title bar buttons disappear

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#94105] opened 2020-04-01 02:02 UTC
- VSCode Version: 1.44 Insiders
- OS Version: Windows

Found while testing #93819

If you bring up the Timeline More Actions `...` dropdown, the title bar buttons are cleared.

![image](https://user-images.githubusercontent.com/12818376/78091515-e947e580-7381-11ea-85ff-e947450566fa.png)

This looks like a general issue with view title bar dropdowns as it also repros with the Outline More Actions dropdown.

**Comment by eamodio** [comment] 2020-04-01 06:34
Duplicate of #92029

**Closed by eamodio** 2020-04-01 06:34 UTC
