### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by januridp** [Microsoft/vscode#63079] opened 2018-11-14 03:37 UTC
Issue Type: <b>Bug</b>

I got update october and my editor starts annoying
https://twitter.com/i/moments/1062545196791955457

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.76GB free)|
|Process Argv|C:\Users\Januri\Desktop\promosi-dev.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.21.0
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
jquerysnippets|don|0.0.1
vscode-author-generator|edw|0.0.5
tslint|eg2|1.0.40
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.4.7
ftp-sync|luk|0.3.3
dotenv|mik|1.0.1
python|ms-|2018.10.1
atom-keybindings|ms-|3.0.4
vsliveshare|ms-|0.3.954
vscode-docker|Pet|0.3.1
LiveServer|rit|5.1.1
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joseph1125** [comment] 2018-11-14 15:15
duplicate of #62970

**Comment by roblourens** [comment] 2018-11-14 18:23
Does clearing notifications help?

**Closed** 2018-11-16 04:52 UTC
Labels: needs more info, new release
