### ISSUE TITLE
Object Literal in <script> of HTML produces TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dmbdesignpdx** [Microsoft/vscode#47922] opened 2018-04-16 01:19 UTC
Issue Type: <b>Bug</b>

While creating an object literal in a `<script>` of an **HTML file**, as soon as I type the starting quote of a quoted property name VS Code auto-completes the ending quote...
```html
<script>
   var obj = {
      ""
}
</script>
```

...but also throws the following error in the output channel:

```
[Error - 18:05:16] Error while computing completions for file:///Users/danielblake/Desktop/example.html: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at getCompletionEntriesFromSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:84803:65)
    at convertStringLiteralCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:84644:21)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:84609:23)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:103260:35)
    at doComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/out/modes/javascriptMode.js:78:49)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/out/htmlServerMain.js:320:38)
    at step (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/out/htmlServerMain.js:36:23)
    at Object.next (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/out/htmlServerMain.js:17:53)
    at fulfilled (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/out/htmlServerMain.js:8:58)
    at <anonymous>
```

This seems to only happen in an HTML file; I tried to reproduce in a JS file, but no error was thrown.
<br>
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (1.21GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1905105|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(6 theme extensions excluded)

**Comment by mjbvz** [comment] 2018-04-16 17:35
Duplicate of #46939

Should already be fixed in insiders

**Closed by mjbvz** 2018-04-16 17:35 UTC
Labels: typescript
