### ISSUE TITLE
Visual Studio Code is no longer responding

### ISSUE THREAD

**Issue by h2u** [Microsoft/vscode#160] opened 2015-11-19 08:06 UTC
Sometimes editor just freeze. Kill task helps only. Have this problem at work and home.
I noticed that this started after latest update (0.10.1).

Working in PHP files.

Windows 10 64.

**Comment by h2u** [comment] 2015-11-19 08:11
I noticed that this started after latest update.

**Comment by h2u** [comment] 2015-11-19 08:17
![image](https://cloud.githubusercontent.com/assets/5619582/11265652/b9798152-8ea6-11e5-9a04-ee1846a3f20a.png)

this is how my task manager looks at VSC freeze

**Comment by bingzheyuan** [comment] 2015-11-19 11:09
I have the same issue since 0.10.1, OS win7 64 bit

**Comment by DerTolleEmil** [comment] 2015-11-19 12:39
I am having the same issue when working on PHP files. At first I thought it was the new linter but I deliberately set the *php.validate.executablePath* to an invalid binary and the freezes still happen - I can confirm that php.exe is not getting called. The next thing I tried was to disable auto save; That did not help either. I am pretty sure that I can rule out both as the cause.

The next thing I did was running Process Monitor and Explorer to see if I can see anything that will lead to the freeze but I wasn't able to come up with anything. It is, however, always the same code.exe process that goes haywire. The affected process is launched with the following command:

`"C:\Program Files (x86)\Microsoft VS Code\code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\out\bootstrap" --type=pluginHost`

The process hanging has the following threads running:

![threads](https://cloud.githubusercontent.com/assets/10513218/11270763/e4f26f54-8ec1-11e5-8f44-7be78822102c.png)

The stack of the endlessly running thread is as follows:

![stack](https://cloud.githubusercontent.com/assets/10513218/11270772/04a93aa8-8ec2-11e5-9ab0-5bd5f54c0ce7.png)

Using Process Monitor I didn't see anything special regarding the freezes, I am also unable to reliably reproduce this but it is happening every few minutes, however, if the editor is left alone it seems ro run fine. It's only when you actually write some code that the editor seems to freeze after a while.

This is affecting me since 0.10.1 on Windows 7 x64, all possible patches applied.

**Comment by matthewjohnston4** [comment] 2015-11-19 13:08
Also happening to me while editing PHP files, although I haven't tried other files too. I thought it was extension related, but then I removed all extensions and it's still happening.

**Comment by blackwire** [comment] 2015-11-19 15:32
I'm experiencing this issue as well. Very often when working on files that are opened via WinSCP I get CPU spikes and then the program eventually freezes up and crashes. When I kill the Code process thread that is running up the CPU it levels out and doesn't crash, but Code says something about a plugin was terminated. Is there a way to backdate to an older exe version of Code? Code is no longer usable for me and I would like to be able to use the previous version until this gets fixed? Anyone know of a way to do this (go back to 0.9~)?

**Comment by DerTolleEmil** [comment] 2015-11-19 15:39
@blackwire Version 0.9.2: https://az764295.vo.msecnd.net/public/0.9.2/VSCodeSetup.exe

Not quite sure how to prevent the auto updating though, not sure if there is an option.

As for my freezes: I don't have any extensions or plugins that are not shipped by default. I think you are experiencing a different problem. Killing the pluginHost fork on my machine does nothing, code crashes completely.

**Comment by h2u** [comment] 2015-11-19 15:40
@blackwire, i was searching for old releases but didn't found anything.

**Comment by blackwire** [comment] 2015-11-19 15:45
@DerTolleEmil So, I don't have any non standard plugins either. Though, when I opened task manager and killed the process thread that was running as a part of code (not the app) that is using 30+% CPU it terminates intellisense I think, because it's no longer working after that point.

**Comment by blackwire** [comment] 2015-11-19 15:50
@DerTolleEmil Thank you for this! You saved my day! I can keep this open for today and get some work done without it crashing all the time. Life.. saver.

**Comment by DerTolleEmil** [comment] 2015-11-19 16:02
@blackwire Are you working on PHP files or are you using another language? So far I can only reproduce this when I edit files that are interpreted as PHP code.

**Comment by DerTolleEmil** [comment] 2015-11-19 16:15
@blackwire One more thing regarding auto-update: Edit your `%appdata%\code\storage.json` file and change `"updateChannel": "stable"` to `"updateChannel": "none"`. That will disable automatic updates.

**Comment by matthewjohnston4** [comment] 2015-11-19 16:19
Is everyone else using WinSCP too?

**Comment by DerTolleEmil** [comment] 2015-11-19 16:29
I'm not, my files are all saved locally without anything else touching them.

**Comment by blackwire** [comment] 2015-11-19 16:30
@DerTolleEmil I work primarily in PHP and yes, the issue does seem to arise while I'm working in a PHP file. Also, thank you very much for the update trick! This is great. I'll wait for issues to be resolved with the new version. I really like some of the features, but I need it to be stable before I can take it. Sad too because I was excited to see the themes were working properly. I'll be patient. Again, you've saved my bacon. I'll be able to get some things accomplished today.

**Comment by h2u** [comment] 2015-11-19 17:48
@DerTolleEmil, thank you for older version.

**Comment by DerTolleEmil** [comment] 2015-11-19 23:20
I got another freeze trying out a few things in a markdown file. I decided to try to reproduce the error and I did make a bit of progress but not much yet.

Here is what's working so far:

I created a new .php file with the following content:
```php
<?php
echo "asd";

echo "asd"
echo "asd";
?>
```

The empty line and the missing semicolon are on purpose. I open the file and then open the editor's development console and switch to the "console" tab. All I need to do now is go to the blank line and enter a function name, for example `fopen()`. As soon as I type the opening bracket you'll see the `[Plugin Host] provideSignatureHelp` console entry followed by the object containing the corresponding help text. So far so good, however, every now and then when I use an invalid function name I don't get the `[Plugin Host] no entry` console output but instead I don't get anything at all. What follows are those two warnings:

`WARNING: Promise with no error callback:undefined`
`Error: Promise did not implement oncancel(...)`

Unfortunately I don't have the line numbers right now because I un-minified the workbench.main.js file. However, the two log entries are printed by this code block:

```javascript
define("vs/base/common/winjs.base", ["./winjs.base.raw", "vs/base/common/errors"], function(e, t) {
    "use strict";

    function n(e) {
        var n = e.detail,
            r = n.id;
        return n.parent ? void(n.handler && o && delete o[r]) : (o[r] = n, void(1 === Object.keys(o).length && setTimeout(function() {
            var e = o;
            o = {}, Object.keys(e).forEach(function(n) {
                var r = e[n];
                r.exception ? t.onUnexpectedError(r.exception) : r.error && t.onUnexpectedError(r.error), console.log("WARNING: Promise with no error callback:" + r.id), console.log(r), r.exception && console.log(r.exception.stack)
            })
        }, 0)))
    }
```

From that point on the whole autocomplete/suggestion system acts completely crazy. Most of the time it won't show anything at all but a simple `Loading...` (and it never goes back to the desired behavior) and sometimes the editor will just freeze. The time between the errors and the editor freezing seems to be random.

Unfortunately it's not really 100% reproducible (I get it to freeze in 3 out of 10 tries or so).

Also, since I am just seeing that issue #266 has been referenced here as well. I also noticed that pasting lots of code (I copied a few hundred lines of simple ```php echo "asd";``` lines) seems to work as well sometimes although that might just be a coincidence. At least I wasn't really able to properly reproduce anything.

**Comment by mworchel** [comment] 2015-11-20 01:47
Experiencing very crashy behavior together with PHP aswell

**Comment by ACCBizon** [comment] 2015-11-20 09:40
same issue,

**Comment by Dev-P** [comment] 2015-11-20 20:47
I'm facing this problem every minutes!

**Comment by bpasero** [comment] 2015-11-20 21:46
This issue is under investigation, stay tuned!

**Comment by bpasero** [comment] 2015-11-21 08:30
I can reproduce that the plugin host process hangs at 100% CPU by simply completing on functions (e.g. fopen()). I also see the console full of normal messages and promise errors. Setting target to recovery build, this is pretty bad.

In my case I did not install any PHP, so the executable was still set to NULL in settings.

**Comment by aeschli** [comment] 2015-11-21 23:12
Fix delivered. Signature help was getting into an infinite loop when no open parent was found.
Thanks to everyone for helping tracking this down!

**Closed by aeschli** 2015-11-21 23:12 UTC

**Comment by Dev-P** [comment] 2015-11-22 17:40
Great @aeschli ! Thanks.

**Comment by blackwire** [comment] 2015-11-23 00:13
@aeschli Thanks! When do you think there will be a new build available? It's not a huge problem, because I was able to get the old build and stop the updates temporarily, but I enjoyed the features of the new version. Just curious more than anything. Appreciate all the help!

**Comment by egamma** [comment] 2015-11-23 09:38
We are planning an update end of this week.

**Comment by h2u** [comment] 2015-11-23 10:50
@egamma, would be great!

**Comment by kurotsukikaitou** [comment] 2015-11-23 12:25
I see. So a lot of people experience this issue. Kudos to you guys for finding the cause pretty fast. :3

**Comment by isidorn** [comment] 2015-11-24 16:21
I have reviewed the change set and it looks good to me.
I would verify that no other place in php might be affected by going from 1 base to 0 base line numbers.

**Comment by xianghongai** [comment] 2016-03-26 04:14
![vc-bug](https://cloud.githubusercontent.com/assets/2075006/14057991/16968754-f34c-11e5-9ecd-cfff4f649270.png)

re or wait or exit , can't fix~

**Comment by xianghongai** [comment] 2016-03-26 04:18
kill vc process, change folder or file name~

**Comment by alexandrudima** [comment] 2016-03-29 12:05
@xianghongai Can you please create a new issue with reproducible steps?

**Comment by martinandersen3d** [comment] 2016-06-22 19:16
xianghongai  > same error here...

**Comment by ezwiebel** [comment] 2016-06-30 05:40
Same strange behaviour here but only since yesterday.
I have a multi language project (ReactJS + Go) and since I installed go extensions (that work very well), VSC seems to not be able to handle ReactJS anymore... No crash, no freeze but a process à 1.3GB memory and ~60% CPU. Cannot use any of the tools I used to (completion, navigation, etc...) Only displays a `Loading...` message.

Very annoying now that I have to go back to frontend dev.

**Comment by alexandrudima** [comment] 2016-06-30 07:55
@ezwiebel Please create a new issue with some information about your project and ping @dbaeumer

**Comment by dontcryme** [comment] 2016-07-06 07:29
same issue...version 1.2.1

![image](https://cloud.githubusercontent.com/assets/18712822/16610532/bf280a10-4396-11e6-989c-a6f9fdb57855.png)

**Comment by beytek** [comment] 2016-07-10 18:44
same has happened to me for the first time today (it happened today several times, but never before today)

**Comment by beytek** [comment] 2016-08-10 09:10
This seems to happen mostly when I am editing large css files (more than 10,000 lines)

**Comment by vmandic** [comment] 2016-08-11 10:34
+1 freezing on two documents opened side by side (small html + less). Installed over 10 plugins, npm stuff. I am suspecting in the intellisense as it mostly freezes while typing stuff in the html file. Documents are small, a few hundred lines. Will try disabling plugins...

**Comment by beytek** [comment] 2016-08-11 10:39
Could be intellisense or the small colour preview square (just my
observation)

**Comment by alexandrudima** [comment] 2016-08-11 14:53
@vmandic @beytek Please create new issues with detailed steps. The message "Visual Studio Code is no longer responding" is shown in all cases the renderer process appears stuck to the main process and it can happen due to a large number of causes. I will lock the conversation on this issue, so we get new issues with new steps.
