### ISSUE TITLE
Do not start without the internet

### ISSUE THREAD

**Issue by ammarfahad** [Microsoft/vscode#63158] opened 2018-11-14 18:05 UTC
Issue Type: <b>Bug</b>

Whenever i  close my wi-fi or set the airplone mode on, the vs code does not start. I don't know why this is happening please fix this

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.86GB (7.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.20
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.5.1
beautify|Hoo|1.4.7
python|ms-|2018.10.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
vscode-icons|rob|7.28.0
JavaScriptSnippets|xab|1.7.1

(8 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2018-11-14 18:11
https://github.com/Microsoft/vscode/issues/7570

What does `code --version` print?

**Comment by JaWiD2** [comment] 2018-11-15 00:51
Hi,
I have same issue since update OS to Windows 10 x64 10.0.17763 (version 1809) on both PC and laptop for any version of VSCode.
Access internet is optional , OS must have Network access (i.e LAN) to open VSCode.
`code --version` returns:
```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```
also i have this problem with visual studio installer (vs 2017 setup) , without network access OS cant open it!

**Comment by roblourens** [comment] 2018-11-15 01:11
Dupe of the above issue

**Closed by roblourens** 2018-11-15 01:11 UTC
Labels: needs more info, new release
