### ISSUE TITLE
No go-to-definition support across files in vscode.dev (typescript)

### ISSUE THREAD

**Issue by dlvhdr** [microsoft/vscode#151231] opened 2022-06-03 16:39 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2 (vscode.dev)
- OS Version: Mac OS Monterey 12.4, Chrome Version 102.0.5005.61 (Official Build) (x86_64)

The web version of vscode is lacking some LSP features for Typescript, like the go-to definition across files.

Steps to Reproduce:

Open a typescript project
Do a language service action
Expected Result: Same as desktop experience

**Comment by mjbvz** [comment] 2022-06-03 19:38
Duplicate of https://github.com/microsoft/TypeScript/issues/47600

**Closed by mjbvz** 2022-06-03 19:38 UTC
