### ISSUE TITLE
showQuickPick input events?

### ISSUE THREAD

**Issue by nocksock** [Microsoft/vscode#34811] opened 2017-09-22 08:43 UTC
Hi there!

I was wondering if there is a way to get input events for the `showQuickPick` dialog? For example I want to handle the return key when all items have been filtered out, so that the QuickPick kinda acts like a combination of Input and QuickPick.

**Comment by ramya-rao-a** [comment] 2017-09-22 17:15
The quick pick control returns a promise.
When user hits ENTER, the promise completes with the value that was chosen.
Wouldn't that work for you?

**Comment by nocksock** [comment] 2017-09-22 17:31
@ramya-rao-a Unfortunately not. Given a list of `[1, 2, 3]` when the user enters `4` and hits return, I want something to happen – or at least the promise to be completed with the entered value. 

Right now, nothing at all happens. It would be nice if one could handle these situations. eg. showing an error, a hint in place of the list or use that value for something else entirely.

**Comment by jrieken** [comment] 2017-09-25 06:49
duplicate of #21372

**Closed by jrieken** 2017-09-25 06:49 UTC
Labels: api, quick-pick
