### ISSUE TITLE
AutoFormat feature does not indent function declaration in function calls properly

### ISSUE THREAD

**Issue by fguitton** [Microsoft/vscode#51524] opened 2018-06-09 16:25 UTC
- VSCode Version: 1.24.0
- OS Version: Windows 10

Hello everybody !

The following issue is also present on a vanilla fresh install of VSCode Insider.

With the AutoFormat function; when trying to make function declaration inside a function call `.then(` the indentation of the first function is broken. Subsequent function indentation work as expected until the parenthesis is closed :

![image](https://user-images.githubusercontent.com/2495155/41193732-7c1f2e5a-6c08-11e8-851b-93093bc110d3.png)

As you can see the first function gets aligned as though it was under `.find(`. As we can see ESLint (active on the project) is picking up on it.

Below you can see that when I manually place the function on the next line, it then indents properly.

![image](https://user-images.githubusercontent.com/2495155/41193737-93c4c56a-6c08-11e8-890f-80eba4322782.png)

Best day to you all 👍

**Comment by mjbvz** [comment] 2018-06-11 15:54
Duplicate of https://github.com/Microsoft/TypeScript/issues/14589

**Closed by mjbvz** 2018-06-11 15:54 UTC
Labels: new release
