### ISSUE TITLE
Allow Zooming on Small Images

### ISSUE THREAD

**Issue by pmartindev** [Microsoft/vscode#27281] opened 2017-05-25 16:22 UTC
I am working on a repository that contains very small images (10x10 pixel .png files). I would like to view these images contained in my repository before and after running code to modify them. However, they are much too small, and I am forced to use a 3rd party application. This is rather tedious when modifying multiple images at once.

**Comment by mjbvz** [comment] 2017-11-03 20:34
Duplicate of #18987

**Closed by mjbvz** 2017-11-03 20:34 UTC
Labels: duplicate, feature-request, help wanted
