### ISSUE TITLE
Support outline？

### ISSUE THREAD

**Issue by ivysrono** [Microsoft/vscode#34698] opened 2017-09-20 13:46 UTC
For markdown, show outline on sidebar.

**Comment by mjbvz** [comment] 2017-09-20 15:52
This is a duplicate of #5605

You can use cmd+shift+o to see the symbol drop down. Try this extension to get this in the sidebar: https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline

Closing as duplicate of #5605

**Closed by mjbvz** 2017-09-20 15:52 UTC
Labels: duplicate, markdown
