### ISSUE TITLE
VSCode locks directories, making them unable to be deleted

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#71718] opened 2019-04-04 11:23 UTC
Issue Type: <b>Bug</b>

I am not sure how to reproduce this consistently, but after one of the later updates, any command that deletes directories like `npm install` and `npm ci` or `rm -rf` (in git bash) frequently fail because of missing permissions. After a restart of VSCode, the problem usually goes away.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
toggle-excluded-files|eam|1.6.0
EditorConfig|Edi|0.13.0
RunOnSave|eme|0.0.18
vscode-test-explorer|hbe|2.9.1
vscode-language-pack-de|MS-|1.32.4
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.6.1
project-snippets|reb|0.5.0
java|red|0.42.1
vscode-coverage-gutters|rya|2.3.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by AlCalzone** [comment] 2019-04-04 12:35
No @vscodebot, this has (almost) nothing to do with the integrated terminal.

**Comment by mjbvz** [comment] 2019-04-05 02:36
Do you know which files are locked? This could be https://github.com/Microsoft/TypeScript/issues/29407

**Comment by AlCalzone** [comment] 2019-04-05 04:59
@Types is on the list, but sometimes it's the build directory too.

**Comment by AlCalzone** [comment] 2019-04-05 05:44
I just had it happen again - this time it was a dependency in node_modules that was registered as a typescript plugin

**Comment by mjbvz** [comment] 2019-04-06 01:50
Ok, do you still see this if you disable all extensions?

**Comment by AlCalzone** [comment] 2019-04-08 17:06
@mjbvz I just reproduced it with disabled extensions. It seems to happen more frequently (but not exclusively) when I `git pull` or something before running `npm ci` while editor windows with TypeScript in it are open.

What I did just now:
0. Error happened (could not compile with `tsc`), close VSCode
1. `code --disable-extensions`
1. `tsc` - worked
1. `git reset --hard HEAD~3` with typescript files open
1. `npm ci` with typescript files still open --> error:
```
$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path C:\Repositories\node-zwave-js\node_modules\@types
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Repositories\node-zwave-js\node_modules\@types'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Repositories\node-zwave-js\node_modules\@types']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Repositories\node-zwave-js\node_modules\@types'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Repositories\\node-zwave-js\\node_modules\\@types' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Repositories\\node-zwave-js\\node_modules\\@types\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Repositories\\node-zwave-js\\node_modules\\@types' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
```
1. restart VSCode again
1. `npm ci` --> works
1. `git reset --hard origin/master`
1. `npm ci` --> same error as above

**Comment by mjbvz** [comment] 2019-04-08 18:13
Thanks. Yes this is a duplicate of Microsoft/TypeScript#29407

We're pushing to get this fixed upstream quickly

**Closed by mjbvz** 2019-04-08 18:13 UTC
