### ISSUE TITLE
Formatting JS code removes spaces before closing parenthesis

### ISSUE THREAD

**Issue by ma2ciek** [Microsoft/vscode#21136] opened 2017-02-22 14:27 UTC
- VSCode Version: 1.9.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Use settings:
```js
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
```
2.Type:
```js
setTimeout( function() {

} );
```
3. Format it.

**Result:**
Now the result is following and space before curly brace is eaten:
```js
setTimeout( function() {

});
```

**Expected Result:**

No change after formatting.

**Comment by roblourens** [comment] 2017-02-23 05:51
This seems right - the setting is for after opening and before closing, ie inside the brackets, right?

**Comment by ma2ciek** [comment] 2017-02-23 09:38
Ow, I made a typo in the title. 
Space should be before closing parenthesis.

**Comment by mjbvz** [comment] 2017-02-24 00:55
@ma2ciek I believe this was fixed in TS 2.2. Try it out in [VSCode insiders](https://code.visualstudio.com/insiders) and let me know if you still see this

**Closed by mjbvz** 2017-02-24 00:55 UTC
Labels: format, javascript

**Comment by ma2ciek** [comment] 2017-02-24 10:34
Yep, It's fixed in VSCode insiders already. Thanks a lot. But it's not a TS issue (?). TS doesn't format JS code.

**Comment by mjbvz** [comment] 2017-02-25 00:00
@ma2ciek Glad to hear the issue is fixed.

We use the TypeScript library to support both JavaScript and TypeScript code so, even though you are working in JS, the TypeScript library was probably was the root cause here
