### ISSUE TITLE
run npm scripts in the active terminal

### ISSUE THREAD

**Issue by carolitascl** [Microsoft/vscode#51508] opened 2018-06-09 03:18 UTC
Npm scripts allways open a new terminal to run it. The expected behavior is that a npm script run in the active terminal. For example, if you have a terminal window splitted in two, and you need to run two npm scripts, each of them has to run in each splitted terminal and not in a new one.

**Comment by Tyriar** [comment] 2018-06-09 08:34
I think this is a dupe of https://github.com/Microsoft/vscode/issues/49737

**Closed by Tyriar** 2018-06-09 08:34 UTC
Labels: integrated-terminal
