### ISSUE TITLE
Add LivePreview feature

### ISSUE THREAD

**Issue by Ayman97** [Microsoft/vscode#42875] opened 2018-02-03 11:05 UTC
Isn't awesome to see this feature in VS Code ?

**Comment by PixelT** [comment] 2018-02-03 11:48
It doesn't make sense to add this as an editor's functionality
Use https://browsersync.io/ instead

**Comment by Ayman97** [comment] 2018-02-03 13:37
@usernamehw 
Like the built-in feature that exists in Brackets

**Comment by Ayman97** [comment] 2018-02-03 13:37
@PixelT I'll try it, Thanks

**Comment by usernamehw** [comment] 2018-02-03 13:44
Duplicate of https://github.com/Microsoft/vscode/issues/12080 ?

**Closed** 2018-02-05 09:39 UTC
Labels: editor, editor-core
