### ISSUE TITLE
Using git bash in VS Code integrated terminal, `interactive.singleKey` setting does not work

### ISSUE THREAD

**Issue by rcdailey** [microsoft/vscode#155998] opened 2022-07-22 20:18 UTC
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.69.2 (system setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

Steps to Reproduce:

1. Open a "Git Bash" terminal inside VS Code:
   ![image](https://user-images.githubusercontent.com/1768054/180518963-096ab608-11bb-4180-8f38-a398856984b9.png)
3. Run `git config --global interactive.singleKey true`
4. `cd` into a valid git repository
5. Make some local modifications to one or more files
6. Run `git add -p`
7. When prompted to stage a single hunk, press `y` (Yes). Because `interactive.singleKey` was set, this should immediately accept your input and proceed to the next hunk. However, it does not. Instead, it waits for you to press `ENTER`. This is the defect.

When I run the above steps in a dedicated Git Bash terminal (outside of VS Code), the `singleKey` setting is respected and the `git add -p` behavior is as expected.

**Comment by Tyriar** [comment] 2022-12-07 18:42
I cannot reproduce this on:

Version: 1.74.0-insider (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T10:17:57.998Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

I believe this is fixed in a later version of conpty which is shipped with Windows updates.

**Closed by Tyriar** 2022-12-07 18:42 UTC
Labels: bug, confirmation-pending, terminal-shell-git-bash

**Comment by rcdailey** [comment] 2022-12-07 21:57
@Tyriar How can I check that I have the same version of conpty that you do? And what version did you test with? I'll be honest, I have no idea what conpty is.

**Comment by Tyriar** [comment] 2022-12-07 22:12
@rcdailey it's shipped with Windows, I'm on 10.0.22621, you're on 10.0.19044

**Comment by Tyriar** [comment] 2022-12-07 23:02
@rcdailey I'm on the Insiders channel so I get much earlier updates

**Comment by rcdailey** [comment] 2022-12-07 23:45
@Tyriar Do you know when that version will hit general release channels? I need some way to remember to re-test this and verify it's fixed as you assert.

Thanks.
