### ISSUE TITLE
Node debug Step Over/Into hangs in 1.9

### ISSUE THREAD

**Issue by chiangf** [Microsoft/vscode#19841] opened 2017-02-03 14:12 UTC
- VSCode Version: 1.9
- OS Version: 10.12.3

Steps to Reproduce:

1. Set a breakpoint and start debugging node process
2. After breakpoint is hit, just try to Step Over (F10) or Step Into (F11) and both will hang. However, if you set a breakpoint on the next line, and do Continue (F5), it'll continue.

This did not happen in 1.8.1 but started happening right after 1.9.

**Comment by wshirey** [comment] 2017-02-03 14:51
Also having this issue.

**Comment by AngefloMusic** [comment] 2017-02-03 15:39
Also having issues with the debugger becoming unresponsive and hanging.

**Comment by weinand** [comment] 2017-02-03 20:50
Which version of node are you suing?
Which version of the node debugger are you using? `node` or `node2`?

**Comment by wshirey** [comment] 2017-02-06 16:53
binary versions
```bash
$ node -v
v5.8.0

$ node-debug -v
Node Inspector v0.12.7
```

launch.json config
```json
{
  "version": "0.2.0",
  "configurations": [

    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/index.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "port": 5858
    }
  ]
}
```

**Comment by weinand** [comment] 2017-02-06 17:00
@wshirey what OS is this?
Does it make a difference if you change the debug type from 'type' to 'type2'?

**Comment by wshirey** [comment] 2017-02-06 17:09
`macOS 10.12.2`

If I change the `type` property to `type2` property in the configurations object list, I get prompted for what environment I want to debug.

![screen shot 2017-02-06 at 11 08 40 am](https://cloud.githubusercontent.com/assets/1452263/22657612/b7189e10-ec5c-11e6-98ca-cef934270f48.png)

**Comment by weinand** [comment] 2017-02-06 17:12
oops, sorry, I miss typed... It should have read:
Does it make a difference if you change the debug type from 'node' to 'node2'?

**Comment by wshirey** [comment] 2017-02-06 17:14
Debugger immediately quits.

![screenshot 2017-02-06 11 14 49](https://cloud.githubusercontent.com/assets/1452263/22657812/722e3502-ec5d-11e6-9443-c2209b140964.png)

**Comment by weinand** [comment] 2017-02-06 17:18
@wshirey makes sense, since you said above that you are using node v5.8.

**Comment by chiangf** [comment] 2017-02-09 02:48
I'm using node v6.9.5 with OSX 10.12.3

I've tried both `node` and `node2` but both have the same behavior.

**Comment by weinand** [comment] 2017-02-09 09:46
We are not able to reproduce this problem.
Do you you have a minimal repro that we can try?

**Comment by adelphes** [comment] 2017-02-09 11:03
For me, this issue appears to be related to the number & size of the local variables. In particular, creating large objects (not arrays) causes the debugger to hang a lot when breakpoints are hit - and for some reason it does seem to be worse in 1.9.

I have since changed my configuration to `node2` which improves things, but I do still occasionally find the debugger hangs - and when it does, the only option is to terminate and start again.

**Comment by chiangf** [comment] 2017-02-09 12:19
That's similar to what I'm finding too. For simple node scripts, it usually doesn't hang (although occasionally it does). But with a more complex express app with `async.js` etc., it hangs every time.

**Comment by weinand** [comment] 2017-02-09 14:10
Please post a screenshot of the debugger UI when it hangs.

**Comment by wmc777** [comment] 2017-02-14 18:41
I think this might be the same issue as #20608

**Comment by adelphes** [comment] 2017-02-16 23:35
This problem appears to be related to watches. Adding a watch causes the debugger to hang on a step command; removing all watches makes it work again.
Not sure if this is the same issue everyone else is experiencing, but here's a video of it happening - in the first part, I'm successfully stepping into `forEach`; I terminate, add a watch and run the same program - it then hangs when stepping into the same `forEach`.
![aoutput](https://cloud.githubusercontent.com/assets/13035517/23046237/60854c64-f4a0-11e6-9f12-feb781b4e432.gif)

**Comment by Eli-Goldberg** [comment] 2017-02-20 18:08
Having the same issue for a while now,
For me it only happens in projects involcing 'Q' module

**Comment by adelphes** [comment] 2017-02-20 18:11
FYI @weinand @roblourens 
OK, so I finally got tired of this issue and debugged the node2 debugger to see what was happening.
And tbh, I was pretty disappointed by what I found.

The issue has already been logged and "fixed": https://github.com/Microsoft/vscode-chrome-debug-core/issues/148

I say "fixed" because the issue is a timing problem - what's happening is that the exact order of the step, resume, evaluate and pause events change depending upon how much work is going on in the process.
The change applied to fix this is to wait for an arbitrary 50ms before trying to perform the evaluation.
Seriously guys - this is lazy development; you can't fix a timing issue by saying "we'll just wait for a few milliseconds and hope for the best"

I expected much better from Microsoft.

Can you please fix this. And not by increasing the delay - make the adaptor robust enough to handle events in any order.

**Comment by roblourens** [comment] 2017-02-20 23:08
It's really a V8 bug, I was able to repro this in Chrome devtools too - I expected better from Google :P

@isidorn Did anything change in 1.9 about when the evaluate request for a watch is sent after a step?

**Comment by isidorn** [comment] 2017-02-21 08:35
@roblourens no.

**Comment by roblourens** [comment] 2017-02-22 19:14
Ok, I'll look at this again and see if there's a better fix.

**Comment by roblourens** [comment] 2017-03-02 19:02
I went back to investigate this and it seems to have been fixed by #21524, with or without my timing hack. Now we don't globally eval watches, and while stepping, the eval request is only sent once the debug adapter has successfully paused. Would appreciate it if you try it out in the Insiders build and let me know.

**Closed by roblourens** 2017-03-02 19:02 UTC
Labels: debug

**Comment by chrmarti** [comment] 2017-03-31 22:59
Could someone on this thread who saw this problem confirm it is fixed with the latest insiders builds?

I tried to verify it, but I cannot reproduce in 1.10.2, so I cannot tell for sure if it is fixed.

**Comment by chiangf** [comment] 2017-04-01 00:38
I'm on 1.10.2 and it looks fixed to me, 👍

**Comment by Eli-Goldberg** [comment] 2017-04-01 05:23
I was getting thit A LOT, seems fixed.
Thanks !!
