### ISSUE TITLE
[html] Pasting HTML code adds extra closing tag on first line

### ISSUE THREAD

**Issue by nickbstudy** [microsoft/vscode#227859] opened 2024-09-07 02:57 UTC
Type: <b>Bug</b>

Paste something like

<div>
    <p>hello world</p>
</div>

and it will automatically insert a closing tag for the first line, showing up as:

<div></div>
    <p>hello world</p>
</div>

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700F (24 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.83GB (50.92GB free)|
|Process Argv|--crash-reporter-id f57729e2-1416-48b3-8c6b-c2a08645c162|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
emmet-jss|car|1.0.0
es7-react-js-snippets|dsz|4.4.3
auto-rename-tag|for|0.1.10
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.10.16
csharp|ms-|2.45.20
vscode-dotnet-runtime|ms-|2.1.5
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.2
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.13
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by AlexDawsonUK** [comment] 2024-09-07 15:48
Can confirm. Reproducable with the following steps:

1. Paste:
2.

**Comment by AlexDawsonUK** [comment] 2024-09-07 15:57
Can confirm, reproducable with the following steps.

1) Paste the following into an HTML5 formatted document
```
<select>
	<option value="1">Americano</option>
	<option value="2">Latte</option>
	<option value="3">Green Tea</option>
</select>
```
VSCode adds a closing tag seen here...
```
<select></select>
	<option value="1">Americano</option>
	<option value="2">Latte</option>
	<option value="3">Green Tea</option>
</select>
```
Currently can only be resolved with Settings > HTML: Auto Closing Tags (Disable).

Version: 1.93.0 (Universal)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by aeschli** [comment] 2024-09-12 10:22
There was a change in how the paste is reported on the extension side.
Instead of a single `TextDocumentChangeEvent`, we now get one event per line.

@hediet Any idea if that change was intended?

**Comment by aeschli** [comment] 2024-09-12 14:16
Sorry, I was wrong, nothing has changed with the `TextDocumentChangeEvent`.

The bug is caused by https://github.com/microsoft/vscode/blob/e4ffea486528c0ae1d00cd03d814c14000f99ec6/extensions/html-language-features/client/src/autoInsertion.ts#L71 (thans @hediet for finding this out). 
There can be eol-characters in `lastChange.text`. The new Position is then not valid with a character offset far off.

We only see this now as the last HTML service update (https://github.com/microsoft/vscode/commit/ce9ce04ab598dfcc78c7cbde5c24f2fe1a8a50f2) included an update of the `TextDocument`, where we now handle invalid positions and normalize them as spec'ed.: https://github.com/microsoft/vscode-languageserver-node/pull/1286

The workaround for users is to manually remove the inserted code, or, if that's too much of a hassle, turn off the auto close feature: `"html.autoClosingTags": false`

**Comment by LucasOe** [comment] 2024-10-03 17:18
Has this been fixed in version 1.94 with #228662? This issue is still open.

**Comment by dailytabs** [comment] 2024-10-05 05:18
Had the issue, which led me here. Noticed the update icon after seeing the last comment. Help: About is now showing 1.94.0. Still had the code on my clipboard, pasted it again, and **no ending tag was added**.

**Comment by siakaramalegos** [comment] 2024-10-16 15:35
Thanks, @dailytabs for mentioning that. I can confirm that after updating to 1.94.2, the bug seems to be fixed for me too. I'm so happy because this was so annoying. I kept wondering why my code changes were so weird and forgetting the extra closing tag it kept inserting. Thanks, all!

**Closed** 2024-10-24 16:03 UTC
Labels: bug, html

**Comment by nickbstudy** [comment] 2024-10-25 05:17
Appears to be fine now, thanks everybody!
________________________________
