### ISSUE TITLE
[Bug] Html Snippet Auto-complete with multiple cursors only first line

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#9627] opened 2016-07-22 15:59 UTC
- VSCode Version: 1.3.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. The easy way is to install [jhon's papa Angular 2 TypeScript Snippets](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2) addon.
2. Open html file, add new lines, select them with multicursor and try to use any snippet.
3. It will only fill the first line with the snippet, see example output below.

Input:
![image](https://cloud.githubusercontent.com/assets/9698639/17063214/d5163b00-4ffb-11e6-9ba0-f3db5ad7d226.png)

Output after applying snippet:
![image](https://cloud.githubusercontent.com/assets/9698639/17063026/04440f16-4ffb-11e6-9acf-8ff58172d84f.png)

### Note: 
The Angular 2 snippet is an easy way to test, however similar thing happens with normal tags:
![image](https://cloud.githubusercontent.com/assets/9698639/17063196/b95c04bc-4ffb-11e6-9244-a294bcb2a459.png)

Output after applying snippet:
![image](https://cloud.githubusercontent.com/assets/9698639/17063167/933d5e2a-4ffb-11e6-8a50-a39d6626e7b1.png)

**Comment by kieferrm** [comment] 2016-07-22 17:35
Duplicate of #5578.

**Closed by kieferrm** 2016-07-22 17:35 UTC

**Comment by Luchillo** [comment] 2016-07-22 19:02
Maybe, however it seems to happen in html and in Go but not in TS nor JS.
