### ISSUE TITLE
Suggestion diagnostic dots show over entire range in high contrast theme

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#47511] opened 2018-04-09 17:21 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. In high contrast theme
1. Open a js file:

```js
module.exports = function() {
    console.log('hello high contrast world')
}
```

**Bug**
Many dots covering entire span:

![screen shot 2018-04-09 at 10 20 19 am](https://user-images.githubusercontent.com/12821956/38512260-a5238ef8-3bdf-11e8-9e9c-9afe36e3799d.png)

I believe we should only show three dots

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment] 2018-04-10 06:58
We don't use dots in HC mode but an underline of the whole marker (for better visibility). I do agree that it's not looking nice but I'd say this is a duplicate of the 'multiline-hint-diagnostics'-issue. Closing as dupe of #47346

**Closed by jrieken** 2018-04-10 06:58 UTC
Labels: bug, lang-diagnostics
