### ISSUE TITLE
Search/replace results: align right the folder path

### ISSUE THREAD

**Issue by koteyur** [microsoft/vscode#100280] opened 2020-06-16 11:01 UTC
I think it would be nice to have this:
![Screenshot from 2020-06-16 12-53-09](https://user-images.githubusercontent.com/4014972/84766076-805f2980-afd0-11ea-80c1-2363694817ed.png)
Instead of this:
![Screenshot from 2020-06-16 12-56-28](https://user-images.githubusercontent.com/4014972/84766298-dd5adf80-afd0-11ea-91c9-cef374eb24fd.png)

To be able to see which files are in the same folder and which are not.
It's really useful when you have a lot of search results in the large project.

**Comment by gjsjohnmurray** [comment] 2020-06-16 11:15
/duplicate of #74637

@koteyur your suggestion of right-aligned paths doesn't exactly match proposals in the linked issue, so you may like to contribute ideas there.

**Closed** 2020-06-16 11:15 UTC
Labels: *duplicate
