### ISSUE TITLE
New terminal lines rendering cuts off bottom/top of characters like underscore

### ISSUE THREAD

**Issue by viktorku** [microsoft/vscode#35901] opened 2017-10-09 12:45 UTC
The new terminal rendering cuts off the bottom part of "long" characters, such as `g`, `j` and `y`.

1.17.0:
![image](https://user-images.githubusercontent.com/14088269/31338405-57b2c1bc-acff-11e7-90d2-923670afef0f.png)

1.17.1: 
![image](https://user-images.githubusercontent.com/14088269/31448664-4b17bdca-aea5-11e7-93c3-81e3366197ad.png)

- VSCode Version: 1.17.0
```
Version 1.17.0
Commit be377c0faf7574a59f84940f593a6849f12e4de7
Date 2017-10-04T23:33:45.303Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version: Ubuntu Trusty 14.04

Steps to Reproduce:

1. Open the Terminal
2. Start typing `git checkout -b feature/object`

Reproduces without extensions: Yes

**Comment by fpauser** [comment] 2017-10-09 18:19
Same problem here.

**Comment by ahmadkhalidjs** [comment] 2017-10-09 18:29
similar to #35794 but on fedora it cuts off the top part

**Comment by masonj88** [comment] 2017-10-09 18:34
Chops the top off on Fedora 26.
![badterminal](https://user-images.githubusercontent.com/25966620/31352999-10ddc036-acee-11e7-8b19-2565afa87f61.png)

**Comment by imgss** [comment] 2017-10-10 02:48
Same problem here.
![](http://images2017.cnblogs.com/blog/1016471/201710/1016471-20171010104816996-582225799.png)

**Comment by ivcosla** [comment] 2017-10-10 08:32
I just changed the `"terminal.integrated.fontFamily"` value. My issue was that underscores were not displayed using `DejaVu Sans Mono`. With other fonts they are displaying, not sure if it would help to fix your problem guys, but sure is worth to give it a try.

**Comment by jashworth** [comment] 2017-10-10 09:11
The variable width font that I'm partial to now looks like this.

![image](https://user-images.githubusercontent.com/4151375/31378418-1ac275fa-ada3-11e7-8d5e-1eae8f63578a.png)

**Comment by Tyriar** [comment] 2017-10-10 15:13
@imgss see https://github.com/Microsoft/vscode/issues/35660
@jashworth see https://github.com/Microsoft/vscode/issues/35681

**Comment by Tyriar** [comment] 2017-10-10 15:14
@viktorku what's in your settings.json file?

**Comment by viktorku** [comment] 2017-10-11 15:02
In 1.17.1 the rendering changed (it's somewhat blurrier and smaller fontsize) but the bug prevails:

![image](https://user-images.githubusercontent.com/14088269/31448642-3ece11cc-aea5-11e7-9c47-b8508ba96dea.png)

@Tyriar This also happens for a fresh code instance (without `settings.json` in the project's root `.vscode`). My User Settings are like this:

```json
{
    "workbench.sideBar.location": "left",
    "files.exclude": {
        "**/.git*": false,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/.tags*": true,
	"**/.pyc": true,
        ".catkin_tools/**/packages": true,
        "build": true,
        "devel": true,
        "logs": true,
        "src/external": true,
        "**/CMakeLists.txt.user": true,
        "**/__pycache__": true
    },

    "editor.fontSize": 12,
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "editor.rulers": [
        100
    ],

    "[python]": {
        "editor.tabSize": 4
    },

    "files.trimTrailingWhitespace": true,
    "diffEditor.ignoreTrimWhitespace": false,

    "workbench.editor.enablePreviewFromQuickOpen": false,

    "window.zoomLevel": 0,

    "clang-format.executable": "/usr/bin/clang-format-3.8",
    "clang-format.style": "Google",
    "clang-format.language.javascript.enable": false,

    "prettier.printWidth": 100,
    "prettier.singleQuote": true,
    "prettier.bracketSpacing": true,
    "workbench.colorTheme": "One Dark Pro",

    "editor.multiCursorModifier": "alt",
    "git.ignoreLegacyWarning": true,
    "workbench.startupEditor": "newUntitledFile",

    "eslint.nodePath": "/home/viktor/.nvm/versions/node/v7.4.0/bin/node",

    "python.linting.pylintArgs": [
        "--load-plugins pylint-django"
    ]
}
```

**Comment by mpartipilo** [comment] 2017-10-18 14:58
Similar issue. Image here: https://github.com/Microsoft/vscode/issues/36322#issuecomment-337618385

**Comment by Tyriar** [comment] 2017-10-18 18:51
Using the [insiders build](https://code.visualstudio.com/insiders) I believe you can workaround this currently by setting:

```
"terminal.integrated.lineHeight": 1.1
```

**Comment by CoenraadS** [comment] 2017-10-31 10:05
@Tyriar 

This workaround doesn't work for me in latest insiders.

Running Ubuntu in virtualbox
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T06:24:27.011Z)
- OS Version: Linux x64 4.10.0-37-generic

![image](https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png)

**Comment by simon387** [comment] 2017-11-03 13:16
yeah, fixed on ```fedora26``` with the terminal.integrated.fontSize option

**Comment by DannyMexen** [comment] 2017-11-09 08:51
Ubuntu 17.10 here and `terminal.integrated.fontSize ` solved it. Thanks, everyone.

**Comment by suonto** [comment] 2017-11-22 14:53
Added `"window.zoomLevel": -0.001` for workaround on fedora26 VSCode 18.1

**Comment by apojomovsky** [comment] 2017-11-23 14:04
Thanks @suonto , it worked on my Ubuntu 16.04 VSCode 1.18.1 as well.

**Comment by mpartipilo** [comment] 2017-11-23 14:13
Confirmed @suonto's fix works on Debian Stretch VSCode 18.1. Also, it looks much better with `"terminal.integrated.lineHeight": 1.2`

**Comment by Jeyanthinath** [comment] 2017-12-06 18:48
Oops , This issue also came into stable build 
```
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
```

**Comment by eightbitraptor** [comment] 2017-12-07 12:27
Yup. This is broken for me:

```
[mattvh@hitomi] ~ % cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
[mattvh@hitomi] ~ % code --version
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```

Can confirm that adjusting terminal font size works as a workaround.

**Comment by kbumsik** [comment] 2017-12-07 15:18
I came from #38133. Underscores are missing in my terminal too.
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
$ code --version
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```

**Comment by mauvehed** [comment] 2017-12-09 15:39
Setting "terminal.integrated.fontSize" to 13 or 15 (default for me was 14) resolved the problem.

**Comment by Tyriar** [comment] 2017-12-11 11:19
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1138

**Comment by logannc** [comment] 2018-01-10 16:50
Changing fonts can also help. Using [Hack](https://github.com/source-foundry/Hack) which is very, very similar to the default fixed it for me.

**Comment by fabiuz** [comment] 2018-02-09 18:07
In the Visual Code Settings is:
"terminal.integrated.fontFamily" : ""
"terminal.integrated.fontSize" : "14"

// Controls the font family.
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",

// Controls the font size in pixels.
"editor.fontSize": 14,

If I use the default settings, the character _ is not displayed.
But, If I change the value of "terminal.integrated.fontSize" for a value diferent of 14, the character is displayed.

And, I noticed, other detail, if I not change "terminal.integrated.fontSize" but
"terminal.integrated.fontFamily" for other font, independently of value in "terminal.integrated.fontSize", is charactere _ is displayed.

**Comment by leejroberts** [comment] 2018-02-14 15:03
In Ubuntu 16.04, changing the terminal font family to a different Ubuntu font fixed the problem.
"terminal.integrated.fontFamily": "Ubuntu mono".

**Comment by sombriks** [comment] 2018-03-19 17:19
using "terminal.integrated.fontSize": 13 or "terminal.integrated.fontSize": 15 did the trick for me. only fontSize: 14 shows the problem. quite curious.

**Comment by rumpelsepp** [comment] 2018-03-19 17:26
Can confirm what @sombriks says.

**Comment by sombriks** [comment] 2018-03-19 17:39
also "terminal.integrated.fontFamily": "Courier" instead of font size solved the problem here.

**Comment by fabiuz** [comment] 2018-03-19 17:56
If I use the default settings, the character _ is not displayed.
But, If I change the value of "terminal.integrated.fontSize" for a value diferent of 14, the character is displayed.

And, I noticed, other detail, if I not change "terminal.integrated.fontSize" but
"terminal.integrated.fontFamily" for other font, independently of value in "terminal.integrated.fontSize", is charactere _ is displayed.

**Comment by certik** [comment] 2018-04-18 17:17
There are two ways to fix this in Ubuntu (I tested this on 16.04 and 17.10):

1. Put this into your settings:
   ```json
    "window.zoomLevel": -0.001,
   ```
   That seems to fix the problem with the original vscode font.

2. Put this into your settings:
   ```json
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.fontFamily": "Ubuntu mono",
   ```
   This will use the same font as in the gnome-terminal in Ubuntu, and the size will be the same as in the original vscode font, so if you are already used to the font size in the vscode terminal, it doesn't change. If you want the same size as in the Ubuntu gnome-terminal window, use size 18.

P.S. I posted this in https://github.com/Microsoft/vscode/issues/46900#issuecomment-377741221, but that issue is closed, and whenever I get on a new computer, I have to google how to fix this issue, so by posting here, it's easy to find the workaround for Ubuntu, until this gets fixed.

**Comment by caub** [comment] 2018-05-31 00:30
![2018-05-31-022537_816x79_scrot](https://user-images.githubusercontent.com/3134574/40754493-f6007ea4-6479-11e8-83de-1325581c225f.png)
with 
	"terminal.integrated.fontSize": 16,
	"terminal.integrated.fontFamily": "Ubuntu mono",
![2018-05-31-022859_800x59_scrot](https://user-images.githubusercontent.com/3134574/40754638-91ddb5bc-647a-11e8-8468-05109b491d8b.png)

**Comment by goodday2you** [comment] 2018-06-01 15:49
Thanks @leejroberts 
    "terminal.integrated.fontFamily": "Ubuntu mono",
    "terminal.integrated.fontSize": 16,

**Comment by hkiang01** [comment] 2018-07-06 14:33
This is also present in version 1.25.0 (Ubuntu 18.04).

**Comment by welkie** [comment] 2018-07-19 17:12
This issue is affecting me on 1.25.0 on Antergos.

All of the fixes mentioned here, including setting `window.zoomLevel` to `-0.001` and increasing line height were unable to fix it for me with my default fault. Only using other zoom levels with ctrl+ and ctrl- or changing fonts worked for me. My workaround was to change fonts to Courier family.

**Comment by sguillia** [comment] 2018-07-30 12:49
Is there going to be any fix for this ?

I think characters in the integrated terminal (eg. underscores) should be displayed without the user having to tweak the settings. A freshly installed VS Code should not suffer from this bug.

**Comment by fessmage** [comment] 2018-08-16 07:08
+1 vote for fix this problem once and for all.
I googled this thread for fix with every fresh install of VS Code.

**Comment by shivakumargn** [comment] 2018-09-02 06:56
The fix that worked best for me is `"window.zoomLevel": 0.001`
(+ or - non-zero value close to zero seems to work fine)

**Comment by IMBurbank** [comment] 2018-09-02 17:03
For those who can't get these font size/type solutions to work - make sure you check in a new terminal window. The changes won't be reflected in any currently open terminals.

**Comment by ryanQL** [comment] 2018-09-06 23:40
@suonto zoom level fix works! I'm using Fedora 28 and VSCode 1.27.1

**Comment by Tyriar** [comment] 2018-09-20 03:29
A temporary workaround was merged for Ubuntu that tweaks the font family/size if it's not set https://github.com/Microsoft/vscode/pull/56429

**Comment by machta** [comment] 2018-10-07 07:35
Another possible workaround (Mint 19 MATE) is changing the terminal rendered like this
```
"terminal.integrated.rendererType": "dom"
```

**Comment by Cerberooo** [comment] 2018-10-07 13:37
@matcha works for ArchLinux with GNOME3 too.

**Comment by praenubilus** [comment] 2018-10-08 23:06
Ununtu 18.04 with zsh, having the same problem.

**Comment by vladipus** [comment] 2018-10-18 10:50
Linux Mint 19. What an upsetting bug. That undescore invisibility just renders the terminal un-usable

**Comment by arufian** [comment] 2018-10-31 05:05
in my case, you just have to zoom in your screen with `[Shift] + [Cmd] + [;]`

**Comment by zaro** [comment] 2019-01-10 10:47
Happens for me also  on  Fedora 29 with vscode 1.30.2

**Comment by kylegmaxwell** [comment] 2019-01-22 18:32
Same here, also on Fedora 29 with vscode 1.30.2
@machta's solution worked for me, not sure what the drawbacks of that render mode are.

> ```
> "terminal.integrated.rendererType": "dom"
> ```

**Comment by welkie** [comment] 2019-01-22 18:42
@kylegmaxwell I remember a while back the devs switched from DOM to canvas for the integrated terminal. Their inspiration was speed. I believe this means switching back to DOM renderer type would fix the regression but be slower in some situations.

https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-how-the-terminal-is-rendered

**Comment by mmhelm** [comment] 2019-02-12 12:21
I fixed the issue by removing `'monospace'` from `editor.fontFamily` in `settings.json` (or Settings > Text Editor > Font > Font Family):
```
# Broken: "Hello_World!" -> "Hello World!"
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"

# Works: "Hello_World!" -> "Hello_World!"
"editor.fontFamily": "'Droid Sans Mono', monospace, 'Droid Sans Fallback'"
```

**Comment by fessmage** [comment] 2019-02-12 13:04
> I fixed the issue by removing `'monospace'` from `editor.fontFamily` in `settings.json` (or Settings > Text Editor > Font > Font Family)

I think this is a bad choise of possible workaround, because by disabling monospace fonts you will have broken pseudo-graphic user interface in various console utilities. 

You should really try to calculate working value of terminal.integrated.fontSize for your case.

**Comment by jhasse** [comment] 2019-02-12 19:46
@fessmage He only removed the 's

**Comment by mmhelm** [comment] 2019-02-12 20:57
@fessmage The broken config contains two `monospace` entries. One with quotation marks (`'monospace'`) and one without (`monospace`). I just removed the entry with quotation marks.

**Comment by fessmage** [comment] 2019-02-13 06:25
@mmhelm  Right, i see it now, sorry.

Also i discovered that in my case, on Ubuntu, i needed no more to declare this settings for correct terminal font:

```
"terminal.integrated.fontSize": 16,
"terminal.integrated.fontFamily": "Ubuntu mono",
```
 because after merging [this PR](https://github.com/Microsoft/vscode/pull/56429), vscode sets this automatically.

**Comment by MicMicMon** [comment] 2019-02-13 20:04
Using this setting solved the issue for me (fedora 29), whatever the integrated terminal font size:

    "terminal.integrated.fontFamily": "monospace"

**Comment by rumpelsepp** [comment] 2019-02-13 20:07
Can confirm this as well. Removing `'monospace'` (=with quotation marks) resolves the issue.

**Comment by deltacastro** [comment] 2019-02-15 15:57
Change the fontWeight works for me.

~~~~ 
"terminal.integrated.fontWeight":"600"
~~~~

**Comment by mikkancso** [comment] 2019-02-18 09:14
> Using this setting solved the issue for me (fedora 29), whatever the integrated terminal font size:
> 
> ```
> "terminal.integrated.fontFamily": "monospace"
> ```

This did not solve the issue for me. I'm also using Fedora 29.
I used to use the zoomlevel = 0.001 workaround, but that does not work either anymore...

**Comment by zaro** [comment] 2019-02-18 09:21
@mikkancso 
What did the trick for me on Fedora 29 was to set the font family to :

    "terminal.integrated.fontFamily": "Liberation Mono"

**Comment by deltacastro** [comment] 2019-02-18 15:51
@mikkancso 
Try with the font weight:

````
 "terminal.integrated.fontWeight": "600",
 "terminal.integrated.fontWeightBold": "600"
````

**Comment by BojanKomazec** [comment] 2019-04-10 14:09
> "terminal.integrated.fontFamily": "Liberation Mono"

Also works on Ubunty 18.04.

**Comment by terislos** [comment] 2019-04-23 15:22
Only add "window.zoomLevel": 0.001

> @Tyriar
> 
> La solución de la altura de la línea no funciona para mí en los últimos conocedores
> 
> Ejecutando Ubuntu en virtualbox
> 
> * Versión VSCode: Código - Insiders 1.18.0-insider ( [81cca6c](https://github.com/Microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5) , 2017-10-31T06: 24: 27.011Z)
> * Versión del SO: Linux x64 4.10.0-37-genérico
> 
> En mi captura de pantalla escribí algunos guiones bajos `_________`
> ![imagen](https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png)
> 
> También probé alturas locas como, `2`pero nada parece ayudar.
> 
> Esta es una regresión de 1.17 donde se muestra bien:
> ![imagen](https://user-images.githubusercontent.com/5593825/32218743-39ad2a70-be2c-11e7-8d87-1312afdd09d5.png)
> 
> El ajuste `terminal.integrated.fontSize": 13`es una solución para mí

**Comment by mrwillis** [comment] 2019-04-23 16:16
Font weight fixed it for me on Ubuntu 18.04

**Comment by psygo** [comment] 2019-05-29 14:41
Excuse me, but I disagree that these `fontWeight` and `fontSize` fixes and circumventions are reasons for closing this issue. It remains as being annoying and unpolished, now either I'm gonna have smaller characters or an overwhelmingly bright terminal. This is a *major visual bug* of VS Code and should be addressed as such.

**Comment by Tyriar** [comment] 2019-05-29 14:54
> Excuse me, but I disagree that these fontWeight and fontSize fixes and circumventions are reasons for closing this issue

The issue won't be closed until it's fixed.

**Comment by max-wittig** [comment] 2019-06-19 11:24
What's the status here? Kind of annoying that the terminal is unusable with the default font-size/height

**Comment by welkie** [comment] 2019-07-03 19:54
I've gotten used to this in the terminal since this issue was originally reported, but today I just noticed that it is affecting other aspects of VS Code as well like the renaming symbol interface. Demonstration:

![underscore_isse](https://user-images.githubusercontent.com/7719209/60621096-cfee1a80-9daa-11e9-8c4f-88144d565752.gif)

**Comment by Tyriar** [comment] 2019-07-03 20:48
@welkie I think that's this one https://github.com/microsoft/vscode/issues/46879, I suspect it's the same underlying cause that `_` in Linux fonts sometimes go out of their expected bounds at least when drawn in Chromium, the fix would look different though.

**Comment by Tyriar** [comment] 2019-07-03 20:53
@welkie please comment on https://github.com/microsoft/vscode/issues/46879 what OS/distro you're on and also whether or not the problem shows up in the intellisense completions as well like in the original post of that issue.

**Comment by welkie** [comment] 2019-07-04 15:00
@Tyriar Looks like I can't comment on #46879 because it's locked. If it's unlocked, I'll leave a detailed comment with all the relevant info.

**Comment by Tyriar** [comment] 2019-07-04 16:56
Unlocked, meant to when I reopened

**Comment by welkie** [comment] 2019-07-04 17:25
@Tyriar Left a detailed comment.

**Comment by nileshjain166** [comment] 2019-08-12 12:35
setting "terminal.integrated.fontSize" to 15 shows the underscore character for me.

**Comment by hugonasciutti** [comment] 2019-08-12 12:48
> setting "terminal.integrated.fontSize" to 15 shows the underscore character for me.

It does not make sense to show only in higher font size, we need to fix it. But good to know the value, it could help debug.

**Comment by pjfitzgerald** [comment] 2019-08-22 18:19
Any progress on this issue?

**Comment by terislos** [comment] 2019-08-23 14:50
> Any progress on this issue?

A none, continue the problem. :/

**Comment by dullroar** [comment] 2019-08-25 15:07
On Linux (Mint 19.2) installing the Inconsolata font and making it the first in the font list (and restarting VS Code) fixed the terminal window issue for me. I know that's not a "fix" but for those reading this thread who want a font "That Just Works" maybe that will help until it is fixed. FWIW, Linux Mint's editor, Xed, has had a similar issue - https://github.com/linuxmint/xed/issues/39.

**Comment by axi92** [comment] 2019-09-05 09:13
I have the same problem
Reproduce: echo "___" into terminal

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Linux x64 4.15.0-60-generic

**Comment by Nirusu** [comment] 2019-09-06 08:28
Same issue here on Ubuntu 18.04 and latest (1.38.0) Visual Studio code. "terminal.integrated.fontFamily": "monospace" provides a good workaround, but a fix would be very appreciated :/

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-60-generic

**Comment by kwahab** [comment] 2019-09-22 07:29
Simply setting terminal font to **Hack** on Kubuntu 18.04 fixed it for me. 
`"terminal.integrated.fontFamily": "Hack"`

**Comment by Remzi1993** [comment] 2019-09-24 14:34
When gets this fixed? It's a issue from 2 years ago already!
I don't understand why it's not a priority.

Setting: `terminal.integrated.fontSize` to 15 fixed the issue.
Maybe, make this font size the default? This could be an option.

**Comment by Kryptoxic** [comment] 2019-09-26 01:01
I work a lot in a linux environment compared to windows environment so when changing over from windows, I always get irritated that I cant see the underscores and I see that this has been going on for two years already. Commenting so I can follow this issue to see it fixed.

**Comment by howaboutsynergy** [comment] 2019-10-01 03:07
I'm not using vscode, but I'm seeing this issue on ArchLinux in both Chromium and Hexchat with certain font-sizes only, but not only with DejaVu Sans Mono (Book) but also with Noto Sans Mono  but way less visible. Tested for chars: `qpjy_`. With Nono the underscore is always visible, but other chars can be seen cut off a bit.

Inconsolata font however seems to exhibit no such issues. Hence why I'm switching my `Monospace` font to it. 
```
$ fc-match monospace
Inconsolata-Regular.ttf: "Inconsolata" "Regular"
```

This [here](https://phabricator.kde.org/D19283#423435) is an interesting read as to why this descenders cut off might be happening.

**Comment by bprosnitz** [comment] 2019-10-10 15:39
Setting font size to 13.9 (from the default of 14) fixed underscores for me.

**Comment by Tyriar** [comment] 2019-10-10 18:43
The current thing blocking this is stabilizing the WebGL renderer, see upstream query: https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Faddon%2Fwebgl

**Comment by suntaoTs** [comment] 2019-10-22 07:45
> @Tyriar
> 
> The line height workaround doesn't work for me in latest insiders
> 
> Running Ubuntu in virtualbox
> 
> * VSCode Version: Code - Insiders 1.18.0-insider ([81cca6c](https://github.com/microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5), 2017-10-31T06:24:27.011Z)
> * OS Version: Linux x64 4.10.0-37-generic
> 
> In my screenshot I typed some underscores `_________`
> ![image](https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png)
> 
> I also tried crazy heights like `2` but nothing seems to help
> 
> This is a regression from 1.17 where it displays fine:
> ![image](https://user-images.githubusercontent.com/5593825/32218743-39ad2a70-be2c-11e7-8d87-1312afdd09d5.png)
> 
> Setting `terminal.integrated.fontSize": 13` is a workaround for me

`fontSize: 13` and `fontSize: 15` all can solve this problem. just advise that the default Size not be 14, it will be solved.

**Comment by jbracer19** [comment] 2019-10-22 07:51
ok so wow, what happened
On Oct 22, 2019, at 2:47 AM, suntao <notifications@github.com> wrote:

﻿

@Tyriar<https://github.com/Tyriar>

The line height workaround doesn't work for me in latest insiders

Running Ubuntu in virtualbox

  *   VSCode Version: Code - Insiders 1.18.0-insider (81cca6c<https://github.com/microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5>, 2017-10-31T06:24:27.011Z)
  *   OS Version: Linux x64 4.10.0-37-generic

In my screenshot I typed some underscores _________
[image]<https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png>

I also tried crazy heights like 2 but nothing seems to help

This is a regression from 1.17 where it displays fine:
[image]<https://user-images.githubusercontent.com/5593825/32218743-39ad2a70-be2c-11e7-8d87-1312afdd09d5.png>

Setting terminal.integrated.fontSize": 13 is a workaround for me

fontSize: 13 and fontSize: 15 all can solve this problem. just advise that the default Size not be 14, it will be solved.

**Comment by jbracer19** [comment] 2019-10-22 07:59
want me to pwr up?  seemed everyone had a little fun with me so i just shut down for the night. But maybe it wasn’t ? i really would like to know, when i booted to another drive had multiple logins were erasing every drive so i shut back down


On Oct 22, 2019, at 2:53 AM, Rocket <notifications@github.com> wrote:

﻿ok so wow, what happened
On Oct 22, 2019, at 2:47 AM, suntao <notifications@github.com> wrote:

﻿

@Tyriar<https://github.com/Tyriar>

The line height workaround doesn't work for me in latest insiders

Running Ubuntu in virtualbox

* VSCode Version: Code - Insiders 1.18.0-insider (81cca6c<https://github.com/microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5>, 2017-10-31T06:24:27.011Z)
* OS Version: Linux x64 4.10.0-37-generic

In my screenshot I typed some underscores _________
[image]<https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png>

I also tried crazy heights like 2 but nothing seems to help

This is a regression from 1.17 where it displays fine:
[image]<https://user-images.githubusercontent.com/5593825/32218743-39ad2a70-be2c-11e7-8d87-1312afdd09d5.png>

Setting terminal.integrated.fontSize": 13 is a workaround for me

fontSize: 13 and fontSize: 15 all can solve this problem. just advise that the default Size not be 14, it will be solved.

**Comment by SurgeS** [comment] 2019-11-08 10:11
Underscores are finally visible with `fontSize: 14` and the latest 1.40 version :tada:

**Comment by viniciussp4** [comment] 2019-11-10 08:23
> @SurgeS 
> Underscores are finally visible with `fontSize: 14` and the latest 1.40 version

Still not working for me on: Ubuntu 18.04.3 LTS x64, VS Code 1.40

I have to use the workaround "terminal.integrated.fontSize": 15" in order to see the underscore.

**Comment by Bessonov** [comment] 2019-11-10 09:12
@viniciussp4 I use my docker image with ubuntu 18.04 for development and I see the underscores:
https://github.com/Bessonov/dev-image

Can you check your installation and vscode settings or the image?
https://github.com/Bessonov/dev-image/blob/master/Dockerfile#L28

I mean, if it's working in a reproducible way with docker, then it could be a local problem.

![image](https://brunocapuano.files.wordpress.com/2016/11/you-are-not-in-a-software-project-until-someone-says-it-works-on-my-machine.jpg?w=568)

**Comment by nobi1007** [comment] 2019-11-13 18:36
> @Tyriar
> 
> The line height workaround doesn't work for me in latest insiders
> 
> Running Ubuntu in virtualbox
> 
> * VSCode Version: Code - Insiders 1.18.0-insider ([81cca6c](https://github.com/microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5), 2017-10-31T06:24:27.011Z)
> * OS Version: Linux x64 4.10.0-37-generic
> 
> In my screenshot I typed some underscores `_________`
> ![image](https://user-images.githubusercontent.com/5593825/32218526-661786ba-be2b-11e7-837d-74ce740f92a8.png)
> 
> I also tried crazy heights like `2` but nothing seems to help
> 
> This is a regression from 1.17 where it displays fine:
> ![image](https://user-images.githubusercontent.com/5593825/32218743-39ad2a70-be2c-11e7-8d87-1312afdd09d5.png)
> 
> Setting `terminal.integrated.fontSize": 13` is a workaround for me

I don't get it but only the with font-size of 14 there comes the problem, but with other font sizes it not the case. Any reason ??

**Comment by segevfiner** [comment] 2019-11-13 18:42
It's an off by one error in measuring the "height" of the font that doesn't happen in all font sizes in the canvas renderer of xterm.js. If there is someway to fix up this computation then that would fix this for the canvas renderer. I think there was an issue in xterm.js where I explained my investigation of this.

**Comment by Tyriar** [comment] 2019-11-14 15:23
The issue is that rows are clipped so that we can render rows independently, otherwise the whole terminal would need an update. https://github.com/microsoft/vscode/pull/84440 fixes this and makes the terminal way faster so stay tuned 😃

**Closed** 2019-11-16 00:39 UTC
Labels: bug, integrated-terminal, upstream, upstream-issue-linked

**Comment by hems** [comment] 2019-12-05 13:13
I'm running OSX and I used to have "ProggyCleanTTSZ"  ( from the amazing https://proggyfonts.net/ ) and it worked like a charm.

One day i decided to accept the "Update" on VS Code and that terrible update started cropping my text on the terminal.

I played with all settings possible here in this thread and nothing worked other than changing my font to "monospace", which is less than ideal as i'm used to use ProggyClean for over 15 years now 😢 

I hope this get fixed before i move back to vim, which perhaps i should never have left, lol

**Comment by Tyriar** [comment] 2019-12-05 16:59
@hems that's a bug in Chromium that shows up on some fonts https://github.com/microsoft/vscode/issues/84432, https://bugs.chromium.org/p/chromium/issues/detail?id=1026254

**Comment by hems** [comment] 2019-12-06 11:02
> @hems that's a bug in Chromium that shows up on some fonts #84432, https://bugs.chromium.org/p/chromium/issues/detail?id=1026254

hopefully fixed soon

**Comment by Tyriar** [comment] 2019-12-06 17:31
You can try out the new WebGL-based renderer where this issue is fixed by using this:

```
"terminal.integrated.rendererType": "experimentalWebgl"
```

It's available in [Insiders](https://code.visualstudio.com/insiders/) and in the [upcoming version](https://github.com/microsoft/vscode/issues/85959).

The canvas renderer will eventually be removed as the webgl one is basically a highly optimized/low-level version of it.

**Comment by hems** [comment] 2019-12-16 12:49
> "terminal.integrated.rendererType": "experimentalWebgl"

that just gave me new problems, like my text is rendered out of the Terminal box sometimes and i can't see it. but if i type for instance `ls -la` then i can se the result because it spans many lines.

**Comment by Tyriar** [comment] 2019-12-27 17:23
@hems I haven't heard of a problem like that before, please report in a new issues with repro steps.

**Comment by Tyriar** [comment] 2020-11-04 19:08
If you're still on the canvas renderer, @hems calls out a workaround in https://github.com/microsoft/vscode/issues/107942#issue-713299633 to regenerate the font file:

> After months and months having the issue with my font being cropped on the bottom of the terminal i managed to solve the issue by importing the font into https://www.glyphrstudio.com/online/ then export it as OTF.
