### ISSUE TITLE
Thread / program do not get focused in the model when clicked in the view

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#18426] opened 2017-01-12 00:45 UTC
I would assume that if I pick a different debug target in the call stack, then type something in the console, it would send an evaluateRequest to the selected debug target. But when I press enter, the selection changes to the first target in the call stack, and the request is sent to the first target.

**Comment by isidorn** [comment] 2017-01-12 10:34
Can not repro.
Every expression I enter in the debug console is sent to the selected stack frame in the call stack.

Can you please provide repro steps or let me know what you are doing different thane me

![hmm](https://cloud.githubusercontent.com/assets/1926584/21886191/f5e1f520-d8ba-11e6-946a-164a742c1687.gif)

**Comment by roblourens** [comment] 2017-01-13 02:38
I guess the trick is, this happens when the focused target is not paused:

![jan-12-2017 18-35-32](https://cloud.githubusercontent.com/assets/323878/21916559/505917aa-d8f6-11e6-899d-8f307cdec0aa.gif)

**Comment by isidorn** [comment] 2017-01-19 15:40
Yes the issue is that currently we do not focus a thread or a process when those are clicked. We only focus when a stack frame gets clicked.
I agree this is not nice, especailly in your use case. Though does not feel critical -> debt week

**Comment by isidorn** [comment] 2017-12-12 09:12
Assigning to December
fyi @weinand

**Closed** 2018-01-03 11:47 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2018-01-03 11:49
I have changed how we handle selection changes in the call stack view.
Notice that a click on the thread or process should expand / collapse it. So if a thread / process is not focus it focuses the thread process and expands it. It will only collapse it if it is already focused. Just try it out and let me know how it works for you since I found this behavior quite ok and natural.

fyi @weinand the issues you were facing with your node cluster should be fixed now
