### ISSUE TITLE
No visual indication that git sync is happening

### ISSUE THREAD

**Issue by mikeschaefer** [Microsoft/vscode#24125] opened 2017-04-06 19:01 UTC
- VSCode Version: 1.11.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Commit changes to local git branch
2. Sync changes to origin, animation on bottom no longer spins the refresh icon.

**Comment by jsynowiec** [comment] 2017-04-06 20:50
Duplicate of #23975

**Closed** 2017-04-06 22:28 UTC
