### ISSUE TITLE
Test code doesn't seem to have inlay hints

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129565] opened 2021-07-27 16:30 UTC
Testing #129465

![image](https://user-images.githubusercontent.com/19672699/127191965-72112c71-bf53-499a-b5b0-b0d1c2d86077.png)

I think commands.executeCommand should have an inlay hint for the command. 

Actual code that repros this is here:
https://github.com/microsoft/vscode-jupyter/blob/main/src/test/datascience/notebook/interruptRestart.vscode.test.ts

**Comment by mjbvz** [comment] 2021-07-27 20:12
Seems to work for me with latest TS nightly:

![Screen Shot 2021-07-27 at 1 11 49 PM](https://user-images.githubusercontent.com/12821956/127220927-9287f909-6f05-4f13-9693-fd034cb782cb.png)


What TS version are you using? Are there any errors in VS Code the developer console?

**Comment by rchiodo** [comment] 2021-07-27 20:18
Might be similar to the other one I reported with the scrolling problem. The top of that file works, but as I scroll down they disappear.

**Comment by rchiodo** [comment] 2021-07-27 20:18
TS version
![image](https://user-images.githubusercontent.com/19672699/127221706-5a7f29c0-25d1-4a7d-869a-de5c2770edf7.png)

**Comment by rchiodo** [comment] 2021-07-27 20:49
There were errors in the developer console
[vscode-app-1627418916241.log](https://github.com/microsoft/vscode/files/6888667/vscode-app-1627418916241.log)

**Comment by mjbvz** [comment] 2021-07-27 21:14
Thanks for the logs! Based on the crash this is a duplicate of https://github.com/microsoft/TypeScript/issues/44960

**Closed by mjbvz** 2021-07-27 21:14 UTC
Labels: needs more info
