### ISSUE TITLE
Colors work in Output pane for logs, but not for extensions

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#66347] opened 2019-01-10 15:32 UTC
Info:
Version: 1.31.0-insider (user setup)
Commit: 344f4fa361e098b49aeace9602e89275fbbd17bf
Date: 2019-01-10T06:21:21.472Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

Issue:
Colored text output is supported for Logs in the Output tab of the lower pane, as seen below:
![image](https://user-images.githubusercontent.com/2294248/50978599-c69e8800-14c2-11e9-840e-468c6e50bd8f.png)
However, when an extension shows output that should be colored, it is not, and instead, the escape sequences are shown as plain text (making it extremely difficult to read):
![image](https://user-images.githubusercontent.com/2294248/50978695-f188dc00-14c2-11e9-9098-eb1ade47232f.png)

**Comment by RMacfarlane** [comment] 2019-01-10 17:54
Duplicate of https://github.com/Microsoft/vscode/issues/571

**Closed by RMacfarlane** 2019-01-10 17:54 UTC
Labels: output

**Comment by iansan5653** [comment] 2019-01-10 17:59
That was on the plan for November 2015 😞
