### ISSUE TITLE
Word wrap doesn't work in Git diffs

### ISSUE THREAD

**Issue by udarkness** [Microsoft/vscode#20533] opened 2017-02-13 08:52 UTC
Word wrap is quite useful features of VS Code in the documents.
However it is broken or not implemented in the git diff view.
This is specially useful here, since the text editor wide is divided by 2.

- VSCode Version: 1.9.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Edit a document with long lines
2. go to git ctrl+shift+g
3. Compare the document
4. You will see the horizontal scroll bar, and not wrapped text
5. Press Alt+z (no effect)

**Comment by jshall** [comment] 2017-02-13 17:21
`alt+z` and `editor.wordWrap` do not work at all for me in 1.9.0 and 1.9.1 _(see #20174)_, however when in diff mode I've never gotten any of the wrap settings to work (`editor.wrappingColumn`, `editor.wordWrap`, or `editor.wrappingIndent`).  I would like to see diff mode support all 3 of these settings.

Currently Using:
 - VS Code Version: 1.9.1
 - OS Version: Windows 7

**Comment by Bill-Stewart** [comment] 2017-02-14 19:55
In my opinion the behavior should be something like the following:

`wordWrap` | `wrappingColumn` | Effect
-----------|----------------------|------
`false`        | *any value*              | no wrapping at all
`true`        | <= 0                        | wrap at viewport
`true`        | > 0                          | wrap at specified column

If vscode adopts the behavior in this table, the defaults would be `editor.wordWrap: true` and `editor.wrappingColumn: 300`.

I find it non-intuitive and confusing that when `wordWrap` is `false` there is sometimes wrapping, and when `wordWrap` is `true` there is sometimes not wrapping.

**Comment by Bill-Stewart** [comment] 2017-02-15 16:54
Also, the following extension may be useful:

https://marketplace.visualstudio.com/items?itemName=BillStewart.set-wrapping-column

The purpose of the extension is to let you easily change the `wrappingColumn` setting without a need to edit the workspace or global `settings.json` file.

**Comment by alexandrudima** [comment] 2017-02-23 15:28
Duplicate of #11387

**Closed by alexandrudima** 2017-02-23 15:28 UTC
