### ISSUE TITLE
code uses all available ram memory and blocks computer

### ISSUE THREAD

**Issue by zeljkoantich** [microsoft/vscode#87326] opened 2019-12-19 08:59 UTC
- VSCode Version:  code --version
1.41.0
9579eda04fdb3a9bba2750f15193e5fafe16b959
x64

- OS Version:
System:    Host: ms Kernel: 4.15.0-54-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 

Steps to Reproduce:
Happens when I run ng serve. 

ng --version
Your global Angular CLI version (8.3.3) is greater than your local
version (8.1.0). The local Angular CLI version is used.

node --version 
v10.16.3

Does this issue occur when all extensions are disabled?: Not sure

code --list-extensions
Angular.ng-template
chrmarti.regex
dbaeumer.vscode-eslint
eamodio.gitlens
esbenp.prettier-vscode
ghaschel.vscode-angular-html
johnpapa.vscode-peacock
mhutchie.git-graph
ms-vscode.sublime-keybindings
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
quicktype.quicktype
rbbit.typescript-hero
streetsidesoftware.code-spell-checker
wayou.vscode-todo-highlight

**Comment by dbaeumer** [comment] 2019-12-19 09:17
@zeljkoantich can you please provide more information about why Code is involved into this. You say to reproduce run `ng serve`.

And can you please provide the information from Help > Open Process Explorer so that we can see what process might cause this?

**Comment by zeljkoantich** [comment] 2019-12-19 09:31
I was using VSCode, ng-serve and on a separate monitor I was monitoring system process.
So I was working and computer froze, then I saw that code process was listed on top of System Monitor, taking more than 5 GB of RAM. Unfortunately I don't have that screenshot.

I downgraded VSCode to previous version now, and will let you know if the problem reappears: 
code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64


![Screenshot from 2019-12-19 10-19-13](https://user-images.githubusercontent.com/34521192/71161120-10522f80-2249-11ea-8ac8-684ce97dcb1a.png)

**Comment by zeljkoantich** [comment] 2019-12-19 09:43
Also I was not using integrated terminal to run ng-serve, I was using terminator terminal emulator.

**Comment by dbaeumer** [comment] 2019-12-19 11:54
@zeljkoantich if you can reproduce it please provide the output from Help > Open Process Explorer. This helps us to identify the code process that causes this.

**Comment by zeljkoantich** [comment] 2019-12-21 11:28
I tried to repoduce but without any sucess. So I will close this issue.
I will reopen this issue if the problem reappears and If I can collect all necessary data.

**Comment by zeljkoantich** [comment] 2019-12-23 11:22
It happened again.
code --version
1.41.0-1576089540

[Full crash report](https://drive.google.com/open?id=10kvjKy5MPCJ6GlYEuiSMVlLtjTNEZPwi)

I have updated to version: 1.41.1-1576681836

**Comment by zeljkoantich** [comment] 2019-12-23 13:19
This time with code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64

Process ID 2630, electron_node tsserver.js


![IMG_20191223_135646](https://user-images.githubusercontent.com/34521192/71360079-e5d8dd00-258e-11ea-83b2-9c84c94e2539.jpg)
![IMG_20191223_135600](https://user-images.githubusercontent.com/34521192/71360081-e5d8dd00-258e-11ea-9de1-dbf5a884f7b8.jpg)

**Comment by dbaeumer** [comment] 2019-12-23 15:52
Looks more like a TypeScript problem.

**Comment by mjbvz** [comment] 2019-12-30 00:28
Almost certainly a duplicate of https://github.com/microsoft/vscode/issues/86707

**Closed by mjbvz** 2019-12-30 00:28 UTC
Labels: typescript
