### ISSUE TITLE
Syncing Across Devices For VSCode

### ISSUE THREAD

**Issue by Jackson5551** [microsoft/vscode#78439] opened 2019-08-03 22:14 UTC
So here is the Idea:  
Being able to use your Microsoft/Visual Studio account to sync: 

- settings
- custom snippets
- theme
- icon theme
- extensions
- etc.

across all VSCode installations natively.

Personally, I have VSCode installed on 3 different devices (Windows desktop, Linux Desktop, Windows Laptop) and I find it a hassle to install the same extensions multiple times, reconfigure settings, recreate custom snippets, etc. This feature would also be helpful if you get a new computer or reinstall an OS and you want an easy, fast way to setup VSCode the way you had it (I also had to do this at one point).

It would be really convenient to have this built in to the application and would benefit users like me who enjoy the product but want a little bit more ease of use.

Thanks for your time and the effort you guys have put in to make VSCode great!

**Comment by IllusionMH** [comment] 2019-08-03 23:09
There is great extension for this: [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

It also supports overrides per PC (e.g. different zoom level on PCs with different resolutions)

**Comment by Jackson5551** [comment] 2019-08-03 23:22
Thanks, I'll give it a go.
Would still like to see a native solution similar the the one in Visual Studio.

**Comment by gjsjohnmurray** [comment] 2019-08-05 08:18
Duplicate of #2743. If you want this I suggest you +1 that issue:

![image](https://user-images.githubusercontent.com/6726799/62449367-ed275780-b761-11e9-8369-309a098027d0.png)

**Closed** 2019-08-05 08:48 UTC
