### ISSUE TITLE
Breakpoints view should appear under debug's start view

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#90225] opened 2020-02-07 11:36 UTC
- In a project without a launch.json go to the debug view

Observe:
Debug view shows new start experience.

- create a breakpoint

Observe:
Breakpoints view appears above the start view.

![2020-02-07_12-31-48](https://user-images.githubusercontent.com/1898161/74026408-6f5d3680-49a6-11ea-8a3b-b6b5ed923efa.png)

We should show the breakpoints view in its default location (at the bottom).

**Comment by isidorn** [comment] 2020-02-07 12:30
I can not reproduce this. I tried also with a fresh user data directory. @weinand let me know if you have better steps, or if you can repro with a new user data dir.
Assigning also to @sandy081 as he might know when the view might not repsect its order. Since I clearly define that the start view has lower order than breakpoints view [here](https://github.com/microsoft/vscode/blob/0ebabc2b2c45726c9871c5c86f775fa26fa7c2b5/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L111)

Though @connor4312 was also seeing this

**Comment by sandy081** [comment] 2020-02-07 13:46
Also provide following info:

From the workspace where you are seeing this, 
- run the command `Developer: Log Storage Database Contents`
- It will log global and workspace storage contents in your developer tools console
- Provide the values for keys `workbench.view.debug.state.hidden` and `workbench.view.debug.state` from global and workspace storage respectively.

**Comment by weinand** [comment] 2020-02-07 14:50
When running VS Code with a fresh user-data-dir the problem disappeared.

From there I could easily reproduce the issue:
If you have moved the breakpoints view once to the top, the new position becomes a user setting. From then on every new project will show this behavior that the start view is no longer the top view.

This behavior seems to be perfectly correct.

However the behavior runs a bit contrary to the purpose of the new "Debug start view": to simplify debugging...

**Comment by isidorn** [comment] 2020-02-07 15:31
@sandy081 can I somehow have a special order that the view is always at the top? And that the user can not set anything before it?

**Comment by sandy081** [comment] 2020-02-10 09:53
Seems we need a fixed position view which is not supported yet. But shall we wait until users see this issue? Looks like this happened bcoz of trying some DnD of views?

**Comment by isidorn** [comment] 2020-02-10 10:03
I would like that we tackle this. However imho there is no rush and we do not have to do it this milestone.

**Comment by isidorn** [comment] 2020-04-07 09:42
@sandy081 I see this from time to time, can we maybe look into it once you find time?

**Comment by sandy081** [comment] 2020-04-08 15:29
Sure

**Comment by sandy081** [comment] 2020-04-27 16:56
Could not get time in this milestone. Moving to May

**Comment by sandy081** [comment] 2020-05-05 17:33
@isidorn Updated the order of welcome view to be the first view. It means that unless user moves  this view or other view to before this view, this view will be shown always first. 

This fixes what you asked for `can I somehow have a special order that the view is always at the top?`

I tried the steps provided by @weinand [here](https://github.com/microsoft/vscode/issues/90225#issuecomment-583423319) to repro and with this fix, the start view is still shown first always.

Steps I used to repro:

- Start with fresh user data directory
- Open VS Code with a folder that has `launch.json`
- Go to debug view and move `Breakpoints` view to the top
- Now open folder that does not has `launch.json`
- Go to debug view and make sure `Welcome` view is on the top
- Open a file and keep a break point
- Make sure the `Welcome` view is still on the top

> And that the user can not set anything before it?

Not sure if you still want to have this - to have a sticky view on the top?

**Comment by isidorn** [comment] 2020-05-06 06:05
Thanks Sandy, however I am not sure if that will fix it. Since the breakpoints view had order 40, and the welcome hard order 10. And now you changed wlecome to be order 1. Both 10 and 1 are lower than 40. So unless there is a special meaning to order == 1 than I am not sure how this would fix it.

I am fine if the user expliclity moves it that it gets moved, however this seems to happen without user explicitly re-arrenging views.

**Comment by isidorn** [comment] 2020-05-06 06:08
Though I tried to reproduce with latest and could not
@weinand can you repro this with latest from out of source?

**Comment by sandy081** [comment] 2020-05-06 06:29
>  I am not sure how this would fix it.

Previously debug views are registered in following order

- variables (10)
- welcome (10) - This was placed second because it is having same order but registered after variables
- watch (20)
- call stack (30)
- loaded scripts (35)
- break points (40)

By default, with above registration welcome view is always shown after variables view. When user moved break points view to top of variables view it took precedence over all views. Hence welcome view is shown after breakpoints view when they are visible. 

This can be fixed in two ways.

1. Register welcome view before registering variables view with same order. This might break anytime if somebody unknowingly moves the code.

2. Change the order of welcome view to be first by default. This is the fix I made and it is the right fix because you want that for welcome view. With this order of views are as follows:

- welcome (1)
- variables (10)
- watch (20)
- call stack (30)
- loaded scripts (35)
- break points (40)

Hence moving the break point to the position before variables view does not impact the position of the welcome view.

> can you repro this with latest from out of source?

You can repro with the steps I posted here -https://github.com/microsoft/vscode/issues/90225#issuecomment-624200062 without my fix 40f83c0.

I reproed it before my fix and with fix I can no longer repro it.

Since you are fine changing the order of welcome view if user explicitly moves it, I am closing this.

**Closed by sandy081** 2020-05-06 06:29 UTC
Labels: debug, feature-request, workbench-views

**Comment by weinand** [comment] 2020-06-04 10:42
Seems to work mostly fine for me now:
If I'm in an active debug session and I move the breakpoints view to the top, that setting becomes my default user setting.

But when opening a new empty project and go to the debug viewlet, the position of the breakpoints view is still below it (which is good).

The only way to force the original problem is to move the breakpoints view explicitly above the Welcome view. From then on every new project will show the breakpoints view above the Welcome view. But this does not happen by accident. It requires an explicit action by the user. So this behavior is fine and does not need some preventive measure on our side.
