### ISSUE TITLE
Typescript: Import suggestions in same line when index.ts is present

### ISSUE THREAD

**Issue by nazarkryp** [Microsoft/vscode#39029] opened 2017-11-23 12:04 UTC
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create project directory (e.g. models)
2. Create some classes in that folder
3. Create index.ts that exports those classes
4. Try to import those classes from other class by starting typing name of that type and then hit suggested name in the intellisense menu and hit enter

**Expected result:**
import { MyClass } from 'app/models';

**Actual result:**
import { MyClass } from 'app/models/myclass.ts';

This is really annoying when you have multiple classes in same folder and exported using index.ts
instead of having added them to single import (e.g import { MyClassFirstm MyClassSecond } from 'app/models';)  and imports each in separate line:
import { MyClassFirst } from 'app/models/myclass-first.ts';
import { MyClassSecond } from 'app/models/myclass-second.ts';

structure of index.ts
export { MyClassFirst  } from './myclass-first.ts';
export { MyClassSecond} from './myclass-second.ts';

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-11-30 02:07
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/19694

Please try using typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2017-11-30 02:07 UTC
Labels: typescript, upstream
