### ISSUE TITLE
Unable to delete text on the extension search box

### ISSUE THREAD

**Issue by ronaldstevanus** [Microsoft/vscode#71629] opened 2019-04-03 02:15 UTC
Issue Type: <b>Bug</b>

on mac, command + shif + x to show the extensions window and search for extension. Pressing backspace/delete will not delete the text.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv|-psn_0_630938|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3
Go|ms-|0.9.2
java|red|0.42.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2

</details>

**Comment by gjsjohnmurray** [comment] 2019-04-03 09:15
/confirmationPending

I wasn't able to reproduce this. Please re-test after launching with `--disable-extensions` argument. Maybe post a short animation of what you're seeing, or at least a static image.

**Comment by xujj25** [comment] 2019-04-08 01:51
I met similar situation. When I focus on searching input of extenstions, nothing happens to the text in the seaching input if I press the Backspace key, but pressing Delete key works well.

If I open a file in the editor and then try the above actions again, pressing Backspace can delete the characters in the opening file but not those in the searching input of extension!

My environment:

VSCode:
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

OS:
Ubuntu 16.04

**Comment by sandy081** [comment] 2019-04-08 08:37
Did you try disabling extensions?

**Comment by xujj25** [comment] 2019-04-08 08:51
@sandy081 Launching with `--disable-extensions` did help to avoid it. Do you mean that the problem may associated with specified extensions?

**Comment by ronaldstevanus** [comment] 2019-04-09 01:35
Sorry for late reply. The issue happens right after I update the vscode. After restarting the vscode, it works normally. I can't repro it anymore :(

**Comment by sandy081** [comment] 2019-04-11 16:21
Since it cannot be reproduced, closing it.

**Closed by sandy081** 2019-04-11 16:21 UTC
Labels: extensions, needs more info
