### ISSUE TITLE
Also enable collapsing from the closing part of a section

### ISSUE THREAD

**Issue by Mumeii** [microsoft/vscode#178217] opened 2023-03-24 11:15 UTC
Whenever I edit a .js file, I can only use the collapse buttons on the opening part of a section

![image](https://user-images.githubusercontent.com/17477935/227506579-f3adc490-408c-4bfd-adc4-0721e971c2c2.png)

... not its closing one : 

![image](https://user-images.githubusercontent.com/17477935/227507058-a5406ee4-9655-4949-a599-3ecccffe488d.png)

Been able to do so would be a time saver, especially whenever I'm working on test files that embed big chunks of mocking objects.

By big chunks I mean several hundreds of lines 😋

**Comment by aeschli** [comment] 2023-03-24 12:18
Duplicate of https://github.com/microsoft/vscode/issues/60670

**Closed by aeschli** 2023-03-24 12:18 UTC
