### ISSUE TITLE
html文件右键格式化问题

### ISSUE THREAD

**Issue by wangyongjie2017** [Microsoft/vscode#58584] opened 2018-09-13 07:53 UTC
Issue Type: <b>Bug</b>

##### html文件，在style中书写完css样式后，右键格式化后出现url链接中 "http:" 与 "//" 之间存在空格的问题。（Right-click formatting has a space problem）

[问题图片 (Screenshot)](http://gfs12.gomein.net.cn/T12fJbB7Cv1RCvBVdK.png)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|/Users/opg/Desktop/myTool/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
css-compressor|bes|0.0.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
html-slim-scss-css-class-completion|gen|1.1.1
vscode-gutter-preview|kis|0.14.1
vscode-simple-icons|Lau|1.8.6
vscode-language-pack-zh-hans|MS-|1.27.2
color-highlight|nau|2.3.0
open-html-in-browser|pea|0.0.3
LiveServer|rit|5.1.1
vscode-preview-server|yui|1.0.1

</details>

**Comment by aeschli** [comment] 2018-09-14 06:49
duplicate of #58578. The fix is in, will be in insiders next week.

**Closed by aeschli** 2018-09-14 06:49 UTC
