### ISSUE TITLE
Alt Tab + Reload Window with a webview makes me unable to open the command palette

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#102636] opened 2020-07-15 20:33 UTC
Issue Type: <b>Bug</b>

I believe this is caused by the experimental iframes flag as I cannot repro it without the flag.

1. Open up a webview and another vs code instance
2. Reload the webview then alt tab to the other vs code instance
3. Repeat this a few times
4. 🐛 Try to trigger the command palette via the keyboard shortcut, it won't let you.

VS Code version: Code - Insiders 1.48.0-insider (cb31fc6ce2b4da3520392b622aa3ebc5b313533b, 2020-07-15T05:34:49.078Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (24.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.7
vscode-pull-request-github|Git|0.18.1
js-debug-nightly|ms-|2020.7.1417

</details>

**Comment by mjbvz** [comment] 2021-02-27 03:46
Seems like a duplicate of #110276 from my investigation

**Closed by mjbvz** 2021-02-27 03:46 UTC
Labels: bug, electron, webview
