### ISSUE TITLE
regression: caret is rendered in wrong position when editor zoomed

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#26429] opened 2017-05-11 05:29 UTC
this is a regression. this did not happen in 11.1

- VSCode Version: 12.1
- OS Version: XUbuntu 16.04.2 LTS (lxde) 

Steps to Reproduce:
 - full-screen VS code
 - View->Reset Zoom
 - create a new file
 - type 100 characters on a single line (not enough to make it wrap)
 - move the caret to end of line
 - View->Zoom Out
 - type some more characters

NOTE: the caret is no longer rendered at the end of the line, and the new characters, while they appear at the end of the line, do not appear where the caret is.

 - View->Reset Zoom
 - View->Zoom In (5 times)

NOTE: different zoom levels affects the positioning error in different ways. zooming out tends to make the caret jump left & right more and more. zooming in yields a subtler error, but still makes it impossible to use as a text editor.

**Comment by Spongman** [comment] 2017-05-11 05:36
![image](https://cloud.githubusercontent.com/assets/1088194/25934177/258f0cd6-35d1-11e7-824b-2dfabb31e3cc.png)

**Comment by alexandrudima** [comment] 2017-05-11 06:47
Duplicate of #26151 

Workarounds until the fix is released:
* change the zoom level, then **close and start again** VS Code
* or use the setting `"editor.disableMonospaceOptimizations": true`

**Closed by alexandrudima** 2017-05-11 06:47 UTC
