### ISSUE TITLE
JavaScript IntelliSense for type annotation of "object" with generics

### ISSUE THREAD

**Issue by yule-cao** [microsoft/vscode#109571] opened 2020-10-28 09:03 UTC
Issue Type: <b>Bug</b>

JavaScript IntelliSense does not work for type annotation of "object" with generics, e.g., "object<string, number>". It treats the variable as "any" only.

But if we annotate the type with "Object<string, number>", it works well.

Should it work for both "object" and "Object"?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-131-generic
Remote OS version: Linux x64 4.4.0-131-generic

**Comment by IllusionMH** [comment] 2020-10-28 11:34
/duplicate of https://github.com/microsoft/TypeScript/issues/36872
`Object` and `object` aren't not equivalent and `object<string, number>` isn't parsed well by TS (can be visible in TS playground)

See https://github.com/microsoft/TypeScript/issues/36872#issuecomment-588196234 for workaround

**Closed** 2020-10-28 11:35 UTC
Labels: *duplicate
