### ISSUE TITLE
High CPU usage when opening certain folders

### ISSUE THREAD

**Issue by dmlemos** [microsoft/vscode#30848] opened 2017-07-17 10:32 UTC
- VSCode Version: 1.14.1
- OS Version: 10.12.5

Reproduces without extensions: Yes

## Steps to Reproduce:
1. `$ cd ~` (not sure you are able to reproduce in yours)
2. `$ code .`

**CPU goes sky high**
```
% CPU
167.8 12.1  5206772 2029252   ??  RN   11:20am   6:48.62 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService

101.2  7.5  4795848 1255188   ??  R    11:20am   5:42.60 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
```

When I close the window, I notice one of processes remain alive:
```
% CPU
102.0  7.5  4804052 1255220   ??  R    11:20am   8:38.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
```

After killing the remaining process, `find` kicks in:
```
% CPU
100.0  0.0  2497332   4280   ??  R    11:20am   1:06.23 find -L . -not ( ( -name node_modules -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store ) -prune ) -type f
```
**Note:** Up until this point, this process was there but not consuming CPU at all.

Usually `find` goes away by itself.

**Comment by chrmarti** [comment] 2017-07-17 14:53
Sounds like the search service got stuck and `find` might be waiting on its stdout that is blocked because of that.

**Comment by chrmarti** [comment] 2017-07-17 16:11
@dmlemos What is the output of `time (find -L ~ -not \( \( -name node_modules -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store \) -prune \) -type f | wc -l)`?

**Comment by dmlemos** [comment] 2017-07-17 18:51
@chrmarti 

$ time (find -L ~ -not \( \( -name node_modules -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store \) -prune \) -type f | wc -l)
 8011384

real    1m33.255s
user    0m14.436s
sys     1m16.833s

PS: I can reproduce this issue every time.

**Comment by chrmarti** [comment] 2017-07-17 18:54
When it reproduces, could you check if there are any errors in the dev console? (Help > Toggle Developer Tools)

**Comment by dmlemos** [comment] 2017-07-18 12:23
Yes! I cleared the console log beforehand

```
/Users/REDACTED/.vscode/extensions/dlech.chmod-1.0.0]: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
Sorry, but currently only the 'navigation' group of the 'editor/title' menu supports alt-commands
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Overwriting extension <<.erb>> to now point to mime <<text/x-erb>>
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Overwriting extension <<.rhtml>> to now point to mime <<text/x-erb>>
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "Class definition with initialize"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "Class definition"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "for loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "if"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "if else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "if elsif"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "if elsif else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "Module definition"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "unless"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "until loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "while loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "method definition"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "if"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "elsif"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "ife"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "unless"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "unlesse"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [/Users/REDACTED/.vscode/extensions/rebornix.ruby-0.12.1]: The "each"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
```

**Comment by chrmarti** [comment] 2017-07-18 14:08
There are many Code Helper processes only the command arguments tell us which part of the system it is. This is almost certainly the search engine like you initially reported.

**Comment by dmlemos** [comment] 2017-07-18 14:12
Let me know if I there is anything else that would help troubleshooting it

**Comment by timothysc** [comment] 2017-10-03 00:43
I have a strage condition which sound's kind of similar, where I get 100's of forked: 

``` 
find -L . -not ( ( -name node_modules -o -name .git -o -name .git -o -name .svn -o -name .hg -o -name CVS -o -name .DS_Store ) -prune ) -type f
``` 

I don't know if this is related or not.

**Comment by chrmarti** [comment] 2017-10-03 14:03
We have a few fixes / changes in this area in the upcoming release. You can give these a try with our insiders build (https://code.visualstudio.com/insiders/) that is currently very close to what will be in the release. If you do, let us know if that improves things.

**Comment by Alonski** [comment] 2017-10-04 06:05
I am also having an issue with searchService causing 100% CPU.
After hanging my computer for a 5-10 seconds VSCode asks me if I want to reload the window.
Doesn't help after reloading it.

I just end up killing the searchService every time it does it. Helps for a few minutes at least

**Closed** 2019-10-08 22:51 UTC
Labels: *out-of-scope, bug, search
