### ISSUE TITLE
Native Notebooks - Latex rendered strangely

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129900] opened 2021-07-31 18:17 UTC
- VS Code Version: 1.58.2
- OS Version: Windows

Steps to Reproduce:

1. Open notebook
2. Run `$ \ne $` in markdown cell 

Expected Output: 
![image](https://user-images.githubusercontent.com/19276747/127749018-f311f882-bf3f-4a61-b7bd-417d294a947a.png)

Actual Output: 
![image](https://user-images.githubusercontent.com/19276747/127749042-011b939f-b79a-4cd6-a26b-aaae125b5e98.png)

**Comment by mjbvz** [comment] 2021-08-04 04:50
Duplicate of #128490

Should be fixed in the first 1.60 insiders builds

**Closed by mjbvz** 2021-08-04 04:50 UTC
Labels: notebook, notebook-markdown
