### ISSUE TITLE
Sticky Scroll for Tree Views

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#167782] opened 2022-11-30 22:46 UTC
With some workspaces with a lot nested folders, it might be nice to have some type of sticky scroll to show the parent directories that are above the view area.

![image](https://user-images.githubusercontent.com/31675041/204924062-2506dc1f-48b0-48ce-85c2-fa8ad065944d.png)

For example, just upon glance, I'm not sure where I am in the file explorer but I just know I'm pretty nested in 😅. It'd be useful to have some type of fixed header that shows parent directories (approx where I have arrows in the pic). 

It gets more useful if you have a lot of identically named folders/files that are in different parts of the workspace. I think this would also help with the tree view elsewhere, like in the search tree.

**Comment by karlhorky** [comment] 2022-12-08 09:30
Just came here to file the same issue. This is also commonly an issue when deep diving somewhere in `node_modules`, maybe additionally inside one of the `packages/*` directories in a monorepo:

<img width="232" alt="Screenshot 2022-12-08 at 10 28 07" src="https://user-images.githubusercontent.com/1935696/206409908-467fe12f-5cae-4c01-acd6-d896a257bda1.png">

Usually means lots of scrolling!

**Comment by joaomoreno** [comment] 2022-12-08 13:35
Duplicate of #161207

**Closed by joaomoreno** 2022-12-08 13:35 UTC
Labels: feature-request, tree-widget
