### ISSUE TITLE
ubuntu: copy text freezes vscode

### ISSUE THREAD

**Issue by adams-sarah** [Microsoft/vscode#24546] opened 2017-04-11 19:20 UTC
- VSCode Version: 1.11.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Select text
2. Copy

VSCode completely freezes. Cannot recover.

**Comment by alexandrudima** [comment] 2017-04-12 08:47
@adams-sarah I could not reproduce in Ubuntu 16.04 LTS.

Does VSCode freeze when:
* copying out of a plain text file?
* copying out of an input box (like the find widget input)

Can you reproduce this with `code --disable-extensions` ?

**Comment by adams-sarah** [comment] 2017-04-13 17:13
I actually can't repro at all anymore. Not sure what happened between two days ago and today.
I was able to repro 5+ times on Tuesday.

I'll ping back if/when it happens again.

**Comment by varkenvarken** [comment] 2017-04-27 08:38
Still here I'm afraid: Ubuntu 15.04, vscode 1.11.2.

1. select anything (in a python file, a plain text file or a .json file)
2. ctrl-c

it freezes, after a few seconds it prompts to reopen the window but if you choose that you get an empty window)

**Comment by alexandrudima** [comment] 2017-04-27 12:49
@varkenvarken Are you able to copy out of a different input in VS Code. e.g. from the find widget input via `ctrl+c` or is this problem reproducing only when copying from an editor ?

![image](https://cloud.githubusercontent.com/assets/5047891/25484062/a3e5dd22-2b58-11e7-8138-79b9e3a04263.png)

**Comment by varkenvarken** [comment] 2017-04-27 15:11
I will check if it is happenign again, but it is not consistently reproducible :-( For the last couple of hours  it is working again as expected ... I have no idea what was changed (i did not update any part of the software or ubuntu). I did notice that thunar (the Ubuntu file manager that I use) was hanging as well and I did kill that one. So I might just be that it is a Ubuntu/xfce/thunar issue.

**Comment by alexandrudima** [comment] 2017-04-27 18:31
Since this appears to failing intermittently without any changes in VS Code, I suggest we close this issue for now, as this might be a problem with the environment / OS. Please keep an eye open and if you spot any causation/correlation I'm happy to try to investigate further.

**Closed by alexandrudima** 2017-04-27 18:31 UTC
Labels: needs more info

**Comment by narf** [comment] 2017-07-31 08:27
Same here (Arch linux), vscode freeze when copying anything, anywhere (impute or text editor).

I tried on the browser and the browser freezed too. ctrl+v or ctrl+x is the same.
Last operation I did that I don't do everytime is ctrl + click on a link inside vscode window.

Did vscode mess up my clipboard ?

**Comment by narf** [comment] 2017-07-31 08:37
Ok, I was able to reproduce it, somewhat...
* ctrl+click on vscode -> a page open in konqueror
* change url with a search like 'vscode freeze' -> konqueror show an error
* Copy what is in the url and paste it in chromium
* Now try to copy something, it will freeze...

Btw, restarting the computer fix it.
