### ISSUE TITLE
word wrap in *.vue's <style> long rule

### ISSUE THREAD

**Issue by shepelevstas** [Microsoft/vscode#59698] opened 2018-09-30 17:55 UTC
Issue Type: <b>Bug</b>

Word wrap work great and horizontal scrollbar never apears. One exception: a long line in a css rule inside <style> tag in .vue file. Horizontal scrollbar apears and takes about 95%. Words are wrapped but wrapping width is wider than the editor width.

Don't know if it matters: UI in my windows 8.1 is scaled 150%.

In .vue file in <style> section I have a rule:
```
.someclass {
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
}
```
and half the times it's wrapped it makes horizontal scrollbar appear and some last letters are covered by minimap

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3403)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.12.0
vscode-sqlite|ale|0.3.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.6
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
theme-macos-classic|hua|1.1.1
output-colorizer|IBM|0.1.2
python|ms-|2018.8.0
vetur|oct|0.12.7
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
dumb-copy-paste|she|1.0.0

(12 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2018-10-02 08:55
@shepelevstas Can you add a screenshot?

**Comment by shepelevstas** [comment] 2018-10-04 05:27
![untitled](https://user-images.githubusercontent.com/14919836/46454456-6962ae80-c7d0-11e8-8156-90aa36837925.png)

**Comment by shepelevstas** [comment] 2018-10-04 05:30
maybe it's caused by 3 added colorpicker squares in one row?

**Comment by shepelevstas** [comment] 2018-10-04 05:38
It really is the colorpickers! Turning off color decorators fixed it, but now I don't have color decorators :))
![untitled2](https://user-images.githubusercontent.com/14919836/46454778-1ee23180-c7d2-11e8-9ad6-3b9be515d0a1.png)

**Comment by alexandrudima** [comment] 2018-10-08 09:47
Duplicate of #32856

**Closed by alexandrudima** 2018-10-08 09:47 UTC
Labels: editor, editor-wrapping
