### ISSUE TITLE
Webview panel does not remove on dispose()

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode#82376] opened 2019-10-11 15:50 UTC
I see that a bug has not been fixed yet. See https://github.com/microsoft/vscode/issues/58360

- VSCode Version: 1.39.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open empty window
2. Add 1st folder to a workspace
3. Add 2nd folder to a workspace 
4. Open WebView, keep its instance and close when any folder is removed from workspace 
```
    this.subscriptions.push(
      vscode.workspace.onDidChangeWorkspaceFolders(this.disposePanel.bind(this))
    );
```

See full code to reproduce https://github.com/platformio/platformio-vscode-ide/blob/develop/src/home.js

We have a lot of reports, every time I close them and ask users to open an issue here. See the latest https://github.com/platformio/platformio-vscode-ide/issues/1048

P.S: I did another research and added debugging here https://github.com/platformio/platformio-vscode-ide/blob/develop/src/home.js#L138:L145

The code calls, but tab does not remove.

Do we have any API in VScode to list opened tabs and close them based on their type/title?

**Comment by vikene** [comment] 2019-10-11 17:11
@mjbvz Can I take up and work on this issue ?

**Comment by mjbvz** [comment] 2019-10-12 06:19
@vikene Sure. Here's the place where dispose is called in main VS Code:

https://github.com/microsoft/vscode/blob/9c3d060aff84aad04f0bf86500dd8b8a50851da6/src/vs/workbench/api/browser/mainThreadWebview.ts#L145

You likely need to also close the editor as well. Here's the function that should be able to do that:

https://github.com/microsoft/vscode/blob/dedf0de944fae56f0bf748913cbc1b2cc24987d2/src/vs/workbench/services/editor/common/editorGroupsService.ts#L503

**Comment by vikene** [comment] 2019-10-14 08:02
@ivankravets I am able to verify the issue, yep something interesting happens when folders are being added. 

I find there is an inconsistency on number of times vs code reloads the extensions,

For example,
- No folder in workspace & first time when a folder gets added - extensions get reloaded
- Add second folder, extensions get reloaded  
- But third folder - nothing happens no extension reload is happening 

but not even once **deactivate** function is being called as a part of extension lifecycle. 

Due to this, when multiple **activate** function of extension is getting called **panel.dispose()** looses context and has the latest object that just got binded to it, resulting in dangling webViews which has to be manually closed and the extension has no control over it. 

I have two possible ways to fix this
1. Extension going through open tabs & checking if it was instantiated by the extension, then deactivating that tab. 
2. Fix deactivate function call in vs-code so lifecycle of the extension gets terminated before another activate on the same extension gets called.

@mjbvz - it would be great, if you can suggest me a path to follow. Or give me any inputs that you feel is  necessary to add to the solution.

**Comment by ivankravets** [comment] 2019-10-14 08:36
> extensions get reloaded

Yes, this is crazy behavior. Every time when VSCode kills us (extension), we stop our PIO Home server, after adding new folder we start it again (it requires CPU resources and time). What is interesting, there is no extra info when VSCode deactivates us: user closes VSCode, or something else.

@mjbvz do you know why VSCode kills all extensions when adding a new folder to a workspace?

**Comment by mjbvz** [comment] 2019-10-21 21:02
See #69335

**Comment by mjbvz** [comment] 2019-10-21 21:07
Duplicate of #70656

**Closed by mjbvz** 2019-10-21 21:07 UTC
Labels: help wanted
