### ISSUE TITLE
Copy/Cut then Paste doesn't preserve or fix indentation

### ISSUE THREAD

**Issue by Sokol-ua** [Microsoft/vscode#6392] opened 2016-05-16 08:41 UTC
- VSCode Version: 1.1.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:
1. Copy some divs code in html (with any method "Ctrl + C || Right Click")
2. Then paste inside other divs

Always have to fix intentation after pasting some code.

Experiencing the same behaviour for css and js.

**Comment by wxkin** [comment] 2016-05-16 17:33
Have you tried to copy/paste it from/at the start of the line?
![div_html](https://cloud.githubusercontent.com/assets/10991163/15297882/c881e2ce-1b9c-11e6-8fd5-14a26cd992b5.gif)

**Comment by Sokolua** [comment] 2016-05-17 11:42
@wxkin I think it would be inconvenient to always target beggining of the line as you add new, hitting the "enter".

**Comment by alexandrudima** [comment] 2016-05-23 19:57
This sounds like you would want some sort of format on paste.

**Comment by Instagit** [comment] 2016-09-15 15:29
Having to fix the indentation characters after copy/pasting is really annoying. Other editors don't have this problem.

>This sounds like you would want some sort of format on paste.

Applying the file's current indentation format to pasted contents would be great.

**Comment by alanwei0** [comment] 2016-09-26 07:48
i need this feature too, just like the "paste and indent" function in sublime with `ctrl + cmd + v`

**Comment by rubymaniac** [comment] 2016-10-13 18:19
This is a very basic feature to have. Is there any specific reason this hasn't been implemented yet?

**Comment by alexandrudima** [comment] 2016-10-24 17:25
@rubymaniac The indentation rules we have at our disposal are fuzzy and there are a plethora of languages where they're incorrectly defined. e.g.
```js
if (true)
    return 5; // <-- you probably would like this line to be indented

switch (a) {
    case 5:
        return 5; // <- same here
     default:
        return 6; // <- same here
}
```

You will find that these cases do not work correctly in vscode today when pressing Enter and there are probably many languages besides js that have this problem.

Now imagine pasting in proper indented code and the editor indenting it in a wrong way. You would be much more upset than the lack of the auto-indent. That's why I try to take the discussion towards format on paste, as formatting is something that can be provided by a language server, and is not language agnostic (like the indentation rules).

**Comment by rubymaniac** [comment] 2016-10-25 08:34
@alexandrudima yes I completely agree with what you say about the fuzziness of the indentation rules. However I usually find myself to copy correctly indented code from one place to another with a different offset and VSCode is not adjusting the indentation to the new offset and I always have to do this manually. 

For that reason I made a [little extension](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent) that tries to adjust the offset of the indentation to where the cursor is when you are pasting code.

**Comment by alexandrudima** [comment] 2016-10-25 08:41
Aha, so you would expect that the pasted code is treated as one blob and indented/unindented as a single blob (all lines the same amount). Makes sense to me.

That would reduce the risk of messing it up, although we'd still need to do per-line adjustments (i.e. detect that the pasted code is indented with spaces@2 meanwhile the file is indented with tabs, etc.).

**Comment by rubymaniac** [comment] 2016-10-25 20:13
@alexandrudima Exactly what I am saying. The per-line adjustments are crucial in order to do it properly. For what it's worth in the extension I wrote I am making per-line adjustments.

Although the problem is solved (at most cases) through the extension, I feel that this should be native functionality (or at least configurable through preferences).

**Comment by MacKentoch** [comment] 2017-01-17 06:24
No news?

It is a **core functionality** to be able to copy/paste *without indentation surprises*.

VSCode is awesome but I may go back Atom just because of that. 
I loose time fixing indentation after a copy/paste...

**Comment by alexandrudima** [comment] 2017-01-21 13:39
@rebornix Has just implemented `editor.formatOnPaste`, so if you are in a language that supports format, the format will be invoked on the pasted content.

**Comment by martin-wiseweb** [comment] 2017-02-22 16:02
@alexandrudima To be honest, `editor.formatOnPaste` is not a good replacement for the requested functionality. I'll try to provide some examples as I see them, but I had to turn it off because it was ruining much of my code.

**Comment by adrientetar** [comment] 2017-04-22 09:34
I'm using Python and I turned on formatOnPaste but that runs autopep8 and I don't want my code wrapped, just indented to fix the paste location. [That's a thing I miss since switching over from Atom.]

**Comment by ZeroVa** [comment] 2017-06-04 12:33
last night i dreamt that this worked

**Comment by hustcer** [comment] 2017-06-04 13:21
@ZeroVa You really have a sweet dream. 😆

**Comment by MatrixV01** [comment] 2017-06-05 19:24
This is another really seemingly minor thing that should just work in VS Code. May also revert to Atom. Death by a 1000 paper cuts with VS Code as much as I want to like it.

**Comment by rebornix** [comment] 2017-06-26 18:37
Already added this feature in Insider.

**Closed by rebornix** 2017-06-26 18:37 UTC
Labels: editor, editor-indentation, feature-request

**Comment by Skura23** [comment] 2017-07-31 09:41
I find a extension might do this trick:
[pase-and-indent extension](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent)
I changed **ctrl+shift+v** of its example configure binds into **alt+z**, and **alt+z** works.

**Comment by neerolyte** [comment] 2017-09-12 00:48
Should pasting without horrible indentation be working in `1.16.0` ?

**Comment by ejochens** [comment] 2017-09-21 01:48
I found that hitting CTRL-Z (undo) after CTRL-V (paste) fixes the indentation.  Faster to fix, but what extra step is taking place that the CTRL-Z has to undo it?  The auto-indent?

**Comment by neerolyte** [comment] 2017-09-21 03:27
@ejochens Nice, that does work.

I logged #34424 as I'm guessing this issue wont' be responded to (despite being broken) because it's closed.

**Comment by zigang93** [comment] 2017-10-12 07:57
need cmd + Z to fix the indentation too.. any update for this bug?

**Comment by zaclem01** [comment] 2017-10-13 12:08
Just to drop in my experience, the indention will very occasionally work correctly on paste, but for the most part, I have to use `CTRL + Z` to get it to the correct level. It seems like it is doing some kind of two step process. I've disabled all my formatting and beautify extensions as well, so it appears to be native.

**Comment by Arnique** [comment] 2017-10-13 13:48
CTRL + Z works like magic! This particular bug, although minor, can drive you mad if you work with lots of Html code. In fact I've been fighting with this bug for 2 months and couldn't take it any longer! TBH I don't know how other front end devs cope with this vcode peculiarity. Anyway, I'm just glad I landed here coz I've finally found a temporary fix. 

Loving the progress of vscode in 2017 though, so even if minor issues like this still exist, I say to you, "Keep up the good work!"

**Comment by coder77** [comment] 2017-10-23 19:38
@rebornix 
Added it in insider? how about my 1.17.2? 
Please... I am **all-visual-studio** fans.

**Comment by taalas** [comment] 2017-10-27 09:38
Still not sure what is happening tbh.

When pasting HTML code indentation is almost always incorrect. CTRL-Z fixes this. What is doing the additional step when pasting?

In regards to the new parameter "editor.formatOnPaste": Should it be true (because it needs a third formatting step) or should it be false (because the mysterious second step will be skipped)?

**Comment by jlock64** [comment] 2017-10-27 15:11
What worked for me was downloading the extension "Paste and Indent" and once enabled going to my "user settings" ( shortcut CTRL + , ) and pasting in "pasteAndIndent.selectAfter": true into your custom settings.

Hope that helps. This was driving me nuts

![vscode custom settings](https://user-images.githubusercontent.com/16665681/32111091-8025b094-bb07-11e7-9b54-cfbf0c3f8877.jpg)

**Comment by ericis** [comment] 2017-10-31 20:29
I get this in Typescript, which I thought VSCode focused on as a primary language. An issue since May 16, 2016? Yikes... (people still commenting with this as an issue and it's closed?)

VSCode v1.17.2
Windows 10 Pro

**.editorconfig**
```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

**./.vscode/settings.json**
```
{
    "files.eol": "\n"
}
```

**Comment by yveslange** [comment] 2017-11-15 12:08
Installing `pasteAndIndent` and adding `"pasteAndIndent.selectAfter": true` to the config worked
