### ISSUE TITLE
webviews should have real view column after they are created

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#140837] opened 2022-01-17 06:54 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150412&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=390

```
1) vscode API - webview
       webviews should have real view column after they are created, #56097:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

```

**Comment by mjbvz** [comment] 2022-08-04 21:29
Duplicate of #153066

**Closed by mjbvz** 2022-08-04 21:29 UTC
Labels: integration-test-failure
