### ISSUE TITLE
Cannot revert deleted directory

### ISSUE THREAD

**Issue by Son0fAnton** [microsoft/vscode#131236] opened 2021-08-20 06:39 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Kali Linux 2021.2

**Comment by JacksonKearl** [comment] 2021-08-23 20:33
Duplicate of https://github.com/microsoft/vscode/issues/111022

**Closed by JacksonKearl** 2021-08-23 20:33 UTC
