### ISSUE TITLE
Incorrect highlighter for HTML comments - add and even number of slashes   

### ISSUE THREAD

**Issue by vdizdarevic** [Microsoft/vscode#41399] opened 2018-01-10 13:58 UTC
Example that simple shows highlighter problem:

### <div>
        <div>
        
        <div>
        </div>
        

          
        <div>
        </div>
        

        

        </div>
</div>

Add number of slashes in closing part makes highlighter problem.

**Comment by aeschli** [comment] 2018-01-10 15:59
Duplicate of https://github.com/Microsoft/vscode/issues/33944

**Closed by aeschli** 2018-01-10 15:59 UTC
