### ISSUE TITLE
syntax highlight broken.

### ISSUE THREAD

**Issue by nurmohammed840** [microsoft/vscode#92410] opened 2020-03-11 00:17 UTC
- VSCode Version: 1.43.0
- OS Version: Windows_NT x64 10.0.18363

Vscode( 1.43.0 ) omit "textmate scopes" and syntax highlight not working.

**Comment by rebornix** [comment] 2020-03-11 01:34
@nurmohammed840 can you confirm if its a duplicate of #92308

**Comment by aeschli** [comment] 2020-03-11 20:28
Duplicate of #92308.

**Closed by aeschli** 2020-03-11 20:28 UTC
Labels: needs more info, new release, semantic-tokens, typescript
