### ISSUE TITLE
Resuming edit sessions took almost a minute

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161941] opened 2022-09-27 10:10 UTC
Testing #161860

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/10746682/192498685-3b444c9f-f1bf-41ba-a456-14805c5452be.png">

**Comment by joyceerhl** [comment] 2022-10-24 21:56
Optimistically closing this as caused by latency issues which have been resolved by Lad's and Daniel's work on the service.

**Closed by joyceerhl** 2022-10-24 21:56 UTC
Labels: perf
