### ISSUE TITLE
Settings Sync Dialog continuously showing

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#95374] opened 2020-04-15 18:56 UTC
Issue Type: <b>Bug</b>

This dialog keeps popping up. I do not want to turn on settings sync. I did login to my Microsoft account in order to get rid of the "1" badge on the gear icon that would not go away. 

![image](https://user-images.githubusercontent.com/13488/79377033-13280d00-7f29-11ea-85a2-e16c921d75f1.png)

Either:
1. Let me log in and keep settings sync turned off and don't show this dialog over and over.
2. Let me NOT be logged in and don't show a badge on the gear icon.

Also... 
VS Code version: Code - Insiders 1.45.0-insider (1c36d747fbf113144d3bf82b0aa3cbd290714e38, 2020-04-15T05:37:18.376Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|12.00GB (5.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.3
githistory|don|0.6.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
output-colorizer|IBM|0.1.2
vscode-peacock|joh|3.7.0
mads|mir|0.0.5
csharp|ms-|1.21.17
remote-wsl|ms-|0.44.2
js-debug-companion|ms-|1.0.0
js-debug-nightly|ms-|2020.4.1417
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
quicktype|qui|12.0.46
vue-vscode-snippets|sdr|1.9.0
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.5
vscodeintellicode|Vis|1.2.6

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-04-15 19:10
Basically duplicate of #94822

**Comment by jtsom** [comment] 2020-04-15 19:12
Similar, but this is more for the dialog that keeps popping up. Yes I get I should read the docs or turn on Sync. I don't need to see the dialog over and over.

**Comment by sandy081** [comment] 2020-04-16 14:45
/duplicate

https://github.com/microsoft/vscode/issues/94888

There was a bug in insiders before that enabled Settings Sync automatically and we fixed this in next insiders here - https://github.com/microsoft/vscode/issues/94888. But fix cannot recover from disabling the sync and removing the badge. 

To fix this please disabled Sync using the command  `Preferences Sync: Turn off`

**Closed by sandy081** 2020-04-16 14:45 UTC
