### ISSUE TITLE
VSCODE gets restart when i drop a folder in explorer part and one more is directory issue, we can only put a working directory in explorer look at sublime text guys

### ISSUE THREAD

**Issue by Rahulshahare** [Microsoft/vscode#16283] opened 2016-11-30 18:14 UTC
- VSCode Version: latest version 1.7.2
- OS Version: windows 8 

Steps to Reproduce:
![git](https://cloud.githubusercontent.com/assets/13538433/20765024/b57972c2-b756-11e6-8cc8-d2de85584c67.jpg)

1. we want more directories to be placed in explorer 
2. and stop restarting when we drop any directory or folder

**Comment by chrmarti** [comment] 2016-11-30 18:33
Duplicate of #396

**Closed by chrmarti** 2016-11-30 18:33 UTC
