### ISSUE TITLE
No obvious way to close "Report a Problem" window when fullscreen on OSX

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode#63192] opened 2018-11-15 06:37 UTC
Issue Type: <b>Bug</b>

There is no button to cancel/close the "Report a Problem" window #59845 and it does not respond to OS common shortcut cmd+W (which is listed in the File menu) or Escape key.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.5.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
docs-article-templates|doc|0.1.3
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.5
docs-preview|doc|0.3.16
xml|Dot|2.3.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-pull-request-github|Git|0.2.3
beautify|Hoo|1.4.7
phpcs|ika|1.0.5
markdown-table-formatter|jos|0.2.3
vscode-liquid-snippets|kil|1.1.1
vale|lun|0.6.0
rainbow-csv|mec|0.8.0
xml-format|mik|1.0.0
ruby-rubocop|mis|0.7.1
mssql|ms-|1.4.0
python|ms-|2018.10.1
azurecli|ms-|0.4.2
cpptools|ms-|0.20.1
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.954
team|ms-|1.144.1
language-liquid|nei|0.0.3
open-html-in-browser|pea|0.0.3
vscode-docker|Pet|0.3.1
tsimporter|pmn|1.2.14
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.1.0
rust|rus|0.4.10
whitespace|san|0.0.5
trailing-spaces|sha|0.2.11
code-eol|soh|0.3.3
code-spell-checker|str|1.6.10

</details>

**Comment by nschonni** [comment] 2018-11-15 06:41
I'd flag this as an accessibility issue as well since it is kind of a keyboard trap

**Comment by RMacfarlane** [comment] 2018-11-27 22:13
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/59845, I've just checked in a fix for that so cmd+W should work as expected

**Closed by RMacfarlane** 2018-11-27 22:13 UTC
