### ISSUE TITLE
syntax highligting for large javascript file

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#38249] opened 2017-11-13 19:56 UTC
- VSCode Version: 1.18 , node 7.9
- OS Version: Win 10

Steps to Reproduce:
 
I have a very large javascript file (this allows me to import Json, since direct import is not supported in es6. There are 328K lines in the file. There is nothing wrong with syntax. but the text is all white, not colored, and the right-click context menu has no option for format. The JS icon does appear in the Exlplorer. The file name is Run-1-0.js

When I first entered the data, syntax highlighting worked, I restarted VSCODE and it was lost.

The data in the file looks like the following (15K repetitions are not included here:

```
export {data, metaData}

const metaData = {
    color: {
        rgba: [255, 255, 0, 255]
      },
    title: "Scene 2, Run 0"
    }
const data = [
    {
       "time": 1.2,
       "type": "3:1:222:1:-51:1:1",
       "name": "RTO",
       "lat": 21.5792240438319,
       "lon": -158.249617987526,
       "height": 3.59563912342738,
       "heading": 11.0059607376812,
       "pitch": 0,
       "roll": 0,
       "vx": 0,
       "vy": 0,
       "vz": 0,
       "forceType": "Friendly",
       "appearance": 33685504,
       "gccX": 0,
       "gccY": 0,
       "gccZ": 0,
       "psi": 0,
       "theta": 0,
       "phi": 0,
       "gccVX": 0,
       "gccVY": 0,
       "gccVZ": 0
     },
     {
       "time": 1.3,
       "type": "3:1:222:1:-51:1:1",
       "name": "RTO",
       "lat": 21.5792248335101,
       "lon": -158.249617823324,
       "height": 3.58777118543317,
       "heading": 10.9791128140066,
       "pitch": 0,
       "roll": 0,
       "vx": 0,
       "vy": 0,
       "vz": 0,
       "forceType": "Friendly",
       "appearance": 33685504,
       "gccX": 0,
       "gccY": 0,
       "gccZ": 0,
       "psi": 0,
       "theta": 0,
       "phi": 0,
       "gccVX": 0,
       "gccVY": 0,
       "gccVZ": 0
     },
```

Here is a screen shot:

![image](https://user-images.githubusercontent.com/2865368/32746128-b64dfa40-c882-11e7-9e1c-fd528b789f4c.png)

Reproduces without extensions: Yes

**Comment by maxibanki** [comment] 2017-11-13 20:14
Duplicate of #5303

Theres a 20 000 character line length limit which is currently as-designed.

**Comment by DrYSG** [comment] 2017-11-13 20:27
Ok, But do you also have to disable the right-click context menu option to format? I can live without colorization, but format is a good feature.

**Comment by mjbvz** [comment] 2017-11-13 20:49
Yes this is a duplicate of #34240

We start disabling many editor features once a file is over a certain size

**Closed by mjbvz** 2017-11-13 20:49 UTC
Labels: duplicate, javascript, new release

**Comment by maxibanki** [comment] 2017-11-13 20:53
@mjbvz #34240 is also a duplicate of #5303 :)
