### ISSUE TITLE
F1 and keybinding customization doesn't work in the integrated terminal

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#7269] opened 2016-06-06 21:47 UTC
- VSCode Version: Insiders 1.2.0
- OS Version: Windows 10 Insider Build 14332

Steps to Reproduce:

1. Open Terminal 
2. Make sure Terminal has focus
3. Press F1 key to invoke Command Palette
4. Command Palette doesn't open

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by Tyriar** [comment] 2016-06-06 22:00
Huh, didn't even notice this because I use <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> for the command palette. Thanks for the report @pcgeek86

**Comment by pcgeek86** [comment] 2016-06-06 22:06
Of course, thanks for looking into it @Tyriar!! :smile: 

I used to use CTRL + SHIFT + P, but then I changed over to F1 when I heard other folks using it. Honestly I love the natural feel of having both options. I use them both at various times.

**Comment by BurtHarris** [comment] 2016-06-20 17:54
I don't understand why you would expect F1 to do this in the "terminal window".   By "terminal window", I assume you mean the a CMD prompt window, such as displayed by pressing Ctrl+Alt+C under version 1.2.1.   

Non system-wide keyboard shortcuts depend on what window has the focus.

**Comment by Tyriar** [comment] 2016-06-21 18:01
The problem here is knowing which key sequences vscode should capture and which should be passed to the terminal. If vscode consumes <kbd>F1</kbd> then any terminal applications that rely on this will no longer work. Going to leave this one for now unless many people report as there is always the workaround of closing the terminal or using the other keybindings.

**Comment by BurtHarris** [comment] 2016-06-22 09:53
Agreed, I believe this is then not a bug but by design.

**Comment by kieferrm** [comment] 2016-06-28 21:47
I'm a F1 person. Not having F1 is particularly weird for cases like when you want to use the command palette to create a new terminal or navigate between them.

**Comment by Tyriar** [comment] 2016-06-28 22:15
Putting my comment on #8312 here on the potential way forward:

> I think the eventual solution to this is being able to tell the terminal which keystrokes to not pass to the terminal, it could be a bit tricky to do though.

**Comment by Tyriar** [comment] 2016-07-05 18:26
Upstream issue https://github.com/sourcelair/xterm.js/issues/152

**Closed** 2016-08-08 16:08 UTC
Labels: bug, integrated-terminal

**Comment by Tyriar** [comment] 2016-08-08 16:11
I just pushed a change that resolves this that will be available for testing in Insiders tomorrow. It exposes the `terminal.integrated.commandsToSkipShell` setting which is a list of command IDs that will *not* be handled by the terminal, allowing them to bubble up to be handled by the VS Code keybinding system. This is the default value:

```json
	"terminal.integrated.commandsToSkipShell": [
		"editor.action.toggleTabFocusMode",
		"workbench.action.quickOpen",
		"workbench.action.showCommands"
	]
```
