### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by adheramaf7** [microsoft/vscode#174179] opened 2023-02-12 11:35 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230210

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33923:11)
    at parseSimpleUnaryExpression (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33552:16)
    at parseUnaryExpressionOrHigher (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33520:35)
    at parseBinaryExpressionOrHigher (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33438:25)
    at parseAssignmentExpressionOrHigher (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33111:18)
    at parseExpression (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33077:16)
    at doOutsideOfContext (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30772:12)
    at allowInAnd (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30793:12)
    at parseExpressionOrLabeledStatement (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34593:24)
    at parseStatement (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34825:12)
    at parseListElement (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31544:12)
    at parseList (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31529:19)
    at parseSourceFileWorker (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30588:24)
    at Object.parseSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30421:20)
    at createSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30282:21)
    at createLanguageServiceSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:134900:22)
    at acquireOrUpdateDocument (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131822:26)
    at Object.acquireDocumentWithKey (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131747:12)
    at getOrCreateSourceFileByPath (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135225:31)
    at Object.getOrCreateSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135205:14)
    at c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135137:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:116904:24)
    at findSourceFileWorker (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119236:23)
    at findSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119156:20)
    at c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119105:22
    at getSourceFileFromReferenceWorker (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119074:26)
    at processSourceFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119103:5)
    at processRootFile (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:118899:5)
    at c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:41
    at forEach (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:5)
    at synchronizeHostData (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135161:15)
    at Object.getProgram (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135233:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171784:41)
    at ConfiguredProject2.updateGraph (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171721:32)
    at ConfiguredProject2.updateGraph (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:172903:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:174510:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175601:26)
    at c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:64
    at flatMap (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:24)
    at updateOpen (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:177026:29)
    at c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:69
    at IpcIOSession.executeWithRequestId (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179585:14)
    at IpcIOSession.executeCommand (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:29)
    at IpcIOSession.onMessage (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179635:51)
    at process.<anonymous> (c:\Users\adher\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:181203:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.30GB free)|
|Process Argv|--crash-reporter-id 6f1d347d-8d79-4949-b812-754a6af9e978|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.7.0
laravel-extra-intellisense|ami|0.6.2
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
vscode-better-align|cho|1.4.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
laravel-goto-view|cod|1.3.8
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-eslint|dba|2.4.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
bloc|Fel|6.6.2
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.224
laravel-blade-wrapper|IHu|1.0.1
pubspec-assist|jer|2.3.2
php-namespace-resolver|Meh|1.1.9
dotenv|mik|1.0.1
remote-wsl|ms-|0.75.1
live-server|ms-|0.4.5
sublime-keybindings|ms-|4.0.10
vscode-typescript-next|ms-|5.0.202302100
vuejs-extension-pack|mub|1.9.0
laravel-goto-components|nao|1.2.0
php-docblocker|nei|2.7.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.4.1
vscode-yaml|red|1.11.0
phpdoc-comment-vscode-plugin|rex|1.3.0
trailing-spaces|sha|0.4.1
vscode-blade-formatter|shu|0.20.9
vscode-status-bar-format-toggle|tom|3.1.1
errorlens|use|3.7.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
volar|Vue|1.0.24
vscode-typescript-vue-plugin|Vue|1.0.25
vscode-postcss|vun|2.0.2
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.31.0
markdown-all-in-one|yzh|3.5.0
php-intellisense|zob|1.0.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30657577
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by mjbvz** [comment] 2023-02-21 02:29
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:29 UTC
