### ISSUE TITLE
1.34 Insiders has broken two FileSystemProvider extensions

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#72909] opened 2019-04-26 08:59 UTC
When using [Remote FS](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs) to connect to FTP sites from 1.34 Insiders I am getting 0-byte results when opening files. If I use the same workspace with 1.33.1 the content of the files is returned correctly.

Create a .code-workspace file with the following content:
```
{
	"extensions": {
		"recommendations": ["liximomo.remotefs"]
	},

	"folders": [
		{
			"name": "ftp.intersystems.com/pub — (Remote)",
			"uri": "ftp://intersystems/pub"
		},
		{
			"name": "ftp.cs.brown.edu/pub — (Remote)",
			"uri": "ftp://brown/pub"
		}
	],
	"settings": {
		"remotefs.remote": {
			"intersystems": {
				"host": "ftp.intersystems.com",
				"scheme": "ftp",
				"username": "anonymous",
				"password": ""
			},
			"brown": {
				"host": "ftp.cs.brown.edu",
				"scheme": "ftp",
				"username": "anonymous",
				"password": ""
			}
		},
	
	}
}
```

Open it. It should recommend installation of the Remote FS extension. Do that. You should have two roots in the workspace:

![image](https://user-images.githubusercontent.com/6726799/56795300-1ef65d00-6808-11e9-92cd-d1a5bf6431b4.png)

Expand the first, locate the file named 00INDEX and open it. No error is reported, but there is no content.

Ditto for README under the second root.

Repeat these steps with 1.33.1 to see file contents fetched correctly.

Now uninstall the Remote FS extension, so it doesn't clash with the other extension we're about to test, [Remote Workspace](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace)

Create a second .code-workspace file containing this:
```
{
	"extensions": {
		"recommendations": ["mkloubert.vscode-remote-workspace"]
	},
	"folders": [
		{
			"uri": "ftp://anonymous@ftp.cs.brown.edu/pub",
			"name": "ftp.cs.brown.edu/pub"
		},
		{
			"uri": "ftp://anonymous@ftp.intersystems.com/pub",
			"name": "ftp.intersystems.com/pub"
		}

	],
	"settings": {}
}
```

Open this, allowing  the extension to install. With this workspace, neither of the roots will even expand.
![image](https://user-images.githubusercontent.com/6726799/56795945-7c3ede00-6809-11e9-8fd1-fdbf469eb16f.png)

Repeating the test in 1.33.1 should work, and you'll be able to open 00INDEX and README to see their true contents.

@bpasero May be related to #72891

Version: 1.34.0-insider (user setup)
Commit: 63655183ba5305b70ffaf1327b8a4708f0a79bd9
Date: 2019-04-26T05:21:48.183Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment] 2019-04-26 09:02
Looking into...

**Comment by bpasero** [comment] 2019-04-26 09:24
@gjsjohnmurray I am happy you reported this, thanks 👍. Will push a fix today.

**Comment by bpasero** [comment] 2019-04-26 09:59
@gjsjohnmurray for your second issue, when I try with stable, I cannot get the folders to expand. How is that possible you see it working?

**Comment by gjsjohnmurray** [comment] 2019-04-26 10:16
@bpasero Re the second issue, maybe the FTP sites aren't so reliable. The intersystems.com one opened OK for me just now from 1.33.1

![image](https://user-images.githubusercontent.com/6726799/56801019-59fe8d80-6814-11e9-8bbe-f190e96925ad.png)

So did the brown.edu one the second time I tried (no screenshot here).

In the past I've used ftp.microsoft.com but that's not responding today. Maybe down, or even decommissioned I guess.

**Comment by bpasero** [comment] 2019-04-26 10:21
@gjsjohnmurray well they work almost instantly with the other extension.

**Comment by bpasero** [comment] 2019-04-26 10:26
Since we should keep issues separate so that they are verified, I will close this one for the first issue reported. Please report a new issue if you think you can reproduce it reliably. Thanks.

**Comment by bpasero** [comment] 2019-04-26 10:27
**Verification:**
* follow the first part of https://github.com/Microsoft/vscode/issues/72909#issue-437570247
* make sure you can open files

**Closed by bpasero** 2019-04-26 10:26 UTC
Labels: bug, extensions, file-io, important, remote

**Comment by gjsjohnmurray** [comment] 2019-04-26 15:14
I confirm that the new Insiders build has resolved the issue with the current release of Remote FS:
```
Version: 1.34.0-insider (user setup)
Commit: c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5
Date: 2019-04-26T13:39:29.623Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299
```
Hopefully that project will still fix the extension so in future its `stat` returns `size` as `number` rather than `string` (https://github.com/liximomo/vscode-remote-fs/issues/56).

The new Insiders doesn't improve results with Remote Workspace, so let's see whether [the issue](https://github.com/mkloubert/vscode-remote-workspace/issues/119) I opened there leads to a fix.

@bpasero thanks for the fast turnaround on this issue.
