### ISSUE TITLE
WSL connect failed 

### ISSUE THREAD

**Issue by lujfsd** [microsoft/vscode#87752] opened 2019-12-27 05:53 UTC
Issue Type: <b>Bug</b>

WSL connect failed

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19536
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:34387

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: connect ECONNREFUSED ::1:34387
</details>Extensions: none

1. run VSCode and then closed
2. run VSCode again error,WSL connect faild。
must be run ```wsl --shutdown``` in powershell and then run VSCode is ok, but closed and run again error

**Comment by IllusionMH** [comment] 2019-12-27 18:22
/causedByExtension

Should issue should be reported in https://github.com/microsoft/vscode-remote-release/issues repo.
Most likely duplicate of https://github.com/microsoft/vscode-remote-release/issues/2082 and root cause https://github.com/microsoft/WSL/issues/4769

**Closed** 2019-12-27 18:22 UTC
Labels: *caused-by-extension
