### ISSUE TITLE
Add option for config sync across multiple installations

### ISSUE THREAD

**Issue by kaushikdas0** [Microsoft/vscode#27127] opened 2017-05-23 09:56 UTC
- VSCode Version:1.12.2 (1.12.2)
- OS Version: Mac

This is a suggestion

VCode should have an option to sign in with Outlook.com/hotmail account and all config should be able to sync across multiple installations though user profile. Option to also create multiple configs like Home Config, Weekend Config or Office Config and easier way to switch.

Lot of times we do some coding in office and switch laptop or use a bigger desktop in home. It would be really easy to sync rather than the Github hack sync way of doing the same. 

Cheers!

**Comment by yfdyh000** [comment] 2017-05-23 14:57
Duplicate of #7311.

**Closed** 2017-05-23 16:51 UTC
Labels: duplicate
