### ISSUE TITLE
Can't configure tasks on new folder

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93919] opened 2020-03-31 12:51 UTC
Testing #93746 on Linux

1. Open a folder without any tasks
2. `Tasks: Run Task`
3. Press `Enter` to `Configure Tasks...`

🐛  nothing happens

Once you've done this, quick open stays open and selecting any other option does nothing at all!

![image](https://user-images.githubusercontent.com/22350/78028255-fef7e380-735e-11ea-820c-eee90876cd00.png)

**Comment by alexr00** [comment] 2020-03-31 13:05
Duplicate of https://github.com/microsoft/vscode/issues/93834

**Closed by alexr00** 2020-03-31 13:05 UTC
