### ISSUE TITLE
Splitting first terminal after reload is sometimes really narrow

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127671] opened 2021-06-30 16:07 UTC
![image](https://user-images.githubusercontent.com/2193314/123994738-811bf100-d982-11eb-99ac-d687c217d2c6.png)

**Comment by meganrogge** [comment] 2021-06-30 18:17
Moving this milestone bc cannot reproduce the problem

**Comment by jeanp413** [comment] 2021-07-28 07:08
Created a PR #129668 fixing this

**Closed** 2021-08-04 16:04 UTC
Labels: bug, terminal
