### ISSUE TITLE
Tree: filter is not discoverable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#72119] opened 2019-04-11 08:59 UTC
I think that the tree filtering is not discoverable, especially in trees where people do not expect it to work. Like Call Stack, Watch...
Here's what I propose:

1. Render the orange filter widget with a minimal width when the tree has focus
2. Hovering over the minimal width filter widget we show a message "Start typing to filter"
3. When the user hides the minimal width widget, we no longer show it when empty for that tree.

**Comment by usernamehw** [comment] 2019-10-08 10:30
A bit similar to #70646

**Comment by joaomoreno** [comment] 2019-10-08 11:01
Thanks for the ping @usernamehw. You might have realized we're in a cleanup iteration right now and closing issues. I will actually close the other issue and keep this open to address the filter discoverability, which you mention in https://github.com/microsoft/vscode/issues/70646. I understand that you actually request more functionality in that issue, but out of cleanup sake, I'll close the issue as won't fix. Note that some of that functionality is spread out in other issues, like https://github.com/microsoft/vscode/issues/59455

**Comment by joaomoreno** [comment] 2020-11-02 15:30
Dupe of https://github.com/microsoft/vscode/issues/70646

**Closed by joaomoreno** 2020-11-02 15:30 UTC
Labels: feature-request, tree, ux
