### ISSUE TITLE
unable to open jupyter notebook

### ISSUE THREAD

**Issue by soumitra9** [microsoft/vscode#137341] opened 2021-11-17 01:38 UTC
We have written the nee
Issue Type: <b>Performance Issue</b>

I am gettingg Errorloading webview as I am trying to open a jupyter notebook.

Full error:

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

VS Code version: Code 1.62.2 (Universal) (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|. --crash-reporter-id 1970fd2b-d839-4c27-8495-efadcea3145e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	   180	 37866	code main
    0	    66	 37871	   gpu-process
    0	    33	 37873	   utility
    0	   246	 37874	   window (Adhoc_null_domain_and_backfill copy.ipynb — FAN-338)
    0	   164	 37877	     extensionHost
    0	   131	 37920	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) --ms-enable-electron-run-as-node /Users/t_mehrso/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/server.bundle.js --cancellationReceive=file:1030e9ab4a23e6bb301e1254b3dae61ce5a75f7d49 --node-ipc --clientProcessId=37877
    0	   147	 37970	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) --ms-enable-electron-run-as-node /Users/t_mehrso/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/server.bundle.js --cancellationReceive=file:37fe2f47c9aa79ec6321d0815f6c6ed4b1830437fc --node-ipc --clientProcessId=37877
    0	    16	 38006	       /Users/t_mehrso/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    16	 38007	       /Users/t_mehrso/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    16	 38008	       /Users/t_mehrso/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    33	 37878	     watcherServiceNSFW
    0	    33	 37880	     searchService
    0	   131	 37876	   shared-process
    0	    49	 37879	     ptyHost
    0	     0	 38099	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 37891	   window (undefined)
    5	    66	 38097	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Adhoc_null_domain_and_backfill copy.ipynb — FAN-338)
|    Folder (FAN-338): 26 files
|      File types: py(10) ipynb(7) csv(3) sql(2) DS_Store(1) xlsx(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

ded data into your clipboard because it was too large to send. Please paste.

**Comment by GammaGames** [comment] 2021-11-18 23:36
I'm getting this as well, but with a [dashboard extension](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard)

**Comment by mjbvz** [comment] 2021-11-19 00:24
Duplicate of #125993

**Closed by mjbvz** 2021-11-19 00:24 UTC
