### ISSUE TITLE
VSCode does not like inline CSS

### ISSUE THREAD

**Issue by fabiogusmao** [Microsoft/vscode#19399] opened 2017-01-25 22:18 UTC
We all know inline CSS is a really bad practice and should be avoided at all costs by any web developer. Yeah, right. But VS Code seems to be taking this rather too seriously and applying bad formatting to any HTML after a style attribute in HTML document, shifting every line after the rotten one to the left, therefore messing the indentation completely.

## How to reproduce

1. Open a new VS Code window
2. Set language to HTML (Control+K, M then type HTML)
3. Paste in the following code:

```
<html>  
    <body>
        
        <div style="border:1 px solid red">I'm a block element</div>
        <p>I'm a paragraph</p>
        <p>I'm a second paragraph</p>
        <p>I'm a third paragraph</p>
    </body>
</html>

```
4. Format code with Control+Shift+F

And it's done! The code will look like this:

```
<html>

<body>

    <div style="border:1 px solid red">I'm a block element</div>
<p>I'm a paragraph</p>
<p>I'm a second paragraph</p>
<p>I'm a third paragraph</p>
</body>

</html>
```

Notice the 3 empty lines and how the `<p>` tags have shifted leftwards?

Tested on version 1.8.1

**Comment by ramya-rao-a** [comment] 2017-01-26 00:05
Duplicate of #17849

**Comment by mousetraps** [comment] 2017-01-26 01:33
Thanks for reporting! Closing as it's a duplicate, but please give the latest Insiders build a whirl and verify that the issue is resolved for you! If not, or if you think it's something different, we can reopen. Thx!

**Closed by mousetraps** 2017-01-26 01:33 UTC
