### ISSUE TITLE
Cannot read property 'iconUrl' of undefined when showing running extensions

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#39715] opened 2017-12-05 19:22 UTC
Re #39568

* Install extension EditorConfig
* Reload Window
* Show Running Extension
* Open Developer Tools

```
TypeError: Cannot read property 'iconUrl' of undefined
    at Object.renderElement (runtimeExtensionsEditor.ts:304)
    at e.renderElement (listWidget.ts:635)
    at e.insertItemInDOM (listView.ts:295)
    at e._splice (listView.ts:196)
    at e.splice (listView.ts:139)
    at e.splice (listWidget.ts:34)
    at listWidget.ts:760
    at e.bufferEvents (event.ts:359)
    at n.e.splice (listWidget.ts:760)
    at i._updateExtensions (runtimeExtensionsEditor.ts:141)
```

I can always see the error on both Linux and macOS, however on Linux, I see an empty entry of running extension

![image](https://user-images.githubusercontent.com/876920/33626166-a053c656-d9ae-11e7-8265-9b253f6ff6af.png)

**Comment by rebornix** [comment] 2017-12-05 19:25
Besides, when this happens, I can no longer scroll the page, no matter how long the list is.

**Comment by ramya-rao-a** [comment] 2017-12-07 17:11
Same for the Go extension

**Comment by isidorn** [comment] 2017-12-07 17:19
I can also look into this one, assigning to November

**Comment by alexandrudima** [comment] 2017-12-07 21:20
I believe this might be caused by a specific extension...

**Closed** 2017-12-08 09:47 UTC
Labels: bug
