### ISSUE TITLE
Quick info gets cut off for long text

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#1112] opened 2015-12-08 20:50 UTC
![image](https://cloud.githubusercontent.com/assets/972891/11668098/2e672f3e-9daa-11e5-8866-7c107b7ffe5f.png)

**Comment by jrieken** [comment] 2015-12-09 09:14
duplicate of #842

**Closed by jrieken** 2015-12-09 09:14 UTC
Labels: bug

**Comment by DanielRosenwasser** [comment] 2015-12-09 09:47
Sorry I missed that, thanks @jrieken!
