### ISSUE TITLE
Terminal split button no longer available when bottom panel alignment is set to Justify

### ISSUE THREAD

**Issue by ChetanGandhi** [microsoft/vscode#162302] opened 2022-09-29 07:21 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0

- OS Version: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Open VSCode integrated terminal.
2. Set the bottom panel alignment to Justify.
3. Terminal split button is no longer available in terminal tabs panel nor in the header.
![image](https://user-images.githubusercontent.com/2204310/192966034-453ca4ab-742c-4c8b-8106-3f337fd0a955.png)

**Comment by Tyriar** [comment] 2022-12-05 17:27
I can't reproduce:



![Image](https://user-images.githubusercontent.com/2193314/205702546-876805a1-970f-4b83-86a1-fc988dba10d8.png)


Maybe a bug that's fixed now or you have hidden the item?



![Image](https://user-images.githubusercontent.com/2193314/205702599-e108d0ea-51ae-49f0-9e4e-db7407a3b49b.png)

**Closed by Tyriar** 2022-12-05 17:27 UTC

**Comment by ChetanGandhi** [comment] 2022-12-08 11:47
@Tyriar, found that this is happening due to this setting `"terminal.integrated.tabs.hideCondition": "never"`.
In this case the actions are visible when I hover the terminal entry in terminal tabs panel
![image](https://user-images.githubusercontent.com/2204310/206438451-d601cf4f-1d02-4fd3-9627-c751e3b60aca.png)

Also if the terminal tabs panel is resized to small width, actions are no longer visible
![image](https://user-images.githubusercontent.com/2204310/206438814-3423ba1d-c00c-4aa0-9ab8-74054b3790eb.png)

If I set this to `"terminal.integrated.tabs.hideCondition": "singleTerminal"` then I am able to see the actions in header
![image](https://user-images.githubusercontent.com/2204310/206438564-1f4e4428-4ce0-461b-afdd-83c5d4a4048c.png)

This still happens with new version of VSCode
Version: 1.74.0 (system setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
