### ISSUE TITLE
Inability to create file/folder at root location

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#9346] opened 2016-07-15 14:18 UTC
- VSCode Version: 1.4.0-insider
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open project that has only directories at root level (and have them a lot - so you need to scroll)
2. Click any folder
3. Try to create folder / file at the root

It won't be possible because there is no space to click to unselect the folder and hence impossible to create new folder or file at the root.

Moreover in the following screen - its not really clear where it will create file / folder (current folder is not highlighted)

![image](https://cloud.githubusercontent.com/assets/1723815/16877279/58053c3c-4a75-11e6-94e5-7ed25329b7d6.png)

If I click new folder it creates in: 

![image](https://cloud.githubusercontent.com/assets/1723815/16877296/676b374e-4a75-11e6-923c-2ee42048e4d2.png)

but as you can see on first screenshot - it was impossible to tell it will create in that folder

**Comment by bpasero** [comment] 2016-08-05 10:25
A UX issue we heard in the past already.

**Comment by bpasero** [comment] 2016-08-05 10:38
Also applies to DND when you try to move a folder to make it top level.

**Comment by niieani** [comment] 2016-08-06 09:29
I'll copy & paste my solution suggestions from the other issue:

1. allow dragging files to the project name, which is an always visible UI element
2. add a slight padding to the bottom of the files list in the Files Explorer, so there is always room to drag files out to the top-level after scrolling down

**Comment by wallverb** [comment] 2016-08-06 16:11
One way to create at the root in such case is to click scrollbar - this way current folder is unselected and its possible to create at root. Works on OSX, not sure about WIN

**Comment by Tyriar** [comment] 2016-08-06 16:55
Duplicate of https://github.com/Microsoft/vscode/issues/1043

**Closed by Tyriar** 2016-08-06 16:55 UTC
Labels: files, ux
