### ISSUE TITLE
vscode opens files from comman line in separate instances

### ISSUE THREAD

**Issue by EugenWiens** [Microsoft/vscode#9616] opened 2016-07-22 09:25 UTC
- VSCode Version: 1.3.1
- OS Version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

If I start vscode multiple times from the command line with file as parameter it opens for every file a new instance.
Is it possible that vscode opens the files from command line in the same instance. So that I get the behavior of geany (editor on ubuntu).

Regards,

Eugen Wiens

**Comment by kieferrm** [comment] 2016-07-22 17:23
Duplicate of #9479.

**Closed by kieferrm** 2016-07-22 17:23 UTC
Labels: duplicate
