### ISSUE TITLE
Build errors have been detected during preLaunchTask 'npm'

### ISSUE THREAD

**Issue by vuhrmeister** [microsoft/vscode#8493] opened 2016-06-29 11:00 UTC
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

If I run my extension in debug mode the first time it's all fine. But when re-running I get the error message `Build errors have been detected during preLaunchTask 'npm'`. I can click "Debug Anyway", though (and it works).

After a restart of vscode I can run my extension without error once again before the error occurs again.

Steps to Reproduce:
1. Create an empty TypeScript extension with Yeoman
2. Install typings: `typings install registry:env/meteor --global`

I also created a repository including the 2 steps, if you prefer that way: https://github.com/vuhrmeister/vscode-extension-prelaunch-fail

I opened this issue as requested by @isidorn (https://github.com/Microsoft/vscode/issues/4070#issuecomment-229321428).

**Comment by isidorn** [comment] 2016-07-06 10:31
@vuhrmeister Thanks for creating great repro steps!
The issue is that you have build errors in your project, if you open the problems panel you can see a bunch of them.

VSCode task framework currently has a limitation that it is not correlating tasks to the errors produced, thus in the debug world we only know there are 22 errors, we do not know what produced them. Due to that reason we show the action 'Debug Anyway' because those errors can be bogus.

In order to improve this experience we need 1 of the following:
* Provide option to dismiss errors, so you could just ignore all the errors from meteors index.d.ts
* Correlate errors to tasks in the task framework 

Due to these reasosn I am assigning @sandy081 and @dbaeumer 
This is not the first user facing this problem so I think we should address this.

**Comment by dbaeumer** [comment] 2016-07-06 19:38
@isidorn I am not a fan of adding a task as a owner or source of an error. That seams bogus. All we can do is to add some counters to a task summary telling of markers got created. Or add an event. Since I'm out on vacation in July this can't happen for the July backlog. But feel free to provide a PR :-)

**Comment by starakaj** [comment] 2018-10-25 21:12
Hey, I'm seeing what I believe to be the same issue showing up in another form. In my case, linting errors from ESLint are being associated with the build task for some reason, and causing the same warning to appear. Happy to add formal steps to reproduce if it's helpful.

**Comment by alexr00** [comment] 2019-05-27 15:10
@starakaj could you add some repro steps? My attempt to repro didn't result in this issue.
My steps:
In an extension add these tasks
```
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
		},
		{
			"type": "shell",
			"command": "echo hello",
			"problemMatcher": [],
			"label": "echo task"
		}
```
Add this launch config
```
		{
			"name": "Error test",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "echo task",
		}
```
Make a compile error in the extension code.
Run the npm watch task.
Run the Launch config.
Restart debugging.

**Comment by alexr00** [comment] 2019-10-10 10:10
Duplicate of https://github.com/microsoft/vscode/issues/31968

**Closed** 2019-10-10 10:10 UTC
Labels: *duplicate, debug, error-list, feature-request, tasks
