### ISSUE TITLE
Passing arguments to preLaunchTask in launch.json

### ISSUE THREAD

**Issue by dopare** [Microsoft/vscode#6061] opened 2016-05-03 09:34 UTC
I am using `launch.json` to debug .Net Core Application in VS code. 
Debugger configuration uses `"preLaunchTask": "build"` to build application before starting, but the problem is that I have several projects in my solution that I want to debug, so I have duplicated `launch.json` configurations for every single executable project in my solution. With this scenario `build` preLaunchTask is not working. I need to pass my project's directory to `build` task.

Is there anyway to pass arguments to `preLaunchTask` from `launch.json`?

**Comment by isidorn** [comment] 2016-05-04 09:43
Yes, tasks in "preLaunchTask" are actually referencing tasks in `tasks.json`. Inside the `tasks.json` you can pass arguments to your task. More about configuring tasks can be found [here](https://code.visualstudio.com/docs/editor/tasks)

**Comment by dopare** [comment] 2016-05-04 09:46
Build task is unique I can't dublicate it in task.json passing different arguments. I need to define arguments in launch.json

**Comment by isidorn** [comment] 2016-05-04 09:51
Forwarding to @dbaeumer to get his opinion what is recommended here

**Comment by dbaeumer** [comment] 2016-05-09 11:03
@dopare I am not fully understanding why you can't have a build2 task having the additional argument.

@isidorn we could extend the task runner API so that you can pass additional arguments which a user specifies in launch.json. Not sure so if you want to do down that road.

**Comment by dbaeumer** [comment] 2016-05-09 11:04
@isidorn please open a request if you want me to add the additional API.

**Comment by isidorn** [comment] 2016-05-09 11:07
@dbaeumer I do not want to go down that road. I was just not fully sure if we support the scenario @dopare is requsting using a build2 task. Since you say we do I am closing this, since this request cant be done by adding an additional task in the `tasks.json` and referencing that task in `preLaunchTask`

**Closed by isidorn** 2016-05-09 11:07 UTC
Labels: question

**Comment by dopare** [comment] 2016-05-09 11:09
I have simple task which is automatically generated by coreclr debugegr
```
{
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build2",
            "args": [],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
```

this says that dotnet-build2 is not a shell command

**Comment by isidorn** [comment] 2016-05-09 12:02
@dopare not sure why you get that error maybe @dbaeumer or @gregg-miskelly can comment

**Comment by dbaeumer** [comment] 2016-05-09 12:04
The problem is that the taskName is automatically added to the command line as an argument. You can do the following:

```
{
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        ... ,
        {
            "taskName": "build2",
            "suppressTaskName": true,
            "args": ["build", "some arguments"],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by dopare** [comment] 2016-05-09 12:06
@dbaeumer your solution is not working, it treat `"build"` as path, still same exception

**Comment by dbaeumer** [comment] 2016-05-09 12:09
Can you add 	"echoCommand": true globally and provide me with the output of triggering build and build2

**Comment by dopare** [comment] 2016-05-09 12:10
@dbaeumer  sorry, updated my comment
Its worked
