### ISSUE TITLE
When you have finished running a task, the terminal panel will always close automatically

### ISSUE THREAD

**Issue by ppyupp** [Microsoft/vscode#32276] opened 2017-08-11 03:17 UTC
- VSCode Version:1.15
- OS Version:macOS 10.12.6

When you have finished running a task, the terminal panel will always close automatically...
1.14 is no such problem

**Comment by dbaeumer** [comment] 2017-08-15 08:40
@ppyupp  This depends on how you have configured the task. Can you provide a setup that demonstrates the problem. Then I can either tell you how to configure it or investigate whether we have a bug.

**Comment by ppyupp** [comment] 2017-08-15 14:12
my task config:

{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "php",
            "command": "/opt/php/bin/php",
            "type": "shell",
            "args": [
                "${file}"
            ],
            "presentation": {
                "reveal": "always",
                "echo": false
            },
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by ppyupp** [comment] 2017-08-15 14:13
@dbaeumer 

my task config:

{
"version": "2.0.0",
"tasks": [
{
"taskName": "php",
"command": "/opt/php/bin/php",
"type": "shell",
"args": [
"${file}"
],
"presentation": {
"reveal": "always",
"echo": false
},
"problemMatcher": [],
"group": {
"kind": "build",
"isDefault": true
}
}
]
}

**Comment by ppyupp** [comment] 2017-08-16 08:22
@dbaeumer 

`<?php

echo 123;`

when i run these code,   the terminal panel will always close automatically


`<?php
sleep(1);
echo 123;`

but...these code, the terminal panel will not close....

**Comment by ChristianSiegert** [comment] 2017-08-21 10:00
I have the same problem: Tasks automatically close the terminal they opened after they ran.

Example tasks.json:
```json
{
	"tasks": [
		{
			"args": [
				"hello"
			],
			"command": "echo",
			"presentation": {
				"echo": true,
				"focus": true,
				"panel": "new",
				"reveal": "always"
			},
			"problemMatcher": [],
			"taskName": "echo hello",
			"type": "process"
		}
	],
	"version": "2.0.0"
}
```

Tested with macOS 10.12.6 and vscode 1.15.1.

**Comment by dbaeumer** [comment] 2017-08-22 19:28
@ChristianSiegert thanks for the repro.

**Comment by dbaeumer** [comment] 2017-08-22 19:28
Moving to August time dependent.

**Comment by dbaeumer** [comment] 2017-08-24 19:16
@ChristianSiegert since I can't reproduce this does this happen with the following task as well.

```
{
	"tasks": [
		{
			"args": [
				"-e", "console.log('Hello')"
			],
			"command": "node",
			"presentation": {
				"echo": true,
				"focus": true,
				"panel": "new",
				"reveal": "always"
			},
			"problemMatcher": [],
			"taskName": "echo hello",
			"type": "process"
		}
	],
	"version": "2.0.0"
}
```

I suspect that this happens because echo typically executed inside a shell. Does this work if you change the "type" to "shell"?

**Comment by ChristianSiegert** [comment] 2017-08-24 20:09
@dbaeumer If I change “type“ from “process” to “shell” in the task I posted originally, the behavior stays the same (the terminal is closed). If I use your task, the terminal stays open.

I tested further and it seems to be a race condition. I created two shell scripts, `script-1.sh` and `script-2.sh`. `script-1.sh` is simply echo and always triggers the bug. `script-2.sh` is echo and sleep. For my system, this is the behavior with different sleep values (sleep accepts a float on my system):

- `sleep 0.09`: terminal almost always closes itself
- `sleep 0.1`: terminal closes itself about 50% of the time
- `sleep 0.11`: terminal rarely closes itself
- `sleep 1`: terminal never closes itself

**script-1.sh:**
```sh
#!/bin/bash
echo "hello"
```

**script-2.sh:**
```sh
#!/bin/bash
echo "hello"
sleep 0.1
```

**tasks.json:**
```json
{
	"tasks": [
		{
			"command": "./script-1.sh",
			"problemMatcher": [],
			"taskName": "script 1",
			"type": "shell"
		},
		{
			"command": "./script-2.sh",
			"problemMatcher": [],
			"taskName": "script 2",
			"type": "shell"
		}
	],
	"version": "2.0.0"
}
```

**Comment by dbaeumer** [comment] 2017-08-25 08:33
@ChristianSiegert thanks for the investigation.

@Tyriar in both cases I construct the same `command line` which I pass to the terminal instance. Could it be that the terminal registers a listener async and in the script-1.sh sample the process already has finished before the listener is registered.

**Comment by Tyriar** [comment] 2017-08-30 16:23
@dbaeumer ah I know what the problem here is... Currently how I know that a shell failed to launch is by seeing if it exited within 500ms:

https://github.com/Microsoft/vscode/blob/751a32c61791b78264a8b90361a0f29fc8377433/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L646-L661

We're only entering the waitOnExit handling block if the terminal state was `KILLED_BY_PROCESS` which ensures the shell has been running for 500ms+. This just needs to be changed to `if (this._shellLaunchConfig.waitOnExit)` since we always want to respect this.

**Closed** 2017-08-30 16:50 UTC
Labels: bug, integrated-terminal, needs more info, new release
