### ISSUE TITLE
Do not close workspace on ⌘W

### ISSUE THREAD

**Issue by abock** [Microsoft/vscode#47756] opened 2018-04-12 15:44 UTC
Issue Type: <b>Bug</b>

Multiple times a day I find myself accidentally closing an entire VS Code workspace (usually with multiple terminals active) because I will <kbd>⌘W</kbd> through open tabs.

Unfortunately once the last tab has closed, <kbd>⌘W</kbd> will close the workspace window, which is _definitely_ not what I want to do.

Visual Studio for Mac does the right thing here - close tabs, never close the IDE.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (4.94GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-color|ans|0.4.5
spellright|ban|2.2.10
cpptools|ms-|0.16.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
qub-msbuild|qub|0.6.3

</details>

**Comment by abock** [comment] 2018-04-12 15:49
Note that `window.closeWhenEmpty` is `false` (the default value) in my user settings, though I'm not sure it's even meant to apply to this scenario:

```json
  // Controls if closing the last editor should also close the window.
  // This setting only applies for windows that do not show folders.
  "window.closeWhenEmpty": false
```

**Comment by usernamehw** [comment] 2018-04-12 17:34
Duplicate of #42898

**Comment by joaomoreno** [comment] 2018-04-13 07:05
You can always clear that keybinding:

![image](https://user-images.githubusercontent.com/22350/38721253-b1707172-3ef9-11e8-8e04-16e2990fa5e5.png)

**Closed by joaomoreno** 2018-04-13 07:05 UTC
