### ISSUE TITLE
${folderName} empty

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#81247] opened 2019-09-20 20:45 UTC
Issue Type: <b>Bug</b>

If I try to set a `window.title` with a `${folderName}` component in it, that component is **always** empty.

When should it have a value?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.2.11-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3537)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|31.33GB (0.25GB free)|
|Process Argv|utils/rpms/cart.spec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.0.0
rpm-spec|Lau|0.2.3
python|ms-|2019.9.34911
code-navigation|vik|0.2.0
vim|vsc|1.10.2

</details>

**Comment by bpasero** [comment] 2019-09-24 06:38
@brianjmurrell it should always have a value when you open a folder or workspace with VSCode. Are you maybe using empty workspace?

**Comment by brianjmurrell** [comment] 2019-09-26 16:06
> open a folder

I suppose I was just assuming **folder** was just whatever directory you were in when you started `code`.  In any case, I have been creating workspaces just so that I can use `${workspaceName}` in my `window.title`.

**Comment by bpasero** [comment] 2019-09-26 16:35
Yes, it is the folder you opened. I cannot reproduce this, closing.

**Closed by bpasero** 2019-09-26 16:35 UTC
Labels: needs more info

**Comment by brianjmurrell** [comment] 2019-09-26 17:04
> Yes, it is the folder you opened

That I _opened_ or was just in when I opened a new `code` window?

I'm assuming that there is an action in `code` that relates to *open*ing a folder more than it just implicitly being the directory you were in when you opened the `code` window.
