### ISSUE TITLE
Support for custom editors registered via file extensions

### ISSUE THREAD

**Issue by pietie** [Microsoft/vscode#5604] opened 2016-04-21 12:39 UTC
Similar to Visual Studio extensions, I would like to register a specific file extension and swap out the code editor for a custom UI experience when that file opened.

**Comment by dbaeumer** [comment] 2016-04-21 13:17
@bpasero @alexandrudima @jrieken FYI.

**Comment by bpasero** [comment] 2016-04-21 14:18
I am tempted to close this one because I do not think our goal would ever be to support this scenario. But since I cannot look into the future, I leave it open.

**Comment by zzmingo** [comment] 2017-02-21 09:58
+1, I read vscode API and source, try to find a way open a custom editor, it seems can't be done with extension API.

**Comment by TomMarius** [comment] 2017-03-02 10:55
+1, I'd like to develop a React-based UI designer coupled with a code editor

**Comment by RobertBColton** [comment] 2017-06-15 07:22
One current way to do this is using the HTML preview for the GUI. HTML does have checkboxes, textfields, etc. I haven't checked if it is possible but you should be able to save the file path and immediately write-back changes in the HTML preview to the file. Or you could add a redundant save button to the HTML preview.

https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample

+1 Because I still feel VS Code needs more robust custom editor extension authoring. The preview work around doesn't really fit with the intended use of the feature.

The number of use cases VS Code would be able to cover would be greatly extended if this feature were implemented. For example, I am currently investigating its use as a project editor for a game engine where this would be extremely useful.

**Comment by cwtuan** [comment] 2017-09-01 03:14
Any plan for "real" custom UI?

**Comment by hellonavneet** [comment] 2017-12-31 01:35
+1 ... I want to build an extension that supports a blockly based experience where kids can code using blocks rather than write code ... Something similar to MIT Appinventor or Scratch.

**Comment by dschaefer** [comment] 2018-02-02 00:05
+1 We have system trace files that I'd like to be able to open my own editor to view the trace graphically. Otherwise it opens as an unknown binary type.

Note that I can do this with my own tree provider. I really just want to do the same in the file explorer for certain file extensions or more generally language modes, i.e. to be able to specify an open command that overrides the default behavior.

If I figure out how to do this cleanly, would you be open to a pull request?

**Comment by egamma** [comment] 2018-02-02 07:11
@dschaefer another approach is that you contribute a command to the explorer´s context menu for this particular file type that opens the trace graphically.

**Comment by dschaefer** [comment] 2018-02-02 15:20
Thanks @egamma yes, I'll do that for the protoype. But it's not a good user experience. It'll be hard to explain why these files don't open like other files in their workspace, especially since the error message says "the file will not be displayed". I think we should be making every attempt for that message not to be displayed, including allowing some other editor, or command at least, to take care of it.

**Comment by bpasero** [comment] 2018-02-06 05:38
Closing as duplicate of https://github.com/Microsoft/vscode/issues/12176 (which has more votes).

**Closed by bpasero** 2018-02-06 05:38 UTC
Labels: feature-request, workbench-editors
