### ISSUE TITLE
opening code from EAGLE CAD

### ISSUE THREAD

**Issue by grosfaignan** [Microsoft/vscode#66914] opened 2019-01-22 11:35 UTC
hi there
when i try to open Code from the command line of EAGLE CAD (autodesk), with this param : 
`"C:\Users\CHARLY\AppData\Local\Programs\Microsoft VS Code\Code.exe" -r -g %F:%L:%C`
the -r param isn't really used, it cans help to don't open a new version of >code, but don't display the opend files related to.
i tried to modify some params as : 
   ```
"workbench.editor.restoreViewState": false,
    "workbench.editor.revealIfOpen": true,
    "window.openFilesInNewWindow": "off",
    "window.openFoldersInNewWindow": "off",
    "window.openWithoutArgumentsInNewWindow": "off",
    "workbench.settings.editor": "json",
```

but did nothing, anyone could help me please? 

regards charly

**Comment by bpasero** [comment] 2019-01-23 09:33
> it cans help to don't open a new version of >code, but don't display the opend files related to

I do not understand this, please clarify. Send a video if you like.

**Comment by grosfaignan** [comment] 2019-01-23 09:51
for example, when i have a bug, in EAGLE CAD ULP, the eagle ulp interpreter open the file.
but the file is opened twice if it was already open in VScode.

**Comment by bpasero** [comment] 2019-01-23 10:19
@grosfaignan opened twice in a new window or same window?

**Comment by grosfaignan** [comment] 2019-01-23 10:23
in the same instance of >code but in a new >tab

**Comment by grosfaignan** [comment] 2019-01-23 10:36
C:\Users\CHARLY\Documents\eagle\ulps\objectDatalist.ulp
C:\Users\CHARLY\Documents\EAGLE\ulps\objectDatalist.ulp
yes that's right but i don't understand why

**Comment by bpasero** [comment] 2019-01-23 10:39
I suggest you ask the maintainers of the program you are using. Otherwise, closing as duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2019-01-23 10:39 UTC
Labels: needs more info
