### ISSUE TITLE
Release Notes loses place

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#78802] opened 2019-08-09 13:59 UTC
Issue Type: <b>Bug</b>

I just started using VS Code a few weeks ago, and so far LOVE IT.  I just got my first "Release Notes" (document) tab automatically appear, when Code seemed to have automatically updated.  So far, so good.  I've been reading the "Release Notes" tab, and trying out the various things that are new (e.g., going to settings).  It seems that whenever I change tabs from the "Release Notes" tab (e.g., to the Settings tab) that when I return to Release Notes, it has scrolled back up to the top, and lost my place.  I would expect it to act, like the other document tabs, to remember where I was scrolled to.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: andy-linux|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3504)|
|Memory (System)|62.86GB (12.05GB free)|
|VM|0%|
</details>

**Comment by garyng** [comment] 2019-08-09 14:24
You can always check the release notes at https://code.visualstudio.com/updates/ using your browser.

**Comment by octref** [comment] 2019-08-09 15:35
Duplicate of #27498.

**Closed by octref** 2019-08-09 15:35 UTC
Labels: new release
