### ISSUE TITLE
White flash on startup

### ISSUE THREAD

**Issue by forumwt** [microsoft/vscode#192498] opened 2023-09-07 22:40 UTC
https://github.com/microsoft/vscode/assets/16545063/54722e82-3b9a-4096-9881-a3d4901418d8

Type: <b>Bug</b>

On startup white screen flashes when run as maximized, same issue in latest insider too

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 x 3912)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (24.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|1.0.0
multi-cursor-case-preserve|Car|1.0.5
path-intellisense|chr|2.8.4
rightclickfix|cod|1.0.4
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
select-all|Gag|0.0.1
batch-rename-extension|Jan|0.0.6
github-icons-for-vscode|juw|1.3.0
vscode-colorize|kam|0.11.1
vscode-phpfmt|kok|1.1.22
pretty-php|lkr|0.4.23
sftp|Nat|1.16.3
select-compare-tabs|out|1.0.3
vscode-css-peek|pra|4.4.1
vscode-thunder-client|ran|2.11.4
css-auto-prefix|spo|0.1.7
errorlens|use|3.13.0
gistfs|vsl|0.4.1
cursor-align|yo1|1.1.2
pretty-ts-errors|yoa|0.5.1
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2023-09-08 01:09
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by tamuratak** [comment] 2023-09-08 03:56
Might be duplicate of  #95190 and #191307

**Comment by forumwt** [comment] 2023-09-08 08:15
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Already tried that but looks problem is not with extension or theme, I have also try to disable and remove all of them but same problem is still there

**Closed** 2023-09-14 23:52 UTC
