### ISSUE TITLE
 I don't use Japanese IME on integrated terminal

### ISSUE THREAD

**Issue by ishisaka** [Microsoft/vscode#8674] opened 2016-07-02 12:01 UTC
- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10 th2

Steps to Reproduce:

1. Ctrl + `, Open integrated terminal. Set cursor on integrated terminal.
2. Alt + `, turn on IME.
3. I can't | ALT + ` should turn on IME | But it doesn't, I don't use Japanese IME on integrated terminal.

**Comment by Tyriar** [comment] 2016-07-02 23:06
Duplicate of https://github.com/Microsoft/vscode/issues/7045

**Closed by Tyriar** 2016-07-02 23:06 UTC
Labels: bug, integrated-terminal
