### ISSUE TITLE
i need using terminal

### ISSUE THREAD

**Issue by Ramsolz666** [microsoft/vscode#117883] opened 2021-03-01 11:25 UTC
Issue Type: <b>Feature Request</b>

when i use the terminal, it is blank, none of all, including cmd or powershell. But i have set all in the settings.json.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18362

**Comment by meganrogge** [comment] 2021-03-01 16:39
Duplicate of #117123

**Closed** 2021-03-01 16:40 UTC
Labels: *duplicate, bug, integrated-terminal
