### ISSUE TITLE
Source Control: Diff does not update after "Stage/Unstage Selected Ranges" ...

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode#149803] opened 2022-05-18 08:36 UTC
... when "files.watcherExclude": {...} is configured in your settings.
!!! The file in question is **NOT** included in the exclude setting. !!!

This annoys me some time now, so this isn't new.

I have my workspace configured as such:
![grafik](https://user-images.githubusercontent.com/1822013/168991311-1e0306a0-1205-45b3-85c8-c8844d8b332e.png)
I've copied the exclude settings from my project where I discovered this.
As you can see `test.c` shouldn't match any of those rules.

This is my test file in the diff view with some unstaged and uncommited changes:
![grafik](https://user-images.githubusercontent.com/1822013/168991233-edf15099-53fc-4d53-a57e-329a24726da3.png)

If I now select some changes and stage them the diff view does not update (most of the time, sometimes it does, but way more often it doesn't). I now have to change tabs or click out of the window and back in to update the diff view.

Made a GIF for you:
![stage_no_work](https://user-images.githubusercontent.com/1822013/168994093-3a90237b-ef7e-4570-a5c6-1eb449b135b7.gif)

The really annoying part is that if you do select-stage multiple sections in sequence without the view updating in between only the last staged change is preserved. GIF again:
![stage_no_preserve](https://user-images.githubusercontent.com/1822013/168995251-e17d9171-94ad-43af-bbbf-9edf6710ccdf.gif)

Here's the workspace I used for testing:
[vsbug.zip](https://github.com/microsoft/vscode/files/8714572/vsbug.zip)

- No Extensions Enabled
- VS Code Version: 1.67.1
- OS Version: W10 21H2

**Comment by Dromantor** [comment] 2022-05-18 12:45
#149535 might be related, at least the outcome is the same.

**Comment by lszomoru** [comment] 2022-12-12 15:24
Closing this as duplicate of https://github.com/microsoft/vscode/issues/147373.

**Closed by lszomoru** 2022-12-12 15:24 UTC
Labels: bug, git
