### ISSUE TITLE
Holding Alt-(key) on Sub-Menu item doesn't trigger that Command.

### ISSUE THREAD

**Issue by JoelViney** [Microsoft/vscode#27106] opened 2017-05-23 02:27 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open Visual Studio Code
2. Hold Down the 'Alt' key
3. Press the 'F' (while still holding down the 'Alt' key)
    The File menu will appear at the top right of your screen
4. Press 'N' (while still holding down the 'Alt' key)
   Nothing happens.

Expected Behaviour: A new file is added to your solution.
The first item in the File menu is 'New File' with the letter N underlined. The underline indicates that it can be activated by pressing the key. The standard approach is to also allow the 'Alt' key to be pressed at the same time.

This should work if the 'Alt' key is still being pressed as this is the behaviour of most editors in windows e.g. Notepad, Word, Visual Studio...

**Comment by lucasshawn** [comment] 2017-06-08 18:16
I hope to see this fixed.  20yrs of muscle memory in VS has me quickly hitting Alt+F, S.  Unfortunately in VSCode if I don't release Alt before S is pressed it doesn't accept the sequence.  VS (on windows) supports S with or without ALT key still being pressed.

**Comment by WereDev** [comment] 2017-08-04 15:07
I am having a similar issue though it seems intermittent.  Alt+key not working for any of the menus.  Didn't work one day.  Worked for me yesterday.  Not working today.

**Comment by monk-time** [comment] 2017-09-13 03:00
The same issue as in the comment (as a closed issue) above. Alt+key randomly stopped working for me today. Restarting VSCode doesn't help. Haven't tried restarting the program yet.

Seems to be related to https://github.com/Microsoft/vscode/issues/10525 (which is also closed for some reason).

**Comment by monk-time** [comment] 2017-09-13 03:03
@WereDev, I figured it out: it was caused by Scroll Lock: https://github.com/Microsoft/vscode/issues/19011

**Comment by WereDev** [comment] 2017-09-13 14:10
@monk-time , confirmed!  I tested it out and it replicated my issue beautifully!  I guess I just had a couple fat finger days...

**Comment by fider** [comment] 2018-04-30 19:34
Same here.
While it still works in other applications in VS Code it is not working.

**Restart of Windows helped :)**

**Comment by et304383** [comment] 2018-05-31 15:07
At least Alt+F opens the file menu for you.  Doesn't for me on Linux.

Apparently they decided this just wasn't an issue: #10525

**Comment by bpasero** [comment] 2018-08-17 06:17
Duplicate of #52935

**Closed by bpasero** 2018-08-17 06:17 UTC
Labels: accessibility, electron, upstream, workbench-menu
