### ISSUE TITLE
Cmd+click jump to js arrow function definition show misleading scroll area.

### ISSUE THREAD

**Issue by FaiChou** [Microsoft/vscode#54367] opened 2018-07-16 04:21 UTC
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: macOS 10.13.6 (17G65)

Steps to Reproduce:

1. command+click arrow function usage
2. jump to this function definition

Does this issue occur when all extensions are disabled?: Yes

![vscode](https://ws4.sinaimg.cn/large/006tNc79ly1ftawcky8psj31kw0obn7n.jpg)

Always tips me 2 definition, but in real only one. 

Each time I click `Esc` to close the nested scroll view. It's a unnecessary step.

How to disable it or how is it a real bug about js arrow function?

**Comment by mjbvz** [comment] 2018-07-16 17:19
Duplicate of #51918

**Closed by mjbvz** 2018-07-16 17:19 UTC
Labels: javascript
