### ISSUE TITLE
Back/Forward mouse button doesn't work anymore

### ISSUE THREAD

**Issue by vystepanenko** [microsoft/vscode#76965] opened 2019-07-09 10:01 UTC
Issue Type: <b>Bug</b>

After upgrade to 1.36.0 back/forward mouse buttons stopped working for "back"(workbench.actions.navigateBack) and "forward" (workbench.actions.navigateForward) commands.  ALT+LeftArrow/RightArrow for this commands working fine

In 1.35.0 everything was fine.
In all other applications(like Chrome) also everything is well

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.3
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.8.2
vscode-npm-script|eg2|0.3.8
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-cs-fixer|jun|0.1.119
dotenv|mik|1.0.1
vscode-deploy-reloaded|mkl|0.87.2
vscode-apache|mrm|1.2.0
php-docblocker|nei|2.0.1
snippet-creator|nik|0.0.5
vetur|oct|0.21.1
laravel-blade|one|1.20.0
laravel5-snippets|one|1.7.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.8.0
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.25
vscode-fileutils|sle|2.14.5
php-docblock-generator|vin|0.0.1
vscode-import-cost|wix|2.12.0
ascii-unicode-escape|yar|0.1.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2019-07-09 10:31
/duplicate of #71318 and will be fixed in upcoming recovery release

**Closed** 2019-07-09 17:57 UTC
Labels: *duplicate
