### ISSUE TITLE
 terminal.integrated.shellIntegration.enabled error bash: _direnv_hook;printf: command not found

### ISSUE THREAD

**Issue by Links2004** [microsoft/vscode#144552] opened 2022-03-07 07:45 UTC
Issue Type: <b>Bug</b>

Steps:

enable:
`terminal.integrated.shellIntegration.enabled`
using bash + direnv 

results in:

```
bash: _direnv_hook;printf: command not found
```
for each command

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.15.25-1-MANJARO
Restricted Mode: No

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.9.1
vscode-eclipse-keybindings|alp|0.14.0
swagger-viewer|Arj|3.1.2
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
gitlens|eam|12.0.1
gitkraken-authentication|git|1.0.3
go|gol|0.31.1
terraform|has|2.20.0
vscode-test-explorer|hbe|2.21.1
vscode-python-test-adapter|lit|0.7.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.20.0
vscode-kubernetes-tools|ms-|1.3.6
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.0
jupyter|ms-|2022.2.1020642448
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.224.2
cpptools|ms-|1.8.4
test-adapter-converter|ms-|0.1.5
ansible|red|0.8.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.4.0
vscode-coverage-gutters|rya|2.9.1
jinjahtml|sam|0.17.0
markdown-preview-enhanced|shd|0.6.2

</details>

**Comment by meganrogge** [comment] 2022-03-07 18:03
where is the `printf` coming from? 

we think the problem is here https://github.com/direnv/direnv/blob/cb5222442cb9804b1574954999f6073cc636eff0/internal/cmd/shell_bash.go#L19

**Comment by Links2004** [comment] 2022-03-08 07:30
with out direnv in Linux terminal
```
$ echo ${PROMPT_COMMAND}
printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
```

in vscode terminal in now have a `""` at the beginning of the PS1:
```
""[test@fubar]~/ $
```

```
$ echo ${PROMPT_COMMAND}
prompt_cmd_original
$ echo ${prompt_cmd_original}

""
```

```
$ direnv hook bash

_direnv_hook() {
  local previous_exit_status=$?;
  trap -- '' SIGINT;
  eval "$("/usr/bin/direnv" export bash)";
  trap - SIGINT;
  return $previous_exit_status;
};
if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
```

running  `eval "$(direnv hook bash)"` later in the terminal and not the .bashrc
keeps the `""` at the beginning and direnv is working fine.

sounds to me like the `prompt_cmd_original` is not calling the original PROMPT_COMMAND like bash is doing it internally.

**Comment by meganrogge** [comment] 2022-03-08 20:24
When I set `PROMPT_COMMAND` within my `.bashrc`, it runs without a problem, so believe `prompt_cmd_original` is calling the original `PROMPT_COMMAND` correctly.

**Comment by thijsputman** [comment] 2022-03-09 18:48
The problem appears to occur when there are multiple "entries" on `PROMPT_COMMAND`, like so:

```shell
echo $PROMPT_COMMAND
_pyenv_virtualenv_hook;_direnv_hook;_powerline_ps1
```

Removing all but one (e.g. setting it to just `_powerline_ps1`) makes the issue disappear (and the powerline reappear 😉).

The empty `""` reported in both this issue and https://github.com/microsoft/vscode/issues/144706 appears to be the result of using `PROMPT_COMMAND` to set the title of the terminal window:

```shell
PROMPT_COMMAND='_powerline_ps1; echo -ne "\033]0;${debian_chroot:+($debian_chroot)}${USER}@${HOSTNAME}: $(dirs +0)\007"'
```

I had the above in my `.bashrc` which caused `""` to appear (once everything else was removed from `PROMPT_COMMAND`).

Moving the escape sequence into `PS1` (where I guess it's supposed to go?) prevents `""` from appearing.

If you search around on "how to set the terminal title via bash", most answers do point to using `PROMPT_COMMAND` though. I guess this issue will have to be fixed on VS Code's end as many people will have this in their Bash settings...

**Closed** 2022-03-12 01:34 UTC
Labels: bug, confirmed, terminal-shell-integration

**Comment by roblourens** [comment] 2022-03-25 20:55
Setting `$PROMPT_COMMAND` in my environment doesn't do anything - what's the difference between that and PS1?

**Comment by Tyriar** [comment] 2022-03-28 13:40
@roblourens you can set $PROMPT_COMMAND to a function and that will run to set your $PS1 dynamically. Here's one I use sometimes: https://github.com/Tyriar/dotfiles/blob/118b6e8bde4525431b93532277437669a430de5c/data/bash/.bash_prompt#L3-L22
