### ISSUE TITLE
[Find in Files] Search results disappear after viewed on editor ("\r\n", regex enabled)

### ISSUE THREAD

**Issue by AndreCunha1** [microsoft/vscode#122810] opened 2021-05-02 13:10 UTC
Issue Type: <b>Bug</b>

**Reproduction steps:**
1. Open a folder with multiple CRLF (i.e. `\r\n`) EOL files
2. Search for `\r\n` through the "Find in Files" input with "Use Regular Expression" enabled
3. Click on a search result for each file, so that the editor opens for viewing the matches
4. When clicking on a search result in a different file than current one opened in the editor, **previous search result disappears from the search result list** even without touching the files 🐛

https://user-images.githubusercontent.com/3430106/116812941-a098c800-ab51-11eb-8860-b941874b089b.mp4

**Additional information:**
- Issue seems to happen because **a different search behavior is used for opened files** instead of the "Find in Files" one
- Tested on a clean install (no extensions, default settings)
- Example folder and files for testing: [TEST folder.zip](https://github.com/microsoft/vscode/files/6411319/TEST.folder.zip)

**Potentially related issues/causes:**
- #18817, in this comment: https://github.com/microsoft/vscode/issues/18817#issuecomment-274874122
> [...] pushed a change that makes it that \n matches the End-Of-Line sequence, regardless if the file is LF or CRLF [...] There is a side-effect, that \r will never match anything
- #19225, in this comment: https://github.com/microsoft/vscode/issues/19225#issuecomment-274873135
> The change is that now:
> - \r will not match anything, ever, even in files with CRLF
> - \n will match the End-Of-Line, both in files with LF and in files with CRLF
- #31449, in this comment: https://github.com/microsoft/vscode/issues/31449#issuecomment-339599065
> In the find widget, it is possible to target the EOL sequence (\n or \r\n) in a file via \n in regex mode. It is not possible to target only the \r in a \r\n EOL sequence.

**Rant:**
- I often bump into discrepancies between "Find in Files" and editor's "Find", which is **extremely** frustrating. I for one wouldn't care at all for a much worse performance if that is the price for a reliable and consistent behavior (so that I can actually use it instead of not using it at all in favor of different search tools that work as expected), but maybe that is just my opinion. Maybe we could have a setting to opt-in for same behavior in both searches? 🙃

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
vstes627:30244334
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by roblourens** [comment] 2021-05-03 18:12
You did a good job of following the history, I would call it a duplicate of #31449. 

@rebornix since this isn't the first time it's come up, what would you think about a workaround like having the editor strip `\r`, or show a warning when you include `\r`, or something like that?

I get the rant, I think the "out" for this is the long uncompleted search provider API that would let someone plug in a (much slower) search implementation that uses the same JS regex engine as the editor. For this specific case, you can match `\r\n` with just `\n` in both types of search, if that helps, but yeah you get different behavior when including `\r`.

**Comment by AndreCunha1** [comment] 2021-05-03 23:37
> I would call it a duplicate of #31449.

@roblourens although I surely got carried away while further describing related issues (bad idea), the initial reproduction steps provided do not seem like a duplicate. The cause seems duplicate, yes, but the reported issue seems new. Check only the first 10 seconds of the recording (what follows it is probably only helpful to better understand the cause).

I mean, it does not seem intended that search results disappear by just clicking/reviewing them. Imagine working with search results where some of them simply disappear without actually editing the original match in them: it would quite likely cause you to inadvertently skip/miss some files even though they still contain matches of the original search query in them (which is exactly what happened to me and made me open this issue).

PS: I am just writing this because I fear the dreaded "closed as duplicate" 😄

**Comment by roblourens** [comment] 2021-05-04 02:15
When you open a file, we refresh the search results from the editor, and the underlying issue is that the workspace text search is different from the editor's search, where you can't search for `\r`.

**Comment by YouenZeng** [comment] 2021-05-18 08:43
I use VSC to replace content in 30+ files, after operation I found 3 files not replaced just because I opened it in editor. This really confused me

**Comment by andreamah** [comment] 2022-12-15 20:25
We likely aren't going to support replacing `\r` because a lot of our normalization involves inserting `\r` and it would be a large-ish overhaul to support it well.

**Closed by andreamah** 2022-12-15 20:25 UTC
Labels: search, under-discussion

**Comment by AndreCunha1** [comment] 2022-12-26 14:53
@andreamah If this issue cannot be easily fixed/enhanced, could we at least warn users in some way? I mean, if we know our limitations and unhandled edge-cases, then we could warn users whenever they are going to be affected by one of them.

For example, in the situation that @YouenZeng shared, depending on the replacement mode and inputs, we could show a confirmation warning stating something like "opened files might not be replaced as expected" before the actual replacement takes place. It is a bit unfortunate but way better than silently working in unexpected ways.

PS: note that the initially reported issue (i.e. search results disappearing by simply viewing them) has nothing to do with replacements, so I am confused with it being the reason for the "wont-fix". If we also cannot improve this other behavior, then how could we explain it to users? It feels very abnormal.
