### ISSUE TITLE
Expose API to provide expandable message in notifications

### ISSUE THREAD

**Issue by nelango** [microsoft/vscode#126526] opened 2021-06-16 20:32 UTC
Expose API to provide expandable message in notifications (`showInformationMessage` / `showWarningMessage` / `showErrorMessage` ). The API could be something like: `showInformationMessage(summaryMessage: string, fullMessage: string, ...items: string[])`

Currently, if actions are present in these notification messages, the view is automatically expanded. Instead:
- minimize it and display a summary message by default
- make it expandable and display the full message exposed through API when expanded

**Comment by bpasero** [comment] 2021-06-17 06:19
//cc @jrieken

**Comment by jrieken** [comment] 2021-06-17 06:50
dupe of https://github.com/microsoft/vscode/issues/125750?

**Comment by bpasero** [comment] 2021-06-17 06:56
Yeah maybe, if we end up implementing the new `detail` option like that for notifications, an extension could use `message` for the brief variant and add additional content to `details`. Let's move into that issue, @nelango maybe comment there.

**Closed** 2021-06-17 06:57 UTC
Labels: *duplicate, api, feature-request, workbench-notifications
