### ISSUE TITLE
String color formatting error in PHP strings starting with "SELECT"

### ISSUE THREAD

**Issue by MikeTodd** [microsoft/vscode#80810] opened 2019-09-12 17:05 UTC
**Steps to Reproduce**

Type the following code into a PHP editor:

```
<?php
$a = 5;
$test = "SELECT * FROM data WHERE data_key = 'id-".intval($a)."'";
```

**Expected**: intval($a) would not be formatted as being part of the string.

**Actual result**: intval($a) is color coded as if it were a part of the string.

**Additional notes**

If you remove the "SELECT" from that string or make it lower case, the color coding works correctly.

This behavior also occurs if you begin the string with INSERT in upper case.

The color coding is also correct if you remove the first single-quote, or if you escape it with a slash. Escaping it with a slash would result in a the string actually containing a backslash and then a single quote though.

**Comment by roblourens** [comment] 2019-09-15 21:58
Dupe of https://github.com/microsoft/vscode/issues/44290

**Closed by roblourens** 2019-09-15 21:58 UTC
