### ISSUE TITLE
Extension host terminated unexpectedly - on a Mac laptop with no extensions installed

### ISSUE THREAD

**Issue by ZoCodes** [microsoft/vscode#127571] opened 2021-06-29 21:38 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Mac 10.10
- OS Version: El Capitan 10.11.6 (15G22010)

Steps to Reproduce:

1. Open VS code in Mac and open up a folder mine has index.html  src/style.css and imagesextensions
2. No extensions are installed
3.
![Screen Shot 2021-06-29 at 22 37 24](https://user-images.githubusercontent.com/17452240/123870698-a11fc600-d92a-11eb-82c0-ad8d768a79db.png)

![Screen Shot 2021-06-29 at 22 37 05](https://user-images.githubusercontent.com/17452240/123870696-9ebd6c00-d92a-11eb-93fd-11aa08b3eee2.png)

**Comment by ZoCodes** [comment] 2021-06-29 21:46
**After a hard delete using:** 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/

rm -rf ~/.vscode*

**This is the console code**

electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
console.ts:137 [Extension Host] (node:1064) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
b @ console.ts:137
localProcessExtensionHost.ts:272 Extension Host
localProcessExtensionHost.ts:273 dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np  Referenced from: /Users/zoeblogg/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylibdyld: Symbol not found: _pthread_chdir_np  Referenced from: /Users/zoeblogg/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylib
abstractExtensionService.ts:621 Extension host terminated unexpectedly. Code:  null  Signal:  SIGTRAP
_onExtensionHostCrashed @ abstractExtensionService.ts:621
log.ts:296   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git, ms-vscode.js-debug, vscode.github-authentication
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
log.ts:296   ERR Error: No authentication provider 'github' is currently registered.
    at L.getSessions (authenticationService.ts:720)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async bi.getAccounts (userDataSyncWorkbenchService.ts:209)
    at async bi.update (userDataSyncWorkbenchService.ts:194)
    at async bi.initialize (userDataSyncWorkbenchService.ts:168)
    at async bi.waitAndInitialize (userDataSyncWorkbenchService.ts:149)
log.ts:290  WARN Settings Sync: Accounts are not initialized

![Uploading Screen Shot 2021-06-29 at 22.45.50.png…]()

**Comment by alexdima** [comment] 2021-07-02 13:55
Duplicate of https://github.com/microsoft/vscode/issues/125989 . The fix will be available in our upcoming 1.58 release or is already available in our [Insiders channel](https://code.visualstudio.com/insiders/)

**Closed by alexdima** 2021-07-02 13:55 UTC
