### ISSUE TITLE
Implement Line scrolling like in Visual Studio 2019

### ISSUE THREAD

**Issue by hahoyer** [microsoft/vscode#111734] opened 2020-12-02 11:55 UTC
If you use the Line-Scroll function, the selected line is preserved - even if it leaves the visible area by scrolling. This is quite annoying and I don't know any editor that does it that way. The other editors make sure that the selected line always stays visible by moving it accordingly when it reaches the top or bottom of the screen. This results in a much better usability. As an example you can have a look at it in Visual Studio 2019.

**Comment by alexdima** [comment] 2020-12-02 12:54
Duplicate of #91867 , #59247

---

You can install the VS Keymap extension or you can use the `editorScroll` command in your `keybindings.json`:

e.g.

```
{
	"key": "ctrl+up",
	"when": "editorTextFocus",
	"command": "editorScroll",
	"args": {
		"to": "up", // 'up', 'down'
		"by": "line", // 'line', 'wrappedLine', 'page', 'halfPage'
		"value": 1, // number of units to move
		"revealCursor": true
	}
}
```

**Closed by alexdima** 2020-12-02 12:54 UTC
