### ISSUE TITLE
Markdown Preview links to local files are broken unless they are another markdown file

### ISSUE THREAD

**Issue by DavidMulder0** [microsoft/vscode#112459] opened 2020-12-14 11:07 UTC
# Steps to Reproduce:

1. Create a markdown file `README.md` and a second file called `test.js` 
2. In the markdown file include `[link](./test.js)`
3. (Ctrl)+click the link in the editor and observe how it opens `test.js`
4. Open the Markdown preview for `README.md`
5. Click the link in the preview

![vscode-md-link](https://user-images.githubusercontent.com/20395438/102074194-b016af00-3e04-11eb-97e4-74035aaf4c4d.gif)

Bug: Currently nothing happens. The link looks like it was clicked, but actually nothing happens. It doesn't show an error, it doesn't indicate that something is happening, just nothing.

# Expected result:
The same behavior should happen as when the link is clicked in the code editor: The linked file should open

---

- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19041

Does this issue occur when all extensions are disabled?: Yes

**Comment by DavidMulder0** [comment] 2020-12-14 14:16
Beyond just the general bugginess of 'here is something that looks like a link, but doesn't behave like a link' just some contextual justification: 

`README.md` files often contain explanations for new developers to a project highlighting important files and general structural information. Here is a clean demonstration of this behavior on Github: https://github.com/DavidMulder0/github-markdown-render-test/ .

**Comment by mjbvz** [comment] 2020-12-15 00:24
Works for me on Mac and WIndows. Please share more specific steps to reproduce this. Do you have a workspace open for example?

**Comment by ArturoDent** [comment] 2020-12-15 03:50
Works for me too on W10 in a workspace.  Fails silently if the relative path to the link is no good - but then it shouldn't open from the non-preview `READ.md`?

**Comment by DavidMulder0** [comment] 2020-12-15 07:48
@mjbvz 

I have tried this both with and without a workspace, but just tried it on my personal computer and there it works as well... Took a recording to show as much as possible context, but honestly, my corporate work laptop is painfully atypical, so I am just going to assume it's just a local problem if it can't be reproduced. Thank you for your work and effort.

![more-context](https://user-images.githubusercontent.com/20395438/102184150-4bfcf500-3eaf-11eb-9425-a1c3b4240ce1.gif)

**Comment by mjbvz** [comment] 2020-12-16 06:37
Thanks for testing. Please let me know if you are able to track down what seems to cause this problem for you.

For now though, I'm going to close this issue as not reproducible until we get more information

**Closed by mjbvz** 2020-12-16 06:37 UTC
Labels: markdown, needs more info
