### ISSUE TITLE
Warnings for long commit messages does not work anymore

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#24104] opened 2017-04-06 17:18 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.11.0|
|prettify-json|mohsen1|0.0.3|
|final-newline|samverschueren|0.3.2|
|join-lines|wmaurer|0.2.2|
|local-history|xyz|1.1.1|;

---
The Git UI used to show a warning when the commit summary exceeded 50 or so characters. This warning is gone and I can't find a config option.

Steps to Reproduce:

1. Enter a commit message with more than 50 characters in the first line.

**Comment by jsynowiec** [comment] 2017-04-06 18:13
Probably duplicate of #23412, see #21144

**Comment by chrmarti** [comment] 2017-04-06 18:53
Tracking with #21144

**Closed by chrmarti** 2017-04-06 18:53 UTC
