### ISSUE TITLE
Broken shortcuts since 1.75 (mac)

### ISSUE THREAD

**Issue by pibenett** [microsoft/vscode#173289] opened 2023-02-03 11:58 UTC
Type: <b>Bug</b>

Hello

My shortcuts are broken since the last update (1.75) and when I try to set them up again I have a weird behavior. For example if I add the key bind "cmd + / " for the "comment line" command everything seems to be working fine until I validate the input with enter and I see "cmd + F3" as shortcut. I try many different bindings and it always end with a totally differnt input.

It's very problematic for my productivity so if you could solve this asap it would be very nice.

Thank you for your understanding

Regards

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 8, 21|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id c1416dfb-36d1-40eb-b1db-628078970245|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
lwccodemate|aru|1.0.4
multi-cursor-case-preserve|Car|1.0.5
npm-intellisense|chr|1.4.4
apex-pmd|chu|0.5.9
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
vscode-salesforce-toolkit|dro|1.3.0
gitlens|eam|13.2.0
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|9.10.4
pine-script-syntax-highlighter|ex-|1.0.5
lana|Fin|1.5.2
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
salesforce-code-snippets|Hel|1.1.0
inline-parameters|lia|0.2.1
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.23.3
vscode-language-pack-fr|MS-|1.75.2023020109
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.0
azure-account|ms-|0.11.3
material-icon-theme|PKi|4.23.1
vscode-xml|red|0.24.0
LiveServer|rit|5.7.9
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode-apex|sal|56.16.0
salesforcedx-vscode-apex-debugger|sal|56.16.0
salesforcedx-vscode-apex-replay-debugger|sal|56.16.0
salesforcedx-vscode-core|sal|56.16.0
salesforcedx-vscode-expanded|sal|56.16.0
salesforcedx-vscode-lightning|sal|56.16.0
salesforcedx-vscode-lwc|sal|56.16.0
salesforcedx-vscode-soql|sal|56.16.0
salesforcedx-vscode-visualforce|sal|56.16.0
sfdx-package-xml-generator|Vig|2.0.9
fig|wit|0.0.7
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30657576
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982
vscsb:30628654

```

</details>

**Comment by sliedes** [comment] 2023-02-03 12:57
This same happens on Linux for me. I had some shortcuts set to alt+§, which is the key above TAB on my keyboard (and they used to wokr). Now those shortcuts had been reset. When I tried to restore it, the shortcut entry window shows it as "alt+[Backquote]", which it may have done previously (although backquote is in a very different place on my keyboard). After pressing enter, the binding as shown in the Keybinding column is "Alt + F1", which is different both from the original and what I entered.

**Comment by sliedes** [comment] 2023-02-03 13:04
Seemingly probably the same issue: #170578 #170503 and maybe #170052.

**Comment by yukulele** [comment] 2023-02-03 19:54
https://github.com/microsoft/vscode/issues/173325

**Comment by alexdima** [comment] 2023-02-05 19:41
Duplicate of #173325

**Closed by alexdima** 2023-02-05 19:41 UTC
Labels: new release
