### ISSUE TITLE
Hit and miss showing selected object on right bar

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#19679] opened 2017-02-01 16:25 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|numbered-bookmarks|alefragnani|0.6.0|
|code-gnu-global|austin|0.2.1|
|one-monokai|azemoh|0.2.4|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.6.7|
|findfile|HastenS|0.0.4|
|rubyblue-theme|hirofumii|1.0.2|
|format-indent|Kasik96|1.3.0|
|cpptools|ms-vscode|0.10.0|
|autotrim|NathanRidley|1.0.6|
|theme-earlytorise|PasqNet|0.0.9|
|seti-icons|qinjia|0.1.3|
|code-spell-checker|streetsidesoftware|0.15.1|
|polscript|vitorfdl|2.1.0|

---

Steps to Reproduce:

.js files only.

When you double click JQuery code to highlight it, some things like variables will show as white squares of reference points throughout your page.  That's what is working.

This isn't consistent for other things that aren't variables.

 $('#item1_' + variable).prop('disabled', true);
 $('#item2_' + variable).prop('disabled', true);
 $('#item3_' + variable).prop('disabled', true);
 $('#item1_' + variable).prop('disabled', true);

1.Double click variable and it highlights the scroll-bar with the white reference place markers.
2.Double click item1_, nothing shows on the scroll bar.
3.Double click .prop nothing shows on the scroll bar.
4.Double click disable nothing shows on the scroll bar.
5. Double click true nothing shows on the scroll bar.

**Comment by conceptualspace** [comment] 2017-02-03 23:34
see also #16042 (possible duplicate)

its been driving me nuts for a while :(

**Comment by mjbvz** [comment] 2017-03-08 02:09
Thanks. Closing as a duplicate of #16042

**Closed by mjbvz** 2017-03-08 02:09 UTC
Labels: duplicate, javascript, typescript
