### ISSUE TITLE
Wobbling debug button only when font-size is in specific range

### ISSUE THREAD

**Issue by Pika-Pool** [microsoft/vscode#126871] opened 2021-06-22 03:15 UTC
Issue Type: <b>Bug</b>

- disable all extensions
- disable all font related settings to vscode default
- change font-size to the range `>=14.5 <=15.1`(I guess this might be specific to my system)
- create a package.json file and add a scripts field to get the "Debug" button
- type anything and notice the "Debug" option

gif: ![gif for Wobbling debug button only when font-size is in specific range](https://user-images.githubusercontent.com/33688622/122859244-52c26400-d339-11eb-8b07-e57e2ce71a2d.gif)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isidorn** [comment] 2021-06-22 15:23
I think this button is provided by js-debug thus forwarding to @connor4312 
However also assigning to @jrieken for code lens, maybe there is a duplicate of this?

**Closed** 2021-06-22 16:00 UTC
Labels: *duplicate, code-lens

**Comment by Pika-Pool** [comment] 2021-06-23 13:35
Which one is the original issue? Could someone please point me to it?
