### ISSUE TITLE
Auto reveal has stopped working in latest version of vs code

### ISSUE THREAD

**Issue by scssyworks** [Microsoft/vscode#68840] opened 2019-02-16 14:15 UTC
- VSCode Version: 1.31.1
- OS Version: 10.13.6 (Mac OSX High Sierra)

### Steps to Reproduce:

1. Click on an opened file tab
2. Check if the file has been automatically revealed in file explorer

Does this issue occur when all extensions are disabled?: Yes

### Expected Behavior:
File should automatically reveal in file explorer

### Observed Behavior:
File is no longer automatically revealed. You need to disable auto reveal and then re-enable it to make it work.

**Comment by isidorn** [comment] 2019-02-18 14:55
I can not reproduce this. Can you repro with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by eddiemf** [comment] 2019-02-19 10:55
I can confirm the problem happens only when executing some kind of script on integrated terminal.

### Steps to Reproduce:
1. Click on an opened file tab (auto reveal should work now)
2. Execute something like `npm start` on terminal
3. Try switching tabs again (shoudn't work now)
4. Open and close settings file (so it refreshes settings)
5. Try switching tabs again (should work properly now)

This is very annoying and started after the last update (1.31.1 I guess)

**Comment by isidorn** [comment] 2019-02-19 16:53
If you F1 > developer tools > open console do you see some errors?
Sounds like a duplicate of https://github.com/Microsoft/vscode/issues/68627

If you do not see errors in console let me know and I can reopen this

**Closed by isidorn** 2019-02-19 16:53 UTC
Labels: needs more info

**Comment by Etchelon** [comment] 2019-02-28 13:40
I do:

  ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at i.e.getDataNode (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1037:266)
    at i.<anonymous> (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1034:703)
    at file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:33:935
    at Object.next (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:34:33)
    at file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:33:160
    at new Promise (<anonymous>)
    at i (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:32:952)
    at i.e.expand (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1034:342)
    at Array.<anonymous> (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5627:417)
    at t (file:///C:/Users/AndreaBertoldo/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:105:891)

I also have to disable and reenable autoreveal from settings to make it work again.
