### ISSUE TITLE
annoying indentation bug while writing html in a php file

### ISSUE THREAD

**Issue by saharso** [microsoft/vscode#32871] opened 2017-08-21 08:09 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

I have auto close tags toggled off in my preference configurations.

whenever i try to manually close an html tag, the closing tag ignore indentation and jumps to the left, which forces me to manually indent whenever I am trying to close a tag.

This is VERY ANNOYING and detrimental to my word flow and concentration. It started to happen after the next to last update.

Steps to Reproduce:

1.
2.

**Comment by nickysixer** [comment] 2017-10-16 02:41
This is such an awful bug that has me rethinking my use of VS Code for PHP dev. When should we expect this to be fixed?

**Comment by RiFi2k** [comment] 2018-07-24 13:16
I made this because I was annoyed at nested HTML in PHP, this should format based on whatever native settings you have for html.format and editor format on save/type [Format HTML in PHP](https://marketplace.visualstudio.com/items?itemName=rifi2k.format-html-in-php)

**Comment by connor4312** [comment] 2019-10-11 17:59
There are several outstanding bugs around indentation in PHP, but this one no longer appears to reproduce.

![Kapture 2019-10-11 at 10 58 23](https://user-images.githubusercontent.com/2230985/66673772-270b5300-ec16-11e9-89ca-d56cff4e58f7.gif)

**Comment by connor4312** [comment] 2019-10-11 18:05
Apologies, some more details --

This appears to be an interaction between the HTML language server and PHP. Opening a PHP file in VS Code and then trying to reproduce the issue won't yield results, but if you open an HTML file (or change the file to HTML and back again), then this issue occurs.

**Comment by rebornix** [comment] 2020-11-03 00:59
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment. As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like https://github.com/microsoft/vscode/issues/19847.

**Closed by rebornix** 2020-11-03 00:59 UTC
Labels: bug, editor-autoindent, html, php
