### ISSUE TITLE
Extensions are randomly uninstalling 

### ISSUE THREAD

**Issue by username1001** [Microsoft/vscode#45016] opened 2018-03-04 16:15 UTC
- VSCode Version: 1.19.3 (and the previous two versions, I think)
- OS Version: Ubuntu 16.04

My extensions are occasionally uninstalling randomly. The most recent being Bracket Pair Colorizer. I noticed the brackets weren't colorizing, and I knew immediately the extension must have uninstalled, as it's happened before with Live Server, and Prettier. So, I checked the extensions, and indeed, it was uninstalled. 

I just looked at my extensions, and once again, Prettier and Live Server are uninstalled. :/ 

Thanks! 

EDIT: After I reinstalled Prettier, Bracket Pair Colorizer uninstalled, again. It happened after clicking "reload" after reinstalling Prettier.

**Comment by zoffyzhang** [comment] 2018-03-05 01:46
my Prettier extension was automatically uninstalled too

VSCode Version: 1.20.1
OS Version: win10

**Comment by sandy081** [comment] 2018-03-13 07:25
Fixed in 1.21 

Duplicate of https://github.com/Microsoft/vscode/issues/44471

**Closed** 2018-03-13 07:25 UTC
Labels: *duplicate, bug, extensions
