### ISSUE TITLE
editor.rulers rendering vertical ruler inconsistently with expectations

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#22801] opened 2017-03-17 15:51 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-icons|robertohuertasm|7.3.0|:

---

I have the editor set to enable a vertical rule at the 140th character.

`"editor.rulers": [140]`

The expectation I have is that it shall always render the ruler.

I am not seeing the ruler show when I have a single file open (no split pane) and the side bar collapsed.
See the first image.

But I always see it with the side bar open. See image 2.

However, that behavior changes when splitting VS Code into two panes. The ruler only shows on the right pane.

This changes even further when reducing the ruler to 80 characters. All of the problems go away.
I thought at first it was being hidden behind the mini map, but when in full resolution (1920x1080) and having a single file. There is more than enough space to render the ruler as it renders just fine with the side bar open.

It has no problems rendering in a single pane or both panes with something smaller like 80. The problems seem to arise when having the ruler set to something larger like 140.

![no_ruler1](https://cloud.githubusercontent.com/assets/2420177/24051582/8670efa2-0b00-11e7-962f-529fb0004cb5.png)

![ruler1](https://cloud.githubusercontent.com/assets/2420177/24051557/6f273e3c-0b00-11e7-9f9d-e0e9f6f7cf27.png)

**Comment by zelein** [comment] 2017-03-20 13:40
I've noticed the visible changes as well. Like when in split pane mode and resizing a pane. The ruler will re-render, and sometimes it will just disappear if you stop the window at the right pixel.

**Comment by alexandrudima** [comment] 2017-03-27 08:28
@nevinera @zelein 
Do you use zooming?

**Comment by nevinera** [comment] 2017-03-27 09:38
Not to my knowledge. Definitely not while producing the bug - I was purely pressing arrow keys, one at a time.

**Comment by alexandrudima** [comment] 2017-03-27 09:45
What I mean: Can you reproduce when setting `"window.zoomLevel": 0` in your settings?

**Comment by nevinera** [comment] 2017-03-27 11:45
Just got to work, and I did have zoomLevel set to `-1`; setting it to zero causes the rules to render as expected.

**Comment by alexandrudima** [comment] 2017-03-27 14:53
Duplicate of #9634. I can only recommend to never use `window.zoomLevel` unless you are projecting to an audience, and use `editor.fontSize` instead.

**Closed by alexandrudima** 2017-03-27 14:53 UTC
Labels: bug, electron, upstream, zoom

**Comment by zelein** [comment] 2017-03-29 18:02
Thanks for alerting me to the duplicate issue. All of my complaints go away when setting zoomLevel back to 0. Unfortunately, setting the fontSize is not good enough as I find the window to be a bit too large at teh default zoom.
