### ISSUE TITLE
Cannot press `return` on search results to go to result inside the 'Search Editor'

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#179877] opened 2023-04-13 14:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.78.0-insider
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Open 'Search Editor'

This one:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/6391776/231783714-a5ee1f38-a24f-4b6f-aab0-c85901fb85d8.png">
 
2. Do a search then hover the cursor line over a line you want to go to.

Like below for example:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/6391776/231783868-68ce7bf0-933a-482d-8467-0261522623e2.png">

Then press `return` key.

It should go where the line is in vscode new tab but it does not. This worked for me before I updated to latest vscode-insiders version. So this is a regression.

Please fix it.

**Comment by nikitavoloboev** [comment] 2023-04-13 14:05
I cannot even double click on the line. Before if I double clicked it would also go the result of the search. Perhaps something is breaking it on my side?

**Comment by andreamah** [comment] 2023-04-13 16:09
I think you have a custom keybinding for return to open the result. Do you know what command it runs when you use return? Very likely a duplicate of https://github.com/microsoft/vscode/issues/179590

**Comment by andreamah** [comment] 2023-04-13 17:16
This should be a duplicate of https://github.com/microsoft/vscode/issues/179590 then.

**Closed** 2023-04-13 17:16 UTC
Labels: info-needed, *duplicate
