### ISSUE TITLE
search function with files to include only show results from currently opened files instead of the whole folder

### ISSUE THREAD

**Issue by dapidmini** [Microsoft/vscode#32606] opened 2017-08-16 04:07 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
vscode-html-css|ecm|0.1.7
prettier-vscode|esb|0.22.1
php-intellisense|fel|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3

---

Steps to Reproduce:

1. open a folder in vscode
2. open file1.php, file2.php
2. search for 'sometext'
3. put '**/*.php' in files to include
4. only get search results from file1.php and file2.php although 'sometext' exists in file3.php

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-08-16 04:56
Duplicate of #32325, fix will be out in a day or two. But the `**` is technically redundant, `*.php` should give the results you expect.

**Closed** 2017-08-16 04:56 UTC
Labels: new release, php
