### ISSUE TITLE
Performance issue trying to handle JSON files >500kb

### ISSUE THREAD

**Issue by gmaggess** [Microsoft/vscode#17742] opened 2016-12-22 18:27 UTC
- VSCode Version: 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281)
- OS Version: MacOS Sierra

Steps to Reproduce:
1. Open JSON file of reasonable size >500k
2. Scroll file up and down or try to fold code.

**Comment by aeschli** [comment] 2017-01-10 02:54
I'm not able to reproduce that. I created a file with 240000 lines and was still able to work with it nicely.
Can you run VSCode without any extensions and see if a extension is causing the problem?
Maybe this is a duplicate of #17859.

**Closed** 2017-01-11 04:37 UTC
