### ISSUE TITLE
Terminal in Editor rendering errors and disposed errors

### ISSUE THREAD

**Issue by weikinhuang** [microsoft/vscode#138770] opened 2021-12-09 16:21 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: `1.63.0 (user setup)`
- OS Version: `Windows 10`

Steps to Reproduce:

1. Set the setting: `"terminal.integrated.defaultLocation": "editor",`
2. Open a new terminal (should open in editor).
   - Error Notification: `Terminal with ID 4 does not exist (has it already been disposed?)`
3. Open another new terminal in the editor.
   - Same message shows up
4. Drag split the terminal window to below.
   - content disappears from the bottom terminal, and is non interactive

I'm mostly repro-ing this with the WSL2 extension, but also happens with the standard windows powershell.

I also separately have VSCode Insiders installed, and have been seeing this since last month on the Insiders release. This issue has started happening in the standard release channel for me starting from yesterday's update.

This also happens on a fresh insiders install, and def with the wsl extension.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by atg** [comment] 2021-12-09 19:44
I am also experiencing this error on Mac after installing the latest update.

I get this error whenever opening a new terminal in the editor. Terminals in the panel do not appear to be affected.

```
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0
```

**Comment by kborisov00** [comment] 2021-12-10 13:55
Also experiencing the same issue.
`
Version: 1.63.0
OS: Windows 10
`

**Comment by dgva** [comment] 2021-12-10 17:32
Also happens on Manjaro KDE, on version 1.63. Seems to be transversal to the OS.

**Comment by meganrogge** [comment] 2021-12-14 18:30
merged into the release branch

**Closed by meganrogge** 2021-12-14 18:30 UTC
Labels: bug, candidate, confirmed, terminal-editors

**Comment by weikinhuang** [comment] 2021-12-15 14:05
@meganrogge Is this in today's insider's build? I'm still seeing the issue with 2 editor terminals when I try to split. Though the disposed warning went away.

```
Version: 1.64.0-insider (user setup)
Commit: b823936907f86ded04a152a4af202d0fc8423522
Date: 2021-12-15T05:14:42.036Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by meganrogge** [comment] 2021-12-15 16:39
@bpasero that sounds like a separate issue. this one was about running create terminal in editor area throwing the error described above.

**Comment by meganrogge** [comment] 2021-12-15 16:41
@weikinhuang
![recording (18)](https://user-images.githubusercontent.com/29464607/146227614-5ca852ed-cd58-436e-a119-7de41c39a714.gif)

what are you seeing? it's working for me

**Comment by bpasero** [comment] 2021-12-15 16:42
I do not see the notification toast when I select "New Terminal" from command palette.

But I see this issue that the OP reported I think:

![image](https://user-images.githubusercontent.com/900690/146227824-36b6ca4a-3102-4dbd-8286-c8cd5d55be40.png)
![recording](https://user-images.githubusercontent.com/900690/146227864-16807e86-4059-47eb-b948-31484582a86f.gif)

**Comment by meganrogge** [comment] 2021-12-15 16:48
So you are splitting the terminal in the editor area then dragging it to the panel, correct? 

![recording (18)](https://user-images.githubusercontent.com/29464607/146228740-46ea7915-7948-429d-ab39-5c2cf97a7f2c.gif)

**Comment by bpasero** [comment] 2021-12-15 16:52
No its not split in the editor, its just a normal terminal in the editor area that I drag to the left of another terminal in panel.

**Comment by meganrogge** [comment] 2021-12-15 16:53
I can reproduce that, but not consistently. I'll make a new issue for that - sounds like you verified the main issue and candidate - that error showing up

**Comment by weikinhuang** [comment] 2021-12-15 16:55
correct, open 2 editor terminals, then drag one of them to the side, not split from the command palette

**Comment by bpasero** [comment] 2021-12-15 17:03
Sounds good, setting label for the notification issue.
