### ISSUE TITLE
Terminal panel stays maximized when editor is split horizontally

### ISSUE THREAD

**Issue by clementhervy** [Microsoft/vscode#33552] opened 2017-08-30 23:10 UTC
- VSCode Version: 1.15.1 Portable (also 1.15.0)
- OS Version: Windows 10

After being maximized, the terminal panel does not restore to the previous size when the editor is split horizontally, when the editors are stacked on top of each other.

Steps to Reproduce:
1. Open two editors, split vertically (stacked on top of each other).
2. Maximize panel with the button or the command.
3. Click on the restore button. Nothing happens.

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-09-01 10:54
Works for me, please let me know what you are doing differently than me
Also please try with latest vscode insiders that you can download here https://code.visualstudio.com/insiders

![panel](https://user-images.githubusercontent.com/1926584/29966973-9c335670-8f14-11e7-81ca-f6d3b2f75411.gif)

**Comment by clementhervy** [comment] 2017-09-01 20:35
I meant split horizontally, when the editors are stacked on top of each other. I edited the issue title to reflect that. I would capture a video but the ways I tried haven't worked. The way you do it works, no problem.

**Comment by isidorn** [comment] 2017-09-04 08:34
Duplicate of https://github.com/Microsoft/vscode/issues/31125
Works in latest inisders, or you can wait for a new release in the next week where this issue will be fixed
![panel](https://user-images.githubusercontent.com/1926584/30018256-7959b79e-915c-11e7-84c0-7a07ab87d575.gif)

**Closed by isidorn** 2017-09-04 08:34 UTC
Labels: needs more info, new release, workbench
