### ISSUE TITLE
editor.ruler doesn't display reliably anymore

### ISSUE THREAD

**Issue by pleprince** [Microsoft/vscode#34451] opened 2017-09-15 10:46 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
xml|Dot|1.9.2
material-icon-theme|PKi|2.2.1
overtype|ada|0.2.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
vscode-color|ans|0.4.5
QML|bbe|1.0.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.3.1
line-counter|dol|0.3.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.0.0
vscode-npm|fkn|3.3.0
rib|glo|0.1.1
badges|idl|1.0.7
textile|idl|0.1.2
kite|Kit|0.0.1
restructuredtext|lex|37.0.0
cpptools|ms-|0.12.4
sublime-keybindings|ms-|2.9.1
syncing|non|1.4.4
seti-icons|qin|0.1.3
qub-xml|qub|1.2.1
tcl|ras|0.1.0
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
todotasks|san|0.5.0
mel|sat|0.1.1
preview-vscode|sea|1.3.1
perforce|sle|2.1.1
shader|sle|0.2.3
cmake|twx|0.0.17
change-case|wma|1.0.0
local-history|xyz|1.4.0
inserttimestamp|zvl|1.1.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1. in user prefs, set `"editor.rulers": [80]`
2. Single column editor: the ruler is not displayed.
3. Dual column editor: the ruler is displayed in the second column
3. Three columns editor: the ruler is displayed in 2nd and 3rd column
4. Switch to stacked editor layout: the ruler is not displayed in any editor.

Reproduces without extensions: Yes !

**Comment by alexandrudima** [comment] 2017-09-21 16:24
@pleprince  I could not reproduce. Perhaps the indent guides look to similar to the ruler ?

The ruler appears for me at column 80.

There are also some indent guides being rendered. They can be turned off via `editor.renderIndentGuides`

![image](https://user-images.githubusercontent.com/5047891/30706881-0a9c90b4-9efa-11e7-8708-39fb6cd72723.png)

Can you please attach a screenshot ?

**Comment by pleprince** [comment] 2017-09-21 16:58
I have found what the issue is: `"window.zoomLevel": -1`
if I set it to 0, I can see the lines, but everything is way too big on my MacBook Pro.
I imagine the display is scaled using nearest and the single pixel line is the disappearing column. Could you make it 2 pixels wide when window.zoomLevel = -1 ?

**Comment by pleprince** [comment] 2017-09-21 17:03
Note that in the previous version it was already happening sometimes, but I could slightly resize the columns to make them appear. This trick doesn't work anymore.

**Comment by alexandrudima** [comment] 2017-09-22 08:53
@pleprince we use [`devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) in establishing a good width for the indent guides.

One of the problems with that is that the `devicePixelRatio` can change when e.g. dragging a window from a retina display to a non-retina display. There is, unfortunately, no event we can use to detect that case.

Are you perhaps regularly moving the VSCode window between different screen types?

**Comment by pleprince** [comment] 2017-09-22 09:32
This is happening on my 2016 15" MacBookPro, so no secondary screen but definitely a retina display.
I googled a bit `window.devicePixelRatio` and it looks like it might not be safe to assume it returns an int on OSX. Are you using integer math by any chance ?

**Comment by alexandrudima** [comment] 2017-09-22 09:36
@pleprince No, we are not using integer math.

Do you then perhaps often switch zoom levels while the window is running.

i.e. does this reproduce when setting zoom level to -1. and then running `F1 > Reload window` or does this reproduce only when changing zoom level and keeping the same window opened ?

**Comment by pleprince** [comment] 2017-09-22 09:56
@alexandrudima , I never change zoom levels: this is set in my user prefs. Reloading the window doesn't change anything.
I just noticed something though: In my prefs I have `"editor.fontSize": 11` and if I set it to 12 (zoomLevel = -1) some of the lines do come back...
<img width="1680" alt="fontsize_11" src="https://user-images.githubusercontent.com/10943552/30739280-a7f83e14-9f84-11e7-9f09-7c96041e5f0e.png">
<img width="1680" alt="fontsize_12" src="https://user-images.githubusercontent.com/10943552/30739281-a7fcc8ee-9f84-11e7-86ef-60c80705afae.png">

**Comment by alexandrudima** [comment] 2017-09-22 10:16
Thank you @pleprince

I can now reproduce when using `Source Code Pro`.

This is easier seen via the cursor width:

![kapture 2017-09-22 at 12 15 33](https://user-images.githubusercontent.com/5047891/30740048-c8519eca-9f8f-11e7-97a6-2e0cb4ab0132.gif)

Looks like the fix we did for #28542 is completely not working after we upgraded to Chromium 58.

**Comment by pleprince** [comment] 2017-09-22 10:20
Awesome. Thanks @alexandrudima :-)

**Comment by henrywallace** [comment] 2018-03-07 14:13
I'll also add that this inconsistency arises for me whenever the zoom level is a negative number.

The motivation for negative zoom levels is that I find the file tree font too large, and there's no config to reduce its size. So that zoom level provides a way to do so.

I'm on VSCode version: 1.21.0-inside, and OS Darwin Kernel Version 17.4.0.

**Comment by alexandrudima** [comment] 2018-03-26 12:55
Fixed via #46029

**Closed by alexandrudima** 2018-03-26 12:55 UTC
Labels: bug, editor, editor-core, electron, upstream, zoom

**Comment by pleprince** [comment] 2018-03-26 12:57
Thanks !
