### ISSUE TITLE
The terminal doesn't changes to default terminal profile while debugging 

### ISSUE THREAD

**Issue by akashdiphazra** [microsoft/vscode#124018] opened 2021-05-17 08:09 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.56.2(stable)
- OS Version: Window 10 home

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/61003681/118452761-171df400-b714-11eb-9563-3f1aeee20e62.png)

2. 
![image](https://user-images.githubusercontent.com/61003681/118453180-8b589780-b714-11eb-888c-69e81fb03024.png)

**Comment by isidorn** [comment] 2021-05-17 10:55
/extPython
I think duplicate of other issues that were filled like this

**Closed** 2021-05-17 10:55 UTC
Labels: *caused-by-extension, new release
