### ISSUE TITLE
organize import bug

### ISSUE THREAD

**Issue by mouradghafiri** [Microsoft/vscode#47964] opened 2018-04-16 13:36 UTC
Hello;

It seems like a bug

- VSCode Version: 1.22.2
- OS Version: Windows

Steps to Reproduce:

import {
  XX as X2,
  YY as Y2,
} from 'exported_things';

When the auto organize feature is executed, it deletes all imports that uses 'as'.

Thanks

**Comment by mjbvz** [comment] 2018-04-16 17:33
Duplicate of #47419

**Closed by mjbvz** 2018-04-16 17:33 UTC
Labels: javascript
