### ISSUE TITLE
`TernarySearchTree.URIIterator`  throws for empty `URI`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#181385] opened 2023-05-03 07:19 UTC
Following test throws:

https://github.com/microsoft/vscode/blob/6384b9bcdf8f2b11988ad2339242955f400895be/src/vs/base/common/ternarySearchTree.ts#L232

```ts
test('URIIterator - does not throw on empty URI', function () {
	const iter = new UriIterator(() => true, () => true);
	iter.reset(URI.revive({ scheme: '', authority: '', path: '', query: '', fragment: '' }));
	iter.cmp('file');
});
```

I found this while investigating https://github.com/microsoft/vscode/issues/181209. 

At that point the editor component is quite broken because of a lot of errors being thrown. Notice how not even a tab shows for the editor:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/900690/235853766-18b0300d-9f07-4c05-a160-9e62f583c2fc.png">

**Comment by jrieken** [comment] 2023-05-03 07:50
`URI.revive({ scheme: '', authority: '', path: '', query: '', fragment: '' })`

⬆️ that should already throw because at least a scheme is needed. It doesn't because `revive` was designed to be the runtime counter part of `toJSON` which never produces such output so some IPC deserialisation cost can be saved.

**Comment by bpasero** [comment] 2023-05-03 07:57
👍 , that works for me and will also throw when we get bad objects into `revive` such as the `URI.revive({ uri: … })` from https://github.com/microsoft/vscode/issues/181209.

**Comment by jrieken** [comment] 2023-05-03 07:59
Yeah, my plan is to add an `strict` argument like we have in other URI-places. It will default to true and only IPC should be relaxed

**Comment by jrieken** [comment] 2023-05-03 13:33
> Yeah, my plan is to add an strict argument like we have in other URI-places. It will default to true and only IPC should be relaxed

Not doing that because it actually already exists as `URI#from`. I believe the adoption/migration task is to use `from` instead of `revive` whenever getting uri components from storage or esp from command arguments. 

Tho, there is one special case for `from` which is that it automatically uses `file` when the scheme is missing. We could make that configurable but a check for `isUriComponents` might make this obsolete

**Comment by jrieken** [comment] 2023-05-03 14:43
Closing this after #181409 and the ask to use `URI#from` when creating uri from "untrusted" sources

**Closed** 2023-05-03 14:43 UTC
Labels: debt, uri
