### ISSUE TITLE
Opening an existing notebook marks it dirty unnecessarily

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#132306] opened 2021-09-03 23:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Stable 1.60
- OS Version: Mac

Steps to Reproduce:

1. Open the following ipynb file (with all extensions disabled)
2. The file is marked dirty

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "source": [
    "# for i in range(0,100000):\n",
    "#     print(i)   \n",
    "ls"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "debugxxx.py\t\tone.three copy 4.ipynb\tsimplePrint.py\n",
      "matplotSample.py\tone.three copy.ipynb\tsmpleWidget.py\n",
      "one.three copy 2.ipynb\tone.three.ipynb\t\tvarViewer.py\n",
      "one.three copy 3.ipynb\tprogressSmaple.py\n"
     ]
    }
   ],
   "metadata": {}
  }
 ],
 "metadata": {
  "orig_nbformat": 4,
  "language_info": {
   "name": "bash",
   "codemirror_mode": "shell",
   "mimetype": "text/x-sh",
   "file_extension": ".sh"
  },
  "kernelspec": {
   "name": "bash",
   "display_name": "Bash",
   "language": "bash"
  },
  "interpreter": {
   "hash": "f18a24808323baba3f9918eb0e4209d5af5f08701b6de1422ac2b2f2ac830fb7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by greazer** [comment] 2021-09-03 23:49
I'm concerned that @rebornix  you won't be able to repro this. I say that because I had had a notebook that was reproing it, but then after doing some fiddling with updating that notebook from the original repo, it stopped reproing for me. However, I was a witness to seeing the behavior @DonJayamanne consistently was reproing above. 

Keeping my fingers crossed that it's reproable.

**Comment by jackthepanisher** [comment] 2021-09-04 10:13
This looks like something related to the kernel selection and folder/workspaces. I can reproduce it with a single `print("hello world")` cell.

1. Opening the notebook file stand-alone (e.g. `code test.ipynb`) doesn't make the file dirty. However, although I selected a kernel for that file before and I see that getting saved into the notebook file, VS Code starts with no kernel selected for the notebook.
2. Opening the contained folder with `code .` and the contained test.ipynb notebook file also doesn't make the file dirty as long as no kernel is selected yet - also after re-opening the folder and/or modifying the notebook
3. Selecting a kernel in that folder will retain the kernel setting after re-opening and make the notebook file dirty - no matter if you save or not save the notebook
4. Opening again with `code test.ipynb` shows the same as 1. i.e. not dirty but also no kernel selected

I don't see a .vscode folder and settings.json created during that experiment so not sure where the kernel information is stored, probably some user %localappdata% settings.

**Comment by greazer** [comment] 2021-09-14 00:35
I'm reproing this right now with a very simple "print" ipynb file. I simple close it, say "no, I don't want to save changes" (as I didn't make any), then reopen it. It gets marked dirty within a second or so. 

Version: 1.61.0-insider (user setup)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:15:14.689Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22454

**Comment by greazer** [comment] 2021-09-14 00:37
Ah, right, to @jackthepanisher's point. It looks like that if the ipynb file has a kernel selected that matches one on the machine, then the file will be dirtied on opening. If the kernel isn't known (and Select Kernel is shown at the top right), then the file will not be dirty.

**Comment by rebornix** [comment] 2021-09-15 21:57
One typical scenario where the document becomes dirty right after it's opened or scrolling:

* Cell language is not supported in VS Code (e.g., `bash`, `raw`)
* Cell rendered in the editor
* We will try to find a language mode for `bash`/`raw`, if failed, it will use `plaintext`
* Text model for the cell is created, which will trigger an update of the cell language from `bash`/`raw` to `plaintext`, which at the end triggers content change.

**Comment by DonJayamanne** [comment] 2021-09-28 20:10
I am still running into this issue, in the latest insiders & all extensions disabled.

**Comment by rchiodo** [comment] 2021-09-30 23:12
@rebornix I'm still hitting this with the latest bits.

**Comment by rchiodo** [comment] 2021-09-30 23:13
I have a file that consistently repros:
[t2.ipynb.txt](https://github.com/microsoft/vscode/files/7262985/t2.ipynb.txt)

**Comment by rebornix** [comment] 2021-10-01 15:26
@rchiodo can you confirm you have all extensions installed when opening that file?

**Comment by rebornix** [comment] 2021-10-01 15:32
Tested with the latest bits on Windows 


![recording (26)](https://user-images.githubusercontent.com/876920/135647263-7bf38497-fbec-4195-8160-8ace6090b084.gif)


Verifier: please test with above file with `--disable-extensions`

**Closed by rebornix** 2021-10-01 15:32 UTC
Labels: bug, important, verification-found, notebook

**Comment by rchiodo** [comment] 2021-10-01 16:09
/verified. It doesn't repro without extensions enabled. Looks to be a bug in the jupyter extension (as that's the only one I have to enable to get the bug to repro again)
