### ISSUE TITLE
Double click to install VSIX file does not work.

### ISSUE THREAD

**Issue by tansvanio** [Microsoft/vscode#50113] opened 2018-05-18 15:26 UTC
Greetings,

I am currently working in a situation where I find myself building and installing VSIX packages very often. This happens in a closed enviroment due to the plugins being private, so using the marketplace is not an option.

So far I have been using the "Install from .VSIX" option available in Visual Studio Code, which as far as I am aware is the only one.

It would be a great addition to be able to double click on a vsix file in order to install it right away, however if I try to do it I get the following error.

Steps to reproduce: 

1. Double click (left mouse button) on a vsix file.

And it will produce this error:

![image](https://user-images.githubusercontent.com/17090444/40243290-b924c7d6-5ab7-11e8-981b-35a7d13acb79.png)

If we further inspect the install log I can find this line : 

![image](https://user-images.githubusercontent.com/17090444/40243353-e5a6449c-5ab7-11e8-8e96-cc616c4352e2.png)

Which in my eyes it means that Visual Studio Code is not being detected for this type of installation.

So, if this is not an intended feature I would like to request it. Many executables can be installed with a double click, so I dont think a VSIX file for an extension should be an exception. This feature could save some time to developers that need to install extensions very often.

Many thanks,
Ricardo

**Comment by tomzx** [comment] 2018-05-20 16:08
It appears that the list of supported SKUs is hardcoded within the `VSIXInstaller.exe`, which is associated with Visual Studio (not VS Code) when installed. I believe Microsoft would have to release an update for Visual Studio (or to the VSIXInstaller) before this can actually work as you expect it. Otherwise VS Code would have to fight with Visual Studio to define which executable will execute `.vsix` files by default.

**Comment by tansvanio** [comment] 2018-05-21 09:13
@tomzx Would it not be possible for the vsix file to announce if the plugin it contains is a Visual Studio Code or a Visual Studio plugin, thus solving the problem to which platform it should be installed on.

**Comment by tomzx** [comment] 2018-05-21 14:11
@tansvanio It already does something like that. If you look at the log file referred in `View Install Log`, you will find the following lines:

```
20/05/2018 11:49:31 - Microsoft VSIX Installer
20/05/2018 11:49:31 - -------------------------------------------
20/05/2018 11:49:31 - Initializing Install...
20/05/2018 11:49:31 - Extension Details...
[...]
20/05/2018 11:49:31 - 	Supported Products : 
20/05/2018 11:49:31 - 		Microsoft.VisualStudio.Code
```

So the `VSIX` file already contains the appropriate information. However the `VSIXInstaller` simply does not recognize the target product, which I guess takes care of delegating to the appropriate product the installation of the `VSIX`.

**Comment by sandy081** [comment] 2018-09-24 17:03
Duplicate of #31079

**Closed** 2018-09-24 17:03 UTC
Labels: *duplicate, extensions, feature-request
