### ISSUE TITLE
Italics break in Markdown mode when there's linebreak

### ISSUE THREAD

**Issue by mkoske** [Microsoft/vscode#1837] opened 2016-01-06 21:00 UTC
Hello,

I noticed, that when editing Markdown text, italics is not shown correctly, if the text, that must be in italics, has linebreak. Same issue is also with bold. I attached screencapture below.

![md-bug](https://cloud.githubusercontent.com/assets/4409023/12154595/1a9cbe66-b4c9-11e5-9a86-7534cf87a6a3.PNG)

**Comment by aeschli** [comment] 2016-01-07 11:13
Difficult to fix, as we tokenize line by line.

**Comment by mkoske** [comment] 2016-01-07 11:24
@aeschli can you point me to right direction where to look at this? I'm pretty new to vscode.

**Comment by mjbvz** [comment] 2018-02-09 22:53
As @aeschli notes, this is a surprisingly difficult problem to fix using text mate grammars since we go line by line.

Given that this problem hasn't attracted much attention since it was opened, I'm going to close this as out of scope as the effort required to fixed it does not seem worth the limited payoff and the high risk of regressions

**Closed by mjbvz** 2018-02-09 22:53 UTC
Labels: bug, grammar, help wanted, languages basic, markdown
