### ISSUE TITLE
Feature request: add time stamp to edited/newly created comment

### ISSUE THREAD

**Issue by matt-erhart** [Microsoft/vscode#34480] opened 2017-09-15 17:57 UTC
e.g.
```javascript
// 9/15/2017@10:53am Some comment that was true at the time
/ *
* 9/15/2017@10:53am Some comment that was true at the time
* /
```
Change any of the text in the comment and the time changes.

**Comment by alexandrudima** [comment] 2017-09-18 08:40
@jrieken perhaps doable with a snippet ?

**Comment by jrieken** [comment] 2017-09-18 08:50
dupe of #32021

**Closed by jrieken** 2017-09-18 08:50 UTC
Labels: snippets
