### ISSUE TITLE
Integrated terminal not defaulting correctly on startup Cygwin

### ISSUE THREAD

**Issue by steves165** [microsoft/vscode#132863] opened 2021-09-10 13:33 UTC
After recent update of VSCode Cygwin stopped opening as default when I startup the application.
I have followed the guide to setup the new terminal profiles and Cygwin is set as the default and it does work correct if I press the + button for a new terminal and when I reload the window, but when I start the application after closing it it comes up with powershell. I have attached some images to show the issue and my settings.

This shows that Cygwin is set as the default profile
![image](https://user-images.githubusercontent.com/2880364/132861191-1d8f47ae-5316-4a3b-b78b-16483adc5a92.png)

This is the profile configuration.
![image](https://user-images.githubusercontent.com/2880364/132861248-6511d023-f22a-4776-982e-042da730cdcc.png)

This is the behaviour on new startup 
![image](https://user-images.githubusercontent.com/2880364/132861383-73faa099-1bb6-4d35-8cab-044c7ce15f76.png)

**Comment by IllusionMH** [comment] 2021-09-10 13:58
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-10 13:58 UTC
Labels: *duplicate
