### ISSUE TITLE
Right click context menu in Explorer side panel appears under mouse pointer; leading to execution of a random command

### ISSUE THREAD

**Issue by Mohammad-Mohsen** [microsoft/vscode#153854] opened 2022-06-30 19:22 UTC
Issue Type: <b>Bug</b>

1. Open a random project
2. Open Explorer sidebar
3. Right click on a file

![vscode_contextmenu_bug](https://user-images.githubusercontent.com/52295823/176764857-9d1b33fd-a3e9-4d93-9c5a-5a8efa06a33a.gif)

For some reason, this is only exclusive to Explorer side-panel; the main editor area and other side-panels' right click menus are totally ok.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.4.0-121-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3111)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5a00998f-074a-41d4-8007-8c2f02801e56|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by lramos15** [comment] 2022-06-30 20:43
I cannot reproduce this on ubuntu 20.04 or macOS. What OS are you using?

**Comment by gjsjohnmurray** [comment] 2022-07-01 01:34
@lramos15 I think this is a duplicate of #106583, which deserves some love. Anything you can do to escalate it?

**Comment by Mohammad-Mohsen** [comment] 2022-07-01 06:23
@lramos15 I use Linux Mint 20, which is based on Ubuntu 20.04

I noticed the issue only happens when sidebars are on the right, and it seems to caused by source control stuff; because the problem cannot be reproduced on first few seconds after startup when those source control stuff are not loaded.

**Comment by lramos15** [comment] 2022-07-01 14:15
@gjsjohnmurray That issue appears closed and resolved is it not?

**Comment by gjsjohnmurray** [comment] 2022-07-01 14:50
@lramos15 sorry, somehow I pasted the wrong issue number. It should have been #113175. I think #114391 is similar too.

**Closed** 2022-07-01 15:02 UTC

**Comment by Mohammad-Mohsen** [comment] 2022-07-01 16:38
@lramos15 The workaround does not work. I even rebooted the whole system but nothing has been changed. 

The thing that really bothers me is other context menus appear and behave appropriately except Explorer entries and only when I use git and move sidebars to right which both are essential and fundamental to my workflow.

**Comment by lramos15** [comment] 2022-07-01 17:18
> The thing that really bothers me is other context menus appear and behave appropriately except Explorer entries

There's nothing uniquely special about the explorer context menu. My guess is it has to do with being the largest context menu on the sidebar pressed up against the window barrier

**Comment by Mohammad-Mohsen** [comment] 2022-07-01 17:28
@lramos15 Didn't thought of that! I checked other context menus, some entries on source control had this problem as well. But the weird thing is that there is no issue when sidebars are on the left.
