### ISSUE TITLE
Allow a rectangular shadow to show focus on minimap

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#21823] opened 2017-03-02 19:56 UTC
- VSCode Version: 1.10.1(653f873) and 1.11.0-insider (0bc62d1)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Allow a rectangular shadow to indicate where the minimap is, without having to move the mouse. Like Atom.

![foco](https://cloud.githubusercontent.com/assets/19866231/23524327/e274029c-ff68-11e6-9978-af344fa1c59e.gif)

And when it slides horizontally, another shadow will be shown to indicate that I'm going to the side. Like Atom.

![foco2](https://cloud.githubusercontent.com/assets/19866231/23524366/0f92c146-ff69-11e6-8475-dcd95c305278.gif)

Update: Correcting the wrong translation from Google Translate.  :blush::blush::blush:

**Comment by Jarvid** [comment] 2017-03-03 23:10
Hi, you might customize this via the custom css and js extension together with a change to 
`.monaco-editor .minimap-slider {
opacity: 1; /* changed from 0 */
transition: opacity .1s linear
}`and `.monaco-editor.vs-dark .minimap-slider { background: hsla(0, 0%, 39%, .7) }`

That should work as a work around when using the dark theme. :)

**Comment by Tsmith18256** [comment] 2017-03-07 00:32
The first part of this request is also similar to the `"always_show_minimap_viewport"` setting in Sublime, for people familiar with that.

**Comment by alexandrudima** [comment] 2017-03-07 14:45
Duplicate of #21784

**Closed by alexandrudima** 2017-03-07 14:45 UTC
