### ISSUE TITLE
[Suggestion] Add the font modification function of the main interface of vscode

### ISSUE THREAD

**Issue by gz83** [microsoft/vscode#147161] opened 2022-04-10 06:34 UTC
Hello developers, because the font of the main interface of vscode does not look good in traditional Chinese, so I changed the font by modifying the "workbench.desktop.main.css" file. After modifying this file, a prompt will pop up every time vscode starts" Your installation of Code - Insiders seems to be corrupted. Please reinstall.", I request that the developer can bring a new setting to vscode to modify the font of the main interface in the correct way, thank you very much!

**Comment by yume-chan** [comment] 2022-04-10 09:03
Duplicate of #519

**Comment by gz83** [comment] 2022-04-10 12:05
> Duplicate of #519

This problem has been going on for a long time.

**Comment by Tyriar** [comment] 2022-12-05 20:39
@gz83 creating another issue for the same thing just wastes our time.

**Closed by Tyriar** 2022-12-05 20:39 UTC
