### ISSUE TITLE
Updaters Broke

### ISSUE THREAD

**Issue by sulkhanp** [Microsoft/vscode#53281] opened 2018-06-29 00:33 UTC
- VSCode Version: 1.25 Insiders
- OS Version: Win10

Steps to Reproduce:

1.Wait for an extension or new 1.25 vscode update.
2.Click update 
![image](https://user-images.githubusercontent.com/32885386/42067035-3ffd7574-7b55-11e8-9f69-23cbf73e2ae2.png)
3.Watch it as it installs
![image](https://user-images.githubusercontent.com/32885386/42067047-5cfb679e-7b55-11e8-8ed0-dff90a557a5d.png)
4.Asked for update again?!
![image](https://user-images.githubusercontent.com/32885386/42067069-74baa1ec-7b55-11e8-830c-2e834e4ed0c4.png)

This happens to both vscode and vscode extensions updater. I've also noticed that when you reload/restart, extensions/vscode are updated and you're no longer asked to update them.

Does this issue occur when all extensions are disabled?: Yes

I've also cross-tested with 1.24 stable release, the same extensions are updating fine there. Same machine, same setup.

**Comment by mastrauckas** [comment] 2018-06-29 01:55
I am having the same problem.

**Comment by sandy081** [comment] 2018-07-02 09:06
Duplicate of #53426

**Closed** 2018-07-02 09:06 UTC
Labels: *duplicate, extensions
