### ISSUE TITLE
Constant freezes after Updating on 13th November, 2018

### ISSUE THREAD

**Issue by shalomz** [Microsoft/vscode#63092] opened 2018-11-14 06:20 UTC
Issue Type: <b>Bug</b>

After applying an update on the 13th November, 2018, my VS Code instance is constantly freezing most of the time. I am on Linux Mint 18.3. Most definitely, there is an issue with this update.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2883)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|7.68GB (0.87GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
django-html|bib|1.2.0
django-snippets|bib|1.1.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
es7-react-js-snippets|dsz|1.9.0
vscode-wasm|dts|1.2.1
prettier-vscode|esb|1.7.2
vscode-optimize-images|fab|1.0.7
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
node-module-intellisense|lei|1.5.0
markdown-converter|man|1.1.2
dotenv|mik|1.0.1
mssql|ms-|1.4.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.0
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.13.0
python-template-snippets|Ric|1.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.28.0
vscode-djaneiro|the|1.4.2
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
vscode-react-native|vsm|0.6.18

(1 theme extensions excluded)

</details>

**Comment by Alchez** [comment] 2018-11-14 08:30
I'm facing the same issue with random freezes.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-38-generic (Ubuntu 18.04.1 LTS)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor (8 x 1563)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.80GB (0.99GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jslint|ajh|1.2.1
vscode-django|bat|0.17.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
git-extension-pack|don|0.1.3
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
gitlens|eam|8.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-pull-request-github|Git|0.2.3
vscode-random|jre|1.4.0
restructuredtext|lex|79.0.0
MagicPython|mag|1.1.0
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
python|ms-|2018.10.1
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.954
autodocstring|njp|0.2.3
vscode-icons|rob|7.28.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.0
vscodeintellicode|Vis|1.0.6
jinja|who|0.0.8
ReactSnippets|xab|2.2.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by DTasev** [comment] 2018-11-14 10:33
Same issue, randomly freezes while _also_ having high CPU usage.

Version: 1.29.0 (system setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by bpinaya** [comment] 2018-11-14 10:41
Same issue on Ubuntu 16.04 after the last update.

Version: 1.29.0
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:42:27.562Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by rilut** [comment] 2018-11-14 10:42
same issue with VSCode 1.29.0 on macOS Mojave 10.14

**Comment by filipesilva** [comment] 2018-11-14 14:58
This issue seems to be a duplicate of https://github.com/Microsoft/vscode/issues/62970. A suggested workaround is to always clear notifications.

**Comment by AshleyMcVeigh** [comment] 2018-11-15 04:06
Same issue

VS Code: Version 1.29.0 (1.29.0)
OS: macOS Mojave 10.14 (18A391)

**Closed** 2018-11-16 04:53 UTC
Labels: needs more info, new release

**Comment by ChuckIrvine** [comment] 2018-12-20 17:41
I have also had random freezes since updating to Mojave, but the problem hasn't been limited to Mojave. Even something as simple as clicking on the LaunchPad icon in the dock also causes a freeze. The problem is temporarily cleared by a restart and then reoccurs after 1 to 3 days. Five days ago in installed the beta of 10.14.3 and the problem has not reoccured. Apple fixed a bug maybe? I have a 2018 MacBook Pro
