### ISSUE TITLE
Allow to add additional folders to quick open search path

### ISSUE THREAD

**Issue by drorata** [microsoft/vscode#57099] opened 2018-08-23 18:42 UTC
It is often the case that one has to open a file which has nothing to do with the current directory/project. When using other editors this is supported using extensions; check for comparison [advanced-open-file (for Atom)](https://atom.io/packages/advanced-open-file) or [ido (for emacs)](https://www.masteringemacs.org/article/introduction-to-ido-mode).

In a nutshell, all it has to do, is scan the current directory (for example the one of the current/active file) and fuzzy search it allowing moving either upwards or downwards. 

I raised this issue in #43505 and it was suggested to start a new thread around this, in my mind, very needed feature.

**Comment by nealot** [comment] 2018-09-10 08:59
Having something like advanced-open-file would improve productivity for Emacs/Atom users in the same way breadcrumbs have helped users of Intellij/Visual Studio. The two features generally both serve the same purpose, but advanced-open-file is more familiar and not as constraining.

**Comment by drorata** [comment] 2018-09-10 10:27
The breadcrumbs doesn't help you if you want to open `~/.zshrc` for example, whereas smarter file opening would.

**Comment by roblourens** [comment] 2019-10-09 02:00
Duplicate of https://github.com/microsoft/vscode/issues/43505

**Closed by roblourens** 2019-10-09 02:00 UTC
Labels: api, feature-request, search
