### ISSUE TITLE
CLI install extension command cannot run non-interactively

### ISSUE THREAD

**Issue by AdamVig** [Microsoft/vscode#58434] opened 2018-09-11 13:30 UTC
- VSCode Version: 1.27.1
- OS Version: MacOS 10.13.6

I have found that I am unable to reliably install extensions via the command line because of an update prompt that requires user interaction. A flag like `--yes` or `--force` or `--update` would be helpful in allowing the `--install-extension` command to run non-interactively.

Steps to Reproduce:

1. `code --install-extension yzhang.markdown-all-in-one` (or any extension that has a newer version than the one you have installed)
2. Prompt appears: `Extension 'yzhang.markdown-all-in-one' v1.6.0 is already installed, but a newer version 1.6.1 is available in the marketplace. Would you like to update? Yes(0) | No(1)`

Does this issue occur when all extensions are disabled?: Yes (CLI command)

**Comment by sandy081** [comment] 2018-09-12 15:39
@AdamVig May I know the use case why do you want to run this non interactively?

**Comment by ThadHouse** [comment] 2018-09-12 17:27
I agree that the CLI should have a way to run every command, especially extension based commands without interaction. I also have an installer that is installing a list of VS Code extensions, and while I haven't directly seen this issue yet, it would be a major issue if it did.

**Comment by sandy081** [comment] 2018-09-13 14:18
Use --force to not to show prompts

**Comment by AdamVig** [comment] 2018-09-13 14:58
@sandy081 Based on the code I could see in the pull request, it looks like this may prevent the `code --install-extension` command from updating already-installed extensions.

Is that the case? If so, they will be updated through some other mechanism, correct?

**Comment by sandy081** [comment] 2018-09-14 12:18
@AdamVig No, it will not prevent. If there is an update and you pass `--force` command, I would skip prompting and install the extension directly.

**Comment by AdamVig** [comment] 2018-09-18 13:45
I was able to verify that the fix is working for me. Thanks @sandy081 for jumping on this!

**Comment by sandy081** [comment] 2018-09-26 21:15
@sbatten May I know if you reopened this issue because of #59481 or is there something else not working here?

**Comment by sandy081** [comment] 2018-09-26 21:29
I can reproduce the error you see in #59841 and it is happening only in windows. Not sure if it is necessary to have both issues open. Is it ok to close the other one and track it here?

**Comment by sandy081** [comment] 2018-09-26 21:33
I think let's have them separate. This issue is for allow installing / updating extension without any prompt and other issue should show the prompt while updating.

**Comment by sandy081** [comment] 2018-09-26 21:46
@sbatten Did you try updating the extension using `--force` argument here?

**Comment by sandy081** [comment] 2018-09-26 21:55
@sbatten `--force` argument updates the extension without any prompts on Windows. Closing this. Please do verify.

Let's track the prompts related issue in the other one you created (#59841)

**Closed by sandy081** 2018-09-26 21:55 UTC
Labels: cli, extensions, feature-request, verification-found
