### ISSUE TITLE
VSCode newer than October (1.40) fails to open Citrix. "The Window is no longer responding" 

### ISSUE THREAD

**Issue by cbtboss** [microsoft/vscode#91030] opened 2020-02-19 22:42 UTC
All I found were marked closed. 
 Happens in insider build. 

- VSCode Version: 1.40 (started with 1.32 and worked my way through every installer released since 1.32.3. All work until I get to 1.40. Then all subsequent versions fail to open.). 
- OS Version: Server 2012 Standard running Terminal Services/Citrix. 

Steps to Reproduce:

1. Install Vscode 1.40 (or newer) on a Server running Citrix XenApp/Desktop. (tested using VDA 7.15 CU4 and CU5)
2. Try to open the program. It will fail to open and will stall out before giving you an error about window is no longer responding. 

Log:
[2020-02-19 09:18:04.948] [main] [info] update#setState idle
[2020-02-19 09:18:34.954] [main] [info] update#setState checking for updates
[2020-02-19 09:18:35.271] [main] [info] update#setState downloading
[2020-02-19 09:18:37.079] [main] [error] [VS Code]: detected unresponsive
[2020-02-19 09:18:38.709] [main] [info] update#setState downloaded

Does this issue occur when all extensions are disabled?: Yes/No Yes. 

Other troubleshooting steps noteworthy:
Happens with new user profiles. 
Happens on both server 2012 and server 2016. 
Tested on Server 2012. Works. then installed Citrix VDA 7.15 CU5, suddenly doesn't work. Let me know if you need more info.

**Comment by deepak1556** [comment] 2020-02-20 03:55
This is duplicate of https://github.com/microsoft/vscode/issues/84914, please try the workaround mentioned in that issue https://github.com/microsoft/vscode/issues/84914#issuecomment-556033410 , thanks!

**Closed by deepak1556** 2020-02-20 03:55 UTC

**Comment by cbtboss** [comment] 2020-02-20 04:43
Oh heavens... thank you soo much! I do apologize for the duplicate.
