### ISSUE TITLE
Can not sign in with Microsoft Authentication in KDE desktop environemnt

### ISSUE THREAD

**Issue by EFanZh** [microsoft/vscode#106380] opened 2020-09-10 05:14 UTC
- VSCode Version: 1.48.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Open VS Code in KDE desktop environemnt.
2. Sign in with Microsoft account.

Does this issue occur when all extensions are disabled?: Yes

The browser hangs on `/signin` URL and did not get a response.

**Comment by jungaretti** [comment] 2020-09-21 02:26
I'm experiencing this issue as well! Same symptoms as @EFanZh, browser hangs on `/signin` and never gets a response.

**Comment by jungaretti** [comment] 2020-09-21 19:14
I found a workaround! Use the `Azure: Sign In with Device Code` command to bypass the `localhost` login system.

**Comment by jungaretti** [comment] 2020-09-21 21:36
It seems like this issue belongs in https://github.com/microsoft/vscode-azure-account

I'm going to comment on https://github.com/microsoft/vscode-azure-account/issues/179, but https://github.com/microsoft/vscode-azure-account/issues/199 and https://github.com/microsoft/vscode-azure-account/issues/217 are also related.

**Comment by EFanZh** [comment] 2020-09-21 23:20
@jungaretti Is your desktop environment also KDE?

**Comment by jungaretti** [comment] 2020-09-21 23:53
> @jungaretti Is your desktop environment also KDE?

Yeah, Arch Linux with KDE

**Comment by EFanZh** [comment] 2020-09-22 01:58
I suspect the reason for the hanging only happens on KDE desktop environment. KDE opens URL in a way that it prefetches the contents of the URL and then, according to the content of the URL, determine the application to open the URL for the second time. So the authentication URL is first handled by KDE, and the response from VSCode is also sent to KDE. But KDE can not resume the authentication process, instead, it opens the browser, and the browser accesses the URL for the second time.

You can verify this by typing `kde-open5 <URL>` in your terminal. You should notice that a progress bar appears before the browser opens the URL. The progress bar indicates KDE is prefetching the URL.

The VSCode authentication server can handle a single request, response with a redirection, then wait for the authentication to complete. But KDE can not finish the authentication process, and the browser does not get the redirection response, so everyone hangs.

I noticed today that the authentication process works fine now. It seems that KDE has fixed the two-step URL handling process, using `kde-open5` opens the URL immediately in the browser now. And my VSCode can sign-in without hanging. @jungaretti You can try to do a system upgrade, see if anything changes.

I think the VSCode authentication server can be more robust against situations like this.

**Comment by jungaretti** [comment] 2020-09-22 02:25
Wow, that's an interesting theory. I'll try updating everything later tonight and check if the issue still occurs. I linked to an issue in the Azure Account extension repo, but it does seem like all of this is being caused by the same core bug. I'm also unable to sign in to settings sync with my Microsoft account.

**Comment by jungaretti** [comment] 2020-09-22 17:09
I did a full system upgrade and the issue continues to occur.

**Comment by MartenBE** [comment] 2021-02-13 11:59
This issue still exists on Fedora 33 KDE (fully updated)

**Comment by TylerLeonhardt** [comment] 2021-05-20 22:34
@EFanZh you are correct. We currently only handle the _first_ request that comes in to `/signin`:
https://github.com/microsoft/vscode/blob/6f2381e33d7450c79ba37f6803e3e6afd84dfcb6/extensions/microsoft-authentication/src/AADHelper.ts#L336-L358

Nothing happens to any request after that. We need to change the logic here to allow multiple requests to come through.

**Comment by MartenBE** [comment] 2021-08-18 19:37
Temporary workaround: selecting GitHub instead of Microsoft works.

**Comment by TylerLeonhardt** [comment] 2022-03-03 02:11
I believe I fixed this in https://github.com/microsoft/vscode/commit/e485dc292f8a7c4b5b478db5746f795e1b321aaf can you give this another try?

**Comment by TylerLeonhardt** [comment] 2022-12-08 20:32
Optimistically closing this

**Closed by TylerLeonhardt** 2022-12-08 20:32 UTC
Labels: bug, authentication
