### ISSUE TITLE
Project Search/Replace with RegExp with \n only searches in currently open file

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#13068] opened 2016-09-30 09:47 UTC
- VSCode Version: 1.5 and 1.6.0-insiders

Steps to Reproduce:
1. Open project-wide search/replace
2. Enable regexp searching
3. Type in a search that includes a new line, like `<\?php\n\nnamespace`
4. Hit enter => no results
5. Open a file where the pattern occurs, like
   
   ``` php
   <?php
   
   namespace Whatever;
   ```
6. Hit enter again => one result _only_ in this open file
7. Remove `\n\n` from query
8. Hit enter again => all results (files) show up

**Comment by sandy081** [comment] 2016-10-03 10:10
@felixfbecker Currently search works as follows with different code paths.

* when a file is opened it searches using the same search implementation as the editor find widget (where multi-line search is supported)
* when a file is not opened it searches in a separate process with a different implementation ((where multi-line search is **NOT** supported)

Hence you are seeing different results when files are open. I think ideal solution here would be is to support multi-line search in Search view completely #13155

Until then we should not be showing any results for multi line search. More over current shown results for multi line search in Search view are also not good because the matches representations are not correct.

**Comment by ahmetalpbalkan** [comment] 2017-01-06 10:08
3 months and no fix? Please see #18198 for a very simple use case. It actually is misleading that it says "no results found" whereas the problem is I don't have the files open currently. Either say the feature is not supported, or just implement it please.

**Comment by felixfbecker** [comment] 2017-01-06 17:03
@ahmetalpbalkan the vscode team is working very hard and there are plenty tickets I would consider higher priority.

**Comment by sandy081** [comment] 2017-01-06 17:32
@felixfbecker Thanks for responding. 

@ahmetalpbalkan We will try to fix this gap in Find in Files and Editor Find very soon. Thanks for mentioning its importance.

**Comment by quickEscape** [comment] 2018-05-22 09:42
@sandy081 "....very soon. ..."

**Comment by roblourens** [comment] 2018-05-22 21:38
The most likely path to a fix involves https://github.com/Microsoft/vscode/issues/47058, although the UI still would need updates.

**Comment by roblourens** [comment] 2018-09-13 01:42
I think can be considered a dupe of https://github.com/Microsoft/vscode/issues/13155, sorry if there's something I'm missing

**Closed by roblourens** 2018-09-13 01:42 UTC
Labels: bug, search
