### ISSUE TITLE
After some updates VSCode performances became slower

### ISSUE THREAD

**Issue by Alyyc85** [microsoft/vscode#81050] opened 2019-09-17 14:08 UTC
Issue Type: <b>Performance Issue</b>

Dear assistance,
after 2 or 3 updates VSCode performances broken significantly. I tried to check if any extension was the problem but even with all extension disabled the problem still persist.

My entire dev team is experiencing the same issue after a certain date, even with different OS configuration.

Intellisense takes minutes to perform a search or suggestion, searching file became impossible, "go to definition" utility stops working and so on.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IllusionMH** [comment] 2019-09-17 14:21
/needsMoreInfo

Is it a problem with some specific folder/workspace? What languages are used? Is it large one?

Does it happen if you open other folders/workspaces with VSCode?

**Comment by Alyyc85** [comment] 2019-09-17 14:42
Hello and thanks for the fast replies
In order:
1. Apps and languages: Angular & Typescript
2. Workspaces: several, not only one in particular, all in the previous language.
3. Size of workspaces: yes they are a little big, they're enterprise apps. File folder is 723MB, 88.555 files (node_modules included)

But we're experiencing this problem from  this September, first days, after an update. In august VSCode performed well.

**Comment by IllusionMH** [comment] 2019-09-17 15:01
What TS version are you using - built in or from `node_modules`?
August update now [ships with TS 3.6](https://code.visualstudio.com/updates/v1_38#_typescript-36).

Does this happen if you change version to 3.5 or one used in your project? You can click on TS version in actions bar to pick other or [check these docs](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

**Comment by Alyyc85** [comment] 2019-09-17 15:53
TS version 3.6.2 from node_modules, i'll try to check different version in test workspaces and i'll update the issue

**Comment by kieferrm** [comment] 2019-09-17 17:10
//cc @mjbvz

**Comment by blindfirefly16** [comment] 2019-09-17 17:48
After latest update to version 1.38.1, I am having trouble with emmet abbreviation. Having this problem on both my office desktop and home laptop. It was working fine with the previous version. I didn't install any extension in between. So, I suspect it has something to do wilth latest vs code update.

**Comment by bmewburn** [comment] 2019-09-18 02:27
I think it's a memory leak with TS. I've switched to 3.5.3 and will see how it goes.
```
CPU %   Mem MB     PID  Process
    0       79    3095  code main
    0        0    3099     zygote
    0      472    3141       window (referenceTransform.ts - intelephense - Visual Studio Code)
    0      268    3182         extensionHost
    0       16    3284           /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3182
    0       16    3285           /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=3182
    0       71    7790           electron_node eslintServer.js 
    0      276   19955           electron_node intelephense.js 
    0      150   32071           electron_node tsserver.js 
    0     1897   32072           electron_node tsserver.js 
    0       94   32089             electron_node typingsInstaller.js typesMap.js 
    0       55    3199         watcherService
    0       71    7842         searchService
    0        0   10953         /bin/bash
    0        0   12374           bash /usr/bin/code --status
    0       55   12381             electron_node cli.js 
    0       94   12405               /usr/share/code/code --status
    0       31   12407                 zygote
    0       39   12437                 gpu-process
    0       55    3216       shared-process
    0        0   12448         /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0   12449           /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0      173   17890       window (package.json - vscode-intelephense - Visual Studio Code)
    0        0   17910         /bin/bash
    0       71   17914         extensionHost
    0       63   17949           electron_node tsserver.js 
    0       94   17950           electron_node tsserver.js 
    0       55   18008             electron_node typingsInstaller.js typesMap.js 
    0       24   18052           /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=17914
    0       31   17933         watcherService
    0      110    3129     gpu-process
```

**Comment by Alyyc85** [comment] 2019-09-18 07:48
I'm testing with another workspace with previous compiler version that requires 3.2.4 TS version.
We'll see...

**Comment by Alyyc85** [comment] 2019-09-18 09:49
> I think it's a memory leak with TS. I've switched to 3.5.3 and will see how it goes.
> 
> ```
> CPU %   Mem MB     PID  Process
>     0       79    3095  code main
>     0        0    3099     zygote
>     0      472    3141       window (referenceTransform.ts - intelephense - Visual Studio Code)
>     0      268    3182         extensionHost
>     0       16    3284           /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3182
>     0       16    3285           /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=3182
>     0       71    7790           electron_node eslintServer.js 
>     0      276   19955           electron_node intelephense.js 
>     0      150   32071           electron_node tsserver.js 
>     0     1897   32072           electron_node tsserver.js 
>     0       94   32089             electron_node typingsInstaller.js typesMap.js 
>     0       55    3199         watcherService
>     0       71    7842         searchService
>     0        0   10953         /bin/bash
>     0        0   12374           bash /usr/bin/code --status
>     0       55   12381             electron_node cli.js 
>     0       94   12405               /usr/share/code/code --status
>     0       31   12407                 zygote
>     0       39   12437                 gpu-process
>     0       55    3216       shared-process
>     0        0   12448         /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
>     0        0   12449           /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
>     0      173   17890       window (package.json - vscode-intelephense - Visual Studio Code)
>     0        0   17910         /bin/bash
>     0       71   17914         extensionHost
>     0       63   17949           electron_node tsserver.js 
>     0       94   17950           electron_node tsserver.js 
>     0       55   18008             electron_node typingsInstaller.js typesMap.js 
>     0       24   18052           /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=17914
>     0       31   17933         watcherService
>     0      110    3129     gpu-process
> ```

Confirm @bmewburn report of memory leak. With older TS verions VSCode runs well. 3.6.x + causes an high processes stress

**Comment by mjbvz** [comment] 2019-09-18 18:07
@Alyyc85 Can you share the performance numbers when intellisense is taking a long time to show up. The current numbers don't show any cpu usage which seems suspicious 

Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to see if that fixes the problem

**Comment by sradevski** [comment] 2019-09-25 08:19
@mjbvz I had the same issue and can confirm that the issue is fixed by installing the extension you linked (uses TS 3.7.0 at the time of writing).

**Comment by mjbvz** [comment] 2019-09-25 18:52
Closing as more information is needed from the original poster to investigate

**Closed by mjbvz** 2019-09-25 18:52 UTC
Labels: needs more info
