### ISSUE TITLE
SERIOUS BUG: Node debug sometimes shows incorrect working directory

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#27391] opened 2017-05-28 07:39 UTC
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Try running a node app with configuration like this:
```
       {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/server.js"
        }
```

2. Sometimes, process.cwd() will show this:
```
/Users/Me/nodeapp
```
**^ THIS ONE IS CORRECT.**

And sometimes it will show this:
```
/Users/Me/nodeapp/bin
```
**^ THIS ONE IS INCORRECT.**

**Comment by jpike88** [comment] 2017-05-28 07:50
Made a hacky workaround for now:

```
process.chdir(process.cwd().replace('/bin', ''))
```

Obviously not ideal but it works.

**Comment by roblourens** [comment] 2017-05-29 04:06
I think it would use the script dirname if a cwd isn't specified? You can set `"cwd": "${workspaceRoot}"` to force it. Which node version?

**Comment by jpike88** [comment] 2017-05-29 05:26
7.10.0

**Comment by jpike88** [comment] 2017-05-29 06:39
More often than not, it works. But sometimes it doesn't. It's hard to reproduce, but cwd is definitely being messed with.

**Comment by weinand** [comment] 2017-05-29 12:30
If `cwd` is not specified, node-debug uses the root of the project directory (in folder mode) or the parent directory of the `program` file. See https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L417

**Comment by isidorn** [comment] 2017-05-29 12:42
@weinand in our API it is specified that the `vscode.workspace.rootPath` is falsy when running in a no folder workspace. More details https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4490

**Comment by weinand** [comment] 2017-05-29 12:47
@jpike88 could it be that you are running VS Code in a "no workspace-folder" mode when you see that `cwd` has the value `/Users/Me/nodeapp/bin` and in a "folder mode" when you see that `cwd` has the value `/Users/Me/nodeapp`?

**Comment by jpike88** [comment] 2017-05-29 13:16
This issue occurs intermittently in a single debug session. Just restarting the debugger produces different results.

**Comment by jpike88** [comment] 2017-05-29 13:17
By single debug session I mean all in the same project session and window

**Comment by weinand** [comment] 2017-05-29 13:18
How do you restart the debugger?

**Comment by jpike88** [comment] 2017-05-29 13:31
fn+f5 usually, sometimes I hit the restart button as well

**Comment by dregorox** [comment] 2017-06-22 00:47
Hi, I don't know if is the same bug but when restarting the app (by using the restart button) VS Code changes the current working directory.

To reproduce:

1.- Create a project like this:
```
bug
|
|--- app
|        |----- index.js
|---- .vscode
|         |------  launch.json
```

index.js contains:

```javascript
console.log(process.cwd());
```

Inside launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app/index.js"
        }
    ]
}
```

2. Open VSCode, and open the `bug` folder

3. Debug the application (F5)
  - You will see /path/to/bug (On the debug console)
  - The app is still running.

4. Restart the application using the restart button.
  - You will see /path/to/bug/app and the expected value is /path/to/bug

**Comment by weinand** [comment] 2017-06-23 21:53
@isidorn this "cwd" discrepancy is a consequence of the fact that we do not call the `startSession` hook on restart. On session start the launch config is passed to the `startSession` hook which adds the missing `cwd` by using the workspaceRoot. On Restart the `startSession` hook is not called and the missing `cwd` is fixed by node-debug DA which uses the parent directory of the `program` file. 

I still think that not calling `startSession` hook on Restart is the right thing to do. But I wonder why we are not using the launch config returned from the `startSession` hook for subsequent restarted sessions?

**Comment by isidorn** [comment] 2017-06-26 07:49
@weinand because he is using an old version of vscode, in the latest (insider) this should be fixed and we would use the config returned by the `startSession`

**Comment by weinand** [comment] 2017-06-26 08:52
I've verified that this is fixed.

**Closed by weinand** 2017-06-26 08:52 UTC
Labels: bug, debug
