### ISSUE TITLE
Add bread crumbs support

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#21607] opened 2017-03-01 07:53 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (40fecfaa77f01672e8a147be71f6f7ccb9cf8a12, 2017-02-27T14:09:29.088Z)
- OS Version: Darwin x64 16.5.0

Add bread crumbs support like jetbrain idea IDE or chrome element inspects!

**Comment by isidorn** [comment] 2017-03-01 09:19
Can you please elaborate on the feature. What does it do exactly?

**Comment by isidorn** [comment] 2017-03-06 15:05
Closing until more data is provided.

**Comment by leaxoy** [comment] 2017-03-07 01:32
Bread is indicate cursor location in a file, or file path.
![](http://o8z0dg641.bkt.clouddn.com/WX20170307-093101@2x.png)

**Comment by isidorn** [comment] 2017-03-07 09:39
fyi @bpasero

**Comment by luqmanrom** [comment] 2017-10-02 19:45
Does VSCode have the file breadcrumbs ?

**Comment by isidorn** [comment] 2017-10-02 21:20
@luqmanrom no, this is an open feature request.

**Comment by luqmanrom** [comment] 2017-10-02 22:16
Oh I am just curious, because the attached picture only highlighted the function breadcrumbs

**Comment by mjbvz** [comment] 2017-11-09 01:22
Duplicate of #9418

**Closed by mjbvz** 2017-11-09 01:22 UTC
Labels: duplicate, feature-request, workbench
