### ISSUE TITLE
VSCode terminal hangs after resizing the terminal window during git diff

### ISSUE THREAD

**Issue by A-l-e-x-a-n-d-e-r** [microsoft/vscode#200988] opened 2023-12-15 17:06 UTC
Issue #199231 has NOT been resolved. I did what I was told to do, i.e. my Windows 10 is fully up-to-date and my VSCode as well, but the problem still persists.

Also, in #199231, it clearly says "OS: Windows_NT x64 10.0.**19045**", so why would you assume it's a winpty issue if winpty is only used before 18309?

**Comment by meganrogge** [comment] 2023-12-15 18:19
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-12-15 18:19 UTC
