### ISSUE TITLE
Avoid sync fs-call at startup perf

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16391] opened 2016-12-02 15:47 UTC
From https://github.com/Microsoft/vscode/issues/16382

[`exthost.api.impl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L450) does a `fs.realPathSync` for each extension on startup of the extension host main.

**Comment by jrieken** [comment] 2016-12-02 16:07
dupe of #16388

**Closed by jrieken** 2016-12-02 16:07 UTC
Labels: perf
