### ISSUE TITLE
Grid: centered editor layout has weird resize behaviour when limit is hit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67360] opened 2019-01-29 10:51 UTC
Refs: #67308

This may also be @isidorn 

* enable workbench grid layout
* enter centered editor layout
* make the editor layout small (from the left sash) and continue
* you start to move the editors around

![grid-tw](https://user-images.githubusercontent.com/900690/51903336-2f8b6880-23bc-11e9-946b-4b9761a7d29b.gif)

**Comment by joaomoreno** [comment] 2019-02-19 10:39
Broken by c01cf1d166bf33a7efc69d3db9c7774af4ee6ea2

**Comment by joaomoreno** [comment] 2019-02-22 17:28
@sbatten We talked about how this was caused by the sloppy snapping feature currently implemented in the split view. We decided not to undo this otherwise the experimental Grid loses snapping. But after self hosting on the experimental Grid a full day, I've gotten multiple situations in which I would hide the view using snapping and then I couldn't get it back no matter what. I had to reload the window each time. Because of that and because of this issue, I decided to revert the commit. So we won't have snapping in the experimental Grid feature for the next stable milestone which, considering the reload issue I just experienced today many times, I think is an OK compromise. That and we get to close this bug! Let me know if you disagree.

**Closed** 2019-02-22 17:31 UTC
Labels: bug, splitview
