### ISSUE TITLE
Clinking on a completion proposal inserts different result

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#26758] opened 2017-05-16 15:25 UTC
- install the Java language server (Redhat)
- open code assist here
```
package com.aeschli.testapp;

public class TestHelper {

    public static <T> boolean isEquals(T t, T u) {
        return t.|<code assist here
```

- use the cursor to find `toString` press enter. All correctly inserted.
![image](https://cloud.githubusercontent.com/assets/6461412/26114011/7e0b315c-3a5c-11e7-8bf9-223596670454.png)
- use the mouse and click on the `toString` proposal. This inserts more (looks like the label)
![image](https://cloud.githubusercontent.com/assets/6461412/26114058/a0f85672-3a5c-11e7-8dc5-f90e22a8a303.png)

**Comment by jrieken** [comment] 2017-05-16 15:55
This is caused by the extension, I'd say they update the label in the `resolve` code path.


![screen shot 2017-05-16 at 17 54 42](https://cloud.githubusercontent.com/assets/1794099/26115625/d2e43cce-3a60-11e7-9c6d-fe771c525fda.png)

**Comment by aeschli** [comment] 2017-05-17 06:39
Ok, it seems the Java extension sets the text edit only on resolve. They also compute stuff like additional imports and rely on resolve to be called before an item is applied.

Looking at the language server trace, it seems we actually call resolve, but then cancel it right away.
```
[Trace - 8:32:24 AM] Sending request 'completionItem/resolve - (49)'.
Params: {
    "label": "toString() : String",
    "detail": "Object",
    "insertTextFormat": 1,
    "kind": 3,
    "sortText": "zzzzzzzadf",
    "data": {
        "decl_signature": "Ljava.lang.Object;",
        "signature": "()Ljava.lang.String;",
        "name": "toString",
        "pid": "3",
        "rid": "2",
        "uri": "file:/home/aeschli/workspaces/samples/test-app/src/test/java/com/aeschli/testapp/TestHelper.java"
    }
}


[Trace - 8:32:24 AM] Sending notification '$/cancelRequest'.
Params: {
    "id": 49
}
```

**Comment by jrieken** [comment] 2017-05-17 06:56
Yeah, it's a little under-specified. The initial motivation for *resolve* was to load more doc, but not to resolve the actual text edit or its range. Therefore we don't always call resolve, esp when we think the item is complete enough to be inserted. Unsure what to do, some field are actually not good to be rewritten during resolve, esp those that affect filtering and sorting...

**Comment by aeschli** [comment] 2017-05-17 07:26
The spec is very vague and talks about complete and incomplete items. 
I'd be in favor of ensuring that resolve is called before an item is applied.

**Comment by aeschli** [comment] 2017-05-17 07:26
Ok to move back to you?

**Comment by jrieken** [comment] 2017-05-17 09:49
> I'd be in favor of ensuring that resolve is called before an item is applied.

Not so sure yet... When the item already appeared complete esp when it can be inserted I was doubt that we should make yet another IPC-call before inserting the text.

**Comment by jrieken** [comment] 2017-11-20 08:53
this is fixed with https://github.com/Microsoft/vscode/pull/38655

**Closed by jrieken** 2017-11-20 08:53 UTC
Labels: suggest, under-discussion
