### ISSUE TITLE
Crashes when opening c and header files

### ISSUE THREAD

**Issue by git-tiger** [microsoft/vscode#76579] opened 2019-07-04 09:24 UTC
Using Version 1.36.0

VScode is now failing to open some files. 
It hangs and displays the "The window is no longer responding" dialog box.
Although, it only happens with some files, not all. Quite hard to single out why.
I have platformio installed.

**Comment by bodhinandach** [comment] 2019-07-04 10:07
I am also having the same problem for some c header file after the June 2019 (v1.36) update is installed.

**Comment by js2854** [comment] 2019-07-05 01:17
I had the same problem. Some cpp files didn't open properly.

**Comment by alexr00** [comment] 2019-07-05 09:57
Can you provide example files? This is likely a grammar issue and examples are the only way to track those down.

**Comment by git-tiger** [comment] 2019-07-06 00:52
this is code that crashes vscode. Line is commented out, and working line below that. 

`#ifdef DEBUG_UART_PORT
    DEBUG_UART_PORT.print( F( "\033[2J" ) );
    //DEBUG_UART_PORT.print( F( "\r*********************** Program Info ***********************\r\n" ) );
    DEBUG_UART_PORT.print( F( "\r\n******* Program Info *******\r\n") );
    DEBUG_UART_PORT.printf( "CHIP ID\t\t\t\t: %x\r\n", ESP.getChipId() );`

**Comment by jeff-hykin** [comment] 2019-07-06 14:35
This is definitely an issue with the C++ grammar, and we're taking a look into it now. It's related to the large number of back-to-back *'s

**Comment by alexr00** [comment] 2019-07-08 10:17
We are rolling back the C++ grammar to the version from 1.35 for the 1.36.1 recovery release. The issue will be fixed with 1.36.1. In insiders, I'll pull in the fix from the C++ grammar. Duplicate of #76774 in VS Code.

**Closed by alexr00** 2019-07-08 10:17 UTC
Labels: needs more info

**Comment by arendst** [comment] 2019-07-08 12:52
Have crashes too.

When will 1.36.1 be released? As now it is unusable and the only way to go forward is installing a previous release.

**Comment by alexr00** [comment] 2019-07-08 14:16
@arendst 1.36.1 should be released in the next day or two. In the mean time, you could try the next [Insiders ](https://code.visualstudio.com/insiders/)build. It should be available in the next 24 hours. I pulled the updates to the grammar in to master with 8200277bb1a7d8d6dd91d62eb0bdec674deba8d3.  There is a known issue for coloring macros, but I'll pull in the fix as soon as its ready. Insiders installs side by side with Stable so you can have both. We also don't have a lot of C++ devs using Insiders, so having more people use it will help catch grammar issues earlier.

**Comment by arendst** [comment] 2019-07-08 14:24
Thx. For now I've gone back to 1.35.1 and set updates to manual.

**Comment by jeff-hykin** [comment] 2019-07-08 16:49
@arendst You can also install [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) and it will get you the latest C++ syntax as soon as they're made.

**Comment by u3IFw2wfJ** [comment] 2019-08-05 23:45
I have the same problem when opening this: 
https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h

**Comment by jeff-hykin** [comment] 2019-08-06 02:36
I am able to reproduce. I opened up a new issue to track it, we'll get to work on it. Its likely related to the repeating ='s or repeating #'s inside the comments.
