### ISSUE TITLE
Monaco API Request: "More" and “Back” Links in Suggestions

### ISSUE THREAD

**Issue by tracksaw** [Microsoft/vscode#67477] opened 2019-01-29 19:57 UTC
The headered list (https://github.com/Microsoft/vscode/issues/67474) provides a list of the most likely items under each headered category. In most cases a “More” link is shown at the bottom. When clicked, the “More” link should switch to a display of all the items for the category that match the user input.

For instance, if the user clicked the “More Data Items…” button in Figure 1 the list would change as shown below.

This list is typically much longer than the original categorical list, and a scrollbar is likely in the list display.

We sometimes want to display multiple headered categories even in the “more” list. 

### Feature Requested

Allow “more” links in the list that switch the list content as described above.

Allow “back” links in the list that switch the list from the “more” content back to the original categorical content.

Allow headers in the “more” list.

Links should be identifiable for styling purposes.

The entire list content including all levels could be settable up-front. Alternatively the switch between categorical and “more” lists (and back) could be done in code by causing the suggestions provider to provide different content.

![bqleditor-search-for-m-more](https://user-images.githubusercontent.com/29378846/51936408-1f808280-23d6-11e9-8449-1044ed924ba2.png)

**Comment by jrieken** [comment] 2019-01-30 16:37
merging this into https://github.com/Microsoft/vscode/issues/67474 as that's required first

**Comment by jrieken** [comment] 2019-01-30 16:37
/duplicate of https://github.com/Microsoft/vscode/issues/67474

**Closed** 2019-01-30 16:37 UTC
Labels: *duplicate, feature-request, suggest
