### ISSUE TITLE
Workspace launch not following default terminal to load

### ISSUE THREAD

**Issue by thomascarlyonrussell** [microsoft/vscode#132284] opened 2021-09-03 17:59 UTC
VScode 1.60 
Had to go back to 1.59 and started working again.  

Expected:
On launch it starts a CMD terminal as that was the default terminal profile

Observed:
On launch it starts PowerShell terminal despite default terminal profile as CMD.

All settings files were checked and CMD was the default.  Tested by installing 1.59 and worked properly by launching CMD in terminal on load.

**Comment by IllusionMH** [comment] 2021-09-03 18:02
/duplicate of #128763 (reproducible not only for remote)

**Closed** 2021-09-03 18:02 UTC
Labels: *duplicate
