### ISSUE TITLE
Dragging a cell sometimes doesn't work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119683] opened 2021-03-23 18:31 UTC
Testing #119118

It looks like either the cursor or the hit target aren't correct, since it makes it look like you can drag, but you can't
![drag](https://user-images.githubusercontent.com/641685/112199278-5e8c7600-8be4-11eb-95f4-3742b90d2355.gif)

**Comment by rebornix** [comment] 2021-03-24 01:09
oh no, it's the `+ code` toolbar ;(

**Comment by misolori** [comment] 2021-03-24 01:33
@eamodio does this repro is you disable the new notebook markdown renderer `"notebook.experimental.useMarkdownRenderer": false`?

**Comment by rebornix** [comment] 2021-03-24 02:43
Verified that I can reproduce with `useMarkdownRenderer` to `true` but not reproduce when it's set to `false`.

**Comment by eamodio** [comment] 2021-03-24 02:55
Yeah, I can only repro with the new renderer

**Comment by mjbvz** [comment] 2021-03-30 22:39
Duplicate of #117489

**Closed by mjbvz** 2021-03-30 22:39 UTC
Labels: bug, notebook, notebook-markdown
