### ISSUE TITLE
Spurious intellisense/code completion in Lua code

### ISSUE THREAD

**Issue by Azarien** [microsoft/vscode#109648] opened 2020-10-29 07:53 UTC
Issue Type: <b>Bug</b>

Unwanted intellisense box appears often when scrolling through Lua code with down arrow key.

1. Enter this code:
```lua
function end1()
end

function end2() -- line 4
end

function end3()
end
```

2. Save it as .lua file or choose Lua language mode manually.
3. Put the cursor at the end of line 4
4. Press the down arrow key.
5. Notice that Intellisense box appears and it is impossible to navigate further down without pressing Esc.

VS Code version: Code - Insiders 1.51.0-insider (2ee8b8c645ec8ab54304bacae7aa979c1d9c647a, 2020-10-29T06:09:07.226Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.84GB free)|
|Process Argv|--crash-reporter-id 34a38cde-41ff-40ec-b4b8-3927484eacbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.10.332292344
shader|sle|1.1.4

</details>

**Comment by alexr00** [comment] 2020-10-29 08:54
Does this reproduce if you disable all extensions?

**Comment by Azarien** [comment] 2020-10-29 10:27
Yes.

**Comment by alexr00** [comment] 2020-10-29 10:44
Thanks for confirming. Looks like a duplicate of https://github.com/microsoft/vscode/issues/109634

**Closed by alexr00** 2020-10-29 10:44 UTC
Labels: needs more info
