### ISSUE TITLE
Ability to mark abandoned extensions 

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#177795] opened 2023-03-21 11:57 UTC
I feel like open source and VS Code extensions have this problem of not beeing properly curated by Microsoft.

Like this: https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml&ssr=false#review-details

It's abandoned and still nr 3 when you write `ext:toml`

<img width="440" alt="Zrzut ekranu 2023-03-21 o 12 54 55" src="https://user-images.githubusercontent.com/3521624/226598792-b88d0b48-03a2-465e-a027-7b703055d73c.png">

I think MS could make this process better or AS I said make it curable that we will have for ex. JavaScript Ext. Week where we promote good Extensions and mark unmaintainable as not recomended.

What do you think about it?

**Comment by usernamehw** [comment] 2023-03-21 12:03
https://github.com/microsoft/vscode-discussions/discussions/1?sort=old

**Comment by isidorn** [comment] 2023-03-21 13:27
Closing as duplicate of https://github.com/microsoft/vscode-discussions/discussions/1

**Closed by isidorn** 2023-03-21 13:27 UTC
