### ISSUE TITLE
trees-views: icons are not updated when the tree row is active

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode#91765] opened 2020-02-28 16:04 UTC
The problem occurs when a `tree-view` row is active and it contains icons (ex: `npm scripts`, `scm`).
At this point (since the color theme is light), the icons are dark, however, when a row is active these icons are hard to see and generally look odd).

I understand this change may be difficult as there might not be a clear way to determine if a theme uses a dark active color for active tree rows.

In the following screenshot, I'd expect that the icons are white (`active foreground color`) so they are more visible provide a better UX.

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/75564112-862d0100-5a19-11ea-9ab9-eb8b15beae6a.png)

</div>

- VSCode Version: 1.42.1
- OS Version: Ubuntu Linux (16.04)

Steps to Reproduce:

1. start a workspace with a `package.json` describing some `scripts`.
2. ensure that a light theme is used (ex: Light+ (default light))
3. in the `explorer`, open the `npm scripts` view
4. click a node (making it active) and notice the icons are not updated and are hard to see

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment] 2020-03-03 18:27
Duplicate of #90911

**Closed by misolori** 2020-03-03 18:27 UTC
