### ISSUE TITLE
Task quick access has misaligned groups

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#93997] opened 2020-03-31 16:52 UTC
Testing #93746
Maybe a dupe since I know this was brought up in the UX discussion, but I'd really like to find a better presentation here:

![image](https://user-images.githubusercontent.com/6561887/78053318-6bb6b200-734e-11ea-8e2e-f0537ebe0570.png)

**Comment by alexr00** [comment] 2020-04-01 08:53
@chrmarti this is coming from quick pick. If there's an icon button on an item that also has a group then the group is aligned differently.

**Comment by bpasero** [comment] 2020-04-01 09:57
Related https://github.com/microsoft/vscode/issues/94131

Though I do not think this is a bug, what would be the alternative? Indent all groups to the same level? Could also look bad.

**Comment by alexr00** [comment] 2020-04-01 10:09
Ideally I think it should only shift the group label when the item that the label is on is selected. No need to indent when the icon isn't even showing.

**Comment by bpasero** [comment] 2020-04-01 10:14
@alexr00 but check https://github.com/microsoft/vscode/issues/92489#issuecomment-598100778 for examples where that solution is less than ideal

**Comment by sbatten** [comment] 2020-04-01 16:00
Can you place more than one action there?

If not, could we just reduce the padding/margins around the actions and have a smaller reserved space?

If so, can we just replace the group when the actions show up?

**Comment by chrmarti** [comment] 2020-04-01 19:56
I'd expect aligning the group labels to look better. (To throw in my 2 cents.)

/cc @isidorn

**Comment by bpasero** [comment] 2020-04-02 05:13
@chrmarti please clarify, do you want to go back to how it was by showing the group labels always at the end until actions appear (e.g. on hover) or indent all groups on the same level?

**Comment by isidorn** [comment] 2020-04-02 08:59
Agree with @chrmarti the group labels should be aligned, and the hovering should not make everything jump.
Idealy on hover the group name would be invisble and the action would take its place. Imho that would provide the least visual noise (though I might be wrong).
I also hate our Restart frame solution in the Call Stack view.

**Comment by bpasero** [comment] 2020-04-02 09:02
> Idealy on hover the group name would be invisble and the action would take its place

I do not understand how that works for the default case where first entry is selected and thus actions appear: 

![image](https://user-images.githubusercontent.com/900690/78230244-5ae27980-74d1-11ea-8e77-5df9be436f72.png)

This would mean we would always hide the group label for the first entry?

**Comment by isidorn** [comment] 2020-04-02 09:06
@bpasero yeah, it does not work well for the focus case. I agree.
Hidding the group for the first entry does not make sense.
My suggestion only somewhat makes sense for the hover case. However having two different experiences for focus and hover does not make sense.

**Comment by chrmarti** [comment] 2020-04-02 10:54
I think the old approach scaled better with the number of actions (imagine 3 or more actions reserve space) and also with the number of group labels (since only one needs to free space for actions).

**Comment by bpasero** [comment] 2020-04-02 11:20
I will revert my change. 

/duplicate of https://github.com/microsoft/vscode/issues/94131

**Closed** 2020-04-02 11:20 UTC
Labels: *duplicate, quick-pick, under-discussion
