### ISSUE TITLE
my mac m3 pro crashs always

### ISSUE THREAD

**Issue by Bader975** [microsoft/vscode#221947] opened 2024-07-17 14:04 UTC
Type: <b>Performance Issue</b>

apple said my mac m3 pro crashs becuse of vscode can you fix it please

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 6, 4|
|Memory (System)|18.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id de1dc57c-6b38-40f4-af36-f5616678aca0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   166	   499	code main
    6	    74	   652	   gpu-process
    0	    37	   654	   utility-network-service
    0	   240	   660	window [1] (Welcome)
    9	   111	   680	shared-process
    0	     0	  1884	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    55	   681	fileWatcher [1]
    5	   295	   682	extensionHost [1]
    0	    37	   734	     electron-nodejs (serverMain.js )
    0	    55	   891	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=682
    0	    37	  1045	     electron-nodejs (eslintServer.js )
    0	    18	  1051	     /Users/bader/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.180.0/aarch64-apple-darwin/TabNine --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.91.1 pluginVersion=3.128.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=a9897fcb54d1ca19204ddc250622026a1712853aca63238242abc1835d7de66f vscode-is-new-app-install=false vscode-session-id=8a7ffef7-26b1-4f4d-a665-ba75ab1de1091721221947518 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0
    0	    18	  1083	       /Users/bader/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.180.0/aarch64-apple-darwin/WD-TabNine --tls_config insecure=false --client vscode --client-metadata clientVersion=1.91.1 pluginVersion=3.128.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=a9897fcb54d1ca19204ddc250622026a1712853aca63238242abc1835d7de66f vscode-is-new-app-install=false vscode-session-id=8a7ffef7-26b1-4f4d-a665-ba75ab1de1091721221947518 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0
    0	    37	  1085	       /Users/bader/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.180.0/aarch64-apple-darwin/TabNine --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.91.1 pluginVersion=3.128.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=a9897fcb54d1ca19204ddc250622026a1712853aca63238242abc1835d7de66f vscode-is-new-app-install=false vscode-session-id=8a7ffef7-26b1-4f4d-a665-ba75ab1de1091721221947518 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 --no_bootstrap
    0	   295	  1096	         /Users/bader/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.180.0/aarch64-apple-darwin/TabNine-deep-local --settings /Users/bader/Library/Preferences/TabNine/local.settingsce94127bSmall --settings-version 1 --client vscode --client-metadata clientVersion=1.91.1 pluginVersion=3.128.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=a9897fcb54d1ca19204ddc250622026a1712853aca63238242abc1835d7de66f vscode-is-new-app-install=false vscode-session-id=8a7ffef7-26b1-4f4d-a665-ba75ab1de1091721221947518 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 --tls_config insecure=false
    0	    55	  1098	     /Users/bader/.vscode/extensions/codeium.codeium-1.8.83/dist/1e20fa38ede961073c4494bc9637bffe13e6a8f4/language_server_macos_arm --api_server_url https://server.codeium.com --manager_dir /var/folders/nj/lnn4wv816kd_fd7flcdcf9pc0000gn/T/59e10b5b-9b49-4f56-bba8-f980b3880908/codeium/manager --enable_chat_web_server --enable_lsp --inference_api_server_url https://inference.codeium.com --database_dir /Users/bader/.codeium/database/9c0694567290725d9dcba14ade58e297 --enable_index_service --enable_local_search --search_max_workspace_file_count 5000 --indexed_files_retention_period_days 30 --sentry_telemetry
    1	   111	  1107	       /Users/bader/.vscode/extensions/codeium.codeium-1.8.83/dist/1e20fa38ede961073c4494bc9637bffe13e6a8f4/language_server_macos_arm --api_server_url https://server.codeium.com --manager_dir /var/folders/nj/lnn4wv816kd_fd7flcdcf9pc0000gn/T/59e10b5b-9b49-4f56-bba8-f980b3880908/codeium/manager --enable_chat_web_server --enable_lsp --inference_api_server_url https://inference.codeium.com --database_dir /Users/bader/.codeium/database/9c0694567290725d9dcba14ade58e297 --enable_index_service --enable_local_search --search_max_workspace_file_count 5000 --indexed_files_retention_period_days 30 --sentry_telemetry --run_child --limit_go_max_procs 4 --random_port --random_port_dir=/var/folders/nj/lnn4wv816kd_fd7flcdcf9pc0000gn/T/59e10b5b-9b49-4f56-bba8-f980b3880908/codeium/manager/child_random_port_1721221963009075000_649815630632359768 --manager_lock_file=/var/folders/nj/lnn4wv816kd_fd7flcdcf9pc0000gn/T/59e10b5b-9b49-4f56-bba8-f980b3880908/codeium/manager/locks/manager.lock --child_lock_file /var/folders/nj/lnn4wv816kd_fd7flcdcf9pc0000gn/T/59e10b5b-9b49-4f56-bba8-f980b3880908/codeium/manager/locks/child_lock_1721221963009157000_2444243212644789201
    0	    92	  1874	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx-html-tags|ang|1.0.1
ng-template|Ang|18.1.2
vscode-color|ans|0.4.5
blackbox|Bla|1.3.63
vscode-tailwindcss|bra|0.13.20
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
codeium|Cod|1.8.83
vscode-eslint|dba|3.0.10
javascript-ejs-support|Dig|1.3.3
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
vscode-expo-tools|exp|1.5.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
live-sass|gle|6.1.2
firebase-snippets|has|0.0.1
vscode-react-typescript|inf|1.3.1
better-cpp-syntax|jef|1.27.1
Angular2|joh|18.0.2
intellij-idea-keybindings|k--|1.7.2
next-js-ts-snippets|loc|2.0.3
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
million-lint|mil|0.1.12
mongodb-vscode|mon|1.6.1
vscode-docker|ms-|1.29.1
csharp|ms-|2.34.12
vscode-dotnet-runtime|ms-|2.0.9
debugpy|ms-|2024.8.0
isort|ms-|2023.10.1
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.375.1
remote-wsl|ms-|0.88.2
cpptools|ms-|1.20.5
js-debug-nightly|ms-|2024.7.1517
notepadplusplus-keybindings|ms-|1.0.7
vscode-typescript-next|ms-|5.6.20240716
vscode-react-native|msj|1.13.0
mysql-autocomplete|nes|0.5.0
polacode|pnp|0.3.4
prisma|Pri|5.17.0
prisma-insider|Pri|31.0.6985
vscode-thunder-client|ran|2.24.12
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
vscode-camera|san|1.0.0
angular-cli|seg|0.0.19
html5-boilerplate|sid|1.1.1
js-jsx-snippets|sky|11.1.3
tabnine-vscode|Tab|3.129.0
ejs-snippets|The|0.7.0
vsfire|tob|1.4.1
pdf|tom|1.2.2
errorlens|use|3.20.0
vscode-lldb|vad|1.10.0
vscode-icons|vsc|12.8.0
console-ninja|Wal|1.0.330
quokka-vscode|Wal|1.0.647
wallaby-vscode|Wal|1.0.379
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.5.4
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
4930e709:31092288

```

</details>

**Comment by Bader975** [comment] 2024-07-17 14:11
https://github.com/user-attachments/assets/c84e0cfc-ef81-4421-8fc1-536fb6402270

**Comment by deepak1556** [comment] 2024-07-22 07:33
I don't see VS Code being mentioned in the attached video, can you share the details that point to VS Code as the root cause.

**Comment by Bader975** [comment] 2024-07-22 19:04
Apple said is the Vcode cus this crash while using it  , and said we can't do anything .
this all the info i can provide to you @deepak1556 

<img width="1502" alt="Screenshot 1445-12-12 at 3 44 38 AM" src="https://github.com/user-attachments/assets/ce121e60-58f6-457e-b905-ad15f85f8278">

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/e2f1c25c-c3e1-43a5-b3e1-331ac63c3fb1">

**Comment by deepak1556** [comment] 2024-07-24 05:11
Can you check if the issue persists when extensions are disabled ?

**Comment by Bader975** [comment] 2024-07-24 05:56
> Can you check if the issue persists when extensions are disabled ?


i can't tell , cuz i cna't work without the extensions.

**Comment by deepak1556** [comment] 2024-07-24 13:04
Sorry without crash reports or a repro it is hard for us to debug this issue further.

**Comment by Bader975** [comment] 2024-07-25 13:49
![image](https://github.com/user-attachments/assets/aee48e35-393e-4e52-b25b-9126b77c3bb0)

**Comment by deepak1556** [comment] 2024-07-26 07:53
The application path in the attached screenshot does not relate to Visual Studio Code, closing as not actionable.

**Closed by deepak1556** 2024-07-26 07:53 UTC
Labels: info-needed
