### ISSUE TITLE
Extension host keeps crashing and failing to start

### ISSUE THREAD

**Issue by prryplatypus** [microsoft/vscode#167610] opened 2022-11-29 19:19 UTC
Type: <b>Bug</b>

When opening VSCode, extensions fail to start and a few minutes after a message appears saying that the extension host failed to start. See logs attached:

![imagen](https://user-images.githubusercontent.com/25409753/204625834-c447fc13-fa66-4de3-90fc-e34a3a0288aa.png)

VS Code version: Code - Insiders 1.74.0-insider (8b9891739b703b50547f506a7e2bc9565e52beff, 2022-11-29T07:05:56.358Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.87GB free)|
|Process Argv|D:\\Users\\prryplatypus\\Desktop\\sanic-forum --crash-reporter-id 1a3a0683-4478-42bb-857e-35078cb854ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.1.1
copilot|Git|1.61.7372
discord-vscode|icr|5.8.0
flake8|ms-|2022.7.13121011
isort|ms-|2022.9.13271012
python|ms-|2022.19.13321005
vscode-pylance|ms-|2022.11.32
remote-containers|ms-|0.265.0
remote-wsl|ms-|0.72.0
material-icon-theme|PKi|4.22.0
developer-theme-dark|Raj|5.0.0
svelte-vscode|sve|106.2.0
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by alexdima** [comment] 2022-12-01 09:38
Duplicate of #167634

**Closed by alexdima** 2022-12-01 09:38 UTC
