### ISSUE TITLE
List multi-select does not differentiate between selected and non-selected states

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95781] opened 2020-04-21 15:01 UTC
Repro:

- Navigate the explorer
- Use `toggleSelection` (ctrl+shift+enter) to toggle items, they look the same when toggled on or off

I have toggleSelection bound to ctrl+space in the gif, notice how hover.ts looks the same while selected:

![2bc7562f-7ac4-41b3-b2c5-65d2f48e5f3d](https://user-images.githubusercontent.com/2193314/79881469-14808c00-83a6-11ea-8a5b-43ae6a896c1b.gif)

Windows explorer for reference:

![image](https://user-images.githubusercontent.com/2193314/79881276-d97e5880-83a5-11ea-9484-1d503c147c69.png)

![image](https://user-images.githubusercontent.com/2193314/79881303-e00cd000-83a5-11ea-81b5-bf595e510c5c.png)

This feature doesn't appear to be keyboard accessible on finder.

**Comment by joaomoreno** [comment] 2020-04-23 09:22
We used to have a third color for both focused and selected. This was eventually removed because it was confusing. 🤷‍♂️ 

In any case, I'd close this as a dupe of https://github.com/microsoft/vscode/issues/95768

**Closed by joaomoreno** 2020-04-23 09:22 UTC
