### ISSUE TITLE
Suggestion of quickOpen

### ISSUE THREAD

**Issue by zouyx** [Microsoft/vscode#10072] opened 2016-08-03 10:23 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Now quickOpen first item is current file
can it change to previous one.
not current file like Idea.
:smile:

**Comment by wallverb** [comment] 2016-08-03 11:11
That's great idea - both Atom and Sublime do it that way

**Comment by zouyx** [comment] 2016-08-05 03:32
@wallverb 
thank you.
:smile:

**Comment by wallverb** [comment] 2016-08-05 12:09
Seems like duplicate of https://github.com/Microsoft/vscode/issues/6923

**Closed** 2016-08-06 13:42 UTC
