### ISSUE TITLE
Getting "unable to get local issuer certificate" error while installing extension

### ISSUE THREAD

**Issue by mlakmal** [Microsoft/vscode#17187] opened 2016-12-14 17:35 UTC
- VSCode Version: 1.8.0.-insider
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Getting "unable to get local issuer certificate" error while trying to install extension. 

VSCode settings already has below option. 

i am not using proxy url as we don't have any proxy url. (im under company proxy (Blue Coat SSLV) and its setup through pac file. all requests need to approve company root certificate which is self signed. i think i am getting above error because of this. )

"http.proxyStrictSSL": false

we had the same issue earlier with node npm install. after setting npm config with below settings it started to work. 

npm config set strict-ssl false

Do we have any steps to enable strict-ssl globally for VSCode (even if http.proxy value is empty)

**Comment by jordang87** [comment] 2016-12-14 20:05
I have VS Code 1.7.2 with Windows 10 x64 and I too am also getting the "unable to get local issuer certificate". I'm also behind Blue Coat as well.

**Comment by joaomoreno** [comment] 2016-12-15 08:38
Did this stop working somehow or you just tried it out?

**Comment by joaomoreno** [comment] 2016-12-15 08:38
Possible duplicate of #7140

**Comment by jordang87** [comment] 2016-12-15 12:27
I was just trying it out. I tried Code out when it first came out but ran across issues where the extension list wouldn't even load. Then I gave up on it until recently and tried again. Now the extension list loads but any time I try to install I get "unable to get local issuer certificate".

**Comment by mlakmal** [comment] 2016-12-19 20:43
@joaomoreno this used to work until last week. where our company updated the proxy certificate with self signed cert. after that this is not working,

**Comment by mlakmal** [comment] 2017-03-30 19:00
did someone added a fix for this in v1.11.0-insider ? i am able to update the vs code and extensions in latest insider edition through VPN...

**Comment by jordang87** [comment] 2017-03-30 19:43
I'm on Version 1.10.2 and it works for me. Maybe it was a back end change?
That or maybe my enterprise settings at work changed.

**Comment by joaomoreno** [comment] 2017-07-03 12:25
Closing due to inactivity.

**Closed by joaomoreno** 2017-07-03 12:25 UTC
Labels: bug, proxy
