### ISSUE TITLE
Terminal doesn't show full command output

### ISSUE THREAD

**Issue by marck0z** [microsoft/vscode#111930] opened 2020-12-05 08:08 UTC
VS Code version: 1.51.1 
OS version: Linux x64 5.9.11-arch2-1

**Steps to Reproduce:**

1. Create a program that prints a lot of lines and then exits, for example a program that prints 1000 lines:
```
    line 1
    line 2
    line 3
    ...
    line 1000
```
2. Create a shell task that runs that program
3. Execute the build task

**Expected behavior**

The terminal should show 1000 lines of text

**Actual behavior**

The terminal only shows the first 400 to 1000 lines, randomly changing in each run, sometimes the last printed line is incomplete

**Additional information**

If we add a delay of 100 milliseconds or more at the end of the program, the terminal shows the 1000 lines correctly
This is not fixed by having a greater value in Scrollback, the first printed lines are not the problem but the missing last lines

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2020-12-17 18:28
Duplicate of #95021

**Closed by meganrogge** 2020-12-17 18:28 UTC
Labels: *duplicate, bug, integrated-terminal
