### ISSUE TITLE
Debug viewlet gear layout changed

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89079] opened 2020-01-22 11:01 UTC
Version: 1.42.0-insider
Commit: 68615717819b3731705d92ec06b52edd47665291
Date: 2020-01-22T05:26:38.760Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

---

Old:

![image](https://user-images.githubusercontent.com/4033249/72888895-c90b0300-3d0e-11ea-9422-690de69b56db.png)

New:

![image](https://user-images.githubusercontent.com/4033249/72888926-d922e280-3d0e-11ea-85b3-4288705e56f3.png)

Is this an intentional change, or is it caused by the view container work?

**Comment by isidorn** [comment] 2020-01-22 11:03
View container bug. Duplicate of https://github.com/microsoft/vscode/issues/89041

**Closed by isidorn** 2020-01-22 11:03 UTC
