### ISSUE TITLE
Support ARM64 for VS Code Server

### ISSUE THREAD

**Issue by idanpa** [Microsoft/vscode#73191] opened 2019-05-02 20:28 UTC
[Remote Development](https://code.visualstudio.com/docs/remote/ssh) is great, thanks for adding it.
One of the cases where you need an external machine to test your code is when developing for different architectures (e.g. ARM64).
Assuming the VS Code Server has no Electron front-end (see #33620), can you please add the support for ARM64 machines?
Currently when I try to open remote SSH to an ARM machine I get:
Can't connect to idanp@machine: unreachable or not Linux x86_64 (Linux armv7l)

**Comment by RMacfarlane** [comment] 2019-05-02 21:07
Thanks @idanpa! This looks like a duplicate of https://github.com/Microsoft/vscode-remote-release/issues/13, please add any more feedback over there.

**Closed by RMacfarlane** 2019-05-02 21:07 UTC
