### ISSUE TITLE
merge editor says 2 conflicts remain when they were both resolved manually

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#230517] opened 2024-10-04 17:05 UTC
1. have merge conflicts
2. resolve several manually
3. click the button to go to merge conflicts
4. see that they're already resolved
5. accept changes
6. see warning that there are still conflicts

I would expect manually resolved conflicts to not be counted as conflicts

edit: did I need to hit save?

![Image](https://github.com/user-attachments/assets/0965f16c-1707-46c9-9f3f-2c7a872e808b)

**Comment by hediet** [comment] 2024-12-09 11:29
Duplicate of #231072

**Closed by hediet** 2024-12-09 11:29 UTC
