### ISSUE TITLE
[rename on type] associates existing closing tag with new opening tag

### ISSUE THREAD

**Issue by azur75** [microsoft/vscode#95101] opened 2020-04-13 08:42 UTC
- VSCode Version:1.44 and 1.45.0-insider
- OS Version: Windows 10

Steps to Reproduce:
	
1. set "editor.renameOnType": true,
("editor.formatOnType" can be true or false,
"html.mirrorCursorOnMatchingTag" can be true or false.
2. have an html tag present on a line of the editor, like : 
`<em>text</em>`
3. begin typing a new instance of this same tag before the existing one : 
`<em<em>text</em>`
4. first bug : the existing closing tag gets selected !
5. close the new tag : 
`<em><em>text</em>`
6. 2nd bug : > is added after the existing closing tag : 
`<em><em>text</em>>`

It also happens on different displayed lines, when there is no CR LF between the new tag and the existing one.

Does this issue occur when all extensions are disabled?: Yes
<img width="111" alt="tag2" src="https://user-images.githubusercontent.com/62250541/79107099-0a420a80-7d74-11ea-99c3-6997f10ad23b.png">

**Comment by azur75** [comment] 2020-04-16 10:06
Actually, it happens always (when the same tag is already present somewhere below), except when one types a carriage return before typing the new opening tag.
The consequences are varied, depending on the existing tags below, on whether one types a tag nested inside an existing one etc.
Sometimes it seems to insert additional tags wrapping some parts of the code below...

**Comment by azur75** [comment] 2020-04-16 12:24
Surprise : by setting editor.renameOnType : false,
the buggy behaviour above stops. The auto-closing of tags, if set to true, works, and the closing tag is matched.
I have set back "htmlmirrorCursorOnMatchingTag": true,
but it does not seem to have any influence.

What a strange and messy implementation !

**Comment by octref** [comment] 2020-04-22 19:09
> <em<em>text</em>

In this case, the editor would think you are writing a pair of `<em       </em>`, and mark them as the same tag.

> <em>text</em>
> <em<em>text</em>

I'm not sure why you have to strangely write a new tag from this position. Why not start writing `<em>` here? `<em>|text</em>`. This feature works best for common cases and does not guarantee always ending up with correct HTML.

> 2nd bug : > is added after the existing closing tag :

Yes, the editor told you that would be the case, it marked the two regions as red, whatever you enter in one region get duplicated in the other region.

**Comment by azur75** [comment] 2020-04-22 20:37
Sorry, I really don't understand ! Where does that strange _text <em_text come from ? I wrote about _<em <em>text</em>_ , worrying that it is impossible to type a new tag before an existing one.
Do you always type new code at the end of existing code, and never in the middle of it ? Do you never add a new <h2> title before an existing one ?
Fortunately, as I wrote afterwards, by deactivating editor.renameOnType, the old behaviour of htmlmirrorCursorOnMatchingTag , which worked perfectly, comes back !

**Comment by octref** [comment] 2020-04-22 21:51
GitHub formatted them and I updated the comment.

Yes, I understand you want to add a `<h2>` into middle of `<em>text</em>`.
I believe most people would start typing `<h2>` here `<em>|text</em>`.
If you have to start typing it from here `<em|>text</em>`, I suggest that you turn off this functionality. That's where people write attributes. I'm not sure why would you try to add a tag in that position to make your HTML invalid.

**Comment by azur75** [comment] 2020-04-23 07:37
Sorry, that is not the case. in the image at the bottom of my first message, I simply wanted to type a new _h2_ tag **before** an existing one, and Code highlighted the existing closing tag together with my new opening tag, messing everything since there was the existing _h2_ opening tag inbetween. Obviously, Code closed automatically my new opening tag, since it was paired with the already existing closing tag...

The same happens when typing a new _em_ tag **before** an existing one. Even several lines before !

**Comment by octref** [comment] 2020-04-23 19:22
I see. Here are the reproducible steps:

1. With content `<div></div>`
2. Type `<div` before it so it becomes `<div<div></div>` and two regions get synced
3. Type `>` which makes it `<div><div></div>>`

I didn't run into this issue myself since I would usually just type `div` and let emmet expand that to `<div></div>`. If you are accustomed to writing the `<` and `>`, I suggest that you turn this feature off `"editor.renameOnType": false`.

**Comment by jsgoupil** [comment] 2020-04-29 20:00
This rename on type is giving me a headache.
My bug here is probably really similar to this (let me know if I should open another one), but basically the matched tags ignore the fact that they are not at the "same nested level". Which means when I delete things, I just get random tags being deleted here and there and it is not pleasant.

[video1.zip](https://github.com/microsoft/vscode/files/4554255/video1.zip)

[video2.zip](https://github.com/microsoft/vscode/files/4554256/video2.zip)

See the video here. In both cases, I delete my lines with CTRL+X.
That second video is just painful, it went to delete something super far of my view.

If this is "the expected behavior", then this feature will be turned off since it's more an annoyance than anything else.

**Comment by aeschli** [comment] 2020-06-04 20:09
duplicate of https://github.com/microsoft/vscode/issues/98053

**Closed by aeschli** 2020-06-04 20:09 UTC
Labels: bug, editor-synced-region
