### ISSUE TITLE
code . not working

### ISSUE THREAD

**Issue by rooroo224** [microsoft/vscode#165999] opened 2022-11-10 11:11 UTC
Type: <b>Bug</b>

sudo su (on wsl)
code . (not working)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (0.98GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/c/Users/BALAJIRohan/AutoML_Local/CloudWebServer --remote=wsl+Ubuntu-18.04 --crash-reporter-id 254d69d7-fb1a-44ef-8b85-b34247d4998b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 1804)|
|Memory (System)|7.63GB (3.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 1804)|
|Memory (System)|7.63GB (3.62GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
githistory|don|0.6.19
gitlens|eam|13.0.4
githd|hui|2.3.3
start-git-bash|McC|1.2.1
black-formatter|ms-|2022.6.0
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
pdf|tom|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by aeschli** [comment] 2022-11-10 13:56
The remote WSL extension can only run with the distro's default user.

**Comment by aeschli** [comment] 2022-11-10 14:03
Marking as duplicate of https://github.com/microsoft/vscode-remote-release/issues/286

**Closed by aeschli** 2022-11-10 14:03 UTC
Labels: new release
