### ISSUE TITLE
Can't install extensions through proxy on windows 

### ISSUE THREAD

**Issue by fbehrens** [Microsoft/vscode#1320] opened 2015-12-15 10:02 UTC
The List of extensions is displayed, but when I click on one iE `Elm` it shows

`Error` `getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443`

Vscode was started from the commandline  with 

    >set | grep proxy
    https_proxy=http://user:pw@ip:port
    http_proxy=http://user:pw@ip:port

System proxy is defined though an `Automatic configuration script` via th url of a *.pac file.
When I start `vscode` from start, without those  environment variables, the above error shows already when loading the list of extensions.

PS. Thanks for the great work.

**Comment by joaomoreno** [comment] 2015-12-16 09:11
Duplicate of #69.

Fix will be available at the end of December.

**Comment by polidore** [comment] 2015-12-18 14:38
+1

**Comment by idoprz** [comment] 2015-12-21 07:46
+1000 :+1:

**Comment by joevin22** [comment] 2015-12-21 14:50
i already set my environment variables proxies in os.

when i set my proxy settings in vscode (File > Preferences > User Settings )
"http.proxy": "http://usr:pwd@ip_proxy:port",
"http.proxyStrictSSL": false

i have message "getaddrinfo ENOTFOUND ip_proxy:port ip_proxy:port:port" on Windows 7.

**Comment by idoprz** [comment] 2015-12-21 15:19
I have same exact issue on win10.

**Comment by Megale** [comment] 2015-12-21 20:36
Hi everyone,

I'm using CNTLM and VS Code 0.10.5 behind my corporate proxy. I can browse the extesions but when i try to download them i get the error mentioned by @joevin22:

"ip_proxy:port ip_proxy:port:port.

 Cheers,

**Comment by CraigHumphrey** [comment] 2015-12-21 21:15
+1 VS Code 0.10.5 Win7

**Comment by jia3ep** [comment] 2015-12-22 12:35
I have the same problem.
Is there a workaround?

**Comment by ywmail** [comment] 2015-12-28 03:09
http.proxy has been set, and http.proxyStrictSSl has been set to false. Still get the error:

unable to verify the first certificate: Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)

**Comment by alexmags** [comment] 2015-12-29 09:21
+1 VS code 0.10.6 Win7
Doesn't auto detect proxy (WPAD)
After configuring proxy in User Settings VS code can't do NTLM authentication with proxy using current user credentials.  I'm using the following settings. We have SSL intercept at proxy but the cert used by proxy is trusted.  
"http.proxy": "http://webproxy.companyname.com:8080/",
"https.proxy": "http://webproxy.companyname.com:8080/",
"http.proxyStrictSSL": false,

No error message displayed, just no results if I do 
CTRL+P
ext install PowerShell

**Comment by joaomoreno** [comment] 2016-01-04 14:40
Closing as dupe of #69

**Closed by joaomoreno** 2016-01-04 14:40 UTC
Labels: bug

**Comment by Senorihl** [comment] 2017-03-02 09:47
Hi everyone, I get this errors when searching for `@popular` with VSCode launched with `--verbose` opt: 

    ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    code: 'ENOTFOUND',
    errno: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]
    ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND vortex.data.microsoft.com vortex.data.microsoft.com:443
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    code: 'ENOTFOUND',
    errno: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'vortex.data.microsoft.com',
    host: 'vortex.data.microsoft.com',
    port: 443 } ]

But my proxy is properly configured as followed : 

    {
        "http.proxy": "http://user:pass@host:port",
        "http.proxyStrictSSL": false
    }

Any idea ? Thx

**Comment by Sispheor** [comment] 2017-04-03 13:02
same for me 
```
[15770:0403/145749:INFO:CONSOLE(103)] "An unknown error occurred. Please consult the log for more details.", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (103)
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 104.45.136.42:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '104.45.136.42',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 64.4.54.254:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '64.4.54.254',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 64.4.54.254:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '64.4.54.254',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 104.45.136.42:443
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '104.45.136.42',
    port: 443 } ]
```
