### ISSUE TITLE
Reference font coincides with code font

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#93476] opened 2020-03-26 10:08 UTC
![code](https://user-images.githubusercontent.com/27546390/77634908-b326f200-6f8c-11ea-9799-7cd59a2f9bec.png)
 When using Ctrl + mouse to scroll in the editor to enlarge or reduce the editor font, the following appears:
Reference font coincides with code font
![code](https://user-images.githubusercontent.com/27546390/77634931-bd48f080-6f8c-11ea-8e7a-302e7ed805aa.png)

**Comment by 395053994** [comment] 2020-03-26 10:09
When using Ctrl + mouse to scroll in the editor to enlarge or reduce the editor font, the following appears:
Reference font coincides with code font
在编辑器中使用Ctrl+鼠标滚动放大或缩小编辑器字体的时候，出现如下的样子：
引用字体与代码字体重合了

**Comment by 395053994** [comment] 2020-03-26 10:15
在编辑器中使用Ctrl+鼠标滚动放大或缩小编辑器字体的时候，出现如下的样子：
引用字体与代码字体重合了
代码版本：1.4.3_x64
windows10：企业版_x64
When you use Ctrl + mouse to scroll in the editor to enlarge or reduce the editor font, the following appears:
Reference font coincides with code font
Vscode Version: 1.4.3_x64
windows10: Enterprise Edition_x64

**Comment by mjbvz** [comment] 2020-03-27 00:41
Duplicate of #93367

**Closed by mjbvz** 2020-03-27 00:41 UTC
Labels: needs more info
