### ISSUE TITLE
previous result is in the sticky scroll section, rather than the relevant command

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#200994] opened 2023-12-15 17:20 UTC
the result of `git status` is stuck to the top of the terminal, rather than the latest command: `git pull origin main`

![image](https://github.com/microsoft/vscode/assets/2019016/c2ca83a6-9d8e-47fc-bd17-3993014974a9)

Seems to only occur for that specific instance of the command (first one in that terminal), I'm not sure what the bold bar on the left means:
![image](https://github.com/microsoft/vscode/assets/2019016/3570ce4e-c113-4950-bd5a-c7f5e1f92ed9)

**Comment by amunger** [comment] 2023-12-15 17:28
no repro with a new terminal

**Comment by Tyriar** [comment] 2024-12-18 10:35
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-18 10:35 UTC
