### ISSUE TITLE
Terminal reporting the wrong width causing weird visual artifacts 

### ISSUE THREAD

**Issue by jkells** [microsoft/vscode#121891] opened 2021-04-22 03:59 UTC
Issue Type: <b>Bug</b>

A dozen of us here are suffering weird terminal glitches that we've tracked down to the wrong terminal width being reported.

I'm not sure if this is a VSCode problem or not but it's only happening in the integrated terminal since the last update.

It presents as autocomplete going onto the wrong line or overwriting what we're typing.

We're all using a linux docker development container in VSCode on MacOSX.

After resizing the terminal pane the problem seems to go away for a while.

`tput cols` outputs `80 `when the terminal in this state. After resizing by a few pixels the output jumps up to the correct value `300+`

`echo $TERM` reports `xterm-256color`

`infocmp screen reports`
```
#       Reconstructed via infocmp from file: /lib/terminfo/s/screen
screen|VT 100/ANSI X3.64 virtual terminal,
        am, km, mir, msgr, xenl,
        colors#8, cols#80, it#8, lines#24, ncv@, pairs#64,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K,
        enacs=\E(B\E)0, flash=\Eg, home=\E[H, hpa=\E[%i%p1%dG,
        ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
        ind=\n, indn=\E[%p1%dS, is2=\E)0, kbs=^?, kcbt=\E[Z,
        kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,
        vpa=\E[%i%p1%dd,
```

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 4.19.121-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (1.05GB free)|
|Process Argv|--crash-reporter-id de4888b6-a9bb-4427-bb04-eb7b98b239da|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: EA Dev Environment|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (7 x 2300)|
|Memory (System)|15.64GB (7.74GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-containers|ms-|0.166.1
vscode-eslint|dba|2.1.20
sort-js-object|deb|0.1.2
java-decompiler|dgi|0.0.2
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
vscode-jest-runner|fir|0.4.34
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.1
bats|jet|0.1.7
vscode-styled-components|jpo|1.5.0
vscode-language-babel|mgm|0.0.31
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
vsliveshare|ms-|1.0.4131
java|red|0.77.0
vscode-coverage-gutters|rya|2.7.2
code-spell-checker|str|1.10.2
shellcheck|tim|0.14.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
vscode-wakatime|Wak|5.0.1
change-case|wma|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vscnewfilehidden:30288034
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by meganrogge** [comment] 2021-04-22 18:38
Does it help if you turn off `terminal.integrated.gpuAcceleration`?

**Comment by meganrogge** [comment] 2021-04-22 18:40
Duplicate of #120810

**Closed** 2021-04-22 18:40 UTC
Labels: *duplicate, bug, integrated-terminal
