### ISSUE TITLE
Emmet function disappeared.

### ISSUE THREAD

**Issue by nktsny2021** [microsoft/vscode#138655] opened 2021-12-08 15:21 UTC
必要なデータが送信するには大きすぎたため、クリップボードに書き込みました。貼り付けてください。
htmlやcssを補完入力できるツール消えました。
バージョン: 1.62.3 (Universal)
コミット: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
日付: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
解決策探しています。

**Comment by nktsny2021** [comment] 2021-12-08 15:34
The tool that can complete html and css has disappeared.
Version: 1.62.3 (Universal)
Commit: ccbaa2d
Date: 2021-11-17T07: 59: 13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
I'm looking for a solution.

**Comment by nktsny2021** [comment] 2021-12-09 22:01
Emmit has recovered.
I'm sorry for the disturbance.
I was able to call it from the command palette.

**Comment by rzhao271** [comment] 2021-12-27 16:33
Ah, Emmet in 1.62.3 is still using the old when clauses and so it will only activate when opening certain file types https://github.com/microsoft/vscode/blob/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/emmet/package.json#L44.
The issue is already fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/).

**Closed by rzhao271** 2021-12-27 16:33 UTC
Labels: needs more info, *english-please, translation-required-japanese

**Comment by rzhao271** [comment] 2021-12-27 16:35
Duplicate of https://github.com/microsoft/vscode/issues/137012
