### ISSUE TITLE
Pass uri to Notebook Serializer functions.

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#125872] opened 2021-06-09 18:35 UTC
While I was working on helping make https://github.com/TylerLeonhardt/shell-runner-notebooks a polyglot shell runner, I realized that it's not possible to deserialize the source of the notebook depending on the file name. 

In the extension there is one serializer to take `.ps1` files into a Notebook by changing the file to be `.Notebook.ps1`. The underlying file stays the same but the markdown and scripts are parsed out into NotebookData.

The same thing happens for `.sh` files. But these two don't share the same parsing into NotebookData.

Finally there's a third type of serializer for just Notebook files where the underlying source is standard notebook json.

While these seem like they should be 3 different serializers considering how different they are, the root problem is that you can't register a controller to multiple kinds of serializers, aka viewtypes. But I don't think we should allow controllers to register to many viewtypes, that seems weird.

Right now the extension uses 3 different controllers and 3 different serializers, which is weird for a user who'd expect only one consistent Notebook.

**Comment by jrieken** [comment] 2021-06-10 10:34
/duplicate of https://github.com/microsoft/vscode/issues/125757

**Closed** 2021-06-10 10:35 UTC
Labels: *duplicate, notebook
