### ISSUE TITLE
New feature for Emmet abbreviation with multiple children to show up at multiple cursor

### ISSUE THREAD

**Issue by sarthak7gupta** [Microsoft/vscode#30670] opened 2017-07-14 05:51 UTC
- VSCode Version: 1.14.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. In HTML, make 3 divs with emmet

 #mydiv-$*3 
which gives-
   < div id="mydiv-1">< /div>
   < div id="mydiv-2">< /div>
   < div id="mydiv-3">< /div>

2. Suppose I later decide to nest one div in each of the mydivs. I have some other code within those divs, so I don't want to use emmet again like

 #mydiv-$*3>#mysubdiv-$ 
which gives-
  < div id="mydiv-1">
    < div id="mysubdiv-1">< /div>
  < /div>
  < div id="mydiv-2">
    < div id="mysubdiv-2">< /div>
  < /div>
  < div id="mydiv-3">
    < div id="mysubdiv-3">< /div>
  < /div>

3. So, I add a multi-cursor between each div where I want to add the mysubdivs.
Now what I would like is if I write

#mysubdiv-$

in three places, emmet should understand that the '$' is being written in 3 different places, so give that 3 different numbers and give me

  < div id="mydiv-1">
    < div id="mysubdiv-1">< /div>
  < /div>
  < div id="mydiv-2">
    < div id="mysubdiv-2">< /div>
  < /div>
  < div id="mydiv-3">
    < div id="mysubdiv-3">< /div>
  < /div>

instead of

< div id="mydiv-1">
    < div id="mysubdiv-$">< /div>
  < /div>
  < div id="mydiv-2">
    < div id="mysubdiv-$">< /div>
  < /div>
  < div id="mydiv-3">
    < div id="mysubdiv-$">< /div>
  < /div>

**Comment by ramya-rao-a** [comment] 2017-07-19 00:59
We use the https://github.com/emmetio/expand-abbreviation module
We pass the abbreviation to expand along with some options
The module returns a single snippet with place holders

The logic of * for multiplication and $ for numbering takes place inside this module.
The editor then replaces current text with the snippet from the emmet module.

For your case we need the emmet module to return an array of snippets instead of a single snippet.

@sergeche thoughts?

**Comment by sergeche** [comment] 2017-07-19 08:04
In new Emmet, the `$` token is replaced only in repeated elements, e.g. if there’s `*` repeater. It’s intentional since in most cases old behaviour produced unexpected results like in `for-each[select="$a in $items"]`. So, in order to have expected behaviour “replace $ in repeated elements” element must be explicitly marked as repeated, e.g. `#mysubdiv-$*`

**Comment by ramya-rao-a** [comment] 2017-07-19 18:26
@sergeche Agreed

What we can do is 
- have a new command say `Emmet: Expand each child separately` (need a better name)
- valid only when multiple cursors are present
- this prompts for an abbreviation
- abbreviation needs to have a * for the first element. eg: `ul*3>li` is valid but `ul>li*3` is not. 
- The output from the emmet expand module is split based on new line
- Each of the split line is then entered into the multiple cursors.

**Comment by ramya-rao-a** [comment] 2017-07-25 03:15
Since this is not one of the emmet actions as described in https://docs.emmet.io/actions/, we won't be adding this into the product by default.

This most definitely is an extension candidate and if any one wants to create a new extension or add on to existing emmet extension as per https://github.com/Microsoft/vscode/issues/30670#issuecomment-316475151, I will be happy to work with them

**Closed** 2018-01-17 21:27 UTC
Labels: *extension-candidate, emmet, feature-request, help wanted
