### ISSUE TITLE
Support the built in product icons in activity bar

### ISSUE THREAD

**Issue by smezger** [microsoft/vscode#108742] opened 2020-10-15 13:40 UTC
It seems extension can not use the built in product icons for activity bar items.
```json
"viewsContainers": {
            "activitybar": [
                {
                    "id": "caplCompile",
                    "title": "CAPL Compile",
                    "icon": "$(alert)"
                }
            ]
        }
```
does not work.
It would be great if this can be supported in the future.

**Comment by IllusionMH** [comment] 2020-10-15 19:05
Looks like duplicate of #106348 or related to it
Original issue about blurry icon in the action bar.

**Closed** 2020-10-16 06:20 UTC
Labels: *duplicate
