### ISSUE TITLE
accessibility view does not work on linux 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#186437] opened 2023-06-27 20:29 UTC
Testing #186214

![image](https://github.com/microsoft/vscode/assets/3840081/91e4ea57-c30f-4362-8ba5-1e9daa08fe2f)

In the above image, it only reads: `(method) def has_id(` rest of the content is skipped.

**Comment by meganrogge** [comment] 2023-06-27 20:54
That is as designed - it will read only the line the cursor is on. Screen reader users will know how to navigate down.

**Comment by karthiknadig** [comment] 2023-06-27 20:59
@meganrogge this is in the hover, I did not see a way to move to the next line in the hover view.

**Comment by meganrogge** [comment] 2023-06-27 21:01
In your screenshot,the accessible view isn't open - maybe due to the key binding issue.

**Comment by karthiknadig** [comment] 2023-06-27 21:02
I could not trigger it at all even with clicking on the command from the palette

**Comment by meganrogge** [comment] 2023-06-27 21:05
Really strange as all of this works on macOS and probably windows

**Comment by meganrogge** [comment] 2023-06-27 21:23
@karthiknadig if you assign the command some keybinding which is not taken already, does it work? any errors in dev tools console?

**Comment by karthiknadig** [comment] 2023-06-27 21:30
It works!! i assigned `ctrl+shift+4` for this and it works as expected.

**Comment by meganrogge** [comment] 2023-06-27 21:32
awesome, thanks @karthiknadig so I'll close this and work on the keybinding issues you've created

**Closed by meganrogge** 2023-06-27 21:32 UTC
Labels: bug, info-needed, accessibility, linux

**Comment by rzhao271** [comment] 2023-07-27 17:57
Verified that it works with Ctrl+Shift+4 on Ubuntu. The OS is probably taking Alt+F2.
