### ISSUE TITLE
Can't go to definition from react component

### ISSUE THREAD

**Issue by lifez** [Microsoft/vscode#26149] opened 2017-05-07 07:36 UTC
- VSCode Version: 1.12.1
- OS Version: Osx 10.12.4

Steps to Reproduce:

1. Open some react component
2. CMD+Click to some react component in render function it not go to the import section

**Note**
The previous version is okay

**Comment by mjbvz** [comment] 2017-05-08 16:59
Can you set `	"typescript.tsserver.trace": "verbose"` and then open `Typescript` section of the output panel. Then reproduce the problem and share the output printed.

I suspect your issue may be caused by https://github.com/Microsoft/TypeScript/issues/15452 but want to verify this

**Comment by lifez** [comment] 2017-05-09 02:17
@mjbvz  is it right ?
![screen shot 2560-05-09 at 9 17 03 am](https://cloud.githubusercontent.com/assets/2588927/25832968/50458f5c-3498-11e7-9277-bbff5047e80c.png)

**Comment by mjbvz** [comment] 2017-05-17 01:40
Thanks @lifez. Yes, that is the correct log

Are those logs the first entries in the output panel or is there more text above or below? I suspect that the ts server has actually crashed here and is not restarting properly: https://github.com/Microsoft/vscode/issues/25807 This should be fixed in the current insiders builds if you give those a try

**Comment by lifez** [comment] 2017-05-17 03:35
@mjbvz  How can I use insiders builds?

**Comment by mjbvz** [comment] 2017-05-17 17:33
You can download them from here: https://code.visualstudio.com/insiders

**Comment by mjbvz** [comment] 2017-05-23 18:17
Closing as likely caused by Microsoft/TypeScript#15452

**Closed by mjbvz** 2017-05-23 18:17 UTC
Labels: javascript, needs more info
