### ISSUE TITLE
Expose editor tokens & scopes to extensionHost tests

### ISSUE THREAD

**Issue by cecilemuller** [microsoft/vscode#100484] opened 2020-06-18 11:07 UTC
I was trying to read the tokens/styles of the current document to get the same values as the `Developer: Inspect Editor Tokens and Scopes` command (to build a JSON structure I can compare to an expected result).

The `Developer: Inspect Editor Tokens and Scopes` command is a `IContentWidget`, so its constructor receives a reference to the services, but I don't see a way to access these services from the API provided by `import * as vscode from 'vscode';` used by tests suites running using an "extensionHost" task.

**Comment by usernamehw** [comment] 2020-06-18 11:56
Possible duplicate of #580

**Closed** 2020-06-26 14:05 UTC
