### ISSUE TITLE
Feature: Add support to use editor on multiple monitors

### ISSUE THREAD

**Issue by sl1msh4dy** [Microsoft/vscode#41834] opened 2018-01-19 00:11 UTC
Hi

I thought it would be a great feature to be able to use multiple screens with the editor.
Just like the split works but then on a different monitor.

Kind regards
Sl1m

**Comment by yume-chan** [comment] 2018-01-19 02:05
Do you mean open multiple windows for the same workspace? If so, it's a duplicate of #10121.

**Closed** 2018-01-19 05:45 UTC
Labels: *duplicate
