### ISSUE TITLE
Mouse cursor disappears in code editor window

### ISSUE THREAD

**Issue by marcnesello** [microsoft/vscode#205512] opened 2024-02-19 08:00 UTC
Type: <b>Bug</b>

Use a light theme. Click on the terminal windows and move the mouse cursor into the code editor window. The cursor disappears and will appear after a few seconds. If you enable a dark theme this does not happen.
This behaviour started with version 1.86 and can be rolled back by installing an older version than 1.86.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.14.21-150400.24.103-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: |
|OS|Linux x64 5.14.21-150400.24.103-default|
|CPUs|Intel(R) Xeon(R) CPU E7-8880 v4 @ 2.20GHz (40 x 2194)|
|Memory (System)|157.35GB (132.15GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.338.1
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.5.0
ccls|ccl|0.1.29
vscode-gardener-tools|gar|0.13.0
go|gol|0.41.0
rest-client|hum|0.25.1
vscode-docker|ms-|1.29.0
vscode-dotnet-runtime|ms-|2.0.1
vscode-kubernetes-tools|ms-|1.3.15
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.13
sqltools|mtx|0.28.1
vscode-yaml|red|1.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30

(2 theme extensions excluded)

</details>

**Comment by deepak1556** [comment] 2024-02-19 09:23
Can you run our bisect tool `npx @vscode/vscode-bisect` to help narrow down the commit that introduced the regression.

**Comment by aeschli** [comment] 2024-02-19 14:28
Can you add a screen capture?

**Comment by MikuAuahDark** [comment] 2024-02-23 13:37
This is likely a duplicate of #204103 and #204181. Screen capture is available in the latter bug report.

**Comment by aeschli** [comment] 2024-02-26 14:31
Thanks.
Marking as duplicate of https://github.com/microsoft/vscode/issues/204181

**Closed by aeschli** 2024-02-26 14:31 UTC
Labels: info-needed
