### ISSUE TITLE
Exploration into adoption of EditContext API in VS Code

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#222010] opened 2024-07-18 02:28 UTC
# Exploration into the adoption of the EditContext API

The [EditContext API](https://developer.mozilla.org/en-US/docs/Web/API/EditContext_API) is a new API that decouples the rendering of the edit state of an HTML dom element from the dom element. The EditContext has the following interface (click to expand):

<details>
<summary>EditContext API Interface</summary>

```
dictionary EditContextInit {
    DOMString text;
    unsigned long selectionStart;
    unsigned long selectionEnd;
};

interface EditContext : EventTarget {
    constructor(optional EditContextInit options = {});

    undefined updateText(unsigned long rangeStart, unsigned long rangeEnd, DOMString text);
    undefined updateSelection(unsigned long start, unsigned long end);
    undefined updateControlBound(DOMRect controlBound);
    undefined updateSelectionBound(DOMRect selectionBound);
    undefined updateCharacterBounds(unsigned long rangeStart, sequence)<DOMRect> characterBounds);

    sequence<Element> attachedElements();

    readonly attribute DOMString text;
    readonly attribute unsigned long selectionStart;
    readonly attribute unsigned long selectionEnd;
    readonly attribute unsigned long compositionRangeStart;
    readonly attribute unsigned long compositionRangeEnd;
    readonly attribute boolean isInComposition;
    readonly attribute DOMRect controlBound;
    readonly attribute DOMRect selectionBound;
    readonly attribute unsigned long characterBoundsRangeStart;
    sequence<DOMRect> characterBounds();

    attribute EventHandler ontextupdate;
    attribute EventHandler ontextformatupdate;
    attribute EventHandler oncharacterboundsupdate;
    attribute EventHandler oncompositionstart;
    attribute EventHandler oncompositionend;
};

```
</details>

The adoption of the EditContext API has the following benefits:
- It is likely to solve some of the IME issues we are currently seeing today
- It would allow more fine grained control of the rendering of the editor text and therefore the screen reader experience

Some exploration has already been done previously on the branch https://github.com/microsoft/vscode/pull/207699. This iteration we have continued working on this exploration. More specifically we have focused on the following three sub-problems that arose in the first exploration:

## Enabling Screen Reader Users with the EditContext

Currently to read accessible text, there exists a hidden text area positioned behind the visible text containing the current active line's text. This text is focused and read by a screen reader when a user navigates in the editor. An attempt has been made to use the EditContext API alongside this textarea but it was soon discovered that the EditContext does not support textarea elements. We are therefore currently exploring using other HTML elements to generate this hidden element and keep screen reader support. Here are some ideas that have been considered:

**1. Use an HTML element like \<div\> containing the text to be read**

In order to enable IME support the text in the hidden area contains the active line's text as well as the text of a couple of lines before it and after it. When a user navigates up and down the editor, the text is updated to match the current edit state. In this case, if you use a \<div\> element which directly contains the text then the screen reader reads the updated text on every single `ArrowUp` and `ArrowDown` commands. We want to avoid that, so a few ideas have been considered:
- Instead of adding the text for several consecutive lines, add the text of the current active line only. In this case we would not have any problem with the update because the screen reader would read the full text which is just the current line text. This solution is not ideal, because it would make IME completions less accurate.
- Tweak the aria attributes of the outer div so that on focus it always reads out the predetermined text of the current active line. An issue that is likely to arise however is that the outer div would be focused not the specific line that would be read out, creating an inconsistency between the screen reader focus box and the text that is read aloud.
- Place each line into a separate HTML element, in the hopes that with some additional work, the screen reader would read only the current line's text on update. This approach is explored in the next section.

The `aria-role` that has been chosen for the div is `textbox`. This aria-role mirrors the aria-role of the current textarea. It's attribute [`aria-multiline`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-multiline) has been set to `true`. Setting the `aria-role` to `textbox` and `aria-multiline = true` does not seem to change how text in the div is read on update - the full text is still read on update. Other aria-roles could still be explored, perhaps there is a more suitable one.

There were some focus problems in the initial implementation. When you would navigate with the `Up` and `Down` arrows, the caret would move down, the hidden element inner content would be updated and focus would be lost and set to the whole VS Code window. It is unclear as of yet why this happens, but it has been noticed that setting `contenteditable = true` on the div element fixes the issue.

**2. Use a \<div\> element containing only the active text.**

Initially I tried changing the textContent of the div directly and set it to the current active line's text. When you would navigate from line to line however, the screen reader would read out only the diff from one line to the next. So if two consecutive lines share the same initial text, the screen reader would not read the full second line when entering on it. To mitigate this, the active line text was added into a div which was nested inside the parent div. In this manner the screen reader read the whole line when navigating upon it. 

After this change, several other issues remained. The first is that when using the Left and Right arrow keys, the screen reader would read out the full updated line anew. To mitigate this, the code was changed so that the inner div was updated only when the line of the cursor selection would change. The second problem is that the Left and Right arrows would not automatically shift the focused black border of the screen reader. At some point focus is lost from the hidden area and set to the full window. Initially I thought would need to set `contentEditable` to true both on the parent div and the child div, but actually it was sufficient to set `role:textbox` on the parent div and the inner div.

**3. Use a \<div\> element with \<div\> or \<p\> children containing the individual lines to be read**

To address the issue of the full text being read on div update, some exploration has been done into using separate HTML elements for every single line. More specifically the following ideas have been considered:
- Place each line into a separate HTML element, make them focusable, and navigated in this manner between the different tabable lines. This solution is not ideal, as we would ideally only want the outer div to focusable.
- Place each line into a separate HTML element and use the `aria-activedescendant` attribute on the parent element to specify which of its children is currently active.

The second idea has been explored. The MDN website says this about the `aria-activedescendant` attribute:

> The aria-activedescendant property provides a method of managing focus for assistive technologies on interactive elements when they contain multiple focusable descendants, such as menus, grids, and toolbars. Instead of the screen reader moving focus between owned elements, aria-activedescendant can be used on container elements to refer to the currently active element, informing assistive technology users of the currently active element when focused. 

The website mentions `aria-activedescendant` attribute should be set alongside the `aria-controls` attribute. Initial work successfully allows the user to navigate in the hidden text area like in the current implementation. In particular the black focus box of voiceover surrounds the current active line on ArrowUp and ArrowDown and surrounds the individual characters on ArrowLeft and ArrowRight. 

The focus problem however remains. When the mouse move Left and Right, it gets stuck as focus is moved out. When the mouse moves over an empty span, the full div is focused, not the child containing nothing. Two solutions have been found:
1. Give the parent and the children nodes the role `textbox` 
2. Give the parent and the children the attribute `contenteditable=true`

Paragraph child elements have been tested. This does not seem to affect the screen reader text.

Setting `aria-multiline=true` seems to read the insertion position. 

### TODO:

- Screen reader reads the selection position which it does not on current implementation. Screen reader also reads consistently `edit text` when moving to a new line.
  - Maybe if not made contenteditable, then this would no longer be read. 

## Enabling usage of `Enter` to add new line

As is mentioned in the following issue https://github.com/w3c/edit-context/issues/94 when the `Enter` key is pressed, the `textupdate` event is not fired. More specifically on this link https://w3c.github.io/edit-context/#handle-input-for-editcontext, the following is written:

> The [inputType](https://www.w3.org/TR/uievents/#dom-inputevent-inputtype)s handled by [EditContext](https://w3c.github.io/edit-context/#dom-editcontext) are those which operate only on raw text. Other [inputType](https://www.w3.org/TR/uievents/#dom-inputevent-inputtype)s that depend on formats, clipboard/dragdrop, undo, or browser UI like spellcheck cannot be handled by [EditContext](https://w3c.github.io/edit-context/#dom-editcontext) since [EditContext](https://w3c.github.io/edit-context/#dom-editcontext)'s state does not include these concepts. If an author wants their application to handle those [inputType](https://www.w3.org/TR/uievents/#dom-inputevent-inputtype)s, they need to process them manually in a [beforeinput](https://www.w3.org/TR/uievents/#event-type-beforeinput) event handler.

As such, to implement the usage of `Enter`, we need to listen to the `beforeinput` event as follows (taken from exploration branch):

```
this._domElement.domNode.addEventListener('beforeinput', e => {
	if (e.inputType === 'insertParagraph' || e.inputType === 'insertLineBreak') {
		this._handleTextUpdate(this._editContextState.positionOffset, this._editContextState.positionOffset, '\n')
	}
});
```

## Enabling copy/paste to add new line

Similarly as for the `Enter` case, copy/pasting functionality needs to be implemented outside of the edit context. This was done by listening on the copy event of the hidden element and the keydown event to detect the paste event.

cc @hediet

**Comment by hediet** [comment] 2024-07-18 08:13
> This solution is not ideal, because it would make IME completions less accurate.

That is not a problem! IME completions only work on the edit context, not the DOM.

**Comment by aiday-mar** [comment] 2024-07-18 11:56
I'll respond in slack

**Comment by aiday-mar** [comment] 2024-07-29 09:07
This comment will be about the more in depth exploration following the initial exploration.

The initial implementation was to have a div with textContent the content of the line under the cursor (the edit context contained more lines above and below the line under the cursor that were used as context for the completions). The issue with this implementation is that as you would navigate from line _n_ to line _n+1_, the screen reader would only read the difference between the contents on those lines. For the following code:

```
this._register(this._editor.onDidChangeSelection());
this._register(this._editor.onDidChangeModel());
```

As the cursor moves down from the top line to the bottom line, the screen reader reads only `Model())` because that is the difference between the two lines. To avoid this issue, it was decided to place the content inside of a div nested inside of the outer root div. In this manner, if we update the whole child div with the new text content, the screen reader reads the full line, not just the difference.

Initially there were some cursor navigation issues. If the cursor was moved down to another line with the ArrowDown arrow, focus would be lost and the next time ArrowDown would be used, the cursor could no longer be moved down. This happens only when the screen reader is used - navigation is correct and as expected without the screen reader. It has been noticed that setting the role to `textbox` keeps the focus on the hidden area. Similarly it has been noticed that

**Comment by hediet** [comment] 2024-09-04 17:53
Duplicate of #207700

**Closed by hediet** 2024-09-04 17:53 UTC
Labels: editor-input, editor-input-IME, exploration
