### ISSUE TITLE
Can vscode's settings.json be cross-platform?

### ISSUE THREAD

**Issue by vision1v1** [microsoft/vscode#199496] opened 2023-11-29 07:59 UTC
I want to distinguish my different configurations under linux and windows. My program needs to load different python interpreters and environments, under linux and window. How do I do this?

**Comment by vision1v1** [comment] 2023-11-29 11:31
I have a solution, it's not very good but it works, use code-workspace.

**Comment by rzhao271** [comment] 2023-11-29 16:14
I'll consider this a duplicate of https://github.com/microsoft/vscode/issues/5595

**Closed by rzhao271** 2023-11-29 16:14 UTC
