### ISSUE TITLE
Nodebook cells rendered without code

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#126090] opened 2021-06-11 19:16 UTC
Issue Type: <b>Bug</b>

I have collapsed some cells in my notebook today and noticed that other cells went blank. They still take the full space of the query and I can make them render by hitting the molecule(?)-icon.

![empty-cells-rendered](https://user-images.githubusercontent.com/8599/121738355-f9437500-caae-11eb-9ec4-7d9e59c52df6.gif)

VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:12:17.675Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (10.54GB free)|
|Process Argv|--locale=de --enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|1.94GB (0.09GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
tsl-problem-matcher|eam|0.4.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
codespaces|Git|0.10.5
remotehub-insiders|Git|2021.6.1108
fluent-icons|mig|0.0.12
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-es|MS-|1.57.1
vscode-edge-devtools|ms-|1.1.9
remote-containers|ms-|0.183.0
debugger-for-edge|msj|1.0.15
msft-todo-unofficial|tyl|0.0.11
gitlens-insiders|eam|2021.5.2405
vscode-language-pack-es|MS-|1.57.1
python|ms-|2021.7.922878407-dev
vscode-pylance|ms-|2021.6.2-pre.1
jupyter|ms-|2021.7.928000153
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30319630
vscgsv2:30305091
vscorehov:30301224
00j7a122:30294756
vscod805:30301674
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by digitarald** [comment] 2021-06-11 19:28
One observation is that collapsing cells causes cells above the collapsed one to get into this invisible state.

**Comment by rebornix** [comment] 2021-06-11 21:30
can be a duplicate of https://github.com/microsoft/vscode/issues/126056

**Comment by mjbvz** [comment] 2021-06-11 22:57
@digitarald  Please test out the next insiders build and let me know if you still see this

**Closed by mjbvz** 2021-06-11 22:57 UTC
Labels: *duplicate
