### ISSUE TITLE
launch.json resetting its content to default after debugging session

### ISSUE THREAD

**Issue by Utamaru** [Microsoft/vscode#368] opened 2015-11-20 18:06 UTC
I tried changing default Unity profile in "configurations", adding custom profile, but every time I stop debugging launch.json resets to its default state.

OS: MacOS Yosemite 10.10.5.
VS Code version: 0.10.1 (issue was there before).

**Comment by Utamaru** [comment] 2015-11-20 18:21
[StackOverlow issue threah](http://stackoverflow.com/questions/33832902/vs-codes-launch-json-keeps-reseting-after-debugging)

**Comment by isidorn** [comment] 2015-11-23 08:52
VSCode should not reset your configuration file.
Can you attach your launch.json before start of debug, and after the debug session has stopped so we compare? Do you have auto save on or off?

**Comment by weinand** [comment] 2015-11-23 09:16
@isidorn Most likely the VS Code plugin for Unity recreates the launch.json. See 
https://code.visualstudio.com/Docs/runtimes/unity item 5: *Configures a launch.json file with the correct debug port - to enable debugging*
This plugin needs to update in order to include the "request": "attach".

**Comment by isidorn** [comment] 2015-11-23 09:39
Thanks Andre, closing this issue since it is not on the VSCode side.
Please file this bug against the unity plugin.

**Closed by isidorn** 2015-11-23 09:39 UTC
Labels: Needs More Info

**Comment by ancashoria** [comment] 2017-06-29 07:01
I have the same issue. Somehow my `launch.json` is reset. I don't have the Unity plugin. How should I trace the source of the problem?

**Comment by weinand** [comment] 2017-06-29 07:43
@ancashoria what do you mean by "reset"? Please post the contents here.

**Comment by ancashoria** [comment] 2017-06-29 08:00
@weinand I'm sorry I can't reproduce it right now because I restored `launch.json` from a backup.
By reset I mean it looked as if VS Code had just created the file. If you attempt to run a debugging session without a `launch.json`, I think it will generate a basic `launch.json` and that's what it looked like.

I will post here the details when it happens again (encountered this twice in the last days)

**Comment by weinand** [comment] 2017-06-29 08:37
Yes, if the launch.json is missing, VS Code will create it if needed. But I've never saw an issue that an existing file got overwritten (but in theory any extension could do this).

@isidorn are you aware of any overwrites of launch.json?

**Comment by isidorn** [comment] 2017-06-29 08:59
@weinand we do not overwirte launch.json if it exists
@ancashoria please create a new issue with reproducable steps and we can investigate
