### ISSUE TITLE
Incorrect window dimensions/rendering after screen resolution change

### ISSUE THREAD

**Issue by johnendev** [microsoft/vscode#90650] opened 2020-02-14 05:00 UTC
Issue Type: <b>Bug</b>

When launched VS Code renders correctly on either display, but after a screen resolution change the dimensions appear to be off by 4px on all sides. VS Code is maximized.

- Scenario 1: Launch with single screen, 3000x2000 200% scaling, then switch to 1920x1080 100% scaling. This results in Image 1, the window renders slightly off-screen on all sides.
- Scenario 2: Launch with single screen, 1920x1080 100%, then switch to 3000x2000 200%. This results in Image 2, the window renders 4px in from all sides.
- Scenario 3: Launch with both displays attached and extended desktop. In this case it doesn't matter which screen VS Code initially on when launched and it renders correctly on the 3000x2000 screen, but on the 1920x1080 screen it always renders as in Image 1.

When not maximized rendering seems to be correct. Un-maximizing and maximizing the window doesn't fix it. Opening another window in the same VS Code instance has the same issue as the initial window.

This issue is new in VS Code since Electron 7 (#90412), but Electron Fiddle doesn't have this issue.

VS Code version: Code - Insiders 1.43.0-insider (1fbacccbc900bb59ba8a8f26a4128d48a1c97842, 2020-02-13T06:41:13.411Z)
OS version: Windows_NT x64 10.0.18363

**Image 1**
![to 96-dpi display](https://user-images.githubusercontent.com/20271944/74502346-19623300-4f52-11ea-8f7e-7697212fd07b.png)
**Image 2**
![to hign-dpi display](https://user-images.githubusercontent.com/20271944/74502385-3565d480-4f52-11ea-85a3-ac406a5261ef.png)

**Comment by ZhenlyChen** [comment] 2020-07-20 10:57
I have a similar problem.
Display1: 3840*2160 (250% scaling)
Display2: 2560*1440 (125% scaling)
VS Code displays correctly on the Display1, but incorrectly on the Display2.(As shown in Image1 above).

VS Code version: 1.47.2  (2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by manospasj** [comment] 2020-07-31 10:42
Duplicate of https://github.com/microsoft/vscode/issues/85592

**Closed** 2020-11-04 22:08 UTC
Labels: *duplicate
