### ISSUE TITLE
Quick Open opens some files in preview when "workbench.editor.enablePreviewFromQuickOpen": false.

### ISSUE THREAD

**Issue by Scott-Tenera** [microsoft/vscode#129695] opened 2021-07-28 14:54 UTC
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-63-generic

I have   "workbench.editor.enablePreviewFromQuickOpen": false set in my settings.

I am  opening my files using Quick Open (ctrl+p). Some files are opening in preview mode (they have italic text, and are replaced with other files). Some files are not opening in preview mode using Quick Open. I can not discern what the difference is between the files opened in preview and the files not opened in preview. Regardless, I would assume that having enablePreviewFromQuickOpen: false, no files should be opening in preview.

**Comment by TylerLeonhardt** [comment] 2021-07-28 15:39
duplicate of #128755 and already fixed in insiders.

**Closed by TylerLeonhardt** 2021-07-28 15:39 UTC
