### ISSUE TITLE
files.exclude not respected with CMD+P

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10946] opened 2016-08-25 11:59 UTC
- VSCode Version: Code - Insiders 1.5.0-insider (2f2d6502638fa108f8ddbcc5831b38a35d5a1c11, 2016-08-25T06:04:22.901Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Added `"common/typings/**": true,` to `files.exclude` & `files.watcherExclude` & `search.exclude` of Workspace Settings and restarted vscode
2. When doing `CMD+P` then files from these folders still show up - I think it should respect the setting (folder is hidden in Explorer and non searchable - just shows up in CMD+P)

![image](https://cloud.githubusercontent.com/assets/1723815/17968204/82a34436-6a99-11e6-9da8-fee90e59ac71.png)

**Comment by bpasero** [comment] 2016-08-26 10:20
@wallverb can you attach a larger screenshot that shows the full box and where the results are coming from? this smells like a duplicate of https://github.com/Microsoft/vscode/issues/6502

**Comment by wallverb** [comment] 2016-08-26 12:07
@bpasero Here is attached larger screenshot. I did `CMD+K CMD+W` which closed all the tabs, restarted vscode, but it still shows up (a little bit weird that it shows Recently Opened on the right side - not sure if there is some cache that survives restarts and if I can clear it somehow)

![image](https://cloud.githubusercontent.com/assets/1723815/18004700/8b6becce-6b63-11e6-8168-4358905de276.png)

If I scroll down a little bit to section 'file and symbol results` it is not there 

![image](https://cloud.githubusercontent.com/assets/1723815/18004781/03ae00a0-6b64-11e6-9707-4a9c6fc43252.png)

**Comment by bpasero** [comment] 2016-08-26 12:37
Thanks, this is https://github.com/Microsoft/vscode/issues/6502 where we fail to apply the exclude patterns on the editor history.

**Closed** 2016-08-27 08:33 UTC
Labels: needs more info
