### ISSUE TITLE
Feature Request: A native solution to sync user settings

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#88572] opened 2020-01-13 17:57 UTC
Rather than using an extension, I'd like a way to be able to login to vscode so that I can sync my user settings, extensions, code snippets, etc from machine to machine. Kind of like logging into Google Chrome

**Comment by IllusionMH** [comment] 2020-01-13 17:59
/duplicate of #2743 and it's already in the works.

In the meantime you can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Closed** 2020-01-13 17:59 UTC
Labels: *duplicate
