### ISSUE TITLE
Empty line and overlapping in suggest box

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3303] opened 2016-02-23 11:12 UTC
1. Trigger intelli-sense inside an empty `tasks.json`
2. Press up key to get to the bottom element, notice an empty suggest element at the top of `promptOnClose` 
3. Sometimes two elements overlap when you go up / down

![screen shot 2016-02-23 at 12 08 41](https://cloud.githubusercontent.com/assets/1926584/13249733/3c336f0c-da26-11e5-8e3e-a02f10e90527.png)

![screen shot 2016-02-23 at 12 11 04](https://cloud.githubusercontent.com/assets/1926584/13249781/8e529880-da26-11e5-8f04-a4b3fdb994c2.png)

**Comment by joaomoreno** [comment] 2016-02-23 11:16
Duplicate of #3022

**Closed by joaomoreno** 2016-02-23 11:16 UTC
Labels: bug, important
