### ISSUE TITLE
copy code paste in evernote ,  doesn't keep indent.

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#38182] opened 2017-11-13 05:36 UTC
- VSCode Version: latest
- OS Version: win7

pycharm work fine with evernote , but vscode lost indent.

**Comment by maxibanki** [comment] 2017-11-13 20:19
Duplicate of #35954

**Comment by rebornix** [comment] 2017-11-13 21:41
@maxibanki thanks! It's a dup.

**Closed by rebornix** 2017-11-13 21:41 UTC
Labels: editor, editor-clipboard
