### ISSUE TITLE
microsoft or vscode account to save all settings and extensions

### ISSUE THREAD

**Issue by jakepintu** [Microsoft/vscode#60626] opened 2018-10-11 11:17 UTC
Feature Request: Would love to be able to create VS Code account to save all settings and extensions to. That way, we could just sign in on any machine where it is installed and all settings would be adjusted and extensions installed.

**Comment by egamma** [comment] 2018-10-11 11:58
Duplicate of (#59780)

**Closed by egamma** 2018-10-11 11:58 UTC
Labels: extensions
