### ISSUE TITLE
Autocompleting `class` after `abstract` inserts comments

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#21738] opened 2017-03-02 09:44 UTC
- VSCode Version: `1.10.1`
- OS Version: `Windows 10`
- `"typescript": "^2.2.1"`

Steps to Reproduce:

1. `abstract c...[auto-complete]`

![image](https://cloud.githubusercontent.com/assets/5593825/23501653/fcb066ac-ff34-11e6-8c5f-30f417256523.png)
![image](https://cloud.githubusercontent.com/assets/5593825/23501671/15713d1a-ff35-11e6-975e-cfbd9519cebd.png)

**Comment by mjbvz** [comment] 2017-03-02 22:12
Thanks @CoenraadS 

Just to add context on the root cause of this issue, I don't believe this was introduced with the new jsdoc support in 1.10. It looks like the class definition snippet is wrong in this case.

For anyone running into this, if  this issue is annoying you, as a workaround disable snippets altogether with: `"editor.snippetSuggestions": "none"`

**Comment by elias-winberg** [comment] 2017-03-25 14:24
I think that we either have to remove the comment here https://github.com/Microsoft/vscode/blob/master/extensions/typescript/snippets/typescript.json#L18 or add a snippet for `abstract class`.

**Comment by mjbvz** [comment] 2017-04-04 00:01
Fixed by @elias-winberg with #23209

**Closed by mjbvz** 2017-04-04 00:01 UTC
Labels: bug, javascript, snippets, typescript
