### ISSUE TITLE
Maximized VSCode window border shown on second screen in 1.47.3

### ISSUE THREAD

**Issue by xwang233** [microsoft/vscode#103737] opened 2020-08-01 00:43 UTC
- VSCode Version: June 2020, 1.47.3
- OS Version: Windows 10

Steps to Reproduce:

1. Prepare dual monitors with Extend mode horizontally, same screen resolution.
2. Maximize VSCode on left screen
3. On the right screen, at the left most pixel column, I can see the "right border" of the VSCode window.

This issue doesn't exist for other windows apps, such as chrome, powershell, etc. I've also checked many windows settings, NVIDIA driver settings. Nothing changed. 

**This issue doesn't exist for VSCode May 2020, 1.46.1. I downgraded my VSCode and confirmed this.**

Does this issue occur when all extensions are disabled?: Yes

<details><summary>system</summary>

CPUs | Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 31.97GB (13.92GB free)
Process Argv |  
Screen Reader | no
VM | 0%

</details>

**Comment by deepak1556** [comment] 2020-08-03 21:59
This is duplicate of https://github.com/microsoft/vscode/issues/85310 , merging.

**Closed by deepak1556** 2020-08-03 21:59 UTC
