### ISSUE TITLE
vscode.typescript extension quotes import statements the wrong way

### ISSUE THREAD

**Issue by binarykitchen** [microsoft/vscode#146882] opened 2022-04-06 06:51 UTC
Does this issue occur when all extensions are disabled?: Yes/No

No.

It is indeed a problem with the vscode.typescript extension. Disable it and it doesn't happen.

- VS Code Version: 1.66.0
- OS Version: MacOS Monterey 12.3.1 (21E258)

Steps to Reproduce:

1. In a *.tsx file, write an import statement like `import React from "react";` (<-- it has double quotes)
2. Save that
3. Some weird, unknown auto formatting happens from the `vscode.typescript` extension (I've disabled everything else like prettier or eslint)
4. It changes that import statement to `import React from 'react';` huh?

I've spent almost two hours on this. Initially I thought it was a mess with prettier or eslint config but heck, it was that native, built-in extension wow. One of my work colleagues just had the same problem as well. We do not share the VS Code settings. Wondering how many others have the same problem out there?

Hope, this helps and you awesome guys can narrow down the issue. 

Happy to provide more information

**Comment by infinnie** [comment] 2022-04-06 09:17
Do you have anything like tsconfig.json?

Ref: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by binarykitchen** [comment] 2022-04-06 09:28
Good question. Here is our TS config. We have one extending from the other one. All is in this Gist:
https://gist.github.com/binarykitchen/87cb238d6288d202b6e3e760a6798f60

Already have set that setting to "auto":
<img width="672" alt="Screen Shot 2022-04-06 at 21 27 55" src="https://user-images.githubusercontent.com/177641/161943858-9dbd92d0-9c76-4739-ac18-a11187914739.png">

**Comment by gjsjohnmurray** [comment] 2022-04-06 09:44
@binarykitchen Notice the suffix stating that the setting is modified in Workspace. What do you see when you switch to the Workspace tab of the Settings Editor?

**Comment by binarykitchen** [comment] 2022-04-06 09:52
@gjsjohnmurray same, auto, see screenshot:
<img width="876" alt="Screen Shot 2022-04-06 at 21 52 20" src="https://user-images.githubusercontent.com/177641/161948870-5575cd79-1fa9-4872-81f9-084ca1905f0d.png">

**Comment by gjsjohnmurray** [comment] 2022-04-06 10:07
Is there anything else in your .tsx file which would cause `auto` to infer that `single` should be used?

**Comment by binarykitchen** [comment] 2022-04-06 10:21
@gjsjohnmurray Let me give you a lot more information. Here's the full file content before and after:
https://gist.github.com/binarykitchen/87cb238d6288d202b6e3e760a6798f60?permalink_comment_id=4123223#gistcomment-4123223

**Comment by gjsjohnmurray** [comment] 2022-04-06 10:37
@binarykitchen I think @mjbvz (assigned) will find your extra information useful.

**Comment by binarykitchen** [comment] 2022-04-06 11:09
Ok, sweet as.

For now, until this is sorted, we will have to run a manual `prettier` command to fix this before merging.

**Comment by mjbvz** [comment] 2022-04-06 17:08
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by binarykitchen** [comment] 2022-04-06 20:59
Nope, with the latest VS Code insiders build I cannot reproduce this anymore. Either with all extensions disabled or enabled, both, it doesn't reproduce any longer.

Did you make any changes, fixes?

**Comment by mjbvz** [comment] 2022-04-06 21:25
Thanks for testing. No changes come to mind. I suspect it's like either an extension or a setting that was causing this but closing this since it's not reproducible

**Closed by mjbvz** 2022-04-06 21:25 UTC
Labels: needs more info
