### ISSUE TITLE
C support in markdown

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#46495] opened 2018-03-25 14:26 UTC
- VSCode Version: 1.21.1
- OS Version: macOS

```c
struct proc_struct {
    enum proc_state state;                      // Process state
    int pid;                                    // Process ID
    int runs;                                   // the running times of Proces
    uintptr_t kstack;                           // Process kernel stack
    volatile bool need_resched;                 // bool value: need to be rescheduled to release CPU?
    struct proc_struct *parent;                 // the parent process
    struct mm_struct *mm;                       // Process's memory management field
    struct context context;                     // Switch here to run process
    struct trapframe *tf;                       // Trap frame for current interrupt
    uintptr_t cr3;                              // CR3 register: the base addr of Page Directroy Table(PDT)
    uint32_t flags;                             // Process flag
    char name[PROC_NAME_LEN + 1];               // Process name
    list_entry_t list_link;                     // Process link list
    list_entry_t hash_link;                     // Process hash list
};
```

```c
int
do_fork(uint32_t clone_flags, uintptr_t stack, struct trapframe *tf) {
    int ret = -E_NO_FREE_PROC;
    struct proc_struct *proc;
    if (nr_process >= MAX_PROCESS) {
        goto fork_out;
    }
    ret = -E_NO_MEM;
}
```

Just try these code snippets above and you will see the problem. I'm using default Markdown engine from VS Code. The problem is, it doesn't match the real coloring from the VS Code and somehow it's not the same as it's by default. Markdown seems to have bad color scopes.

Markdown
![image](https://user-images.githubusercontent.com/10441177/37876168-68f632bc-3051-11e8-8e7a-b74d33096ec7.png)

C
![image](https://user-images.githubusercontent.com/10441177/37876172-73f14242-3051-11e8-84f2-167e5b6bc6cb.png)

**Comment by mjbvz** [comment] 2018-03-26 19:34
Duplicate of #34525. See the discussion and links on https://github.com/atom/language-c/issues/250 for why this is difficult to fix

**Closed by mjbvz** 2018-03-26 19:34 UTC
Labels: markdown
