### ISSUE TITLE
The code runner plug-in runs C + + files in vscode version 1.60 cannot change the terminal from powershell to others

### ISSUE THREAD

**Issue by HQXSTICK** [microsoft/vscode#132335] opened 2021-09-04 13:20 UTC
- VS Code Version:1.60.0 and 1.61.0 insider
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. 在settings.json 改变了默认终端为cmd (command prompt)
![image](https://user-images.githubusercontent.com/64624915/132095761-844ed9b6-9e74-442d-b75e-272f7a65f134.png)
2.但重启系统后打开任意一个c++文件后使用code runner运行都还是在power shell 中

**Comment by gjsjohnmurray** [comment] 2021-09-05 03:47
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-05 03:48 UTC
Labels: needs more info, *duplicate, *english-please, translation-required-chinese-simplified
