### ISSUE TITLE
CompletionItem.preselect seems to be ignore with MRu selection

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#54203] opened 2018-07-12 20:39 UTC
Steps to reproduce (pthyon code)

- type `os.`
- correctly preselects `path`
- pick `pipe`
- delelete `pipe`
- open code complete

Observe: `pipe`is selected although `path` is preselected.

**Comment by dbaeumer** [comment] 2018-07-12 20:39
FYI @vivlimmsft

**Comment by jrieken** [comment] 2018-07-13 07:12
That's most likely because of `"editor.suggestSelection": "recentlyUsed"`. Try `first` (which now actually means default).

**Comment by vivlimmsft** [comment] 2018-07-13 09:39
I didn't have `editor.suggestSelection` set at all, it seems to default to `recentlyUsed`.

It works fine with `first` (and in fact that's a workaround I'm using for development) but I was expecting `preselect`, when set, to take effect regardless of the value of `editor.suggestSelection`. I was hoping that `preselect` would mean that I wouldn't need to write `"editor.suggestSelection": "first"` into user settings for my feature to work.

**Comment by jrieken** [comment] 2018-07-13 10:45
Yeah, `recentlyUsed` is the default and it's a fair question about what should win `preselect` or `recentlyUsed`. I think that `recentlyUsed` should win because it's a recording of actual user-choice. However, given that we now have the preselect-feature we can think about changing the default to `first`... Tho, care must be taken because those changes often cause a big stir. 

As a language extension author you can always contribute a default value for an existing setting, e.g you can say `for python the value is `"editor.suggestSelection": "first"`

**Comment by jrieken** [comment] 2018-09-11 08:54
Closing this as designed

**Closed by jrieken** 2018-09-11 08:54 UTC
Labels: as-designed, suggest, under-discussion
