### ISSUE TITLE
HTMLHint extension not working in VSCode 1.48 and above

### ISSUE THREAD

**Issue by Vetroplovc** [microsoft/vscode#107225] opened 2020-09-22 11:57 UTC
Issue Type: <b>Bug</b>

If I install newer version of VS Code (above 1.47), HTMLHint extension stop showing errors of html documents. I was forced to downgrade VS Code in order to keep functionality of the extension.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
spellright|ban|3.0.52
swap-word|dav|0.1.2
vscode-eslint|dba|2.1.8
htext|Hun|1.4.1
hungry-delete|jas|1.6.0
vscode-map-preview|jum|0.5.5
HTMLHint|mka|0.8.0
autotrim|Nat|1.0.6
subtitles-editor|pep|1.0.4
blank-line-organizer|rin|0.1.5
LiveServer|rit|5.6.1
lorem-ipsum|Tyr|1.2.0
errorlens|use|3.2.1

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2020-09-22 15:51
duplicate of https://github.com/microsoft/vscode-htmlhint/issues/80

**Closed by aeschli** 2020-09-22 15:51 UTC
