### ISSUE TITLE
Emmet suggestions appear out of place

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#204106] opened 2024-02-02 10:14 UTC
I don't have exact repro, but emmet suggestion appears out of place in a typescript file making completion for object members difficult to use:

<img width="809" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/b64f4292-f7a6-4131-b375-71abc1120e7f">

Even more acute case: 

<img width="809" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/024b707f-ebff-48f8-b64c-64a4628ea1f1">

Version: 1.87.0-insider
Commit: 442c133fe92b5e2606c8242caae4e68938faccc7
Date: 2024-02-01T09:51:07.293Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by rzhao271** [comment] 2024-02-02 17:58
Was this in a JSX or TSX file?
Or, do you have a JS/JSX/TS/TSX entry in `emmet.includeLanguages`?

**Comment by ulugbekna** [comment] 2024-02-02 18:14
I experience this in TSX files, no additional settings related to emmet. 

I now disabled emmet for TSX - `  "emmet.excludeLanguages": ["typescriptreact"],`

**Comment by rzhao271** [comment] 2024-02-02 18:54
Duplicate of https://github.com/microsoft/vscode/issues/51537

**Closed by rzhao271** 2024-02-02 18:54 UTC
Labels: info-needed, papercut :drop_of_blood:
