### ISSUE TITLE
Question: Is there any way to trigger a "refresh" of a CodeLensProvider?

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#11546] opened 2016-09-05 13:39 UTC
- VSCode Version: `Version 1.5.0-insider (1.5.0-insider)` 538cd9ded5a471fbb20920f01eff9c8df4b83ee9
- OS Version: `OS X El Capitan Version 10.11.6 (15G31)`

I am trying to figure out a way to trigger a refresh (recalc) of a CodeLensProvider from inside an extension. Currently the CodeLensProvider automatically is refreshed on edits, but I want to have it refreshed after the document is saved (since I want to provide an updated git blame).

I have tried just disposing the CodeLensProvider but that causes the document to jump around far too drastically. Is there another way?

Thanks!

**Comment by jrieken** [comment] 2016-09-06 09:09
dupe of #10648

**Closed by jrieken** 2016-09-06 09:09 UTC
Labels: api
