### ISSUE TITLE
Allow to configure a maximum width for editors

### ISSUE THREAD

**Issue by dtgriscom** [Microsoft/vscode#40841] opened 2017-12-26 17:25 UTC
I'm enjoying my branny new 32" display (3008 x 1692), and VSC looks great with two or three editor groups side by side. However, if I only have a single editor group open, then the editor is too darned wide. The scrollbar and its various state marks are all the way on the right edge of the screen, and I find myself constantly looking back and forth between my code and the scrollbar. As a workaround I open a random file in a second editor group, but that isn't a natural way to work.

How about adding a "Maximum Editor Width" setting, editor.maxWidth, in units of "columns", with "0" being disabled? If set, then no editor would be shown wider than that width. If this leaves unused width in the VSC window, then the groups would be shown flush left, leaving a shaded region on the right edge, whose only purpose would be as a drop zone to add another editor group. I'm not sure what would happen if you manually adjust an editor width to be wider than the setting; it probably doesn't matter as long as it's basically consistent. (Default could be disabled, or 120.)

**Comment by usernamehw** [comment] 2017-12-26 18:07
Duplicate of https://github.com/Microsoft/vscode/issues/15684 ?

**Comment by dtgriscom** [comment] 2017-12-26 18:58
Interesting, and very similar. (Strange that that PR and my suggestion happened three days apart... 'tis the season to get large monitors?)

I personally don't use Zen mode, and it would be a shame to limit this to Zen mode, though. I'm also not clear from the PR preview whether it plays nice with multiple editor groups (i.e. you can reduce the width of a single editor group, while not wasting screen area with two or three editor groups).

**Comment by bpasero** [comment] 2017-12-28 08:19
Reopening since this would be a feature request to support it independent from zen mode.

**Comment by isidorn** [comment] 2018-03-13 09:15
Clsoing as duplicate of centered mode

**Closed by isidorn** 2018-03-13 09:15 UTC
Labels: feature-request, workbench-layout
