### ISSUE TITLE
Inform user to restart VS Code after it has been updated on Linux

### ISSUE THREAD

**Issue by frkn-aydn** [microsoft/vscode#5908] opened 2016-04-27 17:18 UTC
- VSCode Version: 1.0.0
- OS Version: 14.4 UBUNTU

Steps to Reproduce:
1. i just open the VS

i dont see any color on my codes and i see this warning : [http://i.hizliresim.com/o31jQ2.png](url)

http://i.hizliresim.com/o31jQ2.png

---

Edit from @Tyriar: 

See https://github.com/Microsoft/vscode/issues/5908#issuecomment-248075263 for more details, this is the error:

> Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT

**Comment by bpasero** [comment] 2016-04-27 19:42
Never seen this error before. Almost seems to me the spawning via Electron just fails with this error.

**Comment by birz4man** [comment] 2016-04-27 20:25
Ok. i have last question. How can i fix that problem ? when i open Visual Studio i see this problem and i cant edit any code. Right now i just open and close visual studio few times and problem solved but its 
temporary solution.

**Comment by bpasero** [comment] 2016-04-28 04:17
does it reproduce with our latest insider build? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by RyanEwen** [comment] 2016-05-10 13:43
I am seeing this after updating to 1.1

**Comment by 17twenty** [comment] 2016-06-07 01:58
Can confirm I had the same issue
```Error from the extension host: spawn /usr/share/code/code (deleted) ENOENT```

It went away when I killed any already running processes. Probably should force a killall when a user restarts from an update.

**Comment by hoangnguyenba** [comment] 2016-06-16 02:36
same here, ubuntu 16.04
just updated vscode today

**Comment by psquickitprageet** [comment] 2016-06-20 06:39
+1, same issue. just updated the vscode

**Comment by RAdamMartin** [comment] 2016-07-10 19:01
Same here, just updated Ubuntu 14.04 to the June release.  Went away after full close and reopen.

**Comment by ryanbowden** [comment] 2016-07-13 07:16
Got the same error today after upgrading from 1.3 to 1.3.1 and opening a new window.

Ubuntu 14.04

**Comment by rafa-acioly** [comment] 2016-08-29 13:48
same here.

```
Distributor ID:	elementary OS
Description:	elementary OS Freya
Release:	0.3.2
Codename:	freya
```

> Error from the extension host: spawn /usr/share/code/code (deleted) ENOENT

**Comment by JMSantos94** [comment] 2016-09-09 22:39
+1 Error from the extension host: spawn /usr/share/code/code (deleted) ENOENT
I am on 1.5.1 using Ubuntu 16.04

**Comment by rafa-acioly** [comment] 2016-09-10 13:11
I solved the problem by re-installing vscode completely.

**Comment by 17twenty** [comment] 2016-09-11 10:47
The fix would be for the installer to do a ```killall code``` as part of the install scripts in the deb. Basically, it's getting sad because things are linking to old binaries/libs that have been replaced.

By all means, respawn code after installing but that would fix the issue.

**Comment by pepemarino** [comment] 2016-09-13 06:18
I got this error on code 1.5.2 after installing extensions Ruby 0.5.6 and Ruby Language Colorization 0.0.6.  My OS is Ubuntu 16.04.

**Comment by bpasero** [comment] 2016-09-18 07:18
Moving to @Tyriar based on the last comments that this could be a problem with the update from a package. Could it be the update leaves the old running instance around including the extension host and thus the new instance fails to create it?

**Comment by Tyriar** [comment] 2016-09-19 18:05
If anyone reproduces this again can you check which processes are still running after you exit VS Code?

```bash
ps aux | grep code
```

**Comment by Tyriar** [comment] 2016-09-19 18:15
OK never mind, I just reproduced this:

```
Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT
```

These are my repro steps:

1. Open vscode insiders
2. Update vscode insiders to latest
3. Open a new folder

I fixed the issue by simply exiting and reopening vscode. This is as designed, you *must* exit VS Code after updating or you will get a mish-mash of the current and old version which is not designed to work. A possible improvement that could be made is to somehow catch this in a reliable way and present a more useful message indicating to restart vscode

**Comment by d4nyll** [comment] 2016-11-02 15:14
Error occurs when you have VSCode open whilst installing an update. Simply close all VSCode windows and open them again.

**Comment by Tyriar** [comment] 2017-04-20 18:12
Accepting PRs for this, to fix this I think you'll need to search for where the exception is happening in the code base (somewhere related to reloading the window?) and handle `ENOENT` by giving a nicer error message. If you get `ENOENT` and then stat the file and it exists and we're on Linux, it's probably safe to assume this is the case.

**Comment by Tyriar** [comment] 2018-09-12 19:44
The snap package would handle this when the snap is updated: https://github.com/Microsoft/vscode/issues/5458

**Comment by Tyriar** [comment] 2018-09-12 21:36
Some solutions/problems discussed in https://github.com/Microsoft/vscode/issues/45569

**Comment by Tyriar** [comment] 2019-10-09 22:11
I don't think this is a problem anymore.

**Closed by Tyriar** 2019-10-09 22:11 UTC
Labels: feature-request, help wanted, install-update, linux
