### ISSUE TITLE
Problem with high contrast

### ISSUE THREAD

**Issue by Diyorbek7747** [microsoft/vscode#125767] opened 2021-06-08 17:47 UTC
Hello dear developers, I would like to inform you about the problem with high contrast in Microsoft Visual Studio Code, I turned on the high contrast mode in my computer, and then when I turned it off in all applications, this function was turned off, but not in your program. When I try to turn off this mode with a keyboard shortcut in the Microsoft Visual Studio Code application, but it still fails. Help me please. Windows 10 OS

**Comment by aeschli** [comment] 2021-06-09 21:22
duplicate of #125770

**Closed by aeschli** 2021-06-09 21:22 UTC
