### ISSUE TITLE
Merge Does Not Open When Result File Is Already Opened In Active Editor Group

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#158411] opened 2022-08-17 22:36 UTC

**Comment by jrieken** [comment] 2022-08-18 08:37
/duplicate of https://github.com/microsoft/vscode/pull/158377#discussion_r948315556

**Closed** 2022-08-18 08:37 UTC
Labels: bug, merge-editor

**Comment by bpasero** [comment] 2022-08-18 08:47
Yeah, reviewing that change now, I also felt its the cause.
