### ISSUE TITLE
Can't step into Node.js code using F11

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/vscode#22188] opened 2017-03-08 01:49 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 10

I've tried both "node" and "node2" debuggers. Using "node2" I can get the visual "step into" icon to work but if I press F11 its as if I pressed "Run" For the "node" type debugger the visual icon doesn't even work. This just started after the last update. Please help. It's super annoying...

**Comment by Stevenic** [comment] 2017-03-08 02:05
I re-booted my laptop and now I get "Unable to open 'VM560': Cannot read property 'body' of undefined." when I try to step into a function. Sometimes it will work other times it just hangs.

**Comment by Stevenic** [comment] 2017-03-08 03:03
I ended up just starting a new project and copying over my exact same code to fix the issue which is crazy because I'd already tried deleting the .vscode folder from the project that wasn't working.

**Comment by ramya-rao-a** [comment] 2017-03-08 06:39
So at the moment does F11 and the step into icon work as expected?

**Comment by isidorn** [comment] 2017-03-08 09:49
Just tried on Win10 and works nicely for me both by pressing F11 and by clicking on the icon.
Can you also reproduce this issue for vscode insiders? Can you reproduce this issue for any repository you try to debug? Can you create a small repository on GitHub for which we can reporduce your issue and investigate further? Can you still reproduce if you add a custom shortcut for stepInto action in your use keyborad preferences?

If you are maybe running win10 inside a VM running on a mac make sure to disable F11 to show desktop on mac.

**Comment by cwgabel** [comment] 2017-03-13 07:54
I too cannot single step consistently. 
All extensions off. Windows 8.  VSC 1.10.2

**Comment by isidorn** [comment] 2017-03-13 10:04
@cwgabel what debug type are you using? What does it mean not consistently? That both clicking in the debug toolbar and F11 produce no effect at all?

**Comment by cwgabel** [comment] 2017-03-13 15:44
### Node V7.2.1. The cli node debugger works fine, here's my launch.json (partial)
```js
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "defgen.js",
            "program": "${workspaceRoot}//utils//defgen.js",
            "cwd": "${workspaceRoot}"
        },
        ....
    ]
```
### Consistently works great on a small script  like: (running from c:\vsctest) 

```js
var path = require('path');
var mine = require('./myrequire');
var next = 'next';
console.log('finished');
```
I can single step through the require all day long and not miss a beat....

### But on this:

```js
var path = require('path');
var express = require('express');
var colors = require('colors');
var settings = require('./config/settings');
var environment = require('./config/environment');
var routes = require('./config/routes');
var debug = require('debug')('server');

// var models = require('./app/models/');

module.exports.start = function(done) {
    var app = express();

    environment(app);
    routes(app);
    debug("made it here");
    app.listen(settings.port, function() {
        console.log(("Listening on port " + settings.port).green);

        if (done) {
            return done(null, app, server);
        }
    }).on('error', function(e) {
        if (e.code == 'EADDRINUSE') {
            console.log('Address in use. Is the server already running?'.red);
        }
        if (done) {
            return done(e);
        }
    });
}
if (path.basename(process.argv[1], '.js') == path.basename(__filename, '.js')) {
    module.exports.start()
}
```

### I cannot step into:
  var path = require('path')

###   I can step into: 
var express = require('express'); 
...but I never hit the express module. I click single step maybe six times and get through module.js and assert.js but something bounces me back to my main code and advances to the next breakpoint - not the next statement.

The code provided all runs clean and has no eslint errors, just some warnings on unused variables. 

Possibly relevant: 
It very rare that I can set a column breakpoint.  Say for console.log('...'), I can get the red dot indicator between say the console and log, but it goes away almost immediately up clicking any debug action, even if I'm debugging on lines prior to this statement. 

If you need anything else, let me know. 

Happy hunting.

**Comment by Stevenic** [comment] 2017-03-13 19:25
Mine started working when I re-created my project in another folder with all new files.  I literally just copied the contents of each file as it was a small project. And yes I had already tried deleting the .vscode folder.

P.S. - I'm in MSFT Bldg 112 if anyone in Redmond wants to come over and debug the other project.

**Comment by cwgabel** [comment] 2017-03-15 02:50
```js
1   var a = "global variable";
2   var F = function() {
3     var b = "local variable";
4      var N = function() {
5          var c = "inner local";
6          return b;
7      };
8     return N;
9   };
10  var inner = F();
11  console.log(inner());
12  s = 8;
13  var path = require('path');
14  console.log('done');
```

The above works fine for single step debugging on everything but as soon as you add a watch variable (say b), it only steps from 1 to 2 to 10 and then it's done.

Also,  clicking the debug restart icon reloads the sidebar from the debug view to the explorer view. I can't even get it to work with the keyboard (ctrl shift f5) does nothing.

**Comment by weinand** [comment] 2017-03-15 10:13
@cwgabel I can reproduce the problem in Stable (1.10.2) but not in the Insider (1.11.0).
(In the Insider I've fixed an incompatibility with recent versions of node/v8)

Could you try to verify that the problem no longer appears in Insiders?

BTW, what version of node are you using?

**Comment by weinand** [comment] 2017-03-15 10:20
@cwgabel I do not understand your second problem ("reloads the sidebar from the debug view"). 
Could you help us by providing a screenshot or screen cast?

/cc @isidorn

**Comment by cwgabel** [comment] 2017-03-17 14:59
Insiders version has fixed the problem. Thank you. I'm running node 7.2.1.

### reloads the sidebar from the debug view 

The sidebar would change from the debug view to the explorer view when I clicked the restart debug icon. I cannot recreate that problem with insiders. 

### New issue
The one new problem I've experienced (including insiders 1.11.0) pertains to files opened by the debugger during a debug session go blank (no code shown, tabs remain open with tabs showing file name). I can continue to debug the code as I can see the call stack and pertinent information in the debug sidebar view, but the tabs remain blank and and do not close automatically once I force debug session to stop (shift f5).  Occasionally I'll get multiple tabs opened on the same file (say module.js). 

A simple restart/reload of VSC is the quickest solution to this problem.

**Comment by roblourens** [comment] 2017-03-17 15:11
The new issue sounds like https://github.com/Microsoft/vscode/issues/22418 (which applies to any script that isn't in the workspace, eg module.js)

**Comment by weinand** [comment] 2017-03-17 15:20
@cwgabel since your 'new issue' is covered by #22418, I will close this issue.

**Closed by weinand** 2017-03-17 15:20 UTC
Labels: debug
