### ISSUE TITLE
Can not to uninstall plugin

### ISSUE THREAD

**Issue by aox-lei** [Microsoft/vscode#61570] opened 2018-10-23 07:31 UTC
Version: 1.28.2
I uninstalled a plugin. but when I switch other project. the plugin has became installed.

**Comment by weinand** [comment] 2018-10-23 07:58
Please provide steps for how you uninstalled the extension.
For what extension are you seeing this?

**Comment by aox-lei** [comment] 2018-10-24 08:18
@weinand 
I clicked the extensions slider and selected the python extension and click "uninstall" button
![1540368995384](https://user-images.githubusercontent.com/8756622/47416414-3f395680-d7a8-11e8-8037-63e6a927f30a.jpg)

switch project used project Manager extension

thanks for it.

**Comment by weinand** [comment] 2018-10-24 09:23
And after clicking "Uninstall" you did press the "Reload to deactivate" button?

**Comment by aox-lei** [comment] 2018-10-25 01:47
@weinand 
yes, clicking "Unistall" after switch other project , uninstalled extension actually came back.
I am so sorry that I am not good at english

**Comment by sandy081** [comment] 2018-10-25 10:29
@aox-lei What do you mean by switching other project and where do you see the extension back again?

Can you please do following:

- Uninstall the extension
- Reload the Window
- Check if the extension is uninstalled or not

**Comment by aox-lei** [comment] 2018-10-26 02:03
I seted two project by "Project Manager" extension.

```json
projects.json
[
       {
		"name": "django_example",
		"rootPath": "/var/www/django_example"
	},
	{
		"name": "aox_crawl_fund",
		"rootPath": "/var/www/aox_crawl_fund"
	}
]
```

I uninstalled "Python extension", after reload the window, then used command "Project Manager: List Projects to open ", to switch the "django_example" project, the "Python extension" back!

vscode Version:  1.28.2 (1.28.2)
in MAC OS X (10.13.6)

**Comment by sandy081** [comment] 2018-10-26 10:03
@aox-lei By any chance the window having `django_example` project was open when you are using the command?

**Comment by aox-lei** [comment] 2018-10-26 10:08
@sandy081 yes

**Comment by sandy081** [comment] 2018-10-26 14:30
@aox-lei Ok, that explains it. Extension is already loaded in that window and extension got uninstalled after. You have reload the other window too for the extension to be unloaded. Do you see any actions on the extension in the extension view?

**Comment by aox-lei** [comment] 2018-10-27 07:13
yes

**Comment by aox-lei** [comment] 2018-10-27 07:13
@sandy081 yes

**Comment by sandy081** [comment] 2018-10-29 20:04
As mentioned in [comment](https://github.com/Microsoft/vscode/issues/61570#issuecomment-433427622) this is because the window was already open and you have to reload the window for the extension to be unloaded. Hence closing this as designed.

**Closed** 2018-10-29 20:04 UTC
Labels: *as-designed, extensions, needs more info
