### ISSUE TITLE
Feature Request: Column editor like in Visual Studio 2015

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#34355] opened 2017-09-14 08:19 UTC
In Visual Studio 2015 you can hold down ALT and select multiple lines to edit multiple columns.

you can also arbitrary select text in columns the same way, delete it or replace it. 

Its WAAAAAAY EASIER than creating more cursors like in VSCODE.

Column Editing like in VS2015 improve productivity, 

MAKE IT SO... please :)

**Comment by SilverBut** [comment] 2017-09-16 15:46
Use Alt+Mouse Click or Alt+Shift+Arrow. Worked in my version 1.16.1

**Comment by Montago** [comment] 2017-09-18 13:38
> Use Alt+Mouse Click or Alt+Shift+Arrow. Worked in my version 1.16.1

None of those suggestions does anything of what i asked.

**Comment by gwicksted** [comment] 2017-11-26 17:18
Related request: #36892

This is a duplicate of #5402 and #28186 -- possibly others.

And it certainly needs attention!  This is a big productivity win when available.

**Closed** 2019-05-01 23:41 UTC
Labels: *duplicate, editor-columnselect, feature-request
