### ISSUE TITLE
Key maps do not work!!

### ISSUE THREAD

**Issue by prsnnami** [Microsoft/vscode#24502] opened 2017-04-11 11:06 UTC
I run Ubuntu 16.10 and i mapped the keys CAPS + IJKL to the arrow keys , however they do not work properly in VS code but work anywhere else in the System.

I dont know the exact mechanism of the map but i think i mapped CAPS to a third level of shift or something.

**Comment by alexandrudima** [comment] 2017-04-11 12:28
Duplicate of #23991. A workaround is provided in https://github.com/Microsoft/vscode/issues/23991#issuecomment-292336504

**Closed by alexandrudima** 2017-04-11 12:28 UTC
