### ISSUE TITLE
Opening of snippet doesn't absorb auto-closing parenthesis

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32428] opened 2017-08-13 19:29 UTC
- VSCode Version: 1.15
- OS Version: win7x64

First I type (F) and the snippet opens without problem.
But if I too lazy to type (F) and type just (F - opening of snippet will not absorb the second parenthesis.
I think it should.

![f](https://user-images.githubusercontent.com/24613274/29252770-11a9b064-8076-11e7-9a72-a645f834f5b3.gif)

**Comment by jrieken** [comment] 2017-08-16 07:14
duplicate of https://github.com/Microsoft/vscode/issues/10266

**Closed by jrieken** 2017-08-16 07:14 UTC
Labels: snippets
