### ISSUE TITLE
Find in files conflict with OneDrive

### ISSUE THREAD

**Issue by abrud** [Microsoft/vscode#43206] opened 2018-02-08 12:42 UTC
### Issue Type
Bug

### Description

If the opened folder is a subfolder of a local OneDrive synced folder, for example: "C:\Users\jsmith\OneDrive - My Company\Code-Projects\test-code-search" then Find in files will find results only in already opened files in editor. It will not find results in unopened files in same opened folder.
If I move the folder elsewhere, search works.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|Memory (System)|15.87GB (9.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by olmor** [comment] 2018-02-08 13:22
Find in files will find results only in already opened files in editor.
This bug is not only for OneDrive folder but for all local folders.

**Comment by abrud** [comment] 2018-02-08 14:19
Well, using v1.20.0, if my test folder is on Desktop, for example, it works with no opened files - see atached screenshot.
![snip_20180208111756](https://user-images.githubusercontent.com/12251466/35977373-be390a78-0cc1-11e8-852b-a130abeb3ef6.png)

**Comment by roblourens** [comment] 2018-02-08 18:42
duplicate of https://github.com/Microsoft/vscode/issues/35433, this should be fixed in Insiders

**Closed by roblourens** 2018-02-08 18:42 UTC
Labels: new release
