### ISSUE TITLE
Support MacOS Sierra application tabs for multiple windows

### ISSUE THREAD

**Issue by PhoenixWright** [Microsoft/vscode#15478] opened 2016-11-14 18:59 UTC
Hi vscode,

I wanted to ask about MacOS Sierra's tab support for applications - from Apple marketing, we hear that tabs for applications should "just work".

For some applications, when multiple windows are open, the option appears in the menu bar under Window -> Merge All Windows. It would be awesome to manage multiple Code windows in this way, if the implementation is a config change or similar.

This is slightly related to #396, but ultimately serves a different purpose.

EDIT: While using the application, I realized that Cmd+Opt+Shift+N is actually able to create a new tab today - perhaps there is no extra work needed after all!

**Comment by PhoenixWright** [comment] 2016-11-14 19:00
Here are some examples as documented at: http://www.howtogeek.com/275155/how-to-add-tabs-to-almost-any-app-in-macos-sierra/

![macos-sierra-merge-all-windows](https://cloud.githubusercontent.com/assets/382245/20278414/6f0f9b04-aa59-11e6-9ef8-298bace4fbf7.png)
![sierra-windows-merged](https://cloud.githubusercontent.com/assets/382245/20278420/745d8396-aa59-11e6-8131-36828605bc4a.png)

**Comment by TwisterMc** [comment] 2016-11-18 13:35
Related, if you setup your Mac to always use tabs (System Preferences -> Dock -> Prefer tabs when opening documents: Always) you'll end up with two tab bars in Visual Studio Code.  It'd be great if the app could detect this setting and then disable the editors tabs. 

Screenshot: https://cloudup.com/c0RsWsriDC5

**Comment by nicdoye** [comment] 2016-11-25 16:00
@PhoenixWright  File->New Window (Shift-Cmd-N) has opened new tabs for a while. (Perhaps only since 1.7.0 though). 

However, when there's an update to VSCode, and it asks to restart, it then opens all the windows as separate windows, and not tabs. (I shall have to check if there's a "Merge All Windows" at this point (but I doubt it)). This is clearly inconsistent behaviour.

@TwisterMc For your idea, when you split the editor pane into multiple panes, I don't believe the Mac window/tab paradigm would work. In my _opinion_ that's why the current system (where it works by having one project per window/tab) is the way it is. Using macOS' windows-as-tabs feature interferes little with the Electron app; recoding the top-level UI to use macOS interface would.

**Comment by eggbit** [comment] 2016-11-30 16:26
Related: The `-n` switch opens files and directories in a new window but behaves differently than `File->New Window` where it creates a new tab in the current window.  It would be nice if they both had the same behaviour.

**Comment by kavehv** [comment] 2016-12-09 17:12
@TwisterMc I actually prefer it this way, at least until VS Code supports opening multiple folders as part of one project.  This is the only way I have to open multiple folders in one window.

**Comment by bkniffler** [comment] 2016-12-15 22:26
Just installed osX 10.12.2 (had 10.12.1 before with no issues) and vscode tabs disappeared. New windows won't appear as tabs, the "Window" menu item hasn't any tabs related stuff, nothing there. Other programs (like textEdit.app) still work with tabs. Anyone else suffering from this issue?

**Comment by pafffkata** [comment] 2016-12-16 07:22
+1 ^ Exactly the same behaviour - just updated to MacOS 10.12.2 and am experiencing the same symptoms as the described above. Tabs were working until that moment.

**Comment by nunovieira** [comment] 2016-12-16 10:39
I'm still on macOS 10.12.1, but updated to vscode 1.8.0 and no longer can open multiple projects in tabs. It was possible on vscode 1.7.x...

**Comment by andrewatwood** [comment] 2016-12-16 18:37
Yup they used to work perfectly! Super confusing and disappointing.

**Comment by kavehv** [comment] 2016-12-16 18:38
I miss these too, but if they are fixed, can we request that the option to merge all windows be presented under the Window menu?  It wasn't before.

**Comment by eliprand** [comment] 2016-12-19 20:46
One thing I would like to clarify here is that this is classified as a *feature request*. As mentioned by @bkniffler and subsequent entries, this *was* working with `1.7.x` and stopped working with `1.8.0`. We may want to reclassify it.

**Comment by aakrem** [comment] 2016-12-29 10:15
Cmd+Shift+N is not creating a new tab in macOS Sierra v10.12.1 with Code v1.8
It's working in Code v1.7.2 with the same macOS version.

**Comment by alasdairhurst** [comment] 2017-01-04 10:18
@eliprand >  We may want to reclassify it.
Definitely! It's a regression, and should be prioritised as such.

**Comment by chenjie4255** [comment] 2017-01-17 01:32
same problem as you guys macOS Sierra v10.12.1 with Code v1.8 latest, this make me hard to switch project between workspaces.

I hope this could be fixed ASAP....

**Comment by bkniffler** [comment] 2017-02-02 12:23
Any progress? Working on multiple projects on my small macbook has become a pain ever since this doesn't work (nearly 2 months now!). Please fix this!

**Comment by eliprand** [comment] 2017-02-02 20:11
That's apparently a NO since 1.9.0 came out and still broken. What really rubs me the wrong way is that is that people who insist on labeling this a "feature-request" are ignoring the fact that it was working just fine until someone (either on the VS Code team or the underlying framework), changed something that made it stop working too.
Like many people on this thread, I work with several projects at once (yes, my API is in a different project than my Angular code, it's called "good practices"). And having to cycle through the open windows is a serious productivity killer.
Furthermore, the lack of actual communication (all I see from people involved in the project are a bunch of status updates, labels, issues closed, duplicates, etc.). Can someone on the project please take 5 minutes and tell us why this is so hard and when they think it's going to be fixed?

**Comment by andrewatwood** [comment] 2017-02-02 20:14
No kidding! That re-labeling ruined this and has really dragged it out 

# Hi VSCode team this is not a new feature! This is a bug! A pretty big one! Ok thanks ;)

**Comment by bpasero** [comment] 2017-02-03 06:05
VS Code is using [Electron](https://github.com/atom/electron) as framework for all UI related concerns and that includes things like macOS Sierra tabs. There is no way we could support this without helping Electron to support this feature. They already have an issue logged for this here: https://github.com/electron/electron/issues/6124

It is true that for one version we saw Sierra tabs enabled in VS Code but that was only the case because the Sierra update came in and just added tabs support without Electron being aware of it (macOS just added a new menu entry under the view menu and hijacked the "New Window" action to add a new tab if you are in full screen mode). 

Now, until Electron provides proper API to support all aspects of this new OS feature, they decided to disable it in [Electron 1.4.2](https://github.com/electron/electron/releases/tag/v1.4.2) (see `Hide Show Tab Bar menu item on macOS Sierra.` https://github.com/electron/electron/pull/7415).

I suggest that people put their energy of this topic into the Electron issue because that is the place where we should discuss how this feature can come back 👍

**Comment by bkniffler** [comment] 2017-02-07 16:46
Just in case anyone wants to revert to a version that has functional tabs for Mac Sierra:
https://az764295.vo.msecnd.net/stable/7ba55c5860b152d999dda59393ca3ebeb1b5c85f/VSCode-darwin-stable.zip

**Comment by DomVinyard** [comment] 2017-03-20 15:13
I have reverted, i can't think of any features introduced since then that are as important as this.

**Comment by bkniffler** [comment] 2017-03-30 22:40
Hey, there's just been native tabs feature merged into electron: https://github.com/electron/electron/pull/9052

Yay!

**Comment by PhoenixWright** [comment] 2017-03-30 22:42
Brilliant! Thanks for the hard work, team.

**Comment by chenjie4255** [comment] 2017-03-31 01:48
Can't wait for a new version VSCode

**Comment by bpasero** [comment] 2017-04-02 02:29
Current status: Electron 1.6.5 introduced a new option to bring back native macOS Sierra tabs which basically brings us back to where we started with when we had no control of making this optional. This would enable us to make it configurable for the user (e.g. `window.nativeTabs` setting). 

There are however limitations:
* it will not work with a custom title bar style set, so enabling native tabs will disable custom title
* we currently cannot restore tabs to the location they were arranged to because we have no information about this provided from electron
* as it looks now, a new tab will be added when in fullscreen mode and opening a new window but not when not in fullscreen mode (you can still arrange windows to tabs)
* there is a new entry View > Show Tab Bar that is added by macOS as the first entry (we currently cannot move it)

**Closed** 2017-04-24 09:05 UTC
Labels: feature-request, upstream, workbench

**Comment by bkniffler** [comment] 2017-04-24 10:28
Since this been closed without a commit linked, has this been solved @bpasero? Is there a configuration option now?

**Comment by bpasero** [comment] 2017-04-24 11:57
@bkniffler there is a commit linked: https://github.com/Microsoft/vscode/commit/094800ee1388fd0a004440f0ac5ab5014481e909

the setting is called `"window.nativeTabs": true`

**Comment by bpasero** [comment] 2017-04-24 11:57
That said, I wonder if the setting name actually is a good one, feedback welcome :)

**Comment by bkniffler** [comment] 2017-04-24 12:40
Oh, I'm blind, have been looking from your comment downwards, thanks for highlighting the commit! Just tested, seems to work fine. For anyone who wants to update, the Insider Version 1.12.0 works with "window.nativeTabs": true

Thanks @bpasero!

**Comment by chenjie4255** [comment] 2017-04-25 02:25
@bpasero thanks for your wonderful work, but I think VSCode is missing a switch windows command, current "Switch Windows " command is used in a windows, It seems that there is no way to switch window in nativebar?

**Comment by bpasero** [comment] 2017-04-25 04:55
@chenjie4255 is this a native macOS command, can you show where other apps have it?

**Comment by chenjie4255** [comment] 2017-04-25 05:22
@bpasero the MD editor Typora have it (in Window->show next tab/show previous tab), But I am not sure if it is a native bar feature.

**Comment by bpasero** [comment] 2017-04-25 05:47
Unfortunately we do not have API in Electron for tab management for actions like that.

**Comment by chenjie4255** [comment] 2017-04-25 06:28
It is a pity for that, I think I could goto Electron project for help.

**Comment by Borongaj** [comment] 2017-05-05 09:25
Version 1.12.1 doesn't works with "window.nativeTabs": true on my macOS Sierra 10.12.4...

**Comment by commarla** [comment] 2017-05-05 11:26
1.12.1 on sierra 10.12.4 works fine for me.

**Comment by Borongaj** [comment] 2017-05-05 12:47
Crazy!

1.12.1 doesn't show the Tab Bar, but 1.13 Insiders show it normaly.

I'm not alone : https://github.com/Microsoft/vscode/issues/25919

**Comment by Borongaj** [comment] 2017-05-05 12:55
Seems to be some _window_ params conflict with the new window.nativeTabs option.

**Comment by pi0** [comment] 2017-07-11 22:55
Anyone noticed Why native tabs are broken again with `1.13-*` ~> `1.14.*` ?  😭

**Comment by cschiewek** [comment] 2017-07-11 23:24
It works fine for me @ 1.14.0

**Comment by chenjie4255** [comment] 2017-07-12 02:36
It works fine for me too with 1.14.0
@pi0 Try close all the windows and open vscode again.

**Comment by pi0** [comment] 2017-07-12 08:38
But i swear it was broken :)) Will try upgrading vscode on another mac to make sure it wasn't false positive :))

**Comment by yoyo930021** [comment] 2017-07-12 12:24
Have `Window -> Show Tabbar` when Start.
![2017-07-12 8 18 52](https://user-images.githubusercontent.com/9126398/28117387-ce34dbfa-673f-11e7-8c65-b01fce4ba871.png)
but broken when `Open new Window`
![2017-07-12 8 19 08](https://user-images.githubusercontent.com/9126398/28117431-fd8f9bce-673f-11e7-8280-e91c66cb7284.png)

**Comment by yeliex** [comment] 2017-08-09 06:40
the same @yoyo930021

**Comment by chenjie4255** [comment] 2017-10-08 02:04
:( 
It break again when I upgrade macOS to mac high sierra, the 'Window' menu have no 'merge all windows 'command 
vscode verison:1.17.0

**Comment by chenjie4255** [comment] 2017-10-08 02:10
:(
It seems like it broken again when I upgrade macOS to mac high sierra, the click the command  'merge all windows ' doesn't have any effects.
vscode verison:1.17.0

**Comment by Borongaj** [comment] 2017-10-08 06:15
Changelog :

"Note: Native tabs on macOS High Sierra (10.13) are currently only partially supported. We are working on a fix, stay tuned!"

**Comment by nantaphop** [comment] 2017-10-17 01:32
1.17.1 worked after set windows.nativeTab to true.
<img width="985" alt="screen shot 2560-10-17 at 8 30 55 am" src="https://user-images.githubusercontent.com/1725346/31642516-9f7fd5f4-b315-11e7-81d9-268ad9b93669.png">

**Comment by chenjie4255** [comment] 2017-10-17 02:11
@nantaphop 
No, It still no work on macOS High Sierra (10.13)...

**Comment by nantaphop** [comment] 2017-10-17 02:16
@chenjie4255 i'm on Sierra 10.12.6 btw.

**Comment by sebrandon1** [comment] 2017-11-02 15:18
Any updates for High Sierra support yet?  Miss my multiple tabs in the same window.........

**Comment by chenjie4255** [comment] 2017-11-10 11:56
the latest version(1.18.0) still can't work properly with mac's native bar..   :(

**Comment by andrewatwood** [comment] 2017-11-10 17:28
Yep still a problem!

Anyone who wants to still attempt to use it, the window switch shortcut works pretty well in terms of making do, gives you a dropdown to pick from. Not quite as nice but it's much better than going up to the menu bar.
