### ISSUE TITLE
Intellisense replaces correct path when manually typed

### ISSUE THREAD

**Issue by andytuba** [Microsoft/vscode#21026] opened 2017-02-21 23:43 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 15.6.0 (OSX El Capitan 10.11.6)
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.5|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|docthis|joelday|0.3.11|

Steps to Reproduce:

1. Create a project with two files: `ThisProject/src/app/actions/comment.ts` and `ThisProject/src/app/components/CommentsPage.tsx`
2. Add a `tsconfig.json` that sets `"paths": { "app": ["./src/app"], "app/*": ["./src/app/*"] }`
1. Edit `CommentsPage.tsx`
1. Type in `import * as commentActions from 'app/actions/comment';`

Expected: Intellisense does nothing
Actual: When I type the last `'`, Intellisense replaces `'app/actions/comment'` with `'app/*'`

http://imgur.com/a/Chw0J

**Comment by mjbvz** [comment] 2017-02-24 03:22
Can you please share your vscode settings. I see you have `"editor.autoClosingBrackets": false` but I'm not able to reproduce this issue.

There appear to be a couple of possible issues:

* the `app/*` suggestion is hanging around after typing the rest of the path. I'm not sure of the root cause here.
* TypeScript should not return `app/*` as a module suggestion in the first place.  @mhegazy, is the `tsconfig.json` used here actually valid? It was unclear to me where glob patterns are supported in the `paths` compiler option

**Comment by mhegazy** [comment] 2017-02-24 03:25
Looks like a typescript bug. I would port this over.

**Comment by mjbvz** [comment] 2017-02-24 03:35
Thanks @mhegazy. I've opened https://github.com/Microsoft/TypeScript/issues/14282 to track `app/*` being returned as a module name in the suggestions.

I'm still interested in why the suggestion list remains showing though, and the root cause of that is probably somewhere on the VSCode side

**Comment by mjbvz** [comment] 2017-03-01 02:24
Closing as we need more info to investigate this on the VSCode side. @andytuba please try disabling all extensions. If you stills see the suggestions lingering about while typing, share your VSCode settings and I can take a look

**Comment by andytuba** [comment] 2017-03-01 18:35
I updated extensions and disabled extensions and could still reproduce it.  I did notice that after disabling extensions and restarting the app, it seemed to work fine for a little bit.

settings.json:
```json
// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0,
    "editor.autoClosingBrackets": false,
    "editor.rulers": [79, 100]
,
"files.associations": {
    "*.pyx": "python"
},
"files.autoSave": "afterDelay"
}
```

**Comment by andytuba** [comment] 2017-03-01 18:46
Would it be useful to assemble a package with a miniature project and my settings?

**Comment by mjbvz** [comment] 2017-03-02 02:47
@andytuba Yes, if you could do that it would help the investigation. Also, are you using any custom keybindings or a different keyboard layout by chance?

**Comment by mjbvz** [comment] 2017-03-20 21:31
Closing again as we still need more info. @andytuba Please provide a small example project and your settings if you are still running into this

**Closed by mjbvz** 2017-03-20 21:31 UTC
Labels: javascript, needs more info, typescript
