### ISSUE TITLE
Only extensions that are available to vscodium are visible

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#110599] opened 2020-11-13 21:50 UTC
- VSCode Version: 1.50.1-1
- OS Version: manjaro 5.8

Steps to Reproduce:

1. Install it after using vscodium

Does this issue occur when all extensions are disabled?: No

Can be solved if I find out where the product.json is

**Comment by tamuratak** [comment] 2020-11-14 00:19
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed** 2020-11-14 04:43 UTC
Labels: *duplicate

**Comment by Twiggeh** [comment] 2020-11-16 10:31
The solution to this would be to say whether there is a product.json and where its located to set the stores url and not a "please ask microsoft nicely to release their packages on the OpenVSX"
