### ISSUE TITLE
Toggle Tab Key Moves Focus does not appear in command palette anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#174450] opened 2023-02-15 11:06 UTC
* open command pallette
* look for Toggle Tab Key Moves Focus
* :bug: it doesn't appear there, but the keybinding for it works
```
Version: 1.76.0-insider
Commit: 01d2cc631490d923f0c232daa2d0f076d8a6cc70
Date: 2023-02-14T16:08:05.334Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

**Comment by meganrogge** [comment] 2023-02-15 15:23
This hasn't been merged yet, so I don't think I caused this regression 🤔 https://github.com/microsoft/vscode/pull/174265

**Comment by meganrogge** [comment] 2023-02-16 18:26
looks like the type provided for `title` is wrong 

![Screenshot 2023-02-16 at 12 25 01 PM](https://user-images.githubusercontent.com/29464607/219454914-09ff6f8b-cbe6-4932-8523-e01ecf6cc36b.png)

**Closed** 2023-02-16 20:02 UTC
Labels: bug, accessibility, regression
