### ISSUE TITLE
[c++] grammar in endless loop

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23850] opened 2017-04-03 09:55 UTC
* have the below cpp-file
* :bug: an error about the grammar being in an endless loop appears

```cpp


#include <windows.h>

#ifdef


```

**Comment by aeschli** [comment] 2017-04-05 12:59
The problem is https://github.com/Microsoft/vscode/blob/master/extensions/cpp/syntaxes/c.json#L775
```
{
					"begin": "\\G",
					"end": "(?=//)|(?=/\\*(?!.*\\\\\\s*\\n))|(?<!\\\\)(?=\\n)",
					"name": "meta.preprocessor.c",
					"patterns": [
						{
							"include": "#preprocessor-rule-conditional-line"
						}
					]
				}
```
Because of the fix for https://github.com/Microsoft/vscode-textmate/issues/12
we recover by entering the rule and go to the next line.

Moving to vscode-textmate

**Comment by aeschli** [comment] 2017-04-05 12:59
This issue was moved to Microsoft/vscode-textmate#40

**Closed** 2017-05-29 13:51 UTC
Labels: bug, languages basic

**Comment by aeschli** [comment] 2017-05-29 13:53
https://github.com/atom/language-c/pull/237 in the PR for atom/language-c. As discussed in https://github.com/atom/language-c/issues/218, it has to do with differences in the textmate implementation of Atom and VSCode.
