### ISSUE TITLE
new style to React.Fragment not supported by code coloring

### ISSUE THREAD

**Issue by akshatbhargava123** [microsoft/vscode#86001] opened 2019-12-03 05:29 UTC
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. Simply write `<> <p>Some content</p> </>` in your JSX react/react-native code.

Does this issue occur when all extensions are disabled?: Yes

Screenshot:

![image](https://user-images.githubusercontent.com/22184427/70022938-ea2b5f00-15bb-11ea-9975-7b85e9001e2a.png)

Colors show correctly if I change `<></>` to `<React.Fragment></React.Fragment>`

**Comment by mjbvz** [comment] 2019-12-03 05:40
Are you sure you don't have any extensions enabled?

If so, please share code from the screenshot as text

**Comment by gerrytan** [comment] 2019-12-09 10:43
I had the same problem, solved it by disabling https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring. I'm not sure if this extension is still relevant.

**Comment by mjbvz** [comment] 2019-12-09 19:42
Closing as most likely caused by an extension

**Closed by mjbvz** 2019-12-09 19:42 UTC
Labels: javascript, needs more info
