### ISSUE TITLE
editor.cursorSurroundingLines will select text above or below cursor.

### ISSUE THREAD

**Issue by Naughtyusername** [microsoft/vscode#81300] opened 2019-09-23 04:35 UTC
When you click within the range you set for "editor.cursorSurroundingLines" if you move the mouse or touchpad at all, it will select X amount of text depending on how long the delay on your release click is. Generally it selects a big chunk of code and its quite frustrating. 

Is there anything we can do for this? either remove the delay or add extra options onto it so those of us with this issue can toggle it off.

https://i.stack.imgur.com/JQD3v.gif - Example from my pose about this on SO the other day.

**Comment by gjsjohnmurray** [comment] 2019-09-23 08:45
/duplicate of #79934 most likely, assuming @Naughtyusername  isn't using the Insider build where that is already fixed.

**Closed** 2019-09-23 08:45 UTC
Labels: *duplicate
