### ISSUE TITLE
--goto flag opens two windows

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54996] opened 2018-07-25 08:24 UTC
re #54864

* run `code --goto /Users/jrieken/Code/vscode/src/bootstrap.js:23`
* two windows open, both showing the same file at line 23

**Comment by sandy081** [comment] 2018-07-25 10:07
@jrieken I cannot reproduce it. Do you have any previous state like if there are some windows already opened? And do you have any special window settings?

**Comment by jrieken** [comment] 2018-07-25 10:57
Don't recall anymore... Might be that I had other windows open but I can't reproduce anymore either...

**Comment by sandy081** [comment] 2018-07-25 12:40
Ok, closing as it cant be reproduced. Please reopen it if you find the trick to reproduce.

**Closed by sandy081** 2018-07-25 12:40 UTC
Labels: needs more info, workbench-launch
