### ISSUE TITLE
Format confused when html file has style attribute.

### ISSUE THREAD

**Issue by hstarorg** [Microsoft/vscode#17637] opened 2016-12-21 03:22 UTC
- VSCode Version: 1.8.1
- OS Version: Win10

Steps to Reproduce:

1.  Create a new html file
2.  Enter some tags, and add style attribute in a tag.
3.  Ctrl + Alt + F(Format) Will confused.

**Comment by aeschli** [comment] 2016-12-29 03:33
duplicate of #17849

**Closed** 2016-12-29 03:34 UTC
Labels: html
