### ISSUE TITLE
Asking for git username and password unrelated to project

### ISSUE THREAD

**Issue by thomaslima** [microsoft/vscode#132176] opened 2021-09-02 23:20 UTC
Issue Type: <b>Bug</b>

I don't know how to reproduce it, but I have an open project with a git ssh remote (version control functionality works fine), but from time to time (about 5 minutes) a popup input bar shows asking for a username and password for https://git.overleaf.com, which is completely unrelated to my current project. I am not sure what is causing that to happen (disabling extensions does not make it go away). Any ideas? Inputting fake credentials doesn't show me any error. I looked at Git logs and all other log tabs but nothing related showed. I don't know where to search for logs related to this.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 5|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id a3d12f9d-481e-4f94-87b6-b630fe107e3e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
spellright|ban|3.0.60
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.18
gitlens|eam|11.6.0
matlab|Gim|2.0.1
latex-workshop|Jam|8.20.2
restructuredtext|lex|162.0.0
rainbow-csv|mec|1.9.1
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
material-icon-theme|PKi|4.10.0
polacode|pnp|0.3.4
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn420:30356812
pythonvspyt187cf:30361754
pydsgst2:30361792
vscus224:30358039

```

</details>

**Comment by thomaslima** [comment] 2021-09-02 23:31
This shows up out of nowhere: <img width="723" alt="image" src="https://user-images.githubusercontent.com/1088659/131928767-ff8f5998-1550-4ded-a4d6-8565583bb9e7.png">

**Comment by TylerLeonhardt** [comment] 2021-09-03 22:34
It looks like overleaf is a LaTeX thing so maybe start with disabling all your LaTeX-related extensions and try to reproduce this.

**Comment by thomaslima** [comment] 2021-09-03 22:40
Thank you for your comment. I thought of that and tried disabling all extensions before posting this bug, as I mentioned. I don't know where it's picking up from. I do have git remotes outside of this project pointing to overleaf. In my imagination the only way vscode could get that url is either by surveying other folders outside my project (why would it do that) or look at my osxkeychain to try to see which git credentials are stored there (why would it do that?).

What would help is if there was a way to see what is causing vscode to ask for this git credential. Maybe a log viewer or something.

**Comment by nilshartmann** [comment] 2021-10-01 16:23
I have the exact same problem (macOS 11.5.2, vscode 1.60.2).

My folder structure looks like this:

```
develop/
  a/.git/config contains a remote with https://git...
  b/projects/p1/.git/config
  b/projects/p1/subfolder1/  Opening VS Code here: no problems
  b/projects/p1/subfolder2/ Opening VS Code here: requests for credentials from origin in develop/a
```

If I remove folder `a` from `develop` or remove the `remote` from `.git/config` the problem doesn't occur any longer. 

Otherwise the dialog pops up around every 15 minutes.

**Comment by thomaslima** [comment] 2021-10-01 17:15
@nilshartmann Interesting. It seems one of my two hypotheses was correct then. VS Code was accessing files from outside the project. I don't think it should do that. It's weird that it behaved fine in your subfolder1. There must be a bug in the git repo discovery algorithm.

**Comment by thomaslima** [comment] 2022-03-31 03:03
It is no longer an issue for me. How about you @nilshartmann ?

**Comment by lszomoru** [comment] 2022-12-12 19:59
@thomaslima, @nilshartmann, apologies for not getting back to you on this until now. Based on your comments it seems to me that you are unable to reproduce the problem any more. I will go ahead and close this issue but please feel free to reopen it in case you are able to reproduce the issue again. Thank you!

**Closed by lszomoru** 2022-12-12 19:59 UTC
Labels: bug, git
