### ISSUE TITLE
Crash after opening multiple 600Mb files. 

### ISSUE THREAD

**Issue by redknightlois** [microsoft/vscode#51625] opened 2018-06-11 16:56 UTC
- VSCode Version: 1.23.1
- OS Version: Windows

Steps to Reproduce:

1. Open multiple 500+ Mb files simultaneously until it crashes.

**Comment by rebornix** [comment] 2018-06-11 23:31
@redknightlois Are you using VSCode 32bit or 64 bit? It can be possible that it crashes as it exceeds the memory limit of Chromium, can you try to run VSCode with a higher memory limit, for example, `Code.cmd --max-memory=4096` to see if it mitigates the issue.

**Comment by redknightlois** [comment] 2018-06-15 15:16
Mhh after the update to 1.24.0 I cannot even open a single one: ```Unable to open 'adhoc-2018.csv': Invalid string length.```

**Comment by ConstantineK** [comment] 2018-09-25 20:48
I can reproduce this issue with single files with what I assume are weird line breaks (large, but at the 380MB mark) - thought I would mention that Wordpad has no issue opening them, which blew my mind.

**Comment by VariableDeclared** [comment] 2019-01-03 12:49
Similar issue encountered here with vscode, "invalid string length" when opening one-line json file of 43~MB size.

Seems to be common across text editors, though, I had to resort to writing a python program to manipulate in chunks.

**Comment by bpasero** [comment] 2019-01-25 16:23
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2019-02-01 09:09
@chrmarti you should ping @rebornix

**Comment by octref** [comment] 2019-02-01 20:16
I can verify opening 2nd 500MB csv file freeze VS Code on my 16GB mem 2015 RMBP both in stable and insiders.

Don't think Electron 3 alone fixes this.

**Comment by rebornix** [comment] 2019-10-23 22:46
Closing it now as we have updated Electron from 3 to 6 with increased string len limit and better string mem management from v8. Large file can crash the renderer process when it has many lines or tons of non ASCII characters but if you think the file is normal and it crashes vs code for other reasons, feel free to open new issues.

**Closed by rebornix** 2019-10-23 22:46 UTC
Labels: bug, editor-textbuffer, freeze-slow-crash
