### ISSUE TITLE
Terminal environment no longer resolves `yarn`

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#123283] opened 2021-05-07 13:10 UTC
Issue Type: <b>Bug</b>

I have a `npm` task that executes `run foo` (with `yarn` as that is set as the package manager in the project). This works as expected in stable, in this Insiders build, I receive the message `zsh:1: command not found: yarn` instead.

I'm not sure what is missing now, but `~/.yarn/bin` is not part of my `PATH`, as it should be. This is usually set by my `~/.zshrc`.

Replacing the `npm` task with a `shell` task and using an absolute path for `yarn` instead, works around the problem.

VS Code version: Code - Insiders 1.57.0-insider (6bee0f2f3fea9df1ad45344f09b2a139c93b384f, 2021-05-07T08:43:06.427Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (43.32GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/tmp/mdtest --remote=wsl+Ubuntu --crash-reporter-id 506ed10e-ef8f-4fd6-a34b-7e0bd84c1bda|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (42.77GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.16
terraform|has|2.10.2
vscode-esformatter|how|1.6.0
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.819764235
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.31
vscode-yaml|red|0.18.0

(1 theme extensions excluded)

</details>

**Comment by meganrogge** [comment] 2021-05-07 18:08
Duplicate of #123072

**Closed** 2021-05-07 18:08 UTC
Labels: *duplicate
