### ISSUE TITLE
Opening a walkthrough when another walkthrough is open should reuse the same tab

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#144124] opened 2022-02-28 21:22 UTC
It seems odd to me that opening a walkthrough while another one is opened, opens another tab. I had expected it to replace the current one.

This leads to an undesirable case if one walkthrough has a link/step that leads to another walkthrough.

/cc @JacksonKearl  @digitarald

**Comment by JacksonKearl** [comment] 2022-02-28 21:41
It's by design that more than one can be open at the same time, though I could theoretically see having it replace if the second was opened via a link in the first. How are you opening it?

**Comment by eamodio** [comment] 2022-02-28 21:43
I have a step that has a button in the description to open another walkthrough.

**Comment by JacksonKearl** [comment] 2022-04-18 19:21
Duplicate of #129735

**Closed** 2022-04-18 19:22 UTC
Labels: feature-request, getting-started
