### ISSUE TITLE
get the error tips  by ...state

### ISSUE THREAD

**Issue by l3ve** [Microsoft/vscode#4064] opened 2016-03-12 10:04 UTC
```
return {
            …state,
            msg: action.value
            };
```
my jsconfig.js:
```
{
    "compilerOptions": {
        "target": “ES7”,
        "module": “es6”,
        "experimentalDecorators": true
    }
}
```
anything else i forget to set?

**Comment by egamma** [comment] 2016-03-12 16:33
Duplicate of #3804.

**Closed by egamma** 2016-03-12 16:33 UTC
