### ISSUE TITLE
Latest update breaks cursorEnd and cursorHome shortcuts

### ISSUE THREAD

**Issue by sheljohn** [Microsoft/vscode#33610] opened 2017-08-31 17:47 UTC
- VSCode Version: 1.15.1 (commit 41abd21afdf7424c89319ee7cb0445cc6f376959)
- OS Version: macOS Sierra (10.12.6)

Steps to Reproduce:

1. Type several lines of text, eg:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
2. Place cursor randomly inside that text
3. Try to select until the end/beginning of the line, respectively using <kbd>⌘</kbd><kbd>&#x21E7;</kbd><kbd>&larr;</kbd> and <kbd>⌘</kbd><kbd>&#x21E7;</kbd><kbd>&rarr;</kbd>

In my case, no selection happens. And trying to edit the keyboard shortcut for `cursorEnd` does not seem to respond to the combination <kbd>⌘</kbd><kbd>&rarr;</kbd> at all (same for `cursorEndSelect`, `cursorHome` etc).

Reproduces without extensions: Yes

**Comment by sheljohn** [comment] 2017-08-31 17:48
Umm, I don't think this has anything to do with brackets, `bot`.

**Comment by alexandrudima** [comment] 2017-09-01 08:46
@sheljohn I cannot reproduce. On a stock installation of VS Code, without any extensions (which can edit keybindings) `cmd+shift+left` and `cmd+shift+right` work as expected.

Can you please try the following:
### Run without extensions (which can edit keybindings)
* close all instances of vscode
* run vscode with `code --disable-extensions` (alternatively you can disable all the extensions one by one in the UI and restart)
* does the issue reproduce ?
### Remove all your keyboard customizations
* open the keybindings editor `cmd+k cmd+s`
* open `keybindings.json`
* comment out all of your rules, except for the leading `[` and trailing `]`.
### Finally, do we even receive these keybindings from the OS
* if the above do not help whatsoever, it is possible that some software or the OS itself is *eating up* those key combinations
* do you have other software on your machine where these key combinations work as desired / are received ?
* the easiest to find out if we receive these key combinations is:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
### Would the Chrome browser receive these keybindings
* if none of the above helps, you can easily find out if for example, your browser receives these key combinations.
* open the page at https://jsfiddle.net/v1gz5c5m/1/ and check if the key combination `cmd+shift+left` is received.

**Comment by sheljohn** [comment] 2017-09-01 11:19
Sorry, none of these steps worked for me :( 

It seems that the browser does not receive the combination `cmd+shift+left` either. 
However, this combination works fine with Firefox! This is very odd.
 
It also works fine with TextEdit (the basic text editor on OSX), so the combination itself seems to be emitted, it just doesn't get to certain applications apparently.

Could this be an issue with extended attributes on OSX perhaps (ie some permission that would need to be granted by the OS to forward certain key combination, although this seems very unlikely to me)? Otherwise, what do Chrome and VScode have in common?

**Comment by alexandrudima** [comment] 2017-09-01 13:31
`VSCode` is built on top of `Electron`, which is built by "stitching" together `node.js` and `Chromium`. `Chrome` is built on `Chromium`.

If there is an issue in `Chromium`, given we are updating quickly, the issue will surface in both `Chrome` and `VSCode`.

So that's why I believe this might be an issue in Chromium. Perhaps you can let them know of this issue at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by sheljohn** [comment] 2017-09-12 14:37
@chrmarti This is still an issue with the latest release: 1.16.0 (commit 787b31c0474e6165390b5a5989c9619e3e16f953)

@alexandrudima The issue has been [submitted to Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=764334), let's see what happens

**Comment by alexandrudima** [comment] 2017-09-22 10:41
Closing as the upstream issue is marked as wont-fix.

**Closed by alexandrudima** 2017-09-22 10:41 UTC
Labels: editor, editor-brackets, needs more info
