### ISSUE TITLE
cant see text in search window at file

### ISSUE THREAD

**Issue by Nau077** [microsoft/vscode#126978] opened 2021-06-23 09:20 UTC
Issue Type: <b>Feature Request</b>

Since today cant see text inside search window when search at accurate file some text. When click outside search-window, text is not hidden

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:15:45.422Z)
OS version: Linux x64 5.4.0-74-generic snap
Restricted Mode: No

**Comment by IllusionMH** [comment] 2021-06-23 09:25
/duplicate of #126896

Already fixed in latest Insiders build.

**Closed** 2021-06-23 09:26 UTC
Labels: *duplicate
