### ISSUE TITLE
Semantic Highlighting is not tokenizing in untitled Javascript file

### ISSUE THREAD

**Issue by romellem** [microsoft/vscode#121337] opened 2021-04-14 23:23 UTC
- VS Code Version: 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d) x64
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open new file, select `Javascript` as the language. Enter some code that should trigger Semantic Highlighting.
2. Run `Developer: Inspect editor tokens and scopes` from the Command Palette.
3. Observe that the (example) token is not being parsed as any _semantic token type_ and instead is only parsed within a _textmate scope._

I've also reinstalled VSCode and disabled all extensions, and still I can't get VSCode to tokenize some text to its semantic token.

### Working Example
<img width="400" alt="working" src="https://user-images.githubusercontent.com/8504000/114792608-4c6aa700-9d4e-11eb-8cef-6a6f5d132fcc.png">

### Problem Example
<img width="718" alt="problem" src="https://user-images.githubusercontent.com/8504000/114792651-5be9f000-9d4e-11eb-99c3-37c47d22fe71.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2021-04-14 23:33
Have you disabled semantic highlighting? Check the `editor.semanticHighlighting.enabled` setting

**Comment by mjbvz** [comment] 2021-04-14 23:33
Also please check if this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by romellem** [comment] 2021-04-14 23:43
Yes, changing `editor.semanticHighlighting.enabled` to `true` or `false`, the token still isn't being parsed semantically (verified by the `Developer: Inspect editor tokens and scopes` command).

I just downloaded the Insiders version you just linked:

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0
```

I am still seeing the issue unfortunately:

<img width="1136" alt="insiders-also-not-working" src="https://user-images.githubusercontent.com/8504000/114793906-07943f80-9d51-11eb-930b-b28e956d1a2d.png">

I am expecting that `props` should have a _semantic token type_ of `parameter` but instead (as you can see in the screenshot) it is only parsing it as a _textmate token_.

**Comment by mjbvz** [comment] 2021-04-15 00:49
Thanks for testing

@aeschli Looks like this only happens in unsaved Javascript files. The upstream cause is https://github.com/microsoft/TypeScript/issues/43350 but I thought our plugin should still be enabled for JS file

**Comment by romellem** [comment] 2021-04-15 00:55
@mjbvz you are right! Saving the file does make the semantic token recognized.

<img src="https://user-images.githubusercontent.com/8504000/114798534-2dbedd00-9d5b-11eb-81ee-4d8a60ead413.png" width="900" alt="insiders-working-after-saving-file">

**Comment by aeschli** [comment] 2021-04-15 11:58
My guess is that this is related to the way I detect JavaScript files:
https://github.com/aeschli/typescript-vscode-sh-plugin/blob/69b8e117ee4232192ac8e70769e97d854284076b/src/index.ts#L31

I didn't find a way to get the SciptKind of a file.
The Host would have such an API, but then i didn't find how to get the host. @mjbvz Any tricks?

**Comment by mjbvz** [comment] 2021-04-17 01:15
You'd have to ask the TypeScript team about that. I'm fine with just waiting for microsoft/TypeScript#43350 to be fixed, but we need to make sure it makes it into TS 4.3

**Comment by mjbvz** [comment] 2021-05-07 21:50
Closing since https://github.com/microsoft/TypeScript/issues/43350 should now be fixed

**Closed by mjbvz** 2021-05-07 21:50 UTC
Labels: bug, javascript, upstream
