### ISSUE TITLE
On macOS the behavior for Cmd+E is incorrect

### ISSUE THREAD

**Issue by vincentisambart** [microsoft/vscode#44093] opened 2018-02-21 08:26 UTC
### Issue Type
Bug

### Description

On most macOS applications (for example TextEdit or Xcode), Cmd+E sets the find clipboard to what is selected *without changing the focus* (in fact it doesn't even make the search bar appear).
VS Code makes the search bar appear and set the focus to it.

Having the search bar appearing is minor, but if you are used to the standard behavior, not having the editor keep the focus on the editor is pretty disturbing.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.81GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron ./te|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.15.0
Ruby|reb|0.16.0
rust|rus|0.3.2

</details>
Reproduces without extensions

**Comment by lionello** [comment] 2018-11-15 01:32
Relevant line in the code:
https://github.com/Microsoft/vscode/blob/17454d4e88886404af130639b979498b227a9167/src/vs/editor/contrib/find/findController.ts#L474

Should change to:
```
				shouldFocus: FindStartFocusAction.NoFocusChange,
```

**Comment by lionello** [comment] 2018-11-15 01:34
@vincentisambart Could you edit the title of this issue to emphasize that it's related to the focus? The issue is also unrelated to macOS. Perhaps something like "Cmd+E (action.findWithSelection) should not focus the find widget".

**Comment by timestretch** [comment] 2019-09-12 01:43
Are there any plans on merging a fix for this issue? Addressing this issue would go a long way to making Cmd-E in vscode work the way long time Mac users expect.

**Comment by nathany** [comment] 2019-10-22 23:44
This should also appear in the menu. Here are some examples -- also to portray how prevalent this feature is, and implemented in a common way in seemingly everything but VS Code.

Xcode: Find > Use Selection for Find ⌘E
Sublime Text: Find > Use Selection for Find ⌘E
TextMate: Edit > Find > Use Selection for Find ⌘E
BBEdit: Search > Use Selection for Find ⌘E
Atom: appears to be missing this altogether
Day One: Edit > Find > Use Selection for Find
Apple Books: Edit > Find > Use Selection for Find ⌘E
(you get the idea)

Note that ⇧⌘E should be Use Selection for Replace to match other Mac apps.

(as per my post to #69498)

**Closed** 2019-10-25 00:56 UTC
Labels: editor-find, under-discussion, ux

**Comment by rebornix** [comment] 2019-10-25 00:57
Thanks all for your contribution on this topic. Considering this command is only registered with keybindings CMD+E on macOS, I think it makes sense to align it with all other applications on macOS. CMD+E won't focus on the find widget from tomorrow's Insiders.

**Comment by vincentisambart** [comment] 2019-11-08 00:04
The fix is included in 1.40.0 🎉
Thanks @lionello @rebornix!

**Comment by briankendall** [comment] 2019-11-08 03:25
Thank you! This one little fix will drastically improve my experience using VS Code.
