### ISSUE TITLE
Adding accented character with keyboard popup should not keep the original un-accented character (macOS)

### ISSUE THREAD

**Issue by StephenOTT** [Microsoft/vscode#32339] opened 2017-08-11 17:54 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
path-intellisense|chr|1.4.2
FreeMarker|dco|0.0.9
rest-client|hum|0.15.1
debugger-for-chrome|msj|3.1.7
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
guides|spy|0.8.4

---

Steps to Reproduce:

1. type
1. holder letter down on keyboard
1. select accented character

Both characters will remain.

![screen shot 2017-08-11 at 1 48 18 pm](https://user-images.githubusercontent.com/1994838/29225490-7e130768-7e9c-11e7-8f66-506d824efdcc.png)
![screen shot 2017-08-11 at 1 48 39 pm](https://user-images.githubusercontent.com/1994838/29225494-83fe7b12-7e9c-11e7-9428-81d7983bdc61.png)
![screen shot 2017-08-11 at 1 48 48 pm](https://user-images.githubusercontent.com/1994838/29225498-87f2b4c2-7e9c-11e7-9392-132325a70e9e.png)

**Comment by rebornix** [comment] 2017-08-11 18:34
@StephenOTT does this only happen after you upgrade to the latest version?

**Comment by StephenOTT** [comment] 2017-08-11 18:41
@rebornix yes i believe so.  i noticed it today, and ~pretty sure~ that i did not have the problem before.

**Comment by StephenOTT** [comment] 2017-08-11 18:41
Its a larger problem related to electron.  Slack, Atom, etc, have had the same issues.

**Comment by StephenOTT** [comment] 2017-08-24 14:26
@rebornix this problem has been fixed upstream:
https://github.com/electron/libchromiumcontent/pull/293

**Comment by mjbvz** [comment] 2017-09-27 22:23
Duplicate of #32985 Should be fixed in VS Code 1.17

**Closed by mjbvz** 2017-09-27 22:23 UTC
Labels: bug, duplicate, editor, editor-core, editor-ime, needs more info
