### ISSUE TITLE
Errors in webview view sample webview script

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107732] opened 2020-09-29 17:41 UTC
Testing #107626

I know these are harmless but it would be good for a sample to show people how to set this up without errors

![image](https://user-images.githubusercontent.com/323878/94595421-ac30b300-023f-11eb-8942-c3eee82636b1.png)

**Comment by usernamehw** [comment] 2020-09-29 18:04
Similar to https://github.com/microsoft/vscode-extension-samples/issues/342

Looks like no one is assigning issues in that repository.

**Comment by mjbvz** [comment] 2020-09-29 18:50
Duplicate of #96221

**Closed by mjbvz** 2020-09-29 18:50 UTC

**Comment by roblourens** [comment] 2020-09-29 22:39
Thanks @usernamehw we will clean that up next month
