### ISSUE TITLE
[wsl] On WSL2 I get a crazy amount of open processes from VSCode with `remote close` error

### ISSUE THREAD

**Issue by QAnders** [microsoft/vscode#199588] opened 2023-11-29 19:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: Windows 11 22H2 22621.2715, WSL2 Ubuntu 22-04

Steps to Reproduce:

1. Start WSL interaction with VSCode, code for a bit

After running VSCode and coding for a while with two or three open VSCode editors and the same amount of tabs open for WSL2 I end up with a ton of processes in WSL as:
```
.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/node -e const net = require('net'); process.stdin.pause(); const client = net.createConnection({ host: '127.0.0.1', port: 37993 }, () => { client.pipe(process.stdout); process.stdin.pipe(client); }); client.on('close', function (hadError) { console.error(hadError ? 'Remote close with error' : 'Remote close'); process.exit(hadError ? 1 : 0); }); client.on('error', function (err) { process.stderr.write(err && (err.stack || err.message) || String(err)); });
```

Eventually WSL runs out of memory due to the amount of processes and I have to restart my laptop.

**Comment by aeschli** [comment] 2023-12-05 13:35
I've see that too, but don't know how to reproduce.

**Comment by aeschli** [comment] 2024-12-11 15:08
Closing due to lack of reproducible steps

**Closed by aeschli** 2024-12-11 15:08 UTC
Labels: bug, WSL
