### ISSUE TITLE
VSCode in WSL Fails to Open New Window for Folders with Case-Sensitive Names

### ISSUE THREAD

**Issue by eiriksanderfjeld** [microsoft/vscode#221690] opened 2024-07-15 06:59 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open a terminal in WSL.
2. Navigate to the folder `/home/username/code/abcde`.
3. Run the command `code .` to open the folder in VSCode. VSCode opens the folder as expected in a new window.
4. In the same or a new terminal, navigate to a different folder at the path `/home/username/code/ABCDE`, where the folder name differs only in case from the first folder.
5. Run the command `code .` to open this second folder in VSCode.

## Expected Behavior
VSCode should open a new window for the second folder (`/home/username/code/ABCDE`), recognizing it as a different directory due to the case sensitivity of Linux file systems.

## Actual Behavior
VSCode brings focus to the already open window of the first folder (`/home/username/code/abcde`) instead of opening a new window for the second folder. This also happens if i open the folder from inside VSCode. 

## Environment
- VSCode Version: 1.91.1
- OS: Windows Subsystem for Linux (WSL) Ubuntu 22.04 (Linux VU-IMC-7245333 5.15.153.1-microsoft-standard-WSL2)

## Additional Information
- This issue seems to be related to how VSCode handles case sensitivity in folder names on Linux file systems.
- No relevant output in the Developer Console (Help > Toggle Developer Tools) was observed.

## Suggested Labels
- bug
- linux
- wsl
- file-system

**Comment by aeschli** [comment] 2024-07-15 13:34
It's a known issue that we have with all types of remote windows (WSL, SSH, ...). On open, we don't know yet what OS the remote window has and treat the filesystem as case insensitive.
Duplicate of https://github.com/microsoft/vscode/issues/123421

**Closed by aeschli** 2024-07-15 13:34 UTC
