### ISSUE TITLE
Hyperlink's starts blinking

### ISSUE THREAD

**Issue by MASDias** [microsoft/vscode#82364] opened 2019-10-11 14:47 UTC
Issue Type: <b>Bug</b>

As soon you place the text cursor on a hyperlink, put it somewhere else and scroll in and out the the previous text (where) cursor was placed, the underline text for the hyperlink will blink at the same velocity of the cursor.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.14393

Extensions: none

**Comment by usernamehw** [comment] 2019-10-12 07:41
Possible duplicate of #76642

**Comment by octref** [comment] 2019-10-17 18:39
Duplicate of #76642.

**Closed by octref** 2019-10-17 18:39 UTC
Labels: new release
