### ISSUE TITLE
Turn off fading effect

### ISSUE THREAD

**Issue by computHome** [Microsoft/vscode#54708] opened 2018-07-20 06:38 UTC
there is some fading effect in scrollbar or overview bar that may be cool but from a dev point of view, you always want to know the scrollbar position and how much a file is showing in the editor view immediately. is there an option to turn those off?

**Comment by alexandrudima** [comment] 2018-07-20 09:39
Duplicate of #35454

**Closed by alexandrudima** 2018-07-20 09:39 UTC

**Comment by computHome** [comment] 2018-07-20 14:01
The below setting works for scrollbar, but is there a option for overview bar since the gray area indication is shown only if mouse is over the overview area. anyway it feels good right now, thanks

"editor.scrollbar.vertical": "visible",
"editor.scrollbar.horizontal": "visible",

**Comment by ryanhilton** [comment] 2018-09-02 23:18
Thanks @computHome, this works great for me, it's so helpful to be able to see the scrollbar!

I had a file open, and since I was scrolled down, I thought I had a bunch of missing code, so I went in search of how to prevent hiding of the scroll bars, and this worked great (I also lightened up the styling of them using scrollbarSlider.background etc.) since the theme I am using made them a little too dark.
