### ISSUE TITLE
1.2.1 OSX El Cap: Reopen loop after copying to Applications folder

### ISSUE THREAD

**Issue by jcollum** [Microsoft/vscode#8847] opened 2016-07-07 17:35 UTC
- VSCode Version: fe7f407b95b7f78405846188259504b34ef72761
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Download VSCode 
1. Decompress
1. Copy result to Applications folder

Result: App gets stuck in a loop: "This window has crashed: Close, Reopen". Selecting Reopen results in a loop. 

App runs fine if I don't copy to Applications folder.

**Comment by bpasero** [comment] 2016-07-08 08:34
@jcollum can you open the "Console" application and look for crash dumps under "User Diagnostic Reports"?

**Comment by jcollum** [comment] 2016-07-08 14:54
I can't recreate it now. I opened a folder yesterday when the app was in my ~/Downloads folder, that might be related. The app now opens and shows the last folder I opened. How do I wipe all the data that the app is storing on my machine? `$ rm -rf ~/.vscode` didn't do it.

**Comment by bpasero** [comment] 2016-07-08 15:04
@jcollum there is also `$HOME/Library/Application Support/Code/` but deleting that, you should backup the `User` folder inside and restore it later.

**Comment by bpasero** [comment] 2016-07-08 15:05
Closing assuming the issue is gone.

**Closed by bpasero** 2016-07-08 15:05 UTC
Labels: freeze-slow-crash, needs more info, not-reproducible

**Comment by jcollum** [comment] 2016-07-08 15:20
I don't think this should be closed yet. If the app is hitting a bug that is solved by opening a folder _before_ placing the app in the Applications folder that is a legit bug. 

> there is also $HOME/Library/Application Support/Code/

That appears to have much much more thank VSCode data. I don't want to delete it, even with a backup. Please point me to the VSCode folder inside that directory.

**Comment by bpasero** [comment] 2016-07-08 15:39
Should be all code related, here is the contents for me:

![image](https://cloud.githubusercontent.com/assets/900690/16692844/e0f07982-4532-11e6-88de-914999cef885.png

I would keep it open if we have steps to reproduce, that is the absolute minimum.

**Comment by jcollum** [comment] 2016-07-08 15:49
I see, the folder called Code is for VSCode. Don't you think that's  a bit confusing? 

Tried `$ rm -rf "$HOME/Library/Application Support/Code/"; rm -rf ~/.vscode` and re-copying the app. Couldn't reproduce. I guess keep it closed. It is strange, this bug happened to me 4 times yesterday, but none today. It went away after I opened a folder with VSCode.
