### ISSUE TITLE
Separate editor syntax theme from workspace/window theme

### ISSUE THREAD

**Issue by angelhdzmultimedia** [microsoft/vscode#210211] opened 2024-04-12 06:37 UTC
Hello! 
This time I want to suggest (or ask if it's already possible) to separate the editor syntax and workspace/window themes, for example I want the One Dark Darker for the workspace/window, and Dark Vue Theme for the editor syntax.

Dark Vue Theme:
![image](https://github.com/microsoft/vscode/assets/10191085/63d90d81-cfdd-4b82-a290-f95db290acce)

One Dark Darker:
![image](https://github.com/microsoft/vscode/assets/10191085/088811fb-27e3-4432-8c65-5a97d27c06a5)

Desired Result:
![image](https://github.com/microsoft/vscode/assets/10191085/b56fecec-0fbf-4369-ac58-69da8ec50072)

**Comment by aeschli** [comment] 2024-04-12 08:38
Duplicate of #25986

We currently have no plans to separate workbench themes and syntax themes in the UI.

**Closed by aeschli** 2024-04-12 08:38 UTC
