### ISSUE TITLE
Code folding Bug at Powershell

### ISSUE THREAD

**Issue by ChrisRudi** [Microsoft/vscode#36829] opened 2017-10-24 15:08 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-PSStackoverflow|Dou|0.0.2
VBScript|lug|0.0.2
mssql|ms-|1.2.0
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1.Write a PS1 script
2.Fold the code
3.Expand the last Function -> The next Function is there

It seems that this happens only if there are also Functions inside. {Windows.Forms Functions}
This Bug came in in Version 1.17
 

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-10-25 14:44
Please add a code snippet that shows the problem.

**Comment by ChrisRudi** [comment] 2017-10-25 15:20
Function Get-EditForm ($Breite, $Höhe, $FormBreite, $FormHöhe, [int]$Vorderkante , [int]$Oberkante, [string]$Lable) {
    #Erzeugt das Form für den Edit Dialog -Buchungen editieren
    $EditForm = New-Object System.Windows.Forms.Form
    $EditForm.Icon = "$Base\Source\IconW.ico"
    $EditForm.MinimizeBox = $False
    $EditForm.MaximizeBox = $False
    $EditForm.BackColor = "Black"

    $EditForm.Text = "Arbeitszeitaufzeichnung Projektbezogen EDIT"
    $EditForm.Size = New-Object System.Drawing.Size($FormBreite, $FormHöhe)
    $EditForm.ForeColor = "White"
    $EditForm.KeyPreview = $True
    $EditForm.MaximumSize = $EditForm.Size
    $EditForm.MinimumSize = $EditForm.Size
    $Font = New-Object System.Drawing.Font("Times New Roman", 12, [System.Drawing.FontStyle]::Regular)
    $EditForm.Font = $Font

    $Label = New-Object System.Windows.Forms.Label
    $Label.Text = $Lable
    $Label.Location = "$Vorderkante,235"
    $Label.Text = "Ändern:   1.Datum  2.Projekt  3.Zeit"
    $Label.Height = 25
    $Label.Width = 400  
    $EditForm.Controls.Add($Label)

    
    #begin to draw Edit box

    #region assembly loading - we load required assemblies not present in PowerShell
    [reflection.assembly]::Load("System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089") | Out-Null
    [reflection.assembly]::Load("System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
    [reflection.assembly]::Load("mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089") | Out-Null
    [reflection.assembly]::Load("System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089") | Out-Null
    #end region assembly loading
    [System.Windows.Forms.Application]::EnableVisualStyles();
    [System.Windows.Forms.Application]::DoEvents();

    # StartCalendarLabel
    $StartCalendarLabel = New-Object System.Windows.Forms.Label
    $StartCalendarLabel.Text = "Start:"
    $StartCalendarLabel.Location = "250, 15"
    $StartCalendarLabel.Height = 22
    $StartCalendarLabel.Width = 55
    $EditForm.Controls.Add($StartCalendarLabel)

    # StartCalendar
    $StartCalendar = New-Object Windows.Forms.MonthCalendar
    $StartCalendar.Location = "$Vorderkante, $Oberkante"
    $Locentry = Select-query -QueryType ReadPerUser -Worker $Worker 
    $xa = $Locentry.starttime
    $StartCalendar.BoldedDates = $xa
    
    $combo1txt = "Anderes Datum auswählen"
    $StartCalendar.MaxSelectionCount = 1
    [DateTime[]]$xc = $Locentry.starttime | Sort-Object {[DateTime]$_} 
    $Rangestop = $xc | Select-Object -Last 1
    $Rangestart = $xc | Select-Object -First 1
    $StartCalendar.MaxDate = $Rangestop
    $StartCalendar.MinDate = $Rangestart
    
    $EditForm.Controls.Add($StartCalendar)

    $StartCalendar.add_DateChanged(
        {
            $global:ADDSelectedDay = $StartCalendar.SelectionRange.Start
            $startdate = $StartCalendar.SelectionRange.Start
            $enddate = ($startdate).AddDays(1).AddSeconds(-1) #Zeitspanne um Projekte dieses einen Tages einzulesen
            [system.array]$global:Locentry = New-Object System.Collections.ArrayList
            $global:Locentry = Select-query -QueryType ReadPerUserTimerange -Worker $Worker -startdate $startdate -enddate $enddate

            if ($global:Locentry.count -eq 0) {
                $addlist = "Anderes Datum auswählen"
                $addText = $addlist
                $comboboxEDIT.Text = $addText
                $EditButton.Enabled = $False
                $comboboxEDIT.Items.Clear();
                $starttimePicker.CustomFormat = " ";
                $stoptimePicker.CustomFormat = " ";
                $DeleteButton.Enabled = $False
        
            }
            else {
                $addlist = $global:Locentry.task 
                $addText = "Task hier auswählen"; $comboboxEDIT.Text = $addText
                $comboboxEDIT.Items.Clear();
                $comboboxEDIT.Items.addrange($addlist)
                $starttimePicker.CustomFormat = " ";
                $stoptimePicker.CustomFormat = " ";
            } })

    $starttimePicker = New-Object System.Windows.Forms.DateTimePicker
    $starttimePicker.Location = "310, $Oberkante"
    $starttimePicker.Width = "130"
    $starttimePicker.Format = "custom"
    $starttimePicker.CustomFormat = " ";
    $starttimePicker.ShowUpDown = $TRUE
    $starttimePicker.add_ValueChanged( {
            $DeleteButton.Enabled = $False
            $EditButton.Enabled = $True
            $starttime = $starttimePicker.Value
            $global:selected_Soll[0].starttime = $starttime
        })
    $EditForm.Controls.Add($starttimePicker) 
    
    # stoptimePicker Label
    $stoptimePickerLabel = New-Object System.Windows.Forms.Label
    $stoptimePickerLabel.Text = "Stop:"
    $stoptimePickerLabel.Location = "250, 190"
    $stoptimePickerLabel.Height = 22
    $stoptimePickerLabel.Width = 55
    $EditForm.Controls.Add($stoptimePickerLabel)

    # stoptimePicker
    $stoptimePicker = New-Object System.Windows.Forms.DateTimePicker
    $stoptimePicker.Location = "310, 190"
    $stoptimePicker.Width = "130"
    $stoptimePicker.Format = [windows.forms.datetimepickerFormat]::custom
    $stoptimePicker.CustomFormat = " ";
    $stoptimePicker.ShowUpDown = $TRUE
    $stoptimePicker.add_ValueChanged( {
            $DeleteButton.Enabled = $False
            $EditButton.Enabled = $True
            $stoptime = $stoptimePicker.Value
            $global:selected_Soll[0].stoptime = $stoptime
        })
    $EditForm.Controls.Add($stoptimePicker)

    
    #Combobox - Vorgegeben Liste
    $comboboxEDIT = New-Object System.Windows.Forms.combobox
    $comboboxEDIT.Location = New-Object System.Drawing.Size($Vorderkante, 270)
    $comboboxEDIT.Size = New-Object System.Drawing.Size(420, 20)
    $comboboxEDIT.Height = 50
    $comboboxEDIT.Name = 'Combo_Box_UserName'
    $comboboxEDIT.Text = $combo1txt
    $comboboxEDIT.DropDownStyle = "DropDownList"
    $comboboxEDIT.add_SelectedIndexChanged( {
            [int]$x = $comboboxEDIT.SelectedIndex
            $guid = $global:Locentry[$x].guid
            [system.array]$global:selected_IST = New-Object System.Collections.ArrayList
            $global:selected_IST = Select-query -QueryType ReadWithguid -guid $guid | Sort-Object {[DateTime]$_.starttime} 
            $global:selected_SOLL = $global:selected_IST

            $starttimePicker.CustomFormat = "HH:mm:ss"
            $starttimePicker.Value = $global:selected_SOLL[0].starttime
            $stoptimePicker.CustomFormat = "HH:mm:ss"
            $stoptimePicker.Value = $global:selected_SOLL[0].stoptime
            $DeleteButton.Enabled = $True
            $EditButton.Enabled = $False

            $IST_ANzeige = ""
            $IST_ANzeige = "Bisheriger Eintrag: `r`n"
            $IST_ANzeige = $IST_ANzeige + [string]::Join(" | ", $global:selected_IST.task, $global:selected_IST.starttime)
            $IST_ANzeige = $IST_ANzeige + "`r`n"
            $global:IST_ANzeige = $IST_ANzeige + [string]::Join(" | ", $global:selected_IST.task, $global:selected_IST.stoptime)

        })
    $EditForm.Controls.Add($comboboxEDIT)
    


    $DeleteButton = New-Object System.Windows.Forms.Button
    $DeleteButton.Location = New-Object System.Drawing.Size(450, 270)
    $DeleteButton.Size = New-Object System.Drawing.Size(72, 30)
    $DeleteButton.Text = "Delete"
    $DeleteButton.BackColor = "Green"
    $DeleteButton.ForeColor = "White"
    $DeleteButton.DialogResult = "OK"
    $DeleteButton.Enabled = $False
    
    $DeleteButton.Add_Click( {
            $deletePreText = "Wollen Sie diesen Eintrag wirklich löschen ? `r`n"
            $wshell = New-Object -ComObject Wscript.Shell
            $ask = $wshell.Popup($deletePreText + $global:IST_ANzeige, 0, "Delete ?", 0x21)
            if ($ask -eq $true) {  Select-query -QueryType Deleteguid -guid $global:selected_IST[0].guid}
        })
    $EditForm.Controls.Add($DeleteButton)
    $EditForm.AcceptButton = $DeleteButton

    
    $EditButton = New-Object System.Windows.Forms.Button
    $EditButton.Location = New-Object System.Drawing.Size(450, 100)
    $EditButton.Size = New-Object System.Drawing.Size(72, 30)
    $EditButton.Text = "Edit"
    $EditButton.BackColor = "Green"
    $EditButton.ForeColor = "White"
    $EditButton.DialogResult = "OK"
    $EditButton.Enabled = $False
    $EditButton.Add_Click( {
            $editPreText = "Wollen Sie diesen Eintrag wirklich verändern ? `r`n"    
            $Soll_ANzeige = ""
            $Soll_ANzeige = " `r`nVeränderter Eintrag: `r`n"
            $Soll_ANzeige = $Soll_ANzeige + [string]::Join(" | ", $global:selected_Soll.task, $global:selected_Soll.starttime)
            $Soll_ANzeige = $Soll_ANzeige + "`r`n"
            $global:Soll_ANzeige = $Soll_ANzeige + [string]::Join(" | ", $global:selected_Soll.task, $global:selected_Soll.stoptime)

            $wshell = New-Object -ComObject Wscript.Shell
            $ask = $wshell.Popup($editPreText + $global:IST_ANzeige + $global:SOLL_ANzeige, 0, "Edit ?", 0x21)
            if ($ask -eq $true) { 
                $timerangetest = New-TimeSpan  $global:selected_Soll.starttime $global:selected_Soll.stoptime
                [int]$num = $timerangetest.TotalHours
                if ($num -ge 0 -and $num -le $MaxTotalHours) {
                    Select-query -QueryType Update -Worker $Worker -startdate $global:selected_Soll.starttime -enddate $global:selected_Soll.stoptime -guid $global:selected_IST.guid
                }
                else {
                    $wshell.Popup("Achtung die angegebenen Werte sind ausserhalb des Bereichs ! " + "`r`n" + "Der mögliche Bereich ist zwischen 0 und $MaxTotalHours Stunden." + "`r`n" + "Sie haben $num Stunden ausgewählt.", 0, "Edit ?", 0x10)
                }
            }})
    $EditForm.Controls.Add($EditButton)
    $EditForm.AcceptButton = $EditButton
    


    $EditForm.Location = New-Object System.Drawing.Point(($Breite - $FormBreite), ($Höhe - $FormHöhe - $TaskbarHöhe))
    $result = $EditForm.ShowDialog()
    if ($result -eq "Cancel") {exit}
    Return $result
}

Function Enter-Text { 
    s##############################
    #.SYNOPSIS
    #sdf
    #
    #.DESCRIPTION
    #Long description
    #
    #.EXAMPLE
    #An example
    #
    #.NOTES
    #General notes
    ##############################
}

**Comment by aeschli** [comment] 2017-10-30 20:04
@ChrisRudi Thanks for the sample code. What are the steps? I fold all, expand the last function (line 220, `Enter-Text`) by clicking on the `-`.
I don't see anything strange.

**Comment by ChrisRudi** [comment] 2017-11-01 13:17
The strange thing is:
If i fold all, only one Function is visible anymore. But there should be a second one.
![image](https://user-images.githubusercontent.com/32868570/32276387-4b3dbdde-bf0f-11e7-905d-04fca2d1a759.png)

**Comment by aeschli** [comment] 2017-11-01 16:35
@ChrisRudi I can't reproduce that with your example.
Remember, it's all about the indents, we are not language-aware on folding. So maybe your second function is indented?

**Comment by ChrisRudi** [comment] 2017-11-02 14:24
Found a workaround:
When i remove the line:
"#region assembly loading - we load required assemblies not present in PowerShell;"
Code falding  works perfect again.
scary or ?
![image](https://user-images.githubusercontent.com/32868570/32330860-b3227304-bfe1-11e7-953c-4f34b011dd51.png)

**Comment by pr-yemibedu** [comment] 2017-11-05 00:19
Hello,
 The **language-configuration.json** file is set to work with a `#region` `#endregion` pair (instead of `#end region`). Does that also work for your code?

**Comment by ChrisRudi** [comment] 2017-11-05 21:10
Thank's
Super support.
Regards
Chris

Ing. Christian Jud
Am Anger 9\1
8054 Seiersberg
Tel: +43 664 1389052
Mail: judchristian@gmail.com

**Comment by aeschli** [comment] 2017-11-07 15:54
Powershell uses `#region` and `#endregion` as folding markers (`#end region` is not valid).
So your comment happens to start with #region, that could result in a new fold region. But only if you have a #endregion somewhere.

If you think there is a bug here, please send a sample code that shows the problem. So far, looking at your examples all is as intended.

Closing. I'm happy to reopen if we have the sample code...

**Closed by aeschli** 2017-11-07 15:54 UTC
Labels: editor, editor-folding, needs more info
