### ISSUE TITLE
VSCode spawns multiple processes and slows down the whole system

### ISSUE THREAD

**Issue by svdHero** [Microsoft/vscode#42819] opened 2018-02-02 11:49 UTC
- VSCode Version:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Datum 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

- OS Version:
Windows 8.1

Steps to Reproduce:

1. Install VSCode
2. Open VSCode
3. Check Windows Task Manager

Does this issue occur when all extensions are disabled?: Yes

When Visual Studio Code is opened and idle, the whole system slows down extremely and I cannot work anymore. When checking the Windows Task Manager, I can see 7 VSCode processes which bring my CPU workload up to 99%, although VSCode is idle, has no folder opened and no extensions installed.

What's wrong here? I have successfully used VSCode in the past on other computers (both Windows and Linux) and didn't have said problems.

![visual_studio_code_performance](https://user-images.githubusercontent.com/24250824/35731818-7356299a-0817-11e8-824d-01771c1531df.png)

**Comment by bpasero** [comment] 2018-02-02 13:27
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by svdHero** [comment] 2018-02-02 14:07
Thank you bpasero for the link.

The command `code --status` has the output:
```
W:\Foo>code --status


Version:          Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
OS Version:       Windows_NT x64 6.3.9600)
CPUs:             Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3691)
Memory (System):  15.93GB (9.90GB free)
VM:               0%
Screen Reader:    no

CPU %   Mem MB  Process
   -1       66  code main
   -1       62     shared-process
   -1      170     window (Willkommen - Visual Studio Code)
   -1       49       extensionHost
   -1       10       "C:\Program Files\Microsoft VS Code\Code.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\Users\XXXXX\AppData\Local\Temp\VSCode Crashes" --v=1
   -1       27       terminal
   -1        5         "c:\Program Files\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-14024-1-1d39c2e39066894-64e64bfd4a4f5dac9fe4cb4a7cb7f3a7 0 1 80 24
   -1        2           C:\Windows\system32\cmd.exe
   -1        6           C:\Windows\system32\conhost.exe 0x4
   -1       49     gpu-process


W:\Foo>
```

The profiler for the running extensions has the output:
[CPU-20180202T135644.501Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1689578/CPU-20180202T135644.501Z.cpuprofile.txt)

Can I provide anything else that might help?

**Comment by bpasero** [comment] 2018-02-02 14:14
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2018-02-02 14:14
@dbaeumer fyi on code --status returning "-1" for CPU.

**Comment by svdHero** [comment] 2018-02-02 15:37
Like I wrote in my original post above: There are no extensions installed. I had also tried with with the explicit command line argument `--disable-extensions` which didn't bring any improvement.
Do you want me to produce the above outputs again with the `--disable-extensions`? I could do that.

**Comment by bpasero** [comment] 2018-02-02 15:45
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by svdHero** [comment] 2018-02-02 15:58
Yeah, I will try that on monday. Thanks for your help so far.

**Comment by bpasero** [comment] 2018-02-02 16:04
ok

**Comment by svdHero** [comment] 2018-02-05 08:09
Okay. I've tried now with

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Datum 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

and got:
´´´
C:\Users\Baeuerle>code --status


Version:          Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
OS Version:       Windows_NT x64 6.3.9600)
CPUs:             Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3691)
Memory (System):  15.93GB (10.81GB free)
VM:               0%
Screen Reader:    no
CPU %   Mem MB  Process
   -1       74  code main
   -1       71     shared-process
   -1       45     gpu-process
   -1      227     window (Willkommen - Visual Studio Code)
   -1       27       terminal
   -1        5         "c:\Program Files\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-2888-1-1d39e586019ed8e-8d2e1b4b693c4e942044f25c9693099d 0 1 203 22
   -1        2           C:\Windows\system32\cmd.exe
   -1        6           C:\Windows\system32\conhost.exe 0x4
   -1       49       extensionHost
   -1       10       "C:\Program Files\Microsoft VS Code\Code.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\Users\XXXXXXX\AppData
\Local\Temp\VSCode Crashes" --v=1
´´´

So far, the performance problems seem to have vanished. CPU workload is happily chilling around 10 %. I will continue to monitor the behaviour. Thanks for the link to the nightly build.

**Comment by dbaeumer** [comment] 2018-02-05 08:29
The -1 value is indeed strange especially since this value is computed using `($counter.CookedValue / $logicalProcessors)`  (e.g. a division). Need to thing a little how this can happen.

**Comment by bpasero** [comment] 2018-02-05 09:24
@svdHero but do you see the slowdown also with insiders?

**Comment by svdHero** [comment] 2018-02-05 14:08
Ah, sorry that I did not express myself correctly. What I meant above was: "With the nightly insider build the performance problems seem to have vanished".
Also my status output above is from the insiders run.

I will correct my comment above.

**Comment by svdHero** [comment] 2018-02-05 14:12
@dbaeumer Could the -1 thing be related to my corporate antivirus? Also, I think my company IT has been installing the meltdown/spectre updates from Microsoft. Could that screw up the status? Just guessing...

**Comment by dbaeumer** [comment] 2018-02-05 14:15
@svdHero thanks for the idea. I have meltdown/spectre installed as well and it works for me. I also think that Anitvirus shouldn't be a problem either but I will keep it in mind when investigating.

**Comment by bpasero** [comment] 2018-02-05 14:51
Closing as per https://github.com/Microsoft/vscode/issues/42819#issuecomment-363094505

**Closed by bpasero** 2018-02-05 14:51 UTC
Labels: needs more info
