### ISSUE TITLE
Multiple terminals to have tabs not just selected from dropdown

### ISSUE THREAD

**Issue by nhc** [microsoft/vscode#86748] opened 2019-12-11 14:09 UTC
I could not find this in feature requests. 

Instead of just accessing multiple terminal sessions from the drop down I would like to have the option to have them listed as tabs. 

They have the same feature in PHP Storm. Screenshot here 

<img width="814" alt="Screenshot 2019-12-11 at 14 08 36" src="https://user-images.githubusercontent.com/288772/70628280-c9988000-1c1f-11ea-8549-c97b11239210.png">

- Each new terminal spawns a new tab
- It must be possible to name the tabs

**Comment by gjsjohnmurray** [comment] 2019-12-11 14:21
/duplicate of #10546 which was the first result from my search for "terminal tabs"

**Closed** 2019-12-11 14:21 UTC
Labels: *duplicate, integrated-terminal
