### ISSUE TITLE
(?<=:).+ Is Considered As An Invalid Expression

### ISSUE THREAD

**Issue by ArthurZ** [Microsoft/vscode#16891] opened 2016-12-08 03:43 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|Bookmarks|alefragnani|0.10.1|
|vscode-color|anseki|0.2.2|
|ruby-on-rails-snippets|atefth|0.0.1|
|erb|CraigMaslowski|0.0.1|
|LogFileHighlighter|emilast|1.0.1|
|eq|eqela|1.0.0|
|code-runner|formulahendry|0.6.2|
|mdmath|goessner|0.9.0|
|ruby|groksrc|0.0.6|
|name-that-color|guillaumedoutriaux|0.0.1|
|findfile|HastenS|0.0.4|
|icon-fonts|idleberg|1.3.0|
|markdown-toc|joffreykern|1.3.0|
|markdown-table-formatter|josa|0.0.4|
|mdhelper|joshbax|0.0.9|
|vs-color-picker|lihui|0.3.2|
|markdown-shortcuts|mdickin|0.5.0|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.1.5|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|color-highlight|naumovs|1.3.0|
|copy-file-name|nemesv|1.0.0|
|markdown-checkbox|PKief|1.0.2|
|material-icon-theme|PKief|1.1.4|
|Ruby|rebornix|0.10.4|
|markdown-authoring|yanz|0.1.5|
|markdown-pdf|yzane|0.1.4|

---

Steps to Reproduce:

1. Enter some text as TEST:123 BOOK:ISBN2143123 Author:Joe Doe
2. Open search, expression and paste into the find box (?<=:).+
 you will get an error "Invalid expression"

Open Notepad++ do the same, it works.

**Comment by michaeljota** [comment] 2016-12-08 03:59
I reproduce this in a regex tester, and fails with JavaScript flavor. 

https://regex101.com/r/WgmJAa/1

This is the flavor that VSCode uses, as this is made in Electron.

**Comment by kumarharsh** [comment] 2016-12-08 06:06
Javascript doesn't supprt lookbehind assertions inside Regular Expressions (yet). That's why this is not working for you. But if might come soon-ish: http://v8project.blogspot.in/2016/02/regexp-lookbehind-assertions.html?m=1

**Comment by alexandrudima** [comment] 2016-12-08 07:58
Indeed, this is a limitation of the JS regex expression flavour. Once v8 ships support for look behinds, and Electron updates to a version of v8 supporting them (Electron updates quite often), and we update to a newer version of Electron (we also update quite often), they will simply start working. Since there is no work on our side for this to happen, I opt to close this issue for now.

**Closed by alexandrudima** 2016-12-08 07:58 UTC
Labels: as-designed
