### ISSUE TITLE
node: Studio is not supported in NODE_OPTIONS

### ISSUE THREAD

**Issue by alexduros** [microsoft/vscode#102096] opened 2020-07-10 10:34 UTC
- VSCode Version: 1.47.0
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

I'm trying to to start node debugging session along with `aws-vault` as I need to access secure resource which require a valid `aws-vault` session. 
It is working on 1.46.1 (same OS Version).

UPDATE : I'm using `zsh` as a terminal. 

1. Launch a nodejs application with launch debug config with runtimeArgs (I adapted a bit the configuration for confidentiality reasons)

```
        {
            "cwd": "${workspaceFolder}",
            "type": "node",
            "name": "debug",
            "port": 9230,
            "request": "launch",
            "console": "integratedTerminal",
            "timeout": 300000,
            "skipFiles": [
                "<node_internals>/**",
                "node_modules/**"
            ],
            "runtimeArgs": [
                "exec",
                "profile",
                "--prompt=osascript",
                "--",
                "node",
                "--inspect-brk=9230",
                "index"
            ],
            "runtimeVersion": "12.16.1",
            "runtimeExecutable": "aws-vault"
        },
```

2. Unable to launch the process. Exiting with error : 

```
node: Studio is not supported in NODE_OPTIONS
```

The actual launch command is 

```
 env PATH=PATH_TO_NODE 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" ' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/m3/bkwcwnsx6kg3jdgfzkbwfnnm0000gn/T/node-cdp.13047-2.sock","deferredMode":false,"waitForDebugger":"","execPath":"/path/to/nvm/node/v13.3.0/bin/node","onlyEntrypoint":false,"fileCallback":"/var/folders/m3/bkwcwnsx6kg3jdgfzkbwfnnm0000gn/T/node-debug-callback-9fd96f53c9feef22"}' /usr/local/bin/aws-vault exec profile --prompt=osascript -- node index
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-07-10 10:52
Looks like duplicate of #98778
Can you check https://github.com/microsoft/vscode/issues/98778#issuecomment-649784816 and see if it helps?

**Comment by connor4312** [comment] 2020-07-10 15:04
It's actually https://github.com/microsoft/vscode/issues/102035#issuecomment-656384728

You can solve this by:

1. Updating Node to 12+,
1. Using the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) which contains a fix to this, or
1. Setting `debug.javascript.usePreview: false` to temporarily use the old debugger, until a fix for this lands in stable.

**Closed** 2020-07-10 15:04 UTC
Labels: *duplicate, new release

**Comment by connor4312** [comment] 2020-07-16 21:25
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by armchairdeity** [comment] 2020-07-17 19:28
@connor4312 - OK this is freaky... I've never encountered this issue before. I just upgraded my local Node version from 10 to 14 and it started doing it... so I start googling and look , and find out that the fix was released in the last 24 hours.

That's some friggin serendipity. Hells yeah.

**Comment by armchairdeity** [comment] 2020-07-17 19:28
Anyway... meant to say thank you, and yep! Fixed it. ROCK ON TEAM VSCODE!

You guys should do merch... #justsayin
