### ISSUE TITLE
Colour picker disappears when mouse hovers outside editor split

### ISSUE THREAD

**Issue by kimbar** [Microsoft/vscode#36195] opened 2017-10-13 04:56 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. split the editor
2. open "User Settings" in left split
3. enter some custom colours in ``workbench.colorCustomizations``
4. shrink the left split enough to have a colour box near to the split edge
5. activate colour picker
6. move the pointer **hovering over** the colour picker, but through the split vertical line to the other side (eg. to change the hue)
7. the colour picker disappears

![obraz](https://user-images.githubusercontent.com/16984571/31530861-a17fcbdc-afe3-11e7-8e4c-23282af5bc87.png)

Reproduces without extensions: Yes

**Comment by kieferrm** [comment] 2017-12-06 18:40
Since I have the sidebar on the right I hit that quite frequently.

**Comment by usernamehw** [comment] 2018-04-24 20:34
Duplicate of #42818 ?

**Comment by tommai78101** [comment] 2018-06-21 13:15
My theory (may be wrong) is:

-------

Each tab, regardless if it's a document, a settings, UI element, panel, etc., are considered as a JavaScript entity, `document`. When a mouse leaves a `document`, the event is fired off and no longer can be able to detect mouse events.

Perhaps the Color Picker is closing prematurely is because it received a `mouseout` event, a `blur` event, or something that would cause it to fire off a "close" event of some kind, because the `document` is telling the Color Picker the mouse has left the area.

-----

Thoughts?

**Comment by rebornix** [comment] 2018-09-20 21:13
Shares the same root cause as https://github.com/Microsoft/vscode/issues/51794 since we are using the Hover for the color picker. Let's track it there.

**Closed** 2018-09-20 21:14 UTC
Labels: *duplicate, bug, editor-color-picker, editor-hover
