### ISSUE TITLE
[folding] Regions inside a class do  not work

### ISSUE THREAD

**Issue by buffos** [Microsoft/vscode#50210] opened 2018-05-21 10:27 UTC
For some reason, folding does not work in the following class snippet.
When the functions are empty it works fine. With code inside it will not work

```javascript
class Matrix {
  constructor(...args) {
    if (Array.isArray(args[0])) {
      this.shape = args[1];
      this.data = args[0];
    } else {
      this.shape = args;
      this.data = null;
    }
    this.offsets = offsets(this.shape);
    this.length = this.offsets[0];
  }

  //#region indexing
  getAt(...args) {
    if (this.data === null) throw ReferenceError('Matrix data is empty');
    const index = this.indexAt(...args);
    if (index >= this.length) throw RangeError('Index out of range');
    return this.data[this.indexAt(...args)];
  }

  indexAt(...args) {
    let position = 0;
    args.forEach(
      (arg, index) => (position += (arg - 1) * (this.offsets[index + 1] | 0))
    );
    position += args[args.length - 1]; // the last element is added without offset
    return position - 1;
  }
  //#endregion

  //#region initialization functions
  ones() {
    this.data = new Array(this.length).fill(1);
    return this;
  }

  zeros() {
    this.data = new Array(this.length).fill(0);
    return this;
  }

  //#endregion

  //#region Add function
  mAdd(matrixA, matrixB) {
    // check for compatible shapes
    if (!matrixA.shape.equals(matrixB.shape))
      throw TypeError('Incompatible Shapes');
    // create the new matrix
    let matrixC = new Matrix(...matrixA.shape);
    // add elements
    matrixC.data = matrixA.data.map(
      (_, index) => matrixA.data[index] + matrixB.data[index]
    );
    return matrixC;
  }

  add(matrixB) {
    // check for compatible shapes
    if (!this.shape.equals(matrixB.shape))
      throw TypeError('Incompatible Shapes');
    this.data = this.data.map(
      (_, index) => this.data[index] + matrixB.data[index]
    );
    return this;
  }
  //#endregion
}
```

**Comment by mjbvz** [comment] 2018-05-22 22:09
Duplicate of #49904

Should be fixed in the next insiders build

**Closed by mjbvz** 2018-05-22 22:09 UTC
