### ISSUE TITLE
Code Works very slow with large JSON files

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#17731] opened 2016-12-22 13:48 UTC
- VSCode Version: 1.8.1 
- OS Version: Windows 7

Code now gets hang when handling large files, works really slow tab change , selecting any text from the file, adding anything !
It was fine fine before but after the update the large files doenst work as expected.
Sample file is the JSON file with the lines about 242846 lines.

Tried with 1.9 insiders, same problem!

**Comment by egamma** [comment] 2016-12-23 16:16
@shanalikhan can you attach the JSON file that causes the problem.

**Comment by shanalikhan** [comment] 2016-12-23 19:39
File contains SAP client data so i dont think it would be feasible to share the file.

**Comment by aeschli** [comment] 2017-01-04 00:55
I'm not able to reproduce that. I created  a file with 240000 lines and was still able to work with it nicely. 
Can you run VSCode without any extensions and see if a extension is causing the problem?
Maybe this is a duplicate of #17859.

**Comment by aeschli** [comment] 2017-01-30 21:01
Closing, I'm not able to reproduce

**Closed by aeschli** 2017-01-30 21:01 UTC
Labels: freeze-slow-crash
