### ISSUE TITLE
`git.closeDiffOnOperation` does not work when staging multiple files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#144821] opened 2022-03-10 09:34 UTC
Steps to Reproduce:

1. enable `git.closeDiffOnOperation`
2. click on a diff
3. stage all

=> 🐛  diff editors are not closed

![Recording 2022-03-10 at 10 33 55](https://user-images.githubusercontent.com/900690/157633209-f93765d2-46fc-48cd-9650-c886c8e04bc8.gif)

**Comment by lszomoru** [comment] 2022-03-10 11:58
@bpasero, do you have a consistent repro of this? My hypothesis at the moment is that `window.tabGroups.all` returns an empty array and that is why we are not closing the diff editor. If you have a consistent repro, that should be easy to validate. 

//cc @lramos15

**Comment by bpasero** [comment] 2022-03-10 12:07
Repro:
![Recording 2022-03-10 at 13 07 13](https://user-images.githubusercontent.com/900690/157658480-3b94133c-b682-4cfe-b7e7-f643b4857b4b.gif)

**Comment by lszomoru** [comment] 2022-03-10 13:35
Could we set up a screen share so that I take a look, in order to validate whether this is a git issue or an editor API issue?

**Comment by bpasero** [comment] 2022-03-10 14:26
Debugging this, it turns out `window.tabGroups` returns an empty array. 

This is easy for me to reproduce, even running out of sources. I suspect this is somewhat related to the fact that the same diff editor opens and closes.

@lramos15 can you check?

**Comment by lramos15** [comment] 2022-03-14 18:35
@bpasero I was only able to reproduce this once and not again afterwards. I have a few changes and hit stage all is there anything else I should be doing? I'm also happy to jump in a call with you and go over it to figure out what's going on

**Comment by bpasero** [comment] 2022-03-14 19:17
@lramos15 it reproduces every single time for me, even with fresh user data dir. When it happens, the call

```ts
this._proxy.$acceptEditorTabModel(this._tabGroupModel)
```

Always sends an empty array.

Here are my steps:
* generate a hello world extension called `test-ts` via `yo code`
* open `CHANGELOG.md` and add `asdad` to the last line
* open `package.json` and add `asdasd` to line 16
* open `README.md` and add `asdad` to line 16
* close all editors
* close VSCode
* open VSCode
* open changes view
* click `README.md` it should open a compare editor
* stage `README.md` it should close the diff editor
* unstage `README.md`
* click `README.md` it should open a compare editor
* stage `README.md`

=> :bug: it does not close

**Comment by bpasero** [comment] 2022-03-14 19:19
![Recording 2022-03-14 at 20 19 34](https://user-images.githubusercontent.com/900690/158245236-8425a510-451c-46b3-a2b5-4fdb32bb7db9.gif)

**Comment by lramos15** [comment] 2022-03-21 17:58
A lot of refactoring has been done since this bug has been made and I am unable to reproduce the issue even with the `test-ts` steps. Closing for verification

**Comment by bpasero** [comment] 2022-03-21 18:03
Yeah the original steps seem better now. One case that I still see failing is the following, but I am not sure this is a tab API issue or a git extension issue:

![Recording 2022-03-21 at 19 02 31](https://user-images.githubusercontent.com/900690/159335877-f5287e5f-4f03-4727-8db7-7396d56552cd.gif)

Basically when I have opened 2 editors and then stage all, only the active one closes.

**Comment by bpasero** [comment] 2022-03-21 18:04
Steps are actually easy for me:
* have multiple outgoing changes
* click on 2 of them and leave them open
* stage all

=> 🐛 only the active one closes

**Comment by lramos15** [comment] 2022-03-21 18:04
I can repro that, will take a look

**Closed** 2022-03-21 18:47 UTC
Labels: bug, workbench-editors
