### ISSUE TITLE
 Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93308] opened 2020-03-24 13:07 UTC
Issue Id: <b>ae9ea8b6-c54b-6a27-937d-1df395101fe9</b><br /><br />*Versions* <br />- 1.43.1<br />*Stack* <br />TypeError: Cannot read property 'state' of undefined<br />[/vs/workbench/contrib/extensions/browser/extensionsList.ts#147:16 (renderElement)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L147:16 (renderElement))<br />[/vs/base/browser/ui/list/listPaging.ts#58:38](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/browser/ui/list/listPaging.ts#L58:38)<br />

**Comment by sandy081** [comment] 2020-03-26 12:02
@joaomoreno Can you please help me in understanding when this can happen? AFIK extension query does not return null elements.

**Comment by joaomoreno** [comment] 2020-04-01 06:04
@sandy081 `renderElement` will definitely only call with elements provided by you, so the undefined is coming from somewhere.

**Comment by sandy081** [comment] 2020-06-03 15:23
@joaomoreno Good thing is that I can repro this locally not consistently though. I see this while I am scrolling through most popular extensions. Some how `PagedModel.resolve` is returning an element with index that does not exist in the model. See below

<img width="892" alt="image" src="https://user-images.githubusercontent.com/10746682/83655413-af33d380-a5be-11ea-842e-621153ac4f3c.png">

BTW while reproducing this I made sure from the extensions side I filter out undefined or null elements from the model. 

Can you please take a look.

**Comment by joaomoreno** [comment] 2020-06-04 09:09
Awesome, great catch, let me see if I can pick it up.

**Comment by joaomoreno** [comment] 2020-06-30 14:07
@sandy081 I can't reproduce at all. But your screenshot points to something interesting: your page has 34 elements, up to index 33... and `indexInPage` is 34, which is invalid... so I wonder how you got into that state. 🤔 

Do you have any views in which you mix the results of two queries together? This will break the paging.

**Comment by sandy081** [comment] 2020-07-01 07:49
> Do you have any views in which you mix the results of two queries together? This will break the paging.

I do not think so, each view has single list model and I only set data from single query into this model.

**Comment by sandy081** [comment] 2020-07-01 07:51
May be bette is to screen share next week and debug it together?

**Comment by joaomoreno** [comment] 2020-09-30 12:41
@sandy081 Let's remember this next time we sit together. We already know it's related to fractional scrolling.

**Comment by sandy081** [comment] 2020-11-24 10:54
I can't reproduce this anymore. Hence closing this.

**Closed by sandy081** 2020-11-24 10:54 UTC
Labels: bug, error-telemetry, list

**Comment by joaomoreno** [comment] 2020-11-24 11:05
This could've been fixed by an Electron update, since it was fairly reproducible on macOS.
