### ISSUE TITLE
Visual Code Freezes always now since last update

### ISSUE THREAD

**Issue by awaemmanuel** [Microsoft/vscode#11886] opened 2016-09-12 14:27 UTC
- VSCode Version: 1.5.1
- OS Version:  Microsoft Windows 10 Enterprise (10.0.14393)  

Steps to Reproduce:  
1. Open VSCode from a folder with my README.md files
2. Open an .md file
3. Open .md Preview
4. Start typing text
5. App freezes

![image](https://cloud.githubusercontent.com/assets/3170798/18439348/eff9f3c6-78d2-11e6-9a7d-d5404dfe47fe.png)

**Comment by neilpeterson** [comment] 2016-09-12 18:55
I am having the same issue.

OS:

```none
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0
```
Visual Studio Code Version - 1.5.2.

I've removed all extensions and reinstall VSCode.

**Comment by bpasero** [comment] 2016-09-13 13:10
Assuming this is related to markdown and webviews assigning to @jrieken and @kieferrm.

**Comment by jrieken** [comment] 2016-09-13 14:20
Can you guys check which process is running high? Please check top/htop/process_explorer and include the *full* command line string that was used the launch the bad processes. Thanks

**Comment by prusello** [comment] 2016-09-19 14:45
I'm having the same issue under Windows 7 64 bit with v1.5.2 and previously with v1.3.1. Same process to replicate as everyone else. I had Windows Task Manager generate a process dump, but it's 350 MB so not so easy to share. Let me know if there's a better way to get information on this. When looking at the processes tab in Task Manager, one of the Code.exe *32 processes was using 250 MB of memory. I didn't see a way to get more detailed information on that specific Code.exe process.

**Comment by larswolter** [comment] 2016-09-20 09:52
I encountered the same problem with 1.5.2 on Win7 x64, none of the processes consume CPU, I got it to unfreeze reproducable when killing the eslint process (the last one in the screenshot). 
The ESLint Plugin has Version 1.0.6

![vsc_processes](https://cloud.githubusercontent.com/assets/13793513/18665553/1ac0082e-7f28-11e6-87b9-831ded28ce17.png)

**Comment by dbaeumer** [comment] 2016-09-21 08:58
@prusello you can use the process explorer from here https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx. Select the process with the high CPU / memory consumption and run Properties from the context menu. This should give you access to the full command line used to start the process. Please provide the command line here.

Regarding eslint: I can think of no why how the eslint process spawned from the extension host could freeze the renderer without any CPU load.

**Comment by prusello** [comment] 2016-09-21 13:11
I've been trying to get VSCode to freeze this morning, but no such luck. I've been typing for at least a half hour, one minor slow up but VSCode recovered in a few seconds.

In between my original post and this one, I did update the donjayamanne.python-0.3.24 extension and ms-vscode.cpptools-0.9.1 extension. I don't know why either of those would affect Markdown, but that's the only change to VSCode. A bunch of system updates happened yesterday (this is a work computer, so I don't have a list of them) as well, but I'm using the zipped VSCode install so I can update without admin rights so I'm not sure how those would affect VSCode.

If I do encounter a freeze, I'll post the Process Explorer command line here. Thanks for the help and I guess it's good I can't reproduce the freeze now, even though I'm not sure what fixed it...

**Comment by dbaeumer** [comment] 2016-09-22 19:07
@prusello good to heat thatr the freeze went away. I will keep the issue open for now in case you see it again.

**Comment by NearlyUnique** [comment] 2016-09-27 08:30
I have VS Code 1.5.3 and editing markdown hangs routinely. Is there a dump file I can share?

**Comment by dbaeumer** [comment] 2016-09-27 08:53
@kieferrm any hint how to track this down. The original reports and @NearlyUnique complain about markdown.

**Comment by NearlyUnique** [comment] 2016-09-27 11:48
I can use ProcDump to generate a dump file but not sure if that'll help. There is also 7 Code.exe processes and 1 CodeHelper.exe processor, I'm not sure which part hung. There is also a cmd.exe, which I assume is the terminal window.

Process Explorer says the main thread that is still running has a start address of `code.exe!?setID@Transliterator@icu_54@@IAEXABVUnicodeString@2@7@@Z+0x2c9de`

ProDump - https://technet.microsoft.com/en-gb/sysinternals/dd996900.aspx

**Comment by NearlyUnique** [comment] 2016-10-17 07:43
This has not happened for some time now, though I cannot determine what caused it to stop.

I am now upgraded to1.6.1. I'll report it if it happens again

**Comment by dbaeumer** [comment] 2016-10-17 18:22
@bpasero also 1.5.1 could this be caused by the pipe problem as well ?

@NearlyUnique is the md file you open large ?

**Comment by bpasero** [comment] 2016-10-18 04:46
@dbaeumer yes quite possible. as far as I know the freeze is there since node.js 4.x

**Comment by NearlyUnique** [comment] 2016-10-19 11:59
@dbaeumer The files are not large and since my last post I have been editing markdown and go with no ill effects. If it happens again I will look at trying to setup the vscode development/debug environment so I can supply more info.

**Comment by kieferrm** [comment] 2017-04-21 21:57
The information in this issue is about pretty old versions. We haven't seen similar issues for a while. I'll close the issue. Please file a new issue when you see issues in the most recent version of VS Code.
Thanks!

**Closed by kieferrm** 2017-04-21 21:57 UTC
Labels: freeze-slow-crash, needs more info
