### ISSUE TITLE
Colorize files/folders based on .gitignore

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1086] opened 2015-12-07 22:50 UTC
It would be nice if the files/folders text was colorized within the file tree based on the `.gitignore` files.

For example:

    Blue  = File Updated
    Green = File Added
    Gray  = File Ignored

Here is an example that shows added files and ignored files:

![git file highlight](https://cloud.githubusercontent.com/assets/1571806/11642352/0ffe4d7c-9d03-11e5-900d-5e8b1d61d010.jpg)

**Comment by choidamdam** [comment] 2016-01-12 01:14
+1

**Comment by OlsonDev** [comment] 2016-02-12 10:48
+1; I found this issue because I was hoping to just set arbitrary colors/styles on folders/files, including those related to `.gitignore`.

To expand on @TheColorRed's example:
```
Folders => bold

Folder `node_modules` & children => npm logo red
Folder `controllers` & children => blue
Folder `models` & children => green
Folder `views` & children => gold

Files in root, folder `dist` & children, specified by `.gitignore` => light grey

git file updated => blue underline
git file added => green underline
```

I envisioned a place to put our own styles, `explorer.css` or something:

```css
.folder, .file {
    color: inherit; /* Assuming tree has them nested in DOM */
}
.folder {
    font-weight: bold;
}
.folder[data-name="node_modules"] {
    color: #CB3837;
}
.file.project-root, .git-ignored, .folder[data-name="dist"] {
    color: lightgrey;
}
.git-added {
    text-decoration: underline;
    text-decoration-color: green; /* not supported yet, workaround/hack not relevant */
}
/* etc. */
```

**Comment by timc13** [comment] 2016-03-10 06:19
+1

**Comment by Tyriar** [comment] 2016-03-12 04:57
Duplicate of https://github.com/Microsoft/vscode/issues/178

**Closed by Tyriar** 2016-03-12 04:57 UTC
Labels: feature-request, files, git
