### ISSUE TITLE
Terminal shell integration without consent adds maddening nonsense to command output

### ISSUE THREAD

**Issue by thedewi** [microsoft/vscode#231915] opened 2024-10-22 07:53 UTC
Type: <b>Bug</b>

I have been seeing maddening nonsense (GUIDs, partial echoes of my own commands) at the top of terminal command outputs for weeks. I am shocked to discover this isn't just a bug, but the deliberate injection of broken scripts into my shell which I do not remember being adequately informed of or consenting to.

This is just such a risky thing to do, and should not be on by default. This is really damaging to trust.

This is kind of a duplicate of https://github.com/microsoft/vscode/issues/211972 , I guess.

### Workaround

I disabled `terminal.integrated.shellIntegration.enabled`, which should be the default.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.76GB (38.23GB free)|
|Process Argv|--crash-reporter-id c00a1374-0aa8-4417-8fbd-4a58c235f0a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
pastespecial|d3v|0.9.1
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-open-multiple-files|fab|2.0.4
shell-format|fox|7.2.5
vscode-github-actions|git|0.27.0
terraform|has|2.29.0
vscode-drawio|hed|1.6.6
jq-syntax-highlighting|jq-|0.0.2
bulk-problem-diagnostics|Mar|1.0.7
rainbow-csv|mec|3.12.0
vscode-azureresourcegroups|ms-|0.9.7
vscode-bicep|ms-|0.30.23
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.2.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.24.0
azure-account|ms-|0.12.0
vscode-paste-image|mus|1.0.4
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
code-spell-checker|str|3.0.1
shellcheck|tim|0.37.1
pdf|tom|1.2.2
sort-lines|Tyr|1.11.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
showbadge:31153266
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

**Comment by Tyriar** [comment] 2024-12-18 20:11
Sorry you're experiencing problems, we will soon be shipping conpty v2 in VS Code which should fix the majority of these problems as the root cause is in the emulation layer built into Windows (and you're on an old version of Windows):

---

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-18 20:11 UTC
