### ISSUE TITLE
Import suggestions not showing the source (only shows `Auto import from '...`)

### ISSUE THREAD

**Issue by EddyVinck** [microsoft/vscode#104160] opened 2020-08-06 09:00 UTC
- Version: 1.48.0-insider
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 5.3.0-62-generic

Steps to Reproduce:

1. Try to import a file with the import suggestions (in my case, type `<BarChart`
2. See the import suggestions and notice they don't show the source of the import

![image](https://user-images.githubusercontent.com/23434753/89512022-f020b200-d7d2-11ea-8e4e-318345869901.png)

This makes it very hard to decide which import you need when names of functions or components overlap.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mattrhysgregory** [comment] 2020-08-06 11:44
Have noticed this too

**Comment by IllusionMH** [comment] 2020-08-06 17:30
/duplicate of #98228, #29757 and others

Space is limited therefore you can press <kbd>Ctrl</kbd>+<kbd>Space</kbd> one more time to see more details (not only path to import).

**Closed** 2020-08-06 17:30 UTC
Labels: *duplicate
