### ISSUE TITLE
about `typescript.check.npmIsInstalled` or other bug ?

### ISSUE THREAD

**Issue by ifzm** [Microsoft/vscode#27340] opened 2017-05-26 15:02 UTC
![2017-05-26 22-42-20](https://cloud.githubusercontent.com/assets/12740295/26500100/58bb8dda-4267-11e7-947e-5bf162e476b4.png)

- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04

As the picture shows，It's about a `typescript.check.npmIsInstalled` or other bug ?

**Comment by mjbvz** [comment] 2017-05-31 03:18
This is a duplicate of #24961

See [this comment](https://github.com/Microsoft/vscode/issues/24961#issuecomment-305040579) for the workaround we have planned for VSCode 1.13. In the next insiders build, you should be able to set `"typescript.npm"` to point to where you have npm installed to fix this issue

**Closed by mjbvz** 2017-05-31 03:18 UTC
Labels: duplicate, javascript

**Comment by ifzm** [comment] 2017-05-31 03:55
@mjbvz  thank you
