### ISSUE TITLE
VSCode File Tree Not Appearing On Load

### ISSUE THREAD

**Issue by ahinkle** [Microsoft/vscode#33804] opened 2017-09-04 15:22 UTC
- VSCode Version: 1.15.1
- OS Version: Windows 10 Latest Update (9/4/2017)

Steps to Reproduce:

1. Open Application
2. Start > Open Folder > Select Folder
3. No files appear in file tree except for the "Welcome" menu.
4. This appears to happen when I delete the main tree folder and then use a USB to copy + paste a new folder from the USB to same directory and rename it to the original main tree directory name.  

I've ignored this issue long enough - it's really hit and miss. I have to reload/switch folders in the application 5-10 times before it finally appears. I've uninstalled/disabled all extensions. I've went the route of setting restoreWindows to none and I'm still getting the same issue.

I've Googled this and can't find anything. I also have the same issue on a separate computer. Anyone have any suggestions?

Reproduces without extensions: Yes

**Comment by sandy081** [comment] 2017-09-04 17:46
Duplicate of #32962.

You would have got into this state like in [comment](https://github.com/Microsoft/vscode/issues/32962#issuecomment-324866098). 

If so, above comment also tells how to get the view back. 

I have removed this functionality in latest release, it means, folders views cannot be hidden neither intentionally nor accidentally

**Closed by sandy081** 2017-09-04 17:46 UTC
Labels: new release, workbench
