### ISSUE TITLE
No input box to create new file in Explorer

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#68691] opened 2019-02-14 09:32 UTC
* Open a file like `lua/language-cofiguration.json`
* Reload the workbench
* Try to create a file in the root by collapsing all and clicking new file

![kapture 2019-02-14 at 10 29 54](https://user-images.githubusercontent.com/5047891/52777307-be96b280-3043-11e9-86b2-ef13e67a161e.gif)

**Comment by frobinsonj** [comment] 2019-02-14 16:08
The input box is at the layer of the focused file/folder. When you collapse all, it keeps focus on files and folders.

![ezgif-1-b8053c16378b](https://user-images.githubusercontent.com/16726902/52799848-92465a80-3072-11e9-8455-6e4a89f22121.gif)

**Comment by williamparry** [comment] 2019-02-19 07:23
Is [`CollapseAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/viewlet.ts#L178) deprecated in favour of [`CollapseAction2`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/viewlet.ts#L198)?

**Comment by klick-barakgall** [comment] 2019-02-21 14:05
Hello, sorry if this is a bit off-topic but my issue #68126 was closed as a duplicate of this one, and I wasn't told if it was because the underlying issue was determined to be related? But I experienced entirely different behaviour then what is being called out here I think.

Can anyone have a look?

**Comment by isidorn** [comment] 2019-02-25 15:26
The issue here is that the tree keps the item focused even when it is collapsed. Which makes sense.
However here we need to `resolveTo` to the focued item. For that we need tree api similar to what is needed for https://github.com/Microsoft/vscode/issues/68627

**Comment by isidorn** [comment] 2019-02-26 16:05
Fixed by @joaomoreno

**Closed by isidorn** 2019-02-26 16:05 UTC
Labels: bug, file-explorer
