### ISSUE TITLE
Feature request: Show function parameters inline for every function call

### ISSUE THREAD

**Issue by calebdiaz** [microsoft/vscode#152604] opened 2022-06-19 23:11 UTC
The feature would show Inline parameters
those parameters would be read-only annotations displaying inline in the editor - on every function call - like some extensions already have, but this would be for all programming languages.

**Comment by mjbvz** [comment] 2022-06-20 20:40
Duplicate of #152597

**Closed by mjbvz** 2022-06-20 20:40 UTC
