### ISSUE TITLE
Outline View Expands & Collapses during editing

### ISSUE THREAD

**Issue by themelz** [microsoft/vscode#70702] opened 2019-03-18 16:12 UTC
Issue Type: <b>Bug</b>

As I edit a file, the Outline View for the current document changes many times during editing. This includes the tree for areas not being edited. 

Very annoying.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_638161011|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
editorenhancements|gur|1.0.0
haxe-hl|Hax|0.6.0
hxmanager|jar|0.4.5
debugger-for-chrome|msj|4.11.3
vshaxe|nad|2.7.0
lime-vscode-extension|ope|1.2.2
haxe-debug|vsh|1.2.2
haxe-extension-pack|vsh|1.3.0
hxcpp-debugger|vsh|1.2.1
codedox|wig|1.3.0

</details>

**Comment by jrieken** [comment] 2019-03-19 10:36
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by themelz** [comment] 2019-03-19 13:44
If I need to add more info, please specify exactly what info I need to add.

**Comment by jrieken** [comment] 2019-03-19 14:25
🙄 I use the outline, I don't see what you see. give me precise steps so that I can reproduce what you are describing. saying "it doesn't work" isn't enough. what language? what are you typing? what extension is providing outline? etc etc

**Comment by themelz** [comment] 2019-03-19 16:22
I think I've figured it out and it seems to be related to a change in the default behavior of the outline.

Before when I added a function with local variables, the tree would not expand to show those variables. Now it does. I don't want that so I collapse the entire outline and then open the top node or whatever you call it, which is the class name.

The problem seems to occur when I edit a function in a way that interferes with the identification of functions below it, like having a { with out a corresponding }. When I add the }, the functions below appear but now expanded.

If that's the issue then I would like an option where variables local to a function only appear when I deliberating expand that function.

My code is in the Haxe language but I'm guessing that's not the problem.

![weird1](https://user-images.githubusercontent.com/38919440/54623175-06d93400-4a39-11e9-8ac1-5916a297dbc5.jpg)
![weird2](https://user-images.githubusercontent.com/38919440/54623176-06d93400-4a39-11e9-9197-ef5bec346bb2.jpg)
![weird3](https://user-images.githubusercontent.com/38919440/54623177-06d93400-4a39-11e9-81d9-24b6a8d5d726.jpg)

**Comment by jrieken** [comment] 2019-03-19 16:26
Ok, one step closer: you have described the problem in great detail. Next: provide reproducible steps, like sample code, do that, do that (precise!), actual behaviour, wanted behaviour

**Comment by themelz** [comment] 2019-03-19 16:46
This is the sample code as shown in the images:

```
package;

class Weird 
{
    public function new()
    {
    }

    private function test()
    {
        var x:Int = 0;
	var y:Int = 0;

	y = 5;
	if (x == 0) { }
    }

    private function dummy()
    {
        var x:Int = 0;
	var y:Int = 0;
   }

    private function dummy2()
    {
        var x:Int = 0;
	var y:Int = 0;
    }
}

```
Collapse the entire outline then click Weird to expand that. Note that local variables are not shown.
In the Test function delete the } in { } and then reenter it. Note that the local variables in the following functions are now shown automatically.

The desired behavior is that local variables for a function are shown only when I expand that function.

**Comment by jrieken** [comment] 2019-03-22 08:35
The problem is that removing the `}` changes the syntax tree drastically, e.g `dummy` and `dummy2` are now children, not siblings, of `test`. When adding the `}` back the structure changes again and default tree expand behaviour strikes back. 

This is related, likely a dupe of https://github.com/Microsoft/vscode/issues/53262. We can try a different tree node identify approach, e.g instead of (internally) calling nodes `Weird/test`, `Weird/dummy`, or `Weird/test/dummy` we could use the ranges. However, that will mean state is lost when adding new lines

**Comment by themelz** [comment] 2019-03-22 17:04
The "default tree expand behavior" is new. Why was it changed to this? The default should return to what it was where only the main tree is auto expanded. Either that or add an option to auto expand main tree only or each method/function. 

I don't see how auto expanding the entire tree is useful to anyone. So any expansion of a method/function branch should only be automatic when editing that function.

**Comment by themelz** [comment] 2019-04-08 15:55
Any update? Will the new "default tree expand behavior" continue or will the old one be restored?

**Closed** 2019-06-28 08:54 UTC
Labels: *out-of-scope, outline, under-discussion

**Comment by ergcode** [comment] 2020-11-14 02:36
I wonder why all the requests to be able to customize (and maintain state, regardless of project) of the outline view are so much ignored?
