### ISSUE TITLE
Language Type being detected as C for C++ files

### ISSUE THREAD

**Issue by weshoke** [Microsoft/vscode#30523] opened 2017-07-12 15:06 UTC
- VSCode Version: Version 1.14.0 (1.14.0) b8cd5b9556d8b70ea560d35b903422363f6c5c40
- OS Version: OSX 10.12.4 (16E195)

Steps to Reproduce:

Not sure how to reproduce.  Maybe there's a log I can send?

I very clearly have C++ files being detected as C files:

<img width="277" alt="screen shot 2017-07-12 at 8 02 19 am" src="https://user-images.githubusercontent.com/339696/28124462-97002bec-66d8-11e7-8542-b24507100d39.png">

Reproduces without extensions: Yes

Ran with `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-extensions` still reproduces

**Comment by aeschli** [comment] 2017-07-13 01:10
@caioproiete can you open the dev tools and look at the div of the wrong label?

![image](https://user-images.githubusercontent.com/6461412/28146252-05d1128e-67ab-11e7-85ff-49340b7d6831.png)

**Comment by weshoke** [comment] 2017-07-13 17:42
<img width="1440" alt="screen shot 2017-07-13 at 10 42 05 am" src="https://user-images.githubusercontent.com/339696/28179807-f6c68b5e-67b7-11e7-86a0-89d31150100a.png">

**Comment by aeschli** [comment] 2017-07-17 01:17
Do you have a extension installed that added the cpp extension to the 'c' language? It would only be the assigned to the 'cpp' language.

**Comment by weshoke** [comment] 2017-07-17 01:20
It's very possible.  How do I figure this out?

**Comment by aeschli** [comment] 2017-07-17 05:57
In the extensions viewlet, look at all installed extessions and the 'contributions' they add.
This is an example of the 'Java' extension that adds the .class extension for Java.
![image](https://user-images.githubusercontent.com/6461412/28256756-d79ea480-6af7-11e7-9a08-ff430c16bfa1.png)

**Comment by weshoke** [comment] 2017-07-17 06:04
I was really surprised to see that the Microsoft C/C++ extension didn't have a languages section

<img width="862" alt="screen shot 2017-07-16 at 11 02 44 pm" src="https://user-images.githubusercontent.com/339696/28256855-f14983c8-6a7a-11e7-8f9f-ab7aa17d59e4.png">


My other extensions only add Python, Cython, C#, and CMake language references.  Nothing for C or C++ actually.

**Comment by aeschli** [comment] 2017-07-17 07:14
Most of the languages are defined by built-in language extensions that don't show up in the extensions viewlet.

**Comment by weshoke** [comment] 2017-07-17 16:42
Hmm.  So if there's no extension viewlet showing cpp/c language contributions, how do I debug from here?

**Comment by aeschli** [comment] 2017-07-18 00:50
Sorry, no idea. I can't reproduce in my setup. If you have a simple reproducible example that would be great.

**Comment by weshoke** [comment] 2017-07-19 00:31
I figure it out!  Somehow I bunch of files got explicitly added to my settings.json under the files.associations dictionary.
![screen shot 2017-07-18 at 5 29 58 pm](https://user-images.githubusercontent.com/339696/28345376-e1686f9a-6bde-11e7-896e-e832c3f9acf9.png)

**Comment by aeschli** [comment] 2017-08-10 14:17
Thanks for figuring that out. Closing the issue then!

**Closed by aeschli** 2017-08-10 14:17 UTC
