### ISSUE TITLE
Explorer contribution icons being changed to files/folders automatically

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#44619] opened 2018-02-27 17:44 UTC
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T06:09:52.377Z)
OS version: Darwin x64 17.4.0

Testing the Docker extension explorer contribution.  By default, there are no top level icons in the Docker explorer contribution:

![collapsed](https://user-images.githubusercontent.com/1487073/36744601-1f3af9f0-1ba2-11e8-9607-296d4bc9405d.png)

I contribute icons at the next level down for Images and Containers:

![images](https://user-images.githubusercontent.com/1487073/36744618-2c617a0a-1ba2-11e8-9993-f5d6b56280ff.png)

When I expand a node that takes time to load (e.g. the Registries node) then all the nodes that didn't have an icon are replaced with File/Folder icons:

![filefolder](https://user-images.githubusercontent.com/1487073/36744722-5dfd71c2-1ba2-11e8-96a5-3786475f73ae.png)

To repro you need Docker installed locally (https://www.docker.com/community-edition), then get the docker extension and run it locally:

``` bash
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install
code-insiders .
```

`F5` to run the extension

Open a folder, then expand the `Registries` node, then `Dockerhub` or `Azure` nodes, something to trigger the spinning icon where some async process is taking place to load the children.

**Comment by chrisdias** [comment] 2018-02-27 17:51
and if you collapse the folders and refresh, the File/Folder icons go away.

**Comment by sandy081** [comment] 2018-02-28 15:41
@chrisdias There are two parts here.

1. Having icons for some nodes and not for others is breaking the tree indentation. Hence place holder icons were added to the nodes (with children)  if one of the nodes (with children) has an icon. At the same time, an empty icon place holder is added to the node (leaf) if one of the leaf nodes has an icon. Refer to this issue for more details - https://github.com/Microsoft/vscode/issues/28974

When you collapse all and refresh all the information about tree is lost and hence icons were also lost.

2. Folders and Files icons being added  as was a bug. Place holder icon for container node in your case is a dotted box and for leaf node is empty icon.

Obviously this can be improved by adding icons for all container nodes (if there is one) and same for leaf nodes.

**Comment by chrisdias** [comment] 2018-02-28 16:52
If I'm reading the above correctly, I'm going to get a placeholder 'dotted box' icon inserted where I don't have icons, is that correct?

I really don't want icons for my top level items (Images, Containers, Registries). To me, they are like folders and I want to keep it clean, just like the explorer.  

![image](https://user-images.githubusercontent.com/1487073/36800419-5b171630-1c64-11e8-979d-52ff42b9a252.png)

Only when i get to an child that represents an actual thing (much like a file in the explorer) do I want an icon, which is why I only contribute icons for images, containers, and then registries (under `Dockerhub` and `Azure`).

**Comment by sandy081** [comment] 2018-02-28 17:34
Your tree is different with the file explorer tree. File explorer tree has icons only for files which are leafs. But the Docker tree has icons also for nodes with children that is making it different. 

Having icons at one level and not at other levels makes it complicated. For example if you have a node with icon  and with children under `Images` and node with children and without icon under `Registries` then the alignment is broken without fallback icon.

**Note:** A tree is aligned when labels of nodes at same level are aligned always.

Hence, there are just three states similar to file explorer:

1. No Icons
2. All nodes have icons
3. Only leaf nodes have icons

Place holder icons are placed when extension does not meet these requirements

**Comment by sandy081** [comment] 2018-03-01 10:55
Duplicate of #43531

**Closed** 2018-03-01 10:56 UTC
Labels: *duplicate, explorer-custom, insiders, needs more info
