### ISSUE TITLE
Breakpoint indicators out of sync with actual breakpoints

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#38082] opened 2017-11-10 17:08 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T08:13:46.054Z)
- OS Version: Windows_NT x64 10.0.17035
---

This isn't 100% reproducible but the breakpoint indicators seem to very often get out of sync with the actual breakpoints. You can see this below -- where I have no breakpoints, but indicators all over. I am also seeing issues where toggling a breakpoint by clicking in the gutter doesn't work all the time either, sometimes it adds the indicator without adding the actual breakpoint, others it adds the breakpoint with no indicator.

![image](https://user-images.githubusercontent.com/641685/32669703-74485138-c60f-11e7-9886-437c6bc2bc45.png)

Also to get the problem to go away, I usually have to completely restart vscode.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-11-10 21:22
This is a duplicate of a bug that is already fixed in the Insiders.

**Closed by weinand** 2017-11-10 21:22 UTC
Labels: debug, insiders

**Comment by isidorn** [comment] 2017-11-13 10:32
@eamodio omg that is one crazy theme

**Comment by eamodio** [comment] 2017-11-13 13:14
@isidorn haha - indeed. One of my own too - Amethyst. Guess you really gotta love purple to appreciate it ;)
