### ISSUE TITLE
Crash on specific console output

### ISSUE THREAD

**Issue by Zvezdin** [Microsoft/vscode#32220] opened 2017-08-10 09:13 UTC
VSCode crashes / stops responding when the following string is outputted to the bash console:
"b'\\x80\\x03]q\\x00(}q\\x01(X\\x04\\x00\\x00\\x00fromq\\x02K\\x01X\\x02\\x00\\x00\\x00toq\\x03K\\x02X\\x05\\x00\\x00\\x00valueq\\x04K\\x03u}q\\x05(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03u}q\\x06(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03ue.'"

To reproduce type the following in the vscode console:
bash -> echo "b'\\x80\\x03]q\\x00(}q\\x01(X\\x04\\x00\\x00\\x00fromq\\x02K\\x01X\\x02\\x00\\x00\\x00toq\\x03K\\x02X\\x05\\x00\\x00\\x00valueq\\x04K\\x03u}q\\x05(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03u}q\\x06(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03ue.'"

python -> a = "b'\\x80\\x03]q\\x00(}q\\x01(X\\x04\\x00\\x00\\x00fromq\\x02K\\x01X\\x02\\x00\\x00\\x00toq\\x03K\\x02X\\x05\\x00\\x00\\x00valueq\\x04K\\x03u}q\\x05(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03u}q\\x06(h\\x02K\\x01h\\x03K\\x02h\\x04K\\x03ue.'"

The string was a result of a pickled python dictionary

OS: Arch linux
Installed from: visual-studio-code package in AUR
version: 1.14.2-1

edit: The crash doesn't happen in gnome-terminal, most likely not a linux terminal issue

**Comment by weinand** [comment] 2017-08-10 09:22
I can reproduce by running the following in the Integrated terminal on macOS:
```
echo "b'\x80\x03]q\x00(}q\x01(X\x04\x00\x00\x00fromq\x02K\x01X\x02\x00\x00\x00toq\x03K\x02X\x05\x00\x00\x00valueq\x04K\x03u}q\x05(h\x02K\x01h\x03K\x02h\x04K\x03u}q\x06(h\x02K\x01h\x03K\x02h\x04K\x03ue.'"
```

**Comment by Tyriar** [comment] 2017-08-18 00:21
Duplicate of https://github.com/Microsoft/vscode/issues/24795

**Closed by Tyriar** 2017-08-18 00:21 UTC
Labels: integrated-terminal
