### ISSUE TITLE
Weird glitter around icons and text

### ISSUE THREAD

**Issue by Vladyslav42v** [microsoft/vscode#102432] opened 2020-07-13 21:40 UTC
After 'tab' to another apps I can see apperance of weird glitter around icons as well as text (as soon as I start editing text glitter dissapears though). Glitter around icons usually persist for up to few minutes. Obviously this is the case only with VS.

![image](https://user-images.githubusercontent.com/45950773/87356226-5e72ab80-c56a-11ea-9743-dddfbc5ad904.png)

**Comment by IllusionMH** [comment] 2020-07-13 22:04
/duplicate of #93356 or #94523

Should be fixed with starting VS Code with `code --disable-gpu` or more permanent setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Closed** 2020-07-13 22:05 UTC
Labels: *duplicate
