### ISSUE TITLE
Provide an API to resolve a ThemeColor into its real color

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#34411] opened 2017-09-14 22:52 UTC
AFAIK, there isn't any way to resolve a ThemeColor into its real css value. This would probably be useful in quite a few scenarios, but here's what I'm trying to do.

In the image below, I am adding an icon in the top right (link icon) to the hover, but because I have no controls for light vs dark, it is hard to get it to be visible. 

![image](https://user-images.githubusercontent.com/641685/30459148-e18724a0-997c-11e7-875b-396ffa6aa3d2.png)

What I'd like to do is actually use one of the theme colors (aside -- even though it is an svg I couldn't get any css color inheritance to work, neither as a file nor data-uri). So if there was a way to get the real color for a `ThemeColor`, I could build an svg document with the proper color and embed it into a data-uri.

**Comment by aeschli** [comment] 2017-09-15 10:11
duplicate of #32813

As described, I'm trying to avoid adding such API, as it involves sending theme change events and requiring clients to handle theme color changes. Maybe not such an issue with the hover.

For now, instead of using an image, any chance you can this with a font character?

**Closed by aeschli** 2017-09-15 10:11 UTC
Labels: api

**Comment by eamodio** [comment] 2017-09-15 13:41
@aeschli do we have access to the octicons in the hovers?

**Comment by aeschli** [comment] 2017-09-18 08:16
@jrieken Can you reply to https://github.com/Microsoft/vscode/issues/34411#issuecomment-329786043?

**Comment by eamodio** [comment] 2017-09-18 11:52
@aeschli As far as I can tell we don't, I ended up using a unicode character, but it would be nice to support both real icons and/or octicons.
