### ISSUE TITLE
hitting shift enter before a } adds an indent

### ISSUE THREAD

**Issue by lopugit** [Microsoft/vscode#37136] opened 2017-10-30 12:23 UTC
- VSCode Version: 1.17.2
- OS Version: Linux Mint 18.x / OS X / WINDOWS

Steps to Reproduce:

1. write two blocks of code
2. fold the first one with the minus icon next to the line number
3. put your cursor inside the first line of the 2nd block of code you wrote
4. then hit shift enter
5. see that your cursor will go into the first line of the folded block above

super annoying because it means you have to unfold every level of folded content before you can insert text between a line of text that is right below the folded content, because when you fold content it folds all blank lines below it too, meaning that when you shift enter to insert a block of code, it's impossible to do so without unfolding

If someone can point me in the direction of where this code might be stored I will try to rewrite it myself

Reproduces without extensions: Yes

GIF:
https://gyazo.com/27c8ba04bc93410d7eb2005abb5fd0bb

**Comment by octref** [comment] 2017-10-31 22:15
Folding related so pass to @aeschli

**Comment by aeschli** [comment] 2017-11-01 15:35
Reproduced with this example:
```
function thisFoldsToEndOfPage() {
    const variable = [];
}
```
The problem is that pressing enter before `}` adds a new line and indentation.
```
function thisFoldsToEndOfPage() {
    const variable = [];

  }
```
So the folding region no longer ends with `{` and includes more lines. It's folding state is restored and the cursor is moved to a visible area.

Ideally this can be fixed in the auto indent strategy, to no add any indent before '}'

**Comment by alexandrudima** [comment] 2017-11-01 15:58
@aeschli Shouldn't an edit inside a folded region cause the region to become unfolded ?

**Comment by lopugit** [comment] 2017-11-01 16:03
Ahhh it's an auto indent thing, hmmmmmmm, if I can help in any way.. Otherwise, have fun with this one aeschli :')

**Comment by aeschli** [comment] 2017-11-01 16:33
No auto indent also is wrong without folding.

**Comment by lopugit** [comment] 2017-11-01 18:04
@aeschli 

this also happens with no } present if you're interested
https://gyazo.com/5319e2126769ba2abab9d07a1296c3a5

**Comment by aeschli** [comment] 2017-11-02 10:34
Yes, inside a block you want the indent. But before a closing bracket you want a reduced indent.

**Comment by rebornix** [comment] 2017-11-27 23:25
@aeschli there might be issues with auto indent but when auto indent is correct, the problem @lopugit described still existed

1.19-Insiders, TypeScript file.
![indent-with-fold](https://user-images.githubusercontent.com/876920/33294738-d3dbff26-d386-11e7-8a13-7d5ecc991a51.gif)

In above gif, I tried to run `Insert Line Above` at the line of `}`, it inserts a new line above with good indentation (see what I did with the second block). Then I fold the first block, run the command again, it inserts a new line, the cursor goes to the first line. After unfolding, you can see that the `}`'s indentation doesn't change, so it doesn't affect how we fold.

**Comment by aeschli** [comment] 2017-11-30 09:52
@rebornix Oh, now I see it, it's with `Insert Line Above`.
I pushed a fix.

**Closed** 2017-11-30 10:21 UTC
Labels: bug, editor-folding
