### ISSUE TITLE
PHP file associations no longer working

### ISSUE THREAD

**Issue by thattomguy** [Microsoft/vscode#62056] opened 2018-10-29 15:39 UTC
Issue Type: <b>Bug</b>

VS Code - Insiders no longer recognizes my PHP file associations after today's update. I am currently running VS Code - Insiders version 1.29.0.

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:11:45.152Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
vscode-clock|Com|0.0.1
githistory|don|0.4.3
vsc-material-theme|Equ|2.5.1
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.4
vetur|oct|0.13.0
highlight-matching-tag|vin|0.7.1

</details>

**Comment by kieferrm** [comment] 2018-10-29 21:58
See also https://github.com/Microsoft/vscode/issues/62030.

**Comment by crewone** [comment] 2018-10-31 13:06
I have the same.

In my settings.json I have the following section (which used to work):

`"files.associations": {
        "*.inc": "php"
    },`

But every time I open an ".inc" file, it defaults to plain text - asks me what to do with it.

**Comment by alexandrudima** [comment] 2018-10-31 13:59
Duplicate of #62030

**Closed by alexandrudima** 2018-10-31 13:59 UTC
