### ISSUE TITLE
Allow access of token colors in webviews

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#159367] opened 2022-08-27 12:47 UTC
Hi,

when creating a Webviews it is possible to access the current colors via e.g.:
 var(--vscode-editor-foreground)

It would be helpful if it would be possible as well to get the token colors from syntax highlighting the same way, i.e. from the themes.
E.g. I would like to get the color used for comments in source code or others.

**Comment by mjbvz** [comment] 2022-08-28 16:13
Duplicate of #32813

**Closed by mjbvz** 2022-08-28 16:13 UTC

**Comment by maziac** [comment] 2022-08-29 15:19
Hmm, I read carefully through the duplicate but I still can't figure out how to do it in web views or if it is possible at all.
Do you have a simple example like that ```var(--vscode-editor-foreground)``` but for e.g. the 'comment' color?

**Comment by mjbvz** [comment] 2022-08-29 15:20
@maziac It's not possible at the moment

**Comment by maziac** [comment] 2022-08-29 15:33
Thanks for clarification. 
But "at the moment" seems like a euphemism. The feature request is open since 2017 :-)
So I guess this will most likely not be implemented.
