### ISSUE TITLE
Ctrl+click navigation to static class method in JavaScript is broken

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/vscode#17083] opened 2016-12-12 16:13 UTC
See the sample below.
Current behavior when I Ctrl+click the "initHistoryItem" name on line 3: nothing happens.
Expected behavior: VS Code should navigate to the actual static method initHistoryItem on line 5.

Similar problem, when I click on line 3 on the History name, VS navigates to strange definition in lib.es6.d.ts instead of focusing the current class name on line 1.

```
class History {
    search(items) {
        var urls = items.map(History.initHistoryItem); // <-- ctrl+click here
    };
    static initHistoryItem(hi) {
        hi.info = new URL(hi.url);
        return hi;
    };
};
```

- VSCode Version: 1.7.2
- OS Version: Windows 10 Anniversary Update

**Comment by mjbvz** [comment] 2016-12-13 00:35
The case with class `History` appears to be a bug on the TypeScript side. But even after renaming the class `Foo`, we still do not jump to the line with `class Foo` as I would expect. This more general case appears to be a bug on our side since Typescript hands back the correct definition in that case

The range of the definition that TS returns covers the entire class definition, so I believe that when the [TS definition provider returns this range](
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/definitionProvider.ts#L46), the [go to declaration logic checks to see if the cursor is already in the range](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L85). If it is, we do nothing.

@bpasero do you have any thoughts on how to handle this, or know someone who may be helpful here?

**Comment by mjbvz** [comment] 2016-12-13 00:40
Opened  https://github.com/Microsoft/TypeScript/issues/12866 to track the `History` case on the TS side.

**Comment by bpasero** [comment] 2016-12-13 09:06
I cannot reproduce after renaming `History` to `Foo`.

![untitled](https://cloud.githubusercontent.com/assets/900690/21133981/d33a3642-c11b-11e6-8d70-0e2c2e85b01d.gif)

**Comment by mjbvz** [comment] 2016-12-13 19:37
@bpasero The behavior I was describing is if you try to go to the definition of the class `Foo` itself. In that case, we do nothing because the cursor is already inside the definition of `Foo`. This is unexpected to me

**Comment by bpasero** [comment] 2016-12-14 07:54
There is some filtering being done [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L83) that seems to cause this bug. Adding @alexandrudima and @jrieken who seem to be authors of that code area.

**Comment by jrieken** [comment] 2016-12-14 08:36
We filter those definition on which we currently are. The issue is that TypeScript returns ranges spanning the whole type and not its name. This issue is tracked in https://github.com/Microsoft/TypeScript/issues/8808 and on our side in https://github.com/Microsoft/vscode/issues/6772. Closing as duplicate.

**Closed by jrieken** 2016-12-14 08:36 UTC
Labels: bug, intellisense, javascript, typescript
