### ISSUE TITLE
Add IntelliSense for JS in .html files (ESModules)

### ISSUE THREAD

**Issue by ivanjeremic** [microsoft/vscode#149005] opened 2022-05-07 18:23 UTC
There is currently no IntelliSense for ESM in `.html` files.

```js
<script type="module">
  //the path is not autocompleted
  import func from "./func.js";

  func();
</script>

```

**Comment by aeschli** [comment] 2022-05-09 20:02
duplicate of https://github.com/microsoft/vscode/issues/114115

**Closed by aeschli** 2022-05-09 20:02 UTC
