### ISSUE TITLE
Update imported file path while change folder path

### ISSUE THREAD

**Issue by bhavinshiroya1994** [Microsoft/vscode#65899] opened 2019-01-02 07:45 UTC
Issue Type: <b>Feature Request</b>

suggestion:

- while move one sub folder and make it to parent at that time imported all the component's path would be automatically update.

Regards,
Bhavin Shiroya

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by mjbvz** [comment] 2019-01-02 23:17
Sounds like a duplicate of #58987

Let me know if that is not the case

**Closed by mjbvz** 2019-01-02 23:17 UTC
Labels: javascript
