### ISSUE TITLE
Let the custom text editor decide when to use it

### ISSUE THREAD

**Issue by NCC1701M** [microsoft/vscode#166351] opened 2022-11-15 09:37 UTC
When providing an extension with a custom text editor and you set the `priority` property of the `customEditors` contribution point to `"default"` it opens all files with the custom editor that fit the selector. By default that is fine but it also opens the custom editor for files in diff mode. So it puts two custom editors side by side. This could lead to a loss of functionality because diff editing is quit more complex than editing a single file. It's even more complex when you have to highlight the changes.

A workaround would be to use one of the other `priority` options but this would lead to other problems. The user has to switch manually to the custom editor or he edits the file in text mode which could lead to inconsistencies.

The best solution would be to let the extension decide if the custom editor or the default text editor should be used. There are several ways to do this:

1. Add a when clause to the selector object  
  ```json
  "contributes": {
    "customEditors": [
    {
      "viewType": "my-custom.editor",
      "displayName": "A custom editor",
      "selector": [
        {
          "filenamePattern": "*.fileext",
          "when": "!isInDiffEditor"
        }
      ]
     }
    ]
  }
  ```
2. It could be handled in the  `resolveCustomTextEditor` method of the custom provider
  ```typescript
public constructor(private readonly _context: vscode.ExtensionContext) { }

resolveCustomTextEditor(document: TextDocument, webviewPanel: WebviewPanel, token: CancellationToken): Thenable<void> | void {
    if (_context.isDiffMode) {
      return;
    }

    webviewPanel.webview.html = this.htmlForWebview(webviewPanel.webview);
}
  ```
3. Some other solutions....

**Comment by mjbvz** [comment] 2022-11-15 18:42
Duplicate of #138525

**Closed by mjbvz** 2022-11-15 18:42 UTC
Labels: custom-editors
