### ISSUE TITLE
Freeze when PHP_Debug hits breakpoint

### ISSUE THREAD

**Issue by pamtbaau** [microsoft/vscode#123079] opened 2021-05-06 06:45 UTC
Issue Type: <b>Bug</b>

- Set breakpoint in PHP file
- When breakpoint is hit, VSCode will freeze.
- Solution: Refresh window (eg. resize, switch apps) will unfreeze

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU B830 @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.78GB (3.98GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu-20.04/www/grav/site-dev/.site-dev.code-workspace --remote=wsl+Ubuntu-20.04 --crash-reporter-id e9870f12-002b-4e9d-b5fd-ae76dc3cfddc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Celeron(R) CPU B830 @ 1.80GHz (2 x 1795)|
|Memory (System)|6.02GB (5.25GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.1
twig|wha|1.0.2
vscode-intelephense-client|bme|1.7.1
vscode-eslint|dba|2.1.20
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by pamtbaau** [comment] 2021-05-06 10:30
I don't thinks this issue has to do with extension PHP Debug.

The same issue was reported here: [PHP Debug: When breakpoint is hit, tab is frozen for long time, unless vscode refresh happens](https://github.com/microsoft/vscode/issues/117162)

It was said to be related to bug https://github.com/microsoft/vscode/issues/114459. When starting vscode with `code --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` the issue could not be reproduced.

A few weeks ago I started using remote debugging using WSL. Vscode runs in Windows 10, while PHP Debug extension runs in WSL. All went well, until today:
- It happened directly after update to v1.56.0
- Refreshing the vscode window using resize or moving vscode backward/forward unfreezes vscode. Same as issue https://github.com/microsoft/vscode/issues/117162

**Comment by zobo** [comment] 2021-05-06 11:27
vscode-php-debug extension maintainer here. Have you tried to disable other extensions? I wonder if there is a conflict between 
vscode-intelephense-client and php-debug. But from what you are saying here I doubt it.

**Comment by pamtbaau** [comment] 2021-05-06 11:41
- Upgraded back to latest vscode 1.56.0
- Disabled all extensions except Remote - WSL and PHP Debug
- vscode freezes when breakpoint is being hit, breakpoint is not highlighted
- Move vscode window to background/foreground, or minimize/maximize and vscode will unfreeze.

New fact:
- When vscode is not maximized, freezing does not occur.

**Comment by zobo** [comment] 2021-05-06 11:58
I have tried the described setup here. 
```
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```

`Remote - WSL 0.56.1` (Local extension)

`PHP Debug 0.56.1` (Remote extension)

I do not see the described freeze issue... Must be something environmental.

**Comment by pamtbaau** [comment] 2021-05-06 12:20
- Uninstalled extensions `Remote - WSL` and `PHP Debug`
- Removed folder `.vscode-server/` from WSL
- Reinstalled `Remote - WSL` (local) and `PHP Debug` (remote)

```
Version: 1.56.0 (system setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```
`Remote - WSL 0.56.1` (Local extension)
`PHP Debug` 1.14.12 (Remote extension)

- vscode freezes when breakpoint is hit, except... when vscode is partly hidden below Windows Taskbar
- vscode will unfree when window moved around, resized, etc.
- issue does not happen in vscode 1.55.2

**Comment by pamtbaau** [comment] 2021-05-06 12:41
- Deinstalled vscode
- Removed folder .vscode-server/ from WSL
- Removed folder `/Users/<user>/.vscode`
- Removed folders `/Users/<user>/AppData/Roaming/code` and `/Users/<user>/AppData/Roaming/Visual Studio Code` 
- Reboot
- **Installed vscode 1.55.2**
- Installed `Remote - WSL` (local) and `PHP Debug` (remote)
- No freeze of vscode when breakpoint is hit
- **Upgrade to vscode 1.56.0**
- Freeze of vscode when breakpoint is hit

**Comment by pamtbaau** [comment] 2021-05-06 13:33
Maybe far fetched... Chrome has an issue on Windows 10. The current tab freezes when the monitor switches off due to power savings. When the monitor awakes, one needs to switch Chrome tabs to get the current tab responding again.

To fix the issue I had to disable chrome://flag: `Calculate window occlusion on Windows`

vscode has upgraded its Electron dependency and Chrome....

**Comment by pamtbaau** [comment] 2021-05-07 09:30
@isidorn, Would you mind considering to re-open this issue? I cannot imagine that extension PHP Debug is the root cause of it. A similar behaviour has been issued before and was in no way related to the extension.

**Comment by pamtbaau** [comment] 2021-05-10 08:18
@isidorn, When running vscode with option `--disable-features=CalculateNativeWinOcclusion`, code tells me `Ignoring option disable-features: not supported for code.`

Something else noteworthy...
- When browser requests a page: Code freezes when the debugger hits a breakpoint.
- CLI executing PHP: Code does **NOT** freeze when the debugger hits a breakpoint.

**Comment by isidorn** [comment] 2021-05-10 08:22
Let's close as duplicate of https://github.com/microsoft/vscode/issues/123257
Please follow that issue for more details

**Closed by isidorn** 2021-05-10 08:22 UTC
Labels: needs more info

**Comment by pamtbaau** [comment] 2021-05-10 08:45
> That issue has more information which we need

That's a good reason :-)
