### ISSUE TITLE
Format document inserting 4 spaces instead of 2

### ISSUE THREAD

**Issue by frankorama** [Microsoft/vscode#15316] opened 2016-11-10 21:03 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|prettify-json|mohsen1|0.0.3|
|dust|nemesarial|0.0.1|

---

Steps to Reproduce:

1. open user settings
2. set "editor.tabSize": 2
3. "editor.detectIndentation": false
4. ensure nothing set in workSpace Settings
5. write some JS code
6. right-click "Format Document" or alt + shift + F

**Comment by aeschli** [comment] 2016-11-11 21:02
What is shown on the VSCode status line?
Formatting which language?

**Comment by frankorama** [comment] 2016-11-14 19:08
UTF-8  LF JavaScript.  The file I'm working in has a .js extension.

Some strange behaviour:  It seems to be back to 2 spaces now, but when I select all, shift+tab so all the indentation is removed, then right-click "format code", nothing happens.

I thought I had a syntax problem or forgot a semicolon somewhere, but everything looks good.  I removed all my comments as well.  Same behaviour.

**Comment by jedfonner** [comment] 2016-11-15 03:23
I am having this same problem with my .js files.  The status line shows "Spaces: 2" but when I Format Document, it changes all my tabs to 4 spaces.

**Comment by frankorama** [comment] 2016-11-15 10:14
The problem with the automatic formatting is only happening in VS Code for OSX.  I also work on a laptop with Windows 10 and the same code formats normally.

**Comment by jedfonner** [comment] 2016-11-15 11:56
This might be related to the [JS-CSS-HTML-formatter extension](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter).  Removing that extension seems to have solved the problem for me.

See https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/31

**Comment by frankorama** [comment] 2016-11-15 15:26
I only had DUST language support and JSON prettify extensions installed.  Removed them and the formatting is working normally now.  Not sure which one was causing the problem though.  Should have tested bette.

**Comment by dylanparry** [comment] 2016-11-15 16:53
I am seeing the same issue with Windows 10. It strangely only happens the **second** time I open a file.

For example, if I open up this:

![image](https://cloud.githubusercontent.com/assets/3692873/20314603/a4c279de-ab52-11e6-888a-fed2b01b9a09.png)

then hit `alt + shift + f`, the file stays the same with 2-space indentation. If I then close the file, open it up again, and hit `alt + shift + f`, I get this:

![image](https://cloud.githubusercontent.com/assets/3692873/20314648/cebb3726-ab52-11e6-883e-ac3379d334eb.png)

The same occurs for `.js` and `.jsx` files, but does **not** happen for `.json` which I am also formatting with 2-space indentation. It also appears to happen for `.ts` and `.tsx` as well—I'm guessing they use the same formatter now?

I have disabled all the extensions I have installed to see if it was any of them causing this, but it does not appear to be the case as disabling them made no difference.

**Comment by jrieken** [comment] 2016-11-15 17:35
@joaomoreno isn't this what you have seen with TS/JS and reported to them?

**Comment by joaomoreno** [comment] 2016-11-16 08:18
It could be Microsoft/TypeScript#12175

**Comment by MagmaRules** [comment] 2016-11-18 15:11
I'm having exactly the same issue as @dylanparry . OSX 10.11.6 VSCode 1.7.1.

**Comment by frankorama** [comment] 2016-11-18 15:33
I don't know if this helps, but it really is a random problem.  I just installed ESLint, JavaScript (ES6) code snippits, and jshint extensions.  The formatting function stopped working.  I disabled and reenabled the 3 extensions and formatting started working again.  Difficult to pinoint exactly which extension is causing the problem because the problem doesn't occur until after a couple of hours of coding sometimes.

**Comment by supoved** [comment] 2016-12-08 13:46
The issue intermittently happens and very often, but only on files that contains ES6 functions notations
`() => {
...
}`
and not affecting
`function() {
...
}`

**Comment by maybeec** [comment] 2016-12-09 12:35
I am observing this issue as well. Although, I identified no reproducable issue yet, I recognized, that the formatter will internally crash after some time of work. After that it will just use default settings rather than user settings and eventually does not format code at all anymore.

Is there any log, where suppressed issues might be logged to?

**Comment by waderyan** [comment] 2016-12-10 00:04
@maybeec if this is a TS / JS issue then it could be showing up in that log. You can see the log in the output window after adding this setting to your user setting:

```
"typescript.tsserver.trace": "verbose",
```

If you (and others) could post the output of the log when you see the issue here that would be helpful. 

Also if anyone has a workspace that reproduces this issue please post to help us reproduce.

**Comment by maybeec** [comment] 2016-12-12 10:15
I enabled the setting and will have a look when the error occurred. So where can I find the log file?

**Comment by waderyan** [comment] 2016-12-12 19:22
If you open the output window the log information is there... I don't know where the log file is actually created... @dbaeumer do you know the location of the TS log file that gets sent to the output window? Maybe the data is not persisted.

**Comment by maybeec** [comment] 2016-12-13 06:40
Ok basically, I was able to have a view at the output during observation of the error.
However, nothing of interest from tsserver as far as I can see. I save a file and the response comes from `format (2566)` which indicates to insert whitespaces in front of multiple lines. But there is nothing about format itself, e.g., which config is used.

So what I was observing now is, that this behavior comes up, when having multiple instances of vscode open for some time. After some time, the formatter begins to behave odd

**Comment by dbaeumer** [comment] 2016-12-13 08:26
To get the server log you can use an environment variable to control the location. Something like `TSS_LOG="-level verbose -file c:\tmp\server.log"`

**Comment by dylanparry** [comment] 2016-12-18 13:19
This seems to be fixed in the latest release, which bundles a new version of TypeScript. Can anyone else confirm this?

**Comment by mjbvz** [comment] 2017-01-31 23:11
Yes, I think that TS fixed a number of issues around formatting in 2.1.4 and 2.1.5. Please open a new issue if you still see this problem in VSCode 1.9 using TS 2.1.5+

**Closed by mjbvz** 2017-01-31 23:11 UTC
Labels: format, javascript, needs more info

**Comment by xaphod** [comment] 2017-06-20 19:39
Happening on vscode 1.13.1 for me on mac os latest, plugins: debugger for chrome 3.1.4, ESLint 1.2.11, React native Tools 0.3.2. Language: JavaScript, UTF-8

**Comment by RenaldasK** [comment] 2017-06-26 13:15
Not fixed, I still have this issue on VSCode 1.13.1 and TS 2.3.0

**Comment by nariatan** [comment] 2017-07-26 07:40
Not fixed, still have this issue.
macOS 10.12.6
VS CodeVersion 1.14.2 (1.14.2)

**Comment by kalehv** [comment] 2017-08-12 04:42
I believe this is related to https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/31
When I disabled this plugin, formatter maintained my setting of 2 spaces.

**Comment by anjdreas** [comment] 2017-08-26 20:50
Works here with `.html` files, set `Workspace Settings` to:
```
{
    "editor.tabSize": 2,
    "editor.detectIndentation": false
}
```

Default without either of these were 4 spaces.
1.15.1 on Win10.

**Comment by colorpump** [comment] 2017-10-19 14:07
Still have this issue:

* Windows 10
* VS Code 1.17.1
* html file: indent using spaces (4)
* Workspace Settings:

```
{
    "editor.tabSize": 4,
    "editor.detectIndentation": false
}
```
But pressing ALT + SHIFT + F still indented with 2 spaces

**Comment by aeschli** [comment] 2017-10-19 14:42
@colorpump Any extensions enabled related to HTML formatter? Please try without extensions.

To force tabs, use `"editor.insertSpaces": false`

**Comment by colorpump** [comment] 2017-10-19 17:10
It was my fault.
I had a **.editorconfig** file in my project as well which overrode my **.vscode/settings.json**

I'm sorry for confusion
