### ISSUE TITLE
"Continue on" missing from remote menu on desktop

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162119] opened 2022-09-28 06:31 UTC
Testing #161875

I would have expected a "Continue on" entry in the remote menu on desktop:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/900690/192704769-8bc8b4cd-bfcc-4805-a970-5ec5320e382c.png">

**Comment by joyceerhl** [comment] 2022-11-11 20:55
Duplicate of https://github.com/microsoft/vscode/issues/162259

**Closed by joyceerhl** 2022-11-11 20:55 UTC
Labels: feature-request
