### ISSUE TITLE
PHP Autocompletion Activates on closing ?>

### ISSUE THREAD

**Issue by moshie** [Microsoft/vscode#39776] opened 2017-12-06 10:31 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
php-docblocker|nei|1.3.2
vscode-icons|rob|7.18.1
---

Steps to Reproduce:

1. Create a php file
2. Type `<?php ?>`
3. on the final letter the `>` activates the autocomplete 

Reproduces without extensions: Yes

I find this annoying since PHP is for templating and pressing return inserts `$_COOKIE`

**Comment by roblourens** [comment] 2017-12-06 17:46
/duplicate of https://github.com/Microsoft/vscode/issues/37919

Fixed in Insiders

**Closed by roblourens** 2017-12-06 17:46 UTC
Labels: php
