### ISSUE TITLE
Folder tree stops loading when using CTRL+Click to jump to a function in another folder

### ISSUE THREAD

**Issue by rohansekhri** [microsoft/vscode#73177] opened 2019-05-02 16:47 UTC
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Have a workspace that has two folders [in my case they are two different repos], say folder A and B
2. B is more like a wrapper layer that have the actual implementation in A
3. Load the workspace and check the folder tree. All folders and files are loaded normally
4. Open a file in B whose implementation is in A. eg: self.my_object.MethodInA(). Do not open any files from A
5. CTRL + Click to jump to the implementation 
6. The file containing that implementation is opened
7. Now start expanding folder 'A'. No files/folder are found

Does this issue occur when all extensions are disabled?: Did not test
[exthost.log](https://github.com/Microsoft/vscode/files/3139029/exthost.log)

Window log has the following exception:

```
[2019-05-02 11:29:04.378] [renderer6] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///C:/Users/RSekhri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:91:674)
    at setCollapsed (file:///C:/Users/RSekhri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:91:102)
    at s.collapse (file:///C:/Users/RSekhri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:940:219)
    at Y.<anonymous> (file:///C:/Users/RSekhri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:956:590)
    at Generator.next (<anonymous>)
    at r (file:///C:/Users/RSekhri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:32:293)
![load_steps](https://user-images.githubusercontent.com/46380417/57091969-5f5a4d00-6cd8-11e9-9069-bbccf8974d26.gif)
```
![load_steps](https://user-images.githubusercontent.com/46380417/57092098-97fa2680-6cd8-11e9-8397-ce1951116124.gif)

**Comment by isidorn** [comment] 2019-05-03 09:11
Can you reproduce this with latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by rohansekhri** [comment] 2019-05-03 18:54
Yes. It's reproducible on insiders too. The insiders build had only the Python extension. However, the exception was not seen but folders disappeared after CTRL+Click.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by isidorn** [comment] 2019-05-06 10:01
Please share a folder for which you can reproduce all the time. Can you please put it on GitHub so we can reproduce this issue on our machine?
Also exact steps would be useful.

**Comment by rohansekhri** [comment] 2019-05-06 14:06
Exact steps are there. In case, anything is not clear, please feel free to ask. 

The code is company proprietary, so I won't be able to upload that code. However, I can try on some custom code and see if it shows up. I would need some time on that.

**Comment by rohansekhri** [comment] 2019-05-30 21:58
I tried reproducing this with the version below using a small project which wasn't source controlled. Could not reproduce it. But, with the folder structure I have in my company, I can repro this 100%. Is there anything else I can share to resolve this issue?

Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment] 2019-05-31 08:45
Looks like a duplicate of https://github.com/microsoft/vscode/issues/73469

**Comment by rohansekhri** [comment] 2019-06-03 13:21
Exception is similar to what I posted earlier. I saw your comment there that you were able to reproduce it, so let's go with that fix and see if these two are related (on the insiders build, I didn't have any exceptions). Apologies, I haven't had much time to play around much the past weeks.

**Comment by isidorn** [comment] 2019-08-20 08:47
No data provided -> closing issue.
If you still see it please let me know with steps so I can reopen this. Thank you

**Closed by isidorn** 2019-08-20 08:47 UTC
Labels: file-explorer, needs more info
