### ISSUE TITLE
Interactive window on python. Slider not working

### ISSUE THREAD

**Issue by sergio12S** [microsoft/vscode#147827] opened 2022-04-21 08:21 UTC
Issue Type: <b>Bug</b>

The slider (on the right) for scrolling the window down in the interactive Python window does not work.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-25-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3560)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.36GB (2.75GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b3bd5f13-6cdb-4a0e-9c6a-f02bbc434f09|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-css-formatter|aes|1.0.2
tf2snippets|cha|0.1.0
npm-intellisense|chr|1.4.1
vscode-redis-client|cwe|1.2.8
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
python-preview|don|0.0.4
python-environment-manager|don|1.0.4
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
markdown-table-formatter|fcr|2.2.4
shell-format|fox|7.2.2
copilot|Git|1.12.5517
gc-excelviewer|Gra|4.2.54
Python-autopep8|him|1.0.2
rest-client|hum|0.24.6
vscode-kafka|jep|0.14.0
text-compact|jso|0.0.3
vscode-docker|ms-|1.22.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.16.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
vscode-yaml|red|1.6.0
synthwave-vscode|Rob|0.1.11
sourcery|sou|0.11.2
vscodeintellicode|Vis|1.2.19
JavaScriptSnippets|xab|1.8.0
vscode-intelli-refactor|ypr|0.1.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-04-21 09:26
/duplicate of #147027 and reported to be fixed in today's Insiders

**Closed** 2022-04-21 09:27 UTC
Labels: *duplicate, triage-needed
