### ISSUE TITLE
Improve hover appearance

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3196] opened 2016-02-20 13:39 UTC
I find it difficult to read hovers: the font is the same as the underlying text and the hover text does not stand out from the underlying text. And the fixed width font makes hovers wider than necessary. 

Look here: where is the hover?
![2016-02-20 14-33-36](https://cloud.githubusercontent.com/assets/1898161/13196972/746a61bc-d7df-11e5-883a-1a926573f05b.png)

**Comment by joaomoreno** [comment] 2016-02-22 09:26
Closing as duplicate of #2330

**Closed by joaomoreno** 2016-02-22 09:26 UTC
Labels: polish
