### ISSUE TITLE
Feature Request: Update to latest version instead of next version

### ISSUE THREAD

**Issue by pigrammer3** [microsoft/vscode#170298] opened 2022-12-30 17:49 UTC
Sometimes, I'm on vacation or for some other reason I do not open VSCode for a long time. After this, it is often the case that there are multiple updates (e.g., today I opened VSCode; my version was 1.74.0; the latest update is 1.74.2). Then, I have to restart once for each update. It would be great if I didn't have to manually do this for each update.

Now, I'm not sure how the update mechanism works; I assume it probably uses a diff between the previous version and the next version. In that case, the "restart to update" could apply all the updates.

Thank you.

**Comment by IllusionMH** [comment] 2023-01-01 01:32
VS Code does not use diff updates, it's always update to latest available version (after reset to update). But after update process started it won't check for newest version until restarted.

Looks like in your case VS Code downloaded "next" version (which was latest at that moment) before "latest" was available for download, but you didn't perform restart to update. Therefore first restart would be for "next" and after that you will get new request that would return "latest".

Not sure if updater is custom for VS Code or "default" updater for Electron.

**Comment by pigrammer3** [comment] 2023-01-01 01:34
That's the point; I have my VS Code window open, because I don't shut down my laptop often, but I don't use it. Then I have to restart twice if there have been multiple updates.

**Comment by IllusionMH** [comment] 2023-01-01 01:53
Duplicate of #142743 however not sure if there is tracking issue for update infra rework mentioned in https://github.com/microsoft/vscode/issues/142743#issuecomment-1035171117

**Closed** 2023-01-01 13:20 UTC
