### ISSUE TITLE
Global state is not updated in instances when more than one opened

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#132084] opened 2021-09-01 21:57 UTC
In the browser, Settings Sync appears to be on a per workspace instance, while settings.json is per browser.  This means that if you turn settings sync on in one workspace and off in another, and then make settings changes in the "off" workspace, those settings are still synchronized...

in the same browser instance, open two tabs with two instances of `github.dev`, for example:
- `https://github.dev/microsoft/vscode` 
- `https://github.dev/microsoft/vscode-docs`

open a local instance of VS Code, make sure settings sync is turned on and you have some interesting things in local `settings.json` (e.g., a theme is easy to see).

turn on settings sync in both browser tabs so that all 3 are now syncing

turn off setting sync in one of the browser tabs

in that same browser tab instance, where settings sync is off, edit some settings (e.g. delete them all!)

result: the settings are synchronized to the other browser instance and to the desktop, even though settings sync is "off". now you've lost all of your settings.

https://user-images.githubusercontent.com/1487073/131753118-9508f86a-0481-4d60-83ea-159c8a8a737f.mp4

**Comment by bamurtaugh** [comment] 2021-09-01 22:44
I can repro some of the above but not all. 

### Can repro:
The second github.dev tab gets the synced settings (i.e. I changed to a purple theme), :bug: but it isn't showing that it has Settings Sync enabled:

![image](https://user-images.githubusercontent.com/25310137/131754539-1da4286c-54e0-4693-ba7e-c8cc77b5a1b0.png)

I turned off Settings Sync in the first github.dev tab, then reverted color theme to default:

![image](https://user-images.githubusercontent.com/25310137/131754677-f2de6c3f-3108-4061-9d96-01ea7872b05e.png)

:bug: But the second tab (which never showed it had Settings Sync on, and shouldn't be syncing now anyways) got the change too:

![image](https://user-images.githubusercontent.com/25310137/131754775-205c608b-cf6c-4cea-82c5-676985184349.png)

### Can't repro:
One way that my experience differs is my changes did not get synced back to the desktop. The desktop still has the purple theme, as I'd expect.

**Comment by sandy081** [comment] 2021-09-02 06:29
In github.dev, settings sync is enabled/disabled per browser (not per workspace). If you enable it on one repo and it will be enabled from there on when you open other repos in the same browser instance. 
 
In github.dev, settings are shared across github.dev browser tabs (with different repos) as they share the same origin.
In short opening github.dev workspaces in a browser is like opening multiple windows in vscode desktop.

Root cause for your issue is the following:

> turn off setting sync in one of the browser tabs

It seems this change is not getting reflected in other browser tabs, hence other browser tabs are having settings sync enabled. We store the enablement state in global storage and seems like global strorage is not signaling the change in other tabs. You can confirm this by reloading other tabs and check that settings sync is now disabled. @bpasero FYI

> in that same browser tab instance, where settings sync is off, edit some settings (e.g. delete them all!)
result: the settings are synchronized to the other browser instance and to the desktop, even though settings sync is "off". now you've lost all of your settings.

This is because of the fact I mentioned above that all tabs share the settings as they are from same origin. For eg., if you do not have settings sync on in any tab and change the theme, this change will be reflected immediately in other tabs. This is not because of settings sync but because of user data shared across tabs.

Assigning to @bpasero regarding state change not getting signaled in other tabs

**Comment by bpasero** [comment] 2021-09-02 06:38
Works as designed, IndexDB does not support detecting changes, sorry: https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/storage/browser/storageService.ts#L184-L184

**Comment by bpasero** [comment] 2021-09-02 06:40
We could probably hack around it by writing some state into IndexDb and then constantly polling from other tabs, but it's a bit ugly. If the sentiment is that this is an OK limitation, I would leave it as is.

**Comment by sandy081** [comment] 2021-09-02 06:43
You are right that IndexDB does not support that. Instead of polling, I transmitted changes through localStorage which supports listening and hence cross tab settings changes are respected.

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/files/browser/indexedDBFileSystemProvider.ts#L233-L238

**Comment by bpasero** [comment] 2021-09-02 07:20
Oh, looks like these change events need the exact delta to work properly, otherwise we would have to iterate over all keys and read the value again. Not sure what is more performant...

**Comment by bpasero** [comment] 2021-09-06 12:08
I am using `BroadcastChannel` too now, but do not fallback to `localStorage`, so it may not work in iOS or Safari.

**Closed** 2021-09-06 12:07 UTC
Labels: workbench-state, web
