### ISSUE TITLE
when 2 vscode instance are open getting error "The connection to the terminal's pty host process is unresponsive, the terminals may stop working"

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#117542] opened 2021-02-24 04:53 UTC
Issue Type: <b>Bug</b>

Hi,

I am using insiders build and have 2 workspaces ( 1 angular and other react), after a most recent update (24 Feb 2021, 10:20 IST) I am getting the mentioned error when I open the 2 projects in separate instances.

![image](https://user-images.githubusercontent.com/9264813/108949414-63641580-768a-11eb-83b1-b537709ad80b.png)

VS Code version: Code - Insiders 1.54.0-insider (9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea, 2021-02-23T10:46:22.816Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.66GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.3
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.23.1
output-colorizer|IBM|0.1.2
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.14
vscode-typescript-next|ms-|4.3.20210223
vscode-typescript-tslint-plugin|ms-|1.3.3
cordova-tools|msj|2.2.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
vscode-commons|red|0.0.4
vscode-xml|red|0.15.0
vscode-yaml|red|0.15.0
sonarlint-vscode|Son|1.20.1
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscodeintellicode|Vis|1.2.11
glean|wix|5.1.1
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30260314
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoccf:30257852
vscoresta800cf:30263255

```

</details>

**Comment by Tyriar** [comment] 2021-02-25 17:04
@sanket-bhalerao  can you try again on latest? We did a lot of fixes around this yesterday.

**Comment by sanket-bhalerao** [comment] 2021-02-26 09:05
@Tyriar , after the latest install i am not able to replicate the issue. i would like to observe this at least today and tomorrow if its okay with you.

**Comment by Tyriar** [comment] 2021-02-26 14:03
I'll close it for now as I believe it's fixed. Let us know if you see it again

**Closed by Tyriar** 2021-02-26 14:03 UTC
Labels: needs more info

**Comment by vladi-strilets** [comment] 2021-02-28 17:40
@Tyriar, I'm getting the same error on 
```
Version: 1.54.0-insider (user setup)
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:39:10.253Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by donvanone** [comment] 2021-03-03 11:03
Same here:

```
Version: 1.54.0-insider (user setup)
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-02T19:09:10.315Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by Tyriar** [comment] 2021-03-03 15:24
@vladi-strilets @donvanone did you only see this happen when closing a window? You may be seeing this: https://github.com/microsoft/vscode/issues/117956

**Comment by hui0613** [comment] 2021-03-05 03:13
@Tyriar   I'm getting the same error on

I am developing a vscode extension program and need to use the terminal to start another exe process. When I execute the restart, it will execute vscode.commands.executeCommand("workbench.action.terminal.kill") and vscode.window.createTerminal({}), the above error will appear.
However, when I manually close the exe program and then execute vscode.window.createTerminal({}), there is no problem.

**Comment by vladi-strilets** [comment] 2021-03-05 08:15
@Tyriar, the error occurs as soon as I open the terminal, it goes blank (I can't even see the start line with my current project path). 

I had to install the normal Visual Studio Code (not Insiders) and with the same extensions, it works fine.

**Comment by zinderic** [comment] 2021-03-05 13:38
Same thing on MacOS too:

```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by MoisesGonzaga** [comment] 2021-03-05 14:27
I'm also getting the same error. 
I set up VS Code yesterday, installed it and I created a project without any issue. I closed my laptop and went home. Today that I wanted to continue working on the project, I'm getting the same error as my peers above. 

![image](https://user-images.githubusercontent.com/6610529/110128653-aa3dc380-7d8c-11eb-9395-9fc7a994a671.png)


```
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.719Z (15 hours ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Tyriar** [comment] 2021-03-05 14:59
Moving these to the recovery milestone which should mitigate the majority of these problems:

- https://github.com/microsoft/vscode/issues/117990
- https://github.com/microsoft/vscode/issues/117956

**Comment by violacambie** [comment] 2021-03-05 16:59
I have encountered the same "disconnection" problem soon after Visual Studio finished to update today.

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sanket-bhalerao** [comment] 2021-03-07 17:32
@Tyriar, I just opened a new empty folder and got this issue again.
![image](https://user-images.githubusercontent.com/9264813/110248537-b5187400-7f97-11eb-8bd0-487b02a3baf3.png)

I have the latest VSCode insiders build installed.
UPDATE: I restarted the VSCode instance in the same folder and the issue did not appear again for the same folder however, I am able to reproduce the issue every time I follow the below steps
1. select the "Open Folder" option from the menu 
2. create a new folder in the file chooser and name it something (ex: foo)
3. select the newly created folder and open it.
4. a popup "The connection to the terminal's pty host process is unresponsive, the terminals may stop working." appears every time.

**Comment by zinderic** [comment] 2021-03-08 11:03
It seems fixed in latest insider version:

```
Version: 1.55.0-insider (Universal)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:24:34.127Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

I was able to reproduce it with the version before that one. Now after the update it's running for few hours without seeing the error and the terminal is responsive.

**Comment by richardsimko** [comment] 2021-03-11 12:45
Version: 1.54.0
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (6 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Same issue when having 2 VS Code windows open

**Comment by pvogel1967** [comment] 2021-03-12 02:07
I get this error several times an hour at which point I have to open a new terminal to get anything done.  Truly broken.

Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by Temiloluwa-ade** [comment] 2021-03-12 10:48
I'm getting this same error on my Windows

**Comment by Tyriar** [comment] 2021-03-12 11:54
Please update to 1.54.2

**Comment by depeter** [comment] 2021-03-12 12:10
Same happens on 1.54.2 for me. I updated manually because this is bugging me immensely.

Version: 1.54.2 (system setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by astralstriker** [comment] 2021-03-13 08:54
Same error on 1.54.2 for me too

Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by zinderic** [comment] 2021-03-13 09:58
I would suggest to update to latest version:

```
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:09.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

At least on a Mac I've been running it for more than 24 hours without having any issues with my terminals or seeing the error message. It's working great.

**Comment by depeter** [comment] 2021-03-15 10:52
The problem is easily reproduceable on my machine.

In my case I am working on an electron - angular application and am running the electron app as an npm task.

```
Version: 1.54.2 (system setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

1. Start a long running task defined in your package.json using Terminal > Run Task > select the long running task
2. Do this another time. A popup will ask you to restart the task: click restart
3. The task starts running but the original running task is never terminated
4. A bit later you'll get the notification: "The connection to the terminal's pty host process is unresponsive, the terminals may stop working."

**Comment by Tyriar** [comment] 2021-03-15 12:17
@zinderic any more info on a repro would be helpful. Also if you could [try out insiders](http://code.visualstudio.com/insiders) the situation might be better there.

> Do this another time. A popup will ask you to restart the task: click restart

@depeter this was an issue before though, it caused all VS Code windows to hang because of https://github.com/microsoft/vscode/issues/71966. The pty host situation improved that by only breaking the terminals (in all windows) with an option to restart and recover. That's the only known valid reason for the popup.

**Comment by zinderic** [comment] 2021-03-16 06:51
I'm running MacOS Big Sur and I see a significant improvement with version 1.54.2. Before that version the issue was happening pretty much all the time especially when I run long lasting processes in the terminal such as docker-compose or code compilation.

Currently the only way I am able to reproduce the problem is by starting my Time Machine backup. I had to stop it from running automatically because I noticed that it was somehow triggering the problem. Now I'm running it manually on the evening when I close VS Code and that's how I workaround the problem.

I just updated my insider version to this one:

```
Version: 1.55.0-insider (Universal)
Commit: 84fe402d655e029eb1a5c04e675bf64788fa7fcf
Date: 2021-03-15T08:13:06.179Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

I started the backup and the problem did reproduce on both - the insider and the normal versions. They were both running at the time.

**Comment by Tyriar** [comment] 2021-03-16 14:52
@zinderic for macOS 1.54.2 brought in changes to recover when the pty host was unresponsive for some reason (waking from suspend or something) but has since recovered which I'm guessing was the main improvement for you. Interesting that the backup mechanism interacts with this, created https://github.com/microsoft/vscode/issues/119090. I'm interested if it recovers and the notification goes away after a minute or it's just totally broken and you can't create new terminals anymore after that.

**Comment by zinderic** [comment] 2021-03-16 16:42
Totally broken I'm afraid - frozen terminal with no way of creating new ones. Let me do some more testing and I'll update https://github.com/microsoft/vscode/issues/119090 with my findings.

**Comment by florentin** [comment] 2021-03-17 10:30
The nodejs version might play a role in this. I've downgraded from latest (15.11.0) to 14.16.0 and these 'pty host problems' seems to have gone away.

**Comment by adamdehaven** [comment] 2021-03-19 16:51
Issue is still present in `1.54.3 (user setup)` on Windows_NT x64

**Comment by alessandronocera89** [comment] 2021-03-22 08:23
Hi guys,
issue still present in:

`Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (6 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0`

when 1 or 2 (or more) vscode instances are opened. 

Catalina (not upgrading to Big Sure yet).

**Comment by FacePalmDev** [comment] 2021-03-22 09:39
I'm getting this issue in 1.54.3

**Comment by sanket-bhalerao** [comment] 2021-03-22 09:44
@Tyriar i started getting this again.

**Comment by Tyriar** [comment] 2021-03-22 11:29
@sanket-bhalerao some improvements have been made in Insiders for the following version if you want to try that out https://code.visualstudio.com/insiders, it's expected that this will still happen when a Time Machine backup is triggered on mac (https://github.com/microsoft/vscode/issues/119090) or when you trigger the hang on Windows by closing a terminal that was having data written (https://github.com/microsoft/vscode/issues/71966).

If anyone sees this again on v1.55+ outside of the above cases, please create a new issue.
