### ISSUE TITLE
Pass `config.name` to Docker `run` command

### ISSUE THREAD

**Issue by Tbhesswebber** [microsoft/vscode#117142] opened 2021-02-20 18:05 UTC
It's not uncommon to want run additional commands within the devcontainer from terminals that may or may not be the integrated terminal.

Currently, in order to have an intuitive name for containers, you have to include `"runArgs": ["--name=<name>"]`in your config when there is already a `name` property.  It seems as though it would be sensible to default the name of the remote container to that of `config.name`.'

**Example**
I have a monorepo with 5 libraries and 3 applications.  Rather than attempting to cram multiple integrated terminal windows onto the screen at one time, I have an iTerm arrangement that provides 9 panes.  From each pane, I want to run `docker exec -it <name> /bin/bash` so that I can run the tests and application for each application and the tests for each library, all in watch mode.

**Comment by chrmarti** [comment] 2021-03-03 09:55
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/2485.

**Closed by chrmarti** 2021-03-03 09:55 UTC
Labels: remote
