### ISSUE TITLE
Scroll handle is very hard to use while output is being printed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#180847] opened 2023-04-25 16:51 UTC
Testing #180761

Seems like each time we render, the drag handle on the scrollbar loses any mousedown'ed state. This makes it quite hard to use. Are we rendering something oddly?

https://user-images.githubusercontent.com/2230985/234347579-db2f5d21-68de-4aec-bd9f-8bdd8143c192.mp4

**Comment by amunger** [comment] 2023-04-25 19:52
the entire output is rendered on each update. duplicate of https://github.com/microsoft/vscode/issues/177721

**Closed by amunger** 2023-04-25 19:52 UTC
