### ISSUE TITLE
tsconfig.json - problems loading reference tsconfig.schema.json

### ISSUE THREAD

**Issue by temelj** [Microsoft/vscode#44782] opened 2018-03-01 00:26 UTC
Issue Type: <b>Bug</b>

Problems loading reference 'file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/typescript/schemas/tsconfig.schema.json': Unable to load schema from 'c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\typescript\schemas\tsconfig.schema.json': 

VS Code version: Code - Insiders 1.21.0-insider (3fec61014742dec894b3a31cdf8556bf533cb0e1, 2018-02-28T05:17:16.839Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.67GB (4.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
git-tree-compare|let|1.2.0
mssql|ms-|1.3.0
csharp|ms-|1.14.0
code-spell-checker|str|1.6.5

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-03-01 23:35
Duplicate of #44718

**Closed by mjbvz** 2018-03-01 23:35 UTC
Labels: insiders
