### ISSUE TITLE
Go test output in vscode 1.20 syntax highlighting

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#43271] opened 2018-02-09 01:08 UTC
_From @bryanl on February 8, 2018 15:11_

With 1.20 syntax highlighting in test output makes viewing unpleasant

![2018-02-08_10-11-38](https://user-images.githubusercontent.com/240/35980338-75b5f986-0cb8-11e8-89df-7317b52b7b8c.png)

_Copied from original issue: Microsoft/vscode-go#1501_

**Comment by ramya-rao-a** [comment] 2018-02-09 01:10
@sandy081 Shouldnt the syntax highlighting for logs be applied only to the output channels that get used for logs? In this case, the Go extension uses the output channel to show test output. Shouldnt syntax highlight be an opt-in to be controlled by the output channel creators?

**Comment by sandy081** [comment] 2018-02-09 09:19
By default all output channels get `log` as mode id, hence they get the syntax highlighting of logs. But I agree it's not pleasant. 

Duplicate of #42517

**Closed** 2018-02-09 09:19 UTC
Labels: *duplicate, output

**Comment by ramya-rao-a** [comment] 2018-02-09 19:21
@sandy081

> By default all output channels get log as mode id

Then we should probably allow extensions to change the mode id

**Comment by sandy081** [comment] 2018-02-22 09:51
Removing this as duplicate of #42517 as this is about colouring in regular output channels and the other one is about improving colouring in log output channels.

**Comment by sandy081** [comment] 2018-02-22 09:55
Since, some extensions do colouring for their channels, I am removing log syntax highlighting to the regular output channels. 

Log syntax highlighting is meant for log files/channels and since not all output channels are not really logs and they can contain any content. So, providing log syntax highlighting to them could be error prone (like this issue). Hence, removing syntax highlighting for regular output channels and retained only for vscode log channels.

@isidorn FYI

**Comment by rdumont** [comment] 2018-02-22 20:06
Thank you, @sandy081! :)
