### ISSUE TITLE
Weird Formatting after save

### ISSUE THREAD

**Issue by julia-dizhak** [Microsoft/vscode#72799] opened 2019-04-24 09:54 UTC
VSCode Version: Version 1.33.1 (1.33.1)
OS Version: mac

Steps to Reproduce:
1 change files
2 format is changing after auto save 

Does this issue occur when all extensions are disabled?: Yes
I switched off all extensions and it still occurs.

I have video recording as well and can send.

**Comment by julia-dizhak** [comment] 2019-04-24 10:01
Only what helps me, it's removing VS code and install again (as well as all settings and extensions)

**Comment by jrieken** [comment] 2019-04-24 10:20
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by julia-dizhak** [comment] 2019-04-26 14:29
Hm, what is not enough in my description? 
I can't attach file here, it's only possible with the file size 10MB

**Comment by jrieken** [comment] 2019-04-26 14:39
> Hm, what is not enough in my description?

It's perfect because it doesn't specific and name anything. I selfhost on format-on-save with TypeScript using the default TS formatter, works just the way I want. That means I can close this issue because it's not reproducible, I can optionally also point to a random commit if you like. 

Alternatively you put yourself into my shoes, you open an empty project, and you provide **reproducible** steps from there

**Comment by julia-dizhak** [comment] 2019-04-29 08:31
Okay, I hope it will help with screenshots

1. Open any .js file (attach file action-1.png)
<img width="1698" alt="action-1" src="https://user-images.githubusercontent.com/1140769/56884324-b9a1a680-6a69-11e9-9a1a-bf63489a350b.png">

2. It's enough putting just spacing
<img width="1666" alt="action-2" src="https://user-images.githubusercontent.com/1140769/56884325-b9a1a680-6a69-11e9-94a1-9ee3322ebda2.png">

3. New weird formatter applied
<img width="1686" alt="action-3" src="https://user-images.githubusercontent.com/1140769/56884326-b9a1a680-6a69-11e9-80e3-29f91af79f78.png">

All reproducible with all disable extensions.

**Comment by jrieken** [comment] 2019-04-29 08:40
> The problem is reproducible with disable extensions.

There are six extensions enabled, one of them is a formatter. Try reproduce without extensions enabled

**Comment by jrieken** [comment] 2019-05-06 12:28
no actionable information provided

**Closed by jrieken** 2019-05-06 12:28 UTC
Labels: needs more info

**Comment by julia-dizhak** [comment] 2019-05-08 08:44
It seems the reason is a Prettier extension. After disabling and reloading VS code, the issue is gone. Thanks
