### ISSUE TITLE
negated regex with positive lookbehind inside parentheses breaks highlighting

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#92694] opened 2020-03-14 15:15 UTC
```javascript
const x = 0
;/\n/g.test(x)
if (!/(?<=a)bc/.test(x)) {
    const x = 0
    ;/\n/g.test(x)
}
```
![Code_2020-03-14_16-08-47](https://user-images.githubusercontent.com/30108880/76684682-4287e900-660e-11ea-87e0-6249a99489cb.png)

1.43

it has issues coloring `const`, `export` and I think class methods but it will not break everything right away, I did not manage to find what but combining this with some specific regex or template literal further in the file eventually breaks it completely

possibly related to https://github.com/microsoft/TypeScript-TmLanguage/issues/809

**Comment by gjsjohnmurray** [comment] 2020-03-14 20:57
Looks like this is the same as https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Comment by pushkine** [comment] 2020-03-15 11:04
actually the bug happens with any regex that includes a `?` as long as it is preceded by a `!`
```
!/x?/
```

**Comment by mjbvz** [comment] 2020-03-16 17:01
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-03-16 17:01 UTC
