### ISSUE TITLE
Linux - Minimap scrambles on return from suspend

### ISSUE THREAD

**Issue by rodan123** [microsoft/vscode#111334] opened 2020-11-26 01:09 UTC
Issue Type: <b>Bug</b>

1) Open VSCode and load file, showing minimap.
2) Put computer in suspend mode.
3) Return from suspend to find minimap showing "television snow" a dense field of colored dots

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 4.9.240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.33GB (25.01GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
expect|bda|0.1.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
cpptools|ms-|1.1.2

</details>

**Comment by yume-chan** [comment] 2020-11-27 07:28
Duplicate of #69665

You can try the solution in https://github.com/microsoft/vscode/issues/69665#issuecomment-716758361 (can't guarantee to work)

**Comment by alexdima** [comment] 2020-11-27 07:35
Lets' track in #69665

**Closed by alexdima** 2020-11-27 07:35 UTC
