### ISSUE TITLE
Cannot open folder

### ISSUE THREAD

**Issue by JungeWerther** [microsoft/vscode#230688] opened 2024-10-07 09:26 UTC
Type: <b>Bug</b>

Any time I want to open a new folder (like new workspace ctrl-shift-p -> open folder), vscode crashes. Even after update. Never had this before.. also after reboot pc.

VS Code version: Code - Insiders 1.95.0-insider (0ca72abae2123195125c9809525eb07f63da0e53, 2024-10-07T05:03:51.952Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 799)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|4, 3, 2|
|Memory (System)|31.05GB (25.00GB free)|
|Process Argv|--no-sandbox --force-user-env|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|den|3.41.0
copilot|Git|1.235.1137
copilot-chat|Git|0.22.2024100701
vscode-github-actions|git|0.27.0
mdmath|goe|2.7.4
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.11.2024092501
python|ms-|2024.17.2024100401
vscode-pylance|ms-|2024.9.104
jupyter|ms-|2024.10.2024100401
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vim|vsc|1.28.1

</details>

**Comment by JungeWerther** [comment] 2024-10-07 09:31
I'll also add logs here (from `code --verbose` in terminal)

```
[main 2024-10-07T09:29:06.130Z] [DialogMainService]: request to acquire file dialog lock {
  title: 'Open Folder',
  buttonLabel: undefined,
  filters: undefined,
  defaultPath: '<redacted>',
  properties: [ 'multiSelections', 'openDirectory', 'createDirectory' ]
}
[main 2024-10-07T09:29:06.130Z] [DialogMainService]: new file dialog lock created {
  title: 'Open Folder',
  buttonLabel: undefined,
  filters: undefined,
  defaultPath: '<redacted>',
  properties: [ 'multiSelections', 'openDirectory', 'createDirectory' ]
}
[48807:1007/102906.270607:INFO:CONSOLE(35)] "%cDEBUG background: #eee; color: #888 Comments: URIs of continue on comments to add to storage .", source: vscode-file://vscode-app/snap/code-insiders/1758/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (35)
[48807:1007/102906.270864:INFO:CONSOLE(35)] "%cTRACE color: #888 ChatService#constructor: Restored 3 persisted sessions", source: vscode-file://vscode-app/snap/code-insiders/1758/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (35)
```

after that the process just ends.

**Comment by gjsjohnmurray** [comment] 2024-10-07 10:15
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-07 10:16 UTC
Labels: *duplicate, triage-needed
