### ISSUE TITLE
Feature request: Allow custom .vscode directory name

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/vscode#41139] opened 2018-01-04 11:10 UTC
## Suggestion

I would like to request for the ability to set custom folder name to store workspace-specific editor options, canonically stored under a folder named `.vscode` in `${workspaceRoot}`.

## Gains

The sheer awesome it would enable [now that VS Code opens from within WSL](https://github.com/Microsoft/vscode/issues/13138) (on Insider builds starting from 17063) is that one could have side-by-side debugging of the very same source tree opened from Windows VS Code with Windows dependencies and WSL with native Linux dependencies.

## Current behavior

The problem with the hardcoded `${workspaceRoot}/.vscode` is that I cannot set different settings for my Linux and my Windows editor instance which is required to find dependencies (CMake configure params for eg.) on the respective platforms. If I could set `.vscode-win` and `.vscode-wsl` respectively, as global settings for the Win and WSL variants, workspace-specific settings would not collide.

**Comment by sandy081** [comment] 2018-01-08 11:34
Duplicate of #851

**Closed** 2018-01-08 11:34 UTC
Labels: *duplicate, config
