### ISSUE TITLE
User launch.json does not work

### ISSUE THREAD

**Issue by iybaron** [Microsoft/vscode#43273] opened 2018-02-09 01:29 UTC
- VSCode Version: 1.20.0
- OS Version: macOS Sierra 10.12.6

After updating to VSCode 1.20.0, I tried to run my debugger, but got a "'launch.json' does not exist" error. I have the following configuration in my 'User Settings' file:
```
"launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Mocha",
                "program": "${workspaceFolder}/node_modules/.bin/gulp",
                "args": [
                    "mocha"
                ],
                "internalConsoleOptions": "openOnSessionStart"
            }
        ]
    }
```
The same error is found in all my projects. I tried creating a 'launch.json' file, but got the same result.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kongsea** [comment] 2018-02-09 02:11
I encountered the same error as you.
Please fix it as soon as possible.

**Comment by matthewlein** [comment] 2018-02-09 15:12
As a workaround: copy launch config into launch.json, comment out launch config in user settings, and quitting/relaunch gets you running again.

**Comment by Kongsea** [comment] 2018-02-11 03:09
@matthewlein Yes, now it works.
I add launch config to user.settings before:

>     "launch": {
>         "version": "0.2.0",
>         "configurations": [
>             {
>                 "type": "python",
>                 "request": "launch",
>                 "name": "Python",
>                 "program": "${file}"
>             }
>         ]
>     },

When I deleted, it works now.

**Comment by isidorn** [comment] 2018-02-13 10:28
Duplicate of https://github.com/Microsoft/vscode/issues/43461
As explained in that issue
"
The fix will be in vscode insiders tomorrow. I understand this is breaking behavior compared to our stable, however the fix is a bit tricky and I speculate that the number of users depending on this feature are quite small, thus I decided to not make this a candidate (even though it is a regression). Users depedning on this feature can use the insiders from tomorrow
"

So please try the latest vscode insiders and let me know if that fixes the issue.
Apart from that I am now investigating into a minimal fix to push as a candidate release.

**Closed** 2018-02-13 14:12 UTC
Labels: candidate, debug

**Comment by isidorn** [comment] 2018-02-13 14:13
This issue will be fixed in the stable recovery release.

Verifier check:
1. You can debug in a no folder workspace
2. You can debug using a user launch json in a single folder workspace
3. You can debug in a multi folder workspace using multi folder compounds

Note that user settings are not support in mulit folder workspace(this was behavior in the previous stable) and this will be fixed in the next stable release.

**Comment by nbara** [comment] 2018-02-14 10:41
FWIW the current Insiders build does not solve this issue for me. 

I work in a single folder workspace, and have all my launch options set up in my user preferences. I get this overtime I enter debug mode : 

`Failed to launch the Python Process, please validate the path '/path/to/anaconda3/envs/py3/bin/python'`

**Comment by isidorn** [comment] 2018-02-14 10:48
@nbara that is an unrelated issue. You can file it against the python extension, or find more details here https://github.com/Microsoft/vscode/issues/43303
