### ISSUE TITLE
Keybinding for opening files when navigating sidebar?

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [Microsoft/vscode#18412] opened 2017-01-11 19:15 UTC
Thanks Microsoft for this great editor!

This is a feature request based on [issue 28 @vscode-tips-and-tricks](https://github.com/Microsoft/vscode-tips-and-tricks/issues/28).

One can access the sidebar/explorer with `cmd+shift+e` on mac. But how to open a file from there or say, jump into that file?
`ctrl+enter` only opens it to the side.
just `enter` is used to rename the file…

I haven’t seen any keybinding reference in the keybindings.json.
@waderyan answered that this is not possible yet.

So, please implement it.
To use `space` would be a good idea (currently space only open/collapse folders)

Thank you.

**Comment by waderyan** [comment] 2017-01-11 19:18
I think I found the issue. @bpasero this is likely a duplicate of this issue correct? https://github.com/Microsoft/vscode/issues/4557

**Comment by roblourens** [comment] 2017-01-11 19:34
cmd+down is the shortcut on Mac, same shortcut as in Finder.

**Comment by mjbvz** [comment] 2017-01-11 23:16
Yes, this looks like a duplicate of #4557

**Closed by mjbvz** 2017-01-11 23:16 UTC
Labels: duplicate, question

**Comment by ThibaultJanBeyer** [comment] 2017-03-31 09:44
am I right that cmd+down is not working anymore?

**Comment by thinkxl** [comment] 2017-06-28 00:20
cmd+enter works for me
