### ISSUE TITLE
PHP Multi line comment leaking into entire file

### ISSUE THREAD

**Issue by davidteofilovic** [Microsoft/vscode#32500] opened 2017-08-14 18:30 UTC
- VSCode Version: Version 1.15.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open a new PHP file
2. Write a simple one line function
3. Write a multi-line comment above it Using the  /** */ format.
4. Describe a parameter using the @param (TYPE) paradigm.

By doing this, the comment highlighting will leak and incorrectly highlight the rest of the file.

Reproduces without extensions: Yes

Example of the issue
<img width="595" alt="screen shot 2017-08-14 at 11 26 26 am" src="https://user-images.githubusercontent.com/368981/29285607-d9d2be38-80e3-11e7-97aa-58395aa916b9.png">

Example without parenthesis 
<img width="478" alt="screen shot 2017-08-14 at 11 26 50 am" src="https://user-images.githubusercontent.com/368981/29285612-df2db464-80e3-11e7-9e8f-abfd28cfaac3.png">

**Comment by aeschli** [comment] 2017-08-14 20:10
@davidteofilovic Can you paste the example code?

**Comment by davidteofilovic** [comment] 2017-08-14 20:21
```php
/**
* @param (int) number that will be printed
*
*/
function foo($num) {
    echo $num;
}


function bar($num) {
    echo "Why is this commented out";
}
```

**Comment by roblourens** [comment] 2017-08-14 20:33
The problem is the space after the `@param`, which you can remove as a workaround. Filed an issue for this upstream: https://github.com/atom/language-php/issues/256

**Comment by roblourens** [comment] 2017-08-14 23:41
Actually, this is already fixed upstream and will be fixed in the next Insiders build.

**Closed by roblourens** 2017-08-14 23:41 UTC
Labels: new release, php, upstream
