### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Coachware-Admin** [microsoft/vscode#94571] opened 2020-04-06 21:08 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (tsserver.js:98134:22)
    at Object.createProgram (tsserver.js:97765:30)
    at synchronizeHostData (tsserver.js:135218:26)
    at Proxy.getProgram (tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (tsserver.js:140654:63)
    at updateProjectIfDirty (tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143114:29)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (b0791e5236f462fbb785e9a00319705607cefb9d, 2020-03-10T11:17:54.705Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 7|
|Memory (System)|16.00GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Coachware API Dev Contai…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|1.94GB (0.47GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.0.0
remote-containers|ms-|0.110.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-jest|Ort|3.1.1
sort-lines|Tyr|1.9.0

</details>

**Comment by RMacfarlane** [comment] 2020-04-06 21:18
Duplicate of https://github.com/microsoft/TypeScript/issues/37355

**Closed by RMacfarlane** 2020-04-06 21:18 UTC
