### ISSUE TITLE
Menu: we need some kind of overflow behaviour when the menu is large

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52924] opened 2018-06-26 10:32 UTC
Refs: #52854

Steps:
* make the window small
* expand the "View" menu
* 🐛 it is not possible to reach most of the items

![image](https://user-images.githubusercontent.com/900690/41905961-f0c0f1ee-793c-11e8-867b-76d41583e804.png)

The native menu solves this a bit better by just going out of the window. I think we could also think about a scrollbar instead.

**Comment by sbatten** [comment] 2018-07-03 22:10
dupe of #52533

**Closed by sbatten** 2018-07-03 22:10 UTC
Labels: bug, workbench-menu
