### ISSUE TITLE
Import from is incomplete/cut in Suggest Window

### ISSUE THREAD

**Issue by jsanchez-softdepot** [microsoft/vscode#91616] opened 2020-02-26 22:07 UTC
When a library has a class or constant with a long name, the source of the class (at the right) gets cut in the suggest window so it's impossible to know from where I'm importing the component.

Many react libraries use the same component names (like Button) and it's important to know the source library of the suggestion for the auto import functionality.

![vscode-suggest](https://user-images.githubusercontent.com/59839466/75392644-13554600-58b2-11ea-86df-069550b18c06.png)

STEPS TO REPRODUCE:
1. Create a react native project.
2. Add a library or package with a long-name component, such as react-native-screens (which has ScreenStackHeaderBackButtonImage)
3. Write a component name in a the component render function.

RESULT:
The suggest window will show the name of the functions/components/constants and if there is a long one, such as ScreenStackHeaderBackButtonImage, the source module/library/file will be cut off at the right.

EXPECTED RESULT:
The suggest windows should show the full name of the source module/library/file so I know where i'm importing from.

**Comment by IllusionMH** [comment] 2020-02-27 02:44
/duplicate of #29757 , #29126 and may other.

In meantime just hit <kbd>Ctrl</kbd>+<kbd>Space</kbd> again or hover over suggestion with mouse and click on ⓘ (Read more... button) to see detailed description of an item which displays full auto-import message.

**Closed** 2020-02-27 02:44 UTC
Labels: *duplicate
