### ISSUE TITLE
'Source Control' commit message input some time block

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#113297] opened 2020-12-22 15:20 UTC
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. I don't know how exactly reproduce this issue
2. Some time I just type text in input, input block, I have made a gif
![Kapture 2020-12-22 at 21 40 01](https://user-images.githubusercontent.com/20318608/102903384-3a1ce280-44ab-11eb-8ef6-021ffb048a34.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by susiwen8** [comment] 2020-12-23 06:02
Follow up
![Kapture 2020-12-23 at 14 00 54](https://user-images.githubusercontent.com/20318608/102964789-6d04bc00-4527-11eb-904c-94234d57db4d.gif)
Can't delete 'Fix:'

**Comment by fureweb-com** [comment] 2020-12-23 15:34
I have the same problem.

**Comment by eamodio** [comment] 2021-01-05 06:14
Duplicate of #112621

**Closed by eamodio** 2021-01-05 06:14 UTC
