### ISSUE TITLE
Opening attached main.js crashes VS Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39126] opened 2017-11-25 09:53 UTC
Steps to Reproduce:

1. open our very own [main.js.zip](https://github.com/Microsoft/vscode/files/1502957/main.js.zip) in editor
2. renderer freezes and eventually crashes

I think this is related to JS coloring because it did not crash when I just opened the file. 

/cc @alexandrudima @rebornix

**Comment by mjbvz** [comment] 2017-11-27 19:20
The file seems to trigger high cpu usage in the renderer process. Will try tracking down which line causes it to fail

**Comment by mjbvz** [comment] 2017-11-27 19:24
Seems to hang on line 58: 

```
}(),s=function(e){function t(){return e.call(this,[t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),"-",t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),"-","4",t._randomHex(),t._randomHex(),t._randomHex(),"-",t._oneOf(t._timeHighBits),t._randomHex(),t._randomHex(),t._randomHex(),"-",t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex(),t._randomHex()].join(""))||this}return n(t,e),t._oneOf=function(e){return e[Math.floor(e.length*Math.random())]},t._randomHex=function(){return t._oneOf(t._chars)},t._chars=["0","1","2","3","4","5","6","6","7","8","9","a","b","c","d","e","f"],t._timeHighBits=["8","9","a","b"],t}(o);t.v4=r;var a=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;t.isUUID=i,t.parse=function(e){if(!i(e))throw new Error("invalid uuid");return new o(e)},t.generateUuid=function(){
```

**Comment by aeschli** [comment] 2018-01-29 11:28
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/567

**Closed by aeschli** 2018-01-29 11:28 UTC
Labels: bug, freeze-slow-crash, grammar, javascript
