### ISSUE TITLE
Wrong IntelliSense with `chalk` package

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25187] opened 2017-04-22 11:06 UTC
- VSCode Version: 1.11.2
- OS Version: Linux Ubuntu 16.04

I'm using `chalk` package and I found if my variable is for e.g. `string`, I get these suggestions.

![screenshot from 2017-04-22 14-02-44](https://cloud.githubusercontent.com/assets/10441177/25303883/b133de68-2764-11e7-9be7-cf009ef4f133.png)

As you can see in picture I get mixed suggestions with `chalk` i. e. `bgRed` and with normal JS suggestions i. e. `charAt`, I don't know how but they mixed and it's bad, because it's impossible to use these properties/functions in strings. **I also noticed it's the same in TypeScript files, not only JS files.** VS Code need to provide only built-in functions.

My `jsconfig.json`:
```
{
  // Specifies a list of files to be excluded.
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

P.S. As I said this happens to TypeScript files also.

**Comment by mjbvz** [comment] 2017-04-24 21:47
I'm unable to reproduce this with `chalk` and `@types/chalk` installed using the code:

```js
import chalk from 'chalk'

var a = ''
a.|
```

When you hover over `config.hostname`, what is its type? Can you provide small code sample that demonstrates this issue

**Comment by svipben** [comment] 2017-04-24 21:52
@mjbvz I didn't tested it with `@types/chalk` as far as I remember. You can test it also with JS files, because it was the first time I discovered the problem and it still exists.

`(property) hostname: string`

Tested with `@types/chalk` and problem gone, but it's only if you're using TS and you have `@types/chalk`, but what about JS?

**Comment by mjbvz** [comment] 2017-04-24 21:58
Ok, what does it say if you hover over `'chalk'` in `import chalk from 'chalk'`?

**Comment by svipben** [comment] 2017-04-24 22:09
@mjbvz 
When I was testing with `types@chalk` they both use it from project `node_modules`, after I deleted `node_modules/@types` they are now using this:

In JS/TS: `module "/home/svipben/.cache/typescript/node_modules/@types/chalk/index"`

I deleted that `.cache/typescript` and it was created automatically, so I think it's generated by VS Code automatically.

**Comment by mjbvz** [comment] 2017-04-24 22:14
Yes, we use `@types/chalk` to power our intellisense (see [this documentaiton for more info](https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition)). The `d.ts` file doesn't mention anything about extending the string prototype though.

Can you set `	"typescript.tsserver.trace": "verbose"` in your user settings and try triggering the completions for `config.hostname.`. Then open the output panel and share the output for the TypeScript section. The request of interest here is `completions`

**Comment by svipben** [comment] 2017-04-24 22:19
@mjbvz

```
[Trace - 1:18:25 AM] Sending request: open (275). Response expected: no. Current queue length: 0
Arguments: {
    "file": "/home/svipben/Documents/react-boilerplate/test.js",
    "fileContent": "const chalk = require('chalk');\n\nconst a = '';\na.",
    "scriptKindName": "JS"
}
[Trace - 1:18:25 AM] Event received: configFileDiag (0).
Data: {
    "triggerFile": "/home/svipben/Documents/react-boilerplate/test.js",
    "configFile": "/home/svipben/Documents/react-boilerplate/jsconfig.json",
    "diagnostics": []
}
[Trace - 1:18:25 AM] Sending request: navtree (276). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/svipben/Documents/react-boilerplate/test.js"
}
[Trace - 1:18:25 AM] Response received: navtree (276). Request took 15 ms. Success: true 
Result: {
    "text": "<global>",
    "kind": "script",
    "kindModifiers": "",
    "spans": [
        {
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 4,
                "offset": 3
            }
        }
    ],
    "childItems": [
        {
            "text": "a",
            "kind": "const",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 3,
                        "offset": 7
                    },
                    "end": {
                        "line": 3,
                        "offset": 13
                    }
                }
            ]
        },
        {
            "text": "chalk",
            "kind": "const",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 1,
                        "offset": 7
                    },
                    "end": {
                        "line": 1,
                        "offset": 31
                    }
                }
            ]
        }
    ]
}
[Trace - 1:18:25 AM] Sending request: navtree (277). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/svipben/Documents/react-boilerplate/test.js"
}
[Trace - 1:18:25 AM] Response received: navtree (277). Request took 17 ms. Success: true 
Result: {
    "text": "<global>",
    "kind": "script",
    "kindModifiers": "",
    "spans": [
        {
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 4,
                "offset": 3
            }
        }
    ],
    "childItems": [
        {
            "text": "a",
            "kind": "const",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 3,
                        "offset": 7
                    },
                    "end": {
                        "line": 3,
                        "offset": 13
                    }
                }
            ]
        },
        {
            "text": "chalk",
            "kind": "const",
            "kindModifiers": "",
            "spans": [
                {
                    "start": {
                        "line": 1,
                        "offset": 7
                    },
                    "end": {
                        "line": 1,
                        "offset": 31
                    }
                }
            ]
        }
    ]
}
[Trace - 1:18:33 AM] Sending request: completions (278). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/svipben/Documents/react-boilerplate/test.js",
    "line": 4,
    "offset": 3
}
[Trace - 1:18:33 AM] Response received: completions (278). Request took 59 ms. Success: true 
Result: [
    {
        "name": "a",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    },
    {
        "name": "america",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "at",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgBlack",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgBlue",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgCyan",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgGreen",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgMagenta",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgRed",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgWhite",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bgYellow",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "black",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "blue",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "bold",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "chalk",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    },
    {
        "name": "charAt",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "charCodeAt",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "concat",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "cyan",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "dim",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "escapeHTML",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "gray",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "green",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "grey",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "hidden",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "indexOf",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "inverse",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "italic",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "lastIndexOf",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "length",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "localeCompare",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "magenta",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "match",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "rainbow",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "random",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "red",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "replace",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "require",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    },
    {
        "name": "reset",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "search",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "slice",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "split",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "strikethrough",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "strip",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "stripColors",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "substr",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "substring",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "toLocaleLowerCase",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "toLocaleUpperCase",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "toLowerCase",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "toString",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "toUpperCase",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "trap",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "trim",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "underline",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "unescapeHTML",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "valueOf",
        "kind": "method",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "white",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "yellow",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "zalgo",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "zebra",
        "kind": "property",
        "kindModifiers": "declare",
        "sortText": "0"
    }
]
```

**Comment by mjbvz** [comment] 2017-04-24 22:36
These extra types come from `Colors.js` as shown by:

```
require('colors'); 
const a = 'abc'; 
console.log(a.red);
```

`colors` does add globals to `String.prototype` but these suggestions are only valid when `colors` has been imported. They should not be shown normally IMO. I've opened https://github.com/Microsoft/TypeScript/issues/15359 to track this on the TypeScript side

Closing as upstream

**Closed by mjbvz** 2017-04-24 22:36 UTC
Labels: javascript, typescript, upstream

**Comment by svipben** [comment] 2017-04-24 22:37
@mjbvz Thank you very much! :+1:
