### ISSUE TITLE
TypeScript intellisense broken

### ISSUE THREAD

**Issue by johanbaath** [microsoft/vscode#78376] opened 2019-08-02 10:58 UTC
- VSCode Version: 1.36.1
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Open up a particular TypeScript project
2. Intellisense doesn't work

Does this issue occur when all extensions are disabled?: Yes

I tried the same project in VSCode Insiders with a clean install and no extensions as well. Tried different TypeScript versions as well.

This is the output:

```
[2019-08-02 12:55:15.862] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-08-02 12:55:15.862] [exthost] [error] Error: <main> TypeScript Server Error (3.5.2)
Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:2080:24)
    at getDefaultExportInfoWorker (tsserver.js:115542:80)
    at getDefaultLikeExportInfo (tsserver.js:115523:24)
    at tsserver.js:115320:35
    at forEachExternalModule (tsserver.js:115663:21)
    at getAllReExportingModules (tsserver.js:115315:13)
    at Object.getImportCompletionAction (tsserver.js:115301:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:99848:33)
    at Object.getCompletionEntryDetails (tsserver.js:99812:30)
    at Object.getCompletionEntryDetails (tsserver.js:122110:35)
    at tsserver.js:131177:57
    at Object.mapDefined (tsserver.js:670:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:131175:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130106:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63436)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56618)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55516)
	at constructor._reader.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:54992)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:468)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61656)
	at Socket.t.Reader.constructor.e.on.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61304)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

If I remove the `node_modules` folder Intellisense starts working again (for this particular project). I'm not sure on how to debug this further, any suggestions? It seems it crashes when it's parsing/loading some file in `node_modules` but I'm not sure.

**Comment by emrecamasuvi** [comment] 2019-08-08 07:44
In my case;
- VS code Version: 1.36.1 (1.36.1)
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:
1. Open up a non-typescript project
2. `clg` does not autocomplete to `console.log()`

Output was like:
`[renderer1] [error] <main> TypeScript Server Error (3.5.2)`

This may be subject to another issue but after reading @johanbaath 's comment about removing `node_modules`; I did the same and removed `node_modules` in `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features` and `npm install` again; problem solved.

**Comment by mjbvz** [comment] 2019-08-11 09:55
Duplicate of https://github.com/microsoft/TypeScript/issues/31465 based on callstack

**Closed by mjbvz** 2019-08-11 09:55 UTC
