### ISSUE TITLE
Colored outputs being unreadable in text editor

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/vscode#156969] opened 2022-08-03 03:14 UTC
When I open a truncated colored output in text editor I got a json format output with encoded characters instead of texts that I'm interested in.
I understand this is technically not a bug, but this do prevent me from inspecting what's going on with my code.

For example, in the following scenario, I have difficulty reading the full traceback

![image](https://user-images.githubusercontent.com/14952735/182515225-299dec0f-aa55-420a-b7b9-0df822c81fee.png)
![image](https://user-images.githubusercontent.com/14952735/182516442-94cff9c5-014f-407c-81b5-5361ab77b949.png)

**Comment by samedii** [comment] 2022-11-12 21:48
Duplicate of https://github.com/microsoft/vscode/issues/153839

**Closed** 2022-12-02 19:49 UTC
Labels: polish, notebook-output
