### ISSUE TITLE
typing dash changes terminal rendering

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#9902] opened 2016-07-28 14:36 UTC
macOS, lastest insider, 6ef86d5f85a531caa59bfb1715469fcfaa8d2efd

![jul-28-2016 16-36-30](https://cloud.githubusercontent.com/assets/1794099/17216564/78141bb2-54e1-11e6-885a-e9a7b1fee44e.gif)

**Comment by Tyriar** [comment] 2016-07-28 17:47
I can't reproduce... What font is that? It's different to the default one on my machine which seems to be `Menlo`.

**Comment by rogersachan** [comment] 2016-07-28 18:22
@Tyriar That looks like the default font for Terminal on macOS to me, although I may be wrong.

**Comment by Tyriar** [comment] 2016-07-28 18:28
@rogersachan I compared the 'j' character against mine which I barely use and it definitely looks different. You should be able to check the font in devtools (Help > Toggle Developer Tools). I verified which font it was by removing the first one from the `font-family` list and see if it changed.

**Comment by jrieken** [comment] 2016-07-29 07:52
@Tyriar I use `Fira Code` in the editor and see that its also used for the terminal

**Comment by jrieken** [comment] 2016-07-29 08:40
@Tyriar I believe some resizing is part of this... So, usually the first time things are looking ok, then I resize the window/terminal and start seeing this

**Comment by Tyriar** [comment] 2016-07-29 18:31
Could not repro using Fira Code myself, removing important and from milestone as it's likely related to one of the existing resize issues.

**Comment by vekerdyb** [comment] 2016-08-03 09:23
The same thing happens on Fedora 24, e6b4afa53e9c0f54edef1673de9001e9f0f547ae

**Comment by Tyriar** [comment] 2016-08-04 00:22
@vekerdyb are you using Fire Code and did it happen with the `-` character as well?

**Comment by Tyriar** [comment] 2016-08-12 14:40
I managed to repro this on Fedora in v1.4.0 and the same repro didn't work on v1.5.0 Insiders so I'm closing this off as fixed from the row height-related work that was done while adding the scroll bar. :tada:

**Closed by Tyriar** 2016-08-12 14:40 UTC
Labels: bug, integrated-terminal
