### ISSUE TITLE
Copying a selection across multiple filtered settings includes extraneous text

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#16349] opened 2016-12-01 23:45 UTC
- VSCode Version: branch `sandy081/exploreConfiguration`
- OS Version: macOS

Steps to Reproduce:

1. In settings, filter by some text string in the filter box, for example "Save"
2. Select text across multiple settings that show up in this filtered mode
3. Copy to the clipboard and paste somewhere to examine.
4. Note that the copied text can include text that appeared to never be in the selection.

This was my selection:
![screen shot 2016-12-01 at 3 38 55 pm](https://cloud.githubusercontent.com/assets/11839736/20817483/d76dd0f4-b7dc-11e6-848e-50c9a4700322.png)

And this was the output I got after copying and pasting:
```
//Controls the delay in ms after which a dirty file is saved automatically. Only applies when "files.autoSave" is set to "afterDelay"
    "files.autoSaveDelay": 1000,

    //Configure glob patterns of file paths to exclude from file watching. Changing this setting requires a restart. When you experience Code consuming lots of cpu time on startup, you can exclude large folders to reduce the initial load.
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true
    },

    //Controls whether unsaved files are restored after relaunching. If this is enabled there will be no prompt to save when exiting the editor.
    "files.hotExit": false,
```

**Comment by sandy081** [comment] 2016-12-02 06:55
Looks like editor is copying hidden areas also. @alexandrudima any idea how to not to do this?

**Comment by alexandrudima** [comment] 2016-12-02 16:02
@sandy081 This is by design. Hidden areas were added for folding and in the folding case it is mandatory that the folded text gets copied.

**Comment by bgashler1** [comment] 2016-12-05 21:52
Totally makes sense for folded text in every other case.  However, for the settings UX I personally feel it would would be better to exclude it.

**Comment by sandy081** [comment] 2016-12-06 09:04
I agree, in settings we should not have this behaviour. I would need to go away from using hidden areas for filtering and update the model.  Setting to this milestone so that if I have time i will update the strategy

**Comment by sandy081** [comment] 2016-12-07 17:48
Moving this to next milestone where I would revisit the hiding filtered areas strategy

**Comment by sandy081** [comment] 2017-02-21 09:31
It does not look to me a pressing bug as there was not many complaints on this. To me, it is bug related to debt.

**Comment by sandy081** [comment] 2017-04-12 07:44
Closing this as there are no plans in fixing this. This is also not a real scenario to occur.

**Closed by sandy081** 2017-04-12 07:44 UTC
Labels: bug, debt, workbench
