### ISSUE TITLE
No results found when searching across all file managed by OneDrive

### ISSUE THREAD

**Issue by ericdching** [Microsoft/vscode#35433] opened 2017-09-30 17:13 UTC
- VSCode Version: 1.16.1
- OS Version: Windows 10 (insiders preview) 10.0.16299 Build 16299.
I don't have the current release, so can't compare.

Steps to Reproduce:

1. Open a OneDrive folder in VSCode. Note, all files have a green check status and are 'Available on this device'
2. Ctrl+Shift+F to search across all files
3. Enter a string that should produce results and press Enter
4. No results found
5. Copy the directory outside OneDrive. Repeat steps 1-3 and results are returned

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-10-01 01:19
Have you tried any other editors? Do they show results?

**Comment by roblourens** [comment] 2017-10-01 01:23
Maybe related to https://github.com/Microsoft/vscode/issues/27285

**Comment by vojtechhabarta** [comment] 2017-10-15 12:56
I have exactly the same problem on
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.16299

When I open folder `C:\Users\<USER>\OneDrive\Documents\<FOLDER>` then Search (`Ctrl+Shift+F`) and also Go to File (`Ctrl+P`) don't work.

When I open `C:\Users\<USER>\Downloads` everything works as expected.

Only ASCII characters are used in my `<USER>` and `<FOLDER>` names.

I haven't find anything relevant in Developer Tools Console.

**Comment by roblourens** [comment] 2017-10-16 18:12
Any special permissions on the Onedrive folder? Are you running Code as administrator?

**Comment by vojtechhabarta** [comment] 2017-10-17 21:47
Thanks for hints. Finally I resolved the problem by turning off _Files On-Demand_ OneDrive feature.

![files-on-demand](https://user-images.githubusercontent.com/1191407/31690695-cc73a4d6-b393-11e7-8d7f-1be56615069e.PNG)

It seems that ripgrep doesn't work with _Files On-Demand_ feature even if all folders are selected in OneDrive Settings and _Always keep on this device_ is checked in File Explorer.

![menu](https://user-images.githubusercontent.com/1191407/31690709-de6f497e-b393-11e7-988e-6d971204d956.PNG)

In this case directories and files still have special link mode (reparse point attribute with no target) which ripgrep isn't able to process.

Thanks for great editor!

**Comment by roblourens** [comment] 2017-10-17 21:57
Glad you found a workaround. Do you know whether other editors work with this?

**Comment by vojtechhabarta** [comment] 2017-10-18 07:08
I tried Notepad++ and NetBeans and both are able to search OneDrive files when _Files On-Demand_ feature is turned on.

I also tried to add file which was only available online (using OneDrive web app) and after successful search in Notepad++ file had status _Available on this device_ (was downloaded during the search).

**Comment by roblourens** [comment] 2017-10-18 13:46
Ok, I'll have to find out how they prompt windows to download those files.

**Comment by vojtechhabarta** [comment] 2017-10-18 19:08
I don't think these editors do anything special for OneDrive files. I would guess they just open the file as usual and Windows downloads it.

I think we could try to ask ripgrep to support _Files On-Demand_. It has special handling for links so it could also handle these special "links" too.

**Comment by roblourens** [comment] 2017-10-24 22:05
The original report from @ericdching said that this happened even when all files are on the local device. I haven't had a response from him on questions above, and there are multiple reports of this behavior for off-device files, so continuing to use this issue for OneDrive issues in general.

**Comment by aaronsace** [comment] 2017-10-25 11:53
Ticking 'always keep on this device' downloads all the files yet Visual Studio Code still cannot search the contents. 

I tried closing OneDrive and putting the same files/folder in 'C:\Users\aaron\OneDrive' and 'C:\Users\aaron'. The search works but when you reopen OneDrive the search stops working even though the files are still there. 

Windows indexes and searches within the files fine so the issue is with the way Visual Studio Code is searching within the file contents in conjunction with OneDrive. As I say, the files are definitely still on the hard drive so there is a problem with Visual Studio Code.

**Comment by roblourens** [comment] 2017-10-25 17:45
Are there any errors in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by aaronsace** [comment] 2017-10-25 18:02
```
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case --max-filesize '17179869184' --no-ignore --follow --fixed-strings -- 'test' 'c:\Users\aaron\OneDrive\MultiPoolMiner' 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\parts\welcome\page\electron-browser\vs_code_welcome_page'
 - cwd: c:/
 - Sibling clauses: {}
c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\parts\welcome\page\electron-browser\vs_code_welcome_page: The system cannot find the path specified. (os error 3)
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.


```

**Comment by roblourens** [comment] 2017-10-30 22:52
> but, when you reopen OneDrive, the search stops working on the OneDrive location even though the files are still there.

Strange. I haven't been able to repro this. Will keep trying...

**Comment by kevbry** [comment] 2017-12-01 06:25
Same issue here. Identical symptoms to above. Is there anything I can provide/do to help track this down? 

Search output:
`c:\Users\me\OneDrive\Documents\Visual Studio 2017\Projects\test: Access is denied. (os error 5)`

**Comment by kevbry** [comment] 2017-12-03 00:13
Did some further digging on this. When ripgrep is pointed at a directory that is in OneDrive with Files on Demand turned on, it fails as though the directory doesn't exist. If pointed at a specific file within that same directory, it's able to work just fine. This is exactly the same behaviour as here:
https://github.com/Microsoft/vscode/issues/27285

This will have to be fixed by ripgrep. I'll open a ticket up there soon.

**Comment by aaronsace** [comment] 2017-12-03 00:36
@kevbry Great, I hope this gets fixed soon. OneDrive is an integral part of windows these days.

**Comment by roblourens** [comment] 2017-12-04 02:19
I can repro it now after installing another Windows update. I was already on the latest Windows release, but I didn't have the latest OneDrive update for some reason.

**Comment by roblourens** [comment] 2017-12-04 06:06
Upstream bugs: 

https://github.com/rust-lang/rust/issues/46484

BurntSushi/ripgrep#705

**Comment by julenka** [comment] 2017-12-04 17:42
Hi @roblourens I have a live repro of this. All of the files in my "OneDrive - Microsoft" folder are downloaded locally to my machine. I can search my directory using Sublime. When I search using code, the Search Output Window shows this:

rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/.git' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/.svn' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/.hg' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/CVS' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/.DS_Store' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/*.dmp' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/*.dll' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/*.obf' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/*.mp4' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/node_modules' -g '!/Users/jschwarz/OneDrive - Microsoft/workingdirs/**/bower_components' --max-filesize '17179869184' --no-ignore --follow --fixed-strings -- 'test' 'c:\Users\jschwarz\OneDrive - Microsoft\workingdirs'
 - cwd: c:/
 - Sibling clauses: {}
c:\Users\jschwarz\OneDrive - Microsoft\workingdirs: Access is denied. (os error 5)

**Comment by SQLDBAWithABeard** [comment] 2017-12-20 19:26
I didnt have this issue until I updated to todays insider release and now I am getting this error also in the same scenario and the same error

**Comment by tamasys** [comment] 2018-01-02 03:58
This is still very much an issue in the current version of VS Code. Has there been any progress on it? It looks like there hasn't been much activity on the upstream bugs...

**Comment by julenka** [comment] 2018-01-16 19:02
FYI, got the latest stable version of VSCode, still reproduces. Would be great to please get an update on when this might be fixed.

Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by roblourens** [comment] 2018-01-16 19:59
The upstream Rust issue is not seeing any progress, so I hope to come up with a workaround by the end of the month.

I don't think it's been called out in this issue yet, but this can be worked around by disabling ripgrep with `"search.useRipgrep": false`.

**Comment by SQLDBAWithABeard** [comment] 2018-01-17 07:09
Thank you @roblourens - That seems to have done the trick for me :-)

**Comment by roblourens** [comment] 2018-02-06 08:17
This will be fixed when we start building Insiders again.

**Comment by roblourens** [comment] 2018-03-12 01:40
This was actually pulled from the 1.21 release.

Going into 1.22

**Closed** 2018-03-12 01:41 UTC
Labels: bug, search, upstream

**Comment by dbaeumer** [comment] 2018-03-29 10:08
I verified that the following works:

- when the files are already available on my machine
- when the files are not available on my machine. In this case the files are downloaded after the search.
