### ISSUE TITLE
Selecting IntelliSense overwrites text instead of inserting

### ISSUE THREAD

**Issue by StickNitro** [microsoft/vscode#82358] opened 2019-10-11 13:22 UTC
Issue Type: <b>Bug</b>

When selecting an entry from IntelliSense the text on the line after the caret is getting replaced

e.g. closing brackets or braces are replaced, or part of a closing HTML tag gets replaced.

[See this video showing the problem](https://drive.google.com/open?id=1fjmL5tfy-OTIB44xnc9deUcQNBYqAvoh)

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:37:27.907Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
user-secrets|adr|1.0.1
vscode-angular2-files|ale|1.6.2
sort-imports|ama|6.1.0
ng-template|Ang|0.802.3
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.1
vscode-npm-script|eg2|0.3.9
vscode-solution-explorer|fer|0.3.5
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
auto-using|Fud|0.7.9
html-preview-vscode|geo|0.2.5
minify|Hoo|0.4.3
rest-client|hum|0.22.2
csharpextensions|jch|1.3.0
docomment|k--|0.1.8
git-indicators|lam|2.1.1
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.6.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.7.0
debugger-for-chrome|msj|4.12.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.1
typescript-hero|rbb|3.0.0
vscode-manage-user-secrets|Rep|1.0.4
azure-iot-toolkit|vsc|2.10.0
vscode-icons|vsc|9.4.0
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by IllusionMH** [comment] 2019-10-11 13:54
/confirmed

Came here to report same issue and looks like this is new issue (at least I don't remember it yesterday).

Problem occur if I use <kbd>Tab</kbd> to insert suggestion, but it works OK if I use <kbd>Enter</kbd>. At least this is behavior I see in JS files.

@StickNitro can you check if there is difference between using <kbd>Tab</kbd> and <kbd>Enter</kbd> in your case?

Version: 1.40.0-insider (user setup)
Commit: 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb
Date: 2019-10-11T05:44:05.506Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by StickNitro** [comment] 2019-10-11 14:01
@IllusionMH In my case was happening whether I use `Tab`, `Enter` or select using the mouse.  If I undo `Cmd+Z` and the try the IntelliSense again using `^+Space` then it seems to work.

**Comment by isidorn** [comment] 2019-10-11 14:10
Looks like a duplicate, I think there is already a PR which tackles this

**Comment by IllusionMH** [comment] 2019-10-11 14:21
My search skill let me down today. Yes, looks like duplicate of #82324, PR with fix #82349

**Closed** 2019-10-11 14:27 UTC
Labels: *duplicate
