### ISSUE TITLE
Cannot log into microsoft acct to enable sync

### ISSUE THREAD

**Issue by arkansas-coder** [microsoft/vscode#107191] opened 2020-09-21 22:34 UTC
Issue Type: <b>Bug</b>

Prior to 1.49.0 I was able to click the Account SignIn icon and log into my Microsoft account to synce setting between various machines. With 1.49.0 and 1.49.1 when I try to sign in with Microsoft, VS ties to open a browers tab with "localhost:xxx/signin?nonce=xxx", but it just hangs indefinately without reporting any errors.  I have tried both Firefox and Edge.

Steps to reporduce:
Start VS Code
SSH to remote linux machine
Click Sign In to Sync Settings
Select Sign in with Microsoft
Browser tab opens but nothing happens

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux arm 5.4.51-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1920X 12-Core Processor  (24 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.46GB free)|
|Process Argv|--crash-reporter-id fb2bc9a2-8573-4c52-9ede-23d26e43df83|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: openHAB|
|OS|Linux arm 5.4.51-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 933)|
|Memory (System)|0.95GB (0.20GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
oh-alignment-tool|max|2.0.8
openhab|ope|0.7.0

</details>

**Comment by RMacfarlane** [comment] 2020-09-22 15:10
Duplicate of https://github.com/microsoft/vscode/issues/104674

**Closed by RMacfarlane** 2020-09-22 15:10 UTC
