### ISSUE TITLE
False errors with SASS maps

### ISSUE THREAD

**Issue by raphievila** [Microsoft/vscode#15410] opened 2016-11-12 19:04 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|VisualStudioDarkTheme|Adrien|1.0.1|
|jslint|ajhyndman|1.2.1|
|vscode-color|anseki|0.2.1|
|code-runner|formulahendry|0.4.2|
|composer|ikappas|0.5.0|
|vscode-tfs|ivangabriele|0.5.2|
|vscode-scss|mrmlnc|0.5.0|
|debugger-for-edge|msjsdiag|0.4.1|
|sass-helper|ramyaraoa|0.0.2|
|vscode-icons|robertohuertasm|4.0.1|
|php-formatter|Sophisticode|0.1.3|

---

Steps to Reproduce:

1. Create a .scss file and use an associative map, for example: $map: (key1: value1, key2: value2);
2. This will be flagged as an error, even though is a proper formatting.

![scss-maps-false-flag](https://cloud.githubusercontent.com/assets/6283126/20240214/815fe8ea-a8d8-11e6-9173-7e479adeee0b.PNG)

**Comment by aeschli** [comment] 2016-11-14 09:18
duplicate of #1758

**Closed by aeschli** 2016-11-14 09:18 UTC

**Comment by raphievila** [comment] 2016-11-15 04:08
Didn't noticed it, thanks pointed it out.
