### ISSUE TITLE
Pasting multiple lines copied without selection duplicates them

### ISSUE THREAD

**Issue by lukas-tr** [microsoft/vscode#71010] opened 2019-03-23 14:27 UTC
- Version: 1.33.0-insider (user setup)
- Commit: 9474154f133dbbb793ca3c128c9fcfdca39f5b26
- Date: 2019-03-22T06:18:30.063Z
- Electron: 3.1.6
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

![vscode paste not working](https://user-images.githubusercontent.com/36337818/54867337-6f991700-4d7f-11e9-8055-bfd0001160da.gif)

Here is how the result should look like:

![vscode working](https://user-images.githubusercontent.com/36337818/54867314-4082a580-4d7f-11e9-8c6e-6cf44dd4c656.gif)

Both methods should yield the same result

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment] 2019-09-10 09:43
duplicate of #43722

**Closed by alexandrudima** 2019-09-10 09:43 UTC
Labels: bug, editor-clipboard, editor-multicursor
