### ISSUE TITLE
'cancelled because node is unresponsive' when watch big data in Debug Console

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#2408] opened 2016-01-27 06:17 UTC
Steps to reproduce:
* set up environment
```
git clone https://github.com/minggo/vscode-issue
cd vscode-issue
npm install
```
* set breakpoint at [this line](https://github.com/minggo/vscode-issue/blob/master/firedoc-parse.js#L192)
* debug as a node app
* input `ast` in `Debug Console`
* input `ast.classes` in `Debug Console`

Then you will meet `cancelled because node is unresponsive` error.

**Comment by weinand** [comment] 2016-02-12 23:34
Duplicate of https://github.com/Microsoft/vscode-node-debug/issues/11

**Closed by weinand** 2016-02-12 23:34 UTC
Labels: debug
