### ISSUE TITLE
Panel can get into a broken state to only show Ellipsis 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37380] opened 2017-11-01 05:59 UTC
Testing #36906 with 8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791

Similar to the one I made for activity bar:

In vertical panel state

1. Right click terminal -> Hide
2. Ctrl + ` to open terminal
3. Quick VS Code and Relaunch

Panel get stuck in this state of ellipsis, and clicking on ellipsis doesn't do anything.

![image](https://user-images.githubusercontent.com/4033249/32261950-fba1e23a-be8e-11e7-90b8-7071120b1607.png)

**Comment by isidorn** [comment] 2017-11-01 16:16
Duplicate of #37333

**Closed by isidorn** 2017-11-01 16:16 UTC
Labels: bug, workbench
