### ISSUE TITLE
VS Code does not shrink the code view's horizontal scroller automatically

### ISSUE THREAD

**Issue by redstrike** [Microsoft/vscode#15086] opened 2016-11-07 08:40 UTC
- VSCode Version: **1.7.1**
- OS Version: **Windows 10 x64 version 1607**

**Steps to Reproduce:**
1. Paste a very long text.
2. Add some line breaks.

![vs code does not auto shrink horizontal scroller](https://cloud.githubusercontent.com/assets/2168227/20051221/81a851ce-a500-11e6-8f30-4118ee38ba84.gif)

**Comment by alexandrudima** [comment] 2016-11-07 09:02
Duplicate of #13516

**Closed by alexandrudima** 2016-11-07 09:02 UTC
