### ISSUE TITLE
typescript auto-import is broken on filename rename (change only case) on windows

### ISSUE THREAD

**Issue by LexRiver** [microsoft/vscode#83886] opened 2019-11-03 06:58 UTC
Issue Type: <b>Bug</b>

if I rename file from 'Myfile.ts' to 'MyFile.ts' then auto-import is broken.
It's inserting new lines in old file, and opens this file in another tab!
But it should be only one file on windows.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment] 2020-01-27 21:45
Duplicate of #71990

**Closed by mjbvz** 2020-01-27 21:45 UTC
