### ISSUE TITLE
Customize scrollbar widths

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode#100305] opened 2020-06-16 15:19 UTC
Both horizontal and vertical scrollbars in the code editor, as well as the vertical scrollbar in the Explorer, should have settings allowing the user to specify how thick they should be.  Setting should be a number, not values like "small" and "large".

**Comment by gjsjohnmurray** [comment] 2020-06-16 15:29
/duplicate of #30191

Please add your comments there.

**Closed** 2020-06-16 15:30 UTC
Labels: *duplicate

**Comment by jez9999** [comment] 2020-06-16 15:33
@gjsjohnmurray This is not a dupe - that bug only tackles VERTICAL widths.
