### ISSUE TITLE
Color boxes remain for a second after deleting file contents

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#41553] opened 2018-01-12 22:17 UTC
- VSCode Version: Both 1.19 stable and the latest Insiders
- OS Version: All

Steps to Reproduce:

1. Create a css file with multiple hex colors
2. Delete the contents of the file

Expected: Cursor is on line 1 and file is empty
Actual: One of the color box stays in line 1 for a second or so and then disappears

If you start typing before the box disappears, then multiple boxes appear

![weird](https://user-images.githubusercontent.com/16890566/34897543-53693d5e-f7a3-11e7-8811-050962513c5c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2018-09-21 19:27
Duplicate of https://github.com/Microsoft/vscode/issues/49388

**Closed** 2018-09-21 19:27 UTC
Labels: *duplicate, bug, editor-colors
