### ISSUE TITLE
"Untitled" file starts numbering at 7

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#65789] opened 2018-12-28 21:26 UTC
- I press cmd+n to open a blank editor
- There are no other untitled files open but it is called "Untitled 7"
- I close all open files and reload the window
- I open a new editor again
- Correctly named "Untitled-1"
- I open a .ts file
- Open a new editor
- "Untitled-7"

This is weird, it only happens in my vscode workspace. It doesn't happen if I disable extensions. Where should I set a breakpoint to see what's taking untitled documents 1-6?

**Comment by usernamehw** [comment] 2018-12-28 21:31
If vscode is older than 12 hours than possible duplicate of #65611

**Comment by rebornix** [comment] 2019-08-02 19:59
Likely a dup of #65611.

**Closed by rebornix** 2019-08-02 19:59 UTC
