### ISSUE TITLE
Tooltip with package version in package.json

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#108580] opened 2020-10-13 10:43 UTC
Issue Type: <b>Bug</b>

This tooltip which tells the latest version of a npm package seems to be not up to date. I use it all the time to know when I need to upgrade but now Sentry told me to upgrade, while the tooltip was still saying I am up to date. This is absolutely no priority, but I thought you should know. Thank you.

![image](https://user-images.githubusercontent.com/3931907/95850372-67d20680-0d59-11eb-9629-1bace2bef4aa.png)

Notification from Sentry
![image](https://user-images.githubusercontent.com/3931907/95850570-b8e1fa80-0d59-11eb-8cda-b6157812a516.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.59GB free)|
|Process Argv|--folder-uri file:///d%3A/WISK --crash-reporter-id 2d04b6c3-62e2-4115-9ffe-3e2e5bda0239|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-blink-mind|awe|0.0.10
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
auto-close-tag|for|0.5.9
favorites|kdc|2.4.5
back-n-forth|nic|3.1.0
vetur|oct|0.28.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-10-13 22:49
Maybe a duplicate of #108605 which has been fixed by @aeschli

**Comment by aeschli** [comment] 2020-10-14 06:13
dup of https://github.com/microsoft/vscode/issues/108605

**Closed by aeschli** 2020-10-14 06:13 UTC
