### ISSUE TITLE
Santa Hat Removal

### ISSUE THREAD

**Issue by Jackarunda** [microsoft/vscode#87318] opened 2019-12-19 06:25 UTC
Issue Type: <b>Feature Request</b>

Please add the Santa Hat back. The cheer it represents reminds me of when my mother and father were still alive.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Gaboik** [comment] 2019-12-19 07:18
Bring back the Santa hat. A bit of symbolism never hurt anybody, especially when said symbolism is clearly not meant to offend anyone. While Christmas is indeed a Christian tradition, the Santa hat represented the cheerful spirit and happiness many of us observe at this time of year, and we were robbed of that cheerful spirit.

> Please [re add] it immediately and make it your top priority

**Comment by egamma** [comment] 2019-12-19 08:01
Duplicate of #87291

**Comment by Jace67** [comment] 2019-12-19 08:02
Bring back the hat. Santa is not a religious figure even though his schtick is closely related to a religious event. It's like banning "Happy Holidays" since its associated with "Merry Christmas".

**Comment by egamma** [comment] 2019-12-19 08:03
Duplicate of #87291

**Closed** 2019-12-19 08:03 UTC

**Comment by egamma** [comment] 2019-12-19 19:21
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
