### ISSUE TITLE
Bracket pair colorizer fails for typecasted pointers

### ISSUE THREAD

**Issue by magdumnikhil** [microsoft/vscode#132231] opened 2021-09-03 09:32 UTC
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/47320124/131983899-4ed5aaeb-a9b5-4acb-9fcd-1b01b22784e4.png)

The bracket colors around "int *" should be the same. But those are not.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-80-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.62GB free)|
|Process Argv|--crash-reporter-id cbf5af01-9ac6-414e-a2a5-d597132ecd40|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.19.66.27|
|OS|Linux x64 5.4.0-80-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 900)|
|Memory (System)|62.70GB (17.38GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
docs-view|bie|0.0.9
arm|dan|1.5.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vcast-lang|Pat|0.2.0
linkerscript|Zix|1.0.2
asciidoctor-vscode|asc|2.8.9
atlascode|atl|2.9.1
codealignment-vscode|cpm|2.0.19
doxdocgen|csc|1.3.2
gitlens|eam|11.6.0
plantuml|jeb|2.15.1
cpptools|ms-|1.6.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
tabnine-vscode|Tab|3.4.26
tmlanguage|Tog|0.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30361753
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by hediet** [comment] 2021-09-05 20:34
Duplicate of #130996, see #131092.

**Closed by hediet** 2021-09-05 20:34 UTC
Labels: new release
