### ISSUE TITLE
Display Markdown table incorrectly in Extension page

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#45358] opened 2018-03-09 01:00 UTC
Issue Type: <b>Bug</b>

The extension intro page shown in Visual Studio Code can't display Markdown table correctly.  Such as [Angular Extension Pack](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack) contains some document and it can't shown table in the VSCode editor area correctly.  It do can display on Web Browser.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (4.28GB free)|
|Process Argv|C:\PROGRA~1\MIFA7F~1\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.1.9
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
supersharp|cra|0.1.4
vscode-markdownlint|Dav|0.13.0
vscode-simpler-icons|dav|1.5.2
angular-extension-pack|dog|1.0.2
netcore-extension-pack|dog|0.3.0
githistory|don|0.4.0
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.27
prettier-vscode|esb|1.2.2
git-project-manager|fel|1.4.0
auto-rename-tag|for|0.0.15
dotnet|for|0.0.3
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.1.6
vscode-cdnjs|Jak|0.14.3
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.6.0
Angular2|joh|2.14.0
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.0.17
refactorix|kri|0.3.6
csharpfixformat|Leo|0.0.64
json-to-ts|Mar|1.5.4
Angular-BeastCode|Mik|5.2.16
vscode-kubernetes-tools|ms-|0.1.5
azure-account|ms-|0.3.1
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
typescript-javascript-grammar|ms-|0.0.34
vsliveshare|ms-|0.2.206
debugger-for-chrome|msj|4.1.0
vscode-docker|Pet|0.0.25
vscode-versionlens|pfl|0.20.0
tsimporter|pmn|1.2.14
quicktype|qui|8.5.106
Csharp-ASPNETCore|rah|1.0.5
LiveServer|rit|3.2.1
git-add-remote|sam|0.0.2
vscode-open|san|0.1.0
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|2.9.0
vscode-autohotkey|sle|0.2.2
bootstrap4-vscode|the|4.0.0
msbuild-project-tools|tin|0.2.30
vscode-todo-highlight|way|0.5.11
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-03-09 01:03
Duplicate of #32760

**Closed** 2018-03-09 01:13 UTC
Labels: new release
