### ISSUE TITLE
problems in opened files setting

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#19018] opened 2017-01-23 09:31 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.5|
|php-intellisense|felixfbecker|0.0.12|
|code-runner|formulahendry|0.6.6|
|beautify|HookyQR|0.7.3|
|vs-color-picker|lihui|0.3.2|
|vscode-hexdump|slevesque|1.1.4|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. install php-intellisense extension
2. open workspace with PHP files
3. open any PHP file

Expected: Problems panel has problems of only opened files

Actual: Problems panel has problems of total workspace.

Can you add setting to scan on problems only opened files? I have too large workspace with many "prev-" temporary files. I don't need to see errors from temporary files. And I don't need to scan all files, because it take CPU resources.

thank you.

P.S. I write this report to you, because without "php-intellisense" I see in problems panel message: "No problems have been detected in the workspace so far". => This is VSCode ask "php-intellisense" to scan total workspace, if I correct.

**Comment by mousetraps** [comment] 2017-01-24 07:26
Hey @SailorMax, thanks for reaching out! I see how the error list message can be misleading, but turns out it's actually up to extension authors to implement this behavior. Extensions can choose to publish diagnostics for only open files, for all files, or for I don't know, all files named `unicorn.php` :unicorn:. See the [PublishDiagnostics Notification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#publishdiagnostics-notification) section in the language server protocol for more details.

In the case of PHP IntelliSense extension, [this line](https://github.com/felixfbecker/php-language-server/blob/d080c161a9e65e54ec28a4b9a3e3607f09232a9c/src/LanguageServer.php#L314) in particular appears to be the culprit (outer for loop cycling through all the document uris in the project). 

As far as what the optimal behavior here might be, I've seen it both ways. JS/TS, for instance, only shows errors for open files, but there is also an issue open to add an "all files in workspace" option https://github.com/Microsoft/vscode/issues/13953.

Anyways, hope that helps! Closing as this isn't caused by VS Code, but I recommend taking the discussion over the the php-language-server repo.

cc @felixfbecker

**Closed by mousetraps** 2017-01-24 07:26 UTC
Labels: error-list, php
