### ISSUE TITLE
launch.json shows stale warnings after deleting/closing

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#23726] opened 2017-03-31 08:20 UTC
I was working on a feature branch for my extension and switched back to master. Since I now had an invalid `launch.json` (it had values in that relate to the new feature that isn't on my master branch) I got warnings.

I closed `launch.json` and deleted it, then hit F5. I picked mt extensions option which resulted in a new `launch.json` being created; however it still shows warnings based on the old contents.

I suspect some state is hanging around when I deleted the file and also not being refreshed when `launch.json` is being re-created by hitting F5 (it's coming from `initialConfigurations` in `package.json` for my extension).

![launch.json](https://cloud.githubusercontent.com/assets/1078012/24542372/4b8ee846-15f3-11e7-9312-cd49cdf344d0.jpg)

**Comment by DanTup** [comment] 2017-03-31 08:21
As you'd probably expect, cutting and pasting the whole file caused the warnings to disappear.

**Comment by DanTup** [comment] 2017-03-31 08:22
Simple repro steps:

- Open `launch.json`
- Type some garbage to get warnings
- Close `launch.json`
- Delete `launch.json`
- Press F5 and select an option that causes it to be re-created

You'll still see the original warnings.

**Comment by isidorn** [comment] 2017-03-31 13:48
Sounds like a duplicate of https://github.com/Microsoft/vscode/issues/16656
Assigning to @aeschli

**Comment by aeschli** [comment] 2017-04-04 09:34
To reproduce:
- Open `launch.json`
- Type some garbage to get warnings, save
- Restart VSCode
- Open `launch.json`
- Close `launch.json`
- Delete `launch.json`
- Press F5 and select an option that causes it to be re-created
- Open `launch.json, old errors appear

**Closed** 2017-04-04 09:34 UTC
Labels: bug, json
