### ISSUE TITLE
Settings Editor renders error message when the setting is unmodified 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#171887] opened 2023-01-20 23:42 UTC
Even if it's not modified, we still render an error message, which feels wrong

<img width="956" alt="image" src="https://user-images.githubusercontent.com/876920/213824310-9f474cb2-8a94-430a-bebe-ef640f5e8035.png">

**Comment by rzhao271** [comment] 2023-01-21 00:41
Duplicate of #171787
Fixed in OSS

**Closed by rzhao271** 2023-01-21 00:41 UTC
