### ISSUE TITLE
Emmet tag expansion no longer works by default in JSX files

### ISSUE THREAD

**Issue by kvoth3** [Microsoft/vscode#15518] opened 2016-11-15 15:01 UTC
- VSCode Version: 1.7.1
- OS Version: Win10

Steps to Reproduce:

1. In react render method, in return statement type a class name: `.test`
2. Pressing tab should yield: `<div className='test'></div>`

**Comment by mrmlnc** [comment] 2016-11-15 15:04
Please, use search before create a new issues.

Related to https://github.com/Microsoft/vscode/issues/14962 and should be fixed in 1.7.2 (but date is unknown).

**Comment by kvoth3** [comment] 2016-11-15 15:05
sorry i did search but i had the isopen tag so it didn't show. my apologies

**Comment by ramya-rao-a** [comment] 2016-11-16 03:10
Closing as duplicate of #14962

**Closed by ramya-rao-a** 2016-11-16 03:10 UTC
