### ISSUE TITLE
Suggest filtering is wrong

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#49950] opened 2018-05-16 04:30 UTC
Issue Type: <b>Bug</b>

Not able to repro on 1.23.1, but repros on Insider:

![suggest](https://user-images.githubusercontent.com/4033249/40096703-debf908a-5886-11e8-80ae-a029d500db28.gif)

I'm sure the CSS language server is responding with `width` as it's doing in 1.23.1. It's just the `width` item for some reason get filtered out.

This is a regression so I put it under May.

VS Code version: Code - Insiders 1.24.0-insider (0d376d890ceb406cabd2b4281deebf5f4038a78c, 2018-05-15T05:10:53.660Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1306943|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.0.1
vscode-docker|Pet|0.0.26
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
vscode-intelephense-client|bme|0.8.8
tslint|eg2|1.0.28
prettier-vscode|esb|1.3.1
theme-monokai-pro-vscode|mon|1.1.6
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.3.114
debugger-for-chrome|msj|4.4.3
polacode|pnp|0.2.2
vscode-sort-json|ric|1.11.0
vscode-csstree|sme|0.6.0
vim|vsc|0.11.6

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-05-16 07:29
likely a dupe of https://github.com/Microsoft/vscode/issues/49895#issuecomment-389352960

**Closed** 2018-05-16 11:03 UTC
Labels: *duplicate, suggest
