### ISSUE TITLE
Remote SSH password prompt blocks bluetooth mouse functional keys

### ISSUE THREAD

**Issue by Tuyixiang** [microsoft/vscode#90506] opened 2020-02-12 07:43 UTC
Issue Type: <b>Bug</b>

Environment: macOS, a bluetooth mouse (logitech MX Master)

When I am prompted to enter password for a remote SSH host (either by connecting from Remote Explorer or after disconnection), as long as the prompt is there, all the functional keys on my bluetooth mouse (such as switching desktop or even scrolling) seem to be intercepted by that prompt and no longer work, <b>even outside VSCode window</b>.

Further testing shows this interesting behavior:  
It seems that there is an inner switch which determines whether mouse functional keys should be intercepted, and that switch is bugged. 

It turns on (disabling mouse functional keys) when:
- Focusing on a VSCode window with active password prompt. 
- Start rendering _that window_, <b>even if the user is not focusing on it.</b> For example: 
  - Mission Control / App Exposé. 
  - Switching to a desktop where _that window_ is partially visible.
  - Revealing part of _that window_ by dragging the window above it.

It turns off (re-enabling mouse functional keys) when:
- Un-focus the password prompt by clicking outside it. 
- Switch focus from that window to another VSCode window or another application or another desktop.

VS Code version: Code - Insiders 1.43.0-insider (beaf391bc53136912e4f0bbdfb7844ad954247db, 2020-02-07T05:30:08.850Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (5.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
systemverilog|eir|0.9.4
decaf-vscode|equ|0.1.0
vsc-material-theme|Equ|32.4.0
vsc-material-theme-icons|equ|1.1.3
code-runner|for|0.9.15
matlab|Gim|1.5.3
python|ms-|2020.2.62710
remote-containers|ms-|0.101.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
cmake-tools|ms-|1.3.0
cpptools|ms-|0.26.3
systemverilog|msh|0.0.20
veriloghdl|msh|1.0.4
java|red|0.55.1
rust|rus|0.7.0
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
material-theme|zhu|3.2.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2020-02-13 04:47
This is weird because the prompt is just a basic text input, not a native dialog, and I don't think we do anything that would cause this. Can you check whether this happens with similar prompts with text inputs? For example, just normal quickopen (cmd+p)

**Comment by Tuyixiang** [comment] 2020-02-13 06:15
> This is weird because the prompt is just a basic text input, not a native dialog, and I don't think we do anything that would cause this. Can you check whether this happens with similar prompts with text inputs? For example, just normal quickopen (cmd+p)

No. As far as I've seen, only the SSH password input triggers this behavior.

**Comment by roblourens** [comment] 2020-02-14 18:07
Sorry, this is strange and I have no clue why it would happen. It seems more likely that it comes from something strange that your OS or your mouse driver is doing.

If you want to experiment to help us narrow it down, you could try creating a basic hello world extension: https://code.visualstudio.com/api/get-started/your-first-extension then adding the same code that we use to show the password prompt, like

```
const quickPick = vscode.window.createInputBox();
quickPick.title = msg;
quickPick.prompt = prompt;
quickPick.password = true;
quickPick.ignoreFocusOut = true;
``` 

and you could check whether any of those flags in particular trigger this issue

**Comment by Tuyixiang** [comment] 2020-02-16 10:45
`quickPick.password = true` triggers this issue. 

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

  let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {

    const quickPick = vscode.window.createInputBox();
    quickPick.password = true; // commenting this line will resolve the issue
    quickPick.show();

  });
	
  context.subscriptions.push(disposable);

}

export function deactivate() { }
```

I suspect my bluetooth mouse is producing some sort of a key combination or escaped sequence, which is somehow captured by the password input?

**Comment by roblourens** [comment] 2020-02-17 19:32
Very strange. The only difference that the flag makes is that we set `type="password"` on the `<input>` for the input box.

It is possible that when a password box is open or focused, Chrome/Electron/the OS limits what other apps can do, like to prevent them from grabbing the contents of that box.

@chrmarti have you heard anything like this before or do you have any ideas?

**Comment by chrmarti** [comment] 2020-02-18 09:39
No, @deepak1556 any idea why `type="password"` would affect function keys on mice?

**Comment by deepak1556** [comment] 2020-02-19 05:50
When there is focus on `type="password"` field , chrome will enable secure text input https://developer.apple.com/library/archive/technotes/tn2150/_index.html which intercepts the events https://chromium-review.googlesource.com/c/chromium/src/+/943064/ . This is not a bug, and there is nothing actionable from our end.

**Comment by chrmarti** [comment] 2020-02-19 07:05
Thanks @deepak1556 . Closing as known limitation.

**Closed by chrmarti** 2020-02-19 07:05 UTC
Labels: needs more info
