### ISSUE TITLE
Chat responses are not read

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#188835] opened 2023-07-25 17:55 UTC
Testing #188537

- Type a request, press enter
- Nothing from the response is ever read

I think it's supposed to do this?

**Comment by meganrogge** [comment] 2023-07-25 18:47
Are you in screen reader optimized mode?

**Comment by meganrogge** [comment] 2023-07-26 16:45
also any errors in dev tools console?

**Comment by meganrogge** [comment] 2023-07-26 21:52
here's the problem https://github.com/microsoft/vscode/blob/d0a179cf012f40fb50172a40ac9b7dba4f6431ba/src/vs/workbench/contrib/chat/browser/chatAccessibilityService.ts#L44

**Comment by meganrogge** [comment] 2023-07-26 21:56
cc @rperez030 and @jooyoungseo this is the error you were encountering. should be fixed in insider's tomorrow

**Comment by meganrogge** [comment] 2023-07-26 22:00
regression caused by the fix for https://github.com/microsoft/vscode/issues/188417

**Closed** 2023-07-26 22:16 UTC
Labels: bug, important, accessibility, panel-chat
