### ISSUE TITLE
Add configuration for vertical height of Open Editor tabs

### ISSUE THREAD

**Issue by matt-kempster** [microsoft/vscode#127899] opened 2021-07-02 18:36 UTC
I love using "Open Editors" as a _de facto_ "vertical tabs" feature. In fact, I fully disable regular horizontal tabs because I find them largely useless. However, there is one downside of managing tabs this way: vertical space.

In this screenshot, you can see how small these Open Editor tabs are:
![image](https://user-images.githubusercontent.com/13004550/124315841-76e82700-db29-11eb-9f72-4decd36236c1.png)

I would love to be able to configure the vertical height of each. I'd add a couple pixels to the standard height to make each tab a bit taller, thus easier to click.

Thank you!

**Comment by isidorn** [comment] 2021-07-26 13:50
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

Though it might be seen as a duplicate of make the workbench font customisable

**Closed** 2021-08-10 16:55 UTC
Labels: feature-request, *out-of-scope, open-editors

**Comment by RokeJulianLockhart** [comment] 2024-02-18 23:34
> https://github.com/microsoft/vscode/issues/127899#event-5136534808

@isidorn, why is this https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3A*out-of-scope?
