### ISSUE TITLE
"Restart Window" option for extension updates does not restart all  instances of VS Code

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/vscode#17624] opened 2016-12-20 19:23 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Update Extension
2. Click "Restart" button
3. Only the active window of VS Code restarts, leaving other windows loaded with old plugin versions

**Comment by alefragnani** [comment] 2016-12-21 00:10
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/3268

**Closed** 2016-12-21 08:34 UTC
