### ISSUE TITLE
wrapping column not always shown depending on zoom level

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#11843] opened 2016-09-11 11:17 UTC
- VSCode Version: 1.5.1
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:
1.  In the settings, enable wrapping like with "rewrap.wrappingColumn": 80,
2. Restart.
3. Note the line showing the 80th character column will show.
4. Zoom out. Note that the wrapping line is no longer showin.
5. Zoom out again. Wrapping line is now showing.
6. Now if you continue zooming out, the wrapping line never show.

It only shows up with two level of zoom (default, and 2 times out)

**Comment by alexandrudima** [comment] 2016-09-12 11:24
@jyavenard This is caused by the way zooming out is implemented in Chromium, it does pixel-level scaling. 

See for example https://jsfiddle.net/vu8zxyoc/ and try zooming out.

My recommendation is to not use zooming, but to adjust the `fontSize` for example.

Why are you ending up zooming out?

**Comment by alexandrudima** [comment] 2016-09-12 11:26
See also #9634

**Comment by jyavenard** [comment] 2016-09-12 13:24
I didn't realise chromium had anything to do with rendering text content in visual studio...

I have a laptop with high dpi, yet the default font is too big, and I find the settings of zooming out twice to be exactly what my aging eyes is able to read while maximising real estate :)

**Comment by jyavenard** [comment] 2016-09-12 13:26
Oh I couldn't find how to adjust the size of all the other elements at once like zooming does.

**Comment by alexandrudima** [comment] 2016-09-12 13:36
@jyavenard I am also suffering from this lack of customization. Please upvote in #10605 . If there would be a global `fontSize` setting, I don't think we would need to depend on the pixel level zooming Chromium offers.

**Comment by jyavenard** [comment] 2016-09-12 13:46
what about a setting to set the column wrap width. So could set it to 2 pixels here so zooming shouldn't have an impact.

I don't see an option to upvote a bug on github.

**Comment by alexandrudima** [comment] 2016-09-12 13:48
![image](https://cloud.githubusercontent.com/assets/5047891/18438107/4759fcce-7900-11e6-8528-d4ce76913b51.png)

**Comment by alexandrudima** [comment] 2017-04-26 12:38
Duplicate of #9634

**Closed by alexandrudima** 2017-04-26 12:38 UTC
Labels: bug, editor, electron, upstream, zoom
