### ISSUE TITLE
preLaunchTask hold on 

### ISSUE THREAD

**Issue by shepherdwind** [Microsoft/vscode#40150] opened 2017-12-13 08:49 UTC
- VSCode Version: 1.18.1
- OS Version: macos 10.13.2

Steps to Reproduce:

1. clone my example repo `git clone git@github.com:shepherdwind/simple-evaluate.git`
2. checkout branch `git checkout vscode-preLaunchTask`
3. open file `test/shunting-yard.test.ts`
4. run Debug -> Start Debugging or Start Without Debugging

Reproduces without extensions: Yes

Problem, Start Debugging will hold on preLaunchTask.  If I don't stop the preLaunchTask `tsc`, the test task will not run. It is seem that the tsc task never end.

**Comment by isidorn** [comment] 2017-12-13 10:21
@shepherdwind thanks for the nice steps. I just tried this with latest vscode insiders nad the preLaunchTask seems to finish nicely for me.
Can you please try with latest vscode insiders to reproduce since we have pushed some fixed in this area a couple of weeks ago?
You can also wait a couple of days for the new vscode stable and let us know if you can stil lreproduce

Also you should get some timeout message after 10seconds asking you if you want to debug anyway.
The usual problem people have here is that they have a watching task but do not declare it as a background task in tasks.json. Though this does not seem to be the case here.

**Comment by IliaIdakiev** [comment] 2017-12-13 18:49
@isidorn I'm experiencing the same problem. I'm running VSC Version 1.18.1 on macOS High Sierra. It looks like perLauchTask (it's not a background task) never completes even though it does. I have to kill the "running" task to launch my project. I don't receive any timeout but I believe it's because the task completes after all.

**Comment by openreply-dleinhaeuser** [comment] 2017-12-13 21:25
I think I might have the same issue, although when I press enter in the terminal, it will no longer hang.

**Comment by openreply-dleinhaeuser** [comment] 2017-12-13 23:11
I also noticed, that the integrated terminal will behave the same for the shell. I.e. when I exit the shell in the integrated terminal, I have to press enter one additional time before the window will close, otherwise it will just sit there.

**Comment by shepherdwind** [comment] 2017-12-14 08:05
I try this case on some macOS, which version not 10.13.2(for example 10.12.x, 10.13.1), Test run ok. I believe this problem only happen on macOS 10.13.2.

**Comment by isidorn** [comment] 2017-12-14 09:25
@shepherdwind @IliaIdakiev please try with vscode insiders https://code.visualstudio.com/insiders/ as I have already mentioned in my comment above

**Closed** 2017-12-14 11:27 UTC
Labels: debug, needs more info
