### ISSUE TITLE
TypeScript declaration files for Jasmine not found in Angular 2 project

### ISSUE THREAD

**Issue by jorgeas80** [Microsoft/vscode#13125] opened 2016-10-01 18:08 UTC
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install [angular-cli](https://github.com/angular/angular-cli)
2. Run ng new myproject
3. Open the created project with VSCode, and open the spec file (src/app/app.component.spec.ts)

Functions like describe, beforeEach, it and expect are not recognized (see img)

![Jasmine ts types not found](http://pix.toile-libre.org/upload/original/1475345018.png)

Check list:

- node_modules/@types/jasmine/index.d.ts file exist
- this option is included in tsconfig.json

```
"typeRoots": [
      "../node_modules/@types"
    ]
```

As tsd is officially deprecated since August and I'm using the last VSCode release, why could be happening?

**Comment by jorgeas80** [comment] 2016-10-02 11:02
I had to add this to make vscode recognize Jasmine typings.

`/// <reference path="../../../node_modules/@types/jasmine/index.d.ts" />`

It shouldn't be necessary with my version, I think

**Comment by waderyan** [comment] 2016-10-03 21:30
@jorgeas80 thank you for opening this issue. 

@mhegazy can you take a look at this? I have recreated this on my own machine. As far as I can tell everything is setup correctly: `tsconfig.json`, typings exist in the proper location, etc. Seems like I'm missing a config step though...

**Comment by blakehawkins** [comment] 2016-10-11 14:37
I have a similar configuration with the same issue - no angular.

* vscode 1.5.3
* ubuntu 16.04

Steps to reproduce:

1. `npm install @types/es6-shim`
2. Add `"compilerOptions": {"typeRoots": ["./node_modules/@types/"]}` kv to `tsconfig.json`
3. `code` displays an error at, for example, `const features = new Set(arr);`

Can also confirm that compiling with `tsc` succeeds.

**Comment by waderyan** [comment] 2016-10-14 14:04
@blakehawkins thank you for providing more information. This is a language service issue. Moving to that repo.

**Comment by waderyan** [comment] 2016-10-14 14:04
This issue was moved to Microsoft/TypeScript#11620

**Closed by waderyan** 2016-10-14 14:04 UTC
Labels: js, needs more info

**Comment by napalm684** [comment] 2017-01-17 20:00
This does seem to be an issue with version 1.8.1 and required the un-necessary reference path to resolve.  It compiles fine types for jasmine are listed in tsconfig.json along with typeRoots property pointing here:

./node_modules/@types

**Comment by napalm684** [comment] 2017-02-02 23:53
This is no longer a problem for me removing the spec files for my tests from the exclusions property of tsconfig.json took care of it.  

Webpack in my case wasn't affected by this because you specify the files to compile (include) or exclude explicitly in the loader config.  Hope this helps someone.
