### ISSUE TITLE
Make conditional exceptions more discoverable

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#113784] opened 2021-01-04 22:44 UTC
Refs https://github.com/microsoft/vscode/issues/111227

This is a super cool feature and is actually the behavior I want 90% of the time when I tick either of the break-on-exception checkboxes, but it's not very discoverable right now. I think adding a ✏️ or equivalent icon in the right of the tree view item would make it easier to find.

**Comment by weinand** [comment] 2021-01-05 10:32
@isidorn this seems to be duplicate of #113805 ?

**Comment by isidorn** [comment] 2021-01-05 11:14
@connor4312 my mistake, I created a duplicate of this issue this morninig.
I will close this one since the other one has more comments https://github.com/microsoft/vscode/issues/113805

**Closed by isidorn** 2021-01-05 11:14 UTC
Labels: debug
