### ISSUE TITLE
`.ipynb` Please allow to run block of collapsed cells without having to uncollapse them

### ISSUE THREAD

**Issue by matte-esse** [microsoft/vscode#139914] opened 2021-12-30 09:40 UTC
This feature request is about Jupyter Notebooks.

The feature is available on GoogleColab. On GC if you add a Markdown cell with a Heading and collapse the cells below it (the ones between it and the next Markdown block with a Heading of the same or higher importance) and run it, it will run one by one the cells inside it without uncollapsing them. This is very handy for long notebook whose top cells need to be run often but need not to be seen. By keeping them hidden one makes the notebook significantly less cluttered.

**Comment by roblourens** [comment] 2022-01-14 20:17
This was discussed in https://github.com/microsoft/vscode/issues/132690. I am not crazy about it but we can discuss more.

Colab's behavior when a cell fails is to uncollapse and focus the failed cell, that's not bad.

**Comment by master3243** [comment] 2022-06-18 14:49
Can we please, please, pretty please, have this feature. 

I just want a button (or keyboard shortcut or any way at all) to run the following block without running the cells one by one

![image](https://user-images.githubusercontent.com/14184504/174443380-8c9a766c-fe6e-478f-9205-25d8a7fdefbf.png)

Having to uncollapse a hierarchy of markdowns and then running them one by one (making sure you don't accidentally run a cell in the following block) then collapsing them again and repeating the process for multiple top-level markdowns is a waste of time.

Google does this so beautifully with a simple play button next to the group

![image](https://user-images.githubusercontent.com/14184504/174443496-4f7c63ff-9936-4eeb-852b-5eb181f43fd2.png)
 
With google's layout I can, with three mouse clicks, run `import` then `loader` then `BERT` blocks without accidentally touching the `download images` block or any other neighbouring blocks.

With vscode I have to uncollapse the hierarchies, then `shift+enter` one by one and making sure I don't accidentally run neighbouring cells then scroll back up and collapse them. It's so meaningless to do all that manual process when a tiny feature will completely solve the problem.

**Comment by twopwood** [comment] 2023-02-11 01:08
Coming from the standard JupyterLab I also realize how often I need to run collapsed/hidden cells.  I noticed that in JupyterLab selecting a cell above and below along with the collapsed/hidden cells allows options such as "Clear Outputs" to apply to the collapsed/hidden cells.  I also noticed that in the VS Code implementation that it is possible to select a cell below the collapsed/hidden cells and "Execute Above Cells" will run the collapsed/hidden cells.  So is the issue that there is no way to select the collapsed/hidden cells?  Or is there another reason why this doesn't work?  Perhaps adding an option like "Execute all cells between selected cells" would solve the issue?

**Comment by gongx030** [comment] 2023-06-01 18:08
Any updated discussion or ongoing efforts to address this issue? Being able to run a block of cells like in Google Colab is extremely useful.

**Comment by nithinjp1997** [comment] 2023-08-04 04:39
Yes please I am used to the way Google Colab allows us to run collapsed cells. Please bring this feature. Pretty Please

**Comment by danveritus** [comment] 2023-11-10 09:42
This feature is essential. Here's my vote.

**Comment by cbonet** [comment] 2023-12-12 18:37
Yes please, this feature is extreme useful, I use it on Google Colab all the time

**Comment by Nanta-Sp** [comment] 2024-01-10 21:33
Another vote. Please.

**Comment by lianxinhe** [comment] 2024-01-20 16:49
same here. really need it!

**Comment by jessicacardoso** [comment] 2024-01-27 14:42
+1

**Comment by JosephBEAUREDER** [comment] 2024-03-21 16:14
Anobody knows an extension that does the same ?

**Comment by nithinjp1997** [comment] 2024-04-05 04:43
Finally the new update has brought this long awaited feature.

**Comment by JosephBEAUREDER** [comment] 2024-04-05 13:39
Fake news ?

**Comment by joel-kelly** [comment] 2024-04-05 21:07
This is working for me with version 1.88 on Windows!!

**Comment by danveritus** [comment] 2024-04-20 18:10
Finally

**Comment by roblourens** [comment] 2024-05-03 03:35
Ah yes this was implemented, there must be a dupe of this issue somewhere

**Closed by roblourens** 2024-05-03 03:35 UTC
Labels: feature-request, notebook-folding, notebook-execution
