### ISSUE TITLE
Persist selected file icon theme to user config (`settings.json`)

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#13824] opened 2016-10-16 07:46 UTC
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Select a file icon theme
2. Open settings JSON

Expected:

The file icon theme should appear in the settings JSON.

Actual:

The file icon theme doesn't appear in the settings JSON.

**Comment by aeschli** [comment] 2016-10-17 14:22
duplicate of #7358

**Closed by aeschli** 2016-10-17 14:22 UTC
