### ISSUE TITLE
Code helper eat 100% and intellisense not working

### ISSUE THREAD

**Issue by victorzhunjie** [Microsoft/vscode#13294] opened 2016-10-06 12:55 UTC
- VSCode Version: 1.5
- OS Version: MAC El Capitan & Sierra 

Steps to Reproduce:
1. Clean VScode No extension installed
2. running node / es6 javascript 

This issues been bugging me for few months , since then I have tried update vs code to latest and my mac os version to latest aswell. 

Everytime when I open the project , within few seconds the code helper will use 100% of cpu and the intellisense is no longer working . it just have a pop over "Loading ..." 

I have tried googled and people suggested --disable extension but that doesn't work for me . 

Please help

**Comment by waderyan** [comment] 2016-10-06 14:14
@victorzhunjie can you provide me a code sample? This seems to be similar to https://github.com/Microsoft/TypeScript/issues/10735

Can you also add a setting to your settings file? Add `"typescript.tsserver.trace": "verbose"` then open the output window and send me what you see. If this is the same issue then you'll see something like "sequence number cancelled"

**Comment by victorzhunjie** [comment] 2016-10-06 22:23
Thanks for the reply , it just a normal JS node express project NOT TypeScript , when I point it to javascript it just have a "loading ... " 
<img width="603" alt="screen shot 2016-10-07 at 9 21 13 am" src="https://cloud.githubusercontent.com/assets/14845401/19172794/7b71df72-8c6f-11e6-8a68-eaab57d26ae2.png">

**Comment by waderyan** [comment] 2016-10-10 15:52
@victorzhunjie thank you for sharing. Can you give me a link to a workspace so I can reproduce this on my machine? 

Also, can you add this setting to your settings file and open the output window to see the TypeScript log? I believe you are seeing this [issue](https://github.com/Microsoft/TypeScript/issues/10735). Please share what you see in the log. 

```json
"typescript.tsserver.trace": "verbose"
```

**Comment by victorzhunjie** [comment] 2016-10-12 06:56
Hi guys , I am not using type script .

when I setup my project into another directory it working fine. might be something is causing it to eat all the resource in the original location . I will try do some process elimination and report back when I found something.

**Comment by waderyan** [comment] 2016-10-12 18:58
Ok that will be helpful. We are aware that you are not using TypeScript. The TypeScript language service powers both TypeScript **and** JavaScript in VS Code.

**Comment by mjbvz** [comment] 2016-12-01 23:46
Closing as not actionable without more info.

@victorzhunjie Please try out a more recent version of VSCode. If you still see this problem, please add the setting:

```
"typescript.tsserver.trace": "verbose"
```

and upload the log generated in the `View -> Output` for `TypeScript`. As @waderyan noted, the TypeScript language service is also used for JavaScript.

Thanks.

**Closed by mjbvz** 2016-12-01 23:46 UTC
Labels: javascript, needs more info, perf
