### ISSUE TITLE
Files'opening problem

### ISSUE THREAD

**Issue by Gary43** [Microsoft/vscode#32727] opened 2017-08-17 16:03 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.7
vue-snippets|hol|0.1.2
vetur|oct|0.9.3
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**My Problem**: If I remove a project from the sidebar, I can't open it again.

**Comment by Bruemor33** [comment] 2017-08-17 17:18
This is also happening to me. Even after closing the program and re-opening, as well as after re-booting my machine.

Running Ubuntu 16.04 LTS

**Comment by bpasero** [comment] 2017-08-18 10:38
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Bruemor33** [comment] 2017-08-18 13:33
Running VS Code with the command provided didn't work. 

The only extra information I can give is that our code base is accessed through an ftp. So I'm assuming that is the root of my issue. Thing is we have 2 other ftp servers with two other code bases we work on and those are opening fine. Just not the one I need to do work in.

**Comment by bpasero** [comment] 2017-11-11 10:48
This should be fine now.

**Closed by bpasero** 2017-11-11 10:48 UTC
Labels: needs more info
