### ISSUE TITLE
When a font size with a decimal point is defined remotely (using the Remote - SSH extension) any overriding of the font locally doesn't take effect

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/vscode#106295] opened 2020-09-08 15:14 UTC
Issue Type: <b>Bug</b>

I have the font size set remotely that has a decimal point in it (the value is 13.5) and I am unable to set the font locally when this type of value is used.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Windows_NT x64 10.0.19041

**Comment by sandy081** [comment] 2020-09-09 09:38
When you are connected to remote, remote settings always override local settings. You have to update remote settings for the change to take affect.

**Comment by jethas-bennettjones** [comment] 2020-09-09 12:39
I think you've jump to a conclusion here, @sandy081.

If I set the font size without a decimal point, the local changes override the remote changes, but if the remote server has a decimal point in its value, the local settings won't override the remote settings.
So either it is designed to override the local settings or it is designed to not override the local settings, but a design where it overrides the local settings if it doesn't have a decimal point in it seems flawed to me.

I'd appreciate you taking another look at my issue. If you need further information from me then I will be pleased to provide it.

**Comment by sandy081** [comment] 2020-09-09 17:18
Can you please be clear about local change? Is this in User Settings or Workspace Settings? 

Can you also please provide steps to reproduce?

**Comment by jethas-bennettjones** [comment] 2020-09-09 17:27
Hi @sandy081,

Here is a screenshot of the value that I'm referring to: 
![Capture](https://user-images.githubusercontent.com/62298251/92631317-6b6ffa80-f28e-11ea-8ea2-4b01e3767f14.PNG)

If I go to the Remote tab and change it to a value with a decimal, and then come back to the user tab and change the font, the font doesn't change.

Reproduction:
1. Connect VS Code over SSH and open a file and the Settings (UI) pages side-by-side
2. Go to the Remote tab and change the editor.fontsize setting to have a decimal point
3. Go to the User tab and change the editor.fontsize setting to some random value
4. Note that the font size doesn't change
5. Go to the Remote tab and change the editor.fontsize setting to not have a decimal point
6. Note that the font of the text in the file immediately changes to the User setting value

I hope that's enough information. Let me know if you need any more detail and I'll provide it.

**Comment by sandy081** [comment] 2020-09-15 11:34
> 5. Go to the Remote tab and change the editor.fontsize setting to not have a decimal point

After above step, can you please open the file on disk `F1 > Preferences: Open Remote Settings` and let me know what font size value you have there in the file?

**Comment by jethas-bennettjones** [comment] 2020-09-15 13:58
I ran through the repo instructions and after step 5, here is what the Remote Settings file shows:
```
{
  "debug.console.fontSize": 12,
  "editor.fontLigatures": true,
  "editor.formatOnType": true,
  "css.lint.ieHack": "error",
"prettier.printWidth": 120,
"terminal.integrated.fontFamily": "'Cascadia Mono PL', monospace",
"editor.fontWeight": "300",
"editor.fontFamily": "'Casciadia Code PL','Fira Code',Consolas, 'Courier New', monospace"
}
```

**Comment by sandy081** [comment] 2020-09-22 12:43
> I think 14 is the default and that's why it's not appearing.

That explains, can you please try not using the default value and check if it works as expected?

**Comment by jethas-bennettjones** [comment] 2020-09-22 12:49
Hi @sandy081,

If I try setting the remote font size to 15 and change it in the user setting, it doesn't change.
It seems to work as described when the remote font setting is not set to the default.

**Comment by sandy081** [comment] 2020-09-22 13:13
When you set the value to default from the editor, editor removes the setting from the file and therefore user value is considered. 

Would like to close this since as it is working as described. Please let me know if you think otherwise.

**Comment by jethas-bennettjones** [comment] 2020-09-22 13:36
I'd argue against that, actually. If you look at it purely from the Settings UI, all the user is doing is changing a value; you'd have to go into the JSON file to know for certain if your change will make a difference or not.
If the Settings UI somehow showed the user that the default setting of 14 will mean that the setting in User will be picked up, that would be enough. Even a small line of text below the input box would be enough.
This is more a case of unexpected behaviour that can be resolved through proper communication rather than a bug that needs a coding fix.

**Comment by sandy081** [comment] 2020-09-29 21:22
Assigning to @roblourens as it is related to Settings UI

**Comment by roblourens** [comment] 2020-09-29 23:30
https://github.com/microsoft/vscode/issues/58038

**Closed by roblourens** 2020-09-29 23:30 UTC
