### ISSUE TITLE
Can't copy any text from extensions pages

### ISSUE THREAD

**Issue by roostercrab** [microsoft/vscode#69315] opened 2019-02-24 21:13 UTC
Issue Type: <b>Bug</b>

go to any extensions page and try to copy any text from there.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|1.0.6
Happy-Flasker|ape|0.0.6
All-Autocomplete|Ati|0.0.18
vscode-django|bat|0.19.0
django-html|bib|1.3.0
lit-html|bie|1.11.0
htmltagwrap|bra|0.0.7
copy-on-select|din|0.0.6
eppz-code|epp|1.2.41
vscode-toggle-column-selection|eri|1.0.3
auto-close-tag|for|0.5.6
code-runner|for|0.9.7
pgsql-html|hub|0.0.7
path-autocomplete|ion|1.13.1
theme-karyfoundation-themes|kar|18.2.1
vscode-smart-column-indenter|lmc|0.0.13
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
leaper|Onl|0.5.3
color-tabs-vscode-ext|ore|0.4.6
ruby|reb|0.22.1
vscode-yaml|red|0.3.0
vscode-icons|rob|8.2.0
git-merger|sha|0.4.1
django-intellisense|sha|0.0.2
bunker|sld|1.1.6
rewrap|stk|1.9.1
vscode-djaneiro|the|1.4.2
highlight-matching-tag|vin|0.8.6
rainbow-tags|vol|0.0.3
html-snippets|wge|0.1.5
toolbox|Yeh|1.0.8

(46 theme extensions excluded)

</details>

**Comment by Almenon** [comment] 2019-02-24 22:18
> AREPL for python

> AREPL automatically evaluates python code in real-time as you type

> real-time python scratchpad

I'm able to copy text. What part specifically are you having trouble copying?

**Comment by roostercrab** [comment] 2019-02-25 04:56
Specifically I needed to copy some code from the Toggle Column Selection
extension, and in making a demonstration video I found that I still can't
copy with cmd-C, but I *can* copy from the Copy option in the edit menu.

This is on a MacBook Pro, latest Mojave

**Comment by sandy081** [comment] 2019-02-25 08:38
Looks like the user is trying to copy text from the web view.

**Comment by roostercrab** [comment] 2019-02-25 09:18
There is a webview within the program? I'm in vscode still...

**Comment by jpenna** [comment] 2019-03-01 08:20
There are some configurations for the extensions that I would like to copy, but the text is not "copiable". I would like this feature too.

<img width="1507" alt="screen shot 2019-03-01 at 4 20 09 pm" src="https://user-images.githubusercontent.com/16005946/53625392-eee27180-3c3d-11e9-8949-38d3c97d72e4.png">

**Comment by roostercrab** [comment] 2019-03-01 17:46
jpenna, in the interim time you can copy the text with the copy option from the Edit drop-down menu I found.

**Comment by Daniel-McCarthy** [comment] 2019-04-16 13:04
I was not able to reproduce this on version 1.33.1 with Linux x64 4.15.0-47.
Is this still an active issue?

I was able to copy the shown text from VS Code with Ctrl+C.
```
{
    "phpcs.ignorePatterns": [
        "*/ignored-file.php",
        "*/ignored-dir/*"
    ]
}
```

**Comment by roostercrab** [comment] 2019-04-16 15:06
It's from the Extensions page that we can't copy and yes it's still an
issue with the latest version.

**Comment by Daniel-McCarthy** [comment] 2019-04-16 15:53
Yes, I tested by copying from the extension page in VSCode as was shown in an above comment.

It seems this effects some people differently. Fair enough, thanks for letting me know!

**Comment by roostercrab** [comment] 2019-04-17 06:07
For what it's worth, it's on a Macbook Pro running Mojave. I can copy from
the extensions page if I go to the menu and choose copy after I highlight
the section I want, but cmd-C doesn't work like it does everywhere else on
the Mac...

Thanks for looking into this. :)

**Comment by luxcium** [comment] 2019-05-15 10:35
I am so happy that this is still open I find it so annoying as I always have to open the extension page to copy/paste this might be a problem only for Mac users and since it’s not the biggest problem of them all I was scared that no one will ever want to put the effort to find the solution because all other important features and backlog I assume you guys have ... Since I have no idea what might be a good place to start investigate for a solution I think we will have to rely on you ho! Great Lord Maintainer !!!

**Comment by askhogan** [comment] 2019-07-04 21:46
This is an issue for me. I am on Mac OSX Mojave 10.14.5. It is quite annoying bc when you install an extension and attempt to configure it, you can't copy the example config options. My workaround is to 

1. Open the extension in my web browser by going to VS Code Marketplace
2. Open the default settings for VS Code - once you install an extension - the VS Code default settings will have the extensions settings listed. 
3. Use edit copy from the menu

**Comment by bsmith-cycorp** [comment] 2019-07-12 16:23
I too am having this problem. I'm also on MacOS Mojave. The Edit menu shortcut did work for me, thankfully; even right-clicking wasn't working in this context. Super annoying, as extensions frequently include example configurations on their pages that are desirable to copy-and-paste.

**Comment by m-thomson** [comment] 2019-07-20 21:41
I'm seeing the same problem here on Mojave and VSCode version 1.36.1

I just made the switch from WebStorm and encountered this issue setting up my very first project. 

Not a good look. I mean... someone had to actively disable the default system functionality of CMD+C for this to happen. And _then_ go through the trouble of also disabling right click. Obnoxious.

Breaking core OS functionality is **not cool**.

**Comment by shoaibsharif** [comment] 2019-09-09 06:30
any solution yet? I still have the same problem. I'm on Mojave and VSCode 1.380. Before reading this issue, I figured out that I can copy from Edit > Copy that I had to every time I want to copy from the extension page. Very annoying.

<details>
<summary>VSCode Summary</summary>
Version: 1.38.0 <br>
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35 <br>
Date: 2019-09-03T21:47:00.464Z <br>
Electron: 4.2.10 <br>
Chrome: 69.0.3497.128 <br> 
Node.js: 10.11.0 <br> 
V8: 6.9.427.31-electron.0 <br> 
OS: Darwin x64 18.7.0 <br>
</details>

**Comment by mjbvz** [comment] 2019-10-23 22:13
Would be fixed by https://github.com/microsoft/vscode/issues/83188

**Comment by mjbvz** [comment] 2019-10-24 01:47
Actually already tracked by #65452

**Closed by mjbvz** 2019-10-24 01:47 UTC
Labels: bug, extensions, help wanted, webview

**Comment by vbabak** [comment] 2019-12-02 14:01
Can confirm for macOS the only option is using menu "Edit" -> "Copy". 
No right click or cmd+c/ctrl+c available.
