### ISSUE TITLE
Debugging Firebase cloud function emulator inside  WSL locks up the debugger

### ISSUE THREAD

**Issue by alenl** [microsoft/vscode#126912] opened 2021-06-22 14:28 UTC
Issue Type: <b>Bug</b>

(This seems to have been introduced in 1.57. Verified multiple times that it works well in 1.56, and doesn't in 1.57.0 nor 1.57.1)

0. Open a workspace on Windows from within a WSL (maybe that happens in other enviroments as well, didn't test).
1. Run a Firebase functions emulator with --inspect-functions
2. Use a node attach debug action to attach to the emulator
3. Place a breakpoint in an `functions.https.onCall` function
4. Curl the URL so that the breakpoint is triggered
5. Observe that the debugger has correctly stopped at the breakpoint
6. Try to single-step (F10) - this fails
The debugger is now *locked up* so thouroughly that it doesn't respond to any commands. The rest of VSC UI still works normally, just the debugger is useless. Cannot even be detached or stopped. The only recourse is to kill the entire VSC and start it again.
Note: at step 6. above if you try to stop/disconnect (instead of stepping), then it successfully disconnects. Just any other action that requires the debugger to do some communication, locks it up.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
vscode-firefox-debug|fir|2.9.4
remote-wsl|ms-|0.56.5
debugger-for-chrome|msj|4.12.12
vscode-markdownlint|Dav|0.42.1
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.0
vscode-typescript-tslint-plugin|ms-|1.3.3
markdown-preview-enhanced|shd|0.5.21

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615cf:30323120

```

</details>

**Comment by connor4312** [comment] 2021-06-22 18:25
Interesting, I suspect this is the same root cause as https://github.com/microsoft/vscode-js-debug/issues/1033. You can give the [nightly debugger](https://github.com/microsoft/vscode-js-debug#nightly-extension) a spin which might fix this. If so, let me know and I will close this as a dupe. If not:

/jsDebugLogs

**Closed** 2021-06-30 11:29 UTC
Labels: debug, needs more info
