### ISSUE TITLE
when editing cpp files with nested #if directives, screen becomes zig zag jig jag

### ISSUE THREAD

**Issue by showching** [Microsoft/vscode#57921] opened 2018-09-05 01:45 UTC
- VSCode Version: 1.26.1
- OS Version: CentOS 7.5
- C/C++ Extension Version: 0.18.1

Steps to Reproduce:

1. **Install and enable Microsoft C/C++ extension**
2. Maximize VS Code window (optional but helps to reproduce)
3. Use the sample code below: test.cpp
4. I remember the issue does not exist before 1.26

``` cpp
#include <iostream>

int main(int argc, char* argv[])
{
#if VERBOSE
  std::cout << "Whatever"
      << ", ErrorID=" << pRspInfo->ErrorID << ", ErrorMsg=" << pRspInfo->ErrorMsg
      << ", Good=" << pAnGreatObject->Good << ", Description=" << pAnGreatObject->Description 
      << ", Name=" << pAnGreatObject->Name << ", ActionFlag=" << pAnGreatObject->ActionFlag
      << ", ActionDate=" << pAnGreatObject->ActionDate << ", ActionTime=" << pAnGreatObject->ActionTime
      << ", UserID=" << pAnGreatObject->UserID
      << std::endl;
#if CDE
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#elif EFG
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#else
  std::cout << "Whatever"
      << ", ErrorID=" << pRspInfo->ErrorID << ", ErrorMsg=" << pRspInfo->ErrorMsg
      << ", Good=" << pAnGreatObject->Good << ", Description=" << pAnGreatObject->Description 
      << ", Name=" << pAnGreatObject->Name << ", ActionFlag=" << pAnGreatObject->ActionFlag
      << ", ActionDate=" << pAnGreatObject->ActionDate << ", ActionTime=" << pAnGreatObject->ActionTime
      << ", UserID=" << pAnGreatObject->UserID
      << std::endl;
#endif
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;

#else
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#endif
}
```

**The screenshot of the bug**
![vscode-bug](https://user-images.githubusercontent.com/11239092/45066065-13c2b580-b0ef-11e8-9b2b-3fcf6cd05974.png)

**Was reported here**
https://github.com/Microsoft/vscode-cpptools/issues/2481

Does this issue occur when all extensions are disabled?: No

**Comment by sean-mcmanus** [comment] 2018-09-05 02:05
The duplication detection is incorrect.

The bug repros with our C/C++ extension enabled because we add transparent text rendering for inactive regions, which exposes some rendering bug with VS Code, but I'm pretty certain it's not a bug with our extensions. The bug only seems to repro on certain machines, so it seems like some low level rendering issue.

**Comment by bpasero** [comment] 2018-09-05 04:33
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by showching** [comment] 2018-09-05 08:44
By using the exploration build, the issue does not appear. But it doesn't mean the issue is fixed, as you can seen in the screenshot, the inactive region is not rendered correctly or not distinguished, just like the extension is disabled.

![vscode-bug2](https://user-images.githubusercontent.com/11239092/45081752-77b69f80-b12a-11e8-8790-090196791fb2.png)

**Comment by bpasero** [comment] 2018-09-05 08:55
@showching it is not clear to me why the region would show with opacity at all?

**Comment by bpasero** [comment] 2018-09-05 10:16
@showching in the exploration builds these gray zones seem to be missing right? can you open dev tools and inspect the tokens to find out if the CSS class is correctly set to show transparent where it should be?

**Comment by showching** [comment] 2018-09-05 11:00
Both the html and css looks different, could it be caused by the error happened in the extension?
<img width="1850" alt="1" src="https://user-images.githubusercontent.com/11239092/45089163-e51ffb80-b13d-11e8-9807-ff628a7d912d.png">

**Comment by showching** [comment] 2018-09-05 11:07
Yes, it looks like some CSS class not applied. Could it be caused by the extension error, see below screenshot.
![1](https://user-images.githubusercontent.com/11239092/45089474-e1d93f80-b13e-11e8-9f57-5d524618715e.png)

**Comment by bpasero** [comment] 2018-09-05 11:27
@showching I do not think the error is related. I think this is an issue with the extension and not with VSCode. Maybe your configuration is different between the 2 versions of VSCode that could explain this?

Closing as the result does not indicate an error to me in the area of Electron update.

**Comment by showching** [comment] 2018-09-05 13:06
@bpasero  I don't understand the reason to close it. I reported the rendering issue against 1.26.1. But you asked me to test against the exploration build. The test result in the exploration build (not able to reproduce the rendering issue because of extension compatibility), doesn't prove the issue not exist in VSCode, especially version 1.26.1.

**Comment by showching** [comment] 2018-09-05 13:34
@bpasero I tested against 1.25.1, the issue does not exist, it's an regression issue starting from 1.26, it doesn't mean it will be fixed in later release, it's a regression.

**Comment by showching** [comment] 2018-09-05 13:40
I also tested against latest Insiders build, the issue exist only when the --disable-gpu option is set, for 1.26.1, the issue exist either with or without the --disable-gpu option.

**Comment by sean-mcmanus** [comment] 2018-09-05 18:50
@bpasero The exploration build crashes when I use Help->Welcome on Windows -- I'm not sure if I should report a bug on that.

Yeah, if there's some breakage involving our extension not rendering the opacity we can investigate. I don't think we can be sure the rendering is fixed though until we can get the opacity to render correctly, because the opacity is known to be a requirement for the repro.

But I'm also not able to download any extensions (endless progress bar in the extensions pane) -- so I can't investigate what is causing our extension to not render opacity with the exploration build.

**Comment by showching** [comment] 2018-09-06 05:05
I upgraded VS Code to 1.27 today, and the issue only exist when I set the --disable-gpu option. This is the same result I test against the Insiders build yesterday.

**Comment by bpasero** [comment] 2018-09-06 06:15
@sean-mcmanus if you see any issues with the exploration build, yes please report them! I can open the Welcome page and install extensions on Windows 10. Please provide as much details as you can.

@showching maybe you could provide the code snippet to @sean-mcmanus how to reproduce the missing opacity region.

**Comment by sean-mcmanus** [comment] 2018-09-06 18:40
@bpasero I'm no longer reproing the crash with the Welcome screen (maybe it was due to the Azure outage?). I was able to install the extension and get our transparent/inactive text to appear.

@showching Were you able to get the transparent text to appear? The default/empty settings should work. If you set the C_Cpp.loggingLevel to "Debug" you can check the logs for any errors that could be occuring. No opacity would suggest the IntelliSense feature is failing for some reason. You could file an issue in our repo.

**Comment by showching** [comment] 2018-09-07 01:28
@sean-mcmanus I have set C_Cpp.loggingLevel to "Debug", but not seeing any other error except the DeprecationWarning. Does this mean it's an extension bug or should I look somewhere else for logging?
![2](https://user-images.githubusercontent.com/11239092/45193352-28828300-b280-11e8-914f-abd546077451.png)

**Comment by showching** [comment] 2018-09-07 01:32
@sean-mcmanus Maybe this is the log you mentioned
[output-from-c_cpp-extension.zip](https://github.com/Microsoft/vscode/files/2359201/output-from-c_cpp-extension.zip)

**Comment by sean-mcmanus** [comment] 2018-09-07 01:59
@showching I don't see any related errors in those logs. IntelliSense appears to be working (giving back 2 errors). I don't know what is going wrong. Does hovering over the inactive regions correctly give no tooltips? Does setting the inactiveRegionForegroundColor work? Are you able to use some other feature that uses opacity to see if that works?

**Comment by showching** [comment] 2018-09-07 02:13
@sean-mcmanus I find the trick, if I open a single file, the opacity is not taking effect, if I open the containing folder, the opacity works.

**Comment by sean-mcmanus** [comment] 2018-09-07 02:27
@showching Okay, yeah, I repro it -- that appears to be a bug (or possibly a "by design" issue) with our extension -- error squiggles also don't appear in this case. I could file a bug for you if you want. I would recommend using "open folder" instead if you want to use our features. Our support for "open file" is minimal.

**Comment by showching** [comment] 2018-09-07 02:42
@sean-mcmanus thanks for the help, and thanks for file a bug for me, it could be a lower priority bug.

@bpasero finally, I can test in exploration build and the rendering issue disappear, either with or without --disable-gpu option set. Do you have a schedule when to release the exploration builds? Thanks.

**Comment by sean-mcmanus** [comment] 2018-09-07 03:14
@showching It appears that we intentionally disable the gray text (and squiggles) in "open file", because otherwise the experience is bad since we rely on configurations/settings saved per-folder/workspace...so it's "by design".

**Comment by showching** [comment] 2018-09-07 03:19
@sean-mcmanus Ok, I understand, thanks!

**Comment by sean-mcmanus** [comment] 2018-10-25 19:45
@bpasero FYI, a user reported bad scrolling/lag with inactive regions with VS Code (C++ extension), but using the Exploration build fixed the issue for them.

**Comment by bpasero** [comment] 2019-01-25 16:24
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:24 UTC
Labels: electron, fixed-in-electron-3.0.x, upstream
