### ISSUE TITLE
Script tags new line behaviour

### ISSUE THREAD

**Issue by mrlg255** [microsoft/vscode#39128] opened 2017-11-25 11:39 UTC
- VSCode Version: 1.18.1
- OS Version: Win10 x64

Steps to Reproduce:

1. Create <script> tags
2. New line inside those tags

I suppose that intended behaviour is to create additional newline and autoindent. As for now only workaround, that worked for was to edit vscode-emmet-helper\out\expand\expand-full.js@line: 48..

Mockup:
Expected:
![Intended(?)](https://i.imgur.com/iGbM8GA.png)
Actual:
![Present](https://i.imgur.com/q3LZC9O.png)

Reproduces without extensions: Yes

NOTE: Another thing is that '\n's in emmet snippets don't seem to work, for example: "tag": "tag\n\n\ntag" results in "tag   tag"

**Comment by ramya-rao-a** [comment] 2017-11-27 04:20
@aeschli The absence of an indented newline when pressing ENTER between script tags happens even without emmet in play. Use the below in an html file

```
<div>
    <script></script>
    <p></p>
</div>

<script></script>
<p></p>
```

Try pressing ENTER in all the 4 cases above between the opening and closing tags.
All 4 cases except the case of the `script` tag inside the `div` tag, an indented blank line is added between the opening and closing tags.

@mrlg255 Please log a separate issue for the `\n` in custom emmet snippets

**Comment by aeschli** [comment] 2017-11-27 07:42
As the cursor is right where JavaScript starts, likely the auto indent rules of JavaScript are used.
@rebornix I thought we had a duplicate of that once. For the auto indent, we should consider the language on the left side of the cursor.

**Comment by rebornix** [comment] 2017-11-27 18:24
@aeschli to archive the expected result above 

![Intended(?)](https://i.imgur.com/iGbM8GA.png)

we need to write a proper onEnter rule for `<script>|</script>`, indentation rules don't take care of inserting a new line between `<script>` and `</script>`. That's also how we manage pressing enter between `{` and `}` generally https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/onEnter.ts#L63 . To me, it sounds like a feature request for HTML, @aeschli what do you think?

**Comment by aeschli** [comment] 2017-11-30 08:55
![image](https://user-images.githubusercontent.com/6461412/33420825-57812a9c-d5b0-11e7-85cd-db9f70725e34.png)

@rebornix Looking at the scopes at the location of the cursor you see that a JavaScript scope starts, so we use the JavaScript language configurations which don't have an enterRule for `<...>`.
I'm arguing the bug is to take the JavaScript language configurations here. Instead we should look at the language *before* the cursor, which is html and has an enterRule for `<...>`.

If you think about it, 'onEnter' always relates to what's before, so this IMO the right thing to do.

**Comment by chgc** [comment] 2019-04-18 09:34
Any update on this issue? I am having the similar situation. 

When I type `style` , tap and press enter, I feel it should behavior like other html tag. It should create a new line and indent, then I can start edit css style from there. 

I found #31709 issue that had the same problem. It has been referenced to another issue. and closed.

**Comment by alexandrudima** [comment] 2019-10-24 21:33
@aeschli This simply cannot work with the way HTML tokenizes today because in `<script></script>` the `<` in `</script>` is marked with the language javascript. 

With the code on master, the `<` in `</script>` is chosen as a reference, so it picks the language javascript and the enter actions of JS and evaluates them with `beforeText: '', afterText: '<'`.

After I do the following change (to pick the character to the left of enter)
![image](https://user-images.githubusercontent.com/5047891/67527090-6d50bf80-f6b6-11e9-8faa-7ac8ccdb447a.png)

it will pick html for the enter actions and will evaluate them with `beforeText: '<script>', afterText: ''`. Note how the `afterText` is empty, and that is because the `<` in `</script>` is marked with the language javascript, and on enter rules cannot be evaluated across languages. So the rule defined [here](https://github.com/microsoft/vscode/blob/fe2da71dd9b8dfbb14916edbfc7b59f1b86b1b35/extensions/html-language-features/client/src/htmlMain.ts#L132-L136) fails to match because `afterText` is empty.

**Comment by aeschli** [comment] 2019-10-25 08:19
We use https://github.com/textmate/html.tmbundle as the HTML grammar and the issue is https://github.com/textmate/html.tmbundle/issues/65.

They don't have plans to fix this, so I 'm also closing this issue as won't fix.

**Closed by aeschli** 2019-10-25 08:19 UTC
Labels: html, under-discussion
