### ISSUE TITLE
openNativeConsole cannot have Custom Keybinding

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9706] opened 2016-07-25 14:46 UTC
Because of issue #7904 I was needing to set a different keybinding for openNativeConsole. However, it is not respecting the keybinding being set in keybindings.json. No matter what I try to set ctrl+shift+c remains the keybinding.

This may also be happening with ctrl+shift+v and preview.

- VSCode Version: 1.4.0-insiders 7/25
- OS Version: Windows 10

Steps to Reproduce:

1. Set a new keybinding for openNativeConsole
2. test copying text in the console input.

**Comment by gerane** [comment] 2016-07-25 15:03
just noticed that ctrl+v actually works for pasting into the terminal.

**Comment by kieferrm** [comment] 2016-07-26 00:14
Duplicate of #7269.

**Closed by kieferrm** 2016-07-26 00:14 UTC
Labels: duplicate
