### ISSUE TITLE
Error message box doesn't show complete message

### ISSUE THREAD

**Issue by nonameolsson** [Microsoft/vscode#31231] opened 2017-07-21 22:34 UTC
- VSCode Version: 1.15.0 Insider
- OS Version: MacOS 10.12.5

Steps to Reproduce:

1. Try to check for updates
2. Get error message

Reproduces without extensions: Yes

I get the same error as in #27928. But I don't want to report that issue. What I want to submit is that it's not possible to read the full error message.
<img width="1299" alt="screen shot 2017-07-21 at 13 27 31" src="https://user-images.githubusercontent.com/1493018/28484877-a7bb669a-6e3a-11e7-82e1-03821ccf1c9f.png">

It would be better if the message box would show multiple lines.

**Comment by isidorn** [comment] 2017-07-24 07:32
We are working on improving our notification UX and you can find issues about this in our repository.
Closing as duplicate of the notifaction work

**Closed by isidorn** 2017-07-24 07:32 UTC
Labels: insiders
