### ISSUE TITLE
Use require logic for typescript.tsdk

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#9515] opened 2016-07-20 03:39 UTC
- VSCode Version: 1.3.1

In the `settings.json` you can configure the path for `typescript.tsdk`.
You _can_ use an absolute path which _always_ finds a TypeScript language server (at least if it is available), but you can't have different versions of TypeScript for different projects.
You _can_ use a relative path (like `node_modules/typescript/lib`) which allows you to use different versions of TypeScript for different projects, but it _can't_ find a TypeScript language server, if `node_modules/typescript/lib` isn't in your root (e.g. if you use multi-package repositories or multiple independent examples in one repository).

It would be nice, if vscode could just try to `require` `typescript/lib` relative to the current opened TypeScript file which would probably be the most natural way.

**Comment by kieferrm** [comment] 2016-07-20 16:50
@donaldpipowitch Seems to me there are couple of potentially different issues here.
1) Configuring `typescript.tsdk` in your workspace settings rather than your user settings does not work correctly
2) You open a parent folder in vscode to get access to different typescript projects within a single editor window assuming that each project is treated differently/correctly. That's something we don't support right now. 

I assume your issue is the second and close this one as a duplicate of #396. Pls open a new issue if 1) is a problem (too).

**Closed by kieferrm** 2016-07-20 16:50 UTC
Labels: duplicate
