### ISSUE TITLE
TypeScript intellisense stopping after a while

### ISSUE THREAD

**Issue by farlock85** [Microsoft/vscode#52072] opened 2018-06-15 20:16 UTC
- VSCode Version: 1.24.1
- OS Version: Windows 10 x64

In larger TS files with TS 2.9.1 the intellisense stops working after a period of time. See attached screenshot:
![image](https://user-images.githubusercontent.com/1142915/41487586-828f3422-70a6-11e8-91e0-0c5da0a71c85.png)
I'm hovering over the keyword "querable", which was just refactored from "query".

It sends the correct information to TypeScript (line and col) but then gets an incorrect result back. The only way to solve this issue is to restart VSCode completely.

It looks like the TS server and GUI go out of sync somehow.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2018-06-15 20:28
Duplicate of https://github.com/Microsoft/vscode/issues/51960

**Closed by RMacfarlane** 2018-06-15 20:28 UTC
Labels: new release
