### ISSUE TITLE
Fuzzy search sort based on path proximity to currently editing file

### ISSUE THREAD

**Issue by rcywongaa** [microsoft/vscode#147631] opened 2022-04-18 15:31 UTC
When jumping between files, I am more likely to be jumping to a file "closer" (path-wise) to the currently editing file, than to a completely unrelated file in another directory / package.

e.g. when editing a `*.cpp` file and switching to a `CMakeLists.txt` file, most likely, I want to switch to the "nearest" `CMakeLists.txt` file, not the `CMakeLists.txt` file of another completely unrelated package in another directory.

I used to accomplish this by proximity sorting the results of the fuzzy search through https://github.com/jonhoo/proximity-sort

It would be great if this optional was available or more generally, it would be great if some hook could be provided for arbitrary sorting behavior of fuzzy searching results.

Candidate to be added to this list: https://github.com/microsoft/vscode/issues/27317

**Comment by TylerLeonhardt** [comment] 2022-04-19 21:16
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/5806

**Closed** 2022-04-19 21:17 UTC
Labels: *duplicate
