### ISSUE TITLE
C# - symbol rename across files should automatically save all files affected.

### ISSUE THREAD

**Issue by mattcbaker** [Microsoft/vscode#48675] opened 2018-04-25 13:01 UTC
It would be great if the rename symbol functionality saved each file that the rename affected. I'm typically writing code against a running `dotnet watch test` -- tests start to fail after a rename across files. This isn't a huge deal, but I usually stop and say "wait, what did I break", followed by "oh, I need to save all these files that the rename changed".

What does everyone else think? 

- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:
1. Create C# project.
2. Add two classes, in separate files.
3. Add a method to one class and reference it from the other.
4. Use the `rename` (shortcut F2) functionality to rename the method that is used in both files.

**Comment by mjbvz** [comment] 2018-04-27 21:14
Duplicate of #47573

**Closed by mjbvz** 2018-04-27 21:14 UTC
Labels: javascript
