### ISSUE TITLE
VScode shows this error: [js] Expression expected

### ISSUE THREAD

**Issue by victorhugoweb** [Microsoft/vscode#28147] opened 2017-06-06 20:02 UTC
VScode shows this error: [js] Expression expected

PS: i don't want  disable js  validation

```js


const loadSobre = () => import('./paginas/sobre'  );


```
 

![sem titulo](https://user-images.githubusercontent.com/29238083/26849222-b87e0aac-4ad9-11e7-8aa2-51c9f916d8e6.png)

**Comment by mjbvz** [comment] 2017-06-06 20:43
We currently do not support `import` expressions. This is being tracked upstream on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/14495 Hopefully this will be picked up in VSCode 1.14 for june

Closing as a duplicate of https://github.com/Microsoft/TypeScript/issues/14495

**Closed by mjbvz** 2017-06-06 20:43 UTC
Labels: duplicate, javascript, upstream

**Comment by lyquocnam** [comment] 2017-07-05 17:20
me too, hope will be fixed soon :3

**Comment by mjbvz** [comment] 2017-07-05 17:25
Support for dynamic import expressions is in the current insiders builds and will be in VScode 1.14
