### ISSUE TITLE
[Bug] Colour changes between versions ?

### ISSUE THREAD

**Issue by mirusky** [microsoft/vscode#204824] opened 2024-02-09 13:33 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.86.1 (system setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Windows 10 (10.0.19045)

Steps to Reproduce:

1. Download vscode version 1.85.2
2. Write a simple Go file
```go
// main.go
package main

import (
	"strings"
	strings2 "strings"
)

type A struct {
	B string
}

type IInterface interface {
	Test(a A)
}

func main() {
	strings.Contains("foo", "bar")
	strings2.Contains("foobar", "foo")
}

```
4. Update vscode to 1.86.1

Screenshots:
Before:
![image](https://github.com/microsoft/vscode/assets/54698990/0ff89276-2678-43dc-a658-c75dc45f89c3)
![image](https://github.com/microsoft/vscode/assets/54698990/dc73e67f-5623-49b3-8713-700b4213b520)

After:
![image](https://github.com/microsoft/vscode/assets/54698990/2c6c3c2d-92a8-401f-b28e-b056017f23ed)
![image](https://github.com/microsoft/vscode/assets/54698990/9325e171-b720-4073-be59-4ba3cbd61819)

Previously I had the [same issue with Go extension](https://github.com/golang/vscode-go/issues/2355), but now looks like vscode itself is causing it.

The workaround is downgrade the version.

**Comment by alexr00** [comment] 2024-02-09 14:55
Duplicate of https://github.com/microsoft/vscode/issues/203998

**Closed by alexr00** 2024-02-09 14:55 UTC
