### ISSUE TITLE
adding the option for panel groups of opened tabs to be minimized

### ISSUE THREAD

**Issue by hazho** [microsoft/vscode#111018] opened 2020-11-20 10:10 UTC
description:
in the main panel that can put many side panels for containing the tabs(of opened files), there is sometimes need to minimize specific group of tabs in order to focus on other group of tabs (the specific side panel)..!

screenshots:
![image](https://user-images.githubusercontent.com/20362375/99788125-9ebae980-2b5b-11eb-9107-80de3c43bc13.png)

**Comment by gjsjohnmurray** [comment] 2020-11-20 11:19
/duplicate of #109771 

Be sure to go there and click the 👍 at the end of the description there, because it needs at least 20 votes to get automatically moved to the Backlog.

**Closed** 2020-11-20 11:19 UTC
Labels: *duplicate
