### ISSUE TITLE
Improve startup deactivating extensions

### ISSUE THREAD

**Issue by Akhail** [Microsoft/vscode#40783] opened 2017-12-24 15:34 UTC
It should be possible to create job profiles that enable and disable extensions depending on the configured environment and in this way can be reused in other workspaces and that all others are disabled by default.

through the .vscode/settings.json of the project it should be possible to specify which profile has that workspace

**Comment by sandy081** [comment] 2018-01-08 10:40
@Akhail Are you asking for workspace profiles that has extensions to be used for that workspace?

**Comment by Akhail** [comment] 2018-01-10 01:26
Yes, example i have two profiles: python and javascript. I have the following extensions:
Magic python, git history, jinja, nodejs, npm, webpack
at workspace have the follow config:
{
"profile": "python"
}
when opening it only activate "magic python" and "jinja"

**Comment by sandy081** [comment] 2018-01-25 18:04
Duplicate of #40109

**Closed** 2018-01-25 18:04 UTC
Labels: *duplicate, extensions, feature-request
