### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#8611] opened 2016-07-01 10:25 UTC
- VSCode Version:  `git repository`
- OS Version: fedora21

Steps to Reproduce:

1. 

[luncher@localhost vscode]$ ./scripts/npm.sh install --arch=x64
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> windows-mutex@0.2.0 install /home/luncher/vscode/node_modules/windows-mutex
> node-gyp rebuild

make: Entering directory '/home/luncher/vscode/node_modules/windows-mutex/build'
  CXX(target) Release/obj.target/CreateMutex/src/main.o
../src/main.cc:2:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
CreateMutex.target.mk:91: recipe for target 'Release/obj.target/CreateMutex/src/main.o' failed
make: *** [Release/obj.target/CreateMutex/src/main.o] Error 1
make: Leaving directory '/home/luncher/vscode/node_modules/windows-mutex/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/luncher/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.1.13-100.fc21.x86_64
gyp ERR! command "/home/luncher/.nvm/versions/node/v6.2.0/bin/node" "/home/luncher/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/luncher/vscode/node_modules/windows-mutex
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:windows-mutex@0.2.0 windows-mutex@0.2.0 install: `node-gyp rebuild`
npm WARN install:windows-mutex@0.2.0 Exit status 1

**Comment by Luncher** [comment] 2016-07-01 10:36
1. 
  git clone https://github.com/microsoft/vscode  
  cd vscode  

2.   
./scripts/npm.sh install --arch=x64

**Comment by Luncher** [comment] 2016-07-01 10:38
Who can give me some advice do.

**Comment by bpasero** [comment] 2016-07-02 06:18
The build should not fail because windows-mutext is an optional dependency. @Luncher do you have NPM 3 running?

**Comment by Luncher** [comment] 2016-07-02 13:46
@bpasero 

[luncher@localhost vscode]$ npm -v
3.8.9

[luncher@localhost vscode]$ uname -a
Linux localhost.localdomain 4.1.13-100.fc21.x86_64 #1 SMP Tue Nov 10 13:13:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joaomoreno** [comment] 2016-07-05 08:39
Maybe duplicate of #7874.

I can read `npm WARN`. @Luncher this should only be a warning, it's not a problem. Does the command return non zero?

**Comment by Luncher** [comment] 2016-07-05 08:53
build successful, but can not run `./scripts/code.sh` @joaomoreno

**Comment by joaomoreno** [comment] 2016-07-05 09:15
OK. So what error do you get when running that?

**Comment by mrmlnc** [comment] 2016-07-05 10:00
@Luncher I think I know what's going on. Same problem on Windows with Node.js version 6. Both users have a Node.js version 6.

Please try the following instructions:

  1. Install Node.js version **5.11.1** or **5.12.0**
  2. Remove `node_modules` directory in the directory VS Code
  3. Run `./scripts/npm.sh install --arch=x64` and wait
  4. Run `/scripts/code.sh`

On windows:

<details>
  <summary>First run install command</summary>
  ```shell
$ if not defined npm_config_node_gyp (node "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Denis\AppData\Roaming\nvm\v6.2.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Denis\\AppData\\Roaming\\nvm\\v6.2.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\vs-t\node_modules\fsevents
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
code-oss-dev@1.4.0 C:\projects\vs-t
+-- ansi-regex@2.0.0
+-- applicationinsights@0.15.6

...

npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\vs-t\npm-debug.log
  ```
</details>

<details>
  <summary>Second run install command</summary>
  ```shell
  ```
</details>

**Comment by joaomoreno** [comment] 2016-07-05 10:08
No, that's not it.

@Luncher please don't add `--arch=x64` to `npm install` and try again.

**Closed by joaomoreno** 2016-07-05 10:08 UTC
Labels: needs more info
