### ISSUE TITLE
VS Code can crash after using Ctrl+F Find in Extension Preview window

### ISSUE THREAD

**Issue by ZStoner** [microsoft/vscode#230161] opened 2024-09-30 19:37 UTC
Type: <b>Bug</b>

When viewing details pages for extensions, you can do a <kbd>Ctrl+F</kbd> to search in the description text.
If you then click to view a different extension VS Code may crash and close.

#### Repro Example:
1. In VSCode, I viewed the details page for this extension: (_Clock in status bar_: `compulim.vscode-clock`)
2. In the details page, I hit <kbd>Ctrl+F</kbd> typed `gibberish`.
3. I then clicked on this extension to view details: (_Base64Viewer_: `jasonmejane.base64viewer`)
4. > _VS Code crashes after displaying the Extension's header info, but before it renders any of its description markdown._

#### Known Crashing conditions:
* Crash repros regardless of an actual text match from the Find box.
* Crash repros if the Find box has text at the time you choose a different extension.
* Crash _will not_ repro if the Find box was never invoked.
* Crash _will not_ repro if the Find box was closed before viewing the next extension.
* Crash _will not_ repro if the Find box is shown, but empty. This includes if the Find box previously had text, but then cleared the text and kept the Find box open.
* The specific extensions themselves don't seem to matter.  I just picked two in the Example for completeness of a concrete repro.

--------

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.57GB (12.40GB free)|
|Process Argv|--crash-reporter-id c92ccc20-b606-4a82-b062-2771a0b6c7b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
jsonl|Alp|0.0.1
vscode-json|and|1.5.2
fold-to-definitions|arg|1.7.8
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.25.0
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
vscode-coloured-status-bar-problems|bra|0.2.0
vscode-clock|Com|0.0.1
pastespecial|d3v|0.9.1
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.56.0
docs-article-templates|doc|1.0.7
docs-authoring-pack|doc|1.0.2
docs-build|doc|0.4.6
docs-images|doc|1.0.4
docs-markdown|doc|1.0.11
docs-preview|doc|1.0.9
docs-scaffolding|doc|1.0.8
docs-yaml|doc|1.0.5
learnlinter|doc|4.1.8
githistory|don|0.6.20
kusto|don|0.4.4
xml|Dot|2.5.1
vscode-html-css|ecm|2.0.10
LogFileHighlighter|emi|3.3.3
prettier-vscode|esb|11.0.0
html-preview-vscode|geo|0.2.5
mdmath|goe|2.7.4
json2ts|Gre|0.0.6
vscode-guid|hea|1.9.0
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
base64viewer|Jas|1.5.2
copy-markdown-as-html|jer|1.1.0
svg|joc|1.5.4
theme-by-language|jsa|1.3.0
sort-indentation-group|ken|1.1.0
Learn-Training-AI-Assistant|Lea|1.1.50
rainbow-csv|mec|3.12.0
code-point|med|1.11.0
ecdc|mit|1.8.0
vscode-json5|mrm|1.0.0
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.6
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
remote-containers|ms-|0.384.0
powershell|ms-|2024.2.2
material-icon-theme|PKi|5.11.1
highlight-counter|ram|1.6.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
kuskus-extensions-pack|ros|2.0.1
kuskus-kusto-language-server|ros|3.4.1
kuskus-kusto-syntax-highlighting|ros|2.0.4
trailing-spaces|sha|0.4.1
sort-json|Thi|19.1.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
gzip-unzip-text|xba|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
autoexpandse:31146404
iacca2:31144504
cc771715:31146322

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-09-30 20:42
/duplicate of https://github.com/microsoft/vscode/issues/177046

**Closed** 2024-09-30 20:43 UTC
Labels: *duplicate
