### ISSUE TITLE
Git diff visualization is shown after commit  

### ISSUE THREAD

**Issue by nvdv** [Microsoft/vscode#35881] opened 2017-10-09 08:51 UTC
- VSCode Version: 1.17.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce: 

1. Edit source file.
2. Stage edited file for commit.
3. Commit.
4. Observe that git diff visualization is still shown near line numbers (source control tab looks fine).

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2017-10-09 11:47
Can you reproduce this 100% of the time?

**Comment by nvdv** [comment] 2017-10-09 14:13
I made several commits today and observed this issue every time.

**Comment by joaomoreno** [comment] 2017-10-10 07:27
Duplicate of #35559

**Closed by joaomoreno** 2017-10-10 07:27 UTC
Labels: git, needs more info
