### ISSUE TITLE
go to definition F12 doesn't work after last night update

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#63507] opened 2018-11-20 15:10 UTC
Version: 1.30.0-insider (system setup)
Commit: dcc243c9920f0077e87e4a7befbc67c713a1709b
Date: 2018-11-19T06:19:56.999Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. In a Typescript file put the cursor over an identifier
2. Press F12
3. Observe nothing is happening

Expected: to navigate to the definition of the identifier

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2018-11-21 09:31
/duplicate of https://github.com/Microsoft/vscode/issues/63448

**Closed** 2018-11-21 09:31 UTC
Labels: *duplicate, editor-contrib
