### ISSUE TITLE
Characters entered out of order

### ISSUE THREAD

**Issue by rothskeller** [microsoft/vscode#76488] opened 2019-07-02 23:33 UTC
Issue Type: <b>Bug</b>

When I am running vscode on my rather slow laptop, it's normal for characters to appear a little while after I type them (maybe half a second or so).  If I type characters and then, before they appear, use the arrow keys to move the cursor, the characters appear at the new cursor location rather than where the cursor was when I typed them.  This is very frustrating; in essence vscode is handling my keystrokes out of order.

For example, suppose I type `functioncall("abc→→;`.  What should happen is that the two right-arrow keys should move past the closing quote and closing parenthesis that were automatically added, and put a semicolon after them, resulting in `functioncall("abc");`.  What actually happens, when vscode is running slowly, is that I get `functioncall("ab")c;` or even `functioncall("a")bc;`.

This behavior does not appear to be language-specific.  I have seen it both while editing Go code and while editing Javascript code.

I am aware that there is not enough information here to reliably reproduce the problem, but I do not know what additional information or debugging would be helpful.  I'll be happy to provide additional information on request.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
overtype|ada|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
graphviz-preview|EFa|1.3.3
git-project-manager|fel|1.7.1
rest-client|hum|0.21.3
code-select-until|jak|0.6.0
svg|joc|0.1.5
sftp|lix|1.12.7
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
Go|ms-|0.11.0
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
vscode-ginkgo|ons|0.0.1
java|red|0.46.0
sass-indented|rob|1.5.1
rewrap|stk|1.9.1
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.12.7
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
change-case|wma|1.0.0
FilterText|yhi|0.0.14
cursor-align|yo1|1.0.4

</details>

**Comment by rebornix** [comment] 2019-07-25 21:42
/duplicate of https://github.com/microsoft/vscode/issues/71238.

**Closed** 2019-07-25 21:42 UTC
Labels: *duplicate, bug, editor-contrib
