### ISSUE TITLE
Intellisense window blank and won't move out of way of cursor

### ISSUE THREAD

**Issue by jaitaiwan** [Microsoft/vscode#23411] opened 2017-03-28 12:49 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (0b19861f31ed27160c8ea73e55e39dd0213814a6, 2017-03-28T10:41:50.927Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|wallaby-vscode|WallabyJs|1.0.48|
|jsrefactor|cmstead|1.0.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|php-intellisense|felixfbecker|1.1.3|
|vscode-npm|fknop|3.3.0|
|vue|liuji-jim|0.1.5|
|Go|lukehoban|0.6.55|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|2.7.1|
|sass-indented|robinbentley|1.3.1|;

---

Steps to Reproduce:

1. Start typing to show intellisense
2. Intellisense window opens, is blank and will not go away

[Screenshot](http://imgur.com/a/dLItd)

**Comment by jaitaiwan** [comment] 2017-03-28 12:50
Probably a replication of #23407

**Comment by jaitaiwan** [comment] 2017-03-28 13:01
Just want to confirm that I've tried disabling all the plugins for the workspace and the same issue appears.

**Comment by aeschli** [comment] 2017-03-28 15:04
duplicate of #23414

**Closed by aeschli** 2017-03-28 15:04 UTC
