### ISSUE TITLE
Extensions: Allow disabling specific extensions

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode#9655] opened 2016-07-23 20:49 UTC
Allow extensions to be disabled. There are a bunch of them, which I know I won't use. But I might just need them at a certain point. While VSCode is quite clever and loads only while needed, there's still a bunch of stuff that's better left disabled in certain cases. Or while testing, it would very helpul to be able to switch them on and off. 

Also, it would be nice to have the disabled ones to NOT check for updates automatically while disabled. So, the sidebar only notifies on the extensions you care about. Its particularly annoying when it keeps showing up new notifications for extension you really don't care much about.

**Comment by joaomoreno** [comment] 2016-07-25 14:54
Duplicate of #2882

**Closed by joaomoreno** 2016-07-25 14:54 UTC
