### ISSUE TITLE
Launch.json Error

### ISSUE THREAD

**Issue by ijazsharif** [Microsoft/vscode#24333] opened 2017-04-08 22:08 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Unable to create 'launch.json' file inside the '.vscode' folder (Error: EPERM: operation not permitted, mkdir 'c:\Program Files\Microsoft VS Code\resources\.vscode').
2.

**Comment by ijazsharif** [comment] 2017-04-08 22:08
Please help me

**Comment by friedemannsommer** [comment] 2017-04-08 22:22
It looks like your current user doesn't have the permission to write a file to that directory.
Can you please fill out the "VSCode Version" field and the "OS Version" field.
When does this error occur?
Can you reproduce this?

**Comment by chrmarti** [comment] 2017-04-10 04:15
From #24332:

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|;

**Comment by chrmarti** [comment] 2017-04-10 04:18
@ijazsharif It looks like you opened VSCode on a folder in C:\Program Files. It's best to open a folder in your user directory where your account has full permissions.

**Comment by chrmarti** [comment] 2017-04-17 18:32
Closing after no additional info was provided.

**Closed by chrmarti** 2017-04-17 18:32 UTC
Labels: needs more info
