### ISSUE TITLE
Images does not update using JupyterNotebook

### ISSUE THREAD

**Issue by Handberg** [microsoft/vscode#154049] opened 2022-07-04 06:57 UTC
Issue Type: <b>Bug</b>

Insert a picture in a markdown cell

`![Picture` text](Picture.jpg)

If Picture.jpg is updated or changed, the picture in jupyternotebook does not update - even after "run all" or "clear output from all cells".

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (6 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.85GB (34.32GB free)|
|Process Argv|--crash-reporter-id 16dc5465-9271-42a7-bd3b-3ef6216b0e03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
preview-pdf|ana|1.0.0
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.1.1
vscode-drawio|hed|1.6.4
vscode-edit-csv|jan|0.7.1
rainbow-csv|mec|2.4.0
python|ms-|2022.8.1
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
ansys-apdl-syntax|smh|0.2.4
pyqt-integration|zho|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment] 2022-07-05 15:20
Duplicate of #151151

**Closed by mjbvz** 2022-07-05 15:20 UTC
