### ISSUE TITLE
VS Code uses OSX `cmd + down` convention in the Sidebar Explorer

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#20364] opened 2017-02-10 00:51 UTC
OSX made the wrong choice making `Enter` rename a file in Finder, and VS Code should not make the same mistake.

Can the default behavior in the Sidebar Explorer please be `Enter` > `Open`, `cmd + Enter` > `Rename`?

Or at least make this an easy setting to toggle... following this Finder convention makes using the sidebar a sad time. `cmd + down` to open a file? That's not great.

**Comment by Tyriar** [comment] 2017-02-10 00:54
@mherodev right now you can use F2 to rename in the explorer which is the Windows/Linux convention.

**Comment by mherodev** [comment] 2017-02-10 01:05
@Tyriar The issue isn't that renaming is assigned to `Enter` so much as that opening a file is assigned to `cmd` + `down`.

It's this way on OSX because this is the behavior in Finder, but I imagine the vast majority of VS Code users don't actually have that convention memorized as Finder is GUI-based.

e.g. http://pragmactic-osxer.blogspot.com/2007/07/keyboard-shortcut-to-start.html

**Comment by bpasero** [comment] 2017-02-10 07:32
@mherodev if you are willing to switch to our insiders build you can do this by configuring the explorer commands as outlined in https://github.com/Microsoft/vscode/issues/4557#issuecomment-276960041

Duplicate of #4557

**Closed by bpasero** 2017-02-10 07:32 UTC
Labels: explorer-files
