### ISSUE TITLE
Sticky scroll screen cheese

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#180711] opened 2023-04-24 15:15 UTC
1. Open a diff
2. Enable inline diff
    ![image](https://user-images.githubusercontent.com/30305945/234040180-a3c4372a-38ad-453c-879c-b39c158d1ddc.png)
3. :bug: The line numbers are slightly offset:

![image](https://user-images.githubusercontent.com/30305945/234039793-b7ccb9c4-379d-4a76-bce7-8997f3363688.png)

**Comment by aiday-mar** [comment] 2023-06-01 13:12
/duplicate of https://github.com/microsoft/vscode/issues/182276

**Closed by aiday-mar** 2023-06-01 13:12 UTC
Labels: bug, editor-sticky-scroll
