### ISSUE TITLE
Issue highlighting JS code when the property name starts with 'var'

### ISSUE THREAD

**Issue by intenter** [Microsoft/vscode#4455] opened 2016-03-19 13:06 UTC
- VSCode Version: Version 0.10.11 (0.10.11)
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Create a javascript file and enter following code:
```
expect(confNy.vars['config']).to.equal(
    `proxy=nyproxy.company.org1, port=8081`);
```
2. The code is highlighted this way:
![screen1](https://cloud.githubusercontent.com/assets/2051078/13898731/6ce79f22-edec-11e5-887b-05ade5ad9d30.png)

**Comment by aeschli** [comment] 2016-03-21 14:08
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-21 14:08 UTC
