### ISSUE TITLE
Bracket Pair Colorization - window.zoomLevel when set -1 or lower

### ISSUE THREAD

**Issue by ctafts** [microsoft/vscode#167897] opened 2022-12-02 00:46 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.73.1 (Universal)
- OS Version:  macOS 13.0.1 (22A400)

Steps to Reproduce:

1. add `"window.zoomLevel": -1`

window.zoomLevel set to 0 or higher
<img width="618" alt="Screenshot 2022-12-01 at 7 44 46 PM" src="https://user-images.githubusercontent.com/782892/205189271-616e1d10-0745-43c5-8e18-45ec4ee1f2c6.png">

window.zoomLevel set to -1 or lower
<img width="530" alt="Screenshot 2022-12-01 at 7 44 19 PM" src="https://user-images.githubusercontent.com/782892/205189225-95e60004-7bd7-4166-9c03-1602f91247dc.png">

**Comment by hediet** [comment] 2022-12-02 13:28
I cannot reproduce:

image.png
![Uploading image.png…]()

**Comment by ctafts** [comment] 2022-12-07 20:35
@hediet Hmm it seems to be working for me now as well 😂 I had changed
window.zoomLevel  to "window.zoomLevel":  -0.8 and it was working and then adjusting when needed with command +/- but now it seems to be working as expected. 

I also found another [open issue](https://github.com/microsoft/vscode/issues/139067) in regards to this

**Comment by hediet** [comment] 2022-12-09 10:51
Let's close this as duplicate of #139067

**Closed by hediet** 2022-12-09 10:51 UTC
Labels: feature-request, bracket-pair-guides
