### ISSUE TITLE
Renaming local variable in Javascript crashes with "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#1991] opened 2016-01-13 18:13 UTC
See this handy gif:

![visual-studio-fail](https://cloud.githubusercontent.com/assets/79215/12303205/e97ba5a8-b9dd-11e5-9ea0-2b852101ac42.gif)

Here's a snippy snip of the last line of the developer console:

    RangeError: Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
        at o (typescriptServices.js:10)
        at n (typescriptServices.js:10)
        at r (typescriptServices.js:10)
        at o (typescriptServices.js:10)
        at n (typescriptServices.js:10)
        at r (typescriptServices.js:10)
        at o (typescriptServices.js:10)
        at n (typescriptServices.js:10)
        at r (typescriptServices.js:10)
        at o (typescriptServices.js:10)e.doShow @ workbench.main.js:63
    workbench.main.js:16 Main Thread sent to worker the following message:e._onError @ workbench.main.js:16e._onmessage @ workbench.main.js:16e._onSerializedMessage @ workbench.main.js:16(anonymous function) @ workbench.main.js:16worker.onmessage @ workbench.main.js:19
    workbench.main.js:16 Object {type: "threadService", payload: Array[3]}
    workbench.main.js:16 And the worker replied with an error:e._onError @ workbench.main.js:16e._onmessage @ workbench.main.js:16e._onSerializedMessage @ workbench.main.js:16(anonymous function) @ workbench.main.js:16worker.onmessage @ workbench.main.js:19
    workbench.main.js:16 Object {stack: "RangeError: Maximum call stack size exceeded↵    a…ript/common/js/importAndExportRewriter.js:4:3903)", message: "RangeError: Maximum call stack size exceeded"}
    workbench.main.js:91 RangeError: Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
        at importAndExportRewriter.js:4
        at r (typescriptServices.js:10)
        at Object.o [as forEachChild] (typescriptServices.js:10)
        at e._visitNode (importAndExportRewriter.js:4)
        at e.visitBinaryExpression (importAndExportRewriter.js:4)
        at importAndExportRewriter.js:4
        at r (typescriptServices.js:10)
        at Object.o [as forEachChild] (typescriptServices.js:10)
        at e._visitNode (importAndExportRewriter.js:4)
        at e.visitBinaryExpression (importAndExportRewriter.js:4)

...?

**Comment by egamma** [comment] 2016-01-18 14:55
Can you attach the single file that produces the error?

**Comment by egamma** [comment] 2016-01-20 17:38
Closing as duplicate of #2054

**Closed by egamma** 2016-01-20 17:38 UTC
Labels: bug, js
