### ISSUE TITLE
Watermark: toggle terminal keybinding barely readable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14293] opened 2016-10-24 14:41 UTC
See 
![image](https://cloud.githubusercontent.com/assets/900690/19650203/b4240592-9a08-11e6-80b2-c979ad847dea.png)

For it looks like Ctrl F

**Comment by bgashler1** [comment] 2016-10-24 19:12
I'm not seeing the same problem
WIN:
<img width="516" alt="screen shot 2016-10-24 at 12 05 38 pm" src="https://cloud.githubusercontent.com/assets/11839736/19659866/715d3c68-99e2-11e6-90ed-eeedea3cbb19.png">

LINUX:
<img width="519" alt="screen shot 2016-10-24 at 12 12 24 pm" src="https://cloud.githubusercontent.com/assets/11839736/19660029/267b2e8e-99e3-11e6-948f-0e5358eb09ec.png">

**Comment by bgashler1** [comment] 2016-10-24 19:15
@chrmarti are you able to reproduce?

**Comment by bpasero** [comment] 2016-10-25 04:15
Note that I am on a german keyboard, but I checked the HTML and I am basically seeing this: `Ctrl+̂` See how the + and the ^ are on the same character for some reason.

**Comment by chrmarti** [comment] 2016-10-26 16:24
@bpasero There is just one character in the HTML? What does Quick Open show as the shortcut for that command? Also: What does the keybinding.json look like, I don't have a physical German keyboard handy and haven't figured out how to reproduce without it.

**Comment by bpasero** [comment] 2016-10-27 05:22
I cannot reproduce at home and I only saw it at work with an external german keyboard it seems. As far as I know I did not configure this keybinding in any way. I have to check back next week when I am in the office.

**Comment by bpasero** [comment] 2016-10-27 09:22
Hm maybe I had an old install on my Linux, I do not see this at home with my Linux box after updating to latest.

**Comment by bpasero** [comment] 2016-10-27 11:16
Actually could this issue be a duplicate of https://github.com/Microsoft/vscode/issues/14431 ?

/cc @alexandrudima

**Comment by alexandrudima** [comment] 2016-10-27 13:36
@bpasero Yes, that looks to me like Combining Circumflex Accent. The combining characters tend to jump around when they are not combined with anything. We should now render it as Circumflex Accent (aka `^`)

Also @bpasero I'd love to render these characters in red to indicate that they are special, but the `F1` list eventually brings everything down to a string and then to a group or something like that. Would it be possible to render a bit richer HTML for the keybindings in the F1 list?

**Comment by alexandrudima** [comment] 2016-10-27 13:37
It should be reproducible if you switch to a German keyboard layout with a layout similar to:

![image](https://camo.githubusercontent.com/7acd47da8677ca24757c60e068f408452d4c068e/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f332f33362f4b425f4765726d616e792e737667)

**Comment by bpasero** [comment] 2016-10-27 15:22
We can render anything in quick open including colors (see the quick open results when you just type "?" for example). Today the commands do not support colors for keybindings, but we can easily add that if needed.

**Comment by alexandrudima** [comment] 2016-10-27 15:25
@bpasero I'd love to get that! Created #14605 to track this.

**Comment by chrmarti** [comment] 2016-10-27 15:25
I can reproduce the original bug in 1.6, but not in 1.7 under Linux with default keybindings and German keyboard layout. Couldn't figure out which change fixed it by a quick glance over the relevant code in keybinding.ts / keyCodes.ts.

**Comment by alexandrudima** [comment] 2016-10-27 15:27
@chrmarti It is the change linked to in #14431 (49fb2f88b5b858b8bf2b11c517b072038c47d949)

**Comment by chrmarti** [comment] 2016-10-27 15:30
Thanks, closing as duplicate of #14431

**Closed by chrmarti** 2016-10-27 15:30 UTC
Labels: bug, needs more info
