### ISSUE TITLE
TypeScript server crashes with on output or restart option

### ISSUE THREAD

**Issue by scrossan-crown** [Microsoft/vscode#64435] opened 2018-12-05 14:50 UTC
- VSCode Version: 1.29.1
- OS Version: Windows 10

- Version: 1.29.1 (user setup)
- Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
- Date: 2018-11-15T19:13:36.375Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

Steps to Reproduce:

1. Working on a project and there is no indication as to why but js/ts intellisense stops working. There are no errors in the TypeScript output and I can't restart the server as the command is missing. This has happened to me a few times this week.

![image](https://user-images.githubusercontent.com/30405149/49521020-63568000-f89c-11e8-9aae-ef18fb3a8c50.png)

![image](https://user-images.githubusercontent.com/30405149/49521055-75382300-f89c-11e8-992b-c065a4c83e7a.png)

Does this issue occur when all extensions are disabled?: Not sure as it's not a consistent issue

**Comment by mjbvz** [comment] 2018-12-05 18:16
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by scrossan-crown** [comment] 2018-12-06 09:54
It works even better then before. Thanks been hampering my development speed for a couple of days and now it's faster than ever 😄

**Comment by scrossan-crown** [comment] 2018-12-06 10:47
I may have spoken to soon I'm now having an issue in the insiders build in the output `Log (Window)`
```
[2018-12-06 10:45:08.813] [renderer1] [info] no standard startup: not the explorer viewlet
[2018-12-06 10:45:22.101] [renderer1] [error] spawn code ENOENT: Error: spawn code ENOENT
    at _errnoException (util.js:1024:11)
    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-12-06 10:45:51.297] [renderer1] [info] no standard startup: panel is active
```

**Comment by mjbvz** [comment] 2018-12-06 22:29
@scrossan-crown That looks like a generic VS Code message. Does JavaScript and TypeScript intellisense stop working when you see this error?

Can you also please check the developer console to see if there is anymore information about the error:

1. Run the `Developer: Toggle developer tools` command in VS Code
1. Open the console section of the developer tools
1. Look through the console to see if there is any more detail about what process is causing this problem

**Comment by scrossan-crown** [comment] 2018-12-07 09:09
Yes it does unfortunately this does cause the JavaScript and TypeScript intellisense to stop working. After this issue I went through and disabled a bunch of extensions (including I assume the cause of the above error) and the intellisense is working fine now.

**Comment by mjbvz** [comment] 2018-12-07 19:41
Ok, closing this issue as caused by extension since it sounds like everything is working after disabling some extensions

**Closed by mjbvz** 2018-12-07 19:41 UTC
Labels: needs more info
