### ISSUE TITLE
Entering `}` when cursor is left of a `}` shouldn't overwrite it

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#45820] opened 2018-03-15 02:49 UTC
_From @willfaught on March 7, 2018 7:52_

Start with this:

```go
{"SyntaxImag1", SyntaxImag("1i")},
```

Now, SyntaxImag changes from `type SyntaxImag string` to `type SyntaxImag struct { Text string }`, so you must update the code to this:

```go
{"SyntaxImag1", &SyntaxImag{Text: "1i"}},
```

So, you insert the `&` and replace the `(` with a `{Text: `. Now you have:

```go
{"SyntaxImag1", &SyntaxImag{Text: "1i")},
```

Finally, you go to replace the `)` with `}`, but you end up with:

```go
{"SyntaxImag1", &SyntaxImag{Text: "1i"}, // Missing the outer }, because inserting the inner } overwrote the outer }
```

which is unexpected and invalid syntax.

_Copied from original issue: Microsoft/vscode-go#1563_

**Comment by ramya-rao-a** [comment] 2018-03-15 02:49
This is not Go specific. I see this happening on ts files as well

**Comment by rebornix** [comment] 2018-09-05 23:56
Duplicate of https://github.com/Microsoft/vscode/issues/37315

**Closed** 2018-09-05 23:56 UTC
Labels: *duplicate, editor, editor-find
