### ISSUE TITLE
autocomplete shouldn't suggest on empty word

### ISSUE THREAD

**Issue by payonel** [Microsoft/vscode#20481] opened 2017-02-11 17:28 UTC
Autocomplete suggestions should be completely reset/removed if the current word is removed/cleared
Something about the way I format as I code, I often hit a scenario.

- VSCode Version: Code - Insiders 1.9.0-insider (882244ea24cb0b89a9a0c6c649c8f857fb0bc408, 2017-01-23T07:03:07.900Z)
- OS Version: Linux x64 4.4.0-62-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lualinter|dcr30|1.0.3|
|python|donjayamanne|0.5.8|
|Lua|keyring|0.0.9|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|debug|webfreak|0.17.0|

---

Steps to Reproduce:
1. begin typing a word (autocompletion suggestions begin to display)
2. backspace the word out fully bringing the cursor back to where the word started
3. press enter (or tab, depending on what your 'accept suggestion' is set to)

Expected behavior
When you removed the word back to the first cursor position, the suggestions should be unloaded
You should get a literal newline (or tab)

Actual behavior
The suggestion box remained and the editor autocompletes

**Comment by jrieken** [comment] 2017-02-15 09:03
closing as dupe of #19240

**Closed by jrieken** 2017-02-15 09:03 UTC
