### ISSUE TITLE
Extensions View -> Check for updates hangs UI

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55430] opened 2018-07-31 08:26 UTC
Issue Type: <b>Bug</b>

1. Open the extensions view
1. Use the `...` menu to run `check for updates`
1. Try clicking around in the editor.

**Bug**
This hangs the VS Code UI while the check is occuring. 

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
color-info|bie|0.5.0
comment-tagged-templates|bie|0.2.0
emojisense|bie|0.4.1
folder-source-actions|bie|0.0.4
lit-html|bie|1.6.2
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-image-size|bie|0.0.2
markdown-mermaid|bie|1.0.0
speech|bie|0.0.2
vscode-svgviewer|css|1.4.4
dart-code|Dar|2.16.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
mdmath|goe|2.2.1
vscode-memfs|jri|0.0.3
theme-karyfoundation-themes|kar|18.0.1
hg|mrc|1.2.3
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
mssql|ms-|1.4.0
python|ms-|2018.7.1
azure-account|ms-|0.4.2
csharp|ms-|1.15.2
Go|ms-|0.6.85
vsliveshare|ms-|0.3.472
debugger-for-chrome|msj|4.8.2
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.1.0
Ruby|reb|0.18.0

(15 theme extensions excluded)

</details>

**Comment by ivanvoznyakovsky** [comment] 2018-08-17 07:38
this has been around for at least last 2 releases

**Comment by sandy081** [comment] 2018-08-27 15:57
Duplicate of #54041

**Closed** 2018-08-27 15:57 UTC
Labels: *duplicate, extensions
