### ISSUE TITLE
insider v1.29: Not working option"files.associations"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#62124] opened 2018-10-30 08:27 UTC
Does not apply to the Association of files with the file extension "*.tmpl"

Additional information: In the release version 1.28.2 all works well

- VSCode Version:
Версия: **1.29.0-insider (user setup)**
Фиксация: d8c42ed0045d290adb1783ac3e9c113bfc357def
Дата: 2018-10-30T06:19:51.721Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

- OS Version: win 7 pro

Steps to Reproduce:

1. set up "files.associations" as 
```
   {
      "*.tmpl": "html"
   }
```
![image](https://user-images.githubusercontent.com/3082812/47704920-2d3b3600-dc36-11e8-9f02-0946a6c2dc23.png)

2. open "*.tmpl" file
![image](https://user-images.githubusercontent.com/3082812/47704941-37f5cb00-dc36-11e8-8659-5b30b4924704.png)

**Comment by FernandoMiguel** [comment] 2018-10-30 10:28
duplicate of https://github.com/Microsoft/vscode/issues/62030

**Closed** 2018-10-30 10:34 UTC
