### ISSUE TITLE
CPU load increases to 100% after some time

### ISSUE THREAD

**Issue by lepinekong** [Microsoft/vscode#37122] opened 2017-10-30 08:21 UTC
- VSCode Version:  1.17.2
- OS Version: Windows 10
- Computer: Surface Pro 2017 iCore 5

Steps to Reproduce:

1. Open a folder with vscode from explorer
2. Let it open several min / hours even without using it
3. CPU load finally increase to 100%
4. Close VSCode CPU decreases to 10%

Reproduces without extensions: No

**Comment by isidorn** [comment] 2017-10-30 08:59
@lepinekong hi, can you please follow this page to give us more details that we need in order to be able to help
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by sc0ttwad3** [comment] 2017-10-31 16:57
I have the same issue as @lepinekong, and same steps to reproduce but don't need to wait as long, whereby **idle instances** of **VSCode** **_consume enormous amounts of CPU time_** that noticeably load the system (CPU usage averaging between 89%-98%). See the attached Process Explorer screenshots with two example instances and details. 

After reboots, shutting down all other applications, running one instance of VSCode idley and all obvious troubleshooting ideas exhausted, still the same huge CPU usage.

The main process thread consuming the majority of CPU time seems to be specifically:

**Code - Insiders.exe!lsSandboxedProcess+0x2c78da0**

Visual Studio Code - Insiders
Version 1.18.0-insider
Commit 81cca6cc606eeca3443998025bff3893fcfe3ad5
Date 2017-10-31T05:19:39.344Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Windows 10
HP Spectre x360
Intel Core i7-7500U CPU @ 2.70GHz
16.0 GB RAM

Two running examples, same behavior:

![vscode-insiders-processexplorer-4](https://user-images.githubusercontent.com/1682691/32235637-6c38864c-be36-11e7-8bd5-a84a328fa87a.jpg)
![vscode-insiders-processexplorer-1](https://user-images.githubusercontent.com/1682691/32234851-39b32148-be34-11e7-9df6-febdc7a7ad27.jpg)
![vscode-insiders-processexplorer-3](https://user-images.githubusercontent.com/1682691/32234856-3d6f7d54-be34-11e7-9fde-e9ee2225a8c3.jpg)

**Comment by bpasero** [comment] 2017-10-31 17:09
@sc0ttwad3 @lepinekong does it reproduce with any folder you open or particular ones?

**Comment by sc0ttwad3** [comment] 2017-10-31 20:48
@bpasero Just tried opening many different folders of differing varieties (C#, Rust, TypeScript, Julia) and projects.  Same behavior.

**Comment by sc0ttwad3** [comment] 2017-10-31 21:03
After launching the application, and then just letting it sit idle, it starts with about 75% CPU usage, then after about 1:40 run time it's up to full 99%. Graph here is 3:30 of run time where you'll see the abnormal CPU load, before it jumps to 99.9% for some reason.

![vscode-insiders-processexplorer-5-graph](https://user-images.githubusercontent.com/1682691/32248824-45b35016-be5d-11e7-9696-33fcb6188ac1.jpg)

**Comment by bpasero** [comment] 2017-11-01 05:46
@sc0ttwad3 does it also reproduce if you run "`code-insiders --disable-extensions --user-data-dir <some dir>`", this will run without extensions and create a total separate Code instance with separate data directories and settings.

**Comment by sc0ttwad3** [comment] 2017-11-01 17:11
@bpasero It doesn't reproduce!  Running Code without extensions and separate data/settings: negligible CPU usage, nice and quiet.  Running Code with just the extensions disabled: nice and quiet. That leads me to tracking down the **_culprit extension_**. Is there a better way than disabling one-by-one?

**Comment by bpasero** [comment] 2017-11-01 17:15
@sc0ttwad3 no unfortunately not

**Comment by sc0ttwad3** [comment] 2017-11-02 04:10
@bpasero After a lot of extension isolation testing, for me, the culprit is the **_Python Extension_** [donjayamanne.python](https://github.com/DonJayamanne/pythonVSCode).  When **enabled**, CPU usage grows to 99.9% within seconds; **disabled**, CPU usage returns to normal idle.  Screenshot below shows details for the two aberrant processes and associated threads when the plugin is enabled. You can see the normal CPU idle when disabled, then the sharp rise to 99.9% when enabled.

Surprising, because this extension is of the highest quality and has over 4 million downloads and I've never had a problem in the past. The heavy load on the system does however correspond to when I installed the extension on this laptop.

I find a similar issue for the plugin [pythonVSCode issue #1301](https://github.com/DonJayamanne/pythonVSCode/issues/1301) reported in its repo which appears to be related to a python background process, however.  With my issue, no python process is running and I'm opening project directories containing Typescript, Rust, C++, even empty directories, same behavior.
 
@lepinekong Are you still having the issue? I would really like to know its not something only occurring for me, as that would indicate an underlying issue unrelated to the extension, and avoid wasting everyone's time. Is it reproducible elsewhere is the question?

Currently running VSCode 1.18.0-insider commit 2ab10d50163f008ada9a4aa215de8c884857ce99 .

![pythonplugin-processexplorer-cpu-graph-02](https://user-images.githubusercontent.com/1682691/32309044-5a09b796-bf5f-11e7-9144-b3d94aa799e0.jpg)

**Comment by bpasero** [comment] 2017-11-02 09:42
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-11-02 09:42 UTC
Labels: needs more info, workbench

**Comment by sc0ttwad3** [comment] 2017-11-02 19:12
Exactly, appears to be extensions related.  Thanks.

**Comment by sc0ttwad3** [comment] 2017-11-14 06:16
Great find as to the culprit and how to disable the problem! [#2139 in VSCodeVim](https://github.com/VSCodeVim/Vim/issues/2139)

**Comment by sc0ttwad3** [comment] 2017-11-14 06:20
Great find as to the culprit! [#2139](https://github.com/VSCodeVim/Vim/issues/2139)
