### ISSUE TITLE
Keyboard Shortcuts with `Shift + Number` displays the _alt symbol_ instead of `Shift + Number`

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#114110] opened 2021-01-10 20:47 UTC
- VSCode Version:1.52.1
- OS Version:MacOS Catalina 10.15.7

Steps to Reproduce:

1. Create a command with a shortcut that contains `Shift + number`, like `Cmd + Shift + 1`

```json
    "keybindings": [
            {
                "command": "numberedBookmarks.toggleBookmark1",
                "key": "ctrl+shift+1",
                "mac": "cmd+shift+1",
                "when": "editorTextFocus"
            },
```
2. Add that command to the Editor Context Menu (submenus also has issue)
```json
    "editor/context": [
                {
                    "submenu": "numberedBookmarks.context.toggle",
                    "group": "numberedBookmarks@1"
                },
                {
                    "submenu": "numberedBookmarks.context.jump",
                    "group": "numberedBookmarks@2"
                },
                {
                    "command": "numberedBookmarks.toggleBookmark1",
                    "group": "numberedBookmarks"
                }
            ],
```
3. Look that the shortcut presented is not the shortcut itself, but `Cmd + _alt symbol_`

![Screen Shot 2021-01-10 at 17 40 01](https://user-images.githubusercontent.com/3781424/104134910-59e94d00-536b-11eb-9fab-31f66c2a3b27.png)

4. At the Command Palette, the shortcuts are just fine

![Screen Shot 2021-01-10 at 17 31 49](https://user-images.githubusercontent.com/3781424/104134909-5786f300-536b-11eb-9efd-22acefb9241c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2021-02-03 15:53
Duplicate of https://github.com/microsoft/vscode/issues/107383 . Unfortunately, this is an upstream Electron problem.

**Closed by alexdima** 2021-02-03 15:53 UTC
Labels: mac
