### ISSUE TITLE
hide tree view  persistence on workspace settings

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode#36380] opened 2017-10-17 03:51 UTC
there is many root tree view item when installed some plugins. so the real file explorer there is minimal space.   and i click `Hide from sidebar` but next open is still appear. 
can you persistence the hide opration to workspace settings.

or just let the high frequency tree view  in the root. others can fold theres  to one.

**Comment by sandy081** [comment] 2017-10-18 07:33
duplicate of #35462

**Closed** 2017-10-18 07:33 UTC
Labels: duplicate, workbench
