### ISSUE TITLE
Git - "Stage Selected Ranges" converts file from CRLF to LF line endings

### ISSUE THREAD

**Issue by HarveyKBrown** [microsoft/vscode#123557] opened 2021-05-11 10:10 UTC
Issue Type: <b>Bug</b>

Create a file using CRLF line endings (10+ SLOC)
I am using addon "Render Line Endings" to show line eding characters in a similar manner to the renderWhitespace option so that in the working tree view I can see what line endings are being used.
Push the CRLF file to git, then make a 2 line edit, open the file in git, highlight those 2 lines, right click and select "stage selected ranges"
Check the staged working tree, and note that the line endings for the entire file have changed to LF

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (2.71GB free)|
|Process Argv|--crash-reporter-id 4103ee79-a481-4554-bb91-018559eaaae4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-diff|fab|1.4.1
list-symbols|jmb|0.0.1
vscode-csharp-snippets|jor|1.1.0
rainbow-csv|mec|1.8.1
render-crlf|med|1.5.18
git-graph|mhu|1.30.0
csharp|ms-|1.23.11
cpptools|ms-|1.3.1
unity-debug|Uni|3.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by lszomoru** [comment] 2024-12-18 11:39
Closing as duplicate of [#96104](https://github.com/microsoft/vscode/issues/96104)

**Closed by lszomoru** 2024-12-18 11:39 UTC
Labels: bug, git
