### ISSUE TITLE
No code complete for jsconfig.json files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1252] opened 2015-12-14 11:56 UTC
Title says it all :-)

**Comment by dbaeumer** [comment] 2015-12-14 12:01
Works for tsconfig. User error.

**Comment by dbaeumer** [comment] 2015-12-14 12:02
![capture](https://cloud.githubusercontent.com/assets/1931590/11780538/e8e8a6c8-a262-11e5-9787-a64590f66d1a.png)

**Comment by aeschli** [comment] 2015-12-14 13:33
duplicate of #1246

**Closed by aeschli** 2015-12-14 13:33 UTC
