### ISSUE TITLE
C++ inheritence color on different line

### ISSUE THREAD

**Issue by animalvgamer** [Microsoft/vscode#58464] opened 2018-09-11 23:24 UTC
Issue Type: <b>Bug</b>

If you have a class inherit from another on a different line than the class declaration, neither keywords nor the class name will be highlighted.

E.g.
```
class Child : public Parent1,
              public Parent2 {};
```

"`public Parent1`" will be highlighted correctly, but "`public Parent2`" will be entirely without highlight, even though public is a keyword.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1607 0 @ 3.00GHz (4 x 2135)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (25.14GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.3.3
python|ms-|2018.8.0
cpptools|ms-|0.18.1

</details>

**Comment by aeschli** [comment] 2018-09-13 14:09
duplicate of https://github.com/atom/language-c/issues/274

**Closed by aeschli** 2018-09-13 14:09 UTC
