### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by Akash52** [microsoft/vscode#174894] opened 2023-02-21 08:25 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230220

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-styled-plugin`
- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`
- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33949:11)
    at parseSimpleUnaryExpression (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33582:16)
    at parseUnaryExpressionOrHigher (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33550:35)
    at parseBinaryExpressionOrHigher (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33468:25)
    at parseAssignmentExpressionOrHigher (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33141:18)
    at parseExpression (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:33107:16)
    at doOutsideOfContext (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30804:12)
    at allowInAnd (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30825:12)
    at parseExpressionOrLabeledStatement (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34619:24)
    at parseStatement (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:34851:12)
    at parseListElement (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31575:12)
    at parseList (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:31560:19)
    at parseSourceFileWorker (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30620:24)
    at Object.parseSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30453:20)
    at createSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:30314:21)
    at createLanguageServiceSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135115:22)
    at acquireOrUpdateDocument (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:132037:26)
    at Object.acquireDocumentWithKey (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:131962:12)
    at getOrCreateSourceFileByPath (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135440:31)
    at Object.getOrCreateSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135420:14)
    at c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135352:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117119:24)
    at findSourceFileWorker (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119451:23)
    at findSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119371:20)
    at c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119320:22
    at getSourceFileFromReferenceWorker (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119289:26)
    at processSourceFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119318:5)
    at processRootFile (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:119114:5)
    at c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:41
    at forEach (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2309:22)
    at createProgram (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:117899:5)
    at synchronizeHostData (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135376:15)
    at Object.getProgram (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:135448:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:172060:41)
    at ConfiguredProject2.updateGraph (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:171997:32)
    at ConfiguredProject2.updateGraph (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:173179:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:174786:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:175877:26)
    at c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:64
    at flatMap (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:2557:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:176157:24)
    at updateOpen (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:177302:29)
    at c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:69
    at IpcIOSession.executeWithRequestId (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179861:14)
    at IpcIOSession.executeCommand (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179869:29)
    at IpcIOSession.onMessage (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:179911:51)
    at process.<anonymous> (c:\Users\sky\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302200\node_modules\typescript\lib\tsserver.js:181479:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 6.3.9600
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.10GB free)|
|Process Argv|. --crash-reporter-id ef949e1e-ed6c-4331-9a54-a222482ff5c9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.3
ng-template|Ang|15.1.0
vscode-apollo|apo|1.19.11
carbon|Ask|0.0.1
atlascode|atl|3.0.2
emojisense|bie|0.9.1
vscode-tailwindcss|bra|0.9.7
turbo-console-log|Cha|2.7.1
vscode-better-align|cho|1.4.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.58.2
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
rest-client|hum|0.25.1
vscode-react-typescript|inf|1.3.1
path-autocomplete|ion|1.23.1
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vue-volar-extention-pack|Mis|1.1.6
theme-monokai-pro-vscode|mon|1.2.0
vscode-docker|ms-|1.23.3
azure-account|ms-|0.11.3
vscode-typescript-next|ms-|5.0.202302200
debugger-for-chrome|msj|4.13.0
color-highlight|nau|2.5.0
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.37.2
material-icon-theme|PKi|4.24.0
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.11.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.7
vscode-scss-formatter|sib|2.4.5
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
sass-indented|syl|1.8.24
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
volar|Vue|1.1.5
vscode-typescript-vue-plugin|Vue|1.1.5
vscode-import-cost|wix|3.3.0
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
vetur-extended|zar|0.0.23
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
6233i204:30664135

```

</details>

**Comment by mjbvz** [comment] 2023-02-22 04:26
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-22 04:26 UTC
