### ISSUE TITLE
Unable to launch tasks

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#77059] opened 2019-07-10 07:52 UTC
Issue Type: <b>Bug</b>

1. Ctrl+P Tasks: Run Task
2. Select a task.
3. It doesn't run.

Tried with and without extensions loaded. Still persists after rebooting the PC.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (27.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|10.4.4
read-only-indicator|ale|3.0.3
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
bracket-pair-colorizer-2|Coe|0.0.28
githistory|don|0.4.6
gitlens|eam|9.8.3
permute-lines|ear|0.0.10
matlab|Gim|1.2.0
triggertaskonsave|Gru|0.2.9
vscode-dimmer|hoo|2.1.0
vscode-peacock|joh|2.4.0
string-manipulation|mar|0.3.1
select-part-of-word|mle|1.0.1
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
indent-rainbow|ode|7.4.0
indenticator|Sir|0.6.0
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
code-spell-checker|str|1.7.17
selectline-statusbar|tom|0.0.2
sensitive-replace|vil|0.1.1
vscode-icons|vsc|8.8.0
vscode-todo-highlight|way|1.0.4
asn1|wil|0.5.3
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment] 2019-07-10 08:22
I can't reproduce with this task:
```
        {
            "label": "four",
            "command": "sleep 13",
            "type": "shell",
            "problemMatcher": []
        }
```
Can you share your tasks.json?

**Comment by BillDenton** [comment] 2019-07-10 08:28
It works with your tasks.json. My tasks.json is quite long so I'll try to cut it down before sharing. It needs cleaning because we've just moved from ClearCase to git.

**Comment by BillDenton** [comment] 2019-07-10 09:36
I've removed some of the tasks and some of them are working, but not all of them. I'll do further analysis when I have some time.

**Comment by alexr00** [comment] 2019-07-10 12:49
Any example of one that doesn't work would probably help.

**Comment by BillDenton** [comment] 2019-07-10 13:34
Sorry been busy. I'll try to narrow it down.

**Comment by BillDenton** [comment] 2019-07-10 15:30
The following doesn't work:
```
      {
         "label": "four",
         "command": "",
         "args": [ "sleep 13" ],
         "type": "shell",
         "problemMatcher": [],
      }
```
I have a lot of tasks that following that pattern where I have to run shell commands. These ones used to work and now failing. I think it started with the patch release 1.36.1. I also have ones that launch external processes, which seem to be fine.

**Comment by BillDenton** [comment] 2019-07-11 08:07
I've reinstalled version 1.35.1 and its working again.

**Comment by alexr00** [comment] 2019-07-11 08:14
Thank you for tracking down one of the tasks. The issue is that you don't have a command. It looks like that used to be implicitly supported, but the idea of a task with arguments and no command is a little weird. We did used to support it though.

**Comment by alexr00** [comment] 2019-07-11 08:24
I pushed a fix, which you should be able to get in the next insiders release. Inisiders installs side by side with stable, so you can have both if you want to get the fix sooner.

**Comment by BillDenton** [comment] 2019-07-11 08:26
I installed 1.35.1 and before I managed to do much it updated itself 1.36.1 because I forgot to turn of the auto update. Now on "1.36.1" I the following works:
```
      {
         "label": "four",
         "command": "sleep",
         "args": [ "13" ],
         "type": "shell",
         "problemMatcher": [],
      }
```
I'll try to update my more complex tasks to do that. I have a lot of tasks that run long complex commands in cmd. Something like "(scons parm1 parm2 parm3 parm4 || build_fail.bat) && (scons another1 another2 another3 && build_fail.bat) && build_success.bat". I'm not sure how I would split that between the command and args. I could pull it out into a separate batch file, but I don't want to do that because it is more files to maintain when I change the build parameters that I do frequently.

**Comment by kinglionsz** [comment] 2019-07-12 12:53
> I installed 1.35.1 and before I managed to do much it updated itself 1.36.1 because I forgot to turn of the auto update. Now on "1.36.1" I the following works:
>       {
>          "label": "four",
>          "command": "sleep",
>          "args": [ "13" ],
>          "type": "shell",
>          "problemMatcher": [],
>       }
> 
> I'll try to update my more complex tasks to do that. I have a lot of tasks that run long complex commands in cmd. Something like "(scons parm1 parm2 parm3 parm4 || build_fail.bat) && (scons another1 another2 another3 && build_fail.bat) && build_success.bat". I'm not sure how I would split that between the command and args. I could pull it out into a separate batch file, but I don't want to do that because it is more files to maintain when I change the build parameters that I do frequently.
> Update Thanks for fixing it. I've found a work around, which is put the first item (e.g "(scons") in the command and leaving the rest in the args. (only tested one task which I needed to run). I think I'll use the workaround as it is less disruptive than changing to insiders.

A little change as a developer, will bring endless pain to producers, when I catch the bug, it's so painful😢Thanks for fixing it

**Comment by roblourens** [comment] 2019-08-01 18:32
Can you clarify the expected behavior?

On linux I get 

```
/bin/bash: sleep 13: command not found
The terminal process terminated with exit code: 127
```

On windows, there is no error but the task terminates immediate and does not seem to be actually sleeping.

**Comment by alexr00** [comment] 2019-08-02 09:49
There is no sleep command on Windows, so you can test on Windows with:
```
		{
			"label": "My Task",
			"type": "shell",
			"command": "",
			"args": ["echo", "hello"],
			"problemMatcher": []
		}
```
On linux, the way we do escaping means that for the sleep command you should test with:
```
		{
			"label": "My Task",
			"type": "shell",
			"command": "",
			"args": ["sleep", "3"],
			"problemMatcher": []
		}
```

**Closed by alexr00** 2019-08-02 09:49 UTC
Labels: bug, tasks, verification-found

**Comment by BillDenton** [comment] 2019-08-02 09:55
**Wrote this yesterday, but it was late so forgot to press "Comment". Looks like you've verified it.**

I've not tried the insider build yet. I'm using the workaround instead. Not tried on Linux (and not easy for me to do so). On my Windows 10 machine, I have something installed that is providing the command "sleep", so it sleeps for 13 seconds. That is with:
```
      {
         "label": "four",
         "command": "sleep",
         "args": [ "13" ],
         "type": "shell",
         "problemMatcher": [],
      }
```
With:
   ```
     {
         "label": "four",
         "command": "",
         "args": [ "sleep", "13" ],
         "type": "shell",
         "problemMatcher": [],
      }
```
Nothing appears to happen. That pattern used work, and I presuming will work in the next release.
