### ISSUE TITLE
Source control Icons not load when using WSL

### ISSUE THREAD

**Issue by danilo-drs** [microsoft/vscode#78726] opened 2019-08-08 20:29 UTC
Issue Type: <b>Bug</b>

When using WSL Remote Development all icons on "source control" tab does not get loaded.

**Steps to reproduce**
* Install "Remote Development" extension
* Open a wsl bash terminal (I'm using wsl Ubuntu)
* Navigate to a git controled folder
* type `code .` 
* open "source control tab"

**Result**
No action icons are loaded, but tootips are displayed and the action are fired normally

**Expected result:**
All action icons like a not remote session

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|Memory (System)|7.84GB (0.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|Memory (System)|7.84GB (0.47GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vscode-sql-beautify|sen|0.0.4
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0

</details>

**Comment by jrieken** [comment] 2019-08-09 08:33
/duplicate of https://github.com/microsoft/vscode-remote-release/issues/687

**Closed** 2019-08-09 08:33 UTC
Labels: *duplicate, new release
