### ISSUE TITLE
"Explorer" tab/window disapears in sidebar

### ISSUE THREAD

**Issue by vdrasutis** [microsoft/vscode#182736] opened 2023-05-17 08:23 UTC
Type: <b>Bug</b>

"Explorer"  tab disapears in sidebar, always have to click "Ctrl + Shift +E" to oopen window.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.24GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/git/geo/geotrunk/Geo/DataExplorerFiles --crash-reporter-id 5ad273e2-820a-47db-9905-d72114969826|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.10.0
color-info|bie|0.7.2
vscode-tailwindcss|bra|0.9.11
vscode-wev-dev-extension-pack|c0d|2.5.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
vscode-jest-runner|fir|0.4.60
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
fsharp-language-server|geo|0.1.28
rest-client|hum|0.25.1
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
Ionide-fsharp|Ion|7.5.4
vsc-python-indent|Kev|1.18.0
vscode-gutter-preview|kis|0.30.0
csharpextensions|kre|1.7.3
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
inline-fold|moa|0.2.4
hg|mrc|1.9.0
vscode-docker|ms-|1.25.1
csharp|ms-|1.25.7
dotnet-interactive-vscode|ms-|1.0.4258030
vscode-dotnet-pack|ms-|1.0.12
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.5
vscode-remote-extensionpack|ms-|0.24.0
powershell|ms-|2023.5.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
angular-console|nrw|18.1.1
cs-script|ole|2.2.1
material-icon-theme|PKi|4.27.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
xml-toolkit|SAP|1.1.0
trailing-spaces|sha|0.4.1
html-to-css-autocompletion|sol|1.1.2
css-auto-prefix|spo|0.1.7
code-spell-checker|str|2.20.4
vscode-styled-components|sty|1.7.8
es6-string-html|Tob|2.12.1
errorlens|use|3.11.0
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
hg|viv|2.0.5
rainbow-tags|vol|0.4.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
classnametocss|zit|0.0.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-05-17 09:39
Please see https://github.com/microsoft/vscode/issues/181877#issuecomment-1541223025

**Comment by lramos15** [comment] 2023-05-17 14:06
Closing as a duplicate of #181877, let us know if this doesn't fix your problem :)

**Comment by vdrasutis** [comment] 2023-05-17 20:18
solved

**Closed** 2023-05-17 20:18 UTC
