### ISSUE TITLE
Double clicking an element in the Markdown preview does not automatically open the editor

### ISSUE THREAD

**Issue by fhilitski** [Microsoft/vscode#47594] opened 2018-04-10 16:14 UTC
Issue Type: <b>Bug</b>

Documentation says:
Additionally, double clicking an element in the Markdown preview will automatically open the editor for the file and scroll to the line nearest the clicked element.

But I was unable to get it working...

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3597)|
|Memory (System)|15.88GB (2.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
open-in-browser|tec|1.1.0

</details>

**Comment by zb991120** [comment] 2018-04-10 16:18
0907h.vip

**Comment by mjbvz** [comment] 2018-04-10 17:50
Duplicate of #47188

**Closed by mjbvz** 2018-04-10 17:50 UTC
Labels: *duplicate, new release
