### ISSUE TITLE
Keyboard layout change does apply to key shortcuts

### ISSUE THREAD

**Issue by barnski** [Microsoft/vscode#42153] opened 2018-01-25 12:40 UTC
- VSCode Version: 1.19.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Set Keyboard layout to German (it has Z switched with Y)
2. Open VS Code 
3. type 'z' -> 'z' is displayed
4. type Ctrl + z -> undo is called
5. With VS Code opened switch keyboard layout to English(US).
6. type 'z' -> 'z' is displayed
7. type Ctrl + z -> undo is NOT called
8. type Ctrl + y -> undo is called

It seems that keyboard layout is not applied to shortcuts. When you click shortcut keyboard layout with which VS Code was opened is applied. Not the active one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-01-26 08:17
https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/35430678-9fcc8bc0-0279-11e8-9f2b-3acd4a146741.png)

Duplicate of #23690

**Closed by alexandrudima** 2018-01-26 08:17 UTC
Labels: keyboard-layout

**Comment by barnski** [comment] 2018-01-26 08:20
Ah, sorry. I don't know how I missed this page. Thanks!
