### ISSUE TITLE
Search and Find/Replace Erratic Behavior

### ISSUE THREAD

**Issue by Codermar** [Microsoft/vscode#45904] opened 2018-03-15 19:03 UTC
- VSCode Version:
Version 1.22.0-insider (1.22.0-insider) 509b8084d46b82ec5851447903cebd914e4535a5
- OS Version: MacOS Sierra

Description:
Search and Find/Replace erratic behavior:
- Finds Previously Removed Entries 
- Replaces inexistent entries
- Appends replace values to the end of the line of encountered instance

Steps to Reproduce:

1. Search for a string that can be found in 2 files.
2. Find and replace the string you search
3. Search again and the "ghost" entry will be found

What's most damaging though, is that this "cacheing of sorts" that's happening on the search causes unwanted replace entries. If you try multiple combinations you will find the issue.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment] 2018-03-15 19:51
Did you save the files after doing the replace?

**Comment by Codermar** [comment] 2018-03-15 23:09
I am not sure what you mean but below you can see a screen shot of what happened
1. I searched for common.messages.selectOne
2. I replaced it with common.messages.selectOneTest
Then I did the opposite and got what you see in the screenshot (it happened to me with variations quite a few times)

![screen shot 2018-03-15 at 4 05 51 pm](https://user-images.githubusercontent.com/1392720/37495499-d184c1de-286a-11e8-94ab-a627169792ab.png)

**Comment by roblourens** [comment] 2018-03-16 00:35
Sorry I don't understand, you just replaced selectOneTest with selectOne. Now the editor shows selectOne. What's the problem here?

**Comment by dlong500** [comment] 2018-03-16 03:28
There is definitely a problem here.  I'm going to try to post a clear demonstration when I get the chance.  The count of found items gets all messed up after replacing text, and it seems to highlight locations where the original replaced text used to be.

**Comment by Codermar** [comment] 2018-03-16 16:48
I've updated the title and description and added a clarification but if you actually try a few common use-cases of find and replace on multiple files you will definitely run into the issues I described.

**Comment by rebornix** [comment] 2018-03-16 17:17
@Codermar IMO it shares the same root cause as #45770, which is already fixed in latest Insider. We can reopen this issue if you run into any problem again, thanks for our help!

**Closed** 2018-03-16 17:17 UTC
Labels: needs more info, search
