### ISSUE TITLE
Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH

### ISSUE THREAD

**Issue by joedborg** [Microsoft/vscode#26447] opened 2017-05-11 09:53 UTC
- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Open a TS project in VSC
2. Open any JS file

NPM is installed on my system.  There is no complaint if launched from terminal, only from the app package.  There is no config option to set a path to NPM (would be quick fix).

**Comment by burakcan** [comment] 2017-05-11 10:43
https://github.com/Microsoft/vscode/issues/26438

**Comment by mjbvz** [comment] 2017-05-13 04:37
Duplicate of #24961. We're looking into a mitigation for VS Code 1.13 and also into moving away from requiring npm longer term

To help investigate your issue:
* Did you install npm using nvm or n?
* Can you also please run the `Developer: Toggle Developer Tools` command and then evaluate `process.env['PATH']` in the console and see if the correct path is included

Thanks

**Comment by gnhuy91** [comment] 2017-05-14 03:20
I got the same issue, usng `nvm`. `process.env.PATH` contains `/Users/huygn/.nvm/versions/node/v6.10.0/bin` which is correct & should include `npm`.

There is no complaint if launched from terminal, only from the app package.

**Comment by mjbvz** [comment] 2017-05-16 04:23
Thanks @gnhuy91 

Since npm is in your path, I'm not sure why the typings installers cannot find npm or why launching from terminal fixes this. Let's continue tracking this on #24961

**Closed by mjbvz** 2017-05-16 04:23 UTC
Labels: duplicate, needs more info

**Comment by bhatikuldeep** [comment] 2017-06-02 13:03
I think this error pop-up appear when there's no git installed on your machine, thanks @mjbvz for pointing out last steps to check console. 

![capture](https://cloud.githubusercontent.com/assets/10710677/26726782/9aa7fac0-47a4-11e7-99e2-54a39fcec28a.PNG)
 
For me git was missing (was not installed), the moment I installed and restarted visual studio code, this error no more!
