### ISSUE TITLE
Tasks get stuck when restoring a PTY

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#193233] opened 2023-09-15 19:13 UTC
1. Have a debug config like 

  ```
  {
    "name": "Mandelbrot",
    "request": "launch",
    "type": "chrome",
    "url": "http://localhost:3000/",
    "preLaunchTask": "serve"
  }
  ```

  and a task like

  ```
  {
    "label": "serve",
    "type": "shell",
    "command": "npx -y serve -p 8080 dist",
    "isBackground": true,
    "problemMatcher": {
      "pattern": [
        {
          "regexp": "^neverMatched$",
          "file": 1,
          "location": 2,
          "message": 3
        }
      ],
      "background": {
        "activeOnStart": true,
        "beginsPattern": "neverMatched",
        "endsPattern": "Serving"
      }
    }
  }
  ```

2. Hit F5. You're all good ✅
3. Reload the window. Hit F5 again, and observe the terminal with the task gets restored.
4. You get this dialog. I don't really want either of these options, it's already a background task that should be in the 'end' state 🐛

    ![](https://memes.peet.io/img/23-09-23edee99-9490-46df-83ca-26132215908c.png)

5. Terminate or restart the task and try to F5 again. This doesn't work either and you have to reload the window to get debugging work again 🐛

**Comment by meganrogge** [comment] 2023-09-15 22:59
Did this work until recently?

**Comment by meganrogge** [comment] 2023-09-15 23:04
Also doesn't a pre launch task inherently run every time one debugs?

**Comment by connor4312** [comment] 2023-09-15 23:45
> Did this work until recently?

I think so... I honestly don't use preLaunchTask's as much as I should due to a history of papercuts, but I definitely haven't seen this notification before.

> Also doesn't a pre launch task get run every time one debugs?

Yea, but if it's a background task that's already running it shouldn't get run again. I'm not sure how much of this issue is in debug vs tasks

**Comment by meganrogge** [comment] 2023-09-16 17:08
The task stops running on reload of the window because the terminal is killed. That's why it has to run again on window reload. 

Perhaps the solution is to not reconnect (IE restart) prelaunch tasks.

**Comment by meganrogge** [comment] 2023-09-16 17:09
Currently, we persist any background task that has problem matchers.

**Comment by meganrogge** [comment] 2023-11-09 21:12
Should have been fixed with #197381, @connor4312 pls reopen if not

**Comment by connor4312** [comment] 2023-11-09 21:58
I can still repro in today's Insiders

**Comment by meganrogge** [comment] 2023-11-09 22:15
are you reproducing using the task above?

**Comment by connor4312** [comment] 2023-11-09 23:39
I'm using a simpler task following the other issue:

```
    {
      "label": "serve",
      "type": "shell",
      "command": "npx serve",
      "isBackground": true
    }
```

**Comment by meganrogge** [comment] 2023-11-09 23:46
works when I use `runTask`. So has to do with debugging specifically
https://github.com/microsoft/vscode/assets/29464607/4a83828b-1d24-4c18-898a-25b9337bc6b4

**Closed** 2023-12-07 22:02 UTC
Labels: bug, debug, tasks
