### ISSUE TITLE
Scrollbar overlapped with content in tooltip dialog

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode#109836] opened 2020-11-02 09:50 UTC
- VSCode Version: 1.50.1

Steps to Reproduce:
1. Open a vscode extension repository (e.g. https://github.com/moshfeu/vscode-compare-folders)
2. Go to file "treeBuilder.ts" and update the code in line2 to: 
   _import set from 'lodash/set/lodash02/set02/lodash03/set03/lodash04/set04/lodash05/set05'_
3. Move cursor to the tooltip dialog and observe the status

Expected:
All tooltip content display correctly

Actual:
Scrollbar overlapped with content in tooltip dialog when move cursor to the dialog
(Repro on Windows, Linux and Mac)
![Is_overlap](https://user-images.githubusercontent.com/37648162/97854053-e9eb9480-1d33-11eb-9bb5-d7316fa84f8c.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment] 2020-11-02 23:46
Duplicate of https://github.com/microsoft/vscode/issues/69391

**Closed** 2020-11-02 23:46 UTC
Labels: *duplicate
