### ISSUE TITLE
Add line-wrap to file comparison

### ISSUE THREAD

**Issue by KimikoMuffin** [Microsoft/vscode#11596] opened 2016-09-06 17:51 UTC
Currently, there is no way to wrap long lines when comparing two files. Alt+Z has no effect, the "Softwrap" plugin has no effect, nothing. This makes it extremely cumbersome to compare using files that have long lines.

**Comment by alexandrudima** [comment] 2017-11-23 10:47
Duplicate of #10572

**Closed by alexandrudima** 2017-11-23 10:47 UTC
Labels: diff-editor, editor, feature-request
