### ISSUE TITLE
Task builder icon keeps turning

### ISSUE THREAD

**Issue by FLWrd** [Microsoft/vscode#11044] opened 2016-08-27 07:51 UTC
- VSCode Version: 1.4.0
- OS Version: 10.11.6

Steps to Reproduce:
1. Build a typescript project

Expected outcome: once the compilation has finished, the running icon should stop.

Actual outcome: this doesn't always happen. In particular, only the first build stops the icon from running, it seems.

Settings:

tsconfig.json:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "es6"
    },
    "files": [ bunch of .ts files ]
}
```

**Comment by waderyan** [comment] 2016-08-29 18:39
@sandy081 thank you for opening this issue. Below are the steps I have taken in an attempt to reproduce your issue. Can you run through these steps on your machine or clarify where I am in error? 

1. Create a new folder with `test.ts` (copy and paste code below). 
2. Create `tsconfig.json` with the code below. 
3. Open the command palatte. 
4. Type "Configure Task Runner"
5. Choose "TypeScript - tsconfig.json"
6. Open Quick Open (`cmd+p` or `ctrl+p`) and type "task tsc" to compile. 

Based on your bug report I expect the task runner to still be running, however, I am not able to reproduce what you are seeing. 

test.ts

```typescript
console.log('hello world');
```

tsconfig.json

```typescript
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "es6"
    },
    "files": [ "test.ts"]
}
```

tasks.json (generated by VS Code)

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "."],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

**Comment by sandy081** [comment] 2016-08-29 18:57
@waderyan I am not the author of this issue, I just triaged it :)

Pinging the author @FLWrd

**Comment by waderyan** [comment] 2016-08-29 19:05
Whoops! Sorry about that @sandy081. Mistyped.

**Comment by FLWrd** [comment] 2016-09-02 06:39
Hi,

I cannot perform step 6. "task tsc" is not an option.

I can hit cmd-shift-b (run build task). That executes fine. Then, when I make a change to test.ts and hit cmd-shift-b again, the build icon keeps spinning, as reported before.

**Comment by waderyan** [comment] 2016-09-02 17:41
@FLWrd please share your tasks.json file. 

This is what mine looks like. 

```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "."],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

My guess is that you configured your task to run in watch mode, which is why the task is still running - its watching. 

![image](https://cloud.githubusercontent.com/assets/2449568/18212764/c184f198-70f9-11e6-8287-c208009bf444.png)

**Comment by FLWrd** [comment] 2016-09-07 14:49
Sorry for the delay, here it is:
    {
        // See https://go.microsoft.com/fwlink/?LinkId=733558
        // for the documentation about the tasks.json format
        "version": "0.1.0",
        "command": "tsc",
        "isShellCommand": true,
        "args": ["-p", "."],
        "showOutput": "silent",
        "problemMatcher": "$tsc"
    }

I think I copied it from your earlier message. Which attribute would make it watch?

**Comment by waderyan** [comment] 2017-07-13 22:32
should be fixed with latest task improvements

**Closed by waderyan** 2017-07-13 22:32 UTC
Labels: needs more info
