### ISSUE TITLE
Cant use cursor to navigate through filename characters when renaming file. 

### ISSUE THREAD

**Issue by jspronk** [Microsoft/vscode#39333] opened 2017-11-29 19:01 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (6e90f8995da4bd999e8983b8e480a34045c1dfcf, 2017-11-29T05:14:15.979Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
vscode-postman|eri|0.5.2
rest-client|hum|0.16.1
sftp|lix|0.8.10
node-debug2|ms-|1.19.0
html-preview-vscode|tht|0.1.1
vscode-react-native|vsm|0.5.7
ReactSnippets|xab|1.7.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Right click on file in VSCode's Explorer.  Select "rename".
2. click on highlighted file name(like you would to change the name of the file) and try to use the arrow keys to change the cursor position in the filename letters. 

Reproduces without extensions: Yes/No

**Comment by Tekbr** [comment] 2017-11-29 19:12
@jspronk duplicate of #39309?

**Closed** 2017-11-29 19:53 UTC
Labels: *duplicate, editor, editor-core, insiders
