### ISSUE TITLE
Show syntax error while open all es6 files in folder 'node_modules' and it subfolders, and

### ISSUE THREAD

**Issue by flyingcodes** [Microsoft/vscode#1434] opened 2015-12-18 03:26 UTC
Show syntax error while open all es6 files in folder 'node_modules' and it's subfolders, and reopen the file, will show repeatedly syntax error in multilines.

open the es6 project:
![1](https://cloud.githubusercontent.com/assets/12825770/11888441/91b6ae54-a578-11e5-8d3d-d7e2b1550e98.GIF)
open es6 file in root folder, no syntax error:
![2](https://cloud.githubusercontent.com/assets/12825770/11888442/91dde730-a578-11e5-8545-207daa8a6c2e.GIF)
but, open the es6 file in folder 'node_modules', will show  syntax error:
![3](https://cloud.githubusercontent.com/assets/12825770/11888445/91f47298-a578-11e5-8e98-fcd33c961c77.GIF)
text of  syntax error:
![4](https://cloud.githubusercontent.com/assets/12825770/11888446/91f6dac4-a578-11e5-84c3-3374070c9f29.GIF)
show same error while open es6 file in subfolder of  'node_modules':
![5](https://cloud.githubusercontent.com/assets/12825770/11888444/91f3cc94-a578-11e5-85fa-41b15681329a.GIF)
open others not in folder 'node_modules',  no syntax error:
![6](https://cloud.githubusercontent.com/assets/12825770/11888447/91f91960-a578-11e5-8bd3-3ef885870baf.GIF)

and, will show repeatedly syntax error in multilines while reopen the es6 file which has syntax error:
![7](https://cloud.githubusercontent.com/assets/12825770/11888443/91ef39a4-a578-11e5-9833-e85635d4ef1d.GIF)
repoen repeatedly:
![8](https://cloud.githubusercontent.com/assets/12825770/11888448/9217c086-a578-11e5-9983-a74781c50a00.GIF)
![9](https://cloud.githubusercontent.com/assets/12825770/11888449/921ec390-a578-11e5-82bf-a13588d5b327.GIF)

**Comment by flyingcodes** [comment] 2015-12-18 03:38
the code of es6 project:
[vsc.bug.zip](https://github.com/Microsoft/vscode/files/66198/vsc.bug.zip)

**Comment by jrieken** [comment] 2015-12-18 09:44
This is a duplicate of #703

**Closed by jrieken** 2015-12-18 09:44 UTC
Labels: bug, js
