### ISSUE TITLE
Ability to enable/disable extensions inside .vscode

### ISSUE THREAD

**Issue by Zerogiven** [Microsoft/vscode#42497] opened 2018-01-30 15:15 UTC
You alreade made a great job with #15611 and #2882 but i still have a small problem with it cause if i make many projects and/or starting/creating often new tiny projects i always have to make the following steps:

1. Start a new Project, for Example a PHP Project
2. Load it by VS code
3. Go to extensions and disable/enable all necessary extensions

If i start a new PHP Project i have to do step3 all the time. But at a plain PHP project i don't need the typescript & node extensions for example. Same for TypeScript project, where i never need the PHP debuger. And here we only have PHP, NodeJS and TypeScript. It's getting harder and harder if you develop many different languages... many would say, use another IDE, for example for Perl or PHP. But i really like VS code for most of my use cases.

One idea could be to make a user config like "plugins.active" with could be a string array which could have a default value like a joker sign. For Example: plugins.enable: ['*'];

This would activate all plugins by default. Then i could say inside a workspace config which plugins should be active at this project. Also the other way with plugins.disable would be nice so that we can fill in all plugins which are not needed for a project.

Second factor could or should be what i've set inside extension view, so it should merge with .vscode setting.

---

So i hope you understand my problem and maybe you guys have a solution for me :)

**Comment by roblourens** [comment] 2018-01-30 17:35
Ideally you shouldn't have to enable/disable extensions per workspace. If they are causing some problem with workspaces where you don't need them, then you should file a bug on that extension.

What's the problem with leaving them enabled all the time?

**Comment by Zerogiven** [comment] 2018-01-31 21:25
Some of the extensions are still RAM or CPU expensive like some intellisense extensions. So if i use PHP, Path, NPM, SCSS, C/C++ and less Intelisense extension (cause this are the ones i need), i mostly need just a bunch of them and the others are scanning directories too, of course cause i still can have a mixed project like PHP & SCSS or PHP, SCSS and NPM. But sometimes i only need PHP stuff and nothing more, so the others still need some workload which is pretty normal i think, it's more the sum of all.

I attach two screenshots with my workload in a tiny PHP project (About 25 files, 7 directories), first with all extensions enabled, second only with my PHP extensions. Both have the same open files from the same project, just which extensions are enabled differs. The used RAM is almost twice.

Of course, this is maybe not a real problem, more something stickin in my eye ;-) but maybe others have that too.. I'm also not sure to install more extensions like i already have cause maybe sometimes it uses three(or four ^^) times more RAM than with needed extensions enabled only.

![bildschirmfoto vom 2018-01-31 22-15-48](https://user-images.githubusercontent.com/389319/35648108-e3d25f7a-06d4-11e8-80ab-e6ad84bf1f24.png)

![bildschirmfoto vom 2018-01-31 22-16-13](https://user-images.githubusercontent.com/389319/35648118-ed19145c-06d4-11e8-8d58-a470fb8679fa.png)

greetings

**Comment by roblourens** [comment] 2018-01-31 22:46
Those numbers are hard to interpret without more context about what the processes actually are and what else is going on. Only one of those per window is the extensionhost process.

Ideally extensions should only be activated when you are editing files that they care about. If there is a heavy extension which is activated all the time, we should file an issue on it. You can see which extensions are activated by running the "Show Running Extensions" command.

**Comment by Zerogiven** [comment] 2018-02-01 08:25
Okay i'll try to debug this out.

I understand the fact that the extensions should care about working progresses, but if i could handle with extensions are enabled/disabled per Workspace Setting (like i already can do, but only with Local Storage and not by config file) i don't have to care if all of my extensions are handling my pc ressources perfectly. Otherwise it always could be that i can't or won't use an extension cause it's working perfect for what it is made for, but lags for all unnecessary stuff.

thx at all :)

**Comment by roblourens** [comment] 2018-02-01 17:53
Actually we do have something which could help you, extensions can now be enabled/disabled per workspace. Click the gear icon on an extension.

![image](https://user-images.githubusercontent.com/323878/35694288-bcd018b6-0735-11e8-8862-17ba6a322c70.png)

**Comment by Zerogiven** [comment] 2018-02-01 18:21
Sure this helps me a lot at the moment, it's just annoying me that i have to do this all the time if i start a new project. With about 30 installed extensions this is not so funny ;) Especially cause most of the times i enable / disable same extensions for different projects. For example if i start a PHP Project, in 99% of my cases i don't need my typescript extensions.

To handle the RAM & CPU ressource problem i already do it like in your screenshot. It would be just helpfull if i could do it more automatically :D

**Comment by sandy081** [comment] 2018-02-02 10:07
I wonder if you are looking for something like this feature - https://github.com/Microsoft/vscode/issues/40109

**Comment by Zerogiven** [comment] 2018-02-02 13:02
Exactly :)

**Comment by sandy081** [comment] 2018-02-02 16:26
Duplicate of #40109

**Closed** 2018-02-02 16:27 UTC
Labels: *duplicate, needs more info
