### ISSUE TITLE
Chat moved from quick to view appears as running

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#188800] opened 2023-07-25 15:01 UTC
Testing #188542

The stop button is not doing anything then.

![Recording 2023-07-25 at 17 00 46](https://github.com/microsoft/vscode/assets/900690/13ea73ee-606d-41ac-bfb8-ac0727f22a9a)

**Comment by joyceerhl** [comment] 2023-12-05 23:02
Doesn't repro for me, also possibly duplicate of https://github.com/microsoft/vscode/issues/190913

**Closed by joyceerhl** 2023-12-05 23:02 UTC
