### ISSUE TITLE
[markdown] Markdown lists aren't being themed correctly

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#104] opened 2015-11-18 21:16 UTC
Making a custom theme using every possible scope for a Markdown list and can't style them. However, if I style "punctuation", the lists get styled.

**Comment by aeschli** [comment] 2015-11-30 15:34
The markdown tokenizer only emits a very limited set of tokens form now.

**Comment by Tyriar** [comment] 2016-05-28 01:51
@kieferrm I believe you came across this recently, can this issue be closed?

**Comment by kieferrm** [comment] 2016-05-31 16:37
Yes, once the extension is in place, we'll close this.

**Comment by bpasero** [comment] 2016-06-16 15:17
Done?

**Comment by Tyriar** [comment] 2016-06-16 19:10
I just created a duplicate of this at https://github.com/Microsoft/vscode/issues/7789, it's more detail and more relevant though so I'll close this off in favor of it.

**Closed by Tyriar** 2016-06-16 19:10 UTC
Labels: feature-request, languages basic, markdown
