### ISSUE TITLE
High CPU usage when disconnected from the internet, very unresponsive

### ISSUE THREAD

**Issue by todddeweerd** [Microsoft/vscode#40318] opened 2017-12-15 18:44 UTC
The VS Code processes will consume as much CPU as possible. The attached screen shot and memory dumps were captured when the issued happened.
![vscode-high cpu](https://user-images.githubusercontent.com/7583934/34055505-084a2a5a-e195-11e7-97c9-3c7ea3e69267.png)

- VSCode Version: 1.19
- OS Version:

Steps to Reproduce:

1. Disconnect internet
2. Install VS Code
3. Launch VS Code 

Reproduces without extensions: Yes

I created dmp files but can't attach them

**Comment by ramya-rao-a** [comment] 2017-12-15 18:54
- Run `code --status` when this happens and share the results. It gives a more clear picture on which process is causing the trouble
- When Internet is connected you don't see any issues at all?
- Read [Perf Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) for instructions on what you can share so that we can better help you.

**Comment by todddeweerd** [comment] 2017-12-18 23:09
This is a fresh install of code without extensions added manually. Also, because code is consuming so much cpu I can't run all of the suggestions in the perf issues page. Any other thoughts?

code --status
[3784:1218/215046.069:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.
[3784:1218/215052.083:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.
[3784:1218/215057.434:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.
[3784:1218/215102.450:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.
[3784:1218/215107.465:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.
[3784:1218/215112.481:WARNING:dns_config_service_win.cc(661)] Failed to read Dns
Config.

code --prof-startup
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    { Error: connect ECONNREFUSED 127.0.0.1:9223
        at Object.exports._errnoException (util.js:1050:11)
        at exports._exceptionWithHostPort (util.js:1073:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9223 },
    ... 100 more items ] ]

**Comment by joaomoreno** [comment] 2017-12-19 08:17
@bpasero Do you have an idea here?

I can't reproduce the high CPU when there is no internet connection. I also can't reproduce the `ECONNREFUSED` when there is no internet connection... For me, `code --status` spits out a couple of `Failed to read DnsConfig` warnings, but then it correctly outputs the status.

The fact that the user can't even connect to the running instance makes me think that the code which sets up the port for status breaks somewhere and possibly causes the CPU spikes.

It's also confusing to me that the code is trying to connect to a running port... I thought `--status` used the named pipes?

**Comment by bpasero** [comment] 2017-12-19 09:27
Very likely a duplicate of https://github.com/Microsoft/vscode/issues/7570

@todddeweerd do you run in a VM with 1 CPU?

**Comment by todddeweerd** [comment] 2017-12-19 20:25
It does have just 1 CPU. It looks like the same issue.

**Comment by bpasero** [comment] 2017-12-20 07:05
Rather: https://github.com/Microsoft/vscode/issues/34396

**Closed by bpasero** 2017-12-20 07:05 UTC
Labels: needs more info
