### ISSUE TITLE
CJK characters in minimap do not align

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#47430] opened 2018-04-08 13:00 UTC
- VSCode Version: 1.23.0-insiders
- OS Version: Windows 10 1709 (build 16299.334)

Steps to Reproduce:

1. Turn on the minimap.
2. Write something with CJK characters.

![image](https://user-images.githubusercontent.com/18233088/38467736-48ff320a-3b6f-11e8-8743-8248be30a8f6.png)

I use [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic) (Sarasa Mono SC Regular, exactly) as the editor font, and use the theme One Dark Pro Vivid.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment] 2018-04-09 08:42
Duplicate of #22652

**Closed by alexandrudima** 2018-04-09 08:42 UTC
Labels: insiders
