### ISSUE TITLE
Two Problems With Integrated Terminal

### ISSUE THREAD

**Issue by GigglePocket** [microsoft/vscode#128715] opened 2021-07-15 02:47 UTC
Issue Type: <b>Bug</b>

Upon running any python script, the trash can icon is non-functional.
The terminal display is blank except for the cursor at the bottom of the display until the terminal window is resized, then, the majority of output displayed is limited to two characters per line making the output unreadable.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.18GB free)|
|Process Argv|C:\\Users\\Malachi\\Desktop\\Desktop_Master\\_Shared_\\_Documents_\\Python\\Learning\\Practice, Project & Exercise Files\\Projects\\Image Converter\\Image_Converter.py --crash-reporter-id 5bf58387-f4a6-4b59-b3d3-da5638839151|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.2
vscode-json|and|1.5.0
vscode-django|bat|1.6.0
lit-html|bie|1.11.1
vscode-zonefile|Com|0.0.4
vcard|cst|1.0.1
ini-for-vscode|Dav|0.0.4
python-extension-pack|don|1.6.0
EditorConfig|Edi|0.16.4
code-runner|for|0.11.5
beautify|Hoo|1.5.0
latex-workshop|Jam|8.19.2
better-cpp-syntax|jef|1.15.6
vscode-sfz|jok|0.1.0
MagicPython|mag|1.1.0
rainbow-csv|mec|1.9.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
vscode-typescript-next|ms-|4.4.20210714
prettier-standard-vscode|num|0.8.1
fix-json|oli|0.1.2
colorful-comments|Par|0.6.2
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
markdown-snippets|rob|0.7.4
snippets-ranger|rob|0.20.2
code-spell-checker|str|1.10.2
openvms-syntax|tom|0.1.0
latex-support|tor|3.8.0
python-extended-snippets|tus|0.0.1
python-auto-venv|whi|1.2.2
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by Trimonu** [comment] 2021-07-15 05:21
I am having the same problem if anyone has a solution that would be great.

**Comment by blascsi** [comment] 2021-07-15 12:16
I am having the same issue where the trash button does not kill the integrated terminal.
Steps to reproduce:
 - Open VS Code
 - Use `Toggle Integrated Terminal` command
 - Click the trash icon
 - The terminal is not killed and it stays open.

Workaround:
Click inside the integrated terminal, and after the focus is there, click the trash icon again. That way the terminal is actually killed.

**Comment by meganrogge** [comment] 2021-07-15 15:55
will be fixed in the recovery build we release today , duplicate of #128264

**Closed by meganrogge** 2021-07-15 15:55 UTC
Labels: new release

**Comment by GigglePocket** [comment] 2021-07-15 17:08
Hello Attila!
    Thank you for the suggestion and the reply.
However, this does not work for me, as the trash can icon is unresponsive
even after clicking to move
focus to the terminal, also the keyboard shortcut Ctrl + ` has no effect.

I do see that this bug will be fixed today, so I'm sure all will be well.

As an aside, I'm superlatively impressed and surprised that this is the
first major bug I've
experienced using V.S Code given how extensive and full-featured this IDE
is.

So thank you to you and your team, as well as all individuals under the V.S
Code moniker.
Amazing work!
   -mal
