### ISSUE TITLE
vscode.debug.startDebugging returning undefined

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode#71565] opened 2019-04-01 21:23 UTC
Issue Type: <b>Bug</b>

`vscode.debug.startDebugging` is documented as returning `Thenable<boolean>`. 

I'm trying to attach to Python code that has not reached its `ptvsd.enable_attach` statement yet (reference: [Python Debugging](https://code.visualstudio.com/docs/python/debugging#_attach-to-a-local-script) ), and `vscode.debug.startDebugging` returns `undefined`.

Is `undefined` a valid return value? If so, the documentation is incorrect. If not, I'm unclear how this happens.

In case it helps explain the result from `vscode.debug.startDebugging`, here is the ms-python extension log relating to the call (portions have been replaced with the text 'removed').

```
11:31:43 AM, 3/30/2019
Started @ Sat Mar 30 2019 11:31:43 GMT-0700 (Pacific Daylight Time)
From Client:
Content-Length: 313

{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
To Client:
Content-Length: 761

{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"supportsGotoTargetsRequest":true,"supportsEvaluateForHovers":true,"supportsModulesRequest":true,"supportsValueFormattingOptions":true,"supportsHitConditionalBreakpoints":true,"supportsSetExpression":true,"supportsLogPoints":true,"supportTerminateDebuggee":true,"supportsCompletionsRequest":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
From Client:
Content-Length: 430

{"command":"attach","arguments":{"type":"python","request":"attach","name":"removed","host":"localhost","port":5858,"pathMappings":[removed],"logToFile":true,"debugOptions":["RedirectOutput","FixFilePathCase","WindowsClient"],"workspaceFolder":"removed","__sessionId":"72489843-a2bb-4208-8da0-5402cdc1a8c1"},"type":"request","seq":2}
To Client:
Content-Length: 430


To Client:
{"command":"attach","arguments":{"type":"python","request":"attach","name":"removed","host":"localhost","port":5858,"pathMappings":[removed],"logToFile":true,"debugOptions":["RedirectOutput","FixFilePathCase","WindowsClient"],"workspaceFolder":"removed","__sessionId":"72489843-a2bb-4208-8da0-5402cdc1a8c1"},"type":"request","seq":2}
To Client:
Content-Length: 313


To Client:
{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"python","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
Socket End
check and shutdown
shutdown
Sending Terminated Event
To Client:
Content-Length: 45


onEventTerminated
To Client:
{"seq":0,"type":"event","event":"terminated"}
Shutting down debug session
disposing
From Client:
Content-Length: 79

{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
Socket Error
check and shutdown
```

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|0.1.1
gitstash|art|1.0.2
vscode-svgviewer|css|2.0.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
tslint|eg2|1.0.43
plantuml|jeb|2.10.9
extension-manifest-editor|ms-|0.1.5
python|ms-|2019.3.6215
azure-account|ms-|0.8.0
csharp|ms-|1.18.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.4.0

</details>

**Comment by weinand** [comment] 2020-11-09 17:49
How does the code look like that calls `vscode.debug.startDebugging` ?

**Comment by connor4312** [comment] 2020-11-12 23:38
Tracing through the code I don't think this is possible today (barring spooky things in the proxy layer which we would see elsewhere). Looks like all code paths should either return a boolean or throw an exception.

**Comment by weinand** [comment] 2020-11-18 10:43
Closing since we cannot reproduce and there are no other reports for this.

**Closed by weinand** 2020-11-18 10:43 UTC
Labels: bug, debug
