### ISSUE TITLE
JavaScript Does not deindent brace on next line of if block

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32653] opened 2017-08-16 18:24 UTC
Follow up on https://github.com/Microsoft/vscode/issues/30933

**Repo**

1. 
 ```js
if (true) |
```

2. press return and then `{`

**expected**

```js
if (true)
{
     |
}
```

**actual**
```js
if (true)
    {
         |
    }
```

**Comment by ericdrobinson** [comment] 2017-08-16 18:53
This is simply a duplicate of #30933, which is not actually fixed yet. A somewhat related issue was identified and fixed(?) through the history of that issue.

**Closed** 2017-08-16 19:58 UTC
Labels: bug, editor-indentation, javascript

**Comment by simonl65** [comment] 2017-08-17 08:33
@ericdrobinson Agreed - this _is_ simply a duplicate of #30933.

@mjbvz When will your latest fix reach release?

**Comment by mjbvz** [comment] 2017-08-17 17:47
Yes, I didn't read the original issue correctly. This is a duplicate of #30933

This should be fixed in [insiders builds](https://code.visualstudio.com/insiders) already and will go into VSCode 1.16

**Comment by simonl65** [comment] 2017-08-17 18:39
Yay - that fixed it! @mjbvz Thank you.

**Comment by davidstlyoui** [comment] 2017-08-28 15:29
Thanks @mjbvz I tested and it would appear that it's fixed!
You have no idea how painful it was to code in the last ~2 months.
