### ISSUE TITLE
Code Insiders on Ubuntu always has an available update

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#26363] opened 2017-05-10 08:21 UTC
1. Download code insiders from `code.visualstudio.com`
2. Check for updates
3. There is an update available
4. Download and install code insiders again
5. There is still an update available

I've noticed this because of the popup.

![image](https://cloud.githubusercontent.com/assets/5047891/25889582/80c2bdc6-356a-11e7-95e7-49543c2f86b2.png)

**Comment by joaomoreno** [comment] 2017-05-10 08:40
@alexandrudima Installed version A from `apt-get`. It happens that since Insider is frozen, that specific version isn't _released_ by our update server. The latest released version is B. So the update mechanism inside Code keeps saying that there is an update available (a rollback to B), no matter what @alexandrudima does via `apt-get`.

@Tyriar Should we disable the update check for rpm and deb installations?

**Comment by Tyriar** [comment] 2017-05-15 20:31
@joaomoreno my thought was to delay it a week or so if it looks like the repo is installed. That would catch users who either don't have their repo set up correctly or who ignore the system update dialog.

Duplicate of https://github.com/Microsoft/vscode/issues/21651

**Closed by Tyriar** 2017-05-15 20:31 UTC
Labels: bug, install-update, linux

**Comment by alexandrudima** [comment] 2017-05-17 16:25
@Tyriar I think the bug is not a dup of #21651. I think the bug is that the linux repositories shipped an update when the Insiders build was frozen in our builds UI.

AFAIK we freeze the insiders builds during endgame for ~1 week to get coverage on the stable bits. If I understand what happens here, the repository served the new "frozen" build. I will have to double check this in the endgame week when we freeze again.

This means that we cannot rely on insiders coverage during the endgame for linux?

**Comment by Tyriar** [comment] 2017-05-17 16:38
@alexandrudima that specific problem is a duplicate of https://github.com/Microsoft/vscode-release-server/issues/5 then, which would leave it up to the release server to publish to the repo. Currently during end game I have been unpublishing the builds but yes you're right in that all users will not be on the build we expect.

**Comment by alexandrudima** [comment] 2017-11-07 09:49
ping @joaomoreno

**Comment by Tyriar** [comment] 2017-11-08 21:27
@joaomoreno did a fix which should stop Linux builds in the apt repo from getting too far ahead 🎉 

The only remaining issue is that deb builds need to be manually published to the repo or they will be on an older version (until https://github.com/Microsoft/vscode-release-server/issues/5 is covered). The good thing now though is that users can always go to the website to download the latest if they do fall out of sync.
