### ISSUE TITLE
Command Palette's command maybe not locale

### ISSUE THREAD

**Issue by 1msoft** [Microsoft/vscode#5590] opened 2016-04-21 01:25 UTC
- VSCode Version:1.0
- OS Version:osx

Steps to Reproduce:

1. set locale to zh-CN
2. F1 open Command Palette, press "Tasks", nothing.

**Comment by Treri** [comment] 2016-04-21 01:30
#4679

**Comment by Tyriar** [comment] 2016-04-21 01:30
Closing as duplicate of https://github.com/Microsoft/vscode/issues/4679

**Closed by Tyriar** 2016-04-21 01:30 UTC
