### ISSUE TITLE
Alt + F not triggering "File menu"

### ISSUE THREAD

**Issue by jjacode** [Microsoft/vscode#10525] opened 2016-08-14 21:15 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. In VSCode, press Alt + F (or Alt + E/V/G/H)
2. Notice the dropdown menu that isn't showing up as it used to (But the Key hints show up under respective menu items)

**Comment by bpasero** [comment] 2016-08-15 09:00
@jjacode I cannot reproduce on my Windows 10, sorry.

**Comment by bpasero** [comment] 2016-09-18 07:28
@jjacode  could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by ramya-rao-a** [comment] 2016-09-29 00:51
Cannot reproduce in VS Code 1.5.3 on Windows 10 either.

**Comment by jjacode** [comment] 2016-09-29 04:57
This only appears to be reproducible when the integrated terminal has focus.

**Comment by bpasero** [comment] 2016-09-29 06:04
I think the integrated terminal steals all keypresses. @Tyriar can comment on that.

**Comment by Tyriar** [comment] 2016-09-29 16:14
@jjacode the terminal consumes most keypresses with the exception of the commands listed in the `terminal.integrated.commandsToSkipShell` setting and ones which xterm.js doesn't care about. The alt shortcuts for the menu work fine on Linux while focusing the terminal though, I'll have a quick look when I'm on Windows.

**Comment by jjacode** [comment] 2016-09-29 16:39
@Tyriar I've not tried it in Linux yet. But, in Windows when I press Alt the File Menu does the underlining like expected (File underlines "f", Edit underlines "E", etc). But then the terminal captures the letter.

**Comment by Tyriar** [comment] 2016-09-29 16:42
Do you press alt and then f, not alt+f at the same time? I think that's an Electron thing.

**Comment by jjacode** [comment] 2016-09-29 16:43
I'm pressing and holding Alt, then with Alt still pressed I press "F"

**Comment by Tyriar** [comment] 2016-10-22 12:30
Repro'd on Windows, xterm.js must be consuming the keystrokes for some reason.

**Comment by iamzhout** [comment] 2016-10-24 09:18
I also have the same problem, all menu will not popup when hitting **alt + f / e / v / g / h**

* VSCode Version: latest stable 1.6.1
* OS Version: Windows 7

**Comment by nrkn** [comment] 2016-11-27 21:23
I've just started having this issue today. Was working fine yesterday, and the last update was a week ago so it's been working fine for some days until now.

VSCode 1.7.2
Windows 10

**Comment by Tyriar** [comment] 2016-11-28 19:44
Created an upstream issue https://github.com/sourcelair/xterm.js/issues/384

**Comment by Tyriar** [comment] 2016-12-15 19:14
Upstream doesn't want this for good reason. Should check what powershell, cmd, cmder, etc. do with their alt+shortcuts/menus and see if we need a flexible solution or maybe we can just hardcode them.

**Comment by Tyriar** [comment] 2017-04-20 21:05
Closing since this is as designed upstream, see https://github.com/sourcelair/xterm.js/issues/384

**Closed by Tyriar** 2017-04-20 21:05 UTC
Labels: bug, integrated-terminal
