### ISSUE TITLE
Code is deleting on page refresh

### ISSUE THREAD

**Issue by LucyFosterCodeweavers** [microsoft/vscode#79438] opened 2019-08-19 09:00 UTC
VSCode Version: 1.37.1
OS Version: macOS Mojave 10.14.5
Does this issue occur when all extensions are disabled?: Yes

Hi, 

I've been having the same issue occur over and over again, normally when first opening the project up. I will open a php file and type some code (this is happening with both html and php) & go a browser and refresh. When I go back to the php file the code I have just written has disappeared. I've included a gif of what it's doing below. 

I've tried in chrome, safari and firebox but the same thing is happening. 

Normally restarting both mamp and vscode will fix the issue, but today it's still not working. 

![vs-gif](https://user-images.githubusercontent.com/46441527/63252661-19fe6300-c268-11e9-9b69-0a3320ee882f.gif)

**Comment by m8than** [comment] 2019-08-19 09:20
VS Code automatically refreshes your files. So the only thing I can think of is that some other software is overwriting the file instantly? Idk like some security stuff thats preventing vscode from writing the file

**Comment by isidorn** [comment] 2019-08-19 09:33
Can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
This sounds like it is caused by some extension.

**Comment by LucyFosterCodeweavers** [comment] 2019-08-19 09:40
It works with vscode insiders!

I've turned off all extensions in vscode & restarted but I'm still having the same issue. 😔

**Comment by isidorn** [comment] 2019-08-19 12:48
If it works with vscode insiders then it should be fixed when you update.
You can also switch to vscode insiders.
Thus closing this.

**Closed by isidorn** 2019-08-19 12:48 UTC
Labels: needs more info, new release
