### ISSUE TITLE
Tasks "No build tasks defined" with `isBuildCommand`.

### ISSUE THREAD

**Issue by wgj** [Microsoft/vscode#24796] opened 2017-04-14 18:28 UTC
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>b</kbd> to build
2. Observe 
![screen shot 2017-04-14 at 11 18 42 am](https://cloud.githubusercontent.com/assets/463564/25052054/b520b20a-2104-11e7-9965-c6b7c9419204.png)
3. Click "Configure Build Task"
4. Observe `tasks.json`. Is `isBuildCommand` not used elsewhere in `tasks.json`.
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "isBuildCommand": true,
            "command": "cl",
            "isShellCommand": true,
            "args": ["cc", "-Wall", "-Wextra", "-Werror", "-g", "${fileDirname}/${fileBasename}", "${fileDirname}/${fileBasenameNoExtension}_test.c", "-o", "${fileDirname}/${fileBasenameNoExtension}_test"],
            "showOutput": "always",
            "dependsOn": "clean"
        },
snip...
```
Screenshot of Developer Tools (I don't know how to export console log for you):
![screen shot 2017-04-14 at 11 18 28 am](https://cloud.githubusercontent.com/assets/463564/25052113/06798852-2105-11e7-9881-535cfc0fd32e.png)

**Comment by wgj** [comment] 2017-04-14 18:29
Closing and reopening the window (without starting Code) resolves this issue.

**Comment by wkrueger** [comment] 2017-04-15 05:09
Yeah, that solved.
![capture](https://cloud.githubusercontent.com/assets/2209181/25060957/7f4cc28c-2180-11e7-9bb4-d689a1cb0b3b.PNG)
Got the same here.

**Comment by wgj** [comment] 2017-04-15 05:20
I think I have a better understanding the repo conditions here. 

I have a lot of small projects, and I create symlinks for tasks.json and launch.json from my home directory, so I don't have to make or copy around a bunch.

The above error (No build task defined, but isBuildTask is defined) happens when I link the .vscode directory and attempt to build from a VS Code editor that was already open. It's as if there's some parsing of tasks.json that only happens on new windows.

I run this inside of my workspace...
```
function 42vscode {
  mkdir .vscode
  ln -s ~/Workspace/github/dotfiles/vscode/42_tasks.json .vscode/tasks.json
  ln -s ~/Workspace/github/dotfiles/vscode/42_launch.json .vscode/launch.json
  return 0
}
```
to make these links...
```
d09 (master) $ ls -l .vscode/
total 16
lrwxr-xr-x  1 wes  staff  58 Apr 13 18:17 launch.json -> /Users/wes/Workspace/github/dotfiles/vscode/42_launch.json
lrwxr-xr-x  1 wes  staff  57 Apr 13 18:17 tasks.json -> /Users/wes/Workspace/github/dotfiles/vscode/42_tasks.json
```

**Comment by seyaobey** [comment] 2017-04-16 00:05
I am facing the same problem. It just started this morning. I am unable to build my projects using Ctrl+Shift+B. I keep receiving the same error even if I add "isBuildCommand" to the task.json:

![capture](https://cloud.githubusercontent.com/assets/2738569/25067611/a9c5473c-21fd-11e7-95ed-3137239ba81a.PNG)



This is my version:

![capture](https://cloud.githubusercontent.com/assets/2738569/25067588/2a76a8e0-21fd-11e7-9bec-5374752e008d.PNG)

**Comment by javierquevedo** [comment] 2017-04-19 09:02
Same problem, even if I have the isBuildCommand in the tasks.json

**Comment by xJeremie** [comment] 2017-04-21 08:12
Same problem. Turn it on and off REALLY WORK! 😆

**Comment by lukeaus** [comment] 2017-04-24 23:15
A restart fixed it for me, even if isBuildCommand is in tasks.json

**Comment by dbaeumer** [comment] 2017-04-25 13:43
There was a problem that the tasks.json didn't get reparsed after a change if not task has been started before. This is fixed for the next releases. However looks like that people get this even without editing the tasks.json.

**Comment by dbaeumer** [comment] 2017-04-25 13:48
I can't reproduce this neither with the new terminal nor with the old output runner. Here is what I see 

![cast](https://cloud.githubusercontent.com/assets/1931590/25388386/183c2ac8-29ce-11e7-8c17-3fea8deb6788.gif)

and with the new runner:

![cast](https://cloud.githubusercontent.com/assets/1931590/25388459/375a83fa-29ce-11e7-842e-868485069833.gif)

Can someone provide a repository that I could clone to reproduce this. 

As said the only case I can reproduce this is starting with no tasks.json. 

![cast](https://cloud.githubusercontent.com/assets/1931590/25388599/90926410-29ce-11e7-8e21-f01152ddfeb1.gif)

**Comment by jasonswearingen** [comment] 2017-04-25 22:55
i started with no tasks.json (new project) and got this issue.   restarting fixed.

**Comment by dbaeumer** [comment] 2017-04-26 07:30
@jasonswearingen this got fixes for the next update and doesn't require a restart anymore.

**Comment by wgj** [comment] 2017-04-26 23:23
Looks like others might encounter this issue for a different reason, but since I'm the author...

> There was a problem that the tasks.json didn't get reparsed after a change if not task has been started before.

This will likely resolve the issue. Thank you.

> Can someone provide a repository that I could clone to reproduce this.

The issue (for me) is reproduced when starting with workspace without `.vscode` and it's contents, and then they're copied into place out of band (bash `mv` or `cp` existing `tasks.json` from another workspace).

**Comment by dbaeumer** [comment] 2017-04-27 10:58
@wgj I tested your scenario and it works for me on latest insider builds (e.g. copying files into a .vscode directory). I will close the issue since all problematic scenarios described are working for me on insider.

**Closed by dbaeumer** 2017-04-27 10:58 UTC
Labels: bug, needs more info, tasks

**Comment by wkrueger** [comment] 2017-04-29 01:51
Just had the same problem again on the live build in a new project.
Again, restarting the editor solved.

**Comment by dbaeumer** [comment] 2017-05-02 08:53
@wkrueger this got addressed for the next upcoming build which will ship soon.
