### ISSUE TITLE
Fix spdlog Windows issue with non-ascii characters

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58044] opened 2018-09-06 07:01 UTC
From @gnaggnoyil

It seems to be a node-spdlog issue as it does not define `SPDLOG_WCHAR_FILENAMES` macro in `binding.gyp` which is required by spdlog backend to be compiled with wchar filename support since Windows assumes locale-specific multibyte encoding for C's `char []` Null-Terminated Character Type String by default while node.js assumes UTF-8 if I did not get it wrong.

Ref:
https://github.com/Microsoft/node-spdlog/blob/master/binding.gyp
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/os.h#L158

**Comment by jibsen** [comment] 2018-09-06 07:12
I've seen 2-3 issues appear and disappear over the past hour here about code failing on Windows seemingly related to user folders containing non-ascii characters (not sure why they disappear). I am having the same problem after updating to 1.27, I get a blank window where nothing works and the developer tools show a number of errors related to spdlog. My user name contains the Danish character 'ø'.

Is there a way to downgrade to the previous version until this is fixed? I can't find older downloads on the code download site.

**Comment by sandy081** [comment] 2018-09-06 14:57
Duplicate of #47883

**Closed by sandy081** 2018-09-06 14:57 UTC
Labels: bug, log
