### ISSUE TITLE
No Extensions Found

### ISSUE THREAD

**Issue by SemRithiro** [Microsoft/vscode#57917] opened 2018-09-05 01:05 UTC
Issue Type: <b>Bug</b>

I can't find any extensions to install.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.5.3

</details>

**Comment by seraph127** [comment] 2018-09-05 01:37
VS Code reports not finding extensions (that I haven't installed) on monthly or Insider, on my  Windows and Linux installations.

**Comment by christian-chen** [comment] 2018-09-05 01:54
I also got this problem , https://marketplace.visualstudio.com/VSCode  is not availble

**Comment by sultansgillani** [comment] 2018-09-05 01:54
See https://github.com/Microsoft/vscode/issues/57851

**Comment by mjbvz** [comment] 2018-09-05 02:36
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 02:36 UTC
Labels: extensions
