### ISSUE TITLE
Freeze and a lot lag since last update !!!

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#38729] opened 2017-11-19 19:59 UTC
hi since the last update, i have a lot of lag and freeze , when a jump line in vsc !
befor was very fast rendering color bracket, and some texture element, but now its very slow.

When i jump line, its freeze about (4 to 6 second !)

plz how i can come back to last stable version?, do you have a link ?

i desactivate all plugin and its not a plugin..

edit: Fixed, remove all Breakpoints.
You have a mistake in Breakpoints rendering thats freeze !

**Comment by roblourens** [comment] 2017-11-20 01:17
Related to https://github.com/Microsoft/vscode/issues/37880?

**Comment by isidorn** [comment] 2017-11-20 09:21
Yeah, duplicate of #37880
@djmisterjon please update to latest stable and the problem should be fixed

**Closed by isidorn** 2017-11-20 09:21 UTC
Labels: editor, freeze-slow-crash
