### ISSUE TITLE
Format code in left pane, will set the scroll position of same file in right pane to bottom

### ISSUE THREAD

**Issue by sreekumarp** [Microsoft/vscode#47635] opened 2018-04-11 06:44 UTC
Issue Type: <b>Bug</b>

Open same file in left and right panes
Format code in left pane, will set the scroll position of right pane file to bottom

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|Memory (System)|15.88GB (0.99GB free)|
|Process Argv|D:\Apps\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.4.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.27
prettier-vscode|esb|1.2.2
auto-rename-tag|for|0.0.15
json2ts|Gre|0.0.6
angular2-switcher|inf|0.1.6
vscode-scss|mrm|0.6.2
csharp|ms-|1.14.0
team|ms-|1.133.0
debugger-for-chrome|msj|4.3.0
vscode-versionlens|pfl|0.20.0
autoimport|ste|1.5.3
Angular2|UVB|0.4.1
vscode-import-cost|wix|2.6.2

</details>

**Comment by alexandrudima** [comment] 2018-04-13 09:19
@sreekumarp I believe this is a duplicate of #47382. Is this something you can reproduce if you update to 1.22.2 ?

**Closed** 2018-04-20 09:43 UTC
Labels: needs more info
