### ISSUE TITLE
'list.select' keybinding not working in file Explorer pane

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#107377] opened 2020-09-24 19:17 UTC
Issue Type: <b>Bug</b>

When I select a file in the Explorer with the mouse, it opens that file but also 'selects' it, highlighting it with a prominent highlight.

Firstly I don't understand the purpose of this selection. It doesn't do anything. If I use the keyboard to move the keyboard focus to a different file, the 'selection' remains on the file I opened with the mouse, but if I now use a shortcut to perform some action e.g. rename, delete, this action occurs on the file with the keyboard focus _not_ the apparently 'selected' file! So what the hell is the selection for? But I've already reported that and had that [bug report](https://github.com/microsoft/vscode/issues/107180) closed as 'by design' on the basis that while it doesn't make any sense at all that's the way the vscode team want to do it anyway. Fine, whatever.

So this bug is to report a related but distinct issue. Which is that the keybinding for `list.select` doesn't work. On my system the keybinding for `list.select` is `Enter` which is its default value. If I click a file in the Explorer with the mouse it is opened and also selected. If I then use the keyboard to move the keyboard focus to another file and press `Enter` the file is opened, <i>but the file selected using the mouse remains the one highlighted as being selected</i>
 
That's got to be a bug right?

Here are some screenshots to show you what I'm talking about.

![Focus0](https://user-images.githubusercontent.com/18445931/94188360-2c9e8f00-fea1-11ea-99b7-569da7c92f9f.jpg)

![Focus1](https://user-images.githubusercontent.com/18445931/94188370-31fbd980-fea1-11ea-8f02-13566bf26fd2.jpg)

![Open](https://user-images.githubusercontent.com/18445931/94189266-6cb24180-fea2-11ea-9cbc-f436b6c7f812.jpg)

![Borked](https://user-images.githubusercontent.com/18445931/94189280-7045c880-fea2-11ea-9047-85e986b3ab5c.jpg)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.9.0
vscode-great-icons|emm|2.1.56
vscode-jasmine-test-adapter|hbe|1.7.0
vscode-test-explorer|hbe|2.19.1
classic-asp|ili|0.0.4
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.22.0
debugger-for-chrome|msj|4.12.10
nativescript|Tel|0.11.0
subtle-brackets|raf|3.0.0
rewrap|stk|1.13.0
insert-special-symbol|swi|1.3.0
indent-one-space|use|0.2.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by isidorn** [comment] 2020-09-25 08:26
This is native tree behavior forwarding to @joaomoreno
@joaomoreno do we have some master issue for list tree selection and focus so I can just close as duplicate issues of these kind that come in?

**Comment by JW9506** [comment] 2020-09-26 13:08
While trying to reproduce it, although I wasn't able to, I found another issue where when a file is selected, close the file in the editor(I used Ctrl + w), the explorer doesn't 'deselect' the file just closed, so any efforts trying to reopen the file by firing  `list.select` would fail.  Is this behavior expected?

**Comment by Neutrino-Sunset** [comment] 2020-09-26 14:20
I'm surprised you can't reproduce my issue, it's completely consistent across several machines for me, although settings sync could be synching a problematic configuration. Still I can't help wondering whether clarifying the reproduction steps might help.

1. Click a file in the Explorer with the mouse: the file is opened and shows as selected in the Explorer.
2. Press ctrl+shift+e to return focus to the Explorer.
3. Use up/down arrow key to move keyboard focus to another file: previous file remains selected.
4. Press enter to open the file with the keyboard focus: newly opened file is not selected.
5. Press ctrl+shift+e to focus the Explorer again: the first file opened with the mouse remains selected.

**Comment by JW9506** [comment] 2020-09-26 14:25
> I'm surprised you can't reproduce my issue, it's completely consistent across several machines for me, although settings sync could be synching a problematic configuration. Still I can't help wondering whether clarifying the reproduction steps might help.
> 
> 1. Click a file in the Explorer with the mouse: the file is opened and shows as selected in the Explorer.
> 2. Press ctrl+shift+e to return focus to the Explorer.
> 3. Use up/down arrow key to move keyboard focus to another file: previous file remains selected.
> 4. Press enter to open the file with the keyboard focus: newly opened file is not selected.
> 5. Press ctrl+shift+e to focus the Explorer again: the first file opened with the mouse remains selected.

In my case, in step 4, the new file is selected and shown in the editor with `editorTextFocus`, also the previous file `selected` state is gone.

**Comment by Neutrino-Sunset** [comment] 2020-09-26 18:33
Yes. I see the same effect with all extensions disabled.

**Comment by joaomoreno** [comment] 2020-09-30 12:34
@isidorn This is a bug on the Explorer, something broke here lately.

Steps:

1. Click on a file
2. Press <kbd>ArrowDown</kbd>, <kbd>Enter</kbd>

The second file should be selected, but the first remains selected.

![recording (5)](https://user-images.githubusercontent.com/22350/94685620-f8f0b880-0329-11eb-8b31-a9b5408aa5a7.gif)

**Comment by joaomoreno** [comment] 2020-09-30 12:51
@isidorn This can easily be fixed by deleting this code: https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/contrib/files/browser/fileCommands.ts#L147-L163 It appears it's no longer needed, given the reworkings of list commands, the `list.select` command should work just fine in the explorer.

**Comment by isidorn** [comment] 2020-09-30 12:52
@joaomoreno I just checked stable and we also behave the same there.
So what I see is thta when you press `Enter` focus gets moved to the editor area. Thus the tree no longer has focus, and I thought that the tree only renders selection then.
If after your steps I do `F1 > Focus on Folders View` you can see that the focus is preserved.

Ok now you commented again, let me see what removing that code does...

**Comment by isidorn** [comment] 2020-09-30 12:55
You are correct I can remove that command, however I introduced it explicitly to fix this issue https://github.com/microsoft/vscode/issues/104783

Since when removing the command that issue no longer reproduces I will simply remove the command as you suggest.
Thank you!

**Comment by joaomoreno** [comment] 2020-09-30 12:58
Are you sure? The `list.select` handles that keyboard shortcut too:

https://github.com/microsoft/vscode/blob/78b0d0a446681dd4a98ced495be2ea81bc9b8708/src/vs/workbench/browser/actions/listCommands.ts#L536-L536

Can you check what gets run instead of the `list.select` command on macOS?

**Comment by isidorn** [comment] 2020-09-30 13:00
@joaomoreno in that case the selection does not change. And the select event probably does not fire. Read the description of that issue carefully

"open a file with the mouse
press Cmd+ArrowDown"
So you are pressing cmd+arrowdown on an already selected file

**Comment by joaomoreno** [comment] 2020-09-30 13:00
> So what I see is thta when you press `Enter` focus gets moved to the editor area. Thus the tree no longer has focus, and I thought that the tree only renders selection then.

The problem seems to be that the code that reveals in the tree the opened text editor file is not working in this case, since all your command does is open a file. Notice in the GIF how that reveal feature works just fine when I use the command palette to switch files. But it just seems not to work at all when going through your custom command.

**Comment by isidorn** [comment] 2020-09-30 13:00
Yeah. I agree, that seems to be the issue.

**Comment by joaomoreno** [comment] 2020-09-30 13:01
> So you are pressing cmd+arrowdown on an already selected file

Oh. Yeah that's the thing. Yeah you need a custom command for that.

**Comment by isidorn** [comment] 2020-09-30 13:04
Found the issue, pushing fix...
THanks for the help

**Comment by isidorn** [comment] 2020-09-30 13:07
@Neutrino-Sunset `list.select` unfortunetly does not work in the explorer (you can read our discussion from above). You need to use the following command `explorer.openAndPassFocus`

**Closed** 2020-09-30 13:06 UTC
Labels: bug, file-explorer

**Comment by Neutrino-Sunset** [comment] 2020-09-30 13:55
The default configuration appears to be that both `list.select` and `explorer.openAndPassFocus` are already bound to `Enter`.

But I don't understand though. What do I need to do in order to be able to open a file in Explorer using the keyboard and have the correct file appear selected? Do I need to rebind `explorer.openAndPassFocus` to another key or something?

**Comment by isidorn** [comment] 2020-09-30 17:51
The bug was that it did not appear selected. I have pushed a fix for that.
You only need to rebing explorer.openAndPassFocus if you want to use a custom keybinding.

**Comment by Neutrino-Sunset** [comment] 2020-10-01 08:58
So I just need to wait for the fix to come through. Great, many thanks.

**Comment by isidorn** [comment] 2020-10-01 09:00
@Neutrino-Sunset it is already released in vscode insiders if you want to try it out you can.
