### ISSUE TITLE
All default hotkeys are missing after update

### ISSUE THREAD

**Issue by kirillDanshin** [Microsoft/vscode#24345] opened 2017-04-09 05:08 UTC
after update vscode doesn't know about ctrl+c, ctrl+v, ctrl+z, ctrl+y, ctrl+q etc. even when I have no extensions installed, even if I install vscode to fresh system.

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 3.10.0-514.2.2.el7.x86_64
- Extensions: none
---

Steps to Reproduce:

1.
2.

#24343 plus one.

**Comment by kirillDanshin** [comment] 2017-04-09 05:09
labels: [wtf] [bug]

**Comment by alexandrudima** [comment] 2017-04-10 08:21
@kirillDanshin 

I would like to find out what about your environment makes scan code based dispatching fail?

#### 1. What linux distribution are you using?
#### 2. What keyboard layout are you using?
#### 3. What do we receive from Electron when you do these key combinations?
 - open Preferences > Keyboard Shortcuts
 - click on `keybindings.json`
 - on the right hand side editor click on Define Keybinding
 - press the key combination that has a problem
 - hover with the mouse over the input box
 
![image](https://cloud.githubusercontent.com/assets/5047891/24852340/62543a40-1dd7-11e7-8b4e-b9be991d1eb9.png)

#### 4. Possible workaround
Add the following to your settings: `"keyboard.dispatch": "keyCode"` and restart VS Code

**Comment by kirillDanshin** [comment] 2017-04-10 13:15
1. Latest centos 7 w/ xfce/kde.
2. Default english and russian.
3. I'll send it ASAP.

**Comment by alexandrudima** [comment] 2017-04-10 13:36
Thank you for the extra information.

Duplicate of #24057

**Closed by alexandrudima** 2017-04-10 13:36 UTC
Labels: keybindings, linux, needs more info
