### ISSUE TITLE
Provide an option to preserve order when filtering a quickpick list

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#104202] opened 2020-08-06 20:21 UTC
Original order:

![image](https://user-images.githubusercontent.com/13199757/89578221-ae016b80-d7e6-11ea-982d-db6f10868bcf.png)

After I type 'P' in the filter box:

![image](https://user-images.githubusercontent.com/13199757/89578298-c7a2b300-d7e6-11ea-96f8-e42262a5fb70.png)

Python 2.7 is thrown way down. I am wondering what's the current sorting criteria?

We had a scenario where we're trying to dynamically update the list. If new items can appear anywhere in the list, there’s a race condition when the user is trying to click an item, and ends up accidentally clicking the wrong one because the original one shifted down due to more items inserted above.

We were hoping that when we add items at the end of the list, so we don't run into this problem. However when user has something typed in the filter box, this does not happen as the original order is not maintained.

**Comment by karrtikr** [comment] 2020-08-17 13:29
@chrmarti Looks like this issue was missed, can this be acknowledged?

**Comment by chrmarti** [comment] 2020-08-17 14:01
Duplicate of https://github.com/microsoft/vscode/issues/73904

**Closed by chrmarti** 2020-08-17 14:01 UTC
Labels: quick-pick
