### ISSUE TITLE
flash white before menu appears

### ISSUE THREAD

**Issue by johngrabner** [microsoft/vscode#89801] opened 2020-01-31 16:43 UTC
Issue Type: <b>Bug</b>

Anytime a menu is about to appears, that area of the menu is cleared with white, then the menu background  is drawn, then the menu content.
With a dark theam, this white flash is very anoying.
Rather then clear the menu area, just do the next step of filling with menu background.  This would avoid this high speed flash.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-28-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4391)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.75GB (46.41GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.10.0
python|ms-|2020.1.58038
cmake-tools|ms-|1.2.3

</details>

**Comment by sbatten** [comment] 2020-02-03 15:23
@deepak1556 correct me if im wrong. i believe this is an electron+linux issue that can be fixed with disabling gpu acceleration. https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by RonaldinhoL** [comment] 2020-03-13 13:07
i meet the same probelem, i have try 
https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
and it is not working.

**Comment by mustafashujaie** [comment] 2020-03-20 04:12
Using `--disable-gpu` does not solve it. It happens for both dark and light themes and very annoying. 


<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.38GB (2.88GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14


</details>

**Comment by deepak1556** [comment] 2020-03-20 23:13
Is everyone seeing the issue, have their titlebar setting `window.titleBarStyle` as `custom` or `native` ?

**Comment by mustafashujaie** [comment] 2020-03-21 07:56
For me it was native, changed it to custom and it fixed it. Thanks!

**Comment by RonaldinhoL** [comment] 2020-03-22 11:16
native --> custom it not appears anymore, another problem how to change the menu fonts?

**Comment by deepak1556** [comment] 2020-03-31 20:37
Thanks for the details, closing this as duplicate of https://github.com/microsoft/vscode/issues/80798 , please follow that issue for updates.

**Closed by deepak1556** 2020-03-31 20:37 UTC
Labels: linux, menus, needs more info
