### ISSUE TITLE
Treeview node inline editor

### ISSUE THREAD

**Issue by kayazinc** [microsoft/vscode#151829] opened 2022-06-11 11:23 UTC
Can vscode provides the API for treeview node inline editor?
Example, feature similar to the "rename file" [F2] action in file explorer.

Thanks!

**Comment by alexr00** [comment] 2022-06-14 10:50
duplicate of https://github.com/microsoft/vscode/issues/97190

**Closed by alexr00** 2022-06-14 10:50 UTC
