### ISSUE TITLE
Fold/Unfold action does not support multiple regions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3319] opened 2016-02-23 13:46 UTC
On testing #2994

In this snippet range select both 'foo' and 'bar' methods and then perform 'Fold' operation.
```
class xyz {
	foo() {
		hello
	}
	bar() {
		world
	}
}
```

Observe: only 'foo' is collapsed.
I would expect that all regions overlapping with the text selection are collapsed.

**Comment by aeschli** [comment] 2016-02-24 14:48
duplicate of #3403

**Closed by aeschli** 2016-02-24 14:48 UTC
