### ISSUE TITLE
Inline variable previewing when debugging

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#54526] opened 2018-07-18 03:56 UTC
Google Chrome has this ability:

![inline-js-values](https://user-images.githubusercontent.com/9585787/42858508-345e845a-8a79-11e8-88bf-2802ffebe7cc.gif)

Very handy, hopefully VSCode can follow suit?

**Comment by jpike88** [comment] 2018-07-18 04:04
Wow just found this after more googling: "debug.inlineValues"

How is this still experimental??? Isn't this something that shouldn't be tucked away as a dormant option? It's hard enough to know it exists to begin with!

**Comment by myfairsyer** [comment] 2018-07-18 09:04
#12256 #13424 #18670

**Comment by myfairsyer** [comment] 2018-07-18 09:07
https://code.visualstudio.com/updates/v1_9#_inline-variable-values-in-source-code
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_inline-values

**Comment by weinand** [comment] 2018-07-18 09:43
duplicate of #13424.

**Closed** 2018-07-18 09:43 UTC
Labels: *duplicate, feature-request

**Comment by weinand** [comment] 2018-07-18 09:51
Where does VS Code say that "debug.inlineValues" is experimental?

**Comment by myfairsyer** [comment] 2018-07-18 10:37
> Where does VS Code say that "debug.inlineValues" is experimental?

Here: https://github.com/Microsoft/vscode-docs/commit/785ed6e949131b088679a88d389ee57d6c40cd8b#diff-14c0ef6b1c3e28aad72ba871f25aeb0bR816

**Comment by weinand** [comment] 2018-07-18 10:49
Yeah, we could remove the "experimental" now (@gregvanl).

We don't enable this feature by default because:
- it is expensive and slows down stepping,
- many transpilers generate source maps that lack correct variable mappings. The consequence of this is that some values are not shown at all or wrong values are shown.

**Comment by gregvanl** [comment] 2018-07-18 17:14
@weinand Updated docs with https://github.com/Microsoft/vscode-docs/commit/6f2969865e89380050df027aa2448d3738ffd066
