### ISSUE TITLE
additionalTextEdits runs before selection is added to document

### ISSUE THREAD

**Issue by dinhani** [Microsoft/vscode#21836] opened 2017-03-02 21:55 UTC
- VSCode Version: 1.10.1
- OS Version: Windows 7 64 SP1 

Steps to Reproduce:

1. Create a completion item like this:
```typescript
    const completionItem = new CompletionItem("test", CompletionItemKind.Property);
    completionItem.additionalTextEdits = [TextEdit.insert(position, " = ")]
    return completionItem;
```
2. I was expecting to see ` = `  inserted after the `test` keyword was added, but actually the text inserted from the `CompletionItem` replaces the `additionalTextEdits` actions. If I CTRL+Z I can see the selected completion item replaced it.

3. In my case, I want to run the `additionalTextEdits` after the keyword selected in the autocomplete is added to the document, so it would be good if we had `additionalTextEditsBeforeSelectionAdded` and `additionalTextEditsAfterSelectionAdded`

**Comment by jrieken** [comment] 2017-03-03 13:02
dupe of #19694. Long story short is that it's unexpected for to have additional text edits that modify text around the cursor. We advise to keep that in the *main* edit

**Closed** 2017-03-03 13:02 UTC
Labels: duplicate, suggest
