### ISSUE TITLE
Print my code in visual studio

### ISSUE THREAD

**Issue by Aerosiderolito** [Microsoft/vscode#64403] opened 2018-12-05 01:36 UTC
Issue Type: <b>Feature Request</b>

Please can you add a print option?

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment] 2018-12-05 05:30
Duplicate of #7076

**Closed by mjbvz** 2018-12-05 05:30 UTC
