### ISSUE TITLE
launch.json file opens when purposely cancelling debug from extension provider.

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#54702] opened 2018-07-20 02:36 UTC
I have an extension that is providing debug configurations, however these configurations are mainly just used to call other debuggers (mainly the C++ and Java ones from their respective extensions). If I return `undefined` from `resolveDebugConfiguration`, I get the main behavior I want, as I can call the other debuggers, however when I leave the debugger, or if I return early because I need to cancel debugging, the editors always opens the launch.json file. I've tried returning the configuration rather then undefined, however when doing so the debugger enters an infinite loop, and I can't run the debugger again. It seems like this behavior should be something an extension vendor is able to control.

**Comment by isidorn** [comment] 2018-07-20 08:07
This is some historic behavior which some other debug extensions are depending on.
Let's treat as a duplicate of https://github.com/Microsoft/vscode/issues/51069
And you can express your opinoin in that issue. Thanks

**Closed by isidorn** 2018-07-20 08:07 UTC
Labels: debug
