### ISSUE TITLE
Ctrl+Up/Down scrolling cursor should always maintain bottom/top of the visible area

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#91867] opened 2020-03-02 02:01 UTC
**VSCode Version**: 1.42
**OS Version**: Windows 7 x64 Pro

Steps to Reproduce:

1. Typically, you find editors that support Ctrl+Up/Down scrolling will maintain cursor position at the bottom/top of the visible area, respectively.
2. Currently, the cursor remains parked where ever it was when you start scrolling. The impulse is to navigate with the cursor, which reorients the editor where ever it was before you scrolled.

**Comment by alexdima** [comment] 2020-03-02 08:56
Duplicate of #59247

---

You can install the VS Keymap extension or you can use the `editorScroll` command in your `keybindings.json`:

e.g.

```
{
	"key": "ctrl+up",
	"when": "editorTextFocus",
	"command": "editorScroll",
	"args": {
		"to": "up", // 'up', 'down'
		"by": "line", // 'line', 'wrappedLine', 'page', 'halfPage'
		"value": 1, // number of units to move
		"revealCursor": true
	}
}
```

**Closed by alexdima** 2020-03-02 08:56 UTC

**Comment by mwpowellhtx** [comment] 2020-03-02 13:32
Works great, thank you! Rinse and repeat for `up` versus `down`.
