### ISSUE TITLE
VS Code stuck indefinitely

### ISSUE THREAD

**Issue by aulon** [microsoft/vscode#130972] opened 2021-08-17 07:21 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10 Pro 21H1

Steps to Reproduce:

1. Open a folder with thousands of CSV files. Example used (FPL Data): https://github.com/vaastav/Fantasy-Premier-League/tree/master/data
2. Try to replace strings in all those files using VS Code. 

What happened was that VS got stuck and it showed one message: "VS Code not working" with three options "Reopen, Keep waiting, Close". Both options "Reopen" and "Close" simply closed the editor. "Keep waiting" waited for a couple of seconds and then showed the same message again. 

I tried to:
1. Kill the VS Code process via the Task Manager
2. Shut down the computer
3. Restart the computer
4. Start VS code from CMD using `code --disable-exensions`. This last one opened two windows of VS Code. One of which was functional. This still did not remove the blocked window. 

I also found the same issue in this link https://github.com/microsoft/vscode/issues/109811.

Today I managed to find a solution. I deleted all the temp files under: `C:\Users\{USERNAME}\AppData\Roaming\Code\Backups`
Since I could not comment on the issue above, I decided to create a new issue here to let other people know the solution. 

To the contributors of the issue https://github.com/microsoft/vscode/issues/109811 , please comment my solution in the thread if you find it helpful. 

I wish you all a good day :)

**Comment by JacksonKearl** [comment] 2021-08-23 22:09
cc @bpasero , seems the backup service is causing the issue here

**Comment by bpasero** [comment] 2021-08-24 06:27
I would say this is a duplicate of https://github.com/microsoft/vscode/issues/130634 which only now I fixed, so you can try it out in todays insider build.

Bottom line: we have some logic that when a file is changed and becomes dirty, will result in being opened in the editor area unless it is saved in a reasonable time (50ms currently). The rationale is that we don't want dirty files to linger around without the user seeing them. I speculate here in this case, saving took more than 50ms and as such we started to open thousands of editors at once which eventually brought down the application.

With my fixes, opening thousands of editors at once should be fast and shouldn't result in any crash, but would be good if you could test this with today's insider.

Nevertheless I might want to increase that 50ms delay because it seems too aggressive...

**Closed** 2021-08-31 11:29 UTC
Labels: needs more info, freeze-slow-crash-leak
