### ISSUE TITLE
Prefer local auto-imports over those from external modules

### ISSUE THREAD

**Issue by vitosamson** [Microsoft/vscode#42104] opened 2018-01-24 16:31 UTC
- VSCode Version: 1.19.2
- OS Version: Mac OS 10.11.1
- Typescript version: 2.6.2

autoImportSuggestions has some quirky behavior. The first is that it seems to prefer imports from global modules over local files. For example, if I have a file called `Context.ts` that exports an object called `Context`, and I try to auto-import that in another file, the first suggestion is to import it from the `vm` module. It would be nice if there was a way to specify priority of auto-imports.

Another minor quirk is that when I have a directory of files with an index file that re-exports things from the other files, auto-import will import it from `directory/index` rather than just `directory`. Sticking with the `Context` example from above, if my directory structure is:

  - server/
    - Context.ts
    - index.ts // re-exports Context

The automatic import will be `import { Context } from './server/index'`. I'd like to be able to specify that exports from an index file be imported from the directory (`import { Context } from './server'`).

Steps to Reproduce: see examples above

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-01-29 23:10
Can you please share your `tsconfig.json`? Also, please try this out on the latest VS Code insiders builds. We've made a number of fixes to auto-imports since VS Code 1.19

**Comment by vitosamson** [comment] 2018-01-30 01:43
tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "lib": ["es2017"],
    "outDir": "./build",
    "strict": true,
    "noUnusedLocals": true,
}
```

With latest Insiders build I'm still seeing the import suggestion for `Context` defaulting to the `vm` module rather than my project-specific definition. However when I select the correct suggestion it does properly import it from `./server/` rather than `./server/index`.

**Comment by mjbvz** [comment] 2018-02-02 07:15
Thanks. I've updated the issue title to reflect this

**Comment by mjbvz** [comment] 2019-03-22 01:12
I believe this was fixed at some point (possible a duplicate of https://github.com/Microsoft/TypeScript/issues/23598)

**Closed by mjbvz** 2019-03-22 01:12 UTC
Labels: feature-request, javascript
