### ISSUE TITLE
after updating to version 1.52.0，I can't tag breakpoint when debuging php script

### ISSUE THREAD

**Issue by fshch** [microsoft/vscode#112460] opened 2020-12-14 11:09 UTC
Issue Type: <b>Bug</b>

OS :  windows 10.0.18363.1082
installed wsl, vscode

php script in wsl (/home/username/work/...)
before update, PHP Debug worked well
but after updating to versiong 1.52.0, I can't tag breakpoint on opened php script; I am sure PHP Debug work well now, because when I set stopOnEntry to true in file launch.json, it is effective

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (10.97GB free)|
|Process Argv|--crash-reporter-id f617d409-5804-4224-a768-a0887b1d6762|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|Memory (System)|1.94GB (1.33GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.52.0
vscode-intelephense-client|bme|1.5.4
gitlens|eam|11.0.6
php-debug|fel|1.13.0
rest-client|hum|0.24.4
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
vetur|oct|0.31.3
polacode|pnp|0.3.4

</details>

**Comment by gjsjohnmurray** [comment] 2020-12-14 11:21
/duplicate of #112288 which suggests a workaround

**Closed** 2020-12-14 11:22 UTC
Labels: *duplicate, new release
