### ISSUE TITLE
Why the dark+ theme's syntax is different from the light+ theme's syntax?

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#48889] opened 2018-04-28 14:15 UTC
Why the dark+ theme's syntax is different from the light+ theme's syntax?
![dark](https://user-images.githubusercontent.com/24318019/39397406-613edaba-4b31-11e8-9f1c-4f8879e886a1.png)
![light](https://user-images.githubusercontent.com/24318019/39397411-6977cd68-4b31-11e8-82e3-be6e08a74288.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|7.89GB (1.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|2.7.0
markdown-preview-github-styles|bie|0.1.2
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
vsc-material-theme|Equ|2.0.1
debugger-for-chrome|msj|4.3.0
advanced-new-file|pat|1.2.0
vscode-icons|rob|7.23.0

</details>

**Comment by mjbvz** [comment] 2018-04-29 00:38
Duplicate of #48638

**Closed by mjbvz** 2018-04-29 00:38 UTC
Labels: themes
