### ISSUE TITLE
Terminal run selection using powershell should run selection as a block, not as individual lines

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#9715] opened 2016-07-25 18:53 UTC
When running text selection in the integrated terminal, when it finishes and goes back to the prompt it is adding a new line. You have to backspace back up. 

Before

``` powershell
PS C:\>
```

After

``` powershell
PS C:\>
>>
```
- VSCode Version: 1.4.0-insiders 7/25, but has been around for several builds
- OS Version: Windows 10

Steps to Reproduce:
1. run selection in terminal on windows
2.

**Comment by Tyriar** [comment] 2016-07-26 02:54
The code is meant to run the selection and add an `os.EOL` if it doesn't end in one. Do you see any reason why Powershell would behave differently with this?

/cc @chrmarti

**Comment by himanshub16** [comment] 2016-07-26 05:20
I have similar issue. Pressing backspace adds a new line to the integrated terminal.
OS : Debian Stretch
VSCode : 1.3.1

**Comment by chrmarti** [comment] 2016-07-26 17:06
@gerane Could you share the command you are running where this reproduces? Or is this with any command? (I couldn't reproduce so far.)

@himanshub16 That sounds like a separate problem, could you open a new issue for that if it persists? Thanks.

**Comment by gerane** [comment] 2016-08-04 15:14
@chrisbenti it is every command. It runs each line individually unless in curly braces, which means I can't actually use it.

For example, this is what is in my editor atm and just encountered this as we speak.

```powershell
$Combined = $JunkDomains + $Blocked | sort -unique
$NewBlocked = @()
foreach ($Item in $Combined) 
{ 
    if ($Ignored -notcontains $Item) 
    {
        $NewBlocked += $Item
    } 
}
```

and the output of using run selection

```powershell                                                                                                                                                            
PS C:\> $Combined = $JunkDomains + $Blocked | sort -unique                                                                                                                                     
>>                                                                                                                                                                                                                                                                                                                                                                
PS C:\> $NewBlocked = @()                                                                                                                                                                      
>>                                                                                                                                                                                             
PS C:\> foreach ($Item in $Combined)                                                                                                                                                           
>>                                                                                                                                                                                             
At line:1 char:29                                                                                                                                                                              
+ foreach ($Item in $Combined)                                                                                                                                                                 
+                             ~                                                                                                                                                                
Missing statement body in foreach loop.                                                                                                                                                        
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException                                                                                                          
    + FullyQualifiedErrorId : MissingForeachStatement                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                              
PS C:\>                                                                                                                                                                                        
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
PS C:\> {                                                                                                                                                                                      
>>     if ($Ignored -notcontains $Item)                                                                                                                                                        
>>     {                                                                                                                                                                                       
>>         $NewBlocked += $Item                                                                                                                                                                
>>     }                                                                                                                                                                                       
>> }                                                                                                                                                                                           
>>                                                                                                                                                                                             
>>                                                                                                                                                                                             
>>                                                                                                                                                                                             
>>                                                                                                                                                                                             
>>                                                                                                                                                                                             
>>                                                                                                                                                                                             
                                                                                                                                                                                               
    if ($Ignored -notcontains $Item)                                                                                                                                                           
    {                                                                                                                                                                                          
        $NewBlocked += $Item                                                                                                                                                                   
    }                                                                                                                                                                                          
                                                                                                                                                                                               
PS C:\>      
```

The output is incredibly odd. I selected exactly the text above, no added lines or spaces when I ran selection. This also occurs if I run powershell with -NoProfile so its not something from my profile.

**Comment by Tyriar** [comment] 2016-08-12 16:05
OK so I think I know what is happening here. The block of text is not send to the terminal, instead each character is send, meaning that each line is evaluated unless Powershell thinks it's a multi-line statement. That's why `foreach` is getting evaluated and `{` is waiting until it's closed. If you can put { at the end of the `foreach` I expect it to work.

This is how I would expect this to work for bash. So I suspect you want to run the selection as a since block, which would mean maybe wrapping it in some Powershell exec command. Perhaps [`iex`](http://stackoverflow.com/a/6338047/1156119)?

Let me know if this makes sense, going to open this up for PRs/help if so. 

The function that this would need to be handled in is https://github.com/Microsoft/vscode/blob/7f15980aaa768b05e10f09bc42dbb29a22c8b7dc/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L120. There's an issue with this though in that it would need to confirm that powershell is in the active terminal instance/process which may be difficult to determine for the same reason the title of the terminal switcher dropdown doesn't change on Windows. As such maybe it can only work when the shell is explicitly set to powershell (meaning it wouldn't work in cmd shells that launch powershell or powershell wrapped in a script).

**Comment by Tyriar** [comment] 2016-08-12 16:19
Alternatively due to the issues with detecting the shell on Windows, maybe this is better left to the powershell extension once https://github.com/Microsoft/vscode/issues/9957 is implemented and it integrates with the terminal?

**Comment by gerane** [comment] 2016-09-19 16:31
@Tyriar this would move back to using f8 for run selection similar to how it runs now, but in the open terminal correct?

**Comment by Tyriar** [comment] 2016-09-19 17:55
<kbd>F8</kbd> looks like it's bound to `editor.action.marker.next`?

**Comment by gerane** [comment] 2016-10-13 14:26
@Tyriar the powershell extension sets f8 to run selection.

I wanted to update after trying @daviwil sort of beta version of the powershell extension that integrates into the terminal. It appears some of the odd run selection behavior is being caused by the built in PowerShell module called PSReadline. Since PowerShell v4 it is auto loaded at Powershell startup in consoles. It is what provides many of the highlighting and and keyboard shortcuts that give a much improved PowerShell experience.

In the PowerShell Extension David is having to remove the PSReadline module because it is interfering with how he is having to communicate with the terminal. I believe this is temporary and he is looking into a solution for this, but when testing this I tested the Run Selection to see if it impacted anything. Many of the issues went away, but there were still a few present. Mainly with added lines at the end and I think if there was a space between 2 code blocks it would run those as 2 different entries. 

It got me thinking that maybe PSReadline could be causing some other issues, and was wanting to bring it up and maybe see if we can figure out what is going on and see if there is a way we can improve this.

**Comment by gerane** [comment] 2016-10-13 17:06
This is likely also impacted by PSReadline #7077

**Comment by Tyriar** [comment] 2016-10-13 19:42
I always assumed that the issues like this were related to the fact that [pty.js](https://github.com/Tyriar/pty.js) that vscode uses to communicate with the terminal process has a dated version of [winpty](https://github.com/rprichard/winpty) of which the support for powershell is limited.

**Comment by Tyriar** [comment] 2017-04-20 18:40
Closing this as the situation has changed and the PowerShell experience is owned by https://github.com/PowerShell/vscode-powershell

**Closed by Tyriar** 2017-04-20 18:40 UTC
Labels: feature-request, integrated-terminal, windows
