### ISSUE TITLE
Activity bar : Explorer tab active border has wried behaviour when no folder (or workspace ?) opened

### ISSUE THREAD

**Issue by Guema** [microsoft/vscode#84276] opened 2019-11-08 15:09 UTC
- VSCode Version: 1.40
- OS Version: Windows 10

Steps to Reproduce:

1. Open vscode
2. Close any folder/workspace
3. Test switching between Explorer tab and other tabs

Does this issue occur when all extensions are disabled?: Yes

![demo](https://user-images.githubusercontent.com/8943532/68486571-a144ec80-0241-11ea-89a5-da5084f73b2d.gif)

Has the gif show it, when clicking on explorer tab, the active tab border do not trigger.
Then, a wreid blue border appears after some seconds.
Finally, when unfocused, the tab show its active border normally.

I reported this as bug because i could not reproduce it on other tabs. I cannot reproduce when a folder is open either.

**Comment by misolori** [comment] 2019-11-08 16:55
Duplicate of https://github.com/microsoft/vscode/issues/83483

**Closed by misolori** 2019-11-08 16:55 UTC
