### ISSUE TITLE
Rename to invalid syntax should be prevented

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#50259] opened 2018-05-22 05:44 UTC
- VSCode Version: 2.9.1-insiders
- OS Version: Win 10

Steps to Reproduce (in the context of a JavaScript/TypeScript file):

1. Create `function foo() {}`.
2. Rename `foo` to `foo()`. Now you have `function foo()() {}`.
3. Rename `foo` to `.`. Now you have `function .()() {}`.

Does this issue occur when all extensions are disabled?: Yes

---

IMHO it would be nice, if step `2` and `3` wouldn't be possible, because both result in invalid syntax.

**Comment by mjbvz** [comment] 2018-05-22 17:45
Duplicate of #45384

**Closed by mjbvz** 2018-05-22 17:45 UTC
Labels: feature-request, javascript
