### ISSUE TITLE
Text changes for completion CodeAction are affected by the completion

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#39893] opened 2017-12-07 20:48 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (cd906f8af43a928b3c1060be820841538052a202, 2017-12-07T06:14:22.977Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Create `b.ts` containing:
```ts
export const foo = 0;
export const bar = 1;
```
2. Create `a.ts` containing:
```ts
; import { foo } from "./b";
```
3. Go to the start of the line, type `ba`, and accept the completion.
4. You get `bar; import { fo, baro } from "./b";`
(expected `bar; import { foo, bar } from "./b";`)

@mjbvz We were talking about this at the meeting today.

**Comment by mjbvz** [comment] 2017-12-08 22:10
@jrieken I switched the TS auto import completions to use `additionalTextEdits` but still see this issue. Here's the text changes we get from TS:

```
[Trace  - 2:07:10 PM] Response received: completionEntryDetails (47). Request took 7 ms. Success: true 
Result: [
    {
       ...
        "codeActions": [
            {
                "description": "Add 'bar' to existing import declaration from \"./b\".",
                "changes": [
                    {
                        "fileName": "/Users/matb/projects/san/a.ts",
                        "textChanges": [
                            {
                                "start": {
                                    "line": 1,
                                    "offset": 17
                                },
                                "end": {
                                    "line": 1,
                                    "offset": 17
                                },
                                "newText": ", bar"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]
```

We could try applying all the changes with `additionalTextEdits` or shifting down the TS text edits. Any suggestions?

**Comment by jrieken** [comment] 2017-12-11 08:33
The problem is that the main edit runs via the snippet controller and the rest as normal text edits. When both occur on the same line no adjustment happens...

**Comment by jrieken** [comment] 2017-12-11 09:37
@mjbvz The behaviour is kind of expected when using the command for the additional edits... That's because we have no clue what's happening... I have added a unit test for the additional edits scenarios and it works for me. Did you try this by any chance after making the changes in https://github.com/Microsoft/vscode/pull/39944?

**Comment by mjbvz** [comment] 2017-12-13 00:19
@jrieken Yes as we discussed I tried using the additional text edits for the code change, but this created the wrong undo order.

Hey @andy-ms, can we look into adding something akin to [`vscode's insertText`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2790) to the TypeScript API? This would be a much easier way for us to handle https://github.com/Microsoft/TypeScript/pull/20547 imo.

**Comment by andy-ms** [comment] 2017-12-13 00:26
Sure, it would be easy to add. I was hoping to fix that without changing the API, but it sounds like editors care about the difference between what's the completion text and what's a non-completion-text text change.

**Comment by jrieken** [comment] 2017-12-13 09:49
> completion text and what's a non-completion-text text change.

@andy-ms We have that because the completion text can be a snippet for which we don't know how long it will become. It's also hard to predict when a snippets finishes the snippet. Having said that, when the completion edit isn't a snippet we might be able to merge them. But it depends on the shape of the edits. 

You compute all edits based on the same state, right? If they can be merged without adjusting offsets it's easy, e.g just inserting the main edit at the right array position.

**Comment by amcasey** [comment] 2017-12-13 19:04
As far as I can tell, it works correctly in VS.  I followed the repro steps above and got `import { foo, bar }`.

**Comment by amcasey** [comment] 2017-12-13 19:06
Looks like we turn the completion into a change as well and then sort them so that they won't interfere with each other: `var sortedTextChanges = actionTextChanges.Concat(new[] { completionTextChange }).OrderBy(textChange => textChange.Span.Start);`

**Comment by mjbvz** [comment] 2018-01-09 19:05
Moving to backlog as we now have a workaround for the TS bracket completion issue

**Closed** 2018-09-18 21:53 UTC
Labels: *out-of-scope, bug, suggest, typescript
