### ISSUE TITLE
when I write style property in html tag ,I can't see prompt

### ISSUE THREAD

**Issue by Ben07** [Microsoft/vscode#24498] opened 2017-04-11 09:25 UTC
- VSCode Version:1.11.1
- OS Version:win 10

Steps to Reproduce:

1. when I type `<p style="wid">xxxholic</p>` in html file,I can't see `width` in prompt,how could I see it?
In previous version,the tips shown by default.

**Comment by jrieken** [comment] 2017-04-11 12:02
dupe of #24464

**Closed by jrieken** 2017-04-11 12:02 UTC
