### ISSUE TITLE
When switching between 2 files, position continually shifts down

### ISSUE THREAD

**Issue by greay** [Microsoft/vscode#12294] opened 2016-09-20 01:13 UTC
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. have at least 2 files open (C#) in a project
2. switch to the other file, and then back
3. each time you do this, the file position will shift down one or more lines when the # references appear

**Comment by alexandrudima** [comment] 2017-03-02 10:17
Caused by the code lenses, whenever they appear we try to keep the centered line in the viewport centered, but when restoring the view state we restore the scrollTop, not the centered line in the viewport...

**Comment by alexandrudima** [comment] 2018-04-09 11:56
Fixed via #41968

**Closed by alexandrudima** 2018-04-09 11:56 UTC
Labels: bug, editor-contrib
