### ISSUE TITLE
font look compressed in editor on Kubuntu 17.04

### ISSUE THREAD

**Issue by uravnitel** [Microsoft/vscode#42113] opened 2018-01-24 18:38 UTC
- VSCode Version:1.19 
- OS Version:Kubuntu x64 17.04 

Steps to Reproduce:

 font look compressed in editor

 
![screenshot_20180125_002238](https://user-images.githubusercontent.com/13073820/35349983-b2a26440-0166-11e8-9112-8c614e68933b.png)
![screenshot_20180117_195756](https://user-images.githubusercontent.com/13073820/35349995-bdfb124c-0166-11e8-8ca2-715156fa7cc5.png)

 I changed the font settings 
"editor.fontFamily":  

code --disable-gpu
code --force-device-scale-factor=1
reinstall visual code , install with .dep and console 
did not help

on sublime font look fine

![screenshot_20180125_003137](https://user-images.githubusercontent.com/13073820/35350338-cf82f1c8-0167-11e8-8dd8-0567ae148390.png)
 
please help

Does this issue occur when all extensions are disabled?: Yes

**Comment by uravnitel** [comment] 2018-01-24 21:15
"editor.fontFamily": "'Ubuntu Mono', 
change to monospace Droid Sans , segoi iu ..
did not help

menu font like fine

![screenshot_20180125_031311](https://user-images.githubusercontent.com/13073820/35357436-b6cd0626-017d-11e8-9d97-07fbae6957fe.png)

**Comment by alexandrudima** [comment] 2018-01-26 08:19
Duplicate of #35675

**Closed by alexandrudima** 2018-01-26 08:19 UTC
Labels: editor-rendering, linux
