### ISSUE TITLE
How can I use my javascript snippet for jsx?

### ISSUE THREAD

**Issue by taoeer** [Microsoft/vscode#22939] opened 2017-03-21 07:19 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.2.4|
|EditorConfig|EditorConfig|0.3.4|
|path-autocomplete|ionutvmi|1.4.1|
|Go|lukehoban|0.6.55|
|sublime-keybindings|ms-vscode|2.0.1|
|vetur|octref|0.5.6|
|theme-tinaciousdesign|tinaciousdesign|0.2.4|
|Material-theme|zhuangtongfa|2.3.3|;

**Comment by rebornix** [comment] 2017-03-21 16:26
Dup of #20664

**Comment by mjbvz** [comment] 2017-03-21 19:54
Thanks @rebornix. Yes, without more information, this looks like a duplicate of #20664/#19954  See this comment for more details: https://github.com/Microsoft/vscode/issues/19954#issuecomment-277705088

**Closed by mjbvz** 2017-03-21 19:54 UTC
Labels: duplicate

**Comment by taoeer** [comment] 2017-03-22 00:53
thanks
