### ISSUE TITLE
package.json / scoped packages no autocomplete

### ISSUE THREAD

**Issue by bali182** [Microsoft/vscode#24350] opened 2017-04-09 07:35 UTC
- VSCode Version: 1.11.1
- OS Version: Win 10

Steps to Reproduce:

1. Open a `package.json file`
2. Go to section `dependencies` / `devDependencies` / `peerDependencies` / `optionalDependencies`
3. As the package name key, start typing any scoped package that starts with `@` like `@types/minimatch`
4. There is no autocomplete.

It seems like this url, that is being used [here](https://github.com/Microsoft/vscode/blob/cc8df7305bebe1559ac0a2af270bdf2daf518185/extensions/javascript/src/features/packageJSONContribution.ts#L54) does return 0 result when search term starts with an `@`:

https://skimdb.npmjs.com/registry/_design/app/_view/browseAll?group_level=1&limit=50&start_key=["@"]&end_key=["@z",{}].

I'm using the same query in autocomplete-json for atom, and have been having the same issue https://github.com/bali182/autocomplete-json/issues/65 . Now npm doesn't seem to have too much docs on how to query their rest api, do you guys have any idea how to fix this?

**Comment by chrmarti** [comment] 2017-04-10 04:37
Related to #24321.

**Comment by aeschli** [comment] 2017-04-10 08:56
Looks like there's no support for querying scopes yet: https://github.com/npm/npm/issues/8244

Marking as duplicate of #24321.

**Closed by aeschli** 2017-04-10 08:56 UTC
