### ISSUE TITLE
Expanding a node in find references peek view removes focus from the list

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67248] opened 2019-01-28 15:31 UTC
Before:

![image](https://user-images.githubusercontent.com/2193314/51846578-b4985400-22ce-11e9-8457-2aa18d75e076.png)

After pressing right:

![image](https://user-images.githubusercontent.com/2193314/51846594-bcf08f00-22ce-11e9-99c0-664c21b180d0.png)

Version: 1.31.0-insider (user setup)
Commit: 1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c
Date: 2019-01-28T06:21:00.148Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18323

**Comment by joaomoreno** [comment] 2019-01-28 15:41
Dupe of something else I fixed today, can you check dev?

**Closed by joaomoreno** 2019-01-28 15:41 UTC
Labels: bug, important
