### ISSUE TITLE
Windows remote integration tests crash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#192857] opened 2023-09-12 09:39 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=231540&view=artifacts&pathAsName=false&type=publishedArtifacts

[f9d2ddab-06ef-4936-a9ca-fb864b020a8b.dmp.zip](https://github.com/microsoft/vscode/files/12584867/f9d2ddab-06ef-4936-a9ca-fb864b020a8b.dmp.zip)

**Comment by rzhao271** [comment] 2023-09-14 16:11
Symbolicated 

[symbolicated-f9.log](https://github.com/microsoft/vscode/files/12611110/symbolicated-f9.log)

**Comment by rzhao271** [comment] 2023-09-14 16:12
Potential duplicate of #192119

**Comment by deepak1556** [comment] 2023-09-14 23:35
Merging to https://github.com/microsoft/vscode/issues/192119

**Closed by deepak1556** 2023-09-14 23:35 UTC
Labels: freeze-slow-crash-leak, integration-test-failure
