### ISSUE TITLE
[v1.48] Proxy modal window not working and application is stuck

### ISSUE THREAD

**Issue by jayBana** [microsoft/vscode#104930] opened 2020-08-18 13:17 UTC
Reporting the same issue reported for v1.45 in [Proxy modal window not working and application is stuck #97719](https://github.com/microsoft/vscode/issues/97719) appearing again. This issue was fixed, but it seems to have been reintroduced again in the latest version.

VSCode Version: 1.48 latest
OS Version: Mac OS Catalina
Steps to Reproduce:

Behind a proxy wall, open the application
VS Code automatically prompt the Proxy credentials entry modal
After entering the credentials, clicking on "OK" or
"Cancel" does not do anything
Does this issue occur when all extensions are disabled?: Yes/No: NA, Does not allow me to disable extensions. Proxy window opens immediately

One thing I noticed, in the 1.47.3 version, the proxy address would appear on top of the modal for reference. I don't see that in the new version.

![image](https://user-images.githubusercontent.com/3785602/90517396-3e339f00-e15d-11ea-8972-7490033b8beb.png)

**Comment by gjsjohnmurray** [comment] 2020-08-18 14:22
/duplicate of #104603 and will be fixed in upcoming recovery release.

**Closed** 2020-08-18 14:23 UTC
Labels: *duplicate
