### ISSUE TITLE
[serve-web] Github Signup Link uses different host than one provided in CLI, breaking sign-in flow

### ISSUE THREAD

**Issue by thekeith** [microsoft/vscode#191866] opened 2023-08-31 02:07 UTC
Summary:

* As per comment in #168492, attempting to set a host that is different than 127.0.0.1 does not change the host for in-app github sign-in, breaking the sign-in flow on local networks. * * Furthermore, if I do not set a host at startup and connect to VSCode at say ```http://localhost:8000``` it does not reflect the named host, breaking the sign-in flow in a number of SSH clients (not will forward localhost *and* 127.0.0.1 at the same time).

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders 1.82.0
- OS Version: Mac OS 13.3

Steps to Reproduce:

1. Start serve-web with command ```code-insiders serve-web --host [any IP other than 127.0.0.1 such as 192.168.1.10]```
2. Open browser window and navigate to the URL given at startup (ex: ```http://192.168.1.10:8000```)
3. Click "sign in to Github" through the app (such as through turning on settings sync)
4. Note that the link hostname still uses 127.0.0.1

Expected behavior: The github sign-in link should have the same host that is set in --host and/or is in the browser session

**Comment by TylerLeonhardt** [comment] 2023-08-31 19:57
calling this a duplicate of https://github.com/microsoft/vscode/issues/191867 because it has the same fix. Don't use the local server flow in `serve-web` and instead use the device code flow.

**Closed by TylerLeonhardt** 2023-08-31 19:57 UTC
