### ISSUE TITLE
Allow to scope settings by platform 

### ISSUE THREAD

**Issue by ifufanuqa** [microsoft/vscode#207760] opened 2024-03-14 21:55 UTC
Hi

I develop on 3 different platform. When synchronizing settings, snippets and so on, i often must change path, adjust font-size, etc...

So, it could be great if we had a per platform settings set (Windows, Mac, Unix)

**Comment by rzhao271** [comment] 2024-03-14 22:54
Duplicate of #5595

**Closed by rzhao271** 2024-03-14 22:54 UTC
