### ISSUE TITLE
Scrolling flickers after cell "reset"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119599] opened 2021-03-23 13:44 UTC
Testing #119367

* open GH issue notebook, e.g `.vscode/notebooks/endgame.github-issues`
* open the same notebook in another instance of vscode (I usually have `.vscode/notebooks/` open separately)
* in the second window run a cell, like "Verification Needed", expand its items, scroll down
* in the first window clear output
* in the second window scroll up
* cells flicker (move up/down) while scrolling

https://user-images.githubusercontent.com/1794099/112156145-4289d400-8be6-11eb-9ab7-3383000e602b.mov

**Comment by mjbvz** [comment] 2021-04-02 22:56
I believe I see this in a single workspace too:

-  Run all cells in `api` notebook
- Scroll down so that last output is partially off the top of the screen
- Now clear outputs
- Scroll up again slowly
- 🐛 There's a flicker where cells shift around

The root causes seems to be that after clear we send the wrong scroll tops.

Here's directly after running `clear` (cell_id, cellTop):

![Screen Shot 2021-04-02 at 3 55 33 PM](https://user-images.githubusercontent.com/12821956/113459927-de2bf900-93cb-11eb-9f1e-96599b04f7d5.png)

And then after scrolling up:

![Screen Shot 2021-04-02 at 3 55 54 PM](https://user-images.githubusercontent.com/12821956/113459945-ea17bb00-93cb-11eb-8772-c0bb4ba754b0.png)


You see the first cell's in the list ends up shifting upwards to its correct position

**Comment by rebornix** [comment] 2021-04-12 21:00
Pushed a fix but won't close this until we have a fix for https://github.com/microsoft/vscode/issues/121140 .

**Comment by rebornix** [comment] 2021-04-14 17:56
The flicker is now fixed, however due to the fact that markdown cells are rendered in the webview and in a split second, the `scrollHeight` of the list view is updated (as the cell shrinks) but the cell/output's offset in the webview is not updated yet, you can see the markdown cell being pushed (visually) in a split second. I reopened https://github.com/microsoft/vscode/issues/120384 which tracks the idea of having a view layout info inside the webview.

**Closed by rebornix** 2021-04-14 17:56 UTC
Labels: bug, notebook-markdown
