### ISSUE TITLE
Support `alt+up` and `alt+down` to navigate SCM input history

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109437] opened 2020-10-27 04:38 UTC
Testing #109428

Related to my comment here: https://github.com/microsoft/vscode/issues/109435#issue-730091878
>  We should also support `alt+up` and `alt+down` to immediately trigger history navigation regardless of cursor position (search does this today)

**Comment by jvesouza** [comment] 2020-10-27 10:36
Would it be possible to implement an option to disable navigation in the history using the arrows?
From the point of view of accessibility, this option for me would be very useful. I would use the arrows to browse what is being edited and use alt + up / down to browse the history.

**Comment by meganrogge** [comment] 2020-10-27 21:02
duplicate of #109435, use Ctrl/Cmd and the arrows to go up and down regardless of where the cursor is

**Closed by meganrogge** 2020-10-27 21:02 UTC
Labels: feature-request, scm

**Comment by JacksonKearl** [comment] 2020-10-27 23:52
@meganrogge please aadd a feature request verification label or remove from milestone so this doesn't show up in [query](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22October+2020%22+label%3Afeature-request+-label%3Averification-needed+-label%3Aon-testplan+-label%3Averified+-label%3A*duplicate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+repo%3Amicrosoft%2Fvscode-js-debug)

**Comment by joaomoreno** [comment] 2020-10-28 09:17
@meganrogge I think you mean <kbd>Alt</kbd>
