### ISSUE TITLE
VS Code should support custom extension marketplaces/URLs

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#28191] opened 2017-06-07 16:54 UTC
- VSCode Version:

Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Steps to Reproduce:

My company has substantial internal tools, languages, etc. It'd be nice if we could have a company internal marketplace to publish such extensions on, similar to Sublime Text's Package Control supporting multiple extension repositories.

**Comment by mjbvz** [comment] 2017-06-07 17:35
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/21839

Thanks

**Closed by mjbvz** 2017-06-07 17:35 UTC
Labels: duplicate, extensions
