### ISSUE TITLE
I just updated vscode. I think it introduced an error in the terminal. When I resize the side bar the terminal goes crazy and there is one point in the terminal when the cursor goes to the next line while typing something

### ISSUE THREAD

**Issue by kpatel1989** [Microsoft/vscode#28534] opened 2017-06-12 14:37 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quick-open-file|AlanWalk|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|seito-openfile|Fr43nk|1.2.5|
|JSDocTagComplete|HookyQR|0.0.2|
|react-jest-vscode-snippets|jalisimo|0.0.3|
|vscode-jest|Orta|2.2.0|
|highlight-words|rsbondi|0.0.5|
|edit-locations-history|sadesyllas|0.2.5|
|vscode-terminal-here|Tyriar|0.0.5|
|local-history|xyz|1.2.1|;

---

Steps to Reproduce:

1. open terminal type some commands
2. resize the terminal
3. long list of command executes.

**Comment by ramya-rao-a** [comment] 2017-06-12 17:34
@kpatel1989 Can you provide a gif or video?

**Comment by Tyriar** [comment] 2017-06-12 18:13
May be duplicate of https://github.com/Microsoft/vscode/issues/28138?

**Closed** 2017-06-19 19:08 UTC
Labels: integrated-terminal, needs more info
