### ISSUE TITLE
my issue not resolved but closed

### ISSUE THREAD

**Issue by HeavenSky** [microsoft/vscode#94753] opened 2020-04-09 05:49 UTC
https://github.com/microsoft/vscode/issues/94424#issue-593731807
`'${workspaceFolder}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.`

this issue is close but the closer neither resolve nor give an available way. 
And now the release version also has this issue, 
so can anyone give me one way to goback OK version?

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment] 2020-04-09 09:27
cc @isidorn

**Comment by gjsjohnmurray** [comment] 2020-04-09 09:33
@HeavenSky you can download prevous versions via their release notes page. Start at https://code.visualstudio.com/updates and choose the one you want, e.g.

![image](https://user-images.githubusercontent.com/6726799/78880554-7d364300-7a4d-11ea-9223-9db7582d6da0.png)

**Comment by jeanp413** [comment] 2020-04-10 13:46
duplicate of #94725

**Closed** 2020-04-10 13:49 UTC
Labels: *duplicate, variable-resolving

**Comment by isidorn** [comment] 2020-04-10 14:24
@HeavenSky I appologise for not responding sooner, your steps were not clear to me. Now we are looking into a fix for this. Thanks!

**Comment by CDoughty08** [comment] 2020-04-15 22:19
Is there an open issue for this to track? Having the same problem.

**Comment by isidorn** [comment] 2020-04-16 06:43
https://github.com/microsoft/vscode/issues/94725
