### ISSUE TITLE
安装了中文语言包，但仍然是英文界面

### ISSUE THREAD

**Issue by xu-alex** [microsoft/vscode#92979] opened 2020-03-19 01:31 UTC
从昨天开始，我两台电脑上的vscode都变成了英文界面，我已经安装了简体中文语言包，并且ctrl shift p中界面显示语言也是中文。

Since yesterday, the vscode on my two computers has become an English interface. I have installed the simplified Chinese language pack, and the interface display language in ctrl shift p is also Chinese.

**Comment by tfx2001** [comment] 2020-03-19 02:13
I also have this problem, but the problem was fixed after upgrading to version 1.43.1.

**Comment by flasco** [comment] 2020-03-19 02:19
press `cmd + shift + p`, and input `configure display language`, and then select `zh-cn`, after restart, it will take effect.

**Comment by xu-alex** [comment] 2020-03-19 02:20
> I also have this problem, but the problem was fixed after upgrading to version 1.43.1.



> 
> 
> I also have this problem, but the problem was fixed after upgrading to version 1.43.1.
谢谢 手动更新到1.43.1后 就没这个问题了

**Comment by xu-alex** [comment] 2020-03-19 02:21
> 
> 
> press `cmd + shift + p`, and input `configure display language`, and then select `zh-cn`, after restart, it will take effect.

尝试过 更改后再重启vscode 仍然是英文界面

**Comment by aeschli** [comment] 2020-03-19 16:07
Duplicate of https://github.com/microsoft/vscode/issues/92950

**Closed by aeschli** 2020-03-19 16:07 UTC
