### ISSUE TITLE
keyboard for replace is clashing with keyboard shortcut for skip replacing

### ISSUE THREAD

**Issue by derekriemer** [microsoft/vscode#199880] opened 2023-12-03 06:45 UTC
Type: <b>Bug</b>

1. Open ctrl+h
2. Type "it's"
3. Try both skipping and replacing with your keyboard.

expected: enter is not the shortcut both used on the replace button and the next button.

actual: The next button says iits shortcut is enter, while the replace button does likewise.

VS Code version: Code - Insiders 1.85.0-insider (94a3d7bac770b43ce97e9685715bef1a60d1a759, 2023-12-01T19:00:37.339Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (5.57GB free)|
|Process Argv|C:\\Users\\driem\\mydrive\\vscode\\derekriemer.com.code-workspace --crash-reporter-id 28ba6424-1533-4280-b47a-bdf8edaf453d|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.139.0
copilot-chat|Git|0.10.2
isort|ms-|2023.11.13191009
python|ms-|2023.21.13351006
vscode-pylance|ms-|2023.11.102
jupyter|ms-|2023.11.1003351000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.81.8
vscode-yaml|red|1.14.0
svelte-vscode|sve|108.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
2i9eh265:30646982
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialogc:30812479
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by amunger** [comment] 2023-12-14 18:01
duplicate of https://github.com/microsoft/vscode/issues/188716

**Closed by amunger** 2023-12-14 18:01 UTC
Labels: bug, editor-find
