### ISSUE TITLE
Can't open terminal

### ISSUE THREAD

**Issue by mourapj** [microsoft/vscode#109927] opened 2020-11-03 17:28 UTC
Issue Type: <b>Feature Request</b>

"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" failed to launch (exit code: 4294901760).

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

**Comment by eamodio** [comment] 2020-11-03 22:52
Duplicate of #109342

**Closed** 2020-11-03 22:54 UTC
Labels: *duplicate
