### ISSUE TITLE
Tree: Cannot expand folder while performing multiselect

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42566] opened 2018-01-30 22:47 UTC
#41473

### Issue Type
Bug

### Description

**Steps**
1. Begin a multi-select in the explorer.
1. Try to expand a folder to select an item inside of it

**Bug**
There doesn't seem to be a way to do this. I tried clicking on the folder arrow and shift clicking. 

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (8cac1acd97466afc75c663dc1626d8562a9a3f3d, 2018-01-30T17:29:05.837Z)
OS version: Windows_NT x64 10.0.17052

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (6 x 1896)|
|Memory (System)|31.93GB (24.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>
Reproduces without extensions

**Comment by isidorn** [comment] 2018-01-31 11:05
Somewhat a duplicate of https://github.com/Microsoft/vscode/issues/41527
Though this is more about the mouse, thus leaving it open

**Comment by isidorn** [comment] 2018-06-06 14:09
@joaomoreno For this I would need the tree to distuinish a click on the expando and a click on the element itself.
Optimally a click on the expando always expands / colapses the element, no matter if user is in a process of multi-selectng with shift

**Comment by joaomoreno** [comment] 2018-06-07 07:49
Yeah, merging with #49986

**Closed by joaomoreno** 2018-06-07 07:49 UTC
Labels: feature-request, file-explorer
