### ISSUE TITLE
Select all occurrences does is limited to 999 lines / selections

### ISSUE THREAD

**Issue by ddeath** [Microsoft/vscode#35311] opened 2017-09-28 11:31 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-91-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|0.0.8
vscode-eslint|dba|1.3.2
mjml-syntax|dig|0.0.1
githistory|don|0.2.3
phpcs|ika|0.7.0
cpptools|ms-|0.13.0
php-docblocker|nei|1.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. create new file
2. add 1600 lines containing this string: `28.09.2017    09:20:34`
3. select spaces at first line
4. press ctrl + shift + L
5. it select only first 999 lines instead of all of them

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-09-28 12:16
Duplicate of #5887

**Closed by alexandrudima** 2017-09-28 12:16 UTC
Labels: editor
