### ISSUE TITLE
Autocomplete / Peek Definition / Function signatures all broken

### ISSUE THREAD

**Issue by raffjones** [Microsoft/vscode#69563] opened 2019-02-27 23:03 UTC
I have searched for related issues and this is part of the problem - I don't know how to frame this one as a lot of things have broken at once.

VS Code has stopped working for my JavaScript environment. 

Previously I would have this at the top of an ES6 document:
`import * as THREE from 'three'` (where 'three' is an npm-installed library)

Then when I typed `THREE.` in the body of the code, it would make suggestions, including function signatures showing the arguments required. That has all stopped working. 

When I try "peek" on keywords, it just says "No definition found" regardless of what it is. It's making the editor very difficult to use. 

I didn't install any new extensions, and am seeing the above when I launch with `code --disable-extensions`.

**Comment by mjbvz** [comment] 2019-02-27 23:09
Which VS Code version and operating system are you using? 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by raffjones** [comment] 2019-02-27 23:55
Thanks for your reply.

Version: 1.31.1

It does not reproduce in the latest VS Code Insiders build (which I was only aware of following your reply). When I load the same ES6 class up in VS Code Insiders, the autocompletion, function signatures and hovering over symbols is all working perfectly.

**Comment by mjbvz** [comment] 2019-02-28 00:38
Ok, thanks for checking. I'm going to close this issue then since it works in insiders. If you don't want to use the insiders build,  try upgrading to VS Code 1.32 which should come out next week

**Closed by mjbvz** 2019-02-28 00:38 UTC
Labels: javascript, needs more info
