### ISSUE TITLE
I can't lanch the integrated terminal

### ISSUE THREAD

**Issue by hamzakalid** [microsoft/vscode#179664] opened 2023-04-11 07:02 UTC
Type: <b>Bug</b>

when i try to use the integrated terminal it close 
with this error [ The terminal process failed to launch: A native exception occurred during launch (Cannot launch conpty).]
I tried to fix it from vs setting but i can't

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.83GB free)|
|Process Argv|--crash-reporter-id cfe41d2d-1963-4bd3-ae04-347b762cddeb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (98)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
ng-template|Ang|15.2.0
vscode-apollo|apo|1.19.11
vscode-database|baj|2.2.3
vscode-node-readme|ben|3.0.2
vscode-intelephense-client|bme|1.9.5
bfc-vscode-snippets|Bot|0.0.2
vscode-tailwindcss|bra|0.9.11
npm-intellisense|chr|1.4.4
dart-code|Dar|3.62.0
flutter|Dar|3.62.0
vscode-markdownlint|Dav|0.49.0
jshint|dba|0.11.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|13.5.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.8.0
vsc-material-theme-icons|equ|2.7.4
prettier-vscode|esb|9.10.4
explaindev|exp|0.11.2
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
copilot|Git|1.79.10634
vscode-pull-request-github|Git|0.62.0
vscode-graphql|Gra|0.8.7
vscode-graphql-syntax|Gra|1.1.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
jquery-snippets|Hri|1.0.0
icon-fonts|idl|2.5.4
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
firebase-explorer|jsa|0.3.3
graphql-for-vscode|kum|1.15.3
sequelize-snippets|kvc|1.0.0
lorem-space|Man|0.1.4
theme-monokai-pro-vscode|mon|1.2.0
graphql|mqu|0.1.2
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azurecli|ms-|0.5.0
powershell|ms-|2023.3.3
vsliveshare|ms-|1.0.5834
debugger-for-chrome|msj|4.13.0
rose-pine|mvl|2.8.0
deepdark-material|Nim|3.3.0
angular-console|nrw|18.0.2
vetur|oct|0.37.3
laravel-blade|one|1.34.0
laravel5-snippets|one|1.17.0
bootstrap4code|oua|1.0.0
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.26.0
vscode-css-peek|pra|4.2.0
sqlite-viewer|qwt|0.2.3
vscode-thunder-client|ran|2.6.1
prolog|reb|0.0.4
java|red|1.16.0
vscode-xml|red|0.24.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
tabnine-vscode|Tab|3.6.44
ayu|tea|1.0.5
bootstrap4-vscode|the|6.1.0
vscode-readme-pattern|tho|1.3.0
linenote|tkr|1.2.1
vscode-dialog-debugger|tom|1.0.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.1
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.3.0
gitblame|wad|10.2.0
php-debug|xde|1.32.1
php-pack|xde|1.0.3
primengsnippets|yig|1.0.5
bootstrap-v4-snippets|Zac|1.1.3
lorem-picsum|Zaf|1.0.1
material-theme|zhu|3.15.8
php-intellisense|zob|1.1.2

(18 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30705553
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttextcf:30710682

```

</details>

**Comment by PythooonUser** [comment] 2023-04-11 08:06
Have you tried this without any of the 98 extensions running? My guess is that one of those is causing that issue?

**Comment by hamzakalid** [comment] 2023-04-11 08:27
I remove 30 extension.
 each one you think causing this issue

**Comment by PythooonUser** [comment] 2023-04-11 08:51
You can run `code --disable-extensions` for this.

**Comment by hamzakalid** [comment] 2023-04-11 08:55
still the same issue 🥲

**Comment by meganrogge** [comment] 2023-04-11 15:14
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-04-11 15:14 UTC
