### ISSUE TITLE
Artifacts in UI after Code is open for a little while

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#12292] opened 2016-09-20 00:41 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14915

Steps to Reproduce:

1. Sorry, no specific steps to repro

After having VS Code open for a while, editing multiple tabs, etc., sometimes the UI will become corrupted as in the following screenshot, and every action taken (moving the cursor, switching tabs, typing, resizing the window, etc.) causes the black squares and unrendered text in the window to move around).

The amount of time VS Code is open before corruption can occur, or number of tabs opened before corruption occurs seems random. I've seen this start when as few as 1 tab (or even a lot of tabs) are open, or if it has been running for as little as a couple minutes, up to many hours.

The only workaround seems to be to restart VS Code which is a pain especially because it doesn't have an automatic session restore like Notepad++ does.

I've been encountering this issue periodically since Insiders 1.3 or so but I've been trying to get some kind of reliable repro before reporting -- but I've been unable to do so, so I'm reporting it now.

![image](https://cloud.githubusercontent.com/assets/494055/18653633/009c6eda-7e90-11e6-8ad1-2e57646397ea.png)

**Comment by bpasero** [comment] 2016-09-20 08:31
@dilijev are you running inside a VM? does it reproduce with insiders build?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by dilijev** [comment] 2016-09-20 16:03
Not running in a VM. Running Windows 10.0.14915 on Desktop. 2 graphics cards (3rd monitor is on the second card), but this repros on the primary or secondary monitor on the first graphics card (I don't ever code actively on the third monitor).

It has repro'd in insiders (I first noticed it in Insiders 1.3), but I realize we're well beyond that. I switched away from insiders because restarting to update on a daily basis is disruptive without the automatic session restore.

I'll switch back to running insiders and see if I can get a repro.

I'll also see if I can repro on a computer with a more "normal" configuration - my laptop is running 14393 and my home desktop is running 10586, and both machines only have one graphics card - but I don't do that much coding at home.

Would getting an ETW trace after the corruption starts be helpful?

**Comment by bpasero** [comment] 2016-09-20 16:11
What will likely help is running with disabled GPU: `code --disable-gpu` even though that can bring overall slowness in the UI.

**Comment by dilijev** [comment] 2016-09-20 16:14
I guess it would be good to know if it repros with --disable-gpu, but it might just block getting a repro.

**Comment by bpasero** [comment] 2016-09-23 05:33
@dilijev running with `--force-gpu-rasterization` from command line should fix it. Closing as duplicate of https://github.com/Microsoft/vscode/issues/12473

**Closed by bpasero** 2016-09-23 05:33 UTC
Labels: bug, needs more info, upstream
