### ISSUE TITLE
Cursor Position changed after switching open file

### ISSUE THREAD

**Issue by corran2go** [Microsoft/vscode#26529] opened 2017-05-12 07:50 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-77-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.14.0|
|Angular2|johnpapa|2.2.3|
|dart|kevinplatel|0.1.0|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1. open at least two files and position the cursor on a specific line
2. switch editor by key-combination
3. move cursor => sometimes it jumps several lines beneath the original cursor position

This leads to wrong code after C&P actions.

**Comment by egamma** [comment] 2017-05-12 10:10
@corran2go can you reproduce this when you have all extensions disabled as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by corran2go** [comment] 2017-05-12 10:18
Yes, this also happens with all extensions disabled for the current workspace.

I switch between the editors with Ctrl-PageUp/PageDown and the cursor position changes somehow related to the code structure, as it happens consistently when the cursors is inside some substructure like function/if/else.

**Comment by Sensirex** [comment] 2017-05-15 05:27
This happens always when something folded, in my case,
after switching a tab(Ctrl-PageUp/PageDown or Ctrl-Tab)
Try move cursor (left, right, up or down)
and the cursor always moving at down of editor
and all extensions disabled

**Comment by alexandrudima** [comment] 2017-05-18 06:19
The cursor view position is not validated after the folding information is restored from the view state. Duplicate of #26251

**Closed by alexandrudima** 2017-05-18 06:19 UTC
