### ISSUE TITLE
UI render crash on macOS High Sierra

### ISSUE THREAD

**Issue by tonghuashuo** [Microsoft/vscode#35883] opened 2017-10-09 08:59 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (af6ca44db81f5186d3104226c8e76e026789ce20, 2017-10-06T07:50:45.639Z)
- OS Version: Darwin x64 17.0.0 (macOS 10.13 High Sierra, with Supplemental Update Oct. 9 2017)
- Extensions: the listing length exceeds browsers' URL characters limit
---

<img width="1920" alt="2017-10-09 2 26 25" src="https://user-images.githubusercontent.com/6594276/31331382-aa1a2d62-aca7-11e7-8450-925b6e8e087d.png">

Steps to Reproduce:

1. Launch VSCode (I'm using Insider version)
2. Do anything for a while (navigation / scrolling / ...)

Reproduces without extensions: Yes

- This issue only occurred after I upgrade to High Sierra last night. It worked fine on Sierra.
- This issue occurs occasionally, not always.
- Waiting for a while and it came back to normal. then it goes nut again. back and forth. (sometimes minimize and restore the window helps. maybe it triggers a re-render. but I think it's more like just luck)
- Rebooting the computer didn't solve the problem.
- Thought might be problem with electron. but ATOM behaves normal.
- I installed latest node & npm after upgrading. All my projects are working. So runtime should be fine.

This could be an individual case. I don't know if anyone else had the same problem. Hope there's a fix other than reinstalling the OS.

**Comment by demohi** [comment] 2017-10-09 09:25
VSCode Version: .17.0 (1.17.0)
OS Version: macOS 10.13 High Sierra 

terminal ui issue 

![image](https://user-images.githubusercontent.com/1209159/31331853-aa7634b6-aca9-11e7-933c-5b61826c7fb0.png)

**Comment by chrmarti** [comment] 2017-10-09 18:02
Duplicate of #35527

**Closed by chrmarti** 2017-10-09 18:02 UTC

**Comment by tonghuashuo** [comment] 2017-10-10 02:28
no no no. mine situation is not just the terminal display half character. I saw that issue before. the whole UI crash. I had the screenshot in the initial comment.

**Comment by tonghuashuo** [comment] 2017-10-10 02:50
Oh sorry. mis-understood your reference on 'duplication'. you are right.
