### ISSUE TITLE
终端无法输入中文

### ISSUE THREAD

**Issue by yangdachaun** [microsoft/vscode#116071] opened 2021-02-08 03:32 UTC
CPUs | Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: enabled rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.87GB (6.26GB free)
Process Argv | --crash-reporter-id 24ca4424-07cf-475f-9373-b3d1718b11ea
Screen Reader | no
VM | 0%

bracket-pair-colorizer | Coe | 1.0.61
-- | -- | --
auto-close-tag | for | 0.5.10
auto-rename-tag | for | 0.1.6
vscode-language-pack-zh-hans | MS- | 1.53.2
remote-ssh | ms- | 0.63.0
remote-ssh-edit | ms- | 0.63.0
material-icon-theme | PKi | 4.5.0
vuetify-vscode | vue | 0.2.0
path-intellisense | chr | 2.3.0
vue-peek | dar | 1.0.2
vscode-html-css | ecm | 1.9.1
prettier-vscode | esb | 5.9.1
auto-complete-tag | for | 0.1.0
prettify-json | moh | 0.0.3
vscode-language-pack-zh-hans | MS- | 1.53.2
vetur | oct | 0.32.0
vscode-javascript-booster | sbu | 14.0.1
markdown-all-in-one | yzh | 3.4.0
html-css-class-completion | Zig | 1.20.0

vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

**Comment by yume-chan** [comment] 2021-02-08 05:33
Duplicate of #115814

**Closed** 2021-02-08 10:50 UTC
Labels: *duplicate
