### ISSUE TITLE
JSON color decorators disappear when "semanticTokenColors" is present

### ISSUE THREAD

**Issue by BeefaloKing** [microsoft/vscode#137285] opened 2021-11-16 07:55 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version:

Make sure `editor.colorDecorators` is enabled in settings and open a vscode color-theme.json file. If the given theme exclusively specifies textmate scopes color decorators appear as expected, but if the key `"semanticTokenColors"` is present color decorators vanish.

![image](https://user-images.githubusercontent.com/9630438/141943066-d85463b3-9149-4454-a6bf-72e02d2dd99a.png)
![image](https://user-images.githubusercontent.com/9630438/141943240-e3f7d4f3-86bf-4f34-abf0-60a2b7ce5c90.png)

**Comment by aeschli** [comment] 2021-11-16 15:27
Duplicate of https://github.com/microsoft/vscode/issues/137166

Caused by https://github.com/microsoft/vscode/issues/137054

**Closed by aeschli** 2021-11-16 15:27 UTC
Labels: new release
