### ISSUE TITLE
Dragging files doesn't properly insert path

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#180836] opened 2023-04-25 15:29 UTC
Testing #180741

1. Open a workspace, with no custom drop providers registered
2. Drag and drop a file from the native file explorer
3. See an absolute path is inserted (not sure if this should be relative, I dragged a file that was not inside the workspace)
4. Drag and drop a file from the VS Code file explorer
5. 🐛 No path is inserted, appears nothing happened

**Comment by mjbvz** [comment] 2023-04-25 23:43
I can repo on parallels but it's unclear if this is a parallels issue or a Ubuntu specific issue. Seems to work fine on both Windows and Mac

**Comment by mjbvz** [comment] 2023-04-26 00:12
Closing as duplicate of #180837. There's something wrong with the `dragOver` event on parallels + ubuntu

**Closed by mjbvz** 2023-04-26 00:12 UTC
Labels: bug, linux
