### ISSUE TITLE
How to prevent CompletionItemProvider from being executed in strings and comments?

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#1108] opened 2015-12-08 18:37 UTC
I'm working on an extension and have a `CompletionItemProvider`. It works good when writing code. But it's annoying when it pops up suggestions inside of strings and comments. 
I don't want the suggestions to appear in that cases. 

I had a look at other extensions on how they solve this problem. The TypeScript plugin has got these lines:

    function TypeScriptCompletionItemProvider(client) {
        this.triggerCharacters = ['.'];
        this.excludeTokens = ['string', 'comment', 'numeric'];
        this.sortBy = [{ type: 'reference', partSeparator: '/' }];
        this.client = client;
        this.config = configuration_1.defaultConfiguration;
    }

I tried to define the `excludeTokens` in the same way but it doesn't work. How can I prevent the `CompletionItemProvider` from being executed in strings and comments?

**Comment by lukehoban** [comment] 2015-12-08 19:27
I think this is the same as https://github.com/Microsoft/vscode/issues/719?

**Comment by Wosi** [comment] 2015-12-08 22:02
@lukehoban Yes, you're right.

**Comment by egamma** [comment] 2015-12-09 07:51
yes, closing as a duplicate of #719

**Closed by egamma** 2015-12-09 07:51 UTC
