### ISSUE TITLE
Debug should resolve symbolic links for breakpoints

### ISSUE THREAD

**Issue by JoshuaFox** [microsoft/vscode#78443] opened 2019-08-04 07:12 UTC
A breakpoint works when set on the exact same line in one VS Code tab but not in another.

There seem to be two ways of opening a Javascript file, and if the full path appears in the tab, then breakpoints work.

But if the filename only appears in the tab header, then breakpoints all become Unverified (gray; disabled) during execution.

 
![image](https://user-images.githubusercontent.com/4542591/62420778-bb01f100-b6a0-11e9-9afe-87ef949a016a.png)

If you open using CTRL-P, then both variants are usually available.
![image](https://user-images.githubusercontent.com/4542591/62420750-43cc5d00-b6a0-11e9-8c17-38bfd00e9840.png)

VS Code 1.36.1, Node 8.16.0, running Mocha tests.

**Comment by IllusionMH** [comment] 2019-08-04 21:38
Looks like VSCode can't map your project files to files that are reported by node.

Do you have proper values for `runtimeArgs`, `cwd`, `outFiles` etc. for your scenario? 
https://github.com/Microsoft/vscode-recipes has recipes for different cases (including Mocha)

**Comment by JoshuaFox** [comment] 2019-08-05 06:43
Note also that the two variants of each file are treated separately in the debugger, as if they are different files. In this screenshot, each  breakpoint was set in the different variant, and as you see the first is disabled.
![image](https://user-images.githubusercontent.com/4542591/62444186-7d1ad080-b765-11e9-881e-de650bdaf300.png)

**Comment by JoshuaFox** [comment] 2019-08-05 06:45
>  VSCode can't map your project files to files that are reported by node.

Right, but sometimes it can, as described.

> runtimeArgs, cwd, outFiles

In `launch.json`,  `runtimeArgs` was OK. 
* `cwd` was not there, but adding the literal  path (or `${workspaceFolder}` makes no difference.
* As to `outFiles`, there is no transpilation, but in any case, adding the workspace folder as `outFiles` makes no difference.

`{    "version": "0.2.0",    "configurations": [        {            "type": "node",            "request": "launch",            "name": "Launch via NPM",            "runtimeExecutable": "npm",            "runtimeArgs": [                "run-script",                "debugTest"            ],            "port": 9229,            //makes no difference whether present our not            "cwd": "/full-path"        }           ]}`

**Comment by isidorn** [comment] 2019-08-05 09:39
Looks like a duplicate of https://github.com/microsoft/vscode/issues/12448
Assigning to @weinand and @bpasero to potentially close as duplicates

**Comment by JoshuaFox** [comment] 2019-08-05 10:11
I am using Ubuntu 18.04.2, so I guess it is not a matter of
case-insensitivity.

**Comment by IllusionMH** [comment] 2019-08-05 10:12
@isidorn not sure if this one is related to #12448

@JoshuaFox try use configurations from [recipe for mocha](https://github.com/microsoft/vscode-recipes/blob/master/debugging-mocha-tests/.vscode/launch.json) instead of launching npm script.

It still looks more like a question than actual issue with VSCode.

**Comment by JoshuaFox** [comment] 2019-08-05 11:57
I tried that Mocha recipe, and the tests run, but the same breakpoint
issue  occurs.

> than actual issue with VSCode.

Quite possibly. The puzzle is why this is happening.

**Comment by bpasero** [comment] 2019-08-05 13:23
It is easy to find out if this is https://github.com/microsoft/vscode/issues/12448 by going to each tab and copying the full absolute path (from the context menu) and then comparing the 2 paths for differences.

**Comment by JoshuaFox** [comment] 2019-08-05 18:18
You got it!

The two variants' full paths are

/home/joshua/hdd/more-dev/myworkspace/myfile.js
/hdd/more-dev/myworkspace/myfile.js

(I have a symbolic link from my home /home/joshua/hdd/ to target /hdd.)

When I open the workspace folder using  the link path (under  home), and
do CTRL-P to get a file, I see those two variants. Also, the Explorer gives
me the "buggy" variant.  .

The buggy variant is the one under the opened workspace folder (the link
path, under home)! On the other hand, the variant at the non-link path is
the one that  allows breakpoints!

Symbolic links are a normal feature of Unix and should be supported.

**Comment by isidorn** [comment] 2019-08-06 13:53
This sounds like a feature reuqest that we should resolve symbolic links for breakpoints. Which we do not do atm.

**Comment by JoshuaFox** [comment] 2019-08-06 14:30
A fix is not urgent for  me now.

But it seems to me that having a directory tree under a symbolic link is
quite ordinary in Linux, as is  opening a workspace inside such a tree.

In fact, I would expect applications to work with paths  as given, so I am
surprised that VS Code is going through the extra step of resolving
symbolic links, and using those  for its breakpoint path (which also
showing the path-as-given as a second variant).

**Comment by weinand** [comment] 2019-08-06 14:40
VS Code cannot provide symbolic link support for breakpoints b itself. It is the underlying runtime that has to support symbolic links.

In case of node.js you can enable this by adding a flag. 
See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks for details

And there is a discussion here: https://github.com/Microsoft/vscode/issues/57954.

/duplicate #57954

**Closed** 2019-08-06 14:40 UTC
Labels: *duplicate, debug, feature-request
