### ISSUE TITLE
"Alt Gr" (Alt ground) not working inside terminal

### ISSUE THREAD

**Issue by Moke-RS** [Microsoft/vscode#8681] opened 2016-07-02 18:57 UTC
- VSCode Version: 1.2.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Open the terminal inside VS Code
2. Try to write a letter that is only accessible using the "Alt Gr" keyboard button.

In my case, the "/" is under the "Q" in my notebook keyboard. When I tried to write "/" inside the terminal using the "Alt Gr", it was not possible. Out of the terminal I could write it without problem.

**Comment by Tyriar** [comment] 2016-07-03 05:43
Duplicate of https://github.com/Microsoft/vscode/issues/7061

**Closed by Tyriar** 2016-07-03 05:43 UTC
