### ISSUE TITLE
Terminal: link detection doesn't seem to work for relative paths?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#26696] opened 2017-05-15 22:50 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10

Not sure if it makes a difference but my terminal is Cygwin configured like this:

```json
"terminal.integrated.confirmOnExit": false,
"terminal.integrated.fontFamily": "Powerline Consolas",
"terminal.integrated.fontLigatures": true,
"terminal.integrated.shell.windows": "C:\\Cygwin64\\ZShell.bat",
```

```bat
@echo off

set CHERE_INVOKING=1

C:\Cygwin64\bin\zsh.exe --login --interactive
```

For instance, this doesn't work:

```
ERROR in [at-loader] ./app/Index.tsx:18:66
    TS1005: ')' expected.

ERROR in [at-loader] ./app/Index.tsx:18:1
    TS2345: Argument of type 'void | Element | Component<any, ComponentState>' is not assignable to parameter of type 'StrategyOverrides'.
  Type 'void' is not assignable to type 'StrategyOverrides'.
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  546 kB       0
webpack: Failed to compile.
webpack: Compiling...
```

`./app/Index.tsx:18:66` is not detected as linkable.

**Comment by Tyriar** [comment] 2017-05-19 20:23
It should work, however it's relative to the initial directory that the terminal was launched in, not the cwd. Let me know if you didn't change the directory.

**Comment by rfgamaral** [comment] 2017-05-20 09:32
@Tyriar How can I know for sure that was the initial directory that the terminal was launched in?

**Comment by Tyriar** [comment] 2017-05-22 02:56
@rfgamaral currently the terminal front end has no way of tracking what the current working directory is, so it can only do links based on the opened folder for VS Code. Unless you have some extension installed the folder the links are relative to should always be the folder opened in VS Code.

**Comment by rfgamaral** [comment] 2017-05-22 11:31
Then it should work because the opened folder in VS Code has an `app` folder in there. Not sure if it's affecting this somehow but I'm using this extension: https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager

**Comment by Tyriar** [comment] 2017-05-22 17:50
@rfgamaral could you include a screenshot showing the terminal and the explorer opened to that file?

**Comment by rfgamaral** [comment] 2017-05-23 08:18
Sure.

![image](https://cloud.githubusercontent.com/assets/96476/26344743/97b3db72-3f98-11e7-815e-1f57bc55e0b3.png)
![image](https://cloud.githubusercontent.com/assets/96476/26344802/c7b9f19e-3f98-11e7-86fc-2116cd902154.png)

**Comment by Tyriar** [comment] 2017-05-23 17:00
Hmm, can't repro.

![image](https://cloud.githubusercontent.com/assets/2193314/26366027/65b3b542-3f9e-11e7-813b-506dd14b9f06.png)

I wonder if it's related to the styling of the output? If different escape sequences are used to style the text then they will be in different spans and won't be linkified which is a known bug. Could you open devtools (Help > Toggle Developer Tools) and inspect the ./app/Index.tsx to see the form of the HTML?

This is what it should look like:

![image](https://cloud.githubusercontent.com/assets/2193314/26366087/9a9b6c50-3f9e-11e7-97fd-c41a4d1fe999.png)

**Comment by rfgamaral** [comment] 2017-05-23 18:27
It looks like this:

![image](https://cloud.githubusercontent.com/assets/96476/26369834/ca7688d4-3fed-11e7-9a88-4ab90f915c68.png)

**Comment by Tyriar** [comment] 2017-05-24 00:38
I suspect this is because this is winDrivePrefix, not winPathPrefix. Will look into it more when I'm in front of a Windows PC 😄  https://github.com/Microsoft/vscode/blob/921107cd124e9dcf18ac654875957815386ac94a/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L208

**Comment by Tyriar** [comment] 2017-06-23 19:36
I had another look at this, I believe it's actually due to the text color of the link making this a duplicate of https://github.com/Microsoft/vscode/issues/29072

**Closed by Tyriar** 2017-06-23 19:36 UTC
Labels: bug, integrated-terminal, windows
