### ISSUE TITLE
Closing the extension window being debugged didn't stop debugging

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122322] opened 2021-04-27 12:38 UTC
Testing #121763

Repro:

1. Open extension sample in insiders codespace/Safari (I used https://github.com/microsoft/vscode-extension-samples/tree/main/terminal-sample)
2. `npm ci`
3. F5
4. Press continue to open the new window
5. Close the window, debugging doesn't stop

**Comment by isidorn** [comment] 2021-04-27 15:08
This actually works just fine for me when I run locally via `resources/server/web.sh`
And when I run codespaces now with insiders I get a weird error so I can not try this with codespaces.
However assigning to @connor4312 since it sounds like the js-debug extension does not detect a tab going down in codespaces scenario. Or maybe the codespace workspace provider does not emit a correct event?

![Screenshot 2021-04-27 at 17 06 41](https://user-images.githubusercontent.com/1926584/116265053-15978680-a77b-11eb-9497-7d8b2cc9b51d.png)

**Comment by connor4312** [comment] 2021-04-27 21:35
I tried this out -- I ended up with duplicate ext host tabs but I also noticed that when I closed the windows, the extension hosts were not being torn down: https://memes.peet.io/img/aaeec40a-9cc4-4108-b712-9af0b3f6f988.mp4. So it looks like the problem is not in js-debug.

**Comment by isidorn** [comment] 2021-04-28 12:33
@bpasero how does codespaces notify VS Code that the window goes down? Is it though some web api?

**Comment by bpasero** [comment] 2021-04-28 13:13
@isidorn there is no API for it, we install a listener for the `unload` event:

https://github.com/microsoft/vscode/blob/ec972e8acc0f1f3853ec54994a69bafacf6fc844/src/vs/workbench/services/lifecycle/browser/lifecycleService.ts#L30-L30

Anything happening in that event needs to execute sync though, there is no support for long running ops.

**Comment by isidorn** [comment] 2021-08-12 13:42
Dup of https://github.com/microsoft/vscode/issues/124128

**Closed by isidorn** 2021-08-12 13:42 UTC
Labels: debug
