### ISSUE TITLE
Editor not showing text beyond column 10000 in long line

### ISSUE THREAD

**Issue by otolabqu** [microsoft/vscode#97707] opened 2020-05-13 11:52 UTC
Issue Type: <b>Bug</b>

I have a file with very long lines, like 18000 characters long. 

I'm searching for a string in this file and the editor tells me that I have 1 search hit for the string. But it does not scroll to the right to show the actual string. It does tell me the position (Ln 1, Col 14171)  and (23 selected) so it seems that it has actually found and selected the string. But it is not moving the editor to visually show that position, and there is no easy way for me to get there without manually scrolling, which is tedious. 

Expected behavior: When getting search hits, the editor should visually scroll to the part of the code where the hit occurs. It does for normal files and lines as far as I know. 

```
CPUs | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3000)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled

```

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:51:09.716Z)
OS version: Linux x64 5.0.0-38-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
python|ms-|2020.2.64397

</details>

**Comment by otolabqu** [comment] 2020-05-13 11:55
Update: I tried to manually scroll to the position and it turns out the editor is actually not able to scroll beyond column 10000. So that's probably the actual problem. I cannot manually see it either.

**Comment by otolabqu** [comment] 2020-05-13 11:56
Workaround: By moving to position 9999 and pressing "Enter" to add a newline, I can now find the string on the second line in the file, since the 8000 remaining characters are shown on line 2.

**Comment by alexdima** [comment] 2020-05-13 12:09
Duplicate of #7772

**Closed** 2020-05-13 12:09 UTC
