### ISSUE TITLE
Support D&D between staged changes and changes

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#183786] opened 2023-05-30 11:28 UTC
Testing #183587

Now that we have D&D would be cool to support that scenario as well.

**Comment by joyceerhl** [comment] 2023-12-07 17:53
I believe this requires implementing this method for when the `targetElement` is an SCM resource group https://github.com/microsoft/vscode/blob/cea7c824a5430f5fff7e474ed455308847a702c6/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L279-L280

**Comment by lszomoru** [comment] 2023-12-14 11:10
Closing as duplicate of https://github.com/microsoft/vscode/issues/152250.

**Closed by lszomoru** 2023-12-14 11:10 UTC
Labels: feature-request, scm
