### ISSUE TITLE
Selecting a file in Explorer after switching back to VSCode from a different window doesn't do anything

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/vscode#137551] opened 2021-11-19 22:01 UTC
Issue Type: <b>Bug</b>

After recent updates, if I am on a different window and then switch back to VS Code and then directly single-click on a file name in the Explorer list to open the file, the click does not do anything. I have to click the file name again to open it in the editor. I have observed this randomly, multiple times in the past two days, but every time I try to reproduce it again using these steps, it works. So there seems to be some condition under which this occurs.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (35.98GB free)|
|Process Argv|--crash-reporter-id f5824b19-814b-479d-9f84-0e0dac677fb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.2
icons-carbon|ant|0.2.4
custom-window-zoom|cra|1.1.4
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
eppz-code|epp|1.2.52
plantuml|jeb|2.16.0
fluent-icons|mig|0.0.14
azure-pipelines|ms-|1.194.1
azure-account|ms-|0.9.11
cpptools|ms-|1.7.1
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
synthwave-vscode|Rob|0.1.10
bootstrap-product-icons|rub|1.0.2
vscode-zipexplorer|sle|0.3.1
code-spell-checker|str|2.0.12
vscode-icons|vsc|11.7.0
gitblame|wad|8.1.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vshan820:30294714
vscod805:30301674
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534

```

</details>

**Comment by escline** [comment] 2021-11-25 02:22
Yes, happens to me as well. If I try to click on a different file to open when coming back to VSC from another window, it maintains the last selected file.
1. Open file in VSC
2. Switch to another window, like a browser.
3. Come back to VSC and try to click a different file in the explorer to attempt to open it.
4. VSC once again becomes focused, but the last file (from step 1) remains selected.
5. So once VSC is once again in focus, have to select new file again to open it.

**Comment by JacksonKearl** [comment] 2022-02-21 22:14
Duplicate of #140418

**Closed by JacksonKearl** 2022-02-21 22:14 UTC
Labels: bug, file-explorer
