### ISSUE TITLE
Renaming a file in Explorer is extremely slow

### ISSUE THREAD

**Issue by ivan-toriya-precis** [microsoft/vscode#236321] opened 2024-12-17 09:15 UTC
Type: <b>Bug</b>

Note: I'm working on a Python project.

1. Rename any file in the Explore.
2. Notification "Running 'File Rename' participants...' shown.
3. Experience extremely slow renaming.
4. Be annoyed by that.
5. Finished after ~40s.

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Linux x64 6.1.0-28-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 4100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.31GB (2.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2024.56.0
EditorConfig|Edi|0.16.4
themeswitch|Foo|1.0.5
copilot|Git|1.252.0
copilot-chat|Git|0.23.1
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.102.0
go|gol|0.44.0
geminicodeassist|goo|2.23.1
terraform|has|2.34.1
vscode-dbt-power-user|inn|0.50.4
hexinspector|mat|1.5.1
asm-code-lens|maz|2.6.1
bigquery-runner|min|1.22.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.11.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
hexeditor|ms-|1.11.1
remote-repositories|ms-|0.42.0
material-icon-theme|PKi|5.15.0
copy|Pra|1.1.1
vscode-yaml|red|1.15.0
WhenFile|rio|0.5.1
jinjahtml|sam|0.20.0
sql-bigquery|shi|1.9.0
git-autoconfig|shy|0.0.2
even-better-toml|tam|0.19.2
simple-rst|tro|1.5.4
cron-explained|tum|1.3.1
vim|vsc|1.29.0
gitblame|wad|11.1.1

(2 theme extensions excluded)

</details>

**Comment by ivan-toriya** [comment] 2024-12-17 09:18
Disabling `waderyan.gitblame` solves the issue.

**Comment by lramos15** [comment] 2024-12-17 17:27
Please do F1 -> Start Extension Bisect.

**Comment by ivan-toriya-precis** [comment] 2024-12-18 14:13
It didn't help. I can't reproduce the issue.

It happens after some time after `Developer: Reload Window`. 

Source Control and GitHub Copilot also hangs because of "it". It feels like some process blocks other parts.

Right now, I'm experiencing that Source Control hanged, but Copilot is working fine.
![Image](https://github.com/user-attachments/assets/e2844762-a178-406c-9562-178eadaeba6e)

<details>
<summary>Git Log</summary>

```
2024-12-18 14:58:54.104 [info] [Git][getRemotes] No remotes found in the git config file
2024-12-18 14:58:54.104 [info] > git config --get commit.template [17ms]
2024-12-18 14:58:54.105 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [2ms]
2024-12-18 14:58:54.136 [info] > git status -z -uall [16ms]
2024-12-18 14:58:54.137 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [1ms]
2024-12-18 14:59:06.188 [info] [Git][getRemotes] No remotes found in the git config file
2024-12-18 14:59:06.189 [info] > git config --get commit.template [17ms]
2024-12-18 14:59:06.190 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [2ms]
2024-12-18 14:59:06.222 [info] > git status -z -uall [17ms]
2024-12-18 14:59:06.223 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [1ms]
2024-12-18 15:00:26.431 [info] > git fetch [3ms]
```
</details>

After Reload everything works fine again.

**Comment by lramos15** [comment] 2024-12-19 18:59
Ok will close this for now since it's caused by an extension

**Closed by lramos15** 2024-12-19 18:59 UTC
Labels: info-needed
