### ISSUE TITLE
Intellisense Not Supported JSDoc Annotation @yields

### ISSUE THREAD

**Issue by LianSheng197** [microsoft/vscode#169525] opened 2022-12-19 10:54 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.74.1
- OS Version: Ubuntu 22.04.1 LTS x86_64

Steps to Reproduce:

1. **Just write a generator function like this one:**

![image](https://user-images.githubusercontent.com/18535495/208406578-545c738a-2d45-4de1-9768-7a4b64cd771e.png)

As you can see, the bottom variable `f` doesn't get type hints for string.  
This annotation is following [JSDoc @generator](https://jsdoc.app/tags-generator.html).

At this point, if we look at the hint of `parseFiles`, we can see that `yields` doesn't seem to be interpreted correctly, and the function doesn't seem to be a generator function. (no asterisks, nor any text description for generator function)

![image](https://user-images.githubusercontent.com/18535495/208407548-20b30a66-9bd9-4195-95eb-d7a2c4972a26.png)

2. **Current temporary solution**

Replace the `@yields {string}` to `@returns {AsyncGenerator<string>}`.  
Then the variable `f` below can correctly get the string type hint.
![image](https://user-images.githubusercontent.com/18535495/208408906-ee6832bf-bb81-4338-b96c-bd7a5cdc1575.png)

3. **Finally, this is example code:**

More details:
- Node.js v16.18.1
  - Already installed dependence `@types/node`.
  (But whether it is installed or not does not affect the reproduction of this problem.)

```js
import { resolve } from "path";
import * as fs from "fs";

async function* parseFiles(dir) {
    const dirEntires = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const dirent of dirEntires) {
        const res = resolve(dir, dirent.name);
        if (dirent.isDirectory()) {
            yield* parseFiles(res);
        } else {
            yield res;
        }
    }
}

(async () => {
    for await (const f of parseFiles('./public')) {
    }
})();
```

**Comment by mjbvz** [comment] 2022-12-19 18:39
Duplicate of https://github.com/microsoft/TypeScript/issues/23857

**Closed by mjbvz** 2022-12-19 18:39 UTC
