### ISSUE TITLE
Semicolons in Emmet abbreviations inside SASS files

### ISSUE THREAD

**Issue by zloy2452** [microsoft/vscode#115880] opened 2021-02-05 14:27 UTC
- VSCode Version: 1.53.0
- OS Version: Windows 10 Pro 20H2

Steps to Reproduce:

1. Open SASS file.
2. Expand any Emmet abbreviation.
3. The expanded line ends with a semicolon, which is unacceptable for SASS.
4. The issue appeared after 1.53.0 update.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rzhao271** [comment] 2021-02-05 17:23
Duplicate of #115839

**Closed by rzhao271** 2021-02-05 17:23 UTC
Labels: new release
