### ISSUE TITLE
Markdown formatting of link labels is inconsistent.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8821] opened 2016-07-06 22:49 UTC
- VSCode Version: Code - Insiders 1.3.0-insider (a1293f5056e79c3f0e2cd3e24909f41ff4eef472, 2016-07-05T13:09:46.271Z)
- OS Version: Windows_NT ia32 10.0.14372

Steps to Reproduce:

1. Open https://github.com/Microsoft/ChakraCore/blob/master/README.md in VS Code
2. Observe the following:

![image](https://cloud.githubusercontent.com/assets/494055/16637078/39d4a7ba-4391-11e6-8a0c-1e9292b8a1f4.png)

**Comment by unional** [comment] 2016-08-07 02:03
An simplier example:

```md
Something.
[a](#a) and [b](#b)
```

![image](https://cloud.githubusercontent.com/assets/3254987/17460026/68051fb8-5c08-11e6-8aa3-11bd9945173f.png)

**Comment by dilijev** [comment] 2016-08-08 18:58
@unional Thanks for finding a reduced repro :)

**Comment by mjbvz** [comment] 2016-09-27 20:45
@unional Your example looks like a duplicate of #11906. It should be fixed in the latest insiders builds

@dilijev The link colorization should also be fixed in the latest insiders builds. I just gave it a try with the linked file and it seems to be consistent now:

![screen shot 2016-09-27 at 1 43 39 pm](https://cloud.githubusercontent.com/assets/12821956/18891048/7f28a6aa-84b8-11e6-9405-8a74d73ec367.png)

Please let me know if you notice this or similar issues in any other documents.

Thanks

**Closed by mjbvz** 2016-09-27 20:45 UTC
Labels: markdown

**Comment by dilijev** [comment] 2016-09-27 21:09
Looks right now, thanks!
