### ISSUE TITLE
No syntax-highlighting in tooltip (Insiders)

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode#79588] opened 2019-08-21 17:10 UTC
```
Version: 1.38.0-insider
Commit: ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8
Date: 2019-08-21T13:25:25.587Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.9-arch1-1-ARCH
```

Steps to Reproduce:

1. Open any typescript/javascript file and hover over a symbol
2. A tooltip shoud appear with information about the symbol, however the syntax-highlighting is disabled.

![colour](https://user-images.githubusercontent.com/5961244/63452746-50460900-c447-11e9-8e33-8914f7eb902e.png)

Does this issue occur when all extensions are disabled? Yes

**Comment by mjbvz** [comment] 2019-08-21 17:47
Duplicate of #79589

**Closed by mjbvz** 2019-08-21 17:47 UTC
