### ISSUE TITLE
All of the sudden today I keep getting a prompt to reinstall VSCode and it keeps failing

### ISSUE THREAD

**Issue by jpierson** [Microsoft/vscode#1332] opened 2015-12-15 13:44 UTC
I see the following error after choosing to restart VSCode after prompting to install the update.

>The setup files are corrupted. Please obtain a new copy of the program.

Version 0.10.3
Commit 783ecf841a2b21edca6d86853670cae89b4c244f
Date 2015-11-26T14:06:31.538Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1

I've attempted to uninstall and reinstall VSCode but that hasn't seemed to help at all. I still get the same attempted update behavior.

**Comment by joaomoreno** [comment] 2015-12-15 14:14
Duplicate of #780.

Do you have a proxy, though?

**Closed by joaomoreno** 2015-12-15 14:14 UTC
Labels: bug, important, install-update

**Comment by jpierson** [comment] 2015-12-15 17:34
Not that I'm aware of... I am running inside of a Windows 10 VM on MacBook Pro through Parallels though if that helps.

**Comment by joaomoreno** [comment] 2015-12-16 09:10
Alright, thanks for the extra info!
