### ISSUE TITLE
Emmet Abreviation Is Not Working

### ISSUE THREAD

**Issue by TirthPatel06** [microsoft/vscode#107948] opened 2020-10-02 05:19 UTC
Issue Type: <b>Bug</b>

In The My VS Code Emmet Abriviation Is Not Working I Reinstalled VS code 4 to 5 times But Still Emmet Is Not Working And Live Server And Code Runner Is Also Not Working.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.85GB (1.27GB free)|
|Process Argv|--crash-reporter-id 3f54a3a4-688a-493d-a90d-d9e201dd486e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0

</details>

**Comment by rzhao271** [comment] 2020-10-02 21:28
Hi, can you give some steps to reproduce the issue?

**Comment by TirthPatel06** [comment] 2020-10-09 03:28
Yes

**Comment by rzhao271** [comment] 2020-10-22 22:27
Closing because I don't see any steps listed. For example, _how_ is Emmet not working?
Will re-open issue if/when repro steps provided.

**Closed by rzhao271** 2020-10-22 22:27 UTC
Labels: emmet, needs more info
