### ISSUE TITLE
ContextMenu in Editor/Title only available with Tabs active

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#9247] opened 2016-07-14 02:23 UTC
- VSCode Version:1.3.0
- OS Version: Windows 10

Using the [newly available API](https://code.visualstudio.com/updates#_extension-authoring)

Steps to Reproduce:

1. Add a `menu - editor/title` entry to `package.json`
```json
    "menus": {
        "editor/title": [
            {
                "command": "bookmarks.list",
                "group": "bookmarks"
            }
        ]
     }
```
2. Turn off showTabs (`"workbench.editor.showTabs": false`)

The new context menu command is not available. But if you turn on showTabs (`"workbench.editor.showTabs": true`), the command appears.

Thanks in advance

**Comment by jrieken** [comment] 2016-07-14 08:31
The actions then show in the context menu of the tab... Not nice and an active UX discussion. @bpasero for finding the duplicate of this

**Comment by jrieken** [comment] 2016-07-14 08:31
![screen shot 2016-07-14 at 10 31 46](https://cloud.githubusercontent.com/assets/1794099/16833137/2d206cb6-49ae-11e6-933b-42d4cb988ca7.png)

**Closed by jrieken** 2016-07-14 08:31 UTC
Labels: duplicate

**Comment by bpasero** [comment] 2016-07-14 09:39
@jrieken @alefragnani I am not sure this is the same issue, maybe can you clarify? you say that the actions are not showing up in the context menu if you disable tabs, so this would indicate that the issue is not related to us not showing actions when tabs are enabled.

Today:
* tabs disabled: all actions show up in the right hand corner
* tabs enabled: all actions show up on the tab itself

We plan to change this though to always show all actions int he right hand corner.

**Comment by jrieken** [comment] 2016-07-14 09:41
![screen shot 2016-07-14 at 11 41 23](https://cloud.githubusercontent.com/assets/1794099/16835212/e7567748-49b7-11e6-865a-0b02d79ed0d5.png)

Well, I see the commands in both cases. Unsure what the issue then is...

**Comment by bpasero** [comment] 2016-07-14 09:44
There is an edge case where we show a context menu when tabs are disabled and you right click on the title:

![image](https://cloud.githubusercontent.com/assets/900690/16835273/3791d22a-49b8-11e6-9a54-db3aff2397e0.png)

This might cause some confusion because that menu does not contain the actions contributed.

All this will get much better with: https://github.com/Microsoft/vscode/issues/7666

**Comment by alefragnani** [comment] 2016-07-14 11:20
The issue was related to this _edge case_. In fact I didn't notice that button in the right hand corner, sorry.

Thank you both for clarifying :+1:
