### ISSUE TITLE
Webviews in the Side Bar position bugs when views above collapse

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#127204] opened 2021-06-26 05:12 UTC
Issue Type: <b>Bug</b>

1. Run the Calico Colors — Webview View API Sample from vscode's API samples from https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample

2. Move the Calico Colors up so it's not the bottom one, and collapse (close) some view above itself to make it move up. The webview's position is bugged and laggin behind events from further expand/collapse events. (lateral resizing fixes it)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.7.1-050701-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3113)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 2|
|Memory (System)|7.54GB (0.71GB free)|
|Process Argv|webview-view-sample --no-sandbox --crash-reporter-id 21723db9-c8ea-462f-a1b4-f9c26cd3f8a8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
theme-verdandi|be5|2.0.1
emojisense|bie|0.8.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.5.1
tsl-problem-matcher|eam|0.4.0
prettier-vscode|esb|8.0.1
php-intellisense|fel|2.3.14
vscode-pull-request-github|Git|0.27.1
todo-tree|Gru|0.0.213
svgeditor|hen|2.9.0
banner-comments|hey|0.3.0
vscode-power-mode|hoo|2.2.0
rest-client|hum|0.24.5
svg|joc|1.4.7
banner-comments-plus|lun|0.3.1
git-graph|mhu|1.30.0
ecdc|mit|1.4.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4419
debugger-for-chrome|msj|4.12.12
printcode|nob|3.0.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
code-spell-checker|str|1.10.2
selectline-statusbar|tom|0.0.2
errorlens|use|3.2.7
vscodeintellicode|Vis|1.2.14
expand-selection-to-scope|vit|0.2.0
vscode-icons|vsc|11.5.0

(17 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by boltex** [comment] 2021-06-26 05:14
Here are some screen captures. (showing the colors widget before, ad after closing the 'todo-tree' above it.

![Screenshot from 2021-06-26 01-03-35](https://user-images.githubusercontent.com/847716/123502605-b25f8e80-d61b-11eb-9f53-dae1ed5972da.png)

![Screenshot from 2021-06-26 01-03-40](https://user-images.githubusercontent.com/847716/123502616-c3100480-d61b-11eb-9a26-75f07f7d9837.png)

**Comment by mjbvz** [comment] 2021-07-14 02:56
Duplicate of #110450

**Closed by mjbvz** 2021-07-14 02:56 UTC
