### ISSUE TITLE
Multiple hanging dir/find commands for large searches

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11181] opened 2016-08-30 09:51 UTC
Testing https://github.com/Microsoft/vscode/issues/11035

* setup symlinks in a way that you end up having circular references for a large workspace (I was using the VS Code repository to have meaningful large data)
* use quick open to find a file
* watch the processes that get spawned
* due to https://github.com/Microsoft/vscode/issues/11179 we end up doing a lot more work than needed
* close quick open
* open quick open and run the same search again

=> you see more and more dir commands piling up (interestingly the second time you try it seems 2 new dir commands popup instead of one)
=> I would expect the command to be killed when another one starts

![screen shot 2016-08-30 at 10 12 38](https://cloud.githubusercontent.com/assets/900690/18084499/ce525a9a-6ea7-11e6-9e72-b0c739bcee91.png)

**Comment by chrmarti** [comment] 2016-09-13 21:33
Updating title to reflect that this is also a problem with the other platforms.

**Comment by bpasero** [comment] 2016-09-28 13:41
@chrmarti any advise how to reproduce this? i think it was easy on Windows with the circular symlinks, but now we do not have the dir command anymore on Windows.

**Comment by chrmarti** [comment] 2016-09-28 14:50
On Linux/OSX opening/closing QuickOpen multiple time while `find` still runs would spawn an additional `find` process. The fix should prevent this and let the first `find` run to its end before spawning a new one when opening QuickOpen the next time.

**Comment by bpasero** [comment] 2016-09-28 15:08
@chrmarti thanks

**Comment by bpasero** [comment] 2016-09-29 14:35
@chrmarti I am still able to get 2 find processes running though:

<img width="363" alt="screen shot 2016-09-29 at 16 34 52" src="https://cloud.githubusercontent.com/assets/900690/18958355/a9d88b62-8662-11e6-8a3d-d7fc7453f212.png">

Steps:
* large folder (I copied 5 versions of typescript sourcecode with node modules installed and explicitly chose to not ignore node modules folder in search.exclude setting)
* open window and quickly open quick open multiple times

This is on Mac OS btw.

**Comment by chrmarti** [comment] 2016-09-29 16:24
@bpasero Cannot reproduce.

This would happen if the search process has terminated after the cache was populated. QuickOpen would first ask for a new cache to be populated and then start using the old cache (which is gone) which triggers another find.

One way for the search process to terminate is the timeout we've set to 1 hour. Any chance you hit that case? Does it reproduce on your machine?

**Comment by bpasero** [comment] 2016-09-30 05:29
Yes, reproducible right on startup with insiders build:

<img width="840" alt="screen shot 2016-09-30 at 07 27 13" src="https://cloud.githubusercontent.com/assets/900690/18981515/5858eade-86df-11e6-97e7-956c09b76b80.png">

* the workspace contains the typescript sources with installed node_modules 6 times
* contents: 
![image](https://cloud.githubusercontent.com/assets/900690/18981525/8083bd0e-86df-11e6-9bcb-c107d1ef3643.png)
* my settings:

```json
{
	"files.autoSave": "afterDelay",
	"editor.wrappingColumn": 3000,
	"editor.folding": false,
	"explorer.openEditors.visible": 0,
	"workbench.editor.showTabs": false,
	"workbench.editor.enablePreview": false,
	"git.enableLongCommitWarning": false,
	"window.openFilesInNewWindow": true,
	"workbench.quickOpen.closeOnFocusLost": true,
	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/node_modules/**": true
	}
}
```

**Comment by bpasero** [comment] 2016-09-30 05:29
All I do is open/close quick open via Cmd+P in some random order.

**Comment by isidorn** [comment] 2016-09-30 08:10
Leaving this for september, @chrmarti please investigate and decide if for september

**Comment by chrmarti** [comment] 2016-09-30 15:30
@bpasero Might be an artifact from the Activity Monitor. I sometimes see two `find` listed there when `ps` only shows one or none. Could you compare what the Activity Monitor shows you with what `ps` shows: `watch -n 1 'ps ax | grep find'`

Moving milestone as there is currently no action planned. Thanks.

**Comment by chrmarti** [comment] 2016-10-04 16:19
@bpasero Let me know if you get a chance to verify the above.

**Comment by bpasero** [comment] 2016-10-05 05:19
@chrmarti yes there are multiple finds spawned:

```
~/Development/Microsoft/monaco> ps ax | grep find
  173   ??  Ss     0:00.53 /usr/libexec/findmydeviced
37682 s001  U+     0:02.89 find -L . -not ( ( -name .git -o -name .svn -o -name .hg -o -name .DS_Store -o -name bower_components ) -prune ) -type f
37683 s001  U+     0:02.78 find -L . -not ( ( -name .git -o -name .svn -o -name .hg -o -name .DS_Store -o -name bower_components ) -prune ) -type f
37684 s001  U+     0:02.19 find -L . -not ( ( -name .git -o -name .svn -o -name .hg -o -name .DS_Store -o -name bower_components ) -prune ) -type f
37686 s002  R+     0:00.00 grep find
```

Easier for me to reproduce:
* copy the full typescript sources 10 times (this is roughly 500.000 files with 4.6 GB size
* start an instance and open quick open without typing
* open quick open and start typing

=> maybe it is an issue that only shows when you open quick open once without typing and once with typing?

**Closed** 2016-10-05 22:49 UTC
Labels: bug, search, verification-found

**Comment by chrmarti** [comment] 2016-10-05 22:53
Good finding, the cached promise ended up being canceled.

For verification: With a sufficiently large folder it was easy to reproduce. E.g., open the folder containing all your projects, the home folder, the root folder. Make sure there is at most one find process. (Only OSX / Linux.)

**Comment by AlphaBetaPeter** [comment] 2017-01-02 19:29
This bug is still present for me. Loading folders with many files (in my case loading the home folder with `code .`) leads to those find processes piling up. 

`find -L . -not ( ( -name .git -o -name .svn -o -name .hg -o -name .DS_Store ) -prune ) -type f`

Every process uses ~100% of the assigned CPU core which eventually leads to the whole CPU being used.

My setup:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Ubuntu 16.04 LTS

**Comment by bpasero** [comment] 2017-01-03 06:25
@AlphaBetaPeter maybe better to report this as separate issue to have a fresh look on it 👍

**Comment by AlphaBetaPeter** [comment] 2017-01-03 09:40
@bpasero will do :wink:
