### ISSUE TITLE
Run task after "watch" task

### ISSUE THREAD

**Issue by SkrupSulten** [microsoft/vscode#84460] opened 2019-11-11 08:05 UTC
We have an Angular application where I would like to be able to run another task after "ng build --watch" is done with its initial build. Because the watch task never terminates it seems impossible as it is currently.

**Comment by alexr00** [comment] 2019-11-12 09:18
Duplicate of https://github.com/microsoft/vscode/issues/70283

**Closed** 2019-11-12 09:18 UTC
Labels: *duplicate
