### ISSUE TITLE
VSCode is lagging on Mac

### ISSUE THREAD

**Issue by Kamieniu** [Microsoft/vscode#72223] opened 2019-04-12 17:59 UTC
Issue Type: <b>Performance Issue</b>

After the last updates, my VSCode started lagging while I'm working.

I did remove about 50% of my extensions but still, it takes about 10 seconds to display all available "packages" form node_modules to import.
IntelliSense isn't working, I have to add all imports by typing them.

I have tested removing all extensions and I did install Vscode Insiders too - after about 15minutes of work it also starts lagging.

It wasn't happening couples weeks ago.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 6|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|-psn_0_381021|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    98	  4112	code main
    0	    90	  4115	   gpu-process
    0	   287	  4117	   window (ArticlesGallery.tsx — gc-blog)
    0	   401	  4145	     extensionHost
    0	   582	  4155	       electron_node tsserver.js 
    0	    57	  4162	         electron_node typingsInstaller.js typesMap.js 
    0	    74	  4156	       electron_node server.js 
    0	    41	  4158	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=4145
    0	    41	  4146	     watcherService
    0	    33	  4164	     searchService
    0	   115	  4141	   shared-process
    2	    74	  4715	   window (Issue Reporter)
    0	     0	  4720	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ArticlesGallery.tsx — gc-blog)
|    Folder (gc-blog): 96 files
|      File types: json(26) js(24) map(21) tsx(14) ts(9) babelrc(1)
|                  gitignore(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.26
vscode-scss|mrm|0.6.2
python|ms-|2019.3.6558
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
rxjs-snippets|pko|0.0.2
tslint-vue|pro|1.5.6
trailing-spaces|sha|0.3.1
autoimport|ste|1.5.3
language-stylus|sys|1.11.0
python|tht|0.2.3
vscode-icons|vsc|8.5.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.208
wallaby-vscode|Wal|1.0.122
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by jasonaden** [comment] 2019-04-12 18:30
My CPU (current MBP) is maxed out with new release. Initially happened last week when I updated and I've had to keep VSCode closed since then. Updated again this morning and Code Helper is pinning CPU again.

**Comment by Kamieniu** [comment] 2019-04-12 20:17
Is there any solution for this issue? It's really annoying..

**Comment by jonathanconway** [comment] 2019-04-13 11:48
Might issue [72002](https://github.com/Microsoft/vscode/issues/72002) be related?

**Comment by Kamieniu** [comment] 2019-04-14 12:24
I did remove cache and downgrade version of TS to 3.3.3 and now it's all okay 👍

**Comment by mjbvz** [comment] 2019-04-15 15:19
Closing as duplicate of #72002

**Closed by mjbvz** 2019-04-15 15:19 UTC
Labels: freeze-slow-crash, new release
