### ISSUE TITLE
previewHTML: content reload

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#16307] opened 2016-12-01 04:34 UTC
If editor tab that contains `previewHTML` instance is switched off and then switched on again it reloads the content, I think I would be useful to have a mode, where it is not reloaded between switches.

Also it would be useful to have imperative update/reload feature.

**Comment by chrmarti** [comment] 2016-12-01 16:14
Duplicate of #16190. Please open a separate issue for the reload feature.

**Closed by chrmarti** 2016-12-01 16:14 UTC
