### ISSUE TITLE
Files created through the configuration service don't refresh the explorer

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71182] opened 2019-03-26 14:25 UTC
Steps:

- fresh workspace (no .vscode folder)
- Terminal > Configure default build task
- Answer questions which creates a .vscode\tasks.json file through the configuration service

Observe the .vscode folder doesn't show up. The following exception appears in the console

![capture](https://user-images.githubusercontent.com/1931590/55004928-699f7200-4fdb-11e9-9817-ecd310fc2cc8.png)

**Comment by bpasero** [comment] 2019-03-26 15:00
@isidorn could also be explorer

**Comment by isidorn** [comment] 2019-03-26 16:13
I can reproduce on OS X. I can also reproduce with stable. So this is an explorer issue
The issue is that the file service only sends the change event for the tasks.json file being changed, it does not fire that the .vscode folder got created.
Do we want the file service to keep behaving this way that it only sends the most specific resource created. If yes, then I need to write some code in the explorer to handle this

**Comment by bpasero** [comment] 2019-03-26 16:36
@isidorn this might be easier now that the file service is rewritten. Are you saying I should send a `FileOperationEvent(resource, FileOperation.CREATE, fileStat)` for each folder that is created on the way and it would work for you?

**Comment by isidorn** [comment] 2019-03-26 16:54
@bpasero yeah that would be fantastic

**Comment by bpasero** [comment] 2019-03-26 17:23
@isidorn actually a bit tricky for me because of the requirement of the `FileOperationEvent` needing a resolved stat. Currently I do not resolve each folder stat I create during the `mkdirp` call. Can you check if the event without resolved stat would be enough?

**Comment by isidorn** [comment] 2019-03-26 17:27
@bpasero yeah, I will check tomorrow.

**Comment by isidorn** [comment] 2019-03-27 15:59
Investigated a bit more and this is somewhat of a special case it seems.
I can not reproduce it if I turn off explorer auto reveal weirdly.

And for some weird reason I am not getting the events from the `FileService` at all. So I would expect at least on CREATE event for the .tasks.json or launch.json and I am not getting it.
@bpasero can you please investigate?

Turning off auto reveal helps becuase if it is on the explorer tries to reveal an element for which it did not get an event from the file service and it just fails. I get the raw event from the watcher which I handle with a timeout..

**Comment by bpasero** [comment] 2019-03-27 17:42
@isidorn this works for me, here is what I did:
* create an empty folder
* open it (running out of sources)
* add a console.log statement here
* run the action to create a task.json from template
* watch the output

I see:

![image](https://user-images.githubusercontent.com/900690/55099453-fb80ab00-50bf-11e9-8909-fdf8b428130f.png)

Btw this issue reproduces for me in stable as well with the same exception, so I do not think I broke something here.

I can still look into sending the events one by one, though I will have to stat each segment that is created which is a bit of a change from before, so I hope you are ready for more events. Since this is not a regression we can also look into changing it next week.

**Comment by bpasero** [comment] 2019-03-28 08:30
Moving to April, this is not a regression and my idea to send out events on the way actually does not work because in this case `IFileService.createFile()` is being used which is still travelling through the old code.

**Comment by isidorn** [comment] 2019-03-28 10:04
Yeah, let's sync next week to fix this.
I am doing very similar steps as you, but instead of tasks.json I did a "open launch.json". However I was not getting the event from the file service.

Anyways I should handle this case on the explorer side better. I think the issue here is that the reveal active editor comes before the file event, though I have to investigate more.

**Comment by isidorn** [comment] 2019-04-04 13:45
Fixed via 0bce369fea

**Closed by isidorn** 2019-04-04 13:45 UTC
Labels: bug, file-explorer
