### ISSUE TITLE
Tasks: Custom input variables should support predefined variables as default input

### ISSUE THREAD

**Issue by NCC1701M** [microsoft/vscode#152450] opened 2022-06-17 11:23 UTC
It should be possible to define the default value of an input variable as the value of an predefined variable.

For example:

This should set the default value and therefor the initialize value of the input to the currently selected text

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "ng g",
      "type": "shell",
      "command": "echo",
      "args": ["Do something with the input ", "${input:myInput}"]
    }
  ],
  "inputs": [
    {
      "type": "promptString",
      "id": "myInput",
      "description": "Name your component.",
      "default": "${selectedText}" // <-- The default value should be set to the selected text
    }
  ]
}
```

**Comment by alexr00** [comment] 2022-06-17 12:21
duplicate of https://github.com/microsoft/vscode/issues/64358

**Closed by alexr00** 2022-06-17 12:21 UTC
