### ISSUE TITLE
"editor.find.seedSearchStringFromSelection" is ignored

### ISSUE THREAD

**Issue by thomaseding** [microsoft/vscode#142864] opened 2022-02-11 17:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.1 (Universal)
- OS Version: MacOS 11.5.2

Steps to Reproduce:

1. Set `"editor.find.seedSearchStringFromSelection": "never"`
2. Select any text in an open text document
3. Open the search panel using (cmd+shift+f)
4. The search field is now erroneously updated. This is a recent regression, though not sure exactly when.

**Comment by teoincontatto** [comment] 2023-06-01 09:47
Please, fix this since it is really annoying behavior

**Comment by amunger** [comment] 2023-12-14 17:23
closing in favor of https://github.com/microsoft/vscode/issues/193584

**Comment by andreamah** [comment] 2024-01-22 22:43
This is not the same as https://github.com/microsoft/vscode/issues/193584. Steps to repro this:

1. Settings:
```
"editor.find.seedSearchStringFromSelection": "never"
```
2. Do a search near a word in the editor.
3. The editor will use the selection to seed the search :bug:

**Closed** 2024-01-30 17:32 UTC
Labels: bug, search

**Comment by alexr00** [comment] 2024-02-21 16:08
What's the best way to verify this? I tried to repro with VS Code stable, and I couldn't. The setting `editor.find.seedSearchStringFromSelection` seems to be about the find widget not the search view, which I'm also confused about. My steps:
1. Set the setting
2. Open a text document and select a word
3. ctrl+shift+f to open the search view
4. Search view is never populated with the currently selected word from step 2, no matter what the value of the setting is.

**Comment by teoincontatto** [comment] 2024-02-21 17:09
This version should include the fix in #203759

```
Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:07:19.849Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-94-generic snap
```

I can reproduce the issue with:

1. Setting `editor.find.seedSearchStringFromSelection` to `selection`
2. Open a text file and selecting a text (shift+left/right arrow key in my case)
3. Find Next Selection (`editor.action.nextSelectionMatchFindAction` key)
4. Move the cursor to any other different word in the text without selecting it
5. Find Next Selection (`editor.action.nextSelectionMatchFindAction` key)

At this point the other different word is searched instead of the one that was searched in step 3

Reproducible also if `editor.find.seedSearchStringFromSelection` is set to `never` in step 1

**Comment by andreamah** [comment] 2024-02-21 18:22
@teoincontatto I believe that this is a different bug. Can you file a new issue for this? This issue seems to concern workspace search (`ctrl`+`shift`+`f`)

**Comment by wenfangdu** [comment] 2024-03-06 03:34
@andreamah @mjbvz Is this released in the insider build? In the latest insider build, I tried "editor.action.addSelectionToNextFindMatch" + "actions.find" with setting "editor.find.seedSearchStringFromSelection": "never", the selected word still filled the search widget.
