### ISSUE TITLE
intellisense stops working for javascript again and again 1.24.1

### ISSUE THREAD

**Issue by vgvishesh** [Microsoft/vscode#51960] opened 2018-06-15 05:54 UTC
Issue Type: <b>Bug</b>

intellisense for JS stops working abruptly in middle of a working session. After restarting it, it starts working again and after some time again stops.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.23
cpptools|ms-|0.17.4

</details>

**Comment by mjbvz** [comment] 2018-06-18 21:56
@vgvishesh Have you had a chance to test the latest insiders build? If it is still not working, also try upgrading your workspace to use typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Comment by farlock85** [comment] 2018-06-18 22:57
Not sure why my comment was marked offtopic, but I've been using insiders for the last few hours and haven't encountered the error or the error I gave anymore.

**Comment by mjbvz** [comment] 2018-06-19 17:09
@farlock85 please open a new issue. I know the symptoms you were seeing may be similar to this issue but problems like this often have different root causes. I'd like to use this issue to track @vgvishesh's specific case

**Comment by farlock85** [comment] 2018-06-19 17:12
@mjbvz I did: https://github.com/Microsoft/vscode/issues/52072 and then it got closed because it's a duplicate with this one. I find it a bit hash that comments just get marked as offtopic after my original bug gets closed.

**Comment by mjbvz** [comment] 2018-06-19 17:15
Yes sorry that should not have happened. I did not know you got directed to this issue specifically. Sounds like it is fixed now though. Please respond on the #52072 if this is not the case

**Comment by vgvishesh** [comment] 2018-06-23 08:48
@mjbvz, i used the latest insiders build. Looks like it is fixed. 
Cheers.

**Closed** 2018-06-25 18:40 UTC
Labels: javascript, needs more info
