### ISSUE TITLE
Extension produces encoded URIs that cause confusion

### ISSUE THREAD

**Issue by maixuanhan** [Microsoft/vscode#9876] opened 2016-07-28 02:30 UTC
Hi,

Menu `Goto/Back`, `Goto/Forward` sometimes show error if file name contains any UPPERCASE characters.

E.g.
`Error` Unable to open 'schema.h': File not found (/home/mxhan/gitcode/mypro/ncf/plt/scm/schema.h).

while the file 'Schema.h' does exist.

**Additional information**
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:28:46.761Z)
- OS Version: Linux x64 3.16.0-77-generic

Steps to Reproduce:

1. Do code trace and code walk-through in project
2. Move back and forth using menu `Goto/Back`, `Goto/Forward` (or using shortcut)

**Comment by bpasero** [comment] 2016-08-08 11:51
I tried to reproduce and failed. Things I tried:
* navigate through project and go back (works for me)
* create the same file with different casing and go back (works for me, I can go between the 2 files)

I doubt this is an issue with the history but rather the file maybe was modified and we did not get the event? However I also tried that and could not reproduce (navigated around, then renamed a previously visited file to another case and then went back).

Closing until there are reliable steps to reproduce.

**Comment by maixuanhan** [comment] 2016-08-17 04:05
**Reproduce steps:**

1. Prepare a Folder containing 2 C++ source files as below.
2. Open VSCode, menu File > Open Folder..., select the folder, click OK.
3. Single click on Test.h in the explorer view.
4. CTRL + single click on `doAction` function. It should jump to the implementation in .cpp file.
5. CTRL + single click on `mCount` inside the function. It should jump back to the declaration in .h file.
6. Now press CTRL + ALT + - (or menu Go > Back). Bamm! It shows the error.
`Error Unable to open 'test.cpp': File not found (/home/mxhan/code_example/test.cpp).`

-------------------------------------
_Test.h_
```
#ifndef TEST_H
#define TEST_H

class Test
{
public:
    Test();
    ~Test();
    void doAction();
private:
    int mCount;
};

#endif
```
_Test.cpp_
```
#include "Test.h"

Test::Test()
{
    this->mCount = 0;
}

Test::~Test()
{
}

void Test::doAction()
{
    this->mCount++;
}
```

**Comment by maixuanhan** [comment] 2016-08-17 04:09
@bpasero : please try with above steps

**Comment by bpasero** [comment] 2016-08-17 04:27
@maixuanhan what extensions do you have installed?

**Comment by maixuanhan** [comment] 2016-08-17 04:56
@bpasero : C/C++
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by bpasero** [comment] 2016-08-20 06:06
@maixuanhan there seems to be a bug in the C++ extension. When I follow your steps I can see the file Test.cpp opened twice in my tabs: The original one is the one I opened and the second one is the one opened via Goto definition. 

When I look at the resource that gets opened when I click on Test.cpp it is:

`file:///home/ticino/Desktop/cpluscplus/Test.cpp`

The one from C++ extension is:

`file://%2Fhome%2Fticino%2Fdesktop%2Fcpluscplus%2Ftest.cpp`

Since I am using URI.toString() to find out if the file is the same, for me these files are different. 

@jrieken moving to you to decide if something in our world should guard against such URIs or if this is something the C++ team should fix.

**Comment by jrieken** [comment] 2016-08-22 07:33
`file://%2Fhome%2Fticino%2Fdesktop%2Fcpluscplus%2Ftest.cpp` is an uri without a path but just an authority `scheme://authority/path`. See: https://tonicdev.com/57baaa462debe6150094e4e6/57baaa462debe6150094e4e7

@bpasero How/Why does the workbench try to open that?

**Comment by bpasero** [comment] 2016-08-22 07:39
@jrieken if you follow the steps in https://github.com/Microsoft/vscode/issues/9876#issuecomment-240308278

**Comment by jrieken** [comment] 2016-08-22 07:51
I cannot reproduce to an error and I don't understand why this is assigned to me. The problem is that URI isn't used properly - the path ends up as authority for which it's common to normalise the casing (lowercase).

**Comment by jrieken** [comment] 2016-08-22 07:52
This is the data we are receiving from the extension. I wonder why we are getting so far...

![screen shot 2016-08-22 at 09 52 22](https://cloud.githubusercontent.com/assets/1794099/17847416/1fc5766a-684e-11e6-90f3-7e9a10336bc9.png)

**Comment by jrieken** [comment] 2016-08-22 07:55
This is how it looks from TypeScript (note the difference between *authority* and *path*). I'll forward to the CPP folks

![screen shot 2016-08-22 at 09 54 36](https://cloud.githubusercontent.com/assets/1794099/17847472/7475b256-684e-11e6-8c25-e5ecef323c05.png)

**Comment by jrieken** [comment] 2016-08-22 07:57
This issue was moved to Microsoft/vscode-cpptools#1

**Closed by jrieken** 2016-08-22 07:57 UTC
Labels: bug, linux, workbench

**Comment by bpasero** [comment] 2016-08-22 08:31
Thanks, I was expecting this an issue with the extension too but wanted to fyi you.
