### ISSUE TITLE
Gutter (Editor Decoration) and Rulers don't play nicely

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#90182] opened 2020-02-06 23:10 UTC
- VS Code Version: 1.42.0-insider
- OS Version: macOS Catalina 10.15.2 (19C57)

Steps to Reproduce:
I will be using Gitlens for this repro, but any extension that utilizes a Gutter can trigger this.
1. Setup a ruler in settings.json, e.g.   "editor.rulers": [80],
2. Open a file
3. Toggle blame using "Gitlens: Toggle File Blame Annotations"
4. See that the ruler is not updated, so renders at the incorrect character.

w/o gutter:
![Screen Shot 2020-02-06 at 3 09 36 PM](https://user-images.githubusercontent.com/1166263/73986542-b8ec4980-48f2-11ea-920b-73d5fd0a65a4.png)

w/ gutter: 
![Screen Shot 2020-02-06 at 3 09 43 PM](https://user-images.githubusercontent.com/1166263/73986559-c73a6580-48f2-11ea-98eb-cd62771d2ec2.png)

**Comment by eamodio** [comment] 2020-02-07 00:14
Duplicate of https://github.com/microsoft/vscode/issues/39165

**Comment by alexdima** [comment] 2020-02-07 07:07
The problem here is that inline decorations are defined per line, so the width of each inline decoration can vary across lines. The editor lacks the understanding that all of those inline decorations align in such a way and that they push all the content to the right across all lines.

I think we would need to have special editor API for rendering these blame annotations in order to get everything working great, the current usage of inline decorations is ok, but lacks certain semantic info.

**Closed** 2020-04-08 02:24 UTC
Labels: editor-rendering, feature-request
