### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by KillingSpark** [Microsoft/vscode#32463] opened 2017-08-14 09:49 UTC
Hey there,
I took on the challenge to install vscode on void linux from source. The installation doesn't list all dependencies I needed. These were pkg-config, libXScrnSaver, gconfmm. Now its working, with the only exception being the integrated terminal. Would be neat if you could update the installation notes.

**Comment by Tyriar** [comment] 2017-08-14 15:05
Duplicate of https://github.com/Microsoft/vscode/issues/13089, https://github.com/Microsoft/vscode/issues/17142

**Closed by Tyriar** 2017-08-14 15:05 UTC
Labels: install-update
