### ISSUE TITLE
cmd命令模式下，首次打开没有提示符

### ISSUE THREAD

**Issue by yunxu1019** [Microsoft/vscode#70141] opened 2019-03-10 03:13 UTC
- VSCode Version:1.32.1(system setup)
- OS Version: windows10 64bit
![image](https://user-images.githubusercontent.com/15274374/54080176-372c1e80-4325-11e9-94c8-642220216c41.png)

Steps to Reproduce:

1.终端设置为cmd
![image](https://user-images.githubusercontent.com/15274374/54080184-532fc000-4325-11e9-9a7f-20259c50c31a.png)

2. Esc + `

![image](https://user-images.githubusercontent.com/15274374/54080191-765a6f80-4325-11e9-947c-638eea243e19.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment] 2019-03-10 04:08
我没看懂你想说啥……没法翻译……
I don't understand what the author wanted to say...

**Comment by yume-chan** [comment] 2019-03-11 06:48
duplicate of #57803

**Comment by Tyriar** [comment] 2019-03-11 14:42
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Closed by Tyriar** 2019-03-11 14:42 UTC
Labels: new release
