### ISSUE TITLE
Automatically add missing import statements like in WebStorm

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#180212] opened 2023-04-18 10:33 UTC
In WebStorm there's a setting called "Add unambiguous imports on the fly".

> When you are pasting blocks of code that contain references to classes or static methods and fields that are not yet imported, the IDE automatically inserts the missing import statements.

https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#automatically-add-import-statements

It is really useful especially in the cases when you're copy-pasting code or for e.g. when you're using Copilot, because you need to manually add imports or use keyboard shortcut, this could be done automatically. I believe this will make DX even better.

**Comment by mjbvz** [comment] 2023-04-18 16:14
Duplicate of https://github.com/microsoft/TypeScript/issues/50187

**Closed by mjbvz** 2023-04-18 16:14 UTC
