### ISSUE TITLE
Intellisense pop-up opens erroneously & does not closes itself (since 1-2 release)

### ISSUE THREAD

**Issue by mrhammadasif** [Microsoft/vscode#36060] opened 2017-10-11 11:49 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.2
vscode-docker|Pet|0.0.18
Bookmarks|ale|0.16.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
tslint|eg2|1.0.10
expand-region|let|0.1.1
string-manipulation|mar|0.2.0
code-beautifier|mic|1.7.2
dotenv|mik|1.0.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
sublime-keybindings|ms-|2.9.1
team|ms-|1.122.0
Lodash|oys|1.0.0
sass-indented|rob|1.4.2
vscode-todo-highlight|way|0.5.11
blade-runner|yuk|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Write any Object in TypeScript
2. When Completed first parameter and its value then after pressing comma, the auto complete popup appears to complete wrapping function parameters, that doesn't closes until I close it by pressing escape (annoying)
3. You can Check below attached image 

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/1535613/31438934-b50d6ce0-aea3-11e7-9689-569c000553eb.png)

**Comment by bsvipas** [comment] 2017-10-11 12:48
You can try to use `"editor.parameterHints": false`

**Comment by mrhammadasif** [comment] 2017-10-11 14:07
@bsvipas Thanks but I want to have suggestions turned on but to not open on every comma "," entered

**Comment by mjbvz** [comment] 2017-10-11 21:29
Duplicate of #35806

**Closed by mjbvz** 2017-10-11 21:29 UTC
Labels: duplicate, javascript
