### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#21797] opened 2017-03-02 16:19 UTC
- VSCode Version: <code>Code - Insiders 1.11.0-insider **[Unsupported]** (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:04:47.508Z)</code>
- OS Version: <code>Darwin x64 16.4.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)</code>
- Memory (System): <code>16.00GB (0.90GB free)</code>
- Memory (Process): <code>317.59MB working set (0.00MB peak, 172.75MB private, 187.18MB shared)</code>
- Load (avg): <code>7, 3, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|148|
|main|app.isReady => window.loadUrl()|319|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|390|
|renderer|require(workbench.main.js)|1141|
|renderer|-> of which require() node_modules|112|
|renderer|create extension host => extensions onReady()|627|
|renderer|restore viewlet|1742|
|renderer|restore editor view state|690|
|renderer|overall workbench load|2076|
|main + renderer|start => extensions ready|2778|
|main + renderer|start => workbench ready|4105|

---

[9489_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814399/9489_renderer.cpuprofile.txt)
[9489_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/814400/9489_main.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-03-09 16:04
Closing this as a dupe of https://github.com/Microsoft/vscode/issues/22087.

**Closed by jrieken** 2017-03-09 16:04 UTC
Labels: perf-profile
