### ISSUE TITLE
[html] auto close triggers on undo/redo and breaks undo/redo history

### ISSUE THREAD

**Issue by coderpatsy** [microsoft/vscode#34484] opened 2017-09-15 18:05 UTC
- VSCode Version: 1.16.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.  In a html file, type (not copy) `<span>test`
2.  Undo to before step 1
3.  Redo

Now you cannot redo the typing of `test` or any edits after that point, as the auto close overwrote the undo/redo history.

Alternate steps:

1.  Delete an opening tag not immediately followed by its closing tag; e.g. delete the `<span>` of `<span>test</span>`
2.  Undo your deletion

Reproduces without extensions: Yes

Expected behavior:

VSCode does not perform any new automatic formatting on undo/redo.

**Comment by aeschli** [comment] 2018-09-21 12:18
duplicate of #52777

**Comment by rchiodo** [comment] 2021-09-29 22:18
This is still reproing for me? Maybe I misunderstood what the fix did:

![undoSpan](https://user-images.githubusercontent.com/19672699/135356465-4f8bb176-ffc6-403e-8fdf-afa6ce406c26.gif)

**Closed** 2021-09-30 09:11 UTC
Labels: bug, debt, verification-found, extensions

**Comment by rchiodo** [comment] 2021-09-30 22:07
/verified.
