### ISSUE TITLE
Sass: auto-complete being shown with HTML tags right after semicolon

### ISSUE THREAD

**Issue by brunnopleffken** [Microsoft/vscode#976] opened 2015-12-03 17:16 UTC
When editing a *.scss file (Sass/Compass), after typing a semicolon, the auto-complete list is automatically shown with HTML tags and attributes.

<img width="596" alt="screen shot 2015-12-03 at 3 15 13 pm" src="https://cloud.githubusercontent.com/assets/3427344/11567918/af2bd206-99d0-11e5-9401-4879c1f5b4df.png">

Typing semicolon + Enter (line break) actually results in an unexpected behavior...

<img width="201" alt="screen shot 2015-12-03 at 3 11 52 pm" src="https://cloud.githubusercontent.com/assets/3427344/11567868/5a3b869c-99d0-11e5-8cdb-f99b7ade7103.png">

**Comment by aeschli** [comment] 2015-12-04 07:54
duplicate of #250

**Closed by aeschli** 2015-12-04 07:54 UTC
