### ISSUE TITLE
php code inside <script>

### ISSUE THREAD

**Issue by shoxsz** [Microsoft/vscode#16077] opened 2016-11-25 19:00 UTC
- VSCode Version: 1.7.2 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
- OS Version: 6.1.7601 Service Pack 1 compilação 76

Steps to Reproduce:

1. open/create a .php file.
2. put this inside the file:

```
<script>

<?php?>

</script>
```
the closing tag swap its colors, the <\ and > goes red and the text script goes white, haven't reported this with other tags.

EDITED
I was using monokai theme, i changed it and it seems that the closing tag gets the same color scheme of the php tag.

**Comment by kiatng** [comment] 2016-11-27 05:25
I also notice that the highlighting will sometimes fail, in the following example, there is no more highlight from line 31:
```
<script>
var i = <?php echo $this->getOptionI(); ?>;
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
<?php if ($bool) : ?>
i += <?php echo $this->getOptionK(); ?>;
<?php endif; ?>
</script>
```

**Comment by aeschli** [comment] 2016-11-28 14:32
duplicate of #15792

**Closed by aeschli** 2016-11-28 14:32 UTC
