### ISSUE TITLE
Tasks: Please do not reveal a panel on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64900] opened 2018-12-12 17:06 UTC
I opened a multi root workspace where `vscode-docs` is in and got this:

![image](https://user-images.githubusercontent.com/900690/49886089-0d07b500-fe39-11e8-823e-92b52773d9a7.png)

Running this command from the command line does not return an error:

![image](https://user-images.githubusercontent.com/900690/49885883-a8e4f100-fe38-11e8-9dc9-97662f76dfea.png)

It would be great if we could stay away from opening the panel just like that. We already have enough spam from notifications.

**Comment by dbaeumer** [comment] 2018-12-12 21:30
@bpasero are you suggesting we are turning this into a notification. Or is there a different recommendation what to do when such errors occur?

@alexr00 what is strange is the fact that we try to resolve gulp tasks at all. This doesn't happen for me when opening vscode-docs alone. Is this connected to the auto run task feature you added. Looks like from the notification.

**Comment by dbaeumer** [comment] 2018-12-12 21:32
Actually it does fail in vscode-docs even as a workspace folder when Run Task is executed.

<img width="846" alt="capture" src="https://user-images.githubusercontent.com/1931590/49900084-db551500-fe5d-11e8-9208-caaeb792be97.png">

**Comment by dbaeumer** [comment] 2018-12-12 21:37
OK. The problem is that the gulp file in the vscode-docs repository has this in it:

```
if (!GITHUB_TOKEN) {
  $.echo('This script clones vscode-website and requires access token')
  $.exit(1)
}
```

which makes the auto detection fail with a non zero return code (which is correct).

Not sure how to solve this since the task provider API has not means to tell the provider to only resolve tasks for a specific workspace.

**Comment by octref** [comment] 2018-12-12 22:58
I got the same opened panel annoyance from https://github.com/Microsoft/vscode/issues/64166.

@bpasero For the notification flood, did you consider adding an option for hiding the fly-out by default? The count on StatusBar will be updated, and users see all incoming unread message when clicking the bell.

**Comment by bpasero** [comment] 2018-12-13 06:30
> @bpasero are you suggesting we are turning this into a notification. Or is there a different recommendation what to do when such errors occur?

@dbaeumer yes, the advantage of a notification is that I can hit ESC to hide it. The panel is really bad to bring up because:
* it destroys my workbench layout that I had (even if a panel was visible)
* I cannot get back to my previous layout easily
* it covers a lot of space when the window is small
* it seems like a different way of notification compared to our standard way

> @bpasero For the notification flood, did you consider adding an option for hiding the fly-out by default? The count on StatusBar will be updated, and users see all incoming unread message when clicking the bell.

That will probably not work for notifications that ask for user input. Seems OK for notifications without buttons.

**Comment by dbaeumer** [comment] 2018-12-13 08:33
@bpasero 

> Even better than showing a notification right on startup would be to show it more in-context of my action, e.g. the first time I actually invoke a task. Why would you want to inform me about something that I am currently not using?

We do this in general. The problem here is that the user wants us to start a task automatically so we need to find that task and therefore ask the task providers for the tasks they know. Without any automatic task this task resolving only happens when you actually run a task.

**Comment by dbaeumer** [comment] 2018-12-13 08:34
I have no problem turning these into notifications. The advantage though with output panels is that they keep more context in case this fails n times,  more text to show, ...

**Comment by bpasero** [comment] 2018-12-13 09:53
> The problem here is that the user wants us to start a task automatically
I did not enable this for my workspace though ever, so this came out of the blue for me.

> So may be a combination of a detailed text in the output panel and a notification to make users aware of this?

Yes, the output can show as much information as needed, but the goal should be to not show it automatically unless the user agreed. A notification should draw attention to this. This allows us to eventually fine-tune the notification experience better, e.g. allow a user to disable certain notifications through a setting when in Zen mode or in general. I feel the automated revealing of the panel is something the user would never be able to prevent.

**Comment by dbaeumer** [comment] 2018-12-13 10:12
OK. Then we should tune this in our task provider extensions to do the following:

- write stil to the output panel
- no reveal of the output panel
- a notification saying that something failed with a button to reveal the panel.

@alexr00 does that makes sense to you?

**Comment by bpasero** [comment] 2018-12-13 13:20
Awesome, thanks for looking into this 👍 

Question: is this something we need to tell our extension authors too? E.g. are there extensions that open the panel to notify about something similar to what we do with our built in extensions?

**Comment by octref** [comment] 2018-12-13 15:42
> That will probably not work for notifications that ask for user input. Seems OK for notifications without buttons.

If extension has to get user input they'd use QuickInput. Their notification need to handle the dismiss button, so I hope I can say "dismiss all". I have seen hundreds of notifications in the last few months. I read them and dismiss them. I don't remember clicking any button even once.

**Comment by bpasero** [comment] 2018-12-13 16:00
> If extension has to get user input they'd use QuickInput.
I think that is not a good model because that is not a modal thing to show. If an extension must interrupt the user to get input it can imho only be a modal dialog. Anything else would cause issues (e.g. consider you are in the middle of typing into the editor and quick input would popup, you would continue to type into quick input?)

**Comment by Tyriar** [comment] 2018-12-14 14:03
> Question: is this something we need to tell our extension authors too? E.g. are there extensions that open the panel to notify about something similar to what we do with our built in extensions?

Whenever I see extensions do this I normally report issues telling them to be less aggressive (eg. https://github.com/Microsoft/vscode-cpptools/issues/1160).

Looking at this problem a different way, have we considered allowing users to suppress output panel open requests? For example, if an extension requests output focus multiple times, a notification pops up asking if it's annoying and whether they want to disable the extension's output focusing rights?

**Comment by bpasero** [comment] 2018-12-14 14:11
I guess we did not, yet.

**Comment by alexr00** [comment] 2018-12-14 15:02
> Question: is this something we need to tell our extension authors too? E.g. are there extensions that open the panel to notify about something similar to what we do with our built in extensions? Or is this actually coming from our tasks code itself?

This is coming from our built in extensions, not from the tasks code. If there are task providers showing the output we need to ask them to show a notification instead.

Showing the output channel is too agressive and showing a notification is too aggressive. We actually only do this in the gulp extension, nowhere else. I've changed it into a warning notification that directs you to see the output. This will also be helped by https://github.com/Microsoft/vscode/issues/64355 which I'll be doing next. If, after this fix and the one for https://github.com/Microsoft/vscode/issues/64355 tasks are still too noisy we can find some other options.

**Closed** 2018-12-14 15:04 UTC
Labels: feature-request, tasks

**Comment by dbaeumer** [comment] 2018-12-17 09:19
@alexr00 can you do the same change for `jake` and `grunt` as well and may be `npm` or let @egamma know about this.

**Comment by alexr00** [comment] 2018-12-20 13:55
Did it for jake and grunt. Doesn't look like npm needs it.
