### ISSUE TITLE
View title actions not shown when hovering over view on webview views

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#116128] opened 2021-02-06 20:01 UTC
Actions in the view title bar are usually visible when the mouse is anywhere in the view. As shown here:

![image](https://user-images.githubusercontent.com/4674940/107128457-b52b3400-6872-11eb-990d-ac42b78f1c3f.png)

In the focus mode view, however, "Open Pull Request on GitHub" is only visible when hovering over the actual title bar. That makes it hard to discover. I suspect that's because the webview consumes the hover events.

```json
     {
        "command": "pr.openPullRequestOnGitHub",
        "title": "Open Pull Request on GitHub",
        "category": "GitHub Pull Requests",
        "icon": "$(globe)"
      },
```

**Comment by mjbvz** [comment] 2021-02-08 21:59
Duplicate of #109030

**Closed** 2021-02-08 21:59 UTC
