### ISSUE TITLE
--disable-extensions doesn't disable everything

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#60481] opened 2018-10-10 09:12 UTC
Issue Type: <b>Bug</b>

When launching Code from a shell with `code-insiders --disable-extensions`, the icon of one of my extensions stays in the left bar.

Please take a look at this screenshot:

![screenshot2](https://user-images.githubusercontent.com/15984272/46725415-cead1880-cc84-11e8-98c2-4302b3e76bbc.PNG)

The heart on the left bar is the icon of an extension call Favorites.

This is not supposed to happen with `--disable-extensions`. 
The pop-up message on the bottom-right confirms that all extensions are disabled.

When clicking on the heart, nothing happens, which means the extension itself is disabled, but the icon not.

Note that this doesn't happen 100% of the time. More like 30%. Try launching `code-insiders` and `code-insiders --disable-extensions` alternately.

Often, the heart shows up for half a second (which is already too much for an instance supposed to be without any extension), then disappears.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.29.0-insider (cc5e2b41c3add18a31e87f84b5d6162566a38d6e, 2018-10-10T05:19:52.883Z)
OS version: Windows_NT x64 10.0.15063

**Comment by usernamehw** [comment] 2018-10-10 13:19
Duplicate of #60159

**Comment by creal1976** [comment] 2018-10-12 23:22
Stop emailing me

Sent from my Verizon Wireless 4G LTE DROID


"vscodebot[bot]" <notifications@github.com> wrote:


Closed #60481<https://github.com/Microsoft/vscode/issues/60481>.

**Comment by sandy081** [comment] 2018-10-17 10:05
@sguillia I am not able to reproduce this. Can you please try with latest insiders and check if you can still reproduce?

**Comment by sguillia** [comment] 2018-10-17 12:28
@sandy081 Reproduces with 1.29.0-insider (799bc78af597769a5dd5a6b002359ddae412b1be)

**Comment by sandy081** [comment] 2018-10-19 13:20
I can also reproduce it now. Thanks.

**Comment by sandy081** [comment] 2018-10-29 14:46
To verify:

- Install an extension that contributes view container. Eg., live share.
- Open code with a fresh user data directory
- Shut down code
- Open code in the same user data directory but with `--disable-extensions` option
Make sure the live share container icon is not shown. (It appears for a moment from the cache and disappears).

**Closed** 2018-10-29 14:46 UTC
Labels: bug, explorer-custom
