### ISSUE TITLE
Disable Typescript snippets suggestions on imports

### ISSUE THREAD

**Issue by victorgarciaesgi** [Microsoft/vscode#36831] opened 2017-10-24 15:27 UTC
How to disable Typescript snippets on Imports?
It's annoying to read with all the snippets!

![image](https://user-images.githubusercontent.com/15092120/31940865-034407c2-b8c0-11e7-8982-bc8086091346.png)

**Comment by mjbvz** [comment] 2017-10-24 16:58
Duplicate of #1304

**Closed by mjbvz** 2017-10-24 16:58 UTC
Labels: duplicate, typescript
