### ISSUE TITLE
Auto-Complete gives higher priority to variables not in my code.

### ISSUE THREAD

**Issue by mattdesl** [Microsoft/vscode#42536] opened 2018-01-30 19:50 UTC
- VSCode Version: 1.19.3
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Create a new JavaScript file with `const THREE = require('three');` at the top
2. Start typing `console.log(new THREE.`

Auto-complete will default to `HTMLHRElement` instead of `THREE`.

Does this issue occur when all extensions are disabled?: Yes

A bit frustrating since there seems to be no way to disable this.

Typing looks like this before hitting the period `.` key:

<img width="594" alt="screen shot 2018-01-30 at 2 46 25 pm" src="https://user-images.githubusercontent.com/1383811/35587747-b2e98be4-05cc-11e8-822d-ff06d5f8c720.png">

However, upon hitting `.`, auto-complete re-writes `THREE` to `HTMLHRElement`.

<img width="574" alt="screen shot 2018-01-30 at 2 46 31 pm" src="https://user-images.githubusercontent.com/1383811/35587783-cd2996ca-05cc-11e8-8877-0a6a1c29f311.png">

**Comment by mjbvz** [comment] 2018-01-30 19:56
Duplicate of #40311

Should be fixed in insiders

**Closed by mjbvz** 2018-01-30 19:56 UTC
Labels: javascript

**Comment by mjbvz** [comment] 2018-01-30 19:58
Actually could be #41060 as well. Try setting `"editor.selectSuggestions": "never"` if you still hit this in insiders
