### ISSUE TITLE
LESS: Import-Options only allow one option, Spec allows multiple

### ISSUE THREAD

**Issue by Z3roCoder** [Microsoft/vscode#15954] opened 2016-11-23 11:33 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 Enterprise
I am not using any additional LESS-Linting Plugins

Steps to reproduce:
1.  Create a .less-File
2. Enter the following code;
`@import (once,less) url("fonts/someStyleSheet.css");`

VSCode will notify you with:
`[less] ) expected`
Less-Reference: Less-Reference: http://lesscss.org/features/#import-options however allows multiple Import-Options

**Comment by aeschli** [comment] 2016-11-23 13:39
duplicate of #14121

**Closed by aeschli** 2016-11-23 13:39 UTC
