### ISSUE TITLE
Deleting multiple folders in WSL2 makes blue screen and does not release the space

### ISSUE THREAD

**Issue by hyjforesight** [microsoft/vscode#175629] opened 2023-02-28 08:24 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
- OS Version: WIN11 22H2 X64, WSL2 (Ubuntu 22.04)

Steps to Reproduce:

1. Run Ubuntu 22.04 via WSL2 in VSCODE
2. Create multiple folders (at least 10) including big data inside.
3. Delete all folders at the same time.
4. Move your mouse and wait around 5s. Blue screen will show.
![image](https://user-images.githubusercontent.com/75048821/221794828-587de1bd-da9f-4ab0-a09e-2204b604e040.png)
5. Restart your PC. Restart WSL2. Find all the folders were gone, but the space was not released.
6. Try >diskpart, select ext4 file path, >compact vdisk, >detach vdisk. Didn't work. Space not released.

Thanks!

**Comment by aeschli** [comment] 2023-02-28 16:40
Thanks for reporting. Can you report this this against https://github.com/microsoft/WSL ?

Probably a duplicate of https://github.com/microsoft/WSL/issues/7335

**Closed by aeschli** 2023-02-28 16:40 UTC

**Comment by hyjforesight** [comment] 2023-03-01 14:48
Yes, that's a duplicate. Thanks!
