### ISSUE TITLE
Problems Saving Jupyter Notebook

### ISSUE THREAD

**Issue by hadihedge** [microsoft/vscode#114588] opened 2021-01-19 19:25 UTC
Issue Type: <b>Bug</b>

Launch a new Jupyter Notebook: untitled-1.ipynb
Get on with the coding
Saving using Save or Save as does not produce a window to save the file
Only by closing the tab do I get the prompt to save it
Even after I do that, the next time I open the workspace, the untitled file comes back up again.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by bpasero** [comment] 2021-05-21 11:37
Duplicate of https://github.com/microsoft/vscode/issues/121974

**Comment by bpasero** [comment] 2021-08-10 09:02
@hadihedge can you try this scenario again with today's insider build: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2021-08-17 11:26 UTC
Labels: needs more info, notebook, workbench-untitled-editors
