### ISSUE TITLE
Tabulations in makes snipets interpreter

### ISSUE THREAD

**Issue by Ad5001** [Microsoft/vscode#26207] opened 2017-05-08 11:21 UTC
- VSCode Version: 1.12
- OS Version: Ubuntu 17.04
- Extensions: Some are enabled in the example, but the bug is still here with them disabled
- DevTools: Nothing interesting.

Steps to Reproduce:

1. Create a snipet (I use PHP in this example)
2. Include tabs in it. You already see the error "Excepted comma or closing bracket"
3. Try using it. It will isue some [object Object] for absolutly no reason

![Screen Capture](https://cloud.githubusercontent.com/assets/16436883/25802015/b9c44d4a-33f0-11e7-9f44-6a1730869c4c.png)

In this example, I use the "Function description" snipet.

Edit: Partial fix to use tabs in snipets: using \t instead of a tab directly

**Comment by egamma** [comment] 2017-05-08 14:42
Duplicate of #25938, which is planned for the next recovery build.

> Edit: Partial fix to use tabs in snippets: using \t instead of a tab directly

Independently, you should fix your templates and use `\t`,

**Closed by egamma** 2017-05-08 14:42 UTC
Labels: duplicate
