### ISSUE TITLE
Windows-Taskbar icon is not visible

### ISSUE THREAD

**Issue by niralparmar** [Microsoft/vscode#39591] opened 2017-12-04 22:04 UTC
- VSCode Version: 1.18.1 x64
- OS Version: Win 7

Steps to Reproduce:

1.Updated vscode to current version
2. Old Orange icon got replaced with new blue icon
3. Check icon in taskbar (with or without instance running)
Without instance running 
![image](https://user-images.githubusercontent.com/4327556/33578563-d7f5cc98-d8fb-11e7-8671-ae054d14b65e.png)
With instance running 
![image](https://user-images.githubusercontent.com/4327556/33578608-f0b0e308-d8fb-11e7-81b6-7e6f126f91f3.png)

Reproduces without extensions: Yes

**Comment by LeThiHyVong** [comment] 2017-12-05 03:01
Change your wallpaper to another color other than blue. 
Since VS Code new icon is transparent and pure blue, of course you can see it on a blue background.

**Comment by bpasero** [comment] 2017-12-05 05:44
Closing as designed. Please also see: https://code.visualstudio.com/blogs/2017/10/24/theicon

**Closed by bpasero** 2017-12-05 05:44 UTC
Labels: workbench
