### ISSUE TITLE
Rendering issues for one eight block characters in Terminal

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/vscode#161323] opened 2022-09-20 15:51 UTC
Type: <b>Bug</b>

There are a few rendering issues related to the one eight block unicode characters in the vscode terminal, as used for scrollbars and lines.

The following is a screenshot of an app in the vscode terminal. I have highlighted where the rendering isn't quite right. I suspect there is more than one issue here. It looks like their is both a sub-pixel glitch and maybe a block char renders outside of a cell.

<img width="977" alt="Screenshot 2022-09-20 at 16 46 18" src="https://user-images.githubusercontent.com/554369/191305677-a74c7a47-87b0-4ff8-8732-440949f19ff8.png">

The following is iTerm on MacOS. Other terminals look much the same.

<img width="1035" alt="Screenshot 2022-09-20 at 16 47 49" src="https://user-images.githubusercontent.com/554369/191306116-ceb03077-e91a-4264-bb8f-9b9d6cd0b361.png">

I've zoomed in the exaggerate the effect, but the issue is present on more typical zoom levels.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:07:15.900Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 708fb231-9126-40c3-a471-56c4901cf66d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-color|ans|0.4.5
vscode-database|baj|2.2.3
vscode-django|bat|1.10.0
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.8.0
code-runner|for|0.11.8
vscode-pull-request-github|Git|0.50.0
sass-lint|gle|1.0.7
gc-excelviewer|Gra|4.2.55
vscode-peacock|joh|4.2.1
chat|kar|0.35.0
restructuredtext|lex|189.2.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.21
black-formatter|ms-|2022.5.12591021
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.20
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vsliveshare|ms-|1.0.5723
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
hide-gitignored|npx|1.1.0
vetur|oct|0.36.0
austin-vscode|p40|0.10.8
material-icon-theme|PKi|4.20.0
excalidraw-editor|pom|3.3.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
snappify|sna|1.0.1
code-spell-checker|str|2.8.0
sass-indented|syl|1.8.22
cython|tcw|0.1.0
simple-rst|tro|1.5.2
luna-paint|Tyr|0.16.0
vscode-icons|vsc|11.17.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
fc301958:30567733

```

</details>

**Comment by Tyriar** [comment] 2022-09-22 14:07
@willmcgugan can you copy and paste the content of the terminal in this state so we can get the problem characters?

**Comment by Tyriar** [comment] 2022-09-22 18:03
Can reproduce with `▔` when zoomed in:

![image](https://user-images.githubusercontent.com/2193314/191819268-4029751b-d680-4a76-bf8d-756d9356ebfc.png)

**Comment by Tyriar** [comment] 2022-09-23 17:12
Upstream fix: https://github.com/xtermjs/xterm.js/pull/4134

**Comment by willmcgugan** [comment] 2022-09-29 11:18
Thanks @Tyriar  I gather that fixes the long top line, but there are other rendering issues in the screenshot.

Here's vscode. Note the glitches at the top and bottom of the scrollbars.

https://user-images.githubusercontent.com/554369/193017319-021ad132-bea5-41f2-b904-0ac8c1a415e8.mov

Here's iTerm (other terminals look much the same).

https://user-images.githubusercontent.com/554369/193017448-7565e14b-5539-4328-8c0d-bfc8189ea44f.mov

I'm guessing the block characters don't quite cover the background, which is leads to this erroneous line.

**Comment by Tyriar** [comment] 2022-09-29 11:35
@willmcgugan what do you mean at the top of the scroll bar?

I can't reproduce the bottom of the scrollbar problem:

![image](https://user-images.githubusercontent.com/2193314/193021155-9c2cc8e1-dbdd-42e6-afc5-4d33a7251c4c.png)

**Comment by willmcgugan** [comment] 2022-09-29 12:59
I should have moved the scrollbar in the txt dump. Try the following:

[capture2.txt](https://github.com/microsoft/vscode/files/9674686/capture2.txt)

I wonder if it related to screen resolution. It only appears at certain zoom levels, but when it does it is quite obvious. I'm also viewing this on a 4K monitor, which might be making a difference.

Here's a screen capture I've blown up a bit. Hopefully it's obvious now.

![capturezoom](https://user-images.githubusercontent.com/554369/193036910-a9d5512a-eadf-4c42-b020-076b7ff4ca97.png)

Here's the original. The difference is a line of one pixel in height, so it might not be clear unless you download this image and zoom in...

<img width="756" alt="Screenshot 2022-09-29 at 13 43 09" src="https://user-images.githubusercontent.com/554369/193037169-ff8a5b52-8f28-4357-aaed-ada29f03c0ee.png">

**Comment by willmcgugan** [comment] 2022-09-29 13:04
Top of the scrollbar blown up a bit...

![top](https://user-images.githubusercontent.com/554369/193038644-b7a4808b-21e1-4f95-9483-12770e0182a4.png)

**Comment by Tyriar** [comment] 2022-09-29 16:26
I see this:

![image](https://user-images.githubusercontent.com/2193314/193084485-4be7286e-53a5-4d21-85ac-a1656aed21aa.png)

@willmcgugan can you set up the [xterm.js demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo) and see if changing these 4 lines:

https://github.com/xtermjs/xterm.js/blob/51c580e7a47dd92dc77f12fca602e76d106ec327/src/browser/renderer/CustomGlyphs.ts#L429-L432

to:

```ts
      Math.round(xOffset + box.x * xEighth),
      Math.round(yOffset + box.y * yEighth),
      Math.round(box.w * xEighth),
      Math.round(box.h * yEighth)
```

and see if that fixes it? You'll need node installed for this so feel free to decline, but it would make it easier to iterate on this stuff.

**Comment by connor4312** [comment] 2022-09-30 16:34
Reopening as it sounds like there's still some ongoing fixes to be made here

**Comment by Tyriar** [comment] 2022-12-08 15:56
Looks fixed now:

![image](https://user-images.githubusercontent.com/2193314/206494043-7f33f703-4fe0-4458-8a8f-181b201b239b.png)

I tested both canvas and webgl on the xterm.js demo at various zoom levels on my 4k monitor.

**Closed by Tyriar** 2022-12-08 15:56 UTC
Labels: bug, upstream, terminal-rendering
