### ISSUE TITLE
Rg Memory Leak

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode#121455] opened 2021-04-16 11:37 UTC
Before I get into it, I'll start with the vscode "Report Issue" which said I had too much text or something and I needed to paste it in here.
I switched to my browser and another tab opened, containing a bunch of HTML code:
```
(file://<pathTo>/.cache/kioexec/krun/3007895_0/new):
<!DOCTYPE html>
...a whole bunch of vscode generated html...
  </body>
</html>
```
Now for the actual issue...

- VS Code Version: Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:14:35.442Z)
- OS Version: Linux x64 5.10.27-dirty

Steps to Reproduce:

1. Open multi-root workspace
2. Search for 'TIFFFieldWithTag'

Does this issue occur when all extensions are disabled?: Didn't disable them since it appears unrelated given 2 previous searches worked with no issue.

It happened 3 times with that one search.
The first time, I didn't realize what was happening until it was too late and I had to wait for OOM to kick and kill off "rg".
```
Apr 16 05:26:15 computerName kernel: Out of memory: Killed process 3001853 (rg) total-vm:4516264kB, anon-rss:2336064kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:4716kB oom_score_adj:0
```
The second time, I tried it again to make sure I was watching htop to see if it was vscode.
The third time was to get the status information below for that test.

One of the searches I did before which worked with no issue was '_TIFFmalloc(tsi'. I just tried it again right now (after those 3 failures), and it worked fine again.
Out of curiosity, I tried that failed search again and the memory spiked again with no results. VERY odd.

```
Status Before The Search:
Version:          Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:14:35.442Z)
OS Version:       Linux x64 5.10.27-dirty
CPUs:             Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)
Memory (System):  7.23GB (1.09GB free)
Load (avg):       4, 3, 9
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id a2928a5c-190e-4d25-8038-9980bdeb3821
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      133  3006253 code-insiders main
    0       37  3006260    zygote
    0       74  3006323      gpu-process
    0       37  3006262    zygote
    0        0  3006266      zygote
    0       59  3006351    utility
    0      237  3006366    window (tiffdump.c - tiff (Workspace) - Visual Studio Code - Insiders)
    0      148  3006391      extensionHost
    1       30  3006547        <pathTo>/.vscode-insiders/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools
    0       15  3006638        <pathTo>/.vscode-insiders/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3006547 0
    0       59  3006571        <pathTo>/VSCode-linux-x64/code-insiders <pathTo>/VSCode-linux-x64/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=3006391
    0       59  3006422      watcherService
    0       59  3006461      searchService
    0      148  3006403    shared-process
    0       59  3006451      ptyHost
    0        0  3006530        /bin/bash

Workspace Stats: 
|  Window (tiffdump.c - tiff (Workspace) - Visual Studio Code - Insiders)
|    Folder (tiff): 2 files
|      File types: txt(1)
|      Conf files:
|    Folder (jpeg-6b): 147 files
|      File types: c(72) h(13) doc(8) 1(6) st(5) jpg(4) bcc(2) cfg(2) dj(2)
|                  mac(2)
|      Conf files:
|    Folder (libtiff): 1180 files
|      File types: man(236) dll(140) c(105) html(104) rtf(60) 3tiff(38)
|                  mui(36) in(27) ldf(27) 1(25)
|      Conf files: tasks.json(1)


Status During The Search:
Version:          Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:14:35.442Z)
OS Version:       Linux x64 5.10.27-dirty
CPUs:             Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)
Memory (System):  7.23GB (0.12GB free)
Load (avg):       6, 3, 9
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id a2928a5c-190e-4d25-8038-9980bdeb3821
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      104  3006253 code-insiders main
    0       37  3006260    zygote
    9       59  3006323      gpu-process
    0       37  3006262    zygote
    0        0  3006266      zygote
    0       52  3006351    utility
   10      178  3006366    window (tiffdump.c - tiff (Workspace) - Visual Studio Code - Insiders)
    0      118  3006391      extensionHost
    0       67  3006547        <pathTo>/.vscode-insiders/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools
    0        0  3006638         <pathTo>/.vscode-insiders/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3006547 0
    0       59  3006571        <pathTo>/VSCode-linux-x64/code-insiders <pathTo>/VSCode-linux-x64/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=3006391
    0       52  3006422      watcherService
    0       59  3006461      searchService
    2     3532  3006826        <pathTo>/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --ignore-case -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules -g !**/bower_components -g !**/*.code-search --max-filesize 17179869184 --no-ignore-parent --follow --crlf --auto-hybrid-regex --regexp TIFFFieldWithTag\r?\n --no-config --no-ignore-global --json --multiline -- .
    0       89  3006403    shared-process
    0       52  3006451      ptyHost
    0        0  3006530        /bin/bash

Workspace Stats: 
|  Window (tiffdump.c - tiff (Workspace) - Visual Studio Code - Insiders)
|    Folder (tiff): 2 files
|      File types: txt(1)
|      Conf files:
|    Folder (jpeg-6b): 147 files
|      File types: c(72) h(13) doc(8) 1(6) st(5) jpg(4) bcc(2) cfg(2) dj(2)
|                  mac(2)
|      Conf files:
|    Folder (libtiff): 1180 files
|      File types: man(236) dll(140) c(105) html(104) rtf(60) 3tiff(38)
|                  mui(36) in(27) ldf(27) 1(25)
|      Conf files: tasks.json(1)
```

```
Extension | Author (truncated) | Version
-- | -- | --
xml | Dot | 2.5.0
vscode-nuget-package-manager | jmr | 1.1.6
cortex-debug | mar | 0.3.7
csharp | ms- | 1.23.9
cpptools | ms- | 1.1.3
msbuild-project-tools | tin | 0.3.15
```

```
Include A/B experiment info
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletextcf:30288478
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872
```

EDIT0:
I went ahead and downloaded the latest insider, and it's still an issue in that:
```
Version: 1.56.0-insider
Commit: 25785b97e533b15ae3b12e48aaf4187416437e62
Date: 2021-04-15T05:14:30.209Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.27-dirty
```

EDIT1:
AGH! Okay, I forgot I had mounted a mostly unrelated iso in a temporary folder in that libtiff git folder since I was already working in there.
After I noticed that and unmounted/removed it, the search went fine.
What I cannot explain is why that particular search failed but the others succeeded.
I don't know if you want this to remain open to explore the "why", or just close it since I figured out how it was a problem in my case.
I hold the possibility that the mounted iso folder contained large data files (multi-gb) that "rg" may have been trying to load wholly into memory. But again, I don't know why the other searches still worked.

**Comment by JacksonKearl** [comment] 2021-04-16 15:45
It seems to me like the problem is indeed that massive file which ripgrep would try to load into memory. Can you reproduce the problem with standard CLI version of ripgrep? If so maybe file an issue on the project's repo, https://github.com/BurntSushi/ripgrep. 

I will close this as being a configuration issue with search excludes, if using the CLI `rg` never produces this issue we may look more into it.

**Comment by JacksonKearl** [comment] 2021-04-16 15:45
cc @RMacfarlane for the first paragraph re issue reporter.

**Closed by JacksonKearl** 2021-04-16 15:45 UTC

**Comment by vindicatorr** [comment] 2021-04-17 03:43
Whoof, okay ignore all the stuff below "**EARLIER**".
It seems copying/pasting the "rg" command from the "status" output above is no bueno. The "**" was making bash do some REALLY wonky stuff I think, and those globs needed to be in quotes.
Pressing the up-key in the console for going back in the command history showed that wonkiness clearly.

I also found the regex had to be in quotes too.
Once everything was quoted, I could replicate the rg memory hogging.

Failed:
`$ rg --hidden --ignore-case -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --max-filesize 17179869184 --no-ignore-parent --follow --crlf --engine auto --regexp "TIFFFieldWithTag\r?\n" --no-config --no-ignore-global --multiline -- .`

Individual Changes That Succeeded:
- Dropping the "--max-filesize" down to a low value. (I don't have 17GB of available RAM. I don't have 8GB of **available** RAM. "_I don't have a square to spare._")
- Dropping the "\r?\n"
- Dropping the "--multiline"
The iso with large files still had to be mounted to cause the issue. I'm sure that makes sense with the "--multiline" being used.

**Just so you don't miss something I included below, "--auto-hybrid-regex" is deprecated according to the man. It's why I changed that in the command to "--engine auto".

**EARLIER**
Okay, it wasn't even about the iso mounted path with large files... (or maybe not only that)
I can see that the search term was NOT 'TIFFFieldWithTag', but rather a '\r?\n' was appended to it when I selected the text to copy (probably along with '--multiline' which was added to "rg" because of those characters).
I tried it with 'TIFFFieldWithTag' as-is (no cr/lf), and it worked fine, even with the mounted iso.

Succeeded:
unmounted iso; 'TIFFFieldWithTag\r?\n'
mounted iso; 'TIFFFieldWithTag'

Failed:
mounted iso; 'TIFFFieldWithTag\r?\n'

I've been trying to use the command stated in the "status" output above (<pathTo>/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/vscode-ripgrep/...) in a terminal, but for some reason, can't get it to fail (hog memory).
I'm in the libtiff directory with the mounted iso, so I'd think that would do it, but it doesn't. It just returns with:
```
mntiso*/.git: No such file or directory (os error 2)
mntiso*/.svn: No such file or directory (os error 2)
mntiso*/.hg: No such file or directory (os error 2)
mntiso*/CVS: No such file or directory (os error 2)
mntiso*/.DS_Store: No such file or directory (os error 2)
mntiso*/node_modules: No such file or directory (os error 2)
mntiso*/bower_components: No such file or directory (os error 2)
mntiso*/*.code-search: No such file or directory (os error 2)
{"data":{"elapsed_total":{"human":"0.006754s","nanos":6754122,"secs":0},"stats":{"bytes_printed":0,"bytes_searched":0,"elapsed":{"human":"0.000000s","nanos":0,"secs":0},"matched_lines":0,"matches":0,"searches":0,"searches_with_match":0}},"type":"summary"}
```
So NO results are found (even though there are)

As an aside, while looking at the rg man, I saw:
```
--auto-hybrid-regex
           DEPRECATED. Use --engine instead.
```

Okay, I dumbed it down a lot since rg just wasn't working right for me in a console...
I started with "rg TIFFFieldWithTag". Fine.
Then "rg --regexp TIFFFieldWithTag". Fine.
Working all the way back to what I suspected to be an issue "-g !**/.git". Those "**" stuff caused havoc, in the end relating to an "argument list too long" error.
Without any of the "-g" parameters, even the "failed" command worked (though there were no 'TIFFFieldWithTag\r?\n' found, which makes me wonder how I even managed to paste that into the search to begin with).

I think bash is doing some weird stuff when I use those sub wildcard stuff.
Even trying "rg -g !**/.git TIFFFieldWithTag"... wth! Ahhh, okay. Starting over up top.

**Comment by JacksonKearl** [comment] 2021-04-17 13:47
Thanks for the detailed report! To summarize: your query string unintentionally included a newline, causing ripgrep to go into multiline mode. In multiline mode, ripgrep loads files into memory, causing high memory use. This can potentially be mitigated via the `--max-filesize` parameter to ripgrep. 

cc @roblourens for if we might want to support a setting for overriding  `--max-filesize`.
