### ISSUE TITLE
vscode.dev use search error

### ISSUE THREAD

**Issue by Gitby-Leo** [microsoft/vscode#228322] opened 2024-09-12 08:49 UTC
searchService.ts:130 
 Error performing web worker text search TypeError: T.with is not a function
    at l.joinPath (workerMain.js:47:42666)
    at D (localFileSearch.js:5:2452)

vs/base/common/uri.ts
```ts
/**
	 * Join a URI path with path fragments and normalizes the resulting path.
	 *
	 * @param uri The input URI.
	 * @param pathFragment The path fragment to add to the URI path.
	 * @returns The resulting URI.
	 */
	static joinPath(uri: URI, ...pathFragment: string[]): URI {
		if (!uri.path) {
			throw new Error(`[UriError]: cannot call joinPath on URI without path`);
		}
		let newPath: string;
		if (isWindows && uri.scheme === 'file') {
			newPath = URI.file(paths.win32.join(uriToFsPath(uri, true), ...pathFragment)).path;
		} else {
			newPath = paths.posix.join(uri.path, ...pathFragment);
		}
		return uri.with({ path: newPath });
	}
```

how to solve it?

**Comment by andreamah** [comment] 2024-09-13 16:23
duplicate of https://github.com/microsoft/vscode/issues/227742
/duplicate https://github.com/microsoft/vscode/issues/227742

**Closed** 2024-09-13 16:23 UTC
Labels: *duplicate
