### ISSUE TITLE
Cannot open multiples of same task

### ISSUE THREAD

**Issue by krokofant** [Microsoft/vscode#64443] opened 2018-12-05 18:17 UTC
Version: 1.30.0-insider (system setup)
Commit: 85f805acf9436381b878cab5ab6c5146beec7893
Date: 2018-12-05T06:19:36.555Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Add a task like:
```json
		{
			"label": "nodejs environment",
			"command": "../.node/UseNodeEnv.ps1",
			"type": "shell",
			"options": {
				"shell": {
					"executable": "powershell.exe",
					"args": ["-ExecutionPolicy", "Bypass", "-NoExit"]
				}
			},
			"problemMatcher": [],
			"presentation": {
				"echo": false,
				"reveal": "always",
				"focus": true,
				"showReuseMessage": false,
				"panel": "new"
			}
		},
```
Where `../.node/UseNodeEnv.ps1` could be any powershell script.
2. Run the task twice
3. On second run you'll get a message asking if you want to *Terminate* or *Restart* the task.
4. With the config `"panel": "new"` I expect another task instance to be opened.

**Comment by alexr00** [comment] 2018-12-06 08:39
`"panel": "new"` controls if the terminal is re-used, not if a task can have multiple instance. 

Duplicate of #32264

**Closed by alexr00** 2018-12-06 08:39 UTC
Labels: tasks
