### ISSUE TITLE
Drag and Drop text copies it instead of moving

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#35453] opened 2017-10-01 11:27 UTC
- VSCode Version: 1.16.1 - 1.19
- OS Version: Win10x64

Sometimes Drag and Drop'ing text copies it instead of moving (without holding ctrl). It's extremely annoying since it doesn't change the cursor and a copy of a viable chunk of code wouldn't normally trigger linter to complain or even produce a runtime error, but it surely would mess with the output. I only notice it when reviewing my changes in GIT or when this happens after dragging text very short distances, like into the next/prev line. But 3+ lines away it is already easy to miss. 

I don't know how to repro it - happens to me maybe once-twice per work session. I've only noticed that when I do notice this behavior, as long as I don't "disturb" it - it keeps on going, i.e. if I just copied a piece of text this way, if I don't select another chunk or press ctrl or change the tab - every subsequent drag-moving of this still selected piece of text would create a new copy. My first reaction to this is "oh, my ctrl key probably stuck" so I press it a couple of times and it "helps" but as I said, the cursor doesn't even change and there would be a multitude of other things happening if it ware a stuck key, since typing would turn into hotkeying.

Thank you.

**Comment by chrisdothtml** [comment] 2017-10-03 17:32
Same issue here. As far as I can tell, it copies the text every time for me

**Comment by jminer** [comment] 2017-10-20 09:01
I have had this happen many times, but it seems to happen randomly, like 2% of the time I select something. I haven't noticed any way to reproduce it on demand. It is not a stuck key causing it. As the OP said, when it happens, if I try dragging the selected text again, it will create another copy. However, if I deselect the text, and select the same text again, then I can drag and drop the text without it being copied.

**Comment by Spown** [comment] 2017-10-24 05:24
managed to capture the bug "on camera"
![](https://drive.google.com/uc?id=0B-OJBofmehO3Sm53QWlCaEh2R1k)

**Comment by Spown** [comment] 2017-11-28 02:11
~~who do I need to f...~~ What can I do to get this issue looked into? Do you ned some logs? Where should I look when this thing happens?

**Comment by will-l-h** [comment] 2017-12-07 15:36
I've run into this frustrating bug, but like @jminer, it's fairly rare. The only clue that I can add is that the related copy drag and drop feature #21145 is triggered by holding control (on windows) during the drag and the cursor will change to pointer with a "+" but the cursor is not changing during this bug.

**Comment by Elkfoot2** [comment] 2018-03-07 19:14
A recipe to recreate the bug, at least on Windows 10:
1. Hold the Ctrl key
2. Click on another app (not VSCode)
3. Release Ctrl
4. Return to VSCode
5. Select some text and drag it - it will copy instead of move.

I suspect it happens in other situations because I think I see this when I have not left VSCode, but I imagine there is one root cause and this recipe will help to identify it.

**Comment by Kevin-He-DVHS** [comment] 2018-03-19 23:24
Same issue on macOS High Sierra 10.13.3
When it happens, it is permanent at least when the app process is still running (have not tried restarting the app)
Never happened before. This is the first time I encountered this bug

**Comment by dbdemigod** [comment] 2018-04-19 19:48
Still happening in version 1.22, far more than 2% of the time. It just did it like 5 times in a row.

Win 7, .ts and .html files. How long must this persist to get a fix or workaround?

**Comment by Spown** [comment] 2018-04-19 21:58
@rebornix please move this issue in the backlog at least.

**Comment by pablodgcatulo** [comment] 2018-05-05 01:25
Same issue, 1.22 on fedora 27

**Comment by tuliomarchetto** [comment] 2018-06-06 15:39
Same here! **Version 1.23.1** on macOS High Sierra

**Comment by GlenPerkins** [comment] 2018-06-16 04:07
My Mac El Capitan (10.11) laptop and High Sierra iMac both have had this problem ever since drag and drop text moving was introduced to VS Code, so that's multiple versions of Mac HW & OS, multiple versions of Win, and multiple versions of VSC exhibiting this bug, with full line selection (single and multiple lines selected by dragging down line nums) and with a line-portion selection as demonstrated by Spown in the video above.

**Comment by ksmolyanin** [comment] 2018-07-06 11:11
I reproduce it stably on my Linux machine. Version 1.24.1

**Comment by StephenLarkin** [comment] 2018-07-19 09:15
Happens all the time for me on Windows. Version 1.25.1.

**Comment by Aquaculture** [comment] 2018-08-01 15:44
This has been going on for at least a year at this point and is extremely frustrating. I have this on all machines I work on, Windows and Macs. Here are the details for one of my machines:

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by Aquaculture** [comment] 2018-08-01 15:56
After reading some other comments, I found a workaround. After a copy error, if I Ctrl click the page, then it seems to drag & drop properly. Not sure of how consistent the behavior is as I just now discovered it.

**Comment by GammaGames** [comment] 2018-09-05 18:03
I found another way to reproduce it:

1. Highlight some text
2. Press Ctrl+Shift+F to open search with selected text
3. Double click a result to select it
4. Accidentally drag and copy text instead of dragging

It seems to happen whenever the editor loses focus to any sidebars or panels, not just the window.

![peek 2018-09-05 12-01](https://user-images.githubusercontent.com/7832163/45111969-948bac80-b103-11e8-86d1-4a7c1ba827d5.gif)

**Comment by rebornix** [comment] 2018-09-07 23:29
We didn't reset the drag and drop state when the editor loses focus, so if ctrl/option key is pressed before the editor loses focus, then if we come back to the editor and drag and drop, it always thinks it should copy and drop. Shares the same root cause as #53142 .

This is fixed and will be in next Monday's Insiders. If you still see issues, let me know about more details.

**Closed by rebornix** 2018-09-07 23:29 UTC
Labels: bug, editor, editor-contrib, under-discussion
