### ISSUE TITLE
Git links broken on insider release notes

### ISSUE THREAD

**Issue by Sleaker** [Microsoft/vscode#35930] opened 2017-10-09 20:54 UTC
- VSCode Version: latest insider release for 1.18
- OS Version: Windows 10 x64

Steps to Reproduce:

1. install latest insider release.
2. Attempt to click 'Closed bugs' link on the release notes page
3. Link does not quote "October 2017" properly, thus breaking the filter.  

Milestone Naming should either not have spaces, or the release notes need to be passed through a url-encoding for links to fix text what needs to be quoted.

ex: current link opens as: https://github.com/Microsoft/vscode/issues?q=is:issue+label:bug+milestone:October+2017+is:closed

Link in url bar after fixing quote issue and re-pressing enter shows proper url-encoded string: 
https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20milestone%3A%22October%202017%22%20is%3Aclosed%20

**Comment by Sleaker** [comment] 2017-10-09 20:57
Also note the second link showing Closed feature requests is also broken:

https://github.com/Microsoft/vscode/issues?q=is:issue+milestone:October+2017+is:closed+label:feature-request

should be:
https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A%22October%202017%22%20is%3Aclosed%20label%3Afeature-request%20

**Comment by gregvanl** [comment] 2017-10-10 15:10
Closing as duplicate of reopened https://github.com/Microsoft/vscode-docs/issues/1136. I'll see if we can come up with another work around.

**Closed by gregvanl** 2017-10-10 15:10 UTC
