### ISSUE TITLE
Vim plugin does not work in the lastest version

### ISSUE THREAD

**Issue by KaoImin** [Microsoft/vscode#60228] opened 2018-10-09 03:02 UTC
Issue Type: <b>Bug</b>

While updated the lastest version, the vim plugin does not work suddenly.

VS Code version: Code - Insiders 1.29.0-insider (1358e903716cf77711493770d63dde1ea178a73e, 2018-10-08T05:11:18.105Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 3|
|Memory (System)|16.00GB (2.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
vscode-markdownlint|Dav|0.20.0
vscode-dash|dee|1.10.0
vscode-rust-syntax|dun|0.0.30
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
mdmath|goe|2.3.4
asciidoctor-vscode|joa|0.15.1
language-julia|jul|0.10.3
Lisp|mat|0.1.8
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.8.0
cpptools|ms-|0.19.0
Go|ms-|0.6.90
vscode-docker|Pet|0.3.1
vscode-icons|rob|7.27.0
rust|rus|0.4.10
latex-support|tor|2.0.2
tensorflow-snippets|vah|0.3.3
vim|vsc|0.16.9
markdown-all-in-one|yzh|1.6.2
vscode-proto3|zxh|0.2.1

(2 theme extensions excluded)

</details>

**Comment by xconverge** [comment] 2018-10-09 03:28
#60190

**Comment by mjbvz** [comment] 2018-10-09 04:53
Duplicate of #60168

**Closed by mjbvz** 2018-10-09 04:53 UTC
Labels: insiders
