### ISSUE TITLE
Allow to split editor vertically via context menu

### ISSUE THREAD

**Issue by NeilMacMullen** [Microsoft/vscode#28965] opened 2017-06-18 14:33 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

it took me a while today to realise the reason I couldn't get 'side-by-side' file views was because the 'editor group layout' was set to vertically stacked.  To be fair the 'split editor' icon does change according to which mode you're in but it's a bit subtle. Why not provide a right-click context menu on the 'split editor' button to allow a switch?

**Comment by bpasero** [comment] 2018-04-18 16:52
Marking as duplicate of https://github.com/Microsoft/vscode/issues/14909

**Closed by bpasero** 2018-04-18 16:52 UTC
Labels: feature-request, workbench-layout
