### ISSUE TITLE
prevent Jasmine from autofilling from intellisense when mocha/chai is framework

### ISSUE THREAD

**Issue by gfogle** [Microsoft/vscode#27855] opened 2017-06-01 15:10 UTC
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.13.5

Steps to Reproduce:

1. using a project with mocha as the test running with chai, in a test begin typing expect(<<var>>).to
2. wait for intellisense to kick in and `toBe` etc will show up as jasmine suggestions
3. typing `.` will autofill, so will tabbing
4. in order to get `to.be`, `to.equal`, etc you have to hit space, backspace, then `.`

Ask: would like to be able to disable the Jasmine suggestions, or other languages

**Comment by sandy081** [comment] 2017-06-01 16:48
Please file an issue against jasmine extension.

**Comment by chiangf** [comment] 2017-06-01 17:08
@sandy081 Is there a way to disable an extension (e.g. jasmine) so that its intellisense doesn't show up?

**Comment by gfogle** [comment] 2017-06-01 17:11
@sandy081 I'm not using the jasmine extension afaik. It appears, to me, to be defaulted in vscode somehow

<img width="226" alt="screen shot 2017-06-01 at 1 11 06 pm" src="https://cloud.githubusercontent.com/assets/7015773/26691616/cca16676-46cb-11e7-9948-6d2d4adf41b4.png">

**Comment by sandy081** [comment] 2017-06-09 07:35
@gfogle Can you please try to disable all extensions and try? You can disable all extensions from command pallette - Disable all installed extensions.

@chiangf You can disable an extension by clicking the gear icon next to it and you will see options to disable.

Thanks

**Comment by chiangf** [comment] 2017-06-09 17:17
@sandy081 I've disabled all extensions and can still repro. I also don't have any extensions that would affect this.

If I type `expect(something).to`, intellisense pops up suggesting `.toBe` and if I hit `.`, it autocompletes with `toBe`.

![screen shot 2017-06-09 at 1 16 34 pm](https://user-images.githubusercontent.com/1329204/26986546-f08c6c48-4d15-11e7-8a0e-8ff582a19a30.png)

**Comment by sandy081** [comment] 2017-06-12 14:56
@chiangf Thanks for confirmation. We will look into it.

**Comment by mjbvz** [comment] 2017-06-13 01:09
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/15359 We seem to be picking up the global typings from `jasmine` even though you are not using it. 

You should be able to write:

```js
var expect = chai.expect;

...

expect('x').to
```

to get the chai intellisense.

To disable the typings from jasmine, you can also explicitly exclude them. Just create a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project with the contents:

```json
{
    "compilerOptions": { },
    "typeAcquisition": {
        "include": [
            "chai"
        ],
        "exclude": [
            "jasmine"
        ]
    }
}
```

Let me know if this does not work

**Closed by mjbvz** 2017-06-13 01:09 UTC
Labels: javascript, typescript, upstream

**Comment by INRIX-benjamin-okeefe** [comment] 2017-10-03 17:09
@mjbvz - I appreciate the suggestion, but neither the `var expect = chai.expect;` or the jsconfig.json options seem to be working for me.

Has anyone else had success with either of these methods?
