### ISSUE TITLE
(macOS)Text cursor is blinking on unfocused window

### ISSUE THREAD

**Issue by eldenchen** [microsoft/vscode#86974] opened 2019-12-14 05:33 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Open two windows in Desktop 1
2. Switch to Desktop 2 and then switch back

This issue is not caused by the new release, it has been a long time.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|24.00GB (11.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.9
vscode-fix-checksums|leh|1.1.0
cpptools|ms-|0.26.2
Go|ms-|0.11.9

</details>

**Comment by RMacfarlane** [comment] 2019-12-15 01:41
@eldenchen Does this still reproduce with all extensions disabled?

**Comment by eldenchen** [comment] 2019-12-15 05:54
Yes, it does. Tried to launch using command line with flag --disable-extensions.

**Comment by alexdima** [comment] 2020-01-15 16:03
Duplicate of #82326

**Closed by alexdima** 2020-01-15 16:03 UTC
Labels: needs more info
