### ISSUE TITLE
When launching code with --disable-extensions, all extensions show up in the Enabled view

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39823] opened 2017-12-06 19:56 UTC
- Run `code-insiders --disable-extensions`
- Open the extensions viewlet
- Using the menu, select `Show Enabled Extensions`

**Expected**: No extensions should show up in the viewlet
**Actual**: All installed extensions (other than the ones that may have been disabled using the UI before) show up in the viewlet

**Comment by sandy081** [comment] 2017-12-07 08:43
Duplicate of #38597

**Closed** 2017-12-07 08:43 UTC
Labels: *duplicate, bug, extensions

**Comment by ramya-rao-a** [comment] 2017-12-07 16:51
Well, its not really a duplicate though the root cause might be the same and the same fix, fixed both issues.

Regardless, verified the fix by running from source
