### ISSUE TITLE
symbol color scheme error if it contains a keyword for cpp source

### ISSUE THREAD

**Issue by eypsum** [Microsoft/vscode#70752] opened 2019-03-19 12:04 UTC
- VSCode Version:  code-insiders_1.33.0-xxxxx_amd64
- OS Version: Ubuntu Gnome 16.04

If a function name contains a keyword(e.g deleteItem) and it is after any symbol 
 keyword part of that name has not a color for function but keyword.

![delete_keyword_color_error_2019-03-19 20-45-06](https://user-images.githubusercontent.com/20113770/54604620-86dbba00-4a8a-11e9-93c9-f08038810a6a.png)

![not_variable_color_error_2019-03-19 20-43-26](https://user-images.githubusercontent.com/20113770/54604624-8c390480-4a8a-11e9-9a8c-3fe25636d8f3.png)

**Comment by eypsum** [comment] 2019-03-20 02:39
I have just 12 extensions.
I think that has not the problem till earlier vscode.
I don't know what extension cause the problem. so I uninstalled several extensions and removed all file of those.
Now I just have bellow and the problem is continue.
![my_extension_2019-03-20 11-07-53](https://user-images.githubusercontent.com/20113770/54655293-c515bf80-4b04-11e9-968c-5c9b915c4dd6.png)

**Comment by ian-h-chamberlain** [comment] 2019-04-05 14:27
I am able to reproduce this on VSCode Version 1.33.0 (1.33.0 – 0dd516dd412d42323fc3464531b1c715d51c4c1a) with all extensions disabled.

OS version:  macOS Mojave 10.14.3 (18D109)

![Screen Shot 2019-04-05 at 10 20 43](https://user-images.githubusercontent.com/11131775/55634543-ba0d9100-578c-11e9-9620-9c636ec15a58.png)

I believe this was introduced with VScode 1.33 or 1.32 as I never experienced this previously before updating VSCode. Also, function parameters are highlighted now, which they were not previously – I'm guessing that functionality came from the same changeset.

@isidorn Please consider re-opening this issue, it is not caused by an extension as C++ syntax highlighting is performed by VSCode itself.

**Comment by isidorn** [comment] 2019-04-05 15:42
Sure, let's reopen and investigate.

**Comment by alexr00** [comment] 2019-04-08 07:58
Fixed in insiders 1.34.

**Closed by alexr00** 2019-04-08 07:58 UTC
