### ISSUE TITLE
VSC Icon

### ISSUE THREAD

**Issue by thucxuong** [Microsoft/vscode#71039] opened 2019-03-24 15:44 UTC
Issue Type: <b>Bug</b>

I update my MAC to Mojave, the VSC Icon becomes a tiny dot on the launch bar. Please help.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|-psn_0_3388219|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
lorem-ipsum|Tyr|1.2.0
react-pure-to-class-vscode|ang|1.1.8
vscode-custom-css|be5|3.0.3
turbo-console-log|Cha|1.2.17
language-postcss|cpy|1.0.5
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
vscode-random|jre|1.6.0
string-manipulation|mar|0.3.1
vscode-scss|mrm|0.6.2
vetur|oct|0.17.0
indent-rainbow|ode|7.4.0
laravel-blade|one|1.18.0
advanced-new-file|pat|1.2.0
code-settings-sync|Sha|3.2.7
stylelint|shi|0.48.0
bootstrap4-vscode|the|6.1.0
ReactSnippets|xab|2.3.0
markdown-pdf|yza|1.2.0

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2019-03-24 18:06
Duplicate of #59578

**Closed** 2019-03-25 09:04 UTC
Labels: *duplicate
