### ISSUE TITLE
Upon zooming the window, codelens positioning is lost

### ISSUE THREAD

**Issue by Yantrio** [Microsoft/vscode#14980] opened 2016-11-04 12:35 UTC
- VSCode Version: 1.7.1
- OS Version: osx el capitan

Steps to Reproduce:

1. open file with codelens
2. zoom window (cmd + plus)
3. watch codelens fly away

![screen shot 2016-11-04 at 12 31 33](https://cloud.githubusercontent.com/assets/237469/20005615/36e74b30-a28b-11e6-8cf8-de7e2e7f3146.png)

**Comment by con-ssc** [comment] 2016-11-04 13:32
I can confirm that for windows as well, for me the code lens just disappear

**Comment by jdforsythe** [comment] 2016-11-04 20:17
I can also confirm this is an issue - seems to be a new issue with 1.7.1 on Windows 10.

https://github.com/vscode-contrib/vscode-versionlens/issues/23

Regardless of whether you're zoomed in or out and to what degree, the mis-positioned text is always in the same place. The only time it changes is when you reset the zoom, at which point it lines up as expected.

**Comment by alexandrudima** [comment] 2016-11-07 15:57
Duplicate of #14949.

**Closed by alexandrudima** 2016-11-07 15:57 UTC
