### ISSUE TITLE
Refactor: move to new file does not work

### ISSUE THREAD

**Issue by jackfranklin** [Microsoft/vscode#51586] opened 2018-06-11 08:11 UTC
Issue Type: <b>Bug</b>

I have an `index.js` file with two classes in ( I can share the github repo if that's useful)

```js
class Field {...}

class Builder {...}
```

I am able to right click on the class name, select `Refactor` and then select `Move to new file`. However, when I do that, nothing happens. There are no errors in the developer tools, but no code is changed or new files created.

It's worth noting that other refactors (highlight some code + extract method) _do_ work just fine.

I am running code with `--disable-extensions` to ensure it's not a problem with a package.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment] 2018-06-11 15:13
Can you please:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem 
1. Open the output panel and go to the `typescript` section

Are there any errors or stack traces near the bottom? 

If you can share the complete repo I can also investigate this myself

**Comment by jackfranklin** [comment] 2018-06-11 17:22
```
[Trace  - 18:11:29] Sending request: quickinfo (2407). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/jack/git/test-data-bot/src/index.js",
    "line": 27,
    "offset": 9
}
[Trace  - 18:11:29] Response received: quickinfo (2407). Request took 1 ms. Success: true 
Result: {
    "kind": "class",
    "kindModifiers": "",
    "start": {
        "line": 27,
        "offset": 7
    },
    "end": {
        "line": 27,
        "offset": 14
    },
    "displayString": "class Builder",
    "documentation": "",
    "tags": []
}
[Trace  - 18:11:31] Sending request: getApplicableRefactors (2408). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/jack/git/test-data-bot/src/index.js",
    "startLine": 27,
    "startOffset": 7,
    "endLine": 27,
    "endOffset": 14
}
[Trace  - 18:11:31] Response received: getApplicableRefactors (2408). Request took 1 ms. Success: true 
Result: [
    {
        "name": "Move to a new file",
        "description": "Move to a new file",
        "actions": [
            {
                "name": "Move to a new file",
                "description": "Move to a new file"
            }
        ]
    }
]
[Trace  - 18:11:32] Sending request: getEditsForRefactor (2409). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/jack/git/test-data-bot/src/index.js",
    "startLine": 27,
    "startOffset": 7,
    "endLine": 27,
    "endOffset": 14,
    "refactor": "Move to a new file",
    "action": "Move to a new file"
}
[Trace  - 18:11:32] Response received: getEditsForRefactor (2409). Request took 5 ms. Success: false . Message: Error processing request. Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at isExported (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88703:56)
    at addExportToChanges (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88686:17)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88474:25
    at Map.forEach (native)
    at SymbolSet.forEach (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88626:26)
    at getNewFileImportsAndAddExportInOldFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88464:39)
    at getNewStatements (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88267:20)
    at doChange (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88211:105)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88182:94
    at Function.ChangeTracker.with (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82512:17)
    at Object.getEditsForAction (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88182:62)
    at Object.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83240:41)
    at Object.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90541:32)
    at IOSession.Session.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97013:59)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95906:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97221:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97250:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98456:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 18:11:32] 'getEditsForRefactor' request failed with error.
Error processing request. Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at isExported (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88703:56)
    at addExportToChanges (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88686:17)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88474:25
    at Map.forEach (native)
    at SymbolSet.forEach (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88626:26)
    at getNewFileImportsAndAddExportInOldFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88464:39)
    at getNewStatements (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88267:20)
    at doChange (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88211:105)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88182:94
    at Function.ChangeTracker.with (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82512:17)
    at Object.getEditsForAction (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88182:62)
    at Object.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83240:41)
    at Object.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90541:32)
    at IOSession.Session.getEditsForRefactor (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97013:59)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:95906:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97221:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97230:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97250:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98456:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Trace  - 18:11:32] Sending request: getApplicableRefactors (2410). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/jack/git/test-data-bot/src/index.js",
    "startLine": 27,
    "startOffset": 7,
    "endLine": 27,
    "endOffset": 14
}
[Trace  - 18:11:32] Response received: getApplicableRefactors (2410). Request took 1 ms. Success: true 
Result: [
    {
        "name": "Move to a new file",
        "description": "Move to a new file",
        "actions": [
            {
                "name": "Move to a new file",
                "description": "Move to a new file"
            }
        ]
    }
```

This is the full output from doing this. Note that I opened this issue on OS X but I'm currently on the same repo on windows and it's the same thing - I can do the same on OS X if that's useful.

The repo is this one: https://github.com/jackfranklin/test-data-bot

**Comment by mjbvz** [comment] 2018-06-12 01:51
Thank you. Looks like this is fixed in typescript@next

You can follow [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to upgrade today. We'll also pick up TS 3.0 (the current @next) in the July release of VS code

**Closed by mjbvz** 2018-06-12 01:51 UTC
Labels: needs more info, new release

**Comment by jackfranklin** [comment] 2018-06-12 06:51
@mjbvz awesome, thank you for your speedy reply and help :)
