### ISSUE TITLE
Must click inside minimap active area to have "hot scrolling"

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#33014] opened 2017-08-23 08:55 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063

If you click and hold the mouse button outside of the active minimap area, the area doesn't follow when you keep moving the mouse after.

![vs_code_minimap_scroll](https://user-images.githubusercontent.com/1578924/29607374-4d71ee7c-87f1-11e7-955a-f202f0d93076.gif)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-11-27 10:25
Duplicate of #21708

**Closed by alexandrudima** 2017-11-27 10:25 UTC
Labels: editor, editor-minimap
