### ISSUE TITLE
Php variables turns into HTML tags

### ISSUE THREAD

**Issue by kupoback** [Microsoft/vscode#17856] opened 2016-12-27 14:37 UTC
- VSCode Version: 1.8.1
- OS Version: osX 10.12
- Extensions installed: 
    - None, base VSC install

Steps to Reproduce:

1. Open up a .php file
2. Within a php file (in my case a functions file for Wordpress) when I go to create a variable, eg: `$sm_content`, it turns it into `<1sm_content></1sm_content>` upon hitting tab. Hitting space before hitting tab does not cause this, only when the cursor is right up against the variable name.
3. Restarted VSC, still same results.

**Comment by smallp** [comment] 2016-12-27 15:47
This feature is for HTML. However, sometimes people may write HTML in PHP file, so this feature should not be removed.

**Comment by kupoback** [comment] 2016-12-27 15:49
I do write HTML in php, however it's a bit of an annoyance that it see anything with a $ and declares it automatically an HTML element. Is there not a way to get this to know current HTML(5) tags and use it on those? 

I doubt there is an `<sm_content>` tag, unless I'm mistaken.

**Comment by smallp** [comment] 2016-12-27 16:15
Nope. It will treat any words as a tap. So maybe VSCode could check if it begins with '$' first and then decide whether turn to a tap or not.

**Comment by kupoback** [comment] 2016-12-27 16:17
Interesting, as my other variables `$value` and `$field` didn't trigger those events.

Also, on a side note, in Atom, this feature doesn't happen in .php with HTML elements in it. I know the two are built within the same framework. Just curious if I missed a setting.

**Comment by kupoback** [comment] 2016-12-28 14:21
Is there a way to rewrite the keymap for tab to not work in .php files?
    
    {
        "key": "tab",  "command": "tab",
                               when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" 
    }

**Comment by aeschli** [comment] 2016-12-28 18:59
Tab invokes the emmet completion. FYI @ramya-rao-a

**Comment by ramya-rao-a** [comment] 2016-12-30 02:08
Duplicate of #7913

@kupoback To disable emmet for php you can add the following setting:

``` json
"emmet.excludeLanguages": ["php"]
```

**Closed by ramya-rao-a** 2016-12-30 02:08 UTC

**Comment by ramya-rao-a** [comment] 2017-08-10 17:50
No need to add `php` to `emmet.excludeLanguages` anymore.

With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

In this particular case, emmet will not provide any suggestions either

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
