### ISSUE TITLE
[bug] invisible underscore in integrated-terminal

### ISSUE THREAD

**Issue by ilnuribat** [Microsoft/vscode#38133] opened 2017-11-11 22:12 UTC
Couldn't see underscore in integrated-terminal. Other symbols are visible, but underscore is just empty space
f.e.: `npm run migrations_down`
visible like `npm run migrations down`
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic
- Ubuntu 16.04

**Comment by maxibanki** [comment] 2017-11-11 23:31
Duplicate of #35901

**Comment by bawolk** [comment] 2017-11-14 04:19
Same problem here.  But if you zoom out (Ctrl- -) or in (Ctrl +) the underscore becomes visible!

**Comment by nocke** [comment] 2017-11-15 17:59
Got the same issue. Ubuntu-Mate. Appeared first on VSCode 1.18.0.  Only one specific size, only on command-line (`$> cd _posts_` for example), not in listings (`ls`) for some reason.

**Quick work around:** Copy `editor.fontFamily` to your user settings, remove first Family, thus remaining is:
```
"editor.fontFamily": "'monospace', monospace, 'Droid Sans Fallback'"
```

Possibly [came through this PR](https://github.com/Microsoft/vscode/pull/34947)?

**Comment by suonto** [comment] 2017-11-22 14:52
Add `"window.zoomLevel": -0.001` for workaround

**Comment by nocke** [comment] 2017-11-23 10:08
It's worth noting, it's far more likely to happen on comannd line _entry_ than _output_ for some reason.
![selection_221](https://user-images.githubusercontent.com/21154106/33167603-5188a894-d03e-11e7-8158-a4804cdc596b.png)

(So, perhaps something is not about character rendering itself but something related to line-height?  Lineheights chosen too small sometimes clip typo (all the way from word to css...) and the underscore would be the first victim here...)

**Comment by robertloo** [comment] 2017-11-25 16:44
Same issue here. I used @suonto workaround

**Comment by Tyriar** [comment] 2017-12-11 11:17
#35901

**Closed** 2017-12-11 11:17 UTC
Labels: *duplicate, integrated-terminal
