### ISSUE TITLE
Broken JsDoc intellisense

### ISSUE THREAD

**Issue by VitalySenko** [Microsoft/vscode#24942] opened 2017-04-18 09:46 UTC
- VSCode Version: 1.11.2 (1.11.2)
6eaebe3b9c70406d67c97779468c324a7a95db0e

- OS Version: macOS Sierra Version 10.12.4

Steps to Reproduce:

1. write typedef jsdoc
2. try to get intellisense
<img width="657" alt="screen shot 2017-04-18 at 12 45 00" src="https://cloud.githubusercontent.com/assets/12730311/25124611/e956edc2-2434-11e7-9d38-19ad906d25b8.png">

**Comment by epicgirl1998** [comment] 2017-04-18 13:45
don't know if it's by design but it seems to be ignoring the properties unless the typedef has the type `Object` (capital O) or if the type is left out

so these work:

* `@typedef {Object} MyType`
* `@typedef MyType`

and these don't work (properties are ignored):

* `@typedef {object} MyType`
* `@typedef {{}} MyType`
* `class Test {}` + `@typedef {Test} MyType`

![file](https://cloud.githubusercontent.com/assets/25940153/25133424/53414c12-2455-11e7-92c8-b126e7e0d527.png)

**Comment by mjbvz** [comment] 2017-04-18 16:06
This seems like a bug on the TypeScript project that powers both our JS and TS language support. I've opened https://github.com/Microsoft/TypeScript/issues/15250 to track this.

Also, thanks for the workaround @epicgirl1998! Using `Object` does seem to work. You can also use object literal notation:

```js
/**
 * @typedef {{myProp: string}} MyType
 */
```

Closing as upstream

**Closed by mjbvz** 2017-04-18 16:06 UTC
Labels: javascript, typescript, upstream
