### ISSUE TITLE
There's no global "busy" or "executing" indicator while a cell is running, but it's almost there? :)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#130811] opened 2021-07-01 07:09 UTC
- Open a python script with cells
- Execute a cell to open the interactive window. The cell should be a simple sleep(10) or whatever. 

While there's an infinite progress bar animating above the cell and a cell status bar with a timer, there's no other global indication that a cell is running. 

Or is there? 

I would think that the "Interrupt kernel" button would be either grayed out or invisible while the kernel is executing code. This is currently not the case, but was this the ultimate intent?

**Comment by greazer** [comment] 2021-08-14 06:55
Per quick discussion with @rebornix, I think a progress bar at the top of the IW is appropriate.

**Comment by tanhakabir** [comment] 2021-10-06 04:02
Duplicate of https://github.com/microsoft/vscode/issues/130611

**Closed by tanhakabir** 2021-10-06 04:02 UTC
Labels: notebook, papercut :drop_of_blood:, interactive-window
