### ISSUE TITLE
Debugger doesnt compile TypeScript for the second time

### ISSUE THREAD

**Issue by Sardonyx78** [microsoft/vscode#102604] opened 2020-07-15 15:11 UTC
- VSCode Version: 1.48.0-insider
- OS Version: Windows 10 Pro | 10.0.18363 N/A Build 18363

When I try to debug some code, it doesnt compiles the new version and directly executes & debuges

Steps to Reproduce:

1. Write a code in TS
2. Compile and run with the debugger
3. Watch your old code running.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by connor4312** [comment] 2020-07-15 16:17
/duplicate of https://github.com/microsoft/vscode/issues/102296

General tip: you can use `tsc -w` to watch your source code and incrementally compile, which is much faster than rebuilding from scratch each time.

Here's a task:

```
{
  "label": "npm: watch",
  "type": "npm",
  "script": "watch",
  "problemMatcher": ["$tsc-watch"],
  "presentation": {
    "reveal": "silent"
  },
  "group": "build",
  "isBackground": true
}
```

That runs my npm script containing `tsc -w`

**Closed** 2020-07-15 16:18 UTC
Labels: *duplicate

**Comment by connor4312** [comment] 2020-07-15 17:11
Solution here: https://github.com/microsoft/vscode/issues/102296#issuecomment-658889772
