### ISSUE TITLE
discontinuousness of indent guide lines

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#78841] opened 2019-08-09 23:17 UTC
<img width="414" alt="1" src="https://user-images.githubusercontent.com/11925432/62274582-bfe15d80-b472-11e9-9840-28536fdd4522.png">

https://github.com/OmniSharp/omnisharp-vscode/issues/3204

**Comment by alexandrudima** [comment] 2019-08-12 13:46
Duplicate of #9604

**Closed by alexandrudima** 2019-08-12 13:46 UTC
