### ISSUE TITLE
Copy/Paste using shortcut ctrl+c/ctrl+v functionality missing (add such functionality, it's a cool feature in any terminal)

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/vscode#7119] opened 2016-06-02 06:58 UTC
- VSCode Version: 1.2.0 - insider
- OS Version: Elementary OS

Steps to Reproduce:

1. In elementary os, I am able to use ctrl+c/ctrl+v within terminal, This functionality is missing in integrated terminal.
2. So please add direct paste and copy functionality in integrated terminal. It's a cool feature.

**Comment by Tyriar** [comment] 2016-06-02 07:19
Duplicate of https://github.com/Microsoft/vscode/issues/6451

**Closed by Tyriar** 2016-06-02 07:19 UTC
