### ISSUE TITLE
Alt-Key and Ubuntu 16.04

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57354] opened 2018-08-28 09:36 UTC
re  #57316 

* test the mnemonics on ubuntu 16.04
* press alt and notice how the ubuntu menu shows
* this is sooo confusing and conflicting with the press and hold behaviour of VS Code that we should consider not enabling it

**Comment by sbatten** [comment] 2018-10-12 21:41
@jrieken , finally got around to investigating this issue. A couple things
1) Even if you set the titlebar to native and just use mnemonics, you can get into a state where the HUD pops up which is poorly implemented because mnemonics are still natively handled with the same alt-key as the HUD default key.
2) We don't use register a true menu bar so the HUD is useless on custom. 
3) As a workaround, the HUD trigger key can be changed which seems reasonable if you intend to use mnemonics as they would be broken in other applications as well.

All in all I think this can be closed as designed since in the months it has been opened, I have not seen any duplicate sentiment.

**Closed by sbatten** 2018-10-12 21:41 UTC
Labels: bug, workbench-menu
