### ISSUE TITLE
Deleting text creates a ghost URL underline

### ISSUE THREAD

**Issue by ShaynAli** [microsoft/vscode#80075] opened 2019-08-29 21:44 UTC
- VSCode Version: `1.37.1`
- OS Version: macOS Mojave `10.14.5`

Steps to Reproduce:

1. Write some text into a VS code window like the following:
![```example text
more example text
https://www.example.com```](https://user-images.githubusercontent.com/17167726/63976536-8acf2780-ca7f-11e9-8251-6056a98add19.png)
2. Delete the first two lines:
![```example text
more example text
https://www.example.com```](https://user-images.githubusercontent.com/17167726/63976597-adf9d700-ca7f-11e9-9edd-7813af5245b3.png)
3. Note the odd ghost underline appearing where line 3 was
![```example text
more example text
https://www.example.com```](https://user-images.githubusercontent.com/17167726/63976643-c1a53d80-ca7f-11e9-8d02-60f029738b3f.png)

Note that after following the above steps, if the cursor is placed on the line with the URL the ghost underline flashes. The ghost underline appears wherever the URL originally was, so deleting more lines will result in the ghost underline appearing farther under the last line of text.

This issue does _not_ occur when there is a line after the original URL, e.g. in this case:
![image](https://user-images.githubusercontent.com/17167726/63978566-9ec95800-ca84-11e9-992c-8a8267056631.png)

This issue also occurs on `1.38.0-insider`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2019-09-10 12:25
Duplicate of #48321

**Closed by alexandrudima** 2019-09-10 12:25 UTC
