### ISSUE TITLE
Vs Code Blur

### ISSUE THREAD

**Issue by Saiken9** [Microsoft/vscode#56470] opened 2018-08-15 13:22 UTC
Issue Type: <b>Bug</b>

i have blur on my vs code,it gets worse when i enter settings

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.48GB (2.67GB free)|
|Process Argv|C:\Users\Tajeddine\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.59
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.6.1
bootstrap-4-cdn-snippet|eve|1.1.2
html-slim-scss-css-class-completion|gen|1.0.1
live-server-preview|neg|0.1.2
vscode-icons|rob|7.25.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment] 2018-08-15 13:44
Duplicate of #51789

**Closed** 2018-08-15 13:44 UTC
Labels: *duplicate, new release
