### ISSUE TITLE
Extensions not activating in Insiders

### ISSUE THREAD

**Issue by ssmall** [microsoft/vscode#127012] opened 2021-06-23 17:59 UTC
Issue Type: <b>Bug</b>

1. Open existing project in VSCode and confirm that extensions activate normally
1. Use "File > Open" to open a new folder that has not been opened in VSCode before
1. When prompted whether to trust the contents of the new folder, say yes

## Expected Behavior

All extensions activate normally

## Actual Behavior

Most extensions are disabled until window is manually reloaded.

https://user-images.githubusercontent.com/641091/123147368-cc2e8500-d413-11eb-8970-0f00e4f79b28.mp4

## More Info

VS Code version: Code - Insiders 1.58.0-insider (Universal) (9744231fc12f1aed21089180b3f0394d694bd2a2, 2021-06-23T05:12:16.478Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 99efad74-0ad6-4dce-89cf-66f760e85241|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cloudcode|goo|1.12.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.7.963708582

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by kschaab** [comment] 2021-06-24 15:40
I can reproduce this after upgrading insiders from
```
Version: 1.58.0-insider (Universal)
Commit: 6afedfdad59d1f1ba4b614341d21c67775e158a9
Date: 2021-06-21T05:14:03.949Z (3 days ago)
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

to
```
Version: 1.58.0-insider (Universal)
Commit: 3caebff71e514ece73b125468881d102e767ee4d
Date: 2021-06-24T05:14:29.975Z (10 hrs ago)
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Relevant logs:
```
[2021-06-24 08:37:53.075] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
    at Object.r [as canceled] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
    at h._remoteCall (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12947)
    at Proxy._.<computed>.D.charCodeAt._.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9470)
    at D.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:36845)
    at Object.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:57176)
    at useProxySettings (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-06-24 08:37:54.169] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
    at Object.r [as canceled] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
    at h._remoteCall (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12947)
    at Proxy._.<computed>.D.charCodeAt._.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9470)
    at D.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:36845)
    at Object.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:57176)
    at useProxySettings (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[2021-06-24 08:37:54.174] [exthost] [error] ProxyResolver#resolveProxy Canceled: Canceled
    at Object.r [as canceled] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
    at h._remoteCall (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12947)
    at Proxy._.<computed>.D.charCodeAt._.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9470)
    at D.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:36845)
    at Object.resolveProxy (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:57176)
    at useProxySettings (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:159:16)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:107:13
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:335:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    ```

**Comment by lszomoru** [comment] 2021-06-25 07:59
This is a duplicate of #127067. Issue is already been fixed in the latest Insiders release.

**Closed by lszomoru** 2021-06-25 07:59 UTC
Labels: bug, workspace-trust
