### ISSUE TITLE
Markdown Incorrect Colorization of Fenced Code Blocks

### ISSUE THREAD

**Issue by azu** [Microsoft/vscode#17787] opened 2016-12-24 02:59 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0

Put some text before fenced Code Blocks and break syntax highlight of code block.

**OK**:

    # Arbitrary Piece of code

    ```c
    #include <stdio.h>

    int main(void)
    {
        puts("hello world");
        return 0;
    }
    ```

![test md - vscode-textlint-example 2016-12-24 11-54-29](https://cloud.githubusercontent.com/assets/19714/21464907/c4bdbbb8-c9cf-11e6-9d58-0748c685a4ae.png)

**NG**:

    # Arbitrary Piece of code

    text <= break syntax highlight
    ```c
    #include <stdio.h>

    int main(void)
    {
        puts("hello world");
        return 0;
    }
    ```

![test md - vscode-textlint-example 2016-12-24 11-53-37](https://cloud.githubusercontent.com/assets/19714/21464901/b207ad58-c9cf-11e6-8ab8-2e2975280ca0.png)

This case is CommonMark spec's [Example 108](http://spec.commonmark.org/0.26/#example-108).

> Other blocks can also occur before and after fenced code blocks without an intervening blank line:
> http://spec.commonmark.org/0.26/#example-108

**Comment by mjbvz** [comment] 2016-12-29 00:28
Closing as duplicate of #12946

**Closed by mjbvz** 2016-12-29 00:28 UTC
Labels: duplicate, markdown
