### ISSUE TITLE
Terminals broken in Remote-SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#201149] opened 2023-12-18 18:30 UTC
The terminal is just empty

<img width="769" alt="image" src="https://github.com/microsoft/vscode/assets/323878/b5f24a84-d81d-43ca-b979-a613c1274f8d">

I was worried that I had broken it from verification when I was messing with the permissions for `/etc/shells` but that should be back to normal, and this works in stable.

I don't see any obvious errors. The Pty Host log:

```
2023-12-18 10:17:53.836 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/zsh
2023-12-18 10:17:53.836 [trace] [RPC Request] PtyService#getDefaultSystemShell(2)
2023-12-18 10:17:53.836 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/zsh
2023-12-18 10:17:54.009 [trace] [RPC Request] PtyService#getDefaultSystemShell(2)
2023-12-18 10:17:54.010 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/zsh
2023-12-18 10:17:54.010 [trace] [RPC Request] PtyService#getDefaultSystemShell(2)
2023-12-18 10:17:54.010 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/zsh
2023-12-18 10:18:08.733 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.733 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.734 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.734 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.734 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.734 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.734 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.734 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.735 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.735 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.735 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.735 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.735 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.735 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.735 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.736 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.736 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.736 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.736 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.736 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.736 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.736 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.737 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.737 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.737 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.737 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.737 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.737 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.737 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.737 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.738 [trace] [RPC Request] PtyService#getDefaultSystemShell(3)
2023-12-18 10:18:08.738 [trace] [RPC Response] PtyService#getDefaultSystemShell /bin/bash
2023-12-18 10:18:08.779 [trace] [RPC Request] PtyService#getEnvironment()
2023-12-18 10:18:08.780 [trace] [RPC Response] PtyService#getEnvironment {"COMMAND_MODE":"unix2003","DISPLAY":"/private/tmp/com.apple.launchd.jwY01r8bVv/org.macosforge.xquartz:0","HOME":"/Users/roblou","LOGNAME":"roblou","MallocNanoZone":"0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","PATH":"/usr/bin:/bin:/usr/sbin:/sbin","SHELL":"/bin/zsh","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.Y57f22F9yF/Listeners","TMPDIR":"/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/","USER":"roblou","VSCODE_AMD_ENTRYPOINT":"vs/platform/terminal/node/ptyHostMain","VSCODE_CODE_CACHE_PATH":"/Users/roblou/Library/Application Support/Code - Insiders/CachedData/279872bd965e4030c81129a9bf1ce1710ff7cd55","VSCODE_CRASH_REPORTER_PROCESS_TYPE":"ptyHost","VSCODE_CWD":"/","VSCODE_IPC_HOOK":"/Users/roblou/Library/Application Support/Code - Insiders/1.86-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"osLocale\":\"en\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_PID":"7864","VSCODE_PIPE_LOGGING":"true","VSCODE_VERBOSE_LOGGING":"true","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"application.com.microsoft.VSCodeInsiders.283077056.283077062","__CFBundleIdentifier":"com.microsoft.VSCodeInsiders","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0"}
```

main:

```
2023-12-18 10:15:32.191 [warning] [perf] profiling DONE 2e8f0da7-a6b7-4ca0-99b9-3fedb8648ff4
2023-12-18 10:15:33.604 [warning] [perf] profiling DONE d07e5bd4-72dc-4c3b-8951-83fec3efcc3c
2023-12-18 10:15:49.281 [info] Extension host with pid 8088 exited with code: 0, signal: unknown.
2023-12-18 10:17:11.594 [info] Extension host with pid 9125 exited with code: 0, signal: unknown.
2023-12-18 10:17:50.496 [info] Extension host with pid 9612 exited with code: 0, signal: unknown.
2023-12-18 10:18:00.555 [warning] [perf] profiling STARTED 0cf137f8-8f8b-4bbc-a008-cb3320844853
2023-12-18 10:18:01.575 [info] Extension host with pid 9913 exited with code: 0, signal: unknown.
2023-12-18 10:18:05.636 [warning] [perf] profiling DONE 0cf137f8-8f8b-4bbc-a008-cb3320844853
2023-12-18 10:30:12.211 [info] Extension host with pid 9965 exited with code: 0, signal: unknown.
2023-12-18 10:30:26.422 [info] Extension host with pid 12407 exited with code: 0, signal: unknown.
```

lmk if I can provide any other logs

**Comment by roblourens** [comment] 2023-12-18 18:38
Ah here's one more useful, just capturing it when the server starts up

```
[10:37:11.581] [server] [IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
[10:37:11.582] [server] Require stack:
[10:37:11.582] [server] - /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/unixTerminal.js
[10:37:11.583] [server] - /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/index.js
[10:37:11.584] [server] [IPC Library: Pty Host] innerError Error: Cannot find module '../build/Debug/pty.node'
[10:37:11.585] [server] Require stack:
[10:37:11.586] [server] - /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/unixTerminal.js
[10:37:11.586] [server] - /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/index.js
[10:37:11.586] [server]     at require (node:internal/modules/cjs/helpers:121:18)
[10:37:11.587] [server]     at Object.<anonymous> (/home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/index.js:14:20)
[10:37:11.587] [server]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[10:37:11.587] [server]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[10:37:11.587] [server]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[10:37:11.588] [server]     at Module._load (node:internal/modules/cjs/loader:960:12)
[10:37:11.588] [server]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[10:37:11.588] [server]     at require (node:internal/modules/cjs/helpers:121:18)
[10:37:11.589] [server]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[10:37:11.589] [server] [IPC Library: Pty Host] Loading "node-pty" failed
[10:37:11.590] [server] [IPC Library: Pty Host] Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/build/Release/pty.node)
[10:37:11.591] [server]     at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
[10:37:11.591] [server]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[10:37:11.591] [server]     at Module._load (node:internal/modules/cjs/loader:960:12)
[10:37:11.591] [server]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[10:37:11.592] [server]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[10:37:11.592] [server]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[10:37:11.592] [server]     at Module._load (node:internal/modules/cjs/loader:960:12)
[10:37:11.593] [server]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[10:37:11.593] [server]     at require (node:internal/modules/cjs/helpers:121:18)
[10:37:11.593] [server]     at Object.<anonymous> (/home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/node_modules/node-pty/lib/index.js:14:20)
[10:37:11.593] [server]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[10:37:11.593] [server]     at f._resolve (/home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/out/vs/loader.js:6:452)
[10:37:11.594] [server]     at Object.<anonymous> (/home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/out/vs/platform/terminal/node/ptyHostMain.js:43:42642)
[10:37:11.594] [server]     at n._createAndEvalScript (/home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/out/vs/loader.js:4:2506)
[10:37:11.594] [server]     at /home/roblou/.vscode-server-insiders/cli/servers/Insiders-279872bd965e4030c81129a9bf1ce1710ff7cd55/server/out/vs/loader.js:4:2147
[10:37:11.594] [server]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by meganrogge** [comment] 2023-12-18 18:38
duplicate of https://github.com/microsoft/vscode/issues/200754

**Comment by roblourens** [comment] 2023-12-18 18:42
@deepak1556 I see https://github.com/microsoft/vscode/issues/192685 and https://github.com/microsoft/vscode-remote-release/issues/8952, but not sure what the current status is, do you expect an error like that in the latest Insiders?

**Comment by meganrogge** [comment] 2023-12-18 18:50
also cc @rzhao271

**Closed** 2023-12-18 20:10 UTC
