### ISSUE TITLE
blue icon color was good. orange is barely visible on windows 7 aero.

### ISSUE THREAD

**Issue by ulvido** [Microsoft/vscode#36262] opened 2017-10-14 05:26 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-16 08:05
Duplicate of #35783

**Closed by egamma** 2017-10-16 08:05 UTC
Labels: duplicate, new release
