### ISSUE TITLE
Debug Console output not printing output at correct interval

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5668] opened 2016-04-22 19:17 UTC
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

I was testing in Powershell but I was able to reproduce for Javascript.
1. Add the below code and debug with the Powershell extension
2. Observe the speed of the output numbers.

With Start-Sleep set at 100ms output prints 6 lines per refresh instead of printing one line every 100ms. Set at 200ms, 3 lines are printed per refresh, etc.

```powershell
function Write-Item($itemCount) {
    $i = 1

    while ($i -le $itemCount) {
        $str = "Output $i"
        Write-Output $str

        # In the gutter on the left, right click and select "Add Conditional Breakpoint"
        # on the next line. Use the condition: $i -eq 25
        $i = $i + 1

        # Slow down execution a bit so user can test the "Pause debugger" feature.
        Start-Sleep -Milliseconds 100
    }
}

# Do-Work will be underlined in green if you haven't disable script analysis.
# Hover over the function name below to see the PSScriptAnalyzer warning that "Do-Work"
# doesn't use an approved verb.
function Do-Work($workCount) {
    Write-Output "Doing work..."
    Write-Item $workcount
    Write-Host "Done!"
}

Do-Work 50


```

**Comment by dbaeumer** [comment] 2016-04-23 19:30
@isidorn I don't know if this is us or powershell. Starting with you.

**Comment by isidorn** [comment] 2016-04-25 06:57
This is because we have a [throttling of output](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/repl.ts#L48) otherwise the tree could be refreshed every ms and this could cause vscode to crash.
We use this to stop a potentially spammy extension from flooding the repl.

Closing as designed

**Closed by isidorn** 2016-04-25 06:57 UTC
Labels: debug, v-test
