### ISSUE TITLE
NPM Scripts bar does not appear in sidebar explorer

### ISSUE THREAD

**Issue by wandingistaken** [microsoft/vscode#120292] opened 2021-04-01 02:39 UTC
- VS Code Version: 1.55
- OS Version: macOS Big Sur 11.2.1

Steps to Reproduce:

1. `code .` on project dir (DEMO in this case) > DEMO shown in sidebar explorer > NPM scripts bar doesn't appear in sidebar > wasted a few hours trying to get it to show but no luck (editing files, settings, etc.) 
2. then I accidentally clicked something on the menubar, **Help** > **Release Note** specifically, the sidebar miraculously changed and the NPM scripts bar just popped out like that........... 😳😳😳😳😳????
3. take a look...
![image](https://user-images.githubusercontent.com/54961146/113236214-15829480-926a-11eb-9c60-0ec790149337.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment] 2021-04-01 05:56
Your root folder doesn't have a `package.json` so NPM extension won't start here.

Not sure why release node triggers it (release note is not a .json either)

Duplicate of #119868

**Closed** 2021-04-01 08:18 UTC
Labels: *duplicate
