### ISSUE TITLE
reveal-option when opening a document

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#13639] opened 2016-10-13 03:14 UTC
When you call `showTextDocument` you _can_ pass in which column a `TextDocument` should be opened. It works perfectly if it being opened for the first time, but if that `TextDocument` was already opened before, on a different column, you may end up with two views of the same `TextDocument`. 

I didn't find any API to check if the `TextDocument` is/was already opened, or any API to access the `Stacks/Columns`, so I could search for that `TextDocument` and detect the correct column to be used. I only found `onDidChangeTextEditorViewColumn` event, that appears to be a way to _follow_ the changes.

Thanks for your help.

**Comment by jrieken** [comment] 2016-10-13 08:37
There is [`TextEditor.viewColumn`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L953) and the list of `visibileTextEditors` with that you should be able to find what you need. Does that help?

**Comment by alefragnani** [comment] 2016-10-13 15:58
Hi @jrieken ,

Thanks for your advice, but unfortunately it does not work, because it only returns the _currently visible document_ in that column, not the _list of documents_.

I mean, let´s suppose I have two columns with 2 opened documents in each one, like the picture below. In this case the _visible document_ in each column is _the first one_ (**LEFT** - `extension.test.ts` / **RIGHT** - `launch.json`). 

![vscode_column](https://cloud.githubusercontent.com/assets/3781424/19355602/50d8b44e-9141-11e6-9ed4-ffd901cc06e3.png)

In my scenario,  I'm currently focused in the LEFT column. If I need to reopen/navigate to the _second one_ (`package.json`), which is in the RIGHT column, `vscode.window.visibleTextEditors[X]` gives me `launch.json`, with no information about `package.json` (at least no API), so I can't _know_ that `package.json` is also _stacked_ in that column. If I had access to the _stacks_, I could look for that file and open/focus it in the correct column.

The intention is to avoid reopen the same document twice, but instead _navigate_ to the already opened instance. 

Thanks for your help

**Comment by jrieken** [comment] 2016-10-14 07:03
Yes - we have not exposed the stacks/tab model but an editor in the API land is an editor widget that is bound to a model. I will think about some options for the show-call, like *revealIfAlreadyOpenInColumn*

**Comment by alefragnani** [comment] 2016-10-15 00:34
@jrieken thanks 👍 

By the way, I guess you forgot to reopen the issue 😁

**Comment by jrieken** [comment] 2016-10-17 07:10
I did ;-)

**Comment by jrieken** [comment] 2017-04-11 13:38
closing this as dupe of https://github.com/Microsoft/vscode/issues/15178 which came later but is a little easier to understand

**Closed by jrieken** 2017-04-11 13:38 UTC
Labels: api, editor, feature-request
