### ISSUE TITLE
Grid: Support adding horizontal split below a vertical split

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#51213] opened 2018-06-06 10:39 UTC
Issue Type: <b>Bug</b>

If I have two vertically splitted editors like this:
```
___________
|    |    |
|    |    |
|____|____|
```
I want to be able to move an editor below these to to create a horizontal split like this:
```
___________
|    |    |
-----------
|_________|
```

But I cannot do that:
![2018-06-06_12-19-14](https://user-images.githubusercontent.com/304384/41032747-a0362ea0-6984-11e8-97a8-5d0686df0ced.gif)

The editor supports this kind of layout, because if I create a horizontal split first, and split the upper horizontal, I can create the desired layout:
![2018-06-06_12-18-51](https://user-images.githubusercontent.com/304384/41032783-c173f0de-6984-11e8-9bbf-9830d08a535d.gif)
This is why I wonder why it is not possible to create this layout using the first method.

VS Code version: Code - Insiders 1.24.0-insider (0f4cde307559a2140cbe11989dc0052f13679921, 2018-06-01T12:17:19.366Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.2.0
tslint|eg2|1.0.30
vscode-great-icons|emm|2.1.33
vscode-todo-plus|fab|2.1.2
vscode-insiders-language-pack-hu|MS-|1.23.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.5.0
polacode|pnp|0.2.2
vscode-icons|rob|7.23.0
markdown-pdf|yza|1.2.0

(3 theme extensions excluded)

</details>

**Comment by aeschli** [comment] 2018-06-06 11:45
duplicate of #50666

**Closed by aeschli** 2018-06-06 11:45 UTC
Labels: insiders
