### ISSUE TITLE
Unable to use Quick Switch on Mac after opening Markdown Preview

### ISSUE THREAD

**Issue by 10bo** [microsoft/vscode#145303] opened 2022-03-17 10:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65
- OS Version: Mac OS Monterey 12.0.1 (21A559); MacBook Pro (13-inch, M1, 2020)

Steps to Reproduce:

1. Have multiple VS code windows open.
2. On window 1, create a Markdown file.
3. On window 1, open the Markdown preview to the side (⌘ + K, V).
4. Attempt to use ⌘ + ` to quick switch.
5. Window 2 should be brought to the foreground as it normally would. Instead, nothing happens.

The ⌘ + ` ('Quick Switch') Mac feature is essential to my every-day development and this issue in VS code prevents me from quickly switching between projects.

Additional: Moving the Markdown preview from editor group 2 into editor group 1 breaks the quick switch feature from that window entirely.

**Comment by mjbvz** [comment] 2022-03-17 18:12
Duplicate of #71800

**Closed by mjbvz** 2022-03-17 18:12 UTC
