### ISSUE TITLE
"Open file in editor" Terminal text tooltip link broken

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#107294] opened 2020-09-23 12:30 UTC
- VSCode Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version: Windows 10

Steps to Reproduce:

1. Debug a Python file containing `print("hello")a`
2. Try to navigate to the line with the SyntaxError using only the mouse.
3. See a broken Markdown link in the link mouseover tooltip.
![Markdown instead of working link](https://user-images.githubusercontent.com/9662163/94013284-27124d80-fdaa-11ea-96ca-fe9d80045314.png)

Does this issue occur when all extensions are disabled?: No because Python isn't available in the "Run, Start Debugging" options then.

**Comment by meganrogge** [comment] 2020-11-05 15:58
duplicate of #108301

**Closed by meganrogge** 2020-11-05 15:58 UTC
Labels: *duplicate
