### ISSUE TITLE
Debug value popup does not respect defined font family in settings

### ISSUE THREAD

**Issue by zeroskyx** [microsoft/vscode#83889] opened 2019-11-03 11:28 UTC
Issue Type: <b>Bug</b>

Greetings,

when inspecting the value of a variable in debug mode (paused) the popup that displays the value (no longer) respects the font defined in the settings as `"editor.fontFamily"` but falls back to a generic monospace font.

![image](https://user-images.githubusercontent.com/7782966/68084416-6a339d00-fe35-11e9-8983-3c2b929550dc.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.0-19-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3140)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.41GB (5.24GB free)|
|Process Argv|--force-user-env --unity-launch /home/zeroskyx/Dummy/Dummy.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.1
vscode-guid|hea|1.4.19
docomment|k--|0.1.8
rainbow-csv|mec|1.3.1
csharp|ms-|1.21.5
code-spell-checker|str|1.7.18
code-spell-checker-german|str|0.1.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by isidorn** [comment] 2019-11-12 16:12
Works for me.
Can you reproduce with latest vscode insiders? https://code.visualstudio.com/insiders/

![Screenshot 2019-11-12 at 17 11 44](https://user-images.githubusercontent.com/1926584/68688692-88a14300-056f-11ea-9015-4bc386387076.png)

**Comment by zeroskyx** [comment] 2019-11-13 11:18
Unfortunately the same is present in the insider version:

![image](https://user-images.githubusercontent.com/7782966/68759153-71b22d80-060f-11ea-870c-c8299001f25d.png)

With the following minimal settings:

```
{
    "editor.fontFamily": "DejaVu Sans Mono",
    "debug.console.fontFamily": "DejaVu Sans Mono",
    "terminal.integrated.fontFamily": "DejaVu Sans Mono"
}
```

PS: your check was JS while my example is C#; might this make a difference?

**Comment by isidorn** [comment] 2019-11-14 14:43
How about without those settings?
The debugged language should not matter.

**Comment by zeroskyx** [comment] 2019-11-17 14:20
Unfortunately without any settings, the situation is the same.

![image](https://user-images.githubusercontent.com/7782966/69008665-73505e00-094d-11ea-9ef3-0707fdb2f3ff.png)

Interestingly VSCode appears to respect the system-wide setting of my monospace font, which results in the code font being DejaVu Sans Mono.  
The debug console however uses the same (incorrect) default monospace font (Droid Sans Mono according to the dev tools) as the popup:

![image](https://user-images.githubusercontent.com/7782966/69008692-b6aacc80-094d-11ea-86b5-99862c621d67.png)

**Comment by isidorn** [comment] 2019-11-18 09:30
@joaomoreno is there some Linux Snap issue that the fonts are not respected?

**Comment by joaomoreno** [comment] 2019-11-19 10:52
Yes. There used to be, should be fixed by now tho.

**Comment by zeroskyx** [comment] 2019-11-19 12:51
I don't believe it is a snap issue; I can reproduce the same behavior when I download VSCode directly and run the extracted version from the .tar.gz.

**Closed** 2020-04-07 10:14 UTC
Labels: *out-of-scope, bug, debug
