### ISSUE TITLE
VS code changed font on startup

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#124506] opened 2021-05-24 11:50 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2 (user setup)
OS: Windows_NT x64 10.0.19042

I just opened vscode only to find out that my font is gone and in the terminal this weird spacing. This is happening for the first time and usually I use Cascadia code not this font. Why did it change automatically. Please find the below attachment

![image](https://user-images.githubusercontent.com/79589166/119343252-d134d300-bcb3-11eb-8e94-aa12b911e5f8.png)

**Comment by iron-coder12** [comment] 2021-05-24 12:14
I tried restarting changing the font but it dosen't seem to work

**Comment by IllusionMH** [comment] 2021-05-24 12:24
/needsMoreInfo

What is your font `editor.fontFamily` value and how did you install font into the system?
Do you have this font visible in OS Font settings? If it was installed with different app they might switched from 1 version to another with name changed.

**Comment by iron-coder12** [comment] 2021-05-24 12:33
I am using cascadia code @IllusionMH

**Comment by IllusionMH** [comment] 2021-05-24 12:52
I asked for exact string for `editor.fontFamily` and few more questions.

Most likely you removed all fallback font from `editor.fontFamily` and VS Code can't find font with name you provided.

**Comment by Tyriar** [comment] 2021-05-24 14:02
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by IllusionMH** [comment] 2021-05-24 14:09
@Tyriar I think it's about Times New Roman in editor (and terminal), not about spacing in Terminal. Or you are saying that both should be fixed?

**Comment by Tyriar** [comment] 2021-05-24 16:09
Oh right, that will typically happen if you point to an invalid font or it's not installed yet.

This is a good question to answer:

> Do you have this font visible in OS Font settings? If it was installed with different app they might switched from 1 version to another with name changed.

**Comment by iron-coder12** [comment] 2021-05-24 16:14
> Oh right, that will typically happen if you point to an invalid font or it's not installed yet.
> 
> This is a good question to answer:
> 
> > Do you have this font visible in OS Font settings? If it was installed with different app they might switched from 1 version to another with name changed.

I just reset the entire settings of vscode and ya vscode is back to normal but instead of Cascadia code I am currently using the default vs code font and when I switch back to Cascadia code the problem happens again

**Comment by IllusionMH** [comment] 2021-05-24 16:47
As said earlier - most likely you have incorrect value set to `editor.fontFamily` what exactly do you have in your `settings.json` for this field?

Also what is listed in Windows Settings when you search by "cascadia"?
![image](https://user-images.githubusercontent.com/1312662/119379994-d2bcc600-bcc8-11eb-84db-54a336c6b4cb.png)

**Comment by iron-coder12** [comment] 2021-05-25 02:44
![image](https://user-images.githubusercontent.com/79589166/119431871-f87db580-bd30-11eb-8735-da8cf1a5beff.png)
![image](https://user-images.githubusercontent.com/79589166/119431974-2105af80-bd31-11eb-8cb0-769fe2d7848f.png)
If I will change it back to cascadia code and remove the consolas the terminal problem and the font will change again

**Comment by iron-coder12** [comment] 2021-05-25 02:44
"editor.fontFamily": "Consolas, 'Cascadia Code'"

**Comment by iron-coder12** [comment] 2021-05-25 02:46
from where can I install cascadia code?

**Comment by IllusionMH** [comment] 2021-05-25 10:50
/question

Looks like this problem not related to VS Code editor itself so closing it.
See https://github.com/microsoft/cascadia-code#installation for installation steps and use proper font name that matches variant you download.

**Closed** 2021-05-25 10:50 UTC
Labels: *question, needs more info
