### ISSUE TITLE
Noticeable delay opening a markdown file (source)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8173] opened 2016-06-27 08:14 UTC
I am noticing a delay when I click on a markdown file until it opens. I think this is a regression from the new markdown extension but I am not sure what piece could cause it.

//cc @jrieken if you have clues

**Comment by jrieken** [comment] 2016-06-27 09:46
It's starting a process that encapsulated the rendering

**Comment by jrieken** [comment] 2016-06-27 09:47
A dupe of #7066

**Comment by bpasero** [comment] 2016-06-27 11:30
@jrieken I see this when opening the markdown file in source, not preview. I am aware of the delay when previewing.

**Comment by jrieken** [comment] 2016-06-27 12:04
hm... is the grammar we are using?

**Comment by jrieken** [comment] 2016-06-27 12:08
![screen shot 2016-06-27 at 14 06 47](https://cloud.githubusercontent.com/assets/1794099/16379197/6a6bb7ce-3c70-11e6-8ec5-92a118c2e864.png)

Holy moly - the parsing/loading the grammar is **slow**. Tho it only happens once/the first time. @aeschli @alexandrudima ideas how to seep that up?

[CPU-20160627T140746.cpuprofile.zip](https://github.com/Microsoft/vscode/files/334769/CPU-20160627T140746.cpuprofile.zip)

**Comment by alexandrudima** [comment] 2016-06-28 11:01
This sounds like an opportunity for a great new `plist-to-json` node module. I'd love to write that :)

**Comment by jrieken** [comment] 2016-06-29 08:54
Maybe we can use the native `DOMParser` for this (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser)

**Comment by alexandrudima** [comment] 2016-06-29 11:58
@jrieken `vscode-textmate` is a node module and should in theory not use browser API. We can, as always make it injectable with a different plist parser.

**Comment by alexandrudima** [comment] 2016-06-30 14:10
I am on the path of writing a plist parser.

before:
![image](https://cloud.githubusercontent.com/assets/5047891/16491152/15571ae8-3edd-11e6-8fb7-382073b0aacb.png)


after:
![image](https://cloud.githubusercontent.com/assets/5047891/16491179/232583c6-3edd-11e6-925a-64dd9ad341b7.png)

**Comment by jrieken** [comment] 2016-06-30 15:12
Tho, I'd still like to see how it compares to the `DOMParser` ;-)

**Comment by alexandrudima** [comment] 2016-06-30 16:58
[before.CPU-20160630T185643.zip](https://github.com/Microsoft/vscode/files/341935/before.CPU-20160630T185643.zip)
[after.CPU-20160630T185657.zip](https://github.com/Microsoft/vscode/files/341936/after.CPU-20160630T185657.zip)

before:
![image](https://cloud.githubusercontent.com/assets/5047891/16496890/914e286e-3ef4-11e6-9341-bf7d36915919.png)

after:
![image](https://cloud.githubusercontent.com/assets/5047891/16496897/9ab00f62-3ef4-11e6-99fb-92a268b28c95.png)

**Comment by alexandrudima** [comment] 2016-06-30 17:07
To the verifier: please check that you can get the previous (slow) parser when setting the "hidden" preference `editor.useExperimentalParser = false`. I've added this to have a fallback in case my 10x faster parser has a bug, so we can switch back to the SAX based parser based on a setting. I will remove the setting after our confidence grows, by default the setting is on (use faster parser by default).

**Closed** 2016-06-30 17:08 UTC
Labels: bug, markdown

**Comment by bpasero** [comment] 2016-07-01 12:51
Works great in terms of performance 👍
