### ISSUE TITLE
终端无法打开

### ISSUE THREAD

**Issue by wengzhenyucode** [microsoft/vscode#123847] opened 2021-05-14 05:50 UTC
终端进程启动失败: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\winpty-conin-14660-1-1d74883d7d8668b-8b5956e448bd1b94753691d0a2dbad81')。

**Comment by egamma** [comment] 2021-05-14 06:10
Closing as a duplicate of #123849

**Closed by egamma** 2021-05-14 06:10 UTC
Labels: *duplicate, *english-please, needs more info, translation-required-chinese-simplified
