### ISSUE TITLE
Experimental grid layout breaks dragging to open console

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#68135] opened 2019-02-07 17:16 UTC
Version: 1.32.0-insider (user setup)
Commit: 45c7f29565821668f4d010b25e3289953bd9ac71
Date: 2019-02-07T10:25:31.179Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Enable the experimental grid layout (`workbench.useExperimentalGridLayout`).
2. Normally, you can drag up the console by hovering over the top edge of the bottom bar and dragging up when the vertical resize arrows appear. With the experimental layout enabled, the arrows no longer appear.

**Comment by sbatten** [comment] 2019-02-08 02:12
@iansan5653 do you mean that when it is hidden, you cannot unhide it by dragging from the status bar?

**Comment by sbatten** [comment] 2019-02-08 02:14
closing as duplicate of https://github.com/Microsoft/vscode/issues/67209. re-open if i'm mistaken

**Closed by sbatten** 2019-02-08 02:14 UTC
Labels: workbench-grid
