### ISSUE TITLE
Always failed to copy a image file's filename.

### ISSUE THREAD

**Issue by guogangj** [microsoft/vscode#129367] opened 2021-07-26 03:19 UTC
In explorer, click on a image file (eg. a png file). 
Press F2 to try to edit the filename. Now the filename's text is in select state.
Try [ctrl]+[c] to copy the filename's text. Not work.

**Comment by gjsjohnmurray** [comment] 2021-07-26 04:37
/duplicate of 126458 assuming that you are not running Insiders. Ideally, give version info on future issues. Maybe use Report Issue option from Help menu, which does this for you.

**Closed** 2021-07-26 04:38 UTC
Labels: *duplicate
