### ISSUE TITLE
Modify Snippet Variable References to uppercase / lowercase / capitalize not working out

### ISSUE THREAD

**Issue by Sly321** [Microsoft/vscode#41526] opened 2018-01-12 11:23 UTC
- VSCode 1.19.0:
- Windows 10 / MacOS:

I want to create a snippet that modifies the references of the variables.

Example Code Snippet:
```json
"my-snippet": {
	"prefix": "snippet",
	"body": [
		"$1",
		"${1/capitalize}",
		"${1/upcase}",
		"${1/downcase}"
	]
}
```

Expected Output:
```
helloWorld
HelloWorld
HELLOWORLD
helloworld
```

Actual Output
```
helloWorld
${1/capitalize}
${1/upcase}
${1/downcase}
```

Things i know that works: (inserts the base-file-name is downcase)
```
${1:${TM_FILENAME_BASE/(.*)/${1:/downcase}/}}
$1
${2:${TM_FILENAME_BASE/(.*)/${1:/upcase}/}}
$2

// explained
// ${1 - the variable 'name'
// : - the indentificator that a placeholder for the $1 variable follows
// ${TM_FILENAME_BASE/(.*)/${1:/downcase}/} - my custom placeholder
// TM_FILENAME_BASE - base file name ( eslint.json -> eslint)
// /(.*)/ - Regexgroup, take everything
// ${1:/downcase} - reference the first regex group, an modify it to downcase

/** Output - executed in a file called: 'helloWorld.js' */
helloworld
helloworld
HELLOWORLD
HELLOWORLD
```

I don't get this pattern working for my helloWorld case when i want to upcase/downcase my $1 reference. I tried different things like `${2:{$1/(.*)/{$1:/downcase}/}}` but nothings seems to work.

Is this even possible?

I am curious if i am the only one that think its a litte less [documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) for this.

**Comment by jrieken** [comment] 2018-01-12 15:40
dupe of #34683

**Closed by jrieken** 2018-01-12 15:40 UTC
Labels: snippets
