### ISSUE TITLE
Once again, proxy settings are also not working in 1.50.0

### ISSUE THREAD

**Issue by dimsis** [microsoft/vscode#108375] opened 2020-10-09 10:13 UTC
- VSCode Version: 1.50.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSC
2. Help > Update or trying to install extension leads to :
net::ERR_CONNECTION_REFUSED
Source: Update Service

Does this issue occur when all extensions are disabled?: Yes

Tried everything:
* all the possible combinations in files > preferences > settings > proxy (user & workspace)
* starting vscode.exe with proxy parameters
* Replacing auth.js with old https://raw.githubusercontent.com/microsoft/vscode/master/src/vs/code/electron-sandbox/proxy/auth.js

it's not even displaying the proxy window asking the credentials any more.

And of course, restarting VSC every time I did a change and I was always running VSC as admin.

Only when I am trying our proxy without having my credentials in the url and when I have :+1: 
    "http.proxyAuthorization": "false",
    "http.proxyStrictSSL": false
it tried to open the window for username and password, but it's empty. And in fact it opens two blank windows:
https://ibb.co/dKRtW3S

**Comment by bpasero** [comment] 2020-10-12 14:49
The dialog works fine for me in stable following the steps from https://github.com/microsoft/vscode/issues/106489#issue-699287308:

![image](https://user-images.githubusercontent.com/900690/95759980-c1c7c300-0caa-11eb-8829-6047c43faab9.png)

So this must be a different issue with how the credentials are used. I suggest that people who own the connection that needs proxy follow up. Since I see update and extensions installation in there, assigning to Joao and Sandeep.

**Comment by bpasero** [comment] 2020-10-12 14:50
@dimsis 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dimsis** [comment] 2020-10-14 19:07
Sorry for the delayed repsonse @bpasero 
It works with the insider version:
![image](https://user-images.githubusercontent.com/33701/96033934-13b24980-0e61-11eb-942d-d7d9aca0fcc6.png)

**Closed** 2020-11-04 15:37 UTC
Labels: extensions, install-update, proxy
