### ISSUE TITLE
All characters are invisitable.

### ISSUE THREAD

**Issue by recolic** [Microsoft/vscode#16217] opened 2016-11-29 12:27 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.8.6-1-ARCH
- Extensions:
I've tried to open a .cpp file or create a new file, but no character is shown in the editor interface. 
It seems like that the text-color is constantly same as background color...... Changing another color theme won't help. 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|vs-keybindings|ms-vscode|0.1.1|

---

Steps to Reproduce:

1.Just run Visual Studio Code.......Problem occurs.(I got a vscode src pack from aur)

**Comment by chrmarti** [comment] 2016-11-29 18:40
@recolic Could you attach a screenshot? I cannot reproduce the problem in my setup.

**Comment by recolic** [comment] 2016-11-30 10:02
Maybe it's related to ibus Chinese input method...Because  it will work properly in some rare conditions.
![snapshot2](https://cloud.githubusercontent.com/assets/19610256/20747842/98e6d990-b726-11e6-9ca1-45235f3fdd3b.png)

**Comment by chrmarti** [comment] 2016-11-30 18:15
Have you tried with a file that does not contain Chinese characters? Does it occur with other programming languages as well?

**Comment by recolic** [comment] 2016-12-01 03:17
When I create a new file or open an ANSI-coded file without Chinese, the problem still exists.

I haven't found out what makes it to work well...

**Comment by recolic** [comment] 2016-12-01 03:23
Maybe some necessary fonts aren't installed in my Arch Linux?...

**Comment by chrmarti** [comment] 2016-12-01 18:06
What about a text file or a JavaScript file, do these display correctly?

**Comment by recolic** [comment] 2016-12-02 06:33
No... I've tried it.
![snapshot3](https://cloud.githubusercontent.com/assets/19610256/20825021/43a5d04a-b89c-11e6-9fbd-4a82c4dd5e67.png)

**Comment by recolic** [comment] 2016-12-02 07:06
I've solved the problem...As what I'm guessing, it displays all texts correctly after installing these fonts listed in config file(json)...

**Comment by chrmarti** [comment] 2016-12-02 19:29
@recolic Sounds like the Arch package is missing a dependency? Any chance you could follow up with the maintainer of the package? /cc @Tyriar

**Comment by Tyriar** [comment] 2016-12-02 23:10
@recolic what fonts did you install to get it working? Since vscode is based on Chromium, I would expect the same to happen if you had an element in Chrome with the same font-family. This is potentially an upstream issue?

**Comment by recolic** [comment] 2016-12-03 04:10
I've used Chromium for a long time, but similar problem didn't appear(NEVER). I've tried VSCode package from AUR and code.visualstudio.com but it doesn't help.
I got what a fonts list from vscode config json and download them from google... TTFs are packed and uploaded to 'http://recolic-uswest.oss-us-west-1.aliyuncs.com/fontForVscode.tar.gz'

**Comment by Tyriar** [comment] 2016-12-05 20:42
@bpasero @alexandrudima have you seen something like this before?

**Comment by alexandrudima** [comment] 2016-12-05 22:01
@Tyriar First time I'm seeing this. Usually, Chromium falls back if a font is not installed. i.e. you can type anything in `editor.fontFamily` and Chromium ultimately finds a font to render with. I don't know what their fallback font is and what happens if even that one is missing.

**Comment by bpasero** [comment] 2016-12-06 05:28
No, never saw something like this :-/

**Comment by markbenvenuto** [comment] 2017-01-11 20:41
I was actually able to repro this invisible fonts issue on Fedora 25 with VSCode 1.8.1. This issue was evident on VSCode startup where there was no text rendered in either the VS Code Window or the Chrome Developer Tools.

The problem was that I had very few fonts installed. According to `fc-list`, I only had variants of: Century Schoolbook, Comfortaa, Nimbus Mono, Nimbus Roman No9, Nimbus Sans, Standard Symbols, URW Bookman, URW Chancery, URW Gothic, URW Palladio, Utopia.

Installing some more fonts fixed the problem: `dnf install -y google-droid-sans-fonts google-droid-sans-mono-fonts google-droid-serif-fonts`.

**Comment by Tyriar** [comment] 2017-01-12 00:09
Well all font locating logic is done by Chromium. We could make sure by shipping our own font (see https://github.com/Microsoft/vscode/issues/5742).

**Comment by joeyaiello** [comment] 2017-03-28 17:10
I'm also hitting this on a CentOS 7 machine that started as a minimal install (i.e. very few fonts, and I built it up from scratch). I have Chrome installed as well (not Chromium), and no font problems there at the moment. 

Unfortunately, CentOS doesn't seem to have any packages for `google-droid-*-fonts`, but I already had `google-noto-fonts-common` and `google-noto-sans-fonts` from Chrome, so I went and ahead and installed `google-noto-serif-fonts` (and a FC26 RPM for the monospaced fonts, that was all I could find). 

Interestingly, editor views look fine (presumably, it's falling back to Liberation Mono or Inconsolata, which I know are monospace fonts installed on the box). 

Really, I'd just like to know what fonts you guys are using here, so I can go track down a package and install them. I know I'm not the typical user coming up from a minimal install, so I'm almost positive there's a bunch of fallback fonts I *should* have but don't. 

## Screenshots
![nofonts](https://cloud.githubusercontent.com/assets/1255187/24417776/875d851e-139e-11e7-9c59-b9a202064b00.jpg)

![workingfonts](https://cloud.githubusercontent.com/assets/1255187/24417783/8b58388a-139e-11e7-906f-70a6e5eb55fa.jpg)

## Environment data
```
$ uname -a
Linux <hostname> 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ yum list installed code
Installed Packages
code.x86_64                     1.10.2-1488981323.el7                      @code

$ code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by joeyaiello** [comment] 2017-03-28 17:17
So I tracked down some old `google-droid-*.el7` packages from the fine folks that ship Nux, and it totally fixed me. Looks like this might be related #5742, I think it would be awesome if you guys shipped a couple high-quality fonts app-local in the package. (But consider this problem fixed for me.)

**Comment by Tyriar** [comment] 2017-04-21 04:39
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/5742 as it's related to font.

**Closed by Tyriar** 2017-04-21 04:39 UTC
Labels: bug, linux, needs more info
