### ISSUE TITLE
[vscode.dev] I can't change settings using touch screen - Android tablet

### ISSUE THREAD

**Issue by rafrafek** [microsoft/vscode#136519] opened 2021-11-05 13:55 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: Android 10, Chrome browser, Lenovo tablet

Steps to Reproduce:

1. Open vscode.dev on tablet
2. Go to settings and search for telemetry
3. Try to change telemetry settings using touch

Description:
I have Android tablet and I can't change telemetry settings on vscode.dev opened in Chrome using touch. External mouse works.
![obraz](https://user-images.githubusercontent.com/23004737/140520946-c7e30338-290a-4a51-82a3-6a44aa069d24.png)

_Originally posted by @rafrafek in https://github.com/microsoft/vscode/issues/125686#issuecomment-961814746_

**Comment by roblourens** [comment] 2021-11-05 16:42
Dupe of https://github.com/microsoft/vscode/issues/73283

**Closed by roblourens** 2021-11-05 16:42 UTC
