### ISSUE TITLE
[feature request]Support vertical indent level line and renderWhitespace when selection

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#4418] opened 2016-03-18 12:49 UTC
1. Does Code support showing vertical indent level line?
2. now `editor.renderWhitespace` only have `true` or `false`, can we have a option to only render whitespace when selection?

**Comment by glen-84** [comment] 2016-06-18 14:33
Duplicate of #2192 and #1477.

**Comment by alexandrudima** [comment] 2016-06-29 14:25
Let's track in #1477

**Closed** 2016-06-29 14:25 UTC
Labels: duplicate
