### ISSUE TITLE
vscode opens to a blank black screen

### ISSUE THREAD

**Issue by dustinself** [microsoft/vscode#86773] opened 2019-12-11 22:13 UTC
Issue Type: <b>Bug</b>

1. Open vscode
2. Get a blank black screen
3. Reinstall to fix
4. Close vscode
5. Open vscode
6. Get a blank black screen, again

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by RMacfarlane** [comment] 2019-12-11 22:26
Duplicate of https://github.com/microsoft/vscode/issues/86710

**Closed by RMacfarlane** 2019-12-11 22:26 UTC
Labels: integrated-terminal
