### ISSUE TITLE
Saving and running 'Dart' formatter

### ISSUE THREAD

**Issue by Garrison88** [microsoft/vscode#124686] opened 2021-05-26 14:22 UTC
Issue Type: <b>Performance Issue</b>

VS Code hangs while saving a file, even after making just a minor adjustment. It is trying to run the 'Dart' formatter, but never completes. I have tried completely uninstalling VS Code and restarting my Mac, but I am still experiencing the problem. It started when I updated Flutter to 2.2

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.23GB free)|
|Process Argv|--crash-reporter-id 3fdaa67d-ab40-4dbe-980d-b458b70df8e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   164	  1261	code main
    5	    98	  1265	   gpu-process
    0	    33	  1270	   utility
    4	   393	  1271	   window (master_details_view.dart — cmic_mobile_field)
    0	   197	  1277	     extensionHost
    0	    33	  1316	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1277
    0	   721	  1335	       /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id=VS-Code --client-version=3.22.0
    0	     0	  1336	       bash /Users/garrison/Development/flutter/bin/flutter daemon
    0	   164	  1355	         /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/garrison/Development/flutter/packages/flutter_tools/.packages /Users/garrison/Development/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	  1382	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	    33	  1383	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	    66	  1356	       /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --try-ports 10 --allow-embedding
    0	    98	  1279	     watcherService
    0	    33	  1433	     searchService
    1	   131	  1278	   shared-process
    0	    33	  1280	     ptyHost
    0	     0	  6289	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  6276	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (master_details_view.dart — cmic_mobile_field)
|    Folder (cmic_mobile_field): 8211 files
|      File types: svn-base(2037) dart(1421) h(754) png(479) strings(126)
|                  m(115) plist(106) json(96) swift(91)
|                  xcconfig(84)
|      Conf files: settings.json(2) launch.json(1)
|      Launch Configs: dart(9);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
material-icon-theme|PKi|4.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by IllusionMH** [comment] 2021-05-26 14:36
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Looks like duplicate of https://github.com/Dart-Code/Dart-Code/issues/3270

**Comment by puckerxp** [comment] 2021-05-27 07:56
After upgrade to Flutter 2.2, I have the same problem.

**Comment by dbaeumer** [comment] 2021-05-28 07:16
Since the dart formatter is involved here I recommend to start with the dart extension.  Please report the issue here: https://github.com/Dart-Code/Dart-Code

**Closed by dbaeumer** 2021-05-28 07:16 UTC
Labels: needs more info

**Comment by t-kozak** [comment] 2021-06-09 23:04
For anyone who ends here through web search (1st page of results), I've created another issue in the Dart-Code: https://github.com/dart-lang/sdk/issues/45996, that was subsequently closed as most probably cause of the problem is this one: https://github.com/dart-lang/sdk/issues/45996 which has been fixed recently.
