### ISSUE TITLE
Feature Request: Allow setting root custom css properties from extensions

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#30814] opened 2017-07-16 18:15 UTC
text editor decorations allow setting values like color, background color, etc.

An extension may create several decorations that share common values that should change together. Or even a single long-lived decoration that may change over time.

Currently making a change to those values requires creating a new decoration OR using render options which is warned against in the docs for performance reasons.

An alternative would be to allow extensions to set [custom css properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*). This would cause all decorations using this property to automatically update.

For example:
```javascript
// Set an initial background color
vscode.window.setCustomCssProperty('--my-extension-background-color', 'green');
// Create the decoration with the background color set to reference a custom css property
vscode.window.createTextEditorDecorationType({ backgroundColor: 'var(--my-extension-background-color)' });
...
// Something happens that should change the background color
vscode.window.setCustomCssProperty('--my-extension-background-color', 'red');
```

**Comment by aeschli** [comment] 2017-07-18 00:48
The right way would be to allow extensions to define new theme colors.

For now we recommend to always use one the built-in theme colors in decorations.

Duplicate of #14309

**Closed by aeschli** 2017-07-18 00:48 UTC
Labels: api
