### ISSUE TITLE
Can't Open any file

### ISSUE THREAD

**Issue by lacikawiz** [microsoft/vscode#96110] opened 2020-04-25 03:31 UTC
Issue Type: <b>Bug</b>

VSCode generated the following line in ~/.config/Code/User/settings.json 

"editor.quickSuggestions": null

This caused the following error message to be displayed at every attempt to open a file:

`Unable to open '__filename___': Assertion Failed: argument is undefined or null.`

Changing the line to `"editor.quickSuggestions": false`
fixed it.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.0-29-generic

**Comment by gjsjohnmurray** [comment] 2020-04-25 05:56
>
> VSCode generated the following line in ~/.config/Code/User/settings.json

Are you able to identify exactly what did that. Sounds to me more like something a faulty extension is doing.

**Comment by gjsjohnmurray** [comment] 2020-04-25 06:00
See also https://github.com/microsoft/vscode/issues/93679#issuecomment-614137061

**Comment by gjsjohnmurray** [comment] 2020-04-25 06:06
/duplicate of #94931 which I see you have already found.

**Comment by lacikawiz** [comment] 2020-04-25 06:07
Thanks for looking into this.

I have the following extensions:
```
akamud.vscode-theme-onedark-2.2.1  
bceskavich.theme-dracula-at-night-2.6.0
ms-vscode.atom-keybindings-3.0.6
akamud.vscode-theme-onelight-2.2.1
bungcip.better-toml-0.3.2
alefragnani.bookmarks-11.1.0
jamesbirtles.svelte-vscode-0.9.3
```
I installed them in a quick succession so I don't know which one might have messed with the settings.json file.

**Closed** 2020-04-25 06:07 UTC
Labels: *duplicate
