### ISSUE TITLE
Search results not updating

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#231682] opened 2024-10-18 17:31 UTC
Type: <b>Bug</b>

Not sure of the extact trigger but my search is stuck with stale results. This error seems to be the issue:

```
TreeError [SearchView] Data tree node not found: [object Object]: Error: TreeError [SearchView] Data tree node not found: [object Object]
    at u$.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:412:34033)
    at u$.C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:412:31051)
    at u$.updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:412:30824)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2099:18478
    at Array.map (<anonymous>)
    at 
```

VS Code version: Code - Insiders 1.95.0-insider (Universal) (62a233cc87dc8d52a817739bc0d917089d4d103b, 2024-10-17T05:09:34.012Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|5, 14, 13|
|Memory (System)|64.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andreamah** [comment] 2024-10-18 17:32
Do you have any non-default search settings? like sort order or default collapse state?

**Comment by mjbvz** [comment] 2024-10-18 17:35
I have AI search results enabled. Other than that, I think it was in the default state

**Comment by andreamah** [comment] 2024-10-18 17:49
This is a duplicate of https://github.com/microsoft/vscode/issues/231399
I've been trying to repro it, but it seems difficult to. It's likely a race condition somewhere.

/duplicate https://github.com/microsoft/vscode/issues/231399

**Closed** 2024-10-18 17:50 UTC
Labels: *duplicate
