### ISSUE TITLE
Visible search history

### ISSUE THREAD

**Issue by brandondrew** [Microsoft/vscode#43698] opened 2018-02-14 22:12 UTC
Although we thankfully have ⌥↑ and ⌥↓ to cycle through search history,  these are not standard keystrokes that people expect, and are not discoverable in the UI in any way that I can find.  The only way to find these is by Googling or some other form of searching.  

It would be very useful to have a visible UI control to display a list of historical entries.

**Comment by roblourens** [comment] 2018-02-14 22:46
/duplicate of https://github.com/Microsoft/vscode/issues/23099

Popular request :)

**Closed by roblourens** 2018-02-14 22:46 UTC
Labels: search

**Comment by athinboy** [comment] 2018-02-19 11:16
@roblourens   are you sure ?  

Alt+ ↑ / ↓     Move line up/down 

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
