### ISSUE TITLE
VSCode Auto Save untitled files and open those files when opens again like Notepad++

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#3454] opened 2016-02-25 13:37 UTC
Is there any way that i write some text in some files and dont save those files and close the editor when i open the editor again it should auto open those files like notepad++ does.

**Comment by joaomoreno** [comment] 2016-02-26 07:57
This is currently not implemented.

**Comment by axefrog** [comment] 2016-02-26 11:55
This is also the default behaviour in Sublime and Atom.

**Comment by shanalikhan** [comment] 2016-02-27 16:34
i still use notepad++ for such feature. It would be great if this feature is implemented. to even write plain text in VSCode

**Comment by fyears** [comment] 2016-02-28 09:21
This issue seems to be a duplication of #906.

I am another user looking for this features here. I also find someone posted feature suggestion on [uservoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756146-auto-save-temporary-files).

**Comment by joaomoreno** [comment] 2016-02-28 16:24
Thanks. Closing as duplicate of #906

**Closed by joaomoreno** 2016-02-28 16:24 UTC

**Comment by lovebdsobuj** [comment] 2016-08-20 02:25
This feature `"Unsaved files should be preserved on quit"` still not yet implement in **VSCode** version 1.4 !
It's really needed feature.
