### ISSUE TITLE
启动终端出现问题

### ISSUE THREAD

**Issue by xyingzhi** [Microsoft/vscode#10798] opened 2016-08-22 14:16 UTC
- VSCode Version: 1.4
- OS Version:

Steps to Reproduce:

1. 安装程序，启动终端，直接报此处错误  通过退出代码 1 终止的终端进程
2.  Compiled script is not shown while  source map is being loaded! error

**Comment by tailgo** [comment] 2016-08-22 16:21
虽然现在有国人在参与项目，不过建议最好还是都用英语来提issue。

**Comment by sandy081** [comment] 2016-08-23 08:43
@xyingzhi I am not sure if the given steps are helpful enough to recreate or understand the issue you are facing. Can you please give us a little more detailed steps..

Thanks.

**Comment by dbaeumer** [comment] 2016-09-05 07:15
Closing. Haven't received any response. @xyingzhi please ping if the issue is still reproducible with steps that demo the problematic behavior.

**Closed by dbaeumer** 2016-09-05 07:15 UTC
Labels: needs more info
