### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#211415] opened 2024-04-26 05:41 UTC
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=270464

![image](https://github.com/microsoft/vscode/assets/900690/b4fce4ef-12ba-40ef-8273-c75fc0559c60)

**Comment by joaomoreno** [comment] 2024-04-26 07:35
Duplicate of #211027

**Closed by joaomoreno** 2024-04-26 07:35 UTC
Labels: vscode-build
