### ISSUE TITLE
undefined window.activeTextEditor for binary files

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#33869] opened 2017-09-06 02:45 UTC
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:40:17.463Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

window.activeTextEditor and e from onDidChangeActiveTextEditor callbacks are null when selecting/ opening a binary file (ie .png or exe)

I cannot find any other accessor for non-text file/editors.  How do I get the uri for my own extension to operate on?  (ie, showing scm status)

**Comment by jrieken** [comment] 2017-09-06 08:31
Yeah, that's why we call it active*Text*Editor. There is no representation for other editors and contents in the system. We might cover this in #15178

**Comment by jrieken** [comment] 2017-09-06 08:31
Also, duplicate of #14483

**Closed by jrieken** 2017-09-06 08:31 UTC
Labels: api, as-designed, insiders
