### ISSUE TITLE
CommonMark compliant HTML block inside <p> tag is removed by JSDoc Intellisense

### ISSUE THREAD

**Issue by trivikr** [microsoft/vscode#113959] opened 2021-01-07 06:33 UTC
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open the [example code](https://www.typescriptlang.org/play?#code/PQKhCgAIUgeAHAfAQUgIwIYGcCWBjSHAOwBcBTAJwDMM8zIB3HEgC0ioHsOA6WYJKCGDhi5arXoAxLpADeUdlwBckIgFcAtmkoBucAF9w4ADZkS7FdI47IwYJAAqXYyRzxIFMhgAmWSACJ-I1AIaEhUTFwCUUoaOkZmNkwKbkFhGPF4gCEMCjkFZJV1LV0DI1NzNBUcihs7R2dXd08fP38I7HxCUliJBNZ0XO4goA) in VSCode.
2. Hover over `Foo`. The Tooltip reads "".
3. Hover over `Bar`. The Tooltip reads "A basic interface with bar."

The doc comment for `Foo` is compliant under [CommonMark spec 0.29 4.6 HTML Blocks kind 6](https://spec.commonmark.org/0.29/#html-blocks)
* **Start condition**: line begins the string `<` followed by `p`, followed by the string `>`
* **End condition**: line is followed by a blank line

<details>
<summary>Example Code</summary>

```ts
/**
 * <p>A basic interface with foo.</p>
 */
interface Foo {
  foo: number;
}

let f: Foo; // Tooltip reads ""

/**
 * A basic interface with bar.
 */
interface Bar {
  bar: number;
}

let b: Bar; // Tooltip reads "A basic interface with bar."

```

</details>

<details>
<summary>Screenshots</summary>

![Screen Shot 2021-01-06 at 10 27 58 PM](https://user-images.githubusercontent.com/16024985/103859222-87ce4900-506e-11eb-81f4-5b2a66973ae5.png)

![Screen Shot 2021-01-06 at 10 28 03 PM](https://user-images.githubusercontent.com/16024985/103859229-8bfa6680-506e-11eb-92da-ba5241017005.png)

</details>

Does this issue occur when all extensions are disabled?: Yes

**Comment by trivikr** [comment] 2021-01-07 06:36
A similar issue discusses removal of code inside `<pre>` and `<code>` tags in https://github.com/microsoft/vscode/issues/110945, but that appears under [CommonMark spec 0.29 4.5 Fenced code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks)

**Comment by trivikr** [comment] 2021-01-07 16:25
Looking at the code comments, the makrdownRenderer seems to comply with CommonMark 0.29 spec.
https://github.com/microsoft/vscode/blob/6260e655bc606e204ad51ce5b1cb34216cd36dd3/src/vs/base/browser/markdownRenderer.ts#L288

**Comment by trivikr** [comment] 2021-01-07 16:35
Some findings which could be helpful:
* The markdownRenderer uses marked from `vs/base/common/marked/marked`: https://github.com/microsoft/vscode/blob/6260e655bc606e204ad51ce5b1cb34216cd36dd3/src/vs/base/browser/markdownRenderer.ts#L11
* The renderer is markdown parser from https://github.com/markedjs/marked https://github.com/microsoft/vscode/blob/6260e655bc606e204ad51ce5b1cb34216cd36dd3/src/vs/base/common/marked/marked.js#L1-L5

The [Marked Demo](https://marked.js.org/demo/?text=%3Cp%3EA%20basic%20interface%20with%20foo.%3C%2Fp%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) returns data as per [CommonMark spec 0.29 4.6 HTML Blocks kind 6](https://spec.commonmark.org/0.29/#html-blocks) for provided example.

<details>
<summary>Screenshot</summary>

![Screen Shot 2021-01-07 at 8 33 50 AM](https://user-images.githubusercontent.com/16024985/103918058-2d130c80-50c3-11eb-84a9-014bd7582c0e.png)


</details>

**Comment by mjbvz** [comment] 2021-01-07 22:13
Duplicate of #110945 I believe, just with a different html tag

**Closed by mjbvz** 2021-01-07 22:13 UTC
