### ISSUE TITLE
camaras

### ISSUE THREAD

**Issue by Zaalaanko** [microsoft/vscode#234245] opened 2024-11-20 07:57 UTC
> ![Image](https://github.com/user-attachments/assets/dc8fe0bc-80e2-4164-af63-22068218926b)
> No package.json package prompt 

 _Originally posted by @alaric8866 in [#234242](https://github.com/microsoft/vscode/issues/234242#issuecomment-2487707484)_

**Comment by mjbvz** [comment] 2024-11-20 19:52
Duplicate of #234242

**Closed by mjbvz** 2024-11-20 19:52 UTC
