### ISSUE TITLE
vscode stucks after opening big cpp file: Window is no longer responding

### ISSUE THREAD

**Issue by r44083** [microsoft/vscode#76710] opened 2019-07-05 10:59 UTC
- VSCode Version: 1.36.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. Open big .cpp file with a lot of code (example of such file is attached below)
2. Wait about 5-8 seconds and see that vscode doesn't respond on any action. After about 20 seconds, it suggest to reopen/waiting/close vscode (see attached screenshot). None of the suggested actions fix this issue.

[test.cpp.zip](https://github.com/microsoft/vscode-cpptools/files/3362256/test.cpp.zip)

![Screenshot at 2019-07-05 13:12:33](https://user-images.githubusercontent.com/13915612/60716146-52034e00-9f27-11e9-8c87-25a463999412.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by BillDenton** [comment] 2019-07-05 11:45
Exactly the same problem with & without extensions. The file is 16,675 bytes and 552 lines, so not that big.
Completely unusable and unable to continue working. How do I roll back to the previous version, so I can continue working?

**Comment by r44083** [comment] 2019-07-05 13:00
I have notice that if I manually select language mode to "Plain Text" - issue isn't reproduced.
So, this issue is related to C++ syntax highlighting.

**Comment by matter123** [comment] 2019-07-06 02:10
@BillDenton Does your file contain comments or string literals that have many `*`'s in a row?

**Comment by BillDenton** [comment] 2019-07-06 10:10
@matter123 Yes, lots. The first two lines are:
```
/**
 *************************************************************************************************
```
and there many other lines with lots iof "*"'s in a row.

**Comment by matter123** [comment] 2019-07-06 20:41
@BillDenton @r44083 This should be fixed upstream with version 1.12.15 of https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax. 

if you want the changes immediately, install the Better C++ Syntax extension
if you're okay with waiting a few days, you can use the VS Code Insider's release
if you're okay with waiting a while, the changes will eventually be pulled into VS Code stable

**Comment by BillDenton** [comment] 2019-07-08 09:15
I've installed the Better C++ syntax extension and upgraded to 1.36. It is all working. I'll uninstall the extension when the VS Code stable is next updated.

**Comment by alexr00** [comment] 2019-07-08 10:00
Duplicate of https://github.com/microsoft/vscode/issues/76774 in VS Code.

**Closed by alexr00** 2019-07-08 10:00 UTC
Labels: new release

**Comment by BillDenton** [comment] 2019-07-09 18:08
After the update to VS Code 1.36.1 is seems OK without the Better C++ syntax extension. Thanks.
