### ISSUE TITLE
Can not open large files

### ISSUE THREAD

**Issue by ilovesusu** [Microsoft/vscode#15729] opened 2016-11-18 14:35 UTC
- VSCode Version:1.7.1
- OS Version:Debian Testing

Steps to Reproduce:

1. Generate a 50mb file, about 2000000 lines
> $:bash
> $:i= 0
> $:while [ $i -le 3000000 ]; do echo "asdfghjjklooiyerqwuhgsdjg" >>hello; i=$(($i + 1)); done
2. Open a 50mb file

**Comment by ramya-rao-a** [comment] 2016-11-18 18:39
Closing as duplicate of #15393

**Closed** 2016-11-18 18:41 UTC
