### ISSUE TITLE
There is no useful FTP solution

### ISSUE THREAD

**Issue by agahtoruk** [Microsoft/vscode#37119] opened 2017-10-30 07:27 UTC
Hi,
VS Code has not FTP solution. I downloaded the **ftp-sync** and **ftp-simple** plugins but they are not useful. Notepad++ **npp-ftp** plugin is very useful for developers. I think every developer wants FTP solution like **npp-ftp** in VS Code. 
Thanks.

**Comment by maxibanki** [comment] 2017-10-30 09:05
Then contribute to these extensions or create an issue there, so they will meet your wishes. :)
But here is definitely not a place for such an issue. thx

**Comment by ManPython** [comment] 2017-12-02 12:17
@dbaeumer - is this finall decision that this issue is pined to "*extension-candidate" ?
https://github.com/Microsoft/vscode/issues/20861 - depend this issue
Coz we can wait soo long for some good FTP solution that bether is to still use notepad++ ..it's realy curious in this situation that VSC have so big potential for be the main editor and forgot about notepad++

**Comment by Cardinal90** [comment] 2017-12-03 12:40
The best FTP solution I found is actually [Deploy](https://marketplace.visualstudio.com/items?itemName=mkloubert.vs-deploy). It doesn't have `ftp` in its tags, so you won't find it that way.

**Comment by jrieken** [comment] 2018-01-10 01:06
closing as dupe of #20861

**Closed by jrieken** 2018-01-10 01:06 UTC
Labels: *extension-candidate
