### ISSUE TITLE
Indent rules don't work for some coding styles

### ISSUE THREAD

**Issue by ljusten** [Microsoft/vscode#32328] opened 2017-08-11 13:28 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
you-complete-me|Ric|1.0.36
togglehs|bbe|0.1.2
chromium-codesearch|cha|0.0.7
vscode-instant-markdown|dba|1.2.1
python|don|0.7.0
gn|lju|0.0.1
cpptools|ms-|0.12.2
difftomaster|pav|0.0.1
proto|pet|0.0.2
annotator|ryu|0.10.1
rewrap|stk|1.4.2
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

Write a function in C++ with parameters spread over 2 lines. The indent rules currently puts you 2 characters (or however many) in relative to the already indented second parameter line.

```
void Test(bool param1,
          bool param2) {
            ^ Indent rule puts you here
}

```
Instead, the indent rules should put you 2 characters in relative to the line where the function starts.

```
void Test(bool param1,
          bool param2) {
  ^ Indent should be here
}

```
This is extremely distracting, especially when pasting code from elsewhere.

Reproduces without extensions: Yes

**Comment by rebornix** [comment] 2018-09-19 22:50
Duplicate of https://github.com/Microsoft/vscode/issues/30859, let's track it there.

**Closed** 2018-09-19 22:50 UTC
Labels: *duplicate, editor-autoindent, under-discussion
