### ISSUE TITLE
Some bash commands cannot be found when connected to remote Ubuntu device

### ISSUE THREAD

**Issue by marcusnewton** [microsoft/vscode#136842] opened 2021-11-10 09:28 UTC
Recent 1.62.1 update causes some commands to not be available in terminal when connected to remote Ubuntu device. In my case, `nix-shell` and other Nix commands just result in `command not found`. I have not been able to find other missing commands.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.1
- OS Version: Windows 10 Home 21H1
- Remote OS Version: Ubuntu 20.04.3 LTS x86_64

Steps to Reproduce:

1. [Install Nix](https://nix.dev/tutorials/install-nix#linux) on an Ubuntu device
2. Use VS Code to connect to remote Ubuntu device
2. Enter `nix-shell --version`

**Comment by NikPiermafrost** [comment] 2021-11-10 11:35
Can confirm this exact behaviour on WSL remote option on a local Debian install with zsh

**Comment by marcusnewton** [comment] 2021-11-10 12:07
Rolling back to v1.61.2 it works just fine.

**Comment by bersbersbers** [comment] 2021-11-10 12:14
For me, similar problems (Windows 10 21H2, Remote SSH into OpenSUSE Leap 15.2). Problems in the terminal are compatible with the hypothesis that `.bash_profile` is no longer executed. Logon scripts are a bit special with OpenSUSE, but I think one interpretation is that 1.62.0 starts an interactive login shell, while 1.62.1 starts an interactive *non-login* shell. So I fixed a few of my issues by adding `. ~/.bash_profile` to my `.bashrc`.

However, I still cannot `git push` to any GitHub repo, neither from the GUI nor any terminal. Processes just hang. `ps` shows some `/data2/bers/opt/vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node  /data2/bers/opt/vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/git/dist/askpass-main.js Username for 'https://github.com':` 
 and `/bin/sh /data2/bers/opt/vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/extensions/git/dist/askpass.sh Username for 'https://github.com': ` which, when I call it, simply opens a node console:
```
Welcome to Node.js v14.16.0.
Type ".help" for more information.
```

I thought it might be the Remote SSH extension and downgraded it to 0.65.8, with no luck - same issue as with 0.66.0 and 0.66.1.

**Comment by bersbersbers** [comment] 2021-11-10 12:29
I think this issue is a duplicate of #136791, and my git issue of #136837. Both are on the Recovery milestone candidate list, see #136841.

**Closed** 2021-11-10 15:04 UTC
Labels: *duplicate
