### ISSUE TITLE
Consider renaming the SQL built in language to MS SQL

### ISSUE THREAD

**Issue by FelixZY** [microsoft/vscode#221648] opened 2024-07-13 23:47 UTC
Postgres supports dollar quoted strings as an alternative to regular `'<text>'` strings. This is useful when you need to include the `'` character itself but don't want to escape it.

The official documentation can be found [here](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING).

Unfortunately, the default SQL highlighter in VSCode does not seem to support this syntax.

**Steps to Reproduce**

1. Go to https://vscode.dev/
2. Create a new file
3. Set the "SQL" language mode
4. Input the following content:
```sql
comment on schema "public" is $$
  It's an apostrophe!
$$;

-- This is an SQL comment

select * from public.foo;
```

**Expected**

`'` should not start a new string. The content between `$<tag>$` and `$<tag>$` should be identified as a string and highlighted as such.

**Actual**
![Screenshot from 2024-07-14 01-44-39](https://github.com/user-attachments/assets/5284c2d0-1bce-49d6-a3c9-51767af55a9a)

**Additional context**

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: vscode.dev

Also tested in the desktop version with identical results.

**Comment by FelixZY** [comment] 2024-07-13 23:57
> The content between `$<tag>$` and `$<tag>$` should be identified as a string and highlighted as such.

Note that I consider this an _at minimum_ requirement. In reality, dollar quoted strings are often used to declare function bodies in postgres and there are therefore (perhaps more commonly) instances where the content inside the dollar signs would be better off using "regular" sql highlighting.

**Comment by alexr00** [comment] 2024-07-15 09:15
Th grammar we have is for MS SQL and doesn't support features outside that. Duplicate of https://github.com/microsoft/vscode/issues/132944

**Comment by FelixZY** [comment] 2024-07-15 09:27
In that case, I think you should rename the user-visible language mode to "MSSQL" rather than "SQL". I find just calling it "SQL" to be a deceptive marketing practice if you are not going to support other SQL dialects in it.

**Comment by alexr00** [comment] 2024-07-15 09:35
It is fair to say that MS SQL won't work for all SQL flavors. I will discuss renaming it with the team.

**Comment by alexr00** [comment] 2024-07-17 14:18
Based on some quick digging, MS SQL uses Transact-SQL (T-SQL). The most appropriate thing to rename the built in SQL grammar to would be T-SQL. However, I'm not sure that T-SQL will mean something to most users.

**Comment by alexr00** [comment] 2024-07-17 14:29
I'm going to wait and try renaming at the very beginning of our next milestone so that I can see if any insiders users are thrown off first.

**Comment by alexr00** [comment] 2024-07-30 10:44
I think T-SQL is not well known enough and will be confusing. I'll try renaming to MS SQL.

**Closed** 2024-07-30 11:02 UTC
Labels: grammar, under-discussion

**Comment by alexr00** [comment] 2024-08-26 18:59
To verify:
- Open a file in VS Code
- Open the language picker from the status bar
- Verify that you don't see SQL, but instead see MS SQL
