### ISSUE TITLE
Cannot add a breakpoint

### ISSUE THREAD

**Issue by BenjaminLeseur** [microsoft/vscode#112472] opened 2020-12-14 13:38 UTC
Issue Type: <b>Bug</b>

Hello,

I cannot add a new breakpoint in a PHP file, breakpoints previously added (in version 1.51.x) work with the debugger.

To reproduce :
- Open a PHP file
- See some breakpoints (red bullet in left margin)
- Click on a breakpoint remove it
- Click on the same place, a breakpoint is not added

Expected result :
- a click in left margin sould add a breakpoint (marked by a red bullet)

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.8.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2428)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (0.85GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8d57e832-0295-45a4-a2ad-945cc6001c7b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
vscode-intelephense-client|bme|1.5.4
xml|Dot|2.5.1
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
volt-phalcon-language|fbc|1.2.3
php-debug|fel|1.13.0
todo-tree|Gru|0.0.192
phpcs|ika|1.0.5
php-docblocker|nei|2.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30233462
vsjup459:30229593

```

</details>

**Comment by IvanBernatovic** [comment] 2020-12-14 13:55
/duplicate of #112288

The issue is the php-debug extension. The extension is not actively maintained anymore and should be updated for it to work. Here's a [temp workaround](https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329) posted in the issue of the extension itself.

**Closed** 2020-12-14 14:06 UTC
Labels: *duplicate, new release
