### ISSUE TITLE
git.path doesn't work

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode#12992] opened 2016-09-29 11:00 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Set git path to: ``"git.path": "C:\\msys64\\usr\\bin\\git.exe",`
2. You get error `ENOENT: no such file or directory, lstat 'C:\c'`

Git is not in my path and I don't want it in my path because it brings along bash which is hindering with msys and so on.

**Comment by joaomoreno** [comment] 2016-09-29 14:19
Seems to be a duplicate of #10281, let's talk there.

**Closed** 2016-09-29 14:19 UTC
