### ISSUE TITLE
Flaky smoke test: install and activate vscode-smoketest-check extension

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#114707] opened 2021-01-21 14:07 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=101547&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=73

> Error: Active element not found. Current active element is 'HTML > BODY.mac > DIV.file-icons-enabled.monaco-workbench.mac.chromium.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV#webview-extensionEditor > WEBVIEW.webview.ready'. Looking for .quick-input-widget .quick-input-box input

```
  26 passing (2m)
  2 pending
  1 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Extensions
           install and activate vscode-smoketest-check extension:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)
```

**Comment by sandy081** [comment] 2021-01-21 14:21
Duplicate of https://github.com/microsoft/vscode/issues/113746

I am not closing this as this keeps coming.

@mjbvz Are there any plans to fix the root cause of this bug - https://github.com/microsoft/vscode/issues/110276 ?
@bpasero If not, is there another way to open Command Pallette?

**Comment by alexdima** [comment] 2021-01-21 14:23
@sandy081 An option might be to configure `webview.experimental.useIframes` for this smoke test.

**Comment by sandy081** [comment] 2021-01-21 16:42
Yup, I am not testing web views. So I can use that setting which is also recommended as workaround in the issue.

**Closed** 2021-01-21 16:46 UTC
Labels: smoke-test-failure
