### ISSUE TITLE
redundant enter character after auto-completion

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#25930] opened 2017-05-04 20:54 UTC
- VSCode Version:Version 1.12.0 72672be0b7d3eef0784077b880615f91b7ec85aa
- OS Version: Ubuntu 17.04

Steps to Reproduce:
![vscodebug](https://cloud.githubusercontent.com/assets/4303130/25724506/c25b7e96-314e-11e7-94f4-d0008372a39a.gif)

There has a redundant enter character been insert into my code after I enter "enter" key to finish auto-completion.

**Comment by mjbvz** [comment] 2017-05-05 00:52
Do you have any extensions installed? Does this repo if you run code with the `--disable-extensions` flag?

Also, do you have any custom keybindings? What keyboard layout / input method are you using?

**Comment by mjbvz** [comment] 2017-05-05 02:22
@jrieken It looks the behavior of completions items has changed. Could you help take a look here? Here's the steps to reproduce this:

* In a js file, type out `console`
* This should bring up the completion list while typing
* Then press enter to accept the suggestion for `console`

In VSCode 1.11, this would accept the current suggestion. In VSCode 1.12, this instead inserts a new line after `console`

I'm double checking a few other languages to make sure this is not js/ts specific

**Comment by mjbvz** [comment] 2017-05-05 02:24
Ok, confirmed this in python as well. It doesn't seem to effect word based suggestions however or user snippets

**Comment by mjbvz** [comment] 2017-05-05 03:37
This change seems to have been by-design: https://github.com/Microsoft/vscode/commit/89da6ab81fcc552760a1a8972f5e2f3d6a820ecf

**Comment by joaomoreno** [comment] 2017-05-05 06:07
More context: #24420

**Comment by jrieken** [comment] 2017-05-05 06:42
Closing as duplicate of #24420

**Closed by jrieken** 2017-05-05 06:42 UTC
Labels: javascript

**Comment by hangxingliu** [comment] 2017-05-05 07:10
Thank VS Code for making me more adaptive in each time I upgrade the VS Code. :sob:
