### ISSUE TITLE
`inline-folder` content garbled sometime 

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#150385] opened 2022-05-25 15:07 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.5.0

I don't know how to reproduce, It happend from time to time
Steps to Reproduce:

1. folde a code block
2. the end of line show three dot at the end of line
3. sometime it's not thee dot, it show `â‹¯`

This is correct screenshot, I didn't capture the wrong one after I restart vscode
<img width="360" alt="Screen Shot 2022-05-25 at 10 52 04 PM" src="https://user-images.githubusercontent.com/20318608/170293451-0a9e6cfd-b6c0-4df5-823e-3795df56a0bf.png">

I check the code, three dot was render by pseudo classes `inline-folder` content `⋯`

**Comment by aeschli** [comment] 2022-05-30 08:49
duplicate of #145897

**Closed by aeschli** 2022-05-30 08:49 UTC
