### ISSUE TITLE
Java script syntax highlight considers all words starting with "var" a variable declaration

### ISSUE THREAD

**Issue by PD75** [Microsoft/vscode#4234] opened 2016-03-15 07:53 UTC
- VSCode Version: 0.10.11
- OS Version: Win 10 all latest patches

Steps to Reproduce:

1. Create a variable named "var...."
2. Syntax highlight thinks it is a variable declaration in the name:

![image](https://cloud.githubusercontent.com/assets/10294795/13770995/03aa9e6a-ea8b-11e5-8714-c262cf01e2e0.png)

**Comment by aeschli** [comment] 2016-03-15 08:42
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-03-15 08:42 UTC
