### ISSUE TITLE
convert js file to ts -- does not recognize tab indentation

### ISSUE THREAD

**Issue by cjmaroney01** [Microsoft/vscode#57525] opened 2018-08-29 16:33 UTC
i accidentally created a file as a .js file, and then renamed it to .ts.   When i did this, the tslint INSISTED that i was not using tabs to indent, even though i was.  The only way I could fix it was by making a keyboard binding for "indent using tabs" and apply it by doing that keyboard combination.

Later, a colleague and I were converting .js files to .ts that already existed, and we have the same problem

**Comment by dbaeumer** [comment] 2018-08-30 07:52
@egamma assigning to you since the problems come from TSLINT.

**Comment by egamma** [comment] 2018-09-14 12:44
I cannot reproduce this given the information provided:
- What is the tslint.json
- what was the contents of the  .js file when you renamed it, 
- what was the exact error message from tslint?

I´ve tried to reproduce it with tslint.json

```
        "indent": [
            true,
            "tabs"
        ],
```

and a .js file that has a tab indent, but I could not reproduce the error.

**Closed** 2018-09-21 19:08 UTC
Labels: needs more info
