### ISSUE TITLE
File extension association is not respected when file extension and language id share the same icon

### ISSUE THREAD

**Issue by robertohuertasm** [Microsoft/vscode#27475] opened 2017-05-29 21:35 UTC
- VSCode Version: 1.13.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create an `icon A` theme and associate some icon to a `language id` (let's say Elm)
2. Associate another `icon B` to one of the extensions already associated  (in this case the only one `.elm`) by the extension supporting the `language id`. IMPORTANT: `icon B` must be already be in use by a `language id` association.
3. The expected behavior would be that the `.elm` files would show the `B icon` but instead `A icon` is being shown.

According to [vscode api docs](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_file-association):

> A file extension match is preferred over a language match, but is weaker than a file name match.

Also, I remember talking to @aeschli about this in [vscode#10804](https://github.com/Microsoft/vscode/issues/10804#issuecomment-243403933).

You can also view the original report in [vscode-icons#964](https://github.com/vscode-icons/vscode-icons/issues/964), specifically this [comment](https://github.com/vscode-icons/vscode-icons/issues/964#issuecomment-304836687)

**Comment by JimiC** [comment] 2017-05-30 07:51
This is a false positive as demonstrated in https://github.com/vscode-icons/vscode-icons/issues/964#issuecomment-304800323

**Comment by robertohuertasm** [comment] 2017-05-30 08:24
@JimiC, @aeschli I tested this yesterday with `elm` and didn't work. I'll check it out again and let you know the result in case I did something wrong yesterday.

**Comment by robertohuertasm** [comment] 2017-05-30 08:45
@JimiC @aeschli I confirm this is still happening.

**Comment by robertohuertasm** [comment] 2017-05-30 10:22
Please check the latest comments in [vscode-icons#964](https://github.com/vscode-icons/vscode-icons/issues/964#issuecomment-304836687)

**Comment by aeschli** [comment] 2017-10-03 13:38
I wasn't able to reproduce in 1.17. This is what I tried:
Note the html language mode has file extensions 'html' and 'jsp'.

![image](https://user-images.githubusercontent.com/6461412/31127975-9f2e9826-a850-11e7-8ba4-28c87f21c2fb.png)

You can see that the file extension association wins against the language mode association.
Did I misunderstand the bug report?

**Comment by JimiC** [comment] 2017-10-03 13:58
@aeschli The bug is still present. The scenario involves installing a 3rd party extension for language syntax highlight. 

I can confirm that the bug isn't present when you are overriding `vscode` native supported extensions.

**Comment by aeschli** [comment] 2017-10-03 14:44
There is no difference in how built-in and external extensions define language ids and file associations. I tried the following, still all seems to be fine:
![image](https://user-images.githubusercontent.com/6461412/31131316-106572d6-a85a-11e7-906c-60e4a0ba1918.png)

**Comment by JimiC** [comment] 2017-10-03 15:29
You see in our scenario
```
"fileExtensions": {
   "elm": "_elixir"
},
"languageIds": {
   "elm": "_elm"
}
```
is not working.

**Comment by aeschli** [comment] 2017-10-04 07:15
@JimiC Isn't this what I have in my example?
Can you provide a complete sample that includes a minimal file icon theme, the involved language configuration (e.g. for elm) and a file structure that reproduces the issue?

**Comment by JimiC** [comment] 2017-10-04 10:03
@aeschli There is nothing wrong with your example. The key difference in your scenario is that you haven't installed the `elm` [extension](https://marketplace.visualstudio.com/items?itemName=sbrink.elm). If I do so too, (have it disabled), then `elm` has the `elixir` icon but if I have it enabled then `elm` has the `elm` icon instead of `elixir`.
The issue here is that the enabling of 3rd party extension causes the `languageId` to override `file extension` something that is against the stated order.

**Comment by aeschli** [comment] 2017-10-04 14:15
Sorry, not for me:
![image](https://user-images.githubusercontent.com/6461412/31180476-08e5abe6-a91f-11e7-9e62-d60a5ef9c1cd.png)


Closing this issue, I assume the bug is in your theme or got fixed in the meantime.
Please provide a complete sample with a minimal file icon theme and steps to reproduce.

**Comment by JimiC** [comment] 2017-10-04 14:19
@aeschli Will do. Thanks for your time.

**Comment by JimiC** [comment] 2017-10-04 16:53
@aeschli I found some time to iterate over it again and figure out what actually produces this bug, in order to provide repro steps, as you asked.

What I've done.
- Use `vscode` with no extensions enabled.
- Use the `Minimal` File Icon Theme.
- Replace the `vs_minimal_icons.json` found in `C:\Program Files\Microsoft VS Code\resources\app\extensions\theme-defaults\fileicons` with the provided `json`.
- Open a folder in `vscode` and create a file with `.elm` as the file extension.
- Notice that the file has the `root folder dark` icon (correct).
- Install and enable the `elm` extension.
- Reload `vscode`.
- Notice that the file now has the `folder dark` icon (wrong).

And here is something that might help you even more:
- Place `"elixir": "_f_elixir"` in `languageIds` after `"elm": "_f_elm"`
- Notice that the file now has the `root folder dark` icon (correct).

I hope that this time I've been more useful.

Appendix
----
```json
{
	"iconDefinitions": {
		"_root_folder_dark": {
			"iconPath": "./images/RootFolder_16x_inverse.svg"
		},
		"_root_folder_open_dark": {
			"iconPath": "./images/RootFolderOpen_16x_inverse.svg"
		},
		"_folder_dark": {
			"iconPath": "./images/Folder_16x_inverse.svg"
		},
		"_folder_open_dark": {
			"iconPath": "./images/FolderOpen_16x_inverse.svg"
		},
		"_file_dark": {
			"iconPath": "./images/Document_16x_inverse.svg"
		},
		"_root_folder": {
			"iconPath": "./images/RootFolder_16x.svg"
		},
		"_root_folder_open": {
			"iconPath": "./images/RootFolderOpen_16x.svg"
		},
		"_folder_light": {
			"iconPath": "./images/Folder_16x.svg"
		},
		"_folder_open_light": {
			"iconPath": "./images/FolderOpen_16x.svg"
		},
		"_file_light": {
			"iconPath": "./images/Document_16x.svg"
		},
		"_f_elixir": {
			"iconPath": "./images/RootFolder_16x_inverse.svg"
		},
		"_f_elm": {
			"iconPath": "./images/Folder_16x_inverse.svg"
		}
	},

	"folderExpanded": "_folder_open_dark",
	"folder": "_folder_dark",
	"file": "_file_dark",
	"rootFolderExpanded": "_root_folder_open_dark",
	"rootFolder": "_root_folder_dark",
	"fileExtensions": {
		// icons by file extension
		"elm": "_f_elixir"
	},
	"fileNames": {
		// icons by file name
	},
	"languageIds": {
		// icons by language id
		"elixir": "_f_elixir",
		"elm": "_f_elm"
	},
	"light": {
		"folderExpanded": "_folder_open_light",
		"folder": "_folder_light",
		"rootFolderExpanded": "_root_folder_open",
		"rootFolder": "_root_folder",
		"file": "_file_light",
		"fileExtensions": {
			// icons by file extension
		},
		"fileNames": {
			// icons by file name
		},
		"languageIds": {
			// icons by language id
		}
	},
	"highContrast": {
		// overrides for high contrast
	}
}
```

**Comment by aeschli** [comment] 2017-10-05 14:32
Oh, now I see. Thanks!

**Closed** 2017-10-05 16:05 UTC
Labels: needs more info, themes
