### ISSUE TITLE
VSCode uninstalled itself with Windows Update

### ISSUE THREAD

**Issue by metagrapher** [microsoft/vscode#124201] opened 2021-05-19 18:34 UTC
Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: latest
OS Version: Edition Windows 10 Pro
Version Dev
Installed on ‎5/‎14/‎2021
OS build 21382.1
Experience Windows 10 Feature Experience Pack 321.12100.0.3
Steps to Reproduce:

Have VS Code installed and up to date as of 5/14/2021
Update Windows 10 to OS build 21382.1

This ticket was #124153 but that was inappropriately closed, and so this issue has been recreated. Feel free to remove the duplicate if you would prefer to reopen the original ticket. Or track it here for reference.

**Comment by metagrapher** [comment] 2021-05-19 18:51
It is worth noting on this ticket that VSCode was not open at the time of downloading the update, nor was it opened between that time and restarting.  I do not have any underscore directories, nor any remnants of the software that I can find. It's like it was never installed as far as I can find, but as stated previously, I would be happy to perform any troubleshooting and provide more info. 

Please don't close this ticket based on an assumption.

**Comment by joaomoreno** [comment] 2021-05-20 07:29
Can you reproduce the issue?

**Comment by metagrapher** [comment] 2021-05-20 23:21
You are asking me to roll back my Windows installation so that I might reinstall VSCode and then ask Microsoft to please give me specifically the new dev build 21382.1 again so that I might re-apply the recent update in hopes that that it uninstalls VSCode again in the same way? This is a very strange ask, I must say. 

No, I cannot recreate the problem. Or will not. This is not a reasonable request in this case.
I am willing to perform other debugging steps, but compromising my work machine is not one I will do.

Based on the other thread #52855 it may be possible that, in the background, without showing any dialogs, that VS Code did attempt to update itself while Windows was updating the OS. I'm not sure how to discover if this did happen. 

Regardless, the fix does seem to be that VSCode should not attempt to update itself while Windows is updating, and that if it somehow unintentionally does, should leave a "dead-man's switch" style script, where VSCode is the dead-man, that would inform the user of the error on fresh login, or otherwise simply re-install the software/resume the update.

I am, of course, quite interested to discover if that did happen, or what happened, and rolling back my OS would absolutely destroy any further debugging information.

**Comment by joaomoreno** [comment] 2021-05-21 07:11
> Regardless, the fix does seem to be that VSCode should not attempt to update itself while Windows is updating, and that if it somehow unintentionally does, should leave a "dead-man's switch" style script, where VSCode is the dead-man, that would inform the user of the error on fresh login, or otherwise simply re-install the software/resume the update.

Absolutely agree. And the fix would be the same as for https://github.com/microsoft/vscode/issues/52855, since VS Code should just not attempt to upadte ifself if Windows is about to go down. For that reason, I propose once again to close this issue as a duplicate of that. Sorry for not having better news.

**Comment by metagrapher** [comment] 2021-05-21 07:43
Sure, I understand that desire, though we don't know that is in fact what happened, and since there's zero evidence that I can find on my machine of VS Code even having been installed, it seems that either the issue has become exponentially worse, or it's a different bug entirely.  I also may not know the right places to search for evidence of a previous install, if not in Program Files or AppData

From this point we cannot say for certain in this case that Windows Update is what caused this, either, since there was a time window in which this occurred. If this were my software, I would track these separately, but note that they may be related. It's worth attempting to replicate on a dev box, I just don't have a machine at my disposal to do that myself. 

Do you have any ideas about logs I might be able to find or something that would otherwise indicate when and quite what happened, other than just hunches?

Thank you for looking into this

**Comment by joaomoreno** [comment] 2021-05-26 11:55
> Do you have any ideas about logs I might be able to find or something that would otherwise indicate when and quite what happened, other than just hunches?

Sorry for the delay. Unfortunately I don't think you'd find many logs behind, especially if you say the entire VS Code folder is gone.

**Comment by metagrapher** [comment] 2021-05-27 15:44
Right on. I suppose I was hoping that perhaps there was some system log of installation and uninstallation, though I know better than to assume that Windows has any record of registry changes or application installation/uninstallation in the system logs. 

FWIW after installing VS Code Insiders I now have a broken context menu entry for VS Code.  Sharing because it seems related. 

Thank you for looking into this bizarre issue.

**Comment by joaomoreno** [comment] 2021-05-27 17:51
> FWIW after installing VS Code Insiders I now have a broken context menu entry for VS Code.

What is broken about it?

**Comment by metagrapher** [comment] 2021-05-27 17:56
That is a very thoughtful question! Thank you
The icon itself is a broken link icon and clicking on it has no noticeable effect.

**Comment by joaomoreno** [comment] 2021-05-28 10:11
> The icon itself is a broken link icon and clicking on it has no noticeable effect.

Got it. That's more a sign that there was a failed update, rather than a purposeful uninstallation. Thanks for the update. Closing this for now.

**Closed by joaomoreno** 2021-05-28 10:11 UTC
Labels: needs more info
