### ISSUE TITLE
red chunks of code in jsx files with 1.26 &1.27

### ISSUE THREAD

**Issue by samuelcolvin** [Microsoft/vscode#56912] opened 2018-08-21 14:36 UTC
This is very weird, I can't understand why no one else has reported it.

- VSCode Version: 1.26.0 and also 1.27.0-insider
- OS Version: Ubuntu 18.04

![image](https://user-images.githubusercontent.com/4039449/44407492-21f0cd80-a556-11e8-9b4f-31330e3ada07.png)

Steps to Reproduce:

1. open almost any jsx file in vscode, eg. [this file](https://github.com/samuelcolvin/nosht/blob/master/js/src/events/Book.js)
2. You should see chunks of red text as per screenshot above.

Inspecting the red elements, they all have class `mtk15` and color `#f44747`, that class doesn't seem to mean much to google but the color corresponds to ["invalid"](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/common/themes.ts#L90) apparently. However there's not clear reason why those blocks are marked as invalid - they're perfectly valid js/jsx.

Things I've tried:
* disabling extensions
* hoving over the red text to see an error - no error shows
* trying with insider
* adding invalid js or unknown props to try to replicate - doesn't match, errors get a squiggle, not this red text.
* checking settings for any odd colours - know apparently
* googled a lot to try and find a matching problem, nothing comes up

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-08-21 14:53
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/648

**Closed by mjbvz** 2018-08-21 14:53 UTC
Labels: javascript

**Comment by samuelcolvin** [comment] 2018-08-21 14:56
thanks, sorry didn't see that.
