### ISSUE TITLE
Incorrect handling of hyperlinks around word wrapping

### ISSUE THREAD

**Issue by john-cj** [microsoft/vscode#67048] opened 2019-01-24 11:06 UTC
- VSCode Version: 1.30.2
- OS Version: Win 7

Here are word separators in my VS Code (just the default ones):

![Word separators](https://user-images.githubusercontent.com/18004961/51673827-10699100-1fe0-11e9-83bb-e88d8b0c65f4.png)

And here is how long hyperlink will look after the bullet:

Enough space:

![Enough space](https://user-images.githubusercontent.com/18004961/51674457-bcf84280-1fe1-11e9-8e6d-ec8c68fb7f33.png)

Not enough space. The hyperlink is moved to the new line:

![Not enoght space](https://user-images.githubusercontent.com/18004961/51674474-c8e40480-1fe1-11e9-9805-9f99936de3fc.PNG)

Compare it with Atom:

![Atom](https://user-images.githubusercontent.com/18004961/51674492-d3060300-1fe1-11e9-8d6f-a893d4395467.PNG)

or Sublime Text:

![Sublime Text](https://user-images.githubusercontent.com/18004961/51674637-3db73e80-1fe2-11e9-96ab-b20da474d53f.PNG)

**Comment by rebornix** [comment] 2019-01-25 18:50
I can't reproduce this issue 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/876920/51766290-081c5f00-208f-11e9-810f-2747ab17e87a.png">

**Comment by john-cj** [comment] 2019-01-25 19:33
@rebornix It seems you use it on Mac? Probably its Window-specific issue?

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|1.93GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none


![vs](https://user-images.githubusercontent.com/18004961/51768303-fb305780-20f0-11e9-83df-5168060d417a.png)

**Comment by john-cj** [comment] 2019-01-27 10:40
I asked some guys to see the same issue on Linux and Mac, and they have it too:

Linux:

![_linux](https://user-images.githubusercontent.com/18004961/51799930-ebbc2600-2238-11e9-8ce8-8a2d3516fd21.png)

Mac:

![mac](https://user-images.githubusercontent.com/18004961/51799933-f1197080-2238-11e9-9fed-3a3bd1dd3118.png)

**Comment by alexandrudima** [comment] 2019-10-07 12:48
I also cannot reproduce... This might have been fixed in the meantime. I have tried on Windows:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66312689-6897b780-e911-11e9-8fe0-4e99a51632e2.gif)

**Closed** 2019-10-16 16:53 UTC
Labels: editor-wrapping, needs more info
