### ISSUE TITLE
When using multiple carets, autocomplete only completes the first one selected

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#1545] opened 2015-12-21 15:43 UTC
An image says more than a thousand words:

![multicaret-completeonlyfirst](https://cloud.githubusercontent.com/assets/516972/11934345/f0d580b4-a801-11e5-88e5-43e74fd9a595.gif)

**Comment by jrieken** [comment] 2017-04-05 12:40
dupe of #16037

**Closed by jrieken** 2017-04-05 12:40 UTC
Labels: bug, suggest
