### ISSUE TITLE
"before cursor" in timeline contribution may be hard for implementors

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91627] opened 2020-02-26 23:05 UTC
Refs: https://github.com/microsoft/vscode/issues/91330#event-3075425865

The timeline options is defined as:

```ts
export interface TimelineOptions {
  /**
   * A provider-defined cursor specifing the range of timeline items that should be returned.
   */
  cursor?: string;

  /**
   * A flag to specify whether the timeline items being requested should be before or after (default) the provided cursor.
   */
  before?: boolean;
```

Just thinking about databases and such that I've used, take Cosmos DB as an example. After you read results, it gives you a cursor to the next set of items you can use to continue the query. Those cursors _only_ allow you to fetch items that come after the cursor, not before. A CosmosDB-backed timeline provider would be unable to correctly implement the timeline API, as if it's given a token with `before: true`, it can't derive the page of results that came before it. I'm actually not aware of any continuation-based data stores that allow this functionality, though I'm sure there are some out there.

**Comment by rebornix** [comment] 2020-02-26 23:28
I'm confused about the `cursor` too, especially whether the boundaries are included or not

```
[before, after]
before [ ... ] after 
[before ... ] after
```

**Comment by connor4312** [comment] 2020-02-26 23:38
The way I would kind of expect it to work as a naive services person would be for vscode to stash the cursors leading up to the current page (if it paged out any information) and give them back to me to re-retrieve older pages.

**Comment by eamodio** [comment] 2020-02-27 18:42
`before` is mainly to be used to ask the provider for the latest data it might be missing -- so instead, maybe I should just remove the `before` flag, and instead make the request with no starting cursor, and setting `limit` to be the end point

**Comment by eamodio** [comment] 2020-03-02 20:43
The plan is to remove the `before` flag

**Comment by eamodio** [comment] 2020-03-23 17:48
Closing as a duplicate of #91722

**Closed by eamodio** 2020-03-23 17:48 UTC
Labels: bug, timeline
