### ISSUE TITLE
bad experience for markdown

### ISSUE THREAD

**Issue by mu-yu** [Microsoft/vscode#20523] opened 2017-02-13 02:53 UTC
- VSCode Version: 1.9.1
- OS Version: win 10

Steps to Reproduce:
bad experience for markdown:
1. No auto preview  on open with split window. 
2. No auto close preview when file close. 
3. No auto switch preview when switch file.

**Comment by mjbvz** [comment] 2017-04-12 00:06
This is a duplicate of #2766

**Closed by mjbvz** 2017-04-12 00:06 UTC
Labels: duplicate, feature-request, markdown
