### ISSUE TITLE
editor preview tabs looks stronger then active editor tabs

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6759] opened 2016-05-24 09:46 UTC
#6536

See attached screen shot. The preview tab (italics & bold(?)) looks a lot more prominent then the tab of an active editor. That conflicts with my mental model of a preview

<img width="450" alt="screen shot 2016-05-24 at 11 45 05" src="https://cloud.githubusercontent.com/assets/1794099/15499547/1280c72e-21a5-11e6-98ae-171c4d5a3522.png">

**Comment by bpasero** [comment] 2016-05-24 12:44
Noticed this too but it could just be a consequence of the font we are using. We could also play with opacity to draw it less prominent.

**Comment by bpasero** [comment] 2016-05-25 06:21
@bgashler1 maybe you could advise if there is a CSS way to make this better. I do see that the font moves and seems to change its visual font-weightness once it turns italic but I am not sure how to prevent that. Unless we want to play with opacity.

**Comment by joaomoreno** [comment] 2016-05-31 08:34
As a user that doesn't use Open Editors and has auto save enabled, I'm not getting used to a different decoration for unpinned files. Often I look up there and I get the strange feeling that my file is somehow unsaved, which is unfounded since files are automatically saved...

**Comment by bpasero** [comment] 2016-05-31 08:50
We should introduce the option to disable preview editors because when you are not having tabs enabled, they are less useful. This is https://github.com/Microsoft/vscode/issues/2754

**Comment by joaomoreno** [comment] 2016-05-31 09:09
Would it be possible to automate, when I have auto save and tabs and open editors hidden? The number of settings I need to change to get my workflow is starting to grow...

**Comment by bpasero** [comment] 2016-05-31 09:11
@joaomoreno I don't like to change the behaviour of the UI based on other settings you do. There are people that want no preview tabs but still have tabs enabled. How do you please those?

**Comment by joaomoreno** [comment] 2016-05-31 09:36
I didn't say that was the one exclusive way of disabling it. But if someone has no tabs nor open editors, preview editors don't mean anything, right?

**Comment by bpasero** [comment] 2016-05-31 09:46
I am not sure you can say that. Preview editors have nothing to do with tabs or the "opened editors" view. It is a state an editor can have in an editor stack. The stack cannot be disabled, so the preview state always applies. Someone might want to benefit from a stack without seeing it (via tabs) but still have the auto-clean up feature that not every editor ends up on the stack.

I see where you are coming from, as much as possible you want the old behaviour back. That is why I think settings are needed.

**Comment by joaomoreno** [comment] 2016-05-31 14:20
Sold!

**Comment by bgashler1** [comment] 2016-05-31 21:56
@bpasero yes, I think there is a font weight change occuring (which also seems to be causing #6792).  I will see what I can dig up and get back to you on these issues.

**Comment by bgashler1** [comment] 2016-06-03 16:36
@jrieken I'm trying to reproduce this font-weight issue on my Mac, but I don't seem to be experiencing the same problem.

(I'm on the latest build Ben put up on the builds site, commit 7067520fc9db97d37e7c7f9416bb50f5539319e9)
![screen shot 2016-06-03 at 9 33 44 am](https://cloud.githubusercontent.com/assets/11839736/15785846/4e130fe2-296e-11e6-81a2-f8ecfcdd3297.png)

**Comment by bgashler1** [comment] 2016-06-03 17:12
Ahh!!!  I just figured it out!

You guys most likely don't have Segoe UI installed.  So what's happening is your font is SF (San Fransisco) and mine is Segoe UI (which is why I couldn't reproduce).  When I switched to SF, then I was able to reproduce.

**Comment by bgashler1** [comment] 2016-06-03 19:11
Actually, not even the San Fransisco Font was working, so anyone seeing this problem was actually seeing Helvetica Neue Light using our current rule in our CSS:

```
.monaco-shell {
    font-family: Segoe WPC,Segoe UI,SFUIText-Light,HelveticaNeue-Light,sans-serif;
}
```
Note that `SFUIText-Light` does not work in Chrome.  The [ideal way](https://webkit.org/blog/3709/using-the-system-font-in-web-content/) to use this system font is not available in Chrome yet.  So the workaround that Chrome has introduced is `font-family: 'BlinkMacSystemFont'`.  We'll want to keep our eyes on Apple's progress in standardizing the aforementioned ideal way (once Chrome fixes [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=554590) we should switch to the ideal way).

So what does this mean?  Well, we Helvetica Neue Light does not work as it should with italics unless we explicitly set a font-weight of 300.

## Possible Solutions

### 1. We can temporarily use San Fransisco by using the `'BlinkMacSystemFont'` value.  Later we would adopt the ideal way.  For now, the CSS would be this...
```
.monaco-shell {
    font-family: Segoe WPC,Segoe UI,'BlinkMacSystemFont',HelveticaNeue-Light,sans-serif;
}
```
<img width="584" alt="screen shot 2016-06-03 at 12 02 36 pm" src="https://cloud.githubusercontent.com/assets/11839736/15789836/1cd7e2f8-2983-11e6-8c56-2b053d9c5bbe.png">

As you can see, we may want to adjust some things like kerning and font-weight.


### 2. We can standardize our font to always be Segoe UI on all OS platforms (like it is on Windows, and also on my Mac since I have it installed) by installing the font with VS Code for all users (possibly the font license wouldn't allow this?)


### 3. Less desirable: We can avoid using San Fransisco for now and switch HelveticaNeue-Light to HelveticaNeue to fix the problem.  However, this is Mac's old system font and is considered less legible from a UX perspective.
```
.monaco-shell {
    font-family: Segoe WPC,Segoe UI,HelveticaNeue,sans-serif;
}
```

**Comment by bpasero** [comment] 2016-06-04 06:22
@bgashler1 nice findings! we recently changed our font on Mac OS to San Francisco (see https://github.com/Microsoft/vscode/issues/7123). It turns out on Capitan we always used Helvetica for quite a while without even noticing it.

With this change, I no longer see the font dropping when changed from normal to italic. I still see a little bit of stronger weight when the font is italic vs non italic.

**Comment by bgashler1** [comment] 2016-06-04 20:31
That's great, @bpasero!  I'll leave this issue open and look into the font weight.  Can you put a build up that has the change in #7123 and your stacks so I can look into it?  Or, is your branch going to be merged in Alpha soon?  If so, I can just look at Alpha branch.  Thanks!

**Comment by bpasero** [comment] 2016-06-05 00:22
Everything is on alpha.

**Comment by yisibl** [comment] 2016-06-11 03:45
In any place, such as the East Asian language Chinese Italic is not good, because this is the generation algorithm of the s system in italics.

**Comment by bgashler1** [comment] 2016-06-18 00:43
@bpasero I just verified that the fix for this is to add `font-weight:300` to the `.monaco-shell`.  This should fix it for all exiting fonts.  Would you like me to push the change up myself?

**Comment by bpasero** [comment] 2016-06-18 06:22
@bgashler1 if you do a PR I can have a look at it. Thanks.

**Comment by bpasero** [comment] 2016-06-28 04:59
Still have to push it :)

**Closed** 2016-06-28 07:45 UTC
Labels: tabs, ux
