### ISSUE TITLE
Bring Back Old VS Code File Icon

### ISSUE THREAD

**Issue by jjrabbit** [microsoft/vscode#78503] opened 2019-08-05 14:08 UTC
Can you guys please bring back the old VS Code File Icon?

The old file icon (blue VS Code logo) was much easier to spot, now the icon just looks like a notepad file:

![vscode](https://user-images.githubusercontent.com/43035322/62470615-d20c1600-b768-11e9-969d-d24d094728b8.png)

**Comment by misolori** [comment] 2019-08-05 16:58
This is our file icon, it seems like you may have a bug that isn't showing the correct file. Try right-clicking on the file > Open with... > Choose another > Visual Studio Code (check "Always use this app to open .js files") and see if that updates the icon.

Here's what I am seeing:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/35271042/62481428-42b23300-b767-11e9-9f6d-9293a009823a.png">

**Comment by jjrabbit** [comment] 2019-08-05 18:54
Huh, that's really interesting that you have separate icons for each file type.

I tried your suggestion however the icon is the same.  At the very least it definitely shows the correct VS Code file icon because when I change the file explorer View to "Large Icons" the logo becomes visible:

![vscodeicon](https://user-images.githubusercontent.com/43035322/62487447-d8fa4f00-b78f-11e9-8126-0f482491baec.jpg)

Unfortunately I prefer to keep my project files on the "Details" View.

Just wondering but were your icons bundled with the default installer or did you add/install them separately?

Here is additional info:

VS Code Version 1.36.1 (user setup)
Windows 10 Version 1903 (build 18362.267)

**Comment by misolori** [comment] 2019-08-10 17:18
@jjrabbit these are bundled with the installer, it's likely an issue with the Windows file icon cache which we've seen before. One thing you might try is to re-install (just make sure you backup your settings/extensions). Since we have no reliable way to debug/reproduce I am going to close this as it's a bug we can't fix. Please see https://github.com/microsoft/vscode/issues/60716.

**Closed by misolori** 2019-08-10 17:18 UTC
Labels: needs more info
