### ISSUE TITLE
Flaky integration test: webviews with retainContextWhenHidden should preserve their page position when hidden

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#138612] opened 2021-12-07 17:28 UTC
```
  1 failing
  1) vscode API - webview
       webviews with retainContextWhenHidden should preserve their page position when hidden:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://github.com/microsoft/vscode/runs/4444508159?check_suite_focus=true

**Comment by bpasero** [comment] 2021-12-09 16:17
Again but this time a variant of the test:

```
1) vscode API - webview
       webviews with retainContextWhenHidden should preserve their context when they are hidden:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=146220&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=486

**Comment by Tyriar** [comment] 2021-12-17 18:27
Again: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=147363

**Comment by Tyriar** [comment] 2022-01-14 16:07
Again: https://github.com/microsoft/vscode/actions/runs/1697649175, the one that was skipped has a similar name but it's not the same. Will skip it too.

**Comment by bpasero** [comment] 2022-02-24 12:27
Also: `webviews with retainContextWhenHidden should be able to recive messages while hidden`. Skipped.

https://github.com/microsoft/vscode/runs/5318137447?check_suite_focus=true#step:18:390

**Comment by mjbvz** [comment] 2022-08-04 21:29
Duplicate of #153066

**Closed by mjbvz** 2022-08-04 21:29 UTC
Labels: integration-test-failure
