### ISSUE TITLE
扩展插件搜索不到

### ISSUE THREAD

**Issue by AnneMin** [Microsoft/vscode#57919] opened 2018-09-05 01:20 UTC
Issue Type: <b>Bug</b>

点击扩展 推荐项显示0 自行搜索不到

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
path-autocomplete|ion|1.12.0
vscode-github|Kni|0.30.0
vscode-language-pack-zh-hans|MS-|1.26.3
debugger-for-chrome|msj|4.9.0
vetur|oct|0.12.6
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.7.0
easy-wxless|yun|1.4.0

</details>

**Comment by TrumanDu** [comment] 2018-09-05 01:53
@AnneMin vs code marketplace down! wait for fix....

**Comment by mjbvz** [comment] 2018-09-05 02:36
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 02:36 UTC
