### ISSUE TITLE
TS rename causes many type definitions files to open for NPM packages

### ISSUE THREAD

**Issue by kyle-mccarthy** [Microsoft/vscode#53340] opened 2018-06-29 15:04 UTC
With `"typescript.updateImportsOnFileMove.enabled"` setting set to `"always"`, after renaming a TS file, many TS definitions files from NPM packages will open.  When going to close the `.d.ts` files, VS code will think a change was made and prompt to save the package file.

- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: MacOS High Sierra 10.13.5 (17F77)

Steps to Reproduce:

1. Open TS file in project
2. Rename open file
3. Many definitions files from NPM packages open after change

Does this issue occur when all extensions are disabled?: Yes

![bu0toawr8z](https://user-images.githubusercontent.com/7758522/42099598-7a4a5f48-7b83-11e8-920e-35a6144e9b31.gif)

It seemed similar to #53186 but the trigger and result are different.

**Comment by mjbvz** [comment] 2018-06-29 18:44
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled? I recently made a fix for this but it is only in insiders

**Comment by kyle-mccarthy** [comment] 2018-06-29 19:03
@mjbvz I just tried it out and while it didn't open any type def files, it opened several unrelated project files.

![b96cdnp6c5](https://user-images.githubusercontent.com/7758522/42109968-20595cec-7ba5-11e8-9ca6-74e1d739efe8.gif)

**Comment by mjbvz** [comment] 2018-07-02 07:11
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this issue after upgrading?

**Comment by mjbvz** [comment] 2018-07-06 22:51
Closing as duplicate of https://github.com/Microsoft/TypeScript/issues/24914. The next VS Code insiders will include this fix. Let me know if you still see this issue when using TypeScript 3.0+ in your workspace

**Closed by mjbvz** 2018-07-06 22:51 UTC
Labels: needs more info, typescript
