### ISSUE TITLE
Wrong font when certain character is used

### ISSUE THREAD

**Issue by panicbit** [Microsoft/vscode#41153] opened 2018-01-04 15:37 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.14.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.2.0
Handlebars|and|0.2.0
better-toml|bun|0.3.1
language-haskell|jus|2.4.0
vscode-rust|kal|0.4.2
csharp|ms-|1.13.1
sublime-keybindings|ms-|3.0.3
vscode-fileutils|sle|2.7.1
vscode-lldb|vad|0.7.3

(1 theme extensions excluded)

---

![font](https://user-images.githubusercontent.com/628445/34570411-010c3f44-f16c-11e7-84e7-cf04ec08bad9.png)

Steps to Reproduce:

1. Paste `Hello ͜World` into the editor
(The "COMBINING DOUBLE BREVE BELOW" is the important bit)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-01-08 14:04
Duplicate of #23852

**Closed by alexandrudima** 2018-01-08 14:04 UTC
