### ISSUE TITLE
Terminal not loading

### ISSUE THREAD

**Issue by DFelten** [microsoft/vscode#163998] opened 2022-10-19 08:22 UTC
Type: <b>Bug</b>

The terminal is not loading with the latest version of VSCode. It's just empty.

![CleanShot 2022-10-19 at 10 22 06](https://user-images.githubusercontent.com/1169185/196636982-68e3f9ac-87e5-435b-bf54-c33bf29dc6b8.png)

VS Code version: Code - Insiders 1.73.0-insider (7ea2788a43a4c35d8da63a419725ba2485de395b, 2022-10-19T05:32:31.450Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 8|
|Memory (System)|32.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 511166e9-0c5e-4225-a6af-efd2d90c3f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-m3u|af4|1.0.0
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
flutter-snippets|ale|3.0.0
toggle-excluded-files|eam|1.7.0
clipboard-history|Anj|1.0.7
melos-code|bla|0.5.0
vscode-intelephense-client|bme|1.8.2
ccs-flutter-color|cir|1.0.2
gitignore|cod|0.9.0
php-namespace-resolver|ctf|0.0.8
vscode-mac-color-picker|dae|1.1.0
dart-code|Dar|3.51.20221010
flutter|Dar|3.50.0
git-diff-and-merge-tool|dav|1.0.5
vscode-markdownlint|Dav|0.48.1
vscode-new-file|dku|4.0.2
githistory|don|0.6.19
gitlens|eam|13.0.2
bloc|Fel|6.6.2
mason|Fel|0.1.5
flutter-coverage|flu|0.0.4
vscode-pull-request-github|Git|0.52.0
todo-tree|Gru|0.0.219
terraform|has|2.24.3
json-to-dart|hir|3.5.8
rest-client|hum|0.25.1
monkey-patch|ioc|0.1.23
pubspec-assist|jer|2.3.2
shortcut-menu-bar|jer|3.0.4
intellij-idea-keybindings|k--|1.5.4
indent-to-bracket|LAK|1.2.2
flutter-intl|loc|1.18.2
syntax-project-pbxproj|mar|0.1.3
flutter-snippets|Mar|1.0.4
Kotlin|mat|1.7.1
rainbow-csv|mec|3.2.0
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|4.0.0
diff-merge|mos|0.7.0
vscode-docker|ms-|1.22.2
vscode-language-pack-de|MS-|1.72.10120946
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter|ms-|2022.10.1102931121
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.260.0
live-server|ms-|0.4.3
vsliveshare-pack|ms-|0.4.0
vscode-flutter-freezed-helper|mth|0.1.0
sqltools|mtx|0.25.1
sqltools-driver-mysql|mtx|0.4.0
awesome-flutter-snippets|Nas|4.0.1
vscode-yaml-sort|Pas|6.0.0
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.21.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|1.20.1
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
vscode-coverage-gutters|rya|2.10.2
lcov-lang|Ser|1.0.1
reveal|smu|1.2.7
swift-lang|ssw|0.8.2
freezed-model-gen|Sus|1.0.1
better-search|tra|0.0.6
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.29.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009

```

</details>

**Comment by fess932** [comment] 2022-10-19 08:28
too large padding 
![image](https://user-images.githubusercontent.com/17965077/196638517-6fca4a4b-1681-4f3c-8923-56db4e620dcb.png)

**Comment by furai** [comment] 2022-10-19 08:31
Related to #163997 ? 
I'm getting both of this issues.

**Comment by vystepanenko** [comment] 2022-10-19 09:28
Type: <b>Bug</b>

Same here

VS Code version: Code - Insiders 1.73.0-insider (7ea2788a43a4c35d8da63a419725ba2485de395b, 2022-10-19T05:28:16.879Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.92GB (29.34GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/cannibal/projects/api_crm_service --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)|
|Memory (System)|23.43GB (19.93GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.21.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.6.0
vscode-openapi|42C|4.14.1
vscode-sqlite|ale|0.14.1
vscode-intelephense-client|bme|1.8.2
better-phpunit|cal|1.5.3
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
gitlens|eam|13.0.2
prettier-vscode|esb|9.9.0
gitlab-workflow|Git|3.54.0
todo-tree|Gru|0.0.219
php-cs-fixer|jun|0.3.7
vscode-docker|ms-|1.22.2
makefile-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5735
snippet-creator|nik|0.0.5
advanced-new-file|pat|1.2.2
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
code-spell-checker|str|2.10.1
code-spell-checker-russian|str|2.0.6
code-spell-checker-ukrainian|str|1.0.0
tabnine-vscode|Tab|3.6.15
volar|Vue|1.0.8
vscode-import-cost|wix|3.3.0
php-debug|xde|1.29.0
ascii-unicode-escape|yar|0.1.0

(4 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2022-10-19 10:37
Duplicate of https://github.com/microsoft/vscode/issues/163991

**Comment by meganrogge** [comment] 2022-10-19 15:20
already fixed with https://github.com/microsoft/vscode/commit/d105e09d00411a18c99b09be2359487e898f157b

which you'll see in insider's tomorrow

**Closed by meganrogge** 2022-10-19 15:20 UTC
