### ISSUE TITLE
Not clear what the cog wheel notification means

### ISSUE THREAD

**Issue by shane-smith** [microsoft/vscode#51816] opened 2018-06-14 02:51 UTC
Issue Type: <b>Bug</b>

The cog wheel in the bottom-left of my VS Code screen has a notification icon on it, containing the number 1. It is not clear what this actually means. I'm reporting it as a bug, because it is a user-experience issue.

My *guess* after looking at the list is that it's notifying me about an update. But I shouldn't need to make a guess here. If it is for the update, then perhaps the "Restart to Update..." option should be highlighted in some way, or have a marker next to it, so we know that's what the number 1 refers to?

![screen shot 2018-06-14 at 12 16 10 pm](https://user-images.githubusercontent.com/943942/41388886-363106a2-6fcd-11e8-94fa-3f3812dc3c16.png)

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

**Comment by Ayanrocks** [comment] 2018-06-14 02:55
It is there to notify you while coding that an update is available. If restart to update is highlighted then you have to open the gear icon frequently to see for updates. It is not a bug or an issue. Please close this issue.

**Comment by shane-smith** [comment] 2018-06-18 02:09
@Ayanrocks - thanks for your comment. However, my point was that it is a user-experience issue and there are slight tweaks that could be made so that it is more obvious for users.

**Comment by misolori** [comment] 2018-08-22 16:05
An example from Spotify where an update notification badge is connected to the menu item:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44475624-5dd57280-a5ea-11e8-8cd8-8ce9cc4b8732.png">

**Comment by shane-smith** [comment] 2018-09-04 03:55
Thanks for the input @misolori - what Spotify does is great, because it's highlighting in blue the item it wants to bring attention to - the "Update available. Restart now." text.

**Comment by misolori** [comment] 2019-10-08 20:49
@joaomoreno thoughts on appending a `*` on the `Restart to Update` text to have some type of affordance?

<img width="385" alt="image" src="https://user-images.githubusercontent.com/35271042/66432248-75c8ab00-e9d2-11e9-8758-4a18bee63ab0.png">

**Comment by misolori** [comment] 2019-10-16 17:05
I'll be updated this to use `(1)` instead of a `*` as we use this in other areas as well:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/35271042/66941732-682baa80-effc-11e9-83d4-b4f7e07e1314.png">


<img width="269" alt="image" src="https://user-images.githubusercontent.com/35271042/66941720-5e09ac00-effc-11e9-93fa-684c8afc12f6.png">

We'd ideally like to use some type of icon/label that can be re-used in other areas, but that requires support from the electron side:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/35271042/66941771-7ed20180-effc-11e9-9642-5e112f9786b5.png">

**Closed** 2019-10-16 17:25 UTC
Labels: bug, install-update, ux

**Comment by shane-smith** [comment] 2019-11-18 01:50
Perfect, thanks!
