### ISSUE TITLE
Nested peek definition

### ISSUE THREAD

**Issue by kterhorst** [Microsoft/vscode#35608] opened 2017-10-05 06:18 UTC
Are there any plans to allow using peek definition within the peek definition popup window itself? Just like in Visual Studio for loaded project (not Open Folder). IMO it is the last step to make VS Code an excellent tool for exploring large code bases.

From: https://github.com/Microsoft/vscode-cpptools/issues/1093

**Comment by jrieken** [comment] 2017-10-05 10:58
dupe of #6857

**Closed by jrieken** 2017-10-05 10:58 UTC
Labels: workbench
