### ISSUE TITLE
Possible to auto close html tags when pressing enter?

### ISSUE THREAD

**Issue by Gacnt** [Microsoft/vscode#502] opened 2015-11-23 15:47 UTC
Right now you have to type `</` and press enter to close the last tag it would be much simpler to just press enter and have it close

**Comment by formulahendry** [comment] 2016-07-04 14:48
@Gacnt This [Extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) would nearly meet with your requirement. It will automatically add closing tag when you type in the closing bracket of the opening tag. No pressing enter is needed, just same as VS IDE does.

![GIF](https://raw.githubusercontent.com/formulahendry/vscode-auto-close-tag/master/images/usage.gif)

**Comment by aeschli** [comment] 2016-09-12 15:11
duplicate of #2246

**Closed by aeschli** 2016-09-12 15:11 UTC
Labels: feature-request
