### ISSUE TITLE
jsconfig.json sometimes not taken into account

### ISSUE THREAD

**Issue by skovmand** [Microsoft/vscode#703] opened 2015-11-26 10:36 UTC
Hi.

Thanks for your product, I really enjoy using it. However I have one problem:
When using ES6 features, like the arrow functions, I get the message "This can only be used with ES6. Make sure to have a jsconfig.json-file which sets the target to ES6".

However I have a ```jsconfig.json```-file in my root (the folder opened in Visual Studio Code), which contains:

```json
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs"
	}
}
```

The weird part is that I get it for some files, and not for others. Even if the files are in the same directory. Right now I have three files in the subdirectory ```/app/bpm``` names ```bpm.js```, ```bpmController.js``` and ```enterClick.js```. All three are written with ES6-functionality, but I only get the warning and red underlined text for ```bpm.js```. 

UPDATE:
I just restarted VS Code, and the red underline disappeared from ```bpm.js``` too. It was a new file I had created after the two others, however the red underline only went away after a restart.

**Comment by skovmand** [comment] 2015-11-26 10:39
I just reproduced it again. Made a new directory, and moved a file into it. Everything gets the red underline and the warning "This can only be used with ES6. Make sure to have a jsconfig.json-file which sets the target to ES6".

Restart VSCODE and it goes away.

**Comment by gerrywastaken** [comment] 2015-11-26 10:43
I have the same problem except while restarting normally fixes this, in this case it's still no working after a restart for a file called schema.js

**Comment by jaccus** [comment] 2015-11-26 13:28
This bug makes VS Code completely unusable for ES6 development since the whole editor is obfuscated with red underlines.

I managed to sometimes get it resolved by editing jsconfig.json (add whitespace, save) but then again, only sometimes.

Sounds quite critical to me?

**Comment by warpdesign** [comment] 2015-11-26 15:07
+1
Same problem, had to disable builtin js validation.

**Comment by nverba** [comment] 2015-11-27 08:33
+1  This is driving me mental! Completely random too.

**Comment by jrieken** [comment] 2015-11-27 08:43
I can reproduce with a simple sample but after a short while (2-3 seconds) it recovers. I guess you guys are dealing with large projects?

**Comment by mbarzeev** [comment] 2015-11-30 13:43
+1
This is very annoying, and as others have mentioned - this is a key feature.

**Comment by skovmand** [comment] 2015-11-30 14:04
@jrieken My project is about 25 .js-files in different subdirectories. The tree is up to 3 directories deep.

**Comment by nrkn** [comment] 2015-12-01 03:00
How's this for bizarre - I'm getting this same issue in my project, but only in a handful of files that start with the word 'template', like `template-controller.js` etc. - however, not with `templates.js`

My colleague had the same issue, but it went away when he restarted VSCode - that doesn't work for me, makes no difference, nor does editing and resaving the `jsconfig.json`.

**Comment by Cirych** [comment] 2015-12-01 16:18
On Windows VSCode can see jsconfig.json and work properly. But when open project from network drive, VSCode can't see jsconfig.json and show errors on ES6 code.

I have project on VM centos and map a Windows network drive to projects folder. All right, except ES6 errors.
When I copied project to Windows local folder - everything seems Ok with ES6 speling.

**Comment by yevk** [comment] 2015-12-02 10:21
I'm having the same problem. It happens only on directories that are 4th level or deeper. If I move the file up one directory, the error goes away.

**Comment by appetizermonster** [comment] 2015-12-03 04:06
+1

**Comment by lucdew** [comment] 2015-12-03 08:00
+1 I have the same issue and it seems to be random. Sometimes when I restart Visual Studio code it disappears, sometimes not.

**Comment by jrieken** [comment] 2015-12-03 09:00
We will tackle for Dec

**Comment by jrieken** [comment] 2015-12-04 11:49
@skovmand For you specific case, can you check if the full path of your files (_bpm.js, bpmController.js, ..._) contains `js`, like in `/users/me/coding/js-stuff/app/bpm` etc? I am asking because I have found an issue if our file event processing loop. It's a little complex but basically when a file is added/deleted we check if that is of interest the JS language service and the check seems flawed

**Comment by jrieken** [comment] 2015-12-04 12:10
@nrkn I have a fix for the `temp`-prefix issue.

**Comment by jrieken** [comment] 2015-12-04 12:11
@yevk About the 4th level directory. Is it that they either start with `temp` or contain the string `js`?

**Comment by janders223** [comment] 2015-12-04 14:24
This also seems to be the case with shebang scripts. A file at `~/project/bin/server` with the node shebang header `#!/usr/bin/env node` is not recognized. As soon as the file name is changed to `~/project/bin/server.js` it is fine.

**Comment by jrieken** [comment] 2015-12-04 14:40
@janders223 Yeah, at that point in time we cannot look into each and every file...

**Comment by skovmand** [comment] 2015-12-04 19:27
@jrieken Yes, my file path contains js. The file path to the site root is ```/Users/skovmand/Code/beat-ninja-frontend/site/resources/assets/js```

**Comment by yevk** [comment] 2015-12-04 22:48
@jrieken 
No `temp` or `js` in the folder names.
I did some more testing with a completely empty dir containing only `jsconfig.json`, a `test.js` file and a bunch of subdirs named 'a' through 'e'.
It seems to work at all levels but it takes a few seconds to recognize the ES6 syntax. 
This is in an almost empty dir, in a real app dir with `node_modules` and `jspm_packages` at level 4 it doesn't recognize ES6 at all.

I then copied the `package.json` file from the real app and did `npm install` and `jspm install`. After that, it broke again. Also tried using "exclude" in `jsconfig.json`, but that didn't help.

Here's `package.json` and the folder structure for reference.

![image](https://cloud.githubusercontent.com/assets/1427723/11603228/062c661a-9ae9-11e5-9d66-8c99e102f200.png)

![image](https://cloud.githubusercontent.com/assets/1427723/11603284/6e0b9b02-9ae9-11e5-81e5-99d808c5209e.png)

**Comment by jrieken** [comment] 2015-12-07 08:58
@yevk Can you try to exclude the jspm_packages? Due to the fact that the JS language service doesn't run full isolation we have a cap on the amount of resources we load. We exclude certain folders (like node_modules) by default but we don't filter jspm_packages. Cos of that you might run into a limit which then manifests in us not loading `test.js`

**Comment by jrieken** [comment] 2015-12-07 09:31
More debugging insights. We only allow 750 source files per project and since we don't exclude `jspm_packages` by default we reach that limit before reaching to the deep a/b/c/d/e/f-folder. I will make `jspm_packages` be excluded by default.

**Comment by yevk** [comment] 2015-12-07 09:42
@jrieken 
I though of that and did add both to `jsconfig.json` exclude. Still not working well.
Can you reproduce this? I will try it on another PC later to make sure it's not something local.

![image](https://cloud.githubusercontent.com/assets/1427723/11623701/504e7342-9cd7-11e5-9f73-4ee95681eb4e.png)

**Comment by jrieken** [comment] 2015-12-07 09:46
yeah, I could reproduce and fixed it on master.

**Comment by jrieken** [comment] 2015-12-07 10:20
I understood and tackles these tasks

- [x] files are ignored when path contains `js`, like `foo/bar/js-project/far.js`
- [x] paths are ignored when path-segments start with `temp`, like `foo/bar/templateEngine.js`
- [x] problem with exclude patterns
- [ ] problem with files without ending but shebang

**Comment by warpdesign** [comment] 2015-12-07 18:56
@jrieken what about files that contain several dots ? like `foo.bar.dialog.js` ?

**Comment by jrieken** [comment] 2015-12-08 08:58
I see that working fine @warpdesign

**Comment by jrieken** [comment] 2015-12-08 09:06
Closing, the remaining work wrt to shebang and files with an extension will be tackled in #1097.

**Closed by jrieken** 2015-12-08 09:06 UTC
Labels: bug, js, P1

**Comment by dbaeumer** [comment] 2015-12-16 10:56
@jrieken can you please add steps for verification

**Comment by jrieken** [comment] 2015-12-16 11:20
@dbaeumer https://github.com/Microsoft/vscode/issues/703#issuecomment-162473700

**Comment by Natrina** [comment] 2016-02-01 04:57
I'm still having the same issue as @Cirych. When opening a folder over a mapped network drive (in this case opening my Linux folder on Windows). Opening the folder while mapped causes VSCode to show everything as syntax errors. Copying my code over to Windows and then opening VSCode to the new folder causes errors to disappear and for intelliSense to work again.

**Comment by lironka** [comment] 2016-02-27 20:46
I have this error too. I try write ES6 in root site files (etc. wabpack.config.js, test.js)  and have red underlined.  jsconfig.json - doesn't work!

**Comment by StarpTech** [comment] 2016-03-10 22:10
Same issue. Using `jsconfig.json` doesn't work. e.g `const` keyword is red underlined.

**Comment by matthiasg** [comment] 2016-04-19 06:32
Same issue here. In one project it works in another (was a copy of the first) it doesnt. Same content in jsconfig.json. Typings are underlined though.

**Comment by mortonprod** [comment] 2016-07-20 10:44
I also have the same issue using the gulp file from this tutorial:
http://www.mithunvp.com/angular-2-in-asp-net-5-typescript-visual-studio-2015/

The arrow function is the issue. I include the needed jsconfig and nothing? Has anyone solved this yet?

**Comment by malte-timmermann** [comment] 2016-10-12 10:51
I also have the issue the jsconfig.json is not being read.

Tested with Visual Studio Code v1.5.3 and v1.7.0 insider, on Windows x64 (version 1607).

When using Sysinternals process monitor, I see that VC Code is getting some information about jsconfig.json (QueryAllInformationFile), but does NOT read the file (ReadFile).

Log when opening VS Code (with the current project) (reduced to jsconfig.json and my test file)

http://pastebin.com/GTKHPCZC

Log when actually opening jsconfig.json inside VS Code (so something like that should also happen when launching VS Code):

http://pastebin.com/je8Y3p4C

Not reading jsconfig.json unfortunately means that "go to definition" doesn't work for me with my own js files, what hinders me from switching from Netbeans to VS Code :(

I would really appreciate if this issue could be fixed. If you need further information, or my stripped down example, just let me know!

**Comment by malte-timmermann** [comment] 2016-10-12 11:58
I just saw that this bug is closed - will open a new/fresh one...
