### ISSUE TITLE
[TypeScript] Highlighting breaks with a number at the end of return type

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#10255] opened 2016-08-07 01:07 UTC
- VSCode Version: 1.4.0
- OS Version: All

When declaring a return type in `typescript` that ends with a number the colors don't displayed properly.

Here is the invalid highlight:

![invalid highlight](https://cloud.githubusercontent.com/assets/1571806/17459856/3023ed28-5c11-11e6-8a79-9d746883663d.png)

Remove the `2` in the return type, and the highlighting works:

![valid highlight](https://cloud.githubusercontent.com/assets/1571806/17459855/3023cb0e-5c11-11e6-8035-9e04f0af7cfd.png)

**Comment by aeschli** [comment] 2016-08-07 20:05
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/188

**Closed by aeschli** 2016-08-07 20:05 UTC
