### ISSUE TITLE
[java] @interface breaks syntax highlighting

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode#79892] opened 2019-08-27 10:46 UTC
When adding a @annotation interface the syntax highlighting breaks

OSX 10.12.6
All latest versions of date of writing

correct:
<img width="209" alt="Screen Shot 2019-08-05 at 09 03 58" src="https://user-images.githubusercontent.com/738650/62445433-7b9ad980-b760-11e9-9d1f-e62cb6c8fe6b.png">

with annotation:
<img width="305" alt="Screen Shot 2019-08-05 at 09 03 13" src="https://user-images.githubusercontent.com/738650/62445447-82c1e780-b760-11e9-9004-c025004cd96b.png">

(Also using a $ will break the syntax of the return type).

This one is even worse, notice that the commented line is not commented at all:

<img width="317" alt="Screen Shot 2019-08-05 at 10 11 14" src="https://user-images.githubusercontent.com/738650/62448998-69716900-b769-11e9-91aa-d7286cbab397.png">

Issue was originally posted here:
https://github.com/redhat-developer/vscode-java/issues/1019
But I was told it should be reported here.

**Comment by alexr00** [comment] 2019-08-29 10:44
@clankill3r thanks for also opening https://github.com/atom/language-java/issues/203! It looks like they have already made a change to fix it over there, and I will pull the change into VS Code next week.

Duplicate of https://github.com/atom/language-java/issues/203

**Closed by alexr00** 2019-08-29 10:44 UTC
