### ISSUE TITLE
VSCode Extensions Profiles.

### ISSUE THREAD

**Issue by Jerrody** [microsoft/vscode#146021] opened 2022-03-25 04:28 UTC
It's a pretty simple idea of profiles. What's the main idea of profiles?
The profiles will allow us to disable or/and enable specific extensions when we write in a specific language.

**For example**:
I open the Rust project (VSCode auto-selects or I select a profile for Rust), so, I don't need enabled extensions for C++ and JS, and these extensions are auto-disabled according to the Rust profile. And, of course, this profile auto-enables extensions, that we included for the Rust profile.

**Comment by avi5079** [comment] 2022-03-25 04:53
Hello @Jerrody,
I am a beginner to open source. I would like to learn by contributing to this repo. Can you please guide me in this repo like how to get started?

**Comment by gjsjohnmurray** [comment] 2022-03-25 05:32
/duplicate of #40239

@avi5079 please see https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Closed** 2022-03-25 05:32 UTC
Labels: *duplicate
