### ISSUE TITLE
High CPU usage even after quiting Visual Studio Code

### ISSUE THREAD

**Issue by ShiranC** [Microsoft/vscode#46034] opened 2018-03-17 19:00 UTC
Issue Type: <b>Bug</b>

Two processes consume very high CPU usage even after exiting VSCode.

The processes are:

Microsoft.VSCode.CPP.Intellisense.Msvc.darwin
Microsoft.VSCode.CPP.Extension.darwin

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz (8 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Users/Shiran/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
githistory|don|0.4.0
tslint|eg2|1.0.28
open-in-editor-vscode|gen|0.9.7
Lua|key|0.0.9
Go|luk|0.6.77
python|ms-|2018.2.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0
debugger-for-chrome|msj|4.2.1
java|red|0.21.0
vscode-icons|rob|7.21.0
vscode-java-debug|vsc|0.7.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.6.0
vim|vsc|0.11.2

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by tsalinger** [comment] 2018-03-19 08:42
You mention that this problem only occurs with extensions enabled. Please disable all extensions (CTRL+SHIFT+P --> 'Disable all installed extensions') and restart VS Code.
Then check if the problem still persists. If not, try to find which one causes the trouble by enabling one extension after the other.

If the problem is not caused by an extension, please provide us with a reproducible list of steps that cause this behavior.

**Comment by davidpanzarella** [comment] 2018-03-22 22:35
I have the same issue, though i can confirm its nothing to do with an extension. 

`
    0	    49	  2535	     extensionHost
    0	    33	  3417	       electron_node cssServerMain.js
    0	    33	  3418	       electron_node server.js
  125	  2277	  4399	       electron_node server.js
    0	    33	  2536	     watcherService
    0	    33	  3422	     searchService
    0	    16	  3443	     terminal
    0	     0	  3444	       /usr/local/bin/zsh
`

I downloaded Code Insiders, and had no issues out of the box (eg. without anything configured or added). Any idea why I have 2 `electron_node server.js`?

I'm on the latest version and latest Mac OS.

**Comment by bpasero** [comment] 2018-04-05 03:26
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2018-04-05 03:26 UTC
Labels: needs more info
