### ISSUE TITLE
Trying to insert a snippet using multiple cursors only inserts at first created cursor

### ISSUE THREAD

**Issue by CanisLupus** [Microsoft/vscode#20484] opened 2017-02-11 21:21 UTC
If I create 3 cursors (for example using alt+click) and then try to insert a snippet at those locations, the snippet will only be inserted at the first cursor location.

In this example, I first created the bottom cursor, then the middle one, then the top one:

![snippet in multiple cursors](https://cloud.githubusercontent.com/assets/532708/22857608/f78c2790-f09f-11e6-884d-ac7e5fd0a950.gif)

Expected behavior would be to insert it at all three cursors. Then, the snippet's tab stops should happen for all of them as expected (i.e. press tab once and it moves to the next tab stop on all of them). Sublime implements the expected behavior.

**Comment by ramya-rao-a** [comment] 2017-02-11 23:24
Duplicate of #16037
cc @jrieken

**Closed** 2017-02-11 23:24 UTC
Labels: duplicate, snippets
