### ISSUE TITLE
Typescript code highlight

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#10677] opened 2016-08-18 20:55 UTC
- VSCode Version: 1.5.0-insider (231bad)
- OS Version: Windows 10 x64

The code below stops highlighting of Typescript:

```ts
class Config {

    static $inject = [
        '$stateProvider',
        '$urlRouterProvider',
        'ErrorLookupProvider',
        '$locationProvider',
        '$compileProvider',
        '$httpProvider',
        'uiGmapGoogleMapApiProvider',
        '$provide'
    ];

    constructor(
        $stateProvider:angular.ui.IStateProvider,
        $urlRouterProvider: angular.ui.IUrlRouterProvider,
        ErrorLookupProvider: ngErrorLookup.Providers.ErrorLookupProvider,
        $locationProvider: angular.ILocationProvider,
        $compileProvider: angular.ICompileProvider,
        $httpProvider: angular.IHttpProvider,
        uiGmapGoogleMapApiProvider: any,
        $provide: angular.auto.IProvideService
    ) {
        //FastClick.attach(document.body);

        $provide.decorator("$http", ["$delegate", function($delegate: any) {
            var get = $delegate.get;

            $delegate.get = function(url: string, config: string) {
                if (url.indexOf('/templates/') === 0 || url.indexOf('/content/') === 0) {
                    url += (url.indexOf("?") === -1 ? "?" : "&");
                    url += "v=" + VERSIONING;
                }
                return get(url, config);
            };

            return $delegate;
        }]);
    }
}
```
![vscode-2](https://cloud.githubusercontent.com/assets/461084/17790464/efe8a55e-656c-11e6-865f-19712a85eef5.png)

**Comment by alexandrudima** [comment] 2016-08-19 05:53
This is already fixed on master, you can download the Insiders version to get the fix or wait for the August stable release.

**Comment by alexandrudima** [comment] 2016-08-19 05:55
@pocesar Just noticed you are on the Insiders version. This works for me on the exact same version:

![image](https://cloud.githubusercontent.com/assets/5047891/17800292/356d4272-65e2-11e6-9170-e0a9822fcc82.png)

**Comment by pocesar** [comment] 2016-08-19 06:14
the file is actually 735 lines long, I tried deleting parts of it to see if the highlighting would come back. the funny thing is that no matter what code is at line 130ish and below, it never gets highlighted:

![vscode](https://cloud.githubusercontent.com/assets/461084/17800578/c658e8cc-65ba-11e6-9c18-73d2da88db3e.png)
![vscode](https://cloud.githubusercontent.com/assets/461084/17800606/f9ea4df2-65ba-11e6-9923-9379e172b04d.png)

**Comment by alexandrudima** [comment] 2016-08-19 06:18
@pocesar The root cause of these issues are bugs in the TypeScript TM grammar we use for colorizing. Can you please give us a full version of the file (the lines preceding do matter) in a copy-paste friendly format.

[Usually this is caused by a grammar pushing too many stack rules and forgetting to pop them -- this can happen anywhere above the line that stops coloring]

**Comment by pocesar** [comment] 2016-08-19 06:25
@alexandrudima is there an address I can email the file? (it's in a private repo here)

**Comment by alexandrudima** [comment] 2016-08-19 06:27
You can find my email address under by profile -- https://github.com/alexandrudima

**Comment by pocesar** [comment] 2016-08-19 06:30
sent!

**Comment by whitecolor** [comment] 2016-08-21 19:49
Btw agrs and types highlighting works for runction but doesn't for arrow function:
![image](https://cloud.githubusercontent.com/assets/736697/17839469/402cfd98-6802-11e6-93dd-37cd8d243d31.png)

**Comment by alexandrudima** [comment] 2016-08-22 10:04
@pocesar Thank you. I have created the following minimal repro from your source:

```typescript
class C1 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
class C2 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
class C3 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
class C4 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
class C5 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
class C6 {
    m1 = 1;
    static s1() {
        return [() => (new this).m1];
    }
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/17851062/73b5ea36-6860-11e6-9b3a-6e759fed9686.png)

**Comment by alexandrudima** [comment] 2016-08-22 10:11
@pocesar Moved the issue hit by your code to Microsoft/TypeScript-TmLanguage#248
@whitecolor Moved your comment/issue to Microsoft/TypeScript-TmLanguage#249

@whitecolor For your second question, it is not currently possible to overwrite a specific grammar, but please create a new issue for that, as it would be very useful.

**Closed by alexandrudima** 2016-08-22 10:11 UTC
Labels: needs more info

**Comment by pocesar** [comment] 2016-08-22 14:58
@alexandrudima glad I could've been of help :+1:

**Comment by whitecolor** [comment] 2016-09-01 14:33
Guys any progress on this, I still have most of my TS code gray (one color)
![image](https://cloud.githubusercontent.com/assets/736697/18171289/e0b472ca-707a-11e6-9f93-fad0e74f1fca.png)

When is it supposed to be changed?

**Comment by alexandrudima** [comment] 2016-09-01 14:36
@whitecolor Can you provide the entire file in a textual form? Are you on 1.4.0 or on the insiders channel?
It also seems to me that you may be suffering from a different issue, as the code is partially colored. Please create a separate issue

**Comment by whitecolor** [comment] 2016-09-01 14:51
@alexandrudima 
I'm not on insiders, created an issue https://github.com/Microsoft/vscode/issues/11398
