### ISSUE TITLE
Node.js 6.0 messes up debugger when using Typescript with sourcemaps

### ISSUE THREAD

**Issue by pkeuter** [Microsoft/vscode#5936] opened 2016-04-28 09:48 UTC
- VSCode Version: 1.00
- OS Version: Win 10

Steps to Reproduce:

1. Install node.js 6.0.0
2. Try to debug within a router.get function.

```
router.get("/:id", (req, res, next) => {
    controller.getSingle(req.params.id).then(data => res.json(data));
});
```

When I add a breakpoint at the `controller.` call, the debugger stops when I'm using node 5.11.0. It does not after upgrading to 6.0.0. The debugger stops (so it notices a breakpoint), but it doesn't show the line where it stopped anywhere.

Breakpoints outside of the express calls work fine by the way. So when I add a breakpoint at the router.get, it works (but at the start of the application, which is good, obviously).

Changing from () => to function() did not change anything.

**Comment by bpasero** [comment] 2016-04-28 12:44
@isidorn @weinand fyi

**Comment by weinand** [comment] 2016-04-28 12:50
@pkeuter VS Code node debugging hasn't been verified for node 6.x. Many of our node debug tests fail with node 6.x. I will investigate after my vacation next week.

**Comment by anyong** [comment] 2016-05-03 14:35
Yeah this seems to be pretty random. It sporadically works fine or doesn't work at all - same as @pkeuter the debugger pauses execution but no breakpoint or variables are shown. This is with vanilla ES6 and babel transpiled ES6.

**Comment by weinand** [comment] 2016-05-04 08:54
duplicate of https://github.com/Microsoft/vscode/issues/6029

**Closed by weinand** 2016-05-04 08:54 UTC
Labels: bug, debug
