### ISSUE TITLE
Update imports on file move - Typescript

### ISSUE THREAD

**Issue by ghclark2** [microsoft/vscode#111978] opened 2020-12-07 00:36 UTC
Issue Type: <b>Bug</b>

When moving multiple files, only the first one has its imports updated. Should be all of them.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.17GB free)|
|Process Argv|--folder-uri file:///c%3A/TEACHHC/AlgebotsV3 --crash-reporter-id bc06998e-d7c5-49be-a6f8-71d924fccc06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
todo-tree|Gru|0.0.188
vscode-coding-tracker|han|0.6.0
debugger-for-chrome|msj|4.12.11

</details>

**Comment by mjbvz** [comment] 2020-12-07 19:07
Duplicate of #105110

**Closed by mjbvz** 2020-12-07 19:07 UTC
