### ISSUE TITLE
Gear icon for notebook controller does not behave as expected

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#146667] opened 2022-04-03 16:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Click on a controller gear icon to select this controller as default for all notebooks matching the current notebook's filepath
2. Open another notebook of the same type
3. :bug: I still have to manually select a controller. I would expect the controller whose gear icon I clicked on previously to be selected for all my future notebooks

**Comment by jrieken** [comment] 2022-04-04 06:59
closing as duplicate of https://github.com/microsoft/vscode/issues/146339

**Closed by jrieken** 2022-04-04 06:59 UTC
