### ISSUE TITLE
hover quickfix import does not work

### ISSUE THREAD

**Issue by nzstevec** [microsoft/vscode#76791] opened 2019-07-07 05:46 UTC
Issue Type: <b>Bug</b>

add java logic that references an external class that must be imported.

when I hover the mouse of the squigle error indicating reference cannot be resolved to a type and click quickfix then click import xxx nothing is added to the import statements at the top of the file.

when I select the squigle error and enter ctrl+. and then click import xxx the import is added to the statements at the top of the file.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

**Comment by pape2016** [comment] 2019-07-08 07:45
me too, I see the log in Log(Extension Host)
[warning] redhat.java - Code actions of kind 'quickfix 'requested but returned code action is of kind 'source.generate.constructors'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.

It works in 1.35.1!!!

**Comment by pape2016** [comment] 2019-07-08 07:45
it doesn't work in 1.36.0

**Comment by dbaeumer** [comment] 2019-07-08 08:32
@mjbvz starting with you since this seems to work in 1.35.x

**Comment by mjbvz** [comment] 2019-07-08 15:28
Duplicate of #76851

**Closed by mjbvz** 2019-07-08 15:28 UTC
