### ISSUE TITLE
VS Code Accessibility Call - June 2020

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#99916] opened 2020-06-11 21:44 UTC
Each month, we try to hold a call where users in our accessibility community can give feedback, bring up problems, and share accessibility practices with members of our team. The June call will be held on **Tuesday, June 23 at 11am EST / 5pm CEST / 8:30pm IST.**

Based on feedback from the last call, we would like to limit people on the call so that we facilitate richer communication and get more focused feedback. Thus, we are asking those who are interested in participating to fill out the sign up link below:

[Sign up to participate ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR56QZY-o1WBHqGH6gasleCBUMFBNTFVIVk1SWlhRUFMxV1VSTlQ3WDA0Sy4u)

### Agenda:

- Introductions

- Feedback on debug accessibility @isidorn 

- Feedback on editing object settings in setting GUI @9at8 https://github.com/microsoft/vscode/issues/99635

We will reach out to confirm those who will be participating in the call and send you a Microsoft Teams link to join the call. We will post a link to the recorded video at the end of the call.

**Comment by sana-ajani** [comment] 2020-06-23 18:52
**Meeting notes:**

**Settings:**
- What about settings that contain lots of keys? How can a user edit a key? 
- How can we convey to a user that this is an object setting? If a setting is an object, maybe we include it in the left pane?
    - Left side is a set of things that can be collapsed or expanded, right side is a flat list, with no object type settings or hierarchies…having nesting in the right pane may be confusing
    - Depends on how often a user interacts with these settings
		
- What about if a user navigates past this object setting? Is it obvious if the user tabs away? Is the setting read as the object setting and property name or just the setting property name? 

**Debugging:**
- Shift F8, F8 inline navigation of problems
- In the terminal, the `ctrl up/down` is not obvious: https://github.com/microsoft/vscode/issues/100866
- Consider adding the same `ctrl up/down` navigation in the debug console? https://github.com/microsoft/vscode/issues/100868 
- Changing focus to problems view during debugging: https://github.com/microsoft/vscode/issues/100871

**Comment by isidorn** [comment] 2020-06-24 07:38
@sana-ajani thanks a lot for capturing notes.

Since this meeting has taken place as planned and we have createn follow up issues I am closing this issue.
Even though the issue is closed feel free to comment here if needed.

@9at8 should we create some issue for settings to capture the feedback or the [current issues](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+settings+label%3Asettings-editor) already capture it well enough?

**Closed by isidorn** 2020-06-24 07:38 UTC
Labels: accessibility

**Comment by 9at8** [comment] 2020-06-25 01:41
I think most of the feedback that I needed was different ways/expectations for editing object settings from the GUI, and I don't think we need to create more issues for that.
