### ISSUE TITLE
Autocomplete stops working after create a new file

### ISSUE THREAD

**Issue by BetterCallSky** [microsoft/vscode#88660] opened 2020-01-15 07:57 UTC
- VSCode Version: 1.41.1
- OS Version: mac 10.15.1

Steps to Reproduce:

1. Create a new file.
2. Write some code (or use snippet), and try to autocomplete a type/variable.
3. Autocomplete doesn't suggest anything.
4. The problem is not repeatable in 100%. Sometimes it works and sometimes it doesn't. 

This issue is very frustrating for me. I get this problem every day for more than 3 months. To fix it I have to run 'restart TS server' from the command pallet.
Typescript version is 3.7.3, I was able to repeat it with 3.6, and any next.  
However, one of my projects still uses 3.2.2, and It works perfectly.
VSCode is 1.41.1, but I was able to reproduce it in 1.39 or insiders.

In tsserver.log, I can see only this error

```
Perf 839  [8:34:14.169] 103::geterr: async elapsed time (in milliseconds) 0.3529
Info 840  [8:34:14.169] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 841  [8:34:14.219] DirectoryWatcher:: Added:: WatchInfo: /Users/sky/work/kpi/kpi-reactjs-app/apps 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 842  [8:34:14.219] Elapsed:: 0ms DirectoryWatcher:: Added:: WatchInfo: /Users/sky/work/kpi/kpi-reactjs-app/apps 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 843  [8:34:14.221] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 3 structureChanged: true Elapsed: 52ms
Info 844  [8:34:14.221] Different program with same set of files:: oldProgram.structureIsReused:: 1
Info 845  [8:34:14.222] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/Users/sky/work/kpi/kpi-reactjs-app/apps/kpi-client/src/features/dataEntry/components/KpiSidePanelHeader.tsx","diagnostics":[]}}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-01-17 01:54
Can you share the complete TS server log? `geterr` is the name of a request, not an actual server error. If you cannot share the whole log, look for stack traces in the log and please share those

**Comment by BetterCallSky** [comment] 2020-01-17 14:49
[tsserver.log](https://github.com/microsoft/vscode/files/4077292/tsserver.log)

logs attached, but I don't see any errors except 'WatchType: Failed Lookup Locations'

**Comment by mjbvz** [comment] 2020-01-17 18:10
Just to confirm: this works properly when using an older TS version (such as 3.2) in the current version of VS code?

Can you share your project or a small project that triggers this issue?

**Comment by BetterCallSky** [comment] 2020-01-20 17:28
> Just to confirm: auto complete works properly when using an older TS version (such as 3.2) in the current version of VS code?

Correct.

> Can you share your project or a small project that triggers this issue?

I will try to create a new project and reproduce the issue

**Comment by BetterCallSky** [comment] 2020-01-20 18:49
https://github.com/BetterCallSky/vscode-autocomplete-bug

Steps:
- create `Aasdasd.tsx`
- copy it
- Add `'<Button />`
- Autocomplete is not working


![image](https://user-images.githubusercontent.com/4478684/72750662-c0ef7e00-3bbd-11ea-80be-d3147b10d235.png)

TS version is 3.8, but the same issue occurs in 3.7.
Autocomplete works after restarting TS from the command palette.

**Comment by BetterCallSky** [comment] 2020-01-20 18:55
Autocomplete is broken only in the newly created file.
Another demo https://take.ms/8VCsI
I am not sure how to repeat it exactly, but it seems to be random.

**Comment by BetterCallSky** [comment] 2020-01-20 19:04
[tsserver.log](https://github.com/microsoft/vscode/files/4087533/tsserver.log)

Another log file. Autocomplete is broken after creating `Qwer.tsx` file.

**Comment by BetterCallSky** [comment] 2020-01-20 19:18
[tsserver.log](https://github.com/microsoft/vscode/files/4087554/tsserver.log)

Here is a log file without a bug. I created `Bura.tsx` file and autocomplete works properly.
If you compare two log files, you can notice differences.

In `Bura.tsx`, there is no text `/dev/null/inferredProject`.
In `Qwer.tsx`, there are entries

```
Info 155  [20:3:46.275] -----------------------------------------------
Info 156  [20:3:46.276] Project '/Users/sky/work/vccode-test/tsconfig.json' (Configured) 0
Info 156  [20:3:46.276] 	Files (30)
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es5.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.dom.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.dom.iterable.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.core.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.collection.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.generator.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.promise.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2017.object.d.ts
	/Users/sky/work/vccode-test/node_modules/tslib/tslib.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/react/global.d.ts
	/Users/sky/work/vccode-test/node_modules/csstype/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/prop-types/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/react/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/styled-components/ts3.7/index.d.ts
	/Users/sky/work/vccode-test/src/Bara.tsx
	/Users/sky/work/vccode-test/src/Button.tsx
	/Users/sky/work/vccode-test/src/FilterComp.tsx
	/Users/sky/work/vccode-test/src/Foo.tsx
	/Users/sky/work/vccode-test/src/Test.tsx
	/Users/sky/work/vccode-test/src/Tre.tsx
	/Users/sky/work/vccode-test/src/utils.ts
	/Users/sky/work/vccode-test/node_modules/@types/react-dom/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/webpack-env/index.d.ts

Info 156  [20:3:46.276] -----------------------------------------------
Info 156  [20:3:46.276] Project '/dev/null/inferredProject1*' (Inferred) 1
Info 156  [20:3:46.276] 	Files (26)
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es5.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2016.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.dom.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.dom.iterable.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.scripthost.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.core.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.collection.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.generator.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.promise.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	/Users/sky/work/vccode-test/node_modules/typescript/lib/lib.es2016.full.d.ts
	/Users/sky/work/vccode-test/src/Qwer.tsx
	/Users/sky/work/vccode-test/node_modules/@types/prop-types/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/react/global.d.ts
	/Users/sky/work/vccode-test/node_modules/csstype/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/react/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/react-dom/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/styled-components/ts3.7/index.d.ts
	/Users/sky/work/vccode-test/node_modules/@types/webpack-env/index.d.ts
```

It seems like a newly created file is treated as a new separated project.

**Comment by mjbvz** [comment] 2020-01-23 00:49
Thanks. From the symptoms and log, this seems like a duplicate of https://github.com/microsoft/TypeScript/issues/35794

**Closed by mjbvz** 2020-01-23 00:49 UTC
Labels: needs more info, typescript
