### ISSUE TITLE
Most recent update seems to make python code open in wrong terminal

### ISSUE THREAD

**Issue by tomshaffner** [microsoft/vscode#132390] opened 2021-09-05 14:32 UTC
Issue Type: <b>Bug</b>

As discussed at https://stackoverflow.com/questions/69050842/vs-code-python-debugger-keeps-launching-powershell, both I and another user have had the issue that python code launches in powershell no matter what I change the settings to. This makes debugging extremely cumbersome as I have to manually enter the commands to initiate it.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-1040-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (17.13GB free)|
|Process Argv|--crash-reporter-id 52c7c463-9191-46e4-9988-c0b3972a455b|
|Screen Reader|no|

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
output-colorizer|IBM|0.1.2
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.6.0
githistory|don|0.6.18
gitlens|eam|11.6.0
gitignore|mic|1.0.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
resourcemonitor|mut|1.0.7
autodocstring|njp|0.5.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30361753
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by sonicauto-david** [comment] 2021-09-05 15:32
I have had this same issue. Downgrading to July 2021 (version 1.59) fixes the issue. https://code.visualstudio.com/updates/v1_59.

**Comment by timc-enthrall** [comment] 2021-09-05 15:43
Same issue, downgrading to July 2021 fixed it for me too.  These are the instructions I followed for downgrading: https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode.

**Comment by Kronopt** [comment] 2021-09-05 16:18
I'm having the same issue.
I have git-bash as the default shell and, no matter what I do, running/debugging python code always opens powershell

**Comment by drdmitry** [comment] 2021-09-05 18:59
I have the same behavior and the sequence is the following:
- I have a JavaScript project which has a terminal open (Git Bash, which was selected as default)
- close VS Code
- Open VS Code with the same project (where the terminal window was open)
- When VS Code is loaded, it is opening the terminal window with PowerShell
- If I exit from PowerShell and hit Ctrl+` to open terminal - it is opening Git Bash

**Comment by gjsjohnmurray** [comment] 2021-09-05 19:16
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-05 19:16 UTC
Labels: *duplicate, new release

**Comment by sonicauto-david** [comment] 2021-09-07 15:24
> /duplicate of #132150 and will be fixed in upcoming recovery release.

When is the recovery release happening?
