### ISSUE TITLE
Autocomplete for "console.log()" in JavaScript and TypeScript is wrong.

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Microsoft/vscode#9072] opened 2016-07-11 14:19 UTC
- VSCode Version: 1.3.0 (1.3.0)
- OS Version: OS X 10.11.5 (15F34)

Steps to Reproduce:

1. type console.l
2. Press tab to autocomplete
3. the result is "console.console.log();"

It looks like not the method "log" is autocompleted but the entire class + function.

**Comment by dbaeumer** [comment] 2016-07-12 07:26
@VladimirAmiorkov do you have an extension installed that adds snippets. Looks like you selected a snippet. I can't reproduce this using 1.3.0

![cast](https://cloud.githubusercontent.com/assets/1931590/16758572/a8eb4ab6-4812-11e6-8b69-07516b5032ea.gif)

**Comment by dbaeumer** [comment] 2016-07-12 07:27
Please ping if you see this on a vanilla VSCode install. A test project showing the error would be helpful

**Comment by VladimirAmiorkov** [comment] 2016-07-12 07:57
I can confirm that without any extensions I can reproduce this issue in a TypeScript file (.ts) in JavaScript it seams to be ok after removing 3 extensions (TypeScript extension, Angular 2 and NativeScript)

![jul-12-2016 10-42-21](https://cloud.githubusercontent.com/assets/4989411/16759406/654ca11c-481f-11e6-9f83-f5be173a0964.gif)

**Comment by dbaeumer** [comment] 2016-07-13 10:33
@jrieken assigning to you since this is not caused by TS/JS. Looks like that an extensions adds a snippet and the snippet now wins over the TS proposal.

**Comment by jrieken** [comment] 2016-07-13 10:35
I do not own snippets

**Comment by dbaeumer** [comment] 2016-07-13 13:06
As I understand the issue the user has an extension which snippets win over TS/JS proposal. Did something change in regards of sorting/priority. It seemed to work for 1.2.x

**Comment by jrieken** [comment] 2016-07-13 13:23
@dbaeumer No - this is because TypeScript ships with a [`console.log`](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/snippets/typescript.json#L84) snippet

**Comment by dbaeumer** [comment] 2016-07-13 14:03
@jrieken yes I know, but we always did.  @VladimirAmiorkov pointed out this happened after upgrading to 1.3.0 (see https://github.com/Microsoft/vscode/issues/9072#issuecomment-231966033)

For JS his problem disappeared after uninstalling the extensions. Interestingly we don't ship with a log snippet for JS. This is why I ask you whether something has changed in the code to pick the first match.

For TS this is a very strange behavior and I don't know whether its is you or @joaomoreno. See the screen cast. When you first type the 'l' the log method is selected when you go back the snippet is selected. 
![cast](https://cloud.githubusercontent.com/assets/1931590/16806082/548f794a-4913-11e6-8664-b6830501dbcf.gif)

**Comment by jrieken** [comment] 2016-07-13 14:12
@aeschli owns the [`SnippetRegistry`](https://github.com/Microsoft/vscode/commits/master/src/vs/editor/common/modes/supports.ts) which is responsible for inserting snippet completions

**Comment by aeschli** [comment] 2016-07-13 14:33
The problem is IMO not that the snippet proposal appears: Its name prefix-matches the current word, that's why it appears. The problem is that it get's ranked before any of the language proposals in particular the log proposals. 
Either we improve the sort order or we remove snippet proposals from the the code completion list and put them on a separate key.

**Comment by jrieken** [comment] 2016-07-14 15:12
closing as duplicate of #9286

**Closed by jrieken** 2016-07-14 15:12 UTC
Labels: bug, duplicate

**Comment by masaeedu** [comment] 2016-07-30 03:26
@jrieken #9286 is a feature request, this is a bug. Is this bug fixed, or is there a workaround enabled by #9286?
