### ISSUE TITLE
YET another :   The connection to the terminal's pty host process is unresponsive, the terminals may stop working. 

### ISSUE THREAD

**Issue by lgLindstrom** [microsoft/vscode#118606] opened 2021-03-10 07:54 UTC
Hi

I am using PlatformIo and trying to upload to my development card using a serial port and get this (see headline) message.
I have noticed error reports on this issue before,, but they are all closed.
Unfourtnatly the problem still exists for me.

Version: 1.55.0-insider (user setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by xianghongai** [comment] 2021-03-11 06:17
![VSCode-Restart pty host](https://user-images.githubusercontent.com/2075006/110744196-40358a80-8274-11eb-8776-858fd8ce5dbe.png)

```bash
The connection to the terminal's pty host process is unresponsive, the terminals may stop working.
restart pty host
```

```
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by iamzuijiasunyou** [comment] 2021-03-11 06:57
same issue for me

**Comment by eisenwinter** [comment] 2021-03-12 08:16
same issue here on all devices where VS code was updated recently

```
Version 1.54.1
Commit f30a9b73e8ffc278e71575118b6bf568f04587c8
OS: Windows 10
Node.js: v12.18.4
```

**Comment by lgLindstrom** [comment] 2021-03-12 08:20
@meganrogge ,, can you please respond on this issue ???

**Comment by NarmyOnDiscord** [comment] 2021-03-14 11:51
same here

**Comment by lgLindstrom** [comment] 2021-03-19 09:00
Is there a way to go back to a older version of VScode,,??? I am totaly stuck at the moment ...

**Comment by jcobreros** [comment] 2021-03-28 11:44
Same here

**Comment by meganrogge** [comment] 2021-03-30 00:38
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

Duplicate of #117956

**Closed** 2021-03-30 00:38 UTC
Labels: *duplicate, bug, integrated-terminal

**Comment by lgLindstrom** [comment] 2021-03-30 05:40
I have tried this version. Created after the other issues was closed.
It is still not working.  Thats was why I created THIS issue.

Version: 1.55.0-insider (user setup)
Commit: 5d80c30
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by frunox** [comment] 2021-04-14 13:41
Still happens intermittently.

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
