### ISSUE TITLE
"terminal.integrated.defaultProfile.windows"

### ISSUE THREAD

**Issue by Mr-Vipi** [microsoft/vscode#132381] opened 2021-09-05 10:47 UTC
Issue Type: <b>Bug</b>

Since version 1.60, when I start my VS Code, even though my default integrated terminal is set to Git Bash it opens PowerShell. 
I tried VS Code Insider as well same issue.

![Animation](https://user-images.githubusercontent.com/58825526/132124070-2dead81d-aa41-467e-ba21-ade459debb70.gif)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.62GB free)|
|Process Argv|--crash-reporter-id 542ed85f-4729-49f3-9b4e-9b10d3b19b24|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-it|MS-|1.60.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30361775
pythonf5test824cf:30361778
vsdyn478:30356813
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-05 13:26
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-05 13:26 UTC
Labels: *duplicate, new release
