### ISSUE TITLE
Go to definition not working for .scss or .graphql files 

### ISSUE THREAD

**Issue by stevenfitzpatrick** [Microsoft/vscode#70128] opened 2019-03-09 18:38 UTC
- VSCode Version: Version 1.32.0 (1.32.0)
- OS Version: Mac High Sierra 10.13.6

Steps to [Reproduce:]

Within a folder have a .js, .scss and a .graphql file.

When I add an import it will only suggest the `.js` file and ignore the `.scss` and `.graphql` file.

<img width="1060" alt="Screen Shot 2019-03-09 at 18 35 23" src="https://user-images.githubusercontent.com/23268855/54075716-6d708c00-429a-11e9-9463-80f045355c22.png">

Also the Command + Click does not work on `.scss` and `.graphql` files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-03-10 23:48
Duplicate of https://github.com/Microsoft/TypeScript/issues/19018

**Closed by mjbvz** 2019-03-10 23:48 UTC
Labels: javascript
