### ISSUE TITLE
Deselect multiple cursors

### ISSUE THREAD

**Issue by Horray** [Microsoft/vscode#19659] opened 2017-02-01 02:24 UTC
When you use multiple cursors using <kbd>Alt</kbd> + <kbd>Click</kbd>, you can add multiple cursors, but you can't deselect a cursor. Once you clicked, you can't unclick it, other than <kbd>Ctrl</kbd> + <kbd>u</kbd>, which undoes the last cursor action.

Can you add a deselect feature, where you <kbd>Alt</kbd> + <kbd>Click</kbd> on an added cursor to deselect it?

**Comment by alexandrudima** [comment] 2017-02-01 07:47
Duplicate of #16486

**Closed by alexandrudima** 2017-02-01 07:47 UTC
