### ISSUE TITLE
VSCode freezes/hangs/hitches when overlapping on Wayland

### ISSUE THREAD

**Issue by grandprixgp** [microsoft/vscode#84754] opened 2019-11-14 01:49 UTC
- VSCode Version: stable:    8795a988 2019-11-13 (20) 143MB classic
- OS Version: OS: Pop!_OS 19.10 x86_64 on 5.3.0-20-generic 
- Extra: running under Wayland - **only happens in Wayland AFAICTL**

Steps to Reproduce:

1. Open VSCode and maximize it. Verify everything works nominally.
2. Resize VSCode and position it so that the window overlaps / extends off-screen.
3. Type and notice that VSCode freezes/hangs/hitches.
4. The hitches are worse and more constant the more the app overhangs.
5. You can resolve freezes/hangs/hitches by moving the mouse over other areas of the screen.

[Quick screencap demonstrating bug](https://streamable.com/2bhel)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by deepak1556** [comment] 2019-11-14 02:02
The support for wayland comes from chromium, can you verify if chromium 76 has the same issue by loading https://vscode-web-test-playground.azurewebsites.net/

**Comment by grandprixgp** [comment] 2019-11-14 04:55
Installed `chromium 78.0.3904.97` via `snap` and failed to reproduce bug.

Installed `chromium 76.0.3809.100` via `apt` and failed to reproduce bug.

Also discovered that hitches can be avoided by having media play back (Streamable for example), but has to be visible.

**Comment by deepak1556** [comment] 2019-11-15 05:14
@grandprixgp thanks for testing, can you also try our insiders build https://code.visualstudio.com/insiders/ and exploration build https://github.com/microsoft/vscode/issues/84574#issuecomment-553260601 ? which have newer versions of the runtime framework

**Comment by grandprixgp** [comment] 2019-11-15 16:47
@deepak1556 Sorry for delay, seems like alerts bugged out. I will test shortly.

**Comment by grandprixgp** [comment] 2019-11-16 00:19
@deepak1556 Bug reproducible with Insiders build. Bug not reproducible on Exploration build!

Seems like Electron 7.0.1 resolves this.

**Comment by deepak1556** [comment] 2019-11-18 20:01
@grandprixgp thanks for testing it, I will see if I can narrow down the upstream issue on my end.

**Comment by deepak1556** [comment] 2020-03-10 23:28
The fix should be available with our latest stable `1.43`, @grandprixgp can you please confirm. Thanks!

**Comment by grandprixgp** [comment] 2020-03-10 23:55
I will test it first thing tomorrow morning ;) Good job!

**Comment by DasVoelkel** [comment] 2020-03-12 21:01
My issue #92276 was marked a duplicate of this, for me the error also occurs if I edit a file, and close it.
The dialog box that pops up with the choices don't save, cancel, save. Also causes all input after clicking an option to not register (keyboard won't work afterwards, and the rest of the UI can be navigated, but no action happens when clicking anything, e.g. when trying to change folder it won't open the file browser popup.
![1584046924_grim](https://user-images.githubusercontent.com/18036573/76566408-fb361700-64ac-11ea-9bff-b473250a6581.png)

**Comment by deepak1556** [comment] 2020-03-12 21:30
@DasVoelkel does it happen with latest stable as well `1.43` ?

**Comment by DasVoelkel** [comment] 2020-03-12 21:41
yes

**Comment by MPratley** [comment] 2020-04-30 19:01
Am getting this issue, but turning off native window decorations seems to fix it thankfully.

**Comment by ernstp** [comment] 2020-05-04 07:16
Turning off native window decorations did not solve it for me.

**Comment by deepak1556** [comment] 2020-08-28 21:13
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?

**Closed** 2020-09-05 11:41 UTC
Labels: electron-6-update, needs more info, upstream

**Comment by ernstp** [comment] 2020-09-05 11:42
Yeah I don't think this happens anymore!

**Comment by grandprixgp** [comment] 2020-09-14 05:26
Sorry guys, I would love to test this, but the NVMe with my old installation has gone missing. I might get around to setting up a fresh environment just to test this but it's unlikely.
