### ISSUE TITLE
SCSS files do not recognize @layer

### ISSUE THREAD

**Issue by OpCyc-Ben** [microsoft/vscode#203327] opened 2024-01-24 11:50 UTC
Type: <b>Bug</b>

go to https://vscode.dev/ in a new browser
open a new file and set language to .scss specifically!
type "@layer { }"
@layer won't be recognized, although it is in a vanilla .css file. Syntax highlighting inside @layers messes up.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (0.76GB free)|
|Process Argv|--crash-reporter-id 153528b2-c72e-49d9-a465-597d6bd5b7ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|17.1.0
vscode-custom-css|be5|7.2.1
npm-intellisense|chr|1.4.5
gitlens|eam|14.7.0
EditorConfig|Edi|0.16.4
copilot|Git|1.153.0
copilot-chat|Git|0.11.1
plantuml|jeb|2.17.5
vscode-docker|ms-|1.28.0
csdevkit|ms-|1.2.7
csharp|ms-|2.15.30
vscode-dotnet-runtime|ms-|2.0.0
vscodeintellicode-csharp|ms-|0.1.26
remote-wsl|ms-|0.81.9
powershell|ms-|2024.0.0
vs-keybindings|ms-|0.2.1
vscode-stylelint|sty|1.3.0
markdown-pdf|yza|1.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by aeschli** [comment] 2024-01-24 13:22
`@layer` by itself is well supported:
![image](https://github.com/microsoft/vscode/assets/6461412/f1bca2f5-4bc3-49a5-aa30-d37579f446b0)
```
@layer module, state;

@layer state {
  .alert {
    background-color: brown;
  }
  p {
    border: medium solid limegreen;
  }
}

@layer module {
  .alert {
    border: medium solid violet;
    background-color: yellow;
    color: white;
  }
}
```

**Comment by aeschli** [comment] 2024-01-24 13:24
Can you provide the code sample that shows the problem?

**Comment by aeschli** [comment] 2024-01-24 13:24
Also see https://github.com/microsoft/vscode/issues/81038

**Comment by OpCyc-Ben** [comment] 2024-01-24 13:28
![image](https://github.com/microsoft/vscode/assets/142500282/ccb52727-22a5-4020-8561-0a455f5edac7)
mhm

**Comment by burtek** [comment] 2024-01-24 13:30
@OpCyc-Ben I wonder if auto-indentation is caused by a ependency, same as in #81038

**Comment by alexr00** [comment] 2024-01-24 14:02
We need to find a new scss syntax highlighting grammar: https://github.com/microsoft/vscode/issues/81038.

I'm marking this issue as a duplicate of https://github.com/microsoft/vscode/issues/81038, so that when https://github.com/microsoft/vscode/issues/81038 is resolved we can come back and test this issue.

**Closed by alexr00** 2024-01-24 14:02 UTC
