### ISSUE TITLE
Allow text selection in process explorer

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#48585] opened 2018-04-24 18:24 UTC
#48431 

While the mouse is on top of the processes, the cursor becomes `text` style but we can't select text. Either we change the cursor style back to `default`, or we support text selection.

**Comment by RMacfarlane** [comment] 2018-04-26 03:07
Changed the cursor to `default` for now, will work on supporting text selection in debt week

**Comment by RMacfarlane** [comment] 2018-05-02 23:29
Closing as duplicate of https://github.com/Microsoft/vscode/issues/48961

**Closed by RMacfarlane** 2018-05-02 23:29 UTC
