### ISSUE TITLE
Polish language support

### ISSUE THREAD

**Issue by wojtekmaj** [Microsoft/vscode#14241] opened 2016-10-24 00:41 UTC
Please add Polish support and Polish keyboard key bindings (Polish keyboard does not use alt+[letter] for shortcuts as this conflicts with inputting letters like ążółćń).

I'd be happy to help with translations in case you are open to contributions via services like getlocalization.

**Comment by roblourens** [comment] 2016-10-24 01:29
I know we've worked a lot on international keyboards, so can you clarify exactly what problem you're having with the polish keyboard?

**Comment by wojtekmaj** [comment] 2016-10-24 06:32
@roblourens, there's a lot of trouble when using Polish keyboard and trying to enter Polish diacritic signs. I believe that US keyboard copies some shortcuts like ctrl+s to alt key as well; the thing is, alt+[aceszxnlo] are used for entering letters: ąćęśżźńłó respectively. This results in a conflict and inability to enter said letters.

This is a very common problem with American software in Poland, even Windows 10 Mail and Store app were having it for a while.

The problem with keybindings has already been raised by issues: #14234 #13198 #11090 #9205

Please mind that this request is for Polish language support in general, including the UI, which was not mentioned before on GitHub, I believe.

**Comment by Tyriar** [comment] 2016-10-24 14:23
Assigning to @dbaeumer as the keybindings issues seem to be closed or tracked elsewhere.

**Comment by dbaeumer** [comment] 2016-10-25 10:56
@wojtekmaj just to be clear: when pressing alt+e for example VS Code takes you to the main menu bar and opens the edit menu. VS Code doesn't define any keyboard shortcut alt+e for a specific command.

**Comment by wojtekmaj** [comment] 2016-10-25 11:10
Actually, that's not correct for my case.

Pressing alt+e creates letter ę for me :) And it works in VSCode as well. The only one not working in VSCode as of now is alt+l that should make the letter ł. Interestingly, capital Ł (shift+alt+l) works fine.

**Comment by dbaeumer** [comment] 2016-10-25 16:42
OK thanks. Then this has nothing to do with i18n. 
@alexandrudima I checked and by default we don't define any keyboard shortcut for alt+l

**Comment by wojtekmaj** [comment] 2016-10-25 17:28
But it is about i18n! It's about adding Polish UI language!

**Comment by dbaeumer** [comment] 2016-10-26 07:50
@wojtekmaj there are different things here: having the UI strings in Polish is indeed a i18n issue. But translating it to Polish will not fix the problem that if you press alt+I you don't get the correct input letter. 

I will move the item back to i18n then. Please keep discussing the letter input in the other issues then.

**Comment by alexandrudima** [comment] 2016-10-26 09:43
@wojtekmaj re: keyboard layouts.

I believe it is `AltGr+letter` that introduces special characters (i.e. it is usually printed on the key as `AltGr`, otherwise it is the `Alt` located on the right hand side of the spacebar). `Alt+letter` will not produce any characters on the Polish keyboard layout.

https://www.microsoft.com/resources/msdn/goglobal/keyboards/kbdpl1.html

In VSCode (driven by Chromium) `AltGr+letter` is, AFAIK detected as `ctrl+alt+letter`.

On Windows, we don't ship with default keybindings for `ctrl+alt+letter` especially because `ctrl+alt+` is `AltGr+` and used for special characters on different keyboard layouts. Can you please tell us what keyboard combinations (**only coming from the default installation** -- i.e. code --disable-extensions) do not work for Polish out of the box?

**Comment by wojtekmaj** [comment] 2016-10-26 09:52
That is correct, I meant AltGr for the whole time. AltGr + l does not produce the letter ł. But let's keep that discussion in related issues that has already been created:

#14234 #13198 #11090 #9205 (especially the last one, that says specifically about this specific letter)

**Comment by alexandrudima** [comment] 2016-10-26 10:28
@wojtekmaj Agreed, please also see the resolution on #9205:

https://github.com/Microsoft/vscode/issues/9205#issuecomment-232889957

> "I have extension "Bookmarks Alessandro Fragnani" and the problem is with that extension.

Please create an issue on that extension. Here is the root cause -- https://github.com/alefragnani/vscode-bookmarks/blob/master/package.json#L112

**Comment by danyeh** [comment] 2017-05-03 05:54
@wojtekmaj, in case you are interested in contributing translation. Here is the instruction. http://aka.ms/vscodeloc. Discussion is still ongoing about what % of translation need to reach before integrate to VS Code product.

**Comment by wojtekmaj** [comment] 2017-05-03 21:25
@danyeh Sweet! Just what I dreamed of. Thanks!

**Comment by replay111** [comment] 2017-07-13 20:18
Hi,

I've just installed new version of VSCode (1.14.0 for Mac), and I have same problem as @wojtekmaj. I removed keybindings for alt+z (for Polish location still is binded to wordwrap #13198) but in integrated console I cant type alt+l => ł . I removed all extension from ~/.vscode and before installation I removed ~/Library/Application Support/Code so my installation is clean.
In iTerm alt+l works fine (terminal shows "ł").

**Comment by replay111** [comment] 2017-07-14 12:24
Great, now when I removed binding to alt+z, word wrap is not working from menubar (view -> toggle wordwrap) :(

**Comment by n074v41l4bl34u** [comment] 2017-07-29 14:55
The problem is that **Polish keyboard layout, 'right alt' + letter: [acelnoszx] produces a Polish diactric character i.e. [acelnoszx] -> [ąćęłńóśżź]**.

VS Code has no concept of left/right alt key - at least on Windows, **hence many 'alt + letter' combinations produce Polish special letters instead of activating commands**.

It also applies to to more complex keybindings like Ctrl + Alt + letter and it effectively renders using VSCode keyshortcuts useless.

There is no issue in full Visual Studio, so I do not see why it is not working as expected in VS Code.

Can you fix it somehow?

**Comment by piotrku** [comment] 2017-11-28 22:53
Looks like this (RIGHT)ALT+l problem cannot be solved for a year now :(
Hey that can't be so difficult!
I'd gladly unbind this shortcut only if it only was possible.

**Comment by mrrau** [comment] 2018-01-03 10:20
Fix for this should be simple: when keyboard setting in OS is "Polish (programmers) keyboard", don't trigger Ctrl+Alt shortcuts with AlrtGr (right Alt) key.  

For now the only real solution is to unset/change conflicting keybindings.

**Comment by piotrku** [comment] 2018-01-03 10:49
@mrrau the problem is that you cannot unset this binding, because it doesn't appear in the bindings configuration table :)

**Comment by mrrau** [comment] 2018-01-03 14:23
@piotrku 
Go to "Preferences: Open keyboard shortcuts".
Click "For advanced customizations open and edit keybindings.json"
Add empty keybinding for Polish letters,
    {
        "key": "ctrl+alt+l",
    },
it will block editor and extensions to use it.

Anyway, I think handling AltGr key can be an [Electron](https://github.com/electron) issue.

**Comment by piotrku** [comment] 2018-01-04 07:48
@mrrau - you're right "ctrl+alt+l" does the trick when using "Polish (programmers) keyboard" !

**Comment by hash** [comment] 2018-03-14 12:27
In Version 1.21.0
Alt - l is bound to toggleFindInSelection
when removed, nothing happens on Alt - l

**Comment by pociej** [comment] 2018-05-08 10:13
alt + z doesn't work at all

**Comment by piotrku** [comment] 2018-05-08 17:57
In my case the problem was created by on of the VSC extensions - it took over the Polish letter shortcut, so as a first step in solving the problem I'd try to run VSC with all extensions removed to see if the problem still exists.

**Comment by amcsi** [comment] 2018-05-23 11:10
I see there's already an open issue here. Such a shame this has been an issue for at least 1.5 years :/ I don't have a lot of high hopes of the creator fixing this basic international issue.

This is the issue I opened: #50341
I can see another old one that's sadly been dismissed without much thought with flawed reasoning: #41225

**Comment by chrisdias** [comment] 2018-09-21 04:41
I'm resolving this as a duplicate of https://github.com/Microsoft/vscode/issues/50341.  if that's not the case, please let me know and i'll reopen and assign accordingly.  cc @alexandrudima

**Closed by chrisdias** 2018-09-21 04:41 UTC
Labels: feature-request, i18n

**Comment by piotrku** [comment] 2018-09-26 17:19
altGr keys work fine for me now, aren't for you?

**Comment by wojtekmaj** [comment] 2018-09-27 10:39
Yep. But the interface is still in English.

**Comment by danyeh** [comment] 2018-09-28 16:32
@wojtekmaj , Polish language was enabled in community localization tool - Transifex. Translation completion rate has not reached the threshold (50%) that we setup to start to publish beta version of the Polish language pack. It will be great if you can help to nurture Polish community to contribute more. We certainly wish can have Polish language pack as early as possible.

VS Code community localization project info is here: https://aka.ms/vscodeloc.
Language request process info is here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
Current Polish completion rate is around 23% or so.
![image](https://user-images.githubusercontent.com/19785531/46221185-41bba400-c301-11e8-8443-3d8f37d11b6a.png)
@aldonetti , FYI.
