### ISSUE TITLE
File transfer information

### ISSUE THREAD

**Issue by Syntle** [microsoft/vscode#104861] opened 2020-08-17 20:21 UTC
I often transfer files to/from my server while being connected to it through SSH on VSCode, the issue is I can't see a list of the files being transferred or any progress info about the transfer.

It would be very helpful to know certain things like:
  - List of files being transferred
  - Progress of current file being transferred
  - Download/upload speed
  - Transfer ETA

**Comment by isidorn** [comment] 2020-08-20 08:13
Somewhat a duplicate of progress for long running operations. We would not add anything specific to SSH, and due to that closing this as a duplicate https://github.com/microsoft/vscode/issues/73996

**Closed by isidorn** 2020-08-20 08:13 UTC
