### ISSUE TITLE
Header separation is maybe a bit too subtle

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#199285] opened 2023-11-28 09:57 UTC
Testing #199155

In this case it almost looks as if I am looking at one editor:

![Image](https://github.com/microsoft/vscode/assets/2931520/f4d0c3aa-29fc-4361-9fd0-271ef2c8dbc9)

*//edit @hediet: updated screenshot*

**Comment by hediet** [comment] 2023-11-28 10:26
Closing because the initial screenshot showed an (unreproducible) bug.

**Closed by hediet** 2023-11-28 10:26 UTC
