### ISSUE TITLE
SQL - Backslash at end of string disrupts syntax highlighting

### ISSUE THREAD

**Issue by jlucktay** [Microsoft/vscode#6315] opened 2016-05-12 09:37 UTC
Could be related to #1520 / #1634 / #2830

- VSCode Version: 1.1.0
- OS Version: Windows 8.1 Pro

Steps to reproduce:
1. Create new/edit existing SQL file.
2. Enter a string with a backslash as the last character before the terminating single quote.
3. Syntax highlighting thinks the terminating quote is escaped.

SSMS does not behave like this, and will parse the same script without this issue.

Also reproduces when starting VSCode with the --disable-extensions command line argument.

Sample screenshot:
![image](https://cloud.githubusercontent.com/assets/460028/15210098/96e043b4-182c-11e6-9790-c10b2d5e4d06.png)
The select statement on line 4 shouldn't be that colour, since it is not part of the string.

The same snippet in SSMS:
![image](https://cloud.githubusercontent.com/assets/460028/15210149/d6180012-182c-11e6-9dba-c1144d6c1fb4.png)

**Comment by aharpervc** [comment] 2016-05-12 20:44
Related: https://github.com/Microsoft/vscode/issues/5223, https://github.com/atom/language-sql/issues/13

**Comment by aeschli** [comment] 2016-05-13 18:49
duplicate of #5223

**Closed by aeschli** 2016-05-13 18:49 UTC
