### ISSUE TITLE
Show git status for files in explorer

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#5866] opened 2016-04-26 22:57 UTC
what if i have a folder of 100 files all changed except one or two
i can see the changed one in git view but how to find the unchanged ones?
if the modified files were a different color in explorer then it would be easy to see (like Atom)
thanks

**Comment by CristyTarantino** [comment] 2016-06-03 09:50
+1

**Comment by eosrei** [comment] 2016-08-05 22:38
Duplicate of #178 @bpasero

**Closed** 2016-08-06 13:56 UTC
Labels: feature-request, files

**Comment by rdewolff** [comment] 2016-12-28 12:21
Any plugin doing that?
