### ISSUE TITLE
ANSI SGR sequences not correct on windows (but correct on WSL)

### ISSUE THREAD

**Issue by chtenb** [microsoft/vscode#146471] opened 2022-03-31 19:51 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

My apologies if this is a duplicate, but I couldn't find it.

Steps to Reproduce:

I wrote a little nushell script to test the ansi SGR escape code behavior of a terminal

```nu
def printcolors [] {
  for $color-offset in [30 40 90 100] {
    for $color in 0..9 {
      if $color != 8 { # 8 is not a color code
        for $style in 1..9 {
          build-string $"\e[($color + $color-offset);($style)m" $'\e[($color + $color-offset)($style)m' "\e[0m"
        } | str collect
      }
    } | flatten
  } | flatten
}
```

The interpretation and rendering is correct in WSL, but not in windows itself.

WSL             |  Windows
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/1030961/161133227-e00ed2d7-d7f7-4f64-8dc1-49e38f8ff5cf.png)  |  ![image](https://user-images.githubusercontent.com/1030961/161133105-24c80c1b-a83d-472e-bfec-ed4883ffa075.png)

The following things go wrong:

1. Color inversion uses color 0 (black, but gray in my color theme) as foreground, instead of the background color
2. Dimmed colors are ignored
3. Invisibility is sometimes ignored
4. Using color 0 as background color (i.e. 40) does not seem to work (though bright black, i.e. 100, does seem to work)

**Comment by Tyriar** [comment] 2022-03-31 20:25
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2022-03-31 20:25 UTC

**Comment by chtenb** [comment] 2022-04-04 21:22
@Tyriar You've probably considered this, but seeing as the terminal is a pretty important part of VSCode, wouldn't it be worth it to also bundle the latest conpty with VSCode on windows? 

1. This would be good for users in that the terminal experience would be cutting edge.
2. This would be good for the competence of VSCode. Right now it the windows terminal always has the upper hand.
3. This would be good for the VSCode team because they would hopefully have less complaints from the community, meaning less time wasted with crunching issues like this one.
