### ISSUE TITLE
Extension Manager

### ISSUE THREAD

**Issue by jergsistemas** [microsoft/vscode#86762] opened 2019-12-11 17:25 UTC
Issue Type: <b>Feature Request</b>

Hi, I don't know if there's already something to manage extension by it would be awsome if there could be a Feature or an Extension that we could use to manager our extensions by the kind of development that we want to do, If I want to work with Angular then have a extension setup for it (even better if we could save settings for those extension), if I want to work with Ionic then for Ionic, if I want to use Dart / Flutter then different setup for those an so on, of course we'll have to save those setups and call them when we want to use it...

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment] 2019-12-11 22:24
Duplicate of https://github.com/microsoft/vscode/issues/20599

**Closed by RMacfarlane** 2019-12-11 22:24 UTC
Labels: extensions
