### ISSUE TITLE
code color

### ISSUE THREAD

**Issue by Jo-chana** [microsoft/vscode#110932] opened 2020-11-19 10:36 UTC
Issue Type: <b>Bug</b>

the color of codes on editor window is all black.. almost invisible. i can't change that color. what causes this situation?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|. --crash-reporter-id 7f180e92-384c-486e-bafe-e105c84fba61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|1.7.1
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
cpptools|ms-|1.1.2
vscode-react-native|msj|1.1.1
vscode-lldb|vad|1.6.0
material-theme|zhu|3.9.6

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-11-19 10:39
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Please attach screenshot with example of problem. What language causes this problems or it's for all languages?

**Comment by Jo-chana** [comment] 2020-11-19 10:44
![Screen Shot 2020-11-19 at 7 41 06 PM (2)](https://user-images.githubusercontent.com/55430747/99655583-3dcddb80-2a9f-11eb-959f-009488ee3252.png)
Literally the color of all the texts on editor is black.
i guess it is for all languages, and Reloading Window with extensions disabled option wasn't improving the situation.

**Comment by IllusionMH** [comment] 2020-11-19 11:23
Is it still black if you comment out `editor.fontFamily` line in `settings.json`?

Look like duplicate of #100840 and Source Coode Pro is may be culprit see https://github.com/microsoft/vscode/issues/100840#issuecomment-671267067

Workaround https://github.com/microsoft/vscode/issues/100840#issuecomment-726769115

**Comment by Jo-chana** [comment] 2020-11-19 11:27
It is solved after commenting out editor.fontFamily line in settings.json file.
Thank you so much!

**Comment by IllusionMH** [comment] 2020-11-19 12:36
/duplicate of #100840 

As was mentioned above https://github.com/microsoft/vscode/issues/100840#issuecomment-726769115 suggests that you can install this font from Google Fonts and it should work.

**Closed** 2020-11-19 12:37 UTC
Labels: *duplicate, needs more info
