### ISSUE TITLE
VSCode 1.90 crashes when switching monitors

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#214938] opened 2024-06-12 10:37 UTC
Type: <b>Bug</b>

I have an external monitor connected to my laptop via a KVM switch. Whenever I switch to that, the internal monitor is disabled and the desktop is shown on the external monitor only, and vice versa. Since the last VSCode update, whenever I switch screens, VSCode just crashes silently. The problem also happens with all extensions disabled.

See video:
[Screencast from 12.06.2024 12:32:39.webm](https://github.com/microsoft/vscode/assets/17641229/7c153b7e-cb27-4200-987d-6fef10e010f4)

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 6.5.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2982)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|31.05GB (26.45GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 23d56de3-001d-431f-81e8-0c352e7ea82f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
toggle-excluded-files|amo|2.0.0
tsl-problem-matcher|amo|0.6.2
vscode-zipfs|arc|3.0.0
chronicler|arc|0.1.16
search-crates-io|bel|1.2.1
lit-html|bie|1.11.1
vscode-tailwindcss|bra|0.10.5
vscode-diff-viewer|cap|1.5.0
ruff|cha|2024.26.0
css-theme-completions|con|0.0.5
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|2.4.4
dprint|dpr|0.16.2
gitlens|eam|15.1.0
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|10.4.0
codespaces|Git|1.16.22
copilot|Git|1.200.0
copilot-chat|Git|0.16.1
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
vscode-graphql-syntax|Gra|1.3.6
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
compare-folders|mos|0.24.3
vscode-json5|mrm|1.0.0
vscode-azureresourcegroups|ms-|0.9.1
vscode-docker|ms-|1.29.1
vscode-language-pack-de|MS-|1.89.2024050109
vscode-dotnet-runtime|ms-|2.0.6
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-account|ms-|0.12.0
cmake-tools|ms-|1.18.42
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.13
makefile-tools|ms-|0.9.10
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
test-adapter-converter|ms-|0.1.9
vscode-js-profile-flame|ms-|1.0.9
vscode-serial-monitor|ms-|0.11.0
hide-gitignored|npx|1.1.0
vetur|oct|0.37.3
vscode-twoslash-queries|Ort|1.2.2
vscode-versionlens|pfl|1.13.1
typescript-mono-repo-import-helper|q|0.0.6
tsserver-live-reload|rbu|1.0.1
java|red|1.31.0
vscode-sort-json|ric|1.20.0
lit-plugin|run|1.4.3
rust-analyzer|rus|0.3.1958
gitconfig|sid|2.0.1
even-better-toml|tam|0.19.2
cmake|twx|0.0.17
sort-lines|Tyr|1.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
explorer|vit|0.12.0
vscode-arduino|vsc|0.6.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.27.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
vscode-todo-highlight|way|1.0.5
config-editor|zwa|0.0.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by deepak1556** [comment] 2024-06-13 01:40
Thanks for the details, this would be a duplicate of https://github.com/microsoft/vscode/issues/212494

Please start the application with `--use-angle=swiftshader` as a temporary workaround, fix will be available in `1.90.1` this week.

**Closed by deepak1556** 2024-06-13 01:40 UTC
