### ISSUE TITLE
crashed vscode (v 1.24 or 1.25.1  )after several minutes

### ISSUE THREAD

**Issue by abvaalgit** [Microsoft/vscode#56166] opened 2018-08-10 18:53 UTC
recently vscode is in hanging more more even i leave it now ..it is in nervous and crashed yourself

**Comment by ramya-rao-a** [comment] 2018-08-10 19:07
The title of this issue mentions tasks. Can you elaborate on that?

**Comment by abvaalgit** [comment] 2018-08-10 21:08
the titile is so clear ..work more like me with vscode to know that

**Comment by ramya-rao-a** [comment] 2018-08-11 03:36
I understand that the issue is about VS Code crashing. What I don't understand is what you mean by "by increasing runing task about 15 case in task bar windows"

Do you see this with extensions disabled as well? Try `code --disable-extensions`

**Comment by abvaalgit** [comment] 2018-08-11 14:41
![screenshot 188](https://user-images.githubusercontent.com/24298508/43992879-5108b15a-9d9a-11e8-841a-35a9c4a46dbd.png)

**Comment by abvaalgit** [comment] 2018-08-11 14:48
your product will being awful like visual studio 2017 .
all products of MIcrosoft is baloney ,stuff, crap, blather, hokum, bosh, baloney bullshit and so on

**Comment by aminabvaal** [comment] 2018-08-11 14:49
all products of Microsoft is awful

**Comment by ramya-rao-a** [comment] 2018-08-11 20:57
@abvaalgit In the screen shot, `ng serve` is running which might be resource intensive. Does VS Code become unresponsive on other occasions or only when running such tasks?

Our wiki on [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) has a lot of pointers on how we can pin point on what is causing perf issues. Please do read it and let us know if can provide more details

**Comment by abvaalgit** [comment] 2018-08-11 22:03
no in the previous versions this problem was not .recently this hanging and crashing have occurred.
i always was running `ng serve `  long ago and many other task and this issue is not seen before 1.24 1.25 version ..
your product must be robust by running thousand task from power shell downloading in git and other like that task..

you are there to create a great robust product that never will be crashed  if you don't make such that ..
go away and let other people to do that .

i wish luck for you, all stuff of microsoft daily and nightly must test product and report issues

**Comment by Cam-Shaw** [comment] 2018-08-13 02:27
@ramya-rao-a I'm getting the same issue when running Golang and Angular projects. Started happening after the latest update. Seems to happen when only when running things using the terminal in Code. It's happening every few minutes. Let me know if you need anymore information.

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by sandy081** [comment] 2018-08-13 14:48
@ramya-rao-a I am assigning this to you as you are aware of the context of the issue and being in discussion.

**Comment by ramya-rao-a** [comment] 2018-08-13 20:58
@abvaalgit, @Cam-Shaw We just released an update. Can you upgrade to VS Code 1.26.0 and see if you still see the issues?

If you still do see the window not responding, run `code --status` in an external terminal and share the output. It will show the resource usage across the different processes in VS Code. See https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu and https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu

@Cam-Shaw Are you able to reproduce the issue when running with all extensions disabled? Try `code --disable-extensions`

**Comment by Navis-Raven** [comment] 2018-08-15 01:41
Same thing on 1.26.0 the crash occurs randomly after few minuts of usage. But it's random, so it can crash or not.

I'm on windows 7

**Comment by ramya-rao-a** [comment] 2018-08-15 02:51
@Navis-Raven If you see VS Code being unresponsive, please run `code --status` and share the results. If its a complete crash, please follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues and log a separate issue

**Comment by Navis-Raven** [comment] 2018-08-15 23:39
Here are the screenshots:
![image](https://user-images.githubusercontent.com/15887222/44179002-21d77480-a0f5-11e8-9584-e578e2aac140.png)

code --status gives nothing

![image](https://user-images.githubusercontent.com/15887222/44179023-34ea4480-a0f5-11e8-934d-601fea1a4495.png)

**Comment by Navis-Raven** [comment] 2018-08-15 23:44
I'm on Windows 7

I tried again code --status it gave me this (but this doesn't occurs every time)
![image](https://user-images.githubusercontent.com/15887222/44179170-ce195b00-a0f5-11e8-8abf-c2eed050b8f7.png)

**Comment by ramya-rao-a** [comment] 2018-08-15 23:49
@Navis-Raven And is this with extensions disabled or not? Can you disable all extensions just to ensure that one of the installed extensions are not the reason for this? Did you such behavior before 1.26?

**Comment by Navis-Raven** [comment] 2018-08-16 00:05
Yes there was some extensions but very few of the.

Now they are at the minimum. 

![image](https://user-images.githubusercontent.com/15887222/44179733-e9399a00-a0f8-11e8-926c-4e53818d1ecb.png)

**Comment by Navis-Raven** [comment] 2018-08-16 00:07
Did you such behavior before 1.26?

No I'm new on VSCode. I don't have previous versions

**Comment by Navis-Raven** [comment] 2018-08-16 00:09
I don't think the extension have a role in this crash, because the first time it crashed there was not many extensions. Just C/C++, French Language, and probably IAR Workbench.

**Comment by bpasero** [comment] 2018-08-16 05:16
@abvaalgit to clarify, it only crashes when you run `ng serve`, right?

**Comment by TheFitITGuy** [comment] 2018-08-16 17:18
I am having the same issue. I am running Windows 10 Enterprise, Version 1709, OS Build 16299.551. 

I am running 1.26, I did not have this issue running earlier versions of VS Code. I installed the new recommended user setup distribution the crashing was more frequent. I switched back. I a running one extension when I got this error. At this time I can not reproduce the error with all extensions disabled but due to the randomness of the crashing I am not saying that it can not be reproduced. Please let me know if you would like me to provide more information.  VS Code has been great but this last update something changed that has made it unstable on my system. 

![image](https://user-images.githubusercontent.com/25332879/44223700-32134200-a13d-11e8-9b52-187a57662dd4.png)

code --status: 


Version:          Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)
Memory (System):  15.89GB (8.50GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code\Code.exe
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %	Mem MB	   PID	Process
    0	    68	  4340	code main
    0	   119	 11632	   gpu-process
   24	   203	 11956	   window (Confirm-ADMembership.ps1 - PowerShell - Visual Studio Code)
    0	    36	  8752	     searchService
    0	    14	 11780	     watcherService 
    0	    10	  2356	       console-window-host (Windows internal process)
    0	     6	 13572	     winpty-process
    0	    84	 16552	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     9	 18424	       console-window-host (Windows internal process)
    0	    73	 15548	     extensionHost
    0	    37	   184	       searchService
    0	    50	 17464	       electron_node jsonServerMain.js 
    0	     6	 16536	     winpty-process
    0	   229	   676	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& 'C:\Users\rtoumbs\.vscode\extensions\ms-vscode.powershell-1.8.3\modules\PowerShellEditorServices\Start-EditorServices.ps1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.8.3'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\rtoumbs\.vscode\extensions\ms-vscode.powershell-1.8.3\modules'-EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\rtoumbs\.vscode\extensions\ms-vscode.powershell-1.8.3\logs\1534438462-1fd3c8f8-7ce5-46ac-9a57-f744890830981534438458046\EditorServices.log' -SessionDetailsPath 'C:\Users\rtoumbs\.vscode\extensions\ms-vscode.powershell-1.8.3\sessions\PSES-VSCode-4340-711047' -FeatureFlags @()"
    0	     9	  1480	       console-window-host (Windows internal process)
    0	    68	 12124	   shared-process
    0	     9	 13800	   utility
Workspace Stats:
|  Window (Confirm-ADMembership.ps1 - PowerShell - Visual Studio Code)
|    Folder (PowerShell): 414 files
|      File types: ps1(293) dll(53) md(13) psd1(12) psm1(12) xml(9) config(6)
|                  pdb(6) html(2) MD(2)
|      Conf files: launch.json(1) sln(1)
|      Launch Configs: PowerShell(5)

**Comment by ramya-rao-a** [comment] 2018-08-16 18:11
@TheFitITGuy Your issue seems to be specific to powershell. It is being tracked in https://github.com/Microsoft/vscode/issues/56430

**Comment by bpasero** [comment] 2018-08-17 05:11
@abvaalgit to clarify, it only crashes when you run ng serve, right?

**Closed** 2018-08-24 08:01 UTC
Labels: freeze-slow-crash, needs more info

**Comment by Navis-Raven** [comment] 2018-08-24 08:04
Why the bot has closed it while this topic has recent activities just 7 days ago ???

**Comment by Navis-Raven** [comment] 2018-08-24 08:07
A new information is that I use VSCODE on my Windows 8.1 and I had no crash to this date.

**Comment by Navis-Raven** [comment] 2018-08-27 22:32
I've reactivated and reinstalled all removed plugin in order to test this news version, to see if it freezes or not;

**Comment by Navis-Raven** [comment] 2018-09-02 00:39
I didn't have an crash since this new version 1.26.1

**Comment by ramya-rao-a** [comment] 2018-09-12 23:26
Thanks @Navis-Raven

**Comment by Navis-Raven** [comment] 2018-09-16 18:45
no pb
