### ISSUE TITLE
Unable to restore Git Bash as default integrated terminal profile

### ISSUE THREAD

**Issue by burzomir** [microsoft/vscode#132442] opened 2021-09-06 10:11 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open settings.json
2. Edit the following line: "terminal.integrated.defaultProfile.windows": "Git Bash"
3. It says Value is not accepted. Valid values: "PowerShell", "Command Prompt", "Ubuntu (WSL)", "JavaScript Debug Terminal".
4. It used to work before the update with "terminal.integrated.shell.windows". UI also doesn't let to select Git Bash
"terminal.integrated.profiles.windows": {

    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash",
      "path": ["D:\\apps\\git\\bin\\bash.exe"]
    }
  }

![image](https://user-images.githubusercontent.com/13577810/132201120-23daa03f-d774-42a5-ba3c-d1635a5e28fd.png)

**Comment by albertosantini** [comment] 2021-09-06 10:14
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Closed** 2021-09-06 10:55 UTC
Labels: *duplicate
