### ISSUE TITLE
Integrated terminal does not accept numbers [1-8] when in haskell's ghci 

### ISSUE THREAD

**Issue by krepecka** [Microsoft/vscode#13901] opened 2016-10-17 18:53 UTC
- VSCode Version:  1.6.1 (Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e)
- OS Version: MS Windows 7 Professional 64bit Version 6.1.7601

Steps to Reproduce:
1. Have ghci installed
2. Open integreted terminal (ctrl + `)
3. Type ghci and ENTER. Prelude> appears
4. Type numbers 1 through 8 - system sound is played. However integrated terminal accepts 0 and 9.

![screenshot_4](https://cloud.githubusercontent.com/assets/17677991/19450963/252ad306-94b4-11e6-810b-8ccc3f351888.png)

**Comment by roblourens** [comment] 2016-10-17 18:58
Those keys work in the integrated terminal when not in ghci? And do they work in ghci in cmd.exe?

**Comment by Kristupas1421** [comment] 2016-10-17 19:02
Forgot to mention : yes, keys work in integrated terminal when not in ghci.
yes, keys work in cmd.exe when in ghci

**Comment by Tyriar** [comment] 2016-10-18 17:13
Likely related to https://github.com/Microsoft/vscode/issues/13809

**Comment by foxbunny** [comment] 2016-12-26 17:15
I'm currently using VS Code 1.8.1 on Win10 64-bit. I cannot reproduce this issue.

**Comment by Tyriar** [comment] 2017-01-03 18:14
I'll close this off then, let me know if someone else experiences this in 1.8.1+

**Closed by Tyriar** 2017-01-03 18:14 UTC
Labels: bug, integrated-terminal, windows
