### ISSUE TITLE
Cancel extension uninstall causes error

### ISSUE THREAD

**Issue by Senpos** [Microsoft/vscode#35903] opened 2017-10-09 12:54 UTC
- VSCode Version: **1.17**
- OS Version: **Windows 10**

Steps to Reproduce:
1. Open any installed extension page
2. Press "**Uninstall**" button
3. In the prompt window press "**Cancel**"

[Short video that shows the problem](https://drive.google.com/uc?id=0B6HBCntn0EZRUmQ2ZGx4d3VHVTA)

**Error log from** _Developer Tools_

```
webview.ts:151 [Embedded Page] Refused to load the image 'http://vsmarketplacebadge.apphb.com/version-short/HookyQR.beautify.svg' because it violates the following Content Security Policy directive: "img-src https:".

webview.ts:151 [Embedded Page] Refused to load the image 'http://vsmarketplacebadge.apphb.com/rating-short/HookyQR.beautify.svg' because it violates the following Content Security Policy directive: "img-src https:".

webview.ts:151 [Embedded Page] Refused to load the image 'http://vsmarketplacebadge.apphb.com/installs/HookyQR.beautify.svg' because it violates the following Content Security Policy directive: "img-src https:".

messageService.ts:125 e.reduce is not a function: TypeError: e.reduce is not a function,    at e.joinErrors (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:214881),    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:214741,    at Object.m [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:66117),    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:69609),    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:70930),    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:70447),    at n (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:68147),    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:71739),    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:68181),    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:70930),    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcessMain.js:4:70371)
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
i.onError @ extensionEditor.ts:882
(anonymous) @ event.ts:410
(anonymous) @ event.ts:406
(anonymous) @ event.ts:222
r @ eventEmitter.ts:295
e._emitToSpecificTypeListeners @ eventEmitter.ts:162
e._emitEvents @ eventEmitter.ts:181
(anonymous) @ eventEmitter.ts:129
r @ eventEmitter.ts:295
e._emitToBulkListeners @ eventEmitter.ts:170
e._emitEvents @ eventEmitter.ts:176
e.emit @ eventEmitter.ts:196
(anonymous) @ actions.ts:237
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.doRequest.n.TPromise.t.handlers.(anonymous function) @ ipc.ts:254
e.onMessage @ ipc.ts:319
(anonymous) @ ipc.ts:206
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

```

**Comment by sandy081** [comment] 2017-10-10 08:15
Duplicate of #35539

**Closed** 2017-10-10 09:18 UTC
Labels: extensions, new release
