### ISSUE TITLE
SCM integration shows outdated information for files outside of Git repo

### ISSUE THREAD

**Issue by F30** [microsoft/vscode#90453] opened 2020-02-11 14:42 UTC
- VSCode Version: 1.42.0
- OS Version: macOS 10.14.6

When changing from an open file within a Git repo to one outside of a repo, the VS Code Git integration still lets you interact with the first file's repo and does not update to reflect the lack of a repo. Note that this **has nothing to do with opening folders**, the whole problem occurs with just opening single files.

Steps to Reproduce:

1. Open a file which is stored in a Git repository. The SCM Status Bar integration will show the current branch and the Side Bar will show changes from the repository.
2. Open a file which **not** stored in a Git repository in another tab. (For this matter, that includes Untitled new files.) Both the Status Bar and the Side Bar will still show information about the first file's repo, let you change branches, add changes etc.
3. Close the first file's tab and you may still interact with the first repo, without any indication which repo it even is or why it's shown.

Does this issue occur when all extensions are disabled?: Yes

**Comment by F30** [comment] 2020-02-11 14:44
This may be slightly related, but it **not** a duplicate of #41417 (or #37947, rather).

**Comment by joaomoreno** [comment] 2020-02-12 10:27
Both the status bar and side bar are scoped to the active repository. When you open a file contained in a repository, it automatically gets opened. When a single repository is open, it automatically becomes the active one. When you switch to another file, we don't automatically close the repository since that would annoy most people, so the repository stays open and active.

Closing as designed.

**Closed by joaomoreno** 2020-02-12 10:27 UTC
