### ISSUE TITLE
TypeScript intellisense auto import can't use

### ISSUE THREAD

**Issue by TomClinton** [Microsoft/vscode#60728] opened 2018-10-12 04:44 UTC
- VSCode Version: 1.28
- OS Version: Windows 10 1803 17134.345
Language: Chinese

Steps to Reproduce:

1. Cocos Creator : Create a new ts script
2. Can be prompted in other scripts, but not auto import the new script.

Console: err出现未知错误。有关详细信息,请参阅日志。
but i can't find log :)
Thanks Google Translate :)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-10-12 18:36
Duplicate of #60314

Should be fixed in VS Code insiders

**Closed by mjbvz** 2018-10-12 18:36 UTC
