### ISSUE TITLE
When Auto Save enabled Run Build Task should trigger save before building

### ISSUE THREAD

**Issue by hun1ahpu** [microsoft/vscode#17016] opened 2016-12-10 11:52 UTC
When I execute Run Build Task I would expect the latest **saved** version of my code to be compiled. When auto save feature is enabled as a user I assume that the code is always saved so I would expect the **current** version of the code to be always compiled. Very often I Run Build Task immediately after i make this change and it's not always yet saved at this point by the Auto Save timer.
Auto-save on compile would be the short name.

**Comment by dbaeumer** [comment] 2016-12-12 10:42
Actually we do save all files before executing any task (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L825). @hun1ahpu do you have any details on how to reproduce this. Can you share your project ?

**Comment by hun1ahpu** [comment] 2016-12-12 20:06
It seems to repro only for tasks.json. It's marked as saved after the first task execution but i can see that the previous version of tasks.json is used. After the second task execution it works as expected.

**Comment by dbaeumer** [comment] 2016-12-13 08:27
OK. Thanks.

**Comment by cheahkhing** [comment] 2017-09-05 02:00
@dbaeumer Hi, it is not always desirable to "Save All Files before executing any task".
In cases like I have multiple files being changed, but I am only interested to build my current ts file, I cannot do that. It forced me to revert my changes for other files if I accidentally build my "current active file" due to this behaviour.

Is there a way to configure / change this undesirable behaviour?

**Comment by dbaeumer** [comment] 2017-09-05 09:27
@cheahkhing currently not. But providing a hint in the task to control this is something I would accept as a feature request.

**Comment by alexr00** [comment] 2019-10-16 10:36
duplicate of https://github.com/microsoft/vscode/issues/21342

**Closed by alexr00** 2019-10-16 10:37 UTC
Labels: feature-request, tasks
