### ISSUE TITLE
`editor.edit`: Unwanted change of "end of file" selection

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#43000] opened 2018-02-05 23:16 UTC
- VSCode Version: 1.19.3
- OS Version: Ubuntu 16.04

__Steps to reproduce:__

1. Create an extension with a command executing this code:
  (Is there a way to execute code on the current editor without creating an extension?)

```js
import * as vscode from 'vscode';

// ...

// Get current editor.
const editor = vscode.window.activeTextEditor;

// Get the document last line.
const lastLine = editor.document.lineAt(editor.document.lineCount - 1);

// Select the last document char.
editor.selections = [new vscode.Selection(
    lastLine.lineNumber,
    lastLine.text.length - 1,
    lastLine.lineNumber,
    lastLine.text.length
)];

// Insert 'ADDED_STRING' at the end of the editor.
editor.edit((editBuilder) =>
    editBuilder.insert(
      new vscode.Position(lastLine.lineNumber + 1, 0),
      'ADDED_STRING'
    )
);
```

2. Open an editor and add some text in it.

3. Run the newly created command.

__Observed:__
`ADDED_STRING` is part of the selection, which is not expected.  
Only the previously selected character should be selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-04-19 10:30
Duplicate of #4802

**Closed by alexandrudima** 2018-04-19 10:30 UTC
Labels: api, editor, editor-core
