### ISSUE TITLE
WHY this call Powershell??? I set cmd to default!

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode#132337] opened 2021-09-04 13:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: windows 7 x64 sp1

Steps to Reproduce:

1. Use tasks.json cause `Error` 
![](https://i.bmp.ovh/imgs/2021/09/95c5297e336917b6.png)

I set `cmd` to default 
![](https://i.bmp.ovh/imgs/2021/09/f0bd51cd0613aa07.png)

# So, why call powershell by defalut when run tasks.json or Ctrl F5????

# **1.59 Version this tasks can run correctly.**

**Comment by thefatwhale** [comment] 2021-09-04 14:12
I went back to the previous version （1.59.1）
In this version It's Ok (call cmd.exe by default ) Follow my settings.

But 1.60.0 version Can't.
So I'm sure It's a bug.

**Comment by albertosantini** [comment] 2021-09-04 20:46
Maybe /duplicate of #132150

**Comment by gjsjohnmurray** [comment] 2021-09-05 03:42
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release

**Closed** 2021-09-05 03:43 UTC
Labels: *duplicate, new release
