### ISSUE TITLE
Typescript reference is formatted to comment

### ISSUE THREAD

**Issue by lucavallin** [Microsoft/vscode#54893] opened 2018-07-23 18:21 UTC
When I do this

```
/// <reference path="circleMath.ts"/>
/// <reference path="RectangleMath.ts" />
```

It is automatically formatted to

```
/// <reference path="circleMath.ts"/> / <reference path="RectangleMath.ts" />
```

and in general every comment. I am using TSLint with Prettier. Any idea?
Thanks!

**Comment by mjbvz** [comment] 2018-07-23 18:23
Does this reproduce with all extensions disabled?

**Comment by lucavallin** [comment] 2018-07-23 18:46
All linters at least, yes. Do you want my to try with ALL extensions?

**Comment by mjbvz** [comment] 2018-07-23 20:57
Yes, try disabling Prettier and tslint too to see which one causes this

**Comment by lucavallin** [comment] 2018-07-24 18:01
I'm happy to say I am a true idiot, I didn't disable "taichi.react-beautify" which I totally forgot I had installed.
However, I had to find an error in the console to be able to point to that. Is there a way to track what extensions are doing what? That would be handy!

**Comment by mjbvz** [comment] 2018-07-24 18:13
Ok, closing as caused by extension. Please try filing this issue against that extension

I think helping users debug what extension contributes what falls under #53146

**Closed** 2018-07-24 18:12 UTC
Labels: *caused-by-extension, typescript
