### ISSUE TITLE
Allow Custom Icons for Small Sizes

### ISSUE THREAD

**Issue by seFausto** [Microsoft/vscode#60560] opened 2018-10-10 20:38 UTC
Issue Type: <b>Feature Request</b>

I love the new custom icons on windows explorer icons, but, I have my folders in "details" view, so can't appreciate the new Icons.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

**Comment by usernamehw** [comment] 2018-10-10 20:45
Duplicate of #60200

**Closed** 2018-10-10 21:47 UTC
