### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by mukesh-kkk** [microsoft/vscode#186931] opened 2023-07-03 17:53 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.0-dev.20230702

**Steps to reproduce crash**
1.
2.
3.

**Global TS Server Plugins**

- `typescript-styled-plugin`
- `typescript-svelte-plugin`
- `@vsintellicode/typescript-intellicode-plugin`
- `ms-vsintellicode-typescript`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at InferredProject2.updateGraphWorker (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:176576:11)
    at InferredProject2.updateGraph (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:176435:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:178830:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:180449:12)
    at /Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:180679:64
    at flatMap (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:2596:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:180679:24)
    at updateOpen (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:181859:29)
    at /Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:184436:69
    at IpcIOSession.executeWithRequestId (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:184428:14)
    at IpcIOSession.executeCommand (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:184436:29)
    at IpcIOSession.onMessage (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:184478:51)
    at process.<anonymous> (/Users/mukeshkushwaha/.vscode/extensions/ms-vscode.vscode-typescript-next-5.2.20230702/node_modules/typescript/lib/tsserver.js:186059:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id bb3c8349-464e-40ec-af58-761ce46a3db3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
ng-template|Ang|15.2.0
svelte-intellisense|ard|0.7.1
vscode-django|bat|1.10.0
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
vscode-eslint|dba|2.4.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.5.0
prettier-vscode|esb|9.19.0
vscode-express-snippets|Exp|1.1.1
vscode-firefox-debug|fir|2.9.8
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.12.0
go|gol|0.39.0
vscode-drawio|hed|1.6.6
vscode-drawio-insiders-build|hed|1.6.606
canvas-snippets|hol|0.3.2
minify|Hoo|0.4.3
kubernetes-snippets|ipe|0.1.9
svelte-kit-snippets|Jak|0.0.3
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
vscode-kubernetes-tools|ms-|1.3.13
python|ms-|2022.16.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.0
vscode-typescript-next|ms-|5.2.20230702
file-and-folder-icons|nex|1.0.4
autodocstring|njp|0.6.1
vscode-css-peek|pra|4.2.0
prisma|Pri|4.16.2
vscode-thunder-client|ran|2.5.1
java|red|1.15.0
vscode-yaml|red|1.13.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1566
mdx|sil|0.1.1
svg-preview|Sim|2.8.3
autoimport|ste|1.5.4
vscode-styled-components|sty|1.7.5
svelte-vscode|sve|107.6.0
cmake|twx|0.0.17
vscode-mdx|uni|1.3.0
mdx-inline|vad|0.1.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-spring-boot|vmw|1.47.0
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.2
vscode-java-pack|vsc|0.25.12
vscode-java-test|vsc|0.39.0
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.11.1
vscode-spring-initializr|vsc|0.11.2
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
vscode-mdx-preview|xyc|0.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnoceb:30776495

```

</details>

**Comment by mjbvz** [comment] 2023-07-10 18:58
Closing as this is an old VS Code version and the crash is likely caused by one of your TS plugins

**Closed by mjbvz** 2023-07-10 18:58 UTC
