### ISSUE TITLE
Spacebar stops working

### ISSUE THREAD

**Issue by mpukit** [Microsoft/vscode#37430] opened 2017-11-01 17:38 UTC
Spacebar and Copy shortcut (Command+C) just randomly stop working. Copy only works with a right-click dropdown option select. Both work fine in other running apps. I'm running into this issue on macOS Sierra. Latest version of VS Code (1.17.2) - but has happened with previous releases as well.

Read in another issue thread that a workaround for a similar issue was to shut down and restart (which works here too), but a little frustrating to have that as the only solution. With a few projects open, Integrated Terminal tasks running in my workflow, on restart - VS Code only remembers one of the projects I had open.

**Comment by Tyriar** [comment] 2017-11-01 19:28
Do cmd+c to copy doesn't work in the terminal after a selection is made? Can you share your keybindings.json and settings.json files? (in menu Code > Preferences)

**Comment by mpukit** [comment] 2017-11-01 19:58
The 'integrated-terminal' tag was added here automatically, and really didn't have much to do with it. It was actually the code editor tabs/windows themselves where some of these keyboard commands get ignored.

**Comment by alexandrudima** [comment] 2017-11-02 13:46
@mpukit This sounds like an OS-level problem. Do you have any other software installed on your machine that runs in the background and that offers functionality on `cmd+c` or `Spacebar` ? When you encounter this problem, does `cmd+c` or `Spacebar` work in other areas of our UI (like in the Search viewlet input box) ?

**Comment by mpukit** [comment] 2017-11-02 14:53
Next time it happens, I can confirm whether cmd+c or Spacebar work elsewhere in the VS Code UI - I don't think they did.

I don't know of any other background software. Both functions worked however in other open and running apps. I entered this issue in Chrome for instance, while I searched for a solution.

**Comment by alexandrudima** [comment] 2017-11-02 15:54
For example, on my mac, the `F4` key doesn't work since I have installed `Steam`. Once I launch and exit `Steam`, the `F4` key works again... Nasty stuff like this makes me believe this issue is rooted in some other application you have installed...

**Comment by mpukit** [comment] 2017-11-03 20:50
I haven't seen any behavior like this. I use VS Code pretty much all day everyday so I would have noticed if it did.

**Comment by alexandrudima** [comment] 2017-11-06 15:48
@mpukit Do you have any installed extensions?

**Comment by InventingWithMonster** [comment] 2017-11-07 10:41
I'm having this exact problem right now and I've had it multiple times over the last couple weeks.

CMD-C, CMD-V not working at all either. 

I've just restarted the app, and that fixed it. 

I'm on High Sierra, VSC 1.17.2.

**Comment by alexandrudima** [comment] 2017-11-07 11:01
@InventingWithMonster Do you have any steps ? What extensions do you have installed ?

**Comment by InventingWithMonster** [comment] 2017-11-07 11:04
No steps that I know of, it’s random (or feels it) so it’s hard to keep
track.

Extensions:
Code Spell Checker
Eslint

**Comment by alexandrudima** [comment] 2017-11-07 11:14
Here is what I could find.

https://bugs.chromium.org/p/chromium/issues/detail?id=755116#c17

> FWIW, https://discussions.apple.com/thread/7679531 seems to describe similar symptoms - copy/paste working after a restart, then failing.
> It hints at several things:
> * It's an OS issue, and when the issue manifests it affects apps seemingly at random. Chrome is one such app.
> * It can be exacerbated by clipboard helper apps that run at login, but also affects Safe Mode
> * And on the 4th page: it may be related to crashes of system processes (pboard, pbs) which may restart after a crash, but even after the processes come back other apps will need a manual restart.

**Comment by mpukit** [comment] 2017-11-07 14:30
Looks like I'm on an older OS - 10.12.6 and have no extensions enabled.

Also, to clarify - the issue resolves itself upon restarting VS Code only (not MacOS), and can't speak for @InventingWithMonster but I have not encountered this with Chrome or any other app.

**Comment by pixelwhip** [comment] 2017-11-22 00:45
I'm experiencing this on High Sierra (10.13.1) and VSCode (1.18.1).

Clicking on a different file in the sidebar then back again seems to fix it temporarily. I have not noticed a definite pattern to reproduce it though.

**Comment by alexandrudima** [comment] 2017-11-24 10:10
> Clicking on a different file in the sidebar then back again seems to fix it temporarily. I have not noticed a definite pattern to reproduce it though.

@joaomoreno just noticed the exact thing today: `space` and `enter` were not working when focus was in the editor (cursor blinking). Once focus was moved to the sidebar and back to the editor, they started to work.

We suspect there is a problem somewhere in our tree / explorer where a blur event is missing. This leaves the context keys `listFocus` and `filesExplorerFocus` to true.

The following keybindings would stop working in the editor:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/5047891/33205617-e13b61d8-d107-11e7-9ca2-567172216718.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/5047891/33205630-eb1a428c-d107-11e7-921d-a48a425aece1.png">

Since we believe this is focus related, please let us know if you have a specific pattern in which you move focus from the explorer to the editor.

**Comment by joaomoreno** [comment] 2017-11-24 14:36
@alexandrudima @bpasero bf6ff401a18faf27d0c84d9b4f7c47d8209e3642 _might_ fix this.

**Comment by bpasero** [comment] 2017-11-27 16:08
Sounds good, closing optimistically. @mpukit the change landed in insiders if you want to give it a try.  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2017-11-27 16:08 UTC
Labels: mac, needs more info
