### ISSUE TITLE
Move windows independently of vscode

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode#116204] opened 2021-02-09 15:26 UTC
I work on a laptop with an intel iGPU which has an external monitor plugged into to it, and I use both screens. 3840x1080 is not supported by the GPU on HDMI, which doesn't really bother me except for when some (all?) windows on vscode such as the Open File or About open on the middle of the screen, but **can't** be moved without moving vscode itself. So I get this
![Screenshot from 2021-02-09 12-09-05](https://user-images.githubusercontent.com/4423144/107385086-54e5fd80-6ad1-11eb-8eb1-56769b74688d.png)
And if I try to move it, this is the result
![Screenshot from 2021-02-09 12-21-02](https://user-images.githubusercontent.com/4423144/107385124-6202ec80-6ad1-11eb-8281-1e543c192d0a.png)

Could you make them able to moved independently from the main vscode window? Thanks.

**Comment by meganrogge** [comment] 2021-02-09 15:27
Duplicate of #10121

**Comment by KaeLL** [comment] 2021-02-09 15:30
I wasn't sure how to search for this, and I'm not even sure if this is the exact same issue, but Ok.

**Closed** 2021-02-09 15:31 UTC
Labels: *duplicate

**Comment by KaeLL** [comment] 2021-02-12 01:12
I'm an idi*t, lol. You can actually accomplish this by changing the `Attach modal dialogs` option on Gnome Tweaks in the Windows tab. Thanks anyways.
