### ISSUE TITLE
Cannot read property 'loadCell' of undefined

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#149308] opened 2022-05-12 00:53 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.when I open VSCode,  no reaction, and later the devtools opened;
2.the message is  [Cannot read property 'loadCell' of undefined];
3. this problems troubles me a long time, I was tired.
4. Can you tell me how to resolve it?

**Comment by gjsjohnmurray** [comment] 2022-05-12 03:20
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> * VS Code Version:
> * OS Version:

/needsMoreInfo

Also, please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by joyceerhl** [comment] 2022-08-15 22:12
Duplicate of https://github.com/microsoft/vscode/issues/154767

**Closed by joyceerhl** 2022-08-15 22:12 UTC
Labels: info-needed
