### ISSUE TITLE
automatic Update import from "XXX", Mouse style  no Text selection

### ISSUE THREAD

**Issue by topb25** [microsoft/vscode#144372] opened 2022-03-04 07:31 UTC
Issue Type: <b>Bug</b>

Mouse style problem, no Text selection 

VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 8dc449fe-050f-4a6b-b3a7-7686f55ef153 --crash-reporter-id 8dc449fe-050f-4a6b-b3a7-7686f55ef153|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
TabOut|alb|0.2.1
color-info|bie|0.7.0
better-toml|bun|0.3.2
turbo-console-log|Cha|2.1.7
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
dart-code|Dar|3.36.0
flutter|Dar|3.36.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.1
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
gitkraken-authentication|git|1.0.3
vscode-js-annotations|lan|0.11.0
sftp|lix|1.12.10
easy-less|mrc|1.7.3
vscode-docker|ms-|1.20.0
vscode-language-pack-zh-hans|MS-|1.65.1
live-server|ms-|0.2.12
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.5418
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.13.0
vscode-thunder-client|ran|1.12.2
vscode-fileutils|sle|3.5.0
svelte-vscode|sve|105.12.1
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.5
fig|wit|0.0.6
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.20

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841cf:30447410
dsvsc009:30440023
pythonvspyt640:30442238
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvidc:30447482
helix:30440343
vscaac:30438847
vsnot107cf:30443615

```

</details>

**Comment by topb25** [comment] 2022-03-04 07:36
![Untitled](https://user-images.githubusercontent.com/43520248/156719780-2a7dfc66-0ad1-4cc7-9404-efcf7c20168d.gif)


## Mouse style no Text selection

**Comment by mjbvz** [comment] 2022-03-04 21:17
Please share your theme and any theme custom settings you've added

**Comment by topb25** [comment] 2022-03-05 02:37
> Please share your theme and any theme custom settings you've added

I check my settings.json, "files.autoSave": "afterDelay" delete it , The problem disappeared

**Comment by topb25** [comment] 2022-03-05 02:38
> Please share your theme and any theme custom settings you've added

这是我的settings.json 

```json
{
  "files.autoSave": "afterDelay",
  "editor.cursorWidth": 4,
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "editor.suggest.preview": true,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  "workbench.colorCustomizations": {
    "editorCursor.foreground": "#43ff1d"
  },
  "editor.tokenColorCustomizations": {
    "[CodeSandbox Black]": {},
    "textMateRules": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "comment.block",
          "comment.block.documentation",
          "comment.line",
          "comment.line.double-slash",
          "punctuation.definition.comment"
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  },
  "todohighlight.isEnable": true,
  "jsannotations.enabled": false,
  "explorer.confirmDragAndDrop": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "javascript.suggest.completeFunctionCalls": true,
  "typescript.suggest.completeFunctionCalls": true,
  "explorer.confirmDelete": false,
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell",
      "args": [
        "-NoLogo"
      ]
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash"
    }
  },
  "powershell.powerShellDefaultVersion": "Windows PowerShell (x86)",
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "git.confirmSync": false,
  "editor.fontLigatures": true,
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.cursorStyle": "line",
  "editor.snippetSuggestions": "top",
  "files.exclude": {
    ".hbuilderx": true,
    ".vscode": true,
    "**/.history": true,
    "**/.idea": true,
    "**/.tea": true,
    "**/.umi": true,
    "**/.vscode": true
  },
  "editor.fontFamily": "MonoLisa, JetBrains Mono, Fira Code, Consolas, monospace",
  "files.associations": {
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript",
    "*.ttss": "css",
    "*.json": "jsonc",
    "*.nvue": "vue"
  },
  "emmet.includeLanguages": {
    "wxml": "html",
    "ttml": "html"
  },
  "emmet.optimizeStylesheetParsing": false,
  "emmet.triggerExpansionOnTab": true,
  "emmet.showSuggestionsAsSnippets": true,
  "editor.tabSize": 2,
  "task.slowProviderWarning": [
    "npm"
  ],
  "editor.cursorBlinking": "expand",
  "editor.cursorSmoothCaretAnimation": true,
  "editor.smoothScrolling": true,
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "search.exclude": {
    "**/.git": true,
    "**/.history": true,
    "**/.tea": true,
    "node_modules": true,
    "dist/": true
  },
  "window.autoDetectHighContrast": false,
  "editor.fastScrollSensitivity": 6,
  "workbench.list.smoothScrolling": true,
  "files.eol": "\r\n",
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.currentLine.scrollable": false,
  "gitlens.views.repositories.branches.layout": "list",
  "gitlens.advanced.messages": {},
  "gitlens.blame.ignoreWhitespace": true,
  "gitlens.hovers.enabled": false,
  "git.showPushSuccessNotification": true,
  "vim.easymotion": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "j"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "bookmarks.useWorkaroundForFormatters": true,
  "prettier.arrowParens": "avoid",
  "prettier.jsxBracketSameLine": true,
  "prettier.printWidth": 100,
  "scm.alwaysShowRepositories": true,
  "editor.linkedEditing": true,
  "prettier.jsxSingleQuote": true,
  "editor.formatOnSaveMode": "modifications",
  "editor.fontSize": 15,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "rust-client.rustupPath": "C:\\Users\\b5237\\.cargo\\binrustup",
  "debug.console.fontSize": 15,
  "terminal.integrated.fontSize": 15,
  "prettier.trailingComma": "none",
  "todohighlight.defaultStyle": {
    "borderRadius": "5px",
    "color": "red",
    "backgroundColor": "rgba(0,0,0,.2)"
  },
  "todohighlight.keywords": [
    "DEBUG:",
    "REVIEW:",
    {
      "text": "TODO:",
      "color": "yellow",
      "border": "1px solid yellow",
      "backgroundColor": "rgba(0,0,0,.0)",
      "borderRadius": "5px"
    },
    {
      "text": "NOTE:",
      "color": "#ffffff",
      "border": "1px solid #3498db",
      "borderRadius": "5px",
      "backgroundColor": "rgba(0,0,0,.0)"
    }
  ],
  "path-intellisense.mappings": {
    "@": "${workspaceRoot}/src"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.rulers": [
      80
    ],
    "editor.selectionHighlight": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.suggestSelection": "first",
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": false
  },
  "liveServer.settings.donotVerifyTags": true,
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
  },
  "editor.lineHeight": 28,
  "code-runner.showRunCommandInExplorerContextMenu": false,
  "code-runner.showRunIconInEditorTitleMenu": false,
  "less.compile": {
    "compress": true,
    "out": false
  },
  "editor.renderWhitespace": "none",
  "workbench.iconTheme": "material-icon-theme",
  "thunder-client.codeSnippetLanguage": "js-axios",
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "settingsSync.ignoredExtensions": [
    "ms-vscode.powershell"
  ],
  "material-icon-theme.hidesExplorerArrows": false,
  "tabnine.experimentalAutoImports": true,
  "eslint.alwaysShowStatus": true,
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1"
  },
  "editor.accessibilitySupport": "off",
  "security.workspace.trust.untrustedFiles": "open",
  "liveshare.presence": true,
  "diffEditor.renderSideBySide": false,
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "svelte.enable-ts-plugin": true,
  "terminal.integrated.defaultProfile.osx": "zsh",
  "breadcrumbs.symbolPath": "off",
  "breadcrumbs.enabled": false,
  "editor.lineNumbers": "on",
  "editor.gotoLocation.multipleDefinitions": "goto",
  "workbench.colorTheme": "CodeSandbox Black",
  "editor.renderLineHighlight": "all",
  "editor.unicodeHighlight.allowedLocales": {
    "zh-hant": true
  },
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "gitlens.statusBar.enabled": false,
  "gitlens.codeLens.enabled": false
}
```

**Comment by mjbvz** [comment] 2022-03-08 01:10
I'm closing this since it sounds like it's been resolved

@topb25 If you're still seeing this, please share minimal steps to reproduce this (such as only the relevant settings that cause the problem)

**Closed by mjbvz** 2022-03-08 01:10 UTC
Labels: needs more info
