### ISSUE TITLE
emmet.useNewEmmet lead to wrong order of the suggestion list

### ISSUE THREAD

**Issue by zyy7259** [Microsoft/vscode#29161] opened 2017-06-21 05:51 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|beautify|HookyQR|1.1.1|
|prettier-eslint-vscode|RobinMalfait|0.7.1|
|code-settings-sync|Shan|2.8.1|
|jsx|TwentyChung|0.0.1|
|project-manager|alefragnani|0.18.1|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|theme-dracula|dracula-theme|2.1.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.3|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|3.1.4|
|color-highlight|naumovs|2.2.0|
|vetur|octref|0.7.0|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.9.0|
|stylelint|shinnn|0.25.0|
|vscode-react-native|vsmobile|0.3.2|
|gitblame|waderyan|1.11.3|
|local-history|xyz|1.2.1|
|Material-theme|zhuangtongfa|2.8.8|;

---

Steps to Reproduce:

1.set `emmet.useNewEmmet` to false
2.open a css file
3.type `padd`, and the following image show the right suggestion list.

<img width="783" alt="screen shot 2017-06-21 at 1 48 39 pm" src="https://user-images.githubusercontent.com/2311742/27369011-649f4350-5688-11e7-8ba6-2bd8d816faa3.png">

4.set `emmet.useNewEmmet` to true
5.open a css file
6.type `padd`, as the following image shown, the first item in the suggestion list is `Expand Emmet Abbreviation`, which is not suitable.

![image](https://user-images.githubusercontent.com/2311742/27368940-f515f132-5687-11e7-8bd1-eab4e5e0509e.png)

**Comment by ramya-rao-a** [comment] 2017-06-21 16:07
This is related to #28933 
The root cause is that the emmet css abbreviation module tries to match given text with closest matching abbreviation which in times like these misses the closest matching snippet.

Closing in favor of @28933

**Closed by ramya-rao-a** 2017-06-21 16:07 UTC
Labels: new release
