### ISSUE TITLE
JS/TS hover type info syntax highlighting breaks in imported functions

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#120894] opened 2021-04-09 05:48 UTC
VS 1.55.1 latest

```js
// foo.js
export function foo(arg) {}
```
```js
// bar.js
import { foo } from "./foo";
foo();
```
Baseline
<img width="599" alt="Code_2021-04-09_07-36-12" src="https://user-images.githubusercontent.com/30108880/114133834-f9849000-9906-11eb-9440-278c11ad4747.png">

Expected
<img width="360" alt="Code_2021-04-09_07-36-21" src="https://user-images.githubusercontent.com/30108880/114133721-c6da9780-9906-11eb-83f2-8c9e2adbd56c.png">

Actual
<img width="360" alt="Code_2021-04-09_07-36-20" src="https://user-images.githubusercontent.com/30108880/114133715-c3dfa700-9906-11eb-8709-2b2dd886f024.png">

**Comment by mjbvz** [comment] 2021-04-12 21:43
Duplicate of #93762

**Closed by mjbvz** 2021-04-12 21:43 UTC
