### ISSUE TITLE
cannot execute any command when Chinese UI is used

### ISSUE THREAD

**Issue by localvar** [Microsoft/vscode#5290] opened 2016-04-15 01:07 UTC
- VSCode Version: 1.0
- OS Version: Windows 10

All commands are in Chinese when using Chinese UI, when I type something like "ext install", it says "没有匹配的命令(no matched command)" and don't allow me to run the command.

BTW: how to switch to English UI?

Steps to Reproduce:

1. 
2.

**Comment by Treri** [comment] 2016-04-15 01:30
All commands should not be translated to locale specific commands.

## And they should only be **English**

**Comment by chanzig** [comment] 2016-04-15 02:41
[language support and change](https://code.visualstudio.com/docs/customization/locales)
 
surely the commands should not be translated !  OK, why not translated the Keyboard ShortCurts desc..

**Comment by hax** [comment] 2016-04-15 02:59
duplicate #4679 ?

**Comment by egamma** [comment] 2016-04-15 07:00
Duplicate of #4679

**Closed by egamma** 2016-04-15 07:00 UTC
