### ISSUE TITLE
cant update. Setup files corrupted

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/vscode#873] opened 2015-12-01 16:49 UTC
Code says there is an update.  when I click  update I get an error dialog saying "The setup files are corrupted.  Please obtain a new copy of the program"  What does that mean in practice? 

The net result is that I am unable to update VS Code.  

I'll uninstall and reinstall to see if that helps.

**Comment by joaomoreno** [comment] 2015-12-02 07:59
Duplicate of #780

**Closed by joaomoreno** 2015-12-02 07:59 UTC
Labels: bug
