### ISSUE TITLE
拖项目文件夹到visual studio code 编辑器没反应

### ISSUE THREAD

**Issue by xixiayipingtang9557** [Microsoft/vscode#32914] opened 2017-08-22 01:17 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.9.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by CnSimonChan** [comment] 2017-08-22 01:41
Translation:

> # Nothing happens when drag and drop a folder to Code

Duplicate of #32537

Code 为了防止 `打开文件夹` 和 `把文件夹复制到此` 的歧义，禁止了拖动文件夹。

**Closed** 2017-08-22 19:54 UTC
Labels: new release
