### ISSUE TITLE
Commit All (Amend) asks if it should stage changes

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35186] opened 2017-09-26 22:20 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34963

Steps to Reproduce:

1. Have some unstaged changes, none staged
2. Commit All (Amend)
3. 🐛 A dialog asks me if I want to stage changes.

**Comment by pradeepmurugesan** [comment] 2017-09-29 13:54
@joaomoreno so whats the expected behaviour? Should skip the dialog and commit (amend) directly ?

**Comment by chrmarti** [comment] 2017-09-29 14:03
That is what I expected. Since I already chose to commit *all* changes I did not expect a dialog asking me the same question.

**Comment by samir-majhi** [comment] 2017-09-30 11:54
@chmarti This looks like it was intentionally kept there as a reminder so that you'd stage it first before you'd commit.

**Comment by chmarti** [comment] 2017-09-30 15:25
You're looking for @chrmarti. I'm not the right person.

**Comment by samir-majhi** [comment] 2017-10-01 20:06
Sorry. I meant @chrmarti

**Comment by dKab** [comment] 2017-10-06 10:52
so, @joaomoreno, what would be a correct behavior here? Is this issue valid and there shouldn't be a confirmation popup?

**Comment by joaomoreno** [comment] 2017-10-09 07:33
Changes should be staged and then committed.

**Comment by pradeepmurugesan** [comment] 2017-10-09 09:14
@joaomoreno so we can ignore the pop up alerting the user ?

**Comment by pradeepmurugesan** [comment] 2017-10-09 09:47
@joaomoreno  I could see that the pop up is ignored from next time when the user selects "always", Which is also available as a config option (enableSmartCommit).

I would like to keep the dialog as its just the first time and the user has an option to say "always" and override the behaviour

**Comment by joaomoreno** [comment] 2017-10-09 11:51
@pradeepmurugesan That makes sense.

**Comment by roblourens** [comment] 2017-11-27 18:25
This seems fixed

**Closed by roblourens** 2017-11-27 18:25 UTC
Labels: bug, git, good first issue, help wanted
