### ISSUE TITLE
Problem view padding is inconsistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69382] opened 2019-02-25 17:22 UTC
#69204

The top and bottom padding is inconsistent.

![image](https://user-images.githubusercontent.com/2193314/53355782-a85be280-38de-11e9-89b7-4460b66b70e6.png)

Looks like it's related to "invisible" items inside the body:

![image](https://user-images.githubusercontent.com/2193314/53355845-d5a89080-38de-11e9-8527-29626245bac9.png)

Version: 1.32.0-insider (user setup)
Commit: 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

**Comment by Tyriar** [comment] 2019-02-25 21:41
Also part of this, the scrollbar is hidden:

![image](https://user-images.githubusercontent.com/2193314/53370584-f2ef5600-3902-11e9-9d4f-87941cc14f56.png)

**Comment by sandy081** [comment] 2019-02-25 23:20
Fixed the scroll bar and focus issues. But it is hard to have consistent padding because it involves computing height using number of lines. Actually this looks same also before and the difference in padding is not so much to consider.

**Comment by Tyriar** [comment] 2019-02-26 01:07
@sandy081 I beg to differ with the difference in padding, it makes it look sloppy to me. If we can only show the padding if the scroll bar is needed that would be best like in https://github.com/Microsoft/vscode/issues/69391

**Comment by sandy081** [comment] 2019-02-26 08:30
@Tyriar This is how it looks with and without a link. Not sure if it is sloppy.

![image](https://user-images.githubusercontent.com/10746682/53398083-0ead3780-39a9-11e9-8d40-6e0243ff06ed.png)

![image](https://user-images.githubusercontent.com/10746682/53398121-21277100-39a9-11e9-9eb6-13a4acc9a63b.png)

**Comment by Tyriar** [comment] 2019-02-26 22:31
@sandy081 the bottom padding of the contain should match the top padding of the container, just like in the second screenshot?

**Comment by roblourens** [comment] 2019-02-27 01:46
I'm guessing this should be reopened?

I also spun another issue off this: https://github.com/Microsoft/vscode/issues/69495

**Comment by sandy081** [comment] 2019-02-27 08:07
Since this is not a regression, moving this to March

**Comment by sandy081** [comment] 2019-03-20 14:03
Sorry @Tyriar. Looked into it again to make the padding symmetric. But I am sorry to say this need bigger changes to peek widget which I am not willing to do for the value it gives. Moreover it is like this from beginning. Hence closing this as wont fix.

**Closed by sandy081** 2019-03-20 14:03 UTC
Labels: bug, editor-error-widget, polish
