### ISSUE TITLE
git.inputValidationSubjectLength does nothing anymore

### ISSUE THREAD

**Issue by groengpx** [microsoft/vscode#200619] opened 2023-12-12 10:26 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Write a commit message in the source control panel, with a subject that is longer than git.inputValidationSubjectLength.
2. A yellow warning should show up beneath the input field, as it always have been, but it doesn't.
3. Try to actually commit it: also no warning given.

**Comment by GevaOr** [comment] 2023-12-12 10:50
As mentioned in [this comment](https://github.com/microsoft/vscode/issues/200419#issuecomment-1848212180) (originally [here](https://github.com/microsoft/vscode/issues/185606#issuecomment-1840655597)), this setting is now off by default.
I was also having a hard time finding this setting, but eventually found it in Settings -> Extenstions -> Git -> Git: Input Validation (you can change it to `warn`).

**Comment by lszomoru** [comment] 2023-12-12 12:33
Closing as duplicate of https://github.com/microsoft/vscode/issues/200419

**Closed by lszomoru** 2023-12-12 12:32 UTC
