### ISSUE TITLE
Ordering of items in command palette is not as expected

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#19757] opened 2017-02-02 23:05 UTC
Somewhat of a more minor UX issue, but ...

- VSCode Version: 1.9.0
- OS Version: macOS 12.10.3

Steps to Reproduce:

1. Cmd+Shift+P
2. Type 'Install'

Expected result: Offers to install extensions
Actual result: First hit is 'Disable all installed extensions', the exact opposite

**Comment by bpasero** [comment] 2017-02-03 06:42
Lets mark this as duplicate of https://github.com/Microsoft/vscode/issues/14727

**Closed by bpasero** 2017-02-03 06:42 UTC
