### ISSUE TITLE
IntelliSense pop-up doesn't react to font size changes while showing

### ISSUE THREAD

**Issue by phamquocduy** [microsoft/vscode#98310] opened 2020-05-21 10:11 UTC
- VSCode Version: 1.45.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Show IntelliSense pop-up using Ctrl + Space
2. Ctrl + scroll up to extend zoom lvl

*I have 4k display

<img width="1920" alt="bigger-zoom" src="https://user-images.githubusercontent.com/19596268/82548801-319eab00-9b5c-11ea-8786-5890e1e042a8.png">
<img width="1920" alt="bigger-zoom-2" src="https://user-images.githubusercontent.com/19596268/82548803-32cfd800-9b5c-11ea-9307-35a5225c367b.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment] 2020-10-30 14:40
The problem is that there is also suggest line height and that doesn't default to the editor line height but to a static value

**Comment by jrieken** [comment] 2020-11-02 13:36
Bug is acknowledge but I am closing as wont-fix because the font/line height change needs to be propagated all they to the list. For that all items to be to added/removed etc. I think it's not worth the effort given that this issue only occurs an in corner case

**Closed by jrieken** 2020-11-02 13:36 UTC
Labels: bug, suggest, ux, wont-fix
