### ISSUE TITLE
Emmet toggle comment does not consider the position at the end of the selection

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27629] opened 2017-05-30 19:57 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

![image](https://cloud.githubusercontent.com/assets/2193314/26602122/48f2a186-4537-11e7-9e19-763824138f1c.png)

Toggle comment:

![image](https://cloud.githubusercontent.com/assets/2193314/26602148/59789e48-4537-11e7-8e32-ab39c676cde3.png)

I would expect either:

- the selection end cursor position (the top one), not the start cursor as the end cursor is generally considers the master cursor (I think), or
- all rules in the selection are commented

**Comment by ramya-rao-a** [comment] 2017-05-31 02:00
Similar thing happens in html as well.

Root cause: Only the start of the selection is taken to determine which nodes should be commented.

**Comment by ramya-rao-a** [comment] 2017-06-01 23:18
Removed the toggleComment feature from new emmet as it needs more work
https://github.com/Microsoft/vscode/commit/d80d55063470aa31f7fe14e856cb56e26656c5b8

**Comment by ramya-rao-a** [comment] 2017-06-07 02:19
Fixed in both html and css files.

**Closed by ramya-rao-a** 2017-06-07 02:19 UTC
Labels: bug, emmet
