### ISSUE TITLE
Cannot split a terminal without a group

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#207200] opened 2024-03-08 21:12 UTC
- Work in the vscode-copilot repo for awhile
- Run the default build task
- It doesn't run, I just get this error

It worked after I reloaded the window, thought the stack might be useful. This was Insiders 6c19c003574b02afc604c0c1c471b1441b33a3d3 for deminification

```
2024-03-08 16:02:19.138 [error] Cannot split a terminal without a group [object Object]: Error: Cannot split a terminal without a group [object Object]
    at ae.Qb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2902:36622)
    at ae.createTerminal (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2902:35337)
    at async N.Cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1599:16730)
    at async N.Fb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1599:19468)
    at async N.xb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1599:8411)
```

**Comment by meganrogge** [comment] 2024-12-10 16:28
I cannot reproduce, so closing

**Closed by meganrogge** 2024-12-10 16:28 UTC
Labels: bug, terminal-tabs
