### ISSUE TITLE
Very wide "No suggestions" intellisense can still occur

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27619] opened 2017-05-30 18:47 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

![image](https://cloud.githubusercontent.com/assets/2193314/26599468/869848d8-452d-11e7-916e-c93be4d01bf0.png)

Steps to reproduce:

1. Use `emmet.useModules` = true
2. Type `#foo{3}`
3. Press ctrl+space twice

![image](https://cloud.githubusercontent.com/assets/2193314/26599508/aabdf7a8-452d-11e7-8b10-7f2e8f5cc69e.png)

**Comment by ramya-rao-a** [comment] 2017-06-01 04:30
Duplicate of #27673

**Closed by ramya-rao-a** 2017-06-01 04:30 UTC
Labels: bug
