### ISSUE TITLE
Button to re-evaluate mentioned Problems

### ISSUE THREAD

**Issue by Vasista-Eranki** [microsoft/vscode#98237] opened 2020-05-20 11:24 UTC
Issue Type: <b>Feature Request</b>

Team

I'd like to suggest to add a button in the Problems tab to re-evaluate the selected problem(s). I face issue with problems not retting removed though I've resolved them. An explicit re-evauate button shall help here.

Also add a switch to report problems to only modified files (when connected to any source ctrl. repos).

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kieferrm** [comment] 2020-05-22 00:15
In principle, the problem is with the language extension you're using. Do you have a concrete use case? @sandy081 for considering a "clear problems" panel button.

**Comment by Vasista-Eranki** [comment] 2020-05-22 03:55
We're using PSScriptAnalyzer in Powershell and configured it in vs code settings file:
`Install-Module -Name PSScriptAnalyzer`

**Comment by sandy081** [comment] 2020-05-27 13:05
Please file the issue against the extension that is not updating the problems. Re clear problems, there is already a feature request for it. Hence closing this.

**Closed by sandy081** 2020-05-27 13:05 UTC
