### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by Azarchaniel** [microsoft/vscode#105563] opened 2020-08-28 07:30 UTC
Issue Type: <b>Bug</b>

I wasn't doing anything special, just fixing imports after refactoring. It was yesterday and since then I cannot make VS Code works properly. I tried turn off extensions, reinstall VSCode, downgrade, change TypeScript version. Nothing worked. I cannot work without IntelliSense!

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.8
es7-react-js-snippets|dsz|2.8.3
beautify|Hoo|1.5.0
intellij-idea-keybindings|k--|0.2.41
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-graphql|Pri|0.3.1
reopenclosedtab|uyi|1.1.0

</details>

**Comment by Azarchaniel** [comment] 2020-08-28 07:39
Reload with disabled extensions helped with it.

**Comment by mjbvz** [comment] 2020-08-28 18:42
Closing this as caused by an extension then. The most likely cause is the angular templates extension since I believe it extends the TypeScript server

**Closed by mjbvz** 2020-08-28 18:42 UTC
Labels: new release
