### ISSUE TITLE
Insiders 'File' and 'Help' is missing in nightly build

### ISSUE THREAD

**Issue by jsacapdev** [Microsoft/vscode#55633] opened 2018-08-02 08:14 UTC
- VSCode Version: Cant tell you because the help option is missing (see below)
- OS Version: Cant tell you because the help option is missing (see below)

Steps to Reproduce:

1. Open VSCode

![image](https://user-images.githubusercontent.com/10151920/43571236-5bd7296c-9634-11e8-900b-8663022e73cd.png)

One that works

![image](https://user-images.githubusercontent.com/10151920/43571269-73281f2c-9634-11e8-968a-7c7aede481fd.png)

**Comment by mjbvz** [comment] 2018-08-02 09:02
Duplicate of #55624

**Closed by mjbvz** 2018-08-02 09:02 UTC
