### ISSUE TITLE
Navigator automatically lose focus on edit file name/new file/new folder

### ISSUE THREAD

**Issue by maoueh** [microsoft/vscode#137332] opened 2021-11-16 22:07 UTC
Issue Type: <b>Bug</b>

As soon as I try to do any of those actions:
- Select folder in navigator, press enter to edit the filname
- Create a new file from the navigator icon
- Create a new folder from the navigator icon

The input is display briefly before lossing focus almost immediately preventing me from entering any information. 

Sometimes worst, you quickly press enter then type some stuff, when the focus is lost, keys become shortcuts to VSCode and starts doing weird stuff. I have deleted files by mistake, move stuff around, jump elsewhere in the navigator due to that.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:59:05.913Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 12, 14|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|. --crash-reporter-id 19a78635-9194-4fe2-9bb8-1ab6f3e09626|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-database|baj|2.2.3
better-toml|bun|0.3.2
rerun-last-command|Cam|0.0.1
solargraph|cas|0.23.0
wrap-with-template-string|cde|0.0.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
copywithline|dii|0.0.2
dmlog|N/A|0.0.1
vscode-generate-getter-setter|DSK|0.5.0
vscode-wasm|dts|1.3.1
gitlens|eam|11.6.1
tslint|eg2|1.0.47
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.0.0
php-intellisense|fel|2.3.14
flow-for-vscode|flo|1.9.2
vscode-pull-request-github|Git|0.32.0
go|gol|0.29.0
gc-excelviewer|Gra|3.0.44
vscode-graphql|Gra|0.3.18
terraform|has|2.16.0
jsonnet|hep|0.1.0
vscode-styled-components|jpo|1.6.6
solidity|Jua|0.0.136
php-cs-fixer|jun|0.2.8
graphql-for-vscode|kum|1.15.3
macrosRe|l7s|1.3.0
rust-analyzer|mat|0.2.817
dotenv|mik|1.0.1
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.18.0
vscode-kubernetes-tools|ms-|1.3.4
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.1
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.205.2
cmake-tools|ms-|1.9.1
cpptools|ms-|1.7.1
hexeditor|ms-|1.8.2
vscode-react-native|msj|1.8.0
color-highlight|nau|2.5.0
vscode-jest|Ort|4.2.1
ejs-language-support|Qas|0.0.1
ruby|reb|0.28.1
java|red|1.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.0
shellman|Rem|5.6.0
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.3
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
remove-empty-lines|use|0.0.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1
vscode-icons|vsc|11.7.0
HCL|who|0.0.5
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by maoueh** [comment] 2021-11-16 22:17
https://user-images.githubusercontent.com/123014/142075039-7cd73365-9d19-44ea-b6cc-3a3f09e7d788.mp4

This is with extensions disabled. Tried with the Insiders version, same results.

**Comment by JacksonKearl** [comment] 2021-12-02 02:28
Are there any ongoing processes that may be editing the working directory? Such as build scripts or that sort of thing.

**Comment by maoueh** [comment] 2021-12-02 15:40
@JacksonKearl Let me check that.

I'm running in some occasions a `yarn start` process for React app and also `reflex` a tracking tool that re-launch Golang build and run a web server (I run `reflex -r "\.go$" -s -- sh -c 'DEBUG=true go run ./cmd/solgun program serve').

I'll test by eliminating all useless running processes.

**Comment by maoueh** [comment] 2021-12-02 16:59
@JacksonKearl Just tested, seems it could be a side process causing the problem, right now I'm running no long living process and it seems to work properly.

Going to start those one by one and see when it starts to be a problem.

**Comment by maoueh** [comment] 2021-12-02 18:26
Ok I've isolated the external process that does this on my case. It's `solana-test-validator` a tool that launches a local Solana blockchain instance.

When I start that at the root of my VSCode workspace, the problem arrives recursively on any folder. 

If I start the said tool on a subfolder directly, like `devel` sub-folder, then the problem in VSCode is localized in this specific folder (and its children).

Now, this tool specifically, not sure why it would change attributes of "all" files/folders in the project. It's acting normally only under a sub-folder called `test-ledger` so I would assume it would only changes stuff in this sub-folder.

Does it change maybe something on the root workspace folder which triggers the bug in VSCode everywhere, unclear.

The tool can run standalone and can be installed with those steps: https://docs.solana.com/cli/install-solana-cli-tools. I imagine you should be able to reproduce with it, it does not require anything, you can just run it.

**Comment by JacksonKearl** [comment] 2021-12-03 20:06
Thanks for helping to diagnose this, I believe this is a duplicate of #112293, which I plan to tackle next month. Basic plan is to pause all explorer updating while the new item edit menu is shown.

**Closed by JacksonKearl** 2021-12-03 20:06 UTC
Labels: needs more info

**Comment by maoueh** [comment] 2021-12-06 18:24
Thanks, going to track the progress there!
