### ISSUE TITLE
"Go to File" with line number doesn't respect line number any more

### ISSUE THREAD

**Issue by Boddlnagg** [microsoft/vscode#128518] opened 2021-07-13 06:34 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0 (update: also in 1.58.1)
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open "Go to File" (Ctrl+P)
2. Enter a filename followed by colon and line number

I expect that the file opens and the cursor jumps to the specified line (which used to work in the previous release), but it seems to be broken in 1.58.0. The file opens, but the cursor remains where it had been before (or where it remembered that the cursor was placed the last time the file was open).

**Comment by RikkiGibson** [comment] 2021-07-21 00:16
I'm currently working around the issue by using "Go to File", pasting in my destination, then once I'm in the right file, running the command again with the same input to jump to the line number I want.

**Comment by viperet** [comment] 2021-07-21 11:35
I can confirm this issue in 1.58.2, Go to file with a line number doesn't work properly,
but if you will enter the same file name with line number second time - it will jump to the correct line.

**Comment by TylerLeonhardt** [comment] 2021-07-21 15:42
Hmm I can't seem to repro this. Here's my recording:
![ctrlp](https://user-images.githubusercontent.com/2644648/126517636-31bfa28e-e7f9-4f07-9dfb-31db56a6779e.gif)

In the gif I:
* open ctrl+p
* type `package.json:57`
* Enter

which takes me to line 57 in the package.json.

Couple questions:

@RikkiGibson and @viperet are also on Windows like @Boddlnagg?

Can you all send me a gif or recording of the repro so I can see exactly what you're doing?

**Comment by IllusionMH** [comment] 2021-07-21 16:19
I wonder if it was fixed in Insiders build on Windows.
I can reproduce it in zip installation of 1.58.2, but wasn't able to do it in Insiders build.

https://user-images.githubusercontent.com/1312662/126523183-c2b82d29-6374-498c-8585-1efd91375ee2.mp4

As you can see - when file opened for first time - cursor is placed to 1:1, however if same path:line:col are used again - it's placed to proper¹ position.

¹ I guess that cursor was shifted because of tabs vs spaces calsulations.

**Comment by TylerLeonhardt** [comment] 2021-07-21 16:23
> I can reproduce it in zip installation of 1.58.2, but wasn't able to do it in Insiders build.

This is a good sign! Can I get a few others to try Insiders and give it a test?

**Comment by viperet** [comment] 2021-07-21 16:35
@TylerLeonhardt I'm on Mac, will try Insiders build today to see if I can reproduce bug there.

**Comment by TylerLeonhardt** [comment] 2021-07-21 16:55
Glad to hear! I'll go ahead and close this then since it's fixed in insiders.

**Closed by TylerLeonhardt** 2021-07-21 16:55 UTC
