### ISSUE TITLE
Slow Restart?

### ISSUE THREAD

**Issue by 17xande** [Microsoft/vscode#26964] opened 2017-05-19 19:45 UTC
VS Code asked me to submit this issue with these files because of a slow restart :)

[a772_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1015380/a772_main.cpuprofile.txt)
[a772_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1015381/a772_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:07:58.056Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)</code>
- Memory (System): <code>8.00GB (1.53GB free)</code>
- Memory (Process): <code>226.55MB working set (0.00MB peak, 167.24MB private, 92.07MB shared)</code>
- Load (avg): <code>3, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|213|
|main|app.isReady => window.loadUrl()|103|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|426|
|renderer|require(workbench.main.js)|551|
|renderer|-> of which require() node_modules|119|
|renderer|create extension host => extensions onReady()|380|
|renderer|restore viewlet|0|
|renderer|restore editor view state|397|
|renderer|overall workbench load|531|
|main + renderer|start => extensions ready|2756|
|main + renderer|start => workbench ready|2900|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/alexandre/a772_main.cpuprofile.txt`
-`/Users/alexandre/a772_renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2017-06-09 10:40
Thanks. Things seem proper except for loading extensions. Closing as dupe of https://github.com/Microsoft/vscode/issues/28331

**Closed by jrieken** 2017-06-09 10:40 UTC
Labels: perf-profile
