### ISSUE TITLE
Creating a floating window from a terminal

### ISSUE THREAD

**Issue by Jamu2800** [microsoft/vscode#210237] opened 2024-04-12 13:34 UTC
I wanted to make the terminal a floating window.
However, this operation requires that the terminal be displayed once as a tab and then dragged off-screen, as shown in the video below.
I want to display a floating window by dragging it off-screen directly from the terminal.

https://github.com/microsoft/vscode/assets/74401057/0759dbd2-7110-480d-af91-d62dd1a17f89

I have read the source code myself, but have no idea what is going on, so please help.
Thanks for reading!
I'm using a translation tool, so sorry if there's any weird wording.

**Comment by ArturoDent** [comment] 2024-04-14 20:47
Probably a duplicate of https://github.com/microsoft/vscode/issues/193267.

**Comment by Jamu2800** [comment] 2024-04-14 22:54
> For dragging: probably a duplicate of https://github.com/microsoft/vscode/issues/193267.
> 
> And related: https://github.com/microsoft/vscode/issues/34442
> 
> But see https://stackoverflow.com/a/68273093/836330 there is a command:
> 
> // Move Terminal into New Window
> workbench.action.terminal.moveIntoNewWindow
> 
> as of v1.86.

So there was already an issue. 
Thank you for letting me know!!

**Closed** 2024-07-25 00:55 UTC
Labels: feature-request, terminal-tabs
