### ISSUE TITLE
扩展详情页会挡住状态栏

### ISSUE THREAD

**Issue by kickpoint** [microsoft/vscode#87673] opened 2019-12-25 01:26 UTC
详细信息如图所示
![图片](https://user-images.githubusercontent.com/26628173/71427958-754dcf80-26f8-11ea-84ac-f1fadd48477d.png)

**Comment by yume-chan** [comment] 2019-12-25 06:40
Duplicate of #83209

**Closed** 2019-12-26 22:00 UTC
Labels: *duplicate
