### ISSUE TITLE
Error "Unable to open 'workspaceTrustEditor':" when clicking on Manage in Restricted Mode notification

### ISSUE THREAD

**Issue by nerzhulart** [microsoft/vscode#126692] opened 2021-06-18 15:33 UTC
Issue Type: <b>Bug</b>

Open VSCode
Restricted Mode blue notification appeared
Click on Manage hyperlink

Full error message:
Unable to open 'workspaceTrustEditor': Unable to resolve resource vscode-workspace-trust:workspaceTrustEditor.

Reinstalling VSCode doesn't help

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (18.45GB free)|
|Process Argv|--crash-reporter-id 41c965e2-e445-40cd-ab15-6845975b6c90|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehovct:30309550
vscod805cf:30301675
binariesv615cf:30321889

```

</details>

![image](https://user-images.githubusercontent.com/623624/122587511-9467bc00-d066-11eb-909e-a48d6195aec6.png)

**Comment by lszomoru** [comment] 2021-06-21 13:07
@nerzhulart, I have tried to reproduce this issue without much luck so I was wondering if these is any further information that you could provide that could help me track down the root cause of this bug. Could you please answer the following questions:
1. Have you modified any of the workspace trust settings?
2. When you say "Open VSCode", are you opening a folder/workspace, or a loose file?
3. Are you able to reproduce this issue every time you open VS Code?

**Comment by nerzhulart** [comment] 2021-06-21 14:56
@lszomoru Hi! Thanks for the answer!
1. I didn't make any changes inside "workspace trust" (I even don't know where they're located)
2. I open a single file (several log files actually)
3. Yep. It shows an error to me every time I open VSCode.

**Comment by lszomoru** [comment] 2021-06-21 15:13
@nerzhulart, thanks for getting back to me. Are you opening these files using the CLI (ex: `code file1 file2 file3`) or are you starting VSCode and them opening the files using the File -> Open menu?

**Comment by nerzhulart** [comment] 2021-06-21 20:58
> @nerzhulart, thanks for getting back to me. Are you opening these files using the CLI (ex: `code file1 file2 file3`) or are you starting VSCode and them opening the files using the File -> Open menu?

I open them using Windows Shell associations (so I guess it works the same way if to open with command line)

**Comment by sbatten** [comment] 2021-06-21 21:17
@nerzhulart can you try opening code with (note the username to replace)
` code --user-data-dir C:\Users\<user>\Desktop\user1 --extensions-dir C:\Users\<user>\Desktop\ext1` and see if the issue repros?

**Comment by lramos15** [comment] 2021-06-22 02:14
Looks a lot like https://github.com/microsoft/vscode/issues/124386 which should be fixed in insiders.

**Comment by nerzhulart** [comment] 2021-06-22 12:56
> @nerzhulart can you try opening code with (note the username to replace)
> ` code --user-data-dir C:\Users\<user>\Desktop\user1 --extensions-dir C:\Users\<user>\Desktop\ext1` and see if the issue repros?

Seems it helped! The action Manage Workspace trust works now. So AIU I need to clean my VSCode profile folder, right?

**Comment by lramos15** [comment] 2021-06-22 13:08
@nerzhulart my guess is you have something like `{'*': 'default'}` in your settings.json and that's the issue. If you remove that everything should be fixed.

**Comment by Stirfry70** [comment] 2021-06-22 13:33
@lszomoru I

**Comment by lszomoru** [comment] 2021-06-23 08:53
Closing this as duplicate of #124386.

**Closed by lszomoru** 2021-06-23 08:53 UTC
Labels: bug, needs more info, workspace-trust
