### ISSUE TITLE
CoffeeScript syntax highlighting break when / is used without spaces

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/vscode#18707] opened 2017-01-18 09:03 UTC
- VSCode Version: 1.9.0-insider 
- OS Version: Mac OS 10.12.2 (16C67)

Steps to Reproduce:

1. Create coffeescript file 
2. Use `/` somewhere in the code withouth spaces around it.
3. Add more code below it, the syntax will not be detected
4. Try to add spaces around the `/`, any syntax bellow will be detected again

Without spaces:
<img width="226" alt="capture d ecran 2017-01-18 a 12 02 31" src="https://cloud.githubusercontent.com/assets/674667/22057511/04e85324-dd76-11e6-8e31-f15fa594e7b5.png">

With spaces:
<img width="191" alt="capture d ecran 2017-01-18 a 12 02 41" src="https://cloud.githubusercontent.com/assets/674667/22057512/050c0e72-dd76-11e6-8c5b-82f4156b71aa.png">

**Comment by aeschli** [comment] 2017-01-19 16:40
duplicate of https://github.com/textmate/coffee-script.tmbundle/issues/8

**Closed by aeschli** 2017-01-19 16:40 UTC
Labels: languages basic
