### ISSUE TITLE
Unable to establish SSL connection

### ISSUE THREAD

**Issue by pengzhen80** [microsoft/vscode#118778] opened 2021-03-12 01:34 UTC
Connecting to vscode.cdn.azure.cn (vscode.cdn.azure.cn)|116.162.88.66|:443... connected.
 Unable to establish SSL connection.

**Comment by nimula** [comment] 2021-03-12 02:30
I've the same problem since yesterday.

**Comment by TylerLeonhardt** [comment] 2021-03-12 17:16
duplicate of https://github.com/microsoft/vscode-remote-release/issues/4648 this should be fixed now. Please give it another go.

**Closed by TylerLeonhardt** 2021-03-12 17:16 UTC
