### ISSUE TITLE
Error during Datamigration smoke test

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#122317] opened 2021-04-27 11:58 UTC
Testing #122184

The tests all still passed, but there was an error:

```
 VSCode Smoke Tests (Electron)
    Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
      Datamigration
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.windows > DIV.monaco-workbench.windows.chromium.nopanel.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.monaco-scrollable-element > DIV.welcomePageFocusElement'. Looking for .quick-input-widget .quick-input-box input
    at f.isActiveElement (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:570:78624)     
    at m.call (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2781:64105)
    at C.onPromise (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68877)
    at C.onRawMessage (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:68236)
    at file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:67489
    at c.fire (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at EventEmitter.N (file:///C:/Users/alros/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60411)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:117:979)
        √ verifies opened editors are restored
        √ verifies that 'hot exit' works for dirty files
```

**Comment by bpasero** [comment] 2021-04-27 13:32
I was not able to reproduce on the first run, but a second run I noticed how getting started was the active editor and not the one that the test opens. Here the error seems similar, `DIV.welcomePageFocusElement` is the active element even though we expect something else.

I think the new getting started page is causing flakiness in the smoke tests and I wonder whether we should disable welcome entirely when running smoke tests.

When this happened what I saw was this:
* getting started editor appears
* it animates to the left (aka something happens?)
* the editor of the smoke test opens inactive behind the welcome

@JacksonKearl is there possibly any code in getting started that could explain this? are we stealing focus somehow?

**Comment by bpasero** [comment] 2021-04-27 13:34
This is what the smoke test shows:

![image](https://user-images.githubusercontent.com/900690/116250411-fe05d100-a76d-11eb-94c1-6cb0069b67dc.png)

And when the smoke test fails it seems that this editor is active.

**Comment by JacksonKearl** [comment] 2021-04-28 06:06
Yes there's code to open the first walkthrough and focus its first element in some cases, though it should not be occurring here.

**Comment by JacksonKearl** [comment] 2021-04-30 17:40
IMO we should disable experiments in smoke tests, designing smoke tests around them (or them around smoke tests) adds a lot of complexity without any real gain. We have the `workbench.enableExperiments` configuration, but I'm not sure the best way to disable it in smoke tests (can I check in core if I'm in a smoke test environment and set the default to false? Or should I change the smoke test runner to set that configuration false?) 

Any thoughts on this appreciated.

**Comment by bpasero** [comment] 2021-05-26 12:23
Maybe fixed with https://github.com/microsoft/vscode/issues/124674 too.

**Comment by meganrogge** [comment] 2021-06-02 19:33
@JacksonKearl despite the fact that I see you modified this milestone to be in June 9 days ago, looks like Github didn't accept that FYI

**Comment by JacksonKearl** [comment] 2021-06-25 20:53
Welcome has been disabled in smoke tests for a bit now.

**Closed by JacksonKearl** 2021-06-25 20:53 UTC
Labels: getting-started, smoke-test-failure
