### ISSUE TITLE
Powershell launched even if default terminal is set to command prompt on windows.

### ISSUE THREAD

**Issue by puppywang** [microsoft/vscode#132675] opened 2021-09-08 16:59 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.60.0
- OS Version: Win 10.0.19043

```
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1.  Set default terminal to `Command Prompt`, the settings.json have been updated with `"terminal.integrated.defaultProfile.windows": "Command Prompt",`.
2. Keep terminal open, and shutdown VSC, later launch VSC with the same project from taskbar, the `Powershell` is launched as `Default shell`

**Comment by gjsjohnmurray** [comment] 2021-09-08 17:13
/duplicate of #132150 and will be fixed in upcoming recovery release

**Closed** 2021-09-08 17:14 UTC
Labels: *duplicate
