### ISSUE TITLE
vscode.workspace.onDidCloseTextDocument takes about 3 minutes above to fire

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vscode#84505] opened 2019-11-11 16:03 UTC
`vscode.workspace.onDidCloseTextDocument` takes about 3 minutes above to fire.
I search accross the issues to find out with no luck. 
I know it is designed, but it is quite confusing.

In my extension
1. Start a tcp server in extension
2. A client process (not extension itself) connect to the server and send some data
3. Write recieved data to a tmp file
4. Open file with `vscode.workspace.openTextDocument` 
5. Show it with `vscode.window.showTextDocument`

Then I need to know when this doc is closed(when tab is closed), because I need to close the tcp connection. The client process need to know closed event immediately because it is blocking there until tcp connection closed. That's all I need.

I am going to give it up, somebody help me please! Many thanks!

**Comment by DanTup** [comment] 2019-11-11 17:38
I think you probably mean the `Close` event not `Save`? I think this is essentially what's discussed at https://github.com/microsoft/vscode/issues/15178. VS Code gives no way to know which files are "open in editors" as a user would considered open, but rather its APIs cover only its internal definition of the file being open, which persists for up to 3 mins after the user closes an editor.

**Comment by xiaozhuai** [comment] 2019-11-12 03:16
Yes, I do mean `Close` event, not `Save`. Forgive my mistake.
I've already see #15178, The difference is I donot need to know what files are opened. I just need a notifaction when file closed, if that file is open by me, then I can do some cleanup. That's what I want.

**Comment by DanTup** [comment] 2019-11-12 07:12
I understand, but all issues relating to that are being closed as dupes of that one (for ex. see https://github.com/microsoft/vscode/issues/43056). The reason there's a request for open editors is because of the way the close event works (otherwise we could use it to track our own list of open editors).

I feel your pain, it's caused me issues too (https://github.com/Dart-Code/Dart-Code/issues/778).

**Comment by xiaozhuai** [comment] 2019-11-12 07:35
Ok. How I can solve this? Any ideas? @eamodio come up with `workbench.action.nextEditor` cmd to loop through editors, but it is not suit for my case.

**Comment by DanTup** [comment] 2019-11-12 08:03
I don't think there are any other workarounds (lots of us would be very happy if there were).

**Comment by jrieken** [comment] 2019-11-12 08:28
/duplicate of https://github.com/microsoft/vscode/issues/15178

**Closed** 2019-11-12 08:29 UTC
Labels: *duplicate, api
