### ISSUE TITLE
VSCode.ShipIt Service could not initialize xpcproxy

### ISSUE THREAD

**Issue by jayphelps** [Microsoft/vscode#10718] opened 2016-08-19 19:35 UTC
- VSCode Version: 1.3.1
- OS Version: Mac OS X 10.11.5

Every two seconds I'm receiving these in the system Console:

```
8/19/16 12:30:55.476 PM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt[18008]) Service could not initialize: 15F34: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
8/19/16 12:30:55.476 PM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
```

I assume this isn't normal that xpcproxy is crashing. I'm fairly new to vscode so I haven't noticed any particular feature not working except I cannot update vscode without manually going to the website and getting a new binary, but it sounds like #3520 is the cause of that.

**Comment by alexandrudima** [comment] 2016-08-22 08:14
@weinand @joaomoreno any ideas -- I could not find "com.microsoft.VSCode.ShipIt" in our sources

**Comment by joaomoreno** [comment] 2016-08-22 08:21
Check electron/electron#5139. I assume you have tried restarting your machine?

**Comment by jayphelps** [comment] 2016-08-22 17:19
@joaomoreno yep, I've restarted three times since then. No change. Interesting that they also could not update and had the same symptoms as me. When I attempt to update, the app closes and does not start back up, when I start it again it had not updated.

If this is firmly believed to be an electron issue, obviously I can move this over to there.

**Comment by joaomoreno** [comment] 2016-08-22 20:35
Definitely sounds dupe of #3520. You can also reach out to the Electron folks, I'd be interested in knowing if they figure it out.

**Closed by joaomoreno** 2016-08-22 20:35 UTC
Labels: needs more info
