### ISSUE TITLE
扩展程序一直报这个错

### ISSUE THREAD

**Issue by amagiAmagi** [Microsoft/vscode#37865] opened 2017-11-09 03:27 UTC
![image](https://user-images.githubusercontent.com/30867702/32586973-dca0642a-c540-11e7-8ce2-4b62fbf3560f.png)
求解决！！！！！急急急

**Comment by mjbvz** [comment] 2017-11-09 03:42
Duplicate of #34385

**Closed by mjbvz** 2017-11-09 03:42 UTC
Labels: duplicate

**Comment by amagiAmagi** [comment] 2017-11-09 03:48
So what should I do?

**Comment by xrmzju** [comment] 2017-11-27 07:51
so what should i do

**Comment by mjbvz** [comment] 2017-11-27 18:30
Please follow #34385
