### ISSUE TITLE
VS Code black screen VMWare Fusion win 8 vm

### ISSUE THREAD

**Issue by lhsomoza** [Microsoft/vscode#24797] opened 2017-04-14 18:49 UTC
- VSCode Version: 1.11.2
- OS Version: windows 8.1 virtual machine running on VMWare Fusion

Steps to Reproduce:

1. Disable Accelerate 3D Graphics in the vm display setting before booting the vm. Boot and Login.
2. Install VSCode
3. Run VSCode -- screen is black.
4.- Close VSCode.
5. add --disable-gpu.
6. Start VSCode -- screen is black.

**Comment by bpasero** [comment] 2017-04-18 08:51
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by lhsomoza** [comment] 2017-04-28 17:08
Ok,, I followed your link and downloaded the preview release. Steps Performed:
1.- Uninstalled the installed version 1.11.2.
2.- Restarted the vm.
3.- Installed the preview release.
4.- Opened Visual Studio Code.
Observations:
1.- Upon first open, the main window back color became white for a second and then turned black.
2.- I went to File-Open Folder. This time, the window to select the folder opened (this was not happening before).
3.- I selected the folder, the main screen was black.
4.- I went to File and selected close Folder, and Exit Visual Studio Code.
5.- I reopened Visual Studio Code, the screen flickered as in Observation 1.  But the interesting thing,
the folder I had selected and closed opened and the screen shows contents of Release Notes:1.11.2. 
6.- I selected two files for comparison, all displayed fine. I closed folder, I exited Visual Studio Code.
7.- Re opened Visual Studio Code., the screen flickered as in Observation 1. 
8.- I selected File Open Folder and chose a different folder location , I experienced step 3 above. screen is black.
9. This time the screen remained black, folder contents did not display. I exited.
10.- I added the --disable-gpu, and opened again, the screen remained black.

**Comment by olivierc42** [comment] 2017-07-25 14:26
Just got into the same issue with the following setup:
. Host: Windows 10 Pro.
. Hypervisor: Hyper-V
. Guest: Windows 8.1 Pro
. vCPU on guest: 1
. VSCode running on guest will start with a black screen.
. vCPUs increased to 2
. VSCode running on guest will start properly.

**Comment by bpasero** [comment] 2017-11-14 17:33
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.

**Closed by bpasero** 2017-11-14 17:33 UTC
Labels: electron, needs more info, upstream, workbench
