### ISSUE TITLE
find/replace wraps option

### ISSUE THREAD

**Issue by shungo27** [microsoft/vscode#77706] opened 2019-07-21 00:26 UTC
I want an option wrap on/off when find or replace.

![wraps](https://user-images.githubusercontent.com/7065076/61585579-8c145700-ab99-11e9-8ba1-49e3c4526d2d.png)

The current search widget is ugly. It is not good can not see the number of hits in a small window. I like findbar integrated in window, like Sublime text.

![st find bar](https://user-images.githubusercontent.com/7065076/61585580-96365580-ab99-11e9-81e5-b873c5f9afe9.png)

**Comment by rebornix** [comment] 2019-07-26 22:45
/duplicate of https://github.com/microsoft/vscode/issues/15727

**Closed** 2019-07-26 22:45 UTC
Labels: *duplicate, editor-find, feature-request
