### ISSUE TITLE
Breakpoint widget should respect editor font size

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#78790] opened 2019-08-09 11:07 UTC
#73685 isn't fixed

- VSCode Version: 1.37.0
- OS Version: Windows 10

> Steps to Reproduce:
>
> 1. Create a breakpoint
> 2. Right-click it and select "edit breakpoint"
> 3. See the text not vertically centred

![Capture](https://user-images.githubusercontent.com/7588612/62774868-04d24900-ba9e-11e9-9daf-7c6d3a2c1036.PNG)

**Comment by isidorn** [comment] 2019-08-12 14:28
This works just fine for me on OS X and Win10 with vscode insiders.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

![Screenshot 2019-08-12 at 15 58 26](https://user-images.githubusercontent.com/1926584/62870642-42430a80-bd1a-11e9-8a9f-a1eabfa59575.png)

**Comment by yzhang-gh** [comment] 2019-08-12 19:03
Thanks.

I tried and it is indeed fixed in the insider build. However, I can reproduce it for sure on the stable version.

The fix should have been included in June update. I doubt whether it isn't merged into the release branch.

**Comment by isidorn** [comment] 2019-08-13 08:30
There might be some extension which you are using that is modiyfing css and is breaking this.
Sorry but I can not reproduce this, either in stable and in insiders.
Also no other user seems to be hitting this. Due to that I will close this issue.
And yes the fix was included in the June update.

**Comment by yzhang-gh** [comment] 2019-08-13 12:30
I find the key to reproduction now. Just put `"editor.fontSize": 16` in the `settings.json` and you will see the bug.

**Comment by isidorn** [comment] 2019-08-13 13:27
Yes I acknowledge the bug.
The issue is that the breakpoint widget is not updating as the editor font updates. The size of the widget updates, but the font should update as well.
I am open to PR that fix this issue
Code pointer https://github.com/Microsoft/vscode/blob/65ab4f871fc92e8782170a3dd87ba539c74fa896/src/vs/workbench/contrib/debug/browser/breakpointWidget.ts#L47

**Comment by yzhang-gh** [comment] 2019-08-13 13:52
Will have a try

**Comment by yzhang-gh** [comment] 2019-08-13 15:05
Things look more complicated than we expected.

1. The [`lineNum + 1`](https://github.com/microsoft/vscode/blob/65ab4f871fc92e8782170a3dd87ba539c74fa896/src/vs/workbench/contrib/debug/browser/breakpointWidget.ts#L140) doesn't feel right. The `CodeEditorWidget` is of 40px height (with font size set to 16)

   ![image](https://user-images.githubusercontent.com/7588612/62951851-9b767100-bde2-11e9-9edc-00d6ffe2128c.png)

   It looks more reasonable if setting the height to 20px

   ![image](https://user-images.githubusercontent.com/7588612/62952023-e3959380-bde2-11e9-9d2e-b0738b02f7d6.png)

2. The centering thing.

   The `selectBox` is centred by the styles of `select-container` (its parent dom)

   ```
   display: flex;
   justify-content: center;
   flex-direction: column;
   ```

   while `inputContainer` gets a hardcoded 8px `margin-top`...

   ![image](https://user-images.githubusercontent.com/7588612/62952694-0ffddf80-bde4-11e9-8344-bc68c8a46d7e.png)

**Comment by isidorn** [comment] 2019-08-13 16:14
@yzhang-gh yes I acknowledge it is not the nicest. Any improvements in that area would be appreciated.

**Comment by yzhang-gh** [comment] 2019-08-13 19:31
I have gone too deep down the rabbit hole 😵. Leaving it to whoever interested...

**Comment by yzhang-gh** [comment] 2019-10-09 13:48
@isidorn I understand this issue is not that important. But I don't agree this is out of scope 🤔. IMHO, it is at least a bug (although with very low priority).

**Comment by isidorn** [comment] 2019-10-09 13:51
Agree, let's reopen.

**Comment by anirudhrb** [comment] 2019-10-23 13:07
@isidorn Attempted a PR (#83153) for this. Please have a look.

**Comment by isidorn** [comment] 2019-10-23 14:34
Verifier:

Change the editor.fontSize, add a conditional breakpoint and make sure the text in the breakpoint widget is centered.

**Closed** 2019-10-23 14:33 UTC
Labels: bug, debug, help wanted

**Comment by yzhang-gh** [comment] 2019-10-24 10:42
Thank you! @anirudhrb

I confirm it is fixed in the insider build.

**Comment by isidorn** [comment] 2019-10-24 12:38
Thanks for letting us know. Adding verified label.
