### ISSUE TITLE
[Git] Cannot find module '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/out*.nls.en.json'

### ISSUE THREAD

**Issue by cdietrich** [Microsoft/vscode#35201] opened 2017-09-27 06:45 UTC
- VSCode Version: 1.16.1
- OS Version: OSx Sierra, German

Steps to Reproduce:

1. Start and Extension in Debug Mode and open a folder under version control
2. debugger stops and emits errors like

Cannot find module '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/out/statusbar.nls.en.json'

**Comment by cdietrich** [comment] 2017-09-27 06:47
same for

Error: ENOENT: no such file or directory, stat '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/out/extension.nls.en.json'

**Comment by joaomoreno** [comment] 2017-09-27 08:20
@dbaeumer Any thoughts?

**Comment by dbaeumer** [comment] 2017-09-28 12:49
@cdietrich do the files actually exist on disk ? If not it looks like a broken installation. In general we don't check every language file when we resolve nls strings. We assume that if the workbench exists in English all bundle extensions have an English nls bundle as well.

**Comment by dbaeumer** [comment] 2017-09-28 12:49
Wrong button

**Comment by cdietrich** [comment] 2017-09-28 12:52
no they dont. if i create them by copy the default ones the messages go away 
`cp extension.nls.json extension.nls.en.json` so i wonder if they are missing by intention (and the loader should load `extension.nls.json`) or accidentally

**Comment by cdietrich** [comment] 2017-09-28 12:54
a freshly downloaded copy has these files only: 
<img width="194" alt="bildschirmfoto 2017-09-28 um 14 54 15" src="https://user-images.githubusercontent.com/238736/30967557-f4fcfed4-a45c-11e7-96c8-ba5058694bab.png">

**Comment by cdietrich** [comment] 2017-09-28 14:22
and i dont have any en.json files besides these i created manually

**Comment by cdietrich** [comment] 2017-09-28 14:51
i see the same behaviour in a brand new install with this setting

<img width="989" alt="bildschirmfoto 2017-09-28 um 16 50 20" src="https://user-images.githubusercontent.com/238736/30973369-36fd8e92-a46d-11e7-8266-e2e3ec83dd30.png">

**Comment by dbaeumer** [comment] 2017-09-28 18:40
My fault. The file you need is `statusbar.nls.json` which is missing in your installation and as it looks like in the download. When we try to resolve `statusbar.nls.en.json` we fall back to `statusbar.nls.json`.

I have no idea why the file is missing.

**Comment by dbaeumer** [comment] 2017-09-28 18:41
It has to look like this:

![capture](https://user-images.githubusercontent.com/1931590/30984379-72d320c4-a48d-11e7-9a8a-84279ac84925.png)

**Comment by dbaeumer** [comment] 2017-09-28 18:43
I should have looked at https://github.com/Microsoft/vscode/issues/35201#issuecomment-332827282 correctly. The file is there so this is not an installation problem.

**Comment by dbaeumer** [comment] 2017-09-28 18:52
I was not able to reproduce this using the latest insider under Windows.

**Comment by cdietrich** [comment] 2017-09-28 18:57
Will try with Insider as well

**Comment by dbaeumer** [comment] 2017-09-28 18:58
@cdietrich I don't think that this is a Insider / versus stable problem. I saw that you use OSX in German. Do you use VS Code with a German UI?

**Comment by cdietrich** [comment] 2017-09-28 19:02
I don’t change anything. Menu entries are English

**Comment by cdietrich** [comment] 2017-09-28 20:07
i can reproduce this on an english linux as well if i start vscode as follows
`LC_ALL=c.UTF8 code .` or `LANG=en_US.UTF-8 code .`   resulting in 
`'/home/dietrich/Downloads/VSCode-linux-x64/resources/app/extensions/git/out/main.nls.en-us.json'`

**Comment by cdietrich** [comment] 2017-09-28 20:14
i had a look at the code and it looks like it works with catched exceptions. so if i have a look at these while debugging i will be stopping at them as well. sorry for the noise

**Comment by dbaeumer** [comment] 2017-09-29 07:19
@cdietrich good to hear that there is nothing broken. I will close the issue

@isidorn is there any way to exclude some exception when All Exceptions is checked.

**Closed by dbaeumer** 2017-09-29 07:19 UTC
Labels: git, needs more info

**Comment by isidorn** [comment] 2017-09-29 07:42
@dbaeumer not currently. It is up to the debug adapter to fine grain these choices, however I am not aware that any adapter is currently doing this.
