### ISSUE TITLE
vs code is too slow

### ISSUE THREAD

**Issue by kesavamuthu** [microsoft/vscode#100120] opened 2020-06-14 14:07 UTC
vs code is too slow to do anything sometimes while typing the letter that shows after sometimes while share the screen using zoom video application to others (the slowness getting into the master level). 
This issue already reported here
https://github.com/microsoft/TypeScript/issues/32851#issuecomment-642901341.
 As per the instructions installed the typescript globally 
using npm -ig typescript .
Still, the issue is there. It's getting slow some times.

**Comment by sahin52** [comment] 2020-06-14 20:06
Similar issue, normally it wasn't slow but today there was a problem, I haven't faced that issue before. I am using node with WSL on Windows environment. I made the terminal full screen and it was really hard to copy the output from terminal. VSCode wasn't responding fast.

**Comment by jrieken** [comment] 2020-06-15 10:53
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by kesavamuthu** [comment] 2020-06-15 12:45
I hope the required profiler startup log and system details attached are enough. Happy to provide more details. 

[prof-6f02.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780247/prof-6f02.main.cpuprofile.txt)
[prof-6f02.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780249/prof-6f02.renderer.cpuprofile.txt)
[prof-6f02.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780250/prof-6f02.extHost.cpuprofile.txt)
[cod.txt](https://github.com/microsoft/vscode/files/4780253/cod.txt)

**Comment by jrieken** [comment] 2020-06-15 12:50
What OS is this?

**Comment by kesavamuthu** [comment] 2020-06-15 12:53
It's windows 10.
OS Version:       Windows_NT x64 10.0.18363

**Comment by jrieken** [comment] 2020-06-15 13:12
Thanks for clarifying. This is a duplicate of https://github.com/microsoft/vscode/issues/22087 and there is no single cause that known to us. Often AV software is at the bottom of this, delaying the fetching of our application bundle.

**Closed by jrieken** 2020-06-15 13:12 UTC
Labels: needs more info, perf, perf-startup
