### ISSUE TITLE
Add a setting to support RGB color profile chosen by OS

### ISSUE THREAD

**Issue by vincentmathis** [microsoft/vscode#65816] opened 2018-12-29 14:22 UTC
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

Steps to Reproduce:
1. take screenshot of vscode and atom (or even gThumb) next to each other
2. change os/monitor color profile
3. take another screenshot of both

This is Atom with my default color profile, colors are vibrant
![atom-os-profile-thinkpad](https://user-images.githubusercontent.com/33002126/50539201-aabeec00-0b7c-11e9-8883-6a57fd41471f.png)
This is Atom after I changend my color profile to sRGB in the operating system settings
(Atom itself also has an option to force sRGB which would produce the same result), colors are washed out
![atom-os-profile-srgb](https://user-images.githubusercontent.com/33002126/50539204-b6aaae00-0b7c-11e9-9ecc-f543ae667622.png)

This is VSCode with the exact same color theme and hex values (in theory) and default color profile, colors are washed out compared to atom with default color profile
![vscode-os-profile-thinkpad](https://user-images.githubusercontent.com/33002126/50539206-bca08f00-0b7c-11e9-9986-ef59f4c95782.png)
This is VSCode after I changed my color profile to sRGB in the operating system. It looks exactly the same as before.
![vscode-os-profile-srgb](https://user-images.githubusercontent.com/33002126/50539211-c2967000-0b7c-11e9-8046-6e540130ea20.png)

Is there a possibility that VSCode would use the OS chosen colorprofile? Currently the colors in VSCode look a little bit washed out on my monitor.

**Comment by carestad** [comment] 2019-02-19 09:06
I am seeing this as well, in Ubuntu. I believe it is related to Chrome/Chromium having difficulties detecting screen changes after a suspend/resume cycle, where one might dock/undock a laptop and change monitors (going from a dual monitor setup to just using the built-in for instance).

[I reported a bug with chromium a wile back](https://bugs.chromium.org/p/chromium/issues/detail?id=845414) regarding this, but so far the only thing that really works is forcing `srgb` as a color profile, that way the colors stay the same no matter.

I can see that Atom allows one to set the color profile in their settings, so why not vscode as well?

**Comment by mike391** [comment] 2019-02-20 18:56
Chrome has been doing this to me as well, but I was able to fix it by forcing sRGB profile in chrome://flags.  I cant see this being tough to implement in vscode as well.

**Comment by jdsimcoe** [comment] 2019-02-21 19:21
I'm seeing this same issues on macOS with the latest build of VSCode Insiders: `Version 1.32.0-insider`. A manual workaround is to add a line of code to `main.js` inside the VSCode app bundle:

`app.commandLine.appendSwitch('force-color-profile', 'srgb');`

**Comment by douglasmiranda** [comment] 2019-03-22 07:00
My workaround for now for Ubuntu + Nvidia: https://gist.github.com/douglasmiranda/2781fd3a5cf6c143184ddde06e8e7cca#color-issues-in-vscode

**Comment by felrib** [comment] 2019-07-04 14:07
The bright colors are gone since last VSCode update (1.36). Using on Ubuntu 19.04.

Trying with `--force-color-profile=srgb` makes no difference.

**Comment by douglasmiranda** [comment] 2019-07-04 17:11
Yep! Now it seems to be working properly.

Vscode 1.36
Ubuntu 18.04.2
GeForce GTX 1050 Ti (nvidia-driver-430 open source)

**Comment by felrib** [comment] 2019-07-04 18:48
Actually I meant that now (1.36) all colors are too opaque. 1.35 was fine.

@douglasmiranda Is it working fine on your setup?

**Comment by douglasmiranda** [comment] 2019-07-04 19:47
Oh I see, I thought you're saying it was ok now.

Here it seems to be ok.

**Comment by felrib** [comment] 2019-07-04 22:07
Thanks for the heads up :)

**Comment by codeart1st** [comment] 2019-07-09 15:56
I have similar issues since 1.36 with a dual monitor setup. If i working on my normal pc monitor without HDR support I see washed out colors. This happens only in combination with a secondary HDR monitor. If I disable the HDR support of the second monitor in Windows all seems to be ok in VS Code.

**Comment by AngellusMortis** [comment] 2019-07-10 16:51
> I have similar issues since 1.36 with a dual monitor setup. If i working on my normal pc monitor without HDR support I see washed out colors. This happens only in combination with a secondary HDR monitor. If I disable the HDR support of the second monitor in Windows all seems to be ok in VS Code.

I have the exact same issue. I cannot upgrade passed 1.35 until this issue is resolved (or you start default to SDR when you have a HDR and SDR monitor). It is a major blocker for me upgrading as I do not think being forced to use the CLI arg to open VS Code all of the time is a proper solution.

**Comment by bpasero** [comment] 2019-08-05 09:48
People seeing this issue, can please try how the situation is with our new Electron 6 enabled builds:

We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by WangZishi** [comment] 2019-08-05 10:15
It seems fix this HDR issue on Windows.

![image](https://user-images.githubusercontent.com/8288105/62457227-e96cf280-b7ac-11e9-9767-64327469c3e3.png)

**Comment by felrib** [comment] 2019-08-05 12:53
![image](https://user-images.githubusercontent.com/443814/62466051-c3246400-b766-11e9-92d4-629e40eb15d0.png)
Left: 1.37.0 Exploration
Right: 1.36.1

It's finally resolved!

**Comment by bpasero** [comment] 2019-08-05 15:31
If this turns out to be fixed with Electron 6, I think we can survive without having this setting configurable.

**Comment by deepak1556** [comment] 2019-10-10 19:36
Fixed with https://github.com/microsoft/vscode/pull/81644

**Closed by deepak1556** 2019-10-10 19:36 UTC
Labels: feature-request, fixed-in-electron-6.0.x, workbench-electron
