### ISSUE TITLE
References screen won't close if code was edited inside it

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#46969] opened 2018-03-29 21:27 UTC
Issue Type: <b>Bug</b>

Open the references window by right-clicking a type and selecting "show all references".
Then go to some references and edit the code inside the references window directly.
Try to close the references window - it won't close.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|63.92GB (48.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.14.1
vscode-eslint|dba|1.4.8
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.3.0
rest-client|hum|0.18.0
debugger-for-chrome|msj|4.3.0
vscode-todo-highlight|way|0.5.12

</details>
Reproduces only with extensions

**Comment by roblourens** [comment] 2018-04-01 04:20
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by macklinb** [comment] 2018-04-01 10:35
@roblourens I was about to open another issue, but I found this - which is exactly the same issue I'm having. This happens only when the Intellisense prompt appears, and also affects the cursor position of any edited text after the user tries to close the window. Thankfully the issue seems to be fixed in the Insiders build - good job!

**Comment by jrieken** [comment] 2018-04-03 07:38
maybe a dupe of https://github.com/Microsoft/vscode/issues/46346

**Comment by ramya-rao-a** [comment] 2018-04-04 00:54
I can repro this in Stable (1.21.1) but not in Insiders

**Closed** 2018-04-04 00:54 UTC
Labels: needs more info

**Comment by ramya-rao-a** [comment] 2018-04-04 17:47
@alongafni In both Insiders and Stable, I am able to save changes made inside the references window as long as the file being edited is the current file where find references was invoked

**Comment by alongafni** [comment] 2018-04-05 02:11
@ramya-rao-a - I was able to reproduce the issue with latest stable - getting "cannot read property 'dispose' of null".

New repro steps - open the References window, edit something and then press Ctrl+Z to undo.
