### ISSUE TITLE
Previous selected result are removed from the results list when selecting another result if searching chinese word in the "Search" tab

### ISSUE THREAD

**Issue by jhongyu** [microsoft/vscode#189452] opened 2023-08-02 06:50 UTC
Type: <b>Bug</b>

1. Search chinese word in the "Search" Tab, and make sure there are results.
2. Select a result to view it in the editor
3. Then select another result

The expected behavior is that vscode keep the results list untouched, while the actual behavior is vscode will remove the previous selected result from the results list 

VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (4.46GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/jhy/** --crash-reporter-id 243344f5-c2ee-4352-8e68-5e1d7abc56d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|16.1.4
catppuccin-vsc|Cat|2.7.0
vscode-eslint|dba|2.4.2
css-flexbox-cheatsheet|dzh|3.3.3
gitlens|eam|14.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
svg|joc|1.5.3
svn-scm|joh|2.17.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.29.0
material-product-icons|PKi|1.5.0
vscode-fileutils|sle|3.10.3
code-spell-checker|str|2.20.5
sort-json|Thi|17.0.1
vscodeintellicode|Vis|1.2.30
vim|vsc|1.25.2
gistfs|vsl|0.4.1
pretty-ts-errors|yoa|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by andreamah** [comment] 2023-08-08 17:59
I can't seem to repro, see the gif below.
[![Image from Gyazo](https://i.gyazo.com/eeaeb70ee4130b38563cefc2b6083994.gif)](https://gyazo.com/eeaeb70ee4130b38563cefc2b6083994)

Does this happen in all your projects with extension disabled?

**Comment by jhongyu** [comment] 2023-08-09 02:57
So here are steps which I reproduce the issue in a test project:
1. there are some files in the project, and there are chinese words, let's say '测试', in these files, meanwhile, there are also chinese words like '测试服务' in these files, which contains '测试', but not equal to the '测试'.
2. when search '测试‘ with the `Match Whole Word` enabled, the search results will contain '测试服务', then selecting the '测试服务'
3. when selecting the next result, the previous result will be removed.

and I reproduce it with my windows pc and mac

the video is recorded in mac

https://github.com/microsoft/vscode/assets/48473551/d0e1ea58-fa25-4cd8-b701-1c78c4afb65c

**Comment by andreamah** [comment] 2023-08-09 15:38
It seems I can get it to reproduce with these steps:
1. have one file with 
```
测试服务
测试
```
and another with just 
```
测试
```
2. turn case sensitivity and match whole word on and put `测试` in the query box
3. reload the window
4. go to search viewlet and make search
5. notice that it finds `测试服务` despite it not matching whole word (there aren't boundary characters around `测试`) :bug:
6. if you perform another search with the file open, the result disappears.

**Comment by andreamah** [comment] 2023-12-05 20:32
This is actually a duplicate of https://github.com/microsoft/vscode/issues/27280
/duplicate https://github.com/microsoft/vscode/issues/27280

**Closed by andreamah** 2023-12-05 20:32 UTC
Labels: bug, search
