### ISSUE TITLE
file rename bug

### ISSUE THREAD

**Issue by wangzhipeng404** [Microsoft/vscode#54833] opened 2018-07-23 01:49 UTC
Issue Type: <b>Bug</b>

in project，when I rename a file, it will open all my files and change my import   path to full path, but i don't want it, i just want rename one file

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (5.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
python|don|0.7.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
auto-rename-tag|for|0.0.15
rest-client|hum|0.19.0
vscode-language-pack-zh-hans|MS-|1.25.3
sublime-keybindings|ms-|4.0.0
vetur|oct|0.12.5
code-settings-sync|Sha|3.0.0
react-beautify|tai|0.3.0
react-redux-es6-snippets|tim|2.1.0
full-react-snippets|wal|1.1.2
ReactSnippets|xab|2.2.0

(1 theme extensions excluded)

</details>

**Comment by burtek** [comment] 2018-07-23 09:40
Same here. It's hard to look through all the 100+ files to check which change is intended and which one isn't

**Comment by mjbvz** [comment] 2018-07-24 01:14
Duplicate of https://github.com/Microsoft/TypeScript/issues/24914. Should be fixed in the [latest VS Code insiders builds](https://code.visualstudio.com/insiders/)

**Closed by mjbvz** 2018-07-24 01:14 UTC
Labels: typescript
