### ISSUE TITLE
Blurred texts on external screen in macOS 10.14

### ISSUE THREAD

**Issue by kwrush** [Microsoft/vscode#59268] opened 2018-09-24 21:16 UTC
- VSCode Version: 1.27
- OS Version: macOS 10.14 Mojave

Does this issue occur when all extensions are disabled?: Yes

After I updated my macOS to 10.14, texts are blurred on external display. It's not that obvious from the screenshot but it was much sharper in 10.13.

![jietu20180924-225852](https://user-images.githubusercontent.com/8037780/45979052-207f5d00-c04e-11e8-992e-636701ca50f1.jpg)

**Comment by cdnil** [comment] 2018-09-25 00:55
duplicate of https://github.com/Microsoft/vscode/issues/51132

try to execute this command in terminal and restart:
`defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`

**Closed** 2018-09-25 04:42 UTC
Labels: *duplicate
