### ISSUE TITLE
Getting started "new" badge appears on all items

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#127829] opened 2021-07-01 22:41 UTC
<img width="334" alt="CleanShot 2021-07-01 at 15 39 12@2x" src="https://user-images.githubusercontent.com/35271042/124197093-a4c66080-da82-11eb-8d7a-1b87d74d2237.png">

Likely a logic bug since the DOM element appears to be empty?

**Comment by rzhao271** [comment] 2021-07-02 21:04
I'm unable to reproduce this on the current Insiders on Windows using a fresh user data dir.

Version : 1.58.0-insider (user setup)
Commit : 062e6519f8973fede2ca736e80682bd19007460a
Date : 2021-07-02T09:56:48.752Z
Electron : 12.0.13
Chrome : 89.0.4389.128
Node.js : 14.16.0
V8 : 8.9.255.25-electron.0
OS : Windows_NT x64 10.0.19043

**Comment by JacksonKearl** [comment] 2021-07-06 17:42
Duplicate of https://github.com/microsoft/vscode/issues/127780

**Closed by JacksonKearl** 2021-07-06 17:42 UTC
Labels: bug, confirmation-pending, getting-started
