### ISSUE TITLE
Windows 7 performance profile

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#24732] opened 2017-04-13 23:36 UTC
- VSCode Version: <code>Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (8 x 2926)</code>
- Memory (System): <code>7.96GB (4.58GB free)</code>
- Memory (Process): <code>131.20MB working set (136.89MB peak, 109.47MB private, 31.59MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|30|
|main|app.isReady => window.loadUrl()|300|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|324|
|renderer|require(workbench.main.js)|1152|
|renderer|create extension host => extensions onReady()|9611|
|renderer|restore viewlet|0|
|renderer|restore editor view state|413|
|renderer|overall workbench load|678|
|main + renderer|start => extensions ready|11482|
|main + renderer|start => workbench ready|2504|

---

:warning: Make sure to **attach** these files: :warning:
- [9f54_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/921110/9f54_main.cpuprofile.txt)
- [9f54_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/921111/9f54_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-04-14 08:14
@sandy081 Another profile with very slow extension host startup, e.g parsing of package.json files...

**Comment by cleidigh** [comment] 2017-04-17 17:09
@elirnm 
I am also looking at some performance issues on Windows 7 as well as with voice operation
Your initial post included the details of your environment,hardware and detailed extension list
Did you use some tool to create this? I have seen similar entries from others it would be great
to not have to make manually if there is something to accomplish this already?

Thanks Christopher

**Comment by elirnm** [comment] 2017-04-17 21:13
@cleidigh Run `code --prof-startup` from the command line with VSCode closed and then follow the prompts.

**Comment by sandy081** [comment] 2017-04-18 08:23
@elirnm Can you please profile on latest insiders https://code.visualstudio.com/insiders and provide the metrics and profiles again. Because, we extended profiling to happen until extensions are ready. This will give us additional information and could double confirm that 11s is because of parsing package.json files.

May I also know how many extensions do you have installed?

Thanks

**Comment by elirnm** [comment] 2017-04-19 06:28
Insiders is starting much faster.

-----
- VSCode Version: <code>Code - Insiders 1.12.0-insider (7efc373d6874511f730bdf7a30b4728ce84b22a8, 2017-04-18T06:12:01.182Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (8 x 2926)</code>
- Memory (System): <code>7.96GB (4.47GB free)</code>
- Memory (Process): <code>126.23MB working set (126.64MB peak, 99.00MB private, 41.96MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|31|
|main|app.isReady => window.loadUrl()|635|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|619|
|renderer|require(workbench.main.js)|3117|
|renderer|create extension host => extensions onReady()|1447|
|renderer|restore viewlet|0|
|renderer|restore editor view state|619|
|renderer|overall workbench load|850|
|main + renderer|start => extensions ready|5907|
|main + renderer|start => workbench ready|5269|

---

:warning: Make sure to **attach** these files: :warning:
- [0acb_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/932013/0acb_main.cpuprofile.txt)
- [0acb_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/932014/0acb_renderer.cpuprofile.txt)

---

I have 18 extensions installed.

**Comment by sandy081** [comment] 2017-12-04 11:25
Marking this as duplicate of #28331

**Closed** 2017-12-04 11:25 UTC
Labels: *duplicate, bug, extension-host, perf-profile
