### ISSUE TITLE
Unresolved ${selectedText} in commands

### ISSUE THREAD

**Issue by Hovestar** [microsoft/vscode#94060] opened 2020-03-31 20:45 UTC
I would like if there was a way of making a single task that handles both a case with selected text, and no selected text. For example I have a command that opens the language help for the selected text function, but occasionally I want to open this without selectedText. 
This is the error specifically:
`'${selectedText}' can not be resolved. Make sure to have some text selected in the active editor.`
I propose three solutions
1. Allow variable defaulting, perhaps under the syntax as follows: `${selectedText|"default text"}`
1. Have `${selectedText}` be set as `""` if there is no selected text rather than error out. This breaks backwards compatibility, if only to remove an error. 
1. Provide an if defined directive in commands. I don't like this because it implies further metaprogramming tools in defining tasks.

**Comment by ArturoDent** [comment] 2020-03-31 22:59
A good request.  A workaround in the meantime is to use the extension https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable for accessing the selected text:

> `extension.commandvariable.selectedText` : The selected text in the active editor, empty string if nothing selected.

**Comment by alexr00** [comment] 2020-04-01 07:44
If we do something like this I prefer option 1. Duplicate of https://github.com/microsoft/vscode/issues/92854

**Closed** 2020-04-01 07:44 UTC
Labels: *duplicate
