### ISSUE TITLE
Select terminal type when creating a new terminal instead of changing "Default shell"

### ISSUE THREAD

**Issue by ManuelMinkAtBOSCH** [microsoft/vscode#118215] opened 2021-03-05 14:19 UTC
I would like to have the possibility to select the type of a new terminal shell, when clicking on "+"-Button New Terminal.

I often have to change my terminals between WSL, bash and powershell. 
And when i create new ones, i have to first change my "Default Shell" before creating a new terminal.

But it would be awesome if i could long click on the "+"-Button or something, to select the type of the terminal i want to create.

![grafik](https://user-images.githubusercontent.com/48314408/110127656-2dc7d680-7dc6-11eb-8518-146fe030c9b6.png)

![grafik](https://user-images.githubusercontent.com/48314408/110127156-8fd40c00-7dc5-11eb-9072-7a18f51eb7a6.png)

**Comment by meganrogge** [comment] 2021-03-05 22:27
Duplicate of #45444

**Closed** 2021-03-05 22:28 UTC
Labels: *duplicate, feature-request, integrated-terminal
