### ISSUE TITLE
had a hard crash, and vs code would not restart. Was only able to start vscode after issuing shell command: code --verbose --prof-startup

### ISSUE THREAD

**Issue by realityexpander** [microsoft/vscode#134154] opened 2021-09-29 18:02 UTC
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`/Users/chrisathanas/prof-e739.extHost.cpuprofile.txt`
-`/Users/chrisathanas/prof-e739.main.cpuprofile.txt`
-`/Users/chrisathanas/prof-e739.renderer.cpuprofile.txt`

**Comment by jrieken** [comment] 2021-10-04 09:08
@realityexpander The performance profiles show nothing suspicious and they are also not for diagnosing crashes. What is this about? Is this the only way you start VS Code?

**Comment by realityexpander** [comment] 2021-10-04 16:25
Yes it was the only way I could start it.

Otherwise it would just launch then quit.

**Comment by jrieken** [comment] 2021-10-05 07:39
And now? Do you still need to start like that or did it recover?

**Comment by realityexpander** [comment] 2021-10-05 17:28
Now it starts fine, but I had to do that to make it work. There were no error messages or dialogs though and I had to do quite a bit of googling and trial and error. 

An error message would have been helpful in resolving the issue.

**Comment by jrieken** [comment] 2021-10-06 06:37
> An error message would have been helpful in resolving the issue.

Agreed, tho there is sure was one on the console or log. Closing this as not reproducible because there isn't enough information to investigate. Please come back to us if encounter this again

**Closed by jrieken** 2021-10-06 06:37 UTC
Labels: needs more info, perf-profile
