### ISSUE TITLE
Typescript "error underlining" and "problems console" completely broken

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#12375] opened 2016-09-21 11:22 UTC
- VSCode Version: 1.6.0-insider (90dda)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open any .ts file
2. Write any type of garbage
3. The wriggly red underline is gone, and the "problems" console shows nothing wrong
4. Try to compile to .js, receive a sh*tton of errors

I'm also using Typescript@next, which is 2.1.0-dev.20160921

![vscode](https://cloud.githubusercontent.com/assets/461084/18709097/b2564a0c-7fd4-11e6-87fd-8a6681cf576c.png)

**Comment by waderyan** [comment] 2016-09-22 23:41
Can you provide me with code I can copy and paste to reproduce the problem? 
Does the problem exist on TypeScript 2.0.2?

**Comment by pocesar** [comment] 2016-09-23 08:09
happens with either `typescript@next` or stable. it doesn't work with ALL .ts files, my tsconfig (didn't change it, it *just* stopped working):

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "preserveConstEnums": true,
    "lib": [
      "dom",
      "es2015",
      "es5"
    ],
    "noImplicitAny": true,
    "sourceMap": false,
    "moduleResolution": "node",
    "inlineSourceMap": false
  },
  "exclude": [
    "test",
    "system",
    "stylesheets",
    "node_modules",
    "modules",
    "keys",
    "configs",
    "bower_components",
    "blog",
    "jspm_packages",
    "application",
    "api",
    ".vscode",
    ".tscache",
    ".sass-cache"
  ]
}
```

**Comment by pocesar** [comment] 2016-09-23 08:18
tested with vscode 1.5.3, and works properly, regardless of typescript version (2.0.3 or next)

**Comment by waderyan** [comment] 2016-09-23 13:54
@pocesar than you for the information and for providing your settings and tsconfig.json file. Couple additional questions. 

1. Can you try running 1.6-Insiders without any extensions? You can do that by running code with `code <your folder name> --disable-extensions`
2. Are the settings files the same between 1.5.3 and 1.6-Insiders? 
3. Can you provide me with the typescript code I can copy and paste to reproduce the issue on my end?

**Comment by waderyan** [comment] 2016-09-23 13:54
@dbaeumer can I get your thoughts here? It looks like we may have introduced a breaking change between 1.5.3 and 1.6? 

Op tested with 1.6-Insiders originally and saw problems when compiling. He switched back to 1.5.3 and the problems go away. He tried multiple typescript versions.

**Comment by pocesar** [comment] 2016-09-23 19:46
@waderyan 

1. yes, no extensions are enabled
2. yes, same settings
3. the file is in a private repo, can I email you it?

**Comment by waderyan** [comment] 2016-09-23 19:51
Yes. wade.anderson@microsoft.com

**Comment by pocesar** [comment] 2016-09-23 20:04
sent

**Comment by dbaeumer** [comment] 2016-09-26 07:26
@pocesar @waderyan this is actually caused by the Electron update we did on 1.6 insider :-). The Electron version we use in 1.6 has a different implementation of fs.realpath which causes problems in the tsserver. I added a 'work around' on our end. However that only went in last Friday and is available this week.

**Comment by waderyan** [comment] 2016-09-26 17:31
@pocesar can you confirm this works for you using the Insider build?

**Comment by pocesar** [comment] 2016-09-27 01:51
@waderyan I'm not being able to test the insiders because of #12503

**Comment by dbaeumer** [comment] 2016-09-27 09:23
@pocesar does that happened all the time. If so can you share our workspace so that we can investigate.

**Comment by pocesar** [comment] 2016-09-27 14:39
@dbaeumer it's not constant, but it definitely is 9 out of 10. when I do manage to be able to load vscode, when the editor area get focus, it freezes.

**Comment by pocesar** [comment] 2016-09-28 18:01
latest version of vscode insiders (c94c8) is showing the wriggly lines and the "problems" tab is displaying the errors, but still randomly getting freezes

**Comment by dbaeumer** [comment] 2016-09-28 18:36
OK. Will close this one. Lets followup regarding the freezes in #12503

**Closed by dbaeumer** 2016-09-28 18:36 UTC
Labels: bug, typescript
