### ISSUE TITLE
Tab stops at user snippets not working

### ISSUE THREAD

**Issue by itswadesh** [Microsoft/vscode#11763] opened 2016-09-09 11:49 UTC
- VSCode Version: 1.5.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

User Snippets -> Javascript

  "Print to console": {
		"prefix": "x",
		"body": [
			"console.log('xxxxxxxxxxxxxxxxxxxxxxxxxx',$1);"
		],
		"description": "Log output to console"
	}
Pressing tab after x shifts cursor to the end of the line where as the desired place is $1

**Comment by mrmlnc** [comment] 2016-09-09 11:51
Duplicate of #11719 and #11742.

**Comment by jrieken** [comment] 2016-09-09 12:06
yeah - dupe of #11742. working on a fix and trying to get it out asap

**Closed by jrieken** 2016-09-09 12:06 UTC
