### ISSUE TITLE
Request: Add regex support to snippets

### ISSUE THREAD

**Issue by aStonedPenguin** [Microsoft/vscode#26380] opened 2017-05-10 10:18 UTC
Being able to do this would be fantastic and drastically increase snippets usefulness above and beyond the example provided

One use case for example is below, I'd love to be able to auto complete anyvar:AcceptInput() while currently there's no way that I've seen to do so.

```json
"ENT:AcceptInput":
{
	"scope": "source.lua",
	"body": ":AcceptInput($0)",
	"prefix": ".*:AcceptInput",
	"description": "SHARED Method: ENT:AcceptInput()"
}
```

**Comment by egamma** [comment] 2017-05-10 10:53
// @jrieken fyi

**Comment by jrieken** [comment] 2017-05-10 10:57
dupe of #6920

**Comment by jrieken** [comment] 2017-05-10 10:59
Oh, actually not a duplicate. @aStonedPenguin You want to always get that snippet above when the prefix matches `<somethingOrNothing>:AcceptInput`, right? So, `foo:AcceptInput` should become `AcceptInput()`?

**Comment by aStonedPenguin** [comment] 2017-05-10 19:27
Yes, that is what I was hoping to accomplish.

**Comment by jrieken** [comment] 2017-05-11 07:05
I'd recommend you to write an extension for that because it seems like a bit of a special case and with extension API you call the powers you need. You can participate in IntelliSense and provider snippets that way. This is a sample: https://github.com/Microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts

**Comment by jrieken** [comment] 2017-06-27 15:09
Closing because this should be done as extension and we are not planning to make a code change in this repo.

**Closed by jrieken** 2017-06-27 15:09 UTC
Labels: editor, extension-candidate, feature-request, snippets
