### ISSUE TITLE
Mouse flickers on border of certain buttons

### ISSUE THREAD

**Issue by celynw** [microsoft/vscode#214459] opened 2024-06-06 14:06 UTC
Type: <b>Bug</b>

I realise this is a very small visual bug, but reporting nonetheless!

Steps to Reproduce:

1. Make sure the window is focused
   - I can't seem to make this happen when another window is focused
2. Hover the mouse over exactly over the bottom border of certain buttons
   - Seems to only be the bottom border

This applies to some certain buttons across VSCode but not others. Some examples I found:

- Extensions sidebar, the `Refresh` and `Views and More Actions...`
- Output pane, the `Clear Output`, `Turn Auto Scrolling Off`, `Set Log Level...`, `Views and More Actions...`, but curiously NOT the `Hide Panel` button (could be a clue?)

https://github.com/microsoft/vscode/assets/3299161/fd4f2f38-6d4b-4363-9d0d-530ac1371406

Does this issue occur when all extensions are disabled?: **Yes**

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 6.5.0-1023-oem
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.46GB (6.29GB free)|
|Process Argv|--disable-gpu --disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by roblourens** [comment] 2024-06-07 00:23
I reproed this a couple times, then I reproed it in an older Stable so it's not a regression, then I added some logging and can't get it to happen again 😅 

But I assign it to you @benibenj because I'm pretty sure it involves the hover. I think you can somehow get into a spot where the hover is appearing and disappearing really fast, when the mouse is in just the right spot. When it's flickering, you can just barely see the pointer arrow on the hover widget flickering below the cursor.

**Comment by ThomasDurand-EIM2** [comment] 2024-06-26 11:37
I have found the same issue, not just with buttons, but also with the edge of the window title:
![2024-06-26_13h30_27](https://github.com/microsoft/vscode/assets/165182098/63fc65ed-f2ca-47df-8d80-0eb85d475c62)

**Comment by benibenj** [comment] 2024-12-10 11:03
Thanks for reporting, there has been some small improvements here. For the time being we are not planning on addressing this any further.

**Closed by benibenj** 2024-12-10 11:03 UTC
Labels: bug, confirmed, workbench-hover
