### ISSUE TITLE
Scoping workbench color customizations to a specific theme

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/vscode#39298] opened 2017-11-29 09:52 UTC
I'm currently applying a bunch of color customizations to my theme:

```json5
{
    "workbench.colorTheme": "Dracula",
    "workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#44475A77",
        "editor.lineHighlightBorder": "#00000000"
    }
}
```

However, I often have to comment/uncomment these settings when I'm switching between themes, e.g because I'm giving a presentation, recording a screencast, or working at night:

```json5
{
    "workbench.colorTheme": "Dracula",
    "workbench.colorCustomizations": {
         // "editor.lineHighlightBackground": "#44475A77",
         // "editor.lineHighlightBorder": "#00000000"
    }
}
```

It would be helpful if we could scope color customizations to a specific theme, similar to how we can scope settings to a specific file type. The customizations are typically tailored to exactly that theme anyway:

```json5
{
    "workbench.colorTheme": "Dracula",
    "workbench.colorCustomizations": {
        "[Dracula]": {
            "editor.lineHighlightBackground": "#44475A77",
            "editor.lineHighlightBorder": "#00000000"
       }
    }
}
```

**Comment by usernamehw** [comment] 2017-11-29 11:11
Duplicate of https://github.com/Microsoft/vscode/issues/36860

**Closed** 2017-11-29 11:15 UTC
Labels: themes
