### ISSUE TITLE
Directory tree in git tab

### ISSUE THREAD

**Issue by simeloni** [microsoft/vscode#75517] opened 2019-06-14 16:25 UTC
It would be good to have the changed files in the git tab organized by the folder they belong to, as in the tab of the project. 

At the moment the folder the changed file belongs to is written besides the file, but when the number of changed files starts to grow, it would be good to have them organized in a "tree-like" structure. 

Is this possible?

**Comment by gjsjohnmurray** [comment] 2019-06-14 18:00
Duplicate of #14582

**Closed** 2019-06-19 09:34 UTC
Labels: git
