### ISSUE TITLE
Incorrect size of Markdown preview when non-zero zoom level

### ISSUE THREAD

**Issue by urmilparikh** [Microsoft/vscode#25672] opened 2017-04-29 15:15 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Set `"window.zoomLevel": 2` // Anything other than 0
2. Open a markdown file and start preview. The preview window will be small than the space available for it.

The issue also happens with side-by-side preview.

**Comment by mjbvz** [comment] 2017-04-29 18:44
Duplicate of #5745. Should be fixed in latest insiders builds

**Closed by mjbvz** 2017-04-29 18:44 UTC
Labels: duplicate, webview
