### ISSUE TITLE
MDN Reference Links for Javascript

### ISSUE THREAD

**Issue by schockocraft** [microsoft/vscode#149418] opened 2022-05-13 04:00 UTC
Currently i can [get the links to the mdn reference for both Css and Html](https://code.visualstudio.com/updates/v1_38#_mdn-reference-for-html-and-css), but not for Javascript.
I find these links to be very helpful.
Having the exact same feature for javascript would be very useful.

I don't know what more to write here tbh, it's just the same advantage it gives already for html and css, just for javascript aswell.

Also ideally vscode could provide the same functionality for other documentations, like the one from node.js, or allow extensions to do so.
I am unsure if this doesn't count as a separate feature, if it does ignore this. :D

**Comment by mjbvz** [comment] 2022-05-13 23:40
Duplicate of https://github.com/microsoft/TypeScript/issues/44204

**Closed by mjbvz** 2022-05-13 23:40 UTC

**Comment by schockocraft** [comment] 2022-05-13 23:44
oh didn't look after typescript as a keyword, only javascript whoops
