### ISSUE TITLE
Installed June update -- lost my source file

### ISSUE THREAD

**Issue by peter-b-web** [microsoft/vscode#102142] opened 2020-07-10 17:39 UTC
Issue Type: <b>Bug</b>

I'm new to VScode -- I just installed it last week. I  used "File->New" to create a file, then cut and pasted a working webapp written in css/html/javascript/jquery from my google apps script environment into the new file, and resumed editing.

I can confirm that now when I write code, I sometimes write entire blocks of code that don't need to be debugged, thanks to vscode code highlighting and error checking... but...

Now after this update -- my file is gone, and I can't find my settings/json file either. What happened!? Now I'm afraid to use "File->New".

Fortunately, I have been backing up the file into my GAS environment every night, because I like the automatic version history it has.  But what if I had done the update before the backup???  And what about all the other beginners that would assume an upgrade would protect their workbench?

I've been spoiled by google's minute by minute versioning -- and hopefully not too many other new comers were!

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment] 2020-07-11 06:11
Sorry to hear you lost work, that should not happen. But without some steps to reproduce from a clean environment (e.g. run `code --user-data-dir <some folder>`) it would be hard for us to understand what happened. Can you try?

**Comment by peter-b-web** [comment] 2020-07-11 06:50
The seqeunce was like this:  I had the editor open on the file -- I clicked on the update button, vscode updated, and when vscode came back, the file was gone.  I was expecting this to work like a Chrome Browser update.  With my file back in an editor window.

BTW: I only could have lost work... by coincidence I had made a backup of the file the night before. But I have lost a lot of confidence in the vscode update process.  Also, I did not lose the settings.json file, I just did not know where to look for it.  

I did what you suggested ... below is the  cut and paste ... it says **The term 'code' is not recognized as the name of a cmdlet** -- if it makes a difference, the file I was working on is an html file with about 500 lines of javascript code in it.  I have it open in google chrome, while the code is open in vscode.

```
PS C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench> mkdir folder


    Directory: C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench


----                -------------         ------ ----
d-----       2020-07-10  11:27 PM                folder


PS C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench> code --userdata-dir folder
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ code --userdata-dir folder
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench>


```

**Comment by bpasero** [comment] 2020-07-11 07:20
We have tests for that which we conduct before releasing (opening a file, making it dirty, starting the newer version over it and verify the file and its dirty contents are there).

I am sorry, I do not understand how you cannot run `code` from the command line. Maybe this is a powershell problem and it works in a command prompt?

Alternatively try to reinstall Code via installer and make sure you have the option to put Code on the path enabled.

**Comment by peter-b-web** [comment] 2020-07-11 16:02
I can't believe it ... I ran code from command prompt and was able to duplicate the problem...

The steps 

1) Open command prompt, "mkdir folder", then, "code --user-data-dir folder"
2) In vscode: "File->New File"  rename it "tester.html" put a "/* hello world */" in it ...
3) Save the file
4) close the editor window by clicking on the x in the vscode explorer 

5) Now, I can't find the file using vscode explorer.  and it's nowhere inside the folder I created... yet -- I can still reopen it from inside vscode using "File ->Open Recent->Reopen Closed Editor"

6) Close vscode
7) open vscode the same way as step #1

8) Now, I still can't find tester.html in vscode explorer, and File ->Open Recent-> shows no recent file editor

What am I missing here? how can vscode be the most popular programmers editor by far, if File->New works like this?  

In my initial case -- I had vscode open on my PC for an entire week. I was able to "Copy Path" so that I could open it in chrome and "Reveal in File Explore" so I could back it up.  The update caused vscode to close for the first time since I installed it, and so I had this condition described in step #8.  

There is a lot of stuff in "folder" -- just not my tester file in there.  Is there anything there that would be useful to you?

Can you explain how File->New can be used to avoid this problem?  

lmk/p

**Comment by bpasero** [comment] 2020-07-11 16:19
@peter-b-web I think I misunderstood what you are seeing as issue then. If you open VSCode blank (without opening any folder), the explorer will only show the editors that are open. If you close the editor you will have to open the file again from the location where it was saved. Here are steps that outline how to achieve that:
* open VSCode
* create a new file
* save it in `C:\MyFiles\myfile.txt`
* close the editor
* close VSCode
* open VSCode
* pick File > Open File
* navigte to `C:\MyFiles`
* select `myfile.txt`
* the file should open again as editor

Can you confirm that resolves the issue?

**Comment by peter-b-web** [comment] 2020-07-11 18:41
I can confirm that resolves "the issue" -- but it doesn't resolve my issue!!! You're talking about a work around for something I would call a bug: that a "File->Save" does not make a "File->New" persistent across sessions.  How could any beginner user know that File->New only creates a temporary file for that vscode session?

Personally, I think if vscode is closed with open editor windows, it should open the next time with the same open editor windows.  Especially after an update.  But "temporary files" should be more clearly marked, so that new users understand a File-New won't persist unless a File->Save As is performed.

**Comment by bpasero** [comment] 2020-07-12 06:07
@peter-b-web I do not understand what the problem is here really. You open a file, you save it, you close it. But you still expect the file to be visible in the VSCode UI? Where should it appear?

Maybe we can turn it around and instead of you explaining the issue, explain a possible solution to me.

**Comment by peter-b-web** [comment] 2020-07-12 06:58
What you just said is "You open a file, you save it," that is exactly what i did! I opened a file and I saved it ... File->New followed by File->Save.  I understand File->Save As as a way to make a copy of a file. 

My file was visible in explorer under workbench right next to workbench.html and workbench.js.  After the update finished, my file was no longer there in workbench. This is where I think the file should have appeared after the update.

The solution is to not permit a File->Save, before a File->Save As, or to permit File->Save, but to have the user confirm they just want the File->New to be  a static file for the current vscode session.  The dialog can have a check box ... don't ask me about this again.

It doesn't matter if you "do not understand what the problem is here really" -- I'm asking you if you can escalate it. I don't believe I'm the first person that has encountered a lost File->New file.  It's a human factors issue.  I used this software for an entire week, not realizing that I could lose all the work if I closed vscode.  That's simply not safe, and it's the type of error a new user would make.  I also think vscode should open with the same windows that it closed during a software update.

Not everybody thinks the MS way that you always follow a File->New with a File->Save As.  Even you say... "you save it"  You did not say you File->Save As it.  FYI, people coming to vscode from Unity and GAS think differently about new files:  In Unity you "create" a new asset, and then edit that. In Google Apps Script new files are persistent.  Neither of these systems have temporary static files like File->New.  I like the idea of a temporary static file -- but I don't want to stumble into my understanding by losing work. 

I hope you get a better idea of what I'm talking about, and hope you have the same concern about new users losing work because they think Save means "Save with file persistence".

**Comment by bpasero** [comment] 2020-07-12 07:05
@peter-b-web thanks for explaining this better. You say:

>  used this software for an entire week, not realizing that I could lose all the work if I closed vscode

But how is that true. The file is saved to disk, no? How is "work lost"? We may have a bug here where we fail to open the file again in VSCode (something I still cannot understand nor reproduce from your steps), but how are the contents of the file lost if you can simply open the file again from the location you saved it to? After all, your hard disk is the place where the contents are stored, no?

Given your steps, let me try to recap exactly what happened:
* you opened VSCode 1.46 empty (no folder opened, no workspace)
* you clicked "File > New File"
* you clicked "File > Save"
* you saved the file in "C:\mywork\myfile.txt"
* you clicked on the X to close the file in the explorer
* you saw a notification about an update for VSCode in the lower left status bar
* you started the update
* VSCode restarted now at version 1.47
* the file you previously saved was not visible, neither in the explorer nor opened as editor

Does that accurately reflect the bug to you?

**Comment by peter-b-web** [comment] 2020-07-12 07:26
It's true, because I never closed vscode for the entire week -- I close my PC with hibernate, so vscode just stayed open the whole week ... I never even closed the editor window.  And that whole time, the file had a path, so I could load it into chrome, and I could back it up on google drive.

You haven't restated my steps correctly:  I never did a "file-save as" in step 3, I did a File->Save in step 3... These are the steps ... with clearer description for step 3 and 8

1) Open command prompt, "mkdir folder", then, "code --user-data-dir folder"
2) In vscode: "File->New File"  rename it "tester.html" put a "/* hello world */" in it ...
3) Save the file using File->Save
4) close the editor window by clicking on the x in the vscode explorer 

5) Now, I can't find the file using vscode explorer.  and it's nowhere inside the folder I created... yet -- I can still reopen it from inside vscode using "File ->Open Recent->Reopen Closed Editor"

6) Close vscode
7) open vscode the same way as step #1

8) Now, I still can't find tester.html in vscode explorer, and File ->Open Recent-> shows no recent file editor, the file is lost.

**Comment by bpasero** [comment] 2020-07-12 07:33
@peter-b-web "File > Save" and "File > Save As" are really identical for untitled files.

You write:

> In vscode: "File->New File" rename it "tester.html" put a "/* hello world */" in it ...

I do not understand how you "rename it". Are you using this:

![image](https://user-images.githubusercontent.com/900690/87241358-ad152e00-c422-11ea-9fa0-67c39279fbde.png)

?

It should result in an untitled file to open:

![image](https://user-images.githubusercontent.com/900690/87241364-b605ff80-c422-11ea-907f-99bf4f51e2fc.png)


Which when you "File Save" should bring up a save dialog, no?

**Comment by peter-b-web** [comment] 2020-07-12 17:46
You are right, it brings up a dialog.  I don't remember how I changed the name... it was either double click on the editor tab, or, I did it in the explorer workbench panel.  Neither way are possible now... I see a "folder panel" where there was a "workbench panel" two days ago. And I can't figure out how to even display the workbench panel.  Both times it was vscode 1.47

If I open vscode without the `--user-data-dir` option -- I have a workbench panel, and no folder panel.  If I do a "File->New" -- the file does not appear on the workbench, like it did before. And it forces me to do a "Save As" if I click "File->save".

I swear my experience is not a hallucination from a different reality!!!!  But I have no explanation for not being able to redo what I did 2 days ago.

Now I have a new concern -- what is the difference between a workbench and a folder, and why am I seeing a workbench in my vscode explorer?  If  you have an answer, I would be grateful.  I can say that i did all the exercises in the Interactive Editor Playground, and I also experimented with trying to launch my File->New in google chrome. I got nowhere with that, and I finally just did "copy path" to display it in chrome.

I'm sorry to have dragged you along on this beginners nightmare.

**Comment by bpasero** [comment] 2020-07-13 05:45
Sorry, I will go ahead and close this issue as I have spend too much time discussing this without understanding the cause. Someone else from the team or someone from the community will have to pick this up and help you. We also have a community over at https://stackoverflow.com/questions/tagged/visual-studio-code that can be of help, as well as a Gitter chat where people can help: https://gitter.im/Microsoft/vscode

**Closed by bpasero** 2020-07-13 05:45 UTC
Labels: needs more info, new release
