### ISSUE TITLE
Terminal window disappear

### ISSUE THREAD

**Issue by lvhuat** [Microsoft/vscode#17462] opened 2016-12-17 14:36 UTC
- VSCode Version: 1.8.0
- OS Version:WINDOW 10

Steps to Reproduce:

1.  BUG or ? Always, terminal disappear when i pulling the splitter between  terminal and editor,
From
![image](https://cloud.githubusercontent.com/assets/20853184/21287549/2ee85934-c4a9-11e6-982c-8af7288a1c0c.png)
To
![image](https://cloud.githubusercontent.com/assets/20853184/21287554/33ffe50e-c4a9-11e6-8783-fb7b7e5faa1f.png)

**Comment by kieferrm** [comment] 2016-12-17 14:41
Resizing terminal on Win10 on parallels for me shows erratic behavior. Based on the amount I resize the terminal either disappears or gets resized.

**Comment by lvhuat** [comment] 2016-12-17 14:45
Anti-virus software  (mine is 360) report 
`Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js`
as spyware virus

**Comment by lvhuat** [comment] 2016-12-17 15:51
@kieferrm 
non-english language of  menu `Selection | *` change partly,if i fill with wrong language option,then the application cannot restart anymore. OMG...,what should i do then.

**Comment by Tyriar** [comment] 2016-12-19 01:36
I cannot reproduce with cmd/Windows 10, it may be related to running bash. It could also be this bug https://github.com/sourcelair/xterm.js/issues/385 which I was having a difficult time reproducing and finding a fix for.

@kieferrm I suggest we defer this for January unless there have been several other reports.

**Comment by kieferrm** [comment] 2016-12-19 06:11
@Tyriar when I ran vscode on Win10 in parallels I used CMD and could reproduce the behavior.

**Comment by kieferrm** [comment] 2016-12-19 06:11
@lvhuat we had the other discussion in #17465.

**Comment by Tyriar** [comment] 2016-12-28 15:31
This may have been fixed by https://github.com/Microsoft/vscode/commit/d298183b268a81fe9079517419542c8d4eecfe2d which will come to Insiders when it's switched back on.

**Closed** 2017-04-21 04:43 UTC
Labels: important
