### ISSUE TITLE
Syntax Highlighting fails in for loop

### ISSUE THREAD

**Issue by NocFlame** [Microsoft/vscode#4866] opened 2016-04-01 18:16 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7, 10, Mac 10.11.4

Steps to Reproduce:

1. Start VS Code 
2. Type a for loop without a spaced condition i.e j< 10
![screen shot 2016-04-01 at 20 01 10](https://cloud.githubusercontent.com/assets/1550134/14215888/1ee84efc-f846-11e5-861d-384528b462ad.png)

**Comment by Tyriar** [comment] 2016-04-01 21:01
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by Tyriar** 2016-04-01 21:01 UTC
