### ISSUE TITLE
Find and replace not working properly

### ISSUE THREAD

**Issue by s1ssagar** [microsoft/vscode#126952] opened 2021-06-23 05:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. While writing on the find and replace fields the content itself gets hidden unless we navigate to some other place.

**Comment by yume-chan** [comment] 2021-06-23 06:29
Duplicate of #126896

**Closed** 2021-06-23 22:19 UTC
