### ISSUE TITLE
Unable to select all text in internalConsole or integratedTerminal

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/vscode#22035] opened 2017-03-06 00:56 UTC
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1.Run some app that spews a bunch of stuff to the console
2.Try to select it all
3. Notice that select/drag does not scroll the window.  
4. Select at the top then scroll down to shift select at the bottom. 
5. Notice that the selection is trimmed to the top visible line.
6. Try the same thing but starting at the bottom and going up
7. Notice that the selection is similarly trimmed.

**Comment by isidorn** [comment] 2017-03-06 15:22
Duplicate of https://github.com/Microsoft/vscode/issues/2163

**Closed by isidorn** 2017-03-06 15:22 UTC
