### ISSUE TITLE
Feature request: HTML Start and end tag should change at same time like VS have

### ISSUE THREAD

**Issue by ZakiMohammed** [Microsoft/vscode#49689] opened 2018-05-11 11:24 UTC
VS code is love. so does VS. The feature which is there in VS 2017 is amazing where the end tag changes automatically if the start tag changes and vice versa. Its not big feature hope I can see this in next release. <3

**Comment by aeschli** [comment] 2018-05-14 10:54
duplicate of #47069

**Closed by aeschli** 2018-05-14 10:54 UTC
Labels: editor, editor-core
