### ISSUE TITLE
[feature] Ability to click on types within tooltip hints to show further tooltip hints

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#109264] opened 2020-10-23 20:09 UTC
I think it would be helpful if within a tooltip hint, one could click on parts of the code snippet in order to cause the tooltip hint to update to show the info for the thing that was clicked.

For example, consider this tooltip:

![tooltip-type-hint](https://user-images.githubusercontent.com/297678/97049284-51cdfe00-1530-11eb-82bf-98a2623169c3.png)

That tooltip currently shows the definition of `to` because I hovered on `to`.

Imagine we could click on the `ToOptions` identifier, and the tooltip hint would update to show the definition of `ToOptions` instead of the definition of `to`. We could further click on anything in the defintion of `ToOptions` to update the tooltip to that, and so on.

I think this would be helpful.

Otherwise, I have to instead close the tooltip, go back to the code, then use the `Go to Definition` on that piece of code. While `Go to Definition` itself is great, it may be nice to also offer the tooltip option so that the user has an alternate type-exploration workflow that is consistent with the action they already started (looking at types in a tooltip).

The tooltip will be updated on each click, which may often be good enough. But in cases when the tooltip is not good enough (f.e. too much information to show in the tooltip, etc) then the user can still use the `Go to Definition` feature in the actual code.

**Comment by mjbvz** [comment] 2020-11-04 21:21
Duplicate of #64566 (which also included a discussion for normal hovers)

**Closed by mjbvz** 2020-11-04 21:21 UTC
