### ISSUE TITLE
Webview editorGroupToViewColumn exception

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#71316] opened 2019-03-27 21:18 UTC
Issue Type: <b>Bug</b>

* Install GitHub Pull Request extension
* Navigate to pull requests
* Open a description node
* Switch to a local file
* Switch back to the description node
* Exceptions in console

```
Invalid group provided: Error: Invalid group provided
    at Object.t.editorGroupToViewColumn (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2843:274)
    at k.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3592:893)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at e.doEmitActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4507:68)
    at e.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4506:872)
    at t.push.e.onDidGroupChange.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4507:160)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:416)
    at t.editorControl.openEditor.then.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5025:915)
```

https://github.com/Microsoft/vscode/blob/52ec060807443e812290f472f0b550798cb727f3/src/vs/workbench/api/electron-browser/mainThreadWebview.ts#L315

VS Code version: Code - Insiders 1.33.0-insider (1afeb46cc4f2856ed6d0759fff85b13647c7ab83, 2019-03-27T16:02:22.809Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|-psn_0_2204186|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.3
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.25.1
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
vscode-pull-request-github|Git|0.5.1
ocaml|hac|0.6.43
beautify|Hoo|1.4.11
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.12
vscode-azurefunctions|ms-|0.15.0
vscode-language-pack-zh-hans|MS-|1.33.0
python|ms-|2019.3.6139
azure-account|ms-|0.8.0
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1403
debugger-for-chrome|msj|4.11.3
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.17.1
subtitles-editor|pep|1.0.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
ruby|reb|0.22.3
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.5.4
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.1

(12 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-03-28 02:04
Duplicate of #71234

**Closed by mjbvz** 2019-03-28 02:04 UTC
Labels: bug
