### ISSUE TITLE
High CPU usage / Intellisense stops working

### ISSUE THREAD

**Issue by MoxxNull** [Microsoft/vscode#16073] opened 2016-11-25 17:24 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-material2-snippets|deerawan|1.0.1|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.6.4|
|auto-rename-tag|formulahendry|0.0.8|
|Theme-FlatlandMonokai|gerane|0.0.4|
|tstools|iBotMedia|1.1.3|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce / Problem:

1. After some hours of coding, Visual Studio Code uses constantly > 30% CPU 
2. Intellisense stopps working at that point or becomse so slow, you cannot use it.
3. I have to close it, kill the remaining task end reopen it, then it works for a few hours.

**Comment by jrieken** [comment] 2016-11-25 18:29
@MoxxNull Can you reproduce without having extensions enabled (start code with `code --disableExtensions`) and when this happens what exact process is going crazy? Please include the full command including arguments - [process explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) will be your friend. Thanks and Happy Coding

**Comment by MoxxNull** [comment] 2016-11-25 18:32
By the time I posted that, I realized that shoul have been the first thing to do, sorry..   I am currently running without extensions, in case that goes well I will add one by one.  

I'll add more info !

**Comment by Jussif** [comment] 2016-11-25 23:40
I have the same problem when Im trying to code. The program just stop working and freezing, so I have to kill the program and reopen. I updated the program yesterday and today, I have to solve this problem.  Help!

**Comment by buu700** [comment] 2016-11-26 21:29
I'm running into a similar issue on OS X El Capitan (case-sensitive filesystem) while working on a TypeScript project. After noticing IntelliSense stop working (specifically, mousing over something to get its type and/or documentation hangs indefinitely), I consistently find a process called Code Helper spiking my CPU above 100% until I kill it from the task manager.

Only extensions I have installed are Microsoft's "Docker Support" and "Git Blame".

**Comment by fbnlsr** [comment] 2016-11-27 08:39
@buu700 @Jussif @MoxxNull did you have at some point [Crane](https://github.com/HvyIndustries/crane) installed on VS Code ?

I ran into the same problem last week. My VSCode started to consume a huge amount of CPU and Code Helper was taking 120% CPU. Even though I had Crane uninstalled it didn't change. I had to close Code and kill the process.

**Comment by buu700** [comment] 2016-11-27 08:48
Nope, haven't used that one, although it's possible that I could've installed another extension with a similar issue at some point.

**Comment by MoxxNull** [comment] 2016-11-27 08:49
Me neither..  Still testing it without extensions / adding one by one. So far it seems good, but as the problem appeared after several hours  this will take some time.

**Comment by Jussif** [comment] 2016-11-27 11:56
I don't have installed that program. I only have one extension that is the python extension created by donjayamanne. Yesterday, I realized that VS Code consumed more than 50% of the CPU memory and I tried to find the Code Helper process  but I didn't find it. How do you find this process on the pc @MoxxNull @fbnlsr @buu700??? Thanks for your help

**Comment by Method-X** [comment] 2016-11-29 05:14
If multiple people are having this problem, just post your list of extensions and we can narrow down the common denominator that way. Any easy way to list all active extensions?

**Comment by Jussif** [comment] 2016-11-29 12:57
@Method-X I have only one extension installed on VSCode. This extesion is PYTHON created by donjayamanne.
I am testing the following command line that was suggested by @DonJayamanne to be added to the settings.json file

**"python.devOptions":["USERELEASEAUTOCOMP"]**

As soon as I have results I will notify. Thanks for your help.

**Comment by chrmarti** [comment] 2016-11-29 17:00
@Method-X You can use `code --list-extensions --show-versions`. Note that this does include disabled extensions.

**Comment by buu700** [comment] 2016-11-29 17:21
```
PeterJausovec.vscode-docker@0.0.8
waderyan.gitblame@1.3.0
```

**Comment by Jussif** [comment] 2016-11-29 22:35
I have been working adding this command line without any problem. 

"python.devOptions":["USERELEASEAUTOCOMP"]

After this correction, the VSCode is working correctly without increasing the PC usage @DonJayamanne .

**Comment by chrmarti** [comment] 2016-11-30 00:48
https://github.com/DonJayamanne/pythonVSCode/issues/531

**Comment by Method-X** [comment] 2016-12-06 02:21
Well, I can at least confirm this is an extension issue. I uninstalled a few extensions I wasn't using and haven't had this issue since. I didn't keep track of the extensions I uninstalled.

**Comment by buu700** [comment] 2016-12-09 23:42
Agreed that it's probably an extension issue. While I have still had IntelliSense randomly die on occasion since removing my git blame extension, it hasn't been nearly as frequent or been accompanied by the high CPU usage of the original issue.

**Comment by buu700** [comment] 2016-12-24 05:15
Not sure if it's the same root cause or an entirely different issue, but I've been running into exactly these symptoms again (with no extensions enabled) since the 1.8.1 update.

**Comment by chrmarti** [comment] 2016-12-25 09:57
@buu700 Could you run the command in https://github.com/Microsoft/vscode/issues/17740#issuecomment-268851539 when the problem occurs and paste the result there?

**Comment by buu700** [comment] 2016-12-25 16:09
```
100.0 buu700            2268 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
  0.0 buu700            2269 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/buu700/Library/Application Support/Microsoft/TypeScript --enableTelemetry
  0.0 buu700            2538 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  0.0 buu700            2539 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --channel=2538.0.680398471 --mojo-application-channel-token=7347E75BB7700540F77B571EB0F98AE5 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=18,20,29,40,48,51,52,56,58,66,67,71,73,75 --gpu-vendor-id=0x8086 --gpu-device-id=0x0a2e --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x0a2e
  0.0 buu700            2606 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=SharedProcess
  0.1 buu700            2609 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=FC3B99B9B0762E59965A702FCE28F0F2 --lang=en-US --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=7166B41057C2AF2704FADCA3B4D6D8E3 --mojo-application-channel-token=FC3B99B9B0762E59965A702FCE28F0F2 --channel=2538.1.1021247908
  0.0 buu700            2610 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
  0.0 buu700            2611 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
  0.0 buu700            2614 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/p8/ml7_9hzj55lbpr_17ks5tv6c0000gn/T/VSCode Crashes --url=https://ticinocrashreporter.azurewebsites.net/crash --handshake-fd=57
  0.0 buu700            2616 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap /usr/local/bin/git /Users/buu700/cyph/master utf8 /Applications/Visual Studio Code.app/Contents/MacOS/Electron 2.10.0
 99.7 buu700            2638 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
  0.0 buu700            2653 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/buu700/Library/Application Support/Microsoft/TypeScript --enableTelemetry
```

A bit more information:

* Closing vscode doesn't kill any Code Helper processes, so if I don't manually kill them myself, then after a few hours of quitting and reopening vscode I'll end up in situations where a large set of Code Helpers each running at ~100% CPU (often well above) stick around and keep my fans blaring. The command output above is with two of them running, and attached is a screenshot of the OS X Activity Monitor with five.

* This seems to happen often enough no matter what I do, but it's 100% consistently reproducible specifically when I work on TypeScript files that exist outside our repo's subfolder which contains our TS project root / tsconfig.json file (standalone ts-node scripts) and try to use any IntelliSense features (peek / go to definition, mouse over method names, etc.).

<img width="1280" alt="screen shot 2016-12-25 at 11 01 15 am" src="https://cloud.githubusercontent.com/assets/415435/21471921/7feeeddc-ca91-11e6-8db1-898ac637b70f.png">

**Comment by chrmarti** [comment] 2016-12-29 13:18
Reopening for the tsserver using a full CPU and staying around after closing the application. Over to you @mjbvz.

**Comment by buu700** [comment] 2017-02-03 21:19
Any updates on this? It's still reproducible with 1.9.

Also, just went ahead and tested with vscode versions 1.4 - 1.6, and it's consistently reproducible in all of them despite my never having run into this (to my knowledge) before 1.7. Is it possible that this could be a bug in an external dependency, e.g. tsserver being referenced from my global node modules rather than from the vscode bundle?

**Comment by Toxicable** [comment] 2017-02-17 07:25
Could we have an update on this? I have started experiencing it consistently since the 1.9 update, exact same symptoms. I have also talked to at least 3 others who are also getting it since 1.9
```
EditorConfig.EditorConfig@0.3.4
eg2.tslint@0.8.1
Google.ng-template@0.0.12
steoates.autoimport@1.2.2
```

**Comment by stephanjust** [comment] 2017-02-17 07:35
I can't guarantee that this is happening since 1.9, but it definitely happens for some time. Intellisense suddenly stops working, CPU usage rises to ~15% from roughly 0-1% before and the ram usage spiked to over 800MB from roughly 150MB (just the highest using process, not all combined).

abierbaum.vscode-file-peek@1.0.1
davidbabel.vscode-simpler-icons@1.3.0
eg2.tslint@0.8.1
IBM.output-colorizer@0.0.10
mrmlnc.vscode-scss@0.6.1
ms-vscode.typescript-javascript-grammar@0.0.18
pmneo.tsimporter@1.2.13
waderyan.gitblame@1.3.0

**Comment by mrmlnc** [comment] 2017-02-17 07:54
@Toxicable, @stephanjust,

Can you reproduce this problem if you disable all extensions? But I thought that the problem in the editor, because I see a lot of such messages.

**Comment by Toxicable** [comment] 2017-02-17 21:57
@mrmlnc Just tested this, disabled all extensions, been coding for about an hour doing a node.js application in TS and now my intellisense is 100% gone, all TS support is gone, CPU is sitting at a constant 34% (on a quad core i5). This is on a windows 10 machine

**Comment by buu700** [comment] 2017-05-01 21:42
I finally found a workaround for this! Looks like it's unrelated to extensions; I just added a jsconfig.json with `{"exclude": ["**"]}` to the root of my project and the problem seems to have gone away.

**Comment by mjbvz** [comment] 2017-05-01 21:51
@buu700 It sounds like you were running into https://github.com/Microsoft/TypeScript/issues/14636. We've added a workaround in VSCode 1.12 to limit how often this should be hit

Please give VSCode 1.12 with TS 2.3.2 a try a let me know if you are still hitting this issue

**Closed by mjbvz** 2017-05-01 21:51 UTC
Labels: bug, freeze-slow-crash, typescript

**Comment by buu700** [comment] 2017-05-01 21:57
Awesome, I'll update and test it out; looks like I'm currently running 1.11.

**Comment by buu700** [comment] 2017-05-01 22:01
Yep, can't reproduce the problem with the insiders build. Terrible time for me to finally find a workaround after dealing with this for so long, but glad it's finally properly resolved!

**Comment by zapkub** [comment] 2017-05-04 10:07
I am also have a problem with intellisense when I use graphql because AST type guide is too long

to reproduce
- add `react-apollo`
- `import { graphql } from 'react-apollo'`
- intellisense will break after try to suggestion `graphql` object type

<img width="887" alt="screen shot 2560-05-04 at 5 05 30 pm" src="https://cloud.githubusercontent.com/assets/4373581/25699103/fcd7ac7e-30eb-11e7-99f2-415d0b90ae12.png">

**Comment by buu700** [comment] 2017-05-22 01:16
It's much more infrequent now, but I have still been occasionally running into these exact symptoms (Code Helper processes hanging around after vscode is closed and using high CPU).
