### ISSUE TITLE
Error Extension host terminated unexpectedly. On first and subsequent startups.

### ISSUE THREAD

**Issue by EdDore** [Microsoft/vscode#4634] opened 2016-03-24 03:24 UTC
- VSCode Version: 0.10.12-insider
- OS Version: Centos 7.2.1511 (Core)

Steps to Reproduce:

1. Installed/unzipped to /opt/VSCode-linux-x64
2. dbl clicked code-insiders icon from Files app
3. after a few seconds the following error is dropped down in the code editor:

   Error Extension host terminated unexpectedly. Please reload the window to recover.

**Comment by jrieken** [comment] 2016-03-24 07:18
I believe you investigate in a dupe of this

**Comment by Tyriar** [comment] 2016-03-24 15:24
Related: https://github.com/Microsoft/vscode/issues/4438

@EdDore did vscode crash or did you only see the extension host terminated message at the top?

**Comment by EdDore** [comment] 2016-03-25 03:59
@Tyriar  just the error message. vscode was still running, but just repeatedly dropping the error down. Definitely similar if not a dupe of [#4438 ](https://github.com/Microsoft/vscode/issues/4438)

**Comment by EdDore** [comment] 2016-03-25 04:02
@Tyriar To clarify. If I hit the reload button, it just happens again. Can't type, or do anything in the app.

**Comment by joaomoreno** [comment] 2016-03-30 07:06
Closing as duplicate of #4438

**Closed by joaomoreno** 2016-03-30 07:06 UTC

**Comment by xblox** [comment] 2017-02-09 13:25
same here, 1.9 spits this after around less than 5 minutes and so I lost type checking, auto-completion. 

i tried: 
- deleted all *sock files in /tmp but no improvement
- without extensions: same results
- latest vscode-insiders with latest typescript 2.2.0 | 2.1.6

My Folder has 813851 files. Could this be a problem ? I know other IDEs also become useless with lots of files....
