### ISSUE TITLE
editorIndentGuide.activeBackground bug

### ISSUE THREAD

**Issue by ericrousse** [Microsoft/vscode#49230] opened 2018-05-04 17:06 UTC
Issue Type: <b>Bug</b>

Hello,

I've updated my values for my settings with this:
    "workbench.colorCustomizations": {
        "editorIndentGuide.activeBackground": "#ff0000"
    }

Works great, but doesn't work properly when using the scroll wheel or when using the scrollbar with a long block that doesn't fit in a single page.

The highlight goes away when I'm scrolling down. And comes back when I scroll back up. But really like that feature, super nice!

I tested with and without my extensions.

Thanks!

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:55.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by alexandrudima** [comment] 2018-05-07 07:34
Duplicate of #49173

**Closed by alexandrudima** 2018-05-07 07:34 UTC
Labels: new release
