### ISSUE TITLE
Notebook diff editor -- typing in input field drops focus immediately

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#230002] opened 2024-09-27 19:01 UTC
repro:
- open notebook with content in the code cell
- change the content + save
- open notebook diff
- try to type in the input field
- 🐛 immediately after a character is typed, the diff is recomputed and the focus is lost

https://github.com/user-attachments/assets/3024bd68-8c51-46d1-b93c-df07670e0a5a

**Comment by DonJayamanne** [comment] 2024-09-30 21:25
Duplicate of #229489

**Closed by DonJayamanne** 2024-09-30 21:25 UTC
