### ISSUE TITLE
Ability to change file names from tabs. 

### ISSUE THREAD

**Issue by edleesr25** [microsoft/vscode#99884] opened 2020-06-11 15:35 UTC
![image](https://user-images.githubusercontent.com/66228228/84406526-a606c000-abd7-11ea-9657-db282fb2b0d2.png)
Make it so that you can click on where I put the blue in the image, and you can change the file name from there.

**Comment by gjsjohnmurray** [comment] 2020-06-11 16:09
Duplicate of #21919, which is already closed and locked.

**Closed** 2020-06-12 12:32 UTC
Labels: *duplicate
