### ISSUE TITLE
Add support for sign in to app and synchronize settings, plugins previously installed and others preferences.

### ISSUE THREAD

**Issue by augustodossantosti** [Microsoft/vscode#32546] opened 2017-08-15 12:52 UTC
I think that feature can improve productivity when is necessary to use a different computer to code or re-install the software for some reason. This feature will work similary as we can see on google chrome now.

**Comment by callummr** [comment] 2017-08-15 13:40
For now you can use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to achieve this :)

**Comment by faustinoaq** [comment] 2017-08-15 14:31
Yeah, [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) works like a charm.

**Comment by aeschli** [comment] 2017-08-15 14:54
duplicate of #2743

**Closed by aeschli** 2017-08-15 14:54 UTC
Labels: workbench
