### ISSUE TITLE
Configure selector keys for suggest widget

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#3658] opened 2016-03-03 07:26 UTC
Whenever suggest widget (e.g. a completion list) is summoned (by a configured trigger character, e.g. `.` or `>`), both Tab and Enter are valid for selection by default. More than once I've accidentally accepted the suggestion rather than doing a line break as intended.

https://github.com/mitaki28/vscode-clang/issues/8 is a good example of this where a `completionProvider` is configured and triggered by `>`, causing issues when trying to do a line break:
![](https://cloud.githubusercontent.com/assets/1016104/13473657/4b754dec-e088-11e5-8aa3-35e09aee946a.png)

At first I thought I'd suggest that the default should be only Tab to avoid all of this. But then I came to think that perhaps more ideally this should be configurable by the extension that registers a provider with `triggerCharacters`. What do you think?

**Comment by joaomoreno** [comment] 2016-03-03 09:19
It's already part of the [`registerCompetionItemProvider` signature](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#1036).

**Comment by csholmq** [comment] 2016-03-03 10:00
@joaomoreno Could you elaborate? Can't find anything on this.

**Comment by joaomoreno** [comment] 2016-03-03 10:27
Oh! Apologies, I confused the two features!

**Comment by joaomoreno** [comment] 2016-03-03 10:32
Removing <kbd>Enter</kbd> from the acceptance keys would make the whole interaction rather strange, though. I'm not sure that would be such a good idea.

**Comment by csholmq** [comment] 2016-03-03 11:15
I agree that the convention of Enter might not be so popular to remove.

```
template <typename Type>
Type max(Type a, Type b) {
    return a > b ? a : b;
}
```
is perhaps a more valid example for e.g. C++. Other languages have for sure syntaxes which could collide with completion trigger characters. It depends on the coding style of the programmer in this instance. It might also come in play when you do an anonymous function calls (lambda abstraction):

```
context.subscriptions.push(vscode.workspace.onDidSaveTextDocument(d => 
    ...
    yourMagicCode();
    ...
));
```

* Delay is dubious since one will suspect that no completions are available if it's set to more than a second.
* Disable the offender is a ugly workaround IMO. It removes functionality.
* Agreed. Sounds complicated as it's no longer language agnostic.

**Comment by joaomoreno** [comment] 2016-03-03 14:58
So a C++ user could never use the <kbd>Enter</kbd> key to accept a suggestion? I'm not sure that is OK.

I do recognise the problem though.

@stevencl any thoughts?

**Comment by csholmq** [comment] 2016-03-03 17:51
A C++ could very well be able to use this. I'm just suggesting that this choice is left for the extension to control and ultimately by the end user which configures the extension. It all depends on the preferences of the user base. As it stands now, the "only" solution is to disable Enter as a shortcut for **all** extensions and languages.

**Comment by stevencl** [comment] 2016-03-05 08:00
Is it possible to trigger on a string, or sequence of characters? So instead of triggering on '>' we would trigger on '->' for C++?

**Comment by csholmq** [comment] 2016-03-05 13:10
@stevencl That's actually a nice workaround. At least for languages with -> as member operators.

**Comment by joaomoreno** [comment] 2016-03-08 14:42
ping @jrieken

**Comment by jrieken** [comment] 2016-03-08 16:34
Currently there is no way to configure a trigger sequence but only single characters. Still, the issue would continue to exist as most people run with 24x7 IntelliSense enabled. I tend to favour an option that configures if `enter` should accept a suggestion or not - for simplicity and ease of learning independent of that language.

**Comment by jrieken** [comment] 2016-03-08 16:34
see #1657 for more on this

**Comment by jrieken** [comment] 2016-03-09 10:02
closing this as a duplicate of #1657 as we will go down the path of configuring what <kbd>Enter</kbd> does

**Closed by jrieken** 2016-03-09 10:02 UTC
Labels: feature-request, ux
