### ISSUE TITLE
Add JS object completion / Intellisense for prototype accessors

### ISSUE THREAD

**Issue by Seblor** [Microsoft/vscode#32322] opened 2017-08-11 12:29 UTC
- VSCode Version: 1.15.0
- OS Version: Windows 10

When creating a JS object and defining some accessors, I found that I couldn't get the intellisense after `this.`

Example code :

```js
function Obj(foo) {
    this.foo = foo;
}

Obj.prototype = {
    get bar() {
        return this.// No intellisense here
    },
    set bar(val) {
        this.foo = val
    }
};
```
But creating a method with `Obj.prototype.test = function () {...}` will get me the intellisense.

Also after [asking on StackOverflow](https://stackoverflow.com/questions/45634999/is-it-possible-to-enable-js-object-intellisense-in-prototype-accessors-in-visual) if it was possible to enable it by tweaking the user settings, someone pointed out that Visual Studio 2015 would give the intellisense.

Would it be possible to replicate the same lexical analysis for this case ?

**Comment by mjbvz** [comment] 2017-08-11 20:09
Thanks. This is a bug and tracked upstream by https://github.com/Microsoft/TypeScript/issues/15163

Closing as a duplicate of https://github.com/Microsoft/TypeScript/issues/15163

**Closed by mjbvz** 2017-08-11 20:09 UTC
Labels: duplicate, javascript, new release, upstream

**Comment by Seblor** [comment] 2017-08-11 20:22
Actually that's not my issue.
Mine is that intellisense does not work properly *inside* the prototype assignement

For the record, I worked around it by using ES6 classes (but I shouldn't have to change my code for the IDE).

**Comment by Seblor** [comment] 2017-08-11 20:24
Here is what I'm talking about :
![](http://i.imgur.com/RoDcD1V.png)

**Comment by daniloaf** [comment] 2017-08-24 00:38
I have the same issue
