### ISSUE TITLE
[BUG] Overlapping Issue in Terminal

### ISSUE THREAD

**Issue by swarajkumarsingh** [microsoft/vscode#196565] opened 2023-10-25 09:15 UTC
- VS Code Version: 1.83.1 (user setup)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open terminal
2. Choose Git Bash as your default terminal
3. Create a second terminal

Issue: The terminal box is overlapping the terminals list, and because of this navigation between terminals in getting interrupted.

Image:
![image](https://github.com/microsoft/vscode/assets/89764448/5ba7bcd6-bdcd-4e83-ab23-173ec88ba7d2)
![image](https://github.com/microsoft/vscode/assets/89764448/8e58ba42-a8c2-49d4-afef-b960e356481c)

Looking forward to quickly fixing the bug.

**Comment by meganrogge** [comment] 2023-10-25 12:25
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by meganrogge** [comment] 2023-10-25 16:08
any errors in the dev tools console?

**Comment by mmadraimov92** [comment] 2023-10-26 08:10
@meganrogge Yes, looks like it is fixed on insiders build.

**Comment by swarajkumarsingh** [comment] 2023-10-26 10:54
> @meganrogge Yes, looks like it is fixed on insiders build.
> 
> ```
> Version: 1.84.0-insider (Universal)
> Commit: 46982792873b62b7ad1099799f7f7f2c6eafde3f
> ```

![image](https://github.com/microsoft/vscode/assets/89764448/3f462d03-1186-4604-9e6c-dc538bf4b617)

I don't think that the bug is fixed!

**Comment by mmadraimov92** [comment] 2023-10-26 11:31
Can you replicate it on Insiders build?

<img width="886" alt="Screenshot 2023-10-26 at 14 30 35" src="https://github.com/microsoft/vscode/assets/28419987/500bb99e-6a65-464a-9d23-7281af77123e">

**Closed** 2023-10-26 14:52 UTC
Labels: info-needed

**Comment by swarajkumarsingh** [comment] 2023-10-26 16:37
fine no worries, after a little side panel adjusting, it is now functioning properly.
