### ISSUE TITLE
ENOENT: [...] typescript.json

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#44537] opened 2018-02-27 11:18 UTC
Issue Type: <b>Bug</b>

Found in the console while testing:

ERR Error: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\typescript\snippets\typescript.json' c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\typescript\snippets\typescript.json

VS Code version: Code - Insiders 1.21.0-insider (1a84a882737184488d965426747a05474f54a759, 2018-02-27T09:01:48.555Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|Memory (System)|5.98GB (3.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --user-data-dir=tmp\user --extensions-dir=tmp\exts|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none
Reproduces without extensions

**Comment by jrieken** [comment] 2018-02-28 09:00
This smells like an extension installation issue because our built-in extension should really have those snippets

**Comment by mjbvz** [comment] 2018-03-01 02:58
Caused by splitting out ts-basics extension. Fixed in current insiders build

**Closed by mjbvz** 2018-03-01 02:58 UTC
Labels: insiders
