### ISSUE TITLE
Add more mouse gestures for multi-cursor

### ISSUE THREAD

**Issue by jijojv** [Microsoft/vscode#84] opened 2015-11-18 18:35 UTC
Please Implement Column Mode selection/editing. 

Previously requested here
https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7761618-implement-column-mode-selection-editing

On Mac preferred shortcut is cmd+option(alt) like Sublime Text does.

**Comment by nippur72** [comment] 2015-11-18 18:47
+1

**Comment by buzinas** [comment] 2015-11-18 18:47
:+1: +1!

**Comment by nippur72** [comment] 2015-11-18 18:48
perhaps this requires also support for virtual space

**Comment by ZombieProtectionAgency** [comment] 2015-11-18 18:50
This is a feature request, not a bug report/issue. Feature suggestions already have a place over at vscodes [uservoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code).

**Comment by Tyriar** [comment] 2015-11-18 18:54
The [repo readme](https://github.com/microsoft/vscode) says file feature requests to vscode/issues

**Comment by sharwell** [comment] 2015-11-18 18:55
@ZombieProtectionAgency Has a policy for this been established yet? More often than not, GitHub issues are suitable for everything from bugs to usability problems to feature requests. The benefit of supporting this is users who have never submitted feedback before don't need to understand everything about the project structure in order to provide meaningful commentary. :smile:

**Comment by ZombieProtectionAgency** [comment] 2015-11-18 19:03
Fair enough, sorry. I was just letting them know there is already a place for feature requests.

**Comment by ygorlazaro** [comment] 2015-11-24 15:53
+1

**Comment by beattyml1** [comment] 2015-12-13 04:01
+1 here in addition to user voice I don't know which is  checked more

**Comment by egamma** [comment] 2015-12-14 08:38
Isn't this mostly addressed by multi cursor support and the actions 'insert cursor above/below' (which will be changed for the Dec milestone to 'add cursor above/below).

@alexandrudima  fyi

**Comment by digitalGaz** [comment] 2015-12-14 17:35
+1

**Comment by alexandrudima** [comment] 2015-12-14 22:14
@jijojv Can you please help me out with some sort of spec regarding what exactly you want...

We already have:
 * add cursor below <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>
 * add cursor above <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Up</kbd>
 * add selection to next selection match <kbd>Ctrl</kbd>+<kbd>D</kbd>
 * move selection to next selection match <kbd>Ctrl</kbd>+<kbd>K</kbd>, <kbd>Ctrl</kbd>+<kbd>D</kbd>
 * add selections to all selection matches <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>
 * undo last cursor action <kbd>Ctrl</kbd>+<kbd>U</kbd>
 * <kbd>Alt</kbd> + `Click` adds a new cursor

I understand there might be more to it, I think something with <kbd>Ctrl</kbd>+<kbd>Alt</kbd> + `Click` which would add selections in a block-like manner, is that what you mean?

**Comment by beattyml1** [comment] 2015-12-14 23:11
It very well maybe addressed by existing features but having it match expecting functionality of almost all other editors and IDEs would probably really help new users and thereby adoption.

**Comment by jijojv** [comment] 2015-12-14 23:22
@alexandrudima Its a common feature https://www.sublimetext.com/docs/2/column_selection.html . I believe VS has it http://joelabrahamsson.com/select-columns-of-text-in-visual-studio/  http://www.visualstudiotipsandtricks.com/blog/2013/04/20/select-and-edit-vertical-blocks/
but is missing from VS Code.

**Comment by alexandrudima** [comment] 2015-12-15 08:50
@jijojv So this is about adding more mouse gestures since we have this:

![image](https://cloud.githubusercontent.com/assets/5047891/11806124/362c1d76-a311-11e5-81ae-ad71912e9a30.png)

**Comment by jijojv** [comment] 2015-12-15 19:27
@alexandrudima it's not quite the same as it requires 2 separate actions which is error prone e.g if you don't let go but yes in a pinch this 2 steps do get you column mode selection and edits.

⌥⌘↓ then MUST let go , then press ⇧→ to get columns

**Comment by glen-84** [comment] 2016-01-18 08:11
The new title made this difficult to find.

With Programmer's Notepad, Atom (with [Sublime Style Column Selection](https://atom.io/packages/Sublime-Style-Column-Selection)), Visual Studio 2015, and obviously Sublime, you can use Alt+Select.

It would make sense to support the same in VS Code.

**Comment by Uristocles** [comment] 2016-01-20 16:23
Alt+Select would be fab!

**Comment by digitalGaz** [comment] 2016-01-20 19:31
That would be great

**Comment by ZombieProtectionAgency** [comment] 2016-01-22 17:42
This might be a bit much (or might not even fit this suggestion) but one feature I like in editors is being able to click then Alt-Shift-click to select an arbitrary block.

**Comment by masaeedu** [comment] 2016-02-09 15:43
@alexandrudima What is required is the ability to press down <kbd>Alt + Shift</kbd> (or some other key combination, I'm not sure what the consensus is), select a starting position and ending position in the code, and end up with all characters within the bounding box of the start and end position. Obviously this is complicated by things like line wrap, but this is the general idea.

**Comment by aloisdg** [comment] 2016-02-15 16:33
> add cursor below `Ctrl+Alt+Down`
> add cursor above `Ctrl+Alt+Up`

It is `Ctrl+Shift+Down` (or `Up`) on my Linux (Arch Linux / i3 if it matters)

**Comment by Tyriar** [comment] 2016-02-16 15:50
@aloisdg context on why the Linux hotkey is different is that it conflicts with switching workspaces on many Debian-based distros.

**Comment by aloisdg** [comment] 2016-02-16 16:26
@Tyriar I think debian-based distro should move the defaut key for window related stuff to the Windows-key (as an OS key), but this argument is for another issue. Thank you for the answer.

**Comment by ccirello** [comment] 2016-03-10 09:46
+1

**Comment by alexandrudima** [comment] 2016-03-14 20:24
Comes in March

**Closed by alexandrudima** 2016-03-14 20:24 UTC
Labels: feature-request, help wanted
