### ISSUE TITLE
Debug picker switches away from compound launch config

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32439] opened 2017-08-14 03:20 UTC
- Select the "Debug VS Code Main and Renderer" compound launch config
- Click debug
- See it switch to one of the configs, so I have to fix it next time I want to debug

![aug-13-2017 20-19-25](https://user-images.githubusercontent.com/323878/29257181-bcbd88fc-8064-11e7-87b1-059abc7e0f8d.gif)

**Comment by octref** [comment] 2017-08-17 14:59
Same issue. Pretty annoying for debugging...

**Comment by shakurass** [comment] 2017-08-17 18:36
Definitely annoying. +1 for a fix to this issue.

**Comment by Gama11** [comment] 2017-08-17 18:41
Duplicate of https://github.com/Microsoft/vscode/issues/32318?

**Comment by isidorn** [comment] 2017-08-28 13:18
@Gama11 thanks, closing as duplicate. This should be fixed in latest insiders

**Closed by isidorn** 2017-08-28 13:18 UTC
Labels: debug
