### ISSUE TITLE
Windows 10 - vsc 1.29.1 - Antimalware Service Executable - still unresolved

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#63285] opened 2018-11-16 09:09 UTC
Hi,
this process still running after opening VSC - crushes CPU http://bit.ly/2TldY0v

I reported this bad state in #63026 I thought I'd solved it by turning off on option 
`typescript.tsc.autoDetect": "off"` but it does not.

Is this the problem known?
Does anyone solve it?

VSC to version 1.28 works fine.
I'm really sad from and my work on some project is very annoying due to bad behavior.

**Comment by alexr00** [comment] 2018-11-16 09:15
Does this just occur when you launch VS Code, or are you doing something specific with VS Code when this happens?

**Comment by Kcko** [comment] 2018-11-16 09:29
After opening project http://bit.ly/2TbIM3D :(

**Comment by Kcko** [comment] 2018-11-16 09:35
A temporary solution is a complete shutdown WINDOWS DEFENDER, but why? VSC behaves simply strangely.

**Comment by alexr00** [comment] 2018-11-16 10:04
Possible duplicate of #63070.

**Comment by roblourens** [comment] 2018-11-16 19:21
Yes duplicate of #63070

**Closed by roblourens** 2018-11-16 19:21 UTC
