### ISSUE TITLE
Visual bug: screen partially erased

### ISSUE THREAD

**Issue by PierreTurnbull** [Microsoft/vscode#65782] opened 2018-12-28 16:00 UTC
- VSCode Version: 1.30.0
- OS Version: Ubuntu 18.04

When writing some buggy JavaScript code, parts of my VSCode are randomly erased, or filled with squares of the background color (or whatever happens).
Here is a screenshot to demonstrate the bug: 
![image](https://user-images.githubusercontent.com/33256529/50520579-83571900-0ac1-11e9-8993-9307845caad2.png)

Steps to Reproduce:
1. Copy and paste the following in a JS file (the more lines, the more visible the bug is) : 
```
const a = a => { return a 
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
const a = a => { return a }
```

Notice that there is a missing `}` at the end of the first line, which makes the following lines tinted grey (like when lines are unused).

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-01-02 19:23
Duplicate of #63915

**Closed by mjbvz** 2019-01-02 19:23 UTC
Labels: javascript
