### ISSUE TITLE
Deleting `workbench.statusBar.visible` doesn't update View menu

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14448] opened 2016-10-25 16:00 UTC
While testing #14015
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Set `workbench.statusBar.visible` to false in `settings.json`.
2. Delete it, hit save.
3. Status Bar is shown
4. View menu still has "Show status bar" action (which actually hides status bar if clicked)

**Comment by octref** [comment] 2016-10-25 16:21
Can't repro on Linux.

**Comment by rebornix** [comment] 2016-10-25 18:07
Can not repro on macOS.

**Comment by octref** [comment] 2016-10-25 18:18
Somehow I can't repro that on macOS either. But still can repro on Win. @rebornix can also repro on Win.

**Comment by bpasero** [comment] 2016-10-26 04:57
@octref @rebornix not reproducible for me, see:

![editors](https://cloud.githubusercontent.com/assets/900690/19713819/7daf6172-9b49-11e6-853e-3ac94eb20636.gif)

**Comment by octref** [comment] 2016-10-26 05:06
Interesting...Here is my Windows.

![config](https://cloud.githubusercontent.com/assets/4033249/19713943/f49a6854-9afe-11e6-87b9-c40a365b2335.gif)

**Comment by bpasero** [comment] 2016-10-26 07:44
@octref I speculate this is file events being delivered slowly, if you wait a bit longer (5 seconds), does it reproduce then? The menu only updates after it got the file event for the change in settings.json.

**Comment by octref** [comment] 2016-10-26 07:49
Waited 20 sec, still repro. And I made sure to press Ctrl+S multiple times.
Not only that, still "Show Status Bar" + status bar visible after restart.

**Comment by bpasero** [comment] 2016-10-26 08:38
Since I cannot reproduce I close this until further info / debugging can be provided.

**Comment by octref** [comment] 2016-11-04 22:07
@bpasero 
I can reliably repro on macOS by

- Rename `/Users/octref/Library/Application Support/code-oss-dev`
- Build and run from master

**Comment by bpasero** [comment] 2016-11-05 07:01
The key thing here is to only have that setting in `settings.json` and nothing else 👍

**Closed** 2016-11-07 06:59 UTC
Labels: bug
