### ISSUE TITLE
Forced strikethrough on the word 'name' in console.log statement

### ISSUE THREAD

**Issue by rcfoli** [microsoft/vscode#117392] opened 2021-02-23 13:36 UTC
BUG

When I type this code into MY vs code:

const name = 'Roger'
console.log(name)

When I type that code into MY vs code, vs code forces the word 'name' in the console.log statement to have a strike through. It only happens with the word 'name'. I can type any other word and no strikethrough.

Now, even though this happens, it still prints the output fine. So the output for the above code in my vs code is:

Roger 

So the statement prints to the console fine, but I dont understand why only MY vs code is bahaving this way. I am the only student in the class with this problem and the teacher was unable to reproduce my problem in their mac vs code. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.34GB free)|
|Process Argv|--crash-reporter-id 114602c5-cb15-4f19-beaa-bd8f41681a75|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-02-23 13:38
Try using the Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by IllusionMH** [comment] 2021-02-23 13:57
/duplicate of #114725 and related to https://github.com/microsoft/TypeScript/issues/18433

**Closed** 2021-02-23 13:58 UTC
Labels: *duplicate
