### ISSUE TITLE
使用vscode打开java文件出现：窗口出现故障问题

### ISSUE THREAD

**Issue by chengfengli** [microsoft/vscode#77565] opened 2019-07-18 09:48 UTC
Issue Type: <b>Bug</b>

使用vscode打开一个java项目，再打开一个java文件

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by byyxx128** [comment] 2019-07-18 19:10
1. Do not report the same issue more than once. You can edit the existed one, or you should close the old issue if you need to open a new one. (As both of your issues are not in English, you may need to close all and open a new one.)
不要重复报告问题。两中文的杵在那太扎眼了……
2. English description with detailed steps to reproduce please. You can also attach a screenshot if necessary. (You also need to `Configure Display Language` as `en` temporarily before you take a screenshot.)
用英语，要详细步骤，并给出必要的截图。截图前临时把界面改为英文。

**Comment by mjbvz** [comment] 2019-07-18 21:30
Duplicate of #77564

**Closed by mjbvz** 2019-07-18 21:30 UTC
