### ISSUE TITLE
Extension package.json shows phantom errors until window reload

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#120666] opened 2021-04-06 20:45 UTC
### Issue Type: **Bug**

When editing package.json for an extension project, VS Code shows phantom errors until the window is reloaded. Below are a screenshot of one of the phantom errors, and a video depicting the behavior.

### Steps to Reproduce

1. Create a new extension with `yo code`
2. Open the extension folder in VS Code
3. Edit package.json; observe phantom errors
4. Reload window; phantom errors are gone

<img width="453" alt="Screenshot 2021-04-06 at 3 41 55 PM" src="https://user-images.githubusercontent.com/8371943/113775973-06c73200-96ef-11eb-96ae-3a5324a4daf7.png">

https://user-images.githubusercontent.com/8371943/113775983-09298c00-96ef-11eb-8130-533c009bd2fa.mp4

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 8a1dca50-bfd2-4ed7-8721-07dc12b8f52d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
Bookmarks|ale|13.0.4
npm-intellisense|chr|1.3.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.19
vscode-html-css|ecm|1.10.2
graphviz-preview|EFa|1.3.3
vscode-npm-script|eg2|0.3.19
lex-flex-yacc-bison|fau|0.0.3
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
vscode-mysql|for|0.4.0
shell-format|fox|7.0.1
triggertaskonsave|Gru|0.2.17
reg|ion|1.0.2
latex-workshop|Jam|8.16.1
mediawiki|jas|0.0.4
swift|Kas|0.2.0
favorites|kdc|2.4.5
logos|NSE|0.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
syntax-project-pbxproj|mar|0.1.3
perl-debug|mor|0.6.3
python|ms-|2021.2.633441544
jupyter|ms-|2021.2.603412351
cpptools|ms-|1.2.2
psi-header|psi|1.15.1
vscode-yaml|red|0.17.0
perl|ric|2.2.0
vscode-paste-and-indent|Rub|0.0.8
vscode-autohotkey|sle|0.2.2
tmlanguage|Tog|0.9.0
clang-format|xav|1.9.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by aeschli** [comment] 2021-04-07 13:37
Duplicate of Togusa09/vscode-tmlanguage#24

You have to uninstall the tmlanguage extension.

**Closed by aeschli** 2021-04-07 13:37 UTC

**Comment by NSExceptional** [comment] 2021-04-07 14:18
Wouldn't uninstalling the extension break autocomplete? If so, that's not a fix… that said, if it's not being maintained anymore… :/

**Comment by aeschli** [comment] 2021-04-07 14:54
Not sure what the extension all does, but I think it's syntax highlighting and validation for tmLanguage files and some commands.
The issue has been open for a long time so I'm afraid the extension is not maintained.
