### ISSUE TITLE
Dropdown Choice Markdown Not Working

### ISSUE THREAD

**Issue by SeaDude** [microsoft/vscode#144425] opened 2022-03-04 17:39 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: Windows 10

Steps to Reproduce:

**1. Create a Markdown snippet that includes dropdown choices:**
- **Example:** See the `STATUS` below where `TODO,WAITING,IN PROGRESS,DONE` are dropdown choices

```
"TODO": {
        "prefix": "stodo",
	"body": [
	        "- [ ] ${1:Enter Task}",
		"- **STATUS:**      ${2|TODO,WAITING,IN PROGRESS,DONE|}",
		"- **PRIORITY:**    ${3|HIGH,MEDIUM,LOW|}"
		],
	"description": "Capture new TODO"
}
```

**2. Execute the snippet. Notice that what typically was a dropdown choice now says "`Loading`"**

![image](https://user-images.githubusercontent.com/8636973/156813987-2c3343a3-2472-4d05-9983-100740495d09.png)

**Comment by ArturoDent** [comment] 2022-03-04 21:07
For me the choices are filling up with other suggestions.  The alternate choices never appear nor does "loading".

**Comment by SeaDude** [comment] 2022-03-04 22:38
@ArturoDent , I appreciate you checking. It must be one of my extensions. I'll determine which one then address separately.

**Comment by ArturoDent** [comment] 2022-03-04 23:04
I actually meant other suggestions, like text replacements, other snippets, etc. but not the intended `choices`.  So it doesn't work for me either.

**Comment by SeaDude** [comment] 2022-03-05 00:44
Oh excuse me. Thanks for clarifying. Looks more like a real bug then.

**Comment by Samyak-Bumb** [comment] 2022-03-05 04:40
There should be more importance for custom snippets not for the extension.

(
**1st Custom Snippets** should be Loaded & **then Extension Snippets**
)

**Comment by jrieken** [comment] 2022-03-05 08:40
/duplicate of https://github.com/microsoft/vscode/issues/144362

**Closed** 2022-03-05 08:40 UTC
Labels: *duplicate, new release
