### ISSUE TITLE
Delete doesn't remove files in tree but search instead

### ISSUE THREAD

**Issue by jurosh** [microsoft/vscode#76581] opened 2019-07-04 09:40 UTC
- VSCode Version: 1.36.0
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Open project with some files in folder
2. In the left sidebar see files
3. Click on file and hit DELETE key

Instead it's trying to find "DELETE" text in opened files. 
![image](https://user-images.githubusercontent.com/1630137/60656803-73453b00-9e50-11e9-89b6-abe229c233b1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2019-07-04 09:51
/duplicate of https://github.com/microsoft/vscode/issues/76514

**Closed** 2019-07-04 09:51 UTC
Labels: *duplicate, new release
