### ISSUE TITLE
No extension found.

### ISSUE THREAD

**Issue by Mr-sxz** [Microsoft/vscode#57918] opened 2018-09-05 01:15 UTC
![image](https://user-images.githubusercontent.com/28703965/45065512-3b644e80-b0ec-11e8-9971-e46387cac71a.png)

**Comment by programkode** [comment] 2018-09-05 02:16
See #57851

**Comment by mjbvz** [comment] 2018-09-05 02:36
Duplicate of #57851

**Closed by mjbvz** 2018-09-05 02:36 UTC
Labels: extensions
