### ISSUE TITLE
Create folder, undo creation of it, redo creation of it requires two redo operations

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#111692] opened 2020-12-02 02:05 UTC
Testing #111015 related to #111640 but with unexpected behavior

As you can see, I create a folder, 'red'
Ctrl Z undoes the creation of it so it disappears
Ctrl Y should redo the creation of it _but instead recreates a folder I had deleted earlier, 'myfolder'_
Ctrl Y again re-creates 'red'
![recording (54)](https://user-images.githubusercontent.com/29464607/100818977-157ba080-3400-11eb-8ce5-c2607b9a512d.gif)

**Comment by isidorn** [comment] 2020-12-02 09:21
Assigning to November to investigate more

**Comment by isidorn** [comment] 2020-12-02 13:44
I just tried this out and I can not reproduce this.
@meganrogge can you repro with latest code out of source since I pushed some fixes which could potentially fix this?
If you can reproduce can you please try to give more exact steps since these do not work for me?

Thanks!

**Comment by meganrogge** [comment] 2020-12-02 17:19
can't reproduce, so think your fixes might have resolved this.

**Comment by isidorn** [comment] 2020-12-02 17:21
Okey, thanks for letting me know. For now closing, and if you still see this we can reopen.

**Closed by isidorn** 2020-12-02 17:21 UTC
Labels: file-explorer, needs more info, undo-redo
