### ISSUE TITLE
Please add an option to choose the code folding method

### ISSUE THREAD

**Issue by Hari-KrishnanV** [Microsoft/vscode#47630] opened 2018-04-11 04:35 UTC
Issue Type: <b>**Feature Request**</b>

The code folding in the release 1.22.1 is different from the previous releases. It no longer supports selecting the folded code and then apply some intendation, just like pressing 'tab' on a folded line applies tab only for the first line of the code segment. In the previous releases the closing brackets were shown with the folded code segment just like,
              
              function testFunction(){...
              }
But this is not available in the release 1.22.1.
It will be helpeful if there is a feature to select the folding method.
Thanks for keeping the vs code improving

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Hari-KrishnanV** [comment] 2018-04-11 09:54
I don't know how to register a new feature request. I am sorry if this is not the proper way to do it :)

**Comment by mjbvz** [comment] 2018-04-11 17:57
Duplicate of #47240 

To go back to indentation folding, set: `"editor.foldingStrategy": "indentation"`. You can set this for a specific language using:

```json
"[javascript]": {
    "editor.foldingStrategy": "indentation"
}
```

**Closed by mjbvz** 2018-04-11 17:57 UTC
Labels: new release
