### ISSUE TITLE
Unable to debug Hello World extension in Insiders 1.52 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#110170] opened 2020-11-08 07:06 UTC
After upgrading to 1.52 I cannot seem to debug an extension in the extension host anymore. Uninstalling and reinstalling doesn't work. I repro this in 1.52 on Windows 10 and macOS 10.14. I work on the [Python extension](https://github.com/microsoft/vscode-python) and cannot debug that either. Happy to provide any logs if you'll tell me where to look for them!

Version: 1.52.0-insider (user setup)
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:43:01.017Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042 & Darwin x64 18.7.0

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample and open it in Insiders 1.52.
2. Select the Run Extension launch configuration and start debugging.
3. Extension host never launches. The blue progress indicator under the debug configuration dropdown spins forever.

![launchextension](https://user-images.githubusercontent.com/30305945/98459203-64118400-214d-11eb-878b-d5e559e81147.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2020-11-09 09:33
@joyceerhl I cannot reproduce the problems you are seeing. I tried VS Code Insider 1.52 both on macOS and Windows, but debugging works just fine.

It is possible that your issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by joyceerhl** [comment] 2020-11-09 17:18
Hi @weinand, yes this was without extensions (the screenshot above has the popup in the bottom right saying that extensions have been temporarily disabled). If it helps, I see the following in the dev console: 

![image](https://user-images.githubusercontent.com/30305945/98573657-f740db80-226b-11eb-820c-9a8b1dd02f7c.png)

The error is identical to the one here: https://github.com/microsoft/vscode/issues/108610

After adding the following to my settings.json, I can debug extensions again:
>     "npm.packageManager": "npm",

**Comment by IanMatthewHuff** [comment] 2020-11-09 17:27
To drop a note here. I'm on the same team as Joyce I had the same error on the same workspace with the symptom of being unable to load my build tasks. Manually setting npm manager also fixed it for me.

**Comment by weinand** [comment] 2020-11-09 21:40
@alexr00 this issue seems to be npm extension related.

**Comment by alexr00** [comment] 2020-11-10 10:21
Fixed by https://github.com/microsoft/vscode/commit/256066f94c87d599087e2bdc402813bf827de478 already.

**Closed by alexr00** 2020-11-10 10:21 UTC
