### ISSUE TITLE
PROBLEMS filter line edit misses standard navigation shortcuts (HOME/END)

### ISSUE THREAD

**Issue by schaurichr** [microsoft/vscode#199637] opened 2023-11-30 07:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Suse SLES 15 SP5

This bug report describes a problem regarding the PROBLEMS view (workbench.actions.view.problems)

Steps to Reproduce:
1. write a filter string into the PROBLEMS filter line edit
![image](https://github.com/microsoft/vscode/assets/150606293/60feec63-7554-4270-bf56-22755b40c508)
2. Press the HOME button
3. Nothing happens
Expected behavior: the Cursor moves to the beginning of the string

Steps to Reproduce:
1. write a filter string into the PROBLEMS filter line edit
2. move the cursor to the beginning of the string
3. Press the END button
4. The input focus leaves the line edit (and is now on the 'View as Table' button)
Expected behavior: the Cursor moves to the end to the string

**Comment by sandy081** [comment] 2023-11-30 08:56
It works for me on Mac with cmd+left and cmd+right keys. Could be keyboard related, hence assigning to @ulugbekna

**Comment by ulugbekna** [comment] 2023-12-05 10:36
duplicate of https://github.com/microsoft/vscode/issues/180869

**Closed by ulugbekna** 2023-12-05 10:36 UTC
