### ISSUE TITLE
tsserver causing 100% cpu usage (MacOS)

### ISSUE THREAD

**Issue by andrew-r-king** [Microsoft/vscode#71746] opened 2019-04-04 23:34 UTC
Issue Type: <b>Bug</b>

Experiencing this after the latest VS Code Update (1.33.0) on MacOS (Mojave).

Just merely opening a .jsx file spawned a tsserver process that pegged the cpu at 100%. This continued for about an hour until I finally disabled the built-in JS/TS extension.

"ps aux | grep (PID of process)" yields:

(PID) 101.2  1.5  5775252 247640   ??  R     3:58PM   0:22.29 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/jf/lcpzpnrj18j12nh80mpby5640000gn/T/vscode-typescript/tscancellation-5c45dea462f9c216c776.tmp* --locale en --noGetErrOnBackgroundUpdate

These were the extension settings I was using:

  "javascript.autoClosingTags": false,
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "javascript.updateImportsOnFileMove.enabled": "always",

  "typescript.autoClosingTags": false,
  "typescript.surveys.enabled": false,
  "typescript.updateImportsOnFileMove.enabled": "always",

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
applescript|idl|0.14.2
vscode-icon-theme|jtl|1.6.5
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
cpptools|ms-|0.22.1
shader|sle|1.1.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-04-05 00:21
Can you please share the jsx files or more information about your project

**Comment by andrew-r-king** [comment] 2019-04-05 01:36
The most basic React/styled-components .jsx file triggers it:

```
import React from "react";
import styled from "styled-components";

export default (props) => {
    const Section = styled.section`
        background-color: #000;
    `;

    return (
        <Section>
            <a href="http://www.google.com">Google</a>
        </Section>
    );
};
```

**Comment by mjbvz** [comment] 2019-04-05 01:43
Looks like https://github.com/Microsoft/TypeScript/issues/30663

@weswigham When are the new styled component definitions going to be published. A lot of VS Code users are going to hit this through automatic type acquisition

**Comment by hex20** [comment] 2019-04-05 03:12
I'm seeing the same issue
```
102.0  3.7  5582432 312744   ??  R     2:07pm   2:53.94 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/wl/7zyj_dlj3jb17znt889_ndbh0000gn/T/vscode-typescript/tscancellation-f1c61d869c66684734c1.tmp* --globalPlugins typescript-styled-plugin,@divyenduz/ts-graphql-plugin --pluginProbeLocations /Users/angus/.vscode/extensions/jpoissonnier.vscode-styled-components-0.0.26,/Users/angus/.vscode/extensions/prisma.vscode-graphql-0.1.7 --locale en --noGetErrOnBackgroundUpdate
```

**Comment by ScreamZ** [comment] 2019-04-05 08:55
Seems related to new version that use TS 3.4.1, seems to get better when switching to 3.3.3333 in node modules

**Comment by mjbvz** [comment] 2019-04-05 22:42
Duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

If that doesn't solve the issue for you, please open a new issue

**Closed by mjbvz** 2019-04-05 22:42 UTC
Labels: javascript, new release, perf, upstream
