### ISSUE TITLE
JavaScript go to configuration goes to wrong config

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21212] opened 2017-02-22 21:34 UTC
#21037

On following repo: https://github.com/gwtw/js-fibonacci-heap

Steps to reproduce:

1. JavaScript go to configuration, create jsconfig.json as `{}`
2. Copy `./jsconfig.json` to `./test/jsconfig.json`
3. Open `./test/clear-test.js`
4. JavaScript go to configuration, `./jsconfig.json` is opened. I expected `./test/jsconfig.json` to be opened.

**Comment by mjbvz** [comment] 2017-02-23 01:38
I believe that the root cause is that the project has to be reloaded after the jsconfig is changed or moved. This is something we don't handle very well currently, and this command reveals the bug. As far as the loaded version of TypeScript know,`./jsconfig.json` still exists and is used to configure the project

**Comment by mjbvz** [comment] 2017-05-22 19:02
I looked into this a bit more and believe it is a TS issue: https://github.com/Microsoft/TypeScript/issues/16002

Closing as upstream

**Closed by mjbvz** 2017-05-22 19:02 UTC
Labels: bug, javascript, typescript, upstream
