### ISSUE TITLE
Can't drag Visual Studio Code to the secondary taskbar

### ISSUE THREAD

**Issue by vyskoczilova** [Microsoft/vscode#60480] opened 2018-10-10 09:04 UTC
I have two monitors, for extending a standard taskbar I use super simple [Dual Monitor Tool](https://sourceforge.net/projects/dualmonitortool/) app. For many years. With the latest update, I'm able to drag the VSC from one screen to another, however, the taskbar icon remains on the main taskbar, not on the active screen. Do you know what has been changed and how to fix it? It drives me crazy. All other programs I use behaves correctly, just [Franz ](https://meetfranz.com/)didn't from it's beginning, but VSC worked well for years.

- VSCode Version: 1.28.0 (user setup)
- OS Version: Windows 7 Pro

Steps to Reproduce:

1. Have two screens
2. Extend taskbar with Dual Monitor Tool
3. Move VSC to another screen

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment] 2018-10-10 09:17
duplicate of #10121

**Comment by scriptcoded** [comment] 2018-10-10 12:47
@egamma I'd suggest you open this again. If I understood the OP correctly, they're saying that the icon in the Windows taskbar doesn't move along to the correct monitor. #10121 is about detaching windows from VS Code.

**Comment by egamma** [comment] 2018-10-10 19:49
@scriptcoded good catch.

**Comment by bpasero** [comment] 2018-10-11 05:04
This sounds like an issue of the OS or window management that we very likely have no control about. Closing.

**Closed by bpasero** 2018-10-11 05:04 UTC

**Comment by vyskoczilova** [comment] 2018-10-13 20:39
@bpasero On all previous version of VSC it worked normally, I use it for more than a year and a half, workflow still the same. Something has to change in the latest release.
