### ISSUE TITLE
Add support for relative path variables in settings.json to allow portable toolchains.

### ISSUE THREAD

**Issue by Protocol-IRK** [Microsoft/vscode#58845] opened 2018-09-17 23:06 UTC
*Disclaimer - Please don't shoot me, new user to VSCode. I may have missed a setting, also prominently a windows user 7/10*

Please could I request the addition of two variables that are read-only and accessible by settings.json. 

Pseudo names:

%root_drive% - root drive letter/label
%executed_form_directory% - VSCode file path from which code.exe is currently executed from. 

Hopefully obvious by their names. This would provide settings.json the ability to construct a file path regardless of change to letter/label. The use-case would be using a portable storage device such as a USB memory stick (think portableapps.com), allowing the user to store their other tools such as Git, Cmder and gdb, based from the root drive letter, or contained within the installed directory. Have their default debugger within VSCode's root directory.

On computer X the USB assigned drive letting is I:
On computer Y the USB assigned drive letting is T:

Two settings that stand out and would benefit from this would be: "terminal.external.windowsExec" && terminal.integrated.shell.windows" as the user may not have permissions to access the default cmd.exe or may wish to override and use Git Bash/ Mingw for instance. 

e.g.
"terminal.external.windowsExec" : " %drive_root% \ Cmder \ Cmder.exe"
*spaces added to path to avoid any emojii icons.

I have read a few pages of documentation such as https://code.visualstudio.com/docs/editor/portable and https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration (hardcoded file paths) I found no reference to this possibility of having relative paths. Either that or I am overlooking something being a fairly new user.

**Comment by sandy081** [comment] 2018-09-20 13:13
Duplicate of #2809

**Closed by sandy081** 2018-09-20 13:13 UTC
Labels: config, feature-request

**Comment by botmtl** [comment] 2018-10-02 20:36
@sandy081 Could you point us to a pr or a duplicate thread to follow along please.  By closing both /isssue/58845 (by marking as a duplicate of 2809) and also closing  /issue/2809 (by saying it's a duplicate of 58845), it's leaving anyone trying to find out where this has been implemented totally in the dark.

**Comment by sandy081** [comment] 2018-10-03 06:18
@botmtl #2809 is open and not closed as duplicate.
