### ISSUE TITLE
settings.json reverted and now contains superfluous comma after updating to 1.7.1

### ISSUE THREAD

**Issue by atisinger** [Microsoft/vscode#15186] opened 2016-11-08 16:35 UTC
- VSCode Version: 1.7.1
- OS Version: Windows 10 Pro

I was prompted to update VS Code, did the update and when it finished and re-opened Code none of my previous settings carried over. The Explorer side-bar was moved back to the left side (previously had it on the right), custom font type and size were reverted to defaults, etc.

I went to View > Move sidebar right and received the error:

Unable to write settings, Please open User Settings to correct errors/warnings in the file and try again.

I went to File > Preferences > User Settings and two settings.json files open, one for Default settings and one for User settings. One error shows in the error window for the user settings.json file:

"Property expected (5, 1)"

the settings.json file looks like this:

```
// Place your settings in this file to overwrite the default settings
{
    	// Controls the font size.
	"editor.fontSize": 18,
}
```

I was able to fix the issue by removing the comma from the end of line 4, but this should not have been there after the update anyway.

**Comment by bpasero** [comment] 2016-11-08 18:37
@atisinger the explorer positioning setting changed in 1.7, so it seems unrelated to the issue you describe. Can you recap how many entries you had in settings? Are you sure that settings where lost?

**Comment by atisinger** [comment] 2016-11-08 19:46
I can't be sure now, but I think I only had 3 custom settings in my user setttings file: fontFamily, fontSize and tabSize. I am sure settings were lost in the upgrade though. I do not know what version I was on prior to upgrade. Perhaps it was a lower version than 1.7. The main thing that caused me issue was that extra comma in the settings.json that was preventing me from changing other settings through the menus.

**Comment by bpasero** [comment] 2016-11-09 05:29
@atisinger yeah that is mysterious. do you have any extensions installed?

**Comment by bpasero** [comment] 2016-11-16 18:08
@atisinger ping

**Comment by atisinger** [comment] 2016-11-16 18:22
I have no extensions installed.

**Comment by bpasero** [comment] 2016-11-17 05:42
I am closing this due to the lack of information how to reproduce and we did not hear from any other user. Please report back if this ever happens again.

**Closed by bpasero** 2016-11-17 05:42 UTC
Labels: needs more info

**Comment by edvm** [comment] 2016-12-16 13:21
I have this same issue when updating to 1.8. Here is my user settings:

`
// Place your settings in this file to overwrite the default settings
{
 
    "python.pythonPath": "/home/edvm/.virtualenvs/tero-saas/bin/python",
 
    "python.linting.pylintEnabled": false,

}
`

I also attach a screenshot, hope it helps! :) 
Thanks in advance, at every realease this editor is getting more and more cool! :)

![bug1](https://cloud.githubusercontent.com/assets/689275/21264125/4ebe8f0c-c379-11e6-8a64-571c1a86f29e.png)

**Comment by VincentLeie** [comment] 2017-07-23 11:44
remove the last ","
