### ISSUE TITLE
Font Settings for Terminal Suggestions Not Applying in VS Code

### ISSUE THREAD

**Issue by zhiyue** [microsoft/vscode#212362] opened 2024-05-09 16:10 UTC
1. VS Code insiders, Windows 11, integrated PowerShell
2. Have "terminal.integrated.suggest.enabled": true in your settings
3. font settings:
![image](https://github.com/microsoft/vscode/assets/4208883/26706928-8462-4999-834c-967768433792)
![image](https://github.com/microsoft/vscode/assets/4208883/3470a577-3877-4630-8d44-c5c3bfc1e65d)
4. Type l, get `l`:
![image](https://github.com/microsoft/vscode/assets/4208883/2808317d-d6da-4e0a-bca4-5bbaf1687aac)

**Comment by cpendery** [comment] 2024-05-10 16:33
Duplicate of #210597

**Closed** 2024-05-13 15:41 UTC
