### ISSUE TITLE
Relative links do not work on task output terminal

### ISSUE THREAD

**Issue by dschaefer** [microsoft/vscode#69403] opened 2019-02-25 19:37 UTC
- VSCode Version: 1.31.1 (also seeing it when debugging master)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a task that runs in a directory other than the workspace folder and outputs a relative path from that directory
2. Try and click on the resulting link

This was fixed for normal terminals with #27107 but doesn't work with tasks. Firing it up under the debugger, I see that links are resolved before the the processCwd is registered with the link handler.

**Comment by dschaefer** [comment] 2019-02-25 20:06
Actually, digging deeper, I see that _onExit is called before the links are created. this._process is null when trying to get the cwd.

**Comment by dschaefer** [comment] 2019-02-25 20:11
So, yeah, the links get resolved before the process exits, but the call to getInitialCwd() happens after the process exits.

**Comment by alexr00** [comment] 2019-05-28 14:25
I can't reproduce this anymore. Looks like it was fixed by something else. My repro steps:
1. Open a folder that is at the same level as the VS Code repo folder.
2. Create this task:
        {
            "label": "TESTING",
            "type": "shell",
            "command": "echo",
            "args": ["src\\vs\\workbench\\contrib\\terminal\\browser\\terminal.ts"],
            "problemMatcher": [],
            "options": {
                "cwd": "d:\\repos\\microsoft\\vscode"
            }
        }
```
3. Run the task, then try the resulting link.

**Comment by rebornix** [comment] 2019-05-30 00:26
I can reproduce this issue on macOS with below task

```
{
            "label": "TESTING",
            "type": "shell",
            "command": "echo",
            "args": ["src/vs/workbench/contrib/terminal/browser/terminal.ts"],
            "problemMatcher": [],
            "options": {
            	"cwd": "/Users/penlv/code/vscode"
            }
},
```

**Comment by alexr00** [comment] 2019-06-05 13:34
@Tyriar this only reproduces on non-Windows. The issue is exactly as @dschaefer describes above. There is a race in the terminal process manager between listeners of `onReady` and the manager's `_onExit`. The process exits and `_onExit` is called before the listeners of `onReady` are called, which means that the terminal process is null by the time the  terminal instance tries to get the initial cwd.

**Closed** 2019-06-14 19:21 UTC
Labels: bug, integrated-terminal, tasks
