### ISSUE TITLE
Newest version occupy too much CPU

### ISSUE THREAD

**Issue by linxiangjun** [Microsoft/vscode#35872] opened 2017-10-09 06:43 UTC
- VSCode Version:1.17.0
- OS Version:Windows 10

Steps to Reproduce:

1.Open VSCode software
2.Two unknown .exe files called 'rg.exe' which occupy too mush CPU(more than 50%),When you close VSCode,It's will be release.This is only find in newest version,old version don't find this question.Please reply as soon as possible,Thanks.

**Comment by kybom** [comment] 2017-10-09 09:57
The same to you.
My os is Ubuntu 16.04.
VScode starts slowly, and occupies too much CPU.

**Comment by chrmarti** [comment] 2017-10-09 17:57
Duplicate of #35659

**Closed by chrmarti** 2017-10-09 17:57 UTC
Labels: new release, search
