### ISSUE TITLE
Run Build Task (CTRL + Shift +B) Slow to open drop down list

### ISSUE THREAD

**Issue by tcsmith** [Microsoft/vscode#63867] opened 2018-11-27 17:47 UTC
It takes between 5 to 10 seconds to open the dialog.
Prior to the latest update it was near instantaneous.

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Windows 10 Enterprise 10.0.15063

**Comment by alexr00** [comment] 2018-11-28 12:55
Duplicate of #63078

**Closed by alexr00** 2018-11-28 12:55 UTC
