### ISSUE TITLE
Odd search results when looking for newline `\n`

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#62199] opened 2018-10-30 20:56 UTC
- VSCode Version: 1.29 Insiders
- OS Version: Windows 10

Found when testing https://github.com/Microsoft/vscode/issues/62102

Steps to Reproduce:

1. Try a global search for `(\n)`

![image](https://user-images.githubusercontent.com/12818376/47750003-911c2980-dc4b-11e8-96e4-abc8ba3a739b.png)

**Comment by gregvanl** [comment] 2018-10-30 21:00
Also see odd line crunching:

![image](https://user-images.githubusercontent.com/12818376/47750201-1d2e5100-dc4c-11e8-8421-886f485c8239.png)

**Comment by gregvanl** [comment] 2018-10-30 21:07
Seems to be related to rendering text before the match.

![image](https://user-images.githubusercontent.com/12818376/47750652-1a802b80-dc4d-11e8-993d-ff564f81a964.png)

**Comment by roblourens** [comment] 2018-10-31 18:44
Dupe of #62186

**Closed by roblourens** 2018-10-31 18:44 UTC
Labels: insiders
