### ISSUE TITLE
In C language mode, code after '#if 0 // line comment' is colorized wrongly

### ISSUE THREAD

**Issue by Kazemachi4github** [microsoft/vscode#200301] opened 2023-12-08 02:52 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Win 10

Steps to Reproduce:

Try the code below in any file in C language mode: 
```c
     enum
     {
#if 0 // line comment after a blank/tab
        ENUM, // another troublesome line comment
#endif
      }

#define DEFA 1
#define DEFB 2
```
PS: I suppose it's related to the update in this year for I've tried a version published last year. Now I'm using C++ language mode instead, it works well.

**Comment by alexr00** [comment] 2023-12-11 10:14
Thanks @RedCMD! Duplicate of https://github.com/jeff-hykin/better-c-syntax/issues/4.

**Closed by alexr00** 2023-12-11 10:14 UTC
Labels: new release
