### ISSUE TITLE
Redo history is lost when saving HTML file and FormatOnSave results in no changes

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/vscode#149941] opened 2022-05-19 14:25 UTC
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.67.2
- Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
- Date: 2022-05-17T18:20:04.972Z (1 day ago)
- Electron: 17.4.1
- Chromium: 98.0.4758.141
- Node.js: 16.13.0
- V8: 9.8.177.13-electron.0
- OS: Darwin arm64 21.4.0

Steps to Reproduce:

1. Set `"files.insertFinalNewline": true`
2. Create and save a HTML file with some content => a newline is ensured at the end of the file, this is good
3. Make a change and save
4. Undo once => nothing happens, this is bad
5. Undo a second time => the changes are undone
6. Save the undone changes
7. Try to redo => nothing happens, there's no redo history

Then change the language mode from HTML to Plain Text and repeat the steps: step 5 is not needed because only one undo is needed, which is correct, and step 7 succeeds because the redo history is kept after saving.

I'm used to being able to undo, save, and then redo, when any automatic formatting that occurs results in no changes (i.e. the file is properly formatted in all stages of the undo/redo history). I've been doing this consistently for the past 2-3 years, even with editorconfig and rubocop. I rely a lot on my redo history.

Seems like the bug is that an extra stage is added into the undo history when `files.insertFinalNewline` applies to the file, even though it results in no differences. Also occurs when `files.insertFinalNewline` is turned off and I have editorconfig `insert_final_newline = true` and extensions enabled; the reproduction steps above where written with extensions disabled, but the effect is the same: an extra stage added to the undo/redo history that contains no changes, so shouldn't be there.

Cheers, H =)

**Comment by bpasero** [comment] 2022-06-07 12:22
Code is here:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L121-L137

I am not sure if I have to do something special to avoid a no-op edit messing with the undo/redo history, sounds like a editor issue to me.

@alexdima @hediet thoughts?

**Comment by alexdima** [comment] 2022-06-10 13:28
@bpasero Can you reproduce? 
@henrahmagix I cannot reproduce. At step 4, undo works as expected for me:

https://user-images.githubusercontent.com/5047891/173075887-6372a6db-0409-4a65-8201-76b51be27bf1.mp4

**Comment by bpasero** [comment] 2022-06-10 15:13
Maybe there is an extension involved?

Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by henrahmagix** [comment] 2022-06-10 15:28
@bpasero Is that question to me? When I originally replicated this, I did so without extensions. But I did it via command palette "Developer: Reload With Extensions Disabled.

**Comment by henrahmagix** [comment] 2022-06-10 15:45
Got auto-upgraded to 1.68.0 and now can't replicate

**Comment by henrahmagix** [comment] 2022-06-10 15:51
Ah wait, sorry @bpasero, I can now replicate it when I also have `"editor.formatOnSave": true` and all extensions disabled.

https://user-images.githubusercontent.com/1429026/173103780-08c50290-fd29-415b-b3c9-a05999d08370.mov

**Comment by henrahmagix** [comment] 2022-06-10 15:52
Sorry @bpasero please reopen =)

**Comment by bpasero** [comment] 2022-06-11 07:42
I can reproduce when both these settings are enabled:
* `"files.insertFinalNewline": true`
* `"editor.formatOnSave": true`

**Steps:**
* empty window, fresh user data dir
* apply those settings
* new `index.html` file
* first line type something and save
* type something again at the end of line and save
* undo
 
=> 🐛 nothing happens

This seems to require both format on save and adding final new line.

**Comment by alexdima** [comment] 2022-06-15 12:19
Well, it looks we have a case of two features fighting it off :). When I remove `"files.insertFinalNewline": true` I can notice that on each save the last line is removed.

So here's what's going on: 
* **the formatter save participant deletes the last line**
* then, the insert final new line save participant **reinserts it**
* both these edits are grouped in a single undo step because we don't insert undo stops between save participants

Which effectively gives the illusion that the undo doesn't really do anything.

**Comment by alexdima** [comment] 2022-06-15 12:21
@jrieken @aeschli Do you have any thoughts what to do in this case? I can see a simple solution if the formatter would respect the setting `"files.insertFinalNewline"` and not constantly delete the last line. What do you think?

**Comment by aeschli** [comment] 2022-06-17 09:42
The workaround is to use the HTML setting `html.format.endWithNewline`. Setting that will make the issue go away.
I agree that it would be better to remove that setting and use "files.insertFinalNewline" instead. Working on a PR.

**Comment by alexdima** [comment] 2022-06-17 13:01
Fixed by https://github.com/microsoft/vscode/pull/152446

**Closed by alexdima** 2022-06-17 13:01 UTC
Labels: bug, confirmed, undo-redo
