### ISSUE TITLE
Icon alignment in directory tree on mac

### ISSUE THREAD

**Issue by neutraltone** [Microsoft/vscode#11831] opened 2016-09-10 15:34 UTC
- VSCode Version: 1.5.1 (1.5.1)
- OS Version: OS X El Capitan 10.11.6 (15G31)

Steps to Reproduce:

1. Launch a project with many directories in Visual Studio Code and enable one of the icon themes (in this case Seti)
2. Expand directories in the right hand side page, noticed how the files seem to be indented too much of the left hand side.

Screenshot of Error:
![image](https://cloud.githubusercontent.com/assets/1080928/18411690/6225cbe2-7774-11e6-945d-664f8d5f9d09.png)

Screenshot from Windows for comparison:
![image](https://cloud.githubusercontent.com/assets/1080928/18411696/7ada988e-7774-11e6-9069-025b88d3dcea.png)

**Comment by glen-84** [comment] 2016-09-11 16:18
Related: #11762

**Comment by bpasero** [comment] 2016-09-12 15:27
@neutraltone so you say the bug is with the single _main.scss inside vendor that is indented too much?

**Comment by neutraltone** [comment] 2016-09-13 08:51
@bpasero yep, and also the `*.scss` files within the `js` and `components` directory as well. if you look at the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1080928/18467307/62ca5bf6-7997-11e6-8de2-b1121f6671be.png)

One would assume that the `scripts.min.js` and `scripts.js.maps` files are in the vendor directory. Same goes for the `index.html` and other files, at fist glance they look like they are in the `scripts` directory.

**Comment by bpasero** [comment] 2016-09-13 09:00
@neutraltone can you use developer tools (from help menu) and inspect the element that is pushed so far to see what CSS rule is pushing it?

**Comment by neutraltone** [comment] 2016-09-13 09:32
@bpasero It appears to be `padding-left: 22px;` on `.explorer-item.file-icon` in `wordbench.main.css:4`. Turning this rule off aligns the icons perfectly.

![image](https://cloud.githubusercontent.com/assets/1080928/18468641/b77cdcbe-799c-11e6-8389-c3a2cad474eb.png)

**Comment by bpasero** [comment] 2016-09-13 09:43
@neutraltone and for the same icon below that looks nicely aligned? I would assume the padding is always there for all icons...

**Comment by neutraltone** [comment] 2016-09-13 09:48
@bpasero The icons which appear nicely aligned are actually children of the parent directory. In the case of `main.scss` from the original screenshot, that is actually the child of the `scss` directory. So the alignment is still broken causing it to look like a child of the `vendor` directory. Is that the one you meant?

**Comment by bpasero** [comment] 2016-09-13 10:01
@neutraltone I mean this one (cannot explain):

![image](https://cloud.githubusercontent.com/assets/900690/18469784/bd6cd4c8-79a9-11e6-9328-539dfcfd7426.png)

**Comment by neutraltone** [comment] 2016-09-13 10:06
Ahh yes, `main.scss` actually resides in the `scss` directory as per this screenshot:

![image](https://cloud.githubusercontent.com/assets/1080928/18469894/d9a9c3d8-79a1-11e6-9fe0-dfdbd35bdb31.png)

It actually has the same rules as above and again is the `padding-left: 22px` which is causing the issue. See screenshots:

![image](https://cloud.githubusercontent.com/assets/1080928/18469918/f7f1ece4-79a1-11e6-95ac-a7bea6dc55bf.png)

![image](https://cloud.githubusercontent.com/assets/1080928/18469933/055e4238-79a2-11e6-8319-04b64d21726b.png)

**Comment by bpasero** [comment] 2016-09-13 10:17
@neutraltone are you using the vscode-icons extension? Maybe that one conflicts with our built in icons support.

**Comment by neutraltone** [comment] 2016-09-13 10:21
@bpasero Ahh this might be causing the issue. I did have it installed but removed it around the same time as the current update.

I've just checked my `~/.vscode/extensions` directory and it's appearing there. Could it have placed any files elsewhere which could be causing a conflict?

**Comment by bpasero** [comment] 2016-09-13 12:07
@neutraltone can you uninstall and reinstall VS Code to see if you had vscode-icons leftover?

**Comment by neutraltone** [comment] 2016-09-13 13:05
@bpasero I have removed the app from the applications folder and downloaded a fresh copy. I also removed my `~/.vscode` folder but the problem still persists. Could some common files as live elsewhere?

**Comment by bpasero** [comment] 2016-09-13 13:18
@neutraltone is that workspace possible to share with me? So that I can try to reproduce?

**Comment by neutraltone** [comment] 2016-09-13 13:19
@bpasero Actually, I was wrong, things do appear to have changed as the folder icons have now disappeared. Only thing is the alignment still doesn't seem to quite right. `main.scss` still looks like it is part for the un-expanded vendor folder:

![image](https://cloud.githubusercontent.com/assets/1080928/18474981/939d95a2-79bc-11e6-891f-10fe9c14c024.png)

This is why I was getting confused. The previous offending style has also gone but this is also now the same as this issue #11762.

**Comment by bpasero** [comment] 2016-09-13 13:20
@neutraltone yes, closing as duplicate of https://github.com/Microsoft/vscode/issues/11762

Please do NOT install vscode-icons extension in the future, thanks.

**Closed by bpasero** 2016-09-13 13:20 UTC
Labels: needs more info, themes
