### ISSUE TITLE
More types for CompletionItemKind enum

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#2628] opened 2016-02-02 03:11 UTC
And then add an appropriate icon to display in completion lists.  The PowerShellEditorServices extension helps the user auto-complete paths.  When you have a list of folder contents it is very helpful to have an icon to distinguish between files and folders.

Compare this UI from VSCode for path completion:
![vscodeintellisenseforfolders](https://cloud.githubusercontent.com/assets/5177512/12738637/c2f55676-c91f-11e5-9b00-a076ccc90701.png)

To the UI from PowerShell ISE:
![iseintellisenseforfolders](https://cloud.githubusercontent.com/assets/5177512/12738642/ce19387e-c91f-11e5-9b43-6e60ce773399.png)
Having a nice, flat icon for a folder would be very nice to show in this list.

**Comment by daviwil** [comment] 2016-02-02 04:18
Agreed, this would be great to have!

**Comment by jrieken** [comment] 2016-02-02 07:48
@bgashler1 fyi

**Comment by jrieken** [comment] 2016-03-16 13:48
related #4201

**Comment by jrieken** [comment] 2016-05-25 11:18
* Folder 
* Directory
* Event (#5407)

**Comment by Jerry-Hong** [comment] 2016-07-17 05:49
@jrieken Can I use it now?

**Comment by jrieken** [comment] 2016-07-20 08:23
@Jerry-Hong If by `it` you mean the currently existing `ComplemtionItemKind` member "yes". Otherwise you have to wait until this issue is resolved ;-)

**Comment by DustinCampbell** [comment] 2017-01-24 21:37
Looking forward to this.

**Comment by DustinCampbell** [comment] 2017-01-24 21:53
And FWIW, it'd be great to get several more of the icons from VS. We use many of these for C# in VS completion and finding analogs in VS Code is always a bit of a compromise.

Here are icons for which there is no good representation in VS Code's CompletionItemKind:

* Event
* Struct
* Delegate
* Extension method
* Constant
* Enum member
* Operator
* Type parameter
* Versions of all icons with accessibility overlays (e.g. private, protected, internal, etc.)

Here's the basic list of what we use in completion: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Completion/CompletionTags.cs

This is the level of detail we use for Visual Studio: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs#L14-L169

It'd be great if I could replicate the icons in VS Code.

**Comment by jrieken** [comment] 2017-01-25 08:46
Yeah, our plan is to allow for custom icons

**Comment by DustinCampbell** [comment] 2017-01-25 14:31
cc @chrisdias

_Please excuse the sarcasm in my response below @jrieken. I will buy whatever beers are needed to make up, but I need to make a point._

I suppose that would address the problem in some sense. However, it does seem a bit weird that we'd be providing "custom" icons from _Visual Studio_ to workaround the issue that _Visual Studio_ Code doesn't provide the appropriate _Visual Studio_ artwork to support a _Visual Studio_ language. It's seriously weird that _Visual Studio_ artwork is provided for "Enum" while the _Visual Studio_ artwork for "Enum Member" is not included. Rather than fix the oversight, the solution is to force all language extensions to provide that artwork (which would be _Visual Studio_'s artwork if they want to stay consistent) themselves? I thought that _Visual Studio_ Code had intended to standardize on the look and feel of _Visual Studio_ at one point. Does that not include standardizing on important pieces of artwork that are included in the _Visual Studio_ family of products?

Will custom icons be supported by the language server protocol if we choose to implement that at some point? If not, how will extensions that provide _Visual Studio_ language support for _Visual Studio_ Code via the language server protocol (e.g. C++) be able to implement completion in a way that is _Visual Studio_-grade?

Even TypeScript provides overlays for member accessibility in Visual Studio (using the same artwork C# and other languages in Visual Studio do).

![image](https://cloud.githubusercontent.com/assets/116161/22294053/b10104d0-e2c6-11e6-9c59-ac585130cf3a.png)

However, it can't do the same in Visual Studio Code:

![image](https://cloud.githubusercontent.com/assets/116161/22294201/3a557806-e2c7-11e6-9cb9-ac60fe066bb5.png)

**Comment by jrieken** [comment] 2017-01-25 15:41
Sorry that I have ruined your morning ;-). 

I guess my previous comment was a bit too short and didn't explain enough. Saying that we will eventually allow for custom icons doesn't exclude adding more default icons. However, the problem is unbounded and currently we are caught in a catch up game. There is no answer to what the full set of icons is, so we can either keep it simple (like an enum member is just a member), allow for custom icons, or keep adding more icons. 

Talking about the language server protocol and other editors I honestly don't know what's best: Think of the icon for 'extension method' which isn't a frequently occurring feature in programming languages. Will someone draw an icon that fits into Atom and Sublime? Will someone just copy the icons we ship? Will an existing icon be overloaded/reused, say 'method'? 

So far we have been guided by a somewhat fuzzy 'common denominator' approach to fit most programming languages and things like access modifiers fit nicely into that but it also means we cannot cover everything from any language.

**Comment by DustinCampbell** [comment] 2017-01-25 16:10
Oh, you didn't ruin my morning at all Joh. :smile:

I'm willing to be part of any conversation about determining the 'common denominator' set of icons. I even promise to not push for making the common denominator just the set required by C#. :smile:

**Comment by jrieken** [comment] 2017-01-25 16:18
Perfect. We are now in the Jan endgame. I'll schedule this for Feb and get in touch with you when it's time.

**Comment by DustinCampbell** [comment] 2017-01-25 19:11
Sounds good. You might want to include @markw-t from the VS editor team as well.

**Comment by markw-t** [comment] 2017-01-25 19:56
Thanks for the add guys. It makes perfect sense to me that Visual Studio Code extenders would be able to create parity experiences to Visual Studio without creating custom art - a single "Visual Studio Family" experience should be possible in completion lists like this as @DustinCampbell  suggests above; so the Visual Studio Code default set should include all the values found in the Visual Studio enum if possible.

**Comment by jrieken** [comment] 2017-02-20 16:10
Sorry, this has slipped. Blame me for being on vacations 🌴. Moving to March

**Comment by jrieken** [comment] 2017-03-21 16:21
Let's start to tackle this by adding some more *common-denominator* icons. I'd like to propose that we for now leave the modifier icons out of the equation. It's a little unlucky that we have called it `CompletionItemKind` and `SymbolKind` and I have the feeling we shouldn't add all variants in there but add the concept of a *KindModifier* such that both can determine the visual representation of something. 

For the set of common icons we have things like `Snippet`, `Color` or `File` that describe more or less literals and things that occur in programming languages, like `Function` or `Interface`. In https://github.com/Microsoft/vscode/issues/2628#issuecomment-274950971 @DustinCampbell suggests to add more icons to the latter bucket which is OK with me as long as we don't make it too specific for a single language. 

Can we come with a *N-programming-languages-have-this*-rule? For instance, more than *N* programming languages support interfaces so we have `CompletionItemKind.Interface`. Unsure what *N* should be, for sure *N > 1* maybe something around 3-5 of the most [commonly](https://www.tiobe.com/tiobe-index/) used languages.

**Comment by jrieken** [comment] 2017-03-22 14:36
* [x] added  enumeration member as `vscode.CompletionItemKind.EnumMember`. Should go together with `CompletionKindKind.Enum`. *N-lang-have-this*-rule justification: C, C++, C#, Swift, TypeScript, Java [etc...](https://en.wikipedia.org/wiki/Enumerated_type)

**Comment by jrieken** [comment] 2017-03-22 16:25
* [x] added const a `vscode.CompletionItemKind.Constant` because of C-ish, TypeScript, Java

**Comment by DustinCampbell** [comment] 2017-03-22 16:46
Note that many of the items I listed above are not actually C#-specific, they are relevant to any .NET language. So, F#, PowerShell, C#, VB, etc.

**Comment by jrieken** [comment] 2017-03-23 10:54
* [x] added structure as `vscode.CompletionItemKind.Struct`. Popular languages having structs, almost all: *C, C++, C#, Go, Swift, Rust, etc...*

**Comment by jrieken** [comment] 2017-03-28 07:54
This will continue in April

**Comment by jrieken** [comment] 2017-04-05 09:44
I have shelled out the modifier request to https://github.com/Microsoft/vscode/issues/23927

For April I want to get different icons for _function_ and _method_ and I am open for more kind suggestions.

**Comment by DustinCampbell** [comment] 2017-04-05 12:49
So, what icon suggestions have been eliminated by the "n-languages-have-this-rule"?

**Comment by jrieken** [comment] 2017-04-05 14:02
I'd say 'Extension Method'. Also I'd like to fold 'Delegate' into 'Function' esp. once we have a dedicated icon for function vs method. Operator and Type Param are still valid

**Comment by DustinCampbell** [comment] 2017-04-05 14:23
Extension Method makes sense to leave off. Event is the one I'm probably most interested in. I figure that's probably used a ton since it appears in all the .NET languages (i.e. C#, F#, VB, PowerShell, etc.) plus other languages like HTML:

![image](https://cloud.githubusercontent.com/assets/116161/24710031/b4f1a96e-19d0-11e7-9b18-2a01052611ea.png)

**Comment by jrieken** [comment] 2017-04-05 14:42
True - I have forget that one.

**Comment by jrieken** [comment] 2017-04-18 13:45
Added 'Event' and 'Operator', unsure what icon to use for TypeParam. fyi @aeschli about the `Event` completion kind and above sample

**Comment by DustinCampbell** [comment] 2017-04-18 23:06
The one we use for C# and Visual Basic in VS looks like this:

![image](https://cloud.githubusercontent.com/assets/116161/25156681/f0a0f64c-2450-11e7-8da9-608f71ac6187.png)

I think C++ uses something different.

**Comment by jrieken** [comment] 2017-04-19 08:06
I have found this one which fits `Foo<T>` but also reminds of a word processor...

![screen shot 2017-04-19 at 10 05 49](https://cloud.githubusercontent.com/assets/1794099/25169567/cb49a05a-24e7-11e7-8b9c-f2b5d9b03a70.png)

**Comment by DustinCampbell** [comment] 2017-04-19 13:25
I might be wrong, but I think that's what C++ uses for templates.

**Comment by jrieken** [comment] 2017-04-19 13:53
I understand, and the icon is labeled as template but I couldn't find the T-icon. Nothing we cannot change later, what matter is that the kinds are exposed in the api

**Comment by DustinCampbell** [comment] 2017-04-19 14:17
I haven't looked in the image library in awhile, but if it helps, C# uses the image indexed by `GlyphGroupType` in [`Microsoft.VisualStudio.Language.IntelliSense.StandardGlyphGroup`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.language.intellisense.standardglyphgroup.aspx).

**Comment by jrieken** [comment] 2017-04-21 09:24
Closing this since we now have these completion item kinds. We can still change icons via separate issues. Happy Coding!

**Closed by jrieken** 2017-04-21 09:24 UTC
Labels: api, feature-request

**Comment by DustinCampbell** [comment] 2017-04-21 11:46
Thanks for your work here @jrieken! I'm really looking forward to using these.

**Comment by chrmarti** [comment] 2017-04-26 23:07
![screen shot 2017-04-26 at 4 00 02 pm](https://cloud.githubusercontent.com/assets/9205389/25460727/ef7777ba-2a99-11e7-87bd-30b8003e181d.png)
![screen shot 2017-04-26 at 4 00 16 pm](https://cloud.githubusercontent.com/assets/9205389/25460729/ef7c7c74-2a99-11e7-9f03-cc87c54dffc7.png)
![screen shot 2017-04-26 at 4 00 23 pm](https://cloud.githubusercontent.com/assets/9205389/25460728/ef7bc16c-2a99-11e7-970c-8cd5bd46329d.png)
![screen shot 2017-04-26 at 4 00 55 pm](https://cloud.githubusercontent.com/assets/9205389/25460730/ef7d505e-2a99-11e7-837d-3d7a1394f38a.png)
![screen shot 2017-04-26 at 4 01 11 pm](https://cloud.githubusercontent.com/assets/9205389/25460731/ef81b32e-2a99-11e7-8284-f9518e26ff00.png)
![screen shot 2017-04-26 at 4 01 33 pm](https://cloud.githubusercontent.com/assets/9205389/25460732/ef8d4d24-2a99-11e7-9a57-10ec508bd218.png)

LGTM, verified. (Note that the lists are not identical, I assume that's by design.)

**Comment by DustinCampbell** [comment] 2017-10-24 21:48
@jrieken: Any idea when these icons will make their way into the LSP?

**Comment by jrieken** [comment] 2017-10-25 07:49
@dbaeumer will know

**Comment by dbaeumer** [comment] 2017-10-25 08:06
Created https://github.com/Microsoft/language-server-protocol/issues/324

**Comment by DustinCampbell** [comment] 2017-10-25 13:28
Thank you sir!
