### ISSUE TITLE
"Follow link" hover is jumpy

### ISSUE THREAD

**Issue by peter-fb** [microsoft/vscode#168880] opened 2022-12-12 16:34 UTC
Type: <b>Bug</b>

Since a few months the "Follow link" hover got a bit jumpy, see the attached GIF. IIRC, it didn't do that before.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.67GB (9.81GB free)|
|Process Argv|--user-data-dir C:\\Users\\Peter\\vscode-notes\\user-data-dir --extensions-dir C:\\Users\\Peter\\vscode-notes\\extensions-dir --crash-reporter-id cf455283-b236-453b-809a-3231f5d276f8|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

![Animation](https://user-images.githubusercontent.com/7101417/207100027-fae4cc16-c086-4ca7-b9fc-a1bd695a4084.gif)

**Comment by alexdima** [comment] 2022-12-12 18:03
Duplicate of #168106

**Closed by alexdima** 2022-12-12 18:03 UTC
