### ISSUE TITLE
Keyboard shortcut combination not working anymore

### ISSUE THREAD

**Issue by ugy** [Microsoft/vscode#56571] opened 2018-08-16 14:36 UTC
- VSCode Version: 1.26.0
- OS Version: 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux

Hi !
Since the last update of vscode, my keyboard shortcut Control+Shift+E doesn't work anymore and I can't figure out why, I tried to disable all my installed extension but it doesn't fix the problem.

When I try to re set it and I press the combination, it shows Control+Shift+Unknown.
I have this combination for the CursorEndSelect command. Any idea where it may come from ?

Steps to Reproduce:

1. Set a keyboard shortcut with key combination Control+Shift+E

Does this issue occur when all extensions are disabled?: Yes

**Comment by james-gc** [comment] 2018-08-16 15:59
yes same with me, I am on manjaro linux

**Comment by ramya-rao-a** [comment] 2018-08-16 23:16
/duplicate of https://github.com/Microsoft/vscode/issues/56486
cc @Tyriar @bpasero

**Closed by ramya-rao-a** 2018-08-16 23:16 UTC
Labels: new release
