### ISSUE TITLE
bracket completion error in chinese

### ISSUE THREAD

**Issue by TuRan-sino** [microsoft/vscode#142527] opened 2022-02-08 16:13 UTC
When i input '(' while using chinese input method
Vscode will output "(()" but not "()

Uploading wwdg.h - KEIL (Workspace) - Visual Studio Code 2022-02-09 00-12-42.mp4…

"

**Comment by mjbvz** [comment] 2022-02-08 16:58
Duplicate of #142528

**Closed by mjbvz** 2022-02-08 16:58 UTC
