### ISSUE TITLE
1.57.0 reverts openFoldersInNewWindow behavior to default?

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#126077] opened 2021-06-11 17:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Mac OS 10.14.6 (Mojave)

Steps to Reproduce:

1. Open a folder with VS Code.
2. Use the File | Open menu to open a 2nd folder.

Instead of creating a 2nd window for the 2nd folder, VS Code reuses the 1st window. This behavior is controlled by `openFoldersInNewWindow` which I see has the default value. So, I suspect that either the default behavior has changed or VS Code has reverted this setting to its default value, because until yesterday I was always able to open in a new window using File|Open and I have not touched Preferences in the past week.

**Comment by bpasero** [comment] 2021-06-12 05:24
Selecting "File > Open" will always target the current window unless `openFoldersInNewWindow: on`. Nothing should have changed here.

**Comment by john-aws** [comment] 2021-06-15 14:23
Hi, agree that nothing should have changed here. That's why I'm reporting what appears to be a change, at least for me. I've had `openFoldersInNewWindow: on` forever and have not made any preference changes in the past few weeks yet with the arrival of 1.57.0 (commit b4c1bd0a9b03c749ea011b06c6d2676c8091a70c), VS Code seems to have reset this to `openFoldersInNewWindow: default`.

**Comment by bpasero** [comment] 2021-06-15 16:00
I believe this could maybe be another duplicate of https://github.com/microsoft/vscode/issues/126025 so would be good to check once our `1.57.1` recovery release is out.

**Closed** 2021-06-23 11:27 UTC
Labels: needs more info
