### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by HappyZo** [microsoft/vscode#95610] opened 2020-04-18 18:22 UTC
Issue Type: <b>Performance Issue</b>

Hi 
I am receiving this error message when i try to start a new file: "Unable to open 'Untitled-1': Cannot read property 'other' of null"
 I am unexperienced with the Visual Studio Code app. Can you please help me?

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (1.58GB free)|
|Process Argv|-psn_0_286790|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    90	   747	code main
    0	    49	   749	   gpu-process
    0	    25	   751	   utility
    0	    90	   761	   shared-process
    0	     0	   855	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   21	   213	   846	   window (Welcome)
    0	    57	   847	     extensionHost
    4	    74	   852	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
live-html-previewer|hdg|0.3.0
html-preview-vscode|tht|0.2.5

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment] 2020-04-18 20:32
Does this still happen after you use Command Palette to run `Developer: Reload With Extensions Disabled`?

**Comment by HappyZo** [comment] 2020-04-19 10:09
Yes

**Comment by chrmarti** [comment] 2020-04-20 11:21
Same as #95572.

**Comment by chrmarti** [comment] 2020-04-20 11:39
@HappyZo Could you check if there is anything in the console? (`Help` > `Toggle Developer Console`)

**Comment by bpasero** [comment] 2020-04-20 14:24
Sounds like https://github.com/microsoft/vscode/issues/94931

**Comment by alexdima** [comment] 2020-04-24 21:07
@HappyZo Can you please try to install the [Insiders Build](https://code.visualstudio.com/insiders/)? Does that start up on your machine?

**Comment by alexdima** [comment] 2020-04-25 13:42
Duplicate of #94931. 

The workaround is to install [VS Code Insiders](https://code.visualstudio.com/insiders/) and then open the file at `C:\Users\[your-name]\AppData\Roaming\Code\User\settings.json` and remove any settings that were set to be `null`. Some people report that they have `"editor.quickSuggestions": null` in there. If that is the case, can you please comment here the list of extensions that you have installed? It appears that an extension might be mistakenly adding that to the `settings.json`.

**Closed by alexdima** 2020-04-25 13:42 UTC
Labels: needs more info
