### ISSUE TITLE
Insiders IntelliSense/autocomplete

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#42412] opened 2018-01-30 10:07 UTC
- VSCode Version: 1.20.0 (2018-01-30T06:03:34.017Z)
- OS Version: macOS

When I add `.` to get autocomplete by default it scrolls down and I need always to scroll up to see suggestions. Same if I press `ctrl + space` it always show it scrolled to down. And I don't know why, but it always selects `options` in that file.

![image](https://user-images.githubusercontent.com/30043375/35560398-f514a862-05b5-11e8-85ad-91da48ecc693.png)

**Comment by usernamehw** [comment] 2018-01-30 10:11
Possible duplicate of https://github.com/Microsoft/vscode/issues/41060

**Comment by jrieken** [comment] 2018-01-30 10:23
Use the `editor.selectSuggestions: never` setting to turn this off

**Closed** 2018-01-30 10:23 UTC
Labels: *duplicate, suggest
