### ISSUE TITLE
Spawn unknown notification after installing extension

### ISSUE THREAD

**Issue by Leif0** [Microsoft/vscode#24790] opened 2017-04-14 17:57 UTC
- VSCode Version: 1.12.2
- OS Version: Windows 10 Insider Preview 15063 (rs2_release)

Steps to Reproduce:

1. Install the PHP InteliSense plugin
2. Open a PHP file

After doing these two steps, I now see a notification that says : "Spawn UNKNOWN"

That's it, no informations anywhere, I've tried uninstalling the plugin and reinstalling VS Code but nothing changes

![code_2017-04-14_01-02-04](https://cloud.githubusercontent.com/assets/8561135/25051375/952f018e-214c-11e7-93be-0e8e630e1ae0.png)

**Comment by jrieken** [comment] 2017-04-18 08:12
dupe of #21302

**Closed by jrieken** 2017-04-18 08:12 UTC
