### ISSUE TITLE
Create Process Failed on startup

### ISSUE THREAD

**Issue by swapniljn8** [microsoft/vscode#111115] opened 2020-11-22 07:05 UTC
Issue Type: <b>Performance Issue</b>

The issue happened in the StartUp. Unable to run any of the Salesforce CLI command and Terminal is not also opening giving error : "CreateProcess failed".

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.18GB free)|
|Process Argv|--crash-reporter-id 1e71d829-fffb-4235-a2cd-36b5dddce93b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	 14408	code main
    0	    22	  3452	   crashpad-handler
    0	   177	  5168	   gpu-process
    0	   203	  6240	   window (Welcome - Main ORG - Visual Studio Code)
    0	   195	   412	     extensionHost
    0	    23	   440	     winpty-process
    0	    14	 15160	       console-window-host (Windows internal process)
    0	    53	 14040	     searchService
    0	    85	 13480	   window (Issue Reporter)
    0	   105	 15184	   shared-process
    0	    47	 15340	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - Main ORG - Visual Studio Code)
|    Folder (Main ORG ): 42 files
|      File types: json(8) eslintignore(1) forceignore(1) gitignore(1)
|                  prettierignore(1) prettierrc(1) cls(1) xml(1) md(1) apex(1)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
novasuite|Acn|0.0.2
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.8.0
java|red|0.71.0
vscode-xml|red|0.14.0
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|50.5.0
salesforcedx-vscode-apex|sal|50.5.0
salesforcedx-vscode-apex-debugger|sal|50.5.0
salesforcedx-vscode-apex-replay-debugger|sal|50.5.0
salesforcedx-vscode-core|sal|50.5.0
salesforcedx-vscode-lightning|sal|50.5.0
salesforcedx-vscode-lwc|sal|50.5.0
salesforcedx-vscode-visualforce|sal|50.5.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0

</details>

**Comment by roblourens** [comment] 2020-11-22 20:19
Please give more details about what you are doing and what you are seeing.

**Comment by usernamehw** [comment] 2020-11-28 11:44
Possible duplicate of #105431

**Closed** 2020-12-04 18:23 UTC
Labels: needs more info
