### ISSUE TITLE
Configurations naming mixing javascript and typescript

### ISSUE THREAD

**Issue by andremarcondesteixeira** [microsoft/vscode#54270] opened 2018-07-13 18:12 UTC
I the configurations of the editor, when you search for "typescript", you will notice that configurations related to javascript and typescript are mixed with each other.
This is not the ideal, since one can use different configurations for javascript projects than for the typescript projects. See the image attached.

![image](https://user-images.githubusercontent.com/4294962/42707005-2098a27a-86af-11e8-9562-e3cd8f8404b2.png)

**Comment by roblourens** [comment] 2021-10-15 00:37
It seems like the original issue was just about getting "javascript" results when searching "typescript", which is just a ranking issue (we aren't reordering the results). But I would probably close it out of scope.

How are you suggesting we rename settings? I don't follow

**Comment by mjbvz** [comment] 2021-10-15 21:35
Yes the split in names is by design. We do this when we have settings that can be configured independently for each language

However we aslo use `typescript` as the generic category for things like the typescript server. I don't think it's worth the confusion to try migrating those settings to a more accurate category like `js/ts`

**Closed** 2021-11-15 21:15 UTC
Labels: feature-request, javascript, settings-editor, *out-of-scope
