### ISSUE TITLE
Search on Left Side Nav is Empty

### ISSUE THREAD

**Issue by gtiguy92** [Microsoft/vscode#13531] opened 2016-10-11 18:17 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: eg2.tslint-0.5.38, florentulve.vstortoise-0.6.0, joelday.docthis-0.3.3, johnpapa.Angular2-0.4.4, ms-vscode.csharp-1.2.2, ms-vscode.PowerShell-0.6.2, msjsdiag.debugger-for-chrome-0.4.8, robinbentley.sass-indented-0.1.2

Steps to Reproduce:

1. Click the Magnifying Glass (nothing shows)
2. Click Edit -> Find in Files "Error: cannot read property 'focus' of undefined"

**Comment by FabianLauer** [comment] 2016-10-11 18:41
This might be a duplicate of #13447.

**Comment by isidorn** [comment] 2016-10-11 20:52
Dup

**Closed by isidorn** 2016-10-11 20:52 UTC
