### ISSUE TITLE
Integrated Terminal as New Tab

### ISSUE THREAD

**Issue by Mmannem** [Microsoft/vscode#33060] opened 2017-08-24 07:18 UTC
In Visual Code, can we have 'Integrated Terminal' (Ctrl + ~) as New tab ?

We should be able to open it as normal tabs.

**Comment by fabiospampinato** [comment] 2017-08-24 15:23
The [Open in Terminal](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-terminal) extension almost provides this functionality.

It adds an `Open in Integrated Terminal` command, which opens a new terminal tab in the current folder. You can bind <kbd>Ctrl+~</kbd> to it if you like.

**Comment by Tyriar** [comment] 2017-08-24 21:09
Duplicate of https://github.com/Microsoft/vscode/issues/10546

**Closed by Tyriar** 2017-08-24 21:09 UTC
