### ISSUE TITLE
False positive warning in markdown: links inside math

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#197486] opened 2023-11-05 16:24 UTC
- VS Code Version:  1.84.0
- OS Version: macOS 13.2

Square brackets inside katex fragments are mistaken as markdown links.

<img width="550" alt="image" src="https://github.com/microsoft/vscode/assets/2845433/eeb88297-7b32-4a2f-937f-cb93751b78b8">

<img width="550" alt="image" src="https://github.com/microsoft/vscode/assets/2845433/2545da01-eb45-481b-bbf7-89c288db68ad">

**Comment by mjbvz** [comment] 2023-11-06 18:21
Please always share text along with screenshots so we can easily reproduce the issue

**Comment by memeplex** [comment] 2023-11-06 18:32
```
$$
gain^{(s)}
  = \Delta - \Delta ^{(s)}
  = \frac{1}{2}\left[
    gain_{j_L}^{(s)} + gain_{j_R}^{(s)} - gain_j \right]
$$
```

**Comment by mjbvz** [comment] 2023-11-20 20:50
Duplicate of https://github.com/microsoft/vscode-markdown-languageservice/issues/14

**Closed by mjbvz** 2023-11-20 20:50 UTC
Labels: info-needed, markdown
