### ISSUE TITLE
nobody in the world wants powershell as default terminal

### ISSUE THREAD

**Issue by rossi-jeff** [microsoft/vscode#132664] opened 2021-09-08 16:02 UTC
I've been using vscode with WSL as my default terminal for years. A recent update made powershell the default and no matter how many times I change it , powershell is in my terminal every time I open the program. This is an uninstall the program and use something else level of offence.

seriously fuck you all

**Comment by IllusionMH** [comment] 2021-09-08 16:08
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-08 16:09 UTC
Labels: *duplicate

**Comment by CodeCrazy-ywt** [comment] 2021-09-25 13:05
So I wonder whether they had July & August off work? If otherwise how can they make such a bug?
