### ISSUE TITLE
"terminal.integrated.inheritEnv": false having no effect on $SHLVL

### ISSUE THREAD

**Issue by tlambert03** [microsoft/vscode#130915] opened 2021-08-16 15:08 UTC
Issue Type: <b>Bug</b>

I'm struggling with the $PATH of my integrated terminal.  Regardless of the `terminal.integrated.inheritEnv` setting, the `$SHLVL` of the integrated terminal is always 3.  
I have tried disabling all extensions, and reducing my user settings JSON down to that single value.

The main immediate issue for me is that my conda environment's python is at the end of my $PATH, and the system python is being used instead.

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|64.00GB (20.63GB free)|
|Process Argv|--crash-reporter-id 54548331-bd33-484b-8356-4241bb27bb3f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
vscode-sqlite|ale|0.13.0
vscode-django|bat|1.6.0
markdown-preview-github-styles|bie|0.2.0
vscode-styled-jsx|bla|2.0.0
vscode-tailwindcss|bra|0.6.13
cmake-format|che|0.6.11
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.3.2
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
myst-highlight|Exe|0.11.0
auto-close-tag|for|0.5.12
vscode-opencl|gal|0.7.1
matlab|Gim|2.0.1
vscode-pull-request-github|Git|0.29.2
gc-excelviewer|Gra|3.0.42
language-cython|guy|0.0.6
beautify|Hoo|1.5.0
vscode-cudacpp|kri|0.1.1
restructuredtext|lex|156.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.9.0
prisma|Pri|2.29.1
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
vscode-sort-json|ric|1.20.0
vscode-qt-for-python|sea|1.1.4
vscode-fileutils|sle|3.4.5
sourcery|sou|0.9.3
remote-x11|spa|1.5.0
remote-x11-ssh|spa|1.5.0
rewrap|stk|1.14.0
even-better-toml|tam|0.14.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.3
vscode-java-test|vsc|0.31.2
vscode-maven|vsc|0.32.2
change-case|wma|1.0.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
vscode-fish|zgm|0.5.3
material-theme|zhu|3.11.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by IllusionMH** [comment] 2021-08-16 15:21
Not sure about first part.

But Conda at the end of the `PATH`
> The main immediate issue for me is that my conda environment's python is at the end of my $PATH, and the system python is being used instead.

looks like duplicate of #129979

**Comment by tlambert03** [comment] 2021-08-16 15:25
Thanks a lot for your prompt reponse!  I'll keep an eye on that other issue.

given what is stated in the [docs](https://code.visualstudio.com/updates/v1_36#_launch-terminals-with-clean-environments):

>The main visible result of setting inheritEnv to false is that $SHLVL (shell level) should now be 1 and $PATH should not include duplicate paths, provided your launch scripts don't intentionally include them.

it feels like the `$SHLVL` not being 1 might indicate some lower level problem that could cause both issues?  (but I wouldn't know where to start digging).

**Comment by corneliusroemer** [comment] 2021-08-16 23:55
Very interesting that you also have this conda path added in the end issue @tlambert03. My setup is slightly unusual in that I use `fish` and `micromamba` so wasn't sure whether it was down to that.

Have you tried the workaround I gave in the referenced issue?

You are also on MacOS but what's your shell?

**Comment by tlambert03** [comment] 2021-08-17 00:06
> Have you tried the workaround I gave in the referenced issue?

sorry @corneliusroemer ... it wasn't quite clear to me what the workaround was... do you mean the `terminal.integrated.profiles.osx` ... `"args": ["-l"],` bit?  I did try adding the following to my settings.json but it didn't seem to change anything.
```
  "terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh",
      "args": ["-l"]
    }
  }
```

> You are also on MacOS but what's your shell?

I'm using zsh 5.8

conda 4.10.3 (for what it's worth)

**Comment by corneliusroemer** [comment] 2021-08-17 00:38
Sorry if it wasn't clear. If I read it correctly, removing the `-l` flag fixed it. The flag being present seemed to cause it in my case.

Have you tried keeping the snippet but deleting the lost item with `-l`?

**Comment by tlambert03** [comment] 2021-08-17 12:50
aha!  sorry I misread that, you're right, it works!

with 
```json
  "terminal.integrated.profiles.osx": {
    "zsh": { "path": "zsh", "args": [] }
  },
```
I get 
```sh
$ which python
python is ~/miniconda3/bin/python
python is /usr/bin/python

# note shell level hasn't changed
$ echo $SHLVL 
3
```

with the `-l`:
```json
  "terminal.integrated.profiles.osx": {
    "zsh": { "path": "zsh", "args": ["-l"] }
  },
```
I get 
```sh
$ which python
python is /usr/bin/python
python is ~/miniconda3/bin/python
```
(and I have a duplication of some things in my $PATH)

thanks!

**Comment by Tyriar** [comment] 2021-08-17 12:55
Using `-l` means you `.zprofile` is run so you might want to review that script if it's causing problems? Making it idempotent is a good idea if you haven't already

**Closed by Tyriar** 2021-08-17 12:55 UTC

**Comment by tlambert03** [comment] 2021-08-17 13:05
> Using -l means you .zprofile is run so you might want to review that script if it's causing problems?

I don't have a user `~/.zprofile` ... my system `/etc/zprofile` is just this:
```
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
```

I _am_ using oh-my-zsh ... but if I completely remove oh-my-zsh, and return to the default empty `.zshrc` (which I believe is the standard mac setup?) I still get this error if I don't use the empty `args` suggested by @corneliusroemer .

So, I'm still unable to find anything suggesting this is due to an idiosyncrasy in my setup.  I know you have to keep issues to a minimum, so I get closing it, but I don't really see this as "fixed".

**Comment by tlambert03** [comment] 2021-08-17 13:17
another observation:  with the default vcsode config, I get an incorrect path with _both_ `bash` and `zsh` shells.    I need to use `"args": []` in all shells for them to work.  @Tyriar ... do you still think that means my `zprofile` is at fault?  or could there be something about vscode here?

**Comment by corneliusroemer** [comment] 2021-08-17 14:00
Thanks @tlambert03 for confirming that you have another manifestation of the issue I opened here #129979 with the same workaround working as a fix.
I don't understand why the default setup for Linux is without `-l` and Mac with `-l`, causing problems with Mac that disappear if you use the Linux config.

Should we open a new issue that is more general referencing our two issues as special cases? We've narrowed it down to being reproducible and general across MacOS with a variety of downstream effects.

Otherwise, you could comment on the older issue explaining how your case is similar. There hasn't been any response in 2 weeks so it could help if you comment there (then it's not just me).

**Comment by corneliusroemer** [comment] 2021-08-17 14:01
@Tyriar Do you know why `-l` is set by default for MacOS but not for Linux? It causes issues with default (!) setups for now two users at least and probably many more since I use vanilla setup. I looked through Git blame and couldn't find a good reason for the choice of `-l` in one and not the other OS.

**Comment by Tyriar** [comment] 2021-08-19 15:55
The terminal profile on macOS calls `path_helper` by default which shuffles the path around, not sure what we can do about this.

> I don't understand why the default setup for Linux is without -l and Mac with -l

Terminals on macOS run using login shells, Linux the login shell is run on login. There's a detailed explanation at https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

**Comment by corneliusroemer** [comment] 2021-08-19 23:38
But why do I only see this path problem in vs code and not say hyper terminal? Does hyper decide not to use a login shell?

This is what I find confusing as a user. A problem pops up with only vs code but not other terminals.
