### ISSUE TITLE
SCM view should support drag and drop into editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#181361] opened 2023-05-02 22:48 UTC
1. Add an mp4 file
2. Try to drag and drop it from the SCM view with the shift modifier into the editor
3. :bug: nothing happens. The explorer view supports drag and drop so I would expect the SCM view to support it too

**Comment by mjbvz** [comment] 2023-05-03 00:19
Duplicate of #162082

**Closed by mjbvz** 2023-05-03 00:19 UTC
