### ISSUE TITLE
VS Code adds additional space during copying of documented JS functions

### ISSUE THREAD

**Issue by Inspiratore** [microsoft/vscode#140895] opened 2022-01-18 09:57 UTC
Issue Type: <b>Feature Request</b>

Preconditions: 
- selected language mode : JavaScript
- there is a function with doc string before it, e.g.:

```
/**
 * some description
 */ 

function someFunction () {}
```

Than description and function are pasted into another file, VS Code adds redundant space before keyword function, when it was absent in copied / cutted code.

```
/**
 * some description
 */ 
 
 function someFunction () {}
```

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

**Comment by mjbvz** [comment] 2022-01-18 20:44
Duplicate of #121004

**Closed by mjbvz** 2022-01-18 20:44 UTC
