### ISSUE TITLE
Intellisense should show exact match before others

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11423] opened 2016-09-02 00:29 UTC
- VSCode Version: 1.5.0 Insider
- OS Version: 10.11.6

Steps to Reproduce:

1. Open `settings.json`

![image](https://cloud.githubusercontent.com/assets/4033249/18188761/7a685344-7069-11e6-934b-864255b12e23.png)

**Comment by dbaeumer** [comment] 2016-09-02 07:15
@aeschli starting with you since I don't know if you can control this in json or whether this is a bug in the UI.

**Comment by joaomoreno** [comment] 2016-09-02 08:19
The sort order is correct, but the initial pick is definitely wrong. This depends on what the settings mode brings in as `filterText`.

**Comment by jrieken** [comment] 2016-09-02 16:39
@joaomoreno I believe we score against the [wrong](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L152) string. Instead of label we should score against the `filterText`. My bad, feel free to reassign

**Comment by Tyriar** [comment] 2016-09-29 17:26
Seems to not have changed:

![image](https://cloud.githubusercontent.com/assets/2193314/18964761/21c96d82-862f-11e6-9ed7-b97796b7df3a.png)

- VSCode Version: Code - Insiders 1.6.0-insider (0f7880d7a490ba9aee2b053f3f2e46c19423e7e4, 2016-09-29T14:13:08.930Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

**Comment by Tyriar** [comment] 2016-09-29 19:56
Another side effect of this https://twitter.com/druellan/status/781474312129740800

![cthavjfwiaad53e](https://cloud.githubusercontent.com/assets/2193314/18969929/20f0ae56-8644-11e6-803b-caba8af156a1.jpg)

**Comment by jrieken** [comment] 2016-10-04 09:21
re https://github.com/Microsoft/vscode/issues/11423#issuecomment-250573759 - no, the correct item is selected and sorting is lexically. 

https://github.com/Microsoft/vscode/issues/11423#issuecomment-250534620 - well, it is different steps from the initial item (`"editor"` vs `editor`, quotes vs no-quotes) but a fair request. The problem is that we have an insertText ala `"editor.render"` but cannot match that against the text we'll replace (no quotes). 

@joaomoreno We have a nice and fast [scoring](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L179) routine but I wonder if we should relax it such that we count matches and don't stop when something doesn't match - more or less compute the diff/distance of the replace/insert text and use that? For sure a lot less performant. Any other objections?

**Comment by joaomoreno** [comment] 2016-10-04 09:59
Didn't quite understand that. 😕

**Comment by jrieken** [comment] 2016-10-04 10:47
The [_score](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L179) returns as soon as a character doesn't match, meaning comparing `editor.r` with `"editor.render"` and `"foobar"` all result in the same score of `0`

**Comment by joaomoreno** [comment] 2016-10-04 11:20
We'd have to give it a try. I don't think the performance difference would matter much.

**Comment by octref** [comment] 2016-10-06 16:42
Not working in

Latest insider (Insiders 1.6.0-insider (782e3ad7e504c308a5f1592ca6ae2574a13b0e73, 2016-10-05T16:55:51.362Z)
![image](https://cloud.githubusercontent.com/assets/4033249/19161538/10528f64-8ba9-11e6-93aa-c9b7e6a1bc7e.png)

Latest master:
![image](https://cloud.githubusercontent.com/assets/4033249/19161555/1afcf5f8-8ba9-11e6-90b0-2af8b317229f.png)

**Comment by jrieken** [comment] 2016-10-07 08:39
@octref You are aware of the fact that insiders is frozen for the September release, right?

**Closed by jrieken** 2016-10-07 08:39 UTC
Labels: bug, suggest
