### ISSUE TITLE
Uri doesn't honour http-specialities

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#31805] opened 2017-08-01 09:49 UTC
- VSCode Version: 1.14.2
- OS Version: any

Steps to Reproduce:

1. Create and MD file and paste the following link:
[https://azure.microsoft.com/en-us/?ru=https%3A%2F%2Fmicrosoft.com%2F%3Fparam1%3Dvalue1%26param2%3Dvalue2](https://azure.microsoft.com/en-us/?ru=https%3A%2F%2Fmicrosoft.com%2F%3Fparam1%3Dvalue1%26param2%3Dvalue2)

2. Preview and click on the link. You will be sent to https://azure.microsoft.com/en-us/?ru=https://microsoft.com/%3Fparam1=value1&param2=value2

Notice that the url parameter `ru` is an encoded link. VSCode decodes the parameter and the final link becomes incorrect. Just compare to how GitHub works when you click on the link in step 1.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-01 22:15
I don't think this is markdown specific. I see the same behavior when clicking on that link in the editor. Root cause seems to be our Uri parsing logic:

```
URI.parse('https://azure.microsoft.com/en-us/?ru=https%3A%2F%2Fmicrosoft.com%2F%3Fparam1%3Dvalue1%26param2%3Dvalue2')
```

returns 

```
https://azure.microsoft.com/en-us/?ru=https://microsoft.com/%3Fparam1=value1&param2=value2
```

**Comment by jrieken** [comment] 2017-08-14 10:17
> Root cause seems to be our Uri parsing logic:

The parsing logic doesn't return a string as that comment suggest but simply parses an input string into URI components (scheme, auth, path, query, fragment). The `toString`-method does percent encoding everything (without looking at the scheme for more specialised encoding tricks). When called with `false` the `toString`-method does only encode `&` and `?` because those are needed to parse it again. 

Assuming that the result of `toString` can always be used in `http` or any other specialised protocol is not correct.

**Comment by jrieken** [comment] 2017-10-30 16:46
dupe of #25852

**Closed by jrieken** 2017-10-30 16:46 UTC
Labels: feature-request, uri
