### ISSUE TITLE
Allow different sort orders in Source Control view

### ISSUE THREAD

**Issue by allen-ziegenfus** [Microsoft/vscode#23657] opened 2017-03-30 09:47 UTC
When I try to stage a number of untracked git files, the UI is not displaying the changes correctly. Normally the staged changes will be listed at the top, but recently they are displayed within the middle of the regular changes, and scrolling produces strange UI effects (e.g. the title "STAGED CHANGES" disappears when scrolling)

![vscodeprob](https://cloud.githubusercontent.com/assets/16581685/24498369/98fa4d10-153e-11e7-8015-cd6c552803d7.jpg)
![buggy_view](https://cloud.githubusercontent.com/assets/16581685/24498374/9b542c84-153e-11e7-8622-d41a07e81bda.jpg)

- VSCode Version:1.10.2 
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Add a bunch of untracked git files to be staged

**Comment by allen-ziegenfus** [comment] 2017-03-30 09:51
the problem seems to only happen when there are mainly untracked files (say 30) and i am staging a large set of them (say 15 or so)

**Comment by allen-ziegenfus** [comment] 2017-03-30 13:40
hi @joaomoreno i'm not sure what you mean. if i stage just one file, then the "STAGED CHANGES" section is shown above "CHANGES", even if the path name would dictate a different sort order:

<img width="467" alt="select_data_js__index__ _select_data_js_-_web-dev-lrdcom" src="https://cloud.githubusercontent.com/assets/16581685/24506861/291ebb54-155f-11e7-874e-5f44ac96be1d.png">

**Comment by joaomoreno** [comment] 2017-03-30 14:27
Wow, I just paid attention to your screenshot:

https://cloud.githubusercontent.com/assets/16581685/24498369/98fa4d10-153e-11e7-8015-cd6c552803d7.jpg

This should never happen. Can you easily reproduce this?

**Comment by allen-ziegenfus** [comment] 2017-03-30 14:31
is this the commit hash in the about box? 8076a19fdcab7e1fc1707952d652f0bb6c6db331

like i said if i create a bunch of new files (about 30 or so) and select say half of them to be staged, i can reproduce it.

**Comment by allen-ziegenfus** [comment] 2017-03-30 14:32
<img width="266" alt="screenshot_30_03_2017__16_32" src="https://cloud.githubusercontent.com/assets/16581685/24509382/7cdac286-1566-11e7-888c-2bfb3e713877.png">

**Comment by joaomoreno** [comment] 2017-03-30 14:36
Got it!

Would you mind trying it out in our [insider release](https://code.visualstudio.com/insiders)?

**Comment by joaomoreno** [comment] 2017-03-30 14:39
Nevermind! This is definitely a duplicate of #20142 and #19242. The fix hasn't yet hit stable.

Thanks for the help! 👍

**Closed by joaomoreno** 2017-03-30 14:39 UTC
Labels: bug, scm

**Comment by allen-ziegenfus** [comment] 2017-03-30 14:46
hi yes, it is working in the insider release. thanks! sorry i did not see those other tickets.

**Comment by joaomoreno** [comment] 2017-03-30 16:07
No problem!
