### ISSUE TITLE
Disable autoimport on JS/TS files by default

### ISSUE THREAD

**Issue by alirobe** [Microsoft/vscode#38911] opened 2017-11-22 01:20 UTC
- VSCode Version: 1.18.1
- OS Version: Windows 10 1709

Steps to Reproduce:

1. use setTimeout in a large javascript file that didn't use it before.
2. `import { setTimeout } from "timers";` is added to top of file, without any notification, question, prompt, warning, or visible change on screen.

This is an absolutely terrible default, it's unclear the change to my code is happening, as it's not even visible on the screen. It breaks my code. Like most people, I am migrating to TypeScript, not using it exclusively. Some of my code is not compiled before being shipped. This just confuses browsers, and I don't want it. 

This whole feature should be removed until a better UX can be implemented. As a general rule, a code editor doesn't mess with code like this. It isn't your job to be writing my code for me. If I wanted this thing to behave like an IDE, I'd use an IDE. This behavior change is entirely unexpected for an editor. It breaks our workflow. Either ask me before making changes, or stop making changes I can't see.

**Comment by ssamuli** [comment] 2017-11-22 15:24
I agree with @alirobe, it is an awful default.

In case anyone else is ending up here from google, looking for ways to disable it, just put this in your settings:
"typescript.autoImportSuggestions.enabled": false

**Comment by mjbvz** [comment] 2017-11-27 17:23
Duplicate of #38551

As already covered, you can disable this by setting: `"typescript.autoImportSuggestions.enabled": false`. If you are seeing bugs with auto-import behavior or have ideas on how the UX could be improved, please file new issues

**Closed by mjbvz** 2017-11-27 17:23 UTC
Labels: new release

**Comment by alirobe** [comment] 2017-11-28 08:08
@mjbvz this is not a duplicate, it's a UX improvement idea.
