### ISSUE TITLE
When using the command panel, some open windows will be affected [使用命令面板的时候会影响到某些已打开窗口]

### ISSUE THREAD

**Issue by IOLOII** [microsoft/vscode#205639] opened 2024-02-20 06:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.2 (system setup)
- OS Version: Windows_NT x64 10.0.19044

版本: 1.86.2 (system setup)
提交: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
日期: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open release notes
2. Use command `ctrl + shift + p` and confirm lastest command, then  view will scrolled ，repeating the current step will scroll down repeatedly

![find bug](https://github.com/microsoft/vscode/assets/34856171/3a379dcd-1231-49de-9e13-c7a55e2d4804)

**Comment by mjbvz** [comment] 2024-12-09 21:48
Duplicate of #168677

**Closed by mjbvz** 2024-12-09 21:48 UTC
