### ISSUE TITLE
Auto update import on file move | doesn't work

### ISSUE THREAD

**Issue by syedsimanta03** [Microsoft/vscode#70840] opened 2019-03-20 16:38 UTC
Auto update import on file moved not working on VS code latest version for Create React APP. 

Steps to Reproduce:

clone https://github.com/g3offrey/example-node-repository
try to move file from folder1 to another folder or to the root
check if the require path in index.js is updated
Does this issue occur when all extensions are disabled?: Yes

If I can do something to help, don't hesitate to ask me.

feature link : https://code.visualstudio.com/updates/v1_24?WT.mc_id=vscodemay18-twitter-brcl#_update-import-paths-when-a-file-is-moved-or-renamed

"javascript.updateImportsOnFileMove.enabled" : "always",

not working. I am working on a react project and it took me 2hrs to change file path again manually
Thank you

**Comment by mjbvz** [comment] 2019-03-20 18:33
Duplicate of #70689

Please don't open duplicate issues

**Closed by mjbvz** 2019-03-20 18:33 UTC
Labels: javascript
