### ISSUE TITLE
You absolute boofoons

### ISSUE THREAD

**Issue by bozmund** [microsoft/vscode#232376] opened 2024-10-27 23:07 UTC
Type: <b>Feature Request</b>

Imagine not being able to place editor tabs to be on the right side of the editor, f-ing cringe be more inovative like jetbrains where you can literally just select which side you want your tabs on. disapointed and rightfully mad at this open source bs

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by istiak101** [comment] 2024-10-28 04:56
Some 13 years old when they are released from discord hospital.

**Comment by jd-apprentice** [comment] 2024-10-28 05:23
Be professional if you are going to ask for things! Cheers.

**Comment by gjsjohnmurray** [comment] 2024-10-28 07:01
/duplicate of #108264 as long a that one (if ever implemented) gives a left/right choice.

**Closed** 2024-10-28 07:02 UTC
Labels: *duplicate
