### ISSUE TITLE
Description of extension properties under settings UI not localized in WSL

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode#106371] opened 2020-09-09 22:51 UTC
Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Steps to Reproduce:**

1. Open VS Code in WSL
2. Install French language pack and [C++ Extension](https://github.com/microsoft/vscode-cpptools/)
3. Reload VS Code if required to apply French language pack
4. Go to settings UI and go to C++ settings (see screenshot below)
5. Observe that the description of the C++ properties under the settings UI are not localized.
6. Note: description of the C++ settings are localized when extension is running locally (not using WSL)

Is this an issue with settings in WSL not porting over localized strings of an extension?

**Description of properties under settings UI is not localized when running in WSL**
![image](https://user-images.githubusercontent.com/38734287/92662536-e5ff4100-f2b3-11ea-8133-e266c1bb7982.png)

**Description of properties under settings UI is localized when running locally**
![image](https://user-images.githubusercontent.com/38734287/92662472-bcdeb080-f2b3-11ea-8248-e28bc875241f.png)

**Comment by dbaeumer** [comment] 2020-09-11 07:27
@michelleangela is this only happening with the C++ extension. What's about CSS, ....

**Comment by dbaeumer** [comment] 2020-09-11 07:30
This works in principal for me:

<img width="1285" alt="capture" src="https://user-images.githubusercontent.com/1931590/92883605-51aaf080-f411-11ea-8b09-4bb821258b2c.png">

@michelleangela have you checked with the C++ extension whether it is localized at all?

**Comment by michelleangela** [comment] 2020-09-11 18:49
(FYI to @@Colengms)

@dbaeumer Yes, the C++ extension is localized. Our loc files are at https://github.com/microsoft/vscode-cpptools/tree/master/Extension/i18n. 

What's interesting is the C++ extension property descriptions under the settings UI is localized when running the extension on a local machine, but through WSL the property descriptions are not localized. The strings of functional features from the C++ extension are also localized via WSL. The descriptions in our custom c_cpp_properties.json are also localized under our custom UI view. It is just the property descriptions under the  VS Code settings UI that are not localized.

I saw that the other items under the extensions setting menu are localized via WSL. however are these extensions built-in or packaged with VS Code client? Is there something specific that an extension has to do in order to get localization to work via WSL other than using  "vscode-nls/vscode-nls-dev" ?

**Comment by dbaeumer** [comment] 2020-09-14 07:41
@michelleangela do you know how the C++ extension ships their localizations ?

**Comment by Colengms** [comment] 2020-09-14 18:59
@dbarumer We use [vscode-nls](https://github.com/microsoft/vscode-nls) and [vscode-nls-dev](https://github.com/microsoft/vscode-nls-dev).  We generate `nls-bundle.*.json` files, etc..

```
nls.config({ messageFormat: nls.MessageFormat.bundle, bundleFormat: nls.BundleFormat.standalone })();
const localize: nls.LocalizeFunc = nls.loadMessageBundle();
```

**Comment by dbaeumer** [comment] 2020-09-15 07:33
@Colengms so you ship the translations with your extension. You are not part of the VS Code language packs?

**Comment by Colengms** [comment] 2020-09-15 18:56
@dbaeumer Correct.  We do not ship with VS Code.  We ship via the Marketplace.  Our strings (may) change with each release, and are included the vsix for that release.

**Comment by dbaeumer** [comment] 2020-09-16 09:22
I need to investigate this and it might not be easy to fix right now. The problem is that the language packs are installed on both sides to ensure both side have access to the translation. In your case it doesn't make sense to install the extension on the client side as well. This is why the translations are missing on the renderer side.

**Comment by michelleangela** [comment] 2020-09-16 19:15
@dbaeumer 
I tried your suggestion of only installing the extension on the remote side only and the descriptions are still not localized under the settings UI (see screenshot below).

![image](https://user-images.githubusercontent.com/38734287/93381913-33c8fb80-f816-11ea-8efc-04da1a1f209a.png)

**Comment by dbaeumer** [comment] 2020-09-17 08:51
Actually that wasn't a suggestion. You can't work around this. The problematic code is very likely here: https://github.com/microsoft/vscode-distro/blob/distro/src/vs/workbench/services/extensions/node/extensionPoints.ts#L135

Are you sure that the translation works as expected when the extension is installed locally. The code tells me something different :-)

**Comment by michelleangela** [comment] 2020-09-17 17:15
From what I can see when running the extension locally, the text from Typescript and our native binaries are localized.

Looking at the code from that line, maybe there is something we don't know that's not working locally https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/extensions/node/extensionPoints.ts#L137
```
localizedMessages = pfs.fileExists(basename + '.nls' + extension).then<LocalizedMessages | undefined, LocalizedMessages | undefined>(exists => {
				if (!exists) {
					return undefined;
				}
```

**Comment by dbaeumer** [comment] 2020-09-18 08:19
I fixed it in the meantime. It is actually in the remote server code that is not hosted in this repository. I will close the issue when we have merged the fix in.

**Comment by dbaeumer** [comment] 2020-09-18 09:14
Got merged. Closing the issue.

**Closed by dbaeumer** 2020-09-18 09:14 UTC
Labels: bug
