### ISSUE TITLE
Git: File events don't work if .git is outside the opened folder

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#41085] opened 2018-01-03 11:15 UTC
- VSCode Version: latest insider
- OS Version: Windows 10 x64

The following bug only seems to happen when two folders belonging to the **same parent git repository** are added to the workspace. For example, here myApp is the repository:

```
myApp/
myApp/.git
myApp/foo
myApp/foo/test.js
myApp/bar
myApp/bar/test.js
```

Steps to Reproduce:

1. open an empty VSCode window
2. add the `foo` folder to the workspace
3. add the `bar` folder to the workspace
4. open one of the test.js file
5. open the integrated terminal and type `git checkout -b new_branch`

What happens?
The branch sticks to `master` in the bottom left corner of vscode.

*Note:* Exiting VSCode and opening the previous workspace will correctly show the new_branch as current branch.

Reproduces without extensions: Yes

**edit:**
Problem also happens with *macOS* High Sierra. See my last comment.

**Comment by warpdesign** [comment] 2018-01-03 17:40
I looked at the git extension source code and the problem seems to be somewhere in `extensions/git/repository.ts`: the onFSChange() callback isn't executed in my case after running `git checkout new_branch` so the status is never updated.

**Comment by warpdesign** [comment] 2018-01-04 13:46
Question: couldn't the problem simply be that the fileSystemWatcher only listens for file changes inside the **workspace** (ie: in this example, only in `myApp/bar` and `myApp/foo`)?

If I create and switch to a new branch with `checkout -b new_branch`, no files would change inside the workspace (only inside the parent .git directory), the fsWatcher wouldn't trigger any change, and so the git's branch isn't updated.

**Comment by warpdesign** [comment] 2018-01-05 09:17
I now know how to easily reproduce it:

```
myApp
myApp/foo
myApp/.git
```

Opening the `myApp/foo` folder is enough to trigger the problem.

In this case VSCode will detect the git repository found in foo's parent directory but will only listen for file changes inside the `myApp/foo` folder.

Creating a new branch, or changing a branch with no changes (eg. `git checkout -b new_branch`) won't make any file modifications inside `myApp/foo` folder, so won't trigger status update of the git branch.

**Comment by joaomoreno** [comment] 2018-01-09 16:05
Yup.

@jrieken @bpasero This happens because the `.git` folder is up the directory chain and outside the workspace. The git extensions gets no file events within it. This was working fine when I was using `fs.watch`, and stopped working as soon as I moved to `workspace.createFileSystemWatcher`. Have you guys considered providing a file system watcher creator function which lets me pick any root?

**Comment by jrieken** [comment] 2018-01-09 16:25
Exposing this in the API is easy ;-)

**Comment by bpasero** [comment] 2018-01-09 17:01
@joaomoreno not easy without a reliable watcher, but we have https://github.com/Microsoft/vscode/issues/3025 for it already.

**Comment by joaomoreno** [comment] 2018-01-10 08:51
Well this is really just a duplicate of #3025, which I failed to find in my search efforts.

**Closed** 2019-06-12 08:40 UTC
Labels: bug, git
