### ISSUE TITLE
Undo / redo buffer occasionally gets corrupted

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/vscode#139778] opened 2021-12-26 23:04 UTC
Does this issue occur when all extensions are disabled?: Yes/No

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

[OK] [Copy]
```

Steps to Reproduce:

1. Run for a ~long-ish time
2. Go to a file with lots of changes
3. Hold down ctrl-z to undo a whole lot of changes in batch
4. Hold down ctrl-y to redo all of them

Observe the following

![image](https://user-images.githubusercontent.com/49594/147422033-e379c021-9216-48a6-a72d-5f558bab5fd5.png)

**Comment by alexdima** [comment] 2021-12-27 09:17
@Jasper-Bekkers I cannot reproduce this. Do you remember doing something specific that might trigger this? Extensions can also push edits to the text buffer, does this reproduce when disabling all extensions?

**Comment by Jasper-Bekkers** [comment] 2021-12-27 09:36
@alexdima so this is pretty far from a 100% repo. It happens once ever few weeks of editing or so.

I can't easily test this without extensions enabled, though I don't have a lot of them running (mostly just have extensions for debugging, not for editing).

I kind of suspect that this happens when editing, changing git branches, editing again etc.

Are there any logging or debugging settings I can enable to trace this down further since I expect this may be a slow one to track down?

**Comment by alexdima** [comment] 2021-12-27 10:01
Unfortunately there are no extra logging / debugging settings in this area. The text buffer is such a critical piece that logging from it would create endless-loops (e.g. the output editor that renders the logs is using a text buffer, which would then also log every time it changes to display a log message).

From your description, the problem could be in two distinct areas:
* in the undo/redo stack and how it is serialized and revived when closing a file and reopening it. When a file is closed, the undo/redo stack is kept and associated with the sha1 of the file at the state when the file was closed. When the file is reopened, if its contents match the same sha1, the undo/redo stack is restored.
* in the text buffer itself. Our text buffer is using a [piece tree](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation) that would end up with very specific nodes depending on the edits that were done to it, so without having precisely each and every edit we don't really stand a chance to reproduce something here.

I'm not sure how to proceed here. This is also the first report we've had that text ends up "garbled" recently, that's why I'd really like to rule out an extension as the root cause.

**Comment by Jasper-Bekkers** [comment] 2021-12-27 15:23
> This is also the first report we've had that text ends up "garbled" recently, that's why I'd really like to rule out an extension as the root cause.

Since this happens somewhat rarely - but often enough for me to file a ticket for it, I've reduced the amount of extensions I'm running with a bit to just the bare minimum I really need. So I'll keep you posted when it happens again. It's unclear to me what happens here other then "undo a lot/redo a lot" so it's hard to keep an eye out for additional repro steps to narrow down the problem a bit more.

If this happens again - is there anything you'd like me to take a look at in the developer tools? And additionally, could you point me in the rough direction of some of the editor code I should be keeping an eye out for?

**Closed** 2022-01-18 11:26 UTC
Labels: needs more info
