### ISSUE TITLE
Refactor via Extracion not responding in Interactive playground

### ISSUE THREAD

**Issue by Frazer** [Microsoft/vscode#71898] opened 2019-04-08 00:30 UTC
Issue Type: <b>Bug</b>

When tryng the 'Refactor via Extracion' function in the Interactive playground, pushing ⌘.  shows "no code actions available", also the lightbulb doesnt appear.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (12.29GB free)|
|Process Argv|-psn_0_155686|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
gitkraken-glo|axo|1.1.0
path-intellisense|chr|1.4.2
doxdocgen|csc|0.4.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
firebase-snippets|has|0.0.1
rest-client|hum|0.21.2
vscode-edit-csv|jan|0.0.10
chat|kar|0.12.0
git-graph|mhu|1.4.4
python|ms-|2019.3.6352
vsliveshare|ms-|1.0.18
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|2.2.0
code-settings-sync|Sha|3.2.8
vscode-react-native|vsm|0.9.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by mjbvz** [comment] 2019-04-08 21:49
Duplicate of #51575

**Closed by mjbvz** 2019-04-08 21:49 UTC
