### ISSUE TITLE
Allow to change the name of the tab without saving

### ISSUE THREAD

**Issue by DanielSSilva** [microsoft/vscode#69957] opened 2019-03-07 13:54 UTC
Many times I end up copying content into VSCode in order to compare/format/read/etc. Because sometimes I copy content to many diffent files, I keep track of which is which because they are "labeled" Untitled-1, Untitled-2, etc. It would be really cool to allow the change of the name without the need of saving the file.

**Comment by yume-chan** [comment] 2019-03-11 08:22
duplicate of #50303
which is a duplicate of #37414

**Closed** 2019-10-14 15:23 UTC
Labels: *out-of-scope, feature-request, workbench-editors
