### ISSUE TITLE
Save All Keyboard shortcut

### ISSUE THREAD

**Issue by Legitgamer264** [Microsoft/vscode#16467] opened 2016-12-04 23:24 UTC
- VSCode Version: 1.8.0 Insider
- OS Version: Insider Build 14971
I would like to see a "Save All" shortcut button combo. I am usually editing and writing different files in the same project and I wish to edit like for example 5-6 files and then have a shortcut key combo that will Save All of the files at once. I don't know if this will be easy to implement since Ctrl-Shift-S is already "Save As". Its not a high priority, its just something that I would want as an easy way o save the whole project with my keyboard.

**Comment by chrmarti** [comment] 2016-12-05 04:45
It's bound on OSX, the other platforms don't seem to have a good combination that we can use. You can always bind a keyboard shortcut yourself (File/Application > Preferences > Keyboard Shortcuts). Marking as duplicate of #14818

**Closed by chrmarti** 2016-12-05 04:45 UTC
