### ISSUE TITLE
Hitting Run on compound debugger changes the selected debugger

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vscode#32563] opened 2017-08-15 15:05 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Select a compound debugger (in my case C# and Chrome)
2. Hit F5
3. Drop down changes to the first debugger in the compound list.
4. Next run uses that instead of the compound debugger.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment] 2017-08-15 15:44
duplicate of https://github.com/Microsoft/vscode/issues/32318

**Closed by weinand** 2017-08-15 15:44 UTC
Labels: debug, new release
