### ISSUE TITLE
Different font for different content

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#73664] opened 2019-05-13 12:05 UTC
I thought that would be nice if comments' font was different from codes,like `fira code` for comments and `monaco` for codes
Not different colors or different styles,I know these settings.

**Comment by chrmarti** [comment] 2019-05-13 18:27
@joaomoreno Don't you use a theme doing that?

**Comment by joaomoreno** [comment] 2019-05-23 13:39
@chrmarti I use https://github.com/kencrocken/FiraCodeiScript which changes italic text to another font. Not really the same.

Forwarding this to editor.

**Comment by alexandrudima** [comment] 2019-10-25 12:09
Duplicate of #30925

**Closed by alexandrudima** 2019-10-25 12:09 UTC
Labels: editor-rendering, feature-request
