### ISSUE TITLE
typescript codeAction `addMissingImports`  will add duplicated named import

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#215427] opened 2024-06-13 10:46 UTC
## reproduce

1.accept one suggestion which will update imports
2. save quickly (by press `CMD + S`),
3. will cause import duplicated member

Note: I enable the `addMissingImports` codeActionOnSave:

`settings.json`:

```jsonc
"editor.codeActionsOnSave": {
    "source.fixAll": "never",
    "source.addMissingImports": "explicit"
}
```

## expect

don't duplicated add the imports

## solution

When run code action `source.addMissingImports` check whether the imports had already exists

@mjbvz 

```
Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
"typescript": "^5.4.5"
```

https://github.com/microsoft/vscode/assets/41773861/901d52a2-96ae-4177-a380-2e8aa22ef94a

**Comment by tjx666** [comment] 2024-06-25 15:54
@mjbvz Can you reproduce it? This issue impact development efficiency in big project if the intellisense is a little slow.

**Comment by tjx666** [comment] 2024-06-25 15:56
@zardoy Can this be fixed in your [ts extension](https://github.com/zardoy/typescript-vscode-plugins)?

**Comment by zardoy** [comment] 2024-06-25 20:27
> @zardoy Can this be fixed in your ts extension

Yes many things are already fixed only in my extension and many other can be fixed as well. But it would be much better is the fix was generally available to everyone with the of the box experience

**Comment by tjx666** [comment] 2024-07-16 07:49
@mjbvz I think this issue maybe because the codeActionsOnSave nit wait for the `update imports by accpet completion'.

Any settings to disable update imports when accpet completion?

**Comment by zardoy** [comment] 2024-08-05 15:56
> @justschen I see you will fix some issue about typescript imports in August, can you also consider to fix this?

That's the matter of issue prioritizing. It would be better to fix really annoying issues like imports not updating after installing any new package via `npm/pnpm i` (even when the new vscode watcher is enabled).

**Comment by mjbvz** [comment] 2024-09-23 22:12
Duplicate of https://github.com/microsoft/typescript/issues/40921. I don't want to invest more trying to implement this on the VS Code side. Instead it should be handled by TypeScript since they can do this correctly

**Closed by mjbvz** 2024-09-23 22:12 UTC
Labels: typescript, editor-code-actions
