### ISSUE TITLE
Timeline - Page Size - Invalid Setting (with no custom setting)

### ISSUE THREAD

**Issue by hbergren** [microsoft/vscode#98327] opened 2020-05-21 14:01 UTC
Issue Type: <b>Bug</b>

Scroll down to Timeline - Page Size in the Settings UI, and encounter an error, even though there are no user overrides for this setting:

![page-size-invalid-setting](https://user-images.githubusercontent.com/11398766/82566496-00b57a80-9b4a-11ea-9ef1-da4493c3cd5b.png)

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.30GB free)|
|Process Argv|-psn_0_15310489|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.2.0
vscode-tailwindcss|bra|0.2.0
pgformatter|bra|1.14.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.7.0
vscode-firefox-debug|fir|2.8.0
lintlens|ghm|3.0.0
headwind|hey|1.6.5
vscode-peacock|joh|3.7.2
chat|kar|0.33.0
vscode-language-babel|mgm|0.0.27
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vsliveshare|ms-|1.0.2169
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
debugger-for-chrome|msj|4.12.7
sqltools|mtx|0.21.7
vscode-jest|Ort|3.2.0
polacode|pnp|0.3.4
prisma|Pri|0.1.5
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
code-spell-checker|str|1.9.0
shellcheck|tim|0.9.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.7
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-05-22 07:58
Try updating to 1.45.1

**Comment by hbergren** [comment] 2020-05-26 17:18
Still broken for me on `1.45.1`.

**Comment by DAmNRelentless** [comment] 2020-06-02 02:30
Same for me, also using 1.45.1 on Windows.

**Comment by eamodio** [comment] 2020-06-02 05:22
Duplicate of https://github.com/microsoft/vscode/issues/97308

**Closed by eamodio** 2020-06-02 05:22 UTC
Labels: timeline
