### ISSUE TITLE
Autocomplete icons are no longer colored

### ISSUE THREAD

**Issue by chet-manley** [microsoft/vscode#95002] opened 2020-04-11 15:48 UTC
- Version: 1.45.0-insider
- Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
- Date: 2020-04-10T18:15:17.029Z
- Electron: 7.2.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 5.5.13-200.fc31.x86_64

Steps to Reproduce:

1. Start typing to trigger autocomplete
2. Autocomplete appears, but all icons (ex: methods and props used to be colored) are greyscale

![image](https://user-images.githubusercontent.com/6780085/79048243-53158a00-7be1-11ea-9ab9-559f6b3263fa.png)

The commit from ~2 days ago appeared to be working as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-04-11 20:17
Duplicate of  https://github.com/microsoft/vscode/issues/94855

**Closed by RMacfarlane** 2020-04-11 20:17 UTC
