### ISSUE TITLE
High performance bracket pair colorization bug with '=>'

### ISSUE THREAD

**Issue by james-rose** [microsoft/vscode#132399] opened 2021-09-05 18:22 UTC
Issue Type: <b>Bug</b>

The "=>" in :rules (see below) is detected as a delimiter and it causes the closing delimiter to turn red instead of yellow.

          <q-input
            outlined
            v-model="taskToSubmit.name"
            label="Task name"
            class="col"
            :rules="[val => !!val || 'Name is required']"
          />

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:56:36.444Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 8b017bff-2c5e-4b4b-8aa8-a874e6a0eb93|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
numbered-bookmarks|ale|8.1.0
project-manager|ale|12.3.0
git-rename|amb|1.2.0
preview-pdf|ana|1.0.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
copilot|Git|1.4.2586
vscode-pull-request-github|Git|0.30.0
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
vscode-view-in-browser|kop|1.0.5
color-highlight|nau|2.4.0
vetur|oct|0.34.1
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
vue-vscode-snippets|sdr|2.2.1
html5-boilerplate|sid|1.1.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.14
colonize|vms|2.2.2
vscode-icons|vsc|11.6.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.11.4

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedt:30351793
vsdyn321cf:30356811
pydsgsc2:30361791
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by hediet** [comment] 2021-09-05 20:21
Duplicate of #132336.

Please ping the author of the language-extension to remove `<`...`>` from the bracket pairs to colorize. (see [my comment](https://github.com/microsoft/vscode/issues/132336#issuecomment-913204643))

**Closed** 2021-09-05 20:20 UTC
Labels: *duplicate, new release
