### ISSUE TITLE
Default terminal profile setting is ignored

### ISSUE THREAD

**Issue by vaindil** [microsoft/vscode#130268] opened 2021-08-06 16:16 UTC
Issue Type: <b>Bug</b>

I have a custom terminal profile in my settings.json file like I always have. This terminal always opened by default prior to today's update. Today, however, the PowerShell terminal is always opening by default (either when opening VS Code fresh or clicking the + icon in the terminal area to create a new one). I found the setting `terminal.integrated.defaultProfile.windows` and set that to my profile, but it has no effect. I do not have either `terminal.integrated.shell.windows` or `terminal.integrated.shellArgs.windows` specified, so the default profile should be honored, but it's not. Setting the default profile to one of the built-in options, like Command Prompt, also has no effect. Opening my custom profile manually using the dropdown to explicitly choose it works just fine, it just refuses to open by default.

These are the only lines in settings.json that contain the text `terminal` (other than a bunch of lines that are just hex color codes):

```json
"terminal.integrated.profiles.windows": {
  "cmder": {
    "path": "C:\\WINDOWS\\System32\\cmd.exe",
    "args": [
      "/K",
      "C:\\path\\Cmder\\vendor\\bin\\vscode_init.cmd"
    ]
  }
},
"terminal.integrated.defaultProfile.windows": "cmder",
```

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (16.61GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a705106d-83f5-430f-bc96-f3ab88b46638|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt:30346833
dockerwalkthrucf:30346919

```

</details>

**Comment by vaindil** [comment] 2021-08-06 16:23
I see #126732, which is my issue, but it's closed without much info. This is a new issue that started only in today's build for me.

I also see #121722, but the workaround in that issue does not work. Not sure if this should be closed in favor of that one, as mine is a new issue but the old one is so vague that it also encompasses this one.

**Comment by cdxn** [comment] 2021-08-06 16:42
as @vaindil stated: this started today. Not only are profile settings ignored (User, Remote, Workspace), the prior terminal.integrated.shell.linux is also ignored. Windows 10 + WSL2 Ubuntu 20.04 + VSCode insiders.

Always launches integrated using $SHELL, and launches in home, not path from which VSCode was provided.

Version: 1.60.0-insider (user setup)
Commit: 49af1cbe00271ac2ea36cfc5f7352fe31a7b0094
Date: 2021-08-06T06:41:50.275Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by meganrogge** [comment] 2021-08-06 17:43
Thanks for catching this. will be fixed in tomorrow's insider's.

**Closed** 2021-08-06 17:43 UTC
Labels: bug, confirmed, terminal-profiles

**Comment by vaindil** [comment] 2021-08-09 13:43
@meganrogge This only appears to be partially fixed in the latest insiders build. Clicking the + icon works to open the default terminal, but PowerShell is still opened when I initially open a VS Code window (either the first instance or a new window). Looks like #128763 is being used for this, so I'll comment over there too.

**Comment by cdxn** [comment] 2021-08-09 14:02
@vaindil @meganrogge  - observed same behavior on Windows + WSL2. Initial integrated terminal falls back to $SHELL. +, or Ctrl + ` launches using profile.

**Comment by dippas** [comment] 2021-08-09 16:39
This is still not fixed, when restarting/open  @meganrogge

**Comment by meganrogge** [comment] 2021-08-09 17:18
/duplicate of #128763 - this issue tracks the issue with setting a default profile and creating with the + button not working (after the main launch), which has been fixed.

**Comment by KathRains** [comment] 2021-09-10 18:50
I noticed this problem today after the recent update of VS Code. My default profile is Command Prompt and I do have the default settings for it but PowerShell is loaded ignoring them

```
    "terminal.integrated.profiles.windows": {
        "PowerShell": null,
        "Command Prompt": {
            "path": [
              "${env:windir}\\System32\\cmd.exe"
            ]
        }
    },
    "terminal.integrated.defaultProfile.windows": "Command Prompt"
```
