### ISSUE TITLE
Change color to problem/warning count labels

### ISSUE THREAD

**Issue by tavuntu** [microsoft/vscode#44062] opened 2018-02-20 20:22 UTC
This is a small request, but it would be useful to see these labels with a different color (maybe red?) when the problem or warning counts are greater than zero:

[![image.png](https://s17.postimg.org/x3e53lmv3/image.png)](https://postimg.org/image/i7flw0bgb/)

this way the eye will catch more rapidly when there's an error/warning (people like me, with a small monitor, hate to have the problems tab opened)

**Comment by misolori** [comment] 2019-10-28 16:43
Duplicate of https://github.com/microsoft/vscode/issues/22346

**Closed** 2019-10-28 16:43 UTC
Labels: *duplicate, feature-request, ux
