### ISSUE TITLE
Extension Developers: Allow Variable Substitutions in Settings.config

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/vscode#23738] opened 2017-03-31 12:13 UTC
As an extension developer I would love if its possible to use the built in VSCode variable substitution in my own extension settings JSON config file, like task.json & launch.json
https://code.visualstudio.com/docs/editor/tasks#_variable-substitution

The ones of interest for me are `${workspaceRoot}` and `${workspaceRootFolderName}`

**Comment by aeschli** [comment] 2017-03-31 13:32
duplicate of #18709

**Closed by aeschli** 2017-03-31 13:32 UTC
