### ISSUE TITLE
The git repository has too many active changes

### ISSUE THREAD

**Issue by complexityclass** [microsoft/vscode#73728] opened 2019-05-14 15:15 UTC
I have some really annoying warnings and can't even turn them off. _Don't show again_ button doesn't work.

These are two warnings I have
`The git repository at '/private/var/folders/1g/gq74jq1d3h9cwbz240kdr0x45xywwk/T' has too many active changes, only a subset of Git features will be enabled.`

`The git repository at '/Users/user/path/to/monorepo/files' has too many active changes, only a subset of Git features will be enabled.`

**git status -u** shows only 1 change
**git rev-parse --show-toplevel** shows correct folder (it's a big monorepo)

The first one is not even a repo, it is a system temp directory.

- VSCode Version: 1.33.1
- OS Version: 10.14.4

Steps to Reproduce:
1. git difftool HEAD (vscode as a merge tool)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment] 2019-05-23 13:43
> git status -u shows only 1 change

This is pretty weird.

---

If you open a New Window in VS Code, does the error keep appearing?

**Comment by complexityclass** [comment] 2019-05-27 11:38
> > git status -u shows only 1 change
> 
> This is pretty weird.
> 
> If you open a New Window in VS Code, does the error keep appearing?

Yes, it does.

**Comment by joaomoreno** [comment] 2019-05-28 07:01
Does the error appear right on startup? Can you show me a screenshot of the full window with the error?

**Comment by complexityclass** [comment] 2019-05-29 11:06
> Does the error appear right on startup? Can you show me a screenshot of the full window with the error?

Yes, right on startup. It doesn't appear if I have changes in single file and appear for 2 or more files with changes.

Here is a screenshot
<img width="1099" alt="Screenshot 2019-05-29 at 13 56 25" src="https://user-images.githubusercontent.com/2452092/58552356-e2f55400-821a-11e9-925d-5727801a2df1.png">

**Comment by joaomoreno** [comment] 2019-05-29 15:09
Can you show me the full output of `git status -u` on *both* folders?

**Comment by complexityclass** [comment] 2019-06-05 09:33
> Can you show me the full output of `git status -u` on _both_ folders?

Yes
- /private/var/folders/.../T  Is not a git repository (or any of the parent directories): .git
- /Users/complexity/Development
`On branch some/ios/feature/task-15477
  Your branch and 'origin/some/ios/feature/task-15477' have diverged,
  and have 21 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

  Changes to be committed:
  (use "git reset HEAD ..." to unstage)
  modified: TestHelpers.swift`

**Comment by joaomoreno** [comment] 2019-06-05 09:51
Does it keep happening if you relaunch with `code --disable-extensions`?

**Comment by complexityclass** [comment] 2019-06-05 09:57
> Does it keep happening if you relaunch with `code --disable-extensions`?

I've added this key in mine .gitconfig, but the problem still exists 
`[difftool "vscode"]
	cmd = code --disable-extensions --wait --diff  $LOCAL $REMOTE`

**Comment by joaomoreno** [comment] 2019-06-06 06:16
Oh! I missed that part. It only reproduces when used with `difftool`?

**Comment by complexityclass** [comment] 2019-06-06 11:21
> Oh! I missed that part. It only reproduces when used with `difftool`?

yes, only when It used as a difftool

**Comment by joaomoreno** [comment] 2019-06-06 11:46
Can you show me the output of `Git: Show Git Output` when the issue reproduces?

**Comment by complexityclass** [comment] 2019-06-10 08:34
> Can you show me the full output of `Git: Show Git Output` when the issue reproduces?

Yes, here it is
`Looking for git in: /usr/local/Cellar/git/2.21.0/libexec/git-core/git
  Using git 2.21.0 from /usr/local/Cellar/git/2.21.0/libexec/git-core/git`
  > git rev-parse --show-toplevel
  > git config --get commit.template
  Open repository: /private/var/folders/1g/gq74jq1d3h9cwbz240kdr0x45xywwk/T
  > git rev-parse --show-toplevel
  > git status -z -u
  > git config --get commit.template
  Open repository:  
  Users/complexity/Development/path/to/monorepo/ios/app/SharedComponents/  Storage/Transformers
  > git status -z -u
  > git check-ignore -v -z --stdin
  > git rev-parse --show-toplevel
  > git rev-parse --show-toplevel
  > git rev-parse --show-toplevel
  > git rev-parse --show-toplevel
  > git rev-parse --show-toplevel

**Comment by joaomoreno** [comment] 2019-06-12 08:57
There's a `.git` folder in `/private/var/folders/1g/gq74jq1d3h9cwbz240kdr0x45xywwk/T`. If that shouldn't be there, delete it. Then, check whether this still happens.

**Comment by complexityclass** [comment] 2019-06-12 19:56
> /private/var/folders/1g/
There is no such .git directory
  ls -ld .?* 
  shows:
  drwx------   .AddressBookLocks
  drwx------   .CalendarLocks
  -rw-r--r--  1 .keystoneAgentLock

And 
ls -a | grep git
shows:
vscode-git-askpass-3c14dd24371060ee0b74aafeaa1aab22acb

**Comment by joaomoreno** [comment] 2019-06-14 08:40
That's weird because the log says it was successful in opening a git repo in that location. Something is odd.

**Comment by brunovieira97** [comment] 2019-08-25 17:26
Isn't this a duplicate of #55428?

**Closed** 2019-08-30 12:10 UTC
Labels: bug, git, help wanted
