### ISSUE TITLE
Auto update import on file move - doesn't work

### ISSUE THREAD

**Issue by syedsimanta03** [Microsoft/vscode#70689] opened 2019-03-18 11:22 UTC
Auto update import on file moved not working on VS code latest version for Create React APP. Please save my life.

**Comment by mjbvz** [comment] 2019-03-18 15:24
Please share steps to reproduce the problem.

/needsMoreInfo

**Comment by syedsimanta03** [comment] 2019-03-18 15:33
Steps to Reproduce:

clone https://github.com/g3offrey/example-node-repository
try to move file from folder1 to another folder or to the root
check if the require path in index.js is updated
Does this issue occur when all extensions are disabled?: Yes

If I can do something to help, don't hesitate to ask me.

feature link : https://code.visualstudio.com/updates/v1_24?WT.mc_id=vscodemay18-twitter-brcl#_update-import-paths-when-a-file-is-moved-or-renamed 

"javascript.updateImportsOnFileMove.enabled" : "always",

not working. I am working on a react project and it took me 2hrs to change file path again manually
Thank you +1

**Comment by mjbvz** [comment] 2019-03-21 23:38
Hi, I can't access that repo.

This sounds like a potential duplicate of #62018 as well. Can you test in the next [VS Code insiders build](https://code.visualstudio.com/insiders/) as well (the fix for #62018 was checked in today so it will only go out  in the next build)

**Comment by syedsimanta03** [comment] 2019-04-04 07:06
use this repo to reproduce: https://github.com/kabirbaidhya/react-todo-app

Go TO :- react-todo-app/src/components/ui/    into that repo

Move the footer.js 

To : - react-todo-app/src/components/  here

and check react-todo-app/src/components/ui/TodoList.js

the import path should be updated automatically according to new vs code release the doc has 

 "javascript.updateImportsOnFileMove.enabled": "prompt",
  "typescript.updateImportsOnFileMove.enabled": "always",

But it doesn't even work on VS code insider. I also checked after disabling all extensions. Please try to understand. Everybody saying about it and migrated to webStorm. So plz save my life man.  Thanks

**Comment by mjbvz** [comment] 2019-04-08 23:53
Thanks for the project example.

I think you need a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) file. This makes VS Code treat all js files in your workspace as part of the same project (even if they have not been opened yet) Just create a file called `jsconfig.json` at the root of your project:

```
{
    "compilerOptions": {
        "target": "es6"
    },
    "exclude": [
        "node_modules"
    ]
}
```

See the [jsconfig docs](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) for more info

After creating the config, here are the changes:

![Screen Shot 2019-04-08 at 4 53 06 PM](https://user-images.githubusercontent.com/12821956/55764064-d0328000-5a1e-11e9-90c3-fb548c50971b.png)

**Closed by mjbvz** 2019-04-08 23:53 UTC
Labels: javascript, needs more info
