### ISSUE TITLE
[scss] relative path locations wrong when using @use

### ISSUE THREAD

**Issue by bencresty** [microsoft/vscode#153237] opened 2022-06-26 10:06 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows 10 21H2 - 19044.1766

Steps to Reproduce:

1. Open project with sass-files using @use
2. Ctrl-Click on the @use-paths to see that VS Code can't find the existing and working paths in the following situations:

**issue 1**
``` scss
@use '../globals/colors'; // path is perfectly valid in scss and works so VS Code should go on a click to one folder up and search for 'globals/colors.scss' there, but instead searches on some non-existing absolute path 'globals/colors'. 
```
![image](https://user-images.githubusercontent.com/69322733/175809209-a0d6c5f4-7909-4add-b361-5cee83c17ec3.png)

**issue 2**
``` scss
@use 'globals/colors'; // should find relative path as './globals/colors', but searches for 'node_modules/globals/colors.scss' instead (it works when using `./globals/colors` tho, but this is problematic as the sass migration tool auto-generates this path without a `./`
```
![image](https://user-images.githubusercontent.com/69322733/175809226-0658c386-ceeb-473c-b76b-75a7e1bb3e18.png)

The paths in the examples above are perfectly fine Sass and do work fine with dart-sass too. Only VS Code handles the paths differently/not according to the sass rules.

These issues weren't there AFAIK when using `@import`. But `@import` is deprecated for a long time now and it is expected to get removed this year from the language, so we need to move to `@use`.

[edit] Another issue in VS Code resolving on scss files: webpack aliases aka aliases inside jsconfig.json aren't respected by VS Code. They work just fine and are perfectly valid by the Scss language/compiler, but a ctrl-click on an aliased link in a @use doesn't work in VS Code.

`@use scssGlobals/color` should be resolved to in this order (according to the sass docs):
- relative path starting with `scssGlobals` if it exists
- module `scssGlobals` if it exists (a starting `~` is optional nowadays)
- webpack alias `scssGlobals` if it exists

**Comment by bencresty** [comment] 2022-06-29 10:58
Just updated the issue as there seems to be another issue with VS Code not resolving paths as the scss format describes.

Copy of edit to keep things organised here:

Another issue in VS Code resolving on scss files: webpack aliases aka aliases inside jsconfig.json aren't respected by VS Code. They work just fine and are perfectly valid by the Scss language/compiler, but a ctrl-click on an aliased link in a @use doesn't work in VS Code.

`@use scssGlobals/colors' should be resolved to in this order (according to the sass docs):

relative path starting with scssGlobals if it exists
module scssGlobals if it exists (a starting ~ is optional nowadays)
webpack alias scssGlobals if it exists

**Comment by bencresty** [comment] 2022-06-29 11:08
When searching for a solution online on Sass imports resolving (scss) in VS Code I see lots of people having the same request and same issues and didn't find a solution either. Without good support for imports in scss files IMO the editor is quite lacking.

Isn't it an idea to add a similar construction for scss as there is for Javascript (jsconfig.json) and typescript (tsconfig.json)? IMO  having a `scssconfig.json` with a construction like this would make sense and would solve the alias-problems:

``` json
{
    "include": ["src/scss/*"],
    "compilerOptions": {
        "paths": {
            "scss/*": ["src/scss/*"],
            "scssGlobals/*": ["src/scss/globals/*"],
            "scssIncludes/*": ["src/scss/includes/*"],
        }
    }
}
```

**Comment by aeschli** [comment] 2022-06-29 11:31
If something like `scssconfig.json` exists and is standard, then VS Code should support it. But VS Code should not come up with such a file. It's just an editor.

**Comment by bencresty** [comment] 2022-06-29 11:47
> If something like `scssconfig.json` exists and is standard, then VS Code should support it. But VS Code should not come up with such a file. It's just an editor.

I understand. Eventhough Microsoft 'invented' the tsconfig.json?!

Why not add it to the settings.json instead?

**Comment by aeschli** [comment] 2022-06-29 11:57
We can looking some settings, though.
If you are interested into fixing the issue and improving the import lookup story, the code is at https://github.com/microsoft/vscode-css-languageservice/blob/main/src/services/scssNavigation.ts

**Comment by aeschli** [comment] 2022-06-29 12:07
> Eventhough Microsoft 'invented' the tsconfig.json and jsconfig.json?!

:smile: The Typescript compiler team invented and maintains `tsconfig.json`, not VS Code.

**Comment by zackphilipps** [comment] 2022-08-10 20:13
> These issues weren't there AFAIK when using @import. But @import is deprecated for a long time now and it is expected to get removed this year from the language, so we need to move to @use.

Just adding that this issue applies to `@import` statements as well.

**Comment by slynagh** [comment] 2022-09-07 07:43
This looks like a duplicate of issue [142836](https://github.com/microsoft/vscode/issues/142836)
Some things to note:
- Issue doesn't occur in VSCode `1.63.2`
- Issue occurs only if `package.json` exists at project root

**Closed** 2022-09-12 07:18 UTC
Labels: bug, css-less-scss
