### ISSUE TITLE
Fedora package dependency to libX11-xcb is missing from RPM

### ISSUE THREAD

**Issue by tigert** [microsoft/vscode#107659] opened 2020-09-29 08:44 UTC
- VSCode Version: 1.6.12-1.fc33
- OS Version: Fedora 33 Silverblue (vscode installed in Toolbox container)

Steps to Reproduce:

1. install vscode in fedora toolbox following the instructions: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
2. run code and see "error while loading shared libraries: libX11-xcb.so.1"

Does this issue occur when all extensions are disabled?: irrelevant

Installing libX11-xcb package helps, so it is likely a missing dependency on the RPM package.

**Comment by joaomoreno** [comment] 2020-09-30 12:28
@deepak1556 Might you perhaps know if this is a new dependency?

@tigert What VS Code version is this?

**Comment by deepak1556** [comment] 2020-09-30 18:21
@joaomoreno not a new one https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/rpm/dist_package_provides.json, looks like this has been reported a while back and was never added https://github.com/microsoft/vscode/issues/17142#issuecomment-562790162 . 

I would like to work with you next milestone to check and cleanup missing deps for snap (https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asnap), deb (https://github.com/microsoft/vscode/issues/13089), rpm (https://github.com/microsoft/vscode/issues/17142)

**Comment by joaomoreno** [comment] 2020-10-01 14:09
Oh wow. Closing as a dupe of https://github.com/microsoft/vscode/issues/17142

**Closed by joaomoreno** 2020-10-01 14:09 UTC
Labels: needs more info
