### ISSUE TITLE
Multiple issues while saving SVG files!

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#14206] opened 2016-10-22 12:14 UTC
- VSCode Version: 1.6.1
- OS Version: OS X

I don't have any packages related to SVG files.

Steps to Reproduce:

1) Open this valid SVG:

``` svg
<svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 139.03 140.28"><path d="M0 16.32a72.36 72.36 0 0 1 8.69-1.19h5.88s17.38 4.44 18.94 4.94 7.7 2.94 7.7 2.94a9 9 0 0 1 5.87-2.69c3.37 0 6.12.25 6.12.25s2.5 1.62 3.56 2.44a8.14 8.14 0 0 0 6.25 1.5c3.31-.37 6.75-1.44 7.5-2.19s2.44-3.62 2.44-5.37.19-9.5.31-11.06S74.45 0 75.51 0h1.7a23.74 23.74 0 0 0-.81 4.58 44.6 44.6 0 0 0 2.35 11.26c1.5 4.12 1.69 5.12 1.75 6.5s.25 3.12-1 4.75a53.08 53.08 0 0 1-8.29 7.36 23.27 23.27 0 0 1-5.25 2.19s5.44 7.06 7.06 9.81a54 54 0 0 1 3.37 5.87c.63 1.56 3.53 11.25 4.17 12.94s2.45 4.75 2.83 5.5a3.81 3.81 0 0 1 0 2.13l-1.58 2.95s-4.81 5.5-6.37 6.87-10.23 7.13-12.13 8.13-2.94 2.06-3.87.56a6 6 0 0 1-.56-3c-.06-2.31-1.06-6.62-4.31-8.44s-5.12-2.69-7.5-2.62-7.12.56-7.12.56a65.78 65.78 0 0 1-6.31 2.19 8.79 8.79 0 0 0-1.69.25 51.94 51.94 0 0 0-7.87 5.69 70.78 70.78 0 0 0-5.25 6.14s-3.69 6.24-4.94 8.24a24.87 24.87 0 0 1-3.25 3.94 18.77 18.77 0 0 1-4.62 3.62 18.42 18.42 0 0 1-4.69 1.31H0v-6.06a8.73 8.73 0 0 0 3.81-.12 11.46 11.46 0 0 0 6.69-4.87c2.71-3.78 8.06-11.39 10.25-13.72a36.13 36.13 0 0 1 7.63-6.06c1.37-.61 8.55-3.61 11.83-3.94a95 95 0 0 1 10.06-.12 18.65 18.65 0 0 1 4.19 1.19c1.25.69 3.81 2 4.19 2.75s2 2.75 2.25 4.56.56 4.12.56 4.12l3.5-2.94s4.75-3.94 6.06-5.12 3.94-3.81 4.87-4.5a25.19 25.19 0 0 1 3.44-1.75s.62-.56-.19-1.81a52.5 52.5 0 0 1-3.37-7.75 59.74 59.74 0 0 0-2.56-7.57c-.87-1.62-2.4-5.81-3.67-7.44s-2.45-2.94-2.45-2.94a46.89 46.89 0 0 0-2.62-4.62c-.69-.81-5.19-4.62-5.19-4.62a1.6 1.6 0 0 1 1.62-1.75 22.54 22.54 0 0 0 7.62-2.19c2.13-1.25 5.19-3 5.5-3.37s2.19-2.8 2.19-2.8a7.15 7.15 0 0 0 1.06-2.37 13.87 13.87 0 0 0-1.06-3.5s-1.75 3.5-2.87 4.44-3.94 2.69-5.56 2.75-4.56.75-5.69.81a9.23 9.23 0 0 1-3.19-.12c-1.25-.31-6.31-2.31-7.44-2.75a11.94 11.94 0 0 0-2.81-.56s-2.75.94-4.25 1.62a15.08 15.08 0 0 0-2.12 1.12 18.49 18.49 0 0 0-4.91-2.44c-2.37-.62-10.94-3.37-18.62-3.81s-10-.83-12.87 0A42.75 42.75 0 0 0 .01 23.2v-6.88zm56.33 91.57a4.25 4.25 0 0 1-1.6 3.5 7 7 0 0 1-4.45 1.28 10.46 10.46 0 0 1-4.65-1v-3.23a19.15 19.15 0 0 0 2.81 1 8.32 8.32 0 0 0 2.11.3 3 3 0 0 0 1.76-.44 1.5 1.5 0 0 0 .61-1.3 1.44 1.44 0 0 0-.27-.86 3 3 0 0 0-.79-.72 20.48 20.48 0 0 0-2.13-1.11 10.08 10.08 0 0 1-2.26-1.36 5.09 5.09 0 0 1-1.2-1.52 4.33 4.33 0 0 1-.45-2A4.24 4.24 0 0 1 47.3 97a6.14 6.14 0 0 1 4.08-1.25 9.63 9.63 0 0 1 2.44.3 16.79 16.79 0 0 1 2.43.85l-1.12 2.71a16.44 16.44 0 0 0-2.17-.75 7 7 0 0 0-1.69-.21 2.24 2.24 0 0 0-1.52.46 1.52 1.52 0 0 0-.53 1.2 1.49 1.49 0 0 0 .21.8 2.34 2.34 0 0 0 .68.66 21 21 0 0 0 2.21 1.15 8.78 8.78 0 0 1 3.16 2.21 4.31 4.31 0 0 1 .85 2.76zm18.39-3.67a8.91 8.91 0 0 1-2 6.27 8.76 8.76 0 0 1-11.59 0 8.94 8.94 0 0 1-2-6.29q0-4.1 2-6.26a7.58 7.58 0 0 1 5.81-2.16 7.48 7.48 0 0 1 5.79 2.18 8.94 8.94 0 0 1 1.99 6.26zm-12 0a6.86 6.86 0 0 0 1 4.14 3.65 3.65 0 0 0 3.12 1.39q4.17 0 4.17-5.54t-4.14-5.55a3.68 3.68 0 0 0-3.13 1.4 6.83 6.83 0 0 0-1.01 4.16zM85.6 98.7a3.55 3.55 0 0 0-3 1.48 6.87 6.87 0 0 0-1.08 4.12q0 5.49 4.12 5.49a13 13 0 0 0 4.19-.86v2.91a11.63 11.63 0 0 1-4.51.84 6.89 6.89 0 0 1-5.48-2.17 9.2 9.2 0 0 1-1.9-6.24 10.19 10.19 0 0 1 .93-4.49 6.73 6.73 0 0 1 2.68-3 7.92 7.92 0 0 1 4.09-1 11.05 11.05 0 0 1 4.81 1.16l-1.12 2.83a18.6 18.6 0 0 0-1.85-.76 5.52 5.52 0 0 0-1.88-.31zm8.19 13.75V96.03h3.48v16.42h-3.48zm17.57 0h-9.45V96.03h9.46v2.81h-6v3.6h5.56v2.85h-5.56v4.23h6v2.88zm10.27 0h-3.48V98.93h-4.46v-2.9h12.4v2.9h-4.46v13.52zm16.95 0h-9.46V96.03h9.46v2.81h-6v3.6h5.63v2.85h-5.56v4.23h6v2.88zM4.37 140.05H.94v-16.42h9.41v2.85h-6v4.23h5.57v2.84H4.37v6.49zm9.7 0v-16.42h3.48v16.42h-3.48zm22.69 0h-4.43l-7.12-12.42h-.1q.21 3.29.21 4.69v7.73h-3.11v-16.42h4.39l7.13 12.3h.08q-.17-3.2-.17-4.53v-7.77h3.13v16.42zm14.69 0l-1.24-3.91h-6l-1.19 3.91h-3.69l5.79-16.49h4.26l5.83 16.49h-3.75zm-2-6.83q-1.65-5.31-1.86-6t-.3-1.1q-.37 1.44-2.12 7.11h4.28zm22.89 6.83h-4.43l-7.14-12.42h-.1q.21 3.29.21 4.69v7.73h-3.11v-16.42h4.44l7.13 12.3h.08q-.17-3.2-.17-4.53v-7.77h3.13v16.42zm11.61-13.75a3.55 3.55 0 0 0-3 1.48 6.87 6.87 0 0 0-1.08 4.12q0 5.49 4.12 5.49a13 13 0 0 0 4.19-.86v2.92a11.65 11.65 0 0 1-4.51.84 6.89 6.89 0 0 1-5.48-2.17 9.2 9.2 0 0 1-1.98-6.28 10.19 10.19 0 0 1 .93-4.49 6.73 6.73 0 0 1 2.68-3 7.92 7.92 0 0 1 4.09-1 11.05 11.05 0 0 1 4.81 1.16l-1.12 2.83a18.61 18.61 0 0 0-1.85-.76 5.52 5.52 0 0 0-1.8-.28zm8.19 13.75v-16.42h3.48v16.42h-3.48zm17.57 0h-9.5v-16.42h9.46v2.85h-6v3.6h5.56v2.85h-5.56v4.23h6v2.87zm7.41-6.3v6.3h-3.48v-16.42h4.78a8.19 8.19 0 0 1 5 1.22 4.86 4.86 0 0 1 .81 6.28 5.27 5.27 0 0 1-2.26 1.77q3.71 5.54 4.83 7.15h-3.86l-3.92-6.3h-1.85zm0-2.83h1.09a4.3 4.3 0 0 0 2.44-.55 2 2 0 0 0 .79-1.73 1.8 1.8 0 0 0-.8-1.66 4.87 4.87 0 0 0-2.49-.49h-1.06v4.44zm21.91 4.57a4.25 4.25 0 0 1-1.6 3.5 7 7 0 0 1-4.45 1.28 10.45 10.45 0 0 1-4.65-1v-3.23a19.27 19.27 0 0 0 2.81 1 8.36 8.36 0 0 0 2.11.3 3 3 0 0 0 1.76-.44 1.5 1.5 0 0 0 .61-1.3 1.44 1.44 0 0 0-.27-.86 3 3 0 0 0-.79-.72 20.31 20.31 0 0 0-2.13-1.11 10.14 10.14 0 0 1-2.26-1.36 5.1 5.1 0 0 1-1.2-1.52 4.33 4.33 0 0 1-.45-2 4.24 4.24 0 0 1 1.48-3.43 6.14 6.14 0 0 1 4.08-1.25 9.63 9.63 0 0 1 2.44.3 16.79 16.79 0 0 1 2.43.85l-1.12 2.71a16.44 16.44 0 0 0-2.17-.75 7 7 0 0 0-1.69-.21 2.24 2.24 0 0 0-1.52.46 1.52 1.52 0 0 0-.53 1.2 1.49 1.49 0 0 0 .21.8 2.34 2.34 0 0 0 .68.66 21 21 0 0 0 2.21 1.15 8.77 8.77 0 0 1 3.16 2.21 4.31 4.31 0 0 1 .85 2.76z" fill="#facf4b"/></svg>
```

2) Try to edit something and then save it. VSCode can't save it for some reason. When I try to hit cmd+w and then choose to save the svg file before quit, VSCode still fails to save it.

VSCode becomes slow afterwards (high cpu usage?) and can't save any file before app relaunch.

3) Try to close the VSCode editor using X icon - it doesn't close. When I close it using the "save it immediately" command (hold cmd > right click on VSCode icon at the dock > close now), it shows some glitches in the SVG file code and then quits without saving the file. It also doesn't restore the state of the file after the relaunch.

Looks like VSCode fails to parse the SVG code and then goes into some frustration.
Right now I can't save some needed SVGs and have to edit them using Sublime.

You can also try to paste the given SVG code into svgsprite.jade (this may also turn VSCode into "unsaving mode"):

``` jade
svg(xmlns="http://www.w3.org/2000/svg" style="display: none;")
  symbol(id="icon-arrow-left" viewBox="0 0 25 62")
    path(fill="currentColor" d="M25 1.28L2.59 30.85l22.262 29.87L23.124 62 .148 31.18l.265-.198L0 30.68 23.25 0z")/
  symbol(id="icon-arrow-right" viewBox="")
    path(fill="currentColor" d="M0 1.28l22.407 29.567L.15 60.72 1.88 62l22.97-30.82-.264-.197.414-.303L1.75 0z")/
  symbol(id="icon-billboard" viewBox="0 0 488 407.3")
    path(fill="currentColor" d="M448.6 0H39.4A39.35 39.35 0 0 0 0 39.4V316a39.35 39.35 0 0 0 39.4 39.4h110.5v37.8a14.08 14.08 0 0 0 14.1 14.1h160a14.08 14.08 0 0 0 14.1-14.1v-37.8h110.5A39.35 39.35 0 0 0 488 316V39.4A39.35 39.35 0 0 0 448.6 0zm-14.3 301.2H53.7V53.8h380.6v247.4z")/
    path(fill="currentColor" d="M316.6 189.2l-113.8 65.7a9.68 9.68 0 0 1-14.5-8.4V115.1a9.71 9.71 0 0 1 14.5-8.4l113.8 65.7a9.67 9.67 0 0 1 0 16.8z")/
  symbol(id="icon-calendar" viewBox="0 0 51.9 52")
    path(fill="currentColor" d="M46.9 9.4V47H5V9.4h41.9m5-5H0V52h51.9V4.4z")/
    path(fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="5" d="M25.9 0v12.8M38.9 0v12.8M48.6 39.3H2.2M13.9 0v12.8")/
    g(fill="currentColor" stroke="currentColor" stroke-miterlimit="10" stroke-width=".5")
      path(d="M24.7 27.3a4.55 4.55 0 0 1-1.3 3.6 5.59 5.59 0 0 1-3.8 1.2 5.35 5.35 0 0 1-4-1.5 5.51 5.51 0 0 1-1.5-4v-2.8a5.35 5.35 0 0 1 1.5-4 5.28 5.28 0 0 1 3.9-1.5 6 6 0 0 1 4 1.2 4.51 4.51 0 0 1 1.4 3.5v.1h-3.1a3 3 0 0 0-.5-1.8 2.18 2.18 0 0 0-1.7-.5 1.7 1.7 0 0 0-1.6.9 4.84 4.84 0 0 0-.6 2.3v2.9a3.92 3.92 0 0 0 .6 2.3 2 2 0 0 0 1.8.9 2.54 2.54 0 0 0 1.6-.5 3 3 0 0 0 .5-1.8h2.8v-.5zM36.6 20.7h-5.9v2h1.8a5.58 5.58 0 0 1 3.9 1.3 4.13 4.13 0 0 1 1.5 3.3 4.27 4.27 0 0 1-1.5 3.3 5.58 5.58 0 0 1-3.9 1.3h-5V18.3h9.1v2.4zm-6 4.5v4.2h1.9a2.11 2.11 0 0 0 1.6-.6 2 2 0 0 0 .6-1.5 2 2 0 0 0-.6-1.5 2.11 2.11 0 0 0-1.6-.6h-1.9z")
  symbol(id="icon-checkbox" viewBox="0 0 20.12 15.6")
    path(fill="currentColor" d="M20.05 2.35l-2.2-2.2a.48.48 0 0 0-.7 0l-9.9 9.9-4.2-4.2a.48.48 0 0 0-.7 0l-2.2 2.2a.48.48 0 0 0 0 .7l4.5 4.5 2.2 2.2a.48.48 0 0 0 .7 0l2.2-2.2 10.2-10.2a.64.64 0 0 0 .1-.7z")/
  symbol(id="icon-facebook" viewBox="0 0 239.28 512")
    path(fill="currentColor" d="M159.94 512H64V256H0v-88.23h64l-.1-52C63.9 43.79 83.41 0 168.2 0h70.59v88.24h-44.15c-33 0-34.6 12.33-34.6 35.34l-.13 44.16h79.35L229.93 256H160z")/
  symbol(id="icon-instagram" viewBox="0 0 169.06 169.06")
    path(fill="currentColor" d="M122.41 0H46.65A46.71 46.71 0 0 0 0 46.65v75.75a46.71 46.71 0 0 0 46.65 46.65h75.75a46.71 46.71 0 0 0 46.66-46.65V46.65A46.71 46.71 0 0 0 122.41 0zm31.66 122.41a31.69 31.69 0 0 1-31.66 31.65H46.65A31.69 31.69 0 0 1 15 122.41V46.65A31.69 31.69 0 0 1 46.65 15h75.75a31.69 31.69 0 0 1 31.66 31.65v75.75z")/
    path(fill="currentColor" d="M84.53 41a43.56 43.56 0 1 0 43.56 43.56A43.61 43.61 0 0 0 84.53 41zm0 72.12a28.56 28.56 0 1 1 28.56-28.56 28.59 28.59 0 0 1-28.56 28.53zM129.92 28.25a11 11 0 1 0 7.78 3.22 11 11 0 0 0-7.78-3.22z")/
  symbol(id="icon-keyboard" viewBox="0 0 489.7 489.7")
    path(fill="currentColor" d="M454.9 189.1H294.4v-13.3c0-12.5-10.2-22.7-22.7-22.7h-10V120c0-28-22.8-50.9-50.9-50.9h-55c-9.4 0-17-7.6-17-17V0h-33.9v52.2c0 28.1 22.8 50.9 50.9 50.9h55c9.4 0 17 7.6 17 17v33.1h-10c-12.5 0-22.7 10.2-22.7 22.7v13.3H34.7c-14.9 0-26.9 12-26.9 26.9v246.7c0 14.9 12 26.9 26.9 26.9H455c14.9 0 26.9-12 26.9-26.9V216c-.1-14.9-12.1-26.9-27-26.9zm-150.8 56.5c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27zm.8 79.9v27c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7zm-80.4-79.9c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27zM191 318.8h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7H191c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7zm-46.3-73.2c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27zm-80.1 0c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7H71.3c-3.7 0-6.7-3-6.7-6.7v-27zm40.8 187.5c0 3.7-3 6.7-6.7 6.7H71.3c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27zm32.9-73.9h-27.4c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c0 3.7-3 6.7-6.7 6.7zm206.6 73.9c0 3.7-3 6.7-6.7 6.7H151.3c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h186.9c3.7 0 6.7 3 6.7 6.7v27zm33-73.9h-27.4c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27c-.1 3.7-3 6.7-6.7 6.7zm47.1 73.9c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27zm0-160.5c0 3.7-3 6.7-6.7 6.7h-27.4c-3.7 0-6.7-3-6.7-6.7v-27c0-3.7 3-6.7 6.7-6.7h27.4c3.7 0 6.7 3 6.7 6.7v27z")/
  symbol(id="icon-modular" viewBox="0 0 66.9 62")
    path(fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="6" d="M3 3h44.6v14.2H3z")/
    path(d="M37.2 33.5l8.8 3.2 8.8 3.2-5.7 3.4L60 53.5l-2.1 2.1L47 45.4l-3.4 5.7-3.2-8.8-3.2-8.8m-7.8-7.8l3.4 9.4 3.2 8.8 3.2 8.8 3.4 9.3 5.1-8.5.5-.8 6.7 6.2 3.3 3.1 3.2-3.2 2.1-2.1 3.4-3.4-3.6-3.3-6.3-5.9.4-.2 8.5-5.1-9.3-3.4-8.8-3.2L39 29l-9.6-3.3z" fill="currentColor")/
    path(d="M31.3 37.8H5.8v-8.6h22.5l-1.9-5.6H.2v19.8h33l-1.9-5.6M43.6 29.2l1.2.5 5.7 2.1v-8.2H28.7l14.9 5.6" fill="currentColor")/
  symbol(id="icon-play" viewBox="0 0 458.92 490")
    path(fill="currentColor" d="M0 490V0l458.92 245z")/
  symbol(id="icon-quote" viewBox="0 0 65.6 58.9")
    path(d="M.4 55a71.93 71.93 0 0 0 12.8-11.9c3-3.8 4.5-7.1 4.5-10.1a6.05 6.05 0 0 0-1.6-4.5 13.12 13.12 0 0 0-5.6-2.9 13.71 13.71 0 0 1-7.8-4.9A13.7 13.7 0 0 1 0 12.2a11.57 11.57 0 0 1 3.7-8.7A12.75 12.75 0 0 1 12.9 0a15.57 15.57 0 0 1 12.3 5.6c3.1 3.7 4.7 8.5 4.7 14.3 0 6.2-2.2 12.6-6.5 19.3s-10.7 13.3-19 19.7zM36.1 55a71.93 71.93 0 0 0 12.8-11.9c3-3.8 4.5-7.1 4.5-10.1a6.05 6.05 0 0 0-1.6-4.5 13.12 13.12 0 0 0-5.6-2.9 13.71 13.71 0 0 1-7.8-4.9 13.7 13.7 0 0 1-2.7-8.5 11.57 11.57 0 0 1 3.7-8.7A12.75 12.75 0 0 1 48.6 0a15.57 15.57 0 0 1 12.3 5.6c3.1 3.7 4.7 8.5 4.7 14.3 0 6.2-2.2 12.6-6.5 19.3s-10.7 13.3-19 19.7z")/
  symbol(id="icon-sections" viewBox="0 0 53.6 36.4")
    path(d="M19.3 5v5.7H5V5h14.3m5-5H0v15.7h24.3V0zM48.6 5v5.7H34.3V5h14.3m5-5H29.3v15.7h24.3V0zM19.3 25.7v5.7H5v-5.7h14.3m5-5H0v15.7h24.3V20.7zM48.6 25.7v5.7H34.3v-5.7h14.3m5-5H29.3v15.7h24.3V20.7z" fill="currentColor")/
  symbol(id="icon-smile" viewBox="0 0 60.1 61.5")
    path(d="M28.2 6a22.32 22.32 0 0 1 22.3 22.3A22.76 22.76 0 0 1 44.1 44l4.1 8-11.1-3.2a21.83 21.83 0 0 1-8.9 1.9 22.35 22.35 0 0 1 0-44.7m0-6a28.25 28.25 0 1 0 .1 56.5 28.61 28.61 0 0 0 9.2-1.5l9.1 2.6 13.5 3.9L53.6 49l-2.3-4.4a28.38 28.38 0 0 0 5.3-16.4A28.47 28.47 0 0 0 28.2 0z" fill="currentColor")/
    path(d="M30.9 20.1a5.91 5.91 0 0 0-10.1-5.3zM14 25.5a14.46 14.46 0 0 0 24.6 13.1zM43.9 29.8a5.93 5.93 0 0 0-8.9-7.2z" fill="currentColor")/
  symbol(id="icon-tablet" viewBox="0 0 348.2 512")
    path(d="M348.1 466.5v-421A45.67 45.67 0 0 0 302.6 0H45.5A45.67 45.67 0 0 0 0 45.5v421A45.67 45.67 0 0 0 45.5 512h257.2a45.67 45.67 0 0 0 45.5-45.5h-.1zM174.1 45a8.5 8.5 0 1 1-8.5 8.5 8.49 8.49 0 0 1 8.5-8.5zm0 432.9a17.1 17.1 0 1 1 17.1-17.1 17.16 17.16 0 0 1-17.1 17.1zm140-68.4H34.2V106.9h279.9v302.6z" fill="currentColor")/
  symbol(id="icon-tie" viewBox="0 0 158 227")
    path(d="M0 0v227l79-19 79 19V0H0z" fill="currentColor")/
  symbol(id="icon-useful" viewBox="0 0 49.2 58.5")
    path(fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="6" d="M.1 3h49.1M13.6 27.8l10.5 10.5L46 16.4")/
    path(d="M43.2 27.8v6.1a18.63 18.63 0 0 1-18.6 18.6A18.56 18.56 0 0 1 6 33.9V14.6h37.2v8.9l6-6.4V8.6H0v25.3a24.58 24.58 0 0 0 24.6 24.6 24.58 24.58 0 0 0 24.6-24.6V21.5z" fill="currentColor")/
  symbol(id="icon-vkontakte" viewBox="0 0 304.36 172.24")
    path(d="M261.95 109.52c10.1 9.86 20.75 19.13 29.81 30a87.11 87.11 0 0 1 10.68 15.42c4.11 8 .39 16.71-6.75 17.18h-44.34c-11.44.95-20.56-3.65-28.23-11.47-6.14-6.25-11.82-12.91-17.73-19.37a42 42 0 0 0-8-7.09c-6.05-3.93-11.31-2.73-14.77 3.59s-4.32 13.53-4.67 20.69c-.48 10.44-3.63 13.19-14.12 13.66-22.41 1.06-43.69-2.33-63.45-13.64-17.42-10-30.93-24-42.69-40C34.8 87.49 17.26 53.38 1.5 18.34-2 10.4.58 6.16 9.3 6.01c14.47-.28 28.93-.26 43.41 0 5.88.09 9.77 3.46 12 9a269.09 269.09 0 0 0 29.42 54.52c3.2 4.52 6.46 9 11.11 12.22 5.14 3.52 9.06 2.35 11.48-3.37a37.83 37.83 0 0 0 2.59-11.44c1.15-13.38 1.3-26.74-.71-40.08-1.23-8.32-5.92-13.71-14.23-15.29-4.24-.8-3.61-2.38-1.56-4.8C106.37 2.6 109.73 0 116.41 0h50.11c7.89 1.56 9.64 5.1 10.72 13v55.66c-.09 3.07 1.54 12.19 7.07 14.23 4.43 1.45 7.35-2.1 10-4.9 12-12.73 20.56-27.78 28.21-43.37 3.4-6.85 6.31-14 9.14-21.08 2.1-5.28 5.38-7.87 11.33-7.76h48.23a25.44 25.44 0 0 1 4.26.26c8.13 1.39 10.35 4.88 7.84 12.82-4 12.45-11.65 22.83-19.17 33.25-8 11.13-16.64 21.88-24.62 33.07-7.33 10.22-6.75 15.38 2.36 24.25z" fill="currentColor")/
  symbol(id="icon-logo" viewBox="")
  //- symbol(id="icon-" viewBox="")
```

Here's the video http://take.ms/U8i34

**Comment by bpasero** [comment] 2016-10-22 15:49
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by roblourens** [comment] 2016-10-23 17:52
Please try that. Where does the orange underline on 'currentColor' come from? Please check for errors in the devtools console too.

**Comment by fronteed** [comment] 2016-10-25 19:29
Thanks for your comments. 

Issue is caused by **Color Highlight** extension.

**Comment by jrieken** [comment] 2016-10-26 07:47
fyi @alexandrudima and @aeschli - The [Color Highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight)-extension doesn't do anything on save but it seems to add many decorations. Maybe too much?

**Comment by alexandrudima** [comment] 2016-10-26 12:36
Yeah that's a nice way to make us freeze:

https://github.com/sergiirocks/vscode-ext-color-highlight/blob/master/src/lib/color-highlight.js#L54

e.g.

```js
for (var i = 0; i < (unbounded integer); i++) {
  // call here bulk API with a single entry
}
```

@jrieken I think your custom `vscode` API per extension is our only way to auto-detect this.

**Comment by jrieken** [comment] 2016-10-26 13:05
We might but it's also some wishful thinking ;-) It's hard to define what the individual limits per function should be? Like how often can a method be called during some (standard) interval before it hurts us?

**Comment by jrieken** [comment] 2016-11-07 08:17
@fronteed Can you forward this issue to the *color highlight* extensions?

**Comment by aeschli** [comment] 2016-11-08 14:50
Closing issue. https://github.com/sergiirocks/vscode-ext-color-highlight/issues/11 got created for this issue.

**Closed by aeschli** 2016-11-08 14:50 UTC
Labels: caused-by-extension
