### ISSUE TITLE
Typescript import statements

### ISSUE THREAD

**Issue by activebiz** [Microsoft/vscode#818] opened 2015-11-30 13:05 UTC
For import statement in typescript it would be nice if we can reference an object in a class (for e,g.) and the IDE can write (when you click on the object reference Foo in example below) an import statement for you.
For e.g.

`import {Foo} from "../../../bar/somelongpath/foo"`

`export class Test {`
`private f: Foo;`
`}`

Webstorm already provides this and it makes a lot of difference (productivitywise) as you dont have to manually type and figure out the path to the import statement.

**Comment by alexandrudima** [comment] 2015-11-30 13:45
Should this be a quick fix proposal?

**Comment by activebiz** [comment] 2015-11-30 13:48
apologies about this. I guess its not. Kindly move to the appropriate area as required. Or let me know if this is something I can do myself.
Thanks

**Comment by alexandrudima** [comment] 2015-11-30 15:35
@activebiz No worries, you filed the issue in the right spot. I was suggesting a solution to @dbaeumer :)

**Comment by activebiz** [comment] 2015-11-30 15:50
Nice 1 :)

**Comment by caseyhoward** [comment] 2016-01-14 01:05
Since this isn't implemented, is there a better way than having to manually find out how to navigate to the file and typing in the import statement by hand?

**Comment by atifsyedali** [comment] 2016-03-02 20:45
> is there a better way than having to manually find out how to navigate to the file and typing in the import statement by hand?

We are really interested in that question as well. I have scoured the web and tried various IDEs but seems like Webstorm is the only one that supports this. Would be really nice if VSCode supported it.

How do folks at Microsoft writing lots of Typescript code manage their imports?

**Comment by pivalig** [comment] 2016-03-04 18:53
+1. I use this feature in WebStorm but really want to work only in VSCode

**Comment by frederikschubert** [comment] 2016-03-04 19:18
There is already an [issue](https://github.com/Microsoft/TypeScript/issues/188) in the typescript repo for this and it is scheduled for the 2.0 release.

**Comment by egamma** [comment] 2016-03-07 09:19
Closing as a dupe of Microsoft/TypeScript#188

**Comment by dfaivre** [comment] 2016-05-10 19:51
@egamma - just for clarity, if the linked issue gets implemented, VS Code will automatically get it as well?  This is feature is one the main reasons I still use WebStorm over VS Code.

**Comment by egamma** [comment] 2016-05-11 14:50
>@egamma - just for clarity, if the linked issue gets implemented, VS Code will automatically get it as well? 

this is correct, the completion list shown in VS Code are computed by the TypeScript server that also supports JavaScript.

**Comment by caseyhoward** [comment] 2016-08-05 16:29
@egamma Are you referring to only auto-completing as you type import statements? That would be somewhat useful, but the most import thing for me is that if vscode autocompletes a reference to something that is not in scope where it autocompletes, then it adds an import statement to the top of the file for it. I don't feel like I should ever have to type an import statement by hand, with autocomplete help or not.

**Comment by atifsyedali** [comment] 2016-08-05 18:17
Agree with @caseyhoward on automatically adding import statements to the top of the file. That's what I was referring to also in my previous comment. Webstorm currently does.

**Comment by luisfarzati** [comment] 2016-09-18 22:06
Funny thing is the [Vim plugin](https://github.com/Quramy/tsuquyomi) [seems to do this](https://github.com/Quramy/tsuquyomi/raw/master/screen.gif) 😄

**Comment by tonymk** [comment] 2016-09-19 07:33
https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

**Comment by masaeedu** [comment] 2016-09-30 08:56
@egamma I think you've misunderstood the feature request. From the issue description:

> For import statement in typescript it would be nice if we can reference an object in a class (for e,g.) and the IDE **can write an import statement for you**.

I don't think this is implemented by the TypeScript language service. Could this please be reopened?

**Comment by egamma** [comment] 2016-09-30 11:58
@masaeedu apologies if I misunderstood you. 

We have actually enriched the language API in 1.5 so that the language service cannot only provide a single completion but also a set of edits. See https://code.visualstudio.com/updates/v1_5#_extension-authoring the section 'powerful completion items'. We have added this so that this feature can be provided by the C# language service.  The same will eventually happen in the TypeScript language service.

**Comment by masaeedu** [comment] 2016-09-30 12:12
That is amazing news! The issue you linked to however (Microsoft/Typescript#188), is not quite what is being asked for. The requested feature is the ability to reference any top level export from any resolvable module (without explicitly importing it), and have the appropriate import statement inserted at the top of the file. This feature can be found in WebStorm, as well as in the Roslyn compilers. See for example:

![Visual Studio offering to complete missing imports](https://ysvyza.by3302.livefilestore.com/y3mP7uk3BxgibjUCjapVVF7Z9u10drgUd3UQAmonXLhTReHls71yfShX1OmCwbjlZmb5kth3jbSg5YZNJDAz32n3OaMqVrKEHNWH5mH4V1sG-Twv71RShO4VEPXUoI7xig6YbugelzfLrRTx1_qOwEiEAvV5naWeyQYzVzrghOwy7Q/devenv_2016-09-30_08-07-50.png?psid=1)

It would be a huge productivity boost to have something like this in VS Code (or even better, in the language service!). I can confirm that with Visual Studio Code 1.5.3 pointing to tssdk v 2.0.3, I don't see any suggestions for adding an import statement if I reference a top level export from a module I haven't imported yet.

**Comment by masaeedu** [comment] 2016-09-30 12:19
It is possible that you would need some work on the part of module authors to advertise which of their exports should be advertised for auto-import in this way.

**Comment by sophistyx** [comment] 2016-10-12 13:16
isn't that what the concept of 'export' is all about - exporting something so that others can 'import' it?

**Comment by arlair** [comment] 2016-10-30 14:35
I'm confused this is closed. As mentioned, the issue referenced for closing this as a duplicate does not seem to mention automatically creating an import statement in its description.

I installed some of the third party auto import VS Code plugins. No seemed to handle the case I was attempting, auto import statement for a decorator, but WebStorm could.

It seems this should either be re-opened or labelled as not an accepted feature.

**Comment by dbaeumer** [comment] 2016-10-31 10:31
This is indeed not a dup of https://github.com/Microsoft/TypeScript/issues/188.

@waderyan we need to check with TS if they have a feature request for this. What people at the end of the day want is something like this:

- there is a type Orange in the system
- in a file A which doesn't import Orange yet the user types Org<code complete>
- the system should propose Orange. Accepting it should insert Orange and should add a corresponding import statement.

**Comment by waderyan** [comment] 2016-11-02 20:33
I think we're looking for something like this - https://github.com/Microsoft/TypeScript/issues/7849

@bowdenk7  - do you know of a better duplicate in TS's repo then the one I posted above?

**Comment by hadalin** [comment] 2016-11-04 12:39
WebStorm also has an option to use single quotes for generated code

![screen shot 2016-11-04 at 13 31 46](https://cloud.githubusercontent.com/assets/1746370/20005528/2aa0243e-a293-11e6-8bfb-c3789a8cbde3.png)

It'd be cool to have this option here too.

**Comment by dbaeumer** [comment] 2016-11-07 10:05
@waderyan Microsoft/TypeScript#7849 is what we are looking for.

**Comment by waderyan** [comment] 2016-11-07 16:20
Great. Leaving this open on our end to track the completion of the work.

**Comment by MrCroft** [comment] 2016-11-08 08:36
This and a more advanced git integration (like webstorm provides) are the only 2 reasons to why I still use WebStorm instead of VScode. Not sue which one would be more important than the other... I guess this automatic import issue, even if not by much.

**Comment by donaldpipowitch** [comment] 2016-12-15 22:48
> I installed some of the third party auto import VS Code plugins. None seemed to handle the case I was attempting, auto import statement for a decorator, but WebStorm could.

[This plugin](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter) seems to solve this for me. This plugin currently has everything I need. I don't think it was mentioned here before.
But I also would like to see this feature as part of the language service as well.

**Comment by gulshan** [comment] 2017-03-03 01:14
Probably this was done in the last release.

**Comment by thekalinga** [comment] 2017-03-03 09:20
I dont think its fully supported. We need to type the whole class & then the quickfix can import.

**Comment by pgrm** [comment] 2017-03-10 13:01
Currently the import file names are always enclosed in double quotes `"` and I'm manually changing it to single quote `'` is there any way to configure that?

**Comment by lekhnath** [comment] 2017-03-10 17:55
VSCode auto imports, Linters warns, I do a fix. It would be really great to be able to provide quote option through settings.

**Comment by jbrownson** [comment] 2017-03-10 17:58
There are similar problems w/ alphabetical ordering of things using tslint's "ordered-imports" feature.

**Comment by lekhnath** [comment] 2017-03-10 18:25
Funny thing is it imports angular `Component` decorator from `@angular/core/typings/core` instead of `@angular/core`.

**Comment by mjbvz** [comment] 2017-03-10 22:38
The type of quote used for imports is tracked by https://github.com/Microsoft/TypeScript/issues/13270

Sorting imports is being tracked by https://github.com/Microsoft/TypeScript/issues/10020


Closing this issue as the original feature has been implemented. If you run into any bugs with the import quick fix or have any feature suggestions around import, please open new issues.

Thanks

**Closed by mjbvz** 2017-03-10 22:38 UTC
Labels: feature-request, typescript

**Comment by MetodoDigital** [comment] 2017-05-18 11:34
As @adyavanapalli very well mentioned, you can edit the **_typescript.json_** file to get around this issue on `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/` for MacOS and `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\` for Windows.

Thx buddy.
