### ISSUE TITLE
tsdk: changing TS version from status bar does not update it in the status bar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#19423] opened 2017-01-26 09:29 UTC
Testing the new TS status bar:
* have a workspace with NPM installed typescript@next
* open the workspace
* click on the status bar and change to TS 2.2.next
=> after doing so the status bar is still showing 2.1.5 being used.

**Comment by schmuli** [comment] 2017-01-26 10:20
I just ran into this new change, and after restarting VSCode the correct version is displayed in the Status Bar.

However, now that `typescript.tsdk` is no longer a workspace setting, where is this preference actually saved, and how would I share it with other machines/users, like we used to do with `.vscode/settings.json`?

**Comment by schmuli** [comment] 2017-01-26 10:45
Having looked at the commit log, I see that the setting is now stored in `localStorage`, but still leaves the issue that this setting is now un-shareable between computers and/or team members. 

Can't the `useWorkspaceVersion` key be part of user/workspace settings, rather than `localStorage`?

**Comment by schmuli** [comment] 2017-01-26 10:46
@bpasero See also #19427

**Comment by rob3c** [comment] 2017-01-26 17:29
Yes, this new disabling of `typescript.tsdk` in the workspace settings.json is quite ~annoying~ surprising and just asking for trouble. How are we supposed to share the setting via the git repo without the annoying vscode popup asking what version to use? I think it's pretty clear that if we've gone to the trouble of setting a value in the workspace settings, that THAT is the one we want to use.

**Comment by kylecordes** [comment] 2017-01-26 17:41
I think the item I just entered #19451 might be a partial semantic duplicate of this item.

The essence is: it will be most helpful for a great many of our use cases if the "use the version of TypeScript that this workspace uses" setting was either the default, or was sitting in the .vscode/settings file in the workspace. Sticking it over in invisible localstorage seems awful, I had a brief flashback to the Windows Registry era upon reading about it.

**Comment by rob3c** [comment] 2017-01-26 22:10
@kylecordes While related, I think your #19451 is worth keeping open on its own. The workspace-specific tsdk config regression needs to be addressed specifically IMHO.

**Comment by mjbvz** [comment] 2017-01-30 20:44
Closing since the new flow changes how this works. You also need to reload after selecting a new TS version. By design, we continue to show the old version in the status bar because it remains active until reload.

**Closed by mjbvz** 2017-01-30 20:44 UTC
