### ISSUE TITLE
Usability: NVDA is not announcing when "stepover","stepout","stepinto", are added to the code while debugging is on.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17251] opened 2016-12-15 06:40 UTC
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open Visual studio code editor.
2.open any file and using "Ctrl+1" key  navigate to the  first vs code editor.
3.Adding a "breakpoint" to the line of code By pressing  "F9".
4.Start debugging by pressing "F5",key and observe NVDA behaviour.
5.Apply "stepover","stepout","stepinto" by pressing "F10","F11" and "shift+F11" ,key respectively.

**Expected result:**
NVDA should recite proper information when "stepover","stepout","stepinto",  are  added to the code while debugging is on.

**Actual Result:**
NVDA is not providing any information when "stepover","stepout","stepinto",  are  added to the code while debugging is on.

**User Impact:**
Screen Reader user doesn't get to know that "stepover","stepout","stepinto", are added to the code while debugging is on.

**Attachments:**
![narratorbuddyinformation_visualstudiocodeeditor_debuggingfeatures](https://cloud.githubusercontent.com/assets/22956130/21214227/56ff038c-c2bf-11e6-8ab2-92bf54668ef4.jpg)
![nvda_speechviewerinformation_vscodeeditor_debuggingfeatures](https://cloud.githubusercontent.com/assets/22956130/21214226/56fee85c-c2bf-11e6-8e6d-4bb751cc7862.jpg)

**Comment by isidorn** [comment] 2016-12-20 11:15
This works for me as shown in the attached gif - also works if I use keyboard and not mouse.
Namely whenever a debugger is stopped we announce a message in the form
"Debugging paused, reason step, module.js 559 "

@WiproPSAccTest Are you not getting these messages? I see you are using vscode 1.6.1, can you please try with 1.8.1 as I can not reproduce with the latest
Closing until more data is provided

![step](https://cloud.githubusercontent.com/assets/1926584/21348454/8b06c862-c6ad-11e6-9012-925aa0f79471.gif)

**Closed by isidorn** 2016-12-20 11:15 UTC
Labels: accessibility
