### ISSUE TITLE
diff view scroll bar transparent

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#109866] opened 2020-11-02 21:56 UTC
Issue Type: <b>Bug</b>

1. Create two files with long lines
1. Open the diff view on them (F1 -> compare with...)
1. the diff window has a diff scroll bar at the right, and a regular scroll bar at the right of each side of the diff.
1. The text of the files is visibale through the regular scroll bar
1. select a word and press Ctrl+F. The mark in the scroll bar indicating where matches are found may be barley visible over the text, dpending on color scheme. See example screen shot

![image](https://user-images.githubusercontent.com/1149432/97923616-f0dfca80-1d66-11eb-8747-54c18a96dd40.png)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.49GB free)|
|Process Argv|--crash-reporter-id 6949b6e9-d952-4b8f-a136-284374926c80|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4054)|
|Memory (System)|15.54GB (0.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4054)|
|Memory (System)|15.54GB (0.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4054)|
|Memory (System)|15.54GB (0.29GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
material-icon-theme|PKi|4.4.0
gitlens|eam|10.2.2
todo-tree|Gru|0.0.186
me-vscode|ME-|0.0.9
git-graph|mhu|1.27.0
python|ms-|2020.10.332292344
cpptools|ms-|1.1.0-insiders3
hexeditor|ms-|1.3.0

</details>

**Comment by eamodio** [comment] 2020-11-02 23:50
The transparency (or not) of the left side is controlled by the theme.

Duplicate of https://github.com/microsoft/vscode/issues/109760

**Closed by eamodio** 2020-11-02 23:50 UTC
Labels: *duplicate
