### ISSUE TITLE
Extension readmes and Markdown previews cut off on high-DPI monitor / with zoom

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#13894] opened 2016-10-17 16:42 UTC
- VSCode Version: 1.6.0 / 1.7.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Use a high-DPI monitor and/or increase zoom level
2. View an extension readme or preview markdown

![screenshot 33](https://cloud.githubusercontent.com/assets/10532611/19446505/67846016-9499-11e6-87ca-78c94a400e2c.png)

**Comment by roblourens** [comment] 2016-10-17 17:21
Dupe of #5745

**Closed by roblourens** 2016-10-17 17:21 UTC
