### ISSUE TITLE
[feature request] Go to CSS symbols in any file

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#105615] opened 2020-08-28 19:07 UTC
The [documentation says](https://code.visualstudio.com/docs/languages/css#_go-to-symbol-in-file) that we can go to a CSS symbol from "any file", but this doesn't seem to work.

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T22:01:14.734Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.52-1-MANJARO
```

Steps to Reproduce:

1. Open a CSS file (f.e. an index file that `@import`s other CSS files and doesn't contain any style rules).
2. Try `ctrl+shift+o` to go to symbols.
3. There are no symbols to go to.

Does this issue occur when all extensions are disabled?: **Yes**

![Peek 2020-08-28 12-07](https://user-images.githubusercontent.com/297678/91606502-067be280-e927-11ea-9173-8445dd8e559e.gif)

**Comment by trusktr** [comment] 2020-08-28 19:09
I may have misread "any file". Perhaps the documentation meant to say "In any given file, you can go to symbols in that file". But I may be thinking that it should allow me to "go to symbols in any file", which is a little different.

**Comment by trusktr** [comment] 2020-08-28 19:14
I updated the title to convert this into a feature request. We should perhaps also update the doc wording.

**Comment by aeschli** [comment] 2020-08-31 09:59
The built-in CSS extension does not offer workspace symbols. Infact we have no features that go cross files, except from opening links.

https://github.com/microsoft/vscode/issues/47331 is the overarching issue for that. I'd like to close it as a duplicate of that one.

**Comment by aeschli** [comment] 2020-08-31 09:59
I also improved the documentation

**Closed by aeschli** 2020-08-31 09:59 UTC
