### ISSUE TITLE
Installing extension from VSIX always prompts for reload

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#67435] opened 2019-01-29 17:59 UTC
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67298

When installing an extension that doesn't require a reload (ex. docker) from a VSIX, there is still a notification that says "Successfully installed the extension. Reload to enable it." even though the extension is already active

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

**Comment by sandy081** [comment] 2019-01-29 18:05
Duplicate of #67389

**Closed** 2019-01-29 18:05 UTC
Labels: *duplicate
