### ISSUE TITLE
Can’t launch VScode since version 1.40 - hangs with “The Window is no longer responding” error

### ISSUE THREAD

**Issue by stukey** [microsoft/vscode#88068] opened 2020-01-03 22:48 UTC
Since the first Oct 2019 update to VSCode (v. 1.40) I've been seeing this issue. After updating to the latest version, VSCode will not launch, either from Start menu or cmd prompt. The VSCode window appears (empty) and then hangs. Eventually the following error appears:
 
"The Window is no longer responding. You can reopen or close the window or keep waiting"
 
Reopen, Keep Waiting, Close
 
Whichever option you try (Reopen/Keep Waiting), the problem persists. If you click 'Close', the app quits as expected but won't re-open. This started in Oct 2019. Last working version is VSCode x64 1.39.2. Have tried all versions since 1.39.2 and they all show the same issue across multiple different Windows 2016 servers. Today I tried latest release 1.41.1 and same issue. Tried uninstalling and re-installing and deleting VScode directory in AppData. Same issue. If I uninstall and re-install version 1.39.2, VSCode launches and works as expected without any issues,
 
This is happening across 6 different Windows 2016 servers. Using 64-bit system version of VSCode.
 
Here's the verbose output launching VSCode from the cmd prompt:
 
code.exe --verbose
 
[main 2020-01-03T17:20:33.942Z] Starting VS Code
[main 2020-01-03T17:20:33.943Z] from: f:\Program Files\Microsoft VS Code\resources\app
[main 2020-01-03T17:20:33.946Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false
}
[main 2020-01-03T17:20:33.949Z] Resolving machine identifier...
[main 2020-01-03T17:20:34.503Z] Resolved machine identifier: a18f04566926128a9432f98bf4d7f418ad2d5324caacb7cd5f95fd97ca15b9b1 (trueMachineId: undefined)
[main 2020-01-03T17:20:34.524Z] update#setState idle
[main 2020-01-03T17:20:34.527Z] [storage state.vscdb] open(c:\Users\xxxx\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2020-01-03T17:20:34.530Z] lifecycle (main): phase changed (value: 2)
[main 2020-01-03T17:20:34.533Z] windowsManager#open
[main 2020-01-03T17:20:34.610Z] lifecycle (main): phase changed (value: 3)
[main 2020-01-03T17:20:34.612Z] telemetry/optInStatus { optIn: true }
[main 2020-01-03T17:20:34.613Z] telemetry/update:win32SetupTarget { target: 'system' }
[main 2020-01-03T17:20:34.614Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2020-01-03T17:20:34.790Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2020-01-03T17:20:34.790Z] [storage state.vscdb] getItems(): 0 rows
[main 2020-01-03T17:20:34.903Z] [storage state.vscdb] updateItems(): insert(Map(3) {telemetry.instanceId => 14634e4c-982f-405f-9d27-8d8d68943579, telemetry.firstSessionDate => Fri, 03 Jan 2020 17:20:34 GMT, telemetry.currentSessionDate => Fri, 03 Jan 2020 17:20:34 GMT}), delete(Set(0) {})
[main 2020-01-03T17:20:34.905Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2020-01-03T17:20:34.907Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.instanceId','14634e4c-982f-405f-9d27-8d8d68943579'),('telemetry.firstSessionDate','Fri, 03 Jan 2020 17:20:34 GMT'),('telemetry.currentSessionDate','Fri, 03 Jan 2020 17:20:34 GMT')
[main 2020-01-03T17:20:34.911Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2020-01-03T17:20:37.621Z] getShellEnvironment: running on Windows, skipping
[main 2020-01-03T17:21:04.527Z] update#checkForUpdates, state =  idle
[main 2020-01-03T17:21:04.528Z] update#setState checking for updates
[main 2020-01-03T17:21:04.531Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/26076a4de974ead31f97692a0d32f90d735645c0
[main 2020-01-03T17:21:08.254Z] [Error: net::ERR_NAME_NOT_RESOLVED]
[main 2020-01-03T17:21:08.254Z] update#setState idle
[main 2020-01-03T17:21:08.257Z] telemetry/update:notAvailable { explicit: false }
[main 2020-01-03T17:23:23.455Z] [VS Code]: detected unresponsive
[main 2020-01-03T17:23:23.459Z] telemetry/windowerror { type: 1 }
[main 2020-01-03T17:24:36.082Z] Lifecycle#window.on('closed') - window ID 1
[main 2020-01-03T17:24:36.082Z] Lifecycle#onWillShutdown.fire()
[main 2020-01-03T17:24:36.085Z] [storage state.vscdb] close()
[main 2020-01-03T17:24:36.087Z] Lifecycle#app.on(window-all-closed)
[main 2020-01-03T17:24:36.087Z] Lifecycle#app.on(before-quit)
[main 2020-01-03T17:24:36.087Z] Lifecycle#onBeforeShutdown.fire()
[main 2020-01-03T17:24:36.093Z] Lifecycle#app.on(will-quit)
 
Can anybody help or suggest anything to try to fix this issue? I am only seeing this on our Windows 2016 servers. The latest version works fine on my Windows 10 laptop.

**Comment by stukey** [comment] 2020-02-03 12:18
Any update on this issue? It’s still a problem for us on all of our servers!

**Comment by stukey** [comment] 2020-02-03 22:45
Hi @deepak1556 can you help? This is becoming a major issue for us across multiple Windows 2016 servers...

**Comment by juanpecatala** [comment] 2020-02-11 11:19
I have the same problem on Windows Server 2019 servers.

**Comment by deepak1556** [comment] 2020-02-18 19:11
@stukey @juanpecatala can you try the workaround mentioned in https://github.com/microsoft/vscode/issues/84914#issuecomment-556033410 ? This is a known issue with citrix environments.

**Comment by stukey** [comment] 2020-02-19 09:27
@deepak1556 Thank you. The registry workaround in the above linked issue resolved the problem for me. We were able to update VScode to latest version on all of our Citrix servers and launch the app without issue.  Do you know why this suddenly became an issue with VSCode version 1.40 and later? It was working perfectly well on our Citrix servers before that version was released. What changed? Thanks

**Comment by juanpecatala** [comment] 2020-02-19 10:48
Hi, it seems to work.
But it takes longer to open than in the previous versions.

**Comment by deepak1556** [comment] 2020-02-20 04:03
@stukey Thanks for confirming the fix, as for what changed, citrix just started rejecting apps with delay load mechanisms for dlls, its something that should be fixed on their end, please follow up with citrix team for a more concrete solution and do update here with progress, would help other community members.

**Comment by deepak1556** [comment] 2020-02-20 04:04
@juanpecatala can you open a separate issue for the slow startup following the steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly ,  I am afraid it might another citrix issue for bypassing their hooks but better to track separately.

I am closing this issue as the root cause is now mitigated.

**Closed by deepak1556** 2020-02-20 04:04 UTC
Labels: freeze-slow-crash, needs more info, windows
