### ISSUE TITLE
Debugger REPL does not work until any breakpoint triggered

### ISSUE THREAD

**Issue by s0m3on3** [microsoft/vscode#137608] opened 2021-11-21 11:33 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2
- OS Version: Windows 10, Linux Mint 20 Ulyana (used over ms-vscode-remote.remote-ssh plugin v0.66.1, but it also does not work using the host system without any plugins)

Steps to Reproduce:

1. Create a file index.js
```js
const main = async () => {
    console.log("hello world");

    let i = 0;
    setInterval(() => {
        console.log(`timer: ${i++}`);
    }, 1000);
};

main();
```
2. Create a launch.json file
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/index.js"
        }
    ]
}
```
3. Run debugger using "Launch Program" configuration
4. You will see that REPL does not respond anything you enter
![image](https://user-images.githubusercontent.com/15943003/142759712-144f862f-88c5-4da6-a85c-aff9ad724639.png)
5. If you set any breakpoint (for example at console.log in the interval function) the REPL starts working and then it continues working in runtime (when you remove the breakpoint).
![image](https://user-images.githubusercontent.com/15943003/142759761-1b40f755-a2a8-4d3d-bd6e-de9ca6a4530c.png)
6. Then if you remove the breakpoint and restart the configuration, the REPL also works fine until you reload the project or restart the window
![image](https://user-images.githubusercontent.com/15943003/142759812-7705e714-52e6-4a21-a33d-d20a9b8f74c4.png)

Expected behavior:
The REPL can respond on any entered command without having any breakpoint triggered.
It worked fine in vscode 1.61.

**Comment by gjsjohnmurray** [comment] 2021-11-21 14:00
Maybe a duplicate of #137460

**Closed** 2021-11-21 15:07 UTC
Labels: *duplicate
