### ISSUE TITLE
VSCode overwrites externally modified file (that is also modified but not saved in VSCode)

### ISSUE THREAD

**Issue by aardappel** [Microsoft/vscode#41120] opened 2018-01-04 00:10 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Modify file in VSCode, but don't save.
2. Modify it also in other editor (in my case, Visual Studio), and save.
3. Maybe: hibernate computer, and turn back on.
4. Come back to VSCode, make edit to stale version (not noticing it is stale), save, edits from (2) are now gone.

Not sure if this is correct, since when I just tried without (3), I did indeed get `Failed to save 'myfile.ext': The content on disk is newer. Click on Compare to compare your version with the one on disk.`. I did not however get this warning when the issue happened to me, which almost cost me 2 days worth of edits (if it weren't for Visual Studio being able to undo all the way back).

If I have to guess, this bug may be related to hibernating, as the stale file in VSCode had been hanging there for 2 days, with the computer hibernated at least once.. maybe this affects file system watching?

**Comment by bpasero** [comment] 2018-01-04 07:33
@aardappel I just tried to reproduce and cannot. The only way this can happen is if the modification time of the file on disk is wrong (or in the past) and VS Code happily overwrites it because it thinks the file did not change outside. 

Can you reproduce every time you try or not?

**Comment by aardappel** [comment] 2018-01-04 16:18
@bpasero no, I am afraid I cannot.

**Comment by bpasero** [comment] 2018-01-05 06:48
Too bad, closing until we know more about how to reproduce.

**Closed by bpasero** 2018-01-05 06:48 UTC
Labels: needs more info
