### ISSUE TITLE
FontStyle not updating

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#29421] opened 2017-06-26 06:37 UTC
Discovered in #29393

The pull requests makes a change so that settings can specify color and fontStyle overrides for themes.

Updating colors works just fine, but if I add a setting for modifying the font style of a scope, the font style of those matching tokens won't actually re-render until I type to modify a token and then only that token is updated. See the gif below for an example.

**Note:** if I use the theme switcher to change to a new theme that has a font style applied for a scope.

![image](https://user-images.githubusercontent.com/2957173/27527129-546b01de-5a4a-11e7-9010-fadd636c14fa.png)

**Comment by aeschli** [comment] 2017-08-31 10:58
Found the problem. Fixed for August. Duplicate of #33495

**Closed by aeschli** 2017-08-31 10:58 UTC
Labels: feature-request, tokenization
