### ISSUE TITLE
Web: Tasks sync CustomExecution task should flush all data on close

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90528] opened 2020-02-12 14:07 UTC
From: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=67363&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f43345f0-e90d-5fa7-e3aa-7e223f6f3b99&l=656

```
 1) workspace-namespace Tasks sync CustomExecution task should flush all data on close:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```

**Comment by alexr00** [comment] 2020-02-12 14:39
FYI @Tyriar looks like it's happening again.

**Comment by Tyriar** [comment] 2020-02-12 15:24
@bpasero was this flaky or failing all the time?

**Comment by bpasero** [comment] 2020-02-12 15:41
@Tyriar I think I have seen this at least twice in the past days. I am not sure it fails all the time. Note that our web integration tests only run as part of our product builds, so the frequency is a lot less.

**Comment by Tyriar** [comment] 2020-04-27 14:30
@alexr00 I've disabled these tests on web, I believe this flakiness is the same as in the terminal where some terminals just don't launch https://github.com/microsoft/vscode/issues/96057

**Comment by joaomoreno** [comment] 2020-06-21 18:20
@Tyriar Is this still an issue?

**Comment by alexr00** [comment] 2021-03-16 15:26
Duplicate of #96057

**Closed by alexr00** 2021-03-16 15:26 UTC
Labels: bug, integration-test-failure, web
