### ISSUE TITLE
"contrastActiveBorder" blocks "panelTitle.activeBorder"

### ISSUE THREAD

**Issue by tweakimp** [Microsoft/vscode#45447] opened 2018-03-09 22:34 UTC
VSCode Version: 1.22.0-insider
In the `color-theme.json` file that sets the colors, the setting `contrastActiveBorder` blocks `panelTitle.activeBorder`. I dont know if this is intended or not, but it seems that they share the same distance from the object they draw the border around.

Steps to Reproduce:
1. Set `panelTitle.activeBorder` to any color.
2. Set `contrastActiveBorder` to any color, like `#ffffff`. (Issue even happens with 0% opacity, like `#ffffff00`)
Reload.

3. Panel title does not have an active border.
4. Comment out `contrastActiveBorder`.
Reload.
5. Panel title does have an active border.

**Comment by bpasero** [comment] 2018-03-10 09:36
I think they are intentionally mutually exclusive.

**Comment by isidorn** [comment] 2018-03-12 10:10
Yes,  the contrastActiveBorder is for the outline which is mostly used in the high contrast theme and it has priority over regular colors. Since in high contrast we do not want to use regular activeBorder colors - it would be too many colors and the contrast would not be as we designed.
Closing as designed.

**Closed by isidorn** 2018-03-12 10:10 UTC
Labels: themes
