### ISSUE TITLE
Preserve case can overlap textbox

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#165856] opened 2022-11-08 18:47 UTC
<img width="357" alt="image" src="https://user-images.githubusercontent.com/4544166/200649764-03c18ff8-7178-4cb4-9b10-93eb678384d8.png">

**Comment by andreamah** [comment] 2022-11-08 18:49
Duplicate of #151624

**Closed by andreamah** 2022-11-08 18:49 UTC
Labels: *duplicate
