### ISSUE TITLE
Allow to assign multiple languages for one file extension

### ISSUE THREAD

**Issue by brucebrophy** [Microsoft/vscode#22415] opened 2017-03-10 19:52 UTC
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: Mac0S 10.12

```
"files.associations": {
      "*.php": "php, html"
    }
```

The above code block opens up .php files as HTML documents,

This bottom code blocks does not provide HTML code hinting at all

```
"files.associations": {
      "*.php": "html, php"
    }
```

**Comment by rbenson** [comment] 2017-03-11 01:12
@ramya-rao-a I just tried with a custom language I made. I tried adding HTML to it, and no change. I assumed adding the associate would offer snippets for both languages, and I just saw the original, HTML's weren't added

**Comment by bpasero** [comment] 2017-03-12 07:12
@brucebrophy where did you find this syntax? We do not allow you to set multiple languages for one file association currently.

**Comment by brucebrophy** [comment] 2017-03-12 17:21
Someone posted the syntax on a forum, I should have referred to the docs for VSC before creating an issue.

Would be a nice feature to include in an already awesome editor though. :)

**Comment by rbenson** [comment] 2017-03-14 05:31
@bpasero  I found it from you http://stackoverflow.com/questions/30369258/file-associations-in-vscode/30421000#30421000

**Comment by bpasero** [comment] 2017-03-14 05:47
@rbenson on that link I am not seeing someone assigning multiple languages to one extension?

**Comment by brucebrophy** [comment] 2017-03-14 14:40
<img width="1034" alt="screenshot 2017-03-14 10 38 32" src="https://cloud.githubusercontent.com/assets/9742009/23905758/73e7fcbe-08a2-11e7-8a44-9d2bb023f5d1.png">
[Here](https://www.reddit.com/r/webdev/comments/5ye5i5/creating_visual_studio_code_snippets/) is where I found the syntax for two file extensions being associated to a file type.

**Comment by rbenson** [comment] 2017-03-30 04:10
@brucebrophy this doesn't work. 

    "*.html": "html,javascript"

marks this as an js file, and doesn't give me my HTML snippets. Doing `javascript, html`, marks it as html, but no js snippets

**Comment by rmunn** [comment] 2017-08-04 03:58
Related to, but not a duplicate of, #1751.

**Comment by bmewburn** [comment] 2017-08-04 09:13
Assigning multiple languages would be a nice feature, particularly for PHP. A PHP and html language server can work very nicely together. PHP can ignore all outside of `<?php ?>` and html ignore inside the tag. See https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client in html mode to see this in action.

**Comment by alexandrudima** [comment] 2017-11-23 14:48
Our tokenization recognizes each language correctly; check the language field.

|PHP|HTML|
|--|--|
| <img width="518" alt="image" src="https://user-images.githubusercontent.com/5047891/33178225-b462eb9c-d065-11e7-83c8-2574f6336a15.png"> | <img width="496" alt="image" src="https://user-images.githubusercontent.com/5047891/33178209-a6701a3c-d065-11e7-8ae2-32f2f70c75e8.png"> |

---

If you are looking for PHP files to offer intellisense in the HTML portions, you can use the search functionality and upvote one of the existing issues. e.g. #2915 -- that would be something the PHP extension would implement, i.e. delegate to the HTML language services for the HTML portion of PHP.

**Closed by alexandrudima** 2017-11-23 14:48 UTC
Labels: editor, feature-request
