### ISSUE TITLE
 copying (Ctrl+C) and pasting (Ctrl+V) code, VSCode will automatically delete what I paste or the text after the code.

### ISSUE THREAD

**Issue by mangochu** [microsoft/vscode#144718] opened 2022-03-09 02:56 UTC
When copying (Ctrl+C) and pasting (Ctrl+V) code, VSCode will automatically delete what I paste or the text after the code.
For example, when I do i18n translation and paste the json link common.check in t(""), it will become t() instead of t("common.check"). And I need to Undo it (Ctrl+Z), the text will apear.
I have been using VSCode for a long time, but this problem only happened recently, I don't know if it is caused by the update, so I am very confused. I have deactivated all extension modules, but the problem still exists.

**Comment by gehrmanng** [comment] 2022-03-09 06:49
The same problem also occurs on Mac using CMD + C / CMD + V since the last major update. If you press CMD / CTRL + Z (undo) the pasted text will appear.

**Comment by jrieken** [comment] 2022-03-09 07:21
Do you se the `editor.formatOnPaste` setting? Iff so can you try without it enabled?

**Comment by mangochu** [comment] 2022-03-09 07:26
(More info)
The issue is usually found in the following situations
1. ` `<div>Something</div>` ` when I want to paste `${t("")}` to replace **Something**, it will become ` `<div>${t("")` ` and error.
2. `t("").replace("[name]", name)`when I want to insert/paste `common.check` in `t("")`, it will become `t().replace("[name]", name)`

**Comment by mangochu** [comment] 2022-03-09 07:33
> 

Yes, the problem solved when i disabled `editor.formatOnPaste`.
Thank you!
But it was fine a week ago.

**Comment by jrieken** [comment] 2022-03-09 07:34
What languages is this happening with? And what formatter is used for that language?

**Comment by mangochu** [comment] 2022-03-09 07:36
Do you mean this?
![image](https://user-images.githubusercontent.com/84841830/157394240-2456d1ff-baec-4015-a48d-03ddc0eb5987.png)

**Comment by jrieken** [comment] 2022-03-09 07:39
Yes. Next provide a minimal code snippet into which you paste. Also include what you paste so that we can reproduce the issue on our machines

**Comment by mangochu** [comment] 2022-03-09 08:10
A minimal code like below with comment, and thank you again:

```javascript
var leftStr = "<div>Result:</div>"
var zDiv = "<div>"

if (i == 0) {
  let ABC = ''
  if (value == 0) {
    leftStr += zDiv + `Mary &nbsp;&nbsp;</div>`;
    ABC = 'Mary'
  } else if (value >= 1 && value <= 9) {
    leftStr += zDiv + `Alex` + value + ` &nbsp;&nbsp;</div>`;
    ABC = t("common.check").replace("[name]", value)
  } else if (value == 10) {
    leftStr += zDiv + `Tony &nbsp;&nbsp;</div>`;
    ABC = 'Tony'
  } else if (value == 11) {
    leftStr += zDiv + `Selina &nbsp;&nbsp;</div>`;
    ABC = 'Selina'
  }
  $('#ABC').text(ABC)
}

// There are 2 conditions that the issue will occur:
// Paste ${t("")} to replace "Mary", "Tony", "Selina" will go wrong, but replace "Alex" is OK
// Paste common.check into t("")
```

**Comment by gehrmanng** [comment] 2022-03-09 10:39
For me it usually happens for JavaScript / TypeScript Template-Strings which contain multiple expressions. Consider the following TS function:

```typescript
  test(value: string) {
    const mystring = `${value} this is a template string with value ${value} and text after value`;
  }
```

If you replace the second ${value} with any text everything behind the first ${value} is removed. Disabling the formatOnPaste setting fixes this.

**Comment by mjbvz** [comment] 2022-04-13 23:32
Likely a duplicate of https://github.com/microsoft/TypeScript/issues/48006 based on the description

**Closed by mjbvz** 2022-04-13 23:32 UTC
Labels: needs more info, *english-please, translation-required-chinese-traditional
