### ISSUE TITLE
Inconsistent Autoformatting Behavior

### ISSUE THREAD

**Issue by nwayve** [Microsoft/vscode#13210] opened 2016-10-04 14:23 UTC
- VSCode Version: 1.5.3
- OS Version: 10.0.14393

Steps to Reproduce:

1. **[Edit]** File > Preferences > User Settings
2. **[Set]** "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true
3. **[Ensure]** There is no workspace settings file interfering 
4. **[Create]** test.js
5. **[Add]** `var x = ['foo', 'bar'];`
6. **[Observe]** Upon hitting the semi-colon key, the line will be formatted as such:
`var x = [ 'foo', 'bar' ];` as expected
7. **[Auto-Format]** Trigger an auto-format ensuring nothing is highlighted (shift + alt + f)
8. **[Observe]** The line will be formatted back to: `var x = ['foo', 'bar'];`
9. **[Select-All]** 
10. **[Auto-Format]**
11. **[Observe]** The line will be reformatted to the correct: `var x = [ 'foo', 'bar' ];` again

**Comment by waderyan** [comment] 2016-10-10 21:32
@nwayve thank you for opening this issue. Can you try with [v1.6](http://code.visualstudio.com/Download)? I cannot reproduce the bug with the latest download.

**Comment by nwayve** [comment] 2016-10-10 22:23
Just updated to `v1.6.0`.  I still get the same exact behavior following the steps provided except that when I select all to auto-format, it doesn't reformat it.

To verify (and provide myself with a sanity check), I perform the following:
User settings.json file:
```{
    "editor.fontFamily": "Consolas",
    "editor.formatOnType": true,
    "files.autoSave": "afterDelay",
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true
}```
keybindings.json:
```[]``` (Emptied this out to ensure I didn't inadvertently reassign any default keybindings)
`shift + alt + f` Default Keyboard Shortcut:
```{ "key": "shift+alt+f",           "command": "editor.action.format",
                                     "when": "editorHasFormattingProvider && editorTextFocus && !editorReadonly" }```
No `.vscode` folder or workspace file(s).
Working directory: `C:\Projects\temp`
Create `test.js`
Add line `var x = ['foo', 'bar']`
When I press `;` at the end of that line, it auto-formats to:
`var x = [ 'foo', 'bar' ];`
After pressing the semi-colon, I press to auto-format `shift + alt + f` and get:
`var x = ['foo', 'bar'];`
Then I select all `ctrl + a`
And `shift + alt + f` again to auto-format:
`var x = [ 'foo', 'bar' ];`
Or if I delete the semi-colon and re-enter it, it reformats it with the spacing as before:
`var x = ['foo', 'bar']`
`var x = [ 'foo', 'bar' ];`

SS of Sys Info (windows version) and VS Code Version:
![sysinfo_vscodeinfo](https://cloud.githubusercontent.com/assets/1729221/19252991/a9c64386-8f0d-11e6-9e9e-f7e38372fdea.png)

**Comment by waderyan** [comment] 2016-10-13 16:00
@nwayve thank you for your detailed instructions. This seems to be working as intended. 

From what you've written I understand that you expect 

```
var x = ['foo', 'bar']
```

To turn into
```
var x = [ 'foo' ,  'bar' ]
```

When you add a semicolon per `"editor.formatOnType": true` setting. 

Your original issue was that when you selected formatted

```
var x = [ 'foo' ,  'bar' ];
```

It would undo the formatting. However you are not seeing that in V1.6 anymore. 

Is my understanding correct? 

At least I see what I am thinking is correct behavior. See here. 

![autoformatissue](https://cloud.githubusercontent.com/assets/2449568/19356677/7463bb16-9123-11e6-9b5b-76f9850178c7.gif)

**Comment by nwayve** [comment] 2016-10-13 20:55
The behavior you're displaying is correct.  With the line of code **selected**, when you **Format Code**, the formatting will remain as expected, with the spacing added within the brackets.  Now deselect the code and leave the cursor at the end of the line (or anywhere in the doc really, just don't have anything selected).  When you **Format Code** again, it will undo the formatting.

I'm still seeing this behavior in v1.6.1.
![alt text](http://i.imgur.com/tKnRoJ3.gif)

**Comment by waderyan** [comment] 2016-10-14 14:49
@nwayve thank you for your clarification. This is a language service issue. Moving to the language service repo.

**Comment by waderyan** [comment] 2016-10-14 14:49
This issue was moved to Microsoft/TypeScript#11627

**Closed by waderyan** 2016-10-14 14:49 UTC
Labels: js, needs more info
