### ISSUE TITLE
Expose the new tree widget provider to extensions

### ISSUE THREAD

**Issue by kevindiclemente** [Microsoft/vscode#68806] opened 2019-02-15 21:28 UTC
VScode just released a new tree widget with awesome features, like inline search and more. It would be great to have this feature set exposed to extension developers. see below for vscode release notes:

New tree widget
We have pushed our widget game to the next level: a new tree widget was created to address performance issues and enable us to provide more features in several workbench areas. The new tree widget was created through composition over our high-performance list widget. We intend to write a separate blog post about this engineering work and the performance improvements. For now, we'll focus on the features instead.

Note: The new tree was adopted in the File Explorer, all Debug trees, Search, and Peek References. The features described below apply to most of those UI areas, unless explicitly disabled by us.

Improved keyboard navigation

There are now three different types of keyboard navigation in trees: simple, highlight, and filter. In both highlight and filter, typing in a tree will display a widget (control) at the top of the tree, which indicates that you are now navigating the tree:

Keyboard navigation type filter

This widget can also be used to switch between the highlight and filter modes. You can configure a keybinding to execute the list.toggleFilterOnType command if you'd like a keyboard shortcut for switching between modes. The Workbench > List: Keyboard Navigation (workbench.list.keyboardNavigation) setting sets the default mode, including the simple mode in which typing the first few characters of a tree element simply focuses that element.

Users who have single letter keybindings for list/tree actions can still use this feature by making use of the listAutomaticKeyboardNavigation context key. For example, the VIM extension sets this context key to false to disable automatic keyboard navigation and adds a keybinding / to the list.toggleKeyboardNavigation command, so users can just type / and navigate the tree. Learn more about this in the VSCodeVIM pull request.

Theme authors can customize the widget's colors with the following new theme keys:

listFilterWidget.background
listFilterWidget.outline
listFilterWidget.noMatchesOutline
Note: These keyboard navigation modes currently only work on resolved tree nodes. For example, in the File Explorer, if a folder was never expanded, the tree won't look for its children. We are considering several options to make this experience better.

Hierarchical Select All

Pressing Ctrl+A (Cmd+A on macOS) in a tree will now expand the tree's selection in a hierarchical fashion.

Hierarchical select all

Customizable indentation

You can now customize the node indentation of all trees across the workbench using the Workbench > Tree: Indent (workbench.tree.indent) setting.

Expand/Collapse All

Holding the Alt key while expanding/collapsing tree nodes will now work recursively. Note that recursive expansion only works for nodes previously revealed in the tree. For example, the File Explorer will not automatically expand folders which were never expanded before by the user.

Horizontal scrolling

The Workbench > Tree: Horizontal Scrolling (workbench.tree.horizontalScrolling) setting now enables horizontal scrolling on more trees and lists, namely Explorer, Search, SCM, Debug, etc.

**Comment by allenoleksak** [comment] 2019-02-15 23:16
As an extension developer.  I agree.  The current treeview also doesn't have drag/drop, or inline editing capabilities that the main treeview has.  We would love those things as well.

**Comment by sandy081** [comment] 2019-02-18 10:55
Duplicate of #63566

**Closed by sandy081** 2019-02-18 10:55 UTC
Labels: explorer-custom
