### ISSUE TITLE
Relabel "Call Stack" to "Threads"

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#19605] opened 2017-01-31 03:58 UTC
- VSCode Version: 1.8.1
- OS Version: All

The "Call Stack" viewlet is actually a list of threads until a breakpoint is hit, at which point one of the threads expands to show the call stack. The viewlet should be renamed to "Threads".

**Comment by isidorn** [comment] 2017-01-31 11:15
No, since some debuggers do not even support threads (node debugger). 
Also when a user launches multiple debug sessions we show multiple processes there, should it then be relalbeld to "Processes".
Call stack is a more general term which works decent for all cases imho
Closing as designed

**Closed by isidorn** 2017-01-31 11:15 UTC
