### ISSUE TITLE
ctrl + shift + g does not seem to move the focus to the scm view

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#103002] opened 2020-07-21 09:25 UTC
Issue Type: <b>Bug</b>

1. Open a folder in VSCode that belongs to a git repository.
1. Change any files belonging to that folder.
1. Now press ctrl + shift + g.

The focus should be moved to the scm view as in version 1.47 but at least in my environment the focus is not moved.

VS Code version: Code - Insiders 1.48.0-insider (6c21258b65e4c9448323c930fabb1ac6b734c597, 2020-07-20T05:29:10.123Z)
OS version: Linux x64 5.7.9-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2855)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|9.60GB (0.13GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by joaomoreno** [comment] 2020-07-21 10:19
Do you have GitLens installed? I can also reproduce and it's weird. I noticed the culprit on my machine is GitLens, which seems to take over the SCM shortcut:

![image](https://user-images.githubusercontent.com/22350/88042538-5b6c5200-cb4c-11ea-9fd6-d57adea90108.png)
 
@eamodio Not really sure this is such a good idea. I would leave <kbd>Ctrl Shift G</kbd> untouched.

**Comment by jvesouza** [comment] 2020-07-21 10:57
No, GitLens is not installed in my environment.

The same problem happens if I try to access the scm view from the view menu.
Also happens if I run code-insiders with the --disable-extensions options.

**Comment by eamodio** [comment] 2020-07-21 14:36
Yeah, keybindings are hard. The GitLens "chorded" keybinding set has overridden that for a long time (years). I do re-add the same command as `Ctrl+Shift+G, G`, but its certainly not ideal. I kind of wish that if you don't complete a chord fast enough and there is a binding to the first part, it would just run the command bound to it. So I could still have chords that start with `Ctrl+Shift+G`, but if you don't press another key after it it would execute the default binding.

**Comment by eamodio** [comment] 2020-07-21 14:38
Users can also change/turn off GitLens keybindings via _GitLens: Open Settings_ from the command palette

![image](https://user-images.githubusercontent.com/641685/88068457-396bd300-cb3e-11ea-9c62-1aeb0a2ab085.png)

**Comment by eamodio** [comment] 2020-10-07 19:41
Closing as this is caused by GitLens and addressable by changing the keybindings as shown above.

**Closed by eamodio** 2020-10-07 19:41 UTC
