### ISSUE TITLE
Overview in Markdown files

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#48649] opened 2018-04-25 08:21 UTC
Issue Type: <b>Feature Request</b>

While reading the latest release notes within VS Code, I realized that there's one feature I lacked, the ability to easily navigate the Markdown file.

If you've ever read a long Google Docs document you might have a clue as to what I'm talking about. On the righthand side of the screen, theres a navigation pane, giving a clear overview of the document, showing all headings and subheadings withing the document. The same should be present within Markdown files within VS Code.

I put together a quick screenshot for reference.

![vs_code_example](https://user-images.githubusercontent.com/6452991/39234040-600eecbe-4872-11e8-95b7-91911138b2de.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment] 2018-04-25 17:09
Duplicate of #5605 . [Go to symbol](https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-symbol) already presents an outline and can be used to quickly jump between sections

**Closed by mjbvz** 2018-04-25 17:09 UTC
Labels: markdown
