### ISSUE TITLE
Search on searched results.

### ISSUE THREAD

**Issue by pipepupo** [Microsoft/vscode#32350] opened 2017-08-11 20:53 UTC
feature-request

- VSCode Version: all
- OS Version: all
- Languages: all

1. I want to search a phrase only in the files that contains the results of the last search.
2. Then the searched result is more specific.

Steps to Reproduce:

Example:
file1.css:
//THE HOUSES ARE RED 

file2.php:
//THE HOUSE IS BLACK AND WHITE 

file3.py:
//THE CAR IS BLACK

file4.js:
//THE HOUSE IS WHITE AND THE CAR IS YELLOW

I'm looking for a file that contains the phrases: "THE HOUSE", "WHITE", "BLACK".

Search 1 "THE HOUSE": results: file1.css, file2.php, file4.js
Search 2 in the last files: "WHITE" results: file2.php, file4.js
Search 3 in the last files: "BLACK" result: file2.php

Thank you.

**Comment by roblourens** [comment] 2017-08-11 21:04
Duplicate of #19940

**Closed by roblourens** 2017-08-11 21:04 UTC
Labels: php
