### ISSUE TITLE
git new branch turning backslashes into dashes without informing user

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#144219] opened 2022-03-01 23:55 UTC
Version: 1.65.0-insider (user setup)
Commit: b7730c807c1e0fdacdcc91a854bb963715b2a89b
Date: 2022-02-28T14:37:48.095Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. click on the branch picker
2. type in a new branch like `foo\bar`:
![image](https://user-images.githubusercontent.com/2644648/156268545-2c9bbacf-5e48-4652-bb14-9062303f8b72.png)
3. hit ENTER

Expected:
The quick should inform the user that backslashes will be turned into dashes.

Actual:
No warning happens and the behavior happens automatically which may confuse the user:
![image](https://user-images.githubusercontent.com/2644648/156268608-8278151f-d66f-4068-8e96-e2898c39ea64.png)

**Comment by rmunn** [comment] 2022-03-02 03:27
Backslashes are [illegal in Git branch names](https://wincent.com/wiki/Legal_Git_branch_names), so VS Code is converting the branch name to something legal. The [common practice](https://stackoverflow.com/questions/273695/what-are-some-examples-of-commonly-used-practices-for-naming-git-branches) is to use forward slashes to separate conceptual "parts" of the branch name. E.g. it's common practice to call a feature branch `feature/awesome-new-thing`.

So VS Code is working as designed here, replacing the `\` with a legal character. IMHO, though, it shouldn't replace it with a hyphen, but with a forward slash `/` as that's closer to what the user probably intended by using a backslash in a branch name.

**Comment by TylerLeonhardt** [comment] 2022-03-02 15:35
Yep I totally was typing backslash when I meant to type forward slash. Thanks for the explanation! Closing this

**Comment by lszomoru** [comment] 2022-03-09 14:56
My understanding is that the current behaviour was modelled after GitHub. What we could improve is to display an explicit warning when the branch is being created that the branch will be created using a name other than the one specified, similar to GitHub.
 
![image](https://user-images.githubusercontent.com/3372902/157466874-17976204-b521-455f-bbca-6f37aae0dee4.png)

**Comment by TylerLeonhardt** [comment] 2022-03-09 15:40
I really like that @lszomoru. Reopened to track that

**Comment by lszomoru** [comment] 2022-03-10 10:52
@TylerLeonhardt, I have looked at quickInput and quickPick samples and it is not clear to me whether today there is API to provide a warning validation message when validation the input. Is the API there and I just missed it? Thanks!

**Comment by TylerLeonhardt** [comment] 2022-03-10 15:37
@lszomoru https://code.visualstudio.com/api/references/vscode-api#InputBoxOptions

You can define a validateInput function in your options.

Or if you're using the createInputBox API you can set the validationMessage property:

https://code.visualstudio.com/api/references/vscode-api#InputBox

**Comment by lszomoru** [comment] 2022-03-10 16:03
@TylerLeonhardt, right, however my understanding is that this will be rendered as a `red` rectangle and there is no control over the background color.

**Comment by lszomoru** [comment] 2022-12-05 13:10
Fixed with https://github.com/microsoft/vscode/pull/148964

**Closed by lszomoru** 2022-12-05 13:10 UTC
