### ISSUE TITLE
[Tasks 2.0.0] Wrapping output in terminal when Panel is hidden

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22328] opened 2017-03-09 21:03 UTC
Hi,

- VSCode Version: 1.10.2
- OS Version: macOS Sierra

when I run my "test" task in terminal and Panel is hidden, then the output in the terminal is wrapped, it looks like this (new line after 80 chars):
```
Chrome 56.0.2924 (Mac OS X 10.12.3): Executed 1 of 6546 (skipped 6545) SUCCESS (
2.99 secs / 0.015 secs)
```

But when I run the task with opened Panel, then the output is as it should be - non-wrapped. It looks like this:
```
Chrome 56.0.2924 (Mac OS X 10.12.3): Executed 1 of 6546 (skipped 6545) SUCCESS (3.122 secs / 0.018 secs)
```

It would be just a styling issue, but the bigger problem is, that if one has a custom `problemMatcher` which normally matches one line and it is wrapped by hidden Panel, then the matcher never finishes and no other task can be run (and "slashes" indicator \/\/is the bottom left of the Code is spinning and spinning and ...). Once it also crashed whole Code.

My `problemMatcher` to matching problems generated by Chrome when running JS tests by Karma runner:
```
"problemMatcher": {
    "fileLocation": "absolute",
    "pattern": [
        {
            "regexp": "(Expected.+\\.)$",
            "message": 1
        },
        {
            "regexp": "\\s+at\\s+.+\\s+\\((.+\\.js):(\\d+):(\\d+)\\)$",
            "file": 1,
            "line": 2,
            "column": 3
        }
    ]
}
```

Thanks.

**Comment by dbaeumer** [comment] 2017-03-10 10:03
@Tyriar can you please have a look. Is this something I need to control ?

**Comment by Tyriar** [comment] 2017-03-10 10:27
This is on my side, the issue is that initial terminal dimensions are only fetched on a per-terminal basis and if the terminal is hidden it won't work so the default is used (80).

**Comment by Tyriar** [comment] 2017-03-10 11:18
I pushed a fix for this that should fix the size when the panel is minimized or the terminal instance is in the background (provided the panel has been created). I tested via the terminal API:

1. Open terminal panel
2. Run following API code:

    ```js
    const term = vscode.window.createTerminal(`term`);
    term.sendText("ls");
    ```

3. Switch to terminal and verify that `ls` output is formatted to full panel width

@dbaeumer could you verify this with a task?

**Comment by roblourens** [comment] 2017-03-30 22:45
This looks the same to me on stable vs insiders. `ls` wraps to two columns when the terminal is hidden. If i run the same command with the terminal visible, it wraps to five columns.

**Closed** 2017-04-18 21:20 UTC
Labels: bug, integrated-terminal, tasks
