### ISSUE TITLE
Rename providers of several extensions conflict and there is no way to know WHAT it being renamed

### ISSUE THREAD

**Issue by marinaglancy** [microsoft/vscode#183075] opened 2023-05-21 20:26 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.78.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

Currently there is a conflict between PHP extension and the extension that I'm working on. I have reported it in PHP extension github here: https://github.com/DEVSENSE/phptools-docs/issues/334 . But even if/when they fix it, the problem can repeat with different unpredictable extensions that user have installed and enabled.

Basically here is the situation:
- two independent extensions register **RenameProvider** for the same document selector. 
- my extension defines both prepareRename() and provideRenameEdits() functions, however the "prepareRename()" is not executed because another extension hijacks it.
- at the same time my callback provideRenameEdits() is being executed and it assumes that the range is what was specified in the prepareRename() but the original range is completely different
- as a result completely random range is being replaced

The problem is that from the point of view of my extension inside **provideRenameEdits()** I receive the newName parameter but I do not receive any information about the oldName or the range that user thinks they are replacing.

**Comment by marinaglancy** [comment] 2023-05-22 13:02
actually my assumption was wrong and the PHP extension does not even implement prepareRename() as they commented in their github issue. In any case there is some weird behaviour when two rename providers conflict.
For the reference, this is code of my demo extension:  https://github.com/marinaglancy/vscode-renamedemo/blob/master/src/extension.ts

and this is a screencast of how it behaves with PHP exteension disabled and enabled:
https://github.com/microsoft/vscode/assets/836986/a8ee6ced-80ff-403e-8cf8-e86fbb6ed855

**Comment by marinaglancy** [comment] 2023-05-24 06:57
In fact, I can demonstrate the problem in a single extension that implements two rename providers:
https://github.com/marinaglancy/vscode-renamedemo/blob/singledemo/src/extension.ts
one provider targets array indexes like ['something'] , another provider targets function names. If the other provider did not implement the prepareRename() it breaks the first provider in the same way I showed in the screencast above.

Vscode API says that the function prepareRename() is optional but it is actually very important. I understand that at this point vscode can not tell extensions that now they MUST implement it. 

What can be done to reduce confusion:
- do not to execute provideRenameEdits() if the prepareRename() from this provider was not called
- inside provideRenameEdits() allow extensions to know what range is being renamed

**Comment by jrieken** [comment] 2023-11-16 15:49
related to (maybe duplicate) https://github.com/microsoft/vscode/issues/198423

**Comment by jrieken** [comment] 2024-12-17 15:54
/duplicate of https://github.com/microsoft/vscode/issues/115354

**Closed by jrieken** 2024-12-17 15:54 UTC
Labels: under-discussion, rename
