### ISSUE TITLE
automatic import doesn't work with angular sub module

### ISSUE THREAD

**Issue by rcadel** [Microsoft/vscode#39255] opened 2017-11-28 13:16 UTC
- VSCode Version: 1.18.1
- OS Version: ubuntu 16.04 64bit

Steps to Reproduce:

1.create a new project using angular cli ng new project
2.Inside app.component.ts type @Input and accept autocomplete
3.Automatic import add "import { Input } from '[@]angular/core/src/metadata/directives';" which is not working 

**expected**:
Automatic import should stop at [@]angular/core 
import should be "import { Input } from '[@]angular/core';"

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-11-28 17:47
Duplicate of https://github.com/Microsoft/TypeScript/issues/17705

Should be fixed in TypeScript@next. Try installing this into vscode by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed** 2017-11-28 17:47 UTC
Labels: javascript, upstream
