### ISSUE TITLE
React tsx syntax completely broke in some cases

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/vscode#131197] opened 2021-08-19 17:48 UTC
Issue Type: <b>Bug</b>

I'm not actually sure why it breaks in some cases, but not in others.  I have an abstract base class with an abstract render() method, and a class that inherits it, which implements the base class.  Maybe that's the reason?

Either way, the first use of the tsx syntax throws all kinds of errors.  It doesn't seem to recognize any attribute I set within the whole file, nor does it recognize closing tags.

VS Code version: Code - Insiders 1.60.0-insider (c08913337cb8b95493be8e99d62e0b3241563f6b, 2021-08-19T05:15:46.693Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.16GB free)|
|Process Argv|--crash-reporter-id 007f9f10-c4ef-458b-a674-6faaf4393697|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|13.1.0
jest-snippets|and|1.8.0
split-line|che|1.0.2
bracket-select|chu|2.0.2
file-tree-to-text-generator|d-k|1.4.0
vscode-eslint|dba|2.1.23
dotfiles-syntax-highlighting|dot|0.1.0
tsimportsorter|doz|7.4.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
shell-format|fox|7.1.0
vscode-sort|hen|0.2.5
join-lines-context-aware|ian|1.0.1
vscode-ansi|ili|1.1.2
find-unused-exports|iul|1.8.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|1.6.6
guid|kos|0.0.1
bash-ide-vscode|mad|1.11.0
vscode-less|mrm|0.6.3
vsliveshare|ms-|1.0.4673
favorites|ole|1.5.2
prettyxml|Pra|0.11.0
vscode-yaml|red|0.22.0
react-development-extensions-pack|ric|1.5.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
glassit|s-n|0.2.3
vscode-scss-formatter|sib|2.2.3
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
jest-snapshot-language-support|tle|1.1.1
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30353183
javagetstartedt:30350119

```

</details>

**Comment by IllusionMH** [comment] 2021-08-19 17:51
/needsMoreInfo

Please provide code that leads to errors.

Also make sure that you are using `.tsx` files (`.ts` don't support JSX) and don't use `<T>value` assertions.

**Comment by dfoverdx** [comment] 2021-08-19 17:58
@IllusionMH Yes, I'm using a tsx file.  This file worked fine until I upgraded to last night's build.  Also, tsc runs fine.

At the moment, as I'm at work, I don't have time to simplify the code that's failing, and I can't use the original code as it's my company's IP.

**Comment by AlCalzone** [comment] 2021-08-24 10:55
I believe I'm experiencing the same thing. Intellisense and the tokenization randomly break in some `.tsx` files until I reopen the file:
![grafik](https://user-images.githubusercontent.com/17641229/130601766-3e9176fc-fbd4-4834-bfd5-e2c83a1add38.png)

![grafik](https://user-images.githubusercontent.com/17641229/130601836-546c0059-df13-441d-9983-c1a64c8ac089.png)

Not sure how I can be of help since it only happens after working on them a while.

**Comment by mjbvz** [comment] 2021-08-24 18:28
@dfoverdx  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Please also put together a minimal example that demonstrates the issue

**Comment by mjbvz** [comment] 2021-09-01 00:03
Closing as we need more information from the original poster to investigate this

**Closed by mjbvz** 2021-09-01 00:03 UTC
Labels: needs more info
