### ISSUE TITLE
Indent Guides Highlight Incorrect Level for Certain Indent Styles and Simple Code Blocks

### ISSUE THREAD

**Issue by ericdrobinson** [Microsoft/vscode#53737] opened 2018-07-06 17:29 UTC
# Visual Examples

### Allman Style Indentation

![allman](https://user-images.githubusercontent.com/9142587/42392283-4e69c7cc-8120-11e8-8751-2d6fb2a8df29.png)

### K&R Style Indentation

![k r](https://user-images.githubusercontent.com/9142587/42392284-4e790eda-8120-11e8-82da-8fc8a17ea9e3.png)

### Simple Code Block

![simpleblock](https://user-images.githubusercontent.com/9142587/42392285-4e8743ec-8120-11e8-8cb8-c1b2b8a90ef9.png)

### Whitesmiths Style Indentation

![whitesmiths](https://user-images.githubusercontent.com/9142587/42392286-4e94b86a-8120-11e8-9036-82f4d1ad3e2c.png)

# Steps to Reproduce:

1. Create a new JavaScript or TypeScript file.
1. Set the Language/Syntax Highlighting to "TypeScript".
1. Add the following to the file:
    ```ts
    function test()
    {
        if (window !== undefined)
        {
            console.log("Allman style");
        }

        if (window !== undefined) {
            console.log("K&R style");
        }

        {
            console.log("Simple block");
        }

        if (window !== undefined)
            {
            console.log("Whitesmiths style");
            }
    }
    ```
1. Put the cursor at the bracket on lines 4, 6, 8, and 10. Verify that the highlighted Indent Guide is **NOT** associated with the associated `if` statement, but the `function` statement on line 1.
1. Move the cursor to the bracket on line 12 or 14. Verify that the highlighted Indent Guide is **Not** associated with the brackets that define the block, but the encapsulating `function` statement on line 1.
1. Move the cursor to the bracket on line 13.  Verify that the highlighted Indent Guide is associated with the `if` statement on line 12.

# Discussion
As a user who prefers the [Allman indentation style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) I expect that placing the cursor on a bracket (both opening and closing) associated with a specific block will result in highlighting the block associated with that bracket rather than the encapsulating block. As the reproduction steps show, this also fails with the [K&R style](https://en.wikipedia.org/wiki/Indentation_style#K&R) and with simple code blocks.

This _does_ work as expected with the [Whitesmiths style](https://en.wikipedia.org/wiki/Indentation_style#Whitesmiths_style), the [GNU](https://en.wikipedia.org/wiki/Indentation_style#GNU_style), and likely with any other style that indents the brackets themselves beneath the encapsulating statement.

# Environment
**Does this issue occur when all extensions are disabled?:** Yes

- **VSCode Version:** 1.2.5.0
- **OS Version:** macOS 10.13.5

**Comment by alexandrudima** [comment] 2018-07-26 16:21
Duplicate of #49342

**Closed by alexandrudima** 2018-07-26 16:21 UTC
Labels: editor, editor-autoindent

**Comment by hassanbinsafdar** [comment] 2018-08-06 09:30
@alexandrudima you are saying everywhere this is duplicate i visited all references and in all references you are saying the same thing but not telling the solution 👎
