### ISSUE TITLE
activity bar badges collapsing when set to top instead of default after restart

### ISSUE THREAD

**Issue by TheBestOf1204** [microsoft/vscode#215592] opened 2024-06-14 21:27 UTC
Does this issue occur when all extensions are disabled?: Yes/No
No, because w/out any extentions there are not so many badges in the bar that it needs to collapse, so really yes and no...

- VS Code Version: 1.90.1
- OS Version: Windows 10 home

Steps to Reproduce:

1. Set 'activity bar position' to 'top'
2. close and re-open
3. after restart only a view badges show, besides the 3 dots to show all the other badges in a list and a big empty space, even though there is enough space to show all of them
4. only way I found to then show them all is either making the side bar ridiculously long or setting the activity bar postion to 'default' and back to 'top' again

same thing happens when set to 'bottom' instead of 'top'

![image](https://github.com/microsoft/vscode/assets/167515563/2790b34c-fac1-4331-a98e-76a737494139)
![image](https://github.com/microsoft/vscode/assets/167515563/487c0bed-8db4-49f0-8dcf-43d4ec5fc0c7)

**Comment by benibenj** [comment] 2024-06-17 16:35
Very surprised to see this. I tried to reproduce and it doesn't happen for me. I don't think this is being cause by a setting but to be sure, could you remove all your settings except activity bar top (don't forget to copy the to not lose them!) and check if it still happens then? Also, does this also happen when you run the `Reload Window` command?

**Comment by TheBestOf1204** [comment] 2024-06-20 07:30
sorry i'm really new to vscode, how do i remove all the settings? is there like a file for that? if so where is it?

**Comment by brendon1555** [comment] 2024-06-20 11:45
> Very surprised to see this. I tried to reproduce and it doesn't happen for me. I don't think this is being cause by a setting but to be sure, could you remove all your settings except activity bar top (don't forget to copy the to not lose them!) and check if it still happens then? Also, does this also happen when you run the `Reload Window` command?

Not OP, but I can confirm that this still happens even for me with all settings as default and no extensions installed. Initially moving it is fine, but after either `Reload Window` OR closing and reopening VSCode it maxes out at 50% of the width and shows the three-dot more button.

**Comment by brendon1555** [comment] 2024-06-20 13:59
@TheBestOf1204 Did you happen to also use https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension at any point? This seems like it might be the cause even after removing it. Just double-checked with a clean install. All was fine until I installed that extension. Uninstalling the extension doesn't fix the positioning though.

**Comment by benibenj** [comment] 2024-06-20 14:41
Thanks @brendon1555 for figuring this out and letting us know. Closing this issue as it's cause by an extension.

**Closed by benibenj** 2024-06-20 14:41 UTC
