### ISSUE TITLE
Problems with synchronise button

### ISSUE THREAD

**Issue by paoloalba** [microsoft/vscode#74443] opened 2019-05-28 08:18 UTC
Issue Type: <b>Bug</b>

press synchronise button after setting gitconfig to automatic rebase for pull. The effect is that even if I have 0 commit to pull, it pulls everything before pushing, then having to deal with a ton of merge conflicts during the pull-rebase phase.
The problem does not appear when I just push the commits without synchronising.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment] 2019-05-29 07:54
How is it possible that you can push at all, if there are any commits in the remote branch?

Can you give me exact steps to reproduce this against, say, a Github repository?

**Comment by paoloalba** [comment] 2019-05-29 21:06
let me explain the issue in more detail.
Example I have 0 commits to pull, and I want to push my local commits. I do not know what exactly does the VS-Code synchronising button, but after pressing it, the rebase process starts.
As I said, if I push the commits there is no problem at all (0 to pull, x+1 to push), and I set rebase as true for any pull.
Since synchronising is not a default git command, I guess the problem is entirely on the VS side.

**Comment by joaomoreno** [comment] 2019-06-03 13:37
> the rebase process starts

What do you mean? What happens that makes you say this?

> I do not know what exactly does the VS-Code synchronising button,

It [pulls and the pushes](https://github.com/microsoft/vscode/blob/217d9938034b52a2f390a569ce0a2f7034e3ff11/extensions/git/src/repository.ts#L1043:L1066).

---

In that situation what would happen if you run `Git: Pull`?

**Comment by paoloalba** [comment] 2019-06-05 20:04
Hi.

1. it starts the typical rebase routine, in which it moves the head to I do not know how old commit, and starts to apply the following ones in sequence. In the specific I see all the old commits which do not go ff and get stopped due to a conflict.

2. if it simply does so, then it could be implemented a logic to decide if it could be more convenient to first push and the pull.

3. in this case the pull alone does not have any effect. I would guess that it does not even start since there are zero commits to get.

**Comment by joaomoreno** [comment] 2019-06-06 06:21
> if it simply does so, then it could be implemented a logic to decide if it could be more convenient to first push and the pull.

Git doesn't work that way. If there are commits incoming from the server, the server won't let you push at all.

I still don't understand what is happening here. Your status bar says that there are 0 commits incoming. If you then run `Git: Fetch`, does that number change?

**Comment by SupinePandora43** [comment] 2019-06-13 03:03
@joaomoreno maybe seperate synchronize button to 2 buttons "pull" and "push" if "pull commits >0 && push commits>0" ?! also synchronize icon are not correctly centered!

**Comment by luphord** [comment] 2019-10-30 19:08
I have created a gist that reproduces a situation similar to what @paoloalba describes: https://gist.github.com/luphord/624c3bb8f4d446561ceb3c7cd1683662

When pull.rebase is configured and two conflicting branches have been merged, the execution of `git pull` creates the same conflicts again. This happens because git tries to rebase starting from oldest commit moving forward in time to the newest commit (which is the conflict-resolving merge). A `git pull` with rebase is simply not what you want to execute in this situation. But that is exactly what a click on the sync button does.

I don't think there is anything you can do here in vscode provided that sync is equivalent to `git pull && git push`.

**Comment by joaomoreno** [comment] 2019-10-31 10:11
@luphord Great summary. This is something that we, as a team, also have hit often since we all used to use `pull.rebase = true`.

There's actually another value of `pull.rebase` which addresses this issue: `merges`. Simply run `git config --local pull.rebase merges` instead of line 63 of your gist and everything will be happy. You can read the [`docs`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pullrebase) or this [SO post](https://stackoverflow.com/a/56534106) for more info on that.

Give this is git's behavior, closing this issue.

**Suggestion:** `git config --global pull.rebase merges`.

**Closed by joaomoreno** 2019-10-31 10:11 UTC
Labels: git, needs more info
