### ISSUE TITLE
I cannot open files or add a folder to the workspace from the “File” tab.

### ISSUE THREAD

**Issue by JuanBW** [microsoft/vscode#231023] opened 2024-10-10 15:10 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. I cannot open files or add a folder to the workspace from the “File” tab in Linux.
2.

**Comment by IllusionMH** [comment] 2024-10-10 17:22
Duplicate of #230454

**Closed** 2024-10-10 18:56 UTC
Labels: *duplicate
