### ISSUE TITLE
Retry as Sudo hangs application on save indefinitely.

### ISSUE THREAD

**Issue by KazeEnji** [microsoft/vscode#233788] opened 2024-11-13 19:00 UTC
Type: <b>Bug</b>

Attempt to open a priviledged file like /etc/proxychains4.conf running Code as a non-root user. Edit and attempt to save. The application will prompt for a sudo password and upon providing it, the application never completes the save. In the bottom bar, you can see the spinning icon stating it's saving but the save never completes.

This used to work just fine up until a few months ago. Subsequent updates have not fix the error.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.11.2-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.72GB (5.88GB free)|
|Process Argv|/etc/proxychains4.conf --disable-extensions --crash-reporter-id 2483cbef-3427-48b7-8217-04ca112c3871|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by bpasero** [comment] 2024-11-21 08:24
I suggest we continue the discussion here: https://github.com/microsoft/vscode/issues/234311

Duplicate of https://github.com/microsoft/vscode/issues/234311

**Closed by bpasero** 2024-11-21 08:24 UTC

**Comment by bpasero** [comment] 2025-01-10 14:53
A workaround for this issue is now documented in https://github.com/microsoft/vscode/issues/237427#issuecomment-2582881451. It originates from a change in hard limit on the maximum number of open file descriptors, i.e. `ulimit -Hn` returning a very large value (like `1073741816`).
