### ISSUE TITLE
Unable to search content in file

### ISSUE THREAD

**Issue by HermanZzz** [microsoft/vscode#109371] opened 2020-10-26 12:42 UTC
- VSCode Version: 1.49.2
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. I can only search for things about the opened file of the project and the search is infinitely loading.
<img width="722" alt="1" src="https://user-images.githubusercontent.com/8086434/97173352-611ca800-17cb-11eb-8f5a-a468d0392bdd.png">

2. Unable to find text in an un-opened file.
![1](https://user-images.githubusercontent.com/8086434/97955104-56bc6880-1de0-11eb-901a-4d3b95c41ea8.png)

3. Search works fine when I  launch with `code --disable-extensions`. But not for even I disable all the extensions manually.
<img width="487" alt="3" src="https://user-images.githubusercontent.com/8086434/97173555-b9ec4080-17cb-11eb-9814-88a0cd5fc63a.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment] 2020-10-26 18:39
It looks like maybe you just don't have a folder open. Make sure you open a folder like the warning message says.

**Comment by HermanZzz** [comment] 2020-10-27 03:09
Oh, it's just an example. Please refer to my gif below to see the reproduce steps. Tks.
![1](https://user-images.githubusercontent.com/8086434/97252389-cd87bd80-1844-11eb-9232-748d7957875b.gif)

**Comment by thsunkid** [comment] 2020-10-27 09:44
I countered the same issue. 
It turns out VScode's search skips those files in .gitignore. For my case, deleting those files from .gitignore helps.

**Comment by HermanZzz** [comment] 2020-10-27 09:50
> I countered the same issue.
> It turns out VScode's search skips those files in .gitignore. For my case, deleting those files from .gitignore helps.

But my demo above is just a local project. The .gitignore file does exist in this project.

**Comment by HermanZzz** [comment] 2020-11-01 15:04
@roblourens Any helps please~

**Comment by yume-chan** [comment] 2020-11-03 09:11
From https://github.com/microsoft/vscode/issues/102884#issuecomment-661457673

> Can you tell me whether there are any errors in the dev tools console (Help > Toggle Developer Tools)

**Comment by HermanZzz** [comment] 2020-11-03 09:33
> From [#102884 (comment)](https://github.com/microsoft/vscode/issues/102884#issuecomment-661457673)
> 
> > Can you tell me whether there are any errors in the dev tools console (Help > Toggle Developer Tools)

no error in the dev tools console.  need more help~

**Comment by roblourens** [comment] 2020-11-04 17:33
Sorry for the slow response. 

- Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders
- If not, please do the following
  - Run the command "Set log level" and change it to "Trace"
  - Run the search again
  - Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by roblourens** [comment] 2020-11-04 20:22
And closing as dupe of https://github.com/microsoft/vscode/issues/108102, please reply on that issue, thanks

**Closed by roblourens** 2020-11-04 20:22 UTC
Labels: needs more info
