### ISSUE TITLE
rpm versioning

### ISSUE THREAD

**Issue by wimcoekaerts** [Microsoft/vscode#7081] opened 2016-05-31 21:59 UTC
- VSCode Version: 1.1
- OS Version: Linux rpm 

Steps to Reproduce:

rpm is called vscode-x86_64.rpm

when installing the package is called
code-1.1.1-1463146452

normal convention would be to have the rpm name be the -same- as the package name that's installed and to also add a distribution version in it (el6, el7,...)
so for rhel,centos,ol,scientific Linux,... 

it should be 👍 
download code-1.1.1-146314652.el7.x86_64.rpm and install code-1.1.1-146314652 or
download vscode-1.1.1-146314652.el7.x86_64.rpm and instal vscode-1.1.1-146314652

**Comment by wimcoekaerts** [comment] 2016-05-31 22:01
one reason to have the version in the main .rpm file is so that I actually -know- what version I downloaded. All I see is vscode-x86-64.rpm that's it. I have no idea whether that's the current version or older version until I would try and install it or run a command like rpm -q --info but that' should not be required.,

**Comment by Tyriar** [comment] 2016-06-01 00:04
Duplicate of https://github.com/Microsoft/vscode/issues/6587, coming in the June release :smiley:

**Closed** 2016-06-01 00:05 UTC
