### ISSUE TITLE
Decorations with gutter icons hide breakpoint icons

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/vscode#5923] opened 2016-04-28 00:22 UTC
- VSCode Version: 1.0.0
- OS Version: any

Steps to Reproduce:
1. Create a decoration type `window.createTextEditorDecorationType({ gutterIconPath: ... });` with an icon, decorate a line.
2. Set a breakpoint for the line. While the breakpoint works, the decoration type gutter icon is completely hiding it.

Ideally, there should be a way to see both (all) icons. I'm assuming the same issue happens if two different extensions set different icons for the same line. Atom and IntelliJ platform based IDEs solve this by allowing to create a plugin specific gutter/or just extending the gutter horizontally to fit all icons.

If the above mentioned solution is not desirable for some reason, then it should probably be allowed to set a gutter icon `zIndex` for a decoration type. Or maybe the breakpoint icon should just take precedence and always be displayed above any extensions icons.

**Comment by buzzdan** [comment] 2016-06-29 09:50
Hi guys,
Any news on this issue?
it's making it much harder to debug like that (i'm used to use the mouse to set a breakpoint)

![image](https://cloud.githubusercontent.com/assets/18007791/16448008/e645373e-3df7-11e6-931a-a6b2b64d5fbf.png)

**Comment by alexandrudima** [comment] 2016-06-29 11:49
Today there is space in there for one glyph.

I guess we need to implement an overflow experience in there.

This is a feature-bug, as the code was never designed to handle more than one glyph margin for a line.

**Comment by dotnetprofessional** [comment] 2017-02-23 01:13
+1 on this - I'm experiencing the issue with Wallaby, but I can see that other plugins may be competing for the same real-estate in the future. Visual Studio supports this feature today.

**Comment by ChrisBellew** [comment] 2017-05-23 05:26
+1 Also am a Wallaby user who would like to see both breakpoints and wallaby line coverage. My thought is that seeing the breakpoint glyph is of higher importance than the coverage glyph, maybe some kind of multiple glyph (with precedence) system would work?

**Comment by thelazydogsback** [comment] 2017-06-14 00:33
Ignoring the  obvious degenerate cases, why not just make the gutter big enough to hold the maximum number of glyphs currently displayed on any line??

**Comment by breathe** [comment] 2017-07-28 21:49
New to vscode (really enjoying it so far).  Also a fan of wallabyjs and would love to see a fix for this.

**Comment by JoshuaKGoldberg** [comment] 2017-12-01 22:44
It sounds like there are two main ways this could be resolved:

*  _Easier, less flexible path:_ Allowing z-index style ordering so Wallaby icons go below VS Code's
* _Complex, better path:_ Increasing the width of that gutter area 

@alexandrudima is the "easier" path something a first/second-time contributor could tackle? (any hidden gotchas?)

**Comment by alexandrudima** [comment] 2017-12-04 14:16
I think that could work. `IModelDecorationOptions` could get a new `zIndex` property that could be used for sorting in the various places we render decorations.

**Comment by JoshuaKGoldberg** [comment] 2018-04-08 13:29
Cool, looks like f26b9ef408b843101cd865b72a96a156bc2b3e72 fixed this. @ArtemGovorov is that enough to go off of?

**Comment by ArtemGovorov** [comment] 2018-04-08 23:53
@JoshuaKGoldberg Unfortunately, gutter icons decorations in VS Code are apparently rendered by applying class names to the same `div`, so `zIndex` is irrelevant:

<img width="1044" alt="screen shot 2018-04-09 at 9 48 30 am" src="https://user-images.githubusercontent.com/979966/38473977-6e24144e-3bdb-11e8-9b81-684bd6d23a0a.png">

**Comment by CoenraadS** [comment] 2018-04-14 12:28
I just ran into this with my extension, I want to show brackets in the gutter but as long as they block breakpoints it's highly annoying and probably won't be used.

**Comment by jagreehal** [comment] 2018-07-02 09:54
+1 please fix this issue

**Comment by crysyn** [comment] 2018-07-25 00:01
I would very much like a solution to this as I have just forgotten how much I miss using Bookmarks from VS (which has been my history with VSCode.. what am I missing, go find an extension that does it).

Would there be some way an extension could detect other 'states' for a line like 'there is a breakpoint here' and if so incorporate a combo glyph for display? Just some basic onAddBookmark() { if line(number)->hasBreakPoint { useBreakpointBookmark } else { useBookmark } } .. Or something? I know this would not fix multiple extensions working in conjunction with out some auto-combine capabilities to generate the compiled glyphs.. But it might be a step in a direction.

**Comment by HerbCaudill** [comment] 2018-09-11 11:47
+1 Running into this issue with Wallaby code coverage indicators vs breakpoints.

**Comment by timarandras** [comment] 2018-09-18 07:09
+1 Had to stop Wallaby while debugging tests.

**Comment by mrgrauel** [comment] 2018-10-16 08:11
+1 it's really annoying to stop wallaby when I want to debug the application.

**Comment by thelazydogsback** [comment] 2018-10-16 14:51
@mrgrauel - you shouldn't need to stop wallaby to debug - you can still you can still set breakpoints via the F9 shortcut (or the ToggleBreakpoint command directly) and it will work - you just won't be able to see the breakpoint markers.

**Comment by nerdmax** [comment] 2019-02-14 05:56
+1

**Comment by wdaqian** [comment] 2019-03-05 11:14
+1

**Comment by DarkEnchanter1** [comment] 2019-04-07 21:35
Wait, if gutter icon rendering is handled by applying classes to a div, then couldn't an !important modifier be added to the breakpoint class style? Not the best long term solution, but wouldn't that solve the immediate issue?

**Comment by wpatter6** [comment] 2019-05-18 01:28
In some cases it's much more convenient to just click to set the breakpoint, especially on a laptop that requires you to click the line then press `fn+f9` -- I really hope that whatever solution is decided that this would be continue to be possible... Could a possible solution be that gutters are added by extensions instead of reusing the existing one?  That would be relatively similar to the "gutters as wide as they need to be" solution, though I imagine it could get rather cluttered.

Honestly for me losing the click to set breakpoint functionality is more annoying than not being able to see it, since I can see it in the breakpoints list in the debug panel... would that part be a wallaby issue, like they should set `pointer-events: none` to allow for the click to pass through?

**Comment by miguelpruivo** [comment] 2019-11-02 20:06
This is now an issue for Flutter/Dart projects as well.

**Comment by matt-goingout** [comment] 2020-01-30 08:19
+1 - open since 2016 and still no solution to the rather common problem of "being able to debug using modern methods"?  :) I cant believe we're stuck with 'use keyboard shortcuts' as a solution - any news?

**Comment by zeljkoantich** [comment] 2020-04-10 10:55
[Add gutter icons for classes and members navigation](https://github.com/microsoft/vscode/issues/73784)

**Comment by aidan-mundy** [comment] 2020-07-27 06:16
Per personal experience and #95992, the breakpoint icon is no longer hidden when other decorators exist, it merely is displayed in front of them. It seems that as long as #5455 is unresolved (or remains an unplanned feature), an easy (and albeit temporary) solution to this particular issue (and moreso to #95992) would be to make any click event in the breakpoint portion of the gutter toggle the breakpoint for that line (as is the expected behavior when there is no decorator). It seems that click events are ignored when a decorator is being rendered, and that could (potentially) prove to be relatively trivial to resolve. 

It has been 4 years and over 90,000 issues since this problem was originally raised. I hope my suggestion may aid in finally making some progress.

**Comment by xtbe** [comment] 2020-08-24 07:59
+1 for fixing this

**Comment by emahnovets** [comment] 2020-08-26 10:23
+1 for fixing this

**Comment by vuongggggg** [comment] 2020-09-14 08:22
![Screenshot 2020-09-14 at 3 20 57 PM](https://user-images.githubusercontent.com/3168632/93061539-e6298300-f69d-11ea-87e5-a17ff12c7aec.png)
![Screenshot 2020-09-14 at 3 21 24 PM](https://user-images.githubusercontent.com/3168632/93061578-f5103580-f69d-11ea-9fd6-6e4576af252f.png)
I'm not sure how the code could be fixed, but could we have this mix?

**Comment by connectdotz** [comment] 2020-11-13 21:43
hi,

Just curious what is the main blocker for resolving this issue? Does the vscode team think this should NOT be addressed? Or there is no consensus on how to fix it? Or maybe it is a resource/priority issue?  It seems there are a lot of interesting suggestions but did not see comments from the core team... can someone from the vscode team shed some light on how to best move forward on this issue? thanks.

**Comment by ffMathy** [comment] 2020-11-30 12:05
4 years. The issue has been here for 4 years. Am I the only one who thinks it's crazy that this hasn't been worked on so far? I find it quite critical.

It also works very poorly with Error Gutters: https://marketplace.visualstudio.com/items?itemName=IgorSbitnev.error-gutters

**Comment by tintinweb** [comment] 2021-02-05 10:20
Will there be a fix for this?

**Comment by JackSchaible-Pandell** [comment] 2021-03-17 21:08
+1...5 years now without a fix, c'mon guys

**Comment by sachin-agarwal-by** [comment] 2021-05-26 03:55
any update on this its 5 years now .

**Comment by scantron-jared-kremer** [comment] 2021-06-08 18:26
Yep, +1 on this one. Seems simple enough so lets get it done! Clicking the line number could also set a breakpoint or something? :)

**Comment by Tony-Sol** [comment] 2021-12-10 16:35
+1 really usefull feature

**Comment by zasdfgbnm** [comment] 2022-04-25 17:21
Is there any update on this issue?

**Comment by pattazl** [comment] 2022-05-24 03:34
+1 for fixing this , it havn't been fixed yet

**Comment by connectdotz** [comment] 2022-05-24 18:21
looks like this has been resolved in TestExplorer since v1.59, see the gutter menu below. Is there a way to expose the same feature to extensions? cc @connor4312 

<img width="647" alt="Screen Shot 2022-05-24 at 2 14 48 PM" src="https://user-images.githubusercontent.com/891093/170105033-63066070-e89d-479e-a857-6b1d93599f60.png">

**Comment by eamodio** [comment] 2022-06-01 05:02
It looks like the root cause is this function:

https://github.com/eamodio/vscode/blob/e15b7b08a906b1e974a6a8bbd801c7c6863f7a2b/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L431-L443

Where the breakpoint hover/click overlay is explicitly being skipped. While I can kind of see the reasoning -- e.g. not wanting it to look like there is interaction based on the decoration shown, as it will always be about the breakpoint -- at least until #5455 is supported.

Maybe there could be a new `gutterInteraction: false` or `gutterAllowBreakpoint: true` setting that could be added to the decoration options, to allow the breakpoint interaction to be allowed on top of a gutter decoration. Or maybe this should just always be allowed for all current gutter decorations, and when🤞 interactivity on the gutter lands it could turn off the breakpoint interaction.

/cc @hediet as you've been making some recent changes with the 3-way merge support

**Comment by alefragnani** [comment] 2022-06-01 11:43
I know some UX changes needs a fair amount of exploration and tests, but I wonder why not borrow how other products works. 

* JetBrains IDEs (IntelliJ and Rider) simply _expand_ the gutter to support more decorators. 
* Embarcadero Delphi reserves a gutter space to breakpoints, and additional decorators (like bookmarks) are added to its side.

I mean, it's been 6 years...

**Comment by connor4312** [comment] 2022-06-06 11:03
> looks like this has been resolved in TestExplorer since v1.59, see the gutter menu below. Is there a way to expose the same feature to extensions? cc @connor4312

This is something we manually handle in the testing code in VS Code core.

We've also discussed this in https://github.com/microsoft/vscode/issues/114776

**Comment by MDUK0001** [comment] 2022-06-20 16:50
For the Golang equivalent of this functionality, there is an option to only show decorations for partially covered / uncovered lines, which for me minimises the issue as you can usually always find another line on which to place your breakpoint. Would that be something that would be easy to implement?
Example: 
![image](https://user-images.githubusercontent.com/10220539/174648101-9a4a50df-3958-46b1-83bf-2bcabeacac61.png)

**Comment by sehoffmann** [comment] 2022-08-24 10:01
This feature is desperately needed.

**Comment by andrewdingcanada8** [comment] 2023-02-20 02:43
Want to just ping the devs on this again, since it's now 2023.
I personally came across this bug due to the test coverage highlights blocking my ability to add debug breakpoints.
Would love to see this fixed!

**Closed** 2023-04-14 13:15 UTC
Labels: feature-request, editor-rendering
