### ISSUE TITLE
Text rendering issues on Ubuntu 20.04: diffs shows visual glitches 

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#103184] opened 2020-07-23 17:13 UTC
Issue Type: <b>Bug</b>

When using `zoom level: 0.5`, the diff highlighting results in small visual glitches:

![Screenshot from 2020-07-23 10-09-08](https://user-images.githubusercontent.com/13824553/88316588-eecc9100-cccc-11ea-91d8-f559f1e83aa6.png)

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by alexdima** [comment] 2020-09-03 21:24
This is due to using `window.zoomLevel`. I recommend to use `editor.fontSize` for pixel perfect rendering. The `window.zoomLevel` is implemented outside of our control and even if we render rectangles at integer coordinates that perfectly touch each-other, the zooming might introduce rounding errors and create such artefacts.

Duplicate of #91686 and many others

**Closed by alexdima** 2020-09-03 21:24 UTC

**Comment by tlemo** [comment] 2020-09-03 22:07
>  The window.zoomLevel is implemented outside of our control and even if we render rectangles at integer coordinates that perfectly touch each-other, the zooming might introduce rounding errors and create such artefacts.

Would it be possible to combine adjacent regions (with the same background color) instead of one region per line (as I suspect it's currently done)? 

> I recommend to use editor.fontSize for pixel perfect rendering.

Thanks, but this is not a great alternative, since on high-DPI monitors one would need to scale all the UI elements, not just the text.

**Comment by alexdima** [comment] 2020-09-03 22:30
> Would it be possible to combine adjacent regions (with the same background color) instead of one region per line (as I suspect it's currently done)?

This is actually not easy, because we draw each line independently of others, so for example when you type on a line, we take great care to only touch the DOM elements for that line. This helps browsers (or Chromium in our case) invalidate only a small portion of the DOM and repaint only a small area. Our rendering is not what you would typically expect (i.e. we don't clear the pixel buffer every frame and then paint, etc.), we rather output html and that gets rendered by the browser.

> Thanks, but this is not a great alternative, since on high-DPI monitors one would need to scale all the UI elements, not just the text.

I agree. Please upvote #519.
