### ISSUE TITLE
Is it possible to allow to select a different file when moving code to new file using the refactor tool?

### ISSUE THREAD

**Issue by Damilope** [microsoft/vscode#144704] opened 2022-03-08 19:05 UTC
When refactoring code, there's the option to move to a new file which is pretty useful and cool. Is it possible to select the destination file (like select an existing file), rather than creating a new file? I am using it on Typescript code.

**Comment by mjbvz** [comment] 2022-03-09 22:42
Duplicate of #50685

**Closed by mjbvz** 2022-03-09 22:42 UTC
