### ISSUE TITLE
New Feature - Filter option required in Explorer in Left Panel

### ISSUE THREAD

**Issue by zeshan91** [Microsoft/vscode#44377] opened 2018-02-26 04:29 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. No filter option present in Explorer present in Left Panel
2. We need a way to filter out files

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment] 2018-02-26 15:55
Duplicate of https://github.com/Microsoft/vscode/issues/10026

**Closed by RMacfarlane** 2018-02-26 15:55 UTC
