### ISSUE TITLE
wsl terminal

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/vscode#120333] opened 2021-04-01 10:26 UTC
![shell](https://user-images.githubusercontent.com/23334732/113280925-86cc5100-9317-11eb-8865-439c4d4e0fed.jpg)
![error](https://user-images.githubusercontent.com/23334732/113280949-8c299b80-9317-11eb-853d-92ff76d7d15e.jpg)
### There is no support for multilingualism
![code](https://user-images.githubusercontent.com/23334732/113280954-8df35f00-9317-11eb-8348-4db7e3e36eba.jpg)

**Comment by lengyuxuan** [comment] 2021-04-01 10:28
I will pull merge  request

**Comment by lengyuxuan** [comment] 2021-04-01 10:32
wsl -l -q

**Comment by mpasteur** [comment] 2021-04-06 16:00
Duplicate of #120321

**Comment by takapiro99** [comment] 2021-04-14 09:44
it seems to be solved with this PR
https://github.com/microsoft/vscode/pull/120382

**Comment by meganrogge** [comment] 2021-04-14 15:45
Duplicate of #120321

**Comment by meganrogge** [comment] 2021-04-14 15:46
This should be fixed in Insider's

**Closed by meganrogge** 2021-04-14 15:45 UTC
