### ISSUE TITLE
Turns unresponsive on deleting files through file explorer

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#101318] opened 2020-06-29 21:47 UTC
Issue Type: <b>Bug</b>

### Steps to reproduce
1. From the file explorer pane, delete any file.
2. Observe that clicking anywhere inside the vscode window no longer works, until I close/minimize the window and reopen.

VS Code version: Code - Insiders 1.47.0-insider (7923112cdd20575406ec547b55a99c289dd7d7e2, 2020-06-29T06:49:12.675Z)
OS version: Linux x64 5.7.6-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 1864)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.71GB (1.41GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.15.0
cpptools|ms-|0.28.3
material-icon-theme|PKi|4.2.0

(3 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2020-06-30 08:10
I can not reproduce.
Can you reproduce with todays vscode insiders (since we went back to elecontr 7)?
Can you reproduce if you disable all extensions?

**Comment by infixint943** [comment] 2020-06-30 08:45
Yes, I can still reproduce it, even with extensions disabled.
I've upgraded to todays insiders version through `yay -S visual-studio-code-insiders`

**Comment by isidorn** [comment] 2020-06-30 08:55
Did you see something like this @deepak1556 @bpasero 
Let's leave it open and see if other users are hitting this.

**Comment by bpasero** [comment] 2020-06-30 09:00
This is https://github.com/electron/electron/issues/11555

**Comment by isidorn** [comment] 2020-06-30 09:10
Thanks Ben. Then closing as dup of https://github.com/microsoft/vscode/issues/85332

**Closed by isidorn** 2020-06-30 09:10 UTC
Labels: file-explorer, needs more info
