### ISSUE TITLE
Breakpoints don't work on imported TypeScript modules

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode#7836] opened 2016-06-17 21:16 UTC
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5
- node version 4.4.2
- tsc version 1.8.9
[chorus copy.zip](https://github.com/Microsoft/vscode/files/321280/chorus.copy.zip)

Steps to Reproduce:

1.  Open attached project
2.  Set breakpoint on src/subtext/subtext.ts line 2 (console.log...)
3.  run debugger on "all tests"
4. debugger hits the "debugger" statement on line 3 but skips the breakpoint.

**Comment by weinand** [comment] 2016-06-20 22:21
@JonathanMEdwards thanks for providing the zipped project. That made it very easy to identify this issue as a duplicate of https://github.com/Microsoft/vscode/issues/6549. 
The simplest workaround is to rename the 'src' folder something else.
This issue will be fixed in the June release.

**Closed by weinand** 2016-06-20 22:21 UTC
Labels: bug, debug, duplicate

**Comment by weinand** [comment] 2016-06-20 22:30
@JonathanMEdwards fix will be available in next Insider build

**Comment by JonathanMEdwards** [comment] 2016-06-21 17:24
Thanks for the quick fix!
