### ISSUE TITLE
Add `when` context: editorGroupMaximized

### ISSUE THREAD

**Issue by utilityboy** [microsoft/vscode#24163] opened 2017-04-07 02:34 UTC
Following on #8989, we have the ability to bind shortcuts for `maximizeEditor` and `evenEditorWidths` as a workaround for the fact that `Maximize Editor Group and Hide Sidebar` is not a toggle.

Would it be possible to get a context to allow the keyboard shortcut to effectively toggle between the two with the same keyboard shortcut?

e.g.

```
    {
        "key": "shift+cmd+enter",
        "command": "workbench.action.maximizeEditor",
        "when": "!editorGroupMaximized"
    },
    {
        "key": "shift+cmd+enter",
        "command": "workbench.action.evenEditorWidths",
        "when": "editorGroupMaximized"
    }
```

Aside if the difficulty in making `Maximize Editor Group and Hide Sidebar` a toggle is the "Hide Sidebar" bit, from a usability perspective, I think the showing or hiding of the sidebar could be left to the user in any case (like `Toggle Maximized Panel` for example).

Thanks for the consideration.

**Comment by bpasero** [comment] 2017-04-10 07:22
PR welcome.

**Comment by johnnadratowski** [comment] 2017-05-12 03:43
I just thumbs-up 'ed this , and I'm going to keep it because it would benefit current functionality.  However, I'm a new VSCode user (should say convert. loving it.) and I do miss functionality I've seen in other editors which allows for a toggle between a true fullscreen editor group view, and a remembered editor group/panel state.

**Comment by utilityboy** [comment] 2017-06-29 23:24
@bpasero I'd be happy to try to work something up.  Any pointers on where to start?

**Comment by bpasero** [comment] 2017-06-30 04:24
The class that owns editor layout in particular is [`editorGroupsControl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorGroupsControl.ts#L199).

**Comment by DaniilVystoskiy** [comment] 2017-10-27 09:52
@utilityboy, Hi! Is there any work around? )

**Comment by utilityboy** [comment] 2017-11-12 19:25
@DaniilVystoskiy not that I've found just yet.  I've been using this lately:

```
{
        "key": "shift+cmd+enter",
        "command": "workbench.action.minimizeOtherEditors"
    },
    {
        "key": "ctrl+shift+cmd+enter",
        "command": "workbench.action.evenEditorWidths"
    }
```

I spent a couple hours trying to add the context but wasn't getting very far.

**Comment by Michel73** [comment] 2017-11-16 13:41
My two cents, my workaround for a `toggle maximize editor` :
I've installed the `macros`-Plugin and defined a macro in the `user-settings`.
```
"macros": {
    "maximizeEditor": [
      "workbench.action.maximizeEditor",
      "workbench.action.closePanel"
    ]
}
```
then in the keybindings.json I defined `ctrl + m` as maximize toggle:
```
{
    "key": "ctrl+m",
    "command": "macros.maximizeEditor",
    "when": "explorerViewletVisible"
  },
  {
    "key": "ctrl+m",
    "command": "workbench.view.explorer",
    "when": "!explorerViewletVisible"
  }
```
If the `explorer` (and the panel) is visible the editor will be maximized. If `search`, `scm`, `debug` or `extensions` is visible, then first the `explorer` will made visible and then the editor will be maximized.
It is not a real toggle but my closest trial to get one.

**Comment by nikitavoloboev** [comment] 2018-08-10 07:25
Is it possible to do this yet?

I have this binding in VS Code:

```json
  {
    "key": "ctrl+m",
    "command": "workbench.action.maximizeEditor",
    "when": "editorFocus"
  },
```

One thing I am missing is to extend this binding to unmaximize the editor as it was before and bind it to the same hotkey. Is this possible to do?

**Comment by DaniilVysotskiy** [comment] 2018-08-10 07:38
@nikitavoloboev not yet. You have to bind another shortcut to fold this back.

**Comment by nikitavoloboev** [comment] 2018-08-10 08:09
> You have to bind another shortcut to fold this back.

Can you post that other shortcut please?

**Comment by DavidBabel** [comment] 2018-11-26 15:38
As commented here : https://github.com/Microsoft/vscode/issues/16927
I had this issue too and it bored me.
I include a fix in this extension i made : https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever

**Comment by akbyrd** [comment] 2019-04-27 20:37
Alternative solution: just add a new action for toggling. https://github.com/Microsoft/vscode/issues/72968

**Comment by bpasero** [comment] 2019-08-09 11:16
@utilityboy @DavidBabel @nikitavoloboev @Michel73 and others, I wonder if this can be accomplished by what https://github.com/microsoft/vscode/issues/72968 asks for without having to introduce this new context.

To clarify, there would be a new action that:
* maximizes the currently active editor group if is it not maximized already
* even out the widths otherwise

Looks like that:
![Peek 2019-08-09 13-16](https://user-images.githubusercontent.com/900690/62775440-f2f5a380-baa7-11e9-9889-ee8840c8ce1f.gif)

**Comment by nikitavoloboev** [comment] 2019-08-09 11:22
If I understand it correctly, it basically will add an action to `maximize` the current active tab. And if hotkey is activated when the window is maximized, the window will stop being maximized and will return to default state.

This would work for me.

**Comment by bpasero** [comment] 2019-08-09 11:26
@nikitavoloboev yes it is basically a combination of the 2 existing actions "Maximize Editor Group" and "Reset Editor Group Sizes" serving as toggle.

**Comment by bpasero** [comment] 2019-08-09 12:54
I just pushed a change for https://github.com/microsoft/vscode/issues/72968 and will consider this request compete thereby.

Duplicate of https://github.com/microsoft/vscode/issues/72968

**Closed by bpasero** 2019-08-09 12:54 UTC
Labels: feature-request, keybindings, workbench-editors

**Comment by utilityboy** [comment] 2019-08-10 19:41
@bpasero this is exactly what folks are trying to achieve in my opinion.  Terminal applications like iTerm have such a toggle to "focus" work.  This is great!  Many thanks.

**Comment by akbyrd** [comment] 2019-08-13 15:58
This is excellent! Thanks @bpasero.

Is it possible to nudge this related issue? https://github.com/microsoft/vscode/issues/73453 With that resolved maximizing editors will be a nice part of my daily workflow.
