### ISSUE TITLE
Error Loading webview: Simple Browser: Show

### ISSUE THREAD

**Issue by ullaskunder3** [microsoft/vscode#192974] opened 2023-09-13 07:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.82.1
- OS Version: Linux x64 6.4.14 fedora

Steps to Reproduce:

1. vite react template `npm run dev`
```
  VITE v4.4.9  ready in 988 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```
2. on command pallet `Simple Browser: Show` enter url

```
Error loading webview: Error: Could not register service worker: 

InvalidStateError: Failed to register a ServiceWorker:
The document is in an invalid state..
```
![Screenshot from 2023-09-13 12-58-22](https://github.com/microsoft/vscode/assets/66258652/27fa6a0e-ebd3-4547-b916-7a72dd11bb8b)

**Comment by tamuratak** [comment] 2023-09-13 07:42
Might be duplicate of #125993

**Comment by gjsjohnmurray** [comment] 2023-09-13 09:26
Similar to #192965

**Comment by ullaskunder3** [comment] 2023-09-13 09:46
in few previous version it was working... I just updated code today in fedora and this thing stopped working

**Comment by ullaskunder3** [comment] 2023-09-18 18:51
i think it was some how related to the issue i faced recently vs code goes blank

after kill and disable gpu is start working and same for this simple browser i guess 

```
$ killall code
$ code --disable-gpu
```

**Comment by mjbvz** [comment] 2023-12-04 23:35
Duplicate of #125993

**Closed by mjbvz** 2023-12-04 23:35 UTC
