### ISSUE TITLE
Feature requests for smartSelect

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#33118] opened 2017-08-24 22:45 UTC
- VSCode Version: 1.15.1

Allow configuration exclusion for no selected symbols at the boundary, like `"'` & "\`", `{}[]()`, `《》“”` and more.
Allow select to start/end of the string with Shift+Alt+Home/End or PageUp/Down. This helps to replace a part of the string.

**Comment by jrieken** [comment] 2017-10-26 08:14
duplicate of #4795

**Closed by jrieken** 2017-10-26 08:14 UTC
Labels: editor

**Comment by imzjy** [comment] 2017-11-09 14:37
It's not worked for both single quotes and double quotes.
for example:
`import jQuery from '**jquery**';`

If I'd like to select jquery which inside of single quotes, it's not possible with "Expand Select".
The "Expand Select" command will select `'jquery'`, but we want `jquery` in first of trigger of "Expand Select"

Platform: Max OS X
VS Code Version: 18.1
