### ISSUE TITLE
Cannot save file when pasting text that starts with `//`

### ISSUE THREAD

**Issue by washed** [microsoft/vscode#90433] opened 2020-02-11 09:20 UTC
While copy&pasting some C++ into a new file in VSCode, i ran across this strange issue.
When the pasted text starts with a comment string it is impossible to save the file, even when explicitly using "Save As..."

Steps to reproduce:

1. Open a new file (e.g. with Ctrl+N)
2. Paste or type text into it which begins with a double forward slash
`// some text`
3. Try so save the file
4. Receive this toast notification:

> Failed to save '// some text': [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters (`//`)

Supposition:
VSCode implicitly treats the first line in the file as the file name (why?) which causes problems when the first line starts with `//`, supposedly because it looks like a URI?

Tested with `code --disable-extensions`
Probably related to: #90434

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.3
pascal-formatter|ale|2.2.0
vscode-custom-css|be5|3.0.9
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
vscode-todo-plus|fab|4.14.1
innosetup|idl|1.2.0
reg|ion|1.0.1
latex-workshop|Jam|8.7.1
rainbow-csv|mec|1.5.0
lrf-highlight|mf-|0.0.1
python|ms-|2020.1.58038
remote-wsl|ms-|0.42.3
cpptools|ms-|0.26.3
csharp|ms-|1.21.11
powershell|ms-|2020.1.0
printcode|nob|3.0.0
vscode-print|pdc|0.7.13
trailing-spaces|sha|0.3.1
vscode-table-formatter|shu|1.2.1
octave|toa|0.0.3
selectline-statusbar|tom|0.0.2
vscode-icons|vsc|9.7.0
vscode-todo-highlight|way|1.0.4
markdown-pdf|yza|1.4.1
linkerscript|Zix|1.0.0

**Comment by IllusionMH** [comment] 2020-02-11 14:38
Are there reason to have 2 similar issues?

First line is used to differentiate contents and used as filename suggestions https://code.visualstudio.com/updates/v1_42#_untitled-editor-improvements

/confirmationPending
Anyway I cannot reproduce this issue

When I save C++ file with comment in first line all special characters are removed and only space at the beginning is left (will be omitted when saved).
![image](https://user-images.githubusercontent.com/1312662/74245959-7bb9fa00-4cec-11ea-8b9a-da4123424f66.png)

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (12.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by washed** [comment] 2020-02-11 14:53
For me these seemed like two related, but different bugs. The one regards the saving of these files, the other is more about the tab controls breaking. Sorry if this was a bad idea.

Interesting that you cannot repro. Is there anything else I can try to narrow it down? I already tried without extensions.

**Comment by IllusionMH** [comment] 2020-02-11 15:10
>tab controls breaking.

What do you mean under tab controls? I see only this list + Close all in More actions dropdown for group.
![image](https://user-images.githubusercontent.com/1312662/74247740-38ad5600-4cef-11ea-9ca7-588c1863d491.png)

I tried:
<kbd>Ctrl</kbd>+<kbd>F4</kbd>, <kbd>Ctrl</kbd>+<kbd>W</kbd>, <kbd>Ctrl</kbd>+<kbd>K</kbd><kbd>W</kbd>, Close button on tab, and Close, Close All, Close to the Right from context menu on tab - all show confirmation with `//` in suggested name, however after click on Save there are no `//` in File name field.
![image](https://user-images.githubusercontent.com/1312662/74248737-b6be2c80-4cf0-11ea-9a9b-125960c078a8.png)

<kbd>Ctrl</kbd>+<kbd>S</kbd>, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>, <kbd>Ctrl</kbd>+<kbd>K</kbd><kbd>S</kbd> and Save, Save as... Save All form File menu - all open standard Save As dialog that doesn't have `//` in File name field.

Code I tried in C++ and Plain Text language modes
```cpp
// some text
#include <iostream>
int main() 
{
    std::cout << "Hello, World!";
    return 0;
}
```

**Comment by washed** [comment] 2020-02-11 15:22
Sorry for being unclear. Yes by tab controls i meant the ones in the context menu you showed in the screen shot.

I also cannot reproduce it anymore and I have no idea why. It was happening all the time this morning, even through restarts of VSCode, with extension disabled etc.
Now everything works as expected. I can only guess i got my editor into some kind of strange state. I will attempt to reproduce it again.

**Comment by bpasero** [comment] 2020-02-12 06:39
I can also not reproduce this issue. I also tried the simple file dialog (by configuring `"files.simpleDialog.enable": true` which uses an entire different UI. 

I wonder if I should filter out any character that is considered invalid on the OS and maybe also that could be a path separator. Even though windows is probably handling this fine, we could protect against this.

**Comment by bpasero** [comment] 2020-02-12 06:40
Closing until we have better steps how to reproduce.

**Closed** 2020-02-12 06:40 UTC
Labels: confirmation-pending

**Comment by bpasero** [comment] 2020-02-12 07:16
I pushed https://github.com/microsoft/vscode/commit/61ac88515d361700ded06a60f937c65345882437 to suggest the old file name as it used to be (e.g. `Untitled-1`) if the first line contains any characters that are not valid for a file name.

**Comment by washed** [comment] 2020-02-12 08:35
Whatever I tried, I was unable to reproduce the issue. I am sorry to have wasted your time. As is said, it happened all morning yesterday and then suddenly stopped. Perhaps it was something weird in my environment, although nothing comes to mind. Should this happen again and I have further information, should I post it in this issue or create a new one? Thanks for your help.

**Comment by bpasero** [comment] 2020-02-12 09:19
I would not think this can happen again given the change I pushed to never propose invalid file names for the dialog. This change is in starting tomorrows insider build.
