### ISSUE TITLE
Feature Request: Cursor should automatically jump to next line when "Comment line" shortcut key is held

### ISSUE THREAD

**Issue by ishanjain28** [Microsoft/vscode#33648] opened 2017-09-01 07:59 UTC
This is a Feature Request.

Currently, Holding the shortcut key to "Comment Line" does nothing. So, If I want to comment multiple consecutive lines, I have to first select all those lines/add cursors and then comment them. This behaviour is different than most IDEs and text editors and a teensy bit annoying. 

As holding down "Comment Line" shortcut(Ctrl + "/")  currently does nothing. My suggestion is to add a system so if the shortcut is held for more than 2-3 seconds(Configurable) the cursor will jump to next line and comment it and keep doing that until you've released the shortcut keys. 

This behaviour is similar to other IDEs and editors making it easier for people coming from other IDEs/editors to adapt vscode and also makes better use of shortcut. 

If this sounds like a reasonable request, I would absolutely love to work on it.

**Comment by rebornix** [comment] 2017-09-05 21:25
Thanks! It's duplicate of https://github.com/Microsoft/vscode/issues/32411 .

**Closed by rebornix** 2017-09-05 21:25 UTC
Labels: editor, editor-contrib
