### ISSUE TITLE
Hitting the tab key inserts <tab></tab>

### ISSUE THREAD

**Issue by AndreSteenveld** [Microsoft/vscode#60076] opened 2018-10-06 21:20 UTC
Issue Type: <b>Bug</b>

I am not completly sure what the root cause is. But when I open a file and start typing everything works as you'd expect. After going to another window or to another file and coming back to the orginal one hitting the tab-key will insert ```<tab></tab>```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
terminal|for|0.0.10
vetur|oct|0.12.7
vim|vsc|0.16.6
gitblame|wad|2.4.4

</details>

**Comment by RMacfarlane** [comment] 2018-10-07 01:54
@AndreSteenveld @skbolton This is being caused by the vim extension: https://github.com/VSCodeVim/Vim/issues/3096

Looks like a fix has already been checked in for it, not sure when the next release will be. In the meantime, the extension repo has the `.vsix` files of the previous releases, so you could downgrade to the previous version

**Closed by RMacfarlane** 2018-10-07 01:54 UTC
