### ISSUE TITLE
port forwarding for allinterfaces fail

### ISSUE THREAD

**Issue by semal** [microsoft/vscode#165329] opened 2022-11-03 09:52 UTC
Type: <b>Bug</b>

I change the port forwarding config all to allinterfaces, but when i add a new port still localhost auto set and can not changed to be 0.0.0.0

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:33:40.745Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+ab02' could not be established
Remote OS version: Linux x64 4.15.0-194-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id e487c8cf-d8bb-48cb-b102-25d0661ffcb2|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+ab02' could not be established

|Item|Value|
|---|---|
|Remote|SSH: ab01|
|OS|Linux x64 4.15.0-194-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (256 x 1499)|
|Memory (System)|503.78GB (478.29GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.73.11020948
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
protein-viewer|Ari|0.0.8
gmxlang|Cas|1.0.11
dataiku-dss|Dat|1.3.0
copilot|Git|1.56.7152
gc-excelviewer|Gra|4.2.56
rainbow-csv|mec|3.2.0
vscode-docker|ms-|1.22.2
vscode-language-pack-zh-hans|MS-|1.73.11020948
isort|ms-|2022.4.0
python|ms-|2022.18.0
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vs-browser|Phu|2.0.9
biosyntax|rea|0.0.11
vscode-yaml|red|1.10.1
cif|thi|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
3d0df643:30602300

```

</details>

**Comment by alexr00** [comment] 2022-11-03 11:49
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6445

**Closed by alexr00** 2022-11-03 11:50 UTC
Labels: new release
