### ISSUE TITLE
Custom file association breaks VSCode command line registry entry.

### ISSUE THREAD

**Issue by milkergy** [Microsoft/vscode#13919] opened 2016-10-18 04:41 UTC
- VSCode Version: 1.6, 1.6.1
- OS Version: MS Windows 7 Enterprise SP1

Steps to Reproduce:
1. Install the latest stable VSCode 1.6.1
2. Check

> `HKEY_CLASSES_ROOT\vscode\shell\open\command`

registry entry, it should say:

> `"C:\Program Files (x86)\Microsoft VS Code\Code.exe" "%1"`
1. Add a custom file association that has a VSCode entry in:

> `HKEY_CLASSES_ROOT\*.custom\OpenWithProgids`
1. Try and open a _**.custom_\* file. It should open fine.
2. Close VSCode
3. Check`HKEY_CLASSES_ROOT\vscode\shell\open\command`, it now says:

> `"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --open-url "%1"`

`--open-url` option does not work on Windows, double-clicking your *.custom files opens VSCode, but the file's not opened.

**Comment by joaomoreno** [comment] 2016-10-20 14:38
Damn it, nice catch @milkergy!

**Comment by bpasero** [comment] 2016-10-28 07:54
I verified that for an unknown file extension I can associate VS Code from the "Open With" dialog and that it opens the file with VS Code. I did not follow the exact steps in the description because I think our users will not go into the windows registry and change something there.

**Comment by joaomoreno** [comment] 2016-10-28 07:59
@bpasero The URL handling feature from Electron broke the registry that our Setup created. The fix was to rename that registry key in our setup. This only reproduces in Stable though, not in Insiders.

**Comment by bpasero** [comment] 2016-10-28 08:17
Ah ok, then I did not verify correctly.

**Comment by pmcoz** [comment] 2016-12-03 22:23
Has this really been fixed? In 1.7.2 in Windows 7, I reset the .txt file association (by removing --open-url in the relevant registry entry), and on double-clicking a .txt file it opens correctly—but only once! Having opened the file, VS Code seems to put the --open-url back into the registry, which prevents the .txt file from being opened the same way again. VS Code should either accept the --open-url parameter, or not write it to the registry.

**Comment by milkergy** [comment] 2016-12-04 02:51
Yeah, I can confirm that the behavior stayed the same in the latest release version.

**Comment by joaomoreno** [comment] 2016-12-05 07:51
@pmcoz @milkergy Try a full uninstall/install, it should be fixed.

**Comment by pmcoz** [comment] 2016-12-05 23:47
@joaomoreno Just tried that; no change. Before running VS Code, I set HKEY_CLASSES_ROOT\vscode\shell\open\command to "C:\Program Files (x86)\VS Code\Code.exe" "%1". After running VS Code, VS Code has changed the value to "C:\Program Files (x86)\VS Code\Code.exe" --open-url "%1".

**Comment by joaomoreno** [comment] 2016-12-06 08:07
What's the value of `HKEY_CLASSES_ROOT\vscodeSourceFile\shell\open\command`?

**Comment by pmcoz** [comment] 2016-12-06 21:43
There is no HKEY_CLASSES_ROOT\vscodeSourceFile key.

There is, however, HKEY_CLASSES_ROOT\vscode\shell\open\command, which is "C:\Program Files (x86)\VS Code\Code.exe" --open-url "%1".

I would have thought that the problem is the insertion of --open-url that VS Code can't subsequently understand (on Windows).

I note that the VS Code uninstallation does not remove its AppData files; maybe it doesn't clean up the registry either. Ergo, perhaps vestiges of the previous behavior can survive uninstallation.

**Comment by joaomoreno** [comment] 2016-12-07 07:45
@pmcoz 1.7.2 should've inserted that key when updated... I verified that myself. If you reinstall the setup, does it come up?

**Comment by pmcoz** [comment] 2016-12-07 22:20
I uninstalled, then reinstalled via the setup file. No key. Perhaps the setup is seeing one of the old keys and is then bailing out of updating the registry. I'll try to delete all the old VS Code keys before installing again.

**Comment by joaomoreno** [comment] 2016-12-08 07:25
That's so strange, as I consistently see the keys. This is 1.7.2 right?

**Comment by pmcoz** [comment] 2016-12-08 23:27
Yes, 1.7.2. I also installed on a second Windows 7 machine, and that key wasn't created.

Perhaps HKEY_CLASSES_ROOT\vscodeSourceFile is only created if using one or more of the file association options available in the installer. I deselect all of those since I prefer greater control. I'm reticent to see what happens when they're selected because I'm not confident of being able to roll back.

I gather this makes me dependent on HKEY_CLASSES_ROOT\vscode\shell\open\command.

I can probably work around this by associating files with a .BAT that calls code.exe.

**Comment by joaomoreno** [comment] 2016-12-09 08:08
> Perhaps HKEY_CLASSES_ROOT\vscodeSourceFile is only created if using one or more of the file association options available in the installer.

Good catch, that's exactly it! I'll push a fix to always add it regardless of that checkbox. 👍

**Closed** 2016-12-09 08:12 UTC
Labels: bug, in-releasenotes, windows

**Comment by chrmarti** [comment] 2016-12-09 16:54
Verified that:
- `"C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" "%1"` is added when the checkboxes are unchecked during install
- I can associate a custom file extension and such files are then opened in VSCode
- The above registry entry stays the same after opening/closing VSCode

Marking verified.

**Comment by pmcoz** [comment] 2016-12-09 21:41
@joaomoreno Outstanding! I'm very pleased to have been able to help.

Thank you for persevering with this issue. :)

**Comment by joaomoreno** [comment] 2016-12-12 08:22
@pmcoz No, thank you for your persistence! 👍

**Comment by vineykhera** [comment] 2017-06-14 21:57
Getting this same issue while installing VS code 1.13 and 1.14 on windows 10

HKEY_classes_root\vscode source file\shell\open\command

how to resolve this?

**Comment by gstamac** [comment] 2017-08-22 12:25
Same here.
