### ISSUE TITLE
Close to the left

### ISSUE THREAD

**Issue by ibnshayed** [microsoft/vscode#120151] opened 2021-03-30 05:23 UTC
Please add a future like 'Close to the left' on the tab menu, here is only 'Close to the right menu presence on the tab menu by clicking the right button of the mouse.

**Comment by gjsjohnmurray** [comment] 2021-03-30 06:16
/duplicate of #116165 which needs a lot more 👍 on the issue to get beyond Backlog Candidate status.

**Closed** 2021-03-30 06:17 UTC
Labels: *duplicate
