### ISSUE TITLE
Editor: Folding Spoiler

### ISSUE THREAD

**Issue by Fyrestar** [microsoft/vscode#141897] opened 2022-01-31 19:20 UTC
When closing folds nothing about the inside is visible, when having objects as "fields" or properties that have a "name" or "id" property for instance, it would be incredibly useful that the fold spoilers these. I come from PHPStorm were this feature is available, and it really became an issue as i have to unfold longer lists of fields to find what i'm looking for without unfolding all.

The property/attribute keys searched for could be defined in the settings with the priority, for instance
- id
- name
- title
- label

If one of them by priority is found it could be previewed like PHPStorm does

When folded
![image](https://user-images.githubusercontent.com/28584767/151857468-9a882171-6944-4ac6-a7a9-2e487360b496.png)
![image](https://user-images.githubusercontent.com/28584767/151857510-99082fd3-5896-4a9a-863f-f4a46251487a.png)

And could be implemented in general this way for the default languages, like for HTML elements.

**Comment by aeschli** [comment] 2022-02-01 15:35
duplicate of https://github.com/microsoft/vscode/issues/70794

**Closed by aeschli** 2022-02-01 15:35 UTC
