### ISSUE TITLE
Automatically adjust font size and indent length in file explorer

### ISSUE THREAD

**Issue by FuuuOverclocking** [microsoft/vscode#149916] opened 2022-05-19 09:34 UTC
Related issues and PRs:

- [#519 ](https://github.com/microsoft/vscode/issues/519)
- https://github.com/microsoft/vscode/pull/144365

I hope vscode can use a more intelligent and ergonomic method to automatically adjust the font size and indent length in File Explorer.

Personally, I think the size of other components (such as buttons in the side bar and top bar) is very appropriate, but the font in file explorer is too small, and the indent length of the directory structure is too short, which makes it difficult for me to distinguish.

In contrast, the font size of the file explorer in Jet Brains Idea under the default setting is very suitable for me.

Therefore, I hope vscode can add a setting item. By enabling it, when there is enough width, the font and indent length in Explorer will automatically increase within an appropriate range. When the width is insufficient, it will be reduced to the current level.

This may be a better approach than simply allowing users to adjust the font size. This is because when users, if had previously enlarged the font size, get into a large workspace, they are likely to want to go back to the small font setting.

**Comment by FuuuOverclocking** [comment] 2022-06-12 05:44
24 days have passed. Has anyone seen this issue?

**Comment by lramos15** [comment] 2022-06-13 14:56
Dynamic font resizing sounds weird. There are workspace settings so the user can set per workspace. I will mark this as a duplicate of #519 since I think that would solve your problem.

**Closed by lramos15** 2022-06-13 14:56 UTC
