### ISSUE TITLE
3 Way Merge Editor's detecting conflicts is not specific during rebase, better to hava a toggle back to old editor

### ISSUE THREAD

**Issue by Void-King** [microsoft/vscode#157469] opened 2022-08-08 03:36 UTC
Operation: 
git rebase branch-xxx

in 1.68.1:
![image](https://user-images.githubusercontent.com/49579559/183332195-8003249c-06ae-4f34-a0ca-18f8ed232aff.png)

the editor could detect specific conflicts and choose which to keep easily,

in 1.70
![image](https://user-images.githubusercontent.com/49579559/183333305-602e478a-ea4c-479a-b968-45c230bef3e5.png)
the editor considers the whole file as conflict while there are only serveral lines changed,
personally i would pefer the old editor and wish to have a toggle back to it

**Comment by suxinmian** [comment] 2022-08-08 04:49
me too 1.70
now  I don't know how to resolve the conflict

**Comment by gjsjohnmurray** [comment] 2022-08-08 05:41
See https://github.com/microsoft/vscode/issues/157268#issuecomment-1206670413 for how to reinstate the old behaviour. But the team probably wants to discover why this new feature isn't working well for you. Pinging @lszomoru

**Comment by hediet** [comment] 2022-08-08 07:52
@Void-King can you share an anonymized version of your code, so we can debug this?

The conflict ranges in VS Code should have the same size as in git, so this is clearly a bug.
Most likely this is a flaw in our diffing algorithm, but we need a sample to investigate.

**Comment by Void-King** [comment] 2022-08-08 08:43
@hediet 

here's my operations

create a new branch **conflict**
new and commit a file **merge_conflict_test.go**, with **Name: "n1"**

```go
// branch conflict
package main

import (
	"github.com/gin-gonic/gin"
)

func Foo1(c *gin.Context) {
	s1 := s{
		ID:        111,
		Condition: "c1",
		Check:     true,
		Name:      "n1" // diff from master
	}
}

func Foo2(c *gin.Context) {
	line1 := "line1"
	line2 := "line2"
	line3 := "line3"
	line4 := "line4"
	line5 := "line5"
	line6 := "line6"
}

func Foo3(c *gin.Context) {
	s3 := s{
		ID:        123,
		Condition: "c3",
		Check:     true,
		Name:      "n3" // diff from master
	}
}
```

back to **master**, also new file **merge_conflict_test.go**, without **Name: "n1"**

```go
// branch master
package main

import (
	"github.com/gin-gonic/gin"
)

func Foo1(c *gin.Context) {
	s1 := s{
		ID:        111,
		Condition: "c1",
		Check:     true,
	}
}

func Foo2(c *gin.Context) {
	line1 := "line1"
	line2 := "line2"
	line3 := "line3"
	line4 := "line4"
	line5 := "line5"
	line6 := "line6"
}

func Foo3(c *gin.Context) {
	s3 := s{
		ID:        123,
		Condition: "c3",
		Check:     true,
	}
}
```

commit, then goto **conflict**, rebase **master**
![image](https://user-images.githubusercontent.com/49579559/183375450-354e68a2-65a4-486c-96cc-92f0cfee1705.png)

with **"git.mergeEditor": false** on
![image](https://user-images.githubusercontent.com/49579559/183375628-08cb452d-e311-4947-97a7-e053fffd7915.png)

3 way merge editor:
![image](https://user-images.githubusercontent.com/49579559/183375945-38e9a3f1-0f3c-4b65-8c1e-be1acaf6270b.png)

**Comment by hediet** [comment] 2022-08-08 10:00
I see. Currently, this is by design, but getting the same behavior as git might be preferrable here. Thanks!

**Comment by hediet** [comment] 2022-08-08 10:02
I created a [feature request](https://github.com/microsoft/vscode/issues/157496) for this.

Since this issue would be fixed by that feature request, I'm going to close this.

**Closed by hediet** 2022-08-08 10:02 UTC
Labels: info-needed, merge-editor
