### ISSUE TITLE
Intellisense behavior when using import and require 

### ISSUE THREAD

**Issue by caiotavares** [Microsoft/vscode#22710] opened 2017-03-16 02:43 UTC
Intellisense has a strange behavior for import and require statements when using JSDoc "param" tag:

Considering we have a project with three files: foo1.js, foo2.js and bar.js

**foo1.js**:
```javascript
export class Foo1 {
    constructor(name) {
        this.name = name;
    }
}
```

**foo2.js:**
```javascript
module.exports = class Foo2{
    constructor(name){
        this.name = name;
    }
}
```

Now, in the bar.js file, I have Intellisense working fine for the imported Foo1, but Foo2 doesn't seen to be recognized when used in "param":

![1](https://cloud.githubusercontent.com/assets/7378941/23979521/c4903f1e-09d8-11e7-8e73-94ee9f8d4e3f.jpg)

![2](https://cloud.githubusercontent.com/assets/7378941/23979522/c850ecb6-09d8-11e7-9cec-0933c7096c02.jpg)

- VSCode Version: 1.10.2
- OS Version: Windows 10.0.14393

**Comment by mjbvz** [comment] 2017-03-16 23:51
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/14056

**Closed by mjbvz** 2017-03-16 23:51 UTC
Labels: duplicate, javascript, upstream
