### ISSUE TITLE
Integrated Terminal Not Working

### ISSUE THREAD

**Issue by mithuu** [Microsoft/vscode#69420] opened 2019-02-25 22:41 UTC
Issue Type: <b>Bug</b>

integrated terminal not working cannot type anything in it! just blank!

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.0.1
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.9
LiveServer|rit|5.5.1
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment] 2019-02-26 01:17
Probably a duplicate of https://github.com/Microsoft/vscode/issues/68346 or https://github.com/Microsoft/vscode/issues/57803

**Closed by Tyriar** 2019-02-26 01:17 UTC
Labels: integrated-terminal
