### ISSUE TITLE
Notebook: status icon hard to read in dark theme

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96437] opened 2020-04-28 15:54 UTC
Refs: https://github.com/microsoft/vscode/issues/96279

Referring to the icon left to the title:

![image](https://user-images.githubusercontent.com/900690/80509140-45019080-8979-11ea-8da5-91a60b20b9e6.png)

**Comment by jrieken** [comment] 2020-04-28 15:58
/duplicate of https://github.com/microsoft/vscode-github-issue-notebooks/issues/15

**Closed** 2020-04-28 15:59 UTC
Labels: *duplicate, notebook, web
