### ISSUE TITLE
gutter indicators does not work when ssh remote host

### ISSUE THREAD

**Issue by we98** [microsoft/vscode#122262] opened 2021-04-27 03:22 UTC
- VS Code Version: 1.55.2 (Universal)
- OS Version: Mac OS 10.15.4 (19E287)
- Remote Linux Version: Debian GNU/Linux 9

Steps to Reproduce:

1. use remove-ssh plugin of vscode to connect remote host
2. modify/add/delete files in git directory, but without gutter indicators 
3. gutter indicators works in local git directory

Is there any solution to solve this? 🙏
It's so awkward to write code without gutter indicators.

**Comment by we98** [comment] 2021-04-27 03:32
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [git: add gutter indicators for staged/committed changes (#114316)](https://www.github.com/microsoft/vscode/issues/114316)

 not my want…

**Comment by lszomoru** [comment] 2022-01-04 13:28
@we98 are you still able to reproduce this issue with the latest version of VS Code, and Remote SSH extension? Thanks!

**Comment by Migelo** [comment] 2022-01-12 11:40
I just reproduced this bug with the latest available release I get on Ubuntu from snap.

```
➜ code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

**Comment by ChrisShen93** [comment] 2022-04-13 07:13
same issue here

macos: 12.2.1
vscode: 1.66.2 & 1.67.0-insider, both have the same issue

**Comment by lszomoru** [comment] 2022-04-14 19:46
Various functionality implemented in the `git` extension (ex: refreshing the list of changes, show diff decorators in the editor gutter) relies on file system events. My currently hypothesis is that for some reason either these file system events are not being received by the `git` extension, or that the URIs in the event do not line up with the URIs known by the `git` extension. 

Couple of questions:
1. Are you opening the folder using the cli (ex: `code folder`) or by using the "File -> Open Folder" menu?
2. Does the path that you are opening in VS Code contain any symbolic links? 

Could you please implement the following steps to collect additional information:
1. Open the folder/workspace in VS Code.
2. Invoke the `Git: Set Log Level` command in the command palette and set the log level to `Trace`
3. Use the steps in [the following wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-remote) to enable verbose logging in order to collect file system event logs
4. Make changes to the files, and save them.
5. Send us the git output log that you can access using the `Git: Show Git Output` command, as well as the file system event logs

**Comment by stderr-to-devnull** [comment] 2022-11-03 19:34
Yet another unfixed bug while rolling out a truckload of `new features` every two weeks that absolutely no one cares about.
VSCode 1.73, MacOS Monterey, still happening. Take your time.

**Comment by gjsjohnmurray** [comment] 2022-11-03 20:02
@stderr-to-devnull are you able to supply any of the information @lszomoru asked the OP for?

**Comment by agkphysics** [comment] 2022-11-15 02:41
> 2. Does the path that you are opening in VS Code contain any symbolic links?

In my case it was because the repository root was symlinked to another directory. But I wonder why this only affected the gutters and not the diff view?

**Comment by lszomoru** [comment] 2022-12-13 14:57
At the moment it is known that there are various scenarios that are not working as expected when a repository has a symbolic link on its path. The work to add support for symbolic links is currently tracked here - https://github.com/microsoft/vscode/issues/5970. I will go ahead and close this issue as duplicate, and I would suggest that you subscribe to the linked issue to receive updates when the work is being scheduled. Thank you!

**Closed by lszomoru** 2022-12-13 14:57 UTC
Labels: bug, git
