### ISSUE TITLE
Missing Git Icons

### ISSUE THREAD

**Issue by dalgibbard** [microsoft/vscode#78774] opened 2019-08-09 09:28 UTC
Issue Type: <b>Bug</b>

Hey all,
I seem to be missing the Gitlens extension icon and the git "open file"/"discard"/"stage changes" buttons for some reason.

I've had a quick look around the output tabs and can't see any glaring errors.
I'm running Visual Studio Code 1.37.0 (user) on Windows 10 1903 build 18362, using the remote connection feature into WSL (1) running Ubuntu 18.04.2 LTS

Everything seems to be functioning fine, but just no Git buttons or Gitlens button either. Have tried disabling/changing icon and editor themes; tried uninstalling and reinstalling Gitlens too.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

![missing_stuff](https://user-images.githubusercontent.com/1159620/62769172-596ec780-ba90-11e9-80ad-4ab5817ed05c.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3570)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Legacy|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3501)|
|Memory (System)|31.94GB (20.67GB free)|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
code-settings-sync|Sha|3.4.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
search-node-modules|jas|1.3.0
code-groovy|mar|0.1.2
rainbow-csv|mec|1.2.0
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
Go|ms-|0.11.4
gradle-language|nac|0.2.3
open-html-in-browser|pea|1.2.0
java|red|0.47.0
vscode-xml|red|0.8.0
html-preview-vscode|tht|0.2.5
pdf|tom|0.5.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-08-09 09:44
Duplicate of microsoft/vscode-remote-release#908

**Closed** 2019-08-09 16:19 UTC
Labels: *duplicate, new release

**Comment by dalgibbard** [comment] 2019-08-10 07:15
Nice one, thanks @IllusionMH I'll follow that one :+1:
