### ISSUE TITLE
Test results service unit test timeout

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#140978] opened 2022-01-19 14:58 UTC
Linux Run unit tests (node.js):

```
  1) Workbench - Test Results Service
       "before each" hook for "resultItemParents":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/__w/1/s/test/unit/node/index.js)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=150582&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=b2ac4860-fb3b-5a51-42a7-7423ead0721b&l=3452

**Comment by bpasero** [comment] 2022-01-19 17:26
Duplicate of https://github.com/microsoft/vscode/issues/137853 I think.

**Closed** 2022-01-19 17:28 UTC
Labels: unit-test-failure
