### ISSUE TITLE
JSDoc Type hints not working for imported types.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/vscode#21933] opened 2017-03-03 20:32 UTC
Let me know if this is actually a TypeScript bug.  While there isn't explicitly any TypeScript involved (except the typings file in the source) I recognize that a lot of the JavaScript intellisense is sourced from the TypeScript engine.

- VSCode Version: 1.10.1
- OS Version: Windows 10

Steps to Reproduce:

```javascript
var Foo = require('foo');
/** @type {Foo} */
var foo; // `foo` is of type `any` according to tooltip.
```

```javascript
var Foo = require('foo');
var foo = new Foo(); // `foo` is of type `Foo` according to tooltip.
```

```javascript
/** @type {WebGLRenderingContext} */
var foo; // `foo` is of type `WebGLRenderingContext` according to tooltip.
```

The above illustrates that while VSCode knows about and understands the imported type `Foo` (the package has a typing file).  When using JSDoc for type hinting in JavaScript, VSCode doesn't appear to recognize it in the JSDoc.  The last example shows that the JSDoc hinting is working _in general_ by providing a globally scoped/available type in the doc and seeing that VSCode does the right thing.

**Comment by mjbvz** [comment] 2017-03-08 01:11
Thanks. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/14056 being tracked on the TypeScript side

**Closed by mjbvz** 2017-03-08 01:11 UTC
Labels: upstream
