### ISSUE TITLE
vscode auto create .vscode folder when I open any project

### ISSUE THREAD

**Issue by BrillanceZhang** [Microsoft/vscode#30220] opened 2017-07-07 02:47 UTC
- VSCode Version:1.13.1
- OS Version:windows7

Steps to Reproduce:

1.how can I forbid this function?
2.

Reproduces without extensions: Yes/No

**Comment by joecorkerton** [comment] 2017-07-07 08:34
I also have the same thing, but only for some of my project folders. Not sure what is causing it to only happen for certain projects but not others..

**Comment by bpasero** [comment] 2017-07-07 12:52
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BrillanceZhang** [comment] 2017-07-10 07:05
The donjayamanne.python extension makes this happen. When I uninstall the extension, the .vscode will not be created.

**Comment by bpasero** [comment] 2017-07-10 17:17
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-07-10 17:17 UTC
Labels: needs more info
