### ISSUE TITLE
Can't assign [CMD + "] to 'Toggle Terminal' Action

### ISSUE THREAD

**Issue by efefurkankarakaya** [microsoft/vscode#173354] opened 2023-02-03 18:25 UTC
Type: <b>Bug</b>

After the last update, suddenly the keybinding of 'toggle terminal' changed to `[CMD + NumPad_Subtract]`.

And whenever I assign it back to `[CMD + "]` it keeps coming the same to `[CMD + NumPad_Subtract]`.

I tried to be sure if there is any problem with double quote but no, I can assign quote character `"` by itself but can't assign with `CMD` as a combination.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id f8262acf-dbbe-43c7-adf4-9c626b6fc565|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-chatgpt|gen|3.4.3
remotehub|Git|0.50.0
go|gol|0.37.1
todo-tree|Gru|0.0.223
react-native-snippet|jun|0.5.6
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2000312134
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.0
azure-repos|ms-|0.26.0
remote-repositories|ms-|0.28.0
vscode-react-native|msj|1.10.0
vscode-versionlens|pfl|1.1.1
material-icon-theme|PKi|4.23.1
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-conventional-commits|viv|1.25.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30657576
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by meganrogge** [comment] 2023-02-03 22:09
You should run `Developer: Toggle Keyboard Shortcuts Troubleshooting` to see what's going on

**Comment by efefurkankarakaya** [comment] 2023-02-05 15:34
> You should run `Developer: Toggle Keyboard Shortcuts Troubleshooting` to see what's going on

When I press `CMD + "` outputs are below:

```
2023-02-05 18:17:14.079 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
2023-02-05 18:17:14.080 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
2023-02-05 18:17:14.080 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-02-05 18:17:14.152 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-02-05 18:17:14.153 [info] [KeybindingService]: | Resolving meta+[IntlBackslash]
2023-02-05 18:17:14.153 [info] [KeybindingService]: \ No keybinding entries.
2023-02-05 18:17:14.153 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: IntlBackslash, keyCode: 222, key: "
2023-02-05 18:17:14.154 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: IntlBackslash, keyCode: 90 (''')
2023-02-05 18:17:14.154 [info] [KeybindingService]: | Resolving meta+[IntlBackslash]
2023-02-05 18:17:14.154 [info] [KeybindingService]: \ No keybinding entries.
2023-02-05 18:17:14.416 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2023-02-05 18:17:14.722 [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
2023-02-05 18:17:21.331 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2023-02-05 18:17:21.361 [info] [KeybindingService]: + Clearing single modifier due to other key up.
2023-02-05 18:17:23.656 [info] [KeybindingService]: + Storing single modifier for possible chord meta.
2023-02-05 18:17:23.962 [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

Animation of the issue here:
![issue](https://user-images.githubusercontent.com/49307777/216828736-29f1de71-9441-4b3f-8ee7-c9a0d3940370.gif)

And for your information, I have Turkish Q Keyboard.

**Comment by alexdima** [comment] 2023-02-05 19:40
Duplicate of #173325

**Closed by alexdima** 2023-02-05 19:40 UTC
Labels: info-needed, new release
