### ISSUE TITLE
some ways to exit keep unsaved state intact, other ways destroy unsaved state

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#157409] opened 2022-08-06 20:34 UTC
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.5-76051705-generic
```

There are some way in which to exit VS Code that will preserve unsaved state so that the next time we start VS Code the unsaved state will still be there.

There are other ways to exit VS Code that do not honor this, and will frustratingly destroy saved state.

Steps to Reproduce:

1. Exit by choosing the "File > Exit" option.
2. Note that this closes all windows, and saves unsaved state to resume working later (it does not save unsaved files, but caches the unsaved state such that the editor returns to the exact same state next time, and the unsaved work can be subsequently saved to the actual file if desired).
3. Try again with unsaved state Linux, then exit by pressing `alt-tab` until the app switcher highlights the VS Code icon, then hit `alt-q` to quit VS Code.
4. Note that this closes all windows, but if any have unsaved work, VS Code will prevent the window closure, and will ask if we wish to save any unsaved files
5. select not to save changes (thinking that unsaved changes will remain for next time, as usual)
6. re-open VS Code to find work obliterated, begin to pull your hair out and start smashing physical objects around the room. :)

This is a UX problem, especially when one mistakenly thinks that `alt-q` will have the same result as `File > Exit` to quit the whole app, including all windows.

**Comment by bpasero** [comment] 2022-08-07 07:13
It sounds like the difference between the two is that `File > Exit` will trigger our flow to preserve all opened windows and state for opening again, but the other flow you mention triggers closing each window one by one, similar as if you could click the close icon of a window one by one.

This is a duplicate of https://github.com/microsoft/vscode/issues/134336

**Closed by bpasero** 2022-08-07 07:13 UTC
