### ISSUE TITLE
Tilde (~) character not available in integrated terminal

### ISSUE THREAD

**Issue by grainiac** [Microsoft/vscode#9193] opened 2016-07-13 09:25 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Open integrated terminal
2. Press alt+n
3. no tilde character is produced in terminal

BUT
if you press alt+n in the normal editor pane the character can be entered.

**Comment by Tyriar** [comment] 2016-07-13 14:34
Duplicate of #9008

**Closed by Tyriar** 2016-07-13 14:34 UTC
Labels: bug, integrated-terminal
