### ISSUE TITLE
Random files being created

### ISSUE THREAD

**Issue by Sunrise-Sea** [microsoft/vscode#145329] opened 2022-03-17 16:39 UTC
679001
Issue Type: <b>Bug</b>

Hi, 
I was coding in my files and suddenly, I saw a file with '[' name and other random files with weird file names being created and Yes, I have checked all the processes through VirusTotal.com using the Process Explorer which comes in the Sysinternals Suite, and no process was flagged, everything was 0 out of around 69 to 71 anti virus solutions, also scanned my device with Windows Defender for any malware, and at the end checked in other directories if any files were created and no, there weren't any and also since I have enabled controlled folder access for all my directories in Windows Defender it would have shown me the modifications done so, I assume that it is VS Code because when I reload with extensions disabled the problem does not occur. Please fix it as soon as possible. 🙏

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (3.55GB free)|
|Process Argv|--crash-reporter-id c8d35d25-523f-464c-9410-04904f41f1e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
battery-indicator|fbo|1.0.0
code-runner|for|0.11.7
gc-excelviewer|Gra|4.2.53
better-cpp-syntax|jef|1.15.13
cpptools|ms-|1.9.4
indent-rainbow|ode|8.2.2
material-icon-theme|PKi|4.14.1
errorlens|use|3.4.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvidc:30447482
dockersurvey3cf:30453610
pynewfile477:30450038

```

</details>

![1stVSCode](https://user-images.githubusercontent.com/100902074/158849968-15fc7f11-bf96-4d0d-adee-5ad6333eb4a5.png)

**Comment by gjsjohnmurray** [comment] 2022-03-17 16:42
Probably a duplicate of #145297

**Closed** 2022-03-17 18:49 UTC
Labels: *duplicate
