### ISSUE TITLE
[debug] can not stop on 'parseInt'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3346] opened 2016-02-23 16:23 UTC
When testing https://github.com/Microsoft/vscode/issues/2832 I tried to set a function breakpoint on 'parseInt', but that doesn't seem to be supported.
It worked for setTimeout and for my own global functions

**Comment by weinand** [comment] 2016-02-24 09:26
duplicate of #3388

**Closed by weinand** 2016-02-24 09:26 UTC
