### ISSUE TITLE
Snippets - more than one snippet breaks tab autocompletion

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#23823] opened 2017-04-02 17:24 UTC
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.10

When I type some snippet keyword and press tab, snippet autocomplete works as expected when there is only one snippet. When there is Code's default snippet + my user defined, tab completion no longer works.

![peek 2017-04-02 19-22](https://cloud.githubusercontent.com/assets/6587821/24589396/e16d2890-17d9-11e7-8e85-6772a1f969a6.gif)

I have the following settings

```
    "editor.quickSuggestions": false,
    "editor.tabCompletion": true,
```

**Comment by jrieken** [comment] 2017-04-03 07:33
Yeah, there is this [`hasSnippets.set(this._currentSnippets.length === 1); //todo@joh make it work with N`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/snippets/electron-browser/tabCompletion.ts#L69)

**Comment by jrieken** [comment] 2017-04-11 13:46
closing as dupe of https://github.com/Microsoft/vscode/issues/22216

**Closed by jrieken** 2017-04-11 13:46 UTC
Labels: bug, snippets
