### ISSUE TITLE
Linux/Fedora24: Upgrade from 1.2.1 to 1.3.1 breaks launcher

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#9332] opened 2016-07-15 11:47 UTC
- VSCode Version: Upgrade to 1.3.1 from 1.2.1
- OS Version: Fedora24

Steps to Reproduce:

1. download 1.3.1 rpm package
2. "sudo dnf install _path_to_rpm_"
3. attempt to start vscode via the launcher

-> "failed to launch child process: /usr/bin/code not found: no such file or directory"

Workaround:

1. download 1.3.1 rpm package
2. "sudo dnf remove code"
3. "sudo dnf install _path_to_rpm_"

**Comment by bgse** [comment] 2016-07-15 11:53
Maybe it has nothing to do with upgrade, and I've just run into this one?

https://github.com/Microsoft/vscode/issues/8942

**Comment by Tyriar** [comment] 2016-07-15 17:24
#8942 should only apply to the deb package. Perhaps related to #7350 but I have tested it a few times :confused:

**Comment by Tyriar** [comment] 2016-09-06 20:31
Duplicate of #11431

**Closed by Tyriar** 2016-09-06 20:31 UTC
Labels: bug, install-update, linux
