### ISSUE TITLE
Unable to auto switch thread focus for multiple threads

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#57253] opened 2018-08-27 08:21 UTC
When debugging multiple threads program, if there are two threads suspending on breakpoint simultaneously , VS Code cannot switch the focus smoothly. 
![threadswitch](https://user-images.githubusercontent.com/14052197/44648588-100aa100-aa14-11e8-9555-fa9b3c3b1e95.gif)

As the screenshot, if i select `Thread-0` to continue, the focus doesn't switch to the suspending `Thread-1`.

This could be a problem when the user application's threads exceeds the `CALL STACK` window, they may miss those suspending threads not in the visible window.

**Comment by isidorn** [comment] 2018-08-27 12:57
@testforstephen I have pushed a potential fix for this. Please try it out in tomorrow's (Tuesday) insider and let me know if the fix works for you.
If the fix does not work, here's a code pointer to put a breakpoint and try to figure out why the other thread is not getting auto focused. [Code pointer](https://github.com/Microsoft/vscode/blob/2412cce16d35e9885d93dc002287c95669f38a59/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L750)

**Comment by testforstephen** [comment] 2018-08-28 01:27
@isidorn thanks for the quick fix, i would love to verify it when the insider is ready. Will update the status later.

**Comment by testforstephen** [comment] 2018-08-28 09:02
Have a try at the fix, look like the thread status is on chaos.
![threadswitch1](https://user-images.githubusercontent.com/14052197/44712666-e620af80-aae3-11e8-9d79-5b34f228e1de.gif)

After several switches, `Thread-1` is still on paused, but the debug bar shows running.

**Comment by isidorn** [comment] 2018-08-28 09:05
@testforstephen thanks for trying it auto.
So it seems like the correct thread gets selected, however the State is wrong. It thinks it is running, while it is actually stopped.
I will reopen this and push another fix today so you can try tomorrow. Thank you

**Comment by testforstephen** [comment] 2018-08-28 09:13
yes, the cursor switch is correct, but the debug status bar is wrong.

**Comment by LazarusX** [comment] 2018-08-28 09:44
We have a similar issue: https://github.com/Microsoft/vscode/issues/55862

**Comment by isidorn** [comment] 2018-08-28 10:11
@LazarusX do you see the same behavior as @testforstephen in the latest vscode-insiders?

**Comment by LazarusX** [comment] 2018-08-29 03:09
In the latest Insider release, the behavior is different. I have posted my update in https://github.com/Microsoft/vscode/issues/55862#issuecomment-416809128.

**Comment by isidorn** [comment] 2018-08-29 15:26
This behavior is not a regression. We have always behaved like that in stable ( I mean the original comment and the @LazarusX issue).
Multi session focusing is usually delicate and I prefer not to do it on the last day before a release -> assigning to September

**Comment by testforstephen** [comment] 2018-09-10 01:44
@isidorn In latest vscode 1.27.1, the debug toolbar buttons are mistakenly disabled, looks like it's a regression bug.  See the new bug https://github.com/Microsoft/vscode/issues/58327

**Comment by testforstephen** [comment] 2018-09-21 01:54
In 2018-09-20T 14:09:20.109Z insider, the thread status chaos issue got resolved. But it still cannot auto switch to the stopping thread.
![threadswitching1](https://user-images.githubusercontent.com/14052197/45855764-3528d000-bd84-11e8-93a8-e376e3514f42.gif)

**Comment by isidorn** [comment] 2018-09-21 08:00
@testforstephen thanks for checking. We can investigate this in the following milestone

**Comment by isidorn** [comment] 2018-09-28 12:12
Reopening because bot accidently closed it.
But just to get clear can you please write some reproducable steps and in words what is unexpected here. Gif is not very descriptive unfortunetly

**Comment by LazarusX** [comment] 2018-09-28 13:09
@isidorn You can find my repro steps in https://github.com/Microsoft/vscode/issues/55862#issue-347849695.

**Comment by isidorn** [comment] 2018-10-03 13:21
@LazarusX thanks for great repro steps.
Next week insiders will have the fix, let me know if it fixes the issue now. Though I verified with your example and it looks good to me.

**Closed by isidorn** 2018-10-03 13:21 UTC
Labels: bug, debug, needs more info
