### ISSUE TITLE
markdown preview does not scroll to link anchor

### ISSUE THREAD

**Issue by joehays** [microsoft/vscode#198028] opened 2023-11-12 06:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- OS: Windows 10.0.22621, WSL 2
- VS Code version: 1.84.2

Steps to Reproduce:

1. create a link using `[tasks](#tasks)` embedded in a paragraph of text somewhere.

2. elsewhere in the document, create a named anchor using,

```
<a name="tasks">
   my tasks
</a>
```

3. now, view the .md in the preview windows. Click on the tasks link. It does not move the preview down to the anchor location in the document.

Logs:

<html>
<body>

CPUs | 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 31.79GB (11.93GB free)
Process Argv | --disable-extensions --crash-reporter-id da9f2962-5f3c-4410-89cd-106297b105c3
Screen Reader | no
VM | 0%

</body>
</html>

Extensions are disabled

vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018:30886114
aa_t_chat:30882232

**Comment by mjbvz** [comment] 2023-11-15 19:59
You should use `id` instead of `name`, which has been deprecated 

Duplicate of https://github.com/microsoft/vscode/issues/139852

**Closed by mjbvz** 2023-11-15 19:59 UTC
