### ISSUE TITLE
Save terminals layout

### ISSUE THREAD

**Issue by byeze** [microsoft/vscode#96733] opened 2020-04-30 20:27 UTC
Hi. I commonly work with 3 open terminals in VSCode, but, when I restart the program, it only opens 1 terminal.
I would like if VS Code could save the number of open terminals, and re open them on the next program startup.

**Comment by yume-chan** [comment] 2020-05-02 14:42
Duplicate of #95984. Please see comments in that one.

**Closed** 2020-05-04 08:53 UTC
Labels: *duplicate
