### ISSUE TITLE
List of available terminals doesn't show up and the default profile not respected locally

### ISSUE THREAD

**Issue by adinriv** [microsoft/vscode#146981] opened 2022-04-07 08:32 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0 (flatpak)
- OS Version: Red Hat Enterprise Linux release 8.5

Steps to Reproduce:

1.  Open vscode and click the drop down menu for the terminals
![no-menu](https://user-images.githubusercontent.com/624792/162154975-1f119d81-5052-4f44-891c-c654b416259e.png)

with current `settings.json` as follows

```json
{
    "workbench.colorTheme": "Monokai",
    "terminal.integrated.fontFamily": "DejaVuSansMono Nerd Font Mono",
    "terminal.integrated.useWslProfiles": false,
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/usr/bin/bash",
            "args": [],
            "icon": "terminal-bash",
        }
    },
    "terminal.integrated.defaultProfile.linux": "bash",
}       
```

A similar behavior was reported for #143307 but dismissed due to VPN.  Note that in my case this is happening locally.  Similarly, flathub/com.visualstudio.code#288 was reported and linked to #143307 that is now closed.

**Comment by meganrogge** [comment] 2022-04-08 05:09
Do they ever show up?

**Comment by adinriv** [comment] 2022-04-11 06:56
No.

**Comment by adinriv** [comment] 2022-04-19 06:23
@meganrogge do you need any extra information or debug that needs to be done?

**Comment by meganrogge** [comment] 2022-04-19 15:06
Yes, could you pls turn on trace logging via `Developer: set log level` and search for any logs that say `profile not validated`

**Comment by adinriv** [comment] 2022-04-20 14:17
I activated the trace.  Where should the logs appear?

**Comment by meganrogge** [comment] 2022-04-20 21:27
open dev tools 

via : toggle developer tools

and select the console tab

**Comment by adinriv** [comment] 2022-04-21 08:00
I don't see any `profile not validated` error.  What pops out is `ERR ENOENT` (see below).
```
TRACE KeybindingService#dispatch Ctrl+Shift+\ workbench.action.terminal.toggleTerminal
log.ts:289 TRACE CommandService#executeCommand workbench.action.terminal.toggleTerminal
log.ts:289 TRACE terminalInstance#ctor (instanceId: 5) 
{}
log.ts:289 TRACE Webgl was loaded
log.ts:313   ERR ENOENT: no such file or directory, open '/etc/shells': Error: ENOENT: no such file or directory, open '/etc/shells'
log.ts:295 DEBUG terminalInstance added capability 1
log.ts:295 DEBUG Terminal process ready (shellProcessId: 273850)
log.ts:295 DEBUG terminalInstance added capability 3
log.ts:313   ERR ENOENT: no such file or directory, open '/etc/shells': Error: ENOENT: no such file or directory, open '/etc/shells'
﻿```
I tried opening a new window and that is the same error that appears, but nothing else. 

Let me know if you need some other test.

**Comment by meganrogge** [comment] 2022-04-21 18:43
Yep that's the issue - we generate that list of profiles for mac/linux by sourcing your shells there. 

Since that file doesn't exist for you, it's not finding any

**Comment by meganrogge** [comment] 2022-04-21 18:43
A solution would be to copy your shells file (wherever it is) to that location

**Comment by meganrogge** [comment] 2022-04-21 23:06
With your shells not in that file, we can't do anything about this, so closing

**Comment by adinriv** [comment] 2022-04-22 07:23
The file exists on the system and I can see it from my terminal. 

```
$ cat /etc/shells
/bin/sh
/bin/bash
/usr/bin/sh
/usr/bin/bash
/usr/bin/tmux
/bin/tmux
/usr/bin/zsh
/bin/zsh
/bin/csh
/bin/tcsh
/usr/bin/csh
/usr/bin/tcsh
/local/bin/tcsh
/local/bin/bash
/local/bin/zsh
/local/gnu/bin/bash
/bin/ksh
/bin/rksh
/usr/bin/ksh
/usr/bin/rksh
```

**Comment by meganrogge** [comment] 2022-04-22 17:36
Then it's a permissions issue. Are you working on a corporate laptop with a firewall or something?

**Comment by adinriv** [comment] 2022-04-22 19:24
It is corporate, but the installation is standard through flatpak.  Is there a way to debug the permissions?

**Comment by meganrogge** [comment] 2022-04-22 21:51
Not that I'm aware of. Was it working for you in version 1.63?

**Comment by jcdickinson** [comment] 2022-04-23 21:19
Things I have tried:

* `touch /etc/shells` from within the VSCode integrated terminal. Works, but several other features stop working. Does not persist across invocations.
* add `/etc` to the whitelist. Does not work.
* add `/etc/shells` to the whitelist. Does not work.

I am on my own machine (Silverblue) with no corporate firewalls or anything.

**Comment by meganrogge** [comment] 2022-04-24 04:53
@jcdickinson do you know the last version that worked for you? That will help me narrow down the cause

**Comment by jcdickinson** [comment] 2022-04-24 23:33
@meganrogge sorry, I don't know which version was working. The fix is simply to log a warning if `/etc/shells` doesn't exist.

**Comment by nikodunk** [comment] 2022-04-24 23:52
@meganrogge 1.63.2 still works smoothly for me on a standard Fedora 36 Workstation install and recognizes my local shells out of the box in the flatpak build. 

Reproducible by downgrading to 1.63.2 which worked smoothly:
`flatpak update --commit=ce7dece61857fe539f7964d5ca72f9645bea914d41b904471d01b58f2907bd2d com.visualstudio.code`

and then updating to the newest version.
`flatpak update` and the integrated shell config will no longer be recognized.

**Comment by sangsatori** [comment] 2022-05-01 18:50
> Things I have tried:
> 
>     * `touch /etc/shells` from within the VSCode integrated terminal. Works, but several other features stop working. Does not persist across invocations.
> 
>     * add `/etc` to the whitelist. Does not work.
> 
>     * add `/etc/shells` to the whitelist. Does not work.
> 
> 
> I am on my own machine (Silverblue) with no corporate firewalls or anything.

I'm having the same issue (Flatpak on Fedora 35 Silverblue, VSCode v1.66.1).

Reading the [Flatpak docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), looks like `/etc` gets mounted under `/var/run/host`.

I quickly checked from the VSCode integrated terminal and `/etc/shells` indeed exists at that path instead.

```sh
$ cat /var/run/host/etc/shells
/bin/sh
/bin/bash
/usr/bin/sh
/usr/bin/bash
```

**Comment by meganrogge** [comment] 2022-05-02 17:13
Thanks for the investigation. We don't support the flatpak distribution. You should report this to them and then maybe they have an environment variable we should use instead.

**Closed** 2022-05-02 17:14 UTC
Labels: bug, *out-of-scope, confirmation-pending, terminal-profiles

**Comment by sangsatori** [comment] 2022-05-02 20:18
> Thanks for the investigation. We don't support the flatpak distribution. You should report this to them and then maybe they have an environment variable we should use instead.

Running within Flatpak, there's `$FLATPAK_ID` environment variable that can be checked against.

```sh
$ echo $FLATPAK_ID
com.visualstudio.code
```

This could then be used to look up `/var/run/host/etc/shells` instead of `/etc/shells` on https://github.com/microsoft/vscode/blob/57479a5f6be520ada8517ecbbca6a982b1f80ff3/src/vs/platform/terminal/node/terminalProfiles.ts#L303

**Comment by jcdickinson** [comment] 2022-05-02 20:47
> This could then be used to look up `/var/run/host/etc/shells` instead of `/etc/shells` on

This inspired me to put together a PR that links `/var/run/host/etc/shells` to `/etc/shells` in `code.sh`, thanks!

**Comment by nikodunk** [comment] 2022-05-05 22:02
Thank you @jcdickinson! You fix works well, and solves the issue for the Flatpak - VSCode works perfectly again as a Flatpak. @meganrogge @Tyriar FYI this was the fix. Thank you for the great software!

**Comment by Tyriar** [comment] 2022-05-05 22:07
@nikodunk nice, great to hear 🙂

**Comment by nikodunk** [comment] 2022-07-07 19:43
If anyone finds this thread searching for a solution to this (and other) issues on the Flatpak build: Just added documentation for the Flatpak build of VSCode at https://github.com/flathub/com.visualstudio.code for the first time. 

Not as clean as your solution working out the box @sangsatori but better than nothing in the meantime :)
