### ISSUE TITLE
Context menu below window control overlay

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#170349] opened 2023-01-01 07:21 UTC
<img width="270" alt="image" src="https://user-images.githubusercontent.com/900690/210163649-ad479efd-707f-474d-b007-a044718b2e82.png">

**Comment by sbatten** [comment] 2023-12-18 23:54
dupe of https://github.com/microsoft/vscode/issues/160518

**Closed by sbatten** 2023-12-18 23:54 UTC
Labels: bug, *duplicate, titlebar, menus
