### ISSUE TITLE
Selected file in file list is shown on the timeline label

### ISSUE THREAD

**Issue by floriancastelain** [microsoft/vscode#95300] opened 2020-04-15 07:03 UTC
- VSCode Version: 1.44.1
- OS Version: Windows_NT x64 10.0.18362

The selected file name in the file list is weirdly displayed on the timeline label. Seems to happen with all files.

![image](https://user-images.githubusercontent.com/10050024/79307848-db54a180-7ef7-11ea-8e7a-23e46d646c26.png)

Steps to Reproduce:
X

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by eamodio** [comment] 2020-04-15 17:03
Duplicate of #94458

**Closed** 2020-04-15 17:04 UTC
Labels: *duplicate, new release, timeline
