### ISSUE TITLE
Slow/laggy when opening large (~200K) files

### ISSUE THREAD

**Issue by brockallen** [Microsoft/vscode#4828] opened 2016-03-31 14:01 UTC
- VSCode Version: 0.10.11
- OS Version: Win 10

Steps to Reproduce:

1. Open folder containing this file: https://github.com/kjur/jsrsasign/blob/master/npm/lib/jsrsasign.js
2. Open file and scroll around a bit. VS Code gets really slow/laggy.

**Comment by alexandrudima** [comment] 2016-03-31 15:18
@brockallen Thanks a lot for filing this! :+1: 

.. Looks like most time is spent in `decodeTextMateToken`:

![image](https://cloud.githubusercontent.com/assets/5047891/14180718/99a3d0e0-f764-11e5-9a83-df750fac48a3.png)

**Comment by alexandrudima** [comment] 2016-04-08 09:53
This is now fixed on our side by optimizing the `decodeTextMateToken` function, but we still need to investigate what makes the grammar go crazy and generate 20+ embedded scopes in this case

**Comment by digeff** [comment] 2016-04-25 20:11
Create a file full of (as in half a millon lines):
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

VS Code starts to work slowly (Version 1.0.0 in Windows).
Also if you try to do Ctrl + A to select all the code it crashes.
There are many ways to break VS Code or make it crash when using very large files...

**Comment by sergeykhrykov** [comment] 2016-05-14 23:28
- VSCode Version: 1.1.0
- OS Version: Win 10 x64

Trying to open a large JS file (~85K SLOC) makes window crash. 

Steps to reproduce:
1. Open a large JS file (e.g., http://developer-autodesk.github.io/viewer3d/2.2/viewer3D.js)
2. Wait a few seconds to see editor crash.

**Comment by alexandrudima** [comment] 2016-05-26 11:00
@digeff I have just pushed a fix in ca2ca08c63c88f7c0bc2735a37a97ff3b8f600fc that fixes that the `<textarea>` sync we had for accessibility purposes (screen readers) was unbounded and we still have some issues with memory consumption when opening a file (the file gets allocated minimum 2 times), but it gets GC'd after a while (so for your testcase I see the renderer process at 200MB) and with the fix I can select all and have no issue:

![lnaojqzf2f](https://cloud.githubusercontent.com/assets/5047891/15572576/b700ecc8-2341-11e6-8e82-028278983ffa.gif)

**Comment by alexandrudima** [comment] 2016-05-26 11:03
@sergeykhrykov Thank you for the repro, I can reproduce the crash immediately. I have opened #6916 to better track it. On a first look, it seems it goes OOM.

**Comment by alexandrudima** [comment] 2016-05-26 11:53
@aeschli Where do we get the JavaScript grammar from? https://github.com/Microsoft/TypeScript-Sublime-Plugin ?

**Comment by aeschli** [comment] 2016-05-26 13:11
It's the TypeScriptReact grammar from https://github.com/Microsoft/TypeScript-TmLanguage

**Comment by alexandrudima** [comment] 2016-05-26 14:04
The slowness on our side is dealt with for this example, let's use this to track Microsoft/TypeScript-TmLanguage#174

**Comment by alexandrudima** [comment] 2016-07-05 07:14
Since all issues on our side are fixed (no more crashes for these test cases), I would prefer to close this issue. The JavaScript grammar is still broken, but that is being tracked in Microsoft/TypeScript-TmLanguage#174

**Closed by alexandrudima** 2016-07-05 07:14 UTC
Labels: bug, editor, freeze-slow-crash, upstream
