### ISSUE TITLE
Wut a problem when i input mui. on javascript Mode.

### ISSUE THREAD

**Issue by ignatiusyar** [Microsoft/vscode#63739] opened 2018-11-25 11:58 UTC
Issue Type: <b>Bug</b>

when I use mui. in javascript mode than autocomplete make mui. to MutationEvent. its difficult for me to use mui.confim().
plz fix that if that was a problem.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by ignatiusyar** [comment] 2018-11-25 13:51
> You can try this in Settings
> 
> ```json
> "editor.suggestOnTriggerCharacters": false,
> ```
thank you ...

**Comment by usernamehw** [comment] 2018-11-25 13:57
/duplicate of https://stackoverflow.com/questions/48609354/visual-studio-code-autocomplete-when-i-press-key-any-way-to-disable/48609930

**Closed** 2018-11-25 13:57 UTC
Labels: *duplicate, javascript
