### ISSUE TITLE
JS parser breaks with certain syntax since 1.42

### ISSUE THREAD

**Issue by tomato111** [microsoft/vscode#90760] opened 2020-02-15 15:32 UTC
Issue Type: <b>Bug</b>

![1 42](https://user-images.githubusercontent.com/1456245/74590447-c5d70e80-5051-11ea-933d-9ed3c7799d73.png)

sample

----

if (/123(?:foo|bar)?baz/ig.test("123baz")) {}
if (a) {}
if (!/123(?:foo|bar)?baz/ig.test("123baz")) {}
if (a) {}

----

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment] 2020-02-18 18:50
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-02-18 18:50 UTC
