### ISSUE TITLE
Search, files to include, requires wildcard and rejects full files paths

### ISSUE THREAD

**Issue by thekingofspain** [microsoft/vscode#182808] opened 2023-05-17 20:13 UTC
Type: <b>Bug</b>

Edit menu -> Find in Files
Enter "Search" term
Enter "files to include" as full file path:  C:\Users\\_x_\\.rest-client\responses\body\\_filename.json_
Bug:  No search results

Change "files to include" as full file path with wild card:  C:\Users\\_x_\\.rest-client\responses\body\\_filename.jso_<strong>*</strong>

No Bug:  Finds search results in file C:\Users\\_x_\\.rest-client\responses\body\\_filename.json_

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (13.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.2
vscode-sql-beautify|cla|0.3.19
vbscript|Dar|1.0.4
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.12.0
vs-code-xml-format|fab|0.1.5
rest-client|hum|0.25.1
svg|joc|1.5.2
vscode-position|jtr|1.1.2
vscode-format-context-menu|lac|1.0.4
eml|lei|0.4.0
rainbow-csv|mec|3.7.0
render-crlf|med|1.6.1
vscode-oracle-format|mp|0.1.5
csharp|ms-|1.25.7
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.18.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.21.0
remote-wsl|ms-|0.78.5
hexeditor|ms-|1.9.11
powershell|ms-|2023.5.0
vs-keybindings|ms-|0.2.1
sqltools|mtx|0.27.1
oracle-plsql|myc|1.0.3
indent-rainbow|ode|8.3.1
vscode-powerquery|Pow|0.1.52
code-spell-checker|str|2.20.4
tabnine-vscode|Tab|3.6.46
email-viewer|Tom|5.0.0
plsql-language|xyz|1.8.2
cursorCharCode|zei|0.2.3
html-css-class-completion|Zig|1.20.0

</details>

**Comment by andreamah** [comment] 2023-05-17 21:13
/duplicate of https://github.com/microsoft/vscode/issues/48958

**Closed by andreamah** 2023-05-17 21:13 UTC
