### ISSUE TITLE
Status bar hover flickers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#140851] opened 2022-01-17 11:30 UTC
* latest insiders, open TS file
* pin/unpin language status bar item from the hover
* 🧀 the hover flickers

https://user-images.githubusercontent.com/1794099/149761977-23718bf3-1913-4073-8371-bd5e2341e7e4.mov

/cc @daviddossett

**Comment by jrieken** [comment] 2022-01-17 11:31
Also note how the anchor-arrow isn't correct when pinning/unpinng. Tho, I can file a separate issue for that

**Comment by bhavyaus** [comment] 2022-12-13 16:46
Closing as duplicate of https://github.com/microsoft/vscode/issues/127436

**Closed by bhavyaus** 2022-12-13 16:46 UTC
Labels: feature-request, workbench-hover
