### ISSUE TITLE
Code completion triggered by setting the caret with a mouse button click

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21201] opened 2017-02-22 19:31 UTC
1) Open `vscode.d.ts`
2) set caret with mouse button click as shown in screen recording
-> code completion triggered but shouldn't

![yt4qbwfcmd](https://cloud.githubusercontent.com/assets/4674940/23228678/411a4842-f8f2-11e6-9a65-c12053b412cf.gif)

**Comment by mjbvz** [comment] 2017-02-22 21:42
Duplicate of #21056. Should be fixed in master

**Closed by mjbvz** 2017-02-22 21:42 UTC
Labels: bug, duplicate, javascript
