### ISSUE TITLE
从侧边栏删除文件夹

### ISSUE THREAD

**Issue by 542735653** [Microsoft/vscode#33807] opened 2017-09-04 16:26 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.打开一个文件夹， 在侧边栏右键从侧边栏删除
2.然后再去打开文件夹， 就再也打不开了。

Reproduces without extensions: Yes/No

**Comment by 542735653** [comment] 2017-09-04 16:28
打开相同文件夹

**Comment by yume-chan** [comment] 2017-09-05 01:24
你不是一个人

Duplicate of #33717, #32962

`Remove from Side Bar` means "remove this panel from the view", so it will hide the file list, not "close your folder".

When you open the folder again, it's actually opened, but you cannot see the file list.

To get it back, open your folder, right-click on the title of the view (Explorer for this case), and check `Folders`.

**Comment by FrankKai** [comment] 2017-09-05 01:51
1.`ctrl+shift+e`打开资源管理器
2.**右键**上方的很窄的`资源管理器：打开...`
3.选择文件夹即可

**Comment by jrieken** [comment] 2017-09-05 06:52
Thanks @yume-chan. Closing as duplicate

**Closed by jrieken** 2017-09-05 06:52 UTC
Labels: extensions, new release
