### ISSUE TITLE
Copy / Paste between open files does not work as expected

### ISSUE THREAD

**Issue by gamelover42** [Microsoft/vscode#5105] opened 2016-04-08 20:25 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 SP1 64-bit (build 7601)

Steps to Reproduce:

1. Open 3 files by double clicking on them. (file1, file2 and file3 in this example).
2. Switch to "file1"
3. Highlight a block of text in "file1' then use CTRL+C to copy it
4. Paste the text into "file3" using CTRL+V
5. Switch to "file2"
6. Highlight a block of text in "file2' then use CTRL+C to copy it
7. Paste the text into "file3" using CTRL+V
8. Switch back to "file1"
9. Note that the text block in "file1" is still highlighted. Use CTRL+C to copy it
10. Paste the text into "file3" using CTRL+V
11. Note that the text from "file2" is pasted not the text from "file1" as expected.

**Comment by alexandrudima** [comment] 2016-04-28 10:14
@gamelover42 I could not reproduce.

Maybe you are not focusing in "file1" in step 8? [No blinking cursor?]

fyi @bpasero @bgashler1 This might be caused by our poor focus affordance on editors.

![5105](https://cloud.githubusercontent.com/assets/5047891/14882759/9fb16718-0d3a-11e6-87ed-599bee4ceb84.gif)

**Comment by bgashler1** [comment] 2016-04-28 22:13
Thanks @alexandrudima for the heads up.

**Comment by gamelover42** [comment] 2016-04-29 16:40
In step 8 when I click on the file in the explorer pane it should give that file focus. I suspect that is the root of the problem because if, after step 8, I click in the gutter (next to the line numbers) then the problem is resolved.

**Comment by bgashler1** [comment] 2016-04-29 19:47
@alexandrudima I was able to reproduce when I clicked on files in the explorer without clicking on the editor.  Is there a reason why we're not focusing on the editor the moment a user clicks the file in the Explorer?

Now that we are moving towards a unified workflow with tabs or no tabs, it probably makes sense to move the focus to the editor right away (just as would happen if you click on a tab).  Both Atom and Sublime do this also.  Let me know what you think.

**Comment by alexandrudima** [comment] 2016-08-09 07:24
@bpasero Do you have the answer for @bgashler1 

> Is there a reason why we're not focusing on the editor the moment a user clicks the file in the Explorer?

**Comment by bpasero** [comment] 2016-08-09 07:56
Sure there is, if we would move focus away from any tree on click how would you be able to use the keyboard to interact with the tree?

**Comment by alexandrudima** [comment] 2016-10-27 20:35
Bringing focus to the editor on explorer click is not my decision to make.

**Comment by bgashler1** [comment] 2016-10-27 23:27
Since editors that are not focused don't have a caret, I propose we close this issue.  I can understand the keyboard reason that @bpasero suggested above for not focusing the editor by default.

For reference, this is what our competitors do:

**Sublime** moves focus automatically to editor on click of a file.  To get keyboard focus on the tree, you click again on the file.

**Atom** does what we do.

**Closed** 2016-10-28 05:27 UTC
