### ISSUE TITLE
Allow dynamic token types and modifiers

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#86280] opened 2019-12-04 16:21 UTC
Testing #85972

It would be good to allow generating dynamic token types and modifiers and have them match if they are styled.

**Comment by aeschli** [comment] 2019-12-06 14:01
With the current API all token types and modifiers a provider can return are given by the legend which is passed in when registering the provider.

I'll make the change that accepts all ids listed in the legend

Duplicate of #86314

**Closed by aeschli** 2019-12-06 14:01 UTC
