### ISSUE TITLE
WSL control git can't show button add remove

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/vscode#79298] opened 2019-08-16 10:09 UTC
I am coding in WSL, I see that control git can't show button add remove

**Comment by IllusionMH** [comment] 2019-08-16 10:19
Looks like duplicate of https://github.com/microsoft/vscode-remote-release/issues/908 which now is tracked in https://github.com/microsoft/vscode-remote-release/issues/687.

Could you confirm that you have this problem?

**Closed** 2019-08-16 10:48 UTC
Labels: *duplicate
