### ISSUE TITLE
Ability to drag-n-drop files/folders from Finder/Explorer to a CustomTreeView

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#65303] opened 2018-12-18 15:18 UTC
An user from my [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension asked for a feature: To be able to _drag and drop_ folders from Finder/Explorer to my custom TreeView. Doing so, the folder would be added to the custom TreeView as a new **Project**.

I didn't find any API to handle this event, so I suppose its not supported yet. The only thing related to _drag and drop_ in TreeViews that I found was [this other issue](https://github.com/Microsoft/vscode/issues/50363) but it refers to _move_ views to Activity Bar.

Thank you

**Comment by sandy081** [comment] 2018-12-18 17:16
Duplicate of 32592

**Closed by sandy081** 2018-12-18 17:16 UTC
Labels: explorer-custom
