### ISSUE TITLE
Unable to edit

### ISSUE THREAD

**Issue by Ajith-Kumar-G** [microsoft/vscode#152864] opened 2022-06-22 12:44 UTC
Issue Type: <b>Bug</b>

It automatically removes/edits in css file, disabled all extensions still it's occuring, I wish I could record this

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.68GB free)|
|Process Argv|--crash-reporter-id 3fd2f543-1526-4425-9a74-c96bed2ca7fc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549
841h4636:30513947

```

</details>

**Comment by Ajith-Kumar-G** [comment] 2022-06-22 12:46
Any idea how can I share the recording here?

**Comment by IllusionMH** [comment] 2022-06-22 14:27
Pasting/dragging file to comment should upload it to GH and provide preview or link

**Comment by aeschli** [comment] 2022-06-23 13:16
I need detailed steps to understand and reproduce the problem...

**Comment by aeschli** [comment] 2022-06-24 06:39
Is maybe 'format on save' enabled?

**Comment by Ajith-Kumar-G** [comment] 2022-06-26 06:26
yeah, is it the cause, like how does that affect it?

**Comment by aeschli** [comment] 2022-06-27 09:47
I can tell from your screenshot that you have auto save enabled.. (`files.autoSave`)

**Comment by aeschli** [comment] 2022-06-27 09:49
Closing the issue as 'format on save' is the reason for the changes and does it's job as expected.

**Closed by aeschli** 2022-06-27 09:49 UTC
Labels: needs more info
