### ISSUE TITLE
Annoying alert about eslint extension pops up for every repo/project I open. This behavior seems to have changed in the latest release.

### ISSUE THREAD

**Issue by tgreen7** [microsoft/vscode#102836] opened 2020-07-17 22:32 UTC
- VSCode Version: 1.47.2
- OS Version: macos 10.14.6 

Steps to Reproduce:

1. open a project which has eslint installed

<img width="513" alt="Screen Shot 2020-07-17 at 3 29 11 PM" src="https://user-images.githubusercontent.com/10415101/87835663-97e53880-c842-11ea-8467-c24639f9753b.png">

**Comment by IllusionMH** [comment] 2020-07-17 23:01
This message comes from ESLint extension.

/duplicate of https://github.com/microsoft/vscode-eslint/issues/1012

**Closed** 2020-07-17 23:02 UTC
Labels: *duplicate, new release
