### ISSUE TITLE
Missing warning about non-existent workspace folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46832] opened 2018-03-28 10:26 UTC
seen in #44809

* open a workspace
* open its config file
* add a path doesn't exist
* 🐛 no exclamation mark in shown in the explorer, after a reload a exclamation mark is shown

**Comment by isidorn** [comment] 2018-03-28 15:56
Sounds like a duplicate of https://github.com/Microsoft/vscode/issues/46014#issuecomment-376896014
Anyways will fix this as part of that fix either way

**Closed by isidorn** 2018-03-28 15:56 UTC
