### ISSUE TITLE
Zen mode: Centered Editor Layout

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#15684] opened 2016-11-18 01:36 UTC
With the recent addition of zen mode, it may be worth considering adding a centered editor layout option:

![screen shot 2016-11-17 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/12821956/20414983/3ac9d86c-acea-11e6-9732-0df85effdc66.png)

This is something that the [Typewriter atom extension](https://atom.io/packages/typewriter) adds, and I see it being particularly useful in zen mode and when writing text documents, such as markdown. A centered layout would apply both a softwrap and align the wrapped editor content to the center of the current editor pane.

![screen shot 2016-11-17 at 5 20 45 pm 2](https://cloud.githubusercontent.com/assets/12821956/20414982/3ab2d6a8-acea-11e6-8f1f-51de5979e4c2.png)

The major downside is that this would add an ui configuration that we would have to test and support. The centered editor layout also doesn't fit well with all VSCode ui paradigms

**Comment by Zyst** [comment] 2016-12-15 00:04
For now is there any extension doing something similar to this?

**Comment by mjbvz** [comment] 2016-12-15 01:11
@Zyst No, this is not something that an extension would be able to control. [VSCode isolates extensions from the UI implementation, which has a number of benefits](https://code.visualstudio.com/docs/extensions/our-approach), but it also means that extensions cannot customize the VSCode UI like this.

**Comment by atombender** [comment] 2016-12-15 03:58
I think the most intuitive solution would be to let the user specify a desired width, in characters. So if I set 100 (that's how long my codes lines are before I wrap them) as my Zen width, it will adjust the padding so that a 100-character line effectively becomes centered at all times.

**Comment by coreh** [comment] 2016-12-16 16:58
An extension could at least add several extra gutters to fake this, no?

**Comment by phest** [comment] 2017-03-02 01:54
Would love to have this. Ideally top and bottom margins should also be supported. In my opinion WriteRoom has one of the most well designed zen modes, thanks in part to the top and bottom margins. The margins only appear when scrolling to the top or the bottom of the page. 

Ideally it should look something like this (mockup based on @mjbvz's):

![zen mode mockup](https://cloud.githubusercontent.com/assets/8858/23489483/89c2f94e-fea7-11e6-8d54-f334c58d34d4.png)

(Notice the top and bottom stripped areas in the scroll bar area.)

**Comment by filipesilva** [comment] 2017-03-23 10:45
I would also like this. Going into Zen mode on a ultrawide results in a lot of wasted space with an editor all the way to the left.

**Comment by michaelswe** [comment] 2017-03-27 08:40
This would be a very welcome feature. Working i zen-mode on a 27" monitor requires me to physically move to the left on my desk so I can look straight forward on the code. I'd rather stay centered in front of the screen with the code centered in front of me.

**Comment by filipesilva** [comment] 2017-03-29 11:32
As a comparison, this is how VSCode's Zen mode looks on 3440x1440 resolution (ultrawide):

![image](https://cloud.githubusercontent.com/assets/4172079/24452508/7f2251a8-147b-11e7-9a65-450a38a604a8.png)


By comparison, this is how the same file looks on Webstorm's distraction free fullscreen on 2560x1080
resolution (also ultrawide, but smaller):

![image](https://cloud.githubusercontent.com/assets/4172079/24452522/95614d16-147b-11e7-8574-bd462d22a5c7.png)

**Comment by datendenker** [comment] 2017-03-31 09:33
I would also like to see this feature.

**Comment by marcoT89** [comment] 2017-04-01 13:27
Oh yeah plz!! :+1:

**Comment by Grogs** [comment] 2017-05-02 17:32
+1, this prevents Zen Mode from being as good as IntelliJ's "distraction free" mode for me.

**Comment by prokher** [comment] 2017-05-11 15:43
+1, waiting for this feature since the day one...

**Comment by cmer** [comment] 2017-05-18 00:21
+1

**Comment by bradharms** [comment] 2017-05-20 21:34
+1

**Comment by MakhBeth** [comment] 2017-05-24 13:31
+1

**Comment by mariotsi** [comment] 2017-05-24 13:31
+1

**Comment by prichodko** [comment] 2017-05-24 16:10
+1

**Comment by bjrnt** [comment] 2017-05-26 02:02
+1

**Comment by klaytonfaria** [comment] 2017-05-29 17:55
+1

**Comment by jens1o** [comment] 2017-05-29 18:01
Guys, let me say: There is something called GitHub reactions, which avoids such useless comments and won't get maintainer mad.

You do it like this:
1. Go to the top
2. Click on that button: 
![image](https://cloud.githubusercontent.com/assets/11234139/26558486/72b95340-44a9-11e7-8ce2-9496cb9bcb50.png)
3. Select an reaction(you can also use the heart emoji): ![image](https://cloud.githubusercontent.com/assets/11234139/26558475/58775aae-44a9-11e7-8200-411aafad1784.png)
4. Be proud of yourself

Thanks in advance.

**Comment by filipesilva** [comment] 2017-05-29 20:17
It also helps maintainers gauge how much interest there is from looking at the first post only. It's much better overall.

**Comment by phest** [comment] 2017-05-29 22:59
@jens1o they're not clueless. They're probably eager to get a status update, it's been a while. I'd also love to know if there are any plans to implement this.

**Comment by jens1o** [comment] 2017-05-30 03:59
There is a button on a site: 
![image](https://cloud.githubusercontent.com/assets/11234139/26567630/0c0df82c-44fd-11e7-9971-98327bc03b7e.png)

Actually, I used the wrong wording, I was a little bit upset, sorry...

**Comment by asg-mojtaba** [comment] 2017-06-25 11:28
There is a workaround that i am using until issue fixed, you can create empty tab & split editor vertically. adjust split area until give semi-center-aligned editor : 

![image](https://user-images.githubusercontent.com/8407187/27515703-16d2269e-59bf-11e7-8f98-c1e406ad98e9.png)

**Comment by exallium** [comment] 2017-08-28 18:33
This would be very helpful even outsize of zen mode.

**Comment by lomholdt** [comment] 2017-09-12 09:02
Still no centering? I'm running on a ultrawide screen in 3440x1440 resolution. Centering the code would be über awesome!

**Comment by btstream** [comment] 2017-10-11 01:42
It will be a great feature.

**Comment by thundernixon** [comment] 2017-10-14 08:53
@asgmojtaba great workaround! Wow, yeah I really wish there were a hotkey I could hit to do this in a less-hacky way, but this works until then.

**Comment by anhdat** [comment] 2017-11-10 01:49
![image](https://user-images.githubusercontent.com/2699721/32638864-c7c72cba-c5f3-11e7-975a-a9be225eb065.png)
here's another workaround by using search panel, when nothing enter the search box, this panel is an empty one, suitable for our need, and it has a great shortcut combo:
- Ctrl/Cmd + Shift + F to open panel
- Ctrl + 1 to refocus on editor

**Comment by mathsalmi** [comment] 2017-12-05 13:14
I mean really?! This issue's been open for a whole year and nothing yet? 😢

**Comment by jens1o** [comment] 2017-12-05 16:03
@mathsalmi You're free to do a pr :)

**Comment by SrTobi** [comment] 2017-12-23 15:47
Hi, I added a pr for this. Here is a preview:

![preview](https://github.com/SrTobi-Forks/vscode/blob/SrTobi/center-zen-preview/resources/center-zen-preview.gif?raw=true)

**Comment by mathsalmi** [comment] 2017-12-23 16:30
@SrTobi great work!

… and sorry for being an asshole before. I was in a really bad day.

**Comment by MikeDevice** [comment] 2017-12-25 06:57
@SrTobi does it work in zen mode only?

**Comment by dtgriscom** [comment] 2017-12-26 19:06
@usernamehw referenced this from my suggestion at #40841 . Is there a reason why this proposal is limited to Zen mode? And, it isn't completely clear from @SrTobi's PR preview; are the given sizes relative to the screen size, so that having multiple edit groups don't end up with extra margins for each group (wasting screen space)?

**Comment by SrTobi** [comment] 2017-12-27 10:57
@dtgriscom there is only one reason it is limited to zen mode: I only need it in zen mode 😄. That, though, is of course a very bad reason and it would be the mattar of removing one line to make it work in normal mode as well.

I tried to show it in the GIF and am sorry that it doesn't become quite clear, the centered mode is only activated if only one editor group is used (the moment a second one is activated the centered mode is disabled) and it is limited to text editors only, so the welcome screen or the settings screen does not become centered (though I tested it with a diff-screen a moment ago and that is centered as well. That shouldn't be the case). Here are the relevant code lines:

https://github.com/Microsoft/vscode/pull/40757/files#diff-a01e5a175d29ffe97b726ad068c29e9bR2055
```````typescript
// When in zen mode, if there is only one silo open and it shows an editor,
// center the editor
const centerEditor = this.partService.isInZenMode() &&
	editor instanceof BaseTextEditor &&
	this.configurationService.getValue<boolean>('zenMode.centerEditor') &&
	this.visibleSilos === 1;
```````
Currently the centered mode is activated based on these 4 conditions. And when it is activated, it will enforce the sizes that are given in the settings respecting the available space. I also thought about adding a maxWidth option but I wasn't sure which use cases to consider (the current PR is mostly aimed at using the centered mode in zen mode **and** fullscreen).

We would now need to decide which behavior we want in which situation. Maybe we can gather some use cases?

Oftopic @dtgriscom:  I have my wide screen monitor for 2.5 years 👍

**Comment by dtgriscom** [comment] 2017-12-27 13:01
@SrTobi Very cool. To perhaps make this more broadly useful, I have a few suggestions:

- Make it available as a general feature, rather than Zen-only (as we discussed, although this could instead be a setting)
- Instead of specifying left and right margins in percentages, specify width in text columns, which is how existing settings seem to work (it took me a while to understand your percentages)
- To specify positioning of the narrowed editor, have an "align" property, which defaults to "center" but can also be "left" and "right"

Perhaps the settings could be as follows (with a few extra features thrown in):

```
// Specifies parameters limiting editor width
"editor.limitWidth": {
    // Maximum number of columns (0 is default, and means "no limit")
    "columns": 120,
    // Alignment of editor(s) in available space (can be "left", "center" or "right")
    "align": "center",
    // What modes is visible in. Can be single string or array of strings. Values are
    // each possible mode ("zen", "fullscreen", "non-zen"?)
    "active": "zen",
    // Maximum number of open editor groups for this to take effect
    "maxGroups": 1
}
```

This would meet my needs; would it meet yours (and the others who have posted to this thread)? If so, then I'll suggest that it would be more broadly useful than either of the two original requests.


... thoughts? "Love it"? "Take a flying leap"?

**Comment by SrTobi** [comment] 2017-12-27 15:31
Yeah columns is a good idea. Also
- add a boolean option named `rightflow` or `righttail` or `overflow` or something like that which controls if the most right editor should fill the remaining space on the right side.
- currently the editor is centered into the available space which means the left menu pane influences the position of the editor... I think it should be centered in the center of the window. That's no problem in zen mode where the menu pane is hidden most of the time but it would matter in normal mode.

**Comment by dtgriscom** [comment] 2017-12-27 17:40
@SrTobi I'd keep this as simple as possible, and since I don't know VSC internals, and don't really have the time anyway, I'd shoot for whatever would be easiest for you to implement, giving some thought to possible future enhancement. With that in mind:

- Only put the "columns" in if it's easy (e.g. if you can do it without getting complicated about how "remaining space" is handled). In fact, although I'm the one who proposed it, I'm worried that it would open a can of worms (e.g. what if the user manually drags an editor border?).

- I agree that having the nicely centered editor jerk around when you show/hide the sidebar could be annoying, but that's the default behavior that everyone deals with today, and thus it's expected, so I'll suggest fixing it shouldn't be a priority.

- For now, I'd have this be always active (in zen and other modes); once it's done, someone can add in the ability to enable/disable it in various modes if they like.

The other concern is that the more complex this proposal is, the less likely it will be accepted as a PR. A big concern would be lots of special cases, hence my suggestion to skip the "columns" feature for now. Once (if) the primary feature is accepted, then enhancements could be proposed.

**Comment by SrTobi** [comment] 2017-12-27 17:50
Yeah I see the same problem with the columns and the window centering. Haven't looked if it is easy or not (maybe there are already functions to calculate it) and I won't work on any features before someone official has approved of the technical way the centering is currently implemented. I don't want to write it twice :D

**Comment by dtgriscom** [comment] 2017-12-27 20:17
Well, my original feature request [just got closed](https://github.com/Microsoft/vscode/issues/40841). So, help me, Obi @SrTobi ; you're my only hope...

**Comment by rchrdnsh** [comment] 2017-12-29 06:58
wait...this doesn't seem to work yet...is it coming soon???

**Comment by mikerockett** [comment] 2018-01-04 14:33
This is literally the only thing I need for VSC to be my new Sublime. +9999 for @dtgriscom’s suggestion there. `active` could be `zen`, `fullscreen`, and `always`.

**Comment by michaeljcalkins** [comment] 2018-01-11 00:08
I believe you'd just have to hook into whatever calculates the width for:

- .editor-container
- .monaco-editor
- .overflow-guard

<img width="2304" alt="screen shot 2018-01-10 at 3 58 56 pm" src="https://user-images.githubusercontent.com/8272012/34801983-2658e604-f620-11e7-900e-8cb5f35b16ab.png">

I wrote the `draw-centered` plugin for Atom https://atom.io/packages/draw-centered.  Might be able to get a PR in for VSC to add an `editor.drawCentered: (true|false)` option.

**Comment by SrTobi** [comment] 2018-02-04 21:22
Ok, I changed the PR and streamlined the settings a lot (sorry, I didn't feel like making a gif video again, but it essentially looks the same as the gif above... only the settings have changed completely).

The Center Mode is now independent from the zen mode.
It can be activated automatically or manually by the "Toggle Center Mode" action.
If active, it will set the width of the active silo to `centerMode.size` and center it.

The settings are now as follows:

- `centerMode.autoActivate` has the options `always`,  `zen`, `fullscreen` and `never`. It controls in which context the center mode should be activated automatically.
- `centerMode.size` controls the size of the centered widget.
- `centerMode.adoptRight' -> Normally, on the right side of the centered widget would be free space. With this option the silo can be expanded all the way to the right border (is on by default)
- `centerMode.onlyEditors` -> I think most people would use the centered mode only for the text editor... it doesn't make much sense - in my opinion - to use it for a diff  widget or a settings page or welcome page. But if you want that, you can set `onlyEditors` to `false`.

**Comment by jeffochoa** [comment] 2018-02-14 12:06
Is this going to be merged anytime soon? Looking forward to it.

**Comment by jens1o** [comment] 2018-02-14 12:43
@jeffochoa As you can see, it is scheduled for the February release.

**Comment by phest** [comment] 2018-02-14 18:59
@jens1o @jeffochoa Not quite scheduled, it's set as a stretch goal. Hoping it makes the cut.

**Comment by bpasero** [comment] 2018-02-21 06:37
@isidorn I merged the PR, feel free to do follow up work as you see fit.

**Comment by MikeDevice** [comment] 2018-02-21 06:55
Wow, great! So, is it going to be in the next release?

**Comment by isidorn** [comment] 2018-02-21 08:40
@bpasero thanks, taking over from now.

**Comment by SrTobi** [comment] 2018-02-21 12:04
@isidorn the border looks great

I also opened a PR (#44116) for centering the layout when entering the zen mode.

**Comment by isidorn** [comment] 2018-02-21 14:18
Fixed by @SrTobi in https://github.com/Microsoft/vscode/pull/40757

**Closed by isidorn** 2018-02-21 14:18 UTC
Labels: feature-request, ux, workbench-layout

**Comment by robsonsobral** [comment] 2018-03-08 15:00
Is it possible to enable the centered layout for an specific file? Markdown, on my case.

Thanks.

**Comment by SrTobi** [comment] 2018-03-08 15:08
@robsonsobral no, not at the moment. You have to either activate zen-mode (where the center layout is automatically activated) or use the "Toggle centered layout" action. You may assign a key shortcut to that action though

**Comment by pioneerskies** [comment] 2018-03-08 15:41
1.21 on mac does absolutely nothing when activating this **awesome** feature from command palette nor from the *View* menu. No output in console, no nothing. Just me?

**Comment by pioneerskies** [comment] 2018-03-08 15:47
Wiped config and reimported...all ok. Just an x-file.

**Comment by michaeljcalkins** [comment] 2018-03-08 17:09
@pioneerskies What do you mean wiped config and reimported?  Nothing happens for me either when running the command.

**Comment by pioneerskies** [comment] 2018-03-08 17:28
@michaelchiche I've reproduced the problem in a more scientific way: `CMD+option+0` indirectly enables/disables the centred mode.

**Comment by OutThisLife** [comment] 2018-03-08 19:18
Not sure where to put this but it seems like the right place.

Is there a way to resize the editor viewport (like how centered is now) but rather than centering, just let us resize it as we want?

So we could have the editor 50% of the entire window on the left side, rather than straight center.

**Comment by robsonsobral** [comment] 2018-03-08 20:11
Thanks, @SrTobi . So sad...

**Comment by 3ximus** [comment] 2018-03-08 20:52
@OutThisLife You mean how they show in the demo? https://code.visualstudio.com/updates/v1_21#_centered-editor-layout
You can use the `ALT` key while dragging to move the borders separately

**Comment by pioneerskies** [comment] 2018-03-08 21:08
@outthislife that is not working for me FYI 😢

**Comment by SrTobi** [comment] 2018-03-08 22:20
@OutThisLife that's possible. you can press and hold the alt key. That decouples the sashes and you can move them freely. Then you can move the left border all to the left and the right border to the middle or something. Currently it's only possible for the horizontal direction. We thought about the vertical direction but put that back for now. But I don't even see a usecase for that

**Comment by OutThisLife** [comment] 2018-03-08 22:49
@3ximus @SrTobi 

Thanks, perfect :)

**Comment by nohwnd** [comment] 2018-03-09 09:01
@SrTobi Is there a way to reset the borders back to default? I've moved them (by using the Alt key and dragging as you described above), but now I'd like to make them perfectly centered again.

**Comment by isidorn** [comment] 2018-03-09 09:03
@nohwnd double click on sash resets them

**Comment by addertheblack** [comment] 2018-03-15 18:08
I find myself using zen mode to see more of the code cut off horizontally. Is there any reason why someone would want to go into Zen Mode when they have a horizontal scrollbar and not want to expand the viewing area until at least they don't have to scroll horizontally?

Secondly, there's a "zenMode.fullScreen": false! That's awesome!

**Comment by Vxider** [comment] 2018-03-16 02:22
Is there anyway to hide centered layout sash?

**Comment by SrTobi** [comment] 2018-03-16 10:52
@Vxider no, you have to stick with them or open a new issue and request this feature

**Comment by davidmrnustik** [comment] 2018-03-16 11:58
When an user has `View: Toggle Center Layout` enabled, moving cursor over tabs over centered layout border/line, an app provides you with a resize cursor for resizing centered layout instead of let you click the tab.
