### ISSUE TITLE
vscode.dev fails to search on files with long filename and branch name

### ISSUE THREAD

**Issue by liorn** [microsoft/vscode#193455] opened 2023-09-19 12:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: 

Steps to Reproduce:

1. Open this link for a vscode.dev session on a public github repo, with a long branch name: https://vscode.dev/github/liorn/vscode_bug_long_filename/tree/deployments/after/bla/bla/after/bla/bla/after/bla/bla/after/bla/bla/after/bla/bla
2. Search for "secret". *There are no results*, although the single file in the repo does contain the string "secret".

**Comment by liorn** [comment] 2023-10-25 15:37
@joyceerhl @andreamah hey - are there any plans to fix this soon?
We are integrating VSCode dev into our product (www.salto.io) and this problem will prevent users from using it. A lot of our branches contain long names and paths, and unfortunately this bug will commonly happen to them.

**Comment by osortega** [comment] 2024-12-20 02:25
This is a duplicate of https://github.com/microsoft/vscode/issues/116303
Closing

/duplicate

**Closed by osortega** 2024-12-20 02:25 UTC
Labels: bug, confirmed, github-repositories
