### ISSUE TITLE
Markdown preview has stopped working.

### ISSUE THREAD

**Issue by bobeff** [microsoft/vscode#138860] opened 2021-12-10 16:18 UTC
Issue Type: <b>Bug</b>

After I updated to the latest 1.63.0 version of the VSCode the markdown preview has stopped working. 

**Steps to reproduce:**
1. Open a markdown file.
2. Press Ctrl+K V to open markdown preview.

**Result:**
The window for a preview opens but it is empty.

The following error has been reported:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.13.0-22-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics (16 x 3622)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 5|
|Memory (System)|38.59GB (16.06GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9c94c015-c0b0-4912-b562-92559ef0811e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710:30405998
vscexrecpromp3c:30407761

```

</details>

**Comment by mjbvz** [comment] 2021-12-10 18:59
Duplicate of #125993

**Closed by mjbvz** 2021-12-10 18:59 UTC
Labels: new release
