### ISSUE TITLE
"resource" scoped setting returns stale value

### ISSUE THREAD

**Issue by dlech** [Microsoft/vscode#36664] opened 2017-10-21 00:14 UTC
- VSCode Version: 1.18.0-insider
  Commit 4b01451cea60f32412098735709fddcac567b33d
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Clone `https://github.com/dlech/vscode-workspace-settings-bug.git` in VS Code
2. Run/debug the extension
3. Open a folder in the extension development host
4. Open any file in this folder (create a new file if needed)
5. Use command palette to run "Show setting1" - it shows an info box with the default value "default"
6. Use the settings editor to change the value of "extension.setting1" for the folder.
7. Run the  "Show setting1" command again - **it still shows "default" instead of the new value**
8. Reload the window
9. Run the  "Show setting1" command again - it now shows the correct value from the folders settings

Reproduces without extensions: Yes

**Comment by sandy081** [comment] 2017-10-23 09:47
Duplicate of #36448

**Closed by sandy081** 2017-10-23 09:47 UTC
Labels: workbench
