### ISSUE TITLE
The keyboard cursor disappears while side is open

### ISSUE THREAD

**Issue by csutorasr** [Microsoft/vscode#9088] opened 2016-07-11 18:13 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open files side by side.
2. Adjust the width to a low value (e. g. 40% of the screen.
3. Go right with the keyboard cursor.

The cursor disappears if you do this. Only it won't render at the righter positions but it is there and you can type.

**Comment by bpasero** [comment] 2016-07-11 18:14
@csutorasr does it make a difference if you disable tabs (`workbench.editor.showTabs`) ?

**Comment by csutorasr** [comment] 2016-07-11 18:16
Yes, it makes difference. Then everything works well. 1.3.0 and tabs brought this.

**Comment by bpasero** [comment] 2016-07-11 18:22
I can reproduce...

**Comment by bpasero** [comment] 2016-07-11 18:40
@csutorasr can you try me solution in https://github.com/Microsoft/vscode/issues/9029#issuecomment-231825432 ?

**Comment by csutorasr** [comment] 2016-07-11 18:47
document.getElementsByClassName("mix-blend-mode") returns []
So i think it won't work.

**Comment by csutorasr** [comment] 2016-07-12 00:53
I found out.
(Sorry, I can't reproduce, I just switched tabs)
The linewrap turnt on for no reason in tab mode, then the cursor came back. I think something could happen with line wrapping. If I would go out of line wrapping then my cursor is lost.

**Comment by bpasero** [comment] 2016-07-12 05:05
@csutorasr this is not a CSS class but a CSS property on the title element where tabs are in!

**Comment by bpasero** [comment] 2016-07-12 13:11
Duplicate of https://github.com/Microsoft/vscode/issues/8828

**Closed by bpasero** 2016-07-12 13:11 UTC
Labels: important
