### ISSUE TITLE
Semantic Highlighting cant be disabled

### ISSUE THREAD

**Issue by Limonische** [microsoft/vscode#93897] opened 2020-03-31 11:50 UTC
- VSCode Version: 1.44.0-insider
- OS Version: macOS Catalina 10.15.4

Steps to Reproduce:

1. Set "semanticHighlighting": false
2. Open any js file

Notification "Code coloring of 'something.js' has been updated as the theme 'Theme Name' has semantic highlighting enabled."
Semantic highlighting doesn't get disabled.

**Comment by aeschli** [comment] 2020-03-31 21:11
The setting is
```
	"editor.tokenColorCustomizations": {
		"semanticHighlighting": false
	}
```
That's what you tried?

**Comment by DanielHZhang** [comment] 2020-04-01 02:11
I'm having this issue on 1.44.0-insider as well.
I tried applying the following in both the user and workspace settings, but none of them work:
```
 "editor.semanticHighlighting.enabled": false,
 "editor.tokenColorCustomizations": {
   "semanticHighlighting": false,
   "[themeName]": {
     "semanticHighlighting": false,
   }
 }
```

**Comment by vasilenka** [comment] 2020-04-01 08:31
@aeschli I've tried that one, I've tried the one with the theme name, also the old syntax `"editor.semanticHighlighting.enabled": false` but none of them are working.

It's working fine before with the old syntax. 

Here's my VS Code:
Version: 1.44.0-insider
Commit: 2f984aad710215f4e4684a035bb02f55d1a9e2cc
Date: 2020-04-01T05:48:07.538Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

**Comment by Limonische** [comment] 2020-04-01 10:46
> The setting is
> 
> ```
> 	"editor.tokenColorCustomizations": {
> 		"semanticHighlighting": false
> 	}
> ```
> 
> That's what you tried?

Yes. This and other methods two people above tried.

**Comment by aeschli** [comment] 2020-04-01 21:09
duplicate of https://github.com/microsoft/vscode/issues/94211

**Closed by aeschli** 2020-04-01 21:09 UTC
