### ISSUE TITLE
Universal help menu shortcut is not triggering on OSX

### ISSUE THREAD

**Issue by ajaymahale** [microsoft/vscode#84103] opened 2019-11-07 05:30 UTC
Issue Type: <b>Bug</b>

Open VS Code and try to access the app help menu using the keyboard shortcut `CMD + SHIFT + /`

The help menu doesn't appear. Have to use the mouse to trigger the Help menu.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_7964568|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
markdown-preview-github-styles|bie|0.1.6
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-eslint|dba|1.9.1
vscode-quick-select|dba|0.2.8
githistory|don|0.4.6
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.1.2
prettier-vscode|esb|2.3.0
vscode-todo-plus|fab|4.14.1
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.12.0
vscode-test-explorer|hbe|2.14.6
vscode-styled-components|jpo|0.0.26
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|0.8.2
csharp|ms-|1.21.6
copy-json-path|nid|0.0.5
vscode-jest|Ort|3.0.2
vscode-jest-test-adapter|rtb|0.2.0
code-spell-checker|str|1.7.20
gitblame|wad|3.0.1
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by alexandrudima** [comment] 2019-11-07 08:45
Duplicate of #68604

**Closed by alexandrudima** 2019-11-07 08:45 UTC
