### ISSUE TITLE
Autocomplete doesn't work in .jsx-files

### ISSUE THREAD

**Issue by lohmander** [Microsoft/vscode#483] opened 2015-11-23 10:30 UTC
Autocompletion of variable names, auto closing of brackets and so on doesn't seem to work in .jsx-files. Shouldn't these files work the same way as the regular .js-files with the exception of supporting the JSX syntax?

**Comment by admmasters** [comment] 2015-11-23 10:58
Yeah think this is being tracked in #140 .

**Comment by egamma** [comment] 2015-11-23 15:25
Closing this is a duplicate of #140.

**Closed by egamma** 2015-11-23 15:25 UTC
