### ISSUE TITLE
[Version 1.56.2] Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by cloudsere** [microsoft/vscode#125661] opened 2021-06-07 12:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Remove `.vscode` folder and reinstall VSCode
2. Open VSCode to see the extension host terminated unexpectedly error
![屏幕截图 2021-06-07 051146](https://user-images.githubusercontent.com/9955832/121014773-32968080-c74f-11eb-8c54-3bb8d662f1dd.png)

**Comment by alexdima** [comment] 2021-06-08 07:19
@cloudsere Does this reproduce all the time, even when opening an empty window? Does this reproduce when disabling all extensions? Can you please share the extension host log (`F1 > Developer: Show Logs... > Extension Host`)?

**Comment by alexdima** [comment] 2021-06-09 13:53
I am sorry about that! That's definitely wrong. Could you please share the `renderer` log or any logs that have content / show errors ?

**Comment by cloudsere** [comment] 2021-06-21 08:14
I reinstall my windows system...and it worked for several days...today it happens again @alexdima can you help with it?
[20210621T010951.zip](https://github.com/microsoft/vscode/files/6685083/20210621T010951.zip)

**Comment by cloudsere** [comment] 2021-06-21 10:16
@vscode-triage-bot can you help to re open this issue?

**Comment by alexdima** [comment] 2021-06-21 12:38
@cloudsere Thank you for the logs. Unfortunately, they are not really revealing of any problem. But on taking another look at your initial screenshot, I noticed the following:
![image](https://user-images.githubusercontent.com/5047891/122763010-2c9bb600-d29e-11eb-86c8-111e63d19a9d.png)

Do you have any kind of software installed (e.g. antivirus software) that would actively interfere with [named pipes](https://en.wikipedia.org/wiki/Named_pipe#In_Windows) ?

**Comment by cloudsere** [comment] 2021-06-21 15:44
@alexdima I use event logs and found a same log as https://github.com/microsoft/vscode/issues/97031 this issue, but this seems have no affect on the extension host termination error... I think windows defender is the only anti virus software I have, can you tell me how can I check whether a software is interfered with named pipes?

**Comment by alexdima** [comment] 2021-06-21 16:03
@cloudsere Is there anything special about your Windows machine? 

e.g. is it Windows 10 Home/Pro or Windows Server, is your computer domain joined, is it managed by your organization in any way, do you have proxies configured? Is there anything *special* ?

**Comment by cloudsere** [comment] 2021-06-21 16:20
@alexdima Yes, my computer is domain joined and managed by my organization(microsoft:)), I have proxies configured

**Comment by cloudsere** [comment] 2021-06-22 09:37
@alexdima After debugging for a long time, I found that my DNS server is of high CPU usage, and I run `ipconfig /all` and found infinite list of strange server `10.50.50.50`, I run `netsh  interface  ip set DNS Name="Ethernet"  source=DHCP` in powershell, and it works!

**Comment by alexdima** [comment] 2021-06-22 20:28
@cloudsere I'm not an expert with that, so I'm not sure I understood what the problem was, nor what the fix was. Could you please elaborate so I know in the future what problems there might be in the area of named pipes?

**Comment by cloudsere** [comment] 2021-06-24 15:46
Sorry, I am also not sure whether this have something to do with name pipes...

**Comment by alexdima** [comment] 2021-06-29 07:43
Since your issue is resolved and there is nothing to do on our side, I will close this issue for now.

**Closed by alexdima** 2021-06-29 07:43 UTC
Labels: needs more info
