### ISSUE TITLE
Markdown editing experience

### ISSUE THREAD

**Issue by brgrz** [Microsoft/vscode#38499] opened 2017-11-16 10:39 UTC
Currently the Markdown editing experience works in a way that whenever I open a new .md file it would open it separately even if I already have a .md file opened and preview turned on. 

It would then open a new preview window to the side whenever the preview is requested.

A better experience would be to share preview pane across .md files I'm currently editing - when I switch to editing another file the MD preview would sync and (automatically) show the preview of the file I switched to.

The attached screenshot demonstrates the problem. I'm was editing configuration.md and switched to deployment.md and the preview did not update/sync accordingly.

![image](https://user-images.githubusercontent.com/193816/32887017-d3a0f5ec-cac2-11e7-957b-71224de851c7.png)

**Comment by mjbvz** [comment] 2017-11-17 00:39
Duplicate of #27983 / #2766

**Closed** 2017-11-17 00:39 UTC
Labels: *duplicate, markdown
