### ISSUE TITLE
javascript validation is not working

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4215] opened 2016-03-15 00:51 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: OSX 

#4022
Steps to Reproduce:

1. open a new file, add a workspace setting to enable javascript validation `"javascript.validate.enable": false`
2. in the file type: 
```javascript
var str = "qrqweqwewqe"; 
str.test(); 
```

Expected: error under test since test method is not defined on a string.

**Comment by egamma** [comment] 2016-03-15 07:37
>open a new file, add a workspace setting to enable javascript validation "javascript.validate.enable": false

Setting validation to false disables the built-in validation.

Even if you set the setting to `true` you will not get errors. Salsa doesn't report type errors.
Closing as a duplicate of https://github.com/Microsoft/TypeScript/issues/6802

**Closed by egamma** 2016-03-15 07:37 UTC
