### ISSUE TITLE
Model is disposed after closing settings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25511] opened 2017-04-27 05:50 UTC
Found this in my console today, I guess I closed settings:

```
Model is disposed!: Error: Model is disposed!
    at Model.TextModel._assertNotDisposed (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModel.js:56:23)
    at Model.TextModelWithDecorations.changeDecorations (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/model/textModelWithDecorations.js:141:18)
    at InsertSnippetController.stopAll (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/snippet/common/snippetController.js:287:24)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/contrib/snippet/common/snippetController.js:154:23
    at CallbackList.invoke (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:88:40)
    at CodeEditor.CommonCodeEditor.setModel (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/commonCodeEditor.js:150:36)
    at TextFileEditor.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/browser/editors/textFileEditor.js:186:31)
    at SideBySidePreferencesWidget.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:330:48)
    at PreferencesEditor.clearInput (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/preferences/browser/preferencesEditor.js:122:46)
```

**Comment by bpasero** [comment] 2017-05-16 04:43
Already happening in 1.12.x it seems (error telemetry shows it).

**Comment by sandy081** [comment] 2017-05-31 19:02
This is a duplicate of #26617

**Closed by sandy081** 2017-05-31 19:02 UTC
Labels: bug, settings
