### ISSUE TITLE
[snippets] How to get current Filename, LineNumber from Snippet

### ISSUE THREAD

**Issue by 1-9** [Microsoft/vscode#11555] opened 2016-09-06 02:30 UTC
- VSCode Version: 1.4.0
- OS Version: OS X EL Capitan

How can I get filename and line number to insert into a snippet?

**Comment by aeschli** [comment] 2016-09-06 07:55
We currently don't have support for that.

**Comment by careuno** [comment] 2016-10-03 09:53
It would be great if you enable the possibility to get the filename (name of the class) and path (for name of namespace), I'm trying to generate C# class skeleton like Visual Studio.
Thank you

**Comment by jrieken** [comment] 2016-11-03 15:22
closing as duplicate of #13047

**Closed by jrieken** 2016-11-03 15:22 UTC
Labels: feature-request, snippets
