### ISSUE TITLE
Scope background color support for themes

### ISSUE THREAD

**Issue by flagello** [Microsoft/vscode#16461] opened 2016-12-04 17:12 UTC
- VSCode Version: 1.7.2
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. `ext install theme-a`
2. Change theme

<img width="429" alt="screen shot 2016-12-04 at 18 05 37" src="https://cloud.githubusercontent.com/assets/649779/20867808/d2ec5ae2-ba4c-11e6-96be-bc00812731f3.png"><br><br>
_so_<br>
<img width="324" alt="screen shot 2016-12-04 at 18 03 30" src="https://cloud.githubusercontent.com/assets/649779/20867807/d2e8d552-ba4c-11e6-9fce-d8e4bde49ed3.png"><br><br>
_but_<br>
<img width="265" alt="screen shot 2016-12-04 at 18 04 20" src="https://cloud.githubusercontent.com/assets/649779/20867806/d2ba2950-ba4c-11e6-9cdb-643c42078d5b.png">

**Comment by chrmarti** [comment] 2016-12-05 01:44
@flagello Not sure I follow, what should the background color be scoped to?

**Comment by flagello** [comment] 2016-12-05 14:48
Sorry for the lack of clarity @chrmarti. I meant that a scope’s background color is not applied despite being specified.

_VS Code_
<img width="429" alt="screen shot 2016-12-04 at 18 05 37" src="https://cloud.githubusercontent.com/assets/649779/20867808/d2ec5ae2-ba4c-11e6-96be-bc00812731f3.png"><br><br>

_TextMate 2_
<img width="446" alt="screen shot 2016-12-05 at 15 45 30" src="https://cloud.githubusercontent.com/assets/649779/20889078/e54fc61e-bb01-11e6-857a-0e4cd9f598fe.png">

**Comment by aziz** [comment] 2017-02-08 18:34
I have this issue as well. vs-code basically ignores all background color definitions for the scopes in tmTheme file and only applies the global background color. 
This is extremely useful to make themes that get different background colors for different syntaxes. 
for example: 
- marking the code section in a markdown
- changing the background color of the style and script tags inside an HTML document
- change the background color of embedded code inside HTML documents for templating libraries in PHP, Ruby and Python
- having syntax specific background colors. you might want light background color for markdown but dark background color for all the code.

**Comment by auchenberg** [comment] 2017-08-02 00:57
Duplicate, https://github.com/Microsoft/vscode/issues/3429

**Comment by aeschli** [comment] 2017-08-18 07:50
closing as duplicate of #3429, thanks @auchenberg!

**Closed by aeschli** 2017-08-18 07:50 UTC
Labels: editor-core, feature-request
