### ISSUE TITLE
Source Code shows wrong branch

### ISSUE THREAD

**Issue by marcoschou** [microsoft/vscode#165335] opened 2022-11-03 10:43 UTC
Type: <b>Bug</b>

1. Start VsCode
2. Switch to a different branch
3. Source control still shows original (master) branch.
4. I think I should mention that I am using git worktrees, in case it has something to do with the problem.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.44GB free)|
|Process Argv|--crash-reporter-id 786768c0-d188-4f92-a2ad-02c742f90339|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 999)|
|Memory (System)|125.42GB (52.25GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
gitlens|eam|13.0.3
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
3d0df643:30602300

```

</details>

**Comment by ungenict** [comment] 2022-11-03 11:51
I have the same issue. Plus VS Code will pull from master (or other originals) and not the checked out branch.

**Comment by SvenEV-bakerhughes** [comment] 2022-11-03 11:55
Same here since version 1.73.0 🙋‍♂️

**Comment by ungenict** [comment] 2022-11-03 12:23
Changes in #162572 caused this bug. To be specific is this line: 
https://github.com/microsoft/vscode/blob/9c802415e11bf11230720bc4a93397c338121da8/extensions/git/src/git.ts#L2086

This was meantioned by [[jarrodldavis](https://github.com/jarrodldavis) ](https://github.com/microsoft/vscode/issues/164363#issuecomment-1301337047)

**Comment by lszomoru** [comment] 2022-11-04 08:27
Closing as duplicate of #164363

**Closed by lszomoru** 2022-11-04 08:27 UTC
Labels: bug, git, new release
