### ISSUE TITLE
Improper Formatting when using Quick Fix to Import a missing type

### ISSUE THREAD

**Issue by sgalizia** [microsoft/vscode#107475] opened 2020-09-25 19:20 UTC
- VSCode Version: 1.49.2
- OS Version: Windows 10 Pro (Version 2004)

Steps to Reproduce:

1. Open a TypeScript file in a project
2. Add code that references a class or interface in another file in the project
3. Use the quick fix to automatically add the missing import
4. The resulting import is improperly formatted. Example from a project below:
```
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsIn,
  Matches,, Length
} from 'class-validator';
```
In the last line of the destructuring you can see that the import added `, Length` but it was improperly formatted and now there are two commas in a row, breaking the formatting. It's not something that prevents work from being done, but it is an inconvenience and can be easy to miss.

Does this issue occur when all extensions are disabled?: I am using the WSL Remote extension and was not able to disable all extensions to check this issue. I do have coworkers having the same issue working on macOS (no remote extension installed or used)

**Comment by sgalizia** [comment] 2020-09-25 19:25
To add some more context here, this could be an issue where Prettier is formatting the code and using trailing commas. If the quick fix action is not checking for a comma already in place, that could be the issue here and why there are two commas back to back. If our Prettier formatting did not have trailing commas, this would be fine.

**Comment by mjbvz** [comment] 2020-09-25 19:40
Duplicate of #107057

Should be fixed in the current VS Code insiders builds

**Closed by mjbvz** 2020-09-25 19:40 UTC
Labels: new release

**Comment by sgalizia** [comment] 2020-09-30 19:45
> Duplicate of #107057
> 
> Should be fixed in the current VS Code insiders builds

Ah missed that sorry! I did search for a similar issue but guess I didn't search with Prettier. Glad to see it is resolved.
