### ISSUE TITLE
exit full screen toggle(middle button in the right corner) stopped working 

### ISSUE THREAD

**Issue by pelx** [microsoft/vscode#84913] opened 2019-11-15 12:54 UTC
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1.Open VSCode
2. change the size
3. press maximize button
4. Toggle - nothing happens

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by IllusionMH** [comment] 2019-11-15 13:19
Is it about actual Full screen (<kbd>F11</kbd> or Zen Mode) or just problems with Maximize/Restore button?

Probably duplicate of #84343 (as mentioned in https://github.com/microsoft/vscode/issues/84798#issuecomment-554131186)

Could you try Insiders build (https://code.visualstudio.com/insiders/) to see if this issue is fixed there? 
See https://github.com/microsoft/vscode/issues/84343#issuecomment-554202848

**Closed** 2019-11-16 00:20 UTC
Labels: *duplicate
