### ISSUE TITLE
Organizing imports breaks undo history

### ISSUE THREAD

**Issue by domoritz** [Microsoft/vscode#54411] opened 2018-07-16 19:31 UTC
- VSCode Version: 1.25.1
- OS Version: macos

Steps to Reproduce:

1. Enable
```json
	"editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
```

2. Edit some code, add an import, and make sure that vscode has to remove or reorder imports. Now try to undo. The cursor jumps to the top of the file instead of just changing the code that you were editing.

**Comment by domoritz** [comment] 2018-07-16 19:57
Maybe this is realated to the prettier plugin. I'm going to check this with plugins disabled.

**Comment by mjbvz** [comment] 2018-07-16 20:30
Do you see this with all extensions disabled? I wasn't able to reproduce it in vanilla VS Code

**Comment by domoritz** [comment] 2018-07-16 20:32
yes, I tried it with `code --disable-extensions`. Let me try to make a video.

**Comment by domoritz** [comment] 2018-07-16 20:41
![editor](https://user-images.githubusercontent.com/589034/42782454-dc1ca51e-88fd-11e8-9460-cd26e3b21e7f.gif)

**Comment by jrieken** [comment] 2018-07-17 07:04
@mjbvz This could be a duplicate of #54117. @domoritz Please try with latest insiders (b48367a8652bd0aa862638bbc24555a70823d3bd or newer)

**Closed** 2018-07-24 11:00 UTC
Labels: editor, needs more info
