### ISSUE TITLE
Stacktrace view loses focus on stopped thread

### ISSUE THREAD

**Issue by DatGuyJonathan** [Microsoft/vscode#34246] opened 2017-09-12 20:50 UTC
- VSCode Version: 1.16.0-insider
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Start debugger session with a debugger extension that supports multiple stopped threads.
2. Stop at least two threads.
3. Step over with the second thread.

Reproduces without extensions: Yes

Apologies for the watermark, but you can see the UI remains focused on the first thread after the second thread stops again. I think the UI should refocus on the thread that is most recently stopped.

![stacktracefocus](https://user-images.githubusercontent.com/7286437/30347046-a7782c78-97bf-11e7-83d7-4c9844034923.gif)

I suspect the issue is in [debugService.tryToAutoFocusStackFrame()](https://github.com/Microsoft/vscode/blob/release/1.16/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L250). I think that if-statement should be true if there is no callstack or the current focused stack frame is in the same thread as the method parameter. So, something like this:

`if (!callStack.length || (this.viewModel.focusedStackFrame && this.viewModel.focusedStackFrame.thread.threadId === thread.threadId)) {`

**Comment by isidorn** [comment] 2017-09-13 09:22
@DatGuyJonathan thanks for the nice steps and for the pointer where you think the fix is.
However I believe this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1617

Even though if you are maybe not using the C# adapter the extension you are using is suffering from the same flow I described in that issue.

And yes I was first optimistic to try your fix but that did not help. The problem is that when you click step over, the adapter actually contoniues all threads, and then when the stop even comes it comes for the wrong thread making vscode focus wrongly.

Closing as duplicate / caused by extension. Please check with the extension for more details

**Closed by isidorn** 2017-09-13 09:22 UTC
Labels: debug, insiders

**Comment by DatGuyJonathan** [comment] 2017-09-13 21:45
@isidorn I set a breakpoint in rawDebugSession.ts to see how NextResponse is handled. After receiving a response from the adapter, it calls fireFakeContinued() with allThreadsContinued = false. We can see this in the GIF because the second thread's state is 'running' and the first thread's state is still 'paused'. In debugService.ts, the continued event is handled by trying to focus on a stackframe, but it uses a null stackframe. So, focusStackFrameAndEvaluate() defaults the focus to the first thread's stack.

When the stopped event comes for the second thread, it tries to focus that thread's stackframe, but it won't because of that if-statement I mentioned earlier. There's already a focused stackframe, so it won't try to focus again.

Is there a way I can prevent the UI from defaulting to focus on the first thread? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L499

**Comment by isidorn** [comment] 2017-09-14 08:03
@DatGuyJonathan sounds like you got quite deep in the code. Would you be willing to provide a PR, since it is a bit easier for me to understand your intention by looking at proposed code.
Here is our guide on how to contribute https://github.com/Microsoft/vscode/wiki/How-to-Contribute

When running vscode out of source, you will need to add a debug extension. You can do that by simply dropping a .vsix of the extension you are using.
