### ISSUE TITLE
Call stack of the debugger is too narrow when debugging C++

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode#79748] opened 2019-08-24 20:40 UTC
VSCode 1.37.1

When I hit breakpoints debugging a C++ application, the call stack view of the debugger is way too small to fit lines of that length. It forces me to resize the panel to an absurd width to see information:

![image](https://user-images.githubusercontent.com/1311555/63642463-580be480-c6b7-11e9-8b5f-9345873b28f5.png)

I was using QtCreator before and it showed the call stack at the bottom too just fine.
Could there be a way to move the call stack to a bottom panel, where there is more horizontal space to fit the stack?

Note: I guess the debugger GUI is not specifically related to the cpptools extension, but if it is I'll move the issue.

**Comment by isidorn** [comment] 2019-08-26 07:43
For moving the call stack view to the panel it is a duplicate of 
https://github.com/microsoft/vscode/issues/41686
and https://github.com/microsoft/vscode/issues/50853 which will give us more flexible layout.

As for the content of the callstack view please file that against the C++ extension so hey potentially trim the content on their end. Thanks

**Closed by isidorn** 2019-08-26 07:43 UTC
