### ISSUE TITLE
Indent guides skip every couple of levels

### ISSUE THREAD

**Issue by jnicol** [Microsoft/vscode#39607] opened 2017-12-05 06:50 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.4.0
- Extensions: All disabled

I have noticed that the indent guides in vscode skip every couple of indent levels:

<img width="505" alt="screen shot 2017-12-05 at 5 48 27 pm" src="https://user-images.githubusercontent.com/1201646/33593694-9f31b978-d9e4-11e7-8b49-6f5636d29642.png">

Is this by design? Is there any way to have a guide shown at every level?

**Comment by jnicol** [comment] 2017-12-05 11:18
I figured out what is causing it: a negative window.zoomLevel.

**Comment by alexandrudima** [comment] 2017-12-05 11:23
Duplicate of #38656

**Closed by alexandrudima** 2017-12-05 11:23 UTC
Labels: editor
