### ISSUE TITLE
C++ Syntax Hightlighting acts strangely with multi-line defines.

### ISSUE THREAD

**Issue by Knifa** [Microsoft/vscode#21330] opened 2017-02-24 04:56 UTC
Multi-line defines don't seem to terminate correctly.

- VSCode Version: 1.9.1
- OS Version: Windows 10 x64

Images probably better than written steps.

Current:
![image](https://cloud.githubusercontent.com/assets/622619/23291048/6a21067a-fa4d-11e6-9e24-6153362ad304.png)

Better (fixed by adding an extra semi-colon):
![image](https://cloud.githubusercontent.com/assets/622619/23291060/7cfd56fe-fa4d-11e6-8e74-74b0124747c1.png)

Expected:
- Define lines fully syntax highlighted, like the first and second lines.
- Remaining code resumes as normal.

Code for testing convenience:
```#define MAX(a, b) (a > b ? a : b)
#define STATE_BUFFER_SIZE \
    MAX(sizeof(ScreensaverStateHandler), \
    MAX(sizeof(SearchStateHandler), \
    MAX(sizeof(BandScanStateHandler), \
    MAX(sizeof(MenuStateHandler), \
    MAX(sizeof(SettingsStateHandler), \
        sizeof(SettingsRssiStateHandler) \
    )))))
```
Code itself compiles correctly with GCC 4.x.

**Comment by aeschli** [comment] 2017-02-24 08:50
duplicate of https://github.com/atom/language-c/issues/160

**Closed by aeschli** 2017-02-24 08:50 UTC
