### ISSUE TITLE
[php] No suggestion for "id" as an html attribute

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#45865] opened 2018-03-15 14:01 UTC
Issue Type: <b>Bug</b>

In an HTML tag, type `id`.  Instead of  former completion of `id=""`, it suggests only `idate`.

![mar-15-2018 09-58-18](https://user-images.githubusercontent.com/835148/37467915-e10bc2fc-2837-11e8-9a92-e32a9c678ac4.gif)

VS Code version: Code - Insiders 1.22.0-insider (509b8084d46b82ec5851447903cebd914e4535a5, 2018-03-15T09:25:17.428Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.25GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1364301|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.5.1
code-settings-sync|Sha|2.9.0
sort-lines|Tyr|1.5.0
Bookmarks|ale|0.18.2
project-manager|ale|0.24.1
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.8.1
svg|joc|0.0.9
Angular2|joh|2.14.0
vscode-icon-theme|jtl|1.6.1
ecdc|mit|0.11.0
HTMLHint|mka|0.4.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.20.0
polacode|pnp|0.2.2
stylelint|shi|0.34.2
rewrap|stk|1.8.0
ayu|tea|0.14.0
bootstrap4-vscode|the|4.0.0
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment] 2018-03-15 15:24
The suggestion for `id` comes from the html extension, not emmet.
Can you try with all extensions disabled? Run `code --disable-extensions`

**Comment by smlombardi** [comment] 2018-03-15 20:43
It happens with extensions off.  It was a .php file.  It seems to work OK in standard html files.

**Comment by aeschli** [comment] 2018-03-16 07:50
If it's for a PHP file, then this is a duplicate of https://github.com/Microsoft/vscode/issues/670.

For more HTML support in PHP, I'd recommend installing the [intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) extension.

**Closed by aeschli** 2018-03-16 07:50 UTC
Labels: php
