### ISSUE TITLE
Width of right-terminal pane messed up following update to 1.42

### ISSUE THREAD

**Issue by Hong-Revo** [microsoft/vscode#90188] opened 2020-02-07 00:50 UTC
- VSCode Version: 1.42.0
- OS Version: Win 10 Pro 1909

I have a widescreen monitor, so I put my terminal/output/debug pane on the right rather than below the editor pane. It should take up a bit less than half the screen width. After updating to 1.42, this no longer happens; instead the pane shrinks to about one-quarter the width. Resizing the pane and restarting VScode doesn't fix this either; it retains the incorrect width.

What it should look like:

![image](https://user-images.githubusercontent.com/11328890/73991207-a0863880-499f-11ea-81e5-a6a929f49c27.png)

What it actually looks like after restarting Code:

![image](https://user-images.githubusercontent.com/11328890/73991178-88161e00-499f-11ea-92b1-3d83986be404.png)

Steps to Reproduce:

1. Put the terminal pane on the right
2. Drag it to a new width
3. Close VScode and reopen

Does this issue occur when all extensions are disabled?: Yes

**Comment by Hong-Revo** [comment] 2020-02-07 00:57
Possibly relevant info: I also use a 4k monitor at 200% text size.

**Comment by sbatten** [comment] 2020-02-07 02:29
not able to reproduce this issue currently.

I'm following the steps above. If you wait a few seconds after you resize the editor, does the behavior change?

**Comment by P1X3L0V4** [comment] 2020-02-07 09:27
- VSCode Version: 1.42.0
- OS Version: Win 10 Pro 1909

Same issue. Recorded a screen to show how looks on the user side. It looks like the terminal panel is being closed when width goes below certain value.

Link: https://imgur.com/a/nb55Ct9

![](https://imgur.com/a/nb55Ct9)

**Comment by Hong-Revo** [comment] 2020-02-07 11:43
@sbatten Waiting doesn't change anything. Just to clarify: the terminal pane width should remember what I set it to. What I'm seeing is that it doesn't; it always goes back to the wrong width after a restart.

More info: this is a system install, so Code is located in C:\Program Files\Microsoft VS Code.

**Comment by sbatten** [comment] 2020-02-07 15:40
@P1X3L0V4 the behavior you show in the video is intended behavior. when parts of the product resized below their minimum size, we "snap" them away.

@Hong-Revo 
Before Reload: 
![image](https://user-images.githubusercontent.com/6561887/74042718-eb428900-497c-11ea-9593-b0c622b3269b.png)

After Reload:
![image](https://user-images.githubusercontent.com/6561887/74042736-f2699700-497c-11ea-80e6-4aedda5ea595.png)

Do you see any errors in the console when you run `F1` > `Toggle Developer Tools`

**Comment by Hong-Revo** [comment] 2020-02-07 16:03
No errors in the dev console, if this is the one you're referring to:

![image](https://user-images.githubusercontent.com/11328890/74044481-3f05ae80-4a1f-11ea-9722-72a811c00414.png)

Just wondering, since you have a large display: what happens if you set the text size to >100%?

**Comment by P1X3L0V4** [comment] 2020-02-07 16:22
> @P1X3L0V4 the behavior you show in the video is intended behavior. when parts of the product resized below their minimum size, we "snap" them away.

Is there a way to change the minimum width of the terminal panel when it's on the right/left?

Before the recent update I was able to make the width half of what it is minimum right now (let's say 270px). After the update the panel "snaps" at around 420px. I work with two document windows side by side + terminal and every space is precious.

I've checked the changelog (https://code.visualstudio.com/updates/v1_42) already but don't see anything helpful.

Is there a way to change the width or roll back to older VSCode ver?

**Comment by sbatten** [comment] 2020-02-07 16:26
@P1X3L0V4 older versions are always available in their release note pages, you will have to disable updates in settings to stay on that version. that being said, i don't want you to have to stay on an older version and we are tracking an issue to fix to improve this here https://github.com/microsoft/vscode/issues/87347. it looks like you have already found this issue and upvoted it. :)

**Comment by sbatten** [comment] 2020-02-07 16:28
@Hong-Revo yep that's the one. thanks for checking.

On my 4K @ 200% scaling I see the same exact results, so not reproducing still :(

**Comment by P1X3L0V4** [comment] 2020-02-07 16:37
@sbatten Thanks for the reply. I will follow both issue threads 👍

**Comment by Hong-Revo** [comment] 2020-02-07 18:07
I tried rebooting and reinstalling. No luck.

This is with a system install of Code, if that helps.

**Comment by sbatten** [comment] 2020-02-07 19:32
tried the system install as well but no repro. could you record a video of your steps, maybe I can see something that will help? @Hong-Revo

**Comment by Hong-Revo** [comment] 2020-02-08 01:18
I'll give it a try. What's the best way of recording a video?

**Comment by sbatten** [comment] 2020-02-10 19:47
I usually use the game screen recorder built-in. Win+G when VS Code is focused. Then select record in the overlay that pops up.

**Comment by Hong-Revo** [comment] 2020-02-10 20:37
Ok, thanks. I've recorded a clip:

https://1drv.ms/v/s!Ag5qXZX_nSfWwmyTe2uNzFRqBcku?e=Ty6mQe

Here, I:
- open the folder "AzureStor"
- faff around a bit
- resize the terminal pane
- close the folder
- reopen it

**Comment by sbatten** [comment] 2020-02-10 22:14
@Hong-Revo ah! I know the issue now. The key was that you were closing folder with the menu entry, not closing VS Code altogether. I hope this explanation helps and I have a fix for you as well. 

## Context

### Global Panel Size Cache
The size of the terminal panel is saved on a global level. That means that it applies to every window/workspace you open and we don't have individual sizes stored for each workspace. This is because layout sizing typically depends a lot on the window dimensions which aren't workspace-specific. 

### Panel location
Panel has a setting for the default position when a new workspace is opened. When you move the panel with the command or context menu, the settings does not change. Maybe it should but today it doesn't. This setting is `workbench.panel.defaultLocation`.

## What's Happening

First, you open a known workspace. It has a specific position for the terminal pane and opens it there. It saves this size and position.

Next, you close the folder which forces VS Code into an empty workspace which in our case counts as a new workspace every times. That means it uses the default panel location. Due to some additional restoration logic, that overrides your panel position and size with a smaller default.

When you reopen the original workspace, the same additional restoration logic kicks in. The summary is that the panel goes in between positions right and bottom without you seeing it and that resets its sizing.

## Fix it

If you prefer the terminal on the right the majority of the time. Update this setting: `workbench.panel.defaultLocation` to `right` and try to repro. You should see that this resolves the issue.

**Closed by sbatten** 2020-02-10 22:14 UTC
Labels: needs more info, new release

**Comment by Hong-Revo** [comment] 2020-02-10 22:32
Thanks for the info. I'm confused though, I didn't change my workflow at all between 1.41 and 1.42. What did the update change?

**Comment by sbatten** [comment] 2020-02-10 22:44
I believe the logic that we use to ensure that you get a sane layout when moving between workspaces with different panel positions was updated during the last iteration but that means in this case we fallback to the default sizing.

**Comment by Hong-Revo** [comment] 2020-02-10 22:52
Can we change it back please? The current behaviour is very unintuitive, not to mention suboptimal. I don't want to be closing VSCode entirely every time I close a workspace, just to ensure my settings stick. Similarly, I shouldn't have to edit a global default; for different types of projects I might want the pane to be on the right or the bottom, and it sounds like I can have my layout work for only one of these at a time.
