### ISSUE TITLE
JavaScript syntax highlight in for-loops is not correct

### ISSUE THREAD

**Issue by venelinpetrov** [Microsoft/vscode#4707] opened 2016-03-28 05:50 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 8.1

The problem is observed only in the following scenario:
```
for (i=0; attr && i<attr.length; i++) {
	if (attr[i].specified) {
		props[attr[i].name] = attr[i].value;
		hasAttrib = true;
	}
}
```
![image](https://cloud.githubusercontent.com/assets/3126733/14071805/c78772c8-f4c1-11e5-9560-1a1c27ff0a82.png)
compared to:
```
for (i=0; attr && i <attr.length; i++) {
	if (attr[i].specified) {
		props[attr[i].name] = attr[i].value;
		hasAttrib = true;
	}
}
```
![image](https://cloud.githubusercontent.com/assets/3126733/14071816/e4f099b6-f4c1-11e5-85f0-a0cf212ce0fc.png)

Notice the space between `i` and `<`.

**Comment by Tyriar** [comment] 2016-03-28 19:59
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by Tyriar** 2016-03-28 19:59 UTC
