### ISSUE TITLE
(bug/improvement) Ignore doc comment tags inside code block.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#118977] opened 2021-03-15 13:21 UTC
## Description

IntelliSense should ignore doc comments tags `@anything` in code blocks.

```ts
/**
 * The best decorator ever made.
 * 
 * @todo Fix the "@" bug in code block.
 * 
 * @example
 *
 * ```ts
 * class MyComponent {
 *   @SomeDecorator() myValue = 42;
 * }
 * ```
 */

 export function SomeDecorator() {}
```

![vscode-issue](https://user-images.githubusercontent.com/60390085/111159410-5f485b00-8599-11eb-921e-c77f033b8409.gif)

And as bonus the code block should styled with a code block looking. Like in Markdown files.

## Info

```
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by mjbvz** [comment] 2021-03-15 23:04
Duplicate of https://github.com/microsoft/TypeScript/issues/38922

**Closed by mjbvz** 2021-03-15 23:04 UTC
