### ISSUE TITLE
Configure task command failing without error message

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode#101057] opened 2020-06-25 19:11 UTC
- VSCode Version: 1.46.1
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. Include the attached `tasks.json` in your project.
2. Run command "Tasks: Configure Task..."
3. Select any task
4. `tasks.json` is not opened, and no visible error message appears
5. An error appears in the developer console

```
log.ts:197   ERR Unexpected token / in JSON at position 6: SyntaxError: Unexpected token / in JSON at position 6
    at JSON.parse (<anonymous>)
    at file:///C:/Users/styagev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5299:410
log.ts:197   ERR Unexpected token / in JSON at position 6: SyntaxError: Unexpected token / in JSON at position 6
    at JSON.parse (<anonymous>)
    at file:///C:/Users/styagev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5299:410
```

Does this issue occur when all extensions are disabled?: Yes

<details><summary>`tasks.json`</summary>
<p>

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Submit Philly",
            "type": "shell",
            "command": "${workspaceFolder}/atlitools/apropos/submit_philly.ps1",
            "args": [
                "-jobName",
                "genie_mvdr_input__sanity",
                "-vc",
                "sdrgvc",
                "-cluster",
                "wu2",
                "-userName",
                "styagev",
                "-localCodePath",
                "D:/Projects/PrincetonServices/src/OfflineSystem",
                "-codeBlobPrefix",
                "styagev/OfflineSystem",
                "-registryPass",
                // "-dryRun",
                // "1"
            ],
            "options": {
                "env": {
                    "AZURE_STORAGE_ACCOUNT": "princetonexp",
                    "PATH": "C:\\Users\\styagev\\.virtualenvs\\OfflineSystem.36\\Scripts;${env:PATH}"
                }
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Dask on local HPC",
            "type": "shell",
            "windows": {
                "options": {
                    "shell": {
                        "executable": "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"
                    },
                    "env": {
                        "PATH": "C:\\Users\\styagev\\.virtualenvs\\OfflineSystem.36\\Scripts;${env:PATH}"
                    }
                }
            },
            "command": "${workspaceFolder}/atlitools/apropos/dask_on_ilabs_hpc_directly.ps1",
            "args": [
                "-jobName",
                "sepnet_data_cook",
                // "${fileBasenameNoExtension}",

                // run using synced code
                // "-codeRoot", "\\\\ilabs-htcfs\\Shared\\styagev\\Projects\\PrincetonServices\\src\\OfflineSystem\\e2e_simulation",

                "-baseRemoteCodeRoot", "\\\\ilabs-htcfs\\Experiments\\Apropos\\IO\\styagev\\base_code",
                "-pythonEnv", "\\\\ilabs-htcfs\\Shared\\styagev\\.virtualenvs\\OfflineSystem.36",

                "-mainCmd",
                "python -u meeting_synth/labsr/training/experiments/sepnet_on_weak_genie_mvdr.py",
                // "python -u sandbox/stav/experiments/sepnet_analysis.py",
                // "python -u sepnet_train/experiments/sepnet_on_weak_genie_mvdr.py",
                // "externalClients",
                "-pipelineSpecificCodeFilters", "meeting_synth.labsr",

                "-nWorkers", "4",
                "-minWorkers", "4",
                "-nCoresPerWorker", "2",
                "-nThreadsPerWorker", "1",
                "-memoryLimitBytesPerWorker", "20e9",
                "-hpcNodeGroups", "AVX2,Fast,std",

                "-bDisablePreemption", "$true",

                "-bSaveGitCache", "$true"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Dask on Azure Batch",
            "type": "shell",
            "command": "${workspaceFolder}/atlitools/apropos/dask_on_azure_batch.ps1",
            "args": [
                "-jobName",
                "sepnet_extra_mvdr_feats__data_cook__50h",
                "-localPythonEnv",
                "C:\\Users\\styagev\\.virtualenvs\\OfflineSystem.36",

                // run using snapshot copy
                "-remoteCodeDirRel",
                "Shared\\styagev\\aproposCode\\PrincetonServices\\src\\OfflineSystem",
                "-localCodeRoot",
                "D:\\Projects\\PrincetonServices\\src\\OfflineSystem",

                "-mainCmd",
                // "python -u sandbox/stav/experiments/sepnet_analysis.py",
                "python -u sepnet_train/experiments/sepnet_on_weak_genie_mvdr.py",

                "-nWorkers",
                "150",
                "-minWorkers",
                "20",
                "-nCoresPerWorker",
                "2",
                "-nThreadsPerWorker",
                "1",
                "-memoryLimitBytesPerWorker",
                "20e9",
                "-hpcNodeGroups",
                "AVX2,Fast,std",

                "-bSaveGitCache",
                "$true"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Remote docker run",
            "type": "shell",
            "command": "ssh -t styagev@ilabs-gpulnx001 \"docker run --rm -d --gpus=all --network host --name=remote-run --label='user=styagev' --shm-size 100GB -v /net/ilabs-htcfs/Shared/styagev/Projects/PrincetonServices/:/PrincetonServices -v /net/ilabs-htcfs/PrincetonDatasets/OfflineSystemData/BlobMirror:/BlobMirror -v /net/ilabs-htcfs:/net/ilabs-htcfs -e LOCAL_BLOB_MIRROR=/BlobMirror -e username=styagev -e WAIT_FOR_ATTACH=0 --privileged atliresearch.azurecr.io/princeton_e2e:latest-dev tools/mount_and_launch.bash python -u sepnet_train/experiments/sepnet_on_weak_genie_mvdr.py && docker attach remote-run\"",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Remote docker stop",
            "type": "shell",
            "command": "ssh",
            "args": [
                "styagev@ilabs-gpulnx001",
                "docker stop remote-run"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        }

    ]
}
```

</p>
</details>

**Comment by alexr00** [comment] 2020-06-26 13:50
Duplicate of https://github.com/microsoft/vscode/issues/101022

**Closed** 2020-06-26 13:50 UTC
Labels: *duplicate
