### ISSUE TITLE
Touch screen not supported for Extensions List Pane (left side)

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#9792] opened 2016-07-26 15:43 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Click the extensions icon, and in the left it will show all the extensions I've installed
2. But when I want to scroll the extensions list with my touch screen, it doesn't work. (While it works for explorer, search etc.,)

**Comment by joaomoreno** [comment] 2016-07-27 06:19
Duplicate of #9338

**Closed by joaomoreno** 2016-07-27 06:19 UTC
Labels: extensions
