### ISSUE TITLE
Markdown preview breaks when moving the markdown file

### ISSUE THREAD

**Issue by herecydev** [Microsoft/vscode#23655] opened 2017-03-30 09:01 UTC
Whilst editing a markdown with the preview (side-by-side), moving the markdown file caused the preview to lock, so further updates to the markdown file are no longer reflected in the preview. Moving the markdown file back to the original location allows the preview to work again.

- VSCode Version: 1.10.2
- OS Version: Windows 10 x64 Build 10586.839

Steps to Reproduce:

1. Open markdown file
2. Ctrl+K V
3. Move file to subfolder
4. Begin modifying the markdown file
5. Observe that changes are not reflected

**Comment by mjbvz** [comment] 2017-04-03 17:24
Thanks. This sounds like a duplicate of #12033

**Closed by mjbvz** 2017-04-03 17:24 UTC
Labels: duplicate, markdown
