### ISSUE TITLE
VSCode will not stop on breakpoints when first node prcess forks a second

### ISSUE THREAD

**Issue by eljamaki01** [Microsoft/vscode#2576] opened 2016-01-31 02:45 UTC
The first issue is that there is some conflict error when you do the following from your app.js file and hit F5 to debug:

var cp = require('child_process');
var node2 = cp.fork('./app_FORK.js');

Error: listen EADDRINUSE :::15838
    at Object.exports._errnoException (util.js:856:11)

I had the same issue with VS Community, so I did the following there and it worked:
var node2 = cp.fork('./app_FORK.js', [], { execArgv: ['--debug=5859'] });

However, in VS Code, it does not seem to work. I place breakpoints, or try to attach after launching node from the command line and it errors out.

**Comment by weinand** [comment] 2016-02-02 15:57
@eljamaki01 the first issue is not a VS Code issue but the expected behaviour of the fork operation: the forked process cannot listen on the same port.

The second issue I do not fully understand: you fork the node process in debug mode listening on port 5859. Then I assume you try to attach from VS Code by using an 'attach' launch config for port 5859.

I do not understand why you are "launching node" and it what way "it" (node?) errors out. SOme more details would help. Thanks.

**Comment by eljamaki01** [comment] 2016-02-02 16:52
Ok, here is a small sample you can repro it with. Place a breakpoint on line 13 in server.js. Note, if you comment out in the app_FORK.js file both process.send() calls it will break in server.js. Try this - only comment out the first process.send(). You can break, until the timer goes off and then it will no longer break. Obviously, to try out, you open a browser to "http://localhost:3000/". You also need to do an npm install in that directory to first get express installed. Here are the files.

// server.js
var express = require('express');
var cp = require('child_process');
var app = express();

var node2 = cp.fork('./app_FORK.js', [], { execArgv: ['--debug=5859'] });

node2.on('message', function (m) {
	console.log('PARENT got message:', m);
});
node2.send({ hello: 'Forked world' });

app.get('/', function (req, res) {
  console.log('Send message on get request');
  res.send('Hello VS Code!');
});

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function () {
	console.log('Express server listening on port ' + server.address().port);
});

// app_FORK.js
process.send({ msg: 'FORK_RUNNING' });

var backgroundWorker = setInterval(function () {
	console.log('Do some work');
    process.send({ msg: 'Did the work' });
}, 1 * 60 * 1000);

// package.json
{
  "name": "NewsWatcher",
  "version": "0.0.0",
  "description": "NewsWatcher",
  "main": "server.js",
  "author": {
    "name": "yourname",
    "email": ""
  },
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.13.4"
  }
}

**Comment by weinand** [comment] 2016-02-02 18:06
@eljamaki01 thanks a lot for the sample. I believe that I understand your problem now.

Probably your expectation is that a single VS Code can debug both processes. But this is not yet the case (see https://github.com/Microsoft/vscode/issues/865). VS Code can only attach to a single node process. But you can create multiple VS Code windows and each can have its own debugger session connecting to another node process.

The current problem is: VS Code does not allow you to open the same project folder twice. So in your case you have two process but their code is living in a single folder.

I could work around this limitation by creating a sub-folder 'worker' and moving the app_FORK.js file into it (and changing the path in server.js accordingly).
Then I created another VS Code window and opened the 'worker' folder with it.
Then I created an 'attach' launch config and changed the port to 5859.

After launching the server.js in the first window and continuing over the 'fork' I attached the second debugger to the forked node process.
With this setup I was able to debug two processes simultaneously:

![2016-02-02 18-59-42](https://cloud.githubusercontent.com/assets/1898161/12759160/f785fe98-c9df-11e5-9bc3-e8ed04fb8b62.png)

**Comment by eljamaki01** [comment] 2016-02-02 18:27
That is cool that you can attach to the second process.
But, tell me if you can break on line 13 of the first process!
I cannot, even after making your change.

**Comment by eljamaki01** [comment] 2016-02-02 18:34
And just to reiterate, if I comment out the process.send() lines in the app_FORK.js file, I can break on line 13!

**Comment by weinand** [comment] 2016-02-02 23:22
@eljamaki01 Yes, I can easily break on line 13 of the server.js process on OS X.

On Windows the server.js process gets an ECONNRESET error on the debugger connection as soon as I hit the localhost:3000 address in the browser. This terminates the debug session and prevents the breakpoint from being hit. This ECONNRESET exception only occurs if there is an "node2.on('message..." handler installed. If I comment out the handler the breakpoint is hit.

Since I could reproduce the same behaviour with node-inspector, this problem is a node problem and independent from VS Code, hence I will close this issue.

**Closed by weinand** 2016-02-02 23:22 UTC
Labels: debug, question
