### ISSUE TITLE
Avoid 3x file size memory pressure when resolving file contents

### ISSUE THREAD

**Issue by freezestudio** [Microsoft/vscode#1117] opened 2015-12-09 04:24 UTC
open a file size 96935KB error:

Visual Studio Code has crashed
We are sorry for the inconvenience! Please restart Visual Studio Code.

**Comment by alexandrudima** [comment] 2015-12-09 08:05
@freezestudio Can you please share the file with us?

**Comment by freezestudio** [comment] 2015-12-09 12:21
1.setup:NTVS 1.1 VS 2015.msi
2.update npm cache
3.file here: X:\Users\xxx\AppData\Local\Microsoft\Node.js Tools\NpmCache\all_packages.json

**Comment by alexandrudima** [comment] 2015-12-09 12:51
@freezestudio I would really appreciate if you could share the actual file (it would save me quite some time). You can zip it up and drag&drop it in a comment.

From the size (96MB) I think it is very close to our hard stop.

@bpasero Do you remember what our hard stop size is?

**Comment by bpasero** [comment] 2015-12-09 12:56
@alexandrudima MAX_FILE_SIZE = 100 * 1024 * 1024

**Comment by freezestudio** [comment] 2015-12-09 13:00
zip it : size:17223kb 
I am sorry, Upload unsuccessful

**Comment by freezestudio** [comment] 2015-12-09 13:13
![all_packages zip 002](https://cloud.githubusercontent.com/assets/5157556/11686126/6d02f52e-9eb9-11e5-8b19-157a55ec6060.png)

![all_packages zip 001](https://cloud.githubusercontent.com/assets/5157556/11686133/78239224-9eb9-11e5-93d6-5c4f8b795fa1.png)

use 7z

**Comment by freezestudio** [comment] 2015-12-09 13:16
all_packages.zip.001.png --> zip 1  : all_packages.zip.001
all_packages.zip.oo1.png --> zip 2 : all_packages.zip.002

use 7z

**Comment by alexandrudima** [comment] 2015-12-09 14:30
@freezestudio Thank you! Got the file! You are awesome! :sunny:

**Comment by alexandrudima** [comment] 2015-12-09 14:53
@bpasero I can reproduce.

It crashes 4 out of 5 times for me on windows already here: https://github.com/Microsoft/vscode/blob/89c09866cdf3d6c9b73dbb25d9a008d3e5b2dd47/src/vs/workbench/services/files/node/fileService.ts#L427

I think we do the following:
* read the entire file in memory as a NodeBuffer (minimum 100MB)
* convert it to a string according to encoding [<--- crashes OOM]

Maybe the code can be improved to be more "stream-ish", i.e. read a chunk, convert a chunk, etc.

Until such a "stream-ish" implementation we need to reduce the MAX_FILE_SIZE number.

I am also not sure what changed since last I tested a few months ago when I was able to consistently open 110MB files that lead to the 100MB number as a hard limit in the first place.

**Comment by bpasero** [comment] 2015-12-10 08:44
I think we are even paying the memory price 3 times. Once in the buffer from reading the file, once in the string we assign to the content object and once during decode. Maybe a better way would be to read the file as stream and then pipe it through the decode method into the string.

**Comment by alexandrudima** [comment] 2015-12-10 09:11
@bpasero :+1: That would be awesome!

**Closed** 2015-12-21 07:33 UTC
Labels: bug, freeze-slow-crash, important

**Comment by aeschli** [comment] 2016-01-29 14:14
I verified that the attached file can not be opened anymore due to lowering of the maximum file size.
@alexandrudima Can you have a look at @bpasero changes in the second change set?
