### ISSUE TITLE
Support for object type aliases folding

### ISSUE THREAD

**Issue by ialexi-bl** [microsoft/vscode#95620] opened 2020-04-19 03:43 UTC
For now there is no indicator to fold object type aliases like this one

![image](https://user-images.githubusercontent.com/44489753/79678711-9dca7e00-8241-11ea-9417-34a608bd22cd.png)

It is quite annoying, especially when they are big and nested. It is also hard to manage large union types:

![image](https://user-images.githubusercontent.com/44489753/79678732-c9e5ff00-8241-11ea-8e44-4058fe68f20a.png)

I would generally expect to have an ability to fold the whole union type. Although I understand that apart from objects there may also be primitives. So folding only objects would already be nice.

There is an option to use `// #region` and `// #endregion` to fold these groups, but vscode has support for lots of typescript features by default, so I wonder why folding type aliases is not included.

**Comment by mjbvz** [comment] 2020-04-20 04:19
Duplicate of #95577

**Closed by mjbvz** 2020-04-20 04:19 UTC
