### ISSUE TITLE
Should collapse xml elements

### ISSUE THREAD

**Issue by kutyel** [Microsoft/vscode#350] opened 2015-11-20 14:11 UTC
Right now it is not possible to collapse the xml elements in the editor.

![code_xml](https://cloud.githubusercontent.com/assets/5127501/11301612/ca8c46f8-8f98-11e5-80d3-685bae4abb78.png)

**Comment by matt-diehl** [comment] 2015-11-20 15:16
This is on the roadmap (code folding) - 

https://github.com/Microsoft/vscode/wiki/Roadmap

**Comment by glen-84** [comment] 2015-11-22 18:29
Duplicate of #105?

**Comment by alexandrudima** [comment] 2015-11-24 15:25
Indeed, let's track this in #105

**Closed by alexandrudima** 2015-11-24 15:25 UTC
Labels: feature request
