### ISSUE TITLE
Setting extensionHomePath does not install extensions into there

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#9176] opened 2016-07-13 06:56 UTC
When I set the `extensionHomePath` from the command line and install extensions, I do not find the extension in that location I specified.

**Comment by joaomoreno** [comment] 2016-07-13 07:12
@bpasero Is this a duplicate of #7505?

**Comment by bpasero** [comment] 2016-07-13 07:24
@joaomoreno not sure, when I tried I created all the folders before hand.

**Comment by joaomoreno** [comment] 2016-07-13 15:16
Duplicate of #7505

**Closed by joaomoreno** 2016-07-13 15:16 UTC
Labels: bug
