### ISSUE TITLE
[YAML] Wrong syntax highliting of lines containing # inside a multiline content

### ISSUE THREAD

**Issue by sarod** [Microsoft/vscode#50107] opened 2018-05-18 14:32 UTC
Issue Type: <b>Bug</b>

In a YAML document when a multiline value contains a line that contains a "#" vscode highlits the line as a comment instead of keeping it as a value.

For instance:
When creating a YAML document like this:
```yaml
# I'm a comment
myMarkdownProperty:  |
  # I'm a markdown title
  The line above should not be cosnidered a comment
```
vscode highlights "# I'm a markdown title":
![screenshot from 2018-05-18 16-26-23](https://user-images.githubusercontent.com/8543138/40240236-66ccab10-5ab8-11e8-8715-b66fc09e5ef7.png)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.13.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2546)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.61GB (0.54GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
html-css-class-completion|Zig|1.17.1
path-intellisense|chr|1.4.2
typescript|cod|0.9.0
web|cod|0.9.0
vscode-eslint|dba|1.4.9
tslint|eg2|1.0.29
vscode-test-view|eti|0.2.3
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
rainbow-csv|mec|0.2.1
debugger-for-chrome|msj|4.4.3
language-liquid|nei|0.0.3
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.12
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by aeschli** [comment] 2018-05-22 08:59
duplicate of https://github.com/textmate/yaml.tmbundle/issues/17

**Closed by aeschli** 2018-05-22 08:59 UTC
