### ISSUE TITLE
Introducing customized extension groups based on project type in vscode.

### ISSUE THREAD

**Issue by Psp29onetwo** [microsoft/vscode#139747] opened 2021-12-25 17:13 UTC
I've got an idea to group install extensions based on user preference or based on project and language specifications, by doing this users can quickly enable and disable extensions at their convenience and not have to disable one by one and enable the same which saves time and computer resources too like RAM consumed by extension which is not required for that specific project.

for example: If I'm working on a Django project then the user may group the required extensions for the project and by binding these extensions user can just disable that bundled group of extensions when not required by this it saved amount of computer resources that are not required and free the ram which is consumed by extension which is not required.

**Comment by IllusionMH** [comment] 2021-12-27 05:11
As bit different appoach described in this issue, however goal is duplicate of existing requests: eg #116740, #40239, #39272

**Comment by Psp29onetwo** [comment] 2021-12-29 05:58
> As bit different approach described in this issue, however, the goal is duplicate of existing requests: eg #116740, #40239, #39272

The thread [#39](https://github.com/microsoft/vscode/issues/39272) is more sophisticated.

**Closed** 2022-01-03 14:46 UTC
Labels: *duplicate
