### ISSUE TITLE
Crash while searching 'markdown' extension

### ISSUE THREAD

**Issue by kintaat** [Microsoft/vscode#22641] opened 2017-03-15 02:45 UTC
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Ctrl+Shift+X
2. Type 'markdown'
3. Scroll down
4. Crash

**Comment by joaomoreno** [comment] 2017-03-20 11:46
Can you share more details about the crash? Is there any error message? Screenshot?

**Comment by kintaat** [comment] 2017-03-22 04:39
Unfortunately I can't see any error message. Here is the screenshot.
![opt_vscode_crash](https://cloud.githubusercontent.com/assets/6628575/24182083/36f09f56-0efa-11e7-831a-89857291f2e4.gif)
Probably it's  about loading icons of extensions, because it works well if it doesn't show icons. 
![opt_vscode_well](https://cloud.githubusercontent.com/assets/6628575/24182253/7eeec8c2-0efb-11e7-835d-0a34bd0493d4.gif)

**Comment by joaomoreno** [comment] 2017-03-23 16:40
@kintaat Can you run with `code --verbose` and give us the crash error, once it happens in the Terminal?

@bpasero Have you seen anything like this?

**Comment by bpasero** [comment] 2017-03-24 07:23
No :-/

**Comment by kintaat** [comment] 2017-03-27 06:55
@joaomoreno The output in Terminal, from start to crash
```
Gtk-Message: Failed to load module "canberra-gtk-module"
[12436:0327/065125:ERROR:bus.cc(434)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[12436:0327/065125:WARNING:audio_manager.cc(314)] Multiple instances of AudioManager detected
[12436:0327/065125:WARNING:audio_manager.cc(275)] Multiple instances of AudioManager detected
[main 6:51:25 AM] Starting VS Code in verbose mode
[main 6:51:25 AM] from: /usr/share/code/resources/app
[main 6:51:25 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[12436:0327/065126:INFO:CONSOLE(38)] "Error: libxkbfile.so.1: cannot open shared object file: No such file or directory", source: /usr/share/code/resources/app/node_modules/native-keymap/index.js (38)
[main 6:51:27 AM] IPC#vscode-workbenchLoaded
[12436:0327/065127:INFO:CONSOLE(31)] "Overwriting extension <<.m>> to now point to mime <<text/x-matlab>>", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (31)
[main 6:51:27 AM] IPC#vscode:broadcast null vscode:changeColorTheme vs-dark vscode-theme-defaults-themes-dark_plus-json
[12436:0327/065128:INFO:CONSOLE(51)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (51)
[12436:0327/065128:INFO:CONSOLE(51)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (51)
[12436:0327/065128:INFO:CONSOLE(51)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (51)
[12436:0327/065128:INFO:CONSOLE(51)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (51)
[12436:0327/065128:INFO:CONSOLE(51)] "%c[IPC Library: Watcher]", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (51)
Failed to generate minidump.
Failed to generate minidump.
```

**Comment by joaomoreno** [comment] 2017-03-27 08:41
@alexandrudima See above:

```
[12436:0327/065126:INFO:CONSOLE(38)] "Error: libxkbfile.so.1: cannot open shared object file: No such file or directory", source: /usr/share/code/resources/app/node_modules/native-keymap/index.js (38)
```

**Comment by alexandrudima** [comment] 2017-03-27 08:43
Sorry, that error does not cause the crash. The code is written in such a way that it will work perfectly fine if the native code fails to load. See all the console log after it and also the fact that pressing `ctrl+shift+x` succeeds.

**Comment by joaomoreno** [comment] 2017-03-27 08:48
@kintaat Can you reproduce when running with `code --disable-gpu`?

**Comment by kintaat** [comment] 2017-03-28 10:57
@joaomoreno Yes, it crashes too.

**Comment by joaomoreno** [comment] 2017-03-28 12:41
Can you find anything interesting in your system logs?

**Comment by kintaat** [comment] 2017-03-30 06:01
Actually I run vscode in Docker. But if I run it in host, it doesn't meet this issue. In other words, the crash isn't existed in host.

**Comment by kintaat** [comment] 2017-03-30 06:21
I tried install vscode in Docker with ubuntu:16.04 image, and it crashes again. Is it something relative to Docker?

**Comment by joaomoreno** [comment] 2017-03-30 07:38
Yeah definitely could be! Since we don't officially support running Code inside Docker I'll close the issue. I'd be interested to know about the fix, though.

**Closed by joaomoreno** 2017-03-30 07:38 UTC
Labels: needs more info

**Comment by kintaat** [comment] 2017-03-31 06:28
@joaomoreno I may know about the reason. It is caused by limited space of /dev/shm in docker.

After installing ```libxkbfile-dev``` and running vscode with ```code --verbose```,  I found an warning output
```
[8370:0331/054225:WARNING:host_discardable_shared_memory_manager.cc(132)] Less than 64MB of free space in temporary directory for shared memory files: 57
```
```host_discardable_shared_memory_manager.cc``` is source file of chromium and it detects space of /dev/shm
https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/content/common/host_discardable_shared_memory_manager.cc#132
https://chromium.googlesource.com/chromium/chromium/+/master/base/file_util_posix.cc#1003

Docker allocates only 64MB for /dev/shm in default,  so I try to run docker image with option ```--shm-size 1G```. Then vscode doesn't crash anymore, no matter ```libxkbfile-dev``` is installed or not.

**Comment by joaomoreno** [comment] 2017-03-31 06:32
Thanks for letting us know, great job! 👍
