### ISSUE TITLE
fail to save the created file when using 'code' in terminal

### ISSUE THREAD

**Issue by X-Chen97** [microsoft/vscode#114052] opened 2021-01-08 19:34 UTC
Issue Type: <b>Bug</b>

Hi,

I used 'code' command in terminal to create a new .ipynb file(e.g. 'file_new.ipynb'). After I finished my coding in 'file_new.ipynb', I failed to save it. Instead, it pop out that "save as Untitle.ipynb". Also, when I continue to save it as "file_new.ipynb", that's to say, I replaced the original "file_new.ipynb", I found that all my codes in "file_new.ipynb" were gone!! And record showed that "file_new.ipynb" was only modified yesterday, when I first created this file. Hopefully this could be fixed. Thank you!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 5f832398-3f92-42fd-842b-82b5d88b9f93|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.38.0
MagicPython|mag|1.1.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
java|red|0.73.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt875:30241730

```

</details>

**Comment by meganrogge** [comment] 2021-01-08 21:04
Hi what did you enter into the terminal exactly?

**Comment by X-Chen97** [comment] 2021-01-08 21:19
code file_new.ipynb

Megan Rogge <notifications@github.com> 于 2021年1月8日周五 下午1:04写道：

**Comment by meganrogge** [comment] 2021-01-11 16:07
I can't reproduce this issue. Please provide a [gif](https://gifcap.dev/)

**Comment by X-Chen97** [comment] 2021-01-12 05:24
For example I create a new file: visualize.ipynb
![image](https://user-images.githubusercontent.com/54193597/104272030-1bc65900-5451-11eb-9526-8fc3f3c08062.png)
Then it ask me whether to save this new file. I click save.
![image](https://user-images.githubusercontent.com/54193597/104272102-3ef10880-5451-11eb-82bf-66c16b122fcb.png)
Also the file shows up in my folder
![image](https://user-images.githubusercontent.com/54193597/104272769-b4a9a400-5452-11eb-8242-66f3c973fdeb.png)
Then I edit in it. It becomes unsaved state
![image](https://user-images.githubusercontent.com/54193597/104272142-5f20c780-5451-11eb-8c6b-7ec463910dd6.png)
Then I want to save it. i use command+s on my mac. It becomes 'untitled.ipynb'
![image](https://user-images.githubusercontent.com/54193597/104272703-90e65e00-5452-11eb-87e8-48cf78b02880.png)
I click save and there are two files now
![image](https://user-images.githubusercontent.com/54193597/104272812-cdb25500-5452-11eb-936f-77e1768cadb0.png)
visualize.ipynb is empty
![image](https://user-images.githubusercontent.com/54193597/104272883-f33f5e80-5452-11eb-923e-c0b0f6627dfb.png)
If I change the name 'untitle' to 'visualize' when I save the new file, it says 'want to replace?'. If I replace, the newly saved 'visualize.ipynb' will be empty.

**Comment by X-Chen97** [comment] 2021-01-12 05:32
BTW, if i create the file 'visualize.ipynb' using 'touch visualize.ipynb' and then open it using 'code visualize.ipynb', everything goes well. It is well saved after using command+s(no window pops out).

**Comment by bpasero** [comment] 2021-05-21 11:38
Duplicate of https://github.com/microsoft/vscode/issues/121974

**Comment by bpasero** [comment] 2021-08-10 09:01
@X-Chen97 can you try this scenario again with today's insider build: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2021-08-17 11:26 UTC
Labels: bug, needs more info, terminal, workbench-untitled-editors
