### ISSUE TITLE
Breadcrumb menu shows and disappears immediately after clicking, when the file opened is an image 

### ISSUE THREAD

**Issue by blurHY** [microsoft/vscode#101939] opened 2020-07-08 17:50 UTC
- VSCode Version: 1.47.0-insider  d5e9aa0227e057a60c82568bf31c04730dc15dcd
- OS Version: kubuntu 19.10, linux 5.3.0

Steps to Reproduce:

1. Open an image file (png or jpg, I've tested)
2. Click a breadcrumb button

Does this issue occur when all extensions are disabled?: Yes

This bug doesn't happen on other files.

**Comment by mjbvz** [comment] 2020-07-08 18:57
Duplicate of #101181

**Closed by mjbvz** 2020-07-08 18:57 UTC
