### ISSUE TITLE
Import path intellisense is no longer working used to work before.

### ISSUE THREAD

**Issue by dragfire** [Microsoft/vscode#24810] opened 2017-04-15 04:06 UTC
- VSCode Version: 1.11.2
- OS Version: Mac OSX Captain

Steps to Reproduce:
After the recent update, `import` path intellisense is no longer working, used to work amazing with no extensions.  
In my react project, it even used to suggest `packages` inside `node_modules`. 

Appreciate any help on this.

**Comment by mjbvz** [comment] 2017-04-15 18:37
Duplicate of #23962

This is caused by the new settings for quickSuggestions that disable them in strings by default. Please see https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416 for a workaround

**Closed by mjbvz** 2017-04-15 18:37 UTC
