### ISSUE TITLE
Feature request: better positioning for debug actions widget

### ISSUE THREAD

**Issue by knownasilya** [Microsoft/vscode#40921] opened 2017-12-28 22:55 UTC
Currently I'm always fighting with the debug actions widget because it blocks important real estate (tabs, left panel top controls). I can drag it left and right, but no matter where I put it it's always blocking something important.

Some ideas of what can be done:

- Allow it to be draggable to the bottom above the status bar.
- Sticky it to the top of the left panel, so it pushes the panel down. If the panel is hidden, it could float like it does now.
- Hide the faded debug tools in the widget when they are disabled, then it can be over the right side tab controls without covering actual tabs.
- Something else?

**Comment by mattacosta** [comment] 2017-12-28 23:11
Duplicate of #2513. Add your suggestions there and be sure to give the first post a thumbs up reaction.

**Closed** 2018-01-03 10:24 UTC
Labels: *duplicate, debug
