### ISSUE TITLE
Scrollable region for non-text outputs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#209156] opened 2024-03-29 21:07 UTC
When inspecting data frames, the output is not rendered in a scrollable region, making the whole notebook hard to navigate

![image](https://github.com/microsoft/vscode/assets/876920/0f8fb049-c6a6-4cc9-9a23-69899d959f24)

**Comment by shtratos** [comment] 2024-06-22 16:11
It'd be amazing if we could have a rich and adaptable viewer for dataframes since they are so ubiquitous.
(not as heavyweight as DataWrangler though - it disrupts the context too much and changes VSCode layout).

The very particular pain I'm very frequently running into:
- I get the dataframe in the output of a cell - I want to look at the data to either explore it or to make sure it has the right values and columns.
- the frame is too large to fit, so some columns and rows are elided `...`
- now I have to go back and either add `df.head()` to reduce number of rows or `df.columns` to see all the columns, or do `df.head().T` to see all columns in a list with some values.

**Comment by shtratos** [comment] 2024-06-22 16:16
Even cooler would be to also have an easy way to reference the dataframes in notebook as context to Copilot Chat for "how do I join/pivot/aggregate/visualise?" types of questions.

**Comment by rebornix** [comment] 2024-06-24 22:24
@shtratos thanks for the feedbacks!

> Even cooler would be to also have an easy way to reference the dataframes in notebook as context to Copilot Chat for "how do I join/pivot/aggregate/visualise?" types of questions.

Currently we embed the variable summaries in the chat context so you can ask such questions, say you have a data frame `df`, you can ask `how do I join/pivot/aggregate/visualise the data frame` and Copilot is able to generate code with the right data frame reference. Let me know if it works as expected for you.

**Comment by amunger** [comment] 2024-11-22 23:12
duplicate of https://github.com/microsoft/vscode/issues/190426

**Closed by amunger** 2024-11-22 23:12 UTC
Labels: papercut :drop_of_blood:, notebook-output
