### ISSUE TITLE
ES6 yield keyword doesn't have blue color

### ISSUE THREAD

**Issue by ayeressian** [Microsoft/vscode#4407] opened 2016-03-18 09:08 UTC
- VSCode Version: 0.10.11
- OS Version: 10.11.3

Steps to Reproduce:

1. Open a js file in vs code.
2. Type yield keyword.
Notice the color of the text is black. Instead of blue.

**Comment by aeschli** [comment] 2016-03-18 10:53
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/29

**Closed by aeschli** 2016-03-18 10:53 UTC
