### ISSUE TITLE
`code --install-extension` hangs forever on macOS

### ISSUE THREAD

**Issue by knatten** [Microsoft/vscode#32689] opened 2017-08-17 05:32 UTC
- VSCode Version: 1.15.1 41abd21afdf7424c89319ee7cb0445cc6f376959
- OS Version: macOS 10.10.5 (14F2511)

Steps to Reproduce:

`code --install-extension vscodevim.vim`

Hangs at 
```
$ code --install-extension vscodevim.vim
Found 'vscodevim.vim' in the marketplace.
Installing...
(node:75765) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:75765) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also happens for other plugins, like `iGN97.fuse-vscode`

I'm able to install plugins just fine from the GUI.

**Comment by jgsqware** [comment] 2017-08-17 12:28
Go the same of `Shan.code-settings-sync`

**Comment by joaomoreno** [comment] 2017-08-18 07:06
Are you behind a proxy?

**Comment by decoomanj** [comment] 2017-08-18 07:55
Same as this: https://github.com/Microsoft/vscode/issues/32381

**Comment by joaomoreno** [comment] 2017-08-18 09:28
Thanks @decoomanj. Duplicate of #32381

**Closed by joaomoreno** 2017-08-18 09:28 UTC
Labels: extensions, needs more info, new release
