### ISSUE TITLE
Ignore comments while searching in file/s.

### ISSUE THREAD

**Issue by Roinoss** [microsoft/vscode#140948] opened 2022-01-19 01:01 UTC
Three state button in current search feature to look outside or in comments (depending on filetype, for example in:
` /* */, //, /** */, #, <!-- -->`
).

**Comment by IllusionMH** [comment] 2022-01-19 01:12
/duplicate of #11688 (which looks more like search in editor) and #140294 (for search in files, see https://github.com/microsoft/vscode/issues/140294#issuecomment-1007796325 for details)

**Closed** 2022-01-19 01:13 UTC
Labels: *duplicate
