### ISSUE TITLE
Problem with autosuggestion panel when using snippets

### ISSUE THREAD

**Issue by ccpu** [microsoft/vscode#140283] opened 2022-01-07 16:01 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: windows 10

Steps to Reproduce:

1. disable all extinctions
2. install "JavaScript (ES6) code snippets" extension
3. type `imp` press tab
4. type `fs`
5. press `backspace`  and Open brace `{}`
6. press Ctrl+Space

As no suggestions are available at this point, autosuggest should display the top item in the list, but it's still stocking on `imp`.

The problem begins to appear after updating vscode to the latest version.

![Animation](https://user-images.githubusercontent.com/4041334/148570665-2891f50c-2d8e-44fb-8a1c-2e10e093b069.gif)

Besides brackets, I have seen this problem in other places such as auto-completing scope imports, for example here i am importing material UI icons with `imui` snippet key:

![Animation](https://user-images.githubusercontent.com/4041334/148573706-79e6fc69-42e2-4e9e-9d2b-29537a54acd5.gif)

**Comment by jrieken** [comment] 2022-01-10 08:35
/duplicate of https://github.com/microsoft/vscode/issues/136864

**Closed** 2022-01-10 08:35 UTC
Labels: *duplicate
