### ISSUE TITLE
Incorrect behavior with `Occurrences Highlight` in template literals

### ISSUE THREAD

**Issue by JonathanWolfe** [microsoft/vscode#119359] opened 2021-03-19 20:47 UTC
Issue Type: <b>Bug</b>

1. Paste the below code into a window:
```
const gql = `
  enum DateFields {
    approvedDate
    expirationDate
    firstOrder
  }

  enum Status {
    REQUESTED
    APPROVED
    ACTIVE
    COMPLETED
  }

  enum DosageUnit {
    GRAM
    TON
  } 
`
```

2. Move the cursor to the end of the line inside any of the curly braces

You'll notice that with `Occurrences Highlight` turned on, ALL blocks get fully highlighted, when technically nothing should be highlighted at all since I'm not inside a token to search for occurences for.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|--crash-reporter-id fd41cef7-524e-47cb-93a7-66e02ded0e39|
|Screen Reader|no|
|VM|17%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2021-03-19 22:42
Duplicate of https://github.com/microsoft/TypeScript/issues/43292

**Closed by mjbvz** 2021-03-19 22:42 UTC
Labels: new release
