### ISSUE TITLE
VS Code High Memory Utilization

### ISSUE THREAD

**Issue by dlokman** [Microsoft/vscode#31167] opened 2017-07-20 23:48 UTC
- VSCode Version: 1.14.1
- OS Version: windows 7

Steps to Reproduce:

1. Open up 5 VS Code Windows  for 5 Folders(non-git repositories. just regular visual studio folders)
2. Folder has node_modules as 1 of the folders within it (*** may be whats causing it)
2. Do nothing. Just observe the Taks Schedule Memory
3- Each VsCode.exe  takes around 700MB. After leaving it running for 20 min. 2 VS Code instances are up to 1 Gig.
4- The only thing that makes sense is that i also opened node_modules. I don't think VsCode extensions would have caused it. I'm only using the popular most downloaded VS Code extensions

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-07-21 08:40
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dlokman** [comment] 2017-07-21 12:18
Hmm, it got resolved. I just opened the folder 1 level down in the hierarchy so it won't have to open node_modules.

**Comment by dlokman** [comment] 2017-08-17 22:48
I tested this with 2 different laptops. Looks like opening a folder in VSCode that contains node_modules folder makes Vs Code consume more CPU memory (12% more). Opening a sub folder is better but then i can't access angular-cli.json from VsCode folder explorer. Can someone please verify and look into it? Thanks

**Comment by bpasero** [comment] 2017-11-15 17:52
Still happening?

**Comment by dlokman** [comment] 2017-11-15 19:28
Not sure. I just open the folder 1 level down that doesn’t have node_modules in it

**Comment by Iliyass** [comment] 2017-12-14 08:40
@bpasero still uses a lot of memory for such a tiny nodejs project

**Comment by clydeburgos** [comment] 2018-02-26 02:31
@dlokman Hi Bro, just wanna send my appreciation, Going inside the directory a bit lower made the issue gone, from 1.2 GIG consumption of memory to 200MB. Basically targeting directly to the src to escape the node_module level made the fix.  Cheers man!

**Comment by bpasero** [comment] 2018-09-10 16:30
Closing, there is no actionable item in this issue. For people seeing performance issues, please follow our guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Closed by bpasero** 2018-09-10 16:30 UTC
Labels: freeze-slow-crash
