### ISSUE TITLE
Mapped SharePoint Doc Lib - "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

### ISSUE THREAD

**Issue by spjeff** [Microsoft/vscode#20061] opened 2017-02-06 16:48 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|0.7.3|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|1.0.2|
|prettify-json|mohsen1|0.0.3|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.5.1|
|vscode-icons|robertohuertasm|7.1.2|

---

Steps to Reproduce:

1.  From Windows 10 client, map a network drive to a SharePoint 2013 document library   (NET USE Z: HTTP://PORTAL/SITES/TEST)
2. Change directory to (CD Z:\)
3.  Launch VSCode (CODE .)
4.  Error will appear "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."
5.  Screenshot here:
![2017-02-06_10-43-19](https://cloud.githubusercontent.com/assets/5648223/22656612/880e301a-ec59-11e6-9dc7-cbfb56bad956.png)

I suspect this has to do with the WebClient folder redirection over HTTP and potentially SharePoint blocked file types (JSON not allowed).    Ideally was looking for any way to suppress the TS error blinking very 3 seconds constantly.

Similar to https://github.com/Microsoft/vscode/issues/9215  but only occurs with a SharePoint mapped drive letter.  Local folders OK.

Thank you!

---UDPATE---

I performed a fresh new install and the issue no longer occurs.   This may have been caused by either (1) install VSCode over Chocolatey or (2) a NPM Global installed different typescript version.

1) Uninstalled VSCode from Control Panel
2) Deleted "npm" and "npm_cache" folders at "c:\Users\User\AppData\Roaming\"
3) Ran "cuninst visualstudiocode" to remove from Chocoately package manager
4) reboot
5) Install VSCode direct from website
6) Test and works OK now editing JS files from mapped SharePoint drive letter

**Comment by mjbvz** [comment] 2017-02-06 18:31
Thanks for the report. This looks like a duplicate of a bug we are tracking on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/13874

We're coordinating the the TypeScript to fix this. Closing as upstream

**Closed by mjbvz** 2017-02-06 18:31 UTC
Labels: bug, typescript, upstream
