### ISSUE TITLE
Insiders will not load editors when not in a folder workspace

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#15600] opened 2016-11-17 00:35 UTC
- VSCode Version: Code 1.8.0-insiders installed on 11/16/2016 -- Report issue link not working so I've screenshotted the about dialog:
![image](https://cloud.githubusercontent.com/assets/494055/20371415/8a1e8664-ac19-11e6-9126-833e083e28d5.png)

- OS Version: Windows_NT ia32 10.0.14965
- Extensions (running with --disable-extensions)

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.3|

---

Steps to Reproduce:

1. Open Insiders (not running a workspace folder)
2. No editor or anything else loads

![image](https://cloud.githubusercontent.com/assets/494055/20371510/2d32603c-ac1a-11e6-9aa6-9c30732a921e.png)

Opening a folder seems to work around the problem

1. Open Folder
2. Editors show up and life continues as usual
3. Close Folder
4. No editors show up again

Yesterday I added this to my user settings file:

```
"files.hotExit": true,
```

However, removing that does not seem to fix the problem.

On the plus side, hot exit seems to work when the folder is loaded.

**Comment by ramya-rao-a** [comment] 2016-11-17 01:02
@chrmarti Duplicate of #15594 ?

**Comment by ramya-rao-a** [comment] 2016-11-17 01:21
The new insiders build has the fix. Please update.

**Closed by ramya-rao-a** 2016-11-17 01:21 UTC

**Comment by dilijev** [comment] 2016-11-17 22:17
Thanks!
