### ISSUE TITLE
Option for Search to filter comments

### ISSUE THREAD

**Issue by hilloinen** [microsoft/vscode#225928] opened 2024-08-18 19:24 UTC
Visual Studio Code is well aware when some text is inside a comment since it displays such text with a different color - at least with common programming languages.

It would be great if the the search had an option button similar to _"Match Case"_ and _"Match Whole Word"_ buttons that could be used to filter out matches found in comments. I suggest three modes for such button: 1) inactive/include all (it would function like search now), 2) exclude comments, and 3) include only comments.

**Comment by IllusionMH** [comment] 2024-08-18 22:18
Looks like duplicate of #11688

**Closed** 2024-08-19 18:28 UTC
Labels: *duplicate
