### ISSUE TITLE
VSCode should reopen when machine rebooted for updates

### ISSUE THREAD

**Issue by twpol** [microsoft/vscode#12630] opened 2016-09-26 12:22 UTC
- VSCode Version: 1.5.3
- OS Version: Windows 7 Enterprise 64bit

Steps to Reproduce:
1. Have VSCode open with at least one workspace and open files
2. Restart your computer to apply updates, or simulate with `shutdown /g`

Expected Results: VSCode is reopened with workspaces (all of them) open

Actual Results: No VSCode running

According to my tool, https://james-ross.co.uk/projects/arr, VSCode does not register for being restarted at all. It should register at least for "reboot". This should be a simple thing to fix, although the quality of the restart behaviour will depend on issues like #101 and #12436 and others.

**Comment by ivorhuang** [comment] 2018-03-31 20:45
I'm interested in working on this

**Comment by riptide-dev** [comment] 2018-09-14 15:34
VSCode Version: 1.27.2
OS Version: Windows 10 Pro 64bit

Steps to Reproduce:
1. Have VSCode open with at least one workspace and open files
2. Restart your computer to apply updates, or simulate with shutdown /g
3. Expected Results: VSCode is reopened with workspaces (all of them) open

Expected Results: VSCode is reopened with workspaces (all of them) open
Actual Results: No VSCode running

I was able to repro this in the latest version of VSCode.

**Comment by FrederikBolding** [comment] 2018-10-03 07:30
I can take a crack at this one - However, I am unsure as to how I would use Windows Native API calls within Javascript, I can't find other examples of this in the current codebase.

**Comment by vbraziel** [comment] 2018-10-03 09:42
From what I have read on tech blogs and windows OS documentation, the feature to restart previous running programs is an Operating System feature that uses the registry (windows) or something like /proc in linux to know which programs where open at the time of shutdown.

1. Should this feature continue to be managed by the OS vice VS Code?
2. Does anyone know a pointer to the code that controls the logic for tracking open work spaces?
3. Is there a settings feature already in existence that does this?

I think answers to these questions will help to determine the viability of
1) The feature for VS Code to track both its own running state, the OS running state and 
2) Track open work spaces "event loop" that updates on work space change (i.e., open close).
I know that for this to work though more overhead will be incurred in terms of performance when
opening and closing work spaces because of data being written to disk to make this work.

**Comment by FrederikBolding** [comment] 2018-10-03 11:12
We need to use the `RegisterApplicationRestart` function as described here: https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-registerapplicationrestart and here https://docs.microsoft.com/en-us/windows/desktop/recovery/registering-for-application-restart

However, I am unsure of how to use these from Electron/Javascript as well as where in the codebase to call from.

**Comment by vbraziel** [comment] 2018-10-04 11:57
I scanned through the source this morning. I have to admit I am not that familiar with it yet. I did see a few places that relate to vs code's app state, app history, and win32 calls. It might be worth a deeper look.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dylmye** [comment] 2018-10-18 14:04
Is the [`node-auto-launch`](https://github.com/Teamwork/node-auto-launch) project (or it's source) of any help?

**Comment by kdelorey** [comment] 2019-02-23 21:57
Since work seemed dead, I've gone ahead and started development on this issue. I have a prototype of it working. I'm using the [`RegisterApplicationRestart`](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-registerapplicationrestart) method from a Node extension I developed. Expect a PR soon, after I complete testing.

**Closed** 2019-10-17 10:04 UTC
Labels: *out-of-scope, feature-request, good first issue, help wanted, install-update, windows
