### ISSUE TITLE
always need a restart

### ISSUE THREAD

**Issue by WahidinAji** [microsoft/vscode#176558] opened 2023-03-08 20:16 UTC
Type: <b>Bug</b>

in 3 minutes. the extension need 2 times restart

![image](https://user-images.githubusercontent.com/48281037/223839795-239ed903-e588-4e33-9665-ac47c46076c5.png)

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.19.0-32-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 x 1886)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|13.57GB (7.72GB free)|
|Process Argv|. --crash-reporter-id ce48a0dd-96ba-45ac-8d8b-9bb5befdb170|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
laravel-extra-intellisense|ami|0.6.2
laravel-blade-vscode|ami|2.0.4
laravel-blade-spacer|aus|2.1.3
htmlplay|bia|0.0.10
color-info|bie|0.7.2
vscode-intelephense-client|bme|1.9.5
laravel-goto-view|cod|1.3.8
vscode-mysql-client2|cwe|6.2.4
githistory|don|0.6.20
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
shell-format|fox|7.2.5
copilot|Git|1.77.9225
go|gol|0.38.0
icon-fonts|idl|2.5.4
better-dockerfile-syntax|jef|1.0.2
vscode-phpfmt|kok|1.0.31
inline-parameters|lia|0.2.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
makefile-tools|ms-|0.6.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
phpstorm-snippets|phi|1.1.2
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.5.0
vscode-yaml|red|1.12.1
markdown-preview-enhanced|shd|0.6.8
vscode-blade-formatter|shu|0.20.12
default-keys-windows|smc|0.0.9
vscode-todo-highlight|way|1.0.5
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
funwalk2:30676043
pythonms35:30680984

```

</details>

**Comment by Luisparr14** [comment] 2023-03-08 20:47
Same issue

**Comment by coffenbacher** [comment] 2023-03-08 21:12
Same here, just started this morning. We share copilot, prettier-vscode, and gitgraph extensions.

**Comment by bpasero** [comment] 2023-03-09 04:46
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by WahidinAji** [comment] 2023-03-12 07:23
I've followed those instructions. But, 'till got the same issue

**Comment by WahidinAji** [comment] 2023-03-12 10:53
btw, while I disabled my GitHub Copilot, the issue was solved.  so, I subscribe to copilot for what? 😄😄😄

**Comment by WahidinAji** [comment] 2023-03-13 14:54
even while I wrote notes on `readme.md` the copilot makes my vs code broken -_- 
![image](https://user-images.githubusercontent.com/48281037/224738525-ac05574e-d409-4d0c-a4bb-ca3efee26676.png)

**Comment by deepak1556** [comment] 2023-03-14 14:23
@WahidinAji the steps in https://github.com/microsoft/vscode/issues/176558#issuecomment-1461272742 does not address the crash but will help generate the crash logs. Can you attach those logs in this issue thread, thanks!

**Comment by isidorn** [comment] 2023-03-15 10:58
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this problem when disabling Copilot do let us know and we can reopen this issue. Thank you!

**Closed by isidorn** 2023-03-15 10:58 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host, sandbox
