### ISSUE TITLE
Notebook: Scroll jank on deleting cells

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#108618] opened 2020-10-13 19:06 UTC
Have a long cell (over screen width), then a cell after it. Scroll to bottom of the long cell and try to delete the next cell using the trash icon in the tool bar. Scroll gets janked up to top of the long cell.

**Comment by rebornix** [comment] 2020-10-13 19:18
Good point

**Comment by rebornix** [comment] 2020-11-09 19:54
I'm not able to reproduce this issue with latest Insiders and GitHub Issue Notebook, @JacksonKearl can you provide more details about how to reproduce?

**Comment by JacksonKearl** [comment] 2020-11-09 20:02
Hm, I think the issue as originally opened no longer reproduces, but still finding that if I delete a cell that's somewhat off the screen, either above or below, the entire viewport shifts greatly.

**Comment by JacksonKearl** [comment] 2020-11-09 20:06
![Uploading recording (19).gif…]()

**Comment by JacksonKearl** [comment] 2020-11-09 20:06
![recording (19)](https://user-images.githubusercontent.com/8586769/98590624-f4ea7b80-2283-11eb-96bd-f5f365483258.gif)

**Comment by JacksonKearl** [comment] 2020-11-17 16:10
I think this is actionable but lmk if you need anything.

**Comment by rebornix** [comment] 2021-03-30 20:35
Already fixed in Insiders.

**Closed** 2021-03-30 20:35 UTC
Labels: bug, notebook
