### ISSUE TITLE
Allow to shorten the diff editor title

### ISSUE THREAD

**Issue by shasiru** [microsoft/vscode#110694] opened 2020-11-16 04:33 UTC
Issue Type: <b>Feature Request</b>

When comparing two codes side by side, the order is confusing. 
It takes a considerable amount of time just to realize which file is on the left and which is on the right. 

And the tab title showing comparing files is not helpful at all since it is too long
For example, in tab title;
different file names in same location
.....very/very/very/very/long/path/file1.js <-> .....very/very/very/very/long/path/file2.js
 
or

same file name in different locations
.....very/very/very/very/long/path1/file1.js <-> .....very/very/very/very/long/path2/file1.js

either situations, I find it really frustrating to identify which file is on which side by reading the long URL (title). 

What i propose is to implement the vscode interface to allow the user to add labels with custom titles to each side (when in code comparison). 

So instead of a single long URL like this:
![screenshot](https://user-images.githubusercontent.com/18670119/99212984-6bdac380-27f2-11eb-8124-dfd2fff5a213.jpg)

implement a UI feature like this:
![screenshot2](https://user-images.githubusercontent.com/18670119/99229446-0d264180-2814-11eb-8e56-3b181e27d246.jpg)

to show clearly which file is open on which side and also allow the user to add custom title names to each of comparing file (temporarily - for reference)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

**Comment by ArturoDent** [comment] 2020-11-16 05:59
Related: https://github.com/microsoft/vscode/issues/44916

**Comment by bpasero** [comment] 2020-11-16 06:44
The title reflects the editors, the first name is for the left and the second for the right editor?

**Comment by shasiru** [comment] 2020-11-16 07:59
> The title reflects the editors, the first name is for the left and the second for the right editor?

Yes, you are right. 

But the title is taking too much space thus wasting time realizing which code is in which side.

**Comment by bpasero** [comment] 2020-11-30 13:57
With https://github.com/microsoft/vscode/issues/109224 at least for files in the same folder, the label will be much shorter now:

**Before**
![image](https://user-images.githubusercontent.com/900690/100618579-5306fd80-331c-11eb-907a-193864c52c43.png)

**After**
![image](https://user-images.githubusercontent.com/900690/100618603-58644800-331c-11eb-9c0b-b3056231ba44.png)

**Comment by bpasero** [comment] 2020-11-30 15:42
The UI challenge here is really that we have many settings that enable a `description` to appear besides the main editor label (e.g. when you disable tabs) and we typically put the relative path of the file to the root in there, if we did something like that for diff editors, it would end up like this:

![image](https://user-images.githubusercontent.com/900690/100630511-ea734d00-332a-11eb-96dc-d89297ad3f96.png)

If someone has better ideas how to resolve this, I am all up for making a change.

**Comment by bpasero** [comment] 2020-12-12 09:32
@shasiru yeah I somewhat like that idea, if you want to give it a try through a PR, the change would need to go somewhere here:

https://github.com/microsoft/vscode/blob/8c2a384efa9e9ea4a8186cd9f068f394638b1d19/src/vs/workbench/common/editor/diffEditorInput.ts#L43-L58

Interestingly we have a similar challenge already when you open 2 editors with the same name we try to put a description next to the file name that can be used to distinguish the one file from the other:

![image](https://user-images.githubusercontent.com/900690/101980394-457b3d00-3c65-11eb-94f7-c030ffba0435.png)

That code lives here and maybe can be reused for this task?

https://github.com/microsoft/vscode/blob/affd21e65ac41360704b573a4ca3b90107fd9ee8/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L948-L948

**Comment by goldst** [comment] 2020-12-13 14:36
I'd like to suggest that it should use the same format to differentiate between the paths then, like this:
![workBenchTestService.ts .../common <-> workBenchTestService.ts .../browser](https://user-images.githubusercontent.com/43523968/102014689-8d7a8c80-3d57-11eb-9932-df78d3e90954.png)

What do you think about this format? @shasiru if you don't want to implement it and @bpasero if that's ok for you, I'd like to do give it a try.

**Comment by shasiru** [comment] 2020-12-13 16:12
Although I've already started working on it, I realized this won't be implemented by me anytime soon, because of I'm very busy with other several projects at this time.

@goldst, Thanks, be my guest.. the sooner someone comes up with a reliable implementation is better... 😊

**Comment by jeanp413** [comment] 2021-01-08 20:21
@goldst are you working on this? if not I can take a look

**Comment by goldst** [comment] 2021-01-08 21:15
@jeanp413 yes I am, was occupied with other things during the holidays but will likely finish this weekend.

**Comment by goldst** [comment] 2021-01-10 17:21
Okay, I have now both versions working, I'd just need to fix a few bugs on version B.
@bpasero Are you ok with me finishing version B or should I PR version A?

Version A: just shorten diff path
![Version A](https://user-images.githubusercontent.com/43523968/104130245-e8f86400-536f-11eb-9704-e534532ff732.png)


Version B: implements multiple labels for tabs, the path is in description labels
![Version B](https://user-images.githubusercontent.com/43523968/104130078-0aa51b80-536f-11eb-8de7-08ac9acea50e.png)


Reasons for version A:
- fewer changes
- less potential for bugs
- is finished
- slightly shorter tabs for short paths

Reasons for version 2:
- UI is more consistent
- slightly shorter tabs for long paths

**Comment by bpasero** [comment] 2021-01-11 06:22
@goldst I am happy to look at the changes for both to understand the consequence. as for "less potential for bugs", I would say that some unit tests would help to improve on that.

**Comment by goldst** [comment] 2021-01-18 04:01
Thanks, @bpasero for the comment! I have redone solution B more cleanly now.

I can PR as soon as you tell me which one. I prefer B.
A: https://github.com/goldst/vscode/commit/84a98efc5733213c08bde04775ca17bd60e0b1ec
B: https://github.com/goldst/vscode/commit/3ad60356e27ba09fc60598f997dcdd59a7e9a5e7

**Comment by goldst** [comment] 2021-02-07 13:30
@bpasero short reminder :smile: If something is unclear, feel free to ask.

**Comment by bpasero** [comment] 2021-02-09 06:58
I can currently not allocate time for this but suggest to still do a PR with your proposals (maybe link to the alternate solution from the PR).

**Comment by cihanisma** [comment] 2021-07-03 11:31
You can also upvote https://github.com/microsoft/vscode/issues/127087 as it is relevant to the topic.

**Comment by bpasero** [comment] 2021-09-19 15:30
Apologies for the delay in working on this but as we get closer to our issue grooming iteration in October, I decided to look into this again with a fresh mind. @goldst I looked at the PR in https://github.com/microsoft/vscode/pull/116178 but had a hard time following along given the amount of changes. Instead I tried to implement this with concepts we already had, let me try to explain:

My solution aims to leverage existing concepts we already had for normal editors:
* with default settings, a normal file editor tab always just shows the file name
* if there are more than 1 tab open with the same name, we show a description that indicates the difference of the 2 tabs in the folders they are contained in

![image](https://user-images.githubusercontent.com/900690/133923629-4f49cfd4-fcd6-4408-8e5d-9d90b4bd93d1.png)

Taking this concept over to diff editors:
* we should always show `filenameA ↔ filenameB` as the main label for a tab to have a brief and readable label that puts emphasise on the file names and not their folders
* if both `filenameA` and `filenameB` are the same, we should indicate the difference similarly to what we do for normal file editor tabs when the same name appears twice and show a description that is shortened to reflect the difference in the folders they are contained in

Examples:

![image](https://user-images.githubusercontent.com/900690/133922479-d172d0a7-daed-4421-af73-516dd3de2a84.png)

![image](https://user-images.githubusercontent.com/900690/133923411-8dc9a9aa-043a-4e1e-8127-adfaf2f5d928.png)

![image](https://user-images.githubusercontent.com/900690/133923453-8ea26a18-a389-4c93-bf82-469eb1618139.png)

![image](https://user-images.githubusercontent.com/900690/133923479-52c667bc-5e70-406d-b5f6-646c7fed5721.png)

I didn't find the repeated usage of the `↔` character in the description so compelling so I went with just `-`. The ideal solution here would probably be to allow to have something like `labelA | descriptionA ↔ labelB | descriptionB` but that is a lot more work involved.

Thoughts?

**Comment by goldst** [comment] 2021-09-20 08:18
@bpasero thanks for having a look at my code! I agree that it contains a lot of changes and that this might be a reason to choose a simpler solution. It would have been nice to know that in advance though, but no worries.

Your solution looks good! There is one edge case in which I think it should behave differently (not sure if this should be part of this issue or a separate one):

![grafik](https://user-images.githubusercontent.com/43523968/133973275-37639fa0-61ef-4684-8572-56670455cbbb.png)

Here, there are two different `workbenchTestServices.ts` files opened, one in `.../common` and one in `.../browser`, but only one of them is in a diff. I think both tabs should have a label here, because they would if both of them were a normal tab.

**Comment by bpasero** [comment] 2021-09-20 09:58
@goldst yeah you are right, the computation of labels for tabs is strictly identifying duplicates and not cases where a label is made up of 2 sides where one is a duplicate of others. I suggest to treat that as a separate issue and allow this one to close for verification.

**Closed** 2021-09-21 08:11 UTC
Labels: help wanted, feature-request, diff-editor, workbench-editors
