### ISSUE TITLE
Option-Delete in Integrated Terminal deletes too much

### ISSUE THREAD

**Issue by misfo** [Microsoft/vscode#38639] opened 2017-11-17 16:21 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitup|Bra|0.0.2
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
vscode-gist|dba|1.0.0
prettier-vscode|esb|0.24.0
Go|luk|0.6.67
Ruby|reb|0.15.0
cucumber|ste|0.9.6
es-quotes|vil|0.2.6
vim|vsc|0.10.4
vscode-open-in-github|ziy|1.3.0

---

Steps to Reproduce:

1. Open integrated terminal
2. Type `ab cd.ef-gh`
3. Hit `Option`-`Delete` (Backspace)
4. VS Code deletes the `cd.ef-gh` instead of just deleting `gh`

Reproduces without extensions: Yes

---

`Option`-`Delete` in the integrated terminal seems to do the exact same thing as `Ctrl`-`w` (and it looks like that's how it's implemented). But in other terminals (Terminal.app and iTerm) `Option`-`Delete` do what's consistent w/ what `Option`-`Delete` does everywhere else in MacOS: delete back as far as `Option`-⬅️ would take your cursor.

`Option`-`Delete` in one of Code's editor panes does the right thing, could the integrated terminal be changed to do that as well?

---

Thanks for all your hard work on VS Code and especially the integrated terminal! The terminal is one of the killer features for me!

**Comment by Tyriar** [comment] 2017-12-15 16:07
Option delete doesn't appear to do anything for me by default in Terminal.app and iTerm, do you have custom keybindings? Also do you know what keystroke is used for option+delete if not ctrl+w?

**Comment by misfo** [comment] 2017-12-15 22:40
Oh, whoops. I forgot that I had done this, but in both apps I must have set `option` as my meta key ([instuctions on MacOS](http://osxdaily.com/2013/02/01/use-option-as-meta-key-in-mac-os-x-terminal/)). So maybe this should be a configuration in vs code instead of the default.

It looks like setting this preference in Terminal.app it makes `option`-`delete` equivalent to `esc`, `delete` (i.e. pressing `esc` and then `delete` afterwards). `esc`, `delete` actually works in vs code's integrated terminal.

**Comment by Tyriar** [comment] 2017-12-15 23:07
Ah, closing this as duplicate of https://github.com/Microsoft/vscode/issues/11314 then

**Closed by Tyriar** 2017-12-15 23:07 UTC
Labels: integrated-terminal, needs more info
