### ISSUE TITLE
"Search: Focus Previous Search Result" causes "The window is no longer responding"

### ISSUE THREAD

**Issue by lanly-dev** [microsoft/vscode#98880] opened 2020-05-30 23:08 UTC
Issue Type: <b>Bug</b>

Type "search" on Command Palette
Pick "Search: Focus Previous Search Result" in the options dropdown
It causes VS Code to freeze
Insider and Exploration versions have the same behavior.
![Capture](https://user-images.githubusercontent.com/14204732/83340660-c48fc180-a28f-11ea-9b0b-eab00979756c.PNG)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by egamma** [comment] 2020-05-31 09:08
Issue confirmed.

**Comment by roblourens** [comment] 2020-05-31 18:34
Yikes. @JacksonKearl we really should fix the underlying issue here since you could still set up a keybinding to trigger the issue. I'll look into it.

**Comment by roblourens** [comment] 2020-05-31 18:49
Fixed in 79a1f5a5ca0c6c53db617aa1fa5a2396d2caebe2

**Closed by roblourens** 2020-05-31 18:49 UTC
Labels: bug, search

**Comment by roblourens** [comment] 2020-05-31 18:51
Verification

- Set up keybindings for `search.action.focusNextSearchResult` and `search.action.focusPreviousSearchResult`
- Use these keybindings when there are no search results, nothing should happen
- And verify that the commands don't show up in the command palette when there are no search results
- And verify that they work as expected when there are some search results

**Comment by JacksonKearl** [comment] 2020-05-31 19:17
Good point, thanks.
