### ISSUE TITLE
Typescript died 5 times in each minutes

### ISSUE THREAD

**Issue by dibashthapa** [microsoft/vscode#132542] opened 2021-09-07 12:18 UTC
Issue Type: <b>Bug</b>

Getting these errors while opening vs code

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.10.56-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|7.62GB (1.26GB free)|
|Process Argv|--crash-reporter-id 365d9fb1-698f-483b-aa71-0ba7b271aa3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.14
vscode-eslint|dba|2.1.23
wpy-beautify|doi|2.0.10
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
beautify|Hoo|1.5.0
vue|jcb|0.1.5
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
vsliveshare|ms-|1.0.4761
vetur|oct|0.34.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
gruvbox-material|sai|6.4.6
tabnine-vscode|Tab|3.4.26
vim|vsc|1.21.7
material-theme|zhu|3.11.4

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn420:30356812
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-07 12:43
Please use the `Start Extension Bisect` command to see if one of your extensions is causing this.

**Comment by Naught0** [comment] 2021-09-07 13:17
This is happening to me as well, and I resolved by moving my project to Typescript v4.3.5
`4.4.2` and the nightly build both encountered this problem, repeatedly crashing.

I attempted to report the issue via the popup, but it complained I wasn't on the latest version, so it wouldn't let me.

For context, I did a clean reinstall and removed all remnants of vscode (Intel MacOS 11.2.3) and removed all user settings + extensions. The issue still occurred until I changed TS versions.

**Comment by dibashthapa** [comment] 2021-09-07 14:56
> Please use the `Start Extension Bisect` command to see if one of your extensions is causing this.

Thanks solved after hitting this command. I dont know but resolved , i saw these warnings since morning

**Comment by stewart-southwell** [comment] 2021-09-08 18:50
Experiencing the same issue as well.  It only started after update to 1.60.0.  Running  `Start Extension Bisect` fixes the issue temporarily but it came back.  I think it may be related to the other issue mentioned here #132678

**Comment by mjbvz** [comment] 2021-09-15 23:34
Closing as it sounds like the original poster can no longer reproduce

**Closed by mjbvz** 2021-09-15 23:34 UTC
Labels: needs more info

**Comment by jakub-g** [comment] 2021-09-16 09:36
FWIW I've been hitting the same issue since yesterday, with no extensions enables.

MacOS Big Sur latest + vscode latest stable 1.60.1

When I switch typescript version from 4.1.2 (workspace) to 4.4.2 (bundled with vscode) or 4.4.3, it immediately dies 5 times.
