### ISSUE TITLE
Sign In to sync settings frequent notification even after Signing In

### ISSUE THREAD

**Issue by Ajay-056** [microsoft/vscode#118325] opened 2021-03-06 17:42 UTC
- VS Code Version: 1.54.1
- OS Version: Windows 10 x64 10.0.19041

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment] 2021-03-06 18:38
/needsMoreInfo

Under notification you mean badge on Accounts in Action Bar or something else?
Please provide notification text or screenshot if it's not badge.

Most likely duplicate of #117903

**Comment by Ajay-056** [comment] 2021-03-07 04:09
It's a badge showing number 1 in the user icon

**Comment by gmccullo** [comment] 2021-03-07 07:47
Ditto. I get this every day since latest update. Output log:

[Error  - 05:45:25.273] Getting token failed: Error: Unable to transform input.
[Info  - 07:44:20.625] Logging in...
[Info  - 07:44:41.795] Logging in...
[Info  - 07:44:45.642] Exchanging login code for token
[Info  - 07:44:46.751] Exchanging login code for token success
[Info  - 07:44:46.763] Login successful
[Info  - 07:44:46.764] Token available from cache, expires in 3598994 milliseconds

**Comment by paulw2u** [comment] 2021-03-07 16:27
VSCode 1.54.1 (snap)
Ubuntu 18.04 and 20.04

This seems to be the most appropriate bug report to add my comments to. I'm seeing a badge on the Accounts icon being displayed every hour or so and have done so for around the last 36 hours. 

From the userDataSync log:
[settingssync] [info] Auto Sync: Suspended until auth token is available.
[settingssync] [info] Auto Sync: Stopped
[settingssync] [info] Auto Sync: Started
[settingssync] [info] Auto Sync: Triggered by Interval

I log in (no browser tab displayed) and the badge disappears for an hour or so. Whether I'm actually using VSCode or just leave it running in the background the badge on the Accounts icon is displayed. I'm seeing exactly the same behaviour on both of my Ubuntu installations.

**Comment by 82318179** [comment] 2021-03-08 11:28
I also have trouble with this update tip ，How to cancel this prompt
![110273702-1bd57600-8008-11eb-9cee-abb18a1067c2](https://user-images.githubusercontent.com/25976728/110315601-75f42c80-8044-11eb-8b3c-995af455b16c.png)

**Comment by Ajay-056** [comment] 2021-03-08 11:31
Many people have this issue its dragging the attention while coding hoping that they will fix it soon

**Comment by Jimbo99** [comment] 2021-03-08 12:53
Same problem. VSCode 1.54.1; OS: Windows_NT x64 10.0.19042.

For me it happens every time I wake my PC from sleep. I am signed in before it went to sleep, with VSCode running. When I awake the PC from sleep, VSCode is fine except the accounts icon has that "1" notification.

Hovering over it shows:

![vscode](https://user-images.githubusercontent.com/13149215/110323238-41647e80-800c-11eb-9587-ae1a0234f8ff.png)

BUT click that 'Sign in to Sync Settings (1)' link and it shows I am already signed in:

![vscode2](https://user-images.githubusercontent.com/13149215/110323398-77a1fe00-800c-11eb-9f94-7cbaa1a3f348.png)

**Comment by maywzh** [comment] 2021-03-08 16:05
[2021-03-08 23:04:42.844] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2021-03-08 23:04:42.844] [settingssync] [info] Auto Sync: Stopped
...
[2021-03-09 00:04:13.434] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2021-03-09 00:04:13.434] [settingssync] [info] Auto Sync: Stopped

**Comment by sandy081** [comment] 2021-03-08 17:10
/duplicate

#117903

**Closed** 2021-03-08 17:10 UTC
Labels: *duplicate, needs more info, new release
