### ISSUE TITLE
Can not make new file/new foler on root folder

### ISSUE THREAD

**Issue by thohariakb** [microsoft/vscode#114563] opened 2021-01-19 10:01 UTC
I have tried to make new file/new folder on my root project file folder but I doesn't work at all. I just add new file on subfolder of main folder. it's lastest version of VS Code (1.52.1), please fix it. Thanks

**Comment by yume-chan** [comment] 2021-01-19 10:08
I can't reproduce this. Steps:

1. Click the space at bottom of explorer
2. Click "New File" icon

File name input was at project root:

![image](https://user-images.githubusercontent.com/1330321/105019405-01a7fe80-5a81-11eb-8fd4-5c6c0e612b32.png)

Enter a filename, indeed the file was created in project root:

![image](https://user-images.githubusercontent.com/1330321/105019528-256b4480-5a81-11eb-9a02-71b5709e7c17.png)

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by isidorn** [comment] 2021-01-20 10:06
We accidently closed this. @thohariakb please answer @yume-chan questions

**Closed** 2021-01-27 11:35 UTC
Labels: file-explorer, needs more info
