### ISSUE TITLE
multi cursor editing render bug

### ISSUE THREAD

**Issue by xtofs** [microsoft/vscode#131341] opened 2021-08-22 05:19 UTC
Issue Type: <b>Bug</b>

a multi-cursor where the cursor on one line is to the right of an "u" is not rendering the cursors vertically aligned. See attached screen capture.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

https://user-images.githubusercontent.com/10557127/130343381-22ca6de1-6225-4e32-a558-ba31691f1ec9.mov

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.69GB free)|
|Process Argv|--crash-reporter-id 92a42553-efbb-4259-b5e9-48cadaccff30|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
razor-plus|aus|0.1.4
toml|be5|0.5.1
better-toml|bun|0.3.2
path-intellisense|chr|2.4.0
codealignment-vscode|cpm|2.0.19
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
prettier-for-handlebars-vscode|emb|3.0.0
prettier-vscode|esb|8.1.0
abnf|for|1.0.0
dotnet-test-explorer|for|0.7.6
vscode-graphql|Gra|0.3.16
rest-client|hum|0.24.5
yuml|Jai|3.5.1
docomment|k--|0.1.20
Kotlin|mat|1.7.1
rust-analyzer|mat|0.2.710
rainbow-csv|mec|1.9.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.8.1147840270
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
cpptools|ms-|1.5.1
js-debug-nightly|ms-|2021.8.217
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.2
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
prisma|Pri|2.29.1
binary-viewer|Qia|1.1.1
java|red|0.81.0
crates|ser|0.5.9
shader|sle|1.1.5
vscode-hexdump|sle|1.8.1
vscode-lldb|vad|1.6.5
vscode-bnf|Val|0.0.1
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-maven|vsc|0.32.2
cross-rust-analyzer|vsr|0.0.2
scriban|xoo|1.2.1
t4-support|zbe|0.5.0
Idris|zjh|0.9.8
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

**Comment by alexdima** [comment] 2021-08-23 07:04
@xtofs What is the exact content on the lines which do not align?

**Comment by xtofs** [comment] 2021-08-24 14:35
The text is from the vs-code documentation called Interactive Playground. (help/interactive playground)

```
That is the tip of the iceberg for multi-cursor editing have a look at the selection menu and our handy keyboard reference guide for additional actions.

#p1 {background-color: #ff0000;}   /* red */
#p2 {background-color: #00ff00;}   /* green */
#p3 {background-color: #0000ff;}   /* blue */
```


I found this  [file](https://github.com/microsoft/vscode/blob/b74263242ce63d46de3c4471916c6421ea74e26c/src/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md ) but couldn't find it in the main branch and the text is slightly different

**Comment by xtofs** [comment] 2021-08-24 14:42
Theme is called `Dark+ (default Dark)` 
 
```HTML
<p>That is the tip of the iceberg for multi-cursor editing. Have a look at the selection menu and our handy <a href="command:workbench.action.keybindingsReference">keyboard reference guide</a> for additional actions.</p>
<div id="snippet-1.css" class="walkThroughEditorContainer" data-keybinding-context="44" data-mode-id="css" style="--codelens-font-features_1cd5cd2f:&quot;liga&quot; off, &quot;calt&quot; off; --testMessageDecorationFontFamily:Monaco, Menlo, &quot;Courier New&quot;, monospace; height: 72px;"><div class="monaco-editor no-user-select mac  showUnused showDeprecated vs-dark" role="code" data-uri="walkThroughSnippet://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough.md?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2FwalkThrough%2Fbrowser%2Feditor%2Fvs_code_editor_walkthrough%22%7D#1.css" style="width: 649px; height: 72px;"><div data-mprt="3" class="overflow-guard" style="width: 649px; height: 72px;"><div class="margin" role="presentation" aria-hidden="true" style="position: absolute; transform: translate3d(0px, 0px, 0px); contain: strict; top: 0px; height: 72px; width: 51px;"><div class="glyph-margin" style="left: 0px; width: 18px; height: 72px;"></div><div class="margin-view-zones" role="presentation" aria-hidden="true" style="position: absolute;"></div><div class="margin-view-overlays" role="presentation" aria-hidden="true" style="position: absolute; width: 51px; font-family: Monaco, Menlo, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; line-height: 18px; letter-spacing: 0px; height: 72px;"><div style="position:absolute;top:0px;width:100%;height:18px;"><div class="current-line current-line-margin-both" style="width:51px; height:18px;"></div><div class="active-line-number line-numbers" style="left:18px;width:7px;">1</div></div><div style="position:absolute;top:18px;width:100%;height:18px;"><div class="line-numbers" style="left:18px;width:7px;">2</div></div><div style="position:absolute;top:36px;width:100%;height:18px;"><div class="line-numbers" style="left:18px;width:7px;">3</div></div><div style="position:absolute;top:54px;width:100%;height:18px;"></div></div></div><div class="monaco-scrollable-element editor-scrollable vs-dark mac" role="presentation" data-mprt="5" style="position: absolute; overflow: hidden; left: 51px; width: 598px; height: 72px;"><div class="lines-content monaco-editor-background" style="position: absolute; overflow: hidden; width: 1e+06px; height: 1e+06px; transform: translate3d(0px, 0px, 0px); contain: strict; top: 0px; left: 0px;"><div class="view-overlays" role="presentation" aria-hidden="true" style="position: absolute; height: 0px; width: 598px;"><div style="position:absolute;top:0px;width:100%;height:18px;"><div class="current-line" style="width:598px; height:18px;"></div></div><div style="position:absolute;top:18px;width:100%;height:18px;"></div><div style="position:absolute;top:36px;width:100%;height:18px;"></div><div style="position:absolute;top:54px;width:100%;height:18px;"></div></div><div role="presentation" aria-hidden="true" class="view-rulers"></div><div class="view-zones" role="presentation" aria-hidden="true" style="position: absolute;"></div><div class="view-lines monaco-mouse-cursor-text" role="presentation" aria-hidden="true" data-mprt="7" style="position: absolute; font-family: Monaco, Menlo, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; line-height: 18px; letter-spacing: 0px; width: 598px; height: 84px;"><div style="top:0px;height:18px;" class="view-line"><span><span class="mtk8">#p1</span><span class="mtkw">·</span><span class="mtk1">{</span><span class="mtk9">background-color</span><span class="mtk1">:</span><span class="mtkw">·</span><span class="mtk11 ced-colorBox--302978ab-3"></span><span class="mtk11">#ff0000</span><span class="mtk1">;}</span><span class="mtkw">················</span><span class="mtk4">/*</span><span class="mtkw">·</span><span class="mtk4">red</span><span class="mtkw">·</span><span class="mtk4">in</span><span class="mtkw">·</span><span class="mtk4">HEX</span><span class="mtkw">·</span><span class="mtk4">format</span><span class="mtkw">·</span><span class="mtk4">*/</span></span></div><div style="top:18px;height:18px;" class="view-line"><span><span class="mtk8">#p2</span><span class="mtkw">·</span><span class="mtk1">{</span><span class="mtk9">background-color</span><span class="mtk1">:</span><span class="mtkw">·</span><span class="mtk15 ced-colorBox-5dd887d5-3"></span><span class="mtk15">hsl</span><span class="mtk1">(</span><span class="mtk6">120</span><span class="mtk1">,</span><span class="mtkw">·</span><span class="mtk6">100%</span><span class="mtk1">,</span><span class="mtkw">·</span><span class="mtk6">50%</span><span class="mtk1">);}</span><span class="mtkw">····</span><span class="mtk4">/*</span><span class="mtkw">·</span><span class="mtk4">green</span><span class="mtkw">·</span><span class="mtk4">in</span><span class="mtkw">·</span><span class="mtk4">HSL</span><span class="mtkw">·</span><span class="mtk4">format</span><span class="mtkw">·</span><span class="mtk4">*/</span></span></div><div style="top:36px;height:18px;" class="view-line"><span><span class="mtk8">#p3</span><span class="mtkw">·</span><span class="mtk1">{</span><span class="mtk9">background-color</span><span class="mtk1">:</span><span class="mtkw">·</span><span class="mtk15 ced-colorBox-5eec6e69-3"></span><span class="mtk15">rgba</span><span class="mtk1">(</span><span class="mtk6">0</span><span class="mtk1">,</span><span class="mtkw">·</span><span class="mtk6">4</span><span class="mtk1">,</span><span class="mtkw">·</span><span class="mtk6">255</span><span class="mtk1">,</span><span class="mtkw">·</span><span class="mtk6">0.733</span><span class="mtk1">);}</span><span class="mtkw">·</span><span class="mtk4">/*</span><span class="mtkw">·</span><span class="mtk4">blue</span><span class="mtkw">·</span><span class="mtk4">with</span><span class="mtkw">·</span><span class="mtk4">alpha</span><span class="mtkw">·</span><span class="mtk4">channel</span><span class="mtkw">·</span><span class="mtk4">in</span><span class="mtkw">·</span></span></div><div style="top:54px;height:18px;" class="view-line"><span><span class="mtk4">RGBA</span><span class="mtkw">·</span><span class="mtk4">format</span><span class="mtkw">·</span><span class="mtk4">*/</span></span></div></div><div data-mprt="1" class="contentWidgets" style="position: absolute; top: 0px;"><div class="codicon-light-bulb codicon" widgetid="LightBulbWidget" title="Show Fixes (⌘.)" style="position: absolute; visibility: hidden; max-width: 1061px;"></div></div><div role="presentation" aria-hidden="true" class="cursors-layer cursor-line-style cursor-solid"><div class="cursor monaco-mouse-cursor-text " style="height: 18px; top: 0px; left: 0px; font-family: Monaco, Menlo, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; line-height: 18px; letter-spacing: 0px; display: block; visibility: hidden; width: 1.66667px;"></div></div></div><div role="presentation" aria-hidden="true" class="invisible scrollbar horizontal" style="position: absolute; width: 584px; height: 12px; left: 0px; bottom: 0px;"><div class="slider" style="position: absolute; top: 0px; left: 0px; height: 12px; transform: translate3d(0px, 0px, 0px); contain: strict; width: 584px;"></div></div><canvas class="decorationsOverviewRuler" aria-hidden="true" width="33" height="172" style="position: absolute; transform: translate3d(0px, 0px, 0px); contain: strict; top: 0px; right: 0px; width: 14px; height: 72px;"></canvas><div role="presentation" aria-hidden="true" class="invisible scrollbar vertical" style="position: absolute; width: 14px; height: 72px; right: 0px; top: 0px;"><div class="slider" style="position: absolute; top: 0px; left: 0px; width: 14px; transform: translate3d(0px, 0px, 0px); contain: strict; height: 72px;"></div></div></div><div role="presentation" aria-hidden="true" style="width: 649px;"></div><textarea data-mprt="6" class="inputarea monaco-mouse-cursor-text" wrap="off" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" aria-label="The editor is not accessible at this time. Press Alt+F1 for options." tabindex="0" role="textbox" aria-roledescription="editor" aria-multiline="true" aria-haspopup="false" aria-autocomplete="both" style="font-family: Monaco, Menlo, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; line-height: 18px; letter-spacing: 0px; top: 0px; left: 51px; width: 1px; height: 18px;"></textarea><div style="position: absolute; top: 0px; left: 0px; width: 0px; height: 0px;"></div><div data-mprt="4" class="overlayWidgets" style="width: 649px;"><div class="accessibilityHelpWidget" role="dialog" aria-hidden="true" widgetid="editor.contrib.accessibilityHelpWidget" style="width: 500px; height: 300px; display: none; position: absolute;"><div role="document"></div></div></div><div data-mprt="8" class="minimap slider-mouseover" role="presentation" aria-hidden="true" style="position: absolute; left: 0px; width: 0px; height: 72px;"><div class="minimap-shadow-hidden" style="height: 72px;"></div><canvas width="0" height="172" style="position: absolute; left: 0px; width: 0px; height: 72px;"></canvas><canvas class="minimap-decorations-layer" width="0" height="172" style="position: absolute; left: 0px; width: 0px; height: 72px;"></canvas><div class="minimap-slider" style="position: absolute; transform: translate3d(0px, 0px, 0px); contain: strict; width: 0px;"><div class="minimap-slider-horizontal" style="position: absolute; width: 0px; height: 0px;"></div></div></div></div><div data-mprt="2" class="overflowingContentWidgets"><div class="monaco-editor rename-box" widgetid="__renameInputWidget" style="background-color: rgb(37, 37, 38); box-shadow: rgba(0, 0, 0, 0.36) 0px 0px 8px 2px; color: rgb(204, 204, 204); position: absolute; visibility: hidden; max-width: 1200px;"><input class="rename-input" type="text" aria-label="Rename input. Type new name and press Enter to commit." style="font-family: Monaco, Menlo, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; background-color: rgb(60, 60, 60); border-width: 0px; border-style: none;"><div class="rename-label" style="font-size: 9.6px;">Enter to Rename, ⇧Enter to Preview</div></div></div></div></div>

**Comment by alexdima** [comment] 2021-08-24 14:48
Thank you for the extra information. I cannot reproduce the misalignment:
![image](https://user-images.githubusercontent.com/5047891/130638424-7958f8f3-dfbf-471d-804b-8891dcba9522.png)

Did you by any chance make any customizations (like fontSize, fontFamily, zoomLevel, etc.).

**Comment by xtofs** [comment] 2021-08-24 14:52
no customizations but the Dark+ Theme and on a mac 

<img width="670" alt="Screen Shot 2021-08-24 at 07 51 10" src="https://user-images.githubusercontent.com/10557127/130639091-664bec63-b78a-46b2-bb53-09f03d2b948b.png">

**Comment by alexdima** [comment] 2021-08-24 15:05
Thank you. I was able to reproduce:

![image](https://user-images.githubusercontent.com/5047891/130641313-1a73b8c0-2841-4b1c-97c6-4d56b8411496.png)

**Comment by alexdima** [comment] 2021-08-24 15:17
From debugging, I have determined that the root cause are the color boxes. When the color boxes are not rendered, this is not a problem. Once color boxes are rendered, when queried, the browser reports the following offsets for the cursors:

<img width="694" alt="Screen Shot 2021-08-24 at 17 14 46" src="https://user-images.githubusercontent.com/5047891/130643112-f71fedc4-a2a8-4105-9760-fa55000cf4be.png">

The offsets are very close to each other (547.453125 vs 547.53125), but one gets rounded down, while the other gets rounded up.

**Comment by alexdima** [comment] 2021-08-25 14:42
I have tried pushing the rounding as late as possible and even rendering the cursors with the relevant floats e.g. `433.453125` vs `433.53125`, but still there is a gap presumably introduced by Chromium rounding. One possible way to fix this is to introduce some kind of `Math.round` with a memory shared by all view cursors. Such a impure `Math.round` might have a chance to round two subsequent calls i.e. for `433.453125` and `433.53125` to the same integer.

**Comment by alexdima** [comment] 2022-12-11 12:46
I can't reproduce this anymore, I think it was fixed via https://github.com/microsoft/vscode/commit/8b0ea7ddd9140e7893c7ef902f57d598771c2dda

**Closed by alexdima** 2022-12-11 12:46 UTC
Labels: bug, upstream, macos, font-rendering
