### ISSUE TITLE
Feature request: show the last part of the working directory in terminal title

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#32181] opened 2017-08-09 09:04 UTC
A new feature was just added that shows the current process name inside the terminal name, like `node` instead of simply `cmd.exe`.

While it's a good thing, I think it could be improved even more by adding the current terminal working directory, or at least the *last part* of the working directory.

Right now, if you start two webpack watches, in a two different directories `c:\dev\project1` & `c:\dev\project2`, you will end up with this:

```
1: node
2: node
```

If there was a way to get the last part of the current working directory, it could look like:

```
1: node <projet1>
2: node <project2>
```

Which I find a lot better. This may not be that easy to do on Windows though.

**Comment by Tyriar** [comment] 2017-08-14 21:31
Duplicate of https://github.com/Microsoft/vscode/issues/29816 :smiley:

**Closed by Tyriar** 2017-08-14 21:31 UTC
Labels: integrated-terminal
