### ISSUE TITLE
Code Completion Not Working for js

### ISSUE THREAD

**Issue by snaquaye** [Microsoft/vscode#20516] opened 2017-02-13 00:18 UTC
- VSCode Version: 1.9.1
- OS Version: Ubtunu Gnemo 16.10

Aftering upgrading from 1.8 to 1.9.1, intellisense for node node modules, refuses to work. my tsserver is in
node_modules/typescript/bin.

Thanks

**Comment by nguymin4** [comment] 2017-02-13 11:34
Isn't this similar to #20201. I have problem with intelli-sense on Ubuntu 16.04 as well.

**Comment by snaquaye** [comment] 2017-02-14 14:12
Hello,

pls, what more information would you want me to provide.

Thanks

**Comment by mjbvz** [comment] 2017-02-15 01:20
@snaquaye To help investigate:

* Do you have `jsconfig.json`?
* Can you please describe the project you are working with or share some example code.
* What is the expected behavior?
* Is this only happening in one project or in all of your projects?
* Enable `"typescript.tsserver.trace": "verbose"` in your settings. Then restart vs code and repo the issue. Go to the output window and share the output from `TypeScript`

Thanks

**Comment by cmrigney** [comment] 2017-02-15 19:38
My intellisense for javascript also stopped working consistently after the update.  I'm not exactly sure what I do that causes it.  I'll enable the trace.

**Comment by cmrigney** [comment] 2017-02-15 19:44
Even before my issue occurs, intellisense for my node_modules isn't working whereas it did in 1.8.  So for example lodash does not autocomplete with methods.  Maybe related to https://github.com/Microsoft/vscode/issues/20201 ?  I'll let you know if I can reproduce my other issue.

**Comment by cmrigney** [comment] 2017-02-16 21:42
More info, the configure excludes comes up for me, which I used the same excludes in 1.8 and intellisense worked.

Here is my `tsconfig.json`
```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "compilerOptions": {
    "allowJs": true
  },
  "installed": {},
  "exclude": [
    "**/node_modules",
    "docs",
    "scripts",
    "temp",
    "typings",
    "uploads"
  ]
}
```

**Comment by mjbvz** [comment] 2017-02-24 02:54
@cmrigney Please open a new issue for what you are seeing. Although the symptoms are the same as what @snaquaye is seeing, it is unlikely the root cause is also the same

**Comment by mjbvz** [comment] 2017-02-24 02:56
@snaquaye Please try updating to VSCode 1.10 which includes a new version of TypeScript. If you still see the issue, please provide the information I [mentioned](https://github.com/Microsoft/vscode/issues/20516#issuecomment-279889550) to help us investigate this.

**Comment by mjbvz** [comment] 2017-02-27 22:45
Closing as we need more info to investigate the original bug. 

@cmrigney I see you opened #21355. Does that track the error you reported in this thread? If not, please open another bug and I can take a look

Thanks

**Closed by mjbvz** 2017-02-27 22:45 UTC
Labels: needs more info, typescript

**Comment by cmrigney** [comment] 2017-02-28 14:00
@mjbvz Yes it does.  I haven't had the chance to do your requests yet but hopefully soon.
