### ISSUE TITLE
Copy, then selecting a text to replace and pasting do not do past

### ISSUE THREAD

**Issue by olivierchatry** [microsoft/vscode#90347] opened 2020-02-10 09:20 UTC
- VSCode Version:1.42.1
- OS Version:Fedora 31

Steps to Reproduce:

1. Open a file, ( I have tried with JS, HBS, and CSS ) 
2. Select a text
3. Copy using ctrl+c
4. Select another text
5. Paste using ctrl+v
6. Selected text is not replaced with the content first copy. This work with right-click + paste.

Does this issue occur when all extensions are disabled?: Yes, launched vs code with `code --disable-extensions` to be sure.

**Comment by gjsjohnmurray** [comment] 2020-02-10 14:10
/duplicate of #90222. See that issue for info about how to reinstate previous behaviour.

**Closed** 2020-02-10 14:10 UTC
Labels: *duplicate
