### ISSUE TITLE
App freezes frequently for a limited duration

### ISSUE THREAD

**Issue by haug1** [microsoft/vscode#122688] opened 2021-04-29 20:15 UTC
- VS Code Version: Code - OSS 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-22T15:03:39.218Z)
- OS Version: Linux x64 5.11.16-arch1-1

Steps to Reproduce:

Don't know. It happens randomly only on this one machine. 

The symptoms are:
- application freezes completely for a limited time before becoming responsive again, 10 secs or more
- rendering does not happen at all during the freeze (clicking anywhere/doing anything does nothing on the UI, changing from one workspace to another the application does not render, it keeps showing what was on the other workspace)

It doesn't matter what I am doing. Editing typescript/python/markdown files. It may have something to do with `git` integration, but it may not, I can't confirm at this point.

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

Here is output of `code --status` during a freeze (during this freeze I had extensions enabled, but I have confirmed that it happens with extensions disabled as well):

```
09:48:45 main@XPS ~ → code --status
[12208:0429/214848.281072:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code - OSS 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-22T15:03:39.218Z)
OS Version:       Linux x64 5.11.16-arch1-1
CPUs:             Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1211)
Memory (System):  15.22GB (10.26GB free)
Load (avg):       1, 1, 0
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   140	 11861	code-oss main
    0	    62	 11863	   zygote
    0	   125	 11892	     gpu-process
    0	    62	 11864	   zygote
    0	    94	 11895	   utility
    0	   234	 11917	   window (● README.md (Working Tree) - stock-scraper - Code - OSS)
    0	   171	 11942	     extensionHost
    0	    94	 12040	       /usr/lib/electron11/electron /usr/lib/code/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=11942
    0	    94	 11959	     searchService
    0	    94	 12001	     watcherService
    0	   125	 11982	   shared-process
    0	    94	 12028	     ptyHost
    0	     0	 12054	       /bin/bash

Workspace Stats: 
|  Window (● README.md (Working Tree) - stock-scraper - Code - OSS)
|    Folder (stock-scraper): 52 files
|      File types: js(12) map(12) json(8) ts(8) gitignore(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
```

Please let me know what I can do to provide more information if needed.

**Comment by bpasero** [comment] 2021-04-30 04:56
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by haug1** [comment] 2021-05-03 20:31
Sorry I'm late to discover your reply. I only use this machine on my spare time so I will need a couple of days to confirm anything. I will update this thread.

**Comment by bpasero** [comment] 2021-05-04 05:40
Ok

**Comment by yzhang-gh** [comment] 2021-05-06 04:53
I have also seen this issue (twice) since I updated VS Code to v1.56.0 today (on Windows).

I have no idea how to reproduce it. It seems to happen when the computer is idle for a while.

Hope there will be more information from other users as I can see there have been quite a few related reports recently.

**Comment by deepak1556** [comment] 2021-05-06 11:44
@yzhang-gh this issue is tracking the hang on linux for v1.55, I would recommend to open a separate issue for windows if you are experiencing the issue again. Also can you follow the steps below when it happens,

* Download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
* Find the workbench process id by following command in powershell
```
Get-WmiObject win32_process -Filter "name='Code - Insiders.exe'" | where CommandLine -like '*--type=renderer*' | Select-Object ProcessId, CommandLine
```
* Once the app freezes, open process explorer and find the processes with above ProcessId
* Right Click on the Process -> Create Dump -> Full Dump
* Send the files to Deepak.Mohan@microsoft.com

**Comment by aleclarson** [comment] 2021-05-11 16:58
I'm experiencing this on macOS, just today.

```
Version:          Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS Version:       Darwin x64 19.6.0
CPUs:             Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)
Memory (System):  20.00GB (3.01GB free)
Load (avg):       4, 4, 4
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions --crash-reporter-id 6df6dbd2-74fa-47c0-a182-c33f1f3feac1
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    1       82    2586  code main
    0       41    2631     gpu-process
    0       20    2633     utility
   97      246    2634     window (Foo.tsx — xxx)
    8      143    2640       extensionHost
    0      512    2646         electron_node tsserver.js 
    0      922    2647         electron_node tsserver.js 
    0       20    2664           electron_node typingsInstaller.js typesMap.js 
   91     1352    2648         electron_node tsserver.js 
    0       41    2672         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2640
    0       20    2644       watcherService
    0       20    2651       searchService
    0       82    2643     shared-process
    0       20    2645       ptyHost

Workspace Stats: 
|  Window (Foo.tsx — xxx)
|    Folder (xxx): more than 22430 files
|      File types: hpp(3882) js(1108) h(666) java(596) d(477) pcm(372) ts(329)
|                  m(277) dia(266) o(265)
|      Conf files: package.json(27) tsconfig.json(18) github-actions(2)
|                  settings.json(2) tslint.json(1)
```

Trying out the Insiders build now...

**Comment by aleclarson** [comment] 2021-05-11 17:33
Seems to be fixed in v1.57.0-insider

**Comment by haug1** [comment] 2021-05-12 18:09
I've not experienced it again since upgrading to `v1.56.0-insider`

**Comment by deepak1556** [comment] 2021-05-13 00:44
Closing for now based on above comments, can reopen if the issue persists with `1.57` stable release.

**Closed by deepak1556** 2021-05-13 00:44 UTC
Labels: needs more info
