### ISSUE TITLE
Strange white line in status bar

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#23968] opened 2017-04-06 02:06 UTC
![screenshot_2017-04-06_09-55-29](https://cloud.githubusercontent.com/assets/9464825/24734404/c7253760-1aaf-11e7-9cf0-a0bdac5d49d3.png)
![screenshot_2017-04-06_09-55-58](https://cloud.githubusercontent.com/assets/9464825/24734405/c7533278-1aaf-11e7-8bb7-7b5fd6e72979.png)

In the maximized vscode, look at the bottom line of pixels, white in the right side, and black in the left side.
If move mouse over ``2 days ago``, then the white pixels is a little longer.

- VSCode Version: 1.11.0
- OS Version: Ubuntu 16

Steps to Reproduce:

1. Maximize vscode (Note: full screen F11 is okay, a continuous white line shows up)
2. look at the screen bottom

**Comment by innerlee** [comment] 2017-04-06 02:10
BTW, if there is a choice, I prefer this bottom line of pixels be black :)

**Comment by bpasero** [comment] 2017-04-06 04:55
@Tyriar do you see this too?

**Comment by Tyriar** [comment] 2017-04-06 05:20
@bpasero nope. Maybe it's the Chromium glitch where the tooltip shows up in white/black?

**Comment by bpasero** [comment] 2017-04-06 05:24
@innerlee you see this white line all the time right, not just when hovering down there?

**Comment by innerlee** [comment] 2017-04-06 05:31
Yes. Hovering or not just changes the length of white lines. In full screen mode, the screen bottom is a line of white pixels. In maximized mode, this white line is partially becomes black. And varies if i hover over some element in status bae or not. In window mode, the bottom of window is the border of window (os-dependent?) and neither white nor black line observed.

**Comment by bpasero** [comment] 2017-04-06 05:37
@innerlee does it reproduce if you run from the command line "code --disable-gpu"?

**Comment by innerlee** [comment] 2017-04-06 06:19
yes, it does not related to ``--disable-gpu``. 

Another detail: when code starts, the bottom is white line, then the middle part becomes black. Then after ui elements loaded, the white grows, and black becomes shorter.

more picutures:

window mode:
![screenshot_2017-04-06_14-12-01](https://cloud.githubusercontent.com/assets/9464825/24740326/2b9f3a60-1ad3-11e7-8320-b5bf421da0bb.png)

full status bar in max mode:
![screenshot_2017-04-06_14-12-53](https://cloud.githubusercontent.com/assets/9464825/24740325/2b9d3990-1ad3-11e7-825a-26c520372988.png)

**Comment by bpasero** [comment] 2017-04-06 06:30
@innerlee do you set the zoom level in settings to any value?

**Comment by innerlee** [comment] 2017-04-06 06:36
I find this interesting.

black: menu hide, setting page
![screenshot_2017-04-06_14-24-49](https://cloud.githubusercontent.com/assets/9464825/24740796/887dea7c-1ad5-11e7-8d72-8f5bd5e3fe47.png)

white and black: menu hide, normal files
![screenshot_2017-04-06_14-25-13](https://cloud.githubusercontent.com/assets/9464825/24740795/887d7cd6-1ad5-11e7-8d02-0ba55b173489.png)

white: menu hide, normal files, developer tools open
![screenshot_2017-04-06_14-27-25](https://cloud.githubusercontent.com/assets/9464825/24740797/8884daf8-1ad5-11e7-9caf-0e8d0803e117.png)

black: menu shown
![screenshot_2017-04-06_14-28-53](https://cloud.githubusercontent.com/assets/9464825/24740798/8885d49e-1ad5-11e7-8b57-512b488941d6.png)

**Comment by innerlee** [comment] 2017-04-06 06:40
zoom leve: state
0, 2, 4: black
-1, 1, 3: black & white

**Comment by bpasero** [comment] 2017-04-06 07:13
Ok so this is zooming related.

**Comment by joaomoreno** [comment] 2018-12-03 15:05
@bpasero I see this very often and I have zoom at 0 always.

**Comment by roblourens** [comment] 2018-12-08 00:31
This happens when the 'counter' span is sized to a certain fractional width depending on its contents, and is at a certain position depending on what precedes it in the status bar. I think it's a rounding error somewhere. Giving the counter span a whole number width fixes it for me. Spent some time working that out but I also see that it appears to be fixed with 3.0.

**Comment by carlosefr** [comment] 2019-01-03 19:38
Also seeing this. If I change the "Python 2.3.2 64-bit" string (in developer tools) to "Python 2.3.1 64-bit" (which is slightly narrower) it goes away. Seems like it's coming from the warning icon element because toggling it's `background:` style makes it go away (while also making the icon itself go away).
<img width="318" alt="screen shot 2019-01-03 at 19 36 03" src="https://user-images.githubusercontent.com/937276/50657595-d5e77800-0f8e-11e9-9020-15e57c1f83c7.png">

**Comment by roblourens** [comment] 2019-01-03 19:44
I investigated this last month and found that it was due to a rounding issue in the widths of the status bar items + the `-webkit-mask` but it's fixed in electron 3 so not worth working around it.

**Comment by bpasero** [comment] 2019-01-25 16:22
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:22 UTC
Labels: electron, fixed-in-electron-3.0.x, upstream, workbench-status
