### ISSUE TITLE
Snippets started with "#" not worked

### ISSUE THREAD

**Issue by XueYiZhiFeng** [Microsoft/vscode#23719] opened 2017-03-31 03:41 UTC
- VSCode Version: 1.11.0-insider &  1.11.0
- OS Version:macOS 10.11.6

Steps to Reproduce:

1. Write a snippet's started with "#", like "#ifdef"
2. The snippet showed in typing "#" then "ctrl+space", and in the "Insert Snippet" command.
3.  not showed in intelligence.
4. not showed in "#if + ctrl + space" or "#i + ctrl + space".
5. cannot expanded by the "tab".
6. other snippets work correctly.
7. same snippet with a different prefix, works correctly.

use a clean build without any other extension or custom preference.

**Comment by aeschli** [comment] 2017-03-31 06:24
@XueYiZhiFeng With what language are you using that snippet?

**Comment by jrieken** [comment] 2017-03-31 06:53
Yeah, this is likely because `#` isn't considered a word and therefore doesn't trigger 24x7 IntelliSense

**Comment by XueYiZhiFeng** [comment] 2017-03-31 07:18
@aeschli I got problem in c++ but it seems to happen in other fomat.

**Comment by jrieken** [comment] 2017-03-31 07:24
Ok, thanks!

**Comment by jrieken** [comment] 2017-04-05 05:58
actually a dupe of #6504

**Closed by jrieken** 2017-04-05 05:58 UTC
Labels: bug, snippets
