### ISSUE TITLE
Problems area: Errors/warnings are stuck

### ISSUE THREAD

**Issue by mbaric1** [Microsoft/vscode#56557] opened 2018-08-16 12:09 UTC
- VSCode Version: 1.26.0 4e9361845dc28659923a300945f84731393e210d x64
- OS Version: Linux 4.15.0-32-generic #35-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. TS - make warning like "missing whitespace"
2. Fix error

Warning is still there until vscode is restarted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2018-08-16 12:16
Duplicate of #56371

**Closed** 2018-08-16 12:16 UTC
Labels: *duplicate, new release
