### ISSUE TITLE
No tasks found (gulp file autodetect no longer works)

### ISSUE THREAD

**Issue by sergsalo** [Microsoft/vscode#19743] opened 2017-02-02 20:46 UTC
- VSCode Version: 1.9
- OS Version: Windows 10

Steps to Reproduce:

1. Update to the latest version of VS code (v1.9)
2. Try to list tasks (specifically those in gulpfile.js) and see "No tasks found".

**Comment by tkoestler** [comment] 2017-02-02 23:45
Same problem here.  My project has only gulp tasks, I don't have a task.json.  This was working before I clicked update.  Argh!

**Comment by tkoestler** [comment] 2017-02-02 23:59
I added a tasks.json and pointed it at my gulp task, that worked.  
```
{
	"version": "0.1.0",
	"tasks": [
		{
			"taskName": "startup",
			"command" : "gulp",
			"args": ["startup"],
			"isShellCommand": true
		}
	]
}

So looks like auto-discovery issue vs flat out broken.  Should the location of the gulpfile matter?  Mine is in my project root folder.

**Comment by dbaeumer** [comment] 2017-02-03 08:56
Sorry for the breakage. I tried to reproduce this using a simple example but I couldn't. The example is as follows:

- gulp installed locally in a workspace using npm install gulp
- tasks.json
```json
{
	"version": "0.1.0",
	"command": "gulp",
	"isShellCommand": true,
	"args": ["--no-color"],
	"showOutput": "always"
}
```
- gulpfile.js
```js
var gulp = require('gulp');

gulp.task('compile', function() {
	console.log('Compile...');
});

gulp.task('build', function() {
	console.log('Build...');
});
```
This gives:
![cast](https://cloud.githubusercontent.com/assets/1931590/22585213/f260f7fa-e9f6-11e6-9441-bc1e8d354426.gif)

Can someone share the project so that I can investigate more. I changed code in the area so there is a likelihood that I broke something.

**Comment by tkoestler** [comment] 2017-02-03 12:22
Remove the tasks.json. Per my prevous post the issue is with auto-discovery of gulp tasks, not running them through a project.json

**Comment by vukers** [comment] 2017-02-03 12:50
In previous versions, I would be able to run `Tasks: Run Task` without a tasks.json file, and it would correctly list my gulp tasks. It seems that in 1.9, you need to have a tasks.json file in order for auto-discovery to work. @tkoestler try running `Tasks: Configure Task Runner` to generate the tasks.json and removing the "tasks" section -- it should still automatically list the tasks defined in your gulpfile.js

**Comment by tkoestler** [comment] 2017-02-03 13:06
@vukers Did what you suggested. It works and I like it better than what I came up with.  Thanks.

**Comment by dbaeumer** [comment] 2017-02-03 14:03
@tkoestler thanks. It reproduces without a tasks.json.

**Comment by dbaeumer** [comment] 2017-02-03 14:18
I debugged it and the breakage is actually caused by a change in the configuration service. It now returns a empty object literal if a configuration doesn't exist instead of undefined.

@sandy081 moving to you as discussed. Let me know when you have a fix and I will verify.

**Comment by dbaeumer** [comment] 2017-02-03 14:20
@sandy081  Since a work around exists this might not fully qualify for a recovery build. Lets discuss in the next standup depending on the risk of the fix. I could add a work around fix on my end as well.

**Comment by sandy081** [comment] 2017-02-03 16:39
@dbaeumer Fixed it in configuration service to return `undefined` values for a non-existent configuration. 

Fix is less risky. But added more tests to make sure that behavior is not changed and covered most corner cases.

**Comment by sandy081** [comment] 2017-02-03 16:40
Oops.. Did not see your last comment. If we decide not to fix this for recovery I will revert the commits.

**Closed** 2017-02-03 17:05 UTC
Labels: bug, candidate, important

**Comment by dbaeumer** [comment] 2017-02-07 09:24
I reviewed the fix. Looks good to me.
