### ISSUE TITLE
[sass] @at-root showing as an error

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#4524] opened 2016-03-21 19:03 UTC
- VSCode Version: 0.10.11
- OS Version: WIN10 x64 - Home Edition

Steps to Reproduce:
1. Just try to write a SASS / Scss stylesheet with an `@at-root`.
   ![image](https://cloud.githubusercontent.com/assets/9027363/13930447/c57c5cf8-ef7d-11e5-8e73-d37f1353868b.png)

**Comment by VitorLuizC** [comment] 2016-11-23 18:33
I saw some commits about it.
Is it closed?

**Comment by aeschli** [comment] 2016-11-23 18:59
Yes, I forgot, I added support for @at-root some time ago.
duplicate of #10204

**Closed by aeschli** 2016-11-23 18:59 UTC
Labels: bug, css-less-sass
