### ISSUE TITLE
Cannot Start VSCode from Terminal with the command 'code'

### ISSUE THREAD

**Issue by No-108** [microsoft/vscode#141819] opened 2022-01-30 05:53 UTC
Issue Type: <b>Bug</b>

Python2 has been removed in macOS 12.3(public beta), so the command 'code' will raise the error:

/usr/local/bin/code: line 6: python: command not found
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory

This problem can be resolved by changing 'python' in /usr/local/bin/code: line 6 to 'python3'.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id db925b98-7877-4d19-a368-67de695e4518|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
gitignore|cod|0.7.0
highlight|deb|0.1.0
gitlens|eam|11.7.0
shell-format|fox|7.2.2
gc-excelviewer|Gra|4.0.50
output-colorizer|IBM|0.1.2
latex-workshop|Jam|8.23.0
better-cpp-syntax|jef|1.15.10
better-shellscript-syntax|jef|1.1.0
vsc-python-indent|Kev|1.14.2
vscode-leetcode|Lee|0.18.0
MagicPython|mag|1.1.0
rainbow-csv|mec|2.0.0
render-crlf|med|1.5.22
git-graph|mhu|1.30.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
autodocstring|njp|0.5.4
vscode-python-typehint|njq|1.4.1
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
vscode-yaml|red|1.3.0
shellman|Rem|5.6.0
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.16
vscode-icons|vsc|11.8.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop804cf:30404767
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by haykam821** [comment] 2022-01-30 06:18
This seems to be a duplicate of #141738.

**Closed** 2022-01-30 06:20 UTC
