### ISSUE TITLE
Asyncawait + Fibers = extension errors

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#12819] opened 2016-09-27 20:38 UTC
- VSCode Version: 1.5.2
- OS Version: 10.10.5

I created a new extension using `asyncawait` which utilizes `node-fibers`:

```
"dependencies": {
    "asyncawait": "^1.0.6",
    "bluebird": "^3.4.6",
    "copy-paste": "^1.3.0",
    "open": "0.0.5",
    "request": "^2.74.0"
  }
```

```
'use strict';

const vscode = require('vscode');
const request = require('request');
const copyPaste = require('copy-paste');
const open = require('open');
const async = require('asyncawait/async');
const await = require('asyncawait/await');
const Promise = require('bluebird');
```

I get the following error when starting up my extension:

```
Activating extension `MyLaptop.vscode-myextension` failed: `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?.
Activating extension `MyLaptop.vscode-myextension` failed:  `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?
Here is the error stack:  Error: `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/Users/user1/Repos/vscode-myextension/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.L.I.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:25921)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/user1/Repos/vscode-myextension/node_modules/asyncawait/src/fibers.js:1:92)
    at Module._compile (module.js:413:34)
```

I reinstalled `node-fibers` but continued to get the same errors. I know there were some issues a while back (#1556) and I'm not sure if this is related or not. I don't see any issues related to `node-fibers`. Any clues?

Also, I'm using just plain JS. Not TypeScript for the extension.

**Comment by Jakobud** [comment] 2016-09-27 21:11
Brought this up with Fibers as well and it looks like it's something to do with npm not installing Fibers correctly?

https://github.com/laverdet/node-fibers/issues/310#issuecomment-249994053

Also the author recommends moving on from Node 5.x. Is this something VSCode is considering anytime in the near future, especially since 6.x is LTS and 5 isn't?

**Comment by joaomoreno** [comment] 2016-09-28 07:30
Duplicate of #658, we don't support native dependencies yet.

**Closed by joaomoreno** 2016-09-28 07:30 UTC

**Comment by Jakobud** [comment] 2016-09-28 14:45
Does VSCode use Node 5.10.x or 6.6.0 now internally?

**Comment by joaomoreno** [comment] 2016-09-28 15:00
The next release will be coming out with `6.5.0`. You can find this out in the dev tools: `process.versions.node`.

**Comment by Jakobud** [comment] 2016-09-28 15:29
For v 1.5.3 I'm seeing the 6.5.0 (https://github.com/Microsoft/vscode/blob/1.5.3/appveyor.yml) used. But is 1.5.3 not released yet? I still am on 1.5.2 but haven't gotten any sort of update notification. But I do see it here: https://code.visualstudio.com/updates

**Comment by joaomoreno** [comment] 2016-09-28 16:28
1.6.0 went through 2 Electron updates, each of which had a different Node version. Follow [this value](https://github.com/Microsoft/vscode/blob/master/package.json#L4) to know what's the correct version.

**Comment by Jakobud** [comment] 2016-09-28 16:42
Thanks for your help!

**Comment by bpasero** [comment] 2016-09-28 16:44
@joaomoreno @Jakobud https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#electron-update

**Comment by Jakobud** [comment] 2016-09-28 18:35
Excellent thank you
