### ISSUE TITLE
Print option in File menu

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#26991] opened 2017-05-20 10:54 UTC
Please add a Print option to the application in the File menu.

While many scripts wont necessarily be printed onto paper due to code length etc having the option to print to pdf which would preserve code keyword colouring, formatting etc would be very useful for inclusion of code sections into training documents etc

**Comment by yfdyh000** [comment] 2017-05-20 22:58
Duplicate of #25374

**Closed** 2017-05-21 21:34 UTC
Labels: duplicate
