### ISSUE TITLE
Plug in icon is not hidden, but not displayed

### ISSUE THREAD

**Issue by mengyilingjian** [microsoft/vscode#99928] opened 2020-06-12 01:46 UTC
- VSCode Version: 1.46.0 (user setup)
- 提交: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
- 日期: 2020-06-10T09:03:20.462Z
- Electron: 7.3.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.wsl中使用win10子系统开发。插件不显示
![image](https://user-images.githubusercontent.com/34885772/84455813-e37b5400-ac90-11ea-84cc-9db54267013b.png)
![image](https://user-images.githubusercontent.com/34885772/84455861-0443a980-ac91-11ea-8c51-44802fc5eb5a.png)

**Comment by sandy081** [comment] 2020-06-12 12:26
Maybe the same problem as in #92323?

Can you use the network tab on the developer tools and see if the svg icon is correctly loaded?
Check the response header like seen in #92323 (comment)

**Comment by aeschli** [comment] 2020-06-26 14:32
duplicate of https://github.com/microsoft/vscode/issues/97564

**Closed by aeschli** 2020-06-26 14:32 UTC
