### ISSUE TITLE
Missing Breakpoints

### ISSUE THREAD

**Issue by kps84094** [microsoft/vscode#103047] opened 2020-07-21 22:21 UTC
Issue Type: <b>Bug</b>

After the last update, breakpoints are no longer showing to the left of line numbers and when I break at a breakpoint, the line does not highlight.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.4
xml|Dot|2.5.1
python|ms-|2020.7.94776
debugger-for-chrome|msj|4.12.9
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0

</details>

**Comment by isidorn** [comment] 2020-07-27 11:45
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by kps84094** [comment] 2020-07-27 16:42
I can reproduce the bug in the Insiders version.  I am programming in
JavaScript and using the Debugger for Chrome v4.12.9 extension.  When I
click on a line to add a breakpoint, a breakpoint appears in the
BREAKPOINTS tab.  If I click the same breakpoint in the editor, a second
breakpoint is added to the BREAKPOINTS tab instead of removing the
breakpoint.  I can only remove breakpoints from the BREAKPOINTS tab.  My
breakpoints also only appear to the left of the line numbers in the editor
when my code is not running with the Chrome extension.  I have attached an
image of the editor window to show what is happening.

Let me know if you need additional information.

[image: VSCodeBug.png]

**Comment by isidorn** [comment] 2020-07-28 08:46
Sounds like breakpoints get moved by the js-debug extension. I am not sure if there is anything to fix here, but moving to @connor4312 to decide what is best to be done here.

**Comment by connor4312** [comment] 2020-07-28 14:59
Please do two things:

1. Check if the issue still happens on [js-debug nightly](https://github.com/microsoft/vscode-js-debug/#nightly-extension)
1. If so, copy a trace log using these instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by connor4312** [comment] 2020-08-03 22:13
Closing due to lack of info

**Closed by connor4312** 2020-08-03 22:13 UTC
Labels: debug, needs more info
