### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by KurtdeSouza** [microsoft/vscode#119036] opened 2021-03-16 02:41 UTC
Issue Type: <b>Performance Issue</b>

anytime I click  away from the window white pixels show up everywhere but when I mouse over them they go away

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.05GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/kurtd/Desktop/flask|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	 17304	code main
    0	   143	  2484	   gpu-process
    0	    25	  9596	   crashpad-handler
    0	    82	 10528	   window (Issue Reporter)
    0	   213	 13668	   window (index.html - flask - Visual Studio Code)
    0	    12	 13776	     watcherService 
    0	    11	 10616	       console-window-host (Windows internal process)
    0	    70	 17004	     searchService
    0	   154	 19116	     extensionHost
    0	   114	 14172	       electron_node tsserver.js 
    0	   102	 16300	       "C:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=19116
    0	   279	 18244	       c:\Users\kurtd\.vscode\extensions\ms-python.python-2021.2.636928669\languageServer.0.5.59\Microsoft.Python.LanguageServer.exe
    0	    11	  5772	         console-window-host (Windows internal process)
    0	   130	 18524	       electron_node tsserver.js 
    0	    94	 17684	         electron_node typingsInstaller.js typesMap.js 
    0	    70	 18848	       "C:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19116
    0	    77	 18880	       "C:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\kurtd\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=19116
    0	    95	 16740	   shared-process
    0	    70	 16456	     ptyHost
    0	    74	 16804	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	     7	 17544	       console-window-host (Windows internal process)
    0	    44	 18632	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - flask - Visual Studio Code)
|    Folder (flask): 1942 files
|      File types: py(900) pyc(656) h(24) txt(21) exe(21) rst(7) pyd(7) png(4)
|                  virtualenv(3) bat(3)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.2.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
cpptools|ms-|1.2.2
vscode-paste-image|mus|1.0.4
java|red|0.76.0
vscodeintellicode|Vis|1.2.11
vscode-arduino|vsc|0.3.5
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by IllusionMH** [comment] 2021-03-16 03:51
/duplicate of #117491

See for current workaround #93356 (comment) and also #115189 (comment) as one of ways problem was resolved

**Closed** 2021-03-16 03:52 UTC
Labels: *duplicate, new release
