### ISSUE TITLE
V1.59 terminal bug

### ISSUE THREAD

**Issue by tys1244147276** [microsoft/vscode#130405] opened 2021-08-09 11:57 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.when i update vscode to 1.59,and restart it,then i open the terminal viewport
2.the terminal view is messy, word spacing becomes particularly wide，until i delete this terminal viewport,and restart it ,it work normal
This problem did not occur in previous versions，until I updated it this morning

**Comment by meganrogge** [comment] 2021-08-09 13:39
sounds like https://github.com/microsoft/vscode/issues/120004

I can't reproduce this.

**Comment by meganrogge** [comment] 2021-08-17 19:56
likely a duplicate of #120004

**Comment by meganrogge** [comment] 2021-08-17 19:58
Please include steps to reproduce the issue and a gif

**Comment by meganrogge** [comment] 2021-08-17 20:23
duplicate of #130751

**Closed by meganrogge** 2021-08-17 20:23 UTC
Labels: needs more info, *duplicate
