### ISSUE TITLE
Creating New Folder in New Folder

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode#71279] opened 2019-03-27 10:44 UTC
- VSCode Version:
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new folder
2. Create a new folder in the new folder by just clicking the icon "New Folder" (The new Folder is already marked by vs code)

Tree View is freezing
#Edit: The View is freezing if I just go on it will create the new Folder, but you can't see that
Important don't remark the folder by mouse clicking just hit 2 times "New Folder"

Does this issue occur when all extensions are disabled?: Yes

**Comment by peni4142** [comment] 2019-03-27 10:45
I did that already, but I think that a duplicate, but I am not sure at all.

**Comment by bpasero** [comment] 2019-03-27 13:20
I do not think this is a freeze but rather a tree/explorer UI issue.

**Comment by isidorn** [comment] 2019-03-27 13:25
New folder button is disabled for me. How do you actually accomplish what you are saying?
Can you reproducing using latest vscode insiders https://code.visualstudio.com/insiders/

![newFolder](https://user-images.githubusercontent.com/1926584/55079242-12150b00-509c-11e9-9812-31091e6efcf2.gif)

**Comment by peni4142** [comment] 2019-03-28 09:57
1. click "new folder"
2. write a name
3. click enter
4. click "new folder"

**Comment by peni4142** [comment] 2019-03-28 10:11
![issue](https://user-images.githubusercontent.com/33463108/55149276-2c0d2700-514a-11e9-9a85-bb02bd78a8cf.gif)

**Comment by isidorn** [comment] 2019-03-28 10:12
Can you reproducing using latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by peni4142** [comment] 2019-03-28 10:55
works fine in insiders :-)

**Comment by isidorn** [comment] 2019-03-28 11:01
Closing then since it is fixed

**Closed by isidorn** 2019-03-28 11:01 UTC
Labels: file-explorer, needs more info
