### ISSUE TITLE
Orca can't be stopped in native dialogs

### ISSUE THREAD

**Issue by alex19EP** [microsoft/vscode#121811] opened 2021-04-21 11:59 UTC
Issue Type: <b>Bug</b>

open any native dialog about or check for updates.
press ctrl to stop speech.
orca should stop talking.

this issue similar to #93056

VS Code version: Code - Insiders 1.56.0-insider (b4816cfd1f4161a3bb272354d181a9947760ee26, 2021-04-20T07:24:33.853Z)
OS version: Linux x64 5.11.15-arch1-2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 1005M @ 1.90GHz (2 x 1900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.70GB (0.64GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 9fe453d7-430e-46b5-bfd9-60af52319e71|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
meson|asa|1.3.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
vscode-astyle|chi|0.9.0
systemd-unit-file|coo|1.0.6
vscode-github-actions|csc|0.17.0
vscode-markdownlint|Dav|0.40.3
githistory|don|0.6.16
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-pull-request-github-insiders|Git|2021.4.29343
markdown-extended|jeb|1.0.19
better-cpp-syntax|jef|1.15.5
restructuredtext|lex|148.0.0
kconfig|luv|1.0.3
vscode-docker|ms-|1.12.1
vscode-language-pack-ru|MS-|1.55.2
python|ms-|2021.5.746022950-dev
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.6.751425733
remote-containers|ms-|0.169.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.0
cmake-tools|ms-|1.7.0
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|0.18.0
platform-settings|run|0.0.2
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
cmake|twx|0.0.17
grammarly|znc|0.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931cf:30280410
vscnewfiletextcf:30288478
vshan820:30276952
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by alex19EP** [comment] 2021-04-21 12:02
ping @isidorn @joanmarie

**Comment by joanmarie** [comment] 2021-04-21 13:14
I can take a look later, but if Orca doesn't interrupt speech and Orca commands fail to work then that means Orca is not being notified of input events.

**Comment by isidorn** [comment] 2021-04-21 13:19
@alex19EP was this working before?
Asking because we just updated to Electron12 and that might have broken this

**Comment by jvesouza** [comment] 2021-04-21 13:38
@isidorn The problem manifested itself after upgrading to electron version 12.04.
Another side effect is that I am now unable to use the orca's flat review mode to explore the dialogue.

**Comment by joanmarie** [comment] 2021-04-21 14:44
If flat review mode doesn't work at all (as opposed to presenting the wrong object), that's the same problem: Orca doesn't know you pressed any key (e.g. the key to review the current word/line/char/object/etc.).

**Comment by isidorn** [comment] 2021-04-21 15:02
Also assigning to @deepak1556 for the electron update

**Comment by webczat** [comment] 2021-04-21 17:13
looks to me like chrome regression as this probably also doesn't work in newest unstable. Was like that for some time, but because I haven't updated for few weeks, not sure.

**Comment by jvesouza** [comment] 2021-06-28 09:09
Any news regarding this issue? It is still present in the version that uses electron 12.0.12.

Thanks.

**Comment by webczat** [comment] 2021-06-28 09:16
but, newer chrome-dev doesn't seem to have it, so I think it's gonna be fixed soon.

**Comment by isidorn** [comment] 2021-06-28 10:59
I tried to search for an issue in the Chromium repository but I failed.
@joanmarie might you maybe know the when Chrome fixed this? Asking because if it is a simple fix we could backport it to our Electron version.

**Comment by jvesouza** [comment] 2022-02-10 08:03
Except for errors on my part, this problem is still present even after updating to electron 16.

**Comment by isidorn** [comment] 2022-02-21 17:39
@webczat you mentioned that newer chrome versions have this fixed? Can you confirm that in the latest stable chrome this is working?

**Comment by webczat** [comment] 2022-02-21 17:45
hmm that is kinda weird because this bug seems to disappear and reappear. my current test after update few days ago is:
seems fixed in 98.0.4758.102
however, seems not fixed in 100.0.4892.0

**Comment by isidorn** [comment] 2022-02-21 17:46
@webczat would you be so kind to file an issue https://bugs.chromium.org/p/chromium/issues/list
And then we can start talking to Googlers and @joanmarie so they investigate.

**Comment by joanmarie** [comment] 2022-03-14 10:26
The bug (fixed in 2020) is https://bugs.chromium.org/p/chromium/issues/detail?id=1042864 which landed in 86.0.4199.0.

Regarding what @webczat stated about it became unfixed, newer versions of Chrome/Chromium for some reason do not autofocus the open/save-as dialogs. This is true for all users rather than an accessibility thing. I have to press Alt+F6 or click on it before I can interact with it. But once that dialog is focused, Orca's commands work for me.

**Comment by jvesouza** [comment] 2022-03-14 11:21
Just in order to help, I'm posting here the steps I use to reproduce the problem.

1. Make sure that orca is running.
2. Launch VSCode.
3. Press alt+h and locate the about menu using the up arow.
4. Press the enter key.
5. When the orca starts to announce the information contained in the about dialog, try to silence it by pressing the ctrl key.

The orca is not silenced even if I press other keys. I need to wait for it to announce all the text so I can go back to interacting with the keyboard.

**Comment by joanmarie** [comment] 2022-03-14 13:19
@jvesouza: Thanks! I'm afraid the TL;DR version is "Yup. I know. Did the Chromium bug fix I mentioned make it into Electron yet?"

Here's the long version:

I can reproduce it, just as you described. I'm afraid it's still https://bugs.chromium.org/p/chromium/issues/detail?id=1042864. The title/summary of that bug is "Key events are not emitted for native dialogs (Open, Save As, VSCode's About)".

Here are some Orca-free steps to reproduce the problem described by @jvesouza:
1. Download `key-events.py`, the accessible event listener attached to the Chromium bug I mentioned above.
2. Launch that listener in a terminal
3. Launch VSCode
4. Press Alt+h and locate the about menu using Up Arrow.
5. Press enter/return
6. In the resulting dialog, press Tab a bunch of times to switch focus between the buttons
7. Press Escape to close the dialog
Expected results: All key presses would show up in the terminal
Actual results: As soon as the dialog has focus, no key presses show up in the terminal. Here's what I see:
```
Alt_L pressed
h pressed
Up pressed
Return pressed
```

That's it. No Tab (which I pressed a ton) and no Escape. Nothing gets logged until I exit that "About" dialog.

In other words, Orca has no idea that you pressed any keys as soon as you are in the About dialog. Ditto for Open and Save As. 

Why that impacts this VSCode bug: Orca shuts up speech in response to your pressing keys. If it doesn't know you pressed a key, it cannot do the shutting up. See my [earlier comment](https://github.com/microsoft/vscode/issues/121811#issuecomment-824051266).

Similarly, Orca commands work by being notified of key presses and then determining a given key press matches an Orca command. For instance, if Orca knows you pressed KeyPad 8, it reviews the current line. If the app doesn't tell Orca you pressed KeyPad 8, *crickets*. See [this comment](https://github.com/microsoft/vscode/issues/121811#issuecomment-824118484).

Having said all that, the fix for the Chromium issue can be found on the bug itself. Here is a direct link to the [commit](https://chromium.googlesource.com/chromium/src.git/+/7d8454047353a39af3dbf134a3fbc3ff4852868a). Again, it landed in 2020 and Orca commands work for me in native dialogs in Chrome/Chromium. So either the fix is not yet included in the versions of Electron being used, or we have an unaddressed variant of the same bug.

Make sense?

**Comment by isidorn** [comment] 2022-03-14 14:25
@joanmarie latest VS Code Insiders uses Electron 17 that uses Chrome 98 so that fix is in.
The latest VS Code stable uses Electron 13 which uses Chrome 91 so that fix should also be in. fyi next stable will also jump to Electron 17.

**Comment by joanmarie** [comment] 2022-03-14 15:04
That is interesting. I wonder what the difference is....

In the meantime I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1306015.

**Comment by jaragunde** [comment] 2022-03-17 09:12
Hello, I've taken a look to the Chromium side of things, having fixed this bug originally: https://crbug.com/1042864

I think I found a change in Electron that could have broken this behavior: https://github.com/electron/electron/commit/fa65faa4b0221dfd6e5d64abcff01321640a19ad

Before this change, gtk::SetGtkTransientForAura() was always called, but after that, it's only called under this condition:
```
      if (*supports_gtk_file_chooser_native) {
        dl_gtk_native_dialog_set_modal(static_cast<void*>(dialog_), TRUE);
      } else {
        gtk::SetGtkTransientForAura(GTK_WIDGET(dialog_),
                                    parent_->GetNativeWindow());
        gtk_window_set_modal(GTK_WINDOW(dialog_), TRUE);
      }
```

The call to gtk::SetGtkTransientForAura() is what enables Chromium to redirect keyboard events addressed to the dialog, to the corresponding ATK API, according to the solution to the bug: https://crbug.com/1042864

So, I think it's not a bug in Chromium, but in Electron.

**Comment by jaragunde** [comment] 2022-03-17 09:30
To be clear, I think we should move the call to `gtk::SetGtkTransientForAura` outside of the if. And this would fix the problem for file dialogs, there must be similar code for other native dialogs (printing or app-defined dialogs like VSCode "about").

**Comment by isidorn** [comment] 2022-03-17 10:50
@jaragunde. @joanmarie this is awesome! Thanks a lot for this investigation. Yes, we do have ways to patch Electron.
@deepak1556 can we try to patch Electron as @jaragunde suggests. What do you think?

Let me assign to this milestone so we do not loose track of this. And if @deepak1556 you do not have time feel free to push out to April. Thanks!

fyi @tristan957 as the author of that commit

**Comment by tristan957** [comment] 2022-03-17 13:28
I went back into the original PR because I had remembered writing an alternative implementation of this function. I found this: https://github.com/electron/electron/pull/19159/#discussion_r454078946.

So it seems like I removed my custom implementation because nobody really ever answered my questions.

There are two important calls within `SetGtkAuraTransientFor()`:

* https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/gtk_util.cc;l=165
* https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/gtk_util.cc;l=169

If the first call is what allows orca to do its thing, then we have problems. The implementation of that function on both X11 and Wayland assumes you are using a GtkWidget, which GtkNativeDialog is not, so you have no way of accessing any underlying GdkWindow. If it is the second call, we probably will be able to work with that.

A workaround for the VSCode release is to not set `GTK_USE_PORTAL=1` in the `code.sh` file. Users would opt in to native dialogs on Linux. Doing this could use a release notes snippet.

**Comment by joanmarie** [comment] 2022-03-23 14:16
@tristan957: How hard would it be to do a try build with the second call so we can test?

**Comment by tristan957** [comment] 2022-03-23 14:24
Not that hard I would think. How does Orca usually know how to jump from a window to a presented dialog?

**Comment by joanmarie** [comment] 2022-03-23 14:40
It's not the jumping that we care about here. Orca knows it's in the presented dialog already thanks to`window:activate`, `object:state-changed:active`, and `object:state-changed:focused` accessibility events.

The bug is that Orca is not notified about *keyboard events* from the dialog. So when, for instance, the About dialog appears, Orca starts speaking it. And Orca won't shut up in response to the user pressing a key, like `Ctrl`, because the dialog doesn't tell Orca that a key was pressed.

There's an Orca-free way to reproduce the issue described in https://github.com/microsoft/vscode/issues/121811#issuecomment-1066775835.

**Comment by tristan957** [comment] 2022-03-30 22:39
So I see new VSCode has been released. I will look into this this week. I think there is one PR that can be submitted to electron upstream, which is re-adding that gobject_set_data() referenced in the other comment. I will see if I can reproduce the issue after making that change and let you all know. Otherwise, I will have to look into Wayland and X11 stuff...ugh. Hard to find people who are knowledgeable enough and actually care. If anyone knows someone at Canonical or Igalia, now is the time to reach out. Would hate for people relying on screen reading to have a permanent disadvantage when using Electron applications on Linux.

**Comment by tristan957** [comment] 2022-04-15 20:38
I came back to look at this, and I am pretty sure what I want to do is impossible, so this is just stuck unless Electron moves to GTK4. Alternatively just revert the PR upstream in Electron.

**Comment by isidorn** [comment] 2022-04-19 13:59
@tristan957 thanks for looking into this. I know @deepak1556 plans to investigate from the Electron side and then we will have more details.

**Comment by tristan957** [comment] 2022-04-19 14:55
So in re-reviewing my research, my idea isn't even possible in GTK4.

The barrier here is that there is no way to poke at the underlying native window through the GtkFileChooserNative API. The window is created out of process (?) using a D-Bus call. The native window is necessary for `SetGtkTransientForAura()` whether it be X11 or Wayland.

So the best idea might be to revert the GtkFileChooserNative PR and instead use the kdialog approach that upstream Chromium might still be doing.

**Comment by jvesouza** [comment] 2022-08-13 15:45
Hello guys, is there any news regarding this problem?
Thank you very much in advance.

**Comment by deepak1556** [comment] 2022-08-15 05:01
There is discussion in https://github.com/electron/electron/pull/35110 to refactor the file dialog implementation to reuse implementation from chromium and I believe that would allow to resolve this issue as well. I need to check with Electron maintainers to see if this is already on plan for this month.

**Comment by alex19EP** [comment] 2022-08-15 10:14
@deepak1556 hello. file open dialog aren't only one native window in code which exhibits such behavior with orca.
I know at least:

* about dialog
* save confirmation dialog

**Comment by jvesouza** [comment] 2022-11-27 22:06
Hello to everyone.
 Without taking the risk of sounding too boring, is there anything new about this issue?
Thank you very much and forgive me for the insistence.

**Comment by isidorn** [comment] 2022-11-28 09:13
@jvesouza thanks for the ping. 
@deepak1556 maybe we try to put this on the plan some time in the future, what do you think?

fyi @meganrogge

**Comment by deepak1556** [comment] 2022-12-08 08:17
@isidorn yup sounds good, we would first need to refactor the dialog implementation in Electron https://github.com/electron/electron/pull/35110#issuecomment-1200044072

I am optimistically adding this to February 2023 milestone.

**Comment by jvesouza** [comment] 2023-04-13 10:49
Once again, forgive me for being annoying, but now that VSCode is using Electron 22, is there any possibility of fixing this bug?

**Comment by isidorn** [comment] 2023-04-13 12:09
@jvesouza thanks for the ping. I know @deepak1556 has this on the plan and plans to investigate more this or next milestone. I expect us to have more details soon. Thank you for your understanding.

**Comment by jvesouza** [comment] 2023-07-13 19:17
I don't have an explanation but it looks like this problem is gone. from the moment I started using the 45-alpha version of orca.
To confirm I downgraded to version 44.1 of orca and the problem returned.
Could anyone else confirm?

**Comment by joanmarie** [comment] 2023-07-14 08:49
@jvesouza: That would make sense. Due to issues related to Gtk4, Wayland, etc., we can no longer count on getting input events. :disappointed: 

We use (or rather used to use) input events to interrupt speech. Now, sadly, we have to do this heuristically. It sounds like we're getting it right for VS Code with native dialogs. Yay! 

You may find other instances where speech gets incorrectly cut off, which should be reported on the Orca list and/or GitLab.

@isidorn et al.: With respect to this issue here, please note: I do NOT intend to backport the heuristics into earlier versions of Orca because I expect there will be regressions (plural). Heuristics are hard. Thus having the input events from the native dialogs used by VS Code will still be a requirement for Orca v44.x and earlier. Please and thank you. :smile:

**Comment by isidorn** [comment] 2023-07-14 09:00
@joanmarie makes sense :) Thanks a lot for fixing this in newer versions of Orca 👏

**Comment by jvesouza** [comment] 2023-07-14 09:19
> @jvesouza: That would make sense. Due to issues related to Gtk4, Wayland, etc., we can no longer count on getting input events. disappointed
> 
> We use (or rather used to use) input events to interrupt speech. Now, sadly, we have to do this heuristically. It sounds like we're getting it right for VS Code with native dialogs. Yay!
> 
I ended up not mentioning it in my previous comment, but the flat review mode is also working in this case.

**Comment by joanmarie** [comment] 2023-07-14 10:04
@isidorn: You forgot the fingerquotes around "fixing". :stuck_out_tongue:  (The history of accessible input events  in Linux is a long and contentious one.)

Also, you obviously should do what makes the most sense for your project. However, please be aware that Orca v45 (not released) requires the very latest version of AT-SPI2. As a result, Orca users not running the very latest version of their distro -- including those running LTS versions -- might not see this Orca "fix" for a while (years in the LTS case).

**Comment by isidorn** [comment] 2023-07-14 12:21
@joanmarie thanks for clarifying 😄 
Let's see what @deepak1556 says.

**Comment by tristan957** [comment] 2023-07-14 15:52
@isidorn we essentially need 1 of the following 2 things for a fix.

Implement a libportal-based file chooser dialog in Electron or inherit the file chooser dialogs from Chromium. I brought this up in the linked Electron issue somewhere above, but there has been no movement from their side.

The other option is to just revert the offending Electron commits.

**Comment by jvesouza** [comment] 2023-07-20 12:23
I don't know what changed, but the fact is that this problem also disappeared when I use version 44 of orca.
For me the change seems to have been in vscode because if I use version 1.80 of vscode together with orca 44 the problem returns, but if I use the insiders version of vscode together with orca 44 the problem does not happen.

**Comment by isidorn** [comment] 2023-11-24 14:50
I will optimistically go ahead and close this issue. Since we have updated electron multiple times.
If this issue still persists please let me know and I will reopen it. Thank you

**Closed by isidorn** 2023-11-24 14:50 UTC
Labels: bug, upstream, accessibility, linux, electron, native-file-dialog
