### ISSUE TITLE
Capitalization on MacOS

### ISSUE THREAD

**Issue by ksnyde** [Microsoft/vscode#52111] opened 2018-06-16 20:08 UTC
![image](https://user-images.githubusercontent.com/980757/41502041-5fc7d9a2-7165-11e8-8289-5745bb5ac715.png)

I'm finding a LOT of odd behavior on my Mac when I uppercase files. I know in part that MacOS is a bit half-hearted in it's distinction of capitalization which leads to a lot of confusion in the first place but `vs-code`'s ability to deal with this seems particular problematic.

In the screenshot above you see me on the latest version of vs-code (see below) trying to bring up the `Record.ts` file which was previous named `record.ts`. In the finder it's showing Uppercase version twice and the lowercase version once. 

![image](https://user-images.githubusercontent.com/980757/41502049-b726df5e-7165-11e8-994b-ee62463b68dd.png)
With another file, `List.ts` -- which has had the same renaming done -- it's a bit different/better:

![image](https://user-images.githubusercontent.com/980757/41502060-059826d4-7166-11e8-809e-9aa59dece548.png)

I could sort of understand that maybe the `List.ts` situation could come about if you were just caching recent requests and assuming that on the native OS `List` and `list` point to different files (they _wouldn't_ in MacOS). But the `Record` example strikes me as downright odd.

**Comment by ksnyde** [comment] 2018-06-16 20:09
BTW, I wish I could just get MacOS to be truly cap-sensitive but I doubt that will ever happen.

**Comment by RMacfarlane** [comment] 2018-06-17 05:55
@ksnyde Thanks for the clear write up, this is a duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by RMacfarlane** 2018-06-17 05:55 UTC
