### ISSUE TITLE
[json] End of file expected when formatting JSON.

### ISSUE THREAD

**Issue by brandenesmith** [microsoft/vscode#73500] opened 2019-05-09 01:13 UTC
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

### Steps to Reproduce:

1. Install Visual Studio Code.
2. Ensure that there are no extensions.
3. Create a new file.
4. Set the file type to JSON.
5. Enter the text: 
```JSON
{"test": true}
```
6. Press `alt+shift+F`
7. Observe that the document is not formatted. 
8. Observe an error in the console 
```
{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "0",
	"severity": 8,
	"message": "End of file expected.",
	"source": "json",
	"startLineNumber": 1,
	"startColumn": 16,
	"endLineNumber": 1,
	"endColumn": 17
}
```
### Screenshot 
<img width="1136" alt="Screen Shot 2019-05-08 at 8 04 53 PM" src="https://user-images.githubusercontent.com/7876230/57420337-ad85b980-71cc-11e9-8de0-4878c2d3e926.png">

### Note
This error does not occur on any of my other machines running Visual Studio Code 1.33.1 and macOS 10.14.4 however, I cannot seem to fix the problem by removing and re-installing Visual Studio Code.

### Things I've Tried
1. Restart the machine
2. Remove and Re-install Visual Studio Code
3. Remove Visual Studio Code and Re-install macOS, then re-install Visual Studio Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by brandenesmith** [comment] 2019-05-09 13:28
I should also note here that using the Format feature from the Command Pallet works just fine. That is using `cmd+shift+P` then selecting "Format Document" works and the formatting occurs.

**Comment by sturmenta** [comment] 2019-05-22 04:22
I'm having this problem installing the [Monokai Mega](https://github.com/jaszhix/monokaimega-vscode-theme) color theme

![](https://imgbbb.com/images/2019/05/22/Captura-de-Pantalla-2019-05-22-a-las-01.13.55.png)

**Comment by aeschli** [comment] 2019-10-10 09:45
It's the JSON validator that complains here.
I suspect you have a invalid (unicode) character right after the `}`.
Can you check?

**Comment by brandenesmith** [comment] 2019-10-11 18:42
@aeschli, it doesn't appear that there are any unicode characters after the closing brace. 
I opened a new document and entered the text: 
```
{"test": "string"}
```
I then used `alt+shift+F` and still get the error: 
![Screen Shot 2019-10-11 at 1 40 21 PM](https://user-images.githubusercontent.com/7876230/66676297-bc194680-ec2c-11e9-95c1-c794dcc27df6.png)

Using the command palette (i.e. `cmd+shift+P` and selecting "Format Document" works fine.

**Comment by aeschli** [comment] 2019-10-13 17:37
Now I can reproduce it. It's a Mac thing when you have `ABC extended' as your keyboard layout. Then `shift + option + f` inserts ` ̰` instead of formatting.
Looks like this issue was already discussed in https://github.com/Microsoft/vscode/issues/8914.
[A workaround](https://github.com/Microsoft/vscode/issues/8914#issuecomment-302867701) is to change to `ABC`

@alexandrudima Is the recommendation that we avoid using `Alt + shift + f` as shortcut for format?

**Comment by alexandrudima** [comment] 2019-10-14 07:53
Duplicate of #41024

**Closed by alexandrudima** 2019-10-14 07:53 UTC
Labels: json, needs more info
