### ISSUE TITLE
Can't see describe of extensions

### ISSUE THREAD

**Issue by lakid1** [Microsoft/vscode#59150] opened 2018-09-22 11:35 UTC
Issue Type: <b>Bug</b>

Hello I can't see describe of any extensions or describe of new update. Last time when I was using VS code I have at bottom of my screen white line from errors to option button.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment] 2018-09-24 11:39
@lakid1 Not sure if I understood your issue. Can you please provide screenshot of what you are seeing to get better understanding?

**Comment by lakid1** [comment] 2018-09-26 13:12
![image](https://user-images.githubusercontent.com/43139326/46082105-90046200-c19e-11e8-8770-f9af9a5d09d9.png)

**Comment by sandy081** [comment] 2018-09-26 14:31
@mjbvz Could be related to web view?

@lakid1 Can you please check if the other tabs are showing content?

**Comment by lakid1** [comment] 2018-09-26 14:38
Still the same. I am actually tried to reinstall vscode but no results.

**Comment by sandy081** [comment] 2018-09-26 21:00
@lakid1 You mean you do not see anything in `Contributions` tab?

Can you open developer tools and let us know if there are any errors?

**Comment by mjbvz** [comment] 2018-09-26 21:07
Duplicate of #57209 

Please try this in [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Closed by mjbvz** 2018-09-26 21:07 UTC
Labels: needs more info
