### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by RaxFord1** [microsoft/vscode#116195] opened 2021-02-09 13:02 UTC
My previous issue was closed #116127, but it's not a extension problem.

Visual Studio Code:
Version: 1.53.0 (user setup)
Commit: 8490d3d
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

I disabled all extensions with extension bisect and problem still occurs
I installed VS Code Insider and it has the same problems without any extensions.
![image](https://user-images.githubusercontent.com/30433545/107366905-57535200-6ae7-11eb-94c6-f503a57f7e1b.png)

Steps to Reproduce:

1. I dont know what led to this, but i used VS Code for some time and it started.
2. Afk some time and bug starts to show.

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/30433545/107246431-e9e8e800-6a38-11eb-9af4-aadf8137ad6a.png)

**Comment by RaxFord1** [comment] 2021-02-09 13:03
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [UI problem (#116127)](https://www.github.com/microsoft/vscode/issues/116127)

Same problem, not giving the right answer.

**Comment by misolori** [comment] 2021-02-09 14:32
This looks like a problem with your GPU. Have you tried updating your driver or disabling "image sharpening" in the nvidia control panel?

**Comment by IllusionMH** [comment] 2021-02-09 16:54
Same as recent #114552 which is duplicate of #93356

Could you please check if it is reproducible for you in Insiders builds? https://code.visualstudio.com/insiders/


Also check https://github.com/microsoft/vscode/issues/115189#issuecomment-768239687 look like Nvidia drivers may also affect rendering of Electron apps.

**Closed** 2021-02-09 18:54 UTC
Labels: *duplicate
