### ISSUE TITLE
When python is run in the built in vscode terminal, it takes a while to run the code and to close the terminal

### ISSUE THREAD

**Issue by Grey-Prince-Zote** [microsoft/vscode#113182] opened 2020-12-20 08:21 UTC
- VSCode Version: 1.5.2
- OS Version: MacOS Big Sur 11.0.1

Steps to Reproduce:

1. Install everything needed to run python in vscode (Python interpreter, Python extension)
2. Make a python fille
3. In the file type any piece of code e.g. print("Hello world")
4. run the file in the built in terminal. Opening and closing it will take a while even for 1 line of code, this does not happen in other code editors / IDE'S

Does this issue occur when all extensions are disabled?: No because python cannot be run without the extension

**Comment by Grey-Prince-Zote** [comment] 2020-12-20 08:22
It isn't included with those issues

**Comment by cvbge** [comment] 2020-12-20 21:42
Duplicate/related to #112346 ?

**Comment by meganrogge** [comment] 2020-12-22 21:32
duplicate of #112346

**Closed by meganrogge** 2020-12-22 21:32 UTC
