### ISSUE TITLE
formatting on save with ESLint extension is adding extra backslash characters

### ISSUE THREAD

**Issue by jgoux** [microsoft/vscode#152395] opened 2022-06-16 22:04 UTC
Hello,

Today, when ESLint is run through the VSCode extension, it inserts backslash near curly braces characters. I had it happen on my imports but also in template strings when I use variables.

Running ESLint through the CLI works as expected, no backslash inserted.

I was on a preview version of the ESLint extension so I downgraded to the stable release, but the issue persists, this is why I'm not sure it comes from the extension. As I'm using VSCode Insider maybe something broke here.

Before saving:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1443499/174183000-c9c828f7-f09d-4009-b0c2-88c8b5fa23a4.png">

After saving:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/1443499/174183388-2cea3b2e-c49a-4847-9402-7292da1a4523.png">

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.69.0-insider
6f7c824a826ff0ccaf4de05d6fe0aac3be7bc136
arm64
- OS Version: macOS Monterey 12.4

Steps to Reproduce:

I've made a small repro here: https://github.com/jgoux/prettier-repro#steps-to-reproduce

**Comment by curtislarson** [comment] 2022-06-17 00:47
Thank you for identifying the root issue, this was driving me crazy trying to figure out the cause since this was happening with both `ts` and `Deno` auto imports.

My specs

```
Version: 1.69.0-insider (Universal)
Commit: 6f7c824a826ff0ccaf4de05d6fe0aac3be7bc136
Date: 2022-06-16T05:16:31.837Z (19 hrs ago)
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
```

**Comment by Meligy** [comment] 2022-06-17 06:06
Not sure if ESLint. I'm seeing it in C# too.

And seems before any `}`, not just imports for example.

**Comment by Meligy** [comment] 2022-06-17 06:10
This might be a duplicate of https://github.com/microsoft/vscode/issues/152272

**Comment by dbaeumer** [comment] 2022-06-17 08:04
I can't reproduce this in 1.69.0-insider commit `fbf1cf3832d43088e27837dbb68d24ab65a098c1`

![cast](https://user-images.githubusercontent.com/1931590/174255022-3bbc05d8-1865-4a9f-8797-edc11da2cd6f.gif)

**Comment by dbaeumer** [comment] 2022-06-17 08:05
Do you have any other tools enabled that might touch the file. And can you check if you can reproduce this using the stable version of VS Code?

**Comment by curtislarson** [comment] 2022-06-17 08:40
Doesn't seem to happen on `1.68.1`, although it's probably been over a year since I've used non-insiders

**Comment by curtislarson** [comment] 2022-06-17 09:49
Auto imports seem to be behaving now but Search+Replace is still inserting an extra `\` on non focused/opened documents. Here's a repro with all extensions disabled on Insiders


https://user-images.githubusercontent.com/2141050/174274127-8be0c893-bc7e-4660-a0f1-7f6467a4a282.mov

**Comment by kevenleone** [comment] 2022-06-17 17:44
Same to me, anything??

**Comment by curtislarson** [comment] 2022-06-19 11:21
This is no longer occurring for me. Thanks to whoever fixed it!

**Closed** 2022-06-20 11:12 UTC
Labels: needs more info
