### ISSUE TITLE
Smart select test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#114146] opened 2021-01-11 12:06 UTC
```
[JavaScript Error: "Error: Cannot read property 'passes' of undefined" {file: "debugger eval code line 304 > eval" line: 2}]
deliverError@debugger eval code line 304 > eval:4:56
callFunction@debugger eval code:305:28
@debugger eval code:1:44
evaluateFunction@chrome://juggler/content/content/Runtime.js:355:60
callFunction@chrome://juggler/content/content/Runtime.js:102:41
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 [
  `[JavaScript Error: "Error: Cannot read property 'passes' of undefined" {file: "debugger eval code line 304 > eval" line: 2}]\n` +
    'deliverError@debugger eval code line 304 > eval:4:56\n' +
    'callFunction@debugger eval code:305:28\n' +
    '@debugger eval code:1:44\n' +
    'evaluateFunction@chrome://juggler/content/content/Runtime.js:355:60\n' +
    'callFunction@chrome://juggler/content/content/Runtime.js:102:41\n' +
    '_onMessage@chrome://juggler/content/SimpleChannel.js:165:37\n' +
    'receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42\n'
]
to DEBUG, open FIREFOX and navigate to file:///Users/runner/work/1/s/test/unit/browser/renderer.html?m=vs/editor/contrib/smartSelect/test/smartSelect.test
error Command failed with exit code 1
```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=61646&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0

**Comment by alexdima** [comment] 2021-01-11 12:26
@sandy081 I cannot correlate the log with a failure of a Smart Select test. I have found the last line printed by playwright to be bogus. e.g. https://github.com/microsoft/vscode/issues/114028 which had assertion failures in `callStack.test.js` but for which playwright reported at the bottom:
```
to DEBUG, open FIREFOX and navigate to file:///D:/a/1/s/test/unit/browser/renderer.html?m=vs/base/test/common/async.test
```

But the problem was not in `async.test`.

**Comment by alexdima** [comment] 2021-01-11 12:34
To make matters more confusing, I could not find anywhere in our sources the identifier `passes` and I also could not find it in `playwright` itself.

**Comment by alexdima** [comment] 2021-01-11 12:38
This is the top hit when I searched for this error message -- https://github.com/cypress-io/cypress/issues/4304 -- I wonder if we have a mocha reporter that could be acting up...

**Comment by alexdima** [comment] 2021-01-11 12:46
After a full text search for `.passes`, I think this might be a problem within `mocha` itself, as it has the most plausible usages of `.passes`: e.g.

```
	  TAPProducer.prototype.writeEpilogue = function (stats) {
	    // :TBD: Why is this not counting pending tests?
	    println('# tests ' + (stats.passes + stats.failures));
	    println('# pass ' + stats.passes); // :TBD: Why are we not showing pending results?

	    println('# fail ' + stats.failures);
	    this.writePlan(stats.passes + stats.failures + stats.pending);
	  };
```

**Comment by alexdima** [comment] 2021-01-11 16:54
Actually this just happened again without the stack trace involving `.passes`:

https://dev.azure.com/vscode/VSCode/_build/results?buildId=61663&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0&l=7399

And it is again pointing towards `SmartSelect`. I have finally found a decent way to find a failing test. Search fo `    1)`:

```
2021-01-11T15:46:50.9688860Z     âœ“ setEncoding - decode
2021-01-11T15:46:50.9790360Z     âœ“ create with mode
2021-01-11T15:46:50.9890720Z     1) bracket selection
2021-01-11T15:46:50.9991420Z     âœ“ disposes when underlying model is destroyed
2021-01-11T15:46:51.0092240Z     âœ“ Load does not trigger save
2021-01-11T15:46:51.0193290Z     âœ“ Load returns dirty model as long as model is dirty
```

So it is a SmartSelect test, the output at the end was correct!

**Comment by jrieken** [comment] 2021-01-12 10:27
I have fixed https://github.com/microsoft/vscode/issues/114190 and I am waiting for a stack trace. Locally, I doesn't fail. Neither when running in Firefox directly nor when running via playwright-FF

**Comment by jrieken** [comment] 2021-01-12 10:28
re https://github.com/microsoft/vscode/issues/114146#issuecomment-757929854

The error that happens accessing `stats.passes` should also be fixed with https://github.com/microsoft/vscode/issues/114190 because it does implement the stats-property on our "echo runner"

**Comment by jrieken** [comment] 2021-01-13 17:42
Ok, got a stack trace from some of the build machines

```
1) SmartSelect
       bracket selection:

      A=[1,6 -> 1,25] <> E=[1,2 -> 1,25]
      + expected - actual

      -false
      +true
      
  AssertionError@file:///Users/runner/work/1/s/test/unit/assert.js:184:21
  fail@file:///Users/runner/work/1/s/test/unit/assert.js:231:9
  ok@file:///Users/runner/work/1/s/test/unit/assert.js:251:19
  assertRanges@file:///Users/runner/work/1/s/out/vs/editor/contrib/smartSelect/test/smartSelect.test.js:170:24
  async*@file:///Users/runner/work/1/s/out/vs/editor/contrib/smartSelect/test/smartSelect.test.js:188:19
```

**Comment by alexdima** [comment] 2021-01-13 21:17
Another stack trace -- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=100424&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&l=17102

```
  1) SmartSelect
       bracket selection:

      AssertionError: A=[1,2 -> 1,24] <> E=[1,2 -> 1,25]
      + expected - actual

      -false
      +true
      
      at assertRanges (file:///Users/runner/work/1/s/out-build/vs/editor/contrib/smartSelect/test/smartSelect.test.js:170:24)
      at async Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/editor/contrib/smartSelect/test/smartSelect.test.js:188:13)

```

**Comment by alexdima** [comment] 2021-01-14 09:37
And another one -- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=100447&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9f64420a-c490-5fef-d5f3-2bef0000fb37&l=10733

```
  5351 passing (1m)
  12 pending
  1 failing

  1) SmartSelect
       bracket selection:

      AssertionError: A=[1,2 -> 1,24] <> E=[1,2 -> 1,25]
      + expected - actual

      -false
      +true
      
      at assertRanges (file:///D:/a/1/s/out-build/vs/editor/contrib/smartSelect/test/smartSelect.test.js:170:24)
      at async Context.<anonymous> (file:///D:/a/1/s/out-build/vs/editor/contrib/smartSelect/test/smartSelect.test.js:188:13)
```

**Comment by alexdima** [comment] 2021-01-14 10:14
I think this is caused by slowness of sorts. The provider has logic to stop computing after 30ms e.g. https://github.com/microsoft/vscode/blob/00f8540d793cb5eac1333f35fd68a355d89639f0/src/vs/editor/contrib/smartSelect/bracketSelections.ts#L50-L53

**Closed** 2021-01-14 10:21 UTC
Labels: firefox, unit-test-failure

**Comment by jrieken** [comment] 2021-01-14 10:52
I see. Thanks @alexdima
