### ISSUE TITLE
why cannot format xml file in the latest version??????

### ISSUE THREAD

**Issue by sayidzhang** [Microsoft/vscode#1054] opened 2015-12-07 02:20 UTC
in the previous version, i can still format a xml file, but in the latest version, why cannot?????

**Comment by Agetorp** [comment] 2015-12-07 09:33
duplicate of #71

There seems to be an extension to solve your problem: https://marketplace.visualstudio.com/items/DotJoshJohnson.xml

**Comment by aeschli** [comment] 2015-12-08 09:19
duplicate of #71

**Closed by aeschli** 2015-12-08 09:19 UTC
