### ISSUE TITLE
Emmet expansion not working for jsx tags inside other jsx tag prop

### ISSUE THREAD

**Issue by selrond** [microsoft/vscode#69041] opened 2019-02-20 11:40 UTC
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: 10.14.3

Example:

```jsx
<SomeComponent
  property={
    <AnotherComponent />
  }
/>
```
`AnotherComponent` is not expandable with `Emmet: Expand Abbreviation`, nor are any further nested components inside `property`

relevant section from my settings:

```json
"emmet.includeLanguages": {
  "javascript": "javascriptreact",
  "jsx": "javascriptreact",
  "jsx-attr": "javascriptreact",
  "css": "styled-css",
},
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment] 2019-02-27 18:08
@octref 

`property` here is an attribute. In html, attribute values are not a valid location for emmet abbreviation expansion. Therefore, no emmet expansion insider `property`.

To fix this, either the emmet extension should be able to parse jsx or emmet for jsx should be moved to an extension that can parse jsx.

**Comment by selrond** [comment] 2019-02-28 12:30
@ramya-rao-a thx for clarification, I like "emmet for jsx extension" approach more. Is it something I could implement, or should it come from vscode team as an internal adjustment?

**Comment by octref** [comment] 2019-03-03 19:51
@selrond Sorry I don't t think this issue is open for PR. There'll be quite some changes for this to happen.

**Comment by selrond** [comment] 2019-03-04 13:26
@octref could you provide some more details?

**Comment by octref** [comment] 2019-03-04 19:10
Emmet extension treats JSX attribute like HTML attribute, where emmet completion shouldn't happen.
Either making Emmet extension parse JSX or hook Emmet into an extension that parses JSX is not a small amount of change.

**Comment by selrond** [comment] 2019-03-05 09:50
Ok, so is there any hope for this, or none at all in the foreseeable future?

**Comment by selrond** [comment] 2019-03-05 09:53
@octref @ramya-rao-a one more question - if emmet is not supposed to work inside attributes, why `Wrap with abbreviation` works just fine there?

**Comment by octref** [comment] 2019-03-05 16:18
What I said apply to emmet completion not emmet command. Yes there's hope but I'm busy over other areas of work right now.

**Comment by rzhao271** [comment] 2020-11-17 19:03
Duplicate of #61474

**Closed** 2020-11-17 19:28 UTC
Labels: *duplicate, emmet, feature-request
