### ISSUE TITLE
Sometimes the code changes not visible on the git icon , unless I restart my vs code.

### ISSUE THREAD

**Issue by zeeshan-noor** [microsoft/vscode#201271] opened 2023-12-20 09:02 UTC
Type: <b>Performance Issue</b>

After update my vs code version , its occurs many time

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.63GB free)|
|Process Argv|--crash-reporter-id 07909bce-3925-4e14-8e2e-5b0fe1a25b82|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  9784	code main
    0	   270	  1276	window [1] (barcelona - Visual Studio Code)
    0	    95	  3676	window [2] (Issue Reporter)
    0	   236	 17496	extensionHost [1]
    0	    80	  6916	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Zeeshan.Noor\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=17496)
    0	   194	  8504	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Zeeshan.Noor\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.8\dist\server\server.js --node-ipc --clientProcessId=17496)
    0	   115	 22764	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\ZEESHA~1.NOO\AppData\Local\Temp\vscode-typescript\5ff7d90bfdfffbc948da\tscancellation-3e756b777ccd93cb2846.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations c:\Users\Zeeshan.Noor\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30,c:\Users\Zeeshan.Noor\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   212	 23248	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\ZEESHA~1.NOO\AppData\Local\Temp\vscode-typescript\5ff7d90bfdfffbc948da\tscancellation-daa52920c6608a214f5a.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations c:\Users\Zeeshan.Noor\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30,c:\Users\Zeeshan.Noor\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.30 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    82	 31428	       electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/Zeeshan.Noor/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/Zeeshan.Noor/AppData/Local/Microsoft/TypeScript/5.3 --enableTelemetry --typesMapLocation "c:/Users/Zeeshan.Noor/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation)
    0	    81	 23664	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Zeeshan.Noor\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js --node-ipc --clientProcessId=17496)
    0	    97	 31544	     electron-nodejs ("C:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Zeeshan.Noor\.vscode\extensions\streetsidesoftware.code-spell-checker-3.0.1\packages\_server\dist\main.cjs --node-ipc --clientProcessId=17496)
    0	    30	 18144	   crashpad-handler
    0	    42	 22948	   utility-network-service
    0	    95	 23864	shared-process
    0	   147	 24544	   gpu-process
    0	    83	 26060	ptyHost
    0	     8	 21548	     conpty-agent
    0	     8	 25676	     conpty-agent
    0	     7	 25892	     C:\Users\Zeeshan.Noor\AppData\Local\Programs\Git\bin\bash.exe --login -i
    0	    13	 22916	       "C:\Users\Zeeshan.Noor\AppData\Local\Programs\Git\bin\..\usr\bin\bash.exe" --login -i
    0	    66	 30460	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Zeeshan.Noor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    79	 26760	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (barcelona - Visual Studio Code)
|    Folder (barcelona): 1220 files
|      File types: html(427) js(118) tsx(95) pack(71) json(67) ts(58) scss(28)
|                  css(10) yml(8) svg(6)
|      Conf files: package.json(3) dockerfile(2) settings.json(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.5
codium|Cod|0.7.26
vscode-eslint|dba|2.4.2
gitlens|eam|14.6.1
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
git-graph|mhu|1.30.0
vscode-docker|ms-|1.28.0
vsliveshare|ms-|1.0.5900
vscode-thunder-client|ran|2.16.3
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|5.1.0
code-spell-checker|str|3.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vikings-icon-theme|wil|1.0.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by kth-tw** [comment] 2023-12-20 10:35
Same issue on my mac vscode 1.85.1

**Comment by lszomoru** [comment] 2023-12-20 11:31
@zeeshan-noor, @kth-tw, could you please try the latest VS Code Insiders release? There are some known issues, that have already been fixed in VS Code Insiders and it would be great if you could try it out and confirm that the fixes are working as expected. Thanks!

**Closed** 2023-12-21 10:01 UTC
Labels: bug, info-needed, git

**Comment by alexr00** [comment] 2024-01-25 10:44
@lszomoru is there anything that should be verified here?

**Comment by lszomoru** [comment] 2024-01-26 10:32
I believe that the root cause of this is related to https://github.com/microsoft/vscode/issues/200636. Marking this as duplicate.
