### ISSUE TITLE
Allow configuration files to use extension .jsonc

### ISSUE THREAD

**Issue by brettrowberry** [microsoft/vscode#191988] opened 2023-09-01 13:09 UTC
VS Code allows workspace configuration via JSON files in the `.vscode` directory, e.g. `settings.json`, `extensions.json`, `tasks.json`, etc. GitHub Linguist treats them as JSON for syntax highlighting. This leads people to believe that comments aren't allowed in these files, but they are.

I propose allowing these files to use the extension `.jsonc`, in addition to or instead of `.json`.

See https://github.com/github-linguist/linguist/pull/6533 for context.

**Comment by aeschli** [comment] 2023-09-04 12:27
Duplicate of https://github.com/microsoft/vscode/issues/189385

We have currently no plans for such a change. It's a good idea and I wished we would have used `jsonc` from the very beginning, but changing this now just adds additional complexity. In our opinion the benefits are small and do not justify the swirl.

**Closed by aeschli** 2023-09-04 12:27 UTC
