### ISSUE TITLE
Wrong position of block indicator line

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#53337] opened 2018-06-29 14:27 UTC
- VSCode Version: 1.24.1
- OS Version: MacOs

When my cursor is on the "else" keyword i got this : 
![image](https://user-images.githubusercontent.com/5599375/42097741-2fa43028-7bb9-11e8-80e5-b4d4c133575f.png)

Where it should be here : 
![image](https://user-images.githubusercontent.com/5599375/42097778-495afd58-7bb9-11e8-8997-11f6b980d386.png)

**Comment by alexandrudima** [comment] 2018-07-02 07:45
Duplicate of #49342

**Closed by alexandrudima** 2018-07-02 07:45 UTC
Labels: editor
