### ISSUE TITLE
Formatting issue in latest version 1.9.0

### ISSUE THREAD

**Issue by kishanmundha** [Microsoft/vscode#19972] opened 2017-02-05 11:55 UTC
Hi team,

I just update my vscode, in previous version I see that vscode won't wok formatting with inline style html attributes. Thanks you fixed that issue in new version but now I see a another issue with formatting.

Now it behave different-different formating issue on different condition.

### Input

``` html
<html>

<body>
    <input id="key" placeholder="key" value="key1" />
    <input id="value" placeholder="value" value="value1" />
    <button id="submitBtn">Add/Update</button>

<script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXX",
    authDomain: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
    databaseURL: "https://XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
    storageBucket: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
    messagingSenderId: "XXXXXXXXXXXX"
  };
  firebase.initializeApp(config);
</script>
</body>

</html>
```

### Output

```
<html>

<body>
    <input id="key" placeholder="key" value="key1" />
    <input id="value" placeholder="value" value="value1" />
    <button id="submitBtn">Add/Update</button>

    <script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
    <script>
        // Initialize         rebase
  var co             = {
    apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX            XX",
    authDomain: "XXXXXXXXX-XXXXX.XXXXXXXXX            XX",
    databaseURL: "https://XXXXXXXXX-XXXXX.XXXXXXXXX            XX",
    storageBucket: "XXXXXXXXX-XXXXX.XXXXXXXXX            XX",
    messagingSenderId: "XXXXX        XXXX        
  };
  firebase.initializeApp(config);

    </script>
</body>

</html>
```

In this example I also lost some data

### Input

``` html
<html>

<body>
    <input id="key" placeholder="key" value="key1" />
    <input id="value" placeholder="value" value="value1" />
    <button id="submitBtn">Add/Update</button>

    <script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
    <script>
    // Initialize Firebase
    var config = {
        apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXX",
        authDomain: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
        databaseURL: "https://XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
        storageBucket: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX",
        messagingSenderId: "XXXXXXXXXXXX"
    };
    firebase.initializeApp(config);
    </script>
</body>

</html>
```

### Output

```
<html>

<body>
    <input id="key" placeholder="key" value="key1" />
    <input id="value" placeholder="value" value="value1" />
    <button id="submitBtn">Add/Update</button>

    <script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
    <script>
            // Initialize Fireba            var config =                apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXX                authDomain: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX                databaseURL: "https://XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX                storageBucket: "XXXXXXXXX-XXXXX.XXXXXXXXXXX.XXX                messagingSenderId: "XXXXXXXXXXX                        firebase.initializeApp(config    </script>
</body>

</html>
```

In this example all data moved after comment

> If I lost data or my code moved to comment then we can't trust on format command. **Please fix this issue ASAP**

- VSCode Version: 1.9.0
- OS Version: 7 SP 1

**Comment by hzmnet** [comment] 2017-02-05 14:01
It  also could not format correctly!  

 `<script>
  (  function () {
        'use strict';
    }
     );

</script>`

**Comment by tarunzoot** [comment] 2017-02-05 14:27
pasting following code in new html file and saving

`<body>
    <script>
    function demo() {
        
    }
    </script>
</body>`

produces garbled text

**Comment by aeschli** [comment] 2017-02-06 11:35
duplicate of #19813

**Closed by aeschli** 2017-02-06 11:35 UTC
