### ISSUE TITLE
The bug with “BS” code when edit markdown

### ISSUE THREAD

**Issue by liuzhaowei55** [Microsoft/vscode#41068] opened 2018-01-03 02:42 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.22
phpcs|ika|0.7.0
php-cs-fixer|jun|0.1.54
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.70
dotenv|mik|1.0.0
debugger-for-chrome|msj|4.0.0
php-docblocker|nei|1.3.3
vetur|oct|0.11.5
laravel-helpers|raf|0.2.2
laravel-5-snippets|sac|2.0.1

---

Steps to Reproduce:

1. 编辑 markdown 文件时，有小概率在按退格键的时候在正文中产生 “BS” 退格符号。挺严重的一个问题，希望重视。

Reproduces without extensions: Yes/No

**Comment by liuzhaowei55** [comment] 2018-01-03 02:45
Just like this issue ,this copied from vscode bug report window, the "?" I think it's "BS" code,I used "backup" in there.

**Comment by mjbvz** [comment] 2018-01-03 16:41
Duplicate of #37114

**Closed by mjbvz** 2018-01-03 16:41 UTC
Labels: markdown
