### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 1, !entry: false

### ISSUE THREAD

**Issue by jimmcq** [microsoft/vscode#182709] opened 2023-05-17 04:29 UTC
We have written the needed data int
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230509

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 1, !entry: false
    at getDocumentRegistryEntry (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:133014:11)
    at Object.releaseDocumentWithKey (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:133111:19)
    at getOrCreateSourceFileByPath (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:141789:30)
    at Object.getOrCreateSourceFile (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:141773:14)
    at /home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:141705:42
    at Object.getSourceFileWithCache [as getSourceFile] (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:117879:24)
    at findSourceFileWorker (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:120247:23)
    at findSourceFile (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:120167:20)
    at /home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:120116:22
    at getSourceFileFromReferenceWorker (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:120100:69)
    at processSourceFile (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:120114:5)
    at processRootFile (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:119911:5)
    at /home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:118690:41
    at forEach (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:118690:5)
    at synchronizeHostData (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:141729:15)
    at Object.getProgram (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:141801:5)
    at InferredProject2.updateGraphWorker (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:174359:41)
    at InferredProject2.updateGraph (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:174211:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:176601:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:178219:12)
    at /home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:178449:64
    at flatMap (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:178449:24)
    at updateOpen (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:179629:29)
    at /home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:182193:14)
    at IpcIOSession.executeCommand (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:182201:29)
    at IpcIOSession.onMessage (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:182243:51)
    at process.<anonymous> (/home/jim/.vscode-server-insiders/bin/9233de805c8fb05fad4d9d1c15f22fbca85430ad/extensions/node_modules/typescript/lib/tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:939:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (9233de805c8fb05fad4d9d1c15f22fbca85430ad, 2023-05-16T10:44:42.423Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.56GB free)|
|Process Argv|--crash-reporter-id 87d185a2-7477-4022-bd37-a57a09b89fc1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 x 3599)|
|Memory (System)|7.68GB (5.51GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-styled-jsx|bla|2.1.1
es7-react-js-snippets|dsz|4.4.3
auto-close-tag|for|0.5.14
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.1.1
remote-containers|ms-|0.292.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.78.5
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.0
remote-server|ms-|1.1.0
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.12.0
copilot-chat|Git|0.1.2023051601
copilot-nightly|Git|1.86.92
vscode-print|pdc|0.11.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
03d35959:30680466
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

o your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2023-05-17 22:03
Duplicate of #182526

**Closed by mjbvz** 2023-05-17 22:03 UTC
