### ISSUE TITLE
Suggest: Change "Sign in to Microsoft" to "Sign in"

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#94075] opened 2020-03-31 22:28 UTC
Testing https://github.com/microsoft/vscode/issues/93811

The `Sign in to Microsoft` menu option is worded strangely to me.  It reads that I am signing into Microsoft _the company_ or something like that.  And, I think we'll let you sign in to other things as well in the future.

So, my suggestion is to change `Sign in to Microsoft` to simply `Sign In`

**Comment by RMacfarlane** [comment] 2020-04-20 21:30
Duplicate of https://github.com/microsoft/vscode/issues/94766, sort of. With that item we have changed the "Sign in to Microsoft" entry to "Turn on Preferences Sync"

**Closed by RMacfarlane** 2020-04-20 21:30 UTC
