### ISSUE TITLE
Window opens very small, does not remember previous size

### ISSUE THREAD

**Issue by markkuleinio** [microsoft/vscode#149225] opened 2022-05-11 06:26 UTC
Issue Type: <b>Bug</b>

1. Open VSCode
2. Enlarge the window to be usable
3. Close VSCode
4. Open VSCode
5. See that the window is small again

If important, this is an external monitor with 100% scaling (laptop screen is 175% scaling).

This problem started (or became significantly worse) within last two months.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.0-18-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.60GB free)|
|Process Argv|--crash-reporter-id 757686f6-e93e-4b0b-b9fe-7dd65d31fe40|
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|SSH: tools|
|OS|Linux x64 4.19.0-18-amd64|
|CPUs|Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz (4 x 2294)|
|Memory (System)|7.79GB (0.57GB free)|
|VM|100%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
jinjahtml|sam|0.17.0
mib|Ver|0.0.4
xml|Dot|2.5.1
gitlens|eam|12.0.6
python|ms-|2022.6.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.20
vscode-jumpy|wma|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-05-11 07:27
/duplicate of #146499 but the opposite case (primary display is using a larger scaling factor than the display on which VS Code reopens).

**Closed** 2022-05-11 07:28 UTC
Labels: *duplicate, triage-needed, new release
