### ISSUE TITLE
Multiple messages with different action buttons look bad

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4521] opened 2016-03-21 18:49 UTC
E.g. install an extension and open readme and then return:

![image](https://cloud.githubusercontent.com/assets/900690/13930168/0a8e7b58-ef9e-11e5-94ed-5ea5f86f9b74.png)

**Comment by bpasero** [comment] 2016-03-24 13:56
Actually not a regression. I think it is really time to review this with UX, the message list has never had any UX input and is literally unchanged for many years now.

![image](https://cloud.githubusercontent.com/assets/900690/14018943/93f9c92c-f1d0-11e5-9db6-b90654db92bd.png)

Would love to get some ideas on it @stevencl @bgashler1

**Comment by bgashler1** [comment] 2016-04-05 17:26
@bpasero:
@stevencl and I have also seen several other issues come in involving the many varying ways we deliver notifications in the product (such as extension updates, extension tips/tricks, lightbulb for picking a project context, errors and warnings...).

Because of this, we should think about improving all notification experiences.  We can start by seeing what we're currently using and how we optimize and simplify how we deliver these.  I can start the work on this, and hopefully we can also discuss this in Edinburgh if there is time.

**Comment by bpasero** [comment] 2016-04-05 17:51
:+1:

**Comment by bgashler1** [comment] 2016-10-13 17:21
Related #1135

**Comment by isidorn** [comment] 2017-11-20 14:05
Let's close this as duplicate of #1135

**Closed by isidorn** 2017-11-20 14:05 UTC
Labels: ux, workbench-notifications
