### ISSUE TITLE
viewer.smoothScrolling = false

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#51305] opened 2018-06-07 07:38 UTC
Issue Type: <b>Feature Request</b>

Currently we have setting "editor.smoothScrolling".
Can you add same option for viewer? For example for viewer of "Release Notes"?

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:02.816Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by mjbvz** [comment] 2018-06-07 16:02
Duplicate of #39745

**Closed by mjbvz** 2018-06-07 16:02 UTC
Labels: new release
