### ISSUE TITLE
Extensions are disabled on 1.9

### ISSUE THREAD

**Issue by imsky** [Microsoft/vscode#20055] opened 2017-02-06 15:38 UTC
- VSCode Version: 1.9
- OS Version: Mac OS X 10.11.2

Steps to Reproduce:

1. Download VS Code 1.8.1
2. Install an extension (e.g. Git Blame)
3. Restart when it auto-updates

All extensions are disabled. Not sure why this is - on another machine, 1.9 works fine with extensions.

![screen shot 2017-02-06 at 10 38 22 am](https://cloud.githubusercontent.com/assets/330895/22653745/6814e408-ec58-11e6-9146-42c6753d3747.png)

**Comment by sandy081** [comment] 2017-02-06 17:09
Duplicate of #19753

**Closed by sandy081** 2017-02-06 17:09 UTC
