### ISSUE TITLE
The signature in suggestion widget should have syntax highlighting

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#60651] opened 2018-10-11 15:58 UTC
- VSCode Version: 1.28.0
- OS Version: win 7 

Steps to Reproduce:

1. invoke symbol signature popup via mouseover, and contrast with the one invoked via `ctrl+space` (or through suggestion).

When invoked or displayed as part of suggestion, the symbol signature doesn't have CSS applied, nor is properly indented:

![image](https://user-images.githubusercontent.com/5153846/46817245-0c8e6780-cd7f-11e8-95ee-6a73d3a18425.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment] 2019-10-17 17:06
Duplicate of #60651.

**Closed by octref** 2019-10-17 17:06 UTC
Labels: feature-request, suggest, ux
