### ISSUE TITLE
Support octicons in quick pick

### ISSUE THREAD

**Issue by nocksock** [Microsoft/vscode#34903] opened 2017-09-24 12:48 UTC
I added Octoicons to my QuickPick list of [my extension](https://github.com/nocksock/vscode-quick-open-create) and it's looking nice. However there's a bug, when filtering for a string that's in the name of the octoicon:

![screen shot 2017-09-24 at 14 42 07](https://user-images.githubusercontent.com/22164/30782660-a5ae0388-a136-11e7-8c0a-09cff1d44577.png)
![screen shot 2017-09-24 at 14 42 17](https://user-images.githubusercontent.com/22164/30782661-a5ae9ac8-a136-11e7-8a08-157c1dc03442.png)

It'd be great if the interface for QuickPickItem would be something like this:
``` typescript
interface QuickPickItem {
    label: string, // unchanged
    description?: string, // unchanged
    details?: string, // unchanged
    payload?: any, // non-readable payload
    icon?: string // either name of icon (or inline svg code?)
}
```

**Comment by wibjorn** [comment] 2018-02-06 21:31
Would like to second this. Running into the same problems.

**Comment by bpasero** [comment] 2018-02-07 10:31
Duplicate of https://github.com/Microsoft/vscode/issues/21243

**Closed by bpasero** 2018-02-07 10:31 UTC
Labels: api, feature-request, quick-pick
