### ISSUE TITLE
Allow to directly open different terminals without changing default.

### ISSUE THREAD

**Issue by ievgennaida** [microsoft/vscode#113909] opened 2021-01-06 13:51 UTC
Issue Type: <b>Feature Request</b>

I am using both PowerShell and Bash and WSL and I am forced to switch between the terminals all the times. 

It's takes me few clicks drop-down-> "Select default shell" and then '+' to add another button, menu item, dropdown to open to open exact specific terminal. 

I would apperiate submenu under the 'start default shell' with entries:
'New Terminal' -> WSL, BASH, CMD, Poweshell, etc

Thanks!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ManuelMinkAtBOSCH** [comment] 2021-03-05 14:27
@meganrogge Please make this feature available 🙏🏻 It´s just a small thing, but extremely helpful for everydays work...

**Comment by meganrogge** [comment] 2021-03-05 22:26
Duplicate of #45444

On the plan for 2021, coming soon

**Closed** 2021-03-05 22:28 UTC
Labels: *duplicate, feature-request, integrated-terminal
