### ISSUE TITLE
Problems view doesn't show issues  (Looks Critical)

### ISSUE THREAD

**Issue by eypsum** [Microsoft/vscode#63675] opened 2018-11-23 03:16 UTC
- VSCode Version:
Version: 1.30.0-insider
Commit: 0d3a14402d88f0f555ab3250c3ffd4c45a251665
Date: 2018-11-22T06:14:14.378Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-30-generic

I am using some extensions like VSCode C/C++  Tools and QT/QML  for my C/C++ project.

- OS Version: Ubuntu Gnome 16.04.5

Steps to Reproduce:
1. I updated vscode-insiders today (Korea time 23th Nov AM 10H) and open my workspace.
2. the problems view at bottom pannel detect 56 issues but doesn't show any issue elements on list of it.
Anyway I can go to the issue using by F8.
the screenshot is bellow.
https://drive.google.com/open?id=1V3QNiP6IJZVWHFnxgVSO64kNd2x3sQI- 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by xiaoyongdong** [comment] 2018-11-23 06:54
I have the same problem.

**Comment by sandy081** [comment] 2018-11-23 10:03
Duplicate of #63623

**Closed by sandy081** 2018-11-23 10:03 UTC
Labels: extensions
