### ISSUE TITLE
markdown outline stuck on loading document symbols for xxx.md

### ISSUE THREAD

**Issue by masikkk** [microsoft/vscode#196196] opened 2023-10-22 08:16 UTC
Type: <b>Bug</b>

I use vscode to edit a lot of markdown files, and many of them is very big. after update 2023 september，i found many markdown files can not open outline panel, it just stuck on loading document symbols for xxx.md. it's very important to have outline to go through a big markdown text files.
I suspect that: 
1. The hierarchical structure of my Markdown file may not be standardized, such as having a fourth-level heading directly below a second-level heading. 2. There is an unreachable intranet link in the Markdown file? Uncertain

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 21.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 11, 10|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 85b09c04-8ca1-4e20-bd4a-ad480131f021|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctokenver:30821569
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30865275
pythoncet00cf:30866519
h48ei257:30867296
pythontbext0:30864172

```

</details>

**Comment by masikkk** [comment] 2023-10-23 01:44
Supplement, there are several processes with high CPU usage in the system，all is markdown-language-features process
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=82274

**Comment by mjbvz** [comment] 2023-10-30 18:36
Can you please share the markdown file which causes this issue

**Comment by AA8j** [comment] 2023-10-31 14:31
same bug here, how to solve?

**Comment by wangzheng422** [comment] 2023-11-01 13:29
> Can you please share the markdown file which causes this issue

I find out the issue is caused by no-US language document.

if you open document contains ASCII only, then it is ok. for example this md: https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/blob/master/README.md

if you open document contains Chinese words, it will stuck, any outline will not display, for example this md: https://github.com/wangzheng422/docker_env/blob/dev/redhat/notes/2023/satellite.demo.md

**Comment by mjbvz** [comment] 2023-11-01 17:58
Thank you @wangzheng422! 

I believe this is a duplicate of #195487. The next VS Code 1.85 insiders build should have a fix (I also quickly tested using the document you shared and everything looks good). Please let me know if you still see this issue in VS Code 1.85+

**Closed by mjbvz** 2023-11-01 17:58 UTC
Labels: info-needed, markdown

**Comment by AA8j** [comment] 2023-11-07 09:14
My Chinese document also had the same bug, but when I switched the vscode language to Chinese and restarted, the bug disappeared.
