### ISSUE TITLE
Changing keyboard layout while keybindings.json is open doesn't update helper info

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#23514] opened 2017-03-29 03:07 UTC
Testing #23315

Windows 10, switched from Arabic (Lebanon) -> English (US) while keybindings.json is open

![image](https://cloud.githubusercontent.com/assets/762848/24436701/ee27c4fa-13f1-11e7-9c40-b0e1f1866ba3.png)

**Comment by alexandrudima** [comment] 2017-03-29 06:55
Duplicate of #23371

**Closed by alexandrudima** 2017-03-29 06:55 UTC
Labels: keybindings, keyboard-layout
