### ISSUE TITLE
Launch VSCODE Application in WSL without XServer

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/vscode#31073] opened 2017-07-19 20:51 UTC
I have installed windows 10 (b.1703) creators update recently and I am using ubuntu subsystem(WSL).There I have installed Visual Studio Code successfully(Node.js everything installed).

I followed this link too - [support](https://code.visualstudio.com/docs/setup/linux)

Problem is that any GUI elements required application can be launch but not working(no GUI will be elements displayed reason may be WSL has no direct Graphic driver support).

![VSCOE Launch](https://user-images.githubusercontent.com/3683121/28388703-38ee16e4-6cf1-11e7-95ae-15afa1362140.PNG)

As image shown above.after I command to execute vscode thorough 

> macxfadz@BC-LPTP:~$ code

 the WSL BASH take few seconds and nothing display during that time and print second line with empty respond.

I wanted to know How to provide graphic driver support to WSL in order to facilitate GUI applications(in this case VSCODE)? without installing 3rd party software such as XMing-Xserver,putty etc.

Else do we have any other mechanism to achieve it ? only modifying Ubuntu(Linux subsystem) side? other than switching to Windows 10 Insider preview builds?

**Please note that** I don't want to launch VSCODE installed in windows 10 launch via WSL ubuntu bash.

**Comment by macxfadz** [comment] 2017-07-19 20:59
I traveresed through **`lxss/rootfs`** directory nothing has been found to related with VSCODE,how verify that VSCODE installed successfully?

**Comment by macxfadz** [comment] 2017-07-19 21:06
Verified that .
![verification using `which`](https://user-images.githubusercontent.com/3683121/28389538-2aac71a4-6cf4-11e7-8ee9-ad2c860e94b0.PNG)

**Comment by Tyriar** [comment] 2017-07-20 16:10
Duplicate of https://github.com/Microsoft/vscode/issues/13138

**Closed by Tyriar** 2017-07-20 16:10 UTC
