### ISSUE TITLE
Angular 10: Path Mapping shows error in VSCode(Normal/Insiders) when import

### ISSUE THREAD

**Issue by Xiurik** [microsoft/vscode#101696] opened 2020-07-03 17:55 UTC
So I updated a project that was in Angular 8.2 (a project template) to version 10 and followed the instructions from https://update.angular.io/ and everything was ok, but when implemented Path Mapping the pain started, I'm getting this error everywhere:

`Cannot find module '@environments/environment' or its corresponding type declarations.ts(2307)`

And this error applies to @environments and @modules, which are declared in paths, the others does not show any error cause they are not in use.

Right now the project is building correctly when use ng build, haven't tried ng build --prod, no errors appear but Visual Studio Code (v1.46.1) is showing me the imports with errors, this is that I have:

**src/tsconfig.json**

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./e2e/tsconfig.json"
    }
  ]
}
```

**src/tsconfig.app.json**

```
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./lw/app",
    "types": []
  },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.d.ts"],
  "exclude": ["src/test.ts", "src/**/*.spec.ts"]
}
```

**src/tsconfig.base.json**

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/lw",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "emitDecoratorMetadata": true,
    "noImplicitAny": false,
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "paths": {
      "@angular/*": ["./node_modules/@angular/*"],
      "@assets/*": ["assets/*"],
      "@environments/*": ["environments/*"],
      "@api/*": ["app/api/*"],
      "@components/*": ["app/components/*"],
      "@login/*": ["app/login/*"],
      "@models/*": ["app/models/*"],
      "@pages/*": ["app/pages/*"],
      "@services/*": ["app/services/*"],
      "@shared/*": ["app/shared/*"]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true,
    "strictInjectionParameters": true
  }
}
```

NOTE: Have tried with "baseUrl": "src" - "baseUrl": "./src" - "baseUrl": "./" and nothing change.

**VSCode info**
```
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**VSCode Insiders info**
```
Version: 1.47.0-insider (user setup)
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:27:06.804Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Angular CLI**

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 12.18.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
```

Also one really weird thing that happens is for example I have 2 Services (I'm having the problems in every Service) one CityService (which is in use) and ColorService (which is not in use), CityService is not showing any error and I can access the module definition (F12), but in ColorService with the same structure the problems appear and are in red.

Does this issue occur when all extensions are disabled?: **YES**

**Comment by Xiurik** [comment] 2020-07-03 17:56
An extra reference with some Images:

https://stackoverflow.com/questions/62707968/angular-10-path-mapping-shows-error-in-vscode-when-import

**Comment by Xiurik** [comment] 2020-07-03 22:02
After uninstalling and installing many times, is working now.

**Comment by JackD111** [comment] 2020-07-04 12:29
I have the same issue with insiders and latest normal build aswell as the latest angular 10 version. Do you mean it resolved after uninstalling/installing vscode multiple times?

**Comment by Xiurik** [comment] 2020-07-04 22:51
Yeah, is now back the error, haven't been fixed yet.

**Comment by andreyborisenko** [comment] 2020-07-07 09:06
Same issue with Angular 10. I think it is caused by "Solution style" `tsconfig` files.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files

**Comment by mjbvz** [comment] 2020-07-07 20:39
Duplicate of https://github.com/microsoft/TypeScript/issues/39411

Please don't open duplicate issues

**Closed by mjbvz** 2020-07-07 20:39 UTC
