### ISSUE TITLE
Side panels keep resetting themselves

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#142224] opened 2022-02-04 18:27 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0
- OS Version: Win10

I moved the outline and favorites into the new for 1.64 side panel. Then I opened the release notes, and as the opened the panels went back to their default places.  I moved them again, then opened the settings (to see if there was anything related there) and as the settings opened, the panels went back to their default places again.

I get that this is still a feature in progress, but it does limit the usefulness of the feature when it resets itself as you're using unrelated features. If the list of panels in the side were a setting, then they could be synced into git with a folder or a workspace

**Comment by Mochnant** [comment] 2022-02-04 20:54
This issue also seems to reset the collapsed/expanded part of the Outline view.

**Comment by sbatten** [comment] 2022-02-07 14:27
@af4jm can you please provide a screen recording of your experience?

**Comment by zachvalenta** [comment] 2022-02-07 23:47
> This issue also seems to reset the collapsed/expanded part of the Outline view.

Made a [ticket](https://github.com/microsoft/vscode/issues/142451) to cover this specific behavior (outline collapses) because I noticed it in the context of switching tabs, not with the side panel.

**Comment by af4jm** [comment] 2022-02-08 15:33
I tried to grab a screen recording, but the only scenario I'm still able to reproduce the panels go back to their default position is sleeping & waking up the computer... I think it also reset when I switched it off my docking station, but I can't retest that now as I'm in sprint planning all morning, so I need the docking station to stay in the work PC

**Comment by blakeNaccarato** [comment] 2022-03-13 01:05
I've been experiencing sporadic resetting of the new right-hand-side panel as well. I suspect it has something to do with one or more of the following:
- I am putting GitLens menus in the right-hand-side panel. Something about the specific implementation of GitLens menus may be contributing to an "emergency reset" triggering in the side panel.
- I am using the built-in Settings Sync to synchronize UI State across multiple machines. The panel reset issue seems to crop up when attempting to sync a configured right-side-panel to another machine. But only sporadically.
- GitLens provides a "Tags" menu whose title updates to show the number of tags in the current repo, aka "Tags (2)" or "Tags (4)". Could an updating menu tab title mess up UI State if it happens to be looking for "Tags (2)" when there's a "Tags (3)" menu? (see screenshot below)

That last one, the thing about a menu w/ varying title, did seem to induce a sporadic reset. I was remoted into another machine, going back and forth making UI changes and doing Developer: Reload window to induce another Settings Sync fetch. Another thing I notice is that menu order in a given tab is not necessarily preserved exactly across Settings Sync operations.

A workaround that allowed me to recover from the aforementioned sporadic reset is to go to the settings cog, click "Settings Sync is On", click "Settings Sync: Show Synced Data" in the command palette, hover over an older "UI State" folder icon in the "Sync Activity (Remote)" menu, then click the contextual "Restore" button (a backwards-turning arrow). This recovered a previous right-hand-side panel config, allowing me to keep customizing.

![image](https://user-images.githubusercontent.com/20692450/158039390-e5bdf8df-1201-4d77-894b-6a44edd1a53b.png)

**Comment by sandy081** [comment] 2022-03-16 07:21
@sbatten Most probably. 

@blakeNaccarato Can you please try out latest insiders and see if the problems you mentioned have been fixed?

**Comment by blakeNaccarato** [comment] 2022-03-16 16:38
The panel hasn't reset again (yet) even in non-insiders. Of course it's also hard to be sure due to it being a sporadic reset in the first place. But yes I will try to use Insiders when feasible and report back if the panel resets again.

**Comment by grantmcconnaughey** [comment] 2022-03-29 20:36
I'm running into this as well. I'm on macOS 12.3 on VS Code version 1.65.2.

I put outline and timeline in the side panel on the right. The side panel remains on the right, but outline and timeline keep moving back to the left panel under explorer. 

I do use Settings Sync, which syncs between two machines. Both have a side panel and both should retain outline and timeline in that side panel.

**Comment by bret1234** [comment] 2022-03-29 20:57
I have the exact same problem. Still a problem for me

**Comment by sbatten** [comment] 2022-03-29 23:05
For those who are still reporting the issue, are you using the stable version of VS Code? If so, can you reproduce with the latest insiders (which will be released to stable later this week)?

**Comment by blakeNaccarato** [comment] 2022-04-02 18:00
I haven't been able to spend a lot of time in VSCode Insiders, but now that these changes are in stable, I'll see if it recurs. That being said, for me this issue hasn't recurred yet since my last comment here. So whatever is triggering the reset must be sporadic or else possibly fixed. Will report back if it happens again.

**Comment by sbatten** [comment] 2022-04-04 15:35
thanks @blakeNaccarato, I'm going to close this issue for now, but happy to re-open if the issue re-appears

**Closed by sbatten** 2022-04-04 15:35 UTC
