### ISSUE TITLE
Add option for generating conventional commit messages

### ISSUE THREAD

**Issue by max06** [microsoft/vscode#204953] opened 2024-02-11 23:35 UTC
Having copilot generating my commit messages for me is great, no doubt. 

I'd wish for an option to have messages created following the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/). At work we're only using that format for automated package versioning and creation of changelogs.

**Comment by lszomoru** [comment] 2024-12-09 10:57
Closing as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/526. 
Please see the [following comment](https://github.com/microsoft/vscode-copilot-release/issues/526#issuecomment-2509017787) on how to specify custom instructions for commit message generation.

**Closed by lszomoru** 2024-12-09 10:57 UTC
