### ISSUE TITLE
Why my cursor moved while folding?

### ISSUE THREAD

**Issue by huang2002** [Microsoft/vscode#32329] opened 2017-08-11 13:49 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Select a word before `{`
![image](https://user-images.githubusercontent.com/25705146/29214139-b67c74cc-7ed8-11e7-9780-4def7035d395.png)
2. Fold `{`
![image](https://user-images.githubusercontent.com/25705146/29214204-f8a92e30-7ed8-11e7-8d61-cf6486502c13.png)
3. ???
![image](https://user-images.githubusercontent.com/25705146/29214274-429a2b8e-7ed9-11e7-8ae4-da99499b302e.png)
4. Unfold, and fold again
![image](https://user-images.githubusercontent.com/25705146/29214365-a29ad8bc-7ed9-11e7-90dd-30b9dd7a9cf3.png)
![image](https://user-images.githubusercontent.com/25705146/29214395-be9ea854-7ed9-11e7-8167-1d9f3023071b.png)

In addition, my cursor also moved when I tried to select highlights (editor.action.selectHighlights).
![image](https://user-images.githubusercontent.com/25705146/29214892-70bb5ca2-7edb-11e7-8297-3e6ad283bc17.png)
![image](https://user-images.githubusercontent.com/25705146/29215239-c93b910c-7edc-11e7-9064-ee77c6362ecd.png)
![image](https://user-images.githubusercontent.com/25705146/29214979-cb1f6c9c-7edb-11e7-8082-a820584a4a7d.png)
![image](https://user-images.githubusercontent.com/25705146/29215030-f773c892-7edb-11e7-8a13-c0c1d0da7b65.png)
![image](https://user-images.githubusercontent.com/25705146/29215084-31aa5f12-7edc-11e7-8a72-dedf8c7fd47d.png)

**Comment by aeschli** [comment] 2017-08-12 10:26
duplicate of #31446

**Closed by aeschli** 2017-08-12 10:26 UTC
Labels: editor, editor-folding, new release
