### ISSUE TITLE
Font rendering of main window application

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/vscode#66472] opened 2019-01-14 09:41 UTC
Issue Type: <b>Bug</b>

Hello,

Would it be possible to allow the choice of the rendering font of the vscode application window under linux?

Here on the image, we see that on the left the font used by default does not have a quite clear rendering.
While on the right, the font positioned on Ubuntu gives a sharper outline.
![image](https://user-images.githubusercontent.com/331816/51105112-66705480-17e8-11e9-8b23-4309012d997d.png)

I noticed this in the editor (I use Fire Code font), where it is possible to remedy this problem by positioning the font-weigth on 400.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: KDE Neon Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 2080)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (5.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
QML|bbe|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.4
xml|Dot|2.4.0
gitlens|eam|9.4.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
dotnet-test-explorer|for|0.6.0
html-slim-scss-css-class-completion|gen|1.2.1
jira-plugin|gio|0.12.0
rest-client|hum|0.21.1
discord-vscode|icr|3.2.1
vscode-colorize|kam|0.8.3
Angular-BeastCode|Mik|7.0.29
vscode-language-pack-fr|MS-|1.30.2
python|ms-|2018.12.1
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1100
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.5.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.0.0
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.4
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.10
code-spell-checker-french|str|0.1.3
quokka-vscode|Wal|1.0.176
markdown-all-in-one|yzh|1.8.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2019-01-14 16:20
Hey @Xarkam, I think this is a duplicate of https://github.com/Microsoft/vscode/issues/519. Please add any feedback to that issue. Thanks!

**Closed** 2019-01-14 16:20 UTC
Labels: *duplicate
