### ISSUE TITLE
Smoketest fails with a webview exception

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98788] opened 2020-05-29 06:19 UTC
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=76673&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=77

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

```

I can reproduce locally:

```
/Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js:209 [uncaught exception]: Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
```

**Comment by mjbvz** [comment] 2020-05-29 06:41
I think this is a css test that is failing. Where are you seeing the webview error? Also in the smoketests?

**Comment by bpasero** [comment] 2020-05-29 06:47
@mjbvz `yarn smoketest`

**Comment by mjbvz** [comment] 2020-05-29 06:53
I don't see that error locally but this could also be the notebooks tests. I don't think we have any smoke tests that use the webview api itself

**Comment by roblourens** [comment] 2020-06-02 17:48
I think the real issue is that the setting `"css.lint.emptyRules": "error"` is broken. Can repro outside of smoketest. Anyone know why that would be, @aeschli?

**Comment by roblourens** [comment] 2020-06-02 18:20
I guess that's fixed in master

**Closed by roblourens** 2020-06-02 18:20 UTC
Labels: broken-build, smoke-test

**Comment by aeschli** [comment] 2020-06-03 06:35
duplicate of https://github.com/microsoft/vscode/issues/99108
