### ISSUE TITLE
Langauge Specific file encoding setting

### ISSUE THREAD

**Issue by Sleaker** [Microsoft/vscode#19890] opened 2017-02-04 00:49 UTC
- VSCode Version: 1.9 stable release
- OS Version: Windows 10

Ability to set default file encoding on a per-language basis.

I have files for older programming languages that I need to open with Codepage 852 or 437 but I can't set the default file encoding on a per language basis.  These files are not in self-contained repositories so setting a workspace-wide setting doesn't work, and for the most part everything else is UTF. I'd like to be able to add a setting in the language configuration to open a file with specific encoding by default and override the workspace   ##default.

**Comment by rmunn** [comment] 2017-02-04 01:17
Note that this does not appear to be a duplicate of #10444, since this issue is about being able to set the encoding on a language-specific basis in config so that files *never opened before* will be opened with the specified encoding.

**Comment by Sleaker** [comment] 2017-02-06 20:11
@rmunn - that is correct. This request is for files that have not been opened before. It would be nice if this was something that a plugin could also set the defaults for in their own settings as I have a custom plugin I made for the language I'm using. It would be doubly cool if I could set the encodings different for different file extensions within a language configuration, but that might be a bit out of scope or too difficult to manage.

**Closed** 2017-09-11 09:48 UTC
Labels: config, explorer-files, feature-request

**Comment by bpasero** [comment] 2017-09-11 09:52
The following syntax is now supported in settings:

```json
{
  "[html]": {
    "files.encoding": "utf16be"
  }
}
```

**Note:** due to the nature of this setting applying on file reading, it is not possible to assign the encoding for languages who define their kind through the first line of the text content. This only works by looking at the path of the file to determine its file association.

**Comment by Sleaker** [comment] 2017-09-12 23:07
@bpasero  - you listed the syntax for the main launguage id in the main settings, does that mean it's also able to be set in the language specific settings?

**Comment by bpasero** [comment] 2017-09-13 04:22
@Sleaker yes!

```json
"configurationDefaults": {
  "[language id]": {
    "files.encoding": "any encoding"
  }
}
```
