### ISSUE TITLE
"Changing the task execution engine requires restarting VS Code. The change is ignored"

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#32002] opened 2017-08-03 23:29 UTC
Version 1.15.0-insider (1.15.0-insider)
c26f8a312b9aa792f45a7baf06e31576470236a8
Mac

I'm working in the vscode-docker repository and I keep getting this prompt when checking out different branches.

![image](https://user-images.githubusercontent.com/1487073/28948151-c7abce80-7868-11e7-844b-5b586bd9ec39.png)

I have not been able to identify what is causing it.

**Comment by kieferrm** [comment] 2017-08-04 00:46
@chrisdias anything interesting difference in your `tasks.json` between those branches?

**Comment by chrisdias** [comment] 2017-08-04 01:10
I may have had a `tasks.json` in one branch, but not in the other. 

I just tried to build a simple extension, and I ended up in a state where making any change to `launch.json` would trigger this message.  deleted the folder, recreated the extension, and now I can't reproduce :(.  will have to try again tomorrow.

**Comment by dbaeumer** [comment] 2017-08-04 07:51
The actual change is ignored. If you reload the workbench the change will be expected. I can tweak the message however this is IMO not critical for July.

**Comment by chrisdias** [comment] 2017-08-07 04:23
I keep running into this in "daily" development of the `vscode-docker` extension, whenever I edit `launch.json`.  

What I don't quite understand is as a user, what do I do with this message?  I don't restart VS Code but everything seems to work OK. 

Do we _really_ need it?  

//cc: @kieferrm for end game consideration.

**Comment by dbaeumer** [comment] 2017-08-07 08:27
I can't reproduce this when editing the launch.json file. @chrisdias do you have steps so I can try to see why you are seeing this when editing the launch.json file.

The message is shown when the user switches the task execution engine from the old output runner to the new terminal runner. This happens when the user does one of these things:

- change the version of the tasks.json from 0.1.0 to 2.0.0 or vice versa
- add a runner property to the file and set it to terminal for version 0.1.0
- have a 0.1.0 file and deletes it.

The right fix for this is to add a Reload button to the message so that the user can reload the Window. However I think the above three situations are not so common that they require this to be fixed in the end game.

**Closed** 2017-08-24 20:10 UTC
