### ISSUE TITLE
Block labels breaks syntax highlight in javascript

### ISSUE THREAD

**Issue by SDemonUA** [Microsoft/vscode#51344] opened 2018-06-07 11:18 UTC
- VSCode Version: 1.24.0
- OS Version: Windows 10 (1803)

Steps to Reproduce:

1. Create new js file
2. Create object literal with methods
3. Inside any method use lable for code block
4. Add any method after this one

If use labels w/o blocks like `LABEL:for(...){...}` everything works fine

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/983045/41096494-6c3c6b62-6a5d-11e8-92f5-bdccb18cbea0.png)

**Comment by mjbvz** [comment] 2018-06-07 15:04
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/625

**Closed by mjbvz** 2018-06-07 15:04 UTC
Labels: new release
