### ISSUE TITLE
Terminal API message doesn't work in custom pty terminals

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#122343] opened 2021-04-27 13:40 UTC
Testing #122215

I used the sample. But this did not work for me. Here is what I tried:

![image](https://user-images.githubusercontent.com/5047891/116250536-18d84580-a76e-11eb-9f28-24815aebef0b.png)

I could not find `initialText` in the API, so I tried with `message`. Maybe someone else can try, I could not get this to work:

![image](https://user-images.githubusercontent.com/5047891/116251183-baf82d80-a76e-11eb-970d-65da07529822.png)

**Comment by Tyriar** [comment] 2021-04-27 13:48
@alexdima yes it's `message` not `initialText` sorry about that, the issue is probably because you're using `pty` which I don't think would work but I suppose there's no hard supporting it there as well.

**Comment by Tyriar** [comment] 2021-04-27 13:48
Fixed up the test item to clear the confusion

**Comment by Tyriar** [comment] 2021-04-28 14:42
Actually will hold off on this until I bring it up in the api sync.

**Comment by Tyriar** [comment] 2021-05-04 13:46
Closing this as designed since it's each to do this with a Pseudoterminal object as it can write whatever it wants already.

**Closed by Tyriar** 2021-05-04 13:46 UTC
Labels: api, api-proposal, bug, integrated-terminal
