### ISSUE TITLE
Overlappting text on explorer side bar

### ISSUE THREAD

**Issue by ashokkoduru** [microsoft/vscode#93774] opened 2020-03-30 17:10 UTC
Issue Type: <b>Bug</b>

Overlapping text after a recent update. Please fix

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.14.4
mssql|ms-|1.9.0
Go|ms-|0.13.1
debugger-for-chrome|msj|4.12.6
java|red|0.58.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.2

</details>

![image](https://user-images.githubusercontent.com/4610569/77941178-9c271f00-726e-11ea-9ddc-390648934147.png)

**Comment by isidorn** [comment] 2020-03-31 07:27
Duplicate of https://github.com/microsoft/vscode/issues/93344

**Comment by joaomoreno** [comment] 2020-03-31 11:01
This does not look like a duplicate. The body is shown even when the view is collapsed.

**Comment by isidorn** [comment] 2020-04-01 13:09
Cannot reproduce this with latest out of source and with fix for https://github.com/microsoft/vscode/issues/93344

@ashokkoduru Please let us know if you can still repro with vscode insiders from tomorrow and we can reopen

**Closed by isidorn** 2020-04-01 13:09 UTC
Labels: *duplicate
