### ISSUE TITLE
Custom Editors API: Better support for new files

### ISSUE THREAD

**Issue by KevinWuWon** [microsoft/vscode#82783] opened 2019-10-17 15:58 UTC
0. Have an extension installed that handles `.ipynb` files with the Custom Editors API
1. Open a new tab (File: New File)
2. Save As... and call it `foo.ipynb`

Expect that it opens with the custom editor (similar to how if you saved it with a `.py` extension, VS Code automatically switches the language mode to Python).

Observe that it does not, and it continues to be shown in the default text editor.

**Comment by mjbvz** [comment] 2019-10-17 17:40
Duplicate of #81832

**Comment by mjbvz** [comment] 2019-10-17 17:40
Note that extensions can create untitled files with a specific name + file extension and custom editors should work for those

**Closed by mjbvz** 2019-10-17 17:40 UTC
