### ISSUE TITLE
TreeDataProvider: custom views default to 4 lines tall

### ISSUE THREAD

**Issue by patrys** [microsoft/vscode#34136] opened 2017-09-11 10:26 UTC
When you collapse an explorer view and restart/reload vscode expanding the view again will make it so short that it's usually not usable without manually expanding.

Maybe it would be useful to proportionally reduce the size of other expanded views and give the new view _1/n_ of the column height where _n_ is the number of expanded views? Then collapsing the view would redistribute its height between other views.

**Comment by patrys** [comment] 2017-09-12 13:13
The more I think about it the more I think the explorer view would become more useful if it behaved like an accordion where expanding one section would collapse the others.

When use the file list I want to give it as much vertical space as possible.

When I'm reviewing git lens data (which seems like a good candidate for user-contributed views in the SCM tab) I don't care about the file list.

When I'm using my own code outline I again want to give it as much vertical space as possible.

**Comment by eamodio** [comment] 2017-09-12 14:28
@patrys I would LOVE to put the GitLens view on the SCM tab! ;)

Personally, I would only like this **if** there was a way to "pin" a view -- that way only pinned views would stay around and others you didn't care about would collapse.

**Comment by sandy081** [comment] 2017-09-13 14:35
There is a way to hide the views if you don't care about. Right click on the viewlet header and select the views to be shown and hide the rest. 

@patrys I liked the idea of always having one view to be expanded. I will think about.

**Comment by jerryturcios08** [comment] 2018-07-09 19:22
>The more I think about it the more I think the explorer view would become more useful if it behaved like an accordion where expanding one section would collapse the others.

I agree. It would make it easier to work with the explorer view whenever you want one view expanded at a time. I would love for this feature to be implemented.

**Comment by alexr00** [comment] 2019-10-07 14:25
Duplicate of https://github.com/microsoft/vscode/issues/31532 since the solution to one would likely solve the other.

**Closed by alexr00** 2019-10-07 14:25 UTC
Labels: explorer-custom, feature-request
