### ISSUE TITLE
a ?? 4 is formated to a ? ? 4 when save

### ISSUE THREAD

**Issue by Jackiy** [microsoft/vscode#113269] opened 2020-12-22 06:29 UTC
Issue Type: <b>Bug</b>

a ?? 4 is formated to a ? ? 4 when I save the file. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.38.0
vscode-great-icons|emm|2.1.62
beautify|Hoo|1.5.0
nbpreviewer|jit|1.2.2
Angular2|joh|11.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|10.0.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.11
vscode-yaml|red|0.13.0
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|11.0.0
bootstrap-3-snippets|wcw|0.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt859:30239450
vsjup459:30237187

```

</details>

**Comment by yume-chan** [comment] 2020-12-22 08:02
Duplicate of HookyQR/VSCodeBeautify#368

**Closed** 2020-12-23 07:49 UTC
Labels: *caused-by-extension
