### ISSUE TITLE
Unable to debug node.js app

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#31467] opened 2017-07-26 16:54 UTC
- VSCode Version: Version 1.15.0-insider (1.15.0-insider)
- OS Version: Mac OS Sierra

Steps to Reproduce:

Out of the sudden an existing node js project does no longer debug. On start debugging I'm getting a request to choose the environment from a list. Choosing node.js gives an error:

```
Attribute 'program' is not absolute ('${workspaceRoot}/index.js'); consider adding '${workspaceRoot}/' as a prefix to make it absolute.

```

Launch.json was fine for the versions before and is like this:

```
{
	// Use IntelliSense to learn about possible Node.js debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		
		{
			"type": "node",
			"request": "launch",
			"name": "Programm starten",
			"program": "${workspaceRoot}/index.js",
			"cwd": "${workspaceRoot}"
		},
		{
			"type": "node",
			"request": "attach",
			"name": "An den Prozess anfügen",
			"port": 5858
		}
	]
}


```

Trying to add a new debug config to no avail. 

Same does work with ordinary VSCode.

**Comment by weinand** [comment] 2017-07-26 18:07
that's a bug in the Insiders.
Duplicate of #31435

**Closed by weinand** 2017-07-26 18:07 UTC
Labels: debug, insiders
