### ISSUE TITLE
Link underlines blink

### ISSUE THREAD

**Issue by allanchau** [microsoft/vscode#76642] opened 2019-07-04 23:51 UTC
Issue Type: <b>Bug</b>

Links in markdown documents are blinking.

![Screen-Recording-2019-07-05-at-9 15 46-am](https://user-images.githubusercontent.com/1763968/60690376-2ae85480-9f06-11e9-8783-6e4fc51496cb.gif)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|14%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
coldfusion|ili|1.0.1
docthis|joe|0.7.1
atom-keybindings|ms-|3.0.6
color-highlight|nau|2.3.0
code-spell-checker|str|1.7.17
vscode-status-bar-format-toggle|tom|1.5.0
sort-lines|Tyr|1.8.0
vscode-wakatime|Wak|2.1.2
quokka-vscode|Wal|1.0.233
highlight-bad-chars|wen|0.0.3
vscode-caddyfile-syntax|zam|1.0.1

</details>

**Comment by mjbvz** [comment] 2019-07-08 15:47
Does this still happen if you disable all extensions?

**Comment by allanchau** [comment] 2019-07-08 23:54
@mjbvz It's not happening with or without extensions today 🤷‍♂.

**Comment by alexwall** [comment] 2019-07-09 10:07
@mjbvz 
It's quite difficult to reproduce this issue:
The properbility is higher if:

1. I you edit other text, so not the link it self 
2. If the file has some other content apart from the link
3. If the window is narrow, that the link is wrapped to the next line
4. Sometimes the last part of the link starts toggling (underline appears and disappears) when I click randomly inside the text document 

See example:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/316469/60878381-e8918100-a23f-11e9-8023-328ac2b8ad74.png">

I've just one extension in common with @allanchau 

`code-spell-checker`

**Comment by alexwall** [comment] 2019-07-09 10:08
# Example file
```
# Markdown

gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.


- sea takimata sanctus est Lorem ipsum dolor sit amet.
- sea takimata sanctus est Lorem ipsum dolor sit amet.
- fjdskal; n fdsa f dsajkl ; 
- fdsa fjdla 
- fdjlsafd jskal;f jsa
- fd ajdksla; 
- djksla f  fdjksla; f ajfwj jfa  fdsaj jkfld;sajklf;dsaiw gjkflds;a fdsa
- fdsa fdsafdsa  fdsa f j
- [ ] #plan fdsa  fdjsaklf fdsa fdsa fdsa f jfdkls ajfksal;j
- [ ] #plan fdsjlfds aliweroo fsfdsa j fdsjkalow 
- sea takimata sanctus est Lorem ipsum dsfdsa
- **Edit something here and watch link decoration at the bottom**

## More text

- [ ] @todo 1 
- [ ] #next todo 2 fdjskal fj dksla;fj dklsajfja
- [ ] todo 3 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.     


- [ ] augue duis dolore te feugait nulla facilisi. https://www.longlonglong.com/long/long/path/multi/line/sporadic/issue 

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. 

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. 

```

**Comment by jaoord** [comment] 2019-07-12 08:04
I noticed the same in a JS file (react component):

![blinking underline](https://user-images.githubusercontent.com/6464609/61112525-5af6a100-a48c-11e9-9b1b-af441a1c84f2.gif)

**Comment by alexwall** [comment] 2019-07-21 13:42
```markdown
# Minikube on Archlinux

## System is up to date

 example text 
 example text


http://blog.programmableproduction.com/2018/03/08/Archlinux-Setup-Minikube-using-KVM 
```

![screencast 2019-07-21 15-27-17](https://user-images.githubusercontent.com/316469/61592005-99e3cf80-abcd-11e9-90a6-eef20c9bfd83.gif)

<img width="504" alt="image" src="https://user-images.githubusercontent.com/316469/61592018-baac2500-abcd-11e9-99b4-8a4b82731533.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/316469/61592026-d0b9e580-abcd-11e9-9409-9c25ee5f9c78.png">

VSCode Version:
Version 1.36.1 (1.36.1)

**Comment by rebornix** [comment] 2019-07-26 19:58
A potential duplicate of https://github.com/microsoft/vscode/issues/48321

**Comment by andibakti** [comment] 2019-07-30 06:34
I have the same issue in Java with vanilla vscode with no extensions

**Comment by iansan5653** [comment] 2019-08-13 18:27
Experienced this with markdown the other day. Can't reproduce though.

**Comment by Keavon** [comment] 2019-08-15 20:15
It seems to start happening when I visit another tab and then come back, with my text cursor on a nearby line to the link the starts blinking. It's happening in my HTML document.

**Comment by mlewand** [comment] 2019-09-02 06:36
Sometimes I'm getting similar artifacts on Windows, so I guess it might be platform independent.

**Comment by veleek** [comment] 2019-09-14 23:08
Just adding another repro to the list.  I experienced it editing SASS files.

![UnexpectedUnderlineBlinking](https://user-images.githubusercontent.com/1055021/64914567-aa19b600-d709-11e9-9746-f877570295ba.gif)

Just updated literally moments ago and was able to reproduce afterwards:

> Version: 1.38.1 (system setup)
> Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> Date: 2019-09-11T13:35:15.005Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

**Comment by elieux** [comment] 2019-09-19 14:30
Seems easily reproducible in my brand new setup (no custom configuration).

![vscode-blinking](https://user-images.githubusercontent.com/1399406/65253306-b089a280-dafa-11e9-86e7-54d74fffa53a.gif)

> Version: 1.38.1
> Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> Date: 2019-09-11T13:35:15.005Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17763

**Comment by jhadida** [comment] 2019-09-19 15:57
I am also experiencing this bug, and I can reproduce @elieux's post. 

Here is the step-by-step recipe:

 - Open a new window, and reload with extensions disabled.
 - Open a new tab.
 - Copy the text below (including the empty lines before/after).
 - Paste it within the open tab, and **quickly** press the up-arrow key twice in order to place the cursor on the first line. By quickly, I mean that you should start pressing your arrow key _before_ the link becomes underlined at all.
 - This should make the link blink.

```

https://github.com/microsoft/vscode/issues/76642

```

**Comment by alexandrudima** [comment] 2019-10-08 13:11
Also notice the layer borders, this is most definitely a bug in Chromium's rendering pipeline:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66398338-e1fcdc00-e9dd-11e9-96cb-4af2adb42ff9.gif)

**Comment by alexandrudima** [comment] 2019-10-08 13:34
I could eventually reproduce some funny business in Chromium Version 69.0.3497.0

![image](https://user-images.githubusercontent.com/5047891/66400060-0f975480-e9e1-11e9-804b-66df5254eb9e.png)

**Comment by alexandrudima** [comment] 2019-10-08 14:06
I could reproduce wierdness around `text-decoration: underline` in Chrome Canary and I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1012248

**Comment by roblourens** [comment] 2020-01-29 19:19
I think this got worse in Electron 7, and I filed https://github.com/microsoft/vscode/issues/89042, and it seems better now that we are back in 6. Something to watch out for when we upgrade again.

**Comment by ultraGentle** [comment] 2020-10-01 14:59
Since some time has passed, just wanted to add a note that I'm currently experiencing this bug.    

(Details: VSC: 1.50.0, insiders.  Untitled, unsaved file.  No line numbers.  Not all links blink.)

**Comment by babramczyk** [comment] 2021-01-15 20:30
This is still happening to me today 😕

**Comment by deepak1556** [comment] 2021-01-15 22:04
Can you check with our insiders version https://code.visualstudio.com/insiders, the upstream fix has been picked up in those builds.

**Comment by alexilyaev** [comment] 2021-01-17 12:15
Haven't seen this problem for some time now (regular VS Code):
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by babramczyk** [comment] 2021-01-19 17:15
Happened today on regular VS Code (1.52.1). Tried briefly to reproduce on Insiders and couldn't, but sometimes I can't reliably reproduce it on regular VS Code either.

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

Uploading Screen Recording 2021-01-19 at 10.38.04 AM.mov…

**Closed** 2021-01-25 17:44 UTC
Labels: chromium, fixed-in-electron-11, gpu, upstream, upstream-issue-fixed
