### ISSUE TITLE
"Open Folder" command displays as "unbound" in watermark

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16769] opened 2016-12-06 23:20 UTC
Testing #16560

Doesn't appear that there's actually a keyboard shortcut? Also notice that the text is misaligned, so worth verifying that this wouldn't happen for other cases

Steps to reproduce:
1. launch vscode from terminal using `code-insiders -n`
2. close empty file that comes up to view watermark

![image](https://cloud.githubusercontent.com/assets/762848/20946712/b9feb29e-bbc0-11e6-8ce6-dc75100fbc28.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by chrmarti** [comment] 2016-12-07 15:51
Duplicate of #16672

**Closed by chrmarti** 2016-12-07 15:51 UTC
