### ISSUE TITLE
Block Selection Key Kombination

### ISSUE THREAD

**Issue by BergnerM** [Microsoft/vscode#51214] opened 2018-06-06 10:56 UTC
Issue Type: <b>Feature Request</b>

Block Selection ist with the Shift + Alt key, but in most other applications e. g. visiual studio, word the switch key for block selection is only Alt. Why it is different here? Will be better changed to standard of other MS products.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.14393

**Comment by alexandrudima** [comment] 2018-06-11 10:30
Duplicate of #5402

**Closed by alexandrudima** 2018-06-11 10:30 UTC
Labels: editor, editor-columnselect

**Comment by ADTC** [comment] 2018-06-14 06:08
> Kombination

Did you mean _combination_?
