### ISSUE TITLE
Sometimes extension host zombie stays around

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#7168] opened 2016-06-03 07:04 UTC
I often happens to me that I have a zombie extension host somewhere. Unsure how that happens but I think it should self terminate when its parent PID isn't there anymore.

<img width="805" alt="screen shot 2016-06-03 at 09 00 42" src="https://cloud.githubusercontent.com/assets/1794099/15771261/bba2d010-2969-11e6-8bc0-b964e2f4cdc0.png">

<img width="695" alt="screen shot 2016-06-03 at 09 03 39" src="https://cloud.githubusercontent.com/assets/1794099/15771306/17bd1978-296a-11e6-9055-003269c0b245.png">

**Comment by joaomoreno** [comment] 2016-06-03 07:46
You should figure out what's the full argument list of that process, to really figure out which process it is. Use `htop` for that.

**Comment by jrieken** [comment] 2016-06-03 08:19
Cos the extension host binds on port `5870` and cos subsequent starts of the extension host cannot bind to that port (see message about using `5871`) I have high confidence that this is the extension host being orphan.

**Comment by bpasero** [comment] 2016-06-06 08:37
I also sometimes see it, though would expect the killing strategy to take place. I believe this can happen when starting an invalid electron application (debugging an extension "out of dev" without specifying the path to vs code for this case).

**Comment by bpasero** [comment] 2016-06-08 07:17
@jrieken @joaomoreno @alexandrudima whenever you see this please update here with what you did before. I know I get this every once in a while but I never memorize what I did that lead me there...

**Comment by joaomoreno** [comment] 2016-06-08 08:47
I never noticed having this.

**Comment by bpasero** [comment] 2016-06-08 09:50
I still think it happens more often when developing on extensions, e.g. when you launch an extension for debugging. That might explain why you do not see it and others more often (that happen to work on extensions more often).

**Comment by jrieken** [comment] 2016-06-08 09:58
Maybe I run into this when with the integration tests, esp during dev when the don't always succeed or I kill the execution with `Ctrl+C`

**Comment by semihalf-kardach-stanislaw** [comment] 2016-06-10 10:39
I'm running into this on a daily basis with the following setup (deb from the homepage):
```
kda@toster ~ $ code --version
1.2.0
kda@toster ~ $ code --list-extensions
ms-vscode.cpptools
kda@toster ~ $ uname -a
Linux toster 4.4.0-22-lowlatency #40~14.04.1-Ubuntu SMP PREEMPT Fri May 13 22:47:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
kda@toster ~ $ lsb
lsblk        lsb_release  
kda@toster ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa
kda@toster ~ $ apt-cache policy code
N: Unable to locate package code
kda@toster ~ $ apt-cache policy visual-studio-code 
visual-studio-code:
  Installed: 1.2.0-1465219835
  Candidate: 1.2.0-1465219835
  Version table:
 *** 1.2.0-1465219835 0
        100 /var/lib/dpkg/status
```

A simple scenario to reproduce:
```
kda@toster ~ $ code
# Now close the window
kda@toster ~ $ ps -ax | grep code
20588 ?        Ssl    0:01 /usr/share/code/code
20590 ?        S      0:00 /usr/share/code/code --type=zygote --no-sandbox
20666 ?        Sl     0:00 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=SharedProcess
20763 ?        Sl     0:00 /usr/share/code/code ./terminalProcess
```

**Comment by bpasero** [comment] 2016-06-10 10:42
@semihalf-kardach-stanislaw the process that hangs around seems to be the shared process though and not the extension host process. If you can confirm that please open a new issue on this!

**Comment by semihalf-kardach-stanislaw** [comment] 2016-06-10 11:28
@bpasero Just to be sure. How can I confirm it beyond inspecting the command line?

**Comment by bpasero** [comment] 2016-06-10 12:07
@semihalf-kardach-stanislaw yeah command line is totally enough to verify!

**Comment by bpasero** [comment] 2016-06-18 06:42
This is not the extension host process staying around, but a process spawned from the extension host that does not terminate. I just had this issue again and noticed 2 ts-server processes running even though no other VS Code was running (+ many git processes which I think @joaomoreno fixed recently).

<img width="1572" alt="screen shot 2016-06-18 at 08 38 06" src="https://cloud.githubusercontent.com/assets/900690/16169477/783b5e5a-3530-11e6-9b47-c6a8f886bdde.png">

After killing the ts-server process, things worked again in terms of debugging.

@dbaeumer does the ts-server have protection to terminate itself when its parent dies?

**Comment by dbaeumer** [comment] 2016-06-20 08:42
Yes it does. When its stdin stream closes it exits. Since we use our own pipes for stdiin / stdout to talk to an electron node process it might be that we need some explicit code in stdFork to close them. @alexandrudima is this something we need to add?

**Comment by alexandrudima** [comment] 2016-06-20 14:14
@dbaeumer the stdFork behaves the same as stdin (I hope), given all the `unref` dancing at https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stdForkStart.js#L159

So if there are no more listeners on stdin, the fake stdin stream gets unrefed by me and node will shut down gracefully. Maybe stdin behaves differently?

**Comment by alexandrudima** [comment] 2016-06-20 14:15
Is it that if the standard `stdin` closes, node implicitly unrefs it?

**Comment by dbaeumer** [comment] 2016-06-21 07:51
@alexandrudima the problem is not that the extension host (which creates the fake stdin pipe/socket) doesn't exit. It does. But somehow the fake stdin doesn't closed hence the tsserver doesn't exit. What I was trying to say is: do we need a close call on the fake stdin/out when the extension host shuts down.

**Comment by dbaeumer** [comment] 2016-06-29 12:40
@alexandrudima any additional input?

**Comment by alexandrudima** [comment] 2016-06-29 12:55
@dbaeumer 

https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stdForkStart.js#L130

I give to `process.stdin` the exact named pipe connection that node gives me. If node decides to give an error, process.stdin should get an error, etc.

If you don't want to, I can debug what node gives in there, maybe with the new node version something has changed... ?

**Comment by weinand** [comment] 2016-07-01 08:18
not reproducable

**Comment by dbaeumer** [comment] 2016-07-01 10:02
Some more findings: the tsserver can't block the extension host to exit. But if the extension host is still active then of course the tsserver will still be there because it only exists if the extension host closed the stdin pipe. In addition I don't see why the tsserver should block the debugging port of the extension host. It doesn't even know about that port.

Possible reasons why the tsserver doesn't exit are:

- the stdin stream doesn't close or node never receives an event for it
- the tsserver is busy (endless loop)
- the tsserver is in debug mode and sits on a breakpoint

If someone sees this and the tsserver is the only process hanging around could you please drag me in so that I can check why the tsserver doesn't exit itself.

**Comment by qianguozheng** [comment] 2016-10-10 15:12
I encounter this on Ubuntu 15.10, I wrote a TCP socket server , start it and receive thing from client , then stop server. But when I restart the TCP socket server it got panic, I found the process still exist and it still listen the socket. But in Mac OS it work fine.

**Comment by dbaeumer** [comment] 2016-10-11 08:07
@qianguozheng which process did still exist. Your TCP socket server. If so how do you exit / shutdown the server?

**Comment by qianguozheng** [comment] 2016-10-11 13:18
@dbaeumer  The TCP socket server did still exist, I kill the pid of the server( using netstat -luntp to find its pid)

**Comment by dbaeumer** [comment] 2016-10-12 10:03
@qianguozheng I mean how is the socket server to shutdown in the first place. Under Linux a process is not killed when its parent process exists. So the socket server must have some code to exit itseldf. Otherwise it wills stay around.

**Comment by dbaeumer** [comment] 2016-11-15 19:38
Closing the issue. Alex and I rewrote how the extension host is shutdown and I didn't see any tsserver or extension host processes hanging around. Please ping if one of you still thinks this is an issue.

**Closed by dbaeumer** 2016-11-15 19:38 UTC
Labels: bug, needs more info, typescript

**Comment by jrieken** [comment] 2016-12-07 15:07
re https://github.com/Microsoft/vscode/issues/7168#issuecomment-260743929 - I do but we are tracking that somewhere else I believe
