### ISSUE TITLE
Extension doesnt install on ext install ext name in quick open 

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#7398] opened 2016-06-08 09:27 UTC
- VSCode Version: 1.2
- OS Version: win 7

Following is the link- 
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

When i try to install extension via  VS Code Quick Open (Ctrl+P) and paste `ext install code-settings-sync` and hit enter. 
My extension doesnt come at first and selected

But when i write `ext install visualcode-settings-sync` it works.

Please correct the ext install name in the page there is some diflict

**Comment by joaomoreno** [comment] 2016-06-09 07:53
Duplicate of #7327. We will release a fix asap.

**Closed by joaomoreno** 2016-06-09 07:53 UTC
