### ISSUE TITLE
Provide a feature to permanently disable some extensions from some language/environment

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#110021] opened 2020-11-05 14:25 UTC
A lot of Microsoft's python related extensions have very annoying and disrespectful spammy prompts. 

For example, if a user has Python for VSCode and Intellicode installed, every time a python file is opened, the user will get a very annoying and spammy prompt to enable a "microsoft language server": 

![ic](https://user-images.githubusercontent.com/2473545/98252563-dc632400-1f58-11eb-9fea-83bfb54b6a24.png)

As can be seen in the prompt, there is no way to permanently disable the prompt. The button "later" pretty much means "keep annoying me". 

This prompt will happen even if the user has signaled it wants to use the open source "Jedi" language server, instead of the proprietary microsoft one. 

This is an extremely annoying behavior. 

VS Code should provide a way to blacklist and selectively disable certain extensions based on the file/language of the file being edited. 

This way, the user could have a 
```
    "[python]": {
        "disabledExtensions": [ "intellicode", "pylance"]
}
```
And the extensions would be disabled when editing python files, and no prompt will be shown.

**Comment by gjsjohnmurray** [comment] 2020-11-05 15:46
/duplicate of #41767 but you may want to contribute the language-specific aspect of your request there.

**Closed** 2020-11-05 15:47 UTC
Labels: *duplicate

**Comment by phgmacedo** [comment] 2020-11-05 16:41
@gjsjohnmurray While being able to "ignore" some notifications, this issue is quite different from #41767. This issue asks to be able to selectively '_disable_' an extension. That one asks about _muting_ an extension.

**Comment by gjsjohnmurray** [comment] 2020-11-05 17:57
Sorry for misreading. May be a duplicate of #57548

@sandy081 please review and reopen if appropriate.

**Comment by sandy081** [comment] 2020-11-08 11:37
@phgmacedo If I understand correctly your complain is about notifications noise from extensions. You can completely disable or uninstall an extension if you do not like it. If you want the extension to ignore certain files, you would have to open a feature request against that extension to support it. Because from the perspective of VS Code, it is not possible to disable an extension per file, you can do it either globally or per workspace.

**Comment by phgmacedo** [comment] 2020-11-08 12:40
> @phgmacedo If I understand correctly your complain is about notifications noise from extensions. You can completely disable or uninstall an extension if you do not like it. If you want the extension to ignore certain files, you would have to open a feature request against that extension to support it. Because from the perspective of VS Code, it is not possible to disable an extension per file, you can do it either globally or per workspace.

I know it's not possible. That's why it's a feature request.

**Comment by sandy081** [comment] 2020-11-09 06:43
Ok, but the feature (disabling extension per file) cannot be done as it does not fit into our current design. So, tagging this out of scope.
