### ISSUE TITLE
Terminal issues after last update

### ISSUE THREAD

**Issue by ryanhaugh** [Microsoft/vscode#64903] opened 2018-12-12 17:59 UTC
Issue Type: <b>Bug</b>

When I open a new terminal window it doesn't put my cursor at the prompt. Then, even when I scroll up to put my cursor at the prompt, when I start typing, the cursor moves away from the prompt so that all I see on the screen is what I'm typing floating in the middle of the window.

Also, CTRL-K used to clear the console, but that no longer works.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (17.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
mustache|daw|1.1.1
vscode-eslint|dba|1.7.0
gitlens|eam|9.1.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
Angular2|joh|7.0.1
prettify-json|moh|0.0.3
csharp|ms-|1.17.1
PowerShell|ms-|1.10.1
debugger-for-chrome|msj|4.11.1
polacode|pnp|0.2.2
LiveServer|rit|5.3.1
vscode-icons|rob|7.28.0
trailing-spaces|sha|0.2.11

</details>

**Comment by usernamehw** [comment] 2018-12-12 18:36
duplicate of #57803 ?

**Closed** 2018-12-12 19:12 UTC
Labels: integrated-terminal
