### ISSUE TITLE
In column mode selection ignore different line length

### ISSUE THREAD

**Issue by schoetbi** [microsoft/vscode#71282] opened 2019-03-27 10:59 UTC
Issue Type: <b>Feature Request</b>

When selecting characters in column mode (Shift+Alt pressed) + select with mouse downwards. Then the selection should always be in the same column as the starting point of the mouse movement. If another line has less characters these linse should be filled up with spaces up to the selected column.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexandrudima** [comment] 2019-10-17 20:15
Duplicate of #5402

**Closed by alexandrudima** 2019-10-17 20:15 UTC
Labels: editor-columnselect, feature-request
