### ISSUE TITLE
VSCode creating several new 'Untitled.ipynb' files

### ISSUE THREAD

**Issue by lucasfr** [microsoft/vscode#90971] opened 2020-02-19 10:57 UTC
- VSCode Version: 1.42.1
- OS Version: macOS Catalina 10.15.3

Steps to Reproduce:

1. Connect to a Jupiter Notebook server with Python extension via 'Specify Jupyter server URI' running on docker server.
2. VS Code then creates several new 'Untitled.ipynb' files.

Is this a setting I have missed or is it a bug?

**Comment by Heavyknights** [comment] 2020-02-21 14:17
Has been discussed in #7925 and #9671. Apparently, it is by design that these files are created when you start the server yourself. They also should go away when closing VSCode, but for me that is not the case; they just keep piling up.

**Comment by rebornix** [comment] 2020-02-27 00:42
Currently we don't have builtin support for the notebook, please start filing issues with the Python extension first. Thanks !

**Closed** 2020-02-27 00:42 UTC
Labels: *caused-by-extension
