### ISSUE TITLE
Outline for C99/11 with Clang/GCC gets confused - incorrect additional entries

### ISSUE THREAD

**Issue by runelabs** [Microsoft/vscode#53670] opened 2018-07-06 08:13 UTC
- VSCode Version: 1.25.0 x64  2018-07-05T13:10:37.273Z ( 0f080e5267e829de46638128001aeb7ca2d6d50e )
- OS Version: Linux
- Microsoft C/C++ IntelliSense - Version 0.17.6: July 2, 2018
- clang version 6.0.0 , gcc  7.3.0

Steps to Reproduce:

1. The outline view shows several incorrect entries - local function variables and other calls from within function bodies.
2. It seems to be triggered by the Clang and GCC C language extension for _compound expressions_.
 I imagine there is similar incorrect behaviour for Clang blocks.
  -- https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Statement-Exprs.html
  -- https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Naming-Types.html
  -- https://en.wikipedia.org/wiki/Blocks_(C_language_extension)
  -- https://clang.llvm.org/docs/BlockLanguageSpec.html
3. See the confused outline view for the following example code
```C
#include <stdarg.h>
#include <string.h>

#define noing __attribute__((noinline))
#define fn() 
#define success() 0

typedef struct {int a; int b; char* s; int c;} Some;    // weird entry in outline

noing void foo(unsigned int len, int argc,...) {  // note: change signature -> no outline update
  fn();
  int list[argc];
  Some* p = &list[0];
  va_list argp;
  va_start(argp, argc);
  for (int k=0;k!=argc;++k) {
    *p = ({Some tmp = {1, 2, &"", 2}; tmp;}); // compound expression likely culprit
  }
  va_end(argp);                       // va_end  incorrectly shown in outline
  int k = 0;                          // k incorrectly shown in outline
  while (len != 0) {
    if (!success()) {
      register int r = len -1;
      if (k>0) memmove(&list[k],&list[k+1],r*sizeof(int)); // memmove shows in outline
      len--;
    }
    fn();                             // fn incorrectly shown in outline
  }
}

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2018-07-06 08:21
@runelabs What extension are you using for clang?

**Comment by jrieken** [comment] 2018-07-06 08:50
Ok, thanks. The issue is that the extension needs to adopt some new API. I have created https://github.com/Microsoft/vscode-cpptools/issues/2230 for them and I am closing this as duplicate

**Closed by jrieken** 2018-07-06 08:50 UTC
Labels: outline

**Comment by runelabs** [comment] 2018-07-06 09:04
Seeing as https://github.com/Microsoft/language-server-protocol/issues/327 is almost a year old issue, C99/11 outline view with Clang/GCC is broken in VSCode and seems to will stay broken? It is quite useless with outline for C language when this issue persists and the previous extension for showing outline is now defunct with VSCode 1.25.
