### ISSUE TITLE
Focus editor after command Focus next (provious) search result

### ISSUE THREAD

**Issue by rysavyjan** [Microsoft/vscode#69443] opened 2019-02-26 10:27 UTC
When walking through the search results using F4 (Shift+F4), editing each found instance, it would be great to get editor pane activated. When editor pane is already active, F4 keeps caret there - it is OK. But when a next file (or first one after search) from search results is opened, caret is lost and we need to use mouse to activate editor pane.

Would it be possible to always put caret to editor window after F4 / Shift+F4 commands? Or maybe introduce such option? It would greatly improve keyboard-only navigation during search.

**Comment by roblourens** [comment] 2019-02-26 21:37
Yes, that is a bug and should already be fixed in Insiders for our next release.

**Closed by roblourens** 2019-02-26 21:37 UTC
Labels: search

**Comment by darrinholst** [comment] 2019-04-09 12:24
@roblourens This bug seems to have made it to the latest insiders build that I'm running.

```
56f1b4795fed05677eb82a21dac4fc1ab62d747b

2019-04-09T05:06:34.424Z
```

**Comment by roblourens** [comment] 2019-04-09 16:58
I can't reproduce, please open a new issue with more details.
