### ISSUE TITLE
ERROR: Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by strugglews** [Microsoft/vscode#40804] opened 2017-12-25 07:48 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
path-autocomplete|ion|1.7.0
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1. Node.js Debugging in VS Code  
2. error:Extension host terminated unexpectedly.
tip: Nothing is wrong with my code!!!

Launch with `code --disable-extensions` to check.but problems still remain
![error](https://user-images.githubusercontent.com/28152567/34335539-88e8b2a6-e98a-11e7-95a6-af55036aaa90.png)

Reproduces without extensions: Yes 

#debug

**Comment by kormic** [comment] 2017-12-26 16:36
Same happened to me but I disabled all extensions by hand then restared vs code and it seems to be working.

**Comment by weinand** [comment] 2017-12-27 15:07
duplicate of #39818

**Closed by weinand** 2017-12-27 15:07 UTC
Labels: debug
