### ISSUE TITLE
Folded region unfolds when a line is inserted or removed inside it

### ISSUE THREAD

**Issue by ozair-dev** [microsoft/vscode#170352] opened 2023-01-01 09:42 UTC
Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

- VS Code Version: 1.74.2
- OS Version: Ubuntu 20.04.1 LTS

**Issue**
I am making an extension which opens multiple editors side by side for a single document with each editor showing only one class/function and all other code is hidden. When I insert or remove a line in one editor, the folded region in all  other editors which contain that line **unfolds**. I want to disable the unfolding of the regions when a line is inserted or removed inside them with other editor. Inserting other characters doesn't doesn't unfold the area. check the demo:

![Screencast from 01-01-2023 13_41_08](https://user-images.githubusercontent.com/65649182/210166415-d690090f-b5a4-462b-957b-83b55e0a2dfe.gif)

I am able to fix the issue with monaco-editor library by manually folding the region again when the text changes. Please add a fix in vscode for this...

Here is how I did it in monaco edito:

![Screencast from 30-12-2022 14_07_52](https://user-images.githubusercontent.com/65649182/210166421-80a39574-6bab-4e57-a86a-25c00702af17.gif)

**Comment by aeschli** [comment] 2023-01-10 17:44
Likely related to https://github.com/microsoft/vscode/issues/161647

**Comment by ozair-dev** [comment] 2023-02-06 19:11
I've commented there but there is not response yet.
You said in the other issue that you'll look into in November (2022), but there seems to be no progress on that!!!

**Comment by aeschli** [comment] 2023-02-07 13:26
duplicate of https://github.com/microsoft/vscode/issues/161647

**Closed by aeschli** 2023-02-07 13:26 UTC
Labels: editor-folding
