### ISSUE TITLE
There is a bug in emmet extension

### ISSUE THREAD

**Issue by BlackEagle1983** [microsoft/vscode#138205] opened 2021-11-30 19:42 UTC
We have written the needed data into yHello . Good time . VS Code is my favorite editor and I am using this editor for programming python and django but I have found a bug in emmet extension . when we install Django extension that written by Baptiste Darthenay and configure setting.json same as description of the extension we can not use the auto suggestion of html tags in django templates because emmet extensions does not load when we open html document  html tags do not appear in auto suggestion menu . I figured out If I add "onLanguage : django-html" statement to the activationEvent of package.json file of emmet extenstion this bug will be removed and we can use html tags in django templates and use html tags will appear in auto suggestion menu.,
please solve this problem . 
Thank you for your favor .

**Comment by rzhao271** [comment] 2021-11-30 20:18
Duplicate of #137012

It should be fixed in the next release, which comes out in under two weeks.
Alternatively, you can switch to [Insiders](https://code.visualstudio.com/insiders/).

**Closed by rzhao271** 2021-11-30 20:18 UTC
