### ISSUE TITLE
Executing code in wsl does not open vscode in windows

### ISSUE THREAD

**Issue by X-Dean** [microsoft/vscode#192567] opened 2023-09-08 12:34 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.82.0
- OS Version:  Windows 10 Enterprise 22H2
- WSL : AlmaLinux release 8.8

Steps to Reproduce:

1. Update VsCode to the version 1.82.0
2. Try to use code in wsl linux terminal

Downgrading to version 1.81.1 resolves the issue.

**Comment by aeschli** [comment] 2023-09-10 10:30
This works for me (tested with lmaLinux9, Fedora and Ubuntu 22.04).

What do you get for `which code`?

**Comment by aeschli** [comment] 2023-09-10 14:11
Found the problem. It only shows up with WSL1. Duplicate of https://github.com/microsoft/vscode/issues/192506
@X-Dean Can you confirm that you are on WSL1

**Closed by aeschli** 2023-09-10 14:11 UTC
Labels: info-needed, new release

**Comment by X-Dean** [comment] 2023-09-10 21:10
Yes, wsl version 1
