### ISSUE TITLE
When typing a 2nd single quote, the quote gets doubled

### ISSUE THREAD

**Issue by elgwiedo** [Microsoft/vscode#11222] opened 2016-08-30 14:39 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1.  Write a function that has an object as argument (function (myobject) .... ) 
2.  Now you decide to pass a string as a parameter.  Type a first single quote to define the argument that is passed as string (function (**'**myobject) ... ) 
3.  Type the second quote to close the string.  (function ('myobject**'**) ... ) 
   Now you get  (function ('myobject**''**) ... )

**Comment by dbaeumer** [comment] 2016-08-30 14:53
@alexandrudima assigning to you. If this is something JS/TS can control please assign back to me.

**Comment by rmunn** [comment] 2016-09-01 02:41
Probably related to #8539 and/or #8850.

**Comment by Srekel** [comment] 2017-03-02 07:52
In addition to the specific bug OP noted, when you delete the first one, both gets deleted. This is quite annoying :D See gif:

![codebug_quotes](https://cloud.githubusercontent.com/assets/1578924/23497914/90c25f40-ff25-11e6-854a-522732355f9b.gif)

**Comment by rebornix** [comment] 2017-07-14 18:33
It shares the same story as https://github.com/Microsoft/vscode/issues/13523 , we don't do any bracket matching check while typing as the cost is pretty high.

**Comment by rebornix** [comment] 2017-07-14 18:34
From @octref  Don't provide closing paren if there are unmatched closed parens

> - VSCode Version: 1.6

> Steps to Reproduce:

> Type <kbd>(</kbd> before `)`, end up with `())`
> Type <kbd>{</kbd> before `}`, end up with `{}}`

**Comment by rebornix** [comment] 2018-09-05 18:02
The root cause for this issue is our auto closing feature doesn't take language semantics into account. Let's track this issue in https://github.com/Microsoft/vscode/issues/6841 which is the earliest issue. Thanks for your feedback!

**Closed** 2018-09-05 18:02 UTC
Labels: *duplicate, bug, editor-autoclosing, javascript
