### ISSUE TITLE
Code Formating : HTML does not work as expected

### ISSUE THREAD

**Issue by oodboo** [Microsoft/vscode#6419] opened 2016-05-17 12:22 UTC
- VSCode Version: 1.1.1-Insider
- OS Version: Win 10

Steps to Reproduce:

1. Copy HTML code and try ALT+SHIFT+F
2. Does not work properly.
```
<h2 class="project_header section_header">
                    <a class="project_link" href="#"><span>Shopping</span>
                    </a>
                    <div class="right_task_actions">
                        <a href="#"><img class="cmp_share_project" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
                        </a>
                        <a href="#">
                            <img class="cmp_task_actions icon" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
                            </a>
                        </div>
                </h2>
```
Copy/Paste above code and try to press, Format Code shortcut, nothing happens.

Expected behavior is that span would indent below in "a" tag. also that div's and a's ending tags will align but nothing happens.

What would I expect is following:
```
<h2 class="project_header section_header">
        <a class="project_link" href="#">
               <span>Shopping</span>
        </a>
        <div class="right_task_actions">
               <a href="#">
                       <img class="cmp_share_project" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
               </a>
               <a href="#">
                       <img class="cmp_task_actions icon" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
               </a>
         </div>
</h2>
```
I have tried also CTRL+SHIFT+X to delete spaces and then do a format again but nothing happened.

Format will not work on following code as well:
```
<h2 class="project_header section_header">
<a class="project_link" href="#"><span>Shopping</span>
</a>
<div class="right_task_actions">
<a href="#"><img class="cmp_share_project" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
</a>
<a href="#">
<img class="cmp_task_actions icon" src="/app/app/assets/76084e29cb2cf72b320e888edc583dfb.gif" height="16" width="26">
</a>
</div>
</h2>
```

What is the logic behind code formatting, is there anything we can do by config?

**Comment by MeirionHughes** [comment] 2016-05-18 15:12
I'm having trouble with the html code formatting too. Sometimes it seems to work other times it doesn't. I'm specifically using aurelia templates: which look like: 

```
<template>
 <require from="./menu-bar.css"</require>
  <div class="menu-bar">    
   <div class="dropdown">
    <button class="dropbtn">File</button>
    <div class="dropdown-content">
      <a href="#">Link 1</a>
      <a href="#">Link 2</a>
      <a href="#">Link 3</a>
    </div>
  </div>
</template>
```

**Comment by Gheoan** [comment] 2016-05-23 07:24
Formatting does not work when the top level tag is heading (`h1`, `h2`, etc.) or `template`.
As a workaround comment the top level tag, format the code then uncomment the top level tag.

**Comment by oodboo** [comment] 2016-05-23 07:32
@Gheoan Thank you but as workaround I could do it manually, so workaround is not the option... we are trying to find and fix the issues ....

**Comment by aeschli** [comment] 2016-05-23 09:54
This has to do with the HTML formatter configuration. Both 'a' and 'template' are by default on the list of unformatted tags.
In the next build I remove template from that list and make the list explicit in the settings.
See my comment in #5426 how you can configure the list of unformatted html elements

Duplicate of #5426

**Closed by aeschli** 2016-05-23 09:54 UTC

**Comment by oodboo** [comment] 2016-05-23 11:15
@aeschli My settings file definitely growing each day ...

**Comment by aeschli** [comment] 2016-05-23 12:58
@oodboo With my changes you should be able to use the default again.. :-)

**Comment by oodboo** [comment] 2016-05-23 13:05
@aeschli thank you :)

**Comment by a-eid** [comment] 2017-08-27 17:26
+1
