### ISSUE TITLE
Extension host terminated unexpectedly error after installation 

### ISSUE THREAD

**Issue by santoshyadav198613** [microsoft/vscode#94973] opened 2020-04-11 04:43 UTC
- VSCode Version: 1.44.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. 
![image](https://user-images.githubusercontent.com/11923975/79035502-ee583080-7bdc-11ea-897c-2a5e855fe8b0.png)

Console log
![image](https://user-images.githubusercontent.com/11923975/79035516-08920e80-7bdd-11ea-9797-6c46a691ec65.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-04-11 06:40
Duplicate of https://github.com/microsoft/vscode/issues/94807, please see https://github.com/microsoft/vscode/issues/94858#issuecomment-611905765

**Closed by RMacfarlane** 2020-04-11 06:40 UTC
Labels: new release
