### ISSUE TITLE
NPM scripts explorer doesn't show all scripts in multiroot workspace

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#54307] opened 2018-07-14 13:07 UTC
- VSCode Version: 1.25.1
- OS Version: Arch Linux x64

Steps to Reproduce:

1. create a multiroot workspace with 2 folders
2. add package.json to each folder containing npm scripts, some of them having the same name in both folders

Expected results: all npm scripts for both folders are shown
Actual results: all npm scripts for the first folder are shown; for the second folder, only npm scripts that have a name not occurring in the first folder are shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by hbenl** [comment] 2018-07-14 14:08
I checked the listed issues and none of them seems to be a duplicate of this one.

**Comment by egamma** [comment] 2018-07-16 14:37
This looks like a duplicate of #54085.

This is the interesting information
>Actual results: all npm scripts for the first folder are shown; for the second folder, only npm scripts that have a name not occurring in the first folder are shown

**Comment by egamma** [comment] 2018-07-17 06:52
Closing as duplicate of #54085

**Closed by egamma** 2018-07-17 06:52 UTC
