### ISSUE TITLE
Debug Breakpoints not working

### ISSUE THREAD

**Issue by psmocko** [Microsoft/vscode#45657] opened 2018-03-13 13:33 UTC
Issue Type: <b>Bug</b>

After getting te last update, breakpoints no longer work. The breakpoints are breaking on the wrong line of code and therefore are not working.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3491)|
|Memory (System)|15.92GB (6.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.7
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
Angular-BeastCode|Mik|5.2.18
team|ms-|1.122.0
debugger-for-chrome|msj|4.2.0
vscode-icons|rob|7.21.0

</details>
Reproduces without extensions

**Comment by isidorn** [comment] 2018-03-13 13:38
Wow there cowboy. What language are you debugging?
Can you provide a simple repository for which we can reproduce this constantly?

**Comment by psmocko** [comment] 2018-03-13 16:45
The language is typescript\JavaScript. I have not had this problem until
the latest update this week. I do not have a repo at this point as this is
code I a developing at work. I can try to reproduce in another project if
need be.

Paul

**Comment by lostfields** [comment] 2018-03-14 07:57
I got the same problem using typescript and ts-node. It works when I'm using the keyword `debugger` though.

This is a showstopper, have to downgrade (again)

If you want an example, you may clone https://github.com/lostfields/express-ts-router and open the workspace file after installing dependency and laund the debug "Launch mocha tests (workspace)"

**Comment by weinand** [comment] 2018-03-14 09:12
@lostfields the launch.json is missing from the project. How does your launch.json look like?

**Comment by lostfields** [comment] 2018-03-14 09:38
@weinand the launch is inside the workspace file. You have to open it as a workspace (not folder).

**Comment by weinand** [comment] 2018-03-14 10:46
Aha, thanks. I've filed an issue about this https://github.com/Microsoft/vscode/issues/45749

**Comment by weinand** [comment] 2018-03-14 11:00
Your setup works fine for me on macOS with VS Code 1.21 and 1.22.
I'll try to reproduce on Windows...

**Comment by chrumck** [comment] 2018-03-14 11:03
Same problem here. [Here's](https://github.com/chrumck/VSCodeDebuggingDebugger) a little project I've created for showcase the problem. If you set a breakpoint in the gulpFile.js, it's not going to get hit. Interestingly, after changing the casing from gulpFile.js to gulpfile.js and re-setting the breakpoints, they do get hit!
My problem started breakpoints in ts files and Jest test suites though, so I tried the trick of changing the casing there, but it doesn't work the same way.

**Comment by weinand** [comment] 2018-03-14 11:10
Yep, I can repo on Windows.
Are you all seeing this issue on Windows?

**Comment by chrumck** [comment] 2018-03-14 11:22
@weinand I'm on Windows.

**Comment by weinand** [comment] 2018-03-14 12:01
@roblourens I've produced [debug-logs](https://github.com/Microsoft/vscode/files/1810886/traces.zip)
 for VS Code 1.20.3 (where the bp is hit) and 1.21.0 (where the bp is missed).

There is an interesting difference when the TS file with the breakpoint ("basic.ts") is loaded. In 1.20.3 the load triggers a SourceMaps.setBP in 1.21.0 it does not.

Please note that we started to normalize drive letters in 1.21 (see #43959).

VS Code 1.20.3:
```
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts
SourceMap: creating for c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts
SourceMap: sourceRoot: undefined
SourceMap: sources: ["C:\\Users\\weinand\\Projects\\REPROS\\bug45657\\express-ts-router\\src\\test\\basic.ts"]
SourceMap: no sourceRoot specified, using script dirname: c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test
SourceMaps.scriptParsed: c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts was just loaded and has mapped sources: ["c:\\Users\\weinand\\Projects\\REPROS\\bug45657\\express-ts-router\\src\\test\\basic.ts"]
SourceMaps.setBP: Mapped c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts to c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts
SourceMaps.setBP: Mapped c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts:22:1 to c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts:16:5
SourceMaps.setBP: Mapped c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts:29:1 to c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts:20:9
→ To target: "{\"id\":13,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"195\",\"lineNumber\":15,\"columnNumber\":0},\"end\":{\"scriptId\":\"195\",\"lineNumber\":16,\"columnNumber\":0},\"restrictToFunction\":false}}"
→ To target: "{\"id\":14,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"195\",\"lineNumber\":19,\"columnNumber\":0},\"end\":{\"scriptId\":\"195\",\"lineNumber\":20,\"columnNumber\":0},\"restrictToFunction\":false}}"
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"196",....
```

VS Code 1.21.2:
```
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts
SourceMap: creating for c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts
SourceMap: sourceRoot: undefined
SourceMap: sources: ["C:\\Users\\weinand\\Projects\\REPROS\\bug45657\\express-ts-router\\src\\test\\basic.ts"]
SourceMap: no sourceRoot specified, using script dirname: c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test
SourceMaps.scriptParsed: c:\Users\weinand\Projects\REPROS\bug45657\express-ts-router\src\test\basic.ts was just loaded and has mapped sources: ["c:\\Users\\weinand\\Projects\\REPROS\\bug45657\\express-ts-router\\src\\test\\basic.ts"]
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"195",....
```

**Comment by psmocko** [comment] 2018-03-14 17:08
I am on Windows as well. This just started after the last update.

Paul

**Comment by roblourens** [comment] 2018-03-15 04:25
@weinand Thanks for the logs, wish I'd seen them earlier today. I came to the same conclusion after much debugging. I don't think I knew about the drive letter normalization. Unfortunately the debug adapter normalizes to lower case, but doesn't do it for one case that's being hit here.

**Comment by roblourens** [comment] 2018-03-15 23:37
Summary - this was broken by #43959, there is one case where the adapter doesn't correctly fix the drive letter case. I have a low-impact fix, everyone please try it in tomorrow's Insiders build (or the next vscode-chrome-debug update).

Marked as candidate in case we get a 1.21.2 out but wouldn't trigger a .2 by itself.

The best workaround for people using 1.21 is to set the `outFiles` parameter in your launch config so that the adapter can load the sourcemaps before debugging starts. This is generally the best thing to do, and partly explains why this wasn't found earlier, because it won't repro with that set.

For people using ts-node, outFiles doesn't help because the sourcemaps don't exist on disk, so they can't be preloaded. The only workaround there is to deactivate then reactive breakpoints after debugging has started, since the bug is avoided if BPs are set when the scripts have been loaded. Or, right click the breakpoints pane and "Reapply all breakpoints".

**Closed** 2018-03-15 23:53 UTC
Labels: bug, candidate, debug

**Comment by TwitchBronBron** [comment] 2018-03-16 16:52
I just tested the latest insiders build and it's still not working quite right. See my comment in an example project [here](https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging/issues/9#issuecomment-373681660).

*Some* breakpoints are being hit again. However, not all of them. Some are skipped.

**Comment by borekb** [comment] 2018-03-16 17:21
> Or, right click the breakpoints pane and "Reapply all breakpoints". (https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464)

This seems to work for plain debugging but not for tests in our ts-node + Jest + ts-jest project:

![image](https://user-images.githubusercontent.com/101152/37534745-ea08271a-2945-11e8-81d8-f1ec6d47d18e.png)

For reference, ts-jest issue: https://github.com/kulshekhar/ts-jest/issues/466

**Comment by borekb** [comment] 2018-03-16 18:46
I'm experimenting some more and some things seem really weird. For example, when trying to debug Jest tests in TS, ever **even** try hits a breakpoint while every **odd** one fails. Maybe Jest is doing something funny because on every other run, I see this progress bar in the console:

![image](https://user-images.githubusercontent.com/101152/37538848-3a3ec64c-2952-11e8-8de2-824f607bda7a.png)

and breakpoints are not hit only when I see this. Strange..

BTW this is in Insiders (1.22.0-insider 9160e85b1ab0333dfe697032f90da494f1f81fd4) where I can confirm the current patch seems to generally work, compared to 1.21.1 stable version which never hits any breakpoints in my test scenario.

**Comment by roblourens** [comment] 2018-03-16 22:00
Can you share your project? I tried the repo from https://github.com/kulshekhar/ts-jest/issues/466 and it now works fine for me.

**Comment by borekb** [comment] 2018-03-17 00:17
@roblourens I actually just reproduced the issue with the repo given in kulshekhar/ts-jest#466 in 1.22.0-insider 9160e85. Is there more info I could provide?

**Comment by borekb** [comment] 2018-03-18 09:53
@roblourens Are there links to previous Insider versions of VSCode? I'd try the 1.20 version but hesitate to do so in my main VSCode installation. (Would be interesting to have access to previous links to VSCode Insiders anyway.)

**Comment by lostfields** [comment] 2018-03-18 21:08
https://github.com/lostfields/express-ts-router

@roblourens It doesn't work for me in this project, works in 1.20.1, but not in 1.22.0-insider. I got the logs but they are huge.

**Comment by lostfields** [comment] 2018-03-19 07:31
@roblourens why is this closed when it still doesn't work?

**Comment by JosepAlacid** [comment] 2018-03-19 20:25
@roblourens 
> Or, right click the breakpoints pane and "Reapply all breakpoints".

**Comment by lostfields** [comment] 2018-03-20 06:43
@roblourens @JosepAlacid reapply breakpoints works but I really hope that's a temporary work-around.

**Comment by vytautas-pranskunas-** [comment] 2018-03-20 11:53
When can we expect it to be fixed and released - it is very annoying to write tests without debugging...

**Comment by roblourens** [comment] 2018-03-21 17:28
@lostfields Trying multiple projects and windows machines, I still haven't been able to reproduce another issue in Insiders.

That part of the log isn't large enough, could you upload the whole thing? You can send it to the email address in my profile if that's easier.

Also, could you set `"breakOnLoadStrategy": "regex"` in the launch config and try again? You will get a warning about that property not being recognized but you can ignore it. It's an experimental feature that could help here.

**Comment by lostfields** [comment] 2018-03-22 07:14
@roblourens Hi, I've mailed you the logs now, for the newest insider vs vscode 1.20.1. Have you opened the project at https://github.com/lostfields/express-ts-router as a **Workspace** ? The workspace file contains the launch code I've been using.

```
{
    "name": "Launch mocha tests",
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot:express-ts-router}/node_modules/mocha/bin/_mocha",
    "stopOnEntry": false,
    "args": ["--no-timeouts", "--compilers", "ts:ts-node/register", "${workspaceRoot:express-ts-router}/src/test/*.ts"],
    "cwd": "${workspaceRoot:express-ts-router}",
    "protocol": "inspector",
    "trace": true
}
```

Still got issues. I had to remove the "breakOnLoadStrategy" for 1.20.1 since my breakpoints didn't hit when I had this. For 1.22.0 it didn't matter whether it was there or not, since my breakpoints never hit.

**Comment by lostfields** [comment] 2018-03-22 07:35
@roblourens I may have found something interesting. Open my project as a Workspace using the `express-ts-router.code-workspace` file: https://github.com/lostfields/express-ts-router

## Launch "Run program (workspace)"
### 1.22.0 
Debugging by launching "Run program (workspace)" works if I place a breakpoint at `src/index.ts:10`, but it does not break at my breakpoint at `src/express/router.ts:15`

### 1.20.1
I did the same thing here, breakpoints at `src/index.ts:10` and `src/express/router.ts:15`. The last one didn't hit, I had to set a breakpoint at `src/index.ts:8` to get all breakpoints to hit.

## Launch "Launch mocha tests (workspace)"
### 1.22.0
Never hits the breakpoint if I place it at `src/test/basic.ts:30`

### 1.20.1
Hits the breakpoint at `src/test/basic.ts:30`

**Comment by roblourens** [comment] 2018-03-22 17:14
Yes, I've been opening it as a workspace and testing with the same launch config and setup, and hitting the breakpoint. Received the logs, thanks.

**Comment by denismp** [comment] 2018-03-22 17:15
I recently upgraded to 1.21.0 and now 1.21.1, both of which broke the breakpoints.  I tried going back to version 1.16, which really messed things up, so now I am at 1.21.1.  Is there going to be a fix to this?

**Comment by roblourens** [comment] 2018-03-22 17:17
Try Insiders https://code.visualstudio.com/insiders


https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464

**Comment by lostfields** [comment] 2018-03-22 19:03
@roblourens my disk (harddrive) is pretty slow at the moment, may that affect anything?

```
Version 1.22.0-insider
Commit b75321329388d74e34f79dcfcb789246e31836a8
Date 2018-03-22T06:16:52.928Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by roblourens** [comment] 2018-03-23 19:36
Looking at it offline with @lostfields, we found that an old version of the node-debug2 extension was somehow installed.

@borekb I think you also are still having issues using Insiders. Could you check whether you have anything at `<home folder>/.vscode-insiders/extensions/ms-vscode.node-debug2-something`?

**Comment by borekb** [comment] 2018-03-23 21:32
@roblourens Nope :(

```
~/.vscode-insiders/extensions
$ ls -l
total 12
drwxr-xr-x 1 Borek 197609 0 Feb 22 09:16 EditorConfig.editorconfig-0.12.1/
drwxr-xr-x 1 Borek 197609 0 Mar  6 13:47 Shan.code-settings-sync-2.9.0/
drwxr-xr-x 1 Borek 197609 0 Mar 10 14:30 yzhang.markdown-all-in-one-1.1.0/
```

**Comment by dh94** [comment] 2018-03-24 11:29
for me the latest version of the insiders fixed it 👌

**Comment by FilipLaurentiu** [comment] 2018-03-26 05:41
Still broke Debugger for Chrome version 4.2.2, Vs Code 1.21.1

**Comment by roblourens** [comment] 2018-03-26 06:12
Please open a new issue in https://github.com/microsoft/vscode-chrome-debug/issues with details

**Comment by psmocko** [comment] 2018-03-26 11:07
That is the whole issue that got me onto this thread. Chrome debugging.
Unfortunately I do not have the luxury of time to help out by installing
and trying out all of these different versions as I  am the sole dev on a
big project right now.

Paul

**Comment by rebornix** [comment] 2018-03-30 19:32
@roblourens can you provide more details about what we should verify?

**Comment by roblourens** [comment] 2018-03-30 21:37
Easy way is to clone https://github.com/Jostar1024/ts-jest-vscode-1.21.0, set breakpoints in the tests, run the launch config. It should hit the BPs in insiders but not stable
