### ISSUE TITLE
Image attachments aren't retained in history

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#229626] opened 2024-09-24 21:14 UTC
Testing #229263

Probably something you're tracking already, but up-arrowing in my history doesn't retain image attachments like it does normal file attachments :)

**Comment by justschen** [comment] 2024-09-24 21:17
yep will likely have to do some work for local file storage for pasted images (other scenarios are a little easier since we ie, images in the workspace because already have the resource), but looking into it 🫡

**Comment by justschen** [comment] 2024-10-31 23:56
closing, as this should be fixed now

**Closed by justschen** 2024-10-31 23:56 UTC
Labels: bug

**Comment by anthonykim1** [comment] 2024-12-05 18:06
When using PDF such as : [dqd.pdf](https://github.com/user-attachments/files/18027754/dqd.pdf)
It keeps saying that it can't assist, although its programming related :/
![Image](https://github.com/user-attachments/assets/f8798e89-8023-44d7-b135-c9c57f07e85b)
Am I doing something wrong? @justschen

**Comment by justschen** [comment] 2024-12-06 07:34
@anthonykim1 the issue is tracking history via up/down arrows haha i don't think what you described there is connected to the actual issue.

try:
1. attach an image (png)
2. submit (it will fail if you don't have the extension)
3. use arrrows to go thru history and make sure it attaches again

I also don't believe chat has access to whole PDF files atm?
