### ISSUE TITLE
Custom Stylesheet Support

### ISSUE THREAD

**Issue by codejockie** [Microsoft/vscode#36745] opened 2017-10-23 11:29 UTC
Please VSCode team, could you add support for custom stylesheet like Atom does? I want to be able to change my editor background image. This is supported on WebStorm as a plugin, it is supported on Atom by editing the Custom Stylesheet provided.
I would love to see this feature add.

- VSCode Version: 1.17.2
- OS Version: macOS High Sierra

Great work so far!!!

**Comment by mjbvz** [comment] 2017-10-23 15:56
Duplicate of #459

**Closed by mjbvz** 2017-10-23 15:56 UTC
Labels: duplicate, new release
