### ISSUE TITLE
Editor navigation behaviour like in Visual Studio

### ISSUE THREAD

**Issue by ygoe** [Microsoft/vscode#41620] opened 2018-01-15 12:05 UTC
- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Write a line that starts with indenting and a few space-sparated words
2. Place the cursor at the beginning of the line
3. Press Ctrl+Right

Now the cursor is *behind* the first word. It should really be in front of it.

It feels like there's a number of differences in the keyboard cursor control between VS Code and VS (and other editors like Notepad++). That makes it extremely hard to navigate the code because the cursor always lands somewhere else than what I'm used to from other editors. I don't expect much from the textarea fields in web browsers, but real code editors need to have a predictable and consistent behaviour. Otherwise I need to stop editing blindly and verify the correct cursor location after every singe keypress. That reduces my productivity so much that I might as well discard all the benefits I get from VS Code and stick with good old Notepad++. No code completion, no debugging, just solid editing. That's worth *so* much.

PS: I also get irritated by the PageUp/Down keys. They always end up somewhere else than VS or NPP would. Makes it so hard to use this editor. (That editor inconsistency everywhere was one of the reasons I sold the one Mac I had long ago to return to Windows on my second computer.)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-01-17 15:29
Duplicate of https://github.com/Microsoft/vscode/issues/3577#issuecomment-197824244

To control this behaviour and get VS-style Ctrl+Right, please edit your `keybindings.json` and add:

```
{ "key":"ctrl+right",       "command":"cursorWordStartRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordStartRightSelect", "when":"editorTextFocus" }
```

This will overwrite the defaults:

```
{ "key":"ctrl+right",       "command":"cursorWordEndRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordEndRightSelect", "when":"editorTextFocus" }
```

**Comment by alexandrudima** [comment] 2018-01-17 15:30
@rebornix Can we also add these (if we haven't already) to the Visual Studio keymap ?

**Closed by alexandrudima** 2018-01-17 15:29 UTC
Labels: editor, editor-core
