### ISSUE TITLE
Some keyboard shortcuts stop working when launching from terminal

### ISSUE THREAD

**Issue by azdavis** [microsoft/vscode#71553] opened 2019-04-01 16:18 UTC
- VSCode Version: Version: 1.33.0-insider, Commit: 4039ea871879ef8f654f27df5c32d209104b3a44
- OS Version: Darwin x64 18.5.0

Steps to Reproduce:

1. Launch VSCode with no files
2. Open a new file from a terminal (not VSCode's terminal; something like `code file.txt`)
3. Try to use Add Next Occurrence (see below); it doesn't work (the menu bar just 'flashes')
4. Move the focus away from VSCode (e.g. click on some other app), then back
5. Try to use Add Next Occurrence; it does work

What I did to "try to use Add Next Occurrence":

1. Type `asdf`
2. Hit Command-D (the shortcut for Add Next Occurrence)
3. Expect it to select `asdf`, it doesn't

A similar issue occurs with Copy Line Down. But the issue does not occur with Add Cursor Above or Add Cursor Below. I haven't tried other shortcuts.

The issues does not appear to happen if you skip step 1. But even if you skip step 1, it only doesn't happen for the first time.

What that means is: if VSCode is not running, and I launch it with `code file.txt`, then the shortcuts work in `file.txt`. But if I then do `code other.txt`, then the shortcuts do not work until I move the focus away and back as described.

Actually, the filename `other.txt` doesn't even have to be different from `file.txt`. So I can do `code file.txt` and the shortcuts will work, but then I can do `code file.txt` again and the shortcuts stop working.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2019-04-02 10:14
@azdavis I cannot reproduce on my mac. I launch `code README.md` for example and press cmd+d. This works immediately for me.

**Comment by azdavis** [comment] 2019-04-02 13:04
Hm. Was VSCode already running when you said `code README.md`? Also, from my testing the bug only seems to occur when the file does not already exist. When you tried it, did README.md already exist?

I can reliably reproduce this on my Mac; I can try to attach a screen recording if that might help.

**Comment by alexandrudima** [comment] 2019-04-02 14:27
@azdavis I could not reproduce even if the file does not exist. Have you by any chance customized your `keybindings.json`?

**Comment by azdavis** [comment] 2019-04-02 15:25
[Here][1] is my keybindings.json.

However, the problem persists even when I turn off the custom keybindings.

[Here][2] is a video of the problem.

[1]: https://github.com/azdavis/dotfiles/blob/master/vscode/user-data/User/keybindings.json
[2]: https://www.dropbox.com/s/5rudrr1ej5lnq3j/vscode-bug.mov?dl=0

**Comment by alexandrudima** [comment] 2019-04-03 15:54
Thank you, I could now reproduce.

**Comment by iliyang** [comment] 2019-05-07 15:16
I have the same problem when activating an open instance of VS Code via the URL scheme `vscode://` from the Skim PDF viewer. This bug is an issue when working with LaTeX, where the URL-scheme activation is a very common task.

**Comment by Dreen** [comment] 2019-06-12 10:47
Can confirm this bug also occurs when using the "Semantic History" feature of iTerm2 Build 3.2.9 (Cmd+Click to open file).

However, there is a workaround that seems to work 100% for me; just right-click inside the document to bring out the context menu, then close that menu, and the key shortcuts should work.

**Comment by phaseOne** [comment] 2019-06-14 20:09
I ran into this exact issue today when attempting and failing to use the ⌘D "add next occurrence" keyboard shortcut. Calling the function from the menubar did work, so it's specifically an issue with the shortcut. I didn't open vscode from iTerm though. I already had it open, and then I opened an existing workspace from the **Open Recent** menu. I also had an integrated terminal open, but I hadn't interacted with it.

I used @Dreen's workaround to solve the issue. I haven't been able to reproduce yet.

* _VSCode Version 1.34.0_
* _macOS Mojave 10.14.4 (18E226)_

**Comment by Figbash** [comment] 2019-08-05 16:41
This happens constantly if you use VSCode as an IDE for Unity 3D, every time you double to click a log to jump to the file/line in the code you can no longer use ⌘D until performing and canceling a find. It's nearly frustrating enough to switch IDEs if you use ⌘D a lot, if anyone could give this some attention that would be amazing.

**Comment by azdavis** [comment] 2019-08-11 00:19
This issue appears to happen also if you close an editor pane and dismiss unsaved changes.

Steps to reproduce:

1. Open foo.txt, put something into it like `foo\nfoo`
1. Open bar.txt, put something in it like `bar\nbar`
1. Save both
1. Switch to bar.txt, make some changes
1. Close bar.txt, hit Don't Save
1. You should now be switched to foo.txt and the focus should be on the first `foo`
1. Try to use Cmd-D
1. It doesn't work

**Comment by alexandrudima** [comment] 2019-09-09 12:51
Looks like this one shares the same root cause as https://github.com/microsoft/vscode/issues/79460

**Comment by bpasero** [comment] 2019-09-10 05:19
@azdavis i
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by azdavis** [comment] 2019-09-10 05:58
I am still able to reproduce this issue.

**Comment by bpasero** [comment] 2019-09-10 06:54
@alexandrudima I am able to reproduce https://github.com/microsoft/vscode/issues/71553#issuecomment-520189587 and here is what I observe so far:
* it only reproduces with context key `editorFocus` but not `editorTextFocus` which indicates that the underlying issue is focus tracking
* once the native dialog opens we correctly set `editorFocus: false`
* once the native dialog closes, we do NOT restore `editorFocus: true`
* as such, `Cmd+D` fails to work

Now, here is what I do in the workbench after the dialog closes:
* the second (dirty) editor is not to be saved, so I close it
* as such I reveal the first editor
* this eventually calls into `textAreaInput#_setHasFocus(true)`
* for some reason (and this is the bug actually), we think `this._hasFocus === newHasFocus` and return from that method without firing events

Can you please have a look as well.

**Comment by alexandrudima** [comment] 2019-09-11 12:30
:+1: I've pushed a fix for the `editorFocus` context key not being set correctly.

**Closed** 2019-09-11 12:45 UTC
Labels: bug, mac
