### ISSUE TITLE
No prompt when adding a folder to a trusted workspace

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#122292] opened 2021-04-27 09:28 UTC
Testing #122233

1. Open a folder. I opened C:\users\alros\documents\one
2. Trust the folder.
3. Open the trust manager to see what's going on.
3. File -> Add folder to workspace. I added c:\users\alros\documents\two
4. No prompt to trust the newly added folder 🐜 But I can see that the workspace went into restricted mode.

**Comment by lszomoru** [comment] 2021-07-21 07:38
This must have been a regression that we have already addressed as I cannot reproduce the issue any more. Closing for now.

**Closed by lszomoru** 2021-07-21 07:38 UTC
Labels: bug, workspace-trust
