### ISSUE TITLE
Issue with text highlighting when editing mixed LTR/RTL text

### ISSUE THREAD

**Issue by Arshia001** [Microsoft/vscode#59177] opened 2018-09-23 10:13 UTC
Issue Type: <b>Bug</b>

1. Type a block of RTL text followed by an LTR block (for example, 'سلام hello')
2. Highlight the last (left-most, م in the example above) character of the RTL block

Expected: only the last letter is highlighted
Actual: the entire RTL block is highlighted

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexandrudima** [comment] 2018-10-08 09:07
Duplicate of #58273. The fix is available in the [Insiders release](https://code.visualstudio.com/insiders/) and will become available with the next Stable release.

**Closed by alexandrudima** 2018-10-08 09:07 UTC
Labels: editor, editor-contrib
