### ISSUE TITLE
TypeScript Language service Died

### ISSUE THREAD

**Issue by stawen** [microsoft/vscode#119182] opened 2021-03-17 13:13 UTC
Issue Type: <b>Bug</b>

Just on a simple typescript project. Vs Code lauch Initializing JS/TS
And a have this popup 

![image](https://user-images.githubusercontent.com/13132210/111473030-e24ceb00-872a-11eb-84a6-b185177367c0.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1108-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.99GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bvm-pulumi/home/jumpuser/dev --crash-reporter-id 8416884d-8bcc-4656-b44c-9c3ec2df0ecc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm-pulumi|
|OS|Linux x64 4.15.0-1108-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (2 x 2095)|
|Memory (System)|7.79GB (0.54GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.5

</details>

**Comment by mjbvz** [comment] 2021-03-17 20:49
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by stawen** [comment] 2021-03-18 10:03
hi, here more information

My output typescript

```bash
[Info  - 09:35:41.856] Starting TS Server 
[Info  - 09:35:41.856] Using tsserver from: /home/jumpuser/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 09:35:41.858] <syntax> Log file: /home/jumpuser/.vscode-server/data/logs/20210317T193016/exthost4/vscode.typescript-language-features/tsserver-log-788iNA/tsserver.log
[Info  - 09:35:41.858] <syntax> Forking...
[Info  - 09:35:41.864] <syntax> Starting...
[Info  - 09:35:41.867] <semantic> Log file: /home/jumpuser/.vscode-server/data/logs/20210317T193016/exthost4/vscode.typescript-language-features/tsserver-log-NWHbk0/tsserver.log
....
and again and again
....
....
[Info  - 09:50:22.702] <syntax> Forking...
[Info  - 09:50:22.715] <syntax> Starting...
[Info  - 09:50:22.715] <semantic> Log file: /home/jumpuser/.vscode-server/data/logs/20210317T193016/exthost4/vscode.typescript-language-features/tsserver-log-QHI6ys/tsserver.log
[Info  - 09:50:22.716] <semantic> Forking...
[Info  - 09:50:22.723] <semantic> Starting...
```

Here the first log file from tsserver-log-788iNA/tsserver.log
[tsserver-log-788iNA.zip](https://github.com/microsoft/vscode/files/6163078/tsserver-log-788iNA.zip)

the last log file from tsserver-log-QHI6ys/tsserver.log
[tsserver-log-QHI6ys.zip](https://github.com/microsoft/vscode/files/6163089/tsserver-log-QHI6ys.zip)

**Comment by mjbvz** [comment] 2021-03-18 20:10
Thanks. From the logs, this is a duplicate of https://github.com/microsoft/TypeScript/issues/43105

Closing as upstream

**Closed by mjbvz** 2021-03-18 20:10 UTC
Labels: needs more info, new release
