### ISSUE TITLE
Corrupt Menu Rendering

### ISSUE THREAD

**Issue by enly1** [Microsoft/vscode#56738] opened 2018-08-18 11:57 UTC
Issue Type: <b>Bug</b>

Menus rendering broken with update to electron.
Appears to be gpu acceleration related - fixed by starting with --disable-gpu

Running on Dell XPS 9570 ( nvidia and intel )

Looks like an upstream issue now impacting vscode.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.31GB (11.82GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1

</details>

**Comment by bpasero** [comment] 2018-08-18 12:39
@enly1 do you have a screenshot?

**Comment by lukewiwa** [comment] 2018-08-18 13:26
![vscode_menu](https://user-images.githubusercontent.com/2504992/44299673-162abe80-a33e-11e8-8459-9c17debfe9c8.png)

Like this perhaps?

**Comment by enly1** [comment] 2018-08-18 16:07
This is the screenshot from vscode when not running --disable-gpu



Same problem showing up in Chrome ...


Disabling GPU acceleration works fine.

My laptop is a Dell XPS9570 i7
Linux mint 19 installed
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Intel graphics and NVidia 1050-TI-MaxQ

vscode was okay on this machine until recent update, although not sure
which one and if it was vscode, chrome, electron or drivers.

vscode is fine in Windows as is chrome with the same version of chrome and
electron (in vscode, windows was insiders)

So looks like an upstream issue - but another reason I'm thinking that this
laptop isn't the winner for me.

Simon

**Comment by enly1** [comment] 2018-08-19 11:11
![vscode-corrupt-menu-small](https://user-images.githubusercontent.com/5808106/44308211-e533a380-a3a8-11e8-82da-1d602f776410.png)

Can't add image to edited post, so adding it here.

**Comment by bpasero** [comment] 2018-08-20 08:33
@enly1 as a workaround you could configure `"window.titleBarStyle": "custom"`.

@lukewiwa your issue seems different because it looks like you are using our custom menu, can you report a separate issue?

**Comment by enly1** [comment] 2018-08-20 09:39
@bpasero  - afraid I can't use that workaround.  The reason I am using that titlebar setting currently is to workaround a bug / regression with precision touchpad drivers which results in scroll lockups etc.  (Don't have the issue number to hand)  

The fix for that was to disable custom titlebars.  Catch22.

**Comment by enly1** [comment] 2018-08-20 09:40
@bpasero - I've worked around it for now by hacking --disable-gpu into the launch command for the electron app as I launch it from many places (launchers etc), so can't add it manually to command lines when using.

**Comment by bpasero** [comment] 2018-08-20 09:42
@enly1 is this ArchLinux?

@enly1 can you try to reproduce with a newer build that is using Electron 3.0.x: https://az764295.vo.msecnd.net/exploration/57d01751b88c89046b33be3f1d55f860041fd27b/code-exploration-1534445620.tar.gz

**Comment by enly1** [comment] 2018-08-20 10:07
@bpasero - Linux Mint 19 - mate desktop.
Linux dev-XPS-15-9570 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'll take a look at electron 3 over the next couple of days - limited time available at present.

**Comment by enly1** [comment] 2018-08-20 12:03
@bpasero - just tested electron 3 - same issue.

**Comment by logTom** [comment] 2018-08-20 12:31
I have the same problem as lukewiwa in the 2nd post on solus linux.
vscode version 1.26.1
uname -a
Linux logmediapc002 4.17.14-86.current #1 SMP PREEMPT Sat Aug 11 13:47:11 UTC 2018 x86_64 GNU/Linux

**Comment by bpasero** [comment] 2018-08-20 13:46
@logTom @enly1 did this happen in previous versions of VSCode too?

**Comment by logTom** [comment] 2018-08-20 13:52
No.
This bug only occurs for me with "window.titleBarStyle": "custom".
I will stick with "window.titleBarStyle": "native" until this issue is solved.
Here is the full "Help"->"About" dialog:
![screenshot from 2018-08-20 15 51 18](https://user-images.githubusercontent.com/17121556/44344404-ef30d180-a490-11e8-8ed0-ef551dc2a5c9.png)

**Comment by bpasero** [comment] 2018-08-20 13:57
Yeah sorry, I was referring to those that see this issue with the native title.

**Comment by enly1** [comment] 2018-08-20 15:02
@bpasero - just tested electron 3 - same issue.

**Comment by enly1** [comment] 2018-08-20 15:04
@bpasero - It was working fine with vscode - I know it was good as I settled on the alt menu style when I worked out the bug for the scrolling issues - wasn't there then.

This is an upstream issue with chrome as far as I can tell, cascaded down into electron and vscode.

**Comment by sbatten** [comment] 2018-08-20 17:56
@logTom, you may see this issue in the custom titlebar resolved in the latest insiders as some rendering changes were made relating to mnemonics. If you would like to give it a try and let us know that would be great. Thanks,
SteVen

**Closed** 2018-08-28 20:01 UTC
Labels: electron, needs more info, upstream, workbench-menu
