### ISSUE TITLE
[Feature Request] provide api to custom snippetVariables

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#37021] opened 2017-10-27 06:07 UTC
- VSCode Version: 1.17.2
- OS Version: Mac

Steps to Reproduce:

want to use custom variables(which provided by extension) at snippets define

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippetVariables.ts

maybe: 
```js
// extension.ts
vscode.commands.executeCommand("setSnippetVariables", "TM_FRAMEWORK", 'egg');
```

```js
// snippet
const Controller = require('${1:${TM_FRAMEWORK}}').Controller;
```

now I use `vscode.languages.registerCompletionItemProvider` + `insertText` to workaround.

**Comment by jrieken** [comment] 2017-10-27 08:20
dupe of #10561

**Closed by jrieken** 2017-10-27 08:20 UTC
