### ISSUE TITLE
VSCode flozen and sometimes shutdown and tell me many problems

### ISSUE THREAD

**Issue by AtsushiYamashita** [Microsoft/vscode#60751] opened 2018-10-12 08:08 UTC
# VSCode flozen and sometimes shutdown and tell me many problems

## Overview

My first issue for OSS in English :)

My VSCode is heavy and sometimes down.
It tell me many problems.
![image](https://user-images.githubusercontent.com/14036783/46856061-6a36b880-ce40-11e8-9b19-9bd006a9111a.png)

Please couch me for fix.

## Environment

- Extension Name: extension-editing
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

![image](https://user-images.githubusercontent.com/14036783/46856386-4031c600-ce41-11e8-8d2b-7bedd9f99594.png)

## Detail 

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 272,
		"activateCallTime": 3,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:markdown"
	}
}
```
Sometimes, the problem don't happen.
I have wonder, What things make that.

![image](https://user-images.githubusercontent.com/14036783/46856258-dd402f00-ce40-11e8-8611-231f5c54493e.png)

I can provide more details, but I cannot know what help you.
Please tell me that.

Best regards!

### Cannot work debug mode

(18/10/12 17:13)
I had try restart and use add-on's debug mode.
But, it cannot work and shut down in just time.
I had fail to get log.

**Comment by AtsushiYamashita** [comment] 2018-10-12 08:15
Update in title field
About **Append/Cannot work debug mode**

**Comment by egamma** [comment] 2018-10-12 13:31
Duplicate of #60318

**Closed by egamma** 2018-10-12 13:31 UTC
