### ISSUE TITLE
Hover is weirdly wrapped

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#69835] opened 2019-03-05 10:44 UTC
Issue Type: <b>Bug</b>

![demo](https://user-images.githubusercontent.com/9638156/53799977-c4016180-3f4c-11e9-883d-61344b13e1fd.gif)

VS Code version: Code - Insiders 1.32.0-insider (c23e8995f6e31b3540e0a2c3d4fdc58e6d7cba53, 2019-03-04T17:23:10.903Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment] 2019-03-05 10:57
Hope that hard wrapping is done via CSS. I have custom width for hover and this restriction looks really bad.

**Comment by adamtajti** [comment] 2019-03-05 13:07
I think that PR #69845 should fix that:

![9f07ec12-db23-43f5-a435-35b3a4d1b40c](https://user-images.githubusercontent.com/1270407/53806188-95838680-3f4c-11e9-9f79-f9e279446dd2.gif)

**Comment by sandy081** [comment] 2019-03-06 08:34
@usernamehw @adamtajti This `maxWidth` change is intentional so that Docs are wrapped always for readability purpose. See https://github.com/Microsoft/vscode/issues/69388

I am ok to remove that and let all hovers take the same width.

@Tyriar FYI

**Comment by usernamehw** [comment] 2019-03-06 11:11
Maybe you can put it to a vote (inside vscode team or on twitter). 

I like bigger hover and have it almost the same width in Stable with Custom CSS.

**Comment by adamtajti** [comment] 2019-03-06 12:11
So if we decide to remove it, then this part will need to be modified as well (as there'll be no need to differeniate on `code-hover-contents`):

```typescript
markdownDisposeables.push(renderer.onDidRenderCodeBlock(() => {
  hoverContentsElement.className = 'hover-contents code-hover-contents';
  this.onContentsChange();
}));
```

Now that I've followed up on that issue that @sandy081 linked I'm starting to think that deciding on the automatic wrapping / horizontal width of this hover will remain an issue that'll be brought up again and again. 

Community seems to recommend the followings:
- Resizable hover #29126 #14165
- Scrollbars #29126

I think it might also be wortwhile to persue this:
- Wraps that can be easily switched on / off. I believe the default should be off. When it's on, scrollbars shouldn't be visible.

If we agree that those features would solve this matter then it would be best to persue those and close this and future issues with similiar themes like this. Maybe some of these settings could be overridden on the hover itself (for example a small bar at the bottom of the hover that would have a switch for wrapping)

Otherwise, we still need to decide on this issue. I would vote / prefer to have a non-wrapping wide hover.

**Comment by Gama11** [comment] 2019-03-06 12:16
To me the main issue is the discrepancy between the width of the docs and the code block above it - it looks quite strange if they're inconsistent. That being said, I also agree that docs being too wide hurts readability.

**Comment by adamtajti** [comment] 2019-03-06 22:27
Agreed @Gama11, that's strange. I spent some time to read up more on the subject and for readability purposes character per line should be around 70 for desktop. I think it's still readable at 80 and that's pretty close to the original advice of how long a line of code should length.

![image](https://user-images.githubusercontent.com/1270407/53916387-665f3900-4062-11e9-8784-d01c899043e9.png)

The actual code to calculate the max-width of the hover is defined in the `hoverWidgets.ts`. I have changed it locally to display 80 "characters".

```typescript
this._domNode.style.maxWidth = '80ch';
```

Since this is a `maxWidth`, short descriptions are still short in length as well

![image](https://user-images.githubusercontent.com/1270407/53917899-e9ce5980-4065-11e9-83a0-22df47eee7db.png)

I think it doesn't make much sense to display a tooltip any smaller than this. Maybe this size will work for everyone until we add further functionalities to customize the hovers. I can update the PR if you like this more.

**Comment by tamuratak** [comment] 2019-03-06 23:40
The extension [LaTex Workshop](https://github.com/James-Yu/LaTeX-Workshop) needs a larger max-width to display math preview on hover appropriately.  The larger is the better. `500px` or `80ch` is still small for this purpose.

![2019-03-07 8 32 25](https://user-images.githubusercontent.com/10665499/53921523-11e4a980-40b4-11e9-897b-d32224877c27.png)

**Comment by sandy081** [comment] 2019-03-07 08:37
@adamtajti If we fix max width for all hovers to 80ch to make doc hover to look good, then other hovers (problems, type def) get wrapped and does not look good. Current solution is the middle ground that wraps docs at width of 500px and others take more width that is available in the editor. 

Regarding inconsistent widths, I think this cannot be avoided because there could be a multiline problem hover that can cause this.

**Comment by adamtajti** [comment] 2019-03-07 20:23
@tamuratak: Thanks for the feedback. I'm rather new to the VS Code codebase thus I'll need some time to understand how extensions are managed, but I'll look into this project.

@sandy081: I'm not sure whatever it can't be avoided. Setting the same max-width on the hover title and content based on whatever it's a doc hover or something else seems to be achievable. I'll keep thinking about this on the weekend.

**Comment by Tyriar** [comment] 2019-03-07 20:29
Can we wrap the docs only to 80ch?

**Comment by sandy081** [comment] 2019-03-11 08:35
@Tyriar It is right now. Doc hover width is 500px and gets wrapped always.

**Comment by sandy081** [comment] 2019-03-20 12:33
As this is purposeful #69388 that documentation should be wrapped at shorter lines, closing this as designed.

**Closed by sandy081** 2019-03-20 12:33 UTC
Labels: editor-hover, under-discussion
