### ISSUE TITLE
Terminal not auto-focusing on first open.

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#43852] opened 2018-02-16 18:49 UTC
### Issue Type
Bug

### Description

After the latest update, VS Code no longer auto-focuses the terminal when opening it (specifically via shortcut.)

In the gif below I've opened a new window, open the terminal and begin to type. Notice the terminal is not in focus and writes my command into the new file window. I then close and open the terminal and it focuses as normal.

![vscode_cmd](https://user-images.githubusercontent.com/2420177/36323755-a4477e04-1317-11e8-845d-9e50148f73ea.gif)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|15.94GB (1.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.27
python|ms-|2018.1.0
vscode-icons|rob|7.19.0

</details>
Reproduces without extensions

**Comment by usernamehw** [comment] 2018-02-16 19:16
Duplicate of #40416

**Comment by egamma** [comment] 2018-02-18 14:50
@usernamehw thanks for your support!

**Closed** 2018-02-18 14:50 UTC
Labels: *duplicate
