### ISSUE TITLE
html file saving continuosly

### ISSUE THREAD

**Issue by integrys-net** [Microsoft/vscode#16397] opened 2016-12-02 17:45 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 7

Steps to Reproduce:

1. Open html file, with html extension and edit
2. Save
With my installation i've seen when i edit an html file and save it, the save process never stop, as something get be edited and then saved

**Comment by mrmlnc** [comment] 2016-12-02 17:47
Could you list your extensions? `code --list-extensions` will show them.

**Comment by integrys-net** [comment] 2016-12-02 17:57
adambaldwin.vscode-nsp
anseki.vscode-color
brpaz.file-templates
christian-kohler.npm-intellisense
chrmarti.regex
EditorConfig.EditorConfig
fknop.vscode-npm
gerane.Theme-Solarized-dark
gerane.Theme-Solarized-light
GrapeCity.gc-excelviewer
gyuha.format-on-save
humy2833.ftp-simple
HvyIndustries.crane
ianhoney.task-master
imperez.smarty
Perkovec.require-sort
siegebell.incremental-search
sysoev.language-stylus
tanato.vscode-gulp
zgudino.editorconfig-vscode-snippet

After disabling some of the extension i've found the
'''gyuha.format-on-save
broke save process.

**Comment by integrys-net** [comment] 2016-12-02 18:21
I think that thread can be closed.

**Comment by mjbvz** [comment] 2016-12-02 19:25
Closing since it looks like an extension was the root cause. @integrys-net If you have not already done so, please report this bug to the extension author so they can fix it.

Thanks.

**Closed by mjbvz** 2016-12-02 19:25 UTC
