### ISSUE TITLE
YOU DELETED ALL MY WORK

### ISSUE THREAD

**Issue by haydoncurteislateo** [microsoft/vscode#76886] opened 2019-07-08 14:19 UTC
Issue Type: <b>Bug</b>

I was working in Visual Studio Code when I noticed that my extensions were not running, so I closed VSC with the intent on re opening it, once I re opened it I opened the file I was working on to find that it is completely blank there is nothing left IT IS ALL GONE MONTHS OF WORK HAS JUST BEEN LOST I DID NOT HIT ANY DELETE KEYS OR BACKSPACE NOTHING, VISUAL STUDIO CODE JUST DELETED ALL OF IT!!!!

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.1.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
smali|cra|1.0.1
vscode-svgviewer|css|2.0.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.2
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
comment-anchors|Exo|1.6.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.1.0
vscode-firefox-debug|hbe|1.8.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-map-preview|jum|0.4.8
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.11.6
vuejs-extension-pack|mub|1.1.3
color-highlight|nau|2.3.0
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.0
heroku-command|pko|0.0.8
java|red|0.46.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.3.1
vscode-hexdump|sle|1.7.2
vscode-status-bar-format-toggle|tom|1.5.0
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
vscode-icons|vsc|8.8.0
intelligence-change-case|zhe|1.1.0
html-css-class-completion|Zig|1.19.0

(7 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2019-07-08 15:03
@haydoncurteislateo sorry to hear that. To be clear, you worked on one file over several months and suddenly that file turned up empty when you opened VSCode? Was that file stored in a specific place?

**Comment by ChronosX88** [comment] 2019-07-08 15:14
<sarcasm>Git? No, didn't hear.</sarcasm>

**Comment by Ghostium** [comment] 2019-07-08 16:33
I understand your frustration that your code is lost, but please understand that a lot of other factors besides VSCode, like hard disk failure, can impact your work. Working on a single file for months without creating any copies is very risky as you have experienced yourself.

You have demonstrated with your other projects on Github that you interact with Git for some time now. The VSCode maintainers are not at fault for loosing months of work if you don't check in your work especially because you used Git before.

I believe screaming in full caps at the VSCode maintainers and volunteers is the wrong way and really rude. Please remember that you can download and use this awesome editor for free as in beer or for free as in freedom if you compile it from source yourself.

Anyways, maybe you created an accidental copy, have you deployed your code somewhere?

**Comment by haydoncurteislateo** [comment] 2019-07-08 18:39
After some time of grief I've cleared my mind, I do apologise for my behaviour, I did not use Git for this project because it contained contents that I did not think were suitable for general people to access I now fully understand that was stupid and am enormously regretting it, I have since made a repository for this project. I do now know that other variables were possibly at play here and that it can not be Visual Studio Codes sole fault, It could be that the file became corrupt at some other point and I just happened to notice when I opened it up after closing and re-opening VSC. I hugely appreciate the work you guys do and this amazing software, I have been a huge recommender of it and will continue to. I do apologise again and have decided that I will just have to rewrite some of the work that I have done in the hopes that I can write it better and learn a lesson from this. Sorry.

**Comment by Ghostium** [comment] 2019-07-08 19:05
To clarify with other factors I meant not that something other than VSCode caused this error, I only tried to highlight that data loss in the way you experienced can happen even without a VSCode malfunction. 

If you are spending a good chunk of your lifetime for personal or professional projects, creating backups or regularly checking code into Git is important and worth it.

> I did not think were suitable for general people to access

https://help.github.com/en/articles/setting-repository-visibility#making-a-repository-private

Also, if the collaborator limit is a deal breaker for you it is surprisingly easy to [setup your own private repository (ca. 10 min.)](https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server) on your own server as well. If you go down this route don't forget cron jobs for backups ;D

**Comment by bpasero** [comment] 2019-07-09 05:17
After reading through the comments, I do not see clear steps that we could use to identify the origin of this issue, therefor I will close it. If someone has ideas how this could have happened and possibly some steps to reproduce, please comment and we can revisit this.

**Closed by bpasero** 2019-07-09 05:17 UTC
Labels: needs more info
