### ISSUE TITLE
[Bug] CMD+C doesn't work on Extension page

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#73325] opened 2019-05-06 08:13 UTC
Issue Type: <b>Bug</b>

When I open an extension page (readme of the extension), there are usually some instructions how to setup/install some additional stuff needed for extension to work. I can select the text, and I can go to "Edit" => "Copy" from the menu bar, but I can't copy text by pressing "CMD+C" key combination. "CMD+C" works fine in other editor windows.

I also tried with `code --disable-extensions`, but I'm still having the same issue.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.19.6
vscode-eslint|dba|1.8.2
gitlens|eam|9.7.0
rails-snippets|Hri|1.0.8
ruby-rubocop|mis|0.8.0
sublime-keybindings|ms-|4.0.0
ruby|reb|0.22.3

</details>

**Comment by mjbvz** [comment] 2019-05-07 22:50
Duplicate of #69315

**Closed by mjbvz** 2019-05-07 22:50 UTC
Labels: webview
