### ISSUE TITLE
Hover is always selected

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121401] opened 2021-04-15 18:05 UTC
Don't ask me how I got into this state, but my hover always shows its contents fully selected. We should make sure the entire hover is non selectable.

![image](https://user-images.githubusercontent.com/22350/114916839-91154180-9e25-11eb-8d39-989c691a1051.png)

**Comment by sandy081** [comment] 2021-04-16 09:52
@Tyriar Is this has to be fixed in hover?

**Comment by Tyriar** [comment] 2021-04-16 10:35
The hover is selectable by design so users can copy the text.

**Comment by joaomoreno** [comment] 2021-04-19 08:22
Then make sure selection is cleared when the hover appears.

**Comment by Tyriar** [comment] 2021-04-19 08:46
The element get reconstructed so that should already be happening when you hover another element. Did you perhaps have the entire document selected or something, I'd be hesitant to touch the selection unless it was definitely only contained within the hover.

**Comment by joaomoreno** [comment] 2021-04-19 08:55
I haven't been able to repro since. I don't know how I did it.

**Comment by Tyriar** [comment] 2021-04-21 13:03
Closing since it's an edge case without a clear fix

**Closed by Tyriar** 2021-04-21 13:03 UTC
Labels: under-discussion
