### ISSUE TITLE
Polish - target rendering of the folder in the debug drop down 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31531] opened 2017-07-27 09:12 UTC
Testing #31396

Currently the folder of a target is shown in parenthesis which looks noisy:

![image](https://user-images.githubusercontent.com/172399/28662889-f561ee2a-72bb-11e7-849e-f6432530cbe1.png)

Suggestions:
- dim the folder and show it in a darker grey so that no parenthesis is needed
- replace the parenthesis with a '-',  Attach - tslint-server

**Comment by isidorn** [comment] 2017-07-27 09:33
Option 1 is not possible atm since we are using a native HTML select box which does not give me an option to customly render options.
So will try option 2.

**Comment by michelkaporin** [comment] 2017-07-27 10:34
Option 2 seems also very noisy. Right in the example of 'Attach - tslint-server' there are two hyphens which makes it more difficult to read. I would rather stay with parentheses as it is now, if there is no option to style it at the moment.

**Comment by isidorn** [comment] 2017-07-27 12:12
We also use the paranthesis when showing workspace name everywhere   test (workspace). So it might be better to align with that and just stay with perenthesis for now.
Will decide once I try out the - and see how it looks

**Comment by isidorn** [comment] 2017-07-27 14:42
Once trying it out I prefer how the parenthesis look
![screen shot 2017-07-27 at 16 41 59](https://user-images.githubusercontent.com/1926584/28676279-8c00e25e-72ea-11e7-9881-d05dbbb94682.png)

Closing as designed and we can improve here if we decide to go with the custom rendering of the debug dropdown

**Closed by isidorn** 2017-07-27 14:42 UTC
Labels: debug, polish
