### ISSUE TITLE
Auto-import not working for extra node modules with expo project

### ISSUE THREAD

**Issue by soullivaneuh** [microsoft/vscode#94920] opened 2020-04-10 15:31 UTC
- VSCode Version:1.43.2
- OS Version: 5.4.30-1-MANJARO

Steps to Reproduce:

1. Clone the branch `learn-expo` of this project: https://gitlab.com/soullivaneuh/react-native-sandbox/-/tree/learn-expo (it's a fresh expo TS project with some views)
2. Open `App.tsx`
3. Remove the line: `import { Icon } from 'react-native-elements'`
4. Try `Ctrl+space` at the end of the `<Icon` tag. No correct import proposed.

Please note that auto-import from `react-native` package works, but none of the others.

Does this issue occur when all extensions are disabled?: Yes

**Comment by soullivaneuh** [comment] 2020-04-11 14:43
Looks like it's working for interface extends completion:

![image](https://user-images.githubusercontent.com/1698357/79046865-9688ec00-7c13-11ea-821a-58157bccc553.png)

But not for component usage on templates.

**Comment by soullivaneuh** [comment] 2020-04-11 16:43
Well, sometimes the completion auto-import works, sometimes not.

I didn't change anything on the settings, that's weird.

Please give me instructions to do so I can help debugging this issue.

**Comment by mjbvz** [comment] 2020-04-13 21:45
Thanks for the example. This looks like a duplicate of #37812 to me

**Closed by mjbvz** 2020-04-13 21:45 UTC
