### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5026] opened 2016-04-06 09:21 UTC
Issue Id: <b>551dfb3c-f0e8-36c7-5863-9ee08211218f</b><br /><br />*Versions* <br />- 0.10.14-insider<br />-  43ff6af3d4564f59196caa9be4897fc33c15f24c<br />*Stack* <br />TypeError: Cannot read property 'length' of undefined<br />[/vs/base/common/filters.ts#L64:24 (length)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/filters.ts#L64:24 (length))<br />[/vs/base/common/filters.ts#L61:101 (_matchesPrefix)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/filters.ts#L61:101 (_matchesPrefix))<br />[/vs/base/common/filters.ts#L30:25 (word)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/filters.ts#L30:25 (word))<br />[/vs/base/common/filters.ts#L272:90 (fuzzyContiguousFilter)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/common/filters.ts#L272:90 (fuzzyContiguousFilter))<br />[/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L410:20 (matchesFuzzy)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L410:20 (matchesFuzzy))<br />    at Array.forEach (native)<br />[/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L407:15 (forEach)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L407:15 (forEach))<br />[/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L308:17 (onType)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L308:17 (onType))<br />[/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L175:10 (onType)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L175:10 (onType))<br />[/vs/base/browser/dom.ts#L196:3 (handler)](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/src/vs/base/browser/dom.ts#L196:3 (handler))<br />

**Comment by bpasero** [comment] 2016-04-07 07:39
Dupe of https://github.com/Microsoft/vscode/issues/4809

**Closed by bpasero** 2016-04-07 07:39 UTC
Labels: error-telemetry
