### ISSUE TITLE
Usability: NVDA is not reciting the name for the options and extensions available in the extensions side bar area.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/vscode#17242] opened 2016-12-15 05:58 UTC
VS Code Version: 1.6.1
OS Version:1607
NVDA version:-2016.2.1

**Steps to Reproduce:**
Prerequisite: Node.js and git repository need to be installed.
1.Open visual studio code.
2.Using "Ctrl+ Shift+ X", key navigate to the  "Extensions" side bar areas.
3.Using "Tab", key navigate to the "More", "Search fields" and available extensions present in the side bar areas.

Expected result:
NVDA should recite the name for the options "More", "Search fields" and available extensions present in the side bar areas.

Actual Result:
NVDA is not reciting anything for the options and extensions available in the sidebar area.
Note:-Inconsistent NVDA behavior is observed sometimes

User Impact:
Screen Reader user doesn't get to know the purpose of the control as it's not getting announced.

Attachments:
![inspectinformation_visualstudiocodeeditor_extensionsidebar](https://cloud.githubusercontent.com/assets/22956130/21213325/8ee5066c-c2b9-11e6-900d-a5249d3cee16.jpg)
![nvda_speechviewerinformation_vscodeeditor_extensionsidebar](https://cloud.githubusercontent.com/assets/22956130/21213323/8ee24800-c2b9-11e6-8e14-4aa114fb5bd5.jpg)

**Comment by joaomoreno** [comment] 2017-01-04 15:03
Dupe of #17113

**Closed by joaomoreno** 2017-01-04 15:03 UTC
Labels: accessibility

**Comment by WiproPSAccTest** [comment] 2017-01-18 05:16
@joaomoreno  The issue is fixed in vs code editor 1.8.1

**Comment by joaomoreno** [comment] 2017-01-18 08:31
Thanks for verifying!
