### ISSUE TITLE
Cannot use incremental search in Command Pallet.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#4696] opened 2016-03-27 16:19 UTC
- VSCode Version:
  - 0.10.12-insider
  - Commit: ef2a1fcaa553d14d7731b284a5ac5e4a55c42936
  - Date: 2016-03-21T11:33:38.240Z
  - Shell: 0.35.6
  - Renderer: 45.0.2454.85
  - Node: 4.1.1
- OS Version:
  - Windows 7 64bit

Steps to Reproduce:

1. Use Command Pallet in Japanese

![command-pallet-i18n](https://cloud.githubusercontent.com/assets/1937871/14066294/c4e20786-f480-11e5-852c-4a46e97ff853.gif)

I cannot use commands in English.
Japanese IME inputs text as hiragana at first. Then we push the space key, then the text is converted to a combination of hiragana, katakana, and kanji.
This is meaning we cannot use incremental search efficiently.

This is very inconvenient.

Can I turn i18n off?

**Comment by Tyriar** [comment] 2016-03-28 19:54
Duplicate of https://github.com/Microsoft/vscode/issues/4696

You can go back to the English version by switching to `en-us` via the command palette's "Configure locale".

**Closed by Tyriar** 2016-03-28 19:54 UTC

**Comment by mysticatea** [comment] 2016-03-29 18:27
Thank you.

#4696 is this issue. Just link to #4691.
I'm sorry, I hadn't found this in known issues since I mistyped "pallet".

Just information for people which are looking at this issue: 

- "Configure locale" in v0.10.12-insiders but it was changed to "ロケールの構成" in v0.10.13-insiders.

**Comment by mysticatea** [comment] 2016-03-31 07:15
Also, link to #4679.
