### ISSUE TITLE
Makefile recognized as incorrect file type (shell/docker)

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#132005] opened 2021-08-31 19:13 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0-insider
Commit: 44a4b19a910a287adef4daaeabcf68f2ba893c35
Date: 2021-08-30T11:36:29.726Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:
Using a `Makefile` (eg no file type extension), the file is sometimes not recognized as the Makefile type, but also sometimes  `docker` or `shell.sh` files.

After hours of playing around, I think it *might* have something to do with the percentage of lines in the file which could be recognized as another file type (eg .sh file).

Manually specifying a file association also does not work, eg
```json
    "files.associations": {
        "Makefile": "makefile"
    },
```

I can force vscode to recognize it as a makefile by adding enough "dummy" lines which aren't recognized as different file types (see last image).

I'm not 100% sure what is going on exactly, but here's some screenshots of what I mean:

To test it out, this code gets recognized as a docker file:
```makefile
SHELL := /bin/bash
utils := @poetry run python -m scripts.utils
code := jambot tests working az_*

.PHONY : format
format:  ## autopep, isort, flake
	@poetry run autopep8 --recursive --in-place $(code)
	@poetry run isort $(code)
	@poetry run flake8 $(code)

.PHONY : app
app:  ## push jambot app to azure
	@func azure functionapp publish jambot-app --build-native-deps

.PHONY : run-app-local
run-app-local:  ## run app for local testing
	@poetry run func host start

.PHONY : testfunc
testfunc:  ## Test trigger azure function running on localhost
	@curl --request POST -H "Content-Type:application/json" --data '{"input":""}' http://localhost:7071/admin/functions/az_RetrainModel

.PHONY : reqs
reqs:  ## make requirements.txt for function app
	@poetry export -f requirements.txt --output requirements.txt --without-hashes

.PHONY : test
test:  ## run tests
	@poetry run pytest

.PHONY : creds
creds:  ## re-encrypt credentials
	$(utils) --encrypt_creds

.PHONY : codecount
codecount:  ## show lines of code
    @pygount --suffix=py --format=summary jambot

help: ## show this help message
	@## https://gist.github.com/prwhite/8168133#gistcomment-1716694
	@echo -e "$$(grep -hE '^\S+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##\s*/:/' -e 's/^\(.\+\):\(.*\)/\\x1b[36m\1\\x1b[m:\2/' | column -c2 -t -s :)" | sort
```

Examples:

docker:
<img width="1095" alt="docker" src="https://user-images.githubusercontent.com/29611875/131561213-96157c7e-7a48-4359-b9ee-3e0ad9303cd8.png">

shell (just added extra comment lines):
<img width="1130" alt="shell" src="https://user-images.githubusercontent.com/29611875/131561219-9456d626-e152-45a9-b045-0db63ff060ac.png">

makefile (added dummy lines to force back to makefile):
<img width="1109" alt="makefile" src="https://user-images.githubusercontent.com/29611875/131561223-c010d2a8-d61e-4d10-b595-5719f546138e.png">

**Comment by TylerLeonhardt** [comment] 2021-09-03 22:17
Duplicate of #132173 this will be fixed in the next recovery build next week. In the meantime you can do:

```
"[makefile]": {
        "workbench.editor.languageDetection": false
},
```

**Closed by TylerLeonhardt** 2021-09-03 22:18 UTC
Labels: bug, languages-guessing
