### ISSUE TITLE
VSCode 1.12.1 standard c# snippets quit working after update

### ISSUE THREAD

**Issue by klmcwhirter** [Microsoft/vscode#26623] opened 2017-05-14 18:52 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|EditorConfig|EditorConfig|0.9.3|
|beautify|HookyQR|1.0.2|
|markdown-checkbox|PKief|1.0.2|
|vscode-docker|PeterJausovec|0.0.14|
|html-snippets|abusaidm|0.1.0|
|git-easy|bibhasdn|1.9.1|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|rest-client|humao|0.14.3|
|csharpextensions|jchannon|1.3.0|
|Angular2|johnpapa|2.2.3|
|Go|lukehoban|0.6.61|
|markdown-shortcuts|mdickin|0.8.1|
|vscode-todo-parser|minhthai|1.8.10|
|mssql|ms-mssql|1.0.0|
|**csharp**|**ms-vscode**|**1.9.0**|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.7.0|
|yo|samverschueren|0.9.3|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Open .cs file containing a C# class
2. Notice other features of the extension are functioning: Syntax Highlighting, IntelliSense, Go to Definition, Find All References, .NET Core Attach debugging, etc.
3. The extension is installed (see list above) in ~/.vscode/extensions/ms-vscode.csharp-1.9.0/
4. The snippets file exists in the snippets sub-dir as csharp.json
5. Common snippets like "prop", "namespace", etc. simply do not appear.
6. Note the "class" snippet does show up in the intellisense list but produces bad output:
```
    class Name
    {
    
    ,
    }|<== the cursor is left here after specifying the class name and hitting return
```
7. "foreach" snippet does the same thing:
```
            foreach (var item in collection)
            {
            
            ,
            }|<== the cursor is left here after specifying var, item and collection and hitting return
```
8. Command-Shift-p and "Insert Snippet" shows the snippets that will show up in context; all of the ones I tried from the list had the same formatting issues.
9. Here is what I see from csharp.json for the "class" snippet.
```
        "Class": {

                "prefix": "class",
                "body": [
                        "class ${Name}",
                        "{",
                        "       $0",
                        "}"
                ],
                "description": "Class"
        },
```
Given this I suspect there are some syntax errors in this file. But see below - it appears that is not the whole story.

_Note I did try to re-compile the extension in hopes that the json file would be regenerated somehow. But after npm i and doing npm run compile I got an error about missing tsconfig.json file and then also noticed there was no source delivered with the extension. So I stopped there._

Note the csharp.json file had not changed since Oct 2016 - there were 2 commits recently:
[csharp.json commmits](https://github.com/OmniSharp/omnisharp-vscode/commits/master/snippets/csharp.json)

There are several issues opened in the OmniSharp repo - [#1459](https://github.com/OmniSharp/omnisharp-vscode/issues/1459) is just one. So treat this as an FYI.

However they do reference [MS VSCode #26101](https://github.com/Microsoft/vscode/issues/26101) as part of the problem.

The [OmniSharp VSCode #1464](https://github.com/OmniSharp/omnisharp-vscode/issues/1464) issue was closed on May 8 by Dustin Campbell with a reference to MS #26101.

I am hoping you and the OmniSharp folks can fix this soon. It is impactful to snippets across all extensions.

**Comment by Kampfmoehre** [comment] 2017-05-15 05:55
I have the same issue and also all snippets after "iterindex" are missing from the snippet list. For instance the "prop" snippet for auto properties is missing in the list and vscode also doesn't recognise it when I'm typing it. 
If I copy the snippets from https://github.com/OmniSharp/omnisharp-vscode/blob/master/snippets/csharp.json into my own C# snippet file, they are back in the list and also working properly.
Maybe this is a problem with the C# Extension?

**Comment by egamma** [comment] 2017-05-15 07:49
Duplicate of #25938, fix will be in the recovery build we do this week.

**Closed by egamma** 2017-05-15 07:49 UTC
Labels: duplicate
