### ISSUE TITLE
Large JSON formatting adds '}' at the end of file.

### ISSUE THREAD

**Issue by abgrac** [microsoft/vscode#92394] opened 2020-03-10 18:46 UTC
Hello,

I've already checked with other formatters online and my JSON apparently is fine. All of them formats the file normally. VSCode somehow adds a single } at the end of file, as seem here:

* Before:
`{"uid":43,"suspects":112,"refuses":75},{"uid":50,"suspects":6,"refuses":11},{"uid":51,"suspects":5,"refuses":2},{"uid":52,"suspects":14,"refuses":14},{"uid":53,"suspects":41,"cases":1,"refuses":24}]}]}`
![2020-03-10 15_37_56-coronaBR json - Visual Studio Code](https://user-images.githubusercontent.com/7785230/76347936-30dcd380-62e6-11ea-93b5-31e97b91580c.png)

* After:
`{
          "uid": 53,
          "suspects": 41,
          "cases": 1,
          "refuses": 24
        }
      ]
    }
  ]
}}`
![2020-03-10 15_38_08-● coronaBR json - Visual Studio Code](https://user-images.githubusercontent.com/7785230/76347992-4520d080-62e6-11ea-9dc5-f2321869acf9.png)

The file is RFC 8259 conformant.

Do any of you guys know why it's happening?

Thanks in advance.

**Comment by nrayburn-tech** [comment] 2020-03-10 19:40
According to this, https://github.com/microsoft/vscode/issues/91125#issuecomment-595657468, it should be fixed in the most recent stable version.

**Comment by aeschli** [comment] 2020-03-11 12:59
Can you confirm you are seeing this in 1.42? It's fixed in 1.43

duplicate of #91125

**Closed by aeschli** 2020-03-11 12:59 UTC
