### ISSUE TITLE
vscode.OutputChannel.clear() invalid & leads to memory leakage

### ISSUE THREAD

**Issue by soma-liang** [microsoft/vscode#205466] opened 2024-02-18 09:56 UTC
Type: <b>Bug</b>

prart of #200015
1.download extension https://github.com/soma-liang/demo-cache.git
2.Run command StartTest
3.When you see the output, the current time is refreshed every 10 ms. After 10 seconds, call vscode.OutputChannel. clear(), continue refreshing and keep looping
4.Calling script "
#!/bin/bash

echo "30256,30294,30326,30344" >> mem_log.txt

while true

do

   ps -p 30256,30294,30326,30344 -o pid,rss,%cpu | tail -n +2 | tr '\n' ' ' >> mem_log.txt

   echo "" >> mem_log.txt

   sleep 1

done
" to record the memory changes corresponding to vscode
5.Run command EndTest after 5 hours
6.Observing the time displayed in the output, it was found that the displayed content contains more than 10 seconds of data, as well as data that needs to be cleared previously. And observing the log files, it was found that the memory was also growing rapidly

add result img
![image](https://github.com/microsoft/vscode/assets/84301995/73e504c3-2ff3-44d8-bb7d-e012e8c0da7d)
![image](https://github.com/microsoft/vscode/assets/84301995/43d27f45-6f99-4ac9-95eb-495556942517)

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 5.15.0-92-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (8 x 2599)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.61GB (11.82GB free)|
|Process Argv|--crash-reporter-id 46ebf934-2368-4df7-b9e4-a6fde6010a9f|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.8.2
demo-cache|mic|0.0.5
cpptools|ms-|1.18.5
postman-for-vscode|Pos|0.18.0
vscode-counter|uct|3.4.0
wavetrace|wav|1.1.2
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
pydisww1:30959800
3ef8e399:30964150
e3gdj431:30958358
ccp2r6:30958158

```

</details>

```[tasklist]
### Tasks
```

**Comment by sandy081** [comment] 2024-02-21 20:07
I have ran following for 4 hours and the output seems to be behaving correctly.

```ts
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
  const channel = vscode.window.createOutputChannel('test');
  context.subscriptions.push(vscode.commands.registerCommand('test.helloWorld', () => {
    channel.show();
    let i = 0
    const timerOut = setInterval(() => {
      i++
      channel.appendLine(new Date().toISOString())
      if (i > 1000) {
        channel.clear()
        i = 0
      }
    }, 10)
  }))
}
```

Am I missing anything?

**Comment by soma-liang** [comment] 2024-02-28 06:43
There is no problem with your code, and running it according to your code may also result in output not displaying
Please run for more than 10 hours to observe
![image](https://github.com/microsoft/vscode/assets/84301995/145b4611-2d2c-466f-9f5c-84b880bf194d)

**Comment by soma-liang** [comment] 2024-02-29 00:55
If the program is not closed and runs continuously, there will be an error message of insufficient memory
![image](https://github.com/microsoft/vscode/assets/84301995/5dc3eaa8-acfc-4028-a8c5-876ea91b1ac5)

**Comment by sandy081** [comment] 2024-03-04 12:54
> Please run for more than 10 hours to observe

Unfortunately this is not practical to reproduce and fix. Sorry that I would close it as wont fix

**Closed by sandy081** 2024-03-04 12:54 UTC
Labels: info-needed

**Comment by soma-liang** [comment] 2024-03-11 07:58
@sandy081 I now have an application scenario where I forget to constantly add data to the output, but the frequency is not as fast, but it takes a long time for testing. This issue was discovered during the testing process. Please take a look at this issue

**Comment by sandy081** [comment] 2024-03-11 15:53
Sure, since I cannot reproduce it, Can you please help us in capturing the JS heap profiles showing the memory leaks?
