### ISSUE TITLE
Problem Sending Code to F# Interactive

### ISSUE THREAD

**Issue by bytos** [Microsoft/vscode#19556] opened 2017-01-29 02:26 UTC
When I press Alt+Enter to send selected F# code to F# Interactive terminal, a "Microsoft Visual C++ Runtime Library" dialog window appears.

The window has a disabled close button and have to terminate it in Task Manager. The window also has a white frame.

I can run Fsi.exe from the command prompt (system path) and these are my settings:

    "FSharp.toolsDirPath": "C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0",
    "FSharp.fsiFilePath": "C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0/Fsi.exe",

![s](https://cloud.githubusercontent.com/assets/16452541/22401403/2c9e8796-e5a8-11e6-9627-22d5ffa3f132.png)

- VSCode Version: 1.8.1
- OS Version: Windows 8.1
- Extension: Ionide 2.21.1

**Comment by mousetraps** [comment] 2017-01-30 02:25
@bytos, thanks for reporting! Closing, as the issue is caused by an extension, and looks like you've already found the perfect repo for it! https://github.com/ionide/ionide-vscode-fsharp/issues/348

Happy coding!

**Closed by mousetraps** 2017-01-30 02:25 UTC
