### ISSUE TITLE
PR view shows a weird blue button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#174706] opened 2023-02-17 18:47 UTC
<img width="468" alt="image" src="https://user-images.githubusercontent.com/900690/219758307-a5d1bbd9-f10f-4333-91e2-0a14fda454d2.png">

Seeing it since a few days, has bad contrast.

**Comment by alexr00** [comment] 2023-02-20 16:15
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4502

**Closed by alexr00** 2023-02-20 16:15 UTC
