### ISSUE TITLE
Outline, breadcrumbs, and Sticky Scroll and doesn't follow HTML's implicit tag closing rules.

### ISSUE THREAD

**Issue by ARitz-Cracker** [microsoft/vscode#211671] opened 2024-04-29 22:29 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Ubuntu 22.04.4 LTS

We all now know that [XML-style self-closing tags are a lie](https://jakearchibald.com/2023/against-self-closing-tags-in-html/), and that it is in fact potentially harmful to think of HTML as a subset of XML.

VSCode seemingly doesn't consider this, or rather, it doesn't respect HTML's tag omission rules or the fact that elements implicitly close when an ostensibly inner-element is of a type which cannot be a child of a parent type. For example, a `<footer>` cannot be a child of an `<p>`, so the `<p>` implicitly closes when the `<footer>` is encountered. `<p>` should also be implicitly closed when encountering another `<p>`. Similar rules apply to `<li>`, which implicitly closes when encountering another `<li>` that isn't grandchild via a `<ul>`, `<ol>`, or `<menu>` element.

The following is a 100% valid HTML, showing a valid list with a sublist containing a valid paragraph. [Paste it in here if you don't believe me](https://validator.w3.org/#validate_by_input).

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Eyy</title>
	</head>
	<body>
		<ul>
			<li>Look at this list!
			<li>Wooaaah!
			<li>The tags look like bullet points!
			  <ul>
				  <li>
					<p>
					Now there's a sub-list with double-spacing
					<p>
					It's like a &lt;br&gt; except double spaced!
				  <li>
					<p>
					When will this madness end?!
			  </ul>
			<li>Everything I assumed about the world was a lie!
		  </ul>
		  
	</body>
</html>
```

Steps to Reproduce:

1. File -> New Text File
2. Select HTML as the language
3. Write a bunch of lines containing only the string `<p>AAAAAAAAAAAA` -or- Make a really long `<ul>` which have `<li>` elements, but with no closing tag.
4. Notice how your `<p>` or `<li>` elements take up the max amount of lines in the sticky scroll even though they shouldn't, and how breadcrumbs and outline goes all `p > p > p > …` or `li > li > li > …`

I understand that this may be due to the fact that VSCode, in general, doesn't really have an HTML parser and is primarily relying on XML-style syntax when encountering anything beyond void elements, like `<br>` and `<img>`, and there can also be arguments as to whether or not relying on HTML's tag omission rules is "best practice". That said, also believe that when it encounters a syntactically valid HTML file, it should be have as expected by the standard.

**Comment by aeschli** [comment] 2024-05-02 14:46
duplicate of https://github.com/microsoft/vscode-html-languageservice/issues/63

**Closed by aeschli** 2024-05-02 14:46 UTC

**Comment by ARitz-Cracker** [comment] 2024-05-02 14:47
Ah, I searched before but nothing seemed to come up, apologies for the duplicate issue!
