### ISSUE TITLE
Support locking hover position in editors

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#159384] opened 2022-08-28 03:19 UTC
https://github.com/microsoft/vscode/issues/115034 added support for using `alt` to lock the hover in place to make it much easier to mouse into the hover, but this isn't supported on editor hovers.

Being able to lock the hover in place would be very helpful for editors as editor hovers can be very finicky/tricky to get the mouse into. Sometimes they are fine, but other times they can randomly hide, or shift (causing them to hide), etc.

There is also no way for me to fix GitLens issues like: https://github.com/gitkraken/vscode-gitlens/issues/2044 without it.

/cc @alexdima @Tyriar

**Comment by aiday-mar** [comment] 2023-12-05 11:35
Hi @eamodio. When a hover is focused it should not disappear upon hovering out of it. Let me know if this is sufficient for your use case. If not, can you describe what new functionality you would like?

**Comment by DCzajkowski** [comment] 2023-12-05 13:27
@aiday-mar 

Set "editor.hover.sticky" to `false`. At this point, you cannot hover over the hover.
The idea for this PR is that you can hold `alt` and it would keep the hover open and allow you to hover over it, focus it with mouse etc.

Currently, "editor.hover.sticky" set to `false` is useless AFAIK, because it makes it impossible to interact with the hover entirely.

**Comment by aiday-mar** [comment] 2023-12-05 13:42
I see it looks like this issue is a duplicate of the issue https://github.com/microsoft/vscode/issues/151763. This issue will be closed in favor of the other one. You may track progress on the other issue.

**Closed by aiday-mar** 2023-12-05 13:42 UTC
Labels: feature-request, info-needed, editor-hover

**Comment by eamodio** [comment] 2023-12-13 07:27
@aiday-mar Once you can press alt/opt to hold the currently visible editor hover in place, that should address the issue for us -- thanks!
