### ISSUE TITLE
Bad Rendering

### ISSUE THREAD

**Issue by JaDaar** [Microsoft/vscode#45017] opened 2018-03-04 16:27 UTC
### Issue Type
Bug

### Description

I first installed RUST, and a rust extension - the CODE environment displayed a vertical window that seemed to display miscellaneous characters.

I have removed RUST, and switched to Angular - adding two extensions.  The same window appears.  I am highlighting a TypeScript file and there is this window I cannot close next to the source file that has garbage in it.

Opening the Terminal (bash) is totally full of these characters.  Cannot use the integrated terminal from within Code.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 13.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8335  @ 2.93GHz (2 x 2930)|
|Load (avg)|1, 2, 2|
|Memory (System)|4.00GB (0.01GB free)|
|Process Argv|/Users/jeffreyhamlin/Downloads/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular-BeastCode|Mik|5.2.15
Angular2|joh|2.14.0
mssql|ms-|1.3.0
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

**Comment by joaomoreno** [comment] 2018-03-05 16:23
> a vertical window that seemed to display miscellaneous characters

> there is this window I cannot close next to the source file that has garbage in it

> these characters

Can you share some screenshots?

**Comment by JaDaar** [comment] 2018-03-06 13:06
![screen shot 2018-03-06 at 8 00 59 am](https://user-images.githubusercontent.com/961482/37033814-33453816-2115-11e8-8896-b92d6a40c0fe.png)

**Comment by JaDaar** [comment] 2018-03-08 13:31
Maybe I need more memory - but webstorm works fine on the same system

**Comment by alexandrudima** [comment] 2018-03-18 21:32
@JaDaar 

Is this happening after suspending & resuming Linux aka a duplicate of #30292 ?

**Closed** 2018-03-25 21:48 UTC
Labels: needs more info
