### ISSUE TITLE
configurationDefaults should be removed or migrated into the new settings editor

### ISSUE THREAD

**Issue by kbridge** [microsoft/vscode#65844] opened 2018-12-23 09:21 UTC
Hello everyone, I use VSCode-go for golang development for a long time. Yesterday I uninstalled VSCode, cleaned every related folder I known and did a new installation. I took a long time to reconfigure this extension, everything had been settled except the `formatOnSave` feature. Strange enough, even with `"editor.formatOnSave": false` explicitly specified in my `settings.json`, my go format tool still got executed every time I press Ctrl+S.

I struggled for hours, trying to figure out whether VSCode or this extension had a hidden bug. Finally found it was caused by `configurationDefaults`, which was invisible in the new settings editor. After I added the following lines to `settings.json` using the "legacy" settings editor, the problem solved.

```json
    "[go]": {
        "editor.formatOnSave": false
    },
```

I post here to be helpful. I don't think this is a bug, but it can really make users like me feel frustrated.

Hope someone could do something to fix this.

See [package.json](https://github.com/Microsoft/vscode-go/blob/9631a26af65876b9fa96da8340fa869bccbcf84a/package.json#L83).

**Comment by kbridge** [comment] 2019-01-02 01:55
Thank you all for the active reaction.
:handshake:

**Comment by DanTup** [comment] 2019-08-08 08:04
For Dart I'm considering overriding a bunch of VS Code defaults because the frequently cause confusion and complaints (for example, we sort the most relevant completion items to the top of the list, but VS Code's default for `editor.suggestSelection` will often jump down to the bottom of the list, leaving the user really far from the relevant items), but I'm concerned about this - it's not very obvious to the user why their changes to settings won't work if they do want the original behaviour.

I think it would be better if extension-contributed language-specific defaults had lower priority than user-specified global settings. The defaults contributed by extensions are intended to be defaults, it seems unexpected for them to override things the user has explicitly decided to set in the user settings.

**Comment by roblourens** [comment] 2019-10-10 18:46
Duplicate of https://github.com/microsoft/vscode/issues/58995

**Closed by roblourens** 2019-10-10 18:46 UTC
Labels: feature-request, settings-editor
