### ISSUE TITLE
Regression June 2017: Flickering when resizing window or resizing terminal panel

### ISSUE THREAD

**Issue by tkrajacic** [Microsoft/vscode#30460] opened 2017-07-12 05:44 UTC
On the latest June release there is some severe lagging and flickering on the main window on resizing the editor. That wasn't the case before the last update.

- VSCode Version: June 2017 (1.14)
- OS Version: macOS 10.12.5
- Macbook Pro with Retina screen

Steps to Reproduce:

1. open any file
2. resize window or the terminal split panel

Reproduces without extensions: Yes

I made some screen recordings to visualize the problem:

![flicker](https://user-images.githubusercontent.com/873717/28103407-da37f096-66d5-11e7-98c9-8f021a92f366.gif)
![scale-lag](https://user-images.githubusercontent.com/873717/28103408-da615422-66d5-11e7-8a33-a8ed333acb09.gif)

**Comment by mjbvz** [comment] 2017-07-12 06:09
Duplicate of #24643

**Closed by mjbvz** 2017-07-12 06:09 UTC
Labels: duplicate, new release, workbench
