### ISSUE TITLE
Reload Window is slower compared to 1.19

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#42593] opened 2018-01-31 03:49 UTC
Up to 1.19, after running `Reload Window` VS Code starts reloading immediately.
Current build has a ~0.5 second deplay between running the command and starting to reload, as reported by multiple team members from Redmond.
We should find out the cause.

Top is stable, bottom is current.

![reload](https://user-images.githubusercontent.com/4033249/35604322-975b9834-05f6-11e8-94a2-9f08387c62d3.gif)

**Comment by jrieken** [comment] 2018-01-31 07:54
maybe related to https://github.com/Microsoft/vscode/issues/42513

**Comment by jrieken** [comment] 2018-01-31 09:28
likely the sdylog issue

**Comment by joaomoreno** [comment] 2018-01-31 10:01
Definitely spdlog. Duplicate of #42396

@jrieken I checked startup perf of spdlog and I couldn't find any differences from before the update.

**Closed by joaomoreno** 2018-01-31 10:01 UTC
Labels: perf
