### ISSUE TITLE
The terminal process terminated with exit code: 3221225477

### ISSUE THREAD

**Issue by Mahfuzarrahman-sys** [microsoft/vscode#91044] opened 2020-02-20 05:41 UTC
Issue Type: <b>Bug</b>

When I open new terminal shows The terminal process terminated with exit code: 3221225477

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:46:03.121Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1795)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.40GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment] 2020-02-20 08:45
/duplicate of #88780. You are running VS Code on 32-bit Windows 7, which is no longer supported.

**Closed** 2020-02-20 12:17 UTC
