### ISSUE TITLE
Maximizing/resizing the window should automatically snap grid into place (provided it wasn't adjusted)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50706] opened 2018-05-29 17:45 UTC
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458 

Split to right:

![image](https://user-images.githubusercontent.com/2193314/40675465-b8c1d34c-632c-11e8-857e-0af5a797cb4c.png)

Maximize window:

![image](https://user-images.githubusercontent.com/2193314/40675488-c4118e86-632c-11e8-99a7-c74eacc20472.png)

When the terminal panel containing split panes is resized it defaults to resetting the proportional size of the split panes. If something is manually saved it will try to retain that:

https://github.com/Microsoft/vscode/blob/f5300ced7fbd0193babf05ee37860bb2d160beb7/src/vs/workbench/parts/terminal/browser/terminalTab.ts#L22-L25

**Comment by bpasero** [comment] 2018-05-30 04:28
Duplicate of https://github.com/Microsoft/vscode/issues/1447

**Closed by bpasero** 2018-05-30 04:28 UTC
Labels: insiders, workbench-grid
