### ISSUE TITLE
Extension API: get installed/enabled/disabled extensions

### ISSUE THREAD

**Issue by Gerschtli** [Microsoft/vscode#64148] opened 2018-12-02 13:57 UTC
Hello,
I was very confused, that it's currently not possible to retrieve all installed extensions (including the disabled ones) via the API and that there are very few exposed functions for managing extensions.
Therefore I would like to request updating the `vscode.extensions` API as follows (inspired by Atom API https://atom.io/docs/api/v1.33.0/PackageManager ), to add more flexibility and consistency to extension developers:

- add function to retrieve all installed extensions (including the disabled ones)
- add function to retrieve all manually installed extensions (this excludes default/builtin extensions)
- add functions to retrieve all enabled/disabled extensions (globally or workspace-specifically)
- add functions to install/uninstall extensions
- add method in `Extension<T>` to enable/disable extensions (globally or workspace-specifically)
- add an enum property `state` to `Extension<T>` to indicate whether this extension is globally enabled/disabled or workspace-specifically enabled/disabled
- add boolean property `builtin` to `Extension<T>` to indicate whether this extension is a builtin/default extension

What do you think? I would love to help implementing this, but I don't have any experience in this project, so some hints where to look at would be awesome.

Thank you!

**Comment by sandy081** [comment] 2018-12-03 11:07
Duplicate of #14444

**Closed by sandy081** 2018-12-03 11:07 UTC
Labels: extensions

**Comment by Gerschtli** [comment] 2018-12-03 18:08
Doesn't look like a complete duplicate, but regarding the age of the linked PR, this is some part of vscode, that doesn't get the attention it needs to..
