### ISSUE TITLE
JSON schema auto completion not working as expected

### ISSUE THREAD

**Issue by GernotKovar** [microsoft/vscode#201111] opened 2023-12-18 11:10 UTC
Type: <b>Bug</b>

[sample_schema.json](https://github.com/microsoft/vscode/files/13702920/sample_schema.json)
[sample.json](https://github.com/microsoft/vscode/files/13702922/sample.json)

- Use the JSON sample schema and add a reference in the VS code setting.json in the "json.schemas" property.
- Have the sample.json validated using the schema
- Create a new object in the array and set the "type" property.
- When I enter "type:", the autocomplete works as expected (and shows "sample" and "sampleNotWorking")
-If I enter "" after "type:", the autocomplete only shows the definition "sample"

Expected that both values ("sample" and "sampleNotWorking") would also be displayed in the second case

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|64.00GB (12.27GB free)|
|Process Argv|--crash-reporter-id 6f74c1bd-d72a-463e-b84a-fa9fa0bea5f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.19.2
better-comments|aar|3.0.2
TabOut|alb|0.2.2
project-manager|ale|12.7.0
aws-toolkit-vscode|ama|2.3.0
preview-pdf|ana|1.0.0
jest-snippets|and|1.9.1
vscode-json|and|1.5.2
swagger-viewer|Arj|3.1.2
atlascode|atl|3.0.9
rc-beautify|Ato|1.2.0
azurite|Azu|3.29.0
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.53.0
go-to-character-position|dav|2.0.0
vscode-eslint|dba|2.4.2
svg-gallery|dev|2.1.0
githistory|don|0.6.20
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
json-tools|eri|1.0.2
prettier-vscode|esb|10.1.0
image-to-base64|FEZ|1.0.1
vscode-jest-runner|fir|0.4.69
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
remotehub|Git|0.62.0
todo-tree|Gru|0.0.226
imagesprites|gur|1.0.0
vscode-test-explorer|hbe|2.21.1
mdcontenttable|jlu|1.0.0
vscode-peacock|joh|4.2.2
json-escaper|jos|1.1.2
intellij-idea-keybindings|k--|1.5.12
vscode-jest-test-adapter|kav|0.8.1
vscode-gutter-preview|kis|0.30.0
har-analyzer|Mat|0.0.7
git-graph|mhu|1.30.0
mongodb-vscode|mon|1.3.1
vscode-docker|ms-|1.28.0
vscode-language-pack-de|MS-|1.85.2023121309
isort|ms-|2023.10.1
python|ms-|2023.22.1
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2023.11.1003402403
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.327.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.40.0
remote-server|ms-|1.5.0
test-adapter-converter|ms-|0.1.8
json-parse-stringify|nex|1.0.2
vscode-json-editor|nic|0.3.0
copy-json-path|nid|0.3.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.32.0
run-on-save|puc|1.6.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.16.3
vscode-yaml|red|1.14.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
image-essentials|s2j|0.0.5
xml-toolkit|SAP|1.1.0
vue-vscode-snippets|sdr|3.1.1
loopback-json-schemas|seq|1.0.0
markdown-preview-enhanced|shd|0.8.11
printtimestamp|sno|0.1.0
jest-snapshot-language-support|tle|1.1.1
volar|Vue|1.8.25
vscode-typescript-vue-plugin|Vue|1.8.25
quokka-vscode|Wal|1.0.603
wallaby-vscode|Wal|1.0.371
vscode-xsl-transform|Was|1.1.1
highlight-bad-chars|wen|0.0.6
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184c:30925681

```

</details>

**Comment by aeschli** [comment] 2023-12-18 13:28
duplicate of https://github.com/microsoft/vscode/issues/43195

It's a known limitation on how the algorithm processes `anyOf`.

**Closed by aeschli** 2023-12-18 13:28 UTC
