### ISSUE TITLE
different colors for different files

### ISSUE THREAD

**Issue by blaubacher** [microsoft/vscode#204837] opened 2024-02-09 15:38 UTC
Type: <b>Feature Request</b>

Could you allow different files within the editor to use different color schemes?  have the schemes a 'local' rather than 'global' option?

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mirusky** [comment] 2024-02-09 19:02
Duplicate of #203998 
Related to #204824

**Comment by aeschli** [comment] 2024-03-11 10:22
duplicate of #20652

**Closed by aeschli** 2024-03-11 10:22 UTC
