### ISSUE TITLE
Cannot execute paste in InputBox

### ISSUE THREAD

**Issue by nliu-ms** [microsoft/vscode#114325] opened 2021-01-14 03:03 UTC
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.19042
![image](https://user-images.githubusercontent.com/71362691/104538541-0a4e9e00-5657-11eb-827b-a0f1f83bd6c0.png)

Steps to Reproduce:

1. Implement a vscode extension, which has vscode.window.showInputBox
```          
            adminPassword = await vscode.window.showInputBox({
                placeHolder: data.sqlAdminPassword,
                ignoreFocusOut: true,
                password: true,
                validateInput: commonUtils.sqlPasswordValidatorGenerator(adminUserName)
            });
```
2. Debug the extension, trigger the command. Use Ctrl+c/Ctrl+v to copy paste.
3. Paste cannot be performed.
4. Click other applications to change the focus, and then focus back on this input box.
5. Paste can be executed now.

![bug2](https://user-images.githubusercontent.com/71362691/104538170-551be600-5656-11eb-9af2-df4eb8c24ba5.gif)

Does this issue occur when all extensions are disabled?: No.

**Comment by chrmarti** [comment] 2021-01-14 10:14
Possibly related: https://github.com/microsoft/vscode/issues/112557, https://github.com/microsoft/vscode/issues/114019

Since you don't see this with all extensions disabled: Could you run the `F1` > `Help: Start Extension Bisect` to see which extension triggers it?

**Comment by bwateratmsft** [comment] 2021-01-20 15:14
@haf encountered this issue with the Docker extension, also on a password input box: https://github.com/microsoft/vscode-docker/issues/2643

**Comment by nliu-ms** [comment] 2021-01-21 01:33
> Possibly related: #112557, #114019
> 
> Since you don't see this with all extensions disabled: Could you run the `F1` > `Help: Start Extension Bisect` to see which extension triggers it?

Thanks chrmarti, this has been found in an extension implemented by our team. https://github.com/OfficeDev/vscode-mods

**Comment by chrmarti** [comment] 2021-01-21 08:46
@nliu-ms Thanks, closing as caused by extension.

**Comment by chrmarti** [comment] 2021-01-22 08:06
@nliu-ms Did you find the cause for this in your extension? (Or did I misunderstand?)

**Comment by nliu-ms** [comment] 2021-01-25 01:42
> @nliu-ms Did you find the cause for this in your extension? (Or did I misunderstand?)

I haven't. Let me try to build a sample extension to see if this bug can be triggered or not.

**Closed** 2021-04-23 11:28 UTC
Labels: *caused-by-extension, needs more info, quick-pick
