### ISSUE TITLE
Pasting into JavaDoc style comments doesn't add asterisk.

### ISSUE THREAD

**Issue by goldingdamien** [Microsoft/vscode#42073] opened 2018-01-24 05:23 UTC
Not a major issue, but when pasting text into JavaDoc style comments, it would be convenient if it auto-formatted. If this is possible via another method please let me know.

**Comment by warpdesign** [comment] 2018-01-24 13:17
I also noticed.

**Comment by mjbvz** [comment] 2018-01-25 01:46
Duplicate of #25894

**Closed by mjbvz** 2018-01-25 01:46 UTC
Labels: editor

**Comment by goldingdamien** [comment] 2018-01-25 02:07
Just want to note that this is being closed due to a duplicate which was closed due to not enough traction.
Maybe this issue voids that reason.

**Comment by warpdesign** [comment] 2018-01-25 09:58
@goldingdamien I guess it does.
