### ISSUE TITLE
changing ctrl+` shortcut doesn't toggle terminal when terminal is in focus

### ISSUE THREAD

**Issue by lorenzo2702** [Microsoft/vscode#9006] opened 2016-07-09 16:29 UTC
Toggling the new 1.3 Terminal works well when bound to it's default shortcut ctrl+` but when changed to alt+` it will only toggle the terminal if it is not the focus. If the terminal is the focus it will only type the backtick/grave. This happens with the default cmd.exe terminal and with a powershell.exe terminal.

I did not try any shortcuts other than alt+` so I can't speak to the extent of the issue but using alt+` worked with the 1.2 integrated terminal.

- VSCode Version:  1.3.0
- OS Version:  Windows 10.0.10586

Steps to Reproduce:
1.  Add new keyboard shortcut to keybindings.json
2.  { "key": "alt+`",                "command": "workbench.action.terminal.toggleTerminal" }

**Comment by Tyriar** [comment] 2016-07-10 23:37
Closing as duplicate of #7269.

**Closed by Tyriar** 2016-07-10 23:37 UTC
