### ISSUE TITLE
Sysinternals Process Explorer hinders VS Code form updating

### ISSUE THREAD

**Issue by Bernd-L** [Microsoft/vscode#68152] opened 2019-02-07 18:50 UTC
# Sysinternals Process Explorer hinders VS Code form updating

- VSCode Version: 1.32.0-insider 45c7f29565821668f4d010b25e3289953bd9ac71 x64
- OS Version: Windows 10 Pro Version 1809 (OS Build 18298.1000)

## Steps to Reproduce

1. Have Sysinternals Process Explorer Open (Admin, x64)
2. Have VS Code attempt to update
3. Wait
4. Get an error :(

## Workaround
Close PE. Then it works.

## PS
When I search in PE for which processes have file handles on the VS Code file, it only lists itself. This is how I discovered it.

**Comment by joaomoreno** [comment] 2019-02-08 09:17
Unfortunately, closing this as designed, since PE shouldn't lock into files which it doesn't own itself.

**Closed by joaomoreno** 2019-02-08 09:17 UTC
Labels: install-update
