### ISSUE TITLE
Extension host terminated

### ISSUE THREAD

**Issue by ini-orang** [microsoft/vscode#176868] opened 2023-03-11 21:08 UTC
Type: <b>Bug</b>

1. Lastest vs code as per writing
2. Python 3.11.2
3. Run any python file
4. The extension host restarted..?

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.76GB free)|
|Process Argv|--crash-reporter-id cc56ca29-103a-4b12-9ccb-48ac162f7d76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
project-manager|ale|12.7.0
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|13.3.2
copilot|Git|1.77.9225
discord-vscode|icr|5.8.0
better-cpp-syntax|jef|1.17.2
cmake-language-support-vscode|jos|0.0.9
fluent-icons|mig|0.0.18
snapcode|moy|1.1.0
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.5.10681722
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.5.0
java|red|1.15.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
material-theme|zhu|3.15.8
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
funwalk2cf:30682975
pythonms35cf:30680985

```

</details>

**Comment by ini-orang** [comment] 2023-03-11 21:52
Disabling GitHub Copilot Fixes this issue somehow, still I want to use Copilot too

**Comment by isidorn** [comment] 2023-03-15 11:19
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:19 UTC
Labels: freeze-slow-crash-leak, extension-host
