### ISSUE TITLE
toolbar bug on windows with hebrew localization

### ISSUE THREAD

**Issue by Itaybl14** [microsoft/vscode#160559] opened 2022-09-09 20:57 UTC
hi, found this bug a week ago after updating to the newest version
![בסטי איתי](https://user-images.githubusercontent.com/84288727/189444236-2ba12416-ccef-4582-8c92-b2bfd535d4cb.JPG)

**Comment by rzhao271** [comment] 2022-09-09 21:40
Duplicate of #159813

**Closed by rzhao271** 2022-09-09 21:40 UTC
