### ISSUE TITLE
Breadcrumbs—select object—for copy and paste.

### ISSUE THREAD

**Issue by smeyerhot** [microsoft/vscode#126723] opened 2021-06-19 03:51 UTC
I would like to be able to easily select functions which are highlighted by breadcrumbs. I am willing to work on this but I would appreciate some guidance on where to find the files responsible for breadcrumb actions.

**Comment by jrieken** [comment] 2021-06-21 07:23
>  easily select functions which are highlighted by breadcrumbs.

Not sure what you mean by that and how it relates to copy-paste. Is this issue a dupe of https://github.com/microsoft/vscode/issues/56494 or https://github.com/microsoft/vscode/issues/58678?

**Comment by smeyerhot** [comment] 2021-06-21 14:21
Sorry if this is unclear. What I meant is that I’d like to copy the body of a function that is highlighted by breadcrumbs. So, no this isn’t a duplicate of those issues you mentioned.

**Comment by jrieken** [comment] 2021-06-21 14:56
Breadcrumb entries (by its API) are necessarily the whole body, often the structure is only about the name defining the symbol so having a good solution won't be easy... An alternative is "F1 > Expand Selection"

**Closed** 2021-08-23 02:31 UTC
Labels: feature-request, breadcrumbs
