### ISSUE TITLE
Teminal exception error - 4294901760

### ISSUE THREAD

**Issue by KKC1930569** [microsoft/vscode#166979] opened 2022-11-22 16:20 UTC
Type: <b>Bug</b>

Terminal -> New terminal -> error

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (7.68GB free)|
|Process Argv|--crash-reporter-id 7b661f34-6bc5-426a-8d58-a44a295d93ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.29
vscode-npm|fkn|3.3.0
search-node-modules|jas|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
pyind779cf:30617257
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by meganrogge** [comment] 2022-11-28 17:44
I think this is a duplicate of this issue. https://github.com/microsoft/vscode/issues/100366#issuecomment-645322374

The other thing you can try is downloading Powershell 7 and then reloading VS Code. It should pick up on that installation.

**Closed by meganrogge** 2022-11-28 17:44 UTC
