### ISSUE TITLE
Suggestion trigger characters not inserted

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#64257] opened 2018-12-03 22:21 UTC
Issue Type: <b>Bug</b>

**Repo**
1. In  a js file
1. Type `consol`
1. Press `.` to accept `console` suggestion

**Bug**
Only `console` inserted. The `.` is dropped

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by mjbvz** [comment] 2018-12-03 22:46
@jrieken I'm reverting c2c2e48dd3c704b8585ba7a7c642d75afca74ce7 so that it does not hit insiders. Still looking into fix

**Comment by mjbvz** [comment] 2018-12-04 01:39
Sorry @jrieken, I took a look but am not sure how about this one. c2c2e48 would be nice to have but is not a regression so it's not essential for November

**Comment by jrieken** [comment] 2018-12-04 08:11
Fair enough - making the insert-call async was a bold move ;-). Moving this to December for a proper fix

**Comment by mjbvz** [comment] 2019-01-21 19:37
Potential related: #42544 Support suppressing commit character from being inserted during completion

**Comment by jrieken** [comment] 2019-05-19 19:37
Closing this in favour of https://github.com/microsoft/vscode/issues/73311 and/or https://github.com/microsoft/vscode/issues/63013. Both have the same root cause which is us not always resolving completions before inserting...

**Closed** 2019-05-19 19:38 UTC
Labels: bug, suggest
