### ISSUE TITLE
Typescript hangs after "@enum" JSDoc tag was typed

### ISSUE THREAD

**Issue by Aliaksei-Martsinkevich** [Microsoft/vscode#62470] opened 2018-11-02 13:31 UTC
Issue Type: <b>Bug</b>

I have jsconfig in my project and following patter is commonly used to represent enum. Everything works fine at this point.

![before](https://user-images.githubusercontent.com/16012334/47917559-f1fd6900-deba-11e8-8ef6-d3e034fc1842.PNG)

But when I add JSDoc with `@enum` tag, Typescript just hangs, and all suggestions are broken.
Also there is an error: 'Type expected'.

![after](https://user-images.githubusercontent.com/16012334/47917563-f4f85980-deba-11e8-98b9-257c07a56bbe.PNG)

After window reload everything works again. 
If you type JSDoc backwards it works:
`/** {number} */` first, and only then `@enum`.

Reproduced without any extensions: `code --disable-extensions .`

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment] 2018-11-02 18:44
This is likely a duplicate of https://github.com/Microsoft/TypeScript/issues/27471

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Aliaksei-Martsinkevich** [comment] 2018-11-05 08:31
It's not reproduced in latest insiders build.

**Comment by mjbvz** [comment] 2018-11-06 00:34
Thanks. Closing this as a duplicate of Microsoft/TypeScript#27471

Fix will go out to everyone with in VS Code 1.29

**Closed by mjbvz** 2018-11-06 00:34 UTC
Labels: javascript, needs more info
