### ISSUE TITLE
Crash when loading a big code file

### ISSUE THREAD

**Issue by Banyc** [microsoft/vscode#95595] opened 2020-04-18 12:38 UTC
[MipsAsmParser.zip](https://github.com/microsoft/vscode/files/4496615/MipsAsmParser.zip)

Issue Type: <b>Bug</b>

1. Load the file `MipsAsmParser.cs` attached to VSCode.
1. Crashed.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

PS:

I also checked with extensions off. It seems that it is the issue of VSCode.

**Comment by Banyc** [comment] 2020-04-18 12:41
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Visual studio code is getting crashed (#94932)](https://www.github.com/microsoft/vscode/issues/94932)

It is not the same issue.

**Comment by chrmarti** [comment] 2020-04-20 11:13
What is the file's size and how many lines does it have?

**Comment by Banyc** [comment] 2020-04-22 02:21
> What is the file's size and how many lines does it have?

I have uploaded the file in the first line of the issue.

**Comment by alexdima** [comment] 2020-04-27 19:05
@Banyc Thank you, this is all caused by the following line in your file:
```
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__7) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << T__23) | (1L << T__26) | (1L << T__27) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << T__31) | (1L << T__32) | (1L << T__33) | (1L << T__34) | (1L << T__35) | (1L << T__36) | (1L << T__37) | (1L << T__38) | (1L << T__39) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << T__43) | (1L << NEWLINE) | (1L << COMMENT) | (1L << NUM) | (1L << ALPHA))) != 0) );
```

There are multiple regular expressions that take a long time. I found them with some newly added support via `F1 > Developer: Start Text Mate Syntax Grammar Logging`:

```
- searchOnigRegExp: (?x)
(?:
  (?:(\bref)\s+(?:(\breadonly)\s+)?)?(\bvar\b)| # ref local
  (?<type-name>
    (?:
      (?:ref\s+(?:readonly\s+)?)?   # ref local
      (?:
        (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
        (?<name-and-type-args> # identifier + type arguments (if any)
          \g<identifier>\s*
          (?<type-args>\s*<(?:[^<>]|\g<type-args>)+>\s*)?
        )
        (?:\s*\.\s*\g<name-and-type-args>)* | # Are there any more names being dotted into?
        (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
      )
      (?:\s*\?\s*)? # nullable suffix?
      (?:\s*\[(?:\s*,\s*)*\]\s*)* # array suffix?
    )
  )
)\s+
(\g<identifier>)\s*
(?!=>)
(?=,|;|=|\))
|- did not match after 3834.285 ms
```

```
- searchOnigRegExp: (?x)
(\()\s*
(?<type-name>
  (?:
    (?:
      (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
      (?<name-and-type-args> # identifier + type arguments (if any)
        \g<identifier>\s*
        (?<type-args>\s*<(?:[^<>]|\g<type-args>)+>\s*)?
      )
      (?:\s*\.\s*\g<name-and-type-args>)* | # Are there any more names being dotted into?
      (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
    )
    (?:\s*\?\s*)? # nullable suffix?
    (?:\s*\[(?:\s*,\s*)*\]\s*)* # array suffix?
  )
)\s*
(\))(?=\s*@?[_[:alnum:]\(])
|- did not match after 2960.280 ms
```

```
- searchOnigRegExp: (?x)
(?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))\s*
(?!=>|==)(?==)
|- did not match after 3877.615 ms
```

```
- searchOnigRegExp: (?x)
(?:
  (?:(\bref)\s+(?:(\breadonly)\s+)?)?(\bvar\b)| # ref local
  (?<type-name>
    (?:
      (?:ref\s+(?:readonly\s+)?)?   # ref local
      (?:
        (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
        (?<name-and-type-args> # identifier + type arguments (if any)
          \g<identifier>\s*
          (?<type-args>\s*<(?:[^<>]|\g<type-args>)+>\s*)?
        )
        (?:\s*\.\s*\g<name-and-type-args>)* | # Are there any more names being dotted into?
        (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
      )
      (?:\s*\?\s*)? # nullable suffix?
      (?:\s*\[(?:\s*,\s*)*\]\s*)* # array suffix?
    )
  )
)\s+
(\g<identifier>)\s*
(?!=>)
(?=,|;|=|\))
|- did not match after 3979.295 ms
```

**Comment by alexr00** [comment] 2020-04-28 11:02
Moved to the grammar's repo: https://github.com/dotnet/csharp-tmLanguage/issues/180

**Comment by alexr00** [comment] 2020-11-05 11:20
Closing in favor of the upstream issue.

**Closed by alexr00** 2020-11-05 11:20 UTC
Labels: grammar, upstream-issue-linked
