### ISSUE TITLE
Improve error handling when 3rd party cookies are disabled in Chrome

### ISSUE THREAD

**Issue by jkelroy** [microsoft/vscode#178617] opened 2023-03-29 19:27 UTC
Summary: When you have 3rd party cookies disabled on Google Chrome, some things within vscode.dev will not load and give the following error. It would be nice if the response was more user friendly and actionable.

```
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://1van0824i4s6oqpg2iretiujbcspm2kcnhi2k1a7e09bfiu4405b.vscode-cdn.net/stable/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://1van0824i4s6oqpg2iretiujbcspm2kcnhi2k1a7e09bfiu4405b.vscode-cdn.net/stable/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): The user denied permission to use Service Worker..
```

Steps to Repro:
1. In Google Chrome, go to Settings > Privacy and Security > Cookies and site data > check `Block third-party cookies`
2. Open vscode.dev
3. Download GitLens
4. Select the GitLens icon in the left panel

![Screenshot 2023-03-29 at 1 23 25 PM](https://user-images.githubusercontent.com/27739784/228646747-955e75a8-bd2c-485e-adfa-e3de309c797d.png)

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by mjbvz** [comment] 2023-03-29 19:38
Duplicate of #176218

**Closed by mjbvz** 2023-03-29 19:38 UTC
