### ISSUE TITLE
SSH sessions stopped working after update

### ISSUE THREAD

**Issue by brl0** [microsoft/vscode#94823] opened 2020-04-09 18:57 UTC
Issue Type: <b>Bug</b>

Updated to current daily version.
Attempted to reconnect to SSH host.  
Terminal pane appears with just a non-blinking cursor.
After timeout period elapses, an error message appears:
`Could not establish connection to "server".  Connecting with SSH timed out.`
The output pane appears and shows output that seems to indicate a successful connection.

I increased the timeout in settings from 15 seconds to 30 seconds, and the same results.
Tried uninstalling the Nightly version of the Remote/SSH and installing the standard release, same results.

VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:22:11.706Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (6.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-sqlite|ale|0.8.1
vscode-browser-preview|auc|0.6.3
vscode-database|baj|2.2.0
vscode-importmagic|bra|0.2.5
npm-intellisense|chr|1.3.0
codestream|Cod|7.0.0
bracket-pair-colorizer-2|Coe|0.0.29
vs-treeview|DaG|2.7.0
vscode-markdownlint|Dav|0.34.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.21
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.1.1
git-project-manager|fel|1.7.1
file-icons|fil|1.0.23
vscode-firefox-debug|fir|2.7.2
vscode-mysql|for|0.4.0
code-python-isort|fre|0.0.3
vscode-codeql|Git|1.1.1
vscode-pull-request-github|Git|0.15.0
todo-tree|Gru|0.0.171
language-cython|guy|0.0.6
vscode-test-explorer|hbe|2.17.0
vscode-guid|hea|1.4.19
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
codecmder|Jul|0.0.9
vsc-python-indent|Kev|1.8.1
vscode-simple-icons|Lau|1.13.2
restructuredtext|lex|125.0.0
vscode-python-test-adapter|lit|0.3.18
git-graph|mhu|1.22.0
theme-monokai-pro-vscode|mon|1.1.15
vscode-azureappservice|ms-|0.16.4
vscode-docker|ms-|1.0.0
vscode-postgresql|ms-|0.2.0
pyright|ms-|1.1.30
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.3.71659
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
cmake-tools|ms-|1.3.1
cpptools|ms-|0.27.0
jscs|ms-|0.1.9
powershell-preview|ms-|2020.4.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|3.9.20200408
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
sqltools|mtx|0.21.6
python-coding-tools|nil|1.0.3
vetur|oct|0.24.0
material-icon-theme|PKi|4.0.1
text-power-tools|qcz|1.11.1
fabric8-analytics|red|0.0.13
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
LiveServer|rit|5.6.1
preview-vscode|sea|2.1.0
sonarlint-vscode|Son|1.15.0
vscode-taskexplorer|spm|1.26.3
rewrap|stk|1.9.1
ayu|tea|0.18.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
WebTemplateStudio-dev-nightly|WAS|0.2.2007701
material-theme|zhu|3.2.5

(14 theme extensions excluded)

</details>

**Comment by brbecker** [comment] 2020-04-09 22:11
Probably a duplicate of #94816

**Comment by RMacfarlane** [comment] 2020-04-10 00:24
Thanks @brbecker! Closing as a duplicate of https://github.com/microsoft/vscode/issues/94816

**Closed by RMacfarlane** 2020-04-10 00:24 UTC
