### ISSUE TITLE
restart to update issue

### ISSUE THREAD

**Issue by shaddu** [Microsoft/vscode#25733] opened 2017-05-01 13:58 UTC
- VSCode Version: 1.9.1
- OS Version:MacOS

Steps to Reproduce:

1. Click on code->restart to update and it closes all windows of vscode but doesn't updates and not even the application opens automatically

**Comment by kieferrm** [comment] 2017-05-01 14:12
This is a duplicate of #7426.  @shaddu the issue lists how to fix the issue.

**Closed by kieferrm** 2017-05-01 14:12 UTC
