### ISSUE TITLE
Broken syntax highlight in ternary Operator

### ISSUE THREAD

**Issue by mubaidr** [Microsoft/vscode#5640] opened 2016-04-22 05:07 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Open any js file
2. Write ternary if statement
3. Syntax highlight will be broken. 

![bug](https://cloud.githubusercontent.com/assets/2222702/14732233/04910e40-0872-11e6-8044-c716b2ebe983.PNG)

**Comment by Tyriar** [comment] 2016-04-22 05:43
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81

**Closed by Tyriar** 2016-04-22 05:43 UTC
