### ISSUE TITLE
Can not Replace Enter or New Line

### ISSUE THREAD

**Issue by alexblair** [Microsoft/vscode#5466] opened 2016-04-19 02:18 UTC
- VSCode Version:1.0
- OS Version:windows 10 (1511)

Steps to Reproduce:

1. open New File.

2.Ctrl+H

3. USE \n

4.can not find ENTER OR newline

![image](https://cloud.githubusercontent.com/assets/4616320/14625698/f3c8f7fa-0617-11e6-96a5-0d5bc9247556.png)

**Comment by anyong** [comment] 2016-04-19 20:29
I have noticed a number of similar regex issues, like not being able to select `.*` and others. I didn't open issues but it seems like the regex search feature needs some work.

**Comment by Tyriar** [comment] 2016-04-20 01:23
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Closed by Tyriar** 2016-04-20 01:23 UTC
Labels: bug
