### ISSUE TITLE
Run and debug (Flutter ) Not working on 1.92 vertion

### ISSUE THREAD

**Issue by faztrick** [microsoft/vscode#221550] opened 2024-07-12 10:19 UTC
Type: <b>Bug</b>

Run and debug (Flutter ) Not working on 1.92 vertion is automaticaly closing dubug section

VS Code version: Code - Insiders 1.92.0-insider (a35380d6f0ff65f7c35345baafcf1c3f8a378d38, 2024-07-12T05:08:08.550Z)
OS version: Windows_NT x64 10.0.26252
Modes:
Remote OS version: Linux x64 5.15.0-1062-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13980HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.63GB (5.01GB free)|
|Process Argv|--crash-reporter-id 9087b32c-a363-4ece-9b5a-76172960ca56|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: Idol|
|OS|Linux x64 5.15.0-1062-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (2 x 0)|
|Memory (System)|3.82GB (0.96GB free)|
|VM|0%|
</details><details><summary>Extensions (102)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
flutter-snippets|ale|3.0.0
vscode-color|ans|0.4.5
iconify|ant|0.8.1
dart-quick-fix|Art|0.0.1
vscode-imagemin|axe|0.5.1
ccs-flutter-color|cir|1.2.4
languague-renpy|cob|2.0.0
gitignore|cod|0.9.0
macros|ctf|1.1.0
vscode-myssql-client2|cwe|7.5.5
vscode-es-beautifier|dai|1.1.0
dart-code|Dar|3.93.20240711
flutter|Dar|3.93.20240702
git-diff-and-merge-tool|dav|1.0.5
vscode-markdownlint|Dav|0.55.0
flutter-auto-import|dav|0.0.1
vscode-terminal-for-ubuntu|Doc|0.0.2
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.105
json-tools|eri|1.0.2
prettier-vscode|esb|10.4.0
vscode-flutter-i18n-json|ess|0.28.0
git-project-manager|fel|1.8.2
code-runner|for|0.12.2
get-snippets|get|4.3.0
codespaces|Git|1.17.1
copilot|Git|1.212.983
copilot-chat|Git|0.18.2024071201
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.93.2024071104
todo-tree|Gru|0.0.226
hex-to-rgb|hex|1.0.3
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.4
vscode-essentials|jab|1.6.0
pubspec-assist|jer|2.3.2
vscode-text-pastry|jkj|1.3.1
svg|joc|1.5.4
vscode-peacock|joh|4.2.2
intellij-idea-keybindings|k--|1.7.2
build-runner|Kai|2.1.1
vscode-undo-buttons|kco|1.1.1
vscode-gutter-preview|kis|0.31.2
vscode-format-context-menu|lac|1.0.4
flutter-intl|loc|1.19.3
vscode-lottie|lot|1.0.5
dart-import|lua|0.3.1
show-settings-vscode|luc|1.1.0
languague-renpy|Luq|2.3.6
flutter-tree|mar|1.0.0
code-coverage|mar|1.12.0
json|Mee|0.1.2
git-graph|mhu|1.30.0
auto-commit-msg|Mic|0.27.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-edge-devtools|ms-|2.1.5
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.1
debugpy|ms-|2024.8.0
python|ms-|2024.10.0
vscode-pylance|ms-|2024.7.1
remote-ssh|ms-|0.113.2024070816
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.20.5
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2024.7.517
powershell|ms-|2024.3.2
remote-explorer|ms-|0.5.2024070409
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024070809
awesome-flutter-snippets|Nas|4.0.1
color-highlight|nau|2.8.0
dart-syntax-highlighting-only|osc|1.0.1
renpyWarp|Pai|1.4.1
explorer-exclude|Pet|1.3.2
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.4.2
polacode|pnp|0.3.4
vscode-thunder-client|ran|2.24.12
vscode-yaml|red|1.15.0
flutter-insider|rex|2.5.0
hide-files|roo|1.0.3
gi|rub|0.2.11
control-snippets|svi|1.9.1
pdf|tom|1.2.2
vscode-lldb|vad|1.10.0
vscode-gradle|vsc|3.14.1
vscode-icons|vsc|12.8.0
local-history|xyz|1.8.1
dart-built-value-snippets|yon|1.1.2
json|Zai|2.0.2
flutter-provider-snippets|Zar|1.5.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl2:31093712
refactort:31084545
pythonrstrctxt:31093868
4930e709:31088354
hdi1a554:31091669

```

</details>

**Comment by l1qu1d** [comment] 2024-07-12 16:17
Duplicate of #221484

**Comment by l1qu1d** [comment] 2024-07-12 16:29
@faztrick If you need to use debug to get by for now, please look at: https://github.com/microsoft/vscode/issues/221484#issuecomment-2225925190

**Comment by roblourens** [comment] 2024-07-30 00:33
I assume this is https://github.com/microsoft/vscode/issues/224184

**Closed by roblourens** 2024-07-30 00:33 UTC
