### ISSUE TITLE
Provide All Types Font Support , currently monospace fonts only works fine.

### ISSUE THREAD

**Issue by vijayhardaha** [microsoft/vscode#77697] opened 2019-07-20 15:59 UTC
I use "Federo" Font for my every editor but when i am using this font on Visual Studio Code, I'm having word wrap issues and also terminal has issues. I can change the font for the terminal but for the main editor, I wanna use "Federo" without having word wrap issue.

I checked other issues and found you only allowed Monospace fonts for the editor to work properly.

Please Provide all type font support in near future.

**Comment by alexandrudima** [comment] 2019-08-08 11:40
Duplicate of #2654

**Closed by alexandrudima** 2019-08-08 11:40 UTC
Labels: editor-wrapping
