### ISSUE TITLE
a11y: Close Window doesn't always work

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode#116132] opened 2021-02-08 17:02 UTC
Issue Type: <b>Bug</b>

1. Open a folder as a workspace.
2. Open a few editors, some in preview mode, others with edits, all saved.
3. Choose File/Close Window.

First bug: On the Mac, the key binding for close Window and Close editor is both CMD+W. Close Window should maybe be CMD+Shift+W or something similar.
Second bug: Even when explicitly choosing File/Close Window, the window doesn't always close. Instead, sometimes only the current file/editor is closed. Or nothing happens. I haven't figured out the pattern.

VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:23:20.010Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id 4ea43554-4a6d-4f7c-b2fb-6de1a3610d98|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.9.1
vscode-pull-request-github|Git|0.23.0
beautify|Hoo|1.5.0
jstl|jsx|1.0.4
flutter-intl|loc|1.13.0
vscode-docker|ms-|1.9.1
vscode-edge-devtools|ms-|1.1.3
python|ms-|2021.2.529263813-dev
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
debugger-for-edge|msj|1.0.15
nunjucks|ron|0.3.0
vscode-webhint|web|1.5.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by bpasero** [comment] 2021-02-09 06:41
@MarcoZehe can you reproduce the same issue in VSCode stable (1.53.0)? Trying to understand if this is a regression in insiders or not.

**Comment by MarcoZehe** [comment] 2021-02-09 07:02
@bpasero Just confirmed that this works fine in 1.53 stable. (Side note: heck, is that Intel-only build slow on my M1 Mac compared to the Silicon Insider build!)

**Comment by bpasero** [comment] 2021-02-09 07:04
Not sure if this is a menu regression, adding @sbatten 

@MarcoZehe just to confirm, what exactly is working in stable and not working in insiders? Asking because you posted more than one issue here.

**Comment by MarcoZehe** [comment] 2021-02-09 07:08
@bpasero Ah, thanks for the heads-up, I was indeed thinking of the wrong issue initially. I have updated my above comment.

**Comment by isidorn** [comment] 2021-02-12 17:25
I just tried to reproduce this on my macOS and I could not.
In insiders I never hit this since I have cmd+w binded to close all editors in group command.
However I just tried latest Stable and this seems to work just fine. Cmd + w always closes the editor, and if there are no more editors it closes the window. I see the same behavior for example in Chrome, so I do not mind that we do not have a special shortcut for closing the window.

@MarcoZehe Anyways, let us know if you get more precise repro steps. Thanks

**Comment by MarcoZehe** [comment] 2021-02-12 17:57
My use case is this: Sometimes when working on a project, I end up with 30 or so editors open. So, I'd have to press CMD+W 30 times to close the editors and the window. However if I no longer want to work on that project right now, I want to get rid of the window more quickly. Since there is a separate menu item to close the window in the File menu, I would expect it to always close the whole window, including all editors. And this is what used to happen until some time either early in this Insider cycle or the late 1.53 one, I don't remember when it started breaking exactly. Like one time I had 35 editors open and could close the whole thing down just by once selecting File/Close Window, and was done.

That's why I filed this as a regression, since this no longer works. File/Close Editor and File/Close Window now behave the same, as if I was indeed just pressing CMD+W to close a single editor.

**Comment by sbatten** [comment] 2021-02-12 18:07
@MarcoZehe I think I understand the behavior you describe and how you reproduce it, but it doesn't seem to repro for me (or @isidorn). 

1. open VS Code (latest insiders)
2. open a bunch of editors
3. use File > Close Window

This closes the window as expected over dozens of attempts

**Comment by MarcoZehe** [comment] 2021-02-12 18:18
I will try this again over the next couple of days to see if I get a pattern that reproduces it reliably. Maybe I'll attempt to do a screen recording as well.

**Comment by isidorn** [comment] 2021-02-15 11:15
@bpasero was the `File / Close Window` ever closing all the editors? I think not, right?
@marcozehe I recommend that you try out the action "Close all editors in group", might help with your flow

**Comment by bpasero** [comment] 2021-02-15 11:20
No, "File" | "Close Window" will not close editors. But I think by default we bind `Ctrl+W` to close editor as long as editors are opened.

**Comment by bpasero** [comment] 2021-02-18 07:40
It seems this issue needs more info for how to reproduce, so removing from Feb.

**Closed** 2021-02-25 11:31 UTC
Labels: accessibility, needs more info, workbench-window
