### ISSUE TITLE
Cannot Ctrl+Click to open YAML file from JavaScript file 

### ISSUE THREAD

**Issue by nmodi** [microsoft/vscode#78250] opened 2019-07-31 04:38 UTC
- VSCode Version: 1.36.1
- OS Version: Windows 10 Pro 

Steps to Reproduce:

Code: 

```
import React from 'react';
import Card from './Card';

import data from '../data/trucks.yaml';

const AllTrucks = props => {
    return (
        <Card>
            <h3>Trucks for Sale</h3>
            {data.map(truck => (
                <div>{truck.name}</div>
            ))}
        </Card>
    );
};

export default AllTrucks;
```

Importing a yaml file from inside a React Javascript file. I'm using webpack with babel and js-yaml-loader to support the ES6 imports and importing YAML, but Ctrl+Clicking on the import does not bring up the file. That function works fine on JS file imports 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-08-12 18:27
Duplicate of https://github.com/microsoft/TypeScript/issues/15146

**Closed by mjbvz** 2019-08-12 18:27 UTC
