### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by sxd111** [microsoft/vscode#81535] opened 2019-09-27 08:14 UTC
Issue Type: <b>Performance Issue</b>

Closed everything but the cpu usage is still about 20%

VS Code version: Code - Insiders 1.39.0-insider (e0762af258c0b20320ed03f3871a41967acc4421, 2019-09-27T05:26:42.235Z)
OS version: Windows_NT x64 10.0.18990

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.76GB (38.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    91	 14816	code-insiders main
    0	    54	  5928	   electron-crash-reporter
    0	   132	 10228	   window (Welcome - Visual Studio Code - Insiders)
    0	    92	 16920	     extensionHost
   10	    88	 10280	   shared-process
    0	    63	 11512	   utility
    0	   147	 14452	   gpu-process
    0	    85	 18720	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by eitland** [comment] 2019-09-27 08:34
Just to add that a datapoint that speaks against this being a duplicate of an old issue is that it happened for me as well after running upgrade half an hour ago.

I'm off to disable my extensions one by one to see if one of them are responsible, but so far this seems to be related to the latest update in insiders.

**Comment by d0ggie** [comment] 2019-09-27 08:51
I'm seeing this too, right after the very same update; shared-process eats one CPU core.

VS Code version: Code - Insiders 1.39.0-insider (e0762af258c0b20320ed03f3871a41967acc4421, 2019-09-27T05:26:42.235Z)
OS version: Windows_NT x64 10.0.18362

**Comment by GoNZooo** [comment] 2019-09-27 11:52
Seeing the same after this very last update. 1 core pinned by the shared process, disablingc extensions doesn't meaningfully impact it.

Version: 1.39.0-insider (user setup)
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:26:42.235Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18985

**Comment by jtsom** [comment] 2019-09-27 15:03
Seeing similar think here. Running on a Win 10 VM, having a high CPU in Windows is causing VMWare to max out also.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/13488/65779502-dbd14a80-e115-11e9-832f-ff123ea66bb3.png">

```

```CPU %   Mem MB     PID  Process
    0       79    4624  code-insiders main
    0      146     500     gpu-process
   16       74     812     shared-process
    0      159    6004     window (Program.cs - JsonParseTest - Visual Studio Code - Insiders)
    0       34     924       searchService
    0       76    6360       extensionHost
    0        4    3028         cmd /s /c ""C:\Users\John Tsombakos\.vscode-insiders\extensions\ms-vscode.csharp-1.21.3\                                                      .omnisharp\1.34.4-beta.7\OmniSharp.exe" -s "c:\Users\John Tsombakos\Desktop\JsonParseTest" --hostPID 6360 DotNet:enable                                                      PackageRestore=false --encoding utf-8 --loglevel information --plugin "C:\Users\John Tsombakos\.vscode-insiders\extensi                                                      ons\ms-vscode.csharp-1.21.3\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll" FileOptions:SystemEx                                                      cludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store RoslynExtensionsOptions:EnableAnalyzersSupport=true formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"                                                                                                                                              0       11    4864           console-window-host (Windows internal process)                                                                                                  0      144    9208           "C:\Users\John Tsombakos\.vscode-insiders\extensions\ms-vscode.csharp-1.21.3\.omnisharp\1.34.4-beta.7\OmniSharp.exe"  -s "c:\Users\John Tsombakos\Desktop\JsonParseTest" --hostPID 6360 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin "C:\Users\John Tsombakos\.vscode-insiders\extensions\ms-vscode.csharp-1.21.3\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll" FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store RoslynExtensionsOptions:EnableAnalyzersSupport=true formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4                     0       11    7572       watcherService                                                                                                                                      0       11    6956         console-window-host (Windows internal process)                                                                                                    0       14    8492     electron-crash-reporter

**Comment by chrmarti** [comment] 2019-09-27 19:05
Could someone seeing this on the latest VS Code Insiders open the dev tools for the shared process (`F1` > `Developer: Toggle Shared Process`), run the JavaScript profiler (smilar to https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process) and attach the profile here?

**Comment by jtsom** [comment] 2019-09-27 19:13
Hope it helps.
[CPU-20190927T191234.834Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/3664245/CPU-20190927T191234.834Z.cpuprofile.txt)

**Comment by GoNZooo** [comment] 2019-09-27 19:30
Here's another one.

[CPU-20190927T222810.cpuprofile.txt](https://github.com/microsoft/vscode/files/3664289/CPU-20190927T222810.cpuprofile.txt)

**Comment by pocesar** [comment] 2019-09-28 10:07
seeing the same

Version: 1.39.0-insider (user setup)
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:26:42.235Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/461084/65814875-1c849e80-e1be-11e9-85b9-80d8fe21f8e8.png)

nothing obvious in Resource Monitor

**Comment by velut** [comment] 2019-09-28 14:50
Status:

```
Version:          Code - Insiders 1.39.0-insider (e0762af258c0b20320ed03f3871a41967acc4421, 2019-09-27T05:26:42.235Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System):  7.90GB (3.42GB free)
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    74	 11684	code-insiders main
    0	    89	  6496	   gpu-process
   14	    98	 11716	   shared-process
    0	   128	 12128	   window (Welcome - Visual Studio Code - Insiders)
    0	    89	 12064	     extensionHost
    0	    36	  8592	       electron_node server.js
```

Shared process CPU profile (~60 seconds):

[CPU-20190928T163934.cpuprofile.txt](https://github.com/microsoft/vscode/files/3665597/CPU-20190928T163934.cpuprofile.txt)

**Comment by John-McClane** [comment] 2019-09-29 08:41
I can confirm exactly the same behavior.
The cpu usage was absolutely normal up to the 2019-09-25 release.
It all started after the 2019-09-27 update.

<details>
  <summary>System Info</summary>

CPUs	            Intel(R) Core(TM) i7 CPU Q 720 @ 1.60GHz (8 x 1596)
GPU Status	        2d_canvas: enabled
                    flash_3d: enabled
                    flash_stage3d: enabled
                    flash_stage3d_baseline: enabled
                    gpu_compositing: enabled
                    metal: disabled_off
                    multiple_raster_threads: enabled_on
                    oop_rasterization: disabled_off
                    protected_video_decode: unavailable_off
                    rasterization: unavailable_off
                    skia_renderer: disabled_off
                    surface_control: disabled_off
                    surface_synchronization: enabled_on
                    video_decode: enabled
                    viz_display_compositor: enabled_on
                    viz_hit_test_surface_layer: disabled_off
                    webgl: enabled
                    webgl2: enabled
Load (avg)	        undefined
Memory (System)	    7.99GB (3.63GB free)
Process Argv	
Screen Reader	    no
VM	                50%
</details>

<details>
  <summary>Version Info</summary>

Version: 1.39.0-insider
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:26:42.235Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
</details>

<details>
  <summary>Screenshots</summary>

![1](https://user-images.githubusercontent.com/37442959/65829377-ac554600-e2ad-11e9-9963-49cf091fa95a.jpg)
![2](https://user-images.githubusercontent.com/37442959/65829379-b1b29080-e2ad-11e9-811b-c1acf459e63c.jpg)

</details>

**Comment by offero** [comment] 2019-09-29 17:43
This just started happening to me too

![image](https://user-images.githubusercontent.com/4681330/65836494-0d394a00-e2bf-11e9-9cdc-3536eae290b8.png)

Version: 1.39.0-insider (user setup)
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:26:42.235Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by fuckFH** [comment] 2019-09-29 17:48
Same setup as offero except OS:Windows_NT x64 10.0.17134
With the same symptoms like all others.

**Comment by varadero** [comment] 2019-09-29 19:13
Exactly the same here. Started inside empty folder from command prompt  - `code-insiders . --disable-extensions`. The `shared-process` reported by `code-insiders --status` uses 100% of one of my CPU cores:

```
Version:          Code - Insiders 1.39.0-insider (e0762af258c0b20320ed03f3871a41967acc4421, 2019-09-27T05:26:42.235Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System):  7.80GB (2.99GB free)
VM:               0%
Screen Reader:    no
Process Argv:     . --disable-extensions
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       82    8972  code-insiders main
    0      127    2660     window (empty - Visual Studio Code - Insiders)
    0       57    1136       extensionHost
    0       11   12564       watcherService
    0       11    9184         console-window-host (Windows internal process)
    0       14    6932     electron-crash-reporter
   14       70    8252     shared-process
    0      103   10132     gpu-process

Workspace Stats:
|  Window (empty - Visual Studio Code - Insiders)
|    Folder (empty): 0 files
|      File types:
|      Conf files:
```


Command line of the process that uses 100% CPU:
```
"C:\Users\Svincho\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --type=renderer --disable-color-correct-rendering --field-trial-handle=1896,5753891113811261791,4998443115046434544,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=en-US --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-user-model-id=Microsoft.VisualStudioCodeInsiders --app-path="C:\Users\Svincho\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app" --node-integration --no-sandbox --no-zygote --background-color=#1e1e1e --disable-blink-features=Auxclick --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=14099556932833274872 --renderer-client-id=6 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2900 /prefetch:1
```

Here is a screenshot from Process Explorer of the thread that causes main CPU usage and its call stack:

![image](https://user-images.githubusercontent.com/7610713/65837951-20bbd380-e306-11e9-9232-bc870db22a8e.png)

**Comment by chrmarti** [comment] 2019-09-29 20:17
@John-McClane Windows User Setup for the Thursday build is [here](https://az764295.vo.msecnd.net/insider/b0d714d2de2886060e0904bf0cc774e0d70667cd/VSCodeUserSetup-x64-1.39.0-insider.exe).

Lots of `mkdirp` activity in some of the CPU profiles. Can't find a hint where this originates from.

/cc @jrieken @bpasero @sandy081

**Comment by mmacq** [comment] 2019-09-29 21:41
Same problem - 10-14% CPU usage generated by "shared-process" process.
Version: VSCode Insiders 1.39.0
CPU/GPU: Ryzen 5 2500U / integrated

**Comment by bpasero** [comment] 2019-09-30 05:43
I can reproduce and it is indeed tons of calls to `mkdirp`. @sandy081 assigning to you since I think you are the most recent person adding code to the shared process for user sync.

Unfortunately I cannot debug who is the initiator of the `mkdirp` call :(

![image](https://user-images.githubusercontent.com/900690/65852249-e0844180-e355-11e9-8536-02d712d519bf.png)

Something fishy going on with paths it seems:

![image](https://user-images.githubusercontent.com/900690/65852273-eed25d80-e355-11e9-9a13-a4705e39993a.png)

**Comment by sandy081** [comment] 2019-09-30 07:54
None of the settings sync code should be active and I do not think it makes mkdirp calls. But to be sure will investigate.

@bpasero Does these mkdirp calls are coming from file system service or directly getting called?

**Comment by bpasero** [comment] 2019-09-30 08:03
I cannot debug this unfortunately, need to try to reproduce running out of sources.

**Comment by sandy081** [comment] 2019-09-30 11:05
Looks like the culprit is the new log service i created for user data sync that is  giving an invalid path to spdlog. Fixed it.

**Closed** 2019-09-30 11:04 UTC
Labels: freeze-slow-crash, important, perf

**Comment by jtsom** [comment] 2019-09-30 11:54
Any chance of a new Insiders release, to get this fix out?

**Comment by John-McClane** [comment] 2019-09-30 12:39
> 
> 
> Looks like the culprit is the new log service i created for user data sync that is giving an invalid path to spdlog. Fixed it.

**Nope! Not Fixed!**
At least not on the 2019-09-30 build pushed out today.
Still the same issue.

<details>
  <summary>System Info</summary>

CPUs	Intel(R) Core(TM) i7 CPU Q 720 @ 1.60GHz (8 x 1596)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: unavailable_off
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	7.99GB (3.51GB free)
Process Argv	
Screen Reader	no
VM	50%

Extensions: none
</details>

<details>
  <summary>Version Info</summary>

Version: 1.39.0-insider
Commit: 601e3e0762ac93e03cfef8336be8223bf32754e1
Date: 2019-09-30T07:41:01.671Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

</details>

<details>
  <summary>Screenshots</summary>

![1](https://user-images.githubusercontent.com/37442959/65878291-69bb6880-e396-11e9-9b96-f9ef97235efd.jpg)
![2](https://user-images.githubusercontent.com/37442959/65878298-717b0d00-e396-11e9-913f-a2074b1c4e90.jpg)
![3](https://user-images.githubusercontent.com/37442959/65878306-7770ee00-e396-11e9-80bd-1128af8499da.jpg)
![4](https://user-images.githubusercontent.com/37442959/65878315-7c35a200-e396-11e9-843b-a535e52fd371.jpg)

</details>

<details>
  <summary>Shared process CPU profile (~60 seconds)</summary>

[CPU-20190930T150229.cpuprofile.txt](https://github.com/microsoft/vscode/files/3671020/CPU-20190930T150229.cpuprofile.txt)

</details>

![1](https://user-images.githubusercontent.com/37442959/65878755-79877c80-e397-11e9-8dbe-2e9742648574.jpg)
![2](https://user-images.githubusercontent.com/37442959/65878783-8c01b600-e397-11e9-91ea-8d69d430fdc2.jpg)
![3](https://user-images.githubusercontent.com/37442959/65878769-82784e00-e397-11e9-9ccb-e08de4627a95.jpg)
![4](https://user-images.githubusercontent.com/37442959/65878804-93c15a80-e397-11e9-8b8d-5af6c910fe15.jpg)





BTW, I have dug up this version from 2019-09-24, and it's working normal, cpu usage almost nil.
<details>
  <summary>Old Version Info</summary>

Version: 1.39.0-insider
Commit: 9f6a745027fc7b2a12495970f64625e24f410224
Date: 2019-09-24T05:26:22.699Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

![5](https://user-images.githubusercontent.com/37442959/65879411-67f2a480-e398-11e9-9f27-2e74dcde8cb2.jpg)
![6](https://user-images.githubusercontent.com/37442959/65879417-6c1ec200-e398-11e9-9ff2-9610524900b1.jpg)

</details>

**Comment by jtsom** [comment] 2019-09-30 12:58
That’s why I asked is a new build could be pushed out. The 9/30 build doesn’t include that fix (based on the commit I’d in the about box vs. the commit of the fix.

**Comment by sandy081** [comment] 2019-09-30 13:20
Yes its not available in latest insiders. Will release new one with the fix and let you know.

**Comment by sandy081** [comment] 2019-09-30 16:35
Released new insiders. Please check it out.

**Comment by jtsom** [comment] 2019-09-30 16:43
Seems to be better for me.
(Looks like Electron was revered back to v4 for this version too)

**Comment by sandy081** [comment] 2019-10-01 12:01
@John-McClane Electron version was downgraded because of different reasons 
- https://github.com/microsoft/vscode/issues/81516

Please provide your feedback in that issue. Thanks.
