### ISSUE TITLE
typescript always has a alert

### ISSUE THREAD

**Issue by Moriarty02** [Microsoft/vscode#20008] opened 2017-02-06 06:50 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.13.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|0.9.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|filenamecomplete|qinjia|0.0.3|
|sass-indented|robinbentley|1.3.0|
|jsx|TwentyChung|0.0.1|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.when i create a new js file ,this alert shows,like this
![xxx](http://p9.yx-s.com/d/inn/99f9e0ad/GIF.gif)

2. I tied to find the problem in my settings,  I found the setting as default;

// 指定包含要使用的 tsserver 和 lib*.d.ts 文件的文件夹路径。
  "typescript.tsdk": null,
"typescript.check.tscVersion": true

I think the problem is caused here ,i change the  value of "typescript.check.tscVersion" as false, but
it still check,so  I want to change the value of  "typescript.tsdk", but  I cant get the correct value。

**Comment by bpasero** [comment] 2017-02-06 07:27
@Moriarty02 do you work against a network share?

**Comment by Moriarty02** [comment] 2017-02-06 08:10
No,this problem makes me unable to write code with vscode,thanks

**Comment by bpasero** [comment] 2017-02-06 08:32
@Moriarty02 are you working on a folder that is on a Sharepoint drive maybe?

**Comment by Moriarty02** [comment] 2017-02-06 08:44
@bpasero  no,I close my project and find some  js files to open with vscode, it still alert

**Comment by bpasero** [comment] 2017-02-06 08:56
@Moriarty02 ok thanks, any chance you could translate the alert into english and post it here? or can you switch to english locale quickly and post another screenshot?

**Comment by Moriarty02** [comment] 2017-02-06 09:54
the alert is ：
Path “D:\software\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib ” does not point to a valid tsserver installation and will disable the typescript language function，
the second alert is ：
In the past 5 minutes, the typescript service has been unexpectedly interrupted for the last 5 times, consider enabling the bug report

![xxx](http://p7.yx-s.com/d/inn/adb6e567/xxx.jpg)

**Comment by Moriarty02** [comment] 2017-02-06 09:59
@bpasero  I tried to  disable all extentions,but no use

**Comment by bpasero** [comment] 2017-02-06 10:11
Thanks

**Comment by mjbvz** [comment] 2017-02-06 20:07
Thanks @Moriarty02. From the symptoms, this looks like a duplicate of #19814. In that case, some antivirus program was deleting VSCode's TypeScript server files. Reinstalling VSCode should fix this.

If you see this again, please add the `typescript` path mentioned in the error message to the exemption list for the antivirus program. You can also bring your own version of TypeScript: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2017-02-06 20:07 UTC
Labels: javascript, typescript
