### ISSUE TITLE
Incorrectly wrapping multibyte characters

### ISSUE THREAD

**Issue by ondrejhlavacek** [microsoft/vscode#75494] opened 2019-06-14 09:12 UTC
- VSCode Version: 1.35.1
- OS Version: macOS Mojave (10.14.5 (18F132))

Steps to Reproduce:

1. toggle word-wrap on

2. paste multibyte characters into editor 

![image](https://user-images.githubusercontent.com/497675/59497869-90f83380-8e94-11e9-853d-37596e5eb775.png)

3. move window edge so that they wrap at different byte positions

![image](https://user-images.githubusercontent.com/497675/59497883-98b7d800-8e94-11e9-9909-719e4b27c529.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2019-06-14 12:31
Maybe a duplicate of #70627. @ondrejhlavacek if it is please close this one.

**Comment by ondrejhlavacek** [comment] 2019-06-14 12:39
I don't think so, it's not about covering with scrollbar, but wrapping inside a multibyte character (see the question marks at the end of the lines in the second screenshot).

**Comment by alexandrudima** [comment] 2019-08-07 14:47
To reproduce, use the following settings:

```
"editor.wordWrap": "wordWrapColumn",
"editor.wordWrapColumn": 49,
"editor.rulers": [49]
```

and open the following content:

```
🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼🐇👬🌖🌞🏇🍼
```

The issue is about the broken `?` (not so much that the emojis overflow the 49 character limit):

![image](https://user-images.githubusercontent.com/5047891/62632616-0e8b6d80-b933-11e9-84a7-728318634bec.png)

**Closed** 2019-08-07 15:27 UTC
Labels: bug, editor-wrapping

**Comment by ondrejhlavacek** [comment] 2019-08-07 16:06
Awesome, thanks!
