### ISSUE TITLE
Swapped ESC and CapsLock keys are not detected correctly (swapping partly ignored)

### ISSUE THREAD

**Issue by MarkusH** [Microsoft/vscode#38892] opened 2017-11-21 16:53 UTC
- VSCode Version:
  - Version 1.18.0
  - Commit dcee2202709a4f223185514b9275aa4229841aa7
  - Date 2017-11-08T12:44:48.751Z
  - Shell 1.7.9
  - Renderer 58.0.3029.110
  - Node 7.9.0
  - Architecture x64
- OS Version: Arch Linux

Steps to Reproduce:

1. I run KDE. In my Keyboard system settings, I have CapsLock and Escape swapped.
1. In VSCode, open a file, type something with CapsLock turned off. You see lowercase letters as expected
1. Press `Ctrl+F` to open the quick find bar that opens at the top right of the editor window.
1. Search for something. It doesn't need to match anything in the current document
1. Press the `CapsLock` key on your keyboard (which should be mapped to Escape) to close the "find bar". *The bar stays open*.
1. Press the `ESC` key on your keyboard (which maps to CapsLock) and the "find bar" closes. However, *now CapsLock is turned on*.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-11-22 08:08
Duplicate of #23991.

**Closed by alexandrudima** 2017-11-22 08:08 UTC
Labels: keybindings

**Comment by MarkusH** [comment] 2017-11-23 18:01
Thanks for the link to the duplicate!
