### ISSUE TITLE
JavaScript prototypes - Go to def, type def, implementations refs, peek and others don't work

### ISSUE THREAD

**Issue by stephen147** [microsoft/vscode#148750] opened 2022-05-04 23:29 UTC
- VS Code Version: Version: 1.66.2
- Windows: OS: Windows 10 Pro (Build 19044)
- All extensions were disabled and restarted VSC.

# Steps to Reproduce:
Save this code to whatever.js

```javascript
var mytime = 131639508000000000;
var date = new Date((mytime-116444736000000000)/10000);

Date.prototype.yyyymmddhhmmss = function() {
var yyyy = this.getFullYear().toString();
var mm = (this.getMonth()+1).toString(); // getMonth() is zero-based
var dd = this.getDate().toString();
var hh = this.getHours().toString();
var min = this.getMinutes().toString();
var ss = this.getSeconds().toString();
return yyyy + '-' + (mm[1]?mm:"0"+mm[0]) + '-' + (dd[1]?dd:"0"+dd[0]) + ' ' + (hh[1]?hh:"0"+hh[0]) + ':' + (min[1]?min:"0"+min[0]) + ':' + (ss[1]?ss:"0"+ss[0]);
};

console.log(date.yyyymmddhhmmss());
```

If you select anywhere in the `yyyymmddhhmmss` and click on any of the things highlighted red here, they don't work.

This is really the only thing that'll prevent me from switching from Sublime Text.

![image](https://user-images.githubusercontent.com/14054664/166841334-4a9a466e-6640-44be-8f6b-2610c7a4d124.png)

# Screenshot of the problem
![image](https://user-images.githubusercontent.com/14054664/166841352-74e32314-3beb-478b-9da4-af849ae0db19.png)

**Comment by mjbvz** [comment] 2022-05-05 16:44
Duplicate of https://github.com/microsoft/TypeScript/issues/22250

**Closed by mjbvz** 2022-05-05 16:44 UTC
