### ISSUE TITLE
Terminal + WSL + Fish shows spurious characters on every line

### ISSUE THREAD

**Issue by FWest98** [microsoft/vscode#122676] opened 2021-04-29 16:32 UTC
- VS Code Version: 1.55.2 (System x64)
- OS Version: W10 20H2 x64

![afbeelding](https://user-images.githubusercontent.com/1918658/116584644-dce0e400-a917-11eb-9934-d53610b53b15.png)

See the image above. For some reason, the unique combination of VS Code on Windows + ConPTY + WSL + fish causes a spurious "h" character to appear on every line. When resizing the terminal window by just one pixel, these spurious characters disappear and everything is fine. This does not occur when:
- using bash, zsh, or any other terminal
- using fish in a different WSL install
- running VS Code on WSL Remote
- using WinPTY instead of ConPTY
- using this shell in any other terminal (Tilix on WSL, Windows Terminal, cmd.exe, or powershell.exe)
- using this shell in other IDEs (such as PhpStorm)

So I guess this must have something to do with my WSL install, since it does not happen with other shells in VS Code. But on the other hand, the characters do not seem to appear in the output when storing it to a file, and disappear after just a 1px resize, which makes me suspect VS Code. Does anyone have any idea?

The raw byte output:
```
[2m¶(B[m                                                                               
¶ 
[K[38;5;240mLinux Floris-PC 4.4.0-19041-Microsoft x86_64
 18:29:50 up 14:48,  0 users,  load average: 0.52, 0.58, 0.59
(B[m[?2004h[30m(B[m]0;fish ~
(B[m[38;5;247m[48;5;236m [1m[38;5;231m[48;5;236m~ (B[m[38;5;236m (B[m[K[42C[38;5;240m Thu 29 Apr 2021 06:29:50 PM CEST(B[m
[47C
[5C
[30m(B[m[2m¶(B[m                                                                               
¶ 
[K[?2004h[30m(B[m]0;fish ~
(B[m[38;5;247m[48;5;236m [1m[38;5;231m[48;5;236m~ (B[m[38;5;236m (B[m[K[42C[38;5;240m Thu 29 Apr 2021 06:29:52 PM CEST(B[m
[47C
[5C
[30m(B[m[2m¶(B[m                                                                               
¶ 
[K[?2004h[30m(B[m]0;fish ~
(B[m[38;5;247m[48;5;236m [1m[38;5;231m[48;5;236m~ (B[m[38;5;236m (B[m[K[42C[38;5;240m Thu 29 Apr 2021 06:29:53 PM CEST(B[m
[47C
[5C
[30m(B[m[30m(B[m[?2004l
```
[test.txt](https://github.com/microsoft/vscode/files/6400187/test.txt)

**Comment by Tyriar** [comment] 2021-04-30 13:57
I guess the h is coming from `fish ~`. Unconfirmed.

**Comment by FWest98** [comment] 2021-04-30 14:01
That might be, but I guess that is a rendering bug then? Strange that it would only catch the `h`, because this doesn't happen in any other terminal.

**Comment by Tyriar** [comment] 2021-04-30 14:03
It could have something to do with https://github.com/microsoft/vscode/issues/119204, or your set of zsh plugins?

**Comment by FWest98** [comment] 2021-04-30 14:13
Unfortunately, that doesn't seem to be related. The strange thing is that when working in the WSL Remote via the extension, I have no problems at all. This only recently appeared after upgrading VS Code from 1.49 while also upgrading my WSL distro 18.04->20.04, but I don't know which of the two caused it.

Additional observations:
- When terminating a line with Ctrl+C it does not show the extra character
- Any visual reload of the terminal causes the characters to disappear (changing the local echo setting for example)
- Sometimes it also shows an `l`: when running a command, a spurious `l` will show at the beginning of the command line (it does not show before pressing enter, it appears after pressing enter)

![afbeelding](https://user-images.githubusercontent.com/1918658/116707511-0c9ef300-a9cf-11eb-82c8-3c63e5fdb213.png)

**Comment by AlansCodeLog** [comment] 2021-05-27 21:01
I'm also having this exact same problem. Don't remember since how long ago since I kept ignoring it and I've had problems on/off with fish themes, but I took the time and checked that it was still happening with a vanilla fish install. I'm on a Arch WSL 1.0 distro if that helps and it only happens when accessing WSL without the Remote WSL, which I do a lot because I have a bunch of helpful functions written in fish but might not necessarily be developing in wsl.

**Comment by Tyriar** [comment] 2021-06-02 13:48
Disabling local echo might help this: `"terminal.integrated.localEchoLatencyThreshold": -1`

**Comment by AlansCodeLog** [comment] 2021-06-02 22:20
@Tyriar Thanks, but I just tried it and it doesn't work ☹️. Also what is that setting about? I read it's description but what does it mean by server? ssh? or is it talking about something related to the remote wsl extension?

**Comment by Tyriar** [comment] 2021-06-02 22:25
@AlansCodeLog if input/output latency is high (default is 30ms I think), it will attempt to echo what you type locally. This applies to connecting via `ssh` in the terminal or using a remote extension

**Comment by layyne** [comment] 2021-07-13 08:55
Having an identical issue (with the same two characters, `l` and `h`). It seems that the only time an `l` appears is when a command is entered while a fish autosuggestion is pending, and it usually appears on the same line as that prompt/command, though it appears on the next line right next to the `h` when any sequence of only space characters is entered as a command. The `h` indeed always appears, sometimes following a command's output and sometimes on the first line of output (either preceding or following that line).

**Comment by AlansCodeLog** [comment] 2021-07-13 16:18
I think you might be on to something, I'm getting something similar, but mine changes to `powershell` ??? I saw this the other day while the shell was loading and thought VS Code was confused or something, but now I see it happens on executing any command and coincides like you say with the characters printed. This is not on a clean fish install though, just checked on my current one real quick, but I can't think of anything powershell related it could have.

I can't seem to replicate the other stuff, maybe I'm doing it wrong, but both letters always seem to appear to me. The only other thing I
can confirm is they don't appear when pressing `Ctrl+C`.

**Comment by meganrogge** [comment] 2021-10-13 17:24
I'm not able to reproduce the issue, so believe the problem has been fixed upstream in conpty, which you'll see when you update windows. 
![test](https://user-images.githubusercontent.com/29464607/137182771-84283b4f-117e-439d-8203-12dbd0923dc8.PNG)

**Comment by Tyriar** [comment] 2021-10-13 20:54
@FWest98 something really weird is going on with your shell, looking at the byte output you pasted in:

```
�[K�[?2004h��[30m�(B�[m�]0;fish ~
�(B�[m�[38;5;247m�[48;5;236m �[1m�[38;5;231m�[48;5;236m~ �(B�[m�[38;5;236m �(B�[m�[K�[42C�[38;5;240m Thu 29 Apr 2021 06:29:53 PM CEST�(B�[m
�[47C
�[5C
�[30m�(B�[m�[30m�(B�[m�[?2004l
```

That is:

1. `�[K` Clear the line
2. `�[?2004h` Enable bracketed paste mode
3. Bunch of content...
4. `�[?2004l` Disable bracketed paste mode

The really weird thing is around the h and l sequences, bracketed paste mode is only meant to go from the terminal frontend to the backend such that processes are able to know the difference between text that is copied and that which is pasted.

Some questions, sorry if they have already been asked as the issue is quite long:

- Which WSL distro was this?
- You say it doesn't happen when using Remote - WSL, can you clarify what you meant by "Windows + ConPTY + WSL"? Are you running wsl.exe, or pwsh.exe and running wsl inside that?
- Do you know of anything in fish that leverages bracketed paste mode?
- Have you customized the shell at all?
- How did you capture the byte output?

**Comment by FWest98** [comment] 2021-10-13 21:36
Thank you for looking into this! I'm happy to answer these questions.

- Ubuntu 18.04, manually upgraded to 20.04 (which is when this issue started; but at the same time I updated VS Code from 1.49 to 1.55)
- It does not happen when using the Remote plugin and connecting to WSL (so the terminal connects to fish directly, I presume). It does happen when running VS Code locally on Windows; it does not matter whether I start wsl inside `cmd.exe` or `pwsh.exe`, or run wsl directly from the terminal dropdown. So in terms of process layout; the tree in the green square works fine (running terminal inside a Remote WSL session), while both tress in the red square do not work (running "locally")
![Naamloos](https://user-images.githubusercontent.com/1918658/137214202-f7010334-e223-4fc7-a781-156f3a3fe907.png)
- I don't know what bracketed paste mode means, so I'm not sure whether I can answer that question
- This problem occurs even without any modifications to my shell (and these are limited to the shebang contents)
- I ran `wsl > output` in `cmd.exe`; I am not sure whether this is the correct way to do so. If you have any other way, please let me know and I will report back.

Some more information I can think of:
- This problem does not occur in Windows Terminal
- This problem does not occur in Jetbrains IDEs terminal window
- I believe these extra characters are not actually in the shell output anywhere; as soon as I run `nano`, `clear`, `htop`, etc; or as soon as I resize the terminal window, or change any other setting about it, these artifacts disappear.

**Comment by Tyriar** [comment] 2021-10-13 21:46
It's looking more and more like an issue in conpty that is fixed in Windows Terminal/later Windows as @meganrogge suggested, which we wouldn't be able to action unfortunately.

What I was thinking was maybe we're not handling the bracketed paste mode sequences coming the other direction and wrongly printing it, echoing it out seems to work:

![image](https://user-images.githubusercontent.com/2193314/137216930-03342641-f5c8-4c87-a3dd-a69097be22f3.png)

> I am not sure whether this is the correct way to do so. If you have any other way, please let me know and I will report back.

Could you try enabling escape sequence logging to make sure this bracketed paste mode isn't caused randomly by `wsl > output`? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by FWest98** [comment] 2021-10-13 21:57
Interesting test. Manually echoing these characters do trigger the issue - but only in fish. When running bash, this works just fine.
![afbeelding](https://user-images.githubusercontent.com/1918658/137217748-668fba52-0f64-4076-9480-744884d283b0.png)

As for the escape logging, I get this for every time I simply press <kbd>enter</kbd>
![afbeelding](https://user-images.githubusercontent.com/1918658/137218127-0bf0c4b0-ecf0-4d32-bc1d-b94d38efef52.png)

**Comment by AlansCodeLog** [comment] 2021-10-16 16:10
I'm on Windows 10 21H1 still and was not planning on updating to 11 for a while probably, but if it's possible to go back after updating I might give it a try just to see if it fixes this issue.

Not sure what all these characters are about but if I do `echo -e '\x1b[2004ltest \x1b[2004htest'` usually I get `test test`, but sometimes I get extra characters though it seems I have to hit enter between some attempts for it to happen and it takes a while. When it doesn't add extra characters, if the console is slow enough (at the start usuall), I temporarily see `llt` which is then replaced by the correct `test test`.

Here's what my terminal and the output looked like, sorry for the length, but it's hard to replicate and I'm not sure if previous output could have something to do with it.

```
h/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯

h/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

h/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
llthest test
h
 /mnt/t/Code/folder
❯
```
And the corresponding console output

```
xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[2;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[6;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[16;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[20;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data es
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data [K
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[30;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data e
LogService.ts:62 xterm.js: parsing data s
LogService.ts:62 xterm.js: parsing data t
LogService.ts:62 xterm.js: parsing data h
test test[K
[K
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[37;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[44;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[51;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[55;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hh
test test[K
[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data [m[35m
❯[m[K[1C
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h[K

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data 
LogService.ts:62 xterm.js: parsing data [m
[35m❯[m[K[1C
LogService.ts:62 xterm.js: sending data "echo -e '\x1b[2004ltest \x1b[2004htest'" (39) [101, 99, 104, 111, 32, 45, 101, 32, 39, 92, 120, 49, 98, 91, 50, 48, 48, 52, 108, 116, 101, 115, 116, 32, 92, 120, 49, 98, 91, 50, 48, 48, 52, 104, 116, 101, 115, 116, 39]
LogService.ts:62 xterm.js: parsing data echo 
LogService.ts:62 xterm.js: parsing data [25l[38;2;0;95;215m[61;3Hecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[?25h
LogService.ts:62 xterm.js: sending data "
" [13]
LogService.ts:62 xterm.js: parsing data [m
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data llt
LogService.ts:62 xterm.js: parsing data hest test
LogService.ts:62 xterm.js: parsing data 

LogService.ts:62 xterm.js: parsing data h

LogService.ts:62 xterm.js: parsing data [34m/mnt/t/Code/folder[K
LogService.ts:62 xterm.js: parsing data 
LogService.ts:62 xterm.js: parsing data [m
[35m❯[m[K[1C
```

Even stranger when I resize my window, the extra characters (not all but most) are removed!
Terminal changes to look like:

```
h/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯
h
/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯

/mnt/t/Code/folder
❯ echo -e '\x1b[2004ltest \x1b[2004htest'
test test

/mnt/t/Code/folder
❯
```


And console output logs like it seems to reparse the whole section or something, the relevant output is I think this:

```
xterm.js: parsing data [25l[35m[H❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[m
[K[34m
/mnt/t/Code/folder[K[35m
❯[m [38;2;0;95;215mecho[m [38;2;0;175;255m-e[m [38;2;135;135;0m'\x1b[2004ltest \x1b[2004htest'[K[m
test test[K
[K[34m
/mnt/t/Code/folder[K[35m
❯[K[1C[?25h
```

Hope that helps. I'll report back if I decide to try W11.

Note: I'm using fish with some customizations here, didn't have time to try a fresh install, but I had tested this previously with a fresh install and was running into the same issue.

**Closed** 2021-10-18 20:03 UTC
Labels: needs more info, terminal, windows, terminal-conpty
