### ISSUE TITLE
Can't save Julia Jupyter notebook as html

### ISSUE THREAD

**Issue by Bob-McCrory** [microsoft/vscode#128680] opened 2021-07-14 17:34 UTC
This feature is absent in the daily build of 7/14/21, and I use it frequently.

**Comment by joyceerhl** [comment] 2021-07-15 05:32
@Bob-McCrory Are you saying that the export button isn't in the toolbar? If so, that's the same problem as https://github.com/microsoft/vscode/issues/128681 Should be fixed in tomorrow's VS Code Insiders build. If something else, please let us know. Sorry for the inconvenience!

**Comment by Bob-McCrory** [comment] 2021-07-15 15:25
Thank you so much for your reply. Not only was it not in the toolbar, but I also couldn't find it anywhere else. Wouldn't it be a good idea to have anything in the toolbar also available in the menu? I'm not a UI expert, but I would think this might warrant consideration.

Thanks again for your reply.


Bob

Robert T. McCrory, FSA
1532 East McGraw Street
Seattle, WA 98112-2134
206-323-7312
***@***.******@***.***>


________________________________

**Comment by joyceerhl** [comment] 2021-07-15 15:52
@Bob-McCrory The export button disappearing was not intentional, should already be back in today's Insiders builds, and was caused by a bug in VS Code. The export button is only shown when the current workspace is trusted, and there is a context key provided VS Code that we use to determine that; that context key's state was briefly incorrect, causing the export button to be hidden when it should have been displayed. I hope that helps to clarify.  

![image](https://user-images.githubusercontent.com/30305945/125818322-38ada805-fd42-4816-9af3-c5e33a28c959.png)

**Closed** 2021-08-06 11:24 UTC
Labels: needs more info
