### ISSUE TITLE
Feature Request: Different Icons or colors for public vs private vs protected methods in the Outline view

### ISSUE THREAD

**Issue by battarro** [Microsoft/vscode#61239] opened 2018-10-18 13:27 UTC
On the outline view, will it be possible to have different icons or colors for different method signatures?
for example in this image, the top method is public, but the second method is private.
![image](https://user-images.githubusercontent.com/10959815/47157707-eead8f00-d2b7-11e8-94e0-c46126bb384a.png)

maybe a simple color change will suffice. Same icon different color,

**Comment by jrieken** [comment] 2018-10-22 11:56
/duplicate of https://github.com/Microsoft/vscode/issues/49995

**Closed by jrieken** 2018-10-22 11:56 UTC
Labels: outline
