### ISSUE TITLE
React lifecycle method suggestions aren't work with es6

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#25803] opened 2017-05-03 01:57 UTC
- VSCode Version: 1.11.2
- OS Version: Windows 7

Steps to Reproduce:

1. When write React Component with es5 there is a suggestion of React lifecycle method.
2. Now Facebook suggest developers use es6 instead of es5, and the createClass method is deprecated.
3. When I rebuild my app with es6, there is no suggestion of React lifecycle method.

**Comment by mjbvz** [comment] 2017-05-03 16:53
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/7158 

If this is not the case, please provide a code example that demonstrates the issue, along with explaining the expected behavior

**Closed by mjbvz** 2017-05-03 16:53 UTC
Labels: duplicate, javascript, typescript, upstream
