### ISSUE TITLE
Npm task autodetect should contribute install & update even if no script section is present

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27923] opened 2017-06-02 13:10 UTC
- VSCode Version: 1.13
- OS Version: Windows

I got npm install showng up after I added a script section. IMO install and update should show up if the package.json has a dependencies or devDependencies section.

**Comment by egamma** [comment] 2017-06-06 06:55
Duplicate of #27923

**Closed by egamma** 2017-06-06 06:55 UTC
Labels: bug
