### ISSUE TITLE
SCM: Focus on SCM View incorrectly focuses a dummy "Initialise Repository" view

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#96064] opened 2020-04-24 14:27 UTC
```
Version: 1.45.0-insider
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T07:46:52.128Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

> This problem does **not** reproduce on VS Code 1.44.2 (stable).

When I use the command `Source Control: Focus on Source Control View`, the SCM view focuses the "Initialise repository" view which was not there before. Video attached.

Steps to Reproduce:

1. Reload VS Code and confirm the currently open folder is a git repository
1. Check that the SCM view looks normal
1. From command palette, pick `Source Control: Focus on Source Control View`
1. Observe a completely new view being created and focused, with the "Initialise repository" button

[vscode-focus-on-scm-view.mov.zip](https://github.com/microsoft/vscode/files/4529468/vscode-focus-on-scm-view.mov.zip)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by sbatten** [comment] 2020-04-24 17:35
partially by design, the command you are running is intended to focus that view. we should probably unregister the welcome views when they are hidden however to remove this command. maybe it used to but a recent change broke it. 

what's worse however is that if you then try to hide that view with the context menu, it duplicates forever

**Comment by robertrossmann** [comment] 2020-04-24 21:14
Well, not sure what the original intent for this command was, but I was looking for a way to bind a keybinding which would take my keyboard focus to the list of changed files in the SCM view. I have a keybinding to open the SCM view and focus the commit message input, but it takes additional `tab` press to get to the list.

And, yeah... I could not figure out how to get rid of that "Initialise repository" view after I got it to show up. 🤔

**Comment by sandy081** [comment] 2020-04-27 07:22
I do not think this welcome view/command shall be shown/available from command pallete when the repositories view is shown. I will investigate this.

@joaomoreno Actual request from user is to have a command to focus repository changes view.

**Comment by sandy081** [comment] 2020-04-27 13:20
Fixed removing the focus command. Also fixed the model and view to respect active view descriptors.

**Comment by joaomoreno** [comment] 2020-04-27 14:02
That view should not be there at all!

**Comment by sandy081** [comment] 2020-04-27 15:27
Yes.

I reassigned to you because user actually wants - to have a command to focus the list in the changes view.

@robertohuertasm Please create a separate issue for this request. I am closing this for the fix I did here.

**Closed by sandy081** 2020-04-27 15:27 UTC
Labels: bug, workbench-views

**Comment by isidorn** [comment] 2020-04-30 12:27
This behaves normal for me now. There is "Source control: Focus on REPO_NAME view". And that one does not open the SCM Welcome view.
@robertrossmann if you see issues with latest vscode insiders please let us know. Thanks!
