### ISSUE TITLE
Keyboard option swap esc and caps not respected in editor

### ISSUE THREAD

**Issue by the0val** [microsoft/vscode#103357] opened 2020-07-26 10:49 UTC
Issue Type: <b>Bug</b>

I have swapped escape and caps lock to make vim use more comfortable. In VS Code not all uses of the escape key work with the remapping. It seems like escape it's the editor that's broken.

__Reproduction:__
1. Run linux with KDE Plasma.
2. Go to `System Settings > Input Devices > Keyboard > Advanced > Caps Lock Behaviour > Swap Esc and Caps Lock` and check that box.

__Some things that don't work:__
* Escape to close an auto complete list.
* Escape to cancel a selection.
* Escape to cancel multiple cursors.

__Some things that do work:__
* Closing command palette
* Canceling creating a new file

Top of command `Developer: Inspect Key Mappings`
```json
Layout info:
{
	"model": "pc86",
	"layout": "us,se",
	"variant": "dvp,svdvorak",
	"options": "caps:swapescape",
	"rules": "evdev"
}
isUSStandard: true
```

VS Code version: Code - OSS 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-18T16:10:16.658Z)
OS version: Linux x64 5.7.10-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.29GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by KevinBuchs** [comment] 2020-07-29 20:26
I noticed a similar issue, with Caps Lock and Control swapped on Ubuntu 18.04, with Version 1.48.0-insider and the prior version. 

The key shortcuts in Code for, e.g. copy and paste are shown as Control-C and Control-X. When I press the key, I get the status bar message: "The key combination (Ctrl+CapsLock, Ctrl+V) is not a command."  If I got redo the key shortcut, it shows Ctrl+CapsLock Ctrl+V in the keyboard shortcut listing.

**Comment by DLehenbauer** [comment] 2020-08-06 21:50
Confirmed in Ubuntu 20.04.  

An easy repo that works in most distros:
```
/usr/bin/setxkbmap -option "caps:swapescape"
```
Users must dismiss popups, etc. by pressing the _physical_ [Esc] key, but this also has the effect of simultaneously toggling caps-lock.

**Comment by alexdima** [comment] 2020-08-06 22:04
Have you seen https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings , specifically:

![image](https://user-images.githubusercontent.com/5047891/89587261-95726f00-d841-11ea-8773-dda52434cd9a.png)

**Comment by DLehenbauer** [comment] 2020-08-06 22:40
Confirmed dupe of #23991.

(...and the workaround works, thank you!)

**Closed** 2020-08-07 07:08 UTC
Labels: keybindings, linux, needs more info
