### ISSUE TITLE
Dedupe identical suggestions

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#16040] opened 2016-11-24 21:26 UTC
Hello, VS Code team!

/cc @aeschli — because he's God of the CSS service in VS Code
/cc @Tyriar — because I know that he uses the `vscode-scss` and may regard the proposal as a user
/cc any VS Code team members and users

I am the creator of two very useful (😅) plugins: [vscode-less](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) and [vscode-scss](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss).

These plugins provide more informative suggestions for Less and Sass symbols (such as Variables, Mixins and Functions) from all files in the workspace (including `@import` and `// <reference...>` comments).

And it would be nice if users could **disable the standard suggestions** for Symbols because they have duplicates.

For example, Variables in Less:

![photoshop_2016-11-24_23-57-31](https://cloud.githubusercontent.com/assets/7034281/20609941/c3e7dbc6-b2a3-11e6-94d7-4bfc8e89133d.png)

And Functions in Sass:

![code - insiders_2016-11-25_00-03-30](https://cloud.githubusercontent.com/assets/7034281/20609943/d0146bee-b2a3-11e6-9562-3373b81f0aad.png)

**For users**. Please, use GitHub emotions:

👍 - upvote
👎 - downvote

**Comment by jrieken** [comment] 2016-11-25 09:58
We should maybe just dedupe identical suggestions

**Comment by mrmlnc** [comment] 2016-11-25 10:01
Yes, I thought about it. But this can cause performance degradation.

**Comment by aeschli** [comment] 2016-11-25 10:07
@mrmlnc Your extension could choose to replace the built-in css completions by contributing to a stronger document selector. 
Or you play together with the built-in extension and don't make proposals for variables defined locally. I'm happy to take pull requests to improve my proposals. Also feel free to suggest hooks to the css-languageservice that you could use to give your extra proposals. 

Adding more configuration option to css to doesn't make things easier.

**Comment by mrmlnc** [comment] 2016-11-25 10:50
@aeschli,

My extensions provide completion for all Symbols in:

  * Current workspace (used my own parser: [less-symbols-parser](https://github.com/mrmlnc/less-symbols-parser) and [scss-symbols-parser](https://github.com/mrmlnc/scss-symbols-parser))
  * Current document (used your parser from [vscode-css-languageservice](https://github.com/Microsoft/vscode-css-languageservice) because it works with incomplete or broken code). Only for nested symbols (from selectors) such as:

    ```less
    .test {
      @a: 1;
      .selector {
        content: | // @a
      }
    }
    ```

Hmm, yeah, I don't thought about removing suggestions for the current document. This sounds reasonable.

Now I use [parser/mixin.ts](https://github.com/mrmlnc/vscode-scss/blob/master/src/parser/mixin.ts) and [parser/variable.ts](https://github.com/mrmlnc/vscode-scss/blob/master/src/parser/variable.ts) to generate suggestions from the current document. It seems to me, that this must easily integrate into your service.

However, there are problems: What to do with Functions and Mixins? —  because my extensions have **SignatureHelp** and **Hover** for Function/Mixin reference and variables + parameters. Also implement this feature?

**Comment by mrmlnc** [comment] 2016-11-27 10:07
@aeschli,

Small clarification:

  1. Where better to continue communicating: here or in the `vscode-css-languageservice` repository?
  2. If the variable does not have a default value (`FunctionParameter`), then display `null` or nothing?

**Comment by aeschli** [comment] 2016-11-28 14:50
@mrmlnc For pull requests, use vscode-css-languageservice. Bug reports/feature requests better here where historically we manage all css/less/scss related issues. 
I'd suggest to show nothing if there is no default value. Also a label 'no default value' would be an option but looks to intrusive to me.

**Comment by jrieken** [comment] 2017-04-13 13:17
I am closing this as a dupe of #17068

**Closed by jrieken** 2017-04-13 13:17 UTC
Labels: debt, suggest
