### ISSUE TITLE
Format on paste feature removes inserted string

### ISSUE THREAD

**Issue by timocov** [microsoft/vscode#144658] opened 2022-03-08 09:45 UTC
Issue Type: <b>Bug</b>

1. Enable "Format on paste" setting
2. In a typescript file paste string in quotes

=> editor removes inserted string. if you undo then you'll see inserted string

![vscode-format-on-paste](https://user-images.githubusercontent.com/3112183/157210730-d6340fbf-35fd-4ef1-ae7c-52e52a81a468.gif)

<details>
<summary>Code from gif</summary>

```ts
class Foo {
    public bar(arg: string): string[] {
        return [];
    }
}

function func(): void {
    const foo = new Foo();
    foo.bar('').push('');
}
```
</details>

VS Code version: Code - Insiders 1.66.0-insider (45b4204501ac1f50b6231af3c996d35f86359ecd, 2022-03-08T05:15:31.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.67GB free)|
|Process Argv|--crash-reporter-id 11681bbe-6fa9-4a86-a82f-8eb0c752dc92|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vsbas813:30436447
vscscmwlcmc:30428972
azactmsal:30432848
vscgsvid1:30433757
dockersurvey3cf:30438169
pynewfile477:30443519

```

</details>

**Comment by bpasero** [comment] 2022-03-08 10:28
Duplicate of https://github.com/microsoft/TypeScript/issues/48006

**Closed** 2022-03-08 19:40 UTC
Labels: upstream, *duplicate
