### ISSUE TITLE
[web] Folder selector not working as intended on Firefox

### ISSUE THREAD

**Issue by EnKrypt** [microsoft/vscode#84382] opened 2019-11-09 14:43 UTC
I am running VS Code remotely via [`code-server`](https://github.com/cdr/code-server)

* `code-server` version: 2.1485-vsc1.38.1
* OS Version: Arch Linux (rolling release)

Coming from issue: [code-server#1063](https://github.com/cdr/code-server/issues/1063)

![](https://user-images.githubusercontent.com/1106939/66378960-2f734c00-e9d2-11e9-8f8e-bedc225a0b26.gif)

The folder selector seems to be very glitched, making it near impossible to open the folder I want.

Specifically, one of the main bugs seems to be that selecting a folder by left clicking or hitting return on a dropdown entry, does not reflect on the path in the bar.

As such, the "OK" button does not work as intended either.

This bug is consistently reproducible.

**Comment by EnKrypt** [comment] 2019-11-27 04:02
It's been a while. Any updates?

**Comment by alexr00** [comment] 2019-11-28 09:05
duplicate of https://github.com/microsoft/vscode/issues/83292

**Closed** 2019-11-28 09:05 UTC
Labels: *duplicate

**Comment by EnKrypt** [comment] 2019-11-28 10:20
@alexr00 I'm a bit confused here. The dupe points to an issue that has been resolved. Does that mean you expect this issue to be resolved in a specific version?

**Comment by EnKrypt** [comment] 2019-11-28 10:21
@alexr00 I'm a bit confused here. The dupe points to an issue that has been closed. Does that mean I can expect this issue to be resolved in a specific version?

**Comment by alexr00** [comment] 2019-11-28 12:14
The issue is fixed in VS Code. You can check out our test playground here: https://vscode-web-test-playground.azurewebsites.net/
