### ISSUE TITLE
Badges in custom views and containers

### ISSUE THREAD

**Issue by kubawolanin** [microsoft/vscode#38426] opened 2017-11-15 16:22 UTC
Follow up to https://github.com/Microsoft/vscode-extension-samples/issues/41

As a ~~user~~ extension developer I'd like to be able to display a "countBadge" in the TreeView label.
My use case scenario - I have two TreeViews filled with data from a given REST API response.
I'd like to know how many items are in the tree.

See the following screen demonstrating [openHAB extension](https://marketplace.visualstudio.com/items?itemName=openhab.openhab).

![](https://i.imgur.com/SZkmQCt.gif)

A badge like that is visible e.g. in the Git extension:
![](https://user-images.githubusercontent.com/2270505/32796947-785e8652-c970-11e7-8b6f-27167b8854bf.png)

Thank you for your hard work!

**Comment by fabiospampinato** [comment] 2017-11-17 00:27
This could be useful. 

@kubawolanin in the meantime you may display them as text, like `(1)` or `(3)` for instance. They could probably also be vertically aligned just by adding some spaced before them.

**Comment by Gruntfuggly** [comment] 2018-05-15 11:43
Now that views can be placed in custom containers, it would also be nice to have bades for the containers.

**Comment by sandy081** [comment] 2018-08-15 15:05
Duplicate of #47502 and #54938

**Comment by sandy081** [comment] 2018-08-15 15:06
Decorations support (including badges) for file resources is supported. Requires #54938 for non file based resources

**Comment by sandy081** [comment] 2020-09-29 10:43
I am really sorry that I do not remember why I made this as a duplicate of file decorations API. 

Reopening it for badges support in custom views and view containers.

**Comment by alexr00** [comment] 2020-11-06 14:13
Duplicate of https://github.com/microsoft/vscode/issues/62783

**Closed by alexr00** 2020-11-06 14:13 UTC
Labels: explorer-custom, feature-request
