### ISSUE TITLE
A11y_VSCode_ReadingDetailsOnSpecificExtension_Keyboard: Actionable control are not focusable using keyboard

### ISSUE THREAD

**Issue by prasadaps** [microsoft/vscode#76702] opened 2019-07-05 10:18 UTC
**Environment Details:**
VSCode Version : 1.36.0
OS Version : Win10
NVDA 2019.1.1

**Additional Details:**
MAS Violated : MAS 2.1.1

**Repro Steps:**
1.Open Visual studio code editor.
2.Using "Ctrl+Shift+X" key navigate to the extension side view bar option.
3.Using Tab key navigate to the "More" option and select different options( "Show installed Extension, Show outdated extension, Show popular Extension,Etc")
4.Click on any installed extension
5.Try to read all the details about specific extension 

**Actual:**
Focus is not going on the links(Rating, Repository,License ) available on the screen.

This issue is observed in Chrome + NVDA

**Expected**:
Focus should be go on the link's.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Keyboard and screen reader user will face difficulty to access this controls. 

**MAS Reference:**
MAS 2.1.1 - https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachment For Reference:** 
[A11y_VSCode_ReadingDetailsOnSpecificExtension_Keyboard_ActionableControlAreNotFocusable.pptx](https://github.com/microsoft/vscode/files/3362247/A11y_VSCode_ReadingDetailsOnSpecificExtension_Keyboard_ActionableControlAreNotFocusable.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2019-07-08 09:10
Fixed in latest and duplicate of https://github.com/microsoft/vscode/issues/61616

**Closed by isidorn** 2019-07-08 09:10 UTC
Labels: extensions
