### ISSUE TITLE
workbench.action.gotoSymbol do not support vue file

### ISSUE THREAD

**Issue by dyceit** [microsoft/vscode#105705] opened 2020-08-31 07:16 UTC
Issue Type: <b>Feature Request</b>

cmd+shift+o workbench.action.gotoSymbol do not support vue file，not show the var and func in export default .

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.3.0

**Comment by IllusionMH** [comment] 2020-08-31 16:14
/causedByExtension

Functionality for `.vue` files is provided by extension and not VSCode itself.
Duplicate of https://github.com/vuejs/vetur/issues/2058 and https://github.com/vuejs/vetur/issues/1849. See these issues for fix

**Closed** 2020-08-31 16:15 UTC
Labels: *caused-by-extension, *english-please, needs more info, translation-required-chinese-simplified
