### ISSUE TITLE
File with complete match is not shown first in Quick open

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11178] opened 2016-08-30 09:33 UTC
Testing #11106 

1. Assume that you have two files **color.ts** and **color.test.ts**
2. Open **color.test.ts** so that it will be in Recently opened list
3. In Quick open type color.ts

Expected: First match should be **color.ts** file
Observed: **color.test.ts** from Recently opened sections is shown first

![screen shot 2016-08-30 at 11 33 02](https://cloud.githubusercontent.com/assets/10746682/18083913/8cc25b04-6ea5-11e6-9126-570e423f970a.png)

**Comment by bpasero** [comment] 2016-08-30 09:41
We always show history results first and then global file results. Closing as designed because I am not feeling good changing this behaviour.

**Closed by bpasero** 2016-08-30 09:41 UTC

**Comment by sandy081** [comment] 2016-08-30 12:48
@bpasero I do not think we always show history results first is true. We push recently opened files down based on the match score. See this video

![aug-30-2016 14-47-35](https://cloud.githubusercontent.com/assets/10746682/18089537/baf8cac4-6ec0-11e6-8c21-6db9417d9af2.gif)

**Comment by bpasero** [comment] 2016-08-30 12:52
@sandy081 here is how it works:
* there are 2 sources (3 actually when you enable to show symbols now in quick open) that contribute to the list
* the editor history source always comes first on top of all other results for some reasons: it is instant in terms of search speed so we show it before any other result shows up and it also is a good indicator of relevance because the user opened it once
* the file (and symbol results if enabled) always come below second and are sorted individually based on your search value but they never move on top of the editor history results. as soon as there are no history results, the history results bucket goes away and you only see file results

Hope that makes it more clear.

**Comment by bpasero** [comment] 2016-08-30 13:23
This seems to be https://github.com/Microsoft/vscode/issues/10690
