### ISSUE TITLE
Quick Fix feature of ESLint has stopped working in latest June 2109 update

### ISSUE THREAD

**Issue by kswamy15** [microsoft/vscode#77553] opened 2019-07-18 04:35 UTC
I just upgraded to the June 2019 version and the ESLint Quick Fix selection to repair errors is not working. When you have an error in the code, it is redlined. When you right click the redlined code, shows a Quick Fix tab that comes up with many options. One of the option would be a solution to the Fix the error (like Fix no Trailing spaces) and the others would be eslint code to ignore the error. When you choose any of the choices, it doesn't do anything. so the Quick Fix of ESLint extension in VS code has stopped working in the latest update. This is very frustrating.

- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-07-18 22:25
Duplicate of #77018

**Closed by mjbvz** 2019-07-18 22:25 UTC
