### ISSUE TITLE
slow down when lots of output is written to debug console. 

### ISSUE THREAD

**Issue by josephRice** [Microsoft/vscode#19678] opened 2017-02-01 16:03 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.6.2|
|PowerShell|ms-vscode|0.8.0|
|sublime-keybindings|ms-vscode|1.6.1|

---

Steps to Reproduce:

1.  Write a application that logs thousands of lines in a single run.   Say 25,000 to 35,000 outputted log messages.
2.  run that application several times in a row.  
3.  watch vscode slow down, to the point you can't click on anything.      

Workarounds:   

1. Periodically clear the console manually.
2.  close vscode window and start another one. 

Possible solution:   

1. Limit the # of scroll back lines in the console.   So that you use a finite amount of ram.   
2. automatically clear the console at the start of the next debug execution.

**Comment by isidorn** [comment] 2017-02-02 09:30
@josephRice thanks for the nice steps and ideas on how to solve this. However we already do 2. - we clear the console at the start of each debug session. If that is not the case for you then this is clearly a bug
As for the slow down issue, this is basically a duplicate of https://github.com/Microsoft/vscode/issues/11462

**Closed by isidorn** 2017-02-02 09:30 UTC
