### ISSUE TITLE
Exception while running a task in the terminal

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26926] opened 2017-05-19 09:24 UTC
- VSCode Version: master
- OS Version: Windows 10

Steps to Reproduce:

1. Run a task in the terminal without having the terminal open

I get:

![capture](https://cloud.githubusercontent.com/assets/1931590/26241649/b8cf91d6-3c85-11e7-9965-988da79a5b1d.png)

**Comment by dbaeumer** [comment] 2017-05-26 13:31
@Tyriar this is actually preventing me from making the terminal the default. Could you please have  a look?

**Comment by Tyriar** [comment] 2017-05-26 16:26
@dbaeumer cannot reproduce, I tried under the following environment:

- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|EditorConfig|EditorConfig|0.9.3|
|git-project-manager|felipecaputo|1.3.2|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.2.1|;

---

Repro steps:

1. Clone vscode
2. Set task version to 2.0.0
3. Close terminal
4. Reload window
5. Run task -> watch

![image](https://cloud.githubusercontent.com/assets/2193314/26503364/4a83cd4e-41f5-11e7-8a3d-218fc4d1c2d2.png)

**Comment by dbaeumer** [comment] 2017-05-29 08:00
Did not reproduce for me today using PowerShell and cmd.exe.

**Comment by Tyriar** [comment] 2017-05-30 23:24
Closing off for now due to lack of reliable repro steps.

**Closed by Tyriar** 2017-05-30 23:24 UTC
Labels: bug, integrated-terminal, windows

**Comment by dbaeumer** [comment] 2017-06-07 08:25
Reopening. Saw it today again. It looks like the terminal tries to send something to the spawn child process but the child process has already ended.

**Comment by dbaeumer** [comment] 2017-06-07 08:26
@Tyriar could it be that the terminal has not process the end, exit event from the child process and still thinks the child process is alive.
