### ISSUE TITLE
.ini file coloring bug

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#98550] opened 2020-05-26 06:22 UTC
.ini file character coloring is not correct when use single ' and " at value field.
![Snipaste_2020-05-26_14-18-14](https://user-images.githubusercontent.com/9378047/82866707-05b86680-9f5c-11ea-878f-fa89d509e911.png)
key_c and key_e color is different with key_a.

**Comment by alexr00** [comment] 2020-05-29 08:16
Can you please provide a copy/paste-able example?

**Comment by dacapoday** [comment] 2020-06-01 02:14
> Can you please provide a copy/paste-able example?
```
[ .ini file coloring bug ]
key_a = xxxxxxxxxxxxxxxxxxxxxxxxxxxx
key_b = can't use correct color when
key_c = use single ' at value field
key_d = the " also has this problem
key_e = " xxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by alexr00** [comment] 2020-06-03 08:57
Thanks!
This looks like a duplicate of an upstream issue from where we get our ini grammar. https://github.com/textmate/ini.tmbundle/issues/3

**Closed by alexr00** 2020-06-03 08:57 UTC
