### ISSUE TITLE
View Data in Data Viewer does not appear when debugging

### ISSUE THREAD

**Issue by zzh99-handsome** [microsoft/vscode#204455] opened 2024-02-06 06:37 UTC
Type: <b>Bug</b>

Hi all,

I just encountered a really tricky issue. I cannot see "view data in data viewer" option when using run and debug. I have jupyter extension installed and i uninstalled vs code and reinstalled it from scratch. However, I still cannot see the option by right clicking the variable in the debugging mode. The version of vs code is up-to-date. Could anyone help me out? Thanks for any advice.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.75GB (11.50GB free)|
|Process Argv|C:\\Users\\jerry\\Desktop\\题目2\\pairs trading.py --crash-reporter-id e3551513-5487-436b-bf38-cd4d3781ba5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.156.0
copilot-chat|Git|0.12.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.0
vscode-pylance|ms-|2023.12.1
jupyter|ms-|2024.1.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
d34g3935:30958340
7j2b6412:30949929

```

</details>

**Comment by amunger** [comment] 2024-02-06 16:17
duplicate of https://github.com/microsoft/vscode-jupyter/issues/15121

**Closed by amunger** 2024-02-06 16:17 UTC
