### ISSUE TITLE
debug console should inherit editor settings

### ISSUE THREAD

**Issue by keithbentrup** [microsoft/vscode#45156] opened 2018-03-06 19:23 UTC
- VSCode Version: 1.20.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. I enabled the user setting {"editor.acceptSuggestionOnEnter": "off"}
2. In a debugging session, the console still interprets "enter" as a suggestion completion.

This is not intuitive and forces the user to adapt to different ways of typing in the debug console vs. the editor.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment] 2018-03-07 13:53
Debug Console input does inherit editor settings, except [these ones](https://github.com/Microsoft/vscode/blob/8d0228f52bfb1f9d1eac5e0759e2760ecab549b2/src/vs/workbench/parts/debug/electron-browser/repl.ts#L299)
And among them is the acceptSuggestionOnEnter. It uses a custom acceptSuggestionOnEnter behavior.

**Comment by isidorn** [comment] 2020-05-11 10:48
Since we got multiple requests for this reopening for now and assinging to backlog

**Comment by AnthonyWeston** [comment] 2020-11-09 20:15
This issue is a daily struggle. I don't see much discussion around the value of this fix, so is there any specific reasoning behind the decision to tag this out-of-scope?

> Debug Console input does inherit editor settings, except [these ones](https://github.com/Microsoft/vscode/blob/8d0228f52bfb1f9d1eac5e0759e2760ecab549b2/src/vs/workbench/parts/debug/electron-browser/repl.ts#L299)
> And among them is the acceptSuggestionOnEnter. It uses a custom acceptSuggestionOnEnter behavior.

Is this configurable? If it is, I can't find a setting for it. If this issue won't be fixed, would it be an option to make it configurable?

**Comment by pdimh** [comment] 2020-11-09 23:31
is there a way to disable autocompletion for debug console? i mean, if this wont be fixed, it should be nice to disable autocompletion

**Comment by isidorn** [comment] 2020-11-10 08:25
Not at the moment. There is only the option to disable the suggestions from history via
`	"debug.console.historySuggestions": false`

**Comment by Mark-Sims** [comment] 2021-01-20 20:35
Disabling history suggestions (via @isidorn's comment) doesn't completely solve the issue. There are still intellisense suggestions that appear, and are subsequently accepted with the Enter key.

For example, if I initiate a Python debugging session, and type `import re` (attempting to import Python's RegEx module) intellisense suggests RecursionError and if I hit Enter, that suggestion is accepted, and `import RecursionError` is executed. 

This is with the following setting: "editor.acceptSuggestionOnEnter": "off" (As the OP described.)

**Comment by christian-nils** [comment] 2021-01-22 21:11
I agree, it does not make much sense that the behaviour from the normal code and from the debug console are different. Please consider fixing this issue.

**Comment by vike2000** [comment] 2021-01-23 08:44
> **isidorn** commented [on 7 Mar 2018](https://github.com/Microsoft/vscode/issues/45156#issuecomment-371144583)
> > Debug Console input does inherit editor settings, except [these ones][link]
> > And among them is the acceptSuggestionOnEnter. It uses a custom acceptSuggestionOnEnter behavior.

In the regular editor *(1)* I get the expected behavior that I connect with the following of `settings.json`, but in the debug console *(2)* I guess they behave more like default `"languageDefined"`/`"always"` or just forced all true.
``` json
	"editor.autoClosingBrackets": "never",
	"editor.autoClosingQuotes": "never",
	"editor.autoSurround": "never",
	"editor.matchBrackets": "never",
```
I do not see any of them in the quoted link to [`repl.ts` `getReplInputOptions()`][link]. Any tips on what to do?

+1 ***AnthonyWeston*** *on 9 Nov 2020* hoping this could be made configurable.

---
1. extension `bmewburn.vscode-intelephense-client` language contribution to `php`
2. extension `felixfbecker.php-debug` debug contribution

[link]: https://github.com/Microsoft/vscode/blob/8d0228f52bfb1f9d1eac5e0759e2760ecab549b2/src/vs/workbench/parts/debug/electron-browser/repl.ts#L299

**Comment by Mark-Sims** [comment] 2021-02-06 11:16
Any chance this can be reconsidered? Even if it isn't the highest priority at the moment, I don't feel that it should be Closed.

**Comment by edwardreed81** [comment] 2021-02-11 01:26
I agree - I routinely execute the wrong snippet multiple times in a row on the debug console. It is extremely frustrating.

**Comment by isidorn** [comment] 2021-02-11 08:16
Let's reopen this. Though not plans to tackle it in the near future. Thanks

**Comment by stevage** [comment] 2021-02-18 08:41
This issue (specifically #97439) is incredibly infuriating. Especially when you have a variable in scope that you want to view the value of, yet the debugger auto-completes on "enter" and gives you something completely different.

![vscode-autocomplete](https://user-images.githubusercontent.com/678344/108329229-3eeae200-7221-11eb-8b9b-0cee20d4361c.gif)

**Comment by sayginburak** [comment] 2021-03-02 10:10
This is frustrating and unbelievable that it still hasn't been fixed!

**Comment by Jargonautika** [comment] 2021-03-22 20:29
Please please please fix this problem. It is ridiculous.

**Comment by vderm** [comment] 2021-04-06 13:46
Zzz...

**Comment by pgs31** [comment] 2021-04-29 16:30
I would really appreciate a fix for this, it's super annoying! Thanks guys..

**Comment by Rob-DL** [comment] 2021-05-04 13:46
This is a very very annoying issue. 
Example with the python debug console>:
```
> x = [1 ,2 ,3, 4] <Enter>
> x = [1, 2, 3]  <Enter>  <-- Gets autocompleted to x = [1, 2, 3, 4]]
```
Problem, my valid code is now converted into invalid code and I get an error. Even if the code were valid I still don't get the result I want.

Expected behavior: Don't autocomplete on enter in a REPL environment by default.

**Comment by matoles** [comment] 2021-05-10 21:43
I too would very much like this fixed

**Comment by onurtore** [comment] 2021-05-26 17:02
Bruh, really... Do I have to learn electron and fix it by myself... Trust me, it's not gonna be nice.

**Comment by PhilippHils** [comment] 2021-06-14 15:18
This issue is the only downside of using VSCode for me - apart from that it integrates great in my python workflow.

**Comment by isidorn** [comment] 2021-08-17 18:04
This is fixed now via https://github.com/microsoft/vscode/issues/128768 and https://github.com/microsoft/vscode/issues/108439

Closing as duplicate as we do not want to allow debug console to inherit arbitrary editor settings

**Closed by isidorn** 2021-08-17 18:04 UTC
Labels: feature-request, debug
