### ISSUE TITLE
Commit message not committed when starting with a # character

### ISSUE THREAD

**Issue by attieretief** [microsoft/vscode#84473] opened 2019-11-11 10:14 UTC
Issue Type: <b>Bug</b>

I used to be able to simply type a github issues number as #123 as my commit message, but now the message is not committed unless it starts with a character other than a #

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment] 2019-11-11 10:23
/duplicate of #84201
Should be part of Recovery build 1.40.1

**Closed** 2019-11-11 10:23 UTC
Labels: *duplicate, new release
