### ISSUE TITLE
When requiring a file locally, don't duplicate strings if they are after the current cursor location

### ISSUE THREAD

**Issue by bnb** [microsoft/vscode#78100] opened 2019-07-29 14:41 UTC
Currently, when `require()`ing a local file or directory, IntelliSense helps you by smartly suggesting possible paths:

![image](https://user-images.githubusercontent.com/502396/62056696-2d2f8d00-b1ec-11e9-85a9-5121b5698407.png)

This feature is super useful, and I use it constantly – it's really good validation that my path is accurate. However, I end up finding that I often follow the "normal" `require()` pattern of just typing in a name – often, this is the name of the file I'm `require()`ing.

One issue I run into often is that I want to fill in the file path rather than deleting what I've already written. This ends up doing something that I wouldn't expect:

![Encountering an unexpected behavior with IntelliSense](https://user-images.githubusercontent.com/502396/62057160-163d6a80-b1ed-11e9-886e-9adf0526a8ec.gif)

In the GIF above, you can see that the exact string that is inserted already exists. My instinct here is to hit `Enter` to complete the string. However, this currently ends up duplicating the end of the string. If at all possible, it would be really awesome to see the string following the cursor be detected as an exact match and just move my cursor to the end of it.

**Comment by mjbvz** [comment] 2019-08-11 09:58
Duplicate of #74054

**Closed by mjbvz** 2019-08-11 09:58 UTC
