### ISSUE TITLE
fail to update v1.6.1 , show "install package ruined "（安装到1.6.1版本失败，显示安装包受损）

### ISSUE THREAD

**Issue by Hawken94** [Microsoft/vscode#13879] opened 2016-10-17 11:58 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.
2.

**Comment by Hawken94** [comment] 2016-10-17 12:07
I am a chinese and not good at English.

**Comment by rebornix** [comment] 2016-10-17 15:28
From what he is saying, it should be a duplicate of #780 . But I think it is already fixed? @joaomoreno

**Comment by joaomoreno** [comment] 2016-10-20 12:54
Closing as duplicate.

**Closed by joaomoreno** 2016-10-20 12:54 UTC
