### ISSUE TITLE
export * as test from './test' Validation failed ES6

### ISSUE THREAD

**Issue by lzxb** [Microsoft/vscode#20257] opened 2017-02-09 08:14 UTC
![1](https://cloud.githubusercontent.com/assets/8424643/22774581/c1392d3c-eee2-11e6-80f6-076b8e4e31c0.png)

**Comment by mjbvz** [comment] 2017-02-09 19:26
Do you have any extensions installed? Does this happen if you run code with `--disable-extensions`>

**Comment by lzxb** [comment] 2017-02-10 00:49
Did not install the expansion, webpack2 compiler run no problem
version number 1.9.0

**Comment by mjbvz** [comment] 2017-02-10 01:02
Wait a second, shouldn't  you be using `import` instead of `export` here?

**Comment by mjbvz** [comment] 2017-02-10 01:03
Confirmed that `export * as x from 'x';` produce this exact set of errors. Closing since this is a valid error for a real code issue

**Closed by mjbvz** 2017-02-10 01:03 UTC
Labels: as-designed, javascript, needs more info
