### ISSUE TITLE
anycode client: couldn't create connection to server

### ISSUE THREAD

**Issue by ftniu** [microsoft/vscode#145288] opened 2022-03-17 05:47 UTC
[Warn  - 13:44:30] no native wasm support detected
[Error - 13:44:30] Server initialization failed.
  Message: Request initialize failed with message: WebAssembly is not defined
  Code: -32603 
[Error - 13:44:30] anycode client: couldn't create connection to server
  Message: Request initialize failed with message: WebAssembly is not defined
  Code: -32603 

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39
Embedder: github.dev

**Comment by jrieken** [comment] 2022-03-18 08:01
/duplicate of https://github.com/microsoft/vscode/issues/137704

**Closed** 2022-03-18 08:01 UTC
Labels: *duplicate

**Comment by win98se** [comment] 2022-04-08 08:58
[This](https://github.com/microsoft/vscode/issues/137704#issuecomment-976946258) is not and can't be the solution. I wouldn't want to sacrifice parts of my Web safety just because I need to use `[*.]vscode.dev` and `github.dev`; Also adding both of them in exceptions as stated [here](https://github.com/microsoft/vscode/issues/137704) doesn't work.

**Comment by Goku-04** [comment] 2022-04-20 03:20
Yup I tried adding it to an exception but it didn't work out that way
