### ISSUE TITLE
It should be possible to resize error popups

### ISSUE THREAD

**Issue by AcademyOfF** [microsoft/vscode#116062] opened 2021-02-07 22:18 UTC
For context, I'm talking about pop-ups like this: 
![image](https://user-images.githubusercontent.com/51732963/107161093-2e985480-694f-11eb-9983-f02352f7e28c.png)

I'd like to be able to resize this because I can't always see the full error, and sometimes I have to scroll up and down repeatedly to figure out what the error messages trying to tell me.

**Comment by gjsjohnmurray** [comment] 2021-02-07 23:11
Looks like a duplicate of #56525

**Comment by AcademyOfF** [comment] 2021-02-07 23:24
Assuming the same code is used for that, I would agree. I apologize, I tried to look for duplicates, but i was using the search term "popup"

**Closed** 2021-02-08 11:03 UTC
Labels: *duplicate
