### ISSUE TITLE
json schema validation stopped working

### ISSUE THREAD

**Issue by PiIsFour** [microsoft/vscode#124043] opened 2021-05-17 15:16 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.57.0-insider (user setup)
Commit: 82767cc1d7bf8cdea0f2897276d5d15aee91f3d9
Date: 2021-05-17T05:15:14.544Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Hello, we make extensive use of JSON Schema to validate our files. Now VS Code just stopped showing any validation and inteliSense. I think this behavior started in 1.56.1 but I also have the same in 1.56.2 and 1.57.0-insider with no extensions. Seems to still work in 1.56.0

```json
// settings.json
"json.schemas":[
    {
        "fileMatch": [
            "*.test"
        ],
        "url": "./schema/test.schema.json"
    }
]
```
we have custom file endings matched to there schema like this, but now it stopped working. I can replace the fileMatch to `**/*.test` to get it working again but would like to avoid changing everything that worked before. Also tried to isolate the cause and replicate the problem in a small sample project but there for some reason it works. Tried adding subfolders and symlinks but could not find what triggers this failure.

Do you have an idea what changed in 1.56.1 to maybe cause this or any other idea how I could provide you with more useful information? Let me know if I can help with resolving the issue and thanks for all your work.

**Comment by aeschli** [comment] 2021-05-18 10:03
In 1,56 we started supporting glob patterns (`**`), in 1.56.1 there was a fix so it also works on files from folders starting with a dot.
That said, I don't know how that could have caused it. I'm not able to reproduce the problem in 1.56.1
- In your example, you use files `*.test`. That will only works if `test` is associated with the JSON language. (`JSON` should be in the status bar when opening the file)
- https://github.com/aeschli/schemas is my repo that I tested it with
- anything special about the location of repo (any special characters in the path)

**Comment by mfmayer** [comment] 2021-05-19 07:36
I can observe the same. But it seems that this only happens with multi-root workspaces. When I open a single folder in vscode schema validation is working. Adding another folder to the workspace breaks the validation.

**Comment by PiIsFour** [comment] 2021-05-19 08:45
@aeschli Thanks for the fast response and effort to test this.
- yes we have the file endings associated with json
- I cloned your repo and validation is working same as when I tried to isolate the problem myself
- it is one of many projects in a workspace and we have the schemas in a path `.include/flexpage-core/Schemas` where the last folder is a symlink to another project in this workspace

@mfmayer Thanks for the input. Just tried it too, when I only open the project folder then validation works. But trying to create a sample project with a multi-root workspace to demonstrate the problem validation still works. So this is somehow related but I seem to miss some cause.

**Comment by mfmayer** [comment] 2021-05-19 11:12
@PiIsFour : It works for me with the prefix "**/" within fileMatch (like you mentioned in your first post - even in multi-root workspaces).

E.g.:
previously it was (which still works in single-root but not mult-root workspaces ):
```json
    {
      "fileMatch": [
        "*.test.json*"
      ],
      "url": "./schema/test.schema.json"
    },
```

this now also works in multi-root workspaces:
```json
    {
      "fileMatch": [
        "**/*.test.json*"
      ],
      "url": "./schema/test.schema.json"
    },

```

**Comment by PiIsFour** [comment] 2021-05-25 07:11
Somehow I don't get this issue in a smaller project. Not sure what I'm doing wrong there, but since I can't really expect a bug to get fixed if I can not demonstrate it, we have decided to move everything over to glob patterns.

Sorry for not having more information on this and thanks for the help.

**Comment by aeschli** [comment] 2021-08-18 14:24
Closing as I need sample that reproduces the problem, e.g. by adding a change set to https://github.com/aeschli/schemas

**Closed by aeschli** 2021-08-18 14:24 UTC
Labels: needs more info
