### ISSUE TITLE
Double paste

### ISSUE THREAD

**Issue by littlefrog1973** [microsoft/vscode#102053] opened 2020-07-10 01:16 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

When I copy text from other software for ex.  MS Edge and paste to VS CODE editor by [Ctrl+V]. It doubled my copied text.

**Comment by craigsh** [comment] 2020-07-10 01:27
I experience the same thing. Using NX Console to generate Angular components. I paste "abc" into the path textbox and it ends up as "abcabc".

**Comment by pikadun** [comment] 2020-07-10 07:57
I encountered the same problem.
When I paste the content into the Webview, it will paste twice.

**Comment by tspriggs** [comment] 2020-07-10 09:45
I have the same issues of duplicate pasting, when copying and pasting code inside an ipynb file.

**Comment by davins90** [comment] 2020-07-10 13:39
hi guys,

i noticed the same problem after update to the latest version (1.47) when copy and paste in Jupyter notebook extension.

Thanks

**Comment by mjbvz** [comment] 2020-07-10 20:13
Duplicate of #101946

**Closed by mjbvz** 2020-07-10 20:13 UTC
