### ISSUE TITLE
Custom context menu can render off-screen, blocking some options

### ISSUE THREAD

**Issue by TomSputz** [Microsoft/vscode#53119] opened 2018-06-27 09:52 UTC
Issue Type: <b>Bug</b>

1. Enable the new custom title bar
2. Right click on text in file half way down the window - the context menu will be cut off 
![like shown here](https://i.imgur.com/ENWuq8X.png)

Clearly this issue has been noticed, as the context menu will instead be created above your cursor if it does not fit on the screen, however this does not work if doing so would instead cut off the top of the menu.

The best way to solve this is to detect this situation (Where the context menu could not fit between the cursor and top of the screen/bottom of the screen), and slighty shift the menu down. My description isn't very good so for reference here is how discord handles it (The cursor is where I right clicked)
![Discord handling](https://i.imgur.com/AyvzuwR.png)

I also think it would be worth making a system that splits the context menu into two columns / enables scrolling through it  (Much easier - can likely be done in css no problem) in the unlikely case that the context menu is simply taller than the window

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:18:12.763Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3098)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
vscode-custom-css|be5|2.7.1
vscode-icontheme-nomo-dark|be5|1.3.5
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
vsc-material-theme|Equ|2.1.0
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
todo-tree|Gru|0.0.63
beautify|Hoo|1.3.2
vscode-settings-cycler|hoo|1.0.1
discord-vscode|icr|2.6.0
vscode-simple-icons|Lau|1.8.3
python|ms-|2018.6.0
cpptools|ms-|0.17.5
vsliveshare|ms-|0.3.335
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.24.0
pdf|tom|0.3.0

(5 theme extensions excluded)

</details>

**Comment by sbatten** [comment] 2018-07-03 23:50
dupe of #52533

**Closed by sbatten** 2018-07-03 23:50 UTC
Labels: bug, workbench-menu
