### ISSUE TITLE
Sticky Scroll shows start of javadoc comments "/**" as nested scopes instead of functions and classes.

### ISSUE THREAD

**Issue by Maxylan** [microsoft/vscode#158565] opened 2022-08-19 08:38 UTC
Does this issue occur when all extensions are disabled?: Yes
List of installed Extensions: (Not that it mattered since the issue was there with extensions disabled.)
Material Icon Theme v4.19.0
Perl Toolbox v1.4.0
PHP Debug v1.27.0
PHP Intelephense v1.8.2
phpcs v1.0.5
WooCommerce - Snippets & autocomplete v1.1.0
WordPress Snippets v1.3.12

- VS Code Version: 1.70.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Launch a PHP Workspace, I'm 
developing in Wordpress.
2. Create a Javadoc comment above a class/function and scroll into it with Sticky Scroll enabled.
3. You should get this result: (Note the "/**" at the top instead of the names of functions and class scopes)
![Code_gxNKKxqzcd](https://user-images.githubusercontent.com/28407515/185578839-0dc14d6e-3b07-4829-be19-269b8f5ad07e.png)

**Comment by aiday-mar** [comment] 2022-08-19 09:50
Hi thanks for your feedback. This is a duplicate of https://github.com/microsoft/vscode/issues/157180, and should be solved in the new Insiders version of VSCode.

**Closed by aiday-mar** 2022-08-19 09:50 UTC
Labels: new release
