### ISSUE TITLE
new file focus in to navigation

### ISSUE THREAD

**Issue by gintering1000** [microsoft/vscode#142772] opened 2022-02-10 21:23 UTC
when i make new file, my vscode focus go out to new tab.
what i want to do is focus to navigation for make new file again ( like normal file explorer )

now problem
- user can't choose to open new file or not when user make new file. 
- user can't choose focus location after user make new file. 

![Screen Capture 2022-02-11 at 06 20 09](https://user-images.githubusercontent.com/77244047/153498320-c13b4536-dfca-48f9-b2a2-e4d6e7b6dc8d.gif)

**Comment by JacksonKearl** [comment] 2022-03-01 21:00
Duplicate of #142495

**Closed by JacksonKearl** 2022-03-01 21:00 UTC
