### ISSUE TITLE
Theme is not loaded /lagging in sneak peak view

### ISSUE THREAD

**Issue by UncleGoogle** [microsoft/vscode#212333] opened 2024-05-09 07:51 UTC
Type: <b>Bug</b>

Since some time ago sneak peak view start to show strange colors (yellow `async def`) regardless of the chosen theme. It is sometimes fixed when I scroll long enough or enter viewed file in a different editor.

![image](https://github.com/microsoft/vscode/assets/12197825/46187594-b784-486f-bca5-bd1fcb8c4257)
(using Dark Modern theme)

EDIT
the same happened with disabled all extensions

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (13.34GB free)|
|Process Argv|--crash-reporter-id 1406a5c5-8571-456d-b536-687d9dac05ca|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|Memory (System)|15.45GB (12.10GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|1.11.2
mermaid-markdown-syntax-highlighting|bpr|1.6.3
font-switcher|eva|4.1.0
theme-monokai-pro-vscode|mon|1.3.2
remote-containers|ms-|0.362.0
remote-wsl|ms-|0.88.2
vscode-speech|ms-|0.8.0
vscode-openapi|42C|4.25.3
ruff|cha|2024.20.0
gitlens|eam|14.9.1
copilot|Git|1.188.0
copilot-chat|Git|0.15.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.1
debugpy|ms-|2024.6.0
python|ms-|2024.6.0
vscode-pylance|ms-|2024.5.1
sqltools|mtx|0.26.0
sqltools-driver-sqlite|mtx|0.5.1
vscode-python-typehint|njq|1.5.1
java|red|1.30.0
vscode-yaml|red|1.14.0
even-better-toml|tam|0.19.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.1
vscode-maven|vsc|0.44.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dwnewjupytercf:31039676

```

</details>

**Comment by aeschli** [comment] 2024-05-13 08:28
I can't reproduce.
Can you use the `Developer: Inspect Editor Tokens ans Scopes` command on the token with the wrong color?
I'd be interested to see what the hover shows, if you can add a screenshot.

**Comment by UncleGoogle** [comment] 2024-05-13 09:14
Here you are: ![image](https://github.com/microsoft/vscode/assets/12197825/f5064134-d886-4751-bb26-dc0b88e13991)

**Comment by aeschli** [comment] 2024-05-14 08:11
Sorry, it's still unclear to me what the screenshots mean and what's wrong here.
Which are the strange colors? Can you
- add small sample code that reproduces the issue
- create screenshshots that show the correct colors and the wrong colors


Here's what I tried.
Small sample code:
```
async def get(
        ex: Exception
):
    return 1
```
- Using the Dark Modern theme (default theme) I see this:
![image](https://github.com/microsoft/vscode/assets/6461412/79491d09-413f-4a30-a8c0-8b7c3f4eb565)
- run the command `Peek References` on `ex`
![image](https://github.com/microsoft/vscode/assets/6461412/b2d740fe-699e-42c9-9011-33f7d15c3c0e)

-

**Comment by UncleGoogle** [comment] 2024-05-14 09:43
@aeschli I can only reproduce on a closed source one I'm working on. Unfortunately I can't spend more time to extract the problem to smaller scale.

For now I know that It happens on 
- WSL
- around 50k LOC
- with venv installed and python interpreter selected correctly 
- in a sneak peak view when ctrl-clicking on the python method or class definitions to see usages across all the code
- it fixes when CLICKING inside the sneak peak. 

It is just an annoyance. Maybe someone else would find the minimal repro.

Strange colors -- see that yellow `async def` is difference than `async def` on the normal editor. The same with other syntax colors but this one is most visible one.

![bug_theme_peak](https://github.com/microsoft/vscode/assets/12197825/1e7c3848-c6d2-4b19-9c16-f47f017c7b6d)

**Comment by aeschli** [comment] 2024-12-10 10:38
Closing due to lack of reproducible steps

**Closed by aeschli** 2024-12-10 10:38 UTC
