### ISSUE TITLE
ES6 javascript template syntax hightlighting not using string color

### ISSUE THREAD

**Issue by ddcovery** [Microsoft/vscode#242] opened 2015-11-19 14:41 UTC
ES6 string template is shown with the same color than expresions/variables.  On 0.9.2 version, the template was using the string color (i.e. red in default light theme) allowing a good discrimination between template and placehoders expressions.

**Comment by a-type** [comment] 2015-11-19 16:04
#52 seems to indicate this problem is with all interpolation strings, even beyond ES6 JS. It's good to have a solid version number when this did work, though. Should help tracking it down.

**Comment by jnystrom** [comment] 2015-11-20 17:27
I am also noticing this issue with the beta version that was not there in the previous version.

**Comment by zachlysobey** [comment] 2015-11-20 22:20
I just posted a screenshot for this here: 
https://github.com/Microsoft/vscode/issues/130

Super-annoying though...

**Comment by felixfbecker** [comment] 2015-11-21 17:33
I have the same issue.

**Comment by aeschli** [comment] 2015-11-24 16:20
duplicate of #133

**Closed by aeschli** 2015-11-24 16:20 UTC

**Comment by felixfbecker** [comment] 2015-11-24 16:42
@aeschli no, it's not. As @a-type said,
 > #52 seems to indicate this problem is with all interpolation strings, even beyond ES6 JS.

**Comment by aeschli** [comment] 2015-11-24 18:25
If Ruby also has problems with interpolated strings we need to look at this separately. Please file an issue just for Ruby. The issue with JavaScript is that we switched from our own tokenizer to a Text Mate tokenizer that doesn't support ES6.
