### ISSUE TITLE
Wrong color for solarized light theme

### ISSUE THREAD

**Issue by justinchuby** [Microsoft/vscode#24055] opened 2017-04-06 13:23 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|;

---

Steps to Reproduce:

1. The solarized light theme has a color for selection that's too dark. Was a different color before update.

**Comment by chrmarti** [comment] 2017-04-06 17:55
Possibly related to #24040

**Comment by aeschli** [comment] 2017-04-06 21:36
@justinchuby Do you mean the light or the dark theme? Please correct either the issue title or the description.

**Comment by justinchuby** [comment] 2017-04-06 21:43
@aeschli It should be the light theme. Sorry about that.

**Comment by aeschli** [comment] 2017-04-07 07:29
duplicate of #24040

**Closed by aeschli** 2017-04-07 07:29 UTC
