### ISSUE TITLE
HTML: embedded script not colored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84891] opened 2019-11-15 06:42 UTC
I am using web version and open workbench.html:

![image](https://user-images.githubusercontent.com/900690/68922234-63812000-077b-11ea-9a7f-34f076ae97ac.png)

**Comment by alexr00** [comment] 2019-11-15 09:19
Appears to not just be web specific.

**Comment by alexr00** [comment] 2019-11-15 09:22
This is https://github.com/microsoft/vscode/issues/83541
The fix for it only went into the release branch https://github.com/microsoft/vscode/commit/22d5f54e1d53417ce46bf9ec9762e8054e12e348

**Comment by alexandrudima** [comment] 2019-11-20 11:53
Duplicate of #84401

**Closed by alexandrudima** 2019-11-20 11:53 UTC
Labels: bug
