### ISSUE TITLE
files.exclude does not exclude tsconfig.json tasks from being picked up

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31855] opened 2017-08-01 20:29 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.1
sort-lines|Tyr|1.3.0
emojisense|bie|0.2.3
vscode-svgviewer|css|1.4.2
python|don|0.6.9
git-project-manager|fel|1.3.2
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
ayu|tea|0.4.0

(2 theme extensions excluded)

---

Testing #31232

This may only be true in a multi-root workspace context.

<img width="820" alt="screen shot 2017-08-01 at 1 28 13 pm" src="https://user-images.githubusercontent.com/2193314/28845571-5f288d50-76bd-11e7-842b-69ee60b24f9a.png">

**Comment by mjbvz** [comment] 2017-08-01 21:31
Duplicate of #31822

**Closed by mjbvz** 2017-08-01 21:31 UTC
Labels: insiders, typescript
