### ISSUE TITLE
Intellisense not working since the latest update

### ISSUE THREAD

**Issue by balazserdos** [Microsoft/vscode#49361] opened 2018-05-07 11:48 UTC
- VSCode Version: Version 1.24.0-insider (1.24.0-insider)
- OS Version: macOS Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Launch VS Code Insiders
2. Try to use intellisense to reference even to a variable.

Does this issue occur when all extensions are disabled?: Yes

Since the latest Insiders update, I lost the intellisense at all at TS and JS projects as well. It suggests me only code snippets. My vscode config was not modified, any idea? thank you.
Suggests nothing even if I use ctrl-space to explicitly invoke it.

**Comment by mjbvz** [comment] 2018-05-07 15:42
Please provide a code example or project example. What steps cause it to stop working?

**Comment by balazserdos** [comment] 2018-05-07 18:49
**in terminal I could produce with the following steps**

- mkdir newproject
- cd newproject
- tsc --init
- code-insiders .
- create a ts file

there is no Intellisense at all. Absolutely nothing in that .ts file
Thank you @mjbvz

**Comment by balazserdos** [comment] 2018-05-07 20:08
![image](https://user-images.githubusercontent.com/20303564/39722449-1d7f19e8-5243-11e8-9d50-1f451e8040d3.png)

**Comment by mjbvz** [comment] 2018-05-07 20:52
Duplicate of #49350 Should be fixed in the next insiders

**Closed by mjbvz** 2018-05-07 20:52 UTC
Labels: javascript, needs more info
