### ISSUE TITLE
Getting started actions have ugly drop shadow on dark themes

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119688] opened 2021-03-23 18:54 UTC
<img width="555" alt="image" src="https://user-images.githubusercontent.com/2230985/112202305-7658ff80-8bce-11eb-8735-c0e0324f765e.png">

**Comment by JacksonKearl** [comment] 2021-03-23 19:18
Duplicate of #119633

**Closed by JacksonKearl** 2021-03-23 19:18 UTC
Labels: workbench-welcome
