### ISSUE TITLE
Live Unit Testing

### ISSUE THREAD

**Issue by dseelinger** [microsoft/vscode#83152] opened 2019-10-23 12:57 UTC
Please add support for Live Unit Testing similar to what's available in Visual Studio. If that was available, I would have few reasons to ever leave vscode.

**Comment by alexr00** [comment] 2019-10-23 13:36
Individual language extensions could do this. Otherwise, it is a duplicate of https://github.com/microsoft/vscode/issues/9505

**Closed** 2019-10-23 13:36 UTC
Labels: *extension-candidate
