### ISSUE TITLE
How about add a new plugin 'code map'?

### ISSUE THREAD

**Issue by laoqiren** [Microsoft/vscode#9491] opened 2016-07-19 16:00 UTC
I have used several editor like sublime, atom,webstorm and so on, they all have the code map itself or the plugin, while there are too many lines of code, the code map may help us go to somewhere faster, so I wish it that vscode can also have this kind plugin, I long for it.

**Comment by kieferrm** [comment] 2016-07-20 01:27
This is a duplicate of #4865.

**Closed by kieferrm** 2016-07-20 01:27 UTC
Labels: duplicate
