### ISSUE TITLE
Custom view hover name shows command id instead of friendly name

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#51730] opened 2018-06-12 23:01 UTC
- VSCode Version: 1.24.0
- OS Version: Windows

Steps to Reproduce:

1. Install Docker extension (peterjausovec.vscode-docker) which adds a Docker view container called "Docker"
2. Reload and hover over the whale on the Activity Bar and you see "Docker".
3. Install the Azure App Service extension (ms-azuretools.vscode-azureappservice) which adds an Azure view container called "Azure".
4. Hover over the Docker item in the Activity bar and now you see "workbench.view.extension.dockerView".

![image](https://user-images.githubusercontent.com/12818376/41321576-649ea096-6e59-11e8-82bc-7cc6bf9af3a0.png)

5. Close and restart VS Code and hover over Azure item in the Activity Bar which now also shows the command ide "workbench.view.extension.azure"

![image](https://user-images.githubusercontent.com/12818376/41321650-c209ba72-6e59-11e8-8a42-3dd966972c3c.png)

**Comment by gregvanl** [comment] 2018-06-13 06:09
Looks like just a restart is required to have the command id displayed rather than the friendly name.
Simpler repro:
1. Install Docker extension
2. Reload and hover shows "Docker"
3. Close VS Code and restart
4. Now hover shows "workbench.view.extension.dockerView"

**Comment by sandy081** [comment] 2018-06-19 11:07
Duplicate of #51234

**Closed** 2018-06-19 11:07 UTC
Labels: *duplicate, bug, explorer-custom
