### ISSUE TITLE
I need Chinese documents like PowerToys

### ISSUE THREAD

**Issue by wodesj33** [microsoft/vscode#113579] opened 2020-12-30 08:59 UTC
I need Chinese documents like PowerToys
https://docs.microsoft.com/zh-cn/windows/powertoys/

**Comment by YalandHong** [comment] 2020-12-31 01:49
Duplicate of microsoft/vscode-docs#3260

Currently the developers don't have any plan for localization, but they leave that issue open for tracking. So you can upvote and subscribe it.

Hope this helps.

**Closed** 2021-01-04 09:09 UTC
