### ISSUE TITLE
multi link provider is no more clickable

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#151077] opened 2022-06-02 08:47 UTC
Does this issue occur when all extensions are disabled?: Yes

System:
```
Version: 1.68.0-insider
Commit: 15253f1528573fc8f84e956b21af4bad57f38c07
Date: 2022-06-02T05:16:10.890Z
Electron: 17.4.6
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

Steps to Reproduce:

1. create a link provider with a list of clickable links
2. hover on something to show the links list popup
3. links are not clickable

<img width="450" alt="demo" src="https://user-images.githubusercontent.com/7388088/171592513-aeb0e436-6146-4b1b-a33e-7b8acf9c5979.png">

**Comment by jrieken** [comment] 2022-07-01 11:57
> create a link provider with a list of clickable links

@ctf0 Please share a minimal sample of that. Mine (below) works as expected

<img width="372" alt="Screenshot 2022-07-01 at 13 56 33" src="https://user-images.githubusercontent.com/1794099/176889931-4b6538dd-177d-494c-8563-846a24103be8.png">


```ts
	vscode.languages.registerDocumentLinkProvider('fooLang', new class implements vscode.DocumentLinkProvider {
		provideDocumentLinks(document: vscode.TextDocument, token: vscode.CancellationToken): vscode.ProviderResult<vscode.DocumentLink[]> {
			return [
				new vscode.DocumentLink(new vscode.Range(0, 0, 1, 0), vscode.Uri.parse('https://pinkbike.com')),
				new vscode.DocumentLink(new vscode.Range(0, 0, 1, 0), vscode.Uri.parse('https://pinkbike.com')),
				new vscode.DocumentLink(new vscode.Range(0, 0, 1, 0), vscode.Uri.parse('https://pinkbike.com')),
			]
		}
	})
```

**Comment by ctf0** [comment] 2022-07-03 19:12
unfortunately it will be hard to reproduce using something similar, but here are the links using `console.log(JSON.stringify(links));`
```json
[
    {
        "range": [
            {
                "line": 185,
                "character": 46
            },
            {
                "line": 185,
                "character": 69
            }
        ],
        "target": {
            "$mid": 1,
            "path": "/xxx/lang/de/giftCard.php",
            "scheme": "vscode-insiders",
            "authority": "ctf0.laravel-goto-lang",
            "query": "discountCode"
        },
        "tooltip": "resources/lang/de/giftCard.php"
    },
    {
        "range": [
            {
                "line": 185,
                "character": 46
            },
            {
                "line": 185,
                "character": 69
            }
        ],
        "target": {
            "$mid": 1,
            "path": "/xxx/lang/fr/giftCard.php",
            "scheme": "vscode-insiders",
            "authority": "ctf0.laravel-goto-lang",
            "query": "discountCode"
        },
        "tooltip": "resources/lang/fr/giftCard.php"
    },
    {
        "range": [
            {
                "line": 185,
                "character": 46
            },
            {
                "line": 185,
                "character": 69
            }
        ],
        "target": {
            "$mid": 1,
            "path": "/xxx/lang/en/giftCard.php",
            "scheme": "vscode-insiders",
            "authority": "ctf0.laravel-goto-lang",
            "query": "discountCode"
        },
        "tooltip": "resources/lang/en/giftCard.php"
    }
]
```

if there is a way i could debug on my own and reply with the findings, it would be more than appreciated.

**Comment by ctf0** [comment] 2022-07-04 15:16
can u give me a doc link to read more about those rules ?

**Comment by mjbvz** [comment] 2022-07-28 00:07
Duplicate of #152716

**Closed by mjbvz** 2022-07-28 00:07 UTC
