### ISSUE TITLE
Terminal Configuration

### ISSUE THREAD

**Issue by M-Zuber** [Microsoft/vscode#45326] opened 2018-03-08 18:00 UTC
I would love to be able to store terminal configurations on a per project/global basis

As an example of where it can be useful, the current project I am working on contains a graphql api and frontend sites.
On startup of vscode, I always open at least three terminals to run: tests, the api, and the frontend.

[This extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) by @fabiospampinato works very well, and could possibly be a base to build on in order to get something like this into the core

**Comment by fabiospampinato** [comment] 2018-03-08 18:47
I think that integrating my extension into VSC itself, and possibly making it more powerful, would certainly improve the lives of some people.

But I would rather prefer if VSC took the opposite approach, instead of integrating extensions into core, write every non-core functionality as an extension.

**Comment by M-Zuber** [comment] 2018-03-08 19:10
I agree 💯 that it should be done as an extension, but there seem to be a slight difference as to how things that are considered part of the "core experience" are treated, as opposed to other features.
 And in my opinion, this kind of functionality should be first class.

Another use case I thought of, is having terminals start with different values for environment variables. Using my example above, in the terminal for testing, I want `NODE_ENV` to be `test`, but for actually running the app I want it to be `dev`

**Comment by Tyriar** [comment] 2018-03-08 22:14
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/44302, there is actually a that was added which kind of does this now `terminal.integrated.experimentalRestore`. It was added in haste and there are many edge cases I didn't really consider.

@fabiospampinato you should probably sub and drop your thoughts on that issue, maybe this is something that should be left to an extension (by making the terminal API more powerful). I was actually going to tackle that in March but put it on hold as I need to do some thinking about it, how it interacts with tasks and debug and how to prevent annoying situations, for example: create 5 terminals against a folder, work on some other project for a week, open the folder and get 5 terminals restored. But it would be good to have some basic restoring if it won't get in the way, we certainly wouldn't want to add the complexity that this extension allows.

@fabiospampinato I definitely want to hear your thoughts on restoring splits, not sure if you've created an issue yet?

**Closed by Tyriar** 2018-03-08 22:14 UTC
Labels: integrated-terminal

**Comment by fabiospampinato** [comment] 2018-03-09 01:31
@M-Zuber I've opened an [issue](https://github.com/fabiospampinato/vscode-terminals/issues/10) about environment variables.

@Tyriar I've opened an [issue](https://github.com/fabiospampinato/vscode-terminals/issues/9) in Terminals' repo about adding support for split terminals, feel free to comment on that. I'm going to post my thoughts on the issue you linked.
