### ISSUE TITLE
Ability to dim git ignored files / folders

### ISSUE THREAD

**Issue by nickroberts** [Microsoft/vscode#5944] opened 2016-04-28 12:52 UTC
It would be nice to be able to dim files and folders that are listed in the .gitignore file.

I'm not sure if this has been mentioned or not, before, but I couldn't find anything about it.

It would make it easier to tell what is ignored, and what is in your actual repo. Plenty of times I have accidentally edited a transpiled file, wondering why my changes did get updated.

As an aside, file type icons would be cool, as well. I think this has been mentioned before, but put on the back burner because of the "Christmas Tree Effect". It would make finding files a bit easier, IMO. It could be off by default.

I've just started to look into the source of the project, and from what I understand, there isn't a way to access the explorer (sidebar) with an api. It would be nice to be able to create an extension for something like this. (also, It seems like themes do not have access to the explorer, either (except for light vs. dark). It looks kind of odd when the code pane is one color, and the explorer pane is another.

Sorry to run on, but I think these would be some good additions!

**Comment by dbashford** [comment] 2016-05-19 12:35
This would be great.  Atom does this and I've grown accustomed to it.

**Comment by eosrei** [comment] 2016-08-05 22:43
Duplicate of #178 @bpasero

**Closed** 2016-10-27 09:08 UTC
Labels: duplicate, explorer-files, feature-request

**Comment by ZhiliangGong** [comment] 2017-07-25 17:33
yeah, would be super nice feature
