### ISSUE TITLE
tsconfig.json: "Follow link" failing

### ISSUE THREAD

**Issue by rodrigoscna** [microsoft/vscode#164448] opened 2022-10-24 13:02 UTC
Type: <b>Bug</b>

Steps to Reproduce:

1. With the following:
    ./base/tsconfig.json
    ```JSON
    {
      "compilerOptions": {
        ...
      }
    }
    ```
    ./nextjs/tsconfig.json
    ```JSON
    {
      "extends": "../base/tsconfig.json",
      "compilerOptions": {
        ...
      }
    }
    ```
2. Ctrl+click the extends entry "../base/tsconfig.json".

What's expected:

The VSCode will open the correct ./base/tsconfig.json file.

What happens:

VSCode opens a file with the "almost-correct" path, but with a backslash instead of a slash, thus issuing a file not found error, since this path is not exactly valid on WSL/Linux.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.68.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.28GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/rodrigo/Projects/paniclobster/workspace --remote=wsl+Ubuntu --crash-reporter-id cd7ae288-f950-4814-a0e8-468a30358a65|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.68.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3407)|
|Memory (System)|15.59GB (11.59GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
increment-selection|alb|0.2.0
vscode-sqlite|ale|0.14.1
vscode-bazel|Baz|0.6.0
markdown-mermaid|bie|1.15.2
mermaid-markdown-syntax-highlighting|bpr|1.5.0
turbo-console-log|Cha|2.5.6
npm-intellisense|chr|1.4.2
vscode-eslint|dba|2.2.6
javascript-ejs-support|Dig|1.3.1
gitlens|eam|13.0.3
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
vscode-firefox-debug|fir|2.9.8
shell-format|fox|7.2.2
remotehub|Git|0.44.0
vscode-pull-request-github|Git|0.52.0
go|gol|0.35.2
todo-tree|Gru|0.0.219
rest-client|hum|0.25.1
vscode-peacock|joh|4.2.2
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
file-downloader|min|1.0.12
vscode-docker|ms-|1.22.2
playwright|ms-|0.2.13
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
remote-repositories|ms-|0.22.0
sublime-keybindings|ms-|4.0.10
vscode-js-profile-flame|ms-|1.0.4
vsliveshare|ms-|1.0.5739
vscode-react-native|msj|1.10.0
angular-console|nrw|17.23.3
vscode-versionlens|pfl|1.0.10
ansible|red|1.0.90
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
tiltfile|til|0.0.3
sort-lines|Tyr|1.9.1
vscode-mdx|uni|1.0.3
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-conventional-commits|viv|1.24.3
jinja|who|0.0.8
change-case|wma|1.0.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by mjbvz** [comment] 2022-10-24 21:12
Duplicate of #160979

**Closed by mjbvz** 2022-10-24 21:12 UTC
Labels: bug, help wanted
