### ISSUE TITLE
Settings Sync: previous versions of files not being stored locally?

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#129129] opened 2021-07-21 19:10 UTC
- VS Code Version: 1.58.2
- OS Version: macOS 11.4

I've switched Macs last fall and am wondering if the local backups of my settings are actually working fine – the timestamps are all quite old (roughly from the time I had the previous Mac):

<img width="1223" alt="Screen Shot 2021-07-21 at 21 03 01" src="https://user-images.githubusercontent.com/101152/126545741-e4031ef5-0145-46c9-92c1-6d976b2ba979.png">

Also, this:

<img width="1032" alt="Screen Shot 2021-07-21 at 21 08 38" src="https://user-images.githubusercontent.com/101152/126545829-ca78cc0f-8cfe-447d-94d3-32a9b57957f7.png">

Is this expected? (To be honest, I'm not entirely confident I understand what the various panel show and whether I should expect recent versions from, say, today and yesterday there.) Is that a misconfiguration on my end or possibly a VSCode bug?

**Comment by borekb** [comment] 2021-07-22 07:20
Another thing that I'm not sure behaves as expected:

Clicking on `extensions.json` shows a diff:

<img width="1223" alt="Screen Shot 2021-07-22 at 9 16 59" src="https://user-images.githubusercontent.com/101152/126602631-6824f10a-8b35-466f-ac7d-6b6a9c38de12.png">

Clicking on `settings.json` does nothing, for all the items I tried:

<img width="1223" alt="Screen Shot 2021-07-22 at 9 17 37" src="https://user-images.githubusercontent.com/101152/126602640-a68ac4eb-9e23-4803-9a58-4a0bfa40c9ee.png">

**Comment by sandy081** [comment] 2021-07-22 20:13
Local versions are added only when remote updates local just like remote versions are added when local updates remote. It seems in your case there are no changes you pulled from remote during last 8 mos. Can you please check if you have other machine syncing and they are pushing data to remote, so that, the current machine is pulling?

**Comment by sandy081** [comment] 2021-07-22 20:14
> Clicking on settings.json does nothing, for all the items I tried:

What is the settings editor configuration you have? is it split json?

**Comment by borekb** [comment] 2021-07-23 09:40
> What is the settings editor configuration you have? is it split json?

Yes, split JSON.

---

> Local versions are added only when remote updates local just like remote versions are added when local updates remote.

Oh, so I probably had my mental image wrong. This is what I assumed:

<img width="972" alt="Screen Shot 2021-07-23 at 11 31 13" src="https://user-images.githubusercontent.com/101152/126763707-ce52b178-6f3d-4333-baee-eb64235d9f1a.png">

So if I understand correctly, when I want to look at my _local_ versions of `settings.json`, I should look in the _remote_ panel right?

More generally, if I want to see how my `settings.json` evolved over time (which might involve several machines), is there a way to do that? Previously, I used [this external extension](https://github.com/shanalikhan/code-settings-sync) where `settings.json` was stored to a Gist so browsing its previous versions (coming from whichever machine) was pretty simple; I'm looking for a similar functionality with the built-in Settings Sync.

**Comment by borekb** [comment] 2021-07-23 09:47
Also, what does "Open _Local_ Backups Folder" mean? Is it also flipped?

I'd expect to find the backups of my _local_ `settings.json` there but it's probably just snapshots of some old remote files again? (I've been on a single machine for the past ~10 months which would support this theory.)

<img width="1032" alt="Screen Shot 2021-07-21 at 21 08 38" src="https://user-images.githubusercontent.com/101152/126545829-ca78cc0f-8cfe-447d-94d3-32a9b57957f7.png">

Is there a folder on my disk where the versions of my local `settings.json` file could be found?

**Comment by sandy081** [comment] 2021-07-27 08:31
Filed a separate issue for tracking the bug - settings editor is not opening - https://github.com/microsoft/vscode/issues/129494

> So if I understand correctly, when I want to look at my local versions of settings.json, I should look in the remote panel right?

No, remote panel show the history of data that is pushed from multiple machines. So it is not just your local versions. Also note that, remote does not store your local versions if sync is disabled.

> More generally, if I want to see how my settings.json evolved over time (which might involve several machines), is there a way to do that? 

This is what remote panel shows given that you enabled settings sync on all these machines.

**Comment by borekb** [comment] 2021-07-29 19:16
> > More generally, if I want to see how my settings.json evolved over time (which might involve several machines), is there a way to do that?
> 
> This is what remote panel shows given that you enabled settings sync on all these machines.

I don't know how to compare two versions of `settings.json`, is manually copy/pasting to temporary files my best option? Or am I missing some easier way to see how my settings evolved over time?

**Comment by sandy081** [comment] 2021-07-29 19:22
/duplicate

I see what you mean, there is a request for this already - https://github.com/microsoft/vscode/issues/94203. So marking this as duplicate of that.

**Closed** 2021-07-29 19:22 UTC
Labels: *duplicate, needs more info, settings-sync
