### ISSUE TITLE
Multi folders should can be reordered just like sublime text does!

### ISSUE THREAD

**Issue by apang1992** [Microsoft/vscode#39398] opened 2017-12-01 03:31 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
pgsql|dou|0.0.8
prettier-vscode|esb|0.24.0
terminal|for|0.0.10
Go|luk|0.6.67
prettify-json|moh|0.0.3
python|ms-|0.8.0
sublime-keybindings|ms-|3.0.3
java|red|0.14.0
multi-command|ryu|1.0.0
pdf|tom|0.2.0
vscode-java-debug|vsc|0.3.0
vscode-java-pack|vsc|0.2.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-12-01 10:52
/duplicate of https://github.com/Microsoft/vscode/issues/29715

**Closed by bpasero** 2017-12-01 10:52 UTC
