### ISSUE TITLE
[1.96.0/linux perf. regression] Process fileWatcher consumes a full CPU for 2min on startup

### ISSUE THREAD

**Issue by ronjouch** [microsoft/vscode#235969] opened 2024-12-12 16:26 UTC
**[TL;DR](https://github.com/microsoft/vscode/issues/235969#issuecomment-2541701449)** after halp from bpasero:

1. Commit 88b706b2bb41b85a82e183801fd1b9a090fa95ce (https://github.com/microsoft/vscode/pull/228703) may save occasional 100% CPU for some Linux users...
2. ... but at the cost of 100% CPU at startup, for a period of time proportional to the amount of watched folders
    - Adding `**/node_modules` (plus other big folders) to config `files.watcherExclude` does work around 2. (at the cost of out-of-sync TS/JS if touching node_modules)

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Debian 12.8

## Steps to Reproduce:

1. `code --disable-extensions`
2. Look at CPU activity in gnome-system-monitor, listen to CPU fans

Expected: a bit of understandable CPU activity during startup, maybe a bit of CPU fans whizzing

Actual: a *lot* of CPU activity for *2 full minutes*, CPU fan at full speed. Reproducible, happens everytime I open VSCode.

## Extra info

Following [Performance Issues / Collect Information about the running VS Code](https://github.com/microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code), it appears that what consumes a full CPU (12% = 100% / numCpus) is subprocess `fileWatcher [1]`:

<details>
  <summary>Click to expand output of <code>code --status</code> during intense CPU after startup</summary>
<pre>
Version:          Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS Version:       Linux x64 6.12.3-amd64
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3431)
Memory (System):  31.21GB (19.34GB free)
Load (avg):       4, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id b54c45c0-a937-4ca9-aaed-756eeec9c0d9
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 disabled_off
                  webnn:                                  disabled_off

CPU % Mem MB    PID Process
    0   160 497040  code main
    0    32 497045    zygote
    0   128 497083      gpu-process
    0    32 497046    zygote
    0     0 497048      zygote
    0   224 497103  window [1] (Code)
    0    64 497086    utility-network-service
    0   447 497160  extensionHost [1]
    0    96 497236      electron-nodejs (tsserver.js )
    0   224 497237      electron-nodejs (tsserver.js )
    0    64 497270        electron-nodejs (typingsInstaller.js typesMap.js )
    0    64 497262      /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=497160
    0   383 497667      electron-nodejs (eslintServer.js )
    0    96 497175  shared-process
   12   447 497176  fileWatcher [1]

Workspace Stats: 
|  Window (CENSORED • Code)
|    Folder (CENSORED): 30 files
|      File types: js(1)
|      Conf files:
|    Folder (CENSORED): 139 files
|      File types: sh(3) txt(2)
|      Conf files:
|    Folder (CENSORED): 25 files
|      File types: yml(6) js(3) json(3) ts(2) gitignore(1) npmrc(1) nvmrc(1)
|                  md(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 23 files
|      File types: yml(6) json(5) gitignore(1) npmrc(1) nvmrc(1) md(1) ts(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 25 files
|      File types: yml(6) json(4) ts(2) example(1) gitignore(1) npmrc(1)
|                  nvmrc(1) md(1) js(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 20 files
|      File types: json(5) yml(4) npmrc(2) gitignore(1) md(1)
|      Conf files: github-actions(4) package.json(3)
|    Folder (CENSORED): 27 files
|      File types: mjs(8) json(3) env(1) example(1) yml(1) gitignore(1)
|                  npmrc(1) md(1) css(1) html(1)
|      Conf files: github-actions(1) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 21 files
|      File types: yml(6) json(3) gitignore(1) npmrc(1) md(1) yaml(1)
|      Conf files: github-actions(6) package.json(1)
|    Folder (CENSORED): 42 files
|      File types: ts(16) yml(5) json(4) js(3) gitignore(1) npmrc(1) nvmrc(1)
|                  md(1) zip(1)
|      Conf files: github-actions(5) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 59 files
|      File types: ts(32) yml(6) json(4) js(3) md(2) gitignore(1) npmrc(1)
|                  nvmrc(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 38 files
|      File types: mjs(8) yml(5) json(4) config(2) md(2) dockerignore(1)
|                  yaml(1) example(1) test(1) gitignore(1)
|      Conf files: github-actions(5) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 122 files
|      File types: bak(40) sh(35) mjs(18) yml(11) json(3) gitignore(1) md(1)
|                  js(1) py(1)
|      Conf files: github-actions(9) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 64 files
|      File types: ts(14) js(11) map(7) yml(5) json(4) png(4) lua(2)
|                  gitignore(1) luacheckrc(1) npmrc(1)
|      Conf files: github-actions(5) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 68 files
|      File types: tsx(13) png(11) ts(7) json(5) yml(3) svg(3) md(2) html(2)
|                  gitignore(1) npmrc(1)
|      Conf files: github-actions(3) package.json(1) tsconfig.json(1)
|                  webpack.config.js(1)
|    Folder (CENSORED): 80 files
|      File types: ts(22) js(13) map(11) json(7) yml(5) gitignore(1)
|                  npmignore(1) npmrc(1) nvmrc(1) md(1)
|      Conf files: github-actions(5) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 148 files
|      File types: js(74) png(22) svg(10) yml(7) json(5) md(2) sh(2)
|                  example(1) production(1) staging(1)
|      Conf files: github-actions(7) jsconfig.json(1) package.json(1)
|    Folder (CENSORED): 63 files
|      File types: ts(11) yaml(7) yml(4) json(4) md(3) go(3) dockerignore(1)
|                  example(1) js(1) gitignore(1)
|      Conf files: github-actions(4) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 67 files
|      File types: ts(10) js(6) yml(6) json(6) map(5) config(3) yaml(2)
|                  conf(2) dockerignore(1) example(1)
|      Conf files: github-actions(6) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 148 files
|      File types: ts(56) js(30) map(27) yml(6) json(5) md(2) gitignore(1)
|                  npmrc(1) nvmrc(1) tsbuildinfo(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 235 files
|      File types: ts(96) js(49) map(47) json(8) yml(6) md(3) gitignore(1)
|                  npmrc(1) npmrc-github(1) nvmrc(1)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 109 files
|      File types: ts(20) tsx(18) json(14) yml(6) md(5) svg(5) js(4)
|                  babelrc(3) html(2) png(2)
|      Conf files: github-actions(6) settings.json(1) package.json(1)
|                  tsconfig.json(1) webpack.config.js(1)
|    Folder (CENSORED): 86 files
|      File types: js(10) map(10) ts(10) yaml(9) yml(8) json(4) config(2)
|                  conf(2) dockerignore(1) example(1)
|      Conf files: github-actions(8) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 158 files
|      File types: js(34) map(32) ts(29) json(9) yml(8) yaml(7) gitignore(2)
|                  md(2) helmignore(1) kubeconform(1)
|      Conf files: github-actions(8) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 236 files
|      File types: ts(86) js(46) map(44) yml(6) json(6) config(4) yaml(2)
|                  sh(2) conf(2) dockerignore(1)
|      Conf files: github-actions(6) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 164 files
|      File types: ts(37) js(22) map(18) svg(12) yml(7) json(6) ico(4)
|                  config(3) md(3) yaml(2)
|      Conf files: github-actions(6) package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 192 files
|      File types: ts(65) js(35) map(33) yaml(7) yml(7) json(4)
|                  dockerignore(1) example(1) gitignore(1) npmrc(1)
|      Conf files: github-actions(6) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 214 files
|      File types: ts(72) js(36) map(36) png(16) yml(6) json(4) md(2)
|                  example(1) test(1) gitignore(1)
|      Conf files: github-actions(6) dockerfile(1) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 272 files
|      File types: mjs(58) js(34) csv(33) json(30) map(13) mts(12) md(10)
|                  sh(8) gitignore(7) yml(3)
|      Conf files: package.json(11) tsconfig.json(3) github-actions(2)
|                  makefile(1)
|    Folder (CENSORED): 216 files
|      File types: ts(64) js(34) map(32) yml(7) json(5) config(3) yaml(2)
|                  md(2) conf(2) txt(2)
|      Conf files: github-actions(6) dockerfile(2) package.json(1)
|                  tsconfig.json(1)
|    Folder (CENSORED): 381 files
|      File types: ts(140) js(73) map(70) yaml(15) yml(8) json(6) md(3)
|                  helmignore(1) dockerignore(1) example(1)
|      Conf files: github-actions(8) settings.json(1) dockerfile(1)
|                  package.json(1) tsconfig.json(1)
|    Folder (CENSORED): 527 files
|      File types: ts(201) js(107) map(104) yml(7) json(6) sh(5) config(3)
|                  yaml(3) md(3) gitignore(2)
|      Conf files: github-actions(7) dockerfile(3) package.json(2)
|                  tsconfig.json(2)
|    Folder (CENSORED): 200 files
|      File types: yaml(115) sh(11) md(2) gitignore(1) yml(1)
|      Conf files: github-actions(4)
|    Folder (CENSORED): 1510 files
|      File types: yaml(361) map(276) ts(256) js(237) mts(105) mjs(48)
|                  json(16) xml(12) yml(11) md(6)
|      Conf files: github-actions(10) package.json(4) tsconfig.json(3)
|                  dockerfile(2)
|    Folder (CENSORED): 1056 files
|      File types: tf(579) md(108) yml(25) tfplan(19) tfvars(18) sh(14)
|                  hcl(10) yaml(10) zip(10) js(9)
|      Conf files: github-actions(3)
|    Folder (CENSORED): 1411 files
|      File types: ts(575) js(205) json(119) md(61) tsx(60) yml(26) yaml(24)
|                  nvmrc(16) png(15) npmrc(13)
|      Conf files: github-actions(18) package.json(17) tsconfig.json(16)
|                  dockerfile(8)
|    Folder (CENSORED): 1856 files
|      File types: ts(1025) json(191) js(63) md(41) nvmrc(31) npmrc(30)
|                  map(29) prettierrc(28) dockerignore(27)
|                  prettierignore(23)
|      Conf files: package.json(30) tsconfig.json(30) dockerfile(29)
|                  github-actions(12) eslint.json(1)
|    Folder (CENSORED): 7978 files
|      File types: ts(2462) js(2234) map(1230) txt(672) json(462)
|                  mustache(150) pegjs(26) md(24) yml(12) tsbuildinfo(9)
|      Conf files: github-actions(11) tsconfig.json(9) package.json(2)
|    Folder (CENSORED): 4249 files
|      File types: js(1049) jsx(795) tsx(428) ts(355) svg(252) map(244)
|                  png(106) json(34) yml(28) yaml(18)
|      Conf files: github-actions(26) package.json(7) tsconfig.json(5)
|                  settings.json(1) dockerfile(1) jsconfig.json(1)
</pre>
</details

**Comment by bpasero** [comment] 2024-12-12 17:46
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ronjouch** [comment] 2024-12-12 18:03
@bpasero I confirm the problem persists with today's Insiders build Version: 1.97.0-insider - 6a5c8cf95aa814b5cb92de617096144b1f45af2d - 2024-12-12T05:04:17.220Z.

And this led me to realize one thing: both in Stable & Insiders, the problem only happens when I load my workspace (see details in `<details>` block at the bottom of the issue description). Said differently:

1. If I `code(-insiders) foo.txt` (standalone file), no problem
2. If I `code(-insiders) ~/work/work.workspace` (job workspace), CPU to the roof for 2min

So, something in my (twenty small-to-medium projects) workspace causes this 2min explosion. It's of course understandable that startup takes more time in 2. than 1. , but it feels disproportionate, and I think it's a regression of 1.96.0

**Comment by bpasero** [comment] 2024-12-12 18:08
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by ronjouch** [comment] 2024-12-12 21:56
@bpasero wheee, 88b706b2bb41b85a82e183801fd1b9a090fa95ce (#228703) is the first bad commit

Bisect details: npx vscode-bisect got me to [37f77b1017a00d962f0b6492f907d01de38bf4af is the first bad commit after e34ecab75b0c379c17921f759a77eebaf24bebf2](https://github.com/microsoft/vscode/compare/e34ecab75b0c379c17921f759a77eebaf24bebf2...37f77b1017a00d962f0b6492f907d01de38bf4af), then local git bisect did the rest in 3 iterations.

**Comment by bpasero** [comment] 2024-12-13 08:12
@ronjouch kudos for following along this process 👏 

In that change we had to alter `files.watcherExclude` to remove `'**/node_modules/*/**': true` to support TypeScript working properly. I assume that workspace you use is large and potentially has a ton of node modules. You can bring back that setting to your user settings, but it might result in TypeScript not catching up properly when installing node modules.

In general, excluding large folders via that setting is the fix for high CPU on Linux. File watching on Linux works by traversing each and every folder from a root to install watchers, there is no other way that I am aware of. However there is https://github.com/parcel-bundler/watcher/issues/87 which is maybe something to speed this up on Linux, but we depend on upstream here.

**Comment by ronjouch** [comment] 2024-12-13 13:07
@bpasero 

> In that change we had to alter `files.watcherExclude` to remove `'**/node_modules/*/**': true` to support TypeScript working properly. I assume that workspace you use is large and potentially has a ton of node modules. You can bring back that setting to your user settings, but it might result in TypeScript not catching up properly when installing node modules.

Okay thanks. I confirm that my workspace has a ton of node_modules 😓, and I confirm that adding `'**/node_modules/*/**': true` partially fixes high CPU usage on startup.

However, I write “partially”, because two observations make me remain suspicious about this change:

1. After adding `'**/node_modules/*/**': true` to my `files.watcherExclude`, I still get about 40s of 100% CPU usage on startup! 40s is less unpleasant than 2min, but it's still a lot, and it's enough to make fans go full-speed brrr from +20s to +45s 🙁.
    -. I also tried to add to watcherExclude more no-JS/TS folders to never monitor (e.g. `dist`, `coverage`, etc), this resulted in no noticeable improvement
2. So, I tried to go all the way, and completely disabled the watcher with `"**": true`... but it still results in a 100% CPU usage for 35s on startup 😦!

→ Point 2. in particular makes me suspicious. Am I missing something / what's going on in these 35s? Your phrasing suggests that adding `'**/node_modules/*/**': true` should get me back-to-pre-88b706b2bb41b85a82e183801fd1b9a090fa95ce perf, but given these 2 observations, it's clearly not the case (else I'd be back to baseline: ~0% CPU after startup+3s). Are you sure there isn't something else that is startup-performance-averse in this change and that could be configured/reworked?

**Comment by bpasero** [comment] 2024-12-13 14:12
@ronjouch yeah given your 2. point, the high CPU use cannot be attributed to the file watcher, as that will disable the file watcher. Can you distill which process is spinning high from the ones VS Code spawns?

**Comment by ronjouch** [comment] 2024-12-13 14:16
> Can you distill which process is spinning high from the ones VS Code spawns?

@bpasero it’s clearly `fileWatcher`. Excerpt of `code --status` in the issue description:

```
CPU % Mem MB    PID Process

0   160 497040  code main
0    32 497045    zygote
0   128 497083      gpu-process
0    32 497046    zygote
0     0 497048      zygote
0   224 497103  window [1] (Code)
0    64 497086    utility-network-service
0   447 497160  extensionHost [1]
0    96 497236      electron-nodejs (tsserver.js )
0   224 497237      electron-nodejs (tsserver.js )
0    64 497270        electron-nodejs (typingsInstaller.js typesMap.js )
0    64 497262      /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=497160
0   383 497667      electron-nodejs (eslintServer.js )
0    96 497175  shared-process
12   447 497176  fileWatcher [1] // <- Aaaaaah! 100% / 8CPUs = 12%, 1 CPU maxed
```

**Comment by bpasero** [comment] 2024-12-13 14:29
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ronjouch** [comment] 2024-12-13 15:28
@bpasero I was already running with `--disable-extensions`... but you did well to ask! Because re-testing led me to realize that too much re-running this thing again and again got me to go too fast, and misinterpret, my the previous test! My report that

> _So, I tried to go all the way, and completely disabled the watcher by setting `files.watcherExclude` to `{ "**": true }` ... but it still gets me 100% CPU usage for 35s on startup 😦!_

was inaccurate! What is consuming CPU at startup for 35s (and it's not a complete full CPU) is not `fileWatcher` but extensions indeed! Sorry, I got confused and read the wrong process in the process tree 🙃.

---

So, this issue boils down to:

1. Commit 88b706b2bb41b85a82e183801fd1b9a090fa95ce (https://github.com/microsoft/vscode/pull/228703) may save occasional 100% CPU for some Linux users...
2. ... but at the cost of 100% CPU at startup, for a period of time proportional to the amount of watched folders
    - Adding `**/node_modules` (plus other big folders) to config `files.watcherExclude` does work around 2. (at the cost of out-of-sync TS/JS if touching node_modules)

→ I think I’ll live with 2. for now.

---

@bpasero with ,that letting you triage and close/notclose/rename:

1. Maybe current state it's fine
2. Maybe it’d be worth better exposing the `**/node_modules` tradeoff to Linux users? It’d probably require some work do so in a reasonable / not too intrusive way, one e.g. that shows a notification when detecting lots of watched folders (similar to how VSCode notifies when kernel param for file watches should be increased).
3. Maybe it’d be worth for the VSCode team to bring help shipping https://github.com/parcel-bundler/watcher/issues/87

Thanks for all the fast help!

**Comment by bpasero** [comment] 2024-12-13 18:53
Ok good, I am going then ahead and close this. Changing the setting again is not an option. Contributing to parcel watcher is, but we invite everyone from the community to help there if possible.

**Closed by bpasero** 2024-12-13 18:53 UTC
Labels: under-discussion, file-watcher, new release
