### ISSUE TITLE
Terminal rendering issues after intalling the latest VS Code 

### ISSUE THREAD

**Issue by zhj0924** [microsoft/vscode#120496] opened 2021-04-04 07:26 UTC
Issue Type: <b>Bug</b>

Terminal rendering issues (zsh) after intalling the latest VS Code 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.21343
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (9.00GB free)|
|Process Argv|--crash-reporter-id 4acc1094-1430-490d-8cdf-c6f078bf8474|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|15.58GB (0.29GB free)|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-great-icons|emm|2.1.72
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
file-icons|fil|1.0.29
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
better-cpp-syntax|jef|1.15.5
Kotlin|mat|1.7.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-language-pack-zh-hans|MS-|1.55.2
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-ssh-edit-nightly|ms-|2021.3.44100
remote-ssh-nightly|ms-|2021.3.44100
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.6.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0
ayu|tea|0.20.1
vscode-icons|vsc|11.3.0
vim|vsc|1.19.3
jinja|who|0.0.8
material-theme|zhu|3.10.7
vscode-django|bat|1.4.0
doxdocgen|csc|1.1.0
python-extension-pack|don|1.6.0
EditorConfig|Edi|0.16.4
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.25.0
vscode-test-explorer|hbe|2.19.6
better-cpp-syntax|jef|1.15.5
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.13.1
vscode-python-test-adapter|lit|0.6.7
MagicPython|mag|1.1.0
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.5-pre.1
jupyter|ms-|2021.5.702919634
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vscode-typescript-next|ms-|4.3.20210403
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.4.1
autodocstring|njp|0.5.4
java|red|0.76.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12
vscode-arduino|vsc|0.4.0
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-wakatime|Wak|5.0.1
jinja|who|0.0.8
clang-format|xav|1.9.0

(19 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vsget980:30284045
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by zhj0924** [comment] 2021-04-04 07:27
![image](https://user-images.githubusercontent.com/35902491/113501744-6ac5dc80-94dc-11eb-9e4c-41b97571bb72.png)

Before update:
![image](https://user-images.githubusercontent.com/35902491/113501757-7e714300-94dc-11eb-91fd-69ae931f6934.png)

**Comment by BaldemarEspinoza** [comment] 2021-04-05 00:37
I have this issue as well except I am using Cmder with powerline theme:
<img width="541" alt="term" src="https://user-images.githubusercontent.com/74387497/113525665-e0cd5080-957b-11eb-9310-7bc8e304dc11.png">

**Comment by Jo-Geek** [comment] 2021-04-05 03:28
The integrated terminal does have some rendering issues. Notice where the cursor is at and the space between all the characters.
![image](https://user-images.githubusercontent.com/23304242/113533903-c41d3100-95ec-11eb-9261-6e6f03134d30.png)

**Comment by VanderSP** [comment] 2021-04-05 12:18
My terminal are randomly putting ;1R strange characters, im going crazy!!!!!

**Comment by coreylista** [comment] 2021-04-05 22:38
> My terminal are randomly putting ;1R strange characters, im going crazy!!!!!
Yes this!!

**Comment by andrhevictor** [comment] 2021-04-06 21:55
@Jo-Geek 
> However, it fixes itself - If I click on 'Select Default Profile' and select a default terminal (regardless of which one you select)

Selecting a Default Profile did the trick!

**Comment by VanderSP** [comment] 2021-04-07 12:20
I forget to say that im using INSIDER version... anyone having it also with stable?

**Comment by VanderSP** [comment] 2021-04-07 12:20
I forget to say that im using INSIDER version... anyone having it also with stable?

**Comment by shwestrick** [comment] 2021-04-07 13:45
> I forget to say that im using INSIDER version... anyone having it also with stable?

I'm having the issue on stable, version 1.55.0. The 'Select Default Profile' trick also worked for me.

**Comment by VanderSP** [comment] 2021-04-07 14:28
so it can be related to usign remote extension? i use it also for wsl2

i dunno if we are talking about same issues, because i seen lately here on issues, 3 kinds of similar but i dunno if different problems related to terminal lately!

**Comment by meganrogge** [comment] 2021-04-08 03:31
Duplicate of #120004

**Closed** 2021-04-08 03:36 UTC
Labels: *duplicate

**Comment by jedchang** [comment] 2021-04-12 05:46
Use Cmder, there is the same problem
![q](https://user-images.githubusercontent.com/8979857/114346136-82186000-9b95-11eb-8009-bda9cd6de97b.jpg)
