### ISSUE TITLE
TypeScript Function Declarations Syntax Highlighting Problem With Multiline Params

### ISSUE THREAD

**Issue by fxlemire** [Microsoft/vscode#38073] opened 2017-11-10 16:34 UTC
VSCode Version: 1.18.0
OS Version: Windows 10

Wrong syntax highlighting when parameters start on the next line.

![image](https://user-images.githubusercontent.com/4381789/32668236-fbdb62de-c60a-11e7-9963-c616deececcd.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-11-10 18:42
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/539 See that bug for why this can't be addressed

**Closed by mjbvz** 2017-11-10 18:42 UTC
Labels: duplicate, javascript, new release, upstream
