### ISSUE TITLE
intelliSense should always show exact match first

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14942] opened 2016-11-03 22:18 UTC
- VSCode Version: 1.8 Insider
- OS Version: OS X 10.11.6

![image](https://cloud.githubusercontent.com/assets/4033249/19986254/34270664-a1d3-11e6-9f86-d78908f43d26.png)

Don't really know if this is ts language service's problem or the scoring algorithm.

**Comment by jrieken** [comment] 2016-11-04 08:24
dupe of #14861, fixed on master

**Closed by jrieken** 2016-11-04 08:24 UTC
Labels: suggest
