### ISSUE TITLE
Closing tabs feels quite slow

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#24665] opened 2017-04-13 09:35 UTC
- VSCode Version: 1.11.1
- OS Version: macOS Sierra

One common workflow that I have is to close a bunch of tabs I have open by holding down ctrl-w. This very visibly and obviously lags the IDE. 

While the underlying problem may be very difficult, a simple solution seems to me that VSCode could instantly _show_ that the tab was closed, but continue to do the work necessary to close it in the background.

**Comment by bpasero** [comment] 2017-04-17 16:04
April to investigate if there is something obivous that is slow.

@johnfn does it reproduce with extensions disabled?

**Comment by bpasero** [comment] 2017-04-17 16:57
Since the action to "Close All Editors" is quite fast, it is probably related to the fact that we try to open the next editor each time an editor is closed. Maybe we could detect that the user is about to quickly close editors (e.g. by pressing and holding `Cmd+W`) and in that case just close editors without opening the next. Might be tricky to get right though.

**Comment by johnfn** [comment] 2017-04-17 17:04
Curiously I am actually unable to repro it if I just start a new project and open up files and then close them, no matter if I have extensions open or not. Maybe it's something about long running projects that causes this? Unfortunately I am not sure.

**Comment by bpasero** [comment] 2017-04-17 17:09
For sure still something we can improve if we can detect reliably that multiple editors are to be closed.

**Comment by 4O4** [comment] 2017-10-17 18:25
@johnfn Does this proble still happen?

**Comment by kentoj** [comment] 2018-02-23 01:19
yes this problem still happens

**Comment by bpasero** [comment] 2018-09-10 16:00
I am closing this, currently no plans to work on it near term.

**Closed by bpasero** 2018-09-10 16:00 UTC
Labels: perf, workbench-tabs
