### ISSUE TITLE
Changing font width without changing font height

### ISSUE THREAD

**Issue by silvertakana** [microsoft/vscode#179521] opened 2023-04-08 08:06 UTC
I have this new font but it's really wide. I can't find a way to change just the width without affecting the height. I really love that font.

**Comment by unicreators** [comment] 2023-04-09 01:51
@silvertakana Try vscode -> Settings -> Editor: Line Height

**Comment by rzhao271** [comment] 2023-12-04 19:04
Duplicate of #95493

**Closed by rzhao271** 2023-12-04 19:04 UTC
