### ISSUE TITLE
Get extensions behind a proxy

### ISSUE THREAD

**Issue by Harpagon** [Microsoft/vscode#19626] opened 2017-01-31 11:38 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:55:32.357Z)
- OS Version: Linux ia32 4.4.0-59-generic
- Extensions:
none
---

Steps to Reproduce:

Hello, i'am trying setup any extension using proxy-server and get error in developer console
`"workbench.main.js:132 POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_TUNNEL_CONNECTION_FAILED"`

![vscode_error](https://cloud.githubusercontent.com/assets/6270201/22463482/6a83e83a-e7ba-11e6-8fe5-1e842454b2b1.png)

**Comment by joaomoreno** [comment] 2017-01-31 15:03
Duplicate of #17574

**Closed by joaomoreno** 2017-01-31 15:03 UTC
