### ISSUE TITLE
bracket not closing properly 

### ISSUE THREAD

**Issue by rogueXD** [microsoft/vscode#78902] opened 2019-08-11 13:40 UTC
Issue Type: <b>Bug</b>

Can't really reliably reproduce the bug since it happens pretty randomly
When '(' is pressed, another ')' is automatically created. However, when press the ')' to exit, it create another ')'. e.g. expected: while() - get: while())

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
nand2tetris|lea|1.1.1
python|ms-|2019.8.29288
remote-wsl|ms-|0.39.2
material-icon-theme|PKi|3.8.1
ayu|tea|0.18.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2019-08-11 14:25
https://github.com/microsoft/vscode/issues/37315#issuecomment-515200477 describes a change that I think just landed in 1.37. Does it explain what you are seeing?

**Comment by usernamehw** [comment] 2019-08-11 16:34
Possible duplicate of #78833

**Comment by alexandrudima** [comment] 2019-08-12 09:13
@rogueXD What programming language are you using? Starting with 1.37, the editor will overtype only those brackets that it introduced by itself. What steps are you taking, I wonder if you are running into a corner case?

**Comment by rogueXD** [comment] 2019-08-12 11:53
I'm writing in c++

I'm not really sure if that's the same as the overtyping thing you've mentioned though, for example: I usually type 'for' and '(', which will then automatically create a closing bracket ')':
`for()`
When i got to the end of the condition and type the close bracket ')' again, it used to overtype that close bracket and get a normal for loop:
`for(...)`
But now it creates another close bracket, so i get
`for(...))`

Not sure if this is clear enough for not. It doesn't happen all the time though, but it's often enough for me to think that it can be an issue

**Comment by alexandrudima** [comment] 2019-08-12 13:37
@rogueXD Thank you for following up. I am looking to find a specific repro. For me, the `)` does get overtyped:

![Kapture 2019-08-12 at 15 33 30](https://user-images.githubusercontent.com/5047891/62868732-94822c80-bd16-11e9-8487-a9703faa53d9.gif)

The `)` will not be overtyped twice or if you move the cursor outside of the `( ... )` area or if you press Enter. e.g.

(overtyped already)
![Kapture 2019-08-12 at 15 35 12](https://user-images.githubusercontent.com/5047891/62868824-cd220600-bd16-11e9-8261-98ba91d3086d.gif)

(left the area)
![Kapture 2019-08-12 at 15 36 44](https://user-images.githubusercontent.com/5047891/62868934-0a869380-bd17-11e9-93c1-6bc3e2d4dcb0.gif)

I would like to polish the way this works and I'm trying to find out from you when do you find that overtyping is not behaving...

**Comment by rogueXD** [comment] 2019-08-12 13:45
I guess that might have been the case since i couldn't reproduce it without moving the cursor around. I'll see if that the only behavior that i'm getting and i'll follow up with another comment, otherwise i'll close this issue

**Comment by alexandrudima** [comment] 2019-08-12 13:51
Thanks!

**Comment by haymez** [comment] 2019-08-12 17:16
@alexandrudima Is there an existing feature request for a setting that allows us to control the new behavior of closing tags? I've grown quite used to the previous experience where vscode always swallowed closing tags. I realize the new behavior was heavily requested but it seems like there was definitely a sizable group of people who preferred things the way they were.

**Comment by Tryforce** [comment] 2019-08-12 18:27
This has been driving me crazy all morning, glad to see it wasn't just me. In Java, typing my service name and letting the autocomplete fill in the method call will ensure that the closing paren is never jumped over, whereas before this would be the case. 

I've had similar things happening in Typescript, but they seem to happen more intermittently. Not sure why, but Typescript used to also be able to infer when I was calling a function/method and insert the parens on autocomplete, but it doesn't anymore. Not sure if it's related to this.

Can we at least get a setting for this?

**Comment by gjsjohnmurray** [comment] 2019-08-12 18:38
#78975 identifies an issue with parens that are supplied by autocomplete.

**Comment by gjsjohnmurray** [comment] 2019-08-13 06:51
> @alexandrudima Is there an existing feature request for a setting that allows us to control the new behavior of closing tags?

#78833

**Comment by alexandrudima** [comment] 2019-08-13 09:01
Let's continue tracking the option to provide the old behavior in #78833

In the meantime @rogueXD please reopen if you spot some kind of corner case.

**Closed by alexandrudima** 2019-08-13 09:01 UTC
Labels: editor-autoclosing, needs more info
