### ISSUE TITLE
 Path must be a string. Received { Error: Command failed: wmic.exe process where parentProcessId=6220 get ExecutablePath,ProcessId

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32560] opened 2017-08-15 15:02 UTC
Issue Id: <b>b5402855-71b7-e67e-d7de-652e8588ad90</b><br /><br />*Versions* <br />- 1.15.0<br />*Stack* <br />TypeError: Path must be a string. Received { Error: Command failed: wmic.exe process where parentProcessId=6220 get ExecutablePath,ProcessId<br />ERROR:

<br />Description = The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

<br /><br />    at ChildProcess.exithandler (child_process.js:223:12)<br />    at emitTwo (events.js:106:13)<br />    at ChildProcess.emit (events.js:191:7)<br />    at maybeClose (internal/child_process.js:885:16) <no sourcemaps><br />    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5) <no sourcemaps><br />  killed: false,<br />  code: 2147943458,<br />  signal: null,<br />  cmd: 'wmic.exe process where parentProcessId=6220 get ExecutablePath,ProcessId' }<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename))<br />[/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/stopwatch.ts#L5:0](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/stopwatch.ts#L5:0)<br />

**Comment by kieferrm** [comment] 2017-08-15 17:30
Related to #32556.

**Comment by Tyriar** [comment] 2017-08-15 17:58
Duplicate of https://github.com/Microsoft/vscode/issues/32556

**Closed by Tyriar** 2017-08-15 17:58 UTC
Labels: error-telemetry
