### ISSUE TITLE
Discard changes not working properly, still appears in git status

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/vscode#28326] opened 2017-06-09 09:56 UTC
- VSCode Version: 1.13.0
- OS Version: Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:
I discard the changes from a file in VS Code but it still appears when I run `git status`.

![image](https://user-images.githubusercontent.com/19337229/26970713-ea494dd4-4d3c-11e7-8cfe-dbf6c91a3003.png)

**Comment by joaomoreno** [comment] 2017-06-14 08:47
If you close Code and open it again those changes still don't appear?

**Comment by iamdevlinph** [comment] 2017-06-14 08:52
@joaomoreno Just checked. Still doesn't appear on Code restart.

**Comment by joaomoreno** [comment] 2017-06-14 09:48
Does it happen only with that specific `filter.component.js` file? Or other files won't show up either?

**Comment by iamdevlinph** [comment] 2017-06-14 10:26
It happens to any file. It's the `Discard Changes` functionality itself.

**Comment by joaomoreno** [comment] 2017-06-14 10:34
That sounds very odd. What does `git status -zu` return? Can you provide a movie screencast?

**Comment by iamdevlinph** [comment] 2017-06-14 10:37
The file which I did `Discard Changes` appears in the result of `git status -zu`. 

I will provide one ASAP.

**Comment by iamdevlinph** [comment] 2017-06-14 15:00
Here is the screencast. The file in mention is `index.html`.

[View it here](http://g.recordit.co/s5Q8xEKvav.gif)

**Comment by joaomoreno** [comment] 2017-06-15 07:13
Code seems to be doing the right thing here... just the command line git seems to be doing the wrong thing... So... if you go to disk, what are the real contents of that file, if you open it in Nodepad?

**Comment by iamdevlinph** [comment] 2017-06-15 07:18
Hmm. Weird. The change is not there when I opened the file in Notepad.

It's really the CLI git acting up.

**Comment by joaomoreno** [comment] 2017-06-15 08:33
You can see exactly what Code calls git with by running `Git: Show Git Output`.

Closing since the issue isn't related to Code.

Maybe it's related to the `fscache` setting: https://superuser.com/questions/974078/what-does-the-filesystem-cache-do-in-windows-7

**Comment by iamdevlinph** [comment] 2017-06-15 09:12
Turning `fscache` on or off doesn't help. Running Coed as admin doesn't help either.

I found that `Discard change` in Code runs `git checkout -q -- file/to/path`. 

I copied this command and put in the cli and it works properly.

**Comment by iamdevlinph** [comment] 2017-06-15 09:21
I think the problem is with running `fish` in `Ubuntu on Windows`.

Running `git status` in `Git bash` doesn't show any file.

**Comment by joaomoreno** [comment] 2017-06-15 09:43
#13138

**Closed by joaomoreno** 2017-06-15 09:43 UTC
Labels: needs more info

**Comment by iamdevlinph** [comment] 2017-06-16 06:18
Issue was with the file configuration in git.

Need to have the following set as:
```ssh
git config --global core.autocrlf true
git config --global core.filemode false
```

Read more [here](https://github.com/Microsoft/BashOnWindows/issues/2222)
