### ISSUE TITLE
fetchTasks does not return customized tasks.

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#48831] opened 2018-04-27 13:52 UTC
package.json file:
```json
{
    "name": "name",
    "scripts": {
        "lint": "tslint *.ts"
    },
    "dependencies": {}
}
```
When I run `workspace.fetchTasks({ type: 'npm' });` I get all the tasks plus the synthetic install task
![image](https://user-images.githubusercontent.com/172399/39365618-eb5f6e04-4a31-11e8-9ddb-b7cf2cb7252b.png)

When I then customize the lint script to use a problem matcher:
```task.json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": [
                "$tslint5"
            ]
        }
    ]
}
```
Then the lint script is no longer returned:
![image](https://user-images.githubusercontent.com/172399/39365690-24d94b5a-4a32-11e8-8138-52306ad1cbc7.png)

**Comment by dbaeumer** [comment] 2018-04-27 13:57
Good catch

**Comment by dbaeumer** [comment] 2018-04-27 14:10
Actually this is tricky. I need to think a little. The problem is that they internally have a different type. I would suggest the following:

- I add a flag whether customizations should be included.
- if so I will add them. The problem might be to give them the proper type.

How urgent is this. I don't want to break something so late in the end game.

**Comment by dbaeumer** [comment] 2018-04-27 14:32
@egamma I implemented a workaround that makes your feature work. I pushed it to the following branch: https://github.com/Microsoft/vscode/tree/dbaeumer/48831

Feel free merge this next week. There are some downside to it: the type of the task will not be npm since it is a customization which I never surfaced in the API. This needs to be addressed. I opened:

https://github.com/Microsoft/vscode/issues/48835
https://github.com/Microsoft/vscode/issues/48836

**Comment by dbaeumer** [comment] 2018-04-27 14:34
Targeting for May. @egamma please retarget if you want to release.

**Comment by dbaeumer** [comment] 2018-05-23 19:15
Merged in the workaround from /48831@dbaeumer

**Closed by dbaeumer** 2018-05-23 19:15 UTC
Labels: bug, tasks

**Comment by dbaeumer** [comment] 2018-05-31 10:59
To verify:

- have a script in the package.json
- customize the script (e.g. Run Task and press the gear icon next to the entry)
- open npm script explorer
