### ISSUE TITLE
Powershell appearing without a prompt

### ISSUE THREAD

**Issue by rschuetzler** [Microsoft/vscode#72432] opened 2019-04-16 18:16 UTC
When I open an integrated terminal in VS code, the terminal doesn't work quite the way it is supposed to. First, it is scrolled all the way down to the bottom, so I cannot see the `Windows Powershell` copyright lines that appear at the top. If I scroll up, no prompt is visible. I can type, but when I do, the text appears in the middle of nowhere. If I hit enter without typing, a regular prompt appears.

![Integrated terminal with no visible prompt](https://user-images.githubusercontent.com/600775/56233796-80207280-6049-11e9-802e-1c0f56454cba.png)

![Integrated terminal with typing and no prompt visible](https://user-images.githubusercontent.com/600775/56233848-9c241400-6049-11e9-9a8a-7ec0f73c6b6c.png)

![Integrated terminal after Enter key is pressed](https://user-images.githubusercontent.com/600775/56233871-a6461280-6049-11e9-8a20-7cc85d34138d.png)

- VSCode Version: 1.33.1 (User)
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VS Code
2. Open the integrated terminal with powershell selected as the default

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment] 2019-04-18 07:37
duplicate of #57803

**Comment by rschuetzler** [comment] 2019-04-18 11:24
Thank you, @yume-chan. I looked, but probably didn't see it since it's a closed issue.

**Closed** 2019-04-18 11:23 UTC
Labels: integrated-terminal
