### ISSUE TITLE
Symlinked home path causes aliasing files to be considered different

### ISSUE THREAD

**Issue by upsj** [microsoft/vscode#118973] opened 2021-03-01 07:56 UTC
Issue Type: <b>Bug</b>

I am working on an HPC system where /home is symlinked to another path /some/other/path, which seems to cause some issues:

Having opened /home/some/user/path as a folder, VSCode seems to inconsistently follow the symlink, as the reported absolute path for files is /home/some/user/path, but when I Ctrl+click a relative path in the terminal (where the `pwd` output prints the /home path), the corresponding file in /some/other/path gets opened, which causes issues, since I now have the same file open under two different paths, and the two don't get synchronized.

I am not 100% sure whether I should report this issue on VSCode directly or here, since it seems to be related to file handling in general. An obvious workaround is to use the non-symlinked path to open the folder in VSCode, but this still points to a more fundamental issue.

Let me know if you need any additional information to reproduce this issue.

Extension version: 0.64.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-66-generic snap
Remote OS version: Linux x64 4.18.0-193.28.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 2379)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.44GB (0.67GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id e835b16f-3617-43dd-a509-21457f6ca8a2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: some-cluster|
|OS|Linux x64 4.18.0-193.28.1.el8_2.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (80 x 1280)|
|Memory (System)|377.56GB (195.84GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by upsj** [comment] 2021-03-15 14:13
Here you go, a simple example for the issue (I blacked out a bit of PII)
https://user-images.githubusercontent.com/1693511/111166220-2eb7ef80-85a0-11eb-95fe-256def86aab7.mp4

The system is a login node of an HPC system using Red Hat
```
$ cat /proc/version
Linux version 4.18.0-193.28.1.el8_2.x86_64 (mockbuild@x86-vm-07.build.eng.bos.redhat.com) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Fri Oct 16 13:38:49 EDT 2020
```
and the home directories are mounted from a Lustre parallel file system:
```
$ mount | grep pfs/
... on /pfs/data5 type lustre (rw,nosuid,nodev,flock,lazystatfs,_netdev)
```

**Comment by upsj** [comment] 2021-03-16 09:00
I just realized that my original description contained relative paths, so there seem to be two issues at play here:
```
[...@uc2n995 ginkgo]$ echo ./test
./test
[...@uc2n995 ginkgo]$ pwd
/home/kit/scc/.../ginkgo
```
Ctrl+Clicking on ./test opens the file in /pfs/data5/home, even though pwd points to the /home path. CMake and a few compilers also seem to prefer outputting /pfs/data5 paths in the terminal, so this probably all boils down to VSCode not recognizing that the two paths point to the identical file.

**Comment by phil-blain** [comment] 2021-06-09 16:33
I'm seeing the same kind of behavior on our systems. 

- My `$HOME` is set to `/home/me`. 
- `/home/me` is a symlink pointing to a mounted filesystem, i.e. `/mount/path/to/homes/me`

With this setup in place, here are some reproduction steps:

1. I open a folder using "Open Folder...", the dialog box opens and I see the content of my home folder, I choose a folder (located in my home, say `~/code/project`).
2. I open a file (say `~/code/project/path/to/file`) using the Explorer. The path shown under tab is the relative path from the root of the `project` folder (`path/to/file`)
3. I  open a Terminal and do `ls path/to/file`
4. I Ctrl-click on the "`path/to/file`" file link in the terminal
5. A new tab opens with the same file, and the path under the tab name is the full path (`/mount/path/to/homes/me/code/project/path/to/file`)

This creates a lot of confusion, and some (all?) extensions that provide "Outline" functionality (list of functions in the file, etc) **do not** work if the file is open with the full path, so this gets pretty confusing.

This behaviour happens both when launching VSCode on the machines in question (using a remote desktop solution)  and when using the Remote - SSH extension to connect to said machine from say a laptop.

**Comment by phil-blain** [comment] 2021-06-09 16:39
I'm guessing this code is at play and should be more careful somehow ?
https://github.com/microsoft/vscode/blob/31fed90614380aa4cd6a79bc5268b3255bc5c672/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L276-L311

**Comment by Tyriar** [comment] 2021-06-09 22:17
I see, I think I actually might have got the inverse issue reported and removed path resolution that was happening there. The terminal is acting as expected imo, if anything the logic to open the symlink should see that the 2 files resolve to the same file and dedupe them, I think that might be as designed currently though. Passing on.

**Comment by bpasero** [comment] 2021-06-10 05:45
> since I now have the same file open under two different paths, and the two don't get synchronized.

This is as designed, we do not attempt to resolve symlinks whenever you open a file, so you may end up with multiple editors pointing to the same file on disk.

**Comment by upsj** [comment] 2021-06-10 06:20
I can only say that this is somewhat of a hurdle when developing on such a remote system: When I compile in the terminal, all CMake outputs use the symlink-resolved location, but opening `~/project/...` points to the path containing a symlink. So when I want to address a compilation issue on a file I already have open, I Ctrl+Click on the symlink-resolved location (filename + line) and the file gets opened in a new tab instead of using the existing one.

**Comment by bpasero** [comment] 2021-06-10 06:29
@Tyriar let me know if you plan to do something from the terminal to help here. The editor is just opening the path as it is given to and it seems to me that the terminal gives the symlinked path and not the resolved path.

Otherwise, closing as designed.

**Comment by Tyriar** [comment] 2021-06-11 14:43
Well there isn't anything the terminal can do, probably the only thing we could do is resolve the symlink(s) in the cli /cc @joaomoreno

**Closed** 2021-06-19 11:26 UTC
Labels: needs more info, under-discussion

**Comment by upsj** [comment] 2021-06-19 13:25
@bpasero I understand that path resolution can in general only happen synchronously. Does that also apply to opening a folder? Because if you were to resolve symlinks when opening a folder, this problem would be fixed/avoided altogether.
