### ISSUE TITLE
Restarting no longer fixing the issue. No extensions installed, settings are seldom changed except for theme. All dark themes have this issue

### ISSUE THREAD

**Issue by london-coder** [microsoft/vscode#116057] opened 2021-02-07 18:35 UTC
Restarting no longer fixing the issue. No extensions installed, settings are seldom changed except for theme. All dark themes have this issue

_Originally posted by @Patches- in https://github.com/microsoft/vscode/issues/60298#issuecomment-428558192_

**Comment by london-coder** [comment] 2021-02-07 18:42
I have exactly the same problem as reported in the issue. In the edit window, all text is black, and in any dark theme, it is illegible. In light theme(s) the test is still black but with light background is legible. Also there is no syntax highlighting.
The VS Code version is:
Version: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:15:00.813Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

The computer is a Mac Book Pro, with OS:

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,3
  Processor Name:	6-Core Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1554.80.3.0.0 (iBridge: 18.16.14346.0.0,0)

The OS version is:
macOS Big Sur v 11.2

Im happy to provide a screen shot, if required.

**Comment by IllusionMH** [comment] 2021-02-08 02:47
/needsMoreInfo 

Do you have `editor.fontFamily` set in `settings.json`? Is it still reproducible if you comment it out? 

Can be duplicate of #100840 and Source Coode Pro is may be culprit see https://github.com/microsoft/vscode/issues/100840#issuecomment-671267067
 
Workaround https://github.com/microsoft/vscode/issues/100840#issuecomment-726769115

**Closed** 2021-02-15 11:30 UTC
Labels: needs more info
