### ISSUE TITLE
A blank auto complete box is displaying over my code and it won't go away.

### ISSUE THREAD

**Issue by DavidMarcoGonzales** [Microsoft/vscode#23419] opened 2017-03-28 13:16 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (0b19861f31ed27160c8ea73e55e39dd0213814a6, 2017-03-28T10:48:32.966Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icon-theme|jtlowe|1.5.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment] 2017-03-28 15:05
duplicate of #23414

**Closed by aeschli** 2017-03-28 15:05 UTC
