### ISSUE TITLE
VS Code Hangs sometimes when pasting

### ISSUE THREAD

**Issue by TGoyen** [microsoft/vscode#95563] opened 2020-04-17 20:33 UTC
- VSCode Version: 1.44.0
- OS Version: Widnows 10 1909

Steps to Reproduce:

1. Its not clear, but pasting seems to trigger it.
2. The issue does not happen in 1.39.X

Does this issue occur when all extensions are disabled?: Yes/No
Unknown

**Comment by TGoyen** [comment] 2020-04-21 02:59
Might be related to #28596. It does not seem to occur in 1.39.2

**Comment by TGoyen** [comment] 2020-04-21 03:02
If there is something I can do when this happens, I'd be happy to gather more data. I am seeing it about once per day.

**Comment by jjwhitney** [comment] 2020-04-27 13:30
I'm seeing this for the first time in 1.40, too, and am running Ubuntu 18.04 under KVM. After a while VS Code will recover. (Perhaps by "canceling" the paste operation?) If I go to another program and copy something to the clipboard while VS Code is frozen, it immediately recovers.

**Comment by jjwhitney** [comment] 2020-05-01 02:55
More info... I freshly installed Ubuntu 20.04 and VS Code 1.44.2 under KVM and am seeing the same result: Open any document and Ctrl+C, Ctrl+V (first copy/paste works), Ctrl+C, Ctrl+V (second one freezes VS Code).

The paste operation never completes, but after waiting a while (or using the clipboard with another program), VS Code will become responsive again.

**Comment by kisamoto** [comment] 2020-05-07 07:05
Having a similar experience.

## Setup

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.8-300.fc32.x86_64
```

## Expected Behaviour

* Copying text from "outside" VS Code (e.g. a web browser) "into" a file open in VS Code, pastes as normal with no delay.

## What actually happens

* VS Code freezes for around 50 seconds (on my system) and eventually recovers but without pasting 

## Steps to reproduce

1. Copy some text from _outside_ VS Code 
2. Paste into VSC
3. VSC hangs. Linux asks to kill or wait
4. Choosing wait, VSC will recover but *without pasting*
5. If I copy something else during the freeze, VSC will instantly recover

## Things to note

* Copy + Paste works fine within VSC itself. 
* Copy from VSC to outside VSC also works
* Copy from "outside" VSC into VSC causes the hang
* Looking at the "Performance" tab in the developer tools while this is happening the freeze seems to be being caused by the `getData` method (
[chromium performance profile](https://github.com/microsoft/vscode/files/4591249/vscodeprofile.zip) attached)
* Similar performance behaviour when "unfreezing" by copying something elsewhere

**Comment by jjwhitney** [comment] 2020-05-14 06:15
I've discovered that my bug is reproducible outside of VS Code, and is described here: https://bugs.launchpad.net/ubuntu/+source/virt-manager/+bug/1872527

I am hiding my previous posts because this bug is not related to VS Code and it is not the same one described in the original ticket. (Because it couldn't happen on a Windows machine.)

Does the bug report linked above also match what you're seeing, kisamoto?

**Comment by kisamoto** [comment] 2020-05-14 06:46
@jjwhitney Not exact but similar behaviour yes. Will also resolve my issue as I think it is not a VSCode issue and probably something else.

**Comment by rebornix** [comment] 2020-06-25 17:51
Closing as it's an upstream issue. Thanks everyone for all the information!

**Closed** 2020-06-25 17:52 UTC
