### ISSUE TITLE
Rename Symbol:  Extra period added for CSS class rename

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40184] opened 2017-12-13 23:33 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (951f5a20fc820e32a65ca05bb87af86f65027470, 2017-12-12T21:32:54.471Z)
- Stable: 1.18
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Doing a symbol rename on a class selector in CSS results and replacements with an extra period.

Steps to Reproduce:

- attempt to rename a class symbol in CSS for example:

.testClass
.testClass .otherClass

- Make small change add suffix for example 123
- Results:

..testClass123
..testClass123 .otherClass 

Reproduces without extensions: yes

**Comment by aeschli** [comment] 2017-12-15 14:37
duplicate of #7340

**Closed by aeschli** 2017-12-15 14:37 UTC
Labels: bug, css-less-sass, editor-symbols
