### ISSUE TITLE
Build fails for 1.7.2 on a Ubuntu 14.04 Travis CI instance: Error: Cannot find module 'gulp-watch'

### ISSUE THREAD

**Issue by fusion809** [Microsoft/vscode#17013] opened 2016-12-10 09:55 UTC
Hi,

- VSCode Version: 1.7.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Run:

```bash
apt-get update
apt-get install -y wget curl build-essential libx11-dev git

curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install -y nodejs

npm install -g gulp

CODE_VERSION=$(wget -cq https://github.com/Microsoft/vscode/releases -O - | grep ".tar.gz" | head -n 50 | cut -d '"' -f 2 | cut -d '/' -f 5 | sed 's|.tar.gz||g' | grep "[0-9]" | sort -u | tail -n 1)
printf "VERSION is $CODE_VERSION\n"

wget -cqO- https://github.com/Microsoft/vscode/archive/${CODE_VERSION}.tar.gz | tar xz --transform="s/vscode-${CODE_VERSION}/vscode/"
cd vscode
scripts/npm.sh install
node --max_old_space_size=2048 /usr/bin/gulp vscode-linux-x64
```

as root in a Ubuntu 14.04 Travis CI build instance. You'll get the error documented [here](https://travis-ci.org/fusion809/Code-OSS.AppImage/builds/182812418). Most importantly I get the message: 

`Error: Cannot find module 'gulp-watch'`

Thanks for your time,
Brenton

**Comment by joaomoreno** [comment] 2016-12-12 13:58
Duplicate of #13487

> Note: To install Code's dependencies as root (eg: Docker environments) make sure you use --unsafe-perm when invoking ./scripts/npm.sh.

**Closed by joaomoreno** 2016-12-12 13:58 UTC
