### ISSUE TITLE
AutoSave ignores TabSize setting

### ISSUE THREAD

**Issue by ivan-marinov** [Microsoft/vscode#15569] opened 2016-11-16 14:43 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|
---

Steps to Reproduce:

1. Set "editor.tabSize" to 2 in settings.json
2. Set "files.autoSave": "on" in settings.json
3. Edit and save a document

Expected:
Document is formatted with the set (editor.tabSize: 2) tab size .

Actual:
Document is always formatted with 4 and editor.tabSize is ignored.

**Comment by ramya-rao-a** [comment] 2016-11-16 18:38
@ivan-marinov Do you see the issue when you format without saving?

**Comment by ramya-rao-a** [comment] 2016-11-18 18:53
May be related to #15316

**Comment by ramya-rao-a** [comment] 2016-11-19 00:43
Closing as duplicate of #15316

**Closed by ramya-rao-a** 2016-11-19 00:43 UTC
