### ISSUE TITLE
Go to defintion shows multiple definitions on the same line

### ISSUE THREAD

**Issue by andrew-farries** [Microsoft/vscode#52996] opened 2018-06-26 15:21 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Clone [this demo repo](https://github.com/andrew-farries/vscode-multiple-definitions/)
2. Open the folder in VS Code
3. Open `index.jsx` and do `Go to definition` on the usage of the `App` component on line 5.

Expected behaviour:
The cursor moves to the defintion of `App` in `App.jsx`.

Actual behaviour:
The view moves to the correct place but with a popup showing two definitions on the same line:

![multiple-definitions](https://user-images.githubusercontent.com/8225907/41922170-669eae28-795c-11e8-993c-5c4bd902cc53.png)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (6.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
code-spell-checker|str|1.6.10

</details>

**Comment by mjbvz** [comment] 2018-06-26 17:52
Duplicate of #51918

**Closed by mjbvz** 2018-06-26 17:52 UTC
Labels: editor, editor-contrib
