### ISSUE TITLE
No longer can pull Welcome/Getting Started (help)

### ISSUE THREAD

**Issue by ProjectRisky-TO** [microsoft/vscode#126778] opened 2021-06-20 11:18 UTC
Issue Type: <b>Bug</b>

I was lost at the begining and was clicking randomly/ messing with settings (thought I was installing extenstions correctly).. I could use some guidance that the Getting started tab had. I'm sure there is some other way to pull the screen up but I find it easier using the help tab. If someone could find what I did wrong.,
//error msg
Unable to open 'vs_code_welcome_page': Unable to resolve resource walkThrough:/c%3A/Users/zackw/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (0.41GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/zackw/OneDrive/Desktop/New%20folder/Project --crash-reporter-id d048c7f4-eb72-4d2c-974c-664269a2db22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
vscode-pull-request-github|Git|0.27.1
jupyter|ms-|2021.6.999406279
vscodeintellicode|Vis|1.2.14
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30323119

```

</details>

**Comment by yume-chan** [comment] 2021-06-20 12:06
Duplicate of #124386

See https://github.com/microsoft/vscode/issues/124386#issuecomment-857267076

**Closed** 2021-06-30 00:58 UTC
