### ISSUE TITLE
Intellisense completely hosed on files with names starting with "temp"

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#1139] opened 2015-12-09 14:12 UTC
I have a javascript node project with some TypeScript definition files inside it. My jsconfig.json is as follows:
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs"
	}
}

If I rename a javascript source file to temp_hello.js or even temple.js (imagine if temples were in my business domain!) then the intellisense stops working for the file (it does not pick up anything in the typescript definition files) and it also forgets my jsconfig.json settings. That means I can't use ES6 syntax anymore!

**Comment by jrieken** [comment] 2015-12-09 16:15
duplicate of #703. Fix will be pushed with the Dec15 release.

**Closed by jrieken** 2015-12-09 16:15 UTC
Labels: bug
