### ISSUE TITLE
[JS] Indented implicit functions returning multiline strings won't fold

### ISSUE THREAD

**Issue by nighto** [Microsoft/vscode#72826] opened 2019-04-24 21:10 UTC
- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/397851/56693963-07aa5900-66bc-11e9-9df6-1074242a4b9c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nighto** [comment] 2019-04-24 21:13
Sorry, forgot to mention that this code is JavaScript.

**Comment by nighto** [comment] 2019-04-24 21:25
Maybe should be grouped on #3422? But multiline strings like this are "indentation based".

**Comment by mjbvz** [comment] 2019-04-24 22:53
Duplicate of https://github.com/Microsoft/TypeScript/issues/23382

**Closed by mjbvz** 2019-04-24 22:53 UTC

**Comment by nighto** [comment] 2019-04-24 23:32
This isn't TypeScript though. By the way, if anyone finds this, you can change on preferences `Editor: Folding Strategy` to be `indentation` based; with this setting, strings like this will fold.

![image](https://user-images.githubusercontent.com/397851/56700335-1e5aab00-66d0-11e9-99ce-481578828958.png)
