### ISSUE TITLE
False and Weird syntax coloring for JavaScript and TypeScript Syntax after Update 1.43

### ISSUE THREAD

**Issue by GulajavaMinistudio** [microsoft/vscode#92495] opened 2020-03-11 14:47 UTC
- VSCode Version: 1.43 (February Update 2020)
- OS Version: Ubuntu Linux and MacOS 10.11

Steps to Reproduce:

1. Install any theme in VS Code marketlace, such as one dark pro, mayukai theme, or material theme.
2. Update VS Code to version 1.43.
3.  Open JS or TS Style in VS Code 1.43.
4. Syntax coloring is changing and have some weird coloring. Very different from previous VS Code Theme Extension

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-03-11 14:53
/duplicate of #92308

Themes need to be updated to support Semantic Highlighting.
In meantime you can disable it with:
```json
"editor.semanticHighlighting.enabled": false
```

**Closed** 2020-03-11 14:53 UTC
Labels: *duplicate
