### ISSUE TITLE
Feature Request: Support search operators in Problems tab filter field

### ISSUE THREAD

**Issue by lucideer** [Microsoft/vscode#20412] opened 2017-02-10 12:06 UTC
- VSCode Version: 1.9.1
- OS Version: MacOS & Windows 7

Steps to Reproduce:

1. Open a codebase with a large number of **errors** and **warnings** in the source files
2. Open the Problems panel
3. Type the keyword _"error"_ in the filter input to show only **errors** and filter out **warnings**

Current behaviour:

- Any **warnings** which contain the word _"error"_ in their message also appear alongside **errors**

Desired behaviour:

- The possibility to categorically show only one type of problem. This could be done, for example, with search operators like _"type:error"_, &c.

Related issues:

- #8305

**Comment by sandy081** [comment] 2017-11-27 12:58
Duplicate of #8305

**Closed** 2017-11-27 12:58 UTC
Labels: *duplicate, error-list, feature-request
