### ISSUE TITLE
Docker extension does not show the containers after updaing vscode to v1.55: vscode error connect econnrefused 127.0.0.1:80

### ISSUE THREAD

**Issue by davari** [microsoft/vscode#120337] opened 2021-04-01 11:36 UTC
- VS Code Version: 1.55
- OS Version: Windows 10 Pro, Version 20H2

Steps to Reproduce:

After updating vscode to version 1.55 (March 2021), the Docker extension does not show the remote containers anymore and instead shows this error:
vscode error connect econnrefused 127.0.0.1:80
It is worth noting that the containers were shown before the update in vscode 1.54.3.

Failed temporary solution: By disabling the update.mod and downgrading vscode to version 1.54.3, the containers appear again in the remote-docker extension. However, the "Attach Visual Studio Code" option gets disappeared (apparently caused by disabling the auto-update). 

Does this issue occur when all extensions are disabled?: This bug report is about malfunctioning the remote-docker extension after updating vscode from version 1.54.3 to version 1.55. Hence, some bug in the new vscode update (1.55) should have caused the problem.

**Comment by davari** [comment] 2021-04-01 12:56
A temporary solution is suggested here: https://github.com/microsoft/vscode-docker/issues/2831#issuecomment-811864175

**Comment by chrmarti** [comment] 2021-04-01 19:54
Duplicate of https://github.com/microsoft/vscode/issues/120354

**Closed by chrmarti** 2021-04-01 19:54 UTC
