### ISSUE TITLE
GOPATH workspace setting override is not recognized by integrated terminal

### ISSUE THREAD

**Issue by AkmalU** [Microsoft/vscode#43125] opened 2018-02-07 20:22 UTC
- VSCode Version: 1.19.3
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Setting my workspace settings to this:
![screen shot 2018-02-07 at 3 21 24 pm](https://user-images.githubusercontent.com/19156520/35939599-996fe844-0c1a-11e8-8445-7790d502853b.png)

2. After relaunching vscode and opening an integrated terminal window. `echo $GOPATH` is empty.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-02-08 02:16
This works fine for me:

```js
"terminal.integrated.env.osx": {
  "GOPATH": "${env:HOME};/foo"
}
```

Also resolving environment variables is new in version 1.20 with the above format, make sure you update 😃

**Comment by AkmalU** [comment] 2018-02-08 13:53
Updated. Still have the same issue, but only with the `GOPATH`. Can set new env variables, but cannot override existing ones.

**Comment by Tyriar** [comment] 2018-02-08 20:24
@ramya-rao-a I didn't check before, just tried and could not reproduce. @AkmalU do you have any more details on the repro because we both can't see the problem?

**Closed** 2018-02-15 20:36 UTC
Labels: integrated-terminal, needs more info
