### ISSUE TITLE
Add a toggle to the explorer to enable/disable file excludes

### ISSUE THREAD

**Issue by johnalbertlopez90** [Microsoft/vscode#11308] opened 2016-08-31 12:17 UTC
When working with Angular 2 and typescript would be helpful to have an option that allows to filter files that I don't want/need to see, e.g transpiled javascript and maps files.

![image](https://cloud.githubusercontent.com/assets/6677444/18128359/afa504bc-6f5b-11e6-97bf-affbf6d2468e.png)

**Comment by dbaeumer** [comment] 2016-08-31 14:50
@johnalbertlopez90 this is available as a setting: `files.exclude`

@bpasero moving to you since a button that takes me to the setting would be helpful.

**Comment by johnalbertlopez90** [comment] 2016-08-31 14:55
Thank you @dbaeumer, but yes it would be nice to have a button and being able to activate/deactivate the filter.

**Comment by schmuli** [comment] 2016-12-01 19:06
Duplicate of #11486.

**Closed** 2016-12-01 19:37 UTC
Labels: explorer-files, feature-request
