### ISSUE TITLE
The context menu copy function is not working

### ISSUE THREAD

**Issue by evil-pechenka** [microsoft/vscode#184243] opened 2023-06-03 15:09 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.78.2
- OS Version: Windows 11 Pro 22H2

Steps to Reproduce:

1. I copy using the context menu.
2. I paste, but nothing is copied.
3. I copy using the keyboard shortcut.
4. I paste, and everything is copied.

Please watch the video.

https://github.com/microsoft/vscode/assets/109512933/21c79ed2-a064-40ea-92eb-8cdd709ac19a

**Comment by mjbvz** [comment] 2023-06-05 22:54
Duplicate of #141080

**Closed by mjbvz** 2023-06-05 22:54 UTC
