### ISSUE TITLE
API: Support hyperlinks to code locations in MarkedString

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#8223] opened 2016-06-27 21:05 UTC
- VSCode Version: Code - Insiders 1.3.0-insider (616201eff8f8d8de02edd2b9b18eae3b1096fb53, 2016-06-27T17:49:22.393Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
1. Hover over a reference to a class/method in code (e.g., TextEditor)
2. Observe hover with link to some other part of the code opens (e.g, TextDocument)
3. Click link -> nothing happens (expected: target opens, e.g. TextDocument)

**Comment by bpasero** [comment] 2016-06-28 05:21
@chrmarti can you give more details where in code this happens? would like to reproduce

**Comment by chrmarti** [comment] 2016-06-29 01:11
The example I'm using is in an extension's source file. I can reproduce with:

    import * as vscode from 'vscode';
    let editor: vscode.TextEditor;

Hovering over TextEditor shows its doc comment with a blue 'document' link in it. That link doesn't work when clicked on.

**Comment by bpasero** [comment] 2016-06-29 04:59
Cannot reproduce:

![jun-29-2016 06-58-57](https://cloud.githubusercontent.com/assets/900690/16441009/f8de620c-3dc6-11e6-9a97-f0554c713b36.gif)

**Comment by dbaeumer** [comment] 2016-06-29 07:54
I can reproduce using @chrmarti small example. Need to find out whether this is TS or the UI.

**Comment by elsigh** [comment] 2016-07-22 17:06
Is this a feature that should only work for TypeScript?

I'm new to VSCode and basically want to get jump to definition working for es6 modules.
I expect that I could click on path names in imports:

`import Foo from 'bar/baz/Foo.react.js';` <- I would like to click on `bar/baz/Foo.react.js` and be able to open that file.

Additionally I'd love to be able to click `Foo` and jump to it.

I have a jsconfig.json file at the root (above `bar` in this example) but I only see a "Loading ..." tooltip and then shows `import Foo` in the tooltip with no other enhanced functionality. This works in Atom fwiw. I'm new to Visual Studio and sorry for jumping on this bug but it looks like the description is quite close to what I'd otherwise file an issue for so wanted to avoid overspread. Again, I'm not using typescript though.

It would also be cool to have a list of features that one could expect to work to understand if things are set up correctly (or not). I have this is my `jsconfig.json` but it doesn't help (though I thought it might).
```
    "compilerOptions": {
        "target": "ES6",
        "module": "es6"
    },
```
Thanks!

**Comment by chrmarti** [comment] 2016-09-27 22:02
Also in:
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

**Comment by dbaeumer** [comment] 2016-11-15 19:34
OK. The problem is that the JS Doc for the Text Editor looks like this:

```
	/**
	 * Represents an editor that is attached to a [document](#TextDocument).
	 */

```

And the hover is interpreted as markdown which produces the link. I think there is not much the TS extension can do about this. 

@joaomoreno since you own the hover rendering is there anything you think TS can do.

**Comment by joaomoreno** [comment] 2016-11-16 08:20
Oh wow. We can just render links at standard text and take away their click behavior, in the hover.

**Comment by dbaeumer** [comment] 2016-11-16 18:02
@joaomoreno makes sense to me. Is this something you do in the hover code.

**Comment by joaomoreno** [comment] 2016-11-17 08:45
On second thought... there might be an actual URL in there that we definitely don't want to block.

**Comment by waderyan** [comment] 2016-12-09 23:02
@joaomoreno does this make sense to hand off to you?

**Comment by joaomoreno** [comment] 2016-12-12 08:31
We don't support this anywhere. We'd have to open up API such that MarkedStrings could contain hyperlinks to specific code locations. cc @jrieken

**Comment by jrieken** [comment] 2016-12-12 08:53
We have support for that - a link like `file:///my/files/Code/src/vs/code/electron-main/main.ts#L430` will bring you there.

**Comment by jrieken** [comment] 2016-12-12 08:55
If at all, this is a problem with the extension that add links for `vscode.d.ts` symbols

**Comment by joaomoreno** [comment] 2016-12-12 09:50
@waderyan Check @jrieken's comment.

**Comment by jrieken** [comment] 2016-12-12 09:55
@joaomoreno fyi - it is my extension that adds links in `vscode.d.ts`

**Comment by joaomoreno** [comment] 2016-12-12 09:56
Sorry man, too many apples to juggle.

**Comment by jrieken** [comment] 2016-12-12 10:19
Actually, not me 😆 The problem is that we are using relative markdown-links in the jsdoc-comments. So, there is two issues here: For once the opener service should fail more graceful when an invalid link is selected (this can be any kind of link) and then we could try to convince the TypeScript team to expand relative markdown links to symbols defined inside a file (stretch... if you ask me). 

I'll tackle the first and leave the rest up to @mjbvz

**Comment by wolfgangmeyers** [comment] 2017-09-13 21:37
I'd love to see support for this added

**Comment by geovanisouza92** [comment] 2018-02-23 14:12
It's an important feature. Many of my JSDoc's are lacking usefulness without this.

**Comment by mjbvz** [comment] 2019-10-10 19:04
Closing this I don't think there needs to be any api work done. Extensions/languages just need to provide a full file uri or a command uri as the markdown link

#77199 tracks supporting relative links in jsdocs specifically.

**Closed by mjbvz** 2019-10-10 19:04 UTC
Labels: api, feature-request
