### ISSUE TITLE
Two instances of vscode are opened, when opening multi root folders from the command line

### ISSUE THREAD

**Issue by MofX** [Microsoft/vscode#39181] opened 2017-11-27 11:37 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:
Run code with "code c:\ c:\windows"

Sometimes it opens just one instance of code, sometimes it opens two instances

**Comment by bpasero** [comment] 2017-11-27 11:55
@MofX if you open multiple folders from the command line like that we will automatically turn the window into an "Untitled Workspace" that will only go away if you close the window (then you get prompted to either save the workspace or not). It looks like in your case you always have the previous untitled workspace restoring, could that be true?

**Comment by MofX** [comment] 2017-11-27 13:03
Actually yes, this could be true. But what if I don't want to save the workspace? I just want to start code with a bunch of root folders (source folders that are combined by an installer when the product is shipped). I pass the folders to code on the command line, because the selected folders depend on the configuration.

Is there a switch to create a "throwaway workspace" or something like that?

**Comment by bpasero** [comment] 2017-11-28 05:35
Currently not. Duplicate of https://github.com/Microsoft/vscode/issues/30972

**Closed by bpasero** 2017-11-28 05:35 UTC
Labels: multi-root, needs more info
