### ISSUE TITLE
Need an event to signal the user is closing a webview window

### ISSUE THREAD

**Issue by allenoleksak** [Microsoft/vscode#66939] opened 2019-01-22 18:36 UTC
We would like an event to signal that the user is trying to close a webview.  

We have a use case in an extension in which we need to validate the state of what is happening in our webview before allowing the window to close.  This would be the same idea as having the pop up when you try to close an editor with unsaved changes.

**Comment by mjbvz** [comment] 2019-01-22 22:23
Duplicate of #66842

**Closed by mjbvz** 2019-01-22 22:23 UTC
