### ISSUE TITLE
Selection error in folder settings tree

### ISSUE THREAD

**Issue by crucoba** [Microsoft/vscode#71128] opened 2019-03-26 06:09 UTC
![vscode_bug](https://user-images.githubusercontent.com/8542543/54974972-050df400-4f96-11e9-8407-8b665bff385b.gif)
Issue Type: <b>Bug</b>

In folder settings, select «Grunt» in the tree, but HTML will be selected.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (9.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-svn|eli|0.1.0
svn-scm|joh|1.47.5
reload|nat|0.0.6
java|red|0.41.0
vscode-xml|red|0.4.0
svn-scm-ext|spm|1.0.7
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment] 2019-03-26 23:27
I can't reproduce this and I think it's an issue that was already fixed in Insiders.

**Closed by roblourens** 2019-03-26 23:27 UTC
