### ISSUE TITLE
Focusing debug console or output hides TypeScript version being used in status bar

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21216] opened 2017-02-22 21:46 UTC
#21037

It's strange to see the status bar jump around like this, especially when you click the debug console's monaco editor (the status bar item hides on mousedown, and show on mouseup).

It's happening because output and debug console are using monaco editors. The status bar item should show based on the last active editor, not the currently active monaco instance.

![image](https://cloud.githubusercontent.com/assets/2193314/23233899/29c8019e-f905-11e6-9ee7-a879dc975cb9.png)

**Comment by mjbvz** [comment] 2017-02-22 21:51
Duplicate of #16478

**Closed by mjbvz** 2017-02-22 21:51 UTC
Labels: bug, duplicate, typescript
