### ISSUE TITLE
Syntax coloring isn't working when function signature is spread across multiple lines

### ISSUE THREAD

**Issue by radosavljevic** [Microsoft/vscode#31439] opened 2017-07-26 08:05 UTC
- VSCode Version: 1.14.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Create index.ts
2. Enter this code:
```js
let actions = {
  setActiveQueryId: (
    activeQueryId: number,
    widgetConfigurationContext: any
  ) => {
    // Code here...
  }
};
```

You'll see that the `activeQueryId` and `widgetConfigurationContext` arguments  in the arrow function don't get colored. It seems that the problem is a next line is just after the brace.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-27 05:03
This is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/481

Unfortunately the issue has been marked as won't fix upstream due to a limitation of the grammar

**Closed by mjbvz** 2017-07-27 05:03 UTC
Labels: javascript, new release, upstream
