### ISSUE TITLE
class and struct name can't be colored in cpp and .c files

### ISSUE THREAD

**Issue by Lennon925** [Microsoft/vscode#71919] opened 2019-04-08 09:09 UTC
- VSCode Version: 1.33

Steps to Reproduce:
I defined a class like this:
![123](https://user-images.githubusercontent.com/39362073/55712173-d9bce780-5a20-11e9-834a-80f43c20295f.PNG)
![456](https://user-images.githubusercontent.com/39362073/55712184-e04b5f00-5a20-11e9-8338-701a5458e0ba.PNG)

I call this class in another file but the class name color is white, it can't highlight.

**Comment by Lennon925** [comment] 2019-04-08 09:16
It's right for typescript language,but for c and c++,it's not.

**Comment by georgejiang97** [comment] 2019-04-08 19:09
@aeschli Could I try doing this if no one minds? I'm new to open source projects, so any pointers would be appreciated!

**Comment by Lennon925** [comment] 2019-04-09 02:08
> @aeschli @mjbvz Could I try doing this if no one minds? I'm new to open source projects, so any pointers would be appreciated!

this issue has been discussed for more than two years and hasn't been solved.

**Comment by Lennon925** [comment] 2019-04-10 01:06
@alexr00 Hi Alex, How long you will take to fix this issue ? Any plan about it?

**Comment by alexr00** [comment] 2019-04-11 10:00
This is outside the capabilities of TextMate, which we use for syntax highlighting (See discussion in the C++ grammar [here](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/39). Duplicate of https://github.com/Microsoft/vscode/issues/50140

**Closed** 2019-04-11 10:00 UTC
Labels: *duplicate

**Comment by EvgeniyPeshkov** [comment] 2019-05-22 16:53
Hello. I've developed and published syntax highlighting extension based on Tree-Sitter. It provides universal syntax coloring engine for almost any programming language. Currently, C and C++ are supported OOTB. Constructing entire syntax tree, Tree-sitter efficiently overcomes all limitations of built-in TextMate grammars. I've been using it by myself for a month, so I suppose it's ready for public use.

[You can install it from VSCode Marketplace.](https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter)
[Or download .vsix package from GitHub page and install it manually.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
[**Please note**, that extension published in VS Code Marketplace will only work in Windows-x64](https://github.com/EvgeniyPeshkov/syntax-highlighter#distribution).
[For other operating systems, please download pre-compiled .vsix package.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
This will be fixed in the near future with one of the next updates.
Alternatively, you can [build extension from sources](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md).

@Lennon925 , you may give it a try. Here is coloring provided by Syntax Highlighter:
![student](https://user-images.githubusercontent.com/50870158/58193222-2efc4200-7ccb-11e9-8d10-eefe9f5ee61f.png)

**Comment by Lennon925** [comment] 2019-05-23 03:40
> Hello. I've developed and published syntax highlighting extension based on Tree-Sitter. It provides universal syntax coloring engine for almost any programming language. Currently, C and C++ are supported OOTB. Constructing entire syntax tree, Tree-sitter efficiently overcomes all limitations of built-in TextMate grammars. I've been using it by myself for a month, so I suppose it's ready for public use.
> 
> [You can install it from VSCode Marketplace.](https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter)
> [Or download .vsix package from GitHub page and install it manually.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
> [**Please note**, that extension published in VS Code Marketplace will only work in Windows-x64](https://github.com/EvgeniyPeshkov/syntax-highlighter#distribution).
> [For other operating systems, please download pre-compiled .vsix package.](https://github.com/EvgeniyPeshkov/syntax-highlighter/releases)
> This will be fixed in the near future with one of the next updates.
> Alternatively, you can [build extension from sources](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md).
> 
> @Lennon925 , you may give it a try. Here is coloring provided by Syntax Highlighter:
> ![student](https://user-images.githubusercontent.com/50870158/58193222-2efc4200-7ccb-11e9-8d10-eefe9f5ee61f.png)

Goog Job！I will try it and give you feedback later.
