### ISSUE TITLE
Error loading walkthrough content on vscode.dev

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166131] opened 2022-11-11 17:48 UTC
```
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://05g7dv7ef9i6vq72pvc86mfaee1k271hhhm8tnga2o1mm63c41ql.vscode-cdn.net/stable/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://05g7dv7ef9i6vq72pvc86mfaee1k271hhhm8tnga2o1mm63c41ql.vscode-cdn.net/stable/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): The user denied permission to use Service Worker..
```

https://user-images.githubusercontent.com/25163139/201399159-4c68035e-4043-4ac5-ac8b-8d2c18c94b13.mp4

cc @digitarald @bamurtaugh perhaps?

**Comment by joyceerhl** [comment] 2022-11-11 18:04
@daviddossett which browser is this? Maybe duplicate of https://github.com/microsoft/vscode/issues/142813

**Comment by bamurtaugh** [comment] 2022-11-11 19:52
Interesting - I'm not able to repro on Chrome. Maybe @digitarald has an idea.

**Comment by digitarald** [comment] 2022-11-11 20:15
We had some iframe/SW related issues in the past that @mattbierner looked into.

**Closed** 2024-12-09 22:56 UTC
Labels: bug, *duplicate, web, getting-started, vscode.dev
