### ISSUE TITLE
Reload page every time when re-focus on extension editor

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode#48191] opened 2018-04-19 09:06 UTC
Issue Type: <b>Bug</b>

## Issue
I can't contiune viewing the extension page progress and need to re-drag the scroll bar.

## Reproduce
1. Open any extension in the editor
1. Focus on other editor
1. Re-focus on the extension editor just opend
1. The  extension editor page reloads

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.17074

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|7.92GB (2.33GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
hugofy|akm|0.1.0
better-toml|bun|0.3.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.8
EditorConfig|Edi|0.12.1
prettier-vscode|esb|1.3.1
svg|joc|0.1.0
markdown-shortcuts|mdi|0.8.1
vscode-yaml|red|0.0.11
vscode-icons|rob|7.22.0
markdown-preview-enhanced|shd|0.3.5
gitconfig|sid|1.0.1
markdown-all-in-one|yzh|1.1.2

</details>

**Comment by mjbvz** [comment] 2018-09-20 23:04
Duplicate of #27498 and #36310

**Closed by mjbvz** 2018-09-20 23:04 UTC
Labels: bug, extensions
