### ISSUE TITLE
Could VSCode use "region" just like visual studio or in next version?

### ISSUE THREAD

**Issue by SiriusGuo** [Microsoft/vscode#12207] opened 2016-09-18 03:30 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10 x64

In visual studio we can use region like that:
```
//region region-desc

//endregion
```

It can be used in jetbrains idea also:
![image](https://cloud.githubusercontent.com/assets/6395714/18612688/0cb30d8a-7d93-11e6-889d-171eac09a539.png)
-------------------------------------------
![image](https://cloud.githubusercontent.com/assets/6395714/18612702/591bbf0a-7d93-11e6-91c8-7e45bb9d49fd.png)
-------------------------------------------
![image](https://cloud.githubusercontent.com/assets/6395714/18612691/1f313158-7d93-11e6-8d76-26727b4c6098.png)

Can VSCode use this? That's really a nice feture right?

**Comment by mrmlnc** [comment] 2016-09-18 08:45
Duplicate of #12146. Please, add your description to already exists issue.

**Comment by bpasero** [comment] 2016-09-19 05:11
I believe this is about C# and so it should be reported to the C# team.

**Closed by bpasero** 2016-09-19 05:11 UTC
