### ISSUE TITLE
Drag and drop from FTP folder in explorer into editor DELETES the file on FTP server

### ISSUE THREAD

**Issue by frevds** [microsoft/vscode#25196] opened 2017-04-22 21:56 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Not sure if this is a bug in the explorer or VS Code, but when I open an FTP site in the Windows Explorer and drop a file into the editor, not only does it not open it (would be too good), but the file vanishes from the FTP site, as if it was moved somewhere (just that nothing happens in the editor, no feedback at all). 

The problem is most certainly a wrong drop-action-feedback to the windows explorer (Move action). 
However, one does NOT expect this behaviour and is pretty shocked when the file is suddenly lost, especially if one did not backup it before (which one rarely does before opening it).

**Comment by bpasero** [comment] 2017-04-24 06:03
We do not move the file, never. It is always a copy. Looks like this was already reported via https://github.com/Microsoft/vscode/issues/21868 but not giving enough information. 

@frevds does it reproduce when you drop the file into the editor area to open it? If you drop it into the explorer, we try to copy it to that location, if you drop to the editor we try to just open it.

**Comment by frevds** [comment] 2017-04-24 08:04
@bpasero Yes it was reported earlier, with even better documentation, but then closed for no apparent reason. Just try it on your own, it's not complicated to replicate - open ftp://bla in explorer, then drag a file into the editor area - it does not open (nothing happens), but the file gets MOVED from FTP into Nirvana. The end result is the file is LOST, which should not happen (you don't want to delete some component of an old web project just because you wanted to look at a file).

**Comment by bpasero** [comment] 2017-04-24 15:08
I can reproduce (found an online free ftp server with readonly access here: https://test.rebex.net/. I am not sure how to prevent this from happening though, I can also reproduce when dropping a file into a bare Electron application. 

Open for ideas if someone has some. Might be related to the allowed drop feedback (e.g. `copyMove` vs. just `copy`).

**Comment by thomas-educationdynamics** [comment] 2017-06-02 13:40
Hello community,
Here is a screenshot of what happens when trying to DND from filezilla to VSC..
![vs studio code ftp issue](https://cloud.githubusercontent.com/assets/23404939/26728208/742218a4-4777-11e7-8295-dcb8559c2716.png)

**Comment by ihalip** [comment] 2017-06-18 15:05
I also reproduced this with the electron release package. I'm going to dig a bit through electron code.

**Comment by ihalip** [comment] 2017-06-18 19:47
I can't pinpoint the root cause of this issue, but I did a bit of digging.

How drag&drop works in Windows is that when an application did `RegisterDragDrop()`, it receives notifications through the `IDropTarget` interface. My understanding is that electron should specify in the implementation of this interface the effect of the drops it supports, since Windows Explorer will always attempt to use the effects in this order: move, copy, link, none.

Unfortunately, I find it quite difficult to navigate through the Chromium source code for the actual implementation used for the `IDropTarget` interface.

**Comment by frevds** [comment] 2017-06-18 19:56
Good digging, the error might be there, somewhere. 
If so, then it isn't to be found in the supported-actions while the drag operation is ongoing, but in the effective action after the drop. Apparently Electron sends the wrong feedback of what it did with the file and the Windows Explorer deletes the source file form the FTP site.  Of course, the supported-actions feedback (ondragstart/ondragenter/ondragover/ondragleave) should not include the move action either, but it isn't directly responsible, only the ondrop implementation needs to be checked.

**Comment by bpasero** [comment] 2017-06-19 05:16
I this reproduces in Electron alone I suggest to continue the discussion in an issue here: https://github.com/atom/electron

**Comment by darkalfx** [comment] 2019-06-22 15:16
This bug has been fixed in later version of Electron.

**However**, VS Code **STILL** deletes the file when dragging them from FTP into the Editor Group:
![image](https://user-images.githubusercontent.com/22474506/59965656-215ef580-94df-11e9-9bc3-59ecb6e3321c.png)

So the bug is definitely still present.

**Comment by epicfaace** [comment] 2019-07-20 15:31
Any update on this @bpasero ? I accidentally deleted files this way...

**Closed** 2020-10-12 09:20 UTC
Labels: *out-of-scope, electron, upstream, upstream-issue-linked, windows, workbench-dnd, workbench-os-integration
