### ISSUE TITLE
ServiceWorker/CacheStorage folder grows indefinitely large

### ISSUE THREAD

**Issue by matthewjamesadam** [microsoft/vscode#166632] opened 2022-11-17 19:53 UTC
Does this issue occur when all extensions are disabled?: No -- requires an extension with webviews

- VS Code Version: 1.73.1
- OS Version: MacOS 12.5.1

Hello friends!

Our team is working on a VSCode extension, and uses VSCode both as a development platform and for testing our extension.  A coworker recently noticed that VSCode is storing an awful lot of data in `~/Library/Application Support/Code/Service Worker/CacheStorage` (on a Mac) -- 145GB in my case, though other coworkers of mine have seen the same thing.

The folder has thousands of randomly-named folders, each of which seem to contain copies of our extension's webview bundles.  It doesn't look like these folders ever get deleted.  As developers we often run VSCode with these bundles unoptimized (and un-tree-shaken), so they can each be fairly large, and this adds up.

Is there any advice on why these folders are sticking around?  Are they expected to be automatically cleaned up?  Could it possibly be something our extension's webview is doing that could cause this?

Thanks!

**Comment by matthewjamesadam** [comment] 2022-11-17 21:37
I've done some investigation and noticed that an additional folder is created for every webview in the extension, and what's more that every time a webview bundle is modified (and the webview viewed), a new folder is created.  I'm guessing that the random folder name is a hash of the webview content or something.

**Comment by mjbvz** [comment] 2022-11-17 23:03
Duplicate of #131226

**Closed by mjbvz** 2022-11-17 23:03 UTC
