### ISSUE TITLE
Open files are not auto-saved, when extension installation restarts the VS Code

### ISSUE THREAD

**Issue by maroonedsia** [Microsoft/vscode#6068] opened 2016-05-03 15:17 UTC
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open and edit a file.
2. Install an extension that requires restart.
3. Click restart button.
4. The changes you've made to the file is not auto-saved and they are gone.

**Comment by bpasero** [comment] 2016-05-03 17:25
@maroonedsia I cannot reproduce. Could it be that you did all of this in an `Extension Host` window where you debug/run your extension? That is the only window where we actually do not prompt for saving when you close or restart.

**Comment by maroonedsia** [comment] 2016-05-06 18:16
Hi @bpasero,

Thanks for your reply, sorry for the confusion.

You're right, VS Code ask for saving the files, but they're not auto-saved. As a comparison, Sublime saves open files to a temp directory, so, if it crashes or restarts, I never lose anything.

Thanks again,
Sia

**Comment by bpasero** [comment] 2016-05-07 08:24
@maroonedsia but that is a different thing. can you clarify how you are loosing data when you are asked to restart? are you not being asked to save?

**Comment by bpasero** [comment] 2016-05-13 05:05
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-05-13 05:05 UTC
Labels: needs more info
