### ISSUE TITLE
Python: Add 'params' to 'function' tooltips

### ISSUE THREAD

**Issue by C-PyLx** [Microsoft/vscode#62192] opened 2018-10-30 19:34 UTC
Hi, very thanks for this application and we like it.
We wants from you to add (function parameters) into (functions) tooltip.

This property helps us to find the parameters in our pro programs.

**Comment by mjbvz** [comment] 2018-10-30 20:44
Duplicate of #61996

Don't post the same issue here. Open an issue against the python extension

**Closed by mjbvz** 2018-10-30 20:44 UTC
Labels: javascript
