### ISSUE TITLE
No Intellisense for `tags` in a package.json

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#231957] opened 2024-10-22 17:03 UTC
Testing #231887

1. Add the `"tags"` field to an existing setting
2. Hover over the `"tags"` property name
3. :bug: no Intellisense

**Comment by rzhao271** [comment] 2024-10-22 20:23
Duplicate of https://github.com/microsoft/vscode/issues/231917

**Closed by rzhao271** 2024-10-22 20:23 UTC
