### ISSUE TITLE
24x7 IntelliSense should use language at position, not of file

### ISSUE THREAD

**Issue by ebbeknudsen** [Microsoft/vscode#32756] opened 2017-08-18 06:54 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
sass-lint|gle|0.0.4
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Create .tsx file
2. Create render method
3. return (`<div></div>`) in render method
4. Start typing div.col-lg-12 inside the previous div you created
5. Emmet will work with div.col-lg, but when you add div.col-lg-12 it doesn't work anymore

Reproduces without extensions: Yes/No Yes

**Comment by ramya-rao-a** [comment] 2017-08-20 19:48
@ebbeknudsen Until this is resolved you can trigger the suggestions manually after the number at the end of your abbreviation by pressing `Ctrl+Space`

**Comment by ramya-rao-a** [comment] 2017-08-20 20:29
@jrieken @aeschli 

`jsx-tags` is an embedded language inside javascript or typescript.

The wordPattern for `jsx-tags` allows `-`, but the one for typescript/javascript doesn't.
See https://github.com/Microsoft/vscode/blob/release/1.15/extensions/typescript/src/typescriptMain.ts#L153 and https://github.com/Microsoft/vscode/blob/release/1.15/extensions/typescript/src/typescriptMain.ts#L306

The quick suggestions are triggered for words as defined by wordPatterns of the language of the document and do not consider embedded languages.

Is there anything we can do to honor the word pattern as defined by the embedded language instead?

**Comment by jrieken** [comment] 2017-08-21 06:17
Closing as dupe of #32201

**Comment by ramya-rao-a** [comment] 2017-08-21 06:35
@jrieken #32201 is about changing the default where we show the quick suggestions at the end of a word

Where as this issue is about considering word definition as defined by the embedded language instead of the language of the parent.

Not really the same....

**Comment by jrieken** [comment] 2017-08-21 07:35
you are right... Renamed the issue accordingly

**Comment by jrieken** [comment] 2017-08-22 08:13
Hm, the problem is that [`IModel#getWordAtPosition`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModelWithTokens.ts#L409) doesn't use the word def of the language at the current position. 

@alexandrudima Is that something we can change?

**Comment by roblourens** [comment] 2017-08-30 21:36
Seems to work the same, and the suggestions box disappears on each `-`, and doesn't popup automatically again when I get to `12` - was that the original issue?

**Comment by ramya-rao-a** [comment] 2017-08-30 21:52
@roblourens Yes that was the issue. I can repro it too.

**Comment by jrieken** [comment] 2017-08-31 07:39
@roblourens How large is your file? We do call `tokenizeIfCheap` to get the right language (and thereby word definition) at that position. @alexandrudima for more insights

**Comment by alexandrudima** [comment] 2017-08-31 07:52
@jrieken Can you reproduce and confirm it is caused by the change to use `tokenizeIfCheap` ?

**Comment by jrieken** [comment] 2017-08-31 08:44
No, I cannot reproduce that's my problem. When debugging I see that the word at position is `col-`. Tho I also don't get emmet suggestion, but that is true for all of my dev setup /cc @ramya-rao-a for help...

This is what the debugger shows after typing `-` and when computing the leading word to ask for suggestions.

<img width="1298" alt="screen shot 2017-08-31 at 10 42 40" src="https://user-images.githubusercontent.com/1794099/29914570-4b9d41ac-8e39-11e7-948a-066d778511f2.png">

**Comment by alexandrudima** [comment] 2017-08-31 09:30
I also added some log statements and after pressing `-` the UI makes a request for completion items, but it receives an empty array:

<img width="1650" alt="screen shot 2017-08-31 at 11 29 07" src="https://user-images.githubusercontent.com/5047891/29916672-b90b9404-8e3f-11e7-8b64-101ce546ab0f.png">

**Comment by jrieken** [comment] 2017-08-31 13:07
@ramya-rao-a Maybe there is a misunderstanding because the title of this issue is "24x7 IntelliSense should use language at position, not of file" which is something we are not doing and cannot do. What this does is use the word definition of the language at the position, the request is still made for the whole document.

**Comment by ramya-rao-a** [comment] 2017-09-02 22:38
@jrieken 

> what this does is use the word definition of the language at the position,

Yes, that's what I was hoping for.

@jrieken @alexandrudima 

`.col-` would get empty array from emmet completion provider.
`.col-1` would get a non empty array from emmet completion provider.

I can no longer repro the issue inside tags in a jsx file.
Will mark this as verified

@jrieken I can solve this for all languages in general by including numbers 0-9 as trigger characters for emmet completion provider. This makes me wonder if the trigger characters should also support regex. What do you think?

**Closed by ramya-rao-a** 2017-09-02 22:38 UTC
Labels: emmet, feature-request, needs more info, verification-needed

**Comment by jrieken** [comment] 2017-09-04 07:30
> This makes me wonder if the trigger characters should also support regex. What do you think?

this: https://github.com/Microsoft/vscode/issues/33697#issuecomment-326885611
