### ISSUE TITLE
Remember cursor positions and opened editors on hot exit

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15133] opened 2016-11-07 22:23 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (c2418f46d20464a893dc5db6449e9d79766eadc4, 2016-11-07T21:40:57.134Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.7|
|python|donjayamanne|0.5.0|
|tslint|eg2|0.5.39|

---

Steps to Reproduce:

1. Type something in an editor
2. Add a second editor side-by-side
3. Terminate task from task manager
4. Restart: Side-by-side editor is gone and cursor position in edited file is lost

**Comment by chrmarti** [comment] 2016-11-07 22:29
Also: Currently focused editor tab is lost.

**Comment by Tyriar** [comment] 2016-11-07 22:34
@chrmarti focus and cursor position is expected if you had an untitled file focused due to https://github.com/Microsoft/vscode/issues/14116. I'm not sure if cursor position restore works for text files or not.

**Comment by chrmarti** [comment] 2016-11-07 23:21
It does work if you exit the workbench regularly. I was simulating a crash by terminating the task from the task manager.

**Comment by Tyriar** [comment] 2016-11-14 18:41
This currently works for text files but not untitled files. Closing as a duplicate of https://github.com/Microsoft/vscode/issues/14116 as that's the root cause.

**Closed by Tyriar** 2016-11-14 18:41 UTC
Labels: bug, hot-exit
