### ISSUE TITLE
chinese input window far away from cursor on 4K screen

### ISSUE THREAD

**Issue by luv39** [microsoft/vscode#78450] opened 2019-08-04 12:37 UTC
Issue Type: <b>Bug</b>

OS: Mint 18.2 sonya
screen: 4k
input: fcitx-googlepinyin

![](https://raw.githubusercontent.com/luv39/cloudimage/master/img/2019-08-04%2020.29.46.jpeg)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2427)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.66GB (12.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
typewriterscrollmode|and|0.1.1
vscode-language-pack-zh-hans|MS-|1.37.3
python|ms-|2019.6.24221
vscode-paste-image|mus|1.0.4
markdown-preview-enhanced|shd|0.4.3
pdf|tom|0.5.0
vscode-icons|vsc|9.2.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2019-08-05 17:52
/duplicate of https://github.com/microsoft/vscode/issues/58735

**Closed** 2019-08-05 17:52 UTC
Labels: *duplicate, editor-ime, linux
