### ISSUE TITLE
Very serious coding problem

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#82426] opened 2019-10-12 12:21 UTC
Very serious coding problem
![vscode](https://user-images.githubusercontent.com/27546390/66701300-87d97f00-ed2d-11e9-850b-d77d67fb3b8f.png)
Look at the idea
![idea1](https://user-images.githubusercontent.com/27546390/66701303-9031ba00-ed2d-11e9-87f3-776537ddd4a8.png)
![idea2](https://user-images.githubusercontent.com/27546390/66701322-ba837780-ed2d-11e9-8ada-de2bb979e236.png)
![idea3](https://user-images.githubusercontent.com/27546390/66701329-c8d19380-ed2d-11e9-9432-025356acf5f3.png)

**Comment by IllusionMH** [comment] 2019-10-12 21:38
Looks like duplicate of #29757 and #29126

In meantime you can use <kbd>Ctrl+Space</kbd> (or click on blue circle with i) to show details where you can see full entry.

**Comment by 395053994** [comment] 2019-10-13 00:39
This fatal problem should be solved in the first place! Can't write java application. Is this what you hope to see? Why hasn't anyone been working to solve it? . I really doubt how far vscode can go, and whether it considers the ability of back-end development. Or is it a free tool itself?




------------------ 原始邮件 ------------------
发件人: "Andrii Dieiev"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 凌晨5:40
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Very serious coding problem (#82426)




Looks like duplicate of #29757 and #29126
 
In meantime you can use Ctrl+Space (or click on blue circle with i) to show details where you can see full entry.

**Comment by 395053994** [comment] 2019-10-13 00:49
Each issue of the most recent update is to change the icon, and the problem affecting the encoding should be prioritized. Java. . .




------------------ 原始邮件 ------------------
发件人: "Andrii Dieiev"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 凌晨5:40
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Very serious coding problem (#82426)




Looks like duplicate of #29757 and #29126
 
In meantime you can use Ctrl+Space (or click on blue circle with i) to show details where you can see full entry.

**Comment by IllusionMH** [comment] 2019-10-13 00:59
Have you tried to use Read more... as suggested workaround before stating that this is fatal problem?

And as usually with OSS you are welcome to submit fix.

**Closed** 2019-10-13 02:28 UTC
