### ISSUE TITLE
Panel Controls are not Visible

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#24703] opened 2017-04-13 18:18 UTC
- VSCode Version: Code - Insiders 1.12.0-insider (40e58bfba3191b54912c4252b6b91ad57d90a168, 2017-04-12T09:01:04.094Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|theme-sapphire|Tyriar|0.1.0|
|vscode-reveal|evilz|0.0.9|
|vscode-icon-theme|jtlowe|1.5.0|
|Go|lukehoban|0.6.59|
|mssql|ms-mssql|0.3.0|
|live-server-preview|negokaz|0.0.4|
|java|redhat|0.1.0|
|todotasks|sandy081|0.4.0|
|MDTools|seanmcbreen|1.0.1|
|code-spell-checker|streetsidesoftware|1.0.2|;

---

Steps to Reproduce:

1. Toggle the panel
2. No controls are available on the right hand top area
![image](https://cloud.githubusercontent.com/assets/1051190/25018029/b74bfb54-203a-11e7-8e4c-70127ad28728.png)

Expected..
![image](https://cloud.githubusercontent.com/assets/1051190/25018040/c35f6a20-203a-11e7-8bce-244c0ef26dcb.png)

3. An error is also displayed
![image](https://cloud.githubusercontent.com/assets/1051190/25018021/ac2bca74-203a-11e7-9e1e-8946bdefcde1.png)

4. The same thing happens with all extensions disabled i.e. `code . --disable-extensions`

**Comment by aeschli** [comment] 2017-04-14 20:01
duplicate of #24584

**Closed by aeschli** 2017-04-14 20:01 UTC
Labels: bug
