### ISSUE TITLE
On Mac, paths passed to extension do not match path encoding of unicode combining characters used by file system

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#88455] opened 2020-01-10 22:43 UTC
On Mac, paths received by our extension from VS Code do not match paths returned from the file system when they include unicode combining characters.

For example, I have a path with a 'u' followed by a [combining diaeresis](https://www.fileformat.info/info/unicode/char/0308/index.htm).  Using `ls | hexdump -C` I see the 'u' followed by `0xCC 0x88`.  However, in our extension, the uri we receive on didOpen indicates the single-character version.  In `_fsPath`, I see 0xFC (ASCII version).  In `_formatted`, I see `%C3%BC` (combined character).

We use realpath() to canonicalize paths, which returns us the original 'u' followed by `0xCC 0x88`. That path is not recognized by VS Code as the same file path.  So, if it's logged and the user clicks on the path, an additional copy of the file is open.  'Problems' we report using the file system version of the path do not result in squiggles in the file.

Is it a bug that these paths are diverging from those used by the file system?  Or, if it's intentional, should VS Code be considering paths with and without these modifications to be equivalent?  Or, can we get information on what changes may be made, so we can make exactly the same changes to the path, to ensure our paths match.

This is based on a user reported issue in cpptools.  https://github.com/microsoft/vscode-cpptools/issues/4712

**Comment by bpasero** [comment] 2020-01-13 06:48
@Colengms that's right, VSCode is doing some form of normalization so that we can ensure that we are not introducing 2 versions of the same file into our system. Code is here:

https://github.com/microsoft/vscode/blob/22e4d75bd07b1ec7362c69da9dda7667eae95374/src/vs/base/common/normalization.ts#L17

I would argue this is the same and duplicate of the more general issue https://github.com/microsoft/vscode/issues/12448

**Closed** 2020-01-13 06:48 UTC
Labels: *duplicate
