### ISSUE TITLE
caret sticking midway when scrolling up in vs code

### ISSUE THREAD

**Issue by the-a-man-006** [microsoft/vscode#194766] opened 2023-10-04 01:28 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.3
- OS Version: Windows 10

Steps to Reproduce:

1. Scroll down (holding the down arrow).
2. Scroll up (holding the up arrow).

The issue persists when using PageDown/PageUp too.

![vs_code_caret_scrolling_bug](https://github.com/microsoft/vscode/assets/58506175/363ecc94-a681-4078-bbb3-456c447a2b64)

**Comment by the-a-man-006** [comment] 2023-10-04 14:21
Pretty funny bug, I admit, but it's seriously preventing me from working... I'd really appreciate some help...

**Comment by the-a-man-006** [comment] 2023-10-04 20:04
Ok, I narrowed it down to this particular setting:
![image](https://github.com/microsoft/vscode/assets/58506175/5f3ddfd1-a42b-4325-8928-b59fd72540ff)

Any clue? To be clear, I don't want to outright disable Sticky Scroll; was on Visual Studio Preview channel for many a month just for Sticky Scroll; would be sad to have to sacrifice it in VS Code...

**Comment by the-a-man-006** [comment] 2023-10-04 20:28
Sounds like might be related to https://github.com/microsoft/vscode/issues/190409 ???

**Comment by alexdima** [comment] 2023-12-05 08:29
The problem here is that we always reserve N lines above when sticky scroll is enabled in case it wants to render. We do this even if sticky scroll doesn't have something to render in this particular scope. The reason is because we don't know when doing the scrolling itself if sticky scroll has or hasn't something to show.

**Comment by aiday-mar** [comment] 2024-12-13 16:18
duplicate of https://github.com/microsoft/vscode/issues/227750

**Closed by aiday-mar** 2024-12-13 16:18 UTC
Labels: bug, editor-core, editor-sticky-scroll
