### ISSUE TITLE
VS Code just deleted my file.

### ISSUE THREAD

**Issue by joshpitzalis** [Microsoft/vscode#63573] opened 2018-11-21 12:14 UTC
- VSCode Version: Version 1.29.1 (1.29.1)
- OS Version: OSX 10.14.1 Beta (18B50c)

One file, gone.

Unfortunately I didn't save to git.

It was my entire days work.

I'm not sure what happened.

I didn't do anything.

My terminal said `ENOSPC no space left on device` as an error in the file on question. And the file went blank. I checked trash but nothing. The actual file is still there but there is nothing in it. It like someone just copied all the text in the file and deleted it.

I have about 2GB on my hard drive so space isn't an issue.

I love you vs code but this is pretty hard core.

I don't understand why this is even possible.

**Comment by wugq** [comment] 2018-11-22 00:12
The same issue happened to me. I was lucky that the file was commit to git. I can restore the file easily.

I just checked logs at ~/.config/Code/logs, but didn't find any related message.
How can I provide more information about this issue? 

VS Code: 1.29.1-1542309157
OS: Debian GNU/Linux 9.6 (stretch)

**Comment by bpasero** [comment] 2018-11-22 06:42
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/34915. It is certainly possible that the OS reserves a little bit of disk space to operate so that you see this error even though there is still some disk space. Sorry for that, we should get https://github.com/Microsoft/vscode/issues/34915 addressed asap.

**Closed by bpasero** 2018-11-22 06:42 UTC
