### ISSUE TITLE
[Accessibility]A11y_VSCode_InteractiveEditorPlayground_ScreenReader:NVDA reads clickable with lists,links.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#51848] opened 2018-06-14 07:20 UTC
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details:**
ScreenReader[NVDA2018.2],JAWS[18.0.5038],MAS1.3.1
**Repro Steps:**
1. Launch VS Code while NVDA is ON.
2. Navigate to Help(Alt+H) menu option and select "Interactive Editor Playground" from dropdown.
3. Read all the lists,list items,links present on the screen while navigating using "Tab" key.

**Actual:**
NVDA reads the word "Clickable" with each list,listitem and headings which are not interactive.
Same issue observed in JAWS also.
**Expected:**
NVDA should only read the name of the control along with relevant state,value and role. It should not read "Clickable" for every control present on the screen.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
The user will not be able to get clarity about control's name,state,role,value and other important info if screenreader reads "clickable" after each word it reads.

**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:** 
![accessibility a11y_vscode_interactiveeditorplayground_screenreader](https://user-images.githubusercontent.com/39204909/41397303-65371b2c-6fd1-11e8-9e2f-ed884b3fc087.png)

**Comment by isidorn** [comment] 2018-07-03 15:18
Duplicate of https://github.com/Microsoft/vscode/issues/51077

**Closed by isidorn** 2018-07-03 15:18 UTC
Labels: accessibility
