### ISSUE TITLE
"Stage selected lines" in GIT view disabled

### ISSUE THREAD

**Issue by jacek-dargiel** [Microsoft/vscode#2839] opened 2016-02-09 12:36 UTC
The "Stage selected lines" option in the "more" menu of the GIT view is always disabled (grayed out) after updating to 0.10.8.

**Comment by joaomoreno** [comment] 2016-02-10 08:06
@isidorn Are you sure this is ok? The action should only be enabled if the intersection between the editor selection and the changes is not empty.

Reopening for discussion.

**Comment by isidorn** [comment] 2016-02-10 10:23
Ok I reverted my change.
@jacek-dargiel do you have exact reproducable steps, since it is hard for us to repro this. If not I will keep an eye open since I know it happens seldomly

**Comment by jacek-dargiel** [comment] 2016-02-10 10:31
Oh, this is quite strange, yesterday I couldn't get it to work at all, the option was disabled all the time no matter what I did or how I made the selection. Today it works just fine.

**Comment by isidorn** [comment] 2016-02-10 10:43
Yeah it is funky, please keep an eye open and let us know if you see some pattern

**Comment by jacek-dargiel** [comment] 2016-02-22 14:11
Hi guy's. I think i have found a pattern. Here are the steps to reproduce:

0. You will need at least two files with unstaged changes.
1. In the git view, select the first unstaged file.
2. Make a selection containing all changes in the file
3. Select "Stage selected lines" from the menu. At this point all changes in this file have been staged, the file is moved to the "staged changes" section of the git view, the side-by-side view switches to the next file on the list. The selected area is retained from the previous file, although the content is changed.
4. If you make a new selection containing changes in the second file, the "Stage selected lines" option is incorrectly disabled.

**Comment by joaomoreno** [comment] 2016-02-22 15:09
Those steps don't repro for me. Also, the part in which you mention

> the side-by-side view switches to the next file on the list

is incorrect. The side-by-side view switches to the index version of that file, instead of the working file version.

**Comment by isidorn** [comment] 2016-07-21 07:59
Did not see this action disabled for quite some time -> closing until somebody sees it again (hopefully with steps)

**Comment by johneriksson** [comment] 2016-11-16 08:25
I just experienced this. My "stage selected lines" option was grayed out for no apparent reason. I tried closing files & tabs, removing the changes and then trying again but no luck. Restarting Code fixed it. Now I am not able to reproduce it however, so this might not be useful information to you... :/

**Comment by isidorn** [comment] 2016-11-16 09:06
I confess I also see it once evert couple of months -> let reopen and try to get steps

**Comment by yashcr07** [comment] 2017-02-28 11:52
Has the option to stage selected lines been disabled ?
I am on v1.10.0 insiders
using Windows 10

![vscode](https://cloud.githubusercontent.com/assets/7511296/23404325/553d1498-fdda-11e6-87cb-d7388c292ba2.png)

**Comment by isidorn** [comment] 2017-02-28 13:55
@yashcr07 this action has been moved to the command palette

![screen shot 2017-02-28 at 14 54 59](https://cloud.githubusercontent.com/assets/1926584/23407797/ebeefbb4-fdc5-11e6-8ca1-c4c6c056a8fd.png)

**Comment by isidorn** [comment] 2017-04-13 08:30
Git is now an extension and this command is a global workbench command which is always enabled -> closing

**Closed by isidorn** 2017-04-13 08:30 UTC
Labels: bug, git
