### ISSUE TITLE
Can't compile native modules due to iojs errors

### ISSUE THREAD

**Issue by FFY00** [Microsoft/vscode#57711] opened 2018-08-31 19:31 UTC
- VSCode Version: 1.26.1
- OS Version: Arch Linux

Steps to Reproduce:

###### All the steps were run in a clean instalation
1. yarn install

Output:
```
error /build/code/src/code/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /build/code/src/code/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | linux | x64
gyp http GET https://atom.io/download/electron/v2.0.5/iojs-v2.0.5.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.5/iojs-v2.0.5.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.5/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.5/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/build/code/src/code/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/build/.node-gyp/iojs-2.0.5/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/build/.node-gyp/iojs-2.0.5',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/build/.node-gyp/iojs-2.0.5/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/build/code/src/code/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/build/code/src/code/node_modules/native-keymap/build'
  CXX(target) Release/obj.target/keymapping/src/string_conversion.o
  CXX(target) Release/obj.target/keymapping/src/keymapping.o
  CXX(target) Release/obj.target/keymapping/deps/chromium/x/keysym_to_unicode.o
  CXX(target) Release/obj.target/keymapping/src/keyboard_x.o
In file included from /build/.node-gyp/iojs-2.0.5/src/node.h:63,
                 from ../src/keymapping.cc:6:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:15: error: unterminated #ifndef
 #ifndef INCLUDE_V8_H_
 
In file included from /build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:26,
                 from /build/.node-gyp/iojs-2.0.5/src/node.h:63,
                 from ../src/keymapping.cc:6:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8config.h:294:20: error: ‘inline’ can only be specified for functions
 # define V8_INLINE inline __attribute__((always_inline))
                    ^~~~~~
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:8873:3: note: in expansion of macro ‘V8_INLINE’
   V8_INLINE static internal::Object* IntToSmi(int value) {
   ^~~~~~~~~
In file included from ../src/keymapping.cc:6:
/build/.node-gyp/iojs-2.0.5/src/node.h:97:8: warning: attribute ignored in declaration of ‘struct v8::internal::SmiTagging<8>::uv_loop_s’ [-Wattributes]
 struct uv_loop_s;
        ^~~~~~~~~
/build/.node-gyp/iojs-2.0.5/src/node.h:97:8: note: attribute for ‘struct v8::internal::SmiTagging<8>::uv_loop_s’ must follow the ‘struct’ keyword
/build/.node-gyp/iojs-2.0.5/src/node.h:100:1: error: expected unqualified-id before ‘namespace’
 namespace v8 {
 ^~~~~~~~~
/build/.node-gyp/iojs-2.0.5/src/node.h:106:1: error: expected unqualified-id before ‘namespace’
 namespace node {
 ^~~~~~~~~
In file included from /usr/include/features.h:428,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/stdint.h:9,
                 from /build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:19,
                 from /build/.node-gyp/iojs-2.0.5/src/node.h:63,
                 from ../src/keymapping.cc:6:
/usr/include/assert.h:64:1: error: expected unqualified-id before string constant
 __BEGIN_DECLS
 ^~~~~~~~~~~~~
In file included from ../src/keymapping.cc:6:
/build/.node-gyp/iojs-2.0.5/src/node.h:197:1: error: expected unqualified-id before ‘namespace’
 namespace node {
 ^~~~~~~~~
In file included from /usr/include/c++/8.2.0/map:60,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.2.0/bits/stl_tree.h:75:1: error: expected unqualified-id before ‘namespace’
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from /usr/include/c++/8.2.0/map:61,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.2.0/bits/stl_map.h:66:1: error: expected unqualified-id before ‘namespace’
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from /usr/include/c++/8.2.0/map:62,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.2.0/bits/stl_multimap.h:64:1: error: expected unqualified-id before ‘namespace’
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from ../src/keymapping.h:10,
                 from ../src/keymapping.cc:9:
/build/.node-gyp/iojs-2.0.5/deps/uv/include/uv.h:27:8: error: expected unqualified-id before string constant
 extern "C" {
        ^~~
In file included from ../src/keymapping.cc:9:
../src/keymapping.h:15:1: error: expected unqualified-id before ‘namespace’
 namespace vscode_keyboard {
 ^~~~~~~~~
../src/keymapping.cc:11:1: error: expected unqualified-id before ‘namespace’
 namespace vscode_keyboard {
 ^~~~~~~~~
../src/keymapping.cc:30:1: error: expected ‘}’ at end of input
 } // namespace vscode_keyboard
 ^
In file included from /build/.node-gyp/iojs-2.0.5/src/node.h:63,
                 from ../src/keymapping.cc:6:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:8864:34: note: to match this ‘{’
 template <> struct SmiTagging<8> {
                                  ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:8872:3: error: expected ‘}’ at end of input
   }
   ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:8808:20: note: to match this ‘{’
 namespace internal {
                    ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:8872:3: error: expected ‘}’ at end of input
   }
   ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:64:14: note: to match this ‘{’
 namespace v8 {
              ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:3305:19: warning: inline function ‘void* v8::Object::GetAlignedPointerFromInternalField(int)’ used but never defined
   V8_INLINE void* GetAlignedPointerFromInternalField(int index);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /build/.node-gyp/iojs-2.0.5/src/node.h:63,
                 from ../src/keymapping.h:9,
                 from ../src/keyboard_x.cc:6:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h: In static member function ‘static void v8::V8::SetAllowCodeGenerationFromStringsCallback(v8::DeprecatedAllowCodeGenerationFromStringsCallback)’:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:10176:19: warning: cast between incompatible function types from ‘v8::DeprecatedAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v8::Context>)’} to ‘v8::FreshNewAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v8::Context>, v8::Local<v8::String>)’} [-Wcast-function-type]
           callback));
                   ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h: In static member function ‘static void v8::V8::RemoveGCPrologueCallback(v8::GCCallback)’:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:10221:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<Isolate::GCCallback>(callback));
                                                     ^
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h: In static member function ‘static void v8::V8::RemoveGCEpilogueCallback(v8::GCCallback)’:
/build/.node-gyp/iojs-2.0.5/deps/v8/include/v8.h:10228:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<Isolate::GCCallback>(callback));
                                                     ^
make: *** [keymapping.target.mk:102: Release/obj.target/keymapping/src/keymapping.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/build/code/src/code/node_modules/native-keymap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.5-zen1-1-zen
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /build/code/src/code/node_modules/native-keymap
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
Note: It doesn't always fail on this module, but it always fails due to errors in iojs' source.

Why is `iojs` being used?? How can I make the build system use my local node installation?

**Comment by FFY00** [comment] 2018-08-31 20:00
Apparently, you have to specify the arch using `--arch` for this to work. Great error handling :ok_hand:.

**Comment by weinand** [comment] 2018-08-31 20:15
Did you install the prerequisites?
see https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites

**Comment by FFY00** [comment] 2018-08-31 20:49
Yes, I do.

**Comment by dbaeumer** [comment] 2018-09-03 07:34
@joaomoreno do you have any idea. I know that you use Arch Linux from time to time.

**Comment by joaomoreno** [comment] 2018-09-03 09:12
What yarn version are you using?

**Comment by FFY00** [comment] 2018-09-03 11:53
The latest in the repos, 1.9.4.

**Comment by joaomoreno** [comment] 2018-09-04 07:31
Does it work if you call yarn with a new `HOME` variable? Did you try `git clean -xfd .` and retry?

**Comment by FFY00** [comment] 2018-09-04 16:45
That shouldn't affect anything as I build in a clean chroot (clean vanilla acrh instalation) but I think I found the issue here. If I invoke yarn with any argument, it fails. Is this intended (deliberately unsupported) or a bug?

Right now it's faiiling because the visual studio marketplace is down. I am not patching `product.json` so this is weird.

```
[17:37:29] Starting 'vscode-linux-x64-min'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery failed with status code:503
    at Request._callback (/build/code/src/code/node_modules/gulp-remote-src/index.js:70:33)
    at Request.self.callback (/build/code/src/code/node_modules/gulp-remote-src/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/build/code/src/code/node_modules/gulp-remote-src/node_modules/request/request.js:1081:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/build/code/src/code/node_modules/gulp-remote-src/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by joaomoreno** [comment] 2018-09-05 15:46
Not sure what is going on here. This happened this week with @dbaeumer and it worked to simply clean everything: `git clean -xfd`. Have you tried it?

**Comment by FFY00** [comment] 2018-09-06 14:42
Yes, I did. I also did a new clone of the repository and still the same.

**Comment by joaomoreno** [comment] 2018-09-06 15:58
The iojs one. Last one beats me. Can you repro in other machines?

**Comment by FFY00** [comment] 2018-09-06 16:07
It works on my machine. It just doesn't work when compiling in a clean chroot (clean Arch Linux installation), which is required to build the packages for the repos.

**Comment by joaomoreno** [comment] 2018-09-10 08:17
I'm going to have to close this, sorry for that. I'd be interested in knowing what the problem is, if you ever find it, though.

**Closed by joaomoreno** 2018-09-10 08:17 UTC
Labels: needs more info

**Comment by FFY00** [comment] 2018-09-10 11:41
How am I going to be able to solve without help from the actual team? I would think you would be interested in vs code be moved to an official repo, this way your users wouldn't be put at risk by having to go to alternative sources to install it. Do you have any guidelines on how to act on these situations or you just think this is worth solving? IMO this is shows an enormous disrespect for your users. Don't know if that's what you trying to do but it's certainly where it's going.

**Comment by joaomoreno** [comment] 2018-09-10 15:10
Your issue is about yarn/node_gyp/etc, not about VS Code. It doesn't hit users, it hits you because you are trying to compile VS Code in a chroot environment. Usually, we do try and help out people with these kind of issues, but we simply can't address every single  environment which isn't one of the officially supported ones.

**Comment by FFY00** [comment] 2018-09-10 15:41
You clearly don't get what a chroot is. We build in a chroot to isolate problems. What I mean by clean chroot is simply a fresh Arch Linux installation.
I suspect the issue here is that some native dependencies were missing and I had everything listed in your build guide.
And this **does** hit the users as I am required to build official packages in a clean installation, so you're basically denying to help in my efforts to make vscode available in the official arch repos.

Either way, I was able to build 1.27.1 (without `--production`) with the following instructions.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/code

The only issue now is that VS Code always starts in the app folder. Do you have any ideas on why this is happening? I assume it's the way electron starts apps.

**Comment by joaomoreno** [comment] 2018-09-11 08:38
So you think it was one of the `'electron' 'libsecret' 'libxkbfile'` dependencies?

**Comment by joaomoreno** [comment] 2018-09-11 11:56
This is how we do it in the product: https://github.com/Microsoft/vscode/blob/master/resources/linux/bin/code.sh

**Comment by joaomoreno** [comment] 2018-09-12 20:01
> Are you interested in solving this? This is the issue preventing the app from being moved to the official Arch Linux repos. This affects a ton of users, not just Arch Linux's ones but also the users from distributions that rely on our repos, ex.: Manjaro, Antergos, etc..

That's why we distribute a ZIP package. As an Arch user myself, I know that is not ideal. But we (VS Code team) have to draw the line on what targets we support. We simply can't do everything.

**Comment by FFY00** [comment] 2018-09-12 20:15
This issue doesn't seem to hard to fix with your help. You don't even need to make changes in the upstream, I can apply the patches locally before generating the package.

**Comment by joaomoreno** [comment] 2018-09-12 20:18
How can I help?

**Comment by FFY00** [comment] 2018-09-12 20:51
Thank you! Probably the first step would be to find the lines where vscode spawns new processes.

You can have a look at Atom's patch if you like. VS Code's one will probably be drastically different.
https://git.archlinux.org/svntogit/community.git/tree/trunk/use-system-electron.patch?h=packages/atom

**Comment by joaomoreno** [comment] 2018-09-13 07:36
I'm not going to do exploratory work on a platform we don't officially support. Let me know if there's something **specific** I can help with.

**Comment by FFY00** [comment] 2018-09-13 10:44
I am not asking for you to do the exploratory work. Just ping person responsible for the loaders and them if they know where this happens.

**Comment by FFY00** [comment] 2018-09-15 15:01
@joaomoreno can you tell me if you set the `desktopName` in the js code? Right now the main problem is that the app is being launched but it has the electron icon and when pinned, electron is the one effectively pinned.

**Comment by joaomoreno** [comment] 2018-09-16 19:50
That's odd. How does the `.desktop` file look like?

I didn't set the `desktopName` variable until last Friday (https://github.com/Microsoft/vscode/commit/3eac4d8e3e4c766d375e26f4411d37d0b1672db3) when I implemented URL handling for Linux. I think electron uses that key only for that purpose.

**Comment by FFY00** [comment] 2018-09-16 20:07
I used your model: https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop

These are the replacements I do: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/code#n63

**Comment by joaomoreno** [comment] 2018-09-17 09:05
Hm :thinking: and you do you initially pin it? Or how do you initially run it?

**Comment by FFY00** [comment] 2018-09-17 15:18
I ran it.

**Comment by joaomoreno** [comment] 2018-09-18 08:08
From the command line? From Gnome's launcher? From rofi?

**Comment by FFY00** [comment] 2018-09-18 11:52
I am using plank.
