### ISSUE TITLE
Webview Flickering on Resize

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24643] opened 2017-04-12 23:34 UTC
**Repo**
Trigger in-app resizing of a webview, such as opening a markdown preview to the right and adjusting the editor pane widths

**Bug**
The webview flickers on resize

**Comment by mjbvz** [comment] 2017-04-13 04:48
I just checked out 668315e25e29cbdc9a80754fd88cf07e0722af8c~1 but still see this so I don't think that change was related. Also see a bunch of logs:

```
[97493:0412/175337.158027:ERROR:browser_plugin_guest.cc(443)] Attempting to require callback on nonexistent surface
```

These logs don't seem to correspond to the visual flicker however

@bpasero I also tried on locals builds of VSCode using the commit before the electron 1.6 update and the update commit itself. Resizing before is much smoother while resizing after the update has the flicker. Can you please try testing on your machine as well to see if this in indeed a regression caused by the electron update

**Comment by mjbvz** [comment] 2017-04-13 04:54
At the very least, it seems the flicker is more prevalent after the update. Here's from  code 1.11:

![before-update](https://cloud.githubusercontent.com/assets/12821956/24990653/602f73fc-1fca-11e7-9065-7b0e18d9259b.gif)

And here's after the electron update:

![after-update](https://cloud.githubusercontent.com/assets/12821956/24990662/68c1ef40-1fca-11e7-968f-c9bff7bdb75c.gif)


Even before in 1.11, there're are occasional flickers on resize but it's not nearly as noticeable as in the current insiders

**Comment by chrisdothtml** [comment] 2017-04-13 13:45
Does it flicker for you occasionally when you scroll as well? Not sure if it's related, but I've noticed flickering when scrolling recently and am also on the insider build

**Comment by bpasero** [comment] 2017-04-17 16:06
@mjbvz I have seen this error in the console ever since the electron update so it may be related. if you want to report it to Electron I suggest to produce a simple reproducible sample 👍

**Comment by bpasero** [comment] 2017-04-17 16:39
@mjbvz are you sure this is not related to your layout change to prevent the zooming issue?

**Comment by mjbvz** [comment] 2017-04-20 23:25
I originally thought so but I then checked out a change before the webview zoom fix and noticed the same issue. 

Let me try setting up a simple electron app with a webview and seeing if I can also reproduce this issue in 1.6

**Comment by bpasero** [comment] 2017-04-23 17:09
Sounds good, thanks.

**Comment by mjbvz** [comment] 2017-04-25 01:42
@bpasero Confirmed that this looks to be an electron bug. I've created a small example project that demonstrates this and opened https://github.com/electron/electron/issues/9280 to track this upstream on electron

**Comment by bpasero** [comment] 2017-04-25 04:54
@mjbvz awesome

**Comment by bpasero** [comment] 2017-11-14 17:33
@mjbvz do you still see it?

**Comment by mjbvz** [comment] 2017-11-14 18:31
Yes, still in insiders. I need to check again to see if this is still electron or now something we are doing on our side

**Comment by bpasero** [comment] 2018-03-29 08:53
@mjbvz maybe try out with new exploration builds with Electron 2.x?

**Comment by mjbvz** [comment] 2018-04-05 17:15
This is significantly better now. There's still an occasional flicker but it is smooth for the most part

**Comment by bpasero** [comment] 2018-04-05 17:40
@mjbvz great, and I assume this is related to the electron update and not some other changes we did meanwhile?

**Comment by bpasero** [comment] 2018-04-06 08:05
Reopening as we had to revert the update.

**Comment by bpasero** [comment] 2018-04-11 16:42
@mjbvz this is unlikely to get fixed in April given we pushed out the Electron update to at least May.

**Comment by mjbvz** [comment] 2018-06-08 20:15
Fixed again by picking up electron 2

**Comment by bpasero** [comment] 2018-06-15 05:08
Let's only close this when we ship a stable release with Electron, I will keep track of this issue.

**Comment by kuroljov** [comment] 2018-06-18 16:51
Hey folks,

Actually I have similar problem but in my case it happens occasionally in almost random moments. 

- When open-close context menu
- When open-close working tab
- When open-close workbench
- Even when idle

Strange is that I can't record it. It happens on my screen but it doesn't show on recorded video. I will record from my smartphone if necessary. And it happens on both linux machines with arch installed. 

I guess I should wait and see if it happens in stable release? It's fair to say that this issue is the one that prevents me from using vscode

**Comment by bpasero** [comment] 2018-08-06 08:50
Closing, we pushed the Electron update.

**Closed by bpasero** 2018-08-06 08:50 UTC
Labels: bug, electron, upstream, webview
