### ISSUE TITLE
suggest: selection mode not working

### ISSUE THREAD

**Issue by SaifAshrafHelmy** [microsoft/vscode#176918] opened 2023-03-12 23:49 UTC
Type: <b>Bug</b>

Hi, 
I noticed that vscode doesn't select the first option in the suggestions list of intelliSense, 
so I found the option (suggest: selection mode)
it's set to "always" but it's not working..
when I set it to never, and set it back to always, it works fine for some time, but eventually it stops working (doesn't select the first option)

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.40GB free)|
|Process Argv|--crash-reporter-id 23a2443a-1784-498b-8885-4b82133030e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
reacticons|afz|0.1.4
raysocode|bir|0.0.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
javascript-ejs-support|Dig|1.3.3
bracket-pair-toggler|dzh|0.0.3
css-flexbox-cheatsheet|dzh|3.3.2
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.60.0
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
formate|Mik|1.2.1
remote-wsl|ms-|0.76.1
vscode-typescript-next|ms-|5.1.20230310
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
smart-css-autocomplete|sai|1.5.3
comment-box|Sly|2.2.1
code-spell-checker|str|2.19.0
vscode-pets|ton|1.22.0
queryselector-completion|tuw|1.1.0
JavaScriptSnippets|xab|1.8.0
dom-code-snippets|yon|1.0.2
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30677849
funwalk2cf:30682975

```

</details>

**Comment by rppig42** [comment] 2023-03-15 05:02
I have the same problem on Mac with version 1.76.1.

It occasionally happens which is really irritating.

**Comment by jrieken** [comment] 2023-03-16 12:09
/duplicate of https://github.com/microsoft/vscode/issues/173387

**Closed by jrieken** 2023-03-16 12:09 UTC

**Comment by tunde-olu** [comment] 2023-03-28 09:41
I'm also experiencing same issue.

**Comment by tunde-olu** [comment] 2023-04-06 09:44
I solved this problem by disabling the << Snippets Prevent Quick Suggestions >> option in my VS Code app settings.
![quick_suggestion](https://user-images.githubusercontent.com/110298599/230339030-41d394f1-005f-42d0-92e2-e02da381481b.jpg)
