### ISSUE TITLE
Duplicate duplicate identifier error

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#21197] opened 2017-02-22 19:08 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (256d76fed7947e7289f921df10658d7a69233b65, 2017-02-22T07:04:54.544Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

![screen shot 2017-02-22 at 11 07 48 am](https://cloud.githubusercontent.com/assets/9205389/23227839/2cf1af52-f8ef-11e6-9f87-e396f8a3e0bd.png)

**Comment by mjbvz** [comment] 2017-02-22 21:27
I'm unable to reproduce this. Can you provide some more info about the project setup? Does this happen again if you reload the window?

**Comment by chrmarti** [comment] 2017-02-22 21:45
It does reproduce after reload. There is a tsconfig.json with `noImplicitAny` set to true, nothing else. This is with TypeScript 2.2.1-insiders.20170217. Let me know or drop by if you need more information.

**Comment by mjbvz** [comment] 2017-02-24 01:09
@chrmarti Do you have any other js or ts files open by chance? If one of them also defined `foo`, you would see this error

**Comment by chrmarti** [comment] 2017-02-24 04:57
I don't have another file open, but you're still right. It reproduces if there is either a jsconfig.json or tsconfig.json. It goes away if I rename the variable to some unlikely name. (There are many files in that folder.)

What still looks like a bug is that the same error is reported twice on the same position of the file.

**Comment by mjbvz** [comment] 2017-02-27 22:41
Closing since when we talked on Thursday it looks like the root cause a `foo` definition in another file. This specific error message can happen if `foo` is defined in another `js` file and then used like this a `ts` file. The `js` file will not report the error but the `ts` file will. We're looking into adding better error messages for `js` files too

**Closed by mjbvz** 2017-02-27 22:41 UTC
Labels: bug, typescript
