### ISSUE TITLE
Special input causes vscode to hang

### ISSUE THREAD

**Issue by flowmemo** [Microsoft/vscode#27025] opened 2017-05-21 11:08 UTC
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Create a new plain text file, paste "soooooooooooooooooooooooooooooo" into the first line.
2. Manually type "oooooooooooooooooooo" in the second line. The editor will hang when you are typing.

It seems like there are too many calls of function `findAllMatches`.

**Comment by jrieken** [comment] 2017-05-22 09:57
this is a dupe of #26423

**Closed** 2017-05-22 09:57 UTC
Labels: bug, duplicate, suggest
