### ISSUE TITLE
Markdown preview refresh does not refresh image

### ISSUE THREAD

**Issue by generateui** [microsoft/vscode#73673] opened 2019-05-13 15:54 UTC
- VSCode Version: 1.33.1
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Create image in paint, save to folder
2. Refer to image in markdown file `![](image.png)`
3. Verify the image is shown. You may need to enable local content.
4. Edit image in Paint then save it
5. In markdown preview, click the … ellipsis then "Refresh Preview"

Note that the image is not updated. Probably the image cache is not invalidated, where I expect this to be the case.

**Comment by mjbvz** [comment] 2019-05-13 22:34
Duplicate of #65258

**Closed by mjbvz** 2019-05-13 22:34 UTC
Labels: markdown
