### ISSUE TITLE
Terminal "loses" entered command when its output is exact terminal height

### ISSUE THREAD

**Issue by danilaml** [microsoft/vscode#146450] opened 2022-03-31 16:47 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65, 1.66
- OS Version: Win 10 x64

Steps to Reproduce:

1. Open a terminal (tested on PS)
2. Run a program/script that outputs the exact number of lines needed for the command prompt to move to the topmost line. E.g. `python -c "print('foo\n' * 14)"` in my case, with terminal displaying the total of 17 lines:
![image](https://user-images.githubusercontent.com/2046350/161107558-b81c1c63-78bc-43b7-ae69-c7c3d444bfca.png)
3. Do it again/run other program.
4. Scroll up - there is no corresponding `...> python -c "print('foo\n' * 14)` line delimiting the output anymore.

**Comment by meganrogge** [comment] 2022-03-31 20:57
A gif would help

**Comment by danilaml** [comment] 2022-03-31 23:05
@meganrogge 
Here:
![terminal](https://user-images.githubusercontent.com/2046350/161163563-73fcc755-ba8b-4ee3-b9ac-5dba3e33f66e.gif)

You can see that with 9 lines printed (`'foo' * 8`) if I scroll back, the command is retained. However, if I increase the number of lines to fill the whole terminal (to 10 in this case), once I scroll back, the previous `python -c "print('foo\n' * 9)"` dissapears.

**Comment by meganrogge** [comment] 2022-03-31 23:26
thanks for the gif. What do you have `terminal.integrated.scrollback` set to?

**Comment by danilaml** [comment] 2022-03-31 23:28
1000

**Comment by Tyriar** [comment] 2022-04-01 10:06
I can't reproduce but almost certainly it's related to conpty which we wouldn't be able to do anything about anyway:

---

This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2022-04-01 10:06 UTC
Labels: needs more info

**Comment by danilaml** [comment] 2022-04-01 11:42
Thanks. I was able to reproduce the issue in Windows Terminal and reported it here: https://github.com/microsoft/terminal/issues/12805

**Comment by rafrafek** [comment] 2022-04-07 07:06
My terminal in VS Code is broken. When using with Windows PowerShell on Windows 10, lines sometimes disappear, and output from different commands are mixed up. This also happens on my colleagues laptops. Please take a closer look at this issue. Thanks!

There were problems in the past, e.g. https://github.com/Microsoft/vscode/issues/34165 but in my case whole lines disappear.
