### ISSUE TITLE
Paste from Word to VSCode with non-breaking characters

### ISSUE THREAD

**Issue by houghtonap** [microsoft/vscode#105000] opened 2020-08-19 15:10 UTC
Issue Type: <b>Bug</b>

1. Launch Word
1. Open a new document
1. Add the text "abc-def ghi" where the - is a non-breaking hyphen and the space is a non-breaking space
1. Copy the text
1. Launch VSCode
1. Open a new plaintext document with UTF-8 encoding
1. Paste

The non-breaking hyphen is converted to a space. It makes more sense to either retain it as a non-breaking hyphen or convert it to hyphen characters rather than a space character.

The non-breaking space is converted to a space. If you decide to retain the non-breaking hyphen, then you should also retain the non-breaking space.

In contrast, when pasting superscript or subscript characters from Word, VSCode removes the superscript or subscript and retains the actual characters. This might indicate that a non-breaking hyphen should be converted to a hyphen. Regardless the pasting rules should be consistently applied.

The plaintext document that I was pasting into was using the UTF-8 encoding and it was expected that Unicode characters would be pasted, as is, without conversion. Had the plaintext document been using the ASCII encoding or another Code Page, then I would have expected non-breaking characters to be replaced by their equivalent ASCII characters and the current behavior of converting superscript and subscript characters into their actual characters.

As a last thought, could this issue be a result of the font being used for VSCode? The font-family setting for my VSCode is 'Cascadia Code', Consolas, 'Courier New', monospace.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 7322)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.97GB free)|
|Process Argv|U:\Special Audit\W2 Processing\Tax Year 2020\Phrases.txt|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-unicode|bru|0.8.0
excel-to-markdown-table|csh|1.2.2
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
gc-excelviewer|Gra|3.0.39
vscode-guid|hea|1.4.20
plantuml|jeb|2.13.13
vscode-insertdatestring|jsy|2.3.0
rainbow-csv|mec|1.7.1
vscode-html-format|moh|0.0.4
vscode-print|pdc|0.7.14
markdown-preview-enhanced|shd|0.5.13
code-spell-checker|str|1.9.0

</details>

**Comment by rebornix** [comment] 2020-08-31 22:50
You can turn copy with syntax highlighting off if you only want to copy plain text `editor.copyWithSyntaxHighlighting`.

**Comment by rebornix** [comment] 2020-11-03 16:55
/duplicate of https://github.com/microsoft/vscode/issues/88178

**Closed by rebornix** 2020-11-03 16:55 UTC
Labels: editor-clipboard, under-discussion
