### ISSUE TITLE
always show git change window when fold code

### ISSUE THREAD

**Issue by Sesna** [Microsoft/vscode#36406] opened 2017-10-17 09:59 UTC
- VSCode Version: 1.18.0-insider
- OS Version: windows 10

Steps to Reproduce:

1. enable git in settings
2. do some change on my code
3. try to fold or unfold my changed code
before mouse hover
![image](https://user-images.githubusercontent.com/8176600/31658686-5113cc82-b364-11e7-823e-beff8a5da0c1.png)
after mouse hover
![image](https://user-images.githubusercontent.com/8176600/31658645-2da86410-b364-11e7-8896-0aa20dafc572.png)
4. click the fold butons, always show a changes win
![image](https://user-images.githubusercontent.com/8176600/31658778-99a6995c-b364-11e7-96aa-9d72e3e0ce01.png)
5. even though I unfold my code within some changes, this changes window will show too.

Reproduces without extensions: no

**Comment by Erchamion** [comment] 2017-10-17 15:15
I concur, experiencing the same issue.

**Comment by mjbvz** [comment] 2017-10-17 18:02
Thanks. This looks like a duplicate of #36237

**Closed by mjbvz** 2017-10-17 18:02 UTC
Labels: duplicate, editor, editor-folding
