### ISSUE TITLE
Terminal clear shortcut not working

### ISSUE THREAD

**Issue by Romit-Kumar18** [microsoft/vscode#210050] opened 2024-04-10 13:23 UTC
Type: <b>Bug</b>

Edit: Clearing terminal with shortcut causes it to bug out and return all previously cleared info on the execution of another command.

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.72GB free)|
|Process Argv|--crash-reporter-id 92f7d5ed-63fa-4b9e-8f86-fce4549ac106|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.8.5
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
code-runner|for|0.12.2
copilot|Git|1.178.0
copilot-chat|Git|0.14.0
vscode-pull-request-github|Git|0.86.1
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.4.0
isort|ms-|2023.10.1
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.17.17
cpptools|ms-|1.19.9
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.9.10
vsliveshare|ms-|1.0.5918
live-server-preview|neg|0.1.4
vscode-jest|Ort|6.2.3
fabric8-analytics|red|0.9.4
java|red|1.29.0
vscode-yaml|red|1.14.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.57.0
vscode-java-dependency|vsc|0.23.6
vscode-java-pack|vsc|0.26.0
vscode-java-test|vsc|0.41.0
vscode-maven|vsc|0.44.0
quokka-vscode|Wal|1.0.635
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by meganrogge** [comment] 2024-04-10 14:28
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by Romit-Kumar18** [comment] 2024-04-10 17:07
My bad actually the terminal was working it was the clear terminal shortcut that was messing with the UI and resetting the terminal to return the data that was there before clear was used. I've edited the report to reflect this.

![Recording 2024-04-10 at 22 37 11](https://github.com/microsoft/vscode/assets/113458536/55bf2e30-0cf3-4ed5-a6c5-dfbaf5b42bcb)

**Comment by meganrogge** [comment] 2024-04-10 17:10
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2024-04-10 17:10 UTC
Labels: info-needed, terminal
