### ISSUE TITLE
Command Click opens Peek window by default

### ISSUE THREAD

**Issue by davidchiew-ooh** [Microsoft/vscode#52144] opened 2018-06-18 00:08 UTC
Issue Type: <b>Bug</b>

When I press Command Click, previously it would navigate directly to the code. In the last few weeks I've noticed it now opens the pop-up "Peek" window by default which is not my preference, I'd rather it jump straight to the code in the standard editor, instead of popping up the "Peek" window.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.21
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.3.5
prettier-vscode|esb|1.5.0
prettify-json|moh|0.0.3
python|ms-|2018.5.0
csharp|ms-|1.15.2
Go|ms-|0.6.82
vscode-sql-beautify|sen|0.0.4
react-beautify|tai|0.3.0

</details>

**Comment by hippostar** [comment] 2018-06-18 02:54
Got this but oh windows too. Since somewhere in May Clicking "Go to definition" opens a list of 2 possible definitions wich are both on the same line of code (which means theres no reason to even show the list of definitions).

See this image for an example: 
![image](https://user-images.githubusercontent.com/2255872/41516204-535a9b38-7281-11e8-9798-51c28574d844.png)

**Comment by hippostar** [comment] 2018-06-18 03:14
Here is a zip of 2 files you can use to reproduce the issue. Ctrl-Click on bad() in Untitled-2.ts pops up the list of 2 definitions both for line 2 in Untitled-1.ts
[example.zip](https://github.com/Microsoft/vscode/files/2109786/example.zip)

**Comment by davidchiew-ooh** [comment] 2018-06-18 07:02
Thanks for providing the example hippostar. A bit more info from me, I'm also using typescript (.ts). 

- Also Command-Click'ing on a function that lives in a _different file_ does jump to the file without any Peek **(good)**
- Command-Click'ing on a function that lives in the same file shows the Peek popup **(not ideal)**

Would be nice to have the option to turn this Peek off.

**Comment by mjbvz** [comment] 2018-06-19 17:06
Duplicate of https://github.com/Microsoft/TypeScript/issues/24861

You can workaround it by manually upgrading your workspace to typescript@next by following [these instructions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-06-19 17:06 UTC
Labels: typescript
