### ISSUE TITLE
feature-request : Disable extension

### ISSUE THREAD

**Issue by AlanWalk** [Microsoft/vscode#7037] opened 2016-05-31 06:33 UTC
Hi, can i disable extension, just like atom?

![file](https://cloud.githubusercontent.com/assets/4654826/15665259/9618acc2-273c-11e6-80b6-ff5136410cd8.PNG)

**Comment by joaomoreno** [comment] 2016-05-31 08:05
Not yet.

Duplicate of #2882

**Closed by joaomoreno** 2016-05-31 08:05 UTC
Labels: duplicate
