### ISSUE TITLE
iPad: Trackpad scroll doens't work in vscode.dev

### ISSUE THREAD

**Issue by RLungarella13** [microsoft/vscode#164220] opened 2022-10-21 07:59 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.72.2
- OS Version: ipadOS 16.1

Steps to Reproduce:

1. Open any repository in vscode.dev
2. Try to use the trackpad of the magic keyboard

I have an Ipad Air 5th generation and I am using it with a magic keyboard, I am currently using the beta of IpadOS 16.1. When I try to visualize any code in .dev mode the trackpad doens't work. I am using Safari, other browsers don't work as I want. If I add the vscode.dev project to my home screen the scroll works, but only when I open the files from the side bar.
Is this a problem of the IpadOS version? I found some issues where they said they solved it in IpadOS 14.5.

**Comment by yume-chan** [comment] 2022-10-22 20:01
Duplicate of #106232

**Comment by keekerdc** [comment] 2022-10-24 19:41
I don’t think this is a dupe of a two-year-old issue. I’ve rolled up here today to +1 this issue.

Just updated to iPad OS 16.1 today on the full public release. I’m utilizing vscode via the code-server project.

I’ve found that if Settings -> General -> Keyboards -> Shortcuts is turned ON, two-finger scroll on the magic keyboard trackpad works. If that’s turned OFF - as I had been doing since it gets rid of the little keyboard drawer that pushes all the content up when you’re in a text entry context - then the two-finger trackpad scroll stops working. I’ve found this to be the case whether using my vscode instance in the safari browser, or through the full-screened homepage shortcut context.

This wasn’t previously the case - on iPad OS v15.x I could have the Shortcuts setting set to ON and the two-finger scroll worked.

**Comment by cschoenecker** [comment] 2022-10-25 17:49
Same issue for me with VSCode un PWA mode (iPadOS 16.1, work ni 15.x ni PWA mode). If you turn On/Off/On Stage manager scroll work (until you close the app)

**Comment by mtogstad** [comment] 2022-10-31 00:49
I’m having this issue too, and I can’t seem to get sone of the tricks mentioned here to work either (toggling stage manager, turning on Settings -> General -> Keyboards -> Shortcuts).  But placing a cursor in an open file does work for me (this is in safari).  As long as a file is open with a cursor in it, scrolling in the file and the files list works, as soon as the cursor is gone, trackpad scrolling doesn’t work anywhere.

**Comment by PixNyb** [comment] 2022-11-01 08:37
I’ve come here to +1 this issue, I’ve been experiencing the same behavior since i got my IPad and started developing on it. 
I never in a million years thought turning on shortcuts would solve the scroll issue but now i am dealing with pushed up content in the PWA. Anyway i’ve experienced being able to scroll through a view but as soon as my focus is on the view i lose that ability.

**Comment by t0slink** [comment] 2022-11-06 10:48
Can confirm this is still happening in the iPadOS 16.1 production release.

**Comment by huw** [comment] 2022-11-09 06:37
Thank you—been suffering under this for 6 months since the first beta. Thought it had to be something a bit weird with my setup. Cheers ❤️

**Comment by Antoniomm80** [comment] 2022-11-09 19:56
I’m having this same issue with an ipad air with no stage manager support in both safari and PWA

I’ll check on Edge

**Comment by ILSYT** [comment] 2022-11-18 08:44
+1 but I once found it working again, but the next day it didn’t work again. So I don’t know what happened that night.

**Comment by cschoenecker** [comment] 2022-11-24 10:24
Another bug: Text selection (with the mouse for example) crashes regularly. The workaround is to reload the window (iPadOS 16.1)

**Comment by huw** [comment] 2022-12-04 04:05
On iPadOS 16.2 Beta 4, scrolling is much more intermittent with the keyboard bar minimised (when you hit ‘Minimise’ and it goes into the bottom-right corner, not when you have ‘Shortcuts’ off).

You can fix it by un-minimising the bar, which brings it back into the middle. The keyboard bar is clearly just broken in this beta, the nice animations are totally gone—so I’m assuming it’ll get fixed next update but for those of you in the thread who’re relying on this that’s how to get around it for now <3

**Comment by iloveicedgreentea** [comment] 2022-12-12 16:45
Having the same issue Ipad 16.1.1 with magic keyboard. I did some digging in this issue https://github.com/coder/code-server/issues/5861

**Comment by TUCAOEVER** [comment] 2022-12-13 02:49
> 

Enable shortcut only works with normal bar instead of minimized bar, if u minimize the shortcuts bar, the scroll will still not work either. Besides, it's wired, there is also a moment of lag minimizing the bar in safari while scrolling, so i think it's probably the issue with iPadOS or Safari itself. Currently i'm using 16.2 on iPad Pro 2018.

**Comment by LeytonHouck** [comment] 2023-01-12 08:41
Still having this issue on 16.2 with a Logitech folio trackpad. Is this something that can be fired on VS Code's end or does apple have to fix something with Safari?

**Comment by tusing** [comment] 2023-01-14 21:26
My solution was moving back to a Mac, since Safari on iOS is such a mess.

**Comment by jgdevroman** [comment] 2023-01-18 06:23
Still having this issue on iPadOS 16.2 but I was able to fix this by *disabling* the shortcuts on keyboard settings. Hope it helps and apple fix this soon

**Comment by ssabpisa** [comment] 2023-01-18 09:12
> Still having this issue on iPadOS 16.2 but I was able to fix this by *disabling* the shortcuts on keyboard settings. Hope it helps and apple fix this soon

Didn't work for me.

**Comment by cschoenecker** [comment] 2023-01-18 09:38
It doesn't work for me either

**Comment by jgdevroman** [comment] 2023-01-18 10:39
Sorry, it just worked at that moment but didn't work later for me as well.
Although I found out that there is an app called `Blink` that can open Codespaces inside the app and works much better than Safari. I suggest using this until Apple fixes these issues.

**Comment by lwschan** [comment] 2023-01-19 01:55
I just found out that if I zoom out VSCode once with <kbd>Cmd</kbd> + <kbd>-</kbd> then I can scroll even with the keyboard shortcuts bar minimised at a corner. Might be an OK-ish workaround until they get this fixed properly.

**Comment by huw** [comment] 2023-01-19 05:30
@lwschan Replicated in Safari only (i.e. not ‘Add to Home Screen’, which can’t zoom using the keyboard), and only at the 90% zoom level (no further in or out). Weird—but great find!

**Comment by Cupprum** [comment] 2023-01-28 01:20
> @lwschan Replicated in Safari only (i.e. not ‘Add to Home Screen’, which can’t zoom using the keyboard), and only at the 90% zoom level (no further in or out). Weird—but great find!

Today i found out, that if you zoom to 90% level and do ‘Add to Home Screen’ afterwards, the downloaded PWA is the zoomed in one. So the scrolling works, at least for me (did not work before).

**Comment by hzcheng** [comment] 2023-01-29 10:15
> > @lwschan Replicated in Safari only (i.e. not ‘Add to Home Screen’, which can’t zoom using the keyboard), and only at the 90% zoom level (no further in or out). Weird—but great find!
> 
> Today i found out, that if you zoom to 90% level and do ‘Add to Home Screen’ afterwards, the downloaded PWA is the zoomed in one. So the scrolling works, at least for me (did not work before).

This works for me!

**Comment by cschoenecker** [comment] 2023-01-29 10:35
Works for me too. But don't you have a problem with text selection in the code editor that often happens?

**Comment by huw** [comment] 2023-01-30 00:20
> Today i found out, that if you zoom to 90% level and do ‘Add to Home Screen’ afterwards, the downloaded PWA is the zoomed in one. So the scrolling works, at least for me (did not work before).

At least for me on 16.3 this saves the 90% zoomed web app into the PWA. A non-starter for me but good to know that it works! Crazy find.

Hoping now that 16.3 is properly out that this gets a fix. Promising that the ticket has milestones on it now ^_^

**Comment by hzcheng** [comment] 2023-01-30 02:07
> Works for me too. But don't you have a problem with text selection in the code editor that often happens?

No text selection problem in my case. Besides, I use vscode-vim plugin in which I rarely select text with trackpad.

**Comment by cschoenecker** [comment] 2023-02-02 13:37
This works best via Chrome on the iPad (although it is WebKit like Safari). The scroll works without setting the site zoom to 85% and the selection with the cursor also (the right click does not open the editing popup of the OS)

**Comment by TUCAOEVER** [comment] 2023-02-20 16:55
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed** 2023-02-20 16:55 UTC
Labels: bug, upstream, editor-core, ios-ipados

**Comment by huw** [comment] 2023-02-21 00:19
FYI this has been completely fixed for me in iPadOS 16.4, including with Shortcuts off.
