### ISSUE TITLE
Ctrl + f, Ctrl + c, Ctrl + v, Ctrl + x stopped working

### ISSUE THREAD

**Issue by sam1730** [microsoft/vscode#65278] opened 2018-12-18 10:03 UTC
- VSCode Version: 1.30
- OS Version: Windows 10, Enterprise Edition x64

Steps to Reproduce:

1. On launch open any file and start searching by using Ctrl + F

After 4-5 times Restarting the VS Code it starts working

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2018-12-18 16:59
> After 4-5 times Restarting the VS Code it starts working

What was the problem? Please explain exactly what you do and what the problem is.

**Comment by cajetaneducode** [comment] 2018-12-19 14:37
@roblourens I have the same issue here. 

- VSCode Version: 1.30.1 (and 1.30.0)
- OS Version: Windows 10, Home Edition x64 (build 10.0.17134)

The [documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing) specifies that it's possible (and it used to) be possible to cut the whole line on an empty selection by pressing using the shortcut **Ctrl + X**. The alternative shortcut **Shift + Delete** doesn't work.

Copy (**Ctrl + C**) has the same problem. The previous behaviour allowed you to copy the whole line on an empty selection. Now nothing is copied to the clipboard.

Something tells me that the _editor.action.clipboardCutAction_ and the _editor.action.clipboardCopyAction_ are not working properly anymore

**Comment by cajetaneducode** [comment] 2018-12-31 12:10
@roblourens 

Ctrl + F works fine for me, but Ctrl + X, Ctrl + C and Ctrl + V (on an empty selection) don't work.

I don't have any conflict with keybindings.

I can confirm that I don't have that bug on 1.29.1.

**Comment by geisels** [comment] 2019-01-08 16:52
I have same problem. In anothers application all fine.

Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

**Comment by alexandrudima** [comment] 2019-01-10 07:37
@sam1730 @cajetaneducode @geisels Keybindings issues end up in 99% of the time with:
1. there is an installed extension that modifies keybindings
2. there are incorrect tweaks to `keybindings.json`
3. the system clipboard is broken due to using tmux or some 3rd party OS clipboard
4. there is some other software installed on the machine which "steals" keybindings

---

That being said, I don't believe all the 3 of you have the same problem. So I kindly ask @cajetaneducode and @geisels please create separate issues.

---

@sam1730 What appears when you search for the keybinding "Ctrl+F" in the keybindings editor?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by usernamehw** [comment] 2019-01-10 12:08
https://github.com/Microsoft/vscode/issues/55243#issuecomment-423845841

**Comment by chongchai** [comment] 2019-05-16 02:25
I happened to get same problem in VSCode 1.31.1. 
Several times `Ctrl+F` will be not working. But after I reload window, ctrl+f will work again. That's wired.

**Comment by AasmundEndresen** [comment] 2019-05-26 11:46
I have a similar issue which appeared recently after updating to VSCode 1.34.0.

CTRL + C keybinding does nothing (even though it's mapped in keybindings.json), meanwhile CTRL + INS is the only way to copy selections - despite me REMOVING that keybinding from keybindings.json to see if it was causing a conflict.

This is mildly frustrating because copy+pasting is quite an essential feature, especially when refactoring code.  And ctrl+ins just happens to be incredibly less efficient to use on a normal keyboard then ctrl+c because of locations...

**Comment by alexandrudima** [comment] 2019-07-24 07:19
I am closing this issue since the OP @sam1730 did not reply.

@chongchai @AasmundEndresen Please create new issues with your OS and VS Code version, with installed extensions, etc. (preferably from the issue reporter in the Help menu). I am sorry for your problems, and I am happy to try to dig further but I don't believe you are all having the exact same issue.

**Closed by alexandrudima** 2019-07-24 07:19 UTC
Labels: needs more info, windows
