### ISSUE TITLE
[bug] vs code still create debug.log file

### ISSUE THREAD

**Issue by lucdotdev** [microsoft/vscode#116619] opened 2021-02-13 14:52 UTC
- VS Code Version:
1.53.1
5d424b828ada08e1eb9f95d6cb41120234ef57c7
ia32
- OS Version:
windows 10 pro 
version:2004

Steps to Reproduce:

1. open a  project web project with vs code
2. try to modify code , voilà debug.log file appear in current folder
![vs code](https://user-images.githubusercontent.com/55983266/107852874-bc76b280-6e1b-11eb-84fa-fc2f52ed8ea2.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-02-13 14:55
/duplicate of #115874

Fix already released in 1.53.2

**Closed** 2021-02-13 14:55 UTC
Labels: *duplicate
