### ISSUE TITLE
Find crashing with a specific string

### ISSUE THREAD

**Issue by RubenVerg** [microsoft/vscode#94468] opened 2020-04-05 13:32 UTC
- VSCode Version: 1.44.0-insiders
- OS Version: Windows 10 v1809 (17763.1098)

Steps to Reproduce:

1. Open [this file](https://raw.githubusercontent.com/TempoBenSpesoOnline/page/master/locales.yaml) (others may work too?)
2. Open Find and Replace, and turn on regexes.
3. Type `( +- \w+\n)+ +href: \w+\W+(\w+.)+ +`
4. Type `t`
5. Crash!

Does this issue occur when all extensions are disabled?: Yes

**Comment by RubenVerg** [comment] 2020-04-05 13:38
doesn't appear to be duplicate, I can't seem to find a relation to the problem referenced in that issue (the one which it duplicates, actually).
That said, you never know.

**Comment by IllusionMH** [comment] 2020-04-05 22:01
Still 
/duplicate of #30874

Same problem here: catastrophic backtracking happens when you have pattern like `(\w+)+` because RegExp engine need to verify all possible `\w+` patterns and for each of match need to verify that it can be repeated. 

If you need to match dot character in last matching group (need to escape it) - situation may improve and there is chance that RE won't cause backtracking.

**Closed** 2020-04-05 22:02 UTC
Labels: *duplicate
