### ISSUE TITLE
Code completion suggestion disappears after you start manually typing it

### ISSUE THREAD

**Issue by stochris** [Microsoft/vscode#7476] opened 2016-06-09 13:23 UTC
- VSCode Version: 1.2.0
- OS Version: Linux version 3.19.0-32-generic 

Steps to Reproduce:
1. Open a new html file
2. Write a  '< div >' tag
3. Start writing the closing tag of the div ( '</' )
4. Right now, VS Code should show 'div' as a possible suggestion
5. However, once you start typing 'd' ( as in 'div' ), the suggestion disappears

I propose showing the suggestion until the user input stops matching the first part of the suggestion. 

I, for one, would find this helpful, because it feels more natural to keep typing instead of moving my fingers towards enter, while still seeing what the closing tag should look like

**Comment by aeschli** [comment] 2016-06-15 14:12
duplicate of #6243

**Closed** 2016-06-15 14:25 UTC
