### ISSUE TITLE
Debugging control bar disappears

### ISSUE THREAD

**Issue by doogie99** [microsoft/vscode#83771] opened 2019-10-31 16:55 UTC
Issue Type: <b>Bug</b>

I don't know how to recreate this but this seems to have been introduced in the last month or so.

I often debug Golang code in VS Code. When I start debugging I get the debugging control bar showing up near top of screen. For some reason it occasionally disappears now while the debugger is still running. If you try to start a new debugging session you get an error that says something to the effect of "debugging session already running". 

Could this be a z-order problem?  

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
ng-template|Ang|0.802.3
atlascode|atl|2.1.4
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
contextualduplicate|laf|0.2.0
Go|ms-|0.11.7
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.1
vscode-yaml|red|0.5.3

</details>

**Comment by isidorn** [comment] 2019-11-13 10:47
Very simmilar to an issue @joaomoreno is hitting
I plan to look into this

**Comment by isidorn** [comment] 2019-11-27 11:56
@doogie99 do you maybe have better steps to reproduce this? I would really appreciate it.
What I suspect is happening is that the debugee shuts down, the toolbar as tha cause of that disappears. And some state is left behind.
When this happens is the debug status bar still orange?

**Comment by doogie99** [comment] 2019-11-27 16:38
@isidorn I haven't had it happen for a bit but next time I see it I'll try to be attentive to the debug status bar. I usually use this when debugging golang code that provides the api for our app. When the debug controls disappear the api is still running and responsive. I suspected that the missing controls was just a zorder thing but I could not reveal the controls no matter what I tried.

**Comment by isidorn** [comment] 2019-11-27 18:14
Nope, I do not think the issue is css.
Let me know if you find more details next time it happens. Would really appreciate it. Thanks

**Comment by doogie99** [comment] 2019-12-06 18:05
@isidorn 

So, here's some more info. I'm currently in the problematic state where the debugger is not running but my golang api code is still running and there is no obvious way to shut it down in the debugger.

If I try to start a debug session with my current debug configuration it says:

"There is already a debug configuration [My golang debug config] running"

The Debug menu looks like this:

![image](https://user-images.githubusercontent.com/877070/70344609-55bd3880-1817-11ea-88be-85a63036eccd.png)

I found the Debug toolbar in the HTML and forced it to display (it was display: none) but even after doing so the controls on it are ineffective. This didn't surprise me with the Debug menu having the same controls disabled. 

I have Dev Tools open. Here's the contents of the JS Console:

[JS console debug fail.txt](https://github.com/microsoft/vscode/files/3933396/JS.console.debug.fail.txt)

Hope that helps.

-D

**Comment by isidorn** [comment] 2019-12-09 13:36
Thanks a lot, let's reopen and assign for December so I investigate more

**Comment by isidorn** [comment] 2019-12-12 16:34
There will be a new visual studio release in a couple of days.
Can you pease let us know if you can still repro the issue with that latest release 1.41

**Comment by isidorn** [comment] 2020-01-22 14:28
@joaomoreno here's the issue you are seeing. Reopening and assigning to this milestone to investigate more and potentially handle this better.

**Comment by isidorn** [comment] 2020-01-29 13:41
I could reproduce this partially if I start a comound configuration and one of the configuration has issues starting. Then the focused session was not begin properly set and the debug toolbar would be invisible.
I have pushed a fix for this issue.
@joaomoreno please let me know if you still see this starting from tomorrow. Thanks!

**Closed** 2020-01-29 13:41 UTC
Labels: bug, debug
