### ISSUE TITLE
Laggy scrolling behaviour while scrolling up and down using arrow keys 

### ISSUE THREAD

**Issue by NiggyWizzyWoz** [Microsoft/vscode#11659] opened 2016-09-08 01:06 UTC
- VSCode Version: 1.4
- OS Version: 10.11.6 El Capitan

Steps to Reproduce:

1. Use the up and down arrow keys to scroll. (or in may case download the vim extension and use j / k keys)
2. Scrolling by holding the j / k keys or up and down arrow keys results in choppy scrolling behaviour. 
3. If you scroll using the touchpad however, It's silky smooth.

**Comment by ramya-rao-a** [comment] 2016-09-08 02:06
Can you add a screencast/gif/video?

**Comment by NiggyWizzyWoz** [comment] 2016-09-08 02:48
Here are some screen capture videos: 
VSCODE: https://vid.me/dnNn
MACVIM(for comparison): https://vid.me/Ip1z

This is a common problem with chromium-based apps. (same issue with the latest version of Atom as well.)

**Comment by alexandrudima** [comment] 2016-09-08 09:11
@NiggyWizzyWoz can you try changing the OS - level settings for key repeat. I am not familiar where these settings exist, but we basically react to each and every character produced by Chromium, which I believe respects the OS - level setting. I am not sure if MACVIM respects the OS - level setting or it has implemented its own repeat logic.

**Comment by jpoon** [comment] 2016-09-08 21:36
@NiggyWizzyWoz the Vim extension may be adding a bit to the lag (https://github.com/VSCodeVim/Vim/issues/534). Can you try uninstalling it and trying again with the up/down arrows and assess if you see the same sort of lag?

**Comment by rebornix** [comment] 2016-09-08 21:39
we hijacked arrow keys for Vim customization so please uninstall Vim and see if the issue still happens, if not, then let's move this issue to Vim.

**Comment by hashhar** [comment] 2016-09-09 03:42
There are quite a few extensions that add such lag. I would suggest you to binary search your extensions to find the culprit.

Move out half of your extensions at a time from the extensions folder and then see if the issue is fixed. Keep on repeating until you halve down to just the culprit.

**Comment by NiggyWizzyWoz** [comment] 2016-09-09 04:15
So here are my findings after following your advices:
1- I'm using an app called Karabiner which allows me to modify OS-level key repeat & delay rates. This made the choppy behaviour worse  because It was simply registering in more keystrokes.
2- I removed all extensions and used arrow keys. Some of the choppiness is gone. I assume the remaining choppiness has to do with CSS transitions ? (pure speculation ). I would consider it considerably less..
3- Vim Extension. Even though every other package  also adds some delay / slows the app down a little bit ( which is to expected), the vim extension makes the problem so much worse. I used another vim extension called AmVim before switching to the default vim extension and experienced the same issue as well. 
Conclusion: There is some choppiness that might have something to do with CSS transitions. The Vim extension makes the problem much worse.

**Comment by hashhar** [comment] 2016-09-09 04:19
What type of file is it? And how long is it? Could be the syntax files.

**Comment by NiggyWizzyWoz** [comment] 2016-09-09 04:50
.go file - 740 loc. 
uses the Go Extension by lukehoban. 
I just updated vscode to 1.5.1 - no difference.

**Comment by NiggyWizzyWoz** [comment] 2016-09-09 05:03
I must mention that this problem is not as bad on my windows machine  probably due to having a much better cpu and also default key repeat rates. The problem is that I don't actually use that machine for development, just wanted to test whether I would experience the same thing on Windows as well.

**Comment by adanis** [comment] 2016-09-09 15:15
Something like that. As it turned out, the problem was the graphics card driver. With the intel graphics card everything works fine. The problem is only on nvidia. Laptop. Windows10. Apparently the problem is the drivers. Translated with translate.yandex.ru

**Comment by alexandrudima** [comment] 2016-09-12 12:49
Using a vim emulation extension does bring in some latency, because in that case the typed letter `j` has to make its way from the main process to the extension host process, where the vim extension will react to it (hopefully the input parsing is fast), and it will then proceed to send a cursor position change request to the main process, which will then react to it, move the cursor, and paint at the next animation frame.

This latency is expected, and it should not account for more than a few ms (from when I tested the extension host architecture it was at 5ms roundtrip time). But the important thing is not to miss any typed `j`s which I think we do a good job at. So, if you press `j` for 10s and the OS is configured to produce 10 `j`s (one per second), the cursor should go down 10 lines.

**Comment by alexandrudima** [comment] 2016-09-14 17:13
@NiggyWizzyWoz Do you have a laptop with a touchscreen?

**Comment by alexandrudima** [comment] 2016-10-27 20:43
Closing after a number of days without a reply.

**Closed by alexandrudima** 2016-10-27 20:43 UTC
Labels: editor, needs more info
