### ISSUE TITLE
VSCode stops working

### ISSUE THREAD

**Issue by qoqaqola** [Microsoft/vscode#14532] opened 2016-10-26 12:44 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro (64bit)

Not long time ago an error started randomly occuring, screenshot provided: 
![image](https://cloud.githubusercontent.com/assets/14312785/19726258/b3d492e2-9b92-11e6-9ea0-5cd7d73bf49a.png)

Mostly working with HTML and CSS files. 
Error occurs randomly, after that, all compilers stop working, none of the changes display on localhost server and can't even close the VSCode itself, only thru task manager. It keeps bugging every 10 mins or so for now.

**Comment by weinand** [comment] 2016-10-26 15:18
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by qoqaqola** [comment] 2016-10-27 08:32
@weinand Tried to run VSCode without extensions, but error still occurs.
This is what console displays when error appears:
![image](https://cloud.githubusercontent.com/assets/14312785/19760166/ffd4b0b8-9c38-11e6-84c7-e03b879f2244.png)

**Comment by aeschli** [comment] 2017-02-01 15:03
Closing as I'm not able to reproduce.

**Closed by aeschli** 2017-02-01 15:03 UTC
Labels: freeze-slow-crash

**Comment by aeschli** [comment] 2017-02-21 22:26
Most likely a duplicate of #19840, now fixed. Please try the latest [insiders](https://code.visualstudio.com/insiders) build.
