### ISSUE TITLE
Bug: unable to copy full tooltip

### ISSUE THREAD

**Issue by vivainio** [microsoft/vscode#40493] opened 2017-12-19 07:51 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
prettier-vscode|esb|1.0.1
Ionide-fsharp|Ion|3.14.5
Go|luk|0.6.69
python|ms-|0.9.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
rust|rus|0.3.2

---

Steps to Reproduce:

1. Open a typescript file
2. Hover over something with a long type definition (where scrollbar exists)
3. Try to copy paste it to clipboard, either by:
 - starting to mark the area and dragging down. The scrollbar doesn't scroll, rather the marking stops once you leave the popup area
  - Pressing ctrl+a after clicking on the tooltip. This only marks all text in the typescript file

Use case: I have a complex inferred type definition that I would like to write down. Copy-pasting the definition would be the intuitive way to do this

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2017-12-19 10:16
@vivainio Have you tried triple clicking the definition and <kbd>Ctrl A</kbd>?

**Comment by vivainio** [comment] 2017-12-19 10:27
@joaomoreno I can't triple-click the tooltip. It gets dismissed on first click. I can howewer start dragging within it. Even when dragging, trying to press ctrl+A just selects the text in the full document, not the tooltip.

**Comment by joaomoreno** [comment] 2017-12-20 08:22
@vivainio That is very strange indeed. I can easily select text both in Windows and macOS, as long as the mouse cursor stays within the borders of the hover. I can especially use triple click to select whole lines.

![kapture 2017-12-20 at 9 21 23](https://user-images.githubusercontent.com/22350/34197532-37eceede-e567-11e7-9231-e6c827cf1db5.gif)

Can you record a screencast of the behaviour in your system?

Does it also reproduce with `code --disable-extensions`?

**Comment by vivainio** [comment] 2017-12-20 11:45
@joaomoreno that's the deal - you have to dave a tooltip large enough to have a scrollbar. Try to hover over 'foo' in this code:

```typescript
const foo = {
  a: 1,
  b: 1,
  c: 1,
  d: 1,
  e: 1,
  f: 1,
  g: 1,
  h: 1,
  i: 1,
  j: 1,
  k: 1,
  l: 1,
  m: 1,
  n: 1,
  o: 1,
  p: 1,
  q: 1,
  r: 1,
}
```

If you can't see the problem, I can do a screencast. Happens without extensions as well.

**Comment by joaomoreno** [comment] 2017-12-21 08:18
I see what you mean!

**Comment by RoarkeRandall** [comment] 2018-05-02 01:25
Copying from the tool tip is very inconsistent. I think its because the tooltip goes away if you leave the tooltip window, which can be very easy to do accidentally when you're dragging your cursor to select the text.

**Comment by joaomoreno** [comment] 2020-05-06 08:33
I believe this is now fixed. One can even click Ctrl A to select everything inside the hover, after clicking it.

**Closed by joaomoreno** 2020-05-06 08:33 UTC
Labels: bug, editor-hover
