### ISSUE TITLE
vim plugin crashed

### ISSUE THREAD

**Issue by zstar1993** [microsoft/vscode#177165] opened 2023-03-15 03:29 UTC
Type: <b>Bug</b>

My vim plugin host just stopped working.

VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|11, 12, 12|
|Memory (System)|32.00GB (1.65GB free)|
|Process Argv|--crash-reporter-id 16695919-4615-4d4c-825a-1ee06a98aa0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.8.4
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
filter-line|eve|2.0.1
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
vscode-drawio|hed|1.6.6
search-node-modules|jas|1.3.0
hex-fmt|ker|1.0.0
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.4
hexeditor|ms-|1.9.11
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5834
debugger-for-chrome|msj|4.13.0
docthis|oou|0.8.2
vscode-jest|Ort|5.2.3
fabric8-analytics|red|0.3.6
java|red|1.15.0
vscode-yaml|red|1.12.1
markdown-preview-enhanced|shd|0.6.8
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.9
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vim|vsc|1.25.2
quokka-vscode|Wal|1.0.528
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
funwalk2cf:30682975

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-15 07:40
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

Based on other recent issues my guess is Copilot. See #176562

**Comment by isidorn** [comment] 2023-03-15 11:02
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:02 UTC
Labels: freeze-slow-crash-leak, extension-host, triage-needed
