### ISSUE TITLE
Toggle Word Wrap is lost after zooming

### ISSUE THREAD

**Issue by freud** [Microsoft/vscode#23308] opened 2017-03-27 20:38 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.3.0|;

---

Steps to Reproduce:

1. Open .txt file with a very long text, to have a good possibility for word wrapping
2. Just wrap a very long text (ALT+Z)
3. Zoom in OR zoom out (Ctrl++ or Ctrl+-)
4. **The bug** is word wrapping state is now lost and words are unwrapped again, but a text should be still wrapped

**Comment by alexandrudima** [comment] 2017-03-28 12:20
Duplicate of #21487

**Closed by alexandrudima** 2017-03-28 12:20 UTC
