### ISSUE TITLE
Support relative paths in jump to file

### ISSUE THREAD

**Issue by mrkev** [Microsoft/vscode#63042] opened 2018-11-13 17:34 UTC
## Summary

When clicking `Cmd+P` one can jump to any file in the codebase by typing its name and selecting it from the results. This is to request that the input to that function supports file paths (specifically relative to the file I'm currently browsing), to filter (or at least sort) that list.

## Motivation / Workflow
I'm browsing a Javascript file in a codebase I don't know. I see a `require` pointing to `../../index.js`. It's easy enough for me to go to the file tree, and click my way up to the right file.

I, however, love `Cmd+P` and relying on my mouse/trackpad as little as possible. Typing `index.js` in a javascript codebase in the wild might yield results like this, however:

![React codebase: Cmd+P index.js](https://user-images.githubusercontent.com/1285131/48431388-93987c00-e73f-11e8-8ebf-ddd304a49041.png)
_(This is from the React codebase. Large codebases start having repeated names more often)_

I however _know_ which `index.js` file I want relative to the file I'm currently in. Intuitively, I type the path to the file I know I want (`../../index.js`), but that currently yields no results though:

![React codebase: Cmd+P ../../index.js](https://user-images.githubusercontent.com/1285131/48431512-dd816200-e73f-11e8-8eb8-495e09c2f17e.png)

This is a great opportunity for a new feature!

**Comment by mrkev** [comment] 2018-11-13 17:36
I'd actually be happy to work on this and submit a PR, but would appreciate some pointers in the general direction of the files I'd need to look at / work on (:

**Comment by mjbvz** [comment] 2018-11-13 22:47
Duplicate of #46242 I believe

@bpasero or @chrmarti may be able to provide some guidance if you are looking to work on this issue

**Closed by mjbvz** 2018-11-13 22:47 UTC
Labels: javascript

**Comment by mrkev** [comment] 2018-11-24 22:43
Yup, duplicate. Sorry, missed it on my quick search.

Is this a desired feature, down to work on it if so @bpasero @chrmarti
