### ISSUE TITLE
Extension context menu should appear on right click

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#52842] opened 2018-06-25 21:30 UTC
Is there any reason that the menu is only under the gear and not on right click? I only noticed this a few days ago but now it's bugging me. We definitely need the gear icon for discoverability but right click is much more convenient.

**Comment by sandy081** [comment] 2018-09-24 09:02
duplicate of #42737

**Closed** 2018-09-24 09:02 UTC
Labels: *duplicate, extensions, feature-request
