### ISSUE TITLE
 Cannot read property 'galleryInformation' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#669] opened 2015-11-25 22:07 UTC
Issue Id: <b>8334f064-5537-5eb2-61f3-3a8996e99dd8</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts#L325:16 (DataSource.getId)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts#L325:16 (DataSource.getId))<br />[/vs/base/parts/quickopen/browser/quickOpenViewer.ts#L32:59 (DataSource.getId)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/quickopen/browser/quickOpenViewer.ts#L32:59 (DataSource.getId))<br />[/vs/base/parts/tree/common/treeModel.ts#L1224:56 (TreeModel.getItem)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/common/treeModel.ts#L1224:56 (TreeModel.getItem))<br />[/vs/base/parts/tree/common/treeModel.ts#L944:19 (TreeModel.reveal)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/common/treeModel.ts#L944:19 (TreeModel.reveal))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[/vs/base/parts/tree/common/treeModel.ts#L943:5 (TreeModel.reveal)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/common/treeModel.ts#L943:5 (TreeModel.reveal))<br />[/vs/base/parts/tree/browser/treeImpl.ts#L157:20 (Tree.reveal)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/browser/treeImpl.ts#L157:20 (Tree.reveal))<br />[/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L542:14 (QuickOpenWidget.autoFocus)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L542:14 (QuickOpenWidget.autoFocus))<br />[/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L500:11 (QuickOpenWidget.setInputAndLayout)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L500:11 (QuickOpenWidget.setInputAndLayout))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete))<br />    at __dirname.undefined.t.Class.define.done (out/vs/workbench/workbench.main.js:1544:8710)<br />

**Comment by joaomoreno** [comment] 2015-11-26 09:27
The only explanation for this that I can find is #696. Closing this as a dupe of that and let's see if they keep on coming.

**Closed by joaomoreno** 2015-11-26 09:27 UTC
Labels: error
