### ISSUE TITLE
New emmet: possible abbreviation mismatch

### ISSUE THREAD

**Issue by Ser-Gen** [Microsoft/vscode#29302] opened 2017-06-23 07:54 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

---

Steps to Reproduce:

1. Open css file
2. Enter `minh` and press <kbd>tab</kbd>
3. Get `min-width: ;`

![vscode_newemmet_css_minh](https://user-images.githubusercontent.com/1856145/27471665-2e1b2e8c-5801-11e7-9df5-be6d9867d040.png)

**What is the expected behavior?**
Get `min-height: `, as it happens on [emmet site](https://docs.emmet.io/)

![vscode_insiders_emmet_css_demo](https://user-images.githubusercontent.com/1856145/27471745-811d223e-5801-11e7-8f1e-8a124865e868.gif)

**Comment by vvs** [comment] 2017-06-23 11:14
Looks like a duplicate of our good old friend #28933.

Essentially, Emmet has `mih` and `miw` shortcuts for `min-height` and `min-width`, and when you type minh, there is no such shortcut, so VS Code just defaults to the closest it finds, and in this case it is 'mih'.

Well, at least, that's not as bad as other examples in #28933 :)

**Comment by ramya-rao-a** [comment] 2017-06-23 16:20
> when you type minh, there is no such shortcut, so VS Code just defaults to the closest it finds

Actually that's not true. All the fuzzy logic matching of given shortcut to css property is done by the emmet module https://github.com/emmetio/expand-abbreviation

VS Code just passes the abbreviation to this module and displays the return value.

This is a regression in emmet itself. The old emmet gives `min-height` for `minh`.

**Comment by ramya-rao-a** [comment] 2017-06-23 16:20
This issue was moved to emmetio/atom-plugin#25

**Closed by ramya-rao-a** 2017-06-23 16:20 UTC
Labels: bug, emmet, new release
