### ISSUE TITLE
 Cannot read property 'detail' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3229] opened 2016-02-22 08:55 UTC
Issue Id: <b>70b9c65b-9ccd-16b5-73e0-508ddd36a5cc</b><br /><br />*Versions* <br />- 0.10.9<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />TypeError: Cannot read property 'detail' of undefined<br />    at t.e.onErrorEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:12:31088) <no sourcemaps><br />    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:11352 <no sourcemaps><br />    at Array.forEach (native)<br />    at e.emit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:11332) <no sourcemaps><br />    at e.onUnexpectedError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:11696) <no sourcemaps><br />    at Object.u [as onUnexpectedError] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:9137) <no sourcemaps><br />    at null._onTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:20:26789) <no sourcemaps><br />    at Timer.listOnTimeout (timers.js:89:15)<br />

**Comment by joaomoreno** [comment] 2016-02-22 14:12
Just published sourcemaps for db71ac6, but I still can't get a deminified stack in the service.

**Comment by joaomoreno** [comment] 2016-02-22 14:23
Ok, got it after all. Duplicate of #3231

**Closed by joaomoreno** 2016-02-22 14:23 UTC
Labels: error-telemetry
