### ISSUE TITLE
Why on EARTH can you not copy out of inline diffs?

### ISSUE THREAD

**Issue by ExtAnimal** [Microsoft/vscode#61571] opened 2018-10-23 07:33 UTC
You cannot copy old code out of the diffs! It's unbelievable. You can't even use the mouse to select a range in it.

![screen shot 2018-10-23 at 08 31 27](https://user-images.githubusercontent.com/200516/47343532-2fcde680-d69e-11e8-98f4-fd87d857fe9e.png)

**Comment by nealot** [comment] 2018-10-23 08:19
Duplicate of https://github.com/Microsoft/vscode/issues/8226

**Closed** 2018-10-23 10:42 UTC
Labels: diff-editor
