### ISSUE TITLE
Segfault on Linux after signing in to turn on Settings Sync

### ISSUE THREAD

**Issue by elseifthen** [microsoft/vscode#164223] opened 2022-10-21 08:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Linux, RHEL 7

Steps to Reproduce:

1. Turn on Settings Sync
2. Sign in in browser that opens (either with MS account or with github account)

[dumps.zip](https://github.com/microsoft/vscode/files/9837019/dumps.zip)

**Comment by sandy081** [comment] 2022-10-24 15:57
Can you please share a recording of what you are seeing? At which step you are getting this error?

**Comment by elseifthen** [comment] 2022-10-25 07:14
Sorry, I can't share a recording but it's right after I finished the login in the _browser_ window that opens after I select the sign-in method that is presented to me when I click Sign in & Turn on that the _VS Code_ window disappears and I get this error message in the terminal I started vscode from:

`[1025/091126.629287:ERROR:process_memory_range.cc(86)] read out of range
[1025/091126.629562:ERROR:elf_image_reader.cc(606)] missing nul-terminator
zsh: segmentation fault  /work/usr/VSCode-linux-x64/code --disable-extensions  /work/vscode-crash1
`

**Comment by sandy081** [comment] 2022-10-25 07:34
@TylerLeonhardt May be this is while storing the auth token?

**Comment by TylerLeonhardt** [comment] 2022-10-25 08:07
if you have nodejs installed, you can run this simple one-liner to see if the problem is how your keychain is setup:

```
npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication
```
or if you're on Insiders:
```
npx @emacs-grammarly/keytar-cli find-creds -s vscode-insidersvscode.github-authentication
```
This is using the following open source package: https://github.com/emacs-grammarly/keytar-cli

What you should get is something like this:
```js
[
  {
    account: 'github.auth',
    password: '....... longggg string ......'
  }
]
```
> NOTE: on macOS I got a system prompt to allow this process to access the keychain... that may or may not be the case for you

If that succeeds, then the problem is possibly in vscode.

If that _does_ complain, then we'll need to figure out a plan there.

**Comment by elseifthen** [comment] 2022-10-25 11:47
I _do_ get an error issuing this command:

`> npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /work/usr/node_modules/keytar/build/Release/keytar.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/work/usr/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}`

The glibc version on that system (RHEL7) is 2.17 according to yum info glibc. When I add a local library path to a newer gcc version (9.3.0) via

`export LD_LIBRARY_PATH=/work/usr/gcc-9.3.0/lib64:$LD_LIBRARY_PATH`

I can execute the command without an error but it returns an empty response as it seems:

`> npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication
[]`

**Comment by elseifthen** [comment] 2022-10-25 11:57
I _do_ get an error issuing this command:

`> npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /work/usr/node_modules/keytar/build/Release/keytar.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/work/usr/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}`

The glibc version on that system (RHEL7) is 2.17 according to yum info glibc. When I add a local library path to a newer gcc version (9.3.0) via

`export LD_LIBRARY_PATH=/work/usr/gcc-9.3.0/lib64:$LD_LIBRARY_PATH`

I can execute the command without an error but it returns an empty response as it seems:

`> npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication
[]`

**Comment by elseifthen** [comment] 2022-10-25 12:02
Sorry, I had accidentally closed this issue after a reboot;
I tried to execute vscode with the newer libs from gcc 9.3.0 in the LD_LIBRARY_PATH but when I tried to authenticate for the settings sync, I got a catastrophic crash of the xserver to a text screen so I had to reboot my machine. Probably not a good idea to mix the library versions…?

**Comment by deepak1556** [comment] 2022-11-04 11:46
Symbolicated trace:

```
Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x0
Process uptime: 22 seconds

Thread 26 (crashed)
 0  libc.so.6 + 0x13efd6
 1  libcrypto.so.10 + 0x1265b9
 2  libcrypto.so.10 + 0x1268a0
 3  vscode-encrypt-native.node!<.plt ELF section in vscode-encrypt-native.node> + 0x190e0
 4  vscode-encrypt-native.node!<.plt ELF section in vscode-encrypt-native.node> + 0x190e0
 5  libcrypto.so.10 + 0x715ff
 6  vscode-encrypt-native.node!<.plt ELF section in vscode-encrypt-native.node> + 0x190e0
 7  vscode-encrypt-native.node!ossl_init_no_add_all_ciphers_ossl_ + 0x10
 8  vscode-encrypt-native.node!ossl_init_no_add_all_ciphers_ossl_ + 0x10
 9  vscode-encrypt-native.node!openssl_add_all_ciphers_int + 0x2e8
10  vscode-encrypt-native.node!ossl_init_add_all_ciphers_ossl_ + 0x6
11  libpthread.so.0 + 0x620b
12  libpthread.so.0 + 0xcec0
13  vscode-encrypt-native.node!<.plt ELF section in vscode-encrypt-native.node> + 0x3dd74
14  vscode-encrypt-native.node!CRYPTO_THREAD_run_once + 0x6
15  vscode-encrypt-native.node!OPENSSL_init_crypto + 0x180
16  vscode-encrypt-native.node!Encryption::Encrypt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 0x2d
17  vscode-encrypt-native.node!EncryptWorker::Execute() + 0x3e
18  vscode-encrypt-native.node!Napi::AsyncWorker::OnExecute(Napi::Env) + 0x1a
19  code!worker [threadpool.c : 122 + 0x4]
```

**Comment by deepak1556** [comment] 2022-11-04 11:49
From the trace `vscode-encrypt` OpenSSL calls are going into `libcrypto.so` but we actually statically link the component for the desktop. @elseifthen how did you install VSCode ? Can you print the dependency list for vscode-encrypt-native.node from your VSCode installation `ldd <path-to-VSCode>/resources/app/node_modules.asar.unpacked/vscode-encrypt/build/Release/vscode-encrypt-native.node`

**Comment by elseifthen** [comment] 2022-11-04 11:55
I used the tar.gz package (e.g. code-stable-x64-1665614670.tar.gz)
`ldd ./resources/app/node_modules.asar.unpacked/vscode-encrypt/build/Release/vscode-encrypt-native.node
        linux-vdso.so.1 =>  (0x00007ffddc258000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fae6b38d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fae6b177000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fae6af5b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fae6ab8d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fae6b97b000)`

**Comment by deepak1556** [comment] 2022-11-04 12:08
Can you check if the issue repros with the rpm package ?

**Comment by elseifthen** [comment] 2022-11-04 12:23
Unfortunately not as I have no admin rights on this machine. Note that in order for vscode to run, I also need to change chrome-sandbox included in the tar.gz package to symbolically link to my local /opt/google/chrome/chrome-sandbox. Could this be the problem?

**Comment by TylerLeonhardt** [comment] 2022-12-08 19:40
> Could this be the problem?

That is very suspicious... though I'm not sure what to suggest.

**Comment by rzhao271** [comment] 2022-12-08 20:01
Here's a screenshot of the dependency list for the rpm package

![Dependency list](https://user-images.githubusercontent.com/7199958/206556118-735c01cc-5343-410d-9cc6-f0415316a3e8.png)

libcrypto isn't one of the entries

**Comment by gaoxiaosong** [comment] 2022-12-13 15:27
same issue. procedures:

1. `code --verbose --crash-reporter-directory xxx`.
2. open settings sync. 
3. login with microsoft account.
4. when jump back to vscode, it crashed.

error message in verbose log:

```
[1213/231533.628735:ERROR:process_memory_range.cc(86)] read out of range
[1213/231533.628812:ERROR:elf_image_reader.cc(606)] missing nul-terminator
```

crash files is attached:

[error.tar.gz](https://github.com/microsoft/vscode/files/10219392/error.tar.gz)

environment:

* system: CentOS 7.6.1810
* desktop: xfce
* `code --version`: `1.74.0` + `5235c6bb189b60b01b1f49062f4ffa42384f8c91` + `x64`
* `yum info code`: x86_64 + 1.74.0 + 1670260117.el7
* yum source: `baseurl=https://packages.microsoft.com/yumrepos/vscode`
* `ldd --version`: 2.17
* `yum info glibc`: x86_64 + 2.17 + 326.el7_9
* `npx @emacs-grammarly/keytar-cli find-creds -s vscodevscode.github-authentication`: `[]`

**Comment by TylerLeonhardt** [comment] 2022-12-13 16:50
@gaoxiaosong I believe you're seeing https://github.com/microsoft/vscode/issues/167136 which is the issue we are using for tracking the CentOS crash.

**Comment by rzhao271** [comment] 2022-12-15 21:27
gaoxiaosong's symbolicated crash dump is the same as https://github.com/microsoft/vscode/issues/164223#issuecomment-1303309116. This issue can be used to keep track of the sign-in crash aka libcrypto issue.

**Comment by nickhine** [comment] 2023-01-04 11:06
Any update on this? This is stopping me from being able to use github or microsoft authentication on our CentOS 7 machines currently.

**Comment by austin-communitylands** [comment] 2023-02-02 20:25
Also seeing this issue on Amazon Linux 2 when logging into Github.

**Comment by luiz-garrido** [comment] 2023-02-03 15:08
> Also seeing this issue on Amazon Linux 2 when logging into Github.

Same here. My workaround since my home folder is on the network was to launch vscode from a Rocky Linux 8 VM, do the login and then go back to my VM with Amazon Linux 2

**Comment by ricrogz** [comment] 2023-02-08 16:06
Same crash here, CentOS 7 too.

**Comment by CS-Account** [comment] 2023-02-08 23:57
If it's at all helpful, I kept copies of vscode versions as I upgraded every month or so and going back to september I seem to be able to log in without issue, so whatever change caused this likely happened between then and now.

**Comment by fabmac** [comment] 2023-02-12 22:16
Confirming I'm getting the same crash, following the same original repro steps:
* CentOS `7.8.2003`
* vscode `1.75.1` `441438abd1ac652551dbe4d408dfcec8a499b8bf` `x64`

**Comment by CS-Account** [comment] 2023-02-22 18:58
Small update: I found a GCC install with compatibility past the minimum requirements (GLIBCXX 3.4.21) and added that to my LD_LIBRARY_PATH, and it did not appear to work. Not sure how useful that is to anyone, but I figured since the default version on my system only went up to 3.4.19, using one that went further might perhaps solve the problem. It did not. Unfortunately I am still looking for a workaround or solution.

**Comment by ricrogz** [comment] 2023-03-01 20:25
VS Code 1.76 seems to fix it for me (I'm using a gcc 9.3.0 environment here).

**Comment by CS-Account** [comment] 2023-03-01 23:05
> VS Code 1.76 seems to fix it for me (I'm using a gcc 9.3.0 environment here).

Just wanted to tag on that 1.76 seems to have fixed this for me as well

**Comment by CS-Account** [comment] 2023-03-01 23:12
Actually I do note that it doesn't seem to stay signed in, so maybe the underlying issue is still there but it just doesn't cause a complete crash. Still better than before though.

**Comment by webtoolbox** [comment] 2023-05-07 07:38
This also makes github copilot unusable on Amazon Linux 2.

**Comment by thirstyice** [comment] 2023-06-03 01:56
This happens for me on Ubuntu 23.04 with the snap store version, but not with the .deb package from the downloads page

**Comment by TylerLeonhardt** [comment] 2023-12-13 18:56
This seems to have been caused by our dependency on keytar but we removed that in favor of an electron native API. Closing this as it should be fixed but if you still see this issue, please don't be afraid to open a new issue.

**Closed by TylerLeonhardt** 2023-12-13 18:56 UTC
Labels: bug, freeze-slow-crash-leak, linux, confirmation-pending, authentication
