### ISSUE TITLE
Bottom panel sometimes blank when opening a new window

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103886] opened 2020-08-03 23:47 UTC
For the last week or two I've noticed that _sometimes_ the bottom panel is blank when I open a new window

![](https://memes.peet.io/img/20-08-e3b17f84-f621-4bc1-b3ba-bb2aa41bbd54.png)

Here's a stacktrace of an error shown when this happens:

```
 ERR Cannot read property 'setViewVisible' of undefined: TypeError: Cannot read property 'setViewVisible' of undefined
    at O.setPanelHidden (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6517:611)
    at Object.hidePart (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6465:609)
    at _.resetActiveComposite (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6332:609)
    at _.hideComposite (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6331:529)
    at e.hideComposite (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6470:467)
    at e.onDidChangeActiveViews (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6469:321)
    at e.onDidRegisterPanels (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6467:917)
    at file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6469:651
    at c.fire (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at l.registerComposite (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3038:921)
    at l.registerPanel (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3976:932)
    at k.registerPanel (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5835:533)
    at k.registerViewletOrPanel (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5834:777)
    at k.onDidRegisterViewContainer (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5828:365)
    at file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5826:59
    at Array.forEach (<anonymous>)
    at new k (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5826:43)
    at d._createInstance (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:888)
    at d._createServiceInstance (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1662:874)
    at d._createServiceInstanceWithOwner (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1662:399)
    at d._createAndCacheServiceInstance (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1662:74)
    at d._getOrCreateServiceInstance (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1661:381)
    at Object.get (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1659:948)
    at O.initLayout (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6492:220)
    at file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6570:210
    at d.invokeFunction (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1659:817)
    at O.startup (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6570:61)
    at q.open (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7689:911)
 ```

It's recoverable by manually opening and closing the panel

**Comment by TimWhiting** [comment] 2020-08-07 16:44
I've been getting the same error. It's been happening for awhile for me.

**Comment by sbatten** [comment] 2020-08-27 17:26
dupe of #105480

**Closed by sbatten** 2020-08-27 17:26 UTC
Labels: *duplicate
