### ISSUE TITLE
Too many repositories open

### ISSUE THREAD

**Issue by purocean** [Microsoft/vscode#40249] opened 2017-12-15 03:21 UTC
- VSCode Version: 1.19
- OS Version: Windows 10

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/7115690/34025288-fe97fcea-e189-11e7-8294-9d3caa72f85d.png)

2.
![image](https://user-images.githubusercontent.com/7115690/34025312-1b3057f8-e18a-11e7-99f2-9bf00e9d8b98.png)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment] 2017-12-15 04:25
This is being tracked in #40229

**Comment by joaomoreno** [comment] 2017-12-15 07:09
@purocean Are all those repositories the same? Or different ones inside your open directory?

**Comment by purocean** [comment] 2017-12-15 07:38
@joaomoreno Just one. Rollback *1.18.1* it's fine. BTW I use the *WSL git* https://github.com/purocean/wslproxy May be cause the problem.

**Comment by joaomoreno** [comment] 2017-12-15 08:09
Can you reproduce using Git for Windows?

Related to https://github.com/Microsoft/vscode/issues/9502

**Comment by javifm86** [comment] 2017-12-15 08:34
![imagen](https://user-images.githubusercontent.com/11178810/34033458-9986a914-e17a-11e7-8173-edae9edb276d.png)

Same problem here on Windows 10 with latest version.

**Comment by joaomoreno** [comment] 2017-12-15 08:39
@javifm86 What is the full path of that repository? What is the full path of the folder you have opened?

**Comment by javifm86** [comment] 2017-12-15 08:45
@joaomoreno The full path is just J:\

**Comment by purocean** [comment] 2017-12-15 09:04
@joaomoreno Can not reproduce. I am try to find the reason.

**Comment by joaomoreno** [comment] 2017-12-15 09:05
@purocean OK good. You have a duplicate of #9502.

@javifm86 Are you using Git for Windows? Or WSL?

**Comment by javifm86** [comment] 2017-12-15 09:14
@joaomoreno Git for windows installed on C:\Program Files\Git\bin. No git.path setting in vscode.

**Comment by joaomoreno** [comment] 2017-12-15 09:19
@javifm86 I created a repository in `J:` and that doesn't seem to reproduce it.

What else? Tell me exactly what you did, what your steps are, what the names of every open folder are. Send me a screen recording. Etc.

**Comment by javifm86** [comment] 2017-12-15 10:25
@joaomoreno Ok, here the information. It´s a legacy project, a monster :(
I have Git for Windows, https://git-scm.com/download/win, 64 bits version.
I have folder in my workspace, J:, with a lot of folders, subfolders and files.
In J:, I have a git repository, which whas working ok in vscode.
In some subfolders, there are also other git repositories (project hell).

I just open vscode, and git repositories start to duplicate and grow with high cpu usage.

![imagen](https://user-images.githubusercontent.com/11178810/34037838-855e3e10-e18a-11e7-8908-eeac90c32bdd.png)

![imagen](https://user-images.githubusercontent.com/11178810/34037858-91714db4-e18a-11e7-97e3-25d985945c99.png)

![imagen](https://user-images.githubusercontent.com/11178810/34037868-98bfecf6-e18a-11e7-9736-8a9d7757cf1e.png)

Sorry I can´t install here a screen recorder.

**Comment by joaomoreno** [comment] 2017-12-15 10:33
@javifm86 This started happening in 1.19?

**Comment by joaomoreno** [comment] 2017-12-15 10:40
I still can't seem to reproduce:

![image](https://user-images.githubusercontent.com/22350/34038454-b22bada4-e18c-11e7-8e36-7c5610ffbacf.png)

Can you try to find a smaller sample in which this still happens?

**Comment by javifm86** [comment] 2017-12-15 10:54
Yes it started happening today when y updated to 1.19.

**Comment by purocean** [comment] 2017-12-15 11:03
@joaomoreno @javifm86  I can reproduce. Use new *git* with **old && existed** repository

But when I use new repository, it's can't reproduced.

**Comment by joaomoreno** [comment] 2017-12-15 11:05
@purocean We already determined your issue is related to WSL... which we do not yet support:  #9502.

**Comment by purocean** [comment] 2017-12-15 11:11
@joaomoreno NONO. I use @joaomoreno STEPS. 
![image](https://user-images.githubusercontent.com/7115690/34039704-8bc5edf2-e1cb-11e7-89d2-19d0722132f6.png)
![image](https://user-images.githubusercontent.com/7115690/34039706-91d2c3be-e1cb-11e7-93af-962f25c1706d.png)
![image](https://user-images.githubusercontent.com/7115690/34039713-97b16d58-e1cb-11e7-8fd5-b17492400aeb.png)

I am trying find reason

**Comment by joaomoreno** [comment] 2017-12-15 11:12
OK. Good. But when you use that, you don't see the bug...

**Comment by purocean** [comment] 2017-12-15 12:31
@joaomoreno Sorry I made some mistakes. I cant reproduce it.

**Comment by purocean** [comment] 2017-12-15 13:29
I am track code:
```js
// model.js
        if (hint instanceof vscode_1.Uri) {
            console.log('111111111')
            const resourcePath = hint.fsPath;
            for (const liveRepository of this.openRepositories) {
                const relativePath = path.relative(liveRepository.repository.root, resourcePath);
                console.log(liveRepository.repository.root, resourcePath)
                if (util_1.isDescendant(liveRepository.repository.root, resourcePath)) {
                    return liveRepository;
                }
            }
            return undefined;
        }
```

```js
// util.js
function isDescendant(parent, descendant) {
    if (parent === descendant) {
        return true;
    }
    if (parent.charAt(parent.length - 1) !== path_1.sep) {
        parent += path_1.sep;
    }
    return descendant.startsWith(parent);
}
```
![image](https://user-images.githubusercontent.com/7115690/34043512-6d9e57ae-e1dc-11e7-967d-bc797e37b5a0.png)

So I change my [WSL proxy program](https://github.com/purocean/wslproxy/commit/5c24cf7118aac03358f98ccc63f203638d5c8943). It‘s work! 

`isDescendant` function maybe it can be ignore case on Windows platform.

**Comment by joaomoreno** [comment] 2017-12-15 13:56
@purocean Actually, this sounds like a bug in your WSL proxy program.

Specifically because of path casing issues, we always ask [`rev-parse --show-toplevel`](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/model.ts#L193) to git. From then on, every path magic we do is based on the result of that call. So, if Git returns uppercase `C`, we will use `C`. The same, otherwise.

I'm glad you found a fix in your code though.

---

I'm more interested in knowing how @javifm86 actually hits this. @javifm86, no, it shouldn't be related to many files, but rather to how you open the folders in VS Code. Do you use the wrong casing in certain paths?

**Comment by javifm86** [comment] 2017-12-15 15:58
@joaomoreno I don´t know exactly what do you mean by casing certain paths. I have two folders, corresponding to network drives mapped to I: and J:

I: ( sorry, I was wrong when I said before J:, I don´t know if this detail can be relevant ), has a .git folder. And there is another .git folder inside a subfolder. VsCode just recognized before the update one git repository, the main .git folder from I:.

In my workspace I have another network drive mapped in J:, which has a .git folder in a subfolder.

I have tried just with Open folder option from vscode and just opening I:, and the same behaviour is repeated.

**Comment by joaomoreno** [comment] 2017-12-18 09:12
> I have tried just with Open folder option from vscode and just opening I:, and the same behaviour is repeated.

So, the problem is with `I:`.

Please give me exact names... we need to distill this issue to its bare minimum. Does the problem reproduce if you remove that `.git` folder inside the subfolder of `I:`? Is the subfolder immediately inside `I:`, or is it inside another folder?

Try to come up with a very specific git repository in which the problem still occurs and tell me exactly what is in it and how you opened it.

**Comment by javifm86** [comment] 2017-12-19 07:36
**ls -lart** shows me this info (there a lot of folders and subfolders and files, I have changed the name, I think it ´s not relevant.

$ ls -lart
total 71684
-rw-r--r-- 1 javifm86 1049089      354 Jan 24  2008 file.jsp
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Apr  4  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Jul  4  2013 nameFolder
-rw-r--r-- 1 javifm86 1049089     2021 Aug 28  2013 nameFolder
-rw-r--r-- 1 javifm86 1049089     2200 Aug 28  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Sep 19  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Sep 19  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Sep 19  2013 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Feb  5  2014 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 Feb 18  2014 nameFolder
-rw-r--r-- 1 javifm86 1049089     2560 Feb 19  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     3248 Feb 19  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     1612 Feb 19  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089      276 Feb 19  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     5061 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     2378 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     9248 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     3992 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     4857 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     1019 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     1715 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     2357 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     1931 Feb 20  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089     1067 Nov 27  2014 file.jsp
-rw-r--r-- 1 javifm86 1049089    12123 Feb 16  2015 file.jsp
drwxr-xr-x 1 javifm86 1049089        0 Apr 17  2015 nameFolder
drwxr-xr-x 1 javifm86 1049089        0 May 25  2015 nameFolder
-rw-r--r-- 1 javifm86 1049089     2391 Jul 21  2015 file.jsp
drwxr-xr-x 1 javifm86 1049089        0 Jul 28  2015 nameFolder
-rw-r--r-- 1 javifm86 1049089     3498 Jul 29  2015 file.jsp
drwxr-xr-x 1 javifm86 1049089        0 Nov 22 17:31 .vscode

.
.
.

drwxr-xr-x 1 javifm86 1049089        0 Dec 14 12:52 .
-rw-r--r-- 1 javifm86 1049089      261 Dec 14 12:54 .editorconfig
-rw-r--r-- 1 javifm86 1049089    35006 Dec 15 17:21 file.jsp
**-rw-r--r-- 1 javifm86 1049089      802 Dec 18 11:49 .gitignore
drwxr-xr-x 1 javifm86 1049089        0 Dec 18 16:26 .git**

I think it is a problem with .gitconfig file and core.worktree.

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	**worktree = I:/**
	symlinks = false
	ignorecase = true

If I comment that line, problem solved.

**Comment by joaomoreno** [comment] 2017-12-19 08:10
@javifm86 Interesting. How are you running `ls -lart`, if you are using Windows?

**Comment by javifm86** [comment] 2017-12-19 08:18
@joaomoreno From git bash I can use some Linux commands. I have this setting for vsCode Terminal:

`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`

Trust me, I am using Windows 10. :smile: :smile:

![imagen](https://user-images.githubusercontent.com/11178810/34147275-674b6496-e49d-11e7-900b-66b5cdafac7e.png)

**Comment by joaomoreno** [comment] 2017-12-19 08:56
Why do you have that worktree setting? Do you really need it?

Also, what does `git worktree list` return?

**Comment by javifm86** [comment] 2017-12-19 09:24
It is a very old legacy project. I don´t know why is worktree setting there. I think it´s not neccesary so I commented it.
```
$ git worktree list
I:  1ca3d18 [master]
```

**Comment by joaomoreno** [comment] 2017-12-19 09:53
OK, great. I'll close this then, attributing it to bad user configuration. I'll keep it in mind if more people come with similar issues.

**Closed by joaomoreno** 2017-12-19 09:53 UTC
Labels: needs more info

**Comment by javifm86** [comment] 2017-12-19 09:55
Thanks for your attention. :wink:

**Comment by Cartman16** [comment] 2017-12-19 20:41
I just had the time to look here again, know. Thanks for pointing me into the right direction @joaomoreno. I had the working tree issue as well.

If anyone stumbles over this isssue again. I just used the following command to disable the setting:
`git config --unset core.worktree`

**Comment by jonaskello** [comment] 2018-01-02 08:25
I too get this error, but the reason I get it is becuase I am using msys2 with the solution in #4651. It seems this solution is now broken and gives the problems described in this issue.
