### ISSUE TITLE
Cannot type Korean. Splitted self or missing.

### ISSUE THREAD

**Issue by estylehq** [microsoft/vscode#134254] opened 2021-10-01 01:48 UTC
Cannot type Korean right way. Splitted it-self or missing.
> 한글을 정상적으로 입력 할 수 없습니다. 스스로 분해되거나, 사라집니다.

- VS Code Version: 1.60.2 / 7f6ab5485bbc008386c4386d08766667e155244e
- OS Version: macOS Big Sur 11.6 (20G165) / Darwin x64 20.6.0

Steps to Reproduce:

1. Open VS Code.

2. Load any project. (Vue/Nuxt.js project, My case)

3. Click menu; File > New file or `CTRL + N`

4. Input Some words
> `한글을 입력합니다.`

#### Result

ex) `한글을 입력합니다.` -> `한ㅡㄹㅡ 입ㅕ 합ㅣㅏ.`

next combination is failed before completed word, is missing first Moum.
> 글자가 완성된 바로 다음 글자에서 첫 모음이 탈락 됩니다.

-------------

### System information

CPUs | Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 3, 2
Memory (System) | 40.00GB (19.15GB free)
Process Argv | --crash-reporter-id cd8aaa42-d408-4689-814a-178ec03bacb8
Screen Reader | no
VM | 0%

-----------

### Enabled Extensions 

Extension | Author (truncated) | Version
-- | -- | --
android-dev-ext | ade | 1.3.2
Bookmarks | ale | 13.2.1
format-json | Cle | 1.0.2
dart-code | Dar | 3.26.0
flutter | Dar | 3.26.0
vscode-eslint | dba | 2.1.25
jquerysnippets | don | 0.0.1
gitlens | eam | 11.6.0
vscode-html-css | ecm | 1.10.2
react-native-react-redux | EQu | 2.0.6
prettier-vscode | esb | 9.0.0
code-runner | for | 0.11.5
vscode-env | Iro | 0.1.0
code-beautifier | mic | 2.3.3
vscode-edge-devtools | ms- | 1.3.1
nativescript-vue-snippets | msa | 0.9.0
debugger-for-chrome | msj | 4.13.0
debugger-for-edge | msj | 1.0.15
vscode-react-native | msj | 1.7.0
nativescript | Nat | 0.12.3
nativescript-vue-extend | nuo | 0.0.2
vetur | oct | 0.34.1
vscode-scss-formatter | sib | 2.2.4
ReactSnippets | xab | 2.4.0
markdown-pdf | yza | 1.4.4

------ 

### A/B experiment info

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
```

**Comment by estylehq** [comment] 2021-10-01 01:51
https://user-images.githubusercontent.com/37822976/135553279-4def3266-62c8-453e-ac64-82aa1e5ace69.mov

**Comment by CodeCrazy-ywt** [comment] 2021-10-04 15:59
Have you seen this bug in other apps?
다른 앱에서 이 버그를 본 적이 있습니까?

**Comment by estylehq** [comment] 2021-10-05 01:00
> Have you seen this bug in other apps? 다른 앱에서 이 버그를 본 적이 있습니까?

I never seen before.

I think It's not prob, from mac os.

**Comment by csobj** [comment] 2021-10-12 04:53
@estylehq  On my experiences with similar issues, it caused by the kind of linter extension like spell checker.

**Comment by CodeCrazy-ywt** [comment] 2021-10-15 07:58
I know a little bit about Korean, and I think I'm capable enough to add some info.
First of all, the keyboard most Korean people use is different from those used by people using Latin letter-based languages.
![Screenshot_20211015154219](https://user-images.githubusercontent.com/62426149/137451292-c39fc77c-f7e7-404c-8428-69f86d6d2f80.jpg)
In addition, one Korean "character" is composed of two or more "small parts". Take 병 for example, it's made up of ㅂ, ㅕ and ㅇ, so when a Korean want to type this, he/she just needs to type these three parts.
As you can see, 력 turns intoㅕ and 니 turns into ㅣ, which means that some "parts" are missing when typing.

**Comment by alexdima** [comment] 2021-10-15 13:14
@CodeCrazy-ywt Thank you for your comment, it has been really helpful to understand what to do to reproduce.

Here are the steps that I'm now doing:
* install and switch to the `2-Set Korean` keyboard layout on macOS
* press `q`, `u`, `d`
* this should result in this character: `병`, as it does in this `<textarea>` or in Word
* in VS Code, this results in `벼ㅇ`

#### VS Code:

https://user-images.githubusercontent.com/5047891/137492433-adffa290-97ef-484f-841f-ed1a04483aaf.mp4

#### Browser:

https://user-images.githubusercontent.com/5047891/137492575-1f5c813a-c71a-4f75-83a0-9daa37624dbf.mp4

**Comment by estylehq** [comment] 2021-10-15 14:57
@CodeCrazy-ywt
- Thank you.

@alexdima 
- You type just one charactor.
- It makes with combining Mo-um/모음 and Ja-um/자음 (and Bat-chim/받침).
- Your example videos also I had.

Please trying to this step:

1. Changed Korean type mode (2-Set Korean)
2. Type charactors ; dkssudgktpdy / 안녕하세요 / Mean, Hello
3. Type charactors ; gksrmfdmf dlqfur gkqslek / 한글을 입력 합니다 / Mean, Input Korean. (sentense)

This very serious No.3 case, I can't type sentense anymore. I ever seen before macOS Big Sur Upgrading.(It is not meaning Prob Big Sur).

I ah, guess It is new bug VS Code new version, cause it was not happened before.

**Comment by nyschoi** [comment] 2021-10-18 04:38
I only know workaround about this.
If you go to the link below, vscode do not seem to work well w/ default font.
https://rottk.tistory.com/entry/VSCode-한글-받침-분리-현상

So I had to delete all fonts set as default in vscode except for D2Coding ligature (which is my personal font).
Below is a part of my setting.json file.

`
{
    "editor.fontFamily": "D2Coding ligature",
    "editor.fontLigatures": true,
    "files.exclude": {
        "**/__pycache__": true,
        "**/.anaconda": true,
        "**/.classpath": true,
        "**/.dropbox": true,
        "**/.dropbox.cache": true,
        "**/.factorypath": true,
        "**/.gitignore": true,
        "**/.h5": true,
        "**/.ipynb_checkpoints": true,
        "**/.jupyter": true,
        "**/.kite": true,
        "**/.localized": true,
        "**/.matplotlib": true,
        "**/.project": true,
        "**/.pylintrc": true,
        "**/.settings": true,
        "**/.vscode": true,
        "**/*.h5": true,
        "**/Icon?": true
    },
    "workbench.fontAliasing": "auto",
    "debug.console.fontSize": 16,
    "debug.console.fontFamily": "D2Coding ligature",
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.fontWeightBold": "normal",
    "terminal.integrated.fontFamily": "D2Coding ligature",
`

**Comment by alexdima** [comment] 2021-11-29 22:00
I am fairly confident that this was caused by us writing to textarea (changing its value) during the `compositionstart` event. In other words, I think the fix for #138095 will also fix this issue. I would be very thankful if you could verify that the issue no longer reproduces using tomorrow's [Insiders](https://code.visualstudio.com/insiders/) that should be released in 9-10 hrs.

**Closed by alexdima** 2021-11-29 22:00 UTC
Labels: upstream, macos, editor-input-IME

**Comment by TylerLeonhardt** [comment] 2021-12-03 22:24
@estylehq can you try this now using [VS Code insiders](https://code.visualstudio.com/insiders)? It's a separate installation and won't mess up what you have configured in VS Code stable.

**Comment by estylehq** [comment] 2021-12-05 02:52
@TylerLeonhardt 

Hello.

I can't check this right now. I will try this monday asap, comment here.

Thank you.

**Comment by estylehq** [comment] 2021-12-16 06:33
@TylerLeonhardt 
@rzhao271 

Sorry for late.

It really perfectly works.
