### ISSUE TITLE
".vscode/settings.json" inside a workspace folder will render the editor inoperable

### ISSUE THREAD

**Issue by d0ggie** [Microsoft/vscode#33137] opened 2017-08-25 09:40 UTC
- VSCode Version: Code - Insiders 1.16.0-insider  b9ac10234f86f145fdbcf066758934e0857d7592, 2017-08-25T05:24:57.523Z 
- OS Version: Windows 10
- Reproduces without extensions: Yes (note: extensions' .vscode/*.json doesn't seem to be affected)

Steps to reproduce:
- Place (an empty is enough) .vscode/settings.json file under a workspace folder,
- Open the workspace,
- Every file will now display "Place your folder settings here to overwrite those from the Workspace Settings." and merge some of the parsed .json contents with the editor, thus rendering the editor pretty much inoperable as it breaks e.g. syntax hilighting.

In my case, the .vscode/settings.json was a leftover file from an older version. Don't think it should break the VSCode anyway? A day older or so build was working just fine, so this is likely due to some very recent change. Tried with and without extensions.

**Comment by sandy081** [comment] 2017-08-28 08:27
Duplicate of #33130

**Closed by sandy081** 2017-08-28 08:27 UTC
Labels: config, insiders
