### ISSUE TITLE
VScode occupy 75% of cpu.

### ISSUE THREAD

**Issue by yy7054wyq5** [Microsoft/vscode#30897] opened 2017-07-18 03:42 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.18.1
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.11
php-debug|fel|1.11.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
docthis|joe|0.4.7
Angular2|joh|2.4.0
sublime-babel-vscode|jos|0.2.6
vscode-filesize|mkx|1.0.0
debugger-for-chrome|msj|3.1.6
code-settings-sync|Sha|2.8.2
autoimport|ste|1.2.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1.I had close all of Extension.
2.I just run a gulp task in cmd.

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-07-18 08:11
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by yi-huan** [comment] 2017-07-18 08:21
自从升级创意者版本（win10 15063.483）后也造成CPU占用过高，一会儿卡死。

**Comment by bpasero** [comment] 2017-07-18 10:04
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by yy7054wyq5** [comment] 2017-07-18 10:06
I will update this issue in next time when the bug meet again.

**Comment by ypresto** [comment] 2017-07-18 15:53
I disabled all extensions but reproducing the same issue.

- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:07:20.317Z)
- OS Version: Darwin x64 16.6.0

**Comment by ypresto** [comment] 2017-07-18 15:54
When I kill process using CPU much, got below error: (killed twice)
![image](https://user-images.githubusercontent.com/400558/28326823-c62aa9a8-6c1c-11e7-89c2-6c6585bf5f8a.png)

**Comment by ypresto** [comment] 2017-07-18 16:00
Does not reproduce with 1.13.1 stable.

**Comment by yy7054wyq5** [comment] 2017-07-20 02:12
I got 15 pictures. I email to you @bpasero

**Comment by bpasero** [comment] 2017-07-20 04:41
@yy7054wyq5 did you try to reproduce without extensions? Run code --disable-extensions

**Comment by ypresto** [comment] 2017-07-20 05:50
hmm, it does not occur anymore with latest Insider. (Extensions enabled.)

- VSCode Version: Code - Insiders 1.15.0-insider (5a01cdc0c8ee4d807b80e891b9faa95a913650b0, 2017-07-19T22:01:38.817Z)
- OS Version: Darwin x64 16.6.0

**Comment by yy7054wyq5** [comment] 2017-07-20 06:38
@bpasero Before i save the pictures, I had close all of extensions.

**Comment by bpasero** [comment] 2017-07-20 06:51
@yy7054wyq5 does it reproduce with any folder you open? also in empty workspaces?

**Comment by yi-huan** [comment] 2017-07-20 07:46
update: 
[My problem](https://github.com/Microsoft/vscode/issues/30897#issuecomment-315993249) has been solved. CPU no longer rises to 100%.
I updated Nodejs, upgraded from 6.9.5 to 6.11.1

**Comment by yy7054wyq5** [comment] 2017-07-21 02:44
I think this bug is vscode-eslint cause. I close VScode, I find it still in process and same as VScode.

**Comment by bpasero** [comment] 2017-07-21 07:11
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-07-21 07:11 UTC
Labels: freeze-slow-crash, needs more info, new release

**Comment by yy7054wyq5** [comment] 2017-07-24 02:10
Thanks @bpasero
