### ISSUE TITLE
[Idea] Support for Mica effect/Blur effect for Windows 11

### ISSUE THREAD

**Issue by milindgoel15** [microsoft/vscode#141827] opened 2022-01-30 13:09 UTC
The title basically sums everything up. We would love to see the mica effect on vscode. As of now, we can only do this via extensions such as vibrancy but that makes the version unsupported and buggy. 

However, official mica support would be awesome.

**Comment by IllusionMH** [comment] 2022-01-30 22:15
/duplicate of #133774 which in turn is duplicate of #115641 and others

**Closed** 2022-01-30 22:16 UTC
Labels: *duplicate, triage-needed
