### ISSUE TITLE
Remote extension host won't start at all/continually restarts ad-infinitum

### ISSUE THREAD

**Issue by GigglePocket** [microsoft/vscode#146490] opened 2022-04-01 03:52 UTC
Error message:
"Remote Extension host terminated unexpectedly 3 times within the last 5 minutes."

I have searched this error and found 2 other issues open [(#4693)](https://github.com/coder/code-server/issues/4693) & [(#4773)](https://github.com/coder/code-server/issues/4773) but saw no solutions recommended.

I've tried running with all extensions disabled, rebuilding the container, running in Firefox (I'm in Chrome), all with the same result.

Apologies if this is a duplicate. I've tried everything I can think of.

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
Embedder: codespaces

**Comment by hmccafferty** [comment] 2022-04-01 15:21
Same here since last night

**Comment by GigglePocket** [comment] 2022-04-01 16:53
[@TylerLeonhardt](https://github.com/TylerLeonhardt) If I can provide any additional information that would help diagnose this issue, please let me know. Thank you for your help.

**Comment by rongxin-liu** [comment] 2022-04-02 02:52
Hi all, afraid we're experiencing the same issue.

cc @dmalan

**Comment by GigglePocket** [comment] 2022-04-02 04:34
Not sure if it's relevant but, these 3 values in the .devcontainer.json:
```json
    "/opt/cs50/extensions/cs50-0.0.1.vsix", 
    "/opt/cs50/extensions/ddb50-0.0.1.vsix", 
    "/opt/cs50/extensions/phpliteadmin-0.0.1.vsix",
```
Raise the warning: 

```bash
 Expected format: '${publisher}.${name}' or '${publisher}.${name}@${version}'. 
```

**Comment by rongxin-liu** [comment] 2022-04-02 14:57
I launched a Codespace with just these extensions pre-installed and use the default image for the container:

This is my `.devcontainer.json` file:
```
{
  "extensions": [
    "ms-python.python",
    "ms-vscode.cpptools",
    "ms-vscode.hexeditor",
    "ms-vsliveshare.vsliveshare-audio",
    "MS-vsliveshare.vsliveshare-pack",
    "vsls-contrib.gitdoc"
  ]
}
```

But I'm still seeing Extension Host crashed and restarted itself in the console log:

```
ERR Extension host (Remote) terminated unexpectedly with code null.
log.ts:313   ERR Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git-base, vscode.ipynb, GitHub.codespaces, GitHub.vscode-pull-request-github, vscode.git, vscode.github, vscode.github-authentication, vscode.emmet, vscode.merge-conflict, vsls-contrib.gitdoc, ms-vsliveshare.vsliveshare, ms-vsliveshare.vsliveshare-audio
log.ts:301  INFO Automatically restarting the remote extension host.
```

And I'm still getting the same error message: `Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.`

How often would an extension host be terminated unexpectedly? What might have caused it to terminate in general?

**Comment by rongxin-liu** [comment] 2022-04-02 15:21
To follow up, I launched a Codespace with an empty `.devcontainer.json` file (no pre-install extensions, just the default ones), but I'm afraid still getting the same errors:
```
ERR Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git-base, vscode.ipynb, GitHub.codespaces, GitHub.vscode-pull-request-github, vscode.git, vscode.github, vscode.github-authentication, vscode.emmet, vscode.merge-conflict, vscode.html-language-features
```

![Screen Shot 2022-04-02 at 11 16 25](https://user-images.githubusercontent.com/10591665/161389876-7b137cd2-6a43-4533-82a7-72039b3ebee0.png)

Visual Studio Code version info:

```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:48:56.452Z (3 days ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
``` 

I hope this helps!

**Comment by GigglePocket** [comment] 2022-04-02 16:28
Thank you for the update. I was able to use my codespace for a couple of hours last night without the extension host failing. This was after stopping the codespace and restarting 3 times, then reloading the window twice. It seems to be somewhat random when it restarts but, definitely more frequent if I attempt to install an extension. 

To be clear, are you deleting your .devcontainer.json, then reloading?

**Comment by rongxin-liu** [comment] 2022-04-02 17:04
> Thank you for the update. I was able to use my codespace for a couple of hours last night without the extension host failing. This was after stopping the codespace and restarting 3 times, then reloading the window twice. It seems to be somewhat random when it restarts but, definitely more frequent if I attempt to install an extension.
> 
> To be clear, are you deleting your .devcontainer.json, then reloading?

No, I just cleared everything in the `.devcontainer.json` and rebuilt my Codespace, which should effectively launch a Codespace using the default image, and no extra extensions would be installed. I'm doing this to see if I will get the same error in the default Codespace so I can isolate that the issue was not caused by CS50's and others' extensions.

**Comment by GigglePocket** [comment] 2022-04-02 18:38
Understood.  
I said reloading but, I meant rebuilding.
Good luck. I hope you're able to figure it out.
I only have access to codespaces through CS50 otherwise I'd've tried a non-CS50 integrated codespace to deduce the same.

**Comment by rongxin-liu** [comment] 2022-04-02 21:47
Here is the remote extension log that shows the extension host terminated unexpectedly within 5 minutes:

```
[2022-04-02 21:33:44.768] [exthost] [info] Extension host with pid 593 started
[2022-04-02 21:33:44.789] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Lock acquired.
[2022-04-02 21:33:44.873] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-04-02 21:33:45.067] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-04-02 21:33:45.077] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-04-02 21:33:45.091] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-04-02 21:33:45.133] [exthost] [info] ExtensionService#_doActivateExtension GitHub.codespaces, startup: true, activationEvent: '*'
[2022-04-02 21:33:45.868] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2022-04-02 21:33:46.302] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-04-02 21:33:46.522] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-04-02 21:33:49.448] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-04-02 21:33:51.196] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:33:51.253] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:33:51.270] [exthost] [info] Eager extensions activated
[2022-04-02 21:33:52.940] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 583
[2022-04-02 21:34:04.677] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1101
[2022-04-02 21:34:15.283] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare, startup: false, activationEvent: '*'
[2022-04-02 21:34:18.902] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onWalkthrough:jupyterWelcome'
[2022-04-02 21:34:19.883] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2022-04-02 21:34:19.917] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2022-04-02 21:34:27.830] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare-audio, startup: false, activationEvent: '*'
[2022-04-02 21:34:28.361] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'api', root cause: ms-python.python
[2022-04-02 21:35:45.873] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1101
[2022-04-02 21:36:08.997] [exthost] [info] Extension host with pid 3323 started
[2022-04-02 21:36:08.997] [exthost] [error] Error: EEXIST: file already exists, open '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock'
[2022-04-02 21:36:09.002] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Could not acquire lock, checking if the file is stale.
[2022-04-02 21:36:09.004] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': The pid 593 appears to be gone.
[2022-04-02 21:36:09.004] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Deleting a stale lock.
[2022-04-02 21:36:09.043] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Lock acquired.
[2022-04-02 21:36:09.150] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-04-02 21:36:09.231] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-04-02 21:36:09.288] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
[2022-04-02 21:36:09.295] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-04-02 21:36:09.306] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-04-02 21:36:09.334] [exthost] [info] ExtensionService#_doActivateExtension GitHub.codespaces, startup: true, activationEvent: '*'
[2022-04-02 21:36:09.870] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2022-04-02 21:36:10.105] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
[2022-04-02 21:36:10.197] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-04-02 21:36:11.709] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:13.120] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:36:13.140] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:36:13.144] [exthost] [info] Eager extensions activated
[2022-04-02 21:36:28.203] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:33.999] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:39.770] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:45.745] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:52.083] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:36:57.909] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:37:03.669] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:37:09.645] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1102
[2022-04-02 21:37:19.774] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:37:29.470] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:37:35.265] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:37:44.537] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:37:50.355] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:37:56.158] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:01.922] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:07.784] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:13.564] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:19.324] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:25.056] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:31.336] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:37.289] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:43.544] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:38:49.452] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:39:10.014] [exthost] [info] Extension host with pid 4627 started
[2022-04-02 21:39:10.015] [exthost] [error] Error: EEXIST: file already exists, open '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock'
[2022-04-02 21:39:10.015] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Could not acquire lock, checking if the file is stale.
[2022-04-02 21:39:10.017] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': The pid 3323 appears to be gone.
[2022-04-02 21:39:10.017] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Deleting a stale lock.
[2022-04-02 21:39:10.037] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/7e7a5198/vscode.lock': Lock acquired.
[2022-04-02 21:39:10.150] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-04-02 21:39:10.213] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-04-02 21:39:10.265] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
[2022-04-02 21:39:10.271] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-04-02 21:39:10.276] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-04-02 21:39:10.291] [exthost] [info] ExtensionService#_doActivateExtension GitHub.codespaces, startup: true, activationEvent: '*'
[2022-04-02 21:39:10.689] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: true, activationEvent: '*'
[2022-04-02 21:39:10.917] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
[2022-04-02 21:39:11.063] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-04-02 21:39:12.474] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:39:12.509] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:39:12.527] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-04-02 21:39:12.531] [exthost] [info] Eager extensions activated
[2022-04-02 21:39:39.973] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:39:49.772] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:39:59.722] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:05.476] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:12.614] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:18.511] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:24.431] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:30.888] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:36.831] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:43.216] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:40:57.203] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103
[2022-04-02 21:41:03.538] [exthost] [warning] [Decorations] CAPPING events from decorations provider vscode.git 1103

```

**Comment by dmalan** [comment] 2022-04-02 21:55
Afraid I keep seeing the same in Codespaces, @alexdima, fwiw:

https://gist.github.com/dmalan/bc11aa749a6faca4617e2191095ec5d7

The "terminated unexpectedly 3 times" seems to align with a process dying 3 times. E.g.:

```
[2022-04-02 20:36:46.449] [exthost] [error] Error: EEXIST: file already exists, open '/home/codespace/.vscode-remote/data/User/workspaceStorage/-19092080/vscode.lock'
[2022-04-02 20:36:46.449] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/-19092080/vscode.lock': Could not acquire lock, checking if the file is stale.
[2022-04-02 20:36:46.451] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/-19092080/vscode.lock': The pid 693 appears to be gone.
[2022-04-02 20:36:46.451] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/-19092080/vscode.lock': Deleting a stale lock.
[2022-04-02 20:36:46.473] [exthost] [info] Lock '/home/codespace/.vscode-remote/data/User/workspaceStorage/-19092080/vscode.lock': Lock acquired.
```

And the process in question might be (from a different log):

```
codespa+ 11007 41.6 32.7 2144092 1317232 ?     Rl   21:20   3:32 /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
codespa+ 11030  0.5  3.3 689896 135832 ?       Sl   21:20   0:02 /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=11007
codespa+ 12397  0.0  1.2 595504 50936 ?        Sl   21:23   0:00 /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=11007
```

Thanks!

CC @richakumar @garman @mrjf @nikmd23

**Comment by vegantom** [comment] 2022-04-03 11:02
I don’t know how helpful this is or is not but:
On the cs50 discord some people are reporting that this issue only persists either in browser, or in local vscode if they are connected there and in browser at the same time.

But if they are only connected in the local vscode software to their codespace and not through the browser at all they do not seem to be coming across this issue.

**Comment by GigglePocket** [comment] 2022-04-03 16:48
@[vegantom](https://github.com/vegantom) I can confirm one-half of this. I was trying to do my work exclusively in-browser and attempting to log the different activities I performed to perhaps get an idea of the cause, but moved to a local instance because the frequency of the restarts became prohibitive. No issue whatsoever in the local instance.

**Comment by alexdima** [comment] 2022-04-04 10:51
Thank you for all the information. I've looked through all the logs and the video. Some questions:

### 1. Does this reproduce with any repository?

It looks like this reproduces immediately and consistently for you. However, from your logs, it looks like you are all opening a workspace with 1000+ git changes. I wonder if there might be something specific about the workspace that would cause the crash. Does the extension host crash for you when creating a new codespaces for e.g. https://github.com/microsoft/vscode-textmate

### 2. Does this reproduce when switching to vscode insiders?

You can switch to VS Code Insiders on the web using the gear in the bottom left and then choosing Switch To Insiders Version.

### 3. Does this reproduce when disabling some builtin extensions?

From past issues, in 99% of cases, it was always one of the activated extensions that would cause crashes of the extension host process, either directly (e.g. using native node modules which would cause a segmentation fault), or indirectly (e.g. running into OOM, or calling APIs which would lead to an eventual crash), so I will try to focus on this direction.

Going through the crash logs and counting up extension frequency:

| Extension | Crashes present |
|---|---|
| vscode.microsoft-authentication          | 9 |
| vscode.debug-auto-launch                 | 9 |
| vscode.git-base                          | 9 |
| vscode.ipynb                             | 9 |
| GitHub.codespaces                        | 9 |
| GitHub.vscode-pull-request-github        | 9 |
| vscode.git                               | 9 |
| vscode.github                            | 9 |
| vscode.github-authentication             | 9 |
| vscode.emmet                             | 9 |
| vscode.merge-conflict                    | 9 |
| vscode.typescript-language-features      | 6 |
| vscode.html-language-features            | 6 |
| vscode.css-language-features             | 3 |
| vscode.configuration-editing             | 2 |
| vscode.json-language-features            | 2 |
| ms-vsliveshare.vsliveshare               | 2 |
| ms-vsliveshare.vsliveshare-audio         | 2 |
| vscode.extension-editing                 | 2 |
| vscode.markdown-language-features        | 2 |
| vsls-contrib.gitdoc                      | 1 |
| vscode.markdown-math                     | 1 |
| ms-toolsai.jupyter                       | 1 |
| ms-toolsai.jupyter-renderers             | 1 |
| ms-python.python                         | 1 |
| ms-python.vscode-pylance                 | 1 |

Could you please go to the extension viewlet and type `@builtin` (or use the filter icon). Then, could you please disable the following extensions. (Disable All if you get prompts about others depending on them):
* .ipynb support
* Emmet
* Git
* GitHub Pull Requests and Issues
* Merge Conflict
* Node Debug Auto-attach

This should reduce the number of extensions to a bare minimum. Do the crashes still occur? Could you share again the remote extension host logs and also the remote server logs?

**Comment by rongxin-liu** [comment] 2022-04-04 16:40
Thanks for following up! @alexdima

Those 1000+ git changes probably come from the virtual environments, which seemed to be created by Codespace when a container first launched using the default image on a repository with some python files.

The following tests are performed on a 2-core, 4GB Memory Codespace in the browser.

1. Could reproduce this issue by creating a Codespace from the vscode-textmate repository. Without doing anything, the extension host would terminate and auto-restart.

When running the top command, I can see that the CPU utilization for Extension Host is around 45% and continue allocating memory from the container until no more memory can be allocated and the extension host auto-restarted.

2. Could reproduce this issue in the insider version.

3. Disabling all built-in extensions could still reproduce this issue.

4. Not able to reproduce this issue when connecting to the same Codespace via VS Code desktop client.

**Comment by jkeech** [comment] 2022-04-04 16:50
Hi all, apologies for this issue. I think this is caused by a memory leak in the Codespaces web client that results in an out-of-memory situation where the extension host process ends up being killed by the OOM-killer. We are actively investigating and  working on rolling out a fix.

A temporary solution is to use the desktop client only and not connect via the web client.

**Comment by dmalan** [comment] 2022-04-04 18:15
Thank you, @jkeech, all, much appreciated!

**Comment by rongxin-liu** [comment] 2022-04-05 01:12
We can confirm that we are no longer experiencing this issue.

Thank you so much!! @jkeech @alexdima

**Comment by TylerLeonhardt** [comment] 2022-04-05 03:39
Closing this since it was related to a downstream change.

**Closed** 2022-04-05 03:39 UTC
Labels: needs more info, freeze-slow-crash-leak, github-codespaces

**Comment by RamiHadji** [comment] 2022-04-05 10:35
### Hello guys I'm having a problem with codespaces.

I tried many times to log in but the command prompt is not responding and I can't keep files in the cloud.
Can help?
![image](https://user-images.githubusercontent.com/43167480/161735736-01d5ea55-14fa-47f4-8cc6-481175e11303.png)
