### ISSUE TITLE
Update fails after an elevated update has been done before

### ISSUE THREAD

**Issue by OtherShadeOfBlue** [microsoft/vscode#149248] opened 2022-05-11 11:23 UTC
Issue Type: <b>Bug</b>

Today my vscode update failed stating a access failure on the 
AppData\\Local\\Programs\\Microsoft VS Code\\bin
folder.
After some investigations it turned out some files and folders there where owned by BUILTIN\Administrators
I usually make sure updating vscode from a non-elevated session, but recall last update I did was accidentally done elevated.

I was able to fix it by taking ownership of all files/folders in AppData\\Local\\Programs\\Microsoft VS Code

I am running win11 insider build 10.0.22616.100 and seem to recall having done similar elevated updates on earlier win10/win11 builds without issues. So not sure if it is win11-insider or vscode related just yet.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22616
Restricted Mode: No

**Comment by gjsjohnmurray** [comment] 2022-05-11 16:02
Related - #148428

**Comment by joaomoreno** [comment] 2022-05-20 13:26
Duplicate of https://github.com/microsoft/vscode/issues/147408

**Closed by joaomoreno** 2022-05-20 13:26 UTC
