### ISSUE TITLE
permission access to change on remote wsl

### ISSUE THREAD

**Issue by apptonet** [microsoft/vscode#154133] opened 2022-07-05 05:50 UTC
Failed to save 'php.ini': Unable to write file 'vscode-remote://wsl+ubuntu-22.04/etc/php/8.1/apache2/php.ini' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/php/8.1/apache2/php.ini')
https://snipboard.io/re56jq.jpg

**Comment by aeschli** [comment] 2022-07-12 09:05
duplicate of https://github.com/microsoft/vscode/issues/48659

**Closed by aeschli** 2022-07-12 09:05 UTC
