### ISSUE TITLE
Git - Staging selected ranges does not modify file but create a new one

### ISSUE THREAD

**Issue by mcicat** [microsoft/vscode#129093] opened 2021-07-21 08:27 UTC
When I open the VSCode from my git bash using the "git difftool" command and stage selected ranges, new file is created instead of modifying the old one. At least two changes must be in the modified file. 

My git configuration: 
[difftool "default-difftool"]
    cmd = code --wait --diff $LOCAL $REMOTE
[merge]
	tool = vscode
[mergetool "vscode"]
    cmd = code --wait $MERGED

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open git bash in the repository with changes. Changes must be in a file placed in a subfolder of the repository (~/repository/Test/edited_file.c)
2. Use git difftool 
3. When vscode is displayed stage one of the changes using the "Stage selected Ranges'
4. The file "splits" and in the staging area occurs a file without a subfolder (edited_file.c)

![image_2021-07-21_102518](https://user-images.githubusercontent.com/45569599/126456749-ee334df1-121f-4cb8-8ac1-ac34df41c135.png)

**Comment by mcicat** [comment] 2021-08-20 17:09
No answer?

**Comment by jehillert** [comment] 2021-08-21 05:38
I am having the same problem on MacOS, VS Code Version 1.59.1.  I don't think shell or method VS Code is opened, because I open vs code from the code-workspace file (and I use zsh, not bash).  The problem occurs when the command is called, whether that's by context menu or "show all commands" via hotkey.

Also, the file created is a concatenation of the individual ranges staged, and the same ranges can be added over and over.  In the picture below, I staged:
3 lines
3 lines
1 line
3 lines
3 lines
3 lines
1 line
1 line
1 line
![(2021-08-21) XSnip_003644](https://user-images.githubusercontent.com/25601296/130311779-60ff0e0f-4b1e-4cb9-8f4d-919daa7826f5.png)

Last observation is obvious.  Only additions are concatenated.  Deletions are ignored.

**Comment by lszomoru** [comment] 2024-12-18 11:29
Sorry for not getting back to you on this. We have recently pushed some fixes to the "* selected ranges" commands so I would like to ask you to try out the latest VS Code Insiders release (version information below). I will go ahead and optimistically close this issue. Please feel free to reopen it in case you are still able to reproduce the problem. Thank you!

```
Version: 1.97.0-insider
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```

**Closed by lszomoru** 2024-12-18 11:29 UTC
Labels: bug, git
