### ISSUE TITLE
.env file is being recognized as a Python file instead of an Environment file even after manually setting it

### ISSUE THREAD

**Issue by brunolm** [microsoft/vscode#132001] opened 2021-08-31 18:48 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0-insider (user setup)
Commit: 44a4b19a910a287adef4daaeabcf68f2ba893c35
Date: 2021-08-30T11:37:20.484Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open an `.env` file
2. Notice at the bottom right the detected language is Python

It seems to change to `Plain text` if I remove some of the comments. Depending on the file contents it also says it's `Shell Script`.

I want to force `.env` to always be `Envrionment file` instead.

**Comment by TylerLeonhardt** [comment] 2021-09-03 22:19
Duplicate of #132173 this should be fixed in the next recovery build next week.

**Closed by TylerLeonhardt** 2021-09-03 22:19 UTC
Labels: bug, languages-guessing
