### ISSUE TITLE
Terminal "Copy/Paste" issues

### ISSUE THREAD

**Issue by hawkeye64** [Microsoft/vscode#42247] opened 2018-01-27 14:59 UTC
- VSCode Version: Version 1.19.2
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. In a terminal, have some output that exceeds the window
2. Right click for context-menu and select "Select All"
3. Right-click again and select "Copy"
4. In a text editor, paste the results
5. The only text that gets copied is what is currently visible in the terminal window

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-01-27 23:07
I can't reproduce, is it happening 100% of the time for you? Does it behave the same when using select all via command palette (F1) or ctrl+shift+c to copy?

**Comment by hawkeye64** [comment] 2018-01-28 13:13
I just updated to 1.19.3 and the issue no longer appears in this version.

What would be nice in the integrated terminal is to have Ctrl-A with the Select All, like it is for the editor areas of Code.

**Comment by Tyriar** [comment] 2018-01-28 19:02
@hawkeye64 yeah not making ctrl+a select all is a tough call. Unfortunately ctrl+a is a very common keybinding for terminal applications so we need to decide whether to send it to the shell or to handle it before it gets there. Forcing ctrl+a to select all would break a lot of terminal users.

Luckily there's an easy workaround, add this to your keybindings.json file:

```js
{ "key": "ctrl+a", "command": "workbench.action.terminal.selectAll", "when": "terminalFocus" }
```

**Comment by hawkeye64** [comment] 2018-01-31 14:40
Thanks!

**Comment by hawkeye64** [comment] 2018-02-01 19:13
Opening this again as I have a bit more information.
While the v1.19.3 fixed the Select All issue, I can still recreate with similar results.

If you have more data in the terminal than can be selected via the mouse, select an anchor point with the mouse (or multiple lines), then scroll the terminal down to the end. While holding Shift, to drop a closing anchor. Right-click, select "Copy", paste your contents into a text editor. All that pastes is what you see selected in the visible portion of the terminal window.

**Comment by hawkeye64** [comment] 2018-02-01 19:13
My work-around, right now, is to Select All, then paste, then edit out what I don't want.

**Comment by Tyriar** [comment] 2018-02-01 19:34
@hawkeye64 I'm a little lost at the holding shift to drop closing anchor bit, do you mean you drag down to the bottom (mouse over the status bar), bring it back into the terminal and hit shift+click somewhere?

**Comment by hawkeye64** [comment] 2018-02-01 19:41
It's because the terminal won't scroll with the mouse when you are holding the shift key. You have to start an anchor (click) then drop a closing anchor (shift-click). This is common in most editors. 
When you do this, it appear the start anchor moves to the top of the visible area (after scrolling) in the terminal, instead of where you placed it.

**Comment by hawkeye64** [comment] 2018-02-01 19:43
Also, you can do the click and then shift-click in a linux terminal. Under windows, it's a bit different.

**Comment by Tyriar** [comment] 2018-02-01 23:25
> It's because the terminal won't scroll with the mouse when you are holding the shift key.

It works fine for me on mac and Ubuntu?

> You have to start an anchor (click) then drop a closing anchor (shift-click).

@hawkeye64 clicking will always drop the selection, if you want a multiple page selection you can make a selection by clicking, dragging down multiple pages and then letting go of the mouse button. To fine tune it at that point you would need to hold shift and click which will set the end position of the selection.

**Comment by hawkeye64** [comment] 2018-02-03 17:43
Of course I tried that. The terminal window doesn't scroll. At least in my case. Ubuntu 17.10

**Comment by hawkeye64** [comment] 2018-02-03 20:13
Ok, there is something weird happening here. I tried the mouse cursor and it scrolled (new for me), I right-clicked and clicked copy, then opened gedit, right-clicked, the paste was available, selected that and nothing pasted. I tried in Code again, switched over to gedit, pasted, and nothing. :(

**Closed** 2018-06-21 21:53 UTC
Labels: *not-reproducible, integrated-terminal, needs more info
