### ISSUE TITLE
Allow problemMatcher of a task to have multiple relative file location search paths.

### ISSUE THREAD

**Issue by cyliang** [microsoft/vscode#82829] opened 2019-10-18 09:34 UTC
In some build systems, source code files are built under different working directories, so the paths are not relative to same base path. For example, if this build system does this:
```
cd ${workspaceFolder}/path1
g++ a.cxx
g++ b.cxx

cd ${workspaceFolder}/path2
g++ c.cxx
g++ d.cxx
```

It's impossible to find all problematic files reported from the build task through only one base path.

Can we have a syntax like this:
```
"problemMatcher": {
    "base": "$gcc",
    "fileLocation": ["relative", "${workspaceFolder}/path1", "${workspaceFolder}/path2"]
}
```
So VSCode can search all possible files under both `${workspaceFolder}/path1` and `${workspaceFolder}/path2`?

Thank you.

**Comment by sohailrajdev97** [comment] 2019-10-21 09:10
@alexr00. I would like to take this up. Any leads for adding this would be appreciated.

**Comment by alexr00** [comment] 2019-10-21 09:42
@sohailrajdev97 I would start by looking at all the references to `FileLocationKind.Relative` in the code base and seeing where things will need to be changed around there.

I think that the problem matcher `filePrefix` will need to be changed to be a `string[]`. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L135

`getResource` in problemMatcher.ts will probably need to try to resolve the file path when more than one relative path is provided, then only return the URI of the path that resolves successfully. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L190

Note that these are just initial thoughts on how to implement this feature. If you make a PR there might be significant changes to it since I've only thought about this for a few minutes.

**Comment by sohailrajdev97** [comment] 2019-10-22 09:44
@alexr00 What behaviour can be the expected behaviour when more than one URI is resolved successfully (when we have the same filename in different directories) ?

**Comment by alexr00** [comment] 2019-10-22 14:33
@cyliang how likely is [this](https://github.com/microsoft/vscode/issues/82829#issuecomment-544884180) to happen in your use case?

@sohailrajdev97 My initial inclination is to just pick the first one that matches. But I'm not sure about how often multiple matches could happen. If it's going to happen often then we would need a larger code change to support it. I think in this case I would not want to support the feature right now.

**Comment by sohailrajdev97** [comment] 2019-10-22 16:05
@alexr00 As the number of resolvable paths may vary from one use case to another, I don’t think it’s a good idea to add this feature right now. Resolving the link to a wrong file is as bad as (or even worse than) not resolving it at all.

**Comment by Razzeee** [comment] 2019-10-24 14:19
I have two folders in my dotnet project:
- src
- test

```
"problemMatcher": {
        "base": "$msCompile",
        "fileLocation": ["relative", "${workspaceFolder}/src/"]
      }
```

`ServiceTests\MyServiceTest.cs(503,10): warning SA1513: Closing brace must be followed by blank line [C:\development\project\test\Project.Test.csproj]`

So this will never work like it is.

I would expect the problemMatcher to create a `cwd` from my absolute project path `C:\development\project\test\` and handle everything else relative to that. Obviously still depending on how task.json is setup, but that should be possible for some languages at least?

**Comment by cyliang** [comment] 2019-10-25 04:40
@alexr00 @sohailrajdev97 

[This](https://github.com/microsoft/vscode/issues/82829#issuecomment-544884180) will not happen in my use case.

> My initial inclination is to just pick the first one that matches.

This is also how I think about this feature, and I think it is not that important to take care of multiple matches. Picking the first match is already a great feature.

I don't understand why resolving to a wrong file is worse than resolving to nothing. When picking the first match resolves to a wrong file, there is no chance the original usage can resolve to a correct file.

Thank you.

**Closed** 2020-03-16 00:53 UTC
Labels: feature-request, tasks
