### ISSUE TITLE
Allow to change the font of the workbench

### ISSUE THREAD

**Issue by williamsandstrom** [Microsoft/vscode#32217] opened 2017-08-10 07:21 UTC
- VSCode Version: 1.14.2
- OS Version: Debian 9

Recently rebuilt my dev machine and installed VS Code. Did not have droid sans mono at first, so the text in the editor looked bad, finally fixed it to look like it should again. 

The issue now is that all other elements are not using "Droid Sans Mono" or any other monospaced font.

![First](https://i.imgur.com/KMRSlZJ.png)
Check the tab text at top and bottom.

![Second](https://i.imgur.com/uNy0PiE.png)
Same here.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-11-03 19:47
Duplicate of #519

**Closed by mjbvz** 2017-11-03 19:47 UTC
Labels: duplicate, feature-request, workbench
