### ISSUE TITLE
File > New > Project

### ISSUE THREAD

**Issue by sys4soft** [microsoft/vscode#113765] opened 2021-01-04 16:23 UTC
This, I think, is a simple feature request. The editor already contains a File>New file and File>New Window. Why not a File > New Project?

I know that most of the times projects are created in the terminal with composer, npm, react cli, etc. In my case, everytime I want to create a simple folder for a pure PHP project, I have to select File > Open folder, create the folder and then select it.

This feature could also include in the dialogbox some pre-build structures or automations for the most common projects:
> Empty Folder
> Vue Project
> React Project
> etc.
(lunching the terminal, if the case, with the proper commands to create the project)

Thanks.

**Comment by RMacfarlane** [comment] 2021-01-04 18:06
Duplicate of https://github.com/microsoft/vscode/issues/74014

**Closed by RMacfarlane** 2021-01-04 18:07 UTC
