### ISSUE TITLE
Clicking on "Install" button of an already installed extension doesn't open extension tab

### ISSUE THREAD

**Issue by vfonic** [Microsoft/vscode#40848] opened 2017-12-26 22:55 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.2.0
bracket-pair-colorizer|Coe|0.10.14
html-css-class-completion|Zig|1.14.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
auto-rename-tag|for|0.0.15
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
vscode-versionlens|pfl|0.19.1
vscode-import-cost|wix|2.6.0

---

Steps to Reproduce:

1. Install _any_ VSCode extension. (Example: [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf))
2. Go to the installed extension's marketplace url: https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf
3. Click on "Install" button

Expected:
VSCode opens "Extension" tab and loads the extension page.

Actual:
VSCode app gains focus, but nothing else happens (no tabs open).

This is confusing, especially if you have many extensions and are unsure whether you already have an extension installed.

Also there's another poor UI: If I don't have extension installed, and I install it, but not by clicking on the "Instal"/"Cancel" new top bar "notification", but from the button inside the newly open "Extension" tab, the top bar notification doesn't get updated/dismissed. The state of extension (installed/not installed) is not propagated/synced globally)

Reproduces without extensions: Yes

**Comment by mikaoelitiana** [comment] 2018-01-10 16:21
This one is not easy to reproduce on dev vscode because clicking the install button will launch the stable installed vscode instead of the one I launch from build.  Any workaround for that?

**Comment by JacksonKearl** [comment] 2018-01-10 21:06
@mikaoelitiana if you change the first part of the URL from the extension install link from `vscode` to `code-oss` it should open up the dev version. 

e.g. 
`vscode:extension/mikaoelitiana.vscode-mpanjifa-votabia` becomes 
`code-oss:extension/mikaoelitiana.vscode-mpanjifa-votabia`

You'll need to have `./scripts/code.sh` running in the background somewhere already for this to work.

**Comment by mikaoelitiana** [comment] 2018-01-11 10:49
Thank you @JacksonKearl I will try that

**Comment by mikaoelitiana** [comment] 2018-01-11 11:03
I am trying it on windows but it would not open in Code OSS. I change the link and it ask me to open it in Code OSS but after that I have an error. 

![sc1](https://user-images.githubusercontent.com/674667/34822479-5da534f8-f6c7-11e7-85a7-46f5de7de374.jpg)

**Comment by JacksonKearl** [comment] 2018-01-11 15:44
Ah bummer. Maybe it’s only on macOS. And you definitely had the yarn watch and code.bat scripts going?

**Comment by mikaoelitiana** [comment] 2018-01-11 15:46
Yes I did start it already. I will check this later on macOS then.

**Comment by joaomoreno** [comment] 2018-02-09 16:37
Fixed by https://github.com/Microsoft/vscode/pull/42071

**Closed by joaomoreno** 2018-02-09 16:37 UTC
Labels: bug, extensions, good first issue, help wanted
