### ISSUE TITLE
Visual Studio Code error

### ISSUE THREAD

**Issue by Sauron2009** [microsoft/vscode#116887] opened 2021-02-17 22:58 UTC
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: Bug

On Sunday, 02/14/2021. I opened Visual studio code but, it was a black screen on the index.html page from the project I was working on the previous night before closing VS Code. So after trying to uninstall and reinstall Vs Code and opening another project that I opened on VS Code before, I was able to get out of the black screen. I had to open all of my projects on by one on VS Code.
Today when I opened VS Code it said that I don't have any folders opened but, the previous night I was working on a project and I had a folder opened. What should I do?

![image](https://user-images.githubusercontent.com/78165914/108278854-8776a280-7130-11eb-8c0d-79590e8021a3.png)

**Comment by gjsjohnmurray** [comment] 2021-02-17 23:15
/duplicate of #116862

@Sauron2009 please do not open duplicate issues in the hope of getting a faster response. Doing so is unlikely to endear you to those who may be prepared to assist you.

**Closed** 2021-02-17 23:16 UTC
Labels: *duplicate
