### ISSUE TITLE
 Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#41082] opened 2018-01-03 10:12 UTC
Issue Id: <b>c5e3de01-7450-9f6c-794c-486b6248b1a7</b><br /><br />*Versions* <br />- 1.19.1<br />-  816be6780ca8bd0ab80314e11478c48c70d09383<br />-  8598659abef5b83e0854c4a12fbd79cf5817b6ad<br />-  951f5a20fc820e32a65ca05bb87af86f65027470<br />-  d8989c95964ce06c64ffebc2fb400a0327bd447d<br />-  bc206bbacc13e48d4422b8c73334aa9dd6f782df<br />*Stack* <br />TypeError: Cannot read property 'on' of undefined<br />[/vs/workbench/services/search/node/fileSearch.ts#L417:9 (on)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L417:9 (on))<br />[/vs/workbench/services/search/node/fileSearch.ts#L391:7 (forwardData)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L391:7 (forwardData))<br />[/vs/workbench/services/search/node/fileSearch.ts#L235:7 (collectStdout)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L235:7 (collectStdout))<br />[/vs/workbench/services/search/node/fileSearch.ts#L202:7 (apply)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L202:7 (apply))<br />[/vs/workbench/services/search/node/fileSearch.ts#L183:9 (call)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L183:9 (call))<br />[/vs/base/node/flow.ts#L25:2 (fn)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/node/flow.ts#L25:2 (fn))<br />    at Array.forEach (native)<br />[/vs/base/node/flow.ts#L24:6 (forEach)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/node/flow.ts#L24:6 (forEach))<br />[/vs/workbench/services/search/node/fileSearch.ts#L182:8 (parallel)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L182:8 (parallel))<br />[/vs/workbench/services/search/node/fileSearch.ts#L554:10 (clb)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/search/node/fileSearch.ts#L554:10 (clb))<br />

**Comment by roblourens** [comment] 2018-01-03 19:11
/duplicate of https://github.com/Microsoft/vscode/issues/38195

**Closed by roblourens** 2018-01-03 19:11 UTC
Labels: search
