### ISSUE TITLE
[VS Code 1.8][Breaking change] contentChanges of TextDocumentChangeEvent returns wrong text

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#17444] opened 2016-12-17 02:57 UTC
- VSCode Version: 1.8.0
- OS Version: All OS

Several Auto Close Tag users [complain](https://github.com/formulahendry/vscode-auto-close-tag/issues/19) about the extension not working after they upgrade to VS Code 1.8

Steps to Reproduce:

1. Install [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag)
2. Open a html file, and type a open tag, e.g. `<div>`

Expected: A close tag `</div>` is appended
Actual: Nothing happens

After investigation, this issue only happens in a html file and the contentChanges of TextDocumentChangeEvent returns wrong text in https://github.com/formulahendry/vscode-auto-close-tag/blob/master/src/extension.ts#L21
When you type `>` after `<div`, it should return `>`, while it return the text of whole line: `<div>`

Since a lot of users are using this function and the impact for user is big, I am wondering if we have any other workaround to use this API, or could we fix this in 1.8.1?

**Comment by alexandrudima** [comment] 2016-12-19 11:35
@formulahendry The `TextDocumentChangeEvent` also contains a `range` property, which you could take into account in your logic. I am not sure why this has changed from 1.7.0 to 1.8.0, but the `TextDocumentChangeEvent` is correct. e.g.:

* when having a file with the contents
```
<div
```
* and typing `>`
* this is the text document change event being sent:
```
{
  "document": ...,
  "contentChanges":[{
    "range":[{"line":0,"character":0},{"line":0,"character":4}],
    "rangeLength":4,
    "text":"<div>"
  }]
}
```

This event is correct, it allows someone to correctly keep a sync`ed version of the text document. (i.e. the purpose of `TextDocumentChangeEvent` is fulfilled).

That the change now effectively says `"replace <div with <div>"` instead of `"insert > after <div"` is rooted in how the edits reach the buffer, however the `TextDocumentChangeEvent` is correct.

AFAIK there is no API contract on the shape and semantics of `TextDocumentChangeEvent` as long as it allows to maintain a correct replica of the text document. i.e. there are cases where in the core buffer logic edits are simplified for memory saving purposes. e.g. try a replace all in a file where there are 100 matches, there will come 100 `contentChanges`, try a replace all in a file where there are 10000 matches, there will come a single entry in `contentChanges`.

**Comment by formulahendry** [comment] 2016-12-19 12:16
That seems not acceptable, since
* Scenario#1 in a html file
Type `<di`, then type `v`, contentChanges return `v`, then type `>`, contentChanges return `<div>`
When typing `v`, why it returns `v` not `<div`?

* Scenario#2 in a html file
Type `<di`, then type `v`, contentChanges return `v`, then type `1`, contentChanges return `1`
When typing `1`, why it return `1` not `<div1`?

* Scenario#3 in a file which is not html
Type `<di`, then type `v`, contentChanges return `v`, then type `>`, contentChanges return `>`
When typing `>`, why it returns `>` not `<div>`?

**Comment by formulahendry** [comment] 2016-12-22 08:32
Moreover, with below info, it is hard for developer to distinguish whether user is just typing a `>` after `<div` or user is copying and pasting a `<div>`
```json
{
  "contentChanges":[{
    "range":[{"line":0,"character":0},{"line":0,"character":4}],
    "rangeLength":4,
    "text":"<div>"
  }]
}
```

**Comment by rebornix** [comment] 2016-12-30 23:36
Share my understanding of what happens under the hood. When you type any closing electric character, we'll do following steps:

Firstly, check whether there is any **complex** auto close pair for this particular language. If so, append the character and the closing text in the pair and put the cursor just after the closing electric character.

Take below language definition as example

```
"autoClosingPairs": [
	{ "open": "{", "close": "}"},
	{ "open": "[", "close": "]"},
	{ "open": "(", "close": ")" },
	{ "open": "'", "close": "'" },
	{ "open": "\"", "close": "\"" },
	{ "open": "<div>", "close": "</div>" }
]
``` 

The last pair is the so called **complex** auto close pair. If you type `>` after `<div`, and since there is a matched complex pair, we'll end up with (`|` is the cursor)

```
<div>|</div>
```

so the corresponding content change is 

```
{
    "range":[{"line":0,"character":4},{"line":0,"character":4}],
    "rangeLength":0,
    "text":"></div>"}
}
```

However we don't have such definitions in HTML's language configuration file. I think it's easy to see why.

Secondly, if there is no matched complex auto close pair, we'll check against those simple ones. With above language configuration in mind, you'll know that `>` is matched with `<` so append `>` to the end of the text and run **auto indentation**.

For example, if you have `tabSize` set as `4` and `insertSpaces` as `false`, and the text in current line you are editing is `    <div` (starts with four spaces). After you press `>`,  the text of current line will become `\t<div>`.

In this case, the content change will be 

```
{
    "range":[{"line":0,"character":0},{"line":0,"character":8}],
    "rangeLength":8,
    "text":"\t<div>"
}
```

Thirdly, if there is still no matched pair for the character, we'll just insert the text user typed.

Our second step right now is what blocks your extension, I think @alexandrudima knows more about why we do auto indentation there. I agree this piece can be somehow improved, let's say there is no real indentation change, just insert the text instead of running a replacement.

But they are not the root cause of the problem you run into, I'll describe it in following comment.

**Comment by rebornix** [comment] 2016-12-30 23:47
The real problem is you can not use `TextDocumentChangeEvent ` to determine whether users type a character or not. The reason is the `contentChange` is the combined result of Code's internal logic and any extension that takes effect. Below are some cases that might break your extension with current design

* There is a `decreaseIndentPattern` rule for a language, and when users press `enter`, the `decreaseIndentPattern` matches the content of current line. So the `contentChange` of this component is decreasing the indentation and inserting a line break at the end of line. You don't know if users just press the `enter` key.
* A user installs Vim extension and map `>` key to `[">", "o"]` as he/she wants to close the tag and move cursor to next line. As Vim takes over `type` event, the only thing Code knows is the real content change, `>\t`, and then we pass it through extension host. You might think users type `>` and `\t` but actually they only press `>` key.

Above two examples might be invalid but I just want to demonstrate that if you rely on `contentChange` to determine what users type into the editor, the behavior of your extension might be affected by any extension users install.

**Comment by formulahendry** [comment] 2016-12-31 06:50
Thanks @rebornix for the detailed info!

`\t<div>` in second step is acceptable. However, the weird thing is that when you type `abcde<div` then type `>`, content change returns `abcde<div>`, the whole line, seems not related to auto indentation.

I really meet with other extensions affect each other not just in this TextDocumentChangeEvent. For every extension, there seems no better way to avoid the impact from other extensions. This is a general problem for every extension. Therefore, I just want to make sure the extensions is working correctly on a clean VS Code without other extensions. User may have trade-off between the extensions if they are affected by other extensions.

**Closed** 2017-01-24 15:41 UTC
Labels: bug
