### ISSUE TITLE
wrong syntax highlighting for multiline shell strings in markdown code snippets

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#201524] opened 2023-12-26 23:18 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.1
- OS Version: macOS Ventura

Steps to Reproduce:

1. Edit the following Markdown file in VSCode: [example.md](https://github.com/microsoft/vscode/files/13774073/example.md).
2. Render a preview tab.

Screenshot:

<img width="556" alt="screenshot" src="https://github.com/microsoft/vscode/assets/5316/99ece083-a353-42f9-abfb-d9c9877efab2">

The string highlighting for that first `TASK_NAMES` declaration multiline string block appears wonky. Everything from the opening dollar parenthesis for a subprocess (`$(`) up to the awk statement delimiting semicolon (`;`) is white.

Suspect some underlying linguist sh parser is faulty. It may not be adhering to the POSIX sh language spec.

**Comment by RedCMD** [comment] 2023-12-27 03:50
interestingly the code syntax highlighting works correctly
```sh
TASK_NAMES="$(
    awk '/^[a-zA-Z0-9_]+\(\)/ {
        split($0, a, /\(\)/);
        print a[1]
    }' "$0" |
        sort
)"

help() {
    echo 'Usage: ./build [<task> [<task> [<task>...]]]

Tasks:
'

    for TASK in $TASK_NAMES; do
        echo "* $TASK"
    done
}
```
![image](https://github.com/microsoft/vscode/assets/33529441/86435a47-7d46-45f2-bfac-5bd930e48d44)
its only the preview thats broken

**Comment by mjbvz** [comment] 2024-02-08 01:07
Duplicate of #91279

**Closed by mjbvz** 2024-02-08 01:07 UTC
