### ISSUE TITLE
Allow extension to match a specialized file with an existing extension match

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/vscode#10915] opened 2016-08-24 21:01 UTC
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10

I'm trying to create a language extension for [ecmarkup](https://github.com/bterlson/ecmarkup), which uses the `.html` file extension. I don't want my language to completely override the existing HTML syntax, just ones with a `<!doctype ecmarkup>` first line. 

However, https://github.com/Microsoft/vscode/issues/2883, plus the general way languages are matched makes this impossible. If I add `".html"` to the `"extensions"` entry for my language, I end up overriding all HTML files, but if I only add a `"firstLine"` match for something like `"^<!doctype\\s+ecmarkup\\b"`, the HTML syntax is used instead.

What I feel I really need is a more specific set of file matching rules, something like:

``` json
{
  "id": "ecmarkup",
  "aliases": ["ecmarkup", "emu"],
  "rules": [
    { "extensions": [".html"], "firstLine": "^<!(doctype|DOCTYPE)\\s+ecmarkup\b" }
  ],
  "configuration": "./ecmarkup.configuration.json"
}
```
## Proposal

With more specific rules, I can specify multiple requirements for a specific match, where precedence is based on the combined weight of each of the requirements.

Effectively, each of the `"filenames"`, `"filenamePatterns"`, `"mimeTypes"`, `"extensions"`, and `"firstLine"` patterns would internally be transposed into the `"rules"` collection as:

``` json
{
  "rules": [
    { "filenames": [] },
    { "filenamePatterns": [] },
    { "mimeTypes": [] },
    { "extensions": [] },
    { "firstLine": "" }
  ]
}
```

The following is an example of the proposed interface for these rules (borrowed from the types defined in [modeService.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/modeService.ts)):

``` ts
export interface ILanguageServiceExtensionPoint {
    id: string;
    extensions?: string[];
    filenames?: string[];
    filenamePatterns?: string[];
    firstLine?: string;
    aliases?: string[];
    mimetypes?: string[];
    configuration?: string;
    rules?: ILanguageServiceExtensionPointRule[];
}
export interface ILanguageServiceExtensionPointRule {
    filenames?: string[];
    filenamePatterns?: string[];
    extensions?: string[];
    firstLine?: string;
    ignore?: boolean; // If this rule is matched, *do not* use this extension
}
export interface IValidLanguageExtensionPoint {
    id: string;
    aliases: string[];
    mimetypes: string[];
    configuration: string;
    rules: IVerifiedLanguageServiceExtensionPointRule[];
}
export interface IVerifiedLanguageServiceExtensionPointRule {
    filenames: string[];
    filenamePatterns: string[];
    extensions: string[];
    firstLine: string;
    ignore: boolean; // If this rule is matched, *do not* use this extension
}
```

The approximate weights for each match would be something like:

``` ts
const enum TextMimeAssociationWeights {
  UserConfiguredMime = 1 << 4, // highest priority
  Filenames = 1 << 3,
  FilenamePatterns = 1 << 2,
  Extensions = 1 << 1,
  FirstLine = 1 << 0, // lowest priority
}
```

Given how first-line matches are treated in [mime.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts), a user-configured rule that contains only `"firstLine"` would not have the `UserConfiguredMime` flag added.

The following illustrates this weighting scheme:

| User | Rule | Weight |
| --- | --- | --: |
| yes | `{ "extensions": [".html"], "firstLine": "^<!doctype custom" }` | 21 |
| no | `{ "extensions": [".html"] }` | 2 |
| yes | `{ "firstLine": "^#!/usr/bin/env node" }` | 1 |

**Comment by bpasero** [comment] 2016-08-25 12:30
Fair request, this is an area where we do not support this nicely. I think we new about this corner case when we fixed all the other issues in this area.

**Comment by bpasero** [comment] 2016-10-18 05:06
@dbaeumer @alexandrudima do you remember why we decided to use the `firstline` as lowest indicator for a language (see https://github.com/Microsoft/vscode/blob/ben/horizontal/src/vs/base/common/mime.ts#L131)?

Somehow I feel that `firstline` is a much stronger indicator compared to the file extension.  However, changing this now might break other extensions badly...

**Comment by dbaeumer** [comment] 2016-10-25 11:08
@bpasero I only know that it has something to do with Flow and files without extensions. But I can't recall the whole story either.

**Comment by alexandrudima** [comment] 2016-10-25 15:08
I also remember something to do with Flow

**Comment by alexandrudima** [comment] 2016-10-25 15:43
On a first search of `firstLine` in our code base I can see that `xml` would win over `html` for html files starting with `<!doctype`

**Comment by PranayAgarwal** [comment] 2017-01-09 19:47
👋  Any chance this could be picked up this/next iteration? It's blocking an entire category of extensions.

**Comment by bpasero** [comment] 2017-03-23 01:06
@PranayAgarwal thanks for the headsup today at Slack, I can revisit this and investigate, but cannot make promises about time because I will be out next week too.

**Comment by PranayAgarwal** [comment] 2017-11-20 21:34
This can be closed now, I think? VS Code started successfully recognizing `.php` files as Hack without any overrides after a recent update.

**Comment by bpasero** [comment] 2019-04-25 10:07
Duplicate of https://github.com/Microsoft/vscode/issues/53350

**Closed by bpasero** 2019-04-25 10:07 UTC
Labels: api, extensions, feature-request
