### ISSUE TITLE
Terminal window doesn't have a scrollbar

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#8644] opened 2016-07-01 20:34 UTC
- VSCode Version:1.21
- OS Version:Windows 10

Steps to Reproduce:

1. Open integrated terminal
2. Type enough to make it scroll

**Comment by Tyriar** [comment] 2016-07-02 11:08
Duplicate of https://github.com/Microsoft/vscode/issues/6602

**Closed by Tyriar** 2016-07-02 11:08 UTC
Labels: bug, integrated-terminal
