### ISSUE TITLE
AutoIndent clears autocompletion buffer, 'end' becomes 'def' in Ruby

### ISSUE THREAD

**Issue by iccub** [Microsoft/vscode#29210] opened 2017-06-21 19:45 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:07:22.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Ruby|reb|0.12.1

---

GIF for better explanation:

![out](https://user-images.githubusercontent.com/6950387/27402443-f05e8624-56c6-11e7-8b7f-7e162d645ace.gif)

Steps to Reproduce:

1. In .rb file, type something to trigger indentation with 'end' keyword(like class or method)

After 'end' keyword is finished, indentation happens and suddenly autocompletion changes from 'end' to 'def' or other suggestion. Then, pressing enter makes 'endef', if you want to leave 'end' you need to press esc, which isn't too ergonomic.
When cursor is on proper indentation though, 'end' autocomplete seem to work just fine
Other keywords like 'else', 'rescue' behave properly

This bug didn't occur in vscode 1.13.1.
Related issue: #2272

**Comment by rebornix** [comment] 2017-06-21 23:09
@iccub did you run into this issue still if you run without any extension? `code-insiders --disable-extensions`

**Comment by iccub** [comment] 2017-06-22 09:24
Sorry for late reply, I'm in eu timezone

It's the same without extensions too, I reinstalled clean version to be sure

**Comment by joelbandi** [comment] 2017-08-28 18:52
I have the same issue in `Version 1.15.1 (1.15.1)` as well.
`end` automatically becomes `endef` and its really dragging me down 😢

**Comment by iamoni** [comment] 2017-09-28 21:37
very annoying little issue. still going on.

**Comment by chdezmar** [comment] 2017-11-30 13:17
Still going on for 1.18.1. Any quick fix?

**Comment by jeremykay** [comment] 2017-12-08 16:14
Would also love to see a fix for this.

**Comment by jrieken** [comment] 2017-12-11 08:55
Someone: Please provide a code sample and steps that reproduce this

![dec-11-2017 09-54-25](https://user-images.githubusercontent.com/1794099/33822834-468bdd34-de59-11e7-9f99-6abc0b28bdd3.gif)

**Comment by chdezmar** [comment] 2017-12-11 09:16
![endef_vscode](https://user-images.githubusercontent.com/18425314/33823680-3b5a5096-de5c-11e7-9e39-b2d88dbc6b27.gif)
Pressing ENTER after end adds `endef` instead of new line.

**Comment by jrieken** [comment] 2017-12-11 09:39
not for me...

**Comment by chdezmar** [comment] 2017-12-11 09:43
I am working on a rails project, is that behavior probably coming from that context?

**Comment by jrieken** [comment] 2017-12-11 10:01
How would I be able to tell from an animated gif?

**Comment by jrieken** [comment] 2017-12-11 11:36
> just providing more info.

To be honest, you are saying I see this too and you are attaching a similar animated gif. Yes, that's more info but doesn't help me because I still not reproduce this. Please follow this guide: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests, esp. the section of reproducible steps and the code snippet. 

Please put yourself into my shoes for a second. Folks make me follow nervous gifs and make me type that into the editor (did people forget about copy&paste?!?). 

It doesn't repo for me, folks say it reproduces so the truth is that the crucial piece of information is still missing. Unfortunately I don't have time for some exploratory investigation but I do have many other, more precise, issues to work on. So guess what happens? I work on other things. 

So, please test this for once with latest insiders, then share your sample (not a gif nor an image, those are just for decoration), then write down precise steps that leave no room for interpretation which I can follow. A good validation is to test those steps on a different workspace, with different files and/or settings because I don't have your workspace (unless you can share it with me). Thanks for helping out.

**Comment by whitissolutions** [comment] 2017-12-12 18:31
I was having the same issue as the others above and I found a fix by installing "vscode-endwise" extension. Which will auto provide an end when one is needed.

**Comment by GeorgeKaraszi** [comment] 2017-12-17 13:06
I believe the issue is dealing with the equal's sign. Take these few examples.

**Basic Method with out predefined params: (Aligns correctly)**
![good-alignment](https://user-images.githubusercontent.com/9029051/34079688-7b7a5416-e300-11e7-9b3a-feaa41fa5a82.png)

**Basic Method predefined params: (Bad alignment detection)**
![predefined-param](https://user-images.githubusercontent.com/9029051/34079705-b6be6b5c-e300-11e7-9818-3bb35991f9aa.png)


**Body conditional without assignment: (Aligns correctly)**
![body-conditional-no-eq](https://user-images.githubusercontent.com/9029051/34079713-e6357e7a-e300-11e7-9263-1094b4e0177d.png)

**Body conditional with assignment: (Bad alignment detection)**

![body-condtional-eq](https://user-images.githubusercontent.com/9029051/34079719-feb8d94c-e300-11e7-94b2-997494deab2e.png)

**Comment by robruder** [comment] 2017-12-19 20:06
I was having the same issue, and was able to fix it by installing the rcodetools gem.

**Comment by pmossman** [comment] 2018-02-27 19:28
@jrieken I have reproduced this on an out-of-the-box installation of the latest VS Code Insiders (Version 1.21.0-insider)

1) Create a new file with a `.rb` extension
2) Type the word 'enabled' at the top of the file (to give autosuggestion a word to suggest from the file)
3) Begin typing out your function definition:
```
def foo
    bar
```
4) Hit enter after bar, and your cursor should be on the same indentation level as `bar`
5) Begin typing `end`. Notice that as soon as you type `d` the word `end` should unindent to the left.
6) Autosuggest will now offer `enabled`, and hitting enter at this point replaces `end` with `enabled`.

And now your favorite, ![a gif](https://user-images.githubusercontent.com/7798112/36749932-1ef0e0cc-1bb1-11e8-93f2-b57a26609099.gif)

**Comment by jrieken** [comment] 2018-03-08 16:58
> Autosuggest will now offer enabled, and hitting enter at this point replaces end with enabled.

So, your expectation is that outdenting cancels suggest, right? @rebornix Does the editor emit a special change event or a special cursor change reason for that?

**Comment by pmossman** [comment] 2018-03-08 18:45
Yep, I would expect the outdent to cancel any suggestions. This would match Sublime Text's behavior, demonstrated here:

![sublime-behavior](https://user-images.githubusercontent.com/7798112/37169775-ba61ab6e-22bd-11e8-9a69-d7667bd4684f.gif)

**Comment by jrieken** [comment] 2018-03-09 07:49
Thanks @pmossman. I have pushed a change that cancels a suggest session when the start of the to be completed word shifts left. Fingers crossed that this doesn't break other, yet unknown, usages...

**Closed** 2018-03-09 07:49 UTC
Labels: editor-autoindent, suggest
