### ISSUE TITLE
Text color show incorrect after last update.

### ISSUE THREAD

**Issue by boypro2007vn** [microsoft/vscode#92447] opened 2020-03-11 08:41 UTC
Some text color show incorrect after last update.
https://imgur.com/a/jH51pVX

**Comment by mattacosta** [comment] 2020-03-11 12:53
Duplicate of #92308.

Assuming that `isNullOrUndefinedOrEmpty` is a function, then this is just the semantic highlighter doing its thing. You can turn it off using: `"editor.semanticHighlighting.enabled": false`.

**Comment by aeschli** [comment] 2020-03-11 20:26
Duplicate of #92308.

**Closed by aeschli** 2020-03-11 20:26 UTC
Labels: semantic-tokens, typescript
