### ISSUE TITLE
Allow to dock tabs to the side and get back to it later

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#46507] opened 2018-03-25 21:15 UTC
When splitting tabs, is it possible in a coming release to dock a split tab whether the tab is split in a left or right pane and retrieve when needed ?

**Comment by bpasero** [comment] 2018-03-26 04:35
@SheepDomination how would that work?

**Comment by SheepDomination** [comment] 2018-03-26 13:53
When splitting the window; you could click the middle vertical split pane divider and that would dock the pane, for example; to the right, and so you would see the split pane as a tab to the right side of the window.

**Comment by bpasero** [comment] 2018-09-13 05:50
I argue this is a duplicate of https://github.com/Microsoft/vscode/issues/44318

**Closed by bpasero** 2018-09-13 05:50 UTC
Labels: feature-request, workbench-editors, workbench-layout
