### ISSUE TITLE
shell script highligh does not properly

### ISSUE THREAD

**Issue by nraddan** [microsoft/vscode#116117] opened 2021-02-08 15:02 UTC
Issue Type: <b>Bug</b>

sql=`sqlplus -s user/pwd@tns << EOFSQL
set serveroutput on;
EOFSQL`

adding this in a shell script is not properly highlighted things

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1

</details>

**Comment by alexr00** [comment] 2021-02-09 10:41
We get our shell script grammar from https://github.com/atom/language-shellscript/. This issue looks like a duplicate of https://github.com/atom/language-shellscript/issues/158.

**Closed by alexr00** 2021-02-09 10:41 UTC
