### ISSUE TITLE
New update broke Markdown preview zoom

### ISSUE THREAD

**Issue by hsutter** [Microsoft/vscode#13674] opened 2016-10-13 13:04 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.cpptools-0.8.1

Steps to Reproduce:

1. Open a Markdown file.
2. Click Preview icon.
3. Use `Ctrl+=` a few times to zoom -- the child window dimensions don't scale properly, the text gets bigger but the area in which it's shown gets smaller and smaller.

**Comment by gregvanl** [comment] 2016-10-13 16:44
Duplicate of https://github.com/Microsoft/vscode/issues/12921 which is dependent on Electron issue mentioned in https://github.com/Microsoft/vscode/issues/5745

**Closed by gregvanl** 2016-10-13 16:44 UTC
Labels: duplicate
