### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: /Users/sergiomartinez/Documents/Wincaja/wincaja-monorepo/node_modules/.pnpm/@chakra-ui+system@2.5.1_@emotion+react@11.0.0_@emotion+styled@11.0.0_react@18.2.0/node_modules/@emotion/react/types/index.d.ts linked to nonexistent file /Users/sergiomartinez/Documents/Wincaja/wincaja-monorepo/node_modules/.pnpm/@emotion+react@11.0.0_@babel+core@7.21.8_@types+react@18.0.25_react@18.2.0/node_modules/@emotion/react/types/index.d.ts

### ISSUE THREAD

**Issue by smaagk** [microsoft/vscode#186463] opened 2023-06-28 02:52 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230502

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: /Users/sergiomartinez/Documents/Wincaja/wincaja-monorepo/node_modules/.pnpm/@chakra-ui+system@2.5.1_@emotion+react@11.0.0_@emotion+styled@11.0.0_react@18.2.0/node_modules/@emotion/react/types/index.d.ts linked to nonexistent file /Users/sergiomartinez/Documents/Wincaja/wincaja-monorepo/node_modules/.pnpm/@emotion+react@11.0.0_@babel+core@7.21.8_@types+react@18.0.25_react@18.2.0/node_modules/@emotion/react/types/index.d.ts
    at realPath (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42076:9)
    at getOriginalAndResolvedFileName (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41011:28)
    at createResolvedModuleWithFailedLookupLocationsHandlingSymlink (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:40842:48)
    at nodeModuleNameResolverWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:42005:10)
    at nodeModuleNameResolver (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41940:10)
    at resolveModuleName (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:41690:18)
    at resolveModuleName2 (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123681:27)
    at Object.resolve (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123708:47)
    at resolveNamesWithLocalCache (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123747:29)
    at Object.resolveModuleNameLiterals (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123833:12)
    at ConfiguredProject2.resolveModuleNameLiterals (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173634:33)
    at resolveModuleNamesWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118853:20)
    at resolveModuleNamesReusingOldState (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119005:75)
    at processImportedModules (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120520:27)
    at findSourceFileWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120250:7)
    at findSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at processImportedModules (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120544:11)
    at findSourceFileWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120250:7)
    at findSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at processImportedModules (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120544:11)
    at findSourceFileWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120250:7)
    at findSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at processImportedModules (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120544:11)
    at findSourceFileWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120250:7)
    at findSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at processImportedModules (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120544:11)
    at findSourceFileWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120250:7)
    at findSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120115:20)
    at /private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120064:22
    at getSourceFileFromReferenceWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120033:26)
    at processSourceFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120062:5)
    at processRootFile (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119859:5)
    at /private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118638:41
    at forEach (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118638:5)
    at synchronizeHostData (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141677:15)
    at Object.getProgram (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141749:5)
    at ConfiguredProject2.updateGraphWorker (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174307:41)
    at ConfiguredProject2.updateGraph (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174159:32)
    at ConfiguredProject2.updateGraph (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175412:24)
    at updateProjectIfDirty (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175865:35)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178120:11)
    at /private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178397:64
    at flatMap (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178397:24)
    at updateOpen (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179577:29)
    at /private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182149:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182141:14)
    at IpcIOSession.executeCommand (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182149:29)
    at IpcIOSession.onMessage (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182191:51)
    at process.<anonymous> (/private/var/folders/bp/cd32q3113fzc8s68hj38xzhh0000gn/T/AppTranslocation/80973791-DF32-4CF2-B7CC-75F298ABEDD1/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183771:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:939:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (2c73d2651cc525b27fc697b820743098a204ec01, 2023-05-04T22:14:17.675Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 7|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.78.0
copilot-chat|Git|0.3.2023060801
copilot-nightly|Git|1.93.193
vscode-github-actions|git|0.25.8
rest-client|hum|0.25.1
nuget-reverse-package-search|jes|0.1.68
vscode-peacock|joh|4.2.2
vscode-docker|ms-|1.25.1
csharp|ms-|1.26.0
powershell|ms-|2023.6.0
prisma|Pri|4.16.1
prisma-insider|Pri|31.0.2375
LiveServer|rit|5.7.9
icons|tal|3.6.3
quokka-vscode|Wal|1.0.547

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30763246
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
gsof1:30771514
e440d664:30770001
pythonidxpt:30768918
pythondjangots:30768917
pythonnocebcf:30766856
copilotsettingt:30767686
e537b577:30772214

```

</details>

**Comment by bryanalia** [comment] 2023-06-28 06:05
>

**Comment by mjbvz** [comment] 2023-07-10 20:27
Closing as caused by pnpm. Please start by filing an issue against them

**Closed by mjbvz** 2023-07-10 20:27 UTC
