### ISSUE TITLE
highlight more than 999 items using CMD+F2 does not work.

### ISSUE THREAD

**Issue by lookbehindyouathreeheadedmonkey** [Microsoft/vscode#34458] opened 2017-09-15 12:26 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0

---
I cant highlight/edit more than 999 items when using CMD+F2.

Steps to Reproduce:

1. command+f2 try to select highlight item which has more than 999 identical items in the same file.

**Comment by alexandrudima** [comment] 2017-09-28 10:00
Duplicate of #5887

**Closed by alexandrudima** 2017-09-28 10:00 UTC
Labels: editor-1000-limit
