### ISSUE TITLE
Moving line into script tag outdents script tag

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31867] opened 2017-08-01 21:19 UTC
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Testing #31831

One 'move line up' followed by 3 'move line down':
![movelineintoscripttag](https://user-images.githubusercontent.com/9205389/28847509-56a12852-76c4-11e7-8098-592fe780971c.gif)

Text:
```html
<html>

<head>
    <style>

    </style>
    <script>
        var a = 2;
        var b = 2;
        var c = 2;
        var d = 2;
    </script>
</head>

</html>
```

**Comment by roblourens** [comment] 2017-08-04 00:59
Better... 😄 

![aug-03-2017 17-58-15](https://user-images.githubusercontent.com/323878/28950008-6a3884fc-7875-11e7-963f-0a2d09e152b2.gif)

**Comment by alexandrudima** [comment] 2017-09-01 08:57
Moving to September.

**Comment by rebornix** [comment] 2018-09-18 18:59
The issue mentioned above shares the same root cause as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. 
A simple but not perfect fix for this issue (not pushed as it needs more consideration) fixes this one

![movelines-funk](https://user-images.githubusercontent.com/876920/45710019-4c747d00-bb3a-11e8-94f8-58ffad49f360.gif)

Let's use that issue to track.

**Closed by rebornix** 2018-09-18 18:59 UTC
Labels: bug, editor-autoindent, verification-found
