### ISSUE TITLE
Inline breakpoint jumps when saving file with line changes

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#81804] opened 2019-10-01 22:38 UTC
Testing https://github.com/microsoft/vscode/issues/81175

1. Start debugging and place an inline breakpoint
2. Make edits to that line - breakpoint correctly shifts
3. Save the file - breakpoint jumps to original position
![breakpoint_jump](https://user-images.githubusercontent.com/3672607/66005583-c97e4600-e460-11e9-934c-4681003e47c1.gif)

**Comment by isidorn** [comment] 2019-10-02 07:52
This is actually as designed behavior. Reason being, when you save the file we send the breakpoint back to the extension, and the debug extension tells us where the breakpoint should be positioned.
If you think the new position is not correct you should file this against the node / chrome @roblourens 

However I think the behavior here is fine, and there is nothing we can do about this. Since when you stop debugging it should go back to the edited location. Thus closing as designed.
Though I am open for ideas on improvments, in that case I can reopen.
Thanks

**Closed by isidorn** 2019-10-02 07:52 UTC
