### ISSUE TITLE
Terminal input broken for Julia

### ISSUE THREAD

**Issue by ZacLN** [Microsoft/vscode#19815] opened 2017-02-03 09:36 UTC
- VSCode Version: 1.9.0
- OS Version: ArchLinux

Steps to Reproduce:

1. Load VScode, open Julia in the integrated terminal
2. Select some arbitrary code, e.g. `# comment` and send to the terminal
3. The line of code is successfully sent 
4. Reverse-search mode is unintentionally enabled (usually bound to CTRL-R).

It seems that some new escape/control characters are being added at the end of input to the terminal triggering this

UPDATE: occasionally output on the terminal is prefixed by`?20041`

**Comment by Tyriar** [comment] 2017-02-03 16:58
Was this happening in v1.8.1? What does your settings.json file look like?

**Comment by ZacLN** [comment] 2017-02-03 17:35
There were no problems with this in 1.8.1.

This happens with empty settings/ a clean install though using `"terminal.integrated.shell.linux": "rlwrap",` seems to lower the frequency with which it happens.

**Comment by davidanthoff** [comment] 2017-02-03 18:54
I can't repo this on Windows, so this might be a non-Windows only issue.

**Comment by lbollar** [comment] 2017-02-03 19:48
I do have this experience on Mac. VS Code 1.9. 

It doesn't seem to happen upon assignment, but it does when say just typing in a variable name to observe it. I don't have to send code to terminal for this to happen, just typing in the terminal produces it.

**Comment by tshort** [comment] 2017-02-03 20:51
I get something like that, but for me, it's triggering a `forward-i-search`. I'm on ArchLinux with VSCode 1.9.0.

**Comment by Tyriar** [comment] 2017-02-04 00:09
@tshort is `forward-i-search` assigned to ctrl+s on your shell? If so you might be running into this https://github.com/Microsoft/vscode/issues/19766

Could everyone who can reproduce please provide the following info:

- What shell are you using
- If you're using something like oh-my-zsh for some special sauce on your shell
- Does ctrl+s and/or ctrl+q do anything when you trigger them on your native terminal when running a command with a lot of output such as `ls -lR ~`
- Does adding `"terminal.integrated.flowControl": false` to your settings file fix the problem?

**Comment by ZacLN** [comment] 2017-02-04 08:49
- Julia
- no
- ctrl+s -> forward-search
- ctrl+q -> nothing
- disabling `flowControl` fixes it!

**Comment by tshort** [comment] 2017-02-06 13:50
Yes, `ctrl+s` is `forward-i-search`. The workaround from #19766 fixes it for me:

    "terminal.integrated.flowControl": false

**Comment by Tyriar** [comment] 2017-02-06 19:37
Great! This is a duplicate of #19766 then

**Closed by Tyriar** 2017-02-06 19:37 UTC
Labels: integrated-terminal, needs more info
