### ISSUE TITLE
Integrated terminal echoes secrets with new Local Echo feature

### ISSUE THREAD

**Issue by tinyzimmer** [microsoft/vscode#113179] opened 2020-12-20 06:36 UTC
I've noticed that the new Local Echo feature from the October update - always echoes.

That is when my machine is under load and I am executing a command in the integrated terminal under WSL as `sudo`, I see my password on the console while I'm typing it. Same as for SSHing to a remote server using password authentication.

I can understand this is probably mostly harmless, but in an office setting without privacy monitors, this could actually pose a potential risk. 

Is there any way for the local echo to know when the terminal itself is deliberately not echoing back, besides disabling the feature outright?

- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. SSH to far away or high-latency machine requiring password authentication
OR
1. Execute a command as sudo while host system is under load

2. See your password echoed to the console as you type it

Hard to verify, using Remote-WSL which is by itself an extension

**Comment by tinyzimmer** [comment] 2020-12-20 06:37
Actually that definitely looks like a duplicate, my apologies

**Comment by meganrogge** [comment] 2020-12-22 21:40
Duplicate of #110359

**Closed by meganrogge** 2020-12-22 21:40 UTC
Labels: *duplicate
