### ISSUE TITLE
Update hangs or is not installing

### ISSUE THREAD

**Issue by monkeypunch3** [Microsoft/vscode#14543] opened 2016-10-26 15:02 UTC
- VSCode Version:1.2.0
- OS Version:10.11.6

Steps to Reproduce:
1. Selected Check for updates. Expected something to happen but no messages.
2. Went to select Check for update again and it says Installing update...

But it has not shown any change in a a while. There is no feedback if an update is downloading or if the install process has hung.

**Comment by joaomoreno** [comment] 2016-10-26 15:09
Does it reproduce after restarting?

**Comment by monkeypunch3** [comment] 2016-10-26 15:11
I restart and it's the same. Check for Update is an active menu item. It does the same thing. It may be a slow internet connection. What is supposed to happen normally?

**Comment by joaomoreno** [comment] 2016-10-26 15:17
It's supposed to notify you that the update is ready and ask you to restart. Just wait a while.

**Comment by monkeypunch3** [comment] 2016-10-26 15:26
Ain't nobody got time for that

**Comment by joaomoreno** [comment] 2017-04-26 08:53
Closing due to sandwich. 🍞

**Closed by joaomoreno** 2017-04-26 08:53 UTC
Labels: needs more info
