### ISSUE TITLE
Emmet not working

### ISSUE THREAD

**Issue by Lahori-Jawan** [Microsoft/vscode#958] opened 2015-12-03 10:03 UTC
I just updated visual studio code and as a result I see that emmet is not working now. in previous releases, emmet did work fine but since last 2 updates, emmet seems to be disabled or excluded altogehter from visual studio code. I searched for emmet extension on VS CODE repository but found nothing. my current version in 0.10.3. emmet also did not work in last release but before that all was good. I want emmet badly back!

**Comment by egamma** [comment] 2015-12-03 10:28
Cannot reproduce. 
1) open an html file
2) ul>li*5<TAB>
and I get an emmet expansion.

Pls try out these steps in a VS Code setup without any extensions installed.

**Comment by SamVerschueren** [comment] 2015-12-03 12:58
Cannot reproduce either, works fine on Mac OS X (El Capitan).

**Comment by egamma** [comment] 2015-12-03 12:59
closing pls reopen with with reproducable steps.

**Closed by egamma** 2015-12-03 12:59 UTC
Labels: needs more info

**Comment by Lahori-Jawan** [comment] 2015-12-04 06:24
well, removing the extension did the trick but now I wonder if i update next time, then again I would have to remove all the extensions and then re-install them one-by-one which is very time consuming, right! BTW thanks for help!

**Comment by SamVerschueren** [comment] 2015-12-04 07:05
That's abnormal behaviour. Maybe something broke during the update process.

**Comment by egamma** [comment] 2015-12-04 07:21
Or the extension has some side effects. What extension did you have installed when the problem occured?

**Comment by Lahori-Jawan** [comment] 2015-12-04 13:09
just themes. flatland, monokai, batman

**Comment by stevenmwade** [comment] 2016-02-05 19:32
I can reproduce. Open html file and type `div` and hit `tab`, it just tabs.

**Comment by Sapunov** [comment] 2016-10-06 07:02
I can reproduce this behavior. Emmet doesn't work when html file doesn't save on a hard drive.

**Comment by mrmlnc** [comment] 2016-10-06 07:12
@Sapunov,

I cannot reproduce this problem in VS Code 1.5.3 on Windows 10. provide GIF or a small code example where occurs described problem and more detailed information:

  1. VS Code version
  2. List of installed extensions

**Comment by cAstraea** [comment] 2017-01-31 11:26
is the emmet only working in html files ?  How would I go about enabling it in .vue files for example ?

**Comment by skyweb331** [comment] 2017-06-18 19:32
it is only working in html extension files. 
I tried it in *.php file but not working.  I just changed file extension and now working fine

**Comment by jens1o** [comment] 2017-06-18 19:36
> I tried it in *.php file but not working. I just changed file extension and now working fine

This will be fixed in next release, since @ramya-rao-a is working on it. :) There is another issue where this gets explained.

**Comment by ramya-rao-a** [comment] 2017-06-19 01:35
@skyweb331 If you are not on Insiders, try mapping php to html using the `emmet.syntaxProfiles` setting

```
{
    "emmet.syntaxProfiles": {
        "php": "html"
     }
}
```

**Comment by skyweb331** [comment] 2017-06-19 09:45
I did it but still not working.

**Comment by ramya-rao-a** [comment] 2017-06-19 14:58
@skyweb331 What is your VS Code version? Please provide a sample code or gif where you see this issue

**Comment by Boasbabs** [comment] 2017-07-09 22:33
Hi there, I am still having issues using emmet on VScode. From what i read so far, i have to remove all my extensions plugin. But that does not sound logical to me. VSCode is robust. I want to use VScode but if issues like this aren't solved, i will stick with my old editor.

**Comment by ramya-rao-a** [comment] 2017-07-10 00:39
@Boasbabs 

>  I want to use VScode but if issues like this aren't solved, i will stick with my old editor.

We can only solve issues that we can understand. So please help us in that by answering the below questions.

- Is emmet working as expected when you run the command `Emmet: Expand Abbreviation`? 
- Just before you press tab, is there any auto-complete/suggestion list open?
- In which kind of file is emmet not working for you? Eg: html, php, jsx, css, scss ?
- You don't need to remove all your extensions. Can you point to the place where you read that?

**Comment by cjwd** [comment] 2017-07-19 20:07
I'm having the same issue, emmet is not expanding with tab in php files.
To answer your above.

- Yes it works if I use the command palette
- There is no auto complete/ suggestion list open
- PHP

Version 1.14.1 (1.14.1)

I have tried the 
{
    "emmet.syntaxProfiles": {
        "php": "html"
     }
}

**Comment by ramya-rao-a** [comment] 2017-07-19 20:34
@cjwd Do you have `emmet.useNewEmmet` set to `true`?

**Comment by cjwd** [comment] 2017-07-20 21:36
Yes I do.

**Comment by ramya-rao-a** [comment] 2017-07-20 22:25
@cjwd Please read https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list

- tab is not longer the default keybinding for emmet. Use the command `Emmet: Expand Abbreviation` or bind a new keybinding to the command `editor.emmet.action.expandAbbreviation`
- Another thing you can try is to set `emmet.showExpandedAbbreviation` to "always". This will show emmet expansions in the suggestion list

**Comment by cjwd** [comment] 2017-07-21 18:49
Thank you @ramya-rao-a I went with the second option setting emmet.showExpandedAbbreviation to "always"

**Comment by alePanta** [comment] 2017-08-04 18:04
I could use Emmet on CSS files setting `"emmet.useNewEmmet": true` 
Thanks.

**Comment by ramya-rao-a** [comment] 2017-08-10 17:04
Hey All,

In VS Code 1.15, there will be changes to how use Emmet in VS Code. Mainly
- Emmet abbreviations will no longer expand on pressing tab, instead they will appear in the suggestion/auto-completion list. On selecting them from the suggestion list, the abbreviation will get expanded
- `Emmet: Expand Abbreviation` command will continue to work and you bind any keyboard shortcut (other than `tab`) to it (`editor.emmet.action.expandAbbreviation`)
- `emmet.syntaxProfiles` should now be used only for customizing the final output and not for mapping new file types to existing emmet supported modes. For that, use the new setting `emmet.includeLanguages`

Read more on [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

**Comment by iscorporacion** [comment] 2017-08-25 04:09
no se si aun sirva de algo, peo emmet se a actualizado si mal no estoy date una vuelta por https://docs.emmet.io/cheat-sheet/ yo tambien pense que no estaba funcionando, cuando intentaba escribir html5 y esperar el cuerpo base pero fue cambiado a "!" signo de admiracion

**Comment by eduard-ungureanu** [comment] 2017-10-03 17:43
Hi, while this works as expected in a `.html` file:
![html-file](https://www.dropbox.com/s/11yf0vfw6rra2gw/Screenshot%202017-10-03%2020.39.00.png?raw=1)

It doesn't work in a `.php` file if I want to add `HTML` code outside the `<?php ?>` tags:
![PHP file](https://www.dropbox.com/s/32f3kcc0x8ucpg2/Screenshot%202017-10-03%2020.39.17.png?raw=1)

I'm using the latest version Version 1.16.1 (1.16.1) and those are my settings:
```
{
    "editor.fontFamily": "'InputMono-Light', monospace",
    "editor.fontSize": 18,
    "editor.lineHeight": 28,
    "workbench.fontAliasing": "antialiased",
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "workbench.sideBar.location": "right",
    "workbench.iconTheme": "material-icon-theme",
    "materialTheme.cache.workbench.settings": {
        "themeColours": "Default"
    },
    "workbench.colorTheme": "Material Theme",
    "emmet.useNewEmmet": true,
    "emmet.includeLanguages": {
        "php": "html",
    }
}
```

So I guess I'm going back to Sublime Text, since those are working as it should in SB maybe you guys will consider fixing this in the future.

**Comment by ramya-rao-a** [comment] 2017-10-03 18:12
@eduard-ungureanu https://github.com/Microsoft/vscode/issues/32423 tracks the issue of emmet abbreviations with class operator (`.`) not triggering emmet suggestions unless `php.suggest.basic` is disabled.

Here are a few workarounds until we can solve the original issue
- Disable `php.suggest.basic` if you dont use it much. OR
- When you expect the emmet suggestions to show and they dont, do one of the below. Both will cancel the current completion list and trigger new one OR
       - press ESCAPE and then `Ctrl+Space` or continue typing the abbreviation if you are not done doing so. 
       - delete last char and continue typing.

Note this occurs only when the only operator in the emmet abbreviation is the class operator.
Use others like `+` or `>` or `#` and emmet suggestions will appear as expected.

**Comment by DenisValcke** [comment] 2017-10-12 11:23
I had the same problem and then I noticed the following in my default settings:
```json
// When enabled, emmet abbreviations are expanded when pressing TAB.
  "emmet.triggerExpansionOnTab": false,
```

Setting, that to true solved it for me.
