### ISSUE TITLE
MAJOR : Crash when using "Open Folder ..."

### ISSUE THREAD

**Issue by Tomlarigole** [microsoft/vscode#230597] opened 2024-10-05 16:27 UTC
Type: <b>Bug</b>

When i click on "File -> Open Folder ...", VSCode crashes. Sometime it does open a page with my directories, but when i click on a directory, VSCode crashes also.
For now i'm forced to use "code /path/to/directory" to open VSCode at the root of my projects, so it NEEDS to be fixed ASAP.
(Bug happens every-single time: it's reproductible.)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 4342)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.21GB (8.84GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 39873a0c-1bd9-4432-985c-78bcc9467a17|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
auto-rename-tag|for|0.1.10
copilot|Git|1.235.0
copilot-chat|Git|0.21.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5941
firacode|Sey|2.2.1
cmake|twx|0.0.17
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-05 16:51
/duplicate of https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-05 16:52 UTC
Labels: *duplicate, new release
