### ISSUE TITLE
Duplicating strings and numbers with the same characters on type after tab or window switched

### ISSUE THREAD

**Issue by alwonder** [Microsoft/vscode#52125] opened 2018-06-17 09:30 UTC
- VSCode Version: 1.24.1
- OS Version: macOS High Sierra 10.13.5 (17F77)

Steps to Reproduce:

1. Switch to another tab or to another application
2. Switch back to the current tab/focus on the VSCode window
3. Type a character to a string containing only the same characters (e.g. type 3 on a number 333)

![bug](https://user-images.githubusercontent.com/543201/41506622-4a51e2b4-725c-11e8-976f-bc72e9639b5f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-07-31 13:53
Duplicate of #49480

**Closed by alexandrudima** 2018-07-31 13:53 UTC
Labels: bug, editor-input, mac
