### ISSUE TITLE
java debugger

### ISSUE THREAD

**Issue by Basithpk** [Microsoft/vscode#16020] opened 2016-11-24 11:55 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.0.2|
|vscode-javac|georgewfraser|0.0.23|
|java-properties|ithildir|0.0.1|
|java|redhat|0.0.7|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment] 2016-11-24 16:30
I have followed your *Steps to Reproduce* this. They aren't very accurate and leave some room for interpretation. Therefor of that I take the freedom to close this issue as *works for me*. 

In case you want us to improve VS Code but fixing bugs and implementing features, please file issues with steps etc. Learn all about file issues by reading this: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

Feel free to update this issue with information. Happy Coding

**Closed by jrieken** 2016-11-24 16:30 UTC
