### ISSUE TITLE
typescript engine suddenly stops

### ISSUE THREAD

**Issue by rickco75** [microsoft/vscode#144524] opened 2022-03-06 20:20 UTC
Issue Type: <b>Bug</b>

just running in docker container (open is container)

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No
Remote OS version: Linux arm64 5.10.76-linuxkit
Remote OS version: Linux arm64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 8|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 3c25aa88-0110-4e1e-bc23-5dccfb1c329d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: gql-data-layer|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|1.94GB (0.06GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: acoustic-sanctuary|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|1.94GB (0.06GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.224.2
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.3.0
copilot|Git|1.7.5227
vscode-graphql|Gra|0.3.41
vscode-typescript-next|ms-|4.7.20220305

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30448491
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by mjbvz** [comment] 2022-03-08 00:15
What does `suddenly stops` mean? Please try adding more detail on what you are seeing

/needsMoreInfo

**Comment by rickco75** [comment] 2022-03-08 00:56
sorry [image: image.png]

**Comment by mjbvz** [comment] 2022-03-08 01:08
The image you tried attaching isn't showing. Please reply through GitHub to make sure it is uploaded

**Comment by rickco75** [comment] 2022-03-08 01:28
TypeScript language service died unexpectedly 5 times in the last 5 minutes

i've had this problem on and off for months,

thank you,
Rick Cohen

**Comment by mjbvz** [comment] 2022-03-08 23:59
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by ErinCall** [comment] 2022-03-11 21:17
I'm also having this problem. In the `TypeScript` section of the output panel, I see this:

```
[Info  - 20:44:05.205] TSServer log file: /Users/erincall/Library/Application Support/Code/logs/20220311T093542/exthost1/vscode.typescript-language-features/tsserver-log-tFgm6t/tsserver.log
[Info  - 20:44:05.205] Starting TS Server
[Info  - 20:44:05.205] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 20:44:05.207] <syntax> Log file: /Users/erincall/Library/Application Support/Code/logs/20220311T093542/exthost1/vscode.typescript-language-features/tsserver-log-n9nHDC/tsserver.log
[Info  - 20:44:05.207] <syntax> Forking...
[Info  - 20:44:05.208] <syntax> Starting...
[Info  - 20:44:05.208] <semantic> Log file: /Users/erincall/Library/Application Support/Code/logs/20220311T093542/exthost1/vscode.typescript-language-features/tsserver-log-LAquJf/tsserver.log
[Info  - 20:44:05.208] <semantic> Forking...
[Info  - 20:44:05.209] <semantic> Starting...
[Info  - 20:47:13.390] TSServer exited. Signal: SIGABRT
[Info  - 20:47:13.390] TSServer log file: /Users/erincall/Library/Application Support/Code/logs/20220311T093542/exthost1/vscode.typescript-language-features/tsserver-log-LAquJf/tsserver.log
[Info  - 20:47:13.390] Starting TS Server
... and so on ...
```

There's a new `Starting TS Server` line every 3 minutes.

I don't see any obvious stack traces in any of the `tsserver.log`s, but they're 20k+ lines long so it's possible I scrolled past something. I can try grepping if you can suggest a search pattern. 

That logfile size got me wondering about memory, and indeed if I watch htop I can see it gradually consuming more and more memory until it gets up to around 3500M. It hangs out around there until it crashes, then starts over again. I can try turning up my Max TS Server Memory setting (currently 3072), but there's a limit to how far I can take that.

**Comment by nati-maskens** [comment] 2022-03-24 09:08
This seems to be related to #145309

**Comment by mjbvz** [comment] 2022-03-24 22:04
Closing as we need information from the original poster to investigate this

@ErinCall If you are seeing this in VS Code insiders with extensions disabled, please open an new issue. You can also email me the logs: matb at microsoft

**Closed by mjbvz** 2022-03-24 22:04 UTC
Labels: needs more info
