### ISSUE TITLE
Visual studio code does not automatically change folder tree when navigate code

### ISSUE THREAD

**Issue by leowucn** [Microsoft/vscode#69425] opened 2019-02-26 01:22 UTC
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

The bug is that the folder tree does not automatically change when navigating code even if "explorer.autoReveal": true.

**Comment by yume-chan** [comment] 2019-02-26 02:31
Duplicate of #68627

**Closed** 2019-02-26 18:05 UTC
Labels: *duplicate
