### ISSUE TITLE
Unable to rebuild container

### ISSUE THREAD

**Issue by zachgordon25** [microsoft/vscode#139235] opened 2021-12-15 20:47 UTC
ADD ISSUE DESCRIPTION HERE

I get a notification to rebuild my container and then when I click to do so, I get the following message:
Rebuild Container: Unable to start container rebuild.

Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment] 2021-12-16 14:53
Duplicate of https://github.com/github/feedback/discussions/8913

**Closed by chrmarti** 2021-12-16 14:53 UTC
