### ISSUE TITLE
search on vertical selection not work

### ISSUE THREAD

**Issue by cvazwm** [microsoft/vscode#78881] opened 2019-08-11 00:18 UTC
Issue Type: <b>Bug</b>

When I select the code previusly writed, doing one click in one corner and with Shift + Alt other click in the second corner where I want select... I press Ctrl + F, erase the text in the search box for search an custom word... check the option for search in selection.. and the result has been search in the next I had selected... (out of square selected)..  ON the first line selected.
Therefore searched the first word out of the selection on the first line selected.
I think, that its an detail, but I noticed not has worked... 
regards!

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

**Comment by cvazwm** [comment] 2019-08-11 00:33
If I select some text and enable search in selection... only searched on the first line

![a](https://user-images.githubusercontent.com/17833058/62828184-258dc200-bbb6-11e9-8a26-095704a4266d.JPG)

![b](https://user-images.githubusercontent.com/17833058/62828186-2d4d6680-bbb6-11e9-9d6d-9f378fa02c34.JPG)

If I retry select the same text or other part of this... the search box not refresh the search... 

![c](https://user-images.githubusercontent.com/17833058/62828202-83220e80-bbb6-11e9-8dfb-71efe2406984.JPG)

**Comment by rebornix** [comment] 2019-10-22 23:16
/duplicate of https://github.com/microsoft/vscode/issues/38363

**Closed** 2019-10-22 23:16 UTC
Labels: *duplicate, editor-find, feature-request
