### ISSUE TITLE
Allow to copy the name of a file

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#19372] opened 2017-01-25 15:29 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|python|donjayamanne|0.5.6|
|EditorConfig|EditorConfig|0.3.4|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.10|
|cpptools|ms-vscode|0.9.3|
|vscode-clearcase|OpenNingia|1.4.2|
|vscode-icons|robertohuertasm|7.1.2|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

To complement "Files: Copy Path of Active File" please add a "File: Copy Name of Active File", which just provides the filename without the path. For example, for a file "C:\test\test1.c", doing  "File: Copy Name of Active File" would provide "test1.c". I often copy filenames to discuss by email or code review and have to edit out the path. Another useful command could provide the path relative to root folder.

**Comment by mousetraps** [comment] 2017-01-26 01:03
That would be useful! Until then, looks like an extension's got you covered :smiley:
https://marketplace.visualstudio.com/items?itemName=nemesv.copy-file-name

cc @waderyan

**Comment by BillDenton** [comment] 2017-01-26 09:11
There's also an extension for relative path https://marketplace.visualstudio.com/items?itemName=enochc.copy-relative-path
However, I still think that the filename and with relative path should be added as internal commands. I'm not so sure about without the extension. I don't think that this is as useful, so probably not worth it.

**Comment by BillDenton** [comment] 2017-02-24 10:19
I'm don't think I need this anymore as "Copy Path" and "Reveal in Explorer" are on the tab context menu. This is sufficient for my use case. I don't know if this commands can be bound to keys. I'm not interesting in binding them to keys because I don't use them often enough to learn (& forget) yet another key sequence.

**Comment by TomasHubelbauer** [comment] 2018-04-10 15:01
FWIW I would also like to see *Copy Relative Path* and an internal command next to the *Copy Path* one which exists on the tab context menu currently. That one should be renamed to *Copy Absolute Path*. This feature request is titled *Copy file name*, which I am not sure refers to relative files? But that I think would be the most useful.

**Comment by vancouverwill** [comment] 2018-05-14 16:57
*copy relative path* is the killer feature intelliJ products have and it s really useful when working with others, writing documentation, tickets etc

**Comment by bpasero** [comment] 2018-07-02 04:42
Duplicate of https://github.com/Microsoft/vscode/issues/47193

**Closed by bpasero** 2018-07-02 04:42 UTC
Labels: feature-request, file-explorer
