### ISSUE TITLE
i use input-method with macos,when i commit code, There is a high probability that bugs cannot be filled in,because the input cannot be focused

### ISSUE THREAD

**Issue by MrKaKaluote** [microsoft/vscode#114018] opened 2021-01-08 07:10 UTC
the git commit input cannot be focused when i input  in chinese log
![image](https://user-images.githubusercontent.com/21680704/103985277-98440800-51c3-11eb-8d82-c11afe8fac4c.png)

**Comment by Lyan-u** [comment] 2021-01-08 07:31
I also encountered this problem on windows, can not enter the commit message, only restart vscode to solve
![image](https://user-images.githubusercontent.com/46185702/103986671-1dc8b780-51c6-11eb-865e-8a11dbab9d5b.png)

![image](https://user-images.githubusercontent.com/46185702/103986645-15707c80-51c6-11eb-93a2-02150476de25.png)

**Comment by alexdima** [comment] 2021-01-08 08:45
Duplicate of https://github.com/microsoft/vscode/issues/112621

**Closed by alexdima** 2021-01-08 08:45 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
