### ISSUE TITLE
Broken icons when open project from terminal

### ISSUE THREAD

**Issue by redVi** [Microsoft/vscode#26270] opened 2017-05-09 06:03 UTC
- VSCode Version: 1.12.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open terminal an run `code path_to_folder`
<img width="770" alt="console" src="https://cloud.githubusercontent.com/assets/2623486/25837232/f6cb2274-34b6-11e7-8717-aa1611b41da0.png">

2. The icons look awful (after update to 1.12.1)
<img width="1026" alt="code" src="https://cloud.githubusercontent.com/assets/2623486/25837354/a557ce0a-34b7-11e7-9149-7c4e6e32af59.png">

**Comment by jenswegar** [comment] 2017-05-09 06:12
I'm seeing the same thing. Opening from terminal with `code /path/to/project` draws all icons in the UI as strange artifacts. Opening the same project by first opening vscode, then using file->open recent draws the UI as expected.

macOS sierra 10.12.4
vscode: 1.12.1

**Comment by hannupekka** [comment] 2017-05-09 06:35
Same here.

OSX El Capitan 10.11.6
VSCode 1.12.1

**Comment by bpasero** [comment] 2017-05-09 10:47
This is https://github.com/Microsoft/vscode/issues/24820 but I wonder why my workaround is not working as expected in [main.js](https://github.com/Microsoft/vscode/blob/master/src/main.js#L19)

@redVi @jenswegar @hannupekka can you send me the contents of your shell environment? You can quickly get there by running `process.env` from the console when developer tools are open (from the help menu):

![image](https://cloud.githubusercontent.com/assets/900690/25847272/add01abc-34b5-11e7-8934-9065bc9f4ad0.png)

**Comment by redVi** [comment] 2017-05-09 11:01
@bpasero yes, this is the same reason. I removed locale settings `export LC_CTYPE` and `export LC_ALL` and now the artifacts are gone.

**Comment by bpasero** [comment] 2017-05-09 11:03
@redVi and so what are the values you have for `LC_CTYPE` and `LC_ALL`?

**Comment by redVi** [comment] 2017-05-09 11:04
@bpasero 

```
export LC_CTYPE="ru_RU.UTF-8"
export LC_ALL="ru_RU.UTF-8"
```

**Comment by hannupekka** [comment] 2017-05-09 11:06
@bpasero from my `process.env` output:

```
LC_ALL: "fi_FI.UTF-8"
LC_COLLATE: "fi_FI.UTF-8"
LC_CTYPE: "fi_FI.UTF-8"
LC_MESSAGES: "fi_FI.UTF-8"
LC_MONETARY: "fi_FI.UTF-8"
LC_NUMERIC: "C"
LC_TIME: "fi_FI.UTF-8"
```

**Comment by bpasero** [comment] 2017-05-09 14:04
Closing as duplicate of https://github.com/Microsoft/vscode/issues/24820. It looks like having an environment variable `LC_ALL` with certain languages is enough to trigger this issue. In #24820 I was pushing a workaround when `LC_NUMERIC ` is defined but this does not seem to be enough.

There are three options for people hitting this:
* start VS code from the dock instead of terminal
* make sure `LC_ALL` is not set when running from the command line
* use our insiders build where I just pushed a fix (http://code.visualstudio.com/Download#insiders)

**Closed by bpasero** 2017-05-09 14:04 UTC
Labels: candidate, important
