### ISSUE TITLE
aman ghanghoriya

### ISSUE THREAD

**Issue by amanghanghoriya1** [microsoft/vscode#127754] opened 2021-07-01 10:01 UTC
Issue Type: <b>Feature Request</b>

svg2 properties are not supporting in my css file. for example when I am trying to use rx, ry, cx, cy, x, y etc. properties I am getting (unknown property) error in css file.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

**Comment by aeschli** [comment] 2021-07-01 10:14
duplicate of #66053

**Closed by aeschli** 2021-07-01 10:14 UTC
