### ISSUE TITLE
Zen mode eats first Escape key pressed in terminal

### ISSUE THREAD

**Issue by Hubro** [microsoft/vscode#85186] opened 2019-11-20 08:59 UTC
- VSCode Version: 1.40.1
- OS Version: Arch

When in Zen mode, the first Escape key press in the terminal will be gobbled up and not sent to the terminal. This effectively means that if you use Bash/ZSH in Vi mode, you have to press Escape twice to enter command mode.

Steps to Reproduce:

1. Launch VSCode
2. Enter Zen mode
3. Open terminal while in Zen mode
4. Set Bash/ZSH to Vi mode (`set -o vi` / `bindkey -v` respectively)
5. In terminal, press Escape to enter command mode, then press `k` to go to the last command in the command history
6. Instead, you will enter a literal `k`, as the terminal didn't enter command mode
7. Press Escape again, you will now be in command mode

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2019-11-20 14:20
I can not repro this.
Why do you think that Zen Mode is stealing this keybinding?
If I go into Zen Mode and open a find widget in the terminal the first escape will close the find widget, thus the zen mode is not stealing it.
Assigning to @Tyriar since he might have more ideas

**Comment by Hubro** [comment] 2019-11-20 14:25
> I can not repro this.
> Why do you think that Zen Mode is stealing this keybinding?
> If I go into Zen Mode and open a find widget in the terminal the first escape will close the find widget, thus the zen mode is not stealing it.
> Assigning to @Tyriar since he might have more ideas

I'm blaming Zen mode because it only happens while I'm in Zen mode. I have only experienced it happening in the terminal, I'm not commending on the find widgets or any other widgets. I don't know precisely what component of VSCode is stealing the key event, but it sure isn't reaching the terminal.

Try this out with Bash or ZSH in Vi mode. Write a command like `echo test` and execute it, then press Esc, then press `k` to go the previous command. Instead it writes a literal "k" into the terminal.

Repeat this when *not* in Zen mode, now it works and displays the previous command.

When in Zen mode, you have to press Esc twice for the key press to register with the shell.

Let me know if there are any tests I can run to further narrow down the issue.

**Comment by Tyriar** [comment] 2019-11-20 14:55
I can repro. You're right, I confirmed that the escape isn't getting sent to the shell.

**Comment by isidorn** [comment] 2019-11-20 15:00
Please note that Zen mode might take the escape key via the exitZenmode command here 
https://github.com/Microsoft/vscode/blob/39c14fc431f438ec8c41d54783d517f439ea1de4/src/vs/workbench/browser/actions/layoutActions.ts#L395

So if there is no other keybinding attached to escape it might eat it.
We can disable the keybinding when you are in a terminal

**Comment by Tyriar** [comment] 2019-11-20 15:05
@isidorn yep, it's happening because `enterChord` is true here:

https://github.com/microsoft/vscode/blob/6d88ff32b2c1880726cb81c67e7b16d71ff75a4a/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L592-L593

Adding `!terminalFocus` to that chord seems like a good fix for this.

If you're having trouble reproducing you can run the toggle escape sequence logging command and compare the output when in zen mode and out (should not fire on the first esc in zen mode).

**Comment by isidorn** [comment] 2019-11-20 15:14
Due to workbench layering I can not reach out to the terminal contexts. 
The real issue seems to be that you are not using command, but are attaching a keyboard event handler straight up. Otherwise if we had a command there for every key press it would take priority over the zen mode command.

I am open for ideas on how to tackle this

**Comment by Tyriar** [comment] 2019-11-20 15:41
@isidorn that's just how the terminal works, any keypress needs to be sent over in this way. It's impractical to create a command for every single "keybinding" that a terminal would use, that's why `commandsToSkipShell` exists.

I guess to avoid layering problems the terminal can just ignore escape chords in the same way it special cases tab in tab focus mode and alt+f4 on windows:

https://github.com/microsoft/vscode/blob/6d88ff32b2c1880726cb81c67e7b16d71ff75a4a/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L598-L606

**Closed** 2019-11-20 15:50 UTC
Labels: bug, integrated-terminal, workbench-zen

**Comment by isidorn** [comment] 2019-11-20 15:55
Thanks for fixing this.
Hmm we have a command for every single keybinding that the editor uses. Though I understand this might be inpractical in the terminal.

**Comment by Hubro** [comment] 2019-11-20 16:24
@Tyriar is there a keybind I can set on my current vscode version to fix this right now, without waiting for the next version to be released?

**Comment by isidorn** [comment] 2019-11-20 16:31
@hubro You can use insiders vscode from tomorrow
Or you can disable `workbench.action.exitZenMode` keybinding in the Keybindings Editor

**Comment by Tyriar** [comment] 2019-11-20 18:32
> Hmm we have a command for every single keybinding that the editor uses.

@isidorn for the terminal we're not running commands though, we're sending over all keystrokes that may or may not be used by the terminal. Doing so would involve adding terminalFocus keybinds for:

- ctrl+a-z
- ctrl+shift+a-z
- alt+a-z
- The above with all punctuation as well
- etc.

The keybind system is sort of flipped around in the terminal where everything goes to be evaluated by xterm.js (of which we don't get a response back), bypassing vscode's keybinding system, unless it's part of a command whitelist. Additionally to the root of this issue, chords don't tell us which command would get triggered, only that it's entering chord mode.

**Comment by isidorn** [comment] 2019-11-20 18:58
Ok, thanks for the explanation
