### ISSUE TITLE
When hovering an explorer folder or file with zoomlevel: -1, the tooltip is huge

### ISSUE THREAD

**Issue by rafaelramalho19** [Microsoft/vscode#31054] opened 2017-07-19 16:05 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-docker|Pet|0.0.16
php-formatter|Sop|0.2.4
vscode-caniuse|aka|0.5.3
Handlebars|and|0.2.0
vscode-database|baj|1.2.0
vscode-twig-pack|baj|1.0.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
vscode-instant-markdown|dba|1.2.1
divider|din|1.1.0
githistory|don|0.2.1
jquerysnippets|don|0.0.1
vscode-style-formatter|dwe|1.0.0
vscode-babel-coloring|dza|0.0.4
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.11
php-intellisense|fel|1.4.3
canvas-snippets|hol|0.3.1
phpcs|ika|0.7.0
vue|jcb|0.1.5
docthis|joe|0.4.7
language-polymer|jon|1.0.3
php-symbols|lin|2.1.0
vscode-doiuse|mrm|1.4.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.1.6
vetur|oct|0.9.1
polymer-ide|pol|0.5.0
nightwatch-js-snippets|san|0.2.0
twig-for-craft-2|sel|0.5.0
stylelint|shi|0.27.0
sockscode-vscode|shy|0.0.3
svg-snippets|sid|1.0.1
language-stylus|sys|1.7.3
vscode-input-sequence|tom|0.2.0
gitblame|wad|1.11.3
vscode-todo-highlight|way|0.5.8
twig|wha|1.0.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Set "window.zoomLevel": -1 in settings.json
2.Hover an explorer folder/file
3. Look at the text

Video:
https://cl.ly/1u213G0i0q1J

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2017-07-20 07:49
I think this is just how electron behaves, @bpasero not sure if we can do something here, since that is just the size of the native hover

**Comment by isidorn** [comment] 2017-10-27 07:42
@rafaelramalho19 can you try reproducing this with latest vscode insiders 
https://code.visualstudio.com/insiders/

**Comment by rafaelramalho19** [comment] 2017-10-27 09:52
Everything seems fine @isidorn, thank you 🎉

**Comment by isidorn** [comment] 2017-10-27 10:52
Great, thanks for checking, thus I am closing

**Closed by isidorn** 2017-10-27 10:52 UTC
Labels: needs more info, workbench
