### ISSUE TITLE
Opening terminal in a new window

### ISSUE THREAD

**Issue by teshnizi** [microsoft/vscode#213200] opened 2024-05-22 03:36 UTC
Hi,

I usually use a separate monitor when coding, so I have access to both my laptop's screen and a monitor. I'd like to detach the terminal into a new window and move it to my laptop monitor, and have the editor on the external monitor. I know I can use the system terminal, but I prefer VSCode's terminal. Is this feature requested/implemented before?

**Comment by ArturoDent** [comment] 2024-05-22 03:51
Look at the `Terminal: Move Terminal into a New Window` command.  You can then drag that floating terminal window where you want it.

**Comment by pktiuk** [comment] 2024-06-04 18:13
This seems to be a duplicate of: https://github.com/microsoft/vscode/issues/210237

Currently, simple workaround is setting `"terminal.integrated.defaultLocation": "editor",` and moving terminal tab into the new window.

**Closed** 2024-12-18 19:14 UTC
