### ISSUE TITLE
code-insiders: pasting`AWS::*, Alexa::*, and Custom::*.` into a markdown file converted to a link

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#188440] opened 2023-07-21 00:53 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```sh
1.81.0-insider
daf9647eec0867d7bc32d935478fec4bd9de1f56
x64
```
- OS Version: 
```sh
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

```
Steps to Reproduce:

1.  open vscode
2. paste `AWS::*, Alexa::*, and Custom::`
3. it returns this `[Title](AWS:%253A%252A%252C%2520Alexa%253A%253A%252A%252C%2520and%2520Custom%253A%253A)`

**Comment by MeghanKulkarni** [comment] 2023-07-21 17:09
duplicate of https://github.com/microsoft/vscode/issues/187201

**Closed by MeghanKulkarni** 2023-07-21 17:09 UTC
