### ISSUE TITLE
Salsa: Not effectively using suggestion icons

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2425] opened 2016-01-27 10:33 UTC
Testing #2218

![image](https://cloud.githubusercontent.com/assets/5047891/12610786/ce4c15da-c4e9-11e5-881c-9ec51d344a9e.png)

**Comment by alexandrudima** [comment] 2016-01-27 13:25
Also interesting: suggestions on `console.` shows them as methods which is good:

![image](https://cloud.githubusercontent.com/assets/5047891/12614667/b0f6a7bc-c501-11e5-988f-9f9099ba0871.png)

But suggestions on a commonjs module shows everything again using the blue brick icon:

![image](https://cloud.githubusercontent.com/assets/5047891/12614689/c9dca5d8-c501-11e5-977f-6fd9ca45201a.png)

**Comment by egamma** [comment] 2016-01-27 16:37
Duplicate of #2169

**Closed by egamma** 2016-01-27 16:37 UTC
