### ISSUE TITLE
`~` symbol is misinterpreted with cli usage on Windows

### ISSUE THREAD

**Issue by vasily-codefresh** [microsoft/vscode#86856] opened 2019-12-12 23:54 UTC
- VSCode Version: 1.41.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. `code ~/test-file`
2. save the file

you might expect that the file is saved to `%HOME%\test-file`, but it's saved in `%HOME%\~\test-file`

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2019-12-13 18:02
@vasily-codefresh What terminal are you using within VSCode to do this? (bash, powershell, etc.?) Does running the same thing in that terminal outside of VSCode work?

**Comment by vasily-codefresh** [comment] 2019-12-13 18:35
@RMacfarlane PowerShell here (bash would expand `~` itself, so I believe it's not a problem there).

yes, behaviour is the same when running this command both inside PowerShell's terminal and VSCode's terminal.

**Comment by aeschli** [comment] 2019-12-17 09:11
It looks like powershell resolves `~` for built-in commands, but doesn't expand it when calling executables. `notepad.exe ~/test.txt` will also fail.

`~` is a valid file name in Windows, so IMO we shouldn't try to do resolving on the input paths in VSCode.
@bpasero Agree?

**Comment by bpasero** [comment] 2019-12-17 09:18
@aeschli we should only resolve "~" on Linux and macOS to my knowledge for that reason. Though people have asked to support "~" on Windows too, but I am not a big fan of that.

**Comment by vasily-codefresh** [comment] 2019-12-17 10:33
@aeschli well, technically `~` is a valid path on Linux/MacOS as well, pattern `filename~` is one widespread example of using it.

however, when we write it at the beginning of the file path, user expects it to be home directory.

**Comment by vasily-codefresh** [comment] 2019-12-17 10:44
@aeschli p.s. I get the point that this is PowerShell's problems. if that's something that can be fixed in upcoming PS 7 before it hits the street, I think, no need to work around this problem in vscode.

I see that you actually work in MS, could you please ping PS team to know if they plan to fix this (and try to convince them that centralized fix is always better than hacks in every app)? thanks

**Comment by aeschli** [comment] 2019-12-17 11:16
Although I work for Microsoft, I don't know the Poweshell team nor do I know whether this is the intended behaviour or a bug.
I saw you filed it directly against the Powershell team, that's the best way. Thanks!

**Closed by aeschli** 2019-12-17 11:16 UTC
Labels: needs more info

**Comment by vasily-codefresh** [comment] 2019-12-17 11:18
nonono, please don't close it, unless there's a confirmation from the PS team that they will fix it.
unless they do this, we still have a problem in vscode.

**Comment by aeschli** [comment] 2019-12-17 11:20
As mentioned, I don't think VSCode should try to be smart and massage the command line input.
`~` is also a valid file name.

**Comment by vasily-codefresh** [comment] 2019-12-17 11:25
well, to be frank, using `~/` at the beginning of file path as `current directory/~/` is confusing at least. nobody wants this exact behavior. it would be good if this could be fixed on the PowerShell side though, but if not, it's a vscode problem (really, it's weird to hear that powershell + vscode is not a supported environment). let's wait what the PS team says.
