### ISSUE TITLE
Generate current effective value when customizing a workbench color

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#163145] opened 2022-10-10 06:14 UTC
It would be nice for the auto-complete to generate the current effective color instead of `#ff0000`. Most of the times my intent is to tweak the existing color, and this would also help in cases when we expect a transparent color to be supplied, the auto-completed one could have transparency set.

e.g.

https://user-images.githubusercontent.com/5047891/194807285-56e94f6b-7b80-48d9-b955-d3ed1e73156b.mp4

**Comment by aeschli** [comment] 2022-10-10 10:02
duplicate of https://github.com/microsoft/vscode/issues/25633

**Closed by aeschli** 2022-10-10 10:02 UTC
