### ISSUE TITLE
HTML preview using old css code after cache deleted

### ISSUE THREAD

**Issue by Tony-65** [microsoft/vscode#230893] opened 2024-10-09 10:17 UTC
Type: <b>Bug</b>

I am having problems with your preview in google and bing

My html footer is showing as an old design in google and bing preview.
I have deleted my history/cache for google and chrome but there doesn't seem to be a way to do it in VSC (I'm also not sure that this is the problem).

In CSS My old version shows in the preview
.box-1 {background-color: lightgrey;}

My new version which doesn't show is
.box-1 {background-color:  rgb(152, 250, 119)}

In google inspect both show but the rgb version is crossed out.

I am also having problems in that any HTML div that I have wiht headings and text will show headings (H1 etc) but notshow any text between <p> and </p> in the google or chrome preview.

It works now but I had to rewrite the text using <span> and then swap to <p> etc

Hopefully, I've attached a screen shot of the issue. The top CSS code refers to reasons.css That no longer exists and I have cleared my browswer 
cache.

The bottom css version is the one that I am using. It is all crossed out. 

If I comment out the link to reasons.css in the html file the page footer shows as it should with the  rgb background

I've tried to attach a screen print in github but it's not showing as uploaded.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.85GB (1.01GB free)|
|Process Argv|--crash-reporter-id 62864781-2b81-40ef-aa71-e35f3b665033|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1:31151523
5fd0e150:31146321

```

</details>

![Image](https://github.com/user-attachments/assets/c89d0f5d-f584-4002-9e98-5fd8aba8e861)

**Comment by aeschli** [comment] 2024-10-24 15:57
Is this a duplicate of https://github.com/microsoft/vscode/issues/230895 ?

**Closed** 2024-10-24 15:57 UTC
