### ISSUE TITLE
When I save my js file, vs code format my source code,It is so bad

### ISSUE THREAD

**Issue by advxp** [Microsoft/vscode#14367] opened 2016-10-25 08:57 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: lonefy.vscode-JS-CSS-HTML-formatter-0.2.1

Steps to Reproduce:
When I save my js file, "vs code" format my source code,It is so bad.
Like so:
[
    'text'
    , 'radio'
    , 'checkbox' 
].forEach

When I hit ctrl + s,code format like this below:
[
    'text', 'radio', 'checkbox'
].forEach

**Comment by waderyan** [comment] 2016-10-25 13:46
@advxp thank you for opening this issue. It looks like you have a formatter extension installed. Can you uninstall the extension and try again? If the issue is for the extension please open this issue in the extension's repo.

**Comment by waderyan** [comment] 2016-11-21 23:24
Closing until more info is obtained.

**Closed by waderyan** 2016-11-21 23:24 UTC
Labels: format, js
