### ISSUE TITLE
vscode insiders no response and  crumbles

### ISSUE THREAD

**Issue by cl1933404370** [microsoft/vscode#132315] opened 2021-09-04 01:59 UTC
Issue Type: <b>Bug</b>

copying  Settings - 
javascript.inlayHints.variableTypes,
typescript.inlayHints.variableTypes,
javascript.inlayHints.parameterNames,
typescript.inlayHints.parameterNames,
or others setting about typescript/javascript

paste into vscode insiders 

vscode insiders  can  no response and  crumbles

VS Code version: Code - Insiders 1.61.0-insider (87260247dc7b912db6e6a21a366e6f50dca759ba, 2021-09-03T20:58:36.778Z)
OS version: Windows_NT x64 10.0.22449
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (5.18GB free)|
|Process Argv|--crash-reporter-id bec8631b-db86-4595-8087-fe4f83e59785|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
codespaces|Git|1.0.4
copilot|Git|1.4.2586
vscode-pull-request-github|Git|0.30.0
vscode-pull-request-github-insiders|Git|2021.9.1985
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.15.6
vscode-leetcode|Lee|0.18.0
vscode-squirrel|mar|0.0.14
vscode-squirrel-linter|mar|0.0.10
fluent-icons|mig|0.0.12
vscode-squirrel-lang|mon|0.0.13
vscode-docker|ms-|1.16.1
vscode-language-pack-zh-hans|MS-|1.60.2
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
github-issues-prs|ms-|0.9.3
makefile-tools|ms-|0.2.2
powershell-preview|ms-|2021.8.3
test-adapter-converter|ms-|0.1.2
vscode-github-issue-notebooks|ms-|0.0.106
vscode-typescript-next|ms-|4.5.20210903
vetur|oct|0.34.1
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
code-spell-checker|str|2.0.4
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30361752
pydsgst2:30361790

```

</details>

**Comment by IllusionMH** [comment] 2021-09-04 03:15
Are you searching for these in settings editor?

Looks like duplicate of #132250

**Comment by cl1933404370** [comment] 2021-09-04 03:50
> Are you searching for these in settings editor?
> 
> Looks like duplicate of #132250

yes, like duplicate of #132250. No respond when typing "typescript" in Settings page, after using a lot of memory or Prompting to restart.

**Comment by Elias-Graf** [comment] 2021-09-04 10:26
@cl1933404370 you should close the issue if it's a duplicate 😊

**Closed** 2021-09-04 12:26 UTC
