### ISSUE TITLE
collapsing and expanding c functions doesn't work well if the file is 1200 lines long

### ISSUE THREAD

**Issue by SecretAgent0094** [microsoft/vscode#212093] opened 2024-05-06 12:35 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

Extensions:
C/C++
C/C++ Extension Pack
C/C++t Themes
Cmake
Cmake Tools
Dev Containers
ESP-IDF
Makefile Tools
PHP Intelephense
Pylance
Python
Python Debugger
Rainbow CSV
Remote - SSH
Remote - SSH : Editing Configuration File
 Remote Explorer
vscode-pets
Power Mode

Steps to Reproduce:
[Registrazione 2024-05-06 143157.zip](https://github.com/microsoft/vscode/files/15220605/Registrazione.2024-05-06.143157.zip)

1. Open a big file of the project
2. Try to find arrow to collapse c function 
3. try to collapse all with Ctrl+0
4. try to expand all with Ctrl+J

**Comment by aeschli** [comment] 2024-05-07 08:17
Can you explain what doesn't work well? Or maybe provide the file?
From the video it's unclear to me what the problem is.

**Comment by SecretAgent0094** [comment] 2024-05-07 08:44
Hi thanks for the support.
The arrows to the left of the lines, which are used to expand or collapse the functions, disappear when I work on files of more than 1200 lines and consequently I can no longer cover them and expand the functions.
The commands CRTL+K CRTL+0 and CRTL+K CRTL+J also don't seem to work.
However, in files with fewer lines this does not happen.
In the video, first I show you that it doesn't work in the 1200 line file, I also try to run the commands, but they don't work, then I show you the same thing in a shorter file where it works.
I can't understand if this depends on the ESP-IDF extension or is it a small vscode bug that appears with very long files.

Unfortunately I cannot share the file with you.

**Comment by aeschli** [comment] 2024-05-07 09:02
There is a maximum number of folding regions which is by default 5000. The setting `editor.foldingMaximumRegions` configures that. But I don't think you hit that as it would show on the status bar as a warning.
You have the C++ extension installed, so the folding mrkers are coming from that extension.
If you don't see the folding markers, that means that maybe the file could not be parsed correctly? It could also be an issue in the C++ extension.

There's not much I can help with unless we have a reproducible example...

**Comment by SecretAgent0094** [comment] 2024-05-08 06:57
Thanks for the info, I tried opening the file individually instead of from within the project and all the expand arrows appear and work, so the problem is probably project dependent.
Unfortunately, since it is a project for the company I work for, I cannot share it.
For me it's not a blocking issue, my report was only intended as feedback to help find a bug.
If you want you can also close the issue.
Thanks again and good work

**Comment by aeschli** [comment] 2024-05-08 07:59
Maybe it's related to macros? Mayb by commenting out some code you can find out what could cause the issue. The issue is likely in the C++ extension, which computes the folding markers here. The issue should go there but, again, without a reproducible case it's difficult for us to help. 

Sorry for not being of great help. Closing the issue.

**Closed by aeschli** 2024-05-08 07:59 UTC
Labels: info-needed
