### ISSUE TITLE
Reload extension button never goes away

### ISSUE THREAD

**Issue by vavans** [Microsoft/vscode#19685] opened 2017-02-01 18:51 UTC
- VSCode Version: 1.8.1
- OS Version: Linux Mint (same issue on windows 8)

Steps to Reproduce:

1. On a fresh, new installation of VSCode, install the hello plugin : `ext install hello`
2. Click the reload button, the extension is loaded correctly, everything is fine
3. Goto ~/.vscode/extensions/hypnoes.hello-0.1.1 
4. Open package.json 
5. Change lines
```json
	"name": "hello",
	"displayName": "Hello",
```
to

```json
	"name": "Hello",
```

uppercase Hello.

6. Launch VSCode and go to extensions tab
7. The reload button is shown in Hello extension (and will never goes away) but the extension is loaded and works perfectly well

**Comment by sandy081** [comment] 2017-02-03 12:49
This is not related to #19753. This does not load only this particular extension.

**Comment by vavans** [comment] 2017-02-03 14:16
I used this extension as the simplest sample available. But the issue is the same whaterver the extension is used:
Using an extension name with uppercase, without a displayname field, triggers the behaviour

**Comment by sandy081** [comment] 2017-02-10 08:22
@vavans Can you please check if you are able to reproduce it on our insiders build. Looks like it got fixed.

**Comment by johnpapa** [comment] 2017-02-14 02:02
Please re-open as this is an issue with https://github.com/johnpapa/vscode-angular2-snippets/issues/40

cc @chrisdias

**Comment by sandy081** [comment] 2017-02-14 15:55
Found the root cause: Market place is giving a different name for this extension. Market place is having the name of the extension as `Angular` but in its `package.json` it is `angular`.  

In stable, this extension shows it is installed but not running (even though it is running), because installed check is done on `id` and running check is done on `publisher.extensionName` which is different because of market place sending different data.

In insiders, we made a fix for #17290 that checks always are based on `publisher.extensionName`. So this makes this extension not installed from market place due to the above identifier mismatch. Hence reload button is not shown. 

But still there is an issue that local installed extension is not getting mapped with market place extension which leads to issues in detecting updates etc., 

@joaomoreno Any idea why market place is sending different extension name? And is there a workaround for extensions to fix this from their side?

**Comment by sandy081** [comment] 2017-02-21 11:20
Further analysis on this:

VSCE creates a new extension if name is changed because it does not exist in Market place. But Market place is sharing the same UUID for extensions (old and new names). This is causing the for all this confusion. So right solution is to get it fixed in Market place.

**Comment by sandy081** [comment] 2017-03-01 23:50
Adopted VS Code to be resilient with case changes in extension names.

All extension ids `publisher.name` are made case insensitive by lowering the case of `name`.
- gallery 
- local extension
- enablement/disablement
- dependencies
- extension (extension host)

So all above extension interfaces can use strict equals on ids.
Extension id exposed to users (Extension editor, API) will be always same and consistent. 

## Adoption for Extensions
This will impact those extensions using following API in `vscode.d.ts` and doing strict equality check like us. They should lower the case of `name` and do an equality check with Extension.id.
```
Extension.id
```

**Closed by sandy081** 2017-03-01 23:50 UTC
Labels: bug, extensions, marketplace

**Comment by Krzysztof-Cieslak** [comment] 2017-03-02 21:34
As far as I can tell this impact also `extensions.getExtension` calls.

**Comment by sandy081** [comment] 2017-03-03 08:00
@Krzysztof-Cieslak That's a good catch. This api should not be impacted. Since `name` is case insensitive `extensions.getExtension(id)` should support it. 

So `extensions.getExtension('vscode.go)` or `extensions.getExtension('vscode.GO)` should return the extension which is same.

Fixed it. Thanks for mentioning it.

**Comment by sandy081** [comment] 2017-03-03 10:27
I had to revert the changes done in extension host (making id lower case) because it breaks usage of following:

- Storage path
- Mementos

Hence, I reverted id of Extension in Extension host (vscode.d.ts) to be same as before. It means no lowering of case is done. Id of extension will change if the extension author changes the case of the name. 

Adopted at other places in VS Code to use a equality function to compare with extension descriptions.
