### ISSUE TITLE
Introduce an experimental modal walkthrough for web experiences

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#171190] opened 2023-01-12 18:11 UTC

**Comment by bhavyaus** [comment] 2023-01-12 18:41
Related: https://github.com/microsoft/vscode/issues/166895

**Comment by Mumduekndbn** [comment] 2023-02-02 03:48
Duplicate of #

**Comment by Mumduekndbn** [comment] 2023-02-02 03:48
https://github.com/microsoft/vscode/issues/171190#issuecomment-1380853928

**Comment by bhavyaus** [comment] 2023-03-16 19:54
Current Progress:
- We have enabled an experimental modal dialog to be used for gathering feedback.

- Previous studies conducted to test this feature have concluded that users often did not engage with a modal walkthrough. 
See https://github.com/microsoft/vscode/issues/106717#issuecomment-790053982

- One of the issue we would need to address if we do decide to use welcome dialogs for web experiences is users encountering back-to-back modal dialogs - because GitHub Repositories triggers the modal dialog sign in flow for first-time users. 

- Some of the ideas under consideration for this scenario are:
1.  Surfacing the welcome information as a notification instead of modal dialog. 
![image](https://user-images.githubusercontent.com/25044782/225736700-6280c8b8-f9c5-4269-8305-439237a39d38.png)

2.  Sequentially surfacing the welcome modal followed by other setup modals to establish a "welcome flow" to get users to a ready state.

 <img width="446" alt="image" src="https://user-images.githubusercontent.com/25044782/225736841-d731338a-b854-46d2-b7bd-d2055d05f0d8.png">

 followed by

 <img width="345" alt="image" src="https://user-images.githubusercontent.com/25044782/225736941-8a1125b1-fc25-45b7-9f19-bd62eae948be.png">

3. Incorporating setup modal actions (such as sign-in) as a part of the welcome dialog itself and have a singular blocking modal dialog. 

<TBD Mock Up>

4. An intermediate page before loading the actual app - 
![image](https://user-images.githubusercontent.com/25044782/225737804-a8804784-e749-4809-bb19-25cdbf8275cb.png)

**Comment by sandy081** [comment] 2023-04-27 07:37
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.

**Comment by bhavyaus** [comment] 2023-05-31 17:21
We've now added an experimental https://github.com/microsoft/vscode/issues/179401 contextual welcome widget in the editor on the web for new users. We will monitor its usage to determine the usefulness of this model of interaction for welcome experiences on the web.

![image](https://github.com/microsoft/vscode/assets/25044782/424dc3b8-cd23-41ea-b2f8-460585012900)

**Comment by bhavyaus** [comment] 2023-08-04 16:49
We have rolled out a non modal experimental dialog. We will track the experiment metrics in the coming weeks.

**Closed** 2024-01-25 15:43 UTC
Labels: feature-request

**Comment by rzhao271** [comment] 2024-01-25 20:01
Hi @bhavyaus, what are some verification steps for this issue?

**Comment by rzhao271** [comment] 2024-01-25 22:46
Confirmed this is being tracked elsewhere now
