### ISSUE TITLE
 Cannot read property '$isError' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38751] opened 2017-11-20 06:46 UTC
Issue Id: <b>82d5a163-11cf-c65f-1fb3-88f3c541adbb</b><br /><br />*Versions* <br />- 1.18.1<br />*Stack* <br />TypeError: Cannot read property '$isError' of null<br />[/vs/workbench/api/electron-browser/mainThreadErrors.ts#L19:10 ($isError)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/api/electron-browser/mainThreadErrors.ts#L19:10 ($isError))<br />[/vs/workbench/services/thread/node/abstractThreadService.ts#L41:16 (apply)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/services/thread/node/abstractThreadService.ts#L41:16 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L109:39 (invoke)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L109:39 (invoke))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L96:36 (_invokeHandler)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L96:36 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L32:65 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L32:65 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L157:4 (onMessage)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L157:4 (onMessage))<br />[/vs/base/common/callbackList.ts#L36:22 (apply)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/base/common/callbackList.ts#L36:22 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/base/parts/ipc/node/ipc.net.ts#L82:22 (fire)](https://github.com/microsoft/vscode/blob/929bacba01ef658b873545e26034d1a8067445e9/src/vs/base/parts/ipc/node/ipc.net.ts#L82:22 (fire))<br />    at emitOne (events.js:96:13)<br />

**Comment by alexandrudima** [comment] 2018-04-18 22:01
Duplicate of #43052

**Closed by alexandrudima** 2018-04-18 22:01 UTC
Labels: bug, error-telemetry
