### ISSUE TITLE
The powershell program keep opening in the background

### ISSUE THREAD

**Issue by sondragon** [Microsoft/vscode#60719] opened 2018-10-12 03:04 UTC
- VSCode Version: 1.29.0-insider(user setup)
- OS Version: Windows 7 x64 Professional SP1

Steps to Reproduce:
In my cash, when you debug a node problem, it will open sereral powershell programs, but it won't close itself when I stop debuging. Do it more times the Code has to reopen after tens of powershell programs are running in the background because of the RAM had run out. 

Does this issue occur when all extensions are disabled?: No extensions installed

**Comment by egamma** [comment] 2018-10-12 13:47
duplicate of #60585

**Closed by egamma** 2018-10-12 13:47 UTC
Labels: insiders, needs more info
