### ISSUE TITLE
Regression in completion provider

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#17911] opened 2016-12-29 18:55 UTC
This is driving me crazy. Must be a recent regression.

Source Code:
```ts
export interface IMode {
	getId(): string;
	getLanguageIdentifier(): string;
}

let a: IMode;
let v = a.getId();
```

Steps:
* ctrl+space
* arrow down
* enter

Actual:
![completion-actual](https://cloud.githubusercontent.com/assets/5047891/21552268/15ee19aa-ce09-11e6-906e-4f8a026baf49.gif)

Expected:
![completion-expected](https://cloud.githubusercontent.com/assets/5047891/21552235/eaae2dca-ce08-11e6-8ee8-32202e9f6181.gif)

**Comment by mjbvz** [comment] 2016-12-29 22:44
Duplicate of #17906. Have pr out with fix

**Closed by mjbvz** 2016-12-29 22:44 UTC
Labels: duplicate
