### ISSUE TITLE
Vertical scrolling is staggered

### ISSUE THREAD

**Issue by maryam-a** [Microsoft/vscode#34656] opened 2017-09-19 19:49 UTC
- VSCode Version: 1.16.1
- OS Version: Windows 10 Pro (1703)

Steps to Reproduce:

1. Scroll through any file using touchpad.

Reproduces without extensions:

**Comment by alexandrudima** [comment] 2017-09-20 14:04
Duplicate of #13612

**Closed by alexandrudima** 2017-09-20 14:04 UTC
Labels: editor, new release
