### ISSUE TITLE
Create environment variable within user/workspace settings

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#18709] opened 2017-01-18 09:17 UTC
It would be great if you could define variables (and/or environment variables) within the user/workspace settings.

Example: 

```json
{
    "variables": {
        "MY_VAR": "foo"
    },
    "environment_variables": {
        "MY_ENV_VAR": "bar"
    },

    "some_first_setting": "${var.MY_VAR}",
    "some_second_setting": "${env.MY_ENV_VAR}"
}
```

I have the same path typed multiple times in my settings, and if I wish to change it, I have to change the path in multiple places. This feature request could enable more complex settings as you could use paths based on variables.

I'm also keeping my fingers crossed that  [settings overrides](https://github.com/Microsoft/vscode/issues/1587#issuecomment-273397301) will be implemented and that both such overrides as well as defining variables could enable something like this:

```json
{

    "environment_variables": {
        "CONDAENVS": "${workspaceRoot}../condaenvs"
    },

    "windows": {
        "python.pythonPath": "${env.CONDAENVS}/env_win/",
        "window.zoomLevel": -0.001
    },
    "osx": {
        "python.pythonPath": "${env.CONDAENVS}/env_osx/"
    }
}
```

Note: the `python.pythonPath` setting is part of the [PythonVSCode extension](https://github.com/DonJayamanne/pythonVSCode) and here's my feature request to have this extension support python settings based on platform: https://github.com/DonJayamanne/pythonVSCode/issues/644

**Comment by dbaeumer** [comment] 2017-01-19 08:00
@sandy081 assigning to you as the new settings master :-)

**Comment by nsgundy** [comment] 2017-11-16 08:04
What I'd be looking for here is that not only would these environment variables be available to settings anywhere (for example to be used in include-path resolving for the c++ extension), but also passed to anything that gets spawned by VSCode, for example the terminal or any of the tasks. Should be settable per OS.

**Comment by sandy081** [comment] 2017-11-20 08:36
Duplicate of #2809

**Closed** 2017-11-20 08:36 UTC
Labels: *duplicate, config, feature-request
