### ISSUE TITLE
Replace popup does not display Replace field correctly. 

### ISSUE THREAD

**Issue by BradL-Msft** [microsoft/vscode#126946] opened 2021-06-23 02:31 UTC
Issue Type: <b>Bug</b>

Open VS Code.
Create a foo.c text file
ensure file has multiple words
double-click a word to select it
press Control+H to bring up the replace dialog.

The find/replace dialog appears.  The selected word is in the find field.
The replace field does not read "replace" as normal.  It has a blue border and shows no text.  Just typing (after Ctrl+H), or clicking on the Replace field and typing on it does not display what you are typing. 

Click outside the Replace box and the border will disappear and the content that was typed will appear.

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:15:24.214Z)
OS version: Windows_NT x64 10.0.22409
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.51GB free)|
|Process Argv|--crash-reporter-id aff42cce-a2c7-43e4-8e3e-8a0af51e772e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.9.2
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.7.960048241
cpptools|ms-|1.5.0-insiders2
asn1vcx|OSS|1.4.1
vscode-hexdump|sle|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805:30301674

```

</details>
![image](https://user-images.githubusercontent.com/49081806/123026052-6b119d80-d390-11eb-8e11-7b944538efa0.png)

**Comment by yume-chan** [comment] 2021-06-23 06:29
Duplicate of #126896

**Comment by s1ssagar** [comment] 2021-06-23 07:22
The issue was fixed in an update thanks.

**Closed** 2021-06-23 22:19 UTC
