### ISSUE TITLE
Can't accept suggestion with tab

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#111148] opened 2020-11-22 23:05 UTC
- Set `"emmet.triggerExpansionOnTab": true`
- Open some .ts file, trigger suggestions, press tab
- I expect it to accept the current suggestion, but it just inserts a tab instead

I see that it's running `editor.emmet.action.expandAbbreviation` every time I press tab in the editor, I don't know it worked before but seems probably related to https://github.com/microsoft/vscode/pull/110891

**Comment by AjahnCharles** [comment] 2020-11-23 03:11
I'm seeing the same broken behavior for all types of suggestion (also while programming TS): fields, methods, tabnine...

❌ Affected version (broken):
```
Version: 1.52.0-insider
Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
Date: 2020-11-20T07:35:38.417Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
✅ Confirmed that behavior is correct (not broken) in my stable version:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by rzhao271** [comment] 2020-11-23 16:28
Duplicate of https://github.com/microsoft/vscode/issues/111119

**Closed by rzhao271** 2020-11-23 16:28 UTC
