### ISSUE TITLE
"Go to Symbol in Workspace" doesn't find typescript symbols if no .ts file is open

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#32054] opened 2017-08-05 20:51 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. open a folder containing .ts files
2. open a .ts file
3. "Go to Symbol in Workspace"..  for some existing symbol eg. "#a" - it works.
4. close all '.ts' files.
5. repeat step 3. nothing found.

Reproduces without extensions: Yes

**Comment by eamodio** [comment] 2017-08-07 13:26
Duplicate of https://github.com/Microsoft/vscode/issues/17022

**Closed** 2017-08-07 15:29 UTC
Labels: duplicate, typescript
