### ISSUE TITLE
The Terminal window doesn't handle correctly long commands entered at the last line of the terminal

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode#117917] opened 2021-03-01 19:20 UTC
Issue Type: <b>Bug</b>

In the Terminal window, when I'm at the last line and I'm entering a command which is too long for the line itself,  instead than adding a new line, the terminal adds the new text to the  beginning of the current line. This makes the command unreadable.

![image](https://user-images.githubusercontent.com/8233615/109547221-68322a80-7acb-11eb-964d-12f85cac852d.png)

Why doesn't the terminal just add a new line below the current one? Also, why the bizzarre "ghost effect" to the right?

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.15.0-135-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.19GB free)|
|Process Argv|--crash-reporter-id df4f7917-f728-4290-9500-a3632318c3e7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dgx-01|
|OS|Linux x64 4.15.0-135-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2569)|
|Memory (System)|503.79GB (314.64GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
gc-excelviewer|Gra|3.0.41
vscode-docker|ms-|1.10.0
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.603412351
json|Zai|2.0.2

</details>

**Comment by meganrogge** [comment] 2021-03-01 22:44
Duplicate of #116174

**Closed** 2021-03-01 22:54 UTC
Labels: *duplicate
