### ISSUE TITLE
Can't delete file/folder in sidebar explorer with press [delete] or [shift+delete] key

### ISSUE THREAD

**Issue by fajaryanw** [microsoft/vscode#76582] opened 2019-07-04 09:47 UTC
Issue Type: <b>Bug</b>

In sidebar explorer, When focus to a file/folder If I pressed [delete] or [shift+delete] key then bring up filter with 'delete' word instead of delete a file/folder.

![Peek-2019-07-04-16-40](https://user-images.githubusercontent.com/6999559/60657323-5c680e00-9e7b-11e9-896a-846be1b127ca.gif)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.0.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2812)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.68GB (1.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
dart-code|Dar|3.2.0
flutter|Dar|3.2.0
githistory|don|0.4.6
vscode-docker|ms-|0.6.4
code-settings-sync|Sha|3.3.1

</details>

**Comment by jrieken** [comment] 2019-07-04 09:51
/duplicate of https://github.com/microsoft/vscode/issues/76514

**Closed** 2019-07-04 09:51 UTC
Labels: *duplicate, new release
