### ISSUE TITLE
Add Visual Studio's Edit.SelectCurrentWord functionality

### ISSUE THREAD

**Issue by wasker** [microsoft/vscode#92959] opened 2020-03-18 18:52 UTC
Hi all,

The closest to Visual Studio's Edit.SelectCurrentWord (Ctrl-W or Ctrl-Shift-W, depending on your settings) is VSCode's Ctrl-D, however, it has its own idea of word boundary (not compatible with Ctrl-Left/Ctrl-Right, for example), and multiple presses adds more selections to the editor.

I'd like to have a simple Edit.SelectCurrentWord, which selects the current word and works consistently across programming languages, unlike Ctrl-D.

Thanks.

**Comment by alexdima** [comment] 2020-03-19 16:43
Duplicate of #15774

The change is available in the Insiders channel.

**Closed by alexdima** 2020-03-19 16:43 UTC

**Comment by wasker** [comment] 2020-04-09 19:06
Available for all in 1.44.
