### ISSUE TITLE
Files treeview control displays incorrect information when scrolling while adding a new file

### ISSUE THREAD

**Issue by qmuntal** [Microsoft/vscode#26308] opened 2017-05-09 12:48 UTC
- VSCode Version: 1.12.1
- OS Version: Win10

Steps to Reproduce:

1. Open a project with a complex folder/file structure, at least big enough to fill the files treeview.
2. Select a file of a subfolder.
3. Press the "New File" icon.
4. Instead of wrtting the file's name, scroll up or down until the new file is outside the boundaries of the control.

After doing this, the "New File" command is cancelled and the tree displays files inside incorrect folders until the application is restarted.

**Comment by egamma** [comment] 2017-05-09 13:07
@qmuntal thanks for the issue report, from the description is to clear what the problem is. Can you please illustrate the problem using an animated GIF.

**Comment by King66** [comment] 2017-05-09 13:18
maybe he means this..
https://github.com/Microsoft/vscode/issues/22269

**Comment by qmuntal** [comment] 2017-05-09 14:05
@King66 is right, the issue in #22269 is what I was trying to explain.

**Comment by egamma** [comment] 2017-05-09 18:12
@King66 thanks for pointing to the duplicate issue!

Closing as a duplicate of #22269

**Closed by egamma** 2017-05-09 18:12 UTC
Labels: needs more info
