### ISSUE TITLE
Add conditional configuration

### ISSUE THREAD

**Issue by ItachiSan** [Microsoft/vscode#46421] opened 2018-03-23 13:58 UTC
Issue Type: <b>Feature Request</b>

This issue aims to lead the support for conditional configuration.

#### What is it about?
In my case (but I don't believe to be the only one) I boot many times different OSes, in which I have different folder structures (*e.g.* Linux and Windows user directory).
As an example, right now, an user can define a single time the *Python* interpreter. At every OS switch, the setting has to be updated.

#### How should it be?
As in some extensions is already supported, my idea would be to have a configuration such as:
```json
{
    // Shared part
    "someSetting": "SomeValue",
    // Windows part
    "win": {
        "someWindowsOnlySetting": "itsValue"
    },
    // Linux part
    "linux": {
        "someLinuxOnlySetting": "itsValue"
    }
}
```

#### What would lead this to?
This would allow a single-time configuration that could be shared between multiple OSes and, actually, computers (I could copy the `settings.json` file on a new computer and have all my settings).

#### Visual Studio Code details
VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

**Comment by benallan** [comment] 2018-03-24 02:28
As another person having to use various different OSes I agree, it would be really handy if this was supported. In addition to settings.json, I have the same kind of issue with keybindings.json where the mac shortcuts likely use cmd, but windows versions should use ctrl.  

What I do now is keep a separate .json file for each platform and then symlink the appropriate one, but it's a bit of a pain.

**Comment by sandy081** [comment] 2018-03-26 09:05
Duplicate of #17619

**Closed** 2018-03-26 09:05 UTC
Labels: *duplicate, config
