### ISSUE TITLE
Can u add a built in function to open a server to test and see our html code? Thanks!

### ISSUE THREAD

**Issue by Compute165** [microsoft/vscode#109801] opened 2020-11-01 05:12 UTC

**Comment by DanielFerguson** [comment] 2020-11-01 07:20
You can actually already do this with NPM packages like live-server! https://www.npmjs.com/package/live-server 
There are alternatives for other technologies (PHP, etc.) and if you use a framework like vue-cli, nuxt etc. they typically have in-built serving functionality.

**Comment by Compute165** [comment] 2020-11-02 03:35
You mean an extension?

Thanks!

**Comment by aeschli** [comment] 2020-11-02 09:38
duplicate of https://github.com/microsoft/vscode/issues/12080

**Closed by aeschli** 2020-11-02 09:38 UTC
