### ISSUE TITLE
Maximize Editor Group behavior changed

### ISSUE THREAD

**Issue by erikphansen** [Microsoft/vscode#53970] opened 2018-07-10 15:08 UTC
Issue Type: <b>Bug</b>

Before 1.25.0, it used to be that when I enabled `View: Maximize Editor Group` or `View: Maximize Editor Group and Hide Sidebar` it was like entering a "maximize focused editor group" mode, so that whichever group currently had focus would become maximized. This was a really great feature that seems to have been broken with 1.25.0 which added the (great!) new window/group arrangement options. The previous behavior allowed me to have three groups next to each other on a small laptop screen and still be able to effectively work because the file I was working with always got the lion's share of the screen. I hope this is something that can make a comeback.

<img width="633" alt="vscode-maximize" src="https://user-images.githubusercontent.com/20728956/42519092-205dcac2-8418-11e8-8edd-bad242474841.png">

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.2
fish|Ted|0.0.4
better-comments|aar|1.2.6
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
es7-react-js-snippets|dsz|1.8.3
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.5
vscode-toggle-column-selection|eri|1.0.3
open-in-marked|fmo|1.0.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
macros|ged|1.2.1
webpack|jer|2.1.0
vscode-text-pastry|jkj|1.2.0
docthis|joe|0.7.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.5.1
vscode-sort-json|ric|1.12.0
vscode-icons|rob|7.24.0
block-travel|sas|0.0.2
code-spell-checker|str|1.6.10
enumerator|swi|0.0.6
language-stylus|sys|1.9.2
vsfire|tob|1.3.2
colonize|vms|2.2.2
change-case|wma|1.0.0
JasmineSnippets|xab|1.0.1

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-07-10 15:16
Duplicate of https://github.com/Microsoft/vscode/issues/51614

You can try out the insider release to verify the fix works for you: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2018-07-10 15:16 UTC

**Comment by erikphansen** [comment] 2018-07-10 15:33
Looks great in the Insiders version. Thanks @bpasero! Apologies for posting the dupe.
