### ISSUE TITLE
Whenever I type '.', autocomplete is typed.

### ISSUE THREAD

**Issue by Sh031224** [microsoft/vscode#130660] opened 2021-08-12 08:46 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: MacOS BigSur 11.3.1

Steps to Reproduce:

1. I typed '.' several times to use the spread grammar in javascript
2. Each time I typed it, the autocomplete that appears at the top is entered

In the gif below, I only typed .
Of course disable extensions mode.

![what](https://user-images.githubusercontent.com/51149996/129167121-afe69a13-b694-4f90-aa1f-e89133da5242.gif)

**Comment by infinnie** [comment] 2021-08-12 08:47
Duplicate of #130096

**Closed** 2021-08-12 09:18 UTC
Labels: *duplicate
