### ISSUE TITLE
VS Code crashes when left idle (behaviour is inconsistent)

### ISSUE THREAD

**Issue by ritcoder** [Microsoft/vscode#2133] opened 2016-01-20 22:48 UTC
This does not happen every time it is idea but it mostly crashes at least once a day. It gets slow and then crashes. I've been using it exclusively to write elm code so I don't know if it has to do with the plugin.

How can I get detailed log next time it happens?

**Comment by Tyriar** [comment] 2016-01-21 02:12
Likely a duplicate of https://github.com/Microsoft/vscode/issues/508

**Comment by weinand** [comment] 2016-01-21 08:59
@ritcoder what OS?

**Comment by ritcoder** [comment] 2016-01-21 19:22
Using windows 10 pro (insider on the slow ring)
Code version is 0.10.6

**Comment by ritcoder** [comment] 2016-01-21 19:25
@Tyriar Yes. Looks like you might be experiencing the same issue.

**Comment by bpasero** [comment] 2016-01-22 17:45
#508

**Closed by bpasero** 2016-01-22 17:45 UTC
Labels: freeze-slow-crash
