### ISSUE TITLE
Color theme bug

### ISSUE THREAD

**Issue by peckas13** [microsoft/vscode#92419] opened 2020-03-11 04:09 UTC
Since yesterday I experiment a bug that makes the editor be unable to take the font color properly and the text turn almost as the same color and hard to read.

**Comment by IllusionMH** [comment] 2020-03-11 10:55
/needsMoreInfo

Do you have a screenshot?

What language are you using? If it's JS/TS then please check if its same as #92308

**Comment by peckas13** [comment] 2020-03-11 15:28
> 
> 
> /needsMoreInfo
> 
> Do you have a screenshot?
> 
> What language are you using? If it's JS/TS then please check if its same as #92308

Yes i´m using JS and TS and is the same issue as you send me

**Comment by aeschli** [comment] 2020-03-11 20:28
Duplicate of #92308.

**Closed by aeschli** 2020-03-11 20:28 UTC
Labels: needs more info
