### ISSUE TITLE
window.newWindowDimensions inhert sets the max dimensions to the max dimensions on main display

### ISSUE THREAD

**Issue by mwidmann** [microsoft/vscode#52568] opened 2018-06-21 08:40 UTC
- VSCode Version: latest 1.25.0-insider (have issue in regular vscode as well)
- OS Version: Windows 10 v 1803 (17134.112)

Steps to Reproduce:

1. My Setup is a Laptop with a 3000x2000 resolution scaled to 200% (resulting in 1500x1000) set as the main display and an external Display scaled to 100% set at a resolution of 2560x1440.
2. Put the window in non maximized size on the higher resolution external display and resize it to be above the resolution on the main display.
3. set `window.newWindowDimensions` to `inherit`
4. open a new window.

The new window will stack above the other one, but its dimensions won't be the same as the old window, but the max non maximized window dimension on the main display.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-06-25 13:59
I think we are getting the right state here:

https://github.com/Microsoft/vscode/blob/b038882cf7904093079555575baf8de28259c1ac/src/vs/code/electron-main/windows.ts#L1255

But maybe fail to validate the state properly here:

https://github.com/Microsoft/vscode/blob/b038882cf7904093079555575baf8de28259c1ac/src/vs/code/electron-main/window.ts#L748

And then return some default state. If someone has energy to look into this, PR welcome.

**Comment by bpasero** [comment] 2018-06-26 09:51
This seems to be an Electron issue, I verified that I am not getting right window dimensions when asking for it. This even reproduces by just opening a window, make it large and then restart.

**Comment by bpasero** [comment] 2019-10-09 05:14
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-09 05:14 UTC
Labels: electron, upstream
