### ISSUE TITLE
Support for windows magnifier

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [Microsoft/vscode#35613] opened 2017-10-05 07:55 UTC
- VSCode Version:
- OS Version: Windows 10

I'm a proud user of visual studio and VS code seems very interesting to me. However I'm low vision and because VS code doesn't support windows magnifier, I have a hard time using it. I know this is written using a none platform specific UI system and it might be hard to support windows magnifier but wanted to ask to see if it is possible or not. The issue is that the cursor for writing text is not followed by magnifier since it doesn't report to windows accessibility (UI Automation or MSAA whatever it is) its position.

Thanks for considering it

**Comment by alexandrudima** [comment] 2017-10-21 07:56
Duplicate of #7394

**Closed by alexandrudima** 2017-10-21 07:56 UTC
Labels: accessibility, workbench
