### ISSUE TITLE
Menu not respecting when clauses for actions

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#61109] opened 2018-10-17 03:15 UTC
Version: 1.29.0-insider
Commit: f151c46b1783cf4f9a4ca934a85f78846f08688e
Date: 2018-10-11T05:12:53.188Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

OS Linux Mint 19

I have the following two keybindings defined...

{ "key": "escape", "command": "workbench.action.toggleSidebarVisibility", "when": "sidebarVisible"}
{ "key": "escape", "command": "workbench.action.terminal.toggleTerminal", "when": "'workbench.panel.terminal'" },

I will use the sideBar for the following example, but the behaviour is the same for terminal, relatively.

**The Short:** With no file open in any editor, pressing escape will open the sidebar. This violates the when clause of my keybinding.

**Expected Behaviour:**
-when the sidebar is visible, pressing escape closes it.
-when the sidebar is not visible, pressing escape will not open it.

**Observed Behaviour:**
***with a file open in editor**
-when the sidebar is visible, pressing escape closes it. _(good)_
-when the sidebar is not visible, pressing escape will not open it._(good)_
***with no file open in an editor**
-when the sidebar is visible, pressing escape closes it._(good)_
-when the sidebar is not visible, pressing escape **WILL** open it. _(bad)_

**Comment by isidorn** [comment] 2018-10-23 09:35
Thanks for the nice steps. I can reproduce this. The issue here is that the main menu is not always respecting when clauses for actions in the menu. 
In this particular case notice when there are no editors open for some reason the menu executes the command, I am not sure how menu is evaluting when clauses from the main side, thus forwarding this to @sbatten 
fyi @bpasero

**Comment by sbatten** [comment] 2018-11-01 17:47
duplicate of  #35225

**Closed by sbatten** 2018-11-01 17:47 UTC
Labels: bug, workbench-menu
