### ISSUE TITLE
Java: Imports Not working 

### ISSUE THREAD

**Issue by Avinashachu007** [microsoft/vscode#76705] opened 2019-07-05 10:34 UTC
Issue Type: <b>Bug</b>

After Upgrading to the Latest version vscode, Quick Fix and Imports are  not working

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitstash|art|2.1.1
vscode-svgviewer|css|2.0.0
vscode-html-css|ecm|0.2.0
vscode-lombok|Gab|0.9.8
vscode-git-tags|how|1.4.3
thymeleaf|juh|1.0.3
git-graph|mhu|1.10.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-spring-boot|Piv|1.9.0-201906262320
java|red|0.46.0
vscode-xml|red|0.7.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5

</details>

**Comment by TKW25** [comment] 2019-07-05 16:57
It's not just importing, from the drop down option of quick fixes none of them seem to work for me.

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
OS: Windows_NT x64 10.0.16299

<details><summary>System Info</summary>
CPUs | Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.86GB (8.51GB free)
Process Argv |  
Screen Reader | no
VM | 50%
</details>

<details><summary>Extensions (13)</summary>
Extension | Author (truncated) | Version
-- | -- | --
bracket-pair-colorizer-2 | Coe | 0.0.28
vscode-markdownlint | Dav | 0.28.0
vscode-eslint | dba | 1.9.0
Go | ms- | 0.11.1
vscode-typescript-tslint-plugin | ms- | 1.2.1
java | red | 0.46.0
code-spell-checker | str | 1.7.17
vscodeintellicode | Vis | 1.1.7
vscode-java-debug | vsc | 0.20.0
vscode-java-dependency | vsc | 0.5.1
vscode-java-pack | vsc | 0.7.1
vscode-java-test | vsc | 0.18.1
vscode-maven | vsc | 0.17.1
</details>

**Comment by dbaeumer** [comment] 2019-07-06 11:43
@mjbvz starting with you since it happened after the upgrade.

**Comment by mjbvz** [comment] 2019-07-08 15:43
How are you triggering the quick fix?

**Comment by mjbvz** [comment] 2019-07-09 17:26
Duplicate of #76851

**Closed by mjbvz** 2019-07-09 17:26 UTC
Labels: needs more info

**Comment by TKW25** [comment] 2019-07-10 11:22
@mjbvz A simple example would just be writing out `public ArrayList<String> list;` in a file where ArrayList isn't imported.  I'll get the red line with the error *ArrayList cannot be resolved to a type Java(16777218)*, select quick fix and have a list of options, I click on *Import 'ArrayList' (java.util)* and nothing happens.  Nothing happens if I am to click any other options either.  This issue doesn't seem to affect other languages that I have tried (i.e. TypeScript, JavaScript).
