### ISSUE TITLE
React/JSX support for inline color highlighter and picker.

### ISSUE THREAD

**Issue by Riseley** [microsoft/vscode#75085] opened 2019-06-07 16:31 UTC
Hi, I posted this issue here https://github.com/microsoft/vscode/issues/74964 but it seems like the bot misunderstood and mislabeled the issue because of some keywords, so for this thread I am going to purposefully avoid those keywords.

This issue is about:
1. Please fix color highlight's behavior in React/JSX environment because it is currently broken. This is a bug report.
2. Allow shortcut to bring up the internal color picker.

Here's a screenshot of the color highlighter not working:
https://imgur.com/m1Ty0rq

**Comment by Riseley** [comment] 2019-06-07 16:31
No it was a different issue.

**Comment by usernamehw** [comment] 2019-06-07 16:42
Duplicate of #52364 ?

**Comment by egamma** [comment] 2019-06-07 16:52
reopening #74964 and closing this one.

**Closed by egamma** 2019-06-07 16:52 UTC
