### ISSUE TITLE
My all extension off

### ISSUE THREAD

**Issue by sourabhossain** [microsoft/vscode#177172] opened 2023-03-15 05:02 UTC
Type: <b>Bug</b>

After I use vs code for a while all my extensions turn off. but my RAM is also CUP ticked. 

![image](https://user-images.githubusercontent.com/32600240/225211526-7c7f15bd-e4b3-4b41-be74-fbe345dbd64b.png)

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|. --crash-reporter-id 37b4c5ad-564b-4679-a877-40c9b6698903|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-javascript-snippet-pack|aka|0.1.6
auto-align|bla|0.0.13
vscode-standardjs-snippets|cap|0.9.0
turbo-console-log|Cha|2.7.1
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
jsrefactor|cms|3.0.1
vscode-redis-client|cwe|6.2.5
dscodegpt|Dan|2.0.1
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
vscode-babel-coloring|dza|0.0.4
gitlens|eam|13.3.2
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|2.6.1
prettier-vscode|esb|9.10.4
code-runner|for|0.12.0
toggle-zen-mode|fud|1.1.2
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.6
path-autocomplete|ion|1.23.1
search-node-modules|jas|1.3.0
vscode-jest-test-adapter|kav|0.8.1
auto-save|mcr|1.0.3
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
document|min|2.2.1
vscode-filesize|mkx|3.1.0
inline-fold|moa|0.2.3
vscode-docker|ms-|1.24.0
remote-containers|ms-|0.282.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-next|ms-|5.1.20230313
indent-rainbow|ode|8.3.1
vscode-jest|Ort|5.2.3
refactor|p42|3.0.1
tsimporter|pmn|2.0.1
subtle-brackets|raf|3.0.0
vscode-yaml|red|1.12.1
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
code-spell-checker|str|2.19.0
move-ts|str|1.12.0
tabnine-vscode|Tab|3.6.42
errorlens|use|3.8.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
fig|wit|0.0.7
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
pythonb192cf:30669361
funwalk2:30682974
pythonms35:30686772

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-15 07:34
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

Based on other recent issues my guess is Copilot.

**Comment by isidorn** [comment] 2023-03-15 11:01
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:01 UTC
Labels: freeze-slow-crash-leak, extension-host
