### ISSUE TITLE
Using mouse middle click in explorer 

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#42712] opened 2018-02-01 09:37 UTC
For file explorer - treating middle click like double click: `open file/toggle tree` (or, perhaps, a little bit different: open file and not change focus?)

**Comment by bpasero** [comment] 2018-02-01 09:46
I extracted the one for quick open to: https://github.com/Microsoft/vscode/issues/42714

**Comment by bpasero** [comment] 2018-02-05 06:27
/duplicate of https://github.com/Microsoft/vscode/issues/39534

**Closed by bpasero** 2018-02-05 06:27 UTC
Labels: *duplicate, feature-request, file-explorer
