### ISSUE TITLE
[css] support /deep/ selector

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/vscode#7002] opened 2016-05-29 01:16 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10

When writing Angular 2 components using view encapsulation, it may be necessary to use CSS scoping, i.e. special selectors in accordance with:
[Angular 2 Guide](https://angular.io/docs/ts/latest/guide/component-styles.html#!#using-component-styles) and the related reference [CSS Scoping](https://www.w3.org/TR/css-scoping-1/).

VS Code currently produces and error as follows:

Steps to Reproduce:
1. Entering the following code into a css file (as for a ng2 component)

```
:host /deep/ rect.d3chart-background {
  fill: rgba(250,250,250,0.8);
  border-radius: 3px;
}
```
1. VS Code creates an error with message _"{ expected"_. The error is triggered on the first backslash of `/deep/`.

Thanks in advance.

**Comment by aeschli** [comment] 2016-05-30 09:43
'/' is not a valid character in a selector, at least not in CSS3.
I wasn't able to find any details in a newer spec. Is '/' now a valid part of an identifier, or is it an operator or is just `/deep/` a new special selector?

**Comment by Tyriar** [comment] 2016-05-30 09:45
Did `/deep/` ever make it into the spec?

**Comment by tomwanzek** [comment] 2016-05-30 14:04
By way of this some more detail. The issue currently arises in the context of some use cases when styling components in accordance with Angular 2 (RC1). Here a few snippets from the Angular documentation section, I linked in my initial comment:

> **/deep/**
> 
> Component styles normally apply only to the HTML in the component's own template.
> 
> We can use the `/deep/ `selector to force a style down through the child component tree into all the child component views. The /deep/ selector works to any depth of nested components, and it applies both to the view children and the content children of the component. 

...

> The` /deep/ `selector also has the alias `>>>`. We can use either of the two interchangeably.
> 
> The /deep/ and >>> selectors should only be used with emulated view encapsulation. This is the default and it is what we use most of the time.

Angular 2 supports the use of `/deep/ `and `>>>` in emulated view encapsulation, i. e. when there there is no native shadow DOM support.

The `>>>` alias causes an error in a css stylesheets edited in VS Code as well.

Otherwise, the cross-references would lead to the shadow DOM as the note in _Section 2.3_ of [W3C Shadow DOM](https://www.w3.org/TR/shadow-dom/) and the more specific discussion in [Deep Combinator W3C CSS Scoping](https://www.w3.org/TR/css-scoping-1/#deep-combinator).

**Comment by aeschli** [comment] 2016-05-30 19:12
Thanks for the link, which led me to this:  https://www.w3.org/TR/2013/WD-selectors4-20130502/#idref-combinators

**Comment by dstorey** [comment] 2016-06-07 05:55
/deep/ no longer exists, so I don't think we should support it. >>> is the new version, which should probably be supported, but I don't know how stable it is right now. These kind of things usually get renamed a lot before being widely supported.

https://drafts.csswg.org/css-scoping-1/#deep-combinator

**Comment by zhenwenc** [comment] 2016-07-19 11:26
Is there any workaround for this issue? Its breaking the syntax checking and syntax highlight. 

No matter its been deprecated in the future (who knows when, at least its valid at this point), or change to a new version (shouldn't we support both versions then?), it does supported by the parser (it works find if you ignored the vscode error), and has been recommended (or at lease been mentioned) in the Angular2 official doc.

**Comment by aeschli** [comment] 2016-07-19 12:20
There's no workaround except disabling the syntax checking.
Changing the parser and syntax highlighting grammar is considerable work. We have limited resources and want to focus on what's in the standards.
We have an extension APIs that allow external developers to contribute advanced language supports, including replacing grammars. 
Closing this issue

**Comment by zhenwenc** [comment] 2016-07-19 13:08
Thanks! Disable syntax checking would be enough (transpiler will tell me the syntax error anyway).

**Comment by aeschli** [comment] 2016-07-19 14:29
The settings is `"css.validate": false`

**Comment by tomwanzek** [comment] 2016-07-19 15:40
That is what I ended up doing in the interim. Toggling back and forth manually, when I actually change the css files and then screening the real issues out. Not ideal, but I understand your take. Thanks for all the amazing work on VS Code.

**Comment by DmitryEfimenko** [comment] 2016-09-24 00:06
does anyone know if an extension exists that supports this `/deep/` selector?

**Comment by tomwanzek** [comment] 2016-09-24 00:49
Not to my knowledge. Although, I would be more interested now than even before, since there where some recent changes on the Angular2 final (and the last couple of RCs before that), which made me have to use `/deep/` or `>>>` again.

Until recently I could avoid it.

**Comment by canda** [comment] 2016-12-28 14:47
using `>>>` alias, vscode shows an error but doesn't break the syntax checking for the rest of the file. It seems like a suitable workaround

**Comment by szykov** [comment] 2017-02-11 19:03
I hope you guys will change your mind or at least make possible to disable css validation locally in vscode. Thanks.

**Comment by aeschli** [comment] 2017-02-15 09:13
use `"css.validate": false` to disable css validation

**Comment by szykov** [comment] 2017-02-15 10:06
@aeschli  yeap, I'm aware of it, thanks.  But mentioning this in vscode setting file will disable css validation globally. I wold like to see something like:
```
// disable-css-validation-next-line
:host /deep/ >>> other criminal  css stuff.
```

it would be a good workaround.

**Comment by aboveyou00** [comment] 2017-03-24 20:41
Another workaround: instead of disabling css validation, just use `#{"/deep/"}`

**Comment by andregs** [comment] 2017-03-24 21:07
@aboveyou00 can you please explain that syntax?

**Comment by aboveyou00** [comment] 2017-03-25 02:04
It's basically just an "insert raw" command. You can use it to make variable contents part of a selector; this is the example that they give in [http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_](the documentation).

```
$name: foo;
$attr: border;
p.#{$name} {
  #{$attr}-color: blue;
}
```

A feature that doesn't seem to be documented is that you can just insert raw text there by wrapping it in a string. I'm not sure where I found out about it, but you can use it (for example) to prevent SCSS from collapsing expressions in `calc()` values. Example:

```
div {
    width: calc(#{"100% - 80px"});
}
```

Without that it would set the width to either 20% or 20px, I don't remember which, but either is invalid.

**Comment by szykov** [comment] 2017-03-26 07:22
Some updates from my side: I ended up switching on again angular encapsulation and moving from standard linter to [stylelint](https://github.com/stylelint/stylelint). It is more advanced and flexible.

**Closed** 2017-04-06 07:32 UTC
Labels: css-less-sass, feature-request, help wanted

**Comment by aeschli** [comment] 2017-04-06 07:37
I added support for /deep/ and >>> to the cssParser.

**Comment by oldbasilbear** [comment] 2017-04-18 15:55
Has this being fixed on Linux platform - I still have a syntax error in 1.11.2 Ubuntu

**Comment by oldbasilbear** [comment] 2017-04-20 06:45
Thanks very much.

**Comment by SchneMa** [comment] 2017-04-27 14:34
@aeschli is the cssParser support for ">>>" allready live? 
VSCode still telling me that an "{" is expected.

**Comment by aeschli** [comment] 2017-04-27 15:35
It should work in the [insiders build](https://code.visualstudio.com/insiders).
If not, please file a new bug with your code sample.

**Comment by SchneMa** [comment] 2017-04-28 06:04
Thank you for this info!

**Comment by luchillo17** [comment] 2017-05-04 19:06
@aeschli I've donwloaded right now the build 1.12.0 just released and `/deep/` and `>>>` still breaks `scss` validation, did you fix it in `css` only?

**Comment by aeschli** [comment] 2017-05-05 07:54
It should work for css, less and scss. 
I just tried the example from the description of this bug and it works for me.
Please disable all extensions to make sure it is not caused by an extension.
Otherwise please file an issue with sample code that shows the problem.

**Comment by tx8821** [comment] 2017-05-05 08:18
I can confirm that it is still broken in 1.12.1 (updated today). Please view screenshots at #26004
