### ISSUE TITLE
Allow horizontal terminal pane to cover file browser

### ISSUE THREAD

**Issue by bschlenk** [Microsoft/vscode#42141] opened 2018-01-25 08:36 UTC
Right now the file browser owns the left side of vscode. When I open the terminal in horizontal mode, it only takes up the bottom portion of the editor side, but not the file browser side. Since I bring the terminal up and down frequently, I think it should be able to overlap both the file browser and the editor, to give it a larger width. Here is a diagram of what I mean: 

Current behavior:

```
+---------------------------------+
|       |                         |
|       |                         |
|       |                         |
|       |         Editor          |
|       |                         |
| Files |                         |
|       |                         |
|       +-------------------------+
|       |                         |
|       |        Terminal         |
|       |                         |
+---------------------------------+
```

Desired behavior:

```
+-------+-------------------------+
|       |                         |
|       |                         |
|       |                         |
| Files |         Editor          |
|       |                         |
|       |                         |
|       |                         |
+-------+-------------------------+
|                                 |
|            Terminal             |
|                                 |
+---------------------------------+
```

**Comment by bpasero** [comment] 2018-04-18 16:42
Duplicate of https://github.com/Microsoft/vscode/issues/42149

**Closed by bpasero** 2018-04-18 16:42 UTC
Labels: feature-request, workbench-layout
