### ISSUE TITLE
connect ECONNREFUSED 191.238.172.191:443

### ISSUE THREAD

**Issue by Farakan** [Microsoft/vscode#20908] opened 2017-02-20 06:32 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:44:55.542Z)
- OS Version: Linux x64 4.4.46-11-default
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|jslint|ajhyndman|1.2.1|
|vs-code-css-comments|ashhitch|1.0.2|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|Theme-FlatlandMonokai|gerane|0.0.4|
|CSSLint|raymondcamden|0.0.2|

---

Steps to Reproduce:

1. I am trying to install extensions and i got the following error i have included in the Title bar
2.

**Comment by joaomoreno** [comment] 2017-02-21 13:44
Closing as duplicate of #7140

You can help us in #18103

**Closed by joaomoreno** 2017-02-21 13:44 UTC
