### ISSUE TITLE
[VS Code Stable Web 1.46.0] Live Share Web hangs on sign in 

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#100333] opened 2020-06-16 21:34 UTC
- VSCode Version: 1.46.0 (in browser only)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Start a Live Share session on VS Code (desktop)
2. Paste the join url into browser 
3. Cancel out of the join in desktop pop-up
![image](https://user-images.githubusercontent.com/8161247/84830065-ab9c4580-afdd-11ea-8885-6c3605b30897.png)

4. Select join from browser
![image](https://user-images.githubusercontent.com/8161247/84830116-c1aa0600-afdd-11ea-805a-be740b98a0b3.png)

5. Attempt to sign in with Microsoft or Github credentials

![image](https://user-images.githubusercontent.com/8161247/84830209-e4d4b580-afdd-11ea-8200-3bcf2af25766.png)

Additional info:

- this started occurring when Live Share Web upgraded VS Code Stable to 1.46.0
- It doesn't repro on VS Code Insiders (1.47.0)
- It hangs on the attempt to open the external login-in uri
- The same hang can be repro'ed by adding the following to extension activate()
(only in browser - not desktop on 1.46.0)
    const uri = vscode.Uri.parse('https://microsoft.com');
    **await vscode.env.openExternal(uri);**

**Comment by kieferrm** [comment] 2020-06-17 17:05
@jramsay anything in devtools?

**Comment by JacksonKearl** [comment] 2020-06-17 19:05
The problem is the trusted link service blocks resolving links on it being able to open `.git/config`, however if the filesystem blocks until an auth link is resolved we are in a deadlock. @eamodio had already fixed this in Insiders by timing-out the filesystem call, I put up a candidate PR which applies that patch to Stable.

**Comment by JacksonKearl** [comment] 2020-06-17 19:09
Verification steps:

1. set up a serverless remote-web instance (https://github.com/microsoft/vscode-internalbacklog/wiki/VSCode-Web#running-serverless), but modify the in-memory-fs-provider to never resolve `stat` calls:
```
	stat(uri: vscode.Uri): vscode.FileStat {
		return new Promise(() => {})
	}
```
2. ensure opening links still works.

**Closed** 2020-06-17 22:29 UTC
Labels: candidate, workbench-link
