### ISSUE TITLE
Suggestion: allow TypeScript service to be shared with task

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#89650] opened 2020-01-29 19:22 UTC
The built-in TS functionality only shows type errors for open files, so I have defined a task so that I can find all type errors for all files in the project:

```jsonc
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

This is working well, however it means that I now have two instances of TypeScript (service?) running:

1. The one used by the built-in extension
2. The one used by this task

I would like these two usages to share the same TypeScript instance/service, as this would massively help with performance and issues whereby the two instances fall out of sync with each other, resulting in stale errors. These are issues I face a lot when switching between branches and then running `yarn`.

Perhaps the built-in TS extension could detect if there is already an instance running for a task, and then re-use that? I suspect it's not as simple as that though.

Related:
- https://github.com/microsoft/vscode/issues/13953
- https://github.com/microsoft/vscode/issues/13953#issuecomment-516927535

**Comment by mjbvz** [comment] 2020-01-31 19:18
Using a separate task process is the best approach ATM. The TypeScript service is single threaded so tasking it with the build in addition to intellisense is not going to be good user experience

**Comment by mjbvz** [comment] 2020-04-15 22:31
After reading though this again, it seems like the desired UX here is #13953

Closing as a duplicate of #13953

**Closed by mjbvz** 2020-04-15 22:31 UTC
