### ISSUE TITLE
breakpoint fly away when using power-assert transform

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#37199] opened 2017-10-31 03:12 UTC
- VSCode Version: 1.17.2
- OS Version: Mac

Steps to Reproduce:

see https://github.com/atian25/vscode-report-powerassert

1. setBreakpoint at `assert` statement at `index.test.js`
2. launch `Mocha Test without power-assert` via npm, everything is ok.
3. launch `Mocha Test` via npm, the breakpoint is move to the first line.
   - it will use [power-assert](https://github.com/power-assert-js/power-assert) to assert.
   - which will use [intelli-espower-loader](https://github.com/power-assert-js/intelli-espower-loader) to transform the test file.

npm scripts: `mocha --require intelli-espower-loader --inspect-brk`

see snapshot below:
![vscode-report-test](https://raw.githubusercontent.com/atian25/vscode-report-powerassert/master/vscode-report-test.gif)

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-10-31 10:18
Looks like another loader tool that transforms code and creates source maps on-the-fly...

**Comment by roblourens** [comment] 2018-09-12 05:41
BP actually stops at the right place, I think the issue is with the runtime script being named the same as the real source file, still not handled quite right.

**Comment by atian25** [comment] 2018-09-12 05:45
@roblourens not, it did not stop at the right line

**Comment by atian25** [comment] 2019-04-02 05:44
@roblourens @weinand any plan of this?

**Comment by roblourens** [comment] 2019-04-02 15:18
Try setting `"disableOptimisticBPs": true,` and tell me whether that helps

**Comment by atian25** [comment] 2019-04-02 15:23
@roblourens yes, it works! thanks.

**Comment by roblourens** [comment] 2019-04-02 15:27
Great! One issue is that you may not hit breakpoints, since there is a race between loading the code and binding the breakpoint. If so you may want to add a `debugger` statement in a test or the top of the file.

This is probably the best experience we can provide right now so I will close this for now.

**Closed by roblourens** 2019-04-02 15:27 UTC
Labels: debug, feature-request

**Comment by atian25** [comment] 2019-04-02 15:31
yes, just found https://github.com/Microsoft/vscode/issues/60187

thanks again.
