### ISSUE TITLE
Export profile does not work in wsl

### ISSUE THREAD

**Issue by kedevked** [microsoft/vscode#169911] opened 2022-12-23 10:21 UTC
Type: <b>Bug</b>

I am trying to export my code profile so that I can reuse it in other workspaces. But when I try to export it (`command palette profile: export (default)`), there is a dialog that comes with the message `command resulted in an error (Installing extensions to a specific profile is not supported in remote scenario)`

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.21GB free)|
|Process Argv|--crash-reporter-id 27d188d8-e2c0-4227-8030-38b93304cf33|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4 x 2803)|
|Memory (System)|3.83GB (2.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4 x 2803)|
|Memory (System)|3.83GB (2.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4 x 2803)|
|Memory (System)|3.83GB (2.56GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.72.0
ng-template|Ang|15.0.3
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.3
terraform|has|2.25.2
playwright|ms-|1.0.2
vscode-stylelint|sty|1.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by theonlyfoxy** [comment] 2023-01-01 06:47
Same Issue.
Also [This Issue](https://github.com/microsoft/vscode/issues/165247) Could be related.

**Comment by isidorn** [comment] 2023-01-03 10:00
Closing as duplicate of https://github.com/microsoft/vscode/issues/165247
fyi @sandy081

**Closed by isidorn** 2023-01-03 10:00 UTC
