### ISSUE TITLE
Some of VS Code shortcuts broken after upgrading to 20.04

### ISSUE THREAD

**Issue by DLochmelis33** [microsoft/vscode#108679] opened 2020-10-14 19:18 UTC
Issue Type: <b>Bug</b>

I have noticed that after upgrading to 20.04 some of my VS Code keybindings have stopped working while some work properly. In the 'Keyboard Shortcuts' menu I checked the bindings, they were all correct. But when I try resetting them to these same buttons, a weird thing happens: it reads `[Slash]` instead of a `/` symbol, as well as `[Backquote]` instead of a real backquote. What's even more interesting is that VS Code interprets that `[Slash]` as if `.` was pressed, and `[Backquote]` as `ё` (I have a russian layout as well).

![broken-keys-demo-1](https://user-images.githubusercontent.com/30842273/96032012-c5a04480-0e66-11eb-8aac-02b4bdb34385.png)
![broken-keys-demo-2](https://user-images.githubusercontent.com/30842273/96034623-78be6d00-0e6a-11eb-9ced-0da4319eff36.png)

Modifiers like `Ctrl` or `Alt` make no difference. After some investigation I realized that broken shortcuts are the ones that do not correspond to latin **letters but symbols** instead, and they are mapped to russian layout, which results in `/` being interpreted as a `.` - they actually are one button in different languages; same thing with backquote and multiple other buttons. The current selected language plays no role: it reads `[Slash]` anyway. Worth noting that text editing works 100% fine, supporting all keys in all languages.

I tried to use a keylogger to check if this is an Ubuntu problem, but could not find one that properly supports languages other than English. Then I tried to set the same keymappings in other apps like GIMP, and everything works properly there in both layouts. So I suspect this is a specific VS Code problem.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-7310 APU with AMD Radeon R4 Graphics (4 x 1996)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|6.70GB (1.36GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id fb5e495c-3172-434e-b67e-56ea0dacd2b7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
file-templates|brp|1.2.0
vscode-markdownlint|Dav|0.37.1
haskell|has|1.2.0
haskell-linter|hoo|0.0.6
language-haskell|jus|3.3.0
python|ms-|2020.9.114305
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
java|red|0.68.0
sonarlint-vscode|Son|1.17.0
dot|Ste|0.0.1
blueprint|tea|3.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

(1 theme extensions excluded)

</details>

**Comment by DLochmelis33** [comment] 2020-10-15 00:37
#### Update: found several more bugs:

1. `e` is fine, `ctrl+e` is fine, `shift+e` is fine, `ctrl+shift+e` gets mapped to `ctrl+shift+unknown`. When pressed, text editor enters a weird mode I haven't seen before. Same thing with letter `u`, but all the other symbols are not affected by this.

2. `ctrl+shift` inverts NumLock action. That is, normally with NumLock being off the numpad buttons work as `PgUp` etc. and as `9` with NumLock on. However, with NumLock **on** VS Code detects `Ctrl+Shift+9` as `Ctrl+Shift+PgUp` and vice versa.

**Comment by alexdima** [comment] 2020-10-15 08:53
Could you please take a quick look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

I think you might be hitting this:
    ![image](https://user-images.githubusercontent.com/5047891/96100399-a04a1f80-0ed4-11eb-8080-1286444590c0.png)

**Comment by DLochmelis33** [comment] 2020-10-15 10:42
> Could you please take a quick look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
> 
> I think you might be hitting this:
> ![image](https://user-images.githubusercontent.com/5047891/96100399-a04a1f80-0ed4-11eb-8080-1286444590c0.png)

Thanks, solution 2 fixed the layout problem. 
However, `Ctrl+Shift+e` and `Ctrl+Shift+NumPad9` are still broken.

**Comment by DLochmelis33** [comment] 2020-10-15 13:25
Actually, with the fix the `Ctrl+Shift+e` shortcut is now displayed in Shortcuts setup menu as `Ctrl+Shift+` with literally nothing after the plus. Also, I have checked out the Keyboard Shortcuts Troubleshooting thing and here is its output:

when `Ctrl+Shift+a` is pressed (ok):
```
[2020-10-15 16:13:32.447] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2020-10-15 16:13:32.447] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2020-10-15 16:13:32.448] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-10-15 16:13:32.937] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 16, key: Shift
[2020-10-15 16:13:32.937] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2020-10-15 16:13:32.937] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-10-15 16:13:33.453] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: KeyA, keyCode: 65, key: A
[2020-10-15 16:13:33.453] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: KeyA, keyCode: 31 ('A')
[2020-10-15 16:13:33.454] [renderer1] [info] [KeybindingService]: | Resolving ctrl+shift+A
```

when `Ctrl+Shift+e` is pressed:
```
[2020-10-15 16:18:38.725] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2020-10-15 16:18:38.725] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2020-10-15 16:18:38.725] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-10-15 16:18:39.244] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 16, key: Shift
[2020-10-15 16:18:39.244] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2020-10-15 16:18:39.245] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
```
What's interesting is that despite the Output tab is read-only, that weird text editing mode that enables actually writes text into a read-only Output tab. That mode looks somewhat similar to a command palette: it reads exactly 9 symbols, overwriting current symbols, and on 10th disappears as if nothing had happened.

Regarding the Numpad problem, the logs react as if the Numlock was in fact inverted, nothing particularly different.

**Comment by ArturSymanovic** [comment] 2020-11-10 14:09
In my case Ctrl+Shift+E maps to Ctrl+Shift+unknown and does not work. However if I reset the keybinding to default value (to focus on file explorer) and turn on Caps Lock it works :)
Fixes described [here](https://github.com/Microsoft/vscode/issues/48480) do not work.

**Comment by alexdima** [comment] 2020-11-20 15:09
Duplicate of https://github.com/microsoft/vscode/issues/99508#issuecomment-661852920

**Closed by alexdima** 2020-11-20 15:09 UTC
Labels: keybindings, needs more info
