### ISSUE TITLE
Cursor should stay within the viewable part of the document when ctrl+scrolling

### ISSUE THREAD

**Issue by boaz-chen** [microsoft/vscode#89980] opened 2020-02-04 07:31 UTC
Issue Type: <b>Bug</b>

Basically the expectation is to follow Visual Studio's behavior here.

1. Open a document that has more lines than can be displayed on one screen.
2. Use ctrl+arrow down to scroll the document without changing the position of the cursor.
3. Scroll until the line with the cursor goes off view.
4. Now just hit any arrow to move the cursor.

Result: the window jumps back to the original line where the cursor was originally left when ctrl scrolling.

Expected: the cursor to not go out of scope, to avoid the out-of-context jump.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alexdima** [comment] 2020-02-04 08:49
Duplicate of #59247
Duplicate of #88247

---

If you would like to get Visual Studio keybindings, simply install the [Visual Studio keymap extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings) and this keybinding will be defined for you.

If you only want this portion, you can use the `editorScroll` command in your `keybindings.json`:

e.g.

```
{
	"key": "ctrl+up",
	"when": "editorTextFocus",
	"command": "editorScroll",
	"args": {
		"to": "up", // 'up', 'down'
		"by": "line", // 'line', 'wrappedLine', 'page', 'halfPage'
		"value": 1, // number of units to move
		"revealCursor": true
	}
}
```

**Closed by alexdima** 2020-02-04 08:49 UTC
