### ISSUE TITLE
CMD + W doesn't close window anymore

### ISSUE THREAD

**Issue by hamzahamidi** [microsoft/vscode#173283] opened 2023-02-03 11:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: mac OS 13.2 (22D49)

Steps to Reproduce:
Hello, 
A lot of shortcuts are not working anymore. For example the CMD + W doesn't close window anymore.
```
Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z (1 day ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

I'm using macbook pro mac OS 13.2 (22D49)

**Comment by wilhem-meignan** [comment] 2023-02-03 12:33
With a German keyboard layout, in keybindings.json "shift+[Backslash]" is interpreted as Shift+# (correct) but "ctrl+[Backslash]" is interpreted as Ctrl+Y. It should be Ctrl-#.

**Comment by bpasero** [comment] 2023-02-03 16:48
That sounds more like a keybindings issue to me.

**Comment by akotazit** [comment] 2023-02-03 18:07
Same problems here, recently a lot of my shortcuts stopped working. 
For example I am trying to rebind my CMD+ú (BracketLeft on english keyboard) instead it switches to CMD+W.
BracketRight switches to X instead. 

When I manually add shortcuts to json file, it doesn't work anyway.

**Comment by forusak** [comment] 2023-02-03 18:08
Same problems here, recently a lot of my shortcuts stopped working.
For example I am trying to rebind my CMD+ú (BracketLeft on english keyboard) instead it switches to CMD+W.
BracketRight switches to X instead. And more weird stuff like this.
When I manually add shortcuts to json file, it doesn't work anyway.

**Comment by fernandosmither** [comment] 2023-02-03 18:14
The bug is really general keybindings. check #173325

**Comment by alexdima** [comment] 2023-02-05 19:41
Duplicate of #173325

**Closed by alexdima** 2023-02-05 19:41 UTC
Labels: keybindings, *duplicate
