### ISSUE TITLE
Animated Cursor when Typing? 

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#55337] opened 2018-07-29 12:53 UTC
Issue Type: Feature Request

First of all, please don't hate me for such a niche minor thingymabob, this is an idea I though I'd raise. 

So I also use Office 2016 and when typing, not only does the cursor blink like in VSCode's 'smooth' option for cursor, it also animated (moves to the side) during typing, making it look like 1 smooth transition, is it possible to have that in VSCode? Probably as an option, I don't think everyone will like it.

For comparison, right now , the cursor just shifts when typing, for an idea of what I mean by this idea, for anyone with Office 2016, type and see how the cursor moves!

Thanks!

**Comment by alexandrudima** [comment] 2018-07-30 13:39
Duplicate of #20310

**Closed by alexandrudima** 2018-07-30 13:39 UTC
Labels: editor, feature-request
