### ISSUE TITLE
[Request] Enable reopening VS Code to the same workspace and set of files as when VS Code was closed (like Notepad++ default)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9510] opened 2016-07-20 01:19 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-
07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:

1. Open VS Code
2. Open some files from disk
3. Open some Untitled editors and make some changes
4. Close VS Code
5. Reopen VS Code

Actual:
Nothing was opened and need to reopen editors (especially frustrating with daily updates to VS Code).
(And no option to change this behavior to opt-in.)

Desired:
The same editors and workplace that was opened when I closed VS Code are reopened so I can continue working where I left off with minimal disruption.
(There should at least be an option to opt-in/opt-out of this behavior.)

Clarifcation:
Should work even if a workspace/folder was not opened (just using VS Code as a text editor).

**Comment by kieferrm** [comment] 2016-07-20 16:58
This is a duplicate of #101.

**Closed by kieferrm** 2016-07-20 16:58 UTC
Labels: duplicate
