### ISSUE TITLE
Setting terminal path via `terminal.integrated.env.osx` has paths backwards

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46693] opened 2018-03-27 13:27 UTC
I set this:

```js
	"terminal.integrated.env.osx": {
		"PATH": "/fake/path:${env:PATH}"
	}
```

Then in the terminal I ran `echo $PATH` and it output this:

```text
dantup-macbookpro:flutter_hello_world dantup$ echo $PATH
/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/Dev/dart-sdk/latest/bin:/fake/path
```

I put my new path on the front, yet it ended up on the end. Note: the existing paths are set in `/etc/path` and `/etc/path.d` and not added in a terminal script running at startup so I don't think it's just that the other ones are being prepended (and it seems unlikely path would have 0 items in it to start, and I'd expect to see a trailing colon if that was the case).

**Comment by Tyriar** [comment] 2018-03-27 17:57
@DanTup does your .bashrc/.bash_profile scripts manipulate `$PATH`? I can't reproduce this and it looks like it could be because of those scripts (which is as designed as they're run after terminal init).

**Comment by DanTup** [comment] 2018-03-27 18:25
@Tyriar I don't have any path manipulation in any bash files (I set all my paths in `/etc/path.d` files because otherwise they only apply to the terminal). I can reproduce on both my MacBooks.

<img width="945" alt="screen shot 2018-03-27 at 19 24 58" src="https://user-images.githubusercontent.com/1078012/37986865-962b57fe-31f4-11e8-9c16-673e128009df.png">

**Comment by DanTup** [comment] 2018-04-04 19:32
@Tyriar This case is still tagged needs-more-info, but I've added more info above. Let me know if you need anything else.

**Comment by Tyriar** [comment] 2018-04-04 20:31
@DanTup can you run `code-insiders --log trace` and then in the console check what the env is set as?

![image](https://user-images.githubusercontent.com/2193314/38333106-7ab7f2e8-380c-11e8-9e00-d72c7db07952.png)

This should say which side the problem is on.

**Comment by DanTup** [comment] 2018-04-04 20:39
Ok weird, it's correct in the console:

<img width="956" alt="screen shot 2018-04-04 at 21 38 33" src="https://user-images.githubusercontent.com/1078012/38333474-a3a37616-3850-11e8-8a26-89bd0724601f.png">

But still bogus in the terminal:

<img width="385" alt="screen shot 2018-04-04 at 21 38 59" src="https://user-images.githubusercontent.com/1078012/38333484-ac8c9aa0-3850-11e8-810a-4f32f3531807.png">

**Comment by Tyriar** [comment] 2018-04-04 22:00
@DanTup well that log happens on the line before the actual process code is launched:

https://github.com/Microsoft/vscode/blob/eb7e893b7fa79ce05abbc900ddd8f76536c8fd28/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L708-L709

The only other massaging of the env happens here to delete a bunch of keys:

https://github.com/Microsoft/vscode/blob/eb7e893b7fa79ce05abbc900ddd8f76536c8fd28/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L107-L131

And the a bunch of type conversion stuff when moving it to the native layer in https://github.com/Tyriar/node-pty

So I'm still guessing somehow your environment is doing it. Does it repro on any other machines for you?

**Comment by DanTup** [comment] 2018-04-05 18:38
> So I'm still guessing somehow your environment is doing it. Does it repro on any other machines for you?

I've only tried two, but it repros on them both - a MacBook (personal) and MacBook Pro (Google corp). So my guess is whatever it is is fairly common. I tried spawning bash from within bash to see if there was anything weird happening, but this outputs my `PATH` normally:

`bash --login -c 'echo "$PATH"'`
(though I don't know I've done it right)

What's `bootstrap` in your code?

**Comment by Tyriar** [comment] 2018-04-05 21:38
> but this outputs my PATH normally

As in the order you expect?

> What's bootstrap in your code?

Sets up module importing and logging basically, I don't think it modifies the environment.

**Comment by DanTup** [comment] 2018-04-06 07:02
Correct, they where in the order I expected. That said, I don't know exactly what you're doing to spawn the terminal versus what I wrote there - is there a way to tell exactly what you're invoking to actually create the terminal? If I can repro this issue outside of Code, I might be able to figure it out.

(Also, do you have easy access to a Mac to test whether it's just me? Seems weird that it happens on two of them with completely stock shells and almost nothing in any startup scripts).

**Comment by DanTup** [comment] 2018-04-06 07:04
Probably unrelated, but I've opened another issue where `PATH` seems to be totally messed up on Travis during test runs (the changes are significant; I can't figure it out - my guess is there's something in some login scripts on Travis that maybe Code is causing to run again):

https://github.com/Microsoft/vscode-extension-vscode/issues/104

I don't think it's related (that's not related to Terminals) but thought it maybe worth mentioning!

**Comment by Tyriar** [comment] 2018-04-06 19:46
@DanTup this is what happens on my mac:

<img width="510" alt="screen shot 2018-04-06 at 12 44 02 pm" src="https://user-images.githubusercontent.com/2193314/38441035-3bedfbf6-3998-11e8-8471-fbe412d94504.png">

Which is expected as everything to the left of `/fake/path` is set in the init scripts. You could try this to prevent bashrc/bash_profile from running:

```
  "terminal.integrated.shellArgs.osx": [
    "--noprofile",
    "--norc"
  ],
  "terminal.integrated.env.osx": {
    "PATH": "/fake/path:${env:PATH}"
  }
```

In my case this is what I see then:

<img width="429" alt="screen shot 2018-04-06 at 12 46 22 pm" src="https://user-images.githubusercontent.com/2193314/38441126-8bf0b9e0-3998-11e8-9a0c-daa026a639c6.png">

**Comment by DanTup** [comment] 2018-04-06 21:05
Ok, I got a weird prompt asking for permission when I added them and spawned a terminal, but it did solve the issue - the path is now as expected.

I can't explain what's causing this though - my `.bash_profile` is practically empty and I don't have any other files I could imagine messing with path:

<img width="1048" alt="screen shot 2018-04-06 at 22 03 01" src="https://user-images.githubusercontent.com/1078012/38444208-59dfce8e-39e6-11e8-9709-1beec513b80d.png">

On one MacBook I added things to my path by editing `/etc/path` and on the other one I put files in to `/etc.path.d/google` (though it already has a `/etc/path`), so maybe whatever processes them does weird things, but I'm not sure why you don't see it. Something re-ordering `PATH` seems like an pretty broken thing to do :-/

**Comment by Tyriar** [comment] 2018-04-11 20:00
Not sure what's causing it, but I think I've proven the problem is on your side :smile:

**Closed by Tyriar** 2018-04-11 20:00 UTC
Labels: integrated-terminal, needs more info

**Comment by DanTup** [comment] 2018-04-12 08:40
@Tyriar Maybe, but I'm certain I don't have anything others may not, so I don't think this issue is isolated to me.

Are you able to confirm exactly what commands/args you're using to spawn this, so I can try and repro outside of Code to figure out what's going on?

**Comment by Tyriar** [comment] 2018-04-12 13:47
You can follow the code through if you want:

https://github.com/Microsoft/vscode/blob/da9720b39b1a912ce8009587731d824a890797ad/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L683
https://github.com/Microsoft/vscode/blob/da9720b39b1a912ce8009587731d824a890797ad/src/vs/workbench/parts/terminal/node/terminalProcess.ts
https://github.com/Tyriar/node-pty/blob/5868fd9da4150c73d9661119bed4e5e79d5866db/src/unixTerminal.ts#L45
https://github.com/Tyriar/node-pty/blob/5868fd9da4150c73d9661119bed4e5e79d5866db/src/unix/pty.cc#L139
