### ISSUE TITLE
When using VSCode with NVDA in screen reader mode, tab is now exposed as space

### ISSUE THREAD

**Issue by camlorn** [microsoft/vscode#106604] opened 2020-09-13 22:34 UTC
- VSCode Version: 1.49.0
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Open a file with tabs in it.
2. Turn on indentation indication with NVDA.
3. The tab is reported as a single space.

This is problematic because it means that 1 space and 1 tab are reported equivalently and you can't tell which is in use.  I'm not knowledgeable enough on the NVDA side to do much with this, but NVDA is claiming that it's  ascii 32 (i.e. actually space, not just NVDA deciding to say space instead).  I'm assuming that somewhere along the way the algorithm for keeping the screen reader version of the edit control changed?

Sorry if this is a duplicate: it's almost impossible to search for.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hiroshi2141** [comment] 2020-09-16 00:59
I am suffering from the same problem. Installing 1.48.2 solved this problem.

**Comment by isidorn** [comment] 2020-09-16 09:45
Duplicate of https://github.com/microsoft/vscode/issues/104673
It is caused by the update to a new Electron version. We will try to backport a fix for this.
Thanks for reporting

**Closed by isidorn** 2020-09-16 09:45 UTC
