### ISSUE TITLE
Open editor in new window

### ISSUE THREAD

**Issue by lazarkrstic** [microsoft/vscode#87241] opened 2019-12-18 10:43 UTC
Open editor in new visual code, just like Microsoft Edge allow to open tab in new window - simple drag & drop tab. Very useful for 2 monitors.

**Comment by IllusionMH** [comment] 2019-12-18 13:11
/duplicate of existing requests #10121 (enabler), #8171, and #2686.

Unfortunately in the meantime only workaround will be using [Duplicate Workspace in New Window](https://code.visualstudio.com/updates/v1_24#_duplicate-workspace-in-new-window) but it is resources heavy.

**Closed** 2019-12-18 13:11 UTC
Labels: *duplicate
