### ISSUE TITLE
cannot read property openconfigfile of undefined

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#39080] opened 2017-11-24 06:19 UTC
- VSCode Version: 1.18.1

Steps to Reproduce:

for single file debugging which doesn't need to generate launch.json, seems only `resolveDebugConfiguration` would be called, and if for some case I'd like to abort the launch by returning undefined, it will pop up en error message `cannot read property openconfigfile of undefined`. Any idea why? Thanks.

**Comment by weinand** [comment] 2017-11-24 08:13
duplicate of #38674

**Closed** 2017-11-24 08:13 UTC
Labels: *duplicate, debug
