### ISSUE TITLE
HTML RUNNER

### ISSUE THREAD

**Issue by SirCodesAIot** [microsoft/vscode#109862] opened 2020-11-02 19:44 UTC
Issue Type: <b>Feature Request</b>

I'm a HTML begginer, and I want to run my code on this IDE, but there is no option for that, sooo can you guys please add that to this IDE? That will be a great help! Thanks!!!! :DDDD

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by yume-chan** [comment] 2020-11-03 08:58
Duplicate of #12080

Honestly this might never happen because an extension can easily provide this feature, for example [this one](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

**Closed** 2020-11-03 14:40 UTC
