### ISSUE TITLE
Close repo is broken, repo reappear after refresh or reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125914] opened 2021-06-10 10:13 UTC
I have https://github.com/jrieken/vscode-regex-notebook which uses regexper-static as submodule. This submodule only exists so that I can build/bundle regexper as renderer. I will never commit changes to it and I don't want to see it in the SCM view

Obvious bug is described below but I really want to permanently close a repo (e.g don't restore after reload)

* close repo
* refresh
* :bug: repo reappears

https://user-images.githubusercontent.com/1794099/121507431-ea908b80-c9e4-11eb-8fc9-5670ad9f403b.mov

**Comment by AlCalzone** [comment] 2022-03-15 20:23
Maybe duplicate of https://github.com/microsoft/vscode/issues/103235

**Comment by lszomoru** [comment] 2022-12-09 15:40
Closing as duplicate of https://github.com/microsoft/vscode/issues/107398

**Closed by lszomoru** 2022-12-09 15:40 UTC
Labels: bug, git, scm
