### ISSUE TITLE
Diff editor not working when workbench.editorAssociations is configured

### ISSUE THREAD

**Issue by amitgupta4078** [microsoft/vscode#99520] opened 2020-06-06 13:55 UTC
Issue Type: <b>Bug</b>

I have a codebase in which there are some modified files. These files are showing in Source Control Panel too. When I click on any of these file, it opens a file diff view but no diff is shown although Github Desktop is showing the diff. When I scroll in this split file view, both the original and modified files are scrolling independently. Ideally they should be scrolling in sync. This issue is happening only with one repo. Can someone tell me what is the issue here? VS Code is showing file diff for my other repos. What settings should I change for it to work for this repo too. Please note that it was showing file diffs earlier perfectly but probably after some VS Code update, it broke. I tried all sorts of hacks: restarting my system, VS Code, unloading and reloading the repo but nothing works.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
compareit|in4|0.0.2
vue|jcb|0.1.5
python|ms-|2020.5.80290
cpptools|ms-|0.28.2
vetur|oct|0.24.0
gitblame|wad|4.0.1

</details>

**Comment by gjsjohnmurray** [comment] 2020-06-06 14:34
/needsMoreInfo does this also happen after you use the Command palette command to reload with all extensions disabled?

If so, can you paste a screenshot here?

**Comment by amitgupta4078** [comment] 2020-06-07 07:16
I uninstalled all extensions and then did use the Command palette command to reload with all extensions disabled. I can see the diff for .css files now but now for .js files?
Sorry for not being able to post a screenshot since this is a private repo and I cannot post a video recording or screenshot for any of its files.

**Comment by joaomoreno** [comment] 2020-06-08 12:34
> I uninstalled all extensions and then did use the Command palette command to reload with all extensions disabled. I can see the diff for .css files now but now for .js files?

Can you find any other pattern? What about text files? What about other repositories? What about other machines?

**Comment by amitgupta4078** [comment] 2020-06-08 15:38
Can you find any other pattern? What about text files?
> I tried for other file types like .txt, .sh, .json, DockerFile etc. It is working for all other types.
 What about other repositories? 
> Yes, it is working for all other repos perfectly.
What about other machines?
> It is working for my windows machine too.

**Comment by joaomoreno** [comment] 2020-06-09 14:09
So: on one single machine, on one single repository, JavaScript files have no diff, yet all other file types have it. Can you show me a screenshot?

**Comment by amitgupta4078** [comment] 2020-06-09 16:03
Sorry for not being able to post a screenshot since this is a private repo and I cannot post a video recording or screenshot for any of its files.

**Comment by maxxungao** [comment] 2020-06-11 03:12
I also ran into this issue with ".json" files. 
![image](https://user-images.githubusercontent.com/41761094/84340529-cbeb8080-ab55-11ea-83ac-a5adc02793f4.png)

There's no highlights showing the diff. The two panels scroll independently. In the screenshot, both panels are scrolled to the top and they are still off by one line. I tried this after "reload with extensions disabled". It works for other types of files. 

My setup:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

**Comment by amitgupta4078** [comment] 2020-06-11 04:47
I can reproduce this issue with `--disable-extensions`. Also, I just checked again: it is happening on all repos on my machine; not sure why I was unable to reproduce it earlier for other repos. But unlike what @maxxungao mentioned, I am facing this problem with only .js. files. It is working for other file types.

**Comment by joaomoreno** [comment] 2020-06-11 10:24
@amitgupta4078 Can you change your theme to one of the default ones? `Dark Theme` maybe?

**Comment by joaomoreno** [comment] 2020-06-11 10:25
Can you reproduce by running on a different user data dir? `--user-data-dir NEW_FOLDER`

**Comment by joaomoreno** [comment] 2020-06-11 10:26
@bpasero @alexdima Check the screenshots above. It's like the diff editor shows, but each side behaves as a standalone editor. The user event mentions that _The two panels scroll independently_. Does this ring any bells to you?

**Comment by bpasero** [comment] 2020-06-11 10:47
Sounds a lot like https://github.com/microsoft/vscode/issues/99723 which I did not understand.

**Comment by joaomoreno** [comment] 2020-06-11 12:44
Yes looks like it's the exact same issue. 🤔 

Something is off here

**Comment by bpasero** [comment] 2020-06-11 13:56
@amitgupta4078 do you also see this when you compare 2 files from the explorer?

**Comment by amitgupta4078** [comment] 2020-06-11 17:56
![image](https://user-images.githubusercontent.com/13534503/84422352-88b70d80-ac3a-11ea-8c05-3e9673af9933.png)
@joaomoreno I changed my colour theme and issue is still reproducible. I will check with` --user-data-dir NEW_FOLDER` and get back to you.
@bpasero Do you mean: I should compare two files in Mac Finder?

**Comment by maxxungao** [comment] 2020-06-11 18:09
> @amitgupta4078 do you also see this when you compare 2 files from the explorer?

in my case, comparing to .json files doesn't show diff either. 

@amitgupta4078 He means select two files (two .js file in your case) from the the vscode sidebar, right click on them and select "Compare Selected"

**Comment by amitgupta4078** [comment] 2020-06-12 05:17
@joaomoreno  I tried this in a fresh repo placed at a different folder. Earlier my repo was in Downloads folder in Mac; now I placed it on Desktop but the issue is still same.

![image](https://user-images.githubusercontent.com/13534503/84467423-ba12f600-ac99-11ea-8851-6872acf7986f.png)

Also, @bpasero I tried comparing two files as @maxxungao explained above, the issue is there also. You can see below screenshot: I have compared two different files.
![image](https://user-images.githubusercontent.com/13534503/84467530-1bd36000-ac9a-11ea-97e0-09bbe190c5e8.png)

**Comment by bpasero** [comment] 2020-06-12 06:14
@alexdima any ideas how to debug why the diff is not computed?

**Comment by starjesse** [comment] 2020-06-12 07:52
I got same problem two weeks ago. I think you can try to clear the local settings of workbench.editorAssociations #98648.
![image](https://user-images.githubusercontent.com/33248281/84478980-c3658800-acc4-11ea-918a-aae0b3059574.png)

**Comment by bpasero** [comment] 2020-06-12 08:01
@mjbvz this seems to originate from a config such as:

"workbench.editorAssociations": [
	{
		"filenamePattern": "*.cpp",
		"viewType": "default"
	}
]

If you open 2 CPP files and compare them, there is no diff. Can you check?

**Comment by bpasero** [comment] 2020-06-12 08:03
Hm, I cannot reproduce in our `1.46` release though. @amitgupta4078 can you try again with latest?

**Comment by amitgupta4078** [comment] 2020-06-12 15:11
The issue is resolved for me. I uninstalled the VS Code and re-downloaded it. This time I saved the download file and extracted file in Applications folder only. It is again working for all repos and file types. I highly request the team to please include this as an instruction in download section of VS Code product page. 

**Thanks for all the great support.**

**Comment by mjbvz** [comment] 2020-06-12 18:11
Seems like a duplicate of #99172 which should be fixed in VS Code 1.46

**Closed by mjbvz** 2020-06-12 18:11 UTC
Labels: bug, diff-editor
