### ISSUE TITLE
Cannot multi-select items in SCM / Git Viewlet

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode#21571] opened 2017-02-28 19:48 UTC
- VSCode Version: 1.10.0-insider
- OS Version: Mac

Steps to Reproduce:

1. Open a Git repository
2. Edit 2 files and save them
3. Go to the Git viewlet and click on the 1st file
4. Shift + Click to select the 2nd file (or Shift + Down Arrow)

Expected: 
- Both items are selected
- Note that in the 1.9.1 release, multi-select works just fine

Actual:
- Multi-select no longer works for either keyboard or mouse navigation

**Comment by isidorn** [comment] 2017-03-01 09:06
Duplicate of https://github.com/Microsoft/vscode/issues/21000

**Closed by isidorn** 2017-03-01 09:06 UTC
