### ISSUE TITLE
Dropping file onto release notes not possible

### ISSUE THREAD

**Issue by tricki** [Microsoft/vscode#45977] opened 2018-03-16 13:30 UTC
Issue Type: <b>Bug</b>

- Open VS Code
- Open Release Notes (Help > Release Notes)
- Drag and drop a file onto the release notes

Expected behavior:
- Release notes should get a grey overlay on hover to indicate drop zone
- After dropping the file should be opened

Actual behavior:
- Nothing happens

More info:
- No console output
- Dropping works as expected:
  - when on any other tab, including "Welcome" and "Interactive Playground"
  - on tab bar
  - on "Open Editors" area

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:47:13.351Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.89GB (5.88GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

Reproduces without extensions

**Comment by tricki** [comment] 2018-03-16 13:35
Nope, not a duplicate. It's also quite unlikely to be, as I created both issues :smirk:

**Comment by mjbvz** [comment] 2018-03-16 16:51
Thanks. 

This is actually a duplicate of #25856

**Closed by mjbvz** 2018-03-16 16:51 UTC
Labels: new release
