### ISSUE TITLE
Markdown Image copied from clipboard: Cell blank after execution

### ISSUE THREAD

**Issue by bertrtam00** [microsoft/vscode#171668] opened 2023-01-18 10:06 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After working on a markdown cell, including pasting images from clipboard like so: `![image.png](attachment:image-13.png)`, at first everything worked as expected: 

when running the cell (ctrl + enter), text and images are shown like this: 
![image](https://user-images.githubusercontent.com/26382201/213141750-7d7e4c91-0a09-4f40-bd33-4712bd586bff.png)

But today suddenly any cell that contains pasted images is only rendered as one blank line. 
Clicking into the cell still gives me the full content, though. 

It still works in the browser version of jupyter notebook. 
Also, in VS Code Jupyter any Markdown Cell without Images renders correctly.

Any ideas, why?
Thank you! :) 

### VS Code Version

1.74.3

### Jupyter Extension Version

v2023.1.1003441034

### Jupyter logs

```shell
No output generated when rendering markdown cell. (as far as I know)
```

### Coding Language and Runtime Version

markdown

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by amunger** [comment] 2023-01-18 20:28
I can repro - I'm seeing `Error rendering output item using 'vscode.markdown-it-renderer'` in the html of the preview

**Comment by amunger** [comment] 2023-01-18 20:30
dupe of https://github.com/microsoft/vscode-jupyter/issues/12568

**Closed by amunger** 2023-01-18 20:30 UTC
Labels: bug
