### ISSUE TITLE
Pasting into Integrated Console pastes one character at a time

### ISSUE THREAD

**Issue by diggityshmoo** [microsoft/vscode#111054] opened 2020-11-20 20:29 UTC
Issue Type: <b>Bug</b>

When pasting into the powershell integrated console text is being entered one character at a time, as though someone is very quickly typing the text on my keyboard.  For long commands this can cause a noticeable delay in entering the command.  If I use a new terminal window using the + button (either zsh, bash, or pwsh) the entire string of text is pasted into the terminal immediately as expected.

I'm uncertain when the behavior started as this machine was just built and is the only mac I have access to, so I dont know if it was present on earlier versions.  I did create a mac VM in VMWare fusion though and observed the same behavior there with a fresh install of powershell & vscode.

I am running the most recent version of vscode and powershell 7.1.0.  On my windows laptop which is running the same versions I do not observe this behavior, and text pastes into the integrated console normally.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_2941646 --crash-reporter-id bc8ad02e-66f2-4298-a1ef-ed0aca3dc6dd|
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3206
vscode-icons|vsc|11.0.0

</details>

**Comment by meganrogge** [comment] 2020-11-20 22:00
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by diggityshmoo** [comment] 2020-11-20 23:22
Please see a gif of the problem here: [https://giphy.com/gifs/jDFmNmOlh8u0koy1u8/fullscreen](https://giphy.com/gifs/jDFmNmOlh8u0koy1u8/fullscreen)

Sorry, the quality isn't the greatest but you can pretty clearly see the difference pasting into the integrated console vs a zsh or normal pwsh terminal.

The windows terminal doesn't appear to be available on Mac, but i did try it on one of my windows machines.  It appears to paste _almost_ instantly, but on very long commands i do see the slightest delay on it.  Not enough that I'd notice it if i wasn't looking for it though, and certainly nothing compared to what i'm seeing in vscode on my Mac.

**Comment by meganrogge** [comment] 2020-11-20 23:35
thanks for the screenshot. what do you have `terminal.integrated.localEchoLatencyThreshold` set to?

**Comment by diggityshmoo** [comment] 2020-11-21 00:01
I don't have that configured in my settings json, but according to the UI it's set at 30.  I tried setting it to both 0 and -1 (restarting the console in between) but didn't see any change in the behavior.

**Comment by kameshchauhan** [comment] 2020-11-24 18:56
this issue  happens in non-integrated terminal also....and i think it happens in zsh only.

**Comment by diggityshmoo** [comment] 2020-11-24 19:34
> 
> 
> this issue happens in non-integrated terminal also....and i think it happens in zsh only. Try to disable "zsh-syntax-highlighting" plugin in .zshrc if enabled/added....i do see difference when disabled.

I don't see the issue in the non-integrated terminal as shown in the gif i posted above.  Nevertheless I did check my.zshrc and confirmed i dont have that plugin enabled, and also tried setting "terminal.integrated.shell.osx" to "/bin/bash" instead of "/bin/zsh" in case it was somehow used in launching the integrated powershell console, but didn't see any change in behavior.  Thanks for the suggestion though.

**Comment by meganrogge** [comment] 2020-11-24 22:40
duplicate of #111234

**Closed by meganrogge** 2020-11-24 22:40 UTC
Labels: *duplicate, bug, integrated-terminal, needs more info
