### ISSUE TITLE
Terminal autocomplete problem

### ISSUE THREAD

**Issue by tomintaiga** [Microsoft/vscode#28546] opened 2017-06-12 17:06 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-79-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|RustyCode|saviorisdead|0.19.1|
|cmake|twxs|0.0.17|
|vscode-lldb|vadimcn|0.5.0|
|cmake-tools|vector-of-bool|0.9.7|;

---

![out](https://user-images.githubusercontent.com/26430678/27045612-197688aa-4faa-11e7-9ace-c56ad2719c29.gif)

Steps to Reproduce:

1. Open internal terminal
2. Start to write git push command
3. After "git push origin f" press TAB for autocomplete
4. Completed string replace part of the first string in terminal

**Comment by ramya-rao-a** [comment] 2017-06-12 17:25
Closing as duplicate of #28304

cc @Tyriar

**Closed by ramya-rao-a** 2017-06-12 17:25 UTC
Labels: new release
