### ISSUE TITLE
Emmet in TSX seriously interferes with TS suggestions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#225760] opened 2024-08-16 07:22 UTC
* open a `.tsx` file with the content `console.l`
* press cmd+space
* type `og`
* observe how the top suggestion is emmet and pressing `<tab>` or `<enter>` would expand the emmet abbreviation instead of the member completion

![Image](https://github.com/user-attachments/assets/8943479b-3845-4a83-825f-bd89f9c9b7b0)

![Image](https://github.com/user-attachments/assets/78d56012-8cf1-4a43-a39a-5833a57d05d6)

```
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by rzhao271** [comment] 2024-12-11 19:02
Duplicate of https://github.com/microsoft/vscode/issues/51537

**Closed by rzhao271** 2024-12-11 19:02 UTC
Labels: bug, emmet, confirmation-pending
