### ISSUE TITLE
When opening an editor with a URI that contains a query param the breadcrumbs are unexpectedly starting from the root directory

### ISSUE THREAD

**Issue by itsdouges** [microsoft/vscode#213633] opened 2024-05-28 08:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: macOS 14.2.1

Steps to Reproduce:

1. Open an editor using the `vscode.openWith` command
2. When opening the file with a query param the breadcrumbs are starting from the root directory instead of the workspace directory
3. This happens with both custom editors and the default editor. I've put the minimal reproduction for the default editor case below.

**Works**

```jsx
vscode.commands.executeCommand(
  "vscode.openWith",
  vscode.Uri.file(scopedFileName),
  "default",
  vscode.ViewColumn.Beside
);
```

<img width="403" alt="image" src="https://github.com/microsoft/vscode/assets/6801309/fbdb226a-6ba1-4624-989f-fb37daefd28a">

**Does not work**

```jsx
vscode.commands.executeCommand(
  "vscode.openWith",
  vscode.Uri.file(scopedFileName).with({ query: "triplex" }),
  "default",
  vscode.ViewColumn.Beside
);
```

<img width="574" alt="image" src="https://github.com/microsoft/vscode/assets/6801309/89dee33d-400a-4396-ac56-d3b91c0c3410">

---

For added context, I'm using the query in the URI to trick VSCode into thinking the file I'm opening in the custom editor is not the same as the file opened in the default editor so undo/redo aren't shared:

<img width="1508" alt="image" src="https://github.com/microsoft/vscode/assets/6801309/aff3e6e3-7221-4e3d-9fbb-8f19df297c4d">

**Comment by itsdouges** [comment] 2024-08-26 10:34
@jrieken I see you're assigned to this issue. Anything that I can help you debug?

**Comment by jrieken** [comment] 2024-12-11 14:13
same/related https://github.com/microsoft/vscode/issues/212363

**Comment by jrieken** [comment] 2024-12-12 10:55
I believe this is because workspace associations are not considering the query-part of the URI, right @bpasero? Should we invest in this and make sure our TST understands/honors the query-part? A similar problem was discussed for search here https://github.com/microsoft/vscode/issues/227836

**Comment by jrieken** [comment] 2024-12-12 10:58
actually closing as dupe of https://github.com/microsoft/vscode/issues/212363 which has a little more context

**Closed by jrieken** 2024-12-12 10:58 UTC
Labels: uri, workbench-workspace

**Comment by itsdouges** [comment] 2024-12-12 11:24
Thanks, will follow that one. Just to make sure I'm highlighting this again:

> For added context, I'm using the query in the URI to trick VSCode into thinking the file I'm opening in the custom editor is not the same as the file opened in the default editor so undo/redo aren't shared

It's important that I can have effectively the same file open in a custom editor but not have to share its undo/redo with it.
