### ISSUE TITLE
When I write CSS, window is not responding

### ISSUE THREAD

**Issue by BGOnline-CN** [Microsoft/vscode#11362] opened 2016-09-01 02:33 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment] 2016-09-01 07:07
@BGOnline-CN can you please provide more information on how to reproduce this. Can we clone a github repository that demonstrates the behavior.

**Comment by dbaeumer** [comment] 2016-09-02 07:32
@BGOnline-CN can you reproduce this if you disable all extensions (e.g. start code with --disable-extensions)

**Comment by aeschli** [comment] 2016-09-07 18:57
Closing due to lack of information.

**Closed by aeschli** 2016-09-07 18:57 UTC
Labels: css-less-sass, needs more info
