### ISSUE TITLE
1.33.0 Performance Issue - 100% CPU Spiking - GoTo Definition taking 10+ seconds

### ISSUE THREAD

**Issue by glennflanagan** [Microsoft/vscode#71779] opened 2019-04-05 09:22 UTC
Issue Type: <b>Performance Issue</b>

Open up a large JS (JSX) project
Cmd + Click a JSX Element name
Observe slow response and spike in CPU

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	    98	  4852	code main
    9	    82	  4853	   gpu-process
   15	   262	  4854	   window (BladeMaster.jsx — autopilot-ui-components)
    0	   197	  5180	     extensionHost
  100	   524	  5185	       electron_node tsserver.js 
    0	    66	  5187	         electron_node typingsInstaller.js typesMap.js 
    0	    98	  5190	       electron_node eslintServer.js 
    0	    49	  5181	     watcherService
    0	    49	  5184	     searchService
    0	    82	  5182	   shared-process
    3	    66	  5413	   window (Process Explorer)
    0	    82	  5454	   window (Issue Reporter)
    0	     0	  5460	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BladeMaster.jsx — autopilot-ui-components)
|    Folder (autopilot-ui-components): 722 files
|      File types: js(342) jsx(316) snap(24) png(10) json(6) map(4) html(3)
|                  md(2) npmrc(1) prettierignore(1)
|      Conf files: package.json(1) launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.1
language-hugo-vscode|bud|0.11.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
language-postcss|cpy|1.0.5
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
svg|joc|0.1.4
vscode-styled-components|jpo|0.0.26
chat|kar|0.12.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
vsliveshare|ms-|1.0.18
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
vscode-docker|Pet|0.6.1
sort-lines|Tyr|1.8.0
es-quotes|vil|0.2.6

(1 theme extensions excluded)

</details>

**Comment by glennflanagan** [comment] 2019-04-05 09:23
![Screenshot 2019-04-05 at 10 20 59](https://user-images.githubusercontent.com/5485364/55617770-c1349f00-578c-11e9-88ef-bf7427b530d9.png)
Looks like its TSSERVER that's the culprit

**Comment by glennflanagan** [comment] 2019-04-05 09:25
This still occurs with all extensions disabled. Here is my code --status

```
Version:          Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS Version:       Darwin x64 18.5.0
CPUs:             Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)
Memory (System):  16.00GB (1.15GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    6	    98	  5636	code main
    9	    66	  5637	   gpu-process
   16	   246	  5638	   window (Blade.jsx — autopilot-ui-components)
    0	    98	  5964	     extensionHost
   91	   492	  5967	       electron_node tsserver.js
    0	    66	  5982	         electron_node typingsInstaller.js typesMap.js
    0	    49	  5965	     watcherService
    0	    82	  5966	   shared-process

Workspace Stats:
|  Window (Blade.jsx — autopilot-ui-components)
|    Folder (autopilot-ui-components): 722 files
|      File types: js(342) jsx(316) snap(24) png(10) json(6) map(4) html(3)
|                  md(2) npmrc(1) prettierignore(1)
|      Conf files: package.json(1) launch.json(1) settings.json(1)
```

**Comment by zhrk** [comment] 2019-04-05 09:29
Same issue on windows 10 with clean install.

**Comment by jberroa** [comment] 2019-04-05 14:17
I am having the same issue

**Comment by pedromarquesm** [comment] 2019-04-05 16:21
my answer in another issue:
> I actually found what was causing all this issues.
> This new version set the Typescript version to be used, as the default of VS Code, instead of the version inside the project/workspace.
> So, all of a sudden, vs code forced typescript version 3.4.1
> ![image](https://user-images.githubusercontent.com/41088477/55640404-6b2f1e00-57c3-11e9-849f-cd5ad8133e64.png)
> access that selection. by clicking on the version , besides "Prettier" (that is enabled when .ts files are open):
> ![image](https://user-images.githubusercontent.com/41088477/55640443-7f731b00-57c3-11e9-8bda-a3f04f60dadd.png)

**Comment by pedromarquesm** [comment] 2019-04-05 16:22
I have not confirmed yet, but apparently, version 3.4.1 is causing all this issues.
VS Code new version simply put that version as default

**Comment by mjbvz** [comment] 2019-04-05 22:42
Duplicate of #71751 

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

If that doesn't solve the issue for you, please open a new issue

**Closed by mjbvz** 2019-04-05 22:42 UTC
Labels: new release
