### ISSUE TITLE
Can't use keyboard shortcut to copy text from Extension pages

### ISSUE THREAD

**Issue by ahouse101** [microsoft/vscode#99705] opened 2020-06-09 19:57 UTC
- VSCode Version: 1.45.1
- OS Version: macOS Mojave (10.14.6)

Steps to Reproduce:

1. Open the Extensions View.
2. Open an Extension.
3. Select some text (for instance, example code), and try to copy it with Cmd/Ctrl + C

Does this issue occur when all extensions are disabled?: Yes

You can copy from Extension pages if you use the Edit menu, but it doesn't seem to recognize the standard keyboard shortcuts. I've "copied" (using keyboard shortcuts) from an Extension page a few times in the past, and then immediately closed the page, only to have to find and re-open it when I try to paste and realize nothing is on my clipboard. It's a small issue, but can be a minor annoyance when you run into it.

**Comment by gjsjohnmurray** [comment] 2020-06-09 22:31
Probably #65452. Does this problem occur for README text in all of your extensions? The linked issue seems to indicate it happens for extensions that use an iframe in their README.

**Comment by mjbvz** [comment] 2020-08-11 22:08
Seems like a duplicate of #86658. This should be fixed in VS code 1.48

**Closed by mjbvz** 2020-08-11 22:08 UTC
Labels: bug, help wanted
