### ISSUE TITLE
Show search results "incrementally" while searching

### ISSUE THREAD

**Issue by martijnthe** [Microsoft/vscode#17075] opened 2016-12-12 14:00 UTC
### Feature request

Current behavior: vscode currently gathers all search results and when the search is fully complete, the UI is updated with all the results.

Desired behavior: I wish that vscode would update the UI while searching with results that have thus far been found. In my opinion this is a much nicer user experience, especially in larger projects where full project searches can take up a long time to complete. If the desired result is found early in the search, the user should be able to select the result and jump to the code (the search should just keep going until it is completed, or if the user aborts it).

Relates to #16403

**Comment by kieferrm** [comment] 2016-12-13 05:43
@martijnthe the search results are added incrementally to the search results view. However, the perceived behavior can be different. This is mainly a question of how fast the search is, and in what clusters matches are being found. #16403 is about improving the cosmetics of the progress bar in such cases.

Marking as duplicate of #16403.

**Closed by kieferrm** 2016-12-13 05:43 UTC
Labels: duplicate

**Comment by roblourens** [comment] 2016-12-13 17:06
@martijnthe And in 1.8, you should see a faster search with available results appearing sooner, making it more obvious that they're streamed into the UI.
