### ISSUE TITLE
macOS: ⌘H to hide application does not work while a PNG editor is in focus

### ISSUE THREAD

**Issue by kconner** [microsoft/vscode#98246] opened 2020-05-20 14:24 UTC
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Open a PNG file by selecting it from the Explorer sidebar.
2. Click somewhere in the image to focus the editor.
3. Type the system global shortcut ⌘H; observe that nothing happens.
4. Close the file and type ⌘H; observe that the application hides.

The same is true of ⌘⌥H to Hide Others.

Does this issue occur when all extensions are disabled?: Yes

[Mac HIG](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/):
>In general, don’t override standard keyboard shortcuts. Users may become confused if the shortcuts they know work differently in your app.

**Comment by supermitch** [comment] 2020-06-25 18:25
Funnily ⌘ + H also fails to work when "Release Notes" tab is being viewed, but does work when other tabs are selected.

**Comment by mjbvz** [comment] 2020-11-05 20:33
Duplicate of #71800

**Closed by mjbvz** 2020-11-05 20:33 UTC
Labels: bug, help wanted, webview
