### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by lws68825** [microsoft/vscode#75041] opened 2019-06-07 03:18 UTC
When I ran npm start in terminal, I got this error:
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/lws/nodeapps/demo1/public'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1254:11)
    at createFsWatchInstance (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:155:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/lws/nodeapps/demo1/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/lws/nodeapps/demo1/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:155:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo1@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo1@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mjbvz** [comment] 2019-06-07 03:28
Possible duplicate of #64678. Does increasing the file watcher limit as described in that issue help: https://github.com/microsoft/vscode/issues/64678#issuecomment-445516533

**Comment by Tyriar** [comment] 2019-06-07 16:33
Yes this is nothing to do with VS Code.

**Closed by Tyriar** 2019-06-07 16:33 UTC
