### ISSUE TITLE
ftp-simple 실행시 오류

### ISSUE THREAD

**Issue by JaeDongKim3** [microsoft/vscode#227853] opened 2024-09-07 00:27 UTC
Type: <b>Bug</b>

ftp-simple 실행시 알수없는 문자열로 json파일이 실행되고 
알림창으로  ftp-simple:config - FTP connection setting 명령에서 오류가 발생했습니다.
Cannot create property autosave on string c 

라고 오류가 계속 반복되며 나옴,
비주얼스튜디오 삭제 및 로컬데이터 삭제후 다시 설치 실행해봐도 동일현상 발생

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.80GB free)|
|Process Argv|--crash-reporter-id 3a06decd-730b-425a-8abf-940cf9d49c20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-images|doc|1.0.3
ftp-simple|hum|0.7.6
vscode-gutter-preview|kis|0.31.2
vscode-language-pack-ko|MS-|1.93.2024090409
LiveServer|rit|5.7.9
vscode-3dviewer|sle|0.2.2
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-maven|vsc|0.44.0
five-server|yan|0.3.1
beauty|yhp|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
pme_test_c:31118331
ei213698:31121563

```

</details>

**Comment by Codingale** [comment] 2024-09-07 01:16
duplicate of #227743

**Comment by connor4312** [comment] 2024-09-07 02:24
https://github.com/microsoft/vscode/issues/227743

**Closed** 2024-09-07 02:25 UTC
Labels: *duplicate, triage-needed, new release
