### ISSUE TITLE
In Markdown preview an unused margin to the right of the preview is wasting screen space.

### ISSUE THREAD

**Issue by v217** [Microsoft/vscode#23751] opened 2017-03-31 15:35 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.10.0-14-generic
- Extensions: 

 **Please note I disabled all extensions. The problem persists!**
|Extension|Author|Version|
|---|---|---|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|md-navigate|jrieken|0.0.1|
|vscode-paste-image|mushan|0.3.0|
|pony|npruehs|0.0.4|;

---

Steps to Reproduce:

1. If I reduce the width of the right column the margin gets smaller, but remains till the images are so small that they are barely visible

   {
    "window.zoomLevel": 2,
    "files.autoSave": "afterDelay",
    "files.hotExit": "onExitAndWindowClose",
    "workbench.colorTheme": "Visual Studio Dark",
    "editor.minimap.enabled": true,
    "editor.minimap.renderCharacters": false,
    "editor.wordWrap": "on",
    "markdown.preview.fontSize": 4,
    "workbench.activityBar.visible": false,
    "markdown.preview.lineHeight": 1,
    "pasteImage.path": "./b/",
    "[markdown]":{
        "editor.minimap.enabled": false
    },
    "window.menuBarVisibility": "toggle"
    }
![screenshot from 2017-03-31 17-27-37](https://cloud.githubusercontent.com/assets/6884591/24557484/1e79ae28-1638-11e7-9561-97a67e849bfb.png)
![screenshot from 2017-03-31 17-28-06](https://cloud.githubusercontent.com/assets/6884591/24557485/1e7e10c6-1638-11e7-9ea8-71909225ac96.png)

**Comment by mjbvz** [comment] 2017-04-03 16:55
Thanks. Since you have a zoom level here, this looks like a duplicate of #5745

**Closed by mjbvz** 2017-04-03 16:55 UTC
Labels: duplicate, webview
