### ISSUE TITLE
Find with regex does not locate newlines

### ISSUE THREAD

**Issue by boringuser** [Microsoft/vscode#6847] opened 2016-05-25 00:26 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Create a new file and add a few lines of text, separated by newlines
2. Open find dialog, enable regex, use regex "\n"
3. No matches will be found. Expected behavior would be to find the newlines. Also does not work with replace, so you cannot find and replace newlines.

**Comment by Tyriar** [comment] 2016-05-25 03:00
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Closed by Tyriar** 2016-05-25 03:00 UTC
