### ISSUE TITLE
Strange selection/copy behaviour in Debug Console

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#85293] opened 2019-11-21 11:46 UTC
When trying to highlight text to copy in the debug console, it sometimes highlights a random section of text way outside of where I'm dragging. See here where I start copying halfway down the window, but as I get near the bottom, some of the text at the top gets highlighted. (Sorry you can't see my mouse, but I think you guess where it is :-))

![Nov-21-2019 11-45-34 am](https://user-images.githubusercontent.com/1078012/69335279-79e41b80-0c54-11ea-8e93-71a4550993c3.gif)

When I copy to clipboard, that "extra" text is pasted at the location where it was being highlighted:

```
Restarted application in 88ms
1
TBool: bool
TDouble: double
TInt: int
TString: String
[INFO] About to build [web]...
[INFO] Updating asset graph...
[INFO] Updating asset graph completed, took 3ms
[INFO] Running build...
[INFO] 1.0s elapsed, 5/5 actions completed.
[INFO] Running build completed, took 1.0s
[INFO] Caching finalized dependency graph...
1
TBool: bool
TDouble: double
TInt: int
[INFO] Caching finalized dependency graph completed, took 324ms
[INFO] Succeeded after 1.3s with 8 outputs (7 actions)
```

**Comment by isidorn** [comment] 2019-11-21 15:03
The issue here is that we use a virtualised tree for rendering the debug console.
Virtualised tree has a bunch of issues with native browser selection.
Even though this is not an exect duplicate of what you are seeing if we tackle this one your issue would also be tackled https://github.com/microsoft/vscode/issues/2163
Due to that I will close this as a duplicate

**Closed** 2019-11-21 15:03 UTC
Labels: *duplicate, debug
