### ISSUE TITLE
Distorted Webview

### ISSUE THREAD

**Issue by alexzerntev-raw** [microsoft/vscode#140959] opened 2022-01-19 08:36 UTC
Issue Type: <b>Bug</b>

I filed the issue report here https://github.com/microsoft/vscode-extension-samples/issues/547 . But the answer was to report it to VS Code therefore I'am reporting it here.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.11.0-43-generic
Restricted Mode: No

**Comment by mjbvz** [comment] 2022-01-26 20:31
Duplicate of #110450

**Closed by mjbvz** 2022-01-26 20:31 UTC
