### ISSUE TITLE
Powershell debugger not working

### ISSUE THREAD

**Issue by kirilan** [Microsoft/vscode#56669] opened 2018-08-17 11:26 UTC
Issue Type: <b>Bug</b>

I uninstalled the old release that requires admin privileges and installed the latest user environment distribution today.  I only use 2 extensions VSTS and PowerShell. VSTS works as expected however PowerShell throws and initiation error upon start and never loads. 

8/17/2018 2:22:54 PM [NORMAL] - Visual Studio Code v1.26.1 64-bit
8/17/2018 2:22:54 PM [NORMAL] - PowerShell Extension v1.8.3
8/17/2018 2:22:54 PM [NORMAL] - Operating System: Windows 64-bit
8/17/2018 2:22:54 PM [NORMAL] - Language server starting --
8/17/2018 2:22:54 PM [NORMAL] -     exe: C:\WINDOWS\SysWow64\WindowsPowerShell\v1.0\powershell.exe
8/17/2018 2:22:54 PM [NORMAL] -     args: C:\Users\dimitrks\.vscode\extensions\ms-vscode.powershell-1.8.3\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.8.3'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\dimitrks\.vscode\extensions\ms-vscode.powershell-1.8.3\modules'-EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\dimitrks\.vscode\extensions\ms-vscode.powershell-1.8.3\logs\1534504974-93e7d3a9-2909-4ec3-ad58-7ceea3298a671534504952330\EditorServices.log' -SessionDetailsPath 'C:\Users\dimitrks\.vscode\extensions\ms-vscode.powershell-1.8.3\sessions\PSES-VSCode-22212-787020' -FeatureFlags @()
8/17/2018 2:22:54 PM [NORMAL] - Syntax Folding Provider registered
8/17/2018 2:23:54 PM [NORMAL] - Language server startup failed.
8/17/2018 2:23:54 PM [ERROR] - The language service could not be started: 
8/17/2018 2:23:54 PM [ERROR] - Timed out waiting for session file to appear.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.37GB free)|
|Process Argv|C:\Users\dimitrks\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.8.3
team|ms-|1.136.0

</details>

**Comment by sandy081** [comment] 2018-08-20 07:56
@joaomoreno Looks like the user installation cannot run the powershell.exe?

**Comment by joaomoreno** [comment] 2018-08-21 08:45
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/1048

**Closed by joaomoreno** 2018-08-21 08:45 UTC
Labels: new release
