### ISSUE TITLE
Comparing notebooks does not allow search and does not remember page position

### ISSUE THREAD

**Issue by minhtriet** [microsoft/vscode#158496] opened 2022-08-18 14:49 UTC
- Version of VS Code: Version: 1.70.2 (Universal). Commit: e4503b30fc78200f846c62cf8091b76ff5547662
- Your operating system: Mac Monterey
- List of extensions that you have installed: None
- Reproducible steps (1... 2... 3...) that cause the issue
  1. Select two ipynb files, right click, choose "Compare Selected"
  2. Select the comparing tab
- What you expected to see, versus what you actually saw
  1. Expected: Cmd F (Search) should work. Saw: Doesn't work
  3. Expected: When viewing to another tab and switch back to the compare tab, the current position in the page should not change. Saw: Cursor goes to the first line

**Comment by DonJayamanne** [comment] 2024-08-27 00:59
Duplicate of https://github.com/microsoft/vscode/issues/190390

**Closed by DonJayamanne** 2024-08-27 00:59 UTC
Labels: feature-request, notebook-diff
