### ISSUE TITLE
Freezing UI 

### ISSUE THREAD

**Issue by ynno** [Microsoft/vscode#21139] opened 2017-02-22 14:31 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jslint|ajhyndman|1.2.1|
|theme-atom-one-dark|andischerer|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|ejs-language-support|QassimFarid|0.0.1|

---

Steps to Reproduce:

1.  just press tab on  line 439 precisely then the UI is completely freezing
[styles.zip](https://github.com/Microsoft/vscode/files/793759/styles.zip)

**Comment by roblourens** [comment] 2017-02-23 00:10
Not sure what you mean by "tabulate"

**Comment by bpasero** [comment] 2017-02-23 05:57
I suspect emmet here.

**Comment by ynno** [comment] 2017-02-23 11:46
Sorry, i was meaning : press tab on line 439

**Comment by ramya-rao-a** [comment] 2017-02-23 20:35
Duplicate of #8135
Fixed with #19655

The fix is available in the 1.10 insiders build

**Closed by ramya-rao-a** 2017-02-23 20:35 UTC
