### ISSUE TITLE
Add Labels toolbar item only shown on hover over title bar

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#172163] opened 2023-01-24 13:52 UTC
Testing microsoft/vscode-pull-request-github#4433

Makes it hard to discover. I see other views showing toolbar items at all times. Can the PR extension do this too?

**Comment by alexr00** [comment] 2023-01-24 14:03
@chrmarti We're going to re-design the "create" view and integrate the label selection in there, so this should improve after that.

@mjbvz there's a difference between how webview views and tree views show the title bar actions:
- Tree views show the title actions when the mouse is over anywhere in the view 
- Webview views show the title actions only when the mouse is over the title bar

**Comment by mjbvz** [comment] 2023-01-24 18:40
Duplicate of #109030

**Closed by mjbvz** 2023-01-24 18:40 UTC
