### ISSUE TITLE
Sidebar defaults to open with no way to default to closed

### ISSUE THREAD

**Issue by Snugug** [microsoft/vscode#231654] opened 2024-10-18 11:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0
- OS Version: MacOS 14.6.1 (although also a problem in Debian)

Steps to Reproduce:

1. Open a file from the command line (VSCode as default text editor->`open file.ext`
2. Notice the Primary Side Bar is visible
3. Close the primary side bar (either with CMD+B or through the Appearance menu)
4. Open another file from the command line
5. Notice the primary side bar is open again.

This is a new bug I believe introduces in the September release

**Comment by Snugug** [comment] 2024-10-18 13:01
Updated to 1.94.2 (per suggestion) and it's still happening

**Comment by gjsjohnmurray** [comment] 2024-10-18 15:09
/duplicate of https://github.com/microsoft/vscode/issues/230575

**Closed** 2024-10-18 15:11 UTC
Labels: *duplicate
