### ISSUE TITLE
Setting timeline.pageSize incorrect expected type

### ISSUE THREAD

**Issue by MithicSpirit** [microsoft/vscode#99005] opened 2020-06-02 03:28 UTC
Issue Type: <b>Bug</b>

The `timeline.pageSize` setting should accept `number | null` but instead only accepts `number`, even though the default value is `null`. This leads to an issue where the user always gets the error message `Setting has an invalid type, expected "number". Fix in JSON.` even when it is set to the default option.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 3393)|
|Memory (System)|12.44GB (11.53GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
discord-vscode|icr|3.14.0
remote-wsl|ms-|0.44.2
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
lilypond|tru|0.0.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
latex-workshop|Jam|8.9.0
python|ms-|2020.5.80290
cpptools|ms-|0.28.2
vsliveshare|ms-|1.0.2236
color-highlight|nau|2.3.0
vscode-gitignore-generator|pio|1.0.1
code-spell-checker|str|1.9.0
code-spell-checker-portuguese-brazilian|str|0.1.2
code-spell-checker-spanish|str|1.0.3

(1 theme extensions excluded)

</details>

EDIT: Upon some inspection in the code I suspect that the issue is related to this line:
https://github.com/microsoft/vscode/blob/9d856be6628cf52d9fdd98501e16dd1d0f0f680a/src/vs/workbench/contrib/timeline/browser/timeline.contribution.ts#L51

**Comment by gjsjohnmurray** [comment] 2020-06-02 06:09
/duplicate of #97308 which is fixed in the upcoming release.

**Closed** 2020-06-02 06:09 UTC
Labels: *duplicate
