### ISSUE TITLE
No-selection copy/paste omits newline on first execution

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#42110] opened 2018-01-24 17:39 UTC
- VSCode Version:1.19.2
- OS Version:Win10
- Does this issue occur when all extensions are disabled?: Yes

A copy/paste without a selection behaves incorrectly on the first execution.  It works correctly on subsequent executions for the same x,y location

Steps to Reproduce:

1.  Move cursor to new x,y location
2.  Copy, Paste ```expected line to be duplicated, instead inserted line into existing```
3. Undo
4. Copy, Paste ```duplicates line as expected```

![paste](https://user-images.githubusercontent.com/3818866/35347479-dcb93c84-00fa-11e8-8903-3ec09841eee9.gif)

**Comment by rebornix** [comment] 2018-09-05 22:03
@mfrost66 I can't reproduce this issue in latest version, could you please give it a try?

**Comment by mfrost66** [comment] 2018-09-06 12:59
After 9 months, why bother pretending? Y'all should be honest and disable
the issues feature of the site.

**Comment by rebornix** [comment] 2018-09-10 20:47
@mfrost66 sincerely sorry that I didn't respond in time, this issue kind of buries in my inbox. That's my mistake.

I'm going through all issues assigned to me and see if I miss anything important. It would be great if you can provide further information. But sorry for bothering anyways.

**Closed** 2018-09-17 23:08 UTC
Labels: editor, editor-clipboard, needs more info
