### ISSUE TITLE
Continuous High CPU usage

### ISSUE THREAD

**Issue by zehawki** [microsoft/vscode#181168] opened 2023-04-28 22:11 UTC
Type: <b>Bug</b>

Constant high CPU usage by this task, no lower than 25% and increasing upto 50%. Killing it has effect, it starts again immediately. Only way to make it stop is to close and reopen the Local VSCode window (no issue seen on WSL side).

Issue is seen only since last 15 days.

From Process Explorer under Local > code main > extensionHost

`electron-nodejs ("C:\Users\xyz\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\xyz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\xyz\AppData\Local\Temp\vscode-typescript\38388456fe3450ec9b41\tscancellation-6e23f13f2019cb0ad875.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)`

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.56GB free)|
|Process Argv|--crash-reporter-id 5beb9600-8880-40a9-ab9b-bda1e4070ff2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|Memory (System)|1.94GB (0.40GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.77.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by zehawki** [comment] 2023-04-30 11:44
VSCode is impossible to use like this. Even restarting VSCode is no longer stopping this.

**Comment by zehawki** [comment] 2023-05-01 14:48
Ive narrowed it down as follows - as soon as a few pages are opened for editing, the issue starts. When I close the pages, it stops. And then the cycle continues. What a joke.

**Comment by mjbvz** [comment] 2023-05-01 18:12
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by zehawki** [comment] 2023-05-01 23:40
(All extensions except WSL were uninstalled as part of my debugging before I raised this issue.)

Here's another update - the issue has completely disappeared. I downgraded to v1.76.2, and then VS Code updated itself back to 1.77.3 and now its back to normal. No persistent CPU usage anymore.

**Comment by mjbvz** [comment] 2023-05-02 19:12
Closing since it sounds like the issue is not reproducible

**Closed by mjbvz** 2023-05-02 19:12 UTC
Labels: info-needed

**Comment by zehawki** [comment] 2023-05-03 10:01
And we are back with the exact same issue.

**Comment by zehawki** [comment] 2023-05-04 12:05
And we are back. This happened yesterday, but it wasnt for long. Today its just stuck again with CPU churning away upto 50%.

**Comment by zehawki** [comment] 2023-05-05 16:06
@mjbvz FYI - I downgraded again to v1.76.2, and turned off auto VS Code update. No persistent CPU usage anymore since yesterday.

**Comment by switchyrascal** [comment] 2023-06-06 16:41
I am seeing this also on anything newer than v1.76. What would be useful information to collect and what would be the easiest way to do that?
