### ISSUE TITLE
Extension details for globally enabled extensions overflows pane on Mac

### ISSUE THREAD

**Issue by kschaab** [microsoft/vscode#90105] opened 2020-02-05 22:07 UTC
Issue Type: <b>Bug</b>

1. Navigate to a globally enabled extension (with green star).
2. Select the details for it.
3. Note the content will flow out and cover part of the status bar.

Image of the issue:
![image](https://user-images.githubusercontent.com/7329029/73887550-a3a6ea80-4820-11ea-89bf-6f627d6da111.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.34.0
jshint|dba|0.10.21
i3|dca|0.0.1
gitlens|eam|10.2.0
tsl-problem-matcher|eam|0.1.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.11
shell-format|fox|7.0.1
cloudcode|goo|1.1.1
hg|mrc|1.3.0
vscode-docker|ms-|0.10.0
vscode-kubernetes-tools|ms-|1.0.9
python|ms-|2020.1.58038
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.49.0
csharp|ms-|1.21.10
Go|ms-|0.13.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
show-offset|ram|0.0.4
java|red|0.55.1
vscode-yaml|red|0.6.1
code-settings-sync|Sha|3.4.3
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vim|vsc|1.12.4

</details>

**Comment by mjbvz** [comment] 2020-02-05 22:23
Duplicate of #83209

**Closed by mjbvz** 2020-02-05 22:23 UTC
