### ISSUE TITLE
Terminal Sticky Scroll does not show all lines each time

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#199273] opened 2023-11-28 08:40 UTC
Testing #199240

I ran the following command twice in a row. Running it the first time displayed the 3 lines of the multi line command in the sticky scroll. In the second run it only showed the first line of the command.

powershell command: ping 8.8.8.8; >> ping 8.8.8.8; >> ping 8.8.8.8

(>> is new line)

used setting terminal.integrated.stickyScroll.maxLineCount: 3

![Recording 2023-11-28 at 09 39 19](https://github.com/microsoft/vscode/assets/44439583/6923073c-e7c2-4240-b0e5-a4a57904467a)

**Comment by Tyriar** [comment] 2024-12-10 14:52
Hard to capture the exact frame, but at one point the mouse hovers over the previous command and you can see it's extended a little further down. Because of this it looks like the cause is sequences on Windows and it should get fixed by conpty v2

/duplicate https://github.com/microsoft/vscode/issues/224488

**Closed by Tyriar** 2024-12-10 14:52 UTC
Labels: bug, windows, terminal-sticky-scroll
