### ISSUE TITLE
Unable to save to OneDrive.

### ISSUE THREAD

**Issue by wayneluke** [Microsoft/vscode#31766] opened 2017-07-31 17:40 UTC
When attempting to save to OneDrive while "Instance Access" is enabled, I get the following error:
A system error occurred (EINVAL: invalid argument, stat 'c:\Users\Wayne\OneDrive\vBulletin\Release Docs\Patch 5.3.2')

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mdhelper|jos|0.0.11
markdown-shortcuts|mdi|0.8.1
material-icon-theme|PKi|2.0.11

---

Steps to Reproduce:

1. Create a text file.
2. Attempt to save in a OneDrive folder.

Reproduces without extensions: Yes

**Comment by jens1o** [comment] 2017-07-31 22:32
Duplicate of all these issues: https://github.com/Microsoft/vscode/issues?q=assignee%3Abpasero+is%3Aclosed+Onedrive+label%3Aworkbench

**Comment by bpasero** [comment] 2017-08-11 07:26
https://github.com/Microsoft/vscode/issues/27285

**Closed by bpasero** 2017-08-11 07:26 UTC
Labels: workbench
