### ISSUE TITLE
Window Page Scroll commands need to preserve selection.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#16248] opened 2016-11-30 03:44 UTC
When running the "editorScroll" command, I would like an option to extend the current selection to the new location of the cursor.

We need this over in VSCodeVim: https://github.com/VSCodeVim/Vim/issues/907

Thanks! You guys are the best. 😄

**Comment by alexandrudima** [comment] 2016-12-13 09:35
fyi @sandy081

**Comment by alexandrudima** [comment] 2017-04-27 19:49
Duplicate of #22147

**Closed by alexandrudima** 2017-04-27 19:49 UTC
Labels: editor, feature-request, VIM
