### ISSUE TITLE
Produce like white blurr/ white glitch appear on vs code

### ISSUE THREAD

**Issue by danielteatsy** [microsoft/vscode#105275] opened 2020-08-24 08:31 UTC
![Screenshot (276)](https://user-images.githubusercontent.com/69977348/91022072-3ecda900-e627-11ea-82ea-4fc324967d67.png)
We have written the needed data into your clipboard because it was too large to send. Please paste.
![Screenshot (277)](https://user-images.githubusercontent.com/69977348/91022080-41300300-e627-11ea-943b-d3ba851efda9.png)
Every time I using visual code , white blurr/ white glitch appear on my screen for vs code. I have tried update the version package for vs code and I also tried uninstall or install method it still appear on my screen.

**Comment by gjsjohnmurray** [comment] 2020-08-24 09:39
Is this problem reproducible if you launch it like this from a Windows command prompt?

`code --disable-gpu`

More details [here](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration).

**Comment by IllusionMH** [comment] 2020-08-24 13:27
Duplicate of #93356 or #94523

**Comment by RMacfarlane** [comment] 2020-08-25 00:44
Thanks @IllusionMH, closing as a duplicate of #93356.

**Closed by RMacfarlane** 2020-08-25 00:44 UTC
