### ISSUE TITLE
Indexing project files using CTRL+P is ridiculously slow as compared to other IDEs

### ISSUE THREAD

**Issue by haisum** [Microsoft/vscode#2877] opened 2016-02-10 08:00 UTC
I opened a large project with a lot of Java + bash files and CTRL+P takes forever to find and list a file. Same project gets file list indexed almost immediately when I open it in sublime text and CTRL+P file search works smooth as butter. VSCode needs to improve performance of file search.

**Comment by bpasero** [comment] 2016-02-29 14:08
Duplicate of https://github.com/Microsoft/vscode/issues/55

**Closed by bpasero** 2016-02-29 14:08 UTC
