### ISSUE TITLE
after close vscode ,  find -L . type f command consule all cpus

### ISSUE THREAD

**Issue by getmonyinfo** [Microsoft/vscode#34380] opened 2017-09-14 13:31 UTC
- VSCode Version:1.16.0 (1.16.0)
- OS Version: osx 12.6

Steps to Reproduce:
sometimes when i close  a  workspace which contains 225973 file, the command 
```bash
find -L .type f 
```
will consume all cpus
<img width="1161" alt="2017-09-14 9 19 37" src="https://user-images.githubusercontent.com/2359621/30432333-ee5b4090-9926-11e7-9608-c12ea1dbb136.png">

**Comment by chrmarti** [comment] 2017-09-14 15:11
Could you try the latest insiders build and see if it reproduces? You should see `rg` rather than `find` processes there, I'd expect these to run faster.

Also: Does Quick Open (Cmd + P) allow you to open files? Which extensions do you have installed (`code --list-extensions`)?

**Comment by getmonyinfo** [comment] 2017-09-15 02:59
i don't have much extension
```bash
code --list-extensions
HookyQR.beautify
donjayamanne.python
johnpapa.Angular2
lukehoban.Go
ms-vscode.csharp
xabikos.ReactSnippets
```
vscode config file
```bash
// 将设置放入此文件中以覆盖默认设置
{
    "workbench.colorTheme": "Visual Studio Light",
    "markdown.styles": [
        "file:///Users/a/Library/Application%20Support/Code/User/github-markdown.css"
    ],
    "extensions.ignoreRecommendations": false,
    "files.autoSave": "afterDelay",
    //这里要设置， 否则在jsx中不能用emmet
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "vue-html": "html",
        "plaintext": "jade"
    },
    "window.zoomLevel": 0,
    "editor.fontSize": 13,
    "files.exclude": {
        // include the defaults from VS Code
        "**/.git": true,
        "**/.DS_Store": true,

        // exclude .js and .js.map files, when in a TypeScript project
        "**/*.js": { "when": "$(basename).ts"},
        "**/*.spec.ts": { "when": "$(basename).ts"},
        "**/*.js.map": true,
        "**/node_modules": true
    },
    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true
    }
}
```

when in the workspace the following command consume a lot of cpu
<img width="1278" alt="2017-09-15 10 58 01" src="https://user-images.githubusercontent.com/2359621/30464568-dc152baa-9997-11e7-9c14-fdae64a51704.png">

**Comment by chrmarti** [comment] 2017-09-25 20:38
Duplicate of #34434

**Closed by chrmarti** 2017-09-25 20:38 UTC
Labels: needs more info, new release
