### ISSUE TITLE
Maximum call stack size exceeded on JavaScript file format

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#26002] opened 2017-05-05 08:09 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Open JavaScript file with wrong indentation
2. Hit Shift+Alt+F
3. Maximum call stack size exceeded

**Comment by mjbvz** [comment] 2017-05-05 08:15
This may be caused by an extension. Can you please try disabling all extensions by starting code with the `--disable-extensions` command line flag and seeing if this still reproduces

**Comment by con-ssc** [comment] 2017-05-05 12:47
I cannot reproduce the error without extensions. How can I find out which extension is causing the problem?

**Comment by mjbvz** [comment] 2017-05-05 19:03
There's not a great story for this currently but we are looking to improve this: #25695

Try disabling the extensions that contribute js formatters first. Then if you still see the issue, try disabling any extension that is activate in js files. You can also try disabling all extensions and then enabling individual ones until the error appears. I know the process is pretty poor here, sorry about that

Closing as caused-by-extension

**Closed by mjbvz** 2017-05-05 19:03 UTC
Labels: caused-by-extension, javascript, needs more info

**Comment by mjbvz** [comment] 2017-05-05 19:04
You may also want to try opening the developer console (`Toggle Developer Tools`) and inspecting the logs there. That ay give a clue as to what is going wrong
