### ISSUE TITLE
A new profile cannot be created based on one of the templates

### ISSUE THREAD

**Issue by sergiecode** [microsoft/vscode#225403] opened 2024-08-12 13:29 UTC
Does this issue occur when all extensions are disabled?:  Yes

- VS Code Version: 1.92.1
- OS Version:  Windows 11

Steps to Reproduce:

1. Click on "Manage" (Gear icon) 
2. Profile(default)
3. New Profile
4. When I select one of the templates, it says:
'The profile should contain at least one configuration.'
None of the checkboxes can be selected

![image](https://github.com/user-attachments/assets/06796a31-2c1c-477f-8548-007ff6e52936)

**Comment by sergiecode** [comment] 2024-08-12 13:30
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.92.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I'm in the lastest stable release! It's updated

**Comment by gjsjohnmurray** [comment] 2024-08-12 14:18
/duplicate of #224788 which gives a workaround

**Closed** 2024-08-12 14:20 UTC
Labels: *duplicate
