### ISSUE TITLE
Go to definition of default import 

### ISSUE THREAD

**Issue by orenklein** [Microsoft/vscode#23677] opened 2017-03-30 15:19 UTC
I'm not sure if it's TypeScript issue or VS Code issue.
When directly importing the default of a module - 
Go to definition of a reference of the imported object goes to the import line and not to the module (then clicking Go to definition again goes to the module file).

Explicitly setting an alias is giving the expected behaviour. 

![](https://media.giphy.com/media/l4FGylPFatd8M2Jvq/giphy.gif)

- VSCode Version: 1.10.2
- OS Version: OSX 10.11.6

**Comment by mjbvz** [comment] 2017-04-03 18:19
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/12504

From the discussion on the bug, it sounds like the feature is currently working as intended but I know the behavior has been tweaked in the past

**Closed by mjbvz** 2017-04-03 18:19 UTC
Labels: typescript, upstream
