### ISSUE TITLE
SCM Graph - How about some actions on these commits? "Revert commit" "reset commit", etc

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#218207] opened 2024-06-25 20:09 UTC
Testing #217398

<img width="373" alt="image" src="https://github.com/user-attachments/assets/aade16f2-33ae-485e-a2bb-7134e08328cd">

It'd be cool if I could right click on one of the commits and revert or reset it in case I accidentally commit or something.

**Comment by lszomoru** [comment] 2024-12-10 12:46
Closing as duplicate of [#217987](https://github.com/microsoft/vscode/issues/217987)

**Closed by lszomoru** 2024-12-10 12:46 UTC
Labels: feature-request, git, scm
