### ISSUE TITLE
左下角提示：更新不可用

### ISSUE THREAD

**Issue by tianyunperfect** [Microsoft/vscode#35945] opened 2017-10-10 02:49 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
typings-installer|ben|0.2.0
markdown-preview-github-styles|bie|0.0.4
GBKtoUTF8|buk|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
Python-autopep8|him|1.0.2
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
docthis|joe|0.4.8
MagicPython|mag|1.0.12
csharp|ms-|1.12.1
view-in-browser|qin|0.0.5
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
python|tht|0.2.3
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-10 06:40
Translation: Bottom left corner Tip: Update is not available

@tianyunperfect Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by tianyunperfect** [comment] 2017-10-10 07:59
![default](https://user-images.githubusercontent.com/23491291/31375246-799088bc-add3-11e7-983e-9e3349b1cb90.png)
I can not update to the most recent version, and In the help menu, I also can not find the update button,
Thanks for your help.

**Comment by egamma** [comment] 2017-10-11 14:15
@tianyunperfect it looks like the menu item is disabled and this is the case when the update is being downloaded. Can you restart VS Code and try again please.

**Comment by egamma** [comment] 2017-10-16 06:45
Closing please reopen if the issue can be reproduced.

**Closed by egamma** 2017-10-16 06:45 UTC
Labels: needs more info

**Comment by tianyunperfect** [comment] 2017-10-16 08:35
Thanks a lot, Perhaps because of national policy or something, it still can't update. Fortunately, its function has no problem。

**Comment by yume-chan** [comment] 2017-10-19 10:11
![image](https://user-images.githubusercontent.com/1330321/31765853-6732de6e-b4f8-11e7-97cc-56fa8cc4b042.png)

Auto update is only available in Code installed by the installer, not the zip portable version.

@tianyunperfect did you install your Code with the installer?

**Comment by tianyunperfect** [comment] 2017-10-20 01:51
@yume-chan 
You are a genius, This is my problem.  best wishes to you.
