### ISSUE TITLE
Starting Debug from the status bar should use the current configuration

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#40164] opened 2017-12-13 12:52 UTC
If the point of being able to start debugging from the status bar is that it is a shortcut, then why does it popup the configuration chooser menu? 

Surely it should just start the debugger with the configuration that is displayed? Otherwise you end moving the mouse further than you would if you just opened the debug view...

**Comment by ramya-rao-a** [comment] 2017-12-13 19:49
@isidorn I thought this was by design and that the intention was to 
- Know which config is being used when pressing F5 to start debugging (or using the start debugging command from cmd pallet) without having to go to the debug viewlet
- and to be able to change the debug configuration without going to the debug viewlet

**Comment by isidorn** [comment] 2017-12-14 09:28
@ramya-rao-a yes, closing by design

**Closed by isidorn** 2017-12-14 09:28 UTC
Labels: debug, feature-request
