### ISSUE TITLE
Visual Studio Code automatically open new 0 tab when building .csproj with PreBuild event

### ISSUE THREAD

**Issue by phucan1108** [Microsoft/vscode#40836] opened 2017-12-26 14:59 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.16
gitlens|eam|7.1.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
webpack|jer|2.0.2
es-query|jit|0.0.6
Angular2|joh|2.11.2
Angular-BeastCode|Mik|5.1.15
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|4.0.0
html-preview-vscode|tht|0.1.1

---

Steps to Reproduce:

1. Install both VS Code and VS Community 2017 15.5.2
2. Create Sample.csproj and AnotherProject.csproj by VS Community 2017 (VS Code isn't opened)
3. Write the sample .ps1 file such as 'dotnet build AnotherProject.csproj -output C:\temp' and run this powershell script by PreBuild event on Sample.csproj with command "powershell -ExecutionPolicy Unrestricted -File .\sample.ps1"
4. Rebuild the Sample.csproj, the sample.ps1 is calling
5. The VS Code automatically open with the '0' tab when building. The build process has been blocked
6. Close the VS Code and the build process is unblocked and stopped
7. Uninstall VS Code and I can run sample.ps1 normally
![vscodezerotab](https://user-images.githubusercontent.com/6330899/34358891-0ee8d254-ea86-11e7-97c1-715c252c6ac6.JPG)

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-12-27 17:57
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by phucan1108** [comment] 2017-12-29 04:32
Hi @bpasero ,

I have executed `code --disable-extensions` but seems it still happens. Also, I have just resolved that by reinstalling VS Code again BUT remove checkbox 'Add to PATH' while installing. And it is working well. I thought it's just the temporary solution.

Thanks,
Johnathan

**Comment by bpasero** [comment] 2018-01-03 10:19
@phucan1108 what is the contents of `sample.ps1`?

**Comment by phucan1108** [comment] 2018-01-03 10:27
@bpasero It contains that 
`

       Param(
                [string] $buildProject
       )
       dotnet build $buildProject --output "C:\\temp"

`
My purpose is the MSBuild builds another project and copy the dll to the folder. The param is passed via argument in PreBuild event.

**Comment by bpasero** [comment] 2018-01-04 06:51
@phucan1108 the only explanation I have is that someone is calling "code 0" on the command line and this will open the file "0" as dirty in the editor. This seems to be true because as you say it does not reproduce when you do not put "code" on the path. 

Closing, as there seems nothing we can do against it.

**Closed by bpasero** 2018-01-04 06:51 UTC
Labels: needs more info
