### ISSUE TITLE
terminal integrated between editors

### ISSUE THREAD

**Issue by juanfv2** [microsoft/vscode#112309] opened 2020-12-11 17:40 UTC
Sometimes I use the terminal open widely for see all log possible, So I wonder if you can do it that the "terminal integrated" can be open like a "tab" between "editors". Example "app.component.ts" || "terminal"

**Comment by meganrogge** [comment] 2020-12-11 22:57
Duplicate of #33060

**Closed by meganrogge** 2020-12-11 22:57 UTC
