### ISSUE TITLE
Commit message(s) disappear after undoing the last commit

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/vscode#198975] opened 2023-11-23 21:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: Windows 11 x64 (22H2, 22621.2715)

<br>
<br>

Hello, I am the original author of the issue #178460 (**_Use only unique commit messages for auto-complete_**) and so far the implemented solution worked quite well but what I noticed is that commit message(s) disappear after undoing the last commit *(not sure if the new solution brought this issue)*.

Steps to Reproduce:

1. Open a local project that's a Git repository
2. Make some changes
3. **IMPORTANT**: make sure to have multiple commit messages available as auto-complete
4. Cycle through the commit messages, pick one (but a wrong one, accidents do happen! 😉)
5. Commit with that message
6. Since the message is **wrong** - click on the Source dot menu
7. Click on Commit > Undo Last Commit
8. Pick the correct commit message
9. Commit with the correct message and see the commit message from step 4 disappearing (for good...)

> In my case the commit message *"❌ [optimization]: remove rule"* completely disappears.

<br>
<br>

I have attached a video below since it might make things clearer. 😉

<div align="center">
	<video src="https://github.com/microsoft/vscode/assets/20957750/53156850-1fdd-43a6-b2fd-f52f1cecc848">
</div>

**Comment by lszomoru** [comment] 2023-11-24 11:33
@joaomoreno, this seems to be related to the commit message history.

**Comment by danik292** [comment] 2023-11-25 08:56
@lszomoru where is this stored?

**Comment by VDisawal** [comment] 2023-11-25 12:45
Hi @lszomoru , it would be great if I could work on this as my first open source contribution.

I have done some initial analysis and looks like this is where the issue is
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/scm/common/scmService.ts#L146

Calling saveValue replaces the value of the last item in the linked list.
Instead of this, historyNavigator.add would be better because it wouldnt replace the last existing item.

-----
Hey @danik292 , I was going through the code and looks like the linked list is stored in-memory.

**Comment by VDisawal** [comment] 2023-11-27 06:11
I just went through the contribution guide again, and looks like there's no need to particularly get the issue assigned to me before raising the PR.
I'll get the PR raised.
Thanks!

**Closed** 2024-01-08 13:48 UTC
Labels: bug, help wanted, good first issue, scm
