### ISSUE TITLE
html tag rename works only on the opening tag but not the closing tag

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#12231] opened 2016-09-18 19:26 UTC
- VSCode Version: 1.6 insider
- OS Version: win 10 x64

Steps to Reproduce:

```
1.  Create html like: <h1>hello</h1>
2. Double-click on the opening h1 string
3. h1 is selected now
4. start typing 'h' then the autosuggestion gets you h1....h6
5 choose h6 and press enter key
6 the opening tag h1 is now changed to h6
7 the closing tag h1 is still h1
8 please improve
```

**Comment by aeschli** [comment] 2016-09-19 18:10
duplicate of #11153

**Closed by aeschli** 2016-09-19 18:10 UTC
