### ISSUE TITLE
Custom views sometimes don't scroll properly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#62088] opened 2018-10-29 20:46 UTC
Issue Type: <b>Bug</b>

I haven't yet figured out the scenario, but it happens somewhat frequently that a custom view will have been updated, but it won't scroll even though it should (no scrollbar appears either). Although if I resize the view even by a pixel the scroll bar will immediately appear and scrolling is fixed.

/cc @sandy081 

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:18:55.850Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.81GB free)|
|Process Argv|C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment] 2018-10-30 10:32
@eamodio Can you please provide following details

- When do you see this issue in custom view? Is it immediately after window is loaded or later?
- Where is the custom view located?

**Comment by eamodio** [comment] 2018-10-30 13:18
> When do you see this issue in custom view? Is it immediately after window is loaded or later?

Later, and I think it is usually when the tree is updated when it isn't focused (but not sure)

> Where is the custom view located?

I've seen it when it's in it's own sidebar and under the scm sidebar

**Comment by sandy081** [comment] 2018-10-30 14:32
@joaomoreno Is this something to do with the tree layout ?

**Comment by joaomoreno** [comment] 2018-10-31 10:09
@sandy081 Very unlikely. Since a single sash nudge makes it good, it sounds like there's a missing `layout` call up the chain.

**Comment by sandy081** [comment] 2018-10-31 11:06
I thought so too in the beginning but it seems the issue happens in the middle while the tree is being updated. Is it possible that the layout is broken while updating and it got fixed with sash change?

**Comment by joaomoreno** [comment] 2018-10-31 11:37
Again, very unlikely, but I can be proven wrong. :dancer:

**Comment by joaomoreno** [comment] 2018-10-31 11:37
Again, very unlikely, but I can be proven wrong. :dancer:

**Comment by sandy081** [comment] 2018-10-31 15:47
@eamodio Are there steps to repro this otherwise I just have to do some guessing which is not helpful 😞

**Comment by eamodio** [comment] 2018-10-31 19:49
@sandy081 I've just found it is related to hiding the view (by switching to another activity) and switching back. I can reproduce this with the latest GitLens 9 alpha -- where if I size the Repositories view so that it is scrollable, and then switch away to a different sidebar and then come back, the Repositories view won't scroll.

I should mention that I am refreshing (firing an `onDidChangeTreeData`) in the `onDidChangeVisibility` event triggered by the tree becoming visible again. So my guess it is related to the timing of updates because of that.

**Comment by eamodio** [comment] 2018-11-29 05:48
@sandy081 Did something change here? I can't seem to reproduce this anymore.

**Comment by sandy081** [comment] 2018-11-29 10:19
@eamodio Nothing as I am aware of. But happy that the issue is not repro (or got fixed somehow 😄 )

**Closed** 2018-12-06 11:13 UTC
Labels: needs more info
