### ISSUE TITLE
Linux "native" has probably same color as its background

### ISSUE THREAD

**Issue by mireczatko** [Microsoft/vscode#63319] opened 2018-11-16 17:07 UTC
- VSCode Version: 1.29.1
- OS Version: Ubuntu 18.10, dark theme(Yaru)

Steps to Reproduce:
1. start code .
2. menu texts not visible 

Does this issue occur when all extensions are disabled?: Yes

problem with invisible menu is still there with 1.29.0(few days ago) and 1.29.1(I think today) release. Menu is completely invisible with ubuntu & dark theme.
It is only invisible when VSCode window is active.
As soon as I move focus to other application, menu becomes visible.

![screenshot from 2018-11-16 18-09-44](https://user-images.githubusercontent.com/2799697/48636364-f2bdf100-e9ca-11e8-919c-4d12ebaf2dac.png)

**Comment by sbatten** [comment] 2018-11-16 18:51
duplicate of #62593

**Closed by sbatten** 2018-11-16 18:51 UTC
Labels: new release
