### ISSUE TITLE
Replacing words bug

### ISSUE THREAD

**Issue by will3m5** [microsoft/vscode#71986] opened 2019-04-09 09:38 UTC
Issue Type: <b>Bug</b>

In my Symphony modules I wanted to change the word "Application\Modules\Projects" to "Application\Modules\Timeline"

After I did that on the folder I chose there was a bug. In some files Visual Studio Code is putting "Application\Modules\TimelineApplication\Modules\TimelineApplication\Modules\Timeline" many times after eachother or it isn't replace the word but it's just placing the word at the start of the file . I don't know why it is doing that. 
[Image of the bug](https://i.imgur.com/DsZrU3N.png)

I tried the same thing with Sublime Text and it's working perfectly. Hope you guys will fix this soon.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.2
twig-language-2|mbl|0.7.4
LiveServer|rit|5.5.1
vscode-icons|vsc|8.5.0

</details>

**Comment by aeschli** [comment] 2019-04-09 12:08
@BarryLC I assume you used Replace from the File Search viewlet?

**Comment by roblourens** [comment] 2019-04-10 17:27
Is it possible that your files only have CR line endings (not CRLF or LF)?

**Comment by BarryLC** [comment] 2019-04-12 08:20
@roblourens I have CRLF line endings.

**Comment by roblourens** [comment] 2019-04-12 17:17
Is it possible for you to share the file where this occurs? You can email it to me if you don't want to share it publicly. If there is a single CR character in the file then that can cause this issue.

**Comment by BarryLC** [comment] 2019-04-12 18:32
I'll send the file on Monday, can't access the file right now.

**Comment by BarryLC** [comment] 2019-04-15 07:00
@roblourens I've send you an email with the file.

**Comment by roblourens** [comment] 2019-10-08 23:50
Sorry for the slow response. This file does indeed just have CR characters. So this is a duplicate of https://github.com/microsoft/vscode/issues/48063

**Closed by roblourens** 2019-10-08 23:50 UTC
