### ISSUE TITLE
terminal output messed up

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#40800] opened 2017-12-25 05:03 UTC
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T06:08:07.643Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
vim|vsc|0.10.6
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. open terminal
2. start using it

Over time:

- I am seeing output issues.
- cursor jumps up to odd rows rather than stay at the bottom.
- typing 'clear' or pressing CTRL+L fails to clean the screen.
- typing 'reset' fails to clean up the screen.

In picture below my cursor is where the '<======' arrow was typed, there is garbage all over this screen output from previous command outputs.

![screen shot 2017-12-24 at 11 59 22 pm](https://user-images.githubusercontent.com/439226/34333070-92e03344-e906-11e7-817c-a0057617e875.png)

## After typing 'clear' looks like this:

![screen shot 2017-12-25 at 12 01 04 am](https://user-images.githubusercontent.com/439226/34333084-c438a8fe-e906-11e7-91d1-28e8b3c04571.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment] 2017-12-27 14:52
I'm having trouble reproducing this, ctrl+l, cmd+k and `clear` all work fine for me. `reset` adds `[!p` to the terminal but works other than that (looks like an escape sequence isn't supported in xterm.js). Any more info on the repro?

**Comment by Tyriar** [comment] 2017-12-29 00:09
I do notice some weird behavior after running `reset` which screws up the scroll bar/viewport so I'd stay away from that command and see if that fixes your issue.

**Comment by rajinder-yadav** [comment] 2017-12-29 06:10
My issue was the result of general usage, typing 'npm out'. I just mentioned other things I notice.

**Comment by mindplay-dk** [comment] 2018-03-11 15:47
Being unable to clear the terminal at all is really frustrating.

Per normal Linux terminal behavior, `clear` should cause existing content to scroll out of view, which works fine for me.

But `reset` should actually clear all existing content from the scroll buffer, effectively resetting the terminal, which doesn't work - this makes it very hard to read e.g. long output from a test, or long directory listings (etc.) as it's very hard to spot the start and end of each command's output while scrolling.

A command like `reset && npm run test` really needs to work like it does on a regular terminal.

**Comment by Tyriar** [comment] 2018-09-12 22:46
I can't repro, this might have been fixed with the new terminal parser?

**Closed** 2018-09-12 22:46 UTC
Labels: *not-reproducible, bug, integrated-terminal, upstream
