### ISSUE TITLE
Organize Imports feature removes import for shorthand syntax objects

### ISSUE THREAD

**Issue by solova** [Microsoft/vscode#48048] opened 2018-04-17 11:24 UTC
```javascript
import {combineReducers} from 'redux';
import {routerReducer} from 'react-router-redux';
import client from './modules/client';
import user from './modules/user';

export default combineReducers({
  router: routerReducer,
  client,
  user
});
```

Feature keeps `routerReducer` dep, but remove `client` and `user`

**Comment by mjbvz** [comment] 2018-04-17 17:38
Duplicate of #47531

**Closed by mjbvz** 2018-04-17 17:38 UTC
Labels: javascript
