### ISSUE TITLE
Intermittently swapping contents of open file with another open file on save

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Microsoft/vscode#12404] opened 2016-09-21 20:16 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:09:51.625Z)
- OS Version: Linux ia32 3.16.0-4-586

Steps to Reproduce:

This might be hard to reproduce but it's happening at least twice a day for me so I'm reporting it anyway.

*\* May be related to extension: vscode-JS-CSS-HTML-formatter **
1. open a few files, make changes in several, save all, sometimes it will format but then show as dirty, save again and intermittently it will have replaced the contents of one of the open dirty files with the contents of another.  I have seen this issue editing javascript files,
2. Can't make it do it every time unfortunately.  I suspect it's related to the auto formatting of the code before saving , I've figured out how to turn off the format on save for the vscode-JS-CSS-HTML-formatter extension and if this doesn't happen again I'll remove this case and take it up with them.

**Comment by chrmarti** [comment] 2016-10-31 17:04
A number of days has past without answer on the questions (yourself) asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by chrmarti** 2016-10-31 17:04 UTC
Labels: needs more info

**Comment by thejones** [comment] 2016-12-07 21:26
Yes! This happens to me as well. 

So far it only seems to happen when multiple files have changed and I select save all. Then it will prompt to save each and then when I re-open I end up with garbled files. 

I too have the lonefy.vscode-JS-CSS-HTML-formatter extension.

I would not reopen but there may be other cases of this happening and we can at least gather information here to try and help. 

Version 1.7.2 
OS: Windows 7

**Comment by chrmarti** [comment] 2016-12-07 22:23
Duplicate of https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/36 and maybe https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/29 and https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/27 /fyi @jrieken

**Comment by thejones** [comment] 2016-12-07 23:27
Awesome! Thanks @chrmarti
