### ISSUE TITLE
VS Code Selects Wrong Files After Disabling Sticky Tree

### ISSUE THREAD

**Issue by F1LT3R** [microsoft/vscode#212923] opened 2024-05-16 18:49 UTC
I'm not going to go through all the rigmarole you outlined here. Sorry, I just don't have time.

BUT YOU SHOULD KNOW THAT VSCODE IS DELETING THE WRONG FILES!!!

This is what happens after you disable the Sticky views on Windows and WSL2.

![deleting-wrong-files](https://github.com/microsoft/vscode/assets/1218446/315daa15-c411-4b0f-a0f6-32dd0efe9d39)

![image](https://github.com/microsoft/vscode/assets/1218446/22eb8c86-7027-4c11-afcf-77a99118a22a)

**Comment by au-top** [comment] 2024-05-17 01:31
shock

I've been encountering this problem for a long time, about 4 to 5 days

This issue almost prevents me from using vscode

Why hasn't it been fixed yet

I am surprised that such a widely used software would have such a functional bug

And it has not been fixed after I have updated vscode insiders multiple times

The issue of agreement arises in the latest vscode and vscode insiders from macos

**Comment by F1LT3R** [comment] 2024-05-19 17:35
That's right. VS Code rename is also broken for me. In fact, many interactions between the mouse and the tree are now broken.

I'm also shocked that they rolled the sticky updates out as a default without any opt-in.

**Comment by F1LT3R** [comment] 2024-05-19 17:41
And the amount of hours I lost at work from VS Code deleting the wrong directory (that I had not yet committed), is not funny in the least.

**Comment by benibenj** [comment] 2024-05-22 07:16
I'm not able to reproduce this. Also I'm not sure how sticky scroll would be related to this issue. @au-top do you have tree sticky scroll turned off when you see it happen? It also doesn't seem to be a WSL related bug as @au-top is seeing this on macOS. It seems to be some weird corner cases as there would be many more users reporting this otherwise.

@F1LT3R could you share your settings to help us debug this issue? You can also just share explorer and tree related settings if you prefer. Also, do you see this happen with your same settings on windows without WSL?

@lramos15 any idea what this could be?

**Comment by lramos15** [comment] 2024-05-22 14:15
Is VS Code focused in this case?

I currently have https://github.com/microsoft/vscode/issues/211806 tracking that this doesn't work right when right click cannot capture focus

**Comment by au-top** [comment] 2024-05-23 11:04
identical https://github.com/microsoft/vscode/issues/211806

**Comment by benibenj** [comment] 2024-05-23 15:33
Closing as duplicate

**Closed by benibenj** 2024-05-23 15:33 UTC
Labels: info-needed
