### ISSUE TITLE
Code Stash feature

### ISSUE THREAD

**Issue by devmahdi404** [microsoft/vscode#128343] opened 2021-07-09 18:06 UTC
**Sometimes** we delete a block of code and later we want it back. And reaching it out by undoing is not so efficient and some time not possible. Also it is not persistent. If we close the editor, we lose it.

I think a persistent code stash feature would be very useful.

**Comment by IllusionMH** [comment] 2021-07-09 18:27
Not clear - you want manually stash code or some history?

Later is duplicate of #26339

**Comment by devmahdi404** [comment] 2021-07-10 08:31
Well yes. I was talking about manually stash a block of code or a whole file.

But It seems feature request #26339 is much powerful than this. Since I never used Intellij Idea, I didn't think like that.

So, I think we can merge this issue into #26339

**Comment by IllusionMH** [comment] 2021-07-10 21:40
For manually storing code blocks you can search for extension that can suit you. I used [Code Fragments](https://marketplace.visualstudio.com/items?itemName=markvincze.code-fragments) for simiar cases. Bu there should be few more.

For file history you should definitely upvote that issue and it make sense to close this one. In the mean time - I think there were couple of extension that wored with file history as well.

**Comment by devmahdi404** [comment] 2021-07-10 22:50
The [Code Fragments](https://marketplace.visualstudio.com/items?itemName=markvincze.code-fragments) extension is almost as like as I wanted. I am quite satisfied with it. 

And yeah, I will definitely upvote that [Local History](https://github.com/microsoft/vscode/issues/26339) feature request. As much I searched, there were few extensions which was providing a kind of feature like that but not so good as the **Intellij Idea**  one. No need to say that it will awesome if we get a built in feature like that!

Really thanks for helping me out.

And so now lets close this issue?

**Closed** 2021-07-12 08:56 UTC
