### ISSUE TITLE
css autocomplete not working without a blank(space)

### ISSUE THREAD

**Issue by flowfire** [Microsoft/vscode#9930] opened 2016-07-29 01:26 UTC
- VSCode Version:1.3.1
- OS Version:Windows10

Steps to Reproduce:

1. open a css file
2. add a selector and add a property (for emample,position)and type “:”,the autocomplete is not working
3.type a blank " " after ":",the autocomplete works.

![notworking](https://cloud.githubusercontent.com/assets/6639067/17235017/6ce0b5ae-5570-11e6-92c1-47a0a9267b07.png)
![works](https://cloud.githubusercontent.com/assets/6639067/17235018/6ce21606-5570-11e6-8d17-cb808ca0b8da.png)

**Comment by flowfire** [comment] 2016-07-29 01:39
![works](https://cloud.githubusercontent.com/assets/6639067/17235006/5de13f06-5570-11e6-940e-8372960d42b8.png)
![notworking](https://cloud.githubusercontent.com/assets/6639067/17235014/63c509de-5570-11e6-94d6-d5df9863233c.png)

**Comment by aeschli** [comment] 2016-08-02 08:33
duplicate of #7004

**Closed by aeschli** 2016-08-02 08:33 UTC
Labels: css-less-sass
