### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Pointotech** [microsoft/vscode#102721] opened 2020-07-16 18:15 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1. Open VS code.
2. Open file containing Mocha test code.
3. Wait for the TS server to crash 5 times.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99915:161)
    at resolveModuleNamesWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100282:19)
    at processImportedModules (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101695:35)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101438:17)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:60
    at Object.forEach (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:16)
    at synchronizeHostData (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138753:26)
    at Object.getProgram (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146608:44)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:97
    at Object.flatMap (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147790:46)
    at c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149544:28)
    at IOSession.Session.executeCommand (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:33)
    at IOSession.Session.onMessage (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149577:35)
    at Interface.<anonymous> (c:\programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-erb-beautify|ali|0.2.0
vscode-intelephense-client|bme|1.5.2
vscode-deno|den|1.25.0
prettier-vscode|esb|5.1.3
language-haskell|jus|3.3.0
Kotlin|mat|1.7.1
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
vetur|oct|0.24.0
tslint-vue|pro|1.5.6
ruby|reb|0.27.0
java|red|0.64.1
slim|sia|0.1.2
sass-indented|syl|1.8.7
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0
vscode-ruby|win|0.27.0

</details>

**Comment by Pointotech** [comment] 2020-07-16 18:16
All I was trying to do was install the types for the NPM package "mocha" and have TypeScript stop showing Mocha's imports as nonexistent.

**Comment by Pointotech** [comment] 2020-07-16 18:23
I enabled `"typescript.tsserver.log": "verbose"` in the VS Code settings, and it stopped telling me to do that, but it's still giving me the same stack trace that it was showing before.

**Comment by mjbvz** [comment] 2020-07-16 20:26
Duplicate of https://github.com/denoland/vscode_deno/issues/89

Cause by the deno extension

**Closed by mjbvz** 2020-07-16 20:27 UTC
Labels: new release
