### ISSUE TITLE
Electron 3.0.x: Pale/desaturated colors

### ISSUE THREAD

**Issue by atomiks** [microsoft/vscode#68001] opened 2019-02-06 19:51 UTC
⚠️  **bpasero:** ⚠️ 

This will be fixed in Electron 4 when via @poiru https://github.com/electron/electron/pull/15898. Please expect Electron 4 to be out in 2-3 months.

If you cannot wait until then, consider to use our exploration builds that already ship with Electron 4:

We are building exploration builds (you might need to update from within once to get latest) that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Original Issue:**

- VSCode Version: 1.31.0
- OS Version: macOS 10.14.2

Same as https://github.com/atom/atom/issues/17356

The new color profile makes the editor appear desaturated compared to the previous version. Is there an option to use the previous sRGB profile again? (Atom's checkbox doesn't actually work)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jhpratt** [comment] 2019-02-06 22:43
Seconding this on Ubuntu 18.04.

**Comment by kika** [comment] 2019-02-07 00:16
Before update (now taken from Android Studio where I have my color scheme and where I copied the colors from):
![image](https://user-images.githubusercontent.com/207889/52382493-56841300-2a2a-11e9-8e93-aa0d20a4a56c.png)

After update:
![image](https://user-images.githubusercontent.com/207889/52382527-7c111c80-2a2a-11e9-961c-9f9fe564f9f9.png)

**Comment by sam3d** [comment] 2019-02-07 00:30
I'm also seeing this on MacOS 10.14.2 on a 2017 Macbook Pro monitor using the [Dark Molokai Theme](https://github.com/nonylene/vscode-dark-molokai-theme):

#### Before update (`v1.30.2`)
<img width="365" alt="screenshot 2019-02-07 at 00 29 13" src="https://user-images.githubusercontent.com/8385528/52383002-738f0500-2a6f-11e9-84d8-72a862cc0934.png">

#### After update (`v1.31.0`)
<img width="364" alt="screenshot 2019-02-07 at 00 27 38" src="https://user-images.githubusercontent.com/8385528/52383030-8c97b600-2a6f-11e9-8e4e-cecc53b09f4e.png">

It's a subtle change but it's definitely there.

**Comment by tannergaucher** [comment] 2019-02-07 03:52
Also getting this after upgrade on MacOS 10.14.2  and my 2017 Macbook Pro with Atom One Dark theme. Colors are considerably less saturated. 

<img width="338" alt="screen shot 2019-02-07 at 11 50 35 am" src="https://user-images.githubusercontent.com/33970851/52389479-a9afa180-2ace-11e9-932c-0fe9315e81e2.png">

**Comment by bpasero** [comment] 2019-02-07 07:25
This will be fixed in Electron 4 when via @poiru https://github.com/electron/electron/pull/15898. Please expect Electron 4 to be out in 2-3 months.

**Comment by atomiks** [comment] 2019-02-07 07:46
The darwin exploration build still has the desaturated colors. I'm also noticing some color artifacts in the editor background on 1.31 on the right side in the form "tiles" around where the line selection is, which appear to be fixed in the darwin build. Does there need to be a checkbox to use the old color profile?

For anyone wanting the vibrant colors back, on macOS, you can set the whole OS to use sRGB in System Prefs > Displays > Colour:

<img src="https://i.redd.it/dkvhsjdpe0f21.png" height="400">

This has the side effect of making everything in the OS appear overly vibrant/saturated, something that I only like in my editor for the bright syntax highlighting...

**Comment by bpasero** [comment] 2019-02-07 07:51
@poiru is there anything else required than:

`app.commandLine.appendSwitch('disable-features', 'ColorCorrectRendering');`

**Comment by poiru** [comment] 2019-02-07 07:52
@bpasero You need to switch to `app.commandLine.appendSwitch('disable-color-correct-rendering')`.

**Comment by bpasero** [comment] 2019-02-07 13:03
I pushed this change to the exploration build.

**Comment by ablakey** [comment] 2019-02-07 14:47
Not 100% sure I'm dealing with the same issue, but it looks unchanged. Downloaded Exploration build 1 minute ago.

Version: 1.31.0-exploration
Commit: 37818ac3597b4afda264b05226b0b77fb8e85f41

(Is the link in the first post still correct for Linux? Where can I find a more generic landing page for Exploration build?)

![image](https://user-images.githubusercontent.com/9021944/52418758-c347ed80-2abc-11e9-81fb-cf917c56061f.png)

Just wanted to share that this is a blocking issue for me. Call me a broken human but this faded colour is more distracting to my job than a fire alarm going off. I eagerly hope we can help get this fixed in any build. Otherwise I'll seek info on how to revert to 1.30 for the next 2-3 months. Thanks for your help!

**Comment by bpasero** [comment] 2019-02-07 15:34
@ablakey should mention, those links are old and you need to update once to get latest!

**Comment by ablakey** [comment] 2019-02-07 15:41
Derp. Of course!

![image](https://user-images.githubusercontent.com/9021944/52422777-be873780-2ac4-11e9-8c49-2355ca901486.png)

You might have to take my word for it. It is noticeably better to my eyes. The background is distinctly darker.

**Comment by ablakey** [comment] 2019-02-08 15:19
So I did something unconscionably awful.

I didn't want to use a different version of code because I didn't want to migrate all of my settings, extensions, etc. over.

In `/usr/share/code/resources/app/main.js` I replaced:

```javascript
app.commandLine.appendSwitch('disable-features', 'ColorCorrectRendering');
```
with:
```javascript
app.commandLine.appendSwitch('force-color-profile', 'srgb');
```

(via `sed` or your favourite editor with sudo privileges)

This modifies built code in `/usr/share/` which is preeeeetty awful. But it works. I expect it will get clobbered when vscode gets updated next.

**Comment by poiru** [comment] 2019-02-08 15:41
Just for the record, `--force-color-profile=srgb` only works on Windows.

**Comment by Zeex** [comment] 2019-02-09 21:14
@ablakey's fix worked for me too on Ubuntu 18.10

**Comment by dhowden** [comment] 2019-02-25 11:31
Just tried the exploration build for macOS and this does not appeared to be fixed there.  Is there a more up-to-date exploration build we should be trying?

I have tried 37818ac3597b4afda264b05226b0b77fb8e85f41.

**Comment by ablakey** [comment] 2019-03-18 13:27
Are my eyes going bad or does this appear to be fixed in the latest release?

**Comment by dhowden** [comment] 2019-03-18 21:58
I've been switching back and forth between the recent versions (back to 1.30.2).  I still see the same issue.

Which version are you trying?

**Comment by atomiks** [comment] 2019-04-02 08:40
I can confirm it's fixed in the macOS download link version (after updating it) and the colors are vibrant again 🌈. When does that version go stable? I've been staying on 1.30.2

**Comment by nchengyeeshen** [comment] 2019-04-09 01:39
I'm on Fedora 29, VSCode 1.33.0 and colours are still weird unless I force the colour profile to become sRGB.

Another temporary fix I've found is to override the _.desktop_ file by copying it to `~/.local/share/applications` and then adding `--force-color-profile=srgb` at the `Exec` line in `code.desktop`, like so
`Exec=/usr/share/code/code --force-color-profile=srgb --unity-launch %F`.

You might have to restart your desktop environment for this to take effect.

**Comment by jhpratt** [comment] 2019-04-11 04:05
> This will be fixed in Electron 4 via [@poiru](https://github.com/poiru) [electron/electron#15898](https://github.com/electron/electron/pull/15898). Please expect Electron 4 to be released in stable in 2-3 months.

@bpasero Any updates, or an ETA on when Electron 4 will ship beneath Code? _Every single update_ forces me to pull this issue back up to find the necessary file and flag I need to switch. At the very least, putting in an option to toggle it would be great.

**Comment by jhpratt** [comment] 2019-04-18 04:50
@bpasero 

I'm interpreting a lack of response (given your activeness on GitHub) as "we have no timeframe", which is a shame, really. Tons of people are affected by this, and there's no effort to change it.

Upgrading to Electron 4 is the suggested solution, but _this has been deferred_ past the April release (due to come out May 6), per #71830. Your estimated timeframe was 2-3 months, and the release on May 6 is the long end of that. I (along with others) would very much appreciate an updated estimate.

At the absolute least, adding a dropdown in the settings to toggle the rendering would solve the issue temporarily.

**Comment by atomiks** [comment] 2019-04-18 05:04
It seems like the only thing blocking the upgrade is #69301. No response since February from Electron team :\

**Comment by bpasero** [comment] 2019-04-18 06:39
@jhpratt I have just triggered a new Exploration build with latest changes. Have you considered staying on that version until we did the move?

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by bpasero** [comment] 2019-04-18 06:41
As for the setting: since this is something that needs to be set very early on on startup, we do not have access to our settings file yet. Since startup performance is critical to us, we (so far) have stayed away from blocking the startup to read the settings file.

**Comment by dhowden** [comment] 2019-05-22 07:54
@bpasero Has the latest exploration build broken this again?  This was working fine, seems to have stopped working for me today.  I updated to macOS 10.14.5 last night, so that might have caused the problem (hope not, less likely to be fixable!).

**Comment by bpasero** [comment] 2019-05-22 11:41
@deepak1556 maybe knows

**Comment by bpasero** [comment] 2019-06-11 16:14
Are people still seeing this with latest VSCode insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Those have been updated to Electron 4. Just curious.

**Comment by atomiks** [comment] 2019-06-12 01:06
Nope, the desaturated colors and artifact problem are both gone in the latest builds with Electron 4

**Comment by ablakey** [comment] 2019-06-12 05:04
I cannot reproduce the issue on latest insiders.

**Comment by bpasero** [comment] 2019-07-01 06:26
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-07-01 06:26 UTC
Labels: electron, electron-3.0.x-update, fixed-in-electron-4.0.x, upstream

**Comment by dhowden** [comment] 2019-07-16 02:49
Running the latest insiders, looks like the color saturation issue has returned...  Reporting here as it is related, apologies if this should be a new issue!

Version: 1.37.0-insider
Commit: 894056d11c7fffb261a0100fd4dcbf8cff84a8c0
Date: 2019-07-15T05:24:02.940Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
