### ISSUE TITLE
Stage with merge conflicts warning still appears after all conflicts resolved

### ISSUE THREAD

**Issue by amueller** [Microsoft/vscode#53346] opened 2018-06-29 16:26 UTC
Similar to #35404 and #33983 which have been closed.

- VSCode Version: Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
- OS Version: DISTRIB_DESCRIPTION="Ubuntu 17.10"

Steps to Reproduce:
create a conflict like so:

1.
```sh
cd /tmp && mkdir tmpdir && cd tmpdir && git init
echo "first line\n================" > file.txt && git add file.txt && git commit -m "first line"
git checkout -b other_branch && echo "branch change" >> file.txt && git commit -am "branch change"
git checkout master && echo "master change" >> file.txt && git commit -am "master change" &&  git merge other_branch
```
2. Launch ``code --disable-extensions /tmp/tmpdir``
3. "Accept Both Changes" and safe file
4. got to git tab, click "+" for staging

Does this issue occur when all extensions are disabled?: Yes/No

yes

**Comment by amueller** [comment] 2018-06-29 16:28
aaand not I can't reproduce any more ?!

**Comment by amueller** [comment] 2018-06-29 16:31
Ok so the issue is that it's an rst file that contains lots of ``===========`` for headers and that's probably throwing off the regexp. Can reproduce with slightly modified example.

**Comment by rowandh** [comment] 2018-07-26 02:35
I've also experienced this with a C# file that uses generics, which use some of the same symbols as merge conflict markers (`<>`). Can't say for certain that was the cause of the issue, but might be worth investigating.

**Comment by joaomoreno** [comment] 2018-09-19 13:55
Closing this, as it shouldn't occur many times and it's better to be safe than sorry.

**Closed by joaomoreno** 2018-09-19 13:55 UTC
Labels: bug, git, good first issue, help wanted

**Comment by amueller** [comment] 2018-09-20 22:05
Sorry but I disagree. This happens all the time and basically means you
can't commit restructured text files with vscode.

**Comment by amueller** [comment] 2018-09-21 16:04
What's the current regexp? Can it be made tighter?

**Comment by joaomoreno** [comment] 2018-09-24 08:30
Here it is: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L147

It looks for 7 consecutive occurrences of either `<`, `>` or `=` at the beginning of a line.

**Comment by amueller** [comment] 2018-09-24 14:35
Shouldn't all three be present for an unresolved conflict?
I guess that function only works on single lines? I would argue you can't detect whether it's a failed merge on single lines.

A simple way to strengthen that would be to require *exactly* 7. That would make it less likely to fire spuriously. Git always uses 7, right?
Also, it might be more robust to only detect the ``<`` and ``>`` because they need to be seven ``<`` or ``>`` followed by a single space followed by a valid branch name followed by a newline.
