### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by pedritin91** [Microsoft/vscode#47611] opened 2018-04-10 19:54 UTC
I'm trying to install the .vsix since the recommended one on vscode extensions panel isn't working either. Neither of the two ways is working for me.

VSCode 1.22.1

**Comment by octref** [comment] 2018-04-10 20:27
Duplicate of #42229.

**Comment by joaomoreno** [comment] 2018-04-11 07:36
@pedritin91 Can you open the .vsix file using a ZIP program? Can you upload the exact .vsix file somewhere and send it to me?

**Comment by octref** [comment] 2018-04-11 15:08
@joaomoreno This one: https://github.com/vuejs/vetur/releases

**Comment by joaomoreno** [comment] 2018-04-12 07:32
I downloaded `vetur-0.11.8.vsix`. It seems like a working ZIP file. I can also install it with the `Install from VSIX...` action.

```
$ shasum vetur-0.11.8.vsix
1d08cf963496cc524f3b19109230d11f63c774e5  vetur-0.11.8.vsix
```

Do you get the same hash?

@octref Can you reproduce the issue?

**Comment by octref** [comment] 2018-04-12 14:15
Same hash and I cannot repro.

**Comment by joaomoreno** [comment] 2018-04-13 07:34
@pedritin91 Can you check the hash of your vsix file?

**Closed** 2018-04-20 07:43 UTC
Labels: extensions, needs more info
