### ISSUE TITLE
Make text copyable in the Extension overview pages?

### ISSUE THREAD

**Issue by rw3iss-hpl** [microsoft/vscode#102300] opened 2020-07-12 15:08 UTC
Extension detail pages and their readme's will not let you copy any text. 
Seems ridiculous for an IDE where most extensions offer code samples to configure, and copying is pretty convenient.
Is there some good reason copy is disabled in these panes?

**Comment by gjsjohnmurray** [comment] 2020-07-12 15:17
/duplicate of #86658 and fixed in PR #102029, so should arrive next month (sooner if you use Insiders).

**Closed** 2020-07-12 15:18 UTC
Labels: *duplicate
