### ISSUE TITLE
Ask again: Extension authoring: expose TypeScript AST?

### ISSUE THREAD

**Issue by panlina** [microsoft/vscode#92580] opened 2020-03-12 14:16 UTC
Sorry for opening another issue to continue a question, but the old question (#92195) is closed and ignored.

I'm asking if there's plan to expose TypeScript AST to extension authors. It's still a question when TS language service plugin is taken into account, because I'm interested in making an extension use TypeScript AST, not creating another TS language service plugin.

**Comment by mjbvz** [comment] 2020-03-12 18:18
Duplicate of #92195. I already explained that VS Code does not have an AST and linked to the documentation on TS plugins. That is the only way to access the AST and there are no plans to change that

**Closed by mjbvz** 2020-03-12 18:18 UTC
