### ISSUE TITLE
"Go to definition" incorrectly includes type definition

### ISSUE THREAD

**Issue by jonrimmer** [microsoft/vscode#95762] opened 2020-04-21 11:31 UTC
Issue Type: <b>Bug</b>

1) Create a new React app using `npx create-react-app cra-playground --template typescript`
2) In the app, create a React component called `Button` of type `FC`

```tsx
const Button: FC = ({children}) => {
  return <button>{children}</button>
}
```

3) Use the new `Button` component in the `App` component.

```tsx
function App() {
  return (
    <div className="App">
      <Button>Hello</Button>
    </div>
  );
}
```

4) Try to navigate to the `Button` component's definition, either by cmd-clicking it, or by use the context menu's "Go to definition" option.

Instead of navigating to the component's definition, VSCode will instead open up an inline panel with both the `Button` component definition and the definition of `FunctionComponent` in `node_modules/@types/react/index.d.ts`.

![image](https://user-images.githubusercontent.com/183786/79861030-9cc55800-83cb-11ea-8a15-edb35f424e52.png)

This behaviour is nonsensical. `FunctionComponent` is not the definition of `Button`, it an interface that `Button` implements. These are not the same thing. This bug makes it incredibly painful to navigate React apps. Instead being able to quickly navigate between component definitions, VSCode is constantly blocking you.

It is especially pointless when there is already a separate "Go to type definition" option that *does* take you directly to the definition of `FunctionComponent`.

VS Code version: Code - Insiders 1.45.0-insider (b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094, 2020-04-21T05:38:43.781Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|-psn_0_14925371|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment] 2020-04-22 17:40
Duplicate of https://github.com/microsoft/TypeScript/issues/37816

**Closed by mjbvz** 2020-04-22 17:40 UTC
