### ISSUE TITLE
Too many selections with intellisense lead to crash

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#11869] opened 2016-09-12 09:41 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Have 188 selections with intellisense selected
2. Try to type while vscode tries to suggest autocomplete

This scenario leads to a freeze and to a crash

**Comment by alexandrudima** [comment] 2016-09-13 13:39
@con-ssc I cannot reproduce when trying 110 selections for example and doing ctrl-space and accepting a suggestion.

What language are you trying in and perhaps it has something to do with the actual completions? i.e. Can you help me out with a reproducible example.

![selections](https://cloud.githubusercontent.com/assets/5047891/18475813/2bf09182-79c8-11e6-9532-ec895c095b19.gif)

**Comment by alexandrudima** [comment] 2016-10-27 20:41
Closing after a number of days without a reply.

**Closed by alexandrudima** 2016-10-27 20:41 UTC
Labels: needs more info

**Comment by con-ssc** [comment] 2016-10-28 06:40
Plain JavaScript. Since it is a script from a customer and I don't know what causes the freeze I am unable to provide an example.
