### ISSUE TITLE
Touch board double finger rolling sometimes has delay, not smooth. In win10

### ISSUE THREAD

**Issue by GitHublilei** [Microsoft/vscode#36404] opened 2017-10-17 09:54 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|0.1.3
html-snippets|abu|0.1.0
vscode-database|baj|1.2.0
githistory|don|0.2.3
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-npm-script|eg2|0.2.1
react-native-react-redux|EQu|1.4.1
php-debug|fel|1.11.1
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
phpcs|ika|0.7.0
vue|jcb|0.1.5
php-cs-fixer|jun|0.1.45
code-beautifier|mic|1.7.2
mssql|ms-|1.2.0
node-debug2|ms-|1.18.3
debugger-for-chrome|msj|3.3.1
vetur|oct|0.9.11
vuehelper|oys|0.1.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.4
php-formatter|Sop|0.2.4
autoimport|ste|1.2.2
code-spell-checker|str|1.4.10
react-beautify|tai|0.3.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.2
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.Touch board double finger rolling sometimes has delay, not smooth
2.Sometimes there's no problem
3.Double finger scrolling has no problem with other programs

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-17 10:12
Duplicate of https://github.com/Microsoft/vscode/issues/13612

**Closed by egamma** 2017-10-17 10:12 UTC
Labels: duplicate, new release
