### ISSUE TITLE
Suggestion: Add support to hex, byte editor, binary 

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#28233] opened 2017-06-08 13:14 UTC
Hi,

please add support to edit hex, binary files.

- VSCode Version:
```
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

- OS Version:
Kernel: 

> Linux wellington-Inspiron-3647 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```
Steps to Reproduce:

1. Try to open or edit binary file.
2.  Problem to open.

**Comment by michelkaporin** [comment] 2017-06-09 07:39
Duplicate of #2582.

**Closed by michelkaporin** 2017-06-09 07:39 UTC
