### ISSUE TITLE
Debugging a node program causes full CPU load of the renderer process

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67222] opened 2019-01-28 10:52 UTC
While debugging a node process locally I noticed that the renderer process causes full CPU load and no interaction with the renderer is possible. 

I do have edited a break point in case that makes a difference.

**Comment by dbaeumer** [comment] 2019-01-28 10:55
Seems to be tree related
<img width="411" alt="capture" src="https://user-images.githubusercontent.com/1931590/51831922-a14baf80-22f3-11e9-826d-9db0bcb8749c.png">

**Comment by isidorn** [comment] 2019-01-28 12:56
@dbaeumer great find, thanks a lot!
Might be related to https://github.com/Microsoft/vscode/issues/65213

**Comment by joaomoreno** [comment] 2019-01-28 14:10
Yeah definitely a dupe of #65213

**Closed by joaomoreno** 2019-01-28 14:10 UTC
Labels: bug, debug, important, tree
