### ISSUE TITLE
Bug related to the default terminal setting

### ISSUE THREAD

**Issue by psh5496** [microsoft/vscode#132621] opened 2021-09-08 07:23 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. this is my _setting.json_ I set the default terminal to cmd.
![image](https://user-images.githubusercontent.com/67415543/132462960-e932aba5-1d41-4a8f-96ca-c12de8ea8092.png)

2. If I press the new terminal, it operates in cmd. But, If I restart VS Code while the cmd terminal is open, it operates as powersell.
![image](https://user-images.githubusercontent.com/67415543/132463571-2864a5f5-1813-44e9-8785-5f8b03d1a644.png)

3. I wonder if this is my error and want to receive an answer.

**Comment by albertosantini** [comment] 2021-09-08 07:29
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Closed** 2021-09-08 08:55 UTC
Labels: *duplicate
