### ISSUE TITLE
Multiple text cursors after dropping from file explorer

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8521] opened 2016-06-29 16:35 UTC
Test item #7852 
- VSCode Version: Code - Insiders 1.3.0-insider (798b41ab1cf3636a27042020a54ddfb4cfb8d23c, 2016-06-29T05:14:50.570Z)
- OS Version: Linux x64 3.13.0-34-generic

Steps to Reproduce:
1. Open two files side-by-side.
2. Focus left editor -> shows cursor
3. Drag&drop from Ubuntu's file explorer on to the right editor area
4. -> Right editor gets focus and shows cursor, yet the cursor in the left editor is not removed. There are now two blinking cursors which is unexpected.

**Comment by bpasero** [comment] 2016-06-30 06:17
I can reproduce but only on Linux. Since I am calling focus on the second editor (this is clearly visible since the focus in the active editor moves to the side) I am not sure why the editor would still decide to show the blinking cursor.

@alexandrudima moving to you.

**Comment by alexandrudima** [comment] 2017-05-22 21:50
I think this was fixed in the meantime, I can no longer reproduce.

**Closed by alexandrudima** 2017-05-22 21:50 UTC
Labels: bug
