### ISSUE TITLE
version 1.92 can't select configure checkout box for new or editing existing profile  but 1.91 can in Macbook M1 pro with Mac 15.1.

### ISSUE THREAD

**Issue by qi-xmu** [microsoft/vscode#225503] opened 2024-08-13 14:58 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.1
- OS Version: Mac 15.1 Beta版(24B5024e)

Steps to Reproduce:
1. Create a new profile not edit a existing profile, when you click the checkout-box, all of them will be disable, and can't enable any more. Just like this.
<img width="618" alt="image" src="https://github.com/user-attachments/assets/87139e97-b10b-4f20-b22a-81205202a905">

**Comment by gjsjohnmurray** [comment] 2024-08-13 15:26
/duplicate of #224788 which offers a workaround.

**Closed** 2024-08-13 15:26 UTC
Labels: *duplicate
