### ISSUE TITLE
Issue in update

### ISSUE THREAD

**Issue by amitesh-gaurav** [Microsoft/vscode#49963] opened 2018-05-16 09:35 UTC
- VSCode Version: -1.23.0
- OS Version:Windows 7 SP1

Steps to Reproduce:

1. Update the VS Code

Does this issue occur when all extensions are disabled?: No

May 16 14:58:21.161 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
May 16 14:58:21.161 INFO Checking for running Code.exe processes... (attempt 1)
May 16 14:58:21.165 INFO Code.exe is running, wait a bit
May 16 14:58:21.665 INFO Checking for running Code.exe processes... (attempt 2)
May 16 14:58:21.669 INFO Code.exe is running, wait a bit
May 16 14:58:22.169 INFO Checking for running Code.exe processes... (attempt 3)
May 16 14:58:22.171 INFO Code.exe is not running
May 16 14:58:22.172 INFO Checking for possible conflicting running processes... (attempt 1)
May 16 14:58:22.175 INFO Inno Updater v0.4.3
May 16 14:58:22.175 INFO Starting update, silent = false
May 16 14:58:22.196 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
May 16 14:58:22.196 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
May 16 14:58:22.197 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
May 16 14:58:22.209 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
May 16 14:58:22.214 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
May 16 14:58:22.221 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
May 16 14:58:22.227 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
May 16 14:58:22.235 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
May 16 14:58:22.236 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
May 16 14:58:22.236 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
May 16 14:58:22.242 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
May 16 14:58:22.249 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
May 16 14:58:22.254 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
May 16 14:58:22.260 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
May 16 14:58:22.261 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
May 16 14:58:22.267 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
May 16 14:58:22.273 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
May 16 14:58:22.280 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
May 16 14:58:22.285 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
May 16 14:58:22.287 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
May 16 14:58:22.292 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
May 16 14:58:22.297 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
May 16 14:58:22.303 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
May 16 14:58:22.311 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
May 16 14:58:22.311 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
May 16 14:58:22.317 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
May 16 14:58:22.318 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
May 16 14:58:22.324 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
May 16 14:58:22.324 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
May 16 14:58:22.325 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
May 16 14:58:22.325 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
May 16 14:58:22.325 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
May 16 14:58:22.326 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
May 16 14:58:22.326 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
May 16 14:58:22.327 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
May 16 14:58:22.327 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
May 16 14:58:22.335 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
May 16 14:58:22.340 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
May 16 14:58:22.341 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
May 16 14:58:22.341 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
May 16 14:58:22.342 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
May 16 14:58:22.342 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
May 16 14:58:22.343 INFO Delete: "bin" (attempt 1)
May 16 14:58:22.349 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
May 16 14:58:22.350 INFO Delete: "Code.exe" (attempt 1)
May 16 14:58:22.354 INFO Delete: "Code.VisualElementsManifest.xml" (attempt 1)
May 16 14:58:22.356 INFO Delete: "CodeSignSummary.md" (attempt 1)
May 16 14:58:22.361 INFO Delete: "content_resources_200_percent.pak" (attempt 1)
May 16 14:58:22.361 INFO Delete: "content_shell.pak" (attempt 1)
May 16 14:58:22.362 INFO Delete: "d3dcompiler_47.dll" (attempt 1)
May 16 14:58:22.363 INFO Delete: "ffmpeg.dll" (attempt 1)
May 16 14:58:22.364 INFO Delete: "icudtl.dat" (attempt 1)
May 16 14:58:22.364 INFO Delete: "libEGL.dll" (attempt 1)
May 16 14:58:22.365 INFO Delete: "libGLESv2.dll" (attempt 1)
May 16 14:58:22.366 INFO Delete: "locales" (attempt 1)
May 16 14:58:22.557 INFO Delete: "msvcp140.dll" (attempt 1)
May 16 14:58:22.557 INFO Delete: "natives_blob.bin" (attempt 1)
May 16 14:58:22.558 INFO Delete: "node.dll" (attempt 1)
May 16 14:58:22.560 INFO Delete: "pdf_viewer_resources.pak" (attempt 1)
May 16 14:58:22.560 INFO Delete: "resources" (attempt 1)
May 16 14:58:40.802 INFO Delete: "snapshot_blob.bin" (attempt 1)
May 16 14:58:40.803 INFO Delete: "ucrtbase.dll" (attempt 1)
May 16 14:58:40.804 INFO Delete: "ui_resources_200_percent.pak" (attempt 1)
May 16 14:58:40.804 INFO Delete: "vcruntime140.dll" (attempt 1)
May 16 14:58:40.805 INFO Delete: "views_resources_200_percent.pak" (attempt 1)
May 16 14:58:40.806 INFO Rename: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
May 16 14:58:40.820 INFO Rename: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
May 16 14:58:40.829 INFO Rename: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
May 16 14:58:40.839 INFO Rename: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
May 16 14:58:40.849 INFO Rename: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
May 16 14:58:40.861 INFO Rename: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
May 16 14:58:40.870 INFO Rename: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
May 16 14:58:40.880 INFO Rename: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
May 16 14:58:40.891 INFO Rename: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
May 16 14:58:40.901 INFO Rename: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
May 16 14:58:40.911 INFO Rename: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
May 16 14:58:40.921 INFO Rename: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
May 16 14:58:40.933 INFO Rename: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
May 16 14:58:40.943 INFO Rename: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
May 16 14:58:40.953 INFO Rename: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
May 16 14:58:40.964 INFO Rename: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
May 16 14:58:40.975 INFO Rename: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
May 16 14:58:40.985 INFO Rename: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
May 16 14:58:40.994 INFO Rename: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
May 16 14:58:41.005 INFO Rename: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
May 16 14:58:41.015 INFO Rename: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
May 16 14:58:41.026 INFO Rename: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
May 16 14:58:41.035 INFO Rename: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
May 16 14:58:41.046 INFO Rename: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
May 16 14:58:41.056 INFO Rename: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
May 16 14:58:41.067 INFO Rename: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
May 16 14:58:41.077 INFO Rename: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
May 16 14:58:41.088 INFO Rename: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
May 16 14:58:41.099 INFO Rename: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
May 16 14:58:41.113 INFO Rename: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
May 16 14:58:41.123 INFO Rename: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
May 16 14:58:41.134 INFO Rename: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
May 16 14:58:41.146 INFO Rename: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
May 16 14:58:41.159 INFO Rename: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
May 16 14:58:41.171 INFO Rename: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
May 16 14:58:41.182 INFO Rename: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
May 16 14:58:41.194 INFO Rename: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
May 16 14:58:41.207 INFO Rename: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
May 16 14:58:41.219 INFO Rename: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
May 16 14:58:41.230 INFO Rename: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
May 16 14:58:41.240 INFO Rename: "bin" (attempt 1)
May 16 14:58:41.276 INFO Rename: "blink_image_resources_200_percent.pak" (attempt 1)
May 16 14:58:41.282 INFO Rename: "Code.exe" (attempt 1)
May 16 14:58:41.415 INFO Rename: "Code.exe" (attempt 2)
May 16 14:58:41.657 INFO Rename: "Code.exe" (attempt 3)
May 16 14:58:42.151 INFO Rename: "Code.exe" (attempt 4)
May 16 14:58:42.996 INFO Rename: "Code.exe" (attempt 5)
May 16 14:58:44.288 INFO Rename: "Code.exe" (attempt 6)
May 16 14:58:46.131 INFO Rename: "Code.exe" (attempt 7)
May 16 14:58:48.625 INFO Rename: "Code.exe" (attempt 8)
May 16 14:58:51.874 INFO Rename: "Code.exe" (attempt 9)
May 16 14:58:55.968 INFO Rename: "Code.exe" (attempt 10)
May 16 14:59:01.014 INFO Rename: "Code.exe" (attempt 11)
May 16 14:59:01.059 ERRO Access is denied. (os error 5)

**Comment by mjbvz** [comment] 2018-05-16 17:39
Duplicate of #47841

**Closed by mjbvz** 2018-05-16 17:39 UTC
