### ISSUE TITLE
Main window behaves strangely when viewing PROBLEMS pane

### ISSUE THREAD

**Issue by guy-hindle-ibm** [Microsoft/vscode#69770] opened 2019-03-04 09:40 UTC
Issue Type: <b>Bug</b>

For reasons I don't understand, recently I see odd behaviour when selecting the PROBLEMS pane:
- the "bottom" status bar appears about 1/3 the way up the window, with "black" below it
- the titles of the files being edited disappears

**Normal appearance using TERMINAL pane**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48133267/53724099-0d748280-3e61-11e9-85bd-399164a65638.png">

**Broken appearance using PROBLEMS pane**
<img width="607" alt="image" src="https://user-images.githubusercontent.com/48133267/53723918-aa82eb80-3e60-11e9-8a6c-532162a06b41.png">

**Even worse when the side-bar is collapsed**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48133267/53724160-3268f580-3e61-11e9-99bc-be90ad93f9ef.png">

**After clicking on the STATUS bar**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/48133267/53724281-73f9a080-3e61-11e9-90e5-31d92da01623.png">

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
go-test-outline|Rom|0.2.0
better-comments|aar|2.0.3
ng-template|Ang|0.1.11
vscode-django|bat|0.19.0
vscode-icontheme-nomo-dark|be5|1.3.6
language-prometheus|caa|0.1.2
dep|car|0.1.0
path-intellisense|chr|1.4.2
systemd-unit-file|coo|1.0.3
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.25.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
jupyter|don|1.1.5
python-extension-pack|don|1.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
vscode-essentials|god|0.0.1
apiconnecttools|IBM|0.0.5
ibm-developer|IBM|0.0.14
golang-tdd|joa|0.0.9
Angular2|joh|7.0.1
MagicPython|mag|1.1.0
vscode-elixir|mjm|1.1.0
python|ms-|2019.2.5433
Go|ms-|0.9.2
makefiles-support-for-vscode|nae|0.0.3
angular2-inline|nat|0.0.17
vscode-code-outline|pat|0.2.1
vscode-icons|rob|8.2.0
iferrblocks|rst|1.1.1
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.3.11
nativescript|Tel|0.8.4
vscodeintellicode|Vis|1.1.3
jinja|who|0.0.8
vscode-postfix-go|yok|0.0.12

(3 theme extensions excluded)

</details>

**Comment by sandy081** [comment] 2019-03-05 15:39
Duplicate of #67371

**Closed** 2019-03-05 15:40 UTC
Labels: *duplicate, error-list
