### ISSUE TITLE
No apparent way to know whether an output channel is shown

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/vscode#6503] opened 2016-05-18 22:10 UTC
- VSCode Version: 1.1.0
- OS Version: Windows

For some reason (https://github.com/bbenoist/vscode-shell/issues/2), I need to know whether an output channel instance is shown or not.

However, I see no way to get the information with current vscode API.

How can I obtain it from my extension?

**Comment by jrieken** [comment] 2016-05-19 08:58
dupe of #6192

**Closed by jrieken** 2016-05-19 08:58 UTC
Labels: api
