### ISSUE TITLE
Extension host not working fine

### ISSUE THREAD

**Issue by anbcartlow** [microsoft/vscode#177053] opened 2023-03-14 07:54 UTC
Type: <b>Bug</b>

no idea why but it keeps on crashing.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:31:31.010Z)
OS version: Linux x64 5.19.0-35-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 3980)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|15.27GB (6.95GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 737f75a7-d8ef-447a-9994-796c9d502b5a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (110)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-laravel-goto|abs|4.7.0
laravel-model-snippets|ahi|2.0.0
project-manager|ale|12.7.0
laravel-extra-intellisense|ami|0.6.2
beautify-blade|api|1.0.1
gitstash|art|5.1.0
laravel-blade-spacer|aus|2.1.3
bootstrap-snippets-vscode|bha|2.4.0
vscode-intelephense-client|bme|1.9.5
vscode-better-align|cho|1.4.1
regex|chr|0.4.0
gitignore|cod|0.9.0
laravel-goto-view|cod|1.3.8
doxdocgen|csc|1.4.0
env-symbol-provider|ctf|0.0.4
laravel-goto-config|ctf|0.4.1
laravel-goto-controller|ctf|0.4.8
laravel-goto-env|ctf|0.4.3
laravel-goto-lang|ctf|0.4.6
laravel-goto-view|ctf|0.5.7
php-array-symbols|ctf|0.0.3
vscode-mysql-client2|cwe|6.2.4
laravel-easy-blade-snippets|dac|1.2.1
vscode-jq|dan|1.2.0
c-cpp-compile-run|dan|1.0.43
dart-code|Dar|3.60.1
flutter|Dar|3.60.0
vscode-jq-playground|dav|4.3.5
git-extension-pack|don|0.1.3
githistory|don|0.6.20
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
git-project-manager|fel|1.8.2
vscode-pull-request-github|Git|0.60.0
laravel-create-view|gli|0.0.6
CppSnippets|har|0.0.15
vscode-es6-string-html|hjb|1.1.1
jquery-snippets|Hri|1.0.0
laravel-blade-wrapper|IHu|1.0.1
mysql-syntax|jak|1.3.1
vscode-cdnjs|Jak|0.19.0
vscode-picture|Jak|1.0.0
better-cpp-syntax|jef|1.17.2
JavaScriptSnippetsStandard|jms|1.8.0
cmake-language-support-vscode|jos|0.0.9
jq-syntax-highlighting|jq-|0.0.2
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
vscode-js-console-utils-msd|may|0.0.2
auto-save|mcr|1.0.3
php-namespace-resolver|Meh|1.1.9
vscode-language-babel|mgm|0.0.37
laravel-goto-config|MrC|1.0.3
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.3.817
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5834
vsliveshare-audio|ms-|0.1.93
laravel-goto-components|nao|1.2.0
php-docblocker|nei|2.7.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
vscode-html-scss|P-d|0.0.42
jq-vscode|pet|0.1.3
material-icon-theme|PKi|4.24.0
vscode-thunder-client|ran|2.5.1
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.28
vue-vscode-snippets|sdr|3.1.1
vscode-blade-formatter|shu|0.20.12
html5-boilerplate|sid|1.1.1
autoimport|ste|1.5.4
vscode-babel-repl|t-s|0.1.2
tabnine-vscode|Tab|3.6.41
ejs-snippets|Tao|0.1.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
apexsql-power-tools|vs-|2021.1.81
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-maven|vsc|0.40.4
volar|Vue|1.2.0
vscode-typescript-vue-plugin|Vue|1.2.0
gitblame|wad|10.1.0
HTML5-extension-pack|wal|1.0.0
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|3.3.0
php-debug|xde|1.32.0
php-pack|xde|1.0.3
bootstrap-v4-snippets|Zac|1.1.3
vscode-open-in-github|ziy|1.3.6
php-intellisense|zob|1.1.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
funwalk2:30682974
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:12
Not related to Copilot

@anbcartlow can you please use Extension: Bisect to find out what extension is causing this?

**Comment by anbcartlow** [comment] 2023-03-16 04:52
need a little more help please @isidorn .
just installed extension
this is the only extension I could find so far. it says Extension Bisect Demo and not what you said
![image](https://user-images.githubusercontent.com/119594438/225517532-60fd2789-13ee-428e-8c24-dbe3a6aeb15f.png)

**Comment by anbcartlow** [comment] 2023-03-16 04:59
I just did. and ultimately I had an issue created at
https://github.com/MehediDracula/PHP-Namespace-Resolver/issues/110

let me check if I get another issues by some other extension as well

**Comment by isidorn** [comment] 2023-03-16 09:14
Thanks for opening that issue. I suggest to disable that extension until the issue is fixed.
Closing this as there is nothing we can do on the VS Code side

**Closed by isidorn** 2023-03-16 09:14 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host, sandbox
