### ISSUE TITLE
R icon gets too large

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#58274] opened 2018-09-09 01:07 UTC
- VSCode Version: 1.27.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Create an R script and save
2. The icons on the tab and in the file explorer are too large

The icons are normal on VSCode Version 1.26 and prior releases.

Does this issue occur when all extensions are disabled?: Yes

<img width="665" alt="image" src="https://user-images.githubusercontent.com/4662568/45260078-a759f600-b40f-11e8-9cca-97ef8f9ff0e1.png">

**Comment by dsifford** [comment] 2018-09-09 16:30
Dupe of upstream issue jesseweed/seti-ui#507

**Closed** 2018-09-10 06:37 UTC
Labels: *duplicate, new release
