### ISSUE TITLE
TM_FILENAME can't be use with regex in snippets

### ISSUE THREAD

**Issue by LeoIannacone** [Microsoft/vscode#33162] opened 2017-08-25 16:25 UTC
- VSCode Version: 1.15.1
- OS Version: Ubuntu 17.04

Can't use this regex in my snippet:
```
export default class ${TM_FILENAME/(\w+)\.js/\1/g}
```

It actually prints `${TM_FILENAME/(\w+)\.js/\1/g}`

**Comment by jrieken** [comment] 2017-08-28 07:19
dupe of #6920

**Closed by jrieken** 2017-08-28 07:19 UTC
Labels: new release, snippets

**Comment by jrieken** [comment] 2017-09-01 13:02
@LeoIannacone This is in the works and I do have a unit for your scenario however, the TextMate format string doesn't use `\1` (as JS does) but `$1`. I wonder if/where you are using the above snippet?

**Comment by LeoIannacone** [comment] 2017-09-01 13:30
I just tried to implement a snippet based on the doc I found on the website, which redirected me to the TextMate doc. I tried many formats, but all of them failed so I figure out it might have been a bug in VSCode. And here we are.

**Comment by jrieken** [comment] 2017-09-01 13:41
Thanks - we will go with a subset of the Textmate format string, http://manual.textmate.org/references.html#format-string. That makes your snippet be like this: `export default class ${TM_FILENAME/(\w+)\.js/$1/g}`
