### ISSUE TITLE
Code - Insiders Helper stealing 100% CPU (and doesn't go away when closing Code)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#20893] opened 2017-02-19 18:40 UTC
- VSCode Version: `1.10.0-insider` 50f8848e44029ffabf0727de49cd18ae4069b4fe
- OS Version: macOS Sierra `10.12.3 (16D32)`

I don't really have any steps to reproduce, but this has been happening more and more frequently.

Here is some output from the hung process
```
> ps aux | grep 4088
eric              4088  99.5  0.2  3323384  37980   ??  R     3:46AM  55:12.95 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=extensionHost
```

I should also note that when I closed Code, many `Code - Insiders Helper` process were left behind but they all were cleaned up as soon as I killed the one above.

**Comment by chmllr** [comment] 2017-02-20 09:53
Same for me on 1.9.1. I consider to switch to vim temporarily, as VSC gets unusable on my project. The side effects of this is that VSC gets extremely slow, even just the typing is getting slow.

**Comment by johnpapa** [comment] 2017-02-20 13:28
I am seeing this too ... when I close VS Code, the process is still running for the helper. When I quit the helper via activity monitor, the CPU settles ... also, the fan has been going nuts.

![image](https://cloud.githubusercontent.com/assets/1202528/23126782/6153fa2a-f746-11e6-8f0d-54f0d8e0cb6b.png)

![image](https://cloud.githubusercontent.com/assets/1202528/23126785/63acc40a-f746-11e6-8b27-e3c97e1c975a.png)


cc @chrisdias as per our previous chat

**Comment by bpasero** [comment] 2017-02-21 06:02
@eamodio @johnpapa any idea if this reproduces in stable for you? we need to find out if this is a regression in 1.10 or actually caused by an extension in stable (as outlined by @chmllr).

I assume this issue goes away when you try to run with extensions disabled (execute: `code --disable-extensions`)?

**Comment by chmllr** [comment] 2017-02-21 09:05
@bpasero Thanks for the hint. Indeed the problem disappears if I disable extensions on 1.9.1 and I can confirm, that the problem is introduced by the Go extension alone. Disabling the Go extension makes VSC very fast again, but the Go features are obviously not available anymore. Now I'm not sure if this  should be rather reported in https://github.com/Microsoft/vscode-go?

**Comment by bpasero** [comment] 2017-02-21 10:32
@chmllr yes I think it makes sense to report this to them. In fact we have @ramya-rao-a as contributor on that extension which maybe should be involved too.

**Comment by bpasero** [comment] 2017-02-21 10:33
Would be interesting to learn from others on this thread if they also use the Go extension.

**Comment by johnpapa** [comment] 2017-02-21 13:45
I do not use the Go extension. Interestingly, I killed the processes for `code insiders helper` in the activity monitor and I havent seen the CPU spike in the past 24 hours, despite that I am still using VS Code. So I am not sure what did it (on both of my MBPs).

I'll keep trying to narrow it down.

Here are my extensions:

![image](https://cloud.githubusercontent.com/assets/1202528/23167314/ee1c7434-f811-11e6-84af-6d9c6e5f01fd.png)

**Comment by eamodio** [comment] 2017-02-21 15:40
I also don't use the Go extension. Typescript is what I am normally editing. But I also haven't seen the problem happen for the last day either. I will keep an eye on it for sure.

**Comment by rupamroy** [comment] 2017-02-21 19:26
Sorry to chime in with a slightly different variation of this , but in Ubuntu I face a related issue where the performane drops down i get a blank screen which blocks everything else. However i get rid of that by 
```
code --disable-gpu
```

may be it can help with this issue.

**Comment by pocesar** [comment] 2017-02-22 23:46
when editing a TSX, whenever the editor finds an unclosed <View>, the process goes mental, using all CPU, and all Typescript typings stop working. Caught those in the developer logs (using insiders 256d)

![image](https://cloud.githubusercontent.com/assets/461084/23238196/95f74c82-f93f-11e6-83d2-f5cd0759ae41.png)

**Comment by chmllr** [comment] 2017-02-23 10:36
Ok in my case I could definitely narrow down the issue to `geocode` tool working on a project with 700+ bagel build files. So, completely irrelevant to VSC itself. Sorry for noise, guys.

**Comment by bpasero** [comment] 2017-02-23 14:37
@pocesar does this reproduce in our insider build too?  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by pocesar** [comment] 2017-02-23 14:57
I'm using insiders @bpasero

**Comment by bpasero** [comment] 2017-02-23 15:01
@mjbvz @waderyan for the TS issue reported from @pocesar

**Comment by pocesar** [comment] 2017-02-23 15:13
so far, this was the most reproduceable scenario:

```tsx
  render() {
    return (
      <KeyboardAwareScrollView style={styles.form} keyboardShouldPersistTaps="always">
        <Form
          ref="form"
          type={Model}
          value={this.state.form}
          options={options}
          onChange={(o,f) => this.updateForm(o, f)}
        />

        <View style={{marginVertical: 30}}>
          <Button title="Cadastrar logradouro" disabled={this.state.disabled} onPress={() => {
            this.props.dispatch(
              RActions.addStreet({
                cep: this.state.form.cep,
                name: this.state.form.name,
                neighborhood: this.state.form.neighborhood,
                type: this.state.form.type,
                latlng: {
                  lat: this.props.currentLatLng.lat,
                  lng: this.props.currentLatLng.lng
                }
              })
            )

            Alert.alert('Sucesso', 'Rua cadastrada')

            this.setState(this.initialState())
          }} />
        </View>
      </KeyboardAwareScrollView>
   )
```

after a couple of edits inside `KeyboardAwareScrollView` children, the errors appear, and the file is marked as having errors for the remaining of the session, until I forcefully close `insiders` all processes. 
changing the first `<KeyboardAwareScrollView` to  `<View` and leaving it unclosed will certainly trigger the problem

**Comment by bpasero** [comment] 2017-02-23 15:17
@pocesar maybe best we move this particular issue into a separate one given you have steps to reproduce?

**Comment by pocesar** [comment] 2017-02-23 15:19
the issue is the same I guess, whatever makes insiders go using all CPU and closing it won't kill the offending `--type=extensionHost` process, although TS isn't an extension

**Comment by jrieken** [comment] 2017-02-23 15:23
> although TS isn't an extension

Technically they are all extensions. They are bundled with the product but have the same runtime restrictions as any other extension. @pocesar As mentioned above, can you file an issue and most importantly include the list of extensions that you use. Thanks and Happy Coding

**Comment by pocesar** [comment] 2017-02-23 15:40
done, created #21292

**Comment by eamodio** [comment] 2017-02-23 15:44
I've gotten this to happen a few times over the last couple hours again. This time it was related to the new SCM code. I was working on a few git rebases and resolving the conflicts via code. And a few times in a row, the SCM viewlet would stop responding (once with a infinite progress bar, the other times with nothing). Ultimately I went back to use the stable version of code and it had no issues. All the 3-4 times this happened, code left behind a bunch of helper processes with 1-2 of them taking 100% cpu.

**Comment by bpasero** [comment] 2017-02-23 18:36
@eamodio can you check what the arguments of these helper processes are that go frenzy?

**Comment by eamodio** [comment] 2017-02-27 04:10
@bpasero Just got it to happen again:

```
ps aux | grep 58329
eric             58329  99.3  0.3  3352404  49892   ??  R     2:26PM 386:46.67 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Users/eric/Code/vscode-find-related/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry
eric             76539   0.0  0.0  2452260    852 s000  S+   11:09PM   0:00.00 grep 58329
```

**Comment by bpasero** [comment] 2017-02-27 06:08
@eamodio that looks like the TS extension consuming CPU cycles then.

**Comment by eamodio** [comment] 2017-02-27 07:35
@bpasero yeah, and somehow it going nuts interferes with the SCM extension

**Comment by johnpapa** [comment] 2017-03-13 15:42
Still happening for me. I sent a activity monitor dump to Chris Dias.

**Comment by bpasero** [comment] 2017-03-13 15:46
@johnpapa which process is running under high CPU load?

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by johnpapa** [comment] 2017-03-13 16:06
I sent it to Chris Dias. 

John Papa




On Mon, Mar 13, 2017 at 8:46 AM -0700, "Benjamin Pasero" <notifications@github.com> wrote:












@johnpapa which process is running under high CPU load?


To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the Activity Monitor allows to find the PID of the process and from a terminal ps aux | grep <pid> reveals its arguments.





On Windows a tool like Process Explorer helps:





Once you have the information please update this issue with it. Thanks!

**Comment by bpasero** [comment] 2017-03-13 16:34
@johnpapa I appreciate that but in the sake of efficient bug triage I would appreciate if you could check which process is the one that runs with 100%.

**Comment by johnpapa** [comment] 2017-03-13 16:41
It is listed above in my first comment. Code insiders helper process.

**Comment by bpasero** [comment] 2017-03-13 16:57
@johnpapa the problem is that many of the processes we spawn are just called that way. With the steps I posted you can find meta data around the process (= the command line arguments) that helps us understand if for example the extension host process is running with high CPU, or the file watcher, or a search process, or the renderer, or the main side, or the shared process, etc.

**Comment by eamodio** [comment] 2017-03-16 14:25
@bpasero I just ran into this again, here is the grep:

```
> ps aux | grep 49080
eric             49080 100.0  0.6  3409724 108352   ??  R     9:23AM  60:03.27 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=extensionHost
```

**Comment by jrieken** [comment] 2017-03-16 14:33
@eamodio Still remember what extension were active/in-use before that happened? The process that goes crazy is the extension host and for exactly that reason (extensions running amok) we isolate them in a separate process such that not the whole editor is dead. However, once that has happened is hard to know what extension is doing it...

**Comment by eamodio** [comment] 2017-03-16 16:05
@jrieken I have quite a few extensions loaded -- but I think TypeScript may be the culprit here, because right before this happened, I had the vscode codebase open and I was trying to navigation around (ctrl+click, find all references) and nothing was working for me -- the find all references just stuck at "Loading...". I had then quit vscode and noticed my fan running and found the stuck process.

**Comment by jrieken** [comment] 2017-03-17 08:45
Unsure @eamodio because TypeScript runs in yet another process (`tsserver`) so unless the extension part that runs in the extension host (mainly data conversion) goes crazy it should be that typescript server process... @mjbvz ideas?

**Comment by eamodio** [comment] 2017-03-17 14:23
Hrm -- is there any other way to identify the particular extension after the fact (while the process is still running of course)? Is there any logging I can turn on? Or could vscode just send "extra" unused command line arguments to have the extension name in it?

**Comment by jrieken** [comment] 2017-03-20 08:02
You could try `--logExtensionHostCommunication`. Since this logs *a lot* it would be helpful to have a somewhat reproducible scenario first.

**Comment by eamodio** [comment] 2017-03-22 19:39
@jrieken thanks -- unfortunately nothing reliably reproducible at this point. Any thought on a change to have vscode send an unused commandline parameter to the extension host which the extension name in it? Is that something that is possible?

**Comment by jrieken** [comment] 2017-03-23 08:30
Not sure I got that. What would we the extension host with that name/param?

**Comment by eamodio** [comment] 2017-03-23 12:40
It would just be so when we got the command line args of the extension host process we'd know which extension was in it.

**Comment by fifafu** [comment] 2017-05-22 21:08
I had the same issue, but was able to find the extension that caused it using the  ```ps aux | grep pid``` command. I think it would be great to show which extension uses how much CPU directly in VSCode.

Without the command it was hard to figure out, because apparently disabling the extension in VSCode doesn't stop the processes. (For me it was a beta version of the angular 2 language service that caused the issues)

**Comment by mjbvz** [comment] 2017-06-01 23:53
Closing this issue as there not enough information to investigate this

Please try out the current insiders builds and updating all of your extensions. If you are still running into a high cpu usage issues, identify the offending process and open a new issue so that we can investigate further

**Closed by mjbvz** 2017-06-01 23:53 UTC
Labels: caused-by-extension, freeze-slow-crash, needs more info

**Comment by brandondrew** [comment] 2017-06-13 15:42
@mjbvz 

> identify the offending process and open a new issue so that we can investigate further

_How_, exactly?  Judging by the boatloads of issues filed that are similar to this one, it seems that:

1. This is a major problem with VS Code, and
2. people have not been given the tools they need to have to be able to identify the source of the problem.

In other issues I saw a pattern of people saying things like "I disabled X and restarted and the problem went away" only to later come back and say "oh, the problem returned but I'm not using X, so I'm not sure what the source of the problem was".  It seems reasonable to conclude that it's actually very difficult to identify the offending process.

At least for us.  It seems like it might be quite easy for VS Code to identify the offending process.  At least it should be completely possible to do so.  Perhaps VS Code could provide a way to identify the extension that is eating more than its fair share of CPU?  Perhaps it could offer to kill and disable that extension when this happens?

That seems like it might be a real solution to this problem.

**Comment by richarddavenport** [comment] 2017-06-13 16:51
I agree with @brandondrew, I have high cpu usage on insiders frequently and the last couple of builds have been so bad I have moved back to the stable build. I use the same extensions for both builds, and it's fine in stable but not in insiders. If the process could be easier to identify, then these problems would (more than likely) be resolved at a much quicker pace.

**Comment by pocesar** [comment] 2017-06-13 22:06
I usually work with 4-5 insiders editors opened, and each uses at least 6% of CPU, to the sum of 30% non-stop combined...

**Comment by mjbvz** [comment] 2017-06-13 22:28
Right now to identify the offending process, use the process explorer or run `ps aux | grep -i code`

@alexandrudima is looking into handling extensions leaking processes this month. A better story for identifying high cpu usage from spawned processes may also be within the scope of that investigation
