### ISSUE TITLE
VSCode takes ~15 seconds to appear in the launcher bar

### ISSUE THREAD

**Issue by bamarni** [Microsoft/vscode#52783] opened 2018-06-25 07:41 UTC
Screencast (I only recorded a few seconds to highlight the problem, but it lasts 15 seconds) : 

![peek 2018-06-25 09-31](https://user-images.githubusercontent.com/1205386/41836381-d3695826-785a-11e8-96bc-fe5b0f501ecf.gif)

- VSCode Version: 1.24.0
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

When I open VSCode from the desktop interface, it takes ~15 seconds before it shows-up in the launcher bar, in the meanwhile I'm already able to edit files in my projects normally.

The annoying thing with this is when I switch to another window after opening VSCode, I'm then not able to retrieve the VSCode window for 15 seconds. Eg. it doesn't show when I press [Window + TAB], if it's in favorites in the launcher it will open a new window instead of maximizing the existing one.

(When I launch VSCode by entering `code` from the terminal then I don't see this problem, the icon shows immediately.)

**Comment by bpasero** [comment] 2018-08-23 08:53
I see this too very often.

**Comment by bpasero** [comment] 2019-01-28 14:13
This is a duplicate of https://github.com/Microsoft/vscode/issues/65460 which I just reopened.

**Closed by bpasero** 2019-01-28 14:13 UTC
Labels: electron, help wanted, linux, upstream
