### ISSUE TITLE
Editor find widget doesn't show what you type

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#126908] opened 2021-06-22 13:42 UTC
* todays insider
* press cmd+f inside an editor
* start typing
* find is in progress but the find box doesn't show anything

https://user-images.githubusercontent.com/1794099/122935323-8967a100-d370-11eb-9835-d4dd57557af1.mov

**Comment by rebornix** [comment] 2021-06-22 15:02
/duplicate of https://github.com/microsoft/vscode/issues/126896

**Closed** 2021-06-22 15:03 UTC
Labels: *duplicate
