### ISSUE TITLE
Cmd + click underlines a single word instead of the entire filename when it has dashes or kebab case on an import

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40718] opened 2017-12-22 11:54 UTC
Cmd + click underlines a single word instead of the entire filename when it has dashes or kebab case on an import

- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

![dec-22-2017 04-48-31](https://user-images.githubusercontent.com/2301847/34297117-7061d6c2-e6d3-11e7-9c5d-7b33e7ba30e4.gif)

WebStorm comparison:
![dec-22-2017 04-53-38](https://user-images.githubusercontent.com/2301847/34297227-1b383b72-e6d4-11e7-88d8-1d80f33cebd3.gif)

1. Create a JS file with an import to a file with a filename being kebab case or having dashes
2. Cmd+Click and notice the underline

EXPECTING: underlines entire filename
ACTUAL: underlines single word

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-12-22 19:13
Duplicate of #10037

**Closed by mjbvz** 2017-12-22 19:13 UTC
Labels: editor
