### ISSUE TITLE
vs-code dont popup new page

### ISSUE THREAD

**Issue by soshyan** [Microsoft/vscode#9597] opened 2016-07-21 19:56 UTC
- VSCode Version:  1.3.1
- OS Version: windows 7

Steps to Reproduce:

1. when open new code 
 vs-code dont show i for me 
and i must click icon vs-code on task bar

**Comment by kieferrm** [comment] 2016-07-22 16:42
Duplicate of #9562.

**Closed** 2016-07-22 17:51 UTC
Labels: duplicate
