### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

### ISSUE THREAD

**Issue by prateekjpr20** [microsoft/vscode#183196] opened 2023-05-23 09:23 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230509

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
    at getDocumentRegistryEntry (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133014:11)
    at Object.releaseDocumentWithKey (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133111:19)
    at getOrCreateSourceFileByPath (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141789:30)
    at Object.getOrCreateSourceFile (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141773:14)
    at /private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141705:42
    at Object.getSourceFileWithCache [as getSourceFile] (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117879:24)
    at findSourceFileWorker (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120247:23)
    at findSourceFile (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120167:20)
    at /private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120116:22
    at getSourceFileFromReferenceWorker (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120100:69)
    at processSourceFile (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120114:5)
    at processRootFile (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119911:5)
    at /private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:41
    at forEach (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:5)
    at synchronizeHostData (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141729:15)
    at Object.getProgram (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141801:5)
    at InferredProject2.updateGraphWorker (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174359:41)
    at InferredProject2.updateGraph (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174211:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176601:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178219:12)
    at /private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:64
    at flatMap (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:24)
    at updateOpen (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179629:29)
    at /private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182193:14)
    at IpcIOSession.executeCommand (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:29)
    at IpcIOSession.onMessage (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182243:51)
    at process.<anonymous> (/private/var/folders/qs/30n63z654wv5lbfglppwyrjc0000gr/T/AppTranslocation/F3256FBE-BD14-4C5C-B904-8EDD4A3BA99B/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (d0ca6131bfe1936153df2f8a11f85e3790ec1f4b, 2023-05-10T16:07:59.375Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id c191e60d-84f7-4d96-ba4f-2744173621f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot-chat|Git|0.1.2023052205
copilot-nightly|Git|1.86.112

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
0bg3d529:30680467
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-24 21:18
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.


 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment] 2023-05-24 23:59
Duplicate of https://github.com/microsoft/TypeScript/issues/54381

**Closed by mjbvz** 2023-05-24 23:59 UTC
Labels: info-needed
