### ISSUE TITLE
Markup cell initialize fail on window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#161520] opened 2022-09-22 19:06 UTC
This is hard to have stable reproduce but almost every one in the notebook v-team ran into this in last few weeks: when reloading the window with a notebook editor open, the notebook editor might not open successfully, closing it and reopening the same document can fix it.

Debugged with log points in Insiders and I found it failed in `BacklayerWebview#initializeMarkup`

https://github.com/microsoft/vscode/blob/d847171943679c45058838150104741512743d41/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1159-L1182

The `initializeMarkup` message is sent to the webview (at least we called the webview `postMessage`) but the response never came back. When this happens, the webview/iframe contains the `html` content, Jupyter notebook renderers' styles, but it doesn't have anything related to the markup renderers (no markup css).

@mjbvz please help take a look, we can have a call to do some debugging together.

**Comment by mjbvz** [comment] 2022-09-23 03:46
@rebornix  I haven't seen this myself but addressed some possible causes with #161550. Let me know if you can reliably reproduce this issue

3f92eb60d8a2032c10246c9c2b234c0e136caa48 also fixed some issues where if a renderer failed to load or threw during loading, we would never load the notebook

**Comment by mjbvz** [comment] 2022-09-27 01:51
Closing since we haven’t seen this happening again recently

**Comment by IanMatthewHuff** [comment] 2022-09-29 23:22
@rebornix @mjbvz Is it this issue here with a blue cylon but the main document never loads?
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/812783/193158814-da336482-02bd-47f5-a351-090da534abf3.png">

I still get this. I opened a document and reloaded and got this on the fourth try (current insiders). Anything I can collect when this happens to help out?

**Closed** 2022-10-04 19:10 UTC
Labels: bug, important, verification-found, candidate, notebook-markdown
