### ISSUE TITLE
Debug: Scheme is missing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57674] opened 2018-08-31 09:41 UTC
Steps to Reproduce:

1. debug a hello world extension
2. step into code that is not from the extension

=> `uri.ts:19 [UriError]: Scheme is missing: {scheme: "", authority: "", path: "Unknown Source", query: "", fragment: ""}`

Possibly from somewhere around here: https://github.com/Microsoft/vscode/blob/e055c6ef94e024405f34c0cade76886d42d3fa77/src/vs/workbench/parts/debug/common/debugSource.ts#L50

**Comment by isidorn** [comment] 2018-08-31 10:05
We would have to add more checks to verify if it has a scheme.
Also adding @weinand

**Comment by KamasamaK** [comment] 2018-09-14 00:00
`Uri.parse` is causing a ton of these in my debug console since v1.27. The problem is that I am using it to validate a URI by checking if `scheme` is populated. I assume it is expecting that validation to be done prior to parsing, but if so what is the best way to do this? There is no `Uri.validate` or similar function in the API from what I can tell.

**Comment by isidorn** [comment] 2018-09-18 11:50
Fixed via 5717c6a539

**Closed by isidorn** 2018-09-18 11:50 UTC
Labels: debt, debug
