### ISSUE TITLE
Keyboard navigation not working

### ISSUE THREAD

**Issue by simonl65** [Microsoft/vscode#68124] opened 2019-02-07 16:01 UTC
Issue Type: <b>Bug</b>

# Steps to reproduce:
1. Open Explorer panel
2. Click anywher inside Explorer panel
3. Type characters of a file you know exists

# Expected result:
Highlight the file in the tree

# Actual result:
Apparently random file highlight.

This happens with and without extensions enabled.

VSCode Version: 1.31.0 (1.31.0)
Platform: MacBook

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Users/simonlincoln/Projects/ultima/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
vscode-file-header-comment|Ani|0.10.1
vscode-intelephense-client|bme|0.8.8
better-phpunit|cal|1.3.2
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.8.0
vscode-new-file|dku|4.0.2
githistory|don|0.4.6
xml|Dot|2.4.0
EditorConfig|Edi|0.12.8
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.1
gitflow4code|Gre|1.2.3
compareit|in4|0.0.2
php-cs-fixer|jun|0.1.95
VS-code-vagrantfile|mar|0.0.7
yarn-lock-syntax|mar|0.1.3
twig-language-2|mbl|0.5.1
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.11.1
snippet-creator|nik|0.0.5
vetur|oct|0.14.5
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.2
LiveServer|rit|5.4.0
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.24
vue-vscode-snippets|sdr|1.3.0
laravel-56-snippets|Tha|2.2.3
bootstrap4-vscode|the|6.0.3
vscode-status-bar-format-toggle|tom|1.4.0
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2

(3 theme extensions excluded)

</details>

**Comment by kieferrm** [comment] 2019-02-07 17:46
@simonl65 can attach a screen cast that shows it?

**Comment by joaomoreno** [comment] 2019-02-08 08:11
> Apparently random file highlight.

What does this mean?

**Comment by simonl65** [comment] 2019-02-08 10:21
@kieferrm Can you point me to instructions on how to do that, please?

@joaomoreno Sorry, my bad use of words - I mean that when I search for (say) "mail" I see the folder "templates" highlighted.
![screenshot 2019-02-08 at 10 10 55](https://user-images.githubusercontent.com/14094202/52471885-dd9bcd00-2b89-11e9-920a-3e2a50b19b38.png)
I guess that's because "templates" contains both "m" and "a"?
Also, if I search for "api" nothing gets highlighted:
![screenshot 2019-02-08 at 10 13 54](https://user-images.githubusercontent.com/14094202/52472046-497e3580-2b8a-11e9-8772-3e35f6e5caf6.png)
However, if I then click the filter I see only the "bootstrap" folder and the "routes" folder - where the latter actually contains "api.php":
![screenshot 2019-02-08 at 10 16 16](https://user-images.githubusercontent.com/14094202/52472252-bbef1580-2b8a-11e9-9835-d01d2ae33c14.png)
With this:
a) it would be better if the tree opened to show all instances of "api" files/folders,
b) I don't see why "bootstrap" folder is shown and not "app" too, unless it's because "bootstrap" has "ap" with nothing after it, whereas "app" is clearly not "api" - either way, I wouldn't expect either of them to show!

Thank you both for your follow-up though.

**Comment by joaomoreno** [comment] 2019-02-08 15:33
Got it, closing it as a duplicate of #66971

This feature won't change any collapse states. It will also not recurse into unexplored folders for now. We need to polish this feature in the explorer.

**Closed by joaomoreno** 2019-02-08 15:33 UTC
Labels: needs more info, new release
