### ISSUE TITLE
[css] syntax highlighting breaks when using @keyframes

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#16266] opened 2016-11-30 11:41 UTC
Using version 1.7.2 on MacOS.

[Example from `create-react-app`
](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/App.css)
```css
.App {
  text-align: center;
}

.App-logo {
  animation: App-logo-spin infinite 20s linear;
  height: 80px;
}

.App-header {
  background-color: #222;
  height: 150px;
  padding: 20px;
  color: white;
}

.App-intro {
  font-size: large;
}

@keyframes App-logo-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
```

![image](https://cloud.githubusercontent.com/assets/2827047/20751089/4a4b8fe6-b6fa-11e6-9706-cc59417f4bbb.png)

**Comment by mrmlnc** [comment] 2016-11-30 11:48
duplicate of #3481 🔍

**Comment by chrmarti** [comment] 2016-11-30 17:15
Thanks @mrmlnc !

**Closed by chrmarti** 2016-11-30 17:15 UTC
Labels: duplicate
