### ISSUE TITLE
Image fails to show when file is being renamed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86407] opened 2019-12-05 14:13 UTC
* drag a screen shot (png file) into vs code
* notice that is shows as image-editor
* in the explorer, change the name of the file
* 🐛  the image-editor now shows an error

**Comment by mjbvz** [comment] 2019-12-05 19:24
Having trouble reproducing this (also tested with a png):

![a](https://user-images.githubusercontent.com/12821956/70265033-6c4b8d00-174e-11ea-993c-c24d128db4e6.gif)

OS? Any special repo steps I missed?

**Comment by jrieken** [comment] 2019-12-06 07:50
![Dec-06-2019 08-49-59](https://user-images.githubusercontent.com/1794099/70305723-6d8bc100-1805-11ea-9440-fd00bd09159d.gif)


Mac with `bbf00d8ea6aa7e825ca3393364d746fe401d3299` and there actually is that error below ⬇️ 


```
  ERR Invalid group provided: Error: Invalid group provided
    at Object.t.editorGroupToViewColumn (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3051:835)
    at Object.resolveWebview (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4256:240)
    at async C.tryRevive (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4248:286)
    at async C.resolveWebview (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4248:352)
    at async e.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4246:551)
    at async e.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4250:837)
    at async e.setInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6298:406)
    at async p.doSetInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3969:848)
    at async p.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3968:425)
    at async file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5692:787
    at async e.replaceEditors (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5698:877)
```

**Comment by mjbvz** [comment] 2019-12-06 19:40
Thanks @jrieken. That is very helpful. I still cannot repo but from that error I believe I know what the error is

**Comment by mjbvz** [comment] 2019-12-06 19:47
@jrieken I pushed a fix for what I suspect is the root cause of this issue.

If you can confirm that the change fixes the bug on your machine, I'll take it into the release branch too. Reopneing the bug to track that

**Comment by jrieken** [comment] 2019-12-09 15:06
So, the change is not in insiders then? Should this be tested from master?

**Comment by mjbvz** [comment] 2019-12-09 19:41
Actually it made it in before we forked. Should be in the current insiders (1.41)

**Closed** 2019-12-09 19:41 UTC
Labels: bug

**Comment by jrieken** [comment] 2019-12-10 10:56
Great - marking as verified because it worked with my testing
