### ISSUE TITLE
Support WSL git

### ISSUE THREAD

**Issue by jeasonstudio** [Microsoft/vscode#29812] opened 2017-06-29 01:12 UTC
I have installed git in wsl and how can I deploy it to my vscode

**Comment by ztolley** [comment] 2017-06-30 08:17
To add to this. I'd like to be able to tell Visual Studio Code to not only allow you to tell the terminal to use WSL Bash but also configure it specify the path to the git client to use, or the shell, so that git commands issued use the WSL copy (so it picks up the ssh keys etc in that shell) and also run any git hooks in the bash shell too.

**Comment by nguyenbathanh** [comment] 2017-08-21 16:02
This should be great.

**Comment by crewone** [comment] 2017-08-31 09:13
This would be great. 

To illustrate the difference: git on windows does not properly handle symlinks (They seem to be invisible to NTFS in 'windows mode'),  but WSL git properly handles these symlinks.

**Comment by zmsy** [comment] 2017-09-15 15:32
Very confusing for windows users to have two separate git client installs, two sets of ssh keys for the same service, etc depending on whether or not they're using wsl bash.

Would be excellent if setting the terminal as wsl bash automatically defaulted to using wsl git as well.

**Comment by FistMeNaruto** [comment] 2017-09-18 20:41
Facing the same issue

**Comment by wasabigeek** [comment] 2017-10-13 08:41
@zmsy I'm moving off topic, but should you be able to use a single set of SSH keys? When you do keygen, save them in `/mnt/c/Users/USERNAME/.ssh` - then you can add that same path when you use `ssh-agent`.

Correct me if wrong!

**Comment by joaomoreno** [comment] 2017-11-17 08:46
Duplicate of #9502

**Closed by joaomoreno** 2017-11-17 08:46 UTC
Labels: feature-request, git, WSL
