### ISSUE TITLE
anomalies after hibernation

### ISSUE THREAD

**Issue by alex-pro27** [Microsoft/vscode#70875] opened 2019-03-21 03:28 UTC
Issue Type: <b>Bug</b>

after you exit the sleep mode, there is a problem in the built-in console, everything becomes white, only helps restart vscode

![Снимок экрана от 2019-03-21 13-24-02](https://user-images.githubusercontent.com/18297893/54732002-2e690180-4bdd-11e9-8f97-7b5f242380a3.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.52GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
jquerysnippets|don|0.0.1
react-native-snippet|jun|0.5.0
vscode-language-pack-ru|MS-|1.32.4
python|ms-|2019.2.5558
cpptools|ms-|0.22.0
Go|ms-|0.9.2
java|red|0.41.0
vscode-nginx|sha|0.6.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.1

(4 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2019-03-21 07:34
Possible duplicate of #68346

**Closed** 2019-03-21 14:51 UTC
Labels: integrated-terminal
