### ISSUE TITLE
VS Code is sometimes losing keystrokes

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#233762] opened 2024-11-13 12:56 UTC
I can't always repro, but how it happens: 

1. I'm typing something in an editor and suddenly my kestrokes stop entering characters in the editor
2. After a couple of seconds of wait without any keystrokes, keystrokes work again

Version: 1.96.0-insider
Commit: 399779942db4d7ab1bd6f6ae976482d0020f10ca
Date: 2024-11-13T05:04:32.098Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by aiday-mar** [comment] 2024-11-13 16:17
Thanks for filing this issue. Do you remember if you had the edit context enabled?

**Comment by ulugbekna** [comment] 2024-11-14 15:59
I don't think it's enabled unless I'm enrolled in some experiment. Happy to double check if there's a way to do so.

**Comment by aiday-mar** [comment] 2024-11-15 09:16
Currently there is no experimen to enable edit context. I will keep an eye out for this issue.

**Comment by sahin52** [comment] 2024-11-20 15:16
I don't want to disturb, can you clear a bit?
- Do you have any extensions or were you working without extensions. It might be related to an extension checking something syncronously and causing that problem. 
- What was the file type you were working on. If it is causing that problem even in a txt file, it is probably related to VSCode, but if it is another file type, an extension might cause that problem.
- How often do you confront that problem?
- After stopping key strokes, do the older strokes that you already pressed show up, or do they just get lost
- Does VSCode completely freeze, or do just keystrokes stop working and you can click somewhere else, or other keypresses work fine (for example Open Command Palette - Ctrl + Shift + P)
- I checked the existing issues, one of them are somewhat related: https://github.com/microsoft/vscode/issues/215940  but it is closed. 
- Are you using a bluetooth keyboard? Bluetooth keyboards sometimes do exactly the same. So if you encounter this in another application, that is related to another problem like this

I was unable to reproduce this problem, these are the installed extensions:  
```
analytic-signal.preview-pdf
csstools.postcss
eamodio.gitlens
ecmel.vscode-html-css
esbenp.prettier-vscode
github.copilot
github.copilot-chat
magicstack.magicpython
ms-playwright.playwright
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-vsliveshare.vsliveshare
vitest.explorer
yoavbls.pretty-ts-errors
```
on Windows 10 machine with latest VSCode.

**Comment by aiday-mar** [comment] 2024-12-09 09:47
Hi @ulugbekna. In case if you saw this after disabling the EditContext, I have made some improvements to the EditContext lately which may have fixed this issue. Could you let me know if you still see this happening? If not I will close the issue.

**Closed** 2024-12-09 10:17 UTC
Labels: info-needed, important
