### ISSUE TITLE
how to use integrated terminal to debug my program？

### ISSUE THREAD

**Issue by CFhM-Lolipop** [Microsoft/vscode#8090] opened 2016-06-24 07:19 UTC
- VSCode Version:1.3.0
- OS Version:windows 10 build 14371

![image](https://cloud.githubusercontent.com/assets/9619115/16330803/92e9fc8c-3a1e-11e6-83be-9ad496271c0b.png)
as the picture shows, i'd debug my python program, and the debugger always call the original terminal, not the one that integrated in the vscode, i wanna know how to set that the debugger can use the integrated terminal  to show the results.Thank you.(not only  python, cpp also)

**Comment by Tyriar** [comment] 2016-06-24 07:53
Duplicate of https://github.com/Microsoft/vscode/issues/547

For python in particular this is mentioned here https://github.com/DonJayamanne/pythonVSCode/issues/183

**Closed by Tyriar** 2016-06-24 07:53 UTC
