### ISSUE TITLE
Add a setting to only unfold lines by clicking icons (or keyboard shortcut), not by clicking text

### ISSUE THREAD

**Issue by StephenNay** [Microsoft/vscode#63065] opened 2018-11-13 23:39 UTC
I'm working primarily in YAML and JSON files. Like everyone does, I fold sections of code that I don't want to see at the current time. The issue (for me) is that when I click to place the cursor for one reason or another, if that click happens to be on a folded line then the section unfolds, which is not what I want. I would like to see a preferences setting that would only unfold lines when the icon by the line number is clicked or when the keyboard shortcut is used; don't unfold a section just because it is clicked on. I know that changing folded code automatically unfolds it, but clicking on a line should not constitute a change.

**Comment by usernamehw** [comment] 2019-01-03 14:07
Possible duplicate of #64026

**Comment by aeschli** [comment] 2019-01-03 16:06
duplicate of #64026

**Closed by aeschli** 2019-01-03 16:06 UTC
Labels: editor-folding
