### ISSUE TITLE
Page scrolling lags using touchpad

### ISSUE THREAD

**Issue by Elementals** [Microsoft/vscode#27994] opened 2017-06-04 07:42 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|1.0.0|
|java|redhat|0.4.0|
|Seti-theme|TsumiNa|0.0.1|;

---

Steps to Reproduce:

1. Launch VSC, while using two fingers on touchpad to scroll the code page, the response lags.
2. Press ctrl+k, z into zen mode, the lag disappears.

(My device is Surface Pro 4 with an official touchpad)

**Comment by alexandrudima** [comment] 2017-06-06 06:43
Duplicate of #13612. Some known workarounds are collected at https://github.com/Microsoft/vscode/wiki/Known-issues#smooth-scrolling-on-windows-using-laptops-with-precision-touchpad

**Closed by alexandrudima** 2017-06-06 06:43 UTC
