### ISSUE TITLE
Open Markdown links inside the preview pane itself as Markdown preview

### ISSUE THREAD

**Issue by asphub** [Microsoft/vscode#37883] opened 2017-11-09 06:16 UTC
Open Markdown links inside the preview pane itself as Markdown preview, Now it is opening in a new tab and it's opening in Edit mode. Please fix this and this would be surely great for documentation purposes.

**Comment by mjbvz** [comment] 2017-11-09 18:35
Duplicate of #19339

**Closed by mjbvz** 2017-11-09 18:35 UTC
Labels: duplicate, feature-request, markdown
