### ISSUE TITLE
Light bulb influences code indent when tabs-based whitespace is rendered (Remoting)

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#92290] opened 2020-03-09 20:33 UTC
This was originally reported against the C/C++ Extension ( https://github.com/microsoft/vscode-cpptools/issues/5081 ), but appears to be specific to VS Code.  Transfering the issue here, as the user requested.  @mikedld  

**Describe the bug**
- OS and Version: Linux
- VS Code Version: 1.43.0-insider (was present on previous versions as well)
- C/C++ Extension Version: 0.26.3 (was present on previous versions as well)
- Other extensions you installed (and if the issue persists after disabling them): a few, the issue persists
- When `C_Cpp.dimInactiveRegions` and `editor.renderWhitespace` are enabled and tabs are used for indentation, putting cursor on a dimmed line of code shows the yellow light bulb which seems to offset the code past the expected indent.

**To Reproduce**
1. Set `C_Cpp.dimInactiveRegions` to `true` (the default)
2. Set `editor.renderWhitespace` to `"all"`
3. Use tabs for code indentation
4. Find an inactive code region and put the cursor on one of the inactive lines, so that it's on the non-indent part of the line (after leading whitespace)
5. Wait for the yellow light bulb (with "Disable inactive region colorization" action) to appear
6. Notice the indent increase

**Expected behavior**
Light bulb visibility doesn't influence the indent.

**Screenshots**
C++ code indented with tabs:
![Peek 2020-03-08 18-49](https://user-images.githubusercontent.com/298203/76166438-98bcde00-616f-11ea-8dfc-060573c2125b.gif)
![Peek 2020-03-08 20-44](https://user-images.githubusercontent.com/298203/76168133-b1cc8b80-617d-11ea-92f4-c3ce5c12c1c6.gif)

C++ code indented with spaces:
![Peek 2020-03-08 18-54](https://user-images.githubusercontent.com/298203/76166444-a07c8280-616f-11ea-9a22-30885c692ee2.gif)

JavaScript code indented with tabs (within Interactive Playground):
![Peek 2020-03-08 18-46](https://user-images.githubusercontent.com/298203/76166431-86db3b00-616f-11ea-96b1-89b311523306.gif)

**Additional context**
Font: Ubuntu Mono

**Comment by mjbvz** [comment] 2020-04-09 23:50
@alexdima I believe this is related to the c++ extension's use of decorators

**Comment by alexdima** [comment] 2020-04-13 22:27
@mikedld Does the issue reproduce when you disable all extensions except the C++ one? (I notice from the gif that you are using gitlens and I would like to rule that out).

**Comment by mikedld** [comment] 2020-04-14 04:42
@alexdima, you're absolutely right, disabling all extensions except for C++ makes the issue disappear, then re-enabling only GitLens makes it appear again. I'm once again sorry for not properly troubleshooting it myself before reporting.

**Comment by alexdima** [comment] 2020-04-14 08:59
Thank you @mikedld .

@eamodio Can you please help further troubleshoot to the root cause? I was thinking that GitLens only uses the decorations at the end of the line or before the line content, but it looks like in this case there are even more kinds of decorations that might interfere with the lightbulb?

**Comment by mikedld** [comment] 2020-04-14 19:27
@alexdima, I had `coenraads.bracket-pair-colorizer-2` disabled for some time now and it does still reproduce. Below are two GIFs with it enabled and disabled for comparison (I still have GitLens enabled, otherwise it doesn't happen). As the cursor is at column 0 inside the inactive block, the lightbulb isn't even shown (not sure why though) which makes me wonder if it's even related to it...

Enabled:
![Peek 2020-04-14 22-22](https://user-images.githubusercontent.com/298203/79265376-aff19880-7e9e-11ea-894d-62f244095e4d.gif)

Disabled:
![Peek 2020-04-14 22-23](https://user-images.githubusercontent.com/298203/79265386-b41db600-7e9e-11ea-955c-9d5615759e57.gif)

**Comment by mikedld** [comment] 2020-04-16 07:21
I'm not sure if it helps or not but just going to note (since nobody did yet) that it looks like each tab char is one space char wider when GitLens annotation on a line is shown. This leads to noticeable increasing delta with each new tab char on a line: with 1 tab it's a 1 space shift, with 3 tabs it's a 3 spaces shift.

**Comment by mikedld** [comment] 2020-08-02 11:32
The issue remains. Let's please sort this out @alexdima @eamodio. I was never contacted for any additional information; either remove "needs more info" label or tell me what you need... In either case, closing this is not a good idea.

<details><summary>Currently using these versions</summary>

> Version: 1.48.0-insider
> Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
> Date: 2020-07-24T05:43:53.437Z
> Electron: 9.1.0
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Linux x64 5.6.13-gentoo

> Name: C/C++
> Id: ms-vscode.cpptools
> Description: C/C++ IntelliSense, debugging, and code browsing.
> Version: 0.29.0
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

> Name: GitLens — Git supercharged
> Id: eamodio.gitlens
> Description: Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more
> Version: 10.2.2
> Publisher: Eric Amodio
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
</defails>

**Comment by alexdima** [comment] 2020-08-03 11:40
@mikedld I'm sorry about that. I have tried with the gitlens extension and the following settings:
```
{
    "editor.renderWhitespace": "all"
}
```

but I could not reproduce:

![Kapture 2020-08-03 at 13 39 13](https://user-images.githubusercontent.com/5047891/89178805-be1f0e00-d58e-11ea-90fb-67b87749c677.gif)

Is this perhaps influenced by some of your settings? Can you please try commenting out your settings temporarily and check if this reproduces?

**Comment by eamodio** [comment] 2020-08-10 22:10
@mikedld I can't reproduce this either. If you find that your settings are causing this, can you post them?

**Closed** 2020-08-18 11:23 UTC
Labels: editor-code-actions, needs more info
