### ISSUE TITLE
Endless progress opening a custom editor who's view type is not registered

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99258] opened 2020-06-03 13:12 UTC
Testing #99003

- Trying the custom editor extension sample 
- Do not register a custom editor for `catCustoms.catScratch`. In short comment out the line 

https://github.com/microsoft/vscode-extension-samples/blob/41341293757982bedebf1176a92fa6e028f68d3a/custom-editor-sample/src/extension.ts#L7

- Open the example.cscratch file and shows infinite progress

**Comment by mjbvz** [comment] 2020-06-03 21:12
Duplicate of #96407

**Closed by mjbvz** 2020-06-03 21:12 UTC
