### ISSUE TITLE
Pressing Ctrl+W on release notes closes the window

### ISSUE THREAD

**Issue by bancek** [microsoft/vscode#82670] opened 2019-10-16 08:07 UTC
Issue Type: <b>Bug</b>

Open a new window, close the Untitled tab, open Release notes and press Ctrl+W (or Cmd+W) on macOS.

Expected:
Release notes tab is closed.

Actual:
Release notes tab is closed as well as the current window.

You can also open a file, open Release notes and press Ctrl+W. Release notes and the last file will close.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-65-generic

**Comment by Anamika28** [comment] 2019-10-16 13:56
I tried reproducing the issue, seems everything is working fine.

**Comment by OneQuid** [comment] 2019-11-13 22:59
The same happened when closing opened images.
Using "Ctrl+W" to close an image would  1)close another file if there is, 2) otherwise close current VSCODE window 
OS version: Linux Mint 19.2 Tina (Cinnamon)/ XM Linux live(XFCE) image on VM
VS Code version: 1.40.0 and the insider version

Also I tried to reproduce it on a Windows 7 VM, and it was not there.
Is it caused by Electron by any chance?

I'd love to try to fix it. However, yet have no clue on where the related lines of codes are located. Any hints or suggestions? Thanks

**Comment by mjbvz** [comment] 2019-11-19 19:24
Reopening since the fix caused regressions and had to be reverted

**Comment by DavideViolante** [comment] 2020-04-13 08:30
I confirm this is still happening with vscode v1.44.0 and Ubuntu 18.04. Many similar issues are opened already: https://www.github.com/microsoft/vscode/issues/82670, https://github.com/microsoft/vscode/issues/86790

**Comment by mjbvz** [comment] 2020-04-17 22:28
Should be fixed by dbc7b4d912d34da083c969e5ee921f74119c30b9

**Closed by mjbvz** 2020-04-17 22:28 UTC
Labels: bug, linux, webview
