### ISSUE TITLE
Git: Cannot read property 'resourceUri' of undefined

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#35724] opened 2017-10-06 14:00 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (7ac1f1e05baad03d4dd8f8515f1e598180b2c97e, 2017-09-30T05:06:21.234Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
Go|luk|0.6.66
code-beautifier|mic|1.7.2
vscode-icons|rob|7.14.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open the Git Sidebar
2. Click on the 'Discard changes' button filename: fetch.go
3. Then the following error occurs: 
![image](https://user-images.githubusercontent.com/17984549/31281075-aed6e9da-aaae-11e7-949a-bfa3bf1bbee3.png)

Developer Tools: 
![image](https://user-images.githubusercontent.com/17984549/31281100-c024ad4e-aaae-11e7-9c3c-70fdcb9fef53.png)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-10-06 14:02
Looks like that is the same problem like in #33819 and #33389

**Comment by chrmarti** [comment] 2017-10-06 15:21
Must be a new issue since you are on 1.17.0.

**Comment by pftbest** [comment] 2017-10-08 16:22
```
Git: Cannot read property 'resourceUri' of undefined
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
```

**Comment by joaomoreno** [comment] 2017-10-11 07:10
@maxibanki @pftbest Does the issue reproduce easily?

**Comment by maxibanki** [comment] 2017-10-11 07:34
It happened just one time while i was on work. No way to reproduce it currently as i know.

**Comment by aekazitt** [comment] 2017-10-11 07:46
Happening as I am typing this. 
I tried to press + to add a file that already exists in the Git repo and this error kept popping up. And it did not go away so I typed "git commit -am '[commit-message]'" into the console and could commit just fine, however adding using the GUI caused the problem as seen in the screenshot.

<img width="1440" alt="screen shot 2017-10-11 at 3 42 37 pm" src="https://user-images.githubusercontent.com/3035165/31427835-42c8edba-ae9b-11e7-9b93-81dfc2507dd5.png">

Hope this helps
I have included the output console in the screenshot to show as much as possible.

**Comment by AntoineDrouhin** [comment] 2017-10-17 13:55
Same message when trying to stage changes done in an untracked folder.

Worked around it by manually adding the folder with `git add folderName/`

**Comment by joshSummerhays** [comment] 2017-10-20 23:05
Having this issue when trying to stage changes as well as clicking on the file and trying to see the diff. Worked smoothly before an update

**Comment by pftbest** [comment] 2017-10-21 13:38
It happened to me twice yesterday, and in both cases i was editing files that where outside of current workspace but in the same git repo.

**Comment by simon-r** [comment] 2017-10-23 12:46
It happened with c++ when I've tried to add a new source file.

**Comment by Pajn** [comment] 2017-10-30 13:59
I have a bunch of files right now project that is like these, but other files are fine. Is hard to reliably reproduce as only some files sometimes becomes problematic. If I restart vscode all files can be fine. I've seen this in multiple projects which differ quite a bit so I have no idea what the common thing could be.

**Comment by pranav9196** [comment] 2017-10-31 15:57
Add the particular files by going to the directory in your terminal(right click on the folder in your project and open it in terminal) and add all the files you want.

**Comment by klj890** [comment] 2017-11-01 03:05
me too

**Comment by usman-liaquat** [comment] 2017-11-01 09:08
try to perform action using terminal, it worked for me,

**Comment by joaomoreno** [comment] 2017-11-02 09:27
This seems very hard for me to reproduce. It's very possible that https://github.com/Microsoft/vscode/commit/9e9f809fc0d43f4b5079eaeb37cd8a986cce14e4 fixed it. But not sure...

I'l close it for now. Please try the latest Insiders release or the upcoming November stable release (available next week) and let me know if you still see the issue.

**Comment by mjbvz** [comment] 2017-11-03 21:19
For verification, I tried running this command a number of times and did not see the error being hit. Not sure if it only reproduces under certain configurations 

As @joaomoreno said, let us know if you hit this again in the current insiders builds

**Comment by pkreipke** [comment] 2017-11-04 17:43
Was seeing this issue on a single file constantly, in different projects (diff file in diff projects). Relaunching vscode to install 1.17.2 made problem go away. Will report back if begins happening again.

**Comment by maxibanki** [comment] 2017-11-07 11:53
@joaomoreno I had the issue again with this version:

- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 6.1.7601

So the commit 9e9f809 doesn't fixed the issue. 
Here some details, which maybe helps you to reproduce it better:

I opened the SCM sidebar and tried to type in a Git commit message. After that I want to view the difference for some files.
![image](https://user-images.githubusercontent.com/17984549/32492333-36739fd6-c3ba-11e7-9649-d3069d09c96b.png)
All files worked fine to see the difference except the `packages.json`. When I try to click on the file, no error appears. Also the `Stage Changes` and the `Discard` button works fine except on the `package.json`. In this example the files had a difference where the last line got removed. (I checked it via the `git diff` command from the command line). When I clicked on the `Stage Changes` and the `Discard` button the error message from the issue title appears via a Message on the top.

**Comment by joshSummerhays** [comment] 2017-11-09 00:49
on version 1.18.0 as well. sporadic but a lot of files I can't stage changes or view the changes. Git: Cannot read property 'resourceUri' of undefined. +1 to make this high priority

**Comment by davidsielert** [comment] 2017-11-11 17:13
Getting this aswell on 1.18.0, seems hard to reproduce

**Comment by MarcusAhlfors** [comment] 2017-11-14 21:27
Me too for 1.18.0, if I have eg. 10 files to commit there is certainly is at least one of them which fails with this message

**Comment by joekrill** [comment] 2017-11-15 13:57
This has actually gotten seemingly worse for me since my most recent update (1.18.0). Not only am I seeing the resourceUri error, but in some cases I can't even open the file from the source control tab. Right now I have a file in "Changes" and double clicking it does nothing -- it doesn't open it (or the diff), and I don't even get any sort of error. If I try to stage it I still get the "Git: Cannot read property 'resourceUri' of undefined" error message." 

As everyone else is reporting, using the command line works just fine (and the source control tab updates accordingly), so it's not a huge problem for me, just a minor annoyance.

Unfortunately I haven't found a reliable way to reproduce this, but it's happening often enough for me that if anyone has any ideas I'm happy to test them out.

**Comment by joaomoreno** [comment] 2017-11-15 14:06
Guys, if you open the Developer Tools, is there any warning in there?

**Comment by gigouni** [comment] 2017-11-15 14:57
Another possible workaround: pass by your terminal and add manually the file
`git add <your-file>`

VS Code
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T12:44:48.751Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

You'll be able to see the differences through the editor then.

**Comment by Pajn** [comment] 2017-11-15 15:17
>This has actually gotten seemingly worse for me since my most recent update (1.18.0). Not only am I seeing the resourceUri error, but in some cases I can't even open the file from the source control tab. 

Hmm, for me it has always been that way. However the file can still be opened from the file tree.

**Comment by joaomoreno** [comment] 2017-11-15 16:14
Questions for those who hit this:

- Is there any special output in the Developer Tools when this happens?
- Do you have more than a single SCM repository in the SCM view?

**Comment by maxibanki** [comment] 2017-11-15 16:17
In my case only the output (of the first post in this issue) was logged. I haven't used or installed any other SCM provider.

**Comment by joekrill** [comment] 2017-11-16 01:07
I get this in the Developer Tools console when a file won't open:

<img width="792" alt="screen shot 2017-11-15 at 8 05 35 pm" src="https://user-images.githubusercontent.com/393220/32868486-86acb726-ca40-11e7-8ede-c089a26b24db.png">

And to answer your other question @joaomoreno - I only have one SCM repository.

**Comment by simon-r** [comment] 2017-11-16 07:45
The bug is there!
Arch Linux and VSCODE 1.18.0

When I've tried to stage some files only with some apparently random files I've had the problem.

Recently also the git.autorefresh does not work!
Also if I've set in my config git.autorefresh": true .

**Comment by simon-r** [comment] 2017-11-16 07:54
In the developper tools i've found this:

messageService.ts:126 GIT: Cannot read property 'resourceUri' of undefined
e.doShow @ messageService.ts:126

**Comment by hknoerrer** [comment] 2017-11-16 13:43
Also available on OSX 10.12.6 vscode 1.18.0

tried to add a modified file to stage

got two messages:

messageService.ts:126 Git: Cannot read property 'resourceUri' of undefined
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._showMessage @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 Git: Cannot read property 'resourceUri' of undefined
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._showMessage @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560


console.ts:123 [Extension Host] ApplicationInsights:Sender [Object]0: Objectaddress: "40.77.226.250"code: "ECONNREFUSED"errno: "ECONNREFUSED"port: 443syscall: "connect"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()length: 1__proto__: Array(0)concat: function concat()constructor: function Array()copyWithin: function copyWithin()entries: function entries()every: function every()fill: function fill()filter: function filter()find: function find()findIndex: function findIndex()forEach: function forEach()includes: function includes()indexOf: function indexOf()join: function join()keys: function keys()lastIndexOf: function lastIndexOf()length: 0map: function map()pop: function pop()push: function push()reduce: function reduce()reduceRight: function reduceRight()reverse: function reverse()shift: function shift()slice: function slice()some: function some()sort: function sort()splice: function splice()toLocaleString: function toLocaleString()toString: function toString()unshift: function unshift()Symbol(Symbol.iterator): function values()Symbol(Symbol.unscopables): Object__proto__: Object
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:377
(anonymous) @ extensionHost.ts:202
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by ufthelp** [comment] 2017-11-16 17:32
Faced the same issue on below enviornment:- 

- Mac OS - 10.12.6


- VS code - Version 1.15.1 (1.15.1)

Steps:- Made changes to launch.json file but on discarding the changes its showing the error.
[](url)
![vscodeerror](https://user-images.githubusercontent.com/19518528/32906153-f212169e-cab0-11e7-8995-337760c4ed16.jpg)

**Comment by joaomoreno** [comment] 2017-11-17 14:56
OK GUYS! I got it, finally.

![homer](https://media.giphy.com/media/11SNljv9AlnxM4/giphy.gif)

Steps:

1. Have 4 unstaged files: `file1.txt`, `file2.txt`, `file3.txt`, `file4.txt`.
2. In the terminal, type `git add file1.txt file3.txt`
3. Using the UI, stage `file2.txt` then unstage it. Repeat this 5 more times.
4. Try clicking on `file4.txt` or any of its actions.

![spongebob](https://media.giphy.com/media/ODM5MSwVcxl8A/giphy.gif)

Keep reading for a _postmortem_ analysis.

---

Here's where the bug is:

https://github.com/Microsoft/vscode/blob/0a42516de80d3141955114678b5736c5d124f796/src/vs/workbench/api/node/extHostSCM.ts#L265

We're basically dealing with a list of changes, sorted by the occurring index in the original sequence, and applying the same changes into a another list. This, of course, is a problem if the difference between the number of inserted elements is different than the number of deleted elements in that change, since the index positions for the following changes will all be wrong. The usual way to do this is to reverse the list of changes and apply them in that order. We do this in the main thread:

https://github.com/Microsoft/vscode/blob/0a42516de80d3141955114678b5736c5d124f796/src/vs/workbench/api/electron-browser/mainThreadSCM.ts#L179

But we overlooked doing the same when dealing with the `_handlesSnapshot` array.

Combine that with the fact that we only really dispose these guys 10 times after a resource group was effectively modified (that's why step 3 of the repro steps needs to be repeated 5 times), this bug proved to be a very elusive one.

--- 

I'll fix the order of handling these splices. I'll also remove the 10 generations before disposing... we can deal with that in some other way.

**Closed** 2017-11-17 15:30 UTC
Labels: bug, git

**Comment by MattGoldwater** [comment] 2017-11-22 20:40
Should the error be gone in the most recently shipped version? (I'm not using the insiders build) I just got this error now.

**Comment by joaomoreno** [comment] 2017-11-23 08:22
`git tag --contains 9752f3c` returns empty... so: no. This fix is already out in Insiders but will come in the next Stable (1.19.0).

**Comment by gillez** [comment] 2017-11-30 14:34
Any idea when Stable v1.19.0 will be released?  I'm seeing this error often and it's beginning to get annoying. :)

**Comment by maxibanki** [comment] 2017-11-30 14:41
Should be released in the next week or two, according to my experience.

**Comment by joaomoreno** [comment] 2017-11-30 16:26
https://github.com/Microsoft/vscode/issues/38268

**Comment by rokkitpress** [comment] 2017-12-10 20:04
I have just had this happen when staging multiple files, I followed some advice seen above, changed folder, came back to project and all is well.
