### ISSUE TITLE
Native Interactive - Order cell history by most recent execution

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#131933] opened 2021-08-30 16:23 UTC
When navigating through the interactive cell history from the code entry cell, using the up arrow, the new IW currently stores cell history by the order the cell was FIRST executed.

In the image below, I've executed cell `a`, then `b`, then arrowed up and executed `a` again.

When I arrow up one more time, `b` is still the first cell in the history, because it is the most recent "new" cell.

I would really prefer `a` to be the first cell in the history, as it was most recently executed (and this was the behavior in the webview IW).

For example, sometimes I'll be working with a cell that was first executed many cells ago, so I'll have to arrow up a lot, and spend a lot of time searching for it again, rather than knowing it will be the most recent in the queue.

Not sure if this was an intentional change, but at the least would be great to have the original functionality back with a setting. Thanks!!

<img width="816" alt="jupyter_cell_history" src="https://user-images.githubusercontent.com/29611875/131370854-abd46e9a-742e-41fc-a3f5-e69f73c7609f.png">

**Comment by greazer** [comment] 2021-08-30 20:34
The expected behavior is as the user asks. Joyce indicated that the bug here is that if the user executed a history item a second time, it is not added to the history. It should be.

**Comment by joyceerhl** [comment] 2021-08-31 01:24
Duplicate of https://github.com/microsoft/vscode/issues/131659

**Closed by joyceerhl** 2021-08-31 01:24 UTC
Labels: bug, regression, interactive-window
