### ISSUE TITLE
Error while debugging node.js on windows

### ISSUE THREAD

**Issue by gleborgne** [microsoft/vscode#103400] opened 2020-07-27 08:54 UTC
- VSCode Version: 1.47.2
- OS Version: Windows 10 (update 2004)

Steps to Reproduce:

1. Start node.js debugging on a project with Typescript

Does this issue occur when all extensions are disabled?: Yes

Since last vscode version update, when starting to debug I have the error bellow. tslib is at version 2.0.0. I tried downgrading it to 1.X but still have the same error. I saw other bugs that looks related and if I add "debug.javascript.usePreview": false to vscode's settings, everything is working fine.

TypeError: 
    at c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:16:7581
    at Object.<anonymous> (c:\Users\X\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js:16:7609)
    at Object.__decorate (c:\projects\ABCD\master\front\node_modules\tslib\tslib.js:95:96)

**Comment by bdunn313** [comment] 2020-07-27 17:53
I can confirm the exact same behavior, and setting the `"debug.javascript.usePreview": false` does prevent the issue from happening.

I observe that there _may_ be a memory leak in the preview implementation - when starting the debugger, vscode rapidly grows from ~700mb memory to as much as it can grab (I've seen north of 5GB mem taken up).

VSCode Version: 1.47.2
OS Version: Windows 10 v2004 Build 19041.388

**Comment by connor4312** [comment] 2020-07-30 17:48
Thanks for the info. I haven't seen this before -- are you able to collect a trace log using these instructions, or provide a small sample repo?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by prbans** [comment] 2020-08-04 21:17
@connor4312 pinged you offline, I can show you repro and share logs in private

**Comment by connor4312** [comment] 2020-08-10 20:43
Closing due to lack of info

**Closed by connor4312** 2020-08-10 20:43 UTC
Labels: debug, needs more info
