### ISSUE TITLE
Up/down keys no longer respect "filtering" for files in Folders pane (file explorer)

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#117091] opened 2021-02-19 21:10 UTC
- VS Code Version: 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4)
- OS Version: Big Sur 11.2.1 (20D75)

Steps to Reproduce:

1. Focus on the Folders pane
2. Start typing a file's name (the "query")
3. You should see something like this, which I don't know the name of: 
![image](https://user-images.githubusercontent.com/927310/108561533-176e4500-7307-11eb-81c4-d1ac79162992.png)
4. Hit Up or Down keys

Expected Behavior:

Hitting Up/Down should "skip" to the next file that matches the query

Actual Result:

Hitting Up/Down behaves as if no query was written, focusing on the immediate previous/next files.

See:

![Screen Recording 2021-02-19 at 23 08 50](https://user-images.githubusercontent.com/927310/108561906-ae3b0180-7307-11eb-9ab6-a0028da505eb.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment] 2021-02-19 22:59
/duplicate of #115922 and fixed in Insiders, so will arrive in the next Stable (1.54)

**Closed** 2021-02-19 23:00 UTC
Labels: *duplicate

**Comment by zhouyanan617** [comment] 2021-02-25 03:29
I am find this problem too, Is the vscode version caused ? How solve it ? Help!

**Comment by gjsjohnmurray** [comment] 2021-02-25 07:06
Either use Insiders (which you can install alongside Stable) or wait another week until 1.54 reaches Stable.

**Comment by zhouyanan617** [comment] 2021-02-25 07:19
> Either use Insiders (which you can install alongside Stable) or wait another week until 1.54 reaches Stable.

Ok, Thank You!
