### ISSUE TITLE
Nested git repo detection for symlinked repo

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#173766] opened 2023-02-08 07:45 UTC
A few months ago we got a new feature for detecting nested git repos: [feature](https://github.com/microsoft/vscode/issues/37947), [PR](https://github.com/microsoft/vscode/pull/159291).

But it doesn't handle the use case where the repo is in a symlinked directory. We have a number of common repos used in many monorepos, and they're referenced as symlinks:
````
MyMonoRepo/
  .git/
  lib/
    NormalNestedRepo/                  <--- detected
      .git/
    SymlinkedNestedRepo/               <--- not detected
      .git/
  src/
````

The symlinked repo is not detected.

(Unless this is already supported somehow @lszomoru @nteymory ?)

**Comment by lszomoru** [comment] 2024-12-10 15:19
@lonix1, are you still able to reproduce this issue? Since the issue was last updated we have made more improvements in this area. I will go ahead and optimistically close this issue but in case you are still able to reproduce this, please feel free to reopen it. Thanks!

**Closed by lszomoru** 2024-12-10 15:19 UTC
Labels: feature-request, git
