### ISSUE TITLE
TS Server crashes for untitled files

### ISSUE THREAD

**Issue by jhony1104** [microsoft/vscode#85547] opened 2019-11-25 14:50 UTC
Creating a new `javascript` or `typescript` file results in the following error:

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

[tsserver.log](https://gist.github.com/jhony1104/13ceed66e8f2a1ecbdce7d4666e0f6e7)

Setup:
- VSCode Version: 1.40.1
- OS Version: Linux x64 4.19.0-6-amd64 (Debian 10)

Steps to Reproduce:

1. Create a new file
2. Switch language to `javascript` or `typescript`

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur when using the latest insider build?: Yes

Possible duplicate of #84826, but in my case the TypeScript language service works for regular files.

**Comment by jhony1104** [comment] 2019-11-25 14:55
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [TypeScript and JavaScript Language Features crashes extension host (#84842)](https://www.github.com/microsoft/vscode/issues/84842)
> * [TS Language server dies when using TS 3.7.2 on unsaved file in Code 1.40.0 (#84171)](https://www.github.com/microsoft/vscode/issues/84171)

It might be as special case of #84171

**Comment by mjbvz** [comment] 2019-11-25 19:33
Are you sure this repos in the insiders build when using TypeScript 3.7.3-insiders?

**Comment by jhony1104** [comment] 2019-11-26 09:05
The issue does not occure in insiders build, after manually running `npm i typescript@3.7.3-insiders.20191123`.

**Comment by jhony1104** [comment] 2019-12-18 13:50
After Updating to __VSCode 1.41.1__ with __TypeScript 3.7.3__ this issue still occurs.

**Comment by mjbvz** [comment] 2019-12-20 02:05
@jhony1104 Can you please share another copy of the server logs while using VS Code 1.41 and TypeScript 3.7.3+

**Comment by jhony1104** [comment] 2019-12-22 19:40
After updating to VS Code 1.41.1 this issue seemns resolved

**Comment by jhony1104** [comment] 2020-01-31 15:48
Sorry for reopening this again, but the problem occured again.

Here the new [tsserver.log](https://gist.github.com/jhony1104/06b4f22aff2767bc5056fe982a57697c)

**Comment by mjbvz** [comment] 2020-01-31 19:36
Thanks for the log. From the log file, this looks like a duplicate of https://github.com/microsoft/TypeScript/issues/36200

To workaround this, try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2020-01-31 19:36 UTC
Labels: javascript, needs more info, typescript
