### ISSUE TITLE
Selectors autocomplete feature in CSS files

### ISSUE THREAD

**Issue by Lartwel** [Microsoft/vscode#53223] opened 2018-06-28 08:54 UTC
Issue Type: <b>Feature Request</b>

I'd like to autocomplete selectors while writing in CSS files. I don't know if there's an extension with a similar feature or not.

I've tried the 'IntelliSense for CSS class names in HTML'  and it makes the opposite as it caches the used selectors in the CSS file to be written in the HTML file, but I want to cache the used selectors in the HTML files and use them in CSS files.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by aeschli** [comment] 2018-06-28 09:11
duplicate of #28442

**Closed by aeschli** 2018-06-28 09:11 UTC
Labels: html
