### ISSUE TITLE
CodeAlpha can't be started from command prompt

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2177] opened 2016-01-22 09:55 UTC
- Install Code Alpha only. 
- Check add code to path.
- in command type code or codeAlpha 

Observe: both fail.

code.cmd refers to Code.exe, however in Alpha channel code is named CodeAlpha.

**Comment by egamma** [comment] 2016-01-25 08:28
Duplicate of #2127

**Closed by egamma** 2016-01-25 08:28 UTC
Labels: bug

**Comment by dbaeumer** [comment] 2016-01-29 11:00
Verified.
