### ISSUE TITLE
snippet doesn't work when I satrt VSCode

### ISSUE THREAD

**Issue by wenkeming** [Microsoft/vscode#34339] opened 2017-09-14 02:07 UTC
- VSCode Version: 1.16.0
- OS Version: Windows 10

I'm using Vue. I have defined a SCSS snippet. It just doesn't work when I start the VSCode. It must be saved the snippet again before it works.
我用的是vue，并且定义了个scss的代码片段，但是每次启动的时候不起作用，必须再次保存一下代码片段才生效。

![gaollg0](https://user-images.githubusercontent.com/8252267/30409004-e6e4e72c-9934-11e7-80da-3edb300639b0.GIF)

**Comment by jrieken** [comment] 2017-09-14 07:42
duplicate of #33811

**Closed by jrieken** 2017-09-14 07:42 UTC
Labels: new release
