### ISSUE TITLE
Resize area overlaps window contents when using custom title bar style on Windows

### ISSUE THREAD

**Issue by aqst** [microsoft/vscode#157197] opened 2022-08-05 02:46 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0 (user setup)
- OS Version: Windows 11 (Windows_NT x64 10.0.22621)

When the window is not in fullscreen mode and the Window: Title Bar Style setting is set to "custom", it causes the resize area of the window to slightly overlap with the contents of the window. This does not happen when it is set to "native". It's a small issue but I sometimes scroll through files by clicking on or dragging the scrollbar and it causes me to accidentally resize the window every so often. I used the Steps Recorder to get the following screenshots.

Title Bar Style set to "custom":
![Title Bar Style set to "custom"](https://user-images.githubusercontent.com/17473579/182989590-d32a968e-8b14-4188-a5b0-0e7fff99e223.png)

Title Bar Style set to "native" (expected behaviour):
![Title Bar Style set to "native"](https://user-images.githubusercontent.com/17473579/182989578-36c9f77a-bff2-49b5-9b00-3e1c00daa215.png)

**Comment by rzhao271** [comment] 2022-12-08 23:59
Duplicate of https://github.com/microsoft/vscode/issues/102023

**Closed by rzhao271** 2022-12-08 23:59 UTC
Labels: bug, upstream, electron, confirmation-pending, windows 11
