### ISSUE TITLE
PLEASE add filter to context-menu

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#105120] opened 2020-08-21 02:03 UTC
VSCode is too open to user and developer to Customize User Interface .
but It will be a disaster if there is no limit and feasible specification..
like #104738
and also. the context-menu is also a "phenomenon" as same as to  action-icon
![image](https://user-images.githubusercontent.com/1876302/90844011-81785280-e395-11ea-9233-d43386a067c7.png)

extension add to much menu items to context-menu which is Weak relationship with current context beacuse of the vscode and vsocde's none-project-concept.
as the picture, i think the temporary solution is add  a filter to context-menu for faster positioning in so many items.
just like 
![image](https://user-images.githubusercontent.com/1876302/90843969-63aaed80-e395-11ea-81e6-bf6cf2b346b3.png)

**Comment by isidorn** [comment] 2020-08-21 08:13
We will make custom menus configurable. Closing as duplicate of that.
In the meantime uninstall some of those extensinos

**Closed by isidorn** 2020-08-21 08:13 UTC
