### ISSUE TITLE
Error "Cannot read property 'dispose' of null" when trying to close window with "Find all References" results

### ISSUE THREAD

**Issue by Jusys** [Microsoft/vscode#46346] opened 2018-03-22 13:55 UTC
- VSCode Version: 1.21.1
- OS Version: Windows 7 32bit

Steps to Reproduce:

1. Do SHIFT+F12 to find all references of some item in your project's files
2. Small window with search results appears
3. Begin to change found references in before-mentioned small window
4. Change in a couple of files, save them with [ctrl+s]
5. Try to close small window with search results using [x]
6. Window does not close and error "Cannot read property 'dispose' of null" pops out

![6](https://user-images.githubusercontent.com/30110941/37774466-f5496ac4-2de8-11e8-8e13-4c273754d6e8.jpg)
(Sorry for pixelization)

Does this issue occur when all extensions are disabled?: I have no extensions installed

**Comment by roblourens** [comment] 2018-03-22 16:28
Can you open the devtools console (Help > Toggle Developer Tools) and look for more details of the error?

Does this happen consistently?

**Comment by CCludts** [comment] 2018-03-22 18:19
I'm experiencing have the exact same issue.
steps to reproduce:
* SHIFT+F12 a symbol
* rename something in the small editor
* press escape

(language version C#)

![image](https://user-images.githubusercontent.com/18717967/37790039-bee45a94-2e05-11e8-9818-bee149d45258.png)

**Comment by Jusys** [comment] 2018-03-23 12:14
Does this happen consistently? > no it does not.

**Comment by T-Grave** [comment] 2018-03-27 10:46
I've ran into a possibly related error.

When I want to peek / goto implementation, Visual Studio Code pops up an error: `Cannot read property 'getStartPosition' of null` and the action does not happen :(

Looking at the console logs, the error reported above is printed out as well:

```
Cannot read property 'dispose' of null: TypeError: Cannot read property 'dispose' of null
    at e.dispose (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1986:754)
    at Object.i [as dispose] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:65:330)
    at e.dispose (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1988:330)
    at t.dispose (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1284:601)
    at t.dispose (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1770:323)
    at i (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:65:330)
    at Object.i [as dispose] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:65:311)
    at c.dispose (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2085:54)
    at e.closeWidget (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2097:371)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2096:94
```

I have no idea yet on how to reproduce this since I have been having this issue since a couple of days and have not yet been able to get rid of it.

**Comment by jrieken** [comment] 2018-03-28 14:16
@T-Grave @CCludts Can you guys open dev tools before this happens, enable  'break on all errors', and attach a screen shot when it breaks there? 

<img width="225" alt="screen shot 2018-03-28 at 16 15 46" src="https://user-images.githubusercontent.com/1794099/38034779-4c224366-32a3-11e8-9df3-759046caebdf.png">

**Comment by CCludts** [comment] 2018-03-28 14:46
I cant seem to find that button in my devtools? (forgive me, I'm not a javascript dev :) )
![image](https://user-images.githubusercontent.com/18717967/38036692-8def6806-32a7-11e8-8e6b-a061d55075e1.png)

**Comment by jrieken** [comment] 2018-03-28 15:15
Click on the Sources tab (and be patient because the tab is quite overwhelmed on first start)

**Comment by CCludts** [comment] 2018-03-29 18:48
Sorry for the late response. Didnt run into the issue until today.
![image](https://user-images.githubusercontent.com/18717967/38107468-57de5402-3392-11e8-8e1f-744c297a90ba.png)
![image](https://user-images.githubusercontent.com/18717967/38107507-72b3558e-3392-11e8-9a3c-2df241c15909.png)

**Comment by CCludts** [comment] 2018-03-29 19:50
Better breakpoint (i think?). It happens every single time when intellisense provides a suggestion inside the shift-12 editor.
![image](https://user-images.githubusercontent.com/18717967/38110187-17a4d448-339b-11e8-95f4-92789d947aa7.png)

**Comment by huglovefan** [comment] 2018-03-30 14:46
i also get this error using vscode 1.21.1 (commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1) with all default settings and no extensions

1. open this as a .js file:
   ```javascript
   function test () {
   }
   test();
   ```
2. find all references of `test`
3. in the references window:
   1. hover `test` in `test();` to see the tooltip (doesn't reproduce otherwise)
   2. manually replace `test();` with `a();`
4. try to close the references window

there are actually two similar errors that you'll get:

- on the first close, you get this error ("Cannot read property 'dispose' of undefined"):
  ![screenshot_2018-03-30_17-25-28](https://user-images.githubusercontent.com/37460772/38141173-9a698c44-343f-11e8-924b-6759ea56f3cf.png)

- on the second and subsequent tries, you get this ("Cannot read property 'dispose' of null"):
  ![screenshot_2018-03-30_17-26-07](https://user-images.githubusercontent.com/37460772/38141180-a5062c0c-343f-11e8-822f-60e4441424ba.png)

**Comment by jrieken** [comment] 2018-04-03 07:18
cc @ramya-rao-a for the errors in the suggest widget

**Comment by jrieken** [comment] 2018-04-03 07:36
The parameter hints widget has been fixed via https://github.com/Microsoft/vscode/issues/45182

**Comment by ramya-rao-a** [comment] 2018-04-04 00:55
I can repro the issue with the suggest widget only in Stable 1.21.1 but not in Insiders.

**Closed by ramya-rao-a** 2018-04-04 00:55 UTC
Labels: needs more info
