### ISSUE TITLE
Does not display row with too large string

### ISSUE THREAD

**Issue by thekaduu** [Microsoft/vscode#39107] opened 2017-11-24 17:37 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
git-easy|bib|1.9.1
githistory|don|0.2.3
phpunit|ema|2.1.1
prettier-vscode|esb|0.26.0
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
sublime-keybindings|ms-|3.0.3
php-docblocker|nei|1.3.2
laravel5-snippets|one|1.3.4
annotator|ryu|0.10.1
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---
I'm editing a CSS file that has a **background-image** as a base64 image but the editor can not display the entire String (either on the horizontal bar or using the **END** or the arrows.

Steps to Reproduce:

1. Download the attached file ([example.txt](https://github.com/Microsoft/vscode/files/1502275/example.txt)).
2. Rename the file **example.txt** to **example.css**
3. Open the file (example.txt) with the editor (visual studio code)

Open the file (example.css) with the editor (visual studio code)

Reproduces without extensions: No

**Comment by alexandrudima** [comment] 2017-11-27 14:32
Duplicate of #7772

**Closed by alexandrudima** 2017-11-27 14:32 UTC
Labels: bug, editor-rendering
