### ISSUE TITLE
Multi root launches do not switch working directory to correct root dir

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#42479] opened 2018-01-30 14:13 UTC
testing #42036:

- two folder workspace with this launch config in each folder "f1" and "f2":
  ```
		{
			"type": "node",
			"request": "launch",
			"name": "Launch f1",
			"program": "${workspaceFolder}/app.js"
		}
  ```
- compound launch config in workspace settings:
   ```
		{
			"name": "Compound",
			"configurations": ["Launch f1","Launch f2"]
		}
   ```

Launch the "Compound" launch config results in this output:

![2018-01-30_15-00-02](https://user-images.githubusercontent.com/1898161/35570063-5726e052-05ce-11e8-9734-110f6b6d2796.png)

Problem: both programs are launched from the same folder "f1".

We might want to consider to change the working directory for every launched program to the corresponding folder.

@dbaeumer are you doing this for tasks?

**Comment by weinand** [comment] 2018-01-30 14:19
@dbaeumer confirmed that in task land the correct root folder dir is passed to forked/spawed processes. We should do the same when launching debug adapters.

**Comment by isidorn** [comment] 2018-01-31 14:28
Works fine in latest out of source. Bascially a duplicate of https://github.com/Microsoft/vscode/issues/42495

**Closed by isidorn** 2018-01-31 14:28 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2018-02-01 11:33
Now this works as expected:
![2018-02-01_12-32-54](https://user-images.githubusercontent.com/1898161/35676434-0ef6dfe2-074c-11e8-9ae6-c3cc16a51a9f.png)
