### ISSUE TITLE
I can't see underscore(_) in terminal

### ISSUE THREAD

**Issue by daniel12fsp** [Microsoft/vscode#37420] opened 2017-11-01 15:29 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T05:23:12.753Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.1
gitlens|eam|5.7.1
flow-for-vscode|flo|0.7.2

---

Steps to Reproduce:

1. Open integrated terminal
2. Type _ 

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-01 16:14
Duplicate of #35901

**Closed** 2017-11-01 19:30 UTC
Labels: insiders, integrated-terminal
