### ISSUE TITLE
Replacing more than 999+ occurences does not work?

### ISSUE THREAD

**Issue by pydevil** [Microsoft/vscode#33989] opened 2017-09-08 04:04 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
elm-format|aba|0.1.0
vscode-eslint|dba|1.2.11
python|don|0.7.0
terminal|for|0.0.10
elm|sbr|0.15.0

---

Steps to Reproduce:

1.Having file like this
```
13
00:03:39,761 --> 00:03:42,179
You don't think he'll ask us how they died?
14
00:03:44,433 --> 00:03:46,225
Get back on your horse.
15
00:03:50,939 --> 00:03:53,441
Whatever did it to them
could do it to us.
16
00:03:53,567 --> 00:03:55,151
They even killed the children.
17
00:03:56,111 --> 00:03:58,112
It's a good thing we're not children.
```
2. CTRL+H with regex
`^[\d:,> -]*$`
3. Got
`1of 999+`
4.Replace all with nothing
5.Does not work

Reproduces without extensions: Yes/No

**Comment by ToMakeSense** [comment] 2017-09-11 02:47
Releated to [#32522](https://github.com/Microsoft/vscode/issues/32522)

**Comment by alexandrudima** [comment] 2017-09-28 10:48
Duplicate of #32522 i.e. 54ca5101065a7cdb73049755e0393e7b2b31477f also fixes this.

**Closed by alexandrudima** 2017-09-28 10:48 UTC
Labels: editor-1000-limit
