### ISSUE TITLE
Azure Resource Manager (ARM) JSON Template is not validating :: Invalid Resource Type specified

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#886] opened 2015-12-01 22:25 UTC
I've filed a new feedback item on the Azure Resource Manager (ARM) JSON Schema project page, although I believe this might have to do with how Visual Studio Code handles JSON schema validation.

https://github.com/Azure/azure-resource-manager-schemas/issues/68

I'm being told that `Microsoft.Storage/storageAccounts` isn't a valid top-level ARM Resource Type.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by aeschli** [comment] 2015-12-02 12:05
Do you happen to have the sample from the screenshot in hand, so I don't need to type that much? Thanks :-)

**Comment by aeschli** [comment] 2015-12-02 14:38
![image](https://cloud.githubusercontent.com/assets/6461412/11533565/b670b30e-990a-11e5-8f35-42c6b7aa6cd4.png)

**Comment by aeschli** [comment] 2015-12-02 14:39
duplicate of #881

**Closed by aeschli** 2015-12-02 14:39 UTC
Labels: bug
