### ISSUE TITLE
vscode shutdown

### ISSUE THREAD

**Issue by webFunc** [Microsoft/vscode#36407] opened 2017-10-17 10:03 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-express|Com|0.0.5
vscode-eslint|dba|1.3.2
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.2.1
php-debug|fel|1.11.1
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
code-runner|for|0.7.3
search-node-modules|jas|1.2.0
copy-markdown-as-html|jer|1.0.0
docthis|joe|0.5.0
node-module-intellisense|lei|1.4.0
color-highlight|nau|2.3.0
php-docblocker|nei|1.3.2
vetur|oct|0.9.11
vscode-icons|rob|7.15.0
vscode-gulp|tan|0.0.4
expresssnippet|vla|0.1.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.11.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-17 17:32
Please describe what the issue is

**Comment by mjbvz** [comment] 2017-10-24 18:19
Closing as not actionable without additional information

**Closed by mjbvz** 2017-10-24 18:19 UTC
Labels: needs more info
