### ISSUE TITLE
The new logo is so ugly

### ISSUE THREAD

**Issue by whitefirer** [Microsoft/vscode#35819] opened 2017-10-08 07:53 UTC
The new logo is so ugly, could you use the old logo?

**Comment by Kenya-West** [comment] 2017-10-08 10:12
#35783

**Comment by Mlocik97-issues** [comment] 2017-10-08 10:14
Dupl #35683

**Comment by mjbvz** [comment] 2017-10-08 13:40
Duplicate of #35783

**Closed by mjbvz** 2017-10-08 13:40 UTC

**Comment by miladghiravani** [comment] 2017-11-09 15:54
Hi, Thanks a lot for change icon. But new icon need some stroke line.
![image](https://user-images.githubusercontent.com/5067331/32614410-6e7f7d54-c582-11e7-86c2-831a570f8217.png)

Like this:
![image](https://user-images.githubusercontent.com/5067331/32614855-67a34d84-c583-11e7-86f9-071e13515775.png)
