### ISSUE TITLE
Cursor blinking remained a little dot

### ISSUE THREAD

**Issue by wngtk** [microsoft/vscode#143665] opened 2022-02-23 07:57 UTC
Issue Type: <b>Bug</b>

I typed some text in VScode. Waiting that cursor blinking. Then the cursor remained a little dot at top of it.

https://user-images.githubusercontent.com/100271394/155282626-30c55655-513d-462f-aa7a-1f1b85478149.mp4

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3187)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (9.40GB free)|
|Process Argv|--crash-reporter-id aa882517-7579-4b47-9eb7-4cb2bdd95ea9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30442553
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc008:30440022
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by alexdima** [comment] 2022-02-23 14:23
Duplicate of https://github.com/microsoft/vscode/issues/142291

**Closed by alexdima** 2022-02-23 14:23 UTC
