### ISSUE TITLE
JavaScript/TypeScript autocomplete of parentheses for arrow functions

### ISSUE THREAD

**Issue by Si1adan** [microsoft/vscode#171180] opened 2023-01-12 16:58 UTC
I already use ```javascript.suggest.completeFunctionCalls```, but it works only for regular functions.
```
function foo () {
}

const bar = () => {
}

foo();  // autocompleted ()

bar
```

**Comment by mjbvz** [comment] 2023-01-12 18:37
Duplicate of #136414

**Closed by mjbvz** 2023-01-12 18:37 UTC
