### ISSUE TITLE
Publish Branch without prior auth ends up spinning forever

### ISSUE THREAD

**Issue by digitaraldd** [microsoft/vscode#169347] opened 2022-12-16 00:31 UTC
Type: <b>Bug</b>

- Blank Windows 10 laptop. Installed VS Code from website, then git via winget 
- Checked out vscode repo via https URL
- Created a branch, hit Publish Branch
- Endless loading indicator

```
2022-12-15 16:13:43.353 [info] Log level: Info
2022-12-15 16:13:43.354 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:13:43.354 [info] Validating found git in: "C:\Program Files (x86)\Git\cmd\git.exe"
2022-12-15 16:13:43.354 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:13:43.354 [info] Validating found git in: "C:\Users\haral\AppData\Local\Programs\Git\cmd\git.exe"
2022-12-15 16:13:43.392 [warning] Git installation not found.
2022-12-15 16:16:18.019 [info] Log level: Info
2022-12-15 16:16:18.019 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:16:18.030 [info] Using git "2.39.0.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:21:10.626 [info] > git clone https://github.com/microsoft/vscode.git c:\Users\haral\Downloads\vscode --progress [107602ms]
2022-12-15 16:21:10.626 [info] Cloning into 'c:\Users\haral\Downloads\vscode'...
...
2022-12-15 16:21:18.275 [info] Log level: Info
2022-12-15 16:21:18.275 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:21:18.335 [info] Using git "2.39.0.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2022-12-15 16:21:18.397 [info] > git rev-parse --show-toplevel [56ms]
2022-12-15 16:21:18.455 [info] > git rev-parse --git-dir --git-common-dir [53ms]
2022-12-15 16:21:18.468 [info] Open repository: c:\Users\haral\Downloads\vscode
2022-12-15 16:21:18.549 [info] > git rev-parse --show-toplevel [75ms]
2022-12-15 16:21:18.554 [info] > git config --get commit.template [74ms]
2022-12-15 16:21:18.567 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [73ms]
2022-12-15 16:21:18.614 [info] > git rev-parse --show-toplevel [61ms]
2022-12-15 16:21:18.686 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [103ms]
2022-12-15 16:21:18.692 [info] > git rev-parse --show-toplevel [70ms]
2022-12-15 16:21:18.744 [info] > git rev-parse --show-toplevel [49ms]
2022-12-15 16:21:18.798 [info] > git rev-parse --show-toplevel [51ms]
2022-12-15 16:21:18.849 [info] > git rev-parse --show-toplevel [48ms]
2022-12-15 16:21:18.905 [info] > git rev-parse --show-toplevel [52ms]
2022-12-15 16:21:18.951 [info] > git status -z -uall [379ms]
2022-12-15 16:21:18.965 [info] > git rev-parse --show-toplevel [57ms]
2022-12-15 16:21:19.026 [info] > git config --get commit.template [61ms]
2022-12-15 16:21:19.033 [info] > git rev-parse --show-toplevel [65ms]
2022-12-15 16:21:19.043 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [69ms]
2022-12-15 16:21:19.075 [info] > git check-ignore -v -z --stdin [74ms]
2022-12-15 16:21:19.102 [info] > git rev-parse --show-toplevel [65ms]
2022-12-15 16:21:19.158 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [106ms]
2022-12-15 16:21:19.179 [info] > git rev-parse --show-toplevel [71ms]
2022-12-15 16:21:19.231 [info] > git rev-parse --show-toplevel [49ms]
2022-12-15 16:21:19.388 [info] > git status -z -uall [341ms]
2022-12-15 16:21:38.728 [info] > git checkout -q -b independent-ox --no-track HEAD [367ms]
2022-12-15 16:21:38.796 [info] > git config --get commit.template [63ms]
2022-12-15 16:21:38.804 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/independent-ox refs/remotes/independent-ox [64ms]
2022-12-15 16:21:38.915 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [98ms]
2022-12-15 16:21:38.924 [info] > git status -z -uall [116ms]

```

VS Code version: Code - Insiders 1.75.0-insider (44531ffc7b7477dbe82750040d8ed69bae2bb140, 2022-12-15T08:33:44.005Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.72GB free)|
|Process Argv|--crash-reporter-id 3adeb0c6-b0f1-4dc0-b854-0141c0cd4f7e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by digitarald** [comment] 2022-12-16 01:33
Reproduced on Windows 11

**Comment by lszomoru** [comment] 2022-12-21 13:22
@digitarald, do you still have a repro of this? Could it be due to the auth handler configured on the machine?

**Comment by digitarald** [comment] 2022-12-26 06:09
This is a fresh Windows 11 install with winget git install, so nothing else got specifically set up. gcm does seem to handle auth though when using git CLI from VS Code's terminal (see https://github.com/microsoft/vscode/issues/169349).

**Comment by lszomoru** [comment] 2022-12-30 05:20
Given that GCM is handling the auth, I am not sure what we can do here. Can we close this issue?

**Comment by digitarald** [comment] 2023-01-04 05:32
Could we detect when GCM blocks the command to at least bail out of the infinity loop?

**Comment by lszomoru** [comment] 2023-01-04 08:35
Not as far as I am aware.

**Comment by lszomoru** [comment] 2023-01-04 08:40
> Blank Windows 10 laptop. Installed VS Code from website, then git via winget

Do you have the exact command that you have used to install git using winget? Have you installed "Microsoft.Git" or "Git.Git"? I am asking as "Microsoft.Git" is the Microsoft fork of Git, which "Git.Git" is Git for Windows which is what I expect most people will be using.

**Comment by digitarald** [comment] 2023-01-10 05:49
@lszomoru I used the official line from git-scm.com: `winget install --id Git.Git -e --source winget`. I could try with `Microsoft.Git` as well.

**Comment by lszomoru** [comment] 2023-01-10 06:50
No need, as `Git.Git` is what I expect most people would use. Let's try to sync this week to further look at options.

**Comment by manintech** [comment] 2023-05-27 23:27
Reproduced on macOS Ventura ver. 13.4:

VS Code Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (2 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
Sandboxed: Yes

**Comment by manintech** [comment] 2023-05-27 23:53
This the issue:

 git push                                                                                              ─╯
fatal: The current branch ak/team_page has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin ak/team_page

**Comment by manintech** [comment] 2023-05-29 22:13
### Solution:
Had to set up git auth to GitHub through console

**Closed** 2023-12-12 10:04 UTC
Labels: bug, git
