### ISSUE TITLE
Visually differentiate between Nested items and folders

### ISSUE THREAD

**Issue by scottdrichards** [microsoft/vscode#148951] opened 2022-05-06 19:29 UTC
The [Explorer file nesting ](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting) feature is pretty neat! Already however I have found myself feeling some cognitive dissonance between files that are acting like folders. It would be great if there were a way to differentiate between the two.

**Comment by gjsjohnmurray** [comment] 2022-05-06 21:09
#148925 is related.

**Comment by JacksonKearl** [comment] 2022-05-09 17:09
I'm not sure what you mean... icons and arrows should differentiate. For example:
![Uploading image.png…]()

**Comment by scottdrichards** [comment] 2022-05-13 13:49
While icons can definitely help, perhaps my brain is trained to look at the arrows and indentation only to determine if an item is a folder or file and it just will take a little to get used to it.

As a pedantic example, something like this might cause confusion if only relying on iconography and text:
![image](https://user-images.githubusercontent.com/28912482/168297625-455ab903-bddb-4862-b7ca-45d76d03b03b.png)

I think having a different flavor of arrow would be useful. For example, the color might be different. I'm not saying that it is impossible to differentiate, I'm just saying it requires a little extra mental effort that might be alleviated with some extra visual clues.

**Comment by lramos15** [comment] 2022-05-25 17:37
Closing as duplicate of #148925. While they are slightly different they both aim to solve the same problem.

**Closed by lramos15** 2022-05-25 17:37 UTC
Labels: needs more info, file-explorer
