### ISSUE TITLE
VSCode freezes/crashes Windows 10 1809

### ISSUE THREAD

**Issue by wilk-polarny** [microsoft/vscode#78138] opened 2019-07-30 02:14 UTC
Hi, we are experiencing weird behaviour with VSCode and Win10 at the office.
My co-worker and I both have the same machines with Windows 10 1809 installed and noticed that VSCode will eventually soft freeze the whole operating system.

Once the system is frozen (by reproducing using the steps), all windows except for Google chrome and chromium based applications (Google Chrome, Slack, VSCode) are visually responsive, but nothing else happens when interacting with the operating system or UI elements - just as if someone pulled the plug from the SSD/HDD. For example: Launching a shell and trying to ping results in the cmd window freezing.

We will have to hard reboot our machines TWICE - rebooting once does not work, as Windows 10 will stay on the grey loading screen (with the spinner) forever - or even randomly lock out the drive and ask for a bitlocker recovery key (but not after the second (!) reboot).

This issue may be related to #49425 , but should be fixed by now with Windows 10 1809 ?!
WIN+CTRL+SHIFT+B doesn't help here :)

- VSCode Version: 1.36.1
- OS Version: Windows 10 Enterprise 1809

Steps to Reproduce:

1. Open Google Chrome
2. Open VSCode
3. Either close VSCode or open multiple instances (workspaces) and switch between them.

Does this issue occur when all extensions are disabled?: Yes

**Comment by wilk-polarny** [comment] 2019-07-31 19:28
Ok, others within the office are able to reproduce it too on their machines. May have something to do with the updates installed some time ago. `KB4507469` is one of the prime suspects

**Comment by bpasero** [comment] 2019-08-05 12:49
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by wilk-polarny** [comment] 2019-08-08 12:24
@bpasero 
We have downloaded and installed the insider version. It is even worse, as it will freeze the operating system when opening a workspace and show the following message (no screenshots possible using the snipping tool due to failure to save - thus here is a photo):

![image](https://user-images.githubusercontent.com/819238/62702827-19eca080-b9e8-11e9-8770-2be406535d9d.png)

**Comment by bpasero** [comment] 2019-08-08 12:29
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

**Comment by wilk-polarny** [comment] 2019-08-08 14:22
@bpasero 

started using:
`"C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --disable-gpu`

VSCode starts, but has the same behaviour (freezing system) once being closed

**Comment by wilk-polarny** [comment] 2019-08-12 19:55
@bpasero 
Is there anything we can do?

Due to your suggestion to disable GPU accelerated rendering we have upgraded our graphics drivers to the latest version offered by the vendor (July 2019):

```Versions  25.21.14.2545  (NVIDIA Graphics Driver)
            1.3.38.13      (NVIDIA HD Audio Driver)
            26.20.100.6913 (Intel Graphics Driver)```

The machines in question have either NVIDIA Quadro M2000M or NVIDIA Quadro M1000M together with Intel(R) HD Graphics 530 GPUs.

Still, VSCode lets the system freeze upon exiting the application.
Also, `literally`nothing is being written into the error log (event viewer) once the system freezes.

Any ideas how we could help investigating (we don't have debug builds of windows available, though)?

**Comment by gauravmahto** [comment] 2019-08-27 08:41
I'm also observing the same issue. In my case, I get the same dialog box similar to the above screenshot.

But, my Win10 machine doesn't freeze and I can click to 'Reopen' button from the dialog box which closes and reopens the VSCode.

Is there anything I can help with to further isolate and identify the problem? Are there any logs that could be shared?

**Comment by gauravmahto** [comment] 2019-08-27 15:33
@deepak1556 

I tried the exploration build. But regret to inform you that I still observer the same issue.

**Comment by gauravmahto** [comment] 2019-08-28 06:43
@deepak1556 

I've extracted some of the steps from my build task and created a reproducible solution.
The problem here seems to be with the IO operation(s) which I believe VSCode terminal is not able to gracefully exit from.

Pre-requisite:
A gulpfile which performs some IO operations like read files etc. before running the actual gulp task.

Steps:
1) Try to run the gulp task from VSCode 'Run task'.
2) Abrupt the task by clicking the 'Kill Terminal' command. The key thing here is to kill the task before the IO operation is complete.

Please find the attached project.
[issue-78138.zip](https://github.com/microsoft/vscode/files/3549459/issue-78138.zip)

**Comment by gauravmahto** [comment] 2019-09-05 07:28
FYI @deepak1556 
Tested with 1.38. the problem still persist.
Let me know if there is anything I can do.

**Comment by gauravmahto** [comment] 2019-10-04 06:32
@deepak1556 Any update on this? Let me know if I can help.

**Comment by thehappycoder** [comment] 2019-12-26 05:44
It happened with me twice as well. I am using vscode, Firefox, Windows 10 with the latest patches. When vscode freezes, several applications react to mouse clicks only once. After that, even keyboard is not doing anything. I tried win+shift+ctrl+b to reset a graphics driver, but it didn't react to this keyboard binding either (screen should have went black for a second).

**Comment by gauravmahto** [comment] 2020-05-06 13:10
@deepak1556 The problem still persists. I'd provided the reproduction steps. Let me know if you need more info.

**Comment by stellaraccident** [comment] 2020-06-01 23:50
I just experienced these same symptoms after plugging a second monitor in. Fired up VSCode, got a few clicks in and then everything started behaving like the hard drive was removed.

Both monitors are plugged in to an NVIDIA GeForce RTX 2080 Ti. I've had to force reboot (power down by holding the power button for 10s) twice.

**Comment by LPontes** [comment] 2020-06-26 14:05
I'm observing something similar here. Everything runs normally until I open the VScode. The vscode python package cannot load and chrome takes a long time to respond. After a huge time (20 min) VScode is ready to run my python script, although win10 is no longer working properly. It recovers only with a clean boot, but I cannot use VSCode....

**Comment by stellaraccident** [comment] 2020-06-26 16:26
Not sure if it is a fix or a coincidence, but since this felt GPU related and only started happening when I plugged a second monitor in, I tried some different combinations to see if I could get back to stable. When I switched the second monitor from portrait to landscape, I have now not experienced the crash in ~3 weeks of use. As mentioned in the above thread, this is on an NVIDIA GeForce RTX 2080 Ti. I don't have brand information for both monitors, but they are different and different resolutions.

Again, not sure if it is relevant but perhaps a clue.

**Comment by timetraveller432** [comment] 2020-08-05 20:21
Hi, Surprisingly I am facing this same issue. 

_What exactly happens?_
If I leave my system unattended for some time, it **Hard Freezes**. Nothing really works, Not even the lights on the panel blink. About 1/10 times, I get a BSOD. I have shut down the laptop by long pressing the hardware button. 

I discovered this by experimenting with programs I typically use on windows. One by one, I left them running/open every night before leaving the system unattended till next morning. Only when I left VS Code open on windows in the foreground, did I find the system Hard Frozen the next morning. Even the clock stopped at the moment, it happens.

_Since When ?_
About 9 months ago

_What I already tried ?_
I tried the usual fixes as to thought not in the right direction now I understand
1. Re installing windows 
2. Maintaining regular windows updates 
3. Removing all Chrome Extensions, as more often, I find them using a lot of system resources.

_Did I check the Event Viewer?_
Nothing gets written to it.

_My Software Versions_
Windows Update: [](https://support.microsoft.com/en-us/help/4565483/windows-10-update-kb4565483)
VS Code: version 1.47.3

**Comment by liumingkun** [comment] 2020-08-11 19:41
Have the same problem -
Running the latest VS Code (v 1.47.3), on Windows 10 1809 with all patches installed. Dell laptop with an external monitor. VS Code occasionally becomes irresponsive, then the whole system freeze up. Hard reset is the only way out.

**Comment by leo43555483** [comment] 2020-08-15 10:37
The same problem occurred when opening the .js/.ts file, then the whole system freeze up. 
I tried reinstall vscode and removed all extensions
VS Code: version 1.47.3
OS: Windows10 1903-OS Build 18362.1016

**Comment by leo43555483** [comment] 2020-08-18 18:21
> The same problem occurred when opening the .js/.ts file, then the whole system freeze up.
> I tried reinstall vscode and removed all extensions
> VS Code: version 1.47.3
> OS: Windows10 1903-OS Build 18362.1016

I did switch off git.autorefresh in the Settings, then it solved my problem.

**Comment by wilk-polarny** [comment] 2020-08-18 18:35
We still have the same issue here at office on every single dev-laptop and we are clueless as to why this is happening - but we also suspect something GPU (we mostly have units with NVIDIA Quadro M2000M, M2200, P2000, P3200) related, as @stellaraccident did.

A mystery is still how a user space application can cause a freeze so bad, that symptoms persist after a reboot. Only a hard reset helps here.

**Comment by stellaraccident** [comment] 2020-08-18 18:45
This is sounding more and more like Microsoft needs to take a page out of the 90s-AOL playbook and physically procure one of these affected machines and repro/debug locally. This bug is quite devastating when it occurs, and even though I have a workaround (don't put my monitor in portrait mode!?!?), it is relatively terrifying that such a bug can recur at any time and essentially kill my development flow.

**Comment by wilk-polarny** [comment] 2020-08-18 19:20
> ... it is relatively terrifying that such a bug can recur at any time and essentially kill my development flow.

By this point, it evolved into a running gag here, where the follow up question to every problem is: "Did you close VSCode?".

Another thing is, that this issue is impossible to debug (at least for me), as a non-responsive system with no apparently no access to the storage drives (as if you pulled the cables) can't tell where it hurts :/

We already thought about setting up remote debugging using a windows debug build to at least dump some memory contents remotely. But interpreting stuff like this is above my knowledge (I only used such setup once to detect rootkit activity in suspicious software). Thus our current workaround is to NEVER close VSCode once it's opened on Windows or to use macOS workstations where VSCode runs without issues.

**Comment by KB1RD** [comment] 2020-09-02 15:32
This seems to happen on Linux, too. The distinguishing part seems to be the presence of NVIDIA cards on all machines with this issue. I do have the proprietary drivers installed. One interesting point is that some crashes are worse than others: Sometimes, I can't do anything and I hear the music I'm listening to start buzzing (looping inside the buffer). Other times, my desktop is unresponsive, but I can get into a recovery terminal and kill the WM. Rarely, I can still move my cursor enough to close VSCode and all web browsers. This seems to allow my computer to recover.

My case has a hard drive indicator light and every time this happens, the HD light is on full.

On one of my NVIDIA machines, I also see #69665. This is also the machine that crashes roughly 2-3 times per day (requiring a reboot in most cases), rending VSCode difficult to use. In some of my programming, I have encountered differences between what NVIDIA library calls return and what the docs *say* they should return, so my guess is that NVIDIA messed this up.

**Comment by nagulvali555** [comment] 2020-09-30 14:20
Facing same issue. - is there any fix or workaround for this. it's annoying to keep pressing reopen button.

**Comment by wilk-polarny** [comment] 2020-11-05 17:07
@deepak1556 , any chance of getting this issue looked at? Is there something we can do to help and investigate further?

**Comment by ajaythakor** [comment] 2020-11-09 06:37
@deepak1556 @bpasero 
I have started facing this issue last month and now, it happens very frequently.
Every time I run it, it freezes and I had to restart it.

@deepak1556 @bpasero Please update the status.

**Comment by deepak1556** [comment] 2020-11-09 07:03
@wilk-polarny I have not been able to repro the issue with your steps, can you update to latest stable and also download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , once you see the freeze right click on the code.exe process > Create Dump > Create Full Dump... , you will see multiple code.exe process, take the process dump from all of them and send them to Deepak.Mohan@microsoft.com. Thanks!

**Comment by wilk-polarny** [comment] 2020-11-09 20:04
> @wilk-polarny I have not been able to repro the issue with your steps, can you update to latest stable and also download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , once you see the freeze right click on the code.exe process > Create Dump > Create Full Dump... , you will see multiple code.exe process, take the process dump from all of them and send them to [Deepak.Mohan@microsoft.com](mailto:Deepak.Mohan@microsoft.com). Thanks!

Hi, @deepak1556 - that's difficult, as the system freezes as explained above - as if the system had no access to the persistent storage. Starting applications is impossible at the point where it freezes - so is trying to do process dumps.

**Comment by timetraveller432** [comment] 2020-11-30 08:56
In addition to my previous comment detailed [here](https://github.com/microsoft/vscode/issues/78138#issuecomment-669482575): I am observing weird behavior in other Microsoft products too. 

I have been using **Microsoft SQL Server Management Studio** and **Microsoft Visual Studio** for backend development and can confirm that the same issue is popping up there too. It tried using the Apps one by one without launching any other for a day and both times the system crashed. To debug, I tried to turn off most of System Startup Services for SQL Server, that did delay the problem though but it happened eventually when I had to use SQL back again.

This is my hypothesis, though not sure how true. But for me, the only thing common between the VS Code, SSMS, and Visual Studio is that I connect to Azure through all of them. Maybe, the _plugins/drivers/packages_ for **Azure connectivity** are causing this problem.

But really, I have to admit this is the most frustrating thing, since I started programming, and not knowing why this is happening, is disquieting.

**Comment by duaneking** [comment] 2021-01-07 08:20
Found this thread wondering why Visual Studio Code keeps crashing my Win10  20H2 (Build 19042.685) system if I stay up too late programming in it.

I'm using an Intel Graphics card, however.  Symptoms are the entire PC freezes, is unresponsive, video does not refresh and even the system clock in the lower right corner just stops, and accepts no input.  No crash to bluescreen just a full system freeze.

I have to force a power cycle to use the system again; But I lose everything unsaved in progress when I do.

**Comment by erikswed** [comment] 2021-03-23 11:31
> Found this thread wondering why Visual Studio Code keeps crashing my Win10 20H2 (Build 19042.685) system if use visual studio code on it yet if I use notepad++ its fine.
> 
> I'm using an Intel Graphics card, and Brave browser (forked from same as chrome, with additional security added, junkware/telemetry removed, etc) however. That fits the chrome details but I'm not seeing much discussion of intel videocards here.
> 
> Symptoms are the entire PC freezes, is unresponsive, video does not refresh and even the system clock in the lower right corner just stops, and accepts no input. No crash to bluescreen just a full system freeze.
> 
> I have to force a power cycle to use the system again; But I lose everything unsaved in progress when I do.
> 
> Will attempt the gpu off switch and see how that goes.
> 
> Edit: This seems to help with crashes but it slows down visual studio code so much that it becomes unusable in other ways on the system I repro this with. Its such a painful experience.

Exactly the same happens to me but only when starting debugging against Chroma Version 89.0.4389.90 (Officiell version) (64 bitar)

**Comment by PoofyFoopy** [comment] 2021-04-09 19:39
> Found this thread wondering why Visual Studio Code keeps crashing my Win10 20H2 (Build 19042.685) system if use visual studio code on it yet if I use notepad++ its fine.
> 
> I'm using an Intel Graphics card, and Brave browser (forked from same as chrome, with additional security added, junkware/telemetry removed, etc) however. That fits the chrome details but I'm not seeing much discussion of intel videocards here.
> 
> Symptoms are the entire PC freezes, is unresponsive, video does not refresh and even the system clock in the lower right corner just stops, and accepts no input. No crash to bluescreen just a full system freeze.
> 
> I have to force a power cycle to use the system again; But I lose everything unsaved in progress when I do.
> 
> Will attempt the gpu off switch and see how that goes.
> 
> Edit: This seems to help with crashes but it slows down visual studio code so much that it becomes unusable in other ways on the system I repro this with. Its such a painful experience.

The same thing is happening to me too with the latest build. I tried reverting to the January build yet still no change. I'm currently on Windows and this is my Windows Spec:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎29/‎05/‎2020
OS build	19042.906
Experience	Windows Feature Experience Pack 120.2212.551.0

The problem started after updating to the latest build though it still remained even when reverting to a previous build. Also, when VSCode finally closed during the freeze, everything returned back to normal. So might be a VSCode-OS (since the comment above me mentions the same problem but now on Chrome OS) interaction that's causing this. Another observation was that in Task Manager, Disk was at 100% yet if you sorted by Disk, there was nothing showing the 100% Disk usage. Something I noticed too though when reverting to the January build was that when it's a fresh install (deleting both %APPDATA%/Roaming/Code and  user/.vscode), Windows was more responsive. I would assume that the Extensions have something to do with making the freeze a whole lot worse. These are some of the observations I made during the passed two days trying to triage this situation and make VSCode functional again. Guess I'll have to use something else in the meantime.

**Comment by erikswed** [comment] 2021-04-11 12:24
I fixed it by removing plugin Debugger for Chrome and instead using Debugger for Microsoft Edge. hence debug run on Edge Browser for now

**Comment by PoofyFoopy** [comment] 2021-04-13 20:43
> > Found this thread wondering why Visual Studio Code keeps crashing my Win10 20H2 (Build 19042.685) system if use visual studio code on it yet if I use notepad++ its fine.
> > 
> > I'm using an Intel Graphics card, and Brave browser (forked from same as chrome, with additional security added, junkware/telemetry removed, etc) however. That fits the chrome details but I'm not seeing much discussion of intel videocards here.
> > 
> > Symptoms are the entire PC freezes, is unresponsive, video does not refresh and even the system clock in the lower right corner just stops, and accepts no input. No crash to bluescreen just a full system freeze.
> > 
> > I have to force a power cycle to use the system again; But I lose everything unsaved in progress when I do.
> > 
> > Will attempt the gpu off switch and see how that goes.
> > 
> > Edit: This seems to help with crashes but it slows down visual studio code so much that it becomes unusable in other ways on the system I repro this with. Its such a painful experience.
> 
> The same thing is happening to me too with the latest build. I tried reverting to the January build yet still no change. I'm currently on Windows and this is my Windows Spec:
> Edition	Windows 10 Pro
> Version	20H2
> Installed on	‎29/‎05/‎2020
> OS build	19042.906
> Experience	Windows Feature Experience Pack 120.2212.551.0
> 
> The problem started after updating to the latest build though it still remained even when reverting to a previous build. Also, when VSCode finally closed during the freeze, everything returned back to normal. So might be a VSCode-OS (since the comment above me mentions the same problem but now on Chrome OS) interaction that's causing this.
> 
> Another observation was that in Task Manager, Disk was at 100% yet if you sorted by Disk, there was nothing showing the 100% Disk usage. 
> 
> Something I noticed too though when reverting to the January build was that when it's a fresh install (deleting both %APPDATA%/Roaming/Code and  user/.vscode), Windows was more responsive. I would assume that the Extensions have something to do with making the freeze a whole lot worse.
> 
> These are some of the observations I made during the passed two days trying to triage this situation and make VSCode functional again. Guess I'll have to use something else in the meantime.

Follow up to this,
I fixed it by checking for errors on the drive I was using. My code is on the D drive and for some reason it got some errors with Windows saying anything. This would explain how it randomly occurred and a previous version of VSCode would not help.

**Comment by timetraveller432** [comment] 2021-07-04 10:29
I can confirm that the issue still exists. It has troubled me on my laptop
for over a year now.
Desperately need a fix.

You can check my comments in the thread before.

**Comment by 0shu** [comment] 2021-08-28 07:05
This has been happening to me for the past year or so.
Just happened again 5 minutes ago.
I thought it was everything else, change my graphics card, hard drive, CPU, power supply.
Reinstalled windows multiple times.
Finally noticed it stopped when I changed my JOB.
Had no clue why.
Just opened VSCode again to do some coding, and boom, soft crash again.
Then realised I stopped having VSCode up all the time since changing jobs.

So yeah VSCode still soft crashes.

OS:
Win10 Home 
Version 21H1 
Build 19043.1165

VSCode:
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by thehappycoder** [comment] 2021-11-16 11:30
I solved the problem by switching back to Mac OS.

**Comment by duaneking** [comment] 2021-11-16 16:12
This is unusable on many windows systems, and while the fix does indeed seem to be to simply not use windows as that does seem to fix it,  since the same company releases both products, I expect them to be compatible.  When can we expect the teams to act as One Microsoft?

**Comment by colindean** [comment] 2021-12-23 20:24
I was experiencing this for several days, maybe even weeks. Uninstalling my display drivers with the venerable [Display Driver Uninstaller by Wagnardsoft](https://www.wagnardsoft.com/display-driver-uninstaller-ddu-) in safe mode and then reinstalling the drivers (for me, NVIDIA) seems to have quelled the issue. I had also updated to Windows 10 Pro 21H2 from 20H2 so it's possible that something there fixed it, too, as I haven't experienced a crash since either and there was only about a day between the two.

**Comment by angieEncoded** [comment] 2021-12-28 21:56
I had thought perhaps this issue was solved as I have been using VSCode happily for months without a problem. However today I loaded up one of my NodeJS projects and almost like clockwork, within a couple hours the system was soft-locked with the same symptoms as described - I can still move the mouse but the rest of the system is completely unresponsive. I have to hold the power button and lose whatever had been running. 

I had no problems with VSCode developing in Django Python, but when I worked on my Express NodeJS software the behavior was back. 

I do also have a Nvidia GPU in my laptop, but I have my doubts about that being the root of the problem. Could there be something in NodeJS that disagrees with VSCode?

**Comment by colindean** [comment] 2021-12-29 00:17
I didn't open VScode for ~6 days and my system was fine with one unrelated unexpected reboot yesterday. I've had VScode open for about 90 minutes and hit a hard lock already. I think I might be putting VSCode back in the tool box.

**Comment by colindean** [comment] 2022-03-27 14:36
I am still completely unable to use VScode for more than the time specified above. I'll happily provide some debugging information or follow troubleshooting steps if someone can provide me instruction how to do so.

**Comment by duaneking** [comment] 2022-03-27 17:29
Can you please turn off the stupid bot that turns off tickets and closes them just because somebody ignores it for too long?

It's the same thing as saying that if you want to ignore it long enough you can just close it, and that's really disrespectful of the community.

This is clearly a huge issue. It wouldn't be getting the responses it is if it didn't really exist. 

This comes off as people simply not caring.

**Comment by deepak1556** [comment] 2022-03-28 07:29
@colindean can you check if the problem persists with insiders https://code.visualstudio.com/insiders/ and also try to run with `--disable-extension --disable-features=CalculateNativeWinOcclusion`

**Closed** 2022-04-07 11:29 UTC
Labels: needs more info, freeze-slow-crash-leak, windows

**Comment by thehappycoder** [comment] 2022-04-07 20:02
Apparently, Microsoft wants us to switch to MacOS LOL

**Comment by duaneking** [comment] 2022-04-13 23:48
This bot needs deleted, its just creating technical debt.  This issue needs reopened.
