### ISSUE TITLE
editorFocus is still true when launching the command palette

### ISSUE THREAD

**Issue by ShPelles** [microsoft/vscode#124755] opened 2021-05-27 13:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Win 10

Steps to Reproduce:

1. Create new extension (with `yo code`) and open it.
2. Add this to the `contributes` section in `package.json`:
```
"menus": {
	"commandPalette": [
		{
			"command": "editor-focus-bug.helloWorld",
			"when": "editorFocus"
		}
	]
}
```
3. Run the extension (<kbd>F5</kbd>).
4. Open a document.
5. Open the Command Palette (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>), and scroll down. The `hello world` command shows up.
6. Type "hello" in the Command Platte. The "hello world" command is removed.

**Comment by TylerLeonhardt** [comment] 2021-05-27 14:42
This is by design because "focus" is the same concept as focus on the web...it's lost when you click into the command palette.

Here's another example: if you show a button on `editorFocus` and then you click into the terminal, the button disappears.

I'm closing this as by design but if you describe what you're trying to achieve, I could potentially help you find a better context key.

**Comment by ShPelles** [comment] 2021-05-27 18:44
This is a little bit strange.
When I open the Command Palette, editorFocus is true.
If I scroll with the mouse, it's still true.
If I use the Arrow keys or even the pageUp/pageDown keys, the editor still focused.
But when I try to type something, then the focus was lost.

**Comment by TylerLeonhardt** [comment] 2021-05-28 01:35
It sounds like the editor isn't "loosing focus" when the command palette is launched. That to me is a bug.

@chrmarti @bpasero would you agree?

**Comment by bpasero** [comment] 2021-05-28 05:09
Maybe @alexdima can explain how the context key is working. I do not think quick open is doing anything special, I mean in the end the input field has keyboard focus, so I would assume that at least DOM focus is inside quick pick.

**Comment by alexdima** [comment] 2021-06-03 20:19
@bpasero This appears to be intentional due to the implementation of quick open, which is doing something very special [here](https://github.com/microsoft/vscode/blob/b80011a819c022ebd41f5965abd09b46a55108cc/src/vs/workbench/contrib/quickaccess/browser/commandsQuickAccess.ts#L114). I think the commands want to be evaluated in the context of the current active editor, and the current active editor defines `editorFocus`. So AFAICT this works as designed.

**Comment by TylerLeonhardt** [comment] 2021-06-03 20:22
Thanks for the context @alexdima!

**Closed by TylerLeonhardt** 2021-06-03 20:22 UTC
Labels: *as-designed
