### ISSUE TITLE
Ability to prevent folder hierarchy from being opened when one of its files is opened.

### ISSUE THREAD

**Issue by UserSina** [microsoft/vscode#118358] opened 2021-03-07 10:09 UTC
When `CTRL + CLICK`ing a file, it opens as intended but also expands the whole folder structure where the file is located.
I would then have to collapse the folder manually when I'm done with the file.

I would suggest including a small clickable lock icon in front of any folder to allow/prevent it from being expanded when a file in that folder is opened.

Here's the gist of it:

![feature_sugg](https://user-images.githubusercontent.com/44204957/110236279-34c12700-7f35-11eb-9e40-de68da6d605d.jpg)

**Comment by gjsjohnmurray** [comment] 2021-03-07 16:13
/duplicate of #87956 but the lock icon looks new.

**Closed** 2021-03-07 16:13 UTC
Labels: *duplicate
