### ISSUE TITLE
API: allow case insensitive find files via vscode.workspace.findFiles()

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#8666] opened 2016-07-02 06:39 UTC
**Steps to Reproduce:**
a file with name "Unit.pas"

```
filename = 'unit';
vscode.workspace.findFiles('**/' + filename + '.*', '')
```

**Problem:** 
file *Unit.pas" will not be found, because the case doesn't match.
(Windows is a case-insensitive files system)

_VSCode Version: 1.2.1 / OS Version: Windows 10_

**Comment by jrieken** [comment] 2016-07-04 09:06
It just delegates to the [search service](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadWorkspace.ts#L40)

**Comment by bpasero** [comment] 2016-07-04 09:32
After investigation: searches from extensions never fill in `filePattern` but rather `includePattern` and since our glob is case sensitive, this is a valid request.

Refs: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadWorkspace.ts#L50

**Comment by akshita31** [comment] 2018-09-22 00:32
Any update on this one ?

**Comment by roblourens** [comment] 2018-09-22 02:18
Dupe of https://github.com/Microsoft/vscode/issues/10633

**Closed by roblourens** 2018-09-22 02:18 UTC
Labels: api, feature-request, search
