### ISSUE TITLE
Process explorer doesn't show which 'window' is which

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#48450] opened 2018-04-23 22:35 UTC
`code-insiders --status` includes the title of the window in the row for each renderer process:

```
CPU %   Mem MB     PID  Process
    2      164    6379  code-insiders main
    3      180    6380     gpu-process
    0      279    6381     window (package.json — debugs_core (Workspace))
```

But the process explorer doesn't include this info (at least on mac)

![image](https://user-images.githubusercontent.com/323878/39156617-d31596a8-470b-11e8-9839-3ad71a42a49e.png)

so there's no way to tell which set of processes belongs to which window.

**Comment by RMacfarlane** [comment] 2018-04-30 22:09
Duplicate of #48626

**Closed by RMacfarlane** 2018-04-30 22:09 UTC
