### ISSUE TITLE
Auto Format Document doesn't put ELSE on same line as IF's closing brace

### ISSUE THREAD

**Issue by paulthomas75** [Microsoft/vscode#41742] opened 2018-01-17 12:33 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 7

Steps to Reproduce:

1.  Create a typescript file with an if else statement placing the else on any line below opening brace.

```
if (true) 
{
	//this will format correct
}
else 
{
	//this wont
}

```
2.  Highlight section and Shift+Alt+F  to apply formatting

```
if (true) {
	//this will format correct
}
else {
	//this wont
}
```

Note the else doesn't reflect one-liner line style rule.  Should be:

```
if (true) {
	//this will format correct
} else {
	//this wont
}
```

If this is by design, an option to override it would be good.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-01-17 19:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/15061

**Closed by mjbvz** 2018-01-17 19:32 UTC
Labels: editor, editor-autoindent

**Comment by paulthomas75** [comment] 2018-01-18 10:14
Microsoft/TypeScript#15061 still doesn't state what is the option setting to apply the preferred format...one line OR new line.  Something like javascript.format.placeOpenBraceOnNewLineForElseControlBlocks": true
