### ISSUE TITLE
Cannot read property 'size' of undefined warning when navigating an empty explorer list

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#44309] opened 2018-02-24 01:09 UTC
- VSCode Version: 1.21.0-insider (https://github.com/Microsoft/vscode/commit/ce13bb0dabd06981913c46b5a94456647864c2e0)
- OS Version: Windows 10 x64 

Steps to Reproduce:
1. Open a fresh VS Code instance, close any open files/folders.
2. Ctrl+Shift+E to target the Explorer
3. Use up/down to move through the empty list

Does this issue occur when all extensions are disabled?: Yes

Expected repro: A warn notification pops up for every keypress

I first encountered this issue with an open folder but no open files so the explorer had selected the open editors list which was empty.

**Comment by sbatten** [comment] 2018-02-24 01:15
```
TypeError: Cannot read property 'size' of undefined
    at ListView.elementHeight (file:///C:/Users/stbatt/Source/vscode/out/vs/base/browser/ui/list/listView.js:168:37)
    at WorkbenchList.List.reveal (file:///C:/Users/stbatt/Source/vscode/out/vs/base/browser/ui/list/listWidget.js:890:43)
    at focusUp (file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/electron-browser/commands.js:94:22)
    at handler (file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/electron-browser/commands.js:111:57)
    at InstantiationService.invokeFunction (file:///C:/Users/stbatt/Source/vscode/out/vs/platform/instantiation/common/instantiationService.js:48:34)
    at CommandService._tryExecuteCommand (file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/services/commands/common/commandService.js:70:72)
    at file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/services/commands/common/commandService.js:60:65
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///C:/Users/stbatt/Source/vscode/out/vs/base/common/winjs.base.raw.js:1579:49)
    at CommandService.executeCommand (file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/services/commands/common/commandService.js:60:32)
    at WorkbenchKeybindingService.AbstractKeybindingService._dispatch (file:///C:/Users/stbatt/Source/vscode/out/vs/platform/keybinding/common/abstractKeybindingService.js:111:38)
```

it looks like the call into list.reveal is blindly passing the empty list's nonexistent focused item

**Comment by sbatten** [comment] 2018-02-24 01:16
also, potentially related to #43475

**Comment by ntovas** [comment] 2018-02-25 20:31
i m looking it

**Comment by isidorn** [comment] 2018-02-26 16:37
Seems to be fixed in latest out of source - I can no longer reproduce and we pushed commits which are related to this https://github.com/Microsoft/vscode/commit/db616b33097cb578cea924046fc38efc00d1c58f.

Please try it out in tomorrows insiders and if you still see it let me know and I will reopen

**Closed by isidorn** 2018-02-26 16:37 UTC
Labels: bug, file-explorer

**Comment by isidorn** [comment] 2018-03-01 05:39
Pushed a fix https://github.com/Microsoft/vscode/commit/5974852ae10ae8ece1e61e69bcfdd232e9fa02c2

fyi @bpasero
