### ISSUE TITLE
TreeError [testView] Data tree node not found: [object Object]

### ISSUE THREAD

**Issue by kaisunc** [microsoft/vscode#101335] opened 2020-06-30 04:35 UTC
- VSCode Version: 1.47.0-insider
- OS Version: Windos_NT x64 10.0.10941

Steps to Reproduce:

1. load vscode sample extension "tree-view-sample"
2. enter reveal command in command palette, reveal aaa
3. error shown as popup, but nothing logged to console. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by kaisunc** [comment] 2020-06-30 04:37
Same issue as here,
https://github.com/microsoft/vscode/issues/82629
https://github.com/microsoft/vscode/issues/90605

**Comment by kaisunc** [comment] 2020-06-30 06:22
my extension uses the reveal method, and it worked until last wednesday. This monday after updates broke the method. I tested it with the sample extensions and seems to be the update.

**Comment by alexr00** [comment] 2020-07-01 07:30
I can't reproduce this on the latest insiders. This was likely fixed by https://github.com/microsoft/vscode/commit/85d3eb2c644aa8253f529ba73e2071e2d23da194

**Closed by alexr00** 2020-07-01 07:30 UTC
