### ISSUE TITLE
Terminal search results paths not clickable

### ISSUE THREAD

**Issue by decodekult** [Microsoft/vscode#58087] opened 2018-09-06 16:19 UTC
Running Visual Studio Code 1.27.1 over Windows 10, using Git bash as terminal and with ACK installed.

Up until the last update, after performing a term search in the terminal, Ctrl+click over paths in results opened the related file in a new tab. AFter the last update, that shortcut no longer works.

Tested also with PowerShell and the native Windows command line.

**Comment by Tyriar** [comment] 2018-09-06 19:16
Can you share a screenshot? Also what folder was the terminal opened at initially?

**Comment by xackery** [comment] 2018-09-06 21:13
1.27 over OSX, project links of e.g.
test/foo/file.go:12:12: some error here

used to be cmd+click able, now they don't show up as valid urls to click. 
test/foo/file.go is relative to the project workpath root directory.

**Comment by decodekult** [comment] 2018-09-07 05:20
Attaching a screenshot, with the path where the terminal opened, and the unclickable relative paths. No space in any of them.
![captura de pantalla 76](https://user-images.githubusercontent.com/1232205/45199897-81492000-b26e-11e8-982b-c33415fc1c59.png)

**Comment by mceachen** [comment] 2018-09-07 22:43
Confirmed on Mac, Windows, and Linux.

Note that this affects `tsc`/`tsc --watch` build terminals as well.

I'm running vscode 1.27.1 on windows 10, mac OS X 10.11, and Ubuntu 18.04.01.

**Comment by xackery** [comment] 2018-09-09 02:38
this is a duplicate of #58256 i believe.

**Closed** 2018-09-10 13:52 UTC
Labels: integrated-terminal, needs more info
