### ISSUE TITLE
code_helper hangs and makes vscode unresponsive

### ISSUE THREAD

**Issue by Lallassu** [Microsoft/vscode#25006] opened 2017-04-19 09:23 UTC
code_helper hangs in background and makes vscode unresponsive. It has to be restarted with hard kill. This is randomly caused by indenting code using one of the vim plugins. In this case javascript.
The code_helper is hogging the CPU. Killing it doesn't bring back the responsiveness in the gui.

- VSCode Version: 1.11.2
- OS Version: OSX El capitan 10.11.6

Steps to Reproduce:

1. install plugin Vim emulation for visual studio (vscodevim) 0.6.16
2. Indent some lines marking them with shift-v-down then shift-= to indent.

**Comment by mjbvz** [comment] 2017-04-19 21:19
When this happens, can you try running  `ps aux | grep -i "code helper"` in the terminal and share the output. This should help us identify which code helper process is causing problems

**Comment by Lallassu** [comment] 2017-04-20 05:14
Sure, I can give you further output next time it hangs.

**Comment by Jfeurich** [comment] 2017-04-20 13:54
ps -eo pcpu,user,pid,command | grep renderer output: 100% cpu

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=93A1BFE0D5861A2F10442CCE119E9C19 --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=65BE9654104FEB80940C334FCC248304 --mojo-application-channel-token=93A1BFE0D5861A2F10442CCE119E9C19 --channel=63227.16.1361252098

**Comment by Jfeurich** [comment] 2017-04-21 09:43
This is also code helper crashing vscode, but in my case it seems to be related to a large amount of git changes. Clicking the tab makes everything unresponsive.

90081 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=C22959CA599F8E2841030AA601A2AE9E --lang=en-GB --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=B3A766BF907F43B151E9142ACB874943 --mojo-application-channel-token=C22959CA599F8E2841030AA601A2AE9E --channel=63227.20.2083186900

![screen shot 2017-04-21 at 11 41 40](https://cloud.githubusercontent.com/assets/4457903/25272271/8715fad6-2687-11e7-9d9c-47142991e6e1.png)

**Comment by mjbvz** [comment] 2017-04-21 18:48
@Jfeurich Since you mention git, your issue may be related to #23976. The latest insiders build has a fix for this

**Comment by Lallassu** [comment] 2017-04-22 22:03
It hanged again, this is the output for ps:

(standard input):2:nergal           17662 100.0  0.7  3310972 119416   ??  R    Thu01PM   7:34.07 /Users/nergal/Downloads/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/nergal/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Users/nergal/Downloads/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/4j/f8c3624d3kdbd244cbn957fw0000gn/T/vscode-tscancellation-b86b7f4ed61e136a6797.sock*

**Comment by mjbvz** [comment] 2017-04-25 01:56
You may want to try out that latest insiders builds that include TS 2.3.1. This release fixes a number of performance problems that could be causing this. 

It would also be great if you could share the typescript server log. To do this:

* Set `"typescript.tsserver.log": "verbose",`
* Restart VSCode.
* Once the issue reproduces, run the `TypeScript: Open TS Server log file` command and share the log file
* Also reveal the location of the log file in the finder. There should be a `ti-xxx.log` file next to it with information about typings install

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Closed** 2017-05-24 18:42 UTC
Labels: freeze-slow-crash, needs more info
