### ISSUE TITLE
Add progress bar when downloading file

### ISSUE THREAD

**Issue by jeasow-lynx** [microsoft/vscode#144331] opened 2022-03-03 18:54 UTC
Issue Type: <b>Feature Request</b>

My workspace is remote and I use 'Remote - SSH' extension. 

In vscode 'Explorer', when I right click on a file and download, it downloads to my local laptop, but there is no progress indication on how much the file has downloaded. It will be nice if there is a progress bar for the ongoing download.

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-96-generic

**Comment by JacksonKearl** [comment] 2022-03-03 19:32
Duplicate of #111580

**Closed by JacksonKearl** 2022-03-03 19:32 UTC
