### ISSUE TITLE
Voiceover reads all lines instead of a new line

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#88728] opened 2020-01-16 00:23 UTC
Steps to Reproduce:

1. Create blank file with text on three lines, and one blank line
2. Move cursor to each line, voiceover correctly reads each line. 
3. Move to the last, blank line and voiceover reads all the lines again. Expected behavior is to read "blank line" or "new line"

![line_reading_voiceover](https://user-images.githubusercontent.com/9721254/72482331-2b658000-37b2-11ea-87cc-19209563cd4a.gif)

Version: 1.42.0-insider
Commit: 5e758c10c969d668730f036abfc557d9cfb62b87
Electron: 7.1.7
OS: MacOS Mojave

@ivanfetch

**Comment by isidorn** [comment] 2020-01-16 10:05
This is a duplicate of https://github.com/microsoft/vscode/issues/70033
That issue has all the details: in short it is a Chromium bug that the Chromium team has started to work on. 
More details of the chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=951777

**Closed by isidorn** 2020-01-16 10:05 UTC
Labels: accessibility, accessibility-voiceover
