### ISSUE TITLE
Vscode is easy to crash after the handover process, on window 10.

### ISSUE THREAD

**Issue by ZakaryCode** [Microsoft/vscode#63102] opened 2018-11-14 08:11 UTC
Issue Type: <b>Bug</b>

As mentioned in the title, after switching processes on Windows, vscode is prone to crash. There are no screenshots at present, but the probability is high.

Version: 1.29.0 (user setup)
Submission: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
solidity-extended|bea|3.0.2
git-easy|bib|1.9.1
markdown-preview-github-styles|bie|0.1.4
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
react-native-react-redux|EQu|1.9.2
json-tools|eri|1.0.2
prettier-vscode|esb|1.7.2
git-project-manager|fel|1.7.1
code-runner|for|0.9.5
applescript|idl|0.14.2
solidity-solhint|idr|1.1.4
docthis|joe|0.7.1
solidity|Jua|0.0.46
vscode-map-preview|jum|0.4.2
solidity-language-server|kod|0.1.6
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.29.2
mssql|ms-|1.4.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.11.0
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
minapp-vscode|qiu|1.9.2
qub-xml-vscode|qub|1.2.8
java|red|0.33.0
sass-indented|rob|1.4.9
nunjucks|ron|0.2.3
background|sha|1.1.19
velocity|sod|0.1.0
addDocComments|ste|0.0.8
react-beautify|tai|0.3.0
python|tht|0.2.3
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-react-native|vsm|0.6.18
gitblame|wad|2.6.0
vscode-java-saber|You|0.1.0
propertylist|zho|0.0.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joseph1125** [comment] 2018-11-14 15:11
duplicate of #62970

**Closed** 2018-11-16 04:55 UTC
Labels: new release
