### ISSUE TITLE
sizable on mac

### ISSUE THREAD

**Issue by onkelhoy** [microsoft/vscode#84568] opened 2019-11-12 09:40 UTC
- VSCode Version: 1.40.0
- OS Version: 10.14.6

Steps to Reproduce:

1. open vs code
2. try scale window-editor on horizontal (it only goes to a fixed limit) 

I need this when developing responsive behaviour, (having browser on top and vs code on bottom) I have macbook air 2019 13.3"

Does this issue occur when all extensions are disabled?: Yes

**Comment by Mark7528** [comment] 2019-11-12 12:20
Reproduced in:
- VS Code Version 1.40.0
-  Windows_NT x64 Version 10.0.17763

There is no resizing problems in VS Code Version 1.41.0-insider.

**Comment by gjsjohnmurray** [comment] 2019-11-12 13:58
Probably fixed by #84532 which is coming in the 1.40.1 recovery release.

**Closed** 2019-11-12 21:21 UTC
Labels: *duplicate

**Comment by gjsjohnmurray** [comment] 2019-11-13 01:02
@sbatten I think your #84532 only affects min height, reverting an earlier increase of that value. Looks like a corresponding recent min **width** increase remains, which is apparently what triggered this issue. Any plans to revert the min width increase too?

**Comment by sbatten** [comment] 2019-11-13 18:28
no plans to reduce the width currently, the most recent size chosen is the minimum for some of our widgets to appear still allowing side by side on 720p monitors.
