### ISSUE TITLE
tasks presentation echo true doesn't echo command in 1.60

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#132443] opened 2021-09-06 10:11 UTC
Issue Type: <b>Bug</b>

Using
"presentation": {
      "echo": true,
     etc
}
doesn't echo the commands (using git bash as shell under Windows). Used to work in previous version.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (17.48GB free)|
|Process Argv|--crash-reporter-id 27b05253-eb30-4313-974d-48b1345f0a4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
overtype|ada|0.2.0
read-only-indicator|ale|3.6.0
sourcetrail|ast|0.0.2
doxdocgen|csc|1.3.2
gitlens|eam|11.6.0
permute-lines|ear|1.1.0
graphviz-preview|EFa|1.5.0
vscode-toggle-column-selection|eri|1.0.6
matlab|Gim|2.0.1
triggertaskonsave|Gru|0.2.17
symbol-navigate-back|ike|1.1.12
better-cpp-syntax|jef|1.15.6
magit|kah|0.6.21
vscode-opn|lfu|1.1.2
string-manipulation|mar|0.5.2
select-part-of-word|mle|1.0.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
vs-qalc|nor|0.1.7
indent-rainbow|ode|7.5.0
indenticator|Sir|0.7.0
rewrap|stk|1.14.0
code-spell-checker|str|2.0.4
selectline-statusbar|tom|0.0.2
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-09-06 10:59
Maybe because 1.60 is incorrectly always using Powershell? Fix for this is coming in 1.60.1 recovery

**Comment by BillDenton** [comment] 2021-09-06 11:08
I had noticed the problem with Powershell. If I close a window with git bash running and then open it again it re-opens with Powershell (not git). Used to work.
I don't think that it is the same problem as the command is executing correctly. As it a complex command of the form:
export VARIABLE1="something"
&&
export VARIABLE2="something else"
&&
(a build command || failure_script)
&&
success_script
I don't think this would run correctly if it was under Powershell.

**Comment by alexr00** [comment] 2021-09-23 11:43
I am not able to reproduce the issue with 1.60.2.

**Closed by alexr00** 2021-09-23 11:43 UTC

**Comment by BillDenton** [comment] 2021-09-23 11:53
@alexr00 I can still see the problem. I set my presentation options at the top level and not seeing the command echoed:
{
   // See https://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
   "version": "2.0.0",
   "type": "shell",
   "presentation": {
      "echo": true,
      "reveal": "always",
      "focus": false,
      "panel": "shared",
      "clear": true,
      "showReuseMessage": false
   },
   "runner": "terminal",
   "tasks": [
      {
         "label": "Build",
         "group": {
            "kind": "build",
            "isDefault": true
         },
         "windows": {
            "options": {
               "shell": {
                  "executable": "C:\\Program Files\\Git\\bin\\bash.exe",
                  "args": [
                     "-c"
                  ]
               },
               "cwd": "${workspaceFolder}\\<something>"
            }
         },
         "type": "shell",
         "problemMatcher": "$msCompile",
         "command": "",
         "args": [
            "export",
            "SCONSFLAGS=\"<some stuff>\"",
            "&&",
            "export",
            "TEMP=\"<a path>"",
            "&&",
            "(./scons",
            "build argument",
            "build option 1",
            "build option 2",
            "||",
            "<build fail command>)",
            "&&",
            "<build sucess command>"
         ]
      },
