### ISSUE TITLE
Inserting language sepcific setting uses unusal formatting

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#19139] opened 2017-01-24 10:23 UTC
Test: https://github.com/Microsoft/vscode/issues/19060

- VSCode Version: 1.9
- OS Version: Windows

Steps to Reproduce:

1. Insert a markdown specific language setting
2. My settings file looks like this afterwards:
```json
{
	"editor.renderWhitespace": "boundary",
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 1000,
	"explorer.openEditors.visible": 0,
	"tslint.enable": false,
	// "editor.fontFamily": "helvetica",
	"editor.fontFamily": "hack",
	"editor.fontLigatures": false,
	"editor.fontSize": 13,
	"editor.folding": false,
	"workbench.settings.openDefaultSettings": false,
	"workbench.editor.showTabs": true,
	"workbench.editor.enablePreview": false,
	"workbench.editor.enablePreviewFromQuickOpen": false,
	"editor.snippetSuggestions": "bottom",
	"typescript.check.tscVersion": false,
	"git.confirmSync": false,
	"window.zoomLevel": 0,
	"security.workspacesTrustedToSpecifyExecutables": {
		"P:\\mseng\\VSCode\\vscode": true
	}
,
"[markdown]": {
		
	}
}```

Would have expected:

```json
{
	"editor.renderWhitespace": "boundary",
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 1000,
	"explorer.openEditors.visible": 0,
	"tslint.enable": false,
	// "editor.fontFamily": "helvetica",
	"editor.fontFamily": "hack",
	"editor.fontLigatures": false,
	"editor.fontSize": 13,
	"editor.folding": false,
	"workbench.settings.openDefaultSettings": false,
	"workbench.editor.showTabs": true,
	"workbench.editor.enablePreview": false,
	"workbench.editor.enablePreviewFromQuickOpen": false,
	"editor.snippetSuggestions": "bottom",
	"typescript.check.tscVersion": false,
	"git.confirmSync": false,
	"window.zoomLevel": 0,
	"security.workspacesTrustedToSpecifyExecutables": {
		"P:\\mseng\\VSCode\\vscode": true
	},
	"[markdown]": {
		
	}
}
```

@sandy081 FYI.

**Comment by sandy081** [comment] 2017-01-24 10:29
Duplicate of #17195

**Closed by sandy081** 2017-01-24 10:29 UTC
Labels: json
