### ISSUE TITLE
Markdown relative image tags

### ISSUE THREAD

**Issue by Squibs** [microsoft/vscode#158178] opened 2022-08-15 14:43 UTC
Type: <b>Bug</b>

1. Create repository with a folder with an image as well as a readme at the root.

2. Link to the image using `<img src="/Images/cat.jpg" />` in the README markdown file.

3. Image does show when previewing the markdown file.

![markdown issue](https://user-images.githubusercontent.com/2145187/184657534-8837b414-451b-414a-a589-13a5e7f9b2b0.png)

VS Code version: Code - Insiders 1.71.0-insider (1a582f7c079d1eb4c89d4f637da2fc2fcb688b31, 2022-08-15T05:17:18.259Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.82GB free)|
|Process Argv|--crash-reporter-id a13b4e18-07e8-4045-8297-d97a18631ae8|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by mjbvz** [comment] 2022-08-16 14:31
Duplicate of #46448

**Closed by mjbvz** 2022-08-16 14:31 UTC
