### ISSUE TITLE
Completion proposals stay after backspacing first character

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#19240] opened 2017-01-24 17:46 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea, 2017-01-24T10:29:13.076Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Open empty html file
2. Type: foo`<space>`f
3. Completion proposal for `foo` shows
3. Type `<backspace>`
4. Expected: Proposal for `foo` goes away because `f` was deleted
5. Actual: Proposal for `foo` stays

**Comment by jrieken** [comment] 2017-01-25 11:11
this is a dupe of #18577

**Closed by jrieken** 2017-01-25 11:11 UTC
Labels: suggest
