### ISSUE TITLE
Text related to the Find All References feature is not localized

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#85055] opened 2019-11-18 18:51 UTC
This is based on: https://github.com/microsoft/vscode-cpptools/issues/4629

![image](https://user-images.githubusercontent.com/49173979/69080660-42296980-09f1-11ea-8f03-b8db176b56cd.png)

![image](https://user-images.githubusercontent.com/49173979/69080717-5a998400-09f1-11ea-9c30-8a02cdd0df3a.png)

![image](https://user-images.githubusercontent.com/49173979/69080733-5e2d0b00-09f1-11ea-88fb-5c3f94c5b411.png)

**Comment by sean-mcmanus** [comment] 2019-11-18 20:16
This is a duplicate of https://github.com/microsoft/vscode/issues/64526 .

**Closed** 2019-11-18 20:23 UTC
Labels: *duplicate
