### ISSUE TITLE
Keyboard navigation using custom title bar and menus on windows takes the window out of position

### ISSUE THREAD

**Issue by mazyvan** [Microsoft/vscode#54193] opened 2018-07-12 17:13 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:

1. configure `"window.titleBarStyle": "custom"`
2. restart
3. open some title bar menu

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/10915753/42648474-ac6a7c94-85cc-11e8-9871-0ebaad2cb321.png)

**Comment by sbatten** [comment] 2018-07-12 18:30
duplicate of #52533

**Closed by sbatten** 2018-07-12 18:30 UTC
