### ISSUE TITLE
File names/path cut off in debug console

### ISSUE THREAD

**Issue by Cubly** [microsoft/vscode#105007] opened 2020-08-19 15:37 UTC
Issue Type: <b>Feature Request</b>

Have a long file name/path and then console.log something.

I cannot see which line of the file the console.log came from even with hovering over the cut off file name/path.

Example: https://i.imgur.com/bTcVzNH.png

Notice the commands/pickcmd.j... 

I could not find any setting to change this. 
I think there should be a setting to change the max-width of this from 150px and/or an option to show the full line on hover.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)

**Comment by isidorn** [comment] 2020-08-20 08:14
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
Because we pushed a fix for this like 7 days ago.

**Comment by Cubly** [comment] 2020-08-21 00:09
I downloaded VS Code Insiders and my problem is resolved! https://i.imgur.com/Y2cEyYC.png
Really long paths still get cut off, but it's not issue for me personally. It would be nice though if when you hover over a path, it would show the line numbers!

Thanks! I hope it makes it to the main app soon!

**Comment by isidorn** [comment] 2020-08-21 08:54
Yeah it will be a part of the next release.
I have added line numbers to the hover. That makes sense.

**Closed** 2020-08-21 08:54 UTC
Labels: debug, needs more info
