### ISSUE TITLE
--status hangs on Windows 7

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#40315] opened 2017-12-15 18:15 UTC
- VSCode Version: 1.19.0
- OS Version: Windows 7

'code --status' never returns with output

**Comment by bpasero** [comment] 2017-12-16 08:45
I can reproduce but unfortunately I cannot build on Windows 7 due to node.js process getting out of memory.

@dbaeumer I suspect an issue with executing powershell, maybe you could also have a look.

**Comment by bpasero** [comment] 2017-12-16 08:50
I managed to build and I verified that this fails in this [branch](https://github.com/Microsoft/vscode/blob/ben/elevate/src/vs/base/node/ps.ts#L121).

**Comment by dbaeumer** [comment] 2017-12-18 09:57
This is very likely a problem with PowerShell and Windows 7. Will have a look. @seanmcbreen do we have an idea how many Windows 7 users we have?

**Comment by dbaeumer** [comment] 2018-09-24 13:16
Closing the issue. This is now implemented as a native module and the powershell code I wrote is not being used anymore.

**Closed** 2018-09-24 13:17 UTC
Labels: invalid, windows, workbench-diagnostics
