### ISSUE TITLE
unable to install any extension and unable to open setting

### ISSUE THREAD

**Issue by p1kmantra** [microsoft/vscode#206678] opened 2024-03-02 12:06 UTC
Type: <b>Performance Issue</b>

when I am trying to install within vs code on my chromebook. it show me an error message -try manually or check for the log , and when click on the log Unexpected token '#',"#!/bin/bas"...is not valid.

VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:16.599Z)
OS version: Linux x64 6.1.64-09049-g010fe86d9eae
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|2.70GB (2.11GB free)|
|Process Argv|--unity-launch --crash-reporter-id bd7e8623-d441-49cd-9004-64bd45b922b6|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   155	  6018	code main
    0	    44	  6021	   zygote
    1	   108	  6050	     gpu-process
    0	    44	  6022	   zygote
    0	    11	  6025	     zygote
    0	   213	  6074	window [1] (helloworld - Visual Studio Code)
    4	   102	  6942	window [2] (Issue Reporter)
    0	    64	  6057	   utility-network-service
    0	    94	  6342	shared-process
    0	     0	  6954	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6955	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    80	  6343	fileWatcher [1]
    0	   177	  6363	extensionHost [1]
    0	    72	  6717	     /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=6363
    0	    86	  6389	ptyHost
    0	     8	  6417	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     8	  6420	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (helloworld - Visual Studio Code)
|    Folder (helloworld): 1 files
|      File types: vsix(1)
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30958357
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by p1kmantra** [comment] 2024-03-02 12:09
how can the issue as mentioned above be fixed?

**Comment by ThusSpokeNomad** [comment] 2024-03-02 23:39
dupe of #206522

**Comment by sandy081** [comment] 2024-03-04 08:23
Can you please share the following log while you reproduce the issue

- F1 > Open View... > Shared

**Comment by p1kmantra** [comment] 2024-03-04 08:41
sure

**Comment by p1kmantra** [comment] 2024-03-04 09:49
2024-03-04 15:11:23.911 [info] Started local extension host with pid 3412.
2024-03-04 15:11:26.426 [error] Error scanning user extensions: Unexpected token '#', "#!/bin/bas"... is not valid JSON
2024-03-04 15:11:27.161 [error] SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 15:11:28.514 [error] Unexpected token '#', "#!/bin/bas"... is not valid JSON:

**Comment by p1kmantra** [comment] 2024-03-04 10:37
2024-03-04 16:02:57.404 [error] SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:57.651 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:57.812 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:58.867 [error] SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:03:01.444 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:03:01.813 [error] [uncaught exception in sharedProcess]: Event not found: onDidChange: CodeExpectedError: Event not found: onDidChange
    at Object.listen (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:45:4960)
    at E.t (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:44:251)
    at E.q (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:4371)
    at y.value (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:3602)
    at d.y (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1902)
    at d.z (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1972)
    at d.fire (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:2188)
    at MessagePortMain.fe (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:36:30382)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285)

**Comment by p1kmantra** [comment] 2024-03-04 10:38
> Can you please share the following log while you reproduce the issue
> 
> * F1 > Open View... > Shared
2024-03-04 16:02:57.404 [error] SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:57.651 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:57.812 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:02:58.867 [error] SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:03:01.444 [error] [uncaught exception in sharedProcess]: Unexpected token '#', "#!/bin/bas"... is not valid JSON: SyntaxError: Unexpected token '#', "#!/bin/bas"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.factory (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:102:78579)
2024-03-04 16:03:01.813 [error] [uncaught exception in sharedProcess]: Event not found: onDidChange: CodeExpectedError: Event not found: onDidChange
    at Object.listen (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:45:4960)
    at E.t (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:44:251)
    at E.q (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:4371)
    at y.value (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:43:3602)
    at d.y (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1902)
    at d.z (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:1972)
    at d.fire (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:38:2188)
    at MessagePortMain.fe (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:36:30382)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285)

**Comment by sandy081** [comment] 2024-03-04 12:19
Looks like you got corrupted `extensions.json` file. Can you please open extensions folder - `F1 > Open Extensions Folder` and share the `extensions.json` file from there?

**Comment by p1kmantra** [comment] 2024-03-04 14:43
![Screenshot 2024-03-04 8 02 58 PM](https://github.com/microsoft/vscode/assets/129663631/9499db9c-95d7-4312-b06f-180ba7f52622)


I have attached the screenshot of the extension's folder, but as you said about extensions.json file .It is not available there.

**Comment by sandy081** [comment] 2024-03-07 13:54
Can you please confirm the contents of the `extensions.json` file I asked for?

**Comment by p1kmantra** [comment] 2024-03-08 07:07
ok ,sure

#!/bin/bash
unset -v GNOME_DESKTOP_SESSION_ID
cd /opt/sqldeveloper/sqldeveloper/bin
./sqldeveloper "$@"

**Comment by sandy081** [comment] 2024-03-14 10:57
```
#!/bin/bash
unset -v GNOME_DESKTOP_SESSION_ID
cd /opt/sqldeveloper/sqldeveloper/bin
./sqldeveloper "$@"
```

Are these the contents? If so, this is not expected. I am not sure who would have written this into your file. If it is not you, you should be deleting this file and check again.

**Comment by sandy081** [comment] 2024-03-15 17:18
Closing this as no action needed

**Closed by sandy081** 2024-03-15 17:18 UTC
Labels: info-needed
