### ISSUE TITLE
Linux: opening files from FTP connection show up empty

### ISSUE THREAD

**Issue by MartinPL** [microsoft/vscode#73884] opened 2019-05-17 11:14 UTC
- VSCode Version: 1.34.0 & 1.35.0-insider
- OS Version: Antergos / Arch Linux (Linux x64 5.1.2-arch1-1-ARCH) / GNOME 

Steps to Reproduce:

1. Login to FTP on GNOME
2. Drag file to VSC

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2019-05-17 20:13
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by MartinPL** [comment] 2019-05-17 21:14
Yep, exploration don't have this problem.

**Comment by bpasero** [comment] 2019-07-01 06:21
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by MartinPL** [comment] 2019-07-24 11:25
Retested, bug still remain even with Insider.
```
Version: 1.37.0-insider
Commit: 188180bccf1f56b3368c4eb20e877238d69925b8
Date: 2019-07-24T05:28:47.848Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.2-arch1-1-ARCH
```

**Comment by MartinPL** [comment] 2019-08-02 12:13
@bpasero could you reopen this issues?

**Comment by bpasero** [comment] 2019-08-05 09:45
@MartinPL does this reproduce only when dragging dropping, or also when you open the FTP folder in VSCode? Is any FTP extension involved?

**Comment by MartinPL** [comment] 2019-08-05 10:16
In both case same result, tested on clear VSC.

Yea #78320 probably is same issues since PCmanFM may using same backend as Nautilus / GNOME Files (gvfsd)

You can easy reproduce this on newest Ubuntu.

SFTP works fine.

**Comment by bpasero** [comment] 2019-08-05 13:43
> You can easy reproduce this on newest Ubuntu.

I must ask for your help here how to set this up. This is the only chance of ever resolving this issue.

**Comment by MartinPL** [comment] 2019-08-05 17:59
Sure:
- Boot Ubuntu
- Run File / Nautilus app
- Go to Other Locations
- In footer type ftp://yourserver.com
- Press connect
https://linuxconfig.org/images/01-ftp-client-ubuntu-18.04-install.png

**Comment by bpasero** [comment] 2019-08-05 18:08
@MartinPL and then how do you open that as folder in VSCode?

**Comment by MartinPL** [comment] 2019-08-05 18:13
If you are connected to FTP you can just use Open folder, FTP folder should be in Other Locations.

**Comment by bpasero** [comment] 2019-08-06 11:43
I think I understand the issue now. Steps: see https://github.com/microsoft/vscode/issues/78364#issuecomment-518529639

The underlying issue is that we call `fs.read` with a `position` argument to instruct node to read from a certain position in the file. However, some file systems do not support this and will throw an error `ESPIPE: invalid seek, read`. One half of the bug was that we would not properly bubble up this error, so the file ended up empty. I fixed that.

The reason why this used to work is that previously we would set `position` to `null` which instructs node to simply use the current `position` in the file when reading. I do not think we have many usecases for reading from a certain position (though we do expose this as part of our file system API). Have to decide if the fix should go into the file service as general thing for every file system provider, or local to the node.js backed implementation.

**Comment by jrieken** [comment] 2019-08-06 14:34
@bpasero our internal (and proposed) api is modelled after [`pread`](https://linux.die.net/man/2/pread), we can consider adding more overloads to support [`read`](https://linux.die.net/man/2/read) or to replace `pread` with `read`. No strong feelings or experience here...

**Comment by bpasero** [comment] 2019-08-07 06:01
Pushed a fix to prefer `NULL` for `fs.read` / `fs.write` if we detect that the file position is the same. That means FTP access will only fail if we have code that requires a certain position to read/write, which we currently do not have in the text editor at least.

**Closed** 2019-08-07 06:01 UTC
Labels: bug, file-io, important

**Comment by MartinPL** [comment] 2019-08-16 10:42
@bpasero I still have this issues, this is intended?
> Version: 1.37.1
> Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
> Date: 2019-08-15T16:17:25.463Z
> Electron: 4.2.7
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Linux x64 5.2.8-arch1-1-ARCH

**Comment by bpasero** [comment] 2019-08-16 12:21
@MartinPL to clarify you do this:
* add an FTP location to Nautilus on Ubuntu
* open that folder in VSCode
* click on a file
* file shows without any content (and no error is printed)

With version 1.37.1?

**Comment by MartinPL** [comment] 2019-08-17 11:00
@bpasero yes, just tested on Ubuntu in Virtualbox.
https://i.imgur.com/IPIA44y.png

BTW. Snap edition don't show FTPs location.

**Comment by bpasero** [comment] 2019-08-17 11:18
@MartinPL ah, this fix is not yet released to our stable version. You have to use our insiders until then: 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by MartinPL** [comment] 2019-08-17 12:34
@bpasero With insiders works fine 👌

**Comment by aeschli** [comment] 2019-08-28 14:22
Set verified based on https://github.com/microsoft/vscode/issues/73884#issuecomment-522232961
