### ISSUE TITLE
Partial acceptance doesn't work for multi-line completions

### ISSUE THREAD

**Issue by bmuskalla** [microsoft/vscode#172541] opened 2023-01-26 15:46 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.75.0-insider (Universal)
Commit: 270c3b12906a88e9c67fc5ddef87be6aa3b75551

Steps to Reproduce:

1. Proposal provider with a multi-line completion
2. Partial acceptance only works on the first line

![Recording 2023-01-26 at 16 45 03](https://user-images.githubusercontent.com/316929/214881600-8573fddf-3601-4349-898f-2affa3324bd6.gif)

/cc @isidorn

**Comment by isidorn** [comment] 2023-01-26 16:11
Good catch, but duplicate of https://github.com/microsoft/vscode/issues/172162
I think we should look into fixing it in the next couple of milestones.
fyi @hediet

**Closed by isidorn** 2023-01-26 16:11 UTC
