### ISSUE TITLE
Multi-cursor cutting multiple lines does not cut final line

### ISSUE THREAD

**Issue by jmadelaine** [microsoft/vscode#65282] opened 2018-12-18 11:31 UTC
- VSCode Version: 1.30.0
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Begin with a new file.
2. Type the character '1', followed by a new line, and type the character '1' again.
3. You now have two identical lines which can be written as "1\n1" - **note, do not add an empty third line**
>1
>1

4. Highlight one of the '1' characters and press "Ctrl + Shift + L". This will highlight both characters and place two cursors in the document.
5. Press the left arrow key to deselect the characters. The cursors will now be at the start of each line.
6. Use Ctrl + X to cut the lines.

**Expected result**: both lines are cut, leaving a single empty line on the screen.
**Actual result**: the first line is cut, but the second line is copied, leaving a single '1' character on the screen.

If this test is repeated but a third empty line is added (contrary to the note in step 3), then both lines containing '1' characters are cut correctly.

This is a significant bug because many people use the multi-line cut functionality to remove unwanted lines from a document. For example:

>1server
>1server
>2server
>1server
>2server
>2server

If I wanted to remove all the servers from the list that begin with a '2' character, I could select a '2', Use the multi-select shortcut as above, click the left arrow to deselect the '2' which allows me to cut the entire row, and then press Ctrl + X. I would expect there to be no servers with the '2' prefix left in the list, but there are. I first have to put an extra empty line at the end of the document by inserting a return after the last "2server".

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment] 2020-03-09 10:26
I believe this has been fixed in the meantime, because I can no longer reproduce.

**Closed by alexdima** 2020-03-09 10:26 UTC
Labels: bug, editor-commands, editor-multicursor
