### ISSUE TITLE
TCIM.Zhuyin Keyboard layout: Funny keybindings for letter based combinations (copy, paste, undo, etc.)

### ISSUE THREAD

**Issue by kit1858644** [Microsoft/vscode#28237] opened 2017-06-08 13:38 UTC
- VSCode Version: 1.12 
- OS Version: macOS Sierra

Steps to Reproduce:

I'm start using vs code, but I find the copy, paste shortcut in vscode is crazy.

Normally the copy shortcut is cmd+c, but in my vscode the shortcut is Control+alt+cmd+C

please help!!

<a href="http://s165.photobucket.com/user/kit1858644/media/Screen%20Shot_zpsvuhyux64.png.html" target="_blank"><img src="http://i165.photobucket.com/albums/u60/kit1858644/Screen%20Shot_zpsvuhyux64.png" border="0" alt="shortcut photo Screen Shot_zpsvuhyux64.png"/></a>

**Comment by jens1o** [comment] 2017-06-08 17:33
You can change that keybinding.

**Comment by kit1858644** [comment] 2017-06-09 00:58
I trird, but it don't work.

**Comment by sandy081** [comment] 2017-06-09 09:02
@kit1858644 By any chance you have customised these keybindings? Can you please open Keyboard Shortcuts and see the keybindings for above actions? Check if they are Default or User defined

![image](https://user-images.githubusercontent.com/10746682/26968660-18f32be4-4d03-11e7-84a5-92bbc6e20287.png)

**Comment by kit1858644** [comment] 2017-06-09 14:32
@sandy081 It doesn't have User setting, but it have two default setting, how can I delete the second 
 one default setting? 

Thanks your help.

<a href="http://s165.photobucket.com/user/kit1858644/media/Screen%20Shot%202017-06-09%20at%2010.24.41%20PM_zpsduwsmi61.png.html" target="_blank"><img src="http://i165.photobucket.com/albums/u60/kit1858644/Screen%20Shot%202017-06-09%20at%2010.24.41%20PM_zpsduwsmi61.png" border="0" alt="Keybuild photo Screen Shot 2017-06-09 at 10.24.41 PM_zpsduwsmi61.png"/></a>

**Comment by sandy081** [comment] 2017-06-09 15:15
@kit1858644 Thats very strange.. Can you open keybindings.json file, you can see the link just below the search box. Please provide us the Default keybindings (content in the left side editor).

Thanks

**Comment by hungys** [comment] 2017-06-11 15:23
This may be related: #28046 

cc @bpasero @alexandrudima

**Comment by alexandrudima** [comment] 2017-06-12 06:15
@kit1858644 Can you please tell us the list of extensions you have installed. One of the extensions you have installed is binding `ctrl+alt+cmd+C` to copy. Since we allow extensions to override built-in keybindings, the `ctrl+alt+cmd+C` keybinding is given preference and displayed in the `Edit` menu.

**Comment by hungys** [comment] 2017-06-12 06:24
@alexandrudima 

If an extension binds a new keyboard shortcuts for copy, can we **ALWAYS** see this in contributions section of the extension? If so, going through all the contributions may be helpful for judging if any extension is the root cause.

Like Sublime Text Keymap,

![](http://i.imgur.com/5H79ojx.png)

**Comment by alexandrudima** [comment] 2017-06-12 06:26
@hungys  Yes, the Sublime Text Keymap is in no way special. Any extension can contribute keybindings and any extension that does so will show the keybindings it contributes under the "Contributions" section.

**Comment by hungys** [comment] 2017-06-12 06:31
@alexandrudima 

Thanks, that makes sense.
And I have confirmed that all my installed extensions don't have keybindings for copy/paste :)

**Comment by alexandrudima** [comment] 2017-06-12 06:34
@hungys Not that I think more about it, this might also be caused by our mapping of default keybindings based on keyboard layouts. This might also depend on what keyboard layout you have activated and what OSX returns in the `TISCopyCurrentKeyboardInputSource` call we do. Which keyboard layouts do you regularly use?

When the issue occurs, could you  open an editor and run `F1 > Developer: Inspect Key Mappings`.

**Comment by hungys** [comment] 2017-06-12 06:39
@alexandrudima 

I'll try it next time. (Actually it didn't occur during these two days...)

**Comment by alexandrudima** [comment] 2017-06-28 09:39
I will close this issue for now since this might be caused by a specific keyboard layout, which we don't know. 

@hungys @kit1858644 if you find out what keyboard layout caused this, please let us know and attach the output of `Inspect Key Mappings`.

**Comment by hungys** [comment] 2017-06-28 10:28
@alexandrudima 

Luckily... the issue finally occurred again when you closed the issue LOL

Here are the dumped key mappings: http://codepad.org/Ff8Kmwzs

```
Layout info:
{
	"id": "com.apple.keylayout.US",
	"lang": "en"
}
isUSStandard: true
```

I've not restarted it yet, tell me what else you may need.

**Comment by alexandrudima** [comment] 2017-06-28 11:00
@hungys 

Do you have other keyboard layouts installed on your system besides the native US keyboard layout? Do you constantly switch between those keyboard layouts? (even when focused outside of VS Code?)

On OSX we react to keyboard layout changes and adjust our keybindings based on the current keyboard layout.

I am thinking you have a keyboard layout that produces `c` when pressing `C` and also when pressing `AltGr+C`; `z` when pressing `Z` and also when pressing `AltGr+Z`, which leads us to "double up" all our keybindings from `cmd+c` to also `cmd+ctrl+alt+c`, etc.

**Comment by hungys** [comment] 2017-06-28 11:15
@alexandrudima 

I think I have two input methods on my macOS. Here is another keyboard layout detected by VS Code. I used this IME for typing Chinese. (mostly outside of VS Code)

http://dpaste.com/11F1363

```
Layout info:
{
	"id": "com.apple.inputmethod.TCIM.Zhuyin",
	"lang": "zh-Hant"
}
isUSStandard: false
```

> I am thinking you have a keyboard layout that produces c when pressing C and also when pressing AltGr+C; z when pressing Z and also when pressing AltGr+Z, which leads us to "double up" all our keybindings from cmd+c to also cmd+ctrl+alt+c, etc.

I'm not sure if this really happened with Chinese IME?

**Comment by alexandrudima** [comment] 2017-06-28 12:12
@hungys Yes, that's it! Thanks for getting back to me:

e.g.

```
	"KeyC": {
		"value": "ㄏ",
		"valueIsDeadKey": false,
		"withShift": "C",
		"withShiftIsDeadKey": false,
		"withAltGr": "c",
		"withAltGrIsDeadKey": false,
		"withShiftAltGr": "C",
		"withShiftAltGrIsDeadKey": false
	}
```

Our default keybinding for copy is `cmd+c`. We then look at this information and see that on this keyboard layout `c` is producible via `AltGr+[KeyC]` (`ctrl+alt+[KeyC]`). We then proceed to "translate" the default keybinding `cmd+c` to `cmd+ctrl+alt+[KeyC]`.

**Closed** 2017-06-28 13:21 UTC
Labels: bug, keyboard-layout

**Comment by hungys** [comment] 2017-06-28 13:47
@alexandrudima 

Finally... hope the fix works! 💯 

By the way, TCIM.Zhuyin may not be the only case. There is also something like TCIM.Pinyin, and I believe OP was using input methods under SCIM. (TC for Traditional Chinese; SC for Simplified Chinese)

**Comment by alexandrudima** [comment] 2017-06-28 15:27
@hungys Yes, tomorrow's Insiders should contain the fix and `keyboard.dispatch: "keyCode"` should not be needed anymore.

The fix is not specific to a single keyboard layout, it targets all keyboard layouts where latin letters are not produced without modifiers, and with the information I got from you (thanks again), I could write a test to ensure we don't regress.
