### ISSUE TITLE
Freeze when fjfj -> jfjf

### ISSUE THREAD

**Issue by Maingron** [microsoft/vscode#91807] opened 2020-02-29 10:45 UTC
- VSCode Version: 1.42.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. `ctrl` + `n` to open empty document
2. type f and j for about 60 characters, begin with the f and stop with the j
3. `Enter` to create a new line
3. type f and j again, but start with j this time
4. VScode should crash or freeze

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/47825439/75605995-bdb6ae80-5ae8-11ea-8b56-52cfd7ee4e83.png)

**Comment by roblourens** [comment] 2020-03-02 05:54
So just to be sure, this still happens when you start with `--disable-extensions`?

**Comment by Maingron** [comment] 2020-03-02 12:30
Yes, still happens with `--disable-extensions`. Also asked some friends of mine and also happened to them, though they probably didn't disable the extensions.

**Comment by Maingron** [comment] 2020-03-02 12:49
[Vscode Fjfj - Jfjf-1 small.zip](https://github.com/microsoft/vscode/files/4275426/Vscode.Fjfj.-.Jfjf-1.small.zip)
Here a video clip of it in action. I shortened some waiting times though.

**Comment by Maingron** [comment] 2020-03-12 06:51
@roblourens will you work on this?

**Comment by roblourens** [comment] 2020-03-29 17:48
Sorry for the slow response, but I can't reproduce it - so it specifically happens with `fjfj` but not other letters...?

**Comment by Maingron** [comment] 2020-03-29 18:44
No problem. Happens with all letters I've tried.  Also just tried it on another PC - Same over there.

**Comment by roblourens** [comment] 2020-03-30 04:56
So the problem is just that if you type for a few seconds, vscode crashes? Does it ever not crash? :)

Is there some process using high cpu or memory when this is going on?

**Comment by Maingron** [comment] 2020-03-30 06:58
No, I can use Code pretty normal, unless I'm doing the two-letter thing. 
Neither CPU nor Ram are close to their limits - just a bit of software idling in the background.

**Comment by roblourens** [comment] 2020-04-02 03:31
Can you run `code --status` when this happens to check if any process has lots of activity?

Or see the steps here to see if you can get a dump

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows

**Comment by Maingron** [comment] 2020-04-02 06:26
Hope this helps. Though the programm doesn't really crash but rather go to a not responding-status. Don't know if that might be a problem. Though it seemed like it was a bit harder to get than usually.
```LOG
Version:          Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS Version:       Windows_NT x64 10.0.18363
CPUs:             AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3943)
Memory (System):  47.93GB (34.81GB free)
VM:               36%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    1       84   21924  code main
    0       66    5552     shared-process
    0       12    7948     electron-crash-reporter
    0       73   22064     gpu-process
    7      182   22316     window (ΓùÅ Untitled-3 - Visual Studio Code)
    0       62    8292       extensionHost

C:\Users\robin>
```
![grafik](https://user-images.githubusercontent.com/47825439/78216367-f7991d00-74b9-11ea-8326-bbceb9a075ba.png)
[DebugDiag Logs.zip](https://github.com/microsoft/vscode/files/4419204/DebugDiag.Logs.zip)

**Comment by Maingron** [comment] 2020-04-02 06:28
Also just updated to 1.43.2 after the last comment and the bug is still there.

**Comment by roblourens** [comment] 2020-04-02 15:39
@deepak1556 Any idea what might be going on? I'm stumped

**Comment by pkruk2** [comment] 2020-04-02 16:09
In my case, when I started writing in the second line, one code.exe process started to display high cpu usage. Normally it's around 0, when code.exe was frozen, it was 15% once, and another time 30% (as shown by process explorer from sysinternals).

![obraz](https://user-images.githubusercontent.com/34373523/78270364-04922c80-750b-11ea-9d85-f5ed9d3aa878.png)

I have attached to the process:

![obraz](https://user-images.githubusercontent.com/34373523/78270584-4c18b880-750b-11ea-9891-9d6f2cc957ef.png)

![obraz](https://user-images.githubusercontent.com/34373523/78271863-fcd38780-750c-11ea-9dfd-4d2ebb22972d.png)

![obraz](https://user-images.githubusercontent.com/34373523/78271917-11178480-750d-11ea-843c-afbfdd3369d9.png)

**Comment by deepak1556** [comment] 2020-04-03 03:20
I am able to repro it on macOS as well, attaching the profile 
[keypress-freeze-91807.zip](https://github.com/microsoft/vscode/files/4424860/keypress-freeze-91807.zip)

The issue is also seen on monaco editor with both firefox and chrome, so not an issue specific to the runtime, looping in @alexdima

**Comment by roblourens** [comment] 2020-04-03 21:45
Any other repro steps @deepak1556? I still can't repro it and thought it sounded crazy 😁

**Comment by deepak1556** [comment] 2020-04-03 22:17
Yeah its not specific to these characters, but just need repeated fast keypress of a sequence of characters over multi-line, so you can go `ertertfdgfdg` or anything like that, at some point the rendering should freeze on the second line. I was always able to hit this issue when the first line has atleast 70 characters.

**Comment by pkruk2** [comment] 2020-04-06 08:23
Is there vscode with debug symbols?

**Comment by alexdima** [comment] 2020-04-07 09:34
@jrieken I was not able to reproduce, but it has nothing to do with the typing itself, it has to do with completions scoring. I was able to open the CPU profile from @deepak1556 and it looks like fuzzy scoring in suggestions (presumambly due to word suggestions) is the culprit:

![image](https://user-images.githubusercontent.com/5047891/78653572-9e6b2800-78c3-11ea-8b52-17b6f15440fd.png)

**Comment by jrieken** [comment] 2020-04-08 08:44
We have bailout logic that prevents "endless" search but that only works when there are matches. Since this sample never yields a result we search for a long time (zig-zagging a table) and there is now a new check that we never get into this. This issue is fixed now but some debt has been accumulated here and some part should be revisited one day.

**Closed by jrieken** 2020-04-08 08:45 UTC
Labels: bug, freeze-slow-crash, suggest
