### ISSUE TITLE
Folder not expanding in file explorer

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#76031] opened 2019-06-24 17:53 UTC
- VSCode Version: 1.35.1
- OS Version: Windows 10

Steps to Reproduce:

I was working with this project: https://github.com/luabud/tweeter3. Then I created a file called 2.1_test.py in the **tweeter** folder to try to reproduce a bug with the Python extension. Then I renamed it to test_2.py and now I can't expand that folder anymore. 

Does this issue occur when all extensions are disabled?: Yes, it does

![VSCodeBugs](https://user-images.githubusercontent.com/45497113/60040565-2bfbc500-966e-11e9-8b3f-48fe0d5a3128.gif)

**Comment by isidorn** [comment] 2019-06-25 15:09
I can not reproduce.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, if you F1 > developer tools > debug console do you see some errors?

**Comment by luabud** [comment] 2019-06-25 22:51
I haven't seen that in VS Code Insiders. I'll let you know if it happens. Feel free to close this if you want, and I'll reopen if I experience it there. Thanks!

**Comment by isidorn** [comment] 2019-06-26 07:48
Let's keep it open for now and we can close later. Thank you

**Comment by RafaelLeonhardt** [comment] 2019-07-01 12:20
Same problem here after update to the latest version.

**Comment by isidorn** [comment] 2019-07-01 13:28
@luabud can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes. If you f1 > developer tools > debug console do you see some errors
Do you have exact steps to reproduce this?

**Comment by webdjoe** [comment] 2019-07-08 00:13
I am having the same issue after the latest update.  After I refresh as indicated in @RafaelLeonhardt it appears, but only when the folder is expanded with no contents.  I do not see any errors in any of the logs or in the developer console.  It is working correctly in the insiders edition

**Comment by MarkKharitonov** [comment] 2019-07-09 19:16
I have the same issue too after I have upgraded to the latest. Using powershell extension.

**Comment by iansan5653** [comment] 2019-07-31 13:08
Bringing in info from #77821 -
I'm experiencing the same thing with a folder that only has Python modules installed with `pip` editable mode. I'm using a workspace and can still access the files that don't appear when using the breadcrumbs. Issue occurs without extensions.

Version: 1.37.0-insider (user setup)
Commit: e1d3dd5
Date: 2019-07-23T05:23:48.960Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by iansan5653** [comment] 2019-07-31 13:16
Today, the problem didn't occur until I <kbd>ctrl</kbd>+clicked on an `import` statement that was importing one of the four modules in the folder that has the issue. When I did that, the module's file opened as normal, but once I closed the file I was no longer able to see the folder contents and <kbd>ctrl</kbd>+clicking on that same import statement does nothing. 

Based on that, I'd say the issue was caused by the Python extension. However I reloaded with extensions disabled and the problem persisted. Nothing appears in the console or in any of the Output views.

**Comment by luabud** [comment] 2019-07-31 13:27
@iansan5653 interesting, so it seems to be a problem caused when navigating to files. I don't think it's caused only by the Python extension since it seems to have happened with the PowerShell extension as well. But I opened an [issue ](https://github.com/microsoft/vscode-python/issues/6789) in the Python extension repo so they can investigate what may be causing this.

**Comment by kaidokert** [comment] 2019-08-24 00:39
I'm getting the same issue, reproducibly with mostly C++ env, no Python or Powershell extensions installed. I'm clicking on build output ( which is produced through $gcc problemMatcher ), random header file, it does open the file but the folder does not expand, and becomes unexpandable, similar to #75340 gif. Clicking "Refresh explorer" does make the tree node expandable again.

What tracing info can i provide ?

**Comment by isidorn** [comment] 2019-08-26 07:52
@kaidokert can you reproduce with vscode insiders (since we pushed a potential fix for this)
https://code.visualstudio.com/insiders/

**Closed** 2019-09-02 07:52 UTC
Labels: file-explorer, needs more info
