### ISSUE TITLE
Request: Open remote folder via SSH

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#27423] opened 2017-05-29 09:29 UTC
It would be very nice if VS Code could open a remote folder, found via SSH connection. 

Currently I have to use linux Samba share, that is mounted in Windows and it is rather slow - especially for searching and quick opening files. 

It would also resolve problems with versioning, because linux symlinks don't work on Windows (and windows symlinks don't help), changes checking is slow etc.

**Comment by bpasero** [comment] 2017-05-29 12:18
There are probably duplicates.

**Comment by pwwang** [comment] 2017-06-05 18:09
+1

**Comment by PunchyRascal** [comment] 2017-06-05 19:24
I searched the issues, but found nothing similar, but could have overlooked it.

**Comment by rumatakira** [comment] 2017-06-09 02:58
+1

**Comment by booooh** [comment] 2017-08-30 17:02
+1

**Comment by uberthought** [comment] 2017-09-02 16:05
+1

**Comment by jpldev** [comment] 2017-09-13 13:09
+1

**Comment by skunchamwar** [comment] 2017-09-16 12:38
+1

**Comment by jcooklin** [comment] 2017-09-19 23:47
+1

**Comment by nagarakesh4** [comment] 2017-09-26 22:30
+1

**Comment by tanakh** [comment] 2017-09-27 13:20
+1

**Comment by PunchyRascal** [comment] 2017-09-27 13:41
Guys read the guidelines for upvoting issues: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by ofanidariyan** [comment] 2017-10-10 04:08
+1

**Comment by ewright3** [comment] 2017-10-13 16:55
+1

**Comment by iamlaobie** [comment] 2017-10-17 10:21
+1

**Comment by JandunCN** [comment] 2017-10-19 04:39
+1

**Comment by vsoaresz** [comment] 2017-11-13 13:06
+1

**Comment by PunchyRascal** [comment] 2017-11-13 13:28
Use thumbs up on the original post, do not add +1 comments

**Comment by visitantz** [comment] 2017-11-17 15:11
Exactly what needed, now my work flow is open a vscode on VMware Lubuntu SSH connection.

**Comment by sourcepirate** [comment] 2017-12-01 12:01
+1

**Comment by PatrikNordberg** [comment] 2017-12-04 12:09
Any progress on this feature?
I would really like this as well.
Now I use SFTP Net Drive to connect my remote folder as a local drive.
Would be much better if VSCode could handle this internally.

**Comment by PunchyRascal** [comment] 2017-12-04 12:16
Maybe if you can, try setting up your remote drive as a NFS share - it is
faster than samba (if that's your case).

**Comment by devmckeon** [comment] 2017-12-04 17:18
(this is not in response to anyone or any reply, just a suggestion of perspective) 

I think we can all agree that there are always ways to do this from outside vscode. However, opening remote folders over ssh is a very useful feature for a light-IDE slash text-editor. I've heard from colleagues that I've tried to convince to use Code, who've said that they simply would not try anything that didn't have such a feature. I think it's wise to accept that this is a productivity boosting feature that many people feel is essential, and that it's unwise to write-off those users with rationalizations of the form: "that should not be your workflow", or "that's not the way to do it right".  Perhaps in a different world, everybody would simply be a command line natural, and be able to mount remote drives as easy as changing directories.

Also, I would like to shrink the list of things Atom does that Code does not. =) And this remains of the things I miss from other editors.

**Comment by Ginurx** [comment] 2017-12-08 03:10
+1

**Comment by kvn1351** [comment] 2018-02-10 22:32
+1

**Comment by firelizzard18** [comment] 2018-02-26 04:49
@kvn1351, do not +1; doing so is useless. Thumbs up the initial comment/issue description.

There was a similar request to be able to remotely edit files via SSH (#23076) that for some reason was closed as a duplicate of allow reading from stdin (#7320/#6161) even though those issues really don't solve the edit-via-SSH issue.

**Comment by GustavoOS** [comment] 2018-03-09 16:34
It would be very nice if in addition to that you could use the integrated terminal as a terminal to remote computer, as well as the git integration and other resources behaving exactly as in remote. This way remote development would become much faster, with huge productivity gains.

**Comment by benlindsay** [comment] 2018-06-04 19:39
Any progress on this? Remote coding and compiling on a research cluster is a big part of my workflow. Using sshfs to mount folders I can do the editing part ok, but it would be nice not to have to run that extra command. Additionally, it would be great if I could point VSCode to a remote compiler and debugger to build, run, and debug my code from within the VSCode environment.

**Comment by firelizzard18** [comment] 2018-06-05 02:50
@benlindsay The latest major update to VSCode (I believe 1.23) added a FileSystemProvider API (or something like that). With this API, issues like this one and #44378 can be implemented with extensions.

Unfortunately, to date, I have not found an extension that does a good job of this. Given that this API has not been available for long, I expect better things in the future.

**Comment by firelizzard18** [comment] 2018-06-05 02:53
@jrieken This issue should be closed as an extension-candidate, now that the file system provider api has been shipped

**Comment by jrieken** [comment] 2018-06-05 07:35
True story - there is now API that allows extensions to add a different file system to VS Code. There is also some impressive extension out there, eg. https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace.

**Closed** 2018-06-05 07:36 UTC
Labels: *extension-candidate, feature-request, remote

**Comment by mjbvz** [comment] 2019-05-02 19:03
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
