### ISSUE TITLE
VS Code shows cryptic error message Error: net::ERR_NO_SUPPORTED_PROXIES when it cannot resolve HTTP proxy DNS name

### ISSUE THREAD

**Issue by vbrozik** [microsoft/vscode#97480] opened 2020-05-11 09:22 UTC
Issue Type: <b>Bug</b>

After the upgrade all the attempts to check for VS Code updates show this error message:

net::ERR_NO_SUPPORTED_PROXIES

------ This is in the main log:
[2020-05-11 11:12:43.362] [main] [info] update#setState checking for updates
[2020-05-11 11:12:43.387] [main] [error] Error: net::ERR_NO_SUPPORTED_PROXIES
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[2020-05-11 11:12:43.387] [main] [info] update#setState idle

Later I realized that in Windows environment I have the http_proxy variable set to a DNS name which is not resolvable. VS Code should show a more clear error message like for example:
a) Error: Cannot resolve HTTP proxy example-proxy.domain.com to an IP address
b) Error: Cannot connect to HTTP proxy example-proxy.domain.com:8080

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2701)|
|Memory (System)|15.88GB (7.52GB free)|
|VM|36%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
LogFileHighlighter|emi|2.8.0
cisco|jam|1.8.1
eml|lei|0.4.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-markdownlint|Dav|0.35.1
python|ms-|2020.4.76186
bash-debug|rog|0.3.7
shellcheck|tim|0.9.0

</details>

**Comment by vbrozik** [comment] 2020-05-11 10:41
After further investigation I realized that the main problem is in the cryptic message:
Error: net::ERR_NO_SUPPORTED_PROXIES

I realized that something permanently set the Windows environment variable http_proxy. It looks like VS Code versions before 1.45 did not use this environment variable.

I am going to edit the Issue.

**Comment by falco467** [comment] 2020-05-15 08:13
I have the same error, but with a HTTP_PROXY value, which is accepted by most other command line tools (like curl, maven, git): "http://proxyname:8080/"
VS Code can not parse the proxy if the URL has a trailing slash, if I change it to "http://proxyname:8080" without a trailing slash VS Code will accept the proxy and work again.

Maybe this could be changed to accept the trailing slash like many other tools do?

**Comment by hegdevishwa** [comment] 2020-06-12 11:30
I still have this issue

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by chrmarti** [comment] 2020-06-15 07:21
The trailing slash issue was fixed with #97885.

@hegdevishwa Do you have the `http.proxy` VS Code setting or any of the `HTTP_PROXY` or `HTTPS_PROXY` environment variables set?

**Comment by hegdevishwa** [comment] 2020-06-15 07:59
@chrmarti Yes the `http.proxy`  set in VS code with a trailing slash. If I remove it, it works but doesn't work with it.

**Comment by chrmarti** [comment] 2020-06-15 08:23
Ack, this is fixed in 1.46. (Only now realize that you are on 1.45 which does not have the fix.)

Closing as duplicate of #97885

**Closed by chrmarti** 2020-06-15 08:23 UTC
Labels: bug, needs more info, proxy

**Comment by hegdevishwa** [comment] 2020-06-15 08:27
@chrmarti Apologies, I didn't realise that. I'll update it. Thank you!
