### ISSUE TITLE
Completely silent updates

### ISSUE THREAD

**Issue by RedDragonWebDesign** [microsoft/vscode#137128] opened 2021-11-13 17:08 UTC
An option for completely silent and automatic VS Code updates. Instead of needing to click a bunch of popups in the bottom right corner.

- For the first popup that says "update is available", automatically download and install the update.
- For the second popup that says "restart visual studio code to apply the latest update", automatically assume "later". When the user restarts VS Code, the update will install.
- Don't pop up the release notes in a new tab after updating.

When opening a new window, prevent these popups as well, which tend to pop up again every time you open a new window.

Trigger this behavior by selecting Settings -> Update: Mode > silent and automatic.

![image](https://user-images.githubusercontent.com/43397938/141652570-033dffde-9637-4ca5-9d59-c42c15d9cb4a.png)

**Comment by matkoniecz** [comment] 2021-11-13 20:04
duplicate of #9539 found by https://github.com/microsoft/vscode/issues?q=silent+updates+is%3Aopen

**Closed** 2021-11-13 20:56 UTC
Labels: *duplicate
