### ISSUE TITLE
Wayland interface not responding after changing folder

### ISSUE THREAD

**Issue by DasVoelkel** [microsoft/vscode#92276] opened 2020-03-09 15:57 UTC
![1583748184_grim](https://user-images.githubusercontent.com/18036573/76202626-6eadff00-61f5-11ea-9be2-0a5bab36fa70.png)
.. apparently the copy button does not work either.
running with wayland  / sway

Reproduce:
Changing folder. Everytime after changing the folder to another project folder it will stop responding to input  like so:

As far as I have tried it only happened with extensions off ( first submitted bc i thought it was aused b extensions, but later found out it happened without any as well)

Sometimes the terminal doesn't take any input or Terminal -> open new terminal, just straight up does not open a terminal.
Terminal -> run task, does also not show any tasks that can be run
I have to select out and back in to get it to work again.

**Comment by weinand** [comment] 2020-03-09 16:11
Please find the extension that causes this.

**Comment by DasVoelkel** [comment] 2020-03-09 16:14
Nevermind, it happened without any extension on too !

**Comment by bpasero** [comment] 2020-03-10 06:55
I think this is a duplicate of https://github.com/microsoft/vscode/issues/89370 or https://github.com/microsoft/vscode/issues/84754

**Closed** 2020-03-10 06:55 UTC
Labels: *duplicate
