### ISSUE TITLE
Support renaming references if file is renamed

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#148224] opened 2022-04-26 23:44 UTC
Testing #147738

This isn't a bug, but the current behavior is that renaming references updates all references across all files and renames the file itself. Based on that it would be nice if renaming files updates all references as well.

**Comment by mjbvz** [comment] 2022-04-30 21:14
Duplicate of #148146

**Closed by mjbvz** 2022-04-30 21:14 UTC
