### ISSUE TITLE
Panel can have lots of `...`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162006] opened 2022-09-27 16:02 UTC
Testing #161802

1. Open a panel view
2. Hide the views specific to that panel 
3. Then hide the panel controls (such as `close panel`)

**Bug**

There are now two `...` items next to each other in the panel header:

![Screen Shot 2022-09-27 at 8 59 31 AM](https://user-images.githubusercontent.com/12821956/192576897-5972c33c-0c76-4319-8d23-1ff972080374.png)

These two have very similar names when you hover over them so it's difficult to tell which one is which :

![Screen Shot 2022-09-27 at 9 00 11 AM](https://user-images.githubusercontent.com/12821956/192576975-dee3d089-2fb0-45e7-ae50-8d80e8a8e0d9.png)

![Screen Shot 2022-09-27 at 9 00 15 AM](https://user-images.githubusercontent.com/12821956/192576983-0cb8b12b-8716-45b3-8a88-f30add920d15.png)

**Comment by mjbvz** [comment] 2022-09-27 16:08
Would be helped by #147903

However I think we should also have clearer names when you hover over the `...`

**Comment by Tyriar** [comment] 2022-09-27 20:15
Also:

![image](https://user-images.githubusercontent.com/2193314/192626354-0bafaaa1-5eae-41e9-8617-c19ed287b0d6.png)

Could we consolidate them in a single menu with a separator?

cc @sbatten @daviddossett

**Comment by jrieken** [comment] 2022-09-28 08:54
Yeah, I believe the underlying issue is that two toolbars are being used here.

**Comment by sandy081** [comment] 2022-09-28 14:54
Actions are nicely overflowing into `...` sub menu when hidden in the side bar. I cannot reproduce it in the panel though. In views world, `ViewContainerTitleContext` and `ViewTitleContext` menus are used for secondary actions. I do not know how the hidden actions are moved into secondary actions, @jrieken Can you use these menus when hiding the primary actions? Is there something I have to adopt for this to happen?

**Comment by jrieken** [comment] 2022-09-28 15:24
Yeah, sorry I was confused. This is just one toolbar widget but it seems that there are simply two `...` entries. I see the same and I don't believe this is related to hiding but to how views and view container commands are getting merged

<img width="1136" alt="Screenshot 2022-09-28 at 17 24 05" src="https://user-images.githubusercontent.com/1794099/192819805-8877a000-39ea-476a-abf5-06e2cbff26cd.png">

**Comment by jrieken** [comment] 2022-09-28 15:28
Let's keep as stretch for September but this isn't a real new issue

**Comment by jrieken** [comment] 2022-09-29 12:17
> Yeah, sorry I was confused.

I was really confused. So, for the bottom panel there are two toolbars are simply rendered next to each other... I think it's worth merging them into one. 

<img width="394" alt="Screenshot 2022-09-29 at 14 09 57" src="https://user-images.githubusercontent.com/1794099/193027684-30998fbc-7795-4e7c-a698-eac3fb211e9e.png">


@sandy081 for now I think it's best to disable hiding for the global actions menu but we might want to revisit this later. Also, for the GHPR extension there is something off

**Comment by jrieken** [comment] 2022-09-29 15:37
For panels I have pushed a fixed and I have extracted https://github.com/microsoft/vscode/issues/162006#issuecomment-1259998688 into a separate issue because it seems unrelated to hiding menus and panels.

**Closed by jrieken** 2022-09-29 15:37 UTC
Labels: bug, menus
