### ISSUE TITLE
Allow extensions to add new entries to the activity bar

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#23930] opened 2017-04-05 11:42 UTC
I'm moving from Sublime Text and one of the things I miss is a project management feature. The [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension seems to do the trick but it would be nice if it could be integrated into the activity bar.

Either that or implement a built-in project management feature into the Activity bar, if, for me reason, you don't want to allow extensions access to the Activity bar.

What do you guys think?

**Comment by Tyriar** [comment] 2017-04-05 18:23
Duplicate of https://github.com/Microsoft/vscode/issues/12163, it's currently a preview API.

**Closed by Tyriar** 2017-04-05 18:23 UTC
