### ISSUE TITLE
Invalid terminal shutdown process

### ISSUE THREAD

**Issue by abintion-bai** [microsoft/vscode#181868] opened 2023-05-09 08:02 UTC
Type: <b>Bug</b>

Mac operating system version 1.78, when a process is running, kill the process in the terminal window closes the terminal window, but the background process is still running. Whether using the shortcut key (control+c) or clicking on the kill terminal in the operation bar is invalid, it seems that VScode terminal termination is invalid。

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:11:00.813Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 91405d50-8225-4eb2-b833-8033c8c072c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
package-json|pac|1.0.3
volar|Vue|1.6.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by abintion-bai** [comment] 2023-05-09 08:16
Reduce the version to March

**Comment by meganrogge** [comment] 2023-05-09 13:19
assuming you're using a remote window? if so, duplicate of https://github.com/microsoft/vscode-remote-release/issues/7642

**Closed by meganrogge** 2023-05-09 13:19 UTC
