### ISSUE TITLE
Make relative paths from build output clickable in the terminal

### ISSUE THREAD

**Issue by GrandChris** [microsoft/vscode#110014] opened 2020-11-05 11:57 UTC
If a relative path within the terminal starts from the root directory, you can click on it and open the corresponding file.
Using CMake with Ninja and GCC uses relative paths but starts in the "./build" directory. The problemMatcher will still work if you use it like this

``` json
 {
            "label": "Build",
            "type": "shell",
            "command": "cmake --build .",
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": [
                    "relative"
                ]
        },
```
or this
``` json
 {
            "label": "Build",
            "type": "shell",
            "command": "cmake --build ./build",
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}/build"
                ]
        },
```
but clicking the paths directly inside the terminal does not work.

```
../source/Main/main.cpp: In function 'int main()':
../source/Main/main.cpp:27:13: error: 'fuu' was not declared in this scope; did you mean 'fuu2'?
   27 |     int i = fuu;
      |             ^~~
      |             fuu2
```

It would be really nice to be able to click relative paths from a build task output even if the build location is not the root directory (build location as specified in the build task).

**Comment by alexr00** [comment] 2020-11-09 14:19
duplicate of https://github.com/microsoft/vscode/issues/58980

**Closed by alexr00** 2020-11-09 14:19 UTC
Labels: feature-request, tasks

**Comment by GrandChris** [comment] 2020-11-15 16:13
Since this does not make it into the VSCode repository, I've create an extension for this behavior, I'll leave it here, if someone has the same problem and somehow finds this issue.  
[https://marketplace.visualstudio.com/items?itemName=GrandChris.just-let-me-click-this-freaking-paths](https://marketplace.visualstudio.com/items?itemName=GrandChris.just-let-me-click-this-freaking-paths)
