### ISSUE TITLE
Allow multiple extensions to be installed/uninstalled through the CLI

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6368] opened 2016-05-14 01:47 UTC
By the looks of the code this is partially implemented, not sure if it's just incomplete or a bug.

Expected syntax:

```bash
code --install-extension ext1 ext2
```

**Comment by joaomoreno** [comment] 2016-05-24 08:52
Duplicate of #6730.

**Comment by joaomoreno** [comment] 2016-05-24 08:53
At best, we could implement it as 

`code --install-extension "ext1 ext2"`

Since parameterised arguments only take one parameter.

**Comment by Tyriar** [comment] 2016-05-24 21:38
We could make it a boolean flag and all other args are the extensions?

**Comment by Tyriar** [comment] 2016-05-24 21:39
Reopening as we should be able to improve the experience over adding --install/uninstall-extension multiple times

**Comment by joaomoreno** [comment] 2016-05-25 07:20
If so, what should this do?

```
--install-extension foo --uninstall-extension bar
```

Should it install the extensions `foo`, `--uninstall-extension` and `bar`?

**Comment by Tyriar** [comment] 2016-05-25 17:03
I was thinking similar to how npm works: `npm install foo uninstall`. Requiring `--install-extension` multiple times is so verbose.

**Comment by joaomoreno** [comment] 2016-05-25 20:08
Could work, but I will simply close this. We enabled this so people can automate installations, this is not the usual way to install an extension; the product UI is for that. If someone wants to install multiple extensions, they can still do it.

**Closed by joaomoreno** 2016-05-25 20:08 UTC
Labels: duplicate, extensions, feature-request

**Comment by Tyriar** [comment] 2016-05-25 20:29
K sounds good, I have already done [the automation I wanted to do](https://github.com/Tyriar/dotfiles/blob/master/modules/vscode/install_extensions.sh), just waiting on https://github.com/Microsoft/vscode/pull/6366 so it doesn't error out
