### ISSUE TITLE
Minimap keeps disappearing

### ISSUE THREAD

**Issue by jellymann** [microsoft/vscode#116060] opened 2021-02-07 20:56 UTC
Issue Type: <b>Bug</b>

No idea how it started happening. Everything was fine and now all of a sudden my minimap is gone. I can bring it back by toggling it off and on, but then as soon as I switch to another file it is gone again.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.35GB free)|
|Process Argv|--crash-reporter-id acedcadc-a884-4359-95e3-f31b91b81fac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|4.0.1
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-eslint|dba|2.1.14
vscode-wasm|dts|1.3.1
csharp|ms-|1.23.9
vscode-edge-devtools|ms-|1.1.3
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
atom-keybindings|ms-|3.0.9
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
powershell|ms-|2020.6.0
debugger-for-edge|msj|1.0.15
vetur|oct|0.32.0
indent-rainbow|ode|7.5.0
slim|sia|0.1.2
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.28.0

(24 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by spmeesseman** [comment] 2021-02-08 02:42
same here.  i thought i was going crazy lol

**Comment by GibsDev** [comment] 2021-02-08 03:29
I'm also experiencing this issue

**Comment by sarimarton** [comment] 2021-02-08 05:10
Confirmed.

**Comment by godliked** [comment] 2021-02-08 07:27
same

Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by alexdima** [comment] 2021-02-08 14:14
Does this reproduce when disabling all extensions?

**Comment by imdude001** [comment] 2021-02-08 18:40
Same issue here.

**Comment by jcmcclorey** [comment] 2021-02-08 19:31
I'm also having the same issue, can get the minimap back by closing and reopening the editor.

**Comment by RMacfarlane** [comment] 2021-02-08 20:13
@ElenaVerdy Do you mean that you disabled all of them and then re-enabled them? Did you still see the problem when they were all disabled?

Can others please comment on whether or not after running `Extensions: Disable All Extensions` you still see the problem?

**Comment by ElenaVerdy** [comment] 2021-02-08 20:27
@RMacfarlane Yup, exactly. The problem went away when I disabled all extensions. I now have them all running and the minimap works too. I will let you know if it breaks again.

**Comment by sarimarton** [comment] 2021-02-08 22:18
Disabling all extensions in itself didn't solve the issue, but disabling + quit and restart solved it. I then re-enabled my extensions and so far I can't reproduce the issue with enabled extensions.

**Comment by alexdima** [comment] 2021-02-09 08:19
Given the above comments, it appears that an extension you have installed decides to change the minimap editor option. You can try to narrow down which one it is using Extension Bisect:

* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by JanuszCh** [comment] 2021-02-09 09:50
I had the same issue.

VSCode: 1.53.0
Mac: BigSur 11.1

I did the steps described above by @alexdima.

Result:
```
Extension Bisect is done and has identified zhuangtongfa.material-theme as the extension causing the problem.
```
This extension is `One Dark Pro Theme`.

The `minimap` issue has been resolved after disabling this extension.

**Comment by ChristianHecker** [comment] 2021-02-09 15:29
At the last update 1.53.0 i switched to wrap editor tabs in the workbench instead of having a scrollbar.
**I reversed it and haven't had any problems for 2 hours.**
I will let you know when the problem occurs again.

**Comment by jellymann** [comment] 2021-02-10 13:41
I think I solved it by removing the `vscode-custom-css` extension, even though I'm sure I didn't have any custom CSS added at the time. Oh well ¯\_(ツ)_/¯

**Comment by brunottonurb** [comment] 2021-02-10 14:51
For me it was apparently caused by 'sort lines'. Isn't it weird that so many different extensions cause issues with the minimap? Maybe the problem lies elsewhere...

**Comment by jellymann** [comment] 2021-02-10 16:06
> I think I solved it by removing the `vscode-custom-css` extension, even though I'm sure I didn't have any custom CSS added at the time. Oh well `¯\_(ツ)_/¯ `

Scratch that, it started happening again. I'm going to have to bisect my extensions now 😑

**Comment by IceTDrinker** [comment] 2021-02-10 18:01
Is this confirmed to be linked to extensions ? It feels like it started with the latest vscode update more than anything else

**Comment by IceTDrinker** [comment] 2021-02-10 18:11
When the bug started to trigger, I was able to reliably reproduce the issue by switching between two files, a .sh and a .py file while the scrollbar for editors is active, no idea if the scrollbar is relevant. The minimap would disappear every time

**Comment by ChristianHecker** [comment] 2021-02-10 18:29
It must have something todo with the last update. 
I just disabled all my extensions **and the problem is still there**.

I can reproduce the issue (no extensions are enabled):
1.  I change and save something on the page.
2. Then I discard the changes via GIT.
     (Not in the source control panel. Directly by clicking on the color bars close to the line numbers.)
3.  If I now change the page by clicking on another tab the minimap is gone.

**Comment by IceTDrinker** [comment] 2021-02-10 18:44
That would make sense, I sometimes use this too, I’ll check if I can repro

**Comment by Oskenso** [comment] 2021-02-11 00:31
I experienced this bug today, seems to happen everytime I switch tabs. The "Show Minimap" button also stays checked even if it is not shown

**Comment by sfertman** [comment] 2021-02-11 02:24
Same here, everything worked fine until the last update. 

OS
```
macOS Mojave 10.14.2
```
VSCode
```
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:35:15.302Z (2 days ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.2.0
```

**Comment by IceTDrinker** [comment] 2021-02-11 08:08
Can confirm that using the inline git tools (reverting changes by using the colored tools on the left of the document) and then switching to a new file triggers the bug

**Comment by alexdima** [comment] 2021-02-11 08:26
Thank you @IceTDrinker . I can reproduce with your steps:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/107614747-31df5900-6c4b-11eb-9ebb-9ee6737bcf62.gif)

**Comment by edi** [comment] 2021-02-11 10:26
Same. Used bisect, came to the conclusion that it might be VSCode's fault.
With no extensions after a quick reload, you can simply use the UI's git diff checker, it will hide the minimap.

Only workaround is to disable "View -> Show Minimap" then enable it again. Still, it gets hidden every single time when using diffs.

**Comment by alexdima** [comment] 2021-02-11 11:17
Caused by https://github.com/microsoft/vscode/commit/82fe1e7d0df9c074a7ffaaad917a681f717df5df

**Closed** 2021-02-11 11:24 UTC
Labels: bug, candidate, regression

**Comment by jellymann** [comment] 2021-02-11 13:44
Thanks @alexdima 🎉

**Comment by edwardduffell** [comment] 2021-02-13 21:55
Was suffering the same problem, toggled minimap off and then restarted VSC, then switched minimap on.
This seemed to resolved the issue.

**Comment by ShockwaveDev** [comment] 2021-02-14 22:03
I was having the same issue with minimap disappearing.
I managed to fix it by turning off the "Show Minimap" option under view.
Then I restarted VSC and then turned "Show Minimap" back on.
