### ISSUE TITLE
New Mac icon: Extremely disappointing!

### ISSUE THREAD

**Issue by zevrix** [microsoft/vscode#125730] opened 2021-06-08 08:28 UTC
Issue Type: <b>Feature Request</b>

Hi,

Extremely disappointed in the new Mac icon!

I understand that you're trying to follow Apple guidelines for Big Sur.

However, Visual Studio Code had a great, exciting icon - a masterpiece.

Now it's a sad white rectangle with a tiny, hardly visible image of the original icon.

In their guidelines, Apple never asked to destroy previously great icons and replace them with something ugly and ridiculous.

Please restore the glory of the original icon!

Thanks,
Leo

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

**Comment by IllusionMH** [comment] 2021-06-08 11:20
/duplicate of #120507 and therefore #120604

Please provide your request for old icon there

**Closed** 2021-06-08 11:21 UTC
Labels: *duplicate
