### ISSUE TITLE
Moving TS file causes import path formatting to change for unrelated files

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#53186] opened 2018-06-27 22:24 UTC
Issue Type: <b>Bug</b>

Found while verifying https://github.com/Microsoft/vscode/issues/50707

1. Add `"typescript.updateImportsOnFileMove.enabled": "always"` to settings
2. In VSCode repo, drag a file referenced by other files into a different folder. `issueReporterModel.ts` is a nice example because only two other files reference it

The path to the file is correctly updated in files referencing it, but paths in other files are also reformatted (relative paths like `'./list'` change to be from workspace root `'vs/base/browser/ui/list/list'`), causing a large number of editors to open:

![filerename](https://user-images.githubusercontent.com/3672607/42002491-51e575aa-7a1c-11e8-952e-22c8df3a00af.gif)

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:11:02.122Z)
OS version: Darwin x64 17.4.0

**Comment by kyle-mccarthy** [comment] 2018-06-29 14:52
Same issue here, it looks like it opens almost every type definition file.  It doesn't seem like there are actually any changes made to the files, but when I try to close one it will prompt me to save the changes or they will be lost.

VS Code Version: Version 1.24.1 (1.24.1)
OS: MacOS High Sierra version 10.13.5

**Comment by mspoulsen** [comment] 2018-06-30 05:41
I have exactly the same issue. I didn't even move a .ts file - I just copied one. Now I have 670 open editors :open_mouth: They don't show up in Stable when opening the same project. I even tried re-installing Insiders, but my 670 open editors are still there.

Is there a way to close the editors without having to click "Don't Save" 670 times? :slightly_smiling_face: 

VS: 1.25.0-insider
OS: Linux Ubuntu 16.04

**Comment by mjbvz** [comment] 2018-07-02 07:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/24914

Try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-07-02 07:13 UTC
Labels: bug, needs more info, typescript
