### ISSUE TITLE
Code group is not collapsing.

### ISSUE THREAD

**Issue by shreyansRS** [Microsoft/vscode#52389] opened 2018-06-20 05:58 UTC
Issue Type: <b>Bug</b>

I'm using Visual Studio code for React development and I'm not able to collapse JSX objects (HTML Tags) in any of the methods.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.43GB (11.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\perforce\razor\iaetools\newycc\buddy\frontend|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.5.0

</details>

**Comment by mjbvz** [comment] 2018-06-20 17:11
Duplicate of #51266

See that issue for root cause and workaround

**Closed by mjbvz** 2018-06-20 17:11 UTC
Labels: javascript
