### ISSUE TITLE
Sogou Pinyin input method cannot input Chinese in Bash

### ISSUE THREAD

**Issue by lu-lu-yin** [microsoft/vscode#117650] opened 2021-02-25 03:17 UTC
- VS Code Version: 1.53.2
- OS Version: windows 10.0.18363.535 + sougou pinyin 95b/101a

Steps to Reproduce:

1. 1.52.1 be able to input Chinese  in  powershell.
2. If you upgrade to 1.53.2, you can't input Chinese.
3. Degraded to 1.52.1 and returned to normal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Nyaasu66** [comment] 2021-02-25 08:31
是和这个Issue同样的问题：[#115814](https://github.com/microsoft/vscode/issues/115814)

------------------------------------------------------------------------------------

Duplicate of [#115814](https://github.com/microsoft/vscode/issues/115814)

**Closed** 2021-02-25 09:21 UTC
