### ISSUE TITLE
VSCode stops working for a moment when deleting a file

### ISSUE THREAD

**Issue by m0tz** [microsoft/vscode#103735] opened 2020-07-31 23:52 UTC
Everytime i delete a file vscode suddenly stops working, i mean it doesnt allow you to interact with it in any way, you just see the window and cannot do anything but wait for a moment until it goes back to normal.

CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3586)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 11.59GB (4.50GB free)
Process Argv | . --no-sandbox
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
rainbow-brackets | 2gu | 0.0.6
html-snippets | abu | 0.2.1
django-register-tags | agu | 0.0.5
vscode-django | bat | 0.20.0
vscode-eslint | dba | 2.1.8
githistory | don | 0.6.9
gitlens | eam | 10.2.2
vscode-html-css | ecm | 0.2.3
vscode-firefox-debug | fir | 2.9.0
MagicPython | mag | 1.1.0
prettify-json | moh | 0.0.3
vscode-docker | ms- | 1.4.1
python | ms- | 2020.7.96456
vscode-pylance | ms- | 2020.7.4
sqltools | mtx | 0.22.11
html5-boilerplate | sid | 1.0.3
python | tht | 0.2.3
vscodeintellicode | Vis | 1.2.9
jinja | who | 0.0.8

**Comment by erickisos** [comment] 2020-08-01 06:23
Actually I have the same problem, but this issue seems like a duplicate of #43508 

This is my system info.

| | Intel i7-8750H (12) @ 4.100GHz|
|-|--------------------------------------------|
| Load (avg) | 0.63, 0.79, 0.81 | 
| Memory (System) | 23.3GiB (16.53GiB Free) |
| VS Code Version |1.47.3 |
| Commit | 91899dcef7b811 |
| Date | 2020-07-23T15:51:39.791Z |
| Electron | 7.3.2 |
| Chrome | 78.0.3904.130 |
| Node.js | 12.8.1 |
| V8 | 7.8.279.23-electron.0 |
| OS | Linux x64 5.6.19-2-MANJARO |


| Author               | Extension                       | Version      |
| -------------------- | ------------------------------- | ------------ |
| aaron-bond           | better-comments                 | 2.1.0        |
| amazonwebservices    | aws-toolkit-vscode              | 1.12.0       |
| Angular              | ng-template                     | 0.1000.7     |
| axosoft              | gitkraken-glo                   | 1.1.1        |
| christian-kohler     | path-intellisense               | 2.2.1        |
| CoenraadS            | bracket-pair-colorizer          | 1.0.61       |
| eamodio              | gitlens                         | 10.2.2       |
| Equinusocio          | vsc-community-material-theme    | 1.4.1        |
| Equinusocio          | vsc-material-theme              | 32.8.0       |
| equinusocio          | vsc-material-theme-icons        | 1.2.0        |
| firefox-devtools     | vscode-firefox-debug            | 2.9.0        |
| Gruntfuggly          | todo-tree                       | 0.0.178      |
| humao                | rest-client                     | 0.24.1       |
| johnpapa             | vscode-peacock                  | 3.7.2        |
| mhutchie             | git-graph                       | 1.25.0       |
| ms-azuretools        | vscode-docker                   | 1.4.1        |
| ms-dotnettools       | csharp                          | 1.22.1       |
| ms-python            | python                          | 2020.7.96456 |
| ms-vscode-remote     | remote-containers               | 0.128.0      |
| ms-vscode-remote     | remote-ssh                      | 0.51.0       |
| ms-vscode-remote     | remote-ssh-edit                 | 0.51.0       |
| ms-vscode-remote     | remote-wsl                      | 0.44.4       |
| ms-vscode-remote     | vscode-remote-extensionpack     | 0.20.0       |
| ms-vscode            | cpptools                        | 0.29.0       |
| ms-vscode            | vscode-typescript-tslint-plugin | 1.2.3        |
| ms-vsliveshare       | vsliveshare                     | 1.0.2478     |
| ms-vsliveshare       | vsliveshare-audio               | 0.1.85       |
| ms-vsliveshare       | vsliveshare-pack                | 0.4.0        |
| msjsdiag             | debugger-for-chrome             | 4.12.9       |
| msjsdiag             | vscode-react-native             | 0.16.1       |
| PKief                | material-icon-theme             | 4.2.0        |
| ria                  | elastic                         | 0.13.3       |
| ritwickdey           | live-sass                       | 3.0.0        |
| ritwickdey           | LiveServer                      | 5.6.1        |
| ryu1kn               | partial-diff                    | 1.4.1        |
| ThreadHeap           | serverless-ide-vscode           | 0.5.25       |
| VisualStudioExptTeam | vscodeintellicode               | 1.2.9        |
| yzhang               | markdown-all-in-one             | 3.2.0        |

**Closed** 2020-08-12 10:51 UTC
