### ISSUE TITLE
missing button to transfer the console to the right side

### ISSUE THREAD

**Issue by valery-lavrik** [Microsoft/vscode#61211] opened 2018-10-18 07:00 UTC
Issue Type: <b>Bug</b>

she used to be here - http://prntscr.com/l7eixg

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:17:36.900Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.49GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|9.0.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.1
xml|Dot|2.3.2
tslint|eg2|1.0.40
windows-explorer-context-menu|ele|2.0.0
natural-doc-comments|erg|1.2.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
url-encode|fle|1.1.0
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.6
ftp-simple|hum|0.6.8
yii2-snippets|ima|0.1.1
mysql-syntax|jak|1.3.1
vscode-redux-devtools|jin|0.0.11
relativepath|joh|0.1.2
react-native-snippet|jun|0.5.0
sshextension|kon|0.3.1
eml|lei|0.3.1
vscode-remote-workspace|mkl|0.35.1
vscode-html-format|moh|0.0.3
prettify-json|moh|0.0.3
vscode-apache|mrm|1.1.1
vscode-language-pack-ru|MS-|1.28.2
atom-keybindings|ms-|3.0.4
vscode-extension-auto-import|Nuc|1.4.3
format-html-in-php|rif|1.3.8
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.2.0
ayu|tea|0.16.0
email-viewer|Tom|4.0.0
vscode-react-native|vsm|0.6.18
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1

</details>

**Comment by tjmlandi** [comment] 2018-10-18 17:57
I also ran into the same issue, running a clean install of Insiders 1.29.0 with no settings or extensions. 

OS: macOS High Sierra 10.13.6

Stable:
![screen shot 2018-10-18 at 1 54 59 pm](https://user-images.githubusercontent.com/6741304/47173983-778af180-d2dd-11e8-9747-b5adb76b1360.png)

Insiders:
![screen shot 2018-10-18 at 1 55 36 pm](https://user-images.githubusercontent.com/6741304/47174003-85407700-d2dd-11e8-8f6d-c5ca32900c31.png)

**Comment by usernamehw** [comment] 2018-10-18 18:19
Duplicate of #58575

**Closed** 2018-10-23 00:48 UTC
Labels: insiders
