### ISSUE TITLE
Cannot change the width of the side bars with the right location

### ISSUE THREAD

**Issue by 7654098** [Microsoft/vscode#41072] opened 2018-01-03 04:55 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
code-runner|for|0.8.7
terminal|for|0.0.10
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
mssql|ms-|1.3.0
csharp|ms-|1.13.1
team|ms-|1.122.0

After update to 1.19.1 i cannot change the width of any open side bar (explorer, search, etc...) using drag. Before this update it were possible.

If I move side bar to the left, it is possible in the new version.

---

Steps to Reproduce:

1. Move side bars to the right using "workbench.sideBar.location": "right", 
2. Try to change size of explorer, search, etc... using dragging.

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2018-01-03 09:29
@7654098 I am not able to reproduce this and it works fine for me 
Can you also reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If you F1 > developer tools > Application > and delete `storage://global/workbench.sidebar.width` key. Can you still repro? Also please let me know what is the value there

![sidebar](https://user-images.githubusercontent.com/1926584/34514835-8e018fe2-f06f-11e7-8394-7047d14cb10f.gif)

**Comment by 7654098** [comment] 2018-01-03 11:42
@isidorn, thank you for your quick feedback!

> please let me know what is the value there

The value is: 303 (after deleting, closing/open vscode, the value became 363)

> delete storage://global/workbench.sidebar.width key. Can you still repro?

1. Deleted the key you mentioned
2. Closed VS Code and reopen it (my work project loaded automatically)
3. The same problem

What is interesting, if I close the project folder in vs code, I will be able to change the width by dragging. But not with the project folder opened. 

I see the pointer in "draggable left/right" mode, but the width not changed if I drag.

Do you need the video of this issue? What is the best way to record? Quicktime for Mac may be?

> Can you also reproduce with latest vscode insiders

I've installed insider version. This problem is not reproducing, everything work fine there...

**Comment by isidorn** [comment] 2018-01-03 11:53
If everything works fine in the latest insider that it should be fixed once you get the next vscode stable update.
No, the video would not really help.
As a workaround, could you start your vscode with `--user-data-dir=SOME_PATH`
This should clear your UX state and you should be able to nicely drag the sidebar

**Comment by 7654098** [comment] 2018-01-03 17:06
OK, thank you.

I will check in the next releases.

**Comment by 7654098** [comment] 2018-01-10 19:41
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
code-runner|for|0.8.7
terminal|for|0.0.10
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
mssql|ms-|1.3.0
csharp|ms-|1.13.1
team|ms-|1.122.0



---

After previous investigations, we agreed to wait the new release. But after new release, I still noticed this problem, and I've found the new dependence, which cause the bug appearance (new points 2 and 3).

The point is - I like the full height code window, that's why I'm trying to locate everything else (terminal, panels) to the right.

Steps to Reproduce:
1. Move side bars to the right using "workbench.sideBar.location": "right"
2. Place Terminal window to bottom (also right) - here I still able to drag the width of panel
3. Hide Terminal  by pressing close icon (x)
4. Try to change size of explorer, search, etc... using dragging - the width is not changing

Reproduces without extensions: Yes

**Comment by isidorn** [comment] 2018-01-11 09:16
Latest stable release does not contain a fix for this. It was a recovery build with only a couple of fixes, please try with the next one in a couple of weeks.

I aslo tried reproducing following your steps with latest vscode insiders and could not reproduce.

**Closed by isidorn** 2018-01-11 09:16 UTC
Labels: bug, needs more info, workbench-layout
