### ISSUE TITLE
editorIndentGuide.activeBackground doesn't work after scroll down and cursor not visible

### ISSUE THREAD

**Issue by vmeira** [Microsoft/vscode#49464] opened 2018-05-08 13:58 UTC
- VSCode Version: 1.23.0
- OS Version: ubuntu 18.04

My extensios
Extension | Author (truncated) | Version
-- | -- | --
beautify | Hoo | 1.3.0
vscode-docker | Pet | 0.0.26
jshint | dba | 0.10.18
auto-rename-tag | for | 0.0.15

Steps to Reproduce:

If you place the cursor at the bottom of an indented code and scroll up the guide is still highlighted.
1.Place cursor on the start of code with indentation. "editorIndentGuide.activeBackground" should start working and make the indent guide more visible
![screenshot from 2018-05-08 10-54-09](https://user-images.githubusercontent.com/16047296/39761505-a903ce30-52ae-11e8-8006-24f8599ab8c3.png)

2. scroll down so the cursor is not visible anymore. The  "editorIndentGuide.activeBackground" stops working
![screenshot from 2018-05-08 10-56-40](https://user-images.githubusercontent.com/16047296/39761513-ad5c6e88-52ae-11e8-9407-31eb03441863.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-05-09 07:52
Duplicate of #49173

**Closed by alexandrudima** 2018-05-09 07:52 UTC
