### ISSUE TITLE
Uncommenting JSX leaves braces around the element 

### ISSUE THREAD

**Issue by croraf** [microsoft/vscode#82224] opened 2019-10-10 08:44 UTC
- VSCode Version: 1.38.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Toggle block comment around the JSX element to comment it
`<List />` -> `{/* <List /> */}`
2.Toggle block comment again to uncomment it
`{/* <List /> */}` -> `{<List />}`

As you see, it will leave braces that were not present in the original.
Repeating the above steps once more gives:
`{{<List />}}`

Don't know if the braces can be removed after uncommenting, or would this cause some other errors. But if they can safely be removed than it should be fixed.

**Comment by mjbvz** [comment] 2019-10-16 17:51
Toggle block comment is now fix if you select the comment expression like so:

<img width="297" alt="Screen Shot 2019-10-16 at 10 45 11 AM" src="https://user-images.githubusercontent.com/12821956/66944506-2aca1b80-f002-11e9-84c7-949bc0cb9558.png">

It's not fixed in specific case where you:

1. For the code:

    ```ts
    const a = (
        <div>
            <img />
        </div>
    )
    ```

1. Select `<img />`
1. Run toggle block comment.
    This results in ` {/*  <img /> */}` but with only ` <img />` selected
1. Run toggle block comment again. 
    This still leaves the outer braces

The reason for this is that after the first `toggle block comment`,  you only have the js part of a the react expression selected, so we use js commenting styles for the next `toggle block comment`. In general this is the expected behavior for mixed languages like react javascript but this one case doesn't work well

I'm closing this as fixing one case this would cause regressions in other scenarios

**Closed by mjbvz** 2019-10-16 17:51 UTC
Labels: bug, typescript

**Comment by connor4312** [comment] 2019-10-30 18:37
Verified to the extent described in the comment.
