### ISSUE TITLE
Excessive spaces on the localized context menu "Open with Code" in Simplified Chinese (zh-CN)

### ISSUE THREAD

**Issue by byyxx128** [microsoft/vscode#85869] opened 2019-12-01 03:16 UTC
Recently I noticed the context menu "Open with Code" has been localized. However, I found there is a little typo in simplified Chinese (zh-CN).

The original English version is `Open with Code Insiders`, so the simplified Chinese (zh-CN) version should be `通过[One Space]Code Insiders 打开`. However, it is currently `通过[Two Spaces]Code Insiders 打开`.
The difference is there should be only **one space** between `通过` and `Code`, but there are **two spaces** now.
![image](https://user-images.githubusercontent.com/20079289/69908786-34c9a180-142b-11ea-858c-39589465c0dc.png)

GitHub always cuts extra spaces... Anyways, see the screenshot above.

**Comment by sandy081** [comment] 2019-12-01 11:54
Not sure who is responsible for this and hence assigning to three of you.

**Comment by dbaeumer** [comment] 2019-12-02 12:03
@byyxx128 can you provide me with a screen shot showing the context of the menu?

**Comment by byyxx128** [comment] 2019-12-02 16:18
I already provided in my description.

- The Original English menu is:
`Open with Code Insider`
(Because only the insiders version has localized menu, I have to use insiders for example.)
- The localized is
![image](https://user-images.githubusercontent.com/20079289/69975242-d2d56e80-14f4-11ea-812d-ff159d453f0f.png)

So, between the word **`通过`** and **`Code`**, there should be **one space**, however, it's **two spaces** right now. That's my point.

**Comment by dbaeumer** [comment] 2019-12-02 21:17
I mean where exactly do you see the the menu entry and in which context (e.g. on a workspace file for example). I can't reproduce this in my setup but I am sure I am not looking at the same example.

**Comment by byyxx128** [comment] 2019-12-03 04:32
It's not in setup. It's in context menu, when you right click a file or a folder in explorer.
(Obviously you need to check to add the menu when you install through setup.)

**Comment by dbaeumer** [comment] 2019-12-03 08:32
Adding @joaomoreno then.

**Comment by joaomoreno** [comment] 2019-12-03 09:40
Here's the location to fix this: https://github.com/microsoft/vscode/blob/d57b8538763b9db16bd8ca3b4dd17f5aa129b87f/build/win32/i18n/messages.zh-cn.isl#L9

@byyxx128 Care to submit a PR? Thanks!

**Comment by joaomoreno** [comment] 2019-12-03 09:42
Oh actually, the problem is somewhere else.

**Closed** 2019-12-03 09:43 UTC
Labels: bug, i18n, install-update, windows

**Comment by byyxx128** [comment] 2019-12-03 16:20
Great, seems you found the real reason (not related to a specific language).
Waiting for the new insider release to confirm...
