### ISSUE TITLE
app.js file

### ISSUE THREAD

**Issue by meshv-p** [microsoft/vscode#129401] opened 2021-07-26 13:09 UTC
Issue Type: <b>Bug</b>

hey I'd written my app.js file in vs code but some technical error so my vs code did close. I reopened my vs code, and what i saw, my app.js is totally blanked. it showed me blank file!!!.
my all code has gone!!!!.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.30GB free)|
|Process Argv|--crash-reporter-id dd9db3a7-3b42-4ce1-b89b-622430555ae1|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.13
phpserver|bra|3.0.2
doxdocgen|csc|1.3.2
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
php-debug|fel|1.16.1
php-pack|fel|1.0.2
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.28.0
better-cpp-syntax|jef|1.15.6
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
live-server|ms-|0.2.4
vsliveshare|ms-|1.0.4583
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
python|tht|0.2.3
material-theme|zhu|3.11.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by meshv-p** [comment] 2021-07-26 13:10
my issue.

**Comment by mjbvz** [comment] 2021-07-26 22:46
Closing since it sounds like the issue was fixed. If not, please provide more information about how to reproduce the problem

**Closed by mjbvz** 2021-07-26 22:46 UTC
