### ISSUE TITLE
Code freezes when copy pasting the saved filename

### ISSUE THREAD

**Issue by Sentient07** [microsoft/vscode#211981] opened 2024-05-03 21:02 UTC
Does this issue occur when all extensions are disabled?

- VS Code Version:  code_1.89.0-1714530869
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Click ctrl + save 
2. copy the suggested filename to keyboard (preferably saving an existing file with different name)
3. Paste what's on clipboard to the editor
4. Code freezes and doesn't respond

If I paste what is in my clipboard to sublime and copy it from there, no issues

**Comment by Sentient07** [comment] 2024-05-03 21:04
I have Code running on another laptop which is 1.87.2 and this occurs on that as well

**Comment by bpasero** [comment] 2024-05-06 14:51
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by rzhao271** [comment] 2024-05-06 22:33
Potential duplicate of https://github.com/microsoft/vscode/issues/195196.

**Comment by rzhao271** [comment] 2024-12-09 22:35
Closing in favour of #195196.

**Closed by rzhao271** 2024-12-09 22:35 UTC
Labels: freeze-slow-crash-leak
