### ISSUE TITLE
Big wasted space on the right side of integrated terminal

### ISSUE THREAD

**Issue by maple3142** [microsoft/vscode#228306] opened 2024-09-12 05:12 UTC
Type: <b>Bug</b>

1. Open vscode
2. Open integrated terminal
3. Try to select all the text and you can see that the right can't be selected

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor            (16 x 4192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.12GB (14.19GB free)|
|Process Argv|--crash-reporter-id c260269c-b671-4705-9b38-af653213ad14|
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.1
vscode-intelephense-client|bme|1.12.2
vscode-tailwindcss|bra|0.12.5
insert-unicode|bru|0.15.1
gitignore|cod|0.9.0
arm|dan|1.7.4
markdown-table-prettify|dar|3.6.0
vscode-eslint|dba|3.0.10
vscode-deno|den|3.38.0
javascript-ejs-support|Dig|1.3.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.4.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
go|gol|0.42.0
vscode-drawio|hed|1.6.6
prettier-sql-vscode|inf|1.6.0
ejs-beautify|j69|1.0.6
better-cpp-syntax|jef|1.27.1
solidity|Jua|0.0.174
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.1
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
vscode-open-wsl|NoT|0.2.2
material-icon-theme|PKi|5.8.0
java|red|1.33.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
vscode-fix-checksums-next|Rim|1.2.0
rust-analyzer|rus|0.3.2062
jinjahtml|sam|0.20.0
background|sha|1.2.13
svg-preview|Sim|2.8.3
svelte-vscode|sve|108.6.0
pdf|tom|1.2.2
cmake|twx|0.0.17
windows-terminal|Tyr|0.7.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
gistfs|vsl|0.6.0
code-block|wei|0.0.3
vscode-sqlite3-editor|yy0|1.0.189
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details>

**Comment by maple3142** [comment] 2024-09-12 05:15
On windows, powershell
![image](https://github.com/user-attachments/assets/50ed06da-96d1-4d65-bbda-79121079275a)

In WSL, zsh
![image](https://github.com/user-attachments/assets/2d00f020-d128-46c0-ae5d-1c0192924ab1)

Using developer tools I see that `div.xterm-screen` is unusually narrow compared to its parent `div.xterm-scrollable-element`

![image](https://github.com/user-attachments/assets/95bd0ec8-40c7-48ad-9ee3-50e99e1b4e22)
![image](https://github.com/user-attachments/assets/568fb7e4-fed3-4cfc-9216-560782406b7c)

**Comment by meganrogge** [comment] 2024-09-12 14:40
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by maple3142** [comment] 2024-09-12 16:59
I can reproduce th bug on insiders build
![image](https://github.com/user-attachments/assets/54f3d881-742e-4da5-86f7-e7ed4ff11caf)

**Comment by Tyriar** [comment] 2024-12-10 21:03
Should be fixed now. I cannot reproduce, other than when I zoom out a lot I think we hit the max columns

![Image](https://github.com/user-attachments/assets/74a40a29-a1a5-4955-976a-5fb4f88ae3ef)

**Closed by Tyriar** 2024-12-10 21:03 UTC
Labels: bug, terminal-layout
