### ISSUE TITLE
not able to open files with Version 1.43.2

### ISSUE THREAD

**Issue by sujaymetha** [microsoft/vscode#95089] opened 2020-04-13 06:22 UTC
Issue Type: <b>Bug</b>

Unable to open 'seller-landing.component.html': Assertion Failed: argument is undefined or null.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by RMacfarlane** [comment] 2020-04-13 15:49
Duplicate of https://github.com/microsoft/vscode/issues/94931

**Closed by RMacfarlane** 2020-04-13 15:49 UTC
