### ISSUE TITLE
Backticks incorrectly render as diacritical marks on editor

### ISSUE THREAD

**Issue by Samuelfaure** [microsoft/vscode#93567] opened 2020-03-27 11:13 UTC
- VSCode Version: 1.43.1
- OS Version: 5.5.10-arch1-1 (Arch linux)

Keyboard is US INTL with dead keys

**Duplicate** of https://github.com/microsoft/vscode/issues/64034 (closed, unresolved)

Steps to Reproduce:

1. Open a file in VS code
2. Type TWICE the backtick touch (under ESC), you get : ` (Expected behavior)
3. Type ONCE the backtick touch, then a letter such as 'e', you get : è (Expected behavior)
4. Type TWICE the backtick touch, you get : ` ; then type ONCE a letter such as 'e',

You should get : `e, you get: è

This is very annoying while trying to write markdown, but seems to happen in any kind of files.

Another problem: **this creates a weird fake spacing on the right**, look at the cursor in the following animated gif:
![Peek 2020-03-27 12-10](https://user-images.githubusercontent.com/14159757/77750562-4b23ea80-7024-11ea-880f-b017cabf9e75.gif)

Note that **Markdown is still rendered correctly.** with markdown preview. File is rendered correctly with VIM

![image](https://user-images.githubusercontent.com/14159757/77750997-28de9c80-7025-11ea-9530-fb228861f4f4.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by sportshead** [comment] 2020-03-27 11:19
Well if you know this is a duplicate then please close this issue

**Comment by Samuelfaure** [comment] 2020-03-27 11:33
The previous issue is closed and can not be reopened.

**Comment by yougotwill** [comment] 2020-05-14 12:57
Same issue happening with v1.45.0 on macOS 10.14.6

**Comment by Samuelfaure** [comment] 2020-05-14 17:30
I would really enjoy this bug being fixed, I've been writing a lot of javascript and the backticks are essentials.

**Comment by davidolrik** [comment] 2020-07-25 14:37
This is *not* a bug in vscode, but rather a case of using a locale with "dead keys".

When using a locale with dead keys you must press back tick+space to get a single back tick, as typing back tick only is considered a modifier key, and depending on what you type next you will either get a back tick + a letter or a letter with diacritic marks.

Here is an excellent description of how dead keys work: [https://askubuntu.com/questions/56560/what-exactly-is-meant-by-eliminate-dead-keys](https://askubuntu.com/questions/56560/what-exactly-is-meant-by-eliminate-dead-keys).

**Comment by yougotwill** [comment] 2020-07-26 03:59
Also confirmed my issue wasn't VSCode related it was due to Inconsolata Nerd Font.

**Comment by Samuelfaure** [comment] 2020-07-27 08:32
I DO use inconsolata nerd font. I guess that's it for the bug. Thanks !

**Closed** 2020-07-27 08:35 UTC
Labels: bug, editor-input-IME, linux
