### ISSUE TITLE
Incorrect rendering of Katex in Markdown

### ISSUE THREAD

**Issue by mbeliaev1** [microsoft/vscode#129779] opened 2021-07-29 16:33 UTC
Issue Type: <b>Bug</b>
## Summary:
Before the updated built-in notebooks came out, I was using markdown cells within jupyter to render latex equations without any issue. With the new built-in notebooks, I am having rendering errors which I assume are due to the new KaTeX typesetter. I am sure there are more symbols and environments that will give me issues, but I have listed the few that I found so far in the example provided. 

## Steps to Reproduce: 
1. Open an .ipynb file with the new built-in notebooks. 
2. In a markdown cell, enter a KaTeX equation to be rendered using $$ (wrapping it in \begin{equation}\end{equation} environment makes no difference). 

```
$$
p(x|\hat{a},\hat{b})=
\begin{cases}
\langle a,b \rangle,& \textrm{if } a=a^*\\
\langle x,b \rangle,& \textrm{if } a\ne a^*
\end{cases}
$$
```

## Expected Results:
We want to correctly render the \hat symbol, the \cases environment, as well as the \ne or \neq symbol.

## Actual Results:
The symbols/environments mentioned render incorrectly:

![image](https://user-images.githubusercontent.com/50807267/127530774-5be630e5-369e-4f60-8a83-1063d3678607.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.29GB (0.85GB free)|
|Process Argv|--no-sandbox Documents/code/expert_rank/ --crash-reporter-id c276f5fd-6ee5-47a7-ae52-111291da1fc8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|8.1.0
latex-workshop|Jam|8.19.2
markdown-toc|jof|1.4.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment] 2021-07-29 17:29
Duplicate of #128490

**Closed by mjbvz** 2021-07-29 17:29 UTC
