### ISSUE TITLE
Hovering package.json dependency name shows the wrong latest version

### ISSUE THREAD

**Issue by manferlo81** [microsoft/vscode#109203] opened 2020-10-23 04:08 UTC
- VSCode Version: 1.50.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Hover your mouse over `package.json` dependency name.

Does this issue occur when all extensions are disabled?: Yes

![VSCodeIssue](https://user-images.githubusercontent.com/11273138/96955202-3dcdd080-151f-11eb-828d-f8db4769cc2a.png)

Today is October 23 2020. Latest version of `@babel/core` is 7.12.3, VSCode showing 7.11.6 which was published more than 2 months ago.

Every other dependency is showing the wrong version as well, it's not just `@babel/core`.

Thanks.

**Comment by gjsjohnmurray** [comment] 2020-10-23 06:49
@manferlo81 I think something recently got fixed in this area. Are you willing to install [Insiders](https://code.visualstudio.com/insiders/) and check it there?

**Comment by aeschli** [comment] 2020-10-23 10:02
duplicate of https://github.com/microsoft/vscode/issues/108605

**Closed by aeschli** 2020-10-23 10:02 UTC
