### ISSUE TITLE
In Git viewlet Ctrl+Enter doesn't execute the default action anymore

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#213775] opened 2024-05-29 07:25 UTC
Windows + WSL
Latest Insider

I am pretty sure that this once worked since my muscle memory constantly hits Ctrl+Enter and nothing happens

**Comment by lszomoru** [comment] 2024-05-29 10:26
Duplicate of https://github.com/microsoft/vscode/issues/212857

**Closed by lszomoru** 2024-05-29 10:26 UTC
