### ISSUE TITLE
Sticky lines problem oneliners

### ISSUE THREAD

**Issue by Magnusri** [microsoft/vscode#226133] opened 2024-08-21 08:41 UTC
Type: <b>Bug</b>

Sticky lines at top of editor breaks when very long oneliners are broken down to multiple lines that result in beeing higher than the editor window. Results in the editor becoming totally blank when viewing the area in the file with the very long oneliner. Breaks a LOT with minified web files.

Reproduce;
1. Inside an HTML file, insert a oneliner that is very long(i.e would be twice the height of the editor if not oneline)
2. Tell the editor to use linebreak (Show long lines on multiple "rows")
3. If the line becomes taller than the editor height, it will just be blank when the top tries to be "sticky".

Version: 1.93.0-insider

VS Code version: Code - Insiders 1.93.0-insider (e1db90f81da28c0994b5d50dc2b51e964359e62d, 2024-08-21T05:04:11.586Z)
OS version: Windows_NT x64 10.0.26120
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.88.2
vscode-zipfs|arc|3.0.0
gitlens|eam|2024.8.2005
copilot|Git|1.223.1060
copilot-chat|Git|0.20.2024082101
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31111718
nativeloc1:31118317
wkspc-ranged-c:31118571
3ad50483:31111987
93e6f237:31111927
e80f6927:31120813
ei213698:31121563
i21gd607:31121876

```

</details>

**Comment by alex-kinokon** [comment] 2024-10-06 08:51
Duplicate of #227686?

**Comment by Magnusri** [comment] 2024-10-06 09:01
> Duplicate of #227686?

Yes, that one would be a duplicate of this yes.

**Comment by aiday-mar** [comment] 2024-12-11 09:21
The issue you mention is fixed. This issue will be closed.

**Closed by aiday-mar** 2024-12-11 09:21 UTC
Labels: editor-sticky-scroll
