### ISSUE TITLE
Test: Apply indentation rules when pressing enter

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#19081] opened 2017-01-23 20:06 UTC
Test for https://github.com/Microsoft/vscode/pull/16568

- [x] any os @waderyan 
- [x] any os @weinand 

Complexity: 3

Steps:
1. Open files whose language has indentation rules set, for example [TypeScript](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L193) and [Ruby](https://github.com/Microsoft/vscode/blob/master/extensions/ruby/src/rubyMain.ts#L12).
2. Try to write code that matches existing patterns and make sure the indentation adjusts correctly when pressing enter.

Helpful links:
https://github.com/Microsoft/vscode/issues/17868 describes the meaning of four indentation rules and how we interpret them.

**Comment by ramya-rao-a** [comment] 2017-01-25 01:17
@waderyan Are you done testing this? I see the check mark against your name, but the issue is still assigned to you.

If you are done testing, then unassign yourself and close the issue.

**Closed** 2017-01-25 01:36 UTC
Labels: testplan-item
