### ISSUE TITLE
Update Failure

### ISSUE THREAD

**Issue by rawbytz** [Microsoft/vscode#58018] opened 2018-09-06 00:37 UTC
- Version: 1.26.1
- Commit: 493869ee8e8a846b0855873886fc79d480d342de
- Date: 2018-08-16T18:38:57.434Z
- Electron: 2.0.5
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64 Windows 10

Does this issue occur when all extensions are disabled?: Yes
Numerous reboots.
Version: 1.26.1 is working.

Steps to Reproduce:

1. With VSC open, "Installing Update" fails
2. Get abort/retry dialog with this:
> An error occurred while trying to replace the existing file:
> DeleteFile failed; code 32.
> The process cannot access the file because it is being used by another process.

-OR-

1. Close VSC to complete install
2. Runaway process with message saying post this log:

_vscode-inno-updater-1536191300.log_
> Sep 05 17:48:20.129 INFO Starting: C:\Users\Jay\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
> Sep 05 17:48:20.129 INFO Checking for running Code.exe processes... (attempt 1)
> Sep 05 17:48:20.145 INFO Code.exe is running, wait a bit
> Sep 05 17:48:20.660 INFO Checking for running Code.exe processes... (attempt 2)
> Sep 05 17:48:20.660 INFO Code.exe is running, wait a bit
> Sep 05 17:48:21.176 INFO Checking for running Code.exe processes... (attempt 3)
> Sep 05 17:48:21.176 INFO Code.exe is not running
> Sep 05 17:48:21.176 INFO Checking for possible conflicting running processes... (attempt 1)
> Sep 05 17:48:21.191 INFO Inno Updater v0.6.0
> Sep 05 17:48:21.191 INFO Starting update, silent = false
> Sep 05 17:48:21.207 INFO do_update: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
> Sep 05 17:48:21.207 INFO move_update: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
> Sep 05 17:48:21.207 INFO Reading directory: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code"
> Sep 05 17:48:21.207 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-console-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-file-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-file-l1-2-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-file-l2-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-string-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-core-util-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\blink_image_resources_200_percent.pak" (attempt 1)
> Sep 05 17:48:21.223 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 1)
> Sep 05 17:48:21.285 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 2)
> Sep 05 17:48:21.488 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 3)
> Sep 05 17:48:21.941 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 4)
> Sep 05 17:48:22.754 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 5)
> Sep 05 17:48:24.020 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 6)
> Sep 05 17:48:25.832 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 7)
> Sep 05 17:48:28.285 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 8)
> Sep 05 17:48:31.488 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 9)
> Sep 05 17:48:35.551 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 10)
> Sep 05 17:48:40.566 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 11)
> Sep 05 17:48:46.629 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 12)
> Sep 05 17:48:53.832 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 13)
> Sep 05 17:49:02.285 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 14)
> Sep 05 17:49:12.097 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 15)
> Sep 05 17:49:23.363 INFO Get file handle: "C:\\Users\\Jay\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 16)
> Sep 05 17:49:23.363 ERRO Failed to create file handle: The process cannot access the file because it is being used by another process.

**Comment by doublehelix** [comment] 2018-09-06 01:29
Same issue.
Confirmed that "code.exe" is in fact locked... by the `system` process.
![2018-09-06](https://user-images.githubusercontent.com/355130/45129617-25c45700-b1c8-11e8-8341-4744f5ac366b.png)

**Comment by JimAmuro** [comment] 2018-09-06 01:34
Same here, I'm using user setup of VS Code.

**Comment by Monkey-D-Pixel** [comment] 2018-09-06 04:29
Same here
[vscode-inno-updater-1536203889.log](https://github.com/Microsoft/vscode/files/2355436/vscode-inno-updater-1536203889.log)

**Comment by joaomoreno** [comment] 2018-09-06 09:10
Excelent, at least we're not bricking the installation any more. Did you restart your machine, like the dialog asked?

**Comment by rawbytz** [comment] 2018-09-06 14:02
Restarts?  Yes, more than I care to admit.

**Comment by vannizhang** [comment] 2018-09-06 18:10
I am having the same issue when I do my update:

![image](https://user-images.githubusercontent.com/3142684/45176587-4f2fb380-b1c5-11e8-9cde-9495d1ccc76d.png)

[vscode-inno-updater-1536256934.log](https://github.com/Microsoft/vscode/files/2358242/vscode-inno-updater-1536256934.log)

**Comment by eegod** [comment] 2018-09-07 01:37
Same issue with me. 

[vscode-inno-updater-1536282126.log](https://github.com/Microsoft/vscode/files/2359202/vscode-inno-updater-1536282126.log)

PS: I have portable mode enabled according to [this doc](https://code.visualstudio.com/docs/editor/portable#_enable-portable-mode).

**Comment by doublehelix** [comment] 2018-09-07 02:45
Is it possible that `code.exe` is being locked by the system process if it has been registered as the default editor for some particular file extension, or more specifically as the default editor for *git*.
After installing the previous version (1.26.x) I was asked by VSCode to update my GIT to 2.x or higher.
During installation of the new GIT, I was asked if I wanted to make VSCode my default editor?

This may or may not help, but I can't think of any reason for the system process to arbitrarily lock a file like this.

**Comment by markidm** [comment] 2018-09-10 22:30
Same issue here, System process locking Code.exe

**Comment by rawbytz** [comment] 2018-09-11 01:52
@joaomoreno  I ended up uninstalling/reinstalling VSC, and I'm all fixed.

**Comment by joaomoreno** [comment] 2018-09-11 08:59
Alright closing this. #47841 remains open.

**Closed by joaomoreno** 2018-09-11 08:59 UTC
Labels: needs more info

**Comment by shanselman** [comment] 2018-09-14 06:20
Hitting this also...adding logs on the dupe
