### ISSUE TITLE
Notebook webview does not load due to CORS on Codespace

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#112180] opened 2020-12-09 21:30 UTC
Steps to Reproduce:

* Open Codespace, install github issue notebook extension
* Create a new `.github-issues` file, create a query and run
* You may need to authenticate a million times, it's an known bug
* After execution, the output is not displayed properly due to following error

```
Access to fetch at 'https://vscodeweb.azureedge.net/insider/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/loader.js' from origin 'https://rebornix-postbox-wv3h.github.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

This seems recent, not sure what we should do to fix this as we can load it properly in both VS Code desktop and self host web.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-12-10 00:16
I confirmed this in dev. However I also tested in preproduction and did not see this issue. @rebornix Could you try testing a pre-production codespace to see if the issue has been fixed there?

**Comment by rebornix** [comment] 2020-12-10 01:34
![image](https://user-images.githubusercontent.com/876920/101709652-b68fda00-3a44-11eb-87cb-f742e28f0742.png)

I'm seeing the same issue with ppe environment as shown above

**Comment by mjbvz** [comment] 2021-01-23 02:24
I just tested this and it seems to be working for me.

Test steps:

1. Create a codespace in VS Code repo
2. Make sure GitHub notebook extension is installed
3. Create a new file `x.github-issues`
4. In the file, add:
```
$repos=repo:microsoft/vscode repo:microsoft/vscode-internalbacklog repo:microsoft/vscode-remote-release repo:microsoft/vscode-js-debug repo:microsoft/vscode-pull-request-github repo:microsoft/vscode-github-issue-notebooks 
$milestone=milestone:"November 2020"
$repos $milestone is:closed  -assignee:@me label:bug -label:verified -label:*duplicate -author:@me -assignee:@me label:bug -label:verified -author:@me -author:aeschli -author:alexdima -author:alexr00 -author:bpasero -author:chrisdias -author:chrmarti -author:connor4312 -author:dbaeumer -author:deepak1556 -author:eamodio -author:egamma -author:gregvanl  -author:isidorn -author:JacksonKearl -author:joaomoreno -author:jrieken -author:lramos15 -author:lszomoru -author:meganrogge -author:misolori -author:mjbvz -author:rebornix -author:RMacfarlane -author:roblourens -author:sana-ajani -author:sandy081 -author:sbatten -author:Tyriar -author:weinand
```

5. Run

<img width="1240" alt="Screen Shot 2021-01-22 at 6 22 49 PM" src="https://user-images.githubusercontent.com/12821956/105566061-f7833b80-5cde-11eb-8421-b42b554e0568.png">


Closing for additional verification

@rebornix Let me know if you still see this

**Closed by mjbvz** 2021-01-23 02:24 UTC
Labels: bug, github-codespaces, important, webview
