### ISSUE TITLE
Mac: Debugging: Debug Console input- keyboard repeat (mostly) doesn't work

### ISSUE THREAD

**Issue by matteliot** [Microsoft/vscode#42273] opened 2018-01-28 16:26 UTC
- VSCode Version:Version 1.19.3 (1.19.3)
- OS Version: 10.12.6

Steps to Reproduce:

1. load any nodeJS code
2. set a breakpoint anywhere
3. start with debugging
4. cause the breakpoint to be hit
5. open the DEBUG CONSOLE tab
6. put the cursor into the prompt textbox as if you were going to type an expression
7. hold down a regular key, eg: a b c d 1 2 3. Special chars, DEL/bksp, and punctuation seems to repeat fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-01-29 02:46
Duplicate of https://github.com/Microsoft/vscode/issues/19764 I believe

Please see the response there. It appears to be an upstream issue

**Closed by mjbvz** 2018-01-29 02:46 UTC
Labels: *duplicate
