### ISSUE TITLE
Syntax highlighting isn't great

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#9807] opened 2016-07-26 18:02 UTC
- VSCode Version: 1.3.1
- OS Version: OS X El Capitan 10.11.1

Steps to Reproduce:

1. Open a JavaScript file (mine comes from [React Starter Kit](https://github.com/kriasoft/react-starter-kit), client.js)

I expect to see syntax highlighting on par with what I see in Atom, instead there seems to be highlights missing. For example, I would expect the method of an object to be highlight a different color than the object itself. 

VS Code
![image](https://cloud.githubusercontent.com/assets/2449568/17149335/b062dc74-531f-11e6-8fbf-262fb436786b.png)

Atom
![image](https://cloud.githubusercontent.com/assets/2449568/17149345/b89ecc22-531f-11e6-8e95-219ad5cd2ecb.png)

Sublime
![image](https://cloud.githubusercontent.com/assets/2449568/17149494/5fdc7a2a-5320-11e6-9b1f-4311ce686256.png)

**Comment by egamma** [comment] 2016-07-27 07:29
@waderyan pls try https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

**Comment by aeschli** [comment] 2016-07-27 07:52
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/149

**Closed by aeschli** 2016-07-27 07:52 UTC

**Comment by waderyan** [comment] 2016-07-27 17:54
Great this is exactly what I need.
