### ISSUE TITLE
Notebooks - Reverting output change in diff does not revert input 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#134076] opened 2021-09-29 01:50 UTC
- VS Code Version: 1.61.0-insider
- OS Version: Windows

Steps to Reproduce:

1. Open notebook and create any output change
2. Open diff view
3. Revert the output - input does not revert 

Since the output is generated by the input, I would imagine that reverting the output would cause the input to be reverted as well so these are kept in sync. If I just revert the output and go back to the original file, I now have a mismatched cell - input code that does not match the output

**Comment by rchiodo** [comment] 2022-01-19 00:13
This seems like it's by design. Putting back into triage.

**Comment by rchiodo** [comment] 2022-01-19 00:14
If you undo an output, I wouldn't expect the input code to change back too. That should be a secondary undo in my opinion.

**Comment by DonJayamanne** [comment] 2022-01-20 18:58
I disagree with this feature.

both are two separate actions, adding input is one action, and adding output is a separate action by running the cell (can be done 2 days later)
Hence I'd expect to see just an undo for the input.

To me removing the input when undoing output is like expecting hitting undo on a file file edit to result in the deletion of the file, just because the file was first created and then edited to add contents.

**Comment by greazer** [comment] 2022-01-20 21:04
This is a side effect of notebooks having an implicit link to a runtime. Regular files do not have that. To me this is a question that a data scientist could probably answer better than any of us. Does it matter that the outputs of a notebook cell do not match the input code in general? Would users like a warning if they try this at the very least? Would they prefer it to be a setting? etc. etc.

**Comment by greazer** [comment] 2022-01-24 21:28
After discussing, we're closing for now. Soojin is going to keep an eye on how people expect reverts to happen with notebooks.

**Closed by greazer** 2022-01-24 21:28 UTC
Labels: under-discussion, notebook-diff
