### ISSUE TITLE
Show error in the folder

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#12461] opened 2016-09-22 15:55 UTC
- VSCode Version: 1.6.0-insider 25b370a
- OS Version: Windows 10

--Sorry for the English, I used Google Translator --

Steps to Reproduce:

1. When you open a folder VSCode it wrong in that inside the folder.
2. If we click it shows each location of the error.

![1](https://cloud.githubusercontent.com/assets/19866231/18755280/f769ac90-80c1-11e6-89d3-d825aa2b9307.png)

2. If we click on an error, it shows other error concerning that file.

![2](https://cloud.githubusercontent.com/assets/19866231/18755285/fd5c7b32-80c1-11e6-8b6e-6ef7515de1c8.png)

3. But we do not have the option to go back to see the other errors.
And when you close the tab related to the error even clean all design errors.

![3](https://cloud.githubusercontent.com/assets/19866231/18755290/01e2f50a-80c2-11e6-9541-4b155158c0e2.png)

**This is the Bootstrap files.

**Comment by chrmarti** [comment] 2016-09-22 18:29
I think this works as designed. The message when there are no problem is confusion though, it should say that no problems were detected in the _selected files/folder_ or similar.

**Comment by Tekbr** [comment] 2016-09-23 15:30
@chrmarti I believe he is not showing any errors that exist within the folder.

I made a change in npm.js taking parenthesis ')'. Reload Window. See that it only showed the css error. Opening the separate js file in a new window it showed the error that was not displayed when you open the entire folder.

![1](https://cloud.githubusercontent.com/assets/19866231/18791510/63fc8216-8189-11e6-9b5d-d05f5d41d5e4.png)

**Comment by sandy081** [comment] 2016-10-03 11:05
@Tekbr Current strategy of reporting errors is 

- they are generated when you open a file
- they are cleaned when you close the file

I am a bit surprised with the initial state of yours that shows problems when a folder selected. Can you please let me know if you have any extension installed that generated problems?

**Comment by Tekbr** [comment] 2016-10-03 16:58
I own these installed extensions.
You mean that this function not originally exist in vscode? So it would be interesting to show the same errors that may exist in my folder? Be css, js among others?
![1](https://cloud.githubusercontent.com/assets/19866231/19045220/fee5c6de-896d-11e6-8864-1b79e3c250c7.jpg)

**Comment by Tekbr** [comment] 2016-10-03 19:50
--Sorry for the English, I used Google Translator --

@sandy081 I believe that is not a problem but a resource of [HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) extension.

I close this issue and open another requesting similar feature that makes this extension, but for all files, making reference to this case? (Or if you prefer you create a new issue explaining better this question - my English is not very good)

The is at the discretion of you:
1. be a native form and allow the user to choose or not which file types should be checked the errors and warnings.
2. or an official extension to allow the user to choose or not which file types should be checked the errors and warnings.

What do you think?

**Comment by sandy081** [comment] 2016-10-04 07:47
@Tekbr Closing this issue since as you said it is due to HTML CSS Class Completion extension. I think the current out of the box functionality is good enough. Like the other extensions, this functionality can be implemented in an extension. So not filing a feature request for that.

Thanks

**Closed by sandy081** 2016-10-04 07:47 UTC
Labels: bug, error-list, needs more info

**Comment by Tekbr** [comment] 2016-10-04 19:42
@sandy081 If I understand correctly there is a feature request for this, so you mean?

Sorry for the little understanding of English.

**Comment by sandy081** [comment] 2016-10-05 06:11
@Tekbr No there is no feature request yet. What I meant was generating errors / warnings on a folder is not an intended behaviour to me. You can always write a new extension for doing that.

**Comment by Tekbr** [comment] 2016-10-08 02:20
@sandy081 Thanks for the answer. Yes, I said in a suggestion of extension or natively, but configured according to the user.
