### ISSUE TITLE
VS Code causes flickering on Menu Bar items even after uninstalling and re-installing the app

### ISSUE THREAD

**Issue by HarshvardhanJha1** [microsoft/vscode#97574] opened 2020-05-12 04:23 UTC
- VSCode Version:
1.45.0
x64
- OS Version:
Linux pop-os 5.4.0-7626-generic Pop_OS 20.04
Steps to Reproduce:
1. Open VS Code
2. Click on any of the menu bar items and move the mouse pointer from one item to another

Please check this URL for a screen recording of this issue: [https://youtu.be/dk_yVEpnmVs](url)

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur when GPU is disabled?: Yes

**Comment by deepak1556** [comment] 2020-05-13 02:55
This is tracked under https://github.com/microsoft/vscode/issues/80798, can you check if the issue is fixed with our exploration builds https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209 ? Thanks!

**Comment by HarshvardhanJha1** [comment] 2020-05-13 10:02
> This is tracked under #80798, can you check if the issue is fixed with our exploration builds [#94074 (comment)](https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209) ? Thanks!

Setting window.titleBarStyle: "custom" fixed it! Thanks a lot :100:

**Closed** 2020-05-13 10:02 UTC
Labels: linux, needs more info
