### ISSUE TITLE
HTML comments bug

### ISSUE THREAD

**Issue by peon501** [Microsoft/vscode#36728] opened 2017-10-23 07:31 UTC
- VSCode Version: newest
- OS Version: win 8.1

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1125765/31876865-e1b15300-b7dc-11e7-82be-d0cc4fb10a7e.png)

long comments like  ending with --> without space dont end but it should end.

Reproduces without extensions: I use smarty plugin, for smarty templates, but I have no idea if its because of that or its just a bug

**Comment by maxibanki** [comment] 2017-10-23 07:57
I don't think this is a VS Code issue. Referring to the [XML RFC paragraph 2.5](https://www.w3.org/TR/REC-xml/#sec-comments)

>  For compatibility, the string " -- " (double-hyphen) must not occur within comments.]

**Comment by peon501** [comment] 2017-10-23 08:49
ok got it :)

**Comment by yume-chan** [comment] 2017-10-23 10:21
Duplicate of #33944

**Closed** 2017-10-23 10:33 UTC
Labels: editor
