### ISSUE TITLE
Latest update killing a lot of extensions

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#60248] opened 2018-10-09 06:29 UTC
Issue Type: <b>Bug</b>

It seems that the latest updated went pretty bad for some extensions.
Any workaround to recover from that?
![image](https://user-images.githubusercontent.com/30625381/46650584-5b7ca700-cb9d-11e8-8281-c939d9176d83.png)

VS Code version: Code - Insiders 1.29.0-insider (9e017425b3d38cfc2d31a7375a28ff6d833ea4ae, 2018-10-09T05:11:01.507Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_680102 --inspect-extensions=51249|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
toggle-excluded-files|eam|1.6.0
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
vscode-pull-request-github|Git|0.1.7
beautify|Hoo|1.4.4
smarty|imp|0.3.0
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.85
vscode-gutter-preview|kis|0.15.1
php-symbols|lin|2.1.0
pomodoro|lky|1.1.2
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.10.2
color-highlight|nau|2.3.0
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.21.2
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
vscode-yaml|red|0.0.17
code-settings-sync|Sha|3.1.2
stylelint|shi|0.43.0
autoimport|ste|1.5.3
easy-snippet-maker|tar|0.0.6
Snippet|vsc|0.2.4
vim|vsc|0.16.9
quokka-vscode|Wal|1.0.151
vscode-import-cost|wix|2.9.0
sort-js-object-keys|zen|1.0.1

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment] 2018-10-09 06:32
Duplicate of #60168.

**Closed by egamma** 2018-10-09 06:32 UTC
Labels: *duplicate, insiders

**Comment by vinhjaxt** [comment] 2018-10-09 07:31
![image](https://user-images.githubusercontent.com/8877695/46653303-dced2d00-cbcf-11e8-904c-a1576aeccdc1.png)
me too,
Vetur not working anymore :((((((
