### ISSUE TITLE
Language selection is a mess

### ISSUE THREAD

**Issue by keiyunwong** [Microsoft/vscode#56518] opened 2018-08-16 01:55 UTC
Issue Type: <b>Bug</b>

When I want to change version of Python, the selection list is a mess, and items huddle together. If you guys make an improvement in the next version, please inform me if applicable. Thanks a lot.
![image](https://user-images.githubusercontent.com/28135009/44182603-3ab64900-a13a-11e8-84cb-de283a01a807.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.81GB free)|
|Process Argv|/private/var/folders/wd/n7grvlw52tz07g2d4rtnf_k00000gn/T/AppTranslocation/F03AA19F-89AA-4946-817C-05B3EDF023EE/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12
python|ms-|2018.7.1

(4 theme extensions excluded)

</details>

**Comment by beastdestroyer** [comment] 2018-08-16 05:32
Something similar happened in #56499, I suggested to open Developer Tools and see if that text is a jumble of redundant elements, otherwise it might seems to be a one off thing and be related to render issues entirely

**Comment by sandy081** [comment] 2018-08-16 12:25
Can you please provide the steps to reproduce ?

**Comment by keiyunwong** [comment] 2018-08-16 16:06
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Certainly. Just click the red rectangle area, then the list is huddling.


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

       
    

    On 08/16/2018 20:26，Sandeep Somavarapu<notifications@github.com> wrote： 


Can you please provide the steps to reproduce ?

**Comment by bpasero** [comment] 2018-08-17 09:42
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2018-08-24 05:16
Ah so this seems to be coming from an extension. Moving to @chrmarti , see the UI glitch in https://github.com/Microsoft/vscode/issues/56518#issue-351027313 specifically.

**Closed** 2018-08-29 09:17 UTC
Labels: bug, quick-pick
