### ISSUE TITLE
Code folding delete issue

### ISSUE THREAD

**Issue by texsol-p0941** [microsoft/vscode#93832] opened 2020-03-31 07:45 UTC
Issue Type: <b>Bug</b>

Issue in code folding of html tags in React js code.,
Previously it was easy to delete a block of code, when that block is folded.
Now when I delete it will only delete the first line. Please fix the issue.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
path-autocomplete|ion|1.13.6
rainbow-csv|mec|1.6.0
code-beautifier|mic|2.3.3

</details>

**Comment by aeschli** [comment] 2020-03-31 08:30
Nothing has changed here. But remember that you need to select from the first line to the last.

Duplicate of https://github.com/microsoft/vscode/issues/72422

**Closed by aeschli** 2020-03-31 08:30 UTC
