### ISSUE TITLE
Tab wrap - tab should not fill all spare space when wrap to new line

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#113801] opened 2021-01-05 07:16 UTC
![image](https://user-images.githubusercontent.com/1876302/103617216-d72a5180-4f68-11eb-975f-bc6abb05f55f.png)

The latest row should have consistent behavior with the single row

**Comment by bpasero** [comment] 2021-01-05 08:45
@heartacker the reason tabs currently grow is the following pattern that imho is a bit unpleasant otherwise:

![image](https://user-images.githubusercontent.com/900690/103624979-9adffc80-4f3a-11eb-90f9-52f9e6506842.png)

As you can see each row would have an uneven gap on the right hand side.

As a workaround, if you configure `workbench.editor.tabSizing` tabs will have a fixed width and not grow:

![image](https://user-images.githubusercontent.com/900690/103625070-b6e39e00-4f3a-11eb-9402-cd66bfb37216.png)

**Comment by gjsjohnmurray** [comment] 2021-01-05 09:43
@bpasero how about making them grow on every line except for the last one?

**Comment by bpasero** [comment] 2021-01-05 09:47
@gjsjohnmurray this is a good idea but to my knowledge there is no CSS rule that we could leverage here because the wrapping is entirely done via the `flex` layout of the browser. Best we can do is control the growing for the last tab, but not all tabs of the last row.

@SneakyFish5 and @DynDux fyi for CSS tricks maybe I am missing something here.

**Comment by bpasero** [comment] 2021-01-06 07:05
From https://github.com/microsoft/vscode/pull/106448#issuecomment-754978183

![image](https://user-images.githubusercontent.com/900690/103739427-e60b1580-4ff5-11eb-864d-45da63d563fd.png)

**Comment by SneakyFish5** [comment] 2021-01-07 05:11
Here's an accompanying visual for @DynDux's proposed change:

![sMfvSBbQ8t](https://user-images.githubusercontent.com/32284796/103853743-6e300000-5074-11eb-9fb5-9703bc1fdcf3.gif)

**Comment by heartacker** [comment] 2021-01-07 05:13
> Here's an accompanying visual for @DynDux's proposed change:
> 
> ![sMfvSBbQ8t](https://user-images.githubusercontent.com/32284796/103853743-6e300000-5074-11eb-9fb5-9703bc1fdcf3.gif)
> 

great

**Comment by bpasero** [comment] 2021-01-07 06:41
Nice, I suggest to continue via a PR.

**Comment by bpasero** [comment] 2021-01-07 10:38
@SneakyFish5 @DynDux given we also have https://github.com/microsoft/vscode/issues/113926 as an issue I wonder if we should revisit the editor actions toolbar altogether when tabs wrap: what if we simply treat the editor actions toolbar as a "tab", always being the last "tab" in the strip. This would:
* avoid having to use the `margin-right` hack an absolute positioning as the actions would then always appear last
* fix https://github.com/microsoft/vscode/issues/113926 by automatically wrapping these actions to the next line when space is little
* fix this issue: we could configure this last "fake" tab to always fill the remaining space

Thoughts?

**Comment by DynDux** [comment] 2021-01-12 09:02
@bpasero I commented on PR #113926 but see it's closed. So here again:

If the editor actions are just a tab, a clean css-only solution is easy. I created a new fiddle and tried to use the original class names and structure. I also commented the relevant css parts for the layout. Hope it is clear - otherwise please let me know what else you need:

https://jsfiddle.net/seywr7m9/

**Comment by bpasero** [comment] 2021-01-12 09:29
Yeah thanks, I think the biggest challenge is the actual implementation of the editor actions being a "fake" tab. Unfortunately that is not "just" a CSS change (as far as I can tell), but needs a bit of coding and care because lots of operations assume that the children in the tabs container are all tabs, and not "fake" tabs.

**Comment by jjspace** [comment] 2021-02-09 17:19
Any update on this? I like the idea of wrapping tabs but the expanding last row is really throwing me off

**Comment by DynDux** [comment] 2021-02-09 17:56
@jjspace Until a fix is merged, you can use the extension "Custom CSS and JS Loader" with the following css snippet as a workaround:
```

.monaco-workbench .part.editor>.content .editor-group-container>.title>.tabs-and-actions-container.wrapping .tabs-container>.tab.sizing-fit {
  flex-grow: 0;
}
.monaco-workbench .part.editor>.content .editor-group-container>.title>.tabs-and-actions-container.wrapping .tabs-container::after {
  content: '';
  flex-grow: 20;
}
```

**Comment by bpasero** [comment] 2021-02-09 18:57
Instead of patching our CSS (which we strongly advise against), please see an easy solution via settings in https://github.com/microsoft/vscode/issues/113801#issuecomment-754495248

**Comment by DynDux** [comment] 2021-02-10 09:54
Sorry - of course you are absolutely right! I didn't want to give bad advises and messing with the app shouldn't be done.
I just wanted to help jjspace because setting the "Tab Sizing" to _shrink_ will cut off the filenames which, although intended by the setting, maybe sometimes looks confusing:

![image](https://user-images.githubusercontent.com/76206890/107491566-9e931e80-6b8b-11eb-8ab6-e2c9c170d292.png)

If I can help to improve the behavior, please let me know!

**Comment by clottman** [comment] 2021-02-24 16:28
Does using `"workbench.editor.tabSizing": "shrink",` along with ` "workbench.editor.wrapTabs": true,` still work? 

When I add in the `tabSizing: shrink` option, the wrap tabs setting is ignored entirely and everything goes back onto one line.

**Comment by bpasero** [comment] 2021-02-24 16:47
@clottman yeah that should still work, are you using stable or insiders of VSCode?

![recording (1)](https://user-images.githubusercontent.com/900690/109034845-57974400-76c8-11eb-89f2-7e8725dd74d5.gif)

**Comment by clottman** [comment] 2021-02-24 17:34
I'm on stable, on mac. Here's some info about my setup:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0
```
![image](https://user-images.githubusercontent.com/4480480/109041032-39175580-7694-11eb-833f-9f15d42601a0.png)

**Comment by bpasero** [comment] 2021-02-24 18:01
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by clottman** [comment] 2021-02-25 15:15
Huh, my computer updated this morning from Mac OS 11.1 to mac OS 11.2.1 and it works now, without trying the nightly insider build. Strange. 

Thanks for your help!

**Closed** 2021-03-01 09:14 UTC
Labels: feature-request, help wanted, workbench-tabs

**Comment by bpasero** [comment] 2021-03-01 09:39
via https://github.com/microsoft/vscode/commit/3c62a8f898b79dfe2ce384d3c333fb06486119db the growing of tabs now only applies to the last tab in a row (except for the last row) and the overall result is a much calmer tab sizing behaviour when tabs wrap:

**Before**
![tabs-before](https://user-images.githubusercontent.com/900690/109479197-7146db80-7a7a-11eb-80d0-fb25771d03c3.gif)

**After**
![tabs-after](https://user-images.githubusercontent.com/900690/109479230-760b8f80-7a7a-11eb-98a5-b23a949be670.gif)
