### ISSUE TITLE
[json] No value suggestions in project.json for dependencies property

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2331] opened 2016-01-26 13:32 UTC
![capture](https://cloud.githubusercontent.com/assets/1931590/12581872/a957344a-c439-11e5-824b-49920f6bc255.png)

**Comment by dbaeumer** [comment] 2016-01-26 13:35
Same is true for project.json:
![capture](https://cloud.githubusercontent.com/assets/1931590/12581924/186599da-c43a-11e5-8ff6-7c9661c37deb.png)

**Comment by aeschli** [comment] 2016-01-27 11:37
For Bower we never had an API that would give all versions.
But for project.json we had and it seems that the web service that provided us the results is not working anymore.

**Comment by aeschli** [comment] 2016-03-03 15:14
duplicate of #3204

**Closed by aeschli** 2016-03-03 15:14 UTC
Labels: bug, json
