### ISSUE TITLE
Render problem under high DPI monitor

### ISSUE THREAD

**Issue by chrisxvin** [Microsoft/vscode#6082] opened 2016-05-04 01:36 UTC
- VSCode Version: 1.1.0-insider, 
- OS Version: Win10 Pro

I got two different text render styles, one is blurry, and another is clear.
![image](https://cloud.githubusercontent.com/assets/628293/15003152/68b30c4e-11db-11e6-961d-c06e76d8ebba.png)

You can see middle window is more blurry than both left and right window.
My monitor size is 13 inches, with 1920x1080 resolution. Display zoom level is **125%**, and I've set up **Code - Insiders.exe**'s compatible settings, and checked '**Disable display zoom under high DPI**' (may be this, as I'm using a Chinese edition). 

My settings:
![image](https://cloud.githubusercontent.com/assets/628293/15003219/37d97896-11dc-11e6-9131-109af8bf26a4.png)
![image](https://cloud.githubusercontent.com/assets/628293/15003227/5276f0fc-11dc-11e6-9ac0-29e46431a86f.png)

**Comment by lediur** [comment] 2016-05-04 02:48
Is this related to #1896?

**Comment by joaomoreno** [comment] 2016-05-04 05:50
Duplicate of #1896 👍

**Closed by joaomoreno** 2016-05-04 05:50 UTC
