### ISSUE TITLE
External terminal set to Cmder, "Open in Command Prompt" doesn't open in correct directory

### ISSUE THREAD

**Issue by joshpeng** [Microsoft/vscode#13921] opened 2016-10-18 05:39 UTC
- VSCode Version: 1.6.1
- OS Version: Win7 x64

Steps to Reproduce:

1. Added system environment path to my Cmder install
2. In settings.json I have ```"terminal.external.windowsExec": "Cmder.exe"```
3. When I right click on a folder in the Explorer and select "Open in Command Prompt" it launches Cmder, but doesn't auto-navigate me to the directory I just selected on. It opens me at the default Cmder directory instead

**Comment by joshpeng** [comment] 2016-10-19 21:32
I believe the issue with Cmder start directories may be related to the cmdArgs used when spawning the terminal.


Cmder seems to use ```/start```, but [line 74](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminalService.ts#L74) of code only has it as ```start```. [Line 50](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminalService.ts#L50) exhibits the same as well.

Cmder launched like this ```cmder.exe /start c:/someDir``` would open ```C:/someDir```.

**Comment by Tyriar** [comment] 2016-10-22 17:52
This is a duplicate of https://github.com/Microsoft/vscode/issues/6466

**Closed** 2016-10-22 18:33 UTC
Labels: bug, duplicate, integrated-terminal, windows
