### ISSUE TITLE
~/.bash_profile not compatible?

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#7279] opened 2016-06-07 01:55 UTC
- VSCode Version: Version 1.2.0 (1.2.0)
- OSX Version: 10.11.5

```bash
#!/bin/bash
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export GOAPP=$HOME/go_appengine
export JSBIN=$HOME/node_modules/.bin/
export ANDROID=$HOME/Library/Android/sdk/platform-tools/
export PATH=$PATH:$GOBIN:$GOAPP:$JSBIN:$ANDROID
export EDITOR="code"
export VISUAL="code"
export CLICOLOR=1
function prompt {
    EXITSTATUS="$?"
    BOLD="\[\033[1m\]"
    RED="\[\033[1;31m\]"
    GREEN="\[\e[32;1m\]"
    BLUE="\[\e[34;1m\]"
    OFF="\[\033[m\]"

    PROMPT="\u@\h ${BLUE}\W${OFF}"

    if [ "${EXITSTATUS}" -eq 0 ]
    then
       PS1="${PROMPT}${BOLD}${GREEN}/${OFF} "
    else
       PS1="${PROMPT}${BOLD}${RED}/${OFF} "
    fi

    PS2="${BOLD}>${OFF} "
}
export PROMPT_COMMAND=prompt
```
It seems it does execute `.bash_profile` but it doesn't do it correctly on startup?
After doing it manually it works? (see screenshots)

![image](https://cloud.githubusercontent.com/assets/863731/15843453/9051f25a-2c62-11e6-96a2-5e5ec2e13a62.png)
![image](https://cloud.githubusercontent.com/assets/863731/15843499/e4fba116-2c62-11e6-83d9-2439411f7a1f.png)

**Comment by Tyriar** [comment] 2016-06-07 02:06
Duplicate of https://github.com/Microsoft/vscode/issues/7263

**Closed by Tyriar** 2016-06-07 02:06 UTC

**Comment by gertcuykens** [comment] 2016-06-07 02:22
The workaround does work for me, thanks

```bash
#!/bin/bash
if [ -r ~/.bashrc ]; then
  . ~/.bashrc
fi
```
