### ISSUE TITLE
CodeLens overlapping text

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#79521] opened 2019-08-20 15:47 UTC
Please see

![image](https://user-images.githubusercontent.com/22951521/63361660-8350a580-c33e-11e9-8797-eb921aaed15f.png)

- VSCode Version: 1.37.1
- OS Version: Windows 10

Steps to Reproduce:

1. Unsure how to reliably reproduce, but as you can see above it did happen.

Does this issue occur when all extensions are disabled?: N/A. I am using [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) to demonstrate the issue, but the issue is with the editor rendering, which should not be affected by extensions, and the CodeLens API which requires that an extension utilize it.

**Comment by usernamehw** [comment] 2019-08-20 16:51
Possible duplicate of #71745

**Comment by RMacfarlane** [comment] 2019-08-20 18:14
Thanks @usernamehw, I think this is indeed a duplicate of #71745.

@KamasamaK there should be a fix for this in the Insider's version of VSCode, you can try it out or wait for the next stable release. Thanks!

**Closed by RMacfarlane** 2019-08-20 18:14 UTC
