### ISSUE TITLE
Random focus shifting

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121844] opened 2021-04-21 16:25 UTC
@isidorn 

- open run / debug
- open "views and more actions"
- toggle an option in that list
- keyboard focus should land back on "views and more actions" button

**Comment by isidorn** [comment] 2021-04-21 17:17
I can reproduce this and this is a bug. I can investigate further and try to fix this.

**Comment by isidorn** [comment] 2021-04-22 13:19
Aha the issue is that the whole title area toolbar gets "changed", and thus we have new actions coming in, or old actions being removed. Thus the focus is not preserved. Not so straighforward to fix.

**Comment by isidorn** [comment] 2022-04-25 13:40
Sounds like a view / action bar issue. For now assigning to @sbatten and he can forward if needed.

**Comment by sbatten** [comment] 2022-12-29 20:28
This issue no longer seems to reproduce on native or custom menus.

**Closed by sbatten** 2022-12-29 20:28 UTC
Labels: bug, accessibility
