### ISSUE TITLE
Javascript updating imports when change name change node_modules packages

### ISSUE THREAD

**Issue by aigic** [Microsoft/vscode#53109] opened 2018-06-27 09:10 UTC
Issue Type: <b>Bug</b>

Hi , I wanted a change name of a js(to be descriptive a vuex module) file and and vs code (Insiders) suggested me to change the name of imports too.After accepting I saw vs code changed some files in node_modules.(Obviously there were no imports of that file in my packages:).)
I think it would be a good idea to exclude node_module path from this feature.

Thanks for nice app

VS Code version: Code - Insiders 1.25.0-insider (b7e6e04666ca8dde560b69081c43365dce77d12a, 2018-06-22T05:11:25.722Z)
OS version: Darwin x64 17.5.0

**Comment by mjbvz** [comment] 2018-06-27 17:12
Duplicate of #51970

Added workaround on the VS Code side. Should be the newest insiders

**Closed by mjbvz** 2018-06-27 17:12 UTC
Labels: javascript
