### ISSUE TITLE
Auto fill all text when ctrl+F

### ISSUE THREAD

**Issue by shernk** [microsoft/vscode#123298] opened 2021-05-07 15:29 UTC
- VS Code Version: 1.56.0
- OS Version: Windows x64

Steps to Reproduce:

After you ctrl+F
- The result that you expected
![2](https://user-images.githubusercontent.com/31926953/117472147-caebea80-af82-11eb-953d-71f46d7d8041.png)
- The result showed
![1](https://user-images.githubusercontent.com/31926953/117472262-e8b94f80-af82-11eb-8d3b-1e887a61e25e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by nrayburn-tech** [comment] 2021-05-07 19:13
Duplicate of https://github.com/microsoft/vscode/issues/123044.

**Closed** 2021-05-07 21:56 UTC
Labels: *duplicate, new release
