### ISSUE TITLE
Syntax Highlight Problem When writing codeblock in Markdown

### ISSUE THREAD

**Issue by plehdeen** [Microsoft/vscode#40141] opened 2017-12-13 02:16 UTC
- VSCode Version: 1.18.1
  - OS Version: Windows 10
take this pic as a example, the syntax highlight not work for the code in the bracket...
Can someone just give me some tip if it's my own problem.

![33832924-d1f0bf8e-deb8-11e7-9703-2fbd93953e4d](https://user-images.githubusercontent.com/12212092/33918493-9b9711d6-dfee-11e7-9eaa-40ecfc26b2a1.png)

**Comment by mjbvz** [comment] 2017-12-13 02:19
Please post the source code along with the screenshot

**Comment by plehdeen** [comment] 2017-12-13 03:13
it's the test code in the pic above

```c

struct mm{
    int tt;
};

static int f(int a){
    return a;
}
//comment is ok not in the code block
int *f2(int b){
    //comment and syntax highlight not work here !!!
    int *a=&b;
    return a;
}

```

**Comment by mjbvz** [comment] 2017-12-13 18:43
Thanks. This is a duplicate of #34525

**Closed by mjbvz** 2017-12-13 18:43 UTC
Labels: grammar, markdown, needs more info
