### ISSUE TITLE
Depreciation of function in JavaScript

### ISSUE THREAD

**Issue by julienallexandre** [microsoft/vscode#85606] opened 2019-11-26 15:59 UTC
### Is there an extension or an option that allows vs code to mount when a function is obsolete in javascript of this style? 

<a href="https://www.noelshack.com/2019-48-2-1574783919-java-deprecated-method.png"><img src="https://image.noelshack.com/minis/2019/48/2/1574783919-java-deprecated-method.png" border="0" alt="1574783919-java-deprecated-method.png - envoi d'image avec NoelShack" title="1574783919-java-deprecated-method.png"/></a>

**Comment by IllusionMH** [comment] 2019-11-26 16:06
/duplicate of #84580

This should be implemented in TS side and tracked in https://github.com/microsoft/TypeScript/issues/33093 and https://github.com/microsoft/TypeScript/issues/33092

**Closed** 2019-11-26 16:07 UTC
Labels: *duplicate

**Comment by julienallexandre** [comment] 2019-11-27 11:06
Okay, nothing answers my question.

**Comment by IllusionMH** [comment] 2019-11-27 11:20
General questions should be asked on StackOverflow.

JS/TS suggestions in VS Code are powered by TS. I linked 2 TS issues that track implementation of this feature (strike out deprecated items).
Support in VS Code would be when those 2 issues will be resolved (I doubt that there will be any extension that can track deprecated methods across project without help of TS).
