### ISSUE TITLE
Cannot register two commands with the same id: `_workbench.openUserSettingsEditor`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#203165] opened 2024-01-23 15:17 UTC
Saw this in insiders:

```
ERR Cannot register two commands with the same id: _workbench.openUserSettingsEditor: Error: Cannot register two commands with the same id: _workbench.openUserSettingsEditor
at [./platform/actions/common/actions.ts:586:8](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/platform/actions/common/actions.ts#L586)
at [./workbench/contrib/preferences/browser/preferences.contribution.ts:1237:83](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L1237)
([./workbench/contrib/preferences/browser/preferences.contribution.ts:1261:3](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts#L1261))
at [./base/common/event.ts:1127:12](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/base/common/event.ts#L1127)
at [./base/common/event.ts:1138:8](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/base/common/event.ts#L1138)
at [./base/common/event.ts:1162:8](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/base/common/event.ts#L1162)
at [./workbench/services/userDataProfile/common/userDataProfileService.ts:38:34](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/services/userDataProfile/common/userDataProfileService.ts#L38)
at [./workbench/services/userDataProfile/browser/userDataProfileManagement.ts:165:36](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/services/userDataProfile/browser/userDataProfileManagement.ts#L165)
at [./workbench/services/userDataProfile/browser/userDataProfileManagement.ts:127:2](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/services/userDataProfile/browser/userDataProfileManagement.ts#L127)
at [./base/common/actions.ts:194:2](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/base/common/actions.ts#L194)
at [./base/common/actions.ts:185:3](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/base/common/actions.ts#L185)
at [./workbench/services/contextmenu/electron-sandbox/contextmenuService.ts:259:3](https://github.com/microsoft/vscode/blob/800e60abdfb1675a59520bac6a9473bc380d49ea/src/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.ts#L259)
```

**Comment by rzhao271** [comment] 2024-01-23 18:54
I don't see this error. Some clarification questions:

- What type of workspace is this in? Is it a single-root or multi-root workspace?
- Which settings JSON files did you open, if any?
- Did you open the Settings editor? If so, which tabs did you navigate to?

**Comment by bpasero** [comment] 2024-01-23 18:56
Sorry I do not recall, I was hoping from the stack its pretty clear that there is multiple locations where a command is registered with the same ID?

**Comment by rzhao271** [comment] 2024-01-23 19:03
Looks like it occurs when switching profiles due to the way the contribution code works.

**Comment by rzhao271** [comment] 2024-06-24 16:45
Duplicate of #213840

**Closed by rzhao271** 2024-06-24 16:45 UTC
Labels: bug, settings-editor, confirmed
