### ISSUE TITLE
Black Pull Down and Titlebar Menus

### ISSUE THREAD

**Issue by TedGriggs** [microsoft/vscode#98924] opened 2020-05-31 23:22 UTC
Installed VS Code on new install of guest of Debian 10.4 with KDE Plasma within a VirtualBox 6 VM on a Windows 10 host.  When running code with the gpu enabled, pull down menus are rendered as black.  Moving between menus sometimes gets them to render properly, but moving between menus again can turn them back to black.  Clicking in the black, chooses a menu item as if it were visible.

Running code with the gnu-disabled flag, eliminates the problem.  All other 3D accelerated applications seem to work fine, so this seems to be something particular to code.

I think this is the same issue as the closed issue:
https://github.com/Microsoft/vscode/issues/72302

However, hopefully, this information is enough to reproduce.  The GPU in the machine is a RTX 2060.

**Comment by mathisgag** [comment] 2020-06-03 17:53
Same issue with closed issue #94361 in exploration version.

**Comment by deepak1556** [comment] 2020-06-25 07:26
Can you check if the insiders version work fine without disabling gpu acceleration https://code.visualstudio.com/insiders/

**Comment by mathisgag** [comment] 2020-06-25 14:34
Same problem (with the insiders version 1.47.0), after 10 min of utilisation (tried twice). This time the whole application froze (cannot do anything other than open the black menus and do a right click to open another black menu).
Hope this helps

**Comment by deepak1556** [comment] 2020-06-25 21:47
@mathisgag are you also using virtualbox vm ?

**Comment by mathisgag** [comment] 2020-06-25 21:53
Yes, I am also using virtualbox vm. (Running XUbuntu20.04)

**Comment by deepak1556** [comment] 2020-06-25 22:29
Is it any better when you use `"window.titleBarStyle": "native"`

**Comment by mathisgag** [comment] 2020-06-26 12:31
In the Insider version, my title bar style was already (by default) as native (see picture). I don't know if that's what you meant... 
![image](https://user-images.githubusercontent.com/43070865/85857203-6919fc00-b787-11ea-8544-45af6c3e409e.png)

**Comment by deepak1556** [comment] 2020-06-26 19:20
Yup thats correct, in that case how does it look with custom titlebar ?

Can you also confirm if you see this issue with https://github.com/electron/fiddle/releases/tag/v0.15.1 , you can try electron versions `7.3.1`, `8.3.3` and `9.0.5`

**Comment by mathisgag** [comment] 2020-06-29 20:41
Switching to the custom TitleBar fixes the issue on vsCode version 1.46.1 and vsCode Insider v 1.47 . I had gpu acceleration enabled and the Title bar to custom for half a day of work on the official version and I didn't encountered the issue. 
I tried Electron fiddle with electron v 7.3.1 and didn't encountered the issue, but I only tried for 5 mins.

Plus: The custom title bar looks cool!

**Comment by prjemian** [comment] 2020-07-06 15:05
This *is* a duplicate of #84745

**Closed** 2020-11-05 10:04 UTC
Labels: gpu, linux, virtual-machine
