### ISSUE TITLE
Horizontal scrollbar is broken.

### ISSUE THREAD

**Issue by panzi** [microsoft/vscode#96928] opened 2020-05-04 16:08 UTC
- VSCode Version: 1.44.2 ff915844119ce9485abfe8aa9076ec76b5300ddd x68
- OS Version: Fedora Linux 5.6.8-200.fc31.x86_64

Steps to Reproduce:

1. Write code that is longer than one screen and wider than one screen
2. Try to drag the hotizontal scrollbar to the end of the long line

Does this issue occur when all extensions are disabled?: Not sure.

I launched `code --disable-extensions` and now the bug doesn't even occur with extensions enabled again anymore. Weird.

Here is a video that demonstrates the issue:
https://www.youtube.com/watch?v=iljabc6RusA

**Comment by alexdima** [comment] 2020-05-06 14:17
@panzi I have tried to reproduce, but could not, clicking and dragging the scrollbar works fine for me. From your video, it is not clear to me if you click on the scrollbar or like 1px above it.

Please let me know what else I should do to try to reproduce.

**Comment by panzi** [comment] 2020-05-06 14:53
I clicked when the scrollbar got highlighted. I assumed the mouse is over the scrollbar when it's highlighted. There are like two pixels that I can actually click for it to recognize the scrollbar, because most of it is an invisible drag handle to drag in a shell.

Another video where you can see how exact you have to hit the scrollbar and it still didn't work right: https://www.youtube.com/watch?v=MwcPAfBkqSE

**Comment by alexdima** [comment] 2020-05-06 15:48
@joaomoreno I don't know if you're the person for this, but I can also reproduce that the "drag the panel" area is completely over the editor scrollbar. I wonder why could we not move this to be more over the status bar since that is higher than the scrollbar and has more pixels to click on.

**Comment by joaomoreno** [comment] 2020-05-08 16:10
@alexdima While I don't dispute the fact that the sash is on top of the horizontal scrollbar, which it is:

![image](https://user-images.githubusercontent.com/22350/81424872-e5646b80-9156-11ea-8206-761bc608676a.png)

I believe the user isn't talking about the sash, but rather that there seems to be a mismatch between the sash being highlighted and being hit on: when they click and drag it's as if they're setting and dragging the editor cursor, instead of the scrollbar handling the event. Maybe some strange browser rounding error due to a device pixel ratio of >1?

**Comment by alexdima** [comment] 2020-05-11 09:57
> Nevertheless, placing the sash on top of the status bar also doesn't seem to be a good solution

Why not? The status bar is most of the times empty and not clickable, while the scrollbar is always clickable. What is especially ugly here is that the scrollbar reacts to the mouse hover and fades in, making it appear ready to be responsive to the click, but then the click doesn't reach it.

> Instead of moving it 2px down, how do you feel about making the horizontal scroll bar 2px taller?

:+1: We can also do this.

**Comment by joaomoreno** [comment] 2020-05-11 10:08
> What is especially ugly here is that the scrollbar reacts to the mouse hover and fades in, making it appear ready to be responsive to the click, but then the click doesn't reach it.

But it doesn't seem to be because of the sash: otherwise the sash would be moved, instead of the text being selected, right?

**Comment by alexdima** [comment] 2020-05-11 12:30
@joaomoreno I cannot reproduce the initial issue in the opening post. I would fix it if I could reproduce. But then the discussion expanded and we landed on how the scrollbar is covered by the sash in the bottom...

**Comment by joaomoreno** [comment] 2020-05-11 12:57
I also can't repro it. I have plenty of space to select the scrollbar and it seems to always work as the hover feedback predicts it to work.

So, let's pump the editor's horizontal scrollbar height?

**Comment by joaomoreno** [comment] 2020-05-11 13:21
Related to https://github.com/microsoft/vscode/issues/84315#issuecomment-559138911

**Comment by joaomoreno** [comment] 2020-05-11 13:41
Sash was moved to be on top of both the editor and the status bar, half half.

**Closed** 2020-05-11 13:40 UTC
Labels: bug, ux

**Comment by alexdima** [comment] 2020-05-11 14:00
I've also increased the default height from 10px to 12px, so whereas before there were 6px to hit the horizontal scrollbar (10px-4px), now there should be 10px (12px-2px).
