### ISSUE TITLE
i cannot download extensions

### ISSUE THREAD

**Issue by lauramagali** [Microsoft/vscode#57913] opened 2018-09-04 23:41 UTC
Issue Type: <b>Bug</b>

i cannot download extensions, the marketplace says : not extension found, it doens't search anything.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2370)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|3.75GB (0.49GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|1.6.1
auto-rename-tag|for|0.0.15
sublime-babel-vscode|jos|0.2.10
vscode-language-babel|mgm|0.0.20
quokka-vscode|Wal|1.0.143

</details>

**Comment by cliffkoh** [comment] 2018-09-05 00:03
Duplicate of https://github.com/Microsoft/vscode/issues/57851

**Comment by syk543277780** [comment] 2018-09-05 00:10
The whole SOUTH CENTRAL US server was down in 12 hours ago. 
Here is the link you can check the status : [https://azure.microsoft.com/en-us/status/](https://azure.microsoft.com/en-us/status/)

**Closed** 2018-09-05 00:40 UTC
Labels: *duplicate, extensions
