### ISSUE TITLE
New arrow in diff editor needs tooltip

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#155353] opened 2022-07-15 23:33 UTC
<img width="120" alt="image" src="https://user-images.githubusercontent.com/323878/179324327-5accac40-7e3a-4427-86bc-015be256958f.png">

Useful feature but this should tell me what I'm going to do before I click it

**Comment by yume-chan** [comment] 2022-07-16 15:58
#152088

**Comment by hediet** [comment] 2022-07-18 09:56
Duplicate of #152088.

**Closed by hediet** 2022-07-18 09:56 UTC
