### ISSUE TITLE
disable extension pack should disable individuals

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#18428] opened 2017-01-12 01:24 UTC
- VSCode Version: 1.8.1

Using "PHP Extension Pack" as an example.
It contains "PHP Debug" and "PHP IntelliSense".

Disable it ("disable by workspace") only disable itself. I need to disable "PHP Debug" and "PHP IntelliSense" individually.

**Comment by mjbvz** [comment] 2017-01-12 01:56
Duplicate of #16666. You can find more discussion of this behavior on #14440

**Closed by mjbvz** 2017-01-12 01:56 UTC
Labels: duplicate
