### ISSUE TITLE
Incorrect rendering of some ASCII in Terminal. Try F7

### ISSUE THREAD

**Issue by shanselman** [Microsoft/vscode#7900] opened 2016-06-20 19:09 UTC
- VSCode Version: 1.2.1
- OS Version: Win10 10586

Steps to Reproduce:

1. Open Terminal. Do some commands.
2. Press F7

![image](https://cloud.githubusercontent.com/assets/2892/16206917/814e44ca-36df-11e6-87fb-50da8a4772b3.png)

I tried it on VSCode 1.3.0 and it is closer, but there's weird spacing:

![image](https://cloud.githubusercontent.com/assets/2892/16206956/ae3a5168-36df-11e6-90a6-187d1ef7ecee.png)

**Comment by Tyriar** [comment] 2016-06-21 17:27
Duplicate of https://github.com/Microsoft/vscode/issues/7911 - should be fixed soon.

**Closed** 2016-06-21 17:34 UTC
Labels: bug, integrated-terminal
