### ISSUE TITLE
Hot Exit: Editor view state is not restored

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16822] opened 2016-12-07 14:20 UTC
Testing #16544

* run `code-insiders notes2.txt` where `notes2.txt` does not exist on disk
* type something in it
* close the window
* start Code Insiders from the taskbar
* switch from the Untitled file to `notes2.txt`
> Observe: cursor position is at (1;1), the scroll state, the folding regions, etc. are not maintained.

**Comment by bpasero** [comment] 2016-12-07 15:45
I would think this is a duplicate of https://github.com/Microsoft/vscode/issues/16588

**Closed** 2016-12-07 19:02 UTC
