### ISSUE TITLE
Add space on the bottom of Explorer

### ISSUE THREAD

**Issue by secretgspot** [Microsoft/vscode#38255] opened 2017-11-13 22:03 UTC
- VSCode Version: latest
- OS Version: latest

Steps to Reproduce:

1. When you have a large list of folders in Explorer that requires scrolling and you're trying to create a new folder in ROOT directory and have any folder selected, it's impossible to create a folder from within an application.  When clicking Add new folder from explorer toolbar that appears on mouseover explorer header it creates a folder in a selected folder and it's impossible to deselect a folder.  Make same menu appear on mouseover of subdirectories of a parent or allow margin space on the bottom of a list where click is possible to deselect a folder or right click to deselect a folder.

2. It appears that you can click Collapse All or Refresh to deselect a folder but it's too confusing and not intuitive. 

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment] 2017-11-17 09:54
Duplicate of https://github.com/Microsoft/vscode/issues/1043

**Closed by isidorn** 2017-11-17 09:54 UTC
Labels: feature-request, file-explorer
