### ISSUE TITLE
Search editor: Add hover to context lines hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#227684] opened 2024-09-05 11:16 UTC
It's not obvious that this text box is for context lines. A hover would clear this up

![Image](https://github.com/user-attachments/assets/bcdd1850-834b-4a9d-8e87-da27e4a23dd2)

**Comment by osortega** [comment] 2024-12-19 04:05
Duplicate of https://github.com/microsoft/vscode/issues/169322
Closing this one in favor of the older one

/duplicate

**Closed by osortega** 2024-12-19 04:05 UTC
Labels: bug, search
