### ISSUE TITLE
Difficulty selecting horizontal text when wordwrap disabled and minimap enabled.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#21822] opened 2017-03-02 19:51 UTC
- VSCode Version: 1.10.1(653f873) and 1.11.0-insider (0bc62d1)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Difficulty selecting horizontal text when wordwrap is disabled using mouse, with minimap enabled

See differs in VSCode and Atom.

![select](https://cloud.githubusercontent.com/assets/19866231/23524204/6168d51a-ff68-11e6-99a4-c1159094e8e4.gif)

**Comment by alexandrudima** [comment] 2017-03-03 17:19
Duplicate of #21729

**Closed by alexandrudima** 2017-03-03 17:19 UTC
Labels: bug, editor-minimap
