### ISSUE TITLE
Settings editor scrolls up/down while selecting elements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#206239] opened 2024-02-26 12:59 UTC
* open settings ui
* search for `editor.suggest`
* have a viewport from "Editor > Suggest: Show Fields" until "Editor > Suggest: Show Keyword"
* keep pressing the `editor.suggest.showInlineDetails` options
* 🐛 the editor scroll upwards each time I click

https://github.com/microsoft/vscode/assets/1794099/b8e8221b-0460-458d-9bb5-7c4de3a2e851

**Comment by rzhao271** [comment] 2024-02-26 15:40
That doesn't look like the right screen recording, but I believe this issue is a duplicate of https://github.com/microsoft/vscode/issues/204207

**Closed by rzhao271** 2024-02-26 15:40 UTC
