### ISSUE TITLE
from [vscode-cpptools]: "Switch header/source" in split view opens file always in left view.

### ISSUE THREAD

**Issue by bad-ed** [Microsoft/vscode#18730] opened 2017-01-18 12:18 UTC
Redirected from here: https://github.com/Microsoft/vscode-cpptools/issues/444

Example: editor is split into two views. In the left view I have "file.h" opened, "file.cpp" is opened in right view. Issuing "C_Cpp.SwitchHeaderSource" command in "file.h" tab creates new tab "file.cpp" in left view. Seems like it should focus already opened "file.cpp" tab in right view. If there is no tab with corresponding source (or header) it should be created in the same view side by side with tab from which command has been issued.

![vscode](https://cloud.githubusercontent.com/assets/24456989/21926730/165b3774-d994-11e6-80f0-1060f3ab447a.gif)

**Comment by bpasero** [comment] 2017-01-19 08:49
C++ asks for the `revealIfVisible` option to be available as API.

**Comment by jrieken** [comment] 2017-01-19 10:23
dupe of #13639

**Closed by jrieken** 2017-01-19 10:23 UTC
Labels: api, feature-request, workbench
