### ISSUE TITLE
cmd c not working in settings view when overriding the clipboardCopyAction

### ISSUE THREAD

**Issue by hans000** [microsoft/vscode#221440] opened 2024-07-11 07:07 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.91
- OS Version: macos

Steps to Reproduce:

1. override the clipboardCopyAction

reference https://stackoverflow.com/questions/44598894/in-a-vs-code-extension-how-can-i-be-notified-when-the-user-cuts-copies-or-paste
```

function overriddenClipboardCopyAction(textEditor, edit, params) {

    //debug
    console.log("---COPY TEST---");

    //use the selected text that is being copied here
    getCurrentSelectionEvents(); //not shown for brevity

    //dispose of the overridden editor.action.clipboardCopyAction- back to default copy behavior
    clipboardCopyDisposable.dispose();

    //execute the default editor.action.clipboardCopyAction to copy
    vscode.commands.executeCommand("editor.action.clipboardCopyAction").then(function(){

        console.log("After Copy");

        //add the overridden editor.action.clipboardCopyAction back
        clipboardCopyDisposable = vscode.commands.registerTextEditorCommand('editor.action.clipboardCopyAction', overriddenClipboardCopyAction);

        context.subscriptions.push(clipboardCopyDisposable);
    }); 
}
```
2. try to copy text with cmd + c in settings view, it's not working. and others can be working(terminal, editor...)

**Comment by rzhao271** [comment] 2024-12-10 23:15
Does this issue occur for _any_ text selected in the Settings editor? If not, could you add which text you're trying to select?
Potential duplicate of https://github.com/microsoft/vscode/issues/174844

**Closed** 2024-12-18 11:27 UTC
Labels: bug, info-needed, settings-editor, confirmation-pending
