### ISSUE TITLE
wrong vertical cursor movement when text wraps around

### ISSUE THREAD

**Issue by aybabtme** [Microsoft/vscode#34500] opened 2017-09-15 22:37 UTC
It seems like cursor movement is getting confused by text that wraps around

- VSCode Version: 1.16.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1) When doing movements from a line that is visually wrap'd around.
2) Press arrow down.
3) The cursor lands on the wrap'd around part of the line, instead of the 2nd line.

This is especially annoying when doing actions with multiple cursors that are working on the same sort of text where movements and edits should lead to equivalent results. In this example, I'm trying to reach the `panic(...)` line on multiple cursors, from the same "logical" location on 5 cursors. The bottom line is wrapping around and fails to land on the same spot than the 4 first ones. If I were to start editing the top line with belief that my cursors are all doing the same thing, I would end up with some weird results.

![screenflow](https://user-images.githubusercontent.com/1189716/30505677-31055fca-9a44-11e7-8997-7be8880d6a00.gif)

**Comment by alexandrudima** [comment] 2017-09-28 09:36
multicursor navigation currently operates on wrapped (view) lines. AFAIK this matches the behaviour of other editors.

**Comment by aybabtme** [comment] 2017-10-09 14:42
Hi @alexandrudima ! I'm fairly certain this isn't the case in other editors (since muscle memories were built from being used to doing this), but I'll have to install them back to verify. In any case, it would be good if this was an option.

**Comment by alexandrudima** [comment] 2017-10-24 10:20
Duplicate of #26393

This can be implemented from an extension.

**Closed by alexandrudima** 2017-10-24 10:20 UTC
Labels: as-designed, editor, editor-multicursor, feature-request
