### ISSUE TITLE
Hot Exit Does not Open Unsaved File on Launch

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/vscode#15528] opened 2016-11-15 20:04 UTC
- VSCode Version: 1.8.0-Insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open multiple files
2.  Create new unsaved file
3. Type in mumbo jumbo
4. Close VSCode (hot exit)
5. Open VSCode

You will notice that your mumbo jumbo tab is not the tab that is it focus (it seems like there is a delay for opening hot exit'ed files?).

I can make a video if instructions are unclear.

**Comment by Jonatino** [comment] 2016-11-15 20:11
@Tyriar

**Comment by Tyriar** [comment] 2016-11-15 21:29
Thanks for the report, this is a duplicate of https://github.com/Microsoft/vscode/issues/14116. Note that it only affects untitled files right now, eventually they will be restored just like text files :smile:

**Closed by Tyriar** 2016-11-15 21:29 UTC
