### ISSUE TITLE
Objects and Functions keep getting indented when moving down

### ISSUE THREAD

**Issue by 4uxiliar** [microsoft/vscode#72849] opened 2019-04-25 09:00 UTC
Issue Type: <b>Bug</b>

I have noticed this bug in the typescript language mode.
1. Create two Functions. The upper Method should at least be to lines long. The second one should be at least three lines long which mustn't be empty. However the more non-empty lines there are the more pronounced the effect is.

![grafik](https://user-images.githubusercontent.com/24353680/56723055-84831480-6748-11e9-87cb-3f6cb9e8c49d.png)

2. Select the top one and move it down (editor.moveLinesDownAction).

![grafik](https://user-images.githubusercontent.com/24353680/56722944-500f5880-6748-11e9-8aa2-aabb0c4f39eb.png)

3. The moved function is indentation level increases by one for each line it passes.

![grafik](https://user-images.githubusercontent.com/24353680/56722964-59002a00-6748-11e9-9800-bc17552c4012.png)

![grafik](https://user-images.githubusercontent.com/24353680/56722972-5dc4de00-6748-11e9-8eb0-6dab1aa82493.png)

![grafik](https://user-images.githubusercontent.com/24353680/56723012-6e755400-6748-11e9-9eb3-a2ddd1aeb7f3.png)

![grafik](https://user-images.githubusercontent.com/24353680/56723019-7208db00-6748-11e9-9e56-fab89bce0cdd.png)

![grafik](https://user-images.githubusercontent.com/24353680/56723027-76cd8f00-6748-11e9-933a-aecef53391b6.png)

Actual Result: The indentation level of the method is way higher than it should be, it is farther right than the rest of the code.
Expected Result: It should be at the correct indentation level.

Additional Notes:
a) This also happens when you use obejcts which are longer than one line. The same is true for any combination of objects and functions as long as they are longer than one line. 
b) This effect stops when you and the indentation resets when you move below an empty line. That being said, the effect continues as long as there isn't a new line, even when already have move below the initially entered object/function.
c) The effect is also cancelled and the indentation level is reset when you move the line up (editor.moveLinesUpAction). Moving lines up in general doesn't produce the bug at all.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17134

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
shell-format|fox|4.0.5
svg|joc|0.1.4
angular-essentials|joh|0.6.0
Angular2|joh|7.1.1
vscode-peacock|joh|2.1.1
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.7.0
code-spell-checker|str|1.7.4
shellcheck|tim|0.6.0

(1 theme extensions excluded)

</details>

**Comment by andyneff** [comment] 2019-08-08 15:41
I just ran into this. It ONLY happens on windows.

I even started the exact same vscode on linux, and remoted into windows, and no bug on linux remoted into windows, but bug on windows.

It also adds "spaces" on blank lines too, basically indenting the blank line that I did not have selected, when moving

```
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Running the exact same version on linux, except: 
`OS: Linux x64 5.1.18-300.fc30.x86_64`

**Comment by andrewbranch** [comment] 2019-12-09 18:43
Here’s a GIF, might be easier to follow than the series of stills in the OP

![indent](https://user-images.githubusercontent.com/3277153/70462849-982d8200-1a70-11ea-9b45-c94531ed6dc4.gif)

**Comment by gjsjohnmurray** [comment] 2020-01-14 22:22
See also #54829

**Comment by rebornix** [comment] 2020-11-03 18:01
/duplicate of https://github.com/microsoft/vscode/issues/54829

**Closed by rebornix** 2020-11-03 18:01 UTC
Labels: bug, editor-autoindent
