### ISSUE TITLE
Terminal: find widget placeholder should mention up / down arrows for history navigation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148135] opened 2022-04-26 11:27 UTC
Testing #148060

Notice how the editor nicely advertises the up and down arrows for history navigation.
Terminal find widget should do the same since it supports history navigation

![Screenshot 2022-04-26 at 13 26 44](https://user-images.githubusercontent.com/1926584/165290086-e989f757-61b2-48c8-8465-e172bd6950a8.png)
![Screenshot 2022-04-26 at 13 26 47](https://user-images.githubusercontent.com/1926584/165290091-5e54b786-4a85-4c1c-9e5c-f2c88722b57e.png)

**Comment by meganrogge** [comment] 2022-04-28 17:37
I reopened this because it has the correct history message before you search, but then subsequently is just `Find`, but re-closed it bc the editor find has the same behavior

**Comment by rzhao271** [comment] 2022-04-28 17:53
Ironically, I now do not see the up/down arrows for the editor find widget, but I see them for the terminal find widget.

**Comment by meganrogge** [comment] 2022-04-28 18:00
@rzhao271 I think that's the intended behavior - we only show the history placeholder once before someone has searched. is that correct @isidorn ?

**Comment by rzhao271** [comment] 2022-04-28 18:17
I'm not sure if this is as designed:
1. Reload window
2. Navigate to a file such as a ts file
3. Ctrl+F in the file
4. :bug: I only see the "Find" prompt show up with "No results".

**Comment by isidorn** [comment] 2022-04-29 09:28
@rzhao271 I think that might be by design because there is no history to navigate to. You have not yet searched for anything.

@meganrogge I still see an issue here. Steps

1. Terminal, ctrl + F
2. Search for something, press enter
3. Delete content of find widget input -> Placeholder text not shown

@meganrogge should we reopen this? I think it is perfectly fine to fix this in the next milestone.

**Closed** 2022-05-25 20:38 UTC
Labels: bug, polish, terminal-find

**Comment by isidorn** [comment] 2022-05-26 08:40
@meganrogge I just tried out your fix, I see the placeholder text but only initially.
For example if I type something in the find widget and then delete it I no longer see the placeholder text
If I close the find widget and open it again I no longer see the placeholder text

The current experience is very unpredictable and I can not figure out when the placeholder text will appear.

**Comment by Tyriar** [comment] 2022-05-26 14:14
@isidorn works here?

![Recording 2022-05-26 at 07 13 10](https://user-images.githubusercontent.com/2193314/170505464-e153276d-2d76-4e17-bd7c-e25a544a304a.gif)

Note that it's only meant to show up when the input is focused to keep things clean.

**Comment by isidorn** [comment] 2022-05-26 15:10
Ok there is a weird pattern when it does not show up. Here are the steps that repro 100% for me

1. Reload window
2. Open find widget it is empty and placeholder is hown
3. Type "a"
3. Delete "a" using backspace key
5. Placeholder is not shown even though the focus is in the find widget 🐛

**Comment by Tyriar** [comment] 2022-05-26 15:16
@isidorn I see the same in the editor, want to make a new issue?

**Comment by isidorn** [comment] 2022-05-26 15:23
Of course. I just opened this one https://github.com/microsoft/vscode/issues/150459
Thanks
