### ISSUE TITLE
Native Interactive - Debugging a cell causes a second copy of the target file to open.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#127834] opened 2021-07-02 00:18 UTC
- Open a script with cells
- Debug the first cell

A second copy of the debugged file is opened on top of the IW. Closing the extra will just open it again on next step.

![image.png](https://images.zenhubusercontent.com/5bda244bb6c4f1227d4a2d8e/bb6025cc-1e08-4b2b-b229-237b7d57fe9e)

**Comment by joyceerhl** [comment] 2021-07-08 02:47
Duplicate of https://github.com/microsoft/vscode/issues/127792

**Closed by joyceerhl** 2021-07-08 02:47 UTC
