### ISSUE TITLE
In JS/TS mode, variable names starting with "var" incorrectly highlighted

### ISSUE THREAD

**Issue by martine** [Microsoft/vscode#5087] opened 2016-04-07 23:05 UTC
- VSCode Version: 
Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:30:20.458Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

- OS Version:
Ubuntu Linux

Steps to Reproduce:
1. make new dir; `code .`; create new foo.js file
2. add code:

```js
if (!varName)
```

In themes other than the default, the "var" within "varName" is incorrectly syntax highlighted.

**Comment by martine** [comment] 2016-04-07 23:05
![image](https://cloud.githubusercontent.com/assets/3847/14369510/87ea8f4e-fcda-11e5-9f3a-aa2811960a9b.png)

**Comment by Lambdac0re** [comment] 2016-04-08 08:10
:+1:

**Comment by egamma** [comment] 2016-04-08 13:13
duplicate of #4620. 

You can give it a try from our  [insiders build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build)

**Closed by egamma** 2016-04-08 13:13 UTC
