### ISSUE TITLE
Web: File picker dialog is not enabling files with .code-profile 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#176424] opened 2023-03-07 19:07 UTC
Steps to Reproduce:

1. Open vscode.dev
2. Run Import Profile... command
3. Select Import from profile file...

🐛 I cannot select files with .code-profile extension, this works in desktop

<img width="828" alt="image" src="https://user-images.githubusercontent.com/10746682/223525170-f4b43c75-b2ae-403a-b719-a0f7d49d8972.png">

**Comment by bpasero** [comment] 2023-03-08 07:23
Duplicate of https://github.com/microsoft/vscode/issues/149419
Dupicate of https://github.com/microsoft/vscode/issues/148182

**Comment by alexr00** [comment] 2023-03-08 11:07
At the time I added the file type support `-` and `_` were not allowed in file extensions 🤷‍♀️ https://github.com/microsoft/vscode/issues/130035#issuecomment-895091067

**Comment by alexr00** [comment] 2023-03-08 11:21
Tested, and `-` and `_` are still not allowed. @sandy081 can you select to show all files in the dialog?

![image](https://user-images.githubusercontent.com/38270282/223700448-6907595a-741d-49c3-b006-d0c6a785032a.png)

**Closed** 2023-12-13 14:59 UTC
Labels: web, native-file-dialog
