### ISSUE TITLE
[Bug] JSDoc comment creation is gone

### ISSUE THREAD

**Issue by kungfooman** [microsoft/vscode#209214] opened 2024-03-31 10:12 UTC
Reproduction steps:

Simply add a function and type `/**[Enter]`

Test function:

```js
/*
export function defineProtoFunc(cls, name, func) {
  if (!cls.prototype[name]) {
      Object.defineProperty(cls.prototype, name, {
          value: func,
          configurable: true,
          enumerable: false,
          writable: true
      });
  }
}
```

Actual behaviour:

Nothing happens.

Expected Behavior:

As it used to be before the regression...

![vscode_jsdoc_setup](https://github.com/microsoft/monaco-editor/assets/5236548/9b98ee7a-be1d-485b-b8c7-7401a6912b5e)

**Comment by mjbvz** [comment] 2024-04-01 15:29
Works fine for me. Mostly likely you disabled snippet completions (`editor.snippetSuggestions`)

Closing as a question because it's likely not a bug without evidence showing otherwise

**Closed by mjbvz** 2024-04-01 15:29 UTC

**Comment by kungfooman** [comment] 2024-04-01 15:55
My snippet suggestions option is and wasn't disabled.

It also doesn't work in Playground: https://www.typescriptlang.org/play?#code/PQKgUApgHgDg9gJwC4AIBmBXAdgYyQSzixQBMI18sIAFBOJOAMWxwAocAbAZwBoUsAhgFsIfTLgCUKAN5gUKfGhSsAhJy4A6GHQZIAnjAgBtQSIC6U2fOsoA8gCMAVhDwayFKrTiHke9ty0degNRfmFQqxsogDcBDgwIAC50Fh45KJscIgoAcwwEAXsOJJQkBAS0jJsILAwRAqKStDiuUXSqlAB3BHwkQuLksoT26wBfCQBudNGwUaA

Something is wrong and I would like an actual solution...

**Comment by mjbvz** [comment] 2024-04-01 16:10
The playground isn't the same as VS Code

Please start by filing the issue template. Also explain what you've already tried

**Comment by kungfooman** [comment] 2024-04-03 10:34
I know development is hard and the left hand doesn't know what the right one is doing here:

![image](https://github.com/microsoft/vscode/assets/5236548/e459df46-171f-4de6-87b2-ea0987a09541)

Anyway, simply go to https://vscode.dev/ and observe the bug...

**Comment by kungfooman** [comment] 2024-04-04 08:47
Thank you @mjbvz for the open-a-workspace-first workaround - I have a feeling this used to work in Monaco/Playground, but how would I even open a workspace in Monaco/Playground as workaround?

I updated my local VSCode and at least it works locally again - probably should have tried that earlier.

Is there any chance we get this feature in Monaco/Playground by default? At least in Playground language services are loaded and then JSDoc comment completion should work too, right?

Sorry for being pushy about this, I just often have to refactor a swath of code and this feature is a lovely time/nerve saver, I just want it to work reliably wherever possible.
