### ISSUE TITLE
Can's cancel the breakpoint

### ISSUE THREAD

**Issue by q86002618** [Microsoft/vscode#38107] opened 2017-11-11 08:26 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|hbe|0.17.0
ejs-language-support|Qas|0.0.1
java|red|0.14.0

---

Steps to Reproduce:

1.sometimes i can cancel the breakpoint when i click the breakpoint again,but by restarting the VS Code,it can be fixed 
2.but sometimes i quickly click the breakpoint when VS code just restarts,it can't also be canceled

Reproduces without extensions: No

**Comment by weinand** [comment] 2017-11-11 09:51
duplicate of #37880

**Closed by weinand** 2017-11-11 09:51 UTC
Labels: debug, new release
