### ISSUE TITLE
[WelcomeUX] Focus issues while navigating using keyboard

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#18927] opened 2017-01-20 19:17 UTC
Testing #18091 on OS X El Capitan

The "Start", "Recent", "Help" get focus, but the quick links don't.
Quick links do have a hover treatment.
The same can be used for keyboard focus as well.

The check box, gets focus while navigating using keyboard, but there is not much of a visual cue.

**Comment by bgashler1** [comment] 2017-01-20 23:01
Fixed #e9fb82ac4ce6a2e687f80ced1272c6b365d7649c

**Comment by ramya-rao-a** [comment] 2017-01-25 19:45
Go back and forth the quick links using keyboard and you end up with one of the links getting a complete rectangle around it, and another with half, another with just the right and left lines.

![image](https://cloud.githubusercontent.com/assets/16890566/22306295/8ae3e042-e2f3-11e6-835b-d3005ce2b9db.png)

Keyboard focus on links on the left side can use some padding on the left and right

![image](https://cloud.githubusercontent.com/assets/16890566/22306334/b446cda0-e2f3-11e6-96bf-9e2cb4de4264.png)

Check box still has bad focus

**Comment by chrmarti** [comment] 2017-01-26 18:44
Mac looks fine. Reproduces on Windows.

**Comment by chrmarti** [comment] 2018-10-02 10:21
Seems to be fixed in the latest. Probably an Electron issue.

**Closed by chrmarti** 2018-10-02 10:21 UTC
Labels: bug, workbench-welcome
