### ISSUE TITLE
TS Server fatal error:  Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by RyanaQr** [microsoft/vscode#134636] opened 2021-10-08 08:20 UTC
**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2064:20)
    at isNodeModulesOrScopedPackageDirectory (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19715:65)
    at guessDirectorySymlink (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19703:17)
    at processResolution (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19692:22)
    at c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19683:162
    at Map.forEach (<anonymous>)
    at Object.setSymlinksFromResolutions (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:19683:123)
    at ConfiguredProject.Project.getSymlinkCache (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161084:35)
    at Object.getSymlinkCache (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114006:29)
    at Object.host.compilerHost.realpath (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114071:36)
    at realPath (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41680:42)
    at Object.resolveTypeReferenceDirective (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:41044:74)
    at c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162443:112
    at Object.map (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:455:29)
    at Function.AutoImportProviderProject.getRootFileNames (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162443:42)
    at Function.AutoImportProviderProject.create (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162475:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162277:77)
    at ConfiguredProject.Project.updateGraph (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161700:26)
    at ConfiguredProject.updateGraph (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162644:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164368:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165451:44)
    at c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165791:97
    at Object.flatMap (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165791:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166949:46)
    at c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168871:28)
    at IOSession.Session.executeCommand (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168880:33)
    at IOSession.Session.onMessage (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168906:35)
    at Interface.<anonymous> (c:\Users\ryq\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171511:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mjbvz** [comment] 2021-10-08 19:25
Duplicate of https://github.com/microsoft/TypeScript/issues/44953

**Closed by mjbvz** 2021-10-08 19:25 UTC
