### ISSUE TITLE
preLaunchTask does not fire on restart when adapter supportsRestartRequest

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#28979] opened 2017-06-19 04:08 UTC
Steps to Reproduce:

1. Create a build task called "Build" in tasks.json
2. Create a launch configuration in launch.json
3. set the "preLaunchTask": "Build"
4. Launch with F5 and the build task will fire.
5. Press Ctrl+Shift+F5 to restart the debugging session. the build does not fire first.
Maybe we need a "preRestartTask"

**Comment by isidorn** [comment] 2017-06-19 08:57
Works for me, restart will always trigger `preLaunchTask`.
If you would like us to investigate further please provide a github repository for which you can easily reporduce this. Though I believe this is not a vscode issue since I see other users asking the opposite https://github.com/Microsoft/vscode/issues/17439

![restart](https://user-images.githubusercontent.com/1926584/27277223-e9f3f3b8-54dd-11e7-83a9-e0f2c96178b6.gif)

**Comment by justin-romano** [comment] 2017-06-19 22:54
Sorry i need to further qualify this issue. This is using the chrome debugger.
```js
    "configurations": [{
            "type": "chrome",
            "request": "launch",
            "preLaunchTask": "Build",
            "name": "Launch Chrome against localhost",
            "url": "https://j2017.censored.com/censored/web/index.html",
            "webRoot": "${workspaceRoot}"
        }
```

**Comment by isidorn** [comment] 2017-06-20 07:42
That is because the chrome debuggers is using a [custom restart feature](https://github.com/Microsoft/vscode/blob/isidorn/explorerModel/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L903).

When a debug adapter is using this capability it is fully in charge what the restart exeprience should be like. So vscode does not do anything (including restarting the task). We currently do not support a half baked approach, where chrome would do some things in the restart and vscode the rest. Leaving this open as a feature request

Ping @roblourens to also get his opinion

**Comment by roblourens** [comment] 2017-07-04 18:32
I think it should act the same as when running without `supportsRestartRequest`. If your task just does a build, then it would be really useful to have it run the build then refresh the browser. If it's a background task, then it should just refresh the browser.

**Comment by roblourens** [comment] 2017-07-04 18:32
I thought maybe there was another issue for this where we discussed it, but I can't find it. I don't think it would be possible for the debug extension to implement this.

**Comment by isidorn** [comment] 2017-07-17 12:40
@roblourens yes I agree what would be the ideal solution, however as mentioned above due to the current implentation we are not doing that yet (running a prelaucnh task and starting a new debug session are coupled).
Leaving this in the backlog until more users complain

**Comment by weinand** [comment] 2018-05-31 15:21
@isidorn When running a `postDebugTask` in the "supportsRestartRequest == false" case, you use code that checks for `postDebugTask` being defined and you notify about errors:
```ts
if (session.configuration.postDebugTask) {
	this.runTask(session.getId(), session.raw.root, session.configuration.postDebugTask).done(undefined, err =>
		this.notificationService.error(err)
	);
}
```

For `preLaunchTask` there is even more error handling:
```
return this.runTask(sessionId, workspace, resolvedConfig.preLaunchTask).then((taskSummary: ITaskSummary) => {
	const errorCount = resolvedConfig.preLaunchTask ? this.markerService.getStatistics().errors : 0;
	const successExitCode = taskSummary && taskSummary.exitCode === 0;
	const failureExitCode = taskSummary && taskSummary.exitCode !== undefined && taskSummary.exitCode !== 0;
	if (successExitCode || (errorCount === 0 && !failureExitCode)) {
		return this.doCreateSession(workspace, { resolved: resolvedConfig, unresolved: unresolvedConfig }, sessionId);
	}

	const message = errorCount > 1 ? nls.localize('preLaunchTaskErrors', "Build errors have been detected during preLaunchTask '{0}'.", resolvedConfig.preLaunchTask) :
		errorCount === 1 ? nls.localize('preLaunchTaskError', "Build error has been detected during preLaunchTask '{0}'.", resolvedConfig.preLaunchTask) :
			nls.localize('preLaunchTaskExitCode', "The preLaunchTask '{0}' terminated with exit code {1}.", resolvedConfig.preLaunchTask, taskSummary.exitCode);

	const showErrorsAction = new Action('debug.showErrors', nls.localize('showErrors', "Show Errors"), undefined, true, () => {
		return this.panelService.openPanel(Constants.MARKERS_PANEL_ID).then(() => undefined);
	});

	return this.showError(message, [debugAnywayAction, showErrorsAction]);
}, (err: TaskError) => {
	return this.showError(err.message, [debugAnywayAction, this.taskService.configureAction()]);
});
```

In the "supportsRestartRequest == true" case there is no check for `postDebugTask` and `preLaunchTask` being undefined and there is surprising little error notification code:
```
return this.runTask(session.getId(), session.raw.root, session.configuration.postDebugTask)
	.then(() => this.runTask(session.getId(), session.raw.root, session.configuration.preLaunchTask))
	.then(() => <TPromise>session.raw.custom('restart', null));
```

Why this discrepancy?

Since the "supportsRestartRequest" is really an implementation detail of a debug adapter, an end user should not be able to observe any discernible difference between DAs supporting "supportsRestartRequest" and those that do not.

I suggest that you refactor the pre- and post-launch code in two separate methods to ensure that the same code is run in both cases.

**Comment by chrmarti** [comment] 2018-06-28 12:49
I still see the `preLaunchTask` only run once with the Chrome debug adapter. What is the expected behavior?

**Comment by isidorn** [comment] 2018-06-28 12:54
That every time you restart the preLauncTask fires, if that is not the case please reopen and assign to July

**Comment by chrmarti** [comment] 2018-06-28 12:58
It works with the Node adapter, but not with the Chrome adapter. My launches:
```json
        {
            "type": "node",
            "request": "launch",
            "name": "runawhile.js",
            "program": "${workspaceFolder}/runawhile.js",
            "preLaunchTask": "npm: hello1",
            "postDebugTask": "npm: hello2",
        },
        {
            "type": "chrome",
            "request": "launch",
            "name": "Chrome server.js",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/wwwroot",
            "preLaunchTask": "npm: hello1",
            "postDebugTask": "npm: hello2",
        },
```

**Comment by isidorn** [comment] 2018-08-02 19:26
@chrmarti good catch

**Closed** 2018-08-02 19:27 UTC
Labels: bug, debt, debug
