### ISSUE TITLE
Snippets as separate files

### ISSUE THREAD

**Issue by Amparose** [Microsoft/vscode#39989] opened 2017-12-10 15:58 UTC
__Requesting better snippet storage ystem:__

The current implementation of snippets' data is narrow and awkward. By clustering all snippets by language into JSON files it makes it difficult to share, version, and create snippets per projects. SublimeText's implementation of file-per-snippet in a user-defined folder structure is much more flexible.

Perhaps a middle ground would be allowing multiple namespaced JSON files to be concatenated and loaded. E.g. `less.json`, `less_SomeName.json`, `less_ProjectName.json`, etc

Version of VS Code 1.18.1

**Comment by jrieken** [comment] 2017-12-11 08:29
closing this as dupe of #22661 (snippets knowing their scope/language) and #13182 (global snippets)

**Closed by jrieken** 2017-12-11 08:29 UTC
Labels: snippets
