### ISSUE TITLE
Error End of Central Directory Record Signature Not Found when trying to install extensions

### ISSUE THREAD

**Issue by jackfalveyiv** [Microsoft/vscode#44830] opened 2018-03-01 13:53 UTC
- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Complete uninstall/reinstall of VS Code on Windows 10 box
2. Attempted to download through the browser in VS Code and directly from the Extensions library on the website.

Does this issue occur when all extensions are disabled?: Yes

As an additional detail, this is a work computer, however my colleague is able to pull the extension in on his machine without an issue.

**Comment by jackfalveyiv** [comment] 2018-03-01 17:46
Bump

**Comment by sandy081** [comment] 2018-03-02 13:57
Duplicate of #42229

**Closed** 2018-03-02 13:57 UTC
Labels: *duplicate, extensions
