### ISSUE TITLE
paste is needed when r-clicked on a file

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#30327] opened 2017-07-10 07:41 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-58-generic
- Extensions: none
---

Steps to Reproduce:

1. r-click a file
2. no paste option shown

expected:

1. r-click a file
2. show paste options
3. select paste option
4. paste a file on the same directory.

**Comment by alexandrudima** [comment] 2017-08-10 07:55
I believe this is about the explorer ("paste a file on the same directory")

**Comment by mjbvz** [comment] 2017-11-03 21:42
Duplicate of #24931

**Closed by mjbvz** 2017-11-03 21:42 UTC
Labels: duplicate, explorer-files, feature-request, workbench
