### ISSUE TITLE
Find occurrence show ? in find widget in large file

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31554] opened 2017-07-27 11:21 UTC
Testing #30243

File has around 370K lines

![image](https://user-images.githubusercontent.com/10746682/28668061-cc0b9e42-72eb-11e7-8ed9-2e8dbf94abc0.png)

**Comment by alexandrudima** [comment] 2017-08-10 09:39
Duplicate of #496.

Since the find widget only finds the first 1000 occurrences, it doesn't count beyond those. In this case, you were below the first 1000 occurrences, so the UI label indicates that you are somewhere outside the first 1000 occurrences range. If you were to go within the first 1000 occurrences, it would show next to which one you are.

**Closed by alexandrudima** 2017-08-10 09:39 UTC
