### ISSUE TITLE
Tab's horizontal scroll bar is too thin to scroll

### ISSUE THREAD

**Issue by JoeyRxy** [Microsoft/vscode#70731] opened 2019-03-19 06:07 UTC
Issue Type: <b>Feature Request</b>

I'm not talking about the editor's horizontal scroll bar.there is a very thin scroll bar between the tabs and editor,that's what i'm talking about.
When you open too many tabs,some tabs are invisible so you need scrolling horizontally.
There's a scrollbar to scroll the tabs,but it's too thin.
Of course,this wasn't a big bug or what,and I can use "Ctrl+Tab" to switch tabs.
maybe this bar should be bigger or even disappear considering it's not helpful.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment] 2019-03-19 06:20
Duplicate of #32192

**Closed** 2019-03-19 06:33 UTC
Labels: new release

**Comment by octref** [comment] 2019-07-30 18:44
Oops, tagged wrong issue.
