### ISSUE TITLE
F5 brings up empty drop down when using onDebugInitialConfigurations activation event

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39725] opened 2017-12-05 19:56 UTC
Testing #39535 on Windows

I used the Go extension and added the 2 activation events as instructed in #39535

In a workspace without a `launch.json` file, press F5

**Expected**: The drop down appears with available types
**Actual**: The drop down is empty with just the "More" option. Click anywhere else on the editor, the drop down gets refreshed with the available types

**Note**: Clicking on the gear icon brings up the drop down with the available types without any issue. So this cannot be about the Go extension taking time to get activated.

**Comment by isidorn** [comment] 2017-12-05 20:23
Dupe of https://github.com/Microsoft/vscode/issues/39661

**Closed by isidorn** 2017-12-05 20:23 UTC
Labels: debug
