### ISSUE TITLE
[js][0.10.6] Syntax highlighting after multiline strings

### ISSUE THREAD

**Issue by beyondcompute** [Microsoft/vscode#2664] opened 2016-02-03 10:32 UTC
Hello! Here's the highlighting of simple multiline string in ES5 is broken:
<img width="450" alt="" src="https://cloud.githubusercontent.com/assets/248055/12779620/8f6ac572-ca71-11e5-8e82-7b8d1477f165.png">

Here's more interesting case. All syntax highlighting in entire file below the string is broken:
<img width="452" alt="" src="https://cloud.githubusercontent.com/assets/248055/12779699/186bfdaa-ca72-11e5-91d7-a2aedd9ef000.png">

**Comment by aeschli** [comment] 2016-02-03 16:33
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/5

**Closed by aeschli** 2016-02-03 16:33 UTC
