### ISSUE TITLE
How to listen input onChange event in showQuickPick?

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/vscode#20499] opened 2017-02-12 05:39 UTC
- VSCode Version: 1.9.1
- OS Version: 10.11.6

Is there a way to listen input onChange event in `showQuickPick`?
I want to emit command when user input changed.

Has `onDidChangeInput` not implemented yet?

Thanks

**Comment by jrieken** [comment] 2017-02-15 08:54
That's not possible yet

**Comment by jrieken** [comment] 2017-04-11 08:12
closing as dupe of #15659

**Closed by jrieken** 2017-04-11 08:12 UTC
Labels: api, feature-request, quick-pick
