### ISSUE TITLE
cmd命令模式下，cls无法真正清屏

### ISSUE THREAD

**Issue by yunxu1019** [Microsoft/vscode#70142] opened 2019-03-10 03:22 UTC
- VSCode Version: 1.32.1(system up) 几乎每个版本都存在
- OS Version: windows 10 64bit

Steps to Reproduce:

1. 在命令行模式下输入一些命令，做为要清理的干扰信息
![image](https://user-images.githubusercontent.com/15274374/54080225-32b43580-4326-11e9-84b4-bb45a656e7cf.png)

2. 输入cls
![image](https://user-images.githubusercontent.com/15274374/54080250-89217400-4326-11e9-9ce6-c19719a853f7.png)

3. 回车之后向上滚动屏幕，之前的干扰信息还在

![image](https://user-images.githubusercontent.com/15274374/54080257-ab1af680-4326-11e9-9347-72ae4a2a2b1c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment] 2019-03-10 03:44
为方便交流，下次请用英文描述。尤其是标题。
![image](https://user-images.githubusercontent.com/20079289/54080358-d9172100-42bb-11e9-8261-c19fb4988888.png)
***
**A brief in English. I don't have this issue.**
>"cls" cannot really clear the screen in terminal.
The previous lines were still there if rolling mouse.

**Note the author used cmd as terminal in VS Code.**

**Comment by byyxx128** [comment] 2019-03-10 04:17
为方便交流，下次请用英文描述。尤其是标题。
**A brief in English. I don't have this issue.**
>`cls` cannot really clear the screen in terminal.
The previous lines were still there if you roll your mouse.

**Note the author used cmd as terminal in VS Code.**
I guess it should be assigned to you. 🤔@Tyriar

**Comment by yume-chan** [comment] 2019-03-11 06:48
duplicate of xtermjs/xterm.js#106

**Comment by Tyriar** [comment] 2019-03-11 14:42
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Closed by Tyriar** 2019-03-11 14:42 UTC
Labels: new release
