### ISSUE TITLE
VSCode Marketplace site does not support internal links in Readme markdown

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#11863] opened 2016-09-12 07:44 UTC
(This isn't a problem with VSCode itself, however I couldn't find a better place to file this)

When VSCode Marketplace site renders readme for a published extension, it ignores internal (aka intra-document) links.  For example, consider the document below; the table of contents links to sections work correctly in the internal VSCode viewer, however on the Marketplace site they all just open a new copy of the page.  

```markdown
Table of contents:
[Section 1](#section-1)
[Section 2](#section-2)
...

# Section 1
...

# Section 2
...
```

**Comment by joaomoreno** [comment] 2016-09-13 06:04
Duplicate of Microsoft/vscode-vsce#118

**Closed by joaomoreno** 2016-09-13 06:04 UTC
Labels: marketplace
