### ISSUE TITLE
INSERT key not functioning in Windows 10 installation of Visual Studio Code

### ISSUE THREAD

**Issue by keithwanta** [microsoft/vscode#116590] opened 2021-02-12 23:24 UTC
- VS Code Version: 1.53.0
- OS Version: Windows 10

Steps to Reproduce:

1A.) press INSERT key to 'ON' 
1B.) Go into Notepad > place cursor before the letter {old letter} key > press the {new letter} key > confirm the letter {old letter} was replaced with the letter {new letter}
1C.) Go into Visual Studio Code > place cursor before the letter {old letter} key > press the {new letter} key > confirm the letter {old letter} WAS NOT replaced with the letter {new letter} <-- after fix, {new letter} should replace the {old letter}
2A.) press INSERT key to 'OFF' 
2B.) Go into Notepad > place cursor before the letter {old letter} key > press the {new letter} key > confirm the letter {old letter} WAS NOT replaced with the letter {new letter}
2C.) Go into Visual Studio Code > place cursor before the letter {old letter} key > press the {new letter} key > confirm the letter {old letter} WAS replaced with the letter {new letter} <-- after fix, {new letter} should NOT replace the {old letter}

Does this issue occur when all extensions are disabled?: Yes/No
Yes, I turned on Extension Bisect and can reproduce the issue.

**Comment by IllusionMH** [comment] 2021-02-12 23:44
> 2C.) Go into Visual Studio Code > place cursor before the letter {old letter} key > press the {new letter} key > confirm the letter {old letter} WAS replaced with the letter {new letter} <-- after fix, {new letter} should NOT replace the {old letter}

Do you really observe this step in current version? Because AFAIK VS Code doesn't support <kbd>Insert</kbd> (Override) mode at all. See #1012

Looks more like duplicate of #1012 to support it in first place or issue with some of extensions.

**Comment by alexdima** [comment] 2021-02-15 08:49
Let's track in #1012

**Closed by alexdima** 2021-02-15 08:49 UTC
