### ISSUE TITLE
"View: Toggle Word Wrap" isn't working

### ISSUE THREAD

**Issue by dewdad** [Microsoft/vscode#50221] opened 2018-05-21 13:18 UTC
Issue Type: <b>Bug</b>

Load a large text file and try to toggle word wrap

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (4.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|8.3.2
vscode-npm-script|eg2|0.3.4
code-runner|for|0.9.3
jsonnet|hep|0.1.0
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
Kotlin|mat|1.6.0

</details>

**Comment by alexandrudima** [comment] 2018-05-22 07:42
Duplicate of #44206

Starting with the next stable release, a message will be provided when a large file is opened which will allow to forcefully enable that word wrapping works even for large files:

![image](https://user-images.githubusercontent.com/5047891/40348628-dc019228-5dac-11e8-8063-70ef62c95b6e.png)

**Closed by alexandrudima** 2018-05-22 07:42 UTC
Labels: editor, editor-contrib
