### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 133922249** [Microsoft/vscode#32008] opened 2017-08-04 00:34 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
vscode-babel-coloring|dza|0.0.4
auto-rename-tag|for|0.0.14
code-sync|gol|2.3.1
code-beautifier|mic|1.7.2
material-icon-theme|PKi|2.0.11
code-settings-sync|Sha|2.8.2
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1.Open the node service use the powerShell of vscode, 
2.and the node service still exists and cannot close after the vscode is closed

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment] 2017-08-04 15:57
@133922249 pls provide more detailed steps to reproduce. Do you refer to the integrated terminal? Do you execute commands there? Any additional steps you take other than launching and switching to the integrated terminal?

**Comment by 133922249** [comment] 2017-08-07 01:35
@kieferrm   I'm sorry to reply you so late. 
The following are detailed steps.
1. Open vscode.
2. switch to the integrated terminal, it use powerShell.
3. Enter 'npm start' to start the node service,
4. If I close vscode now, the node service still exists.
   Repeat the 1-3 steps, and it tell me the port was occupied.
   I can only solve it by restarting my computer.

**Comment by kieferrm** [comment] 2017-08-07 21:57
@133922249 How does `npm start` bring you your node application? Do you have a custom script or just a `main` property in your `package.json` file?

**Comment by Tyriar** [comment] 2017-08-09 02:03
Duplicate of https://github.com/Microsoft/vscode/issues/26807.

**Closed by Tyriar** 2017-08-09 02:03 UTC
Labels: integrated-terminal, needs more info
