### ISSUE TITLE
Move a js file doesn't update relative path in the require declarations inside the file

### ISSUE THREAD

**Issue by Morikko** [Microsoft/vscode#51606] opened 2018-06-11 12:17 UTC
- VSCode Version: 1.24
- OS Version: Mac 10.13.4

Steps to Reproduce:

1. Folder structure
folder1/
  a.js (require('./b')
  b.js (require('./a')
folder2/

2. Move b.js to another folder
folder1/
  a.js (require('../folder2/b')
folder2/
  b.js (require('./a') // WRONG

--> Other files that require the moved file are well updated
--> Inner relative requirement are not well updated

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-06-12 02:36
Duplicate of https://github.com/Microsoft/TypeScript/issues/24345

Should be fixed in vs code 1.25 and if you manually upgrade to typescript@next

**Closed by mjbvz** 2018-06-12 02:36 UTC
Labels: bug, javascript, upstream
