### ISSUE TITLE
C++ header text blocked bug

### ISSUE THREAD

**Issue by MoeLang** [microsoft/vscode#76877] opened 2019-07-08 13:08 UTC
- VSCode Version: 
1.36
1.37.0-insider
- OS Version: 
Windows 10 1903 18362.207
Ubuntu 18.04.2 LTS

Steps to Reproduce:
1. create newfile.h
2. paste text:
`public:/*******************Blocked************************/`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2019-07-09 08:00
Duplicate of #76774
We rolled back the C++ grammar version to match 1.35 so this will be fixed in 1.36.1. It is also already fixed in Insiders.

**Closed by alexr00** 2019-07-09 08:00 UTC
