### ISSUE TITLE
Feature-Request: Explorer navigation

### ISSUE THREAD

**Issue by Legends** [Microsoft/vscode#47082] opened 2018-04-02 12:53 UTC
In VS I can focus an entry in the file explorer, press a/some character(s) on my keyboard and explorer will focus the first file whose filename starts with the characters pressed.

But this does not work in VsCode.

**Comment by Legends** [comment] 2018-04-02 12:56
![image](https://user-images.githubusercontent.com/966368/38196955-099dcc36-3686-11e8-9f89-0129e6bdb646.png)

**Comment by Legends** [comment] 2018-04-02 12:57
Which release will fix this?

**Comment by bpasero** [comment] 2018-04-03 04:26
/duplicate of https://github.com/Microsoft/vscode/issues/10026

**Closed** 2018-04-03 04:26 UTC
Labels: *duplicate, file-explorer
