### ISSUE TITLE
Regression in Insiders: Markdown for a step doesn't show up until switching steps and back and/or image links are broken

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#144129] opened 2022-02-28 21:54 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
1. git clone https://github.com/Azure/bicep.git
2. git checkout sw/keep/vscode/bug-walkthrough-md
3. cd src/vscode-bicep
4. npm i
5. cd ..
7. code .
8. F5 ("VSCode Extesion")
9. Help -> Getting Started 
10. Pick "Getting Started With Bicep"
EXPECTED: You should see "Open a Bicep file" on the left, and "First step" markdown on the right (or underneath)

## Stable (as expected):
Version: 1.64.2 Commit: f80445acd5a3dadef24aa209168452a3d97cc326:21.3.0
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/6913354/156063058-c7949de4-1212-4e46-9eb8-b92b6e0de007.png">

## Insiders 

ACTUAL: Either:
  a) The markdown is not displayed at all, or
  b) The image link inside it is broken

<img width="832" alt="image" src="https://user-images.githubusercontent.com/6913354/156064464-7280c448-4c74-4189-b789-c5eb4427b059.png">

Version: 1.65.0-insider
Commit: b7730c807c1e0fdacdcc91a854bb963715b2a89b
Datum: 2022-02-28T14:38:07.627Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Darwin x64 21.3.0

**Comment by JacksonKearl** [comment] 2022-02-28 23:08
Thanks for the report, this is a duplicate of #143985 and should be fixed in the next release

**Closed by JacksonKearl** 2022-02-28 23:08 UTC
