### ISSUE TITLE
[html] exclude single quote from autoClosingPairs for element content

### ISSUE THREAD

**Issue by documentsforomar** [Microsoft/vscode#18541] opened 2017-01-14 05:50 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Create an html file
2. Create a paragraph tag and use single quotes for typing a sentence such as we're.

The output displays the following
<p>We're'

Also when tabbing out of quotes such as <link rel="stylesheet" href="/style.css">
The output displays the following
<link rel="<stylesheet></stylesheet>" href="/<style class="css"></style>"

Steps to Reproduce:

1. Type <link rel="
2. The program will auto insert another set of quotes
3. It will change to this <link rel=""
4. Type <link rel="stylesheet"
5. The cursor is between t and "
6. Press tab
7. The output inserts open and close tags for <stylesheet></stylesheet>

**Comment by aeschli** [comment] 2017-01-30 15:49
I agree we should refine this. #19515 has a good idea.

**Comment by aeschli** [comment] 2017-11-23 15:47
Since a while, single and double quotes are not autoclosed if typed directly after a letter. That fixes the `we're` case.
Also, the `<link rel="stylesheet"` is no longer reproducible, there must have been some changes.
Closing

**Closed by aeschli** 2017-11-23 15:47 UTC
Labels: feature-request, html
