### ISSUE TITLE
Sometimes the lazy value placeholder shows up

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#143752] opened 2022-02-23 16:18 UTC
Testing #143572

Sometimes the lazy value placeholder shows up and I cannot get rid of it:

![CleanShot 2022-02-23 at 17 15 09](https://user-images.githubusercontent.com/1898161/155360270-689439cd-6d4b-499d-a355-139caef117f7.gif)

Even stopping and restarting the debug session doesn't help. I have to restart VS Code.

**Comment by connor4312** [comment] 2022-02-23 18:17
Yes, easy repro in js-debug:

1. Have a getter with a setter. Double click to set the variable and just click out
2. Enter anything in the repl (to trigger a variable refresh)
3. The variable now includes its placeholder and `(...)`. It should remain expanded.

**Comment by roblourens** [comment] 2022-02-24 00:14
Dupe of https://github.com/microsoft/vscode/issues/143751. The DOM gets messed up permanently

**Closed by roblourens** 2022-02-24 00:14 UTC
Labels: debug
