### ISSUE TITLE
Can't Scrolling down on .ipynb file When cursor is in output cell

### ISSUE THREAD

**Issue by capslock-inc** [microsoft/vscode#174545] opened 2023-02-16 09:58 UTC
Type: <b>Bug</b>

create ipynb file.
run a cell which outputs of text (at least 4 lines ).
now try to scroll down to end of the page while keeping cursor on output cell.

Love you guys for this amazing product.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.50GB free)|
|Process Argv|--crash-reporter-id 6da24a21-c0cd-41c8-b3e7-ed9a77b716df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
TabOut|alb|0.2.2
ng-template|Ang|15.1.0
vscode-opennewinstance|chr|0.0.12
vscode-database-client2|cwe|6.2.1
dart-code|Dar|3.58.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-solution-explorer|fer|0.7.5
remotehub|Git|0.50.0
vscode-pull-request-github|Git|0.58.1
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.224
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.30
jupyter|ms-|2023.1.2010391206
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.275.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.3
vscode-remote-extensionpack|ms-|0.23.0
remote-repositories|ms-|0.28.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.24.0
material-product-icons|PKi|1.4.1
sqlite-viewer|qwt|0.1.5
vscode-thunder-client|ran|2.4.1
errorlens|use|3.7.0
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982
showlangstatbar:30664136

```

</details>

**Comment by rebornix** [comment] 2023-02-16 18:28
/duplicate of https://github.com/microsoft/vscode/issues/174375

**Closed by rebornix** 2023-02-16 18:28 UTC
