### ISSUE TITLE
Terminal does disappear when you cancel opening new project on file saving

### ISSUE THREAD

**Issue by jpastuszuk** [Microsoft/vscode#37688] opened 2017-11-05 21:53 UTC
- VSCode Version: 1.17.2 (1.17.2)
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Create/ Open project in Visual studio Code 
2. Create new File without saving it (Untitled-1)
3. Within open project, try to open another project ( File>Open...), choose corresponding folder
4. On "Do you want to save the changes you made ?" popup, cancel opening project (Cancel)

Your terminal box is now gone (despite running/not running anything in it before) - you have to add new terminal manually
As far as I know, it does reproduce on windows

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-11-06 14:45
I think what's happening here is that the workbench is getting into a fresh slate because the old state is being associated with the older folder. I guess this might be correct behavior, hadn't considered it before. @bpasero

**Comment by bpasero** [comment] 2017-11-07 05:47
@Tyriar I am not sure I understand, could it be the terminal is disposing in the onBeforeShutdown event phase and not onWillShutdown? The former is for veto support and the latter is when it really happens.

**Comment by Tyriar** [comment] 2017-11-07 22:19
@bpasero oh sorry, I misread the issue.

This is a duplicate of https://github.com/Microsoft/vscode/issues/37481

**Closed by Tyriar** 2017-11-07 22:19 UTC
Labels: hot-exit, under-discussion
