### ISSUE TITLE
Previous search results not cleared

### ISSUE THREAD

**Issue by Dodo17sky** [microsoft/vscode#232474] opened 2024-10-29 10:37 UTC
Type: <b>Bug</b>

Search results are not cleard.
Step 1: search for "foo"
 - Found in file 1
 - Found in file 2

Step 2: search for "bar"
 - Found in file 1 (wrong, no "bar" here)
 - Found in file 2 (wrong, no "bar" here)
 - no other files shown

This issue is sporadic and the only solution found is to restart the workspace

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
githistory|don|0.6.20
remotehub|Git|0.64.0
jenkins-pipeline-linter-connector|jan|1.2.0
code-groovy|mar|0.1.2
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
azure-repos|ms-|0.40.0
cpptools|ms-|1.22.10
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
trailing-spaces|sha|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by andreamah** [comment] 2024-10-29 16:24
Does this happen on the latest insiders build? This might be a duplicate of https://github.com/microsoft/vscode/issues/231399

**Comment by eleanorjboyd** [comment] 2024-12-10 22:11
closing as stale- please comment with the response to the above question if you are still seeing this and I can reopen. Thanks!

**Closed by eleanorjboyd** 2024-12-10 22:11 UTC
Labels: info-needed
