### ISSUE TITLE
File icon moves when switching between tabs

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#51939] opened 2018-06-14 23:03 UTC
Issue Type: <b>Bug</b>

![move](https://user-images.githubusercontent.com/4033249/41442505-65e15afe-6fec-11e8-85e1-abb11a62ede8.gif)

VS Code version: Code - Insiders 1.25.0-insider (11b0f3a40be055e02b721abbb93cb0012818f99e, 2018-06-14T05:11:13.121Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_6260216|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
gitlens|eam|8.3.5
tslint|eg2|1.0.32
vsc-material-theme|Equ|2.1.0
prettier-vscode|esb|1.5.0
theme-monokai-pro-vscode|mon|1.1.8
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
vscode-proun|oct|0.0.1
polacode|pnp|0.2.2
vscode-sort-json|ric|1.11.0
vscode-csstree|sme|0.7.0
language-stylus|sys|1.9.2
vim|vsc|0.12.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-06-15 06:48
@octref I tried to reproduce but cannot, e.g.:

![before](https://user-images.githubusercontent.com/900690/41454215-d654f6ce-7078-11e8-9e00-dcba3deb19ca.gif)

Do you see this with all icon themes? Do you also see this when the tab sizing is configured to "fit" instead of "shrink"?

**Comment by octref** [comment] 2018-06-15 15:56
Reproduced with Seti too. You need to set both `tabSzigin` to `shrink` and `tabCloseButton` to `off`.

**Comment by bpasero** [comment] 2018-06-15 16:15
@octref I can still not reproduce. Could it be that you have a scrollbar and the logic to reveal the tab is just kicking in?

**Comment by octref** [comment] 2018-06-15 16:48
I also got some artifact from wrong active tab highlighting, see:

![test](https://user-images.githubusercontent.com/4033249/41479686-d45d0fca-7080-11e8-84fe-5c104b30123a.png)

If I disable the 5px from the `::after`, things are back to normal:

![test2](https://user-images.githubusercontent.com/4033249/41479800-2e9b4e48-7081-11e8-8917-c2c4e6ded4e4.png)

**Comment by bpasero** [comment] 2018-06-15 16:52
@octref it is possibly related to your theme then, which one is it?

**Comment by octref** [comment] 2018-06-15 16:58
I narrowed it down to Material Theme, which writes this section to settings:

```
  "workbench.colorCustomizations": {
    "activityBarBadge.background": "#80CBC4",
    "list.activeSelectionForeground": "#80CBC4",
    "list.inactiveSelectionForeground": "#80CBC4",
    "list.highlightForeground": "#80CBC4",
    "scrollbarSlider.activeBackground": "#80CBC450",
    "editorSuggestWidget.highlightForeground": "#80CBC4",
    "textLink.foreground": "#80CBC4",
    "progressBar.background": "#80CBC4",
    "pickerGroup.foreground": "#80CBC4",
    "tab.activeBorder": "#80CBC4"
  }
```

When I remove this part from the settings, this does not happen any more.

**Comment by octref** [comment] 2018-06-15 17:01
Whichever theme that sets `tab.activeBorder` would cause this. Here is the minimalist repro:

```
{
    "workbench.editor.tabSizing": "shrink",
    "workbench.editor.tabCloseButton": "off",
    "workbench.colorCustomizations": {
        "tab.activeBorder": "#80CBC4"
    }
}
```

**Comment by bpasero** [comment] 2018-06-16 08:03
I can reproduce, this is because with that configuration we suddenly have 2 things using the `::after` element:
* the bottom border
* the gradient shadow

/cc @Dari-K

**Comment by bpasero** [comment] 2018-06-18 16:37
@Dari-K it seems to me we introduced a `::after` element for the only purpose to have some 5px margin to the right of the tab label such as the gradient does not show up unless the tab label is shrinking. Can you think of any other way how to accomplish this so that the `::after` element becomes free to be used for the bottom border?

The rule in question is: https://github.com/Microsoft/vscode/blob/8be8f654687341db407086c7e277d80b7055e12a/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css#L85-L91

**Comment by bpasero** [comment] 2018-06-19 05:32
Fixed by making the border-top/border-bottom elements in the tab container real DIVs so that we avoid the clash in `::after` elements.

**Closed by bpasero** 2018-06-19 05:32 UTC
Labels: bug, help wanted, workbench-tabs
