### ISSUE TITLE
Close Debug Console completly (if merged with other panels)

### ISSUE THREAD

**Issue by gitter-me** [microsoft/vscode#148616] opened 2022-05-03 07:57 UTC
I have merged the debug console, variables and watch panels at the bottom.
![sample](https://user-images.githubusercontent.com/47410353/166418937-3aaf1107-fed7-4de6-a330-413b0eb4119e.png)

I have also debug.console.closeOnEnd active.

If I stop the debugger the debug console collapes instead of closing the whole bottom panel

![sample2](https://user-images.githubusercontent.com/47410353/166419264-0fcbda3a-c15e-405d-a790-360f3270e148.png)

(If debug console is the only panel the whole bottom area closes.)

I' not sure if the behaviour is a bug or by design? Or is there already a setting to control this?
Otherwise a settings would be great if it should be collapsed or closed.

What I want to have is more a less: on debug start to open the bottom with all debug panels side-by-side and on exit debug to close the whole bottom area. 

I already use "debug.internalConsoleOptions" with "openOnSessionStart" and  
"debug.console.closeOnEnd"

Side note: I'm not too happy with the Run and Debug area on the left side, because after debugging I have to switch back to Explorer view and I'm constantly resizing the left side, because for debug the width is too small and for explorer then it is too wide.

**Comment by roblourens** [comment] 2022-05-03 16:07
Fair feature request, it feels weird to hide other unrelated views as a result of this setting, but the user opted in to it and I can't imagine anyone actually wants the current behavior.

@sbatten currently I call `IViewsService#closeView`. If I want to close the panel here, is there a way to find the parent view container and call `closeViewContainer`?

> I'm not too happy with the Run and Debug area on the left side, because after debugging I have to switch back to Explorer view and I'm constantly resizing the left side, because for debug the width is too small and for explorer then it is too wide.

Yeah, currently it can't be moved. You might try putting it in the "secondary side bar" if that helps, then you can have it a different size although on the other side of the screen.

**Comment by sbatten** [comment] 2022-05-03 16:15
@roblourens you can use the `IViewDescriptorService` to get any information you need. e.g. the ViewContainer will tell you its in Debug. The View Container Location can tell you which Part it is in.

**Comment by roblourens** [comment] 2022-05-13 23:39
Thanks. I'm confused about what I'm seeing though. I think I want to check whether the Debug Console view is inside the Debug Console view container (and not the debug sidebar or somewhere else). So I call `this.viewDescriptorService.getViewContainerByViewId(REPL_VIEW_ID);` and get back a View Container that has this id: `'workbench.views.service.panel.16bc7ee5-d929-4163-8a42-9ce36fe79429'` but I registered the view container with the id `'workbench.panel.repl'`, that happened here: https://github.com/microsoft/vscode/blob/2fd2a6041557ea4c7784b8ee7f785a114452a434/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L349-L357

Am I doing something wrong? I see another view container in the ViewContainersRegister (this is `viewContainersRegistry.all`)
<img width="560" alt="image" src="https://user-images.githubusercontent.com/323878/168401677-10936e24-0094-4bc3-b113-ce5192817592.png">

**Comment by sbatten** [comment] 2022-05-16 18:08
@roblourens please `Reset View Locations` and try reproducing again. The container id that you see suggests that you're debug panel view has been moved out of its original container.

**Comment by roblourens** [comment] 2022-05-16 21:04
It works after that. But then I rearrange views a little more and it gets the ID with the GUID again. 

![image](https://user-images.githubusercontent.com/323878/168660351-16a6ff3e-0457-41c1-914a-6e39302075c3.png)

I'm not sure whether it matters though, I guess I'm still trying to decide what the behavior should be.

@gitter-me do you think that the full panel should always close in this case? If I drag the debug console into the problems panel, should it close? Only when the title of the panel is Debug Console?

**Comment by gitter-me** [comment] 2022-05-24 11:24
@roblourens if you for example drag the debug console to the right of the problems panel the tab is labeled "problems", dragged to the left its called "debug console"

If you check for the tab title the usability gets a little bit complicated: To achieve what the settings suggest, you have to make sure the debug console is placed in a way that the tab reflect its name (in other words it must be the first on the left). Also this would be also a brittle implementation, if the tab naming logic or display text changes in the future. For this two reasons I would not use the title of the panel. 

I would close the bottom panel if the debug console is a visible child of the active panel (or if debug console is the only active panel [nothing grouped together] ) 
In your example, if the setting is active and you drag debug console into the problems, the whole panel should close.

**Comment by roblourens** [comment] 2022-06-08 17:04
I think we can just go with the logic of closing whatever view container the debug console is currently in. Makes sense to keep it simple because the user configured their views this way, and they changed the default of the setting to close the debug console, and if they don't like it they can reset that setting. Also consistent with the existing internalConsoleOptions setting which can show the debug console on session start, wherever it is.

**Closed** 2022-06-08 17:31 UTC
Labels: feature-request, debug
