### ISSUE TITLE
1.26 linux tar.gz crashes with segmentation fault

### ISSUE THREAD

**Issue by martynas-m** [Microsoft/vscode#56303] opened 2018-08-14 06:32 UTC
Issue Type: <b>Bug</b>

Updated to 1.26 (linux, 64bit). cant start with this error: 
[1]    22648 segmentation fault (core dumped)  vscode

downgraded to 1.25- works.

Please fix.

Thanks.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.14-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (7.62GB free)|
|Process Argv|/home/martynas/bin/VSCode-linux-x64/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
solidity|Jua|0.0.46
vim|vsc|0.16.0
ReactSnippets|xab|2.2.0

</details>

**Comment by bpasero** [comment] 2018-08-14 08:25
@martynas-m how do you start VSCode, from a terminal or dock?

**Comment by ltennstedt** [comment] 2018-08-14 09:05
I can confirm this. I tried to build the tag 1.26 directly form the Git repo under Linux without modifying anything.

'yarn install' works fine. The error will occur if './scripts/code.sh' is executed.

If I should provide some logs, please tell me where I can find or produce them.

OS: Arch Linux 64bit
Kernel: 4.17.14-arch1-1-ARCH
Bash: 4.4.023-1
Node.js: v8.11.3
npm: 6.3.0
Yarn: 1.9.4

**Comment by martynas-m** [comment] 2018-08-14 09:48
@bpasero - from terminal and from dmenu (app loader for i3 - there is no docs or desktop concept for [i3](https://i3wm.org))

**Comment by bpasero** [comment] 2018-08-14 10:47
@ltennstedt wait, you run "out of sources" and get this right? not when running the installed app?

@martynas-m 
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by martynas-m** [comment] 2018-08-14 11:38
Hi, 
I'm not good at linux debuging, it took some time to get this: (let me know if it's enough, otherwise, I can attach core file itself)

           PID: 5079 (code)
           UID: 1000 (martynas)
           GID: 1000 (martynas)
        Signal: 11 (SEGV)
     Timestamp: Tue 2018-08-14 14:22:33 EEST (11min ago)
  Command Line: ./code
    Executable: /home/martynas/Downloads/VSCode-linux-x64/code
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (martynas)
       Boot ID: 4a1a4a8f1b2f48858334b1bf69804390
    Machine ID: 2287a615b4fe43a48fedc9a32d611dc6
      Hostname: dell
       Storage: /var/lib/systemd/coredump/core.code.1000.4a1a4a8f1b2f48858334b1bf69804390.5079.1534245753000000.lz4
       Message: Process 5079 (code) of user 1000 dumped core.
                
                Stack trace of thread 5079:
                #0  0x0000000000ab6fd0 n/a (/home/martynas/Downloads/VSCode-linux-x64/code)

GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/martynas/Downloads/VSCode-linux-x64/code...(no debugging symbols found)...done.
[New LWP 5079]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./code'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000ab6fd0 in ?? ()
(gdb) bt
#0  0x0000000000ab6fd0 in  ()
#1  0x00007fc30378d9a2 in node::http2::Http2Session::Callbacks::Callbacks(bool) ()
    at /home/martynas/Downloads/VSCode-linux-x64/libnode.so
#2  0x00007fc30378da65 in  () at /home/martynas/Downloads/VSCode-linux-x64/libnode.so
#3  0x00007fc3039e86da in call_init.part () at /lib64/ld-linux-x86-64.so.2
#4  0x00007fc3039e87da in _dl_init () at /lib64/ld-linux-x86-64.so.2
#5  0x00007fc3039da03a in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in  ()
#7  0x00007ffd0ce061a4 in  ()
#8  0x0000000000000000 in  ()
(gdb)

**Comment by ltennstedt** [comment] 2018-08-14 12:41
@bpasero Yes, I cloned the GitHub repository and ran the following commands inside the root directory of the cloned Git repository:
- git checkout tag 1.26
- yarn install
- cd scripts
- ./code.sh

I build the newest tag regularly and I have also a self-written desktop file pointing to 'scripts/code.sh'. I always run 'code.sh' the first time from the console because it compiles some stuff the first time it is run.

The error will only show up if you run 'code.sh' from the command line. I hope that helps.

**Comment by ltennstedt** [comment] 2018-08-14 13:14
I wanted also to follow the wiki to provide useful information about the crash but the global installation of electron-atos via npm failed. I wanted to report the bug but the GitHub page says that 'Symbolicate an Electron macOS crash report'. Are you sure that I can install this on a Linux system?

**Comment by bpasero** [comment] 2018-08-14 13:49
Marking as duplicate of https://github.com/Microsoft/vscode/issues/51917 which I just reopened.

**Closed by bpasero** 2018-08-14 13:49 UTC
Labels: electron-2.0.x-update, freeze-slow-crash, needs more info
