### ISSUE TITLE
Python Debug Console doesn't honor newline char

### ISSUE THREAD

**Issue by rfernand2** [microsoft/vscode#90849] opened 2020-02-17 22:10 UTC
Issue Type: <b>Bug</b>

For example, if I go to the debug console while debugging a Pandas Data Frame object named "df" in a python app and enter the expression "df.describe()", the output is shown as a single line with embedded "\n" newline characters, instead of multiple lines, as one would see at the python command line, a jupyter notebook, or the output of a python program running in an OS command line.  

This ignoring of the newline character makes it extremely hard to interpret output from python programs and functions.  Please change this behavior to create new output lines when a newline character is encountered in the output.  At a minimum, please provide an easy-to-find option that toggles this behavior on and off.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment] 2020-02-18 09:37
This is fixed in vscode insders. Duplicate of a fixed issue.

**Closed by isidorn** 2020-02-18 09:37 UTC
