### ISSUE TITLE
vscode 路径 e:\vscode\resources\app\extensions\typescript\node_modules\typescript\lib 未指向有效的 tsserver 安装。将禁用 TypeScript 语言功能。

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#18038] opened 2017-01-03 12:31 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. version 1.8.1
2.

**Comment by rebornix** [comment] 2017-01-03 15:57
`The path {0} doesn\'t point to a valid tsserver install. TypeScript language features will be disabled `

**Comment by mjbvz** [comment] 2017-01-03 18:21
This looks like a duplicate of #16246

@ydcoming Can you please check the listed path and let us know if the file exist there. 

There are several possible workarounds as well:

* You can also try reinstalling VSCode which may resolve the issue
* Use `typescript.tsdk` to point to a different typescript install in your workspace.
* Try  upgrading to 1.9-insiders, which includes a new version of TypeScript

**Comment by ydcoming** [comment] 2017-01-04 02:40
what i am using is javascript  not typescript! why i must need TypeScript.it is JavaScript! I do not want to use typescript.tsdk

**Comment by mjbvz** [comment] 2017-01-04 17:53
@ydcoming We use the TypeScript library to analyze both TypeScript and JavaScript in VSCode.

Please try running through the suggestions and let me know if they resolve the issue.

Thanks

**Comment by ydcoming** [comment] 2017-01-05 09:41
it does not work i think it is a bug

**Comment by mjbvz** [comment] 2017-01-05 21:47
@ydcoming Did you work through the suggested steps?

Also, can you please check to see if the referenced folder exists.

**Comment by mjbvz** [comment] 2017-01-09 22:31
Closing as we need more information to investigate this

**Closed by mjbvz** 2017-01-09 22:31 UTC
Labels: duplicate, needs more info, typescript
