### ISSUE TITLE
Windows 7 Pro: Terminal text disappears on VSC window resize, pane snap & Explorer pane resize.

### ISSUE THREAD

**Issue by danaoira** [Microsoft/vscode#31420] opened 2017-07-26 00:26 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.1.6
vetur|oct|0.9.3
vscode-icons|rob|7.11.0

(4 theme extensions excluded)

---

Steps to Reproduce:

Console before error.
![image](https://user-images.githubusercontent.com/2514403/28599245-ce1fafb4-715d-11e7-969a-807563ac93bf.png)

1. Have console output text.
2a. Move VSC to left or right side of screen so that the "pane snap" preview appears.
2b. Resize VSC window to a smaller size.
2c. Adjust Explorer size to make terminal smaller.
3. Parts of the terminal text will disappear and cannot be recovered.

![image](https://user-images.githubusercontent.com/2514403/28599256-e4ad5330-715d-11e7-8798-418c62fcc860.png)

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment] 2017-07-26 04:57
@danaoira 
cc @Tyriar
This is by design and a function of the way xterm interacts with the shell.
Duplicate of #30430
See discussion there as well.

**Closed** 2017-07-31 17:02 UTC
Labels: integrated-terminal, new release
