### ISSUE TITLE
"source.organizeImports" is removing my imports on js(x) files

### ISSUE THREAD

**Issue by rebelliard** [Microsoft/vscode#49457] opened 2018-05-08 13:05 UTC
Issue Type: <b>Bug</b>

**Steps to Reproduce:**

1. Enable   `"editor.codeActionsOnSave": {"source.organizeImports": true}`.
2. Save a file with default exports (e.g., `export {Video, Chat}`).
3. VS Code will delete the imports instead of organizing them.
* See video [here](https://drive.google.com/file/d/1MruTpS6isBtfRxc6vB5lR8Z-RzU77Ypq/view).

**Does this issue occur when all extensions are disabled?**: Yes.

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (0.66GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.1
bracket-pair-colorizer|Coe|1.0.48
vscode-markdownlint|Dav|0.15.0
EditorConfig|Edi|0.12.1
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
vscode-custom-css|be5|2.7.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
mustache|daw|1.1.1
jshint|dba|0.10.18
githistory|don|0.4.0
eslint-disable-snippets|drK|1.1.4
gitlens|eam|8.2.4
tslint|eg2|1.0.28
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
debugger-for-chrome|msj|4.4.3
vscode-code-outline|pat|0.1.1
vscode-icons|rob|7.23.0
vscode-fileutils|sle|2.8.1
es6-mocha-snippets|spo|0.1.2
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.6.2

**Comment by Cameri** [comment] 2018-05-08 13:10
I'm experiencing the same issue.

I'm running VSCode Insiders build:
```
Version 1.23.0-insider
Commit e545ae6b34aae3f05a923d5258adbb58805ca27f
Date 2018-04-27T05:11:37.547Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64```

**Comment by mrmartineau** [comment] 2018-05-08 14:56
@rebelliard I found this to be the case too. I think it is a "feature" in this scenario because those imports are not being used when you saved the file.

**Comment by rbelliard-vivial** [comment] 2018-05-08 15:00
I don't think it should be a feature, as it breaks my ability to create an index file:

	// components/index.js
	import Chat from './Chat'
	import Conference from './Conference'
	import Video from './Video'
	
	export {Chat, Conference, Video}

and then use it as:
	
	// pages/index.js
	import {Chat, Conference, Video} from '../components'

**Comment by rebelliard** [comment] 2018-05-08 15:01
I don't think it should be a feature, as it breaks my ability to create an index file:

	// components/index.js
	import Chat from './Chat'
	import Conference from './Conference'
	import Video from './Video'
	
	export {Chat, Conference, Video}

and then use it as:
	
	// pages/index.js
	import {Chat, Conference, Video} from '../components'

**Comment by mrmartineau** [comment] 2018-05-08 15:18
@rebelliard sorry, you are right. The video example was blurry and I did not see that. There are a few [other](https://github.com/Microsoft/vscode/issues/49416) [issues](https://github.com/Microsoft/vscode/issues/49193).

It looks like the issue has been fixed on the insiders build, see this comment: https://github.com/Microsoft/vscode/issues/49416#issuecomment-387236575

**Comment by lipis** [comment] 2018-05-08 15:34
Same thing happens with `.tsx` files.

**Comment by mjbvz** [comment] 2018-05-08 17:58
Duplicate of #49193 

Fixed in insiders

**Closed by mjbvz** 2018-05-08 17:58 UTC
Labels: new release
