### ISSUE TITLE
Opening Developer Tools undocked asks for default program in Windows 10

### ISSUE THREAD

**Issue by lalo-mx** [microsoft/vscode#72621] opened 2019-04-19 19:52 UTC
Issue Type: <b>Bug</b>

Open Visual Studio Code
Toggle Developer Tools
Undock the Developer Tools
A dialog appears with the message "You will need a new app to open this chrome-devtools"

VS Code version: Code - Insiders 1.34.0-insider (7d39e805fb66a6eac22f19af8bb90f48da863fd5, 2019-04-19T05:19:16.037Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.86GB (5.35GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by sbatten** [comment] 2019-04-24 01:53
I am not sure why this happens. A vanilla electron app does not reproduce the issue. Will keep investigating.

**Comment by sbatten** [comment] 2019-10-09 00:21
@deepak1556 you might have the dupe of this issue

**Comment by cuongthm** [comment] 2020-08-01 12:31
On latest version "1.47.3", the message is **"You will need a new app to open this devtools"**.

**Comment by rzhao271** [comment] 2021-01-14 18:51
Is it me or is this issue fixed now in [Insiders](https://code.visualstudio.com/insiders/)?
Can anyone still reproduce this issue using it?

**Comment by sbatten** [comment] 2021-01-14 19:13
@rzhao271  seems resolved for me in insiders as well

**Closed** 2021-01-25 17:43 UTC
Labels: bug, fixed-in-electron-11, windows
