### ISSUE TITLE
Rectangular selection doesn't work

### ISSUE THREAD

**Issue by ayeressian** [Microsoft/vscode#1926] opened 2016-01-11 13:44 UTC
I hold alt and click and hold left mouse button. It doesn't select the text in rectangular way.
I am running OSX elcapitan.

**Comment by isidorn** [comment] 2016-01-11 15:20
This is a feature that for instance sublime text supports, but we do not have it yet. I noticed that sublime text inserts multi cursors

**Comment by glen-84** [comment] 2016-01-18 08:14
Duplicate of #84?

**Comment by alexandrudima** [comment] 2016-01-29 09:39
:+1: I'll keep this one around, as it gives a great concise description of what should be implemented

**Closed** 2016-03-17 12:14 UTC
Labels: editor, feature-request
