### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lucasrivoiro** [Microsoft/vscode#225] opened 2015-11-19 13:55 UTC
After the latest update of visual code constantly closed because of crashes.

**Comment by h2u** [comment] 2015-11-19 13:59
do you have similar issue? - #160

**Comment by bpasero** [comment] 2015-11-19 14:05
@lucasrivoiro can you share more details about your environment? and maybe the interaction you do that leads to the crash.

**Comment by lucasrivoiro** [comment] 2015-11-19 15:40
Of course! As will typing in code, the program just freeze, but the menus
(file, edit, view) continue to function normally. After a few seconds the
windows warns that the program is not responding and the only solution is
to close the program. There is no specific situation I've noticed that
causes the problem.

2015-11-19 12:05 GMT-02:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment] 2015-11-20 20:30
@lucasrivoiro is this editing PHP maybe?

**Comment by lucasrivoiro** [comment] 2015-11-21 11:54
Yes, but C too.

Lucas Rivoiro
Em 20 de nov de 2015 6:30 PM, "Benjamin Pasero" <notifications@github.com>
escreveu:

**Comment by eByte23** [comment] 2015-11-23 04:59
I have experienced crash/freezing but have manage to recover twice after waiting for a long period of time and received a message about an extension being unresponsive or something, but I have no 3rdparty extensions installed.

Occurred while editing php and standard text files

**Comment by bpasero** [comment] 2015-11-23 14:24
Closing as duplicate of #160

**Closed by bpasero** 2015-11-23 14:24 UTC
Labels: Needs More Info
