### ISSUE TITLE
Windows: possible to have drag overlay stick around

### ISSUE THREAD

**Issue by KevinMarquette** [Microsoft/vscode#10970] opened 2016-08-25 18:54 UTC
- VSCode 
  Version 1.5.0-insider
  Commit 435df14a684df718c5ec523f9d674e63d1662c37
  Date 2016-08-22T08:10:56.602Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version: Windows 7

Steps to Reproduce:
1. Open Code to a folder with lots of folders and files
2. Open 2 explorer windows and place them in front of Code leaving the tree view visible between them
3. Click and drag a folder between the 2 explorer windows and over the tree view.
4. Drag back and fourth fairly quickly watching Code gray out and return to normal.
5. Watch for it to not restore back to normal.
6. Bring Code into focus.
7. See that you cannot interact with the Code editor window.
8. The File Menu bar does continue to work.
9. Drag a file or folder back over Code to restore functionality.

Sometimes it will reproduce very nicely and other times hardly at all. I think the folder/file structure in the tree view makes a difference. I can only do this with folders and not files and the motion has to be fairly fast. As if it misses the mouse leaving the window event or something like that.

[OK]

**Comment by bpasero** [comment] 2016-08-26 10:17
Thanks much for the steps, I was waiting for steps to reproduce. Unfortunately I am not able to find a good fix to prevent the gray from showing up in this scenario but I pushed a fix so that the workbench removes the overlay when the mouse moves into the workbench. This fixes the issue with having a non-functional workbench around.

**Comment by bpasero** [comment] 2017-05-15 05:05
I cannot reproduce anymore.

**Closed by bpasero** 2017-05-15 05:05 UTC
Labels: bug, help wanted, workbench
