### ISSUE TITLE
Intellisense is Broken for Packagees

### ISSUE THREAD

**Issue by chamalperera** [microsoft/vscode#210013] opened 2024-04-10 05:40 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. I have NPM Intellisense installed in my VS Code.
2. I am developing a ReactJS project.
3. I have installed Material UI packages through NPM
4. Use the components available in the Material UI
5. When I typed a part of the name of a component, the intellisense gave me the suggestions from different packages 
6. I then updated the VS Code to the latest release (v1.88)
7. And after that when I tried to use the components, the intellisense does not gives me the correct suggestions.

![image](https://github.com/microsoft/vscode/assets/86777399/dac3eb4b-0db8-4710-86de-6ad6ed9252bb)
![image](https://github.com/microsoft/vscode/assets/86777399/94aae49b-75f7-42b6-bb48-9b3768630ba5)

**Comment by gjsjohnmurray** [comment] 2024-04-10 06:10
Probably https://github.com/microsoft/TypeScript/issues/58113#issuecomment-2043273180

**Comment by steeljustify** [comment] 2024-04-10 08:22
I have no intellisense for anything at all. Not tsconfig, not package.json, not even for the console object in a js file. The same project intellisense works fine in visual studio and webstorm.

**Comment by mjbvz** [comment] 2024-04-10 18:44
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by lyricalcasanova** [comment] 2024-04-10 22:24
@mjbvz & @gjsjohnmurray 
We started an issue in MUI about this, because it seems to only affect certain packages.
Not sure if there is already an existing issue for this or if this is where we should tag to but for now the easiest workaround is to downgrade to 1.87.2 we found

I can confirm that the issue still is persistent and not fix currently in the 1.89.0 (Insiders) the MUI imports still have the same issues.

Imports work in ts/tsx but do not resolve properly in js/jsx for MUI Specifically at least
.ts / .tsx works correctly as expected:
![image](https://github.com/microsoft/vscode/assets/33468668/c9f089e7-2036-4258-9e52-7539e46958f7)

.js / .jsx does not work correctly:
![image](https://github.com/microsoft/vscode/assets/33468668/06ecd80d-07f3-43d4-8a04-88ddb795b93e)

Would love to find a main issue to tag for this to get fixed quickly! Thank you! 😄
mui/material-ui#41802

**Comment by mjbvz** [comment] 2024-04-10 22:27
@lyricalcasanova https://github.com/microsoft/TypeScript/issues/58113 but this user isn't seeing any intellisense so possible not related

**Comment by lyricalcasanova** [comment] 2024-04-10 22:32
Curious @mjbvz what would be the easiest way for me to test the solution proposed in that issue "You should be able to use the nightly TS extension to work around this for now." if you can offer a few more details on this I could see if it works unless that's just switching from .js to .ts instead as I show above?

**Comment by mjbvz** [comment] 2024-04-10 22:34
You can either install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next or install `typescript@next` in your workspace and run `Select typescript version` to use it

**Comment by lyricalcasanova** [comment] 2024-04-10 22:39
> You can either install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next or install `typescript@next` in your workspace and run `Select typescript version` to use it

This is exactly what is needed to be updated can confirm works as intended after installed
I would put this at the top of the list on priority as there will probably be A LOT more people soon if their VS Code auto updates like mine did and they don't have the extension installed and are facing the same issue

It is VERY hard to search for this issue as I didnt know if this was VS or MUI originally and most people won't

![image](https://github.com/microsoft/vscode/assets/33468668/208c3cf5-9efc-405f-96ae-0b9b05e67db9)

**Comment by mjbvz** [comment] 2024-04-10 22:40
That's why were releasing a recovery release for it

**Comment by lyricalcasanova** [comment] 2024-04-10 22:43
Where can the progress for that be viewed? I assume there's a PR but thank you once again !

**Comment by mjbvz** [comment] 2024-04-10 22:44
https://github.com/microsoft/vscode/issues/209915

**Comment by lyricalcasanova** [comment] 2024-04-10 22:51
Thank you for all the help!
I assume this can be closed as duplicate because I know the OP has the exact same issue as me he just typed the full component name and then waited for suggestions as shown:
![image](https://github.com/microsoft/vscode/assets/33468668/f48f8c69-8c4b-4862-b2a8-ec19aa118ecb)

PLEASE add those same details you gave me above to the original issue as I actually saw that but it was too vague and didn't seem related since I was using .JS / .JSX

**Comment by chamalperera** [comment] 2024-04-11 05:38
Hi @mjbvz & @lyricalcasanova

It seems it is an issue with the latest release of VS Code v1.88.0. I have gone through all the comments @lyricalcasanova  provided, and thanks so much for giving many details of the issue.

I have installed the JavaScript and TypeScript Nightly extension into my VSCode and selected the VSCode version. But I am still having the same issue, it does not show me the correct suggestions.  Have I done it incorrectly? Or do we have workaround for this issue? Or do we have to wait until the next release?

![image](https://github.com/microsoft/vscode/assets/86777399/3d233b24-6d1b-4c07-9265-2ef8b4c212aa)

**Comment by lyricalcasanova** [comment] 2024-04-11 07:11
If all else is failing you can also attempt to revert back to 1.87.2 of VS Code which is confirmed to be working without the extension (Don't forget to disable automatic updates) 

If the issue still persists, most likely you need to install the packages again in the root of your project where your package.json is located execute the command below and it will install all the packages required for mui if not already install and give an error if there are any:
```npm install @mui/material @emotion/react @emotion/styled```

(I accidentally did this a few times while pulling my original code and forgetting to reinstall the deps so some of my tests I realized were failing no matter what because the packages didn't exist in my project)

**Comment by mjbvz** [comment] 2024-04-11 15:22
@chamalperera Does any IntelliSense work? Try opening an empty javascript or typescript file and triggering suggestions

 Also did you test in the latest insiders build?

**Comment by chamalperera** [comment] 2024-04-12 00:51
Hi @mjbvz & @lyricalcasanova,

I have updated the VS Code to the lastest release v1.88.1 which resolves the issue. I can confirm the auto imports are now working. I have tested it aftre uninstalling the TypeScript & JavaScript Nightly extension, which @lyricalcasanova suggested earlier as a workaround.

If VS Code is updated to v1.88.1, issue should be gone

**Closed** 2024-04-13 02:01 UTC
Labels: info-needed
