### ISSUE TITLE
git checkout branch/tag list ignores git.branchSortOrder when filtering

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#183583] opened 2023-05-26 19:22 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Mac OS 13.4

Steps to Reproduce:

1. Ensure `git.branchSortOrder` is set to "committerdate"
2. Run the `git.checkout` command
3. Observe that branches/tags are sorted w/ the most recent committed branch/tag first
4. Enter text to filter the branch/tag list
5. Observe that branches/tags are now sorted alphabetically

This has been particularly unhelpful when I've been attempting to check-out a release branch for a project where I filter by the "release-" prefix and I would expect to see the most recent release branches at the top of the list.

**Comment by lszomoru** [comment] 2023-12-19 12:44
Closing as duplicate of https://github.com/microsoft/vscode/issues/199471

**Closed by lszomoru** 2023-12-19 12:44 UTC
Labels: bug, git, papercut :drop_of_blood:
