### ISSUE TITLE
Js automatic prompt in html files

### ISSUE THREAD

**Issue by JHeLiu** [Microsoft/vscode#56117] opened 2018-08-10 01:10 UTC
Because I have been using VS and not VS CODE, when I turn around, some are not suitable,
1, its JS file can not be dragged into the HTML project I wrote like VS
2. When I am working on my own project, I hope that my own js can also be prompted in my project, such as the Html page.
3, because these things in VS are what our developers do not need to consider. This is really convenient, I hope VSCODE should also inherit this feature of VS.
I tried to find information help in this area, but it was not what I wanted, so I came here to ask for help. Can you give me some help?

**Comment by ramya-rao-a** [comment] 2018-08-10 01:56
>  its JS file can not be dragged into the HTML project I wrote like VS

- Where are you dragging the js file from and where are you dropping it?
- Are you expecting the file to moved into the dropped folder/project?

> When I am working on my own project, I hope that my own js can also be prompted in my project, such as the Html page.

You are expecting suggestions from your js file in the <script> tag of your html file?

**Comment by JHeLiu** [comment] 2018-08-10 02:16
Because it is not a good demonstration here, I try to explain it a little bit;
I don't know if you have used Visual Studio's full line of products, including Visual Studio 2017, I will say 2017. When I create a new project, it should have //
1, html / js /csss
I open html I just hold down my project list js file and drag it to the html file. It will automatically fill in the <script src="/script/config.js"></script> tag for me, yes or no Wrong, this is very convenient.

2. When I introduce my own js file in the html page, for example (test.js), if this is the case.
<script src="/script/test.js"></script>

I don't need any management in Visual Studio, it will automatically prompt me for any function written in test.js.

Visual Studio Code does not have this by default. I don't know how

**Comment by ramya-rao-a** [comment] 2018-08-10 02:30
We dont support drag and drop inside existing file, so we cant really support the first case. But what we can look into is providing prompts/suggestions for your js files when you have `<script src="">` tag and the cursor is inside the "". cc @mjbvz and @octref for path completion

For the second case, are you saying that if there is a `<script src="/script/test.js"></script>` in a html file, then in further `<script>` tags, you want prompts/suggestions for functions from the `test.js` file.

**Comment by JHeLiu** [comment] 2018-08-10 02:38
Yes, I need VS CODE to have this mechanism by default.

Suppose I wrote a test.js library myself, there is a test() function, I reference it to my html page, then I reference it in the html page, I hope it can prompt the function inside test.js, for example Test();


-- test.html
-- test. js

In the html reference:
<script src="/test.js"></script>

<script >

//Here, I hope it will automatically prompt me for all the function methods in test.js
//Visual Studio is doing it and Visual Studio Code is not

**Comment by ramya-rao-a** [comment] 2018-08-10 02:43
Thanks for that clarification

**Comment by JHeLiu** [comment] 2018-08-10 03:08
I brought a dynamic picture to express,
I hope that the future vs code will have such a default feature like Visual Studio, which is great.

![vs2017](https://user-images.githubusercontent.com/15246138/43936957-b26c363c-9c8d-11e8-91f7-a6fb58dccb72.gif)

**Comment by octref** [comment] 2018-08-10 04:58
Let's say you have

```
/index.html
/static/
  /test.js
```

And `/static/` is served at top-level.
Then `<script src="./static/test.js">` will be wrong, as the correct path would be `./test.js` or `/test.js`.

And today users usually only include a few scripts tags, as most of the path handling is done through bundlers like webpack. So I feel this feature is hard to make it work in all cases and wouldn't be too useful.

**Comment by aeschli** [comment] 2018-08-10 05:48
duplicate of #5772

**Closed by aeschli** 2018-08-10 05:48 UTC

**Comment by JHeLiu** [comment] 2018-08-10 06:14
@octref  
Well, you are right, I have been looking for smart tips for VS CODE development tools, I don't know how to write js packages. How do you have good suggestions on your project smart tips?

**Comment by octref** [comment] 2018-08-10 06:59
@JHeLiu Do you mean things like https://github.com/Microsoft/vscode-tips-and-tricks?
