### ISSUE TITLE
how to make debug console vertical

### ISSUE THREAD

**Issue by erichocean** [Microsoft/vscode#3357] opened 2016-02-23 17:06 UTC
It's changed to horizontal and now consumes 40% of my editor space automatically every time I run my program. Extremely annoying, and impossible to get rid of: closing it just reopens it the moment something logs to the console.

How can I get the previous "vertical" debugger? Or better yet, how can I pull the debug console out into its own window?

**Comment by joaomoreno** [comment] 2016-02-24 08:49
Duplicate of #2806

**Closed by joaomoreno** 2016-02-24 08:49 UTC
