### ISSUE TITLE
How to quickly jump.Less files？

### ISSUE THREAD

**Issue by Linbubin** [Microsoft/vscode#39910] opened 2017-12-08 02:37 UTC
I can ctrl + left mouse  to  jump js files
![image](https://user-images.githubusercontent.com/19225429/33748306-b38d5e02-dc02-11e7-85fe-0900189487ba.png)

but when I do it for .less file, no reaction

Is there any configuration or plug-in that can quickly locate the corresponding .less file

**Comment by aeschli** [comment] 2017-12-13 08:56
duplicate of #29899

**Closed by aeschli** 2017-12-13 08:56 UTC
