### ISSUE TITLE
Error Loading Webview

### ISSUE THREAD

**Issue by Embercleave** [microsoft/vscode#196218] opened 2023-10-22 20:23 UTC
Error loading webview: Error: Could not register service worker: AbortError: Failed to register a ServiceWorker for scope ('https://15a1n67slk34baefkk71ap1thgoj8e0ophadgo25ml5om22vkkha.assets.github.dev/stable/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://15a1n67slk34baefkk71ap1thgoj8e0ophadgo25ml5om22vkkha.assets.github.dev/stable/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=codespaces+bookish-computing-machine-pjpq4764p6pc7x9g'): Operation has been aborted.
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Embedder: codespaces

this happens every time i open my codespace and it comes up with the same error every time i try to use the duck debugger that comes with this codespace.

**Comment by junman95** [comment] 2023-11-15 15:08
I am having same issue.
I am currently using 1.84 to develop my vsc extension.
As having feedback on version compatibility especially on vsc 1.83
So I downgrade my app and ran my extension and getting same error as above.
Below is my webview debug console and error messages.

![image](https://github.com/microsoft/vscode/assets/22022776/3f392a09-4bae-43ff-b978-697884d64f52)

**Comment by junman95** [comment] 2023-11-15 15:28
> I am having same issue. I am currently using 1.84 to develop my vsc extension. As having feedback on version compatibility especially on vsc 1.83 So I downgrade my app and ran my extension and getting same error as above. Below is my webview debug console and error messages.
> 
> ![image](https://user-images.githubusercontent.com/22022776/283158558-3f392a09-4bae-43ff-b978-697884d64f52.png)

I fixed that issue by below reference
https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

You should check it out.
Point is to close all existing vscode apps.

**Comment by mjbvz** [comment] 2023-11-15 22:45
@junman95 That will only work desktop. This issue is for web

@Embercleave What browser are you using?

**Comment by Embercleave** [comment] 2023-11-16 15:45
> @junman95 That will only work desktop. This issue is for web
> 
> @Embercleave What browser are you using?

I am using duckduckgo but now that i've tried it seems to work for whatever reason on both it and google. for weeks before this it never seemed to work and now apparently it just does.

**Comment by mjbvz** [comment] 2023-11-16 22:33
Thanks for testing again. Closing since it sounds like the issue is no longer happening

**Closed by mjbvz** 2023-11-16 22:33 UTC
Labels: info-needed, webview, web
