### ISSUE TITLE
SSH Remote not working version 1.44

### ISSUE THREAD

**Issue by haimtz** [microsoft/vscode#94893] opened 2020-04-10 10:59 UTC
- VSCode Version: 1.44
- OS Version: Windows 10 pro
- extension Remote -SSH version: 0.51.0

Steps to Reproduce:

1. go to Remote Explorer
2. select remote host to connect
3. password dialog will open type your password
4. the connect will fail all the time although the password is correct 

i was downgrade the VS code version and the ssh connection is working

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lwp001** [comment] 2020-04-10 13:40
the vscode   start  in remote-server  server.sh  --host=127.0.0.1  me too not work

**Comment by RMacfarlane** [comment] 2020-04-10 16:05
Duplicate of https://github.com/microsoft/vscode/issues/94816

**Closed** 2020-04-10 16:05 UTC
Labels: *duplicate
