### ISSUE TITLE
Emmet - a perf hooligan?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#71381] opened 2019-03-28 13:32 UTC
The top 5 of extensions blocking the extension host process has a newcomer and that's emmet. In 1.31.1 it was top 20, with 1.32.3 it 2nd with 26037 hangs over 5 seconds. I don't have a profile at hand and I also don't use emmet but looking at its implementation might explain it, esp since it doesn't do things in LSP-style but in-proc, e.g probably slowing everything down when a file is large/huge

**Comment by octref** [comment] 2019-03-28 15:52
Likely the cause of https://github.com/Microsoft/vscode/issues/70371, will investigate.

Emmet re-parses the file on each edit to determine which region (html attribute? html attribute value? css-in-html? jsx in ts file? css property?) emmet is in.

IMO the proper solution would be either having an API where extensions can figure out regions, but we have decided to not expose TM scopes to extensions.

The alternative is to have emmet hook into the on completion visitors of each LS. I remember @ramya-rao-a said there was issues with JS/CSS LS and with completion trigger characters.

**Comment by ramya-rao-a** [comment] 2019-03-28 17:16
@jrieken When you say "top 5" and "top 20" is this something coming from the users or telemetry or your local usage?

AFAIK Nothing has changed in terms of emmet parsing files in almost a year, so why the sudden change?

Regarding the alternative for emmet to hook into html and css completion providers, we did find good results with html, but not with css. The css language server is not great in identifying the right places where emmet should kick in, especially in in-complete css files. Please see #29113

**Comment by octref** [comment] 2019-03-28 18:10
@ramya-rao-a I'll see what has changed. The only one I recall is https://github.com/Microsoft/vscode/pull/68326, but that's related to wrapping not typing emmet abbreviations in general. Thanks for linking #29113 too.

I'm also interested in the full list.

**Comment by octref** [comment] 2019-05-09 20:31
Using `@emmetio/html-matcher` to parse the HTML source of https://microsoft.github.io/language-server-protocol/specification takes 2-3 seconds. That's for each document change.

In comparison, HTML parser took between 50-100ms.

**Comment by octref** [comment] 2019-05-10 22:56
@ramya-rao-a Wondering what's the original reason for choosing `@emmetio/html-parser` instead of using `vscode-html-languageservice`. I think the proper solution to #70731 is either replacing the parser or do incremental parsing by:

- Look at changes
- Find closest ancestry html node that contain the changes
- Only use the parser to parse that region

**Comment by ramya-rao-a** [comment] 2019-05-12 03:50
@octref The issue you linked is to a non emmet problem, can you link the right issue?

From what I recall, we had good results from moving emmet completions for html to the html language service. What didn't work out well was the move for css/scss/less etc. And the call we took at the time was that we either move both or none at all.

The only caveat with moving to html language service is the problem of how to support emmet completions in non html files

**Comment by octref** [comment] 2019-05-12 21:12
Fixed link.

We can just switch to using the html parser, which seems to be much faster than emmet's, and still keep emmet as a separate extension.

**Comment by shepelevstas** [comment] 2019-07-06 08:31
Is it solved? I just updated to the latest version and it fills like emmet got slower.
![emmet](https://user-images.githubusercontent.com/14919836/60753867-ff975f80-a002-11e9-9c7d-b8f5f2a6eb5e.gif)

**Comment by Download** [comment] 2019-08-25 18:59
According to this issue it should be fixed:
https://github.com/microsoft/vscode/issues/70371

**Comment by octref** [comment] 2019-11-07 04:31
I fixed two major perf issues for emmet. Think those are the most common cases for hangs (completion, tab-expansion).

Look forward to see a new list of hooligans.

**Closed by octref** 2019-11-07 04:31 UTC
Labels: extensions, freeze-slow-crash, perf
