### ISSUE TITLE
TS Server fatal error:  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by royalbhati** [microsoft/vscode#106613] opened 2020-09-14 01:57 UTC
\Issue Type: <b>Bug</b>

**TypeScript Version:** 4.1.0-dev.20200911

**Steps to reproduce crash**
Started Popping in vscode

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13424:55)
    at getTextOfNode (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13449:16)
    at Object.declarationNameToString (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:13761:66)
    at getDisplayName (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39745:53)
    at declareSymbol (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39859:111)
    at bindExportsPropertyAssignment (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41969:17)
    at bindWorker (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41665:29)
    at bind (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41554:13)
    at bindExpressionStatement (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40619:13)
    at bindChildren (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40104:21)
    at bind (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41565:21)
    at /Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:94
    at Object.forEach (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:188:30)
    at bindEach (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40052:16)
    at bindEachFunctionsFirst (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40045:13)
    at bindChildren (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40144:21)
    at bindContainer (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:40002:17)
    at bind (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:41568:21)
    at bindSourceFile (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39611:17)
    at Object.bindSourceFile (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:39550:9)
    at initializeTypeChecker (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:77500:20)
    at Object.createTypeChecker (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:43597:9)
    at Object.getTypeChecker (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:104583:79)
    at synchronizeHostData (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144689:21)
    at Proxy.getProgram (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:144771:13)
    at InferredProject.Project.updateGraphWorker (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149616:53)
    at InferredProject.Project.updateGraph (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:149549:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:151631:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153151:26)
    at /Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:97
    at Object.flatMap (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:153408:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:154427:46)
    at /Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:88
    at IOSession.Session.executeWithRequestId (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156291:28)
    at IOSession.Session.executeCommand (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156300:33)
    at IOSession.Session.onMessage (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:156324:35)
    at Interface.<anonymous> (/Users/royalbhati/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.1.20200911/node_modules/typescript/lib/tsserver.js:158540:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T00:56:22.923Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|24, 9, 5|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv|. --crash-reporter-id 72a6b389-2857-4e96-a4ab-b36f85ce0e19|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.4.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.56
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.6.0
go|gol|0.16.2
debug-visualizer|hed|2.0.6
headwind|hey|1.7.0
theme-monokai-pro-vscode|mon|1.1.17
vscode-typescript-next|ms-|4.1.20200913
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
mdx|sil|0.1.0
code-spell-checker|str|1.9.0
ayu|tea|0.20.1
vscode-icons|vsc|10.2.0
full-react-snippets|wal|1.4.2
JavaScriptSnippets|xab|1.8.0
vscode-mdx-preview|xyc|0.3.0
material-theme|zhu|3.8.7

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-09-14 18:18
Duplicate of https://github.com/microsoft/TypeScript/issues/40513

**Closed by mjbvz** 2020-09-14 18:18 UTC
