### ISSUE TITLE
Weird selection behavior with consecutive Notebook cells

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#119703] opened 2021-03-23 20:19 UTC
- VS Code Version: 1.55.0-insider (Universal)
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open a Jupyter Notebook with 2 cells of Markdown.
2. See weird behaviour

![recording (22)](https://user-images.githubusercontent.com/12758612/112212411-2f710700-8bda-11eb-9cce-8ecacb5ac132.gif)

**Comment by mjbvz** [comment] 2021-03-23 20:28
Duplicate of #119515 I believe

**Closed by mjbvz** 2021-03-23 20:28 UTC
Labels: bug, notebook
