### ISSUE TITLE
textEditor.insertSnippet: what does multiple ranges do?

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#19447] opened 2017-01-26 16:07 UTC
Testing #15952

Create the following extension:
```typescript
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        if (!vscode.window.activeTextEditor) {
            console.log('No editor');
            return;
        }
        let doc= vscode.window.activeTextEditor.document;
        let lines= [ doc.lineAt(0).range, doc.lineAt(2).range];
        vscode.window.activeTextEditor.insertSnippet(new vscode.SnippetString('for (var ${1:i}=0; ${1:i}<len; ${1:i}++) { $0 }'), lines);
    });

    context.subscriptions.push(disposable);
}
```

- run the extension, open an editor and run the 'hello world' command.
Only the first line is replaced. I somehow expected that the first and third line are affected.

**Comment by jrieken** [comment] 2017-01-27 08:28
It inserts the snippet multiple times, but today we only support that for snippets that only define the final cursor position, like `foo$0bar`. Closing as dupe of #16037

**Closed by jrieken** 2017-01-27 08:28 UTC
