### ISSUE TITLE
[folding] Allow automatic folding of region on file open

### ISSUE THREAD

**Issue by scooobs** [microsoft/vscode#142062] opened 2022-02-03 08:12 UTC
Currently you can define custom folding regions (see [here](https://code.visualstudio.com/docs/editor/codebasics#_folding)), these work really well however sometimes you have files with large chunks of code which you want to fold each time you open the file.

I think it would be useful if you could define regions which when the file is opened are automatically folded. Perhaps an implementation could be on the start region tag for whichever language you are using append "always", e.g. for Typescript your region tag becomes: ```//#region always```.

Thank you.

**Comment by aeschli** [comment] 2022-02-03 10:45
duplicate of https://github.com/microsoft/vscode/issues/40338

**Closed by aeschli** 2022-02-03 10:45 UTC
