### ISSUE TITLE
Browser integration test time out

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#120225] opened 2021-03-31 06:48 UTC
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=111117&view=logs&jobId=3792f238-f35e-5f82-0dbc-272432d9a0fb&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d. The underlying issue was a test throwing rejecting a promise, see https://github.com/microsoft/vscode/blob/4fd610fc717b1e45c84eb7f4d47c0e00868b02eb/extensions/vscode-api-tests/src/utils.ts#L129-L130

Since the failing promise is awaited the test should have failed and its failure should be printed somewhere

**Comment by bpasero** [comment] 2021-04-05 11:30
Nevermind, this is a general issue with our tests in CI having quite aggressive timeouts (of 7 minutes):

![image](https://user-images.githubusercontent.com/900690/113569607-12ddc180-9613-11eb-973a-5a1d795983da.png)

I think @lszomoru  you recently increased the timeout?

**Comment by lszomoru** [comment] 2021-04-05 12:50
I did increase the test timeout from 7 to 10 minutes as part of an investigation but that change has been reverted. Looking at successful builds I see that our browser integration tests take around 3-4 minutes to complete so I am not sure that we want to bump up that threshold. I would expect (and that was the case last time) that if our integration tests cannot complete in 7 minutes we have a regression in a test.

**Comment by lszomoru** [comment] 2021-04-05 12:53
The integration test timeout was fixed in https://github.com/microsoft/vscode/commit/00c1ca5afcbd2d64a74a1f75d766d668ae001267

**Comment by bpasero** [comment] 2021-04-05 14:48
Hm, maybe this was a wrong assumption from me and the test just timed out because of a test actually not finishing. 

@jrieken does this reproduce locally? I tried to write a test that has such a rejected promise and it was reported correctly.

**Comment by jrieken** [comment] 2021-04-06 06:03
I have only seen this on build machine - the test didn't fail locally which made this impossible for me to investigate. So, likely due to the timeout

**Comment by bpasero** [comment] 2021-04-06 08:27
I locally get the test to fail with:

```
1) vscode API - commands
       getCommands:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

If I do something like `const moveChange = asPromise(notebook.onDidChangeNotebookCells, 1000);` in a commands test that does not deal with notebooks, so I think that is fine.

One thing I noticed while testing this, I can get tests to hang like so:
* have a test with a `done` callback (instead of being `async`)
* never call `done` (e.g. because a promise is awaited on that is rejected)
* the test never completes

I would argue that we should stop using this pattern and always return a promise from a test because this will handle rejected ones as well. However, I do not see this pattern being used for notebooks test and actually we only had 1 usage in API tests that I will take care of.

**Closed** 2021-04-06 08:31 UTC
Labels: integration-test-failure, needs more info

**Comment by jrieken** [comment] 2021-04-06 08:49
> I would argue that we should stop using this pattern and always return a promise from a test because this will handle rejected ones as well. 

Maybe, but I doubt that's the cause here. Sure, `asPromise` uses promises and either you wire that up to `done` correctly or return a promise from your test. Those timeouts, e.g waiting for the an event to happen, should be a normal test exception.

**Comment by bpasero** [comment] 2021-04-06 09:03
@jrieken I looked into this and it turns out we seem to configure a timeout of `60000` for most of our integration tests, e.g. here:

https://github.com/microsoft/vscode/blob/e9166375289c451dd1c1c82cd3fef766857a0c52/extensions/vscode-notebook-tests/src/index.ts#L12-L12

In your case I think we had 7+ tests all waiting for 1min to finish and this caused the build machine to cancel the task entirely. 

I verified that I get a good error when I reduce the timeout to e.g. 5s:

```
    1) timeout
  0 passing (5s)
  1 failing
  1) vscode API - commands
       timeout:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/out/singlefolder-tests/commands.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```
