### ISSUE TITLE
[bug] "cursorWordPart" movement stopped working

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#90570] opened 2020-02-13 07:06 UTC
```
Version: 1.43.0-insider
Commit: f4c95d5b9cfb2265f1730d564df1709533eff55e
Date: 2020-02-12T05:45:29.569Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. try to navigate `deleteWordPartRight` by word part, it wont work
2. try to delete `deleteWordPartRight` by word part, works as expected

**Comment by JacksonKearl** [comment] 2020-02-13 07:27
I am unable to reproduce. Are you triggering these with keybindings? You may have some other application swallowing the bindings, do they work from command pallet?

**Comment by ctf0** [comment] 2020-02-13 08:07
am using keybindings yes, and sadly there is no command pallet 😢

**Comment by ctf0** [comment] 2020-02-13 08:10
i managed to fix it by changing the default keybindings which used to work b4 but not anymore, if u want we can close this ticket unless you need to investigate further.

thanx again.

**Comment by JacksonKearl** [comment] 2020-02-15 01:32
Unable to reproduce with a fresh `--user-data-dir` either. `cursorWordStart*` have different binds than the word-part commands, so I don't think it would be interfering. Probably some issue with the way your `keybindings.json` was configured? Closing for now.

**Closed by JacksonKearl** 2020-02-15 01:32 UTC
