### ISSUE TITLE
1.33.1 Update keeps crashing in windows 10 32 bit

### ISSUE THREAD

**Issue by cedverd** [microsoft/vscode#73096] opened 2019-04-30 18:06 UTC
while opening the terminal it crashes

> Says we are Sorry for the inconvenience!. You Can reopen the window to continue where you left.

I reset my Windows I was using 18362 build and today updates to 18385.1001. 

here is the status of `code --status`

` Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS Version:       Windows_NT ia32 10.0.18885
CPUs:             AMD A4-3330MX APU with Radeon(tm) HD Graphics (2 x 2196)
Memory (System):  2.99GB (0.99GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      disabled_off
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       79    2832  code main
    0       46    3616     gpu-process
    0       64    6828     shared-process

Workspace Stats:
|  Window (Welcome - NODE - Visual Studio Code)
|    Folder (NODE): 0 files
|      File types:
|      Conf files: `
![Screenshot (3)](https://user-images.githubusercontent.com/28141633/56982981-2919b200-6ba0-11e9-9a7f-51145e3df1e4.png)

**Comment by cedverd** [comment] 2019-04-30 18:08
last time i was trying to trying to run a maven project now I was going to setup a node project.

**Comment by bpasero** [comment] 2019-05-01 06:18
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by cedverd** [comment] 2019-05-01 12:22
Can't try now may be a week later

**Comment by cedverd** [comment] 2019-05-01 12:23
right now I'm using 1.32

**Comment by bpasero** [comment] 2019-05-01 13:55
Thanks

**Comment by cedverd** [comment] 2019-05-05 20:35
I tried the insiders vs code but ti was crashing due to terminal

**Comment by bpasero** [comment] 2019-05-06 06:12
@cedverd what does that mean?

**Comment by ChadMcCaffery** [comment] 2019-05-06 16:52
Terminal crashes for me as well. It so happens I had started code from elevated command-line, so got this output after the crash:
```text
[main 2019-05-06T16:43:25.986Z] update#setState idle
[main 2019-05-06T16:43:55.988Z] update#setState checking for updates
[main 2019-05-06T16:43:56.016Z] update#setState idle
Error: async hook stack has become corrupted (actual: 5401, expected: 0)
 1: v8::RetainedObjectInfo::~RetainedObjectInfo
 2: node::InternalCallbackScope::Close
 3: node::RemoveEnvironmentCleanupHook
 4: node::InternalCallbackScope::Close
 5: uv_run
 6: 00007FF65A7C924A
 7: 00007FF65A986610
 8: IsSandboxedProcess
 9: GetHandleVerifier
10: 00007FF65A986610
11: 00007FF65A9D2963
12: 00007FF65A9D2B5C
13: 00007FF65A9D2D35
14: 00007FF65A9D33B8
15: 00007FF65A9984F9
16: GetHandleVerifier
17: IsSandboxedProcess
18: IsSandboxedProcess
19: IsSandboxedProcess
20: GetHandleVerifier
21: 00007FF65A7C3C27
22: IsSandboxedProcess
23: BaseThreadInitThunk
24: RtlUserThreadStart
[main 2019-05-06T16:46:23.880Z] [VS Code]: render process crashed!
```
After clicking __Reopen__ button, `code.exe --status` reports:
```text
Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS Version:       Windows_NT x64 10.0.14393
CPUs:             Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)
Memory (System):  15.91GB (7.94GB free)
VM:               0%
Screen Reader:    no
Process Argv:     cess
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
22: IsSandboxedProcess
CPU %aseMem MBIn   PIDk Process
    0tlU    78ea 18324  code main
    0 20   14206  6112:2   gpu-processde]: render process crashed!
    0       77   16744     shared-process
    0      167   17856     window (ExternalCommandProxies.ps1 - Packaging - Visual Studio Code [Administrator])
    0       11    7892       watcherService
    0       10   11304         console-window-host (Windows internal process)
    0        6   13736       winpty-process
    0        9    7740         console-window-host (Windows internal process)
    0      198   18332         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& 'C:\Users\chadm\.vscode\extensions\ms-vscode.powershell-1.12.1\modules\PowerShellEditorServices\Start-EditorServices.ps1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\chadm\.vscode\extensions\ms-vscode.powershell-1.12.1\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\chadm\.vscode\extensions\ms-vscode.powershell-1.12.1\logs\1557161189-3052ca7c-9b71-4eb2-ae23-7e5501e521571557161185787\EditorServices.log' -SessionDetailsPath 'C:\Users\chadm\.vscode\extensions\ms-vscode.powershell-1.12.1\sessions\PSES-VSCode-18324-365556' -FeatureFlags @()"
    0       73   17584       extensionHost
    0       39   17640         electron_node server.js

Workspace Stats:
|  Window (ExternalCommandProxies.ps1 - Packaging - Visual Studio Code [Administrator])
|    Folder (Packaging): 108 files
|      File types: ps1(73) md(14) xml(5) psm1(4) dll(4) psd1(2) json(1) cmd(1)
|                  gitignore(1) config(1)
|      Conf files:
```

**Comment by bpasero** [comment] 2019-05-07 05:41
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by ChadMcCaffery** [comment] 2019-05-08 17:15
### Code/Extension logs: [code-logs.zip](https://github.com/microsoft/vscode/files/3158547/code-logs.zip)
### Console Dump
```
Error: async hook stack has become corrupted (actual: 26591, expected: 0)
 1: 00007FF7DA8C1A6F
 2: 00007FF7D955FFA5
 3: 00007FF7DA8BDD3E
 4: 00007FF7DA8BDBDD
 5: 00007FF7D9557091
 6: 00007FF7D9557495
 7: 00007FF7DA8BA985
 8: 00007FF7DA9A8E63
 9: 00007FF7D9581D50
10: 00007FF7D957E4FD
11: 00007FF7D8B88824
12: 00007FF7D8BF4A86
13: 00007FF7D8B88824
14: 00007FF7D8BB2277
15: 00007FF7D8BB27E8
16: 00007FF7D8BB3399
17: 00007FF7D8BCF7B1
18: 00007FF7D952A9EB
19: 00007FF7D8B6C4E4
20: 00007FF7D9108586
21: 00007FF7D8B6BC41
22: 00007FF7D72B13B8
23: 00007FF7DB8D40A2
24: 00007FFE595784D4
25: 00007FFE5B7BE851
[main 2019-05-08T16:58:53.750Z] [VS Code]: render process crashed!
```
### Post-crash status
```
Version:          Code - Exploration 1.34.0-exploration (9a6e4a4980895ef245ae7d69274b8a9acdf6f662, 2019-05-07T06:04:09.245Z)
OS Version:       Windows_NT x64 10.0.14393
CPUs:             Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)
Memory (System):  15.91GB (8.48GB free)
VM:               0%
Screen Reader:    no
Process Argv:     E:\repo\Zeppelin\ReleaseBranchScripts
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       98   14332  code-exploration main
    0      129   10648     window (Packaging - Visual Studio Code - Exploration)
    0       11   12348       watcherService
    0       10    7612         console-window-host (Windows internal process)
    0       75   15040       extensionHost
    0      148   12148     window (Update-PackagesConfigVersions.ps1 - ReleaseBranchScripts - Visual Studio Code - Exploration)
    0        6    4352       winpty-process
    0        8    3896         console-window-host (Windows internal process)
    0      163    5840         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass 
                                 -Command "& 'C:\Users\chadm\.vscode-exploration\extensions\ms-vscode.powershell-1.12.1\modules\PowerShellEditorServices\Start-EditorServices.ps1' 
                                 -HostName 'Visual Studio Code Host' 
                                 -HostProfileId 'Microsoft.VSCode' 
                                 -HostVersion '1.12.1' 
                                 -AdditionalModules @('PowerShellEditorServices.VSCode') 
                                 -BundledModulesPath 'C:\Users\chadm\.vscode-exploration\extensions\ms-vscode.powershell-1.12.1\modules' 
                                 -EnableConsoleRepl 
                                 -LogLevel 'Verbose' 
                                 -LogPath 'C:\Users\chadm\.vscode-exploration\extensions\ms-vscode.powershell-1.12.1\logs\1557332871-53f8deb0-5385-4255-88cf-0ffcf0a1ddec1557332868403\EditorServices.log' 
                                 -SessionDetailsPath 'C:\Users\chadm\.vscode-exploration\extensions\ms-vscode.powershell-1.12.1\sessions\PSES-VSCode-14332-272710'
                                 -FeatureFlags @()"
    0        6    4956       winpty-process
    0       95   16980         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        9   18388         console-window-host (Windows internal process)
    0       11    8656       watcherService
    0       10   16864         console-window-host (Windows internal process)
    0       79    9668       extensionHost
    0       13   12976     electron-crash-reporter
    0      111   16044     gpu-process
    0       70   18064     shared-process

Workspace Stats:
|  Window (Update-PackagesConfigVersions.ps1 - ReleaseBranchScripts - Visual Studio Code - Exploration)
|  Window (Packaging - Visual Studio Code - Exploration)
|    Folder (ReleaseBranchScripts): 27 files
|      File types: ps1(15) psm1(11) psd1(1)
|      Conf files:
|    Folder (Packaging): 154 files
|      File types: ps1(107) md(14) xml(7) psm1(6) dll(6) psd1(3) nupkg(3)
|                  nuspec(2) json(2) yaml(1)
|      Conf files: settings.json(1)
```

**Comment by cedverd** [comment] 2019-05-09 10:25
> @cedverd what does that mean?

As you asked I tried the insider vs code[ visual Studio Code] build 1.34 but it was also crashing. while I was opening the the terminal I will update the `code -status later`

**Comment by DanTup** [comment] 2019-05-09 16:05
@bpasero is there somewhere to get more info on the crash (or have VS Code write more info)? I see it happen a lot lately when running tests on AppVeyor.. I see this in the output:

```
[main 2019-05-09T12:00:31.608Z] [VS Code]: render process crashed!
```

Then nothing happens until the test run times out. I know AppVeyor isn't a supported use case, but it'd be good to understand the failure - it's possible it's not AppVeyor-specific (it does work a lot of the time) - and we do really need to be able to run tests for extensions on Windows somehow.

If there's crash data being written to a folder somewhere, I can make sure it's uploaded at the end of the run.

**Comment by bpasero** [comment] 2019-05-09 16:20
We have https://github.com/microsoft/vscode/wiki/Native-Crash-Issues that documents how to read native crashes.

**Comment by DanTup** [comment] 2019-05-09 16:23
Ah thanks - that doesn't look like something I could automate in an AppVeyor build though. Hopefully it's the same issue someone is seeing directly and it can be tracked down that way. Thanks!

**Comment by ChadMcCaffery** [comment] 2019-05-09 18:51
@bpasero, Here you go: [DebugDiag-Logs.zip](https://github.com/microsoft/vscode/files/3163556/DebugDiag-Logs.zip)

**Comment by karolz-ms** [comment] 2019-05-09 21:52
Just FYI I was experiencing the same problem (attempt to launch terminal crashes VS Code), probably after installing latest Windows update (not sure). What solved it for me was
1. Uninstall VSCode
1. Install VSCode portable
1. Move extensions and user data to vscode portable location
HTH!

**Comment by bpasero** [comment] 2019-05-10 05:17
Since everyone here talks about the terminal, moving to @Tyriar

**Comment by Tyriar** [comment] 2019-05-10 17:43
Install the 64-bit version of VS Code as you're on 64-bit Windows. It's fixed in the upcoming version but you should use the 64-bit version to avoid weirdness like this.

/duplicate https://github.com/microsoft/vscode/issues/72190

**Closed by Tyriar** 2019-05-10 17:43 UTC
Labels: electron, freeze-slow-crash, needs more info, upstream, windows

**Comment by ChadMcCaffery** [comment] 2019-05-10 17:59
@tyriar: Title is misleading in my case, because I always use 64-bit Code on my 64-bit OS.

**Comment by Tyriar** [comment] 2019-05-10 18:10
@ChadMcCaffery could you create a separate issue? I suspect most people here are using ConPTY on 32-bit VS Code/64-bit Windows, but ConPTY is not available in your version of Windows.
