### ISSUE TITLE
Under conpty, shell integration decorations can be incorrectly positioned

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#153476] opened 2022-06-28 13:28 UTC
Testing #153365

1. Open microsoft/vscode
2. Start the default VS Code build task
3. Make some errors
4. The problem decorations are one line too high:

![image](https://user-images.githubusercontent.com/38270282/176190584-7ea33dc2-dd95-47b3-b548-7247ccfcebae.png)

---

Update from @Tyriar: This tracks the common set of issues that come from conpty doing its own "rendering" and not guaranteeing the position of the shell integration sequences. Upstream issue: https://github.com/microsoft/terminal/issues/8698

**Comment by meganrogge** [comment] 2022-06-28 16:08
on windows?

**Comment by Tyriar** [comment] 2022-06-28 16:09
Yep that's Windows, this was by designed to put it on the beginsPattern right?

**Comment by alexr00** [comment] 2022-06-29 08:43
Yes, it's Windows.

**Comment by Tyriar** [comment] 2022-06-29 10:22
This seems to be working for me:

![image](https://user-images.githubusercontent.com/2193314/176413870-d2d9b6dd-ab17-455c-874d-ccf75fca7d98.png)

I did see some weird behavior when resizing the width of the terminal earlier, that's probably too risky to fix this late in endgame.

**Comment by Tyriar** [comment] 2022-08-03 11:18
More info on this: When conpty supports "passthrough" of the OSC 133/633 sequences this should be fixed. Currently we have a bunch of heuristics that try to fix up incorrectly places sequences as the position isn't guaranteed to be correct since they are not output during the render phase. Upstream issue: https://github.com/microsoft/terminal/issues/8698

**Comment by Tyriar** [comment] 2023-12-05 20:23
Closing this as out of scope as this will eventually get fixed in later versions if Windows and it's fairly low impact.

**Closed by Tyriar** 2023-12-05 20:23 UTC
Labels: bug, upstream, windows, terminal-conpty, upstream-issue-linked, terminal-shell-integration, terminal-shell-pwsh
