### ISSUE TITLE
text pointer and links underline blinking at the same time

### ISSUE THREAD

**Issue by Sillum** [microsoft/vscode#80231] opened 2019-09-02 19:27 UTC
Issue Type: <b>Bug</b>

#1 open 2 new file
#2 write to a file 2 link one to the first line a link then to the second line the same like that:
(first row)    
[Untitled-1.txt](https://github.com/microsoft/vscode/files/3566979/Untitled-1.txt)

[Untitled-1.txt](https://github.com/microsoft/vscode/files/3566980/Untitled-1.txt)

1   | https://www.google.com/
(second row) 2 | https://www.google.com/
#3 then set the text pointe to the first row (to anywhere here only is the first rov the important)
#4 go to the another new file 
#5 then go back
#the underline on the link in the second row start blinking in the same tempo as the text cursor
(the files are unseved whit no file extension but this also works whit .txt files when the .txt file is not saved or had changes)

[ sorry for the broken engrish i now learning the language :) ]

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (4.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-picture|Jak|1.0.0
tag-inserter|l7s|1.4.0
python|ms-|2019.8.30787
cpptools|ms-|0.25.1
csharp|ms-|1.21.1
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.9.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
html-snippets|wge|0.1.5

(3 theme extensions excluded)

**Comment by usernamehw** [comment] 2019-09-02 20:58
Duplicate of #76642

**Closed** 2019-09-10 12:23 UTC
Labels: *duplicate, electron, gpu, upstream
