### ISSUE TITLE
User Snippets not working on Insiders edition

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#57034] opened 2018-08-22 17:44 UTC
Issue Type: <b>Bug</b>

I have the following code set up on my html.json file.

```
"My Form":{
	"prefix": "myform",
	"body": [
		"<form name=$name method=$method action=$action>",
		"</form>"
	],
	"description": "Start an input tag"
}
```

What happened in the standard build of VSCode was I would type myform and hit enter and the form tag would pre-populate and the cursor would highlight  on $name to allow me to enter the name of the field.  Hitting TAB would pass to $method and then to $action.

When I enter myform in VSCode - Insiders, I get the following:

```
<form name= method= action=>
</form>
```

I don't get the '$' variables that are set up in the code to trigger cursor highlights.

VS Code version: Code - Insiders 1.27.0-insider (07796186d388044595cd101c49378c7cd48b350b, 2018-08-21T08:48:57.835Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.73GB (7.04GB free)|
|Process Argv|C:\Users\Brandon.Rice.AD\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.6.1
php-intellisense|fel|2.3.4
auto-close-tag|for|0.5.6
beautify|Hoo|1.3.2
classic-asp-html|jtj|0.1.0
vs-color-picker|lih|0.7.0
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.3
vscode-icons|rob|7.25.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-08-23 07:38
Works for me... Anything you have different then I have? Special settings?

![aug-23-2018 09-37-51](https://user-images.githubusercontent.com/1794099/44511566-46fd5180-a6b8-11e8-9c8f-b2825f2c943f.gif)

**Comment by jrieken** [comment] 2018-08-23 07:40
On an unrelated note, the `$name` syntax isn't actually correct and `${1:name}` should be used for placeholders. The `$name` syntax is referring to variables and we make it work by implementing a fallback for 'unresolved' variables, turning them into placeholders

**Comment by BrandonRice** [comment] 2018-08-23 12:40
jrieken - Are you using the Insiders build?  I don't have any special settings.  I installed the Insiders build and copied my personalized user snippets over from the stable release of VSCode.  They work fine there but not in the Insiders build.  I'll try it again this morning and see if I get any better result.

**Comment by BrandonRice** [comment] 2018-08-23 12:42
Seems to be working today.  Guess I just needed to do the fix all, restart Windows! :)

**Comment by jrieken** [comment] 2018-08-23 13:50
Funky... Closing as not reproducible but please speak up you see this again

**Closed** 2018-08-23 13:50 UTC
Labels: *not-reproducible, needs more info, snippets
