### ISSUE TITLE
use language server for onEnterRules

### ISSUE THREAD

**Issue by kyle-rb** [Microsoft/vscode#57968] opened 2018-09-05 16:04 UTC
Issue Type: <b>Bug</b>

1. Create a pair of opening and closing tags, e.g. `<div></div>`
2. Type some text in between those tags, with part of it embedded in another tag, e.g. `<div>some <em>text</em> here</div>`
3. With the cursor just before the outer closing tag (in this case `</div>`), press enter
4. A newline is created normally, with the closing tag indented to the same level as the opening tag

The expected behavior is for the closing tag to be indented two lines, and for the cursor to be in the line between the opening and closing tags, indented a level past them. This can be observed when the same steps are followed, except no additional tag is embedded in step 2, just normal text.

Note: this issue occurs commonly for me when using Emmet to type nested lists (many `<li>` and `<ul>` tags).

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 16.7.0

**Comment by aeschli** [comment] 2018-09-12 10:13
I see what you mean. You want auto-indentation to work with more content on the line
The problem is that the auto-indentation feature is based on a regular expressions that matches at the text just before the cursor. It's difficult (impossible?) to write a regular expression that also handles text in between containing closed tags.

The solution would probably be to use the language server for auto indentation.

**Comment by aeschli** [comment] 2019-01-08 16:50
duplicate of #63097

**Closed by aeschli** 2019-01-08 16:50 UTC
Labels: editor-autoindent, feature-request
