### ISSUE TITLE
Did you run npm install?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64381] opened 2018-12-04 21:14 UTC
- Clone a new repo
- Open in vscode
- Tasks output panel pops up and says `Running gulp --tasks-simple didn't list any tasks. Did you run npm install?`
- I didn't but I was just about to! Get off my back! 😁 

This doesn't happen in stable, can this be less aggressive? Does it absolutely need to detect tasks when I haven't asked it to run a task yet?

**Comment by alexr00** [comment] 2018-12-05 10:31
We now detect tasks earlier because of automatic tasks. Based on this and other feedback we should not show anything in the output for automatic task issues!

**Comment by roblourens** [comment] 2018-12-05 17:10
This repo didn't have automatic tasks, this is the tasks.json: https://github.com/Microsoft/vscode-edge-debug/blob/master/.vscode/tasks.json#L1:L21

**Comment by roblourens** [comment] 2018-12-05 17:12
Pretty sure this is the repo where I saw it at least

**Comment by alexr00** [comment] 2018-12-12 09:39
Ended up being a duplicate of #64040

**Closed by alexr00** 2018-12-12 09:39 UTC
Labels: feature-request, tasks
