### ISSUE TITLE
Recents not showing in task bar on windows 10

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#3473] opened 2016-02-25 20:49 UTC
This is all I see when right clicking on the task bar icon.
![untitled](https://cloud.githubusercontent.com/assets/1727302/13333908/31b2e5d0-dc01-11e5-993a-ea99da05dd9d.png)

**Comment by bpasero** [comment] 2016-02-29 10:28
@pflannery which version of Code is this?

**Comment by pflannery** [comment] 2016-02-29 13:22
@bpasero 0.10.8

**Comment by bpasero** [comment] 2016-03-01 11:18
Likely an issue with Electron...

**Comment by bpasero** [comment] 2016-04-03 09:11
Duplicate of https://github.com/Microsoft/vscode/issues/241

**Closed by bpasero** 2016-04-03 09:11 UTC
Labels: bug, upstream
