### ISSUE TITLE
when enter comma or '.', cause wrong code completion.

### ISSUE THREAD

**Issue by liangpure** [Microsoft/vscode#55581] opened 2018-08-01 14:38 UTC
- VSCode Version:1.25.1
- OS Version: win7/win10

Steps to Reproduce:

1.  coding  `arr.reduce((a,))`  
2.  when I tap ',' cause code completion,editor show 
    `arr.reduce((addEventListener,))`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment] 2018-08-03 08:46
This is pretty weird, why would TypeScript propose `addEventListener` at a parameter name position...

**Comment by akukolu** [comment] 2018-08-07 05:53
Seems to be the same issue as https://github.com/Microsoft/vscode/issues/47696

Setting `editor.acceptSuggestionOnCommitCharacter` to false worked for me.

**Comment by mjbvz** [comment] 2018-08-07 20:42
Duplicate of #54386

**Closed by mjbvz** 2018-08-07 20:42 UTC
Labels: editor, typescript
