### ISSUE TITLE
Fold .ts .js and .js.map files into a single unit

### ISSUE THREAD

**Issue by pratik229** [Microsoft/vscode#16564] opened 2016-12-06 03:58 UTC
Similar feature is available IntelliJ where in the .ts .js and .js.map files are folded into a single unit and only .tx file available to edit by default. A user can still view .js and .js.map files if required by unfolding the unit. Currently I found a way to hide .js and .js.map files by ignoring them through settings, but having the ability to fold would be more beneficial to a developer.

**Comment by aluanhaddad** [comment] 2016-12-07 08:09
Please add support for this. Currently I am using the same workaround as @pratik229 to hide these files but it is far from ideal. I would say what would be ideal is actually something along the lines of @MadsKristensen's exceptional [File Nesting plugin for Visual Studio](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileNesting). I would very much like to be able to have nesting like

```
a.ts
--a.js
----a.js.map
--a.html
--a.css
----a.css.map
```
Thank you for VS Code, it is awesome!

**Comment by mjbvz** [comment] 2016-12-07 19:42
Closing as a duplicate of #6328

**Closed by mjbvz** 2016-12-07 19:42 UTC
Labels: duplicate, explorer-files, feature-request

**Comment by gs-rpal** [comment] 2017-08-14 07:29
It does not work for VS Code
