### ISSUE TITLE
VSCode Icons look gross when launching it from Terminal

### ISSUE THREAD

**Issue by cansi** [Microsoft/vscode#28421] opened 2017-06-10 13:36 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.1.0 (macOS Sierra 10.12.1)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|lorem-ipsum|Tyriar|1.0.0|
|csharp|ms-vscode|1.10.0|
|live-server-preview|negokaz|0.0.4|
|java|redhat|0.5.0|
|sass-indented|robinbentley|1.4.1|;

---

Steps to Reproduce:

1. In Terminal, type the command `code path/to/folder` 

<img width="82" alt="schermata 2017-06-10 alle 15 30 57" src="https://user-images.githubusercontent.com/11475254/27003158-e5530c4c-4df1-11e7-94ce-65c1df28b727.png">
<img width="123" alt="schermata 2017-06-10 alle 15 31 13" src="https://user-images.githubusercontent.com/11475254/27003160-e5763582-4df1-11e7-9fe1-934cd9ae68b9.png">
<img width="95" alt="schermata 2017-06-10 alle 15 31 26" src="https://user-images.githubusercontent.com/11475254/27003159-e570c37c-4df1-11e7-8a00-889d889e6d9d.png">

**Comment by Leoxdnardo** [comment] 2017-06-10 14:16
same here

**Comment by serge-io** [comment] 2017-06-10 14:46
same goes for **OS Sierra 10.12.5**
when opening folder with = **code .** from the terminal

**Comment by lanzenotter** [comment] 2017-06-10 17:41
after Update i get the same issue. No Commandlineoption help´s.

**Comment by Ghosty141** [comment] 2017-06-11 02:48
I don't have the issue. I used "code /PATH/" and it started without any issues. (Hackintosh) Sierra 10.12.4, VS Code Version 1.13.0

**Comment by krokofant** [comment] 2017-06-11 19:19
😆 What the hell caused this. My eyes hurt!

![image](https://user-images.githubusercontent.com/5908498/27013815-8c7b463e-4eeb-11e7-85dc-19e5244a1145.png)

**Comment by burknator** [comment] 2017-06-12 10:57
Same here, on macOS 10.12.5 and Code 1.13.0.

But after opening the explorer view by clicking on it's icon, everything is fine for a short time. I can't quite make out when or why is switches back to the blurry icons.

**Comment by ramya-rao-a** [comment] 2017-06-12 17:15
Thanks @burknator, Closing as duplicate of #28345

cc @bpasero

**Closed by ramya-rao-a** 2017-06-12 17:15 UTC
Labels: new release
