### ISSUE TITLE
Add debug configuration button defunct

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16659] opened 2016-12-06 14:07 UTC
* enable `editor.formatOnSave`
* enable `files.autoSave: onFocusChange`
* have the launch.json below
* press add config button
* select nodejs launch
* 🐛 nothing happens

![dec-06-2016 15-05-50](https://cloud.githubusercontent.com/assets/1794099/20928325/a6582234-bbc5-11e6-80b0-6aeeb1e6f1d6.gif)

```json
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

**Comment by isidorn** [comment] 2016-12-07 09:47
Works for me. Can you constantly reproduce it?
I believe I am doing exactly the same as you with the launch.json you attached ->

![addconfiguration](https://cloud.githubusercontent.com/assets/1926584/20962641/6d6bd11e-bc6a-11e6-8fa0-3bd6f8c4cd94.gif)

**Comment by jrieken** [comment] 2016-12-07 10:31
Yes, I can
![dec-07-2016 11-30-34](https://cloud.githubusercontent.com/assets/1794099/20964147/a1346910-bc70-11e6-949f-2068897e585e.gif)

**Comment by isidorn** [comment] 2016-12-07 11:09
@jrieken skipping the add configuration, if you manually trigger a snippet with suggest and choose a suggestion it works fine?
Do you get this behavior all the time and if you choose any configuration option or only for Nodejs Launch Configratuion?
This is on mac?

**Comment by isidorn** [comment] 2016-12-08 09:35
After investigating with @jrieken the issue is that he has auto save on focus lost and format on save.
The problem surfaces because clicking on a suggest widget workbench treats as a focus lost event.

So forwading to @bpasero as onFocusLost event should only be triggered when the whole editor widget lost focus, not when text lost focus.

Easy repro -> 
1. Have auto save on focus lost
2. Have file dirty
3. Open find widget -> file is saved. Should not be

**Comment by jrieken** [comment] 2017-01-27 13:57
still happens: 
![jan-27-2017 14-56-34](https://cloud.githubusercontent.com/assets/1794099/22373158/d7172ab0-e4a0-11e6-9757-5cb6276a911b.gif)

**Comment by isidorn** [comment] 2017-01-27 14:04
Pushing it to february since it only happens with format on save, save on focus lost and mouse click

**Comment by bpasero** [comment] 2017-02-23 13:20
Fixed via https://github.com/Microsoft/vscode/issues/21273

**Closed by bpasero** 2017-02-23 13:20 UTC
Labels: bug, workbench
