### ISSUE TITLE
Add option config.forcePullTags

### ISSUE THREAD

**Issue by Fabian1976** [microsoft/vscode#129404] opened 2021-07-26 13:34 UTC
I'm seeing messages like this on our repos when syncing with vscode:
```
$ git pull --tags origin main                                                                                                                      on  main↓3|
From ssh.dev.azure.com:v3/<REDACTED>
 * branch            main       -> FETCH_HEAD
 ! [rejected]        latest     -> latest  (would clobber existing tag)
```

I've searched the issues and everyone seems to think that the "solution" is to disable the pulling of tags. That seems more of a temporary work-around to me. I want/need the tags to pull. Now i could do it manually and add a `--force` to the pull command, but it would be nicer to have a configuration parameter that would do that for me.

Especially when the `latest` tag is becoming more common.

Are the steps similar to this [PR](https://github.com/microsoft/vscode/pull/67527/files)?

**Comment by trigunam** [comment] 2021-07-28 02:34
@Fabian1976 I am looking for this feature as well, thanks for creating the issue.
When I looked at PR, `--force` option is not present for the `git pull --tags` command. Looks like a new line of code or configuration needs to be added.

**Comment by digitarald** [comment] 2021-11-24 19:05
I ran into the same issue and had used `git pull` for months to work around it.

The solution is provided by https://stackoverflow.com/questions/58031165/how-to-get-rid-of-would-clobber-existing-tag has 🔥 300 votes on the question and 🔥 700 votes on the top answer. If it would be tagged `visual-studio-code` it would be it would make it one of the most upvoted issues.

To avoid that users see the error and have to find the option to force pull tags, could the error be detected and provide an option to force pull tags? Wdyt, @lszomoru?

**Comment by lszomoru** [comment] 2023-12-14 12:58
Duplicate of https://github.com/microsoft/vscode/issues/160822

**Closed by lszomoru** 2023-12-14 12:58 UTC
Labels: feature-request, git
