### ISSUE TITLE
Make it possible to inactivate folders within a workspace

### ISSUE THREAD

**Issue by mojoaxel** [microsoft/vscode#98421] opened 2020-05-23 09:01 UTC
I like the idea of workspaces where you can work on multible projects/libraries/folders within a given  context. 💓

**The idea:**

_Mark folders within a workspace "inactive" or "active"._ ☑️

**Description**

If a folder in a workspace was marked "inactive":
- It is closed/collapsed and can not be reopend untill marked "active" again.
- It is excluded from the global search
- Changes are not shown in the source-control panel

**Why?**

I often work on a project that consist of multible libraries. These libraries belong to the same "project" and I like them in one place/workspace. But it happens often that a search returns files from a sub-library that I'm not currently interested in (I know I can tweak the search but this again is work, I don't want to do every time). Also the source control gets easily cluttered with git infos I'm not interested in. And why vscode is still missing a task-focused-ui-plugin I would like a way to reduce (the always growing) amount of "noise" in the workspace. ⁉️

**Work around / current state**

At the moment I remove folders from the workspace and than add them again if I need to work on them again. This makes the whole concept of a workspace useless. 💔

**Comment by nickcoad** [comment] 2020-05-23 09:19
You can already do this - in settings you have the option to provide globs for files/paths to exclude from the file manager, you can set this on a workspace or a user level.

**Comment by mojoaxel** [comment] 2020-05-23 09:48
> You can already do this - in settings you have the option to provide globs for files/paths to exclude from the file manager, you can set this on a workspace or a user level.

@nickcoad Thanks for your answer but I don't think you got my point. I know that I can remove/hide files from a workspace, there are in fact multible ways of doing this. I'm looking for a fast and easy way of excluding and including them again without removing/hiding them completely.

Here is an example how [mylyn](https://www.eclipse.org/mylyn/) in eclipse does something similar:
![image](https://user-images.githubusercontent.com/600565/82727482-1b732500-9ceb-11ea-8456-70e6113189ba.png)

**Comment by isidorn** [comment] 2020-05-26 09:41
You basically working sets, thus duplicate of https://github.com/microsoft/vscode/issues/9498

**Closed by isidorn** 2020-05-26 09:41 UTC

**Comment by mojoaxel** [comment] 2020-05-26 10:21
@isidorn While #9498 might be similar i8t focuses only on open files in the editor. I propose to also exclude folders/project from search and source-control.

So this issue proposes a "working-set" for complete folders and not only opened files.

**Comment by isidorn** [comment] 2020-05-26 10:27
Should be covered by this idea https://github.com/microsoft/vscode/pull/87666

**Comment by mojoaxel** [comment] 2020-05-26 12:37
> Should be covered by this idea #87666

Yes! Thank you for pointing me to this!
