### ISSUE TITLE
vscode.workspace.textDocuments call does not return hidden previewHtml documents 

### ISSUE THREAD

**Issue by Raymondd** [Microsoft/vscode#20075] opened 2017-02-06 19:43 UTC
- VSCode Version: 1.9.0
- OS Version: Win10 and MacOS

Steps to Reproduce:
**Configuration to connect to SQL from the extension**
Reference: https://github.com/Microsoft/vscode/issues/19732 

**Repro steps - execute 2 separate queries**
Highlight the text `select * from sys.databases` and execute `MS SQL: Execute Query` (Ctrl+Shift+E) to run
You will notice the results editor tab opens, which is a WebView component.
![1](https://cloud.githubusercontent.com/assets/3318689/22663003/dec75a52-ec5f-11e6-8a25-0113d860230f.PNG)

Hide this webview behind the .sql document you just created:
![2](https://cloud.githubusercontent.com/assets/3318689/22663023/ef0e5fc8-ec5f-11e6-821a-6f83151ce2b1.PNG)

Highlight the text` select * from sys.tables` and execute the MS SQL: Execute Query

Expected:
The results editor tab is found, brought to the foreground, and refreshed. 

Actual:
The results editor tab is not found and not refreshed. A new results tab with the same URI is opened in the second pane. 
![3](https://cloud.githubusercontent.com/assets/3318689/22663301/f5905ad0-ec60-11e6-8468-d5cb09587225.PNG)

Note that, if you have the results tab in the foreground, it is always found and refreshed properly. 
The reason this is not happening is because this slice of code tells us if there is one already open or not: 

```
    public doesResultPaneExist(resultsUri: string): boolean {
        let resultPaneURIMatch = vscode.workspace.textDocuments.find(tDoc => tDoc.uri.toString() === resultsUri);
        return (resultPaneURIMatch !== undefined);
    }
```
`vscode.workspace.textDocuments` contains all text documents, regardless of if they are visible or not, but it does not contain all previewHtml documents. It only contains the previewHtml documents that are visible. (In other words, any previewHtml documents which are not visible are not found in `vscode.workspace.textDocuments` which is inconsistent with other types of text documents)

**Comment by mjbvz** [comment] 2017-02-07 21:28
@bpasero can you please take a look. 

This issue also effects the markdown preview (see issues like #8581). When I looked through the implementation in VSCode, I believe the current behavior may have been by design but perhaps we need a way to return all documents include html previews.

**Comment by jrieken** [comment] 2017-02-09 17:25
Closing this as dupe of https://github.com/Microsoft/vscode/issues/15178 which is about knowing what tabs (tab != editors != documents) are open. Ultimately we should migrate folks from the dark side and enable actual UX extensions

**Closed by jrieken** 2017-02-09 17:25 UTC
Labels: api, workbench

**Comment by Raymondd** [comment] 2017-02-09 18:23
If this is the case, is there anyway to determine which tabs are open?
