### ISSUE TITLE
Snippets with prefix with no alpha-nunmeric character have inconsistent behavior

### ISSUE THREAD

**Issue by jlelong** [Microsoft/vscode#64818] opened 2018-12-11 19:15 UTC
Consider the following snippets (they are related to LaTeX but can be tested with plain text document)

```
"subscript": {
	"prefix": "__",
	"body": "_{$0}",
	"description": "Add a subscript"
},
"superscript": {
	"prefix": "**",
	"body": "^{$0}",
	"description": "Add a superscript"
},
"alpha": {
	"prefix": "@a",
	"body": "\\alpha",
	"description": "Insert alpha"
},
"partial": {
	"prefix": "@6",
	"body": "\\partial",
	"description": "Insert partial derivative symbol"
}
```

The prefix `__` does automatically trigger intellisense but `**` does not. For `**`, I have to manually trigger suggestions. Hitting `TAB` directly after `**`, without manually triggering suggestions just inserts some spaces.

Then, trying to complete `b__` and `b**` leads to different behaviors
<img width="164" alt="capture d ecran 2018-12-11 a 18 00 08" src="https://user-images.githubusercontent.com/2910140/49819676-57742d80-fd76-11e8-962e-ac2c18f9b913.png">
<img width="135" alt="capture d ecran 2018-12-11 a 18 00 20" src="https://user-images.githubusercontent.com/2910140/49823691-96a77c00-fd80-11e8-9c52-72777fb5f6a5.png">

Similarly, The prefix `@a` triggers intellisense but `@6`requires manual triggering to show the suggestion menu. However, hitting `TAB` after `@6` expands it even no suggestion shows up. This is not coherent with the behavior for `**`.

- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2018-12-12 08:17
/duplicate of https://github.com/Microsoft/vscode/issues/62906#issuecomment-440582118

**Closed** 2018-12-12 08:18 UTC
Labels: *duplicate, suggest

**Comment by jlelong** [comment] 2018-12-12 08:39
@jrieken While googling I  had come across [#62906](https://github.com/Microsoft/vscode/issues/62906#issuecomment-440582118), which only explains why `**` does not automatically trigger 24x7 intellisense. Does this also mean that `@6` is not considered an end of word whereas `@a` is?

Moreover it does not explain why trying to complete `b__` and `b**` leads to different behaviors
<img width="164" alt="capture d ecran 2018-12-11 a 18 00 08" src="https://user-images.githubusercontent.com/2910140/49819676-57742d80-fd76-11e8-962e-ac2c18f9b913.png">
<img width="135" alt="capture d ecran 2018-12-11 a 18 00 20" src="https://user-images.githubusercontent.com/2910140/49823691-96a77c00-fd80-11e8-9c52-72777fb5f6a5.png">
Note that in both screenshots, intellisense was triggered manually. This is actually the most annoying problem in my issue and it used to work.

**Comment by jrieken** [comment] 2018-12-12 09:12
Each language defines what a word is - so it depends on that. We have this restriction because we don't want IntelliSense to constantly pop up.

**Comment by Astrantia** [comment] 2018-12-12 09:13
@jrieken Can you point to the documentation about how to define words in languages?

**Comment by jrieken** [comment] 2018-12-12 09:14
there you go: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages
