### ISSUE TITLE
Removing breakpoint removes two breakpoints

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#38099] opened 2017-11-11 01:40 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T06:19:28.857Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: none
---

Steps to Reproduce:

1. Create a file `a.js` containing:
```js
0;
1;
2;
```
2. Put a breakpoint on each line.
3. Delete the breakpoint next to `0;`.
    Two breakpoints are removed!
4. Try to delete the remaining breakpoint next to `2;`.
    Nothing happens...

**Comment by eamodio** [comment] 2017-11-11 04:53
Assuming this is a Duplicate of https://github.com/Microsoft/vscode/issues/37880

**Comment by weinand** [comment] 2017-11-11 09:49
yes, duplicate of #37880

**Closed by weinand** 2017-11-11 09:49 UTC
Labels: debug, insiders
