### ISSUE TITLE
Feedback form "how we're doing". Incorrect character count when newline present

### ISSUE THREAD

**Issue by beyondcompute** [Microsoft/vscode#2662] opened 2016-02-03 10:09 UTC
To reproduce.
* click smiley in the bottom right of editor window. The feedback form should appear
* enter several characters, press "Enter" (the new line should appear)
* continue entering characters while you can
You should stop at "1 character**s** left" (declensions?) After that you will not be able to enter anything

On the screenshot. There's a newline after "1". I reached the end of input and unable to enter more characters. But counter still says _"1 characters left"_:
<img width="468" alt="" src="https://cloud.githubusercontent.com/assets/248055/12779043/94bbf6d4-ca6e-11e5-9c03-92c9ec641218.png">

_Mac OS 10.10.5 Yosemite_

**Comment by waderyan** [comment] 2016-02-15 22:59
This is interesting. I created this [fiddle](https://jsfiddle.net/wadeanderson7/1pv9xd71/) to reproduce the behavior. 

@egamma do you have any thoughts on this? Here are a couple ideas we've talked about before. 

1 - Remove the text area completely and replace with just the tweet button. This makes sense because we're submitting to twitter anyways. 
2 - Hack the text area element to get better behavior. This would involve looking for new line characters based on the batter described by OP. I'm not a fan of this as it seems error prone. 

If we go with option 1, I'll work with Brad and get some design love on the form. 

@beyondcompute any thoughts? 

I created PR #3033 to fix the "s" on singular count issue.

**Comment by beyondcompute** [comment] 2016-02-16 18:21
Thanks for your amazing job and thanks for asking! :blush:  If the "Tweet" button will not require having a Twitter account, then it's a solution, I guess.
I feel a bit weird reporting those super-tiny issues that still require developers time. Is the [Webkit issue](https://code.google.com/p/chromium/issues/detail?id=158652) related (then we should star it)? Probably even disabling line breaks (like turning `textarea` into line input) could be a solution.

**Comment by waderyan** [comment] 2016-02-16 18:49
Yes that is the exact issue. Starred it!

I thought about disabling line breaks, but I think it would be a good thing for the user to do, considering Twitter supports line breaks. 

The Tweet button wouldn't require a Twitter account, but once the Tweet button takes them to twitter they would need to login.

**Comment by beyondcompute** [comment] 2016-02-16 19:08
Well, the need to login on Twitter is a requirement to have a Twitter account :blush: I wouldn't think it's a good UX :relaxed:

**Comment by waderyan** [comment] 2016-02-16 19:10
Right. Unfortunately Twitter doesn't support anonymous tweets.

**Comment by waderyan** [comment] 2016-02-18 19:21
After some internal discussion we decided to go with a dialog redesign. Will work with our UX designer to get some help.

**Comment by waderyan** [comment] 2016-02-18 19:23
Closing as it will be fixed with #3136.

**Closed by waderyan** 2016-02-18 19:23 UTC
Labels: bug
