### ISSUE TITLE
Error squigglies don't appear for zero-length diagnostics on empty line

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#21523] opened 2017-02-27 22:29 UTC
See below:
![image](https://cloud.githubusercontent.com/assets/762848/23382903/e40c5a86-fcf8-11e6-890b-451291c996e4.png)

**Comment by hoovercj** [comment] 2017-02-27 23:24
Duplicate of #1688

**Closed** 2017-02-27 23:54 UTC
Labels: duplicate, editor
