### ISSUE TITLE
[Feature request] Gray out unused or unreachable code in editor

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23805] opened 2017-04-01 20:50 UTC
Feature request here: Gray out unused code (unused `import`'s and `require`'s and unreachable code) in editor with capability to remove it using IntelliSense and <kbd>Ctrl+.</kbd> keyboard shortcut. Primarily needed in Angular 2+ and TypeScript projects.

**Comment by mjbvz** [comment] 2017-04-03 16:42
Duplicate of #15710, which I've add a note to about unreachable code as well

**Closed by mjbvz** 2017-04-03 16:42 UTC
Labels: duplicate, feature-request, javascript, typescript
