### ISSUE TITLE
Window freeze when receiving lots of output (renderer)

### ISSUE THREAD

**Issue by StefH** [Microsoft/vscode#12265] opened 2016-09-19 12:38 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 2008R2

Steps to Reproduce:

1. Open an Java Maven project with a lot of tests
2. Do a `maven clean install` as task command

You get an error message like:
![2016-09-19_14h30_47](https://cloud.githubusercontent.com/assets/249938/18632130/233db5e4-7e76-11e6-84a6-cb4130e5d58c.png)

When you wait until Maven is finished running all the tests, the VS Code windows are completely blocked.

Is there a way to increase the time-out from the `OUTPUT `window?

**Comment by chrmarti** [comment] 2016-09-20 04:43
Couldn't reproduce with a long-running task with lots of output on both OSX and Windows 10. It looks like the large amount of output did slow things down though. The fact that the task runs for a long time shouldn't cause any of this.

@StefH Could you paste your tasks.json for comparison? Thanks.

**Comment by StefH** [comment] 2016-09-20 05:33
**tasks.json**
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "mvn",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "clean"
        },
        {
            "taskName": "compile",
            "args": [
                "clean",
                "install"
            ],
            "isBuildCommand": true
        },
        {
            "taskName": "test"
        },
        {
            "taskName": "package"
        },
        {
            "taskName": "verify"
        }
    ]
}
```

**Comment by chrmarti** [comment] 2016-09-20 21:21
Related to #7353

**Comment by dbaeumer** [comment] 2016-09-21 08:15
This is actually a problem of the output window. Moving to @isidorn.

**Comment by dbaeumer** [comment] 2016-09-21 08:16
I saw the same behavior last week when enabling typescript server tracing which writes a lot of output. In this setup no tasks are involved.

**Comment by isidorn** [comment] 2016-09-21 08:38
September to investigate

**Comment by isidorn** [comment] 2016-09-28 14:03
@dbaeumer can you please share your reproducable steps since I do not want to setup java in order to investigate this. How to setup typescript server tracing and how to get that huge amount of output? Thanks!

**Comment by dbaeumer** [comment] 2016-09-28 14:05
Settings: 

```json
{
	"typescript.tsserver.trace": "verbose"
}
```

Open content assist quite frequently in a project that has a browser environment.

**Comment by bpasero** [comment] 2016-09-29 07:50
I am not convinced that this is an issue with the output panel. I rather believe this is an issue with the extension host pumping data to the renderer and then getting stuck. I have test cases that produce the freeze when run from an extension and no freeze when run within the workbench:

Freeze from Extension (simple hello world extension with hello world command):

```typescript
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.window.showInformationMessage('Crashing!');
        const outputChannel = vscode.window.createOutputChannel("Test");
        outputChannel.show();
        lotsOfOutput(outputChannel);
    });

    context.subscriptions.push(disposable);
}

var max = 10000;
var i = 0;
function lotsOfOutput(outputChannel) {
    setTimeout(() => {
        outputChannel.appendLine(`[Trace - 9:21:49 AM] Sending request: quickinfo (89). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:\\Users\\bpasero\\Desktop\\test-ts\\src\\extension.ts",
    "line": 8,
    "offset": 17
}`);
    i++;
    if (i < max)
        lotsOfOutput(outputChannel);
    }, 1);
}
```

No Freeze within Workbench (for testing purposes change the `CloseEditorAction` in actions.ts (`vs\workbench\electron-browser\actions.ts`) and invoke it:

```typescript
export class CloseEditorAction extends Action {

	public static ID = 'workbench.action.closeActiveEditor';
	public static LABEL = nls.localize('closeActiveEditor', "Close Editor");

	constructor(
		id: string,
		label: string,
		@IOutputService private outputService: IOutputService,
		@IWorkbenchEditorService private editorService: IWorkbenchEditorService
	) {
		super(id, label);
	}

	public run(): TPromise<any> {
		const channel = this.outputService.getChannel("foo");
		channel.show();

		lotsOfOutput(channel);

		return TPromise.as(false);
	}

	private appendOutput(channel): void {

	}
}


var max = 10000;
var i = 0;
function lotsOfOutput(outputChannel) {
    setTimeout(() => {
        outputChannel.append(`[Trace - 9:21:49 AM] Sending request: quickinfo (89). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:\\Users\\bpasero\\Desktop\\test-ts\\src\\extension.ts",
    "line": 8,
    "offset": 17
}`);
    i++;
    if (i < max)
        lotsOfOutput(outputChannel);
    }, 1);
}
```

Adding @jrieken to the thread. I wonder if the [direct call](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostOutputService.ts#L38) to append is too aggressive and needs some buffering.

**Comment by jrieken** [comment] 2016-09-29 08:00
@bpasero @dbaeumer Things are being mixed up here. The initial bug talks about `task.json` which doesn't go via the extension host. Somehow you now brought the extension host into the game which is different.

**Comment by jrieken** [comment] 2016-09-29 08:02
Also - if many messages are being send, a warning should be [printed](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostProcess.ts#L86)

**Comment by bpasero** [comment] 2016-09-29 08:05
@jrieken yup, @dbaeumer filed a similar issue and I merged it here. see https://github.com/Microsoft/vscode/issues/12265#issuecomment-250176298

Bottom line is that the TS extension can produce lots of output when the tracing option is turned on and this output is being send from the extension host.

**Comment by jrieken** [comment] 2016-09-29 08:06
It actually does - <img width="536" alt="screen shot 2016-09-29 at 10 05 42" src="https://cloud.githubusercontent.com/assets/1794099/18945776/4e5df992-862c-11e6-800c-201169f8d867.png">

**Comment by bpasero** [comment] 2016-09-29 08:07
Btw I am on Windows 10 and see this, did not try on Mac. I am also scrolling in the output when this happens. The process monitor shows no activity when this happens, so  it is not stuck in high CPU or high memory.

**Comment by jrieken** [comment] 2016-09-29 08:11
45% of the time is spend in the `OutputService`, 17% in the `OutputEditor`, 7% GC'ing

<img width="674" alt="screen shot 2016-09-29 at 10 09 04" src="https://cloud.githubusercontent.com/assets/1794099/18945892/cdf481f8-862c-11e6-901f-d82a6f0c4bcd.png">

[CPU-20160929T100930.cpuprofile.zip](https://github.com/Microsoft/vscode/files/500072/CPU-20160929T100930.cpuprofile.zip)

**Comment by jrieken** [comment] 2016-09-29 08:12
So, I don't believe this is an issue specific to the extension host (albeit some more buffering could happen) but I see that most work is being spend in the parts outlined above.

**Comment by bpasero** [comment] 2016-09-29 08:13
@jrieken can you reproduce the freeze? is this profile from running from extension host or main side?

**Comment by bpasero** [comment] 2016-09-29 08:13
Also I am not convinced this issue can be tracked down by profiling: When VSCode freezes, there is no high CPU activity nor memory pressure.

**Comment by jrieken** [comment] 2016-09-29 08:17
@bpasero It is very slow and 'yes' this is the main side (OutputService, string-utils etc).

**Comment by dbaeumer** [comment] 2016-09-29 09:40
@StefH reported this when executing a task which is executed in the render (no extension host involved). 

May be an easy way to reproduce this is to write a node program that simply produces lots of output and start it via a task.

**Comment by bpasero** [comment] 2016-09-29 10:25
Ok lets keep this item to look into the performance on the renderer side and https://github.com/Microsoft/vscode/issues/6737 to check for the extension side.

**Comment by bpasero** [comment] 2016-09-29 10:51
I am seeing half of the time spend in the editor in setValue and about 15% in the append function of the outputService:

![image](https://cloud.githubusercontent.com/assets/900690/18951097/7a3415c6-8643-11e6-86bf-b4fc8113d0e5.png)

**Comment by bpasero** [comment] 2016-09-29 14:39
For October to investigate if we can make this faster when lots of output is received. Moving since it is not a regression from previous milestones.

**Comment by bpasero** [comment] 2016-10-14 07:40
@isidorn leaving to you if there is something we can improve. otherwise, the hang in the renderer is a different issue unrelated to consuming the output (related: https://github.com/Microsoft/vscode/issues/13736 and https://github.com/Microsoft/vscode/issues/13667)

**Comment by isidorn** [comment] 2016-10-26 13:21
@bpasero looked in the output and there is nothing obvious to improve. AFAIK the slowness comes from https://github.com/nodejs/node/issues/7657 as you pointed out in a different issue.
Thus closing this

**Closed by isidorn** 2016-10-26 13:21 UTC
Labels: bug
