### ISSUE TITLE
may i add a new menu after help

### ISSUE THREAD

**Issue by hanfengcan** [Microsoft/vscode#38790] opened 2017-11-20 15:07 UTC
may i add a new menu with a tree  after help when i code a extension.

such as this pic

![image](https://user-images.githubusercontent.com/4559753/33024943-744e6b8c-ce47-11e7-9aed-20ef4b6ffed6.png)

**Comment by yume-chan** [comment] 2017-11-21 01:53
Duplicate of #365

**Closed** 2017-11-21 06:12 UTC
Labels: *duplicate, workbench
