### ISSUE TITLE
Failed IPC communication with `playwright` smoke tests from preload script

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#146785] opened 2022-04-05 00:34 UTC
```
1) VSCode Smoke Tests (Electron)
       Quick Open
         "before all" hook for "quick open search produces correct result":
     locator.waitFor: Timeout 40000ms exceeded.
=========================== logs ===========================
waiting for selector ".monaco-workbench" to be visible
============================================================
      at Application.checkWindowReady (D:\a\_work\1\s\test\automation\src\application.ts:149:56)
      at Application._start (D:\a\_work\1\s\test\automation\src\application.ts:98:4)
      at Application.start (D:\a\_work\1\s\test\automation\src\application.ts:75:3)
      at Context.<anonymous> (src\utils.ts:92:3)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=165034&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9302e8c4-de85-5274-34fa-935ce79d4e8d

**Comment by bpasero** [comment] 2022-04-05 05:33
Yes this is from the new smoke tests with playwright, they are marked to not fail the build though.

**Comment by bpasero** [comment] 2022-04-05 07:26
This is our master issue for tracking the Windows issues for using `playwright`. 

/cc @pavelfeldman

**Comment by bpasero** [comment] 2022-04-05 12:03
More logging reveals that the window awaits a IPC reply from the main process to continue loading the workbench. Here is the flow:
* electron main process opens a `ipcMain.handle` (from [here](https://github.com/microsoft/vscode/blob/a7e487b049fecf6dad4cc41f5fc91698b6143059/src/vs/platform/protocol/electron-main/protocolMainService.ts#L141) before the window loadUrl is called)
* window loads `preload.js` first which will immediately call on the `ipcRenderer.invoke` (from [here](https://github.com/microsoft/vscode/blob/4e31ae70e14768f8343b5cdba87d013bab719084/src/vs/base/parts/sandbox/electron-browser/preload.js#L74))
* we await the config object to be resolved
Now we seem to time out on this call, a warning is printed after 10s that we still await the call.

**Comment by bpasero** [comment] 2022-04-05 17:24
Mitigated by doing a window reload after timeout of 10 seconds. This change only impacts smoke tests, I am hesitant to change something in our preload or bootstrap files until real users report this.

Still would be interesting to figure out if this is a Electron regressions.

**Comment by bpasero** [comment] 2022-04-14 08:01
@deepak1556 while I can mitigate the hang in the renderer by doing a window reload, I cannot mitigate it for the shared process where this is also happening and is most likely the cause of https://github.com/microsoft/vscode/issues/146800

Would it be possible to do an internal build where https://github.com/electron/electron/pull/33323 is reverted to see if that is the cause?

**Comment by deepak1556** [comment] 2022-04-20 01:40
@bpasero turns out the above change and https://github.com/electron/electron/commit/3001b69f58c0bcd6fec9de3b007e8966b85e8a75 was reverted internally by Teams since it caused a regression on their end for their custom ipc implementations and never made it into our product builds. This could also explain why it was only seen with CI. I am currently creating newer builds with those changes added back in. Pretty sure this is very likely related to the root issue sharing the cause `sender.url being an empty string when using playwright for testing` in https://github.com/microsoft/vscode/issues/147301. Playwright is causing some sort of frame swap on initial load causing the empty url as well as https://github.com/electron/electron/blob/31c2b5703a75a5ff2bf0e68f472d9002fe866bfb/shell/browser/electron_browser_client.cc#L1558-L1559 condition to fail. I will look into this further once we have newer builds.

**Comment by bpasero** [comment] 2022-04-20 15:59
Thanks ❤️ , I forgot that we use different builds in our CI for smoke tests, so that is a good thing to keep in mind going forward.

Curious what kind of issue Teams folks saw with IPC, maybe we can connect the dots with our issue.

**Comment by bpasero** [comment] 2022-04-22 05:46
Optimistically closing, will reopen when this happens again, I have removed all our workarounds.

**Closed by bpasero** 2022-04-22 05:46 UTC
Labels: linux, windows, smoke-test-failure
