### ISSUE TITLE
File Save is unreliable

### ISSUE THREAD

**Issue by af4jm** [Microsoft/vscode#10003] opened 2016-08-01 02:21 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (4656fe3ff2952e9538d81e7a7571674352e5d62f, 2016-07-29T05:08:49.671Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. press Ctrl-S, about a 50/50 chance if the file will save or not, been happening for at least a month on 2 computers, Win 7 & Win 10
2. separate scenario, same result... had a single file open, it was dirty... with mouse, picked File>Save, then clicked the X to close the app, was prompted to save when the file save was just done (or worst case should have been in progress)

**Comment by bpasero** [comment] 2016-08-06 09:46
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-08-13 06:59
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-08-13 06:59 UTC
Labels: bug, needs more info
