### ISSUE TITLE
File (Explorer) tab randomly disappear

### ISSUE THREAD

**Issue by huyennbl** [microsoft/vscode#129939] opened 2021-08-02 04:04 UTC
I don't understand why and how to reproduce this bug, but just sometimes the 'File' tab in the left panel (see attachment) randomly disappears. I have to later get it back by going to menu View/ Explorer. After that, the tab is back.
Please note that there is no recent extension installation. I've been working with my current set of extensions for quite a long time and this issue happens recently
``` Update: I see that it happens more when I use Ctrl + Shift + F to do search ```

- Windows 10
![image](https://user-images.githubusercontent.com/33422297/127803074-9bd47696-ea4e-4f1f-ac51-7209d9a30582.png)

This tab
![image](https://user-images.githubusercontent.com/33422297/127802869-29c4cb8e-3b43-4397-98eb-13c60bcc0bda.png)
Bug happens
![image](https://user-images.githubusercontent.com/33422297/127803541-2a5108d7-bdab-4c34-aa04-41fa46eb4049.png)

**Comment by isidorn** [comment] 2021-08-02 08:08
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by huyennbl** [comment] 2021-08-03 04:14
hi @isidorn, Insiders version doesn't have this behavior

**Comment by isidorn** [comment] 2021-08-03 08:52
Then the issue is probably related to on of your extensions. I suggest that you disable them one by one. Or to swtich to insiders.
Anyways there is nothing actionable we can do here, thus closing this issue

**Closed by isidorn** 2021-08-03 08:52 UTC
Labels: file-explorer, needs more info

**Comment by huyennbl** [comment] 2021-08-03 13:27
Okay, thanks @isidorn 
I just wanna get back to you that even I disabled all my extensions, the problem is still there. Seems like switching to the insiders version is the only choice for me in this case.
