### ISSUE TITLE
Task 'New Window' doesn't work

### ISSUE THREAD

**Issue by michaelbaranov** [Microsoft/vscode#9189] opened 2016-07-13 08:57 UTC
- VSCode Version: 1.3.1
- OS Version: Windows 10, build 10240

Steps to Reproduce:

1. Right click on VS icon in task bar
2. Select 'New Window'

Actual result- In task manager I can see new process starts, but it disappear in 2 seconds.
Expected result- New instance of VS is opened.

**Comment by weinand** [comment] 2016-07-13 10:18
@michaelbaranov I cannot reproduce this in Windows 10.  Does the problem persist after a reboot?

**Comment by michaelbaranov** [comment] 2016-07-14 06:56
@weinand Yes, it persists even after 3 reboots.
Are there any logs written I can look into?
It looks like new VS process starts and crashes after few seconds.

**Comment by weinand** [comment] 2016-07-14 07:54
@michaelbaranov you can open the "Toggle Developer tools" via F1 and switch to their console. Are there any errors showing up?

**Comment by michaelbaranov** [comment] 2016-07-18 15:00
Nothing there. I guess logs are written to console of instance that crashes and not the one that is open at the moment.

**Comment by kieferrm** [comment] 2016-07-22 17:58
@michaelbaranov Do you by any chance run in admin mode? (see #9600)

**Comment by VitorLuizC** [comment] 2016-07-28 12:58
Same happens to me.
Window 10 and vs code 1.4.0-insiders

![image](https://cloud.githubusercontent.com/assets/9027363/17213212/be8cf510-54a9-11e6-82b2-6804fd2be9f4.png)

PS. I'm running in the admin mode

**Comment by mrmlnc** [comment] 2016-07-28 13:02
I can reproduce this in Windows 10 (build 10586.494) with admin mode.

**Comment by kieferrm** [comment] 2016-08-02 19:30
Duplicate of  #9600.

**Closed by kieferrm** 2016-08-02 19:30 UTC
Labels: needs more info
