### ISSUE TITLE
Unable to uninstall Extensions

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#33787] opened 2017-09-04 10:28 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Go to Extensions
2. Try to uninstall an extension
3. Massive amount Unknown Errors in devtools console
![image](https://user-images.githubusercontent.com/30625381/30022670-93a2f4b6-916c-11e7-94c5-156ec00a02f3.png)

**Comment by bm-stschneider** [comment] 2017-09-06 06:32
This is by the way not specific to a certain extension, I have this on various once also some newly installed and some old extensions.

**Comment by sandy081** [comment] 2017-09-07 11:56
Can you follow following steps and provide more information

- Type `Developer: Toggle Shared Process` in the command pallette and run the command.
- This will open developer tools for shared process that does install/uninstalling of extensions
- Provide any logs from that process.

Thanks

**Comment by bm-stschneider** [comment] 2017-09-07 12:27
Here you go
[-1504787167235.txt](https://github.com/Microsoft/vscode/files/1284618/-1504787167235.txt)

**Comment by sandy081** [comment] 2017-09-08 06:50
@bm-stschneider Are you sure the above log is from the Shared process ? I am suspecting this is same as the one you pasted in the desription.

**Comment by bm-stschneider** [comment] 2017-09-08 06:57
You are correct. Sorry, hang on.

**Comment by bm-stschneider** [comment] 2017-09-08 06:58
The shared process stays empty.

**Comment by sandy081** [comment] 2017-09-12 07:11
Hmm.. strange.

Is it happening for all extensions?
Any luck restarting VS Code?

**Comment by bm-stschneider** [comment] 2017-09-12 08:37
Currently, yes. No restarting does not change anything. I can still uninstall them manually of course by deleting them in the extensions folder. Just trying to help :)

**Comment by sandy081** [comment] 2017-09-13 14:30
@joaomoreno Can you please help in knowing the root cause of this issue? Anything to do with the folder access permissions?

**Comment by joaomoreno** [comment] 2017-09-14 06:41
@bm-stschneider Does uninstalling from the command line work?

```
code --uninstall-extension publisher.name
```

**Comment by bm-stschneider** [comment] 2017-09-14 06:55
@joaomoreno No, does not work.

**Comment by joaomoreno** [comment] 2017-09-15 06:57
Any errors there? Any output?

**Comment by bm-stschneider** [comment] 2017-09-18 06:30
Nope, vscode just starts normally and does not prompt anything.

**Comment by joaomoreno** [comment] 2017-09-18 07:46
Can you try closing Code, moving the `~/.vscode/extensions` folder away, launching Code, install a few extensions and then try to uninstall them? Maybe there is something strange in the `extensions` folder which breaks things.

**Comment by bm-stschneider** [comment] 2017-09-18 07:55
A fresh extensions folder works

**Comment by bm-stschneider** [comment] 2017-09-18 07:58
I had a look at the extensions folder. Is it correct that there are sometimes multiple versions of the same extension in there?

**Comment by joaomoreno** [comment] 2017-09-18 08:30
Yeah that should be fine. Any chance you can zip that up so we take a look at it?

**Comment by bm-stschneider** [comment] 2017-09-18 08:52
I guess not. But as far as I remember it started when I tried to install from the marketplace directly.
Sometime I have the extension already installed and sometime vscode wouldn't start to prompt me for installation when I already have installed it from within vscode directly.

**Comment by joaomoreno** [comment] 2017-09-18 08:54
Oh, you didn't save the folder? You deleted it?

**Comment by bm-stschneider** [comment] 2017-09-18 08:57
No, but I removed all the extra version of some extensions and that might have solved the problem. But since it where multiple I don't know which one might have been the show stopper.

**Comment by joaomoreno** [comment] 2017-09-18 09:29
Alright, I'll close this for now. Keep an eye open. If it happens again send us the archived folder. :+1:

**Closed by joaomoreno** 2017-09-18 09:29 UTC
Labels: extensions, needs more info

**Comment by G3z** [comment] 2017-11-13 18:29
this just happened to me and I noticed some incorrect permissions
```
drwxr-xr-x  18 root  staff  576  2 Nov 13:03 vsmobile.vscode-react-native-0.5.1
drwxr-xr-x  18 g3z   staff  576  7 Nov 16:52 vsmobile.vscode-react-native-0.5.2
```
running a `sudo chown -R g3z extensions` fixed the issue

My best guess: some extension was installed (or auto updated) while i was running `code` as super user ( to edit httpd.conf or php.ini, in case you are wondering) and before uninstalling an extension vscode has to check some files in the extension folder it now can't access
