### ISSUE TITLE
Python docstring auto-inserts triple quotes at both cursors in a file during Live Share

### ISSUE THREAD

**Issue by aely-aronoff** [microsoft/vscode#127910] opened 2021-07-02 23:34 UTC
Issue Type: <b>Bug</b>

Hello, hello. Firstly, let me say I really love VS Code and Live Share and use it all the time with my team. Fantastic work!

There is a bug we've noticed and I'm not sure if it's coming from Live Share or the Python extension but here's what happens:
- On host machine, when I type the opening triple quotes of a docstring (`"""`) it automatically inserts the closing triple quotes, which is desired behavior.
- When I'm on Live Share with another dev on a remote machine, if they type an opening triple quote it automatically inserts the closing triple quotes _at my cursor_ instead of at their cursor.

This is a little annoying since any time the other dev starts a docstring I suddenly have three quotes appear wherever I'm writing code. Note that this only happens when we're both editing the same file - it doesn't happen if we're editing different files. It also doesn't happen when the other dev starts a regular string with quote (`"`) or apostrophe (`'`). Only with the docstrings. 

I haven't tested this on other pairs of computers, but my computer is a Windows machine and the other dev is on a MacBook Pro, MacOS v11.1.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.50GB free)|
|Process Argv|--crash-reporter-id 823b39f3-cbe6-4f28-9268-d408bb416063|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
go|gol|0.26.0
vscode-edit-csv|jan|0.6.0
solidity|Jua|0.0.124
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vsliveshare|ms-|1.0.4498

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by sbatten** [comment] 2021-07-06 16:57
This is possibly caused by extension, assigning to @alexdima to determine if its possibly us.

**Comment by alexdima** [comment] 2021-07-14 09:59
Moved to https://github.com/MicrosoftDocs/live-share/issues/4353

**Closed by alexdima** 2021-07-14 09:59 UTC
