### ISSUE TITLE
Feature Request: "Always show Error List if build finishes with errors"

### ISSUE THREAD

**Issue by rickvanprim** [Microsoft/vscode#37379] opened 2017-11-01 04:43 UTC
Requesting the same feature as Visual Studio.  It would be nice to be able to run a task, watch the output, and then once the task finishes, automatically switch to the Problems tab if there is a matcher associated and problems are detected.  I think this could be another bool option underneath Tasks' Presentation grouping.

![image](https://user-images.githubusercontent.com/13792812/32260339-7b63f3a6-be84-11e7-82bd-b1dd8432f4d1.png)

**Comment by dbaeumer** [comment] 2017-11-01 08:15
As a workaround you can click on the error status in the status bar which opens the problems view as well.

**Comment by rickvanprim** [comment] 2017-11-01 17:55
Right now I have `presentation.reveal: silent` in my build task so that when I build it doesn't hide the Problems panel.

**Comment by aardappel** [comment] 2017-11-08 15:49
@dbaeumer : that is not a great workaround, as currently the problem is that it is not very obvious whether there is an error at all. Basically, I press Ctrl-Shift-B, and then either one of two things happens: my program launches correctly, or I need to spot a little `0` in the status bar change into a `1`. Then I need to either click on that or press F8.

**Comment by aardappel** [comment] 2017-11-08 15:50
related: https://github.com/Microsoft/vscode/issues/36308

**Comment by rickvanprim** [comment] 2018-12-03 23:41
related: #44146

**Comment by alexr00** [comment] 2018-12-21 14:30
Duplicate of #44146, since that once has more activity.

**Closed** 2018-12-21 14:30 UTC
Labels: *duplicate, feature-request, tasks
