### ISSUE TITLE
Variable evaluation for task input defaults

### ISSUE THREAD

**Issue by ARF1** [microsoft/vscode#86523] opened 2019-12-07 13:23 UTC
@alexr00 Thanks for implementing input variables in tasks in #63910.

Currently, the default inputs can only be "pure" strings. Any variables are not evaluated. Would it be possible to evaluate any variables in the default string?

This would be really useful if one wanted to save the result of a task run on a file using a variant of the original filename. E.g. `myfile.py` --> `myfile_profiling_results.txt`

Example use:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    // ... snipped for conciseness ...
    "inputs": [
        {
            "id": "filename",
            "description": "Please enter a filename for the profiling results file",
            "default": "{$file}",
            "type": "promptString",
        },
    ],
}
```

**Comment by alexr00** [comment] 2019-12-09 08:41
Duplicate of https://github.com/microsoft/vscode/issues/64358

**Closed** 2019-12-09 08:41 UTC
Labels: *duplicate, tasks
