### ISSUE TITLE
git Synchronized modification

### ISSUE THREAD

**Issue by meiletian** [microsoft/vscode#154732] opened 2022-07-11 02:24 UTC
Issue Type: <b>Bug</b>

When I submit all the local code, there will always be a button for synchronizing changes displayed there, which makes me feel very uncomfortable, always thinking that I have something unfinished, and I feel bad after the upgrade.

VS Code version: Code 1.69.0 (Universal) (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id add9dde9-7e6e-4ffe-8273-f190a9b631a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
iconify|ant|0.3.3
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
vscode-drawio|hed|1.6.4
headwind|hey|1.7.0
eslint-rules-zh-plugin|mag|0.1.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.69.7060951
vscode-stylelint|sty|1.2.2
volar|Vue|0.38.3
json|Zai|2.0.2
es6-string-javascript|zjc|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by lszomoru** [comment] 2022-07-11 11:54
Thank you very much for the feedback. Closing this issue as duplicate of #154478 as that is where I would like to gather all the feedback about the "Sync Changes" button being shown even when there are no incomig/outgoing changes.

**Closed by lszomoru** 2022-07-11 11:54 UTC
Labels: git, new release
