### ISSUE TITLE
Debug output: Detected links are incomplete

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#24080] opened 2017-04-06 15:17 UTC
ElementaryOS Freya

- clone and open  https://github.com/Microsoft/vscode-css-languageservice
- add an error to one of the tests
- run the tests
- observer the debug console: the underlined link does not cover the full path (lib is ommited).
 Clicking on the link gives and error as the file can not be found

![image](https://cloud.githubusercontent.com/assets/6461412/24761844/de735004-1aec-11e7-9453-2fa6e7894cde.png)

![image](https://cloud.githubusercontent.com/assets/6461412/24761859/eddadcb0-1aec-11e7-8019-28c9f4a8a109.png)

**Comment by michelkaporin** [comment] 2017-04-06 16:05
Sorry, duplicate of #15760

**Closed by michelkaporin** 2017-04-06 16:05 UTC
