### ISSUE TITLE
Ctrl+D changes search input for repeated content

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23732] opened 2017-03-31 09:52 UTC
Version 1.11.0-insider
Commit 277dc8bdb99ac2ae820d5ee35d9fa2fedd65d0b1
Date 2017-03-31T08:31:42.609Z

Have the following file foo.txt
```
asdasdasd

sasdasd

asdasdasdasd
```
- select `das` on the first list
- Press Ctrl + D. Observe that the selection gets extended to 'dasdas' and that the next match is on line 3

**Comment by alexandrudima** [comment] 2017-03-31 09:58
Duplicate of #6661

**Closed by alexandrudima** 2017-03-31 09:58 UTC
