### ISSUE TITLE
"Editor Rulers" issues in settings panel

### ISSUE THREAD

**Issue by q3boy** [microsoft/vscode#97591] opened 2020-05-12 08:45 UTC
Issue Type: <b>Bug</b>

1. open user settings panel.
2. find “Editor Rulers” section.
3. click edit in `settings.json`.
4. it automatic generate code is `"editor.rulers": [ {} ], looks not correctly.
5. then I change it to `"editor.rulers": [80, 88, 96, 104, 112]` 
6. finally it works, but in settings panel, I got an error message ` Setting has an invalid type, expected “array”, FIX in JSON. `

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

**Comment by alexdima** [comment] 2020-05-12 09:08
@roblourens Giving to you to investigate. Here is how the setting is defined:

https://github.com/microsoft/vscode/blob/756e105ee4f12330c454eb2b61fca10c35b6ced8/src/vs/editor/common/config/editorOptions.ts#L2714-L2740

**Comment by gjsjohnmurray** [comment] 2020-05-12 09:48
Perhaps #97192 which looks like it'll get fixed in the recovery

**Comment by q3boy** [comment] 2020-05-12 10:08
I change my settings to `"editor.rulers": [ {"column":80}, {"column":88}, {"column":96}, {"column":104}, {"column":112} ]`, now it shows no more errors. Should this change been update to the document?
![Uploading CleanShot 2020-05-12 at 18.07.34.png…]()

**Comment by roblourens** [comment] 2020-05-13 00:42
Duplicate of https://github.com/microsoft/vscode/issues/97192

**Closed by roblourens** 2020-05-13 00:42 UTC
