### ISSUE TITLE
Vscode didn't show the lastest branch 

### ISSUE THREAD

**Issue by yifeifang** [microsoft/vscode#115142] opened 2021-01-26 20:00 UTC
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a folder
2. Launch VScode
3. create a file (doesn't matter about the type)
4. Git init repo from vscode
5. Do the init commit
6. Try to create a new branch from master but the master is not displayed as git ref. Only HEAD is displayed

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/29108355/105898138-f186a680-5fcd-11eb-9eff-0e825c3c94a6.png)
![image](https://user-images.githubusercontent.com/29108355/105898183-fea39580-5fcd-11eb-9831-9349ea92a366.png)
![image](https://user-images.githubusercontent.com/29108355/105898225-08c59400-5fce-11eb-9e2b-161dcad8c8f5.png)

It wouldn't not display the latest branch no matter what I did.
Updated git to newest windows git 2.30

**Comment by eamodio** [comment] 2021-01-26 22:38
Duplicate of #112838

**Closed by eamodio** 2021-01-26 22:38 UTC
