### ISSUE TITLE
Emojis can get cut off in the terminal

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35102] opened 2017-09-26 12:41 UTC
Testing #34868

[emoji-test.txt](https://github.com/Microsoft/vscode/files/1333096/emoji-test.txt)
* save this file as UTF8 with bom (I think it is already)
* configure `"terminal.integrated.scrollback": 5000`
* run `chcp 65001`
* run `cat emoji-test.txt`

Observe:

#### cut emojis e.g.
![image](https://user-images.githubusercontent.com/5047891/30860437-5f5aa4e4-a2c7-11e7-89c7-6fd90a408adc.png)

#### combining sequences that Chromium supports e.g.
![image](https://user-images.githubusercontent.com/5047891/30860515-9ee48cba-a2c7-11e7-8067-ceae60af9ae8.png)

**Comment by Tyriar** [comment] 2017-09-26 17:51
@alexandrudima what font is this with? For all the monospace fonts I've tested they consistently only cover 2 cells.

Skin tone modifiers are not just a matter of joining the characters in the terminal as the shell doesn't understand that these characters are one. This is as designed for the time being as we're relying on the older tech in shells. See https://github.com/sourcelair/xterm.js/issues/942

**Comment by alexandrudima** [comment] 2017-09-27 06:51
@Tyriar Did you attempt to reproduce this given the steps I have provided ? I did not customize the font, otherwise I would have mentioned it.

**Comment by Tyriar** [comment] 2017-09-27 12:54
@alexandrudima I don't have access to a Windows machine, trying to get enough information to fix without access.

**Comment by alexandrudima** [comment] 2017-09-27 13:27
Sure, if it helps it is also reproducible on OSX with default settings with this:
```
2639 FE0F                                  ; fully-qualified     # ☹️ frowning face
```

**Comment by Tyriar** [comment] 2017-09-27 13:42
Ah I can reproduce as well, seems that not all emojis are being handled correctly:

<img width="45" alt="screen shot 2017-09-27 at 9 38 39 am" src="https://user-images.githubusercontent.com/2193314/30916558-b51c4ebe-a367-11e7-9c4e-8cc9d4aba08e.png">

This may have been introduced in https://github.com/sourcelair/xterm.js/commit/c4da8325ace6e4bde77822377bf994d389a7c75a#diff-59a6c78910b740a7b8381b034eeb73a2. Chars are now drawn and their dimensions measured to see if they consume the following cell. Previously I used this regex to test if it was an emoji:

```js
char.search(/([\uD800-\uDBFF][\uDC00-\uDFFF])/g) >= 0;
```

**Comment by alexandrudima** [comment] 2017-09-27 14:28
@Tyriar this is how I look for emojis in the editor input:

```ts
/**
 * Generated using https://github.com/alexandrudima/unicode-utils/blob/master/generate-emoji-test.js
 */
const CONTAINS_EMOJI = /(?:[\u231A\u231B\u23F0\u23F3\u2600-\u27BF\u2B50\u2B55]|\uD83C[\uDDE6-\uDDFF\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F\uDE80-\uDEF8]|\uD83E[\uDD00-\uDDE6])/;

export function containsEmoji(str: string): boolean {
	return CONTAINS_EMOJI.test(str);
}

if (/\uFE0F/.test(potentialEmojiInput) || strings.containsEmoji(potentialEmojiInput)) {
  // it is probably an emoji
}

```

**Comment by Tyriar** [comment] 2017-09-27 18:55
@alexandrudima thanks for this, I'll probably just test this before doing the actual measure (which covers other unicode chars) 👍

**Comment by Tyriar** [comment] 2017-09-28 12:08
Turns out this was already fixed I just wasn't on the latest. Fixed in https://github.com/Microsoft/vscode/commit/f9a040fe712957a7bf756aa9c76b79ec764f7160

**Closed by Tyriar** 2017-09-28 12:08 UTC
Labels: bug, integrated-terminal, upstream

**Comment by Tyriar** [comment] 2017-09-28 12:11
No plan to fix the issue where the emoji is so width is expands beyond 2 cells. I'll keep it in mind though if we tweak the cell ownership model.
