### ISSUE TITLE
javascript multi-line template literals highlight bug

### ISSUE THREAD

**Issue by batobolg** [microsoft/vscode#125627] opened 2021-06-06 16:19 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (3 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

Steps to Reproduce:

1. I hava a js file like this
![image](https://user-images.githubusercontent.com/8541549/120931772-0c141d80-c72e-11eb-807b-2f102fc03847.png)

2. wen focus on the tag text or on the between word it highlight all the template literals, in long multi-line text it boring to edit.

**Comment by IllusionMH** [comment] 2021-06-06 23:13
/duplicate of https://github.com/microsoft/TypeScript/issues/43292

Best thing you can do ATM is to disable all occurrences highlights with `"editor.occurrencesHighlight": false`.

**Closed** 2021-06-06 23:13 UTC
Labels: *duplicate
