### ISSUE TITLE
Inlay hints' text edits do not apply when being resolved

### ISSUE THREAD

**Issue by SomeoneToIgnore** [microsoft/vscode#193124] opened 2023-09-14 15:26 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
```
Version: 1.82.1
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:49:22.656Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

Steps to Reproduce:

1. Have a language server that is able to resolve `textEdits` field of inlay hints, e.g. rust-analyzer
2. Get a hint, hover it and double click it, to insert hint's edit
Expected: the document gets edited with hint contents
Actual: nothing happens, but hint resolve definitely happens as LSP log shows, and we can cmd+click certain hints (which means r-a resolved `label.location`)

Additional information: if `textEdits` is not resolved (see patch for rust-analyzer in https://github.com/rust-lang/rust-analyzer/issues/15604 or remove the corresponding client hint resolve capability), double clicking the hint works.

**Comment by jrieken** [comment] 2023-09-15 06:43
Please attach a minimal but complete code sample that allows me to reproduce this

**Comment by SomeoneToIgnore** [comment] 2023-09-15 07:01
Alas, I'm not aware of any other langserver capable of sending hints' edits, so I'm using rust-analyzer as an example, any latest version has this.

1. Create a new Rust project somewhere: `cargo init test_resolve`
2. adjust `./test_resolve/src/main.rs` to contain anything with variables, e.g. 
```rust
fn main() {
    let test = "foo".to_string();
}
```
3. `test` variable will have a `: String` hint after you interact with the editor (VSCode does not issue another hint request after hint refresh, see https://github.com/rust-lang/rust-analyzer/issues/13369#issuecomment-1711503896, so you have to scroll or somehow edit the document for the first hints to appear)
4. double click the hint — it would not insert its edit
5. cmd + click the hint — it will navigate elsewhere

rust-analyzer resolves both properties (`textEdit` that does not work and `label.location` that works and navigates).

<details>
  <summary>LSP trace I'm getting for this sequence</summary>
  
  ```log
[[Trace - 09:55:50] Sending request 'initialize - (0)'.
[Trace - 09:55:50] Received response 'initialize - (0)' in 5ms.
[Trace - 09:55:50] Sending notification 'initialized'.
[Trace - 09:55:50] Sending notification 'textDocument/didOpen'.
[Trace - 09:55:50] Received notification 'experimental/serverStatus'.
[Trace - 09:55:50] Received request 'client/registerCapability - (0)'.
[Trace - 09:55:50] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 09:55:50] Received request 'window/workDoneProgress/create - (1)'.
[Trace - 09:55:50] Sending response 'window/workDoneProgress/create - (1)'. Processing request took 0ms
[Trace - 09:55:50] Received notification '$/progress'.
[Trace - 09:55:50] Sending request 'textDocument/codeAction - (1)'.
[Trace - 09:55:50] Received response 'textDocument/codeAction - (1)' in 2ms.
[Trace - 09:55:50] Sending request 'textDocument/inlayHint - (2)'.
[Trace - 09:55:50] Received response 'textDocument/inlayHint - (2)' in 22ms.
[Trace - 09:55:50] Received notification '$/progress'.
[Trace - 09:55:50] Sending request 'textDocument/inlayHint - (3)'.
[Trace - 09:55:50] Sending notification '$/cancelRequest'.
[Trace - 09:55:50] Sending request 'textDocument/inlayHint - (4)'.
[Trace - 09:55:50] Received response 'textDocument/inlayHint - (3)' in 28ms.
[Trace - 09:55:50] Received response 'textDocument/inlayHint - (4)' in 3ms.
[Trace - 09:55:51] Received request 'client/registerCapability - (2)'.
[Trace - 09:55:51] Sending response 'client/registerCapability - (2)'. Processing request took 1ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (3)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (3)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (4)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (4)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Sending request 'textDocument/foldingRange - (5)'.
[Trace - 09:55:51] Sending request 'textDocument/semanticTokens/range - (6)'.
[Trace - 09:55:51] Received response 'textDocument/foldingRange - (5)' in 0ms.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received response 'textDocument/semanticTokens/range - (6)' in 28ms.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Sending request 'textDocument/semanticTokens/full - (7)'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'workspace/semanticTokens/refresh - (5)'.
[Trace - 09:55:51] Sending response 'workspace/semanticTokens/refresh - (5)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'workspace/codeLens/refresh - (6)'.
[Trace - 09:55:51] Sending response 'workspace/codeLens/refresh - (6)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (7)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (7)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'workspace/semanticTokens/refresh - (8)'.
[Trace - 09:55:51] Sending response 'workspace/semanticTokens/refresh - (8)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'workspace/codeLens/refresh - (9)'.
[Trace - 09:55:51] Sending response 'workspace/codeLens/refresh - (9)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (10)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (10)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (11)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (11)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'client/registerCapability - (12)'.
[Trace - 09:55:51] Sending response 'client/registerCapability - (12)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (13)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (13)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (14)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (14)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received request 'workspace/semanticTokens/refresh - (15)'.
[Trace - 09:55:51] Sending response 'workspace/semanticTokens/refresh - (15)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'workspace/codeLens/refresh - (16)'.
[Trace - 09:55:51] Sending response 'workspace/codeLens/refresh - (16)'. Processing request took 0ms
[Trace - 09:55:51] Received request 'workspace/inlayHint/refresh - (17)'.
[Trace - 09:55:51] Sending response 'workspace/inlayHint/refresh - (17)'. Processing request took 0ms
[Trace - 09:55:51] Received notification 'experimental/serverStatus'.
[Trace - 09:55:51] Received request 'window/workDoneProgress/create - (18)'.
[Trace - 09:55:51] Sending response 'window/workDoneProgress/create - (18)'. Processing request took 0ms
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Received notification '$/progress'.
[Trace - 09:55:51] Sending request 'textDocument/codeAction - (8)'.
[Trace - 09:55:51] Sending request 'textDocument/documentSymbol - (9)'.
[Trace - 09:55:51] Received response 'textDocument/documentSymbol - (9)' in 0ms.
[Trace - 09:55:51] Sending request 'textDocument/codeLens - (10)'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received response 'textDocument/codeLens - (10)' in 1474ms.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:53] Received notification '$/progress'.
[Trace - 09:55:54] Received notification 'textDocument/publishDiagnostics'.
[Trace - 09:55:54] Received response 'textDocument/semanticTokens/full - (7)' in 3362ms.
[Trace - 09:55:54] Received response 'textDocument/codeAction - (8)' in 2643ms.
[Trace - 09:55:54] Sending request 'textDocument/semanticTokens/full/delta - (11)'.
[Trace - 09:55:54] Received response 'textDocument/semanticTokens/full/delta - (11)' in 2ms.
/////////////////////// above logs are for me opening an editor and waiting, doing nothing

[Trace - 09:56:19] Sending request 'textDocument/inlayHint - (12)'.
[Trace - 09:56:19] Received response 'textDocument/inlayHint - (12)' in 2ms.
[Trace - 09:56:19] Sending request 'textDocument/inlayHint - (13)'.
[Trace - 09:56:19] Received response 'textDocument/inlayHint - (13)' in 1ms.
/////////////////////// above logs appeared after scrolling below and back, to make the hint appear

[Trace - 09:57:09] Sending request 'inlayHint/resolve - (14)'.
[Trace - 09:57:09] Received response 'inlayHint/resolve - (14)' in 3ms.
[Trace - 09:57:09] Sending notification 'textDocument/didOpen'.
[Trace - 09:57:09] Sending request 'textDocument/hover - (15)'.
[Trace - 09:57:09] Sending notification 'textDocument/didClose'.
[Trace - 09:57:09] Received notification 'textDocument/publishDiagnostics'.
[Trace - 09:57:09] Received response 'textDocument/hover - (15)' in 20ms.
/////////////////////// above logs appeared after hovering the hint, I get the pop-up, ability to cmd+click it, but no double click to apply the edit
  ```  
</details>

I would assume you can adjust VSCode to not to show `textEdit` inlay hint resolve capability, that would make rust-analyzer to send these edits back and double click will work.
Alternatively, patch rust-analyzer to forbid resolving `textEdit` (see patch in https://github.com/rust-lang/rust-analyzer/issues/15604) and do `cargo xtask install --server` on rust-analyzer + make VSCode settings.json aware of the installed server: `"rust-analyzer.server.path": "rust-analyzer",` (or use any other installation path if needed).
This will bring the same results: double click starts to work.

**Comment by SomeoneToIgnore** [comment] 2023-09-15 12:43
If it's helpful, here are the json responses rust-analyzer language server emits for the example above

* during first response
```
{
    "jsonrpc": "2.0",
    "id": 13,
    "result": [
        {
            "position": {
                "line": 1,
                "character": 12
            },
            "label": [
                {
                    "value": ": "
                },
                {
                    "value": "String"
                },
                {
                    "value": ""
                }
            ],
            "kind": 1,
            "paddingLeft": false,
            "paddingRight": false,
            "data": {
                "file_id": 0
            }
        }
    ]
}
```

* after resolving on hint hover
```
{
    "jsonrpc": "2.0",
    "id": 15,
    "result": {
        "position": {
            "line": 1,
            "character": 12
        },
        "label": [
            {
                "value": ": "
            },
            {
                "value": "String",
                "location": {
                    "uri": "file:///Users/someonetoignore/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/string.rs",
                    "range": {
                        "start": {
                            "line": 364,
                            "character": 11
                        },
                        "end": {
                            "line": 364,
                            "character": 17
                        }
                    }
                }
            },
            {
                "value": ""
            }
        ],
        "kind": 1,
        "textEdits": [
            {
                "range": {
                    "start": {
                        "line": 1,
                        "character": 12
                    },
                    "end": {
                        "line": 1,
                        "character": 12
                    }
                },
                "newText": ": String"
            }
        ],
        "paddingLeft": false,
        "paddingRight": false
    }
}
```

there seems nothing in `location` and `textEdits` that could get obsolete during inlay hint hover, so I'm not sure why the former works and the latter does not after resolving.
If `textEdit` contents gets moved into the initial response, double click starts to work.

**Comment by SomeoneToIgnore** [comment] 2023-09-21 12:53
A small update: I've added a [workaround](https://github.com/rust-lang/rust-analyzer/pull/15635) into rust-analyzer, so now, in order to reproduce it with VSCode, somebody has to either change the `clientInfo.name` value to something different or use rust-analyzer without the patch.

**Comment by SomeoneToIgnore** [comment] 2023-12-11 12:19
Can confirm this is still a thing with the edits only.

**Comment by heejaechang** [comment] 2024-01-09 05:34
Hi, I am a dev from `pylance` and we are having the same problem.

it looks like it is **a bug** either in `vscode` or `lsp` based on what is the expected behavior.

when `LSP` is initialized, it clearly says it supports resolving `textEdits` as it is shown in the source code.

https://github.com/microsoft/vscode-languageserver-node/blob/d1c83dbbb0a37621a2028ac871f6ce3409e7baba/client/src/common/inlayHint.ts#L39-L41

but `vscode` never actually resolve `textEdits` property according to the source code.

https://github.com/microsoft/vscode/blob/7452aaa51d440d39c4e6ab61970b290b8600f52f/src/vs/editor/contrib/inlayHints/browser/inlayHints.ts#L58-L59

so either `LSP` should not say it support `textEdits` or `vscode` should set `textEdits` it got from `resolveInlayHint`

...

but that said, for us, we want `textEdits` to be supported since we want to make some improvements where `text edit` we generate is actually valid and context aware (that also means it is too expensive to generate for all inlay hints upfront)

and also, it looks like all it needs to fix the issue is just adding one line to the vscode above.

``` ts
this.hint.textEdits = newHint?.textEdits ?? this.hint.textEdits;
```

**Comment by heejaechang** [comment] 2024-01-09 05:46
there are actually multiple places in `vscode` codebase that calls `resolveInlayHint` and this one seems handle `textEdits`

https://github.com/microsoft/vscode/blob/7452aaa51d440d39c4e6ab61970b290b8600f52f/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1460-L1468

but none of others do.

**Comment by jrieken** [comment] 2024-01-09 10:03
Thanks you @heejaechang !

**Closed** 2024-01-09 10:19 UTC
Labels: bug, inlay-hints
