### ISSUE TITLE
[php] HTML element not hilighted correctly in php document

### ISSUE THREAD

**Issue by lalit22** [Microsoft/vscode#6314] opened 2016-05-12 09:31 UTC
![screenshot](https://cloud.githubusercontent.com/assets/19204218/15210525/824fc9ba-1854-11e6-88e7-c6e4d272b6f1.jpg)
- VSCode Version:1.1.0
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open any php document
2. Then click on any html tag. (eg. Div)
3. You will see that all div element highlighted

element not highlight its opening or closing tag like html document

**Comment by anudeep3998** [comment] 2016-05-17 16:48
+1

**Comment by aeschli** [comment] 2016-07-19 14:46
duplicate of #2915

**Closed by aeschli** 2016-07-19 14:46 UTC
Labels: feature-request, php
