### ISSUE TITLE
VSCode/CodeHelper process is blocking folders (Cordova)

### ISSUE THREAD

**Issue by Urahara** [Microsoft/vscode#7492] opened 2016-06-09 19:47 UTC
- VSCode Version: 1.2.0
- OS Version: Windows 7 Professional (7601: Service Pack 1)

Steps to Reproduce:

1. Edit some file in VSCode.
2. Try to run cordova (compile, etc)

![process](https://cloud.githubusercontent.com/assets/1462548/15943923/838f6f1a-2e61-11e6-8114-786da361792d.png)

When i try to compile my app I get the **enotempty directory not empty** because of blocking of vscode/codehelper.

**Comment by bpasero** [comment] 2016-06-13 08:05
@Urahara is this project using typescript?

**Comment by Urahara** [comment] 2016-06-13 11:15
@bpasero Only JS.

**Comment by bpasero** [comment] 2016-06-13 11:59
@dbaeumer is the file locking issue with TypeScript also an issue for JS given Salsa?

**Comment by dbaeumer** [comment] 2016-06-14 07:30
@dbaeumer I would say yes since JS files will be handled by Salsa which will install the TS file watcher. To be sure @Urahara could do the following:

- reproduce the problem
- use handle.exe (https://technet.microsoft.com/en-us/sysinternals/handle.aspx) to find out which process is holding a lock to the folder or files inside a folder that can't be deleted.

Post the process, including its command line here. Then we can be sure which process is holding the lock.

**Comment by Urahara** [comment] 2016-06-14 15:05
cordova run android -idsmartphone

    8: File  (---)   C:\Program Files\Microsoft VS Code
    C: File  (---)   C:\Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2
  120: File  (---)   C:\Program Files\Microsoft VS Code\snapshot_blob.bin
  128: File  (---)   C:\Program Files\Microsoft VS Code\natives_blob.bin
  150: Section       \Sessions\1\BaseNamedObjects\node-debug-handler-5448
  22C: File  (---)   C:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\utils\electronForkStart.js
  244: File  (---)   C:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
  248: File  (---)   C:\Projetos\ProjetoMobile\.vscode\typings\angularjs
  24C: File  (---)   C:\Projetos\ProjetoMobile\.vscode\typings\cordova
  250: File  (---)   C:\Projetos\ProjetoMobile\.vscode\typings\cordova\plugins
  254: File  (---)   C:\Projetos\ProjetoMobile\.vscode\typings\ionic
  258: File  (---)   C:\Projetos\ProjetoMobile\.vscode\typings\jquery
  26C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\assets\www\js
  29C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www
  2A0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\cordova-js-src
  2A4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\cordova-js-src\android
  2A8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\cordova-js-src\plugin\android
  2AC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\js
  2B0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\js\audiencias
  2B8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\js\bin
  2BC: File  (---)   C:\Program Files\Microsoft VS Code\icudtl.dat
  2C0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\js\login
  2C8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\com.telerik.plugins.nativepagetransitions\www
  2D0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-camera\www
  2D4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-file\www
  2D8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-file\www\android
  2DC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-file\www\browser
  2E0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-file-transfer\www
  2E4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\cordova-plugin-statusbar\www
  2E8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\debug\www\plugins\net.ekuwang.cordova.plugin.statusbar\www
  2EC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www
  2F0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\cordova-js-src
  2F4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\cordova-js-src\android
  2F8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\cordova-js-src\plugin\android
  2FC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\js
  300: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\js\audiencias
  304: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\js\bin
  308: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\js\login
  30C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\com.telerik.plugins.nativepagetransitions\www

  310: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-camera\www
  314: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-file\www
  318: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-file\www\android
  31C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-file\www\browser
  320: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-file-transfer\www
  324: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\cordova-plugin-statusbar\www
  328: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\build\intermediates\assets\release\www\plugins\net.ekuwang.cordova.plugin.statusbar\www
  32C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova
  330: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\lib
  334: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\lib\builders
  338: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\abbrev
  33C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\ansi\examples
  340: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\ansi\examples\beep
  344: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\ansi\examples\clear
  348: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\ansi\examples\progress
  34C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\ansi\lib
  350: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\balanced-match
  354: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\balanced-match\test
  358: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\base64-js\bench
  35C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\base64-js\lib
  360: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\base64-js\test
  364: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\big-integer
  368: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\bplist-parser
  36C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\bplist-parser\test
  370: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\brace-expansion
  374: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\concat-map
  378: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\concat-map\example
  37C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\concat-map\test
  380: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common
  384: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src
  388: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src\ConfigChanges
  38C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser
  390: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src\CordovaError
  394: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src\PluginInfo
  398: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-common\src\util
  39C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-registry-mapper
  3A0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\cordova-registry-mapper\tests
  3A4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\elementtree\lib
  3A8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\elementtree\lib\parsers
  3AC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\elementtree\tests
  3B0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\glob
  3B4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\inflight
  3B8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\inherits
  3BC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash
  3C0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\array
  3C4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\chain
  3C8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\collection
  3CC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\date
  3D0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\function
  3D4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\internal
  3D8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\lang
  3DC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\math
  3E0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\number
  3E4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\object
  3E8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\string
  3EC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\lodash\utility
  3F0: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\minimatch
  3F4: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\nopt\bin
  3F8: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\nopt\examples
  3FC: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\nopt\lib
  400: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\nopt\test
  404: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\once
  408: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\os-homedir
  40C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\os-tmpdir
  410: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\osenv
  414: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\osenv\test
  418: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\path-is-absolute
  41C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\plist\dist
  420: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\plist\lib
  424: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\properties-parser
  428: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\properties-parser\test
  42C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\q
  430: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\sax\examples
  434: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\sax\lib
  438: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\sax\test
  43C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\semver
  440: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\semver\test
  444: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\shelljs
  448: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\shelljs\scripts
  44C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\shelljs\src
  450: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\underscore
  454: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\unorm\lib
  458: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\util-deprecate
  45C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\wrappy
  460: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\wrappy\test
  464: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\xmlbuilder\lib
  468: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\cordova\node_modules\xmldom
  46C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www
  470: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\cordova-js-src
  474: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\cordova-js-src\android
  478: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\cordova-js-src\plugin\android
  47C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\com.telerik.plugins.nativepagetransitions\www
  480: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-camera\www
  484: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-file\www
  488: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-file\www\android
  48C: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-file\www\browser
  490: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-file-transfer\www
  494: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\cordova-plugin-statusbar\www
  498: File  (---)   C:\Projetos\ProjetoMobile\platforms\android\platform_www\plugins\net.ekuwang.cordova.plugin.statusbar\www
  49C: File  (---)   C:\Projetos\ProjetoMobile\plugins\com.telerik.plugins.nativepagetransitions\adapters
  4A0: File  (---)   C:\Projetos\ProjetoMobile\plugins\com.telerik.plugins.nativepagetransitions\www
  4A4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\appium-tests\android
  4A8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\appium-tests\helpers
  4AC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\appium-tests\ios
  4B0: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\src\blackberry10
  4B4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\src\browser
  4B8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\src\firefoxos
  4BC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\src\windows
  4C0: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\tests
  4C4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\www
  4C8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\www\blackberry10\assets
  4CC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-camera\www\ios
  4D0: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\src\blackberry10
  4D4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\src\browser
  4D8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\src\firefoxos
  4DC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\src\windows
  4E0: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\tests
  4E4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www
  4E8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\android
  4EC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\blackberry10
  4F0: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\browser
  4F4: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\firefoxos
  4F8: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\ios
  4FC: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\osx
  500: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\ubuntu
  504: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file\www\wp
  508: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\src\windows
  50C: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\tests
  510: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\www
  514: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\www\blackberry10
  518: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\www\browser
  51C: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\www\firefoxos
  520: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-file-transfer\www\wp7
  524: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-statusbar\src\browser
  528: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-statusbar\src\windows
  52C: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-statusbar\tests
  530: File  (---)   C:\Projetos\ProjetoMobile\plugins\cordova-plugin-statusbar\www
  534: File  (---)   C:\Projetos\ProjetoMobile\plugins\net.ekuwang.cordova.plugin.statusbar\www
  538: File  (---)   C:\Projetos\ProjetoMobile\www\js
  53C: File  (---)   C:\Projetos\ProjetoMobile\www\js\audiencias
  540: File  (---)   C:\Projetos\ProjetoMobile\www\js\bin
  544: File  (---)   C:\Projetos\ProjetoMobile\www\js\login
  558: File  (---)   C:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib
  55C: File  (---)   C:\Projetos\ProjetoMobile
  560: File  (---)   C:\Projetos\ProjetoMobile
------------------------------------------------------------------------------

**Comment by dbaeumer** [comment] 2016-06-15 06:47
@Urahara can you add the process for one or two files which holdes the lock. Very interesting is the command line of that process.

**Comment by bpasero** [comment] 2016-06-22 08:42
@Urahara ping

**Comment by Urahara** [comment] 2016-06-22 11:22
@dbaeumer @bpasero you want file that have locked? Sorry i didn't understand.

**Comment by dbaeumer** [comment] 2016-06-22 11:56
We need the command line of the Code.exe holding a lock on one of the files. To do so select one of the file handles, which reveals it on the process explorer main window. Then select properties from the context menu and let us know about the command line.

**Comment by Urahara** [comment] 2016-06-22 12:56
@dbaeumer done.

"C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\utils\electronForkStart" "c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js"

**Comment by dbaeumer** [comment] 2016-06-23 07:41
This is a TS server issues tracked here: https://github.com/Microsoft/TypeScript/issues/7762 and will be fixed in the next tsserver release.

If this is blocking for you, you can try to use the tsserver from the TS nightly build which already contains a fix for this. See https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions on how to do this.

**Closed by dbaeumer** 2016-06-23 07:41 UTC
Labels: bug, js, needs more info

**Comment by Urahara** [comment] 2016-06-23 12:38
@dbaeumer Thanks! :smiley:
