### ISSUE TITLE
Raw string with backslash should not highlight letters following \ 

### ISSUE THREAD

**Issue by parsh78** [microsoft/vscode#78140] opened 2019-07-30 03:05 UTC
Issue Type: <b>Bug</b>

A raw string like below, is highlighting h and w and p and r. 

file_name = r'C:\hello\world\python_scripts\results\{0}_auto_test_results.log'

It should not.

Thank you.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.6.5
python-extension-pack|don|1.6.0
gc-excelviewer|Gra|2.1.32
MagicPython|mag|1.1.0
python|ms-|2019.6.24221
vscodeintellicode|Vis|1.1.8

</details>

**Comment by alexr00** [comment] 2019-07-30 09:41
@parsh78 what language is this?

**Comment by parsh78** [comment] 2019-07-30 13:38
This is Python.
________________________________

**Comment by alexr00** [comment] 2019-07-31 10:10
Duplicate of https://github.com/MagicStack/MagicPython/issues/155. Can you do as suggested [here](https://github.com/MagicStack/MagicPython/issues/155#issuecomment-516370689)?

**Closed by alexr00** 2019-07-31 10:10 UTC
Labels: needs more info
