### ISSUE TITLE
Terminal: pressing Escape closes the terminal panel

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7089] opened 2016-06-01 09:37 UTC
- VSCode Version: 1.2.0 Insider
- OS Version: Windows 10

Steps to Reproduce:

1. open the terminal panel
2. type some text
3. press Escape

What happens: the text is removed (that's expected), and the terminal panel is immediately closed (unexpected).

**Comment by Tyriar** [comment] 2016-06-01 17:42
Duplicate of #6455, will be coming in 1.3.0

**Closed by Tyriar** 2016-06-01 17:42 UTC
