### ISSUE TITLE
Since version 1.66.0-1648620611 code tries to store authentication information

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode#146553] opened 2022-04-01 15:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0-1648620611
- OS Version: Ubuntu Focal 20.04

Steps to Reproduce:

1. Start code
2. Message pops up "Writing login information to the keychain failed with error ..."

Until the update to version 1.66.0-1648620611 Code did not try to write anything to the keychain. I don't want it writing anything to the keychain. I'm not allowing it to write anything to the keychain. I have not intentionally enabled any online services in Code that would require it to store login information.

**Comment by karabaja4** [comment] 2022-04-02 04:58
Same issue here on Arch Linux.

I don't want to have Visual Studio Code to integrate or write anything to the OS keychain.

With 1.66.0, a message pops up (probably due to having no gnome-keyring or dbus running):
```
Writing login information to the keychain failed with error 'Unknown or unsupported transport “disabled” for address “disabled:”'.
```
and there is no way to avoid it, even though I don't use Settings Sync, GitHub integration or anything else that would require a keychain.

**Comment by reporter123** [comment] 2022-04-05 19:18
gnome-keyring is indeed the service code expects to be running. This is an invalid assumption since kubuntu does not use gnome-keyring in the first place.

**Comment by TylerLeonhardt** [comment] 2022-04-05 19:56
Just to give you all some context. The auth provider isn't expecting `gnome-keyring` it's expecting the presence of any `libsecret` based keyring. More info for that here: https://github.com/microsoft/vscode/issues/104319#issuecomment-1057588052

The issue is that we use to only check if a keyring was available if/when you attempt to interact with the keyring but I changed it as a result of some other work to check at startup.

I need to rework this a bit here to not have that `findCredentials` line:
https://github.com/microsoft/vscode/blob/f5d9ed8acaaca8c0b08910020473eda88a5a2b97/src/vs/platform/credentials/electron-main/credentialsMainService.ts#L42

As a workaround you can launch vscode with `--disable-keytar`.

**Comment by mbenkmann** [comment] 2022-04-05 20:55
Thanks for the workaround 👍

**Comment by TylerLeonhardt** [comment] 2022-04-14 19:23
Ok! You should no longer see the notification at start up. You will see it once you attempt to log into an account for whatever reason or if an extension attempts to store something using the secret storage or keytar extension API.

This will be in insiders tomorrow and stable early next month.

**Comment by TylerLeonhardt** [comment] 2022-04-25 21:38
@mbenkmann @reporter123 @karabaja4 can one of you confirm that you no longer see this notification on VS Code Insiders?

**Comment by TylerLeonhardt** [comment] 2022-04-25 21:40
Verification steps:

* Install latest vscode insiders on a Linux machine that doesn't have the `gnome-keyring` installed (if you grab a distro that uses KDE as the default, that should be a good one to test on)
* At start up, you shouldn't see a notification about the keyring
* Now log in with GitHub for settings sync or an extension
* You should see a notification that points you to troubleshooting docs

**Comment by ntrf** [comment] 2022-04-27 10:15
I've tried the Insiders version. Notification no longer appears on start, but it didn't appear after configuring settings sync either. No entry was created in KDE Wallet or anywhere else (no modified files). It seems that auth token was not stored anywhere. Upon reloading, Accounts button on the sidebar shows notification to sign in. These are the log messages after restart:

```
[2022-04-27 13:10:04.301] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-04-27 13:10:04.301] [settingssync] [info] Auto Sync is enabled.
[2022-04-27 13:10:04.301] [settingssync] [info] Auto Sync: Suspended until auth token is available.
```

Code Version: Insiders 410fe0fc from Snap store

Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-40-generic (64-bit)

**Comment by TylerLeonhardt** [comment] 2022-04-27 21:55
@ntrf anything in the `Log (Main)` Output channel?

**Comment by ntrf** [comment] 2022-05-02 09:42
Sorry for the delay. I've collected all the relevant non-empty log files into this gist: https://gist.github.com/ntrf/785d9027840962077bde74eb4bfb50c5

It's the continuation of the same run:

* Settings sync was configured in the prior session,
* VSCode was restarted (full restart, not just `Reload Window`),
* Settings sync fails,
* `Settings Sync: Configure` -> `github` invoked manually,
* Github tab opens in browser and immediately redirects to VSCode,
* Settings sync works.

Nothing of interest in "Log (Main)", but there are errors in github authentication extension log.

**Comment by TylerLeonhardt** [comment] 2022-05-02 16:35
Thank you SO much @ntrf! That was incredibly helpful. I have a PR out to fix this now:
https://github.com/microsoft/vscode/pull/148567

I (or maybe a bot) will let you know when this is in insiders.

**Comment by TylerLeonhardt** [comment] 2022-05-02 19:01
fixed in that PR

**Closed by TylerLeonhardt** 2022-05-02 19:01 UTC
Labels: bug, candidate, authentication

**Comment by TylerLeonhardt** [comment] 2022-05-03 16:12
@ntrf can you verify that this is fixed in the latest insiders?

**Comment by ntrf** [comment] 2022-05-04 15:04
Looks good to me.

1. Starting the editor with Settings Sync Off -- no notifications displayed
2. After passing github authentication URL to VSCode -- notification pops up: `Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files` with Troubleshooting Guide button. Accounts button shows menu with `Github` listed.
3. After restarting shows no additional notifications. Accounts button works, but shows "You are not signed in" in the menu. Setting Sync is shown as enabled, shows "Last synched: 8 mins ago" in Settings editor
4. Executing `Settings Sync: Turn Off` disables Settings Sync and it persists through restarts.
5. Selecting `Accounts` -> `Github` -> `Sign Out` after login shows `Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown` notification again. This is only possible immediately after interactive sign in. After restart account is never signed in.

Version: 1.67.0-insider
Commit: 3159d61ccf5150764f7742f098d76872e3114dcb
Date: 2022-05-04T00:09:21.877Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-40-generic snap

**Comment by TylerLeonhardt** [comment] 2022-05-04 17:10
Thank you for going through that @ntrf!

**Comment by ChasingSingularity** [comment] 2022-06-08 12:52
So is the issue solved because i am getting it in vscode and not edge

**Comment by TylerLeonhardt** [comment] 2022-06-08 14:54
@ChasingSingularity can you get a new issue going and share a screenshot of what you're seeing?

I want to keep this issue separate since it's been totally closed out.

**Comment by yingyi666** [comment] 2022-06-16 16:00
Sorry, I also encountered the same problem when using vscode for github login synchronization, which prevented me from syncing my settings and using GitHub Copilot

I was prompted with the same message,
```
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by yingyi666** [comment] 2022-06-16 16:01
The system I use is manjaro kde

**Comment by yingyi666** [comment] 2022-06-16 16:06
I tried to install gnome-keyring on my computer, I can log in normally, but I don't want to install gnome tools in kde, is there any other solution?

**Comment by trapper2hin** [comment] 2022-06-16 16:10
No

**Comment by TylerLeonhardt** [comment] 2022-06-16 20:46
@yingyi666 follow this thread closely: https://github.com/microsoft/vscode/issues/104319#issuecomment-1058254378
