### ISSUE TITLE
Naming incorrectly

### ISSUE THREAD

**Issue by Camus10** [microsoft/vscode#113337] opened 2020-12-23 11:53 UTC
I named my file as Staircase.js then it names on folder (left files list on folder) as Staircase.js too. But on my title file, it names stairCase.js (title working file). Actually there is no problem about compiling code. Just Naming Bug.
![Bug Naming Visual Studio Code](https://user-images.githubusercontent.com/70552281/102993495-d8fb1a80-454f-11eb-870f-48b1283655e4.png)

**Comment by isidorn** [comment] 2021-01-04 11:36
Duplicate of case sensitiviy on case insensitive os issue. You can search for it.

**Closed by isidorn** 2021-01-04 11:36 UTC
Labels: *duplicate
