### ISSUE TITLE
Multiline Find & Replace finds multiline string but substitutes $1 literally when replacing

### ISSUE THREAD

**Issue by TSMMark** [microsoft/vscode#80732] opened 2019-09-11 17:38 UTC
Possible related issue #63297

- VSCode Version: 1.38.0
- OS Version: Mac OSX 10.14.5

Steps to Reproduce:

1. Search for a multiline pattern with a match group
    e.g.
    ```
    <Fragment>([\s\S\r]*)</Fragment>
    ```
2. Enter replace with $1 
    e.g.
    ```
    <>$1</>
    ```
3. Run the replace and see that you get a literal `$1` as the replace string

**Comment by TSMMark** [comment] 2019-09-13 14:31
The bug is present in in Search in Files: `Ctrl+Shift+F` / `Cmd+Shift+F`

Your question prompted me to try the same in Find in File `Ctrl+F`, and the bug is not present there! I guess I had unconsciously assumed they were backed by the same code. Good to know in case I need to work around it for now. Thanks @alexandrudima!

**Comment by miguel-bluefox** [comment] 2019-09-13 18:50
Just tried it and got the same issue. 

![https://i.imgur.com/rd39fnN.png](https://i.imgur.com/rd39fnN.png)

If it works with Find in File but not in Search in Files, then maybe porting the code from Find in File over would be the easiest way to go about this? (Even better, merging the two so they use the same functionality/methods).

**Comment by roblourens** [comment] 2019-09-15 19:42
Dupe of https://github.com/microsoft/vscode/issues/80667

**Closed by roblourens** 2019-09-15 19:42 UTC
Labels: needs more info

**Comment by TSMMark** [comment] 2019-09-16 14:15
Fixed in 57f485539ce2aa53c9f60e60bfdb47ae93f5d5f1

Thanks!
