### ISSUE TITLE
Launching multiple debugger sessions

### ISSUE THREAD

**Issue by Disane87** [Microsoft/vscode#38864] opened 2017-11-21 10:38 UTC
Actually I have a workspace with multiple folders. For debugging my application, I need to start an API and my Website via grunt tasks. Now I want to start the debug-session with the launch.json and compound config:

launch.json for website:
```js
{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Site",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:82/landing",
            "sourceMaps": false,
            "webRoot": "/www",
            "runtimeArgs": [
                "--remote-debugging-port=9222"
            ],
            "preLaunchTask": "grunt: serve"
        }
    ]
}
```

launch.json for api:

```js
{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Start API and XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "preLaunchTask": "grunt: serve",
        }
    ]
}
```

For both I need to execute the grunt tasks "serve".
How can I achive a compound launch, whoch executes "preLaunchTasks" in different folders.

My workspace structur looks like this:
![image](https://user-images.githubusercontent.com/956158/33068096-85ba7b86-ceb0-11e7-903f-2a0ffd41e980.png)

**Comment by weinand** [comment] 2017-11-21 10:42
Duplicate of #38134

**Closed** 2017-11-21 10:41 UTC
Labels: *duplicate, debug
