### ISSUE TITLE
Unmodified files are marked as changed

### ISSUE THREAD

**Issue by ostap1010** [Microsoft/vscode#17606] opened 2016-12-20 12:24 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|debugger-for-chrome|msjsdiag|2.4.1|

---

Steps to Reproduce:

1. Open any file
Result: it is marked as changed
Expected result: Unmodified file should not be marked as changed

**Comment by egamma** [comment] 2016-12-20 16:22
@ostap1010 I'm unable to reproduce this behaviour.

Can you reproduce this behaviour when you have all extensions disabled? You can disable the extensions in the Extensions viewlet.

**Comment by ostap1010** [comment] 2016-12-20 17:19
Yes, sorry, works ok without extensions. The problem was in editorconfig extension.

**Comment by egamma** [comment] 2016-12-20 20:22
@ostap1010 thanks for verifying. I assume you have reported an issue against the editorconfig extension. I'm closing this one.

**Closed by egamma** 2016-12-20 20:22 UTC
Labels: needs more info
