### ISSUE TITLE
Feature Request: api to custom files sort order at the sidebar

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#12345] opened 2016-09-21 01:11 UTC
- VSCode Version: 1.5.2
- OS Version: mac

**Comment by chrmarti** [comment] 2016-09-21 15:51
What's the use case you're after?

**Comment by atian25** [comment] 2016-09-21 16:05
I want to write a plugin to let some lib in node_modules to show at top, because need to explore them frequently

**Comment by Zyphrax** [comment] 2016-09-23 22:23
It would be great if VS Code would allow a custom sort of the files view.

In TypeScript, module resolution automatically processes index.ts files. It would be great to change the sorting so that the index.ts file is at the top.

For example:
```
[] reducers
   estimates.ts
   index.ts
   locations.ts
```

Would become:
```
[] reducers
   index.ts
   estimates.ts
   locations.ts
```

**Comment by denizdogan** [comment] 2017-04-25 10:03
I'm also looking for this functionality, I'd really like it if VSCode could put `index.js` at the top and `README.md` at the bottom, for example!

**Comment by isidorn** [comment] 2017-11-17 10:55
Duplicate of https://github.com/Microsoft/vscode/issues/27286

**Closed by isidorn** 2017-11-17 10:55 UTC
Labels: feature-request, file-explorer
