### ISSUE TITLE
Keyboard shortcut system crash

### ISSUE THREAD

**Issue by Caalan** [Microsoft/vscode#45198] opened 2018-03-07 11:41 UTC
### Issue Type
Bug

### Description

ctrl+alt+12 with C/C++ extention is keyboard shortcut for peek declaration. It is also shortcut for switching virtual console in ubuntu. I suspect conflict there. It hung whole system and hard reset is required. Tested on two PCs (one got Ubuntu with cinnamone, on with Ubuntu with unity). 

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.37GB (1.55GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.0.2
cpptools|ms-|0.15.0
partial-diff|ryu|0.5.1

</details>
Reproduces only with extensions

**Comment by Caalan** [comment] 2018-03-08 06:45
No, after doing that there is no more problem. Problem is with default shortcut assignment and default Ubuntu shortcut collision I suppose.

**Comment by kieferrm** [comment] 2018-03-09 19:11
@Caalan what I hear you saying is that
- When you assign `crl+alt+12` to a built-in command no crash happens. However, the keyboard short-cut conflict still exists since `crl+alt+12` is bound to a VS Code command as well as by Ubuntu.
- When `crl+alt+12` is assigned to `Show declaration` in the C++ extension, your system crashes.
- When you bind a different shortcut to `Show declaration` in the C++ extension, your system is fine.
Correct?

**Comment by Caalan** [comment] 2018-03-10 11:25
Yes indeed, everything is correct :)

**Comment by kieferrm** [comment] 2018-03-11 21:55
@Tyriar any idea?

**Comment by Tyriar** [comment] 2018-03-23 22:16
@Caalan I can't reproduce without the extension so my guess is it's caused by the C++ extension calling out to some binary at the same time the virtual console is pulled up is causing issues. You might want to follow this up on https://github.com/Microsoft/vscode-cpptools

**Closed** 2018-03-23 22:16 UTC
Labels: *caused-by-extension, linux
