### ISSUE TITLE
Built in color picker stopped working after upgrading

### ISSUE THREAD

**Issue by adstechappdev** [Microsoft/vscode#45084] opened 2018-03-05 20:09 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment] 2018-03-06 00:47
Pls provide concrete steps to reproduce the issue on the latest stable or on the current insider build. Pls see https://aka.ms/vscodeissuereporting.

**Comment by adstechappdev** [comment] 2018-03-06 18:00
Sure.  I have VS Code 64 bit installed on 3 different VMs.  Two upgraded to latest and both had the issue, one not.

1) Upgrade VS Code
2) In .scss file, type background-color: red;
3) Hover over the color box to change the color - no color picker appears.

**Comment by kieferrm** [comment] 2018-03-09 19:05
You still get the color picker when you hover over the test rather than the box.

**Comment by rebornix** [comment] 2018-09-21 18:50
Duplicate of https://github.com/Microsoft/vscode/issues/40634, let's track it there.

**Closed** 2018-09-21 18:50 UTC
Labels: *duplicate, editor-contrib, under-discussion
