### ISSUE TITLE
Please give us Toolbar with icons

### ISSUE THREAD

**Issue by BenHayat** [Microsoft/vscode#59703] opened 2018-09-30 20:27 UTC
In VS Code's header, under the Menu line, could you please another toolbar of Icons for the most used functions, like Save File, Open File, and etc. Like Visual Studio. We need to be able to configure it ourselves to add/delete items.

**Comment by usernamehw** [comment] 2018-09-30 21:04
Duplicate of #41309

**Closed** 2018-09-30 21:16 UTC
