### ISSUE TITLE
Display multi-line errors in panel list

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13285] opened 2016-10-06 08:33 UTC
As shown in the picture below we are not displaying multi-line errors in the error list. I would expect that multi-line errors occupy the correct number of lines.

I know you are using the tree widget as the underlying implementation, so you can check the repl which does the same. Uses the tree but for elements that are multiple lines it [reserves additional lines](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L119).

I am passionate about removing the error zone widget and this is one of the rare things that the error list is missing which the error zone widget provides.

<img width="660" alt="screen shot 2016-10-06 at 10 26 14" src="https://cloud.githubusercontent.com/assets/1926584/19145597/f8da07ac-8baf-11e6-9497-41e3f868a2f0.png">

**Comment by sandy081** [comment] 2017-11-27 12:53
Duplicate of ##1927

**Closed by sandy081** 2017-11-27 12:53 UTC
Labels: error-list, feature-request
