### ISSUE TITLE
Login dialog does not go away (again)

### ISSUE THREAD

**Issue by OxfordGrid** [microsoft/vscode#105050] opened 2020-08-20 04:51 UTC
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

The same as:
https://github.com/microsoft/vscode/issues/97233
https://github.com/microsoft/vscode/issues/97199
only on v1.48

Steps to Reproduce:

1. Open VSCode
2. After a few minutes of work (random time) a dialog (I assume a proxy login dialog even though it doesn't have any title) appears
![image](https://user-images.githubusercontent.com/18425436/90718520-6f46d780-e2f5-11ea-846d-7aff21f1f2f0.png)
3. The dialog will NOT go away or show any signs of life independently what I do:
- enter correct credentials
- enter wrong credentials
- click cancel
4. The only way to get rid of it is to kill Code via Activity Monitor

PS: interesting thing - if I have multiple VSCode instances open then it appears only on first launched instance, but not the others
PS2: sometimes this dialog appears for the first time with the close button at the top left corner and the title VSCode. If I close it with this button then the second one appears immediately without the close button.

**Comment by gjsjohnmurray** [comment] 2020-08-20 05:22
/duplicate of #104603 and will be fixed in upcoming recovery release

**Closed** 2020-08-20 05:22 UTC
Labels: *duplicate
