### ISSUE TITLE
Text goes to alien search bar when writing commit message

### ISSUE THREAD

**Issue by SimiCode** [microsoft/vscode#93656] opened 2020-03-28 15:30 UTC
- VSCode Version: 1.42.2
- OS Version: Windows 10 Pro 18363.720

Steps to Reproduce:

1. Add a file change to staged commits
2. As the file is being added, Start writing your commit message
3. If the file staging finishes before you do, 
4. The rest of your commit message does not go into the commit message text box but rather another weird brown text box with no spaces added. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by SimiCode** [comment] 2020-03-28 15:31
- [ ] @[

1. 

- 

> ### _`[](url)`_

](url)

**Comment by askvortsov1** [comment] 2020-03-28 16:22
I can confirm this, it is quite annoying. I believe the root cause is that the git pane refreshes when a commit is staged, but if the cursor is active in the commit message box it ceases to be active there when the panel is refreshed.

**Comment by askvortsov1** [comment] 2020-03-30 00:32
Duplicate of https://github.com/microsoft/vscode/issues/92401

**Closed** 2020-03-31 15:11 UTC
