### ISSUE TITLE
Repeating git commands causing progress badge to constantly appear

### ISSUE THREAD

**Issue by JAK0723** [microsoft/vscode#173555] opened 2023-02-06 12:43 UTC
Type: <b>Bug</b>

I noticed the progress badge for the SCM tab in the activity seemed to be flickering so I checked the log and it seems to be repeating commands that produce "NotAGitRepository" errors. This seems to be happening because I have some files open that belong to git repos, while other files don't belong to git repos.

I was able to partially reproduce the issue with newly created directories, one of which was git repo, while the others were not. Oddly, the error did not constantly repeat itself. The error only repeated with my actual workspace, where I have files from several different repositories.

As a temporary solution I've set "git.showProgress" to false to disable the progress badge entirely. However, I'd much prefer to actually use the progress badge.

I've included a trace-level log from my attempt to reproduce the issue. I've also included a screen recording showing the problem.

<details>
<summary>Log</summary>

```
2023-02-06 23:26:22.044 [info] Log level: Trace
2023-02-06 23:26:22.044 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-02-06 23:26:22.044 [info] Using git "2.39.1.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2023-02-06 23:26:22.044 [trace] [swf] Scan workspace folders: [d:\Downloads\test1]
2023-02-06 23:26:22.044 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:26:22.044 [trace] [swsf] Scan workspace sub folders. autoRepositoryDetection=true
2023-02-06 23:26:22.044 [trace] [swsf] Workspace folder: d:\Downloads\test1
2023-02-06 23:26:22.044 [trace] Opening repository: d:\Downloads\test1
2023-02-06 23:26:22.044 [trace] [swsf] Workspace scan settings: repositoryScanMaxDepth=1; repositoryScanIgnoredFolders=[node_modules]; scanRepositories=[]
2023-02-06 23:26:22.044 [trace] [swsf] Workspace scan sub folders: []
2023-02-06 23:26:22.060 [info] > git rev-parse --show-toplevel [27ms]
2023-02-06 23:26:22.060 [trace] Repository root for path d:\Downloads\test1 is: d:\Downloads\test1
2023-02-06 23:26:22.087 [info] > git rev-parse --git-dir --git-common-dir [25ms]
2023-02-06 23:26:22.090 [info] Open repository: d:\Downloads\test1
2023-02-06 23:26:22.090 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:22.096 [info] No remotes found in the git config file.
2023-02-06 23:26:22.121 [info] > git config --get commit.template [27ms]
2023-02-06 23:26:22.122 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [27ms]
2023-02-06 23:26:22.127 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:22.153 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
2023-02-06 23:26:22.154 [trace] Operation end: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:22.188 [info] > git status -z -uall [63ms]
2023-02-06 23:26:22.189 [trace] Operation end: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:22.190 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:22.196 [info] No remotes found in the git config file.
2023-02-06 23:26:22.222 [info] > git config --get commit.template [29ms]
2023-02-06 23:26:22.223 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [27ms]
2023-02-06 23:26:22.228 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:22.256 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [28ms]
2023-02-06 23:26:22.256 [trace] Operation end: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:22.257 [info] > git status -z -uall [32ms]
2023-02-06 23:26:22.258 [trace] Operation end: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:22.274 [debug] [wt] Change: d:\Downloads\test1\.git\fsmonitor--daemon
2023-02-06 23:26:22.274 [debug] [wt] Change: d:\Downloads\test1\.git\fsmonitor--daemon\cookies
2023-02-06 23:26:22.274 [debug] [.git] Change: d:\Downloads\test1\.git\fsmonitor--daemon
2023-02-06 23:26:22.608 [trace] Operation start: CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:22.633 [info] > git check-ignore -v -z --stdin [25ms]
2023-02-06 23:26:22.634 [trace] Operation end: CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:23.280 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:23.286 [info] No remotes found in the git config file.
2023-02-06 23:26:23.329 [info] > git config --get commit.template [47ms]
2023-02-06 23:26:23.330 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [44ms]
2023-02-06 23:26:23.334 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:23.361 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [27ms]
2023-02-06 23:26:23.362 [trace] Operation end: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:23.362 [info] > git status -z -uall [30ms]
2023-02-06 23:26:23.363 [trace] Operation end: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-06 23:26:25.072 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:26:25.072 [trace] [svte] Repository for editor resource d:\Downloads\test1\readme1.txt already exists: d:\Downloads\test1
2023-02-06 23:26:25.281 [trace] Operation start: Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:25.283 [trace] Operation start: GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:25.309 [info] > git ls-files --stage -- D:\Downloads\test1\readme1.txt [26ms]
2023-02-06 23:26:25.309 [trace] Operation end: GetObjectDetails (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:25.309 [info] > git show --textconv :readme1.txt [28ms]
2023-02-06 23:26:25.310 [trace] Operation end: Show (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-06 23:26:29.799 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:26:29.880 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:26:29.880 [trace] [svte] Open repository for editor resource d:\Downloads\test2\readme2.txt
2023-02-06 23:26:29.884 [trace] Opening repository: d:\Downloads\test2
2023-02-06 23:26:29.928 [info] > git rev-parse --show-toplevel [44ms]
2023-02-06 23:26:29.928 [info] fatal: not a git repository (or any of the parent directories): .git
2023-02-06 23:26:29.929 [trace] Opening repository for path='d:\Downloads\test2' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
2023-02-06 23:26:36.458 [trace] [swf] Scan workspace folders: []
2023-02-06 23:26:39.544 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:26:39.545 [trace] [svte] Open repository for editor resource d:\Downloads\test2\readme2.txt
2023-02-06 23:26:39.547 [trace] Opening repository: d:\Downloads\test2
2023-02-06 23:26:39.575 [info] > git rev-parse --show-toplevel [29ms]
2023-02-06 23:26:39.576 [info] fatal: not a git repository (or any of the parent directories): .git
2023-02-06 23:26:39.576 [trace] Opening repository for path='d:\Downloads\test2' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
2023-02-06 23:27:38.695 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:27:38.773 [trace] [svte] Scan visible text editors. autoRepositoryDetection=true
2023-02-06 23:27:38.773 [trace] [svte] Open repository for editor resource d:\Downloads\test3\inner\readme3.txt
2023-02-06 23:27:38.776 [trace] Opening repository: d:\Downloads\test3\inner
2023-02-06 23:27:38.815 [info] > git rev-parse --show-toplevel [38ms]
2023-02-06 23:27:38.815 [info] fatal: not a git repository (or any of the parent directories): .git
2023-02-06 23:27:38.815 [trace] Opening repository for path='d:\Downloads\test3\inner' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
```

</details>

[Code_2023-02-06_23-22-27.webm](https://user-images.githubusercontent.com/29014804/216972708-cb2cef70-7e71-48ca-a212-77f0f6757bbf.webm)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.90GB (39.80GB free)|
|Process Argv|--crash-reporter-id 6e042173-714b-4856-9752-72ac64f95cfb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
ksp-cfg-support|al2|0.2.1
vscode-subtitles|ast|0.4.0
vscode-django|bat|1.10.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.19
overtype|DrM|0.4.7
shell-format|fox|7.2.2
vscode-graphql|Gra|0.8.5
vscode-graphql-syntax|Gra|1.0.6
twitch-chat-log-language|JAK|1.0.4
latex-workshop|Jam|9.6.1
vsc-python-indent|Kev|1.18.0
gnuplot|mam|1.0.5
vscode-autohotkey-plus-plus|mar|3.2.0
Kotlin|mat|1.7.1
rainbow-csv|mec|3.5.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
remote-containers|ms-|0.275.0
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.75.1
vscode-remote-extensionpack|ms-|0.23.0
powershell|ms-|2023.1.0
remote-explorer|ms-|0.2.0
gremlins|nho|0.26.0
subtitles-editor|pep|1.1.7
logcat-color|Rai|0.0.1
vscode-xml|red|0.24.0
vscode-fileutils|sle|3.10.0
code-spell-checker|str|2.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
pyind779cf:30657577
89544117:30613380
pythonsymbol12:30657548

```

</details>

**Comment by JAK0723** [comment] 2023-02-06 12:47
I just noticed #173513, which appears to describe this same issue, but from VS Code 1.74.3. I thought this problem was introduced with 1.75.0, but it may have been present in earlier versions and I never noticed until now.

**Comment by JAK0723** [comment] 2023-02-10 03:03
I've updated to 1.75.1 and the issue is still present, though I'm no longer getting the "NotAGitRepository" log message. I've included the log with the `--log trace --disable-extensions` flags.

<details>
<summary>Log</summary>

```
2023-02-10 13:58:37.322 [info] Log level: Trace
2023-02-10 13:58:37.322 [info] Validating found git in: "C:\Program Files\Git\cmd\git.exe"
2023-02-10 13:58:37.322 [info] Using git "2.39.1.windows.1" from "C:\Program Files\Git\cmd\git.exe"
2023-02-10 13:58:37.322 [trace] [swf] Scan workspace folders: [d:\Documents\personal-notes]
2023-02-10 13:58:37.322 [trace] [svte] Scan visible text editors. autoRepositoryDetection=subFolders
2023-02-10 13:58:37.322 [trace] [swsf] Scan workspace sub folders. autoRepositoryDetection=subFolders
2023-02-10 13:58:37.322 [trace] [swsf] Workspace folder: d:\Documents\personal-notes
2023-02-10 13:58:37.322 [trace] Opening repository: d:\Documents\personal-notes
2023-02-10 13:58:37.323 [trace] [swsf] Workspace scan settings: repositoryScanMaxDepth=1; repositoryScanIgnoredFolders=[node_modules]; scanRepositories=[]
2023-02-10 13:58:37.323 [trace] [swsf] Workspace scan sub folders: [d:\Documents\personal-notes\.vscode]
2023-02-10 13:58:37.374 [trace] [swf] Scan workspace folders: [d:\Documents\personal-notes]
2023-02-10 13:58:37.407 [info] > git rev-parse --show-toplevel [87ms]
2023-02-10 13:58:37.409 [trace] Repository root for path d:\Documents\personal-notes is: d:\Documents\personal-notes
2023-02-10 13:58:37.437 [info] > git rev-parse --git-dir --git-common-dir [28ms]
2023-02-10 13:58:37.441 [info] Open repository: d:\Documents\personal-notes
2023-02-10 13:58:37.441 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-10 13:58:37.444 [trace] Opening repository: d:\Documents\personal-notes\.vscode
2023-02-10 13:58:37.474 [info] > git rev-parse --show-toplevel [30ms]
2023-02-10 13:58:37.474 [trace] Repository root for path d:\Documents\personal-notes\.vscode is: d:\Documents\personal-notes
2023-02-10 13:58:37.474 [trace] Repository for path d:\Documents\personal-notes already exists
2023-02-10 13:58:37.474 [trace] Opening repository: d:\Documents\personal-notes
2023-02-10 13:58:37.474 [trace] Repository for path d:\Documents\personal-notes already exists
2023-02-10 13:58:37.477 [info] > git config --get commit.template [29ms]
2023-02-10 13:58:37.480 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [28ms]
2023-02-10 13:58:37.485 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:37.512 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [27ms]
2023-02-10 13:58:37.512 [trace] Operation end: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:37.513 [info] > git status -z -uall [30ms]
2023-02-10 13:58:37.515 [trace] Operation end: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-10 13:58:37.516 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-10 13:58:37.554 [info] > git config --get commit.template [35ms]
2023-02-10 13:58:37.555 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [33ms]
2023-02-10 13:58:37.560 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:37.587 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [27ms]
2023-02-10 13:58:37.588 [trace] Operation end: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:37.588 [info] > git status -z -uall [30ms]
2023-02-10 13:58:37.589 [trace] Operation end: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-10 13:58:37.597 [debug] [wt] Change: d:\Documents\personal-notes\.git\fsmonitor--daemon\cookies\2820-205
2023-02-10 13:58:37.717 [trace] [swf] Scan workspace folders: []
2023-02-10 13:58:37.722 [debug] [wt] Change: d:\Documents\personal-notes\.git\fsmonitor--daemon\cookies\2820-206
2023-02-10 13:58:37.953 [trace] Operation start: CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:37.977 [info] > git check-ignore -v -z --stdin [24ms]
2023-02-10 13:58:37.977 [trace] Operation end: CheckIgnore (blocking: false, readOnly: true; retry: false; showProgress: false)
2023-02-10 13:58:38.109 [debug] [wt] Change: d:\Documents\personal-notes\.git\fsmonitor--daemon\cookies\2820-207
2023-02-10 13:58:39.112 [trace] Operation start: Status (blocking: false, readOnly: false; retry: false; showProgress: true)
2023-02-10 13:58:39.141 [info] > git config --get commit.template [26ms]
2023-02-10 13:58:39.142 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/master refs/remotes/master [25ms]
2023-02-10 13:58:39.146 [trace] Operation start: GetRefs (blocking: false, readOnly: true; retry: false; showProgress: false)
```

</details>

**Comment by dunkyl** [comment] 2023-02-10 11:44
Reproduced also on 1.75.1.

In the short term, since this was driving me mad, I used the Hide Badge option.

**Comment by JAK0723** [comment] 2023-03-02 11:05
I've updated to 1.76.0 and the issue is still present.

**Comment by JAK0723** [comment] 2023-05-14 05:30
I've updated to 1.78.2 and I still have this problem.

**Comment by lszomoru** [comment] 2023-05-17 10:32
@JAK0723, I have recently fixed an issue very similar to this one. The fix is already included in the latest Insiders release. I will go ahead and optimistically close this issue. Please download the latest Insiders release and reopen the issue if you are still able to reproduce it. Thank you!

**Closed by lszomoru** 2023-05-17 10:32 UTC
Labels: bug, git
