### ISSUE TITLE
Constants are still colored differently with semantic highlighting off

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#95714] opened 2020-04-20 17:14 UTC
Issue Type: <b>Bug</b>

1. Turn off the `editor.semanticHighlighting` setting
2. View file with some constants in it:
<img width="687" alt="Screen Shot 2020-04-20 at 10 08 42 AM" src="https://user-images.githubusercontent.com/3672607/79779384-2f43f980-82ef-11ea-9251-747a8efd17f9.png">

I expected these to be blue as they are in stable.

VS Code version: Code - Insiders 1.45.0-insider (ec0d19789f89d4c25895f4a0cf364276cfb0c6ed, 2020-04-20T06:04:22.698Z)
OS version: Darwin x64 18.7.0

**Comment by IllusionMH** [comment] 2020-04-20 20:56
Duplicate of https://github.com/microsoft/vscode/issues/95346

**Comment by aeschli** [comment] 2020-04-22 09:30
duplicate of https://github.com/microsoft/vscode/issues/95346

**Closed by aeschli** 2020-04-22 09:30 UTC
