### ISSUE TITLE
Code blocks collapsing incorrectly at multi-line formatted strings

### ISSUE THREAD

**Issue by darkshoxx** [microsoft/vscode#129681] opened 2021-07-28 11:07 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Win 10 Edu 64 bit

Description:
Submitting this as a bug because it doesn't occur in a different editor.
I tend to collapse functions in my code, especially in longer files. However, VSCode will strictly collapse to the next indent of the same or lower height. 
But formatted strings (if you don't want to split them up into multiple strings and allocate more memory) start unindented after linebreaks. They cannot therefore be currently collapsed properly. 
What's even worse, if you try to collapse directly at the strings new line, it will swallow anything underneath, because it interprets that as "within the same block". 
I am aware of things like "text.dedent" but that is a hacky workaround, since it works in the other editor. The "solution" in the second print call in the first image is no good either, as can be seen by the printout.

Steps to Reproduce:

1. Open new python file.
2. Create something with an indent, like define a function. "def test():"
3. Within, print a formatted string with line indents, prefrably with the given linebreaks.
4. Write something in the lines underneath with the same or deeper indents.
5. Click the chevron next to print to collapse the print call, it will stop at the new line of the unindented string.
6. Click the chevron at the string, it will swallow anything below whole.
7. Finally, click the shevron at "def" to collapse the function. Likewise, it will stop at the new line of the string.
![A Steps 1-4](https://user-images.githubusercontent.com/43265727/127310940-ab9dbef8-fac8-4dc8-955e-7bf281653320.png)
![B Step 5](https://user-images.githubusercontent.com/43265727/127310943-27019ee7-333a-4797-a6ec-7f7834239737.png)
![C Step 6](https://user-images.githubusercontent.com/43265727/127310945-56dfecd0-cdbd-4e01-9522-f75e0f49f9ac.png)
![D Step 6 also](https://user-images.githubusercontent.com/43265727/127310947-6fcfdc61-b403-4546-9406-3d460982ceff.png)

Kind Regards

**Comment by aeschli** [comment] 2021-08-17 19:01
duplicate of https://github.com/microsoft/vscode-python/issues/1847

**Closed by aeschli** 2021-08-17 19:01 UTC
