### ISSUE TITLE
Cannot pass environment variable that is already defined in shell's rc file.

### ISSUE THREAD

**Issue by saml** [Microsoft/vscode#4779] opened 2016-03-29 21:29 UTC
- VSCode Version: 0.10.11
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Export a variable in your default shell  (`~/.zlogin` for zsh;  `~/.bash_login` for bash, for example. You can use `.bashrc` as well).

    ```sh
    export FOOBAR="1"
    ```

2. Pass different value of the same variable to VSCode.

    ```sh
    FOOBAR=2 code .
    ```

3.  VSCode uses value defined for login shell, not current session: 
    
    Help > Toggle Developer Tools. And in Console,  `process.env.FOOBAR`  gives "1"  when I expect "2".

It looks like VSCode executes default shell as login shell again before launching the program UI.

Being able to pass different values for existing environment variables greatly helps writing/testing extensions.

Related discussion:  https://github.com/Microsoft/vscode-go/issues/220#issuecomment-203092824

###### strace example:

```sh
$ strace -E GOPATH=1 -E FOOBAR=2 -s 1000000 -e verbose=execve -e abbrev=none ./.build/electron/electron  .
execve("./.build/electron/electron", ["./.build/electron/electron", "."], [... "GOPATH=1", ...]) # What I expected
...
read(62, "...\nGOPATH=/home/saml/go\n....")  # What is this?
...
```

**Comment by saml** [comment] 2016-03-30 03:24
Looks like this is the place that resets envvars:

https://github.com/Microsoft/vscode/blob/25ce394231a63cad030c804460bd957a1102d14e/src/vs/workbench/electron-main/main.ts#L252-L256
```ts
// On some platforms we need to manually read from the global environment variables
// and assign them to the process environment (e.g. when doubleclick app on Mac)
getUserEnvironment()
	.then(userEnv => {
		assign(process.env, userEnv);
```

https://github.com/Microsoft/vscode/blob/25ce394231a63cad030c804460bd957a1102d14e/src/vs/base/node/env.ts#L22
```ts
         let child = cp.spawn(process.env.SHELL, ['-ilc', 'env'], {
```

Do we really need to execute `$SHELL -c env` there?  Can we assume or check if `env` command exists and execute it?

```bash
$ GOPATH=1 env |grep GOPATH
GOPATH=1

$ GOPATH=1 $SHELL -c env |grep GOPATH
GOPATH=/home/saml/go
```

**Comment by Tyriar** [comment] 2016-03-30 16:34
@bpasero @joaomoreno any comment on why this is used over `process.env`? I just fixed an issue with it recently because multi-line variables weren't working.

**Comment by joaomoreno** [comment] 2016-05-24 09:05
Duplicate of #1033, fixed already.

**Closed by joaomoreno** 2016-05-24 09:05 UTC
Labels: bug
