### ISSUE TITLE
Negating TS/JS regex tests breaks the syntax highlightning

### ISSUE THREAD

**Issue by hexrcs** [microsoft/vscode#93490] opened 2020-03-26 13:43 UTC
- VSCode Version:  1.43.2
- OS Version: macOS 10.14.6

Steps to Reproduce:

In a TypeScript file,

1. write a simple regex test like `/^@?(\w){1,15}$/i.test(values.username)`
2. put a `!` in front of this regex test in order to negate the result - `!/^@?(\w){1,15}$/i.test(values.username)`

Now, the syntax highlighting of all code after this line will break, as shown in the screenshot below. Especially the `if` keyword, which should have the class name `mtk6`, now has the class name `mtk7` in devtools.

![image](https://user-images.githubusercontent.com/26751752/77653122-a647d580-6f6f-11ea-9a31-55d47867c04b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-03-26 16:53
Duplicate of https://github.com/microsoft/TypeScript-TmLanguage/issues/806

**Closed by mjbvz** 2020-03-26 16:53 UTC
Labels: new release
