### ISSUE TITLE
TSX code formatter behaves incorrectly after encountering type arguments

### ISSUE THREAD

**Issue by jakepearson** [Microsoft/vscode#9080] opened 2016-07-11 15:41 UTC
- VSCode Version: 1.3.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Switch theme to `dark+`
1. Create a `.tsx` file.
2. Paste in the following code:
``` typescript
interface InboxStateProps {
  items: Immutable.List<InboxItem>;
  replyingItems: ReplyingItems;
}

class Inbox extends React.Component<InboxProps, {}> {
  render() {
    return (
      <div className={ classes.inbox }>
        { this.getLoadingIndicator() }
        { cards }
      </div>
    );
  }
}
```
3. Most of the text below line 2 will be grey.
![](http://i.imgur.com/S9ASqr2.png)
4. Switching the file over to `typescript` language mode appears to solve the problem except for the `div` tags. I think that makes sense.

**Comment by aeschli** [comment] 2016-07-12 15:59
duplicate of #8045

**Comment by jakepearson** [comment] 2016-07-13 15:36
Awesome, thanks!

**Closed** 2016-07-14 20:54 UTC
