### ISSUE TITLE
Cannot save a new file under a filename if another file exists whose filename starts with the intended new name

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#137224] opened 2021-11-15 12:32 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Windows 10, Remote SSH to OpenSUSE Leap 15.2

Steps to Reproduce:

1. `touch bug.txt`
2. `code -r bug.txt`
3. Ctrl-Shift-S (File: Save As ...)
4. Now try to save this file under the name `bug` next to `bug.txt`.
5. VS Code will try (at least) to overwrite `bug.txt`:

![pYzKDtSKnC](https://user-images.githubusercontent.com/12128514/141782666-f37a9c05-e3ac-4fc3-a2f5-552dcf42df50.gif)

**Comment by alexr00** [comment] 2021-11-15 13:32
duplicate of https://github.com/microsoft/vscode/issues/135838

**Closed by alexr00** 2021-11-15 13:32 UTC
Labels: *duplicate, simple-file-dialog
