### ISSUE TITLE
[extensions] Quickpick enhancements

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#21244] opened 2017-02-23 04:31 UTC
- VSCode Version: `1.10.0-insider` 256d76fed7947e7289f921df10658d7a69233b65
- OS Version: macOS Sierra `10.12.3 (16D32)`

It would be great to have more control over a Quickpick. Here are some things I would love to have.

1. Stream or push items into a Quickpick (basically be able to show/add more items to the list as promises are resolved)
1. Update the placeholder dynamically
1. Control which item should be selected when shown
1. Add event for `right-arrow` press on an item, similar to the file access quickpick
1. Seed the inputbox with a value

**Comment by jrieken** [comment] 2017-02-23 08:46
dupe of https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Aapi+label%3Aquick-pick+assignee%3Ajrieken

**Closed by jrieken** 2017-02-23 08:46 UTC
Labels: feature-request

**Comment by eamodio** [comment] 2017-02-23 15:10
@jrieken only some of those are duped there.

I don't see these 3 on that list

1. Stream or push items into a Quickpick (basically be able to show/add more items to the list as promises are resolved)
1. Update the placeholder dynamically
1. Add event for right-arrow press on an item, similar to the file access quickpick

**Comment by jrieken** [comment] 2017-02-23 15:19
[Please file one issue per request/problem/bug](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests)
