### ISSUE TITLE
I would like to re-use the same cloned repo when using `Continue On` to desktop

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162031] opened 2022-09-27 18:02 UTC
Testing #161875

When I first used the feature, I chose to continue on desktop since I already had the repository cloned, then tried to use git in the terminal but realized that I could only use the git integration since I was working on a remote repository, rather than my local copy.

Then I tried `Clone and Continue on desktop`, selecting the same location, but that just creates another copy. So that command is really only useful once, and using it again on a very large repo would be a pain since it would redownload the entire thing

**Comment by amunger** [comment] 2022-09-27 20:16
I had another moment of confusion where I re-opened vscode, which automatically opened up my most recent workspace. The `File: open folder` command was behaving strangely, and took be a while to realize that it was because I was in a remote repository.

**Comment by joyceerhl** [comment] 2022-09-27 21:12
Fwiw, there are a few indicators that you're in a remote repository:
- the remote indicator in the bottom left corner in the status bar will say `[GitHub]`
- the workspace folder title will have `[GitHub]` as the workspace suffix

**Comment by joyceerhl** [comment] 2022-11-11 22:02
Duplicate of https://github.com/microsoft/vscode/issues/162031

**Closed by joyceerhl** 2022-11-11 22:02 UTC
Labels: feature-request

**Comment by amunger** [comment] 2022-11-11 22:11
@joyceerhl - you marked this as a duplicate of itself

**Comment by joyceerhl** [comment] 2022-11-12 00:06
Fixed, thanks!
