### ISSUE TITLE
Feature request: support creating folders when saving files in Remote Development mode

### ISSUE THREAD

**Issue by zhuowei** [microsoft/vscode#151961] opened 2022-06-13 16:51 UTC
When saving a file using Remote Development/SSH in VSCode, the save file dialog has no way to create a directory in the desired path if it doesn't exist. This is unlike saving a file locally, where macOS/Windows/Linux's native file picker allows creating folders.

For example:
- install the Remote Development pack
- ssh to a development machine
- create a new file
- choose File -> Save
- in the "Save As" dialog, enter a path that contains a directory that doesn't exist yet

Current: the dialog just shows "Please enter a path that exists":
<img width="601" alt="Screen Shot 2022-06-13 at 12 49 20 PM" src="https://user-images.githubusercontent.com/704768/173404583-3660ad4a-924b-4b65-a5fd-3524713173bf.png">
There's no button/option to create directories, and I would need to cancel the save, manually create directories, then save again.

Desired: the dialog should offer the user a button/prompt to create the directories that don't exist

**Comment by TylerLeonhardt** [comment] 2022-06-13 17:23
I can't remember if this is owned by @alexr00 or @bpasero

**Comment by alexr00** [comment] 2022-06-14 09:59
duplicate of https://github.com/microsoft/vscode/issues/71425

**Closed by alexr00** 2022-06-14 09:59 UTC
Labels: remote, simple-file-dialog
