### ISSUE TITLE
Not getting intellisense in .html file for type and Src value.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4629] opened 2016-03-23 22:14 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Create Asp .net core empty project in visual studio.
2. Add some directories under wwwroot folder for client code like JS.
3. Add new item to manage client lib and add bower.json file.
4. Add some client side lib in to bower.json under dependency section.

> ![image](https://cloud.githubusercontent.com/assets/17735796/14002399/19404f8e-f109-11e5-85fe-0b25c3b8b733.png)

5. Add index.html under view folder and add basic html code like below and save changes.
<!Doctype html>
<html>
<head>
    <title>Hello world</title>
</head>
<body>

</body>
</html>
6. Now launch VSCode and Open project folder.
7. Open index.html and try to add script section inside body.
<body>
<script type="text/javascript" src="JS/wwwroot/lib/angular/angular.js"></script>
</body>

Actual: Not getting any intellisense for
1. path for scr  like :
![image](https://cloud.githubusercontent.com/assets/17735796/14002236/e6c67908-f107-11e5-9b33-3fc3bcb791ed.png)

2. Value for type like: "text/javascript"
![image](https://cloud.githubusercontent.com/assets/17735796/14002230/dceac650-f107-11e5-892b-e57cc377d801.png)

3. closing script tag i.e. </script>
![image](https://cloud.githubusercontent.com/assets/17735796/14002111/f213d87e-f106-11e5-9cda-17a84c2355b5.png)

Expected: It should display values same like visual studio intellisense.

**Comment by aeschli** [comment] 2016-03-24 08:38
duplicate of #2037

**Closed by aeschli** 2016-03-24 08:38 UTC
