### ISSUE TITLE
Screen cheese in the middle of scrolling with sticky scroll

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#169042] opened 2022-12-13 19:56 UTC
<img width="599" alt="image" src="https://user-images.githubusercontent.com/6561887/207431435-c08dd5a7-fdaf-42da-8cc7-c4de82792023.png">

**Comment by andreamah** [comment] 2022-12-14 15:48
Repro steps (Windows 11, on insiders):
1. go to https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/src/vs/workbench/services/search/common/search.ts#L44 in the desktop version
2. right click `textSearch` -> "Go to Implementations"
3. 
<img width="918" alt="image" src="https://user-images.githubusercontent.com/31675041/207642545-e731a9e5-35aa-4f85-81dd-3dda79cd3ef2.png">

**Comment by jrieken** [comment] 2022-12-15 08:25
Closing as dupe of the theme bug. It doesn't seem like a theme color can prevent transparency (I know that we support the opposite)

/cc @aeschli in case I missed something

**Closed by jrieken** 2022-12-15 08:25 UTC
Labels: bug, editor-sticky-scroll
