### ISSUE TITLE
Reading from stdin fails on WSL 2

### ISSUE THREAD

**Issue by vbergbauer** [microsoft/vscode#99815] opened 2020-06-11 01:39 UTC
Issue Type: <b>Bug</b>

On WSL 2 (Ubuntu 20.04) On Windows 10 version 2004, if I pipe input from the console like this:
```bash
ps aux | grep code | code - 
```
I get an empty window (nothing in the tmp file)

On the other hand, piping from stdin does work correctly on WSL 1.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.90GB free)|
|Process Argv|--wait --skip-add-to-recently-opened --file-uri=vscode-remote://wsl+ubuntu2004/tmp/code-stdin-joj.txt --remote=wsl+ubuntu2004 --waitMarkerFilePath C:\Users\VBERGB~1\AppData\Local\Temp\nenrnajsa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu2004|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v5 @ 2.90GHz (8 x 2904)|
|Memory (System)|25.01GB (23.91GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
Go|gol|0.14.4
terraform|has|2.0.1
mermaid-markdown-syntax-highlighting|bpr|1.0.2
viml|dun|0.1.7
jq-syntax-highlighting|jq-|0.0.2
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-mscgen|msc|1.2.0
debugger-for-chrome|msj|4.12.8

</details>

**Comment by aeschli** [comment] 2020-06-26 16:03
It also works from the integrated terminal.

**Comment by aeschli** [comment] 2020-06-29 07:01
So far I haven't been able to find out why this doesn't work from WSL2. `process.stdio` doesn't get any data events, just a close.
I reproduce it with the server build, but not with un-minified sources nor with a stripped down sample program.

**Comment by vbergbauer** [comment] 2020-06-29 12:57
It could be a timing issue with the Linux file system notification?
This is my current workaround in bash:
```bash
c() {
  tmpfile=$(mktemp /tmp/c.XXXXXX)
  while IFS= read -r line; do
    printf "%s\n" "$line" >> $tmpfile
  done
  code $tmpfile
  rm $tmpfile
}
```

**Comment by bpasero** [comment] 2020-07-10 11:08
I pushed a fix in this area today: https://github.com/microsoft/vscode/commit/f7ef06c0fe2097a278e83155d7e03e8f8671b2de

Though this issue seems to be older (29d) and the regression I think only came in 2 weeks ago.

**Comment by aeschli** [comment] 2020-10-16 20:55
The problem is that other commands in the wsl code script steal the stdin.
Now I write the stdin early into a file

**Comment by connor4312** [comment] 2020-10-29 18:46
It seems like there's still a race. `ps aux` echoes quite a few things but it misses the first lines of the stdin (the number of lines that actually open varies)

![](https://memes.peet.io/img/20-10-503b67ca-a0a8-451e-a759-318bf108fa60.png)

**Closed** 2020-10-29 18:48 UTC
Labels: bug, remote, verification-found
