### ISSUE TITLE
Merge-conflict decoration text disappears in high-contrast theme

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27289] opened 2017-05-25 18:32 UTC
- VSCode Version: Code - Insiders 1.13.0-insider (755d45a10785bf5008f27e10a8d607c4443dbf0c, 2017-05-25T05:06:38.560Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

The '(Current change)' text disappears in the high-contrast theme, also in 1.12 with Better Merge. @aeschli Maybe the extension does something wrong? It's using opacity there.

**Comment by chrmarti** [comment] 2017-05-25 18:34
Dark+:
<img width="498" alt="screen shot 2017-05-25 at 11 33 14 am" src="https://cloud.githubusercontent.com/assets/9205389/26464838/fcf28e7e-413d-11e7-87f1-402d219adb31.png">

HC:
<img width="429" alt="screen shot 2017-05-25 at 11 32 54 am" src="https://cloud.githubusercontent.com/assets/9205389/26464845/03501ed0-413e-11e7-98c9-b8f9a0dc8c53.png">

**Comment by aeschli** [comment] 2017-05-25 22:32
The color is set to rgba(0, 0, 0, 0.7) [here](https://github.com/Microsoft/vscode/blob/master/extensions/merge-conflict/src/mergeDecorator.ts#L84). The HC background is #000, so it's black on black.

I'd suggest to use the color id `descriptionForeground` here. It's 0.7 from the workbench foreground color.

**Comment by aeschli** [comment] 2017-05-25 22:44
Actually, the problem is the `mix-blend-mode: difference` that is used in high contrast.

**Comment by chrmarti** [comment] 2017-05-25 23:16
`descriptionForeground` works well, thanks.

A little unexpected is how the foreground colors are rendered on the two headers in high contrast:
<img width="645" alt="screen shot 2017-05-25 at 4 09 24 pm" src="https://cloud.githubusercontent.com/assets/9205389/26474264/d560df60-4164-11e7-8b4c-c649999dfd1f.png">

And without `mix-blend-mode: difference`:
<img width="617" alt="screen shot 2017-05-25 at 4 14 52 pm" src="https://cloud.githubusercontent.com/assets/9205389/26474353/675e4e98-4165-11e7-9d9b-5403207d4118.png">

**Comment by aeschli** [comment] 2017-05-26 15:25
Yes, `mix-blend-mode: difference` makes things very unpredictable. For now we have to live with it.

**Closed by aeschli** 2017-05-26 15:25 UTC
