### ISSUE TITLE
[Feature Request] - Move integrated terminal to the top

### ISSUE THREAD

**Issue by d-cole** [Microsoft/vscode#70970] opened 2019-03-22 17:31 UTC
I believe it would be great if the integrated terminal could be dropped down from the top above the editor window! 

Many developers I know, myself included, spend a fair amount of time in the integrated terminal at the bottom of the screen. This means spending a lot of time gazing at the very bottom of the screen, increasing the toll of desk work on our necks and posture. If the terminal dropped down from the top the text would be in the middle of the monitor - excellent positioning for proper posture!

**Comment by usernamehw** [comment] 2019-03-22 18:22
Possible duplicate of #37877

**Comment by d-cole** [comment] 2019-03-22 18:37
> Possible duplicate of #37877

That is similar. This is roughly what I was imagining


<img width="1391" alt="Screen Shot 2019-03-22 at 2 34 24 PM" src="https://user-images.githubusercontent.com/12245101/54845528-f088dd80-4caf-11e9-9737-627348515cef.png">

**Comment by sbatten** [comment] 2019-03-22 21:37
/duplicate

@d-cole I think this is similar enough to be resolved as a dupe. Correct me if there is some major difference I am missing.

**Closed** 2019-03-22 21:37 UTC
Labels: *duplicate
