### ISSUE TITLE
File search giving insane results

### ISSUE THREAD

**Issue by NitroGhost** [Microsoft/vscode#29838] opened 2017-06-29 09:16 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|2.0.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|pgsql|doublefint|0.0.8|
|vscode-scss|mrmlnc|0.6.2|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.11.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|dust|nemesarial|0.0.1|
|vscode-docker|PeterJausovec|0.0.16|
|material-icon-theme|PKief|2.0.9|
|java|redhat|0.6.0|
|sass-indented|robinbentley|1.4.1|
|sonarlint-vscode|SonarSource|1.0.0|;

---

Steps to Reproduce:

1. ctrl-p
2. search file that has similar names
3. order of the search may come back in an insane order

I have checked this with my colleague who is also using VS Code, but his search gives sane results. I have tried running VS Code with `--disable-extensions` but the results are still borked. Is there a way to clear the indexing of the search?

Screenshot:
![search](http://i.imgur.com/VU7vD3C.png)

**Comment by jrieken** [comment] 2017-06-29 16:06
@roblourens I have nothing to do with this until someone adopts `fuzzyScore`

**Comment by roblourens** [comment] 2017-06-29 17:19
@chrmarti do you know where results are sorted by relevance?

**Comment by chrmarti** [comment] 2017-06-29 18:01
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/comparers.ts#L141

The problem is that the path is only used as a tiebreaker. Seems to be a duplicate of #25925.

**Closed** 2017-06-29 18:06 UTC
Labels: search
