### ISSUE TITLE
Watcher events not triggered when folder is renamed or deleted from VSCode

### ISSUE THREAD

**Issue by savpek** [microsoft/vscode#90746] opened 2020-02-15 09:21 UTC
During development of https://github.com/OmniSharp/omnisharp-roslyn/pull/1694 i tried to figure out why removal of folders didn't send any events for backend. Tracked down that on VsCode side file watched doesn't get triggered in two cases: when folder is renamed or deleted from vscode.

There are similar issues reported when files are handled outside of vscode (like `mv` command) but didn't find one that matches this case when directly made from vscode UI.

- VSCode Version: 1.42.1 c47d83b293181d9be64f27ff093689e8e7aed054 x64
- OS Version: Win10

Steps to Reproduce:

1.  Delete folder from VsCode (or rename folder)

![image](https://user-images.githubusercontent.com/481896/74585383-b7064280-4fe4-11ea-9028-ba42fee7e0dc.png)

What i expect to see is all files under folder gets `onDidDelete` from watcher, but nothing gets triggered. Similiar thing happen if i rename folder from vscode, no events triggered and any change to files under folder after that cause `onDidCreated` to trigger. On rename case i think i expect to see delete->create similar for file rename event.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2020-02-18 06:12
@savpek can you run VSCode with the verbose flag (code `--verbose` from command line) and check the output in developer tools around this file watcher:

![image](https://user-images.githubusercontent.com/900690/74708684-78a79800-521d-11ea-9e9c-ebd995615294.png)

When you do the delete, it should print a message unless there is a bug in the file watcher.

Here is what I see:

![Kapture 2020-02-18 at 7 12 05](https://user-images.githubusercontent.com/900690/74708868-01becf00-521e-11ea-9e4b-fc5e60dbf78b.gif)

**Comment by savpek** [comment] 2020-02-23 11:04
Debugged this bit deeper, indeed fie watcher gets triggered (log lines are shown etc) but glob patterns seems to work bit oddly:

Omnisharp-vscode uses glob pattern "**/*.*" to notice all filechanges at workspace `workspace.createFileSystemWatcher('**/*.*')`.

Lets think theres `/foo/bar/asd.cs` file where `/bar/` folder gets removed.

 When folder gets removed no file watcher event is triggered for `**/*.*` pattern. I think i except to see "removed /foo/bar/asd.cs" since it's matches pattern and similar events happen for update/create.

When folder gets removed with pattern `**/` event of removed folder `/foo/bar/` gets triggered. I think this is working as i except to see.

When folder gets removed with pattern `**/*` event of removed folder `/foo/bar/` gets triggered. But no event for file `/foo/bar/asd.cs`. I think here i except to see both `/foo/bar/` and `/foo/bar/asd.cs` since they match to pattern.

Is this by design or bug? I can fix that on extension side by figuring out files under removed folders but for me behavior feels bit strange 🤔

**Comment by bpasero** [comment] 2020-02-23 11:24
I think this is a duplicate of https://github.com/microsoft/vscode/issues/60813 then.

**Closed** 2020-03-01 11:39 UTC
Labels: file-watcher, needs more info
