### ISSUE TITLE
The issue of command line about automatic scroll

### ISSUE THREAD

**Issue by Yu-Che-Gao** [Microsoft/vscode#18387] opened 2017-01-11 05:12 UTC
- VSCode Version: 1.9.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Key in "ctrl+shift+`" and show the command line.
2. Key in some command.
3. When lines of command are more than visible lines of command, the scroll bar cannot scroll to bottom automatically sometimes.

**Comment by mjbvz** [comment] 2017-01-11 18:55
@Tyriar This sounds like it may be a duplicate of the issue you mentioned yesterday. Can you please take a look?

**Comment by Tyriar** [comment] 2017-01-11 19:03
Yes this should have been fixed in the insiders build released a few hours after the issue was filed.

**Closed by Tyriar** 2017-01-11 19:03 UTC
Labels: integrated-terminal
