### ISSUE TITLE
Consider to not close files when receiving delete events

### ISSUE THREAD

**Issue by dchw** [Microsoft/vscode#4862] opened 2016-04-01 15:33 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 Pro

What I Would Expect:

I would love it  if my files did not close, or if I got a warning that something bad happened before my files close.

Steps to Reproduce:

Preface: It happens in all sorts of circumstances, but this is the fastest way I have seen to reproduce it. It does involve installing a plugin, but this happens to me (and other members of my team) when we do not have any plugins running. It just happens less often, and we do not yet have an easy way to reproduce it beyond these steps.

1. Install the tslint plugin
2. Set `"tslint.configFile"` at the project level to reference a `tslint.json` within the project (mine is at the root of the project)
3. Open split view, one side being `tslint.json`, the other being some TypeScript in the same project.
4. Try changing and saving the rules, and going back to the code to see the linting rules affect the code.Do this multiple times, I move rather quickly between panes and edits.
5. Eventually, both sides of the split pane will close. Its worth noting that despite working with both files, `tslint.json` does not show up in the "Working Files" list, but the code file does.

There was a bug, #4542, where this was reported via files mounted over GVFS, but since it seems to be happening on Windows with local git repos, it may be more a more general issue, Here are some timestamped logs from when it happened last, Paths/Filenames are anonymized:

    csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 08:59:52.043 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 08:59:52.162 csharpWatcherService.ts:76 [File Watcher]  >> normalized [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 08:59:52.759 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\some-project\.git\index.lock
    2016-04-01 08:59:52.763 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\some-project\.git\index.lock
    2016-04-01 09:00:01.944 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 09:00:01.947 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 09:00:02.068 csharpWatcherService.ts:76 [File Watcher]  >> normalized [CHANGED] c:\Users\Some.User\src\some-project\tslint.json
    2016-04-01 09:00:02.757 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\some-project\.git\index.lock
    2016-04-01 09:00:02.760 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\some-project\.git\index.lock
    2016-04-01 09:00:02.761 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\some-project\.git\index
    2016-04-01 09:00:02.761 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\some-project\
    2016-04-01 09:00:02.879 csharpWatcherService.ts:76 [File Watcher]  >> normalized [DELETED] c:\Users\Some.User\src\some-project\
    2016-04-01 09:00:02.879 csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\some-project\.git\index.lock
    2016-04-01 09:00:02.879 csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\some-project\.git\index

**Comment by bpasero** [comment] 2016-04-03 07:53
Something seems to trigger a DELETE event on c:\Users\Some.User\src\some-project\. Can you share the workspace with me and the setup to reproduce?

**Comment by dchw** [comment] 2016-04-05 14:56
I can't send you a workspace, since all the code files in the workspace have a scary legal warning at the top of them. I _can_ provide you with logs and a more information (and easier repro steps) that do not need a workspace or any plugins. The error and corresponding logs look similar enough that it seems likely to be the same issue. Here is what I did:

1. Create a folder for a new project
2. Make a blank file in the project
3. Open the folder in VSC
4. Change the file in VSC
5. `git init` the folder
6. `git add -A` to add the file
7. The file should have closed in VSC, and is no longer showing as a working file

The above happens regardless of using the commandline, or the VSC Git GUI to stage your commit.   These logs were obtained without any plugins loaded. Here are the logs: 

    csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:45.006 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:55.049 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:55.050 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\gittest\.git\objects\1b\562f0e7ed75371bfdf55a5f2b700bc8885a3bf
    2016-04-05 08:48:55.051 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:55.051 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index
    2016-04-05 08:48:55.052 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\
    2016-04-05 08:48:55.164 csharpWatcherService.ts:76 [File Watcher]  >> normalized [DELETED] c:\Users\Some.User\src\gittest\
    2016-04-05 08:48:55.165 csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:55.165 csharpWatcherService.ts:76 [File Watcher]  >> normalized [CHANGED] c:\Users\Some.User\src\gittest\.git\objects\1b\562f0e7ed75371bfdf55a5f2b700bc8885a3bf
    2016-04-05 08:48:55.165 csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\gittest\.git\index
    2016-04-05 08:48:55.737 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 08:48:55.738 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\.git\index.lock

**Comment by bpasero** [comment] 2016-04-05 17:15
@dchw maybe related to the git version you are using? which one are you on?

**Comment by bpasero** [comment] 2016-04-05 17:16
@dchw also do you have any extensions installed? can you try with "code --disable-extensions"?

**Comment by dchw** [comment] 2016-04-05 17:29
@bpasero Here is the version of git I am using. I am using it from ConEmu (v. 150813g, 64-bit).

    $ git --version
    git version 2.7.0.windows.1

The same thing happens when extensions are disabled. Just to be thorough, here are logs doing the same thing using the command `code . --verbose --disable-extensions`:

    csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 11:26:47.917 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\gittest\.git\objects\bc\621a9d848be8912d1ad9dd1be8fd05d842524d
    2016-04-05 11:26:47.918 csharpWatcherService.ts:76 [File Watcher] [CHANGED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 11:26:47.918 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index
    2016-04-05 11:26:47.918 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\
    2016-04-05 11:26:47.972 csharpWatcherService.ts:76 [File Watcher] [ADDED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 11:26:47.975 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\.git\index.lock
    2016-04-05 11:26:48.097 csharpWatcherService.ts:76 [File Watcher]  >> normalized [DELETED] c:\Users\Some.User\src\gittest\
    2016-04-05 11:26:48.098 csharpWatcherService.ts:76 [File Watcher]  >> normalized [CHANGED] c:\Users\Some.User\src\gittest\.git\objects\bc\621a9d848be8912d1ad9dd1be8fd05d842524d
    2016-04-05 11:26:48.098 csharpWatcherService.ts:76 [File Watcher]  >> normalized [ADDED] c:\Users\Some.User\src\gittest\.git\index
    2016-04-05 11:26:57.706 csharpWatcherService.ts:76 [File Watcher] [DELETED] c:\Users\Some.User\src\gittest\.git\index.lock

**Comment by bpasero** [comment] 2016-04-05 18:04
I just tried to reproduce on Windows 7 with git 2.6.3 and cannot:
![untitled](https://cloud.githubusercontent.com/assets/900690/14292708/8e158576-fb69-11e5-8083-689f77d39b8b.gif)

**Comment by dchw** [comment] 2016-04-05 18:54
@bpasero Hmmm. That is  odd. I wonder if its something else in my environment, because following those exact steps in you gif causes the document to close on my machine (and also everyone on my team's machine). 

Any ideas on other environmental things that could be affecting this? I suspect AV, but company restrictions prevent me from turning it off.

**Comment by bpasero** [comment] 2016-04-05 18:59
Yes, it could be something like that. The only idea I have is to explicitly exclude the workspace folder from file watching (though that can cause other issues): Open settings and find the `files.watcherExclude` setting and fill in something like:

`files.watcherExclude: <path to workspace>: true`

**Comment by dchw** [comment] 2016-04-05 19:11
I can't seem to find that setting, is that a setting that isn't in 0.10.11? What are the expected issues you can run into when excluding the workspace folder?

**Comment by bpasero** [comment] 2016-04-05 19:30
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by dchw** [comment] 2016-04-05 19:41
Setting the workspace setting does seem to work, and prevents the documents from closing.

I'm still curious what else (besides the git integration) might be affected by turning this off?

**Comment by bpasero** [comment] 2016-04-06 08:35
@dchw are you actually opening `c:\Users\Some.User\src\gittest\` in VS Code or a parent directory?

Disabling file events has some impact:
* git will not update automatically for changes in that folder
* editor does not update for files changed outside
* explorer does not update for files changed outside

But this is all scoped to that one folder, should not happen for sub folders.

**Comment by dchw** [comment] 2016-04-06 14:26
@bpasero We do open `c:\Users\Some.User\src\gittest\` in VSCode. I guess that might be a tradeoff we have to make given the way t he company sets up our computers, if there is not a better solution/fix for us.

**Comment by bpasero** [comment] 2016-04-06 14:39
What puzzles me is how you manage to get the DELETE event on that folder, I am not able to reproduce this. A workaround on my end might be to just ignore such an event because I should not react on a DELETE on workspace root.

Do you ever see this issue in sub folders of the workspace?

**Comment by dchw** [comment] 2016-04-06 14:45
@bpasero Yes, we do. If I have a file like this: `c:\Users\Some.User\src\gittest\src\services\someFile.ts`, I can get VSCode to react the same (delete event + closed document in editor) with that file.

**Comment by bpasero** [comment] 2016-04-06 14:50
Ok so I assume some tool on your machine is firing delete events for folders. It is unclear to me what tool this could be but the way VS Code reacts to this is not good in your case. 

Best you can do in that case is to completly disable file events (by using a pattern like `files.watcherExclude: <path to workspace>/**: true`).

This will have drawbacks though but prevent the closing of editors.

For the future we might revisit this decision to close editors on file events, so I keep this issue open.

**Comment by JoyPeterson** [comment] 2016-04-16 01:29
@bpasero ,

I noticed in the video where you were trying to reproduce it that you were using a dos window.  both @dchw and I are using a git bash window.  There are several of us here that experience this problem and we are all using git bash (or some other bash shell) on Windows.  The bash environment is likely a factor.

**Comment by bpasero** [comment] 2016-04-16 07:42
Good point,

**Comment by bpasero** [comment] 2016-04-18 21:05
We decided today in our UX meeting that we will keep the behavior of closing files when they get deleted. We might revisit this in the future but for now this is as it is.

**Closed by bpasero** 2016-04-18 21:05 UTC
Labels: ux

**Comment by yomed** [comment] 2016-06-03 15:25
@bpasero Closing files when they get deleted will close that split view - it becomes quite annoying to constantly resplit the view when working with temporary files.

**Comment by bpasero** [comment] 2016-06-03 15:50
@yomed we plan to add a setting to allow for empty groups and then this should not be an issue anymore.
