### ISSUE TITLE
VSCode [Insider]: Source control bug in 31.05.2019 Release

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#74634] opened 2019-05-30 19:04 UTC
![](http://joxi.ru/5mdagKoS31jeD2?d=1)
![](http://joxi.ru/MAjxEnJijZnkGm?d=1)

- VSCode Version: v1.35.0-insider (2019-05-30T05:09:19.856Z)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Download release with this hash (e9c50663154c369a06355ce752b447af5b580dc3)
2. Try to commit something

_If you want reproduce second image, after first bug, try toggle left sidebar (close -> open)_

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-05-30 20:22
Duplicate of #74617

**Closed by mjbvz** 2019-05-30 20:22 UTC
