### ISSUE TITLE
Can't open a new window on different desktop/screen.

### ISSUE THREAD

**Issue by jimbomorrison** [Microsoft/vscode#70029] opened 2019-03-08 09:01 UTC
Issue Type: <b>Bug</b>

1. Open MSVSC on Mac screen §1
2. Open a second window and move it to §2
3. Close the window on screen §2 - you now have no windows, but still have focus of the menu bar.
4. Go "File" > "New Window" ... nothing happens.

Notes: 
@2. NB. At this point, on either screen you can successfully open more windows...
@4. NB. You can go to screen §1 (where there is an existing window), open a new window and that works...

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
vscode-eslint|dba|1.8.1
vscode-html-css|ecm|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
mysql-syntax|jak|1.3.1
vue|liu|0.1.5
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
php-formatter|Sop|0.2.4

</details>

**Comment by bpasero** [comment] 2019-03-11 10:34
If this reproduces, I would be happy for someone to look into this and possibly provide a fix or explanation 👍

**Comment by ginoheusdens** [comment] 2019-03-15 21:48
> If this reproduces, I would be happy for someone to look into this and possibly provide a fix or explanation 👍

I can reproduce this also on my machine. Build the vscode codebase but nothing obvious found in the logs so far.
When I use the new window command in the context menu of the dock icon it creates a new window properly. 
I'm not familiar with the code base, tried to set break points but nothing get's triggered when I click on the New window command.
If someone can give some advise where to start searching/debugging I can give it an other go?

**Comment by bpasero** [comment] 2019-03-17 07:36
@ginoheusdens `src/vs/platform/menubar/electron-main/menubar.ts` is what gets used for any usage of the menu on macOS, maybe go from there. Thanks.

**Comment by bpasero** [comment] 2019-03-25 11:03
@jimbomorrison I cannot reproduce this, here are my steps:
* have 2 monitors
* start Code and it opens on the primary monitor
* open a new empty window and move it to the second monitor
* close that window via the close button in the window toolbar
* at this point the menu on the second monitor shows up dimmed to me (almost disabled) and the first window on the primary monitor becomes active
* I can click on the menu in the second monitor (even though it shows up disabled) and select "New Window" and that opens a new window on that monitor

What is different?

**Comment by AmirS** [comment] 2019-03-28 23:24
@bpasero no need for 2 monitors. 

Create multiple macOS desktops in one monitor, move a second VSCode to the second desktop and then close second VSCode window. 

It seems like there is no active VSCode window at that point. But menu is not updated to use fallback handlers bacause the last window is not closed yet: 

`(this.windowsMainService.getWindowCount() === 0 && this.closedLastWindow)`

Duplicate of #63959.

**Comment by bpasero** [comment] 2019-03-29 07:16
Duplicate of #63959

**Closed by bpasero** 2019-03-29 07:16 UTC
Labels: bug, help wanted, needs more info
