### ISSUE TITLE
How to see all details of a type in VSCode popup when hovering over variable

### ISSUE THREAD

**Issue by doberkofler** [microsoft/vscode#146582] opened 2022-04-01 19:13 UTC
When hoovering over a TypeScript variable in VSCode a popup shows the type definition.
When the type is complex, the popup does not show all of the definition but rather uses an ellipsis sign to shorten the content.
The "Goto Type Definition" only works when the type is explicitly defined somewhere.
It would be most helpful to have an option that shows complete definition of a type?

**Comment by mjbvz** [comment] 2022-04-01 20:52
Duplicate of #94679

**Closed by mjbvz** 2022-04-01 20:52 UTC
