### ISSUE TITLE
How to get consent for multiple resource scopes at once in the microsoft authentication provider

### ISSUE THREAD

**Issue by billti** [microsoft/vscode#193311] opened 2023-09-17 19:18 UTC
Our extension <https://marketplace.visualstudio.com/items?itemName=quantum.qsharp-lang-vscode-dev> needs to make a few different `vscode.authentication.getSession` calls with slightly different params, as we first need to get the list of tenants, then sign-in to the specific tenant (for ARM sign-in), and once this is done requests a scope to a different resource (for `https://quantum.microsoft.com/`). This results in repeated pop-ups with "The extension ... wants to sign-in using Microsoft", followed by an account quick-pick for "The extension ... wants to access a Microsoft account"

Generally if writing code against AAD directly (e.g. using MSAL or similar) you would list the scopes you want to consent for in advance for the login and just consent once, then aquireToken for already consented scopes will silently work. I've tried various methods in the `getSession` API of listing scopes, having a static set and requesting '/.default', etc., all with no luck. Seems you need to call getSession for each unique combination of resource and tenant, and each results in a UX interactions for approval.

The result is our extension can prompt you 3 times for consent when trying to do one operation (connect to your Azure Quantum workspace). Is there a way to achieve this? Am I just approaching it wrong (current code at https://github.com/microsoft/qsharp/blob/main/vscode/src/azure/workspaceActions.ts#L19 )? Or is this just a limitation of the current API design?

Thanks!

**Comment by TylerLeonhardt** [comment] 2023-09-22 02:29
This should be fixed in https://github.com/microsoft/vscode/pull/193727 making it a dupe of https://github.com/microsoft/vscode/issues/184218

let me know tomorrow in Insiders if the issue persists!

**Comment by TylerLeonhardt** [comment] 2023-09-25 03:12
Try this for your `getAuthSession` function:

```ts
/**
* 
* @param {string[]} scopes 
*/
async function getAuthSession(scopes) {
    output.info("About to getSession for scopes", scopes.join(","));
    let session = await vscode.authentication.getSession(
        "microsoft",
        scopes,
        { silent: true }
    );
    if (!session) {
        session = await vscode.authentication.getSession(
            "microsoft",
            scopes,
            { createIfNone: true }
        );
    }
    output.info("Got session: ", session);
    return session;
}
```

All I did was add a silent call first. I think what you're hitting is... you're always using createIfNone: true which will show a pop up if there is no "session preference". Session Preference is really only a thing if the auth provider supports multiple accounts, which the Microsoft Auth Provider does... it's also decided by the user, not extensions. That said, if you use the silent flow, then we pick the last used account because a session is better than no session.

When I tried your https://github.com/billti/vsmin/tree/tokens with my work account, I only got one pop up.

I will say, I did get a 2nd pop up for my MSA, but that's expected, because my MSA doesn't have access to the Microsoft tenant.

**Comment by TylerLeonhardt** [comment] 2023-09-25 20:30
This, plus https://github.com/microsoft/vscode/pull/193727 gives you what you want :) re-marking as dupe.

**Closed by TylerLeonhardt** 2023-09-25 20:30 UTC
Labels: info-needed
