### ISSUE TITLE
save/open dialog has wrong scaling on high res displays

### ISSUE THREAD

**Issue by ardeego** [microsoft/vscode#89867] opened 2020-02-02 18:44 UTC
save/open dialog has wrong (font) scaling on high res displays, i.e. dpi is not scaled properly when system uses a 4k display for example and uses  windows based % up scaling.

**Comment by gjsjohnmurray** [comment] 2020-02-02 23:21
Probably a duplicate of #38976

**Comment by zenzoa** [comment] 2020-03-25 21:25
I'm seeing an unscaled file dialog only since the Feb update. I use Window 10 on remote desktop with a high-res display (a MacBook Pro 13" 2017).

**Closed** 2020-11-04 22:01 UTC
Labels: *duplicate
