### ISSUE TITLE
Right click menu is different

### ISSUE THREAD

**Issue by skumar1996** [microsoft/vscode#139093] opened 2021-12-14 14:23 UTC
Issue Type: <b>Bug</b>

When i used to right click on a functional component or any variable in react, i used to be able to go to definition, peek defnition etc. Now i see a completely different menu. A colleague of mine in the same environment and file is seeing a different right click menu. How can i revert to the previous right click menu?

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (18.22GB free)|
|Process Argv|--crash-reporter-id 1dd54252-04eb-49d0-a3c3-878770ff98bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
react-pure-to-class-vscode|ang|1.1.8
atlascode|atl|2.10.0
vscode-intelephense-client|bme|1.8.0
bracket-pair-colorizer-2|Coe|0.2.2
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
fortranbreaker|eki|0.0.4
vscode-great-icons|emm|2.1.79
font-switcher|eva|4.0.3
auto-close-tag|for|0.5.13
auto-rename-tag|for|0.1.9
vscode-pull-request-github|Git|0.34.1
terraform|has|2.17.0
vscode-styled-components|jpo|1.7.0
cpptools|ms-|1.7.1
vscode-yaml|red|1.2.2
autoimport|ste|1.5.4
errorlens|use|3.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315:30406435
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3t1:30407762

```

</details>

**Comment by IllusionMH** [comment] 2021-12-14 17:21
/needsMoreInfo

Please provide screenshots and code/configuration that causes this problem.
Are you sure you have proper language use/detected for file - JavaScript or TypeScript?

**Comment by skumar1996** [comment] 2021-12-14 17:24
Actually I think its because Typescript isnt configured correctly (anymore). I get the error on vscode startup: 'The ts language service died 5 tiems right after it got started fix'. When I come to report the issue to VScode they reccomend I upgrade my typescipt but the error persists even after upgrading. Im using TS version 4.6.0-dev.20211213. 

Below is my settings.json file:
`{
    "workbench.colorTheme": "Default Dark+",
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "workbench.iconTheme": "vscode-great-icons",
    "git.autofetch": true,
    "git.confirmSync": false,
    "git.suggestSmartCommit": false,
    "tabnine.experimentalAutoImports": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "yaml.schemas": {
        "file:///c%3A/Users/Sagar/.vscode/extensions/atlassian.atlascode-2.10.0/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
    "redhat.telemetry.enabled": true,
    "atlascode.jira.enabled": true,
    "atlascode.bitbucket.enabled": false,
    "atlascode.jira.jqlList": [
        {
            "id": "c88fab8b-bb59-4666-b0b3-7d87e4668db2",
            "enabled": true,
            "name": "My zenjob Issues",
            "query": "assignee = currentUser() AND resolution = Unresolved ORDER BY lastViewed DESC",
            "siteId": "649ae3eb-7dda-49e2-8d5d-84cbabdc6d99",
            "monitor": true
        }
    ],
    "atlascode.jira.lastCreateSiteAndProject": {
        "siteId": "649ae3eb-7dda-49e2-8d5d-84cbabdc6d99",
        "projectKey": "BI"
    },
    "atlascode.jira.todoIssues.triggers": [
        " TODO:",
        " BUG:",
        " FIXME:",
        " ISSUE:"
    ],
    "atlascode.jira.startWorkBranchTemplate.customPrefixes": [
        "[feat | fix]/XXX_CVS-"
    ],
    "atlascode.jira.explorer.refreshInterval": 5,
    "editor.fontFamily": "Consolas, Fira Code, 'Courier New', Garamond, monospace",
    "terminal.integrated.fontFamily": "monospace",
    "bracket-pair-colorizer-2.depreciation-notice": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": -1
}`

**Comment by mjbvz** [comment] 2021-12-15 00:45
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by skumar1996** [comment] 2021-12-15 10:50
Can we arrange a more secure method to exchange this information? Otherwise I can share the first error that occurs here anyways:

`Info 16   [11:40:03.740] Failed to load module 'typescript-styled-plugin' from c:/Users/Sagar/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules: Error: Could not resolve JS module 'typescript-styled-plugin' starting at 'c:/Users/Sagar/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules'. Looked in: c:/Users/Sagar/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-styled-plugin/package.json, c:/Users/Sagar/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-styled-plugin.js, c:/Users/Sagar/.vscode/extensions/jpoissonnier.vscode-styled-components-1....(cont.)`

**Comment by mjbvz** [comment] 2021-12-16 00:32
Ok, based on the error, this is a duplicate of #138794 (#139119 that you also opened)

**Closed by mjbvz** 2021-12-16 00:32 UTC
Labels: needs more info
