### ISSUE TITLE
Settings: gray out decoration comes too late

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31572] opened 2017-07-27 13:25 UTC
Refs: #31448

1. Multi root workspace, open folder settings
2. Add some forbiden setting like workbench.colorTheme, notice that it does not get greyed out. So now me as a user am puzzled why it is not being applied
3. If i press enter it gets greyed out or if I open the file again

I think you should update all decorations on every save event in the settings file

**Comment by sandy081** [comment] 2017-07-27 13:39
Duplicate of #31558

**Closed by sandy081** 2017-07-27 13:39 UTC
Labels: bug, settings
