### ISSUE TITLE
URL escaping is changed when using "Loaded Scripts" viewlet

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33712] opened 2017-09-01 22:58 UTC
chrome-debug sends ` {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":11,"source":{"name":"test2.js","path":"http://localhost:8080/out/client%20with%20space/test2.js","sourceReference":1001}}}}` (with `%20` escaped spaces)

I open test2.js from "loaded scripts" and set a breakpoint in it. VS Code sends `setBreakpoints({"source":{"path":"http://localhost:8080/out/client with space/test2.js","name":"test2.js"},"lines":[3],"breakpoints":[{"line":3}],"sourceModified":false})` (with unescaped spaces)

**Comment by isidorn** [comment] 2017-09-04 08:54
@roblourens can you please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1065) and check if the `normalize` call is removing escape codes.

An alternative would be that our internal [`uri`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L7) implementation somehow removes escape code.

Also assigning to @weinand since he is aware that some loaded scripts paths get incorectly transformed on windows

**Comment by roblourens** [comment] 2017-09-05 22:46
It's from URI, the 'path' goes through decodeURIComponent https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L189

I think it's hard to store a URI inside another URI and get the exact same representation out, because it will always be transformed in some way.

**Comment by isidorn** [comment] 2017-09-06 08:31
True, I do not see a straighforward way to fix this since we use uri everywhere inernally. 
I am open for suggestions on how to fix this

**Comment by weinand** [comment] 2017-09-06 09:56
I'll investigate...

**Comment by weinand** [comment] 2017-09-16 21:56
duplicate of #23194

**Closed by weinand** 2017-09-16 21:56 UTC
Labels: debug, needs more info
