### ISSUE TITLE
[CSS] provide color picker

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4329] opened 2016-03-16 17:22 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:
1.  Launch app and Open any CSS file 
2. Try to add some color property to any css class
3. Press # to get color options.

Actual: 
1. It is displaying only few color options.
2. When user insert some value with #code (like : #00) and then intellisense is not guiding.
![image](https://cloud.githubusercontent.com/assets/17735796/13821703/ecd9b15a-eb5f-11e5-9e8d-5173bc95c3fe.png)

Expected:
1. When user press # or #00 then it should display all the available color options.
1. I tried with Visual Studio 2015 and Visual studio is showing correct options and guiding properly to choose color with # code.
   ![image](https://cloud.githubusercontent.com/assets/17735796/13821794/4e1ae100-eb60-11e5-8d08-d88bc48868f7.png)

**Comment by h2u** [comment] 2016-03-17 09:00
Would be nice to have color picker like in Brackets.
![Image of Brackets Color picker](https://www.andrewmunsell.com/wp-content/uploads/2015/06/04.png)

**Comment by zbandhan** [comment] 2016-03-21 21:01
vs code might be more excellent than any other

**Comment by yisibl** [comment] 2016-06-08 06:10
I would like to be able to transplant the Chrome DevTools color picker to here.

**Comment by dstorey** [comment] 2016-06-08 15:43
@aeschli all browser inc. Edge 14 now include a native colour picker with input type="color", so it may be possible to just use that. For VS code it would presumably use the Chrome colour picker, which is the platform's native colour picker on Win and Mac. I'm not sure about Linux. It should work for Monaco too. In Edge we don't use the system colour picker but instead a custom touch friendly one built in HTML which has been made fully accessible.

**Comment by 0x4E69676874466F78** [comment] 2016-07-03 20:23
https://youtu.be/fO9TR5aYt0E?t=93

**Comment by smlombardi** [comment] 2016-10-05 18:10
Agree, a code picker like Brackets, Atom, Sublime or most other code editors.  I was shocked that Code had no such solution.

**Comment by Tyriar** [comment] 2016-10-28 16:42
A Windows only extension was released recently that provides a color picker which may be useful to some for the time being.

**Comment by anseki** [comment] 2017-02-20 18:44
Exactly one year ago, I published [Color Picker extension](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color).
That does not launch by pressing `#` but it might help you.

And the installation seems to fail sometimes in some environments.
I'd be glad if you report something to my repository.

**Comment by erichiller** [comment] 2017-02-27 21:27
I think this might be a duplicate of #625

**Comment by Tyriar** [comment] 2017-02-27 22:46
Thanks @erichiller

**Closed** 2017-02-27 22:46 UTC
Labels: css-less-sass, duplicate, feature-request

**Comment by andreszs** [comment] 2017-05-04 21:07
Forget about the color picker, just add the color preview circle please!
