### ISSUE TITLE
I cannot install extensions in my VS code.

### ISSUE THREAD

**Issue by snwlms** [Microsoft/vscode#38179] opened 2017-11-13 05:21 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment] 2017-11-13 05:51
@snwlms can you explain?

**Comment by snwlms** [comment] 2017-11-13 09:13
I'm new to coding and Visual Studio code.
I cannot install any extensions. 
![xhr error](https://user-images.githubusercontent.com/27275085/32717711-aef6f348-c880-11e7-8029-7eb0c34f5678.jpg)
I was hoping to install live preview for VS code to preview web page that i was making. I tried to download the extensions from the official website, but it also wont load.  Can you please help. Newbie here

**Comment by sandy081** [comment] 2017-11-13 11:30
@snwlms Is your system is behind any proxy ?

@joaomoreno FYI

**Comment by snwlms** [comment] 2017-11-13 12:12
No Proxy in chrome and mozilla.
Is there a proxy setting for VS Code?
![no proxy](https://user-images.githubusercontent.com/27275085/32725145-029573d0-c89a-11e7-9896-f364dcf6a2dd.jpg)

**Comment by snwlms** [comment] 2017-11-14 06:20
![image](https://user-images.githubusercontent.com/27275085/32765730-da62163c-c931-11e7-9747-5f82104138f6.png)
Should I re-install VS Code?
There's no install in the network tab.
Also Thank you for your time.

**Comment by joaomoreno** [comment] 2017-11-14 09:24
Oh, it seems you can't even search for them.

Hit <kbd>Ctrl Shift P</kbd> to open the command palette, type `Developer` and choose `Developer: Toggle Developer Tools`. In the devtools which opens, switch to the `Network` tab and retry searching. There should be a failed request there.

**Comment by snwlms** [comment] 2017-11-14 10:08
![image](https://user-images.githubusercontent.com/27275085/32774281-d34d2d94-c951-11e7-9781-9052f22862ae.png)
Same error!
XHR failed.
I really want to use VS Code.
:(

**Comment by sandy081** [comment] 2017-11-14 10:22
@snwlms Looks like the image still show Shared Process. Please do following steps and try

- Hit <kbd>Ctrl Shift P</kbd> to open the command palette, 
- Type `Developer` and choose `Developer: Toggle Developer Tools`. 
- switch to the `Network` tab in Dev tools.
- Search for extensions now

Capture what you see in the Dev tools.

**Comment by andrewisakov** [comment] 2017-11-15 06:44
Они её решать в конце концов собираются, эту проблему?
Медведю по вкусу эта балалайка, но вот расстроилась немного...

**Comment by sandy081** [comment] 2017-11-22 11:19
Closing this as the requested info is not provide. Please reopen with requested info.

**Closed by sandy081** 2017-11-22 11:19 UTC
Labels: extensions, needs more info

**Comment by dandy** [comment] 2017-11-22 11:59
https://github.com/Microsoft/vscode/issues/34385

**Comment by servicios-digitales** [comment] 2017-11-27 18:20
Trying to reopen this thread with the requested info (see image)

    VSCode Version: 1.18.1
    OS Version: Ubuntu 17.10

Steps to Reproduce:
- Open VS Code
- Click Extensions on the side bar
- Typed C#

Reproduces without extensions: Yes

I was searching for an extension after opening Dev tool on the Network tab
In my case I just finished installing VS Code, so no other extensions are installed

All my intends to upload a screenshot failed, so here's a link to what I see..

<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="https://i.imgur.com/mKTuFbI.png" alt="commercial photography locations"></a>

**Comment by xrmzju** [comment] 2017-11-28 07:58
i run into the same error too. and later i followed the guide of @sandy081, but i can not get any output in Network Tab, like @snwlms do.
