### ISSUE TITLE
Searching for newline characters in regex mode doesn't find any results

### ISSUE THREAD

**Issue by gaui** [Microsoft/vscode#6431] opened 2016-05-17 15:31 UTC
- VSCode Version: 1.1.1
- OS Version: Windows 7 Professional x64

Steps to Reproduce:

1. Create a document with multiple lines
2. Search for `\n`, `\r` or `\r\n` in regex mode.

What happens: When I try to search a multi-line text for `\n`, `\r` or `\r\n` in regex mode it doesn't find any results. However when I try to search for the same thing in Atom or Sublime, it finds results.

**Atom**

![Atom](http://i.imgur.com/81eEmcb.gif)

**Sublime Text 3**

![Sublime Text 3](http://i.imgur.com/tHLL08l.gif)

**VS Code**

![VS Code](http://i.imgur.com/qMni8Ch.gif)

**Comment by Tyriar** [comment] 2016-05-17 18:08
Duplicate of https://github.com/Microsoft/vscode/issues/313, be sure to :+1: it to help prioritize.

**Closed by Tyriar** 2016-05-17 18:08 UTC
