### ISSUE TITLE
Debug Console: ANSI color escapes garbled in console output

### ISSUE THREAD

**Issue by x0rsw1tch** [microsoft/vscode#230441] opened 2024-10-03 22:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0
- OS Version: Windows 11 23H2

![image](https://github.com/user-attachments/assets/fbf463d6-38f8-452b-8fb8-f3db2bb327c7)

This problem started after updating to newest version today.

Steps to Reproduce:

1. Create a launch configuration (mine is below, runs `pnpm run dev` launches Vite)
1. Run launch configuration
1. Look at Debug Console, output is garbles

```
    {
      "name": "Debug Vite/SvelteKit",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "env": {
        "NODE_OPTIONS": "--inspect --enable-source-maps"
      },
      "runtimeExecutable": "pnpm",
      "runtimeArgs": [
        "run",
        "dev"
      ]
    }
```

Cheers!

**Comment by GrahamMThomas** [comment] 2024-10-03 22:59
+1 

Happening in c# as well.

![image](https://github.com/user-attachments/assets/8d97f944-427e-4535-bb52-148353e623e5)

**Comment by ylazy** [comment] 2024-10-04 05:47
I'm facing this issue too. I had to roll back to 1.93.1.

**Comment by ogak-github** [comment] 2024-10-04 08:24
![image](https://github.com/user-attachments/assets/60b7175b-d77d-4fd2-8fa5-fdf3a0058409)

I thought it was my setting make it break. it because vscode version 1.94.0 ??

**Comment by mark-nicepants** [comment] 2024-10-04 08:25
Yes confirmed its the update :-) You can either revert or wait for a hotfix.

**Comment by afarellanoz77** [comment] 2024-10-04 08:41
waiting too

**Comment by Winens** [comment] 2024-10-04 10:00
![image](https://github.com/user-attachments/assets/2d522eb4-4dae-43c8-8c75-361130254205)
Same problem here.

**Comment by ssbarnea** [comment] 2024-10-04 15:47
The funny bit is the only application that I found to be affected by this is `gh` cli :) --- Where it does break the title of the pull requests when trying to create a new PR.

![](https://sbarnea.com/ss/Screen-Shot-2024-10-04-16-47-06.53.png)

The weird characters in the title are caused by the latest version of vscode. Clear regression, older versions worked fine.

**Comment by connor4312** [comment] 2024-10-04 15:48
@ssbarnea your issue is unrelated, this bug only impacts certain output displayed in the Debug Console

**Comment by connor4312** [comment] 2024-10-04 15:49
Fixed in js-debug nightly https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension which will be available in an hour or two. I'll also put this in as a candidate.

**Comment by Troyx21** [comment] 2024-10-05 14:23
Same issue with NestJS (Node, TS) project: TypeORM query logging became messed up.
**Please fix asap!**

![image](https://github.com/user-attachments/assets/69820ec4-dbee-4dda-a0e6-1891277eb1c1)

**Comment by sv-22** [comment] 2024-10-05 16:23
Same issue with GO.

This
```
package main

import "fmt"

const (
    Red    = "\033[31m"
    Green  = "\033[32m"
    Yellow = "\033[33m"
    Blue   = "\033[34m"
    Reset  = "\033[0m"
)

func main() {
    fmt.Println(Red, "This is red text", Reset)
    fmt.Println(Green, "This is green text", Reset)
    fmt.Println(Yellow, "This is yellow text", Reset)
    fmt.Println(Blue, "This is blue text", Reset)
}
```


prints this 

<img width="942" alt="image" src="https://github.com/user-attachments/assets/768a4add-24f4-4523-808c-f0b16f35c297">

Here is my build 
<img width="254" alt="image" src="https://github.com/user-attachments/assets/981f3bf9-90b2-4f5f-9626-9832389e4dc6">

**Comment by connor4312** [comment] 2024-10-06 00:16
This is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/), and users of the JS debugger who hit this can also use [js-debug nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension). We will put out a stable release with this fix next week.

**Closed** 2024-10-08 20:30 UTC
Labels: bug, debug, candidate
