### ISSUE TITLE
Terminal always opens PowerShell even though it's not the default

### ISSUE THREAD

**Issue by robinheidrich** [microsoft/vscode#130329] opened 2021-08-07 15:34 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Set the default profile for the terminal to Command Prompt
2. Open a new terminal, it's still PowerShell

What I've already tried:

- Reinstall VSCode
- Remove deprecated settings from settings.json

In my settings.json there is nothing related to the terminal, so the terminal profile is not overwritten.

Preview:

![screenshot](https://user-images.githubusercontent.com/23118399/128605001-86c0e015-7f81-409c-be2d-8dfecea82060.gif)

**Comment by IllusionMH** [comment] 2021-08-07 17:51
/duplicate of #130268

Fixed for next Insiders build.

**Closed** 2021-08-07 17:51 UTC
Labels: *duplicate
