### ISSUE TITLE
Closing tabs using mouse wheel click turns cursor into auto scroll

### ISSUE THREAD

**Issue by efroim102** [Microsoft/vscode#16690] opened 2016-12-06 17:41 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:
1. Open multiple files at a time until the tab menu is scroll-able.
2. Click on an open tab using the mouse wheel, the tab will close, but the cursor will turn into auto scroll (css: all-scroll) and when you move the mouse it will scroll the tab menu.

When closing tabs using scroll wheel click, I shouldn't need to click away to get a normal cursor.

**Comment by bpasero** [comment] 2016-12-07 08:26
I am not seeing this on my Windows 10 so I assume this is also mouse/configuration dependent.

**Comment by pawlikooo** [comment] 2017-04-26 07:35
I have pretty same issue. I don't even need scroll-able tab container to reproduce it.

1. Open single file.
2. Click on an open tab using the mouse wheel.

Mouse cursor turn into 8-way arrows depends on its position.
Nothing scrolling on mouse move: neither tabs nor code.
Have to click middle mouse one more time to escape mouse scrolling mode.

Also it correspond to #12623

Version 1.12.0-insider
Commit 48ae6e3027be560d45dd1ebfbe090d6ff77af7f0
Date 2017-04-26T06:13:08.212Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by CnSimonChan** [comment] 2017-08-20 09:15
This problem only happens when I set my DPI scale to 125%, all other values (100%, 150% and 175%) are ok.

Middle click on anywhere will trigger the scrolling, not only the tab bar.

Even `* { overflow: hidden !important; }` doesn't help.

**Comment by megakoresh** [comment] 2017-09-08 13:03
Yes, very annoying. Happens all the time when window is maximized. When it isn't seems to work fine.

**Comment by bpasero** [comment] 2017-10-26 14:05
Since I cannot reproduce this, I cannot help. If someone has ideas, here are instructions how to run VS Code from source: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by megakoresh** [comment] 2017-10-26 14:26
It has been fixed in the latest stable release. I have not encountered this problem after the update.

**Comment by sleutho** [comment] 2017-10-26 14:29
I'm running 1.17.2 on Windows 10 and still have this issue.

**Comment by bpasero** [comment] 2017-10-26 15:35
Should have mentioned, all the tabs are being created and styled in [`tabsTitleControl.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L498)

**Comment by efroim102** [comment] 2017-10-27 18:22
I have not encountered this issue for a while now, It must have been patched in one of the updates.

**Comment by jm-mwi** [comment] 2017-11-02 16:49
As @yume-chan mentioned... I had my scaling set to 125%. I changed it to 100% scaling and the issue was alleviated.

I'm adjusting my font settings to look as I'd like, but it would be nice if this issue was fixed so that the middle click to close a tab worked regardless of if a monitor was scaled or not.

**Comment by bpasero** [comment] 2017-11-03 09:12
@efroim102 @sleutho @megakoresh @yume-chan @pawlikooo can you verify that 125% scaling reproduces the issue and 100% scaling "fixes" it?

**Comment by megakoresh** [comment] 2017-11-03 09:54
Yes, can confirm.

**Comment by pawlikooo** [comment] 2017-11-03 10:26
Yes, just switched from 100% to 125% - still have annoying scroll mode. Turn back to 100% - it works fine.

Windows 10 Pro
VSCode 1.18.0-insider

**Comment by bpasero** [comment] 2017-11-03 10:43
Can someone enlighten me how to get this scroll-with-middle-mouse feature to work? Is this a mouse setting?

**Comment by bpasero** [comment] 2017-11-03 10:47
Actually I can reproduce...

**Comment by bpasero** [comment] 2017-11-03 10:57
Looks like a `return false` from the mouse-down handler fixes it. The issue is that the tabs container is a scrollable element and middle mouse click should not start to scroll-lock with the mouse because this action is already taken by the close-tab behaviour.

**Comment by ostap1010** [comment] 2017-11-20 09:18
It is still reproducible in version 1.18.1 on Windows 10.  Really waiting for this fix.

**Comment by megakoresh** [comment] 2017-11-20 09:35
It absolutely is, I think we will need to wait for next release for the fix to be merged.

**Comment by yume-chan** [comment] 2017-11-25 16:53
@bpasero I finally have my problematic PC back, and I really don't want to say: the problem is still reproducible.

I'm using: 

Version 1.19.0-insider
Commit 89b158e11cb1c3fe94a3876222478ed2d0549fc8
Date 2017-11-24T05:14:03.606Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by bpasero** [comment] 2017-11-27 11:29
Sorry to hear that I can still not reproduce with my mouse: Logitech (5 buttons).

At this point I need help from someone still seeing this issue. You can read [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#contributing-to-code) how to build VS Code from sources. If you see this happening when running out of sources, let me know and I can think about some code to add into the mouse handling of the tabs.

@yume-chan @megakoresh @ostap1010 do you also see the scroll lock when you click with the middle mouse into the editor or into the tree?

**Comment by bpasero** [comment] 2017-11-27 11:42
Yeah I can still reproduce, weird. I pushed another change to call `preventDefault()` on the mouse event and that seems to help. We will have an insiders build tomorrow to give it a spin and verify.

**Comment by bpasero** [comment] 2017-11-28 06:51
@yume-chan @megakoresh @ostap1010 can you give todays insider build a try to see if the issue is now fixed?  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by pawlikooo** [comment] 2017-11-28 07:19
Checked on latest version few minutes ago with 125% scaling:
- Middle mouse click on tab works like a charm.
- Middle mouse click on empty space in tab bar still force scroll mode with zero reaction on moving mouse.
- Same with double middle mouse click (expected new "Untitled-1" tab).

Version 1.19.0-insider
Commit d88e71355feeb2b0deb02c021d33cb968531726e
Date 2017-11-28T05:13:37.597Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by bpasero** [comment] 2017-11-28 08:56
@pawlikooo yeah good catch, I addressed that via https://github.com/Microsoft/vscode/commit/d784938bc9b1b80f37bd30e505e626103a57f8b5

**Closed by bpasero** 2017-11-28 08:56 UTC
Labels: bug, workbench-tabs
