### ISSUE TITLE
Broken SourceControl panel

### ISSUE THREAD

**Issue by MbIT9I** [microsoft/vscode#177989] opened 2023-03-22 09:55 UTC
Type: <b>Bug</b>

After update in my case broken SourceControl panel.
https://i.imgur.com/m6HUlNy.png
Sometimes files didn't show

1. Clone repo
2. Change some files
3. Open SourceControl panel
4. not see files wich edit. After reload this files shown but not show commit button 
expected result
seen files and commit button

VS Code version: Code - Insiders 1.77.0-insider (b8e4c550bc87aa1db64e612706ac5238035e9cc2, 2023-03-22T05:22:27.933Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.67GB free)|
|Process Argv|--crash-reporter-id 8d216072-85c9-4696-b5dd-e2acdd21bc47|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (103)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
add-reference|adr|1.0.2
asp-net-core-snippet-pack|adr|1.51.0
user-secrets|adr|2.0.1
vsc-scaffolding|alf|0.1.14
nugetpackagemanagergui|ali|2.0.6
nuxt-vscode-extension|all|0.0.21
bala-bks-kubernetes-snippets|bal|0.2.2
npm-intellisense|chr|1.4.4
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.4.0
vscode-dotnet-auto-attach|Den|1.1.1
docs-images|doc|1.0.0
k8s-snippets|dog|0.4.2
quicktype-refresh|dog|1.0.2
vscode-resx-editor|Dom|0.0.5
gitlens|eam|13.4.0
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
prettier-vscode|esb|9.10.4
hadolint|exi|1.1.2
vscode-solution-explorer|fer|0.8.2
vscode-firefox-debug|fir|2.9.8
cshtml-tm|fir|1.0.0
code-runner|for|0.12.0
dotnet-test-explorer|for|0.7.8
shell-format|fox|7.2.5
gitlab-workflow|Git|3.57.3
vs-code-runner|Har|2.0.1
kubernetes-snippets|ipe|0.1.9
jbockle-format-files|jbo|3.4.0
better-cpp-syntax|jef|1.17.2
better-dockerfile-syntax|jef|1.0.2
better-shellscript-syntax|jef|1.5.2
docomment|k--|1.0.0
vscode-ngrok-client-http|kar|1.0.3
graphql-for-vscode|kum|1.15.3
i18n-ally|lok|2.8.1
kubernetes-templates|lun|1.3.1
bash-ide-vscode|mad|1.35.0
vscode-nuget-package-manager-improved|max|2.1.0
manpages|mer|0.1.3
file-downloader|min|1.0.12
mindaro|min|2.0.120230310
ecdc|mit|1.8.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-dotnet-pack|ms-|1.0.12
vscode-dotnet-runtime|ms-|1.6.0
vscode-dotnet-sdk|ms-|0.8.0
vscode-ros|ms-|0.8.4
vscode-aks-tools|ms-|1.3.11
vscode-kubernetes-tools|ms-|1.3.11
data-workspace-vscode|ms-|0.4.0
mssql|ms-|1.17.1
sql-bindings-vscode|ms-|0.3.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.286.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.77.0
azure-account|ms-|0.11.3
cpptools|ms-|1.15.0
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.11
live-server|ms-|0.4.7
powershell|ms-|2023.3.1
remote-explorer|ms-|0.2.0
resourcemonitor|mut|1.0.7
vetur|oct|0.37.3
remote-kubernetes|Okt|0.4.7
vscode-jest|Ort|5.2.3
ngrok-for-vscode|phi|1.10.1
addlocalnetreferences|Raf|0.4.8
vscode-commons|red|0.0.6
vscode-xml|red|0.24.0
vscode-yaml|red|1.12.2
shellman|Rem|5.6.1
robotframework-lsp|rob|1.9.0
bash-debug|rog|0.3.9
edit-with-shell|ryu|1.3.0
kubernetesapply|Sha|1.4.1
svg-preview|Sim|2.8.3
msbuild-tools|ste|0.0.12
ms-teams-vscode-extension|Tea|4.2.4
vscode-h2o|tet|0.2.9
shellcheck|tim|0.29.4
msbuild-project-tools|tin|0.4.9
vsfire|tob|1.4.1
luna-paint|Tyr|0.16.0
volar|Vue|1.2.0
iis-express|war|1.5.0
vscode-todo-highlight|way|1.0.5
browserslist|web|1.1.0
shell-script-ide|woo|0.0.3
txt-syntax|xsh|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
azdwalk:30687957
pythonms35:30671666
cai9j608:30680470
24365598:30687740

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-22 10:15
Please use the Start Extension Bisect command to check whether any of your extensions are interfering with the built-in Git extension.

**Comment by lszomoru** [comment] 2023-03-22 10:16
Closing as duplicate of [177980](https://github.com/microsoft/vscode/issues/177980).

**Closed by lszomoru** 2023-03-22 10:16 UTC
