### ISSUE TITLE
Open Folder always use existing window

### ISSUE THREAD

**Issue by xrfang** [Microsoft/vscode#35207] opened 2017-09-27 07:22 UTC
- VSCode Version: 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d)
- OS Version: Kubuntu 17.04 (Linux desktop 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Steps to Reproduce:

1. open a folder in an existing VSCode window
2. press ctrl-shift-n to open a new vscode window
3. in the new window, click the "Open Folder" blue button on the Explorer pane to open the SAME folder as in the first code instance.

The folder refused to be opened in the second window, and the first window is focused.   This issue seems to be reported multiple times, before reporting, I have followed suggestions in history by editing my configuration:

    "window.openFoldersInNewWindow": "on",

However, it seems not working.  The reason I need to open two window is that I want to show two Code instance on two monitors so that I can reference code easily.   As a matter of fact, I don't know the rationale to prevent two code instance of the same folder??

Reproduces without extensions: Yes

**Comment by sandy081** [comment] 2017-09-29 15:07
@xrfang This setting is applicable when you open a different folder. But if you open a folder which is already opened, we always show the same window. This is designed. 

You can open same folder in different windows using our new **Workspace** feature.  Perform following steps to open two workspaces with same folder.

- Open an Empty window
- Add the folder to the Workspace

**NOTE:** This feature is available only in our Insiders. To try this please download the insiders 
https://code.visualstudio.com/insiders/

@bpasero I think we can do following improvements here
- Make it easy to open the same folder in a new window
- Make it easy to open a workspace from an empty window.

**Comment by bpasero** [comment] 2017-09-30 05:58
@sandy081 isn't this a duplicate of https://github.com/Microsoft/vscode/issues/2686 ?

**Comment by xrfang** [comment] 2017-09-30 15:03
Thank you @sandy081。 I will first learn the concept of a workspace, :-)

**Comment by sandy081** [comment] 2017-10-02 09:06
@bpasero Yes.

Duplicate of #2686

**Closed by sandy081** 2017-10-02 09:06 UTC
Labels: feature-request, multi-root, workbench
