### ISSUE TITLE
Incorrect clean up of formatting at end of file when deleting lines.

### ISSUE THREAD

**Issue by lordcheeto** [microsoft/vscode#99553] opened 2020-06-07 06:47 UTC
Issue Type: <b>Bug</b>

Description: When a line in the editor is formatted with an underline (e.g. a url) and is at the end of the file, removing lines above it leaves behind traces of the underline.

![2020-06-07 00-59-36](https://user-images.githubusercontent.com/145350/83962150-95b1b680-a860-11ea-8a03-96fd29f070b5.gif)

Expectation: No overflow of formatting.

VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
OS version: Windows_NT x64 10.0.19041

Does this issue occur when all extensions are disabled?: Yes

**Comment by eikaramba** [comment] 2020-06-08 13:58
can confirm, had the same issue today :)
![G0NE46eWX5](https://user-images.githubusercontent.com/1320525/84038959-db759880-a9a0-11ea-9d78-b4c794b0358c.gif)

**Comment by alexdima** [comment] 2020-06-09 06:36
Duplicate of #48321

**Closed by alexdima** 2020-06-09 06:36 UTC
