### ISSUE TITLE
[debug] Threads shown in "running" state after a "stopped" event with "allThreadsStopped": true

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#70107] opened 2019-03-09 02:44 UTC
- VSCode Version: 1.32.1
- OS Version: Ubuntu 18.10

Steps to Reproduce:
When a debug adapter sends "stopped" event, which includes `"allThreadsStopped": true` flag, VSCode sometimes shows some threads in "running" state.    This seems to happen only to "new" threads, i.e. ones whose creation has been reported just before the stop event.

**Comment by isidorn** [comment] 2019-03-11 14:04
@vadimcn can you please edit the mock sample on your fork such that I can simple run it and see the issue you mention?
Here's the mock sample https://github.com/Microsoft/vscode-mock-debug

**Comment by vadimcn** [comment] 2019-03-12 01:01
@isidorn Here's the branch: https://github.com/vadimcn/vscode-mock-debug/commits/repro-70107

Note that with mock debug it reproes about 5-10% of the time.  Restarting VSCode for each attempt might help.

![Screenshot](https://user-images.githubusercontent.com/3203809/54167447-ef8dbb80-4426-11e9-9fad-6facf47f534e.png)

**Comment by isidorn** [comment] 2019-03-12 08:39
@vadimcn thanks, I will investigate next week

**Comment by isidorn** [comment] 2019-03-15 15:38
I pushed a fix.
Can you please try with Monday's vscode insiders and let us know if the issue is fixed. Thanks!

**Closed** 2019-03-15 15:38 UTC
Labels: bug, debug

**Comment by vadimcn** [comment] 2019-03-18 18:42
Yep, now it works as expected.  Thanks!

**Comment by isidorn** [comment] 2019-03-19 08:33
Thank you, adding verified label.
