### ISSUE TITLE
Markdown image links are not giving a "follow link" link in the hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#196572] opened 2023-10-25 10:20 UTC
This is meant to be a link such that a user can trigger it using only the mouse.

![Image](https://github.com/microsoft/vscode/assets/2193314/8524c272-8423-4cd3-abcf-07a959bd92db)

Ctrl+click works fine.

Example of working link:

![Image](https://github.com/microsoft/vscode/assets/2193314/aa517594-aeaf-4cd4-b4cd-4352e5aa720b)

Which also makes me think the markdown one is not localized for some reason?

**Comment by mjbvz** [comment] 2023-10-30 21:01
Duplicate of #158996

**Closed by mjbvz** 2023-10-30 21:01 UTC
