### ISSUE TITLE
JS/TS Language Server continues to die repeatedly

### ISSUE THREAD

**Issue by jeffbski-rga** [microsoft/vscode#89728] opened 2020-01-30 17:07 UTC
Issue Type: <b>Bug</b>

[Info  - 16:59:32.941] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 16:59:32.943] <syntax> Forking...
[Info  - 16:59:32.953] <syntax> Starting...
[Info  - 16:59:32.958] <semantic> Forking...
[Info  - 16:59:32.968] <semantic> Starting...
[Info  - 16:59:43.0] TSServer exited
[Info  - 16:59:43.0] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 16:59:43.2] <syntax> Forking...
[Info  - 16:59:43.10] <syntax> Starting...
[Info  - 16:59:43.11] <semantic> Forking...
[Info  - 16:59:43.20] <semantic> Starting...
[Info  - 16:59:52.888] TSServer exited

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|22, 14, 8|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.7.0
project-manager|ale|10.10.0
vscode-browser-preview|auc|0.5.9
vscode-database|baj|2.2.0
replacerules|bhu|0.4.1
better-toml|bun|0.3.2
multi-cursor-case-preserve|Car|1.0.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
bettergitcommits|dav|0.5.0
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
vscode-postman|eri|1.0.2
prettier-vscode|esb|3.20.0
git-project-manager|fel|1.7.1
serverless-vscode|fra|1.0.0
glitch|gli|0.1.5
todo-tree|Gru|0.0.166
vscode-dynamodb|har|0.0.1
ternjs|hsi|0.0.4
rest-client|hum|0.23.1
output-colorizer|IBM|0.1.2
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.23.1
node-module-intellisense|lei|1.5.0
vscode-emacs-friendly|lfs|0.9.0
codeacejumper|luc|2.1.8
terraform|mau|1.4.0
rainbow-csv|mec|1.5.0
ecdc|mit|1.3.0
theme-monokai-pro-vscode|mon|1.1.14
vscode-azurefunctions|ms-|0.20.2
vscode-docker|ms-|0.10.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
azure-account|ms-|0.8.8
Go|ms-|0.12.0
vsliveshare|ms-|1.0.1510
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.6
copy-json-path|nid|0.0.5
vscode-for-node-js-development-pack|nod|2.0.1
vscode-ts-config-plugin|oct|0.2.0
vscode-jest|Ort|3.1.1
material-icon-theme|PKi|3.9.2
polacode|pnp|0.3.4
vscode-sort-json|ric|1.18.0
terraform-comments-beautifier|sah|0.0.3
block-travel|sas|0.0.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.1
mdx|sil|0.1.0
vscode-multiclip|sle|0.1.5
vscode-zipexplorer|sle|0.3.1
sonarlint-vscode|Son|1.13.0
org-mode|too|0.5.0
vscode-icons|vsc|9.7.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
unsaved-files-vscode|wra|2.1.1
JavaScriptSnippets|xab|1.7.2
vsc-postman-collection-syntax|xk0|0.2.1
vsc-postman-logs-syntax|xk0|0.3.0
vscode-mdx-preview|xyc|0.2.2
markdown-all-in-one|yzh|2.7.0
sort-js-object-keys|zen|1.0.6
material-theme|zhu|3.2.1

(28 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-01-31 19:10
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2020-02-07 23:55
Closing as not actionable without more info. Possible caused by an extension

**Closed by mjbvz** 2020-02-07 23:55 UTC
Labels: needs more info
