### ISSUE TITLE
can not launch in wsl ubuntu

### ISSUE THREAD

**Issue by scirac** [microsoft/vscode#192835] opened 2023-09-12 03:47 UTC
Type: <b>Bug</b>

i can't launch the vs code from WSL ubuntu  
1. open WSL ubuntu20.04
2. cd  /my_directory
3. code .   
expect to open the directory in vs code ,but not any response

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Connection to 'wsl+Ubuntu-20.04' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.40GB free)|
|Process Argv|--crash-reporter-id 7df69232-bf53-49af-8661-e135baa14e1c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|Memory (System)|15.75GB (8.40GB free)|
|VM|0%|

Connection to 'wsl+Ubuntu-20.04' could not be established
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.81.3
vscode-language-pack-zh-hans|MS-|1.82.2023090609
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by phudson** [comment] 2023-09-12 10:32
Was WSL already running? I've had two incidents (one with the latest VSCode, one with the previous version) where VSCode wouldn't start when WSL wasn't already started.

**Comment by aeschli** [comment] 2023-09-12 10:40
duplicate of https://github.com/microsoft/vscode/issues/192506

**Closed by aeschli** 2023-09-12 10:40 UTC
