### ISSUE TITLE
korean character input error when pressing arrow left

### ISSUE THREAD

**Issue by illmatik12** [microsoft/vscode#114017] opened 2021-01-08 04:44 UTC
- VSCode Version: 1.52.1
- OS Version: Windows10 x64 , 10.0.18363

Steps to Reproduce:

1. Typing some korean character
2. Press left arrow key. As a result, copy last character to left position

https://user-images.githubusercontent.com/7012709/103975466-8f4d3980-51b7-11eb-9ec7-dd3133d561c1.mp4

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment] 2021-11-29 22:39
I am fairly confident that this was caused by us writing to the textarea (changing its value) during the `compositionstart` event. In other words, I think the fix for #138095 will also fix this issue. I would be very thankful if you could verify that the issue no longer reproduces using tomorrow's [Insiders](https://code.visualstudio.com/insiders/) that should be released in 9-10 hrs.

**Closed by alexdima** 2021-11-29 22:39 UTC
Labels: bug, help wanted, windows, editor-input-IME

**Comment by rchiodo** [comment] 2021-12-02 23:10
/verified
![korean](https://user-images.githubusercontent.com/19672699/144517537-f4d9df3f-932f-49ab-a056-3a6864e0d0d9.gif)
