### ISSUE TITLE
NumPad keys ignored

### ISSUE THREAD

**Issue by kamujin** [Microsoft/vscode#24609] opened 2017-04-12 14:49 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.8.0-46-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|trailing-spaces|shardulm94|0.2.11|;

This seems to be a regression introduced with the latest version(s)

---

Steps to Reproduce:

1. Open document in vscode.
2. Press Home (End, PageUp, PageDown) key on numpad
3. See nothing happen

**Comment by kamujin** [comment] 2017-04-12 15:17
using "keyboard.dispatch": "keyCode" to workaround problem

**Comment by alexandrudima** [comment] 2017-04-13 07:39
Duplicate of #24064 - the latest insiders release already contains a fix

**Closed by alexandrudima** 2017-04-13 07:39 UTC
