### ISSUE TITLE
vscode server open fail on  WSL

### ISSUE THREAD

**Issue by ppb440219** [microsoft/vscode#118745] opened 2021-03-11 16:51 UTC
[2021-03-11 16:42:45.102] Installing VS Code Server for x64 (f30a9b73e8ffc278e71575118b6bf568f04587c8)
[2021-03-11 16:42:45.102] Downloading:     
[2021-03-11 16:44:15.588] VS Code Server for WSL failed to start. No messages received for 90s
[2021-03-11 16:44:15.588] For help with startup problems, go to
[2021-03-11 16:44:15.588] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2021-03-11 16:44:15.597] WSL Daemon exited with code 0

**Comment by WadeTsai** [comment] 2021-03-11 23:25
The root cause is unable to download vscode-server-linux-x64.tar.gz from server.
How to repro:
`wget -nv -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:f30a9b73e8ffc278e71575118b6bf568f04587c8/server-linux-x64/stable/`

**Comment by aeschli** [comment] 2021-03-12 08:50
duplicate of https://github.com/microsoft/vscode-remote-release/issues/4648

**Closed by aeschli** 2021-03-12 08:50 UTC
