### ISSUE TITLE
Copy Call Stack doesn't work when doing C/C++ debugging with a multithreaded process

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#81406] opened 2019-09-24 23:57 UTC
- VSCode Version: 1.38.1
- OS Version: Windows (others?)

Steps to Reproduce:

1. Use the C/C++ extension to attach to a multithreaded process, break into the debugger, and right click a call stack and choose "Copy Call Stack" and then paste somewhere.

Bug: Copy silently has no effect. It works with TypeScript debugging. I don't think our C/C++ debugger extension is to blame.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2019-09-25 10:47
@sean-mcmanus thanks for reporting this. I have pushed a fix. You can try it out in vscode insiders from Thursday and onwards and let us know if the issue is trully fixed for you. Thanks

**Comment by alexr00** [comment] 2019-10-04 13:06
My verification steps:
Install C++ extension
Add this debug config:
```
		{
			"name": "(Windows) Attach",
			"type": "cppvsdbg",
			"request": "attach",
			"processId": "${command:pickProcess}"
		},
```
Launch stable VS Code so that I have something good to attach to.
Run the debug config and choose a Code.exe process
Hit the pause button
Expand a thread in the Call Stack
Right click -> Copy Call Stack
Paste but 🐛 the call stack isn't what pastes, it's instead the last thing from my clipboard.

**Comment by isidorn** [comment] 2019-10-22 14:12
This should be fixed with latest with https://github.com/microsoft/vscode/pull/82235
@alexr00 since you have nice steps, can you be so kind to try it out?
In case it does work not can you ping me so we investigate? Or you can put a breakpoint [here](https://github.com/Microsoft/vscode/blob/2aa29a989591a1d683c46faf82744c53231a1484/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L112)

**Comment by isidorn** [comment] 2019-10-23 10:50
@alexr00 thanks a lot for the help. I believe i have hunted down the issue.
Argument `undefined` was getting lost for the unavailbe stack Frames. Now ti should work

**Closed** 2019-10-23 10:49 UTC
Labels: bug, debug, verification-found
