### ISSUE TITLE
Expanded entry inside collapsed entry only shows children after collapsing & expanding (custom tree views)

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#29381] opened 2017-06-24 14:15 UTC
- VSCode Version: 1.13.1
- OS Version: Win 10

Steps to Reproduce:

1. Create an extension with a custom tree provider
2. Have a tree where the top-level node is collapsed, and it has one children which is expanded and has itself a couple of children
3. Observe that when you click on the top-level node to expand it, then the little arrow on the child is in the "expanded" state, but no children are display. After collapsing and re-expanding, the children appear.

**Comment by letmaik** [comment] 2017-07-13 19:48
A little visualization:
![vscode-custom-view-bug](https://user-images.githubusercontent.com/530988/28184743-7a7704e8-680c-11e7-935a-a45a9b23d31d.gif)

**Comment by sandy081** [comment] 2017-07-27 16:39
Duplicate of #30918

**Closed by sandy081** 2017-07-27 16:39 UTC
Labels: bug, explorer-custom
