### ISSUE TITLE
Add another option for editor.showFoldingControls

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#40384] opened 2017-12-17 17:13 UTC
`editor.showFoldingControls` only allows for "always" and "mouseover". It would be nice if we could disable it entirely.

The only way to remove the controls (and save space in the editor) is to set `"editor.folding": false`. However, this will also disable the keyboard shortcuts for folding.

Preferably, we could disable the UI controls while still being able to use the keyboard shortcuts.

**Comment by aeschli** [comment] 2017-12-18 11:59
How would you know where folding regions are? Just trying blindly to collapse?

**Comment by Montago** [comment] 2017-12-19 07:57
BUG: 
"editor.showFoldingControls": "always" is ignored !!!!

after updating to latest version of VSCODE, this option is ignored :(

**Comment by aeschli** [comment] 2017-12-19 10:14
@Montago It was broken in 1.18, but fixed in 1.19. Please make sure you are on the latest stable build.

**Comment by Montago** [comment] 2017-12-19 11:33
oh...  didn't notice the update. VsCode hasn't said anything about any updates :) 

Thanks :+1:

**Comment by joelhsmith** [comment] 2018-05-18 17:42
The "editor.showFoldingControls": "always" is ignored in version 1.23.1 on MacOS Sierra also

**Comment by aeschli** [comment] 2018-05-22 07:45
@jabacchetta Works for me on 1.23.1. Please file a new issue with your current settings and steps to reproduce.

**Comment by aeschli** [comment] 2018-05-22 07:46
@jabacchetta How would you know where folding regions are? Just trying blindly to collapse?

**Comment by joelhsmith** [comment] 2018-05-24 13:44
Update to my issue of missing code folding functionality:

In my User Settings, if I remove "editor.accessibilitySupport": "on" the "editor.folding" works.

I am a web developer that specializes in web accessibility, so people like me are running the screen readers while they work for testing all the time.

A cool feature of VSCode is that when you activate the Voice Over screen reader it asks if the person is using a screen reader:
![vscode-screen-reader-dialog-box](https://user-images.githubusercontent.com/7026376/40488242-4d7ec258-5f34-11e8-9620-a7c049098212.png)

If the user select the "Yes" button it automatically adds the editor.accessibilitySupport to the User Settings.

The dialog box does mention that "Some editor features will have different behavior: e.g. word wrapping, folding, etc."

Should this behavior of disabling code folding be considered a bug or works as designed? 

If it works as designed, can we add a link in the dialog box to a page that explains what functionality is added and taken away by using that setting? Similar to this entry https://code.visualstudio.com/updates/v1_13#_better-nvda-support

**Comment by aeschli** [comment] 2018-05-28 09:19
@joelhsmith Can you file that as a separate issue?

**Closed** 2018-06-04 09:59 UTC
Labels: editor-folding, feature-request, needs more info

**Comment by jabacchetta** [comment] 2018-06-18 00:36
@aeschli Apologies on the delayed response. This isn't a major issue for me since I don't find myself using code folding often. But to answer your question...

From my understanding, folding regions are always the same, aren't they? Classes, methods, functions, objects, imports, etc.

And the folded code is already represented by the `...`.

**Comment by jabacchetta** [comment] 2018-06-18 16:00
@aeschli Sounds good.

I do think that, at least for JavaScript, folding regions are mostly self-explanatory. And the reasoning behind any potential update would be to basically just save space in the editor on that left hand side (hiding the controls, but still allowing folding with the keyboard shortcut).

Those most likely to notice this are users coming from WebStorm, which does allow for folding without the controls shown.

But yeah, it very well may be the case that nobody else cares about it. So might be best left as closed until someone else brings it up.

Thanks!
