### ISSUE TITLE
Add Option for Adding NumberBadges on Custom ActivityBarItem

### ISSUE THREAD

**Issue by pingubro** [Microsoft/vscode#67713] opened 2019-02-01 08:41 UTC
I have not found any resource on doing this and no request was suggested when I was searching with my key words, so...

Maybe add an option to the API so that we can use `NumberBadges` or `Badges` on custom `ActivityBar/SideBar` items like the ones that are on the File Explorer, SCM or Settings View.

A use case might be that your extension gathers data on your project or fetches them externally and you want to notify the user when the data has arrived. 

E.g. the extension looks for blacklisted words in files. All files that contain these words are in a custom `TreeView` which is shown in a custom `ActivityBarTab`. When you have scanned all files the file count is shown with the help of a `Badge` on your custom `Tab`  to notify the user.

**Comment by sandy081** [comment] 2019-02-01 09:13
Duplicate of #62783

**Closed** 2019-02-01 09:13 UTC
Labels: *duplicate, api, explorer-custom, feature-request
