### ISSUE TITLE
intellisense doesn't work.no auto completion with inline javascript code in the .html file

### ISSUE THREAD

**Issue by fantacytyx** [Microsoft/vscode#3465] opened 2016-02-25 19:00 UTC
I build vscode from the master branch.(0.10.10)
Found that intellisense doesn't work,no auto completion with inline js code in the .html file.
The previous version(0.10.8) support
![default](https://cloud.githubusercontent.com/assets/8966236/13330917/127a6596-dc36-11e5-9796-70d1c0dda3ef.jpg)

**Comment by egamma** [comment] 2016-02-25 20:20
This is a known limitation since we switched to Salsa. I will document this in the release notes for the february update

**Comment by Thaina** [comment] 2016-05-04 08:40
@egamma Are there any news or issue tracking on typescript side yet? Or this is only problem on vscode side?

**Comment by egamma** [comment] 2016-05-04 15:44
The fix requires collaboration on both ends. One VS Code has to feed that html file into the project context and Salsa needs to be able to work with this 'virtual' JS document.

**Comment by shea-sollars** [comment] 2016-05-05 06:18
![image](https://cloud.githubusercontent.com/assets/2511672/15037294/8bde089a-124e-11e6-9205-a2959552aa9d.png)

**Comment by shea-sollars** [comment] 2016-05-05 08:02
Works with inline style, why not inline JavaScript?

**Comment by Tekbr** [comment] 2016-07-28 17:28
Any progress in fixing this?
This is similar to #8928 ?

**Comment by lealcy** [comment] 2016-07-29 14:35
Very limiting issue.

**Comment by rwatts3** [comment] 2016-11-11 22:33
Ok it has been several months , I have gone through several beta releases to see that this still has not been addressed. As I write nearly all of my code in a handlebars/mustache like environment, this is extremely limiting and has a huge reduction in productivity. 

Can at least a timeline  or "we'll be working on this in x release" be posted somewhere.

I expect that majority of the community probably use a template engine or language of some sort so it's definitely not a low priority issue. This should be high priority IMHO

**Comment by asolopovas** [comment] 2016-11-18 12:07
It sad that almost every great code editor lacks some vital functionality for modern development. PHP storm doesn't have proper vue.js support and very resource hungry, SublimeText does not have proper completion, VSCode does not support completion in script tags. Hopefully one day things will get better.

**Comment by asolopovas** [comment] 2016-11-21 11:47
Does any one know if this will be implemented at all?

**Comment by waderyan** [comment] 2016-11-21 22:54
@asolopovas @rwatts3 apologize for the delay. This is on the iteration plan for this month and is actively being worked on. https://github.com/Microsoft/vscode/issues/15099

**Comment by rwatts3** [comment] 2016-11-21 22:55
Thank you

**Comment by waderyan** [comment] 2016-11-21 22:57
As this is a duplicate of #15377, I will close this one. Thank you for your feedback! We hear you and are working on making an excellent experience.

**Closed by waderyan** 2016-11-21 22:57 UTC
Labels: feature-request, js
