### ISSUE TITLE
v1.25: Project import TS re-write shortcut

### ISSUE THREAD

**Issue by DominicTobias** [Microsoft/vscode#55234] opened 2018-07-27 11:16 UTC
- VSCode Version: 1.25
- OS Version: Windows 7

This isn't a bug report but it's happening at least once everyday and nobody on Stackoverflow knows the answer.

In v1.25 you have added the worst (keyboard shortcut?) in the universe. It happens at least once per day that I accidentally press something which results in every single import in my project which has a typedef being re-written like this:

![rewrite-import](https://user-images.githubusercontent.com/760314/43317922-c4dbec7e-9196-11e8-801b-6256c8b83ac4.jpg)

There isn't even a prompt before it re-writes everything so not sure when it happens until I notice.

Why would that even be something that anyone wants? And how do I turn it off!? This never happened in previous versions.

Thanks and feel free to close this, just getting desperate as there are no answers on SO.

**Comment by mjbvz** [comment] 2018-07-27 18:37
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-27 18:37 UTC
Labels: javascript

**Comment by DominicTobias** [comment] 2018-08-03 16:13
@mjbvz my project isn't even using Typescript. I tried globally updating to v3 but made no difference.

This specifically happens when I press F12 to rename a file, as soon as I rename and hit Return key. It doesn't happen if I right click -> rename it strangely enough.

**Comment by DominicTobias** [comment] 2018-08-06 08:55
Edit: This happens on any kind of file rename on 1.25.1 too, so annoying

**Comment by mjbvz** [comment] 2018-08-07 20:49
@DominicTobias This is the same problem. Use insiders
