### ISSUE TITLE
High contrast selection only available in high contrast theme

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode#43569] opened 2018-02-13 09:57 UTC
- VSCode Version: 1.20.0
- OS Version: Linux

When the high contrast theme is selected, selected text in the editor obeys both editor.selectionBackground and editor.selectionForeground, which allows for high contrast selections similar to those in a terminal (although I think the color inversion offered by terminals is superior in sysntax highlighting context).
If a non-high contrast theme is selected, editor.selectionForeground is ignored. It's effectively impossible to make a selection perfectly readable in a syntax highlighting context for any theme that's not high contrast. You must always choose to either use an editor.selectionBackground that's close to the background color and therefore make the whole selection hard to see or accept the fact that some syntax elements will be unreadable because they are colored to close to the background color.

To fix:
* editor.selectionForeground should always be obeyed if set, not just in high contrast theme.
* Conversely, for the high contrast theme there should be a way to unset the foreground, e.g. null or "".

An option to get the color inversion (swap background and foreground) as used by terminals would be a nice addition.

**Comment by usernamehw** [comment] 2018-02-13 11:18
Duplicate of #36490

**Closed** 2018-02-16 14:01 UTC
Labels: themes
