### ISSUE TITLE
Let Typescript hovers convert `{@link Thing}` in JSDoc comments into clickable links

### ISSUE THREAD

**Issue by nilslindemann** [microsoft/vscode#102229] opened 2020-07-11 16:57 UTC
Please do this :-)

**Comment by mjbvz** [comment] 2020-07-13 18:26
Duplicate of https://github.com/microsoft/TypeScript/issues/35524

**Closed by mjbvz** 2020-07-13 18:26 UTC

**Comment by nilslindemann** [comment] 2020-07-13 18:44
Thanks, didnt see.
