### ISSUE TITLE
Minimap disspears when Ctrl+Click is triggered on a SCSS variable

### ISSUE THREAD

**Issue by collinsnji** [Microsoft/vscode#28472] opened 2017-06-11 21:58 UTC
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04 Xenial Xerus
- Commit hash: 376c52b955428d205459bea6619fc161fc8faacf

Steps to Reproduce:

1. Create a two `.scss` files (eg. `main.scss` and `_part.scss`)
2. In `_part.scss` make a new variable (eg: `$color`: "blue");
3. In `main.scss` make a call to the variable, like `.color { background: $color; }`
4. Click on `$color` while holding down `ctrl` in `main.scss`. This opens the definition box for `$color`. But when it is closed (or clicking anywhere), the minimap on the right disappears

To show the minimap again, restart VS Code

**Comment by ramya-rao-a** [comment] 2017-06-12 22:33
@collinsnji What do you mean by the "overview map"? Do you mean the minimap on the right?

**Comment by collinsnji** [comment] 2017-06-13 06:58
@ramya-rao-a yes. That what I mean. I did not know exactly how to call it. I'll update the issue

**Comment by ramya-rao-a** [comment] 2017-06-13 15:22
In that case, this is a duplicate of #28093 
The fix is available in Insiders

**Closed by ramya-rao-a** 2017-06-13 15:22 UTC
Labels: needs more info, new release
