### ISSUE TITLE
Where are the icons?

### ISSUE THREAD

**Issue by maorui2014** [Microsoft/vscode#23380] opened 2017-03-28 10:12 UTC
- VSCode Version: Code - Insiders 1.11.0-insider (d4a9c30378579fc4980d5bc272c7eb65a7c576ab, 2017-03-28T07:25:45.304Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|vscode-icons|robertohuertasm|7.4.0|;

---

![image](https://cloud.githubusercontent.com/assets/18439500/24400181/08d47cd6-13e2-11e7-9b09-1cead8aec82f.png)

After the update, all icons are not display.

**Comment by tlgreg** [comment] 2017-03-28 10:33
Looks like it strips out the directory separators from the icon file paths, like: `file:///C:/Users{user}.vscode-insiders%0Extensionsrobertohuertasm.vscode-icons-7.4.0icons%0Folder_type_js.svg`
Same thing with other icon themes.

**Comment by lafe** [comment] 2017-03-28 11:51
This is a duplicate of #23346

**Closed** 2017-03-28 15:03 UTC
