### ISSUE TITLE
Vs Code lost my custom font every time after restart/turn off machine.

### ISSUE THREAD

**Issue by rodrigofbm** [microsoft/vscode#195191] opened 2023-10-09 20:23 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.0
- OS Version: Windows 11

Steps to Reproduce:

1. Add some font to C:/Windows/Fonts
2. Change vs code to that font
3. Restart/turn off machine

Hi, so every time I restart/turn off my machine VS code lost the font that I have set. So I have to delete the font in C:/Windows/Fonts folder. Install it again. Close and open Vs Code to it work again.
It happens to every custom font. But now I'm having this issue with JetBrains Mono.

**Comment by rzhao271** [comment] 2023-10-09 21:46
Duplicate of #173543
Also, is this an issue new to 1.83, or has it happened in the past?

**Comment by rodrigofbm** [comment] 2023-10-10 15:58
> Duplicate of #173543 Also, is this an issue new to 1.83, or has it happened in the past?

Sorry, I didn't find this thread.
I'm not sure, but I think it happens from two or more previous versions from now.

**Comment by rohitprofc** [comment] 2023-10-17 14:39
### Hello @rodrigofbm @rzhao271

- I too face the same [problem](https://github.com/microsoft/vscode/issues/173543#issuecomment-1623311036).
- After rebooting the system I was unable to see the JetBrains Font in VS Code 
- But I tried installing font for all users like this ⬇️
- ![Screenshot (54)](https://github.com/microsoft/vscode/assets/100615505/fd4162a0-f841-414d-9a40-548c7afa58b9)
- Issue was solved  - #173543

**In windows 11:**
1. Select all in JetBrains font folder 
2. Right click and got to show more options
3. There you can find Install for all users
4. Click install for all users
- ![image](https://github.com/microsoft/vscode/assets/100615505/a8033300-14fa-4844-a96f-9969fae6d846)

**Comment by rzhao271** [comment] 2023-10-17 23:14
Merging with #173543

**Closed by rzhao271** 2023-10-17 23:14 UTC
Labels: bug, info-needed
