### ISSUE TITLE
Cannot re-focus notebook comparison editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127538] opened 2021-06-29 18:54 UTC
Testing #127355

1. Using Compare Active File with, compare two notebooks
2. Ctrl+tab twice to switch away from and back to the diff
3. The diff closes and an error is shown 🐛 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2230985/123852102-cbdd3080-d8d0-11eb-8d66-71e4c2111476.png">

**Comment by bpasero** [comment] 2021-06-30 05:58
Duplicate of https://github.com/microsoft/vscode/issues/127483

**Closed** 2021-06-30 13:02 UTC
Labels: *duplicate
