### ISSUE TITLE
网络代理问题

### ISSUE THREAD

**Issue by Mrbuchixiangcai** [microsoft/vscode#104770] opened 2020-08-17 01:07 UTC
所需的数据太大，无法直接发送。我们已经将其
Issue Type: <b>Bug</b>

公司网络不能直接联网，打开软件出现一个代理弹窗，输入ip之后，点击ok或者cancel不能退出，100%复现

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.83GB free)|
|Process Argv|F:\homework\01_iar\Project\Project_project\03_PF\PF_Source\V20\PFS_PRJ_V20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets|221|0.1.38
include-autocomplete|ajs|0.0.4
cppincludeguard|aki|1.1.0
c-compiler|bra|0.0.4
arm|dan|1.4.0
c-cpp-compile-run|dan|1.0.11
c-cpp-project-generator|dan|1.2.1
githistory|don|0.6.9
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
vscode-highlight|fab|1.4.1
file-icons|fil|1.0.25
CppSnippets|har|0.0.14
beautify|Hoo|1.5.0
vscode-gnu-global|jay|0.3.3
c-cpp-flylint|jbe|1.5.1
ccpp-extension-pack|Leo|1.0.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.48.1
csharp|ms-|1.23.0
atom-keybindings|ms-|3.0.8
cmake-tools|ms-|1.4.1
cpptools|ms-|0.29.0
color-highlight|nau|2.3.0
vscode-cpptest|Par|2020.1.2
material-icon-theme|PKi|4.2.0
iar-vsc|plu|1.3.0
iar|pol|1.6.0
reloaded-cpp|rel|0.1.9
code-settings-sync|Sha|3.4.3
codelf|unb|11.7.0
better-align|wwm|1.1.6

(5 theme extensions excluded)

</details>
写入剪贴板，请粘贴。

**Comment by marco-cc** [comment] 2020-08-17 01:20
Duplicate of #104766

**Comment by matthewkwong2** [comment] 2020-08-17 05:50
Duplicate of #104603

**Closed** 2020-08-17 16:31 UTC
Labels: *duplicate, *english-please, needs more info, new release, translation-required-chinese-simplified
