### ISSUE TITLE
Extension not updating after having it installed from the terminal using --install-Extension

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#17290] opened 2016-12-15 10:45 UTC
- VSCode Version: 1.9.0-insiders
- OS Version: Windows

Steps to Reproduce:

1. I installed the eslint extension using the command line as described here: https://github.com/Microsoft/vscode-eslint/issues/42#issuecomment-264828064. The vsix is in that comment as well.
2. Now I published a new version to the store with version number 1.2.1 expecting that the eslint will be updated to that version. However no update happens in the insider build into which I installed eslint using the command line.

**Comment by bpasero** [comment] 2016-12-15 14:11
Adding @sandy081 since @joaomoreno is out on vac.

**Comment by sandy081** [comment] 2016-12-15 16:01
Looks like showing updates for locally installed extensions was never working. The only way for now to update such extensions is 

- Search for that extension and **Install** it from market place

When syncing installed extensions with gallery extension we are using `id` as mapper which is available for extensions installed from gallery. 

Fix is to use identifier `publisher.name` which maps any installed extension with gallery

**Comment by sandy081** [comment] 2016-12-15 16:44
@joaomoreno FYI

**Comment by dbaeumer** [comment] 2016-12-15 17:38
@sandy081 @egamma would this be a candidate?

**Comment by joaomoreno** [comment] 2016-12-15 22:07
@dbaeumer This is neither a candidate, important nor a bug. It's a feature we never supported. In order to benefit from its updates, you must install an extension from the gallery. Installing a VSIX is an extraordinary, exceptional, out-of-normal situation. At least this is our current story.

An argument which supports this is the fact that anyone can just come up with the same publisher and extension names as the ones in the store for their VSIX. We don't want to have situations in which we overwrite something we should not.

@sandy081 I suggest to revert this change.

**Comment by sandy081** [comment] 2016-12-16 06:37
This is definitely not a candidate (hence set to January). But IMO, this looks to me a bug from an end user point of view. In this scenario, As an user, I expect an extension to show update  or to distinguish local (VSIX) with Gallery extension. I would not suggest to have another category of extensions instead it makes much sense to get it sync with market place.

**Comment by dbaeumer** [comment] 2016-12-16 09:06
I look onto this form a user perspective. Since the market place is not allowing us to have an insider channel I ask ESLint extension users to install the vsix to help me testing new features. However now all users that did this are stuck and they don't even know about this since I didn't know about this. They are not receiving an new updates anymore

@joaomoreno if this is working 'as-designed' could you please let me know how I should ask existing ESLint extension users to participate in new version testing.

**Comment by joaomoreno** [comment] 2016-12-16 09:37
@dbaeumer Not supported, but tracked: #15756. If we want it badly, I believe we should support it from the Marketplace.

@sandy081 I can't be sure that this change won't break existing users, since we now may be matching against some extensions that the user has installed locally and he didn't intend to.

**Comment by sandy081** [comment] 2016-12-16 13:16
Fix reverted

**Comment by joaomoreno** [comment] 2017-01-03 09:44
Closing as duplicate of #15756

**Comment by sandy081** [comment] 2017-02-01 09:44
Let's fix this for February.

**Comment by sandy081** [comment] 2017-02-02 09:00
@joaomoreno Pushed the reverted fix.

**Closed** 2017-02-02 09:00 UTC
Labels: bug, extensions

**Comment by aeschli** [comment] 2017-02-24 16:00
Verified, but found #21375
