### ISSUE TITLE
Add a feature to set "terminal.ansiBlack"="terminal.background"

### ISSUE THREAD

**Issue by xmha97** [microsoft/vscode#140610] opened 2022-01-13 06:01 UTC
Please add a feature to set "terminal.ansiBlack"="terminal.background"
```json
    "workbench.colorCustomizations": {
        "terminal.ansiBlack": "terminal.background"
    },
```

**Comment by Tyriar** [comment] 2022-01-18 17:13
FWIW I don't think you would want to do that because then ansiBlack would be invisible, but this is a general feature request to allow resolving theme values something like `"terminal.ansiBlack": "${terminal.background}"` so sending to @aeschli

**Comment by aeschli** [comment] 2022-01-19 21:44
Duplicate of https://github.com/microsoft/vscode/issues/56855

**Closed by aeschli** 2022-01-19 21:44 UTC

**Comment by xmha97** [comment] 2022-01-20 05:13
> "terminal.ansiBlack": "${terminal.background}"

![image](https://user-images.githubusercontent.com/23485114/150277554-61a457bb-566f-429a-b7b1-0e1fda3cf372.png)
Now Working :(
