### ISSUE TITLE
FIles in $GIT_DIR/info/exclude don't appear as gitignored

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#79118] opened 2019-08-14 14:07 UTC
Per [this SO answer](https://stackoverflow.com/a/1753078/1243041) and the [Git documentation](https://git-scm.com/docs/gitignore#_configuration), you can add files to the local `.git/info/exclude` file to ignore them in the same way as if they were added to `.gitignore`, except it will only apply locally. The files matched by this means, however, don't appear as gray in VSCode.

Version: 1.38.0-insider (user setup)
Commit: ffa22b268f451b5211abbe2d2a47e6b753b55b1a
Date: 2019-08-13T07:27:53.993Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by iansan5653** [comment] 2019-08-14 14:10
^ That's almost certainly a bug in vscodebot considering that's my issue and has nothing to do with this one. Does the bot have a repo?

**Comment by joaomoreno** [comment] 2019-08-30 11:21
@jrieken Is the current fading out specific to `gitignore`?

**Comment by jrieken** [comment] 2019-08-30 12:44
No, we ask git what's being ignored. So either there is a flag missing or it's an upstream issue: https://github.com/microsoft/vscode/blob/e77b008fb04222192a608906ff603bd72943d779/extensions/git/src/repository.ts#L1278-L1281

**Comment by joaomoreno** [comment] 2019-08-30 15:45
@iansan5653 Can you check whether `check-ignore` returns the correct result in your case?

**Comment by mathieucaroff** [comment] 2020-06-18 20:16
I don't fully understand this issue, but I believe like @dvd-z that it is a duplicate of #98945 and that as such, it should be fixed by PR #100123 .

**Comment by joaomoreno** [comment] 2020-11-09 15:22
Fixed by https://github.com/microsoft/vscode/pull/106270

Sorry about that!

**Closed by joaomoreno** 2020-11-09 15:22 UTC
Labels: bug, git, help wanted
