### ISSUE TITLE
After opening a file it should remain in working files even though its not edited

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#6507] opened 2016-05-19 01:17 UTC
A lot of times you want to look at a file for reference e.g the generated js while you modify ts.

The working files tend only only keep files with modification. It should behave like sublime where it stays open

**Comment by bpasero** [comment] 2016-05-23 17:43
There are many ways to make a file durable, e.g. double click. With the work on tabs there are even more ways (e.g. double click on the title). Would you expect other ways?

**Comment by nojvek** [comment] 2016-05-23 20:19
I absolutely had no idea about double click.

May be a contextual tooltip?

Why not add the files to working files on a single click? Like sublime ?

**Comment by bpasero** [comment] 2016-05-23 22:25
@nojvek sublime does not add files to working files on single click, you need a double click or edit.

**Comment by nojvek** [comment] 2016-05-26 20:49
Ahh you are right @bpasero 

Although What I usually use is Ctrl+P to quickly search for file and open it. sublime adds it as a proper tab / working file, while vscode doesn't.

Is this an easy fix I could make?

**Comment by bpasero** [comment] 2016-05-26 21:01
Closing as duplicate of https://github.com/Microsoft/vscode/issues/5554 then.

**Closed by bpasero** 2016-05-26 21:01 UTC
Labels: feature-request, tabs
