### ISSUE TITLE
Japanese IME shows incorrect pre-committed text on Ubuntu

### ISSUE THREAD

**Issue by vain0x** [microsoft/vscode#138763] opened 2021-12-09 14:47 UTC
Issue Type: <b>Bug</b>

In some cases, pre-committed text of IME is visually incorrect.
A reproduction step is:

- Input some word (press sensei), press Space (convert), press Enter (commit).
- Input another word (press konnnitiha), press space
    - at this time text on editor that I see should be "先生こんにちは" (with こんにちは underline)
   - however, actually it is "先生先生こんに" (with 先生こんに underline)

https://user-images.githubusercontent.com/6957032/145417893-325c45a4-033e-490f-a60c-bfe0bd19334d.mp4

----

Notes:

- At the time, if Space is pressed, IME seems working correctly. IME converts "konnnitiha" to expected candidates such as こんにちは/今日は/etc. Shown text on editor is still incorrect.
- if Enter is pressed, expected word is commited. Shown text is now correct. ("先生こんにちは")

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.4.0-91-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3870)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (6.62GB free)|
|Process Argv|/home/owner/repo/local/milone-lang --crash-reporter-id 720274d0-9a32-4459-810b-6982ea2da2f8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vs360:30404995
vsrem710:30405998

```

</details>

**Comment by vain0x** [comment] 2021-12-09 14:54
PS: I didn't see similar issue until yesterday when I used VSCode on the same environment. Today, I also tried the reproduction step on other text-input places, such as textarea on Chrome and Text Editor app, and issue didn't occur.

**Comment by tamuratak** [comment] 2021-12-09 22:53
Duplicate of #138704

**Comment by vain0x** [comment] 2021-12-10 12:00
Thanks. I saw that issue but I was unsure whether these issues were same because I didn't see issue about pressing Left/Right keys.

https://user-images.githubusercontent.com/6957032/145571042-8b791f4f-5465-4d05-93cc-9748da0b2aed.mp4

PS: I'm using ibus 1.5.17 + mozc 2.20.2673.102 .

**Comment by kahsa** [comment] 2021-12-12 02:04
Same issue on ArchLinux

**Comment by alexdima** [comment] 2021-12-17 21:36
@vain0x :+1: Thank you for the very clear steps, they have helped me understand what was going wrong.

**Closed** 2021-12-17 21:55 UTC
Labels: bug, linux, editor-input-IME
