### ISSUE TITLE
Typescript formatting does not work with Ctrl + Shift + l 

### ISSUE THREAD

**Issue by rupamroy** [Microsoft/vscode#24258] opened 2017-04-07 19:40 UTC
Typescript formatting does not work with Ctrl + Shift + l, but works if Ctl+Shft+P and then Format Code

- VSCode Version:March 2017 (version 1.11)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Write a typescript code like this in a file test.ts
```
export class test {
    foo(){
    console.log("test formatting");
    }
}
```
2. Save the file - formatting does not work
3. press Ctrl+shift-l - formatting does not work
4. Press Ctrl+Shift+P and then choose Format Document - This will work and format the document.

**Comment by mjbvz** [comment] 2017-04-07 19:43
This sounds like a duplicate of #24258. Can you try setting up a new keybinding for the format command to see if that fixing the issue

**Closed by mjbvz** 2017-04-07 19:43 UTC
Labels: duplicate

**Comment by rupamroy** [comment] 2017-04-07 22:38
This is issue #24258. I may be mistaken but looks like when i click the linked issue it brings me back to the current issue.

**Comment by mjbvz** [comment] 2017-04-07 22:55
Sorry, wrong one there. Should have been issue #23802
