### ISSUE TITLE
Can't insert a tab at the end of a line in a jade file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11478] opened 2016-09-02 22:29 UTC
Have a jade file with this content-

```
extends layout

block content
  h1= title
  p Welcome to #{title}
```

Put the cursor directly after layout, content, or title, and press tab, and nothing happens. If you type a space, then you can insert a tab.

If the cursor is after the } in the last line, pressing tab will replace the braces with spaces and move the cursor next to the #.

**Comment by mrmlnc** [comment] 2016-09-03 09:29
Hello @roblourens,

First, this is not a bug in VS Code. Is bug in Emmet, but only in the second case. Please, assign @egamma for full answer to this issue.

> Put the cursor directly after `layout`, `content,` or `title`, and press <kbd>tab</kbd>, and nothing happens. If you type a space, then you can insert a `tab`.

Emmet thinks it's abbreviation.

**Operators:**

  * `layout` - text (is abbreviation without expanding)
  * `content` - text (is abbreviation without expanding)
  * `title` - text (is abbreviation without expanding)
  * `title` + `space` - text, but Emmet walked out of the stream, because used a space.

> If the cursor is after the `}` in the last line, pressing tab will replace the braces with spaces and move the cursor next to the `#`.

**Operators:**

  * `#` - id (for example `#id`)
  * `{}` - text (for example `{title}`)

**Result:**

  * `#` + `{}` = `#`
  * `#id` + `{title}` = `#id title`

![2016-09-03_12-11-59](https://cloud.githubusercontent.com/assets/7034281/18224018/d99a8fea-71d0-11e6-837a-002062e65c22.gif)

**Comment by egamma** [comment] 2016-09-04 18:40
This is the same behaviour as in 1.4.

The analysis of @mrmlnc above is correct. This makes me wonder whether we should bind the `TAB` key to expand abbbreviation in `jade` files. The current behaviour is confusing as this issues shows.

**Comment by roblourens** [comment] 2016-09-04 20:00
I haven't used emmet or jade so I didn't know what to expect - I was just clicking around. Don't change it just because of me anyway.

**Comment by egamma** [comment] 2016-09-05 07:12
@roblourens thanks, but I expect that the current behaviour is confusing to Jade users since we have emmet enabled by default for Jade.

@mrmlnc 
What happens in the cases when the `TAB` appears to be swallowed is that `layout``TAB` -> gets expanded into `layout{0}` which appears as no expansion to the user. It inserts the same text and positions the cursor at the end. I was thinking that we detect this case and treat it like no expansion has happened and pass the `TAB` key back to the editor.

**Comment by mrmlnc** [comment] 2016-09-05 13:13
@egamma, yes, I thinks that is a good idea. Theoretically (at a rough guess), we could replace the expanded snippet in a `replaceContent` function (`editorAccessor.ts`). For example:

```ts
let codeSnippet = snippets.CodeSnippet.fromEmmet(value);
// If expanded snippet === value from editor without ${N}  at the end.
if (codeSnippet.lines.length === 1 && (codeSnippet.lines[0] === value.replace(/\$\{\d+\}$/, ''))) {
    codeSnippet.lines[0] += INDENT_BY_EDITOR
}
```

As far as I know, this is the only place where we can see expanded snippet.

**Comment by egamma** [comment] 2016-09-05 17:49
@mrmlnc this looks right. I'll add this to September milestone. Now that we have unit tests... we do this with unit tests 😎 

To give the `TAB` back to the editor we can do something like this.

```javascript
	this_editor.trigger('emmet', Handler.Tab, {});
```

**Comment by mrmlnc** [comment] 2016-09-05 17:57
@egamma, :+1:

**Comment by egamma** [comment] 2016-09-29 12:52
@mrmlnc was looking into fixing this. However, the above approach has the issue that inside replaceContent we cannot know anymore whether the replacement was triggered by a `tab` key/expand abbreviation. The call to replaceContent can also happen as a consequence of `Wrap with Abbreviation` and in this case inserting a TAB would be the wrong thing to do. 

Deferring until we have a better fix.

**Comment by mrmlnc** [comment] 2016-09-29 13:08
@egamma, Well, I'll think about it in my spare time.

**Comment by egamma** [comment] 2016-09-30 14:42
@mrmlnc I start to think that this should best be fixed in the Jade syntax profile of emmet. Filtering out proposal coming from emmet is a bit fishy and looks like a work around.

**Comment by mrmlnc** [comment] 2016-09-30 16:45
@egamma, Well,  in this case, we need to understand that this issue will be regarded very long time. Because Emmet is more dead than alive. Honestly, I don't know what to do. Most likely, temporary solution will be permanent.

Creator of Emmet a few months ago, wrote the following:

> PS: я через некоторое время собираюсь полностью переписать проект, там уже будут другого рода абстракции и более плотная интеграция с возможностями редакторов.
>
> https://github.com/emmetio/emmet/issues/455#issuecomment-230309555

**Short translation:** I am going to completely rewrite Emmet project (after some time) with more features.

**Comment by egamma** [comment] 2016-10-02 11:24
@mrmlnc thanks for the back ground.

Then I see the following options:

- disable the `TAB` expansion for emmet inside jade files. Jade users can use the command 'Expand Abbreviation' to get emmet expansion.

- we remember inside the ExpandAbbreviation actioin that the expansion was triggered from a Jade file using the `Expand Abbreviation`. We somehow pass this on to the editor accessor and only in this case we make the hack in `replaceContent` we discussed above.

**Comment by mrmlnc** [comment] 2016-10-02 12:04
> disable the `TAB` expansion for emmet inside jade files. Jade users can use the command `Expand Abbreviation` to get emmet expansion.

I think it's better to accept the fact that we have now. I myself use the Pug (ex. Jade) and use menu command every 5-10 seconds - it's bad idea (IMO).

All editors have exactly the same problem (Atom, ST) and most likely Visual Studio. In WebStorm Emmet doesn't work with Jade 🔮 .

**Comment by alexandrudima** [comment] 2016-10-28 09:29
Postponing to November.

**Comment by chrmarti** [comment] 2017-04-27 22:40
Tab after `#{title}` expands to `# title`, should this be excluded from expansion too?

**Comment by ramya-rao-a** [comment] 2017-04-28 17:35
@chrmarti That part I'd say is by design from emmet.

Good news is, in the new emmet extension, this is fixed. So I wouldn't spend much time here.

The TAB being swallowed though is fixed

**Closed by ramya-rao-a** 2017-04-28 17:35 UTC
Labels: bug, emmet, verification-found
