### ISSUE TITLE
Editor window does not activate when breakpoint hit.

### ISSUE THREAD

**Issue by JeffJustJeff** [Microsoft/vscode#22429] opened 2017-03-10 22:58 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|tslint|eg2|0.8.1|
|HTMLHint|mkaufman|0.3.3|
|tsimporter|pmneo|1.2.13|
|autoimport|steoates|1.2.2|;

---

Steps to Reproduce:

1. Set a breakpoint in your Typescript file
2. With multiple code windows open, hit the breakpoint
3. Execution stops at breakpoint. Must manually find window and breakpoint.

Window should come to front/activate (if open) or open and activate if not opened. Line containing current breakpoint should be visible in the editor window.

**Comment by isidorn** [comment] 2017-03-13 13:54
Duplicate of https://github.com/Microsoft/vscode/issues/21111

**Comment by JeffJustJeff** [comment] 2017-03-13 15:16
Not a duplicate of 21111. Issue 21111 specifies debugging two apps at the same time. I am only debugging a single application.

**Comment by isidorn** [comment] 2017-03-13 15:24
Ok, let's reopen to investigate

**Comment by isidorn** [comment] 2017-03-14 16:01
@JeffJustJeff works for me on my win10 machine. It nicely blinks in the status bar as being activated.

Can you please try reproducing this behavior with our smoke test application in the following 3 steps
1. clone https://github.com/Microsoft/vscode-smoketest-express
2. npm install
3. open in vscode, set breakpoint in index.js line 6, start debugging
4. open your browser at localhost:3000
5. does vscode get nicely activated?

If still does not work then it might be an electron issue on your WinNT

**Comment by isidorn** [comment] 2017-03-17 19:50
Closing until more data is provided. Once we have more information I can reopen to continue investigating

**Closed by isidorn** 2017-03-17 19:50 UTC
Labels: debug, needs more info
