### ISSUE TITLE
iPadOS: close terminal always focus into the editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#127832] opened 2021-07-01 23:51 UTC
I was testing https://github.com/microsoft/vscode/issues/125470 and found that whenever I close the terminal through the `x` button, it always focus the editor and brings up the on screen keyboard.

**Comment by isidorn** [comment] 2021-07-02 07:13
@rebornix good catch, thanks for reporting this.
This is coming from [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/layout.ts#L1554). Every time we close the panel for whatever reason we pass the focus to the editor.

This behaviour does not make a lot of sense on touch devices and we should not do it if the action is triggered using a `tap`. However that call is a bit too deep, and we do not really know what caused it.

Some options:
1) Add a somewhat ugly `isIos` check there to not focus the editor
2) Try to wire down if the event is caused by tap and in that case do not focus

@bpasero @sbatten what do you think?

**Comment by bpasero** [comment] 2021-07-02 09:16
I think another case is closing a notification toast. Maybe we should do a pass of all calls that focus the editor area and revisit for touch devices.

**Comment by isidorn** [comment] 2021-07-02 11:59
We could do a pass, but still the question remains: should we have a simple check "is touch device" or try to be smarter and hook down if triggered via touch or click.

**Comment by bpasero** [comment] 2021-07-02 12:18
I would do it based on the fact wether an external keyboard is attached to the iPad or not.

**Comment by isidorn** [comment] 2021-07-02 12:26
@bpasero good idea, but I could not find a way to detect if a keyboard is connected on an iPad.
Maybe @rebornix also tried this before and maybe has some ideas?

**Comment by bpasero** [comment] 2021-07-02 12:27
That is defnitley something we should bring forward to Apple then.

**Comment by isidorn** [comment] 2021-07-02 12:35
I filled this one https://bugs.webkit.org/show_bug.cgi?id=227618
Maybe @grorg or @alefragnani can help

**Comment by bpasero** [comment] 2021-07-02 12:41
I think as long as we cannot detect it I would make it hardcoded based on a `isIpadOs` check.

**Comment by rebornix** [comment] 2021-07-05 20:51
I doubt if iOS/iPadOS would expose this info to applications. +1 for checking `isIpadOS` directly unless it's triggered by `cmd+j`.

**Comment by isidorn** [comment] 2021-08-16 14:16
Since we can not detect, I have added an explicit `isIos` check for when the panel is closed. That should cover this case.

**Closed by isidorn** 2021-08-16 14:16 UTC
Labels: under-discussion, ios-ipados
