### ISSUE TITLE
Top line of terminal text gets cut off after latest release

### ISSUE THREAD

**Issue by bduffany** [microsoft/vscode#137457] opened 2021-11-18 15:51 UTC
Issue Type: <b>Bug</b>

The top line of text in the terminal gets cut off by a few px (I think at most 2 or 3px) sometimes. I can repro the issue by resizing the middle divider between terminals, but I'm not sure if the root cause of the issue is due to resizing the divider.

I am almost 100% certain this started happening after the latest release or the release before that.

Notice in this screenshot how the dot on the i / j are barely visible:

![image](https://user-images.githubusercontent.com/2414826/142449470-22e084ab-6450-413e-91f9-a9d04c7eed77.png)

This is a clean terminal (just pressed Ctrl+L to clear it), and it does not have a scrollbar so the problem is not just that I'm scrolled up and the text is only partially visible.

Video (all extensions are disabled):

https://user-images.githubusercontent.com/2414826/142450374-4951177b-d95c-44b8-8596-51f6e8d534ac.mp4

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 1542)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.30GB (16.14GB free)|
|Process Argv|--no-sandbox /home/b/code/bb --crash-reporter-id f2e8d752-f1e7-45c2-99de-f61c21d4c5b2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246:30401890

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-18 16:14
Looks like a duplicate of #137113

Are you able to test with [Insiders](https://code.visualstudio.com/insiders)?

**Comment by Tyriar** [comment] 2021-11-19 13:55
👍 we tweaked a lot of the layout code in https://github.com/microsoft/vscode/pull/136522

/duplicate

**Closed by Tyriar** 2021-11-19 13:55 UTC
