### ISSUE TITLE
TOC for Jupyter Notebook

### ISSUE THREAD

**Issue by ryanbehdad** [microsoft/vscode#96220] opened 2020-04-27 06:10 UTC
Hi,
I have migrated from running jupyter notebooks in the browser to VS Code. It has been an awesome experience. One of the biggest things I miss is TOC for the notebook. It was available for jupyter notebooks and lab through extensions. But, in the VS Code, I've not seen it.

I suggest adding a button at the top of the notebook page (next to "Clear All Outputs") to show/hide TOC.

Many thanks.

**Comment by datauduong** [comment] 2020-06-16 12:29
Azure Data Studio already have the TOC features

**Comment by zlhlianne** [comment] 2020-07-23 01:08
I am in much need of the table of contents and other extensions for Jupyter notebook in VS code, so I want to upvote this issue. But I am new in Github and not familiar with the functions. Would anyone let me know how I can upvote this issue? Is it just clicking the thumbs up?

**Comment by jrieken** [comment] 2020-08-20 08:49
/duplicate of https://github.com/microsoft/vscode/issues/98173

**Closed** 2020-08-20 08:50 UTC
Labels: *duplicate, feature-request, notebook
