### ISSUE TITLE
Terminal pty host unresponsive after closing a VS Code window

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117956] opened 2021-03-02 08:17 UTC
I've seen this happen a few times now, and this last time it seemed to happen right after I closed a VS Code window. After that, I got the following notification in all my other open VS Code windows.

![image](https://user-images.githubusercontent.com/641685/109618414-83ba2700-7b05-11eb-8903-7ff429d1933d.png)

Here is the Shared Process output
```
[2021-03-02 03:11:02.588] [sharedprocess] [warning] No ptyHost heartbeat after 6 seconds
[2021-03-02 03:11:07.592] [sharedprocess] [error] No ptyHost heartbeat after 12 seconds
[2021-03-02 03:11:40.245] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "4": Error: Could not find pty with id "4"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.shutdown (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35103)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2021-03-02 03:11:40.303] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "2": Error: Could not find pty with id "2"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.resize (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35219)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2021-03-02 03:11:40.838] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "2": Error: Could not find pty with id "2"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.shutdown (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35103)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by Tyriar** [comment] 2021-03-02 20:02
Going to look into whether we can wait for the process input to stop before actually killing the process for windows as another workaround for https://github.com/microsoft/vscode/issues/71966. This process can take a bit of time now if needed since it's off the window being shutdown which has limited time to react.

**Comment by Tyriar** [comment] 2021-03-02 20:19
It looks like we are using the same method as before where we indicate to dispose immediate.

https://github.com/microsoft/vscode/blob/af915f0bc4c136ad3c13d6323dbe993abaa3848f/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L304-L304

Perhaps it's different before because the window going down would more aggressively shut down its child processes?

**Comment by Tyriar** [comment] 2021-03-02 20:40
@eamodio @meganrogge we can consider bringing this in for the recovery build if we start seeing reports.

**Comment by donvanone** [comment] 2021-03-03 16:37
No, a few seconds after I open a second VSCode instance, this error message appears in both instances. It also happens if I open a second terminal in one instance

**Comment by Tyriar** [comment] 2021-03-03 16:44
@donvanone an extension may be closing the terminal, or it might be getting relaunched if an extension changes the environment (like the git extension will do when opening a new workspace). Does it happen if you open a new window and then wait 10 seconds before opening a terminal, such that extensions can activate?

**Comment by donvanone** [comment] 2021-03-04 07:35
I had the problem even with uninstalled extensions. But the good old "did you try turning it off an on again" helped. After a windows reboot, everything works fine

**Comment by Tyriar** [comment] 2021-03-11 15:58
To clarify the scope of this fix since @eamodio is still seeing lingering issues in insiders for this that we aren't able to nail down. Verified here means that the mechanism to delay killing the process on Windows for up to 5 seconds works as expected.

**Comment by DavyLandman** [comment] 2021-03-30 08:35
Don't know if this helps, but I've noticed that it consistently happens if I open a terminal in 2nd level (is that the vscode term for running vscode "inside" vscode?), after closing that 2nd level all terminals are stuck.

**Comment by creage** [comment] 2021-04-01 09:39
VSCode 1.55., the issue is till there.

Single instance of VSCode looks fine, but starting another instance fires the warning almost immediately, breaking terminals in both instances.

**Comment by XtremeGood** [comment] 2021-04-07 07:36
It did not happened with git console but happens a lot with powershell but git has this other problem https://stackoverflow.com/questions/62685569/error-while-installing-python-extensions-cant-open-file-directory-filename

**Comment by joshuaclausen** [comment] 2021-04-09 17:53
I've been getting this recently, though consistently throughout my day, while doing remote ssh sessions through the vscode terminal window.  I open a new terminal and then use wsl2, and within wsl2 doing the ssh sessions.  I experience this in both of the following VSCode versions:


Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043


Version: 1.56.0-insider (user setup)
Commit: 845efe5d8e31079cc858131c95c36103d9439e74
Date: 2021-04-09T09:50:06.816Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by ladarit** [comment] 2021-04-26 13:47
for me, even single instanse of vscode show this message, if i want to restart "watch" task

**Comment by Tyriar** [comment] 2021-04-27 19:06
Update: https://github.com/microsoft/vscode/issues/121336#issuecomment-827846740

**Comment by faydanube** [comment] 2021-05-04 05:31
2021-05-04
I hope that vscode will keep developing at a high speed while paying more attention to the most basic experience.

**Comment by jpelton-stroud** [comment] 2021-05-05 06:23
Started getting this error in VSCode 1.55.2 after upgrading to Chrome OS v90; appears to cause the whole VM to seize.  Persists after full powerwash & fresh VM/Code install, no exts enabled. :(

**Comment by LordMidi** [comment] 2021-05-06 08:48
I'm getting this error all the time since some months. If I start an npm script in VS Code this error occurs. So I had to switch to the real terminal. Hope this gets fixed...
Still happens with 1.56.0

**Closed** 2021-05-13 22:38 UTC
Labels: bug, terminal, terminal-conpty, windows

**Comment by SFeldman-Accenture** [comment] 2021-05-14 15:28
I am receiving this same error myself. I only have a few extensions installed and I've been extremely stable until I installed the PowerShell Extension. At that point I immediately receive the error that "The connection to the terminal's pty host process is unresponsive", as well as two others: "the language service could not be started", and "Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance"

I'm pretty new to using VS and programming in general so I'm not sure what to do about this.

**Comment by Tyriar** [comment] 2021-05-14 17:30
@SFeldman-Accenture this should be fixed in the [Insiders](https://code.visualstudio.com/insiders) build as of today, coming to stable in a month or so.

**Comment by SFeldman-Accenture** [comment] 2021-05-14 18:02
> @SFeldman-Accenture this should be fixed in the [Insiders](https://code.visualstudio.com/insiders) build as of today, coming to stable in a month or so.

Hey @Tyriar, forgive me if this is a dumb question but the Insiders build is kind of like a "beta" build? So there's the potential for it to have issues in other areas? Just weighing the pros and cons of getting the extension working vs. potentially having issues in other areas.

**Comment by Tyriar** [comment] 2021-05-14 18:04
@SFeldman-Accenture yes it is, you may get some instability but also access to new fixes/features. But this issue is fixed (finally), it just won't be available in stable until early next month.

**Comment by SFeldman-Accenture** [comment] 2021-05-14 18:30
I'm not sure if this is something I missed but the terminal doesn't let me tab to auto-complete anymore after installed Insiders. When I hit tab it moves the cursor out of the terminal console and onto a new area within VS Code. Is there a way to fix that?

**Comment by Vistur** [comment] 2021-06-02 10:29
I get this all the time even in the Insiders build and with no extensions. It started for me right after updating to macOS Big Sur v11.4

**Comment by Tyriar** [comment] 2021-06-02 12:10
@Vistur this is the only know case where this can happen on macOS https://github.com/microsoft/vscode/issues/119090

**Comment by RomanDavlyatshin** [comment] 2021-06-04 12:57
Getting this issue all the time at Windows10.
I'm opening plenty of VS code projects (usually 2-5 at the same time).
TBH it just got so unbearable, I launch external terminals manually whenever it's possible. (So basically every time, except when I'm using a debugger)

My system specs are
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z (3 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

Any feedback/fix suggestions are greatly appreciated

**Comment by Tyriar** [comment] 2021-06-04 13:06
@RomanDavlyatshin the new release which fixes this should be out next week.
