### ISSUE TITLE
Git commit input does not wrap text

### ISSUE THREAD

**Issue by Dan-Bird** [microsoft/vscode#147097] opened 2022-04-08 15:59 UTC
Issue Type: <b>Bug</b>

As shown in the screenshot, when typing into the Github commit input the text no longer wraps. 

I do not have VoiceOver running on my Mac. When I start VSCode I get the dialogue box asking if I am using one. 

I click 'No', and have assured that `"editor.accessibilitySupport": "off",` is in my settings JSON. 

I have also ran VSCode with `code --disable-extensions` and the issue still occurs. I have also closed all running applications and started VSCode again, and still have the issue.

I have tested with a fresh install of the insiders version, and I also get the same. Putting the `"editor.accessibilitySupport": "off",` within the settings JSON on the insiders build also didn't help. 
![Screenshot 2022-04-08 at 16 59 52](https://user-images.githubusercontent.com/27159748/162479537-f529e3c4-571a-43a1-853b-9ccdc16c35a6.png)

<img width="657" alt="Screenshot 2022-04-08 at 17 02 39" src="https://user-images.githubusercontent.com/27159748/162479798-35c3d7f6-09d7-42b0-b0e0-1982b5b50bdd.png">

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 9, 11|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|--crash-reporter-id 0366754e-1b97-4da0-b897-b730c4b15ad9|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
alignment|ann|0.3.0
vscode-color|ans|0.4.5
htmltagwrap|bra|0.0.7
vscode-svgviewer|css|2.0.0
ts-grammar-extended|dan|1.1.1
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
vscode-styled-jsx-languageserver|Div|1.3.1
vscode-styled-jsx-syntax|Div|1.3.1
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.5
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
vscode-pull-request-github|Git|0.40.0
terraform|has|2.21.0
hubl|Hub|0.15.0
rest-client|hum|0.24.6
RelativePath|jak|1.4.1
vue|jcb|0.1.5
vscode-styled-components|jpo|1.7.0
graphql-for-vscode|kum|1.15.3
hubspot-hubl-snippets|mag|0.2.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
azure-account|ms-|0.10.1
js-debug-nightly|ms-|2022.4.617
vsliveshare|ms-|1.0.5449
vetur|oct|0.35.0
vscode-jest|Ort|4.2.1
material-icon-theme|PKi|4.15.0
vscode-css-peek|pra|4.2.0
prisma|Pri|3.12.0
vscode-thunder-client|ran|1.16.0
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
jinjahtml|sam|0.17.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.5.0
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.18
vscode-icons|vsc|11.10.0
fig|wit|0.0.6
ReactSnippets|xab|2.4.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-04-08 16:08
> have assured that `"editor.accessibilitySupport": "off",` is in my settings JSON.

Did you check this at the Workspace level of Settings Editor, as well as the User level?

**Comment by Dan-Bird** [comment] 2022-04-08 16:24
> > have assured that `"editor.accessibilitySupport": "off",` is in my settings JSON.
> 
> Did you check this at the Workspace level of Settings Editor, as well as the User level?

Good Idea! I checked the workspace setting. It was set to `auto`. 

I changed it to `off` and restarted VSCode. Unfortunately the input still doesn't wrap.

**Comment by lszomoru** [comment] 2022-04-11 11:46
@alexdima, it looks like there might be another case in which wrapping is not working as expected.

**Comment by Dan-Bird** [comment] 2022-05-01 16:30
An update to this issue, today I opened VS Code on my personal Macbook (issue above is seen on one I use for work). 

I have never opened or used VoiceOver on my personal Mac, but I do have settings sync on VS Code. 

This issue has carried over to VS Code on my personal machine too. I tried to reset the `"editor.accessibilitySupport"` setting and the issue remained still.

**Comment by lszomoru** [comment] 2022-06-22 20:35
@alexdima, I believe that this is a duplicate of #142844.

**Comment by alexdima** [comment] 2022-06-23 12:08
Yes, let's track in #142844

**Closed by alexdima** 2022-06-23 12:08 UTC
Labels: bug, scm, editor-wrapping
