### ISSUE TITLE
Wayland support breaks with second display and scaling

### ISSUE THREAD

**Issue by pseidemann** [microsoft/vscode#174876] opened 2023-02-21 00:37 UTC
Type: <b>Bug</b>

I'm using vscode and vscodium with `--enable-features=UseOzonePlatform --ozone-platform=wayland` (and `"window.titleBarStyle": "custom"` to enable window decorations) which works fine, until I enable my second display. once the second display is enabled, vscode gets blurry as if wayland support is not working anymore. I made a video of the phenomenon:

https://user-images.githubusercontent.com/431162/220217469-3a6092c9-19de-454a-a36d-777947a39ae6.mp4

<br>

my main display is a 27" 3840x2160 60hz with 175% scaling.
my second display is a 23" 1920x1080 60hz with 100% scaling and rotated 90 degrees counter clock wise.
scaling is set normally in ubuntu settings and other electron apps work as expected (e.g. slack).

I can consistently reproduce this in vscode and vscodium.

Ubuntu 22.10 with all updates installed.

tested with `--disable-extensions`.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.19.0-31-generic
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.54GB (11.78GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --disable-extensions . --crash-reporter-id 502f5502-77bb-4ae2-9da8-f2ce7f2b99a0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by HubKing** [comment] 2023-02-24 12:21
I came here to ask about the same problem. I have two monitors with different DPI's (100% and 175%), and I have enabled fractional scaling under Wayland Gnome. When I ran VS Code as native Wayland (with the parameters you know),  it looked blurry on the 175% monitor. I saw other people's comments and disabled the other monitor (100%) and then VS Code looked better on the 175% monitor.

**Comment by pseidemann** [comment] 2023-02-28 21:12
I can confirm this bug exists also with 100% and 150% scaling, but does *not* exist with non-fractional/integer scaling, e.g. 100% and 200%.

**Comment by jon-dez** [comment] 2023-03-06 01:15
> I can confirm this bug exists also with 100% and 150% scaling, but does _not_ exist with non-fractional/integer scaling, e.g. 100% and 200%.

Not true for me. The blurry text is still present when I have one monitor at 100% and another at 200%.

VSCode version 1.76

**Comment by jon-dez** [comment] 2023-03-06 01:19
It appears that the blurriness does not apply to the context menu bar and the right click menu.

**Comment by TinoCle** [comment] 2023-03-22 13:30
Still breaking, just when I enable the fractional scaling on ubuntu.

**Comment by gkssf** [comment] 2023-03-29 21:47
I'm having the same issue. Fractional scaling breaks wayland support.

**Comment by Mxbonn** [comment] 2023-04-09 10:31
Same issue here.

**Comment by fivkovic** [comment] 2023-04-15 02:32
I was able to reproduce the same issue and behavior on Ubuntu 22.04.2 LTS _(GNOME Version 42.5)_.

The only VSCode setting that was changed from default is `window.titleBarStyle` which is set to `custom` value. All other settings are default. The issue is present both when extensions are enabled and with disabling extensions using the `--disable-extensions` flag.

In my specific case of display settings _(see screenshots below)_ it seems that the blur is only present when the window is located on the built-in (higher-resolution) display. When moving the window to the external (smaller-resolution) display, the blur is not present.

After additional exploration, I found that changing the _Scale_ to an equal value for both displays, either:
- for the built-in display from 200% to 100%, or
- for the external display from 100% to 200%

seemingly makes the issue disappear and the blur is not present anymore (also when moving the window between the displays).

Based on that, and taking into consideration that in my specific case the _Fractional Scaling_ is not enabled, it looks like using _Fractional Scaling_ is not the root cause of this issue as stated in the previous comments. Although I am not entirely sure, it seems more likely that the base value used for scaling is the minimal _Scale_ value for all displays, and that the window is being downscaled/upscaled for the difference, based on the current display it's located on.

I hope that this information will contribute to quickly resolving the issue.

# Issue report

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.19.0-38-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (10.94GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations --disable-extensions --crash-reporter-id 985ff925-0740-46c8-8790-b7698ead8513|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
azdwalk:30687957
pythonms35:30701012
pythonfmttext:30710681

```

</details>



# Display settings




Built-in Display             |  External Display
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/129757506/232177230-28e171e1-f6aa-4b9f-ab14-523e3993488e.png) |  ![image](https://user-images.githubusercontent.com/129757506/232177241-823e9f21-ea3a-4a80-a7b2-f8dc3be460e8.png)

**Comment by deepak1556** [comment] 2023-04-17 08:38
Can you test if the issue continues to happen with our insiders version https://code.visualstudio.com/insiders which comes with an updated version of the runtime.

**Comment by Mxbonn** [comment] 2023-04-17 10:27
> Can you test if the issue continues to happen with our insiders version https://code.visualstudio.com/insiders which comes with an updated version of the runtime.

For me the issue is indeed resolved when using the insiders version.

**Comment by fivkovic** [comment] 2023-04-17 17:15
I can confirm that the issue is not present anymore in the insiders version.

```
Version: 1.78.0-insider
Commit: 1e774371f2ca5f6618b4f40fdc72ce7518443014
Date: 2023-04-17T05:27:45.204Z
Electron: 22.4.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-38-generic
Sandboxed: Yes
```

**Comment by HubKing** [comment] 2023-04-18 07:53
Yeah, I didn't even use Insider version, but I tested just the regular 1.77.3, it no longer looked blurry.

**Comment by pseidemann** [comment] 2023-04-18 15:00
@deepak1556,
I don't have a multi display setup currently so if other people say it's fixed, feel free to close as resolved

**Closed** 2023-04-21 15:36 UTC
Labels: bug, upstream, linux, chromium, wayland, fixed-in-electron-22

**Comment by TylerLeonhardt** [comment] 2023-04-28 00:15
verified based on https://github.com/microsoft/vscode/issues/174876#issuecomment-1511769961
