### ISSUE TITLE
Minimap doesn't react to theme changing

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#21312] opened 2017-02-23 19:16 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (0b27b528a7aac070bced1239310144d0763823bd, 2017-02-23T07:08:55.971Z)
- OS Version: Linux x64 4.8.0-34-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.0.5|
|vscode-terminal-here|Tyriar|0.0.5|
|vscode-svgviewer|cssho|1.3.1|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.0.1|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.1|
|csharp|ms-vscode|1.7.0|
|seti-icons|qinjia|0.1.3|
|annotator|ryu1kn|0.10.1|;

---

![image](https://cloud.githubusercontent.com/assets/2193314/23274955/7a31aed2-f9b9-11e6-84c0-f39f01fb761f.png)

**Comment by alexandrudima** [comment] 2017-02-23 19:58
Duplicate of #21007

**Closed by alexandrudima** 2017-02-23 19:58 UTC
