### ISSUE TITLE
[javascript] Intellisense issues in large JS project

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#4974] opened 2016-04-05 18:51 UTC
- VSCode Version: 0.10.14
- OS Version: Windows 10

After I upgraded to 10.13, and soon after to 10.14, the autocomplete is not triggering. At first I thought that by moving away from salsa for javascript projects would have broken something, but reading your blog post gives me the idea that intellisense would still _work_, albeit not as well as with salsa. But then I found out that even simple words _in the same file_ are not showing up when I start typing words.

Is anyone else also facing this issue?

**Comment by egamma** [comment] 2016-04-06 20:30
No code changes happened in the area of intellisense and salsa. So I doubt that this has to do with 0.10.14 but it is a more general problem. I also don't full understand the problem you are seeing.

Can you pls add an animated gif that illustrates the problem you are seeing together with the snippet.

**Comment by kumarharsh** [comment] 2016-04-06 21:19
After your comment, I took a look again, and found that the problem is occuring inside *any* file within my project (there is a jsconfig.json file at the root of this project). If I create a new Untitled file, set the Language Mode to javascript, and type, then intellisense and snippets are working properly.

I've set `"javascript.validate.enable"` to `false`. but even setting it to `true` doesn't help.

**Comment by kumarharsh** [comment] 2016-04-06 21:19
Here is a gif showing the autocomplete not triggering:

![test](https://cloud.githubusercontent.com/assets/760112/14333244/50aaf6d2-fc6b-11e5-9fd0-f51c6df3039c.gif)

**Comment by kumarharsh** [comment] 2016-04-06 21:37
Removing the jsconfig.json file fixed the issue (but it also took away all the benefits ;) )

FYI, my jsconfig file looks like this:

```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2015",
    "experimentalDecorators": true
  }
}
```

**Comment by kumarharsh** [comment] 2016-04-06 21:46
on a related note, if salsa can indeed by disabled by setting `javascript.validate.enable: true` then why does the use of decorators still say:
```
[js] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

when the jsconfig file is removed, or the `experimentalDecorators` key removed?

**Comment by egamma** [comment] 2016-04-07 08:55
>Removing the jsconfig.json file fixed the issue (but it also took away all the benefits ;) )

How did the `jsconfig.json` file look like when intellisense did not work? 

If you have no `jsconfig.json` then the `node_modules` folder is excluded by default. Does this work:
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2015",
    "experimentalDecorators": true
  },
  exclude: ["node_modules]   
}

**Comment by egamma** [comment] 2016-04-07 09:01
>if salsa can indeed be disabled by setting javascript.validate.enable: true then why does the use of decorators still say...

Interesting, pls file a separate issue with a repro snippet on this. What file suffix are you using?

**Comment by kumarharsh** [comment] 2016-04-07 10:35
> How did the jsconfig.json file look like when intellisense did not work?

[Like this](https://github.com/Microsoft/vscode/issues/4974#issuecomment-206582529)

**Comment by kumarharsh** [comment] 2016-04-07 10:35
I've also found that just keeping an **empty** file of the name `jsconfig.json` kills autocomplete completely, snippets included.

**Comment by kumarharsh** [comment] 2016-04-07 10:56
On opening a new folder with code, it seems to be working *as expected* - the autocomplete seems to be coming as well as the snippets. Suddenly I'm really at a loss why it's not working with my actual project folder...

* There is no project-level setting
* There are **885** first-level folders in the `node_modules` directory on account of me using npm@3
* ... i don't know... :disappointed: I'll keep looking

**Comment by egamma** [comment] 2016-04-07 11:58
Did my suggested jsconfig.json help in your existing project? https://github.com/Microsoft/vscode/issues/4974#issuecomment-206768115

The empty excludes array is wrong and you must exclude the node_modules folder and may be others, pls see https://github.com/Microsoft/vscode-docs/blob/vnext/docs/languages/javascript.md#excludes

**Comment by kumarharsh** [comment] 2016-04-08 08:02
It did help, only a little though. I put the config in yesterday. Didn't work, so I forgot about it.
Today when I opened my editor, it magically started giving me auto-suggestions, snippet completions, and everything else. Then I opened my jsconfig file, made some changes - AND reverted those changes, and saved it. And everything went back to as it was.

I have a suspect that it's my project which vscode can't handle. Doing a:

```(gci src -Recurse).length```

gives a total file count of `1113` which are mostly `es6 + jsx` files.

There are more behaviours which also support this theory (atleast in my mind):
* vscode-eslint has a noticeable lag in showing errors - 3-4 seconds after I type something, it underlines the line - and it seems like all the errors in a queue are shown one after another until it catches up with the current state of the file.
* intellisense shows up in fits and starts sometimes, on functions which I had my cursor on a couple of seconds ago.

**Comment by egamma** [comment] 2016-04-08 13:36
>the Configure Excludes notice shows up in the bottom strip in vscode telling me that my src has many files.

This is the interesting one. The language service has a limit on the numbers of files it can load, it warns when 500 files are loaded. So when you excluded the node_modules then you reduced the number of files, so this helped.

Can you try to exclude additional folders with generated, packaged .js files (e.g. webpack archives) that you do not consider as source files?

You add a jsconfig.json file in subfolders of your large project and then open each folder in a new VS Code window. Obviously then you do not get cross-folder Intellisense and you need to setup a typings folder for each subfolder.

Regarding:
>vscode-eslint has a noticeable lag in showing errors - 3-4 seconds after I type something, it underlines the line - and it seems like all the errors in a queue are shown one after another until it catches up with the current state of the file.

This is interesting since eslint operates on a single file and does this in a separate process, so this should not affect the tsserver.  @dbaeumer can you explain how this can happen?

**Comment by dbaeumer** [comment] 2016-04-13 07:37
@egamma this could happend when:

- the JS files are really really big. 
- the extension host is busy. All eventing and coordination in the extension host is sync right now (more or less). So if for example another extension is blocking the extension host (could even be the TS/JS extension) then no other extension can do something.

**Comment by kumarharsh** [comment] 2016-04-13 07:44
@dbaeumer The JS files themselves are not so big. There are just too many (~1k). I do think it's because of your second point.

**Comment by dbaeumer** [comment] 2016-04-13 07:46
@kumarharsh the eslint checker has only the files that are open in the editor. It doesn't validate them all. So the total amount doesn't count as long as you don't open them all.

**Comment by dbaeumer** [comment] 2016-04-13 07:49
Assuming that you don't open all files there must be something else. Are you able to share your project?

**Comment by kumarharsh** [comment] 2016-04-13 10:37
I don't open all the files. Only have ~10 in the working directory. The project is a private project...

**Comment by d4rkr00t** [comment] 2016-04-15 13:24
I've almost the same issue with intellisense. On a big project autocomplition becomes sluggish and loading suggestions list takes a while.

**Comment by egamma** [comment] 2016-04-17 13:39
>I've almost the same issue with intellisense. On a big project autocomplition becomes sluggish and loading suggestions list takes a while.

@d4rkr00t did you exclude files as recommended here https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson

**Comment by d4rkr00t** [comment] 2016-04-17 18:10
Yes I did. I excluded all generated files and all external dependencies, but there are a lot of files in project anyway.

**Comment by egamma** [comment] 2016-04-18 12:25
@d4rkr00t do you have some sizing of your project, e.g., how many JS files?

**Comment by d4rkr00t** [comment] 2016-04-18 12:30
It's huge about 5k js files.

**Comment by d4rkr00t** [comment] 2016-04-18 12:31
And it's only not ignored ones. Otherwise it's about 40k files :)

**Comment by kumarharsh** [comment] 2016-04-19 05:52
Don't *even* count node_modules! :stuck_out_tongue:

**Comment by egamma** [comment] 2016-04-22 15:29
@d4rkr00t can you partition the project by adding jsconfig.json files in subfolders and opening code on the subfolders?

**Comment by d4rkr00t** [comment] 2016-05-04 19:39
@egamma yes, sure, i'll try

**Comment by rvaidya** [comment] 2016-11-23 21:14
VSCode version: latest Insiders
Typescript version: 2.1.1

Intellisense gets stuck on "Loading..." after I install a new npm package or leave VS Code running for a few hours.  Do I need to create both tsconfig.json and jsconfig.json (with node_modules excluded) or do I only need tsconfig.json?

**Comment by waderyan** [comment] 2016-11-28 20:25
@rvaidya can you share your workspace?

**Comment by waderyan** [comment] 2016-12-09 23:04
Closing as we've added a lot of work here sense April. If someone has a workspace that we can reproduce this issue then we can reopen and continue discussing. Thanks for the feedback! Cheers.

**Closed by waderyan** 2016-12-09 23:04 UTC
Labels: needs more info, typescript

**Comment by charliedavison** [comment] 2016-12-15 10:54
Just had this exact issue following upgrading to 1.8 this morning. Deleting the jsconfig file re-enabled intellisense, putting it back kills it again. Included my jsconfig.json file below.

`{
	// See https://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	"exclude": [
		"node_modules",
		"bower_components",
		"jspm_packages",
		"tmp",
		"temp"
	]
}

However unlike other commentors my project folder is not large, we only have <150 JS files.

**Comment by waderyan** [comment] 2016-12-16 19:09
@charliedavison can you share your project so I can clone it on my end?

**Comment by jeffijoe** [comment] 2017-11-01 10:54
@charlespierce I have the same issue; deleting the jsconfig restores intellisense, having it present kills it.
