### ISSUE TITLE
The code prompt expires after a period of time

### ISSUE THREAD

**Issue by esshs2019** [microsoft/vscode#174335] opened 2023-02-14 12:45 UTC
Type: <b>Bug</b>

The recent code prompt is always invalid after a period of time. You need to restart the application to take effect.

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (1.44GB free)|
|Process Argv|--crash-reporter-id bdc307fb-22fe-4445-9b13-4d055d8a90e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
FreeMarker|dco|0.0.9
gitlens|eam|13.2.0
copilot|Git|1.73.8685
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.75.2023020809
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
cmake-tools|ms-|1.13.45
cpptools|ms-|1.13.9
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vetur|oct|0.36.1
vscode-thunder-client|ran|2.4.1
fabric8-analytics|red|0.3.6
java|red|1.14.0
vscode-xml|red|0.24.0
markdown-preview-enhanced|shd|0.6.7
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.10.1
vscode-spring-initializr|vsc|0.11.2
volar|Vue|1.0.24
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by sandy081** [comment] 2023-02-15 13:47
> The recent code prompt is always invalid after a period of time. 

May I know what prompt are you talking about? Can you please share a gif/video/screenshot?

**Comment by esshs2019** [comment] 2023-02-17 00:11
After a period of time, "Quick Fix.." always loading.
![image](https://user-images.githubusercontent.com/50191310/219515059-1b7d55a3-d2b9-4282-8a2e-ed306d143c51.png)

Restart the vscode, "Quick Fix.." is OK. 
![image](https://user-images.githubusercontent.com/50191310/219515550-c707f320-fca4-43a6-a12d-cf46833c3325.png)

**Comment by esshs2019** [comment] 2023-02-17 00:40
![image](https://user-images.githubusercontent.com/50191310/219520157-ed8abf04-b728-4382-a13c-613f27babd59.png)
Always loading again.

**Comment by sandy081** [comment] 2023-02-17 16:58
Can you please provide steps to reproduce?

@mjbvz Assigning this to you because I assume this is related to code actions.

**Comment by esshs2019** [comment] 2023-02-19 01:22
Unable to provide.It appears when it is used.Sometimes a few minutes, sometimes a few hours.

**Comment by mjbvz** [comment] 2023-02-20 13:19
Please file this against the Java extension (assuming this is for Java code)

**Closed by mjbvz** 2023-02-20 13:19 UTC
Labels: info-needed

**Comment by esshs2019** [comment] 2023-02-21 00:49
Can it be solved?
