### ISSUE TITLE
Invalidating stale cache entries

### ISSUE THREAD

**Issue by anudeep3998** [Microsoft/vscode#11795] opened 2016-09-09 18:53 UTC
- VSCode Version: 1.5.1
- OS Version: Win 8

I moved some files from one folder to another, and when I  use Ctrl+P to open some files, the suggestions still show the file in the old folder and the new, though it is only present in the new. The old entry is present in the 'recently opened' section. When clicked on the old entry, it just fails and asks if it should create a new file there. 

I tried reproducing it with a small project, but I can't seem to be able to, so I don't know how this came to be like this in the first place.

Nevertheless, can some option for the user in the menu to trigger invalidating cache and re-building it ? I couldn't find something like that, which might be useful in this as well as similar cases.

![capture](https://cloud.githubusercontent.com/assets/5004036/18399019/2c3c46a0-769d-11e6-8d7f-d82d64323bed.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5004036/18399018/2c3c014a-769d-11e6-9733-0e6c393586ea.PNG)

TIA

**Comment by calebmer** [comment] 2016-10-14 17:03
I typically rename files in my project a lot, and recently I renamed a lot of files. The search still uses the old file names. How would one manually invalidate or clear the cache?

**Comment by chrmarti** [comment] 2016-10-28 16:30
There are Clear Editor History and Remove From Editor History commands.

**Comment by chrmarti** [comment] 2016-10-28 17:16
@bpasero We're not cleaning up the history automatically when files are moved/deleted (unless the file happens to be open in an editor). A simple approach could be to check if the files still exist before serving up the list in HistoryService.getHistory() - that will involve making it async and moving history.ts to 'electron-browser' from what I see. Any ideas / concerns from your side?

**Comment by anudeep3998** [comment] 2016-10-28 23:50
Huh, cool. Those options work. Didn't know they existed already! Making it automated would be great.

**Comment by bpasero** [comment] 2016-10-30 06:01
@chrmarti if you follow the trace of the [`History.remove()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L409) method you can see that we do remove entries if we detect them deleted on the file system. Of course this does not protect us from dropped file events or deletions that happen between restarts of Code.

I would not want to do all the disk access to validate the history each time (up to 200 entries), we never did that and I think its fine. We do remove an entry one it failed to open from history automatically.

Somewhat related though: https://github.com/Microsoft/vscode/issues/12665

**Comment by chrmarti** [comment] 2016-10-31 14:57
Only files removed/moved that are open in an editor trigger `History.remove()`. What happens more often - it seems - is that the user renames a folder and the history entries for files in that folder become stale.

**Comment by bpasero** [comment] 2016-10-31 15:02
That is a regression that I introduced and should fix, thanks for finding out.

**Comment by bpasero** [comment] 2016-10-31 15:03
Filed https://github.com/Microsoft/vscode/issues/14761

**Comment by chrmarti** [comment] 2016-10-31 17:44
@bpasero It might still make sense to check the history entries for existence on disk after startup. Should we cover that with this issue?

**Comment by bpasero** [comment] 2016-11-01 05:48
@chrmarti I think this is covered with https://github.com/Microsoft/vscode/issues/12665

There are many things in local storage that would benefit from validation after startup. To me the only solution is to detect file events between restarts, anything else is a custom hack. You end up building 2 layers of validation (the one using file events and the other by checking each and every file for existence) which is bad design.

As for detecting file events between restarts, we would need to persist the state of the file system and be able to make a diff after startup to reconcile

**Comment by bpasero** [comment] 2016-11-01 09:38
@chrmarti this recorded file events feature would also be interesting if we ever build a file index that is persisted on disk. To update the index, the missed file events should be played back right after startup.

**Comment by chrmarti** [comment] 2016-11-01 14:37
Duplicate of #12665

**Closed by chrmarti** 2016-11-01 14:37 UTC
Labels: search
