### ISSUE TITLE
Error when trying to Open Changes in GitHub Issues notebook

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#111665] opened 2020-12-01 19:36 UTC
Testing #111552, focusing on diffing from https://github.com/microsoft/vscode/issues/109549 

Make a change to GitHub Issues notebook

Navigate to source control viewlet, "Open Changes:"

![image](https://user-images.githubusercontent.com/25310137/100787743-f3b2f700-33c8-11eb-87fd-8791df95b023.png)

Got error message: "Unable to open 'XYZ.github-issues (Working Tree)': e.load is not a function."

![image](https://user-images.githubusercontent.com/25310137/100787485-928b2380-33c8-11eb-91d8-82317beb0592.png)

**Comment by bamurtaugh** [comment] 2020-12-01 19:39
I realize this actually also happens when I try just clicking on the file from the source control viewlet after I closed it- I get the same error message and am unable to open/load the file:

![image](https://user-images.githubusercontent.com/25310137/100788335-c9156e00-33c9-11eb-9a74-f2c87b1d3a88.png)

**Comment by rebornix** [comment] 2020-12-02 17:14
@bamurtaugh thanks for the report, it's a duplicate of https://github.com/microsoft/vscode/issues/111599 and already fixed!

**Closed by rebornix** 2020-12-02 17:14 UTC
