### ISSUE TITLE
Sign in with GitHub account failed in administrator mode

### ISSUE THREAD

**Issue by 928PJY** [microsoft/vscode#109214] opened 2020-10-23 07:43 UTC
- Version: 1.50.1 (system setup)
- Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
- Date: 2020-10-13T15:06:15.712Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open VS Code in administrator mode
2. Sign in with GitHub account, after sign in succeeded and credential returned to the VS Code, the following error occurs
![image](https://user-images.githubusercontent.com/17958546/96970524-6ae1a980-1546-11eb-94fe-b35fc8d046a2.png)
![image](https://user-images.githubusercontent.com/17958546/96970536-6fa65d80-1546-11eb-9738-e8defcc16180.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-10-23 22:28
@joaomoreno Is the protocol handler expected to work in this scenario?

**Comment by 928PJY** [comment] 2020-10-26 05:24
Maybe the same rooot cause with this issue #6560

**Comment by joaomoreno** [comment] 2020-10-26 13:19
Yeah dupe of #6560

**Closed by joaomoreno** 2020-10-26 13:19 UTC
