### ISSUE TITLE
Double-click tab to open in new window

### ISSUE THREAD

**Issue by tiagosiebler** [microsoft/vscode#83918] opened 2019-11-04 12:35 UTC
This aligns tab-functionality with other editors. A quick double-click on a tab should pop it out into a new window, allowing for quick multi-tasking without interrupting a workflow.

**Comment by IllusionMH** [comment] 2019-11-04 15:19
If you need it in separate window (for example to drag on second monitor) than it is currently impossible.

/duplicate of existing requests #10121 (enabler), #8171, and #2686.

Unfortunately in the meantime only workaround will be using [Duplicate Workspace in New Window](https://code.visualstudio.com/updates/v1_24#_duplicate-workspace-in-new-window) but it is resources heavy.

If you are sure that this issue is closed by mistake let developers know with more details about your request.

**Closed** 2019-11-04 15:19 UTC
Labels: *duplicate
