### ISSUE TITLE
Intelligence are sometimes annoying

### ISSUE THREAD

**Issue by hua03** [Microsoft/vscode#46612] opened 2018-03-27 04:11 UTC
- VSCode Version: 1.21.1
- OS Version: Windows10
![image](https://user-images.githubusercontent.com/19561959/37946289-38915cca-31b7-11e8-8fb0-684a7cd74501.png)

Steps to Reproduce:

1. Paste the following code into  .js file

```js
var person = {}
Object.defineProperty(person, 'name', {
  value: '尼古拉斯凯奇',
  enumerable: true
})
```

2. Enter `,` after this `enumerable: true`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-03-27 07:10
Duplicate of https://github.com/Microsoft/TypeScript/issues/22106 + https://github.com/Microsoft/TypeScript/issues/1150

**Closed by mjbvz** 2018-03-27 07:10 UTC
