### ISSUE TITLE
Window State According To Git Branch

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#28164] opened 2017-06-07 05:48 UTC
- VSCode Version:
- OS Version:

Feature:

1. Can VScode preserve its window state according to git branch? As Branch Changes the working files and working context changes. This feature will help for alot in day to day work in different branches.

**Comment by michelkaporin** [comment] 2017-06-07 08:55
Duplicate of #15824

**Closed by michelkaporin** 2017-06-07 08:55 UTC
