### ISSUE TITLE
osx small icon looks corrupted after 1.55 update

### ISSUE THREAD

**Issue by massimo-cassandro** [microsoft/vscode#120804] opened 2021-04-08 08:52 UTC
- VS Code Version: 
Versione: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Data: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
Sistema operativo: Darwin x64 20.3.0

- OS Version: OSX 11.2.3

Steps to Reproduce:

1. Install VSCODE
2. Look for small app icon in app list as in this screenshot

![Schermata 2021-04-08 alle 10 35 45](https://user-images.githubusercontent.com/1047169/113997228-39d90500-9858-11eb-81d4-a11a2edccf12.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2021-04-08 08:53
/duplicate of #120305 and will be fixed in upcoming 1.55.1

**Closed** 2021-04-08 11:18 UTC
Labels: *duplicate
