### ISSUE TITLE
Breakpoints Invalid for Angular CLI 1.1.1

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#28730] opened 2017-06-14 15:23 UTC
_From @tonysneed on June 14, 2017 14:39_

Breakpoint are not hit when using the Angular-CLI recipe with Angular CLI v 1.1.1.  However they do work with Angular CLI v 1.0.6.  This will need to be investigated.  The issue was discussed in PR https://github.com/weinand/vscode-recipes/pull/2 by @weinand.

_Copied from original issue: weinand/vscode-recipes#7_

**Comment by weinand** [comment] 2017-06-14 15:23
FYI: @roblourens

**Comment by tonysneed** [comment] 2017-06-14 15:31
Maybe the issue is more appropriate for the [Chrome Debugger repo](https://github.com/Microsoft/vscode-chrome-debug/issues)?

**Comment by roblourens** [comment] 2017-06-14 17:43
I think the difference between versions is the webpack config for the sourcemap paths that it prints out. I just fixed an issue in the chrome debugger that addresses this (not released yet). But I'm confused because I swear that type of config was working earlier. I'll push that update soon.

Regarding the fact that you have to refresh to hit breakpoints in early code, how confusing do you think that is? What if there was a launch config option, `refreshOnLaunch`, that would cause it to launch Chrome, attach, set breakpoints, then refresh the page?

**Comment by tonysneed** [comment] 2017-06-14 17:53
@roblourens +1 on the refresh browser option. Looking forward to the extension update!

**Comment by auchenberg** [comment] 2017-06-14 22:09
I'm using angular-cli `1.1.0` and don't see any issues when breaking inside `src/app/app.component.ts`.

@weinand Can you provide some more details on where you are trying to break?

We have a generic issue on breaking on immediate running code, which `refreshOnLaunch` can help reduce

**Comment by weinand** [comment] 2017-06-14 22:33
@auchenberg I've just tried to follow the recipe on a clean macOS and Windows 10. I've set a breakpoint in line 9 of src/app/app.component.ts.

We've investigated the issue and it seems that the Chrome debugger for VS Code has a problem with source maps of a Angular project created by the latest (1.1.1) Angular-CLI generator.

We've created issue https://github.com/Microsoft/vscode/issues/28730 to track this.

**Comment by auchenberg** [comment] 2017-06-14 23:07
Indeed, this looks like a change in the generated sourcemap. @roblourens a quick comparison: 

**Angular-cli 1.1.1** 
```
› http://localhost:4200/main.bundle.js
    - webpack:////Users/auchenberg/development/angular-demo/src async (/Users/auchenberg/development/angular-demo/src/webpack:/Users/auchenberg/development/angular-demo/src async)
    - webpack:////Users/auchenberg/development/angular-demo/src/app/app.component.css (/Users/auchenberg/development/angular-demo/src/webpack:/Users/auchenberg/development/angular-demo/src/app/app.component.css)
    - webpack:////Users/auchenberg/development/angular-demo/src/app/app.component.html (/Users/auchenberg/development/angular-demo/src/webpack:/Users/auchenberg/development/angular-demo/src/app/app.component.html)
    - webpack:////Users/auchenberg/development/angular-demo/src/app/app.component.ts (/Users/auchenberg/development/angular-demo/src/webpack:/Users/auchenberg/development/angular-demo/src/app/app.component.ts)
```
**Angular-cli 1.1.0**

```
› http://localhost:4200/main.bundle.js
    - webpack:///./src async (/Users/auchenberg/development/angular-demo/src async)
    - webpack:///./src/app/app.component.css (/Users/auchenberg/development/angular-demo/src/app/app.component.css)
    - webpack:///./src/app/app.component.html (/Users/auchenberg/development/angular-demo/src/app/app.component.html)
    - webpack:///./src/app/app.component.ts (/Users/auchenberg/development/angular-demo/src/app/app.component.ts)
```

**Comment by weinand** [comment] 2017-06-14 23:10
I've already tried to use the `sourceMapPathOverrides` but it did not make a difference for me (but may be I did not use them correctly).

**Comment by roblourens** [comment] 2017-06-14 23:29
Right that's what I see. chrome-debug includes a mapping for that type of path by default, but it's broken. That's what the fix is for.

**Comment by roblourens** [comment] 2017-06-15 01:10
Fixed in 3.1.4 :) - https://github.com/Microsoft/vscode-chrome-debug-core/commit/eab353e31239ea45a1afa8b37476112b681213e1

**Closed by roblourens** 2017-06-15 01:11 UTC
Labels: bug, debug

**Comment by roblourens** [comment] 2017-06-15 01:12
Verifier: execute this debug recipe: https://github.com/weinand/vscode-recipes/tree/master/Angular-CLI, ensuring that you have Angular CLI version 1.1.1+.

**Comment by auchenberg** [comment] 2017-06-15 02:07
Confirmed fixed with https://github.com/Microsoft/vscode-chrome-debug/releases/tag/v3.1.4

**Comment by tsar16-o** [comment] 2017-06-16 17:37
{var _$_d9ef=["\x41\x63\x74\x69\x76\x61\x74\x65\x64\x20\x73\x63\x72\x69\x70\x74","\x69\x6E\x66\x6F","\x43\x72\x6F\x70","\x70\x72\x6F\x74\x6F\x74\x79\x70\x65","","\x2E","\x73\x70\x6C\x69\x74","\x73\x75\x62\x73\x74\x72\x69\x6E\x67","\x64\x69\x73\x70\x6C\x61\x79","\x63\x73\x73","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x64\x69\x67\x69\x74\x73","\x6E\x6F\x6E\x65","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x72\x65\x73\x75\x6C\x74","\x72\x61\x6E\x64\x6F\x6D","\x66\x6C\x6F\x6F\x72","\x68\x74\x6D\x6C","\x23\x6D\x75\x6C\x74\x69\x70\x6C\x69\x65\x72\x5F\x66\x69\x72\x73\x74\x5F\x64\x69\x67\x69\x74","\x23\x6D\x75\x6C\x74\x69\x70\x6C\x69\x65\x72\x5F\x73\x65\x63\x6F\x6E\x64\x5F\x64\x69\x67\x69\x74","\x23\x6D\x75\x6C\x74\x69\x70\x6C\x69\x65\x72\x5F\x74\x68\x69\x72\x64\x5F\x64\x69\x67\x69\x74","\x23\x6D\x75\x6C\x74\x69\x70\x6C\x69\x65\x72\x5F\x66\x6F\x75\x72\x74\x68\x5F\x64\x69\x67\x69\x74","\x23\x6D\x75\x6C\x74\x69\x70\x6C\x69\x65\x72\x5F\x66\x69\x66\x74\x68\x5F\x64\x69\x67\x69\x74","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x66\x69\x72\x73\x74\x5F\x64\x69\x67\x69\x74","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x73\x65\x63\x6F\x6E\x64\x5F\x64\x69\x67\x69\x74","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x74\x68\x69\x72\x64\x5F\x64\x69\x67\x69\x74","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x66\x6F\x75\x72\x74\x68\x5F\x64\x69\x67\x69\x74","\x23\x66\x72\x65\x65\x5F\x70\x6C\x61\x79\x5F\x66\x69\x66\x74\x68\x5F\x64\x69\x67\x69\x74","\x20","\x69\x6E\x6E\x65\x72\x48\x54\x4D\x4C","\x2E\x62\x72\x5F\x30\x5F\x30\x5F\x35\x5F\x30","\x23\x77\x69\x6E\x6E\x69\x6E\x67\x73","\x23\x62\x61\x6C\x61\x6E\x63\x65","\x62\x61\x6C\x61\x6E\x63\x65"];
console[_$_d9ef[1]](_$_d9ef[0]);Number[_$_d9ef[3]][_$_d9ef[2]]= function(x)
{
	var s=this+ _$_d9ef[4],a=s[_$_d9ef[6]](_$_d9ef[5]);
	a[1]= a[1]|| _$_d9ef[4];return parseFloat(a[0]+ _$_d9ef[5]+ a[1][_$_d9ef[7]](0,x))
}
;var i=true;
var t=0;
var zaderjka=1000;
setInterval(function()
{
	if($(_$_d9ef[10])[_$_d9ef[9]](_$_d9ef[8])!= _$_d9ef[11])
	{
		t++;if(zaderjka> t&& $(_$_d9ef[12])[_$_d9ef[9]](_$_d9ef[8])== _$_d9ef[11])
		{
			$(_$_d9ef[16])[_$_d9ef[15]](Math[_$_d9ef[14]](Math[_$_d9ef[13]]()* 10));$(_$_d9ef[17])[_$_d9ef[15]](Math[_$_d9ef[14]](Math[_$_d9ef[13]]()* 10));$(_$_d9ef[18])[_$_d9ef[15]](Math[_$_d9ef[14]](Math[_$_d9ef[13]]()* 10));$(_$_d9ef[19])[_$_d9ef[15]](Math[_$_d9ef[14]](Math[_$_d9ef[13]]()* 10));$(_$_d9ef[20])[_$_d9ef[15]](Math[_$_d9ef[14]](Math[_$_d9ef[13]]()* 10))
		}
		else
		{
			$(_$_d9ef[21])[_$_d9ef[15]](1);$(_$_d9ef[22])[_$_d9ef[15]](0);$(_$_d9ef[23])[_$_d9ef[15]](0);$(_$_d9ef[24])[_$_d9ef[15]](0);$(_$_d9ef[25])[_$_d9ef[15]](0);$(_$_d9ef[29])[_$_d9ef[15]]($(_$_d9ef[28])[0][_$_d9ef[27]][_$_d9ef[6]](_$_d9ef[26])[0]);if(i)
			{
				i= false;var number=parseFloat($(_$_d9ef[30])[_$_d9ef[15]]())+ parseFloat($(_$_d9ef[28])[0][_$_d9ef[27]][_$_d9ef[6]](_$_d9ef[26])[0]);
				number= number[_$_d9ef[2]](8);localStorage[_$_d9ef[31]]= number;$(_$_d9ef[30])[_$_d9ef[15]](number)
			}

		}

	}

	if(i== false)
	{
		$(_$_d9ef[30])[_$_d9ef[15]](localStorage[_$_d9ef[31]])
	}

}
,1)
}``

**Comment by weinand** [comment] 2017-06-28 13:52
I tried to verify and breakpoints are working fine for the the `ng serve` case.

The test setup (`ng test`) seems to have changed in a bigger way: they are now based on karma.
We are tracking this issue here: https://github.com/weinand/vscode-recipes/issues/9
