### ISSUE TITLE
Right Click context menu content is getting out of workspace and not able to see half of options.

### ISSUE THREAD

**Issue by coolminder** [Microsoft/vscode#53813] opened 2018-07-08 17:22 UTC
- VSCode Version: 1.25.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. right click on half of the screen from the bottom (http://prntscr.com/k3za5a)

Does this issue occur when all extensions are disabled?: Yes/No
**- Yes!**
**Description:**
I am having the issue with the right-click context menu in the workspace. Each time when I hit right click in half of the screen from the bottom I am unable to see the context menu options, to access all of the options I need to click at top of the screen.

Thank you!

**Comment by khaled4vokalz** [comment] 2018-07-10 04:43
Facing the same problem... The menu gets cut if it's fired from down below the editor....

**Comment by sbatten** [comment] 2018-07-10 21:53
duplicate of #52533

**Closed by sbatten** 2018-07-10 21:53 UTC
