### ISSUE TITLE
Dynamic items in menu bar can cause crash

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#55347] opened 2018-07-30 03:47 UTC
- VSCode Version: 1.26.0-ins
- OS Version: win7x64

```
Version: 1.26.0-insider
Commit: dae69dbf00357ff8a3fe740a1f211d66b0b4681c
Date: 2018-07-27T05:17:55.890Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

GIF with exts disabled:
![crash - menu bar](https://user-images.githubusercontent.com/24613274/43376386-34c8a0b2-93c3-11e8-8c81-3dedfd4236ca.gif)

1) force reload VS Code (or close and start)
2) after 1-2 seconds - open any menu bar when it's options are visible already
3) randomly move cursor above the options

**_Notice_**: with Disabled Extensions Mode it can be detected not so often, really rarely.
BUT in Mode with extensions enabled - every second-third trying to repro - makes a crash!

PS: btw where I can find logs of VS Code crashes?

**Comment by Tyriar** [comment] 2018-07-30 23:49
Can you close all windows, then run `code - -verbose` and check the output in the terminal when it crashes?

**Comment by sbatten** [comment] 2018-07-31 00:07
@Tyriar 
```
PS C:\Users\stbatt\Source\vscode> code-insiders.cmd --verbose

[main 5:06:21 PM] Starting VS Code
[main 5:06:21 PM] from: c:\Users\stbatt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app
[main 5:06:21 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 5:06:21 PM] Resolving machine identifier...
[main 5:06:21 PM] Resolved machine identifier: 9db93396bd2759ea57c88403454e7401a6c5e52368525a73a6d77a802602bf66
[main 5:06:21 PM] update#setState idle
[main 5:06:21 PM] windowsManager#open
[main 5:06:21 PM] telemetry/optInStatus { optIn: true }
[main 5:06:21 PM] telemetry/update:win32SetupTarget { target: 'user' }
[18324:0730/170622.103:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:22 PM] windowsService#whenSharedProcessReady
[18324:0730/170622.129:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170622.137:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:22 PM] menubarService#updateMenubar 1
[main 5:06:22 PM] windowsService#getRecentlyOpened 1
[main 5:06:22 PM] menubarService#updateMenubar 1
[main 5:06:22 PM] windowsService#setRepresentedFilename 1
[18324:0730/170622.291:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170622.292:INFO:CONSOLE(1395)] "%cDEBUG", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:22 PM] windowsService#setRepresentedFilename 1
[18324:0730/170622.618:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:22 PM] windowsService#getWindowCount
[main 5:06:22 PM] IPC#vscode-workbenchLoaded
[main 5:06:22 PM] windowsService#getRecentlyOpened 1
[18324:0730/170622.862:INFO:CONSOLE(1395)] "%c INFO", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.054:INFO:CONSOLE(1395)] "%cDEBUG", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.080:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.083:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.083:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.083:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.084:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:23 PM] windowsService#startCrashReporter
[main 5:06:23 PM] menubarService#updateMenubar 1
[18324:0730/170623.355:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.355:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.355:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.355:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.356:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170623.491:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:23 PM] menubarService#updateMenubar 1
[main 5:06:23 PM] menubarService#updateMenubar 1
[18324:0730/170623.736:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:23 PM] windowsService#isFocused 1
[main 5:06:23 PM] menubarService#updateMenubar 1
[18324:0730/170625.058:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.058:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.059:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.059:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.059:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.059:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.059:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.060:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.061:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.061:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.061:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.062:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.164:INFO:CONSOLE(272)] "%c[Extension Host] %cActivating extension 'Equinusocio.vsc-material-theme' failed: Cannot find module './accents-setter'. %c(at Object.showMessage (c:\Users\stbatt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:72))", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (272)
[18324:0730/170625.164:INFO:CONSOLE(272)] "%c[Extension Host] %cActivating extension `Equinusocio.vsc-material-theme` failed: ", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (272)
[18324:0730/170625.168:INFO:CONSOLE(272)] "%c[Extension Host] %cHere is the error stack: ", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (272)
[18324:0730/170625.169:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.169:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.213:INFO:CONSOLE(3220)] "Activating extension 'Equinusocio.vsc-material-theme' failed: Cannot find module './accents-setter'.", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (3220)
[18324:0730/170625.239:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.239:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.666:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.669:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[18324:0730/170625.689:INFO:CONSOLE(1395)] "%cTRACE", source: file:///C:/Users/stbatt/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js (1395)
[main 5:06:25 PM] menubarService#updateMenubar 1
```

**Comment by sbatten** [comment] 2018-07-31 00:10
@Tyriar (from source)
```
PS C:\Users\stbatt\Source\vscode> .\scripts\code.bat
[17:08:31] Syncronizing built-in extensions...
[17:08:31] You can manage built-in extensions with the --builtin flag
[17:08:31] [marketplace] ms-vscode.node-debug@1.26.6 ✔︎
[17:08:31] [marketplace] ms-vscode.node-debug2@1.26.7 ✔︎

[main 5:08:32 PM] update#ctor - updates are disabled
[10112:0730/170834.333:INFO:CONSOLE(182)] "%c INFO", source: file:///C:/Users/stbatt/Source/vscode/out/vs/platform/log/common/log.js (182)
Debugger listening on ws://127.0.0.1:5876/dc6897b8-471f-4ffb-bb6b-7df95f1fc72f
For help see https://nodejs.org/en/docs/inspector
[10112:0730/170835.207:INFO:CONSOLE(234)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (234)
[10112:0730/170835.512:INFO:CONSOLE(143)] "%c[Extension Host] %cdebugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/087c5155-8136-4498-bf5a-f1136a0a2c09", source: file:///C:/Users/stbatt/Source/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.js (143)
Backtrace:
        GetHandleVerifier [0x00007FF76119B544+14307636]
        purecall [0x00007FFF5BAE4A74+52]
        GetHandleVerifier [0x00007FF76161D30F+19033855]
        GetHandleVerifier [0x00007FF761666640+19333680]
        IsSandboxedProcess [0x00007FF76191CFF1+2725937]
        IsSandboxedProcess [0x00007FF76191A742+2715522]
        IsSandboxedProcess [0x00007FF76191B63D+2719357]
        IsSandboxedProcess [0x00007FF761C3FA14+6013524]
        GetHandleVerifier [0x00007FF761609102+18951410]
        GetHandleVerifier [0x00007FF76162700C+19074044]
        IsSandboxedProcess [0x00007FF7618C9859+2384025]
        IsSandboxedProcess [0x00007FF7618C9C86+2385094]
        IsSandboxedProcess [0x00007FF7618C9B0E+2384718]
        IsSandboxedProcess [0x00007FF7618C98F1+2384177]
        IsSandboxedProcess [0x00007FF761B936EB+5308203]
        IsSandboxedProcess [0x00007FF76189B9EC+2196012]
        IsSandboxedProcess [0x00007FF76189BA8A+2196170]
        GetHandleVerifier [0x00007FF76164DC3D+19232813]
        IsSandboxedProcess [0x00007FF7618FEEF3+2602803]
        IsSandboxedProcess [0x00007FF761903BFF+2622527]
        IsSandboxedProcess [0x00007FF7619026D4+2617108]
        IsSandboxedProcess [0x00007FF7618CD12C+2398572]
        IsSandboxedProcess [0x00007FF7618CC8C3+2396419]
        CallWindowProcW [0x00007FFF6DA76CC1+1217]
        DispatchMessageW [0x00007FFF6DA76693+467]
        GetHandleVerifier [0x00007FF760468B07+468727]
        GetHandleVerifier [0x00007FF760468662+467538]
        GetHandleVerifier [0x00007FF7604682F4+466660]
        GetHandleVerifier [0x00007FF76041A9FF+148975]
        IsSandboxedProcess [0x00007FF7617FFF88+1558472]
        IsSandboxedProcess [0x00007FF761801366+1563558]
        IsSandboxedProcess [0x00007FF7619D5412+3480658]
        IsSandboxedProcess [0x00007FF761C647F8+6164536]
        IsSandboxedProcess [0x00007FF761995DFD+3221053]
        IsSandboxedProcess [0x00007FF761995CF0+3220784]
        IsSandboxedProcess [0x00007FF7627011BE+17291774]
        GetHandleVerifier [0x00007FF7614E1540+17740080]
        (No symbol) [0x00007FF7601FBC85]
        IsSandboxedProcess [0x00007FF762CF5BD3+23536659]
        BaseThreadInitThunk [0x00007FFF6FFB3034+20]
        RtlUserThreadStart [0x00007FFF70341431+33]
```

**Comment by user3323** [comment] 2018-07-31 00:48
@Tyriar 

and from me:

[exts enabled.txt](https://github.com/Microsoft/vscode/files/2243320/exts.enabled.txt)

extensions **_enabled_**

**Comment by sbatten** [comment] 2018-07-31 17:08
possibly related to testing #55081 as of right now

**Comment by bpasero** [comment] 2018-08-17 13:39
Steps:
• start VSCode
• wait for the File menu to appear
• move mouse up and down over items but also into window (a bit below the menu)
• do this long enough until crash

**Comment by bpasero** [comment] 2018-08-17 14:03
This blocks dynamic menus on Linux and Windows.

**Comment by bpasero** [comment] 2018-08-20 10:01
Opened https://github.com/electron/electron/issues/14213

**Comment by sbatten** [comment] 2018-08-24 21:31
I'm moving this out of august since we shouldn't enable the dynamic menus until we have a proper fix for this.

**Comment by bpasero** [comment] 2018-09-27 12:38
@sbatten I looked into this again and here is what I found:
* macOS: does not crash with dynamic menus
* Linux: crashes with dynamic menus
* Windows: crashes with dynamic menus

Given that macOS works fine and Windows has the custom menu enabled by default, Linux is the OS that we should look for a workaround. I was NOT able to reproduce the crash if I would simply keep an array of menus around, like so:

```typescript
let oldMenu = Menu.getApplicationMenu();
if (oldMenu) {
	this.menus.push(oldMenu);
}

if (menubar.items && menubar.items.length > 0) {
	Menu.setApplicationMenu(menubar);
} else {
	Menu.setApplicationMenu(null);
}
```

So the culprit lies within the fact that when the garbage collector finds that the menu is not used anymore, it will destroy it even if the user is still interacting with the menu. By keeping the menu referenced, this GC does not happen. We could add a scheduler that removes items from this array in certain intervals to ensure we are not leaking anything.

 I think we should enable dynamic menus early in October to get some coverage including this change for Linux/Windows. I would also like to see us exploring the possibility of caching the menu as JSON structure. If we do that, we will probably find out that the menu is not changing that often after all, so I would also expect this issue to surface less often.

Thoughts?

**Comment by sbatten** [comment] 2018-09-27 17:46
@bpasero All of that sounds pretty great, thanks for the investigation. I'll definitely plan to hook this up ASAP in October. The menu caching I think will be vital to matching the current macOS experience. As discussed earlier, we should probably populate the menu fully on launch and disable things as that functionality comes up. A follow-up question is whether or not we should use the cached structure in the fallback menu and disable everything but a few items when there are no windows open.

**Comment by bpasero** [comment] 2018-09-27 17:56
@sbatten yes I think the JSON structure could maybe know if the entries work in the 0-window case on macOS and then it could be fully used also for the fallback menu when no window is opened.

**Closed** 2018-10-04 17:41 UTC
Labels: electron, freeze-slow-crash, upstream, workbench-menu
