### ISSUE TITLE
High Memory Usage(Over 3GB)

### ISSUE THREAD

**Issue by zhangzujian** [Microsoft/vscode#37913] opened 2017-11-09 10:05 UTC
![mem](https://user-images.githubusercontent.com/13048299/32599756-756deae2-c578-11e7-9610-379cac582403.png)

- VSCode Version:  1.18.0-x64
- OS Version:  Win10-1709-x64

Steps to Reproduce:

1. Open VSCode with all extensions disabled (No open folders or projects) :  "C:\Program Files\Microsoft VS Code\Code.exe" --disable-extensions 

2.  

Reproduces without extensions: Yes

**Comment by bpasero** [comment] 2017-11-09 10:28
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by zhangzujian** [comment] 2017-11-10 01:06
@bpasero  It seems the insider release works well. It consumes only 200+ MB memory.

![insider](https://user-images.githubusercontent.com/13048299/32637675-312e79b8-c5f6-11e7-8c27-a4d63a5627c5.png)

**Comment by bpasero** [comment] 2017-11-10 06:04
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by zhangzujian** [comment] 2017-11-10 06:09
Please see the **Steps to Reproduce**   : ) .

I'm pretty sure that I disabled all extensions.

**Comment by zhangzujian** [comment] 2017-11-10 06:11
The problem is similar to #37800 .

**Comment by TOotg** [comment] 2017-11-10 06:16
same happened to me on MacOS
<img width="495" alt="qq20171110-3 2x" src="https://user-images.githubusercontent.com/28853542/32645264-59a47d40-c621-11e7-9148-838351e2456d.png">

when use 
```
code --disable-extensions
```

it is like this

<img width="430" alt="qq20171110-4 2x" src="https://user-images.githubusercontent.com/28853542/32645317-a600d990-c621-11e7-9263-99c21a93bfbb.png">

**Comment by bpasero** [comment] 2017-11-10 06:17
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by zhangzujian** [comment] 2017-11-10 06:22
![2](https://user-images.githubusercontent.com/13048299/32645521-9764f6d6-c622-11e7-94ec-3abb2335dbcb.png)

Hope it helps.

**Comment by TOotg** [comment] 2017-11-10 06:30
<img width="562" alt="qq20171110-5 2x" src="https://user-images.githubusercontent.com/28853542/32645688-8bac1c24-c623-11e7-9e39-ce4035875ad4.png">

``` shell
○ ps aux | grep 7256
tan               7256  96.5 16.8 14463260 1412884   ??  R     2:17PM  11:10.21 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=245AD4540CE533E4B17405FAA7E138C1 --lang=en-US --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --service-request-channel-token=245AD4540CE533E4B17405FAA7E138C1 --renderer-client-id=6
tan               1860   0.0  0.9  5637136  77256   ??  S    11:08AM   1:04.96 /Applications/Google Chrome.app/Contents/Versions/62.0.3202.89/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper --type=renderer --field-trial-handle=3295442269365291016,13802268741811839651,131072 --service-pipe-token=C7026DAED6FB8691F95265DEB8876C93 --lang=en-US --metrics-client-id=7129a43a-f9ba-4177-9dce-6c14bbada797 --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=false,disallowFetchForDocWrittenScriptsInMainFrameOnSlowConnections=true --enable-pinch --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,34037;0,12,34037;0,13,34037;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,34037;1,12,34037;1,13,34037;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,34037;3,12,34037;3,13,34037;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553;5,0,3553;5,1,3553;5,2,3553;5,3,3553;5,4,3553;5,5,34037;5,6,3553;5,7,3553;5,8,3553;5,9,3553;5,10,3553;5,11,3553;5,12,3553;5,13,34037;5,14,34037;5,15,3553;5,16,34037;5,17,34037;6,0,3553;6,1,3553;6,2,3553;6,3,3553;6,4,3553;6,5,34037;6,6,3553;6,7,3553;6,8,3553;6,9,3553;6,10,3553;6,11,3553;6,12,3553;6,13,34037;6,14,34037;6,15,3553;6,16,34037;6,17,34037 --enable-gpu-async-worker-context --service-request-channel-token=C7026DAED6FB8691F95265DEB8876C93 --renderer-client-id=41
root              1286   0.0  0.1  4287256   6240   ??  S    10:45AM   0:00.02 /Users/tan/Library/Application Support/byteexec/sysproxy-cmd wait-and-cleanup 127.0.0.1 60502
root                89   0.0  0.1  4349864   7256   ??  Ss   10:22AM   0:12.76 /usr/libexec/opendirectoryd
tan               7847   0.0  0.0  4275944    588 s000  R+    2:27PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 7256
```

**Comment by zhangzujian** [comment] 2017-11-10 06:40
It's strange that my VS Code works fine now... I will report if it happens again.

**Comment by bpasero** [comment] 2017-11-10 06:41
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by TOotg** [comment] 2017-11-10 07:16
- [ ] it reproduces with extensions disabled (code --disable-extensions from the command line - NOT the integrated terminal of Code)
- [x] it was not happening in the previous stable release (i suppose)
- [x] there is no suspicious output when running from the command line (code --verbose)
- [x] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces when opening empty (code -n from the command line)
- [ ] it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json (backup first! see below for paths)

Above is a list i've checked
just a few seconds after i put my settings.json back it happens, i think something wrong with the configuration either for vscode or its extension

```json
{
  "editor.fontFamily": "Cousine,Hannotate SC ",
  "editor.fontSize": 14.5,
  "editor.tabSize": 2,
  "editor.lineHeight": 20,
  "editor.snippetSuggestions": "top",
  "editor.minimap.enabled": false,
  "editor.cursorStyle": "block",
  "editor.wordWrap": "wordWrapColumn",
  "editor.renderIndentGuides": false,
  "editor.formatOnSave": true,
  "editor.lineNumbers": "relative",
  "editor.codeLens": false,
  "editor.renderControlCharacters": true,
  "editor.minimap.renderCharacters": false,
  "files.insertFinalNewline": true,
  "files.autoSave": "off",
  "files.associations": {
    "*.wxml": "html",
    "*.wxss": "less"
  },
  "explorer.openEditors.visible": 6,
  "explorer.openEditors.dynamicHeight": true,
  "workbench.editor.tabCloseButton": "off",
  "workbench.editor.showTabs": false,
  "workbench.editor.enablePreview": true,
  "workbench.statusBar.visible": true,
  "workbench.iconTheme": "file-icons-colourless",
  "workbench.activityBar.visible": false,
  "workbench.sideBar.location": "right",
  "workbench.colorTheme": "Dracula Soft",
  "window.zoomLevel": 0,
  "window.newWindowDimensions": "inherit",
  "window.nativeTabs": true,
  "search.followSymlinks": false,
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.fontFamily": "menlo",
  "prettier.semi": false,
  "prettier.singleQuote": true,
  "prettier.jsxBracketSameLine": true,
  "prettier.printWidth": 80,
  "prettier.bracketSpacing": false,
  "typescript.implementationsCodeLens.enabled": true,
  "gitlens.blame.line.enabled": false,
  "gitlens.statusBar.enabled": false,
  "gitlens.annotations.file.gutter.heatmap.location": "left",
  "C_Cpp.intelliSenseEngine": "Default",
  "vim.useSystemClipboard": true,
  "vim.disableAnnoyingNeovimMessage": true,
  "vim.visualstar": true,
  "vim.easymotion": true,
  "vim.easymotionMarkerBackgroundColor": "#e5c07b",
  "vim.easymotionMarkerHeight": 20,
  "vim.easymotionMarkerFontSize": "14",
  "vim.easymotionMarkerFontFamily": "Chalkboard",
  "vim.easymotionMarkerFontWeight": "bold",
  "vim.easymotionMarkerWidthPerChar": 10,
  "vim.leader": ",",
  "vim.statusBarColorControl": true,
  "vim.statusBarColors": {
    "normal": "#3378ef",
    "insert": "#f15f48",
    "visual": "#23c0e9",
    "visualline": "#23c0e9"
  },
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["g", "p"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.previewDeclaration",
          "args": []
        }
      ]
    },
    {
      "before": ["g", "o"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.navigateBack",
          "args": []
        }
      ]
    },
    {
      "before": ["g", "i"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.navigateForward",
          "key": "ctrl+right"
        }
      ]
    },
    {
      "before": ["g", "u"],
      "after": [],
      "commands": [
        {
          "command": "workbench.view.debug",
          "when": "editorTextFocus"
        }
      ]
    },
    {
      "before": ["u"],
      "after": [],
      "commands": [
        {
          "command": "undo",
          "when": "editorTextFocus && !editorReadonly"
        }
      ]
    },
    {
      "before": ["g", "h"],
      "after": [],
      "commands": [
        {
          "command": "extension.dash.specific",
          "when": "editorTextFocus"
        }
      ]
    },
    {
      "before": ["t", "t"],
      "after": [],
      "commands": [
        {
          "command": "editor.debug.action.toggleBreakpoint",
          "when": "editorTextFocus"
        }
      ]
    },
    {
      "before": ["t", "r"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.debug.restart",
          "when": "inDebugMode"
        }
      ]
    },
    {
      "before": ["t", "n"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.debug.continue",
          "when": "inDebugMode"
        }
      ]
    },
    {
      "before": ["t", "a"],
      "after": [],
      "commands": [
        {
          "command": "workbench.debug.viewlet.action.removeAllBreakpoints"
        }
      ]
    },
    {
      "before": ["F"],
      "commands": [
        {
          "command": "workbench.action.toggleFullScreen",
          "args": []
        }
      ]
    },
    {
      "before": [" "],
      "after": ["/"]
    },
    {
      "before": [";"],
      "after": [":"]
    }
  ],
  "workbench.colorCustomizations": {
    "statusBar.background": "#23c0e9",
    "statusBar.noFolderBackground": "#23c0e9",
    "statusBar.debuggingBackground": "#23c0e9"
  },
  "workbench.panel.location": "right"
}

```


If you need more check or info, let me know

**Comment by TOotg** [comment] 2017-11-10 08:19
After i disabled extension vscodevim everything looks pretty good, so seems not a vscode problem

**Comment by DanielDeMarco** [comment] 2017-11-14 16:56
Setting 'vim.statusBarControlColors: false' to solved this issue for me, so if you're getting this issue because of vscodevim you might not have to disable the entire extension.

**Comment by bpasero** [comment] 2017-11-15 05:31
@TOotg @DanielDeMarco can you report this to the extension itself?

**Comment by TOotg** [comment] 2017-11-23 02:49
There is a similar issue https://github.com/VSCodeVim/Vim/issues/2166 , and they already closed it

**Comment by TOotg** [comment] 2017-11-23 02:54
Sorry, the issue is this one:  https://github.com/VSCodeVim/Vim/issues/2124

**Closed** 2017-11-23 06:12 UTC
Labels: extensions, freeze-slow-crash, needs more info
