### ISSUE TITLE
Search does not respect .gitignore in subdirectories when "files to include" is set

### ISSUE THREAD

**Issue by jwien001** [microsoft/vscode#181842] opened 2023-05-08 21:44 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.0
- OS Version: Darwin arm64 22.4.0 (macOS Ventura 13.3.1 (a))

Steps to Reproduce:

1. Have the following directory structure:
  - project/.gitignore
  - project/foo/bar/baz/.gitignore
    - this file should ignore the deps/ directory
  - project/foo/bar/baz/deps/
  - various files in project/foo/bar/baz/deps/

2. Search for a string found in the deps/ directory. Expect to see no results.
3. Click the Use Exclude Settings and Ignore Files (to disable it) and repeat the search. It should show results in the deps/ directory.
4. Enable Use Exclude Settings and Ignore Files again. Set "files to include" to "foo/bar/baz/" and search again. While I would expect no results here, the results in deps/ show up for me. Disabling/reenabling Use Exclude Settings and Ignore Files doesn't change anything.

I believe this is at least related to https://github.com/microsoft/vscode/issues/93079.

**Comment by jjspace** [comment] 2024-02-12 18:49
I just spent over half an hour fighting with VSCode over this frustratingly unexpected behavior.

Simpler way to explain reproduction

1. Search for a string in a file that's gitignored
    - It hidden when "Use Exclude Settings and Ignore Files" is on
    - It's shown when it's off
 2. Specify part of the path to the ignored file in the "files to include" field
    - The file is now shown always, regardless of "Use Exclude Settings and Ignore Files"

I'm working in a repo with multiple npm workspaces and wanted to use the "files to include" field to limit the search to one workspace but that forces it to show all ignored files even if the setting to hide them is on.

**Comment by runofthemill** [comment] 2024-09-25 20:50
Went down a rabbit hole w/ this same issue, turns out it's due to how VSCode implements ripgrep

https://github.com/microsoft/vscode/issues/192045
https://github.com/BurntSushi/ripgrep/issues/2606

What I'm curious about is whether [this](https://github.com/BurntSushi/ripgrep/issues/2606#issuecomment-1712053068) change can be made on the VSCode side; trying that change (removing the `-g` flag with the value specified in `files to include` and changing the search path instead to that value) on the command line worked fine, but perhaps that approach doesn't work in various other situations 🤔

**Comment by runofthemill** [comment] 2024-09-25 20:59
Heh, this goes back quite a bit... https://github.com/microsoft/vscode/issues/26574

@andreamah (apologies if you aren't still working on this area) is this something that VSCode would reconsider addressing, independent of any upstream changes?

**Comment by jlahtinen** [comment] 2024-11-14 10:36
Before tried to make a new issue I found this. Is this same issue as:

❯ git init
❯ mkdir ansible
❯ mkdir ansible/build
❯ echo ansible/build >> .gitignore
❯ echo teststring >> ansible/build/a

![Image](https://github.com/user-attachments/assets/cd6560bb-4da2-421e-bcf1-a96cf632c137)
seems ok

![Image](https://github.com/user-attachments/assets/5622ae0b-9037-4f05-8adc-61df79e7800a)
I think this result should not be here

**Comment by osortega** [comment] 2024-12-20 20:33
Duplicate of https://github.com/microsoft/vscode/issues/26574
Closing 

/duplicate

**Closed by osortega** 2024-12-20 20:33 UTC
Labels: bug, search, confirmed
