### ISSUE TITLE
Bottom Bar Seems Cut Off

### ISSUE THREAD

**Issue by DanJ210** [microsoft/vscode#87831] opened 2019-12-29 03:32 UTC
Issue Type: <b>Bug</b>

No other app has an issue but VS Code on my computer seems to cut off a small sliver of the bottom bar when I maximize it. I have to hide the task bar to get the sliver back but still the bottom bar is slightly cut off. If I toggle the setting to automatically hide the task bar in desktop mode I'll see VS Code size right for a split second and then it adjusts to this cut off sizing.

![image](https://user-images.githubusercontent.com/16159685/71552022-c9d7a000-29c1-11ea-91ec-84effc3feafe.png)

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|2.0.11
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.10
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
dotnet-test-explorer|for|0.7.1
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
rest-client|hum|0.23.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
dotnet-core-essentials|Kis|0.0.8
vscode-attrs-sorter|mrm|2.1.0
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
vscode-edge-devtools|ms-|1.0.6
mssql|ms-|1.8.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-node-azure-pack|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.1424
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.3
debugger-for-chrome|msj|4.12.3
debugger-for-edge|msj|1.0.13
vuejs-extension-pack|mub|1.1.5
vetur|oct|0.22.6
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.9.2
tslint-vue|pro|1.5.6
LiveServer|rit|5.6.1
vscode-essentials-snippets|rob|2.0.0
yo|sam|0.9.3
code-settings-sync|Sha|3.4.3
git-autoconfig|shy|0.0.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.2
azure-iot-toolkit|vsc|2.14.0
vscode-icons|vsc|9.7.0
WebTemplateStudio-dev-nightly|WAS|0.1.1934601
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-12-29 03:50
/duplicate of #85592

Please provide more info if you are sure that you have different issue

**Closed** 2019-12-29 03:50 UTC
Labels: *duplicate, integrated-terminal
