### ISSUE TITLE
Object.entries not recognised after a while in TS project

### ISSUE THREAD

**Issue by Akxe** [Microsoft/vscode#54856] opened 2018-07-23 09:07 UTC
I would say it is pretty common, as it happened to me twice this week on very different project on two distinct computers.

**Problem**:
I have TS project that I use babel on, therefor I use esnext syntax. TS compiles just fine, but after a while, VSCode's intelisence starts recognising only es2015. 

**Example**:
VS intelisence says `[ts] Property 'entries' does not exist on type 'ObjectConstructor'.`, but TS compiler does not log any errors, therefor I suspect it is VScode error.

PS: Not tested on insider, but it have happened to me in few version before already.

- VSCode Version: 1.25.1
- OS Version: Windows 10, 64bit

Steps to Reproduce:

1. Have tsconfig.json with this settings in.
```
{
	"compilerOptions": {
		"lib": [
			"dom",
			"esnext",
		],
		... anything can be here, any combination, target esnext, es5, strict or not
	}
}
```
2. Hard to say, just wait and see, it will happen soon.

Hint: I have just update `@types/video.js` in my package.json, but it may just be coincidence.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-07-23 17:59
When you see this error in a file, run the `go to project configuration` command in VS Code. Does this command open the correct `tsconfig.json`?

Also please test in insiders if you can

**Comment by Akxe** [comment] 2018-07-24 07:16
It indeed does not. And both my project currently doing it have TS folder nested

- Sources
  - JavaScript
  - SASS
  - TypeScript
    - video
      - plugins
        - myPlugin.ts <--- Here I get error that Object.entries is not part of Object
      - player.ts 
    - tsconfig.json
- package.json

```
{
	"files": [
		"./video/player.ts"
	],
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"lib": [
			"dom",
			"esnext",
		],
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"esModuleInterop": true,
	}
}
```

This should be whole needed setup. But I should mention, it worked for a while...

**Comment by mjbvz** [comment] 2018-07-24 18:35
Does `player.ts` import `myPlugin.ts` in any way? If it does not, since you set `"files"` to only include `player.ts`, `myPlugin.ts` will not be included in the project

**Comment by Akxe** [comment] 2018-07-24 18:38
It does using the `import('./plugin')` syntax.

**Comment by mjbvz** [comment] 2018-07-24 23:55
@Akxe Having trouble reproducing this with TS 2.9 and TS 3.0+. Does the import for `plugin` get resolved correctly? What is the exact code for the `import(...)`?

It would also help if you can share a minimal example project

**Comment by Akxe** [comment] 2018-07-25 00:54
It is hard to replicate, but it had happened to me several times. One thing to note is that my libraries are conditionally imported, they are not even in the code, I iterate thought array with strings that contains options for my app setup. `[plugin1','plugin2'].foreach(name => import('.plugins/' + name).then(register => register())`. It get compiled just fine.

**Comment by Akxe** [comment] 2018-07-25 10:22
I have some findings, it may be because, the imports are not "writen" down, that TypeScript doesn't see them and therefor nor does VSCode. I have putted all of my project in `include` in TSconfig file, and now I gets intelisence. But is it possible to get it working without it? Since webpack have found it...

**Comment by mjbvz** [comment] 2018-07-25 20:54
Dynamic imports like that won't be detected properly and fixing that is out of scope. Try adding the referenced files to your `tsconfig` or using static import statements

**Closed by mjbvz** 2018-07-25 20:54 UTC
Labels: needs more info, typescript
