### ISSUE TITLE
Search(Ctrl+Shift+F) result can't jump to corresponding files

### ISSUE THREAD

**Issue by CxpKing** [microsoft/vscode#108701] opened 2020-10-15 02:25 UTC
Issue Type: <b>Bug</b>

Search(Ctrl+Shift+F) result can't jump to corresponding files.
Open a file and press the shortcut key Ctrl + Shift + F to jump to the search results interface for any word. Double click on any item to jump to the search result interface. Old versions can jump.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (12.26GB free)|
|Process Argv|--crash-reporter-id 244fd305-1859-4e45-93a1-1c2bc1822a79|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment] 2020-10-16 23:58
Dupe of https://github.com/microsoft/vscode/issues/108579

**Closed by roblourens** 2020-10-16 23:58 UTC
Labels: new release
