### ISSUE TITLE
Git rid of Windows Power Shell

### ISSUE THREAD

**Issue by TradeIdeasPhilip** [microsoft/vscode#132692] opened 2021-09-08 21:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version:
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎12/‎2021
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

Steps to Reproduce:

1. Set your default terminal type to git bash.
2. Hit the `+` button to create a new shell.
3. Verify that the new shell is running git bash, as expected.
4. Close the Windows Power Shell tab.  Now only git bash is running.
5. Close VS Code.
6. Reopen VS Code.
7. At this point I'd expect to see git bash running in my terminal, but instead I see Windows Power Shell.

This is a new problem.  It started today when VS Code updated itself.  I immediately saw a message saying asking me to migrate deprecated terminal shell settings.  I hit OK.  And now I'm stuck with Windows Power Shell instead of the shell I've asked for.

**Comment by IllusionMH** [comment] 2021-09-08 22:36
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Closed** 2021-09-08 22:37 UTC
Labels: *duplicate
