### ISSUE TITLE
[css] :has(>child) selector not working in SCSS

### ISSUE THREAD

**Issue by DrSensor** [microsoft/vscode#111202] opened 2020-11-23 22:49 UTC
Issue Type: <b>Bug</b>

```scss
a:has(>img) {

}
```
![2020-11-24_05-47](https://user-images.githubusercontent.com/4953069/100023998-94794380-2e18-11eb-982e-27668c28e06d.png)

Will give error:

<sub>red squiggle at `>`</sub>
```
) expectedscss(css-rparentexpected)
```
<sub>red squiggle at `)`</sub>
```
{ expectedscss(css-lcurlyexpected)
```

VS Code version: Code - OSS 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-12T10:54:25.653Z)
OS version: Linux x64 5.8.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3086)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (0.24GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|bspwm|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DrSensor** [comment] 2020-11-23 22:50
https://developer.mozilla.org/en-US/docs/Web/CSS/:has

**Comment by aeschli** [comment] 2020-11-24 13:02
Waiting a bit until this is adopted by browsers.

**Comment by Airkro** [comment] 2021-01-27 01:17
![image](https://user-images.githubusercontent.com/12206891/105928156-60243c80-6080-11eb-9054-4a743199a782.png)

same problem

**Comment by yume-chan** [comment] 2021-01-27 01:52
> ![image](https://user-images.githubusercontent.com/12206891/105928156-60243c80-6080-11eb-9054-4a743199a782.png)
> 
> same problem

No, yours is another feature.

**Comment by DrSensor** [comment] 2021-01-27 02:39
Actually, all `>` or `<` symbol inside a bracket has a similiar problem.

**Comment by Airkro** [comment] 2021-01-27 02:53
@yume-chan 

Maybe not, but they have the same error message

![image](https://user-images.githubusercontent.com/12206891/105935880-bc418d80-608d-11eb-86ac-0d41175e9830.png)

**Comment by GEMI** [comment] 2022-02-03 13:32
Anything happening with this issue?

**Comment by erictompkins** [comment] 2022-05-19 10:53
We are having a similar issue, but with the `+` selector followed by a class

```
.Tabs-button:hover:has(+ .Tabs-button.is-active) {
        border-right: none;
        padding-right: 17px;
}
```

<img width="390" alt="image" src="https://user-images.githubusercontent.com/4851312/169276948-08ecf873-dd5a-4290-a208-0194444b3c9a.png">

VS Code shows two errors

- `) expectedcss(css-rparentexpected)` for the first red squiggly
- `{ expectedcss(css-lcurlyexpected)` for the second red squiggly

The CSS code is valid and works in Safari.

**Comment by controversial** [comment] 2022-06-21 17:31
Having the same issue using `:has(+ ...)`:

<img width="598" alt="Screen Shot 2022-06-21 at 1 27 38 PM" src="https://user-images.githubusercontent.com/10377391/174861134-0aa9293d-7f2d-4ff5-a1a4-7b470af23d90.png">

> Waiting a bit until this is adopted by browsers.

Worth noting that support for `:has` shipped in Safari 15.4 (on both iOS and macOS) in March, and that it will ship in Chrome 105 at the end of August (see [caniuse](https://caniuse.com/css-has)).

**Comment by fabiospampinato** [comment] 2022-09-17 12:59
Can this be put in the next issue's milestone? It's an important feature which shipped in most browsers already, and it's just not supported properly by the editor.

**Comment by aeschli** [comment] 2022-09-19 12:13
I've aleady fixed the `has` support and it will be in the next milestone.

Duplicate of https://github.com/microsoft/vscode/issues/147353

**Closed by aeschli** 2022-09-19 12:13 UTC
Labels: feature-request, css-less-scss
