### ISSUE TITLE
Comments messing up with spaces on HTML/CSS files

### ISSUE THREAD

**Issue by mdalpi** [Microsoft/vscode#31213] opened 2017-07-21 13:53 UTC
- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a new (or open a) HTML/CSS file;
2. Write some text;
3. Keep toggling comment on the line, it will add one space before and one after for every toggle.

Reproduces without extensions: Yes

Here's a demo: https://streamable.com/rdoze
The only installed extension is Python (0.6.8) by DonJayamanne.
And it was happening on 1.14.1 too.

**Comment by AyumuKasuga** [comment] 2017-07-21 21:54
Can confirm this.

**Comment by ergonomicus** [comment] 2017-07-22 21:36
VSCODE
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

OS Linux Mint 18.2

I have the same issue as described by @mdalpi

**Comment by Shaker-Hamdi** [comment] 2017-07-24 07:44
I can confirm this. It can make Git see a change in the file even if I'm just toggling a comment for testing.

**Comment by qdirks** [comment] 2017-08-04 06:50
I'm also having this issue. I hope it will be fixed soon because I really like using the keyboard shortcut to quickly comment and uncomment css styles to see the effect they are having.

**Comment by kieferrm** [comment] 2017-08-07 20:57
Duplicate of #30800.

**Closed by kieferrm** 2017-08-07 20:57 UTC
