### ISSUE TITLE
The editor.wordWrap is not working properly when the variable width font is used in editor

### ISSUE THREAD

**Issue by rosertech** [Microsoft/vscode#52166] opened 2018-06-18 08:19 UTC
The editor.wordWrap is not working properly when the variable width font is used in editor. 

When the editor.wordWrap is 'on' and a fixed width font like Courier New is used, VSC wraps the long lines correctly according to viewport size. 

But if I change the editor font to variable width font like Arial, VSC wraps the long lines earlier than real viewport size. So there many gaps(1~2inches in 22inch monitor) between the end of each line wrapped and viewport window. 

I hope the wrapping algorithm consider this font style case.

* The notepad++ works properly for fixed and variable width fonts both.

**Comment by alexandrudima** [comment] 2018-06-18 08:44
Duplicate of #2654

**Closed by alexandrudima** 2018-06-18 08:44 UTC
Labels: editor, editor-core
