### ISSUE TITLE
Markdown preview: Image insertion using HTML fails to use path relative to workspace

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [microsoft/vscode#191358] opened 2023-08-26 09:06 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.1
- OS Version: Darwin arm64 22.6.0 (macOS 13.5.1)

Steps to Reproduce:

1. Create and open a workspace (folder) with the following file structure (all are paths relative to the workspace root):

```
images/
images/image.jpg
docs/
docs/doc.md
```

2. Try inserting `image.jpg` to `doc.md` in two ways

```markdown
<!-- native markdown -->
![alt](/images/image.jpg)

<!-- HTML -->
<img src="/images/image.jpg" alt="alt">
```

In the built-in preview, only the first way works, while the second way fails to find the image. In my test, it seems that the HTML way only recognize path relative to the *current file*, and absolute path. I wonder whether this is a bug or intended behavior.

**Comment by mjbvz** [comment] 2023-08-28 15:58
Duplicate of #46448/#159365

**Closed by mjbvz** 2023-08-28 15:58 UTC
