### ISSUE TITLE
File fails to load if custom editor is no longer registered

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101629] opened 2020-07-02 19:15 UTC
1. Develop a custom editor extension such as the hex editor extension. Open a file make some edits and hot exit the VS Code instance
2. Open that same workspace in a vscode instance which doesn't have the hex editor registered. It will get stuck trying to load the file into the hex editor which is no longer there.

There are no errors in the dev console.

**Comment by mjbvz** [comment] 2020-07-02 19:16
Duplicate of #96407

**Closed by mjbvz** 2020-07-02 19:16 UTC
Labels: bug, custom-editors
