### ISSUE TITLE
format code alt + shift + f

### ISSUE THREAD

**Issue by hrkazemi** [microsoft/vscode#76839] opened 2019-07-08 07:49 UTC
Issue Type: <b>Bug</b>

using alt + shift + f cuse error <main>typescript server error ...
i curruntly working on react typescript project.
i think after vs code updated this problem occured.
now i use prettier-vscode instead

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.79GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
vscode-scss-formatter|sib|1.4.1

</details>

**Comment by mjbvz** [comment] 2019-07-08 15:11
What is the error?

**Comment by hrkazemi** [comment] 2019-07-09 05:07
> What is the error?

<main> TypeScript Server Error (3.5.2)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (tsserver.js:110675:34)
    at tsserver.js:110622:21
    at visitNode (tsserver.js:16634:24)
    at Object.forEachChild (tsserver.js:17045:24)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at tsserver.js:110622:21
    at visitNode (tsserver.js:16634:24)
    at Object.forEachChild (tsserver.js:17024:21)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at processChildNodes (tsserver.js:110732:48)
    at tsserver.js:110624:21
    at visitNodes (tsserver.js:16639:24)
    at Object.forEachChild (tsserver.js:17023:21)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at processChildNodes (tsserver.js:110732:48)
    at tsserver.js:110624:21
    at visitNodes (tsserver.js:16639:24)
    at Object.forEachChild (tsserver.js:17027:21)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at tsserver.js:110622:21
    at visitNode (tsserver.js:16634:24)
    at Object.forEachChild (tsserver.js:16832:24)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at tsserver.js:110622:21
    at visitNode (tsserver.js:16634:24)
    at Object.forEachChild (tsserver.js:16909:24)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at processChildNodes (tsserver.js:110732:48)
    at tsserver.js:110624:21
    at visitNodes (tsserver.js:16639:24)
    at Object.forEachChild (tsserver.js:16869:24)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at tsserver.js:110622:21
    at visitNode (tsserver.js:16634:24)
    at Object.forEachChild (tsserver.js:16764:21)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at processChildNodes (tsserver.js:110732:48)
    at tsserver.js:110624:21
    at visitNodes (tsserver.js:16639:24)
    at Object.forEachChild (tsserver.js:16944:21)
    at processNode (tsserver.js:110621:20)
    at processChildNode (tsserver.js:110681:21)
    at processChildNodes (tsserver.js:110732:48)
    at tsserver.js:110624:21
    at visitNodes (tsserver.js:16639:24)
    at Object.forEachChild (tsserver.js:16871:24)
    at processNode (tsserver.js:110621:20)
    at formatSpanWorker (tsserver.js:110439:17)
    at tsserver.js:110420:208
    at Object.getFormattingScanner (tsserver.js:109209:23)
    at formatSpan (tsserver.js:110420:31)
    at Object.formatSelection (tsserver.js:110238:20)
    at Object.getFormattingEditsForRange (tsserver.js:122387:34)
    at IOSession.Session.getFormattingEditsForRange (tsserver.js:131071:45)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130082:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by kmorales13** [comment] 2019-07-09 20:17
Started having the same issue recently while working in a ReactNative project.

**Comment by mjbvz** [comment] 2019-07-09 20:20
Duplicate of https://github.com/microsoft/TypeScript/issues/29233

**Closed by mjbvz** 2019-07-09 20:20 UTC
Labels: needs more info

**Comment by qwabra** [comment] 2019-07-12 10:23
> <main> TypeScript Server Error (3.5.2) Debug Failure.

with multiline `className`

```tsx
const qwa = () => (<>
	<div className="qwa
	qwa2">div</div>
</>)
```

```
tsc -v
Version 3.3.3
```

```
code -v
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
```

**Comment by capan** [comment] 2019-08-09 12:32
Same problem has just occured on my VS Code Studio. 
I use Ubuntu 18, I've installed VS Code using apt.
I was developing React code when it happened first time.
Any solutions ?

**Comment by hrkazemi** [comment] 2019-08-09 20:53
as [issues/29233](https://github.com/microsoft/TypeScript/issues/29233) said 
if you used // in react tsx file as text, change it to {'//'}
my problem solved by this.
search for // in your code.
