### ISSUE TITLE
VSCode AWS CodeCommit credentials issue

### ISSUE THREAD

**Issue by markl-vesper** [Microsoft/vscode#69566] opened 2019-02-28 00:48 UTC
Issue with git credentials and AWS CodeCommit.

git is working perfectly from command line without any issue. Commit & Push are all good etc etc.

VSCode is showing the updated/changed files and I can commit them from within VSCode. However when I go to push I get an error

Git: APKAXXXXXXXXXXXXXXX@git-codecommit.ap-southeast-2.amazonaws.com
Permission denied (publickey)

Strange that VSCode fails when cmdline and AWS Powershell Tools is all OK

The url/username in the error is not matching my git config file for the repo in question so where is VSCode getting this from and where do you change it to fix it?

**Comment by rebornix** [comment] 2019-02-28 01:02
Duplicate of https://github.com/Microsoft/vscode/issues/57488

**Closed** 2019-02-28 01:02 UTC
Labels: *duplicate
