### ISSUE TITLE
Diff decorators not showing modified lines

### ISSUE THREAD

**Issue by alicanyuksel** [microsoft/vscode#125625] opened 2021-06-06 14:33 UTC
I don't know the cause but I no longer see the git changes (diff decorators) in the file I'm working on. But I can see them well in Source Control. The problem is that it only happens to me for one file, for other files, I have no problem with diff decorators. In the SCM config, everything is enabled for diff decorators. For this problematic file, Vscode changes the color of the file name with the small letter M which means "modified" but not showing modified lines.

Any explication for that ?

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.56.2
- OS Version: Darwin x64 18.7.0

**Comment by IllusionMH** [comment] 2021-06-06 18:16
Have you renamed this file?
Looks like duplicate of #124645 and/or #103444

Check https://github.com/microsoft/vscode/issues/124645#issuecomment-855102385 for possible solution.

**Comment by alicanyuksel** [comment] 2021-06-06 18:53
Yes I'd renamed two files and I've used "git mv" command for that. The other file isn't problematic.
So, it doesn't mean it's not a bug. Sublime, Atom, Pycharm are able to detect all changes even though the files are renamed. It's only Vscode which couldn't manage that.

**Comment by IllusionMH** [comment] 2021-06-06 19:04
/duplicate

I'm not saying it's not a bug, it's just duplicate of existing issues.

**Closed** 2021-06-06 19:04 UTC
Labels: *duplicate
