### ISSUE TITLE
Cannot Collapse Powershell code after trusting Azure Repo

### ISSUE THREAD

**Issue by ctholloway** [microsoft/vscode#153342] opened 2022-06-27 17:17 UTC
After connecting to an Azure Repo and trusting the repo in Manage Workspace trust, the code collapse arrows disappear and we cannot collapse various codeblocks. Previously collapsed code expands.  Putting the repo back in Restricted mode resolves the issue immediately.   We are not having any issues with local files or any files not contained in our Azure Repo.  This issue appeared recently and occurs for multiple users on my team and on multiple computers. We have Powershell scripts in our repo.  This issue occurs for us on both the stable and prerelease version of Azure Repo.

Azure Repo Version:

v0.12.0

Powershell Version 7.2.5

VSCode Version:

Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

![RestrictedRepo](https://user-images.githubusercontent.com/48926625/175997875-2f83a604-8022-46f8-9171-400bcfbd0bfc.PNG)
![TrustedRepo](https://user-images.githubusercontent.com/48926625/175997877-987ea9ba-67d4-408d-9cd6-0e64f4e156f4.PNG)

**Comment by joyceerhl** [comment] 2022-06-27 17:31
@sbatten assigning to you since the repro involves exiting restricted mode

**Comment by sbatten** [comment] 2022-06-27 18:19
I verified that disabling the powershell extension in trusted mode works properly, so this is caused by the extension.

**Closed by sbatten** 2022-06-27 18:19 UTC
