### ISSUE TITLE
Code Actions Are Uppercased

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#226441] opened 2024-08-23 14:08 UTC
![Image](https://github.com/user-attachments/assets/2bdb9167-bf48-4ea5-b968-8557db96c998)

**Comment by justschen** [comment] 2024-08-23 20:38
duplicate of https://github.com/microsoft/vscode/issues/226487, tracking there!

**Closed by justschen** 2024-08-23 20:38 UTC
