### ISSUE TITLE
Spread operator incorrectly flagged as error for "...["

### ISSUE THREAD

**Issue by macp3o** [Microsoft/vscode#61578] opened 2018-10-23 08:21 UTC
Issue Type: <b>Bug</b>

Problem: `[ ...[ ] ]`, and `[ 1, ...[ 2 ], 3 ]`

Actual result: VSCode reports "expression expected" at the location of the `...` and underlines `...` red.

Expected result: Valid syntax.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:34.132Z)
OS version: Linux ia32 4.4.0-137-generic

**Comment by mjbvz** [comment] 2018-10-24 22:14
Can't repo this:

![screen shot 2018-10-24 at 3 13 28 pm](https://user-images.githubusercontent.com/12821956/47464839-62abd380-d79f-11e8-8481-7f16c7c50b0d.png)


Do you still see this if you disable all extensions? Are you using an old version of TypeScript in the workspace?

**Comment by macp3o** [comment] 2018-10-24 22:47
Wow!. Disabled Glacier theme and it solved it. Can a theme do that? It was plain JS. Thanks.

**Comment by mjbvz** [comment] 2018-10-24 22:49
A properly written theme shouldn't have anything to do with error reporting. Are you sure that was all that changed?

**Comment by macp3o** [comment] 2018-10-24 23:12
Correct. I only had one extension (the Glacier theme), and I have automated updates disabled for VSCode.

**Comment by mjbvz** [comment] 2018-10-25 22:59
Ok, I'm going to close this as caused by extension. Let me know if you see it again

**Closed by mjbvz** 2018-10-25 22:59 UTC
Labels: needs more info

**Comment by macp3o** [comment] 2018-10-25 23:03
Sounds good to me. Thanks!
