### ISSUE TITLE
Intellisense not working on custom Typescript functions/properties

### ISSUE THREAD

**Issue by RajanKrishnan** [Microsoft/vscode#40880] opened 2017-12-28 03:00 UTC
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.11.2
Angular-BeastCode|Mik|5.1.15
html-css-class-completion|Zig|1.15.0

---

Steps to Reproduce:

1. Create property or function in your custom Typescript file and try to use them in another html file
This happens with out or with extensions. 

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2018-01-02 19:32
Duplicate of #29315

**Closed by mjbvz** 2018-01-02 19:32 UTC
Labels: typescript
