### ISSUE TITLE
Open with remote container from "code" command

### ISSUE THREAD

**Issue by fire015** [microsoft/vscode#119096] opened 2021-03-16 16:00 UTC
When working with a remote container on my WSL machine, I run `code .` to open the project, then I need to open the command palette and then select the "Remote-Containers: Reopen in Container" command.

This seems like a waste of time. It would be better if running `code .` or `code --remote .` could detect the presence of a `devcontainer.json` file and open in the container rather than in WSL.

**Comment by chrmarti** [comment] 2021-03-17 06:41
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/4684

**Closed by chrmarti** 2021-03-17 06:41 UTC
