### ISSUE TITLE
Paste doesn't work anymore in the built-in terminal (Windows 10)

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#28516] opened 2017-06-12 12:37 UTC
- VSCode Version: 1.14.0-insider 1cc8f3...
- OS Version: Windows 64 bit (insider 16215)
- cmd.exe used for the integrated terminal

Steps to Reproduce:

1. open an existing file and select + copy some text
2. open the built in terminal & right click in it

What happens?
Nothing happens: nothing is pasted. And the clipboard seems to be empty

What should happen?
Text should be pasted and kept in the clipboard.

Note: selecting & copying some text inside the terminal div and then pasting it inside the terminal seems to work. But if it's copied outside of the terminal div, it doesn't work.

**Comment by Tyriar** [comment] 2017-06-12 18:12
Certainly related to the massive changes with selection that just landed https://github.com/Microsoft/vscode/issues/9958, will look into it soon.

**Comment by Tyriar** [comment] 2017-06-12 18:53
Did you have a selection in the terminal beforehand? If so this is by design, at least at the time of implementation. One of the perks of this new selection implementation is that the selection doesn't disappear whenever the terminal loses focus, so the right click you may be expecting to paste may be doing a copy using the existing selection?

**Comment by warpdesign** [comment] 2017-06-12 19:01
No, I didn't have a selection in the terminal.

**Comment by Tyriar** [comment] 2017-06-12 19:37
@warpdesign are you sure? The selections aren't visible currently unless you have a theme that sets `selection.background` (https://github.com/Microsoft/vscode/issues/28554).

If not some follow ups:

- Any errors in devtools console?
- What's in your settings.json file?
- Where are you right clicking exactly (on selection, outside selection, outside viewport)?

**Comment by warpdesign** [comment] 2017-06-12 20:50
@Tyriar I'll try to make a video. No errors in devtools console.

**Comment by warpdesign** [comment] 2017-06-12 21:10
Here is a video (the skin I use supports selection in the terminal).

![vscodepaste](https://user-images.githubusercontent.com/199648/27055292-387e3198-4fc4-11e7-9b80-eb44ad91fe43.gif)

**Comment by warpdesign** [comment] 2017-06-12 21:12
Here is my user settings file:

```json
{
    "window.zoomLevel": 0,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorBlinking": true,
    "workbench.colorTheme": "Dracula",
    "workbench.iconTheme": "vscode-icons",
    "editor.minimap.enabled": true,
    "window.openFilesInNewWindow": "off",
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe",
    "editor.cursorStyle": "line-thin",
    "workbench.statusBar.visible": true,
    "window.menuBarVisibility": "default",
    "workbench.activityBar.visible": true
}
```

And my workspace settings json:

```json
// Place your settings in this file to overwrite default and user settings.
{
	"javascript.validate.enable": true,  
  "jshint.enable": false,
  "jshint.options": {
    "esversion": 6,
    "esnext": true
  },
	"editor.insertSpaces": true,
	"editor.tabSize": 4,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/.happypack": true
    }    
}
```

**Comment by Tyriar** [comment] 2017-06-12 21:38
@warpdesign very helpful thanks. While I look into this again you should fix up the spaces and tabs in your workspace settings.json :wink:

**Comment by warpdesign** [comment] 2017-06-12 21:45
@Tyriar glad it helps. You're right, I'll fix it ;)

**Comment by Tyriar** [comment] 2017-06-12 21:47
Can't repro using regular cmd.exe, how does clink get launched?

**Comment by warpdesign** [comment] 2017-06-12 21:52
I installed it using the installer here: [clink installer](http://mridgers.github.io/clink/). No idea how it gets launched.

But I uninstalled it and still get the same bug.

**Comment by warpdesign** [comment] 2017-06-12 21:56
Hmm.. it might be related to the Windows console: opening an external cmd prompt, right-clicking on the title bar, choosing "default" and checking `use legacy console` seems to fix the problem after restarting Code.

Note that on an external prompt cmd prompt, right-click to paste works, no matter if `use legacy console` is set or not.

**Comment by Tyriar** [comment] 2017-06-12 22:13
Interesting... So I don't have legacy console enabled and it works just fine in VS Code.

Would you be able to debug into `TerminalPanel.ts` here and see if it's hit?

![image](https://user-images.githubusercontent.com/2193314/27057589-aa1bcccc-4f81-11e7-9808-077bd45aa234.png)

**Comment by warpdesign** [comment] 2017-06-13 08:49
@Tyriar It's a hit:
![vscodebreakpoint](https://user-images.githubusercontent.com/199648/27074001-004582ec-5026-11e7-8742-986ceb6ff3db.png)

**Comment by warpdesign** [comment] 2017-06-15 09:32
I think I found the problem: I tried disabling my extensions one by one and it seems [documentThis](https://marketplace.visualstudio.com/items?itemName=joelday.docthis) is the guilty one: if I disable it, right-click to paste works as expected.

**Comment by Tyriar** [comment] 2017-06-16 14:31
@warpdesign very strange, that extension seems to have nothing to do with the terminal. So after installing it against you see the issue occur? Did you try to step through the code and see which path it takes? Was it always going through the `clearSelection()` route for example?

**Comment by jens1o** [comment] 2017-06-16 15:22
I experienced the same issue on Windows. After an Windows update and an Insiders update, it didn't worked anymore. But since then <kbd>Ctrl + V</kbd>(Paste) works fine.

**Comment by Tyriar** [comment] 2017-06-22 19:24
I think this was caused by the bug in `Terminal.hasSelection` https://github.com/sourcelair/xterm.js/pull/725

**Comment by Tyriar** [comment] 2017-06-22 19:25
To verifier: Any OS should do, as long as `terminal.integrated.rightClickCopyPaste` is set to true.

**Closed by Tyriar** 2017-06-22 19:24 UTC
Labels: insiders, integrated-terminal, needs more info
