### ISSUE TITLE
Icons are blurry in 1.44.2

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode#95883] opened 2020-04-22 14:44 UTC
Issue Type: <b>Bug</b>

Some icons in SCM panel appears blurry.

If i rollback to 1.43.2 then this issue goes away, if i upgrade back to 1.44.2 issue reappears.

Screenshot with side-by-side comparision:

![image](https://user-images.githubusercontent.com/993454/79994305-7207fc00-84be-11ea-855d-9a04a402ff48.png)

Top: 1.43.2
Bottom: 1.44.2

Note that "Open File" and "Stage" icons are blurry, while file icons themselves do not look like they are affected by this.

Doesn't always reproduce, sometimes they are fine (not blurry), but after i reload vscode they become blurry anyway. This seems to reproduce less frequently (or doesn't reproduce at all) on section icons (i.e. "Changes" section in SCM panel) or on untracked files, e.g.:

![image](https://user-images.githubusercontent.com/993454/79995129-80a2e300-84bf-11ea-96fc-bec1b10a671f.png)

Also reproducible in insiders build.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.4.0-146-generic

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.44.0
cpptools|ms-|0.19.0
Go|ms-|0.14.1
shader|sle|1.1.4
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by alekseyt** [comment] 2020-05-15 15:22
![image](https://user-images.githubusercontent.com/993454/82066529-3ab0f780-96d8-11ea-9141-3795507c37a6.png)

This is image from vscode insiders build with and without `M` symbol (on the right) indicating type of changes. Note that action icons aren't blurry without `M` symbol and blurry with it.

I suspect that icons are being placed somewhere in the missdle of the pixel (like when position is at x=123.27 or something) due to their alignment and this triggers anti-aliasing, but don't quote me on that.

`M` disappearing may or may not be another bug, idk. But this is how i make it disappear: in insiders build i don't have any extensions enabled, so when i start vscode with `.cpp` file already open (left open from previous launch), it suggests to install C++ extension, i immediately press Esc to dismiss popup and after this modification type icons in VCS somehow don't appear.

**Comment by alekseyt** [comment] 2020-10-24 18:27
Might be OS-specific issue. On Windows adding `display: inline-table;` might or might not improve image quality, icons just stay blurry with or without it. However depending on ClearType settings, there might be some improvements, but not as drastic as on Linux. It still does some sort of anti-aliasing even if icon is supposedly at integer pixel position:

![image](https://user-images.githubusercontent.com/993454/97089300-79f85280-163f-11eb-89da-2bd557db4337.png)

Part of the potential improvement is coming from LCD subpixel rendering, if grayscale is used instead, then icons just appear blurry as usual.

**Comment by deepak1556** [comment] 2020-10-26 19:49
@misolori will let you decide if you want to merge this to https://github.com/microsoft/vscode/issues/86308

**Comment by misolori** [comment] 2020-11-04 20:09
This isn't an icon issue, passing it to @joaomoreno

**Comment by joaomoreno** [comment] 2020-11-05 09:53
@misolori This is a consequence of using fonts as a means to render icons together with the subpixel anti-aliasing. It happens because of https://github.com/microsoft/vscode/blob/dc269a975e2cc5df96d8c02b00b25c37be5409c2/src/vs/base/browser/ui/codicons/codicon/codicon.css#L17-L17

**Comment by joaomoreno** [comment] 2020-11-05 09:57
Actually it seems the bug is that subpixel antialiasing isn't working sometimes, so the icons appear blurry then.

![image](https://user-images.githubusercontent.com/22350/98225981-ac665180-1f55-11eb-88ae-3f9c22c1e9ee.png)

I can't reproduce in SCM, so closing the issue.

**Closed by joaomoreno** 2020-11-05 09:57 UTC

**Comment by alekseyt** [comment] 2020-11-05 11:38
That `M` though. It also appears that there is a mix of grayscale and rgba anti-aliasing on different text elements which is quite interesting on its own, perhaps due to some transformations or opacity applied to said elements.

I'll recheck this issue in 1.51 when it is released.

**Comment by alekseyt** [comment] 2020-11-07 04:14
No, it's still reproducible in 1.51:

![image](https://user-images.githubusercontent.com/993454/98431617-b86e2280-20bf-11eb-9da8-b71ba4594ff4.png)

There is obvious image quality improvement if `display: inline-table;` is added to `.scm-view .monaco-list-row .resource>.name>.monaco-icon-label>.actions .action-label.codicon`:

![image](https://user-images.githubusercontent.com/993454/98431648-ebb0b180-20bf-11eb-811b-a66552990118.png)

The issue is most apparent when (slight) grayscale antialiasing is used in system settings and less apparent when rgba (LCD) antialiasing is used. I guess because grayscale antialiasing is using gray to smooth lines and icons are also gray, this blurs the icons. When rgba antialising is used, smoothing is in different colors, so it's a colored blur which is less obvious, but it exists.
