### ISSUE TITLE
TS Server fatal error:  Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by crallan** [microsoft/vscode#116234] opened 2021-02-09 22:01 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'indexOf' of undefined
    at Object.parsePackageName (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:39472:30)
    at ConfiguredProject.Project.enablePlugin (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:151962:24)
    at ConfiguredProject.enablePluginsWithOptions (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:152477:30)
    at ProjectService.loadConfiguredProject (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154206:25)
    at ProjectService.createAndLoadConfiguredProject (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154145:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:154150:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155055:44)
    at /home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:97
    at Object.flatMap (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:156413:46)
    at /home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158277:28)
    at IOSession.Session.executeCommand (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158286:33)
    at IOSession.Session.onMessage (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:158310:35)
    at Interface.<anonymous> (/home/crallan/.vscode-server/bin/5d424b828ada08e1eb9f95d6cb41120234ef57c7/extensions/node_modules/typescript/lib/tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.21301
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.42GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/crallan/repos/thewall --remote=wsl+Ubuntu --crash-reporter-id ac07df6f-0eeb-4ab4-a38a-7c82500ac1fa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4007)|
|Memory (System)|7.73GB (3.08GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
file-icons|fil|1.0.28
dotenv|mik|1.0.1
remote-wsl|ms-|0.53.3
code-settings-sync|Sha|3.4.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.1
vscode-graphql|Gra|0.3.15
vscode-docker|ms-|1.9.1
vsliveshare|ms-|1.0.3629

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by daniel-white** [comment] 2021-02-09 22:04
duplicate: https://github.com/microsoft/vscode/issues/116229

**Comment by mjbvz** [comment] 2021-02-09 22:23
Duplicate of #116219

**Closed by mjbvz** 2021-02-09 22:23 UTC
Labels: new release
