### ISSUE TITLE
The Debug show an error: I can highlight it, but I can't copy it

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#75117] opened 2019-06-08 08:35 UTC
Issue Type: <b>Bug</b>

I tried to copy the text shown in this print screen
![image](https://user-images.githubusercontent.com/24194840/59144244-2d25c480-89d5-11e9-8f49-9775b7b445e7.png)

 When I select the text (it highlights in blue) then click on ctrl+C, the little error frame disappears, and doesn't copy anything.  

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
transformer|dak|1.6.0
vscode-eslint|dba|1.9.0
vscode-todo-plus|fab|4.13.0
macros|ged|1.2.1
beautify|Hoo|1.5.0
vscode-favorites|how|1.4.0
reg|ion|0.0.2
vscode-opn|lfu|1.1.2
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
powershell|ms-|2019.5.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.2.9
vscode-fileutils|sle|2.14.5
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
local-history|xyz|1.7.0

</details>

**Comment by isidorn** [comment] 2019-06-10 09:55
This works for me. Are you doing something differently than me?
Can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/

![copy](https://user-images.githubusercontent.com/1926584/59187792-8a0cb080-8b76-11e9-8bee-20ebd742cc8a.gif)

**Comment by WiliTest** [comment] 2019-06-12 04:55
I apologize for the delay.
Yes, I'm doing exactly the same as you do, but it doesn't copy anything.

The context menu doesn't show when I highlight and right click.

Before installing vs code insiders,  after trying, how could I go back to the "normal" version (without losing my configuration). Or should I install it separately?

**Comment by isidorn** [comment] 2019-06-12 08:16
If it is fixed in insiders than it should be fixed in the next stable in a month.
Also make sure that one of your extensions is not breaking this (try disabling extensions one by one).

**Closed by isidorn** 2019-06-12 08:16 UTC
Labels: debug, needs more info

**Comment by WiliTest** [comment] 2019-06-20 14:29
The problem came back (it might be an extension though, I did not look into that)
