### ISSUE TITLE
Pinned tabs scroll out of view

### ISSUE THREAD

**Issue by envirocoder** [microsoft/vscode#116431] opened 2021-02-11 09:27 UTC
- VS Code Version: 1.53.1
- OS Version: Linux

Apologies if it's my misunderstanding of how pinned tabs work, but I've never been able to get them to work -- if I pin a tab it reorders it to the start, but it doesn't prevent it from scrolling off the left side when I add more tabs or scroll through tabs.
![video(1)](https://user-images.githubusercontent.com/51299908/107619565-44f22900-6c4b-11eb-8c59-db13e1475bf5.gif)

Steps to Reproduce:

1. Select Pintab on one or more tabs
2. Scroll tab bar -- pinned tab still scrolls off screen

It is the same in the latest insiders:
![video(2)](https://user-images.githubusercontent.com/51299908/107620287-5ab41e00-6c4c-11eb-9edb-04ab8f86b3ba.gif)
Version: 1.54.0-insider
Commit: 93f705ab40b37aade9d3b5165ed09114a8c87ac9
Date: 2021-02-11T05:44:44.032Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.15.0-135-generic

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-02-11 12:19
Duplicate of #111896 and works as designed according to https://github.com/microsoft/vscode/issues/111896#issuecomment-738852209

**Comment by envirocoder** [comment] 2021-02-11 14:20
Thanks -- agree it does work as designed.

However, is there any sense in making `Pinned Tab Sizing` default to `shrink` -- I didn't even know there was a setting for it, and it seems more useful setup that way, and I'm not sure the advantage of it being in `normal` ?

**Closed** 2021-02-12 06:51 UTC
Labels: *question, new release

**Comment by envirocoder** [comment] 2021-02-12 09:07
This isn't a question I need answering, It's a proposal for a change to the default setting that will hopefully make VSCode easier to use.
