### ISSUE TITLE
When file is renamed, IDE spoiled all import directive

### ISSUE THREAD

**Issue by master-7** [Microsoft/vscode#55137] opened 2018-07-26 11:42 UTC
- VSCode Version: version 1.25
- OS Version: Mac High Siera 10.13.6  

Steps to Reproduce:

1. Rename file in VS code
2. All imports in project spoilt

Looks like
```js
import { clone, compose } from '../../../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/ramda'
```
Instead of
```js
import { clone, compose } from 'ramda'
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2018-07-26 22:04
Duplicate of #54841

**Closed by mjbvz** 2018-07-26 22:04 UTC
Labels: javascript
