### ISSUE TITLE
Windows: Investigate changes to API behavior for Wi-Fi access and location

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#196746] opened 2023-10-26 18:02 UTC
Due to this upcoming [breaking change in Windows](https://learn.microsoft.com/en-us/windows/win32/nativewifi/wi-fi-access-location-changes), it seems like VS Code is shown as an application which occasionally asks for Location:

> We are seeing location access prompts being generated by this app due to a breaking change in Windows 2024 and want to be sure that this is expected, and that no fixes in the app need to be made.
[Changes to API behavior for Wi-Fi access and location - Win32 apps | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fnativewifi%2Fwi-fi-access-location-changes&data=05%7C01%7CJoao.Moreno%40microsoft.com%7Cbde138e5fba34460c3f608dbd5f676cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638339026762824131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BKp6kV37XhFPCTAJE3EBxjkE9IPp%2BOOYfW2jwZXoykw%3D&reserved=0)
>
> Is VS Code calling either the Wi-Fi or Location APIs and has a use case for location? If not, this may result in end-user confusion.

As for rollout schedule:

> - In a Windows Insider Preview release, the changes will first take effect in October 2023.
> - You'll then have until the following Windows feature release in fall of 2024 to test your app's scenarios, and to make any necessary changes. After that date, Windows devices will begin getting the update that contains the behavior change described above.

**Comment by deepak1556** [comment] 2023-12-06 02:54
Prompt confirmed, affects all Electron applications.

![location_prompt](https://github.com/microsoft/vscode/assets/964386/ebcfba0f-64bf-4faf-aa90-7ba6bc42bcf7)

**Comment by deepak1556** [comment] 2023-12-14 16:19
Got steps to retrigger the prompt for further analysis. One thing I found today, prompt does not trigger with Electron 27 based insiders. This hints positive, we might not need to make any changes in the runtime. I will confirm the details in following days.

**Comment by deepak1556** [comment] 2024-01-09 08:49
`WlanQueryInterface` was being called on application startup in stable as part of creating the network context as seen in the screenshot below
![wlan_usage_electron](https://github.com/microsoft/vscode/assets/964386/17882198-5b6d-4a78-a6ff-10b3ab0212e6)

The relevant code has been refactored and removed from the startup path since this CL https://chromium-review.googlesource.com/c/chromium/src/+/4485483 which first landed in Chromium 115, also validated there are no other usages of the affected api in the latest insiders based on Chromium 118. Closing this issue are resolved, next stable release `1.86` should have the changes as well.

**Closed by deepak1556** 2024-01-09 08:49 UTC
Labels: bug, upstream, windows, electron

**Comment by andreamah** [comment] 2024-01-25 20:24
@deepak1556 @joaomoreno How can we verify this?

**Comment by deepak1556** [comment] 2024-01-26 00:28
Steps for verification:

* Use a device that has Wi-Fi access
* Switch to canary channel of Windows OS
* Under OS settings > Privacy & security > Location
* Ensure location services is On and `Let apps access your location` set to Off
* Launch VS Code insiders and confirm that prompt from https://github.com/microsoft/vscode/issues/196746#issuecomment-1842002963 is not seen
* Launch VS Code stable and confirm that prompt from https://github.com/microsoft/vscode/issues/196746#issuecomment-1842002963 is seen

**Comment by deepak1556** [comment] 2024-01-26 00:29
The bug was about verifying the issue, which I have already done so feel free to skip verifying again.
