### ISSUE TITLE
Insiders TS/JS language services die 5 times, complain I have an undefined version

### ISSUE THREAD

**Issue by mtaran** [microsoft/vscode#143140] opened 2022-02-15 21:25 UTC
Issue Type: <b>Bug</b>

1. Open the editor on my project
2. Wait for a while as my laptop tries to take off like a jet engine (during which time the language service does seem to start up, e.g. it adds inlay type hints etc.)
3. Eventually the fan noise subsides and VSCode gives up, saying that the service crashed after starting five times and won't be restarted.
4. Click the button to file an issue and get greeted with a prompt saying that I'm not cool enough to file an issue because "The workspace is using an old version of TypeScript (undefined)."

The lasts bit is obviously unhelpful. The package.json file of the project open in my workspace specifies TS 4.4, which is fairly recent and has been working fine until an Insiders update last week. After that, this crash issue happens every time I start it.

Happy to provide more info if I can!

VS Code version: Code - Insiders 1.65.0-insider (Universal) (50089c3f92c17584a4aca179f51f220b56c22020, 2022-02-14T05:17:15.582Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|26, 24, 13|
|Memory (System)|64.00GB (1.36GB free)|
|Process Argv|--crash-reporter-id c7f5de1e-17f9-4102-a676-dc1fa20b59e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
flip|Chr|0.0.4
jump-to-last-cursor|ctf|0.0.1
native-ascii-converter|cwa|1.0.9
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
githistory|don|0.6.19
kusto|don|0.3.8
xml|Dot|2.5.1
gitlens|eam|11.7.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.2.0
flow-for-vscode|flo|2.0.0
duplicate|gee|1.0.2
codespaces|Git|1.5.3
copilot|Git|1.7.23
remotehub|Git|0.24.0
vscode-pull-request-github|Git|0.36.1
go|gol|0.31.1
gc-excelviewer|Gra|4.0.50
vscode-mocha-test-adapter|hbe|2.13.1
vscode-test-explorer|hbe|2.21.1
highlight-string-code|iuy|0.4.5
svg|joc|1.4.17
jq-syntax-highlighting|jq-|0.0.2
language-haskell|jus|3.4.0
nim|kos|0.6.6
go-prof|Max|0.0.4
vscode-docker|ms-|1.19.0
remote-containers|ms-|0.222.0
remote-ssh|ms-|0.70.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.64.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.0
cpptools|ms-|1.8.4
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.5
vscode-typescript-tslint-plugin|ms-|1.3.3
negate-numbers|mta|0.0.1
vscode-paste-image|mus|1.0.4
elm|sbr|0.26.0
rewrap|stk|1.16.2
vscode-open-in-github|sys|1.16.0
remove-blank-lines|tha|1.1.1
vscode-input-sequence|tom|0.2.0
faster-new|wen|1.5.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
sublime-commands|Zar|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30421357
vsclayoutctrc:30405799
dsvsc008:30436272
pythonvsnew555cf:30426299
vsbas813:30436447
vscscmwlcmt:30428973
azactmsal:30432848
vscgsvid2:30433758
helix:30438212
cppdebug:30437091
dockersurvey3:30438168

```

</details>

**Comment by mjbvz** [comment] 2022-02-15 23:32
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment] 2022-02-15 23:33
Also be sure to test using the latest TypeScript builds, specifically the 4.6-rc, to make sure this has not already been fixed. This version is included in the current VS Code insiders

**Comment by mjbvz** [comment] 2022-03-09 00:03
Thanks for the logs. Based on them, this is a duplicate of this ts-lint plugin issue: https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/148#issuecomment-1040871143

**Closed by mjbvz** 2022-03-09 00:03 UTC
Labels: needs more info
