### ISSUE TITLE
SSH connecting then parse error

### ISSUE THREAD

**Issue by cybath** [microsoft/vscode#115470] opened 2021-01-30 17:14 UTC
Local macOS 10.15.7
Remote Ubuntu 20.04.2
 When I attempt to connect to the remote machine, the connection is established and then a parse error occurs in VSCode. However from my local machine's terminal I can log in without a problem. I have tried reverting the extension version to previous versions and the same error occurs. I also have tried modifying the config file and that hasn't helped either. In reading other troubleshooting forums, it seems like I am not the first to have this issue, however the recommendations haven't worked for me. I have also done a clean install of VScode. 

The error I get is:

[11:43:12.307] Failed to parse remote port from server output
[11:43:12.313] Resolver error: Error: 

Any recommendations on how to resolve this?

**Comment by cybath** [comment] 2021-01-30 17:17
Additionally i can connect to a different VM using the client just fine

**Comment by gjsjohnmurray** [comment] 2021-01-31 03:38
> I have tried reverting the extension version

Which extension? 

Please also post the VS Code version information from the About box.

**Comment by cybath** [comment] 2021-01-31 14:07
@gjsjohnmurray It is the Remote - SSH extension by Microsoft. 

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by gjsjohnmurray** [comment] 2021-01-31 16:24
/causedByExtension

Looks like a duplicate of #115066

**Closed** 2021-01-31 16:24 UTC
Labels: *caused-by-extension

**Comment by cybath** [comment] 2021-01-31 16:29
@gjsjohnmurray It might be however, downgrading to v.62 does not help resolve the issue

**Comment by gjsjohnmurray** [comment] 2021-01-31 16:32
@cybath please open a fresh issue on the extension's repo, then link this to it.
