### ISSUE TITLE
General Task Explorer like NPM Scripts

### ISSUE THREAD

**Issue by shba007** [microsoft/vscode#148028] opened 2022-04-25 05:51 UTC
Task Explorer by Scott Meesseman should be natively supported like NPM scripts for better Developer Experience 

![image](https://user-images.githubusercontent.com/48382105/165034398-2044a19e-5e55-46a5-9936-41aac57d2edf.png)

**Comment by alexr00** [comment] 2022-04-25 07:57
Duplicate of https://github.com/microsoft/vscode/issues/28235

**Closed by alexr00** 2022-04-25 07:57 UTC
