### ISSUE TITLE
Typescript Auto-import produces invalid code if there is a trailing comma on the existing imports

### ISSUE THREAD

**Issue by paustint** [microsoft/vscode#107079] opened 2020-09-19 20:47 UTC
- VSCode Version: Version: 1.49.1
- OS Version: OSX 10.15.6 (19G2021)

Steps to Reproduce:

1. Create a file with multi-line imports (E.x. many imported items from one source file)
2. Write code which includes a typescript type that needs to be imported from the same file
3. Put the cursor at the end of type and press cmd+space to open intellisense menu
4. Press enter to auto import

NOTE: This seems to happen any time there is a trailing comma on a prior imports and the auto-import adds the new item at the end (which does not always seem the case)

### before import

```typescript
import {
  ToolingFlowRecord,
  ToolingFlowRecordWithDefinition,
  MetadataWorkflowRuleRecord,
  ToolingWorkflowRuleRecord,
  ToolingWorkflowRuleRecordWithMetadata,
  ToolingMetadataComponentDependencyRecord,
  ToolingFlowDefinitionWithVersions,
  AutomationControlMetadataTypeItem,
  ToolingValidationRuleRecord,
  ToolingAssignmentRuleRecord,
  ToolingApexTriggerRecord,
} from './automation-control-types';

export function initItemsById() {
  const foo: AutomationControlParentSobject;
}
```

### after import

```typescript
import {
  ToolingFlowRecord,
  ToolingFlowRecordWithDefinition,
  MetadataWorkflowRuleRecord,
  ToolingWorkflowRuleRecord,
  ToolingWorkflowRuleRecordWithMetadata,
  ToolingMetadataComponentDependencyRecord,
  ToolingFlowDefinitionWithVersions,
  AutomationControlMetadataTypeItem,
  ToolingValidationRuleRecord,
  ToolingAssignmentRuleRecord,
  ToolingApexTriggerRecord,, AutomationControlParentSobject
} from './automation-control-types';

export function initItemsById() {
  const foo: AutomationControlParentSobject;
}
```
![image](https://user-images.githubusercontent.com/5461649/93688949-2f574980-fa87-11ea-9817-ca69f7f6f8ad.png)

![image](https://user-images.githubusercontent.com/5461649/93688942-26667800-fa87-11ea-9486-651bfd6e8abc.png)

Does this issue occur when all extensions are disabled?: **Yes**/~~No~~

**Comment by mikecann** [comment] 2020-09-21 11:09
I can confirm this is happening and is super frustrating if you are using Prettier

**Comment by mjbvz** [comment] 2020-09-21 17:00
Duplicate of #107057

**Closed by mjbvz** 2020-09-21 17:00 UTC
Labels: new release
