### ISSUE TITLE
Release notes tab does not remember scroll position

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#24122] opened 2017-04-06 18:37 UTC
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.19

Steps to Reproduce:

1. Open release notes
2. Scroll
3. Change tab
4. Change tab back to release notes
5. Scroll position of release notes tab is not preserved

**Comment by mjbvz** [comment] 2017-04-06 19:46
Duplicate of #15214

**Closed by mjbvz** 2017-04-06 19:46 UTC
Labels: duplicate, webview
