### ISSUE TITLE
双引号

### ISSUE THREAD

**Issue by 18894142401** [Microsoft/vscode#57094] opened 2018-08-23 14:46 UTC
Issue Type: <b>Feature Request</b>

希望在写html时输入class=时自动添加双引号，或者class=“时自动添加另一个双引号，我是初始者，使用过sublime,webstorm,Hbuilder

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by byyxx128** [comment] 2018-08-23 15:18
@18894142401 
现在就是这样的，你用成中文标点了吧……下次反馈问题用英文……

Translation here:
> I suppose that quotation marks can be added when I input `class=` in html, or another quotation mark can be added after I input `class=“`. I am a beginner and I've used Sublime, WebStorm, HBuilder.

　　I think the author cause the issue because he used a wrong quotation mark, `“` is a Chinese quotation mark. So he shouldn't input `class=“`, he should use `class="`, as `"` is English quotation mark.
　　But sometimes it is difficult to identify under some fonts.

**Comment by rebornix** [comment] 2018-08-23 20:00
Thanks @byyxx128 for doing the translation. I have a feeling that a wrong double quote is used, close this issue for now but @18894142401 confirmed that it's not the case, we can have it reopened.

**Closed by rebornix** 2018-08-23 20:00 UTC
