### ISSUE TITLE
Pasting specific text into terminal freezes VSCode

### ISSUE THREAD

**Issue by natefinch** [Microsoft/vscode#32605] opened 2017-08-16 03:58 UTC
- VSCode Version: 1.15.0
- OS Version: OSX

Steps to Reproduce:

1.  Open terminal
2. paste the following text into the terminal:

"\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a\xb5\x27\xc1\x20"

The way I originally triggered this was doing a diff of some encoded binary data.  This was a tiny piece of a 1000 character string.  Originally I thought it was a long line problem, but evidently not.

Note this happens with the default terminal and with iTerm2 .  Not sure about other OSes.

Reproduces without extensions: Yes/No

Yes

**Comment by rmunn** [comment] 2017-08-16 04:13
I can reproduce on Linux (Linux Mint 18) but not on Windows (Windows 10), so this is probably Unix-related.

**Comment by rmunn** [comment] 2017-08-16 04:50
I also noticed, on my Linux box, that pasting portions of that text causes the integrated terminal to start slowing down and becoming more and more unresponsive. What I mean is:

1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c" into the terminal, and press Enter. Now press Enter a second time. VS Code has a very slight slowdown in responding to the second Enter keypress, but I wouldn't have noticed it if I wasn't specifically looking for it.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3" into the terminal, and press Enter. Now press Enter a second time. Same thing: slight, barely noticeable slowdown in VS Code's responsiveness to that second Enter keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code becomes noticeable: about 1-2 seconds to respond to that second Enter keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code becomes still more noticeable: about 2-3 seconds to respond to the second keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code becomes significant: about 5 seconds to respond to the second keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a\xb5" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code increases again: about 9 seconds to respond to the second keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a\xb5\x27" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code increases again: about 18 seconds to respond to the second keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a\xb5\x27\xc1" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code increases again: about 36 seconds to respond to the second keypress.
1. Kill the terminal by clicking the garbage can icon, then reopen the integrated terminal.
1. Paste "\xff\x8c\x90\xc1\x6a\xeb\x30\x10\x45\xf7\xfe\x8a\xbb\x73x1e\x3c\xd3\x0f\xf0\x4a\xb5\x27\xc1\x20" into the terminal, and press Enter, then press Enter again. Slowdown in VS Code increases again: about 72 seconds to respond to the second keypress.

The doubling of the unresponsive time with every additional character is very, very suggestive. Also, during that unresponsive period, VS Code is using 100% CPU and does not respond to other input either: e.g., a mouse click on a folder's "open this item" triangle will appear to do nothing, but if you wait the 18, or 36, or 72 seconds for VS Code to become responsive again, both the Enter keypress and the mouse click events will be processed.

NOTE: I made sure to kill the terminal in between each step of this process, because at first I thought I was seeing cumulative delays. But that may not have been necessary: after I pasted the 18-second-delay string, then pasted the 36-second-delay string, I would have expected to see a 54-second delay if the delays really were cumulative, but I did not. I only saw the same 36-second delay that I had seen when I pasted that string into a fresh Terminal process.

**Comment by rmunn** [comment] 2017-08-16 04:57
Same thing, with the exact same timings (18 seconds, 36 seconds, etc.) happens with the Insiders build:

Version 1.16.0-insider
Commit baa6fbece9035e3d20cbcb776d73ebc6c4ddde26
Date 2017-08-15T05:09:24.067Z

**Comment by Tyriar** [comment] 2017-08-16 16:40
Duplicate of https://github.com/Microsoft/vscode/issues/24795

**Closed by Tyriar** 2017-08-16 16:40 UTC
Labels: integrated-terminal, new release
