### ISSUE TITLE
quick import path is too long, display information can not compare the difference

### ISSUE THREAD

**Issue by reaink** [microsoft/vscode#167690] opened 2022-11-30 07:35 UTC
<img width="930" alt="Screenshot 2022-11-30 at 15 31 14" src="https://user-images.githubusercontent.com/45023042/204734289-19cacb52-b488-44de-b662-395f2695e725.png">

show path ends info, `/ab/cd/..../df/foo.ts`

**Comment by mjbvz** [comment] 2022-11-30 17:46
@jrieken Adding you in case we want to change how the suggest widget shows truncated paths here. I think TS including the full path is correct because you do need to know which specific file the import comes from (not just the file name)

@reaink The intellisense box is resizable. If you want to see the full path, try expanding its width

**Comment by mjbvz** [comment] 2022-12-05 19:42
Marking this as by design. We have to truncate the path somewhere in these cases and the VS Code APIs can't safely make  assumptions about where the truncation should be (start vs end)

**Closed by mjbvz** 2022-12-05 19:42 UTC
Labels: feature-request, ux, suggest
