### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:4 and sourceFile.scriptKind: 1, !entry: false

### ISSUE THREAD

**Issue by DoveLanLan** [microsoft/vscode#183382] opened 2023-05-25 01:25 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.1-rc

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:4 and sourceFile.scriptKind: 1, !entry: false
    at getDocumentRegistryEntry (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:133137:11)
    at Object.releaseDocumentWithKey (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:133234:19)
    at getOrCreateSourceFileByPath (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141912:30)
    at Object.getOrCreateSourceFile (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141896:14)
    at e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141828:42
    at Object.getSourceFileWithCache [as getSourceFile] (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:117906:24)
    at findSourceFileWorker (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120299:23)
    at findSourceFile (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120219:20)
    at e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120168:22
    at getSourceFileFromReferenceWorker (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120152:69)
    at processSourceFile (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120166:5)
    at processRootFile (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119963:5)
    at e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118718:41
    at forEach (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2325:22)
    at createProgram (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118718:5)
    at synchronizeHostData (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141852:15)
    at Object.getProgram (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141924:5)
    at InferredProject2.updateGraphWorker (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174484:41)
    at InferredProject2.updateGraph (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174336:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176726:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178344:12)
    at e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178574:64
    at flatMap (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2573:17)
    at _ProjectService.applyChangesInOpenFiles (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:178574:24)
    at updateOpen (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:179754:29)
    at e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182326:69
    at IpcIOSession.executeWithRequestId (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182318:14)
    at IpcIOSession.executeCommand (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182326:29)
    at IpcIOSession.onMessage (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182368:51)
    at process.<anonymous> (e:\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:183948:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (f6be5461f8bc69013a605f5baea834651c6589fb, 2023-05-20T01:18:53.811Z)
OS version: Windows_NT x64 10.0.19041
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.10GB free)|
|Process Argv|--crash-reporter-id eb5e479c-6345-4510-b75b-cdaf9864d067|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
gitlens|eam|2023.5.2405
prettier-vscode|esb|9.13.0
auto-rename-tag|for|0.1.10
codespaces|Git|1.14.7
copilot-chat|Git|0.1.2023052205
copilot-nightly|Git|1.86.114
go|gol|0.38.0
code-spell-checker|str|2.20.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
cai9j608:30680470
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-25 22:16
Duplicate of https://github.com/microsoft/TypeScript/issues/54381

**Closed by mjbvz** 2023-05-25 22:16 UTC
