### ISSUE TITLE
About Search

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#42075] opened 2018-01-24 07:12 UTC
hope vs-code provide multi search results view. can see several keyword result at the same time .

**Comment by usernamehw** [comment] 2018-01-24 10:23
Use regex?

**Comment by doyee** [comment] 2018-01-26 07:41
@midGitub you can use regex search

**Comment by midGitub** [comment] 2018-01-26 07:47
thanks ,that's a solution.

**Comment by roblourens** [comment] 2018-01-26 17:33
Also duplicate of https://github.com/Microsoft/vscode/issues/16488

**Closed** 2018-01-29 07:18 UTC
Labels: *duplicate, search

**Comment by mccreeker** [comment] 2018-02-03 00:12
Not seeing how to do a regex search that's separate from a normal search... I need multi-search instances due to comparing two different code installs for a site conversion.
