### ISSUE TITLE
Allow Cloning Git repositories using ssh instead of http

### ISSUE THREAD

**Issue by Matt-1-2-3** [Microsoft/vscode#21448] opened 2017-02-26 17:16 UTC
- VSCode Version: 1.9.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Select Clone Git repository
2. Enter git@github.com:Matt-1-2-3/random_junk.git 

This works in Git CLI and Pycharm IDE but VS Code is expecting only HTML link e.g. https://github.com/Matt-1-2-3/random_junk.git

Also I should mention that if you initially clone via ssh and the git command line, VS code will then happily push changes via ssh afterwards.

**Comment by joaomoreno** [comment] 2017-02-28 09:52
Can you show us a screencast of what happens? SSH urls should work.

**Comment by Matt-1-2-3** [comment] 2017-02-28 12:59
So I have included 2 screenshots. You can see the SSH url is surrounded by a red box. When I hit enter it doesn't clone the repository. If I use the HTTP url you notice there is NO red box surrounding it and hitting enter begins the clone process.

I get the same behavior on my Mac and Fedora 25 machines. Both clone fine using SSH via command line and Pycharm IDE but will not work with VS Code.

<img width="666" alt="ssh_url" src="https://cloud.githubusercontent.com/assets/25351176/23406120/66b74a9e-fd8b-11e6-9fd0-31ae999ddab0.png">
<img width="651" alt="http_url" src="https://cloud.githubusercontent.com/assets/25351176/23406121/66c5a9c2-fd8b-11e6-9a0a-968a8ed4e10c.png">

**Comment by Matt-1-2-3** [comment] 2017-02-28 13:17
Here is me cloning on the same machine using the cli 

<img width="1193" alt="cli" src="https://cloud.githubusercontent.com/assets/25351176/23406708/59f77e34-fd8e-11e6-93f7-8176588dc4e2.png">

**Comment by rmunn** [comment] 2017-02-28 13:41
I can reproduce this, using a [repo I just created to reproduce a *different* bug](https://github.com/rmunn/repro-csvprovider-slowness). Cloning `git@github.com:rmunn/repro-csvprovider-slowness.git` doesn't work, because the Git Clone command rejects that as an invalid URL. But if I edit the URL to be `ssh://git@github.com/rmunn/repro-csvprovider-slowness` instead, then the URL is accepted. It looks like the Git Clone command just doesn't like repo URLs with no protocol part, whereas the Git command line accepts them.

**Comment by joaomoreno** [comment] 2017-02-28 14:10
This is now fixed in the new SCM Preview, soon to replace the current Git behaviour.

Until then: workaround is @rmunn's solution: use `ssh:`

**Closed by joaomoreno** 2017-02-28 14:10 UTC
Labels: needs more info
