### ISSUE TITLE
Drag and drop files from Explorer not working 

### ISSUE THREAD

**Issue by vHrqO** [microsoft/vscode#230664] opened 2024-10-06 19:35 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0-insider
- OS Version: Windows 11 23H2(22635.4300)

Steps to Reproduce:

1. run vscode
2. Drag and drop file from explorer
3. Nothing changed

Temporary fix: roll back to version 1.94.0

![ezgif-2-4ca97f23c7](https://github.com/user-attachments/assets/a43e3ce9-4849-4533-a56e-0da6e3471702)

**Comment by gjsjohnmurray** [comment] 2024-10-06 20:51
/duplicate of #230536 and fix expected in Monday build.

**Closed** 2024-10-06 20:52 UTC
Labels: *duplicate
