### ISSUE TITLE
 Uncaught Error: Illegal value 21 for `lineNumber`

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#43667] opened 2018-02-14 15:14 UTC
Issue Id: <b>bf73c273-f2fc-8360-56e2-bbedf67b0b6a</b><br /><br />*Versions* <br />- 1.20.0<br />-  7636a7d6f7d2749833f783e94fd3d48d6a1791cb<br />-  3f8cf5311b631c5bc395df1e8b9c795358c1ef80<br />*Stack* <br />Error: Illegal value 21 for `lineNumber`<br />[/vs/editor/common/model/textModel.ts#L776:9](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/common/model/textModel.ts#L776:9)<br />[/vs/editor/contrib/quickFix/lightBulbWidget.ts#L141:28 (getLineContent)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/contrib/quickFix/lightBulbWidget.ts#L141:28 (getLineContent))<br />[/vs/editor/contrib/quickFix/lightBulbWidget.ts#L112:9 (_show)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/editor/contrib/quickFix/lightBulbWidget.ts#L112:9 (_show))<br />[/vs/base/common/winjs.base.raw.js#L1524:0 (onComplete)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1524:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1180:0 (call)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1180:0 (call))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1813:0 (complete)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1813:0 (complete))<br />[/vs/base/common/winjs.base.raw.js#L1838:0 (argDone)](https://github.com/microsoft/vscode/blob/c63189deaa8e620f650cc28792b8f5f3363f2c5b/src/vs/base/common/winjs.base.raw.js#L1838:0 (argDone))<br />

**Comment by egamma** [comment] 2018-02-14 15:17
closing as duplicate of #43662

**Closed by egamma** 2018-02-14 15:17 UTC
Labels: editor, editor-code-actions
