### ISSUE TITLE
Feature Request: Allow disabling of angular 1.* HTML options

### ISSUE THREAD

**Issue by Brocco** [Microsoft/vscode#17613] opened 2016-12-20 14:56 UTC
Currently in HTML files by default there are autocomplete options for angular 1.* (i.e. `ng-if`, `ng-repeat`, `ng-show`)

Many developers use VS Code for web development without using angular 1.* and would like to either have these helpers turned off by default or have an option to be able to turn them off from within user/workspace settings.

**Comment by egamma** [comment] 2016-12-20 16:15
@Brocco there already is a setting for this `html.suggest.angular1` that you can set to false. Doesn't this work anymore?

FYI the suggest settings for HTML are:
```
  // Configures if the built-in HTML language support suggests Angular V1 tags and properties.
  "html.suggest.angular1": true,

  // Configures if the built-in HTML language support suggests Ionic tags, properties and values.
  "html.suggest.ionic": true,

  // Configures if the built-in HTML language support suggests HTML5 tags, properties and values.

```

**Comment by Brocco** [comment] 2016-12-20 16:26
I hadn't known about those settings before, but just tried setting `"html.suggest.angular1": false` in both user & workspace settings and am still seeing the angular 1 options (ng-if, ng-include...) in an html file.

I also tried killing and reopening VS Code with no success.

FYI @egamma, this is with the Insiders version, which I use exclusively.

**Comment by egamma** [comment] 2016-12-20 16:30
@Brocco then this looks like a regression, the implementation of the html support has changed significantly since these options were introduced.

**Comment by Brocco** [comment] 2016-12-20 16:33
I may try to look into this as well, I'll keep you posted if I find something.

**Comment by aeschli** [comment] 2017-01-04 00:48
It was broken. Fixed with 420de32d3c94fea1b20a74831453617ca9bfb0fc

**Closed by aeschli** 2017-01-04 00:48 UTC
Labels: bug, html

**Comment by scniro** [comment] 2017-05-01 13:49
This still seems to be an issue, unless I am using the API incorrectly. Please see https://github.com/Microsoft/monaco-html/issues/3

**Comment by Hirse** [comment] 2017-11-06 05:07
Why are these suggestions turned on by default anyway?
It seems weird to have this specific framework supported by default.
