### ISSUE TITLE
File explorer does not correctly list case sensitive directories

### ISSUE THREAD

**Issue by huettenhain** [microsoft/vscode#90983] opened 2020-02-19 12:54 UTC
#### Host Information

- VSCode Version: 1.42.1
- VSCode Insiders Version: 1.43.0-insider, Commit https://github.com/microsoft/vscode/commit/c94724193451009962e2c116808f71a3328a9836
- OS Version: Windows 10, 1903, Build 18362.592

Does this issue occur when all extensions are disabled?: Yes

#### Steps to Reproduce:
1. Create a directory `foo`
2. Navigate to `foo` as an Administrator account and issue the command
    ```
    fsutil file setCaseSensitiveInfo . enable
    ```
3. Create files named `bar` and `BAR` inside the directory `foo`
4. Open the directory `foo` in Visual Studio Code

#### Expected Behavior:
There are two files visible in the file explorer panel.

#### Observed Behavior:
Only one file is visible.

#### Remarks
Using the quick-jump feature, it is possible to open other files from the opened directory, but it would be much more comfortable if the explorer panel would also support case sensitive folders. I thought this might be related to #79205, but I also tried this with the insiders build https://github.com/microsoft/vscode/commit/c94724193451009962e2c116808f71a3328a9836 and the behavior was the same.

#### Use Case
I work on code where (unfortunately) some file names only differ in case. Since I work on Windows, I made the directory case sensitive, but was puzzled to find that VSCode does not correctly display the file tree for a directory tree where certain folders are case sensitive.

**Comment by isidorn** [comment] 2020-02-19 14:01
For this the FileSystem provider for windows would have to notify us that it is case insensitive.
Not currently working, thus assigning to Backlog to potentially fix in the future.

**Comment by huettenhain** [comment] 2020-02-19 16:45
Playing around in VSCode insiders I just realized that there is a workaround for this if you run WSL: Opening the folder using [remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) will correctly list all present files in the explorer panel.

**Comment by isidorn** [comment] 2020-02-19 16:57
Yeah. Since that file system provider correctly states it is case insensitive.

**Closed** 2020-05-19 11:45 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by ExE-Boss** [comment] 2020-10-06 20:18
Duplicate of <https://github.com/microsoft/vscode/issues/94307>
