### ISSUE TITLE
Paste doesn't work in terminal in VSCode windows

### ISSUE THREAD

**Issue by alexsorokoletov** [Microsoft/vscode#9201] opened 2016-07-13 11:06 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. open terminal with Ctrl Shift `
2. press Ctrl+V, you see ^V entered
3. pressing Ctrl+V in just cmd.exe (running it separately) pastes the clipboard
4. using Edit->Paste menu in VS Code works. Interesting, this menu has shortcut Ctrl+V

**Comment by Tyriar** [comment] 2016-07-13 14:33
Duplicate of #6451

**Closed by Tyriar** 2016-07-13 14:33 UTC

**Comment by alexsorokoletov** [comment] 2016-07-13 14:58
Thanks and sorry for the noise, should've check the issues before

**Comment by Tyriar** [comment] 2016-07-13 20:01
No worries 😃
