### ISSUE TITLE
amend commit via gui while rebasing fails

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#112166] opened 2020-12-09 15:56 UTC
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (7.55GB free)|
|Process Argv|--crash-reporter-id 3db855c9-13d1-4048-a508-8cf1012da4c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
ng-template|Ang|0.1100.2
spellright|ban|3.0.52
lit-html|bie|1.11.1
scratchpads|bue|0.0.7
find-related|eam|0.9.0
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
vscode-open-in-application|fab|1.0.5
vscode-open-multiple-files|fab|1.3.0
kotlin|fwc|0.2.18
html-slim-scss-css-class-completion|gen|1.7.8
restore-git-branch-tabs|gko|0.4.1
todo-tree|Gru|0.0.190
rest-client|hum|0.24.4
jenkins-pipeline-linter-connector|jan|1.2.0
search-node-modules|jas|1.3.0
svg|joc|1.4.1
escape-regexp|kir|1.0.0
vscode-commitizen|Kni|0.9.3
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-azureappservice|ms-|0.20.0
mssql|ms-|1.9.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.4
vscode-typescript-tslint-plugin|ms-|1.3.0
vsliveshare|ms-|1.0.3303
debugger-for-chrome|msj|4.12.11
htmlescape-vscode-extension|ray|0.0.7
java|red|0.72.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
vscode-quick-scope|ska|0.2.0
reveal|smu|1.2.7
vscode-terminal-here|Tyr|0.2.4
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.26.0
vim|vsc|1.18.4
JasmineSnippets|xab|1.0.1
material-theme|zhu|3.9.11

(1 theme extensions excluded)

</details>

Steps to Reproduce:

1. Start an interactive rebase in git and mark a commit for editing.
2. While the rebase is paused for editing the commit, make a change and attempt to amend the commit via **Commit > Commit All  (Amend)** in the **Source Control** menu.
3. The commit fails with the following error:

```
C:\Users\npalmer\AppData\Local\Programs\Microsoft VS Code\Code.exe: bad option: --wait
error: There was a problem with the editor '"C:\Users\npalmer\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by andersea** [comment] 2020-12-14 19:53
I don't know if it is the same thing I ran into. I did a rebase from my master where I had to resolve a bunch of conflicts. Finally when I had all of them resolved, there were no further files modified or staged, but the UI still showed a commit message. It just wouldn't let me commit. I had to go into the command line and type git commit -m "Some message"

**Comment by eamodio** [comment] 2021-01-06 22:28
Duplicate of https://github.com/microsoft/vscode/issues/113873

**Closed by eamodio** 2021-01-06 22:28 UTC
