### ISSUE TITLE
Replacing `^\n` throws error

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#95497] opened 2020-04-17 06:38 UTC
Attempt to replace `^\n`:
This one doesn't have any problems with single items replacement, or Replace from find widget, but Replace all in Find in files results in error: `Error: Overlapping ranges are not allowed!`

_Originally posted by @IllusionMH in https://github.com/microsoft/vscode/issues/95425#issuecomment-614689672_

/fyi @suchoss

**Comment by roblourens** [comment] 2020-04-18 16:47
Can you share the file/repo where you encountered this issue? I can't reproduce it. And is it possible that your file has some bare CR characters (CR not CRLF), there are some known issues with this.

**Comment by suchoss** [comment] 2020-04-18 17:11
@roblourens Unfortunatelly I can't send repo but here is one of those files:
https://gist.github.com/suchoss/4519fa509ed8c586d526cb91fdc11d2c

1) Just make a file from that gist.
2) Create about 20 copies of it in the same folder.
3) Run this regex replace on all files `^další.*`
4) Run this regex replace on all files `^\n` -> this fails.
5) Optional - if you click fast enough on previous regexp to "replace single" button, then it also deletes lines which are not like `^\n` expression.

**Comment by roblourens** [comment] 2020-04-26 01:45
I can't repro with this sample but is it possible that the file on your disk has some plain `\r` line endings (not `\r\n` or `\n`)?

**Comment by suchoss** [comment] 2020-05-04 14:40
Hi, sorry for the late answer - yes, there is \r\n line ending.

**Comment by suchoss** [comment] 2020-05-04 15:05
Is there a way how to display line-endings in vs code?

I downloaded an extension for that, but from the extension's description I can see following:  
> Visual Studio Code normalizes line endings upon load and thus this extension will only show one kind of line ending character. Currently it is not possible to have multiple different line endings (see issue 127).

It seems that these line-endings shouldn't matter to vs. I do not expect that there will be just `\r`, but is there a way how to find it?

Thanks

**Comment by IllusionMH** [comment] 2020-05-04 19:52
After that couple of times (even with Window Reload) when I saw errors in console, I wasn't able to repro it in different files. I doubt that file might contain `\r` (or it was some left off after few edits/replaces).

@saighost you can run RegExp search for `\r(?!\n)` to ensure that there are no `\r` that was left alone.

**Comment by roblourens** [comment] 2020-05-05 13:47
If you open the file in vscode, edit, and save it, then we would save it with normalized line endings. These only show up when external tools are involved. I'm not sure off the top of my head whether ripgrep would find them in a normal search or whether it would get confused.

**Comment by IllusionMH** [comment] 2020-05-05 13:52
> ripgrep would find them

At least it founds `\r`, `\r\n`, and `\r(?=\n)` in files with CRLF line endings so I think it would catch negative lookahead.

**Comment by suchoss** [comment] 2020-05-05 13:57
Well, then no - line endings were CRLF in all files, because all files were edited several times in vs code before.

**Comment by roblourens** [comment] 2020-05-09 00:06
Which OS are you using?

**Comment by suchoss** [comment] 2020-05-09 06:59
Win 10 (64).
![image](https://user-images.githubusercontent.com/39336141/81466610-50538800-91d3-11ea-8ae3-441135e961d0.png)


I recorded a video what happens. <https://youtu.be/ItwnmGe6h-o>

**Comment by roblourens** [comment] 2020-08-15 00:31
Sorry, I still can't reproduce the original issue, or the issue I see in your video where clicking "replace all" does nothing. But I do see the issue with clicking too fast to replace, and I'll fix that in this issue.

Verification steps

- Set up a search/replace that will produce a bunch of matches in the same file, and where the replacement leaves that range with a different number of lines than originally
- Click on the "replace" buttons on the result rows very quickly
- It should do all the replaces successfully without mangling the editor content

**Comment by roblourens** [comment] 2020-08-15 00:32
Fixed in https://github.com/microsoft/vscode/commit/e0cc8f579f6b911a7eb72dea231ad89dace369b8

**Closed by roblourens** 2020-08-15 00:32 UTC
Labels: bug, search
