### ISSUE TITLE
Menu: drop fade animations when menu is already open

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54158] opened 2018-07-12 10:23 UTC
When using <kbd>LeftArrow</kbd> and <kbd>RightArrow</kbd>, the menus still use a fade animation, so the whole thing looks a bit weird. If a menu is already open and we jump to a sibling menu, it shouldn't use fade animation.

![peek 2018-07-12 12-22](https://user-images.githubusercontent.com/22350/42627792-5c7ef6fe-85ce-11e8-8849-68d59d77f9d5.gif)

**Comment by sbatten** [comment] 2018-07-12 18:19
duplicate of #53808

**Closed by sbatten** 2018-07-12 18:19 UTC

**Comment by joaomoreno** [comment] 2018-07-13 07:48
@sbatten Actually I do like the current approach: fade in, but instant hide. It just doesn't work nicely if you jump between menus.

It is a duplicate if you really remove the animation. Though I'd argue that you should still support the fade-in. My Linux setup, for example, has fade in animations.

**Comment by sbatten** [comment] 2018-07-16 22:38
@joaomoreno Do we have other instances of settings for animations? It seems like settings bloat to me. Matching Linux won't be universal given the number of distros, but if I were to pick one to mimic it would likely be Ubuntu which doesn't have animations for classic style menus (e.g. see terminal)

**Comment by joaomoreno** [comment] 2018-07-17 07:38
We have settings to control the text editor cursor blinking as well as smooth scrolling, both animation related. I think we should have one for this, and I think fade-in should be the default. Animation is useful to turn good UX experiences into great ones, but there will always be people who dislike it and just want a fast experience, hence the setting.

**Comment by sbatten** [comment] 2018-07-17 17:18
I don't disagree that animations can be used to create better UX experiences, but I don't see how the menubar is one of them. Even macOS which is touted for great UX doesn't use a fade-in animation because the speed at which a menu opens is what makes that UX great. (they do use a fade-out animation, but this is counter to your request and I still don't think that adds to the experience) @bpasero do you have an opinion here? I know this is a simple change either way, but I don't like excess settings personally and I think more users would prefer speed to the animation when they aren't even accustomed to it. making them configure another setting for this seems like unnecessary friction. and having the opposite as the default leads me to believe the setting will never be touched because even if you prefer the animation, you aren't going to look for it.

**Comment by joaomoreno** [comment] 2018-07-17 17:31
You have successfully convinced me. :laughing:

**Comment by bpasero** [comment] 2018-07-17 18:32
Not sure, I did not notice the animation as a bad thing the way it is. I can live with or without animation but please do not introduce a setting for this if possible.
