### ISSUE TITLE
Startup takes too long

### ISSUE THREAD

**Issue by mammaknullare** [microsoft/vscode#93379] opened 2020-03-25 11:11 UTC
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-82e9.extHost.cpuprofile.txt`
-`prof-82e9.main.cpuprofile.txt`
-`prof-82e9.renderer.cpuprofile.txt`
[prof-82e9.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4380422/prof-82e9.renderer.cpuprofile.txt)
[prof-82e9.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4380423/prof-82e9.extHost.cpuprofile.txt)
[prof-82e9.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4380424/prof-82e9.main.cpuprofile.txt)

## System Info

* Code: 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50)
* OS: win32(10.0.18362)
* CPUs: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz(8 x 2400)
* Memory(System): 7.85 GB(2.52GB free)
* Memory(Process): 151.55 MB working set(119.24MB private, 0.25MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process          | Info                                      |
| --------------------------------------------------------------- | -------- | ---------------- | ----------------------------------------- |
| start => app.isReady                                            | 85       | [main]           | initial startup: true                     |
| nls:start => nls:end                                            | 1        | [main]           | initial startup: true                     |
| require(main.bundle.js)                                         | 72       | [main]           | initial startup: true                     |
| app.isReady => window.loadUrl()                                 | 149      | [main]           | initial startup: true                     |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 19095    | [main->renderer] | NewWindow                                 |
| require(workbench.desktop.main.js)                              | 582      | [renderer]       | cached data: YES, node_modules took 150ms |
| require & init workspace storage                                | 61       | [renderer]       | -                                         |
| init workspace service                                          | 81       | [renderer]       | -                                         |
| register extensions & spawn extension host                      | 9343     | [renderer]       | -                                         |
| restore viewlet                                                 | 139      | [renderer]       | workbench.view.explorer                   |
| restore panel                                                   | 0        | [renderer]       | -                                         |
| restore editors                                                 | 210      | [renderer]       | 1: PerfviewInput                          |
| overall workbench load                                          | 411      | [renderer]       | -                                         |
| workbench ready                                                 | 20436    | [main->renderer] | -                                         |
| extensions registered                                           | 29924    | [renderer]       | -                                         |

## Extension Activation Stats

| Extension                         | Eager | Load Code | Call Activate | Finish Activate | Event               | By                                |
| --------------------------------- | ----- | --------- | ------------- | --------------- | ------------------- | --------------------------------- |
| vscode.debug-auto-launch          | true  | 6         | 1             | 21              | *                   | vscode.debug-auto-launch          |
| vscode.emmet                      | true  | 16        | 5             | 16              | *                   | vscode.emmet                      |
| vscode.git                        | true  | 36        | 12            | 100             | *                   | vscode.git                        |
| vscode.github-authentication      | true  | 8         | 1             | 79              | *                   | vscode.github-authentication      |
| vscode.merge-conflict             | true  | 10        | 2             | 5               | *                   | vscode.merge-conflict             |
| vscode.search-result              | true  | 4         | 1             | 4               | *                   | vscode.search-result              |
| vscode.vscode-account             | true  | 9         | 0             | 76              | *                   | vscode.vscode-account             |
| vscode.extension-editing          | false | 15        | 1             | 31              | onLanguage:markdown | vscode.extension-editing          |
| vscode.markdown-language-features | false | 44        | 9             | 22              | onLanguage:markdown | vscode.markdown-language-features |

**Comment by jrieken** [comment] 2020-03-26 08:34
/duplicate of https://github.com/microsoft/vscode/issues/56644

**Closed** 2020-03-26 08:34 UTC
Labels: *duplicate, perf-startup
