### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by zaker** [microsoft/vscode#101835] opened 2020-07-07 06:56 UTC
We have written the needed data into your clipboard because it was too large to send. Pl
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.4
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99888:161)
    at resolveModuleNamesWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100106:26)
    at resolveModuleNamesReusingOldState (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100255:19)
    at processImportedModules (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101668:35)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101411:17)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101638:21
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101633:16)
    at findSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101408:21)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:85
    at getSourceFileFromReferenceWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101207:34)
    at processSourceFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101240:13)
    at processRootFile (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101063:13)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:60
    at Object.forEach (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99987:16)
    at synchronizeHostData (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138726:26)
    at Object.getProgram (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138818:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143310:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143253:42)
    at ConfiguredProject.updateGraph (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144047:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145700:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146581:44)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:97
    at Object.flatMap (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146900:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147763:46)
    at c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149517:28)
    at IOSession.Session.executeCommand (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149526:33)
    at IOSession.Session.onMessage (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149550:35)
    at Interface.<anonymous> (c:\Users\snaust\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19592

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (8.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
pgformatter|bra|1.14.0
better-toml|bun|0.3.2
cmake-format|che|0.6.10
vscode-postgres|cko|1.1.11
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.1
inception|dav|0.0.2
vscode-eslint|dba|2.1.6
vscode-deno|den|1.25.0
factor|dex|0.3.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
elm-ls-vscode|elm|1.1.1
dotnet-test-explorer|for|0.7.3
vscode-pull-request-github|Git|0.17.0
go|gol|0.15.0
vscode-versionlens|Hof|0.25.6
beautify|Hoo|1.5.0
reg|ion|1.0.1
chat|kar|0.35.0
go-prof|Max|0.0.4
rainbow-csv|mec|1.7.0
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.6.1
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
proto|pet|0.0.2
goasm|qui|0.0.4
logstash|Ran|0.0.4
vscode-yaml|red|0.8.0
rust|rus|0.7.8
vscode-coverage-gutters|rya|2.5.1
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
pegs|the|0.0.5
zig|tie|0.2.4
mako|tom|0.2.0
clang-format|xav|1.9.0
go-mod-grapher|xmt|1.1.1
vscode-proto3|zxh|0.4.2

</details>
ease paste.

**Comment by mjbvz** [comment] 2020-07-07 20:19
Caused by the deno extension. 

Duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-07-07 20:19 UTC
