### ISSUE TITLE
Feature Req: https://github.com/microsoft/vscode/issues/172214

### ISSUE THREAD

**Issue by the-moog** [microsoft/vscode#173420] opened 2023-02-04 11:15 UTC
I reference the issue https://github.com/microsoft/vscode/issues/172214 which was closed - even though I was trying out a suggestion.

I think my suggestion is still valid, as the proposed solution does not meet the requirements. Further windows get the same colour even if you are on an entirely different systems.  This is because profiles follow the user not the repo.

Please either re-open [172214](https://github.com/microsoft/vscode/issues/172214) or copy paste.

**Comment by DonJayamanne** [comment] 2023-02-04 22:58
Duplicate of https://github.com/microsoft/vscode/issues/172214

**Closed by DonJayamanne** 2023-02-04 22:58 UTC
Labels: triage-needed

**Comment by DonJayamanne** [comment] 2023-02-09 22:36
@the-moog sorry for that, i have re-opened that issue.
