### ISSUE TITLE
C++ Template Function Highlighting

### ISSUE THREAD

**Issue by nick-prat** [Microsoft/vscode#50912] opened 2018-06-01 00:42 UTC
Template functions that are manually type specified are highlighted in a different way then regular functions.

- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04 x86 4.15.0-22-generic

Steps to Reproduce:

1. Type code in picture into editor

![vscode_function_template](https://user-images.githubusercontent.com/19151224/40815190-7a54fd04-64f9-11e8-94ab-fbbfa9b30a91.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-06-01 18:19
Please share code as text

**Comment by nick-prat** [comment] 2018-06-02 00:52
```
class C {
public:
    template<typename T>
    T func(T param) {
        return param;
    }
};

template<typename T>
void func1() {

}

void func2() {

}

int main() {
    C c;
    c.func<int>(10);
    c.func(10);

    func1<int>();
    func2();
}
```

**Comment by mjbvz** [comment] 2018-06-04 17:32
Thanks. 

Duplicate of https://github.com/atom/language-c/issues/215

**Closed by mjbvz** 2018-06-04 17:32 UTC
Labels: needs more info
