### ISSUE TITLE
Debug Console errors cover open file tabs

### ISSUE THREAD

**Issue by CTimmerman** [Microsoft/vscode#32175] opened 2017-08-09 07:59 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.15.2
riot-tag|cri|0.1.7
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.3.3
tslint|eg2|0.17.0
prettier-vscode|esb|0.22.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
referenceshelper|gay|0.1.3
emoji-code|idl|0.2.0
Lisp|mat|0.1.7
language-stylus|sys|1.7.3
jadeview|viv|1.0.0
JavaScriptSnippets|xab|1.4.1
maple|yjt|1.1.6

(8 theme extensions excluded)

---

Steps to Reproduce:

1. Press F5 while having the Debug Console focused instead of the open file.
2. Notice vague error popup that's hiding the open file tabs instead of staying in the context of the Debug Console. See annotated screenshot: 
![vscdebugconsolepopuplocation](https://user-images.githubusercontent.com/9662163/29111145-72797f04-7ce9-11e7-9c08-12535c8ccef3.png)

Reproduces without extensions: Yes

**Comment by weinand** [comment] 2017-08-09 08:55
Since there is only a single error notification mechanism, errors are shown in a singe place.
So this issue is a duplicate of #32136

**Closed by weinand** 2017-08-09 08:55 UTC
Labels: debug

**Comment by CTimmerman** [comment] 2017-08-09 10:06
Technically this bug is about moving them so they don't cover important information, but tucking them away for later reading like Windows and MacOS do with theirs is neater.

**Comment by weinand** [comment] 2017-08-09 10:08
@CTimmerman I suggest to comment on the original issue and not on this closed issue.
