### ISSUE TITLE
Keyboard not working after Code install on Ubuntu 16.   PageUp/Down Line Up/Down Left/Right (and others) not working.  Going back to 1.10.2, keyboard works again.

### ISSUE THREAD

**Issue by skvenkatesh** [Microsoft/vscode#24296] opened 2017-04-08 04:39 UTC
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-65-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|swagger-viewer|Arjun|1.4.0|
|vscode-markdownlint|DavidAnson|0.7.1|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|plantuml|jebbs|1.4.0|
|Go|lukehoban|0.6.59|
|debugger-for-chrome|msjsdiag|2.7.3|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|Spell|seanmcbreen|0.9.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.Install 1.11.1 code (sudo dpkg -i code_1.11.1-1491486998_amd64.deb)
2. Update pkgs (sudo apt-get install -f)
3. Launch code
4. Observe navigations keys (PC keyboard) not working.
5. Go back to 1.10.2 code (sudo dpkg -i code_1.10.2-1488981323_amd64)
6. Update pkgs again (sudo apt-get install -f)
7. Observe navigation keys (PC keyboard) working fine.

**Comment by chrmarti** [comment] 2017-04-08 04:43
Which keyboard layout are you using?

**Comment by skvenkatesh** [comment] 2017-04-08 14:52
I use local Dell PC laptop to connect to my development Ubuntu VM (Linux ubuntu1604 4.4.0-65-generic) via X2Go where I have vscode installed.

Navigation keys (up/down/left/right pageUp/PageDown/Home/End/Insert/Delete....) keys on PC laptop do not work after vscode upgrade to 1.11.1, whereas they have been working so far on all vscode since last 6 months with the same setup.  I have gone back to vscode 1.10.2 code and and using it without any issues.

**Comment by skvenkatesh** [comment] 2017-04-08 15:09
Layout: US
As per Windows 10 device manager, Keyboard devices (HID Keyboard device and Standard PS/2 Keyboard) are working fine

**Comment by alexandrudima** [comment] 2017-04-10 08:29
Duplicate of #24107

Workaround detailed in https://github.com/Microsoft/vscode/issues/24107#issuecomment-292325492

**Closed by alexandrudima** 2017-04-10 08:29 UTC

**Comment by skvenkatesh** [comment] 2017-04-14 13:52
Updated to code_1.11.2-1492070517_amd64.deb  and this seems to be working fine without needing any workaround.  Thanks!
