### ISSUE TITLE
Terminal Sticky Scroll flickers

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#199400] opened 2023-11-28 17:43 UTC
Testing #199240

Just a small UI thing I noticed (much more noticeable on larger terminal commands). Not sure if this is something with rendering that you can fix though - other than this and the existing issues noted, it looks good!

![Recording 2023-11-28 at 09 42 20](https://github.com/microsoft/vscode/assets/54879025/32f8e151-9df9-4ac5-8607-a43d33113ece)

**Comment by joyceerhl** [comment] 2023-12-15 00:09
Duplicate of https://github.com/microsoft/vscode/issues/198446

**Closed by joyceerhl** 2023-12-15 00:09 UTC
Labels: bug, terminal-sticky-scroll
