### ISSUE TITLE
Allow user to customize VSCode UI by loading specific CSS style file.

### ISSUE THREAD

**Issue by x-strong** [microsoft/vscode#147065] opened 2022-04-08 07:53 UTC
**Allow user to customize VSCode UI by overriding the CSS, namely that allow we specifiy a CSS file to load on VSCode startup.**
Now what I can do is to modify the workbench.desktop.main.css file under the folder "xxx\Microsoft VS Code\resources\app\out\vs\workbench", but I get a warning every time when VSCode  loaded. 
```css
.tab.active {
    text-shadow: 1px 1px 10px white;
    background-color: #ffffff26 !important;
    font-weight: bold;
    filter: brightness(2.5);
}
```
![image](https://user-images.githubusercontent.com/3232261/162390073-a5f8c3c8-de7f-4697-88d7-e1edbe2a21f7.png)

![image](https://user-images.githubusercontent.com/3232261/162387854-6155bfd7-ec01-4635-bbb0-ca570ad7479d.png)

So if we can specify a customized CSS file in Settings for VSCode to load on starting up, the problem is solved. 
That would be a great feature, big convenience and flexibility.

**Comment by IllusionMH** [comment] 2022-04-08 08:51
See related https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312

There are extensions that allows that, but use them at your own risk

**Comment by x-strong** [comment] 2022-04-08 10:09
> See related [#40764 (comment)](https://github.com/microsoft/vscode/pull/40764#issuecomment-355011312)
> 
> There are extensions that allows that, but use them at your own risk

**But users already use [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) and it's worse because it requires reload every update, admin rights and corrupts install.**

**Conduct some kind of vote if users wishing to have this Feature agree not to complain about changing CSS names and close all issues about changed naming as dupliates with reference to that vote.**

**Make something similar with --disable-extensions: --disable-custom-css**

**You can't make 10n configs to change every minor CSS setting.**
**It doesn't even have to be a permanent solution: users will change CSS and wait for the implementation of some feature in the core editor.**

**Comment by x-strong** [comment] 2022-04-08 10:16
This kind of feature requests will not stop and more and more FRs will be created until some day VSCode provide something like this, believe me! : )

**Comment by IllusionMH** [comment] 2022-04-08 10:32
> But users already use [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) and it's worse because it requires reload every update, admin rights and corrupts install.

That's what I was referring to in my comment.

> ...users ... agree not to complain about changing CSS names ...

This never works. Ideally users should report here only VS Code editor issues, yet there is ton of issues that are extension specific.

> ... and close all issues about changed naming as dupliates with reference to that vote.

This will waste devs time/attention after each update where it's important to see actual problems after release.

My bet is that issues will be more often then feature requests, but I'm not a team member so not my decision for sure.

**Comment by x-strong** [comment] 2022-04-08 10:50
> ..., but I'm not a team member so not my decision for sure.

What a pity! :(

**Comment by aeschli** [comment] 2022-04-08 12:56
Closing as duplicate of #40764. We want to control how VS Code can be extended.  This is done through documented APIs that we keep stable across versions so that extensions don't get broken.
The DOM and the related CSS change as we develop the user interface, and the freedom of doing that is crucial for the future of VS Code.

**Closed by aeschli** 2022-04-08 12:56 UTC
