### ISSUE TITLE
Custom File/Folder Ordering

### ISSUE THREAD

**Issue by AzuStar** [microsoft/vscode#148520] opened 2022-05-01 18:42 UTC
Nothing even remotely similar found.

I'd like to propose custom ordering for explorer. Personally, I am getting lost quite fast within my workspace when it's starting to look something like this. Those lines almost blur together in a sense. 
![image](https://user-images.githubusercontent.com/52426335/166159637-884df36d-6353-49de-b908-c7afc3d5679a.png)

What I'd like to propose, what Blizzard has achieved, not to underestimate it, perfectly in Warcraft 3 World Editor's Trigger Editor, is completely custom file and folder order.
![image](https://user-images.githubusercontent.com/52426335/166159675-2ea57f55-e4a4-4916-adeb-54565e18ac67.png)
![image](https://user-images.githubusercontent.com/52426335/166159696-430529cc-0ff9-4d88-b6ce-52bca47f22fe.png)

The order in which files and folders show up in the order in which the user put them. That straight up lets user know where he put his stuff, even if it makes subfolder strategy a bit obsolete and makes the list of folders/files long, it still helps bring custom order to the workspace in which you know what is where.

Comments would also be nice, but this sounds like another feature.

Ordering of files/folders could be mapped through a helper file that is located in .vs folder for source control.

**Comment by JacksonKearl** [comment] 2022-05-03 16:43
Duplicate of #145414.

**Closed by JacksonKearl** 2022-05-03 16:43 UTC
