### ISSUE TITLE
Re-opening VSCode Incorrect Integrated Terminal

### ISSUE THREAD

**Issue by AJDowds** [microsoft/vscode#132923] opened 2021-09-11 18:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: Microsoft Windows 10 Home

Steps to Reproduce:

1. Open VSCode and open a Git Bash integrated terminal
2. Close VSCode with the terminal still open
3. Re-open VSCode and see that the terminal has now switched to PowerShell

I have set my default terminal to Git Bash and have even removed Powershell from the options listed using the following:

```js
  "terminal.integrated.profiles.windows": {
    "Git Bash": {
      "source": "Git Bash"
    },
    "PowerShell": null
  },
```

If I open a new integrated terminal, I do indeed get a Git Bash terminal but if I close VSCode and re-open it, it's back to being PowerShell. I have to close the terminal and re-open it to get back to Git Bash.

**Comment by IllusionMH** [comment] 2021-09-11 18:51
/duplicate of #132150

Already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Closed** 2021-09-11 18:51 UTC
Labels: *duplicate
