### ISSUE TITLE
 Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#47547] opened 2018-04-10 05:49 UTC
Issue Id: <b>db042bd6-3045-c94d-e9f1-0cfc44554b41</b><br /><br />*Versions* <br />- 1.22.1<br />-  6b4d53cdab8bcae1eaaa4934d93c077319b573db<br />*Stack* <br />TypeError: Cannot read property 'id' of undefined<br />[/vs/platform/extensionManagement/common/extensionManagementUtil.ts#25:113 (getGalleryExtensionIdFromLocal)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L25:113 (getGalleryExtensionIdFromLocal))<br />[/vs/platform/extensionManagement/common/extensionEnablementService.ts#148:15 (_getIdentifier)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/platform/extensionManagement/common/extensionEnablementService.ts#L148:15 (_getIdentifier))<br />[/vs/platform/extensionManagement/common/extensionEnablementService.ts#64:26 (getEnablementState)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/platform/extensionManagement/common/extensionEnablementService.ts#L64:26 (getEnablementState))<br />[/vs/platform/extensionManagement/common/extensionEnablementService.ts#127:31 (isEnabled)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/platform/extensionManagement/common/extensionEnablementService.ts#L127:31 (isEnabled))<br />[/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#47:51](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#L47:51)<br />    at Array.filter (native)<br />[/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#47:5 (onComplete)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/workbench/parts/preferences/electron-browser/preferencesSearch.ts#L47:5 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0 (_run)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1083:0 (_run))<br />[/vs/base/common/winjs.base.js#1051:0 (onComplete)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1051:0 (onComplete))<br />[/vs/base/common/winjs.base.js#1185:0 (_notify)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1185:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1083:0](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/src/vs/base/common/winjs.base.js#L1083:0)<br />    at<br />

**Comment by sandy081** [comment] 2018-04-17 09:27
Duplicate of #47550

**Closed** 2018-04-17 09:27 UTC
Labels: *duplicate, error-telemetry
