### ISSUE TITLE
Format Document option is broken in 1.14.1.

### ISSUE THREAD

**Issue by dbagga** [Microsoft/vscode#30667] opened 2017-07-14 05:33 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jshint|dba|0.10.15
backbone-js-snippets|ioa|0.0.1
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Make a new file, write some code in javascript in unformatted manner.
2. Use shortcut keys to 'option + shift + F' not working, even format document option missing in context menu.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-07-14 18:05
It's odd that you don't even see the format option in the context menu. To investigate:

1. What is the language mode of the document? This is shown in the lower right corner in the status bar
2. Does this reproduce if you disable all extensions?
3. Open the output panel and check the `TypeScript` section. Do you see any error messages?
4. Run the `Toggle Developer Tools` command and open the developer console. Do you see any error messages here?

**Comment by dbagga** [comment] 2017-07-17 04:43
Hi,


1) Javascript.

2) Yes, still reproducible without extensions.

3) No errors.

4) 3 errors - Activating extension `vscode.typescript` failed: [vscode.typescript]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.typescript.

In previous version everything works fine. After updating to 1.14.1, i am getting this problem.


Thanks,

Dinesh

________________________________

**Comment by mjbvz** [comment] 2017-07-19 20:27
Thanks. This is a duplicate of #30716

It should already be fixed in insiders and we are working on a fix for 1.14.2

**Closed by mjbvz** 2017-07-19 20:27 UTC
Labels: duplicate, javascript, new release
