### ISSUE TITLE
<semantic> TypeScript Server Error (4.5.5) Debug Failure. False expression. Error: Debug Failure. False expression. at

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#144093] opened 2022-02-28 13:45 UTC
Stack
Error: <semantic> TypeScript Server Error (4.5.5) Debug Failure. False expression. Error: Debug Failure. False expression.
at getCompletionEntryCodeActionsAndSourceDisplay (/extensions/node_modules/typescript/lib/tsserver.js:129174:22)
at Object.getCompletionEntryDetails (/extensions/node_modules/typescript/lib/tsserver.js:129117:30)
at Proxy.getCompletionEntryDetails (/extensions/node_modules/typescript/lib/tsserver.js:160082:35)
at <anonymous> (/extensions/node_modules/typescript/lib/tsserver.js:171577:57)
at Object.mapDefined (/extensions/node_modules/typescript/lib/tsserver.js:619:30)
at IOSession.Session.getCompletionEntryDetails (/extensions/node_modules/typescript/lib/tsserver.js:171575:33)
at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/extensions/node_modules/typescript/lib/tsserver.js:170400:61)
at <anonymous> (/extensions/node_modules/typescript/lib/tsserver.js:172195:88)
at IOSession.Session.executeWithRequestId (/extensions/node_modules/typescript/lib/tsserver.js:172186:28)
at IOSession.Session.executeCommand (/extensions/node_modules/typescript/lib/tsserver.js:172195:33)
at IOSession.Session.onMessage (/extensions/node_modules/typescript/lib/tsserver.js:172221:35)
at Interface.<anonymous> (/extensions/node_modules/typescript/lib/tsserver.js:174826:31)
at Interface.emit (events.js:315:20)
at Interface._onLine (readline.js:337:10)
at Interface._normalWrite (readline.js:482:12)
at Socket.ondata (readline.js:194:10)
at Socket.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) at u._executeContributedCommand (/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:30418) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by mjbvz** [comment] 2022-02-28 19:29
Duplicate of https://github.com/microsoft/TypeScript/issues/45637

**Closed by mjbvz** 2022-02-28 19:29 UTC
Labels: error-telemetry
