### ISSUE TITLE
Automatic Language Detection (1.60) overwrites vscode.languages.setTextDocumentLanguage()

### ISSUE THREAD

**Issue by AdrianG-OSS** [microsoft/vscode#132629] opened 2021-09-08 08:43 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Win 10

Hi

I am developing an extension that uses _untitled_ files as a means of displaying special temporary text data (that the user can chose to later save to the disk or just discard). I'm using vscode.languages.setTextDocumentLanguage() method to manually assign a language id to the file so as to be able to provide coloring + smart editing features to this file (I have a language server that is assigned to this language id). However, with VScode 1.60 the newly introduced Automatic Language Detection overwrites the assigned language id with something that is not even remotely correct. 

This behavior appears to happen only for files longer that 35-40 lines.

I think Automatic Language Detection should respect a previously set language id.

**Comment by infinnie** [comment] 2021-09-08 08:50
Duplicate of #132173

**Closed** 2021-09-08 12:57 UTC
Labels: *duplicate
