### ISSUE TITLE
I hope to invoke addExtraLib method in vscode extension

### ISSUE THREAD

**Issue by xiaobindebingo** [microsoft/vscode#140070] opened 2022-01-04 02:49 UTC
please Add typescript types lib for code hint in vscode extension, I hope to invoke addExtraLib method in vscode extension; like monaco editor:

```
monaco.languages.typescript.typescriptDefaults.addExtraLib()
```
detail: [https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults)

**Comment by mjbvz** [comment] 2022-01-04 20:04
Duplicate of #139923 

Please follow up on the original issue instead of posting a duplicate

**Closed by mjbvz** 2022-01-04 20:04 UTC
