### ISSUE TITLE
Ability to listen for command events in the extensions API: `onCommand(...)`

### ISSUE THREAD

**Issue by jonburger** [Microsoft/vscode#12262] opened 2016-09-19 10:51 UTC
When creating an extension the author can activate it by listening for a specific command event, however this is the only time when an extension can seemingly respond to a command.

It would be very useful to have an `onCommand(...)` type listener option.

My use case was creating an status bar extension that could watch for build tasks `workbench.action.tasks.build`, and then also listen for `workbench.action.tasks.terminate` to be able to show an icon to illustrate the watching task, and provide and option for terminating it through the UI.

However I believe this functionality would be very useful to other extensions, as would an API for checking running task statuses etc. but that's a separate issue.

**Comment by jrieken** [comment] 2016-09-23 13:19
dupe of #1431

**Comment by jrieken** [comment] 2016-09-23 13:19
@chrmarti please assign feature requests

**Closed by jrieken** 2016-09-23 13:19 UTC
Labels: api, feature-request
