### ISSUE TITLE
[Feature Request] feature to update vscode internally

### ISSUE THREAD

**Issue by bardiainjast** [Microsoft/vscode#36463] opened 2017-10-18 06:37 UTC
it would be great if we could have update vscode without every time downloading and installing it again and again, maybe through using some gui or even option for automatic update, this is awesome because specially now days minor updates are coming in short periods of time.

**Comment by mjbvz** [comment] 2017-10-18 07:43
@bardiainjast Which operating system are you using?

Updates should be downloaded automatically but you still have to click on the update button to install them. Silent updates are tracked by #9539

**Comment by bardiainjast** [comment] 2017-10-18 07:45
@mjbvz i'm using ubuntu 17.04

**Comment by joaomoreno** [comment] 2017-10-18 09:18
@bardiainjast Do you use our deb packages?

**Comment by bardiainjast** [comment] 2017-10-18 09:20
@joaomoreno yes, i download the deb file every time you release a new version

**Comment by joaomoreno** [comment] 2017-10-18 09:33
We publish to our deb repository everytime we release so you should get the updates via your system updater. Right, @Tyriar?

**Comment by Tyriar** [comment] 2017-10-21 16:43
Yes updates should come automatically, I think what @bardiainjast is after is an auto updater similar to browsers these days which provide an experience closer to our current macOS flow; the update is downloaded and applied on next restart.

Good news is that we've invested some time recently in snap packages and that is likely the direction we will go, eventually this is the sort of behavior we should be able to achieve with snap packages. So I'll close this as a duplicate of https://github.com/Microsoft/vscode/issues/5458

---

Also in the meantime you might want to set up a script something like this:

alias up='sudo apt update && sudo apt install code'

This allows you to just run the command `up` when you start and the update will be pulled and installed if available.

**Closed by Tyriar** 2017-10-21 16:43 UTC
Labels: install-update
