### ISSUE TITLE
Delete a file from sidebar,the file cannot be opened again.

### ISSUE THREAD

**Issue by pandaiiz** [Microsoft/vscode#33717] opened 2017-09-02 01:54 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
jquery-snippets|Hri|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Delete a file from sidebar
![image](https://user-images.githubusercontent.com/25072780/29992002-36f3278a-8fc4-11e7-8b6e-ee17c831394d.png)
2.Then open this file again.
![image](https://user-images.githubusercontent.com/25072780/29992024-96843a22-8fc4-11e7-93e6-b5ef7385be60.png)
3.This file cannot be opened,there is nothing exhibit.
![image](https://user-images.githubusercontent.com/25072780/29992006-491be44c-8fc4-11e7-94b3-c534c85ac6ee.png)

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment] 2017-09-02 07:14
Duplicate of #32962

`Remove from Side Bar` means "remove this panel from the view", so it will hide the file list, not "close your folder".

When you open the folder again, it's actually opened, but you cannot see the file list.

To get it back, open your folder, right-click on the title of the view (Explorer for this case), and check `Folders`.

**Closed** 2017-09-04 17:40 UTC
Labels: new release, workbench
