### ISSUE TITLE
Python interactive window not working

### ISSUE THREAD

**Issue by PrateekArya** [microsoft/vscode#100865] opened 2020-06-23 16:18 UTC
Issue Type: <b>Bug</b>

Python interactive stopped working just after updating to the current insider build. 
Disabled all other extensions except for python, updated python extension, reset all python extension settings to default, restarted my computer, etc. Nothing seems to be working. Its stuck at "Executing Cell" status and the "Python Interactive" window frame is completely blank.

Steps to reproduce:
1. Open any .py file with "#%%" for marking cells.
2. Execute any cell. 

![image](https://user-images.githubusercontent.com/1255663/85427584-3c45c900-b57c-11ea-949a-07b1ce8b7757.png)

![image](https://user-images.githubusercontent.com/1255663/85427608-449e0400-b57c-11ea-9d94-1f6a4ff38957.png)

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (55.76GB free)|
|Process Argv|D:\OneDrive - NTNU\0.3. Codes & Workspaces\4. SSW DTU\SLy-CalmW|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.89046-dev

</details>

**Comment by mjbvz** [comment] 2020-06-24 00:17
Duplicate of https://github.com/microsoft/vscode/issues/100879

**Closed by mjbvz** 2020-06-24 00:17 UTC
