### ISSUE TITLE
Seeing two SCM viewlets

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#142087] opened 2022-02-03 15:30 UTC
Returned to my machine and saw this... No user that I remember, maybe settings sync related but nothing special in the logs (last UI state change below). The first SCM viewlet is "normal", the second full of gitlens views which I all had manually hidden

<img width="455" alt="Screen Shot 2022-02-03 at 16 25 13" src="https://user-images.githubusercontent.com/1794099/152373365-19633055-7c23-411b-a7f2-b4203a5d403f.png">

```
// OLD
		"workbench.panel.pinnedPanels": {
			"version": 1,
			"value": "[{\"id\":\"workbench.panel.markers\",\"name\":\"Problems\",\"pinned\":true,\"order\":0,\"visible\":true},{\"id\":\"workbench.panel.output\",\"name\":\"Output\",\"pinned\":true,\"order\":1,\"visible\":true},{\"id\":\"workbench.panel.repl\",\"name\":\"Debug Console\",\"pinned\":true,\"order\":2,\"visible\":false},{\"id\":\"terminal\",\"name\":\"Terminal\",\"pinned\":true,\"order\":3,\"visible\":true},{\"id\":\"refactorPreview\",\"name\":\"Refactor Preview\",\"pinned\":true,\"visible\":false},{\"id\":\"workbench.views.service.panel.637c4d4e-c071-47ff-996f-38cd4dce5db4\",\"name\":\"Timeline\",\"pinned\":true,\"visible\":true}]"
		},


// NEW
		"workbench.panel.pinnedPanels": {
			"version": 1,
			"value": "[{\"id\":\"workbench.panel.markers\",\"name\":\"Problems\",\"pinned\":true,\"order\":0,\"visible\":true},{\"id\":\"workbench.panel.output\",\"name\":\"Output\",\"pinned\":true,\"order\":1,\"visible\":true},{\"id\":\"workbench.panel.repl\",\"name\":\"Debug Console\",\"pinned\":true,\"order\":2,\"visible\":true},{\"id\":\"terminal\",\"name\":\"Terminal\",\"pinned\":true,\"order\":3,\"visible\":true},{\"id\":\"refactorPreview\",\"name\":\"Refactor Preview\",\"pinned\":true,\"visible\":false},{\"id\":\"workbench.views.service.panel.637c4d4e-c071-47ff-996f-38cd4dce5db4\",\"name\":\"Timeline\",\"pinned\":true,\"visible\":true}]"
		},
```

**Comment by sandy081** [comment] 2022-02-04 10:26
The corresponding state is `workbench.activity.pinnedViewlets2` - Any changes for this key?

**Comment by jrieken** [comment] 2022-02-04 11:18
Yes, send the @sbatten directly.. Here they are

BEFORE 

```
"workbench.activity.pinnedViewlets2": {
			"version": 1,
			"value": "[{\"id\":\"workbench.view.explorer\",\"pinned\":true,\"visible\":true,\"order\":0},{\"id\":\"workbench.views.service.sidebar.2ca16687-89c2-48d0-8f69-9a7f5d6689a8\",\"pinned\":true,\"visible\":true},{\"id\":\"workbench.view.search\",\"pinned\":true,\"visible\":true,\"order\":1},{\"id\":\"workbench.view.scm\",\"pinned\":true,\"visible\":false,\"order\":2},{\"id\":\"workbench.view.debug\",\"pinned\":true,\"visible\":true,\"order\":3},{\"id\":\"workbench.panel.terminal\",\"pinned\":false,\"visible\":false,\"order\":3},{\"id\":\"workbench.view.extensions\",\"pinned\":false,\"visible\":true,\"order\":4},{\"id\":\"workbench.view.remote\",\"pinned\":false,\"visible\":true,\"order\":4},{\"id\":\"workbench.view.testing\",\"pinned\":true,\"visible\":false,\"order\":5},{\"id\":\"workbench.view.extension.test\",\"pinned\":false,\"visible\":false,\"order\":6},{\"id\":\"workbench.view.extension.references-view\",\"pinned\":true,\"visible\":false,\"order\":7},{\"id\":\"workbench.view.extension.ts-playground\",\"pinned\":true,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.github-pull-requests\",\"pinned\":false,\"visible\":true,\"order\":8},{\"id\":\"workbench.view.extension.github-pull-request\",\"pinned\":true,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.hexExplorer\",\"pinned\":true,\"visible\":false,\"order\":10},{\"id\":\"workbench.view.extension.copilot-sidebar-webview\",\"pinned\":true,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.objectExplorer\",\"pinned\":true,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.jupyter\",\"pinned\":true,\"visible\":false,\"order\":10},{\"id\":\"workbench.view.extension.kubernetesView\",\"pinned\":true,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.todo\",\"pinned\":true,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.CppRenameActivityBar\",\"pinned\":true,\"visible\":false,\"order\":11},{\"id\":\"workbench.view.extension.cspell-explorer\",\"pinned\":true,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.opensshremotesexplorer\",\"pinned\":false,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.gitlens\",\"pinned\":false,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.PowerShellCommandExplorer\",\"pinned\":false,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.dockerView\",\"pinned\":false,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.azure\",\"pinned\":false,\"visible\":false,\"order\":11},{\"id\":\"workbench.view.extension.liveshare\",\"pinned\":false,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.sync\",\"pinned\":false,\"visible\":false}]"
		},
```

AFTER 

```
"workbench.activity.pinnedViewlets2": {
			"version": 1,
			"value": "[{\"id\":\"workbench.view.explorer\",\"pinned\":true,\"visible\":true,\"order\":0},{\"id\":\"workbench.views.service.sidebar.2ca16687-89c2-48d0-8f69-9a7f5d6689a8\",\"pinned\":true,\"visible\":true},{\"id\":\"workbench.view.search\",\"pinned\":true,\"visible\":true,\"order\":1},{\"id\":\"workbench.view.scm\",\"pinned\":true,\"visible\":true,\"order\":2},{\"id\":\"workbench.view.debug\",\"pinned\":true,\"visible\":true,\"order\":3},{\"id\":\"workbench.panel.terminal\",\"pinned\":false,\"visible\":false,\"order\":3},{\"id\":\"workbench.view.extensions\",\"pinned\":false,\"visible\":true,\"order\":4},{\"id\":\"workbench.view.remote\",\"pinned\":false,\"visible\":true,\"order\":4},{\"id\":\"workbench.view.testing\",\"pinned\":true,\"visible\":false,\"order\":5},{\"id\":\"workbench.view.extension.test\",\"pinned\":false,\"visible\":true,\"order\":6},{\"id\":\"workbench.view.extension.references-view\",\"pinned\":true,\"visible\":true,\"order\":7},{\"id\":\"workbench.view.extension.ts-playground\",\"pinned\":true,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.github-pull-requests\",\"pinned\":false,\"visible\":true,\"order\":9},{\"id\":\"workbench.view.extension.github-pull-request\",\"pinned\":true,\"visible\":false,\"order\":10},{\"id\":\"workbench.view.extension.hexExplorer\",\"pinned\":true,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.copilot-sidebar-webview\",\"pinned\":true,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.objectExplorer\",\"pinned\":true,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.jupyter\",\"pinned\":true,\"visible\":false,\"order\":10},{\"id\":\"workbench.view.extension.kubernetesView\",\"pinned\":true,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.todo\",\"pinned\":true,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.CppRenameActivityBar\",\"pinned\":true,\"visible\":false,\"order\":11},{\"id\":\"workbench.view.extension.cspell-explorer\",\"pinned\":true,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.opensshremotesexplorer\",\"pinned\":false,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.gitlens\",\"pinned\":false,\"visible\":false,\"order\":8},{\"id\":\"workbench.view.extension.PowerShellCommandExplorer\",\"pinned\":false,\"visible\":false,\"order\":12},{\"id\":\"workbench.view.extension.dockerView\",\"pinned\":false,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.extension.azure\",\"pinned\":false,\"visible\":true,\"order\":11},{\"id\":\"workbench.view.extension.liveshare\",\"pinned\":false,\"visible\":false,\"order\":9},{\"id\":\"workbench.view.sync\",\"pinned\":false,\"visible\":false}]"
		},
```

**Comment by sandy081** [comment] 2022-02-22 09:13
I just compared the above states and I don't see any duplicates except that some view containers are made visible and scm viewlet is one whose visibility has changed to true.

@sbatten it seems views code might be enabling the same view container twice?

**Comment by sbatten** [comment] 2022-02-22 15:43
I saw 2 or 3 reports of this all with gitlens before releasing to stable. I'm of the mind that there may have been some issue with gitlens registeration at some point. After releasing to stable, I got no additional reports. So, without a clear repro, with the fact that the state is sane and recoverable, I am going to close this for now.

**Comment by jrieken** [comment] 2022-03-09 15:09
Still this or related behaviours

* setup new machine, install gitless, hide all its views, enable settings-sync
* setup new browser (private mode)
* 🐛 gitless view come back
* :bug: browser (only browser) shows repo picker in explorer (1st screen shot)
* :bug: hiding views in one machine syncs the state but doesn't update the UI (2nd screen shot)

<img width="459" alt="Screenshot 2022-03-09 at 15 55 54" src="https://user-images.githubusercontent.com/1794099/157469590-dcb337b0-55fe-46c7-8253-7ea6ef3ba313.png">

<img width="597" alt="Screenshot 2022-03-09 at 15 55 41" src="https://user-images.githubusercontent.com/1794099/157469610-a9a1d3f8-9bd1-4c8f-8401-0e08aaca9492.png">

**Comment by sandy081** [comment] 2022-03-09 15:28
Thanks for the repro @jrieken, will investigate

**Comment by joaomoreno** [comment] 2022-03-10 13:35
Similar? https://github.com/microsoft/vscode/issues/143625

**Comment by sandy081** [comment] 2022-03-10 18:52
Not similar. This has a different root cause and repro steps. Only similarity is that Settings Sync will help in reproducing this bug.

BTW I could repro both issues and understood the root causes, will be fixing them.

**Closed** 2022-03-11 21:08 UTC
Labels: bug, workbench-views
