### ISSUE TITLE
drag and drop folder to terminal no longer works

### ISSUE THREAD

**Issue by gregbenz** [microsoft/vscode#117459] opened 2021-02-23 19:30 UTC
Issue Type: <b>Bug</b>

In the past, you could drag a file/folder from the Explorer to the Terminal to get the path and it would work.

Now, the path is enclosed with a single quote on either end, which causes it to fail in bash. You end up having to delete the quotes, which is cumbersome since it is used so frequently.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 18.7.0

<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by meganrogge** [comment] 2021-02-25 04:39
Duplicate of #116583

**Closed** 2021-02-25 04:39 UTC
Labels: *duplicate
