### ISSUE TITLE
[FR] Allow extensions to show images inline

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode#97953] opened 2020-05-15 22:49 UTC
Per this [question](https://stackoverflow.com/questions/52709966/vscode-is-it-possible-to-show-an-image-inside-a-text-buffer), it's not possible to make a vscode extension that adds inline preview for images to markdown files, like this:
![image](https://user-images.githubusercontent.com/36224762/82102193-fea38400-9723-11ea-9ce0-bafbf5a065f7.png)

**Comment by mjbvz** [comment] 2020-05-18 18:24
Duplicate of #85682

**Closed by mjbvz** 2020-05-18 18:24 UTC
