### ISSUE TITLE
Linux: commands with keybindings ignore when clause of the command if defined

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#26318] opened 2017-05-09 15:43 UTC
Version: 1.12.1
OS: Windows 10

I have the following keybinding:

```json
    {
        "key": "ctrl+enter",
        "command": "workbench.action.toggleZenMode",
        "when": "editorTextFocus"
    }
```

When I am using `git` and I am entering a commit message, by pressing <kbd>ctrl+enter</kbd> to commit the message, the editor commits it but it also goes into zen mode. Based on my `when` statement, it shouldn't do that since I am using `editorTextFocus`.

**Comment by alexandrudima** [comment] 2017-05-10 08:42
I could reproduce on Linux.
It is happening because Toggle Zen Mode is in the menus. i.e. the Toggle Zen Mode action is triggered via electron's menus keybinding listeners and via `ipc`, not via the keybindings service.

![image](https://cloud.githubusercontent.com/assets/5047891/25890263/260c132a-356d-11e7-8e4c-cebeb0dc2019.png)

![image](https://cloud.githubusercontent.com/assets/5047891/25890295/46be07f4-356d-11e7-8d16-60607cc3c0ce.png)

**Comment by alexandrudima** [comment] 2017-05-10 08:44
@bpasero I am not sure what the fix should be. We would need to know if a menu action got triggered by the menus via electron's keybindings listener and re-evaluate the `when` condition.

i.e. in other words, showing a keybinding next to a menu action means adding a keybinding in our system without the `when` condition

**Comment by bpasero** [comment] 2017-05-10 13:52
As far as I know there is no way for us to know if a menu item was triggered via mouse of keybinding. There is an event object on the menu item (https://github.com/electron/electron/blob/master/docs/api/menu-item.md#new-menuitemoptions) but this one only seems to be triggered when clicked via mouse and not when triggered via keybinding.

**Comment by bpasero** [comment] 2017-11-13 06:46
Marking as duplicate of https://github.com/Microsoft/vscode/issues/35225

**Closed by bpasero** 2017-11-13 06:46 UTC
Labels: bug, upstream
