### ISSUE TITLE
problem editing keyboard shortcuts in 1.11.1

### ISSUE THREAD

**Issue by cubodehelio** [Microsoft/vscode#24440] opened 2017-04-10 13:41 UTC
- VSCode Version: 1.11.1
- OS Version: Linux Mint 17.2 (ubuntu trusty based)

Steps to Reproduce:

1. ctrl+k ctrl+s to open the keyboard shortcut editor
2. edit "Toggle Line Comment" by pressing `ctrl+[`

The result is `ctrl+shift+{` combination instead of the selected `ctrl+[`.

I used to set `ctrl+[` key combination to toggle line comments. Version `1.11.1` changed most of my custom bindings. Now I wanted to edit the settings to come back to my layout but I can't in some cases.

**Comment by alexandrudima** [comment] 2017-04-10 14:51
@cubodehelio What keyboard layout do you use?

**Comment by MarcosEllys** [comment] 2017-04-10 18:06
Hi,

I'm facing the same problem when commenting a code, the ok + ok shortcut does not work.

My keyboard is Brazilian standard ABNT2

**Comment by yurickgomes** [comment] 2017-04-10 18:42
Hello,
i'm having a similar problem, vscode 1.11.1 (Linux) is not accepting ctrl + / as shortcut. Cheers

**Comment by alexandrudima** [comment] 2017-04-11 07:15
Duplicate of #24147

**Closed by alexandrudima** 2017-04-11 07:15 UTC
Labels: needs more info
