### ISSUE TITLE
Monokai color theme is not consistent on golang

### ISSUE THREAD

**Issue by luxcgo** [microsoft/vscode#206749] opened 2024-03-04 02:32 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:51.279Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.1.0

Steps to Reproduce:
![image](https://github.com/microsoft/vscode/assets/73606679/63d78fc4-ba2f-4f06-9469-d357c202520c)

Old look
![image](https://github.com/microsoft/vscode/assets/73606679/eac5607e-d07e-4a6d-91bd-d3cd9f76f920)

New look 
![image](https://github.com/microsoft/vscode/assets/73606679/b244e9cd-01a0-49fe-aeef-1c02cf10e387)

How could I get the old theme back? Currently, I can only reinstall the v1.85.0, and the old color theme will be back.

**Comment by alexr00** [comment] 2024-03-05 08:48
Duplicate of https://github.com/microsoft/vscode/issues/203998.

I have a comment there which describes how you can change token colors. You can use the steps there to change the colors you care about: https://github.com/microsoft/vscode/issues/203998#issuecomment-1923987723

**Closed by alexr00** 2024-03-05 08:48 UTC
