### ISSUE TITLE
References: focus editor on double click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101522] opened 2020-07-01 16:11 UTC
I am not sure we have API in custom tree land for this, but e.g. the explorer focuses the editor when you double-click a file.

**Comment by jrieken** [comment] 2020-07-01 16:11
no api for that

**Comment by alexr00** [comment] 2020-07-02 07:39
Duplicate of https://github.com/microsoft/vscode/issues/85636

**Closed** 2020-11-05 11:32 UTC
Labels: *duplicate, api, feature-request, references-viewlet
