### ISSUE TITLE
The font size of menu bar.

### ISSUE THREAD

**Issue by michaelbrucelin** [microsoft/vscode#152285] opened 2022-06-16 03:20 UTC
Issue Type: <b>Feature Request</b>

Since vscode was upgraded to v1.68.0, the font of the menu bar (File, Edit, Selection, View, Go, Run, Terminal, Help) will be larger than the font in other locations, and I have not found a way to set the font size of this part. , can the size of this part of the font be adjusted to the font size of other parts of the UI interface, or provide a method to change the font size?

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-15-amd64

**Comment by JasonGore** [comment] 2022-06-20 21:02
I'm having the same issue. The menu is now comically large relative to my font preferences and I haven't yet found a way to change it.

![image](https://user-images.githubusercontent.com/26070760/174677240-30696160-1b34-45f8-a9e5-4cc117d21dc7.png)

**Comment by JasonGore** [comment] 2022-06-20 21:05
Possible duplicate of #151803

**Comment by michaelbrucelin** [comment] 2022-06-21 03:02
> 

Yes, maybe it's the reason for my obsessive-compulsive disorder, although it doesn't affect anything, it looks awkward.

**Comment by DuSHmaner** [comment] 2022-06-21 06:26
I would like to point out that for zoom level < 0 the submenu (in this case preferences submenu) is not positioning right and it can cause some of the menu options which would reach out of the window being hidden.
![image](https://user-images.githubusercontent.com/39909995/174730858-0efa883d-0208-4867-ae7e-7885c64d1a34.png)

**Comment by sbatten** [comment] 2022-06-21 15:49
I'll be closing this as a duplicate, see above, but we definitely are looking to resolve this issue given the issues folks are seeing. 

@DuSHmaner can you file a separate issue for that?

**Closed by sbatten** 2022-06-21 15:49 UTC
