### ISSUE TITLE
vscode-file build: unable to load sourcemaps from asar paths

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#107726] opened 2020-09-29 17:08 UTC
Testing #107466

Ubuntu 

On opening the shared process window I see a bunch of console spam about source maps. 

![image](https://user-images.githubusercontent.com/8586769/94590552-b0f36800-023b-11eb-835d-2cd2cc218059.png)

**Comment by bpasero** [comment] 2020-10-01 06:30
We maybe missing some code for the `vscode-file` protocol in https://github.com/microsoft/vscode/blob/81ec8ec12f4424c69f54bece2c6e971d6a615f5b/src/bootstrap.js#L47-L47, not sure.

**Comment by bpasero** [comment] 2020-10-30 09:40
Looks to me like a duplicate of https://github.com/microsoft/vscode/issues/103344

**Closed** 2021-04-06 19:04 UTC
Labels: *duplicate, debt, sandbox
