### ISSUE TITLE
Git ignore decorations do not reload when branch is changed

### ISSUE THREAD

**Issue by SharpCoder** [microsoft/vscode#53260] opened 2018-06-28 17:41 UTC
- VSCode Version: 1.24.1
- OS Version: Mac OS X 10.11.6

Steps to Reproduce:

1. Create .git project (do not create a .gitignore file)
2. Add some files to the project.
3. Commit changes.
4. Create another branch.
5. Add .gitignore to this branch, which excludes one or more of the files created in previous step.
6. Close VS Code
7. Using a terminal, git checkout the first branch (sans .gitignore)
8. Open the project again in VS code
9. Using a terminal, git checkout the second branch (with .gitignore)
10. VS Code will not process .gitignore until you close and re-open the application.

Expected result:
.gitignored folders would be grayed out

Actual result:
.gitignored folders are still marked as "new"

Does this issue occur when all extensions are disabled?: Yes

**Comment by stoiandan** [comment] 2018-07-21 09:47
I've wrote a [bash script](https://github.com/stoiandan/vscode/blob/%2353260_git_ignore_reload/reproduce.sh) that reproduces your steps, thought it would make it easier.

**Comment by stoiandan** [comment] 2018-07-21 10:45
At step 5, should I commit the `.gitignore` in the second branch? 

Not sure what you meant at step 8: 

> (sans .gitignore)

**Comment by SharpCoder** [comment] 2018-07-21 22:11
Hello. Step 5 you should commit the .gitignore to the second branch, yes.

At step 8, you should checkout the first branch (by `sans .gitignore` I simply meant the branch without .gitignore)
Next step, you should open VS code
Next step, you should use a console to `git checkout second-branch`

**Comment by Hindol** [comment] 2018-09-07 10:21
So, `git checkout` from within **VSCode** should trigger a refresh of `.gitignore` content? I am willing to work on a fix if @stoiandan is not already working on it.

**Comment by joaomoreno** [comment] 2019-06-12 08:53
@jrieken This is clearly a bug.

**Comment by kanlukasz** [comment] 2020-06-22 13:38
In my case I can't reproduce it step by step, but I can confirm that something is wrong with refreshing ignoring decorations (grayed out).

Several times I had a situation in which ignored files stopped being grayed out.

Refreshing VSCode or saving the .gitignore file again helps, but it doesn't change the fact that there is an error here

#### My environment:
```
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by joaomoreno** [comment] 2020-06-23 07:15
I believe the fix for this was pushed in https://github.com/microsoft/vscode/commit/fad4d8d254f9959bb64b9ebb9f6a0742ec4cc005

Let's see if the issues keep coming in.

**Closed by joaomoreno** 2020-06-23 07:15 UTC
Labels: bug, git, help wanted
