### ISSUE TITLE
TypeScript server unable to start

### ISSUE THREAD

**Issue by martellaj** [microsoft/vscode#105617] opened 2020-08-28 19:53 UTC
Issue Type: <b>Bug</b>

When trying to build my code, I get a long-running notification that says "Initializing JS/TS language features" and it'll eventually error out.

**Here's the output (note the timestamps):**
```
[Info  - 18:19:55.175] Starting TS Server 
[Info  - 18:19:55.175] Using tsserver from: c:\Users\joem\Code\client-web\node_modules\typescript\lib\tsserver.js
[Info  - 18:19:55.179] <syntax> Forking...
[Info  - 18:19:55.189] <syntax> Starting...
[Info  - 18:19:55.190] <semantic> Forking...
[Info  - 18:19:55.198] <semantic> Starting...
[Error  - 19:43:17.298] TSServer errored with error.
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at g.onLengthData (c:\Users\joem\.vscode-remote\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\extensions\typescript-language-features\dist\extension.js:45:59996)
	at Socket.<anonymous> (c:\Users\joem\.vscode-remote\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\extensions\typescript-language-features\dist\extension.js:45:59666)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.31GB free)|
|Process Argv|--folder-uri vscode-remote://vsonline%2Be1218aa3-baca-4eb4-badd-7531c44b087f%2Baccountprovider%3Dmicrosoft/c%3A/Users/joem/Code/client-web|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: joem-dev|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|31.79GB (7.27GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vsonline|ms-|1.0.2688
debugger-for-chrome|msj|4.12.10
ejs-language-support|Qas|0.0.1
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
gitlens|eam|10.2.2
prettier-vscode|esb|5.5.0
vscode-pull-request-github|Git|0.19.0
sort-typescript-imports|mic|1.4.1
vscode-azureappservice|ms-|0.18.0
csharp|ms-|1.23.1
azure-account|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2708
vsonline|ms-|1.0.2688
polacode|pnp|0.3.4
vscode-graphql|Pri|0.3.1
project-snippets|reb|0.5.0
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-08-31 21:56
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Specifically extensions such as tslint and IntelliCode which extend the TypeScript server?

**Comment by martellaj** [comment] 2020-09-02 17:54
I switched back to Insiders to see if it was also broken there. It seems to be working as expected in Insiders (didn't disable any extensions).

**Comment by mjbvz** [comment] 2020-09-03 21:27
Thanks for checking. Your insiders build may also have a different set of extensions installed

Closing this for now since it does not happen in insiders. Let us know if you see this again in insiders, specifically with extensions disabled. If you see it only after enabling a specific extension, please file the issue against that extension

**Closed by mjbvz** 2020-09-03 21:27 UTC
Labels: needs more info
