### ISSUE TITLE
SSL error when checking for updates.  No action option to connect anyway.

### ISSUE THREAD

**Issue by Liquidmantis** [Microsoft/vscode#30871] opened 2017-07-17 17:02 UTC
When checking for updates while behind a corporate proxy, an SSL error is given and the user is asked if they want to connect anyway, but there is no option to do so.  Disabling strict SSL doesn't help either.

![image](https://user-images.githubusercontent.com/399056/28279884-2953e222-6adf-11e7-8a8f-7a236fd0768b.png)

- VSCode Version: 1.14.0-insider
- OS Version: MacOS 10.12.5

Steps to Reproduce:

1. Check for VS Code Update

**Comment by joaomoreno** [comment] 2017-07-19 13:17
Interesting, never saw this.

**Comment by AngefloMusic** [comment] 2017-08-15 18:00
Bump, I'm also getting this when checking for updates

**Comment by joaomoreno** [comment] 2017-08-16 07:55
https://code.visualstudio.com/docs/setup/network#_ssl-certificates

Does the update work if you launch Code with `--ignore-certificate-errors`?

**Comment by AngefloMusic** [comment] 2017-08-21 15:11
Hey @joaomoreno I tried that, and it didn't work, I'm also behind a corporate proxy though, however when I bypass the proxy to do the update, it still doesn't work.

**Comment by joaomoreno** [comment] 2017-08-22 07:41
> it still doesn't work

But you still get the same SSL error?

**Comment by rdamron** [comment] 2017-10-16 12:44
Also having this issue.

The problem is very likely due to corporate firewall proxy. Our proxy will mitm tls traffic to do deep packet inspection.

The problem is that the root cert used to sign the the certs presented isn't part of the bundled chrome binary in electron and electron doesn't pick up certs from the host environment.

I've gotten around this in my own electron apps by manually adding the cert to https.globalAgent. Perhaps there could be a config option to add certs?

```
function addRootCA() {
  const trustedCa = ["rootca.crt"];

  https.globalAgent.options.ca = [];
  for (const ca of trustedCa) {
    capath = path.join(__dirname, ca);
    https.globalAgent.options.ca.push(fs.readFileSync(capath));
  }
}
```

**Comment by joaomoreno** [comment] 2017-11-23 14:46
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Closed by joaomoreno** 2017-11-23 14:46 UTC
Labels: bug, install-update
