### ISSUE TITLE
Terminal gives up rendering

### ISSUE THREAD

**Issue by NitroGhost** [Microsoft/vscode#42460] opened 2018-01-30 12:52 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tabulous|bwi|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.4
pgsql|dou|0.1.0
gitlens|eam|7.5.7
tslint|eg2|1.0.24
beautify|Hoo|1.3.0
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
python|ms-|0.9.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.1.0
dust|nem|0.0.1
material-icon-theme|PKi|3.2.2
sass-indented|rob|1.4.6
preview-vscode|sea|1.4.2
code-settings-sync|Sha|2.8.7
react-beautify|tai|0.3.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---
I came across a bizarre issue that I don't know how to reproduce. I locked my laptop and went and interviewed someone for an hour, then when I came back, every single terminal panel across both of my VS Code windows had stopped rendering, with a couple of them showing as black blobs. Closing the side bar made them render again. I use powershell as the terminal in case that helps. 

GIF:
![terminals borked](https://i.imgur.com/vub6XoX.gif)

**Comment by rwatts3** [comment] 2018-01-30 15:21
My Terminal is actually opening and closing it never stays open. lots of terminal fallout in this last release.

**Comment by Tyriar** [comment] 2018-01-30 18:45
@rwatts3 that was a regression in Insiders on Windows related to an optimization we introduced to the node modules shipped with the product. Should be fixed when you update and is unrelated to this issue which has been in since 1.17.

**Comment by rwatts3** [comment] 2018-01-30 18:57
Awesome I can confirm that the last push fixed this issue.

**Closed** 2018-06-21 21:54 UTC
Labels: *not-reproducible, bug, integrated-terminal
