### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by 87lst** [microsoft/vscode#167280] opened 2022-11-25 18:49 UTC
Type: <b>Bug</b>

Constantly listing problems that don`t exist underlining correct lines of code.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.68GB free)|
|Process Argv|--crash-reporter-id db78a79b-30f8-48f0-bc4b-15c049005ef2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.8
cloudcode|goo|1.20.4
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by phudson** [comment] 2022-11-26 09:51
> Constantly listing problems that don`t exist underlining correct lines of code.

More details needed to enable anyone to be able to help you here.

**Comment by joyceerhl** [comment] 2022-11-28 17:11
@87lst please provide a minimal repro e.g. code snippet or sample repository. Please also check whether this is caused by a specific extension (e.g. by disabling all extensions or using the `Start Extension Bisect` command).

**Comment by 87lst** [comment] 2022-11-28 17:32
Hi Joyce

The problem was with Pylance, I have disabled it and don't have these
issues anymore.
Thank you for looking into it for me.

Kind regards

Yuri

**Comment by joyceerhl** [comment] 2022-11-28 18:36
Thanks--closing as this is caused by an extension, please consider reporting a bug on https://github.com/microsoft/pylance-release instead.

**Closed by joyceerhl** 2022-11-28 18:36 UTC
Labels: info-needed, triage-needed
