### ISSUE TITLE
Antimalware Service Executable spikes when searching

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vscode#63070] opened 2018-11-14 00:45 UTC
⚠️ **This is NOT A DUPLICATE of #62509**

- VSCode Version: 

```
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

- OS Version:
```
Microsoft Windows 10 Enterprise Version 1803 (OS Build 17134.407)
```

### Steps to Reproduce:

1. Open **Task Manager** and confirm **Antimalware Service Executable** is not above 10%
2. Open **VSCODE** and wait until **Antimalware Service Executable** goes below 10%
3. Open a file in **VSCODE** and confirm **Antimalware Service Executable** stays below 10%
4. Open a `*.code-workspace` file and confirm **Antimalware Service Executable** is above 80%+

### Does this issue occur when all extensions are disabled?: 
Yes

### Additional info
1. This behavior started to happening right after the latest update.
2. `File` + `Close Workspace` makes **Antimalware Service Executable** go below 10%
3. Opening a folder which is in the Workspace directly has the same affect for a brief moment but then **Antimalware Service Executable** goes below 10%

**Comment by roblourens** [comment] 2018-11-14 01:42
Does it happen if you start with `--disable-extensions`? Likely some extension is starting a search.

**Comment by cilerler** [comment] 2018-11-14 02:37
@roblourens as I already stated in initial post, yes.

**Comment by roblourens** [comment] 2018-11-14 02:42
I missed that, thanks.

When this happens, do you see any `rg.exe` processes? Are there any other vscode processes using high CPU when this happens?

**Comment by cilerler** [comment] 2018-11-14 02:50
Yes, actually I have 2 `rg.exe` with 1% and 1.7% CPU

By the way I'm doing additional test upon a hunch

### Additional experiment
1. I created a new `temp.code-workspace` file and waited until **Antimalware Service Executable** goes below 10%
```
{
	"folders": [	
		{
			"path": "C:\\Users\\myuser\\Documents\\Folder1",
			"name": "Notes"
		}
}
```
2. Added an additional folder into the `temp.code-workspace` file
```
{
	"folders": [	
		{
			"path": "C:\\Users\\myuser\\Documents\\Folder1",
			"name": "Notes"
		},
		{
			"path": "C:\\Users\\myuser\\Documents\\Folder2",
			"name": "Codes"
		}
}
```
it spiked again. not sure what is going on but literally can't work with Workspaces any more.

**Comment by roblourens** [comment] 2018-11-14 02:53
If extensions are disabled, there shouldn't be any `rg.exe` unless you do a search. Can you get the command line args of those from Task manager or the process explorer?

**Comment by cilerler** [comment] 2018-11-14 02:56
I wasn't running it with `--disable-extensions` 
I tried with that and once I saw it does the same thing, I stopped using it.
let me run it with that parameter, will get back to you in a minute

**Comment by cilerler** [comment] 2018-11-14 03:17
By the way, is there any easy way to figure out which one of the extension is causing this?

**Comment by roblourens** [comment] 2018-11-14 05:15
That doesn't necessarily mean it's C#'s fault, do you see something similar when doing a search in this workspace? I asked about rg.exe because it has been involved with Antimalware strangeness in the past. In fact, there is another similar issue open for 1.29: https://github.com/Microsoft/vscode/issues/63036

If you see this with a normal search, then we can reopen this and investigate some more.

**Comment by cilerler** [comment] 2018-11-14 11:04
You were right again, it also happens on another extension [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense). It is not happening as heavy as [C# for Visual Studio Code](https://github.com/OmniSharp/omnisharp-vscode) one but a single `rg.exe` stays in the **Task Manager** and it causes **Antimalware Service Executable** consumption to stay above 40%

However, it doesn't happening on a search even with a heavy result one.  I mean, it does it briefly but then goes down to the normal levels.

I tested 53 extensions and those 2 are the only ones causing this issue.  Here is a good news, since **Path-Intellisense**'s last commit was on Jul 10, 2017, your theory gets confirmed that it should not be something extension related.  _(therefore closing the issue on https://github.com/OmniSharp/omnisharp-vscode/issues/2682 and re-openning this one)_

<details>
 <summary>Tested extensions</summary>

- aaron-bond.better-comments
- acarreiro.calculate
- azuredevspaces.azds
- bierner.markdown-preview-github-styles
- christian-kohler.path-intellisense
- DavidAnson.vscode-markdownlint
- dbaeumer.vscode-eslint
- docsmsft.docs-markdown
- donjayamanne.githistory
- DotJoshJohnson.xml
- EditorConfig.EditorConfig
- eg2.tslint
- esbenp.prettier-vscode
- formulahendry.auto-close-tag
- formulahendry.auto-rename-tag
- formulahendry.dotnet-test-explorer
- helixquar.asciidecorator
- humao.rest-client
- humy2833.ftp-simple
- ionutvmi.reg
- jebbs.markdown-extended
- jebbs.plantuml
- jmazouri.sharppad
- josephwoodward.vscodeilviewer
- jq-syntax-highlighting.jq-syntax-highlighting
- k--kato.docomment
- kumar-harsh.graphql-for-vscode
- mechatroner.rainbow-csv
- ms-azuretools.vscode-azurestorage
- ms-azuretools.vscode-cosmosdb
- ms-docfx.DocFX
- ms-kubernetes-tools.vscode-kubernetes-tools
- ms-mssql.mssql
- ms-python.python
- ms-vscode.azure-account
- ms-vscode.azurecli
- ms-vscode.csharp
- ms-vscode.github-issues-prs
- ms-vscode.PowerShell
- ms-vsliveshare.vsliveshare
- ms-vsliveshare.vsliveshare-audio
- ms-vsts.team
- msjsdiag.debugger-for-chrome
- PeterJausovec.vscode-docker
- pflannery.vscode-versionlens
- PKief.material-icon-theme
- quicktype.quicktype
- redhat.vscode-yaml
- stansw.vscode-odata
- tomoki1207.pdf
- vitorsalgado.vscode-redis
- wayou.vscode-todo-highlight
- zbecknell.t4-support

</details>

**Comment by roblourens** [comment] 2018-11-14 17:59
Did you test text search or file search?

**Comment by cilerler** [comment] 2018-11-14 18:55
File

![image](https://user-images.githubusercontent.com/385958/48505357-e09a5200-e814-11e8-8e71-0fbad6356877.png)

**Comment by roblourens** [comment] 2018-11-14 18:58
That's text search, I ask about file search (ctrl/cmd+p) because it is probably what the extension is actually doing.

Anyway I think the whole point of this is that rg triggers windows defender, I don't know why.

**Comment by cilerler** [comment] 2018-11-14 19:06
Sorry my bad, I thought <kbd>CTRL</kbd>+<kbd>F</kbd> is **text search** and the one through **tab** is **file search**, didn't realized there is a 3rd option <kbd>CTRL</kbd>+<kbd>P</kbd>

I hope you can figure out what it is, since I can not use C# extension any more :cry:

**Comment by PerpetualWar** [comment] 2018-11-16 08:05
I have the same problem from ver. 1.29.0, now I updated to 1.29.1, problem persists.... I also use C# and path intellisense extensions among many others. I had to add exception to Defender for Code.exe, and maybe even that is not enough, so I had to turn off real time protection.

This really needs fixing :/

**Comment by PerpetualWar** [comment] 2018-11-16 08:13
Ye, I have to either disable real time protection or to disable C# plugin (which I ended disabling). 

```Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64```

**Comment by cilerler** [comment] 2018-11-16 13:04
Confirming that v1.29.1 also has the same issue

```
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by bmingles** [comment] 2018-11-18 02:59
I am also seeing CPU spikes from antimalware service when running vscode since upgrading to 1.29.1

**Comment by Kcko** [comment] 2018-11-18 15:30
> I am also seeing CPU spikes from antimalware service when running vscode since upgrading to 1.29.1

From 1.29.0 :(

**Comment by sstoychev** [comment] 2018-11-20 00:34
Just a hint - this started since vscode moved to rg. 0.10, as I noticed in #61130 .
Now I tried, downloaded rg 0.9, replaced it and now filesearch is working. Vscode 1.28 was with rg 0.9 and was fine. I know text search is not working with 0.9 but I can live with this.

**Comment by bobwinners** [comment] 2018-11-20 13:37
I am having this same problem.  It takes about 10 minutes for the Defender Antivirus Service to go back down to normal CPU utilization.

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by Kcko** [comment] 2018-11-20 13:40
to ALL: temporary solution is turn off Windows Defender :(

**Comment by Kcko** [comment] 2018-11-20 13:42
To dev team: Is anyone trying to solve this a major problem?

**Comment by roblourens** [comment] 2018-11-20 18:52
This has been an issue for as long as we've been using ripgrep, unfortunately walking the disk and opening lots of files seems to be suspicious behavior...

**Comment by julesgilson** [comment] 2018-11-22 09:19
same basic issue - have Path Intellisense extension installed also (as well as many others). Like all others, issue has started since V1.29.0, didn't notice any lengthy slow-downs before that

**Comment by roblourens** [comment] 2018-11-26 02:16
This is actually a regression after all, I am following up upstream with ripgrep.

**Comment by scramsby** [comment] 2018-11-27 17:42
Note: I'm experiencing this same issue, and even if you disable Defender, I just see CPU usage on the ripgrep processes spike up to max instead. Makes VS Code essentially unusable for me right now.

**Comment by ratidzidziguri** [comment] 2018-11-27 21:04
Same here version 1.29.1 IDE became unusable for me

**Comment by Twois** [comment] 2018-11-28 09:03
Same too, its really annoying.

**Comment by jextrevor** [comment] 2018-11-28 19:51
I'm encountering this same issue.

**Comment by roblourens** [comment] 2018-11-28 19:55
Pushed a fix into Insiders - would appreciate if everyone tries in the **next** Insiders build (about 11 hours after this post)

**Closed** 2018-11-28 19:56 UTC
Labels: bug, search

**Comment by sstoychev** [comment] 2018-11-29 08:09
It is working for me, text search is OK too.

**Comment by julesgilson** [comment] 2018-11-29 10:11
I don't have the exact same extensions in my Insiders install but opening the latest Insiders build with the same workspace as stable build no longer results in long periods of the Antimalware Service Executable hitting max CPU. It did when I first opened the workspace, presumably as there was indexing going on (PHP Intelephense) - but subsequent start-ups are fine. Any idea when this will get pushed to stable release?

**Comment by Cyrus-d** [comment] 2018-11-29 11:56
No high CPU with Insiders build.

**Comment by PerpetualWar** [comment] 2018-11-29 12:52
@cilerler have you tried enabling C# plugin again and testing this ?

**Comment by cilerler** [comment] 2018-11-29 13:04
@PerpetualWar yes

**Comment by tcsmith** [comment] 2018-11-29 13:33
Insiders build solved the problem. Ctrl-Shift-B menu is near instantaneous.
Thanks for the quick fix.

**Comment by roblourens** [comment] 2018-11-29 15:45
Fantastic, thanks for checking. Next stable release is sometime around December 12th.

**Comment by sllim93** [comment] 2018-12-12 07:06
this issue not resolved yet, just a reminder for the authority in charge.

**Comment by cilerler** [comment] 2018-12-12 07:18
@sllim93 as stated above it will be released on December 12th in stable build, however you can use the insider build in the meanwhile which has the patch
