### ISSUE TITLE
predefined variables does not work on input default Field

### ISSUE THREAD

**Issue by chidaren** [microsoft/vscode#77727] opened 2019-07-22 02:28 UTC
- VSCode Version: 1.36.1
- OS Version: Linux work-PC 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux

Steps to Reproduce:

1. edit task.json to add this:
```
{
            "label": "test this file",
            "group": "build",
            "type": "shell",
            "command": "go",
            "args": [
                "test",
                "${input:file}"
            ],
            "problemMatcher": "$go",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            }
        }
```
2. add input varibale like this:
```
  {
            "type": "promptString",
            "id": "file",
            "description": "the file name to be tested",
            "default": "${file}"
        },
```

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/12998285/61602408-f0075000-ac6b-11e9-8ec3-7944dba8eb0b.png)

**Comment by alexr00** [comment] 2019-07-29 11:46
Duplicate of https://github.com/microsoft/vscode/issues/64358

**Closed** 2019-07-29 11:46 UTC
Labels: *duplicate, extensions
