### ISSUE TITLE
Using cls in integrated terminal sometimes freezes it

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6735] opened 2016-05-24 08:57 UTC
Testing #6654 

on Windows, default PowerShell

I am sorry for the unclear steps, please ping me if you cannot repro
* do some `cd`s
* do some `ls`s
* do a `cls`
* sometimes it works, but very often it appears to freeze the terminal and the cursor is no longer visible
* scrolling a bit seems to help...

![terminal-freeze](https://cloud.githubusercontent.com/assets/5047891/15498089/3dfd76a6-219e-11e6-8dc7-f9aa007c7da8.gif)

**Comment by alexandrudima** [comment] 2016-05-24 12:35
The same problem occurs on Ubuntu 16.04 when using `clear` -- the cursor disappears

**Comment by Tyriar** [comment] 2016-05-24 20:29
I believe I've reproduced this before, but I think it's one in the category of bugs that would require forking term.js.

**Comment by russlescai** [comment] 2016-05-31 04:06
I could be experiencing the same issue, not sure - when I type "cls" into command prompt, sometimes (with a full screen of text) it won't refresh until I hit another key (then it clears the screen and renders that key).

Windows 7, using Cmd and Powershell 2 as terminal

**Comment by leedonhyun** [comment] 2016-06-08 00:50
enter key down repeatly in terminal window.

key down cls command.

![animation](https://cloud.githubusercontent.com/assets/8449892/15879291/c65aabc0-2d5d-11e6-9010-d0d96d5ea72c.gif)

**Comment by Tyriar** [comment] 2016-06-08 00:51
@leedonhyun thanks for the animation! That looks like this issue: https://github.com/Microsoft/vscode/issues/6738

**Comment by Tyriar** [comment] 2016-07-05 17:39
Closing as a lot of changes have been made to clear logic in v1.2.

**Closed by Tyriar** 2016-07-05 17:39 UTC
Labels: bug, integrated-terminal
