### ISSUE TITLE
JavaScript syntax not working as expected

### ISSUE THREAD

**Issue by githubhero** [Microsoft/vscode#7753] opened 2016-06-16 06:26 UTC
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Paste some JavaScript code (I used this one: https://github.com/wbkd/d3-extended/blob/master/d3-extended.js);
2. Check highlight errors;

![js](https://cloud.githubusercontent.com/assets/1677287/16107310/ea7a4ed6-339b-11e6-8971-b4023132f755.png)

The theme I'm using is Monokai.

**Comment by aeschli** [comment] 2016-06-16 09:45
Can you describe what you are expecting?

**Comment by githubhero** [comment] 2016-06-16 09:57
@aeschli, I want highlighted:

- console.log;
- prototype.addClass;
- document.createElement;
- parentNode;
- insertBefore;
- etc.

Just compare the JS file you find at: https://github.com/wbkd/d3-extended/blob/master/d3-extended.js

**Comment by githubhero** [comment] 2016-06-16 10:19
This is from SublimeText:

![sublime](https://cloud.githubusercontent.com/assets/1677287/16113453/829e500c-33bc-11e6-89d0-62ef4e76e334.png)

This one is from Atom:

![atom](https://cloud.githubusercontent.com/assets/1677287/16113463/8ab03ab2-33bc-11e6-8717-2b0f9e9743a3.png)

I hope this helps   :-)

**Comment by aeschli** [comment] 2016-06-16 14:03
Ok, what you want is highlighting for references of variables and functions.
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/149

**Closed by aeschli** 2016-06-16 14:03 UTC
Labels: bug

**Comment by githubhero** [comment] 2016-06-16 14:22
`document.createElement` is something built-in in JS (it's DOM programming), not custom code, anyway

**Comment by aeschli** [comment] 2016-06-16 14:29
It depends if you are in a browser or nodejs environment. But yes, I see what you mean. it's colorizing for standard library functions.

**Comment by githubhero** [comment] 2016-06-16 14:32
@aeschli Of course, yes. In this case, since _d3.js_ is a client library (it deals with SVG), it's client code
