### ISSUE TITLE
Support CSS Color Module Level 4 colors

### ISSUE THREAD

**Issue by DominicTobias** [microsoft/vscode#114495] opened 2021-01-17 16:46 UTC
VSCode currently only shows the color picker for old style rga and rgba values, i.e.:

![old](https://user-images.githubusercontent.com/760314/104849732-479c7f80-5926-11eb-8f32-bed9b5e6e604.png)

Chrome DevTools uses [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/) by default now, so currently we have to manually convert colors copied from there to see what they are in VSCode, as the picker doesn't show:

![new1](https://user-images.githubusercontent.com/760314/104849764-74509700-5926-11eb-892f-7dfa4722ef56.png)

![new2](https://user-images.githubusercontent.com/760314/104849766-761a5a80-5926-11eb-9860-62e478860e88.png)

So I'm requesting support for this new syntax which become the default in the future. Thanks!

**Comment by aeschli** [comment] 2021-01-18 09:47
duplicate of https://github.com/microsoft/vscode/issues/43111

**Closed by aeschli** 2021-01-18 09:47 UTC
