### ISSUE TITLE
Thin font rendering issues on macOS Catalina

### ISSUE THREAD

**Issue by sschultze** [microsoft/vscode#82109] opened 2019-10-08 14:48 UTC
Issue Type: <b>Bug</b>

After upgrading to macOS Catalina, the system font used in Visual Studio Code looks very narrow - and different from other apps in macOS Catalina.

It seems that instead of using **SF Pro Text**, Visual Studio Code uses **.SF NS** on macOS Catalina.

This is probably due to a bug in Chromium which I have reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1012247

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by misolori** [comment] 2019-10-09 16:22
Relate to this, on the Welcome screen the title areas are a lot thinner in the new font:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35271042/66500431-5be0a400-ea76-11e9-9ea7-1ecd610240a0.png">

**Comment by bpasero** [comment] 2019-10-10 12:13
@deepak1556 maybe something to backport

**Comment by sschultze** [comment] 2019-10-11 07:46
One of my computers I downgraded to macOS Mojave because of this issue.

On the other computer, downgrading is not possible (because of my photo library etc.), but I've found a workaround at least for the code editor:

You can play around with the setting "Editor: Letter Spacing". On my computer, entering "-0.2" did a good job at working around this issue (at least for the editor, which is the most important to me).

**Comment by DOBRO** [comment] 2019-10-14 13:38
Try this in Terminal:
```
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
```
and reopen VS Code

**Comment by sschultze** [comment] 2019-10-15 06:05
Thank you, but doesn't change anything and doesn't seem to have anything to do with this issue. (I had CGFontRenderingFontSmoothingDisabled to NO set globally before, that's probably the reason I don't see any change).

**Comment by DOBRO** [comment] 2019-10-15 07:52
Setting `CGFontRenderingFontSmoothingDisabled` to `NO` (or `YES`) globally doesn't change font rendering for VS Code on Catalina.
You should also check option `workbench.fontAliasing` in VS Code settings, it should be set to `default`.
So, this is what I've done step by step:

- in Terminal:
```
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
```
- in VS Code Settings:
```
"workbench.fontAliasing": "default"
```

Text looks better now but not as perfect as before on Mojave.

**Comment by reinvanimschoot** [comment] 2019-10-21 09:45
Back in Mojave, this fix used to work fine but it doesn't anymore. Is there any other possible solution to this issue?

**Comment by mit-bhalodi** [comment] 2019-10-27 04:41
> Try this in Terminal:
> 
> ```
> defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
> ```
> 
> and reopen VS Code

I have have issue with font smoothing (MacBook Air 2017 )command which stopped working after Catalina update, so font looks kinda blurry. please give me solution for this.

**Comment by MariuzM** [comment] 2019-11-11 17:21
1.39
<img width="1440" alt="1 39" src="https://user-images.githubusercontent.com/36937039/68607005-925f7380-04a7-11ea-9702-4dcb48ac933f.png">

1.40
<img width="1440" alt="1 40" src="https://user-images.githubusercontent.com/36937039/68607020-99868180-04a7-11ea-814d-8b7acf53a1b2.png">

On Mojave

Also using these to fix Mojave aa font rendering so not sure if this is related. 
`defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE
`
`defaults -currentHost write -globalDomain AppleFontSmoothing -int 1
`

**Comment by bpasero** [comment] 2019-11-11 18:09
@MariuzM how about VSCode insiders 1.41?

**Comment by MariuzM** [comment] 2019-11-11 18:32
For Insider 1 41
<img width="1440" alt="1 41 Insider" src="https://user-images.githubusercontent.com/36937039/68611270-a314e700-04b1-11ea-9875-679d976f9667.png">

**Comment by bpasero** [comment] 2019-11-12 07:10
@MariuzM 
We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)

**Comment by DOBRO** [comment] 2019-11-12 10:51
> @MariuzM
> We are building exploration builds that use a much newer version of our UI framework (Electron version 7.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
> * Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
> * Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
> * Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)

I've downloaded macOS version. No changes on iMac (Retina 5K, 27-inch, Late 2015), Catalina 10.15.1. Still thin fonts.
```
Version: 1.41.0-exploration
Commit: fbad8db043f1ef8e3b4031d46057edb5911f92ba
Date: 2019-11-08T08:14:25.355Z
Electron: 7.1.1
Chrome: 78.0.3904.99
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0
```

My VS Code settings (before):
```
"editor.fontSize": 18,
"editor.fontFamily": "'Roboto Mono', Menlo, Monaco, monospace",
"editor.fontWeight": "300",
"workbench.fontAliasing": "default"
```

So I have to set:
```
"editor.fontWeight": "400",
"workbench.fontAliasing": "antialiased"
```

**Comment by cebor** [comment] 2019-11-12 14:52
I think what we should keep in mind is that macOS has thinner fonts since Mojave, as wanted by Apple.

The following workaround works with Pre-Electron 6 versions (<= vscode 1.39), but not with >= 1.40:
```bash
defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE
```
For all users who don't use this workaround, font rendering has improved since 1.40, for all those who use it it has stayed the same or even deteriorated.

So I think many users see the thinner fonts as a bug even though this is not one at all.

**Comment by bpasero** [comment] 2019-11-12 17:00
I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net

Does the issue reproduce in that setup in the browser?

**Comment by MariuzM** [comment] 2019-11-12 18:01
Exploration
<img width="1440" alt="Screenshot 2019-11-12 at 18 00 54" src="https://user-images.githubusercontent.com/36937039/68697283-6828b700-0576-11ea-862e-85e06fac666b.png">

**Comment by MariuzM** [comment] 2019-11-12 18:09
1.39 - With Mojave font tweak
<img width="1440" alt="1 39" src="https://user-images.githubusercontent.com/36937039/68697807-7cb97f00-0577-11ea-90b6-242f9dba64c3.png">

1.39 - Default Mojave
<img width="1440" alt="1 39 - Mojave defaults" src="https://user-images.githubusercontent.com/36937039/68697831-8c38c800-0577-11ea-93be-ce225b89fc2e.png">

1.40 - Default Mojave
<img width="1440" alt="Screenshot 2019-11-12 at 18 06 59" src="https://user-images.githubusercontent.com/36937039/68697864-98bd2080-0577-11ea-9b0b-63f6a2afc1e4.png">

**Comment by MariuzM** [comment] 2019-11-12 18:12
So the way I understand this Mojave tweak is not causing the issue.

**Comment by cebor** [comment] 2019-11-12 18:26
@MariuzM very strange, for me its the exact opposite, besides the dimmed colorization.

Can you check the Settings -> Workbench -> Appearance -> Font Aliasing, is it set to `default` ?

**Comment by MariuzM** [comment] 2019-11-12 18:29
Yep on all instances it's set to default

**Comment by cebor** [comment] 2019-11-12 18:34
MacOS Preferences -> General -> Use font smoothing when available (x).  Do you also have this enabled.  For me, when i disable this option i get the same results as you.

**Comment by MariuzM** [comment] 2019-11-12 18:36
Tried both on and off no difference this was tested with default Mojave (no font tweak)

**Comment by sschultze** [comment] 2019-11-12 18:53
The Chromium team has yet to fix this unfortunately. Until then, I guess there's not much that can be done on the VS Code side. I have downgraded my main computer to macOS Mojave because of this issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=1005969

"We're treating this issue as high priority and progress is being made towards a fix. The issue is complex due to changes to the "San Francisco" system font and how CoreText works with respect to setting the optical size axis. As you can see from the BlockedOn: column, the Chromium side fix depends on fixes in the Skia graphics library. Please continue to star this issue and follow along, but please keep comments on topic."

**Comment by uurtsaikhb** [comment] 2019-12-17 18:00
They have patch to fix it, can't wait to update it. Good job guys

**Comment by CamelCaseNotation** [comment] 2020-01-15 20:51
Is this still an ongoing issue?

**Comment by DOBRO** [comment] 2020-01-16 07:33
> Is this still an ongoing issue?

As for me, it should be closed. Thanks!

**Comment by MariuzM** [comment] 2020-01-16 10:56
For me it's still an issue but i just got used to it.

**Comment by luisbelloch** [comment] 2020-02-11 08:39
Still and issue for me 🤔  Font looks blurry on external monitor.

![Screenshot 2020-02-11 at 09 37 03](https://user-images.githubusercontent.com/160260/74221345-34167c80-4cb2-11ea-9ff9-790a9b3389d1.png)

![Screenshot 2020-02-11 at 09 37 28](https://user-images.githubusercontent.com/160260/74221346-3678d680-4cb2-11ea-8086-0b712ef85895.png)

I've also set this:

```
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
```

Keeping on 1.39.0 until this gets fixed 😞

**Comment by MariuzM** [comment] 2020-02-11 09:14
This won't get fixed i believe, VSCode or Electron stoped using MacOS sub pixel AA, even on Mojave and later Apple stoped supporting this

**Comment by sodatea** [comment] 2020-02-11 09:42
The Chromium team has (partially) fixed the narrow font issue and shipped it in the Canary channel (v81).

The current stable Electron release depends on Chromium 80 https://github.com/electron/electron/releases/tag/v8.0.0

The VSCode project depends on Electron 7.1.11 at the moment https://github.com/microsoft/vscode/blob/f4a868fb0dbcf397579cb58fab168049a0448e6c/package.json#L97

So there seems still a long way to go.

**Comment by deepak1556** [comment] 2020-11-05 09:11
the relevant chromium fix has been landed with our latest stable, closing

**Closed by deepak1556** 2020-11-05 09:11 UTC
Labels: electron, font-rendering, macos-catalina, upstream, upstream-issue-linked
