### ISSUE TITLE
Java extension probably has conflict with the 1.46.0 version

### ISSUE THREAD

**Issue by SilenceX12138** [microsoft/vscode#99958] opened 2020-06-12 09:15 UTC
Issue Type: <b>Bug</b>

Issue occurs when using java pack to develop.
When clicking "run", it used to run the code with breakpoint neglected. But now it will end up in the same way as clicking "debug".

![LB3(O5C%1Y%{ U){@V(C) 3](https://user-images.githubusercontent.com/47887520/84486595-345e6d00-acd0-11ea-9546-2d1e5d7bdc9b.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment] 2020-06-12 09:31
@isidorn could this be related to what @weinand wrote [here](https://github.com/microsoft/vscode/pull/99678#pullrequestreview-427275116) about the #99678 change you made for 1.46?

**Comment by isidorn** [comment] 2020-06-12 09:37
@gjsjohnmurray great catch.
Yes this smells like a duplicate of that issue.
@SilenceX12138 can you always reproduce this? For example you reload VS Code and just hit Run? Does it work as expected then?
Or it only does not work when you switch between run and debug?

**Comment by SilenceX12138** [comment] 2020-06-12 10:05
> @gjsjohnmurray great catch.
> Yes this smells like a duplicate of that issue.
> @SilenceX12138 can you always reproduce this? For example you reload VS Code and just hit Run? Does it work as expected then?
> Or it only does not work when you switch between run and debug?

I tried both reloading VS Code and rebooting my PC, it still occurs however...

**Comment by isidorn** [comment] 2020-06-12 15:09
@SilenceX12138 I will provide a build which has the issue fixed on monday so you can verify all is good with that build. THanks

**Comment by jdneo** [comment] 2020-06-16 06:56
I tested the insider:

Version: 1.47.0-insider (user setup)
Commit: 0288447572790f983c350905bd1fc5b754970a0a
Date: 2020-06-15T07:44:14.223Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Still cannot run without debug

**Comment by isidorn** [comment] 2020-06-16 10:13
I pushed a potential fix for this, can you please try vscode insiders from Wednesday.
Also @testforstephen can you reproduce this?

**Comment by testforstephen** [comment] 2020-06-16 10:40
yes, i can reproduce it in 1.46.0 and 1.47.0-insider.

**Comment by isidorn** [comment] 2020-06-16 13:04
@testforstephen can you please try it tomrrow with vscode insiders? I have pushed a potential fix for this.

**Comment by isidorn** [comment] 2020-06-17 10:13
Duplicate of https://github.com/microsoft/vscode/issues/100364
Will be fixed soon both in insiders and stable

**Closed by isidorn** 2020-06-17 10:13 UTC
Labels: debug, needs more info
