### ISSUE TITLE
Rename preview doesn't seem to work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#99444] opened 2020-06-02 18:30 UTC
Testing: microsoft/vscode#98821

![recording (6)](https://user-images.githubusercontent.com/2193314/83556178-4cf6a800-a4c4-11ea-80a3-92810e9ed822.gif)

**Comment by jrieken** [comment] 2020-06-08 16:02
😕 I cannot reproduce anymore... @Tyriar Can you give it a try?

**Comment by Tyriar** [comment] 2020-06-08 17:43
I can't repro either, I'm guessing my notebook became corrupted somehow as https://github.com/microsoft/vscode/issues/99443 also was happening all the time back then and now isn't (after I've deleted and recreated the notebook since).

**Comment by jrieken** [comment] 2020-06-09 06:58
I guess, it must have been something in-flight. When I wrote the test plan it quickly tested things and while the diff is bogous no errors are thrown. Then, when you reported the issue I could reproduce the error. Now it's gone. Bit rotting and healing?

**Comment by jrieken** [comment] 2020-06-09 06:58
closing but I'll keep an eye open

**Closed** 2020-06-09 06:58 UTC
Labels: *not-reproducible, bug, notebook
