### ISSUE TITLE
Using custom names for identical folder names in workspace confuses search

### ISSUE THREAD

**Issue by r0ckarong** [microsoft/vscode#184997] opened 2023-06-13 08:45 UTC
Type: <b>Bug</b>

I have to maintain several projects both on git and SVN but they are separate copies. I have added both copies to the workspace and then manually edited the "name" field in the workspace file to add the respective location e.g. "project (git)" and "project (SVN)". Now when I try to perform a search (Find in Folder) of one of these projects I will get search results for any and all files from all projects across the workspace. It seems the search can not handle the added parentheses in the name field and instead shows all search results across all projects in the workspace. 

If changing the repo "name" manually isn't intended then please consider this a feature request to support this.

![2023-06-13 10_46_15-Window](https://github.com/microsoft/vscode/assets/4920542/e930869a-6b82-4e76-b600-24c8756724ba)
![2023-06-13 10_46_40-Window](https://github.com/microsoft/vscode/assets/4920542/d0cd629f-6b36-43df-9a62-82fa36265693)

VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (5.50GB free)|
|Process Argv|--crash-reporter-id e4090bd3-edd6-49af-8d84-8d1687ea6c20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
xml|Dot|2.5.1
auto-close-tag|for|0.5.14
selected-lines-count|gur|1.4.0
output-colorizer|IBM|0.1.2
code-eol|jef|1.0.12
endwise|kai|1.5.1
vsc-python-indent|Kev|1.18.0
ruby-symbols|mig|0.1.8
pylint|ms-|2023.4.0
python|ms-|2023.10.0
vscode-pylance|ms-|2023.6.10
cpptools|ms-|1.16.0
material-icon-theme|PKi|4.28.0
synthwave-vscode|Rob|0.1.15
multi-command|ryu|1.6.0
code-spell-checker|str|2.20.5
code-spell-checker-german|str|2.2.1
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
gitblame|wad|10.2.0
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30757130

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-06-13 09:05
Does it behave better if you avoid all types of bracket in the folder name override?

**Comment by r0ckarong** [comment] 2023-06-13 09:12
> Does it behave better if you avoid all types of bracket in the folder name override?

Yes, if I just use a dash as a separator it shows only results from the selected folder.

![2023-06-13 11_11_33-Window](https://github.com/microsoft/vscode/assets/4920542/ae3e8036-d0b4-4271-b645-11b9179882be)
![2023-06-13 11_11_43-Window](https://github.com/microsoft/vscode/assets/4920542/036ea79f-4546-4e0c-be25-b5c47ae57215)

**Comment by gjsjohnmurray** [comment] 2023-06-13 12:26
#166318 fixed Find in Folder in cases where the folder name contains some special characters, but not the ( and ) brackets.

**Comment by andreamah** [comment] 2023-06-15 22:13
https://github.com/microsoft/vscode/pull/166318 should have already been released, but I see that this persists in the current latest.

**Comment by andreamah** [comment] 2023-12-05 22:25
This is actually a duplicate of https://github.com/microsoft/vscode/issues/175063

**Closed by andreamah** 2023-12-05 22:25 UTC
Labels: bug, search
