### ISSUE TITLE
Iterating multiple occurrences changes the search filter when occurrences are adjacent

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode#11151] opened 2016-08-30 01:29 UTC
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

I'm just trying to select all dashes by selecting one dash and pressing Cmd+D. However after a while, selection filter turns  into `----`. This is a bit unexpected to me coming from Sublime Text.

![](https://cl.ly/0N0X302P3J23/Screen%20Recording%202016-08-29%20at%2006.27%20PM.gif)

Compare this with Sublime Text:

![](https://cl.ly/3T0Z0k3P462r/Screen%20Recording%202016-08-29%20at%2006.28%20PM.gif)

**Comment by alexandrudima** [comment] 2017-03-31 07:20
Also duplicate of #6661

**Closed by alexandrudima** 2017-03-31 07:20 UTC
Labels: bug, editor, editor-multicursor
