### ISSUE TITLE
ittellisense crashes when jest is installed in node_modules

### ISSUE THREAD

**Issue by abumalick** [Microsoft/vscode#30805] opened 2017-07-16 13:26 UTC
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.8.0-51-generic (Linux Mint MATE 18.2)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
sort-lines|Tyr|1.3.0
vscode-color|ans|0.4.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
python|don|0.6.7
gitlens|eam|4.3.1
tslint|eg2|0.16.0
prettier-vscode|esb|0.21.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
sass-lint|gle|0.0.4
vscode-remark|mrm|1.1.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
gitlink|qez|0.2.2
Ruby|reb|0.12.1
vscode-icons|rob|7.10.1
stylelint|shi|0.27.0
autoimport|ste|1.2.2
code-spell-checker|str|1.3.0
vscode-react-native|vsm|0.3.2
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

Steps to Reproduce:
```
git clone https://github.com/abumalick/vscode-jsconfig.git
yarn
```
go into src/test.js put the cursor after `Lib.` and press Ctrl+space to see suggestions, I see it one time and after that I don't see suggestions anymore, it seems intellisense crashed.

In output/Typescript I have the following logs:
```
[Error  - 3:16:04 PM] 'completions' request failed with error.
Error processing request. Project '/home/abumalick/ws/prj/vscodeBug/jsconfig.json' does not contain document '/home/abumalick/.cache/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
Error: Project '/home/abumalick/ws/prj/vscodeBug/jsconfig.json' does not contain document '/home/abumalick/.cache/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:75718:23)
    at ConfiguredProject.Project.getScriptInfoForNormalizedPath (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:77238:42)
    at ConfiguredProject.Project.getScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:77243:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76551:51)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:84
    at Object.map (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:1483:29)
    at ModuleBuilder.getReferencedFileInfos (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:31)
    at ModuleBuilder.updateFileReferences (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76708:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76693:30)
    at ModuleBuilder.onProjectUpdateGraph (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:76684:22)
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-07-17 16:40
Duplicate of #30425

I'm working with the TypeScript team to resolve this.

As a workaround, try disabling type acquisition as [suggested here](https://github.com/Microsoft/vscode/issues/30425#issuecomment-315660909). You can also downgrade the TypeScript version. [Here are the instructions on that](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). We previously shipped with TS 2.3.4 so you'll want to try installing that version locally and using it in your workspace

**Closed by mjbvz** 2017-07-17 16:40 UTC
Labels: duplicate, new release, typescript
