### ISSUE TITLE
Tasks won't run if User Settings file has no settings after updating to 1.9.0

### ISSUE THREAD

**Issue by esoltys** [Microsoft/vscode#19862] opened 2017-02-03 16:14 UTC
Tasks that ran before the 1.9.0 update weren't after updating. I discovered that they resumed working after I defined a setting in User Settings. I usually keep my settings in Workspace and User Settings had been empty other than the default comment:

// Place your settings in this file to overwrite the default settings

- VSCode Version: 1.9.0
- OS Version: Windows 10 Home v1607

Steps to Reproduce:

1. Update to VSCode 1.9.0
2. Have no settings defined in User Settings.
3. Tasks that ran before updating to 1.9.0 will no longer run.
4. Define a User Setting, such as "editor.renderWhitespace": "none"
5. Tasks resume working.

Tasks don't run or produce any message in the output window. The same commands can be run manually from the VSCode terminal, so I don't believe it was a PATH problem.

**Comment by dbaeumer** [comment] 2017-02-06 10:20
@esoltys I was not able to reproduce. I started VS Code with `code.cmd --user-data-dir . --extensions-dir . .` which creates a fresh user data in a fresh workspace. I used the tasks.json
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "args": ["Hello World"],
    "showOutput": "always"
}
```
which executes fine. Can you share a workspace demonstrating the problem. 

Could also be a dup of https://github.com/Microsoft/vscode/issues/19743

**Comment by dbaeumer** [comment] 2017-02-06 10:21
@sandy081 is this something that sounds familiar. Could be another behavior change in settings.

**Comment by sandy081** [comment] 2017-02-06 11:06
@dbaeumer Looking at the steps to reproduce, I do not think there is a behavioral change. Looks like user has all files (user settings, tasks.json) where as in other case (#19743) there was no tasks.json. Unless user gives us more information I cannot confirm.

**Comment by esoltys** [comment] 2017-02-06 16:52
I can reproduce, by opening User Settings and deleting everything but the opening comment line "// Place your settings...". Put even empty braces "{ }" in the file and tasks will work again.

**Comment by esoltys** [comment] 2017-02-06 17:03
@dbaeumer I tried your test case and the User Settings file contains empty braces. I could reproduce tasks not running by deleting those empty braces leaving only the comment line.

So, to reproduce: User Settings file contains only a comment on the first line.

**Comment by sandy081** [comment] 2017-02-06 17:29
@esoltys I am also not able to reproduce it on 1.9v. Please see the steps I followed in the following video. Let me know if I missed any steps or any other difference with the setup.

![kapture 2017-02-06 at 18 25 51](https://cloud.githubusercontent.com/assets/10746682/22658306/f30b3f94-ec99-11e6-8f53-a486b2e60147.gif)

Also, Is it possible to try our insiders build and reproduce it? Here is the link to latest insiders 
http://code.visualstudio.com/insiders

**Comment by esoltys** [comment] 2017-02-06 21:45
You need to have a comment line // as the sole contents of the User Settings.

// anything can go here

**Comment by sandy081** [comment] 2017-02-07 08:03
@esoltys Same result with commented line also. Cannot reproduce.

**Comment by dbaeumer** [comment] 2017-02-07 10:23
@sandy081 the problem is a call this.configurationService.reloadConfiguration() which results in an exception in this setup. Moving to you.

**Comment by sandy081** [comment] 2017-02-07 10:34
@esoltys I take back my last comment. It's reproducable with just a comment line. This is a dup of #19773

**Closed by sandy081** 2017-02-07 10:34 UTC
