### ISSUE TITLE
In JS files, the function call buffer() is not colored

### ISSUE THREAD

**Issue by joakim** [Microsoft/vscode#18979] opened 2017-01-21 15:19 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0

In JavaScript files, the function call `buffer()` is not colored like other function calls, despite not being a reserved word or anything special. It appears to affect all themes.

Screenshot:
http://cl.ly/372Q2G310U1C

Same code as in screenshot (how it should look):
```js
foo()
buffer()
buffer(true)
buffer(foo(true))
```

**Comment by aeschli** [comment] 2017-01-23 13:33
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/408

**Closed by aeschli** 2017-01-23 13:33 UTC
Labels: javascript
