### ISSUE TITLE
Crashing on OS X 10.8.3

### ISSUE THREAD

**Issue by tarunjuneja** [Microsoft/vscode#1058] opened 2015-12-07 08:07 UTC
Hi,

The moment i upgraded from an older version to v0.10.1it started crashing. I can not open it anymore.

I tried downloading greater version like 
- v0.10.2
- v0.10.3

But that does not work either. Please see attached file [crash info.txt](https://github.com/Microsoft/vscode/files/53608/crash.info.txt) for more information.

Thanks

**Comment by egamma** [comment] 2015-12-07 10:23
@bpasero duplicate of atom/electron#3530?

**Comment by bpasero** [comment] 2015-12-07 10:32
@egamma yes, we do not support 10.8, same as Atom.

**Closed** 2015-12-07 10:33 UTC
