### ISSUE TITLE
SSL errors after 1.5.1 update

### ISSUE THREAD

**Issue by polizz** [Microsoft/vscode#11774] opened 2016-09-09 13:58 UTC
**- VSCode Version:**
1.5.1
**- OS Version:**
El Capitan

**Steps to Reproduce:**
1. Open Vscode and message is displayed "unable to get local issuer certificate".
2. Click close and open extensions panel and message is displayed "Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting."

I had already set my strict settings in the prior versions to get around corporate firewall.

`"http.proxyStrictSSL": false`

Another person sitting next to me (with same system) also has this issue after updating to 1.5.1.

**Comment by Arithmeticae** [comment] 2016-09-09 14:15
I also have this same issue using windows 7. The circumstances are almost identical. 

It worked previously in 1.4 using `"http.proxyStrictSSL": false` however I now get the same error messages you do.

**Comment by svswaminathan** [comment] 2016-09-09 16:10
After upgrading VS Code to 1.5.1 on Mac (El Capitan), searching for any extensions in Extension Manager window, throws up the same error.

**Comment by jacob2512** [comment] 2016-09-09 18:17
Just updated to 1.5.1 and this issue popped up. Was fine in 1.4.

**Comment by gmf002** [comment] 2016-09-09 18:58
I also have this issue after upgrading to 1.5.1 on Ubuntu 16.04.  I have not tested on Windows yet.

"http.proxy" is set, and "http.proxyStrictSSL" is set to false.  I had been getting a certificate error at first, but now it returns "Marketplace returned 'ECONNREFUSED'. Please check the 'http.proxy' setting." with no certificate error.

**Comment by ramya-rao-a** [comment] 2016-09-09 19:56
@joaomoreno related to #11702 ?

**Comment by joaomoreno** [comment] 2016-09-11 17:59
Duplicate of it.

A fix will be delivered very soon in 1.5.2. Until then, you can use the [Insiders release](http://code.visualstudio.com/insiders).

**Closed** 2016-09-11 18:01 UTC
Labels: duplicate
