### ISSUE TITLE
failed to load my VS code extensions

### ISSUE THREAD

**Issue by 3bsamad0x90** [microsoft/vscode#176958] opened 2023-03-13 13:00 UTC
Type: <b>Bug</b>

Most extensions stop working suddenly

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.64GB free)|
|Process Argv|--crash-reporter-id d5ba23ff-ac3b-41ff-852d-bf45b036b60b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
laravel-model-snippets|ahi|2.0.0
laravel-extra-intellisense|ami|0.6.2
laravel-blade-additional-snippets|arb|0.0.7
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.8
postcss|css|1.0.9
laravel-goto-config|ctf|0.4.1
laravel-goto-controller|ctf|0.4.8
php-array-symbols|ctf|0.0.3
vscode-dash|dee|2.4.0
python-preview|don|0.0.4
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.10
laravel-ide-helper|geo|1.0.2
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
vscode-settings-cycler|hoo|1.0.1
kubescape|kub|0.3.3
smalise|Loy|0.0.12
php-namespace-resolver|Meh|1.1.9
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
vscode-docker|ms-|1.24.0
isort|ms-|2022.8.0
python|ms-|2023.4.1
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1200692131
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
remote-explorer|ms-|0.2.0
remote-server|ms-|1.0.0
sqltools|mtx|0.27.1
sqltools-driver-mysql|mtx|0.5.1
vetur|oct|0.37.3
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
vscode-css-peek|pra|4.2.0
laravel-helpers|raf|0.2.2
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.28
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.8
vscode-blade-formatter|shu|0.20.12
tabnine-vscode|Tab|3.6.41
highlight-matching-tag|vin|0.11.0
vscode-postcss|vun|2.0.2
vue|Wsc|1.0.26
php-debug|xde|1.32.0
json|Zai|2.0.2
material-theme|zhu|3.15.8
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30677849
vscodeenable:30660116
pythonb192cf:30669361
funwalk2:30682974
pythonms35:30680984

```

</details>

**Comment by gjsjohnmurray** [comment] 2023-03-13 13:52
Please use the `Start Extension Bisect` command to investigate.

**Comment by sandy081** [comment] 2023-03-14 17:12
> Most extensions stop working suddenly

Can you please explain more about what you mean by this? Are you seeing these extensions in the Extensions View? Are you seeing any errors?

**Comment by isidorn** [comment] 2023-03-15 11:13
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:13 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host
