### ISSUE TITLE
The color picker does not appear except when I first open a file or start VS Code.

### ISSUE THREAD

**Issue by STsa97914** [microsoft/vscode#224540] opened 2024-08-02 03:54 UTC
Type: <b>Bug</b>

The color picker does not appear except when I first open a file or start VS Code.

VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (2.92GB free)|
|Process Argv|--crash-reporter-id 9918ca5c-7bd8-49f4-8c55-b9d8c498366e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-br-tag|1na|1.0.0
html-end-tag-labels|ant|1.0.0
vscode-color-picker|Ant|0.0.4
vscode-html-css|ecm|2.0.10
vsc-material-theme|Equ|34.4.0
vsc-material-theme-icons|equ|3.6.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
live-sass|gle|6.1.2
vscode-htmlhint|HTM|1.0.5
vscode-language-pack-ja|MS-|1.92.2024073109
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
format-html-in-php|rif|1.7.0
vscode-csstree|sme|1.1.0
code-spell-checker|str|3.0.1
ayu|tea|1.0.5
vscode-icons|vsc|12.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193

```

</details>

**Comment by aiday-mar** [comment] 2024-08-05 07:37
Hi, can you please include a screen recording of the issue and a copy paste example of the code where this happens?

**Comment by Raydle** [comment] 2024-08-09 09:55
> Hi, can you please include a screen recording of the issue and a copy paste example of the code where this happens?


https://github.com/user-attachments/assets/e8075a40-d5ba-4faa-a08b-4bcfad58fb7c

**Comment by STsa97914** [comment] 2024-08-10 11:37
> > Hi, can you please include a screen recording of the issue and a copy paste example of the code where this happens?
> 
>  Video_240809135115.online-video-cutter.com.mp4

Thank you Raydle san. The exact same phenomenon is happening in my VScode.

**Comment by aimG313** [comment] 2024-08-25 14:01
I've a solution and it's not a bug I guess. Just go to the settings and search "editor.hover" and enable "Editor > Hover : Sticky" and hopefully the problem will be resolved😍

**Comment by aiday-mar** [comment] 2024-10-30 11:04
Hi thanks for filing this issue. This should be fixed with the following PR : https://github.com/microsoft/vscode/pull/232586

**Closed by aiday-mar** 2024-10-30 11:04 UTC
Labels: info-needed, editor-color-picker
