### ISSUE TITLE
Scroll bar in Python interactive pane doesn't work

### ISSUE THREAD

**Issue by amar-0** [microsoft/vscode#146715] opened 2022-04-04 10:02 UTC
Issue Type: <b>Bug</b>

```
#%%
import pandas
import numpy
df = pandas.DataFrame(numpy.random.rand(100,1))
print(df)
print(df)
```

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.28.0
python|ms-|2022.4.0
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-repositories|ms-|0.4.0

</details>

![scroll](https://user-images.githubusercontent.com/66088666/161523546-6547c331-3af8-4166-84f7-b2dba9de223a.gif)

This behaviour is new in version 1.66.0, it did not happen in version 1.65.2

**Comment by chris-steenkamp** [comment] 2022-04-06 11:56
I am experiencing the same issue with the latest version (1.66). Reverting to 1.65.2 restores the ability to scroll in the interactive window.

**Comment by chris-steenkamp** [comment] 2022-04-07 18:29
This issue is still present in the latest update (v1.66.1)

**Comment by amar-0** [comment] 2022-04-08 10:51
> This issue is still present in the latest update (v1.66.1)

Confirm that for me too v1.66.1 does not resolve this issue.
In v1.66.0 and v1.66.1 trackpad gestures for scroll does work though as a workaround.

This issue is also reported here: #147027

**Comment by Jakoviz** [comment] 2022-04-13 08:06
Insiders 1.67.0 same problem

**Comment by amar-0** [comment] 2022-04-14 12:30
> Insiders 1.67.0 same problem

Thanks for checking. Would you mind 👍 the above issue description to increase visability?

**Comment by rebornix** [comment] 2022-04-20 19:39
Duplicate of https://github.com/microsoft/vscode/issues/147027 and should be fixed in next Insiders.

**Closed by rebornix** 2022-04-20 19:39 UTC
