### ISSUE TITLE
[Accessibility][Usability]A11y_VSCode_ActivityBar_Screenreader: After expanding setting button NVDA is not announcing the instruction to select item from list

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52396] opened 2018-06-20 06:17 UTC
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],Usability

**Repro Steps:**
1. Launch VS Code while NVDA is ON.
1.Navigate to "Activity Bar" at left side of the screen after login.
2.Navigate to "SettingsButton" and click on it.
3.Observed that nvda is not reading the instructions.

**Actual:**
NVDA is reading it only as menu submenu but not reading the instructions that how to navigate/select/access the item from the list.

**Expected:**
NVDA should read it like select the item from list by using arrow keys.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets.
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
User will not unserstand that any list of item is display also don't understand how to select item from list.

**Attachment For Reference:**
[[Accessibility][Usability]A11y_VSCode_ActivityBar_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2118067/Accessibility.Usability.A11y_VSCode_ActivityBar_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment] 2018-06-20 11:12
Duplicate of #52385

**Closed** 2018-06-20 11:12 UTC
Labels: *duplicate, accessibility
