### ISSUE TITLE
this build is crashing frequently. 

### ISSUE THREAD

**Issue by roopkt** [Microsoft/vscode#34323] opened 2017-09-13 20:27 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
git-easy|bib|1.9.1
path-intellisense|chr|1.4.2
gitlens|eam|5.0.0
tslint|eg2|1.0.4
vscode-great-icons|emm|2.1.16
git-project-manager|fel|1.4.0
node-module-intellisense|lei|1.4.0
PowerShell|ms-|1.4.3
vs-keybindings|ms-|0.1.7
vscode-run-git-difftool|nar|0.0.4
material-icon-theme|PKi|2.2.1
rxjs-snippets|pko|0.0.2
typescript-hero|rbb|1.4.1
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
git-common-commands-suite|sam|0.2.2
move-ts|str|1.5.0

---

Steps to Reproduce:

1. open 3-4 terminals 
2. in one run npm run test, in another run npm run build, while running change code sometime it crashing

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment] 2017-09-14 06:41
What build?

**Comment by roopkt** [comment] 2017-09-15 14:22
![capture](https://user-images.githubusercontent.com/330383/30486811-a1733d30-99ff-11e7-9135-5693f183fae6.PNG)


today morning again it happened I was about to change my code while I am runing npm TEST in terminal It crashed and  "The window has crashed" dialog came up.

**Comment by joaomoreno** [comment] 2017-09-15 14:52
Can you show me a screenshot of the window has crashed dialog?

@Tyriar have you seen this related to the Terminal?

**Comment by roopkt** [comment] 2017-09-15 16:32
![capture](https://user-images.githubusercontent.com/330383/30493386-edcf397e-9a11-11e7-96db-52da1f7271de.PNG)

Just crashed again

**Comment by jkristia** [comment] 2017-09-15 16:57
I see the same when run 'tsc -w' and 'live-server' using integrated terminals. I do not see any crash when using external terminals. Is there a log file somewhere which can be of any help ?

**Comment by Tyriar** [comment] 2017-09-15 17:18
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/34039, please see if this reproduces in v1.16.1.

**Closed by Tyriar** 2017-09-15 17:18 UTC
Labels: needs more info, new release

**Comment by roopkt** [comment] 2017-09-15 17:59
In issue #34039 they typed \\\ in terminal however, I did not type Type \\\\\\\\\\\\\\\\\\\\\\\\\\ in my terminal. In my case it is crashing while my tests are runing and I change my code. It is not crashing everytime I change my code. It is occasionally crashing I went back to previous version and so far no crash.

**Comment by jkristia** [comment] 2017-09-15 18:25
I have been running 1.16.1 for an hour now with no crash. I have 3 integrated terminals. run 'tsc -w' in one, 'live-server' in another and use the third for git commands. So far so good.

**Comment by Tyriar** [comment] 2017-09-28 16:07
It's actually https://github.com/Microsoft/vscode/issues/34301 which got pushed to v1.17
