### ISSUE TITLE
Keyboard locks after a certain sequence

### ISSUE THREAD

**Issue by saveriomiroddi** [microsoft/vscode#98559] opened 2020-05-26 07:55 UTC
- VSCode Version: 1.45.1-1589445302 and 1.46.0-1590182489 (insiders)
- OS Version: Ubuntu MATE 20.04

Steps to Reproduce:

1. Save [this](https://raw.githubusercontent.com/saveriomiroddi/personal_notes/f6af9dce9cebe479c9f17d80a5c758746cb68dd7/debian_packaging_ppas.md) file locally (it happens also with other files; this is a file I've been able to reproduce it consistently with)
2. Launch VSC
3. Open the file above
4. Tap Ctrl+K, V
5. Now, perform the following sequence without leaving the finger from Ctrl: 
    - Ctrl + 1, Ctrl + End, Ctrl + 2, Ctrl + W
6. The keyboard is now locked! Tapping any key/combination doesn't have any effect.

I don't know if the "without leaving the finger" part is voodoo or it's real, but reproducing the bug consistently has been hell enough :-)

With the above procedure, I can reproduce it almost all the times with at most 3 attempts. If the bug doesn't happen, close the preview, move the file cursor to the top of the file, and restart from 4.

Does this issue occur when all extensions are disabled?: Yes. I've also tested with a wiped configuration directory.

**Comment by alexdima** [comment] 2020-06-01 11:44
By default, `ctrl+k v` is bound to `markdown.showPreviewToSide`, so I believe this is about keybindings now working when the webview has focus.

**Comment by mjbvz** [comment] 2020-06-02 03:44
Also related to #97992

**Comment by Cacique99** [comment] 2020-06-08 12:05
Hi, I would like to look further into this. Is there anyone else working on it?

**Comment by mjbvz** [comment] 2020-11-05 21:48
Duplicate of #97992

Also see Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1144999

**Closed by mjbvz** 2020-11-05 21:48 UTC
Labels: bug, help wanted, webview
