### ISSUE TITLE
Screen doesn't use whole area to show markdown preview

### ISSUE THREAD

**Issue by mkiuchi** [Microsoft/vscode#15992] opened 2016-11-24 01:18 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.3|

---

Steps to Reproduce:

1. select "Preview" of Markdown(or type Ctrl+Alt+V)
2. Screen doesn't use whole area to show preview.(see attachment)
![screenshot](https://cloud.githubusercontent.com/assets/604096/20583661/416ecc8c-b22f-11e6-8bd9-3af423d14d85.png)

**Comment by jrieken** [comment] 2016-11-24 08:34
dupe of #5745

**Closed by jrieken** 2016-11-24 08:34 UTC
Labels: duplicate
