### ISSUE TITLE
Visual-Studio-Code organization owns first party authentication but looks very sketchy

### ISSUE THREAD

**Issue by sparr** [microsoft/vscode#158980] opened 2022-08-23 20:55 UTC
Various first and third party extensions for vscode use the GitHub authentication provider. When attempting to use those extensions, the user is presented with a prompt to authenticate via GitHub in a web browser.

![image](https://user-images.githubusercontent.com/121299/186259153-1ef2b16c-38f5-4900-9aea-412a3a52149e.png)

The info at the bottom of this interface is mildly reassuring, but everything else is not.

The link to "by [Visual-Studio-Code](https://github.com/Visual-Studio-Code)" leads to an empty organization. No repositories, no members, no projects, just a couple of links to twitter and the vscode site. This is exactly what you'd see if a malicious actor had created a phishing organization and spent 30 seconds setting it up, with a name such as VisualStudio-Code (which is available right now).

The first Google result for `"GitHub for VS Code"` is https://vscode-auth.github.com/ which is the opposite of informative. Fortunately it's on the github.com domain, but it still looks like something an outside attacker might have hot linked to in the middle of an otherwise secure authentication process.

This situation would be a lot less concerning if this authentication flow was owned by https://github.com/microsoft, or at the very least any other organization that owns some legitimate Github or VSCode repos.

**Comment by TylerLeonhardt** [comment] 2022-08-26 17:37
Thanks for the feedback! I'm in chat with GitHub folks to try and make this look less sketchy... here's the plan.

1. First off, we asked if `Visual-Studio-Code` could be `Visual Studio Code` and they've done that:
![image](https://user-images.githubusercontent.com/2644648/186959422-c2f5e43a-8ead-40b8-9085-f2d4f45b8729.png)

2. I'm also working with the GitHub folks to get this app "verified" (I don't exactly know what that will look like... but it sounds good 😅 )

3. I will try to find some time to make the Org README look nice so it doesn't just appear empty.

The root of the problem is
1. we don't wanna move the `GitHub for VS Code` app under the Microsoft org because that org is _huge_ and not owned by the vscode team
2. we don't wanna move `microsoft/vscode` to `Visual-Studio-Code/vscode` as that looks silly...
3. GH doesn't have a way to have an app assigned to a specific repo

**Comment by sparr** [comment] 2022-08-26 19:49
It would lend credibility for some github (or even microsoft) folks to be public members of the Visual-Studio-Code org

**Comment by TylerLeonhardt** [comment] 2022-08-26 19:52
@sparr do you not see our faces on your end?:
![image](https://user-images.githubusercontent.com/2644648/186980823-151b76aa-7d86-4421-bf2b-816540d9198a.png)

All of those folks there work on the VS Code team.

**Comment by sparr** [comment] 2022-08-26 20:04
![image](https://user-images.githubusercontent.com/121299/186982787-dc348b98-f33d-4a9d-a2bb-ab8b51c3b9a1.png)

**Comment by sparr** [comment] 2022-08-26 20:11
> 2. we don't wanna move `microsoft/vscode` to `Visual-Studio-Code/vscode` as that looks silly...

Why do you think this looks silly? Sure, it's a little worse than `vscode/vscode` but Victor Salazar beat you to the punch there. Having an org with the same/similar name as their largest repo is not at all uncommon. `vuejs/vue`, 'tensorflow/tensorflow', `symfony/symfony`, `angular/angular`, 'golang/go', 'flutter/flutter', 'nodejs/node', ...

**Comment by TylerLeonhardt** [comment] 2022-08-26 20:54
We also get a lot of governance & security stuff for free for being in the Microsoft Org - something we would need to hand roll ourselves in our own Org. Moving repos over to Visual-Studio-Code is not something we want to do right now.

btw, I asked GitHub about the Members not showing up so they can provide guidance.

**Comment by sparr** [comment] 2022-08-29 20:51
The org now has 4 publicly visible members, including three also in the Microsoft org. That's a good small step in the right direction!

**Comment by TylerLeonhardt** [comment] 2022-08-29 20:54
@sparr you beat me to the update :) unfortunately, GitHub can't let me unilaterally make everyone public... so I have to wait for folks to do it manually... but yes... progress.

**Comment by TylerLeonhardt** [comment] 2022-12-08 05:03
We are verified 😎 

![Image](https://user-images.githubusercontent.com/2644648/206360924-ceb3e8e5-fe87-42a9-a81b-c6adffb9110f.png)

I think this is enough for now. At some point, maybe we create a small org README, but I don't think it's absolutely needed.

**Closed by TylerLeonhardt** 2022-12-08 05:03 UTC
Labels: feature-request, authentication

**Comment by TylerLeonhardt** [comment] 2023-01-23 17:43
Verification:
* Open incognito Window
* Go to: https://github.com/Visual-Studio-Code
* See that it's verified and also has other info that makes it look legit

**Comment by sparr** [comment] 2023-01-23 20:11
Verified is good. 5 people... Good, I guess, although still a bit sketchy given the relative size of the orgs involved. One repo (https://github.com/Visual-Studio-Code/.github) containing just a shell of one file, still very sketchy.
