### ISSUE TITLE
Error: ENOENT: no such file or directory, open windowsShellHelper.js

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#33242] opened 2017-08-28 08:26 UTC
- VSCode Version: d30825f323a7f77e17d25b212fef6440e73fdc14
- OS Version: windows 10 64x

```
Uncaught (in promise) Object
detail: Error: ENOENT: no such file or directory, open 'f:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\electron-browser\windowsShellHelper.js'
code: "ENOENT"
errno: -4058
path: "f:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\electron-browser\windowsShellHelper.js"
syscall: "open"
message: "ENOENT: no such file or directory, open 'f:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\electron-browser\windowsShellHelper.js'"
stack: "
Error: ENOENT: no such file or directory, open 'f:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\terminal\electron-browser\windowsShellHelper.js'"
errorCode: "load"
moduleId: "vs/workbench/parts/terminal/electron-browser/windowsShellHelper"
neededBy: Array(1)
0: "===anonymous8==="
```

![image](https://user-images.githubusercontent.com/461084/29765335-2b3f1794-8bb1-11e7-8c7a-e5bdc9a4063a.png)

Steps to Reproduce:

1. Updated VSCode
2. Started the editor

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-08-29 18:53
Duplicate of https://github.com/Microsoft/vscode/issues/33308 - fix coming soon

**Closed by Tyriar** 2017-08-29 18:53 UTC
Labels: integrated-terminal
