### ISSUE TITLE
highlighting problems

### ISSUE THREAD

**Issue by AsukaSoryu0** [microsoft/vscode#165578] opened 2022-11-05 04:54 UTC
Type: <b>Feature Request</b>

Line 18 and line 19 have different name highlighting colors
Other words do not have this problem as attributes of obj
Color Theme is vscode Dark+
This is not a problem in other theme

vscode Dark+
![image](https://user-images.githubusercontent.com/86198114/200101730-0be17c90-644e-4e72-8483-7ea57b159394.png)

one dark pro
![image](https://user-images.githubusercontent.com/86198114/200101823-aceb159d-4108-4fef-ad80-ce09c8b851d2.png)

vscode Dark+
![image](https://user-images.githubusercontent.com/86198114/200101743-65996535-2200-476b-904d-b977b5b9a73f.png)

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const obj = {
            name: 'Mars',
            id: 1001
        }

        const { name: name, id: id } = obj
        console.log(name, id) // mars 1001
    </script>
</body>

</html>
```
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by GauravB159** [comment] 2022-11-05 05:16
I think the incorrect highlighting is with `id`, not `name`. Any variable name other than `id` renders using the `mtk9` class while `id` renders using the `mtk18` class. I'm not sure if that is intended behavior or a bug though.

**Comment by IllusionMH** [comment] 2022-11-05 23:13
It might be related to fact that `name` present in global scope (and assume that "one dark pro" either doesn't support semantic highlights or uses same color in this case). This is speculation as I can't verify this.

Doos it have same colors If you disable semantic highlight?

**Comment by aeschli** [comment] 2022-11-07 08:56
![image](https://user-images.githubusercontent.com/6461412/200267950-a844ca5b-1766-433c-addf-88acea244b6b.png)

The semantic token modifier `defaultLibrary` seems wrong. Should be moved to TypeScript

**Comment by mjbvz** [comment] 2022-11-09 03:04
Yes this is expected (but not good ux IMO). The root cause is that `name` is a global dom variable. If you enable `//@ts-check` in the code, you'll also see an error that makes this a little more obvious:

![Screen Shot 2022-11-08 at 7 03 44 PM](https://user-images.githubusercontent.com/12821956/200727960-ae95fd93-2275-4048-bb7f-d5f862198698.png)

Closing as a duplicate of https://github.com/microsoft/TypeScript/issues/39534

**Closed by mjbvz** 2022-11-09 03:04 UTC
