### ISSUE TITLE
Make multi line snippets easier

### ISSUE THREAD

**Issue by Circuit8** [Microsoft/vscode#66636] opened 2019-01-17 00:28 UTC
Instead of this:
```JSON
"body":[
  "for(int i = 0; i < 3; i++)",
  "{",
  "   //code goes here",
  "}"
],
```

It would be way easier to write like this (the way atom does it):
```JSON
"body": """
  for(int i = 0; i < 3; i++)
  {
      //code goes here
  }
"""
```

The reason I bring this up is I'm trying to add a snippet for a vue component scaffold, which is very long:
```Vue
<template>
  <div>
  </div>
</template>

<script>
// import { mapActions, mapGetters } from "vuex"

export default {
  components: {},

  props: {},

  data(){
    return {}
  },

  methods: {},

  computed: {},

  watch: {},
}
</script>

<style lang="scss" scoped>
</style>
```

**Comment by usernamehw** [comment] 2019-01-17 00:47
Well, that's just not a valid json.

Related by difficulty of making long snippets #26706.

**Comment by Circuit8** [comment] 2019-01-17 00:49
Yes perhaps we could switch to whichever format Atom is currently using? Although to be honest if we had an easy way to select text and automatically convert to a snippet that would solve this issue

**Comment by jrieken** [comment] 2019-01-17 03:09
closing this as duplicate of https://github.com/Microsoft/vscode/issues/25661. While that's currently marked as out-of-scope we still collect up-votes for it.

**Closed** 2019-01-17 03:09 UTC
Labels: *duplicate, snippets
