### ISSUE TITLE
diff: Collapse unchanged fragments

### ISSUE THREAD

**Issue by vaxXxa** [microsoft/vscode#39138] opened 2017-11-25 19:04 UTC
Please, add new feature for diff explorer (like IDEA does) – command and icon with this action:

**Collapse unchanged fragments**
Click this button to collapse all unchanged fragments in both files. The amount of non-collapsible unchanged lines is configurable in settings.

**Comment by joaomoreno** [comment] 2017-11-27 07:59
What does this feature do? Can you describe it in a little bit more detail?

**Comment by vaxXxa** [comment] 2017-11-27 10:48
When I make few changes in very large file and then try to check git diff from VSCode panel – I don't want to see 500 line of my code, which do not changed.

Just show me my diff + some context (10 line up and 10 line down)

Compare the same diff with and without this option:

![image](https://user-images.githubusercontent.com/139175/33263076-22662f2e-d371-11e7-99bf-59a6436402a9.png)

![image](https://user-images.githubusercontent.com/139175/33263088-28e95704-d371-11e7-98a4-2ca64170ee2b.png)

**Comment by ShadowXVII** [comment] 2018-03-27 06:29
I know this feature as "Hide Unchanged Lines".

Simply hides unchanged lines in a diff to better highlight the important pieces (the changes). Sometimes a few lines before and after remain visible for context. A pretty common feature for diff tools.

**Comment by nexcvon** [comment] 2018-04-12 09:00
Duplicate of #3562.

**Comment by hazrpg** [comment] 2019-05-31 10:30
I would like to see this too! So very useful.

**Comment by farzadso** [comment] 2019-06-15 04:51
Any updates on this?

**Comment by alexandrudima** [comment] 2019-10-11 21:04
Duplicate of #3562

**Closed by alexandrudima** 2019-10-11 21:04 UTC
Labels: diff-editor, feature-request
