### ISSUE TITLE
Change horizontal scrolling to scroll the window

### ISSUE THREAD

**Issue by aroemen** [Microsoft/vscode#1200] opened 2015-12-11 15:41 UTC
Currently when scrolling horizontally with a touchpad it moves the position of the cursor. Can there be an option added to scroll the window verses just moving the cursor?

**Comment by egamma** [comment] 2015-12-11 19:44
fyi: @alexandrudima

**Comment by alexandrudima** [comment] 2015-12-12 10:59
@aroemen What OS are you using and what laptop brand. Sometimes, the trackpad gestures are implemented in funny ways (e.g. they send ArrowLeft/ArrowRight key down events instead of scroll events).

**Comment by aroemen** [comment] 2015-12-15 23:09
@alexandrudima I have it happening on multiple computers and OSes. One is a HP running Windows 10 and the other is an IBM running Windows 7

**Comment by alexandrudima** [comment] 2015-12-16 14:51
my Lenovo's w530 trackpad scrolls horizontally instead of moving cursor.

@aroemen What happens if you open a webpage with a native textarea with a horizontal scrollbar in Chrome and use the horizontal scroll gesture? I've made such an example at https://jsfiddle.net/n5ego3fs/

Does Chrome move the cursor too or just scrolls? What do other browsers do?

**Comment by aroemen** [comment] 2015-12-16 17:04
@alexandrudima in Chrome, it is scrolling the viewing area. Here is a screencast showing the differences between jsfiddle page and vscode.http://screencast.com/t/CFbXK1wv

**Comment by aroemen** [comment] 2016-01-05 19:44
@alexandrudima - horizontal scrolling appears to be working now after updating.

**Comment by saborrie** [comment] 2016-07-14 14:34
This issue is not resolved.

**Comment by jflheureux** [comment] 2016-07-14 22:06
I have this issue too in version 1.3.1 on Windows 8.1 on a Lenovo T44p laptop. The jsFiddle textarea scrolls correctly while VSCode doesn't.

To avoid this issue, I need to use the Softwrap extension and have it activated all the time.

**Comment by alexandrudima** [comment] 2016-07-15 08:30
@jflheureux Does scrolling in Chrome in the editor at https://microsoft.github.io/monaco-editor/ work for you? If yes, then it might be only a matter of time until we catch up (we are on Chromium 49) and Chrome is at 51.

**Comment by jimfrenette** [comment] 2016-12-28 14:46
I have the same issue with horizontal scrolling. when the curser is moved to the right with the arrow key on a single line of code that extends beyond the right of the viewport, the screen does not follow it. I had to install and enable the Softwrap extension as a workaround per @jflheureux 

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by Odame** [comment] 2017-01-08 16:52
I have the same issue horizontal scrolling.
Sometimes (quite seldom and I can't reproduce the behaviour), the window is rather scrolled. But most of the time, it is the cursor that is moved, even if the mouse pointer is on another editor in vscode.

**Comment by stereokai** [comment] 2017-03-08 02:20
This issue is NOT resolved. I am reporting identical symptoms. Tried scrolling in Chrome in the editor at https://microsoft.github.io/monaco-editor/ and over there it reacts as I would expect - scrolling the viewport and not moving the cursor.

VSCode version: 1.10.1
OS version: Microsoft Windows [Version 10.0.14393.693]

**Comment by Noitidart** [comment] 2017-03-29 06:37
I use the "Home" and "End" keys a lot to move cursor position. When I do this, the window scroll position does not change, and my cursor goes out of view. I have to press the Left or Right arrow to get window scroll to bring cursor into viewport.

**Comment by alexandrudima** [comment] 2017-11-24 14:33
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Closed by alexandrudima** 2017-11-24 14:33 UTC
Labels: editor, trackpad/scroll, upstream

**Comment by stereokai** [comment] 2017-11-27 09:48
@alexandrudima can you share with the community the Chromium bug?

**Comment by alexandrudima** [comment] 2017-11-27 10:36
@stereokai I cannot reproduce this behaviour on my laptop. That is why I ask that someone who can reproduce create an issue with Chromium.

**Comment by stereokai** [comment] 2017-11-27 14:43
I don't mean to be rude, but I want to ask you - what makes you think this is a Chromium bug? The text editor is a JS implementation after all - not a native text area

**Comment by jongood01** [comment] 2017-11-29 08:21
Same issue and the monaco editor scrolls horizontally no problem

**Comment by alexandrudima** [comment] 2017-11-29 08:50
@stereokai Because of the code we wrote where the cursor moves left or right when we receive a `keydown` event for arrow left or arrow right and not when we receive a `scroll` or `mousewheel` event (which are the events a trackpad should generate).

Please build VSCode locally with the following diff in `/src/vs/platform/keybinding/common/abstractKeybindingService.ts`:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/5047891/33366057-70a355f2-d4ea-11e7-80f6-30ca0b2bc071.png">

This will show on your machine in the developer console what kind of `keydown` event (most likely arrow left / arrow right) is produced when using the trackpad.

**Comment by stereokai** [comment] 2017-11-29 11:40
@alexandrudima I'll give that a try. Perhaps there *is* something to do about it in VSCode, because the bug is not reproduced in [Monaco itself](https://microsoft.github.io/monaco-editor/).

**Comment by alexandrudima** [comment] 2017-11-30 09:55
@stereokai IMHO 2 possibilities:
1. VS Code is on Chromium v.58, while Chrome Stable is on Chromium v.62
2. The trackpad driver does something differently if the foreground window belongs to a process with image name "Chrome.exe" vs a process with image name "Code.exe".

You can try renaming "Code.exe" to "Chrome.exe" as a crazy check for 2. As for 1., we update regularly to keep up with newer Electron releases.

---

But there really is no code change I can possibly do, because 100% the same code works correctly via the Monaco Editor in Chrome...

**Comment by dubyajaysmith** [comment] 2017-12-01 06:02
> You can try renaming "Code.exe" to "Chrome.exe" as a crazy check for 2.

That worked here. For me, it wasn't a trackpad but an mx master horizontal scroll wheel.

**Comment by Noitidart** [comment] 2017-12-01 06:23
I use Microsoft Sculpt which has a horizontal scroll wheel. It sends a bunch of left/right arrow keys.
