### ISSUE TITLE
Add syntax highlighting for new CSS units.

### ISSUE THREAD

**Issue by romainmenke** [microsoft/vscode#170769] opened 2023-01-07 17:35 UTC
I would like to add new units to the CSS syntax highlighting.

Normally I would open a pull request here : https://github.com/atom/language-css
This repository has been archived but the dependency on this repo still exists for CSS in VSCode.

How do I submit a patch for the new CSS units?

related : https://github.com/microsoft/vscode/issues/169873
related : https://github.com/microsoft/vscode-css-languageservice/pull/324

pull request in this repo : https://github.com/microsoft/vscode/pull/170781

**Comment by alexr00** [comment] 2023-01-11 12:06
Closing as a duplicate of https://github.com/microsoft/vscode/issues/169873

**Closed by alexr00** 2023-01-11 12:06 UTC
Labels: *duplicate
