### ISSUE TITLE
WebviewPanel.Reveal() moves the panel to current active view column

### ISSUE THREAD

**Issue by sajithpt** [microsoft/vscode#141089] opened 2022-01-20 17:23 UTC
I am using vscode.WebviewPanel.Reveal this way-

panel.Reveal(panel.viewColumn, false);

to make an already existing panel the active window without changing its viewColumn. This used to work fine in vscode 1.59.1. But after updating to vscode 1.63, the panel becomes active but it moves to a different column.

What is the right way to just make the panel active without changing its viewColumn?

**Comment by mjbvz** [comment] 2022-01-21 21:58
Duplicate of #138914

**Closed by mjbvz** 2022-01-21 21:58 UTC
