### ISSUE TITLE
Auto wrapping too much when using non-monospace font

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#19134] opened 2017-01-24 10:08 UTC
Testing #19061 

Have the following snippet in an editor buffer, with `editor.fontFamily` set to `Arial` and `editor.wrappingColumn` set to `0`.

```js
/**
 * @param {Array<string>} [plugins=['defaults']] - plugins to enables @param {Array<string>} [plugins=['defaults']] - plugins to enables @param {Array<string>} [plugins=['defaults']] - plugins to enables @param {Array<string>} [plugins=['üdefaults']] - plugins to enables plugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enablesplugins to enables
 */
define(['modules/interface'], function (i) {
  console.log(i);
})
```

You'll notice the editor is wrapping more than it should:

![image](https://cloud.githubusercontent.com/assets/22350/22242896/691f6db0-e225-11e6-84d5-0347cd4b3fd6.png)

**Comment by alexandrudima** [comment] 2017-01-24 10:38
Duplicate of  #2654

**Closed by alexandrudima** 2017-01-24 10:38 UTC
