### ISSUE TITLE
VS Code auto highlights entire blocks of code seemingly randomly

### ISSUE THREAD

**Issue by jasondotlee** [microsoft/vscode#119702] opened 2021-03-23 20:16 UTC
Issue Type: <b>Bug</b>

While clicking into a document, large swathes of code/text will be highlighted. It looks like the text is selected at first glance, but you can faintly see things that are actually selected inside. Clicking off onto an area outside of the highlighted areas sometimes will make it go away, but then it randomly comes back. Started happening right after recent update. Unclear if this is some setting that got toggled somehow. 
![Screen Shot 2021-03-23 at 4 16 14 PM](https://user-images.githubusercontent.com/52800493/112212241-1e80bf80-8bf3-11eb-9ce8-e2ccb70989b9.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 7|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv|. --crash-reporter-id 9189746a-6478-4b03-8a54-4b4ab0cb6bde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
console-log|dot|0.6.2
prettier-vscode|esb|6.3.1
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.163.2
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.4018
svelte-vscode|sve|104.8.0
gitblame|wad|6.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-03-23 20:28
Does this also happen after you run the command to reload with all extensions temporarily disabled?

**Comment by jasondotlee** [comment] 2021-03-23 20:43
> Does this also happen after you run the command to reload with all extensions temporarily disabled?

Yes it persists after running that command. I'm seeing a pattern where it is specifically doing this for string text within block quotes and snake cased variables, which makes me now think that this is actually likely a setting and not a bug.

**Comment by alexdima** [comment] 2021-03-24 15:26
> I'm seeing a pattern where it is specifically doing this for string text within block quotes

This sounds like something the TS language service changed recently.

**Comment by mjbvz** [comment] 2021-03-24 18:46
Duplicate of https://github.com/microsoft/TypeScript/issues/43292

**Closed by mjbvz** 2021-03-24 18:46 UTC
