### ISSUE TITLE
Overlapping dropdown on UI editor

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#172213] opened 2023-01-24 17:24 UTC
testing https://github.com/microsoft/vscode/issues/172075

Seems like the rendering isn't right for this dropdown, not sure if it is related to adding the new setting or the setup of the UI editor.
<img width="899" alt="Screenshot 2023-01-24 at 9 22 00 AM" src="https://user-images.githubusercontent.com/26030610/214363942-55335414-3be1-4312-bbed-6985bd334169.png">

**Comment by gjsjohnmurray** [comment] 2023-01-24 19:49
A problem of this type was fixed very recently. Please confirm you are running today's Insiders or later.

**Comment by rzhao271** [comment] 2023-01-24 22:41
Duplicate of https://github.com/microsoft/vscode/issues/171804

**Closed by rzhao271** 2023-01-24 22:41 UTC
Labels: info-needed
