### ISSUE TITLE
Syntax Error => Arrow functions

### ISSUE THREAD

**Issue by marcelaraujo** [Microsoft/vscode#4289] opened 2016-03-16 04:51 UTC
- VSCode Version: 0.10.11
- OS Version: Mac OS X 10.10.5

Steps to Reproduce:

1. Create a new javascript file and add this source

```
import React from 'react';

export default class Item extends React.Component {
    update(e) {
        console.log(e.target.value);
    }
    
    test = (e) => {
        console.log(e.target.value);
    }
    
    render() {
        return <span>{this.props.name}<br/>
<input type="text" onChange={(e) => this.update(e)} /><br/>
<input type="text" onChange={this.test} />
</span>;
    }
}
```
2. IDE show me as syntax error.
<img width="1140" alt="screen shot 2016-03-16 at 1 49 48 am" src="https://cloud.githubusercontent.com/assets/421794/13802334/75c0345e-eb19-11e5-89bd-c74837b1eba8.png">

**Comment by egamma** [comment] 2016-03-16 13:18
duplicate of #3804 

@marcelaraujo the next update will support to disable the built-in JS validation and the recommendation is to use eslint for validation.

**Closed by egamma** 2016-03-16 13:18 UTC

**Comment by marcelaraujo** [comment] 2016-03-16 13:31
Thanks.
