### ISSUE TITLE
Ctrl + click throught scss file path doesn´t work 

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#66984] opened 2019-01-23 12:57 UTC
Doesnt work when scss file is in some folder (bad recognition in nested folders)
See video pls (you will see the difference)

http://bit.ly/2HrJ6cx

**Comment by octref** [comment] 2019-01-23 20:56
Duplicate of #58204.

**Closed by octref** 2019-01-23 20:56 UTC
