### ISSUE TITLE
Terminal window is not useful

### ISSUE THREAD

**Issue by fsefacan** [Microsoft/vscode#43821] opened 2018-02-16 11:37 UTC
- VSCode Version: 1.20.1
- OS Version: Win 10 Pro

Hi,
Using a tab instead of a dropdown on the terminal window might make more sense.
In addition, the directory name can be shown on the tabs.

**Comment by egamma** [comment] 2018-02-16 11:57
Duplicate of https://github.com/Microsoft/vscode/issues/10546

**Closed** 2018-02-16 11:57 UTC
Labels: *duplicate, new release
