### ISSUE TITLE
为什么不支持文件多选择和多项目查看

### ISSUE THREAD

**Issue by xiashu** [Microsoft/vscode#10038] opened 2016-08-02 14:30 UTC
- VSCode Version: 1.3
- OS Version: win7

1，  vscode 不能在一个窗口内创建多个项目，这个功能比较缺失，在某一些项目带来很不便利，希望微软重视这个基础开发的问题。把编辑器设计多树的功能。

2，文件多选择也不支持，这样导致不能删除多个文件，以及不能做文件多操作的功能

3，html 开发功能比较薄弱，使用起来不够智能，比起其他编辑器都偏弱一点。对括号内的联想提示比较薄弱一点

**Comment by aeschli** [comment] 2016-08-02 15:34
@rebornix Peng, can you help translating?

**Comment by glen-84** [comment] 2016-08-02 22:19
1. [Add support for opening multiple project folders in same window](https://github.com/Microsoft/vscode/issues/396)
2. [Implement multi-select in left-panel file tree](https://github.com/Microsoft/vscode/issues/1023)
3. (not sure exactly which HTML development features he/she is referring to)

(I don't speak Chinese, I just used Google Translate =)

**Comment by rebornix** [comment] 2016-08-03 02:01
Thanks @glen-84 you are doing  great with the translation!

In addition to @glen-84 's comment, the third one is duplicate of #7008. I'm going to close this issue as all problems @xiashu mentioned are already tracked.

**Closed by rebornix** 2016-08-03 02:01 UTC
Labels: needs more info
