### ISSUE TITLE
Typescript Intellisense not working anymore

### ISSUE THREAD

**Issue by digaobarbosa** [Microsoft/vscode#15936] opened 2016-11-23 03:04 UTC
Since 1.7.1 my Typecript Intellisense is not working anymore. VSCode only gives me suggestions based on content, nothing derived from types. And it does not warn about compilation errors during file editing. I have to run the typescript compiler manually to see it.

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Handlebars|andrejunges|0.2.0|
|python|donjayamanne|0.4.2|
|typescript-hero|rbbit|0.10.1|
|java|redhat|0.0.6|

---

Steps to Reproduce:

1.
2.

**Comment by lafe** [comment] 2016-11-23 07:37
Just a quick tip: You might want to enable the TypeScript log so that it tracks errors in the TypeScript Service that is used by Visual Studio Code to power the TypeScript language features. On Windows, you have to set the "TSS_LOG" environment variable to "-level verbose" and I guess that it will be similar on Linux. Afterwards, the log might give you a hint what went wrong. There were already several instances (see #15238) where entries in the tsconfig.json had caused issues for newer versions of the TS Service.

**Comment by waderyan** [comment] 2016-11-28 20:25
@digaobarbosa thank you for opening an issue. Can you share your workspace and a list of steps to reproduce?

**Comment by mjbvz** [comment] 2016-12-05 19:10
Closing since we need more info.  This could perhaps be related to #15963

@digaobarbosa Please share some information about your workspace so that we can investigate this

**Closed by mjbvz** 2016-12-05 19:10 UTC
Labels: intellisense, needs more info
