### ISSUE TITLE
YAML user snippits not working in latest release

### ISSUE THREAD

**Issue by harrington101** [Microsoft/vscode#27573] opened 2017-05-30 14:10 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:

1. Create a YAML user snippet
2. Open a new file and save as a .yaml file.
3. type the prefix.
4. Nothing happens.

**Comment by jrieken** [comment] 2017-05-31 09:17
dupe of

**Closed** 2017-05-31 09:17 UTC
