### ISSUE TITLE
Native Notebooks - Dragging and dropping multiple cells doesn't always have same result

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#133917] opened 2021-09-28 00:35 UTC
- VS Code Version: 1.61.0-insider
- OS Version: Windows

Steps to Reproduce:

1. Select multiple cells with a gap
2. Ctrl + Z to put them back
3. Move cells again to same place

There is a different result when moving cells. In the recording below, the first time moves the last two cells and not the first (I believe related to #133915) and remains in selected mode. The second time, it moves the first cell and is no longer in selected mode. 

![moving cell inconsistency](https://user-images.githubusercontent.com/19276747/135003294-f3884448-b0e7-4e04-b11b-d463abc8e862.gif)

**Comment by roblourens** [comment] 2021-11-04 03:15
This is a dupe of #133915 (since we only drag consecutive chunks of cells). Can discuss in #133915 if needed

**Closed by roblourens** 2021-11-04 03:15 UTC
Labels: bug, notebook-dnd, nb-golden
