### ISSUE TITLE
"Open editors" can't be hidden when no folder is opened

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#17253] opened 2016-12-15 06:43 UTC
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new window without opening a folder
2. Set "explorer.openEditors.visible" to 0

Expected:
"Open editors" hidden in explorer.

Actual:
One open editor is shown (same as "explorer.openEditors.visible" being set to 1).

**Comment by kieferrm** [comment] 2016-12-16 01:23
Duplicate of #9509.

**Closed by kieferrm** 2016-12-16 01:23 UTC
