### ISSUE TITLE
Running command works in external terminal (cmd) but not in integrated terminal. 

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode#40453] opened 2017-12-18 19:53 UTC
- VSCode Version: 1.19.0
- OS Version: Windows 10 build 16299

Steps to Reproduce:

1. Open a terminal (cmd, powershell) in vs code. 
2. xelatex cv.tex
Output:

```C:\Users\eriha\OneDrive\Documents\Jobbsøknad\resume4>xelatex cv.tex
This is XeTeX, Version 3.14159265-2.6-0.99998 (MiKTeX 2.9.6500 64-bit)
entering extended mode
(cv.tex
LaTeX2e <2017-04-15>
Babel <3.14> and hyphenation patterns for 75 language(s) loaded.
(fr
Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/eriha/AppData/Local/MiKTeX/2.9/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.

C:\Users\eriha\OneDrive\Documents\Jobbsøknad\resume4>
``` 

Reproduces without extensions: Yes

I'm trying to compile a latex resumé, but the integrated terminal seems to fail, while doing the same task in an external terminal seems to work. I'm not sure how to troubleshoot this.

**Comment by cleidigh** [comment] 2017-12-18 22:24
@erihanse 
Did you look at the log and get any useful information there?  Perhaps you could post relevant output.
One and to look at:  Does the latex program have everything it needs in the environment?

**Comment by erihanse** [comment] 2017-12-18 22:29
Thank you for your response. 
Here's the output from xelatex.log. 
```
2017-12-18 23:27:20,607+0100 INFO  xelatex - starting with command line: xelatex cv.tex
2017-12-18 23:27:20,612+0100 INFO  xelatex - allowing known shell commands
2017-12-18 23:27:20,613+0100 INFO  xelatex - enabling input (output) from (to) processes
2017-12-18 23:27:20,720+0100 FATAL xelatex - No error
2017-12-18 23:27:20,720+0100 FATAL xelatex - Info: 
2017-12-18 23:27:20,720+0100 FATAL xelatex - Source: libraries\miktex\texandfriends\include\miktex\c4p\C4P.h
2017-12-18 23:27:20,720+0100 FATAL xelatex - Line: 477
2017-12-18 23:27:20,728+0100 INFO  xelatex - finishing with exit code 1
``` 

I'm running the exact same command, both in the integrated terminal and the external, being in the same folder. I would expect the integrated command to behave in the same way.

**Comment by cleidigh** [comment] 2017-12-19 05:33
@erihanse 
I don't know anything about xelatex so I'm offering fairly generic help here FWIW :-)

The log only seems to give fairly generic information.  It does point to a specific line 477 there appears to be in a library file.  Have you looked at that?
I still my guess there is an environment issue.  Get and record the environment variables in the external
terminal and do the same under the integrated terminal.  Perhaps there is something that does not get inherited.   @Tyriar  is the terminal guru and he may have some better ideas than I do.

**Comment by erihanse** [comment] 2017-12-19 18:08
When doing echo %PATH% I get the same, in both internal and external terminal. I don't know much about xelatex myself, not even sure where I can find that file (search didn't find it). Anyways, here is the output:

```
C:\Program Files\Microsoft MPI\Bin\
C:\ProgramData\Oracle\Java\javapath
C:\Perl64\site\bin
C:\Perl64\bin
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\WINDOWS\system32
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Users\eriha\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\
C:\Program Files\Git\cmd
C:\Go\bin
eriha\go\bin
\Users\eriha\go\bin
C:\Program Files\Java\jdk1.8.0_144\bin
C:\Users\eriha\Anaconda3
C:\Users\eriha\Anaconda3\Scripts
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Vertica Systems\VSQL64
C:\Program Files\dotnet\
C:\Users\eriha\.dnx\bin
C:\Program Files\Microsoft DNX\Dnvm\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
C:\Program Files\R\R-3.4.1\bin
C:\Program Files\Anaconda3\Scripts
C:\Program Files\Anaconda3
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Users\eriha\Downloads\apache-maven-3.5.0-bin\apache-maven-3.5.0\bin
C:\Program Files\MongoDB\Server\3.4\bin
C:\Program Files\nodejs\
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Yarn\bin
C:\Users\eriha\AppData\Local\Microsoft\WindowsApps
C:\Users\eriha\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
C:\texlive\2016\bin\win32
C:\Program Files\Inkscape
C:\Program Files\Microsoft VS Code\bin
C:\Users\eriha\AppData\Roaming\npm
C:\Program Files\Microsoft VS Code
C:\Users\eriha\AppData\Local\Microsoft\WindowsApps
C:\Users\eriha\Documents\dhis\dhis-live
C:\Program Files\PostgreSQL\10\bin
C:\Users\eriha\AppData\Local\Yarn\bin
C:\Users\eriha\AppData\Local\GitHubDesktop\bin
C:\Program Files\Docker\Docker\Resources\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp
```

**Comment by erihanse** [comment] 2017-12-19 18:25
Think I was supposed to do `set` instead. Anyways, here is the diff between doing a `set` in the internal and the external consoles:

```
[ubuntu@Erik-PC resume3]$ diff internal external
21d20
< LANG=en_US.UTF-8
53,54d51
< TERM_PROGRAM=vscode
< TERM_PROGRAM_VERSION=1.19.0
62a60
> VSCODE_LOGS=C:\Users\eriha\AppData\Roaming\Code\logs\20171219T191949
67d64
<
\ No line ending at end of file
```

**Comment by combefis** [comment] 2017-12-23 23:29
@erihanse we got exactly the same issue here, on a Surface Pro, while trying to run:

pdflatex report.tex

- VSCode Version: 1.19.1
- OS Version: Windows 10 Build 16299.125

Running the command from external terminal (cmd or powershell) does work fine, but an error occurs when being run in the integrated terminal.

I tried the same on a desktop computer with the same VS Code and OS, and there, everything does work fine.

I looked at the line 477 of the library, it tries to execute a putc, which fails by returning EOF meaning a writing error. But I do not have any more ideas about where to look at more deeply (https://github.com/MiKTeX/miktex/blob/master/Libraries/MiKTeX/TeXAndFriends/include/miktex/C4P/C4P.h#L477).

@cleidigh any guess about what could be wrong?

**Comment by erihanse** [comment] 2017-12-23 23:43
The output also gets truncated. If you look closely, it was about to output something, starting with 
> (fr
This varies between each time I try to compile. Dunno if it means something.

**Comment by combefis** [comment] 2017-12-24 09:32
Exactly the same here on the machine where it fails. The observations are therefore coherent:

- putc (from miktex) is failing, which means that output to the integrated terminal somewhat fails on some machine/configuration.

**Comment by Tyriar** [comment] 2017-12-27 16:19
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/36630 which has a fix but is waiting for a Windows update to roll out.

**Closed by Tyriar** 2017-12-27 16:19 UTC
Labels: integrated-terminal, needs more info
