### ISSUE TITLE
When the Release Notes is open, double actions are performed on Keyboard Shortcuts

### ISSUE THREAD

**Issue by subsr97** [microsoft/vscode#84898] opened 2019-11-15 08:07 UTC
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-31-generic

Steps to Reproduce:

1. Open the Release Notes using `> Show Release Notes`
2. While it is active, press `Ctrl + N` -> Two tabs will be opened.
3. Make the Release Notes active once again.
4. Press `Ctrl + Shift + N` -> Two new windows will be opened.
5. Make the Release Notes active once again.
6. Press `Ctrl + W` -> Release Notes and one more open file will be closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-11-18 19:45
Duplicate of #82670

**Closed by mjbvz** 2019-11-18 19:45 UTC
