### ISSUE TITLE
Cannot type in a separate window

### ISSUE THREAD

**Issue by Jef-Z** [microsoft/vscode#230993] opened 2024-10-10 03:45 UTC
Type: <b>Bug</b>

- Opening a file in VSCode
- Drag the file out of the main VSCode window and the file will open in a separate window.
- **Input any text. [Unable to type]**

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|35.83GB (13.10GB free)|
|Process Argv|D:\\Ctrip\\code\\origami --crash-reporter-id 730373f1-4002-4048-ba7e-3ac46657e8ef|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics (16 x 0)|
|Memory (System)|17.48GB (12.88GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics (16 x 0)|
|Memory (System)|17.48GB (12.88GB free)|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.4
project-manager|ale|12.8.0
jest-snippets|and|1.9.1
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.6.0
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.237.0
copilot-chat|Git|0.21.1
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
vscode-react-typescript|inf|1.3.1
intellij-idea-keybindings|k--|1.7.2
ts-extension-pack|loi|0.3.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
vscodeintellicode-csharp|ms-|2.1.11
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
vscode-js-profile-flame|ms-|1.0.9
vscode-typescript-next|ms-|5.7.20241009
color-highlight|nau|2.8.0
tsimporter|pmn|2.0.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
move-ts|str|1.12.0
vscode-styled-components|sty|1.7.8
vscode-icons|vsc|12.9.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

![Image](https://github.com/user-attachments/assets/6ee63bd7-8c6b-40f4-9625-f896615296e4)

**Comment by gjsjohnmurray** [comment] 2024-10-10 03:53
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Jef-Z** [comment] 2024-10-10 03:59
Hi
Here are the steps (btw, I've always had a problem with the Extension Bisect feature.)：

- Start Extension Bisect 

![Image](https://github.com/user-attachments/assets/12ed8466-fe26-4868-9291-6b95cd2e38cc)

- click `I can reproduce` as the bug still exists
- then I got this:

![Image](https://github.com/user-attachments/assets/d9548354-87ea-47c2-bfb4-59ed93760dee)

**Comment by bpasero** [comment] 2024-10-10 06:21
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by aiday-mar** [comment] 2024-10-10 08:29
Hi @Jef-Z do you have the setting `editor.experimentalEditContextEnabled` turned on? As was mentioned in the previous comment do you see this issue on https://code.visualstudio.com/insiders/ ?

**Comment by Jef-Z** [comment] 2024-10-11 09:06
@aiday-mar Hi
Yes

![Image](https://github.com/user-attachments/assets/ebf34fa7-87e7-45fb-8faa-e4f5d3ccb872)

I turn on the new feature every time I check the change history. 
I turned it off and the problem went away.

**Comment by aiday-mar** [comment] 2024-10-11 09:17
Yes thank you for filing this issue. This is a duplicate of the issue https://github.com/microsoft/vscode/issues/229825 and a fix was merged last week which should be in next month's stable release or already in current Insiders release. I will close this issue.

**Closed by aiday-mar** 2024-10-11 09:17 UTC
Labels: info-needed
