### ISSUE TITLE
Firefox on macOS: discrepancy in dropdown menu look

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86251] opened 2019-12-04 10:11 UTC
Testing https://github.com/microsoft/vscode/issues/85987:

on macOS I noticed a discrepancy in the look of dropdown menus:

![2019-12-04_11-07-39](https://user-images.githubusercontent.com/1898161/70133568-a7828900-1686-11ea-882b-52ff17d18a8e.png)

I like the debug config dropdown (green arrow) and I dislike the other dropdown boxes (red arrows).

**Comment by misolori** [comment] 2019-12-04 18:36
Duplicate of #86050 and should be fixed already

**Closed by misolori** 2019-12-04 18:36 UTC
