### ISSUE TITLE
Sign in required every time I open VSCode

### ISSUE THREAD

**Issue by RobRukavina** [microsoft/vscode#174387] opened 2023-02-14 18:42 UTC
Type: <b>Bug</b>

close vscode, reopen vscode. profile icon will have a notification that you need to sign in to sync. 

Please just keep me signed in. This is annoying

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.89GB (21.54GB free)|
|Process Argv|--crash-reporter-id 959ed214-d4bb-41d8-bbdc-98dc72272e05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dscodegpt|Dan|1.0.15
vscode-eslint|dba|2.4.0
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
vscode-peacock|joh|4.2.2
csharp|ms-|1.25.4
LiveServer|rit|5.7.9
sabio-prework|Sab|0.0.14
vscode-wakatime|Wak|24.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549
vsctsb:30662444

```

</details>

**Comment by TylerLeonhardt** [comment] 2023-02-15 03:04
I'm guessing this is a duplicate of https://github.com/microsoft/vscode/issues/130893 ... can you try the troubleshooting steps here to confirm? https://code.visualstudio.com/docs/editor/settings-sync#_windows

**Comment by RobRukavina** [comment] 2023-02-15 03:21
@TylerLeonhardt I just opened vscode again and it didn't ask me to sign in... Maybe it fixed itself? If the issue happens again, I'll try the steps above and see if that helps. Thanks for your help!

**Comment by TylerLeonhardt** [comment] 2023-02-15 03:23
I will optimistically close this then

**Closed** 2023-02-15 03:23 UTC
Labels: info-needed
