### ISSUE TITLE
Color theme got strange when writing Java code.

### ISSUE THREAD

**Issue by kaku2020A** [microsoft/vscode#89838] opened 2020-02-01 12:47 UTC
- VSCode Version:1.41.1
- OS Version:Windows 10 1809
- Theme:Dark+ (default dark)

I'm writing Java code and it turns out the color theme will do completely different operation
depends on only a space is input or not.

1.with a space between "]" and "{"
<img width="975" alt="space" src="https://user-images.githubusercontent.com/59546311/73592112-1e7ab780-453a-11ea-8514-811a293e6839.png">

2.with no spaces between "]" and "{"
<img width="981" alt="no space" src="https://user-images.githubusercontent.com/59546311/73592120-29cde300-453a-11ea-85bd-945cdffdb1a8.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-02-04 08:50
Can you provide some copy/pastable code that shows the issue?

**Comment by kaku2020A** [comment] 2020-02-04 12:43
Not much but should be useful.
Hop to be helpful for you.
```
    String s = String.valueOf(new Object[] {String.valueOf("obj")});

    if (s == null) {
        
    } else {
        
    }

    for (int i = 0; i < s.length(); i++) {
        
    }
```

**Comment by alexr00** [comment] 2020-02-04 14:04
Thank you! I can reproduce the issue. We get our java grammar from https://github.com/atom/language-java. Looks like a duplicate of this upstream issue https://github.com/atom/language-java/issues/172

**Closed** 2020-02-04 14:05 UTC
Labels: grammar, upstream-issue-linked
