### ISSUE TITLE
Terminal leaks processes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26807] opened 2017-05-17 09:05 UTC
- VSCode Version: 1.13 insider
- OS Version: Windows

Steps to Reproduce:

1. clone vscode-eslint repository
2. chdir to eslint/eslint-server
3. open terminal (I use powershell as the terminal, not sure if it matters)
4. type npm install
5. type npm run watch
6. Kill the terminal by pressing the garbage bin button

Open a process explorer

Observe: there are still two process orphaned conhost.exe and node.exe

![capture](https://cloud.githubusercontent.com/assets/1931590/26146494/aeee5eb8-3af0-11e7-99a1-d095b0becfd0.png)

**Comment by dbaeumer** [comment] 2017-05-17 09:06
This also affects the task runner when using the terminal as the execution engine

**Comment by dbaeumer** [comment] 2017-05-17 09:08
Executing this natively in a PowerShell command prompt and using Ctrl+C to interrupt the process works as expected.

**Comment by dbaeumer** [comment] 2017-05-17 09:19
Using node version 6.5.0 but happens with 7.10.0 for me as well.

**Comment by dbaeumer** [comment] 2017-05-18 20:21
I just noticed that this also happens in Hyper.js. Looks like something has changed how winpty-agent launches processes.

**Comment by Tyriar** [comment] 2017-05-19 20:22
Related: https://github.com/Microsoft/vscode/issues/26897

**Comment by Tyriar** [comment] 2017-05-25 02:42
I actually can't reproduce using your steps on:

- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.14393

I tried 3 times and every time both node and conhost processes are terminated after around 5 seconds max which is consistent with the code https://github.com/Microsoft/vscode/blob/f95866f07eaf1cdea610479a11778ae82f69bf4b/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L129

Any more info on a repro would be good. What version of Windows are you on?

**Comment by dbaeumer** [comment] 2017-05-26 08:08
My Windows version:

![capture](https://cloud.githubusercontent.com/assets/1931590/26486387/34453850-41fb-11e7-996e-9b503a22a191.png)

**Comment by dbaeumer** [comment] 2017-05-26 08:09
I will see if I can find out more. However I do see them leak and I was even able to reproduce the leaking in Hyper.js. How does winpty-agent start the process. Is it using detach ?

**Comment by dbaeumer** [comment] 2017-05-26 08:13
And from using processes in tasks heavily I know that if a sub process inherits the input/output stream from a parent parent process then the child process might get orphaned if the streams are still open. So in the case of VS Code -> winpty -> node it might happend that node inherits stdio from VS Code and when winpty gets killed node is still sticking around since the stream owned be VS Code are still around.

**Comment by Tyriar** [comment] 2017-05-26 16:31
I believe it works like this:

VS Code (node-pty) -> winpty-agent -> conhost -> node

Just speculating here, but maybe we need to tell ptyProcess to die here: https://github.com/Microsoft/vscode/blob/66bc0d13fafadbddb5b26a3bc114bdcc29cfd39c/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L127

**Comment by Tyriar** [comment] 2017-05-26 21:25
I can reproduce on my home machine using `npm run dev` on xterm.js, the server created on `npm start` doesn't die. Here's what's happening according to process explorer:

![image](https://cloud.githubusercontent.com/assets/2193314/26513206/176f5aca-421f-11e7-8514-6bdc6b1e9b2e.png)

After hitting killing the terminal via the button the process is detached, all processes die except for the node server one:

![image](https://cloud.githubusercontent.com/assets/2193314/26513213/289a7b86-421f-11e7-85e0-7071a434b9dc.png)

**Comment by Tyriar** [comment] 2017-05-26 21:26
Something similar happens when doing the same in a regular cmd.exe window, you need to hit the X window button about 4 times though as it only kills 2 or so of the processes at once. It eventually kills them all though if you're persistent.

**Comment by Tyriar** [comment] 2017-05-26 21:30
`taskkill /pid <pid>` doesn't kill the entire tree either:

![image](https://cloud.githubusercontent.com/assets/2193314/26513347/d5fcbff0-421f-11e7-8dd3-ba62a54c634f.png)

**Comment by Tyriar** [comment] 2017-05-26 21:32
I can kill all the processes forcefully by running this:

```
taskkill /F /t /pid <pid>
```

Not sure that's better though.

**Comment by Tyriar** [comment] 2017-05-26 21:33
@rprichard do you know why some processes running in the shell on Windows (servers in particular) don't get killed but all other processes in the tree are?

**Comment by rprichard** [comment] 2017-05-27 00:46
@dbaeumer Thanks for the test case.  I was able to immediately reproduce the issue.

Some background:

 - `winpty.dll` spawns `winpty-agent.exe` using `CreateProcessW` and `bInheritHandles==FALSE`: [[code]](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/libwinpty/winpty.cc#L498)

 - `winpty-agent.exe` spawns the child process (e.g. `PowerShell.exe`) using `CreateProcessW` and typically `bInheritHandles==FALSE`: [[code]](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/agent/Agent.cc#L384)

 - `winpty-agent.exe` registers a console ctrl handler so it can generate Ctrl-C without terminating itself: [[code]](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/agent/Agent.cc#L54)

 - When VSCode (or any winpty client) destroys the console, winpty notices that its control pipe has closed and ultimately calls `agentShutdown`, which sends a `WM_CLOSE` message to the console window.  Closing a console window normally terminates all the processes attached to the console. [[code]](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/shared/WinptyAssert.cc#L35)

When I run `npm run watch` in an ordinary Windows console, then click the console's 'X' button, it kills some of the processes running in the console, but it doesn't kill the second `node.exe` process.

I found the problem on GitHub by searching for `SetConsoleCtrlHandler` in the libuv repo (libuv is the runtime that node.js runs on):

```c++
    case CTRL_CLOSE_EVENT:
      if (uv__signal_dispatch(SIGHUP)) {
        /* Windows will terminate the process after the control handler */
        /* returns. After that it will just terminate our process. Therefore */
        /* block the signal handler so the main loop has some time to pick */
        /* up the signal and do something for a few seconds. */
        Sleep(INFINITE);
        return TRUE;
      }
      return FALSE;
```
[[link]](https://github.com/libuv/libuv/blob/fd39cec4b848b27be6bf3f8a3e0bce29474366bb/src/win/signal.c#L119)

When I click the 'X' button of a console with `npm run watch` running, libuv intercepts the `CTRL_CLOSE_EVENT` event on a new thread, which somehow dispatches a "SIGHUP"... somewhere... and then waits forever.  I'm guessing that libuv is assuming that the SIGHUP handler will terminate the process, but it doesn't always.  (Aside: I think the Unix emulation is breaking down here, though, because a Unix program can ignore multiple SIGHUP signals, right?  A libuv Windows program can only ignore a single `CTRL_CLOSE_EVENT`/`SIGHUP` event.)

When I click the 'X' button a second time, I guess Windows knows that the console ctrl handler is already running and decides to just kill the thing.

Two ideas for a fix:

1. winpty could better expose the Windows behavior with a new API that "requests" the console be closed (e.g. sends a `WM_CLOSE` message), but the winpty instance remains functioning until it really has closed.  A second close request would (probably?) kill it for sure.  In the VSCode UI, you could click the `Kill Terminal` button, and nothing would happen because the console wasn't dead yet.  After you click it a second time, the winpty instance dies, then VSCode detects this and hides the GUI.  (For example, I tested ConEmu with `npm run watch`, and ConEmu behaved this way -- I had to close ConEmu twice to get it to really close.)

2. No API change.  Instead, winpty mimics libuv's `CTRL_CLOSE_EVENT` handler a bit and prevents its termination until it sees that all attached processes are gone (using `GetConsoleProcessList`).  If they aren't gone after, say, 30 seconds, then it posts another `WM_CLOSE`, which is very likely to terminate everything.  (Note that `winpty-agent.exe` itself is attached to the console, so that second `WM_CLOSE` will presumably kill `winpty-agent.exe`.)

Right now, I lean towards fix 2 because it seems like less trouble.

I'm not sure about the VSCode "plan B" thing.  As long as it doesn't terminate `winpty-agent.exe`, I guess it's OK.

(Note to self: I wonder what happens if I register a new console ctrl handler between the two `WM_CLOSE` messages.  Does Windows still terminate the process?)

**Comment by rprichard** [comment] 2017-05-27 00:49
> 30 seconds

I suppose leaving `npm run watch` around for 30 seconds would be painful.  Maybe 5 seconds is better?  It could be configurable.

Actually, this seems like an argument for implementing fix 1, if that's feasible.

**Comment by rprichard** [comment] 2017-05-27 00:59
Also: maybe `npm run watch` should be fixed so it exits the first time the console 'X' button is clicked.

**Comment by rprichard** [comment] 2017-05-27 01:31
Testing using an ordinary Windows console (with the `cmd.exe` shell, not that it should matter):
 * Win7 node-6.9.3 / npm-3.10.10 `npm run watch`: prints a bunch of errors, pauses for a couple of seconds, then the console closes.
 * Win7 node-6.10.3 / npm-3.10.10 `npm run watch`: prints a bunch of errors, then the console closes immediately.

gist: https://gist.github.com/rprichard/88c50833fd7fadd1a0ce6d009b9a4710

**Comment by rprichard** [comment] 2017-05-27 02:04
More testing (all with node-6.10.3 / npm-3.10.10):

 * Win8.1: prints a bunch of errors, exits immediately.
 * Win10 14393.0 v1 console: prints a bunch of errors, exits immediately.
 * Win10 14393.0 v2 console: prints a bunch of errors, exits immediately.
 * Win10 15063.332 v1 console: prints a bunch of errors, exits immediately.
 * Win10 15063.332 v2 console: no errors, doesn't exit until I click 'X' a second time.  The console GUI is responsive (e.g. While it's waiting, I can resize the console, and the text reflows.)

When I start `npm run watch`, if there is an `npm-debug.log` file in the `eslint-server` working directory, it is deleted.  When I click the console 'X' button, an `npm-debug.log` file appears in the working directory.

Apparently, the problem won't happen if you enable the legacy console or switch back to 14393.

**Comment by rprichard** [comment] 2017-05-28 09:44
I think I understand what's happening now with Node.

 * The npm `node.exe` process calls `CreateProcessW` for a command-line like `cmd.exe /d /s /c installServerIntoExtension ... && tsc --watch ...`, then it calls `AssignProcessToJobObject` to assign the `cmd.exe` process to a job object.  `tsc` is a batch file that invokes `node.exe`, so eventually, the parent `node.exe` has a `node.exe` grandchild.  Because the parent `node.exe` uses `JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK` for the job assignment, only `cmd.exe` is assigned to the job, not the grandchild.

 * Windows issues `CTRL_CLOSE_EVENT` to each attached process, one at a time, giving it up to 5 seconds to exit before terminating it.  While it's iterating over processes, though, if Windows sees a process that has already exited on its own, it aborts the close-signaling operation.  This behavior seems to have started in Windows 8.  (I have a test case demonstrating this behavior.)

 * From Windows XP to Windows 10.0.14393, inclusive, given a series of child processes, Windows signals them in last-attached-to-first-attached order.  (I'm not trying to exhaustively determine the signaling order -- I just used a simple test.)  Starting with 15063, and only with the v2 console, Windows uses first-attached-to-last-attached order.

 * This is our process tree when the console is closed:

    * A: node.exe (npm run watch, owns Job1)
      * B: cmd.exe (belongs to Job1)
        * C: node.exe (tsc --watch)

   Windows signals A to close.  A doesn't respond to the libuv-emulated `SIGHUP`, so nothing happens.  After 5 seconds, Windows kills A.  I suspect there's a race condition here, because something (the kernel?) is going to destroy Job1 and kill B, but something else (also the kernel? csrss.exe? conhost.exe?) moves on to B and notices that it's already gone.  In the typical, second situation, Windows notices that B is already gone, and the close operation ends with C remaining.

   With the v1 console (and previous Windows versions), Windows signals C first.  I don't recall whether it even registers a libuv `SIGHUP` handler, but either way, it will certainly exit, and once it has, we know that B will exit, and we know that A will ignore a close event for up to 5 seconds while it deals with its failed subprocess, then it will exit.

I have a detailed test case I'll post soon.

**Comment by dbaeumer** [comment] 2017-06-06 11:54
@Tyriar can you please have a look. I had ~20 leaking winpty processes today. It is not that this only happens once a while for me :-).

**Comment by Tyriar** [comment] 2017-06-06 17:57
@dbaeumer it's blocked an upstream fix isn't it?

Might be able to workaround by using the legacy cmd.exe:

> Apparently, the problem won't happen if you enable the legacy console or switch back to 14393.

**Comment by dbaeumer** [comment] 2017-06-06 19:01
I thought you have your hands in winpty as well :-)

I will try to use cmd.exe for now. Was using PowerShell.

**Comment by rprichard** [comment] 2017-06-07 00:56
> Might be able to workaround by using the legacy cmd.exe:
>
>> Apparently, the problem won't happen if you enable the legacy console or switch back to 14393.

No, the legacy console is the `ConhostV1.dll` implementation used in `conhost.exe`.  The new console is `ConhostV2.dll` and provides things like VT/ANSI escape-sequence I/O, automatic line rewrapping, and line-based selection.  It's unrelated to `cmd.exe` and `powershell.exe`, which are shells.

Here's how to enable the legacy console:

https://www.isunshare.com/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10.html

Each user on a Window machine has their own "use legacy console" setting, which is shared by all programs on the machines.  winpty creates a hidden console window and is also affected by the setting.

**Comment by MastroLindus** [comment] 2017-06-22 07:43
I have a similar problem on Linux Mint 17 on visual code 1.13.0 using tmux 2.3 as my terminal.

Started processes (webpack in watch mode) don't get killed when closing the editor.

In the past I opened issue 24688 for the same problem, and even if some work has been done on it in April and got verified, I still experience the problem.

**Comment by Tyriar** [comment] 2017-06-22 17:22
@MastroLindus this issue is specifically for Windows which uses a very different backend. We can discuss this in another issue if you want, the main thing I'll need is reliable repro steps.

**Comment by MastroLindus** [comment] 2017-06-27 07:33
@Tyriar Apologies, I was afraid to create duplicate issues for a similar problem, but I understand that given the different backend it is better to separate them. I created #29531 for it, so please ignore my comment above.

**Comment by Ciantic** [comment] 2017-07-13 11:08
I'm experiencing this with the simplest example:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "start",
            "problemMatcher": ["$tsc-watch"]
        }
    ]
}
```

VSCode 1.14.0

Even if I add isBackground there it won't help. If I choose to terminate the process, it disappears from VSCode but keeps running in background.

Is this problem with my VSCode installation? Because this is now documented way to use tasks, and if it leaks processes, it's not working.

**Comment by dbaeumer** [comment] 2017-07-13 13:49
@Tyriar not sure if it helps tracking this down however when executed in a PowerShell terminal directly pressing the close button of the PowerShell Window doesn't actually close the Windows. Interestingly the interpreter process goes away and the same node processes get orphaned. When pressing the close button a second time all processes close.

**Comment by dbaeumer** [comment] 2017-07-13 13:52
I did some more experimenting and what works as a sequence is the following:

- press Ctrl+C in the terminal
- then Kill the terminal

May be as a workaround the integrated terminal could first send a `Ctrl+C` and then a kill when under Windows to work around that problem.

**Comment by dbaeumer** [comment] 2017-07-13 14:05
More info: a gulp file in watching mode doesn't expose the problem. Killing the terminal leaves now leaking processes.

**Comment by dbaeumer** [comment] 2017-07-13 14:15
This seems to be very specific to npm (or node starting node as a child). I was not able to reproduce the leaking for other setups (gulp, calling tsc directly, ...)

**Comment by Ciantic** [comment] 2017-07-13 16:34
Using npm script "node webpack.dev.server.js" is probably common among webpack users, others above seem to have complained same thing because of webpack.

I figured from @dbaeumer's comment then that workaround is to do this instead, *this works*:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "command": "node",
            "taskName": "start",
            "args": ["webpack.dev.server.js"],
            "problemMatcher": ["$tsc-watch"]
        }
    ]
}
```

**Comment by Tyriar** [comment] 2017-07-17 16:13
Cannot repro using the original steps with cmd, powershell, git bash or powershell running through git bash:

> Steps to Reproduce:
> 
> 1. clone vscode-eslint repository
> 2. chdir to eslint/eslint-server
> 3. open terminal (I use powershell as the terminal, not sure if it matters)
> 4. type npm install
> 5. type npm run watch
> 6. Kill the terminal by pressing the garbage bin button

**Comment by vasilrimar** [comment] 2017-07-18 20:35
I've created a simple repo to demonstrate the problem. Running on Windows 10 using Powershell as terminal and Node v6.11.0.

Here are the steps to reproduce: 

1. type `git clone https://github.com/vasilrimar/vscode-process-leak.git`
2. type `cd vscode-process-leak`
3. type `npm install`
4. type `npm run start`
5. Kill terminal by pressing garbage bin button (at this point the node process will still be running)
6. open terminal and type `npm run start` again
7. Will throw `Error: listen EADDRINUSE` (port in use) error due to process not exiting correctly

**Comment by Tyriar** [comment] 2017-07-25 01:28
Should be fixed in tomorrow's build, the process tree is now forcefully killed using `taskkill.exe /T /F /PID <pid>`

**Comment by chrmarti** [comment] 2017-08-02 19:03
The original steps still reproduced:
![image](https://user-images.githubusercontent.com/9205389/28889868-3ce22e32-777a-11e7-930e-e1cc03d7a725.png)

- VSCode Version: Code - Insiders 1.15.0-insider (211ffdf184329179ddca9c1fe993f5f11f3c4dda, 2017-08-02T05:16:00.824Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: None

**Comment by Tyriar** [comment] 2017-08-03 06:58
Hmm, not sure how this would still be happening. Deferring.

**Comment by the-ress** [comment] 2017-08-06 02:05
I don't think killing whole process tree is a good idea. You can have launched applications that aren't attached to the console, e.g. notepad. Killing the process tree will kill them too, losing unsaved work, etc.

**Comment by rprichard** [comment] 2017-08-06 02:37
Maybe the fix could involve `GetConsoleProcessList` somehow.  e.g. `winpty-agent.exe` could terminate the processes in that list.

**Comment by the-ress** [comment] 2017-08-06 02:57
I've already implemented passing that list to vscode in [the-ress/node-pty](https://github.com/the-ress/node-pty/tree/get_process_list) (I'm going to need it for improving #30732), but it probably makes more sense if `winpty-agent.exe` terminates the processes.

**Comment by Tyriar** [comment] 2017-08-28 16:16
Created https://github.com/rprichard/winpty/issues/129 in winpty.

**Comment by Tyriar** [comment] 2017-09-08 00:55
@dbaeumer unfortunately I'm busy through September with Electron tasks and travel so I doubt I'll be able to get to this. I'm committed to making it a priority and explicitly putting it on the October iteration plan though.

**Comment by Tyriar** [comment] 2017-09-08 01:01
@the-ress did you end up making any progress on your branch of node-pty? If it's still a WIP maybe I can take what you have when I free up and build upon it?

**Comment by dbaeumer** [comment] 2017-09-08 09:04
@Tyriar thanks for letting me know.

**Comment by the-ress** [comment] 2017-09-08 19:50
@Tyriar no, it's still WIP/PoC. Yes, of course you can.

**Comment by the-ress** [comment] 2017-09-16 12:51
Created rprichard/winpty#130 with winpty part of the changes.

**Comment by Tyriar** [comment] 2017-10-03 17:58
@the-ress just tested your winpty patch and it correctly returns the process list without the notepad process launched via `start notepad` 👍

**Closed** 2017-10-03 20:58 UTC
Labels: bug, integrated-terminal, upstream, windows

**Comment by Tyriar** [comment] 2017-10-03 21:02
Thanks to @the-ress this is now fixed at the node-pty level. 🎉 

@the-ress when the winpty PR is finalized I'll pull the latest code into the next version of node-pty.

**Comment by EdonGashi** [comment] 2017-10-15 11:42
I am experiencing this issue on win 10 x64.

```
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:24:50.851Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

node.exe gets orphaned when using `npm run ***` and closing vs code.

Tested with git bash and ps as terminal.

**Comment by Tyriar** [comment] 2017-10-18 19:45
@EdonGashi the fix for this will be out in v1.18, you can try it out now in the Insiders build https://code.visualstudio.com/insiders

**Comment by EdonGashi** [comment] 2017-10-19 20:47
Tried it. It's working as expected. Thanks!

**Comment by Beretta1979** [comment] 2017-11-13 10:44
For me this is still occurring on windows 10 with node js. If I kill the terminal using the garbage bin button the node processes are killed correctly. If VS Code is closed the processes keep running.

**Comment by TomasHubelbauer** [comment] 2017-11-13 15:08
@Beretta1979 I am on Windows 10 and VS Code 1.18.0 and the integrated terminal I am using is `cmd.exe`. I used an external PowerShell terminal and did `tasklist -fi "imagename eq node.exe"` after doing `npm start` and closing using the bin button and after doing `npm start` and closing VS Code as a whole and in my case it worked as it should have. What is in your `terminal.integrated.shell.windows` setting?

**Comment by Beretta1979** [comment] 2017-11-13 15:11
@TomasHubelbauer I tested this both with terminal.integrated.shell.windows set to powershell (default) as with cmd.exe
