### ISSUE TITLE
Terminal resizing fills terminal with previously cleared content

### ISSUE THREAD

**Issue by wex-ler** [Microsoft/vscode#69287] opened 2019-02-23 22:03 UTC
- VSCode Version: 1.31.1
- OS Version: Windows 10 Education version 1809

Steps to Reproduce:

1. Open a terminal. 
2. Fill it with text (preferably long enough so it will wrap around).
3. Clear it with `workbench.action.terminal.clear`.
4. Resize the terminal.

Does this issue occur when all extensions are disabled?: Yes

Visual example:

![Example](https://i.imgur.com/Hqse1Ri.gif)

I think this has something to do with text wrapping, as it happens sooner on instances where it is long enough to be wrapped. Without that I would have to resize the terminal to really small size to reproduce the issue.

**Comment by Tyriar** [comment] 2019-02-26 01:32
Maybe a duplicate of https://github.com/Microsoft/vscode/issues/68721, also some messing up is expected currently.

**Closed by Tyriar** 2019-02-26 01:32 UTC
Labels: integrated-terminal
