### ISSUE TITLE
Add filename color support in the explorer

### ISSUE THREAD

**Issue by huyinghuan** [Microsoft/vscode#10530] opened 2016-08-15 02:54 UTC
Can you please add filename  color support in the tree view?

I don't want to switch to git panel every time when i need know which file changed .

webstorm do very well. like this:

![image](https://cloud.githubusercontent.com/assets/3005433/17654513/6447b000-62d6-11e6-9c2c-b9a4ff247e14.png)

it is very clear that use different color mark filename

**Comment by bpasero** [comment] 2016-08-15 07:50
Duplicate of https://github.com/Microsoft/vscode/issues/178

**Closed by bpasero** 2016-08-15 07:50 UTC
