### ISSUE TITLE
Windows and Editors not restored after reboot (1.25.1 on Windows 10 1803)

### ISSUE THREAD

**Issue by youurayy** [Microsoft/vscode#56235] opened 2018-08-12 23:58 UTC
- VSCode Version: 1.25.1
- OS Version: Windows

Note: This is NOT a duplicate of #50846 which is about a loss of VS Code windows when VS Code is started by opening a file.

Steps to Reproduce:

1. Set VSCode to `"window.restoreWindows": "all",`
2. Open a VSCode window in some folder, and open a few files.
3. Optional: open more VSCode windows and open some files in each.
4. Reboot the system via start menu.
5. When booted, start VSCode

Expected result: All VSCode windows and all editors in their remembered tab splits and tab positions should be restored (this worked in previous versions).

Actual result: only the first VSCode window is restored, and no editors are restored (the window is empty).

Note: when VSCode is closed by right-clicking on the Taskbar icon, and clicking "Close all windows", the Editors are restored, but only the first Window is reopened.

User sentiment: it's really tiring to have to manually reopen ~6 windows with 20's of tabs each on every Windows restart, which there are plenty.

Does this issue occur when all extensions are disabled?: Yes, tested!

My VSCode config:

```json
{
    "window.zoomLevel": 0,
    "workbench.statusBar.visible": false,
    "editor.renderWhitespace": "all",
    "editor.wordWrap": "on",
    "editor.tabSize": 2,
    "editor.cursorBlinking": "solid",
    "git.confirmSync": false,
    "window.restoreWindows": "all",
    "window.restoreFullscreen": true,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.lineNumbers": "off",
    "editor.detectIndentation": false,
    "editor.autoClosingBrackets": false,
    "editor.mouseWheelZoom": false,
    "editor.folding": false,
    "editor.rulers": [],
    "editor.glyphMargin": false,
    "editor.codeLens": false,
    "explorer.openEditors.visible": 999,
    "editor.fontSize": 14,
    "editor.scrollBeyondLastLine": false,
    "editor.quickSuggestions": false,
    "files.trimTrailingWhitespace": true,
    "terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["/bin/xhere", "/bin/bash"],
    "window.newWindowDimensions": "fullscreen",
    "files.eol": "\n",
    "workbench.editor.revealIfOpen": false,
    "zenMode.hideTabs": false,
    "zenMode.restore": true,
    "git.enabled": false,
    "git.autorefresh": false,
    "git.autofetch": false,
    "git.countBadge": "tracked",
    "editor.formatOnType": false,
    "workbench.iconTheme": null,
    "editor.renderControlCharacters": true,
    "editor.renderLineHighlight": "all",
    "editor.minimap.enabled": false,
    "window.openFoldersInNewWindow": "on",
    "workbench.startupEditor": "none",
    "window.menuBarVisibility": "toggle",
    "window.smoothScrollingWorkaround": true,
    "extensions.ignoreRecommendations": true,
    "javascript.validate.enable": false,
    "flow.useNPMPackagedFlow": true,
    "workbench.activityBar.visible": false
  }
```

**Comment by bpasero** [comment] 2018-08-13 15:04
Duplicate of https://github.com/Microsoft/vscode/issues/12058

**Closed by bpasero** 2018-08-13 15:04 UTC
Labels: workbench-state

**Comment by bpasero** [comment] 2018-08-13 15:29
@youurayy that is expected, it will actually trigger a close of each window one by one and as such is different from File > Exit where no windows close but the application quits.
