### ISSUE TITLE
"Go to file" feature stumbles when typing any file name

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#112797] opened 2020-12-18 08:21 UTC
Issue Type: <b>Bug</b>

Greetings to everyone,

since the release of 1.52.x I've encountered an issue with "Go to file" pop-up form.
Basically, non deterministically, when I type a name of a file I'm look for the input form stumbles for aprox. 2 seconds (I guess the UI of VSCode stops as well) and only AFTER that everything goes back to normal.

Sorry for the vague description, I can't make a gif to visualise the issue (non deterministic), the only conditions I can give you are the big picture:

It DOESN'T happen all the time (during my working hours aprox. 5-10 times a day)
It happens in any project structure and complexity (small files or big files - doesn't matter)
It happens only in VScode 1.52.x and above
I didn't try to use VScode without any extensions for that I can't work without them and wait until whether or not the issue persist.
I'm open to give any further info if needed.

As always, thank you for the amazing tool!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.1.0
Remote OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Ipernet|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|15.94GB (6.82GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
sublime-keybindings|ms-|4.0.7
vscode-icons|vsc|11.0.0
alignment|ann|0.3.0
path-intellisense|chr|2.3.0
indent4to2|Com|0.1.2
vscode-eslint|dba|2.1.14
vstortoise|flo|1.2.2
beautify|Hoo|1.5.0
svn-scm|joh|2.13.5
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
vscode-filesize|mkx|2.1.4
prettify-json|moh|0.0.3
vscode-paste-and-indent|Rub|0.0.8
sass-indented|syl|1.8.13

</details>

**Comment by alexdima** [comment] 2020-12-18 21:57
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by IperStan** [comment] 2020-12-21 16:07
> ~This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (#112843)~ This cannot be the case because the remote OS is Windows.

Thanks for keeping in touch! Sadly I still can't give any more information than above-mentioned ones. The only sure thing is, again, the fact that it doesn't happen on the releases bellow 1.52

**Comment by roblourens** [comment] 2020-12-30 21:25
> when I type a name of a file I'm look for the input form stumbles for aprox. 2 seconds

Can you tell me a little more about what exactly you are seeing?

**Comment by IperStan** [comment] 2021-01-04 11:40
Hi, so I tried to figure out some valuable messages in devtools of the VScode and here is the result. When I tap CMD+P and *start* to write any filename, the UI of the VSCode freezes completely for about 1.5 - 2 seconds and according to logs I suspect it's ColdFusion related extensions. (I'm not sure whether CFLinter or CFML syntax).
Since I can't shut down those extensions during my development, I don't know what else I could do in order to track the cause of the issue. Any help?

![image](https://user-images.githubusercontent.com/43338672/103530912-9824cf00-4e88-11eb-9984-cbcf72497e01.png)

**Comment by roblourens** [comment] 2021-01-04 18:05
I would guess that this is just related to search itself, but I don't have a guess as to why this just shows up with 1.52. Do you think it makes a difference based on what you start typing in cmd+P?

**Comment by IperStan** [comment] 2021-01-05 08:30
> I would guess that this is just related to search itself, but I don't have a guess as to why this just shows up with 1.52. Do you think it makes a difference based on what you start typing in cmd+P?

I understand you, it's hard to tell even from my user's perspective what causes this undeterministic behaviour. It would be much easier to see it in action by recording a video but it's impractical to record my entire working day. From my experience since the 1.52.x version came up, it makes no difference on *what* I type in the searching bar. I see it happen and it happens in any project I've been working so far: small, medium and big ones - 0 difference.

I really like your product and I'll make sure next time I'll be more precise and have more concrete evidence. For now I'll cope with my issue and investigate more on the matter. I'll try to monitor devtools on the second monitor when the searching bar freezes again and see what I can do.

Thank you!

**Comment by roblourens** [comment] 2021-02-03 00:03
Please let me know if there is any new info. Also 1.53 will be released within the next week.

**Closed by roblourens** 2021-02-03 00:03 UTC
Labels: needs more info, quick-pick, search
