### ISSUE TITLE
Image viewer zoom Touchpad reversed pinch to zoom { VSCODE 1.20.0 }

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#43372] opened 2018-02-10 04:55 UTC
Dell 5558 when pinch to zoom it reverse action

zoom in = zoom out
zoom out = zoom in

**Comment by mjbvz** [comment] 2018-02-12 18:39
Duplicate of #43138

**Closed by mjbvz** 2018-02-12 18:39 UTC
