### ISSUE TITLE
Icons are invisible

### ISSUE THREAD

**Issue by bvbeek** [microsoft/vscode#110782] opened 2020-11-17 08:29 UTC
![image](https://user-images.githubusercontent.com/28626283/99364888-d6edce00-28b6-11eb-9475-888d619b3e95.png)
![image](https://user-images.githubusercontent.com/28626283/99365148-2e8c3980-28b7-11eb-9ba3-46271d88708d.png)
![image](https://user-images.githubusercontent.com/28626283/99365213-46fc5400-28b7-11eb-82f3-feb52d050c2b.png)
![image](https://user-images.githubusercontent.com/28626283/99365273-57143380-28b7-11eb-828e-8d6f33f14eea.png)

**Comment by roblourens** [comment] 2020-11-17 19:00
Not an extension issue but I don't know who knows about this, do you know anything about it @eamodio?

**Comment by isidorn** [comment] 2020-11-23 08:26
@bvbeek I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
For now assigning to @misolori since this seems to be an Icon issue.

**Comment by bvbeek** [comment] 2020-11-23 09:28
@isidorn, I'm unable to test this, it's running on a VM where multiple users are working on it.
Is there something else what I can share or try?

**Comment by misolori** [comment] 2020-11-24 16:34
@bvbeek is this still happening to you? Have you attempted to close and restart VS Code? I'm unable to reproduce on Windows.

**Comment by bvbeek** [comment] 2020-11-25 09:13
Yes, and also other people on the same server.
Already restart VS Code.
Is there something else what I can share or try?

**Comment by misolori** [comment] 2020-11-25 17:29
@bvbeek we need more information from your environment. Can you go to Help > Report Issue and fill out some text and the paste the info into this issue (it should copy all of your system info + extensions). Also, are you using [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync)?

**Comment by bvbeek** [comment] 2020-11-26 08:16
Not using Settings Sync.
Here is the info:

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (16 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|128.00GB (64.43GB free)|
|Process Argv|--crash-reporter-id 0ed34af5-e0e6-4055-934c-e8d9d70191af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
al-code-outline|and|2.0.20
al-codeactions|dav|0.2.21
githistory|don|0.6.14
gitlens|eam|11.0.5
al-object-designer|mar|0.2.4
al|ms-|6.1.362735
powershell|ms-|2020.6.0
al-formatter|ras|3.0.0
vscode-icons|vsc|11.0.0
crs-al-language-extension|wal|1.3.3
al-navigator|wbr|0.3.2


</details>

**Comment by bvbeek** [comment] 2020-12-19 09:17
Just tried to remove VS Code including settings in folders:
- %USERPROFILE%\.vscode
- %AppData%\Code
Restart server and install again.
Same issue.
Please can anyone help me with this issue?
What can I try?

**Comment by misolori** [comment] 2020-12-21 18:06
Are you connected to the VM via SSH in VS Code(using the remote extensions) OR are you connecting via RDP?

**Comment by bvbeek** [comment] 2020-12-22 09:45
connecting via RDP

**Comment by misolori** [comment] 2021-01-04 17:56
@sandy081 assigning to you as there's not much else I can do and this appears to be issues with extension icons

**Comment by sandy081** [comment] 2021-01-06 15:38
Can you please open dev tools and inspect the element with no icon and let us know the path of the icon? Let me know if you need any help in inspecting this?

**Comment by sandy081** [comment] 2021-01-07 16:54
May I know if the VS Code is running on the same machine where the above icons are located?

**Closed** 2021-01-15 12:06 UTC
Labels: needs more info

**Comment by Heinerion** [comment] 2021-01-22 15:19
Hi there, I got the same Problem with V 1.52.1

![grafik](https://user-images.githubusercontent.com/13521176/105509045-6192e500-5ccd-11eb-9ae8-b93e914ac063.png)
![grafik](https://user-images.githubusercontent.com/13521176/105509280-a3239000-5ccd-11eb-84f1-b1409f53de99.png)

**Comment by bvbeek** [comment] 2021-01-25 11:55
> May I know if the VS Code is running on the same machine where the above icons are located?

Yes, same server

**Comment by misolori** [comment] 2021-04-19 14:51
Pasting an update from @bvbeek:

> Now I got the solution for this, maybe it’s good to add that solution there.
>
> Execute: ie4uinit.exe -show
> Source: https://www.winhelponline.com/blog/refresh-icon-cache-windows-7-quickly/
>
>Now are my icons visible for every user.

This appears to clear the icon cache
