### ISSUE TITLE
Intellisense activating inside of strings

### ISSUE THREAD

**Issue by v-codeel** [Microsoft/vscode#5051] opened 2016-04-06 20:50 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

(Code examples will be in C#, but also repro's with other languages)

Scenario 1 Repro:
1. `var x = "%%`
2. With the cursor at `%%`, Type `C`
3. Code Completion suggestions are shown.
![image](https://cloud.githubusercontent.com/assets/10519323/14332053/be020618-fbfc-11e5-97d1-668ce22db799.png)

Scenario 2 Repro:
1. `Console.WriteLine("%%)`
2. Intellisense will be showing. Click elsewhere in the file to dismiss it.
3. Type `(`
4. Intellisense is shown again.
![image](https://cloud.githubusercontent.com/assets/10519323/14332327/e327a668-fbfd-11e5-867c-2dcffad8a61d.png)
(This would be normal if it hadn't been previously dismissed.)

**Comment by v-codeel** [comment] 2016-04-06 20:54
Repro's on OSX as well.

**Comment by DustinCampbell** [comment] 2016-04-06 21:03
Both are great bugs -- could you please file over in https://github.com/omnisharp/omnisharp-vscode/issues rather than on VS Code itself?

**Comment by v-codeel** [comment] 2016-04-06 21:37
Migrated to https://github.com/OmniSharp/omnisharp-vscode/issues/154, but leaving this open since it repro's with languages other than C# (specifically tested with JavaScript)

**Comment by joaomoreno** [comment] 2016-04-07 07:33
Forwarding to @dbaeumer due to

> specifically tested with JavaScript

**Comment by dbaeumer** [comment] 2016-04-07 07:58
@v-codeel we always include textual completions in code complete (e.g words that are in the document). We find this useful in strings and comments. Are you proposing not to show them? They are marked with an icon 'abc' to indicate that they are textual completions only.

**Comment by v-codeel** [comment] 2016-04-07 18:29
@dbaeumer I thought it was odd since this doesn't happen in the normal VS product. I didn't notice the 'abc' icons previously, but I guess it makes sense.
Having the snippets seems odd to me, but based on the resolution of #5069, I suppose the answer would be to leave those as well.

**Comment by mjbvz** [comment] 2017-01-26 07:51
Closing as this is by design. I only see word based and snippet suggestions inside of string in JS.

**Closed by mjbvz** 2017-01-26 07:51 UTC
Labels: as-designed, javascript
