### ISSUE TITLE
Please allow for C++ user defined types to be highlighted 

### ISSUE THREAD

**Issue by Blaze23** [Microsoft/vscode#56199] opened 2018-08-11 15:57 UTC
Please allow for C++ user defined types to be highlighted, like in visual studio. Currently the syntax highlighting doesn't work for them, so when I make a class (eg 'Person' ) and then initialise an object of that class, although intellisense recognises that the Person keyword refers to the class, it isn't highlighted unlike visual studio.

**Comment by ramya-rao-a** [comment] 2018-08-11 18:36
Can you share sample code? A screenshot of the sample code in Visual Studio and Visual Studio Code will also help

**Comment by aeschli** [comment] 2018-08-15 16:19
Duplicate of https://github.com/atom/language-c/issues/266

**Closed by aeschli** 2018-08-15 16:19 UTC
Labels: needs more info

**Comment by Blaze23** [comment] 2018-08-15 17:18
Incorrect. This is a completely different issue - please reopen.

Thanks,
Ansh Bhatnagar
________________________________

**Comment by ramya-rao-a** [comment] 2018-08-15 17:32
@Blaze23 Can you explain how the issue is different? Perhaps share a sample code?

**Comment by Blaze23** [comment] 2018-08-15 17:39
I have attached screenshots to the email, comparing how Visual Studio does syntax highlighting differently to VS code with regards to user defined types. The class “Planet” that I have made is highlighted when creating objects of that type – VS code does not do this.

- Ansh

________________________________

**Comment by ramya-rao-a** [comment] 2018-08-15 17:49
Can you paste the screenshots here?

**Comment by aeschli** [comment] 2018-08-16 07:04
Visual Studio code:
![image](https://user-images.githubusercontent.com/6461412/44193490-52d69a00-a133-11e8-92e1-8ee85a963cdc.png)
![image](https://user-images.githubusercontent.com/6461412/44193491-55d18a80-a133-11e8-8b7d-b84e6ce3e2c6.png)
Visual Studio:
![image](https://user-images.githubusercontent.com/6461412/44193443-2a4ea000-a133-11e8-943c-da8e758426a6.png)
![image](https://user-images.githubusercontent.com/6461412/44193469-3cc8d980-a133-11e8-8ffd-7fe01c8b1de1.png)

**Comment by aeschli** [comment] 2018-08-16 07:06
@Blaze23 I verified again that https://github.com/atom/language-c/issues/266 is the underlying cause for this.
