### ISSUE TITLE
Unable to fold block comments

### ISSUE THREAD

**Issue by chengkiang** [Microsoft/vscode#51282] opened 2018-06-07 03:01 UTC
Issue Type: <b>Bug</b>

With the latest release, I am no longer able to fold block comments. I have tried loading Code without extensions but it still doesn't work. The little [+] button appears in the gutter beside the comments for a short while, then disappears. The keyboard shortcut or the command palette also does not work.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (8.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.7.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
vscode-mocha|Com|0.1.1
vscode-eslint|dba|1.4.12
xml|Dot|2.2.0
gitlens|eam|8.3.3
permute-lines|ear|0.0.9
vscode-npm-script|eg2|0.3.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
vscode-ungit|Hir|1.5.0
rest-client|hum|0.18.4
search-node-modules|jas|1.3.0
prettify-json|moh|0.0.3
mssql|ms-|1.3.1
cpptools|ms-|0.17.4
markdown-preview-enhanced|shd|0.3.5
vscode-arduino|vsc|0.2.16
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.6.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-06-07 06:55
See the `syntax aware folding` section of the release notes for more info: https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts

Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Closed by mjbvz** 2018-06-07 06:55 UTC
Labels: new release
