### ISSUE TITLE
VSCode crashing due to sigbus

### ISSUE THREAD

**Issue by pvicol** [Microsoft/vscode#64569] opened 2018-12-07 00:01 UTC
- VSCode Version: 1.29.1
- OS Version: 10.14.1

Does this issue occur when all extensions are disabled?: Yes

Getting the following error in the /var/log/system.log for both latest insider and current version I have installed:
Dec  6 15:54:37 REDACT com.apple.xpc.launchd[1] (com.microsoft.VSCodeInsiders.4508[4089]): Service exited due to SIGBUS | sent by exc handler[4089]

The issue started happening after an update for Outlook. It seems to work when booted in Safe Mode.

**Comment by pvicol** [comment] 2018-12-07 12:37
@jrieken OSX Mojave 10.14.1; I am using Cylance. Using latest VS Code Insiders, I get the same error:

```
com.apple.xpc.launchd[1] (com.microsoft.VSCodeInsiders.4596[10568]): Service exited due to SIGBUS | sent by exc handler[10568]
```

Also tried to launch with verbose and disable extenstions:
```
 $ code --disable-extensions --verbose                                                                                               
[main 4:34:24 AM] Starting VS Code
[main 4:34:24 AM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 4:34:24 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 4:34:24 AM] Resolving machine identifier...
[main 4:34:24 AM] Resolved machine identifier: c7e2af2b85573732a616c2fa96e9b28f65fbe0918d979d72fe2595e0fabe2792
[main 4:34:24 AM] update#setState idle
[main 4:34:24 AM] windowsManager#open
[main 4:34:24 AM] telemetry/optInStatus { optIn: true }
[12186:1207/043425.823775:INFO:CONSOLE(1445)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1445)
[12186:1207/043425.831174:INFO:CONSOLE(1445)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1445)
```

**Comment by jrieken** [comment] 2018-12-07 12:52
@bpasero Cylance strikes again

**Comment by bpasero** [comment] 2018-12-07 13:03
Duplicate of https://github.com/Microsoft/vscode/issues/62628

**Closed by bpasero** 2018-12-07 13:03 UTC
Labels: needs more info
