### ISSUE TITLE
Kill/detach issue 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71206] opened 2019-03-26 18:02 UTC
re #71063

* run cluster debugging as described here https://github.com/Microsoft/vscode/issues/71063#issuecomment-476669886
* child process 3 is selected, detach action shows
* select cluster, kill action shows
* select child process 3 again
* :bug: kill action still shows

![Mar-26-2019 19-00-05](https://user-images.githubusercontent.com/1794099/55021756-9c586300-4ff9-11e9-8218-f87b91f7393c.gif)

**Comment by misolori** [comment] 2019-03-26 22:19
Other weird behaviors to note:

- Before you hit the breakpoint, selecting any child processes selects the parent (like #71205)
- After you hit the breakpoint, you can select other child processes and detach from them as expected
- After detaching from a child process, this reverts back to this original issue

**Comment by weinand** [comment] 2019-03-26 22:28
this is a duplicate of #71183 (which is already targeted for the release).

**Closed** 2019-03-27 11:30 UTC
