### ISSUE TITLE
The formatting of JSX code inside JS is getting disturbed with Save

### ISSUE THREAD

**Issue by Lharesh** [microsoft/vscode#82337] opened 2019-10-11 08:46 UTC
Upon saving the code, the Visual Studio code is deformatting the JSX tags inside Javascript and showing errors.

**Comment by Lharesh** [comment] 2019-10-11 09:58
I have pasted the code before after save.
Before:
import React, { Component } from 'react';
import {gql} from 'apollo-boost';
import {graphql} from 'react-apollo';

//create query
const getBooksQuery = gql`
  {
    books{
      id
      name
      genre
    }
  }
`

class BookList extends Component {
    render() {
      console.log(this.props);
        return (
          <div>
            <ul id = "book-list" >
              <li> Book Name </li>
            </ul>
          </div>
        );
    }
};

export default graphql(getBooksQuery)(BookList);


After we save the code:-
import React, { Component } from 'react';
import { gql } from 'apollo-boost';
import { graphql } from 'react-apollo';

//create query
const getBooksQuery = gql `
  {
    books{
      id
      name
      genre
    }
  }
`

class BookList extends Component {
    render() {
        console.log(this.props);
        return ( <
            div >
            <
            ul id = "book-list" >
            <
            li > Book Name < /li> < /
            ul > <
            /div>
        );
    }
};

export default graphql(getBooksQuery)(BookList);

Thanks & Regards

Dr. Haresh

Mob: 9866533141

**Comment by IllusionMH** [comment] 2019-10-11 10:21
This code looks OK and formatted as expected.

Can you reproduce this issue with extensions disabled? <kbd>F1</kbd> and `>Developer: Reload With Extensions Disabled` ?
Do you have any other watchers that apply formatting?

**Comment by Lharesh** [comment] 2019-10-11 10:57
No, I don't have any other watchers.

Thanks & Regards

Dr. Haresh

Mob: 9866533141

**Comment by Lharesh** [comment] 2019-10-11 10:59
even with extensions disabled, it has the same problem.

Thanks & Regards

Dr. Haresh

Mob: 9866533141

**Comment by mjbvz** [comment] 2019-10-11 15:59
@Lharesh Please fill out the issue template: https://aka.ms/vscodeissuereporting Include a list of extensions you have installed

**Comment by mjbvz** [comment] 2019-10-21 20:47
Closing as not actionable without more information. Bugs like this are almost always caused by extensions

**Closed by mjbvz** 2019-10-21 20:47 UTC
Labels: needs more info
