### ISSUE TITLE
Several feature request or idea for future Visual Studio: Code

### ISSUE THREAD

**Issue by Hanif1601** [Microsoft/vscode#69700] opened 2019-03-02 10:06 UTC
Hello Microsoft and Visual Studio Code developer,
I'll give a several idea and feature request for future version of Visual Studio Code.
1. Add option to open a new window in File **but** Google Chrome's browser inside Visual Studio Code, _not user default browser_ on their PC for browse Internet quickly without user opening their browser (because everyone know this app is Chrome Stable 66 based),
1. Allow user to install Chrome extensions inside Visual Studio Code (like other Chrome-based browsers does), and the last...
1. Add option to synchronize settings using Microsoft Account across devices (if user install Visual Studio Code in other PC).

If you do this, well, I will wait for those. Thank you.

**Comment by rebornix** [comment] 2019-03-04 00:54
FR1 can be supported by an extension, FR 3 is a duplicate of #2743. For FR 2, IMO we won't support this feature in near term.

**Closed** 2019-03-04 00:54 UTC
Labels: *duplicate, *extension-candidate
