### ISSUE TITLE
Format On Save not working for certain files.

### ISSUE THREAD

**Issue by Alonski** [Microsoft/vscode#26653] opened 2017-05-15 12:36 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.16.0|
|Handlebars|andrejunges|0.2.0|
|htmltagwrap|bradgashler|0.0.3|
|path-intellisense|christian-kohler|1.4.2|
|vsc-ember-frost|ciena-blueplanet|0.0.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-gist|dbankier|0.5.3|
|vscode-npm-script|eg2|0.1.9|
|vscode-ember|emberjs|0.1.0|
|prettier-vscode|esbenp|0.17.1|
|tortoise-svn|fantasytyx|0.1.1|
|vsc-ember-cli|felixrieseberg|0.3.3|
|nativebase-snippets|GeekyAnts|0.5.22|
|beautify|HookyQR|1.0.2|
|csharpextensions|jchannon|1.3.0|
|vscode-stylefmt|mrmlnc|2.4.1|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|better-merge|pprice|0.7.0|
|vscode-icons|robertohuertasm|7.7.0|
|code-settings-sync|Shan|2.7.0|
|stylelint|shinnn|0.24.0|
|slack|sozercan|0.0.13|
|sort-lines|Tyriar|1.2.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1. Have formatOnSave set to True in settings
2. Save a large JS file. About 500+ Lines

--

The file isn't formatted.
This used to always work for me and now I can't figure out why it isn't working for me.

If I use Command Prompt + Format Document the file gets formatted.

**Comment by mjbvz** [comment] 2017-05-17 01:07
Can you please try disabling all extension to make sure one of them is not the root cause of this issue. Just start code with the `--disable-extension` command line flag.

**Comment by mjbvz** [comment] 2017-05-22 15:28
Closing as we do not have enough info to investigate further

**Closed by mjbvz** 2017-05-22 15:28 UTC
Labels: javascript, needs more info

**Comment by Alonski** [comment] 2017-05-22 15:34
Sorry I forgot about this. I will try again tomorrow

**Comment by Alonski** [comment] 2017-05-24 06:16
I switched to a better computer and now I can't reproduce this... Will report back if I see this again.
