### ISSUE TITLE
VS Code online cannot load script from Excel workbook

### ISSUE THREAD

**Issue by HuyNguyen7994** [microsoft/vscode#162698] opened 2022-10-04 21:25 UTC
Steps:
- Open workbook on Excel Online
- Launch VS Code 
- VS Code successfully connected to the workbook
- Loading script took forever

I tried the same step on a different result and the script still failed to load. My colleagues tried with his own workbook and it worked, so I see there must be something wrong with my Excel Online / VS Code connector. 

Version: 1.72.0-insider
Commit: a12109a6ac8cdb070d94d63a5dc3a3a8f53bad8c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53
Embedder: vscode.dev

**Comment by bamurtaugh** [comment] 2022-10-07 17:28
Thank you for filing @HuyNguyen7994, and I'm following up with the Excel team!

In the meantime, you able to see if the script loads if you use your colleague's workbook? That way we can try to narrow down if it's an issue specific to a workbook, script, or user account.

**Comment by bamurtaugh** [comment] 2022-10-11 19:55
Adding @wandyezj so that he can help here too!

**Comment by HuyNguyen7994** [comment] 2022-10-12 06:51
I cannot load script from my colleague as well

**Comment by wandyezj** [comment] 2022-10-12 17:30
Hello @HuyNguyen7994 

- What browser are you using? The User Agent suggests Microsoft Edge, is that right?
- Are you able to load and run the script in the normal editor?

**Comment by HuyNguyen7994** [comment] 2022-10-13 02:17
Hi,

> What browser are you using? The User Agent suggests Microsoft Edge, is that right?

The browser was Edge. But just now I tried with both Chrome and Edge and I cannot launch VS Code Online editor from Excel.

> Are you able to load and run the script in the normal editor?

I don't know how to load and run the script in normal editor.

**Comment by wandyezj** [comment] 2022-10-19 16:44
@HuyNguyen7994 Can you share an email address I can follow up with you on? I'd like to set up a meeting with you so you can show me the issue, if that's ok?

**Comment by HuyNguyen7994** [comment] 2022-10-22 08:48
@wandyezj my address is mnn024@maersk.com (also the account in trouble). Please send me an email first.

**Comment by bamurtaugh** [comment] 2022-12-12 22:00
Closing as it sounds like the issue is being addressed via email. If folks would like to discuss here as well, please just let me know. Thanks!

**Closed by bamurtaugh** 2022-12-12 22:00 UTC
Labels: info-needed, web
