### ISSUE TITLE
Ability to open new files within the same project in a new window

### ISSUE THREAD

**Issue by NathanBrianRoberts** [microsoft/vscode#120091] opened 2021-03-29 10:42 UTC
Hey there, 

In Visual Studio I can drag files within a project and they will open up in a new window on my other monitor. I have noticed that this is not the case in Visual Studio code, as it just creates a shortcut link. Could we have the ability to open files within the same project up on in a new window, without having to launch another vs code in order to achieve this. 

Nathan,

**Comment by IllusionMH** [comment] 2021-03-29 10:46
Looks like duplicate of #2686 and #10121

**Closed** 2021-03-29 12:01 UTC
Labels: *duplicate
