### ISSUE TITLE
White outline on Mac OS

### ISSUE THREAD

**Issue by vladimirkrstic** [Microsoft/vscode#63228] opened 2018-11-15 17:23 UTC
SInce updated to macOS 10.14 ugly outline is present on top border of VS Code window. 

<img width="2522" alt="screen shot 2018-11-15 at 6 17 30 pm" src="https://user-images.githubusercontent.com/1664428/48569903-41a05380-e903-11e8-80e8-fef46c3fae2a.png">

**Comment by misolori** [comment] 2018-11-15 18:44
This was fixed in v1.29.0, closing as duplicate of https://github.com/Microsoft/vscode/issues/54838

**Closed by misolori** 2018-11-15 18:44 UTC

**Comment by vladimirkrstic** [comment] 2018-11-15 22:29
I see it present on 1.29.0. A screenshot is of 1.29.0.

**Comment by misolori** [comment] 2018-11-15 22:43
@vladimirkrstic is your OS appearance set to "Light" or "Dark"? 

![image](https://user-images.githubusercontent.com/35271042/48586394-a39d9080-e8e4-11e8-9e6f-ef96467b9100.png)


I think what you're seeing is the new style for mojave:

![image](https://user-images.githubusercontent.com/35271042/48586419-bdd76e80-e8e4-11e8-98d8-a7b983231235.png)

**Comment by vladimirkrstic** [comment] 2018-11-15 22:53
@misolori It's on Light when on Dark it's looking cool. 

Light:
<img width="194" alt="screen shot 2018-11-15 at 11 46 27 pm" src="https://user-images.githubusercontent.com/1664428/48586886-84792000-e931-11e8-8c2c-874686ea4f78.png">
Dark:
<img width="194" alt="screen shot 2018-11-15 at 11 48 05 pm" src="https://user-images.githubusercontent.com/1664428/48586891-89d66a80-e931-11e8-913f-f7b7b4071d95.png">

Just noticed all Electron based apps have this white outline on top.

**Comment by misolori** [comment] 2018-11-15 22:57
Yea, here is the related issue for Electron https://github.com/electron/electron/issues/13164

**Comment by vladimirkrstic** [comment] 2018-11-15 23:23
I see, so Dark is fixed Light not yet.
