### ISSUE TITLE
Invalid keybindings.json bricks editor

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#9995] opened 2016-07-31 18:41 UTC
- VSCode Version: 1.3.1
- OS Version: Win 10

Steps to Reproduce:

1. Put array instead of string in keybindings command field
2. Restart editor

exact key binding that caused bricking the editor
```json
{
    "key": "ctrl+up",
    "command": ["scrollLineUp", "scrollLineUp"],
    "when": "editorTextFocus"
}
```

![](http://i.imgur.com/CkDKBLq.png)

**Comment by kieferrm** [comment] 2016-08-02 05:30
Duplicate of #9566.

**Closed by kieferrm** 2016-08-02 05:30 UTC
