### ISSUE TITLE
twice now VSCode has deleted my entire workspace but not put in trash

### ISSUE THREAD

**Issue by ldwight** [microsoft/vscode#171656] opened 2023-01-18 18:48 UTC
on Jan 13 and again just now, was working in VSCode and all of a sudden every file name is red and struck out. 
The Finder shows all the directories are gone, but weirdly, all the directories in "node_modules" are now at a higher level.
and...THERE IS NOTHING IN THE TRASH!!!
I recently installed chatGPT and have been using it.
Ran disk doctor and it reports all is fine.
Thankfully I pushed to git last week, but this is crazy!
I will remove the chatGPT extension and restore from the repository, but this is a huge problem.

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 11, 9, 6
Memory (System) | 16.00GB (0.51GB free)
Process Argv | --crash-reporter-id b7b01b4e-ee71-4c81-a0a8-54219d083123
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
   21	   180	 49372	code main
    0	    49	 49375	   gpu-process
    0	    16	 49377	   utility-network-service
    0	   229	 49378	   window (Get Started — skeleton)
    0	   115	 49462	   shared-process
    0	    33	 49465	     ptyHost
    0	    33	 49561	     fileWatcher
    0	     0	 74171	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 49463	   extensionHost
    0	    16	 49612	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/s4/7rpp8bvn1vn_3bzm1ylnlhy40000gn/T/vscode-typescript501/101b192b4598c74fcc87/tscancellation-699ef2426c3a6071c4d5.tmp* --globalPlugins typescript-tslint-plugin --pluginProbeLocations /Users/lili/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.3.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    66	 49613	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/s4/7rpp8bvn1vn_3bzm1ylnlhy40000gn/T/vscode-typescript501/101b192b4598c74fcc87/tscancellation-f7c56438a1bd26a8f63b.tmp* --globalPlugins typescript-tslint-plugin --pluginProbeLocations /Users/lili/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.3.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    33	 49619	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/lili/Library/Caches/typescript/4.9 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    16	 49614	     /Users/lili/.vscode/extensions/deque-systems.vscode-axe-linter-4.5.0/dist/bin/LSP-server-4.5.0 --stdio
    0	     0	 49641	     /Users/lili/.pyenv/versions/3.9.9/bin/python /Users/lili/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
    0	    33	 49648	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/lili/.vscode/extensions/ms-python.vscode-pylance-2023.1.20/dist/server.bundle.js --cancellationReceive=file:92c46dcd1f1264267875f9501eba514fff89c9856c --node-ipc --clientProcessId=49463
    0	    33	 49650	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=49463
    0	    33	 56591	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/main --node-ipc --clientProcessId=49463
    0	    82	 74152	   issue-reporter

Extension | Author (truncated) | Version
-- | -- | --
askcodi-vscode | Ask | 3.1.0
askjarvis-vscode | Bha | 2.0.4
vscode-expo | byC | 0.9.2
doxdocgen | csc | 1.4.0
dscodegpt | Dan | 1.0.6
vscode-axe-linter | deq | 4.5.0
better-cpp-syntax | jef | 1.17.2
vscode-docker | ms- | 1.23.3
isort | ms- | 2022.8.0
python | ms- | 2022.20.2
vscode-pylance | ms- | 2023.1.20
jupyter | ms- | 2022.11.1003412109
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.13
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
remote-containers | ms- | 0.266.1
remote-ssh | ms- | 0.94.0
remote-ssh-edit | ms- | 0.84.0
remote-wsl | ms- | 0.72.0
vscode-remote-extensionpack | ms- | 0.23.0
cmake-tools | ms- | 1.12.27
cpptools | ms- | 1.13.9
cpptools-extension-pack | ms- | 1.3.0
js-debug-nightly | ms- | 2023.1.1617
node-debug2 | ms- | 1.43.0
remote-explorer | ms- | 0.0.3
vscode-typescript-tslint-plugin | ms- | 1.3.4
vscode-react-native | msj | 1.10.0
cmake | twx | 0.0.17

<span style="color: rgb(88, 110, 117); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(221, 214, 193); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(1 theme extensions excluded)</span>

**Comment by lszomoru** [comment] 2023-01-20 10:12
@ldwight, thank you very much for filing this issue. If you are suspecting that the issue is caused by an extension that you have installed, I would suggest that you file an issue in the extension's repository in order to get assistance from the extension authors. I will go ahead and close this issue, but in case you are able to reproduce the problem with extensions disabled please feel free to reopen the issue and we will investigate this further. Thanks!

**Closed by lszomoru** 2023-01-20 10:12 UTC
