### ISSUE TITLE
Feature Request: Support drag/drop api for custom explorer trees

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#47541] opened 2018-04-10 04:14 UTC
Feature Request

Support being able to drag/drop nodes in a custom explorer. 

Scenario: I want to drag a local docker image to a hosted repository. In the extension, I would tag and push the image, but the user would just need to drag the image around.  Related, I would like to drag a local image or an image in a repository to the Azure App Service tree to deploy that image as a container to the site.

**Comment by dongryphon** [comment] 2019-08-24 23:49
Sad that this hasn't been pushed for as I don't see how it could have been overlooked for extension authoring. I assumed because the Files view could drag items, so could my custom tree... wasted a bit of time looking over the docs for how to do it and eventually came here.

I want this for a WYSIWYG designer to drag items from a catalog (custom tree) and drop them on a design canvas (a webview).

**Comment by Gama11** [comment] 2019-08-26 11:02
This looks like a duplicate of #32592?

**Closed** 2019-10-09 13:58 UTC
Labels: *duplicate, feature-request, file-explorer
