### ISSUE TITLE
Find-history

### ISSUE THREAD

**Issue by maratumba** [microsoft/vscode#110065] opened 2020-11-06 09:36 UTC
(searched for existing issues, apologies if I missed an existing feature request similar to this)

See previous searches in "find" and "find in files". When you're going back and forth between different searches, which I do a lot, it would really help.

**Comment by IllusionMH** [comment] 2020-11-06 09:52
/duplicate of #23099

You already can access history in Find in files and Find (in editor) with <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> (however usually simple <kbd>↑</kbd> and <kbd>↓</kbd> works)

**Closed** 2020-11-06 09:53 UTC
Labels: *duplicate
