### ISSUE TITLE
【vscode.dev】jQuery library. Entering $. will not automatically prompt jQuery information

### ISSUE THREAD

**Issue by darrenweb** [microsoft/vscode#226572] opened 2024-08-26 02:59 UTC
In https://vscode.dev, click the [open folder] button to open the project containing the jQuery library. and in js file entering $. will not automatically prompt jQuery information.
Here are the steps：

1.Create a jquery demo folder on my local computer,，
2.npm i @types/jquery
3.Open the URL https://vscode.dev through the latest Chrome browser, click open folder, and select the jquerydemo folder created in the first step above
4.Open the index.js file and enter $. I hope to see jQuery information, but there is no prompt.

In the previous version of vscode.dev, jquery information can be prompted normally, 
and In the Visual Studio Code  jquery information can be prompted normally, 
but the latest vscode.dev version cannot prompt it.

look this.
![27`Y~MC5W5 PF 1W_V@D6L9](https://github.com/user-attachments/assets/5bb9a799-75f9-4f36-a877-0c5178ea5da3)

**Comment by mjbvz** [comment] 2024-08-27 18:05
Duplicate of #182791

Should work in the latest insiders version of vscode.dev

**Closed by mjbvz** 2024-08-27 18:05 UTC
