### ISSUE TITLE
Failed to auto update on windows

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#46199] opened 2018-03-20 17:53 UTC
The progress window did not stop showing progress (see below) and this is the log
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/1830522/vscode-inno-updater.log)

![image](https://user-images.githubusercontent.com/172399/37673163-d32fbc10-2c6f-11e8-904b-8a75689294ec.png)

**Comment by joaomoreno** [comment] 2018-03-21 07:34
Why is Code still running in the background?

@bpasero I call lifecycleService.quit here:

https://github.com/Microsoft/vscode/blob/5cc9bf1f7dffe52d79aaf4102cad8277dd9384a5/src/vs/platform/update/electron-main/abstractUpdateService.ts#L143

It seems it wasn't vetod, yet the app stays running.

Any ideas?

**Comment by joaomoreno** [comment] 2018-03-21 07:35
@egamma This would also happen with the legacy updates. If Code isn't shutdown, then something else is very wrong.

**Comment by bpasero** [comment] 2018-03-21 09:09
@joaomoreno I added more logging to that `quit` method but this will only appear when running with `trace` logging enabled. 

Bottom line, it could be that a previous call to quit was found that has not completed yet. In that case the call to `quit` is basically a no-op until the previous call returns. However looking at the code I am not sure how this can happen, there is basically two scenarios:
* we get a veto and the shutdown stops, in that case we reset the pending quit promise
* we get no veto and in that case the `will-quit` event should fire because all windows closed

I just tried and could not reproduce. In theory this could be related to the changes around the shared process disposal that we did for this milestone.

**Comment by bpasero** [comment] 2018-03-21 09:10
@egamma it would be great if you could go 1 version back and really try to reproduce what you did to see if this persists 👍

**Comment by egamma** [comment] 2018-03-22 09:39
@bpasero I went back a version, but I could not reproduce the problem, sorry.

**Comment by joaomoreno** [comment] 2018-03-26 13:37
Closing for now.

**Closed by joaomoreno** 2018-03-26 13:37 UTC
Labels: needs more info
