### ISSUE TITLE
Multicursor bug in html files

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#85923] opened 2019-12-02 12:44 UTC
Issue Type: <b>Bug</b>

Open any html file. Put cursor on a tag. Observe multicusror becomes active. From now on you cant do any selection. 
Now move the cursor to the end of the tag. Observe cursor starts blinking, `Ln X, Col Y` in right bottom corner goes crazy cause cursor position gets changed all the time as far as I understand. Also 2 of the renderer processes start consuming 100% of the CPU.
This is reproducible with all extensions disabled and does not happen in stable version.

https://youtu.be/Piat_U2iOZs

VS Code version: Code - Insiders 1.41.0-insider (7cf4cca47aa025a590fc939af54932042302be63, 2019-12-02T05:26:29.458Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_10521096|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
vscode-todo-plus|fab|4.14.1
vscode-pull-request-github|Git|0.13.0
rainbow-csv|mec|1.3.1
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.2
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.20
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.6.0
vim|vsc|1.11.3
local-history|xyz|1.7.0
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-12-02 16:14
@ivanvoznyakovsky video is private, so can't see behavior (probably should be changed to owners of direct link).

From description it looks related to #47069 tagging @octref

**Comment by octref** [comment] 2019-12-02 21:00
Duplicate of #85715.

**Closed by octref** 2019-12-02 21:00 UTC
Labels: html

**Comment by ivanvoznyakovsky** [comment] 2019-12-02 21:18
@IllusionMH made the video public. old habit 😄 and yes, #85715 looks like the same bug.
