### ISSUE TITLE
code --status and reporting performance issue fails without /bin/ps

### ISSUE THREAD

**Issue by hyperfekt** [Microsoft/vscode#70390] opened 2019-03-13 11:06 UTC
Issue Type: <b>Bug</b>

When trying to use `code --status` as instructed by [the wiki](https://github.com/Microsoft/vscode/wiki/Performance-Issues), it fails with
```
[main 2019-03-13T11:01:51.754Z] Error: Command failed: /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
/bin/sh: /bin/ps: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```
Relatedly, trying to report a performance issue from within Visual Studio Code is impossible, as the submit button hangs with `Loading data...`.
The fields under `Include my currently running processes` and `Include my workspace metadata` are empty, and unchecking them does not enable the submit button.

I am using NixOS which doesn't have any binaries except `sh`in `/bin`, so relying on `/bin/ps` cannot work.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.20.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 915)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.31GB (16.35GB free)|
|Process Argv|--skip-getting-started --extensions-dir /nix/store/dkz0f461qxdipm7p38ds08p7khpbd09y-vscode-extensions-1.31.1/share/vscode/extensions --wait --waitMarkerFilePath /tmp/nsqbfxvac|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment] 2019-04-11 00:07
Duplicate of https://github.com/Microsoft/vscode/issues/49612

**Closed** 2019-04-11 00:07 UTC
Labels: bug
