### ISSUE TITLE
stdscr.getkey() in curses executed through IntegratedTerminal on VSCode identify 'Arrow left' as 'KEY_B1' instead of 'KEY_LEFT'

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode#130075] opened 2021-07-19 06:18 UTC
## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Relevant/affected Python packages and their versions: 
-   Relevant/affected Python-related VS Code extensions and their versions: 
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

PC: pip install windows-curses

```
import curses

def main(stdscr):
    input = stdscr.getkey()
    curses.endwin()
    print(input)

curses.wrapper(main)
```

In the integratedTerminal(Powershell or CMD):

Arrow up is 'KEY_UP': 259,
Arrow down is 'KEY_DOWN': 258
Arrow right is 'KEY_RIGHT': 261
Arrow left is 'KEY_LEFT': 260,

## Actual behaviour

```
import curses

def main(stdscr):
    input = stdscr.getkey()
    curses.endwin()
    print(input)

curses.wrapper(main)
```

In the integratedTerminal(Powershell or CMD):

Arrow up is 450 (KEY_A2) instead of 'KEY_UP': 259,
Arrow down is 456 (KEY_C2) instead of 'KEY_DOWN': 258
Arrow right is 454 (KEY_B3) instead of 'KEY_RIGHT': 261
Arrow left is 452 (KEY_B1) instead of 'KEY_LEFT': 260,

While externalTerminal or CMD and Powershell works well.

**Comment by ChrisIdema** [comment] 2021-08-24 14:49
I created a similar issue a year ago: https://github.com/microsoft/vscode/issues/112405. Microsoft closed it without a fix. Since you quoted part of my issue, so you must be aware, soI'm adding the reference to that issue so that more people can find this. I also created an issue for the windows-curses repo, but they haven't responded yet: https://github.com/zephyrproject-rtos/windows-curses/issues/23.

**Comment by Tyriar** [comment] 2021-08-30 17:13
This is either an issue with windows-curses or the terminal backend we use (conpty) which is what is built into Windows Terminal. You could try repro in Windows terminal and report to [microsoft/terminal](https://github.com/microsoft/terminal/) but it looks like https://github.com/zephyrproject-rtos/windows-curses/issues/23 is probably the right place to track it.

**Closed by Tyriar** 2021-08-30 17:13 UTC

**Comment by ppescher** [comment] 2022-10-01 21:55
This issue cannot be closed. The problem is still there after more than one year!

It seems that anything using the ncurses library on Windows does not receive arrow keys when it runs inside the vscode integrated terminals (powershell or cmd).
I always had this kind of issue with menuconfig inside vscode, and only there, it works perfectly in Command Prompt, native Powershell or even the new Windows Terminal.

So it must be related to vscode and really I feel it should have been investigated more. Unfortunately I don't have the background required to fix this myself or even attempt to do it.
I don't understand how this could have gone unnoticed and neglected all this time, as if I were the only one experiencing this problem, or one of the very few apparently.

Sorry for the rant, but it's really frustrating. I wish I could be more helpful in the reasolution of this long standing issue.

**Comment by Tyriar** [comment] 2025-09-28 03:38
@lygstate that makes sense given it's likely related to conpty. You can try `"terminal.integrated.windowsUseConptyDll": true` to move to a newer version bundled with VS Code, though note there are some other problems with that which is why it's off by default. In general it should give a better experience.
