### ISSUE TITLE
ADD A LOGIN SYSTEM

### ISSUE THREAD

**Issue by sahil-patel6** [Microsoft/vscode#58800] opened 2018-09-17 10:42 UTC
I would like to request you to add login system so we can sync our settings, installed extensions,etc so we can use throughout our devices.. I know this feature has been requested already by many users but I expect it would be nice to create another issue so you guys can know that  we really need that feature badly. It is a good feature, it will compete with other text editors like atom,sublime,vim,etc....

I hope you guys will add in the next update...

**Comment by V-ed** [comment] 2018-09-17 15:34
Duplicate of #2743

Creating another issue with all caps, begging and even aknowledging that this request is already present for this program won't help make it happen faster. Give a :+1: to issues you want to see being added and hope that it gets added quicker either by a PR of a community member, a member of Microsoft itself or via an extension.

While I know it may not fit everyone's ideals, the [Settings Sync extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) provides most of the features wanted in the issue I linked and in yours. It's an extension, and I myself would rather want to have it in the core of VSCode, but we have to deal with what we have now.

Please follow the [Submitting bugs and Suggestions guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) next time, even if you probably know them already.

Have a great day!

**Comment by octref** [comment] 2018-09-17 21:12
@V-ed Thanks a lot for lining to duplicate 👍

**Closed** 2018-09-17 21:12 UTC
Labels: *duplicate, extensions
