### ISSUE TITLE
Wrong syntax highlight for JavaScript

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#3610] opened 2016-03-02 04:29 UTC
`var` and `let` at the head of variable names and property names are colored.

![image](https://cloud.githubusercontent.com/assets/1937871/13450591/5bae9b5e-e07a-11e5-958d-9afce4e57495.png)

```
Version 0.10.10-insider
Commit 97d4ad1c55a82369f65078406ed770e8a34055fc
Date 2016-02-29T16:00:09.098Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by aeschli** [comment] 2016-03-02 08:41
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed by aeschli** 2016-03-02 08:41 UTC
Labels: js
