### ISSUE TITLE
Scrolling cause text line shake vertically.

### ISSUE THREAD

**Issue by nerocui** [Microsoft/vscode#23192] opened 2017-03-24 23:42 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|beautify|HookyQR|1.0.2|
|cpptools|ms-vscode|0.10.3|
|csharp|ms-vscode|1.8.0|;

---

Steps to Reproduce:

1.dude, just scroll
2. look at the lines closely

**Comment by deprilula28** [comment] 2017-03-25 17:35
Try messing with the size with Ctrl+ and Ctrl-, it was doing that to me at first as well

**Comment by rebornix** [comment] 2017-04-06 18:48
Can you provide a gif/recording to help troubleshoot the problem?

**Comment by amb** [comment] 2017-04-20 09:35
I can confirm this bug. 
![jumping](https://cloud.githubusercontent.com/assets/99240/25223986/b428de66-25c5-11e7-95ea-f77b8fd79acc.gif)

**Comment by alexandrudima** [comment] 2017-05-11 12:01
Duplicate of #22008

**Closed by alexandrudima** 2017-05-11 12:01 UTC
Labels: editor, needs more info
