### ISSUE TITLE
Incorrect Recomendation Engine Navigation

### ISSUE THREAD

**Issue by samtholiya** [Microsoft/vscode#20343] opened 2017-02-09 18:43 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-react-instyle|bookworms|0.0.2|
|csharp|ms-vscode|1.7.0|
|vscode-react-native-storybooks|Orta|0.1.0|
|material-icon-theme|PKief|1.3.2|
|vscode-react-native|vsmobile|0.2.5|

---

Steps to Reproduce:

1. Open a java file.
2. Notification with recommendation of Language support for java by Red Hat plugin will appear
3. Click on show recommendations 

Output Expected : 
Language support for Java by Red Hat as an option

Output Received:
![screenshot 16](https://cloud.githubusercontent.com/assets/11261548/22797759/8ea1aac8-ef25-11e6-85f1-ed66aaab1994.png)

**Comment by Tyriar** [comment] 2017-02-09 22:49
I can repro, this is the message:

![image](https://cloud.githubusercontent.com/assets/2193314/22806435/e83d9f1e-eed6-11e6-807c-df32392e6b13.png)

**Comment by waderyan** [comment] 2017-02-10 17:49
Confirmed this on Insiders as well. The code is setup properly in [product.json](https://github.com/Microsoft/vscode-distro/blob/master/quality/insider/product.json#L81). 

I'll need @joaomoreno to take a look.

**Comment by joaomoreno** [comment] 2017-02-13 07:29
Duplicate of #19613. Not fixed in 1.9.1, but in Insiders only so far.

**Closed by joaomoreno** 2017-02-13 07:30 UTC
Labels: bug, important
