### ISSUE TITLE
Can't open the same directory in multiple instances of VS Code

### ISSUE THREAD

**Issue by goleary** [Microsoft/vscode#18203] opened 2017-01-06 01:24 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|Angular2|johnpapa|1.0.2|
|code-beautifier|michelemelluso|1.6.2|
|cordova-tools|vsmobile|1.2.5|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Open folder in vs code
2. Start new instance of VS code

**Comment by Spown** [comment] 2017-01-06 03:51
it is a feature, not a bug.

**Comment by sandy081** [comment] 2017-01-06 09:15
Duplicate of #48

**Closed by sandy081** 2017-01-06 09:15 UTC
Labels: duplicate
