### ISSUE TITLE
[themes] settings: support for multiple theme names in VSCode colorCustomization

### ISSUE THREAD

**Issue by nnnkit** [microsoft/vscode#71842] opened 2019-04-06 07:19 UTC
You should be able to add multiple Theme Names for colour customisation. May be like this

```
workbench.colorCustomizations": {
 "[Night Owl No Italics, Night Owl]": {
   "activityBar.background": "#000C1D",
   "activityBar.border": "#102a44",
   "sideBar.background": "#001122",
   "sideBar.border": "#102a44",
   "sideBar.foreground": "#8BADC1"
  }
}
```

If you have to do that right now it's not supported you have to repeat the same for two different theme like this.

```
workbench.colorCustomizations": {
 "[Night Owl]": {
   "activityBar.background": "#000C1D",
   "activityBar.border": "#102a44",
   "sideBar.background": "#001122",
   "sideBar.border": "#102a44",
   "sideBar.foreground": "#8BADC1"
  },
 "[Night Owl No Italics]": {
   "activityBar.background": "#000C1D",
   "activityBar.border": "#102a44",
   "sideBar.background": "#001122",
   "sideBar.border": "#102a44",
   "sideBar.foreground": "#8BADC1"
  }
}
```

**Comment by aeschli** [comment] 2020-08-24 07:10
duplicate of #103694

**Closed** 2020-08-24 12:38 UTC
Labels: *duplicate, feature-request, themes
