### ISSUE TITLE
 Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#56634] opened 2018-08-17 06:30 UTC
Issue Id: <b>20c42adb-c8d3-efb3-31df-8ce21a8ec380</b><br /><br />*Versions* <br />- 1.26.0<br />*Stack* <br />TypeError: Cannot read property 'remove' of undefined<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#269:22 (_render)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L269:22 (_render))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#256:7 (setItems)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L256:7 (setItems))<br />[/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#227:16 (updateBreadcrumbs)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L227:16 (updateBreadcrumbs))<br />[/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#231:2 (update)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L231:2 (update))<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#141:57 (updateBreadcrumbsControl)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L141:57 (updateBreadcrumbsControl))<br />[/vs/workbench/browser/parts/editor/tabsTitleControl.ts#262:7 (openEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L262:7 (openEditor))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#792:24 (doShowEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L792:24 (doShowEditor))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#766:32 (doOpenEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L766:32 (doOpenEditor))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#735:14 (openEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L735:14 (openEditor))<br />[/vs/workbench/services/editor/browser/editorService.ts#249:15 (doOpenEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/services/editor/browser/editorService.ts#L249:15 (doOpenEditor))<br />[/vs/workbench/services/editor/browser/editorService.ts#242:15 (openEditor)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/services/editor/browser/editorService.ts#L242:15 (openEditor))<br />[/vs/workbench/parts/search/browser/searchView.ts#1436:28 (open)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/parts/search/browser/searchView.ts#L1436:28 (open))<br />[/vs/workbench/parts/search/browser/searchView.ts#1430:8 (onFocus)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/parts/search/browser/searchView.ts#L1430:8 (onFocus))<br />[/vs/workbench/parts/search/browser/searchView.ts#580:11 (call)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/parts/search/browser/searchView.ts#L580:11 (call))<br />[/vs/base/common/event.ts#140:15](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/common/event.ts#L140:15)<br />    at out/v<br />

**Comment by ssbarnea** [comment] 2018-08-21 15:26
I am getting this with 1.26.1 which makes me believe is not a duplicate.

**Comment by jrieken** [comment] 2018-08-21 15:41
@ssbarnea Do you have steps to reproduce?

**Comment by jrieken** [comment] 2018-08-23 14:55
Tweaked the node management of the breadcrumbs widget and added extra logic to print more info when errors occur. Closing this for new telemetry issues

**Closed by jrieken** 2018-08-23 14:55 UTC
Labels: error-telemetry

**Comment by ssbarnea** [comment] 2018-08-23 16:59
Thanks, this should help finding root causes for these errors. I am sure is a plugin, but who has time to bisect all these to spot the culprit.

**Comment by CharlieEtienne** [comment] 2018-09-04 11:53
I'm having the same error when I hit Ctrl+W to close a tab. The breadcrumb stop working then.

But it seems Material Theme update 2.4 is fixing this issue. (Not sure)
