### ISSUE TITLE
Automatically use TypeScript version from workspace on trusted projects.

### ISSUE THREAD

**Issue by fudom** [microsoft/vscode#200735] opened 2023-12-13 12:33 UTC
Currently you have to separatly allow execution of workspace tsdk. It feels unnecessarily redundant in an already trusted project (workspace). It should be automatically use the workspace version. Otherwise it leads to unexpected problems in the team. There is a notification about this that disappears after a short while. I see no reason why not just allow it automatically on a trusted workspace. Any concerns?

![image](https://github.com/microsoft/vscode/assets/143608856/2b4ac610-0693-4587-811c-cace0a2591a7)

**Comment by mjbvz** [comment] 2023-12-14 00:59
Duplicate of #135713

**Closed by mjbvz** 2023-12-14 00:59 UTC
