### ISSUE TITLE
C# Language Extension missing?!

### ISSUE THREAD

**Issue by N3r0Nu77** [Microsoft/vscode#2062] opened 2016-01-16 21:52 UTC
After updating I now receive an error.

[c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o/package.json: ENOENT: no such file or directory, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\csharp-o\package.json'

Upon checking I found that the entire c# extension is empty and have found no solutions yet to remedy this.

**Comment by jrieken** [comment] 2016-01-18 10:41
That's an issue with the installer

**Comment by joaomoreno** [comment] 2016-01-18 13:17
Duplicate of #1605

**Closed by joaomoreno** 2016-01-18 13:17 UTC
Labels: c#
