### ISSUE TITLE
Persistent result view for Find All References

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/vscode#25212] opened 2017-04-23 23:23 UTC
- VSCode Version: 1.11.2
- OS Version: Windows 10.0.14393

I'm trying to explore the code in a large (~25000 LOC) TypeScript file, and it gets a little confusing when you're only able to look at the find references result for a single function at a time. I had two feature requests:

 - Would it be possible to give users the option to disable the code-attached Find References result window and simply display it as a fixed pane somewhere?
 - Would it be possible to display a history of Find References searches and their results? Something similar to Notepad++'s find results:

![Notepad++ find results](https://ldzfpw.by3302.livefilestore.com/y4mqGe8s5zgmKkAVaIZgSe7QPIdPU1Lc_G9GUWbSOxKg_Dh2LC_iYXfxI88ZyfmbrA6Ptcya2OTsTolCUn7gxFj7NS0N4cvImTr6IDf0fTfRpqwKUMXeXS9BiIcGK0PbXiWLAxnl7LQZpyISjioeU-gWBGrclX4xG_XCM2xRVWgRHpgAAqv4tLt-PDW5Z0hZda_LGCmGhOtWnNaSYljKgYUlg/2017-04-23_19-20-34.gif?psid=1)

A more general solution to the problem would be some kind of symbol explorer that lets you inspect the complete reference graph of any symbol, however this might be prohibitively expensive given how the language server protocol works.

**Comment by jrieken** [comment] 2017-04-25 06:53
dupe of https://github.com/Microsoft/vscode/issues/22261

**Closed by jrieken** 2017-04-25 06:53 UTC
Labels: feature-request, ux
