### ISSUE TITLE
Fetch Online Package Info data not correct or missing

### ISSUE THREAD

**Issue by GHMatty** [microsoft/vscode#108591] opened 2020-10-13 12:30 UTC
- VSCode Version:
- OS Version:
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open Typescript project
2. Open package.json
3. Hover over dependencies library version number of typescript lib
4. A wrong latest version number is shown - 'Latest version: 3.4.3'
5. Open console and type 'npm view typescript'
6. The console shows the correct npm view data of the typescript lib with latest version 4.0.3
7. A hover over an private library shows NO info at all.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gjsjohnmurray** [comment] 2020-10-13 14:27
Possible duplicate of #108580

**Comment by mjbvz** [comment] 2020-10-13 18:16
Yes, looks like a duplicate of #108580

**Closed by mjbvz** 2020-10-13 18:16 UTC
