### ISSUE TITLE
A quote character on its own line appears to mess up terminal link detection

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#158752] opened 2022-08-22 12:51 UTC
![Recording 2022-08-22 at 08 51 14](https://user-images.githubusercontent.com/4544166/185925424-8a67a980-803b-474d-b252-388e97814396.gif)

Only seems to appear if I resize the terminal such that a `"` is on its own line.

**Comment by Tyriar** [comment] 2022-12-07 21:00
Cannot repro:


![Image](https://user-images.githubusercontent.com/2193314/206294594-ca52f334-4dd1-40f5-8e19-02fa77503c98.png)

**Comment by lramos15** [comment] 2022-12-08 18:40
I can still reproduce this? For example cat this file to your terminal

```
...writing /Users/fake/path-to-project/some-repo/generated/detailed-diff.json
...writing /Users/fake/path-to-project/some-repo/generated/revived.json
...writing /Users/fake/path-to-project/some-repo/generated/before-row-declaration-diff.json
...writing 20 rows to "/Users/fake/path-to-project/some-repo/generated/newProperties.csv"
...writing 10 rows to "/Users/fake/path-to-project/some-repo/generated/newEvents.csv"
...writing 30 rows to "/Users/fake/path-to-project/some-repo/generated/new.csv"
...writing 3 rows to "/Users/fake/path-to-project/some-repo/generated/retiredEvents.csv"
...writing 202 rows to "/Users/fake/path-to-project/some-repo/generated/retiredProperties.csv"
...writing 3186 rows to "/Users/fake/path-to-project/some-repo/generated/retiredCommonProperties.csv"
...writing 205 rows to "/Users/fake/path-to-project/some-repo/generated/retired.csv"
...writing 5 rows to "/Users/fake/path-to-project/some-repo/generated/updatedProperties.csv"
...writing 6 rows to "/Users/fake/path-to-project/some-repo/generated/updatedCommonProperties.csv"
...writing 5 rows to "/Users/fake/path-to-project/some-repo/generated/updated.csv"
...writing 4 rows to "/Users/fake/path-to-project/some-repo/generated/reassignedProperties.csv"
...writing 4 rows to "/Users/fake/path-to-project/some-repo/generated/reassigned.csv"
...writing 214 rows to "/Users/fake/path-to-project/some-repo/generated/applyThis.csv"
...writing 100 rows to "/Users/fake/path-to-project/some-repo/generated/applyThis-1.csv"
...writing 100 rows to "/Users/fake/path-to-project/some-repo/generated/applyThis-2.csv"
...writing 14 rows to "/Users/fake/path-to-project/some-repo/generated/applyThis-3.csv"
...writing 46427 rows to "/Users/fake/path-to-project/some-repo/generated/diffable.csv"
```

Then drag until a quote is the only thing on one of the lines. This causes the link detection to detect everything below that quote.

**Comment by Tyriar** [comment] 2022-12-08 19:05
Couldn't repro on Windows but I do see some offset problem after the resizes:

![image](https://user-images.githubusercontent.com/2193314/206544850-c432c625-8b62-4d1b-92f5-3fb49a33cbb5.png)

Probably an issue with reflow (mac/Linux)

**Comment by Tyriar** [comment] 2022-12-21 20:19
In tried on my mac and I still can't reproduce:

![Recording 2022-12-21 at 12 18 35](https://user-images.githubusercontent.com/2193314/208995665-ae611053-1a98-44e0-81c4-099844f9b2d0.gif)

**Comment by lramos15** [comment] 2022-12-22 14:21
Still able to reproduce this, have passed repo steps regarding the private repo offline.

**Comment by Tyriar** [comment] 2022-12-23 01:09
Still struggling to repro, I did notice sometimes it's off by 1 or 2 cells in either direction like this though:

<img width="852" alt="Screenshot 2022-12-22 at 5 08 03 pm" src="https://user-images.githubusercontent.com/2193314/209251096-dd291bb7-b903-4311-8df1-b31738e9e922.png">

**Comment by Tyriar** [comment] 2022-12-23 01:13
This happens because of line caching, hovering a wrapped line and then resizing it a little such that the line is still there, the line range will be off:

<img width="866" alt="Screenshot 2022-12-22 at 5 12 44 pm" src="https://user-images.githubusercontent.com/2193314/209251389-9a4db775-3084-41b1-9347-d1da1a09b993.png">

**Comment by Tyriar** [comment] 2022-12-27 14:24
That one repro's upstream:

<img width="793" alt="Screenshot 2022-12-27 at 6 24 10 am" src="https://user-images.githubusercontent.com/2193314/209680218-345bdd43-c4e8-4015-a266-fa7c056f270d.png">

Since I can't repro your actual issue I'll fix this and see if that's the underlying issue.

**Comment by lramos15** [comment] 2022-12-28 20:04
Can still repro this building OSS. Note you do not need to resize the terminal for this to occur if it's already the correct size when you run the task.

**Comment by lramos15** [comment] 2022-12-28 20:52
Update cannot repro when debugging. So odd 🤔

**Comment by Tyriar** [comment] 2023-05-08 13:47
Still can't reproduce so closing as unactionable until there's a solid repro.

Insiders:

<img width="632" alt="Screenshot 2023-05-08 at 6 43 07 am" src="https://user-images.githubusercontent.com/2193314/236840078-c43a77ca-f292-49e9-b42e-9c35853f1554.png">

OSS:

<img width="637" alt="Screenshot 2023-05-08 at 6 44 55 am" src="https://user-images.githubusercontent.com/2193314/236840405-043ec8c6-e27d-4424-a8cc-5b4337544a56.png">

OSS debugging:

<img width="633" alt="Screenshot 2023-05-08 at 6 46 16 am" src="https://user-images.githubusercontent.com/2193314/236840742-3e510580-bedb-4c13-9353-f4c40a1045ef.png">

cat this file:

```
...writing /Users/daimms/dev/microsoft/vscode/src/bootstrap-amd.js
...writing /Users/daimms/dev/microsoft/vscode/src/bootstrap-fork.js
...writing /Users/daimms/dev/microsoft/vscode/src/bootstrap-node.js
...writing 20 rows to "/Users/daimms/dev/microsoft/vscode/src/bootstrap-window.js"
...writing 10 rows to "/Users/daimms/dev/microsoft/vscode/src/bootstrap.js"
...writing 30 rows to "/Users/daimms/dev/microsoft/vscode/src/buildfile.js"
...writing 3 rows to "/Users/daimms/dev/microsoft/vscode/src/cli.js"
...writing 202 rows to "/Users/daimms/dev/microsoft/vscode/src/main.js"
...writing 3186 rows to "/Users/daimms/dev/microsoft/vscode/src/server-cli.js"
...writing 205 rows to "/Users/daimms/dev/microsoft/vscode/src/server-main.js"
...writing 5 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.base.json"
...writing 6 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.json"
...writing 5 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.monaco.json"
...writing 4 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.tsec.json"
...writing 4 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.vscode-dts.json"
...writing 214 rows to "/Users/daimms/dev/microsoft/vscode/src/tsconfig.vscode-proposed-dts.json"
```

**Closed by Tyriar** 2023-05-08 13:47 UTC
Labels: bug, verification-found, terminal-links
