### ISSUE TITLE
Some folders don't use ~ when showing full path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103967] opened 2020-08-04 17:12 UTC
- Show the Open Recent menu
- Some folders in my home directory use `~`, some don't, probably a recent regression

![image](https://user-images.githubusercontent.com/323878/89323694-fbd97080-d63a-11ea-8c52-2e9406407725.png)

I think you have worked on the file labels @isidorn? Sorry if I'm misremembering

**Comment by roblourens** [comment] 2020-08-04 17:13
I don't have repro steps to get them to show up one way or another

**Comment by isidorn** [comment] 2020-08-05 07:47
Yes, I have worked on the file labels. Assigning to July to investiage.

**Comment by isidorn** [comment] 2020-08-06 13:06
I investigate a bit into this and I believe the problem is the following, the workspace asks for the label of the workspace very early, before the formatter is registered. It goes down this path
https://github.com/microsoft/vscode/blob/eebfafcc96523075cdca0e033a28ef3b5346af5e/src/vs/workbench/services/label/common/labelService.ts#L141
Where we use a depracted `resolvedUserHome` in order for the method to be sync and not async.

I believe we had this problem since we introduced an async fetching of user home.

More details can be found here https://github.com/microsoft/vscode/issues/83213

**Closed** 2020-11-02 18:07 UTC
Labels: *out-of-scope, label-provider
