### ISSUE TITLE
Undo bug in Find

### ISSUE THREAD

**Issue by Theoda** [microsoft/vscode#73606] opened 2019-05-11 04:23 UTC
Issue Type: <b>Bug</b>

Here is how to reproduce:
1. Start a new file in VS Code
2. Input like this:
``` plain
abc
def
```
3. Select `def` and press Ctrl+F
4. Delete text in Find window and type `ab`
5. Now select `def` and press Ctrl+F again
6. Focus on textbox in Find window and press Ctrl+Z, and then the bug occurs (it is expected to be `ab`, but it's `df` here)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|Memory (System)|7.88GB (1.52GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.0
code-runner|for|0.9.9
latex-workshop|Jam|6.5.1
python|ms-|2019.4.12954
cpptools|ms-|0.23.0

(2 theme extensions excluded)

</details>

**Comment by RyanJeon** [comment] 2019-06-27 16:12
Seems like whatever is keeping track of what to change on Ctrl+Z is not being updated when you do a Select + Ctrl + F. I'm going to give this a shot.

**Comment by rebornix** [comment] 2019-07-25 22:05
/duplicate of https://github.com/microsoft/vscode/issues/27035 actually.

**Closed** 2019-07-25 22:05 UTC
Labels: *duplicate, bug, editor-find
