### ISSUE TITLE
Breakpoints disappears from gutter when debugging Node in Docker

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#34982] opened 2017-09-25 18:12 UTC
Reported by @johnpapa

Breakpoints disappears from gutter when debugging Node in Docker, but are still hit.

Details: Insiders + Node 6 + Inspector protocol

![image001](https://user-images.githubusercontent.com/173559/30823837-7138d798-a1e2-11e7-80fa-44fbccc95e1f.png)
![image002](https://user-images.githubusercontent.com/173559/30823844-73f29622-a1e2-11e7-9c0f-b492ce9ac0cc.png)

**Comment by isidorn** [comment] 2017-09-26 07:52
1. What happens if you click on the breakpoint pane on the routes.js breakpoint?
2. What happens if you click on the gutter after the breakpoints have disappeared?
3. Can you reproduce this constantly? If yes, please provide reproducable steps so we could investigate (like a repository on github and steps to get into this state)

**Comment by johnpapa** [comment] 2017-10-03 12:36
Please do not close. I was at MS Ignite last week, and a week is not enough to reply if someone is out. 

What happens if you click on the breakpoint pane on the routes.js breakpoint?

It show the breakpoints. 

2. What happens if you click on the gutter after the breakpoints have disappeared?

it does not appear while running. if i stop it, it does.

3. Can you reproduce this constantly? If yes, please provide reproducable steps so we could investigate (like a repository on github and steps to get into this state)

The repo is here https://github.com/Azure-Samples/angular-cosmosdb/tree/develop 

Use the readme to get started. Be sure to be on the develop branch. I run `npm docker-local` to start it. Then attach the debugger using the config in the project.


cc @chrisdias @auchenberg

**Comment by isidorn** [comment] 2017-10-03 14:50
Since the brekapoints disapear while you are running and they appear back when you stop my bet is that the node2 debug adapter is updating the brekapoints to some other location -> assigning to @roblourens to investigate further.

**Comment by johnpapa** [comment] 2018-05-10 17:51
i have not seen this issue happen in over 6 months on my machine. I'm not sure if that is because I moved on to Node 8+ or the issue has been fixed.

Since nobody else has reported anything since then, I think it is safe to close this one

**Closed** 2018-05-10 18:33 UTC
Labels: bug, debug
