### ISSUE TITLE
Strange icon for failed renaming

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59490] opened 2018-09-26 20:55 UTC
What does this icon mean?

![image](https://user-images.githubusercontent.com/4033249/46108728-93deb700-c193-11e8-9a93-5cb4b926875f.png)

And in certain cases it changes into a different icon:

![image](https://user-images.githubusercontent.com/4033249/46108787-b7096680-c193-11e8-8afd-faf6ca0f731b.png)

/cc @misolori

**Comment by misolori** [comment] 2018-09-26 21:14
Also, looking at the dom, it appears that there's supposed to be a message shown?

**Comment by mjbvz** [comment] 2018-09-26 21:16
Duplicate of #59426

@jrieken I fixed this in core rather than just fixing the TS extension case. Take a look at cd7726dee77a6beb133357365aa73a33c9eb0edc to confirm the fix looks ok

**Closed by mjbvz** 2018-09-26 21:16 UTC
Labels: rename

**Comment by jrieken** [comment] 2018-09-27 07:31
lgtm. thanks for fixing
