### ISSUE TITLE
"Add file to File Excludes" in file context menu.

### ISSUE THREAD

**Issue by danteissaias** [microsoft/vscode#88019] opened 2020-01-03 02:06 UTC
Add an entry to the context menu of files that allows you to add that file to the "Files: Exlude" list in order for it to be "hidden" from the file explorer.

**Comment by gjsjohnmurray** [comment] 2020-01-03 08:29
/duplicate of #71836. A PR that implemented this was rejected on the basis that it should be done as an extension.

**Closed** 2020-01-03 08:29 UTC
Labels: *duplicate
