### ISSUE TITLE
Can't use cmd+` as a shortcut on macOS

### ISSUE THREAD

**Issue by Specyk** [microsoft/vscode#109956] opened 2020-11-04 13:02 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open keyboard shortcuts (json or with gui)
2. Set some command to cmd+`
3. Press cmd+`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment] 2020-11-06 09:54
Duplicate of https://github.com/microsoft/vscode/issues/79832 

> On mac, `` cmd + ` `` is typically reserved to loop through windows of an application. The keybinding needs to be removed from the OS in order for it to function in applications that have multiple windows.

**Closed by alexdima** 2020-11-06 09:54 UTC
Labels: mac
