### ISSUE TITLE
Incorrect terminal contents if switching between code and multiple terminal tabs

### ISSUE THREAD

**Issue by erhhung** [microsoft/vscode#131674] opened 2021-08-25 21:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open a window with at least one code (non-terminal) tab open
2. Open a terminal (Ctrl-`) in the lower pane; move to editor area
3. Open another terminal and move to editor area
4. Run different commands in each terminal just so their contents are clearly different
5. Click on a non-terminal tab (a code tab) but note which terminal tab was last shown
6. Click back to the other terminal tab (not the one previously shown)
7. Desired tab is selected but contents are of the previously shown terminal
8. Repeating steps 5 and later does not fix the problem until switching **from terminal tab to terminal tab**

I often open multiple terminals, each with different environment settings to deploy code to different environments. If the contents of two terminals were similar, it would be easy to issue a command in the wrong shell environment if I selected the intended tab but the command was executed in the unintended shell.

**Comment by erhhung** [comment] 2021-09-02 03:14
Here's a screen capture of a recent Insiders build showing a code tab and 3 terminal tabs, and wrong contents are being shown when switching between code and terminal tabs. I intentionally chose very different terminal contents, and you could see that, even with the wrong content shown, I could still interact with it, which means that if the tabs were used to execute commands against different environments where only the environment variables are set differently in each shell, then I could easily run commands in unintended environments.

![vscode-terminal-tab-switching](https://user-images.githubusercontent.com/5808864/131775748-3e48ebad-e14d-4fef-8357-091a2a90d45f.gif)

Version: 1.60.0-insider (Universal)
Commit: 8dbad73de575e47e127c8b1a4324f2b61257fbdc
Date: 2021-08-27T21:27:11.911Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

**Comment by jeanp413** [comment] 2021-09-02 15:32
duplicate of #130110
PR fixing it #131211

**Closed** 2021-09-02 19:14 UTC
Labels: bug, terminal, terminal-editors
