### ISSUE TITLE
Markdown: Navigating via relative link & editing the file navigated to prevents saving that file

### ISSUE THREAD

**Issue by mmwoodfo** [microsoft/vscode#159815] opened 2022-09-01 22:29 UTC
Within Visual Studio Code, if you're in a markdown file and ctrl+click a relative link that links to another markdown file in your workspace then that markdown file you navigated to cannot be saved. You must close and re-open it from the sidebar in order to save it.

Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.71.0
- OS Version: Windows 11

**Steps to Reproduce:**
1. Create 2 markdown files. One of which is in a subfolder
![image](https://user-images.githubusercontent.com/43832670/188023134-a28671cc-41be-4b7a-abe3-7dabcb52b450.png)
2. Add a relative link to either (or both)
e.g. Add this link in one.md : `[Doc 2](directory/two.md)`
4. Close both files in VS Code
5. Restart VS Code
6. Open the markdown file with the relative link
7. Nav to that file using ctrl+click
8. Edit the file you just navigated to & notice that you cannot perform a valid save

**Comment by mjbvz** [comment] 2022-09-09 21:25
Duplicate of #157260

**Closed by mjbvz** 2022-09-09 21:25 UTC
