### ISSUE TITLE
Ruby: editor.action.addSelectionToNextFindMatch does not work for numbers

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#22490] opened 2017-03-12 21:38 UTC
- VSCode Version: 1.10.2
- OS Version: macOS 10.12

Steps to Reproduce:

1. Open a Ruby file.
2. Place caret inside a number.
3. Hit cmd+D to highlight it and other occurrences. Nothing happens.

Works fine in other languages.

**Comment by weinand** [comment] 2017-03-13 09:18
@atombender are you using a ruby extension for VS Code?

**Comment by atombender** [comment] 2017-03-13 20:15
I am using the Ruby extension (0.10.4). But whenever I bring up grammar deficiencies, I'm told that's all in VSCode itself.

**Comment by alexandrudima** [comment] 2017-03-28 13:33
I can reproduce, `ctrl+d` on numbers in Ruby files is a no-op because `ctrl+d` uses the language configured word definition... introduced via db979de520715ac7bf78c047c657e65b8246ff2e

https://github.com/Microsoft/vscode/blame/master/extensions/ruby/src/rubyMain.ts#L14

**Comment by rebornix** [comment] 2017-04-05 21:54
Fixed via https://github.com/Microsoft/vscode/commit/45e6e90858932e688c02e7838a59561c0def1eed

**Closed by rebornix** 2017-04-05 21:54 UTC
