### ISSUE TITLE
Cutoff on terminal output if it wraps.

### ISSUE THREAD

**Issue by ifmad** [Microsoft/vscode#53249] opened 2018-06-28 14:33 UTC
Issue Type: <b>Bug</b>

Have a terminal open.
Resize it to be small.
Run some command so the result gets line-wrapped.
Enjoy your missing words!

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.98GB (0.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12
mssql|ms-|1.3.1
vscode-docker|Pet|0.0.27

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment] 2018-06-28 15:01
Can you provide a screenshot?

**Comment by ifmad** [comment] 2018-06-28 15:38
![console_normal](https://user-images.githubusercontent.com/3315749/42044630-682f7d44-7af1-11e8-853e-fc3b54b46c42.png)
![console_extended](https://user-images.githubusercontent.com/3315749/42044634-6aaddc3c-7af1-11e8-8792-470c2b4c11bc.png)

Only on the longest line the wrapping appears, some characters are out of sight either way.

**Comment by Tyriar** [comment] 2018-06-28 16:07
Ah, this is a duplicate of https://github.com/Microsoft/vscode/issues/23688

**Closed by Tyriar** 2018-06-28 16:07 UTC
Labels: integrated-terminal, needs more info
