### ISSUE TITLE
Broken JavaScript syntax highlighting

### ISSUE THREAD

**Issue by the-spyke** [Microsoft/vscode#32126] opened 2017-08-08 08:51 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-30-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
Nix|bbe|1.0.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.7.0
LogFileHighlighter|emi|1.1.1
vscode-nginx-conf-hint|han|0.0.4
docthis|joe|0.4.7
hg|mrc|1.1.5
debugger-for-chrome|msj|3.1.7
vscode-icons|rob|7.12.0
vscode-nginx|sha|0.3.1
change-case|wma|1.0.0

---
Steps to Reproduce:

1. Create an empty `.js` file
2. Add code

```
describe("Test", function() {
    const options = {
        "condition": "<"
    };

    // Comment

    function initialize() { /* Empty */ }
});
```

3. Syntax is broken [(screenshot)](https://drive.google.com/open?id=0B4l6ZVUiBYzbay1CUmRabXNvZTQ)
4. Delete `<` symbol
5. All good now [(screenshot)](https://drive.google.com/open?id=0B4l6ZVUiBYzba21HVUt0RTcxTWM)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-08 17:45
Duplicate of #31230

This has already been fixed in the current insiders build and will be fixed in VSCode 1.15 which comes out later this week

**Closed by mjbvz** 2017-08-08 17:45 UTC
Labels: duplicate, javascript
