### ISSUE TITLE
"Error processing 'configurationDone' request. Unknown Error: 0x89720010" in 1.22.0-insider

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#46270] opened 2018-03-21 16:08 UTC
This issue was reported by @nesshoever in https://github.com/OmniSharp/omnisharp-vscode/issues/1431

VS Code version:
Version 1.22.0-insider
Commit 31c30b99345e65fffdc33066726d0962dfbecfa3
Date 2018-03-21T06:14:55.070Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS Version: Ubuntu 16.04 x64

Repro steps:
1.  Install insiders build
2. Open a C# folder
3. Attempt to debug

Result:
C# debug adapter fails with "Error processing 'configurationDone' request. Unknown Error: 0x89720010"

This error indicates that the handshake request is failing or providing the wrong data.

**Comment by isidorn** [comment] 2018-03-21 16:18
@bpasero did we update the handshake library for the new electron? Do we have some checkbox so we do not forget to do this onward?

@gregg-miskelly thanks for reporthing this.

**Comment by bpasero** [comment] 2018-03-21 16:36
@isidorn we always build that handshake library as part of the build unless that changed @joaomoreno ?

**Comment by bpasero** [comment] 2018-03-21 17:49
@isidorn fyi I verified that the handshake module can be required in insiders, so this must be something else.

**Comment by isidorn** [comment] 2018-03-21 18:33
@gregg-miskelly we did not change the handshake module, aren't you guys the authors of that module?

**Comment by gregg-miskelly** [comment] 2018-03-21 18:36
We provided the initial implementation, but we don't own it.

**Comment by isidorn** [comment] 2018-03-22 07:28
@gregg-miskelly can you please check if everything works fine if you remove the handshake in your extension? Also you could provide more data on what is worng on your extension side.
Please note that the following 4 days are off in Zurich so I will have no time to look into this.

**Comment by joaomoreno** [comment] 2018-03-22 08:46
This could be due to the new build machines. @isidorn Make sure this works for you in Windows.

**Comment by bpasero** [comment] 2018-03-22 09:14
Fyi I verified that the `vsda` module can be required on all platforms.

**Comment by gregg-miskelly** [comment] 2018-03-23 19:06
Here is the result that VS Code sends -
```json
{"type":"response","seq":3,"command":"handshake","request_seq":2,"success":true,"body":{"signature":""}}
```

**Comment by bpasero** [comment] 2018-03-24 06:19
Maybe then it is not about building the module and requiring it but there is actually more...

**Comment by bpasero** [comment] 2018-03-26 08:56
@gregg-miskelly I cannot reproduce the empty string, what value are you passing into the `sign` function that would return an empty string?

**Comment by gregg-miskelly** [comment] 2018-03-26 18:25
@bpasero are you using Linux? I don't see the issue on OSX. I will check what the input is.

**Comment by gregg-miskelly** [comment] 2018-03-26 18:46
Here was the input: `"fut8qEkPJtmF0lntCUnlGDjD1mnsIvnBjycgqcZ4Z4E="`.

**Comment by jtsom** [comment] 2018-03-26 19:14
FYI I'm seeing this also, on Linux:
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

Latest Insiders / C# extension.

**Comment by bpasero** [comment] 2018-03-27 05:01
@gregg-miskelly thanks I can reproduce on Linux only too.

**Comment by bpasero** [comment] 2018-03-27 05:47
@gregg-miskelly can you please try with todays insider build from [here](https://az764295.vo.msecnd.net/insider/65e502e8eff7f36fa13a02e26adb9c5fbce151ed/code-insider-1.22.0-1522127690_amd64.tar.gz). 

@joaomoreno looks like you changed back to our old Linux build machine. That seems to have fixed the issue, I am getting a hash back now again from todays insider build. Leaving the issue up to you.

**Comment by joaomoreno** [comment] 2018-03-27 07:16
@bpasero I'll close this for now. But whoever owns that signing code should be aware that stuff will break as soon as we update to 16.04. Which we don't intend on doing anyway.

**Comment by XewTurquish1** [comment] 2018-03-30 02:55
I'm still getting this error.

Version 1.22.0-insider
Commit 952b2a641da89a6c7bc28387474bc8afd47f0d2f
Date 2018-03-29T15:50:12.706Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Fedora 27

Try with both the 1.14.0 OmniSharp C# extension as well as 1.15.0-beta4 OmniSharp C# extension.

**Comment by bpasero** [comment] 2018-03-31 06:03
@joaomoreno I can reproduce, are you sure we have the exact same build environment as before?

**Comment by Huck** [comment] 2018-04-01 20:44
Im also getting this error, can not debug at all.

Error processing 'configurationDone' request. Unknown Error: 0x89720010


Version 1.22.0-insider
Commit 6c22e21cdcd6811770ddcc0d8ac3174aaad03678
Date 2018-03-30T14:36:39.526Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Ubuntu 17.10 64

**Comment by bpasero** [comment] 2018-04-03 07:53
@XewTurquish1 thanks!

**Closed** 2018-04-03 07:52 UTC
Labels: bug, debug, important

**Comment by dvdbrink** [comment] 2018-05-14 11:38
I'm getting this error with 1.23.1 when trying to debug a fresh 'dotnet new webapi' project.

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-04T19:23:45Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Linux: [Solus](https://solus-project.com/)
dotnet: 2.1.300-rc1-008673
