### ISSUE TITLE
[typescript autocomplete] take "literal" | string as a hint for completion

### ISSUE THREAD

**Issue by antoinep92** [microsoft/vscode#126687] opened 2021-06-18 15:16 UTC
Consider the following typescript code:
```ts
type Letter: "A" | "B" | "C" | string;
function process(letter: Letter) { }
process(" // I'm typing here, and triggering autocomplete
```

**Current behavior**
Autocomplete is not shown automatically, triggering it with <ctrl+space> shows a bunch of strings used in the project:
- "random string 1"
- "random string 2"
- ...

**Expected behavior**
It would be nice if explicit options listed in the type declaration were prioritized by the autocomplete. When typing the opening quote, it could suggest A, B, C and then below other strings:
- "A"
- "B"
- "C"
- "random string 1"
- ...

I understand that my `Letter` type is strictly equivalent to `string`, but this kind of types are sometimes used for documentation purposes, and it would be nice if the autocomplete was smart enough to pick it up.

**Comment by usernamehw** [comment] 2021-06-18 15:52
/duplicate of https://github.com/microsoft/TypeScript/issues/29729

**Closed** 2021-06-18 15:52 UTC
Labels: *duplicate
