### ISSUE TITLE
Settings Sync  to prompt login all the time, and prompt again every time you log in for a period of time

### ISSUE THREAD

**Issue by xiexiangrui** [microsoft/vscode#105121] opened 2020-08-21 02:29 UTC
- VSCode Version: 1.48.0
- OS Version: windows10 pro  10.0.18363

Steps to Reproduce:

1.sign in witch Microsoft success
2.Wait for a period of time, 1 hour or more, if it appears multiple times in a day, it will prompt to log in again

Does this issue occur when all extensions are disabled?: No
![Snipaste_2020-08-21_10-28-22](https://user-images.githubusercontent.com/24934739/90845678-10d33500-e399-11ea-81e6-7189cfeb91e6.png)

**Comment by gjsjohnmurray** [comment] 2020-08-21 05:59
Maybe related to #105017

**Comment by sandy081** [comment] 2020-08-25 12:22
Can you please provide following logs
    - View -> Open View… -> Log (Window)
    - View -> Open View… -> Microsoft Authentication

**Comment by RMacfarlane** [comment] 2020-09-01 15:52
Closing as a duplicate of https://github.com/microsoft/vscode/issues/105503

**Closed by RMacfarlane** 2020-09-01 15:52 UTC
Labels: needs more info
