### ISSUE TITLE
Large object variables can not be expanded

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#3499] opened 2016-02-26 15:17 UTC
I am writing a debugger adapter, and met an issue that if a variable is a large object, it is blocked if want to expand it to see its properties. The response of the `variablesRequest` is correct, the detail value of response is [here](https://gist.github.com/minggo/16321ae1e9c9580c692e).

<img width="651" alt="screen shot 2016-02-26 at 11 06 53 pm" src="https://cloud.githubusercontent.com/assets/488203/13356153/fa12a7b2-dcde-11e5-8e97-4d2d1242e5ea.png">

**Comment by minggo** [comment] 2016-02-26 15:18
As you can see, the blocked variable is `this`.

**Comment by minggo** [comment] 2016-02-26 15:32
More information:  The variables are not cleared as #3382 mentioned.

VSCode: v0.19.0
Mac OS X: 10.11.2

**Comment by minggo** [comment] 2016-03-01 02:54
@weinand 
Could you please take a look?
Thanks.

**Comment by isidorn** [comment] 2016-03-01 08:19
Does it remains in a spin forever? Does your adapter return a response.
I do not see the 'this' in your variables response.
Are you sure the names are unique across scopes. E.g you do not have two `this` variables

**Comment by minggo** [comment] 2016-03-01 08:26
> Does it remains in a spin forever? Does your adapter return a response.

Yep. The spin remains forever. The response is correct, the response value is attached above.

> I do not see the 'this' in your variables response.

The varialbes response is the value of `this`.

> Are you sure the names are unique across scopes. E.g you do not have two this variables

Yep, only one this.


And you can return a response with the value i offered to have a try.

**Comment by isidorn** [comment] 2016-03-01 08:58
Well then that is the reason for the slowness. Not sure if we can properly display 3000 elements in our tree. Am I reading your response properly, this has around 3000 children?

**Comment by minggo** [comment] 2016-03-01 09:02
Yep, it loads many javascript files, and the global object will record loaded script files.

**Comment by minggo** [comment] 2016-03-01 09:03
May i know why it is slow to display? Is it too much work to do for it? As i thought, it just loop the object and display them.

**Comment by isidorn** [comment] 2016-03-01 09:07
We use a virtualised tree so this should work in theory, though we never stress tested it.
Is there some way I can get this reproduced on my machine?

Can you also try to send 100 variables instead of 3000 to see if that makes a difference?

**Comment by weinand** [comment] 2016-03-01 09:10
@minggo You'll have to consider to show the data in chunks (like we do for large arrays):
![2016-03-01 10-09-50](https://cloud.githubusercontent.com/assets/1898161/13422542/d53ce4e8-df95-11e5-95ed-0bdc56fe8e6c.png)

**Comment by minggo** [comment] 2016-03-01 09:19
@isidorn 
My debugger is special, it is not easy to create a demo. But i think it will happen in Node debugger if an object has many properties. I will try to reproduce it if i have time.

100 variables works correctly.

@weinand 
It looks good. Does it mean that i have to check the properties size, and create new variables dynamically? For exmaple, `[0..999]` is a variable name generated dynamically, right?

**Comment by weinand** [comment] 2016-03-01 09:40
@minggo yes, `[0..999]`is a dynamically introduced 'dummy variable'.

**Comment by weinand** [comment] 2016-03-01 09:44
@isidorn I'm not sure that a virtualised tree can help if the underlying data model is not virtualised.
So even if the tree only shows the items that are visible (e.g. 10 items), the underlying data model has to retrieve all 3000 items from the debug adapter before the tree can start the rendering of the 10 items.

**Comment by minggo** [comment] 2016-03-01 09:46
@weinand 
Thanks, i will try it.

**Comment by isidorn** [comment] 2016-03-01 09:47
@weinand true, but the underlying model does not have to retrieve the 3000 items seperatly from the debug adapter, it just retrieves all the children in one request - unless I am missing something here.

Closing this since there is a workaround, and will reopen if we get reproducable steps to look more into this.
I just tried a simple sample and it worked great for me

```
var large = {};
for (var i = 0; i < 3000; i++) {
    large[i] = 'hello';
}
```

**Comment by weinand** [comment] 2016-03-01 09:54
@minggo make the implementation of the debug protocol requests as fast as possible. If you wait too long (because you have to read files from disk), the VS Code UI will show the spinner.

**Comment by minggo** [comment] 2016-03-01 09:59
@weinand 
Thanks for the information.

**Comment by minggo** [comment] 2016-03-03 03:24
@weinand 
I found it only took 85ms for `variableRequest()`，is it too long?

**Comment by minggo** [comment] 2016-03-03 03:25
It took 81ms to get variable properties from remote, i can not reduce this part too much.

**Comment by minggo** [comment] 2016-03-03 03:45
I found if i return empty array after receive data from remote(which costs about 81ms), then there is not spinner. 

What reasons will cause the spinner except taking too much time?

**Comment by minggo** [comment] 2016-03-03 06:34
@isidorn 
@weinand 
I resolved it.

There are two reasons that cause the issue:

* response.body contains null element, for example

```javascript
protected variablesRequest(response: DebugProtocol.VariablesResponse, args: DebugProtocol.VariablesArguments): void {

    response.body = [
        new Variable('name1', 'value1'),
        null,  // null variable
        new Value('name2', 'value2')
    ]
}

   ...
```

* Variable's value is empty but it has a valid `ref`, for example

```javascript
protected variablesRequest(response: DebugProtocol.VariablesResponse, args: DebugProtocol.VariablesArguments): void {

    response.body = [
        new Variable('name1', 'value1'),
        new Value('name2', '', 1000),  // empty value, and its ref is 1000
        new Variable('name3', 'value3'),
    ]
}

   ...
```

I think VSCode should shoot these information instead of just show a spinner. Or it should handle these exceptions and shoot some warning information.

**Comment by isidorn** [comment] 2016-03-03 08:29
@minggo yes I agree that we should handle this case more gracefully, I can improve that experience

**Comment by minggo** [comment] 2016-03-03 08:34
@isidorn Thanks.
And could you please reopen this issue or create a new one.

**Comment by weinand** [comment] 2016-03-03 09:32
@isidorn the 'null' issue is pretty bad because the UI does not recover from it without a window reload. So even a new debug session does not help. I suggest that you log null variable to the console so that DA developer can see them in dev tools.

**Comment by weinand** [comment] 2016-03-03 09:40
@minggo I cannot reproduce the problem with the empty variable value. You are using a class 'Value' in your example above. Since I don't have this I tried with `new Variable('name2', '', 1000)` but this works fine for me.

**Comment by minggo** [comment] 2016-03-03 09:45
@weinand 
`Value` is a typo.

I will try it again if i have time.

**Closed** 2016-03-03 16:41 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2016-03-03 16:45
I do not log the null value to the console, since so far we never log to the console unless there is an explicit error. This case I handle the same way as if the adapter would return two variables with the same name - I just silently ignore it.
The DA developer would see this while inspecting the messages he is sending from his side, I do not think there is a need for vscode to add msgs to the console, a variable missing in the variables view is a clear enough signal for the developer to check his outgoing variables response imho

**Comment by minggo** [comment] 2016-03-08 08:41
>  a variable missing in the variables view is a clear enough signal for the developer to check his outgoing variables response imho

@isidorn I think it is not clear if an object has many properties, such as more than 100 properties.
