### ISSUE TITLE
A bug about the space display

### ISSUE THREAD

**Issue by WangCong0192** [microsoft/vscode#77991] opened 2019-07-26 13:20 UTC
Issue Type: <b>Bug</b>

As shown, there are a total of 32 spaces. Obviously, the indentation of the space shows a problem.
![图片](https://user-images.githubusercontent.com/42882723/61954284-1a019f00-afeb-11e9-8b4c-1a40b70df9ad.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2937)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (0.35GB free)|
|Process Argv|/home/wangcong/opencv/Learn-OpenCV-4-By-Building-Projects-Second-Edition-master/Chapter_02/main.cpp|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.37.0
cpptools|ms-|0.24.1

</details>

**Comment by niruix** [comment] 2019-07-26 13:43
Dude, you're not the only one. You posted this right after I recorded screencast for my own report, and I also discovered this issue (https://github.com/microsoft/vscode/issues/77466) from few days ago.

So, let's just save each other's time then:) The screencast: https://youtu.be/AYvD42zCYWY

Additional info about the screencast:

- The installation is freshly `snap install code --classic` ed for the screencast
- All configuration and extensions has been removed as shown

Maybe something to do with snap/local language? Just a guess. Hope this problem can be fixed soon.

**Comment by rebornix** [comment] 2019-07-26 17:52
Could you please share the source code in the screenshot to help reproduce?

**Comment by niruix** [comment] 2019-07-27 01:04
Absolutely! Here is a screenshot of a project I been working on for like few years now, you can clearly see the _Whitespace Rendering_ there is a bit wonky donkey.

![My years old project](https://user-images.githubusercontent.com/30656734/61987815-05a1be80-b04c-11e9-99b7-83af3bda90f1.gif)

Also, don't know whether or not it's relative, but my system received an update of `noto-cjk` the day before the problem started to occur (and persist). The is the full list of that update:

    Start-Date: 2019-07-26  07:49:33
    Commandline: aptdaemon role='role-commit-packages' sender=':1.5771'
Upgrade: gir1.2-gtk-3.0:amd64 (3.22.30-1ubuntu3, 3.22.30-1ubuntu4), libegl1-mesa-dev:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), sane-utils:amd64 (1.0.27-1~experimental3ubuntu2, 1.0.27-1~experimental3ubuntu2.1), libegl-mesa0:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgtk-3-common:amd64 (3.22.30-1ubuntu3, 3.22.30-1ubuntu4), libgtk-3-0:amd64 (3.22.30-1ubuntu3, 3.22.30-1ubuntu4), libglapi-mesa:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libglapi-mesa:i386 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), mesa-common-dev:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), fonts-noto-cjk:amd64 (1:20170601+repack1-2, 1:20190409+repack1-0ubuntu0.18.04), iputils-arping:amd64 (3:20161105-1ubuntu2, 3:20161105-1ubuntu3), librbd1:amd64 (12.2.11-0ubuntu0.18.04.2, 12.2.12-0ubuntu0.18.04.1), libxatracker2:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), iputils-tracepath:amd64 (3:20161105-1ubuntu2, 3:20161105-1ubuntu3), libegl1-mesa:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgbm1:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libsane1:amd64 (1.0.27-1~experimental3ubuntu2, 1.0.27-1~experimental3ubuntu2.1), libgtk-3-bin:amd64 (3.22.30-1ubuntu3, 3.22.30-1ubuntu4), libwayland-egl1-mesa:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgles2-mesa-dev:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgl1-mesa-dev:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgl1-mesa-dri:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgl1-mesa-dri:i386 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), iputils-ping:amd64 (3:20161105-1ubuntu2, 3:20161105-1ubuntu3), libgl1-mesa-glx:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libgl1-mesa-glx:i386 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libsane-common:amd64 (1.0.27-1~experimental3ubuntu2, 1.0.27-1~experimental3ubuntu2.1), tmux:amd64 (2.6-3ubuntu0.1, 2.6-3ubuntu0.2), gtk-update-icon-cache:amd64 (3.22.30-1ubuntu3, 3.22.30-1ubuntu4), mesa-vdpau-drivers:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), apache2-utils:amd64 (2.4.29-1ubuntu4.7, 2.4.29-1ubuntu4.8), librados2:amd64 (12.2.11-0ubuntu0.18.04.2, 12.2.12-0ubuntu0.18.04.1), fonts-noto-cjk-extra:amd64 (1:20170601+repack1-2, 1:20190409+repack1-0ubuntu0.18.04), mesa-va-drivers:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), base-files:amd64 (10.1ubuntu2.4, 10.1ubuntu2.5), libglx-mesa0:amd64 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2), libglx-mesa0:i386 (19.0.2-1ubuntu1.1~18.04.1, 19.0.2-1ubuntu1.1~18.04.2)
    End-Date: 2019-07-26  07:58:10

Hope it helps :)

**Comment by WangCong0192** [comment] 2019-07-27 03:54
As you can see, this problem seems to be independent of language and code. This problem occurs once the characters are entered after the space.
The problem can aso occur when I enter a space at the beginning of each line.





------------------ 原始邮件 ------------------
发件人: "Peng Lyu"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 凌晨1:54
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "王聪"<995381116@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] A bug about the space display (#77991)




Could you please share the source code in the screenshot to help reproduce?

**Comment by niruix** [comment] 2019-07-28 04:45
Hello, @rebornix Looks like I've found out the cause, it's font related.

So bravo to me, I guess. You're free to credit me in your next release note, as always :)

![Here you go](https://user-images.githubusercontent.com/30656734/62002377-5c36f780-b135-11e9-92f2-265bc4e00169.gif)

Sadly I just got `vim` up and running as I liked.

**Comment by rebornix** [comment] 2019-07-29 17:54
Thanks for the info!

/duplicate of https://github.com/microsoft/vscode/issues/1727

**Closed** 2019-07-29 17:54 UTC
Labels: *duplicate, editor-rendering, needs more info
