### ISSUE TITLE
Traditional Chinese translation of text labels on the notebook toolbar is not correct

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode#130255] opened 2021-08-06 12:17 UTC
- VS Code Version:1.59.0
- OS Version: Win10 21H1

![image](https://user-images.githubusercontent.com/37107237/128508099-ca79458b-b16e-4654-aead-dbf292515f50.png)

1.In English UI, the red circle above is "code", but it means "verification code" in Traditional Chinese UI. The correct translation is like the red circle below.
2. Some text is not translated.

**Comment by v-mholloway** [comment] 2021-08-16 12:13
dupe of https://github.com/microsoft/vscode-loc/issues/397#issuecomment-899450182

**Closed** 2021-08-17 01:55 UTC
Labels: *duplicate, L10N
