### ISSUE TITLE
Cannot rename terminal when certain tabs are focused

### ISSUE THREAD

**Issue by jesteves** [microsoft/vscode#95986] opened 2020-04-23 16:58 UTC
Issue Type: <b>Bug</b>

It seems that the "Terminal Rename" command does not work when the editor has the focus on a tab other than a regular file.

To reproduce:  (1) Go to extensions and make the settings for any of them visible on the editor. (2) Open a terminal. (3) Execute "Terminal Rename".

Effect: Prompt asking the name for the terminal does not show.

As a side note, I've first noticed this behavior not on a settings tab, but when the output of an extension (Git Graph) is shown.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment] 2020-04-23 17:11
I can repro in 1.44.2 and confirm fixed in 1.45.0-insider

/duplicate of #75209

**Closed** 2020-04-23 17:12 UTC
Labels: *duplicate
