### ISSUE TITLE
Files not restored on restart

### ISSUE THREAD

**Issue by CraigJamesHamilton** [microsoft/vscode#181377] opened 2023-05-03 04:55 UTC
Hi,
The opened files in my workspace do not open on vs code restart., **It only affects one of my workspaces as the rest are behaving as expected.** If I open the failing workspace, open files, open another workspace, open the failing workspace, the failing project has its windows open and breakpoints as expected. If I then close the application and reopen the failing workspace then we lose the open windows etc.

My solution was to remove the .code-workspace file, rename the folder, open the folder within vs code, and then "Save Workspace As..." in the renamed folder. Now it works, but is not a solution in my instance as the folder name is specific to our project.

I tried 1.78.0 insider today, which opens the windows, but is unusable as it won't set breakpoints.

I need help on how to fully remove a workspace from all settings etc to find where this going wrong. Obviously references to the old folder are stuffing things somewhere.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: Windows 11

Steps to Reproduce:

1. Open a file within a project
2. Close vs code
3. Reopen vs code

Thanks

**Comment by bpasero** [comment] 2023-05-03 05:55
This issue is very likely a configuration / setup issue on your end and not a defect in VS Code. The steps you provide are not reproducing a bug for me. You will have to provide more details and real steps to reproduce if you want help here.

**Comment by CraigJamesHamilton** [comment] 2023-05-03 22:51
Hi bpasero,
I agree it is unlikely you can reproduce the bug your end as it affects only one project my end. Simply creating a workspace and following the above steps will not do it. This is why I need information on completely removing the project from vs code so i can trace my end. I need to know the files and reg settings that might be involved.

The configuration has not changed within vs code for over a year.

The steps listed above are straight forward and what you do. What other steps are there and what additional information do you need?

Thanks.

**Comment by bpasero** [comment] 2023-05-04 06:49
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by CraigJamesHamilton** [comment] 2023-05-04 22:56
Hi Benjamin,
I’ve attached all the log files as requested after trying to open the faulty workspace. Please forgive the late reply as I’m in Australia.

Thanks

***@***.***

**Comment by CraigJamesHamilton** [comment] 2023-05-04 23:31
Hi Benjamin,
This set of logs is after I have opened a few files and then shut down vs code.

Regards,

***@***.***

**Comment by bpasero** [comment] 2023-05-05 05:07
I see them not attached, can you upload them directly to https://github.com/microsoft/vscode/issues/181377

**Comment by CraigJamesHamilton** [comment] 2023-05-05 05:14
This set is from starting vs code with the faulty workspace.
[editSessions.log](https://github.com/microsoft/vscode/files/11403430/editSessions.log)
[extensionTelemetry.log](https://github.com/microsoft/vscode/files/11403431/extensionTelemetry.log)
[exthost.log](https://github.com/microsoft/vscode/files/11403432/exthost.log)
[Git.log](https://github.com/microsoft/vscode/files/11403433/Git.log)
[GitHub Authentication.log](https://github.com/microsoft/vscode/files/11403434/GitHub.Authentication.log)
[main.log](https://github.com/microsoft/vscode/files/11403435/main.log)
[Microsoft Authentication.log](https://github.com/microsoft/vscode/files/11403436/Microsoft.Authentication.log)
[network.log](https://github.com/microsoft/vscode/files/11403437/network.log)
[notebook.rendering.log](https://github.com/microsoft/vscode/files/11403438/notebook.rendering.log)
[ptyhost.log](https://github.com/microsoft/vscode/files/11403439/ptyhost.log)
[remoteTunnelService.log](https://github.com/microsoft/vscode/files/11403440/remoteTunnelService.log)
[renderer.log](https://github.com/microsoft/vscode/files/11403441/renderer.log)
[sharedprocess.log](https://github.com/microsoft/vscode/files/11403442/sharedprocess.log)
[tasks (1).log](https://github.com/microsoft/vscode/files/11403443/tasks.1.log)
[tasks.log](https://github.com/microsoft/vscode/files/11403444/tasks.log)
[telemetry.log](https://github.com/microsoft/vscode/files/11403445/telemetry.log)
[userDataSync.log](https://github.com/microsoft/vscode/files/11403447/userDataSync.log)
[views.log](https://github.com/microsoft/vscode/files/11403448/views.log)

**Comment by CraigJamesHamilton** [comment] 2023-05-05 05:15
This set is after closing vs code with the faulty workspace.
[editSessions.log](https://github.com/microsoft/vscode/files/11403451/editSessions.log)
[extensionTelemetry.log](https://github.com/microsoft/vscode/files/11403452/extensionTelemetry.log)
[exthost.log](https://github.com/microsoft/vscode/files/11403453/exthost.log)
[Git.log](https://github.com/microsoft/vscode/files/11403454/Git.log)
[GitHub Authentication.log](https://github.com/microsoft/vscode/files/11403455/GitHub.Authentication.log)
[main.log](https://github.com/microsoft/vscode/files/11403456/main.log)
[Microsoft Authentication.log](https://github.com/microsoft/vscode/files/11403457/Microsoft.Authentication.log)
[network.log](https://github.com/microsoft/vscode/files/11403458/network.log)
[notebook.rendering.log](https://github.com/microsoft/vscode/files/11403459/notebook.rendering.log)
[ptyhost.log](https://github.com/microsoft/vscode/files/11403460/ptyhost.log)
[remoteTunnelService.log](https://github.com/microsoft/vscode/files/11403461/remoteTunnelService.log)
[renderer.log](https://github.com/microsoft/vscode/files/11403462/renderer.log)
[sharedprocess.log](https://github.com/microsoft/vscode/files/11403463/sharedprocess.log)
[tasks.log](https://github.com/microsoft/vscode/files/11403464/tasks.log)
[telemetry.log](https://github.com/microsoft/vscode/files/11403465/telemetry.log)
[userDataSync.log](https://github.com/microsoft/vscode/files/11403466/userDataSync.log)
[views.log](https://github.com/microsoft/vscode/files/11403467/views.log)

**Comment by bpasero** [comment] 2023-05-05 05:36
There is a suspicious error:

```
[error] [storage state.vscdb] open(): Unable to open DB due to Error: SQLITE_IOERR_ACCESS: disk I/O error
```

Are you storing the user data folder on a UNC drive? I see a path such as `\\HKCC\redirected\CraigHamilton\AppData\Roaming\Code\User\globalStorage`.

**Comment by CraigJamesHamilton** [comment] 2023-05-05 05:41
Yes, that is our server.

***@***.***

**Comment by bpasero** [comment] 2023-05-05 05:45
So just to clarify, you explicitly run `code --user-data-dir Path-To-Server`?

The list of editors to restore is stored in a SQLite DB and given the disk errors I found in the logs, it is possible that the DB is corrupt. Can you make a backup of `\\HKCC\redirected\CraigHamilton\AppData\Roaming\Code\User\workspaceStorage` and recreate the folder, that should clear all your settings and data associated with workspaces.

**Comment by CraigJamesHamilton** [comment] 2023-05-05 05:47
No I just run from my start menu, not a command line.

***@***.***

**Comment by CraigJamesHamilton** [comment] 2023-05-05 05:53
Did as requested and it now works. Any ideas as to the cause? SQLite error might be a possible disk corruption.

**Comment by bpasero** [comment] 2023-05-05 06:57
Yeah, I think what you saw is not something caused by VS Code but possibly a corruption on disk. Since you are connecting to a server, maybe it is an issue with how that is mapped back to the OS.

I am still curious unrelated to this issue how you end up with a user data dir that is on the server. Can you provide anymore details about your environment? Was VS Code installed by an admin? Is this part of an enterprise machine?

**Comment by CraigJamesHamilton** [comment] 2023-05-07 22:37
Good morning,
I did a chkdsk and there are no issues on the disk. As for the operating environment:

Edition  Windows 11 Pro
Version 22H2
Installed on         ‎29/‎11/‎2022
OS build               22621.1635
Experience         Windows Feature Experience Pack 1000.22641.1000.0

Server:
Windows Server 2016 Standard
Version 1607
OS Build 14393.5850

I installed vs code as admin with the default provided in the installer. The machine is a regular i7.

I went to sqlite.org and found this:
(3338) SQLITE_IOERR_ACCESS
The SQLITE_IOERR_ACCESS error code is an extended error code<https://www.sqlite.org/rescode.html#pve> for SQLITE_IOERR<https://www.sqlite.org/rescode.html#ioerr> indicating an I/O error within the xAccess method on the sqlite3_vfs<https://www.sqlite.org/c3ref/vfs.html> object.
Short of opening up the sqlite db in a hex editor and doing a forensic comparison I think this might be one of those errors that can just happen. What vs code needs is a way to notify the user of this error and allow recovery to take place that follows the steps you provided earlier so the user can start again with fresh settings.

Regards,

***@***.***

**Comment by bpasero** [comment] 2023-05-08 04:41
> I installed vs code as admin with the default provided in the installer. The machine is a regular i7.

Understood, but how is VS Code storing its data on the server? Our default data folder is in %APPDATA%, but maybe you configured %APPDATA% to be on the server for all applications?

**Comment by CraigJamesHamilton** [comment] 2023-05-09 00:38
Hi Benjamin,
Just checked the group policy and AppData is redirected to the server.

**Comment by bpasero** [comment] 2023-05-09 03:06
Thanks. I am going ahead and close this issue. VS Code requires a functional non-erroring file system to store application data. We could improve case by case but not planned for now.

**Closed by bpasero** 2023-05-09 03:06 UTC
Labels: info-needed

**Comment by bpasero** [comment] 2023-05-09 20:01
A heads up that I believe you might be impacted by our `1.78.1` security update: https://code.visualstudio.com/docs/setup/windows#_working-with-unc-paths

**Comment by CraigJamesHamilton** [comment] 2023-05-09 22:14
Thanks for the help, good luck.

***@***.***
