### ISSUE TITLE
Provide way for extensions to download and install native dependencies

### ISSUE THREAD

**Issue by DustinCampbell** [microsoft/vscode#6929] opened 2016-05-26 18:12 UTC
- VSCode Version: 1.1.1
- OS Version: Any

This is a request for the [C# Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp). Essentially, the extension needs platform-specific native binaries in order to function (both for debugging support and OmniSharp for language server support). It does this by acquiring the binaries during the extension's first activation, rather than during installation. So, the user experience for installation is a bit awkward:
1. Install C# Extension
2. VS Code prompts to restart after successful installation
3. User restarts VS Code and opens a C# project
4. User waits after the "installed" extension finishes installing itself by acquiring native dependencies

To make matters worse, in order to acquire the native dependencies, the extension essentially has to copy code from VS Code in order to handle HTTP proxies correctly (see https://github.com/OmniSharp/omnisharp-vscode/commit/b8f01e4dffd3e1208e08ded719f09c365416f9b1).

**Comment by aeschli** [comment] 2016-05-27 13:59
To handle HTTP proxies correctly, use the https://www.npmjs.com/package/request-light node module.
It is also used in https://github.com/OmniSharp/omnisharp-vscode/pull/224.

Maybe we need a hook on installation? Or platform dependent extensions? @joaomoreno @egamma

**Comment by joaomoreno** [comment] 2016-05-27 14:33
Have you tried bundling the native dependencies with your extension?

**Comment by DustinCampbell** [comment] 2016-05-28 03:30
@aeschli -- handling HTTP proxies correctly also means checking the VS Code setting for proxies. Shouldn't that be transparent for extensions so they don't get it wrong?

**Comment by DustinCampbell** [comment] 2016-05-28 03:34
@joaomoreno -- that's not acceptable for a number of reasons:

1. It's more than three platforms. For Linux, we support RHEL, CentOs, Debian and Ubuntu. Each are different payloads.
2. I've packaged the native binaries for a *single* platform and it's 40 MB. While there's a bit of sharing that will get that down somewhat, bundling all in one is far from ideal. We're talking about 6 different debugger and language service payloads in a single extension.

**Comment by DustinCampbell** [comment] 2016-05-28 03:38
@joaomoreno -- one other thing to consider is that there isn't any progress shown in VS Code while an extension is downloaded. So, if extensions don't stay reasonable small, the user can have a confusing experience where VS Code looks it isn't doing any work for a long while.

**Comment by andrewcrawley** [comment] 2016-06-02 00:15
This would be very valuable for the CppTools extension as well - we're currently bundling native binaries for the language service and debugger integration for every platform we support, and it's getting unwieldy.  Being able to acquire only the binaries relevant to the platform would be a big gain for us.

**Comment by MarkSky** [comment] 2017-03-03 08:30
I would like to know if it has been solved now?

**Comment by Razzeee** [comment] 2018-11-04 13:34
This would still be very appreciated.

For reference https://github.com/OmniSharp/omnisharp-vscode/issues/2648#issuecomment-435528564

**Comment by BrettMoan** [comment] 2019-02-14 19:12
as a user of extensions that need this fixed in the core to allow those extensions to have additional functionality, i would find this feature very helpful if it we to get picked up in teams next backlog grooming. @

**Comment by gilescope** [comment] 2020-02-11 10:35
I'd close this and mark as dupe of https://github.com/microsoft/vscode/issues/23251 where the story continues...

**Comment by gjsjohnmurray** [comment] 2020-09-18 03:55
> I'd close this and mark as dupe of #23251 where the story continues...

/duplicate as suggested by @gilescope

**Closed** 2020-09-18 03:56 UTC
Labels: *duplicate, extensions, feature-request
