### ISSUE TITLE
[semantic highlighting] functions in josef.rouge-theme get wrong color

### ISSUE THREAD

**Issue by josefaidt** [microsoft/vscode#92536] opened 2020-03-12 01:16 UTC
I'm experiencing an issue with my custom theme after updating VSCode

**System Info**:

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. install extension `josef.rouge-theme`
2. change theme to `Rouge 2`

Does this issue occur when all extensions are disabled?: Yes

### Details

- Link to video [https://twitter.com/josefaidt/status/1237905816096845835?s=20](https://twitter.com/josefaidt/status/1237905816096845835?s=20)

There is also some odd behavior from the inspector. It looked like some of the tokens had updated so I started updating my theme, and was able to get some of it changed but others show it's supposed to be one color (and is that color <5s of reloading the window) then flips to another. 

The color flipping after window reload can be found in the video linked above

![image](https://user-images.githubusercontent.com/5033303/76477949-f140e500-63d4-11ea-8377-90015c6c6d1b.png)

**Comment by aeschli** [comment] 2020-03-12 09:19
What you see is the new semantic highlighting feature updating the highlighting with resolved information from the TypeScript server. The server takes a while to load, depending on the size of the project, that's why the highlighting come in delayed.

As a result, each identifier gets colored & styled with the color of the symbol it resolves to. You can see this the easiest in the imports where you can now see what is a function, variable or type. Another example are that readonly variables ('consts') and members can get a different style that modifiable variables, if the theme has defined different colors & styles.
There are still bugs with the way symbols are classified ((help welcome)[https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#the-semantic-highlighting-for-typescript--javascript-files-looks-wrong-how-can-i-debug-this]), and probably also other bugs but the color changes as such are intended.

You can turn the semantic highlighting feature off with
`"editor.semanticHighlighting.enabled": false`

**Comment by josefaidt** [comment] 2020-03-12 12:15
Thank you @aeschli that setting fixed the issue. I don't mind updating my theme to reflect the changes (it really changed things to a point where the theme is mostly one color), but then I started running into issues like shown above in the screenshot where it shows two selectors, the textmate scope, and the semantic type with the updated color. Though it's not actually that color, and instead is taking the foreground of some other selector with my default theme color.

It looks to be classified properly but I'm not sure how to begin troubleshooting why the color isn't receiving the right one. Here we can see it's not being overwritten by another selector (assumably):
![image](https://user-images.githubusercontent.com/5033303/76520628-4579b280-6431-11ea-9066-cd6011480705.png)

**Comment by aeschli** [comment] 2020-03-12 13:51
duplicate of #92308

**Comment by aeschli** [comment] 2020-03-12 16:14
@josefaidt  Somethings fishy, I will investigate

**Comment by Sultanc** [comment] 2020-03-12 16:35
Hi, i have the same problem, i use 1mm themes and methods colors switches to the same color as variables after reloading

**Comment by Zaseth** [comment] 2020-03-12 17:30
A fix is to put the following in your settings:

```json
"editor.semanticHighlighting.enabled": false
```

Taken from the Twitter link.

**Comment by aeschli** [comment] 2020-03-12 21:48
The semantic highlighting code finds the wrong rule for functions (not the most specific one).
That's why the function are colored with the wrong color and so many identifiers end up looking the same. I push a fix to insiders.

**Closed** 2020-03-12 21:52 UTC
Labels: candidate, semantic-tokens, typescript

**Comment by aeschli** [comment] 2020-03-17 14:32
Verify:
- install Rouge 2 theme
- set in user settings 
```
	"editor.tokenColorCustomizations": {
		"[Rouge 2]": {
			"semanticHighlighting": true
		}
	}
````
- verify that in `function foo() { const x = 1; }`, `foo` and `x` have different colors.

**Comment by josefaidt** [comment] 2020-03-17 15:11
@aeschli should I check this in Insiders? 
![image](https://user-images.githubusercontent.com/5033303/76870445-b48f4680-6837-11ea-8889-acfa53f1effe.png)

**Comment by josefaidt** [comment] 2020-03-17 15:14
Verified, Insiders shows the correct token colors
![image](https://user-images.githubusercontent.com/5033303/76870748-1b146480-6838-11ea-8c5f-e7230dba2d2f.png)
