### ISSUE TITLE
Font family stopped working after update.

### ISSUE THREAD

**Issue by dhrivnak** [microsoft/vscode#214461] opened 2024-06-06 14:10 UTC
Type: <b>Bug</b>

I updated VSCode this morning, and my font family no longer works. I use "Source Code Pro Medium", and it has been working for months until this morning. If I change it to "Source Code Pro", that works, but I want the Medium weight.

Version: 1.90.0 (Universal)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:44.157Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|18.00GB (0.71GB free)|
|Process Argv|--crash-reporter-id 9189c1ee-0d21-4a6b-9207-ab5b22d94b77|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
gitlens|eam|15.0.4
prettier-vscode|esb|10.4.0
copilot|Git|1.199.0
copilot-chat|Git|0.16.0
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.88.1
vscode-docker|ms-|1.29.1
vscode-jest|Ort|6.2.5
pretty-ts-errors|Yoa|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by aecorredor** [comment] 2024-06-06 14:25
Yeap - just updated and had the same issue.

**Comment by aecorredor** [comment] 2024-06-06 14:36
For clarity, these are the settings I had relating to fonts/colors/tokens:

```json
  "editor.fontFamily": "Operator Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontSize": 14,
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "comment",
          "constant.language",
          "keyword.control",
          "keyword.operator.expression",
          "keyword.other",
          "keyword.operator.new",
          "variable.language",
          "entity.other.attribute-name",
          "storage"
        ],
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": [
          "storage.type.function.arrow"
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  },
```

**Comment by dhrivnak** [comment] 2024-06-06 14:47
Here's my only font customization:

`"editor.fontFamily": "Source Code Pro Medium, Menlo, monospace"`

**Comment by debuggerpk** [comment] 2024-06-06 16:19
yep, went all bold for me!

**Comment by CameronSumpter** [comment] 2024-06-06 19:00
This issue started happening for me this morning, also after updating to v1.90.0. It appears to be forcing use of bold in my case (with Operator Mono), as the dollar sign glyph in the font is different for bold than for all other weights and it appears that way regardless of how it’s configured.

Setting `"editor.fontWeight": "normal"` has no effect, although setting `"editor.fontWeight": "bold"` results in it applying faux bold to the already-bold weight being rendered.

**Comment by kylefox** [comment] 2024-06-06 19:21
Likewise, 1.90 made Operator Mono all bold for me. Changes to `editor.fontWeight` have no effect.

<img width="485" alt="image" src="https://github.com/microsoft/vscode/assets/37838/f42515a0-c6f5-4e5b-aea8-a0d289ab3bdb">

**Comment by rzhao271** [comment] 2024-06-06 21:35
Duplicate of https://github.com/microsoft/vscode/issues/214390

**Closed by rzhao271** 2024-06-06 21:35 UTC
Labels: new release
