### ISSUE TITLE
VSCode 1.33 two main bugs on Ubuntu 18.04

### ISSUE THREAD

**Issue by fc373745** [microsoft/vscode#73303] opened 2019-05-05 13:30 UTC
Here are the bugs i've been noticing on Ubuntu 18.04 even despite disabling extensions and changing to default settings. 

1. Intellisense is EXTREMELY SLOW. for example, I will type 'hello' randomly in my typescript function and the red underline that should come up almost instantly takes nearly 7-8 seconds to see.
2. Saving files has a weird behavior. When i save, it will, for one second, be saved, but then unsaved again. Repeating this process to save around 3-4x will do the trick.

- VSCode Version: 1.33
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. Download Ubuntu 18.04.2 LTS
2. Open a typescript file in VSCode 1.33

By the lack of open issues about this has me worried that i'm an extreme edge case and that it has to do more with my machin than vscode, but please still check it out. It's been bugging me since 1.32 

Does this issue occur when all extensions are disabled?: Yes/No
 Yes
I have to revert my code to version 1.31 to have these issues mitigated. I say mitigated because i'm still having the saving issue on 1.31, but the intellisense is what it should be.

**Comment by RMacfarlane** [comment] 2019-05-05 15:31
Hey @fc373745, can you also please make sure you have the latest version of @types/styled-components installed? See DefinitelyTyped/DefinitelyTyped#34391 for details, both of these issue may be caused by that

**Comment by fc373745** [comment] 2019-05-06 00:05
seems to be the solution. thanks!

**Comment by fc373745** [comment] 2019-05-08 17:50
was fine for one day, but all of the sudden its broken with the same problems again 
also typing `console.log` auto imports `import console = require("console");` to my file. 

I have reverted back to 1.31

`@types/styled-components` is in its latest version

**Comment by fc373745** [comment] 2019-05-08 22:07
Sorry i didn't read thoroughly to the referenced issue, and upon further reading, i had to DOWNGRADE `@types/styled-components` to `4.5.1` which seems to solve it.

**Comment by fc373745** [comment] 2019-05-21 17:14
After playing around with the versions of typescript, @types/styled-components, and vscode, i have gotten the bugs with any of the combination of these
```
code 1.34
typescript 3.4.5, 3.3.4000,
@types/styled-components 4.1.11, 4.1.12, 4.1.15
```
any version of code 1.34 has a problem with matching with any of these dependencies 

For some reason upgrading, downgrading typescript or @types/styled-components serves as an initial solution, but after a couple of hours, it will start to break down again (weird saving behaviors, extremely slow intellisense and typescript linting/checking) 

The best way i can mitigate this is to downgrade code to 1.31 and it actually has the best result.

here is what i'm using. 
```
code 1.31
typescript 3.4.5
@types/styled-components 4.1.11 (the latest - 4.1.15 will give me problems even in code 1.31)
```
Really weird things happening, might give up styled-components and go back to css modules after this :sob:

**Comment by mjbvz** [comment] 2019-05-22 22:48
Duplicate of https://github.com/microsoft/TypeScript/issues/30819. Please try using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Closed by mjbvz** 2019-05-22 22:48 UTC
Labels: typescript
