### ISSUE TITLE
Cannot enter tilde '~' character in terminal window anymore, w/ Belgian Keyboard

### ISSUE THREAD

**Issue by arnauldvm** [microsoft/vscode#71925] opened 2019-04-08 10:29 UTC
Issue Type: <b>Bug</b>

When trying to type tilde ('~') character in the terminal window, I get this strange behaviors:

- Hitting AltGr+Tilde -> displays "="
- Hitting AltGr+Tilde, Space -> displays "=~"
- Hitting AltGr+Tilde, AltGr+Tilde -> displays "==~"

It is not possible to issue a single Tilde character.

(Using a Belgian Keyboard, where the tilde key is labeled "+ = ~", and is located immediately left before the right shift key.)

In other windows, the tilde works correctly.

It used to work normally in the terminal windows a few weeks ago.

Tested on at least 2 separated computers.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.92GB (7.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.4.2
emojisense|bie|0.5.0
markdown-preview-github-styles|bie|0.1.4
better-toml|bun|0.3.2
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.25.1
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
graphviz-preview|EFa|1.3.1
tslint|eg2|1.0.43
git-project-manager|fel|1.7.1
gc-excelviewer|Gra|2.1.31
todo-tree|Gru|0.0.126
Scala|itr|0.1.7
plantuml|jeb|2.10.9
asciidoctor-vscode|joa|2.4.0
puppet-vscode|jpo|0.18.0
vs-color-picker|lih|1.0.0
VS-code-vagrantfile|mar|0.0.7
HTMLHint|mka|0.6.0
python|ms-|2019.3.6352
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
java|red|0.42.1
vscode-yaml|red|0.4.0
vscode-open|san|0.1.0
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
vscode-zipexplorer|sle|0.3.1
dot|Ste|0.0.1
html-preview-vscode|tht|0.2.5
shell-launcher|Tyr|0.3.0
vscode-icons|vsc|8.5.0
gitblame|wad|2.7.0
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.8.1
markdown-pdf|yza|1.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by arnauldvm** [comment] 2019-04-10 08:45
Same behavior with version 1.33.0

**Comment by Tyriar** [comment] 2019-04-12 15:41
Can you verify whether it works in 1.31.1? Download links at the top of https://code.visualstudio.com/updates/v1_31

**Comment by arnauldvm** [comment] 2019-04-17 14:39
Same issue with that version:

```
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by arnauldvm** [comment] 2019-04-17 14:41
But, the issue is not present with the version before:

```
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

**Comment by arnauldvm** [comment] 2019-04-25 14:57
Note for clarity:

- in the title of the issue, "terminal window" meant the terminal panel of the VScode window
- in the description, "other windows" meant any other panel in the VScode window (e.g. editor, search box, etc.)

**Comment by skneko** [comment] 2019-05-07 16:38
As a quick hotfix, pressing down Ctrl and Alt at the same time, then the corresponding key, works as expected. For example, Ctrl+Alt+4 inputs a tilde (`~`) properly using my ISO Spanish keyboard while AltGr+4 does not work (inputs a `4`). Version 1.33.1, not sure when it stopped working but it was recently.

**Comment by bcxpro** [comment] 2019-05-07 19:14
I think this is a duplicate of #68262

**Closed** 2019-05-10 18:33 UTC
Labels: *duplicate, bug, integrated-terminal, windows
