### ISSUE TITLE
CSS @supports throws errors

### ISSUE THREAD

**Issue by tomliv** [Microsoft/vscode#28553] opened 2017-06-12 17:43 UTC
Using @supports in scss and css throws errors.

- VSCode Version: 1.13.0
- OS Version: MacOS 10.12.5

Steps to Reproduce:

1. Using this syntax:
@supports ( prop: value ) {
	/* styles */
}
Errors are flagged in bottom info bar.

2.

**Comment by tomliv** [comment] 2017-06-13 17:48
My apologies. I think this is in the wrong place. This is for the caniuse extension. Moving...

**Comment by tomliv** [comment] 2017-06-13 17:50
Nope. Two separate issues. Carry on. Reopening...

**Comment by bradkemper** [comment] 2017-06-15 17:53
Yeah, the spec for @supports and other conditionals (@media) has been stable for at least 4 years:

https://www.w3.org/TR/css3-conditional/

The "problems" panel also seems to be even confused by the syntax of where the curly brackets are, implying it doesn't really parse unknown @ rules in general well either.

**Comment by lrs** [comment] 2017-06-25 09:46
Also throws out autocomplete:
![licecap_code_supports](https://user-images.githubusercontent.com/582574/27515091-6f608ee4-5993-11e7-9f62-e783214e04e5.gif)

**Comment by codingcircus** [comment] 2017-08-04 16:06
Is this on the roadmap already? Would be great to get support for this feature soon.

**Comment by adamchenwei** [comment] 2017-08-10 15:12
yea crazy annoying keep seeing all these red curly braces under so many places because one @support on top....

Can we have some sort of hack to at least disable scss from linting @support? That will be great.

**Comment by aeschli** [comment] 2017-08-14 08:26
duplicate of #1505

**Closed by aeschli** 2017-08-14 08:26 UTC
Labels: css-less-sass
