### ISSUE TITLE
The `Open Changes` button not displayed as disabled for files without any changes

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#26425] opened 2017-05-11 04:14 UTC
VSCode Version: 1.12.1
OS Version: OS X EI Capitan 10.11.3

Steps to Reproduce:

1. Open some project from GitHub.
2. Open a file A.cs which has no fresh changes at all.
3. Stay on the editor of A.cs, and notice the button of `Open Changes` on the top right corner above the editor doesn't display as disbled! Clicking it has no effect of course, but it should display as disable in this case just like what in the old versions.

**Comment by joaomoreno** [comment] 2017-05-11 08:29
Can't fix without #21131, closing for now.

**Comment by cateyes99** [comment] 2017-05-11 22:58
since it connot be fixed without #21131, should this be kept open and linked to #21131 then?

**Comment by joaomoreno** [comment] 2017-05-12 07:35
Sure.

**Comment by joaomoreno** [comment] 2017-11-23 13:42
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by sana-ajani** [comment] 2021-06-29 19:18
Hoping to re-open this because I got this as a feedback item from a few CS educators. They notice their students clicking it accidentally and being confused when there is no apparent action.

**Comment by bpasero** [comment] 2021-08-03 13:36
I think this has regressed, I now miss this button when a file is staged.

**Comment by lramos15** [comment] 2021-08-03 14:31
Fixed regression with https://github.com/microsoft/vscode/commit/323237921b889eaedb02d4a58af2d766bde59ce7

**Comment by lszomoru** [comment] 2021-11-05 14:49
There is another regression (#131739), so I will be reverting this fix for this, and will refactor it.

**Closed** 2021-11-22 15:13 UTC
Labels: bug, git
