### ISSUE TITLE
Clicking in the title area after the menu does not close the menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54739] opened 2018-07-20 15:38 UTC
Click on the menu. While open click on the area in the title after the last menu entry -> menu does not close.
Notice how menus on win / mac always close if you click there.

The current behavior makes the menu more sticky and not nice.

**Comment by sbatten** [comment] 2018-07-20 17:12
duplicate of #53479

**Closed by sbatten** 2018-07-20 17:12 UTC
Labels: bug, workbench-menu
