### ISSUE TITLE
Drag n' drop editor tabs with weird behavior on ChromeOS (with videos)

### ISSUE THREAD

**Issue by MatheusZabin** [microsoft/vscode#118882] opened 2021-03-13 14:56 UTC
### Environment:
- Version: 1.54.1
- Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
- Date: 2021-03-04T22:38:50.094Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Linux x64 5.4.74-10576-gb6cc41974db3

### Steps to Reproduce:

1. Download  and install VSCode .deb from main download page.
2. Run it straight through .desktop file launcher.
2. Open any other Linux app (including VSCode)
3. Try to use drag n drop with editor tabs

Does this issue occur when all extensions are disabled?: Yes

### Description
I've made 4 videos to describe the problem, for each situation.
- [Drag n drop with correct behavior](https://youtu.be/fpdlErNt_74) (only VSCode as open Linux apps) 
- [Unfocused VSCode "stealing" the drag n drop tab](https://youtu.be/5kLbFfpmYqA)  (2 VSCode as open Linux apps)
- [Even if  VScode windows dont overlap, the "stealing" still occurs ](https://youtu.be/fy-2BmIAjSs)  (2 VSCode open side by side)
- [Drag n drop not working when exists other Linux app running](https://youtu.be/liHr3vNO96Y)  (1 VSCode + random Linux app open)

**Comment by bpasero** [comment] 2021-03-13 15:41
Likely duplicate of https://github.com/microsoft/vscode/issues/109176 then unless it reproduces without wayland.

**Comment by matheusqueirozzabin** [comment] 2021-03-13 15:46
> Likely duplicate of #109176 then unless it reproduces without wayland.

All these vídeos were recorded without Wayland flags, just a deb install from VSCode download page.

**Comment by bpasero** [comment] 2021-03-13 17:38
@MatheusZabin weird indeed, do you see the same using Chrome browser and VSCode from https://vscode-web-test-playground.azurewebsites.net/?enter=true ?

**Comment by MatheusZabin** [comment] 2021-03-13 18:10
> @MatheusZabin weird indeed, do you see the same using Chrome browser and VSCode from https://vscode-web-test-playground.azurewebsites.net/?enter=true ?

No. On web-test drag n drop works properly, even with multiple windows open (overlapping and side by side).
This issue doesn't occur on code-server PWA either.

**Comment by bpasero** [comment] 2021-03-14 07:15
@deepak1556 fyi maybe you have heard about these issues before (see the videos).

**Comment by MatheusZabin** [comment] 2021-03-21 11:45
Can someone remove "needs more info" and reopen?

**Comment by MatheusZabin** [comment] 2021-05-06 00:15
Fixed with wayland flags on 1.56.0 release.

**Closed** 2021-05-06 00:15 UTC
Labels: confirmation-pending, electron-11-update

**Comment by aschwartz2018** [comment] 2021-05-08 13:17
The icon preview in chromeos is gigantic for some reason
![image](https://user-images.githubusercontent.com/68354532/117540660-2bf4dc00-afde-11eb-9fd1-6e9652512298.png)

**Comment by MatheusZabin** [comment] 2021-05-08 13:23
> The icon preview in chromeos is gigantic for some reason
> ![image](https://user-images.githubusercontent.com/68354532/117540660-2bf4dc00-afde-11eb-9fd1-6e9652512298.png)

Same here. Also, occasional stop in keyboard/mouse input response.
There's a filled bug for this?

**Comment by aschwartz2018** [comment] 2021-05-08 13:46
I don't know if a bug was filled for the gigantic thumbnail issue, but it isn't due to the Wayland flags.
My code.desktop file without the icon fixes it, however even icons from the internet don't fix the weirdness.

`[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland --unity-launch %F
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Keywords=vscode;`

**Comment by aschwartz2018** [comment] 2021-05-08 13:47
It could be due to the newest version of VSCode

**Comment by aschwartz2018** [comment] 2021-05-08 13:48
Hmm I don't ever have a stop in keyboard/mouse input response. My device is HP Chromebook x360 14 (nami) btw
