### ISSUE TITLE
Feature: Hide code preview on NPM Script Explorer

### ISSUE THREAD

**Issue by Codelica** [microsoft/vscode#143387] opened 2022-02-18 16:24 UTC
As someone who uses the NPM Script Explorer option A LOT :), I'd love to see  an option (perhaps even the default?) to hide the script code preview in that panel.  Personally I find it really clutters things up, and you're only a click away from pulling up the package.json anyway.   Basically:

<img width="391" alt="package-json-orig" src="https://user-images.githubusercontent.com/386101/154721806-9c2b4b0f-6f54-46c3-b97a-ee9af74ab9b4.png">

TO:

<img width="391" alt="package-json-new" src="https://user-images.githubusercontent.com/386101/154721856-165a4047-69f8-4c09-ba0d-0028c72022e1.png">

**Comment by alexr00** [comment] 2022-02-21 07:41
Duplicate of https://github.com/microsoft/vscode/issues/138694

**Closed by alexr00** 2022-02-21 07:41 UTC
