### ISSUE TITLE
Cannot right click token due to tooltip appearing on top of it

### ISSUE THREAD

**Issue by jameshfisher** [microsoft/vscode#113330] opened 2020-12-23 09:31 UTC
- VSCode Version: Version: 1.52.1, Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523, Date: 2020-12-16T16:30:02.420Z (6 days ago), Electron: 9.3.5, Chrome: 83.0.4103.122, Node.js: 12.14.1, V8: 8.3.110.13-electron.0
- OS Version: Darwin x64 20.2.0

## Steps to Reproduce

1. Create a fresh name for something, e.g. `let unusedVar;`
2. Hover over `unusedVar`
3. Right click

## Expected behavior

Brings up normal right-click context menu for `unusedVar` token

## Actual behavior

Right-click is intercepted by a tooltip that gets in the way of the token, saying that `unusedVar` is unused

## Suggested fix

The tooltip should appear above/below the hovered token, rather than on top of it

## Does this issue occur when all extensions are disabled?

Yes

## Screen recording

See https://user-images.githubusercontent.com/166966/102981086-cd383580-4508-11eb-8cc4-cc8b7eaaa79c.mov

**Comment by alexdima** [comment] 2020-12-23 13:27
Duplicate of #112391 . A fix is available in our Insiders Release Channel.

**Closed by alexdima** 2020-12-23 13:27 UTC

**Comment by jameshfisher** [comment] 2020-12-23 13:55
Ah great, thanks @alexdima 🎉
