### ISSUE TITLE
Search "files to include" overriding path to file (not case - sensitive)

### ISSUE THREAD

**Issue by andrzejskowron** [Microsoft/vscode#29938] opened 2017-06-30 12:13 UTC
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|agauniyal|0.5.0|
|path-intellisense|christian-kohler|1.4.2|
|tortoise-svn|fantasytyx|0.1.1|
|php-debug|felixfbecker|1.10.1|
|php-intellisense|felixfbecker|1.4.3|
|code-runner|formulahendry|0.6.24|
|minify|HookyQR|0.3.0|
|format-indent|Kasik96|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|ftp-sync|lukasz-wronski|0.3.3|
|sublime-keybindings|ms-vscode|2.9.0|
|stylelint|shinnn|0.26.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Search on the left panel
2. type some text to search in files
3. put the wrong path to include (etc. /themes/hc-main **instead of** /themes/HC-main
4. click on the searched file to open
5. if you save opened file, it saves in the new folder (in this example "hc-main")

**Comment by roblourens** [comment] 2018-09-13 19:02
Dupe of https://github.com/Microsoft/vscode/issues/51554

**Closed by roblourens** 2018-09-13 19:02 UTC
Labels: bug, search
