### ISSUE TITLE
Toggling line comment/indent line not working on keyboard

### ISSUE THREAD

**Issue by c01nd01r** [Microsoft/vscode#17106] opened 2016-12-13 10:00 UTC
- VSCode Version: 1.7.2
- OS Version: Mac OSX 10.11.1 (15B42)

Steps to Reproduce:

1. Open editor and any file
2. Try to comment line (cmd + /) or indent line (cmd + ] / cmd + [)

Similar to  #17023 

My keybindings.json is empty.  It happens from time to time. It helps only reload window.
I recorded a screencast: https://youtu.be/JoJJdzwFDK0

**Comment by kieferrm** [comment] 2016-12-13 18:45
Duplicate of  #17023.

**Comment by alexandrudima** [comment] 2016-12-14 09:25
@c01nd01r What is your keyboard layout? Did you customize your keyboard layout in any way? Do you have any OS level software that you use to bind OS level shortcuts? Does this issue appear in relation to opening/closing other software? Does this issue appear in relation to switching keyboard layouts?

 Next time you notice these keybindings not functioning, can you please digg deeper to find out what the problem is:

### Is it a problem with the actions?
When you notice the keybindings not working, can you try pressing `F1` and invoking the action from the `F1` list? Does the action execute correctly?

### Is it a problem with the keybindings?
When you notice the keybindings not working, can you open `Preferences` > `Keyboard shortcuts` and then clicking on the Define Keybinding box in the lower right. You can then press the keybinding you're having issues with in there. That widget will print the keybindings it receives from Chromium / the OS.

Here is a page describing how keybindings are handled in VS Code and various troubleshooting techniques -- https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings

**Closed** 2017-03-23 17:38 UTC
Labels: mac, needs more info

**Comment by alexandrudima** [comment] 2017-03-23 17:40
Without further information about the exact keyboard layout used, I cannot validate, but simply assume that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) behave correctly for this keyboard layout.
