### ISSUE TITLE
pressing CMD+v on latest update produces a workspace zoom-in instead of a Paste of data.

### ISSUE THREAD

**Issue by ing-garcia** [microsoft/vscode#173743] opened 2023-02-08 02:05 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0
- OS Version: macOS 12.6.1

Steps to Reproduce:

1. Pressing CMD + V produces a workspace zoom in instead of pasting the data. 

This started to happen as soon as VSCode was updated. Data is still able to be pasted using Edit > Paste from the menu. The Paste keybinding is still the default CMD+v

**Comment by ing-garcia** [comment] 2023-02-08 04:22
Upon further research, it seems that somehow a Keybinding for command+V was added for the zoom in. This was not added by me, and it happened just after updating 
<img width="881" alt="Screen Shot 2023-02-08 at 13 18 37" src="https://user-images.githubusercontent.com/31834682/217432853-6ea35af1-1dcd-46dc-abe9-64d8b37961b7.png">

**Comment by samcackett** [comment] 2023-02-08 14:20
I had a similar issue in which a few of my keybindings had random new ones added against them. I didn't do anything, just started my day as usual and found `CMD+V`, `CMD+[`, `CMD+/` etc were either unresponsive or doing the wrong thing. They were bound to things like "Unfold all" and "Go to end of line" etc. I didn't add them or change anything about my install. The source for these was "User" if that means anything, but I did absolutely nothing. I disabled all my extensions and nothing fixed it except manually removing the erroneous keybindings.

Also on 1.75.0.
MacOS 13.2 (22D49

**Comment by samcackett** [comment] 2023-02-08 15:18
Here's another one I just noticed broken. For some reason `CMD+X` has been mapped to "go forward". It does nothing when I press it. Removing the "go forward" binding fixes cut.
![Screenshot 2023-02-08 at 15 14 21](https://user-images.githubusercontent.com/5948635/217571490-7a953cb4-0d05-4996-9851-5b34eae68781.png)

**Comment by janikschoenfelder** [comment] 2023-02-09 09:16
Bug also exists for me. I have a custom keybinding for editor zoom in: `⌘ +`
Today I started my machine and the keymapping was automatically changed to: `⌘ X`

If I want to change the binding again to `⌘ +`, VS Code displays `cmd+[BracketRight]` and when I hit enter, the keybinding is `⌘ X` again. 

Seems that the `+` is mapped to `X` somehow, but only if I reassign a shortcut in VS Code. Everywhere else my keyboard layout is totally fine. I'm on a mac using a german layout.

What I also find out is if I combine `Backspace` with `+` the plus sign gets mapped correctly. I will change the binding for now, but really a strange issue.

**Comment by alexdima** [comment] 2023-02-10 11:20
Duplicate of #173325

**Closed by alexdima** 2023-02-10 11:20 UTC
