### ISSUE TITLE
(IntelliSense) Hover disappears too quickly when trying to click on it

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode#162471] opened 2022-09-30 20:12 UTC
Type: <b>Bug</b>

On Ubuntu 22.04 with Wayland and also on macOS. Sometimes it is very hard to access the details of a hover. Please check the attached screenshot below for details.

Originally reported here: https://github.com/microsoft/vscode-cpptools/issues/9937#issuecomment-1263851619

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:12:14.256Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|7.42GB (2.98GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 20280fc3-3c6d-43d3-9eb5-55c536b003d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
markdown-mermaid|bie|1.15.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.48.1
githistory|don|0.6.19
gitlens|eam|12.2.2
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.50.0
better-cpp-syntax|jef|1.15.19
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.1
cpptools-extension-pack|ms-|1.3.0
rust-analyzer|rus|0.3.1221
swift-lang|ssw|0.8.2
ninja|sur|0.0.1
even-better-toml|tam|0.18.1
cmake|twx|0.0.17
vscode-lldb|vad|1.7.4
vscode-apple-swift-format|vkn|1.3.2
vscode-swiftlint|vkn|1.7.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by Zingam** [comment] 2022-09-30 20:18
On the screenshot, when attempting to click on `View details` on the hover, which is displayed when hovering the mouse over the red squiggle, the hover disappears too quickly. It feels like a clicking game, which require very precise and careful moves.

This happens also in other context but the sample context it is really difficult.

![image](https://user-images.githubusercontent.com/3337419/193144207-168bcd55-5d16-4ce4-8f49-2245a683dfb3.png)
![Test3.zip](https://github.com/microsoft/vscode-cpptools/files/9638165/Test3.zip)

**Comment by ArturoDent** [comment] 2022-10-03 18:39
See [v1.72 Release Notes: Improved Hover](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_72.md#improved-hover)

> Improved hover
> 
> The editor hover used to be quite aggressive in hiding itself, especially when the mouse was going over an empty area of the editor. This would make it very difficult to reach some of the actions shown in the hover. Now, the hover will stay visible as long as the mouse is moving towards it. The setting `"editor.hover.sticky": false` will continue to work as before:

In addition, you will probably want `"editor.hover.sticky": true` so that the hover stays visible when you are over it.

**Comment by alexdima** [comment] 2022-10-07 12:56
Duplicate of https://github.com/microsoft/vscode/issues/147403

:+1: The latest VS Code release (that went out yesterday) will contain a fix.

**Closed by alexdima** 2022-10-07 12:56 UTC
