### ISSUE TITLE
Apply folding view state from untitled files to file when saved

### ISSUE THREAD

**Issue by japsancha** [Microsoft/vscode#10795] opened 2016-08-22 12:42 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. When we  save a file and open again the fold state must maintain..

**Comment by sandy081** [comment] 2016-08-23 08:46
@japsancha It works for me when I saved a file, closed it and opened it, folding state is in previous state.

 Can you please provide more steps to re-create the issue you are seeing?

Thanks.

**Comment by dbaeumer** [comment] 2016-09-05 07:15
Closing. Haven't received any response. @japsancha please ping if the issue is still reproducible with steps that demo the problematic behavior.

**Comment by japsancha** [comment] 2016-09-12 14:50
Hi

In the images file I send an example

![2016-09-12 1](https://cloud.githubusercontent.com/assets/435622/18440207/629d906a-78ef-11e6-85eb-b9bee6150a4a.png)
![2016-09-12](https://cloud.githubusercontent.com/assets/435622/18440209/636bec9e-78ef-11e6-8531-0277f2feb7b2.png)

**Comment by aeschli** [comment] 2016-09-13 17:03
The screenshot shows an unsaved, untitled file.
Where did you save it? Is it in the workspace folder?

**Comment by aeschli** [comment] 2016-09-13 17:04
Assigning to @bpasero. It's the workbench who reopens the file with the save state (which contains the folding regions)

**Comment by bpasero** [comment] 2016-09-13 17:16
PR welcome 👍

**Comment by bpasero** [comment] 2017-01-05 14:48
When saving a untitled file (or using "Save As" on an existing file), the entire editor view state is now being applied again on the target.

Note that there is a corner case: If a save participant is running and changing the content as a matter of the save (removing / adding lines), the view state is ignored by the editor because the line count do not match anymore.

**Closed** 2017-01-05 14:48 UTC
Labels: feature-request, verification-needed, workbench
