### ISSUE TITLE
CTRL C, Z and so on. not working in integrated term, while a process is running.

### ISSUE THREAD

**Issue by moe123** [Microsoft/vscode#18620] opened 2017-01-16 18:55 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-symbols|linyang95|2.0.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|cpptools|ms-vscode|0.9.3|

---

Steps to Reproduce:

1. write a infinite loop case in whatever language
2. run the culprit on the integrated term
3. try terminating/escaping.

**Comment by Tyriar** [comment] 2017-01-16 21:29
This should be fixed in the Insiders build, coming to 1.9.0 soon :smiley: Closing as dupe of https://github.com/Microsoft/vscode/issues/17875

**Closed by Tyriar** 2017-01-16 21:29 UTC
Labels: integrated-terminal
