### ISSUE TITLE
feat: move `emmet abbreviation` to bottom as default

### ISSUE THREAD

**Issue by cangSDARM** [microsoft/vscode#156396] opened 2022-07-27 03:35 UTC
It's not convenient to always jump down to pick something. 

hope set those settings with default: 

```json
{
  "emmet.showSuggestionsAsSnippets": true,
  "editor.snippetSuggestions": "bottom",
}
```

> I guess this setting is just a workaround, maybe a better setting can be added?

Similar question on SF:
https://stackoverflow.com/questions/66710026/vscode-disable-emmet-abbreviation-editor-on-first-line

**Comment by gjsjohnmurray** [comment] 2022-07-27 04:04
Changing defaults like this risks upsetting a lot of users.

I suggest you make the change in your user level settings. If you work on lots of different environments, can you use Settings Sync?

**Comment by cangSDARM** [comment] 2022-07-27 08:53
> Changing defaults like this risks upsetting a lot of users.
> 
> I suggest you make the change in your user level settings. If you work on lots of different environments, can you use Settings Sync?

The sequential processing of hints and snippets does not seem to depend on the token type. So it's always a pain as a prompt for the first pick.

**Comment by rzhao271** [comment] 2022-07-27 16:22
Duplicate of #51537

**Closed by rzhao271** 2022-07-27 16:22 UTC
Labels: *duplicate
