### ISSUE TITLE
Roots expanded on startup if all were collapsed on close

### ISSUE THREAD

**Issue by LouDou** [microsoft/vscode#136511] opened 2021-11-05 11:09 UTC
Possible regression of https://github.com/microsoft/vscode/issues/53904 ? 

It seems to me that this behaviour is quite annoying, and has changed since the last couple of versions ago - sorry I don't recall exactly when this started.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.8.0-63-generic

Steps to Reproduce:

1. Open VS Code
2. Observe that all roots in the workspace explorer expand

**Comment by IllusionMH** [comment] 2021-11-05 11:38
/duplicate of #134665

Should be already fixed in latest released version

**Closed** 2021-11-05 11:39 UTC
Labels: *duplicate
