### ISSUE TITLE
showInputBox does not pass preset value

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#12244] opened 2016-09-19 06:47 UTC
- VSCode Version: 1.5.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. use `vscode.window.showInputBox`
2. pass a string to the `value` options field
3. Hit enter

Please have a look at the following code:

```typescript
window.showInputBox({
    prompt: 'Please enter a variable name for the default export',
    placeHolder: 'Default export name',
    value: declaration.name,
    validateInput: s => !!s ? '' : 'Please enter a variable name'
}).then(defaultAlias => {
    if (defaultAlias) {
        console.log('something set!');
    }
}));
```

The value in the `value` field of the options hash is not passed, when the user just hits "enter". So if the user is fine with my prediction, an empty string is passed to the promise. The problem is, that this also happens when the user hits escape.

In my opinion, `showInputBox` should pass the inserted value to the promise IF the user hits enter and `undefined` when the user hits escape.

Cheers

**Comment by jrieken** [comment] 2016-09-19 09:15
dupe of #11503

**Closed** 2016-09-19 09:15 UTC
Labels: duplicate
