### ISSUE TITLE
Exception when close all working files and some are dirty

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4253] opened 2016-03-15 14:20 UTC
- VSCode Version: 18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7
- OS Version: any

Steps to Reproduce:

1. Have multiple files open in working files
2. Have at lease one of those files dirty
3. Close All Working files by clicking the close action in the working files header, notice the exception
4. I can not repro this every time, but see it regularly

![screen shot 2016-03-15 at 15 19 34](https://cloud.githubusercontent.com/assets/1926584/13780854/5fa23e5e-eac1-11e5-80f3-3b80b82f65f9.png)

edited: first exception that I now removed was caused by an unrelated issue

**Comment by bpasero** [comment] 2016-03-15 14:30
@isidorn do you get the dialog prompting you to save dirty files before the exception or after?

**Comment by isidorn** [comment] 2016-03-15 14:37
I get the dialog and I say 'do not save' - can not always repro, can you please try it out a couple of times

**Comment by bpasero** [comment] 2016-03-15 14:49
I dont even know what that handler is as it seems in the extension host, moving to @jrieken / @alexandrudima

**Comment by alexandrudima** [comment] 2016-03-15 15:47
@isidorn Can you reproduce without installed extensions?
Hint: "Notification handler" string is not in vscode source code.

**Comment by isidorn** [comment] 2016-03-15 15:52
@alexandrudima I can repro it if I do not have any extensions installed

**Comment by jrieken** [comment] 2016-03-15 16:07
@isidorn The steps don't do it for me, also the message appears nowhere in our sources. Please attach the debugger to the extension host and break on error such that we have a chance to understand this

**Comment by alexandrudima** [comment] 2016-03-15 17:07
@dbaeumer Maybe you use such strings in the language protocol?

**Comment by isidorn** [comment] 2016-03-15 17:15
@jrieken when I attach debugger to the extension host I can not seem to get it to break on this error.
I can easily repro so just drop by my table if you are interested in looking into this.

**Comment by jrieken** [comment] 2016-03-15 17:47
@isidorn Sure you don't have PowerShell tools installed? https://github.com/PowerShell/PowerShellEditorServices/blob/9fa1feaf16d13075c02b420789bbebe9b75c122b/src/PowerShellEditorServices.Protocol/LanguageServer/TextDocument.cs#L59

**Comment by jrieken** [comment] 2016-03-15 17:48
harding @alexandrudima assumption about the language protocol (https://github.com/Microsoft/vscode-languageserver-protocol/blob/46dd8c99166b3cbee69a54e6043b99be221d793c/README.md#L654)

**Comment by isidorn** [comment] 2016-03-15 18:34
@jrieken I do not have powershell installed

**Comment by jrieken** [comment] 2016-03-15 19:03
maybe *tslint*?

**Comment by isidorn** [comment] 2016-03-15 19:09
I do not have any extensions installed :)
I only use open in github but I uninstalled it to try to repro this issue, and I could repro

**Comment by jrieken** [comment] 2016-03-16 07:58
Yes you have. It's called JSON and uses the language server protocol. Moving to @dbaeumer cos this seems to come from `/Users/jrieken/Code/vscode/extensions/json/server/node_modules/vscode-languageserver/lib/protocol.js`

**Comment by dbaeumer** [comment] 2016-03-16 12:07
The protocol calls a notification handler which causes an exception. The protocol on the lowest level catches the excpetion sends it back to the client which prints it to the console. There is nothing I can do better. The root cause of the exception must be fixed.

The root cause lies in the languge server. I receive an update event for a document that is already closed. The interesting question is why? But I will protect my code against it.

**Comment by dbaeumer** [comment] 2016-03-16 12:10
This issue was moved to Microsoft/vscode-languageserver-node#28

**Closed by dbaeumer** 2016-03-16 12:10 UTC
Labels: bug, important

**Comment by dbaeumer** [comment] 2016-03-16 12:13
Published 1.4.1 of the language server.
