### ISSUE TITLE
Text is pasted into integrated terminal instead of search box

### ISSUE THREAD

**Issue by bartsokol** [Microsoft/vscode#33833] opened 2017-09-05 09:32 UTC
- VSCode Version: 1.15.1 64-bit
- OS Version: Windows 10

Steps to Reproduce:

1. Copy some text to clipboard
2. Go to integrated terminal (powershell in my case)
3. Open search box (ctrl-f)
4. Paste copied text into search box.

Behavior:
![pasting-in-terminal](https://user-images.githubusercontent.com/9638275/30054875-dd9b3652-922d-11e7-824d-2d01177a28a7.gif)

Text is pasted into terminal instead of terminal search box, or in both places. Right-click on Find field in the box to paste from context menu also pastes the text into terminal, even without explicitly selecting Paste from context menu. This changes depending on focus, sometimes closing and opening search box changes behavior slightly, but it still appears in one or other way.

**Comment by ihalip** [comment] 2017-09-06 19:47
dupe of #30994 ?

**Comment by bartsokol** [comment] 2017-09-07 07:12
Yup, looks like, I've commented on that issue and referenced to this one already.

**Comment by Tyriar** [comment] 2017-09-11 20:58
Closing as duplicate of https://github.com/Microsoft/vscode/issues/30994

**Closed by Tyriar** 2017-09-11 20:58 UTC
Labels: bug, integrated-terminal
