### ISSUE TITLE
Do not rely on codeSnippet for filtering

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6620] opened 2016-05-21 23:25 UTC
![image](https://cloud.githubusercontent.com/assets/2193314/15451300/902b0c48-1f70-11e6-95a3-8c0bd24e8c29.png)

**Comment by aeschli** [comment] 2016-05-22 11:22
@jrieken This is caused by 9ce57e (for #6320)
In JSON the completion labels (e.g. css.validate) don't contain the doublequotes and we relied on the comparison with the code snippet.
The same for html tags, which is now also broken.

I can add the filter string everywhere, but I suggest to revert the fix for now.

**Comment by jrieken** [comment] 2016-05-23 06:36
I have reverted the changes for #6320. Moving to @aeschli to start using the `filterText` property

**Comment by Tyriar** [comment] 2016-05-23 20:45
Seems fixed now, removing important.

**Comment by jrieken** [comment] 2016-06-25 09:30
@aeschli Is this in reach or still needed that now things became extensions? I'd like to fix #6320

**Closed** 2016-06-27 20:38 UTC
Labels: bug
