### ISSUE TITLE
Multi root workspace closing directories

### ISSUE THREAD

**Issue by scriptcoded** [microsoft/vscode#96782] opened 2020-05-01 15:49 UTC
- VSCode Version: 1.44.2 (also 1.45.0-insider)
- OS Version: Linux x64 5.3.0-51-generic

Steps to Reproduce:

1. Create a multi root workspace
2. Open files from different root folders
3. Root folders in sidebar will close

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2020-05-04 12:46
I can not reproduce this. Can you please provide a short video showing this?
Also can you reproduce if you disable all your extensions

**Comment by scriptcoded** [comment] 2020-05-06 18:50
Here comes a video of the bug in action, as well as a zip containing a sample project. It seems like the issue has to do with the `files.exclude` option in `.vscode/settings.json`. Perhaps I'm simply using the settings incorrectly.

[vscode-multi-root-example.tar.gz](https://github.com/microsoft/vscode/files/4588859/vscode-multi-root-example.tar.gz)

**Comment by isidorn** [comment] 2020-05-07 07:55
Correct, seems like you are having some corner case setup with `files.include`.
I will not have time to debug this right now, thus assigning to backlog.
If you would like to investigate more, here's a code pointer where you can put a breakpoint
F1 > developer tools > sources
https://github.com/microsoft/vscode/blob/3a04fccaf89d9dafc70e64ab23504e15203360f4/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L588

**Comment by Enteleform** [comment] 2020-05-19 11:13
@isidorn 

I'm having this issue as well, and believe that it should be categorized as a bug. The issue seems to have been introduced by one of the recent updates, as I had never experienced this before updating my portable instance of VSCode recently.

&nbsp;  
> I can not reproduce this. Can you please provide a short video showing this?

Here's a sample project that demonstrates the issue. I included cases where the issue is apparent, as well as cases where the expected functionality is intact. 

- [YouTube Video](https://www.youtube.com/watch?v=nI_ov0apvvo)
- [GitHub Repository](https://github.com/enteleform-issues/VSCode--96782--Multi-root-workspace-closing-directories)

&nbsp;  
> Also can you reproduce if you disable all your extensions

Yes

**Comment by MBetters** [comment] 2020-07-10 21:13
I reported it in more detail here: https://github.com/microsoft/vscode/issues/102147

Closed that since it's a duplicate.

I used the built-in issue submitter, so it includes all my system info:

## Actual

- Setup a multi-root workspace. Let's say there's two roots, `rootA` and `rootB`
- Add an entry to `rootA/.vscode/settings.json:files.exclude` to exclude `someSubFolder` in `rootA`
- Navigate back and forth between the roots in the File Explorer
- Watch as the `rootA/someSubFolder` is shown/hidden as you navigate back and forth between the roots.

## Expected

files.exclude settings in all multi-root workspace roots should be respected while navigating between roots, not glitchingly show/hide the subfolders that are supposed to be hidden.

Thanks!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.76GB (10.04GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/ubuntu-vm|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu-vm|
|OS|Linux x64 5.4.0-31-generic|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (4 x 2111)|
|Memory (System)|3.84GB (0.53GB free)|
|VM|100%|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
vagrant|bbe|0.5.0
vscode-log-viewer|ber|0.10.3
turbo-console-log|Cha|1.4.0
path-intellisense|chr|2.2.1
pomodoro|cos|1.1.0
vscode-markdownlint|Dav|0.36.1
xml|Dot|2.5.0
find-related|eam|0.9.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
git-project-manager|fel|1.7.1
code-runner|for|0.11.0
iot-extension-pack|for|0.0.6
platformio|for|0.3.0
terminal|for|0.0.10
vscode-node-red|for|0.2.0
seito-openfile|Fr4|1.8.7
todo-tree|Gru|0.0.178
beautify|Hoo|1.5.0
open-file-from-path|jac|1.3.4
bash-ide-vscode|mad|1.10.2
cortex-debug|mar|0.3.7
dlt-logs|mbe|0.22.0
smart-log|mbe|1.7.0
vsc-lfs|mbe|1.2.0
csharp|ms-|1.22.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.91350
azure-account|ms-|0.8.11
cmake-tools|ms-|1.4.1
cpptools|ms-|0.29.0-insiders2
vsliveshare|ms-|1.0.2427
quicktype|qui|12.0.46
java|red|0.64.1
vscode-xml|red|0.13.0
vscode-yaml|red|0.8.0
bash-debug|rog|0.3.9
vscode-open|san|0.1.0
vscode-fileutils|sle|3.0.1
vscode-hexdump|sle|1.7.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.9
azure-iot-edge|vsc|1.22.0
azure-iot-toolkit|vsc|2.16.2
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
debug|web|0.25.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.1.0
vscode-proto3|zxh|0.4.2
project-manager|ale|11.1.0
expect|bda|0.1.0
vscode-zonefile|Com|0.0.4
systemd-unit-file|coo|1.0.6
arm|dan|1.4.0
cloudformation-yaml-snippets|dst|2.15.0
LogFileHighlighter|emi|2.8.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
openssl-configuration-file|gee|0.0.1
AWK|lug|0.0.2
VS-code-vagrantfile|mar|0.0.7
dotenv|mik|1.0.1
vscode-azurevirtualmachines|ms-|0.1.1
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.8
material-icon-theme|PKi|4.2.0
devicetree|plo|0.1.1
tcl|ras|0.1.0
code-settings-sync|Sha|3.4.3
fish-vscode|sky|0.2.1
vscode-iot-device-cube|vsc|0.2.0
vscode-ruby|win|0.27.0
linkerscript|Zix|1.0.1

(1 theme extensions excluded)

</details>

**Closed** 2020-07-31 15:30 UTC
Labels: file-explorer, under-discussion, wont-fix
