### ISSUE TITLE
Right click in the explorer does not focus the window

### ISSUE THREAD

**Issue by philipmarnef** [microsoft/vscode#138733] opened 2021-12-09 10:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.0 (Universal)
- OS Version: macOS 12.0.1 (21A559)

Steps to Reproduce:

1. focus another app
2. right click in VS Code exporer bar and choose 'new file'
3. VS Code is not focused, so I'm not able to type the filename
4. When trying to click the new file to enter the filename, the explorer gains focus, but now removes the file since it didn't get input for the filename and I have to repeat the process

**Comment by gjsjohnmurray** [comment] 2021-12-10 13:12
Maybe a duplicate of #137551

**Closed** 2021-12-13 22:30 UTC
