### ISSUE TITLE
Editor still inserting spaces when editor.autoIndent set to false

### ISSUE THREAD

**Issue by natevw** [Microsoft/vscode#41639] opened 2018-01-15 19:41 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:49:04.682Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

Steps to Reproduce:

0. Set `"editor.autoIndent": false` in user settings
1. File > New File [this uses Plain Text syntax for me]
2. Type `{` [or a `[` or a `(` and possibly others] on the first line
3. Press return to get a second line

Expected results:

Second line should have **nothing** on it, with cursor at the beginning of line, since `autoIndent` is disabled and I haven't typed anything (or hit an indent shortcut).

Actual results:

Second line has $editor.tabSize spaces on it already, and my cursor is indented! Why?

Notes:

What I want is that when I press "return" when at the end of a line of code, the new line has the same indent as the previous line — no more and no less! I do **not** want any additional syntax-aware indentation when autoIndent is off.

**Comment by julien-l** [comment] 2018-06-13 21:14
I have the same issue:

![autoindent](https://user-images.githubusercontent.com/1530763/41378438-e9244e64-6f13-11e8-8d89-8b30b229eb5a.gif)

My user settings, where `autoIndent` is set to `false`:

![autoindent](https://user-images.githubusercontent.com/1530763/41378481-06f5c0ee-6f14-11e8-9b3a-752ed56f725f.png)

System info:

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

Can reproduce with extensions disabled.

**Comment by rebornix** [comment] 2018-09-10 20:41
Right now the auto indent flag doesn't include the old behavior for pressing enter. We should consider that.

**Comment by rebornix** [comment] 2018-09-19 23:28
Duplicate of #30872

**Closed** 2018-09-19 23:29 UTC
Labels: *duplicate, editor, editor-autoindent, under-discussion
