### ISSUE TITLE
Cannot find name 'Fluxxor' && 'Import Fluxxor' - multiple conflicting Intellisense detections

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode#544] opened 2015-11-24 12:49 UTC
![screen shot 2015-11-24 at 10 43 58 pm](https://cloud.githubusercontent.com/assets/406975/11367128/6a53fb2e-92fd-11e5-911c-752e64b96a2f.png)

**Comment by jwulf** [comment] 2015-11-24 12:51
This is on a Mac.

**Comment by jwulf** [comment] 2015-11-24 13:05
Perhaps it is the `* as Fluxxor`?

`import * as Fluxxor from 'fluxxor'`

**Comment by dbaeumer** [comment] 2015-11-30 10:17
@jwulf would you be able to share a folder with me that shows the behavior.

**Comment by unional** [comment] 2016-04-15 20:51
Just encountered this also.
The code runs fine on `tsc` but error on vscode (`ts language service`). Here is how to reproduce:

```ts
// s.ts
export class Foo {}

// m.ts
import { Foo } from './s';
declare namespace Foo { };
export = Foo;

// c.ts
import * as Foo from './m';

console.log(Foo);
```
![image](https://cloud.githubusercontent.com/assets/3254987/14574542/1a0e1bca-0311-11e6-9dc9-27838f267675.png)

**Comment by unional** [comment] 2016-04-15 20:51
Reference: 
https://github.com/typed-typings/npm-any-promise/pull/1

**Comment by unional** [comment] 2016-04-15 20:57
I tested this on Windows.

Code: 1.0  :tada: 
Also tested with TypeScript@next using `settings.json/typescript.tsdk`: `1.9.0-dev.20160415`

**Comment by dbaeumer** [comment] 2016-04-18 09:22
@unional thanks for the code test case. I am moving this to TS since the seems to be caused by the reexport in m.ts

**Comment by dbaeumer** [comment] 2016-04-18 09:23
This issue was moved to Microsoft/TypeScript#8140

**Closed by dbaeumer** 2016-04-18 09:23 UTC
