### ISSUE TITLE
Toggle Line Comment does not toggle

### ISSUE THREAD

**Issue by tore-jan-skarstein** [microsoft/vscode#109889] opened 2020-11-03 07:15 UTC
Issue Type: <b>Bug</b>

# Highlight the following two lines your PS script and choose Menu > Edit > Toggle:

# Write-Host("The hashtag should be removed on toggle")
Write-Host("Prepend a hashtag to this line")

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.85GB free)|
|Process Argv|--crash-reporter-id fc41337f-535f-4f66-bf45-11f7fca41661|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
vscode-azurefunctions|ms-|1.0.0
azure-account|ms-|0.9.3
powershell|ms-|2020.6.0
run-in-powershell|tob|1.1.0

</details>

**Comment by yume-chan** [comment] 2020-11-03 08:26
I guess the correct formatting should be 

```powershell
# Highlight the following two lines your PS script and choose Menu > Edit > Toggle:
# Write-Host("The hashtag should be removed on toggle")
Write-Host("Prepend a hashtag to this line")
```

Duplicate of #93374

**Closed** 2020-11-03 23:16 UTC
Labels: *duplicate
