### ISSUE TITLE
stick with #193421, memory leak

### ISSUE THREAD

**Issue by soma-liang** [microsoft/vscode#200015] opened 2023-12-05 09:14 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: V1.84.2
- OS Version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Sorry for not responding to question #193421 during this period of time.
Currently, I have downloaded the latest version of vscode V1.84.2 and written a demo for testing, but the issue still exists
https://github.com/soma-liang/demo-cache.git

There are two questions here
Steps to Reproduce:
1. Run this demo
2. Run command StartTest2, The Treeview icon constantly replaces and refreshes the display
3. After repeating this cycle for several hours, a memory leak occurred
4. Count the memory usage once per second, as shown in the following figure
![icon_cache](https://github.com/microsoft/vscode/assets/84301995/f57dd87d-9469-4a41-861b-4dbd0eddda40)

Steps to Reproduce:
1. Run this demo
2. Run command Hello World,The extension will create an outputchannel
3. Run command StartTest, Outputchannel will continuously output content and clear it after reaching a certain quantity
4. After repeating this cycle for several hours, a memory leak occurred
5. Count the memory usage once per second, as shown in the following figure
![output_cache](https://github.com/microsoft/vscode/assets/84301995/e3bfc637-50b5-4548-8803-e7fc7f21600b)

**Comment by soma-liang** [comment] 2023-12-05 09:25
Supplement:
Question 2: When there is a memory leak, vscode OutputChannel. clear() is unable to clear previous content properly

**Comment by soma-liang** [comment] 2023-12-19 10:03
May I ask if there is any progress

**Comment by alexr00** [comment] 2023-12-19 10:51
I've tried the sample for the tree view, but it doesn't appear to actually modify the tree:

![image](https://github.com/microsoft/vscode/assets/38270282/91517980-09a0-4916-a953-872c41905e29)

**Comment by soma-liang** [comment] 2023-12-19 11:11
please update and try again
![image](https://github.com/microsoft/vscode/assets/84301995/8d884321-26e3-4899-9e6f-cd671aa70bc4)

**Comment by alexr00** [comment] 2023-12-19 11:32
Thanks for the update. Using the chrome or edge dev tools to check the heap, I can't reproduce any increase in memory usage. How are you generating your chart? Can you give steps using the chrome or edge dev tools?

**Comment by soma-liang** [comment] 2023-12-23 03:48
Excuse me, may I ask about the current progress of this issue

**Comment by alexr00** [comment] 2024-01-09 14:20
There is a real memory leak in the tree view. Fix coming shortly.

**Comment by alexr00** [comment] 2024-01-09 14:31
I think I got all the tree memory leaks in https://github.com/microsoft/vscode/pull/202080. Adding @sandy081 for the output memory leak.

**Comment by sandy081** [comment] 2024-01-09 15:27
@soma-liang Thanks for reporting the issue. Since you are able to reproduce the memory leak for output channel, can you please let me know which process is leaking? Once you figured out the process, can you please profile that process and share it with us? You can find steps to profiling the process here - https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by soma-liang** [comment] 2024-01-11 08:09
@sandy081 In the problem description, there is a problem extension link [https://github.com/soma-liang/demo-cache.git](url) where you can run to view the problem

**Comment by sandy081** [comment] 2024-01-15 14:38
Thanks for sharing the link. It would be great if you can share the requested information that will help us in finding the root cause quickly

**Comment by soma-liang** [comment] 2024-01-16 07:04
about output memory leak.
You can use the demo step to run for more than 3.5 hours, which will result in memory leakage.
In vscode.OutputChannel always calls appendLine(), and call clear() after reaching a certain number.
After a few hours, the accumulated information in the OutputChannel will be more and more. After the clear(), calling appendLine() will also generate the information that needs to be cleared before.

**Comment by sandy081** [comment] 2024-01-17 04:55
> After the clear(), calling appendLine() will also generate the information that needs to be cleared before.

Do you mean, this shows the previous generated information after clear? Is this the memory leak you are talking about?

**Comment by soma-liang** [comment] 2024-01-18 09:24
Yes, memory leakage caused by constant appendLine() and invalid clear()
Strangely, clear() was effective in the first few hours

**Comment by sandy081** [comment] 2024-01-24 13:47
This is not a memory leak. Because the content is written and read from the file. This seems to be a bug in the feature. It seems this issue has a fix already for a memory leak. I would suggest to have an issue tracking one problem for better tracking. Therefore, I would close this fixing for the first issue.

@soma-liang I would request you to create a separate issue for the above analysis you have done for output. I also request to share steps which can help me in reproducing easily.

**Closed by sandy081** 2024-01-24 13:47 UTC
Labels: info-needed, perf, output

**Comment by TylerLeonhardt** [comment] 2024-01-25 22:16
@alexr00 do have some good steps for this one?

**Comment by connor4312** [comment] 2024-01-25 22:25
I validated with the initial steps for several minutes, and compared memory snapshots to look for leaks. It lgtm

**Comment by soma-liang** [comment] 2024-02-18 10:07
@sandy081 I have created a new issue #205466
