### ISSUE TITLE
Delay between key-press and rendering

### ISSUE THREAD

**Issue by highfestiva** [Microsoft/vscode#22875] opened 2017-03-20 09:28 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 7 Enterprise, SP1 **and** Windows 10 Home

Steps to Reproduce:

1. Open a large file (for instance a 20k+ lines python file).
2. Press PageDown and watch the delay between each key-press and when the rendering happens. It's hard to measure, but I'd say the delay is at least 100 ms, probably more.
3. Load the same file in Notepad++ and do the same experiment. You'll see that there is no noticeable delay between the key-press and the rendering.

This seems to happen on all extensions all the time, it seems fundamental. My colleague has it too, and the commenter on my StackOverflow question as well; I believe everyone has it. It's just that a lot of developers are fine with it.

I've seen no suggestions to circumvent this delay in the question I posted on [StackOverflow](http://stackoverflow.com/questions/39648612/visual-studio-code-rendering-delay). This is a nuisance and really a showstopper for me - I can't use an editor with too slow rendering - which is a shame as I think Visual Studio Code seems like an otherwise awesome tool.

**Comment by weinand** [comment] 2017-03-20 10:00
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by alexandrudima** [comment] 2017-03-31 11:03
@highfestiva Does the issue reproduce for you if:

* close all instances of vs code. Run from the command line `code --disable-extensions`. Does the issue reproduce?

* copy paste the contents of the python file to a .txt file. Does the issue reproduce?

Is it also possible that you share this file or some file very similar to it with us such that we can try to reproduce?

P.S. Not that the first commenter on StackOverflow appears to talk about Visual Studio, not Visual Studio Code, and the second commenter on StackOverflow offers a hypothesis.

**Comment by highfestiva** [comment] 2017-03-31 12:46
Please try it yourself. It happens to me always, and on my colleagues computer as well. It doesn't bother him (very slow typist), it bothers me.

**Comment by alexandrudima** [comment] 2017-04-04 13:42
@highfestiva I am trying it myself, but it always depends... on installed extensions, perhaps on the file that is being rendered, etc.

Here is what I have tried and I could not reproduce any slowness7:

```
parents, babies = (1, 1)
while babies < 100:
    print 'This generation has {0} babies'.format(babies)
    parents, babies = (babies, parents + babies)
```

and I duplicated it until I got 20436 lines.


I am pressing page up and page down and I am not noticing any delays.

**Comment by highfestiva** [comment] 2017-04-04 22:36
Did you make the comparison with Notepad++? (You can get a blind spot for anything, including delays, if you're used to them.)

**Comment by alexandrudima** [comment] 2017-05-10 19:10
Closing after a number of days with no reply. There is no action we can take if we cannot reproduce.

**Closed by alexandrudima** 2017-05-10 19:10 UTC
Labels: needs more info

**Comment by highfestiva** [comment] 2017-05-10 19:52
Take that as a 'no.' Someone please make a fast code editor without bloat, but with the bare minimum of features.
