### ISSUE TITLE
Extensions: install and activate vscode-smoketest-check extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113746] opened 2021-01-04 10:56 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98914&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&l=87

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Extensions
           install and activate vscode-smoketest-check extension:
     Error: Timeout: is active element '.quick-input-widget .quick-input-box input' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by sandy081** [comment] 2021-01-07 15:18
From error it seems app is waiting for quick access to open while the active element is a web view

> Active element not found. Current active element is 'HTML > BODY.mac > DIV.file-icons-enabled.monaco-workbench.mac.chromium.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV#webview-extensionEditor > WEBVIEW.webview.ready'. Looking for .quick-input-widget .quick-input-box input

I can also repro this on insiders, when there is a web view open (either extension editor or markdown preview) some of the keybindings are not detected, for eg: command pallette is not opened using keyboard shortcuts. I cant repro it always but it happens when I am switching apps.

Hence assigning to @mjbvz

**Comment by mjbvz** [comment] 2021-01-08 18:28
Duplicate of #110276 I believe

**Closed by mjbvz** 2021-01-08 18:28 UTC
Labels: bug, smoke-test-failure
