### ISSUE TITLE
Cannot press Enter in Settings Editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#52973] opened 2018-06-26 14:08 UTC
* Open Settings on Windows
* Try to press <kbd>Enter</kbd>:
* It does not work:
![image](https://user-images.githubusercontent.com/5047891/41917612-1edab7e0-795b-11e8-8ec2-b91b23c56b6e.png)

**Comment by alexandrudima** [comment] 2018-06-26 14:09
Adding the following to my `keybindings.json` has unblocked me:

```
{
	"key": "enter",
	"command": "-settings.action.editFocusedSetting",
	"when": "inSettingsEditor"
}
```

**Comment by sulkhanp** [comment] 2018-06-26 14:55
@alexandrudima dupe of #52942 ?

**Comment by roblourens** [comment] 2018-06-26 16:54
Duplicate of #52973

**Closed by roblourens** 2018-06-26 16:54 UTC
Labels: important
