### ISSUE TITLE
Multi-select is not correct

### ISSUE THREAD

**Issue by zhoudotnet** [Microsoft/vscode#16960] opened 2016-12-09 05:39 UTC
- VSCode Version: v1.7
- OS Version: win7

Steps to Reproduce:

1. Open vscode

2. Input the contents:
Account
acb

3. select this character: "c", and click Ctrl + F, then you will see the issue. It should have 3 cursors, but it only have 2 cursors.

**Comment by zhoudotnet** [comment] 2017-02-22 06:30
When do you fix this issue?

**Comment by alexandrudima** [comment] 2017-03-31 07:21
Duplicate of #6661

**Closed by alexandrudima** 2017-03-31 07:21 UTC
Labels: bug, editor-multicursor
