### ISSUE TITLE
Copy path shortcut (Alt + Shift + C) is broken on Windows 10

### ISSUE THREAD

**Issue by prashantsharmain** [Microsoft/vscode#53843] opened 2018-07-09 05:48 UTC
Issue Type: <b>Bug</b>

**Steps to reproduce**:

1. Open any file in editor
2. Press the key combination Alt + Shift +C to copy current file's path to clipboard
3. Paste clipboard contents to a file in a different text editor

**Actual:** 

File path is not pasted

**Expected:**

Keyboard shortcut Alt + Shift +C should copy the current file's path to clipboard

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (1.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.1.0

</details>

**Comment by bpasero** [comment] 2018-07-09 08:50
A regression from https://github.com/Microsoft/vscode/commit/0ec5e324d1ad6ec8b699295f23b4d01da3efaa4c

**Comment by isidorn** [comment] 2018-07-17 13:52
We changed this behavior since that keybinding was also used by the find widget.
The full explanation what we did can be found here https://github.com/Microsoft/vscode/issues/47947

Closing as designed since only 1 user complained in the last 3 months. This only works when focus in the explorer. As a workaround you can bind your custom keybinding for this and remove the `when` clause.

**Closed by isidorn** 2018-07-17 13:52 UTC
Labels: bug
