### ISSUE TITLE
An installed extension has "recommended" badge in the Extensions panel

### ISSUE THREAD

**Issue by radevm** [Microsoft/vscode#45135] opened 2018-03-06 12:37 UTC
### Issue Type
Bug

### Description

One of the installed extensions has the "recommended" badge with the explanations "This extension is recommended based on the files you recently opened".

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|Memory (System)|7.43GB (1.99GB free)|
|Process Argv|C:\Program Files\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.2.3
python|ms-|2018.1.0
vscode-hexdump|sle|1.6.0

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by mjbvz** [comment] 2018-03-06 19:20
Duplicate of #37898 / #40881

**Closed by mjbvz** 2018-03-06 19:20 UTC
