### ISSUE TITLE
Focus vanishes after refactoring

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#5220] opened 2016-04-13 09:48 UTC
- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Press F2 on a variable
2. Refactor the name
3. Focus is somewhere else, but not in the editor anymore

**Comment by jrieken** [comment] 2016-04-25 12:24
closing as dupe of #5008

**Closed by jrieken** 2016-04-25 12:24 UTC
Labels: bug

**Comment by DasJott** [comment] 2016-06-07 14:14
Thank you!
