### ISSUE TITLE
[Terminal] (Windows) 'clear' or 'cls' doesn't empty the backbuffer, i can still scroll up and see the history

### ISSUE THREAD

**Issue by RUSshy** [microsoft/vscode#114086] opened 2021-01-09 19:01 UTC
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Install GIT for windows
2. Setup the bash shell as default in vscode
3. Open terminal view, type some stuff to fill the buffer/history
4. type 'clear'

Expected: buffer should be fully cleared

What happen instead: I can scroll up and see what i had before clear

This does not happen when i do the same using the Terminal for Windows, same on Linux, same on macOS

This only happens on vscode's terminal on Windows 

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2021-01-12 16:53
What happens if you clear and instead of scrolling, zoom in or out?

**Comment by RUSshy** [comment] 2021-01-12 18:14
https://user-images.githubusercontent.com/18348637/104354800-0e20da00-550a-11eb-9071-ac45fd201364.mp4

i recorded a video, will be easier to explain, i hope

- i press enter multiple times
- i type 'clear'
- i try to zoom|in/out (it now show 2 lines instead of 1)
- i try to scroll
- i type again 'clear'

**Comment by RUSshy** [comment] 2021-01-12 18:17
I get the same issue if i use the stock cmd.exe

cls never clear the buffer, i can still scroll up and see history

if i type 'cls' in the windows Command Prompt window, it properly clear the buffer and i can't scroll anymore

**Comment by NotWearingPants** [comment] 2021-03-02 22:27
Duplicate of #75141 I think.

**Comment by meganrogge** [comment] 2021-03-29 19:10
Duplicate of #75141

**Closed** 2021-03-29 19:10 UTC
Labels: *duplicate, bug, integrated-terminal
