### ISSUE TITLE
Typescript Intelligence Bug: different behaviors on  interface implementation.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/vscode#33000] opened 2017-08-23 04:20 UTC
- VSCode Version: Version 1.15.1 (1.15.1)
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. The minimal sample codes:
```ts
interface Component<P, S> {
  componentWillMount?(): void;
  componentDidMount?(): void;
  componentWillReceiveProps?(nextProps: Readonly<P>, nextContext: any): void;
  shouldComponentUpdate?(nextProps: Readonly<P>, nextState: Readonly<S>, nextContext: any): boolean;
  componentWillUpdate?(nextProps: Readonly<P>, nextState: Readonly<S>, nextContext: any): void;
  componentDidUpdate?(prevProps: Readonly<P>, prevState: Readonly<S>, prevContext: any): void;
  componentWillUnmount?(): void;
}
class Component<P, S> {
}

class MyComponent extends Component<{}, {}> {
  // Mark1
  shouldComponentUpdate(nextProps, nextState, nextContext) {}
  // Mark2
}
```
2. Two problems:

    a. [maybe bug] At Mark1 and Mark 2, typing ctrl + space gives me intelligence suggestion: all the life cycle methods. MyComponent just extends the Component not implements it. Compare with typescript playground, I can't even get any suggestions in `extends` or `implements` way. Does it is a bug that we get suggestions?

    b. Assuming point a is normal behavior. 
        [bug] At Mark1, after popping suggested methods and select, auto-completion provides us the full method skeleton. e.g. type character 'c' (or ctrl + space), then select the `componentDidUpdate`, auto-completion produces 'componentDidUpdate(prevProps, prevState, prevContext)'.
        [bug] At Mark2, type character 'c', I can't get any methods suggestion.
        [bug] At Mark2, type ctrl + space, I get the unused methods suggestion. If I select one, auto-completion only produces the method's name. e.g. 'componentWillReceiveProps'. I have to fill the parameters, compare with Mark1 the different behavior make me confused.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-08-23 06:47
A. I think the playground may be using an old TS version. You should get suggestion for public or protected superclass members in the subclass. This was only added in TS 2.4

B1. We only complete the properties when you have enabled `    "typescript.useCodeSnippetsOnMethodSuggest": true`. @zheeeng What is the expected behavior in this case?

B2 + B3. These are bugs. I've opened https://github.com/Microsoft/TypeScript/issues/17977 to track this.

**Comment by zheeeng** [comment] 2017-08-23 07:14
@mjbvz It is a  mistake on marking B1 as bug. For point A, any docs guide us how to writing class and interface which have the same name, and does this interface will be actually set on the class automatically?

**Comment by mjbvz** [comment] 2017-08-23 20:50
Take a look at this StackOverflow answer: https://stackoverflow.com/a/43056090/306149

I believe the resulting `Component` type in your example will be a merged version of the `class` and `interface`. It will have a `new` implementation from the `class` along with all the properties from the `interface`. However, as far as I know, the class `Component` does not actually implement the interface `Component`.

Closing this issue as upstream, tracked against TS

**Closed by mjbvz** 2017-08-23 20:50 UTC
Labels: new release, typescript, upstream

**Comment by zheeeng** [comment] 2017-08-24 10:01
@mjbvz I have read this SO answer before created this issue. According to his explains I came up that why I get suggestions when 'MyComponent just extends the Component not implements it'.
If I use `Component` as an interface, it is reasonable. But I get suggestions in extending way, I want some docs about this behaviour and I guess that it is may be caused by the newer features of TS.

Could you re-open it for getting more help?

**Comment by mjbvz** [comment] 2017-08-24 20:16
Since that is more of a TS question, please try asking on SO or over on the [TS github issues](https://github.com/Microsoft/TypeScript/issues)
