### ISSUE TITLE
Branches with / do not appear in browser

### ISSUE THREAD

**Issue by cmurphyb** [microsoft/vscode#136760] opened 2021-11-09 15:09 UTC
When opening a github repo in the browser, checking out a branch with a "/" in the name of the branch will not go to the branch presumably due to the URI.

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
Embedder: vscode.dev

**Comment by joyceerhl** [comment] 2021-11-15 20:48
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/70

**Closed by joyceerhl** 2021-11-15 20:48 UTC
Labels: bug, vscode.dev
