### ISSUE TITLE
git源代码管理，切换输入法时偶现提交消息输入框卡死

### ISSUE THREAD

**Issue by limoning** [microsoft/vscode#113569] opened 2020-12-30 03:30 UTC
Issue Type: <b>Bug</b>

1.切换到源代码管理选项卡
2.提交消息输入框，输入文字（可能有切换输入法（搜狗））偶现卡死，无法输入文字现象，重启vscode后卡死现象消失

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 99777281-8664-4c9f-b778-914407c2b8fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
project-manager|ale|12.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
EnglishChineseDictionary|Cod|1.0.1
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.1.0
vscode-html-css|ecm|1.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
gc-excelviewer|Gra|3.0.40
beautify|Hoo|1.5.0
comment-translate|int|1.4.2
svn-scm|joh|2.13.5
vscode-language-pack-zh-hans|MS-|1.52.2
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
vetur|oct|0.31.3
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.14
element-ui-snippets|SS|0.7.2
code-spell-checker|str|1.10.2
language-stylus|sys|1.11.0
tabnine-vscode|Tab|3.1.23
vscode-icons|vsc|11.0.0
vscode-import-cost|wix|2.13.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.12
project-tree|zhu|0.3.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by eamodio** [comment] 2021-01-05 06:13
Duplicate of #112621

**Closed by eamodio** 2021-01-05 06:13 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
