### ISSUE TITLE
Timeline view does not have filter to choose local or git history

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#225950] opened 2024-08-19 07:55 UTC
![Image](https://github.com/user-attachments/assets/3823db8f-958f-4223-8475-f35be06aea2a)

**Comment by gjsjohnmurray** [comment] 2024-08-19 08:03
On several view in Insiders I have recently seen contributed command buttons disappearing. Dragging the view elsewhere and then resetting its location fixes the issue until it happens again.

See https://github.com/microsoft/vscode/issues/225844#issuecomment-2294901707

**Comment by gjsjohnmurray** [comment] 2024-08-19 08:06
Different symptoms with Timeline view. My Filter button was displaying normally until I dragged Timeline onto Panel. There it didn't display Filter. Using its titlebar context menu option to Reset Location didn't bring the filter button back.

**Comment by bpasero** [comment] 2024-08-19 08:48
Caused by https://github.com/microsoft/vscode/commit/08735536e372b5cf3bb054933308f6756e965ec1

**Comment by jrieken** [comment] 2024-08-19 09:36
/duplicate of https://github.com/microsoft/vscode/issues/225718

**Closed** 2024-08-19 09:37 UTC
Labels: bug, *duplicate, menus, confirmed, regression
