### ISSUE TITLE
Add "accept theirs", "accept ours" git commands/context menu actions

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#66950] opened 2019-01-22 22:03 UTC
I'm not sure how much this is due to me not being familiar with merging conflicts in vscode but I'm finding it next to impossible to use. For files with conflicts which vscode recognises (i.e. .py files) when I open the conflicted file it displays a bar at the top allow me to select the incoming changes or local changes. For all other files there doesn't seem to be any way to accept / reject changes even at the file level (i.e. accept/reject all incoming changes)

i.e. I have an ipynb file with conflicts. Under MERGE CHANGES it has a C beside it. If I open the file it doesn't present and options to diff or merge the files. I have `nbdime` installed but not sure how to configure it with vscode. But the issue also occurs for .log files etc.

If I right click on the files under MERGE CHANGES, there are options to 'Accept All Current' or 'Accept All Incoming'. Neither of these appear to do anything, there's no change to the indicators - the C icon is still displayed, and trying to stage continues to presents the warning "are you sure you want to stage xyz.ipynb with merge conflicts"

I'm having to resort to command line merging.

**Comment by joaomoreno** [comment] 2019-01-23 08:40
> If I open the file it doesn't present and options to diff or merge the files.

Is that file binary? What does VS Code show when you click it? How do you solve that file in the command line?

**Comment by david-waterworth** [comment] 2019-01-24 00:01
No it's a text format (basically json) whcih contains a mix of "code", "output" and metadata so it';s basically impossible to merge using a normal diff tool (there's a 3rd party tool called `nbdime` which does an intelligent diff). Other text files weren't working properly either though.

When I opened the file, it opened in the editor as normal. The bar at the top didn't appear with the Accept Current Changes | Accept Incoming Changes etc as per the image in the first reply to this issue - https://stackoverflow.com/questions/38216541/visual-studio-code-how-to-resolve-merge-conflicts-with-git

i resolved in the console manually by

git checkout --theirs \conflicted\file 
git add \conflicted\file

based on Pascal Fares answer to https://stackoverflow.com/questions/10697463/resolve-git-merge-conflicts-in-favor-of-their-changes-during-a-pull.

**Comment by joaomoreno** [comment] 2019-01-24 09:45
So. Is the resolution for you for this file always to "take theirs"?

**Comment by david-waterworth** [comment] 2019-01-24 22:37
Either "take theirs" or "take mine" if merging isn't practical.  As I mentioned in the original issue this does seem to be an option but it didn't appear to work. On the Source Control file tree the files had the icon C which presumably indicates a conflict. The right mouse context menu presented the options  'Accept All Current'  and 'Accept All Incoming' but I couldn't see any visual status change to indicate these were having any effect (and to the contrary after selecting 'Accept All Incoming'  then stage changes an error message displayed indicated the files were still in conflict).

Even better would be to be able to associate the custom diff tool (i.e. ipynb -> nbdiff) but I'm not even sure if this is possible, I couldn't get the command line version to work.

**Comment by joaomoreno** [comment] 2019-01-28 08:55
What we're missing are context menu commands which "accept theirs" or "accept ours". The current ones come from the git merge built-in extension and need to be removed.

**Comment by Kingwl** [comment] 2020-05-09 04:57
It's useful feature, I'd like to work on this.

**Comment by aleksandarbos** [comment] 2021-03-29 19:22
What's the status on this one? Having a better way of handling binary file conflicts using VS code would be pretty handy.

**Comment by lszomoru** [comment] 2024-12-10 20:47
Closing as duplicate of [102857](https://github.com/microsoft/vscode/issues/102857)

**Closed by lszomoru** 2024-12-10 20:47 UTC
Labels: help wanted, feature-request, git
