### ISSUE TITLE
Bug introduced in version 1.58.2: Insane warnings when opening files

### ISSUE THREAD

**Issue by edbird** [microsoft/vscode#129895] opened 2021-07-31 13:36 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open VS Code
2. Open folder containing code

This appears:

![image](https://user-images.githubusercontent.com/2939755/127741496-d00e2dbe-6be6-4f40-8fac-820a245f0950.png)

I consider this to be a "bug" because I cannot for the life of me imagine why someone would consider this addition to be a good idea.

Why would I want VS Code to ask me if I trust the code I am opening? That is insane. I obviously did not open the file/folder by accident.

Please remove this annoying warning in future release.

Considering that people who write code are usually technically competent people, I can't see that this warning provides anything of useful value to even a single user of the IDE.

**Comment by gjsjohnmurray** [comment] 2021-07-31 14:48
See #126348

**Comment by Ranguna** [comment] 2021-07-31 18:01
@gjsjohnmurray  that issue is about disabling this feature, this issue is about removing it altogether.

**Comment by edbird** [comment] 2021-08-01 09:19
To further elaborate considering the linked issues from the above linked issue (126348).

One of the points I did not make was you have essentially written a completely new IDE, and it is genuinely a very, very good software tool.

I am a long-time vim addict, and although VS Code lacks some of the functionality that vim offers, a significant amount of that functionality can be "emulated" using keyboard shortcuts.

However, like many very, very good software tools which have been developed throughout history, you are now in danger of making your very, very good software tool into bloatware.

The reason why things like vim are good is because they are fairly minimalist, or at least written in such a way that they are responsive, and work well on a broad range of hardware, including decade old laptops.

Your problem here is you have added a "feature" which isn't just a pain-in-the-arse for the developers who use VS Code (because no one wants to click through a load of pop-up messages which disable features of your IDE) but it also bloats out the software.

If you keep adding these kind of things, VS Code will end up being bloated and slow, and then it won't be a good experience to use.

You are already writing an electron app with JS. You do not have the luxury of writing in something like C / C++ where whatever you write, as long as it is reasonable code, will run fast, on basically anything. You are several software layers higher in a stack, and therefore the code you write is likely to be less efficient, by default.

Look - my point here is this: Consider how your software runs on something like a Raspberry Pi, or a 10 year old laptop. Why *shouldn't* the user be able to run VS Code on this, and have it run well? I just don't see why every dev should be expected by default to develop on a workstation replacement laptop which was released in the last 24 months or an i7 desktop with 32 gigs of ram.

Yes, the computer I am using to submit this issue does have 64 gig of ram, and an 7th gen i7 in it - but someone else who doesn't have that should be able to use VS Code, and it should be a responsive, good user experience for them.

Generally speaking: By all means add new features which are genuinely useful. (Git integration is one example.) But please also provide a way to turn these things off for those who don't want them and please do not add bloatware which just obstructs the developer from doing his work.

**Comment by Ranguna** [comment] 2021-08-01 09:53
@edbird 
> considering the linked issues from the above linked issue (126348).
> (...)
> But please also provide a way to turn these things off for those who don't want them

The issue #126348 does indeed provide "a way to turn these things off for those who don't want them": https://github.com/microsoft/vscode/issues/126348#issuecomment-861460514

About vscode being heavy, that is not false but I don't think it is directly related to this issue (unless any vscode devs wants to pitch in saying that this trust banner indeed affects performance). It's heavy due to many reasons, one of which is the underlying engine, either way I don't think the feature that the OP is mentioning affect in any way how CPU/RAM heavy vscode is.

Please keep the comments on topic and do not derail the discussion.

**Comment by Ranguna** [comment] 2021-08-01 09:55
@edbird 
> considering the linked issues from the above linked issue (126348).
> (...)
> But please also provide a way to turn these things off for those who don't want them

The issue #126348 does indeed provide "a way to turn these things off for those who don't want them": https://github.com/microsoft/vscode/issues/126348#issuecomment-861460514

**Comment by edbird** [comment] 2021-08-03 16:18
> @edbird
> 
> > considering the linked issues from the above linked issue (126348).
> > (...)
> > But please also provide a way to turn these things off for those who don't want them
> 
> The issue #126348 does indeed provide "a way to turn these things off for those who don't want them": [#126348 (comment)](https://github.com/microsoft/vscode/issues/126348#issuecomment-861460514)

The question I would probably ask is "why is it on by default and not off by default".

**Comment by Ranguna** [comment] 2021-08-04 09:10
I would say vscode people are doing security by default. It's not hard to imagine having an extension run a test suite and somewhere along the code it'll trigger a `rm -rf ~`.

Tbh, I'm opposed to adding this feature to vscode, but since it's already here, I'm guessing it's gonna be a little harder to remove it vs to push it back if it hadn't been released yet.

But vscode's devs probably have more insight about this.

**Comment by tanhakabir** [comment] 2021-10-05 06:23
Closing as duplicate of https://github.com/microsoft/vscode/issues/126348 as @gsjohnmurray pointed out. Thanks for your feedback!

**Closed by tanhakabir** 2021-10-05 06:23 UTC
Labels: workspace-trust
