### ISSUE TITLE
v1.50.1 creates debug.log automatically

### ISSUE THREAD

**Issue by ent3r** [microsoft/vscode#108886] opened 2020-10-18 09:45 UTC
Issue Type: <b>Bug</b>

1. Open a folder
2. Open any file in said folder

VSCode will automatically create a debug.log file. This issue was not present on v1.50, but appeared on v1.50.1.

Related: #105191. (Bug was fixed on v1.49.2, has now reappeared again). Repro steps from that issue are likely to work now too.

VS Code version: VSCode 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-15T10:44:06.171Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.9.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.10
githistory|don|0.6.12
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vscode-front-matter|eli|1.7.0
prettier-vscode|esb|5.7.1
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
gc-excelviewer|Gra|3.0.40
Python-autopep8|him|1.0.2
vue-snippets|hol|0.1.12
svg|joc|1.3.11
docthis|joe|0.7.1
vsc-python-indent|Kev|1.11.0
kite|kit|0.129.0
restructuredtext|lex|129.0.0
template-string-converter|meg|0.1.8
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
debugger-for-chrome|msj|4.12.11
vscode-streamdeck|nic|4.1.5
hide-gitignored|npx|1.1.0
vetur|oct|0.28.0
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.3.0
ruby|reb|0.27.0
synthwave-vscode|Rob|0.1.8
trailing-spaces|sha|0.3.1
svg-preview|Sim|2.8.3
control-snippets|svi|1.9.1
sass-indented|syl|1.8.12
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|11.0.0
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.9.3

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment] 2020-10-18 21:47
I am unable to repro with the steps from previous issue as well as the current one. We haven't changed the runtime between `1.50` and `1.50.1`, so highly unlikely the issue resurfaced. Can you paste the contents of `debug.log` ?

**Comment by turbcool** [comment] 2020-10-19 04:10
I had same problem. For me it was `ckolkman.vscode-postgres` extension that was creating `debug.log`.

**Comment by balintbalazs** [comment] 2020-10-19 09:28
I can confirm this behaviour. The contents of the file:
```
[1019/095427.124:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
```

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by ent3r** [comment] 2020-10-19 13:32
For some reason I can't repro anymore, but here is one of the files it created while i still could repro:
```
[1018/120034.920:ERROR:registration_protocol_win.cc(103)] CreateFile: Systemet finner ikke angitt fil. (0x2)
[1018/120330.913:ERROR:registration_protocol_win.cc(103)] CreateFile: Systemet finner ikke angitt fil. (0x2)
[1018/120724.633:ERROR:registration_protocol_win.cc(103)] CreateFile: Systemet finner ikke angitt fil. (0x2)

(Poorly) Translated: The system cannot find the specified file
```

**Comment by AlphaEndgame** [comment] 2020-10-19 15:41
Hello, I can confirm that this issue is still happening on v1.50.1. VSCode keeps creating a debug.log on the root of my working directory with these contents:

`[1019/155955.848:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)`

**Comment by cDurhamZP** [comment] 2020-10-19 15:46
I am having the same issue. I've ran as administrator as well.

`[1016/093125.450:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
[1016/121627.459:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
`

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by deepak1556** [comment] 2020-10-19 15:49
@balintbalazs @AlphaEndgame @cDurhamZP based on the log, the issue you are facing is from chrome and not vscode please refer to https://bugs.chromium.org/p/chromium/issues/detail?id=1138853 for more info.

@ent3r I am closing this issue, can reopen if there is a repro with vscode, the issue is getting side tracked with unrelated bug from chrome or other chromium related browsers.

**Closed by deepak1556** 2020-10-19 15:49 UTC
Labels: needs more info, windows

**Comment by ent3r** [comment] 2020-10-19 15:54
that would make sense if it wasnt for the fact that i dont have chrome/chromium installed. im guessing since electron is also chromium it goes under that bug?

**Comment by cDurhamZP** [comment] 2020-10-19 16:36
I managed to get the error to go away by removing an extension: JavaScript Debugger (Nightly)

Not sure if correlation or causation, but there it is

**Comment by deepak1556** [comment] 2020-10-19 17:10
@cDurhamZP the problem is not the extension but the extension spawning any chromium browser for debugging which would hit the issue I had linked.

>  im guessing since electron is also chromium it goes under that bug?

@ent3r Depends on what other electron app you might have, if there is a reliable repro it would help.

**Comment by ent3r** [comment] 2020-10-19 17:11
I'll have a look if it appears again, thanks for the quick response

**Comment by jmoupah** [comment] 2020-10-27 16:26
Hello,

same here with VSCodium 1.50.1 and able to repro while not using Chrome : 
1. clone https://git.spip.net/spip-contrib-extensions/cvt_rechercher.git somewhere on your Windows 10 machine
2. open this repo in VSCodium 
3. clone https://git.spip.net/spip-contrib-extensions/responsivenav.git somewhere else on your Windows 10 machine
2. open this 2nd repo in another VSCodium
3. open the file prive\squelettes\contenu\configurer_responsivenav.html
4. TADAM !

Maybe it's something about windows access permissions to files/folders ?

**Comment by deepak1556** [comment] 2020-10-27 17:22
@jmoupah VSCodium is not vscode, they wouldn't have the runtime that contains the fix yet.

**Comment by jmoupah** [comment] 2020-10-28 09:38
Ok, thanks for your answer. 
Thing is, I don't see any issue on the repo https://github.com/VSCodium/vscodium/issues?q=is%3Aissue+debug.log
