### ISSUE TITLE
Syntax highlighting incorrect for C code within Markdown file

### ISSUE THREAD

**Issue by keck-in-space** [microsoft/vscode#92973] opened 2020-03-18 23:00 UTC
Issue Type: <b>Bug</b>

There seems to be an issue with correctly highlighting a C code block in Markdown files.

For example, if you have a markdown file like shown below, only the first #define is rendered correctly. The second #define is just rendered as if it were text and not code.

> # Example Markdown
> This is an example code block that fails to render correctly.
> ```c
> #define TRUE    (1U)
> #define FALSE   (0U)
> ```

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)

**Comment by keck-in-space** [comment] 2020-03-18 23:02
![image](https://user-images.githubusercontent.com/32853381/77015355-f361f100-694a-11ea-9804-d093d305a193.png)

**Comment by mjbvz** [comment] 2020-03-20 19:21
Duplicate of #34525

**Closed by mjbvz** 2020-03-20 19:21 UTC
Labels: new release
