### ISSUE TITLE
Trying to paste primary selection on replacement box instead pastes in editor

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#72189] opened 2019-04-12 07:22 UTC
1. Be on Linux
2. Press ctrl-f to open the search box
3. Press the arrow to open replacement
4. Middle click on the on the replacement text box to try to paste primary selection in it
5. The text is pasted into the editor instead

VSCode 1.33.0 on OpenSUSE Leap 15.0

**Comment by rebornix** [comment] 2020-11-05 19:57
I'm not able to reproduce this on Ubuntu now with latest VS Code. Closing it but we can reopen if anyone is still seeing it.

**Closed** 2020-11-05 19:58 UTC
Labels: editor-find, invalid, linux
