### ISSUE TITLE
Dropdown Menu - No arrows for items with sub-menu

### ISSUE THREAD

**Issue by nicolagranata** [microsoft/vscode#86989] opened 2019-12-14 13:14 UTC
![Annotazione 2019-12-14 141208](https://user-images.githubusercontent.com/49106793/70849241-fea10e80-1e7b-11ea-8ac5-41bef69dc40d.png)
Issue Type: <b>Bug</b>

Hello, the arrows indicating the presence of a sub-menu are missing (or better, they are moved beyond the visible area)

VS Code version: Code - Insiders 1.42.0-insider (cbeff45f80213db0ddda2183170281ed97ed3b12, 2019-12-13T07:08:57.560Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.91GB free)|
|Process Argv|D:\Lavori Nicola\Active\Siti\vscode-themes-master\.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.41.5
local-history|xyz|1.7.0

(4 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2019-12-14 19:26
Duplicate of https://github.com/microsoft/vscode/issues/86951

**Closed by RMacfarlane** 2019-12-14 19:26 UTC
Labels: integrated-terminal
