### ISSUE TITLE
Error HighLight on Variable name in ver:1.65.0

### ISSUE THREAD

**Issue by onlytherailgun** [microsoft/vscode#144676] opened 2022-03-08 12:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.0
- OS Version: Win10

Steps to Reproduce:

1. As pic show that,  Left is 1.65.0 , and Right is 1.64.2 , however , while mainColor changeing to blue from white, "QingMin2022" is a Variable name and it should be highlight, but in fact now vscode cannot recognize it ,
![POPO20220308-195825](https://user-images.githubusercontent.com/21358242/157234653-fa42ef4d-1c39-4d06-8a9c-377a9f6dec45.png)

**Comment by alexr00** [comment] 2022-03-09 09:38
@onlytherailgun can you share a copy/pastable example that I can use to reproduce the issue? Is this with C++?

**Comment by onlytherailgun** [comment] 2022-03-09 10:01
It's Lua.  @alexr00 , the example: 
`g_ItemDropMgr:SendItemWithCheck(EnumAddItemEvent.QingMin2022, self, 14500007, {BXJPlay_QingMingSet.FinalAccRewardItem.NumVal,1})`

**Comment by alexr00** [comment] 2022-03-09 10:14
Thank you! It looks like this is already fixed in our insiders build:

![image](https://user-images.githubusercontent.com/38270282/157420764-65a85708-0a36-4bd3-be65-363d6a8c6959.png)

The fix is available now in the insiders build, and it will be part of the 1.66 release.

**Closed by alexr00** 2022-03-09 10:14 UTC
