### ISSUE TITLE
Two finger scroll becomes laggy on Surface Book when one or more plug-in's are enabled

### ISSUE THREAD

**Issue by alanosman** [Microsoft/vscode#35844] opened 2017-10-08 19:53 UTC
I'm having a scroll-lag issue in Visual Code when using two-finger scrolling on a Surface Book (i7 model) when one or more plug in is enabled.  The more plug-ins I enabled, the greater the lag.   

The lag is seen when following these steps:

1. Scroll down some way in a large piece of code (say 200 lines)
2. Place two fingers at the lower side of the track pad
3. Slide two fingers up 
4. The Visual Code UI will not slide immediately
5. There is a lag and then the sliding begins and snap scrolls

The performance of two finger scroll on Chrome or Edge is far superior.  I searched the usual places on the internet to see if someone else had this issue, but it seems two-finger scrolling has had a number of issues over the years.  I have to rule out the device itself because it works perfectly in other apps that support smooth scrolling.

- VSCode Version: 1.17.0
- OS Version: Latest Windows 10 Preview build. 

Reproduces without extensions:  **No**  but any extension will slow it down.

**Comment by tommitytom** [comment] 2017-10-09 02:52
I have this issue and I've seen it mentioned in a few other issues.  One solution is to de-maximise, then re-maximise the window.  Not ideal but a workaround until it's fixed!

**Comment by alexandrudima** [comment] 2017-10-09 06:14
Duplicate of #13612

**Closed by alexandrudima** 2017-10-09 06:14 UTC
Labels: editor, editor-core, new release
