### ISSUE TITLE
Notebook: Hovers are cut off

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94100] opened 2020-04-01 01:23 UTC
See the screenshot:

![image](https://user-images.githubusercontent.com/4674940/78089574-b3ecc900-737c-11ea-8138-46825da282c9.png)

**Comment by rebornix** [comment] 2020-04-01 15:48
/duplicate of #93930 , let's track it there.

**Closed** 2020-04-01 15:49 UTC
Labels: *duplicate, notebook
