### ISSUE TITLE
JavaScript Missing Type Validation in 0.10.10

### ISSUE THREAD

**Issue by sghung** [Microsoft/vscode#4038] opened 2016-03-11 20:10 UTC
In 0.10.8, if I have a TypeScript Definition for a JavaScript file, there is validation done on the parameters. This was particularly useful for finding broken APIs.

Example of definition file and code:
![image](https://cloud.githubusercontent.com/assets/7843164/13714107/8da20336-e79a-11e5-87e5-8a3164caabec.png)

In 0.10.8, a warning is shown for an incorrect type:
![image](https://cloud.githubusercontent.com/assets/7843164/13714116/9f7416f8-e79a-11e5-9063-7b0ed08021f5.png)

Now, in 0.10.10, there is no validation at all. The "100" shows as being valid:

![image](https://cloud.githubusercontent.com/assets/7843164/13714176/0722b250-e79b-11e5-9cf5-c353ab67501c.png)

Losing the validation is a big loss. When switching to Salsa, was this the intention? Is there any properties that can be set to have the JavaScript intellisense + validation go back to the old engine (I believe it was using the TypeScript engine).

Thanks

**Comment by egamma** [comment] 2016-03-14 20:38
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/6802

**Closed by egamma** 2016-03-14 20:38 UTC
