### ISSUE TITLE
Seed the native file dialog with the parent of the currently active file

### ISSUE THREAD

**Issue by jayongg** [Microsoft/vscode#2615] opened 2016-02-01 16:36 UTC
Whenever I use "Open File", the box defaults from some default directory.  I would like the Open File dialog to show the directory that the current file is in.  99% of the time when I open a file it is to find some sibling file to the one I'm looking at.  

Either a user setting, or a completely new command would be great.

**Comment by bpasero** [comment] 2016-05-30 16:09
Duplicate of https://github.com/Microsoft/vscode/issues/1210

**Closed by bpasero** 2016-05-30 16:09 UTC
Labels: feature-request, files
