### ISSUE TITLE
Save All replaces contents of one dirty file with other dirty file

### ISSUE THREAD

**Issue by NigelJames14** [Microsoft/vscode#19356] opened 2017-01-25 12:24 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|react-toolbox-snippets|alechp|0.12.0|
|vscode-twig-pack|bajdzis|1.0.0|
|Aurelia|behzad88|1.2.1|
|compulim-vscode-closetag|Compulim|0.1.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.32|
|aurelia|ErikLieben|0.1.3|
|vsc-aurelia-cli|ErikLieben|0.0.2|
|vue-snippets|hollowtree|0.1.0|
|redux-snippets|jameshrisho|0.0.1|
|weex|jaylinwang|0.4.0|
|MeteorSnippets|jmlv|0.1.3|
|vue|liuji-jim|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|font-awesome-codes-html|medzhidov|0.0.4|
|vetur|octref|0.2.0|
|meteorhelper|ramonitor|0.1.3|
|vue|seanwash|0.4.2|
|html5-boilerplate|sidthesloth|1.0.1|
|react-beautify|taichi|0.3.0|
|html-preview-vscode|tht13|0.1.1|
|ReactSnippetsStandard|TimonVS|1.0.3|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.5|
|vscode-meteor|vuhrmeister|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|ReactSnippets|xabikos|1.2.0|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment] 2017-01-25 13:32
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by mousetraps** [comment] 2017-01-30 02:15
@NigelJames14 have you gotten a chance to try running with extensions disabled, as @bpasero suggested?

**Comment by lthompson-cartasite** [comment] 2017-02-08 18:46
I've noticed this as well while working on node.js code on OSX. Steps to reproduce: 
1) Open one file, edit it
2) Open second file, edit it
3) click first file on the navigation tab
4) click File->Save All from the menu

Code from file 2 will replace code in file 1

The code that is replaced is not identical to the code in file 1, which may indicate that the built-in git extension may be involved. The last time this happened I was working on a POC app and had not yet initialized the git repo for the app.

**Comment by bpasero** [comment] 2017-02-08 18:47
@lthompson-cartasite 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by lthompson-cartasite** [comment] 2017-02-08 18:56
@bpasero It is entirely possible. If I get time I'll do that if I get time, but it is an intermittent bug and I am not particularly interested in selectively re-enabling a extensions and waiting for the bug to occur while trying to write production code. My enabled extensions are: johnpapa.Angular1, t-sauer.autolinting-for-javascript, iZDT.javascript-unit-test-snippet, lonefy.vscode-JS-CSS-HTML-formatter, yzane.markdown-pdf. Perhaps one of these coincides with an extension used by the original poster.

**Comment by lthompson-cartasite** [comment] 2017-02-08 20:40
It happened a bit differently this time. In a project with two files: test.js and client-api.js. 

1) launch the debugger from test.js
2) execution stops with an exception in client-api.js
3) click the stop button (red square) n the debugger menu bar
4) edit the code in client-api.js, but did not save the code
5) click the test.js tab in the editor
6) press the start button on the debug menu (green arrow)
7) the entire contents of client-api.js replaces the code in test.js and then test.js executes.

No git repository. No extensions enabled. Using the default launch.json. The debugger panel was selected the entire time on the left-side menu.

**Comment by twhiting** [comment] 2017-02-08 23:06
Casually reading through issues, I've seen something similar to this in another electron project (boostnote). (meaning it might be electron itself?)  Perhaps look there if you guys are stumped by this.  Could be way off but thought I'd chime in.

**Comment by bpasero** [comment] 2017-02-09 06:16
@lthompson-cartasite are you able to somehow record your bug as a video for me to see how this behaves? How did you run with "no extensions enabled"?

**Comment by NigelJames14** [comment] 2017-02-09 12:08
Hi, yes I did try with extensions disabled and the saving error never occurred but it was only for one session and it was not a problem that is constant so I do not know if it was an issue with an extension or just got lucky and the problem did not occur at that time. I use different IDE’s and editors so I am not constantly using VS Code.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bpasero** [comment] 2017-02-09 13:57
@lthompson-cartasite can you share this setup with me (those 2 files), I would like to reproduce.

**Comment by lthompson-cartasite** [comment] 2017-02-09 17:24
I just updated to 1.9 and was not able to trigger it immediately. I'll continue as I did yesterday and see if it repeats. As I said, it is an intermittent bug but it happened a few times an hour yesterday. I disabled the extensions from the extensions menu by clicking each one individually (I know this isn't identical to running with the command-line switch, but it ought to be close). If I can get it to repeat I'll share code snippets and a screen capture. If not, it might have been a side-effect of something that was fixed in 1.9.

**Comment by lthompson-cartasite** [comment] 2017-02-09 19:19
It just happened again, and this time I think I have it narrowed down pretty precisely. I had three files open in a project, all of which had edits. When I used the keyboard shortcut for Save All, the code in my current document was replaced with the code in my last-visited document. I can now use Redo/Undo and watch the code swap back and forth from what is supposed to be there and what is in the last-edited file. Given that Save All gets triggered when you start the debugger with unsaved files, I think this may be the real source of the error.

**Comment by bpasero** [comment] 2017-02-10 07:43
@lthompson-cartasite @bunditng see here how I try to reproduce but I cannot, please let me know if you do things differently:

![kapture 2017-02-10 at 8 41 04](https://cloud.githubusercontent.com/assets/900690/22818299/d510bbd8-ef6c-11e6-8829-c68f2c8d3607.gif)

Also can you maybe share your VS Code settings with me? I wonder if there is something.

And to be clear, please always try with `code --disable-extensions` so that we can rule out bad behaving extensions 👍

**Comment by lthompson-cartasite** [comment] 2017-02-10 18:06
As I indicated, this is an intermittent bug, but once it occurs the first time it is repeatable. I launched the app from the terminal with the following command: open -a "Visual Studio Code" --args --disable-extensions. It took a while before it appeared, but I could repeat it as often as necessary once it started to happen. It only happens with Save All, not if I use Save for each file. I used the menu for the video to make it clear exactly what I was doing, but it works exactly the same way if you use the menu accelerator keys. 

Here's the video:
![saveall vscode bug](https://cloud.githubusercontent.com/assets/19983426/22838064/95bee3d8-ef80-11e6-923a-8e3dfc014073.gif)

There is nothing fancy about my config. This is a POC JavaScript API for a REST service, it consists of one module and one test file. The launch.json was autogenerated, the only change I made was to set the startup file for the debugger. The bug was present both before and after I created the launch.json file. Hope this helps.

**Comment by bpasero** [comment] 2017-02-11 07:55
@lthompson-cartasite crazy stuff, I tried to reproduce for 10 minutes, I cannot. Two things:
* can you share your settings file with me (both your global settings.json as well as the contents of all files inside .vscode folder
* can you share this workspace with me? maybe it is somehow related to the contents

**Comment by bunditng** [comment] 2017-02-11 09:09
sorry, late answer. this from normal start. 
![ezgif com-0601a7f1f4](https://cloud.githubusercontent.com/assets/5108850/22852661/5eb0269c-f073-11e6-8cab-03c6cea051c1.gif)

**Comment by bunditng** [comment] 2017-02-11 09:22
and after try start with arg. for disable extensions. got this
![ezgif com-02fb579bf5](https://cloud.githubusercontent.com/assets/5108850/22852757/dd1eeb10-f075-11e6-9a0c-9953d782af19.gif)


i think it cause form some extensions. work when saving content of file like Formatter

**Comment by bpasero** [comment] 2017-02-19 08:39
@bunditng yes for you it looks like an extension is causing this. 

@lthompson-cartasite can you show me a screenshot of the "Extensions" view when you are able to reproduce this?

**Comment by bpasero** [comment] 2017-03-10 05:23
https://github.com/Microsoft/vscode/issues/22330

**Closed by bpasero** 2017-03-10 05:23 UTC
Labels: needs more info
