### ISSUE TITLE
new `markdown.experimental.validate.*` settings don't honor each other

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#151895] opened 2022-06-12 19:18 UTC
Issue Type: <b>Bug</b>

I have the following VSCode settings in my Obsidian folder, because Obsidian uses a headerlink format that's not compatible with VSCode (or anything else... but I like their Sync feature)... if I have a file link that's valid, but has a header link tacked onto the end of it, it gives an error for invalid header link even though those are set to ignore

``` json
{
    "markdown.experimental.validate.enabled": true,
    "markdown.experimental.validate.fileLinks.enabled": "error",
    "markdown.experimental.validate.headerLinks.enabled": "ignore",
}
```

![image](https://user-images.githubusercontent.com/849948/173249748-07025277-2344-4f4d-b1e3-01665bd00029.png)

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (19.03GB free)|
|Process Argv|--file-uri file:///c%3A/src/AF4JM.code-workspace --crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
case-change|Aka|1.0.2
rtf|ale|2.5.0
spellright|ban|3.0.64
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.14.0
markdown-yaml-preamble|bie|0.1.0
vscode-tldr|bmu|1.0.0
mermaid-markdown-syntax-highlighting|bpr|1.2.3
npm-intellisense|chr|1.4.2
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.47.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.19
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.25
vscode-macros|EXC|1.4.0
vscode-npm|fkn|3.3.0
shell-format|fox|7.2.2
macros|ged|1.2.1
matlab|Gim|2.3.1
gc-excelviewer|Gra|4.2.54
vscode-favorites|how|1.10.2
rest-client|hum|0.24.6
path-autocomplete|ion|1.19.1
mediawiki|jak|2.1.0
anki|jas|1.2.6
markdown-katex|jef|0.1.4
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscode-peacock|joh|4.0.1
gpg|jva|0.1.2
docomment|k--|0.1.31
markdown-shortcuts|mdi|0.12.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.205.0
vscode-azureappservice|ms-|0.24.2
vscode-azureresourcegroups|ms-|0.5.3
vscode-azurestorage|ms-|0.14.1
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
azure-account|ms-|0.10.1
powershell|ms-|2022.5.1
vscode-node-azure-pack|ms-|0.3.0
bib|phr|0.3.0
vscode-yaml|red|1.8.0
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
addDocComments|ste|0.0.8
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.21
vscode-icons|vsc|11.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment] 2022-06-13 15:25
Duplicate of #150949

**Closed by mjbvz** 2022-06-13 15:25 UTC
