### ISSUE TITLE
Follow link resolution for sass does not respect existing files

### ISSUE THREAD

**Issue by joneff** [microsoft/vscode#77464] opened 2019-07-16 10:18 UTC
- VSCode Version: 1.36.1
- OS Version: Windows 10

Steps to Reproduce:

1. create three files `main.scss` and `_partial.scss` `file.scss`
2. add `@import _partial.scss` in `main.scss`
3. add `@import file.scss` in `main.scss`
4. click hover any of the `@import` lines and try to follow link.

Expected result is to go correct locations, how ever:

* `_partial.scss` will look for `__partial.scss`
* `file.scss` will look for `_file.scss`

![image](https://user-images.githubusercontent.com/8048/61284324-649f4200-a7c7-11e9-8681-a34c818d0216.png)

Follow link sass file resolution should respect sass import resolution:

### `@import "file"`
* look for `file.scss`, if not found
* look for `file.sass`, if not found
* look for `file.css`, if not found
* look for `_file.scss`, if not found
* look for `_file.sass`, if not found
* look for `file/_index.scss` (as per dart-sass), if not found
* look for `file/_index.sass` (as per dart-sass), if not found
* show current error message
  * note: since it's not clear what type was needed to be created, perhaps a multi option interface should be shown with `_file.scss` being the default option, probably

### `@import "_file"`
* look for `_file.scss`, if not found
* look for `_file.sass`, if not found
* look for `_file.css`, if not found
* look for `_file/_index.scss` (as per dart-sass), if not found
* look for `_file/_index.sass` (as per dart-sass), if not found
* show error message with multi option interface

### `@import "file.scss"`
* look for `file.scss`, if not found
* look for `_file.scss`, if not found
* probably not look for `file.scss/_index.scss`,
* probably not look for `file.scss/_index.sass`,
* show current error message

Note: `@import "file.sass"` -- works the same like above, with `sass` extension.

### `@import "file.css"`
* look for `file.css`, if not found
* probably not look for `file.css/_index.scss`,
* probably not look for `file.css/_index.sass`,
* show current error message

### `@import "_file.scss"`
* look for `_file.scss`, if not found
* probably not look for `_file.scss/_index.scss`,
* probably not look for `_file.scss/_index.sass`,
* show current error message

Note: `@import "_file.sass"` -- works the same like above, with `sass` extension.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment] 2019-07-17 17:57
Duplicate of #58204. You can test the fix in tomorrow's Insider release.

**Closed** 2019-07-17 17:56 UTC
Labels: *duplicate
