### ISSUE TITLE
High memory usage on local machine when flushing a large number of characters to screen

### ISSUE THREAD

**Issue by Bobholamovic** [microsoft/vscode#112759] opened 2020-12-01 10:37 UTC
Issue Type: <b>Performance Issue</b>

Just one step to reproduce it:

```bash
base64 /dev/urandom
```

And you'll see the memory usage of VSCode on the local machine surges, until the program stops working.

Does this have anything to do with a local screen buffer?

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-74-generic

**Comment by meganrogge** [comment] 2020-12-17 18:37
Duplicate of #111562

**Closed** 2020-12-17 18:37 UTC
Labels: *duplicate, bug, integrated-terminal
