### ISSUE TITLE
Terminal scrolls content to the left without a reliable way of recovering

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#6846] opened 2016-05-24 23:59 UTC
OS: Windows

1) open the built-in terminal 
2) run command that produces a bunch of output such as 'npm list' or cat a file
3) try to scroll up to reveal text that was already scrolled out of sight
-> content is scrolled to the left (and then gets stuck)
-> there is no reliable way to get the terminal back into a 'normal' state; sometime Enter works, sometimes not

Here is a [screen recording](https://www.dropbox.com/s/y0x7m77ys8xne3v/scroll-issue.mov?dl=0).

**Comment by Tyriar** [comment] 2016-05-25 02:29
Duplicate of #6738

**Closed by Tyriar** 2016-05-25 02:29 UTC
Labels: bug, integrated-terminal
