### ISSUE TITLE
Preserve custom command line in /usr/share/applications/code.desktop

### ISSUE THREAD

**Issue by ryanlederman** [Microsoft/vscode#58635] opened 2018-09-13 20:32 UTC
Every time I upgrade, I have to manually edit `/usr/share/applications/code.desktop` to restore the `--disable-gpu` argument in the `Exec=` line.

I run VS Code in a VM, so it performs much better with that option. I imagine this is a rather common use case, so I would suggest to **not overwrite the exec line, but rather do a merge** with it.

**Comment by joaomoreno** [comment] 2018-09-14 06:48
@bpasero Any chance we can have another way of disabling gpu by default on the user's settings? I know it needs to come in very early... but maybe the main can set it before any renderers come up? If so, I propose we bring back that `argv` file in the user-data-dir which just contains command line arguments to append on startup.

**Comment by bpasero** [comment] 2018-09-14 06:53
Duplicate of https://github.com/Microsoft/vscode/issues/15211

@joaomoreno this has to be set before app.on("ready"), setting it before a renderer starts is not sufficient as far as I know.

@ryanlederman also see my comment there (https://github.com/Microsoft/vscode/issues/15211#issuecomment-421003607)

**Closed by bpasero** 2018-09-14 06:53 UTC
