### ISSUE TITLE
Allow first letter navigation in trees

### ISSUE THREAD

**Issue by Neurrone** [Microsoft/vscode#41405] opened 2018-01-10 14:57 UTC
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (2bab83a097135cf8c2a1ca1498bb8906f06d2cb3, 2018-01-10T05:13:51.946Z)</li>
	<li>OS Version: Windows_NT x64 10.0.15063</li>
	<li><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.1
vscode-rust|kal|0.4.2
rust|rus|0.3.2
markdown-preview-enhanced|shd|0.3.2

</details></li>
</ul>

Steps to Reproduce:

1. Open a folder of files.
2. Ctrl+shift+E to move focus to the explorer tree view. First letter navigation doesn't work.

**Comment by Tyriar** [comment] 2018-01-14 05:10
I believe we can close this off as a duplicate of https://github.com/Microsoft/vscode/issues/10026

**Closed** 2018-01-14 15:14 UTC
Labels: feature-request, insiders, tree
