### ISSUE TITLE
Allow a config option to change default line sequence (CRLF and LF)

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#3337] opened 2016-02-23 14:46 UTC
Unless I am missing an existing configuration option (searched through the default settings, nothing jumped out at me), VS Code will always default to CRLF (at least on Windows).

For developers targeting cross platform (particularly with publishing packages to npm, for example) it would be nice to be able to set a user setting to default to LF instead of CRLF (or vice versa for other scenarios).

**Comment by egamma** [comment] 2016-02-23 14:49
Closing as a duplicate of #2957

**Closed by egamma** 2016-02-23 14:49 UTC

**Comment by tstringer** [comment] 2016-02-23 16:12
@egamma thanks for the administration of this, and apologies for not seeing that issue before opening this one!

**Comment by egamma** [comment] 2016-02-23 16:19
No need to apologize, if in doubt pls file an issue. This is indeed an important one.
