### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by hongsefb** [microsoft/vscode#95864] opened 2020-04-22 11:25 UTC
Issue Type: <b>Bug</b>

The preference icon in File option is not correct. It should be >, not √.
![image](https://user-images.githubusercontent.com/29223722/79976544-6113b680-84cf-11ea-8af8-45028b3361fb.png)

VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:44:55.510Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment] 2020-04-22 12:16
Actually duplicate of #95838

**Closed** 2020-04-22 14:12 UTC
Labels: *duplicate
