### ISSUE TITLE
Add more extension-point to support more rich editor (types).

### ISSUE THREAD

**Issue by Dollyn** [Microsoft/vscode#12212] opened 2016-09-18 09:45 UTC
Text editor is not enough for all. It will be much better if plugins could add more 'rich' editors, just like the extension editor.

**Comment by bpasero** [comment] 2016-09-19 05:13
@jrieken @Tyriar fyi

**Comment by jrieken** [comment] 2016-09-19 08:39
dupe of #12176

**Closed by jrieken** 2016-09-19 08:39 UTC
Labels: api, feature-request
