### ISSUE TITLE
Webview stopped working with local files included in an iframe using localResourceRoots

### ISSUE THREAD

**Issue by pbaksa** [microsoft/vscode#123766] opened 2021-05-13 09:33 UTC
Issue Type: <b>Bug</b>

With VSCode 1.56.1 update, my extension can't display local (included in extension) html files in a webview. This is the text in the iframe where the html should appear:
ResourceNotFoundThe specified resource does not exist. RequestId:d2d6507d-001e-0029-2dd8-477c48000000 Time:2021-05-13T09:16:59.8441377Z

It worked in 1.55

my code:
```
this.refguideView = vscode.window.createWebviewPanel(
            'refguide',
            'GDL reference guide',
            {   preserveFocus: true,
                viewColumn: vscode.ViewColumn.Beside
            },
            {
                enableFindWidget: true,
                enableScripts: true,
                enableCommandUris: true,
                localResourceRoots: [ vscode.Uri.file(root) ]
            });

this.refguideView.webview.html = RefGuide.refguideHtml(this.refguideView.webview.asWebviewUri(furi));

private static refguideHtml(url: vscode.Uri) : string {
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <title>Redirecting...</title>
</head>
<body scrolling="no" style="padding: 0px;">
    <div scrolling="no" style="background-color:#ffffff; display: flex; flex-direction: column; width: 100vw; height: 100vh; overflow: hidden">
        <nav style="margin: auto; width: fit-content; height: fit-content; padding-top: 10px; padding-bottom: 10px;">
            <a href="#" onclick="history.back()" style="margin-right: 10px; text-decoration: none;">Back</a>
            <a href="#" onclick="history.forward()" style="margin-left: 10px; text-decoration: none;">Forward</a>
        </nav>
        <hr/>
        <iframe src="${url}" frameborder="0" sandbox="allow-scripts allow-same-origin" scrolling="yes" style="flex-grow: 1; width: 100%; height: 100%;"></iframe>
    </div>
</body>
</html>`;
    }
```

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|30.91GB (14.01GB free)|
|Process Argv|c:\\Dev\\BPet-AAAP-Whiskey\\Sources\\LibPackages\\Tools\\conversion_tools\\buildandrevert.bat --crash-reporter-id beeacb82-76dc-4358-bba1-7d7debef436f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|13.0.4
alignment|ann|0.3.0
close-all|ben|1.0.2
docs-view|bie|0.0.9
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.21
vscode-npm|fkn|3.3.0
formatdump|pba|0.0.4
gdl|Gra|1.25.159
markdown-viewer|jul|1.0.0
private-extension-manager|jul|1.4.8
guid|kos|0.0.1
vs-color-picker|lih|1.0.0
rainbow-csv|mec|1.8.1
vscode-antlr4|mik|2.2.4
perforce|mjc|4.15.2
perl-debug|mor|0.6.3
language-gettext|mro|0.2.0
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
hexeditor|ms-|1.6.0
printcode|nob|3.0.0
relativegoto|ret|0.0.1
vscode-todo-highlight|way|1.0.4
goto-line-ex|xyz|0.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301300

```

</details>

**Comment by pbaksa** [comment] 2021-05-13 09:50
The iframe tag viewed with Webview Developer Tools is:
<iframe src="https://612ea885-6fe7-4b9c-8415-069df9b14a2f.vscode-webview-test.com/vscode-resource/file///c%3A/Users/pbaksa/.vscode/extensions/graphisoft.gdl-1.25.159/VSCodeRef/reference/TUBE2.html" frameborder="0" sandbox="allow-scripts allow-same-origin" scrolling="yes" style="flex-grow: 1; width: 100%; height: 100%;"></iframe>

**Comment by mjbvz** [comment] 2021-05-13 16:41
Duplicate of #121479. We no longer support loading iframes from disk on desktop (and have never supported this case on the web

Iframes in webview can cause other issues too so try to avoid using them, especially if just loading html from disk

**Closed by mjbvz** 2021-05-13 16:41 UTC
