### ISSUE TITLE
Webview resources not loading - ERR_UNKNOWN_URL_SCHEME (vscode-insiders)

### ISSUE THREAD

**Issue by mhutchie** [microsoft/vscode#100918] opened 2020-06-24 08:59 UTC
- Version: 1.47.0-insider (user setup)
- Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
- Date: 2020-06-23T09:03:35.861Z
- Electron: 8.3.3
- Chrome: 80.0.3987.165
- Node.js: 12.13.0
- V8: 8.0.426.27-electron.0
- OS: Windows_NT x64 10.0.18362

I'm the author of the [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph#overview) extension. This bug is affecting all Git Graph users that use Visual Studio Code Insiders, as well as every other extension I'm aware of that loads resources (e.g. CSS, JS) in Webview's _(more specifically, resources loaded by `Webview.asWebviewUri`)_. I can replicate bug on Windows & Mac, I've had reports of this from many users.

Steps to Reproduce:
1. Install an extension that uses a Webview (Git Graph for the following steps)
2. Open Visual Studio Code in a Git repository.
3. Click the "Git Graph" Status Bar Item
4. Observe that the CSS & JS resources aren't loaded:
![image](https://user-images.githubusercontent.com/5315753/85524174-3e2a8d80-b64b-11ea-88ed-a1e027f11389.png)
5. If you run the Visual Studio Code command "Open Webview Developer Tools", the following errors can be seen:
![image](https://user-images.githubusercontent.com/5315753/85524358-7205b300-b64b-11ea-8223-9132665a8eba.png)

Does this issue occur when all extensions are disabled?: No (Because it only affects extensions that use Webview's)

The resolution of this issue is being tracked for Git Graph users [here](https://github.com/mhutchie/vscode-git-graph/issues/317).

**Comment by mhutchie** [comment] 2020-06-24 09:02
Looping in @mjbvz.

**Comment by lafe** [comment] 2020-06-24 09:28
This might also cause an issue with the [Draw.io plugin](https://github.com/hediet/vscode-drawio) which does not work anymore after updating to the current Insiders version (same version as posted by @mhutchie).

**Comment by iwittkau** [comment] 2020-06-24 09:55
I also see this issue in the Insiders build with markdown preview and with the extension [Project Dashboard](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard).

**Comment by cmendible** [comment] 2020-06-24 11:21
This is also affecting [Device Simultor Express](https://www.microsoft.com/en-us/garage/profiles/device-simulator-express/)

**Comment by mjbvz** [comment] 2020-06-24 17:41
Duplicate of #100879. Should be fixed in the next insiders build

**Closed by mjbvz** 2020-06-24 17:41 UTC
Labels: freeze-slow-crash-leak

**Comment by lafe** [comment] 2020-06-26 06:24
The [Draw.io Plug-in](https://github.com/hediet/vscode-drawio) works again. Thanks for the fix, @mjbvz!

**Comment by mhutchie** [comment] 2020-06-26 07:37
@mjbvz I've had reports that this was fixed in the Insiders release 9b620b2, however it is broken again for every user I've checked with in:

Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

How could this occur again?
