### ISSUE TITLE
Add file rename and move commands to the command palette

### ISSUE THREAD

**Issue by wesbos** [microsoft/vscode#108809] opened 2020-10-16 15:26 UTC
The move / rename commands in the sidebar are super handy because they update import paths in JS and TS projects.

These commands aren't part of the command palette and make me break my workflow / reach for the mouse.

Could we get these commands in the command palette too? I currently use the "file utils" extension to do this, but they don't seem to update import paths like VS Code rename/move commands do.

**Comment by yume-chan** [comment] 2020-10-16 16:33
Duplicate of #100591 where Code team said it won't happen

**Comment by isidorn** [comment] 2020-10-22 10:31
We can add the rename file to the command pallete. I guess you would expect that to be executed on the currently active editor. So the command would -> open sidebar -> reveal currently active editor and show the input box

Move command does not make that much sense to be in the command palette imho, since we call it Cut in the explorer, and Cut already lives in the command pallete (since it is a text cut in the editor).

Both these commands have keyboard shortcuts so I am not sure why are you reaching for the mouse.
Cmd + shit + e to show explorer, focus should be on the active editor. F2 or enter to rename. Ctrl / cmd + X to Cut.

**Closed** 2021-02-10 11:30 UTC
Labels: file-explorer, needs more info, under-discussion
