### ISSUE TITLE
Issues on SAVE

### ISSUE THREAD

**Issue by jromier** [Microsoft/vscode#10959] opened 2016-08-25 14:53 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows 8.1 x64

From at least two releases of Visual Studio Code, I have issues with the SAVE menu item.
I generally work with several tabs opened and when I save the file of the current tab, the tab title still blinking, and the save is not done while I'm not selecting another tab.
But most of the time, the content of the saved tab is copied on the new displayed tab. 
There is a second issue : if by mistake, I also do save in the new tab (after the content has been changed or replaced) the 'undo' precess doesn't works!

Steps to Reproduce:

1. modify the code ot the selected tab
2. Do save -> tab title is blinking
3. Go to another tab -> the file of the previous tab is saved
4. The content of the saved tab is copied into the new current tab.

**Comment by bpasero** [comment] 2016-08-26 06:23
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-08-30 09:15
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by jromier** [comment] 2016-09-09 06:30
Sorry, I haven't yet read your answer.
I'll try your suggestion asap and give you a feedback.
Thanks for your support

**Comment by jromier** [comment] 2016-09-09 15:27
Well I typed the command 'code --disable-extensions' in the VS Code terminal, but nothing changed.
Do you think I should uninstall all my extensions for a test?

**Comment by bpasero** [comment] 2016-09-09 17:20
@jromier so you say the issue is still there when you run with extensions disabled? what extensions do you have installed?

**Comment by jromier** [comment] 2016-09-12 13:01
Hello,

Please, see the attached file for the extensions I use in VS Code.
For complete information, I'm working with typeScript in an angular2 project.
Other precision: issue comes aonly with HTML and CSS files.
Thanks again

![vscode-extensions](https://cloud.githubusercontent.com/assets/21243495/18436555/4c3299d8-78f9-11e6-89f2-da9cb8fab0db.png)

**Comment by jromier** [comment] 2016-09-12 14:29
OK thanks,
I've downloaded your last insiders release and I try to test it in a few hours.
I'll give you my feedback then.

**Comment by jromier** [comment] 2016-09-12 17:18
I have the same behavior with the insider version of VS Code :-(

**Comment by bpasero** [comment] 2016-09-12 17:51
@jromier wow, bad. any chance you can attach a video how this looks like and is triggered?

**Comment by jromier** [comment] 2016-09-14 09:00
Well, following your idea and the fact I only had issues with CSS and HTML files, I uninstalled 2 extensions: 'Close HTML/XML tag' and 'JS-CSS-HTML Formatter' and my issue disapeared.

So it's one of these 2 extensions that gives the issue I had.
I'll try to reinstall one for find the true guilty.

Thanks again for your support

**Comment by bpasero** [comment] 2016-09-14 09:13
@jromier how is that possible given I asked you to run "code --disable-extensions"?

**Closed by bpasero** 2016-09-14 09:13 UTC
Labels: needs more info
