### ISSUE TITLE
vscode sends two stackTraceRequest(s) to debug adaptor.

### ISSUE THREAD

**Issue by paulo-fernando-silva** [Microsoft/vscode#62908] opened 2018-11-11 02:26 UTC
- VSCode Version: 1.28.2
- OS Version: MacOS 10.13.6

I was trying out the vanilla Mock Debug extension and I noticed that  vscode sends two stackTraceRequest in sequence. Why?
I don't see a way to distinguish between the two requests, so I'm imagining this is more of a bug. I'm just surprised that no one noticed before.

Steps to Reproduce:
- download Mock Debug from: https://github.com/Microsoft/vscode-mock-debug.git
- Set a breakpoint in stackTraceRequest and run it on any file.
- When it stops on breakpoint, press F5 and notice how it'll receive another stackTraceRequest.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2018-11-11 17:15
VS Code sends two (or more) requests on purpose. The first request asks for the first stackframe and the total number of frames. The next asks for then next n frames starting with the second frame. Typical n is 19 so that in total 20 frames are initial shown. If there are more than 20 frames, VS Code will show a "More Frames" button.

**Comment by isidorn** [comment] 2018-11-12 09:28
@weinand thanks for providing the explanation.
@paulo-fernando-silva The way to distuingish between these requests are the `startFrame` and `levels` attributes. https://github.com/Microsoft/vscode/blob/76ee724e18353c93b2cc8eca92de5edd848b05ff/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L729

Closing as designed.

**Closed by isidorn** 2018-11-12 09:28 UTC
Labels: debug

**Comment by paulo-fernando-silva** [comment] 2018-11-12 14:06
Makes sense, but I'm getting two requests as follows:
```
To client: {"seq":0,"type":"response","request_seq":7,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"thread 1"}]}}
logger.ts:150
From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
logger.ts:150
From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
```
That's why I thought it was strange because the requests are indistinguishable.
So it's only natural I thought it was a bug...

**Comment by isidorn** [comment] 2018-11-13 10:45
@paulo-fernando-silva I tried to reproduce your issue by changing nodeDebug to not suppor delayed stack trace loading and I could not.
Only one stack trace is being sent out.

If you would like to dig deepere, please F1 > developer tools > wait a bit and open `rawDebugSession.ts` and put a breakpoint [here](https://github.com/Microsoft/vscode/blob/1df80b25cc7ddfa372f34f4332e16699a31ab4ff/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L351)
And check if the `stackTrace` is indeed sent twice as you are saying and try to find the reason why that is so by looking at the callers.
Thanks!

**Comment by paulo-fernando-silva** [comment] 2018-11-13 16:30
Here's what I catch if I set a breakpoing there and hit continue every time:
```
args = {threadId: 1, startFrame: 0, levels: 1}
args = {threadId: 1, startFrame: 1, levels: 19}
From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
args = {threadId: 1, startFrame: 0, levels: 1}
args = {threadId: 1, startFrame: 1, levels: 19}
From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
From client: scopes({"frameId":0})
```
The "From Client" are actually printed on the console.
Still not sure why the four stack requests get translated into two, but my guess is that maybe it's summing the levels? Not sure what's going on here. But it doesn't seem to be an issue anyway, so I guess we can ignore it until it starts to actually be an issue.

**Comment by isidorn** [comment] 2018-11-13 17:08
MIght it be that the `"From client"` you are loging in your extension?  This should not come from vscode. Do you maybe have some weird extension installed?
If I ignore the `From client` logging the `args` looks quite good.
Are you sure your extensions is setting [`supportsDelayedStackTraceLoading`](https://github.com/Microsoft/vscode/blob/b4c6906b62e3199eee87c17649979939a4e43323/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1190) to `false`

**Comment by paulo-fernando-silva** [comment] 2018-11-14 13:44
The "From Client" is output from the logger in the extension. The extension that I'm trying is the [vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug), which seems to be the sample provided by the vscode project in the documentation [here](https://code.visualstudio.com/docs/extensionAPI/api-debugging).
Adding `response.body.supportsDelayedStackTraceLoading = false;` in that project doesn't change this behavior. It still receives two stackRequests as before.
