### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by drsparksMS** [microsoft/vscode#149189] opened 2022-05-10 21:20 UTC
Issue Type: <b>Bug</b>

When I restart to update VS Code, I get the following error:
"There was an error while Opening file handle:
'C:\\Users\\<xxxx>\\AppData\\Local\Programs\\Microsoft VS Code\\bin\\code'
Failed to create file handle: Access is denied."

I've rebooted a few times and the error persists.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22616
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|45.73GB (37.10GB free)|
|Process Argv|--crash-reporter-id 2c86a73a-98df-4fda-a3a4-64957ac06622|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
gitlens|eam|12.0.6
terraform|has|2.22.0
theme-monokai-pro-vscode|mon|1.1.20
azure-pipelines|ms-|1.205.0
vscode-azureappservice|ms-|0.23.3
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.6.1
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.22.0
vscode-dotnet-runtime|ms-|1.5.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
powershell-preview|ms-|2022.5.1
vscode-node-azure-pack|ms-|0.3.0
azurerm-vscode-tools|msa|0.15.6
vetur|oct|0.35.0
material-theme|zhu|3.13.25

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by drsparksMS** [comment] 2022-05-10 21:21
[vscode-inno-updater-1652217128.log](https://github.com/microsoft/vscode/files/8665063/vscode-inno-updater-1652217128.log)
![Screenshot 2022-05-10 142115](https://user-images.githubusercontent.com/49798379/167724001-f9fe18f6-1e08-49a7-8982-115b1fd22822.jpg)

**Comment by drsparksMS** [comment] 2022-05-10 21:29
If I try to install over the current version:


![Screenshot 2022-05-10 142805](https://user-images.githubusercontent.com/49798379/167725058-14c4e12b-6ad2-4112-a60e-31bde5da3acd.jpg)

**Comment by OtherShadeOfBlue** [comment] 2022-05-11 11:27
I observed the exact same and reported it in #149248
My guess was it was caused by an earlier elevated vscode session update.
Was able to workaround by taking ownership of the files/folders in AppData\Local\Programs\Microsoft VS Code

**Comment by ealap** [comment] 2022-05-12 15:01
Experiencing the same issue on Win11, though I have never run any VSCode instance in elevated mode. The workaround to take ownership of the whole VSCode installation folder does work.

**Comment by drsparksMS** [comment] 2022-05-12 20:28
Interesting...when I opened permissions on AppData\Local\Programs\Microsoft VS Code and noted that my account had nothing checked.  Trying to grant my account Full Control gave me this error:

![Screenshot 2022-05-12 132717](https://user-images.githubusercontent.com/49798379/168162341-09ed10a7-cf0b-4aff-af8e-9ecda6d9f770.jpg)

**Comment by Big2thaE** [comment] 2022-05-18 19:37
Opening it escalated fixed the issue for me.

**Comment by joaomoreno** [comment] 2022-05-20 13:27
Duplicate of https://github.com/microsoft/vscode/issues/147408

**Closed by joaomoreno** 2022-05-20 13:27 UTC
