### ISSUE TITLE
DiagnosticCollection does not scale well and blocks UI thread

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/vscode#11976] opened 2016-09-13 18:44 UTC
- VSCode Version: 1.5.2
- OS Version: Tested Windows 10 and macOS 10.11

Repro steps:
1. Clone https://github.com/DustinCampbell/diagnostic-perf-test
2. Open the diagnostic-perf-test project in VS Code
3. F5 to compile and launch the extension under the debugger
4. In the debuggee process, select `View->Problems` to display the Problems pane.
5. In the debuggee process, select `View->Command Palette...` and execute the `Populate Diagnostics` command.

At this point, the VS Code debuggee window will stop responding as it populates a single diagnostic for 2000 files. This is very similar to the diagnostics produced for a medium- to large-sized C# solution (say, one generated by Unity) where there are a couple thousand files and each has a single "remove unnecessary using directives" diagnostic.

Expected result:
* Populating diagnostics should not scale exponentially by the number of files.
* Calling `DiagnosticCollection.set(...)` should periodically free up the UI thread while processing.

**Comment by jrieken** [comment] 2016-09-19 09:54
The problem is that we call [`changeOne`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/markers.ts#L19) per uri+owner combination which leads to many events. Processing those events (problems view) takes a long time. We should not fire so many events...


[CPU-20160919T115033.cpuprofile.zip](https://github.com/Microsoft/vscode/files/479685/CPU-20160919T115033.cpuprofile.zip)

![screen shot 2016-09-19 at 11 54 19](https://cloud.githubusercontent.com/assets/1794099/18628287/d269c0d8-7e5f-11e6-9d8c-9eb2d63498a7.png)

**Comment by jrieken** [comment] 2016-09-19 11:55
We have found a couple of issues

* [ ] event storm by emitting in the loop
* [ ] the problems view sorting and filtering *all* elements

**Comment by jrieken** [comment] 2016-09-19 13:23
@sandy081 I have pushed changes to send all events at once and to make reading of marker a little faster. that improves the situation a tiny bit. as discussed the culprit is the problems view. pls continue from here

**Comment by sandy081** [comment] 2016-09-19 17:05
Thanks @jrieken for the changes. I will do the improvement is problems view as discussed.

**Comment by sandy081** [comment] 2016-09-20 17:35
Root cause: Problems model is getting update resource by resource and every time it is being refreshed (filtered and sorted). So this is doing filtering and sorting as many times as the number of resources (in this case 2000). Fixed it by doing bulk update / refresh.

Also did some optimisations in the model for better performance. After all this, amount of time came down from **20s** to **1s**

Attaching the pre-fix and post-fix profiles here

![screen shot 2016-09-20 at 18 39 18](https://cloud.githubusercontent.com/assets/10746682/18681590/0dbcbb7c-7f69-11e6-8f83-db0674228449.png)


![screen shot 2016-09-20 at 19 26 15](https://cloud.githubusercontent.com/assets/10746682/18681595/148745c6-7f69-11e6-8066-24cccf44c524.png)

**Comment by DustinCampbell** [comment] 2016-09-20 17:36
nice!

**Comment by jrieken** [comment] 2016-09-21 08:02
reopening for me to further improve `MarkerService#read`. That 1 second must go ;-)

**Comment by jrieken** [comment] 2016-09-22 07:17
🐎 `MarkerService#read` from 1000ms down to 2.5ms. Slightly embarrassing it wasn't like this to begin with...

![screen shot 2016-09-22 at 09 16 01](https://cloud.githubusercontent.com/assets/1794099/18739632/48923f82-80a5-11e6-8a9a-c4429c4eb6df.png)

**Comment by jrieken** [comment] 2016-09-22 07:20
@sandy081 The last big chunk is `Tree#expand` which you might wanna consult with @joaomoreno if it can be improved. 

![screen shot 2016-09-22 at 09 19 51](https://cloud.githubusercontent.com/assets/1794099/18739714/ca8ad1c0-80a5-11e6-867b-d243f56c09a9.png)

**Comment by sandy081** [comment] 2016-09-28 09:45
I added another fix/improvement while applying filters. 

Using Tree.expand on each item or Tree.expandAll is not making any difference. 
Will discuss with @joaomoreno and see if I can improve this. 

Otherwise Closing this since we improved drastically.

**Closed by sandy081** 2016-09-28 09:45 UTC
Labels: bug, freeze-slow-crash
