### ISSUE TITLE
Vs code crash when opening a folder in the file browser

### ISSUE THREAD

**Issue by NicolasWent** [microsoft/vscode#231851] opened 2024-10-21 16:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. File
2. Open Folder
3. Browsing works but when I click on my folder, it crashes

## Additional details

- It crashes when I run a completely fresh vscode with --user-data-dir to another directory
- Not only this folder crashes, whenever I open a `target` directory generated by rust, it can crash sometimes
- I was able to open the folder that I was working with previously a lots of times on the same version and it crashes just now.
- doing `code .` on my folder opened the folder normally. It only crashes when I am browsing to my folder
- Sent my pending/101.....601.dmp file at mail at: [opencode@microsoft.com](mailto:opencode@microsoft.com)

**Comment by fslongjin** [comment] 2024-10-21 16:44
me too

**Comment by gjsjohnmurray** [comment] 2024-10-21 16:55
Probably https://github.com/microsoft/vscode/issues/230454

**Comment by NicolasWent** [comment] 2024-10-21 17:05
> Probably [#230454](https://github.com/microsoft/vscode/issues/230454)

It may crash differently from me. I am actually able to browse and also open some projects

But just some folders crashes

#230454 may by default enter a crashing folder this is why it directly crashes

Also I am using i3wm and picom if that may help reproducing the issue

**Comment by deepak1556** [comment] 2024-10-22 08:49
Thanks for the crash dump, it is a duplicate of https://github.com/microsoft/vscode/issues/230454

Please refer to https://github.com/microsoft/vscode/issues/230454#issuecomment-2418352959 for the root cause and also the reason why it only breaks with certain projects.

**Closed by deepak1556** 2024-10-22 08:49 UTC
