### ISSUE TITLE
Expand selection doesn't always work with every theme (for quotes)

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#25344] opened 2017-04-25 21:56 UTC
- VSCode Version: 
- OS Version: Windows 10

Steps to Reproduce:

1. Type anything between quotes
2. Put cursor between the cursor on what you just typed and use expand selection (Alt+Shift+Right Arrow)
3. Try it first with Dark+ (default) theme or Dracula Theme and then with Mattia Astornio's Material Theme or with Nord theme

Thing to notice: If the quotes are colored as same as text, it includes it in the selection, but it doesn't if it has different color assigned. 

![ff2de466-29bb-11e7-9230-5e5ff7f0443d](https://cloud.githubusercontent.com/assets/26769888/25409665/81d88366-2a30-11e7-85ee-4011b1739ddf.gif)

To-do: Expand selection should not include quotes, but just the text because a lot of times we need to change what is inside the quotes only. Putting quotes around the text again will add one step more.

Originally posted on Dracula theme repo, but as it also includes the default Dark+ theme and seems to be like a bug in VS Code itself, which I found a lot of people like and stick to it, so I put it here too.

https://github.com/dracula/visual-studio-code/issues/24#issuecomment-297170876
(Below one is copied from the link above)
Scopes of interest:
* punctuation.definition.string.begin
* punctuation.definition.string.end
When set to a different color than string, it expands correctly. When set to the same color, it does not.

**Comment by jrieken** [comment] 2017-04-26 09:29
dupe of https://github.com/Microsoft/vscode/issues/4795

**Closed by jrieken** 2017-04-26 09:29 UTC
