### ISSUE TITLE
Installation is corrupted [Ubuntu 16.04]

### ISSUE THREAD

**Issue by ougarte** [Microsoft/vscode#68009] opened 2019-02-06 21:00 UTC
- VSCode Version: 1.31 
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1. Download VSCode from https://code.visualstudio.com/Download
2. Open a terminal (on same directory where new code_1.31.xxx_amd64.deb file is)
3. Run following command - sudo dpkg -i code_1.31.xxx_amd64.deb
4. Following error raised
```ssh
Preparing to unpack code_1.31.0-1549443364_amd64.deb ...
Unpacking code (1.31.0-1549443364) over (1.30.2-1546901646) ...
dpkg-deb (subprocess): cannot copy archive member from 'code_1.31.0-1549443364_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive code_1.31.0-1549443364_amd64.deb (--install):
 cannot copy extracted data for './usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg' to '/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 code_1.31.0-1549443364_amd64.deb
```

Does this issue occur when all extensions are disabled?: Yes/No (both)

_note: I noticed that the size if .deb file is  2.0 MB_

**Comment by jhpratt** [comment] 2019-02-06 22:41
Duplicate of #68008.

**Closed** 2019-02-06 22:45 UTC
Labels: *duplicate, install-update

**Comment by Tyriar** [comment] 2019-02-06 22:47
@ougarte this could be region related, where are your located?

**Comment by ougarte** [comment] 2019-02-08 00:14
@Tyriar hi Daniel, Bolivia
