### ISSUE TITLE
Alternatives for "Select Editor" quickpick

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#106411] opened 2020-09-10 14:50 UTC
From user studies with students, when they create a new file from the Welcome page, this quickpick option really threw them off. They didn't realize "untitled" was the name of their new file, didn't know what "built-in" and "text editor" meant. I think this is unintuitive when you click on "new file". Maybe we can add an option from the welcome page to "create a new notebook", or introduce a new action which asks what editor to use, or have the notebook editor (and hex editor) be available from the language mode picker.

![image](https://user-images.githubusercontent.com/9721254/92747715-7e4c0300-f352-11ea-9293-c1a5ac191755.png)

**Comment by bpasero** [comment] 2020-09-10 16:15
@sana-ajani I think this was a bug actually which is fixed in insiders. We do not prompt anymore as far as I can tell, can you check?

PS: this issue seems to be in internal backlog when it can be in OSS repo I think.

**Comment by mjbvz** [comment] 2020-09-10 16:43
Yes this was a bug but should be fixed now. I just confirmed it is fixed in insiders

**Closed by mjbvz** 2020-09-10 16:43 UTC

**Comment by sana-ajani** [comment] 2020-09-10 16:51
@mjbvz do you think we could add the notebook editor as one of the options in the language picker?

**Comment by mjbvz** [comment] 2020-09-10 17:16
@rebornix I know you demoed including notebooks in the language selector. Is this currently supported for python notebooks?

**Comment by rebornix** [comment] 2020-09-11 22:46
@mjbvz it's still in progress https://github.com/microsoft/vscode/pull/93669 , we can make it happen if it looks reasonable to you.
