### ISSUE TITLE
mouse select not working

### ISSUE THREAD

**Issue by onequbit** [microsoft/vscode#191093] opened 2023-08-23 15:43 UTC
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code - Insiders. 
I cannot select text with the mouse in the text editor window. Selecting text works everywhere else, but not for the text file I am editing in VSCode.

VS Code version: Code - Insiders 1.82.0-insider (ad94cf18189746d2e942fda257950901049b3af3, 2023-08-23T05:33:37.329Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmhint1:30815193

```

</details>

**Comment by alexdima** [comment] 2023-09-01 07:20
Duplicate of #191083

**Closed by alexdima** 2023-09-01 07:20 UTC
