### ISSUE TITLE
Updated code command in bash (OS X) not working

### ISSUE THREAD

**Issue by rensa** [Microsoft/vscode#3941] opened 2016-03-10 01:22 UTC
I recently updated to the new version of code (0.10.10) on OS X, and I was asked to remove an existing `code` alias I had set up in bash. I did so by modifying my `.bashrc` and then allowed code to apply its own. But the new one doesn't work after restarting code and bash:

```
$ code
  File "<string>", line 1
    import os,sys; print os.path.realpath(sys.argv[1])
                          ^
SyntaxError: invalid syntax
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
```

**Comment by joaomoreno** [comment] 2016-03-10 09:20
Duplicate of #3790

Workaround: open `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code` and change `python` to `/usr/bin/python`.

**Closed by joaomoreno** 2016-03-10 09:20 UTC
