### ISSUE TITLE
Insiders randomly crashing

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#28618] opened 2017-06-13 12:43 UTC
- VSCode Version: bbcd10ae
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Typing in Typescript file
2. Get a random crash

I couldn't find a reliable way to replicate, but it crashed 3 times since I've updated insiders to the latest nightly. Since it's crashing to the desktop, I have only the `Event Viewer` event

```
Faulting application name: Code - Insiders.exe, version: 1.14.0.0, time stamp: 0x591206a2
Faulting module name: Code - Insiders.exe, version: 1.14.0.0, time stamp: 0x591206a2
Exception code: 0xc000041d
Fault offset: 0x00295dbf
Faulting process id: 0x25fc
Faulting application start time: 0x01d2e4362b08e820
Faulting application path: F:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe
Faulting module path: F:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe
Report Id: b72c615a-5c8f-41d9-a600-ebddf4803cbb
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 108977662563, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Code - Insiders.exe
P2: 1.14.0.0
P3: 591206a2
P4: Code - Insiders.exe
P5: 1.14.0.0
P6: 591206a2
P7: c000041d
P8: 00295dbf
P9: 
P10: 

Attached files:
\\?\F:\Users\Paulo\AppData\Local\Temp\WER1979.tmp.WERDataCollectionStatus.txt
\\?\F:\ProgramData\Microsoft\Windows\WER\Temp\WER2D1D.tmp.csv
\\?\F:\ProgramData\Microsoft\Windows\WER\Temp\WER2D4D.tmp.txt

These files may be available here:
F:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Code - Insiders._5473dc6fce759f1be93536b34ef97ae7cf6a2c8_127c4c61_455d4e23

Analysis symbol: 
Rechecking for solution: 0
Report Id: b72c615a-5c8f-41d9-a600-ebddf4803cbb
Report Status: 268435456
Hashed bucket: 0f995e98384851a39f8b710e266a3f76
```

contents of the Report.wer https://pastebin.com/r6Kx6eHv

at the current state, Insiders is unusable

**Comment by pocesar** [comment] 2017-06-13 12:55
found a quick way (but not always reproducible) to make it happen: open a big typescript file, go to `Help` > `Toggle Developers Tools`, do it a couple of times, it will crash

**Comment by mjbvz** [comment] 2017-06-13 21:31
I'm able to reproduce this by opening and closing the dev tools quickly, but I don't think that one is TS specific. Here's a crash while working in a small json file: [crash.txt](https://github.com/Microsoft/vscode/files/1072931/crash.txt)

**Comment by pocesar** [comment] 2017-06-13 22:03
yeah, it doesn't seem to be specific to TS, but most of the time I'm editing a TS file, it's crashing

**Comment by bpasero** [comment] 2017-06-14 04:14
The dev tools crash is unrelated. Does it crash without dev tools involved?

**Comment by pocesar** [comment] 2017-06-14 10:22
yes, it does, just by typing in a Typescript file like I said

**Comment by mjbvz** [comment] 2017-06-14 20:26
I'm unable to reproduce this. I'm also not sure how the TS extension could be brining down the VSCode process

@pocesar:

* Does this happen if you disable all extensions by starting code with `--disable-extensions`
* Does this happen in other file types?
* Does this happen in all TS files or just some file?

**Comment by pocesar** [comment] 2017-06-15 10:12
c89a5f66 is giving this upon starting

![image](https://user-images.githubusercontent.com/461084/27176692-e9c19180-5199-11e7-8649-0a10efb5b531.png)

**Comment by pocesar** [comment] 2017-06-18 18:24
while 73015a5e isn't crashing anymore while editing TS files, it's still crashing when opening the devtools at least twice

**Comment by mjbvz** [comment] 2017-06-20 00:48
Thanks @pocesar. I've opened #29063 to track the devtools issues.

Closing out this issue since it sounds like it no longer is happening. Perhaps you were just on a bad insiders build.

**Closed by mjbvz** 2017-06-20 00:48 UTC
Labels: freeze-slow-crash, needs more info, typescript
