### ISSUE TITLE
JS jQuery - the code is not colorful

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#36977] opened 2017-10-26 12:00 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
    *Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

1. download minified jQuery file from https://jquery.com/download/
2. open in VSCode

Result:

Code is white, not colorful.

Reproduces without extensions: Yes

**Comment by maxibanki** [comment] 2017-10-26 12:41
```

/resources/app/out/vs/workbench/workbench.main.js:10 Line (!function(a,b){...): longer than 20k characters, tokenization skipped.
/resources/app/out/vs/workbench/workbench.main.js:10 Line (a.removeEventLi...): longer than 20k characters, tokenization skipped.
/resources/app/out/vs/workbench/workbench.main.js:10 Line (null==d?void 0:...): longer than 20k characters, tokenization skipped.
```

**Comment by mjbvz** [comment] 2017-10-26 19:00
Duplicate of #5303

The 20000 character line length limit is currently as-designed

**Closed by mjbvz** 2017-10-26 19:00 UTC
Labels: as-designed, grammar, javascript
