### ISSUE TITLE
git 私钥可以配置密码

### ISSUE THREAD

**Issue by hzr1140521792** [microsoft/vscode#84761] opened 2019-11-14 03:08 UTC

**Comment by hzr1140521792** [comment] 2019-11-14 03:22
我的git私钥带密码，每次用vscode的工具提交，无法输入私钥密码，一下这issue都不是我想提的
我的操作系统：window 10
vscode版本：









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"vscodebot[bot]"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 中午11:11
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"往事如风"<1140521792@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] git 私钥可以配置密码 (#84761)




(Experimental duplicate detection)
 Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
  
Git ssh don't ask password (#81554) 
 
Git: Could not hash object when staging selected ranges (#58874) 
 
Git commit message format not reflected in git log (#81978) 
 
Git log (#17936) 
 
"Stage selected ranges" sometimes stages a revert of changes in the previous commit (#64027)

**Comment by yume-chan** [comment] 2019-11-14 04:47
Duplicate of #13680

The first issue from the bot is exactly your question.

**Comment by byyxx128** [comment] 2019-11-14 17:16
@hzr1140521792 Come to [GitHub](https://github.com), do not use email because it is not convenient to read the whole contents.
And always English please.
As mentioned above, someone has already report the same issue. So you can close yours.

**Closed** 2019-11-14 19:49 UTC
Labels: *duplicate
