### ISSUE TITLE
Syntax highlighting and formatting for TypeScript problems

### ISSUE THREAD

**Issue by adamerose** [microsoft/vscode#176007] opened 2023-03-03 05:16 UTC
Can VS Code add syntax color highlighting and newline formatting for TypeScript messages?

---

When I hover over a function I typically get this nicely formatted panel with newlines between arguments and syntax coloring:
<img src="https://user-images.githubusercontent.com/10884874/222636479-736b9bef-4fa0-493a-a1c1-798099e44665.png" width="400" /> 

---

But when I hover TypeScript errors it is just an uncolored unformatted block of text with long horizontal scrolling:

<img src="https://user-images.githubusercontent.com/10884874/222636422-800744ed-cc92-458b-be8d-6e5356a01438.png" width="400" /> 

<img src="https://user-images.githubusercontent.com/10884874/222636886-6040d971-586c-4ff0-b25e-70c51cafc51d.png" width="400" /> 

<img src="https://user-images.githubusercontent.com/10884874/222637019-993486f3-9151-4dd2-9896-fcd580b0c76d.png" width="400" />

**Comment by mjbvz** [comment] 2023-03-06 16:56
Duplicate of #54272

**Closed by mjbvz** 2023-03-06 16:56 UTC
