### ISSUE TITLE
Markdown Preview Broken in WSL Remote

### ISSUE THREAD

**Issue by dwatley** [microsoft/vscode#73924] opened 2019-05-18 01:32 UTC
In an update today-ish for Insiders, VSCode stopped rendering Markdown in Preview properly (no code fences, different font, etc), specifically inside a WSL remote. This also broke scrolling while viewing Markdown and Preview side-by-side.

Viewing local Markdown files in Preview behaves as it should.

I tried removing the .vscode-remote directory to re-install and the behavior is the same.

Good:

![good](https://user-images.githubusercontent.com/2055181/57962910-0098f400-78d2-11e9-9a41-f6860b514e89.png)

Bad:
![bad](https://user-images.githubusercontent.com/2055181/57962912-08589880-78d2-11e9-80da-6236fc089281.png)

**Comment by mjbvz** [comment] 2019-05-18 02:03
@alexandrudima Looks like our `vscode-resource` urls are broken. I started looking into this but could not track down the root cause. I see the requests being made in from the webview but they are never resolved

**Comment by mjbvz** [comment] 2019-05-21 05:12
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/376

**Closed by mjbvz** 2019-05-21 05:12 UTC
Labels: bug, markdown
