### ISSUE TITLE
Python Jupyter Notebook does not load in remote mode

### ISSUE THREAD

**Issue by Toni-Chan** [microsoft/vscode#82513] opened 2019-10-14 15:30 UTC
Issue Type: <b>Bug</b>

Jupyter Notebook does not load in the remote mode after reconnecting to the server, moving from a local network to a public one (but with same configurations). Other modules and files load well.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: **.**.**.**|
|OS|Linux x64 5.0.0-29-generic|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 1596)|
|Memory (System)|15.62GB (1.06GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.39.3
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
vscode-markdownlint|Dav|0.31.0
code-runner|for|0.9.14
rainbow-csv|mec|1.3.1
vscode-language-pack-zh-hans|MS-|1.39.3
python|ms-|2019.10.41019
markdown-pdf|yza|1.3.1

</details>

**Comment by mjbvz** [comment] 2019-10-14 22:23
Duplicate of #82336

**Closed by mjbvz** 2019-10-14 22:23 UTC
Labels: new release
