### ISSUE TITLE
Allow offline editing in Remote-WSL

### ISSUE THREAD

**Issue by ozimos** [microsoft/vscode#121799] opened 2021-04-21 08:32 UTC
After successfully opening a VSCode editor in Remote-WSL mode and then some time after, I lose network connectivity, I want the editor to remain usable.  The current behavior brings up the `Disconnected. Attempting to reconnect`  modal. After dismissing the modal, the modal returns almost immediately, making it impossible to continue editing. I want to be able to continue editing the file until network connectivity is restored. Only VSCode features [dependent on the network](https://code.visualstudio.com/docs/setup/network#_common-hostnames)  should be disabled

**Comment by alexdima** [comment] 2021-06-07 15:31
@ozimos Sorry for the slow response, I think I misunderstood this issue when I first read it. Do you use the regular WSL on your local machine? What do you mean "then some time after, I lose network connectivity"? Do you mean that you turn off your wi-fi?

**Comment by ozimos** [comment] 2021-06-08 00:07
Apologies for the muddled issue description. Yes, I use WSL2 on my windows machine. No, I do not turn off the wifi. But sometimes, the internet connection becomes unstable or goes down completely. At such times VSCode displays the `Attempting to reconnect` modal. When the modal is closed, it pops up immediately or shortly thereafter. While the modal is open, I cannot continue typing in the text editor. So after typing a few letters the modal pops open, I close it, type a few letters and the cycle repeats. I will try to reproduce by turning off my Wifi

**Comment by alexdima** [comment] 2021-06-09 17:15
I have investigated this and pushed https://github.com/microsoft/vscode/commit/bb01438efce6d7cb91a40543fd5b6911031a481b to log more information when disconnection occurs. Here is what I do:
* I open a new WSL window
* I go to the Windows Network Adapter Settings and disable my Ethernet network (the only active one besides vEthernet(WSL) ).
* the VS Code windows continues to work correctly and everything is fine
* I go and re-enable the Ethernet network
* **the browser WebSocket disconnects** which sends us in the reconnection loop

This is what I see with the extra logging that I just pushed:
```
[2021-06-09 19:13:24.642] [renderer3] [info] [remote-connection][ExtensionHost][c2db8…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2021-06-09 19:13:24.694] [renderer3] [error] {"isTrusted":true}
[2021-06-09 19:13:24.696] [renderer3] [info] [remote-connection][ExtensionHost][c2db8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-06-09 19:13:24.696] [renderer3] [info] [remote-connection][ExtensionHost][c2db8…][reconnect] resolving connection...
[2021-06-09 19:13:24.696] [renderer3] [info] [remote-connection][ExtensionHost][c2db8…][reconnect] connecting to 172.26.138.234:45139...
[2021-06-09 19:13:24.696] [renderer3] [info] [remote-connection][Management   ][709a5…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2021-06-09 19:13:24.697] [renderer3] [error] {"isTrusted":true}
[2021-06-09 19:13:24.697] [renderer3] [info] [remote-connection][Management   ][709a5…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-06-09 19:13:24.698] [renderer3] [info] [remote-connection][Management   ][709a5…][reconnect] resolving connection...
[2021-06-09 19:13:24.698] [renderer3] [info] [remote-connection][Management   ][709a5…][reconnect] connecting to 172.26.138.234:45139...
[2021-06-09 19:13:32.773] [renderer3] [info] [remote-connection][Management   ][709a5…][reconnect] reconnected!
[2021-06-09 19:13:32.789] [renderer3] [info] [remote-connection][ExtensionHost][c2db8…][reconnect] reconnected!
```

And I can confirm that the WebSockets are being closed using the Network Tab:
![image](https://user-images.githubusercontent.com/5047891/121399672-f170bd00-c956-11eb-8548-4be6b8e2fcf2.png)

@aeschli I would first ask that maybe you can investigate if WSL is the root cause of the closing WebSockets. If WSL is not the root cause of the socket disconnect, then I think we need help from @deepak1556 and create an issue for Chromium.

**Comment by aeschli** [comment] 2021-10-18 19:43
Not sure if something has changed, but I'm not able to reproduce a disconnect. I tried the steps from https://github.com/microsoft/vscode/issues/121799#issuecomment-857881313, tuning of th WSL Ethernet Adapter, Airplane mode, WIFI disconnect. I get reconnected correctly.
Closing the issue for now.

**Closed by aeschli** 2021-10-18 19:43 UTC
Labels: WSL, remote

**Comment by aeschli** [comment] 2021-10-21 10:52
@alexdima Hm, I don't have a wired network adapter and would first have to organize/buy an USB-3 adapter/dock...

Do we want to extract the 'enable adapter triggers disconnect' into a new issue? I'm nor sure if/how it relates to the original reported issue.
