### ISSUE TITLE
terminal doesn't have scrollbar

### ISSUE THREAD

**Issue by chintan9** [Microsoft/vscode#7425] opened 2016-06-08 15:20 UTC
- VSCode Version:1.2
- OS Version:win10 10240

Steps to Reproduce:

1. ctrl+` 
2.  terminal doesn't have scrollbar (not working on my laptop except  mouse scroll)

**Comment by Tyriar** [comment] 2016-06-09 04:34
Duplicate of https://github.com/Microsoft/vscode/issues/6602

**Closed by Tyriar** 2016-06-09 04:34 UTC
