### ISSUE TITLE
Tasks: npm script aren't being prefixed with "run"

### ISSUE THREAD

**Issue by HeavyStorm** [Microsoft/vscode#45709] opened 2018-03-13 23:00 UTC
- VSCode Version: 1.22.0-insider 112670122d3acf863aa9542b1642d64c69be10bf x64
- OS Version: Microsoft Windows [Version 10.0.17074.1002] 

Steps to Reproduce:

1. Setup a task  in tasks.json for "npm", with script as "build".
2. Run the task by calling npm: run build in the command bar.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

Example task.json:

```js
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "build",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

Task.json that works:
```js
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "run build", // <--- must add run!
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

If this is expected behavior, it changed from last version. I think that the key "script" may lead a user (such as myself) to believe that a npm run-script will called, as opposed to any npm command (as it is right now).

Also, if that's expected behavior, task generation for npm is generating it wrong (exactly like my first example).

**Comment by HeavyStorm** [comment] 2018-03-13 23:07
I think my diagnose may be wrong. What is happening is that nothing is being ran. 

I thought the reason was that vscode was shelling "npm build" instead of "npm run build".

```
![image](https://user-images.githubusercontent.com/1890900/37374500-29be2402-26fa-11e8-97b6-624df28fa5bd.png)

```

**Comment by dbaeumer** [comment] 2018-03-14 09:43
This is a duplicate of https://github.com/Microsoft/vscode/issues/45684. I broke that yesterday but is fixed in todays insider again. We added support for space quoting and I wrongly quoted whole command lines hence making them fail.

**Closed by dbaeumer** 2018-03-14 09:43 UTC
Labels: tasks
