### ISSUE TITLE
Code panes crashing

### ISSUE THREAD

**Issue by Brocco** [Microsoft/vscode#7743] opened 2016-06-15 21:21 UTC
- VSCode Version: 1.3.0-insider
- OS Version: OS X 10.10.5

Steps to Reproduce:

Unfortunately I have no specific steps to reproduce this issue, but as I click in a code window (TypeScript typically) just to navigate around the code pane crashes.

It happens periodically with no apparent regularity.

**Comment by tjsail33** [comment] 2016-06-16 01:12
+1. Happens when highlighting frequently for me. Interestingly, even though the file is removed from the working files list when I reopen the file the code I had highlighted when the pane crashed was still highlighted. So it seems like the context for editing the file is intact, the viewing panel just ceases to exist.

**Comment by dbaeumer** [comment] 2016-06-20 19:37
@bpasero assigning to you since this could be caused by the new editor / tab code. And according to https://github.com/Microsoft/vscode/issues/7743#issuecomment-226363567 this is language agnostic.

**Comment by tjsail33** [comment] 2016-06-20 21:14
FWIW I am no longer experiencing this as of the update the day after my comment.

**Comment by bpasero** [comment] 2016-06-21 05:24
@Brocco @tjsail33 could it be that it always happens with the same file you open? this could point to an issue with our tokenizer.

**Comment by Brocco** [comment] 2016-06-23 01:40
@bpasero I haven't had any crashes in the past few days either, just like @tjsail33. So I'm not sure if something in one of the updates had fixed the issue or not. When it was happening in was not just one particular file or file type that was causing it to crash. If it happens again, I'll report back.

I'll leave it to you as to whether you want to close this issue or not, I'm fine either way.

**Comment by bpasero** [comment] 2016-06-23 04:44
Sure, lets reopen when you see it again.

**Closed by bpasero** 2016-06-23 04:44 UTC
Labels: bug, freeze-slow-crash, needs more info, workbench
