### ISSUE TITLE
ctrl+backspace does not delete entire word in integrated terminal

### ISSUE THREAD

**Issue by fireattack** [microsoft/vscode#208551] opened 2024-03-25 04:08 UTC
Type: <b>Bug</b>

Within the integrated terminal, ctrl+backspace does not delete entire word as it is in Windows Terminal.

It does not work in either CMD or PS.

CMD: `ctrl+backspace` only deletes one character.
PS: ctrl+backspace prints `^W`.

Log from keybind troubleshooting (when using CMD):

```
2024-03-25 12:07:37.388 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-03-25 12:07:37.389 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-03-25 12:07:37.389 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
2024-03-25 12:07:37.389 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
2024-03-25 12:07:37.390 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-03-25 12:07:37.629 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-03-25 12:07:37.629 [info] [KeybindingService]: | Resolving ctrl+Backspace
2024-03-25 12:07:37.630 [info] [KeybindingService]: \ From 3 keybinding entries, matched workbench.action.terminal.sendSequence, when: terminalFocus && terminalShellType == 'cmd', source: built-in.
2024-03-25 12:07:37.630 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backspace, keyCode: 8, key: Backspace
2024-03-25 12:07:37.630 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backspace, keyCode: 1 ('Backspace')
2024-03-25 12:07:37.631 [info] [KeybindingService]: | Resolving ctrl+Backspace
2024-03-25 12:07:37.631 [info] [KeybindingService]: \ From 3 keybinding entries, matched workbench.action.terminal.sendSequence, when: terminalFocus && terminalShellType == 'cmd', source: built-in.
2024-03-25 12:07:37.631 [info] [KeybindingService]: + Invoking command workbench.action.terminal.sendSequence.
2024-03-25 12:07:37.708 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-03-25 12:07:37.709 [info] [KeybindingService]: | Resolving ctrl+Backspace
2024-03-25 12:07:37.709 [info] [KeybindingService]: \ From 3 keybinding entries, matched workbench.action.terminal.sendSequence, when: terminalFocus && terminalShellType == 'cmd', source: built-in.
2024-03-25 12:07:37.778 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-03-25 12:07:37.778 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-03-25 12:07:37.779 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```
It was already reported before (#98404) but for some reason the ticket was closed despite the problem persists.

A VS Code dev [claimed it should work](https://github.com/microsoft/vscode/issues/98404#issuecomment-1802535324) but made no further comment when the user said it didn't work on their end (it obviously didn't work here, too).

And the log of `2024-03-25 12:07:37.779 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.` looks very relevant to this bug (it makes sense it would only delete one character if VS Code ignore Ctrl for some reason), but no further investigation was done in the previous ticket. 

VS Code version: Code - Insiders 1.88.0-insider (409da0445d397e37a790ce5d2499688955c3fcfa, 2024-03-22T05:50:17.322Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (2.41GB free)|
|Process Argv|--crash-reporter-id bcd92158-6998-4802-84d9-5452edf8ef65|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.2.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
jupyter|ms-|2024.2.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30998029
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
7ghi1836:30988844
showvideot:30994525

```

</details>

**Comment by meganrogge** [comment] 2024-03-25 20:36
this works for me despite seeing the same in the keyboard shortcuts troubleshooting log. 

Thus, I think this is related to your setup/settings. Can you comment out your settings.json file to see if it persists?

**Comment by fireattack** [comment] 2024-03-26 00:17
My settings.json is totally empty (I tested with Insiders + fresh profile) and I can reproduce this with multiple machines (Win10).

**Comment by meganrogge** [comment] 2024-03-26 14:36
a gif would help

**Comment by meganrogge** [comment] 2024-03-26 15:08
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-03-26 15:12 UTC
Labels: info-needed, upstream, windows, terminal-conpty

**Comment by fireattack** [comment] 2024-03-26 18:46
@meganrogge 

No, I cannot reproduce it in Windows Terminal. If so I have already reported it there. Actually, I have never had such issue in Windows Terminal, ever.

Look, I understand we don't fix upstream issues in this repo, that's totally fair. But it looks to me you are not even sure if it's an upstream issue.

> This issue seems

> chances are 

Can we not close issues promptly without any confirmation or discussion? This is frustrating. 

You said "this works for me" in https://github.com/microsoft/vscode/issues/208551#issuecomment-2020605783. Are you testing in Win10? Win11? MacOS? Which version exactly? No information was given or whatsoever. Again, you said "[probably] it's fixed in a later version of Windows", but it was never broken in WT which makes feel that is unlikely.

I personally tested it with 4 machines, multiple versions of VS Code, all kinds of settings, before I opened the ticket. I think I made an effort to be as thorough as possible. 

I understand you are likely busier than me, but you just asked a question, and now after barely 1 hour, you chose to give up waiting for my answer and just closed the ticket anyway. Like should I just live on GitHub and answer the questions in real time or what?

I don't think this is the right attitude to help users or VS Code in general.

**Comment by Tyriar** [comment] 2024-03-26 19:05
@fireattack I told @meganrogge to close it off with this reply. I did so because:

- ctrl+backspace works for both her and me on Windows 11.
- The fact that it prints ^W indicates that it's being sent to pwsh, it's not being handled. Meaning our part of the job is being done.
- Conpty mentioned above ships with Windows, which means you're on a very old version at this point.
- It _likely_ works on Windows Terminal because they bundle the very latest version of Conpty (which we are actually quite close to do as well). In the slim chance that is not the case, then chances are it's due to their use of a native win32 input mode of which we considered but ultimately decided not to do.

If you're curious how it works, this is what happens when you hit ctrl+backspace on Windows:

https://github.com/microsoft/vscode/blob/ffbd5de8c8ecfd66766cca142002e347260c0451/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L238-L250

These keybindings (which you can customize on your end if you want to try) send special sequences because pseudoterminals, which conpty is emulating, do not natively encode ctrl+backspace.

I understand your frustration, but we do have a lot to do and this is _very_ likely to be fixed by updating to a later version of Windows 11, or when the Windows Terminal team ships the Nuget package which we can consume (https://github.com/microsoft/terminal/issues/15065). We response with terse or canned responses sometimes because we're engineers, not support staff, and writing this up was a good 20 minutes of which I could be doing something more productive. This is why I created the FAQ you were pointed to: https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue. Any feedback on the FAQ or our message is welcome
