### ISSUE TITLE
New Line Separator for the entire project

### ISSUE THREAD

**Issue by grigoriu-stefan-iulian** [microsoft/vscode#93011] opened 2020-03-19 13:25 UTC
The software is great!
Please add an option to change the New Line Separator for the entire project. It's CRLF on windows but my linter asks for LF and I can change it for individual files only :(

**Comment by aeschli** [comment] 2020-03-22 13:38
duplicate of https://github.com/microsoft/vscode/issues/68601

**Closed by aeschli** 2020-03-22 13:38 UTC
Labels: feature-request
