### ISSUE TITLE
Tab snippet for generating  html tag is slow at first time

### ISSUE THREAD

**Issue by ardivali** [Microsoft/vscode#17220] opened 2016-12-15 03:45 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|vscode-console-wrapper|fabiodam|0.4.0|
|vscode-todo|MattiasPernhult|0.8.0|
|cpptools|ms-vscode|0.9.3|
|typescript-javascript-grammar|ms-vscode|0.0.12|

---

Steps to Reproduce:

1. Open VSCode
2. Create new Html file.
3. Type div
4. Press Tab

**Comment by ramya-rao-a** [comment] 2016-12-15 23:24
This is due to the lazy load we do for emmet the cost of which is borne by the first use of emmet.
Will keep this issue open to investigate if we can do anything better before closing as "by design"

**Comment by emreald** [comment] 2016-12-16 05:37
Thanks!

**Comment by ramya-rao-a** [comment] 2017-04-02 03:58
There was an older issue for the same, so will close this one in favor of #6816

**Closed by ramya-rao-a** 2017-04-02 03:58 UTC
Labels: emmet

**Comment by ramya-rao-a** [comment] 2017-04-06 17:55
#21943 looks into having emmet features come from an extension rather than the tightly coupled in built way it is integrated today.

Closing this issue as the work done in #21943 will have a better user experience.

If #21943 doesn't pan out, then we will get back to see if there is something we can do to improve the first time experience.
