### ISSUE TITLE
Output (tasks) pane doesn't autoscroll

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#17629] opened 2016-12-20 23:07 UTC
- VSCode Version: `1.9.0-insider` 04f541160e0d41be95df9a964b1b570aec549157
- OS Version: macOS Sierra `10.12.2`

Steps to Reproduce:

1. Setup a build task ('m using a powershell script)
2. Open the output pane to `tasks`
3. Trigger a build (I used the hotkey)
4. The tasks pane will clear, but won't autoscroll

I've had the same issue with a `watch` command (also powershell) but the difference there is that it doesn't clear the pane first -- but I would still expect it to autoscroll as long as I haven't scrolled up, and if I have, then it should resume auto-scrolling if I scroll all the way back down.

//cc @isidorn

**Comment by isidorn** [comment] 2016-12-21 09:22
Can not repro. 
Tried with using a custom output from an extension using this snippet
Also tried with openinging output pane to tasks, triggering a vscode build 

Assigning to @dbaeumer to try to repro as this also might be how tasks are using output.

```javascript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "ts-extension" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed
        const output = vscode.window.createOutputChannel('isidor');
        output.show();
        output.clear();
        for (var i = 0; i < 100; i++) {
            output.appendLine('hello');
         }
         setTimeout(() => output.appendLine('hello'), 100);
        // Display a message box to the user
        vscode.window.showInformationMessage('Hello World!');
    });

    
    context.subscriptions.push(disposable);

}

 
    vscode.languages.registerCompletionItemProvider({ pattern: '**/*' }, {

		provideCompletionItems(document, position, token) {
            
			const mySnippet = new vscode.SnippetString();
            mySnippet.appendText('zurich ');
            mySnippet.appendVariable('postCode', '8008');
            
            const item = new vscode.CompletionItem('ZURICH', vscode.CompletionItemKind.Class);
            item.insertText = mySnippet;

            return [item];
            // return [mySnippet];
        }
    });

// this method is called when your extension is deactivated
export function deactivate() {
}
```

![tasks](https://cloud.githubusercontent.com/assets/1926584/21383680/4c11c52a-c767-11e6-816a-19fa87599e79.gif)

**Comment by dbaeumer** [comment] 2016-12-21 09:24
I am not able to reproduce this either using as task producing quite some output. @eamodio can you share a project showing the problematic behavior. Would help tracking it down.

**Comment by eamodio** [comment] 2016-12-21 23:10
@dbaeumer I can't share this project, but I will try to setup a sample (might be delayed a bit as I'm away for vacation).

**Comment by eamodio** [comment] 2016-12-23 11:07
@dbaeumer I've been able to repo this using the following:

`tasks.json`
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "powershell",
    "args": [
        "-NoLogo",
        "-NoProfile"
    ],
    "echoCommand": false,
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "test",
            "args": [ "${workspaceRoot}/output.ps1" ]
        }
    ]
}
```

`output.ps1`
```ps
for ($i = 0; $i -lt 50; $i++) {
    Write-Host "Output line: $i"
    Start-Sleep -m 100
}
```

Each time I run that task -- the output clears, but doesn't scroll at all. I am running powershell 6.0 alpha 13

Please let me know if I can provide any more details.

**Comment by dbaeumer** [comment] 2016-12-27 10:55
Works under Windows. Need to find out what is different to PowerShell under Mac.

![cast](https://cloud.githubusercontent.com/assets/1931590/21498259/40e6dc94-cc2b-11e6-84b7-b1237e88c73b.gif)

@eamodio can you try one thing. Set isShellCommand to false and let me know if this makes a difference.

**Comment by eamodio** [comment] 2016-12-30 20:32
@dbaeumer setting `isShellCommand` to `false` doesn't seem to make a difference

**Comment by dbaeumer** [comment] 2017-01-23 20:16
@eamodio I reimplemented how task are executed. Instead of having my own runner I am now executing them in the terminal. For the next release you still have to opt in into this new support using the tasks.json property `"_runner": "terminal"`. Can you give this new support a try. I will not invest into fixing bugs on the old story since it has to many limitations and the future direction is to execute task in the integrated terminal.

**Comment by eamodio** [comment] 2017-01-23 20:25
@dbaeumer great -- can't wait to try it out :)

**Comment by eamodio** [comment] 2017-01-24 07:42
@dbaeumer I tested it out and it works -- looks great. No issues with scrolling, and now it has color! Eventually will the output still live on the `Output` pane (under Tasks) or in the `Terminal` pane?

Personally I hope they move out of the `Terminal` pane, as it kind of hijacks my terminal usage -- now its not as easy for me to get to a command line when I have a task running.

I think it would be great if there was a first class `Tasks` pane -- one were you could easily see which task was running, the output from it, and be able to kill it

**Comment by dbaeumer** [comment] 2017-01-24 07:47
@eamodio good to hear that it works

The current thinking is to have them in the terminal pane since they are terminals. I did prefix the terminal labels with Task to make this more clear.

I am not sure if a separate Task panel makes sense since it will ask for other grouping up there as well. I would rather opt for having some filtering of terminals in the terminal pane.

@Tyriar FYI. Do you have an idea how to best tackle this.

**Comment by Tyriar** [comment] 2017-01-24 17:10
Terminal tabs would largely solve this imo, if we had tabs there could be some indicator on the tab to show it's a task? https://github.com/Microsoft/vscode/issues/10546

Splitting the terminal is another area similar to this which is needed to improve terminal management imo. https://github.com/Microsoft/vscode/issues/7504

Right now all we can do is change the name as you're doing.

**Comment by eamodio** [comment] 2017-01-24 20:07
Yeah, I think terminal tabs could certainly solve this.

Now that there are "tabs" on the bottom pane, I think it could be nice if instead of the dropdown ui the terminal has currently, it would have something similar (though distinct) for terminals.

In this area:
![image](https://cloud.githubusercontent.com/assets/641685/22264567/72f95cee-e246-11e6-8bb1-7cf59ec2a671.png)

**Comment by vector-of-bool** [comment] 2017-02-03 05:16
I've been having problems with auto-scrolling for quite a while, on both Windows and Linux. I like to use the `OutputChannel` to see build output, so when it doesn't scroll, it gets very frustrating. I think I've discovered one of the possible causes. I found that one particular extension, `better-merge`, would make the auto-scroll stop working in output panes. I downloaded the code and found that the line to blame is here:

```typescript
vscode.languages.registerCodeLensProvider({ pattern: '**/*' }, this)
```

If this line is commented out, auto-scroll works. If the line is present, auto-scroll does not work. I'm not sure why there is an odd interaction between CodeLens and OutputChannel, but I hope someone will be able to make use of this information. And ideas?

**Comment by dbaeumer** [comment] 2017-02-03 09:28
@jrieken please see last comment. This adds a code lens provider to every open model. Right. And the output channel travels as a model to the extension host. 

@isidorn can you please investigate why a code lens provider on the output channel prevents scrolling

@vector-of-bool thanks for providing the details.

**Comment by jrieken** [comment] 2017-02-03 10:19
wow - code lenses everywhere... behind the scenes an output channel is an editor and therefore affected by that code lens provider. unsure why the auto scroll is affected by that tho

**Comment by isidorn** [comment] 2017-02-10 10:48
@vector-of-bool @eamodio can you please try if auto scrolling works with latest insiders - we changed something there a couple of days ago which might fix your issue

If the issue persists can you please create a small github repo with your extension where I can reproduce this issue - thanks a lot!

**Comment by eamodio** [comment] 2017-02-10 15:22
@isidorn it seems to be working for me in the latest! Thank you!

**Comment by isidorn** [comment] 2017-02-10 15:36
Love hearing that

**Closed by isidorn** 2017-02-10 15:36 UTC
Labels: bug, mac, needs more info, workbench
