### ISSUE TITLE
发热量大

### ISSUE THREAD

**Issue by mljuw** [Microsoft/vscode#31375] opened 2017-07-25 09:32 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
tortoise-svn-for-vscode|cds|0.1.1
Lua|key|0.0.9
gmod-luadev|lix|0.1.1
cpptools|ms-|0.12.1
java|red|0.7.0
vscode-icons|rob|7.11.0
vscode-todo-highlight|way|0.5.8
lua-for-vscode|xxx|0.0.23

---

Steps to Reproduce:

1.macbook pro 使用长时间发热量比较高， 我使用sublime Text2 完全没有这种情况出现
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment] 2017-07-25 23:21
duplicate of https://github.com/Microsoft/vscode/issues/16963

**Closed** 2017-07-25 23:21 UTC
Labels: new release
