### ISSUE TITLE
Invalid regular expression: //bc++/b/: Nothing to repeat

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154747] opened 2022-07-11 07:13 UTC
[Error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=b34dbb4b-0a2e-2cdd-455c-34abcfc8a52a):

```
SyntaxError: Invalid regular expression: //bc++/b/: Nothing to repeat
at new RegExp (<anonymous>)
[at Qa.checkForWholeWordMatchType in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:558:7](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L558:7)
[at Qa._doFindMatchesInSetting in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:506:11](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L506:11)
[at Qa._findMatchesInSetting in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:471:23](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L471:23)
[at new Qa in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:467:32](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L467:32)
[at P in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:120:35](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L120:35)
[at l.filterSettings in src/vs/workbench/services/preferences/common/preferencesModels.ts:80:33](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/services/preferences/common/preferencesModels.ts#L80:33)
[at mr.searchModel in src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts:134:42](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/preferencesSearch.ts#L134:42)
[at Jt._filterOrSearchPreferencesModel in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1591:39](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1591:39)
[at Jt.filterOrSearchPreferences in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1516:15](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1516:15)
[at Jt.localFilterPreferences in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1502:15](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1502:15)
[at <anonymous> in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1485:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1485:17)
[at <anonymous> in src/vs/base/common/async.ts:333:13](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/async.ts#L333:13)
[at async Jt.onSearchInputChanged in src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1335:3](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L1335:3)
```

**Comment by rzhao271** [comment] 2022-07-12 21:36
Duplicate of https://github.com/microsoft/vscode/issues/153583

**Closed by rzhao271** 2022-07-12 21:36 UTC
Labels: error-telemetry, *duplicate
