### ISSUE TITLE
Notebook input cell padding varies with layout direction

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99364] opened 2020-06-04 12:24 UTC
Check it out:

![recording (13)](https://user-images.githubusercontent.com/22350/83756215-05f8e600-a66f-11ea-9b3e-661c7f418913.gif)

**Comment by rebornix** [comment] 2020-06-05 00:22
Started to see this layout issue recently. My guess is monaco somehow renders horizontal scrollbar.

**Comment by rebornix** [comment] 2020-06-05 00:24
/duplicate of #99163 and I left even almost the same reply ;(

**Closed** 2020-06-05 00:24 UTC
Labels: *duplicate, bug, notebook

**Comment by roblourens** [comment] 2020-06-05 16:10
Why is there no left padding in the editor? Is that a settign?
