### ISSUE TITLE
Paste not working correctly in Terminal

### ISSUE THREAD

**Issue by papaiatis** [Microsoft/vscode#18852] opened 2017-01-20 15:14 UTC
- VSCode Version: 1.8.1
- OS Version: Calculate linux (Gentoo)

Steps to Reproduce:

1. Open Integrated Terminal in VSCode
2. type "history" (this may not be necessary, but I tried to copy a previous command I executed)
3. Select long, wrapped text from terminal which spans to multiple lines, right click then Copy
4. Next to the curost, Right click and Paste the text to the terminal
5. Only the "first line" in the wrapped text is pasted

I'm using bash shell.

**Comment by rmunn** [comment] 2017-01-20 15:22
I can't reproduce this on Linux Mint using GNOME Terminal (and the Bash shell). Which terminal emulator, and shell, are you using?

**Comment by papaiatis** [comment] 2017-01-20 15:36
I updated a little bit the "Steps to Reproduce". I'm using bash shell. Not sure which terminal emulator? It's the integrated terminal in vscode.

**Comment by Tyriar** [comment] 2017-01-20 16:12
I can't repro either on Ubuntu/Unity. @papaiatis do you have any errors in dev tools console? (Help > Toggle Developer Tools)

**Comment by papaiatis** [comment] 2017-01-23 08:22
I could reproduce it on another machine. Here's a similar command I'm trying to copy&paste:

`APP_CONFIG=/home/dev/WS/vsc/dev/apps/dashboard/project/129876/etc/dashboard.dev.conf perl -I lib/ -I /home/dev/WS/vsc/dev/apps/component/My-Some-Module/project/129876/lib/ bin/dashboard-app.pl --config etc/dashboard.dev.conf --log_level TRACE`

There is no error in the Developer Tools Console.

**Comment by bobmagicii** [comment] 2017-01-23 23:11
this is what happens to me with long text. all the foo and a bit of bar as well. 
![image](https://cloud.githubusercontent.com/assets/881944/22227072/e971b398-e18e-11e6-85de-029866e01884.png)

**Comment by Tyriar** [comment] 2017-01-23 23:25
@bobmagicii yes this is probably different, lots of work happened to improve Windows support so check on the [Insiders build](https://code.visualstudio.com/insiders) before filing 😄

**Comment by bobmagicii** [comment] 2017-01-24 01:33
bruh i been on the insider build since before it was its own installer. :) but i agree it kinda does sound different. didn't want to file a new ticket at first yet though just in case.

**Comment by Tyriar** [comment] 2017-04-21 18:59
@papaiatis closing this off as we cannot repro, let us know if you have any more details.

**Closed by Tyriar** 2017-04-21 18:59 UTC
Labels: integrated-terminal, linux, needs more info

**Comment by bobmagicii** [comment] 2017-04-22 03:04
have not experienced this in a while i believe it was cleared up a few releases later
