### ISSUE TITLE
Small selection highlighting rendering glitch

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#42681] opened 2018-01-31 22:45 UTC
**Steps to Reproduce:**

1. In a file:

```
a
aa
```

2. Select all

**Bug**
Tiny edge rendering glitch between lines:

![screen shot 2018-01-31 at 2 44 13 pm](https://user-images.githubusercontent.com/12821956/35651658-5a92ee94-0695-11e8-9a5d-1bf96cb6c3be.png)

**Comment by joaomoreno** [comment] 2018-02-05 08:35
Duplicate of #38591?

**Closed** 2018-02-05 13:53 UTC
Labels: bug, editor-rendering
