### ISSUE TITLE
Modified elsewhere hover not very discoverable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153587] opened 2022-06-28 18:44 UTC
Testing #153351

1. Can we change the "modified elsewhere" item to be clickable. On click it would also show the hover
2. Also on hover can we change mouse style to be pointer?

That way the hover would be more discoverable. I am afraid some users might not find it otherwise

**Comment by mjbvz** [comment] 2022-06-28 18:49
Duplicate of #153578

**Closed by mjbvz** 2022-06-28 18:49 UTC
