### ISSUE TITLE
Format Document on HTML with inline styles

### ISSUE THREAD

**Issue by vivaladan** [Microsoft/vscode#19674] opened 2017-02-01 15:19 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|xml|DotJoshJohnson|1.7.0|
|vscode-npm-script|eg2|0.1.6|
|csharp|ms-vscode|1.6.2|
|lorem-ipsum|Tyriar|1.0.0|

---

Steps to Reproduce:

1. Include inline stypes on the HTML tags themselfs
2. Format document
3. All lines below will have their indenting removed

Before format document:
![image](https://cloud.githubusercontent.com/assets/1514212/22512850/3d7aa256-e892-11e6-92ee-d6fb7cbd862f.png)

After format document:
![image](https://cloud.githubusercontent.com/assets/1514212/22512865/4c89ac2e-e892-11e6-9116-627fa305f4a9.png)

**Comment by aeschli** [comment] 2017-02-01 16:00
duplicate of #17849

**Closed by aeschli** 2017-02-01 16:00 UTC
