### ISSUE TITLE
vscode exploration: intelliSense / suggestion box is not positioned normally.

### ISSUE THREAD

**Issue by evangunawan** [microsoft/vscode#86682] opened 2019-12-10 16:53 UTC
- VSCode Version:
Version: 1.41.0-exploration (system setup)
Commit: 22c3db00ec057fecf0144c4c7f8c6bc6cb60e5d6
Date: 2019-12-03T21:30:12.474Z
Electron: 7.1.3
Chrome: 78.0.3904.126
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19035

- OS Version:
Windows version 2004 (OS Build 19035.1) Insider build - fast.

Steps to Reproduce:

1. Open Vscode exploration
2. Type something, ctrl+space, or it will auto appear.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/29895822/70550133-e42f1280-1ba7-11ea-8ac4-87c03dc695e0.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by IllusionMH** [comment] 2019-12-10 17:08
Most like duplicate of #85313 which was already fixed in Insiders, but I'm not sure if it is in Exploration builds.

**Closed** 2019-12-10 18:04 UTC
Labels: *duplicate
