### ISSUE TITLE
Bulk edit integration tests print to console

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#87414] opened 2019-12-19 15:36 UTC
Since a while I notice how we seem to be printing file operation errors when running integration tests, e.g.:

```
{
  fileOperationResult: 1,
  options: {
    acceptTextOnly: true,
    limits: { size: 17179869184, memory: 1468006400 }
  }
}
```

Hard to figure out the origin, so I added `new Error().stack` as message into the error [1] and that reveals:

```
{
  fileOperationResult: 4,
  options: {
    foo: 'Error\n' +
      '    at new FileOperationError (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/platform/files/common/files.js:253:35)\n' +
      '    at FileService.doValidateMoveCopy (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/platform/files/common/fileService.js:537:27)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n' +
      '    at async FileService.doMoveCopy (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/platform/files/common/fileService.js:442:69)\n' +
      '    at async FileService.move (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/platform/files/common/fileService.js:421:26)\n' +
      '    at async NativeTextFileService.moveOrCopy (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/workbench/services/textfile/browser/textFileService.js:321:28)\n' +
      '    at async BulkEdit._performFileEdits (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/workbench/services/bulkEdit/browser/bulkEditService.js:257:21)\n' +
      '    at async BulkEdit.perform (file:///Users/bpasero/Development/vscode-electron-6.0.x/out/vs/workbench/services/bulkEdit/browser/bulkEditService.js:240:21)'
  }
}
```

[1]

```ts
export class FileOperationError extends Error {
	constructor(message: string, public fileOperationResult: FileOperationResult, public options?: IReadFileOptions & IWriteFileOptions & ICreateFileOptions) {
		super(new Error().stack);

		this.options = { foo: new Error().stack } as any;
	}

	static isFileOperationError(obj: unknown): obj is FileOperationError {
		return obj instanceof Error && !isUndefinedOrNull((obj as FileOperationError).fileOperationResult);
	}
}
```

**Comment by jrieken** [comment] 2019-12-20 09:46
/duplicate of https://github.com/microsoft/vscode/issues/84283

**Closed** 2019-12-20 09:46 UTC
Labels: *duplicate, integration-test

**Comment by jrieken** [comment] 2019-12-20 09:50
The error is expected because those tests also cover invalid scenarios. What's unclear is there/wy the error is printed to the console... Is this the log service? https://github.com/microsoft/vscode/blob/c11a0c130046bc8318c5ff81e4a09a0d3365b37f/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L434

**Comment by bpasero** [comment] 2019-12-20 10:18
But wouldn't that also print the stacktrace?

**Comment by jrieken** [comment] 2019-12-20 10:24
🤷‍♂ no clue, but no `console.log` statement seen so it must be something in there.

**Comment by bpasero** [comment] 2019-12-20 11:03
Indeed, coming from:

https://github.com/microsoft/vscode/blob/ecc140e81dc5f2934181ddd40ff733a68646e149/src/vs/platform/log/common/logIpc.ts#L40
