### ISSUE TITLE
[ruby] add support for non-interpolated (and others) heredoc syntax

### ISSUE THREAD

**Issue by rgl** [Microsoft/vscode#5155] opened 2016-04-11 08:13 UTC
- VSCode Version: 0.10.11.
- OS Version: Windows 10.

Currently Code supports the Here Documents (aka heredoc) using this syntax:

![image](https://cloud.githubusercontent.com/assets/43356/14420605/e8df4f46-ffc4-11e5-8a74-3ab0657b1be8.png)

But the following are not supported:

![image](https://cloud.githubusercontent.com/assets/43356/14420640/16de0734-ffc5-11e5-828f-4e134bb84441.png)
![image](https://cloud.githubusercontent.com/assets/43356/14420654/2e565f10-ffc5-11e5-9e73-e765b73ee56f.png)
![image](https://cloud.githubusercontent.com/assets/43356/14420686/55c2d0b0-ffc5-11e5-9db9-e0d135206c4f.png)

See the exact details about the [Here Documents at the Ruby Manual](http://ruby-doc.org/core-2.2.0/doc/syntax/literals_rdoc.html#label-Here+Documents) and also [other examples](http://makandracards.com/makandra/15003-how-to-ruby-heredoc-without-interpolation).

**Comment by aeschli** [comment] 2016-04-11 15:26
the <<HEREDOC syntax seems to work now (there has been a recent update).
But I can reproduce the issue for <<-'EXPECTED'

**Comment by aeschli** [comment] 2016-04-11 15:26
This issue was moved to textmate/ruby.tmbundle#96

**Comment by aeschli** [comment] 2017-02-21 22:51
Closing as the issue is in https://github.com/textmate/ruby.tmbundle

**Closed by aeschli** 2017-02-21 22:51 UTC
Labels: bug, upstream
