### ISSUE TITLE
Rainbow brackets bug

### ISSUE THREAD

**Issue by FMorschel** [microsoft/vscode#209435] opened 2024-04-03 12:18 UTC
Type: <b>Bug</b>

Add this to a .dart file:

```
class A {
  @override
  String toString() => '${ {} }';
}
```

There is a Dart string interpolation that shows an explicit map/set.

The first opening bracket is showing red and the seciond to last one (the last one on line 3) is showing blank.

VS Code version: Code - Insiders 1.88.0-insider (57028e3d274ebde851c7cc02123def372ca619a6, 2024-04-03T04:43:57.217Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.22GB free)|
|Process Argv|--crash-reporter-id 15414217-e08c-4dfd-812d-8a5c20e4b31f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vsc-export|asl|1.2.0
path-intellisense|chr|2.8.5
dart-code|Dar|3.86.0
flutter|Dar|3.86.0
vscode-markdownlint|Dav|0.54.0
xml|Dot|2.5.1
gitlens|eam|14.9.0
vsc-material-theme-icons|equ|3.5.0
duplicate|gee|1.0.2
copilot|Git|1.177.801
copilot-chat|Git|0.14.2024032901
cloudcode|goo|2.7.0
selected-lines-count|gur|1.4.0
vscode-auto-open-markdown-preview|hnw|0.0.4
flutter-intl|loc|1.19.3
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|6.2.2
vscode-docker|ms-|1.29.0
vscode-kubernetes-tools|ms-|1.3.16
remote-containers|ms-|0.353.0
vsliveshare|ms-|1.0.5918
awesome-flutter-snippets|Nas|4.0.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.34.0
vscode-thunder-client|ran|2.20.3
vscode-yaml|red|1.14.0
data-size-count|Thi|1.1.1
pdf|tom|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
gee8j676:30988845
gd77d436:30999572

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-04-05 03:25
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by FMorschel** [comment] 2024-04-07 14:32
Thanks for the support! I found that `Dart-Code.Dart-Code` has an issue. I'll file it there!

**Comment by DanTup** [comment] 2024-04-07 16:32
@gjsjohnmurray I'm the author of the Dart extension and it's not clear to me how to fix this. The issue seems to be with VS code's bracket colouring, but it's not clear to me how it decides which brackets match. The "Inspect Tokens" popup shows taht both brackets are the same colour (I guess this occurs before the bracket colouring):

<img width="759" alt="Screenshot 2024-04-07 at 17 27 25" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/c4e7a2e4-4f20-4240-abc4-741ccd1dc41a">
<img width="755" alt="Screenshot 2024-04-07 at 17 27 34" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/6ca29c02-511c-4a69-8879-06e0c21ac179">

My suspicion is that maybe the "Standard token type" is impacting this, but I can't find any description of how VS Code is matching brackets. Do you know where I can find the rules for this?

**Comment by RedCMD** [comment] 2024-04-07 18:58
yes `Standard token type` disables bracket matching
also have a look at `"unbalancedBracketScopes"` under `"grammars"`

**Comment by DanTup** [comment] 2024-04-08 11:11
@RedCMD thanks! I made some progress, but I'm having problems with strings nested inside expressions. I believe it may be because the standard token type for nested strings is not working as I'd expect.

Here, I have a string inside an interpolation expression inside a string. Both the outer and inner token types are mapped to "string", but the applied token is "other" (which is for only the "middle" token):

![image](https://github.com/microsoft/vscode/assets/1078012/94ac3822-15cf-43ce-8b47-0aeddafe7122)

Do you know what is wrong? I need to be able to exclude bracket matching for strings inside interpolation expressions inside strings, without disabling for the interpolation expression.

**Comment by FMorschel** [comment] 2024-04-08 12:13
I'm not completely sure if this is the same, but this talk got me curious and I tested it with python as well since the syntax is close enough.

Here is my code:

```py
dic = {1: 2}
keys = dic.keys()

#interpolated string test
print(f'The value is {dic[1]}\n{{1: 2}} -> {keys}.')

1.0.truncate()
print(f'Is even: {1.0.truncate()}')

print(f'Testing {{1:2}.keys()}')
```

<details>

<summary> Screenshot </summary>

![View inside vscode](https://github.com/microsoft/vscode/assets/52160996/0bf64ddd-75c9-4ea5-b66e-59db7b8abcc9)

</details>

I'm not completely sure if this should work but since the `truncate` method works, I do believe that there is a problem here as well. 

Now, my question here would be if this is a problem with the Python extension as well (or even Python as a whole as I will explain in my next paragraph). It also gives me an error in the last line `SyntaxError: f-string: single '}' is not allowed` and paints every character (but the opening and closing brackets) inside the string interpolation with the same colour as it's painting my string.

Both examples can also be seen in the code block above. Where the `{{1:2}}` string inside the first print has `{1:2}` painted with the same colour and the last line can't be painted right since it has an error.

**Comment by DanTup** [comment] 2024-04-08 14:03
I don't know much about Python so I don't know what's wrong there, but the highlighting generally looks correct to me. I tried something similar in TypeScript and it seemed to work - however I was unable to figure out _why_ it works there and it doesn't work for Dart.

I think my colouring issue is due to the Standard Token type being wrong, but I don't know why it's selecting the middle of three scopes, when either side (the outermost and the innermost) are the ones I want.

**Comment by FMorschel** [comment] 2024-04-08 19:37
FYI I created the (already closed) issue above and the above error was a mistake I made because the colour parsing in Python from the extension was a little misleading as well (filed https://github.com/microsoft/vscode-python/issues/23203 to solve it), but it doesn't have any relation to the problem. I'm sorry.

**Comment by RedCMD** [comment] 2024-04-08 22:22
I haven't used `"tokenTypes"` before
there's also `"balancedBracketScopes"`
the scopes `comment`, `string` and `regex` disables brackets
`meta.embedded` clears the standard token

**Comment by FMorschel** [comment] 2024-04-09 00:21
The thing that bugs me the most is that if the code is stationary and I first install the extension it works just fine. It only starts giving out the error after I restart vscode or introduce a new element to it or something.

> * Clean VSCode install (or at least uninstall `dart-code.dart-code` it and restart vscode)
> * Install the latest pre-release (v3.87.20240402) or the latest release (v3.86.0)
> * Add this to a .dart file:
> 
> ```
> class A {
>   @override
>   String toString() => '${ {} }';
> }
> ```
> 
> * See that everything works
>   ![Code without bug](https://private-user-images.githubusercontent.com/52160996/320289997-b3d73df2-24cb-4406-bfd6-62b2029544cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjIyNTUsIm5iZiI6MTcxMjYyMTk1NSwicGF0aCI6Ii81MjE2MDk5Ni8zMjAyODk5OTctYjNkNzNkZjItMjRjYi00NDA2LWJmZDYtNjJiMjAyOTU0NGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAwMTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjAwZmM2YWUxODY4ZTE0MTZjYjRkMzkyYmQ3ZTNkZmUxMThjMjYzNWI4NjJkNjVlMGFlM2U3OGQ4ZTlhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V538ZZMzKluTdhmSihyloEuFKheDh7meT1aAXNeFXWo)
> * Restart vscode
> * See bug:
>   ![Code with visual bug](https://private-user-images.githubusercontent.com/52160996/320289820-8b8b8a39-5210-4d9a-aeea-6e1c028e993c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjIyNTUsIm5iZiI6MTcxMjYyMTk1NSwicGF0aCI6Ii81MjE2MDk5Ni8zMjAyODk4MjAtOGI4YjhhMzktNTIxMC00ZDlhLWFlZWEtNmUxYzAyOGU5OTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAwMTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGJjNWJjYTIzOTI2ZDJhYjFkYWZmNDQzMDQyYjMwZDM1Y2UyNmU1NzE2YWU5MDEzOWMwNzgwMDg4ZmRiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AmrNH0Hk3ZmIlxUI-ANsTfJnjPKjhO44NQKWRTZNhbA)

**Comment by DanTup** [comment] 2024-04-09 10:15
> maybe the order is based on the "tokenTypes" order?

I tried swapping them but it didn't make any difference. I also tried re-listing the ones I want in `balancedBracketScopes` but they seemed to be ignored when also inside the unbalanced scopes.

I think it's going to be difficult to fix this without some clear rules from VS Code about how this works.

**Comment by DanTup** [comment] 2024-04-09 16:16
I managed to get closer with this:

```
"grammars": [
	{
		"language": "dart",
		"scopeName": "source.dart",
		"path": "./syntaxes/dart.json",
		"tokenTypes": {
			"string.interpolated.double.dart": "string",
			"string.interpolated.single.dart": "string",
			"string.interpolated.triple.double.dart": "string",
			"string.interpolated.triple.single.dart": "string",
			"string.quoted.double.dart": "string",
			"string.quoted.single.dart": "string",
			"string.quoted.triple.double.dart": "string",
			"string.quoted.triple.single.dart": "string",
			"string.interpolated.expression.dart string.interpolated.double.dart": "string",
			"string.interpolated.expression.dart string.interpolated.single.dart": "string",
			"string.interpolated.expression.dart string.interpolated.triple.double.dart": "string",
			"string.interpolated.expression.dart string.interpolated.triple.single.dart": "string",
			"string.interpolated.expression.dart string.quoted.double.dart": "string",
			"string.interpolated.expression.dart string.quoted.single.dart": "string",
			"string.interpolated.expression.dart string.quoted.triple.double.dart": "string",
			"string.interpolated.expression.dart string.quoted.triple.single.dart": "string",
			"string.interpolated.expression.dart": "other"
		},
		"unbalancedBracketScopes": [
			"string.interpolated.expression.dart string.interpolated.double.dart",
			"string.interpolated.expression.dart string.interpolated.single.dart",
			"string.interpolated.expression.dart string.interpolated.triple.double.dart",
			"string.interpolated.expression.dart string.interpolated.triple.single.dart",
			"string.interpolated.expression.dart string.quoted.double.dart",
			"string.interpolated.expression.dart string.quoted.single.dart",
			"string.interpolated.expression.dart string.quoted.triple.double.dart",
			"string.interpolated.expression.dart string.quoted.triple.single.dart"
		]
	}
],
```

This works for expressions inside strings.. however is only handles two levels. If you put a string inside an expression inside a string inside an expression, then it doesn't work. I don't feel I should need to put `"string.interpolated.expression.dart string.interpolated.double.dart"` because I feel like the most-specific rule should match.

I also get the impression that we can't use `balancedBracketScopes` to re-enable bracket matching for an expression inside something in `unbalancedBracketScopes` (which is very limiting).

I feel like it should be possible to have scopes like this:

```
var a = "{}    ${  "{}   ${  "{} ${1 + 2}"  }  "   }    ";
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expression
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
                         ^^^^^^^^^^^^^^^^^^^^ expression
                             ^^^^^^^^^^^^^ string
                                 ^^^^^^^^ expression
```

And have all of the parts where the inner-most scope is "string" excluded from bracket matching, but all the parts where the inner-most scope is "expression" included. However I am unable to make anything like that work.

**Comment by RedCMD** [comment] 2024-04-09 18:28
I would just use the scopes `string` and `meta.embedded` in the TextMate grammar to disable and renable bracket matching
and not worry about `"tokenTypes"`

**Comment by DanTup** [comment] 2024-04-10 13:10
Hmmm, it seems like that works but I don't really want to change all of the scopes for a grammar that is used by editors other than VS Code. I don't understand why I can't change the names of the scopes and provide these scope names in `package.json` to get the same behaviour.

**Comment by DanTup** [comment] 2024-04-10 13:22
I thought maybe the issue was having "string" in "string.interpolated.expression.dart", however it seems like "meta.embedded" has some special handling beyond what can be done in `package.json`. If I use `meta.embedded` then everything is fine. If I change it to `"danny"` and add:

```
"tokenTypes": {
	"danny": "other"
}
```

Then it does _not_ work. Adding it to `balancedBracketScopes` also does not help.

I even tried:

```
"tokenTypes": {
	"danny": "other"
},
"embeddedLanguages": {
	"danny": "dart"
}
```

Which seems like it should work based on the text at https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#:~:text=Token%20types%20and%20embedded%20languages, but it doesn't.

I guess I'll go with `meta.embedded` for now, but I feel like it should be possible to do this without using those specific scopes based on that text.

**Comment by DanTup** [comment] 2024-04-10 14:26
@FMorschel I've fixed the Dart issue (https://github.com/Dart-Code/Dart-Code/issues/5061), you can probably close this one. I filed a bug about the above, but for now I'm just changing the scopes (I may change them back if that issue is responded to before my fix is shipped).

**Closed** 2024-04-10 14:30 UTC
