### ISSUE TITLE
Allow multiple keybindings for an action

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode#95547] opened 2020-04-17 16:37 UTC
This is a feature of Intellij, for example I can have `ctrl+n` and `command+n` bound to the same thing. I would like to be able to do  this in vscode as well. intellij only supports 2 so I wouldn't expect more from vscode. This is largely because I spend my days working on mac, but also have windows/linux machines.

**Comment by IllusionMH** [comment] 2020-04-17 16:47
You can add any number of shortcuts for same command to `keybindings.json`.
If needed you can narrow it further to OS using `when` condition https://code.visualstudio.com/docs/getstarted/keybindings#_conditional-operators

**Comment by xenoterracide** [comment] 2020-04-17 17:01
so the 1 keybinding is a limitation of the UI? could that be remedied?

**Comment by usernamehw** [comment] 2020-04-18 09:00
It is limitation of UI. Duplicate of #45244

**Closed** 2020-04-20 09:31 UTC
Labels: *duplicate
