### ISSUE TITLE
[folding] in scss fails when there are multiple properties in a rule that does string interpolation

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46734] opened 2018-03-27 17:52 UTC
Testing #46535

Folding fails in the second rule below

```
/* rule names with variables */
.orbit-#{$d}-prev {
  #{$d}-style: 0;
  foo-#{$d}: 1;
  #{$d}-bar-#{$d}: 2;
  foo-#{$d}-bar: 1;
}
```

See [Interpolation in scss](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_)

Below case work fine
```
/* rule names with variables */
.orbit-#{$d}-prev {
  #{$d}-style: 0;
}
```

**Comment by aeschli** [comment] 2018-03-28 21:03
duplicate of #46738

**Closed by aeschli** 2018-03-28 21:03 UTC
Labels: bug, css-less-sass, editor-folding
