### ISSUE TITLE
SegFault Error on startup

### ISSUE THREAD

**Issue by yaa110** [Microsoft/vscode#56466] opened 2018-08-15 11:58 UTC
- VSCode Version: 1.26 (.tar.gz x86_64)
- OS Version: 4.17.14-arch1-1-ARCH x86_64 GNU/Linux
- npm version: 6.3.0
- node version: v10.8.0

Steps to Reproduce:

1. Update to v1.26
2. Run to get error of `./bin/code: line 35:  4996 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-08-15 12:18
Duplicate of https://github.com/Microsoft/vscode/issues/55934

**Closed by bpasero** 2018-08-15 12:18 UTC
Labels: electron-2.0.x-update, extensions
