### ISSUE TITLE
Vscode does not start a separate instance when different --user-data-dir is passed

### ISSUE THREAD

**Issue by ymolists** [Microsoft/vscode#42514] opened 2018-01-30 17:13 UTC
- VSCode Version: code-insider-1.20.0-1517305900
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. run in one terminal `./code-insiders --verbose  --user-data-dir /tmp/vscode/000`
2. run in another terminal `./code-insiders --verbose  --user-data-dir /tmp/vscode/001`

Nothing happens. And the logs on term 1 console shows that vscode tried to use the same instance

Does this issue occur when all extensions are disabled?: NA

This [comment](https://github.com/Microsoft/vscode/issues/42503#issuecomment-361644476) explains what was the original intent

**Comment by Tyriar** [comment] 2018-01-30 18:35
`--user-data-dir` will only work for the first instance of vscode by design.

**Comment by ymolists** [comment] 2018-01-30 18:37
why on earth close the ticket ? there is a functionality that is 1) documented somewhere else to be what i am expecting and 2) is a clear need. Please don't just close the ticket and push it on someone else plate here :(

**Comment by Tyriar** [comment] 2018-01-30 19:25
@ymolists I closed it as you're suggesting a feature/change which we will not implement. `--user-data-dir` was created to enable running as root and portable installs. It was not made to allow running of multiple main processes.

**Comment by ymolists** [comment] 2018-01-30 19:34
@Tyriar there is an option in gihub to actually reword the title. Is that all it takes to reopen this ?

**Comment by Tyriar** [comment] 2018-01-30 19:42
@ymolists it is a much larger change than you likely envision to support launching multiple main processes and we generally discourage the user of `--user-data-dir` unless you absolutely need it. We are trying to keep the amount of issues down to those that are actively being considered as it's difficult to manage several thousand with our small team.

**Comment by ymolists** [comment] 2018-01-30 19:47
Duly noted. I am assuming this already came up and was closed as a no op because of the Hefty amount of engineering required. In the future it would help if you just say that this is a no-fix please take a look at this issue why we decided to not fix this. It helps people like me with absolutely no context or the experience you have :) I am assuming this was already debated elsewhere !

**Comment by weinand** [comment] 2018-02-01 11:52
I've verified that the following works on macOS but not on linux:
```
sardinia:~ weinand$ code --user-data-dir ./tmp/A
sardinia:~ weinand$ code --user-data-dir ./tmp/B
```

**Comment by bpasero** [comment] 2018-02-01 14:06
@Tyriar @joaomoreno do we prevent this on Linux for some reason?

**Comment by joaomoreno** [comment] 2018-02-01 14:31
Not that I am aware of... It should work.

**Comment by joaomoreno** [comment] 2018-02-01 14:32
[This might be related to `XDG_RUNTIME_DIR`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L24). @weinand is that variable set in your system?

**Comment by joaomoreno** [comment] 2018-02-01 14:33
If confirmed, I suggest to do it similarly to Windows: [hash the userDataPath and use that for the sockets paths](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L31).

**Comment by weinand** [comment] 2018-02-01 14:57
@joaomoreno yes, both Ubuntu 16.04 and 17.10 have a variable XDG_RUNTIME_DIR defined. This seems to be the default since I didn't change my environment in any way.

**Closed** 2018-02-08 15:33 UTC
Labels: bug, linux, os-integration
