### ISSUE TITLE
VSCode 1.66.x is too slow in comparison to 1.67.0-insiders

### ISSUE THREAD

**Issue by Zx-EvM** [microsoft/vscode#147612] opened 2022-04-18 03:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:

Stable:
```
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043
```
Log for stable: https://pastebin.com/raw/B5BKrRQE

Insiders:
```
Version: 1.67.0-insider (user setup)
Commit: a9288be67bab4e9c4dbe62207f01fafc2bdaadcb
Date: 2022-04-15T05:16:11.219Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```
Log for insiders: https://pastebin.com/raw/vZTa4PwV

- OS Version: Windows 10 Pro 21H1 19043.1645

Steps to Reproduce:

1.
2.

The short video that shows reproduce of the issue: https://user-images.githubusercontent.com/20873402/163747425-b5ac7123-66ec-4696-a208-3a1b9a93e48f.mp4

Also there is always some kind bug on running stable version. You can see it on the video. The bugs appears since 1.66.0 but not reproduce in 1.67.0-insiders at all.

**Comment by dalisoft** [comment] 2022-04-18 08:57
@Zx-EvM 
Related issue (and maybe duplicate?)
- https://github.com/microsoft/vscode/issues/147188#issuecomment-1094725853
- https://github.com/microsoft/vscode/issues/147211

**Comment by Zx-EvM** [comment] 2022-04-18 09:50
@dalisoft I don't see any non usual high CPU usage in my experience as described in issues. But I surely see the lags on start and it's take very long time in comparison to insiders version.

**Comment by lorand-horvath** [comment] 2022-04-19 08:36
@Zx-EvM Your report is a duplicate of https://github.com/microsoft/vscode/issues/146737
You can keep using the Insiders 1.67 until it's official in May, or revert to 1.65.2

**Comment by deepak1556** [comment] 2022-04-19 08:43
Merging to https://github.com/microsoft/vscode/issues/146683

**Closed by deepak1556** 2022-04-19 08:43 UTC
