### ISSUE TITLE
Integrated terminal can not be opened,on path contains chinese char

### ISSUE THREAD

**Issue by zwq00000** [Microsoft/vscode#9024] opened 2016-07-10 11:01 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Ctrl+` open intergrated terminal 
2.terminal window flash and closed

The project parent directory contains Chinese ，like  

> c:\projects\经验教训库\webapp

rename this folder ,terminal can been opend  success. like
> c:\projects\Expriences\webapp

**Comment by Tyriar** [comment] 2016-07-11 17:53
Duplicate of #7727

**Closed by Tyriar** 2016-07-11 17:53 UTC
