### ISSUE TITLE
Annoying "random" padding popping in terminal panel

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#97795] opened 2020-05-14 09:30 UTC
There is a weird behavior where a padding is added when interacting in some ways (resize, switch panel, open/close editor).

![vsc](https://user-images.githubusercontent.com/9438102/81917921-1b31a600-95d6-11ea-91ed-7377705c6d5b.gif)

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment] 2020-05-14 12:40
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

/label "needs more info"

**Comment by inwardmovement** [comment] 2020-05-14 15:12
If by _trying to reproduce_ you mean something like this:
![vsc](https://user-images.githubusercontent.com/9438102/81951876-010fbc00-9606-11ea-895e-52fff0d1dc8c.gif)

Then it doesn't seem to reproduce in the Terminal.

**Comment by rzhao271** [comment] 2020-11-04 21:16
Duplicate of #97808

**Closed by rzhao271** 2020-11-04 21:16 UTC
Labels: bug, integrated-terminal
