### ISSUE TITLE
Temporarily Closeable Workspace Folders

### ISSUE THREAD

**Issue by utkumaden** [microsoft/vscode#73299] opened 2019-05-05 08:58 UTC
Many modern IDEs allow you to temporarily close some of the projects/folders in a workspace, which makes it easier to focus. Allow the user to temporarily close a folder, so it's removed from the source control list and push it to the bottom in the file list.

Another advantage of this is allowing the user to selectively load folders, increasing performance at start up. A user may want all related projects in their workspace, but not want to work on all, at all times.

**Comment by 1138-4EB** [comment] 2019-07-08 18:05
Possible duplicate of #63963.

**Closed** 2019-10-09 19:11 UTC
Labels: *out-of-scope, feature-request, workbench-multiroot
