### ISSUE TITLE
vscode colors inconsistently loading in webviews

### ISSUE THREAD

**Issue by AnyaHunt** [Microsoft/vscode#72172] opened 2019-04-11 23:58 UTC
- VSCode Version: 1.33.0 **This issue ONLY began happening after I upgraded to 1.33.0**
- OS Version: Windows 10 - Version 1803 (OS Build 17134.648)

Steps to Reproduce:

1. Create an extension that has webviews
2. Launch extension in debugging mode
3. Load webview
4. vs-code colors are missing from the html style tag in the iframe (see image)
5. Change themes with the webview open to refresh the variables (see image)
6. However, in debugging mode, closing and opening the webview again does not fix it

**This issue ONLY began happening after I upgraded to 1.33.0**

When first opened:
![WebviewBugBroken](https://user-images.githubusercontent.com/49539354/56003279-b7bea180-5c7a-11e9-9d9b-b52edad93824.png)

After changing themes to another one and back:
![WebviewBugFixed](https://user-images.githubusercontent.com/49539354/56003291-c86f1780-5c7a-11e9-9371-413fea7cce29.png)

When the extension is compiled and installed, other developers report it fails to load the first time, but closing and opening the webview again refreshes it.

Does this issue occur when all extensions are disabled?: Yes/No
Cannot test as webviews are part of the extension

**Comment by mjbvz** [comment] 2019-04-12 18:52
Duplicate of #71741

Please try using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Closed by mjbvz** 2019-04-12 18:52 UTC
