### ISSUE TITLE
Search kinda broken, automatically selecting current line when text is highlighted

### ISSUE THREAD

**Issue by markainick** [microsoft/vscode#60521] opened 2018-10-10 14:40 UTC
- VSCode Version: 1.28.0 (1.28.0)
- OS Version: macOs Sierra 10.12.6

After the update to Version 1.28.0 (1.28.0) when text is selected and using Find, the line is automatically highlighted and the search doesn't work as expected since it's only searching in the line where the cursor is. This is getting really tedious, since I usually select text->copy->find->paste the text. I could not reproduce this on a Windows installation.

Example: https://i.imgur.com/0zG0cEa.mp4

Steps to Reproduce:
1. select text
2. Find CMD+F

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment] 2018-10-10 20:46
@markainick can you please check if setting `editor.find.autoFindInSelection` is set to `true` somehow?

**Comment by markainick** [comment] 2018-10-10 20:56
Yes it is, I set it to false and it works just like before the update. So basically the line is automatically highlighted if `editor.find.autoFindInSelection` is set to true

**Comment by rebornix** [comment] 2018-10-11 18:49
yup, that's the expected behavior of `editor.find.autoFindInSelection` which will use your selection as the search scope.

**Comment by LorisZ** [comment] 2018-10-12 07:20
Before the September patch (1.28) it behaved differently. It only searched inside the selection (with editor.find.autoFindInSelection enabled) when more than one line was selected. Now every time you find something, you can't search anything new without first deselecting the found text:

1. you search a text.
2. It's found.
3. You search a new text.
4. It only searches it inside the last result.

Not sure if intended, but it's quite annoying most of the time. And it's definitely not the way it behaved before the patch.

**Comment by Spongman** [comment] 2018-10-16 23:38
the find-in-selection checkout should be **disabled** when the selection is single-line _even_ when `autoFindInSelection` is checked.

**Comment by markainick** [comment] 2018-10-19 15:58
@egamma @rebornix shouldn't this be reopened?

**Comment by Spongman** [comment] 2018-10-22 19:22
yeah, `ctrl-f3` is broken now
- enable `autoFindInSelection`
- open a text document
- select a single word
- `ctrl-f3`

recently it started enabling the 'find in selection' checkbox in this case (it didn't before, correctly) which breaks this use case. the `find in selection` checkbox should _only_ be automatically enabled if the selection is multi-line.

**Comment by rebornix** [comment] 2019-10-23 21:56
/duplicate of https://github.com/microsoft/vscode/issues/64513 and let's track it there, we may need a richer autoFindInSelection option.

**Closed** 2019-10-23 21:56 UTC
Labels: *duplicate, editor-find, under-discussion
