### ISSUE TITLE
Unable to create new profile

### ISSUE THREAD

**Issue by hahavenn** [microsoft/vscode#224788] opened 2024-08-05 09:10 UTC
Type: <b>Bug</b>

1. Click "Manage" button
2. Pick "Profile Default"
3. Pick "New Profile"
4. Remove one of checkboxes
5. Showed up warning-hint "The profile should contain at least one configuration"
6. Enter profile name
7. Choose "Copy from: Default"

Then try to check any of checkboxes, it doesn't checking. Button "Create" also doesn't work. Hint doesn't close

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

---

The workaround as @gregrobson pointed out please set in your settings
"workbench.experimental.enableNewProfilesUI": true

**Comment by hahavenn** [comment] 2024-08-05 09:11
Also want to mention - i don't have any other profiles, only default

**Comment by hahavenn** [comment] 2024-08-05 09:37
https://github.com/user-attachments/assets/ea5c7b5a-b2f3-4b0a-aacb-f048a629e641

here is video of this bug

**Comment by iYadavVaibhav** [comment] 2024-08-05 12:12
Experiencing the same issue after update. I am on Mac M2 with following details:

```yaml
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (4 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by silascript** [comment] 2024-08-05 12:30
same issue.

```yaml
版本: 1.92.0
提交: b1c0a14de1414fcdaa400695b4db1c0799bc3124
日期: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.6.41-1-MANJARO
```

**Comment by michael-bentz** [comment] 2024-08-05 20:24
Same issue.
```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (4 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.2.0
```

**Comment by acfatah** [comment] 2024-08-06 22:57
Me too.

```
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by Ssj003** [comment] 2024-08-07 02:40
Same issue.

```
Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by CitrinitaSoft** [comment] 2024-08-07 19:17
Same issue.

Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

**Comment by Tommy-Turner** [comment] 2024-08-07 20:23
Samesies

**Comment by Tommy-Turner** [comment] 2024-08-07 20:23
samesies

**Comment by gregrobson** [comment] 2024-08-07 20:37
If it helps anyone - I had no issue with creating a profile when I used the new Experimental New Profiles UI.

![image](https://github.com/user-attachments/assets/2439a9ac-c020-41a9-8cb2-f022b699a052)

![image](https://github.com/user-attachments/assets/6755655b-38b5-44a0-8a5c-09ff07c4ea56)

**Comment by gregmsanderson** [comment] 2024-08-07 22:19
@gregrobson Thanks! I wasn't aware they had added a new UI. That works for me too.

**Comment by Ssj003** [comment] 2024-08-08 02:43
@gregrobson Thanks! That works for me too!

**Comment by staylet** [comment] 2024-08-08 04:30
@gregrobson Thanks! It worked for me! 😃

**Comment by m-rm** [comment] 2024-08-08 06:03
I have the same problem. The new UI also doesn't work for me because pressing the "Create" button does nothing.

**Comment by duwejeferson** [comment] 2024-08-08 13:52
Same problem. Using WSL
Version: 1.92.0 (system setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by adstro** [comment] 2024-08-09 02:18
Use issue, new version of VSCode:

Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.2.0

**Comment by isidorn** [comment] 2024-08-09 08:52
Sorry about this. We are in the process of migrating to the new Profiles UI, and we introduced a regression to the older Quick Pick driven experience.

The workaround as @gregrobson pointed out  please set in your settings
`"workbench.experimental.enableNewProfilesUI": true`

That way you will use the new Profiles UI (that will be default in next Stable) and you should not see this issue.

**Comment by hahavenn** [comment] 2024-08-09 11:01
> Sorry about this. We are in the process of migrating to the new Profiles UI, and we introduced a regression to the older Quick Pick driven experience.
> 
> The workaround as @gregrobson pointed out please set in your settings `"workbench.experimental.enableNewProfilesUI": true`
> 
> That way you will use the new Profiles UI (that will be default in next Stable) and you should not see this issue.

Worked for me, thanks. Should i close issue?

**Comment by isidorn** [comment] 2024-08-09 12:53
No. Let's keep the issue open since it is still valid, and users might be hitting it.
But our Sept+ goal is to move everyone to the new Profiles UI. So putting `"workbench.experimental.enableNewProfilesUI": true` in your settings is the way to go.

**Comment by m-rm** [comment] 2024-08-09 13:22
> No. Let's keep the issue open since it is still valid, and users might be hitting it. But our Sept+ goal is to move everyone to the new Profiles UI. So putting `"workbench.experimental.enableNewProfilesUI": true` in your settings is the way to go.

But the new Profiles UI is also not working when trying copy from an existing profile.

**Comment by joaomoreno** [comment] 2024-08-12 07:06
> > No. Let's keep the issue open since it is still valid, and users might be hitting it. But our Sept+ goal is to move everyone to the new Profiles UI. So putting `"workbench.experimental.enableNewProfilesUI": true` in your settings is the way to go.
> 
> But the new Profiles UI is also not working when trying copy from an existing profile.

Can you clarify? I can't reproduce this issue in the new Profiles UI.

**Comment by m-rm** [comment] 2024-08-12 08:55
> > > No. Let's keep the issue open since it is still valid, and users might be hitting it. But our Sept+ goal is to move everyone to the new Profiles UI. So putting `"workbench.experimental.enableNewProfilesUI": true` in your settings is the way to go.
> > 
> > 
> > But the new Profiles UI is also not working when trying copy from an existing profile.
> 
> Can you clarify? I can't reproduce this issue in the new Profiles UI.

Sure, I recorded the problem:
![Animation](https://github.com/user-attachments/assets/fae70c6a-e4bd-4d43-884d-a3e4f7839391)

The create button does not work when I select a profile to copy. When I select "None" it's working fine.

**Comment by sergiecode** [comment] 2024-08-12 14:53
I have a clue!

If you do:
1. File -> Preference -> Setting 
2. Search workbench.experimental.enableNewProfilesUI
3. Enable the newmprofile UI

Using the experimental GUI you can "copy" the profiles. So, maybe with the experimental update they have broken the normal feature

**Comment by nbros** [comment] 2024-08-15 08:10
I also have the same issue creating a profile, even though I am trying to copy from a profile that does have settings, shortcuts and extensions configured. The checkboxes are not clickable (they reset to unchecked when clicked).
![image](https://github.com/user-attachments/assets/078a547e-d343-48e1-8271-28d727bd406a)

**Comment by quickdraw6906** [comment] 2024-08-16 03:48
Same issue as others. Using legacy UI, the checkboxes are greyed out with message "The profile should contain at least one configuration". Enabling the new UI allows me to set up the profile (from Python template or duplicate or straight up new profile) and clicking Create button goes through the motions, but then the Create button doesn't change and trying to close the UI prompts me to discard or save.

**Comment by jharopr** [comment] 2024-08-18 19:57
> Si ayuda a alguien: no tuve ningún problema al crear un perfil cuando usé la nueva interfaz de usuario experimental de nuevos perfiles.
> 
> ![imagen](https://private-user-images.githubusercontent.com/1911321/355979969-2439a9ac-c020-41a9-8cb2-f022b699a052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMTEyODIsIm5iZiI6MTcyNDAxMDk4MiwicGF0aCI6Ii8xOTExMzIxLzM1NTk3OTk2OS0yNDM5YTlhYy1jMDIwLTQxYTktOGNiMi1mMDIyYjY5OWEwNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTk1NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FlNmNjOWY1YTVkMjg4ZDNiYTkzMjRiZjg3ODA4ZDJjNjkxOGQxYzhiYWU1M2IxNmI0YmRiYWVmZjY1ZmRkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8g-1VbKxa1bEUZCo8_JxuQzX56uoS-yD4X-wOc73c1I)
> 
> ![imagen](https://private-user-images.githubusercontent.com/1911321/355980240-6755655b-38b5-44a0-8a5c-09ff07c4ea56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMTEyODIsIm5iZiI6MTcyNDAxMDk4MiwicGF0aCI6Ii8xOTExMzIxLzM1NTk4MDI0MC02NzU1NjU1Yi0zOGI1LTQ0YTAtOGE1Yy0wOWZmMDdjNGVhNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTk1NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM5OTM2ZGEzNGEwYzAzOTc1OTM1YzA1OTBmNjQwZjE5OWNiNDk3MmJkYzY5OTNlMjBkZDUxZmYzNzkwMDEzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G5rfPRAoxV9_k6OuQl3J5NDNz-ljrLKa1bO11clEI5Y)

great, it worked

**Comment by sandy081** [comment] 2024-08-18 20:08
@TylerLeonhardt I observe a behavioural change in the quick pick behaviour in the last milestone. I am not able to find out what caused this in quick pick component. I can only explain following

- When a checkbox is changed, following function is called
https://github.com/microsoft/vscode/blob/5a0335dcf3ffe79466b90d7c24923f3158fac81a/src/vs/workbench/services/userDataProfile/browser/userDataProfileImportExportService.ts#L435-L449
- This function updates the description of items and call following `update` function
https://github.com/microsoft/vscode/blob/5a0335dcf3ffe79466b90d7c24923f3158fac81a/src/vs/workbench/services/userDataProfile/browser/userDataProfileImportExportService.ts#L414-L417
- This function sets the items in the quick pick to update the description. 

🐛  This is triggering `onDidChangeSelection` event on quick pick with no items selected. This is causing all items to be deselected automatically. This is causing the bug.

Please take a look and let me know if there is something I should adopt as a consumer.

**Comment by HotariTobu** [comment] 2024-08-19 01:29
The issue can be reproduced with fewer steps.

![Animation](https://github.com/user-attachments/assets/d2ad58f4-6a9d-4437-8f12-fcde74640863)

```
Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

@gregrobson The new UI works well, thank you!

**Comment by sandy081** [comment] 2024-08-20 14:32
@m-rm I tried to reproduce the flow you demoed and it seems to work for me - I cannot reproduce the issue. Can you please file a new issue (because this is related to new UI) with exact steps to reproduce. Also share the default profile.

**Comment by mcalligator** [comment] 2024-08-23 19:52
> Hello! I am unable to create a new Profile that is copied from an existing custom Profile on the new Profiles UI. But choosing "None" or any profile templates work just fine.
> 
> I am using VSCode in WSL
> 
> [edit]: creating Profiles locally in VSCode works just fine, the issue arises on VSCode in WSL.
> 

When using **WSL**, copying an existing profile does not work in the **new Profiles UI** either.  However, here's a workaround:

1. Open a new instance of VSCode from a Command prompt (*not* a WSL terminal).
2. Create a new profile using the new Profiles UI by copying an existing profile.
3. Save this new profile.
4. Close VSCode.
5. Check any other instance of VSCode running from a WSL directory - this should now include the newly-created profile.
6. Configure the new profile as desired.

**Comment by navidmafi** [comment] 2024-08-24 12:00
This also affects editing existing profiles if that's relevant

But the experimental Profiles tab is refreshing and much more straightforward, while also working around the problem 😄

**Comment by sandy081** [comment] 2024-08-26 10:12
We will be shipping the new Profiles UI in next release (https://github.com/microsoft/vscode/issues/226600) which would be fixing this issue. Therefore closing this issue.

**Closed by sandy081** 2024-08-26 10:12 UTC
Labels: bug, regression, user-profiles

**Comment by miguelgargallo** [comment] 2024-09-05 13:22
Still can't

**Comment by navidmafi** [comment] 2024-09-05 14:58
@miguelgargallo 

Please add the following to your settings.json and check whether the issue persists

```json
  "workbench.experimental.enableNewProfilesUI": true,
```

**Comment by TSonono** [comment] 2024-09-06 06:26
Still doesn't work on 1.93.0, with and without the experimental parameter set. Worth noting that it works if I set "Copy from" to "None", but not when set to "Default". I have no prior profiles (except for the default one).

**Comment by isidorn** [comment] 2024-09-06 07:33
For users that still can not create profiles - can you please file a new issue? 
Thank you!

**Comment by cookopotamus** [comment] 2024-09-28 18:57
It's an issue with copying `Extensions` from existing profiles, it seems.
When I check `Settings`, `Keyboard Shortcuts`, `Tasks`, and `Snippets`, but uncheck `Extensions`... I'm able to successfully create a Profile from a Template (i.e. Node.js).
