### ISSUE TITLE
Cannot download extensions / proxy settings

### ISSUE THREAD

**Issue by Edus001** [Microsoft/vscode#25921] opened 2017-05-04 18:59 UTC
- VSCode Version: 1.11.2
- OS Version: x86_64 GNU/Linux (Ubuntu 16.04 LTS)

Hi, I'm afraid that other people have asked this, but I didn't find any solution yet. I am behind a proxy and I cannot download extensions. On the console windows ( 'Help -> Toggle Developer Tools) I can see the following message: 

extensionquery (failed) err::ERR_TUNNEL_CONNECTION_FAILED

And regarding the proxy settings I have the environment set correctly:

ftp_proxy=ftp://user:pass@proxyserver:8080/
http_proxy=http://user:pass@proxyserver:8080/
https_proxy=https://user:pass@proxyserver:8080/
socks_proxy=socks://user:pass@proxyserver:8080/

I tried programming the proxy settings in preferences but it doesn't help:

{
    "window.zoomLevel": -1,
    "http.proxyStrictSSL": false,
    "http.proxy": "http://user:pass@proxyserver:8080"
}

I have checked also with the last version of code-insiders but I haven't succeeded. 

Could anyone help me? Thank you in advance..

Steps to Reproduce:

1. Install visual code 
2. Program proxy preferences
3. try to download/find extensions

**Comment by grajesh2028** [comment] 2017-05-04 19:16
I am also having the same issue. I am using macOS Sierra, but same settings in windows working just fine.

**Comment by ugurozturk** [comment] 2017-05-04 23:23
#23164 looked same to me

**Comment by joaomoreno** [comment] 2017-05-05 06:28
Dupe of #22369

**Closed by joaomoreno** 2017-05-05 06:28 UTC
Labels: proxy, question
