### ISSUE TITLE
Cursor gets wrong offset through zoom-in/out

### ISSUE THREAD

**Issue by nocke** [Microsoft/vscode#26388] opened 2017-05-10 13:48 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|java|redhat|0.2.0|
|sass-indented|robinbentley|1.3.1|
|trailing-spaces|shardulm94|0.2.11|
|language-stylus|sysoev|1.6.0|
|vscode-react-native|vsmobile|0.3.2|
|markdown-pdf|yzane|0.1.7|;
---

Steps to Reproduce:

1. have a multi-line Text open in Editor. Use wrap mode. Cursor somewhere 1/3rd from left.
2. Add/remove a few characters.
3. Zoom In (enlarge / `ctrl-+`). Type a letter.

RESULT: Actual inserting is 10-15px further left, than the seeming cursor position: Here I typed three 'A' and didn't move the cursor after that... yet, the cursor seems 1¼ chars further right...

EXPECTED: correct Cursor position.

* Closing and reopening file doesn't heal.
* Effect ist stronger closer to the right side of the panel.
* I only noticed this bug in the last 1-3 releases, not before. (And I zoom quite a bit :)

![bug-3a](https://cloud.githubusercontent.com/assets/21154106/25901719/ea8acee2-3597-11e7-94c9-5cf2e590c035.png)

**Comment by alexandrudima** [comment] 2017-05-10 16:04
I just pushed a fix for this 2hrs ago :). Duplicate of #26151

**Closed by alexandrudima** 2017-05-10 16:04 UTC
