### ISSUE TITLE
Git repositories on Dev Drive are not detected

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#194528] opened 2023-09-30 06:20 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0-insider (4268e464763087044d0c1b5bdd37ebbe683cadfa)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. create a Dev Drive which is mounted to `$HOME\Repositories` and does not have a drive letter
2. create a directory `foo` at `$HOME\Repositories\foo`
3. clone a repo `bar` at `$HOME\Repositories\foo\bar`
4. open VS Code
5. set `git.repositoryScanMaxDepth` to 2
6. add `$HOME\Repositories` to the workspace

Expected: `bar` is detected as a Git repo in the source control view

Actual: 

![image](https://github.com/microsoft/vscode/assets/15714253/882d4988-3286-4225-baf4-7fb4e0e07957)

**Comment by lszomoru** [comment] 2023-10-03 13:23
@anthonyvdotbe, could you please implement the following steps:
1. Close all instances of VS Code Insiders
2. From the terminal run `code-insiders --log vscode.git:trace`
3. Open the folder/workspace that contains the repository
4. Share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)

**Comment by lszomoru** [comment] 2024-01-30 14:33
@anthonyvdotbe, apologies for not getting back to you on this. I have finally set up a Windows machine with a Dev drive (ex: D:\). I am able to successfully open git repositories from the Dev drive so I think that the problem might be related to the way the drive is mounted. Could you please share more details on how you have mounted the Dev drive? Thanks!

**Comment by anthonyvdotbe** [comment] 2024-01-30 17:01
>  I am able to successfully open git repositories from the Dev drive

Just to be clear: this issue is about VS Code automatically detecting Git repos, not about being able to open Git repos yourself.
Outside a Dev Drive, as soon as I open VS Code, all my Git repos are detected & opened automatically.
On a Dev Drive, no Git repos are detected. Only when I open a file in a Git repo is the repo detected & opened by VS Code.

> Could you please share more details on how you have mounted the Dev drive?

I ran the following in `Terminal (Admin)`:

>fsutil devdrv setFiltersAllowed "PrjFlt, WdFilter, bindFlt, wcifs"

and followed the [docs](https://learn.microsoft.com/en-us/windows/dev-drive/) to set up a Dev Drive:

![image](https://github.com/microsoft/vscode/assets/15714253/5f7acf89-b8f3-4e06-878f-2331e9f86eea)

Note that it doesn't have a Drive letter, and that it's mounted within my `$HOME` directory, both of which might play a role.

**Comment by lszomoru** [comment] 2024-01-30 20:02
> Just to be clear: this issue is about VS Code not automatically detecting Git repos, not about being able to open Git repos yourself.
Outside a Dev Drive, as soon as I open VS Code, all my Git repos are detected & opened automatically.
On a Dev Drive, no Git repos are detected. Only when I open a file in a Git repo is the repo detected & opened by VS Code.


Do you mind sharing a recording using https://gifcap.dev? Thanks!

**Comment by anthonyvdotbe** [comment] 2024-01-31 06:26
Outside Dev Drive / Expected: 
![Recording 2024-01-31 at 07 21 52](https://github.com/microsoft/vscode/assets/15714253/c3e8d78f-b7b0-4a92-a6d4-a6e71a099163)

Inside Dev Drive / Actual:
![Recording 2024-01-31 at 07 23 59](https://github.com/microsoft/vscode/assets/15714253/9c58e533-bd45-401d-a0c1-6f8615b94215)

**Comment by anthonyvdotbe** [comment] 2024-02-22 16:02
@lszomoru sure, setting it to -1 has the same behavior as setting it to 2: Git repositories are not detected

**Comment by lszomoru** [comment] 2024-05-30 10:25
@anthonyvdotbe, sorry for not getting back to you on this. I have set up a Dev Drive on my Windows machine that matches what you are having and I was still unable to reproduce the issue.

Then I went back through the issue logs and found that you also ran this command:
> fsutil devdrv setFiltersAllowed "PrjFlt, WdFilter, bindFlt, wcifs"

Ran the command, rebooted the machine and now I am able to reproduce the issue.  I will investigate the issue and get back to you.

**Comment by lszomoru** [comment] 2024-06-06 08:18
The fix is included in the lates VS Code Insiders release (version information below). Could you please validate it? Thanks!
```
Version: 1.91.0-insider (Universal)
Commit: 5f646b8e67a869ef33061085ffe0e377d5ba040c
Date: 2024-06-06T05:49:08.564Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

**Closed by lszomoru** 2024-06-06 08:18 UTC
Labels: bug, git, confirmed

**Comment by anthonyvdotbe** [comment] 2024-06-06 16:09
This is indeed fixed, thanks!

Version: 1.91.0-insider
Commit: 5f646b8e67a869ef33061085ffe0e377d5ba040c
Date: 2024-06-06T05:48:05.714Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by lszomoru** [comment] 2024-06-07 11:09
@anthonyvdotbe, thank you very much for your patience and sorry for the delay.
