### ISSUE TITLE
`editor.wordWrap` doesn't wrap, no way to resize SCM input view

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#203218] opened 2024-01-23 18:38 UTC
Testing #203025

Mac Sonoma 14.2.1

Expected that when turning on wordWrap I would be able to resize the SCM input field. 

![image](https://github.com/microsoft/vscode/assets/1487073/fcee3755-0a99-45e4-9561-8bbadb5de5f9)

* turn on `wordWrap` for `[scminput]` language type (per test plan instructions)
* write a very long commit message with spaces

result: now wrapping if I resize the view, no way to make the input box taller, no vertical scroll bar

**Comment by lszomoru** [comment] 2024-01-23 20:44
Duplicate of https://github.com/microsoft/vscode/issues/203114

**Closed by lszomoru** 2024-01-23 20:44 UTC
Labels: bug, scm
