### ISSUE TITLE
Welcome view should scroll

### ISSUE THREAD

**Issue by Tarocch1** [microsoft/vscode#93344] opened 2020-03-25 01:34 UTC
- VSCode Version: 1.43.2
- OS Version: win10 18362.592

Steps to Reproduce:

1. Expand the Opened Folders panel.
2. Expand the Outline panel.
3. Drag the Outline panel.
4. The two panels overlap.

![image](https://user-images.githubusercontent.com/15124068/77492485-a23a8b80-6e7b-11ea-8e09-dbd6c2b0e86b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2020-03-25 19:36
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Tarocch1** [comment] 2020-03-26 01:15
@isidorn 

![image](https://user-images.githubusercontent.com/15124068/77600198-1ccdde80-6f42-11ea-9814-58989cbe78fc.png)

**Comment by isidorn** [comment] 2020-03-26 10:54
Looks like an electron rendering issue. Aslo might be some layout
@sbatten and @deepak1556 on ideas

**Comment by sbatten** [comment] 2020-03-26 23:56
The welcome view (all of them) is not handling layout at all and they do not scroll by default. Should they scroll or should we set a minimum size for all welcome views?

**Comment by isidorn** [comment] 2020-03-27 10:20
Both solutions work for me. Scroll and minimum size. However not sure how to compute minimum size, since that can depend on contributions. Thus scroll seems like an easier solution.
@sbatten Let me know what you prefer and if you plan to look into this or should I.

Assigning to this milestone, since looks quite ugly.

**Comment by joaomoreno** [comment] 2020-03-31 14:13
Related: https://github.com/microsoft/vscode/issues/93910

**Comment by joaomoreno** [comment] 2020-04-01 10:38
@isidorn Can you verify once this is out?

**Closed** 2020-04-01 10:38 UTC
Labels: bug, layout

**Comment by isidorn** [comment] 2020-04-01 10:42
@joaomoreno yeah.
