### ISSUE TITLE
VSCode suggest imports from node_modules relative to file instead of using package module name

### ISSUE THREAD

**Issue by blackholegalaxy** [Microsoft/vscode#54254] opened 2018-07-13 11:40 UTC
- VSCode Version: 1.25.1 and previous version (updated to see if it fixed something but no)
- OS Version: MacOS latest version and Windows 10 pro 64
- typescript version: 2.7.2

## Steps to Reproduce:

1. Open a typescript project, for example angular one
2. Try to import a third party or angular module for example

The suggested import: 

![image](https://user-images.githubusercontent.com/11064123/42689684-65d320a8-866f-11e8-8551-35b591b4c39a.png)

=> `import { Component } from '../../../../../node_modules/@angular/core';`
`import { Store } from '../../../../../node_modules/@ngrx/store';`
`import { UUID } from '../../../../../node_modules/angular2-uuid';`
`import { Subscription } from '../../../../../../../node_modules/rxjs';`

Our tsconfigs:

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "./",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@testUtils/*": ["src/app/tests/testUtils/*"],
      "@core/*": ["src/app/core/*"]
    }
  }
}

```

`tsconfig.app.json`:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [],
    "paths": {
      "@testUtils/*": ["app/tests/testUtils/*"],
      "@core/*": ["app/core/*"],
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts",
  ]
}
```

### Extensions off
Does this issue occur when all extensions are disabled?: Yes

## Additional information

This doesn't occur on webstorm, which suggests imports properly. This started to occur within last month along with VSCode updates.

I tried to change the importModuleSpecifier to test all available settings of` "javascript.preferences.importModuleSpecifier"` which is auto by default. Even after VSCode restart, it doesn't change anything.

**Comment by superamadeus** [comment] 2018-07-13 15:17
I'm experiencing the same issue.

**Comment by FromTheCodeCave** [comment] 2018-07-13 16:20
I'm also experiencing the same issue even when all the extensions are disabled. I started noticing this a couples weeks backs and adjusted the paths. Our project doesn't specify rootDir/rootDirs configuration in the tsconfig.json. If there is something I can help out with or test, please reach out.

**Comment by ipap85** [comment] 2018-07-14 06:53
I also experienced a similar issue immediately after updating to 1.25.0.
In a React project, VSCode kept auto replacing my imports with paths from my user folder node_modules (and opened all this files in 'unsaved' state). 
This did not affect all imports though, it was replacing the same specific libraries.
I temporarily reverted to 1.24.1 where it is ok.

**Comment by mjbvz** [comment] 2018-07-16 17:57
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)

**Closed by mjbvz** 2018-07-16 17:57 UTC
