### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by churchs19** [Microsoft/vscode#16219] opened 2016-11-29 14:28 UTC
- VSCode Version:
Version 1.8.0-insider (1.8.0-insider)
`4721762a2ac1e21f1e33094e810d4888052f3d8d`
2016-11-29T07:03:09.021Z
- OS Version: Mac OS X 10.11.6

Steps to Reproduce:

@joaomoreno I'm seeing this error, `end of central directory record signature not found,` attempting to update any extension today. 

The relevant portion of my user settings is:

`    "http.proxy": "http://localhost:3128/",
    "https.proxy": "http://localhost:3128",    
    "http.proxyStrictSSL": false,`

The localhost proxy is a Cntlm authentication proxy (https://sourceforge.net/projects/cntlm/) to our NTLM corporate proxy.

I'm not seeing any network requests in the VS Code developer tools window, so I'm unsure of what might be causing this. If I break in net.js at line 729 where the call to createWriteReq() starts, I get the following `data` parameter on Beautify (for example - it's similar on all other extensions):

`"{"id":50,"type":0,"channelName":"extensions","name":"installFromGallery","arg":[{"id":"697255a9-3f36-44c8-b084-d3b91edfb23a","name":"beautify","version":"0.6.2","date":"2016-11-28T04:23:10.43Z","displayName":"beautify","publisherId":"901b401e-7657-4a33-8c9a-0854c569607e","publisher":"HookyQR","publisherDisplayName":"HookyQR","description":"Beautify code in place for VS Code","installCount":339711,"rating":4.625,"ratingCount":24,"assets":{"manifest":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Code.Manifest","readme":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Content.Details","download":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.VSIXPackage?install=true","icon":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Icons.Default?redirect=true","iconFallback":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Icons.Default","license":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Content.License"},"properties":{"dependencies":[],"engine":"^1.6.0"}},true]}"`

Opening the `download` URL in that parameter in my browser downloads the zip file successfully.

Also referenced this issue in https://github.com/Microsoft/vscode/issues/2384#issuecomment-263580095.

**Comment by joaomoreno** [comment] 2016-11-29 16:39
This just started happening today? Was it working before?

**Comment by churchs19** [comment] 2016-11-29 19:06
Prior to today, it had been working, although it had been a week since I had last used it due to the Thanksgiving holiday.

**Comment by antmanler** [comment] 2016-11-30 02:15
The same problem

**Comment by lafe** [comment] 2016-11-30 07:44
Same problem here. The issue started appearing yesterday as well; last Wednesday the update worked. I am also behind a corporate proxy which is added in the User Settings.

**Comment by joaomoreno** [comment] 2016-11-30 08:15
Is everyone on OSX?

If you try [this build](https://az764295.vo.msecnd.net/insider/287a5deb91f7025ee8d737cde856e608f57da5e5/VSCode-darwin-insider-unsigned.zip) from roughly a week ago, does it still work?

**Comment by flam182** [comment] 2016-11-30 08:46
Hi, same problem on linux Mint. I am also behind an enterprise proxy

**Comment by melito00** [comment] 2016-11-30 08:53
I have same problem on Windows7. I am befind a proxy. This issued occured from yesterday.

**Comment by lafe** [comment] 2016-11-30 09:16
I have the problem on Windows Server 2008 R2. Is there an insider build for Windows from one week ago that I can try?

**Comment by joaomoreno** [comment] 2016-11-30 10:26
[Here's an old Windows build](https://az764295.vo.msecnd.net/insider/4ac353bfb3c3598338dad6ce8e162c67650cf2cc/VSCode-win32-1.8.0-insider.zip).

**Comment by lafe** [comment] 2016-11-30 11:37
Surprisingly, it also does not work. I see that there are currently five updated plugins but I cannot install them and get the "end of central directory record signature not found" error.
Debug console has the following trace stack (not sure if it helps):
```
messageService.ts:126end of central directory record signature not found: Error: end of central directory record signature not found,    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules\yauzl\index.js:98:14,    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules\yauzl\index.js:342:5,    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules\fd-slicer\index.js:32:7,    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)e.doShow @ messageService.ts:126
extensionHost.ts:291[Extension Host] ApplicationInsights:Sender Array[1]
```

To check this issue, I downloaded the build, renamed the old installation folder and put the older build in a new folder with the same name (so c:\Program Files (x86)\Microsoft VS Code Insiders contains only the contents of the archive). I did not change the personal settings or configuration files stored in my personal Users folder.

**Comment by joaomoreno** [comment] 2016-11-30 11:47
@hamenon @modigrv Did something in the Marketplace change recently? `end of central directory record signature not found` means that the bits downloaded when fetching the VSIX aren't really a `.zip` archive.

**Comment by bastiannijboer** [comment] 2016-11-30 12:58
Same here.. I'm behind a corporate proxy as well and I'm getting the same error.

**Comment by chuckhendo** [comment] 2016-11-30 13:29
Also just started getting this error on macOS 10.12, VSCode 1.8.0-insider. Also behind a corporate proxy.

Interestingly enough, this issue is NOT occurring in the non-insiders build, 1.7.2.

**Comment by bigbash** [comment] 2016-11-30 13:38
Also have this issue on Windows 10 with VSCode 1.7.2 (ZIP download) behind corporate proxy.  

The VSCode 1.7.2 EXE installer works just fine however.

**Comment by JeCap** [comment] 2016-11-30 14:09
Same issue. 
Side-by-Side installation on win10 behind a corporate proxy.

VS Code Insider 1.8.0: `end of central directory record signature not found`
VS Code 1.7.2: works fine.

**Comment by joaomoreno** [comment] 2016-11-30 14:52
I've received confirmation that the Marketplace team is looking into the issue.

**Comment by lafe** [comment] 2016-12-01 07:11
Has something changed? Updates are working again on my machine without any change on my site.

**Comment by joaomoreno** [comment] 2016-12-01 07:21
The Marketplace team released an update to the service which should fix this for you guys. 👍 

At the same time, today's Insider build will also come with a fix for this.

Thanks for the reports!

**Closed by joaomoreno** 2016-12-01 07:21 UTC
Labels: bug, proxy

**Comment by flam182** [comment] 2016-12-01 08:10
Thanks, it's works now for me

**Comment by sandy081** [comment] 2016-12-08 16:22
Adding verified tag since one of the users confirmed it works. Thanks.

**Comment by churchs19** [comment] 2016-12-12 14:36
I can also confirm it works correctly now. Thanks for the quick response!

**Comment by xiaofengqinyu** [comment] 2017-04-20 09:02
I just get this error now,but it works just correctly yestoday.
