### ISSUE TITLE
Terminal doesn't show with VSCode 64bit

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#31335] opened 2017-07-24 16:59 UTC
- VSCode Version: 1.14.2 64bit
- OS Version: Windows 10 Creator Update

Steps to Reproduce:

1. Open VSCode 64bit
2. Toggle Terminal

![image](https://user-images.githubusercontent.com/27698189/28534825-39d363e6-70cc-11e7-98b0-eaae1e5f8397.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-07-24 17:02
Duplicate of https://github.com/Microsoft/vscode/issues/27915

**Closed by Tyriar** 2017-07-24 17:02 UTC
Labels: integrated-terminal, new release
