### ISSUE TITLE
File icons look strange after the update

### ISSUE THREAD

**Issue by Ksld154** [Microsoft/vscode#63191] opened 2018-11-15 05:56 UTC
After the update to 1.29.0, the file icons in OS explorer are all changed
but not in the way as release note says.

Here's the screenshot:
![default](https://user-images.githubusercontent.com/26498007/48532720-8238a680-e8dc-11e8-8c01-3dc415047708.png)
![2](https://user-images.githubusercontent.com/26498007/48532735-9086c280-e8dc-11e8-8162-6103225be625.png)

No matter I use big icon view or list icon view, all vscode related files show up with the same default icon,
and this new default icon isn't the same as the old one, they look so similar with the txt file icon. 
It really confused me a lot.
Is there any way to change the icon to the old default one?
Or is is possible to set "File icons per file type" as the release note says?

- VSCode Version: 1.29.0
- OS Version: Windows10 17763.55

Steps to Reproduce:

1. Just open the OS file explorer, then will see that the files icons are not correct

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment] 2018-11-15 13:31
Can you try changing the default app for the Python file, say from VS Code to Notepad, and then set it back to VS Code to see if it updated? Have you also tried restarting your computer? 

We’ve seen a lot of weird caching issues with Mac/Win file icons.

**Comment by misolori** [comment] 2018-11-15 18:35
Tried to repro and couldn't get the same results. I had v1.28.0 installed, set the default app to VS Code, and then upgraded VS Code to v1.29.0 but my icons didn't get updated until I did a reboot:

![image](https://user-images.githubusercontent.com/35271042/48573742-092c5580-e8c2-11e8-8e3f-cce7e0f339af.png)

Let me know if a reboot resolves this issue.

**Comment by Ksld154** [comment] 2018-11-15 18:48
I have tried to reboot my PC several times, but the icons still look the same.
I've also switch the default app to Codeblocks then switch back to VScode for both python and cpp files,
still the icons look the same

**Comment by misolori** [comment] 2018-11-15 19:05
What language is your Windows set to?

**Comment by Ksld154** [comment] 2018-11-15 19:14
Chinese(Taiwan)
I switched to English(United States) and did a reboot just now, but still didn't work.

**Comment by misolori** [comment] 2018-11-15 19:19
The last thing you can try is to re-install VS Code, and make sure you've selected "Register Code as an editor for supported file types".

**Comment by Ksld154** [comment] 2018-11-15 19:34
No, i wont re-install VScode because backup setting files will cost me too many time.
Some of my friends encounter the same trouble as i do,
so i think that it must have some bug in this version update.
Hope devs can figure it out soon. 
Anyway, thanks for you help, sir.

**Comment by cooper1x** [comment] 2018-11-16 01:34
Me too.

**Comment by misolori** [comment] 2018-11-16 01:53
@cooper1x can you post a screenshot and your app/os version?

**Comment by cooper1x** [comment] 2018-11-16 01:56
![image](https://user-images.githubusercontent.com/9080789/48592938-b3b97c80-e985-11e8-9152-695e44760eca.png)
![image](https://user-images.githubusercontent.com/9080789/48592952-bc11b780-e985-11e8-835b-65d9d565b323.png)
![image](https://user-images.githubusercontent.com/9080789/48592980-d5b2ff00-e985-11e8-838d-0e90d9c55802.png)

**Comment by misolori** [comment] 2018-11-16 02:06
@cooper1x those file icons look correct. What’s the problem that you’re seeing?

**Comment by cooper1x** [comment] 2018-11-16 02:16
![image](https://user-images.githubusercontent.com/9080789/48593629-9cc85980-e988-11e8-8f1e-cfccb3baea0c.png)
![image](https://user-images.githubusercontent.com/9080789/48593644-a8b41b80-e988-11e8-81d5-0afa70b1a2a5.png)
That was never the case before.

**Comment by misolori** [comment] 2018-11-16 02:21
I’m our [1.29.0 release](https://code.visualstudio.com/updates/v1_29#_updated-file-icons-per-file-type) we introduced these icons in the smaller view. What you are seeing is correct and by design.

**Comment by rti56kt** [comment] 2018-11-16 07:47
![image](https://user-images.githubusercontent.com/43367240/48605026-8afdab00-e9b6-11e8-8dc9-d83bf4e0409f.png)
My icons is also wired after the update. It really looks like a text file.

**Comment by Tim-Veestraeten** [comment] 2018-11-16 11:39
I have the same problem:
![image](https://user-images.githubusercontent.com/33923948/48619039-7eb82480-e99b-11e8-8420-a789b19b2662.png)

vs code version: 1.29.1
OS: Windows 10 64bit v 1803
OS language: Dutch (Belgium)

Is it possible this has something to do with the [file association bug in Windows 10](https://www.windowslatest.com/2018/11/09/microsoft-confirms-file-association-bug-in-windows-10/)? I can't change default file types and have the wrong icons on two different PC's.

**Comment by misolori** [comment] 2018-11-16 16:45
@Tim-Veestraeten thanks for the reminder of the file association bug. This is the same issue as #60716 so I'll close this issue since it's not a issue with vs code but with Windows.

**Closed by misolori** 2018-11-16 16:45 UTC
Labels: needs more info, new release
