### ISSUE TITLE
Incomplete intellisese menu after VSCode version 1.51.1

### ISSUE THREAD

**Issue by Flame12220** [microsoft/vscode#111149] opened 2020-11-22 23:16 UTC
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a C++ File (.cpp)
2. Create a public C++ class with at least two overloads of one member function with large variable names as parameters
3. Then create a object of this class and then try to access the member function you just created using the "." operator 
4. While doing this the intellisense menu will pop up and you wont be able to read the whole list of the function parameters which is just replaced with "...."

Does this issue occur when all extensions are disabled?: Yes

- I belive this error happened after the VSCode version:  1.51.1, installing an older version of VSCode shows that this had never happened before

- Version 1.51.1:
![Screenshot (5)](https://user-images.githubusercontent.com/32613923/99919836-26e9ec00-2d20-11eb-9f61-2104a15422ee.png)

- Version 1.50.1:
![Screenshot (4)](https://user-images.githubusercontent.com/32613923/99919855-39642580-2d20-11eb-9b98-9cf024176e46.png)

**Comment by jrieken** [comment] 2020-11-24 08:23
/duplicate of https://github.com/microsoft/vscode/issues/109937

**Closed** 2020-11-24 08:23 UTC
Labels: *duplicate, suggest

**Comment by JonWallsten** [comment] 2020-11-26 09:37
> /duplicate of #109937

@jrieken Is this really a duplicate of #109937? The issue is that the IntelliSense autocomplete box always has the height of one item even though multiple items exists. The ticket you linked to is related to the details view, not the list itself.
![image](https://user-images.githubusercontent.com/5993909/100333684-2f1d8200-2fd3-11eb-9425-0fb192067177.png)
![image](https://user-images.githubusercontent.com/5993909/100333729-3c3a7100-2fd3-11eb-8fca-7b696249d2a4.png)

**Comment by JonWallsten** [comment] 2020-11-30 08:34
https://github.com/microsoft/vscode/issues/110554
