### ISSUE TITLE
VS Code does not start sometimes

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/vscode#6137] opened 2016-05-05 19:02 UTC
Often I'll have Code open and then try to open a new file either through code.bat, "Open With Code", or even from the Start Menu and nothing will happen. I assume this has been reported several times before, but couldn't find anything as there are lots of issues reported here.

- VSCode Version: 1.0.0
- OS Version: 10.14335

Steps to Reproduce:
Not 100% sure of the steps to get this to happen every time
1. Have code running already with some files open (1 or more instances of it)
2. Right click on a file and select `Open with Code`
3. Nothing starts up - no additional `code.exe`s show up in Task Manager

![Task Manager when code is not working - only 1 window](https://cloud.githubusercontent.com/assets/1149244/15053789/126e454a-12b9-11e6-9382-92cf2350672c.png)

If I then close all of the active Code windows and try again, things work.
This means that I then lose my active files :(

**Comment by joaomoreno** [comment] 2016-05-26 14:25
This is somehow strange. Like the named pipe stops working.

Is your machine managed by some domain? Is there any thing special about it that comes to mind?

**Comment by joaomoreno** [comment] 2016-05-26 14:26
Actually closing as duplicate of #4921.

**Comment by Tadimsky** [comment] 2016-05-26 15:46
@joaomoreno I've been playing around with this a bit and I now believe it's due to the fact that I'll often start Code from an elevated command prompt.
Once I have it running elevated I can't stay any normal instances. 

My developer command prompt has to be run elevated and so when executing code <folder> from that prompt, I can't start Code again from start menu or from Windows explorer

**Comment by joaomoreno** [comment] 2016-05-26 18:35
Excellent, let me give that a try.

**Comment by joaomoreno** [comment] 2016-05-26 18:40
![image](https://cloud.githubusercontent.com/assets/22350/15585936/19f6ee14-2382-11e6-852f-4b83cf555c7f.png)

Got it! Good catch, @Tadimsky!

cc @bpasero

**Comment by joaomoreno** [comment] 2016-05-26 18:41
Alright, #4921 is definitely the same issue. Let's merge them, closing this one.

**Closed by joaomoreno** 2016-05-26 18:41 UTC
Labels: bug

**Comment by Tadimsky** [comment] 2016-05-26 18:43
Awesome!
