### ISSUE TITLE
Debugger stops after pressing F5 in AL, debugging for AL is broken in this version.

### ISSUE THREAD

**Issue by ArijetaI** [microsoft/vscode#181829] opened 2023-05-08 17:04 UTC
Type: <b>Bug</b>

Open VS Code, setup launch.json file to reach to a webclient, add some breakpoints, press F5.
Once when webclient runs in debugging mode, moving to the next breakpoint is not possible.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment] 2023-05-08 17:41
/duplicate of https://github.com/microsoft/vscode/issues/181485

**Closed** 2023-05-08 17:42 UTC
Labels: *duplicate, new release
