### ISSUE TITLE
Feedbacks about the paths autocomplete (v 1.8)

### ISSUE THREAD

**Issue by ggregoire** [Microsoft/vscode#17331] opened 2016-12-15 18:23 UTC
- VSCode Version: 1.8

Hey guys! I had a discussion on Hacker News with @mjbvz about this new feature.

I think the feature could be improved by copying what the extension [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) provides.

Some screenshots will speak for themselves. 

Here is the extension:

![screen shot 2016-12-15 at 11 20 11](https://cloud.githubusercontent.com/assets/591804/21234914/3e11a10e-c2ba-11e6-8e85-1b0d94a5299f.png)

![screen shot 2016-12-15 at 11 20 22](https://cloud.githubusercontent.com/assets/591804/21234917/41bcbd34-c2ba-11e6-91ae-5feec9f62ce1.png)

I didn't look at the code but I would bet that they detect when a string starts with `'./'` or `'../'` and then list the files and folders in the current or previous directory.

**IMO it's perfect and it's exactly what I expect from a paths autocomplete.**

For comparison, here is the native feature:

![screen shot 2016-12-15 at 11 21 11](https://cloud.githubusercontent.com/assets/591804/21234921/44982bb0-c2ba-11e6-9182-d19daee0d5a2.png)

![screen shot 2016-12-15 at 11 24 41](https://cloud.githubusercontent.com/assets/591804/21234925/46be00d6-c2ba-11e6-9925-353f34f36cd8.png)

![screen shot 2016-12-15 at 11 24 47](https://cloud.githubusercontent.com/assets/591804/21234927/4897d030-c2ba-11e6-8074-cec1030b8401.png)

My thoughts:

1) **Intellisense suggests a lot of things (paths, snippets, symbols in the current file, etc)!**

On this screenshot, the file contains few lines of code (it's the `./index.js` of the project) so the list of suggestions is relatively small. But I tried in another project, in a file with 300 LOC and a lot of symbols, and the list of suggestions was really too long.

The suggestion I was looking for was `components` which is the first folder of the project in alphabetical order. When I started typing, `components` was not in the first visible suggestions. Actually I had to type almost the full name of the folder, i.e. `'./compon'`, to get the suggestion.

2) **The 🔧  icon is not really intuitive.**

The extension uses a file icon. You could display a folder ( 📁 ) or a file ( 📄 ) in function of the suggestion.

--- 

Hope these feedbacks can help.

Thanks for the amazing work! 🙂

**Comment by mjbvz** [comment] 2016-12-16 23:16
Quick update on the the second issue. I just merged in a fix (#17434) to show both path and direcotry completions with a file icon instead of the generic icon:

![screen shot 2016-12-16 at 3 14 17 pm](https://cloud.githubusercontent.com/assets/12821956/21281534/73940aae-c3a2-11e6-9a4d-c22d5bcdd96e.png)

I'm also looking into using different icons for directories and files, but we need to make a change on the VSCode side to support a directory completion type (tracked by #17435).

**Comment by mjbvz** [comment] 2016-12-16 23:25
@ggregoire Can you please try setting `"editor.snippetSuggestions": "none"` and checking if you still see the unwanted completions in the paths? It looks like most of those suggestions may be coming from snippets, so this issue may be related to #1304

Thanks

**Comment by ggregoire** [comment] 2016-12-18 16:55
Thank for the update on the second issue. It was quick!

Yes this setting removes the snippets suggestions in the paths but I usually use these suggestions, so it's not really practical for me. :)

By the way, there are not only snippets suggestions in the list, there are also all the symbols used in the file:

![screen shot 2016-12-18 at 10 37 28](https://cloud.githubusercontent.com/assets/591804/21294959/7fa2990a-c50f-11e6-86ee-ee024597d328.png)

And actually, I'm not even sure the feature is working. I disabled all my extensions and I'm looking for the folder `Login` (same level that the current field):

![screen shot 2016-12-18 at 10 53 07](https://cloud.githubusercontent.com/assets/591804/21294980/571d370a-c510-11e6-9f72-bdf9cc9d734d.png)

On the previous screenshots, it seems like Intellisense proposed `config` in the suggestions only because there was a symbol `config` in the file.

**Comment by mjbvz** [comment] 2016-12-20 01:14
@ggregoire I'm unable to repo the extra completions showing when trying to complete `import foo from './|'`. If you do not have a `package.json`, the completing on an empty require path will fallback to those word based suggestions. 

A few other questions:

* Does the workspace have a `package.json` file?
* Does the workspace have a `jsconfig.json` file?
* If possible, can you please share a simple test project that shows this behavior

Thanks.

**Comment by mjbvz** [comment] 2017-01-04 19:50
Closing as I'm unable to reproduce the remaining problem. @ggregoire please let me know if you are still hitting this and I can investigate further.

**Closed by mjbvz** 2017-01-04 19:50 UTC
Labels: intellisense, javascript, needs more info, typescript
