### ISSUE TITLE
I cannot type Chinese Char in terminal

### ISSUE THREAD

**Issue by kicebeauty** [microsoft/vscode#117965] opened 2021-03-02 11:44 UTC
after updated to 1.53.2，however I cannot type any Chinese Char more，even ABC from Chinese inputmethod.

**Comment by xsro** [comment] 2021-03-04 01:11
是和这个Issue同样的问题：#115814

---

Duplicate of #115814

**Comment by meganrogge** [comment] 2021-03-04 22:01
Duplicate of #115814

**Closed** 2021-03-04 22:02 UTC
Labels: *duplicate, integrated-terminal
