### ISSUE TITLE
VS code cannot render markdown

### ISSUE THREAD

**Issue by umnovI** [Microsoft/vscode#59480] opened 2018-09-26 18:42 UTC
Issue Type: <b>Bug</b>

It cannot render extensions description and random markdown document.
Tried without extensions.

![image](https://user-images.githubusercontent.com/30232564/46100751-da073b00-c1d2-11e8-9bb0-68c46cbbadf0.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G    (2 x 2595)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.47GB (3.47GB free)|
|Process Argv|C:\Users\%User%\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apache|mrm|1.1.1
vscode-language-pack-ru|MS-|1.27.2
sublime-keybindings|ms-|4.0.0
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.1.2
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by mjbvz** [comment] 2018-09-26 18:45
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by umnovI** [comment] 2018-09-26 19:06
It doesn't.

**Comment by mjbvz** [comment] 2018-09-26 19:57
Thanks. Closing since this is fixed in insiders (or caused by an extension)

**Closed by mjbvz** 2018-09-26 19:57 UTC
