### ISSUE TITLE
Commit message Input will always show last commit memsage when I restart VSCode

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#138919] opened 2021-12-11 17:57 UTC
Version info:

```
Version: 1.64.0-insider (Universal)
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:13:44.798Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

Reproduce:

1. create an folder `vscode-issue-reproduce`
2. cd that folder and add a file `test.txt`
3. run `git init` and `git add -A` in terminal
4. write `first commit` to VSCode commit message input` and make a commit by click `√`
5. the commit message will disappear after commit success
2. restart VSCode, the commit message `first commit` show again

**Comment by gjsjohnmurray** [comment] 2021-12-11 19:07
/duplicate of #138834 and should be fixed in next Insiders.

**Closed** 2021-12-11 19:08 UTC
Labels: *duplicate
