### ISSUE TITLE
Show the action to reopen closed repositories in Source Control Repositories view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#203146] opened 2024-01-23 14:20 UTC
Testing #203035

One has to use command pallette to reopen closed repositories. As we are providing the capability of closing a repository and other repositories in SCM Repositories view, it is expected to also have the action to reopen them from the same place.

**Comment by lszomoru** [comment] 2024-01-26 09:34
Duplicate of https://github.com/microsoft/vscode/issues/197466

**Closed by lszomoru** 2024-01-26 09:34 UTC
Labels: feature-request, git
