### ISSUE TITLE
"Show Source" button on md preview throws error in 1.21

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#44783] opened 2018-03-01 00:36 UTC
- VSCode Version: Insiders dated 2/28
- OS Version: Any

Steps to Reproduce:

1. Open preview for a markdown file
2. Click on the "Show Source" button on the top right corner of the preview

**Expected**: The editor with the source of the md preview gets focus
**Actual**: Notification: `cannot open vscode-markdown-preview:2. Detail: no provider for vscode-markdown-preview:2`

Does this issue occur when all extensions are disabled?: **Yes**

This doesnt happen in 1.20

**Comment by mjbvz** [comment] 2018-03-01 00:46
Duplicate of #44523

**Closed by mjbvz** 2018-03-01 00:46 UTC
Labels: insiders, markdown
