### ISSUE TITLE
Unpleasant flow when installing dev container

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186285] opened 2023-06-27 09:17 UTC
Testing #186222

In an empty profile:

![Recording 2023-06-27 at 11 16 48](https://github.com/microsoft/vscode/assets/900690/d1442c3b-3456-4973-a008-454543d29513)

![image](https://github.com/microsoft/vscode/assets/900690/c07e9ac8-1871-4f0d-a957-dcda98cfcd41)

**Comment by bhavyaus** [comment] 2023-06-27 22:39
Dupe of: https://github.com/microsoft/vscode/issues/186374

**Closed by bhavyaus** 2023-06-27 22:39 UTC
