### ISSUE TITLE
Unsaved file content (at least on Linux x64)

### ISSUE THREAD

**Issue by peter-kehl** [microsoft/vscode#175007] opened 2023-02-21 20:16 UTC
Type: <b>Bug/Incomplete feature</b>

**Summary**
VS Code consistently shows an old version of a file (NOT based on any GIT revision). Linux tools show different version (content) of the same file.

**Quick elimination question:**
Does VS Code require "access times" on Linux filesystems? I have this turned off (but the "modified" file time is up to date, see `touch` below).
![image](https://user-images.githubusercontent.com/4270240/220461902-63fb3343-5b5c-4c80-920b-1e0b32757068.png)

**Search existing issues**
- YES, I've searched for: "Linux cached file", all pages (https://github.com/microsoft/vscode/issues?page=8&q=Linux+cached+file).

**When all extensions are disabled?**
- YES:
![image](https://user-images.githubusercontent.com/4270240/220447382-92e63f42-1e55-43c2-a01a-02179eb78379.png)

**Reproduce**
Unfortunately, reproducing this is extremely difficult:

This is happening in `Rust` programming language source (my fork https://github.com/coop-rs/rust), but I'm sure it's not Rust-specific, nor project-specific. Anyway, I've run `x clean`, which is Rust build cleanup:
![image](https://user-images.githubusercontent.com/4270240/220450077-0cdceb98-b791-4271-a5e9-8257a416cd96.png)

The pure source code takes `2.2 GBs` (excluding `.git/` and with no artifacts at all):
![image](https://user-images.githubusercontent.com/4270240/220470151-fc5d22c9-3208-4fb4-95e1-e6bb9b5405b1.png)

Hence, could you suggest steps for me to minimize/investigate this, please. Steps/tips with in-depth VS Code and Linux knowledge. As you can see below, I've done some investigation already, but no success yet unfortunately:

- I've rebooted:
![image](https://user-images.githubusercontent.com/4270240/220461313-b2e0db82-66fa-4425-bc5c-4f883d381cb0.png)
- I've `touch`-ed the offending file:
![image](https://user-images.githubusercontent.com/4270240/220461556-d1047e7c-3147-4c51-be0a-be56931c2f16.png)

I've run the following two commands show that the file, as from filesystem, doesn't contain "assert_covariance" function/text:
```bash
sed -n '27,38p;39q' /share/pkehl/GIT/rust/library/alloc/src/collections/btree/map.rs
grep assert_covariance /share/pkehl/GIT/rust/library/alloc/src/collections/btree/map.rs
```
Shell output is in the right terminal tab/panel:
![image](https://user-images.githubusercontent.com/4270240/220464266-4f825433-7cb4-4b89-8d9f-bc0ad157bc2c.png)

But VS Code (editor) shows extra code (see the previous screenshot, center panel, highlighted), the code being copied here:
```rust
#[allow(dead_code)]
fn assert_covariance() {
...
}
```
However, that was a temporary code (which I never committed to GIT), and which I'm pretty sure I've undone (possibly with `git checkout` or `git restore` instead of editing it in VS Code). But VS Code keeps showing the above obsolete file content.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.1.12-1-MANJARO
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2710)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.65GB (2.45GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by peter-kehl** [comment] 2023-02-21 21:41
Ignore until further notice. It may be my Linux/Manjaro. Once I know more, I'll update this ticket.

**Comment by peter-kehl** [comment] 2023-02-22 05:49
`~/.config/Code/User/settings.json`:
```json
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "extensions.ignoreRecommendations": true,
    "update.mode": "none",
    "files.watcherExclude": {
        "**/target/**": true
    },
    "lldb.showDisassembly": "never",
    "workbench.startupEditor": "none",
    "terminal.integrated.scrollback": 50000,
    "editor.cursorWidth": 10,
    "editor.cursorSurroundingLines": 3,
    "editor.unfoldOnClickAfterEndOfLine": true,
    "bracket-pair-colorizer-2.depreciation-notice": false,
    "workbench.activityBar.visible": false,
    "workbench.editor.wrapTabs": true,
    "editor.fontSize": 18,
    "terminal.integrated.fontSize": 18,
    "window.menuBarVisibility": "toggle",
    "editor.guides.bracketPairs": true,
    "security.workspace.trust.untrustedFiles": "open",
    "terminal.integrated.shellIntegration.enabled": true,
    "window.title": "${dirty}${activeEditorMedium}${separator}${rootName}${separator}${appName}",
    "workbench.experimental.editor.dropIntoEditor.enabled": false,
    "debug.console.closeOnEnd": true,
    "workbench.editor.tabCloseButton": "off",
    "git-buttons": {
        "commit": true
    },
    "workbench.colorTheme": "Default High Contrast",
    "editor.rulers": [
        100
    ],
    "workbench.colorCustomizations": {
        "editor.findMatchBackground": "#00FF00",
        "editor.findMatchHighlightBackground": "#008800",
        "editorRuler.foreground": "#303000",
        "statusBar.background": "#000000",
        "statusBar.noFolderBackground": "#000000",
        "statusBar.debuggingBackground": "#000000",
        "statusBar.foreground": "#ffffff",
        "statusBar.debuggingForeground": "#ffffff"
    },
    "debug.showBreakpointsInOverviewRuler": true,
    "editor.cursorStyle": "block-outline",
    "editor.renderLineHighlight": "gutter",
    "workbench.editor.highlightModifiedTabs": true,
    "rust-analyzer.typing.autoClosingAngleBrackets.enable": true,
    "editor.fontFamily": "'Source Code Pro', 'monospace', monospace",
    "telemetry.telemetryLevel": "off",
    "codetour.recordMode": "pattern",
    "codetour.customTourDirectory": "",
    "bookmarks.keepBookmarksOnLineDelete": true,
    "bookmarks.sideBar.expanded": true,
    "window.autoDetectHighContrast": false,
    "window.restoreFullscreen": true,
    "workbench.editor.enablePreview": false,
    "editor.wordWrap": "bounded",
    "BUFchronicler.ffmpeg-binary": "/usr/bin/ffmpeg",
    "chronicler.ffmpeg-binary": "/home/pkehl/GIT/present_markdown_reveal.js/all_args.sh",
    "chronicler.dest-folder": "${workspaceFolder}/.videos",
    "chronicler.recording-defaults": {
        "flags": {
            "c:v": "libx264rgb",
            "crf": 0,
            "color_range": 2
        },
        "fps": 4,
        "countdown": 3
    },
    "vscrof.directoryStyle": "Linux",
    "vscrof.storageFileTitle": "VsCode - Remember Open Files (vscrof)",
    "tab-groups.relativePaths": true,
    "tab-groups.saveGlobally": false,
    "editor.minimap.enabled": false,
    "sort-tabs.showStatusbarMessage": false,
    "errorLens.statusBarMessageEnabled": true,
    "errorLens.statusBarColorsEnabled": true,
    "errorLens.scrollbarHackEnabled": true,
    "rust-analyzer.cargo.unsetTest": [
        "alloc"
    ],
    "git.detectSubmodules": false,
    "statusBarCustomColor.primaryBkColor": "#000000",
    "statusBarCustomColor.secondaryBkColor": "#000000",
    "breadcrumbs.filePath": "on",
    "breadcrumbs.symbolPath": "last",
    "filePathBar.pathStyle": "relative",
    "vscode_custom_css.imports": [
        "file:///home/pkehl/GIT/scripts_and_configs/vs-code/custom-css/status_bar.css"
    ],
    "GitLink.defaultRemote": "origin",
    "line-length-checker.lineLength": 100,
    "editor.wordWrapColumn": 100,
    "git.openRepositoryInParentFolders": "always",
    "remote.autoForwardPorts": false
}
```

**Comment by lszomoru** [comment] 2023-12-07 11:13
@bpasero, do you mind taking a look at this, as this does not seem to be related to git. Thank you!

**Comment by bpasero** [comment] 2023-12-07 13:19
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by peter-kehl** [comment] 2023-12-07 18:29
And/or, please point out where the unsaved content is saved. People need to know this, for example when moving project directories to a new/different machine.

**Comment by peter-kehl** [comment] 2023-12-08 18:18
Thank you for explaining.

1. "obvious" - Then why didn't the previous assignee understand, or couldn't triage, this issue?
2. Older versions (`1.75`) did not show the white circle in the editor tabs. They showed the white circle only in the overall VS Code application name/title bar, and only if an unsaved file's editor is the active one. Plus, the overall application name/title bar is not visible in full screen.

I do see that Hot Exit has been developed for years. But `#2.` above documents how confusing it has been. Suggest adding a guideline to VS Code developers that when adding a major feature that is not well tested yet, they make it NOT enabled by default.

**Comment by bpasero** [comment] 2023-12-08 18:48
@peter-kehl the white circle on tabs to indicate unsaved editors has been around since 2015. I suggest you take a look at our intro videos where you can see the indicator too:

<img width="1105" alt="image" src="https://github.com/microsoft/vscode/assets/900690/961bf3bb-5a25-4185-9590-3e7dc16e9b72">

See https://code.visualstudio.com/docs/introvideos/codeediting

**Comment by peter-kehl** [comment] 2023-12-08 22:40
Summary of this comment: `#1.` the circle indicator in an editor tab (not the overall application bar) did NOT work as of `1.75.1`; `#2.` I do not request any changes to the existing functionality, but `#3.` I request this to be mentioned in Lessons Learned and/or Dev. Guidelines or similar.

1. The editor tab circle indicator did not show up in `1.75.1` (January 2023): https://code.visualstudio.com/updates/v1_75 > downloaded `code-stable-x64-1675893708.tar.gz` -> `/opt/VSCode-stable-1675893708/bin/code &` ->
![image](https://github.com/microsoft/vscode/assets/4270240/74fbc719-1703-400c-90a6-00a7348dde55)

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.7.0-1-MANJARO
Sandboxed: No
```
That, together with using Full Screen, gives bad surprises.

Even as-is, this feature, still gives bad surprises - because, if the user uses File -> Exit, or Ctrl+Q, to close VS Code, they may not learn about the unsaved change for long. While protecting unsaved work is beneficial, and is a part of other advanced IDE's, all other IDE's - common/good practice - notify the user of the fact early (for example, `vi`/`vim` notify the user on re-start).

Telling users to watch videos? No. Features on `stable` should follow common/good practice, or they should be disabled by default.

2. Of course, I'm not for any change to that now (it's too late).

3. But, I'm asking for that to be recognized as a part of good practice.

**Comment by bpasero** [comment] 2023-12-09 05:15
> I request this to be mentioned in Lessons Learned and/or Dev. Guidelines or similar.

So if I understand you correctly you expect our documentation to explain that the circle on an editor tab indicates unsaved changes?

**Comment by peter-kehl** [comment] 2023-12-09 11:24
> So if I understand you correctly you expect our documentation to explain that the circle on an editor tab indicates unsaved changes?

That's not what I asked for, but yes, that needs to be documented - if it's not already documented in general and/or in accessibility.

What I stated & asked for:
1. There was a period when there was no circle on an editor tab (see screenshot above). Do you agree or disagree?
2. That (missing circle on an editor tab) together with Full Screen has lead to bad user experience. Hours wasted.
3. Mistakes/incomplete features like that (missing circle) do happen, and will continue to happen, because we (including VS Code developers) are human.
4. Hence, requesting Lessons Learned and/or Dev. Guidelines (or similar) to mention not to enable new complex/non-trivial features by default, or at least not enabling them by default until they are tested as bullet-proof.

**Comment by bpasero** [comment] 2023-12-09 14:25
I have opened https://github.com/microsoft/vscode-docs/issues/6895 in our docs repository for the documentation part.

It is certainly possible that we had a bug that made the circle not show during that period we mention and I want to apologise if that caused confusion for you, that was really not our intent!

I still hope you can find some joy with using VS Code going forward.

Closing this issue as duplicate of the one mentioned above, have a nice weekend.

**Closed by bpasero** 2023-12-09 14:25 UTC
Labels: info-needed
