### ISSUE TITLE
Minimap in CSS files

### ISSUE THREAD

**Issue by Woogyloaf** [Microsoft/vscode#22792] opened 2017-03-17 13:46 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 8

Steps to Reproduce:

1. in CSS file select line. Go to mini map and move it slightly up or down.
Same happen with "[stylus](http://stylus-lang.com/)" files  

![minimap css](https://cloud.githubusercontent.com/assets/5297722/24045641/6e5a7834-0b28-11e7-95c3-821db08b951d.gif)

**Comment by Tyriar** [comment] 2017-03-17 20:01
@Woogyloaf can you elaborate a little? It's not clear what the issue is.

**Comment by Woogyloaf** [comment] 2017-03-17 22:50
Hello, Tyriar. 
1. Open terminal
2. Open big CSS file and select line of code ( + - In the middle ). 
3. Select Mini map and move it slightly down. 
- Vision section must jump.
- Video [http://recordit.co/X7fLHsPk1h](url)
This happen _**ONLY**_ if terminal is open. I have same problem with all type of files.

**Comment by alexandrudima** [comment] 2017-03-27 08:47
Duplicate of #22008

**Closed by alexandrudima** 2017-03-27 08:47 UTC
Labels: editor-minimap

**Comment by Woogyloaf** [comment] 2017-03-27 19:44
Thank you. Sorry for duplicate. i don't find it =\
