### ISSUE TITLE
[Feature Request] Different variants for date & time snippets

### ISSUE THREAD

**Issue by dnguye86** [Microsoft/vscode#43139] opened 2018-02-07 22:06 UTC
- VSCode Version: 1.20
- OS Version: Windows 7

For the following global snippets, it would be nice to add more variations in case the users don't want the default text displays.

- CURRENT_MONTH

- CURRENT_DATE

We could have used a CURRENT_MONTH_SHORT_LETTERS, where the month is "Feb" or CURRENT_MONTH_FULL_LETTERS, where the month is "February". For date, it would also be nice to have a different snippet to display single digit date.

I suppose we can expand this for time snippets as well. Suggestions & ideas are welcome!

**Comment by jrieken** [comment] 2018-02-26 15:42
dupe of #43140

**Closed** 2018-02-26 15:42 UTC
Labels: *duplicate, snippets
