### ISSUE TITLE
Startup time seems to have gotten much longer

### ISSUE THREAD

**Issue by nvonada** [Microsoft/vscode#36752] opened 2017-10-23 14:15 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.  Open code
2.  Wait.  An older (2-3 months ago) version of Code in one of my VM's loads in 3-4 seconds.  The current version Code on the physical machine takes 29 seconds.

Reproduces without extensions: Yes/No
Yes

**Comment by jrieken** [comment] 2017-10-25 08:12
Can you attach the readings from `F1 > Startup Performance` and can you also create a startup performance profile by starting like this `code --prof-startup`

**Comment by mklemarczyk** [comment] 2017-10-26 16:11
First start after system restart is extremely long.

**Comment by jrieken** [comment] 2017-10-27 08:16
Two issues here, (1) *extremely* slow starting of additional processes on your machine. It takes around 5seconds (blocking) to start the extension host, file watchers etc... and (2) it does take a long time to set the menus (which is noticeable given the horrible spawn times)

<img width="1206" alt="screen shot 2017-10-27 at 10 15 11" src="https://user-images.githubusercontent.com/1794099/32094354-c3991c10-baff-11e7-8c47-60e7886d0097.png">

<img width="898" alt="screen shot 2017-10-27 at 10 15 22" src="https://user-images.githubusercontent.com/1794099/32094355-c3b894aa-baff-11e7-88f8-729ac90d266c.png">

**Comment by jrieken** [comment] 2017-10-27 08:18
The slow spawning issue is tracked here #24884, the slow menu here #21964. I am closing this as a dupe of those two issues. Thanks for reporting!

**Comment by jrieken** [comment] 2017-10-27 08:18
You wanna tweak your AV software as have heard this might be the cause for this: https://github.com/Microsoft/vscode/issues/24884#issuecomment-294877147

**Closed by jrieken** 2017-10-27 08:18 UTC
Labels: freeze-slow-crash, needs more info, workbench

**Comment by mklemarczyk** [comment] 2017-10-27 14:42
@jrieken  I do not know about reporter, but I do not have AV other than built in Windows 10.
