### ISSUE TITLE
Searching for text that spans across multiple lines

### ISSUE THREAD

**Issue by HunderlineK** [Microsoft/vscode#40726] opened 2017-12-22 16:18 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro 64-bit Build 16299

Steps to Reproduce:

1. Add a text (string) that spans across multiple lines
```javascript
`This is a text that
spans multiple lines`
```
2. Search for a sub string that spans across multiple lines, e.g. `that spans`. The editor cannot find the text. This is useful for cases where you are searching for a hardcoded text in your codebase (a footnote, tooltip, etc.)

**Comment by weinand** [comment] 2017-12-22 17:25
In other text editors searching for "that spans" would not find anything either.
But there doing a regexp search with "that\sspans" works.

**Comment by alexandrudima** [comment] 2018-01-08 10:49
The OP issue, searching for `that spans` correctly yields no results.

---

Now, the curious case of `that\sspans` + regex mode:

Currently, `\n` must be present explicitly in the search text for our multi-line search mode to kick in.

The fact that a single `\s` in the search text doesn't bring the search in multiline mode is a duplicate of #9051 . The root cause is that we go into multiline search (where we create a large concatenated string of the entire buffer) only if there is sufficient evidence that the search query is multiline. We don't consider `\s` as sufficient evidence at this point.

**Closed by alexandrudima** 2018-01-08 10:49 UTC
