### ISSUE TITLE
Keybinding Discoverability for Zen Mode

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16723] opened 2016-12-06 19:58 UTC
Testing #15647 

Is there any way we can get cords added to the view menu - I think there was some blocking factor here.  I just worry users may struggle to work out the keybinding...

![image](https://cloud.githubusercontent.com/assets/1051190/20941436/2358c7ae-bbab-11e6-8f4b-c06f1184d846.png)

**Comment by isidorn** [comment] 2016-12-06 21:11
Agree - we should look into this, the issue is that we do not render chords in the menu

**Comment by joaomoreno** [comment] 2016-12-07 10:58
cc @bpasero

**Comment by isidorn** [comment] 2016-12-07 11:02
As @bpasero just informed me this is the limiation of electron that they only allow us to put 1 keybinding not 2. 
In the command pallete it is nicely rendered and it is also in our keybindinds - should help people figure out the keybinding.

Closing as tehre is nothign to be done and will work if electron allows us to put multiple keybindings in the future as we are doing everyhing we can on our side.

**Closed by isidorn** 2016-12-07 11:02 UTC
