### ISSUE TITLE
background prelaunchTask blocks launch

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [microsoft/vscode#136527] opened 2021-11-05 15:56 UTC
Issue Type: <b>Bug</b>

I have a background task defined like this:

```
{
            "label": "python dev server",
            "type": "shell",
            "command": "python3 dev_server.py",
            "isBackground": true,
            "problemMatcher": {
                "pattern": {
                    "regexp": ""
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "",
                    "endsPattern": "serving at"
                }
            },
        },
```

and a launch config:

```
{
            "name": "Debug in Chrome ",
            "type": "chrome",
            "request": "launch",
            "preLaunchTask": "python dev server",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceFolder}",
            "userDataDir": false,
            "disableNetworkCache": false,
        },
```

In the previous VSCode version, the browser and debugger were started immediately when the background process printed "serving at localhost:"

In the current version the browser and debugger never starts. I think this is a regression.

***

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 10, 7|
|Memory (System)|16.00GB (1.50GB free)|
|Process Argv|--crash-reporter-id 6c0f1725-6e9b-4c9e-9036-6687233bbc25|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by weinand** [comment] 2021-11-05 16:32
@alexr00 are you aware of any changes in task land that could explain this?

**Comment by alexr00** [comment] 2021-11-08 08:39
None that I'm aware of, and the background prelaunch task + launch configs for the extension samples are still working. 

@mmarczell-graphisoft can you share a minimal `dev_server.py` that can be used with your tasks and launch config to reproduce this issue?

**Comment by mmarczell-graphisoft** [comment] 2021-11-08 08:49
You can even use the builtin one in Python and still reproduce:

```
{
            "label": "python dev server",
            "type": "shell",
            "command": "python3 -m http.server 8000",
            "isBackground": true,
            "problemMatcher": {
                "pattern": {
                    "regexp": ""
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": " ",
                    "endsPattern": "Serving HTTP on"
                }
            },
        },
```

I'm also getting this strange error message:
![image](https://user-images.githubusercontent.com/72875131/140711594-b673f6b9-8ff4-4a99-a4a2-e696a88b3aa7.png)

**Comment by plateniteshow** [comment] 2021-11-08 09:42
I ran into this exact problem today and have no idea how to fix it (other than running tasks manually, which I'd prefer not to do). Looking forward for any workarounds or fixes...

**Comment by alexr00** [comment] 2021-11-08 10:03
Maybe a duplicate of https://github.com/microsoft/vscode/issues/136585, because in the example the line that we're problem matching against is the first line.

**Comment by alexr00** [comment] 2021-11-08 10:09
Yep, its a duplicate of https://github.com/microsoft/vscode/issues/136585.

**Closed by alexr00** 2021-11-08 10:09 UTC
