### ISSUE TITLE
Git decorations are wrong in the explorer

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#212054] opened 2024-05-05 16:21 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 22.6.0

Steps to Reproduce:

Saving a document after changing. It should now have the "M" next to it in the explorer to show that this file is modified.
This behavior does not work however. 
Sadly I can not make out any rules, it seems to be very random.

**Comment by runxel** [comment] 2024-05-31 14:22
> When you save the file, does the file appear in the "Source Control" view under "Changes"?

Yes it does, but it is missing a git decorator there too. So neither "M" nor "U" appear, but the file initself is visible under "changes".

**Comment by lszomoru** [comment] 2024-05-31 14:34
Could you check the value of the `git.decorations.enabled` setting? Thanks!

**Comment by runxel** [comment] 2024-05-31 14:37
It was on. I disabled and enabled it and... voilá this stupid trick helped here once more.
Now every file seems ot have a correct git decorator, in both source tree and changes.
I'll keep an eye on it; I wonder how this could gone corrupt?

**Comment by lszomoru** [comment] 2024-05-31 14:40
Yeah, it would be interesting to understand how you have gotten into this state. If you do not mind I will go ahead and close the issue but in case you are able to reproduce again please feel free to reopen it. Thanks!

**Closed** 2024-05-31 14:45 UTC
Labels: info-needed, git

**Comment by runxel** [comment] 2024-05-31 20:26
It happened again and I finally realized now how the state gets corrupted @lszomoru!
I have an external (proprietary) tool that writes binaries, but can also "transpile" them back into code (as a technical sidenote: that works because the code is just wrapped into a binary, it does not get touched).
In any case, whenever I use this tool and its output overwrites a file that already exists, VSC will now fail to generate git decorators. Only after turning the function off and on they are regenerated. Even if I modify a source file in VSC directly again it won't show a decorator.

**Comment by lszomoru** [comment] 2024-06-01 20:30
Very interesting. I am happy to investigate this further if you are able to reproduce this issue without the external proprietary tool. Please let me know if you can reproduce it without the tool. Thanks!

**Comment by runxel** [comment] 2024-06-02 14:31
Yes I can reproduce it very easily. Going to the folder in the terminal, opening a file with your favorite terminal editor (mine is "ne"), editing and saving the file. VSC will not show any git decorator.
Another reproducible issue: Some files are still marked as "untracked" (U) with a git decorator, even tho they have been tracked already.
Toggling the option helps here as well.
So it seems like there is a general problem that VSC does not refresh the git state properly.

**Comment by lszomoru** [comment] 2024-06-27 14:00
I have done the following and I am unable to reproduce the issue:
1. Installed `ne`
2. Opened a folder in VS Code
3. Opened a file in the editor
4. Used `ne` to edit the file. As soon as the file was saved switched back to VS Code and the decorator appeared correctly

**Comment by runxel** [comment] 2024-06-27 17:07
So what else can we try? This issue persists on my end and does not shown any signs of resolving.
What could be different in my VSC, that makes it act wrongly, and yours not?
