### ISSUE TITLE
infinity symbol in .less comments caused a crash, and now shows warnings

### ISSUE THREAD

**Issue by danwulff** [Microsoft/vscode#13304] opened 2016-10-06 17:35 UTC
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Include an infiniti symbol (value #x221e) in a block comment (.less file)
2. Try to tab the line over
3. Visual Studio Code process crashes (happened once, not repeatable by myself) OR Visual Studio Code gives the Warning "CSS parsing error at line __, char __: Unrecognized character ∞"

Since I have not yet had a problem with unicode symbols within .less comment blocks during compiling, it seems like the IDE should just ignore the odd unicode symbol within comments.

![screenshot](https://cloud.githubusercontent.com/assets/17821843/19162831/579ca788-8bae-11e6-8062-fe6fb934a29d.png)

**Comment by aeschli** [comment] 2016-10-17 14:31
@danwulff Can you add sample file here? I'm not able to reproduce. My guess it that it has to with the file encoding.

**Comment by danwulff** [comment] 2016-10-17 16:09
Ah. that would make sense. Let me know what you find.
[parallax-initialization.zip](https://github.com/Microsoft/vscode/files/533986/parallax-initialization.zip)
Lines 22 & 24

**Comment by aeschli** [comment] 2016-10-18 15:22
I was able to reproduce now, execption happens inside Emmet.
```css
/*  
0 -> ∞ */
```
Place cursor before '0', press Tab.

**Comment by ramya-rao-a** [comment] 2017-04-02 04:37
This doesn't repro for me in the latest VS Code

I tried with the file provided by @danwulff 

Something we did along the months must have fixed this.

Closing this now.

@aeschli @danwulff If you can still repro, please drop a comment and I can investigate further

**Closed by ramya-rao-a** 2017-04-02 04:37 UTC
Labels: bug, css-less-sass, emmet
