### ISSUE TITLE
Color Picker : Sass : File Extension not working

### ISSUE THREAD

**Issue by ScorpioCoding** [Microsoft/vscode#42931] opened 2018-02-04 16:44 UTC
- VSCode Version:  

    - Version 1.19.3
    - Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
    - Date 2018-01-25T10:36:34.867Z
    - Shell 1.7.9
    - Renderer 58.0.3029.110
    - Node 7.9.0
     - Architecture x64

- OS Version:   
    - Win 10 Pro
    - veriosn 1709
    - build 16299.129

![color-picker-sass-not-working](https://user-images.githubusercontent.com/20724826/35779767-c328cab0-09d2-11e8-94c9-d220ba4be1e8.PNG)

**Comment by usernamehw** [comment] 2018-02-04 17:18
Duplicate of https://github.com/Microsoft/vscode/issues/36724

**Closed** 2018-02-16 14:06 UTC
