### ISSUE TITLE
Moving a set of adjacent editor cursors does not move the editor's viewport to them 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9593] opened 2016-07-21 17:57 UTC
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:12:40.233Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

Steps to Reproduce:
1. Open large file
2. Add cursor somewhere
3. Add cursor down command
4. Scroll down with mouse
5. Press up, notice the viewport doesn't move. With a single cursor the viewport will go to the cursor.

Maybe this should be a special case for when cursors either can fit within the viewport and/or are all adjacent to each other?

**Comment by alexandrudima** [comment] 2017-11-24 15:13
Duplicate of #6995

**Closed by alexandrudima** 2017-11-24 15:13 UTC
Labels: editor-multicursor, feature-request
