### ISSUE TITLE
Ripgrep console error when started on a non-existing workspace folder

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#43579] opened 2018-02-13 11:22 UTC
Create a workspace description where the first workspace folder doesn't exist
```
{
	"folders": [
		{
			"path": "../bla-bla"
		}
	],
	"settings": {
	}
}
```
Check the console:
[Extension Host] [IPC Library: Search] spawn /usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg ENOENT (at /usr/share/code-insiders/resources/app/out/vs/workbench/services/search/node/searchApp.js:147:153)

**Comment by roblourens** [comment] 2018-02-14 01:14
/duplicate of https://github.com/Microsoft/vscode/issues/42219

**Closed** 2018-02-14 01:14 UTC
Labels: *duplicate, search
