### ISSUE TITLE
Git - Unstage selected ranges doesn't work 

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120928] opened 2021-04-09 12:32 UTC
- VS Code Version: 1.55.1
- OS Version: Windows 10 20h2

Steps to Reproduce:

This confusing if the option is visible in the menu and doesn't work.

![1](https://user-images.githubusercontent.com/17777237/114180379-68320f80-9940-11eb-864d-90e7806ab369.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pmatos** [comment] 2022-05-31 12:24
Interesting that nobody else has complained. I have noticed this as well and it's quite annoying.

**Comment by lszomoru** [comment] 2022-12-13 15:00
Closing this as duplicate of https://github.com/microsoft/vscode/issues/156748.

**Closed by lszomoru** 2022-12-13 15:00 UTC
Labels: bug, git
