### ISSUE TITLE
Have issue with top bar in Visual Studio for RTL language setup

### ISSUE THREAD

**Issue by mastermind-zubair** [microsoft/vscode#160112] opened 2022-09-05 16:40 UTC
Type: <b>Bug</b>

Hello there,
I have been using VSCode for very long time. However after recent update I got an issue in which my standard windows state buttons (maximized, minimized and close buttons Overlapping my top menu bar. I can't see them and I cant' use them using mouse, however I can access them through keyboard shortcuts

Steps to reproduce are
1. Install VSCode with following specs
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25193
Sandboxed: No

2. run the exe file. you can see it

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.25193
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.52GB free)|
|Process Argv|--crash-reporter-id c6487cbc-75a8-4212-87cb-2413fd368e04|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.2.0
numbered-bookmarks|ale|8.3.1
vscode-dbf|ape|0.1.2
atlascode|atl|2.10.12
insert-unicode|bru|0.13.3
simple-react-snippets|bur|1.2.6
turbo-console-log|Cha|2.5.1
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
apex-pmd|chu|0.5.9
font-preview|ctc|2.2.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.2.1
env-switcher|Eck|0.3.2
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|9.8.0
filter-line|eve|2.0.1
comment-anchors|Exo|1.9.6
php-intellisense|fel|2.3.14
lana|Fin|1.5.0
auto-close-tag|for|0.5.14
code-runner|for|0.11.8
copilot|Git|1.43.6621
gc-excelviewer|Gra|4.2.55
vscode-power-mode|hoo|3.0.2
compareit|in4|0.0.2
Angular2|joh|13.0.0
node-module-intellisense|lei|1.5.0
rainbow-csv|mec|2.4.0
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
vscode-edge-devtools|ms-|2.1.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
cpptools|ms-|1.12.4
hexeditor|ms-|1.9.8
live-server|ms-|0.4.0
vscode-react-native|msj|1.9.2
sqltools|mtx|0.24.0
php-docblocker|nei|2.7.0
material-icon-theme|PKi|4.20.0
quicktype|qui|12.0.46
vscode-data-preview|Ran|2.3.0
vscode-thunder-client|ran|1.18.7
typescript-hero|rbb|3.0.0
java|red|1.10.0
vscode-commons|red|0.0.6
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.10.1
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|55.8.0
salesforcedx-vscode-apex|sal|55.8.0
salesforcedx-vscode-apex-debugger|sal|55.8.0
salesforcedx-vscode-apex-replay-debugger|sal|55.8.0
salesforcedx-vscode-core|sal|55.8.0
salesforcedx-vscode-expanded|sal|55.8.0
salesforcedx-vscode-lightning|sal|55.8.0
salesforcedx-vscode-lwc|sal|55.8.0
salesforcedx-vscode-soql|sal|55.8.0
salesforcedx-vscode-visualforce|sal|55.8.0
code-spell-checker|str|2.7.2
unique-window-colors|stu|1.0.51
vscode-styled-components|sty|1.7.4
serverless-ide-vscode|Thr|0.5.34
vsfire|tob|1.4.1
pdf|tom|1.2.0
sfdx-package-xml-generator|Vig|2.0.8
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.2
vscodeintellicode|Vis|1.2.24
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.1
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.38.0
vscode-json-path|wei|2.4.0
vscode-import-cost|wix|3.3.0
bracket-lens|wra|1.5.3
ReactSnippets|xab|2.4.0
php-debug|xde|1.28.0
php-pack|xde|1.0.3
txt-syntax|xsh|0.2.0
json|Zai|2.0.2
php-intellisense|zob|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-09-05 17:47
/duplicate of #159813 where you can also find a setting to toggle that will work around this.

**Closed** 2022-09-05 17:48 UTC
Labels: *duplicate, triage-needed, new release
