### ISSUE TITLE
Can't change Terminal default shell to bash 

### ISSUE THREAD

**Issue by yigaldviri** [microsoft/vscode#83427] opened 2019-10-28 12:44 UTC
- VSCode Version: 1.39
- OS Version: MacOs 10.15

Steps to Reproduce:

1. Open the 'auto detect' tasks 
![image](https://user-images.githubusercontent.com/13430395/67678289-ed18ab80-f98e-11e9-9f9d-2c4f4a6743d8.png)
2. Choose one of the npm tasks and run

Result: `zsh:1: command not found: npm`.
![image](https://user-images.githubusercontent.com/13430395/67678120-7da2bc00-f98e-11e9-8f86-3956f5209771.png)

Tried to alter the setting.json to this:
```
    "terminal.integrated.shell.osx": "/bin/bash",
    "terminal.integrated.automationShell.osx": "/bin/bash"
```
And got: `/bin/bash: npm: command not found`
![image](https://user-images.githubusercontent.com/13430395/67678197-b478d200-f98e-11e9-8be9-576f4fc88631.png)

- When typing in the integrated terminal `echo ${SHELL}` I get `/bin/zsh` 
![image](https://user-images.githubusercontent.com/13430395/67679223-4b468e00-f991-11e9-8fb2-eb06ce51f670.png)

Does this issue occur when all extensions are disabled?: Didn't try

**Comment by yigaldviri** [comment] 2019-10-30 06:38
My system default shell is bash:
![image](https://user-images.githubusercontent.com/13430395/67834607-83181780-faf0-11e9-8913-0e37b778c507.png)

**Comment by alexr00** [comment] 2019-10-30 08:49
It looks like for tasks it's correctly using /bin/bash, but for some reason can't find npm. Can you open the developer tools in VS Code and run `process.env` in the console then share the value of PATH from that?

**Comment by yigaldviri** [comment] 2019-10-30 09:03
PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin".

For now, my workaround was to copy the content of my `.bash_profile` to  `.zprofile` but that's not something I would love to keep going on with.

**Comment by alexr00** [comment] 2019-10-30 10:28
Tasks run in a non-interactive non-login shell, so if VS Code doesn't have npm on the path that it can see, then neither can your task. 
There is some code that run and tries to make sure that VS Code has a good `env`, but for various reasons it doesn't always work. Looks like that's what you're hitting. @joaomoreno in case you want to investigate. Otherwise, duplicate of https://github.com/microsoft/vscode/issues/21655.

**Closed** 2019-10-30 10:28 UTC
Labels: *duplicate
