### ISSUE TITLE
Outline tree flashing at every character written

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode#84352] opened 2019-11-09 05:55 UTC
Issue Type: <b>Bug</b>

New this morning, after no apparent change in VS Code.
Editing a markdown file. At every character entered, the outline tree is deleted and recreated.
In the output panel, plenty of errors as the following appears:
```
[2019-11-09 06:43:48.733] [renderer1] [error] TreeError [OutlinePanel] Tree input not set: Error: TreeError [OutlinePanel] Tree input not set
    at Q.updateChildren (file:///C:/Users/Mario Valle/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1047:30)
    at e._doUpdate (file:///C:/Users/Mario Valle/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5269:515)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
spellright|ban|3.0.48
github-markdown-preview|bie|0.0.2
markdown-footnotes|bie|0.0.7
markdown-yaml-preamble|bie|0.0.4
vscode-toggle-quotes|Bri|0.3.2
refactorix|chr|0.3.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.1.2
vscode-great-icons|emm|2.1.47
vscode-todo-plus|fab|4.14.1
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.162
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.18.0
prettify-json|moh|0.0.3
notepadplusplus-keybindings|ms-|1.0.3
leaper|Onl|0.6.0
vscode-jscpd|pau|0.3.4
vscode-versionlens|pfl|0.24.0
bib|phr|0.3.0
vscode-javascript-booster|sbu|0.11.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.0
unique-window-colors|stu|1.0.51
highlight-matching-tag|vin|0.9.5
vscodeintellicode|Vis|1.2.0
highlight-bad-chars|wen|0.0.3
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by crystalfp** [comment] 2019-11-09 06:36
Some additional info.
1) I'm not sure to have edited any markdown file after 1.40.0 upgrade, so the problem could have started after the upgrade.
2) A reboot cleared the problem for few minutes, then it restarted.
3) The outline has "filter on type" and "sort: by position" checked
4) In explorer the workspace file list is collapsed, the outline is expanded

**Comment by gjsjohnmurray** [comment] 2019-11-09 08:13
Did you try running with all your extensions disabled in case it is being caused by one of those?

**Comment by jrieken** [comment] 2019-11-09 13:58
Does repo for me... @crystalfp Does the error persist? Is that related to specific markdown extension? Can you try disabling them as suggested?

**Comment by crystalfp** [comment] 2019-11-09 14:07
Let me arrive home and will check. Thanks!

**Comment by crystalfp** [comment] 2019-11-09 18:15
Seems the culprit is Spell Right. If I disable it, the Outline does not flash. The strange thing is that the error message in the Log (Window) panel makes no mention of this extension.
Opened as spell-right [issue 320](https://github.com/bartosz-antosik/vscode-spellright/issues/320#issue-520493205)

**Comment by crystalfp** [comment] 2019-11-09 20:30
Sorry, it seems a red herring. The problem appears even with Spell Right extension disabled, but depends on the kind of editing I'm doing. I will shortly prepare a reduced example that shows the problem.

**Comment by crystalfp** [comment] 2019-11-10 06:43
Strange, strange.

If I disable all extensions, the problem goes away. Then, if I reenable them except "Bracket Pair Colorizer" seems the problem is solved. Enabling it and the problem reappears. So this extension should be the culprit.

Not so fast. If I disable it again, the problem is back. If I disable all extensions except it, the problem does not appear.

At the end seems that disabling both "Bracket Pair Colorizer" and "Spell Right" solved the problem.
At the end I'm not inclined to make them guilty, due to the above incoherences, but seems some form of interaction between them and the latest VS Code version.

Thanks for helping!
mario

**Comment by HiEv** [comment] 2019-11-10 10:51
I have the same problem, and I don't use either of those extensions.

That said, the problem only occurs with one particularly long JavaScript file (13k+ lines of code and comments, 300+ functions).  No other files cause the problem where the "Outline" tree vanishes a brief moment after hitting one key, and then reappears a brief moment after hitting another key.  If I hit two keys in quick succession, then it does the same thing as hitting one.  (This happens even if I disable _all_ of my extensions.)

Based on this, I'd guess that there is some code which is expecting something to be done within a certain amount of time, and when it takes too long (because of the large amount of code), it's failing, thus causing the outline tree to get blanked out.  Then, the next time, the tree is empty, so it gets done in time, and the outline tree shows properly again.

Anyways, it's _really_ annoying, so if anyone has any ideas, a fix would be greatly appreciated.

**Comment by crystalfp** [comment] 2019-11-10 11:07
Yes! My markdown file is quite long. This is why I was not able to create a small example

**Comment by crystalfp** [comment] 2019-11-11 04:33
My markdown file: 2300 lines 256KB.
Strange enough, this morning with all extensions enabled, the problem does not reappear (for now). Maybe a good night sleep helped also VS Code :-)

**Comment by HiEv** [comment] 2019-11-11 04:37
> My markdown file: 2300 lines 256KB.
My JavaScript file is 566KB, so yeah, it looks like it's large files that are the problem.

> Strange enough, this morning with all extensions enabled, the problem does not reappear (for now). Maybe a good night sleep helped also VS Code :-)
It probably also depends on what other things you have running in the background, which could slow things down enough to cause the problem.

**Comment by jrieken** [comment] 2019-11-11 08:07
Can one you share those files with me?

**Comment by HiEv** [comment] 2019-11-11 10:30
> Can one you share those files with me?

[Here you go](https://qjzhvmqlzvoo5lqnrvuhmg-on.drv.tw/UInv/UniversalInventorySystem.js).

**Comment by jrieken** [comment] 2019-11-11 10:41
@HiEv Thanks! I could reproduce after the keystroke 😮

**Comment by jrieken** [comment] 2019-11-11 10:47
Alright, problem is that after 100ms we [show a message](https://github.com/microsoft/vscode/blob/46a6420b0bdf3d75e119706a0d2a6c9528684555/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L470) saying "Loading symbols..." and that resets the tree so that the subsequent update finds the tree in an unexpected state...

**Comment by jrieken** [comment] 2019-11-11 10:54
This was introduced with bcaa2be1b51441fd11685e599b2704908f25a6f2

**Comment by jrieken** [comment] 2019-11-11 10:56
This will be fixed in tomorrows [insider's build](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwin6Prl_-HlAhXKfMAKHcySC3YQFjAAegQICBAC&url=https%3A%2F%2Fcode.visualstudio.com%2Finsiders%2F&usg=AOvVaw0f8kL4zvRmKCp9_9q4hy9V)

**Comment by jrieken** [comment] 2019-11-11 13:56
Re-open so that we can cherry-pick this for the October Recovery release

**Closed** 2019-11-12 14:02 UTC
Labels: bug, candidate, outline
