### ISSUE TITLE
Support enum arrays in settings UI

### ISSUE THREAD

**Issue by znck** [microsoft/vscode#95186] opened 2020-04-14 06:26 UTC
A string array type in settings UI is already supported.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2596484/79192681-ccfa7d00-7e46-11ea-822b-f99ee459bdb6.png">

I request enum arrays are supported in a similar manner. Example schema from `znck.grammarly` extension:

```json
 { 
    "grammarly.emotions": {
          "markdownDescription": "**Experimental.** How do you want to sound?",
          "scope": "resource",
          "type": "array",
          "items": {
            "enum": [
              "neutral",
              "confident",
              "joyful",
              "optimistic",
              "respectful",
              "urgent",
              "friendly",
              "analytical"
            ],
            "enumDescriptions": [
              "😐 Neutral",
              "🤝 Confident",
              "🙂 Joyful",
              "✌️ Optimistic",
              "🤗 Friendly",
              "⏰ Urgent",
              "📊 Analytical",
              "🙌 Respectful"
            ]
          },
          "default": []
        },
}
```

**Comment by roblourens** [comment] 2020-05-17 22:47
Duplicate of https://github.com/microsoft/vscode/issues/77458

**Closed by roblourens** 2020-05-17 22:47 UTC
Labels: feature-request, settings-editor
