### ISSUE TITLE
“Visual Studio Code 3” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by daviadenisco** [microsoft/vscode#85071] opened 2019-11-18 21:14 UTC
- VSCode Version: 3
- OS Version: 10.15.1

Steps to Reproduce:

1. Download VS Code for macos
2. Drag VS Code to Applications
3. Click to open VS Code 3
4. Get message stating: “Visual Studio Code 3” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment] 2019-11-18 21:19
duplicate of https://github.com/microsoft/vscode/issues/74782

**Closed by egamma** 2019-11-18 21:19 UTC
