### ISSUE TITLE
Failed to install VS Code update. Unable to execute file Code.exe

### ISSUE THREAD

**Issue by lrayze** [Microsoft/vscode#54406] opened 2018-07-16 17:05 UTC
- VSCode Version: 1.25.1
- OS Version: Windows 10 64 bits Version 1803

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2198626/vscode-inno-updater.log)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by TomSputz** [comment] 2018-07-17 11:52
Duplicate of #47841 - At the moment the most common cause seems to be malwarebytes preventing code from properly updating - this has been fixed in the latest update, so if you use malwarebytes check that you're running the latest version

**Comment by joaomoreno** [comment] 2018-07-17 16:49
@lrayze Let me know if @TomSputz's solution helps.

**Closed** 2018-07-17 16:48 UTC
Labels: install-update
