### ISSUE TITLE
A question about line_length_linter

### ISSUE THREAD

**Issue by Cobbybaby** [microsoft/vscode#123526] opened 2021-05-11 00:36 UTC
Hi
Thank you for your tools. I am trying to use it, but i have a problem about it . I  use R in vscode, when the line has more than 80 characters , it will  throw a note with a wavy line : Lines should not be more than 80 characters. line_length_linter.  But i do not find  it in lint for R to chage it.  Moreover , in the setting.json, I do not know the name of parameter configuration though i  search it in the internet. Do you help me?

**Comment by mjbvz** [comment] 2021-05-11 04:30
Duplicate of #123528

**Closed by mjbvz** 2021-05-11 04:30 UTC
