### ISSUE TITLE
task completion notifications

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#142871] opened 2022-02-11 19:07 UTC
I currently use the [ZSH plugin bgnotify](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/bgnotify) to receive OS notifications when a long running terminal command completes. This allows me to do something else while rebuilding or running tests without having to constantly check to see when they finish. However, since the VSCode task runner apparently doesn't load a full shell environment this plugin only works if I use the built-in terminal. It would be great if the task runner had built-in support for sending OS notifications when tasks complete.

**Comment by alexr00** [comment] 2022-02-14 09:27
Duplicate of https://github.com/microsoft/vscode/issues/141506.

**Closed by alexr00** 2022-02-14 09:27 UTC
