### ISSUE TITLE
VS Code Tab key respond too slow for PHP while Emmet is active

### ISSUE THREAD

**Issue by Shimul22** [microsoft/vscode#75936] opened 2019-06-22 12:13 UTC
The problem is: When I enabled "Trigger Expansion On Tab", and works on PHP and press tab for taking four space (default behavior of Tab key), it takes too much to respond my request. I mean it takes too much to go four space from current position.

**Comment by octref** [comment] 2019-06-24 16:28
Duplicate of #71996.

**Closed by octref** 2019-06-24 16:28 UTC
Labels: emmet
