### ISSUE TITLE
Common git operations should be directly available, currently each time need to go though navigation tree, loosing time

### ISSUE THREAD

**Issue by ArunEdathadan** [microsoft/vscode#105700] opened 2020-08-31 03:06 UTC
Issue Type: <b>Feature Request</b>

In git menu,  the commit , push , pull, sync operations in inside the second level of the menu, these are commonly used, need to move to first menu level of the git for easy acces,  just a copy of the button is fine, hard move is not required

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

![Code_qp47oMDfca](https://user-images.githubusercontent.com/16814342/91679128-0f59f780-eb65-11ea-89dc-10c4d55dbd24.png)

**Comment by nrayburn-tech** [comment] 2020-08-31 03:20
This is under discussion here, https://github.com/microsoft/vscode/issues/104762.

**Comment by RMacfarlane** [comment] 2020-08-31 03:23
Closing as a duplicate of #104762

**Closed by RMacfarlane** 2020-08-31 03:23 UTC
