### ISSUE TITLE
Ctrl+Shift+ \ doesn't page down to matching bracket

### ISSUE THREAD

**Issue by swyman1** [Microsoft/vscode#34671] opened 2017-09-20 03:45 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.10
githistory|don|0.2.3
terraform|mau|0.0.17

Not sure if this is a bug or not, but since upgrading to v1.16 I've noticed that the Go to Bracket keybinding will mark the matching bracket but it does not page down to that bracket.  I've checked shortcut settings and it is indeed listed as a shortcut.  I just updated to v1.16.1 but the problem still persists.  If it is not a bug and instead some sort of setting I need to change please let me know.

---

Steps to Reproduce:

1.  Highlight a curly bracket then hit Ctrl+Shift+\ 
2.  Typically the page would jump to the matching bracket and in my case it no longer does.

Thanks for the help.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment] 2017-09-20 13:42
Duplicate of #32597

This has been already fixed on the Insiders version.

**Closed by alexandrudima** 2017-09-20 13:42 UTC
Labels: editor, editor-brackets, new release
