### ISSUE TITLE
Untitled new Luna Paint file cannot save backup when reloading window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#188963] opened 2023-07-26 18:26 UTC
1. Install Luna Paint
2. Create a new untitled image
3. Reload window
4. :bug: get this message

<img width="400" alt="image" src="https://github.com/microsoft/vscode/assets/30305945/ddcf4478-eb7c-4a10-9d0d-2b9acd5b5255">

I don't recall if we always failed to do hot exit for custom editors, but "could not be saved to the back up location" feels like an implementation detail that shouldn't be shown in a user facing message, can we say something like "could not be backed up"

**Comment by amunger** [comment] 2023-07-26 19:20
cc @bpasero

**Comment by bpasero** [comment] 2023-07-26 20:38
I suggest to move this to the respective extension, Luna reports:

```
[Extension Host] Backup failed Error: Could not backup file as it's too large
    at ns.<anonymous> (/Users/bpasero/.vscode-oss-dev/extensions/tyriar.luna-paint-0.16.0/luna/dist/vscode/exthost/extension.js:51:11607)
    at Generator.next (<anonymous>)
```

If you feel strong about the wording, please file a new issue specifically for that.

**Comment by Tyriar** [comment] 2023-07-27 14:01
I think this is by design, Luna Paint works a little differently to other extensions as the source of truth is maintained within the webview and not the exthost and it is not synchronized outside of saving because of the amount of data and time to serialize that may be needed. You can change `luna.hotExitMaxPixels` to up the cap but it could slow things down as this happens basically on every change.

I created https://github.com/microsoft/vscode/issues/113507 to fix this properly but it was closed as out of scope ☹️

**Closed by Tyriar** 2023-07-27 14:01 UTC
