### ISSUE TITLE
Right-clicking class name opens "psuedo-file" with wrong filename

### ISSUE THREAD

**Issue by JLa2r** [microsoft/vscode#80397] opened 2019-09-05 12:24 UTC
Issue Type: <b>Bug</b>

I have a file "../src/app/shared/navUtility.ts" which defines
export abstract class NavUtility {}

right-clicking on the name NavUtility (in this file or any file that references this class) cases VSCode to open the navUtilty.ts file but it's named as "NavUtility.ts".  Changes made in either file are represented in both files, but the filename change is misleading and confusing.

![1navUtility](https://user-images.githubusercontent.com/43070936/64341488-724a9a00-cfb6-11e9-9ba7-b59b63cb0cc2.png)
![2NavUtility](https://user-images.githubusercontent.com/43070936/64341489-72e33080-cfb6-11e9-92b7-3b724367d2f4.png)

I am running VSCode version:
Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (23.90GB free)|
|Process Argv|C:\SourceCode\xxx\xxx\DEV\Projects\XXX|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment] 2019-09-20 01:47
Duplicate of #55655

**Closed by mjbvz** 2019-09-20 01:47 UTC
