### ISSUE TITLE
product icons from theme extensions

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#78766] opened 2019-08-09 07:40 UTC
Can you add support product icons from theme extensions?
Your latest experiment with product icons will raise another wave of dissatisfied (#78752).
But restore old icons we do not have the opportunity :/

thank you.

**Comment by octref** [comment] 2019-08-09 16:23
Marking as duplicate of #78752 then.

**Closed by octref** 2019-08-09 16:23 UTC

**Comment by SailorMax** [comment] 2019-08-10 15:49
@octref How feature suggestion can be duplicate of decision complaint?

**Comment by misolori** [comment] 2019-08-11 05:13
@SailorMax see https://github.com/microsoft/vscode/issues/26130 for theming product icons
