### ISSUE TITLE
Contrast border lines vanish for selected tree item or split header

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#26113] opened 2017-05-06 10:12 UTC
- VSCode Version: Latest and greatest
- OS Version: Sierra

When you set contrast borders if you look closely they have this 1pt of pixel not-perfectness:

<img width="433" alt="screen shot 2017-05-06 at 2 35 09 pm" src="https://cloud.githubusercontent.com/assets/2157285/25771535/b77d9150-3269-11e7-8bd8-f32ce13482bc.png">

<img width="200" alt="screen shot 2017-05-06 at 2 41 08 pm" src="https://cloud.githubusercontent.com/assets/2157285/25771542/1203e2e6-326a-11e7-8377-ba4945658a72.png">

Also, headers get not borders at right which is also problematic:
<img width="326" alt="screen shot 2017-05-06 at 2 42 10 pm" src="https://cloud.githubusercontent.com/assets/2157285/25771546/34f70d28-326a-11e7-8610-bec170b39df8.png">

**Comment by bpasero** [comment] 2017-05-07 07:37
@pmkary can you share your theme changes so that I can see what happens to the header? I cannot reproduce in my simple test case:

```json
"workbench.colorCustomizations": {
	"contrastBorder": "#ff0000"
}
```

![image](https://cloud.githubusercontent.com/assets/900690/25778793/c470178a-3308-11e7-9597-aa613678d241.png)

The border of the entire sidebar should actually separate the header too.

**Comment by pmkary** [comment] 2017-05-07 19:05
@bpasero Thanks a lot for your investigation :D

## 1
I can actually see that your editor has just the same problem, Look: 
<img width="36" alt="screen shot 2017-05-07 at 10 59 58 pm" src="https://cloud.githubusercontent.com/assets/2157285/25783890/020537c2-3379-11e7-9b51-771fee7d0ed7.png">

Before the age of workbench configs I used to manually change the CSS of the page and I know how to fix that, just [check this snippet](https://github.com/karyfoundation/vscode-light-ui/blob/master/assets/theme.css#L2-L20)

but if you live to have more detail this the full settings:
```

    "workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#f2f2f2",
        "contrastBorder": "#e5e5e5",
        "peekViewEditor.background": "#E2EEFA",
        "peekViewResult.background": "#E2EEFA",
        "focusBorder": "#3778B7",
        "widget.shadow": "#cccccc",
        "editorGroup.border": "#E0E0E0",
        "editorGroupHeader.noTabsBackground": "#f1f1f1",
        "editorGroup.dropBackground": "#f1f1f1",
        "editorGroupHeader.tabsBackground": "#f1f1f1",
        "tab.inactiveBackground": "#f1f1f1",
        "tab.inactiveForeground": "#aaaaaa",
        "tab.activeForeground": "#C94824",
        "tab.border": "#f1f1f1",
        "editorWidget.background": "#f7f7f7",
        "panelTitle.activeBorder": "#B052A1",
        "titleBar.activeBackground": "#f1f1f1",
        "button.background": "#3778B7",
        "input.background": "#ffffff",
        "input.border": "#ffffff",
        "editorLineNumber.foreground": "#cccccc",
        "scrollbarSlider.background": "#DC8564",
        "scrollbarSlider.activeBackground": "#C94824",
        "scrollbarSlider.hoverBackground": "#C94824",
        "list.activeSelectionBackground": "#E2EEFA",
        "list.activeSelectionForeground": "#3778B7",
        "list.focusBackground": "#E2EEFF",
        "list.inactiveSelectionBackground": "#E2EEFA",
        "list.highlightForeground": "#3778B7",
        "inputOption.activeBorder": "#C94824",
        "activityBar.background": "#f1f1f1",
        "activityBar.foreground": "#aaaaaa",
        "activityBarBadge.background": "#C94824",
        "statusBar.background": "#3778B7",
        "statusBar.noFolderBackground": "#B052A1",
        "statusBar.debuggingBackground": "#C94824",
        "sideBarSectionHeader.background": "#f7f7f7",
        "sideBarTitle.foreground": "#A56416",
        "sideBar.background": "#f1f1f1"
    }

```

To be used with [Kary Foundation - Light](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes) if you want the full idea.

## 2
About the one pixel glitch I have no idea what so ever. I think if you change the sidebar header's height it would be the simplest to fix

**Comment by bpasero** [comment] 2017-05-08 06:02
I pushed a fix. We never actually want a contrast border for the first split view (this does not fix the reported issue but avoids it altogether).

Remains the issue with the `border-right`.

**Comment by pmkary** [comment] 2017-05-08 15:07
@bpasero thanks a lot 👍 
As always the fact that you guys are so kind and caring about the issues and user request is really awesome and appreciated. Thanks a lot :D

**Comment by bpasero** [comment] 2017-05-08 15:25
I decided to extract the other issue to https://github.com/Microsoft/vscode/issues/26218 so that we can close this one and verify it.

Verify:
* you are not seeing a border on top of the first split view (explorer, debug) in HC theme. Only for N > 1.

**Closed by bpasero** 2017-05-08 15:25 UTC
Labels: bug, themes
