### ISSUE TITLE
Display watchpoint values as hex

### ISSUE THREAD

**Issue by drahnr** [Microsoft/vscode#44131] opened 2018-02-21 14:36 UTC
- VSCode Version: 1.20.1
- OS Version: Fedora 27

Steps to Reproduce:

1. Debug an ARM emebdded target / any target
2. Add watchpoints

There is not way to display the members of structs as hex

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment] 2018-02-21 15:03
duplicate of #28025

**Closed by weinand** 2018-02-21 15:03 UTC
