### ISSUE TITLE
Hide panel, sidebar and activity on editor tab double click

### ISSUE THREAD

**Issue by lascarayf** [Microsoft/vscode#47453] opened 2018-04-09 02:39 UTC
Issue Type: <b>Feature Request</b>

Like "Eclipse" 

Double click on editor tab **->** hide sidebar, activity and panel.
Double click again **->** restore previous state.

Double click on panel tab **->** maximize panel size.
Double click again **->** restore panel size.

**Comment by bpasero** [comment] 2018-04-09 05:42
/duplicate of https://github.com/Microsoft/vscode/issues/16927

**Closed** 2018-04-09 05:42 UTC
Labels: *duplicate, feature-request
