### ISSUE TITLE
Supported File Live Previews

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#15996] opened 2016-11-24 02:48 UTC
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.12 Public Beta (16B2657)

My idea is to open files supported by the OS, VSC extensions, etc as a file in preview mode. For example, right clicking an html file then clicking "Open as Preview" will open a new tab as if its a file and show the contents in a simple frame. If you are wanting to see an example I've edited to look like the new feature I'm requesting, well here you go...

![](http://i.imgur.com/gUeMsUo.jpg)
![](http://i.imgur.com/Knt9UsA.jpg)

I'm sorry, I'm not the best at photoshopping but I did my best. This is kind of what I mean. If the file is being view without a workspace (alone as a single file), then there would be a button next to "Split view" at the top right near the exit button that will open the file as a preview file if it is supported by an extension, software, raw file view by OS or is supported by VSC. If the file you want to preview is in a workspace (currently open is a folder viewing workspace), then there would be an option to right click the file then "Open as Preview" or the same way you would open it as a singular file (without workspace). I tried my best to explain what I mean but if you are still having trouble understanding, just take a look at the images above. Please note that there is a reload button on the top right of the preview side of the second image, that will reload the preview to be updated with the code. A second idea (possibility) is a JavaScript Developer Console can be put below the preview with JavaScript errors, warnings and logs like Chrome does but that is optional.

**Comment by jrieken** [comment] 2016-11-24 08:32
This should be done as extension (and with our API that is possible)

**Comment by waderyan** [comment] 2017-02-16 19:16
Hi @JacobGunther12 - I am doing a short user research study on this issue. If you have time tomorrow or Tuesday can you sign up? https://calendly.com/waderyan/try-vscode

**Comment by JacobGunther12** [comment] 2017-02-16 19:25
@waderyan I'm not gonna sign up for anything I'm not sure about, thanks for the opportunity though.

**Comment by waderyan** [comment] 2017-02-16 21:17
@JacobGunther12 no problem!

**Comment by mjbvz** [comment] 2017-11-03 20:23
Duplicate of #12080

**Closed by mjbvz** 2017-11-03 20:23 UTC
Labels: duplicate, extension-candidate, feature-request
