### ISSUE TITLE
Irrelevant snippet has precedence over user snippet?

### ISSUE THREAD

**Issue by marcohamersma** [Microsoft/vscode#26312] opened 2017-05-09 13:47 UTC
- VSCode Version:  1.12.1
- OS Version: Mac OS X 10.12.4

I have a snippet called `clog`, which is an abbreviation for `console.log` that I've used for quite a while. Since the last version of vs code, however. It seems that the ranking for snippets has changed, and I'm getting an irrelevant suggestion as the first choice, and muscle memory makes me want to just press return to activate it.

![image](https://cloud.githubusercontent.com/assets/577144/25853592/44a3161a-34c5-11e7-9abf-b26c2448c68a.png)

I'm not sure where this suggestion comes from, it's nothing that I've typed in any of the files I have open. But I think that probably, user snippets should get precedence here. especially if they're this specific (I'm typing the exact and complete prefix).

Steps to Reproduce:

1. Open a javascript file
2. Create a snippet with the prefix "clog",
3. Somewhere in the file, type the word "clog" and see the suggestions appear
3. See alternative suggestions appear before manually added snippet

**Comment by egamma** [comment] 2017-05-09 18:10
Duplicate of #26182, fix will be available in next recovery build.

**Closed by egamma** 2017-05-09 18:10 UTC

**Comment by marcohamersma** [comment] 2017-05-09 18:27
Oops, I searched earlier but couldn't find a similar looking issue for some reason. Sorry for the duplication.
