### ISSUE TITLE
auto type acquisition doesn't kick in without --save

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15844] opened 2016-11-22 00:58 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Steps to Reproduce:
1. remove `underscore` from `%localappdata%/TypeScript/package.json` and from corresponding `node_modules`
2. open a Node project that does not have `underscore` installed (e.g. https://github.com/Microsoft/vscode-smoketest-express.git). VSCode will subsequently install type-registry, and any `@types` associated with the project. 
3. `npm install underscore`

Expected: underscore is installed, as are associated types, even though it doesn't exist in package.json
Actual: types are not installed

Note that reloading the project altogether yields the expected behavior.

**Comment by dbaeumer** [comment] 2016-11-22 17:30
@waderyan looks like a TS issue to me.

**Comment by mjbvz** [comment] 2016-11-22 22:39
This discussion on the TS side tracks a somewhat related design consideration: https://github.com/Microsoft/TypeScript/issues/11917

I believe this is currently the expected behavior, but I'll go ahead and open a issue against TS to see if this is the correct design. In the simple `npm install X` case, it probably makes sense to download the typings, but would would also want to make sure we don't install unnecessary typings for second level+ dependencies.

**Comment by mjbvz** [comment] 2016-11-22 23:39
After more investigation, I found that we do acquire typings in this case, but only after we trigger a project update in some way (for example, editing a file):

![nov-22-2016 15-30-43](https://cloud.githubusercontent.com/assets/12821956/20546356/5e817232-b0c9-11e6-9750-65a3d1f5c59b.gif)

In the `--save` case, we always install the typings. In the regular install case, it seems the typings are only installed after I edit and save a file or reload the project. It could be that the `--save` case is automatically sending some edit action to the server which triggers the typing acquisition, or TS could be handling this differently.

**Comment by waderyan** [comment] 2016-11-28 20:30
Closing in this end as this issue is tracked in TS's repo.

**Closed by waderyan** 2016-11-28 20:30 UTC
Labels: javascript, typescript, upstream
