### ISSUE TITLE
Files getting corrupted arbitrarily

### ISSUE THREAD

**Issue by dvirsky** [Microsoft/vscode#12889] opened 2016-09-28 14:33 UTC
- VSCode Version: 1.5.3
- OS Version: Linux (Ubuntu 16.04)

Steps to Reproduce:

While working on VScode, occassionally the code I'm working on gets corrupted - usually a few lines will get deleted or a bunch of spaces added. This usually happens on the file I'm editing, but not at the place I'm editing.

I'm working with the MS C/C++ extension, and clang-format. This could be the auto formatting, or it could be something inherent in the editor. 

A co-worker working with the same set-up experiences the exact same same issue.

**Comment by bpasero** [comment] 2016-09-28 15:40
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dvirsky** [comment] 2016-09-28 15:51
@bpasero I suspect it's an extension as well, my current suspect is a `clang-format` extension, and I've disabled it. it's the best suspect since it's meddling with file content on save. It might have a race condition or something. I'll see if disabling it solves this.

**Comment by bpasero** [comment] 2016-10-04 13:24
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-10-04 13:24 UTC
Labels: needs more info

**Comment by dvirsky** [comment] 2016-10-04 18:25
@bpasero  No problem, but I've been on holiday most of that time since, and programmed very little. I didn't have any incidents since, but that's based on ~2-3 hours of C programming in the past week. I'll let you know if it happens again.

**Comment by bpasero** [comment] 2016-10-04 18:37
Thanks.

**Comment by dvirsky** [comment] 2016-10-06 11:55
After a few more hours of coding without incidents (this used to happen every 10-15 minutes) I think we can safely say that it's the `clang-format` extension's fault. Since the MS c/cpp extension now supports clang formatting as well, if anyone encounters this - just don't use the standalone clang-format extension. 

Disabling it fixed the issue.
