### ISSUE TITLE
Integrated Terminal Freezes Intermittently

### ISSUE THREAD

**Issue by NimishVerma** [microsoft/vscode#120192] opened 2021-03-30 19:01 UTC
- VS Code Version:  1.52.1
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:
Issue started happening since the macOS update from Catalina to Big Sur
1.  normally working in code's terminal 
2. freezes for 3-4 seconds, records response during the freeze which are keyed after the delay

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment] 2021-03-30 20:59
Duplicate of #105446

**Closed** 2021-03-30 21:00 UTC
Labels: *duplicate
