### ISSUE TITLE
Return with increment operator breaks Typescript syntax highlight

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#35768] opened 2017-10-06 23:57 UTC
- VSCode Version: 1.17.0
- OS Version: Window 10 x64

Steps to Reproduce:

1. Open a new empty Typescript file and paste the following:
```
setTimeout(function(){
  let c = 0;
  return c++ < 5;
},1);

let a = 10;
let b = function(){
  let everythingIsInGreenNow;
}
```
![](https://puu.sh/xRNZ9.png)

The syntax highlight is now broken for the rest of the file. The bug is only caused when the increment operator is used in the return statement. `return c-- < 5` does not cause the bug, only `return c++ < 5`;

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-10-09 15:45
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/526

**Comment by roblourens** [comment] 2017-11-01 22:49
Still broken: 

![image](https://user-images.githubusercontent.com/323878/32301702-47e75200-bf1c-11e7-9c37-af684eb8955d.png)

**Comment by roblourens** [comment] 2017-11-01 22:53
Nvm, I have this installed: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

which is 1.5 months old. Is it not updated anymore?

**Closed by roblourens** 2017-11-01 22:53 UTC
Labels: bug, grammar, typescript, upstream, verification-found
