### ISSUE TITLE
Explorer not working

### ISSUE THREAD

**Issue by 10aditya** [Microsoft/vscode#60874] opened 2018-10-14 09:22 UTC
Issue Type: <b>Bug</b>

When mouse wheel scrolling over files in explorer, it shows files at different positions.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.15.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1661)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.70GB (1.98GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
Angular2|joh|6.3.0
python|ms-|2018.9.0
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
vscode-icons|rob|7.27.0

</details>

**Comment by egamma** [comment] 2018-10-14 17:27
Please provide detailed steps for how to reproduce the problem.

**Comment by 10aditya** [comment] 2018-10-14 18:29
When I scroll over file explorer using mouse wheel, files and folders are shown at different locations. Like when I scroll fast, files at top are shown at bottom, but they are actually at their locations only.

**Comment by isidorn** [comment] 2018-10-15 08:14
Duplicate of a tree issue @joaomoreno is aware off and can provide a pointer if needed.

**Closed** 2018-10-15 08:14 UTC
Labels: *duplicate, new release
