### ISSUE TITLE
Web download: same permission asked twice

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#109499] opened 2020-10-27 15:40 UTC
Testing #109284

Edge/Linux

Open the web playground, select a folder and download. When asked for a destination, create a new folder.
Two permission dialogs appear, select 'View files' and 'Save files'
![image](https://user-images.githubusercontent.com/6461412/97324925-b364d400-1872-11eb-945b-f748ecadd730.png)

Now download another folder. Select the same folder as destination. Again I'm asked for the same permissions.
Isn't the playground supposed to have the permissions already?

**Comment by bpasero** [comment] 2020-10-27 15:50
I can reproduce and I am surprised too, but I am not sure if my code has any impact on this behaviour...

**Comment by bpasero** [comment] 2020-10-28 08:50
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1143184. Possibly this is expected behaviour though.

**Comment by aeschli** [comment] 2020-10-28 11:21
:+1: 
It would also be great to have a single permission dialog for reading and writing.

**Comment by bpasero** [comment] 2020-11-04 07:51
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming

**Closed by bpasero** 2020-11-04 07:51 UTC
Labels: file-explorer, upstream, upstream-issue-linked, web
