### ISSUE TITLE
Extensions are unable to retrieve secrets through the Secret Storage API since v1.80.0

### ISSUE THREAD

**Issue by abeatrix** [microsoft/vscode#188952] opened 2023-07-26 17:19 UTC
Does this issue occur when all extensions are disabled?: 
- The issue happens to all the installed extensions that require access to Secret Storage API

- VS Code Version: 1.80.1
- OS Version: Linux Rocky

Steps to Reproduce:

1.  Sign into any extensions that store access tokens to secret storage via the Secret Storage API
2. Reload VS Code
3. You will now be signed off and require signing in again because the extension unable to retrieve the token through the Secret Storage API

This issue happens after upgrading to 1.80.0 and persists in 1.80.1

**Comment by TylerLeonhardt** [comment] 2023-07-30 02:00
This sounds like a duplicate of https://github.com/microsoft/vscode/issues/187338

**Closed** 2023-08-04 14:42 UTC
Labels: info-needed
