### ISSUE TITLE
Window with VS Code instance ignores integrated terminal confirmation on exit

### ISSUE THREAD

**Issue by yialo** [microsoft/vscode#92881] opened 2020-03-17 20:51 UTC
After installation of Node.js 12.16.1 there is no chance to prevent accidental close of IDE with working terminal by setting option `Terminal -> Integrated -> Confirm On Exit` to `true`. Popup message with dialog appears, but VS Code doesn't wait for user choice and closes itself almost immediately after the 'window-close' trigger fires.
Previous version of Node.js was 12.13, the behavior was correct on it.

- VSCode Version: 1.43.0 (user setup)
- OS Version: Windows 10 Pro x64, version 1909, build 18363.720

Steps to Reproduce:

1. Install Node.js v12.16.1.
2. Install Git for Windows v2.25.1-64-bit.
3. Set option `"terminal.integrated.confirmOnExit": true`.
4. Set option `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`.
5. Launch `Developer: Reload Window` from Command Palette, or close window with IDE instance via click on cross-button, or push `Alt + F4` keyboard shortcut.

Does this issue occur when all extensions are disabled?: Yes

**Comment by masbaehr** [comment] 2020-03-17 22:23
This happens for me too with node v13 installed. But i don't understand how the installated node version can have influence on vscode as it has it's own embedded node version

![image](https://user-images.githubusercontent.com/38694044/76907342-45047000-68a6-11ea-9778-7978d8407817.png)

**Comment by yialo** [comment] 2020-03-18 07:09
Maybe these versions of Node change something in OS environment during installation what then prevents correct listening of 'window-close' event by VS Code?

**Comment by Tyriar** [comment] 2020-03-18 18:47
@sbatten does before shutdown trigger the panel to start destroying views or something? The terminal has a feature that vetos the shutdown at the `LifecycleService.OnBeforeShutdown` step such that it will show a dialog if there are any terminal processes and the `confirmOnExit` setting is true.

**Comment by ian-h-chamberlain** [comment] 2020-03-26 05:03
Adding more details in case they are helpful. My symptoms are more like #92997 but it was closed as duplicate of this issue. When running `code --verbose` I see this after attempting to quit, the `confirmOnExit` prompt is shown and I press confirm:
```
[2535:0326/005635.692251:INFO:CONSOLE(1647)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.quit", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[main 2020-03-26T04:56:35.704Z] Lifecycle#quit() - from update: undefined
[main 2020-03-26T04:56:35.704Z] Lifecycle#quit() - calling app.quit()
[main 2020-03-26T04:56:35.704Z] Lifecycle#app.on(before-quit)
[main 2020-03-26T04:56:35.704Z] Lifecycle#onBeforeShutdown.fire()
[main 2020-03-26T04:56:35.715Z] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: '/Users/ianchamberlain/Library/Application Support/Code/Backups/1585198590687',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 0,
      y: 23,
      width: 1680,
      height: 962
    }
  },
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: 'file:///Users/ianchamberlain/Documents/Development/corewa_rs/tests/data',
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 1, x: 0, y: 23, width: 1680, height: 963 }
  },
  openedWindows: []
}
[main 2020-03-26T04:56:35.716Z] SharedProcess#close prevented
[main 2020-03-26T04:56:35.717Z] Lifecycle#window.on('close') - window ID 1
[main 2020-03-26T04:56:35.717Z] Lifecycle#unload() - window ID 1
[2535:0326/005635.819595:INFO:CONSOLE(1647)] "%cTRACE color: #888 lifecycle: onBeforeUnload (reason: 2)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005635.819876:INFO:CONSOLE(1647)] "%cTRACE color: #888 DialogService#confirm There is an active terminal session, do you want to kill it?", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.174395:INFO:CONSOLE(1647)] "%cTRACE color: #888 lifecycle: onBeforeUnload continues without veto", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[main 2020-03-26T04:56:36.175Z] Lifecycle#unload() - no veto (window ID 1)
[2535:0326/005636.176298:INFO:CONSOLE(1647)] "%cTRACE color: #888 lifecycle: onWillUnload (reason: 2)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.180427:INFO:CONSOLE(1647)] "%cTRACE color: #888 [storage state.vscdb] updateItems(): insert(Map(6) {lifecyle.lastShutdownReason => 2, memento/workbench.parts.editor => {"editorpart.state":{"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":0,"editors":[{"id":"workbench.editors.welcomePageInput","value":"{}"}],"mru":[0]},"size":510}],"size":1632},"orientation":0,"width":1632,"height":510},"activeGroup":0,"mostRecentActiveGroups":[0]}}, editors.mru => {"entries":[{"groupId":0,"index":0}]}, history.entries => [{"editorInputJSON":{"typeId":"workbench.editors.welcomePageInput","deserialized":"{}"}}], memento/workbench.editor.walkThroughPart => {"walkThroughEditorViewState":[["walkThrough:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D",{"0":{"viewState":{"scrollTop":0,"scrollLeft":0}}}]]}, workbench.panel.terminal.numberOfVisibleViews => 1}), delete(Set(0) {})", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.181198:INFO:CONSOLE(1647)] "%cTRACE color: #888 [storage state.vscdb] Trace (event): BEGIN TRANSACTION", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.181444:INFO:CONSOLE(1647)] "%cTRACE color: #888 [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('lifecyle.lastShutdownReason','2'),('memento/workbench.parts.editor','{"editorpart.state":{"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":0,"editors":[{"id":"workbench.editors.welcomePageInput","value":"{}"}],"mru":[0]},"size":510}],"size":1632},"orientation":0,"width":1632,"height":510},"activeGroup":0,"mostRecentActiveGroups":[0]}}'),('editors.mru','{"entries":[{"groupId":0,"index":0}]}'),('history.entries','[{"editorInputJSON":{"typeId":"workbench.editors.welcomePageInput","deserialized":"{}"}}]'),('memento/workbench.editor.walkThroughPart','{"walkThroughEditorViewState":[["walkThrough:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D",{"0":{"viewState":{"scrollTop":0,"scrollLeft":0}}}]]}'),('workbench.panel.terminal.numberOfVisibleViews','1')", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.182315:INFO:CONSOLE(1647)] "%cTRACE color: #888 [storage state.vscdb] Trace (event): END TRANSACTION", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.188349:INFO:CONSOLE(1647)] "%cTRACE color: #888 [storage state.vscdb] close()", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.194297:INFO:CONSOLE(1647)] "%cTRACE color: #888 terminalInstance#dispose (id: 1)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.196041:INFO:CONSOLE(1647)] "%cDEBUG background: #eee; color: #888 Terminal process exit (id: 1) with code undefined", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.196303:INFO:CONSOLE(1647)] "%cDEBUG background: #eee; color: #888 Terminal process exit (id: 1) state 4", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005636.196687:INFO:CONSOLE(1647)] "%cTRACE color: #888 terminalInstance#dispose (id: 1)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[main 2020-03-26T04:56:36.202Z] Lifecycle#onBeforeWindowClose.fire() - window ID 1
[2535:0326/005636.203881:INFO:CONSOLE(1647)] "%cTRACE color: #888 IPty#kill", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005638.303902:INFO:CONSOLE(1647)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.quit", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005638.936645:INFO:CONSOLE(1647)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.quit", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005639.206543:INFO:CONSOLE(1647)] "%c  ERR color: #f33 A system error occurred (ESRCH, No such process): Error: ESRCH, No such process
    at z.enableInspectPort (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3947:124)
    at e.getInspectPort (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3691:994)
    at K.getInspectPort (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4045:851)
    at y._onDidChangeResponsiveChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4338:819)
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:44)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3570:437
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3690:669
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at g._setResponsiveState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3677:580)
    at g._checkUnresponsive (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3677:409)
    at g.runner (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3676:694)
    at g.doRun (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:144:756)
    at g.onTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:144:722)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[2535:0326/005639.320279:INFO:CONSOLE(1647)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.quit", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
[main 2020-03-26T04:57:00.588Z] update#checkForUpdates, state =  idle
[main 2020-03-26T04:57:00.589Z] update#setState checking for updates
[main 2020-03-26T04:57:00.984Z] update#setState idle
[2535:0326/005826.845563:INFO:CONSOLE(1647)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.quit", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1647)
```
Note that I subsequently tried to quit the application a few more times after the first one failed. No further prompt was displayed.

**Comment by nc-wittj** [comment] 2020-03-27 13:32
This issue has been happening to me. I use this feature to prevent accidentally closing VSCode if I have running terminal sessions. I did not actively update my NodeJS version (to my knowledge). This appeared for me on VSCode 1.43.0 (I believe). I am running MacOS 10.15.3 (19D76).

Here's what I observe:

1. Clicking Cancel
![demo1](https://user-images.githubusercontent.com/28936242/77760452-beb9fd80-700c-11ea-9078-3fa7428684d2.gif)
After trying to close VSCode, if I click cancel, the terminal session is killed anyways. (Preventing this is the point of this feature.) If I restart something in the terminal and try to close VSCode, it closes immediately with no popup (another pop up used to appear).

2. Clicking Yes
![demo2](https://user-images.githubusercontent.com/28936242/77760483-cc6f8300-700c-11ea-8674-d9530ae1a1d2.gif)
After trying to close VSCode, if I click Yes, the window is not closed (it used to immediately close). I need to try to close VSCode again.

**Closed** 2020-03-27 17:44 UTC
Labels: bug, integrated-terminal
