### ISSUE TITLE
sticky scroll stuck when switching to files with one line

### ISSUE THREAD

**Issue by stevesakhnini** [microsoft/vscode#166286] opened 2022-11-14 15:42 UTC
Type: <b>Bug</b>

When a sticky scroll shows up on a file (Ex. large TS file) and then switch tabs to a file with one line of raw text, the sticky part remains, blocking access to the one line file's content.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.79GB (23.26GB free)|
|Process Argv|--crash-reporter-id 59f38217-06a5-405c-96f1-6cc551fd81a0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment] 2022-11-18 14:57
/duplicate of https://github.com/microsoft/vscode/issues/165385

**Closed** 2022-11-18 14:58 UTC
Labels: *duplicate, editor-sticky-scroll
