### ISSUE TITLE
Autocompletion doesn't work after a few moment. 

### ISSUE THREAD

**Issue by gquittet** [Microsoft/vscode#20473] opened 2017-02-11 12:20 UTC
When I code during 10 minutes, autocompletion says "Loading ..." and I don't know why.
I have to restart VS code and autocompletion works great again. But after a few moment, the autocompletion stop working. Fix autocompletion please.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-gist|dbankier|0.5.2|
|python|donjayamanne|0.5.8|
|theme-dracula|dracula-theme|1.2.5|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|
|latex|ms-vscode|0.1.3|
|java|redhat|0.0.10|
|vscode-icons|robertohuertasm|7.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by laggingreflex** [comment] 2017-02-12 14:55
Facing same issue. I'm not getting any errors in dev console when it stops working either. 

It does help though if I start it with `--disable-extensions`, but the nature of the problem is unpredictable so I'm not sure.

**Comment by gquittet** [comment] 2017-02-12 20:17
What plugins do you use ? Because the bug doensn't come from VS code.

**Comment by laggingreflex** [comment] 2017-02-13 04:14
I'm trying to identify which by slowly enabling one by one, but like I said since the nature of the problem is unpredictable I might not uncover anything useful. 

Currently using:

```
Asuka.insertnumbers-0.9.1
bibhasdn.git-easy-1.9.1
bibhasdn.unique-lines-1.0.0
donjayamanne.githistory-0.1.5
HookyQR.beautify-0.7.4
sleistner.vscode-fileutils-2.3.3
spoonscen.es6-mocha-snippets-0.0.2
alefragnani.Bookmarks-0.10.2
```

Currently disabled:

```
dbaeumer.vscode-eslint-1.2.5
esbenp.prettier-vscode-0.5.0
lkytal.FlatUI-1.1.0
ms-vscode.Theme-TomorrowKit-0.1.3
PeterJausovec.vscode-docker-0.0.11
streetsidesoftware.code-spell-checker-0.14.6
sysoev.language-stylus-1.6.0
```

So far I suspect `eslint` to be causing it but like I said, I could be wrong.

**Comment by joaomoreno** [comment] 2017-02-14 14:00
@laggingreflex @gquittet Which language are you using?

**Comment by gquittet** [comment] 2017-02-14 15:07
I use Java. My plugins are:

- C/C++

- Language Support for Java by RedHat

- Python

- vscode-icons

**Comment by joaomoreno** [comment] 2017-02-14 15:44
Does the same issue occur outside of a Java file?

**Comment by gquittet** [comment] 2017-02-14 16:08
I don't know because I've never used Visual Studio Code outside a Java file.

**Comment by joaomoreno** [comment] 2017-02-14 16:12
Can you please try?

**Comment by laggingreflex** [comment] 2017-02-19 11:38
I'm using javascript. Would tslog be helpful? here's `.tslog` (of last 1000 lines) after it stopped working. [tslog.txt](https://github.com/Microsoft/vscode/files/785797/tslog.txt)

**Comment by joaomoreno** [comment] 2017-02-20 07:24
@laggingreflex That tslog appears to be healthy.

I will close this issue since it seems to be a problem with the Java extension. @gquittet Please file an issue in https://github.com/redhat-developer/vscode-java/issues

**Comment by laggingreflex** [comment] 2017-02-20 11:53
I'm not using java, it still stops working for me from time to time.

**Comment by joaomoreno** [comment] 2017-02-20 13:59
ping @jrieken

**Comment by jrieken** [comment] 2017-02-20 14:34
Start VS Code from the console with the `--logExtensionHostCommunication` flag and attach the trace here. Finding out which extension goes crazy is complicated unless some one want to attach a debugger. The communication trace could give a hint

**Comment by gquittet** [comment] 2017-02-20 20:08
Where are the Visual Studio Code logs on Windows ?

**Comment by gquittet** [comment] 2017-02-20 20:10
[7868:5712:0220/205020:ERROR:crash_service.cc(295)] could not start dumper
[4548:14144:0220/205020:VERBOSE1:crash_service_main.cc(78)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode "--crashes-directory=C:\Users\gquit\AppData\Local\Temp\VSCode Crashes" --v=1]
[4548:14144:0220/205020:VERBOSE1:crash_service.cc(142)] window handle is 000B007C
[4548:14144:0220/205020:VERBOSE1:crash_service.cc(284)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\gquit\AppData\Local\Temp\VSCode Crashes
[4548:14144:0220/205020:VERBOSE1:crash_service.cc(288)] checkpoint is C:\Users\gquit\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[4548:14144:0220/205020:ERROR:crash_service.cc(295)] could not start dumper

**Comment by jrieken** [comment] 2017-02-21 07:18
@gquittet It should have printed something onto the dev tools console. Hit F1 > Toggle Developer Tools > Console and check for output there. Thanks

**Comment by gquittet** [comment] 2017-02-21 07:49
There's a bug when I open a java file. I'll code during 30 minutes and I'll see the other bugs.

> shell.ts:437 Illegal argument, contents must be defined : Error: Illegal argument, contents must be defined
    at new e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:7536)
    at asHover (C:\Users\gquit\.vscode\extensions\redhat.java-0.0.10\node_modules\vscode-languageclient\lib\protocolConverter.js:71:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jrieken** [comment] 2017-04-05 10:02
@gquittet The stacktrace point to an issue with the java-extension. Please file the issue against them. Thanks and Happy Coding

**Closed by jrieken** 2017-04-05 10:02 UTC
Labels: caused-by-extension
