### ISSUE TITLE
Set env to extensionHost type in launch.json did not work

### ISSUE THREAD

**Issue by leozdgao** [Microsoft/vscode#22150] opened 2017-03-07 15:07 UTC
- VSCode Version: 1.10.1
- OS Version: MacOS 10.12.3

Steps to Reproduce:

I'm working on a vscode extension development, and my launch.json here:

```js
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false,
            "env": {
                "NODE_ENV": "development"
            }
        }
    ]
}
```

And `env` seems not to be set. I try to follow the prompt here:

```
"node2" is no longer supported, use "node" instead and set the "protocol" attribute to "inspector".
```

And modify my launch.json like this:

```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false,
            "env": {
                "NODE_ENV": "development"
            }
        }
    ]
}
```

But got the connection timeout error here:

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:28486).
```

**Comment by roblourens** [comment] 2017-03-07 19:12
That error message about 'node2' is wrong. I think it was fixed by https://github.com/Microsoft/vscode/issues/21596, but the problem is that 'extensionHost' doesn't support the attribute 'env'. Right @isidorn?

**Comment by ramya-rao-a** [comment] 2017-03-07 19:15
@leozdgao Can you debug your extension using your initial launch.json configuration but without the `env` attribute?

**Comment by leozdgao** [comment] 2017-03-08 05:56
@ramya-rao-a I'm not sure. I just want to find an approach to judge the debugging environment, so I could load some development configuration. Is there anyway to do so without set env? 😕

**Comment by ramya-rao-a** [comment] 2017-03-08 06:42
I was currently trying to narrow down if debugging the extension works at all to begin with. Hence the question about trying without the env attribute.

**Comment by leozdgao** [comment] 2017-03-08 06:49
@ramya-rao-a Oh, debugging the extension works well. But the env configuration did not work.

**Comment by isidorn** [comment] 2017-03-08 09:39
@roblourens not sure if `extensionHost` supports `env`, forwarding to @weinand

**Comment by weinand** [comment] 2017-03-08 11:58
The extensionHost debugger doesn't support setting the env.

But the nasty problem is that the error squiggly is completely misleading:

![2017-03-08_12-46-29](https://cloud.githubusercontent.com/assets/1898161/23702884/896352b8-03fd-11e7-8913-580cf69480ed.png)

It flags the type "extensionHost" as wrong and not the illegal use of "env".

If the key value pair "foo":"bar" is removed from the env structure the error is flagged correctly:

![2017-03-08_12-52-03](https://cloud.githubusercontent.com/assets/1898161/23703044/3a5f4f04-03fe-11e7-8e0f-ca8a2a6ea397.png)

@aeschli Is there a way to let your validator know that the "type" attribute is special (and has higher priority)?

**Comment by leozdgao** [comment] 2017-03-08 12:03
@weinand BTW, is there anyway to know the code is running in the debug environment besides set env?

**Comment by weinand** [comment] 2017-03-08 16:54
Currently this feature is blocked by #22233

**Comment by aeschli** [comment] 2017-03-08 17:57
@weinand It's difficult for the JSON validator to know which variant ('any of') is the right one.
Please file an issue against JSON.

**Closed** 2017-03-08 22:27 UTC
Labels: debug, feature-request

**Comment by weinand** [comment] 2017-03-09 10:23
@leozdgao with the latest Insiders build you can now access env variables in the extension that are defined in the launch config.
