### ISSUE TITLE
Auto-Import should use tslint's quote setting

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#21444] opened 2017-02-26 13:43 UTC
Some folks use single quotes, some double quotes. This feature should look at the selected setting in `tslint.json`

```
    "quotemark": [
      true,
      "single"
    ],
```

- VSCode Version: Insiders 1.10.0
- Mac OSX

Steps to Reproduce:

1. use auto import

![auto import](https://cloud.githubusercontent.com/assets/1202528/23340160/7f1d6894-fbff-11e6-828c-51ce2c2f950c.gif)

**Comment by arciisine** [comment] 2017-02-26 16:19
I think this is a dupe of #21424

**Closed** 2017-02-26 19:13 UTC
Labels: duplicate
