### ISSUE TITLE
Debug in left menu does not update if triggered via f5

### ISSUE THREAD

**Issue by Coding-Kiwi** [microsoft/vscode#74796] opened 2019-06-03 15:38 UTC
Issue Type: <b>Bug</b>

I rarely use the debug tool, so I hid by rightcklicking on the icon in the left bar and unselecting it in the menu. When I hit f5 by accident, the debug icon shows up again, but the entry in the rightclick menu is still unchecked, so I have to check and uncheck it to hide.
The entry should automatically be checked again when triggered by a shortcut.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment] 2019-06-04 08:59
Disagree. This is how the activity bar is designed.
If you choose to explictly show something we treat that as temporary, you are not changing you actual layout setup.
Closing as designed, also since it is behaving like this since day 1, and this is the first complaint.

**Closed** 2019-06-04 08:59 UTC
Labels: *as-designed, debug
