### ISSUE TITLE
HTML tag not paired in PHP files

### ISSUE THREAD

**Issue by tbrcrl** [Microsoft/vscode#15191] opened 2016-11-08 17:30 UTC
- VSCode Version: 1.7
- OS Version: Win 10 64

Hello, I work a lot in PHP and one feature that will boost a lot productivity is the possibility to "pair" the HTML tags in PHP files as normally done in HTML files (please refer to the attached image for visual explanation). 
I know that it is possible to switch between PHP and HTML languages using the button on the bottom right part of the page. I was just wondering if it is possible to have an automatic recognition of HTML tags in mixed HTML / PHP content (like other editors do) without the need to switch forth and back between languages.

Thanks
![paired-tags](https://cloud.githubusercontent.com/assets/16580030/20109581/fe2296de-a5e0-11e6-9aad-d45d32f54214.png)

**Comment by aeschli** [comment] 2016-11-08 17:56
duplicate of #2915

**Closed by aeschli** 2016-11-08 17:56 UTC
