### ISSUE TITLE
Git commit "n characters left" tooltipcovers "staged changes" header

### ISSUE THREAD

**Issue by jrial** [microsoft/vscode#87089] opened 2019-12-16 14:36 UTC
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-72-generic

Steps to Reproduce:

1. Open Source Control view
2. Start typing in the field for the commit message
3. You'll see the "N characters left in current line" tooltip cover part of your staging controls, namely the "Staged Changes" header. See attached images.

![image](https://user-images.githubusercontent.com/570247/70915015-6476cd00-2019-11ea-8264-bb442aa300f3.png)

![image](https://user-images.githubusercontent.com/570247/70915044-722c5280-2019-11ea-93d4-71d6bd95cdc2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2020-01-14 11:26
Yeah, this is a popup, otherwise we would have to push content. Closing it as designed since the popup goes away as soon as focus goes out of the input box.

**Closed by joaomoreno** 2020-01-14 11:26 UTC
Labels: git

**Comment by jrial** [comment] 2020-01-17 12:35
@joaomoreno Well, actually, since the commit message input box is focused by default, the view starts out covering important aspects of the UI already. Not sure if that fits the "as designed" description.

Should I perhaps open a separate issue to not focus that text field from the start? It's kind of pointless to focus the commit text field until you're actually ready to commit, which would require you to first add some changes, which will defocus the field anyway.

See animation:

![output](https://user-images.githubusercontent.com/570247/72612828-23324f80-392e-11ea-92f8-491c3f36c847.gif)

**Comment by joaomoreno** [comment] 2020-01-21 08:33
We're currently refactoring that input box to use the monaco editor, so this info popup would disappear. It will happen this iteration.
