### ISSUE TITLE
not showing file icons in suggestions when importing js or ts files 

### ISSUE THREAD

**Issue by mahmoudabdulmuty** [microsoft/vscode#144910] opened 2022-03-11 13:29 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.65.2
- OS Version:  Windows_NT x64 10.0.22000

Not showing file icons when importing js or ts files

before in version 1.64

https://user-images.githubusercontent.com/52681435/157875906-46f4b316-e88f-4dbb-80c9-837dd3704570.mp4

after in version 1.65

https://user-images.githubusercontent.com/52681435/157876538-bda46865-603e-42fa-8796-b36acd6bb3b3.mp4

**Comment by mjbvz** [comment] 2022-03-11 20:12
Duplicate of https://github.com/microsoft/vscode/issues/144455

Please test on the latest insiders build to confirm it's been fixed

**Closed by mjbvz** 2022-03-11 20:12 UTC
Labels: new release
