### ISSUE TITLE
Diff tool doesn't work from file explorer when window.titleBarStyle set to custom

### ISSUE THREAD

**Issue by elch10** [Microsoft/vscode#56225] opened 2018-08-12 16:32 UTC
- VSCode Version: 1.25.1
- OS Version: Linux elch10 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux

When I set **"window.titleBarStyle"** to **"custom"**, vscode can not diff files selected from opened editors. Vscode just does not show a split screen with the 2 files being compared. It's like it's ignoring this action.
I checked it when **"window.titleBarStyle"** set on **"native"**, and it works normally.
P.S. It also works if I start it from terminal (code --diff)
P.P.S. sorry for my english 

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment] 2018-08-13 01:26
Thanks for reporting @elch10 

I see this when choosing 2 files from the file explorer and selecting the `Compare` option in the context menu

**Comment by ramya-rao-a** [comment] 2018-08-13 01:28
cc
@sbatten for custom menu
@alexandrudima for diff editor
@isidorn  for file explorer

**Comment by alexandrudima** [comment] 2018-08-13 08:06
@ramya-rao-a 

IMHO this should not be a recovery issue, given it is not a regression introduced in July. (i.e. the bug exists in 1.25.x)

**Comment by elch10** [comment] 2018-08-13 11:08
@alexandrudima You do this in turn, first you select one file, then the other. But I meant if you select 2 files at once. At first I noticed that it does not work only from ** Open Editors **, but now I see that it doesn't work from **Repro** too.
P.S. Yes, I can to reproduce it on Insiders build too.

**Comment by isidorn** [comment] 2018-08-13 13:05
`window.titleBarStyle: custom` is still a preview feature. So I think it is fine to push this out to August.

**Comment by alexandrudima** [comment] 2018-08-13 13:53
Thank you, I can reproduce now.

I believe this affects all the usages of `getMultiSelectedResources` in `fileCommands` and possibly more. It looks like that method returns a single selected resource.

**Comment by sbatten** [comment] 2018-08-14 00:53
@isidorn I noticed the check for dom focus here https://github.com/Microsoft/vscode/blob/f0a793389e244bba05a7a5536ace590e535f6cbd/src/vs/workbench/parts/files/browser/files.ts#L47 The custom context menu will take dom focus from the list. If I remove the requirement, everything works fine, but I don't if that is the right fix. Maybe the context menu service needs to restore focus right before calling the action which is what I do in the menubar.

/cc @bpasero

**Comment by bpasero** [comment] 2018-08-14 13:08
Moving to August. I think the issue here is that the menu uses the `WorkbenchList`, could that be true?

**Comment by isidorn** [comment] 2018-08-15 11:01
The issue here is that the new context menu "steals" focus from the open editors and explorer.
`getMultiSelectedResources` is written with an assumption that it will only respect what is selected in the open editors view or the explorer if they have focus. 
Otherwise it could happen that the user selects 3 files in the open editors view, goes to the editor works on something unrelated and triggers a close command from the command pallete -> this close command shuold not close the 3 files still selected in the open editors view since it does not have focus.

@sbatten well you are already restoring focus to the workbench when the menu is closed -> could you not restore the focus before the commands get executed?
@bpasero the `getMultiSelectedResources` wrongly assumes that if a list has focus than that list is an open editors view, though this does not seem to be the main problem here.

**Comment by bpasero** [comment] 2018-08-15 13:55
@isidorn isn't it too late to put the focus back only before running the commands, e.g. does it have an impact on the list of menu items when it shows up?

Ignore my comment about `WorkbenchList`, I think we are not using it for the menu.

**Comment by bpasero** [comment] 2018-08-15 14:04
@isidorn yeah I was more worried that we have some commands that have a when condition where we assume the list has to have DOM focus to operate and these would obviously not work anymore if the context menu steals focus. But maybe this is not an issue, just bringing it up.

**Comment by isidorn** [comment] 2018-08-15 14:50
@bpasero good point, but in practice I do not think we have such commands

**Closed** 2018-08-16 14:07 UTC
Labels: bug, diff-editor, menus
