### ISSUE TITLE
Auto Complete pops up "invalid arguments" message

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#27015] opened 2017-05-21 06:12 UTC
An annoying warning message pops when using auto-complete (see image below)
I've disabled all extensions.

- OS Version: Ubuntu 16.04
- VSCode Version: 
Version 1.13.0-insider
Commit cdaa5f28efd6d6fa012a34a92a6cf3fe57928b38
Date 2017-05-19T05:11:19.365Z

Steps to Reproduce:

1. Create new JS file and save it
2. Start typing "module" and use Tab or Enter to auto complete
3. Delete the entire word and repeat step 2
3. A warning message saying: "invalid arguments" will pop up

![image](https://cloud.githubusercontent.com/assets/19211868/26281607/e15a7db6-3e04-11e7-999b-c41a89086761.png)

**Comment by mjbvz** [comment] 2017-05-22 06:57
This is not specific to js/ts. Here's repo in a txt file:

1. Open a new text file.
2. Enable word based completions
3. Type out:

```
abc
ab
```

4. Trigger completions on on `ab` and the type `c`. Then hit tab


This shows invalid argument as well. 

----

Here are the errors that I see when this happens. First:

```
/Users/matb/projects/vscode/out/vs/workbench/electron-browser/shell.js:268 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at file:///Users/matb/projects/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:65:101
    at Model.TextModelWithDecorations._changeDecorations (file:///Users/matb/projects/vscode/out/vs/editor/common/model/textModelWithDecorations.js:173:26)
    at Model.TextModelWithDecorations.changeDecorations (file:///Users/matb/projects/vscode/out/vs/editor/common/model/textModelWithDecorations.js:145:29)
    at OneSnippet.move (file:///Users/matb/projects/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:57:44)
    at SnippetSession._move (file:///Users/matb/projects/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:270:44)
    at file:///Users/matb/projects/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:254:30
    at EditStack.pushEditOperation (file:///Users/matb/projects/vscode/out/vs/editor/common/model/editStack.js:43:87)
    at Model.EditableTextModel._pushEditOperations (file:///Users/matb/projects/vscode/out/vs/editor/common/model/editableTextModel.js:132:41)
    at Model.EditableTextModel.pushEditOperations (file:///Users/matb/projects/vscode/out/vs/editor/common/model/editableTextModel.js:59:29)
    at SnippetSession.insertNested (file:///Users/matb/projects/vscode/out/vs/editor/contrib/snippet/browser/snippetSession.js:253:39)
```

The actual exception is in `setSelections` in `commonCodeEditor`:

<img width="1317" alt="screen shot 2017-05-21 at 11 56 04 pm" src="https://cloud.githubusercontent.com/assets/12821956/26295900/1df02290-3e81-11e7-9917-ae044e958201.png">

@jrieken Can you please take a look

**Comment by jrieken** [comment] 2017-05-22 07:42
dupe of https://github.com/Microsoft/vscode/issues/26914

**Closed by jrieken** 2017-05-22 07:42 UTC
Labels: suggest
