### ISSUE TITLE
Add option to disable "Working Tree" editing from the Source Control pane

### ISSUE THREAD

**Issue by icopp** [Microsoft/vscode#64263] opened 2018-12-03 23:17 UTC
When I use the Source Control pane, it's rarely if ever that I want to actually see the diff version of the file. I'd rather have opening a file from this pane just open it as a normal editor. Can an option be added for this?

**Comment by usernamehw** [comment] 2018-12-04 06:50
/duplicate of #63005  Should be in the next release **1.30.0**

**Closed** 2018-12-04 06:50 UTC
Labels: *duplicate
