### ISSUE TITLE
Windows: Load environment variables without restart

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#29679] opened 2017-06-27 21:21 UTC
If env variable added or changed one need to close all the instances and reopen again to catch the changes (to be able to use in terminal etc). It is not very convenient in dev environment. So maybe VSCode could handle it better.

**Comment by ihalip** [comment] 2017-06-28 18:27
There is no notification from the operating system that the variables have changed.

However...

At least on my Windows 7 machine, it looks like user environment variables are placed under `HKCR\Software\Environment`, and system environment variables are in `HLKM\System\CurrentControlSet\Control\Session Manager\Environment`.

There should be an easy way to check for changes in these registry location.

**Comment by whitecolor** [comment] 2017-06-28 18:51
Well, vs code could update the values when launching each new external/shell process or opening terminal. I don't think that it would make any things slower, but it would be more convenient really.

**Comment by the-ress** [comment] 2017-07-08 20:56
Actually, there is a notification. OS sends [`WM_SETTINGCHANGE`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725497(v=vs.85).aspx) with `lParam` set to `Environment`.

**Comment by the-ress** [comment] 2017-07-08 21:27
Also [chocolatey/choco](https://github.com/chocolatey/choco) has a script that reloads env variables:
[RefreshEnv.cmd](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd) or [a more readable PS version](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1).

It handles merging PATH and other special cases.

**Comment by Tyriar** [comment] 2017-10-02 18:35
@bpasero @joaomoreno do you think we would ever support reloading the environment without restarting the main process?

**Comment by whitecolor** [comment] 2017-10-02 21:11
At least it would be good to see it happening after `Reload Window`  for particular instance.

**Comment by joaomoreno** [comment] 2017-10-03 08:40
@Tyriar It's a tough cookie to solve.

Seems like a duplicate of #6333

**Comment by Tyriar** [comment] 2017-10-03 16:19
Yeah let's closing as a duplicate of #6333

**Closed by Tyriar** 2017-10-03 16:19 UTC
Labels: feature-request, help wanted, windows
