### ISSUE TITLE
每天在17:30以后，开始卡顿，接近一小时时间。

### ISSUE THREAD

**Issue by MarsYu123** [Microsoft/vscode#63203] opened 2018-11-15 10:11 UTC
没见过这么灵异的现象，只开了vscode，webstrom，内存使用50%。持续大概半个小时。莫非是后门？有人遇到过此问题的吗？确认不是电脑问题。

**Comment by zouhuigang** [comment] 2018-11-15 10:46
我的一只卡，不知道咋搞的，写一会代码之后，切换到其他地方，就卡住了

**Comment by joseph1125** [comment] 2018-11-15 12:20
Please use English next time, duplicate of #62970 

Main maintainers here are English only, they don't understand your problem if you use Chinese, and issues are not message thread

**Comment by roblourens** [comment] 2018-11-16 04:20
> I have never seen such a strange phenomenon, only open vscode, webstrom, memory usage 50%. It lasts for about half an hour. Could it be the back door? Has anyone encountered this problem? Confirm that it is not a computer problem.

Please include more details about exactly what you are doing and what you are seeing. Which process is using lots of memory? Also using lots of CPU?

**Closed** 2018-11-23 05:13 UTC
Labels: needs more info
