### ISSUE TITLE
can't debug extension tests unless emptyWindow trust is on

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#125569] opened 2021-06-04 22:40 UTC
Version: 1.57.0-insider
Commit: fe1eafc80c07608de52a2f9c99fee103dea77f5e
Date: 2021-06-04T12:17:34.314Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-53-generic

- scaffold a new TypeScript extension: `yo code`
- open the extension in code-insiders
- in the debug viewlet, launch`Extension Tests` 
- new (empty) [Extension Development Host] window opens, error shows: `Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.`

Try again, but first set the settings
`"security.workspace.trust.emptyWindow": true`

Now the Window comes up properly and the tests run.

**Comment by sbatten** [comment] 2021-06-05 04:45
I tried for several hours to get a repro in OSS, but I guess things happen too slowly over there. From what I can tell:

1) The window is started with a trust value of false
2) The extension host is started 
3) The window is trusted once it is initialized because it has an extensiontestpath uri
4) The extension host is either started again or the port changes
5) we never attach and so the extension host is hung

However, this was not validated by this change I built and tested: https://github.com/microsoft/vscode/commit/3ef865abc23375ef3d48e20c80cbdb1a19ff83de

**Comment by lszomoru** [comment] 2021-06-05 11:41
We have done quite some changes to make sure that the workspace trust state is set *before* the extension host starts. Given the fact that the change to set the trust state to `true` still does not resolve the problem, makes me believe that even though the trust state is set to `true` there is a state transition back to `false`. I believe that the problem is here:
https://github.com/microsoft/vscode/blob/ea2778063405633fb87c911ef5f580cc0a1d32c8/src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts#L445

Let me try to build a version which contains the fix and confirm that it resolves the problem.

**Comment by lszomoru** [comment] 2021-06-05 14:12
I can confirm that b2715f1f3004615eca56afc016cc87069fa5c504 resolves this issue. Marking it as candidate.

**Closed** 2021-06-07 12:32 UTC
Labels: candidate, extension-host, workspace-trust
