### ISSUE TITLE
Markdown preview will not work if machine is offline.

### ISSUE THREAD

**Issue by Lukas238** [Microsoft/vscode#35748] opened 2017-10-06 16:49 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
FreeMarker|dco|0.0.9
python|don|0.7.0
EditorConfig|Edi|0.10.1
php-debug|fel|1.11.1
auto-rename-tag|for|0.0.14
code-runner|for|0.7.2
macros|ged|1.2.0
Language-TodoTXT|ger|0.0.1
beautify|Hoo|1.1.1
vscode-browser-sync|jas|1.2.0
docthis|joe|0.4.8
vscode-insertdatestring|jsy|2.1.0
ecdc|mit|0.10.3
prettify-json|moh|0.0.3
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1
partial-diff|ryu|0.3.3
stylelint|shi|0.29.1
sort-lines|Tyr|1.3.0
markdown-pdf|yza|0.1.7
html-css-class-completion|Zig|1.10.0

---

## Steps to Reproduce:

1. In VSCode, create and fill a .md file (markdown).
2. Go offline (disconnect network cable and WiFi).
3. Open Markdown review on VSCode.
4. The preview windows opens, but nothing is displayed.

Reproduces without extensions: Yes

## Developers Tools: Console Log

```
shell.ts:419 net::ERR_INTERNET_DISCONNECTED

Error: net::ERR_INTERNET_DISCONNECTED: Error: net::ERR_INTERNET_DISCONNECTED

Error: net::ERR_INTERNET_DISCONNECTED
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:78173)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
---
webview.ts:151 [Embedded Page] Uncaught Error: EFILE
```

**Comment by Tyriar** [comment] 2017-10-06 18:13
Cannot reproduce on Windows/macOS.

@Lukas238 could you update to the latest version 1.17 and try again?

**Comment by mjbvz** [comment] 2017-10-08 13:47
I also cannot reproduce this issue. If you stills see this with 1.17, can you also please try disabling all extensions to make sure one of them is not causing trouble here

**Comment by Lukas238** [comment] 2017-10-13 15:59
All is working fine, online and offline, on version 1.17.


The issue was on ver 1.16, with and without extensions. Not sure way.

Thanks!!

**Comment by mjbvz** [comment] 2017-10-13 18:28
Thanks for the followup, @Lukas238!

Closing this issue since it seems to have been resolved

**Closed by mjbvz** 2017-10-13 18:28 UTC
Labels: markdown, needs more info
