### ISSUE TITLE
Settings GUI should expose *all* settings even if JSON editable only

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode#69881] opened 2019-03-06 01:06 UTC
I just experienced a second hidden feature in the VSCode settings. Not too long ago, I was surprised to learn there was a secret `[yaml]` setting (#69011). Today, it was `editor.codeActionsOnSave`.

I was trying to figure out why my imports kept sorting. I searched high and low through the settings UI. I searched for "imports", "sort", "sorting", "organize", "organizing", "typescript", "javascript", "save", and "saving", and nothing explained the behavior I was seeing. Even after turning off all extensions (including Prettier and TSLint), the imports kept sorting when I hit save. *Finally*, I decided to check the settings.json and stumbled upon `editor.codeActionsOnSave`.

As I mentioned in #58995, the problem is not having to edit a JSON file, it's lack of *discoverability*. And it's not just discoverability of features I don't yet know about, it's discoverability of settings that are currently causing my files to be actively edited against my will.

I use the settings UI to find out about settings, and then if I need to hop over to JSON to edit it, that's fine, but please at least list *every* setting and sub-setting that matches my search keyword, whether I can edit it via the UI or not. If it needs to be edited in the JSON file, just mention that and maybe throw in a link that pops open the JSON editor.

**Comment by roblourens** [comment] 2019-03-06 17:52
I'm going to close this as a duplicate of #58995 but I understand that this is a real issue and I need to do something about it.

**Closed by roblourens** 2019-03-06 17:52 UTC
