### ISSUE TITLE
BUG: Scrollbar moves by changing the files tab

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#29106] opened 2017-06-20 13:40 UTC
- VSCode Version: 1.13.1
- OS Version:  Windows 10

Steps to Reproduce:

1.  Open two files with scrollbar
2.  Move the scrollbar to the middle
3.  Switch between tabs

See the image, NOTICE THE BREAKPOINTS ON FIRST TAB:

![bug_vscode](https://user-images.githubusercontent.com/5774595/27335846-3cf7bde4-55a4-11e7-8c53-cdee9867cd0a.gif)

**Comment by mjbvz** [comment] 2017-06-21 21:10
This is a duplicate of #19917

When adding codelenses, we currently preserve the scroll position to the middle of the screen. That is what is causing the breakpoint at the top of your file to be pushed off screen

**Closed by mjbvz** 2017-06-21 21:10 UTC
Labels: code-lens, duplicate, new release

**Comment by cwberick** [comment] 2017-06-26 12:25
Ok, but then not exists one solution for this problem??
I saw very suggestions for this problem.
This bug is very very annoying.. =/

**Comment by cwberick** [comment] 2017-06-26 12:28
I liked this solution:
https://github.com/Microsoft/vscode/issues/23652#issue-218120842
