### ISSUE TITLE
Word wrapping renders spaces as first characters on a line

### ISSUE THREAD

**Issue by g102** [microsoft/vscode#74607] opened 2019-05-30 08:43 UTC
When word wrapping is enabled and the first character that does not fit on a line is a whitespace, the space is rendered as the first character on the new line. This creates a fake indentation that, while not being an issue or breaking the workflow, can be annoying. Other text editors usually don't exhibit this behaviour.

For clarity, consider this paragraph:

![vscode](https://user-images.githubusercontent.com/32854170/58620319-b430b980-82be-11e9-9d66-0ebed50dfee1.PNG)

The second line of the paragraph ends with "veniam, ", with the space being the first character not to fit on the line. As such, the line is wrapped just after the comma and the space is rendered as the first character on the third line. Compare it with Notepad++ (same font, same fontsize):

![npp](https://user-images.githubusercontent.com/32854170/58620397-e0e4d100-82be-11e9-9c7a-c6060d4ded75.PNG)

The second line would end at "veniam, " as well, but the word is wrapped after the previous whitespace, after "ad minim ", and the space between "veniam," and "quis" is still rendered.

**Comment by LiteracyFanatic** [comment] 2019-07-25 17:54
I have also noticed this issue. I'd like to slightly clarify the conditions which cause this to happen. It is necessary but not sufficient for the first character which does not fit on a line to be a space. The preceding character must also be a comma. In the absence of a comma, the word preceding the space will also wrap around and the line will look fine. The following screenshot demonstrates this:

![1564076477](https://user-images.githubusercontent.com/18249574/61895902-6361c980-aed9-11e9-9a3d-08b01cb10a3a.png)

**Comment by fguada** [comment] 2019-08-02 18:12
I think it's a duplicate of [Word wrap should not break before a space (#47990)](https://github.com/microsoft/vscode/issues/47990).

**Comment by rebornix** [comment] 2019-08-02 18:18
@fguada thanks!

**Comment by martinauer** [comment] 2019-11-16 14:02
Can reproduce this in v1.40.1 / macOS. Fix would be greatly appreciated! Thanks!

**Comment by steponeloops** [comment] 2019-11-17 12:15
Reproducible also in 1.40.0 / Linux.

**Comment by alexdima** [comment] 2020-01-10 10:04
Fixed with the fix for https://github.com/microsoft/vscode/issues/33366

**Closed by alexdima** 2020-01-10 10:04 UTC
Labels: editor-wrapping, feature-request
