### ISSUE TITLE
Need to press Command+S twice to save a file.

### ISSUE THREAD

**Issue by mablejohn** [Microsoft/vscode#12755] opened 2016-09-27 12:50 UTC
- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: OS X EI Capitan, Version 10.11.6

Steps to Reproduce:

1. File->Open Select any project folder, in my case the project was an ionic hybrid app. 
2. Make any changes on a file and try to save.

Note: I had installed a lot of 'Extensions'.

![screen shot 2016-09-27 at 6 17 26 pm](https://cloud.githubusercontent.com/assets/6983882/18873811/c956d154-84de-11e6-80f9-609f55c624da.png)

**Comment by bpasero** [comment] 2016-09-28 07:21
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by mablejohn** [comment] 2016-09-28 08:55
It's working fine without extensions.

**Comment by mablejohn** [comment] 2016-09-28 08:58
Is there any way or techniques to find out which extension are actually malfunctioned.

**Comment by bpasero** [comment] 2016-09-28 09:18
Currently not, sorry.

Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2016-09-28 09:18 UTC
Labels: needs more info

**Comment by mablejohn** [comment] 2016-09-28 09:21
Thanks for the support.

**Comment by ramya-rao-a** [comment] 2016-09-30 20:29
@mablejohn I had the same issue and could narrow it down to the extension `JS-CSS-HTML Formatter`. Do you have the same extension installed? If yes, then can you uninstall and check if you still see the issue?

I have logged https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/28 in the extension's repo

**Comment by mablejohn** [comment] 2016-10-01 04:47
@ramya-rao-a yes, i had installed the same extension you mentioned. Now it is working fine after uninstall it.

Thank you
