### ISSUE TITLE
custom properties not showing in second css file

### ISSUE THREAD

**Issue by kemerait** [microsoft/vscode#214831] opened 2024-06-11 02:01 UTC
Type: <b>Bug</b>

1. Create 2 .css files. 
2. In one place a few :root {} level variables such as --sample-1; --sample-2; --sample-3; etc.
3. in the other file create an #element {} 
4. inside set the background-color: var(--sample-1);

when you start typing you will see all 3 variables as options. Now either add another property such as color: var(--sample-2); or another #element{} You will notics that it no longer shows all 3 custom properties only 1 or 2. If you remove the 2nd instance of var(--xxx) all 3 will reappear.  Here is a link with a screen recording to observe the behavior...

https://photos.app.goo.gl/nzyECSUuk1szgKQw7

https://github.com/microsoft/vscode/assets/172342943/6cb823c0-3371-4fa2-a711-56d2fcd2c43a

https://github.com/microsoft/vscode/assets/172342943/e372345e-9a10-4778-be5f-3952781b1ed7

I have done a complete uninstall and reinstall, no extensions running ... no default values changed. I did this twice!  If you put the variables AND the var(--xxx) in the same file everything works as designed but if you split the files into 2 then the problem occurs.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (27.76GB free)|
|Process Argv|--crash-reporter-id 8c91652e-cc67-4c0c-bf9a-5a3306e8bd25|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by aeschli** [comment] 2024-06-12 07:57
duplicate of #214871

**Closed by aeschli** 2024-06-12 07:57 UTC

**Comment by kemerait** [comment] 2024-06-12 13:07
Did you close both the original and duplicate?
