### ISSUE TITLE
Jump Marks & Jump Mark Index Tab(Code Navigation)

### ISSUE THREAD

**Issue by NeverMops** [microsoft/vscode#118420] opened 2021-03-08 10:14 UTC
Hello! I think it would be great to Place hidden Code Marks inside the Code, and to add some Code Marks Tab, to the Left in VScode, whre the Extensions are. So you could easyly Navigate to frequently used Places in the Code or set Bootmarks..

**Comment by aeschli** [comment] 2021-03-08 10:49
Duplicate of #36082, #45216, #46321, #47691, #96961, #97067 and maybe more. 

You can use the popular Bookmarks extension.

**Closed by aeschli** 2021-03-08 10:49 UTC
