### ISSUE TITLE
Shortcuts not working when switching input source language

### ISSUE THREAD

**Issue by cmas1** [Microsoft/vscode#67379] opened 2019-01-29 11:31 UTC
- VSCode Version: 1.30.2
- OS Version: Ubuntu 16.04

It appears that vscode uses as keyboard layout for the shortcuts the input source language that is active when the program is launched. Once the program is running, changing the source input language does not affect the way vscode interpretes the keys for shortcuts. This only affects the shortcuts, not general typing.

Steps to Reproduce:

1. In Ubuntu set input source language to EN
2. launch vscode and in an editor try the comment line shortcut, ctrl + /
3. switch language to IT
4. press again the keys  ctrl + /, which in IT layout should be read as ctrl + -, that is the shortcut for zoom out. However it still executes the comment line shortcut.

Now, close vscode and try the opposite.
1. In Ubuntu set the input source language to IT
2. launch vscode and in an editor and press ctrl + /. Now this is read correctly as ctrl + - and the font size decreases
3. switch language to EN
4. press again the keys  ctrl + /. Once again, the font size decreases instead of performing the comment line shortcut.

I also verified the same problem when switching from English (US) to German.

**Comment by alexandrudima** [comment] 2019-01-30 17:17
This is documented at https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

Duplicate of #23690

**Closed by alexandrudima** 2019-01-30 17:17 UTC
Labels: editor-contrib
