### ISSUE TITLE
Activity bar sometimes re-orders when dragging new entry to top

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#94331] opened 2020-04-03 00:40 UTC
Issue Type: <b>Bug</b>

**Repro**
Try dragging new view to top of the activity bar:

![repos](https://user-images.githubusercontent.com/12821956/78312470-be3bce00-7508-11ea-92ad-1a2ec7646b1a.gif)

**Bug**
Notice how the terminal icon I dragged to the top shifts to the bottom after a half second

This does not happen reliably for me. I don't know why it sometimes happens and why it usually does not

VS Code version: Code - Insiders 1.44.0-insider (d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa, 2020-04-02T06:40:18.155Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|-psn_0_3175175|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by sbatten** [comment] 2020-04-03 18:42
Unfortunately, I just cannot reproduce this one so I am not sure how to debug it. Since it relates to new functionality that is in preview, I am going to set it for April.

**Comment by sbatten** [comment] 2020-04-27 17:02
I'm going to close this as resolved since after 30 or so tries it does not reproduce. Further, there were too many refactorings in the area to know if the behavior changed.

**Comment by sbatten** [comment] 2020-04-27 17:05
To Verify:
1. It's difficult to verify this since it did not reproduce reliably, but simply try to move the terminal to the top position of the activity bar from the panel.
2. Reset View Locations
3. Repeat above steps 10 or more times.
4. Verify that the terminal is always the top position and does not move after a second.

**Comment by roblourens** [comment] 2020-04-30 21:35
I saw the same thing happen a couple times. But I don't have repro steps, sorry. I also saw this happen when dragging back to the panel. I dragged it to the right-most spot, and it went to the left-most spot.

**Comment by roblourens** [comment] 2020-04-30 21:38
Example:

![Apr-30-2020 16-37-38](https://user-images.githubusercontent.com/323878/80761844-f4b53a80-8b00-11ea-8ae5-83a852cc7d59.gif)

**Comment by sbatten** [comment] 2020-05-18 23:54
pretty sure I now know the reliable repro for this and its multi-window:

1. Open 2 windows
2. In Window 1, move terminal to the first position of the panel (note this syncs across the windows)
3. In Window 1, move terminal to side bar (also syncs)
4. In Window 1, move terminal back to panel in last position

:bug: => terminal moves to end then back to 3rd position.

This has to do with the fact that we move the composite into position after moving it to the right container. The order of storage change events and and the fact that `order` is what is used to determine initial position but is never updated when things move causes this strange behavior.

**Comment by connor4312** [comment] 2020-06-04 22:22
I still repro this using Steven's instructions on the latest insiders: https://memes.peet.io/img/20-06-37d9fcdb-679a-4c3f-abc1-4590d2491f94.webm

**Comment by sandy081** [comment] 2020-06-05 08:24
@connor4312 I followed the same instructions and I cannot repro it on insiders and also running out of sources. I see in the video that it is happening to you but I am not able to assume what is causing this. Can you please try on fresh user data dir ?

**Closed** 2020-06-08 21:07 UTC
Labels: bug, verification-found, workbench-dnd, workbench-views
