### ISSUE TITLE
Some bug in terminal

### ISSUE THREAD

**Issue by devam3132** [Microsoft/vscode#66259] opened 2019-01-09 04:34 UTC
Issue Type: <b>Bug</b>

when we open terminal it will goes to directly last line.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
angulardoc-vscode|Ang|6.1.3
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
easy-icons|jam|0.3.1
Angular2|joh|7.0.1
team|ms-|1.144.1
vscode-extension-auto-import|Nuc|1.4.3
polacode|pnp|0.2.2
LiveServer|rit|5.3.1
sass-indented|rob|1.5.1
autoimport|ste|1.5.3
quokka-vscode|Wal|1.0.175

(2 theme extensions excluded)

</details>

**Comment by MicahZoltu** [comment] 2019-01-09 08:18
I am experiencing this as well (I think).  The terminal starts scrolled down past the point where I can see the prompt, so by default the terminal appears to not show anything.  If I scroll up, I can see the prompt.

Note this seems to be a problem with Powershell terminals, however if I create a powershell terminal (triggering this problem) then create a CMD terminal I experience the same issue for the first CMD terminal I create.  Any further CMD terminals will be properly scrolled.

**Comment by RMacfarlane** [comment] 2019-01-09 17:58
Duplicate of https://github.com/Microsoft/vscode/issues/57803

**Closed by RMacfarlane** 2019-01-09 17:58 UTC
Labels: *duplicate, new release
