### ISSUE TITLE
Quick fixes for missing imports not available in typescript files

### ISSUE THREAD

**Issue by iRoachie** [Microsoft/vscode#57156] opened 2018-08-24 15:01 UTC
References:
https://github.com/Microsoft/vscode/issues/56501#issuecomment-413349992
https://github.com/Microsoft/vscode/issues/56501#issuecomment-415725978

- VSCode Version: 1.26.1
- OS Version: macos High Sierra 10.13.6

Steps to Reproduce:

1. Setup a project with @types/react-native and typescript
2. Write code that requires a missing input

```tsx
import {
  Keyboard,
  StyleProp,
  StyleSheet,
  TextInput,
  TextInputProperties,
  TextStyle,
  TouchableOpacity,
  View,
} from 'react-native'
// Further in code
onBlur = (e: NativeSyntheticEvent<TextInputFocusEventData>)
```

Does this issue occur when all extensions are disabled?: Yes

Already tested in insiders.

Other relevant files:
```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "jsx": "react-native",
    "noEmit": true,
    "moduleResolution": "node",
    "strictPropertyInitialization": false,
    "skipLibCheck": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "noUnusedLocals": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "paths": {
      "@components": ["components"],
      "@config": ["config"],
      "@pages": ["pages"],
      "@types": ["types"],
      "@util": ["util"],
      "@actions": ["actions"],
      "@reducers": ["reducers"],
      "@data": ["data"]
    },
    "lib": ["es2017", "dom"]
  },
  "exclude": ["node_modules"]
}
```

`"@types/react-native": "^0.56.7",`

**Comment by mheavenor** [comment] 2018-08-27 15:19
I too am having this issue. The Quick Fix lightbulb does not appear and hitting Ctrl+. on the missing import yields in `ERR An unknown error occurred. Please consult the log for more details.` in the Developer Tools.

Using VSCode 1.26.1

**Comment by mjbvz** [comment] 2018-09-05 01:01
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by iRoachie** [comment] 2018-09-05 05:45
@mjbvz Yes i've already said that.

**Comment by iRoachie** [comment] 2018-09-05 05:46
Version 1.27.0-insider (1.27.0-insider)

**Comment by mjbvz** [comment] 2018-09-05 18:31
Duplicate of #56332

Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

**Closed by mjbvz** 2018-09-05 18:31 UTC
Labels: needs more info, typescript

**Comment by iRoachie** [comment] 2018-09-05 18:50
Works! Thanks
