### ISSUE TITLE
Editor. Formatting. not working

### ISSUE THREAD

**Issue by bodynar** [Microsoft/vscode#25223] opened 2017-04-24 08:49 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.1|
|Theme-azure|gerane|0.0.2|
|Theme-peel|gerane|0.0.2|
|csharpextensions|jchannon|1.3.0|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.8.1|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1. since last update editor.action.formatDocument is no longer working for me (default settings)
2. no full document & selection format

**Comment by will-stone** [comment] 2017-04-24 12:03
A colleague of mine is experiencing this intermittently too, and a restart usually fixes it. None of her extensions match yours though. Can you paste your `settings.json`?

**Comment by bodynar** [comment] 2017-04-24 13:15
Oh, restart (reboot also) didn't help.

here settings.json:
`
{
    "files.associations": {
        "*.cshtml": "razor"
    },
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "vs-minimal",
    "editor.roundedSelection": false,
    "editor.minimap.enabled": true
}
`

**Comment by will-stone** [comment] 2017-04-24 13:38
Hmmm, no correlation there except the colorTheme and the minimap. We'll need someone from Microsoft to advise on how to debug.

**Comment by jrieken** [comment] 2017-04-24 13:46
>  We'll need someone from Microsoft to advise on how to debug.

How about rewriting this issue so that we can reproduce this? The initial poster didn't spell out what language he is trying to format which is vital because *all* formatting features come via extensions. Then there is mentioning of the underlying command `editor.action.formatDocument` but mentioning now that command is invoked. Keybinding? Contributed Menu? Context Menu?

**Comment by bodynar** [comment] 2017-04-24 16:49
Sorry for topic message.

languages where i gets bug: c#, javascript, Razor (.cshtml extensions), html [asp.net development langs group]
Command invoke: default keybinding (alt+shift+f) && contributed Menu.

vs code extentions declared in topic message.

how i get bug [possibly steps to reproduce]:
**1**. open vs code
**2**. create new file and set C# lang (by click in right bottom menu-bar and choosing from dropdown in top)
**3**. writin' some code (like 
`public class Student{
    public int Age                      {get;set; }
}`

[result must be format: `public class Student {
    public int Age  { get; set; }
}` ]
[editor removed several spaces\tabs between **Age** and **{get;set;}**
**4**. use keybinding (alt+shift+f)

**Comment by jrieken** [comment] 2017-04-25 06:52
> 4. use keybinding (alt+shift+f)

Can you reproduce this when selecting format from the context menu? For each file type mentioned above check that the context menu contains the format document and/or format selection action

**Comment by bodynar** [comment] 2017-04-25 08:34
Hm..

I don't have format-command in c# \ js \ razor context menu.
Only:
- (ctrl + f2) [only in c#]
- Cut
- Copy
- Paste

**Comment by jrieken** [comment] 2017-04-25 09:48
Ok. The context menu reflects the state of our feature registry and that means there is no formatting available/registered for this languages. For JS we ship a formatter which makes me wonder if you have a workspace or user setting disable those?

**Comment by bodynar** [comment] 2017-04-25 11:38
Sorry for my mistake.

I do have context menu with formatting-command in js-files.
And keybinding works for js too (as command from context menu).
![image](https://cloud.githubusercontent.com/assets/22620134/25383447/dc84c5de-29c4-11e7-98eb-24b9f14a9391.png)

**Comment by jrieken** [comment] 2017-04-25 13:02
Ok. Then is seems that you are missing an extension that can format C# and Razor. For the former I'd recommend [_vscode.csharp_](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) for Razor I am unsure what to use. 

Closing this because it's the design of VS Code to delegate formatting to extensions

**Closed by jrieken** 2017-04-25 13:02 UTC
Labels: format, needs more info

**Comment by bodynar** [comment] 2017-04-25 13:37
But in topic message i mentioned all extensions and vscode.csharp installed.

What should i do?

**Comment by jrieken** [comment] 2017-04-25 13:49
Please file an issue against the extensions individually then.

**Comment by maierson** [comment] 2017-05-15 23:25
I just got bit by this one today. Out of the blue javascript formatting just stopped working. No changes to the editor.
