### ISSUE TITLE
 Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#45808] opened 2018-03-14 22:20 UTC
Issue Id: <b>7ac04df4-92ba-ac9c-dc43-89c2f8470d4f</b><br /><br />*Versions* <br />- 1.21.0<br />-  c63189deaa8e620f650cc28792b8f5f3363f2c5b<br />-  eb5e41cfd5df83b126cccf7a5483b05878ef637f<br />-  f88bbf9137d24d36d968ea6b2911786bfe103002<br />*Stack* <br />

Cannot read property 'map' of undefined)<br />[/vs/workbench/api/node/extHostDocumentsAndEditors.ts#L118:24 (apply)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/api/node/extHostDocumentsAndEditors.ts#L118:24 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L159:27 (_invokeHandler)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L159:27 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L108:39 (_receiveRequest)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L108:39 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L90:9 (call)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L90:9 (call))<br />	at /out/vs/workbench/node/extensionHostProcess.js:585:494 <no sourcemaps><br />	at /out/vs/workbench/node/extensionHostProcess.js:588:343 <no sourcemaps><br />	at /out/vs/workbench/node/extensionHostProcess.js:87:749 <no sourcemaps><br />[/vs/base/common/event.ts#L142:15 (fire)](https://github.com/microsoft/vscode/blob/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/base/common/event.ts#L142:15 (fire))<br />

**Comment by alexandrudima** [comment] 2018-03-28 22:18
Caused by running EH at version N+1 and the renderer at version N

Duplicate of #45547

**Closed** 2018-03-28 22:18 UTC
Labels: *duplicate, error-telemetry
