### ISSUE TITLE
Previously ran launch is always shown in the debug console

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#64438] opened 2018-12-05 15:51 UTC
Steps to repro

- Open VS Code repo
- Launch `Attach to Extension Host` and it fails
- Launch Git unit tests
- Debug console has a dropdown for above two
- Clear the console using clear action
- Dropdown disappears
- Launch Git unit tests again
🐛 Dropdown with `Attach to Extension Host` appears in the console

**Comment by isidorn** [comment] 2018-12-06 13:50
You have actually cleared the git unit tests debug console
And not the Attach to Extnesion Host which is left behind.
Once you start git again, the new session appears and the attach to extension host is there since it was not cleared (note you can not clear the last one).

For now closing as will not fix / as designed. If users complain about this and find it confusing I would be open to changing it.
Thanks

**Closed by isidorn** 2018-12-06 13:50 UTC
