### ISSUE TITLE
Extensions need to be reloaded

### ISSUE THREAD

**Issue by KaoImin** [microsoft/vscode#144955] opened 2022-03-12 15:08 UTC
Issue Type: <b>Bug</b>

All extensions prompt need to reload, even after reloading.

VS Code version: Code - Insiders 1.66.0-insider (6b7453421201c888b81eae5c04ec822a6423608f, 2022-03-11T05:17:19.559Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 4175)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (32.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 4175)|
|Memory (System)|31.32GB (12.71GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 4175)|
|Memory (System)|31.32GB (12.71GB free)|
|VM|0%|
</details><details><summary>Extensions (103)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.2
vscode-dash|dee|2.4.0
alloy-vscode|Don|0.1.6
vscode-rust-syntax|dun|0.0.32
rust-syntax|dus|0.6.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
gruvbox-ish|Gra|0.5.18
Lua|key|0.0.9
Lisp|mat|0.1.12
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.65.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
language-purescript|nwo|0.2.8
material-icon-theme|PKi|4.14.1
pytorch-snippets|SBS|1.0.2
vscode-autohotkey|sle|0.2.2
latex-support|tor|3.10.0
errorlens|use|3.4.2
vscode-icons|vsc|11.10.0
vim|vsc|1.22.2
pestfile|xor|0.2.0
lua-debug|act|1.53.0
markdown-toc|Ala|1.5.6
vscode-hie-server|ala|0.2.1
vscode-sqlite|ale|0.14.0
alloy|Ara|0.7.1
asciidoctor-vscode|asc|2.9.8
better-toml|bun|0.3.2
vscode-postgres|cko|1.4.0
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
alloy-vscode|Don|0.1.6
vscode-wasm|dts|1.3.1
vscode-rust-syntax|dun|0.0.32
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.3.0
code-runner|for|0.11.7
vscode-pull-request-github|Git|0.39.2022031015
mdmath|goe|2.7.4
go|gol|0.32.0
gc-excelviewer|Gra|4.2.53
debug-visualizer|hed|2.3.0
latex-workshop|Jam|8.23.0
c-cpp-flylint|jbe|1.11.0
asciidoctor-vscode|joa|2.8.0
rust-doc-viewer|JSc|2.0.1
solidity|Jua|0.0.137
nvim-ui-modifier|Jul|0.0.7
language-haskell|jus|3.4.0
Lua|key|0.0.9
marp-vscode|mar|1.5.0
rust-analyzer|mat|0.2.964
Lisp|mat|0.1.12
rainbow-csv|mec|2.0.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.20.0
vscode-language-pack-zh-hans|MS-|1.65.2
csharp|ms-|1.24.1
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.8.4
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
ide-purescript|nwo|0.25.11
language-purescript|nwo|0.2.8
erlang|pgo|0.8.4
vscode-manifest-yaml|Piv|1.32.0
material-icon-theme|PKi|4.14.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.5.1
pytorch-snippets|SBS|1.0.2
crates|ser|0.5.10
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.8.1
tabnine-vscode|Tab|3.5.26
latex-support|tor|3.10.0
codelf|unb|11.7.0
vscode-lldb|vad|1.6.10
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.17
docker|vsc|1.0.0
yaml|vsc|1.0.0
flowistry|wcr|0.5.11
autocomplete-english-word|wus|0.1.7
Pangu-Markdown|xlt|0.0.6
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
vscode-proto3|zxh|0.5.5

(8 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2022-03-12 15:12
/duplicate of #144900

Thanks @Lemmingh

**Closed** 2022-03-12 15:12 UTC
Labels: *duplicate
