### ISSUE TITLE
Uninstalling an extension should notify the user that a VSCode restart is required

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8298] opened 2016-06-28 10:10 UTC
Testing https://github.com/Microsoft/vscode/issues/8215:

- install extension 'mock-debug'
- create a launch config and a readme.md file with some lines of text
- start debugging

Observe: you should be able to step through the lines of the readme.md file

- from the extension viewlet uninstall 'mock-debug'
- start debugging

Observe: you get an error message that some *.js file is missing

Expected behaviour: after removing the extension, the debug type 'mock' should no longer be defined and the error message should say so.

Since a reload window fixes that, I suggest to always reload after an uninstall (the same as on install).

**Comment by isidorn** [comment] 2016-06-28 15:13
June to investigate

**Comment by gregvanl** [comment] 2016-06-29 18:51
Should we simply show a Disable button on the extension entry after Uninstall just like we show an Enable button after Install.  Pressing the Disable button, displays the restart prompt dialog (with slightly different wording "In order to disable this extension, ...."
Showing a Disable button also lets the user know that the extension is still active.

**Comment by isidorn** [comment] 2016-06-30 12:25
@gregvanl I like your idea however to implement it is a bit complex in the endgame. The issue is that once you uninstall the extension it is gone from our extension model, so if a user uninstalls an extension, goes to some other viewlet, and comes back to the extensions viewlet the extension should still be present in the list (so the user could disable). However this is not the case since it is no longer in our model. Due to this it would take some resructuring of the extensions model to support this - thus assigning this to July and Joao.

After discussing with @weinand for now we agreed to show a message box - so the same behavior that the stable vscode has. It does not blend nice with the whole new experience but we believe it is better than not showing anything. And it is nothing new since we already shipped with this.

**Comment by joaomoreno** [comment] 2016-07-04 12:31
Let's leave it this way until we can hot activate / deactivate.

**Closed by joaomoreno** 2016-07-04 12:31 UTC
Labels: bug, extensions

**Comment by riteshatsencha** [comment] 2016-10-18 15:02
Uninstalling extension on windows 10 does not show a message at all. Extension is definitely removed but user is not displayed any message. OS X is ok. Is this intentional?
