### ISSUE TITLE
Error: Extension host terminated when first started and on Reload Window

### ISSUE THREAD

**Issue by lucnoc** [Microsoft/vscode#6375] opened 2016-05-14 22:13 UTC
- VSCode Version: 1.1.0 (1.1.0)
- OS Version: OS X El Capitan 10.11.4

I tried this with different downloads, and it happens consistently: as the window opens the following error message shows in the top of the window:

Error: Extension host terminated unexpectedly. Please reload the window to recover.

Pressing Reload Window button causes main vscode window to go completely black and after the side bar and the status bar reappear the message is back.

I did try rm -rf ~/.vscode* and restart and also when open and clicking "Reload Window" button and in both cases the message is back.

Steps to Reproduce:
1. downloaded latest vscode from website
2. double click vscode executable

See screenshot with error in Developer Tools

![untitled](https://cloud.githubusercontent.com/assets/2250424/15270923/253ceb20-19e6-11e6-97b5-b5108f2a5b60.png)

I tried also to delete .sock file and restart vscode but that did not help

```
srwxr-xr-x  1 lucnoc  staff  0 May 14 15:07 /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd.sock
```

**Comment by bpasero** [comment] 2016-05-17 05:13
@lucnoc weird, not sure we heard an issue like this before. did you maybe start once as admin? could be a permission issue after all. 

does it also reproduce from our insider build? http://code.visualstudio.com/Download#insiders

**Comment by lucnoc** [comment] 2016-05-17 16:40
Thanks. I just download and double click the executable - not using sudo.
I did try the insider build before with same behavior - this is what I get when using the link you provided:
![untitled](https://cloud.githubusercontent.com/assets/2250424/15330726/f2dd4402-1c12-11e6-9367-bce0df1bda5b.png)

**Comment by bpasero** [comment] 2016-05-17 18:09
@alexandrudima @jrieken @joaomoreno @Tyriar any ideas?

**Comment by Tyriar** [comment] 2016-05-17 18:22
@lucnoc any interesting things about your environment you're aware of? I notice you're part of the `staff` group, I wouldn't think that would affect it though as I assume you're running under `lucnoc`.

I'm not aware of what the `s` bit is at the start of the file permissions (`srwxr-xr-x`), nor do I know what the file is actually used for. I don't seem to have a `/var/folders/` on Ubuntu.

**Comment by lnocera** [comment] 2016-05-18 00:01
@Tyriar on a different mac where I have no problem (same OS version) permissions are similar:

srwxr-xr-x  1 luciano  staff    0 May 17 13:14 vscode-8f6c21accac61bf60cabea3163e25b8237afb5af.sock

these file are created when vscode is running. The s I believe denotes a socket link -- see man ls under "The Long Format" and in wikipeadia https://en.wikipedia.org/wiki/Ls

**Comment by tomgilder** [comment] 2016-05-18 23:30
I'm having the exact same problem, also on OS X. 

I can run Code on a different user account, but not my own.

**Comment by bpasero** [comment] 2016-05-19 05:37
It looks like it fails to connect to or create the socket. moving to @joaomoreno to see if he has more ideas.

**Comment by alexandrudima** [comment] 2016-05-23 16:19
I think you might have some dead/stale vscode processes running that lock those `.sock` files. I am unsure if we attempt to always connect to the same `.sock` file or if their names are randomly generated, @joaomoreno definitely has the insights here (about the shared process, which looks like is the owner of these `.sock` files)

**Comment by joaomoreno** [comment] 2016-05-24 07:44
Very interesting...

Are your systems managed by some corporate network?

**Comment by lucnoc** [comment] 2016-05-24 18:55
@alexandrudima restart and checking processes does not seem to show anything related to vscode.

@joaomoreno nope this is my laptop - a MacBook Pro (15-inch, Early 2011) 2.2 GHz Intel Core i7 - 8 GB 1333 MHz DDR3 running OS X version 10.11.4 (15E65)

**Comment by joaomoreno** [comment] 2016-05-25 07:11
The socket files are not stale... OS X and Linux simply do not delete them on shutdown, but on startup. They can be deleted since @lucnoc was able to do so manually.

The shared process seems to be not launching at all in your system... since you never mentioned the existence of a `/var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock` file.

**Comment by lucnoc** [comment] 2016-05-31 17:09
@joaomoreno there is no Code-91fbfd-shared.sock but there is a Code-91fbfd.sock:
```
Old-MacBook-Pro:~ lucnoc$ ls -al /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock
ls: /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock: No such file or directory
Old-MacBook-Pro:~ lucnoc$ ls -al /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd.sock 
srwxr-xr-x  1 lucnoc  staff  0 May 31 09:17 /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd.sock
```

I manually copied `Code-91fbfd.sock` to `Code-91fbfd-shared.sock and restarted vscode but now I get:

```
shell.ts:416 connect ECONNREFUSED /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock: Error: connect ECONNREFUSED /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)e.onUnexpectedError @ shell.ts:416
shell.ts:416 Watcher terminated unexpectedly and is restarted again...e.onUnexpectedError @ shell.ts:416
```
changing permissions + to all does not help:

```
Old-MacBook-Pro:T lucnoc$ ls -al Code-91fbfd*
srwxrwxrwx  1 lucnoc  staff  0 May 31 09:17 Code-91fbfd-shared.sock
srwxrwxrwx  1 lucnoc  staff  0 May 31 09:51 Code-91fbfd.sock
```

and also tried to move 9c folder to __9c, restarting causes a new folder to be created:
```
bash-3.2# ls -al /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/
Code-91fbfd.sock  TemporaryItems/   com.apple.mail/   xcrun_db
```
but only Code-91fbfd.sock is created and I get the original error:

```
shell.ts:416 connect ENOENT /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock: Error: connect ENOENT /var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/Code-91fbfd-shared.sock
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```
 
This are the complete logs for the original error from developer tools *before* I tried creating the -shared file:
[1464711582728.log.txt](https://github.com/Microsoft/vscode/files/291673/1464711582728.log.txt)

**Comment by joaomoreno** [comment] 2016-06-01 07:37
Thanks for the log, @lucnoc, now I get to see the real issue.

@dbaeumer: from @lucnoc's log, it appears that the value in the `VSCODE_NLS_CONFIG` env variable is not valid JSON, making `bootstrap-amd.js` fail at line 20, thus preventing the shared process to launch at all. Any idea how this can happen?

**Comment by joaomoreno** [comment] 2016-06-01 08:45
@lucnoc, we are circling this out. Let me ask you to do a couple of things:

- In the Developer Tools' Console, give me the value you get when running `process.env['VSCODE_NLS_CONFIG']`.
- Also, give me the value you get when running `window.location.search`.

**Comment by lucnoc** [comment] 2016-06-02 03:26
@joaomoreno, here is the output:

```
process.env['VSCODE_NLS_CONFIG']
"{"locale":"en-us","availableLanguages":{}}
COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/LUCNOC/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/private/tmp/com.apple.launchd.onuhsKavd2/ServiceProcessSocket"

window.location.search
"?config=%7B%22pathArguments%22%3A%5B%5D%2C%22programStart%22%3A0%2C%22enablePerformance%22%3Afalse%2C%22verboseLogging%22%3Afalse%2C%22debugBrkExtensionHost%22%3Afalse%2C%22logExtensionHostCommunication%22%3Afalse%2C%22openNewWindow%22%3Afalse%2C%22openInSameWindow%22%3Afalse%2C%22gotoLineMode%22%3Afalse%2C%22diffMode%22%3Afalse%2C%22disableExtensions%22%3Afalse%2C%22waitForWindowClose%22%3Afalse%2C%22execPath%22%3A%22%2FApplications%2FVisual%20Studio%20Code.app%2FContents%2FMacOS%2FElectron%22%2C%22workspacePath%22%3A%22%2FUsers%2Flucnoc%2FDocuments%2Frtlogs.git%22%2C%22filesToOpen%22%3A%5B%5D%2C%22filesToCreate%22%3A%5B%5D%2C%22filesToDiff%22%3A%5B%5D%2C%22extensionsToInstall%22%3A%5B%5D%2C%22appName%22%3A%22Visual%20Studio%20Code%22%2C%22applicationName%22%3A%22code%22%2C%22darwinBundleIdentifier%22%3A%22com.microsoft.VSCode%22%2C%22appRoot%22%3A%22%2FApplications%2FVisual%20Studio%20Code.app%2FContents%2FResources%2Fapp%22%2C%22version%22%3A%221.1.1%22%2C%22commitHash%22%3A%22def9e32467ad6e4f48787d38caf190acbfee5880%22%2C%22appSettingsHome%22%3A%22%2FUsers%2Flucnoc%2FLibrary%2FApplication%20Support%2FCode%2FUser%22%2C%22appSettingsPath%22%3A%22%2FUsers%2Flucnoc%2FLibrary%2FApplication%20Support%2FCode%2FUser%2Fsettings.json%22%2C%22appKeybindingsPath%22%3A%22%2FUsers%2Flucnoc%2FLibrary%2FApplication%20Support%2FCode%2FUser%2Fkeybindings.json%22%2C%22userExtensionsHome%22%3A%22%2FUsers%2Flucnoc%2F.vscode%2Fextensions%22%2C%22extensionTips%22%3A%7B%22ms-vscode.csharp%22%3A%22%7B**%2F*.cs%2C**%2Fproject.json%2C**%2Fglobal.json%2C**%2F*.csproj%2C**%2F*.sln%7D%22%2C%22ms-vscode.mono-debug%22%3A%22%7B**%2F*.cs%2C**%2F*.csproj%2C**%2F*.sln%7D%22%2C%22msjsdiag.debugger-for-chrome%22%3A%22%7B**%2F*.ts%2C**%2F*.tsx**%2F*.js%2C**%2F*.jsx%2C**%2F*.es6%7D%22%2C%22lukehoban.Go%22%3A%22**%2F*.go%22%2C%22ms-vscode.PowerShell%22%3A%22%7B**%2F*.ps%2C**%2F*.ps1%7D%22%2C%22austin.code-gnu-global%22%3A%22%7B**%2F*.c%2C**%2F*.cpp%2C**%2F*.h%7D%22%2C%22Ionide.Ionide-fsharp%22%3A%22%7B**%2F*.fsx%2C**%2F*.fsi%2C**%2F*.fs%2C**%2F*.ml%2C**%2F*.mli%7D%22%2C%22dbaeumer.vscode-eslint%22%3A%22%7B**%2F*.js%2C**%2F*.jsx%2C**%2F*.es6%7D%22%2C%22eg2.tslint%22%3A%22%7B**%2F*.ts%2C**%2F*.tsx%7D%22%2C%22Kasik96.format-indent%22%3A%22%7B**%2F*.php%7D%22%2C%22felixfbecker.php-debug%22%3A%22%7B**%2F*.php%7D%22%2C%22linyang95.phpmd%22%3A%22%7B**%2F*.php%7D%22%2C%22ikappas.phpcs%22%3A%22%7B**%2F*.php%7D%22%2C%22tht13.python%22%3A%22%7B**%2F*.py%7D%22%2C%22donjayamanne.python%22%3A%22%7B**%2F*.py%7D%22%2C%22magicstack.MagicPython%22%3A%22%7B**%2F*.py%7D%22%2C%22saviorisdead.RustyCode%22%3A%22%7B**%2F*.rs%2C**%2F*.rslib%7D%22%2C%22hars.CppSnippets%22%3A%22%7B**%2F*.cpp%2C**%2F*.cc%2C**%2F*.h%7D%22%2C%22mitaki28.vscode-clang%22%3A%22%7B**%2F*.cpp%2C**%2F*.cc%2C**%2F*.h%7D%22%2C%22ms-vscode.cpptools%22%3A%22%7B**%2F*.c%2C**%2F*.cpp%2C**%2F*.cc%2C**%2F.cxx%2C**%2F*.hh%2C**%2F*.hpp%2C**%2F*.hxx%2C**%2F*.h%7D%22%2C%22seanmcbreen.Spell%22%3A%22%7B**%2F*.md%7D%22%2C%22ms-vscode.Theme-MarkdownKit%22%3A%22%7B**%2F*.md%7D%22%2C%22DavidAnson.vscode-markdownlint%22%3A%22%7B**%2F*.md%7D%22%7D%2C%22mainIPCHandle%22%3A%22%2Fvar%2Ffolders%2F9c%2Fgkt2df7j11b965s2c1tgxvk80000gn%2FT%2FCode-91fbfd.sock%22%2C%22sharedIPCHandle%22%3A%22%2Fvar%2Ffolders%2F9c%2Fgkt2df7j11b965s2c1tgxvk80000gn%2FT%2FCode-91fbfd-shared.sock%22%2C%22isBuilt%22%3Atrue%2C%22crashReporter%22%3A%7B%22productName%22%3A%22VSCode%22%2C%22companyName%22%3A%22Microsoft%22%2C%22submitURL%22%3A%22https%3A%2F%2Fticinocrashreporter.azurewebsites.net%2Fcrash%22%2C%22extra%22%3A%7B%22vscode_sessionId%22%3A%22%24(sessionId)%22%2C%22vscode_version%22%3A%22%24(version)%22%2C%22vscode_commit%22%3A%22%24(commit)%22%7D%7D%2C%22extensionsGallery%22%3A%7B%22serviceUrl%22%3A%22https%3A%2F%2Fmarketplace.visualstudio.com%2F_apis%2Fpublic%2Fgallery%22%2C%22cacheUrl%22%3A%22https%3A%2F%2Fvscode.blob.core.windows.net%2Fgallery%2Findex%22%2C%22itemUrl%22%3A%22https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%22%7D%2C%22welcomePage%22%3A%22https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D723048%22%2C%22productDownloadUrl%22%3A%22https%3A%2F%2Fcode.visualstudio.com%22%2C%22releaseNotesUrl%22%3A%22https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D533483%23vscode%22%2C%22licenseUrl%22%3A%22https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D533485%22%2C%22updateFeedUrl%22%3A%22https%3A%2F%2Fvscode-update.azurewebsites.net%2Fapi%2Fupdate%2Fdarwin%2Fstable%2Fdef9e32467ad6e4f48787d38caf190acbfee5880%22%2C%22updateChannel%22%3A%22stable%22%2C%22aiConfig%22%3A%7B%22key%22%3A%228aa6e059-82b6-46f6-8138-5a43aa3dd621%22%2C%22asimovKey%22%3A%22AIF-444c3af9-8e69-4462-ab49-4191e6ad1916%22%7D%2C%22sendASmile%22%3A%7B%22reportIssueUrl%22%3A%22https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D534872%22%2C%22requestFeatureUrl%22%3A%22https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D533482%22%7D%2C%22enableTelemetry%22%3Atrue%2C%22userEnv%22%3A%7B%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F9c%2Fgkt2df7j11b965s2c1tgxvk80000gn%2FT%2F%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.xFgRZxUhDl%2FRender%22%2C%22USER%22%3A%22lucnoc%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.kqCbyP2x79%2FListeners%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22PATH%22%3A%22%2Fopt%2Flocal%2Fbin%3A%2Fopt%2Flocal%2Fsbin%3A%2Fopt%2Flocal%2Fbin%3A%2Fopt%2Flocal%2Fsbin%3A%2Fopt%2Flocal%2Fbin%3A%2Fopt%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%3A%2Fopt%2FX11%2Fbin%3A%2Fusr%2Flocal%2Fmongodb%2Fbin%3A%2FUsers%2Flucnoc%2Fbin%3A%2Fusr%2Flocal%2Fbin%22%2C%22PWD%22%3A%22%2F%22%2C%22EDITOR%22%3A%22emacs%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22XPC_SERVICE_NAME%22%3A%22com.microsoft.VSCode.74912%22%2C%22SHLVL%22%3A%221%22%2C%22HOME%22%3A%22%2FUsers%2Flucnoc%22%2C%22VSCODE_NLS_CONFIG%22%3A%22%7B%5C%22locale%5C%22%3A%5C%22en-us%5C%22%2C%5C%22availableLanguages%5C%22%3A%7B%7D%7D%5CnCOM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS%2FUSERS%2FLUCNOC%2FLIBRARY%2FAPPLICATION_SUPPORT%2FGOOGLE%2FCHROME_SOCKET%3D%2Fprivate%2Ftmp%2Fcom.apple.launchd.onuhsKavd2%2FServiceProcessSocket%22%2C%22LOGNAME%22%3A%22lucnoc%22%2C%22PKG_CONFIG_PATH%22%3A%22%2Fusr%2Flocal%2Flib%2Fpkgconfig%3A%22%2C%22MONGO_PATH%22%3A%22%2Fusr%2Flocal%2Fmongodb%22%2C%22DISPLAY%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.h09Nl1vodu%2Forg.macosforge.xquartz%3A0%22%2C%22PHP_AUTOCONF%22%3A%22%2Fusr%2Flocal%2Fbin%2Fautoconf%22%2C%22_%22%3A%22%2Fusr%2Fbin%2Fenv%5Cn%22%7D%2C%22recentFiles%22%3A%5B%5D%2C%22recentFolders%22%3A%5B%22%2FUsers%2Flucnoc%2FDocuments%2Frtlogs.git%22%5D%7D"
```

**Comment by joaomoreno** [comment] 2016-06-02 07:48
Yep there is definitely a problem there, still can't figure out how, though...

In a terminal, what do you get with `$SHELL -ilc env`?

**Comment by lucnoc** [comment] 2016-06-03 00:30
```
Old-MacBook-Pro:~ lucnoc$ $SHELL -ilc env
Restored session: Thu Jun 2 17:28:51 PDT 2016
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/9c/gkt2df7j11b965s2c1tgxvk80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.xFgRZxUhDl/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=37CEA60A-C93C-41E9-A031-2AF628BBA879
USER=lucnoc
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.kqCbyP2x79/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mongodb/bin:/Users/lucnoc/bin:/usr/local/mongodb/bin:/Users/lucnoc/bin:/usr/local/bin
PWD=/Users/lucnoc
EDITOR=emacs
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/lucnoc
SHLVL=2
COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/LUCNOC/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/private/tmp/com.apple.launchd.onuhsKavd2/ServiceProcessSocket
LOGNAME=lucnoc
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:
DISPLAY=/private/tmp/com.apple.launchd.h09Nl1vodu/org.macosforge.xquartz:0
MONGO_PATH=/usr/local/mongodb
PHP_AUTOCONF=/usr/local/bin/autoconf
_=/usr/bin/env
Saving session...
...saving history...
...completed.
```

**Comment by joaomoreno** [comment] 2016-06-03 07:34
Ok, figured it out, thanks a lot @lucnoc!

You seem to have a variable named with forward slashes, somehow, and that breaks our [parsing code](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/env.ts#L42). Parsing env is proving to be a real challenge... we might try to go another route and try spawning `node -p 'JSON.stringify(process.env)'` to get an unequivocal environment.

**Closed** 2016-06-03 08:48 UTC
Labels: bug, freeze-slow-crash

**Comment by lnocera** [comment] 2016-06-03 16:05
thanks @joaomoreno! Should I try the insider build?

**Comment by lucnoc** [comment] 2016-06-10 19:19
@joaomoreno would you have a workaround I tried to unset `COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/LUCNOC/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET` opening the package and editing Content/Resources/app/bin/code but I can't seem to find how to escape it. Also removed chrome...

**Comment by joaomoreno** [comment] 2016-06-13 05:48
Unfortunately not... You could use our [Insiders build](https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders) for a while, which already has the fix.

**Comment by lucnoc** [comment] 2016-06-17 14:37
Thanks! confirming that http://code.visualstudio.com/Download#insiders is fixed

**Comment by dbaeumer** [comment] 2016-06-20 08:46
Marking as verified based on comment https://github.com/Microsoft/vscode/issues/6375#issuecomment-226786223

**Comment by anthonyclarka2** [comment] 2017-08-16 18:44
I had an env var that was causing the same socket problem with both the normal build and the insiders nightly.

It was this:  "triangle=$(echo -e '\xEE\x82\xB0')"

Which shows in the output of "env" as "triangle=" (if your font has unicode support)

Not sure if that's a WONTFIX or not, but thought you should know.
