### ISSUE TITLE
Visibility of Source Control Viewlet (for "when" contexts)

### ISSUE THREAD

**Issue by ebynum** [Microsoft/vscode#41280] opened 2018-01-08 11:25 UTC
There is not currently a way to detect the visibility (or focus) of the "Source Control Viewlet" like there is for the Search and Explorer Viewlets.
[searchViewletVisible, searchInputBoxFocus, explorerViewletVisible, explorerViewletFocus]

My use-case for this is to allow intelligent toggling of the sidebar viewlets (roughly like https://github.com/Microsoft/vscode/issues/41186), although I suspect there are other uses for the visibility and focus when clause contexts.

My suggested names would be scmViewletVisible, scmViewletFocus, scmInputBoxFocus.

**Comment by yume-chan** [comment] 2018-04-28 09:34
Duplicate of #17722

`"when": "activeViewlet == 'workbench.view.scm'"`

**Closed** 2018-04-30 07:26 UTC
Labels: feature-request, scm
