### ISSUE TITLE
blank proxy popup window

### ISSUE THREAD

**Issue by zr0395** [microsoft/vscode#106468] opened 2020-09-11 09:54 UTC
When I start VSCode 1.49.0 the proxy authentication window pops up, but is completly blank (see picture below).

- VSCode Version: 1.49.0 (e790b93 2020-09-10T13:22:08.892Z)
- OS Version:         Windows_NT x64 10.0.17763

The same happens with VSCode-Insiders 1.49.0 f66741d 2020-08-31T05:32:36.938Z

It worked with a privious version:
Version: 1.45.0-insider
Commit: 4f05de82a75569601bc2dc894023383b4ce1c2c0
Date: 2020-04-13T17:53:50.995Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

![vscode](https://user-images.githubusercontent.com/11992971/92906803-0d295000-f425-11ea-963e-45c2fa9a8be6.png)

**Comment by chrmarti** [comment] 2020-09-14 07:26
Could be #106434. Could you check the latest Insiders build (cca20eba from 9/12 or later)?

**Comment by zr0395** [comment] 2020-09-14 07:50
> 
> 
> Could be #106434. Could you check the latest Insiders build ([cca20eb](https://github.com/microsoft/vscode/commit/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648) from 9/12 or later)?

Sure.

**Comment by zr0395** [comment] 2020-09-14 07:56
> 
> 
> Could be #106434. Could you check the latest Insiders build ([cca20eb](https://github.com/microsoft/vscode/commit/cca20eba8974b1d6b6a9b71bf4e60a29c8f26648) from 9/12 or later)?

I tested cca20eb and the error is still there.

**Comment by bpasero** [comment] 2020-09-15 06:36
I cannot reproduce with latest insiders:

![image](https://user-images.githubusercontent.com/900690/93174541-6e576900-f72e-11ea-91c0-3bd7b86a6d49.png)

I followed the steps from https://github.com/microsoft/vscode/issues/106489#issue-699287308 on Windows.

Also, the blank window should not happen as a result of https://github.com/microsoft/vscode/issues/106434. If you hit https://github.com/microsoft/vscode/issues/106434 you will see the dialog closing immediately.

Is there any output when you run `code-insiders --verbose` and follow these steps that you could attach?

**Comment by zr0395** [comment] 2020-09-15 07:31
[verbose.txt](https://github.com/microsoft/vscode/files/5223150/verbose.txt)

This is the output I get with --verbose.

**Comment by bpasero** [comment] 2020-09-15 07:33
@zr0395 is that the full output from the command line? I am missing specific output from the windows itself, they should start with something like this: `[16237:0915/093259.345021:INFO:CONSOLE(1705)]`

The reason I ask is because I wonder if the auth dialog that opens throws an error. To clarify, you never see the controls to type username and password right?

**Comment by zr0395** [comment] 2020-09-15 07:36
I will check again, give me a second.

Yes that right.

**Comment by zr0395** [comment] 2020-09-15 07:47
okay it looks like I found the error. I was starting vscode from a network drive.
I copied it to my lokal drive and started it and the proxy authentication worked.

Anyways I didn't find the output in the main log you discribed.

**Comment by bpasero** [comment] 2020-09-15 07:56
@joaomoreno fyi this maybe unrelated and could point to an issue with supporting the auth dialog from network drives. Though checking the code it seems we load the window like other windows and if something was going wrong with how we compute paths it would probably fail for the workbench too. 

I added network drive support to https://github.com/microsoft/vscode/issues/106489

**Closed by bpasero** 2020-09-15 07:56 UTC
Labels: needs more info, new release, proxy

**Comment by bpasero** [comment] 2020-09-15 15:06
Hmmmmmm:

https://github.com/Microsoft/vscode/blob/836fbb1b5db08306d3e90933b4996e4570a59e04/src/bootstrap-window.js#L243-L243
