### ISSUE TITLE
Able to see Outline and Tree at the same time

### ISSUE THREAD

**Issue by daslicht** [Microsoft/vscode#58526] opened 2018-09-12 15:07 UTC
It would be very useful if we could see the outline  and the tree at the same time.
Swithing between both is less optimal.

Maybe make teh outline dockable so athat we could move iot to the right of teh window ?

**Comment by jrieken** [comment] 2018-09-13 07:28
/duplicate of Alternative locations for the outline view feature-request outline under-discussion workbench-layout
#49923

**Closed** 2018-09-13 07:28 UTC
Labels: *duplicate, outline
