### ISSUE TITLE
Tasks: Allow programmatic problem matcher

### ISSUE THREAD

**Issue by onwsk8r** [microsoft/vscode#51957] opened 2018-06-15 05:33 UTC
Two of my favorite uses for tasks are to run unit and integration tests, and most of the tooling I use to accomplish that can produce JSON output. I think VSCode is the only IDE on the planet that has a concept of a `problemMatcher`, or at least the best, and it would be so cool if I could trade string parsing for object parsing.

One reason you want to support this format is because most developers probably wouldn't consider a small change in reporting format to be a breaking change - especially when they already have a JSON format. But that one little change can make an entire regex explode all over your screen, potentially damaging code that used to pass. Another reason you'll love it is because, per RFC8259, JSON has to be in UTF-8. One reason we'd all love it is because I can use the same test command with VSCode that I use with automated testing tools. That may not seem all that significant, but less has never been more than it is with computer programming. Oh, and one last reason is because some of those developers may try to pretty up the formatting (eg assuming it's running in an 80x24 terminal for long lines, use things like `tput`, etc), which may bling up your terminal, but it will just serve to break my regex.

Zero issues turned up when I searched to see what kind of progress you were making towards this feature, and I'd be more shocked to find out I'm the first person that's requested it than to find out that there's already an open issue that I missed, so apologies in advance if that's the case.

If you were to implement this using `jq`-style syntax, the following Mocha output
```json
["start",{"total":3}]
["pass",{"title":"should parse a TSLA message correctly","fullTitle":"Message should parse a TSLA message correctly","duration":2,"currentRetry":0}]
["pass",{"title":"should parse a TSRO message correctly","fullTitle":"Message should parse a TSRO message correctly","duration":1,"currentRetry":0}]
["fail",{"title":"should calculate total volume correctly","fullTitle":"Message should calculate total volume correctly","duration":1,"currentRetry":0,"err":"expected 10765733.922434954 to equal 10981023","stack":"AssertionError: expected 10765733.922434954 to equal 10981023\n    at Context.it (src/message_test.ts:54:42)"}]
["end",{"suites":1,"tests":3,"passes":2,"pending":0,"failures":1,"start":"2018-06-15T03:15:44.322Z","end":"2018-06-15T03:15:44.344Z","duration":22}]
```
could be matched as:
```json
{
    "severity": ".[0] # Hackish I know",
    "message": ".[1].stack",
    "beginsPattern": ".[0] == 'start'",
    "endsPattern": ".[0] == 'end'"
}
```

**Comment by dbaeumer** [comment] 2018-06-15 07:01
Actually that is a cool idea. Will definitely ease parsing problems where the tools supports JSON format.

**Comment by alpalla** [comment] 2019-05-07 14:30
Hi! I'd like to help out with this issue, would it be possible to get some more pointers?

**Comment by dbaeumer** [comment] 2019-05-08 09:29
@alexr00 instead of having a more sophisticated problem matcher it might be a good idea to use the custom task for this. However that would need some additional API to give them access to the managed diagnostic collection.

**Comment by alexr00** [comment] 2019-05-16 17:27
I think that this would fit nicely as part of the "custom problem" matcher idea, where a problem matcher uses code to consume the output instead of the using regex. The custom task sounds a bit heavy for this since users would need to deal with the launching themselves.

**Comment by alexr00** [comment] 2019-08-07 14:47
duplicate of #59337

**Closed by alexr00** 2019-08-07 14:47 UTC
Labels: feature-request, tasks
