### ISSUE TITLE
In Windows, vscode, the files to include section in search is case-sensitive.

### ISSUE THREAD

**Issue by TwoBrushes** [microsoft/vscode#234238] opened 2024-11-20 04:53 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Windows 11 23h2

In the Windows system, file names are case-insensitive, so it is not reasonable to use case sensitivity in the “files to include”.

![Image](https://github.com/user-attachments/assets/d89115db-9c3d-41ef-9477-30deabe1f230)
![Image](https://github.com/user-attachments/assets/ca7d4a0c-a209-4d77-ad0a-a2be2581a6d7)

**Comment by diminutivesloop** [comment] 2024-11-22 18:15
I agree although this shouldn't be restricted to Windows as Mac OS is also case-insensitive. It would also be great if these fields supported "smart" behavior like that enabled by `search.smartCase`.

**Comment by osortega** [comment] 2024-12-20 20:58
Duplicate of https://github.com/microsoft/vscode/issues/10633
Closing this one

/duplicate

**Closed by osortega** 2024-12-20 20:58 UTC
Labels: bug, search

**Comment by dmitrivMS** [comment] 2026-01-14 08:03
This is done.
