### ISSUE TITLE
Sass TM language: `content`, `cursor`, `backdrop-filter` properties

### ISSUE THREAD

**Issue by atomiks** [Microsoft/vscode#65573] opened 2018-12-22 02:19 UTC
- VSCode Version: 1.30.1
- OS Version: macOS 10.14.1

1. The Sass TM language is scoping these properties with `entity.name.tag` instead of `support.type.property-name`:

- `cursor`
- `content`

Which makes them a different color from other properties

2. The regular CSS and Sass languages are missing the `support.type.property-name` scope for the `backdrop-filter` property.

**Comment by usernamehw** [comment] 2018-12-22 10:30
The first part is a duplicate of https://github.com/atom/language-sass/issues/226

**Comment by alexr00** [comment] 2019-01-04 09:43
This issue was moved to atom/language-sass#264

**Closed** 2019-01-04 09:43 UTC
