### ISSUE TITLE
Folded code regions should not show region marker

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#146952] opened 2022-04-06 20:42 UTC
Just started using region markers to fold chunks of code (Python). When folded, I see this:
![image](https://user-images.githubusercontent.com/26465923/162066960-23ecce4a-0c39-41bc-aa3e-ebc48d328b25.png)

This comes from code like this:
```
# region Example 1: blah blah blah
```

The `region` marker should be hidden when folded, so I just see the comment following it as the "title" of the region.

`region` is case sensitive so it's unsightly and inflexible, in my opinion.

**Comment by aeschli** [comment] 2022-04-07 09:39
I thin it's fair to say that this is a duplicate of https://github.com/microsoft/vscode/issues/83458,
depending on https://github.com/microsoft/vscode/issues/70794

**Closed by aeschli** 2022-04-07 09:39 UTC
