### ISSUE TITLE
Zoomed out terminal glitch 

### ISSUE THREAD

**Issue by tparisotto** [microsoft/vscode#129389] opened 2021-07-26 10:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 Pro Version 20H2

Steps to Reproduce:

1. Open Terminal tab in VS Code
2. Zoom out the terminal with `ctrl + -`
3. Execute commands that print text

The rectangle glitches will add up in the terminal window and will only disappear if the terminal is killed
![Screenshot 2021-07-26 123058](https://user-images.githubusercontent.com/48412924/126976186-3db6fb59-a291-40f0-907b-641e3eef3315.png)

**Comment by IllusionMH** [comment] 2021-07-26 11:01
/duplicate of #106981

Please check Insiders build to see if it's still reproducible for you https://code.visualstudio.com/insiders/

**Closed** 2021-07-26 11:01 UTC
Labels: *duplicate
