### ISSUE TITLE
CSS Grid Syntax: "grid" shorthand property not supported

### ISSUE THREAD

**Issue by dmbdesignpdx** [Microsoft/vscode#42177] opened 2018-01-26 02:25 UTC
No fire here; this is more of an FYI.

<br>

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
file-icons|fil|1.0.7
ginfuru-vscode-jekyll-syntax|gin|0.0.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. In a CSS or SCSS document, declare a `grid` property with an appropriate value within a selector.

The property is flagged as a problem: "Unknown property: 'grid'".

![image](https://user-images.githubusercontent.com/5041305/35422341-017b982a-01fd-11e8-83ca-cf9e8b40c35a.png)

Verification that the property does, in fact, exist:
[W3C: grid-shorthand](https://www.w3.org/TR/css-grid-1/#grid-shorthand)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2018-01-26 05:07
Duplicate of https://github.com/Microsoft/vscode/issues/32499

Hey @aeschli, looks like atom fixed this upstream if you want to pull in the updated grammar

**Closed** 2018-01-26 15:23 UTC
Labels: css-less-sass
