### ISSUE TITLE
Images are not loaded in the tooltip through VS Code Remote SSH

### ISSUE THREAD

**Issue by andreeageorgian** [microsoft/vscode#140920] opened 2022-01-18 16:16 UTC
- VS Code Version: 1.63.2
- OS Version: Ubuntu 18.04.5 LTS

Steps to Reproduce:

1. Open a remote workspace with VS Code Remote SSH.

2. Insert a comment containing an image with an absolute path.

3. ![img1](https://user-images.githubusercontent.com/25352050/149965691-9fe41099-1595-48d9-a0f6-136e92c13535.png)
  The image is not loaded, although it does exist:
  ![img2](https://user-images.githubusercontent.com/25352050/149966449-1e46440e-3bcc-4d44-ae14-c368e0ee202e.png)

It looks like the issue appeared after this commit[ #136687](https://github.com/microsoft/vscode/pull/136687).

Thank you for your support! :)

**Comment by mjbvz** [comment] 2022-01-18 20:40
Duplicate of #137632

**Closed by mjbvz** 2022-01-18 20:40 UTC
