### ISSUE TITLE
plugin 'Sorting HTML and Jade attributes' breaks in v1.10.1

### ISSUE THREAD

**Issue by beeplin** [Microsoft/vscode#21967] opened 2017-03-04 08:22 UTC
- VSCode Version: 1.10.1
- OS Version: windows 10 x64 1607

The plugin 'Sorting HTML and Jade attributes' works fine in v1.9.1 but breaks in v1.10.1. It can still sort HTML attributes, but with it installed, the original format function (alt+shift+f) is not working.

Steps to Reproduce:

1. install plugin 'Sorting HTML and Jade attributes': https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-attrs-sorter
2. open a HTML file and press alt+shift+f to format it: not working

(https://github.com/mrmlnc/vscode-attrs-sorter/issues/31)

**Comment by mrmlnc** [comment] 2017-03-06 12:41
**Note:** IMHO this is not related to my plugin, because he have no keyboard shortcuts by default and I don't see the breaking changes in the changelog.

**Comment by aeschli** [comment] 2017-04-07 07:50
@mrmlnc The issue is against the 'Sorting HTML and Jade attributes' extension no longer working. Please investigate on your side and then file a specific bug on what's wrong in VSCode. I  don't know your the extension is expected to do or what it did before.

My guess is that it's format edits are conflicting with the formatting edits from the built-in html extension. That's a common problem if there is more than one formatter installed for the same language. To solve that you can disable the built-in formatter with `"html.format.enable": false`.
I'd actually suggest to not hook on the format action as your tool does much more than a typical formatter does. Normally a formatter just modifies whitespace. 

Closing this issue.

**Closed by aeschli** 2017-04-07 07:50 UTC

**Comment by mrmlnc** [comment] 2017-05-09 15:34
@aeschli,

Well, it's a conflict between VS Code built-in formatter and extension formatter. But how I can resolve this conflict?

I now have same issue with a different extension – `vscode-postcss-sorting`. And built-in formatter has no `css.format.enable` option (also, `scss` and `less`).

Just Gif for future discussion.

#### Run plugin from command

<details>

<summary>GIF</summary>

![command](https://cloud.githubusercontent.com/assets/7034281/25858807/5a6d6ba6-34e5-11e7-95a2-7e811e95d510.gif)

</details>

<details>

<summary>Result object</summary>

![command-result](https://cloud.githubusercontent.com/assets/7034281/25858739/203827dc-34e5-11e7-92d0-cb4717732f45.png)

</details>

#### Run plugin as formatter

<details>

<summary>GIF</summary>

![formatter](https://cloud.githubusercontent.com/assets/7034281/25858916/aa99e262-34e5-11e7-81e0-d624f39f1714.gif)

</details>

<details>

<summary>Result object</summary>

![formatter-result](https://cloud.githubusercontent.com/assets/7034281/25858999/e51b9cc8-34e5-11e7-9dcb-ddb152b4966a.png)

</details>

**Comment by aeschli** [comment] 2017-05-10 10:36
There is no built-in css formatter...

**Comment by aeschli** [comment] 2017-05-11 08:59
@jrieken Can you reply to the question above? Any recommendations on how extensions can prevent conflicts?

**Comment by mrmlnc** [comment] 2017-08-11 10:44
> @jrieken Can you reply to the question above? **Any recommendations on how extensions can prevent conflicts**?

Gentle ping :)

**Comment by jrieken** [comment] 2017-08-14 08:36
Well, our recommendation is to have configuration options to enable/disable a formatter: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_multiple-formatters.
