### ISSUE TITLE
Source Control Spinner No Longer Animates

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#25200] opened 2017-04-23 01:03 UTC
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Open a project that has source control enabled
2. Make some changes, save them, and commit them
3. Click the circular spinner icon

Expected outcome: spinner icon animation plays when push is occurring
Actual outcome: spinner icon animation no longer plays

I think this stopped working with the April release. It's not mission critical by any means, but I miss it.

<img width="161" alt="screen shot 2017-04-22 at 6 02 00 pm" src="https://cloud.githubusercontent.com/assets/16694050/25309577/d68782e8-2785-11e7-9d9f-aa330c965b02.png">

**Comment by mjbvz** [comment] 2017-04-24 05:37
This sounds like a duplicate of  #23975. Please give the latest insiders builds a try to verify that this has been fixed

**Closed by mjbvz** 2017-04-24 05:37 UTC
Labels: duplicate
