### ISSUE TITLE
Cannot display _ in terminal.

### ISSUE THREAD

**Issue by smallp** [Microsoft/vscode#39120] opened 2017-11-25 06:05 UTC
- VSCode Version:1.18.1
- OS Version:Ubuntu 16.10
![2017-11-25 14-03-18](https://user-images.githubusercontent.com/10028968/33227922-6aa900a6-d1e9-11e7-8d6e-7a48760d7812.png)

Steps to Reproduce:

1.print `_` in bash
2.cannot display `_` but it exist.
Reproduces without extensions: Yes

**Comment by maxibanki** [comment] 2017-11-25 14:15
Duplicate of #38133

**Closed** 2017-11-25 18:50 UTC
Labels: *duplicate, integrated-terminal

**Comment by Tyriar** [comment] 2017-12-12 17:50
https://github.com/Microsoft/vscode/issues/35901
