### ISSUE TITLE
fold can only handle 18 block

### ISSUE THREAD

**Issue by Inori-Lover** [microsoft/vscode#78756] opened 2019-08-09 04:51 UTC
- VSCode Version: `1.37.0(user setup)`
- OS Version: `Windows_NT x64 10.0.17763`

Steps to Reproduce:

1. Paste those [js code](https://paste.ubuntu.com/p/WmsrkpGvVP) into vscode
2. change Language to javascript
3. if the bug is real(?), you can see vscode donot really fold all block

Does this issue occur when all extensions are disabled?: Yes

my english is not good, feel free to help me translate this commit！

**Comment by Inori-Lover** [comment] 2019-08-09 04:52
![image](https://user-images.githubusercontent.com/9866055/62754926-71e8dd00-baa4-11e9-92f3-baeb253eaf9f.png)

**Comment by mjbvz** [comment] 2019-08-11 09:48
Duplicate of https://github.com/microsoft/TypeScript/issues/32328

**Closed by mjbvz** 2019-08-11 09:48 UTC
Labels: new release
