### ISSUE TITLE
args format not correct in help

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/vscode#37128] opened 2017-10-30 09:38 UTC
- VSCode Version: 1.17.2 b813d12980308015bcd2b3a2f6efa5c810c33ba5
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. `code --help`
```
Usage: code [options] [paths...]

Options:
  -d, --diff <file> <file>                                     Compare two files with each other.
  -a, --add <dir>                                              Add folder(s) to the last active window.
  -g, --goto <file:line[:character]>                           Open a file at the path on the specified line and character position.
  --locale <locale>                                            The locale to use (e.g. en-US or zh-TW).
  -n, --new-window                                             Force a new instance of Code.
  -p, --performance                                            Start with the 'Developer: Startup Performance' command enabled.
  --prof-startup                                               Run CPU profiler during startup
  -r, --reuse-window                                           Force opening a file or folder in the last active window.
  --user-data-dir <dir>                                        Specifies the directory that user data is kept in, useful when running as root.

...
```

2. `sudo code --user-data-dir ~/.vscode file.txt`
error: `It is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.`

3. `sudo code --user-data-dir='~/.vscode' file.txt`   It's OK

**Comment by bpasero** [comment] 2017-10-30 10:26
I think the warning about running as admin is off because I can set a user-data-dir without having to use a "=".

**Comment by stoiandan** [comment] 2018-07-12 22:04
I'd like to help Any tips?

**Comment by Tyriar** [comment] 2018-07-14 18:04
@stoiandan I'd start at argv.ts to try to figure out why = works but space doesn't (as the docs say, and how --locale works?)

**Comment by stoiandan** [comment] 2018-07-15 17:30
`./scripts/code.sh --help` will not show the help options, but it will instead open vscode. That shound't happen, right?
Talking about building from source code.

**Comment by stoiandan** [comment] 2018-07-15 18:29
Need to use.`/scripts/code-cli.sh --help`, got it.

**Comment by stoiandan** [comment] 2018-07-16 04:09
I still can't figure out how to debug `code-cli.sh`.

**Comment by Tyriar** [comment] 2018-07-16 16:17
@stoiandan I think you can debug it by attaching to the process using the configured launch.json. You could also run `code-cli.sh --verbose` to get logs in the terminal

**Comment by stoiandan** [comment] 2018-07-17 04:39
@Tyriar 
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).`
I've read it has to do with `chrome processes`, I don't even have chrome/chromium installed. And I've tried to kill a `code` process that has the word chrome in it. Any idea?

**Comment by aileronajay** [comment] 2018-09-09 09:09
This seems to be a duplicate of the issue https://github.com/Microsoft/vscode/issues/41429

and seems to have been fixed by 
https://github.com/Microsoft/vscode/commit/262660203e92f1a52a063274cabbb6af628acd63

**Comment by Tyriar** [comment] 2018-09-10 13:51
Thanks @aileronajay! We're just in the process of cleaning up our issues so this is very helpful 😃

**Closed by Tyriar** 2018-09-10 13:51 UTC
Labels: bug, good first issue, help wanted, linux
