### ISSUE TITLE
Replace: right hand side gets broken when input or replace gets changed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57143] opened 2018-08-24 09:34 UTC
1. Search for something
2. Type a replace term. All is nicely shown
3. Now change the search or the replace and press enter -> right hand side gets broken

Assigning to August since it looks quite broken

**Comment by sandy081** [comment] 2018-08-24 09:38
@bpasero This is happening because diff editor is not getting closed when one of the models in the diff editor was got disposed.

May I know why?

**Comment by bpasero** [comment] 2018-08-24 10:06
This could be a regression from the grid work, I have to check.

**Comment by bpasero** [comment] 2018-08-24 12:49
@sandy081 I was able to reproduce this all the way down to 1.23, so it is unrelated to the grid work. I see that we have code in place to dispose the input, if one of its sides gets disposed:

https://github.com/Microsoft/vscode/blob/bd6bd5f73dc4500bc6e027c7a75e9df35c1ea635/src/vs/workbench/common/editor.ts#L570-L582

Would you be able to dispose the input when the search changes instead of disposing the underlying model? We typically do not listen to the model getting disposed for closing the editor, this works all through the inputs that originally caused the editor to open in the first place.

**Comment by sandy081** [comment] 2018-08-27 08:19
I will see if I can dispose the input

**Closed** 2018-08-27 08:42 UTC
Labels: bug, search-replace
