### ISSUE TITLE
Microsoft sign in

### ISSUE THREAD

**Issue by MrEasy50** [microsoft/vscode#136297] opened 2021-11-02 16:04 UTC
Issue Type: <b>Bug</b>

Program keeps wanting me to sign into my microsoft account. Even when I check, I am signed in. Not sure what I am doing wrong???

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.33GB free)|
|Process Argv|--crash-reporter-id 9b663a59-47f3-40d9-8097-9a97fa7beab4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode-standard|bys|0.22.1
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|9.0.0
vscode-express-snippets|Exp|1.1.1
auto-rename-tag|for|0.1.9
Angular2|joh|12.0.0
dotenv|mik|1.0.1
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by TylerLeonhardt** [comment] 2021-11-04 21:12
Looks like a duplicate of https://github.com/microsoft/vscode/issues/133201#issuecomment-956430361 can you take a look at the linked comment for next steps?

**Closed by TylerLeonhardt** 2021-11-04 21:12 UTC
