### ISSUE TITLE
Extensions: Suggest is broken in extensions viewlet

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85313] opened 2019-11-21 16:28 UTC
![image](https://user-images.githubusercontent.com/22350/69356650-196cd280-0c84-11ea-8ce7-561855c037c0.png)

**Comment by IllusionMH** [comment] 2019-11-21 16:30
Duplicate of #85312 😄

**Comment by JacksonKearl** [comment] 2019-11-21 17:24
@joaomoreno Unable to repro on MacOS. What platform are you on?

**Comment by IllusionMH** [comment] 2019-11-21 17:26
@JacksonKearl in my case it is reproducible on Windows.

**Comment by JacksonKearl** [comment] 2019-11-21 19:15
Worse when sidebar is at right. It gets obscured completely if the sidebar is a reasonable size. 
![image](https://user-images.githubusercontent.com/8586769/69369053-2a035580-0c50-11ea-9e56-799ee9e86880.png)

**Comment by JacksonKearl** [comment] 2019-11-21 19:56
Caused by a95ec814013b2f45a0ac76549f9169b53a3a497b. cc @bpasero

**Comment by JacksonKearl** [comment] 2019-11-22 02:50
@sbatten @mattbierner you mentioned having knowledge in this area

**Comment by sbatten** [comment] 2019-11-26 19:56
looks like we just need to update the logic for suggest widget positioning based on the containing box since the box is now just the sidebar (with the layer hinting added in the workbench) for linux and windows.

@rebornix and I will update this afternoon.

**Comment by rebornix** [comment] 2019-12-04 18:29
We reverted the *simple* fix on master as it's leading to wrong positioning of content widgets in the editor and debug toolbar.

A summary of places we need to verify when we have new proposals:

*Compact Menu*

<img width="238" alt="image" src="https://user-images.githubusercontent.com/876920/70169704-26c08e80-1680-11ea-8def-cf05a2893537.png">

*Suggest Widget in Extensions View*

<img width="318" alt="image" src="https://user-images.githubusercontent.com/876920/70169733-3dff7c00-1680-11ea-9af6-f542280471ea.png">

*Suggest Widget in Settings Editor*

<img width="575" alt="image" src="https://user-images.githubusercontent.com/876920/70169520-df3a0280-167f-11ea-9b32-d9a6dc6cb005.png">

*Suggest Widget in Monaco* (exist with change from https://github.com/microsoft/vscode/commit/9d47191895b0705f689a234c1a4e1e790303cb70)

<img width="801" alt="image" src="https://user-images.githubusercontent.com/876920/70169829-7010de00-1680-11ea-8a0e-457e7d3f99e8.png">


*Editor Hover* (exist with change from https://github.com/microsoft/vscode/commit/9d47191895b0705f689a234c1a4e1e790303cb70)

<img width="847" alt="image" src="https://user-images.githubusercontent.com/876920/70170052-d5fd6580-1680-11ea-8019-db3a091a63b4.png">

**Comment by sbatten** [comment] 2019-12-05 22:44
by reverting the layer promotion changes, this should be resolved.

**Closed by sbatten** 2019-12-05 22:44 UTC
