### ISSUE TITLE
Auto code completion feature is lost

### ISSUE THREAD

**Issue by partha0047** [microsoft/vscode#94811] opened 2020-04-09 15:52 UTC
After the march 2020 update the auto completion feature is lost.
Live Serve extension is also not supported in this new update

**Comment by gjsjohnmurray** [comment] 2020-04-09 16:08
If you disable LiveServer extension do the missing auto completion features start working again?

**Comment by gjsjohnmurray** [comment] 2020-04-09 16:12
Maybe related to #94807

**Comment by RMacfarlane** [comment] 2020-04-09 18:15
@partha0047 What programming language are you using?

**Comment by partha0047** [comment] 2020-04-09 18:53
I'm using html ,css and javascript files.After the new update it says the
extension host terminated unexpectedly. Auto completion feature is also
lost.

**Comment by alexdima** [comment] 2020-04-15 11:48
Duplicate of #94858

**Closed by alexdima** 2020-04-15 11:48 UTC
Labels: needs more info
