### ISSUE TITLE
Enable or disable workspace

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#52867] opened 2018-06-26 04:45 UTC
It is not always we are working on a **single project and open multiple folders** and then save it as a workspace.

### VS Code

![2018-06-26_10-02-17](https://user-images.githubusercontent.com/29014463/41889452-65f46df2-7928-11e8-9c28-3677c89da33a.png)

It is possible that we even open **multiple folders from different projects** in that case, VS Code converts all of them into a workspace, which is not a good idea. Atom does a good job here, although it doesn't have the option to save them as a workspace but we can open multiple folders and work on it.

### Atom 

![2018-06-26_10-07-37](https://user-images.githubusercontent.com/29014463/41889547-efab5024-7928-11e8-9aaf-b7623c46cae0.png)

![image](https://user-images.githubusercontent.com/29014463/41889557-006b2452-7929-11e8-89dd-8b7d639600ee.png)

### VS Code

![image](https://user-images.githubusercontent.com/29014463/41889633-4b08070a-7929-11e8-8bab-8b21685bf4fa.png)

## My point is...

There should be an option to create a workspace regardless you have opened one or more than one folders.

**Comment by TomSputz** [comment] 2018-06-26 05:02
I'm with you that this feature would be very helpful - though this is a duplicate of #43188, it would be great if you could close this issue and add your support to that

**Comment by mittalyashu** [comment] 2018-06-26 05:29
@TomSputz, thanks for the thumbs up, but both these issue are different.

**Comment by TomSputz** [comment] 2018-06-26 06:11
No, I suppose I don't quite understand it - you want to 'open multiple folders from different projects', but not 'converts all of them into a workspace'. At the moment VSCode only supports opening one 'Workspace' where all the open files are listed, to open folders outside of this context we would need to be able to have multiple workspaces. Hence my linking to the related issue.

What am I missing?

**Comment by mittalyashu** [comment] 2018-06-26 06:59
> open multiple folders from different projects', but not 'converts all of them into a workspace

You guessed it right, but there's a twist when we add the second folder to the vs code, it automatically converts it into a workspace.

But I don't want that, instead, we should have the power in our own hands when to create a workspace and even if we create a workspace, there should be an option to delete that workspace directly from VS Code.

**Comment by roblourens** [comment] 2018-06-26 17:18
"Workspace" is basically just what VS Code calls it when you open multiple folders in one window. I don't understand what the difference would be, as you see it, between opening two folders in one window and a "workspace".

**Comment by mittalyashu** [comment] 2018-06-27 08:47
Sorry guys to create confusion.

I have created a video to explain in detail: https://www.youtube.com/watch?v=2d9_R_lv6Qc

Hope it explains everything I wanted to tell.

**Comment by roblourens** [comment] 2018-06-27 16:59
Thanks but it seems like you just restated the original question without answering my question. It seems like you just have a problem with the word "workspace". What is the behavior difference you want to see between having multiple folders in a workspace vs multiple folders in a window that isn't a workspace?

Also you can create a single-folder workspace by opening an empty window and using "Add Folder to Workspace"

**Comment by mittalyashu** [comment] 2018-06-28 05:54
My point is that VS Code should not automatically create a workspace.

There should be some kind of option to create a workspace manually or users can create settings to create workspace automatically.

**Comment by roblourens** [comment] 2018-06-28 17:51
Two folders in one window = workspace. I'll close this unless you can explain exactly what you want to happen differently.

**Closed by roblourens** 2018-06-28 17:51 UTC
Labels: needs more info

**Comment by mittalyashu** [comment] 2018-06-28 18:37
It is possible you are not able to understand my issue properly, it would be great if we can have a discussion over a call.

**Comment by roblourens** [comment] 2018-06-28 18:45
I just need to know exactly what you expect to happen when two folders are open in one window. I think you might be misunderstanding what a "workspace" in vscode is.

**Comment by mittalyashu** [comment] 2018-06-29 03:01
> what you expect to happen when two folders are open in one window

It should not create a workspace.

**Comment by roblourens** [comment] 2018-06-29 05:14
A "workspace" in this case is really just two folders open in one window. You can save the configuration in a workspace file if you want, but that's optional.

**Comment by mittalyashu** [comment] 2018-06-29 05:22
I know the what workspace does.

But why workspace is created automatically, instead we should create or delete workspace manually.

Or users can add in the `settings.json` to create workspace automatically.

**Comment by mittalyashu** [comment] 2018-06-30 05:22
Does it explain now?

**Comment by mittalyashu** [comment] 2018-06-30 15:47
If you are working on different projects (project unrelated to each other) and you have opened all the projects in a single instance, then it's obvious we will not save as a workspace.

And to create a workspace we need at least two folders opened in the explorer, so there is no option to save single folder as a workspace.

---

I have created a separate folder name "workspace" and whether it's a single or multiple project workspace I save it in this folder so that all the workspaces can be easily accessible.

![image](https://user-images.githubusercontent.com/29014463/42126788-e7768240-7caa-11e8-9605-ba4e35f405ee.png)

**Comment by roblourens** [comment] 2018-06-30 16:17
I think we are talking in circles, but in any case we aren't likely to change this. Just remember that you don't have to actually save the workspace...

**Comment by mittalyashu** [comment] 2018-06-30 19:32
I not saying to remove it, what I meant is to add the option inside `ctrl + shift + p` to toggle workspace
