### ISSUE TITLE
Can't use ${selectedText} as a optional variable for Tasks

### ISSUE THREAD

**Issue by MohitGhodasara** [microsoft/vscode#117121] opened 2021-02-20 09:59 UTC
- VS Code Version: 1.53.2
- OS Version: Ubuntu 18.4 LTS

I want to create a task that takes either from the selected text or asks for input. something like this 

```
{
  "label": "Blah Blah",
  "type": "shell",
  "command": "echo ${selectedText} || ${input:get-string}",
  "problemMatcher": [],
  "group": "build",
}
```

but it throws error when text is not selected 

> Variable ${selectedText} can not be resolved. Make sure to have some text selected in the active editor.

is it possible to get seleted text lenght that we can check conditionally? `${seletedTextLenght} == 0 `
or by default ${selectedText} return empty string? `${selectedText} == ''`

**Comment by ArturoDent** [comment] 2021-02-20 23:20
See https://github.com/microsoft/vscode/issues/92854 and https://github.com/microsoft/vscode/issues/94060

**Comment by alexr00** [comment] 2021-02-22 12:58
Thanks for linking @ArturoDent . Duplicate of https://github.com/microsoft/vscode/issues/92854, since that's how we'd solve this problem.

**Closed by alexr00** 2021-02-22 12:58 UTC
