### ISSUE TITLE
Custom TitleBar Randomly Becomes Unclickable

### ISSUE THREAD

**Issue by sulkhanp** [Microsoft/vscode#52522] opened 2018-06-20 23:10 UTC
- VSCode Version: 1.25 Insiders
- OS Version: Windows 10

Steps to Reproduce: Didn't notice a particular pattern to reproduce 

1.Click ALT
2.Hover over the menu
3.Try clicking, nothing happens,

For clarity: https://i.imgur.com/Opf3BLf.png

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sbatten** [comment] 2018-06-27 01:15
After spending a lot of time trying to understand the repro for this, I think what's happening is that if you have your mouse over the title bar (a draggable region), press alt, then move your mouse over the menubar (or if it was already over), then the menubar is not clickable until you move the mouse out to another non-draggable region like the editor and come back. This seems to be an issue with the way webkit-app-region works and eats mouse events. Open to ideas...

**Comment by bpasero** [comment] 2018-06-29 04:54
Steps to reproduce:
* configure `"window.menuBarVisibility": "toggle"`
* move mouse into title bar
* press and hold `Alt` key
* => 🐛 you cannot use the menu

**Comment by bpasero** [comment] 2018-06-29 04:54
Moving to July, I really don't think this blocks the release.

**Comment by jtlowe** [comment] 2018-07-06 18:19
I'm also running into this when the mouse is sometimes outside of the title bar and have interacted with other elements:

* click/collapsing the "Open Editors"
* hold `Alt` key to show the menu
* hovering over and clicking the menu does not work (there's a brief menu highlight that disappears)

**Closed** 2018-07-17 16:04 UTC
Labels: bug, workbench-menu
