### ISSUE TITLE
Cursor gone missing

### ISSUE THREAD

**Issue by impelsystems** [Microsoft/vscode#9021] opened 2016-07-10 09:12 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Multiple files open in tabs with both panes, switching between a js on the right hand pane and an html on the left hand pane
2. In the html file, hitting home the cursor is present 
3. Either hit end or arrow right and once the cursor gets to a tag attribute value (within the "") that is partially hidden off screen, the cursor disappears

**Comment by alexandrudima** [comment] 2016-07-11 10:24
@impelsystems Thank you for reporting, I spent quite some time trying to reproduce, but I could not get it to happen. Can you please record a gif? Do you have any extensions installed? Does this reproduce with `vscode --disable-extensions`?

![cursor-hidden](https://cloud.githubusercontent.com/assets/5047891/16727595/88eca0dc-476a-11e6-98ff-6df586f56965.gif)

**Comment by bpasero** [comment] 2016-07-11 18:40
@impelsystems can you try my solution in https://github.com/Microsoft/vscode/issues/9029#issuecomment-231825432 ?

**Comment by impelsystems** [comment] 2016-07-11 20:21
@alexandrudima I will get a gif through if I can replicate it again

@bpasero sure thing I will try that

**Comment by marvinhagemeister** [comment] 2016-07-12 07:21
This seems to be similar to #8828

**Comment by impelsystems** [comment] 2016-07-12 08:12
@marvinhagemeister yep that is the one exactly #8828 
cc @alexandrudima @bpasero

**Comment by bpasero** [comment] 2016-07-12 13:11
Duplicate of https://github.com/Microsoft/vscode/issues/8828

**Closed by bpasero** 2016-07-12 13:11 UTC
Labels: important
