### ISSUE TITLE
Problem opening Visual Studio Code on the new macOS

### ISSUE THREAD

**Issue by AWShane92** [microsoft/vscode#90635] opened 2020-02-13 21:33 UTC
- VSCode Version: 1.42.1
- OS Version: macOS 10.15.3

Steps to Reproduce:
1. Download Visual Studio Code on a MacBook running macOS 10.15.3.
2. Install the app as instructed.
3. Attempt to open the application and you will receive an error saying that:

 "Visual Studio Code.app" can't be opened because Apple cannot check it for malicious software. 
  This software needs to be updated. Contact the developer for more information. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by randonia** [comment] 2020-02-13 22:26
Duplicate of #74782

Looks like this week they started properly building for Catalina, but until that hits main you can tell OSX to ignore the quarantine by doing this

```shell
xattr -d com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```

**Closed** 2020-02-13 22:44 UTC
