### ISSUE TITLE
Go to Declaration on JSX Element reveals @types/react in latest vscode release

### ISSUE THREAD

**Issue by dontsave** [Microsoft/vscode#69994] opened 2019-03-07 22:18 UTC
In 1.32.0, using "go to declaration" on a JSX Element, `<MyComponent/>` will no longer directly open the immediate location of the declaration. Instead it will reveal 2 locations, the correct one, and the Function Component interface it extends in @types/React. This is new behavior as of the most recent VSCode update. The expected behavior would be for the file with the declaration of `MyComponent` to be opened

**Comment by mjbvz** [comment] 2019-03-07 23:13
Duplicate of https://github.com/Microsoft/TypeScript/issues/30246

**Closed by mjbvz** 2019-03-07 23:13 UTC
Labels: javascript
