### ISSUE TITLE
Bad experience on JSX attribute auto-complete 

### ISSUE THREAD

**Issue by littlee** [Microsoft/vscode#47966] opened 2018-04-16 13:54 UTC
- VSCode Version: 1.22.2
- OS Version: 10.13.4

Steps to Reproduce:

in a react component file, type
<img width="254" alt="1" src="https://user-images.githubusercontent.com/7534668/38812835-f29bc80e-41bf-11e8-8985-3f0e5a3b780d.png">
pressing tab will result in:
```jsx
<button className></button>
```
that's good.

**BUT** when start type the second attribute
<img width="671" alt="2" src="https://user-images.githubusercontent.com/7534668/38812908-24883eec-41c0-11e8-9ec2-aa9a3042f281.png">
pressing tab result in:
```jsx
<button type="button" {className}></button>
```
I don't think `{` and `}` is needed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-04-16 17:32
Duplicate of #47112 / https://github.com/Microsoft/TypeScript/issues/23099

**Closed by mjbvz** 2018-04-16 17:32 UTC
Labels: javascript
