### ISSUE TITLE
批量替换功能有问题

### ISSUE THREAD

**Issue by q13044256742** [microsoft/vscode#127046] opened 2021-06-24 03:38 UTC
ctrl + h 批量替换时，
输入框在输入文本时，无法实时看到输入的内容，必须点击其他地方(控件失去焦点)，刚才输入的内容才会显示在文本框里

When ctrl + h batch replacement, the input box cannot see the input content in real time when entering text. You must click elsewhere (the control loses focus) before the just input will be displayed in the text box

![image](https://user-images.githubusercontent.com/16590810/123199017-ade28b00-d4e0-11eb-8bbc-8ba8a6e62c3a.png)
![image](https://user-images.githubusercontent.com/16590810/123199030-b4710280-d4e0-11eb-866c-4919b9049011.png)
![image](https://user-images.githubusercontent.com/16590810/123199049-bb981080-d4e0-11eb-9fc4-1807502c3345.png)

**Comment by yume-chan** [comment] 2021-06-24 06:51
Duplicate of #126896

**Closed** 2021-06-24 06:56 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
