### ISSUE TITLE
[Bug] The fullscreen and close buttons of the built-in terminal in VSCode are missing

### ISSUE THREAD

**Issue by 1chooo** [microsoft/vscode#235418] opened 2024-12-05 16:58 UTC
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin x64 24.0.0
```

Steps to Reproduce:

1. Open VSCode
2. Open Terminal
3. The fullscreen and close buttons of the built-in terminal in VSCode are missing.

Screenshots:

![Image](https://github.com/user-attachments/assets/30f70eb5-2bdc-4c87-983b-6edfc415454e)

**Comment by meganrogge** [comment] 2024-12-07 18:40
I cannot reproduce, thus closing.  can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Closed by meganrogge** 2024-12-07 18:40 UTC
