### ISSUE TITLE
Multiple open tabs

### ISSUE THREAD

**Issue by kirtangajjar** [Microsoft/vscode#3212] opened 2016-02-21 13:20 UTC
This is a feature request.

It would be really cool to have atom-like multiple tabs open for simultaneous editing. It is hard to click on those small strips on the sidebar. Having tabs on top like below image ensures that we could easily navigate between multiple files while editing. 

![image](https://cloud.githubusercontent.com/assets/8456197/13202744/ed76d9d6-d8cb-11e5-9deb-20430b1f4855.png)

**Comment by Growiel** [comment] 2016-02-22 05:56
Have to agree. While multi editor is sometimes (often) useful, I miss my tabs sooo much.

I would even go as far as saying that each editor should have its own list of tabs.

**Comment by joaomoreno** [comment] 2016-02-22 09:42
Duplicate of @224

By the way, check this out: if you hold <kbd>Ctrl</kbd> (or <kbd>⌘</kbd> on OS X), press <kbd>E</kbd> a few times and finally release <kbd>Ctrl</kbd>, you get a very cool history navigation that I feel replaces (and improves) the tab-like interaction. Give it a try, it's my everyday bread.

**Closed by joaomoreno** 2016-02-22 09:42 UTC
