### ISSUE TITLE
Go to implementations won't work when sourcesContent present in *.map

### ISSUE THREAD

**Issue by UchihaYuki** [microsoft/vscode#142980] opened 2022-02-14 02:18 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Windows 10

Reproduce:

When I serve angular app, it will somehow add sourcesContent  in my angular libraries' *.map files. Then Go to implementations won't work, even sources is still there. If I reinstall those packages, and right before I run `ng serve`, it will work again. It will even work, if I just manually delete sourcesContent.

**Comment by mjbvz** [comment] 2022-02-14 06:18
Please provide a minimal example project and steps to reproduce this issue

/needsMoreInfo

**Comment by UchihaYuki** [comment] 2022-02-15 09:57
It seems sourcesContent have higher priority over sources. So when it presents, vs code won't go to the original files. You can add this property to any map file, then Go to Implementation will stop work.

**Comment by mjbvz** [comment] 2022-02-15 23:34
Please share a project that demonstrates this issue so we can investigate it

**Comment by UchihaYuki** [comment] 2022-02-16 16:12
In my demo, I use an empty sourcesContent string, but you can use the right string, the result is the same.

**Comment by mjbvz** [comment] 2022-02-24 22:59
Ok, that sounds like a duplicate of https://github.com/microsoft/TypeScript/issues/6209 based on your description 

Closing as upstream

**Closed by mjbvz** 2022-02-24 22:59 UTC
Labels: needs more info
