### ISSUE TITLE
"editor.wordSeparators" option is not always honored

### ISSUE THREAD

**Issue by nerdo** [Microsoft/vscode#36848] opened 2017-10-24 20:36 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swift|Kas|0.0.3
php-namespace-resolver|Meh|0.8.0
material-icon-theme|PKi|2.2.3
vscode-intelephense-client|bme|0.7.2
vscode-eslint|dba|1.4.0
vscode-dash|dee|1.7.1
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.3.1
phpunit|ema|2.1.1
LogFileHighlighter|emi|1.2.0
phpcs|ika|0.7.0
insert-cursor-at-beginning-of-each-line-selected|kai|1.0.1
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.0
debugger-for-chrome|msj|3.4.0
php-docblocker|nei|1.3.2
pdf|tom|0.2.0
vim|vsc|0.10.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Set the `editor.wordSeparators` option to `"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"`. This is essentially the default value with `$` removed.
2. Enter this in the editor
```
$this->stuff
this stuff
and $this thing
```
3. Place the cursor at the beginning of line 1 and press `CMD+D` to highlight the word `$this`. Nothing happens. Further, moving the cursor to anywhere within the word `$this` and pressing `CMD+D` highlights `this`, effectively ignoring the `editor.wordSeparators`.
4. Side note: using the mouse *does* seem to honor the setting.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-10-25 10:54
Duplicate of #15774

**Closed by alexandrudima** 2017-10-25 10:54 UTC
Labels: editor, editor-core
