### ISSUE TITLE
Organize imports feature fails when using Object Literal Shorthand Syntax

### ISSUE THREAD

**Issue by krvajal** [Microsoft/vscode#50897] opened 2018-05-31 18:58 UTC
- VSCode Version: 1.23.1
- OS Version: Mac

Steps to Reproduce:

1. Enable the new setting
```
"editor.codeActionsOnSave": {
        "source.organizeImports": true
    } 
```
2.
Create a js file like this
```js
import api from './index'
const obj = {
    api
}
```
3. Save the file and you will end up with this
```js
const obj = {
    api
}
```
The import statement is completely gone.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-05-31 19:02
This is already fixed in VS Code insiders

Duplicate of #49172

**Closed by mjbvz** 2018-05-31 19:02 UTC
Labels: javascript
