### ISSUE TITLE
[Feature Request] Option for Bracket guides to always choose the smallest scope

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#146029] opened 2022-03-25 07:21 UTC
Hi

In Bracket Pair Colorizer extension, the scope is always the closest brackets to the cursor:

![image](https://user-images.githubusercontent.com/5593825/160073464-43fe47b4-724d-4b1a-986b-fb7022473553.png)

In Native feature, it chooses the outer scope

![image](https://user-images.githubusercontent.com/5593825/160073575-fffc084b-1dda-476d-81f3-ea1efaa64054.png)

**Comment by yume-chan** [comment] 2022-03-25 08:26
Duplicate of #136475

**Closed** 2022-03-25 08:47 UTC
