### ISSUE TITLE
[html] Wrongful handling of Javascript in script templates

### ISSUE THREAD

**Issue by Starcounter-Jack** [microsoft/vscode#231180] opened 2024-10-12 12:40 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.94.2 (Universal)
- OS Version: Darwin arm64 23.6.0

Steps to Reproduce:

1. Create a file with an .html extension
2. Paste the following text:

```
<template>
    <script type="module">
        export default "foo"
    </script>
</template>
<template>
    <script type="module">
        export default "bar"
    </script>
</template>
```

This wrongfully produces two items in the "problems views", ignoring the fact that the exports are not declared in the top-level module  :

```
[{
	"resource": "/Users/jack/temp.html",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "A module cannot have multiple default exports.",
	"source": "javascript",
	"startLineNumber": 3,
	"startColumn": 9,
	"endLineNumber": 3,
	"endColumn": 29
},{
	"resource": "/Users/jack/temp.html",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "A module cannot have multiple default exports.",
	"source": "javascript",
	"startLineNumber": 8,
	"startColumn": 9,
	"endLineNumber": 8,
	"endColumn": 29
}]
```

**Comment by Starcounter-Jack** [comment] 2024-10-12 12:44
Thanks for the suggestion. The problem remains in the latest version (1.94.2).

**Comment by aeschli** [comment] 2024-12-09 20:59
Duplicate of https://github.com/microsoft/vscode/issues/229357

**Closed by aeschli** 2024-12-09 20:59 UTC
Labels: bug, html
