### ISSUE TITLE
Published version failed to find the contributed command but it works in debug mode.

### ISSUE THREAD

**Issue by jackalcooper** [Microsoft/vscode#32937] opened 2017-08-22 09:11 UTC
- VSCode Version: Version 1.15.1 (1.15.1)
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. Check out the extension [here](https://github.com/jackalcooper/bucklescript-tea-tools).
2. install node dependency and run it with `F5`
3. Toggle command: "BuckleScript-TEA: Convert HTML to DSL in OCaml"
4. It should work

5. Install this extension from marketplace. Its name: `BuckleScript-TEA Tools`
6. Toggle command: "BuckleScript-TEA: Convert HTML to DSL in OCaml" in a non-debug instance of VS Code
4. It says:
```
command 'bucklescriptTeaTools.htmlToView' not found
```

**Comment by jackalcooper** [comment] 2017-08-22 09:18
notice: please do not install the dev dependency because it will install whole `BuckleScript` toolchain which including compiling OCaml compiler and this takes long.

**Comment by yume-chan** [comment] 2017-08-22 09:48
Do you have `Ionide-fsharp` extension installed? If you do, it's a duplicate of #32673.

**Comment by jackalcooper** [comment] 2017-08-22 09:57
@yume-chan No, I haven't installed it.

**Comment by jackalcooper** [comment] 2017-08-23 02:20
```
2gua.rainbow-brackets-0.0.6
AzkabanCoders.dustjs-0.1.1
CraigMaslowski.erb-0.0.1
DavidAnson.vscode-markdownlint-0.10.0
HookyQR.beautify-1.1.1
PeterJausovec.vscode-docker-0.0.16
alexdima.copy-relative-path-0.0.1
christian-kohler.npm-intellisense-1.3.0
codezombiech.gitignore-0.5.0
donjayamanne.python-0.7.0
freebroccolo.reasonml-0.0.99
hackwaly.ocaml-0.6.41
jackalcooper.bucklescript-tea-tools-0.0.3
lukehoban.go-0.6.63
misogi.ruby-rubocop-0.4.0
mjmcloug.vscode-elixir-0.5.1
rebornix.ruby-0.15.0
red-auto.red-0.2.1
sbrink.elm-0.15.0
vortizhe.simple-ruby-erb-0.2.1
wmaurer.change-case-1.0.0
yuce.erlang-otp-0.2.4
```
@yume-chan these are my installed extensions. Anything might cause the problem here?

**Comment by yume-chan** [comment] 2017-08-23 02:27
Sorry, I don't know.

Maybe you can try to check the DevTools console for messages like [#32673 (comment)](https://github.com/Microsoft/vscode/issues/32673#issuecomment-323030284)?

**Comment by jackalcooper** [comment] 2017-08-23 02:34
@yume-chan I tailed the file `tsserver.log` and didn't see any new lines after running the command.

**Comment by yume-chan** [comment] 2017-08-23 04:17
Not tsserver.log, press Ctrl Shift P, type DevTools, enter, a Chrome DevTools will open, switch to Console tab.

**Comment by jackalcooper** [comment] 2017-08-23 06:48
@yume-chan got same error
```
command 'bucklescriptTeaTools.htmlToView' not found
```

**Comment by jrieken** [comment] 2017-08-23 06:56
@jackalcooper Does this work on second try? The extension activates on that command and might not be ready yet

**Comment by jackalcooper** [comment] 2017-08-23 07:01
@jrieken no, I've tried multiple times.

**Comment by jrieken** [comment] 2017-08-23 07:14
I have just tried with the extension (cloned from GH) and I cannot reproduce this. Please check the developer tools console (F1 > Toggle Developer Tools) and check what the 'Console' tab reads. Thanks

**Comment by jackalcooper** [comment] 2017-08-23 07:18
![image](https://user-images.githubusercontent.com/5133557/29603313-4dd9e958-8816-11e7-83dc-d2e40bd4431e.png)

@jrieken I got this (installed from marketplace)

**Comment by jrieken** [comment] 2017-08-23 10:25
@jackalcooper Is that your extension? Is it possible that the published version doesn't contain a npm dependency and therefore fails to load?

**Comment by jackalcooper** [comment] 2017-08-23 14:02
@jrieken I think you are right. The stand library `bs-platform` is not contained in dependency but in devDependency. But this is a 400MB package after installed. It is obviously not a good idea to include it just for couple of `*.js` files. Looks like have to bundle it with tools like `webpack` or `brunch`, or you have any better ideas?

**Comment by jrieken** [comment] 2017-08-23 14:05
> bs-platform this is a 400MB package after installed

Is that 400MB JavaScript? Unlikely, right? We think we don't even allow to publish extensions that large. Often, extension download large things on first use and when needed. Or they require some 'external' install step. Unsure what is best for you...

**Comment by jackalcooper** [comment] 2017-08-23 14:26
@jrieken sorry I didn't make it clear. It is not just JavaScript but whole toolchain of OCaml language and BuckleScript standard library which is both in OCaml and JavaScript. (BuckleScript is a compiler compiles OCaml to JS). The JavaScript part of standard library of BuckleScript is what I want to include in my VS Code library. The requiring for standard library looks like this in the JavaScript files BuckleScript generates.
```
var List         = require("bs-platform/lib/js/list.js");
var $$String     = require("bs-platform/lib/js/string.js");
var Js_dict      = require("bs-platform/lib/js/js_dict.js");
var Pervasives   = require("bs-platform/lib/js/pervasives.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
```

**Comment by jrieken** [comment] 2017-08-23 15:03
Hm, do you see this message being printed? https://github.com/jackalcooper/bucklescript-tea-tools/blob/master/extension.js#L12

**Comment by jackalcooper** [comment] 2017-08-23 15:13
@jrieken If you are talking about console of develop tools, the answer is no.

**Comment by jrieken** [comment] 2017-08-24 15:45
So, it does seem a file is missing from the published extension. When debugging this I see that during activate, code loading fails. However, I also see an error about that on the console

<img width="1076" alt="screen shot 2017-08-24 at 17 42 46" src="https://user-images.githubusercontent.com/1794099/29674902-c905ec7a-88f3-11e7-8e88-bc87a8f1de9a.png">


<img width="527" alt="screen shot 2017-08-24 at 17 44 54" src="https://user-images.githubusercontent.com/1794099/29674952-f8cd72e8-88f3-11e7-8ddf-566d6ab90c98.png">

**Closed** 2017-08-24 15:46 UTC
Labels: caused-by-extension

**Comment by jackalcooper** [comment] 2017-08-25 02:15
Thanks
