### ISSUE TITLE
Intermittent Frontend Display Failing to Update

### ISSUE THREAD

**Issue by dmblack** [Microsoft/vscode#19468] opened 2017-01-27 00:49 UTC
- VSCode Version: code_1.8.1-1482158209_amd64.deb
- OS Version (All Debian): Linux devlap 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux

Note: This does not happen on any of my Windows, or macOS devices - and is limited to Debian at this stage.

- Extensions: Omitted, as I've also tested with these disabled - and they differ between workstations.

- Project Language: Omitted, as this happens with any open project, and is not limited to anything in particular.

I've been using VSCode for some time, and seem to be plagued by this consistent, though unpredictable, freezing. This has been since day one, and present in at least 1.5.* of my version history.

I've attempted to investigate further, with the debugger open - however I cannot seem to gather anything unique about the case. In the few cases it's frozen with debugger open, the debugger is not available either. (Apologies; I've just found the persistent log option, and enabled)

I've tried running without extensions enabled, and have this issue with any language

It does happen on all three of my workstations running Debian release. The current workstation is running a backported kernel for unrelated reasons.

Steps to Reproduce:
 - Cannot provide. The freeze is intermittent.

**Comment by Tyriar** [comment] 2017-01-27 01:43
How frequent does this happen exactly? I would recommend attempting to gather a timeline in dev tools of the situation if possible, that would reveal which function is the problem.

Another thing you could do is to try reproduce using [Electron](http://electron.atom.io/), but again that would depend on how frequent it happens.

**Comment by dmblack** [comment] 2017-01-27 02:05
Just had another freeze.

Nothing saved in console, with 'preserve log' enabled.

**Comment by Tyriar** [comment] 2017-01-27 02:11
@bpasero any ideas for diagnosing intermittent app freezes?

**Comment by dmblack** [comment] 2017-01-27 03:34
Another 'freeze'.

Attempted to take a screenshot, with unexpected results. (Please note - I cut some irreverent information for confidentiality reasons). The windows you can see are from Firefox Developer Edition and RoboMongo. So it looks like screen updates fail once the application becomes unresponsive.

![vscode-frozen](https://cloud.githubusercontent.com/assets/14871038/22359585/9ebeca00-e49c-11e6-9c6e-b6cf75d8ae4a.jpeg)

Incase relevant;
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Kernel driver in use: i915

All three boxes are running Intel integrated graphics. Do not have access to the drivers on each, but will get this soon. I know it's a combination of release, backported, and entirely removed graphics drivers - as I had some issues with them (unrelated). The only way these have ever impacted VSCode in the past is a weird 'black box' artifacting.

**Comment by dmblack** [comment] 2017-01-27 03:51
So I noticed I could see the file active in the status bar when using the Gnome 'task selector'. I typed input, though I could not see it, then returned to the 'task selector', and could see the white circle (indicating unsaved changes).

I returned to the application, CTRL + S, then back to 'task selector', and found that the white circle had disappeared. I manually navigated to this file path and confirmed that the file had changed (with my gibberish input)

So it seems the application is responsive, but the user interface no longer updates.

I've updated the issue title to a more appropriate description.

00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Kernel driver in use: i915
(xserver-xorg-video-intel (2:2.99.917+git20161206-1~bpo8+1))

Going to entirely remove this driver and test.

Note: No other applications are demonstrating this behavior.

**Comment by bpasero** [comment] 2017-01-27 05:59
Is there a process spinning 100% in VS Code when this happens maybe?

**Comment by dmblack** [comment] 2017-01-28 03:47
@bpasero 
Well, oddly enough; I've not had a single crash since removing the Intel drivers. But I'll review usage if it happens again.

As stated earlier; no other apps are demonstrating this symptom.

**Comment by dmblack** [comment] 2017-02-24 02:28
Hey Team,

Had to reinstall intel drivers again to immediately be reproduced this issue.

I'm assuming this is more so an issue with Electron and the Intel drivers.

So how do we want to manage this? Surely I'm not the only one impacted - given it's an issue on two laptops running i3/i5 embedded intel graphics on Linux.

**Comment by Tyriar** [comment] 2017-02-24 17:54
Well it would probably be difficult to verify, something VS Code is doing could be triggering the crash in Chromium. @bpasero should we close this off?

**Comment by bpasero** [comment] 2017-02-25 06:48
Best to report this to [Electron](https://github.com/atom/electron) ideally with a reproducible case using the Electron [framework](https://github.com/electron/electron/releases).

**Comment by bpasero** [comment] 2017-02-25 06:49
@dmblack does it reproduce when you run `code --disable-gpu` from the command line?

**Comment by dmblack** [comment] 2017-02-26 22:33
@bpasero 
Firstly; thanks for your responses!

So far, with this argument; I have not had any crashes. Will post another update by the end of the day.

Thanks!

**Comment by dmblack** [comment] 2017-02-27 22:43
@bpasero 
Nearly two days without a single crash, running; `--disable-gpu`

Is there any additional logging we can enable with this flag not provided to ensure we capture what is happening?

Thanks again for your help!

**Comment by Tyriar** [comment] 2017-03-01 18:55
@dmblack not that I'm aware of. Since `--disable-gpu` fixes it though that identifies it as a [Chromium](https://www.chromium.org/Home) issue so I'll close this off as there's the workaround until it's fixed upstream.

**Closed by Tyriar** 2017-03-01 18:55 UTC
Labels: bug, freeze-slow-crash, needs more info, upstream

**Comment by dmblack** [comment] 2017-06-12 09:32
Just for reference;
This issue is back and worse than ever with release;

Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:41:25.571Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Using Intel drivers;
Package: xserver-xorg-video-intel
Status: install ok installed
Priority: optional
Section: x11
Installed-Size: 3248
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Architecture: amd64
Version: 2:2.99.917+git20161206-1~bpo8+1

I'll get around to submitting an issue with Chromium soon enough >.<

Any users impacted with this will likely find removing Intel display drivers entirely fixes the behavior - at the expense of some GPU acceleration features.
