### ISSUE TITLE
Debug: always load default option ...

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode#4028] opened 2016-03-11 19:03 UTC
Hi there,

I have two options in my projet with vscode.
The default one `Launch` is used to compile my Typescripts then running a `live-server`.
The second one `Tests` is used to run tests using karma.

The problem is that when I select `Tests` then run, it will always run the `Launch` option instead.

In order for the `Tests` option to work I have to restart vscode every time I change the select input ...

Here's my configurations array:

		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/.vscode/launch_debug.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
        {
            "name": "Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/.vscode/launch_tests.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        }
`

**Comment by isidorn** [comment] 2016-03-14 10:32
Might your workspace be on a shared drive?
What OS are you using?

Is it possible to share your workspace or create a simple reproducable case for us to investigate? Since I can not reproduce this on my machine.

**Comment by MLefebvreICO** [comment] 2016-03-14 12:04
I do not work on a shared drive, everything is located in my C drive.
I'm using Windows 7 Professionnal x64.

As for sharing the workspace I cannot since it's what we are doing at my job, but if I have some spare time this week, I'll try to reproduce it on something else and post it.

**Comment by isidorn** [comment] 2016-03-14 13:02
Trying to reproduce it on something else would be great.
Also do you see this on all of your repos or on only one? Also if you open a file in vscode, and change that file outside vscode does vscode immediatly pick up that change?

**Comment by isidorn** [comment] 2016-03-23 07:51
Closing until we get reproducable steps

**Closed by isidorn** 2016-03-23 07:51 UTC
Labels: debug, needs more info
