### ISSUE TITLE
Dataloss while editing a notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#118592] opened 2021-03-10 02:11 UTC
Issue Type: <b>Bug</b>

No repro steps right now.

I was editing a TypeScript Jupyter notebook. I started from an empty notebook and added around 8 cells while intermittently running them and restarting the kernel. While was editing in the cell at the bottom, the editor refreshed on my and lost all but 3 cells. Since I run with AutoSave enabled, I lost 5 cells and their contents.

VS Code version: Code - Insiders 1.55.0-insider (Universal) (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f, 2021-03-08T05:24:34.127Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 5.4.0-1031-azure
Remote OS version: Linux x64 5.4.0-1036-azure
Remote OS version: Linux x64 5.4.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.94GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1036-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (8 x 2693)|
|Memory (System)|15.64GB (7.90GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (5.94GB free)|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.4.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
codespaces|Git|0.8.1
Kotlin|mat|1.7.1
theme-monokai-pro-vscode|mon|1.1.18
remote-ssh-edit-nightly|ms-|2021.3.12420
remote-ssh-nightly|ms-|2021.3.12420
remote-wsl|ms-|0.54.2
azure-account|ms-|0.9.7
github-browser|ms-|0.0.15
vscode-github-issue-notebooks|ms-|0.0.70
material-icon-theme|PKi|4.5.0
vscode-ruby|win|0.28.0
vscode-track-build-errors|aes|0.0.3
git-branch|ale|1.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.16
typescript-notebook|don|1.1.0
gitlens|eam|11.3.0
tsl-problem-matcher|eam|0.4.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
graphviz-markdown-preview|gee|0.0.8
codespaces|Git|0.8.1
vscode-pull-request-github|Git|0.24.0
vscode-pull-request-github-insiders|Git|2021.3.12063
mdmath|goe|2.5.1
lszomoru-proposed-api-sample|lsz|0.0.1
Kotlin|mat|1.7.1
rainbow-csv|mec|1.8.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-docker|ms-|1.10.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.4.625511240
azure-account|ms-|0.9.7
azurecli|ms-|0.5.0
hexeditor|ms-|1.4.0
js-debug-nightly|ms-|2021.3.817
vscode-github-issue-notebooks|ms-|0.0.70
vscode-js-profile-flame|ms-|0.0.14
vscode-markdown-notebook|ms-|0.0.14
material-icon-theme|PKi|4.5.0
ruby|reb|0.28.1
vscode-xml|red|0.15.0
code-spell-checker|str|1.10.2
vscode-ruby|win|0.28.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30268768
vscoresta800:30265947
vspre833:30267464

```

</details>

**Comment by rebornix** [comment] 2021-03-10 03:02
> the editor refreshed on my and lost all but 3 cells

The refresh is triggered by file change on disk and then a force reload since the document is not dirty.

**Comment by temiwale88** [comment] 2021-03-10 16:35
This is a painful issue that I discovered about 4 days ago (I have my theories) -
When working in Jupyter (.ipynb ext) notebooks, after a while the notebook reverts back to an older version.
Thus newly written code (and cells) are missing but the variables may still exist (not sure).
I noticed this over the past weekend to yesterday  – so I’d say over 4 days now. Was there a **vs code** or **Jupyter** update within that timeframe?
 
What I’ve tried:
•	Running ML experiments with Azure ML’s compute instances on vs code remote – issue persists here with .ipynb
•	Created none .ipynb files (e.g. .txt, .py) in vs code remote – no issue
•	Reinitializing my git repo in vs code remote with rm -rf .git and git clone…. – issue persists here with .ipynb
•	Running same experiment(s) on my local vs code while leveraging Azure ML’s compute instances – no issue
 
I think this might be a git and Jupyter issue.
 
For now, I’m not using vs code remote to run any notebooks so as not to lose precious work.

**Comment by jrieken** [comment] 2021-03-11 08:25
Adding @bpasero who is working on a unified editor save logic

**Comment by bpasero** [comment] 2021-03-11 08:43
First of all this needs good understanding where exactly data loss occurs and how to trigger it.

Then, if this turns out to be a consequence of reloading the model based on file events, then I suggest to disable this feature until a more generalised solution is available. I think data loss should be resolved as soon as possible and not depend on my work because I cannot make any estimates when those changes are available.

**Comment by temiwale88** [comment] 2021-03-11 16:59
I'm happy to have a video call (with screen share) with anyone from MS who wants to understand what the issue is.

**Comment by temiwale88** [comment] 2021-03-12 16:47
Adding a note: I discovered this issue on not only ns remote within Azure ML's compute instances / vms but also on my local PC's version of VS Code.

**Comment by aparente-nurix** [comment] 2021-03-20 00:22
I've experienced this 3 times when saving (auto save was off). The intact file can sometimes be found in the git tab and re-opened but is read only and can't be saved (but can be exported to .py/.html for people who want to save the code). 
However, the git version will also eventually revert back especially if changes are committed. 

See issue here: https://github.com/microsoft/vscode-jupyter/issues/5134

**Comment by thakkarparth007** [comment] 2021-03-21 15:43
Even I've faced some strange issues like this. I remember two instances:

1. I had a notebook open in both jupyter (web) and VSCode. If I'd make a change in VSCode, and on pressing Ctrl+S, the notebook state would get reverted to the version last saved from jupyter (web). If i pressed Ctrl+Z next, it'd revert to the 'correct' state in VSCode and pressing Ctrl+S again worked fine.

2. I observed a similar behaviour like this another time, but that time Jupyter (web) wasn't open. I'm not sure how VSCode would revert to an old state (don't know where the state is stored). Ctrl+Z again worked.

Apart from this, however, I've observed this once: if I close VSCode (File>Exit), the next time I open it, some of the code cells which I definitely had saved, were empty. I'll report if I observe this again.

**Comment by jrieken** [comment] 2021-03-21 16:21
@thakkarparth007 @aparente-nurix Please share what version of VS Code you are using

**Comment by thakkarparth007** [comment] 2021-03-21 16:56
@jrieken I'm using this:

Version: 1.55.0-insider (user setup)
Commit: 84fe402d655e029eb1a5c04e675bf64788fa7fcf
Date: 2021-03-15T05:14:29.836Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by aparente-nurix** [comment] 2021-03-22 22:45
> 
> 
> @thakkarparth007 @aparente-nurix Please share what version of VS Code you are using

See the link I included to the issue on the vscode-jupyter repo for the full bug report. 

https://github.com/microsoft/vscode-jupyter/issues/5134


Extension version: 2021.3.619093157
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

**Comment by jrieken** [comment] 2021-03-23 14:46
@thakkarparth007 @aparente-nurix Please both use _latest_ insiders which has a potential fix for this

**Comment by thakkarparth007** [comment] 2021-03-23 15:57
@jrieken, the latest insiders build is quite broken for me. I don't see any option to select the notebook kernel, and the cells cannot be executed. The "Run" buttons don't show next to the cells, nor does pressing Ctrl+Enter work.

The developer console showed two errors, not sure if they're both relevant:

![image](https://user-images.githubusercontent.com/747423/112176986-944e5080-8c1e-11eb-85e3-4a7e3fe39aa0.png)

**Comment by jrieken** [comment] 2021-03-23 16:11
@thakkarparth007 Make sure to be on latest and greatest jupyter too

**Closed** 2021-03-24 09:32 UTC
Labels: bug, important, notebook

**Comment by connor4312** [comment] 2021-03-26 21:19
Marking verified based on "positive feedback" -- if there are specific steps to take for verification let me know
