### ISSUE TITLE
shortcut keys for New Folder and New File not working

### ISSUE THREAD

**Issue by AmelloAster** [microsoft/vscode#155571] opened 2022-07-19 07:52 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.70.0-insider
Commit: a74adedba8fb56d14f01f7950340dab33cfeae57
Date: 2022-07-19T05:21:29.044Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
- OS Version:
-  OS           macOS 12.4.0 Monterey
CPU          Apple M1 Pro (10)
Steps to Reproduce:

1.Set the shortcut keys for New Folder and New File.
2.Using shortcut keys is not valid

https://user-images.githubusercontent.com/26178326/179697009-41946587-4a2f-4249-b2e9-5f8dcc1da6a3.mov

**Comment by gjsjohnmurray** [comment] 2022-07-19 08:03
Did this work for you on previous 1.70.0-insider versions?

**Comment by gjsjohnmurray** [comment] 2022-07-19 08:07
I was able to verify that binding unshifted a to the `explorer.newFile` command works in 1.69.2 but not in today's Insiders.

@joaomoreno could this have been caused by your find/filter changes which merged yesterday?

**Comment by gjsjohnmurray** [comment] 2022-07-19 08:44
@joaomoreno when I bind `a` to `explorer.newFile` in 1.69.2 on Windows the command takes precedence over the type filter widget. Pressing `b` or any other key brings up the widget as expected.

**Comment by AmelloAster** [comment] 2022-07-19 11:39
> Did this work for you on previous 1.70.0-insider versions?

Yes, in the previous version is normal, today I see a new insider version update prompt, after updating the operation is invalid

**Comment by AmelloAster** [comment] 2022-07-19 11:41
> @AmelloAster I'm curious to understand how this was working for you before, since pressing `A` before today's build would open the type filter widget. Did you disable that in settings?

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/26178326/179741775-cc1d9438-063f-402e-a20d-ef5bb00bbe33.png">

**Comment by joaomoreno** [comment] 2022-07-19 12:53
Thanks, then I broke it! And I'll fix it. 😄

**Comment by joaomoreno** [comment] 2022-07-24 19:09
**Verification:**

1. Create a keyboard shortcut for the letter `A` to run `explorer.newFile` using the when clause `filesExplorerFocus && !inputFocus`
2. Focus the explorer, press <kbd>A</kbd>: a new file should be created

**Comment by amunger** [comment] 2022-07-27 22:35
I can't get a new file to create with that shortcut, but it looks like the newly linked issue covers it?

**Comment by joaomoreno** [comment] 2022-07-28 11:55
Somehow this broke since my fix...

**Closed** 2022-07-28 15:27 UTC
Labels: bug, tree-views
