### ISSUE TITLE
Pressing PgUp opens up frame with broken text when using experimentalWebGl terminal renderer

### ISSUE THREAD

**Issue by Gameghostify** [microsoft/vscode#88236] opened 2020-01-07 20:09 UTC
- VSCode Version: 1.41.1
- OS Version: Windows 10 (Version 10.0.18362 Build 18362)

Steps to Reproduce:

0. Use experimentalWebGl renderer
1. Open up source control tab
2. enter some text into the commit message input
3. Press `PgUp`
4. This happens:
![image](https://user-images.githubusercontent.com/33099493/71925713-f5ad0f80-3191-11ea-96fc-5aa652eea1f3.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Gameghostify** [comment] 2020-01-07 20:10
The image shows the full vscode window (the top half is being scrolled out of view when the broken bottom area opens)

**Comment by Tyriar** [comment] 2020-01-07 22:44
This should be fixed in master/insiders, root cause was https://github.com/xtermjs/xterm.js/issues/2623

/duplicate

**Closed by Tyriar** 2020-01-07 22:44 UTC
Labels: integrated-terminal
