### ISSUE TITLE
[html] Hide the line of the html close tag

### ISSUE THREAD

**Issue by inshua** [Microsoft/vscode#55035] opened 2018-07-25 10:43 UTC
let 
```
<p>
    hello world
</p>
```
become
```
<p>
   hello world
```
or show with a blur color(gray?)

it will bring editor very clean.

**Comment by aeschli** [comment] 2018-07-26 09:42
Showing with a different color is something you could do through an extension. Hiding is more difficult. Would this be like folding? We don't support such kind of folding.

**Comment by aeschli** [comment] 2018-09-21 13:45
duplicate of #24515

**Closed by aeschli** 2018-09-21 13:45 UTC
Labels: feature-request, html
