### ISSUE TITLE
Terminal: your 131072x1 screen size is bogus. expect trouble

### ISSUE THREAD

**Issue by ahmadkhalidjs** [Microsoft/vscode#35798] opened 2017-10-07 16:03 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.4-200.fc26.x86_64

when I open the integrated terminal, I see this message:
your 131072x1 screen size is bogus. expect trouble

![22196280_1736826593284383_8653127284161334460_n](https://user-images.githubusercontent.com/18547251/31309626-efaedefc-ab91-11e7-877b-d606f9a309d3.jpg)

the image shows also bug #35794 with font isn't fitting in line.

**Comment by Tyriar** [comment] 2017-10-07 16:24
I saw this happen on Fedora. Not sure what would be causing it but it seems harmless.

**Comment by andreiucm** [comment] 2017-10-08 05:24
I have similar issue in ubutnu 16.04
https://github.com/Microsoft/vscode/issues/35773#issuecomment-334932232

**Comment by mmclark** [comment] 2017-10-08 16:03
I see it on my Fedora 26 installation as well.  Beyond the error message, the font rendering seems off.  Notice how the tops of the letters are clipped:

![screenshot from 2017-10-08 09-00-32](https://user-images.githubusercontent.com/54338/31318432-724d396a-ac07-11e7-84cd-aeacf6eecc2d.png)

**Comment by rbakaou** [comment] 2017-10-09 08:43
Got same letters clipped since Version 1.17.0. I'm on fedora 26 too.

**Comment by Zauberklavier** [comment] 2017-10-09 13:16
Same here, also on Fedora 26 on VMware with disabled GPU acceleration.

I set the font to Droid Sans Mono as a temporary workaround. It still gets clipped, this time at the bottom and only barely so it's a lot better.

**Comment by paperplane9** [comment] 2017-10-09 15:34
Got the same issue, Fedora 26 with Version 1.17.0.

**Comment by hugopossani** [comment] 2017-10-09 16:13
Fedora 25, same issue

**Comment by rohel01** [comment] 2017-10-09 19:37
- VSCode Version: Code 1.17.0  be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z 
- OS Version: Linux x64 4.13.4-200.fc26.x86_64
- Extensions:  Extension|Author  truncated |Version -|-|- better-toml|bun|0.3.1 python|don|0.7.0 plantuml|jeb|2.3.0 cpptools|ms-|0.13.1 vscode-code-outline|pat|0.0.11 rust|rus|0.3.1 vscode-lldb|vad|0.6.2 

Same issue, Fedora 26

**Comment by vstoykov** [comment] 2017-10-10 06:44
I have the same issue. Found this on the StackExchange https://unix.stackexchange.com/questions/259529/your-screen-size-is-bogus-expect-trouble

> This message comes from (perhaps other places) procps, which does a quick check to determine the screen width for ps command's notion of width.
>
> procps makes this check in set_screen_size, e.g., if the screen size is too small to print anything useful:
>
>      if((screen_cols<9) || (screen_rows<2))
>        fprintf(stderr,"Your %dx%d screen size is bogus. Expect trouble.\n",
>          screen_cols, screen_rows
>        );
> You might see the same code (via cut/paste) in other programs, but this is the most likely one.
>
> As to why the problem occurred: when starting a terminal emulator, it can be multiple processes which communicate, sharing the information about the pseudo-terminal connection. Sometimes, the information is not shared rapidly enough, causing (usually) minor errors in the terminal settings.

**Comment by mprahl** [comment] 2017-10-10 13:49
I'm having the same problem on Fedora 26.

**Comment by Tyriar** [comment] 2017-10-10 15:06
Nice find @vstoykov, looks like the terminal is set at 1 row initially which is causing the error.

**Comment by jstaf** [comment] 2017-10-11 17:35
Some additional info - this happens only when you had the integrated terminal open the last time you closed VSCode. The display corruption (with the top of each line getting moved to the bottom of the line) appears to be new to the latest update.

**Comment by Tyriar** [comment] 2017-10-13 20:54
I see layouts are occurring on start up with the rows at 1
<img width="158" alt="screen shot 2017-10-13 at 1 54 09 pm" src="https://user-images.githubusercontent.com/2193314/31566105-10f1a5fa-b01e-11e7-8805-a5644246306a.png">

**Comment by sherl0cks** [comment] 2017-10-17 14:14
FYI this is duplicate of https://github.com/Microsoft/vscode/issues/35644 which was fixed in https://github.com/Microsoft/vscode/milestone/55?closed=1

**Comment by vstoykov** [comment] 2017-10-18 11:46
@sherl0cks the issue that you mansions is not the issue that is discussed here.

**Comment by sagebind** [comment] 2017-10-18 16:22
I see the same kind of issue when using Fish shell. If the terminal is already open when the window loads, I see this in the terminal:

<img width="490" alt="screen shot 2017-10-18 at 11 19 25 am" src="https://user-images.githubusercontent.com/2192863/31730077-6ac3a426-b3f6-11e7-9e55-861d2d2aa065.png">

This doesn't happen if the terminal is initially closed, and then you toggle it manually after the window loads. It seems that the terminal size is set to be very small initially while the window is loading.

I reasonable fix I think would be to not actually spawn any integrated terminal processes until the window finishes loading (and the size can actually be known).

**Comment by Barugon** [comment] 2017-10-18 18:06
Same issue on Fedora 26.

**Comment by ezralalonde** [comment] 2017-10-18 20:57
I am also seeing this.

- Fedora 26 (Workstation Edition)
  4.13.5-200.fc26.x86_64
- Code 1.17.1
  1e9d36539b0ae51ac09b9d4673ebea4e447e5353.

If I launch after having exited with the terminal open, I see the following message:
```
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
```

It appears to be start fine if I launch after exiting with the terminal closed, or if I exit the terminal (with CTRL+D or `exit`) and then re-open it.

Thanks to jstaf for mentioning the workaround above, it helped me. And thanks to the entire `vscode` team for making such a wonderful product. I have tried many editors, and Code's the only one which has been able to take any mindshare from `vim`.

**Comment by FelikZ** [comment] 2017-10-23 07:03
same 1.17.2

**Comment by Tyriar** [comment] 2017-10-25 20:49
I think this is also causing this on Windows:

![image](https://user-images.githubusercontent.com/2193314/32022470-5b864686-b98b-11e7-835d-09dbe0ef06e9.png)

**Comment by guildeol** [comment] 2017-10-26 00:34
Hi!
The clipping issue seems to occur if the fonts for vscode and the terminal are different. After I chaged vscode to use the same font as my terminal, the clipping was gone (though the 'screen size is bogus' persists).

![image](https://user-images.githubusercontent.com/6934643/32029625-9c872f76-b9d4-11e7-9832-8cb90cf84272.png)

**Closed** 2017-10-28 08:01 UTC
Labels: bug, help wanted, integrated-terminal
