### ISSUE TITLE
Intellisense and type checking in Embedded code in markdown

### ISSUE THREAD

**Issue by llgcode** [Microsoft/vscode#15890] opened 2016-11-22 14:47 UTC
- VSCode Version: 1.7.1
- OS Version: Win 7

Unable to have completion and type checking on embedded typescript code in markdown
```markdown
    ```typescript
    import Person = require("Person");
    var person = new Person("My name");
    console.log(person.name)
    ```
```

It would be also a useful feature to be able to run embedded code

**Comment by mjbvz** [comment] 2017-11-03 19:59
Duplicate of #639

**Closed by mjbvz** 2017-11-03 19:59 UTC
Labels: duplicate, feature-request, markdown
