### ISSUE TITLE
Slow Startup Profile

### ISSUE THREAD

**Issue by errorx666** [Microsoft/vscode#28038] opened 2017-06-05 13:50 UTC
- VSCode Version: <code>Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T09:59:32.734Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2793)</code>
- Memory (System): <code>15.91GB (10.13GB free)</code>
- Memory (Process): <code>154.42MB working set (154.96MB peak, 129.91MB private, 32.46MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|304|
|main|app.isReady => window.loadUrl()|134|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2940|
|renderer|require(workbench.main.js)|555|
|renderer|create extension host => extensions onReady()|6988|
|renderer|restore viewlet|5371|
|renderer|restore editor view state|5264|
|renderer|overall workbench load|7204|
|main + renderer|start => extensions ready|11040|
|main + renderer|start => workbench ready|11225|

---
[79e7_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052137/79e7_main.cpuprofile.txt)
[79e7_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052138/79e7_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-06-15 14:46
Thanks, we found https://github.com/Microsoft/vscode/issues/24884 in that profile. Also getting the zoom factor seems to place a role here. Closing as dupe of those

**Closed by jrieken** 2017-06-15 14:46 UTC
Labels: insiders, perf-profile
