### ISSUE TITLE
Cannot install VS code on Mac Catalina

### ISSUE THREAD

**Issue by jerseymec** [microsoft/vscode#82809] opened 2019-10-18 00:31 UTC
“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Safari downloaded this file today at 8:27 PM from az764295.vo.msecnd.net.

**Comment by misolori** [comment] 2019-10-18 00:59
/duplicate of https://github.com/microsoft/vscode/issues/74782

**Closed** 2019-10-18 00:59 UTC
Labels: *duplicate
