### ISSUE TITLE
Tyepscript bug - V1.88.1 Mac/TS 5.4.5

### ISSUE THREAD

**Issue by arielkark** [microsoft/vscode#210345] opened 2024-04-14 11:48 UTC
Does this issue occur when all extensions are disabled?: Yes

- All TS features are not working, including Intellisense.
- TS server more than 100% cpu usage.

<img width="483" alt="image" src="https://github.com/microsoft/vscode/assets/142738354/b3f0b09c-b3aa-4f91-83f6-55236806f649">

[tsserver.log](https://github.com/microsoft/vscode/files/14970552/tsserver.log)

**VS Code Version: 1.88.1**
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.0.0

**OS Version: 14.0** 

**Typescript version 5.4.5**

**Comment by PurplProto** [comment] 2024-04-14 13:15
I'm also seeing this since the 1.88 release, I've had to roll back to 1.87.2. Intellisense does work for me, eventually, however, it's extremely slow and `htop` also shows tsserver.js maxing out 1 core even after my Code window has been untouched for 10 mins.

I have a different environment though WSL2 with Node.js v20.11.1.

**Comment by max06** [comment] 2024-04-14 21:43
Joining the party... Devcontainer (Node 20.11.0, bun 1.1) on remote ssh host (Ubuntu 22.04). I can easily trigger it by doing anything in the git panel.

**Comment by maslennikov** [comment] 2024-04-16 10:08
Same here. Increased CPU usage, very slow intellisense and basic file operations (like deleting or renaming).

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-27-generic snap

**Comment by mjbvz** [comment] 2024-04-29 18:18
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Specifically try disabling `@mdx-js/typescript-plugin`

**Comment by mjbvz** [comment] 2024-04-30 21:51
Looks like you have `vue.volar` enabled. Do this happen with it and all other extensions disabled?

**Comment by max06** [comment] 2024-04-30 22:24
For now I can say it still happens after disabling volar. That process started freaking out when I followed a definition into a node_module: 

![image](https://github.com/microsoft/vscode/assets/7556827/062c0a36-2cec-41a6-8f8a-c9de5be0cec3)

The trace looks the same as before.

I'll give it another shot tomorrow with as many extensions disabled as possible.

**Comment by max06** [comment] 2024-04-30 22:34
Uh, I've got something. I changed the loglevel of the typescript extension, now seeing very much (60MB in minutes) of 

```text
Info 14950[22:31:34.022] Finding references to /workspaces/nimbus/node_modules/h3/dist/index.d.ts position 29296 in project /workspaces/nimbus/app/tsconfig.json
Info 14950[22:31:34.041] Finding references to /workspaces/nimbus/node_modules/h3/dist/index.d.ts position 29296 in project /workspaces/nimbus/app/server/tsconfig.json
Perf 14950[22:31:34.055] 29692::references: elapsed time (in milliseconds) 33.3095
Info 14951[22:31:34.055] response:
    {"seq":0,"type":"response","command":"references","request_seq":29692,"success":true,"body":{"refs":[{"file":"/workspaces/nimbus/node_modules/h3/dist/index.d.ts","start":{"line":671,"offset":18},"end":{"line":671,"offset":27},"contextStart":{"line":671,"offset":1},"contextEnd":{"line":671,"offset":122},"isWriteAccess":true,"isDefinition":true},{"file":"/workspaces/nimbus/node_modules/h3/dist/index.d.ts","start":{"line":1088,"offset":2598},"end":{"line":1088,"offset":2607},"contextStart":{"line":1088,"offset":1},"contextEnd":{"line":1088,"offset":2860},"isWriteAccess":true,"isDefinition":false},{"file":"/workspaces/nimbus/app/.nuxt/types/nitro-imports.d.ts","start":{"line":141,"offset":1502},"end":{"line":141,"offset":1511},"contextStart":{"line":141,"offset":1},"contextEnd":{"line":141,"offset":1769},"isWriteAccess":true,"isDefinition":false}],"symbolName":"setCookie","symbolStartOffset":18,"symbolDisplayString":"function setCookie(event: H3Event, name: string, value: string, serializeOptions?: CookieSerializeOptions): void"}}
Info 14951[22:31:34.055] request:
    {
      "seq": 29693,
      "type": "request",
      "command": "references",
      "arguments": {
        "file": "/workspaces/nimbus/node_modules/h3/dist/index.d.ts",
        "line": 681,
        "offset": 18
      }
    }
Info 14951[22:31:34.056] Finding references to /workspaces/nimbus/node_modules/h3/dist/index.d.ts position 29678 in project /workspaces/nimbus/app/tsconfig.json
Info 14951[22:31:34.077] Finding references to /workspaces/nimbus/node_modules/h3/dist/index.d.ts position 29678 in project /workspaces/nimbus/app/server/tsconfig.json
Perf 14951[22:31:34.092] 29693::references: elapsed time (in milliseconds) 36.6133
Info 14951[22:31:34.092] response:
    {"seq":0,"type":"response","command":"references","request_seq":29693,"success":true,"body":{"refs":[{"file":"/workspaces/nimbus/node_modules/h3/dist/index.d.ts","start":{"line":681,"offset":18},"end":{"line":681,"offset":30},"contextStart":{"line":681,"offset":1},"contextEnd":{"line":681,"offset":110},"isWriteAccess":true,"isDefinition":true},{"file":"/workspaces/nimbus/node_modules/h3/dist/index.d.ts","start":{"line":1088,"offset":1586},"end":{"line":1088,"offset":1598},"contextStart":{"line":1088,"offset":1},"contextEnd":{"line":1088,"offset":2860},"isWriteAccess":true,"isDefinition":false},{"file":"/workspaces/nimbus/app/.nuxt/types/nitro-imports.d.ts","start":{"line":141,"offset":490},"end":{"line":141,"offset":502},"contextStart":{"line":141,"offset":1},"contextEnd":{"line":141,"offset":1769},"isWriteAccess":true,"isDefinition":false}],"symbolName":"deleteCookie","symbolStartOffset":18,"symbolDisplayString":"function deleteCookie(event: H3Event, name: string, serializeOptions?: CookieSerializeOptions): void"}}
Info 14951[22:31:34.094] request:
    {
      "seq": 29694,
      "type": "request",
      "command": "references",
      "arguments": {
        "file": "/workspaces/nimbus/node_modules/h3/dist/index.d.ts",
        "line": 694,
        "offset": 18
      }
    }
``` 

repeating. Same file, different line specs.

**Comment by mjbvz** [comment] 2024-05-01 16:15
Can you share the full logs or an example project so I can reproduce the issue

**Comment by itzaks** [comment] 2024-05-07 13:09
I've also been seeing extremely high CPU usage, using 1.88. Also running vue and typescript projects, with the official vue extension. When downgrading to 1.87.2 my CPU went from 102% to 3% usage.

**Comment by PurplProto** [comment] 2024-05-14 16:21
> I'm also seeing this since the 1.88 release, I've had to roll back to 1.87.2. Intellisense does work for me, eventually, however, it's extremely slow and `htop` also shows tsserver.js maxing out 1 core even after my Code window has been untouched for 10 mins.
> 
> I have a different environment though Win11 - WSL2 with Node.js v20.11.1.

This no longer appears to be an issue for me in 1.89.1. Not entirely sure what version the issue was resolved in, but can confirm I've done a full day of work on 1.89.1 without seeing this issue 😊

**Comment by mjbvz** [comment] 2024-06-27 00:08
@itzaks Please file an issue against the Vue extension. VS Code does not have built-in vue support

@max06 A spike when installing a new package is expected as we have to analyze is. Codiumate could also be causing issues so make sure to check it

Closing since we haven't heard back from the original poster. The most likely cause of this is a misbehaving extension or something like yarn pnp which patches our typescript code

**Closed by mjbvz** 2024-06-27 00:08 UTC
Labels: info-needed

**Comment by max06** [comment] 2024-06-27 08:20
I'd be very happy if it was just a spike. Sadly, it's a never-ending loop, analyzing the same file over and over again...
