### ISSUE TITLE
VSCode uses 18GB+ virtual address space

### ISSUE THREAD

**Issue by mafjmafj** [microsoft/vscode#115236] opened 2021-01-27 16:13 UTC
- VSCode Version:
$code --version
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64

- OS Version:
CentOS Linux release 7.7.1908 (Core) 3.10.0-1062.el7.x86_64 #1 SMP 

Steps to Reproduce:

1. invoke 'code' from command line
2. open folder
3. open a file in the editor
4. top shows that VIRTUAL metrics jumps up to dozens of Gb
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
113895 xxxx 20   0   14.8g 224412  81336 S   0.0  1.4   0:19.75 code 
```

Does this issue occur when all extensions are disabled?: Yes
` 29460 xxxx   20   0   18.8g 205608  88452 S   0.0  1.3   0:03.39 code  `

Note when I disabled all the extensions including all the built-in extensions as well
 (and have the same folder opened with the same single file in the editor) the mem usage is:
` 29963 xxxx 20   0 9165624 168560  69396 S   0.0  1.0   0:04.42 code  `
 
 When I enable just the git SCM integration extension I get:
`  29963 xxxx 20   0   18.7g 177348  71552 S   0.0  1.1   0:06.24 code `
 
When I disable the git SCM integration extension (restart required):
` 30461 xxxx 20   0 9164932 188792  70388 S   0.7  1.2   0:02.21 code `
 
 When I enable the C/C++ Language Basics extension, the address space goes again from this
` 31389 xxxx 20   0 9150572 146860  68656 S   0.0  0.9   0:02.07 code `
 to this:
` 31389 xxxx 20   0   18.7g 176080  68824 S   0.0  1.1   0:04.04 code`

 The side effect is that search or extensions installation or opening files in editor fail often with `-ENOMEM`.
  
I have checkd /proc/pid/maps and these are the biggest maps:
```
 92200960 5586437c1000-558648faf000 r-xp 01635000 fd:00 424266 /usr/share/code/code
106078208 7f8457dd1000-7f845e2fb000 r--p 00000000 fd:00 133047 /usr/lib/locale/locale-archive
132386816 ff0001ff000-ff008040000 ---p 00000000 00:00 0
2147483648 2cdd5a870000-2cddda870000 ---p 00000000 00:00 0
4081844224 ff00cb40000-ff100000000 ---p 00000000 00:00 0
8573157376 2cdddb870000-2cdfda870000 ---p 00000000 00:00 0
```
The last map is over 8GB in size.

**Comment by mafjmafj** [comment] 2021-01-27 17:06
I have tried other versions of vscode on the same host:
```
$code --version
1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
```

as well as code-insiders-1.53.0-1611738706.el7.x86_64.rpm 
All with the same effects (use of 18.7GB)

I have tried to go as far back as possible and 1.45.1 still somewhat bad but better
` 44926 xxxx 20   0   12.1g 182652  71224 S   0.0  1.1   0:05.02 code       `                                                    
Which in my case makes vscode about usable.


Finally 1.44.2 looks good :
` 46015 xxxx 20   0 1298152 301568  89264 S   0.0  1.9   0:06.07 code`

**Comment by mafjmafj** [comment] 2021-01-27 17:09
Just to sum up. This looks like regression between 144.2 and 1.45.1, Where the majority 2/3 of virtual space usage increase occurred.

**Comment by ErikSwan** [comment] 2021-01-28 00:25
I'm fairly certain something related to this is the root cause behind the lockups I am experiencing on a CentOS 7.7 VM with 8GB of memory with recent releases of VS Code.

Any release I've tried that's newer than 1.48.2 (July 2020) causes VS Code to immediately lock up when opening a new file/editor, with the following in the log (from `code --verbose`):

```
$ ./VSCode-linux-x64_1.52.1/bin/code --verbose
[...snip...]
[17110:0127/182147.152213:INFO:CONSOLE(1779)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.files.newUntitledFile", source: file:///home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/out/vs/workbench/workbench.desktop.main.js (1779)
[17110:0127/182147.634814:INFO:CONSOLE(1779)] "%c  ERR color: #f33 WebAssembly.Memory(): could not allocate memory: RangeError: WebAssembly.Memory(): could not allocate memory
    at Object.default (/home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/node_modules.asar/vscode-oniguruma/release/main.js:1:8315)
    at /home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/node_modules.asar/vscode-oniguruma/release/main.js:1:5457
    at Object.t.loadWASM (/home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/node_modules.asar/vscode-oniguruma/release/main.js:1:5685)
    at E._doGetVSCodeOniguruma (file:///home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/out/vs/workbench/workbench.desktop.main.js:5988:17)
    at async Promise.all (index 1)
    at async E._getOrCreateGrammarFactory (file:///home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/out/vs/workbench/workbench.desktop.main.js:5983:921)
    at async file:///home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/out/vs/workbench/workbench.desktop.main.js:5984:841", source: file:///home/eswan/Downloads/VSCode-linux-x64_1.52.1/resources/app/out/vs/workbench/workbench.desktop.main.js (1779)
#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
#
#
#FailureMessage Object: 0x2aebfd46f620#0 0x55844ded1d69
<unknown>
```

Versions 1.45.1 to 1.48.2 inclusive do not lock up, but syntax highlighting does not work (not sure if this is related or not). Versions 1.44.2 and prior work as expected (syntax highlighting works fine), so this seems to match up with you finding a regression in between 1.44.2 and 1.45.1.

However, I cannot reproduce the virtual address space issue on 1.45.1:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
14344 eswan     20   0  867592 157080  58284 S   0.0  2.0   0:05.25 code
```


My environment:
``` 
$ cat /etc/centos-release
CentOS Linux release 7.7 (Core)

$ uname -r
3.10.0-1062.1.2.el7.x86_64

$ ulimit -v
8810313
```

**Comment by ErikSwan** [comment] 2021-01-28 00:59
I tried on a much larger CentOS 7 machine and I am able to reproduce the virtual address space issue on VS Code 1.52.1:

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                       
125468 eswan     20   0   18.5g 141760  58572 S   0.0  0.1   0:03.49 code
```

Environment is the same as above with the exception that on this bigger VM, `ulimit -v` is `290265558`. VS Code does not lock up on this machine.

**Comment by mafjmafj** [comment] 2021-01-28 01:23
I have figured out that virtual address space usage was correlated with Commit memory, which was a real culprit.

My Centos system comes with Commit Memmory restriction policy enabled by default.
/proc/sys/vm/overcommit_memory = 2, which with other parameters (actual physical memory, overcommit_ratio and swap) resulted in Commit Limit of some 16GB.

Opening my project folder and few windows bumps Commit AS metric (from /proc/meminfo) by 3GB alone.
Fortunately I was able to increase overcommit_ratio.

**Comment by kieferrm** [comment] 2021-01-30 02:25
@deepak1556 we should at least document that.

**Comment by mafjmafj** [comment] 2021-01-30 17:13
I have been made aware that this is V8 javascript engine allocating whole 4GB 32-bit addressable blocks of virtual memory to avoid expensive boundary checking

**Comment by ErikSwan** [comment] 2021-02-02 02:19
I'd be curious to know if anyone can reproduce what I was experiencing with the current release of VS Code locking up on a Linux machine with only 8GB of physical or virtual memory.

**Comment by mafjmafj** [comment] 2021-02-02 08:55
Erik, With my 16GB VM I saw variety of problems: VS code stopping responding to menu actions and keywords, and searchbox not showing results but '-ENOMEM' instead.

Does it work for you now? Have you tried setting /proc/sys/vm/overcommit_memory to 0 or /proc/sys/vm/overcommit_ratio to 300?

**Comment by ErikSwan** [comment] 2021-02-09 17:47
Unfortunately I do not have root access on the VM or the ability to reconfigure the VM. Is this issue isolated to virtual machines? What happens on a machine with 8GB of physical memory?

It seems broken to me that a text editor would require >16GB of memory just to get basic functionality working correctly.

**Comment by evbo** [comment] 2021-07-27 03:58
Is there anyway to avoid the `Fatal process out of memory: Failed to reserve memory for new V8 Isolate` error without making changes to the environment requiring root?

I am trying to support a customer and do not have control over their environment and they are experiencing this issue

**Comment by evbo** [comment] 2021-07-28 14:38
@ErikSwan I can confirm this issue occurs independent of VsCode. If I simply package an electron.js app using electron version `12.0.9` I get this error in _certain_ Centos7 environments (see fix below).

If I revert to a June 2020 version of electron, version `8.3.2`, I do not get this error at all. Not sure if it matters, but the environment I'm running in seems to only work if I run with `--no-sandbox --in-process-gpu` commandline switches

**Comment by evbo** [comment] 2021-07-28 14:48
@ErikSwan I can confirm this issue occurs independent of VsCode. If I simply package an electron.js app using electron version `12.0.9` I get your same `Failed to reserve memory for new V8 Isolate` error in _certain_ Centos7 environments (see fix below).

If I revert to a < July 2020 version of electron.js like you say, version `8.3.2` (from June 15th), I do not get this error at all. Not sure if it matters, but the environment I'm running in seems to only work if I run with `--no-sandbox --in-process-gpu` commandline switches

**Comment by ErikSwan** [comment] 2021-08-31 17:07
Seems like it is an issue that would need to be fixed in the upstream Electron, then. Unfortunately I simply gave up on making it work and resigned myself to using a different editor in my CentOS 7 environment.

**Comment by deepak1556** [comment] 2022-12-07 16:31
Closing as this is default allocation performed by the runtime and not something VSCode can manage.

**Closed by deepak1556** 2022-12-07 16:31 UTC
