### ISSUE TITLE
code command from wsl doesn't exit

### ISSUE THREAD

**Issue by sarim** [microsoft/vscode#193302] opened 2023-09-17 14:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 11 22H2 22621.2215. WSL Ubuntu 22.04.3 LTS

Steps to Reproduce:

1. code .
2. observe as vscode opens but terminal code command doesn't exit

https://github.com/microsoft/vscode/assets/1235888/35f5d0e0-c07f-446a-b1d5-a03c43b4070c

**Comment by anupdebnath** [comment] 2023-09-17 14:57
I have the same issue,

- VS Code Version: 1.82.2 
- OS Version: Windows 10 Pro 22H2 OS Build 19045.3448 WSL Ubuntu 22.04.2 LTS

**Comment by yongzhang** [comment] 2023-09-18 07:27
https://github.com/microsoft/vscode/issues/193321

**Comment by sarim** [comment] 2023-09-20 17:54
#193453

**Comment by aeschli** [comment] 2023-09-21 21:08
Duplicate of #193453

**Closed by aeschli** 2023-09-21 21:08 UTC
Labels: triage-needed

**Comment by sarim** [comment] 2023-09-21 21:29
> Duplicate of #193453

@aeschli I opened this issue two days before that one, but somehow it didn't get triaged :P
