### ISSUE TITLE
"Check for updates" missing from Help menu

### ISSUE THREAD

**Issue by Cirieno** [Microsoft/vscode#53708] opened 2018-07-06 12:40 UTC
As the title says, "Check for updates" has gone from the Help menu.  Probably not actually an issue but I'm marking it here in case others also notice this.  Feel free to close / delete if this has already been addressed.

- VSCode Version: 1.25.0

![vscode_issues](https://user-images.githubusercontent.com/37182505/42379193-e707be52-8121-11e8-957d-ff304b1a943f.png)

**Comment by webmasterMeyers** [comment] 2018-07-06 14:41
I do not have this issue, Windows 10 Pro, same VS Code version

**Comment by jpdemko** [comment] 2018-07-07 20:17
I also have this issue, Windows 10 Pro, same VS Code version. :)

**Comment by RonanQuigley** [comment] 2018-07-12 12:18
I also have this issue too and it's the same version. This issue isn't in insiders though.

**Comment by caiornpstrf** [comment] 2018-08-14 15:28
Also have the same issue:

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
Windows 10 Enterprise and Professional

Seems like the issue is related to the new title bar view. On my end it shows up in the old title bar but not the new one:

![image](https://user-images.githubusercontent.com/31257987/44101258-644a3494-9fbd-11e8-8f91-143484413651.png)
![image](https://user-images.githubusercontent.com/31257987/44101316-88b6289c-9fbd-11e8-9963-0c49e2a0678c.png)

**Comment by sbatten** [comment] 2018-08-14 23:26
Closing this as it was resolved in 1.26, assigning to August to ensure it is verified again separately.

**Closed by sbatten** 2018-08-14 23:26 UTC
Labels: bug, workbench-menu
