### ISSUE TITLE
Old/new snippets being summoned by Intellisense right after a change

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#32724] opened 2017-08-17 15:07 UTC
- VSCode Version: 1.15.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Change an existing snippet (PowerShell in this case).
2. Open a script, type the snippet prefix.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/4306938/29419115-e338a8d2-8333-11e7-8f50-485112136a45.png)

**Comment by jrieken** [comment] 2017-08-18 12:54
You are saying both are user snippets and on disk there is actually only one snippet? Does this persist?

**Comment by adbertram** [comment] 2017-08-18 13:21
There is only one snippet for that prefix on disk but the old version and
the new version show up via Intellisense. I can restart VS Code and it's
back to only showing a single instance as it should.

**Comment by jrieken** [comment] 2017-08-18 15:07
Hm, still cannot reproduce... For me the snippet isn't duplicated... What in the snippet are you changing, the `body` I assume?

**Comment by adbertram** [comment] 2017-08-19 14:49
Yes. I'm just making a minor change. I'm not sure how it got in this
particular state.

**Comment by jrieken** [comment] 2017-09-22 15:49
@adbertram Are you still seeing this? Can you try this with current insider: https://code.visualstudio.com/insiders?

**Comment by adbertram** [comment] 2017-09-27 19:39
I don't see this behavior with the latest insiders build. Thanks!

**Comment by jrieken** [comment] 2017-09-28 07:38
Ok, closing then. Thanks for getting back to me

**Closed by jrieken** 2017-09-28 07:38 UTC
Labels: needs more info, snippets
