### ISSUE TITLE
Tooltip info string “New Object” in file “settings.json” is not localized

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode#106221] opened 2020-09-07 08:21 UTC
VSCode Version: VSCode 1.48.2

Steps to Reproduce:
1.Install VSCode
2.Install Language Extension Chinese(Simplified) and C++ extension
3. Open Settings UI page
4. Click link “Edit in settings.json” (will navigate to file "settings.json")    
![image](https://user-images.githubusercontent.com/37648162/92364793-2c269a00-f126-11ea-90e4-b6f169b65359.png)
5. Check the info in tooltip window

Expected:
Tooltip info string “New Object” should localized

Actual:
Tooltip info string “New Object” is not localized
(Repro on Windows, Linux and Mac)
![image](https://user-images.githubusercontent.com/37648162/92364749-1a44f700-f126-11ea-917c-8900592e5fc2.png)

**Comment by Colengms** [comment] 2020-09-09 19:55
@weinand Please re-open.  The "New object" string is coming from VS Code.  This string does not exist anywhere within the code of the C/C++ Extension.

I see the string in the following file:  C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain.js

**Comment by aeschli** [comment] 2020-09-10 07:20
duplicate of https://github.com/microsoft/vscode/issues/106220

**Closed by aeschli** 2020-09-10 07:20 UTC
