### ISSUE TITLE
High CPU load on single-CPU VM

### ISSUE THREAD

**Issue by hgotur** [Microsoft/vscode#17097] opened 2016-12-13 01:11 UTC
- VSCode Version: 1.7.2
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1.  Install VS Code
2.  Launch VS Code

I tried uninstall and reinstall and it still happens. I open VS Code, and the CPU usage goes up. It goes back down after a few seconds, but shoots back up again. This is despite not opening any files or doing anything on VS Code.

**Comment by kieferrm** [comment] 2016-12-13 05:22
@hgotur Do you see any errors in the dev console? `Command Palette > Developer: Toggle Developer Tools`. Also, can you pls go to `Command Palette > Help: Report Issue` and copy the list of extensions in the pre-populated issue into this one?

**Comment by bpasero** [comment] 2016-12-13 05:51
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jrieken** [comment] 2016-12-13 08:00
Also, please use process explorer and provide the full list of arguments of the process going crazy

**Comment by alexdresko** [comment] 2016-12-16 20:16
Exact same problem here. Basically a brand new 2012 R2 VM install on VMWare. 2GB RAM. Brand new install of vscode, with no plugins.  

It's practically impossible to use. It takes 30+ seconds for the window to even appear after clicking the icon to launch the application. Don't know if it'll ever come up enough for me to get to the command palette. 

I am using the latest insiders build. "code - insiders.exe" is consuming the CPU. 

![image](https://cloud.githubusercontent.com/assets/333022/21276996/1d5eff2c-c3a2-11e6-85b4-2111b8234705.png)

![image](https://cloud.githubusercontent.com/assets/333022/21277082/8936c748-c3a2-11e6-88cb-f7558ee4eb7d.png)

Hope that helps.

**Comment by bpasero** [comment] 2016-12-17 08:14
We have heard reports of VS Code running slow on VMs when they are configured with 1 CPU.

**Comment by alexdresko** [comment] 2016-12-18 14:44
@bpasero It does only have one CPU. I'll fiddle some knobs when I get back from vacation and see if it fixes the problem.

**Comment by hgotur** [comment] 2016-12-19 22:57
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.8.1|
|csharp|ms-vscode|1.3.0|


These are the extensions. There were no errors in the dev console. My configuration is also a VM with one CPU.

**Comment by amitmittal** [comment] 2016-12-22 08:27
I am also facing the exact same issue on a vm with single core cpu and 2 gb ram. Works pretty cool on my local dual core pc. 
Fresh install of VS, No extensions installed. 

![capture](https://cloud.githubusercontent.com/assets/5319694/21419564/4687e19a-c7dd-11e6-8bb2-619b1c0b8d65.PNG)

**Comment by mguinness** [comment] 2017-01-04 18:10
Same issue here with version 1.8, CPU is maxed out.  Fresh install, no extensions.  Single core w/ 1 GB memory.

Any known workarounds?  Would using an earlier version help?  Is this a VS Code issue or Electron?

**Comment by vov32** [comment] 2017-03-02 21:36
I have same issue on core i7. Host arch linux.
- VSCode Version: <code>Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:47:58.633Z)</code>
- OS Version: <code>Linux x64 4.9.9-1-MANJARO</code>
- CPUs: <code>Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 2599)</code>
- Memory (System): <code>9.63GB (6.10GB free)</code>
- Memory (Process): <code>173.82MB working set (211.97MB peak, 99.30MB private, 74.53MB shared)</code>
- Load (avg): <code>2, 1, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|58|
|main|app.isReady => window.loadUrl()|408|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|313|
|renderer|require(workbench.main.js)|1660|
|renderer|create extension host => extensions onReady()|783|
|renderer|restore viewlet|1084|
|renderer|restore editor view state|1|
|renderer|overall workbench load|1399|
|main + renderer|start => extensions ready|3347|
|main + renderer|start => workbench ready|3875|

**Comment by ShayneSmyth** [comment] 2017-03-06 03:02
Same here. 100% cpu just from opening vscode. no extensions, 
Brand new Azure Windows Server 2012 R2 - 1 cpu
Fresh install of vscode 1.10.1

**Comment by BSykesUSCG** [comment] 2017-03-06 15:07
CONFIRMED SOLUTION -- We added another core to our existing VM and the CPU issues disappeared for both Visual Studio Code and Atom (Both of which rely on Electron).  At this point I believe this is actually electron issue [electron/electron#7839](https://github.com/electron/electron/issues/7839).

**Comment by jrieken** [comment] 2017-04-05 09:54
Closing this as question. Our application model highly depends on multiple process. This isn't fit single core machines well but we also believe that's a problem of VMs. Single core hardware should be very rare these days.

**Closed by jrieken** 2017-04-05 09:54 UTC
Labels: freeze-slow-crash, perf, question

**Comment by alexdresko** [comment] 2017-04-05 13:33
Rare, like my brand new Raspberry PI Zero W? Sorry, I get it. But it's frustrating. I love VS Code.

**Comment by mguinness** [comment] 2017-04-05 16:54
@jrieken How about adding the need for multiple cores in release notes and [VS Code requirements](https://code.visualstudio.com/docs/supporting/requirements)?

**Comment by jrieken** [comment] 2017-04-10 07:39
cc @gregvanl for the comment above

**Comment by lasrol** [comment] 2017-05-02 10:42
IMHO this should be fix/improved. Code is a good tool to edit files on the fly and should be a proper lightweight alternative to the big IDE's. For me this is the exact solution where i would use Code instead of any other IDE/Editor, systems with low resources and I don't want to install VS(or any other IDE), code is fast and easy to install and gives me just what i need for debugging and some quick editing of my source files.

**Comment by knocte** [comment] 2017-05-09 06:55
IMNSHO at the very least, VisualStudioCode should detect that it's running on a single-core and give an error to the user at launch time, informing him about this limitation, otherwise the UX is quite ludicrous.

**Comment by Coresi7** [comment] 2017-06-13 10:25
@jrieken Problem still on version 1.13
For client, yes, for server and VM, no. More cores means more money and waste of computing resources.
So you may think it wont be used on server or VMs?

**Comment by JackUkleja** [comment] 2017-07-13 00:45
I am getting this issue on Hyper-V single CPU VM.

CPU is pegged at 100% just starting up Code and stays pegged. The OS is unusable.

I do not understand how this issue is closed. This is **not** a case of "VS Code is a resource intensive app, you can't expect it to run well on a single core VM!!".

There appears to be some horrible degenerate bug here.

**Comment by m-brian** [comment] 2017-07-22 04:19
Version 1.5.2 takes a minute to launch but otherwise works well on single core machines.

**Comment by mguinness** [comment] 2017-07-22 22:08
@m-brian Thanks, confirmed that version from August 2016 works.  Also, there is now an insiders build for a new [64 bit](https://code.visualstudio.com/updates/v1_14#_engineering) version which might be worth trying.

**Comment by javp0103** [comment] 2017-08-21 10:53
Version 1.15.1, clean installation without extensions in a single hyper-v VM Windows Server 2012 R2 (6.3.9600) 100% cpu. Upgraded to 2 cpu and VS Code starts up without any problem

**Comment by costica-moldovanu** [comment] 2017-09-13 21:27
Same problem as today September 13, 2017. Just installed latest version and never have been able to start it. The VM CPU goes to 99% and becomes unresponsive. Fresh install, no extensions..
![image](https://user-images.githubusercontent.com/11563621/30401489-6ec2aee6-98a8-11e7-8a8e-48f3ecfc64fa.png) 
And is starting 4 different threads. Does not make sense. I have installed it just to use it for getting source code from TFS without installing a full VS . Thx, but NO thx.

**Comment by mguinness** [comment] 2017-09-13 21:39
@costica-moldovanu AFAIK the single core CPU issue isn't VS Code per se, but rather the underlying use of [Electron](https://github.com/electron/electron).  As for TFS, you can also use the [TFS CLI](https://github.com/Microsoft/tfs-cli).

**Comment by costica-moldovanu** [comment] 2017-09-14 00:38
Thx
