### ISSUE TITLE
Choosing a code suggestion replaces first match completely inside import quotes

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#54586] opened 2018-07-18 15:31 UTC
Issue Type: <b>Bug</b>

![issue](https://user-images.githubusercontent.com/46930/42891446-106dad16-8ab8-11e8-9af2-3d083f1db30a.gif)

Steps to reproduce: 

* Select some part of code
* Select another part
* Type some characters
* Select one of suggestions

As you can see the first selected part will be replaced completely. 😞 

---

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
Bookmarks|ale|9.0.0
project-manager|ale|8.0.0
vscode-color|ans|0.4.5
snapshot-tools|asv|0.0.7
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.0
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
vscode-styled-components|jpo|0.0.21
typescript-duck-snippet|Ky6|1.0.0
atom-keybindings|ms-|3.0.4
vscode-icons|rob|7.24.0
code-settings-sync|Sha|3.0.0
stylelint|shi|0.37.0
language-stylus|sys|1.9.2

(1 theme extensions excluded)

</details>

**Comment by Ky6uk** [comment] 2018-07-18 15:40
I'm not sure, but maybe this is a TypeScript-related issue.

**Comment by mjbvz** [comment] 2018-07-18 21:50
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Ky6uk** [comment] 2018-07-19 03:30
@mjbvz yes, it does.

---

VS Code version: Code - Insiders 1.26.0-insider (a7689a0eb1369afbb3d912cb38876a93e601ff06, 2018-07-18T05:11:51.838Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (1.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3826598|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment] 2018-09-20 14:18
Interestingly, #58597 has the exact opposite problem where the text is inserted and not replaced. If we could only swap behaviors in these two cases.

![completion-bug-now](https://user-images.githubusercontent.com/5047891/45484934-1f008b80-b756-11e8-9432-03c12788054a.gif)

**Comment by mjbvz** [comment] 2019-01-05 03:10
With #58597 addressed, the behavior for path completions now matches how we handle normal completions. Replacing the entire path segment also matches how path completions work for other languages like html and css.

Since there hasn't been any other feedback on this issue since June, I'm closing this as by-design

**Closed by mjbvz** 2019-01-05 03:10 UTC

**Comment by Ky6uk** [comment] 2019-01-07 11:24
@mjbvz the original issue a little bit different. Problem is a different completion with multiselect. Look at gif file. I selected two similar parts then I selected suggested thing but first selection do replace entire line when second selection only part of.

![issue](https://user-images.githubusercontent.com/46930/42891446-106dad16-8ab8-11e8-9af2-3d083f1db30a.gif)

**Comment by mjbvz** [comment] 2019-01-07 22:57
Created simplified example with https://github.com/Microsoft/vscode/issues/66180
