### ISSUE TITLE
HTML File Preview

### ISSUE THREAD

**Issue by Malikhardy23** [microsoft/vscode#85800] opened 2019-11-29 05:49 UTC
Issue Type: <b>Bug</b>

I'm unable to see my HTML file previews on Microsoft Explorer. Any help would be greatly appreciated, 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 5405U @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-html-css|ecm|0.2.3
php-intellisense|fel|2.3.13
vscode-firefox-debug|fir|2.5.3
terminal|for|0.0.10
live-html-previewer|hdg|0.3.0
python|ms-|2019.11.50794
cpptools|ms-|0.26.1
live-server-preview|neg|0.1.4
platformio-ide|pla|1.10.0
LiveServer|rit|5.6.1
vscode-zipexplorer|sle|0.3.1

</details>
3

**Comment by gjsjohnmurray** [comment] 2019-11-29 07:11
/needsMoreInfo is this caused by an extension? Please run with all extensions disabled and test. If extension-specific, report to its repo and close this issue.

**Comment by Malikhardy23** [comment] 2019-11-29 17:19
I was experiencing difficulties because of my extensions. Thank You!

**Comment by gjsjohnmurray** [comment] 2019-11-29 17:35
@Malikhardy23 please close this issue.

**Comment by sandy081** [comment] 2019-12-01 13:27
Please file the issue against the extension.

**Closed by sandy081** 2019-12-01 13:27 UTC
Labels: needs more info
