### ISSUE TITLE
F# Syntax highlighting breaks on class definitions with private primary constructor

### ISSUE THREAD

**Issue by moonPtr** [Microsoft/vscode#48780] opened 2018-04-26 18:59 UTC
![code_2018-04-26_20-59-04](https://user-images.githubusercontent.com/32428601/39326259-aedc479c-4994-11e8-9999-ba03cdf1e6fd.png)

And while I'm on the topic of private constructors, the highlighting for the access specifier is inconsistent between Record types and Discriminated Union types:

![code_2018-04-26_21-02-32](https://user-images.githubusercontent.com/32428601/39326412-299b74ee-4995-11e8-88d8-a8f927ffaf82.png)

**Comment by mjbvz** [comment] 2018-04-27 20:01
Please post up source code along with all screenshots

**Comment by moonPtr** [comment] 2018-04-27 20:31
That's... the whole code?
It just affects the type signature and nothing else
![code_2018-04-27_22-31-30](https://user-images.githubusercontent.com/32428601/39383765-c50c86a4-4a6a-11e8-8748-d26d32f3ad6e.png)

**Comment by mjbvz** [comment] 2018-04-27 20:41
Please share the text of the source code along the screenshots

**Comment by moonPtr** [comment] 2018-04-27 20:44
ah, done

**Comment by mjbvz** [comment] 2018-04-27 20:53
Thanks. This is caused by the f# grammar from your f# extension. Please file the issue here: https://github.com/ionide/ionide-fsgrammar/issues/38 

I believe the no-highlighting issue has already been fixed in master for that extension. The inconsistent highlighting remains

**Closed by mjbvz** 2018-04-27 20:53 UTC
Labels: grammar, needs more info
