### ISSUE TITLE
Rename Symbol Creates Conflicting File

### ISSUE THREAD

**Issue by bobbyg603** [Microsoft/vscode#39399] opened 2017-12-01 03:34 UTC
- VSCode Version: 1.18.1
- OS Version: OS X 10.13.1

Was refactoring some code for a company I contract for. I'm not sure how I got into this state, but this issue happened twice today (VSCode was restarted between occurrences). This bug ended up causing data loss. I worked in the rogue file by accident and lost a bunch of work by mindlessly clicking the checkmark after being asked to compare conflicting files.

[Video Demonstration](https://drive.google.com/file/d/1x9KsV9TqQRp6piYz2iJIqnPxHjF8yHs5/view?usp=sharing)

Steps to Reproduce:
1. Right click next to a function parameter in a .ts file
2. Select "Rename Symbol"
3. Notice the editor opens a new tab with a new file. Notice the new file has the same name as the old file except the first letter is capitalized. Notice that the symbol is not renamed in the original file, but it is renamed in this weird new file.

This seems very strange, but it has happened twice today and once resulted in data loss. It felt worth reporting.

Thanks,
Bobby

**Comment by bobbyg603** [comment] 2017-12-01 04:00
Additional observations:
1. Any variable in this file will trigger the issue, not just function parameters
2. The rogue file does not appear on disk prior to it being created by VSCode

**Comment by mjbvz** [comment] 2017-12-01 19:21
The symptoms sound like https://github.com/Microsoft/TypeScript/issues/19329 to me. The new file's case is being changed here, correct?

**Comment by bobbyg603** [comment] 2017-12-01 19:57
@mjbvz yes, this looks like the same issue. can you please specify what additional info you need? i'd be happy to get whatever information you need as this has been a huge productivity drain over the last few days. thanks!

**Comment by mjbvz** [comment] 2017-12-07 01:09
To check this:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings
1. Close all editors in your workspace then restart vs code.
1. Now reproduce the problem
1. Open the output panel and go to the `TypeScript` section

In this log, look for the bad editor's filepath. See if there are any casing differences between this and the original path

**Comment by Krossmaskinen** [comment] 2017-12-12 16:23
A new file is being created, but it's being created by VSCode (or TS?). It's happening to me all the time and is starting to take quite a lot of time away from work.

I sometimes get it when I use "F12" to go to definition as well.

**Comment by mjbvz** [comment] 2017-12-13 20:50
@Krossmaskinen The problem is that TS returns a file with the incorrect case to VS Code which causes us to create it on the disk. Can you please quickly go through the [steps in my comment](https://github.com/Microsoft/vscode/issues/39399#issuecomment-349828420) to confirm that this is indeed a duplicate of Microsoft/TypeScript#19329

**Comment by Krossmaskinen** [comment] 2017-12-14 10:25
@mjbvz it looks like it indeed. The difference is that in my case it's happening on files that never changed names. Still looks like a TS-problem though.

**Comment by mjbvz** [comment] 2017-12-14 23:03
@Krossmaskinen Are you able to share the relevant log sections? Since there is no rename in this case, I think it may be a different TS issue

**Closed** 2017-12-21 23:05 UTC
Labels: needs more info, typescript
