### ISSUE TITLE
Two-step collapse in multi-root Explorer setting

### ISSUE THREAD

**Issue by SamJust** [microsoft/vscode#90961] opened 2020-02-19 10:04 UTC
Can we, maybe, have a setting to control this behavior? Because I don't like it, and I'm VERY used to collapsing everything in one click, since even on top level my folders have almost two dozens entries each, and if i want to quickly find something, I still need to scroll. Though I do see the usefulness of this.

We should have setting to control this behavior, IMO.

**Comment by isidorn** [comment] 2020-02-19 11:27
This is a fair feature request. We might introduce this setting in the future, thus assigning this to Backlog.
fyi @roblourens

**Comment by roblourens** [comment] 2020-02-19 22:06
Out of curiosity @SamJust would you also want a setting to disable this in the search view, or is that not an issue for you?

**Comment by SamJust** [comment] 2020-02-20 12:07
@roblourens Not really, because I usually search in a specific folder, so I don't get results in multiple folders. Though, I think, that if you are to add setting for file explorer, it'd be good to have one for search bar, for consistency.

**Comment by blocknonip** [comment] 2020-02-26 21:45
Honestly, I'm amazed that the default behavior that has existed since *forever* was changed without so much as an option to undo it. I've been happily minimizing all folders since the first release of VSCode, and now I have to spam-click the mouse button instead. It's quite infuriating.

Also, I think this ticket could use a more descriptive title.

**Comment by SamJust** [comment] 2020-02-26 21:56
@isidorn HI! This behavior is annoying. So, I consider doing changes to the code myself. I know I am to discuss this with feature owner, whom I assume is you. The question is, can I start on this, or you don't accept external help for this issue?

**Comment by isidorn** [comment] 2020-02-27 09:21
We still do not accept PRs for this. Though this might change in the future.

**Comment by blocknonip** [comment] 2020-02-27 12:42
> We still do not accept PRs for this. Though this might change in the future.

It sounds like the feature should be reverted, then. This was clearly a short-sighted change that did not take into account users' workflows over the past **4 years**.

**Closed** 2020-06-09 14:03 UTC
Labels: *out-of-scope, feature-request, file-explorer

**Comment by blocknonip** [comment] 2020-06-09 14:17
@isidorn This isn't a feature request. This is a bug report for expected behavior that was changed after **4 years** of daily use.

I don't think it's fair to your users to whisk this away under the carpet.
