### ISSUE TITLE
Special Character being duplicated when entered on Mac

### ISSUE THREAD

**Issue by arturogh** [Microsoft/vscode#35406] opened 2017-09-29 23:49 UTC
- VSCode Version: Code 1.16.1 **[Unsupported]** (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
vscode-custom-css|be5|2.5.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
vscode-coffeescript-preview|dre|0.1.4
vscode-babel-coloring|dza|0.0.4
auto-rename-tag|for|0.0.14

(4 theme extensions excluded)

---

Steps to Reproduce:

1. On a Mac, to write 'ñ', you hold down 'n', and then press '1' when a bubble pops up.
2. When I do this on VS Code, I get 'nñ' (an 'n' and also an 'ñ').

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2017-10-02 07:52
Duplicate of #34826

**Closed by alexandrudima** 2017-10-02 07:52 UTC
