### ISSUE TITLE
Debugging not working with v8 version 3.12.19.19

### ISSUE THREAD

**Issue by CodeCloak** [Microsoft/vscode#17323] opened 2016-12-15 17:07 UTC
- VSCode Version: 1.8.0
- OS Version: Win 7 enterprise 64 bit
- Node Version: 6.5.0 (Also tested with 4.1.2 and 4.6.0)

Hello, I work at Everi Games and we are evaluating Visual Studio Code as an editor to replace Webstorm (We script games in Javascript on top of a C++ engine using v8). We like everything about it, but we can't seem to get debugging to work. We think that it is related to the version of v8 we are using but we currently aren't in a position where we can update v8. I've done some debugging and found where the error is occurring, but I'm not sure what I could do to fix it. Could someone on the VSCode team look at debugging with an older version of v8, preferably version 3.12.19.19 and see what could be done to allow debugging to work?

Code that is breaking with relevant variables expanded in watch:
![vscodebreaklocation](https://cloud.githubusercontent.com/assets/10749782/21233671/9e012940-c2b5-11e6-91e6-2890d5bc596a.png)

Log dump:
[VSCodeDebugLog.txt](https://github.com/Microsoft/vscode/files/655304/VSCodeDebugLog.txt)

**Comment by roblourens** [comment] 2016-12-15 19:20
This is a very old v8 version, it at least predates Node 0.9 which is the oldest one that nvm will install.

**Comment by isidorn** [comment] 2016-12-19 14:37
Hello @CodeCloak setting up such an old v8 version does not sound fun to me. So let's debug it at your machine.
Can you please check the callstack who is calling `rawUpdate` method which breaks on exception, it should probably be the debug service around line 258, if yes can you please set a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L258). And basically let us know what is `response.body.threads`

I suspect when you say debugging is not working that breakpoints do not get hit, you do not see locals, can not evaluate and so on.

**Comment by CodeCloak** [comment] 2016-12-19 15:22
I can do that.

![vscoderequesteddata](https://cloud.githubusercontent.com/assets/10749782/21317858/8971c84e-c5cc-11e6-8f8f-49072dd15ce8.png)

I do actually HIT the breakpoints, but get no visual indication of such, don't see locals, can't evaluate, etc.

**Comment by isidorn** [comment] 2016-12-19 15:43
Ok what seems to be fishy here is that the adapter is returning the thread event with `Id === 3`. My suspicion what is going on
1. VSCode recieves a stopped event for `threadId === 1` 
2. VSCode fetches threads from the adapter and weirdly only gets back the thread with `threadId === 3`
3. Null exception happens because a thread with `Id === 1` is stopped but it appears to be non existent

I can introduce some null checks so you do not get exceptions but you would still not get the call stack. The bottom line issue seems to be that the debug adapter extension is returning a thread with id === 3.
Forwarding to @weinand as node debug adapter should always only have one thread and he might have more ideas what is the root cause

**Comment by weinand** [comment] 2016-12-20 08:01
@CodeCloak does your "C++ engine using v8" add support for multiple threads?

**Comment by CodeCloak** [comment] 2016-12-20 15:28
I can't give a definitive "yes" or "no" to that question, because I'm not a 100% sure where to look in our code to get that information. The information I do have leads me to believe yes but the person who would know for sure is on holiday for a week or two.

**Comment by CodeCloak** [comment] 2017-01-03 16:44
After talking with the person who I thought would know and showing him this thread he said the following:

We are using v8 in multiple threads and using v8 locks but he isn't sure that is what you meant by "added support for multiple threads"

**Comment by weinand** [comment] 2018-09-17 16:08
Seems to be fixed in recent versions.

**Closed by weinand** 2018-09-17 16:08 UTC
Labels: bug, debug, needs more info
