### ISSUE TITLE
vscode 1.54/1.55 do not work on red hat 7.5

### ISSUE THREAD

**Issue by nathanptackett** [microsoft/vscode#120941] opened 2021-04-09 15:14 UTC
When downloading version 1.55 and trying to run on red hat 7.5, it crashes. Reverting back to vscode 1.52 works. not sure if this is for all linux distros or just red hat.

**Comment by IllusionMH** [comment] 2021-04-09 16:06
/duplicate of #115784

New Electron versions don't support CentOS 7. See linked issue for details and probable workarounds

**Closed** 2021-04-09 16:06 UTC
Labels: *duplicate
