### ISSUE TITLE
Markdown preview does not always refresh

### ISSUE THREAD

**Issue by erhhung** [Microsoft/vscode#13280] opened 2016-10-06 06:11 UTC
- VSCode Version: 1.5.3
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Open new VSCode window
2. Open a project folder
3. Click on README.md
4. Both text and .md preview tabs open
5. Close .md text tab (preview still open)
6. Open another editor window (Sublime)
7. Open the same project folder
8. Open README.md, make changes and save
9. Click on README.md in VSCode Explorer
10. Text tab shows modified content
11. .md preview is now stale
12. Close preview tab so only text tab visible
13. Click on Open Preview icon in upper right
14. .md preview still shows old content
15. Pressing Shift-Cmd-V same thing
16. (Both text and preview tabs still open)
17. Right-click on README.md in Explorer pane and choose Open Preview
18. Focus changes to preview tab, but still stale
19. Close .md preview tab
20. Do step 18 again, and preview shows refreshed content
21. Make more changes in the other editor and save
22. Now it doesn't matter what I do (tried any/all steps above), .md is not refreshing
23. But text tab always refreshes
24. **OK, found a pattern: the .md preview will only reliably refresh if its text tab is open AND in focus** - when making external changes, the text tab auto-updates, and THEN switching to the preview tab shows updated content
25. If .md preview tab is in focus and external change is made, clicking back to the text tab causes a **weird flicker with the focus staying on the preview tab**. Click the text tab again to see updated content, but the refresh problem remains

**Comment by mjbvz** [comment] 2017-02-07 20:54
Closing as duplicate of #5687

**Closed by mjbvz** 2017-02-07 20:54 UTC
Labels: duplicate, markdown
