### ISSUE TITLE
Wrong auto-indentation in typescript

### ISSUE THREAD

**Issue by rzvc** [microsoft/vscode#209802] opened 2024-04-08 06:59 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:
```ts
if (true)<enter>
	{<enter>
	}
```
This seems to happen on `for` and `while` as well. In other languages auto-indentation doesn't happen after the first `<enter>` in the example. While it could be good as a feature, it would be great if on typing the opening bracket, it would automatically un-indent. Also, it seems like the kind of thing that needs a toggle, because it can backfire in multiple ways.

Another thing that I noticed was that the auto-indentation happens even if the `if` line is commented out.
```ts
// if (true)<enter>
	|<cursor ends up here>
```

This was not a problem in the previous version.

**Comment by StevenJohnston** [comment] 2024-04-11 18:59
I too have this issue

**Comment by AndrewStovell** [comment] 2024-04-14 00:41
+1 to also having this issue. Can confirm, If, Else If, For, While, and Arrow Functions affected. Functions & Switches are fine.
Have tried commenting out settings.json, and issue persists.

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by TheWyo** [comment] 2024-04-22 11:57
Seems to be a re-occurrence of #30933 from quite some time ago.

**Comment by 1564047446** [comment] 2024-04-30 08:14
yeah, the latest version must auto error. emmmm, how long fix the bug

**Comment by Jemt** [comment] 2024-05-05 20:57
I wonder why this bug report does not have a billion upvotes. I have the same problem, and it basically renders VSCode useless. I constantly have to fix my code manually. I tried disabling all my extensions, but to no eval.

This is what I experience in JS files:

<img width="183" alt="image" src="https://github.com/microsoft/vscode/assets/1258714/4b1153fb-aa16-4cae-80c4-8a94e711a2a5">

Pressing ENTER after control flows such as `if` or `for` indents the cursor like shown above, where it previously did not.

In this example I pressed ENTER after the `function()` declaration on line 5 which caused incorrect indentation in the opposite direction.

Things seems to work fine for PHP files.

**Comment by FlowIT-JIT** [comment] 2024-05-06 06:22
Probably a duplicate of https://github.com/microsoft/vscode/issues/209805
Although I'm not sure this covers the issue with the forEach(..) construct.

**Comment by FlowIT-JIT** [comment] 2024-05-06 06:45
Switching `Auto indent` to "advanced" makes VSCode usable again:

![image](https://github.com/microsoft/vscode/assets/10479064/3a2b66f8-ce11-4f17-ad57-1543d2b631b4)

But it's beyond me that 1.88 even shipped with these changes. Completely destroyed the editing experience.

**Comment by FlowIT-JIT** [comment] 2024-05-06 08:25
This is the behaviour with "Auto indent" set to Full:

![VSCodeindentationbugs-ezgif com-video-to-gif-converter](https://github.com/microsoft/vscode/assets/10479064/e49ad8d3-1a12-42c9-9ddd-6370cc656414)

I constantly have to fix the code.

**Comment by ssigwart** [comment] 2024-05-11 04:41
For those that don't like the new behavior, I created the `ssigwart.javascript-typescript-language-configuration` extension that will remove the auto-indenting after `if`, `for`, and `while` in JavaScript and Typescript.

**Comment by aiday-mar** [comment] 2024-05-13 09:03
Hi everyone thank you for expressing your concern. This change has come in as a result of the following issue with 43 upvotes (https://github.com/microsoft/vscode/issues/43244) which precisely asked for indentation to be added after a braceless if/for/while statement. I will explore the idea adding indentation by default, and then removing it when { is typed.

**Comment by photonstorm** [comment] 2024-05-21 13:57
Please, for the love of all things sane, revert this terrible decision. It makes VSCode an absolute nightmare to work with.

**Comment by photonstorm** [comment] 2024-05-21 14:08
If you hate this change as much as I do, this works:

Uninstall the current broken version and revert to v1.87 https://code.visualstudio.com/updates/v1_87

Then go to File > Preferences > Settings, search for update, and change the automatic update setting to 'none' to prevent the broken version from being downloaded again.

Obviously, this is less than ideal - but I'd much rather stay fixed on this slightly older release than deal with the pain of fixing every single time I use an `if` or `for` statement.

**Comment by ZLam** [comment] 2024-05-30 07:10
fix it ！

**Comment by photonstorm** [comment] 2024-06-02 21:41
> fix it ！

Don't hold your breath. I've a feeling I'm going to be stuck on version 1.87 for at least a year, or more, because of this insane change. An _editor_ should never, ever, dictate a coding style, which is exactly what this change does. The only exception is if the language demands such structure, such as Python. In all other cases, it should be entirely up to the user.

**Closed** 2024-06-20 09:14 UTC
Labels: typescript, javascript, editor-autoindent

**Comment by photonstorm** [comment] 2024-06-20 12:10
So happy to see this fixed. How do we easily track when it enters a live release version? As I'm pinned to v1.87 and don't want to turn automatic updates on again until I know this has landed.

**Comment by aiday-mar** [comment] 2024-06-20 13:38
The update that has been merged today will be in tomorrow's Insiders release

**Comment by aiday-mar** [comment] 2024-06-24 07:26
To verify: 

- Open a TypeScript or JavaScript file
- Type `if(<some code>)` in the file
- Type `Enter`, verify the next line is indented
- Type an opening curly brace `{`, verify a second closing curly brace is added and we have:

```ts
if(<some code>)
{}
```

- Press `Enter` from within the curly braces, verify we have:

```ts
if(<some code>)
{
....
}
```

Here the dots represent the spaces.

**Comment by aiday-mar** [comment] 2024-06-24 07:33
Hi @FlowIT-JIT yes these should be tabs if you configured tabs for the file
