### ISSUE TITLE
Find and replace "line break"

### ISSUE THREAD

**Issue by brusMX** [Microsoft/vscode#1114] opened 2015-12-08 23:38 UTC
In other IDEs I used to simple copy a line break and paste it to the find text box. Then I could replace it with some other string.

I tried to do it with regex find using "\n" or "\r" and I had no luck either. 

This is very helpful when creating db queries or csv files on the fly by replacing line breaks with strings like: '");' or whenever you detect  some char (like >) you can replace it with a breakline. 

Thanks a lot!

**Comment by Tyriar** [comment] 2015-12-09 02:58
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Comment by egamma** [comment] 2015-12-09 07:42
@Tyriar thanks - closing as duplicate of #313

**Closed by egamma** 2015-12-09 07:42 UTC
