### ISSUE TITLE
Menus broken most of the time, making VS Code nearly unusable

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode#165704] opened 2022-11-07 13:23 UTC
Steps to Reproduce:

1.  Install VS Code from FlatHub with no extensions, just as-is
2. Don't maximize VS Code since unmaximized it seems to make it more likely
3. Try to use menus by clicking menu bar:

[vscodebug.webm](https://user-images.githubusercontent.com/64124388/200320882-1e29bc61-ef14-434f-b82e-1a82bffff204.webm)

**VS Code version:** 1.73.0

**Installed via:** flatpak/flathub

**System:** Fedora Linux 36 on x64 laptop

**Desktop** GNOME 3 (Wayland session)

**Comment by cruxic** [comment] 2022-11-18 16:44
This is also happening to me sporadically. Ubuntu Mate 22.04.

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic
Sandboxed: No

**Comment by rzhao271** [comment] 2022-12-05 23:26
I believe this is a duplicate of #159852

**Closed by rzhao271** 2022-12-05 23:26 UTC
