### ISSUE TITLE
Go to file (CTRL +P) works ugly since 1.44

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#96034] opened 2020-04-24 06:32 UTC
Issue Type: <b>Bug</b>

1) open android sources workspace
2) CTRL+p 
3) enter: development/tools/bugreport/Android.bp
4) nothing found!
5) strip path to : bugreport/Android.bp
6)  file is found.

It looks like since 1.44 vscode can only search pattern:
dir/file
but cannot search
dir/dir/file

see attached video:\
![quick_search](https://user-images.githubusercontent.com/801951/80181909-6c213080-860e-11ea-98bf-34565cde60d3.gif)

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.22GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2Bvdybala.some_server.ru/nvm/work/prod_android_repo/prod_android_repo.code-workspace|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vdybala.some_server.ru|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 947)|
|Memory (System)|31.30GB (10.26GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-docker|ms-|1.1.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-todo-highlight|way|1.0.4
cpptools|ms-|0.27.0
Go|ms-|0.14.1

</details>

**Comment by back2war** [comment] 2020-04-24 09:55
I'm experiencing the same bug. It occurs only for remote-wsl. For local workspaces Quick Open works as expected.

**Comment by dibalavs** [comment] 2020-04-24 09:56
I use remote-ssh.

**Comment by bpasero** [comment] 2020-04-24 12:14
I think this is a duplicate of https://github.com/microsoft/vscode/issues/94871. To verify, does it reproduce in insiders?

**Comment by back2war** [comment] 2020-04-24 12:35
Checked in insiders - no issue, works as expected.

**Comment by bpasero** [comment] 2020-04-25 05:46
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2020-04-25 05:46 UTC
