### ISSUE TITLE
Unable to update through apt.

### ISSUE THREAD

**Issue by ashwinee2591** [microsoft/vscode#86936] opened 2019-12-13 15:10 UTC
- VSCode Version: 1.40.2
- OS Version: Linux Mint 19.2 LTS

Err:3 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages                                                                                             
  File has unexpected size (156354 != 156065). Mirror sync in progress? [IP: 13.76.190.189 80]
  Hashes of expected file:
   - Filesize:156065 [weak]
   - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
   - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
   - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
   - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
  Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
Hit:4 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                              
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                 
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                       
Ign:7 http://packages.linuxmint.com tina InRelease                                                                                                                    
Hit:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                           
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                                                          
Hit:10 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu bionic InRelease                                          
Hit:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                  
Hit:12 http://packages.linuxmint.com tina Release                                              
Hit:15 http://repo.steampowered.com/steam precise InRelease              
Reading package lists... Done 
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (156354 != 156065). Mirror sync in progress? [IP: 13.76.190.189 80]
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by gzmorell** [comment] 2019-12-13 15:24
Same in Debian:
0

linux deb repo seems to contain some error: This is whate I get from apt update:

    Get:14 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [156 kB] Err:14 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages File has unexpected size (156354 != 156065). Mirror sync in progress? [IP: 13.74.252.37 80] Hashes of expected file: - Filesize:156065 [weak] - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0 - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak] - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak] Release file created at: Thu, 12 Dec 2019 19:59:19 +0000 Reading package lists... Done E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2 File has unexpected size (156354 != 156065). Mirror sync in progress? [IP: 13.74.252.37 80] Hashes of expected file: - Filesize:156065 [weak] - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0 - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak] - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]

The "https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2" real file size is: 156354 the file "https://packages.microsoft.com/repos/vscode/dists/stable/InRelease" tells that the size is 156065.

Furthermore:

gpg --verify Release.gpg Release

**Comment by ksze** [comment] 2019-12-13 15:31
Duplicate of #86858

**Closed** 2019-12-13 16:09 UTC
Labels: *duplicate, install-update
