### ISSUE TITLE
Is there a shortcut to collapse all multiline comments?

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#35533] opened 2017-10-03 16:32 UTC
I like to leave detailed comments of wth is going inside this function which has 50 lines.
I have choice of making 30 functions or writing 50 lines, so more than not I pick 50 lines.

But 12 lines comments are draining.

I collapse them, is there a way to collapse all multiline comments by pressing shortcut.

Also another plus would be to hold key like (Ctrl/Cmd) and hovering over multiline comment would show icon, when I click it it'd toggle between collapsed and expanded state. That'd be too cool

I know i can manually collapse them by pressing - sign on the left

**Comment by aeschli** [comment] 2017-10-04 13:56
duplicate of #11524

**Closed by aeschli** 2017-10-04 13:56 UTC
Labels: editor, editor-folding
