### ISSUE TITLE
ctrl + p file search will jump to file after ctrl release when current file is a gif

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode#82734] opened 2019-10-16 23:27 UTC
Issue Type: <b>Bug</b>

1. Add a gif to the workspace.
![loader](https://user-images.githubusercontent.com/5885195/66966207-29632680-f0c8-11e9-8927-2af5553fd7a0.gif)

2. Open a non gif file in the workspace.
3. `ctrl + p` , search for the gif and open the gif
4. `ctrl + p` again and search for another file while the gif is the active editor. When releasing  `ctrl` the editor will jump to the previous file and typed text will instead get inserted into the newly focused file instead of the file search bar.

Step 4 may not reproduce the issue the first time but repeat from step 3 and it happens on subsequent attempts.

![vscode_file_search](https://user-images.githubusercontent.com/5885195/66966378-c0c87980-f0c8-11e9-854a-8ad571efc7b3.gif)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.68GB (0.33GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
vsc-material-theme|Equ|30.0.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.8.1
csharp|ms-|1.21.5
vetur|oct|0.22.4
ayu|tea|0.18.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-10-25 01:36
The root cause of this is the we think that ctrl+p is being triggered twice here. Same root problem as #83231

**Comment by mjbvz** [comment] 2020-04-17 23:06
Actually, duplicate of #88284

Should be fixed in next insiders build

**Closed by mjbvz** 2020-04-17 23:06 UTC
Labels: bug, linux, webview
