### ISSUE TITLE
Output from process running in Terminal appears in Console

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#46414] opened 2018-03-23 12:47 UTC
Issue Type: <b>Bug</b>

- In my projects launch configuration, I set `"console": "integratedTerminal`.
- In my workspace, I have a compound that starts that launch configuraiton.
- When the process outputs, the output appears in both the dedicated terminal window *and* the debug console.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4014)|
|Memory (System)|15.90GB (4.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe api-testing/api-testing.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.7
EditorConfig|Edi|0.12.1
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-lebab|mrm|2.5.0
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.2.1

(1 theme extensions excluded)

</details>
Reproduces only with extensions

**Comment by oliversalzburg** [comment] 2018-03-23 12:54
Seems like this happens when generating output with `console.log`. When writing to an explicit stream, I get proper separation.

**Comment by isidorn** [comment] 2018-03-26 09:37
@oliversalzburg what node version do you have? Or does this happen when you use the chrome debugger?

**Comment by oliversalzburg** [comment] 2018-03-26 12:59
@isidorn 8.9.0 currently. And, yes, this is Node, Chrome is not involved.

**Comment by roblourens** [comment] 2018-03-26 17:36
This is by design, when attached to a process, any output that comes over the debug port is written to the console. Is that a problem?

> Seems like this happens when generating output with console.log.

That's true, writing directly to the output stream doesn't send it through the debug port.

**Comment by oliversalzburg** [comment] 2018-03-27 11:46
@roblourens It's unexpected in the configuration I set up.

I run 4 processes (the core processes of our platform) through a launch configuration compound and I want to (be able to) debug all of them, thus I run them through the Node debugger.

I also set these up to use a discrete terminal for each process to keep each output isolated.

However, the output of all processes is merged into the debug console, which is unfortunate at the very least. This is additionally complicated by the fact that I run a fifth process in the same session which I actually actively want to work on. I expect that process to output to the debug console.

So the whole output is just a big mess that is extremely hard to work with. https://stackoverflow.com/questions/49449739/how-to-control-terminal-names-in-debugging-compound also plays into this overall issue.

**Comment by roblourens** [comment] 2018-03-27 20:41
I'm trying to decide, is this just a problem of differentiating output from different processes in the debug console? @isidorn is there any other issue for filtering/labeling output from different processes?

Or, is it just about what we do with output from a process running in the terminal? It would make sense to not send output to the debug console in that case. I still do because I figure that it shouldn't hurt (and if it's too confusing, then it should be fixed, see above). But keeping the output out of the debug console in this case would be a good workaround.

**Comment by oliversalzburg** [comment] 2018-03-28 08:39
When I was reading through #10546 I really liked the mockup from https://github.com/Microsoft/vscode/issues/10546#issuecomment-370917304.

From my point of view, having multiple debug console tabs (one for each running process) seems like a very attractive solution. But only if they aren't solved through the dropdown approach from the terminals, which does not have a good feel to it.

My approach utilizing terminal windows was just me trying to work with what I see as my options.

**Comment by isidorn** [comment] 2018-03-28 09:05
@roblourens there might be an issue that the debug console is centrelized and not per process. But feel free to create a new one.

**Comment by roblourens** [comment] 2018-03-28 15:55
Opened a new issue. I'll change the debug adapter to not send output to the console when the process is started in the terminal. I'll do that at the beginning of April so we can see whether anyone complains.

**Comment by weinand** [comment] 2018-04-04 09:16
@roblourens yes, that's a good approach.

**Closed** 2018-04-04 23:45 UTC
Labels: bug, debug

**Comment by weinand** [comment] 2018-04-23 14:09
@roblourens this change of behaviour should be mentioned in the release notes.
