### ISSUE TITLE
Folder name is always ALL CAPS in Explorer Tab

### ISSUE THREAD

**Issue by kmurray24** [microsoft/vscode#191160] opened 2023-08-24 03:14 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.81.1
- OS Version: 10.0.22621 Build 22621

Steps to Reproduce:

1. Open Folder with name in lower case
2. Observe Folder name as top level with ALL CAPs.
![VS Code Folder name ALL CAPS](https://github.com/microsoft/vscode/assets/13936320/377063cb-6286-498d-9be2-fb60bfdfdbbe)
![Windows Folder name lowercase](https://github.com/microsoft/vscode/assets/13936320/bb619c65-215b-4344-83d4-62d794380cb3)

**Comment by gjsjohnmurray** [comment] 2023-08-24 03:26
I think this is caused by a long - established VS Code UI convention. View headers are all displayed this way.

When I first started using VS Code this bugged me, as using ALL CAPS is known to reduce the speed with which a reader "gets" what is written. But I doubt it will change unless an accessibility option gets added to turn this off.

Pinging @daviddossett

**Comment by kmurray24** [comment] 2023-08-24 03:37
OK, Thanks for the info.  I'll just continue to let it bug me for a really long time everyday!  ;)
I am sure it has to bug other developers with more clout then myself as a newcomer. 
Anyone else think this is wrong?   Thanks for the info John.  Greatly appreciated! > Ken

**Comment by gjsjohnmurray** [comment] 2023-08-24 03:58
See also https://github.com/microsoft/vscode/issues/47213#issuecomment-378859498

**Comment by kmurray24** [comment] 2023-08-24 04:06
Well,  #47213 (comment)<https://github.com/microsoft/vscode/issues/47213#issuecomment-378859498> is a quick shutdown to all. Would think the option to show true name should be there.
It actually confused me a bit at first and thought I had an older version, or I accidentally named it wrong, or would have to reference it that way in CAPS.
I think it would be more correct to show it the way it is really named, but I'll let it go if the powers to be say it's better to leave the legacy...
Thanks for the help and input.  Should I close this or leave it open for more comments?

Ken Murray
603.759.4118 mobile
________________________________

**Comment by gjsjohnmurray** [comment] 2023-08-24 04:26
Note to self - could https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps be useful for all view titles, specifically the small-caps or petite-caps option?

**Comment by aa956** [comment] 2023-12-27 14:21
I just imagine if this convention would be used everywhere, including all of Windows documentation for consistency sake :)

> To open your actual desktop folder, navigate to
> `C:\USERS\FIRSTNAME.LASTNAME\ONEDRIVE - COMPANY NAME EUROPE GMBH\DESKTOP`

Any way to change it to correct folder name? Some extension?

**Comment by gjsjohnmurray** [comment] 2024-04-15 11:07
The intro at https://en.wikipedia.org/wiki/All_caps puts it like this:

![image](https://github.com/microsoft/vscode/assets/6726799/f00b8eb8-96fe-4666-9fd7-155563edf083)

The first link is to https://en.wikipedia.org/wiki/Typography#Readability_and_legibility

**Comment by kmurray24** [comment] 2024-04-16 11:55
CAPS works as the actual title of something.  
e.g. 
I’m going to see 
“Napoleon Dynamite” 
not
“NAPOLEON DYNAMITE”

**Comment by lramos15** [comment] 2024-12-16 16:11
We have no plans to change this since it's just the VS Code UI paradaigm. So will close as wont fix for now as I have not heard any other users requesting this as wel. You can see in the no folder case we have `NO FOLDER OPEN`

<img width="242" alt="Image" src="https://github.com/user-attachments/assets/1eb23eaa-d4ee-48b2-938a-eba1d57d7149" />

**Closed by lramos15** 2024-12-16 16:11 UTC
Labels: file-explorer, under-discussion

**Comment by lramos15** [comment] 2024-12-16 16:52
> Personally I'm sad to see this closed (see my contributions to the issue), but figure I was probably always on a losing wicket (a term that maybe only make sense to residents of cricketing nations).

Understood, but your points seem to indicate that even view titles should be changed not just folder names at the top of the explorer. Is that correct?

**Comment by gjsjohnmurray** [comment] 2024-12-16 17:46
@lramos15 yes I think the view titles should also change.
