### ISSUE TITLE
VSCode does not resolve path for .vue files inside a .js file

### ISSUE THREAD

**Issue by RilRil** [microsoft/vscode#100581] opened 2020-06-19 13:43 UTC
- VSCode Version: 1.46.1
- OS Version: os x catalina

Steps to Reproduce:

1. install Vue CLI and create a new project
2. Go to main.js
3. cmd + click on `"./App.vue"` at line 2
4. nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-06-19 19:34
Duplicate of https://github.com/microsoft/TypeScript/issues/15146

**Closed by mjbvz** 2020-06-19 19:34 UTC
Labels: new release
