### ISSUE TITLE
When showing the sidebar, keep focus in the editor

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46986] opened 2018-03-30 03:13 UTC
If I'm editing in an editor on a file, and I show the sidebar with Cmd+B, then focus is lost from the editor, so I can't continue typing code until I close the sidebar again.

Please instead keep focus on the editor, or add an option to do so.

**Comment by usernamehw** [comment] 2018-03-30 05:17
Duplicate of #46092

**Closed** 2018-03-30 06:53 UTC
