### ISSUE TITLE
Support command attribute on languages contribution

### ISSUE THREAD

**Issue by dschaefer** [Microsoft/vscode#71086] opened 2019-03-25 14:48 UTC
I know opening custom editors for non text files has been raised before but discussion seems to have stalled. Instead, I'll propose the start of a solution.

The example that brought this to the forefront again was the vscode-pdf extension. It's probably the best done that I've seen but is still a huge hack and you still get a pretty weird user experience.

It listens for onDidOpenTextDocument and if the document has the language id it added, i.e. "pdf", it closes the active editor (assuming I guess that the current document is in the active editor), and opens up it's custom editor that renders pdf files instead.

That is essentially the behavior we're looking for. But I can imagine it would be much cleaner if we were allowed to register a command id with the language that would be run when opening the text document that short circuits the hack needed in the extension.

That still leaves hooking up editor menu commands like undo and save, but at least we could get viewers like the PDF one working much more cleanly.

**Comment by jrieken** [comment] 2019-03-25 14:58
/duplicate of https://github.com/Microsoft/vscode/issues/12176

**Comment by jrieken** [comment] 2019-03-25 14:59
Closing as dupe of https://github.com/Microsoft/vscode/issues/12176. Adding a command to the languages is really not the right layer for this. This should be done somewhere in the opening world...

**Closed** 2019-03-25 14:58 UTC
Labels: *duplicate
