### ISSUE TITLE
Dull colors when using a color profile

### ISSUE THREAD

**Issue by newbrain** [Microsoft/vscode#69250] opened 2019-02-22 23:37 UTC
- VSCode Version: 1.31.1
- OS Version: Windows 10 1809 - 17763.316

Steps to Reproduce:

1. Set a color profile as default in "Color Management"
2. Open VS Code: All colors (regardless of theme) are muted.
![image](https://user-images.githubusercontent.com/17814222/53276750-cd92fa00-3700-11e9-9169-aad94a79710d.png)
![image](https://user-images.githubusercontent.com/17814222/53276839-3e3a1680-3701-11e9-8891-e6ec6296a783.png)
3. Exit VS Code.
4. Remove the color profile in "Color Management".
5. Open VS Code: Colors are normal.
![image](https://user-images.githubusercontent.com/17814222/53276796-0b901e00-3701-11e9-9815-43c182443e5f.png)
![image](https://user-images.githubusercontent.com/17814222/53276897-74779600-3701-11e9-8018-1ced1f00e958.png)

Does this issue occur when all extensions are disabled?: Yes

The visual effect is the same as reported in closed issue #34146
Oddly, the issue appears even when using the machine running VS Code through RDP.

Note also that the profile I'm using should make no color transformation (my display is calibrated with its internal LUT to sRGB, and that's the color space I'm using), I'm attaching it for reference.

[U2713H.zip](https://github.com/Microsoft/vscode/files/2896215/U2713H.zip)

**Comment by aeschli** [comment] 2019-02-27 08:11
duplicate of #65816

**Closed by aeschli** 2019-02-27 08:11 UTC
