### ISSUE TITLE
Markdown relative image is not shown in Preview on windows

### ISSUE THREAD

**Issue by davidgreen99** [microsoft/vscode#86017] opened 2019-12-03 09:26 UTC
- VSCode Version: 1.40.2
- OS Version: Windows 10 x64

This seems to be a regression. Previous versions of VSCode allowed relative images to preview. But it is no longer working.

This the same issue as closed and locked issue https://github.com/microsoft/vscode/issues/45155 (which I am unable to reopen or comment on).

1. For a folder structure:
images/
    cat.png
   doc.md

2. With doc.md:
![](images/cat.gif)

3. Open doc.md directly (don't open the folders)
4. Open preview

Bug: 
No image shown in preview.

**Comment by mjbvz** [comment] 2019-12-03 22:50
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Also, please include the source of the markdown file (as text)

**Comment by davidgreen99** [comment] 2019-12-04 10:14
It is NOT reproducible on Version: 1.41.0-insider (user setup).
It IS reproducible on Version: 1.40.2 (user setup) 
both on OS: Windows_NT x64 10.0.14393

1. I open the local folder containing my repo, containing images in the 'media' folder:

2. In markdown I reference an image like this:
![localized image](/en-us/federated-authentication-service/media/policy-definitions.png)

3. Preview in Version: 1.40.2 (user setup) only shows this:
![10-12-22](https://user-images.githubusercontent.com/31207225/70133836-ced55800-167e-11ea-89cc-68972e3012e5.png)

**Comment by mjbvz** [comment] 2019-12-04 23:42
Closing since it is fixed in insiders. The current insiders will be released as 1.41 sometime next week

**Closed by mjbvz** 2019-12-04 23:42 UTC
Labels: markdown, needs more info
