### ISSUE TITLE
 invalid marker service state

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#13026] opened 2016-09-29 17:45 UTC
Issue Id: <b>142f09d3-a83c-91d4-c461-dd8bd756e69f</b><br /><br />*Versions* <br />- 1.6.0-insider (9/28/2016 6:06:50 AM)<br />*Stack* <br />Error: invalid marker service state<br />[/vs/platform/markers/common/markerService.ts#L159:10](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/platform/markers/common/markerService.ts#L159:10)<br />[/vs/platform/markers/common/markerService.ts#L147:9 (changeOne)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/platform/markers/common/markerService.ts#L147:9 (changeOne))<br />[/vs/editor/common/services/modelServiceImpl.ts#L349:119 (remove)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L349:119 (remove))<br />    at Array.forEach (native)<br />[/vs/editor/common/services/modelServiceImpl.ts#L349:82 (forEach)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L349:82 (forEach))<br />[/vs/editor/common/services/modelServiceImpl.ts#L460:7 (_cleanUp)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L460:7 (_cleanUp))<br />[/vs/editor/common/services/modelServiceImpl.ts#L474:9 (_onModelDisposing)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L474:9 (_onModelDisposing))<br />[/vs/editor/common/services/modelServiceImpl.ts#L371:67 (_onModelEvents)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L371:67 (_onModelEvents))<br />[/vs/editor/common/services/modelServiceImpl.ts#L50:64 (eventsHandler)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/editor/common/services/modelServiceImpl.ts#L50:64 (eventsHandler))<br />[/vs/base/common/eventEmitter.ts#L303:9 (func)](https://github.com/microsoft/vscode/blob/c94c824db64a88bd4909da2e84e44316dbf8e8fb/src/vs/base/common/eventEmitter.ts#L303:9 (func))<br />

**Comment by ramya-rao-a** [comment] 2016-09-29 17:48
@jrieken related #12635 ?

This is currently seen in the insiders build dated 9/28 whereas your fix for #12635 went in on 9/26 ?

Un-minified callstack:

Error: invalid marker service state 
at e.changeOne (out/vs/workbench/workbench.main.js:63:6665) 
at e.remove (out/vs/workbench/workbench.main.js:63:6475) 
at out/vs/workbench/workbench.main.js:69:20925 
at Array.forEach (native) 
at e._cleanUp (out/vs/workbench/workbench.main.js:69:20881) 
at e._onModelDisposing (out/vs/workbench/workbench.main.js:69:22655) 
at e._onModelEvents (out/vs/workbench/workbench.main.js:69:22875) 
at out/vs/workbench/workbench.main.js:69:21270 
at out/vs/workbench/workbench.main.js:69:15310 
at o (out/vs/workbench/workbench.main.js:29:21441)

**Comment by jrieken** [comment] 2016-10-04 07:39
I'd say dupe of #12635

**Closed by jrieken** 2016-10-04 07:39 UTC
Labels: error-telemetry
