### ISSUE TITLE
git push doesn't work

### ISSUE THREAD

**Issue by dipanshparmar** [microsoft/vscode#137351] opened 2021-11-17 09:20 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: Pop OS 21.04

Steps to Reproduce:

1. Initialize a git repo
2. try to push the code. You will get the "No anonymous write access" error

Please note that **git push** works fine in Android Studio

**Comment by gjsjohnmurray** [comment] 2021-11-17 11:14
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Comment by dipanshparmar** [comment] 2021-11-24 11:41
@gjsjohnmurray Please reopen the issue if possible. This issue still persists for me in v1.62.3.

**Comment by gjsjohnmurray** [comment] 2021-11-24 11:52
> @gjsjohnmurray Please reopen the issue if possible. This issue still persists for me in v1.62.3.

Pinging @lszomoru

**Comment by lszomoru** [comment] 2021-11-24 15:09
Could you please ensure that after you have updated to `1.62.3` all windows are closed again, and restart VS Code? Thanks!

**Comment by dipanshparmar** [comment] 2021-11-24 15:17
> Could you please ensure that after you have updated to `1.62.3` all windows are closed again, and restart VS Code? Thanks!

Yeah! I can confirm that I restarted VS Code and the issue is still there.

**Comment by dipanshparmar** [comment] 2021-11-25 06:52
Hey, @gjsjohnmurray @lszomoru I'm not sure how but the git push seems to be working fine now. It asked me to log in again and after login, it is working fine.

**Closed** 2021-11-29 19:38 UTC
Labels: git, *duplicate
