### ISSUE TITLE
Support dynamic QuickPickItem items

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25140] opened 2017-04-21 12:43 UTC
In order to implement #21439, it would be great to have a `QuickPickItem` which is never filtered out no matter what the user types. Additionally, it would be aware of what the user has typed when selected.

Proposal 1
----------

```ts
export interface QuickPickItem {
  alwaysVisible?: boolean;
}

export interface QuickPickOptions {
  onDidPickItem?<T extends QuickPickItem>(item: T | string, input: string): any;
}
```

cc @jrieken

**Comment by jrieken** [comment] 2017-04-21 15:25
dupe of https://github.com/Microsoft/vscode/issues?q=is%3Aopen+label%3Aquick-pick+label%3Aapi

**Closed by jrieken** 2017-04-21 15:25 UTC
Labels: api, feature-request, quick-pick

**Comment by joaomoreno** [comment] 2017-04-24 06:36
Did you just flush my proposal down the toilet?

**Comment by jrieken** [comment] 2017-04-24 06:40
No. As I have told you this request has been made already a few time, so I wasn't expecting you to create yet another duplicate but use an existing, long-standing issue. For instance these: #21372, #15659, and #11468

**Comment by joaomoreno** [comment] 2017-04-24 06:51
All those requests, aside from not fully addressing my issue, bring considerable conceptual changes to the quick pick API. The proposal in this issue is an incremental change.

But I understand if you want to stop any incremental changes in favour of a better thought APIv2.
