### ISSUE TITLE
Show picker for multiple imports close to editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40414] opened 2017-12-18 06:05 UTC
Just noticed that we now seem to bring up the picker when deciding which import to pick when there are multiple:

![before](https://user-images.githubusercontent.com/900690/34092030-8f5b0432-e3c1-11e7-882c-343e05dec1a4.gif)

It took me a while to understand what was going on, because suddenly focus goes away from the editor while typing and moving into a UI component that is quite far away to the top. Imho we cannot do this from the picker but should show a menu directly where I am typing similar to quick fix:

![image](https://user-images.githubusercontent.com/900690/34092082-dda80176-e3c1-11e7-9c6b-b7729a8df8e8.png)

**Comment by mjbvz** [comment] 2017-12-18 18:50
Yes that would be better. Can extensions create these context menus currently?

**Comment by bpasero** [comment] 2017-12-19 05:34
@mjbvz I am not sure. I think we need to give this some priority though, removing focus from the editor while typing is imho not acceptable. So I suggest to not show the picker until extensions can do the context menu without loosing focus. I am getting very frustrated at this change.

**Comment by mjbvz** [comment] 2017-12-19 21:53
I believe that TS generally should choose the shortest import option automatically in many cases. @andy-ms Is that correct, and would it be expected in this case?

**Comment by andy-ms** [comment] 2017-12-19 21:57
We do that for completions but not for import fixes, where we add both as options (https://github.com/Microsoft/TypeScript#19724). We could change it to only return one import fix in that case, though, if you think it's too annoying to have to choose (and usually there's a clear correct answer).
There will still be cases where we return multiple import fixes though, such as if there are actually two different values with the same name in two different modules.

**Comment by mjbvz** [comment] 2017-12-19 22:03
@andy-ms This is for the auto-import completion case. Should multiple options be returned for those?

**Comment by andy-ms** [comment] 2017-12-19 22:10
No, we should be returning only one. Microsoft/TypeScript#20700 should fix that.

**Comment by cyrilletuzi** [comment] 2018-01-05 22:36
> There will still be cases where we return multiple import fixes though, such as if there are actually two different values with the same name in two different modules.

Yes, in Angular it happens quite often with common classes like `EventEmitter`.

Please take #41175 into account, because I'm not sure this issue is exactly the same : if I understand correctly the first use case, the problem is about an unique class with multiple paths possible, but there are also a lot of times when there really are two or more different classes from different modules. And in these cases, choice has to be made by the user (not automatically).

**Comment by mjbvz** [comment] 2018-01-05 22:42
@cyrilletuzi Ok, I misunderstood what you were referring to in #41175 .

In cases where the same symbol exists in multiple files, we show multiple suggestions in the completion list. The alternative ux, where you select the symbol name and them select where it should come from, results in a poor ux like in this issue

**Comment by mjbvz** [comment] 2018-01-19 06:42
Showing the multiple import options was actually a bug. Should be fixed in latest TS insiders build

**Closed by mjbvz** 2018-01-19 06:42 UTC
Labels: bug, javascript, upstream

**Comment by cyrilletuzi** [comment] 2018-01-19 11:33
@mjbvz Will this solve #41175 ? Your message seems to suggest it won't be the case. If not, please reopen it, and it should be a priority before next release, as it's now several months auto imports are here and are still messing up more than helping.

**Comment by bpasero** [comment] 2018-01-30 14:45
I am not seeing this picker anymore.
