### ISSUE TITLE
Git - "Git: Unstage Selected Range" does not revert "Git: Stage Selected Range" on the same range

### ISSUE THREAD

**Issue by SimonTheLeg** [microsoft/vscode#156748] opened 2022-07-31 12:25 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Darwin x64 21.6.0
- Git Version: 2.37.1

Steps to Reproduce:

1. Prepare a simple git repo with a file and start VSCode with no extensions
```sh
mkdir test
cd test
git init
echo -e "line 1" > file
git add file
git commit -m "commit"
echo -e "line 2\n\nline 4" >> file
code --disable-extensions .
```
2. Select line 2 like so
![image](https://user-images.githubusercontent.com/20774623/182025859-abdb17bd-7b9f-434c-aeed-fe527c890169.png)

3. Run "Git: Stage Selected Ranges". Everything should look fine, the range is being staged, like so
![image](https://user-images.githubusercontent.com/20774623/182025893-d0c86381-0e1a-44e6-be5c-6a8bc968380f.png)

4. With the same selection (pic), run "Git: Unstage Selected Ranges"
![image](https://user-images.githubusercontent.com/20774623/182025975-08a7289c-8503-4b4a-ba42-fdad5f777ae8.png)

5. The selection is not being unstaged, everything stays as before. I would have expected that the selection is being unstaged
![image](https://user-images.githubusercontent.com/20774623/182026162-486203dd-f023-4a3e-b399-5d23efb01ad1.png)

Additional Notes:
This is similar to #120928, but not exactly the same. Because in my case the "Stage Selected Ranges" does work outside of the diff view, just the "Unstaging" does not. Therefore I decided to open a separate issue.

**Comment by lszomoru** [comment] 2022-12-19 10:47
@SimonTheLeg, thank you very much for the detailed repro steps. I have looked into this and while I do agree with you that the experience is not ideal, looking at the code, this seems to be the intended behaviour. The "Stage/Unstage Selected Ranges" commands are always present in the command palette but there are several conditions that have to be fulfilled in order for the command to execute (ex: there has to be an opened document, there has to be a selection, the selection has to contain changes, etc.). If any of these conditions are unmet, the command will not execute. In the case of the "Unstage Selected Ranges", the selection has to be made on the right side of the diff editor (Index), and the selection has to contain changes.

There are couple of things that we could to in order to avoid the confusion: 
1) Hide the command for obvious cases (ex: there is no document opened, no selection)
2) Display an information notification for other cases (ex: selection does not contain changes)

@joaomoreno, what are your thoughts?

**Comment by SampsonCrowley** [comment] 2023-02-06 19:54
@Iszomorou those sound like massive limitations. I'm coming over from atom, since now it's sunset... :cry: and I could open a single _combined_ diff view and unstage _or_ stage _any_ line I wanted by selecting it, right clicking and selecting "stage/unstage selected" it was a hugely useful workflow and not being able to _undelete_ a section that has been removed because you can only stage/unstage on the "right" side is, to put it frankly, dumb. it's completely unintuitive to anybody coming from a another IDE where things "just work(tm)"

**Comment by lszomoru** [comment] 2024-12-20 15:26
Closing as duplicate of [#96850](https://github.com/microsoft/vscode/issues/96850)

**Closed by lszomoru** 2024-12-20 15:26 UTC
Labels: bug, git
