### ISSUE TITLE
Include Actual 3-way Merging in the 3-way Merge Editor

### ISSUE THREAD

**Issue by enjibby** [microsoft/vscode#159821] opened 2022-09-02 00:30 UTC
I have long-used `git config --global merge.conflictStyle diff3` as an excellent way to see the "motivation" behind each side of a conflict. This includes a copy of the original code before either of the changes were made to make the changes more obvious.

![image](https://user-images.githubusercontent.com/936564/188033979-73cf334f-a126-4c7f-b84e-cc55f118f0df.png)

When the new Git Merge Editor was unexpectedly turned on by default, I lost the ability to see this "parent of..." section until I eventually found a way to return to the old conflict resolution view that I had grown to rely on.

If git is set to `merge.conflictStyle diff3` and an additional setting in vscode is enabled, could we please have either:

1. some sort of highlighting that shows us how each side of the merge differs from the "parent of..." instead of each other?
2. a 4th pane showing the "parent of..." view?

**Comment by yume-chan** [comment] 2022-09-02 04:41
Duplicate of #155277

**Closed** 2022-09-02 06:45 UTC
Labels: *duplicate
