### ISSUE TITLE
Feature Request - Git option to disable auto stage

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [Microsoft/vscode#26185] opened 2017-05-08 05:39 UTC
Would love to have an option to disable git from auto staging and committing all files incase a file was not staged in GUI. I have run into this, a couple of times when I forget to stage one file and all the unstaged changes get committed which is kind of annoying.

It would be a nice little quality of life improvement feature to have in settings

**Comment by staffann** [comment] 2017-05-17 07:31
+1
The autostaging is a bit dangerous since it increases the risk of committing files unintentionally, including files with sensitive information or big files that we have to revise the git history to get rid of. An option to disable it would be very useful.

**Comment by ouchxp** [comment] 2017-05-18 02:00
+1
Sometime I would like to leave some temporarily used file untracked. The ability to disable it could be very helpful.

**Comment by huanglw** [comment] 2018-03-27 10:29
+1

**Comment by luav** [comment] 2018-05-01 12:36
For me the main problem with VSCode "auto staging" is that it differs from `git commit -am` and stages new files besides the modified, which is really annoying.

**Comment by joaomoreno** [comment] 2018-09-18 13:03
The setting is `git.enableSmartCommit`.

**Comment by techniq** [comment] 2018-09-18 15:42
@joaomoreno I do not believe this setting is for the auto staging issue.  I have this disabled, but still see the auto-staging occurring.

![image](https://user-images.githubusercontent.com/177476/45699359-cb1beb00-bb37-11e8-8b57-f6608a77ccf6.png)

**Comment by joaomoreno** [comment] 2018-09-19 08:03
If I disable the setting and try to commit, I get this:

![screenshot from 2018-09-19 10-02-38](https://user-images.githubusercontent.com/22350/45739377-2b239780-bbf3-11e8-842c-7f0450f71e61.png)

Do you get it too?

**Comment by techniq** [comment] 2018-09-19 12:38
@joaomoreno I do, but the issue is some files get staged automatically (regardless of this setting).  I think this mostly has to do with new files.  For example, I just created `test.js` and it's already staged (and I still have the smart commit unchecked).

![image](https://user-images.githubusercontent.com/177476/45753602-5902df00-bbe7-11e8-8483-6dc79fab0720.png)

**Comment by joaomoreno** [comment] 2018-09-20 07:39
>  For example, I just created test.js and it's already staged

Are you sure Code did that? Can you reproduce that with `--disable-extensions`?

**Comment by techniq** [comment] 2018-09-20 12:14
@joaomoreno hmm, I typically have VSCode, Visual Studio for Mac, and SourceTree open for the same project which could all culprits.

I just closed everything down and added a new file via the command line, and `git status` shows the file already staged.  I have a very simple `.gitconfig`, but at this point, I'm not sure it's VSCode (to be honest I wasn't sure what the culprit was, but when I saw this issue, I thought it was related to what I was seeing).

Thanks for your time.

**Comment by techniq** [comment] 2018-09-20 12:28
@joaomoreno Actually, while I thought I had shut down all 3, Visual Studio for Mac was still open, and closing it stopped the auto-staging, so I think I found, my culprit.

---

While there isn't a setting in Visual Studio for Mac, disabling version control globally resolved my issue.  Sorry for the noise :)

![image](https://user-images.githubusercontent.com/177476/45818220-1573a800-bcaf-11e8-9c3c-68808ce6833f.png)

**Closed** 2018-09-20 12:48 UTC
Labels: feature-request, git
