### ISSUE TITLE
Insiders token syntax hilighting on functions declared as var

### ISSUE THREAD

**Issue by Aetherall** [microsoft/vscode#89782] opened 2020-01-31 13:09 UTC
Version: 1.42.0-insider
Commit: 9e8c4c247a779cdd1f4f53db963bc6124a28ac2f
Date: 2020-01-30T08:43:06.481Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic

Steps to Reproduce:

1. Open some jest test files

What is wrong :
Before updating, the `describe` `it` `beforeEach` etc was yellow, now it is the same colors as variables.
It only takes the wrong colors after the typescript features are initialized

in jest.d.ts, they are first declared as var at the top of the file

![image](https://user-images.githubusercontent.com/13298494/73541553-09ffc780-4433-11ea-9b1f-9ca93b749090.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-02-04 15:44
duplicate of #89337

**Closed by aeschli** 2020-02-04 15:44 UTC
