### ISSUE TITLE
Disable multiple selection in tags

### ISSUE THREAD

**Issue by TicTak21** [microsoft/vscode#111095] opened 2020-11-21 13:33 UTC
- VSCode Version: 1.52.0-insider
- Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
- Date: 2020-11-20T07:35:38.417Z (1 day ago)
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: MacOS Darwin x64 19.6.0

After the last few updates I noticed a strange problem/bug. 

Steps to Reproduce(screenshots below):

1.  Select any tag
2. Change selected tag(they will turn red)
3. All tags with similar name will changes

1, 2)
<img width="701" alt="Screenshot 2020-11-21 at 15 26 52" src="https://user-images.githubusercontent.com/44474697/99878440-fca80980-2c0d-11eb-8571-f7ffb808649c.png">

3)
<img width="701" alt="Screenshot 2020-11-21 at 15 27 21" src="https://user-images.githubusercontent.com/44474697/99878453-0df11600-2c0e-11eb-8dee-3d202bc3e757.png">

Expected behaviour: 

Only selected tag and closing tag will be renamed. ONLY <Container></Container> without next tag.

Does this issue occur when all extensions are disabled?: Yes

How can I disable/fix this issue. Its very annoying when all tags with similar name will be renamed. 
Maybe it related to [this issue](https://github.com/microsoft/vscode/issues/110983)? #110983

**Comment by aeschli** [comment] 2020-11-23 07:47
That's in a TypeScript / JavaScript React, right?

**Comment by TicTak21** [comment] 2020-11-23 08:01
Yes. 
Typescript + React.

**Comment by jrieken** [comment] 2020-11-24 07:59
Please share the file you are seeing this with

**Comment by TicTak21** [comment] 2020-11-24 08:05
[Header.tsx.zip](https://github.com/microsoft/vscode/files/5588273/Header.tsx.zip)

**Comment by jrieken** [comment] 2020-11-24 08:06
fyi - just disable `onTypeRename` (for TS only) and this stops

**Comment by jrieken** [comment] 2020-11-24 08:08
fyi @mjbvz tsx/jsx tag rename seems to be (partially) working as tsserver reports some of them as const

**Comment by TicTak21** [comment] 2020-11-24 08:14
```
"[typescriptreact]": {
    "editor.renameOnType": false
  },
```
work for me

**Comment by jrieken** [comment] 2020-11-24 09:25
Closing this as the feature works as designed. Tho it might be unexpected in some cases...

**Closed by jrieken** 2020-11-24 09:25 UTC
Labels: needs more info
