### ISSUE TITLE
Ctl+Shift+L => crash/no longer responder on 100MB text file.

### ISSUE THREAD

**Issue by chetratep** [Microsoft/vscode#47656] opened 2018-04-11 13:00 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by chetratep** [comment] 2018-04-12 06:00
It supposes to trigger select all occurrences in the current file, but instead, it makes vs code windows not responding and then I need to reopen or report the program.

**Comment by chetratep** [comment] 2018-04-13 09:35
It error both when I try to select either a few or more occurrent. Replacing also cause this error. it is not different.

**Comment by alexandrudima** [comment] 2018-04-13 13:44
@chetratep Can you provide us with the file in question or otherwise a very similar file or otherwise with a script to generate such a file that causes the crash ?

**Comment by alexandrudima** [comment] 2018-04-17 23:01
Pushed a change via 605ed53 where the number of cursors is limited to 10k and a message is shown when this happens.

Duplicate of #28121

**Closed by alexandrudima** 2018-04-17 23:01 UTC
Labels: needs more info

**Comment by chetratep** [comment] 2018-04-18 00:46
`for($i = 0; $i < 10; $i++){
	open(my $fl,">","./test_data_".$i.".csv");
	$factor = $i * 10000000;
	$tmp_max = 11351100;
	for($ind=($factor+1); $ind<($tmp_max+$factor);$ind++){
	  print $fl $ind.",\n";

	}

	close $fl;
}`
Here is how to generate the data. No message is displayed. It not repsonding and then a pop window to close or reopen appear. The replace function also cause this error too.
