### ISSUE TITLE
Add provision to apply functions to variables within snippets

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#17395] opened 2016-12-16 14:42 UTC
- VSCode Version:

Version 1.9.0-insider
Commit 32222e2eefc7a0afe9a1a0ecb4794119efd9bc81
Date 2016-12-16T07:18:07.856Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

Currently snippets does not have any way to apply functions to the variable being edited.

For eg., if the user selects `ng2-component` template using [this](https://github.com/johnpapa/vscode-angular2-snippets) plugin, user needs to enter the same name in multiple places

1. in lowercase for the selector name
2. in Camelcase for the class name

If vscode supports applying functions to the template variables names, the extension developer can write functions to update the rest of the template using this the text captured within this variable

**Comment by unional** [comment] 2016-12-17 06:18
Besides function, I always want to use `date` string.
Should it be a separate request?

**Comment by thekalinga** [comment] 2016-12-17 10:23
If you have ability to write code, its trivial to get date.

This is the holy grail.

**Comment by jrieken** [comment] 2017-01-27 10:29
closing this as dupe of #6920

**Closed by jrieken** 2017-01-27 10:29 UTC
Labels: feature-request, snippets
