### ISSUE TITLE
Live Server: Feature request

### ISSUE THREAD

**Issue by ModernWebService** [Microsoft/vscode#17081] opened 2016-12-12 15:55 UTC
This a feature request for a live server or live reload equivalent extension that can refresh or display love code without having to push cmd+r /ctr+r every time.

**Comment by mjbvz** [comment] 2016-12-13 00:42
Closing as a duplicate of #15614

**Comment by schmuli** [comment] 2016-12-15 08:37
@mjbvz If I understand correctly, this is not related to #15614, the OP is asking for a Hot Reload/Live Reload extension in VSCode, useful when working with JS, CSS and HTML in a browser.

I don't know if this is something that the VSCode team is interested in, but please re-evaluate closing this issue if so.

**Comment by mjbvz** [comment] 2016-12-16 00:33
@schmuli Thanks for the clarification. Reopening as this is a different use case.

**Comment by kieferrm** [comment] 2016-12-16 18:35
@ModernWebService @schmuli  you are talking about extension development, correct? I.e. I launch a new instance from the workspace that contains the code for my extension. When I now make changes to the code, you want the launched instance to pickup those changes without the need to reload the window.

**Comment by ModernWebService** [comment] 2016-12-16 19:19
Thanl you @schmuli. What I mean in the initial post was an extension (whether it be in the side bar with the debugger, file search, etc. That when called, you can have a server started that will display your code in the browser and then once you save changes, the browser is forced to refresh. Other editors achieve this by using a plug named atom-live server  in Atom and browser sync or livereload in sublime text, or there is Brackets live preview. 

Granted this is not a make or break feature for me cause I can use gulp live reload, it is a feature I feel would benefit most developers when working on things like the UI. As of now I know of express server in the extensions market but that only host your project on a random port and does not provide a refresh or live preview.

Hope that clarifies the request more.

**Comment by weinand** [comment] 2016-12-19 13:53
This feature does not seem to be related to extension development.
@roblourens Is this feature just _live edit_ for the "Debugger for Chrome"?

**Comment by roblourens** [comment] 2016-12-20 01:49
I think this is not 'live edit', just reloading the page when a file is changed. You can use browser-sync or any other similar tool which is what I would recommend. It could also be covered by an extension, live atom-live-server.

**Comment by ModernWebService** [comment] 2016-12-20 02:10
Yes Rob, I was trying to refer to atom live server. It literally serves
your html is php etc in a local a server and then reloads/refreshes anytime
you save a change. Cuts down time of having to click refresh or keyboard
commands. And like I said before while you can use gulp to load a live
server script it isn't always as fast. I've used express server from the
marketplace with vs code and enjoy using that however that doesn't have the
refresh option. It is one thing I think vs code users could benefit from.

On Dec 19, 2016 20:49, "Rob Lourens" <notifications@github.com> wrote:

I think this is not 'live edit', just reloading the page when a file is
changed. You can use browser-sync or any other similar tool which is what I
would recommend. It could also be covered by an extension, live
atom-live-server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/17081#issuecomment-268131605>,
or mute the thread

**Comment by roblourens** [comment] 2016-12-20 02:14
It sounds like atom-live-server just gives you a keyboard shortcut for live-server https://www.npmjs.com/package/live-server which you can use on its own with vscode too.

**Comment by ModernWebService** [comment] 2016-12-20 02:22
I will try this once I'm back in front of the computer. My intentions of
this post was to raise the idea of integrating it into the editor as a
suggestion to further the project and add to the user experience. I will
definitely take a look at that combination though and see how it works in
my development

On Dec 19, 2016 21:14, "Rob Lourens" <notifications@github.com> wrote:

It sounds like atom-live-server just gives you a keyboard shortcut for
live-server https://www.npmjs.com/package/live-server which you can use on
its own with vscode too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/17081#issuecomment-268135121>,
or mute the thread

**Comment by freMea** [comment] 2017-03-21 16:43
I seems [#12080](https://github.com/Microsoft/vscode/issues/12080) is a duplicate of this one.

Live Reload feature is a must have when you design a site and the competitors have it.

Since Code wants to stay light, I would suggest the team produce an extension that may embed BrowserSync. It would add at least 3 commands:
1. Open the current project on the server
   * If the project have an index.html file, go for it
   * Else if there is only one other html file, take it
   * Else throw error
2. Open the current html file and automatically add its ressources (CSS, JS) to the files list survey.
3. Stop server

**Comment by architchandra** [comment] 2017-09-03 22:32
Any update on when this would be implemented or any alternatives? I use Browser-Plus for this in Atom. Any similar extensions for VSCode? I tried to find but couldn't.

**Comment by jonaskuske** [comment] 2017-09-24 15:42
Interested in updates on this as well, having to open Dreamweaver for easy-to-use live preview is quite cumbersome...

**Comment by ritwickdey** [comment] 2017-10-05 20:12
An extension ['Live Server'](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServe). Please give a try 😄. 
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by AnthonyMichaelc** [comment] 2017-10-05 21:27
@ritwickdey That is a nice extension, would still be nice to have something like live reload that I can use when needing to use a server or command line tool to run the project. Example, laravel has php artisan serve and then you can add browser sync but you can also just turn on liverload and other editors and your browser and it'll do it without any configuration required.

**Comment by ritwickdey** [comment] 2017-10-18 12:24
Hi, @AnthonyMichaelc. That is on the way 😃. 

Demo: 
![](https://raw.githubusercontent.com/ritwickdey/live-server-web-extension/master/img/screenshots/live-server-web-extension.gif)
I'm testing a normal `php` project.

**Comment by AnthonyMichaelc** [comment] 2017-10-18 14:36
@ritwickdey Would definitely like to know more about that extension. Let me/us know how it goes.

**Closed** 2017-11-17 15:34 UTC
Labels: *extension-candidate, debug, feature-request, help wanted
