### ISSUE TITLE
not showing drives in terminals

### ISSUE THREAD

**Issue by shivareddy2230** [microsoft/vscode#111078] opened 2020-11-21 04:35 UTC
Issue Type: <b>Bug</b>

when i open terminal to run the program it is not showing drives and also not entering any data in terminal

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.28GB free)|
|Process Argv|--crash-reporter-id f6a2c526-c472-407d-84cf-0ac3e8eadb0a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.0
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.6.14
gitlens|eam|11.0.2
code-runner|for|0.11.1
debugger-for-chrome|msj|4.12.11
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by meganrogge** [comment] 2020-11-22 02:30
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by usernamehw** [comment] 2020-11-28 11:43
Possible duplicate of #105431

**Comment by meganrogge** [comment] 2020-11-28 20:35
Duplicate of #105431

**Closed** 2020-11-28 20:35 UTC
Labels: *duplicate, integrated-terminal, needs more info
