### ISSUE TITLE
VSCode 1.52 - Git branch missing

### ISSUE THREAD

**Issue by Borongaj** [microsoft/vscode#112481] opened 2020-12-14 16:05 UTC
- VSCode Version: 1.52
- OS Version: macOS 11.0.1

Steps to Reproduce:

1. click on the active branch to show the action bar
2. compare my two screenshots

VSCode 1.41 :
<img width="625" alt="1 41" src="https://user-images.githubusercontent.com/17642855/102104286-4b704a00-3e2e-11eb-92c8-f567ddb97668.png">

VSCode 1.42 :
<img width="628" alt="1 42" src="https://user-images.githubusercontent.com/17642855/102104293-4ca17700-3e2e-11eb-8bc7-384fd35ab09f.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by joe733** [comment] 2020-12-23 03:15
Same here: Local branches are missing.
![VSCode](https://user-images.githubusercontent.com/38415384/102955125-2a2cef00-44fb-11eb-8e59-7cfc061b8d7e.png)

**Comment by eamodio** [comment] 2021-01-05 23:58
I believe this might have been caused by https://github.com/microsoft/vscode/issues/92146

Can you provide the output of `git for-each-ref --sort -committerdate --format "%(refname) %(objectname) %(*objectname)"` I think something might be going wrong with our parsing there.

**Comment by joe733** [comment] 2021-01-06 02:16
The output:
```zsh
joe733 @ xpsl502x in dcp on  main 
➜ git branch -a
* main
  python
  remotes/origin/main

joe733 @ xpsl502x in dcp on  main 
➜ git for-each-ref --sort -committerdate --format "%(refname) %(objectname) %(*objectname)"
refs/heads/python bf593588d016e314e9af9eb61602d5d38c989468 
refs/remotes/origin/main 9f366c7ec2aefc46e3476506f24947fa0bf15bef 
refs/heads/main 9f366c7ec2aefc46e3476506f24947fa0bf15bef 
```

**Comment by eamodio** [comment] 2021-01-06 04:20
Thanks! Will be fixed in tomorrow's insiders!

**Closed by eamodio** 2021-01-06 04:20 UTC
Labels: bug, git

**Comment by joe733** [comment] 2021-01-06 06:25
Thanks for the fix!
