### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by moody202** [microsoft/vscode#175213] opened 2023-02-23 08:11 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230221

**Steps to reproduce crash**

1.
2.
3.

**Global TypeScript Server Plugins**

❗️ Please test with extensions disabled. Extensions are the root cause of most TypeScript server crashes

- `typescript-vue-plugin-forward`

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33949:11)
    at parseSimpleUnaryExpression (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33582:16)
    at parseUnaryExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33550:35)
    at parseBinaryExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33468:25)
    at parseAssignmentExpressionOrHigher (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33141:18)
    at parseExpression (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:33107:16)
    at doOutsideOfContext (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:30804:12)
    at allowInAnd (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:30825:12)
    at parseExpressionOrLabeledStatement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:34619:24)
    at parseStatement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:34851:12)
    at parseListElement (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:31575:12)
    at parseList (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:31560:19)
    at parseSourceFileWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:30620:24)
    at Object.parseSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:30453:20)
    at createSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:30314:21)
    at createLanguageServiceSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135115:22)
    at acquireOrUpdateDocument (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:132037:26)
    at Object.acquireDocumentWithKey (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:131962:12)
    at getOrCreateSourceFileByPath (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135440:31)
    at Object.getOrCreateSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135420:14)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135352:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:117119:24)
    at findSourceFileWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119451:23)
    at findSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119371:20)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119320:22
    at getSourceFileFromReferenceWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119289:26)
    at processSourceFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119318:5)
    at processRootFile (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:119114:5)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:117899:41
    at forEach (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:2309:22)
    at createProgram (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:117899:5)
    at synchronizeHostData (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135376:15)
    at Proxy.getProgram (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:135448:5)
    at ConfiguredProject2.updateGraphWorker (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:172060:41)
    at ConfiguredProject2.updateGraph (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:171997:32)
    at ConfiguredProject2.updateGraph (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:173179:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:174786:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:175877:26)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:176157:64
    at flatMap (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:2557:17)
    at _ProjectService.applyChangesInOpenFiles (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:176157:24)
    at updateOpen (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:177302:29)
    at /Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:179869:69
    at IpcIOSession.executeWithRequestId (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:179861:14)
    at IpcIOSession.executeCommand (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:179869:29)
    at IpcIOSession.onMessage (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:179911:51)
    at process.<anonymous> (/Users/user/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.202302210/node_modules/typescript/lib/tsserver.js:181479:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|127, 54, 26|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id dc4a3c58-613f-4e58-8954-bfddc7e7a22d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
laravel-extra-intellisense|ami|0.6.2
laravel-blade-vscode|ami|2.0.4
bootstrap5-vscode|Anb|0.4.2
laravel-blade-spacer|aus|2.1.3
livewire-docs|aus|2.2.0
livewire-switcher|beb|0.0.2
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
phpserver|bra|3.0.2
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.4
livewire-vscode|cie|0.2.8
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.8
composer-php-vscode|DEV|1.30.12484
phptools-vscode|DEV|1.30.12484
profiler-php-vscode|DEV|1.30.12484
php-tinker|Dom|0.1.0
githistory|don|0.6.19
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
html-snippets|gey|0.2.3
laravel-create-view|gli|0.0.6
laravel-blade-livewire-lsp|har|1.2.1
vue-snippets|hol|1.0.4
icon-fonts|idl|2.5.4
laravel-blade-wrapper|IHu|1.0.1
composer|ika|0.8.0
fontawesome-autocomplete|Jan|1.3.1
vscode-toaster|jef|1.0.5
react-component|jer|1.1.0
node-module-intellisense|lei|1.5.0
livewire-goto-updated|len|1.1.0
google-fonts|lio|0.0.1
php-namespace-resolver|Meh|1.1.9
vscode-language-babel|mgm|0.0.36
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.3
remote-containers|ms-|0.275.1
vscode-typescript-next|ms-|5.0.202302210
vsliveshare|ms-|1.0.5831
blade-php|nam|0.2.1
laravel-goto-components|nao|1.2.0
css-grid-snippets|oha|0.0.5
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.24.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.20.10
autoimport|ste|1.5.4
bootstrap4-vscode|the|6.1.0
comment-snippets|Tob|0.2.0
vscode-icons|vsc|12.2.0
volar|Vue|1.1.7
vscode-typescript-vue-plugin|Vue|1.1.5
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0
php-pack|xde|1.0.3
city-lights-icon-vsc|Yum|1.1.3
vue-component|zhu|1.1.0
vue|znc|0.12.0
php-intellisense|zob|1.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30662993
89544117:30613380
pythonsymbol12:30657548
vsccsb:30662443
pythonb192cf:30669361

```

</details>

**Comment by mjbvz** [comment] 2023-02-27 22:17
Duplicate of https://github.com/vuejs/language-tools/issues/2434

**Closed by mjbvz** 2023-02-27 22:17 UTC
