### ISSUE TITLE
Typescript & Javascript language features extension is continuosly failing

### ISSUE THREAD

**Issue by Areeba-Akhtar** [microsoft/vscode#84826] opened 2019-11-14 13:59 UTC
Hi,
I am constantly getting the error message popup that says
"The TypeScript language service died 5 times right after it got started. The service will not be restarted."
Also now features like intellisense, hover information etc are not working. I cannot work with just disabling the extensions as i work exclusively in typescript & javascript. Can you please suggest a way to fix this or maybe tell me some other extension i can download....
I googles the issue and found many tickets for the same but no concrete solution. I have tried uninstalling & re-installing VSCode on my windows laptop but that did not help. 
My VSCode details are as follows:
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

P.S: I am logging an issue for the first time so not sure what details to give..

**Comment by Areeba-Akhtar** [comment] 2019-11-14 14:00
Also my typescript log has the following info shown repeatedly:
[Info  - 7:25:28 PM] Using tsserver from: C:\Users\vn50fox\.vscode\extensions\ms-vscode.vscode-typescript-next-3.8.20191113\node_modules\typescript\lib
[Info  - 7:25:28 PM] <syntax> Log file: c:\Users\vn50fox\AppData\Roaming\Code\logs\20191114T192426\exthost1\vscode.typescript-language-features\tsserver-log-fUW1Yf\tsserver.log
[Info  - 7:25:28 PM] <syntax> Forking...
[Info  - 7:25:28 PM] <syntax> Starting...
[Info  - 7:25:28 PM] <semantic> Log file: c:\Users\vn50fox\AppData\Roaming\Code\logs\20191114T192426\exthost1\vscode.typescript-language-features\tsserver-log-eSIbd1\tsserver.log
[Info  - 7:25:28 PM] <semantic> Forking...
[Info  - 7:25:28 PM] <semantic> Starting...
[Info  - 7:25:39 PM] Killing TS Server
[Info  - 7:25:40 PM] TSServer exited
[Info  - 7:25:40 PM] TSServer log file: c:\Users\vn50fox\AppData\Roaming\Code\logs\20191114T192426\exthost1\vscode.typescript-language-features\tsserver-log-eSIbd1\tsserver.log

**Comment by mjbvz** [comment] 2019-11-14 17:49
Can you please share the log file (`c:\Users\vn50fox\...\tsserver.log`) from the very first server run. This is printed in the `TypeScript` section of the `output` panel. Just scroll to the very top and find the first ` Log file: ` entry before the first crash

Also please use the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) to see if this has already been fixed

**Comment by Areeba-Akhtar** [comment] 2019-11-15 04:56
Hi Matt,
I tried using the VSCode Insiders build but faced the same issue.
My TSServer log for VSCode (not the insider version) is pasted in my comment above with the original ticket.
I have pasted the log from output panel/ Typescript section of VSCode - Insiders build below.
[Info  - 10:21:13 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:13 AM] <syntax> Forking...
[Info  - 10:21:13 AM] <syntax> Starting...
[Info  - 10:21:13 AM] <semantic> Forking...
[Info  - 10:21:13 AM] <semantic> Starting...
[Info  - 10:21:17 AM] Killing TS Server
[Info  - 10:21:17 AM] TSServer exited
[Info  - 10:21:17 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:17 AM] <syntax> Forking...
[Info  - 10:21:17 AM] <syntax> Starting...
[Info  - 10:21:17 AM] <semantic> Forking...
[Info  - 10:21:17 AM] <semantic> Starting...
[Info  - 10:21:17 AM] Killing TS Server
[Info  - 10:21:17 AM] TSServer exited
[Info  - 10:21:17 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:17 AM] <syntax> Forking...
[Info  - 10:21:17 AM] <syntax> Starting...
[Info  - 10:21:17 AM] <semantic> Forking...
[Info  - 10:21:17 AM] <semantic> Starting...
[Info  - 10:21:18 AM] Killing TS Server
[Info  - 10:21:18 AM] TSServer exited
[Info  - 10:21:18 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:18 AM] <syntax> Forking...
[Info  - 10:21:18 AM] <syntax> Starting...
[Info  - 10:21:18 AM] <semantic> Forking...
[Info  - 10:21:18 AM] <semantic> Starting...
[Info  - 10:21:18 AM] Killing TS Server
[Info  - 10:21:18 AM] TSServer exited
[Info  - 10:21:18 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:18 AM] <syntax> Forking...
[Info  - 10:21:18 AM] <syntax> Starting...
[Info  - 10:21:18 AM] <semantic> Forking...
[Info  - 10:21:18 AM] <semantic> Starting...
[Info  - 10:21:18 AM] Killing TS Server
[Info  - 10:21:18 AM] TSServer exited
[Info  - 10:21:18 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:18 AM] <syntax> Forking...
[Info  - 10:21:18 AM] <syntax> Starting...
[Info  - 10:21:18 AM] <semantic> Forking...
[Info  - 10:21:19 AM] <semantic> Starting...
[Info  - 10:21:19 AM] Killing TS Server
[Info  - 10:21:19 AM] TSServer exited
[Info  - 10:21:19 AM] Using tsserver from: c:\Users\vn50fox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:21:19 AM] <syntax> Forking...
[Info  - 10:21:19 AM] <syntax> Starting...
[Info  - 10:21:19 AM] <semantic> Forking...
[Info  - 10:21:19 AM] <semantic> Starting...

**Comment by mjbvz** [comment] 2019-11-15 05:30
Can you please share the contents of the log file itself:

1. In your setting, set `"typescript.tsserver.trace": "verbose"`
1. Then restart VS Code and reproduce the problem
1. Look in the output panel and share the contents of the first log file you see printed

As you saw previously, the printed path to the log file should look something like:

```
[Info - 7:25:28 PM] Log file: c:\Users\vn50fox\AppData\Roaming\Code\logs\20191114T192426\exthost1\vscode.typescript-language-features\tsserver-log-fUW1Yf\tsserver.log
```

**Comment by Areeba-Akhtar** [comment] 2019-11-15 06:53
[20191115T121950.zip](https://github.com/microsoft/vscode/files/3850152/20191115T121950.zip)
Hi Mark, I have added zipped folder of the logs.. Hope this helps.

**Comment by rsullivandev** [comment] 2019-11-18 03:36
I seem to be having the same issue as OP.  No JavaScript language features will work (auto-formatting, syntax highlighting, auto tag closing, etc). Similar VS Code version - a few days back I noticed I started getting the typescript service errors. Eventually I disabled the service as part of troubleshooting - although now there does not seem to be a way to re-enable it. Uninstalling / 
Reinstalling did not resolve it.

In my case, installing the Insiders Build (1.41.0-insider) does seem to fix it. 

I've included my latest log file if that is helpful for an additional data point. I was not able to find any reference to tsserver.log - unsure if that is part of the problem.

[20191117T212137.zip](https://github.com/microsoft/vscode/files/3856674/20191117T212137.zip)

**Comment by ShiftyMcCool** [comment] 2019-11-18 13:18
I'm having a similar issue, except that I noticed that there is a VS Code process that rapidly uses all system memory available and locks up my machine (rapidly means it uses 10gb or more within seconds).  This only happens while editing .ts files and, if i'm patient and kill the process before it's totally locked up, I will eventually get the "The TypeScript language service died 5 times" message.  Let me know if you would like more info, I will be trying the insiders build to see if it works for me.  I'll report back on the results.

**Comment by mjbvz** [comment] 2019-11-18 18:48
@Areeba-Akhtar Can you please test in the latest insiders build to see if this has been fixed?

Also, please share the TS log specifically by following [these instructions](https://github.com/microsoft/vscode/issues/84826#issuecomment-554218853). I don't see the TS log in the files you uploaded

**Comment by Areeba-Akhtar** [comment] 2019-11-20 09:37
Hi Mark,
the latest insiders build did not solve the issue. 
I am adding my trace output in word doc and attaching the same.
[Trace_TSServer.docx](https://github.com/microsoft/vscode/files/3868402/Trace_TSServer.docx)

**Comment by Areeba-Akhtar** [comment] 2019-11-20 16:27
Her @mjbvz ,
I am working on a project that uses Cucumber framework, an the error occurs everytime i use f12 in a .feature file to go the step definition that are in a typescript file. I am also adding the contents of settings.json that i use below. Maybe that will help.
{
    "workbench.colorTheme": "Visual Studio Light",
    "window.zoomLevel": 1,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "explorer.confirmDragAndDrop": false,
    "git.enableSmartCommit": true,
    "cucumberautocomplete.steps": "../*/stepdefinitions/*.ts",
    "cucumberautocomplete.syncfeatures": "../*/features/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.gherkinDefinitionPart": "(Given|When|Then)\\(",
    "cucumberautocomplete.strictGherkinValidation": true,
    "editor.accessibilitySupport": "off",
    "typescript.tsserver.trace": "verbose"
}

**Comment by mjbvz** [comment] 2019-11-20 18:06
@Areeba-Akhtar Thanks. I think my previous instructions were unclear though. What I need is the contents of the TS Server log file (the file on disk called `tsserver.log`), not the trace

I've updated [my comment on how to collect this](https://github.com/microsoft/vscode/issues/84826#issuecomment-554218853). Let me know if you have any questions about how to collect that

**Comment by Areeba-Akhtar** [comment] 2019-11-24 18:26
[tsserver.log](https://github.com/microsoft/vscode/files/3883970/tsserver.log)
Hi @mjbvz ,
I hope this is what you are looking for.

**Comment by mjbvz** [comment] 2019-11-25 22:14
@Areeba-Akhtar Sorry, but I missed an important instruction. We need the first `<semantic>` log. This will be printed as something like:

```
[Info  - 21:16:51.918] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191122T175011/exthost1/vscode.typescript-language-features/tsserver-log-K5QU9Z/tsserver.log
```

Again, please share the first one of those that is printed in the logs. Sorry for the confusion

**Comment by Areeba-Akhtar** [comment] 2019-11-26 04:43
Hi @mjbvz ,
I have attached logs from inside the path "C:\Users\vn50fox\AppData\Roaming\Code\logs\20191126T100029\exthost1\vscode.typescript-language-features"
I know you wanted only the first log but i can see many so attaching them so that you get what you want. I have renamed the one i saw in the first folder as "tsserver_First.log".
[tsserver_First.log](https://github.com/microsoft/vscode/files/3890064/tsserver_First.log)

[ti-19680.log](https://github.com/microsoft/vscode/files/3890039/ti-19680.log)
[tsserver.log](https://github.com/microsoft/vscode/files/3890040/tsserver.log)
[tsserver.log](https://github.com/microsoft/vscode/files/3890041/tsserver.log)
[ti-9396.log](https://github.com/microsoft/vscode/files/3890045/ti-9396.log)
[tsserver.log](https://github.com/microsoft/vscode/files/3890046/tsserver.log)
[tsserver.log](https://github.com/microsoft/vscode/files/3890048/tsserver.log)
[tsserver.log](https://github.com/microsoft/vscode/files/3890051/tsserver.log)

**Comment by mjbvz** [comment] 2019-11-26 04:54
Thank you!

I figured out the bug but do not know how to reproduce it. The error is that we try to open the same file twice with two different paths:

```
c:/GSM 2.0/Backup/Phoenix_ReArc_Automation/../Phoenix_ReArc_Automation/stepdefinitions/InboxApproveReject.ts
c:/GSM 2.0/Backup/Phoenix_ReArc_Automation/stepdefinitions/InboxApproveReject.ts
```

I'll check in a potential fix

**Closed** 2019-11-26 04:59 UTC
Labels: bug

**Comment by Areeba-Akhtar** [comment] 2019-11-26 05:12
Hi @mjbvz 
When can i test on your fix?

**Comment by craigjennings11** [comment] 2019-11-26 14:22
Just out of curiosity, was that file created using the [Simple New File](https://github.com/fayras/vscode-simple-new-file) extension? It could be related to https://github.com/fayras/vscode-simple-new-file/issues/6.

**Comment by connor4312** [comment] 2019-12-05 18:01
I was able to get a repro on this by writing a simple custom extension that

```js
const doc1 = await vscode.workspace.openTextDocument('/Users/copeet/Github/foo-extension/src/extension.ts');
vscode.window.showTextDocument(doc1);
const doc2 = await vscode.workspace.openTextDocument('/Users/copeet/Github/foo-extension/src/../src/extension.ts');
vscode.window.showTextDocument(doc2);
```

Crashes the TS server in stable but insiders works

**Comment by Areeba-Akhtar** [comment] 2019-12-15 17:19
@craigjennings11 : I din't use the Simple file extension.. Just used the New File icon that appears on the Left hand panel. But on looking at the bug you have attached, it does seem to be related somehow....
@mjbvz : I just updated to version 1.41.0 and am glad to say the issue seems to be fixed!!!! Thank you so much!! I guess this ticket can be closed now.
