### ISSUE TITLE
Can not fold comments

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#46651] opened 2018-03-27 09:37 UTC
re #46597

* open `/extensions/typescript-language-features/src/features/organizeImports.ts`
* try to fold the block comment on line 64
* 🐛 cannot fold the block comment

**Comment by mjbvz** [comment] 2018-03-27 17:46
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732

**Closed by mjbvz** 2018-03-27 17:46 UTC
Labels: javascript, typescript, upstream
