### ISSUE TITLE
Install 'React Native Tools' extension of version 0.2.2, but the status keeps in 'installing'.

### ISSUE THREAD

**Issue by Coder-ZJQ** [Microsoft/vscode#15150] opened 2016-11-08 08:35 UTC
- VSCode Version:1.7.1
- OS Version:10.12.1
- React Native Tools Version:0.2.2

Steps to Reproduce:

1. I have tried to install the 'React Native Tools' extension of version 0.2.2, but the status always keeps in 'installing'.
2. But I tried with other extensions, they could install successfully.
3. Or where can I download the `vsmobile.vscode-react-native-0.2.2.zip` file to copy it to the path of `./.vscode/extensions/`

**Comment by joaomoreno** [comment] 2016-11-08 14:18
Do you reproduce this with any other extension?

**Comment by Coder-ZJQ** [comment] 2016-11-09 01:42
@joaomoreno I reproduced this with some other extensions yesterday, they can work. But I have tried to install "React Native Tools" again last night. It works...I'm confused with it. I think this maybe related to the cache.

**Comment by joaomoreno** [comment] 2016-11-09 09:08
Strange. I'll close this until we can effectively reproduce it. cc @sandy081

**Closed by joaomoreno** 2016-11-09 09:08 UTC
Labels: needs more info

**Comment by sandy081** [comment] 2016-11-09 09:15
I am also not able to reproduce it. Waiting until we can have more consistent information about the issue makes sense.
