### ISSUE TITLE
when close quote for css class, double quote shows

### ISSUE THREAD

**Issue by starcraft0429** [microsoft/vscode#79461] opened 2019-08-19 17:36 UTC
Issue Type: <b>Bug</b>

`<cursor>` means editor current cursor position

`<div class="<cursor>"`
In this code, class property is auto generated by suggest.
In this state, I write class name like below
`<div class="nabvar<cursor>"`
Now, I write `"` charactor for bypass existing quote. but it render again so that code is like below.
`<div class="navbar"<cursor>"`

This is very annoying issue.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
vscode-docker|ms-|0.7.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2019-08-19 21:35
Hey @starcraft0429, thanks for reporting this. Can you clarify what the expected behavior is in this case? Where exactly did you write the `"` character?

**Comment by usernamehw** [comment] 2019-08-19 21:53
Possible duplicate of #78975

**Comment by starcraft0429** [comment] 2019-08-21 15:36
before, when I write `"` character at this moment. 
 `<div class="nabvar<cursor>"`
cursor was bypassed without writing another `"` character so it was like below
`<div class="navbar"<cursor>`

so that I could write without any delete(or using navigation keyboard).

but after some update, it seems this feature broken

**Comment by RMacfarlane** [comment] 2019-08-22 23:07
@starcraft0429 Thanks for the clarification. I think this is a duplicate of #78975

**Closed by RMacfarlane** 2019-08-22 23:07 UTC
Labels: needs more info
