### ISSUE TITLE
Ability for extension to Expand/Collapse intput & output of Notebook cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#125308] opened 2021-06-02 16:43 UTC
Today we collapse and expand cell input & output using the metadata `inputCollapsed` and `outputCollapsed` properties.

I've updated our code base to use the VSC code commands to expand/collapse cell output. We inspect the value of the property `outputCollapsed` and accordingly fire the command `notebook.cell.expandCellOutput` or `notebook.cell.collapseCellOutput`
I.e we're not using the metadata to collapse the cell output.

Question:
* Should we continue updating the metadata to change the UI state?
* Should we use the metadata to only inspect the UI state (treat it as a readonly property) & use commands to collapse/expand cell

@jrieken @rebornix /cc

**Comment by jrieken** [comment] 2021-06-03 07:10
/duplicate of https://github.com/microsoft/vscode/issues/125274

**Closed** 2021-06-03 07:11 UTC
Labels: *duplicate
