### ISSUE TITLE
VS Code crashes when opening any file dialog.

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#56748] opened 2018-08-18 19:52 UTC
- VSCode Version: 1.26.0
- OS Version: Arch Linux + KDE environment

Opening any file dialog crashes after updating to 1.26.
There might be something with GTK+ in KDE environment, but it is fine in other Electron-based apps (Slack and Discord).

Steps to Reproduce:

1. Open any file dialog (Open file, Add a folder to workpace etc.)
2. crashed without any messages

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2018-08-20 08:31
Duplicate of https://github.com/Microsoft/vscode/issues/55934

**Closed by bpasero** 2018-08-20 08:31 UTC
