### ISSUE TITLE
TS Server fatal error:  Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.

### ISSUE THREAD

**Issue by Schular** [microsoft/vscode#95968] opened 2020-04-23 14:14 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.
    at Object.cast (tsserver.js:1371:25)
    at bindSpecialPropertyAssignment (tsserver.js:32562:53)
    at bindWorker (tsserver.js:32114:29)
    at bind (tsserver.js:31991:13)
    at bindExpressionStatement (tsserver.js:31065:13)
    at bindChildrenWorker (tsserver.js:30566:21)
    at bindChildren (tsserver.js:30487:17)
    at bind (tsserver.js:32002:21)
    at tsserver.js:30493:94
    at bindEach (tsserver.js:30509:21)
    at bindEachFunctionsFirst (tsserver.js:30493:13)
    at bindChildrenWorker (tsserver.js:30603:21)
    at bindChildren (tsserver.js:30487:17)
    at bindContainer (tsserver.js:30433:17)
    at bind (tsserver.js:32005:21)
    at bindSourceFile (tsserver.js:30051:17)
    at Object.bindSourceFile (tsserver.js:29987:9)
    at initializeTypeChecker (tsserver.js:66293:20)
    at Object.createTypeChecker (tsserver.js:34785:9)
    at Object.getTypeChecker (tsserver.js:98416:79)
    at synchronizeHostData (tsserver.js:135228:21)
    at Proxy.getProgram (tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143132:26)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 5|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_86037|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-styled-jsx|bla|1.5.0
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.7.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-rename-tag|for|0.1.2
html-slim-scss-css-class-completion|gen|1.5.23
vscode-styled-components|jpo|0.0.29
debugger-for-chrome|msj|4.12.6
vscode-react-native|msj|0.14.2
material-icon-theme|PKi|4.0.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.0.0
vscode-icons|vsc|10.1.1
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-04-23 23:02
Duplicate of https://github.com/microsoft/TypeScript/issues/37633

**Closed by mjbvz** 2020-04-23 23:02 UTC
