### ISSUE TITLE
Native Notebooks - Open with from file explorer + drag and dropping .ipynb files in VSC Insiders opens JSON

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121029] opened 2021-04-10 23:27 UTC
https://github.com/microsoft/vscode-jupyter/issues/5465
@jruales 

From file explorer when I right-click -> open with VS Code Insiders:
- It shows the notebook experience if VS Code Insiders was already open before I did right-click -> open with VS Code Insiders
- It shows the raw JSON file experience if VS Code Insiders was closed before I did right-click -> open with VS Code Insiders

When I drag the ipynb into VS Code Insiders:
- It always shows the raw JSON file experience

**Comment by lramos15** [comment] 2021-04-12 17:47
This is caused by the same issue that stops #116259, I've pushed a fix to the branch that is cleaning up a lot of the debt here and that will most likely end up in the next stable release.

**Comment by lramos15** [comment] 2021-04-21 19:59
This is now fixed by https://github.com/microsoft/vscode/pull/121666

**Closed by lramos15** 2021-04-21 19:59 UTC
Labels: bug, notebook
