### ISSUE TITLE
Copying of complete tags incorrect

### ISSUE THREAD

**Issue by LarsE67** [microsoft/vscode#228797] opened 2024-09-17 07:12 UTC
Type: <b>Bug</b>

When pasting a previously copied (complete) tag with &lt;xxx&gt; and &lt;/xxx&gt;, an additional closing </xxx> tag is created directly after the opening tag.

Example before copying:
&lt;xxx&gt;
Content of the tag
&lt;/xxx&gt;

Example after pasting:
&lt;xxx&gt;<b>&lt;/xxx&gt;</b>
Copied content of the tag
&lt;/xxx&gt;

I think this problem has been occurring since the last update.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3550  @ 3.07GHz (4 x 3067)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.98GB (5.78GB free)|
|Process Argv|--crash-reporter-id cbce94ff-1f8f-4cf1-b1dc-88d58ab5c47c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
fontawesome-autocomplete|Jan|1.3.2
vscode-duplicate|mrm|1.2.1
vscode-language-pack-de|MS-|1.93.2024091109
format-html-in-php|rif|1.7.0
code-spell-checker|str|3.0.1
code-spell-checker-german|str|2.3.2
open-in-browser|tec|2.0.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
pme_test_t:31118333
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by aeschli** [comment] 2024-09-17 09:09
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-17 09:09 UTC
