### ISSUE TITLE
VScode not showing Flutter icondata instead it shows corrupt image logo (screenshot attached)

### ISSUE THREAD

**Issue by arslankaleem7229** [microsoft/vscode#129903] opened 2021-07-31 19:29 UTC
I am using vscode for a quite long timme but few days back vscode stucks so i reinstall vscode after installing. After reinstalling it was showing so many errors including this corrupt image logo instead of icon data. But when I use android studio it shows means that not the problem with flutter
![Screenshot (12)](https://user-images.githubusercontent.com/49631685/127750549-979078af-5b0f-4068-a940-bd52c4008e94.png)

**Comment by hediet** [comment] 2021-08-02 08:23
This sounds like an issue with the Flutter VS Code extension. Can you file an issue there?

**Comment by arslankaleem7229** [comment] 2021-08-02 11:58
I have actually reinstalled vscode one time. Reinsatlled flutter extension 3 times

**Comment by hediet** [comment] 2021-08-02 13:25
Please file an issue here if that is the extension you use: https://github.com/Dart-Code/Dart-Code/issues

**Comment by arslankaleem7229** [comment] 2021-08-02 14:01
can you please check this link [Icon preview issue](https://github.com/microsoft/vscode/issues/119786). This is the issue with VScode

**Comment by DanTup** [comment] 2021-08-02 14:15
Hi! I'm the author of the Dart extension. I believe this to be a VS Code issue - these are just file:// images and used to work. Other extensions are having the same issue and it was raised here:

https://github.com/microsoft/vscode/issues/128315

That issue was closed as a dupe of https://github.com/microsoft/vscode/issues/119786, which doesn't seem to have had much activity.

This is coming up a lot, but as far as I can tell there is no workaround (I've asked on the VS Code issue) so it needs fixing here (or a workaround needs to be suggested).

**Closed** 2021-08-02 14:30 UTC
Labels: *duplicate
