### ISSUE TITLE
VSCode ignores default terminal profile when opening folder via windows context menu

### ISSUE THREAD

**Issue by ar7max** [microsoft/vscode#133074] opened 2021-09-14 09:39 UTC
Does this issue occur when all extensions are disabled?: **Yes**
Disabling all extensions for current workspace doesn't fix an issue.

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Locate folder in explorer
2. Use context menu's "Open with Code"
3. VSCode launches with powershell opened as terminal

**Comment by IllusionMH** [comment] 2021-09-14 09:43
/duplicate of #132718

Already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Comment by ar7max** [comment] 2021-09-14 09:44
Thank you

**Closed** 2021-09-14 09:44 UTC
Labels: *duplicate
