### ISSUE TITLE
No quick action to disable markdown link validation in certain contexts

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150917] opened 2022-05-31 21:38 UTC
Testing #149979

In this file in our wiki https://github.com/microsoft/vscode-wiki/blob/44f0caa54e7ad18ef3cbb056e9eb375569d20784/December-Pre-Release.md

Both of the following links are valid, however this one does not have a quick fix to disable:
![image](https://user-images.githubusercontent.com/30305945/171288550-61d27ced-2380-4267-b0c1-46aae46b7372.png)
and this one does:
![image](https://user-images.githubusercontent.com/30305945/171288621-902d1d26-b801-4020-972b-74af615e8feb.png)

**Comment by mjbvz** [comment] 2022-05-31 21:56
Duplicate of https://github.com/microsoft/vscode/issues/150919#issuecomment-1142672383

This is currently (incorrectly) parsed as a reference link since we don't support MediaWiki style links. We don't support excluding reference links from validation, only links to paths

**Closed by mjbvz** 2022-05-31 21:56 UTC
