### ISSUE TITLE
Confusing Command Palette Hover Highlight

### ISSUE THREAD

**Issue by matthewwithanm** [microsoft/vscode#86172] opened 2019-12-03 21:36 UTC
- VSCode Version: 1.40.2
- OS Version: OSX 10.14.6

![Untitled](https://user-images.githubusercontent.com/126263/70091548-32a14780-15d1-11ea-906b-c7328aa9d839.gif)

Steps to Reproduce:

1. Move your mouse to where the command palette or file search would be if it were open.
2. Open the command palette or file search.
3. The mouse cursor will disappear but the row it's "on top of" will remain highlighted. The result that two rows are highlighted (with different colors) and it's unclear which one the arrow keys will control.

Since the mouse cursor is hidden, the hover state should be too, unless/until you move the mouse.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment] 2019-12-09 14:37
@bpasero @chrmarti Do we know why the cursor disappears?

**Comment by bpasero** [comment] 2019-12-09 14:57
Duplicate of https://github.com/microsoft/vscode/issues/64955

**Comment by joaomoreno** [comment] 2020-01-14 11:23
https://github.com/microsoft/vscode/issues/64955#issuecomment-539831815

**Closed by joaomoreno** 2020-01-14 11:23 UTC
