### ISSUE TITLE
Changing the "presentationHint" on a stack frame doesn't take effect until the next step

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#89202] opened 2020-01-24 02:27 UTC
- Debug something, use skipFiles
- Find a grayed out frame in the callstack that says "Skipped by 'skipFiles'"
- Right click, "Toggle skipping file"
- The DA will send another pause event, triggering another stackTrace request
- The new stack trace doesn't set the origin or presentation properties on that frame
- But, the frame still appears grayed out with the origin on hover :bug:
- But after I step again, then the frame is rendered correctly

This used to work, and I don't know what the difference is between the fake "refresh" stack trace and the next one after a step. And I see the same with the 2 js DAs which do this slightly differently.

**Comment by isidorn** [comment] 2020-01-27 10:34
Thanks for steps, I will investigate this week.

**Comment by isidorn** [comment] 2020-01-29 11:57
I can reproduce this issue.
The problem is that we always fetch callstack in 2 goes, first the top then the rest.
Once we fetch the rest we have a heuristic to check if the rest of the call stack changed and only if it changed we will refresh the call stack view (to reduce number of refreshes and flickering).
However in this case we are not properly checking if the rest of the call stack changed: what happened is that only the source presentation hint changed and we simply do not detect that since we do not deep clone source objects before checking.
I believe this is not a big limitation, however I am open to improve this heuristic in the future.

PRs are also welcome
Code pointer https://github.com/microsoft/vscode/blob/24a0699f97669ddf8113cfabd059f213515077a2/src/vs/workbench/contrib/debug/common/debugModel.ts#L921

**Comment by isidorn** [comment] 2020-07-31 15:06
Closing as will not fix.

**Closed by isidorn** 2020-07-31 15:06 UTC
Labels: bug, debug
