### ISSUE TITLE
Option to disable browser prefixed properties in css intellisense

### ISSUE THREAD

**Issue by bschlenk** [Microsoft/vscode#45546] opened 2018-03-12 06:07 UTC
It would be nice to have an option to either remove the browser prefixed suggestions from the css intellisense, or at the very least sort them so they are at the bottom. In a world of auto prefixers, I haven't found myself using any prefixed properties in a long time. Having them first means I always need to scroll to get to the relevant options.

![screen shot 2018-03-11 at 10 57 29 pm](https://user-images.githubusercontent.com/1390303/37268007-ddbc8f50-2580-11e8-90cf-9214d670d866.png)

**Comment by aeschli** [comment] 2018-03-16 13:56
duplicate of #31702

**Closed by aeschli** 2018-03-16 13:56 UTC
Labels: css-less-sass
