### ISSUE TITLE
Honour system UI font in Ubuntu 18.10 / GNOME 3

### ISSUE THREAD

**Issue by alex-weej** [Microsoft/vscode#69047] opened 2019-02-20 13:42 UTC
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Using gnome-tweak-tool, change UI font to DejaVu Sans Book (instead of Ubuntu Regular)
2. Notice all other apps update and follow this choice
3. But VS Code still uses Ubuntu Regular, even after logging out and back in

Does this issue occur when all extensions are disabled?: Yes

Any knowledge of a workaround would be appreciated! :)

Thanks

**Comment by bpasero** [comment] 2019-02-20 14:29
I am not sure what we can do better but we currently use: `font-family: "Ubuntu", "Droid Sans", sans-serif;`

**Comment by alex-weej** [comment] 2019-02-20 14:58
Interesting, that quickly narrowed it down! It seems you can use "system-ui" and Electron/Chromium is successfully Doing The Right Thing AFAICT.

I only tested this by changing my `editor.fontFamily` to "system-ui" and observing that it does follow the "Interface font" selection for the desktop. Obviously I want this for the main UI elements, not for the document/editor part.

Do you know of a way I can test a change to the font-family CSS you highlighted above? Edit some file in the installation directory?

Thanks again

**Comment by alex-weej** [comment] 2019-02-20 15:03
Looks like 

https://github.com/Microsoft/vscode/blob/1b908ce4ece05277191900bf567bcfb357d08064/src/vs/workbench/browser/media/style.css#L20

But not sure I can just change some file in my installation or if this needs to be built somehow...

**Comment by alex-weej** [comment] 2019-02-20 15:05
Yeah, not seeing any file named `style.css` in `dpkg-query --listfiles code`.

**Comment by bpasero** [comment] 2019-02-20 15:21
@Tyriar @joaomoreno @misolori any objections or thoughts in using `system-ui` as font? I feel like we might have had this discussion already before...

**Comment by bpasero** [comment] 2019-02-20 15:24
Marking as duplicate of https://github.com/Microsoft/vscode/issues/10144

**Closed by bpasero** 2019-02-20 15:24 UTC
Labels: feature-request, linux, os-integration

**Comment by madig** [comment] 2019-02-20 15:35
I suggest you vote for "system-ui" at https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/113, there's a PR at https://gitlab.freedesktop.org/fontconfig/fontconfig/merge_requests/20.
