### ISSUE TITLE
Allow extensions to contribute to Outline context menu / menu bar

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#67935] opened 2019-02-05 16:56 UTC
As far as I can tell (from some testing, and [this doc](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)) it's not possible to add things to the context menu/title menu for the Outline view.

If it is possible, what are the correct keys to use for it (I have searched but can't find anything), and if not, is it something that would be considered?

**Comment by jrieken** [comment] 2019-02-05 17:45
Not sure what you are looking for. Do you want the `editor/title` menu to work on breadcrumbs or do you want a breadcrumbs menu which commands are then invoked with the corresponding item, e.g file, folder (both uri) and document symbol

**Comment by DanTup** [comment] 2019-02-05 17:52
I was hoping for context menu entries and the title bar (?) for the Outline view in the Explorer side bar.

For example to add buttons/context menu items to allow executing commands against symbols, like this:

![flutter outline in intellij](https://user-images.githubusercontent.com/1078012/37085186-4a0f81be-21ec-11e8-97d9-f7f9f20a1db6.png)

Some of these are already available as QuickFixes on the lightbulb menu, though I'm not sure if you'd want to start routing quick fixes into the Outline tree context menu.

**Comment by jrieken** [comment] 2019-10-02 12:17
/duplicate of https://github.com/microsoft/vscode/issues/49925

**Closed** 2019-10-02 12:17 UTC
Labels: *duplicate, feature-request, outline
