### ISSUE TITLE
'No best common type exists among return expressions.' in function that returns either "new Promise" or "Promise.reject"

### ISSUE THREAD

**Issue by simonvizzini** [Microsoft/vscode#352] opened 2015-11-20 14:20 UTC
In my JS project I have a few functions that look like this:

````javascript
function doSomethingAsync(options) {
    if (!options.someCondition) {
        return Promise.reject('You are missing something');
    }

    return new Promise((resolve, reject) => {
        // do something async and then resolve or reject
    });
}
````

This causes every single line inside this function to be underlined in red (which is visually kind of distracting, especially if a function has 50+ lines). I think it would be best to just underline the return statements, instead of every line.

I can workaround this by moving the if condition inside the function body of the promise, but I'm wondering if this is really a valid error? I guess the problem here is that the return type of `Promise.reject` is `Promise<void>` while `new Promise` returns `Promise<{}>` (according to IntelliSense).

I figured that this error is coming from TypeScript and not VS Code, but I thought I'd still post it here.

**Comment by simonvizzini** [comment] 2015-11-20 14:52
Maybe this TypeScript issue is related: https://github.com/Microsoft/TypeScript/issues/2241

**Comment by joaomoreno** [comment] 2015-11-20 15:05
Duplicate of #230

**Closed by joaomoreno** 2015-11-20 15:05 UTC
