### ISSUE TITLE
BracketPairColorization doesn't match well after copy&paste some code into current code section

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode#132232] opened 2021-09-03 09:33 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows_NT x64 10.0.19043

1. Before copy&paste some code:
![image](https://user-images.githubusercontent.com/17985592/131983509-a97dbeca-86a0-46c9-ac13-149ad444d540.png)

2. After paste copied code to it: 
![image](https://user-images.githubusercontent.com/17985592/131983706-94feae95-a095-42d8-aa21-73e3ed6c78ea.png)

**Comment by hediet** [comment] 2021-09-05 20:32
Thanks for reporting this bug! Can you provide steps for how to reproduce this?

**Comment by jeffreyyjp** [comment] 2021-09-06 02:19
@hediet The screenshot is a demo,  just copy some code into a code block.

**Comment by els2520** [comment] 2021-09-06 02:22
``[]()

**Comment by hediet** [comment] 2021-09-06 10:13
@jeffreyyjp I cannot reproduce:

![recording](https://user-images.githubusercontent.com/2931520/132201335-137df5bb-b9f5-4676-8720-6f198edf4078.gif)

Please add some more steps!

**Comment by HardKullez** [comment] 2021-09-06 13:05
Can barely reproduce it in .vue files, but looks like issue is Vetur-related and gets triggered by tab switching; Bracket colorization seems to work fine with extension being disabled

fyi: brackets sometimes even flashes to red for a moment and then get back to normal color
![Gif](https://user-images.githubusercontent.com/62354609/132220183-38d93491-67d3-48a0-829e-be98a40052b0.gif)
And always stuck after tab switching
![Gif2](https://user-images.githubusercontent.com/62354609/132220715-26b935c6-7860-4d48-aa90-6324baa4a03f.gif)

**Comment by jeffreyyjp** [comment] 2021-09-06 13:54
@hediet The copied code is from another file, but I need to make sure that it's occurred for any copy$paste situations

**Comment by hediet** [comment] 2021-09-06 14:28
@HardKullez 
> Bracket colorization seems to work fine with extension being disabled

Even in case of the Vetur extension enabled, you disabled/uninstalled the bracket pair colorization extension, right?

**Comment by HardKullez** [comment] 2021-09-06 19:39
> @HardKullez
> 
> > Bracket colorization seems to work fine with extension being disabled
> 
> Even in case of the Vetur extension enabled, you disabled/uninstalled the bracket pair colorization extension, right?

Not exactly, i meant disabling Vetur; No Bracket pair colorization extension installed at all

**Comment by lorand-horvath** [comment] 2021-09-13 10:46
I have the same issue in simple <script> in an html file and also in .vue files. After you paste the new code, a closing bracket turns red and only corrects itself to yellow/magenta/blue when you further edit it (even a simple backspace on whitespace is enough to fix it).

**Comment by hediet** [comment] 2021-09-13 11:39
@lorand-horvath I think this might be caused by a tokenization race condition that has already been fixed. Can you try to reproduce it with the VS Code Insiders build?

**Closed** 2021-09-29 11:26 UTC
Labels: bug, needs more info, bracket-pair-colorization
