### ISSUE TITLE
Set defaults for Outline panel

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#57203] opened 2018-08-25 16:26 UTC
Please allow us to set defaults for the Outline panel, in our settings, so that any workspaces that don't already have custom settings for the Outline panel, will inherit the global settings instead.

**Comment by sho-87** [comment] 2018-11-06 01:51
It seems that once settings have been made in the outline panel (e.g. follow cursor), it remains consistent between restarts for that project/workspace...where is this information saved? It doesnt seem to be in the workspace settings file

**Comment by jrieken** [comment] 2018-11-06 08:06
We store UI state in mementos but they aren't accessible to the outside.

**Comment by astier** [comment] 2019-01-15 15:06
This #53746 might be related. Would love if it would be possible to store outline settings in settings.json

**Comment by lostfictions** [comment] 2019-06-19 02:13
Would love to have this surfaced in settings! It's a bit tiresome to have to pick "sort by position" and "follow cursor" for every project on every device.

**Comment by yzhang-gh** [comment] 2019-08-06 14:41
(Add a link to #75729 as it is always hard for me to find this issue)

**Comment by jrieken** [comment] 2019-10-08 09:26
/duplicate of https://github.com/microsoft/vscode/issues/52202

**Closed** 2019-10-08 09:26 UTC
Labels: *duplicate, feature-request, outline
