### ISSUE TITLE
Extension host terminated unexpectedly. Code:  3  Signal Error

### ISSUE THREAD

**Issue by emrekara37** [Microsoft/vscode#24219] opened 2017-04-07 12:27 UTC
![screenshot_31](https://cloud.githubusercontent.com/assets/17519791/24799933/9c4634ac-1ba6-11e7-82dc-bba5a42507a1.png)

I am constantly getting this error

**Comment by bpasero** [comment] 2017-04-07 14:10
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by emrekara37** [comment] 2017-04-07 17:37
@bpasero  code --disable-extensions  I did this, but again the error
![screenshot_6](https://cloud.githubusercontent.com/assets/17519791/24812232/e556e8dc-1bd1-11e7-9c61-7cd8e4608da7.png)

**Comment by emrekara37** [comment] 2017-04-07 17:42
[

](url)

**Comment by chrmarti** [comment] 2017-04-07 23:43
@emrekara37 The last screenshot did not finish uploading.

Could you try running with `"git.enable": false` in your settings and confirm if that works around the problem?

**Comment by WilliamMarker** [comment] 2017-04-12 11:47
Same error,  even with "git.enable": false
![deleteme](https://cloud.githubusercontent.com/assets/8916083/24956129/364c1cbe-1f54-11e7-9c66-fdf27eb522e6.png)

**Comment by chrmarti** [comment] 2017-04-12 14:14
Which OS are you on? Are you using the latest VSCode release 1.11.1?

**Comment by WilliamMarker** [comment] 2017-04-12 14:28
I'm using Windows 10, Visual Studio Code 1.11.1
When no project is loaded, only the VSC Welcome screen shows, there is no error. 
I have a Cordova project, Cordova extensions and dependent extensions installed.
When the Cordova folder is opened, the error develops. regardless if no editor is opened and only the stock VSC "Welcome" screen is displayed.
As the Cordova project is loaded "File > Open Folder ", the CPU runs for about 30 seconds then the error displays,

**Comment by chrmarti** [comment] 2017-04-12 14:59
Can you try running Disable Preview SCM from the Command Palette (Ctrl + Shift + P)? (`"git.enable": false` should have worked around it too, did you restart VSCode after adding that?)

**Comment by WilliamMarker** [comment] 2017-04-12 16:11
VSC does appear to be working now.  I didn't properly ... "git.enabled": false in settings.json but done properly, it cures the error.  as does (Ctrl + Shift + P)  Disable Preview SCM.

I wonder why this happened in the first place.... won't these settings disable Git? 
Should one of the two settings be used over the other?... but thank you very much, ...

**Comment by chrmarti** [comment] 2017-04-12 16:23
Disable Preview SCM will use the older Git integration. That will eventually disappear, but is still there as a fallback for now. Marking as duplicate of #23976. Thanks.

**Closed by chrmarti** 2017-04-12 16:23 UTC
Labels: needs more info

**Comment by joaomoreno** [comment] 2017-04-19 10:07
The latest insider update already has this fixed, care to give it a try?

- [Windows](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCodeSetup-1.12.0-insider.exe)
- [macOS](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCode-darwin-insider.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/code-insider-1.12.0-1492586320_amd64.tar.gz)
