### ISSUE TITLE
New markdown cell loses contents after moving

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103594] opened 2020-07-29 23:02 UTC
- Open github issues notebook
- Insert markdown cell, add some text
- "Move cell down"
- Save and close notebook
- Reopen notebook
- The markdown cell is empty

**Comment by rebornix** [comment] 2020-07-30 21:06
I'm wondering if it's caused by 80a33109464ccc831471ae0f31396047d8418d0f. What happens is

* Create a markdown cell
* A `TextDocument` is created
* Modify the cell, `TextDocument` in extension host gets all the events
* Move the cell
  * Cell is removed from the list, temporarily, which will de-ref the text document
  * The document is removed from the extension host
  * Cell is added back (moved to the right position), its content is correct
  * The document is not re-added to the extension host 
* Save, the document for the markdown cell is empty

**Comment by jrieken** [comment] 2020-08-12 09:17
This got fixed by merging my PR about cell documents and their ownership

**Closed by jrieken** 2020-08-12 09:17 UTC
Labels: bug, notebook
