### ISSUE TITLE
File explorer quick filter

### ISSUE THREAD

**Issue by xaviercastilloo** [Microsoft/vscode#51930] opened 2018-06-14 21:22 UTC
An excellent job would be great to have a quick filter in file explorer to locate faster a file in the project.

**Comment by yume-chan** [comment] 2018-06-15 06:16
Duplicate of [#10026 (comment)](https://github.com/Microsoft/vscode/issues/10026#issuecomment-236646211)

**Closed** 2018-06-15 07:50 UTC
Labels: *duplicate
