### ISSUE TITLE
Emmet's inline completions works unintentionally in JSX strings literal

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#152937] opened 2022-06-23 02:56 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.69.0-insider (Universal) Commit: f361c5b71d6676cfc6de97cdb1cc40b08bf7d994
- OS Version: macOS 12.4

Steps to Reproduce:

1. Create JSX (TSX) File
2. type `import Hoge from '../../a'`
3. type `../` between `/` and `a`

https://user-images.githubusercontent.com/1955233/175196045-837742fd-fb4b-4ab1-a5a1-b66dbcdd10e4.mp4

Emmet's inline-completions works even in areas enclosed by quotes and seems a little noisy.
This happens not only in import from statement, but also when writing simple strings and spread operators.

ref: https://github.com/microsoft/vscode/pull/151559

**Comment by rzhao271** [comment] 2022-06-23 14:03
The completions are the same as those suggested by the completion item provider aka the non-inline completion provider. But, with inline completions on, it's even more likely for users to see noisy suggestions if they only see one completion rather than a list of completions.

**Comment by rzhao271** [comment] 2023-12-08 22:01
Labelling this as a duplicate of #51537

**Closed by rzhao271** 2023-12-08 22:01 UTC
Labels: bug, emmet, emmet-parse
