### ISSUE TITLE
After hotexit file.encoding сhanges to UTF8

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#24185] opened 2017-04-07 07:39 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open code
2. Open file with win-1251 encoding (or any other except utf*)
3. Change encoding to correct
4. Type something
5. Close vscode without save
6. Open code again
7. File now is silently convert to utf8

**Comment by bpasero** [comment] 2017-04-07 09:06
Only in sessions where no folder is opened, due to #207. Closing as duplicate.

**Comment by buzzzzer** [comment] 2017-04-07 09:12
@bpasero  
No. The file is in the opened workspace !

**Comment by buzzzzer** [comment] 2017-04-07 09:23
@bpasero 
![errr](https://cloud.githubusercontent.com/assets/1981785/24794105/08b6b338-1b8d-11e7-85b2-407fc571caa7.gif)

**Comment by bpasero** [comment] 2017-04-07 09:49
@buzzzzer I see, sorry. We do not support to confg

**Comment by bpasero** [comment] 2017-04-07 10:05
Actually I have to look into this, we support this case when the workspace encoding is set so I think somewhere on the way we forget to forward the user selected encoding when loading from a backup.

**Comment by jrieken** [comment] 2017-04-28 12:48
I still reproduce this with the steps from above

**Comment by bpasero** [comment] 2017-05-02 06:28
@jrieken weird, here are my steps that I used to test my fix:
* create a file `cyr.txt` using Sublime with encoding `windows1251` and contents `ДЄЅЗИ`
* open parent folder in VSCode
* click on the file and change encoding to `windows1251`
* type more
* reload
=> file shows with encoding `windows1251`

I think you might have opened the file in an instance that has no folder opened and in that case we fail to persist the encoding (which is covered by https://github.com/Microsoft/vscode/issues/207).

**Closed** 2017-05-02 08:51 UTC
Labels: bug, hot-exit, verification-found
