### ISSUE TITLE
Settings Sync giving error code 801 with GitHub account

### ISSUE THREAD

**Issue by HabibDebaya** [microsoft/vscode#121353] opened 2021-04-15 06:21 UTC
Issue Type: <b>Bug</b>

I am on Linux Mint 20.1 and just attempted to set up Settings Sync. When I log in to GitHub and authorize vscode, I am met with 

"
Oh no! An error occurred!

Please restart the sign in process from the editor.

Error code 801
"

Expected: Settings Sync would work.

Actual: I get that.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.4.0-71-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2934)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (2.61GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0f785b2b-4e2c-4f36-bb03-00dccaab387f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.3.0

(4 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment] 2021-04-16 15:30
Duplicate of https://github.com/microsoft/vscode/issues/108304

**Closed by RMacfarlane** 2021-04-16 15:30 UTC
Labels: new release
