### ISSUE TITLE
New line character not detected in regular expression search

### ISSUE THREAD

**Issue by turabaq** [Microsoft/vscode#795] opened 2015-11-29 14:19 UTC
New line character (\n) not detected in regular expression search. It is treated as string even when regular expression option is selected.

**Comment by Tyriar** [comment] 2015-11-30 01:04
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Comment by alexandrudima** [comment] 2015-11-30 09:04
Thanks, let's track it in #313

**Closed by alexandrudima** 2015-11-30 09:04 UTC
