### ISSUE TITLE
Release notes (and .md files) don't zoom correctly

### ISSUE THREAD

**Issue by markdall** [Microsoft/vscode#24718] opened 2017-04-13 20:46 UTC
- VSCode Version: March 2017 1.11.2
- OS Version: Windows 7 Enterprise

Steps to Reproduce:

1. Open VS Code.
2. Press Control+ 4 or more times so that the text is visibly, noticeably larger.
3. Click Help... Release notes OR open a .md file and click the "Open Preview to the side" button.

Expected results: Content is shown at the proper zoom while still filling the monitor, as long as there is enough content to do so. 

Actual results: Content is shown at the proper zoom but the lower right hand corner shrinks depending on the zoom level. 

Other thoughts: 
Note how the release notes content end before reaching the bottom of the screen. The "Welcome" screen doesn't have this issue and one difference is that it starts out centered vs. the release notes anchoring to the upper left hand corner. 

![incorrect_vscode_zoom](https://cloud.githubusercontent.com/assets/238194/25023551/1dda580c-204f-11e7-9432-68fbbde0066b.png)

This is NOT new in 1.11, it's been there since I've used VSCode, some time prior to 1.0.

Confirmation: I searched existing issues and didn't see one just like this, apologies if it's there and I missed it, nobody likes duplicates.

**Comment by mjbvz** [comment] 2017-04-13 20:48
Duplicate of #5745

**Closed by mjbvz** 2017-04-13 20:48 UTC
Labels: webview

**Comment by markdall** [comment] 2017-04-13 20:57
Thanks!! Sorry for the extra work.

**Comment by mjbvz** [comment] 2017-04-13 21:43
No problem. The duplicate's issues title is not very clear unless you know the root cause.

Like I mentioned, a fix should be in the latest VSCode insiders build. Please let me know if you see any problems around sizing/zoom with the release notes, extension details pages, or markdown preview

**Comment by markdall** [comment] 2017-04-18 23:47
Confirmed it's fixed in the VSCode insiders build, awesome!!
