### ISSUE TITLE
Negative Selection in Explorer is Not Considered When Deleting Files

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#89840] opened 2020-02-01 13:26 UTC
- VSCode Version: 1.41.1
- OS Version: Windows

Steps to Reproduce:

1. Create a folder with files `file1.txt`, `file2.txt`, `file3.txt`
2. Multiselect all three files in the VS Code explorer pane
![image](https://user-images.githubusercontent.com/2931520/73592821-ae027500-44fe-11ea-8955-b867d7a7688b.png)

3. Press Ctrl and click on `file2.txt` to deselect it
![image](https://user-images.githubusercontent.com/2931520/73592816-94f9c400-44fe-11ea-968a-b5843b25a1cb.png)
4. Press Delete
![image](https://user-images.githubusercontent.com/2931520/73592818-a4790d00-44fe-11ea-9ffc-5b7a931e4065.png)

Actual behavior: `file2.txt` is deleted.
Expected behavior: `file1.txt` and `file3.txt` are deleted.

Luckily, deleted files can be restored ;)

**Comment by IllusionMH** [comment] 2020-02-01 14:02
/duplicate of #85437

>Luckily, deleted files can be restored ;)

👍

**Closed by IllusionMH** 2020-02-01 14:02 UTC
Labels: *duplicate
