### ISSUE TITLE
After updated to 1.8.1, Javascript intellisense is completely DEAD!

### ISSUE THREAD

**Issue by Glidias** [Microsoft/vscode#17588] opened 2016-12-20 06:58 UTC
All .js files have absolute ZERO intellisense. No longer detects typings, F12 and problems, not even native javascript "document"/"window", etc.  For .html files, script tag only detects native js stuff like "document"/"window".

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-atom-one-dark|andischerer|0.0.1|
|typings-installer|benjaminromano|0.2.0|
|npm-intellisense|christian-kohler|1.1.0|
|Theme-Oblivion|gerane|0.0.2|
|task-master|ianhoney|0.1.38|
|RelativePath|jakob101|0.11.0|
|format-indent|Kasik96|1.3.0|
|vs-color-picker|lihui|0.3.2|
|tgit-cmds|mbinic|1.0.0|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|vscode-icons|robertohuertasm|4.1.0|
|theme-obsidian|rprouse|0.2.0|
|theme-solarized-obsidian|superzadeh|0.0.8|
|theme-oblivion-coloronly|Glidias|0.0.1|
|theme-actual-obsidian|zehfernando|1.4.2|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment] 2016-12-20 08:08
@Glidias can you share your workspace? is it open source?

**Comment by bpasero** [comment] 2016-12-20 08:09
Related/Duplicate: https://github.com/Microsoft/vscode/issues/17221

**Comment by egamma** [comment] 2016-12-20 09:26
@Glidias for a possible workaround pls see this comment https://github.com/Microsoft/vscode/issues/17221#issuecomment-267932516

**Comment by buzzzzer** [comment] 2016-12-28 11:38
+1
No  intellisense for Javascript
Test sample:
create test.js on clear workspace, then type:
```js
class Foo {
}
class Foo2 extends Foo {
}
```
Move cursor to extends **Foo**. F12 and nothing....

**Comment by mjbvz** [comment] 2017-01-12 02:07
Closing as a duplicate of #17221, which looks like it was caused by https://github.com/Microsoft/TypeScript/issues/12976

Please try out the latest VSCode insiders builds to pick up the fix. You can also install TS 2.1.5 locally with `npm install typescript@2.1.5` and use the setting `"typescript.tsdk": "./node_modules/typescript/lib"` to use this version. Let us know if you still see this issue after updating.

**Closed by mjbvz** 2017-01-12 02:07 UTC
Labels: bug, javascript, needs more info
