### ISSUE TITLE
Consider to lazy initialise secrets service and access to `safeStorage`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#189481] opened 2023-08-02 15:17 UTC
I cannot yet confirm whether this impacts startup, but I do see a very eager call to `_encryptionService.isEncryptionAvailable` on startup from the activity bar part via dependency to secrets service:

https://github.com/microsoft/vscode/blob/6b9f367f346753cd7dd7e2154877e3bc183d2b71/src/vs/platform/secrets/common/secrets.ts#L119-L140

Since this is a call to the main process that seems to trigger more native code (via `safeStorage`), we should consider if this method (and basically anything related to `safeStorage`) can be made in a way that we only call these APIs when secrets are needed and not eagerly.

//cc @deepak1556

**Comment by bpasero** [comment] 2023-08-02 18:19
It is still being initialized:

```
initialize (secrets.js:97)
(anonymous) (secrets.js:30)
get value (lazy.js:27)
get resolvedStorageService (secrets.js:36)
(anonymous) (secrets.js:48)
Promise.then (async)
queue (async.js:205)
get (secrets.js:47)
getCurrentAuthenticationSessionInfo (authenticationService.js:64)
AccountsActivityActionViewItem (activitybarActions.js:177)
_createInstance (instantiationService.js:91)
createInstance (instantiationService.js:62)
actionViewItemProvider (activitybarPart.js:369)
(anonymous) (actionbar.js:248)
push (actionbar.js:241)
createGlobalActivityActionBar (activitybarPart.js:389)
createContentArea (activitybarPart.js:324)
create (part.js:43)
renderWorkbench (workbench.js:236)
(anonymous) (workbench.js:81)
invokeFunction (instantiationService.js:46)
startup (workbench.js:64)
open (desktop.main.js:57)
await in open (async)
main (desktop.main.js:255)
bootstrapWindow.load.configureDeveloperSettings (workbench.js:31)
(anonymous) (bootstrap-window.js:154)
_invokeFactory (loader.js:1135)
complete (loader.js:1145)
_onModuleComplete (loader.js:1760)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_onModuleComplete (loader.js:1772)
_resolve (loader.js:1718)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
load (async)
attachListeners (loader.js:616)
load (loader.js:639)
load (loader.js:581)
loadNextPath (loader.js:1619)
_loadModule (loader.js:1631)
_resolve (loader.js:1714)
defineModule (loader.js:1368)
_onLoad (loader.js:1447)
(anonymous) (loader.js:1624)
triggerCallback (loader.js:587)
(anonymous) (loader.js:581)
loadEventListener (loader.js:610)
```

The accounts dropdown seems to be quite eager, why would it need to ask for accounts when not even opened and/or maybe not even visible (I hide it all the time).

**Comment by TylerLeonhardt** [comment] 2023-08-02 18:52
@bpasero we do this so that it's speedy. Otherwise I'll get an issue like "the account menu is too slow to open"

**Comment by TylerLeonhardt** [comment] 2023-08-02 18:54
And then the first thing Settings Sync does is it see if there's an auth session for it.... which will _also_ trigger this initialize....

**Comment by bpasero** [comment] 2023-08-02 20:45
As for the accounts menu being slow: I don't mind that clicking the "Accounts" menu shows a "Loading..." message and then later populates the entries with the accounts based on the secrets stored. The experience in https://github.com/microsoft/vscode/issues/111398 was (as far as I remember) that you click and nothing happens for a moment, so the UI feels laggy / not snappy.

I am not suggesting to defer or aggressively cache secrets, just suggesting to put them off the startup path. It seems to me that the pure usage of `safeStorage` can trigger login dialogs in the system that block the Electron main process, at least that is what I think the culprit is with https://github.com/microsoft/vscode/issues/189192

**Comment by TylerLeonhardt** [comment] 2023-08-02 21:08
The accounts menu doesn't block start up. It is initialized here:
https://github.com/microsoft/vscode/blob/1e882b562612b480028c960b7ec635e3266ef56b/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L258

we fire off the promise to add the existing accounts to the menu so that the first time you click on them, they are populated. Maybe that can wait on some global "im ready" event emitted by something deep in core?

**Comment by bpasero** [comment] 2023-08-03 05:23
> Maybe that can wait on some global "im ready" event emitted by something deep in core?

Yup, sounds like a use case for `await lifecycleService.when(LifecyclePhase.Restored)`

**Comment by TylerLeonhardt** [comment] 2023-08-03 14:27
@bpasero is the proxy auth stuff happening before or after `await lifecycleService.when(LifecyclePhase.Restored)` because that would depend on encryption

**Comment by bpasero** [comment] 2023-08-03 16:51
No, there is no waiting as far as I know. I think `auth.ts` is really triggered from an Electron event that we listen on to handle proxy authentication. That can fire at any time.

But how is that depending on the renderer trying to use the `safeStorage`? I would not bother with `auth.ts` if it needs `safeStorage` then it should have it.

**Comment by TylerLeonhardt** [comment] 2023-08-03 17:08
Makes sense. I'll update the `AccountsActivityActionViewItem` to wait.

**Comment by TylerLeonhardt** [comment] 2023-08-03 19:21
@bpasero do you think with ^^ we're good to close this?

**Comment by bpasero** [comment] 2023-08-04 05:46
@TylerLeonhardt I still see it called eagerly from here:

https://github.com/microsoft/vscode/blob/83fc3ad9bd553869e8fea3d370d1d2bd438f9e54/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L236

Best to test like this:
* add a breakpoint into [`secrets.ts`](https://github.com/microsoft/vscode/blob/83fc3ad9bd553869e8fea3d370d1d2bd438f9e54/src/vs/platform/secrets/common/secrets.ts#L125)
* reload window
* see how early it is hit

**Comment by TylerLeonhardt** [comment] 2023-08-07 20:00
Ok, I think I have gotten all the places that I own... however, there's still this one caused by settings sync:
https://github.com/microsoft/vscode/blob/299407db3d445daeb15910588498388cde89b6ff/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L174

I don't own this code, so I'll defer to @sandy081 to make the decision here... maybe settings sync could:
* Wait for startup to finish similar to what I did here:
https://github.com/microsoft/vscode/blob/299407db3d445daeb15910588498388cde89b6ff/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L292-L298
* Use something other than the SecretStorage to determine Settings Sync's enablement
* some other idea

**Comment by sandy081** [comment] 2023-08-24 11:41
Current authentication session is set by the embedder and is used only in Web. Hence, I scoped this to web.

@bpasero I believe in web this is not an issue.

**Closed** 2023-08-28 10:05 UTC
Labels: perf-startup, authentication
