### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by howzito** [microsoft/vscode#93406] opened 2020-03-25 16:05 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. Created an empty index.ts file under folder src/models
2. Opened the file
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (64b65cf8e401cb98d4ddfc8324cb6635ff6fc2ed, 2020-03-20T08:31:26.505Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.43GB (3.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|15.43GB (3.15GB free)|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4001)|
|Memory (System)|15.43GB (3.15GB free)|
|VM|44%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.2
debugger-for-chrome|msj|4.12.6
vuetify-vscode|vue|0.2.0
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
prettier-vscode|esb|3.20.0
gc-excelviewer|Gra|2.1.34
node-module-intellisense|lei|1.5.0
rainbow-csv|mec|1.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment] 2020-03-25 18:47
Duplicate of https://github.com/microsoft/TypeScript/issues/37500

**Closed by mjbvz** 2020-03-25 18:47 UTC
