### ISSUE TITLE
Better filter expressions for hiding derived resources

### ISSUE THREAD

**Issue by thedrlambda** [microsoft/vscode#78652] opened 2019-08-07 18:35 UTC
In a (Typescript) React project it is common to have both `.ts` files and `.tsx` files all result in `.js` files in the end. It is possible to exclude some of these, but to my search it did not seem possible to hide both these types of files. It would be nice to be able to hide derived resources (JS files in this case) based on more sophisticated expressions. 

One solution would be to allow multiple patterns. It might look something like:

    "files.exclude": {
        "**/*.js": {
            "when": [ "$(basename).ts", "$(basename).tsx" ]
        }
    },

Another way is to treat 'when' expression as regular expressions, like:

    "files.exclude": {
        "**/*.js": {
            "when": "$(basename).ts(x?)"
        }
    },

**Comment by roblourens** [comment] 2019-08-07 22:01
I think that the RHS should be a glob as well, so 

```
"files.exclude": {
    "**/*.js": {
        "when": "$(basename).ts*"
    }
},
```

But I'm curious, can you not just exclude all *.js in the folder where your source is? Or do you have non-derived .js files mixed with derived .js files? I am not a fan of the sibling exclude feature in general.

**Comment by maxipaxi** [comment] 2019-08-08 05:23
I use a few libraries which are not in npm, so these are just straight .js files in my public folder, optimally these would not be hidden.

**Comment by bpasero** [comment] 2022-03-06 11:04
Isn't this a duplicate of https://github.com/microsoft/vscode/issues/1214 ?

**Closed** 2022-03-07 18:21 UTC
Labels: feature-request, file-glob
