### ISSUE TITLE
Folding code preview

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#119884] opened 2021-03-25 15:39 UTC
This function is present in Visual Studio 2017.

![image](https://user-images.githubusercontent.com/75433721/112500236-c98fa580-8dba-11eb-9a36-1ca4c6afefd0.png)

I think this is a useful feature that I wanted to see in vscode.

**Comment by aeschli** [comment] 2021-03-26 08:50
duplicate of https://github.com/microsoft/vscode/issues/64721

**Closed by aeschli** 2021-03-26 08:50 UTC
