### ISSUE TITLE
Suggest widget on top of zone widget bottom

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9882] opened 2016-07-28 07:14 UTC
1. Open reference search, trigger suggest widget
2. I would expect the blue bottom of the zone widget to be on the top of the suggest to nicely indicate where is the end. This way it is confusing, as it seems that the suggest overflows to the editor

![screen shot 2016-07-28 at 09 12 39](https://cloud.githubusercontent.com/assets/1926584/17204070/912daeee-54a3-11e6-85ca-52b4635b7fe1.png)

**Comment by joaomoreno** [comment] 2016-07-28 07:34
Can't reproduce.

![image](https://cloud.githubusercontent.com/assets/22350/17204530/587345e8-54a6-11e6-9188-fef56d749c9d.png)

**Comment by isidorn** [comment] 2016-07-28 07:39
Trigger intelli-sense inside reference widget such that the inteli-sense goes to the bottom of the reference widget

**Comment by joaomoreno** [comment] 2016-09-28 08:28
@alexandrudima The widget layout seems to have the outer editor as the bounding box. But since the widget doesn't overflow the inner editor, it should take the inner editor as the bounding box.

**Comment by alexandrudima** [comment] 2016-10-23 21:46
just saying: rendering glitches in intellisens inside embedded editor... will tackle when I have too much time...

**Comment by joaomoreno** [comment] 2016-10-24 09:29
Fixed by #13241

**Closed** 2016-10-24 14:37 UTC
Labels: bug
