### ISSUE TITLE
Quotation marks in script type causing syntax issues

### ISSUE THREAD

**Issue by daniel4ing** [microsoft/vscode#162542] opened 2022-10-03 06:23 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2/1.72
- OS Version: Windows 11

Steps to Reproduce:

1. If the script tag contains a type, the syntax highlighter stops working with the PHP tags inside the script tag.
2. If I remove the script type, it works again.
![ezgif-4-a4628634f4](https://user-images.githubusercontent.com/54732803/193512826-21463771-4c20-4118-973a-19b0563eb954.gif)

**Comment by aeschli** [comment] 2022-10-03 09:39
What is the language mode the editor is in? PHP or HTML?

**Comment by daniel4ing** [comment] 2022-10-03 10:04
Language mode is set to PHP, the version I'm currently using is 7.4 and the file is also a PHP file..

**Comment by roblourens** [comment] 2022-10-05 00:39
Our grammar is pulled from https://github.com/atom/language-php, which is no longer maintained. There are several open issues around embedded languages, similar to this. I am going to start closing PHP grammar issues against this issue, which tracks replacing our grammar https://github.com/microsoft/vscode/issues/162707

**Closed by roblourens** 2022-10-05 00:39 UTC
Labels: bug, php

**Comment by KapitanOczywisty** [comment] 2022-10-06 09:14
This is HTML issue, which is also not maintained and duplicate of #36280
