### ISSUE TITLE
Initializing JS/TS Language features dies in perpetuity

### ISSUE THREAD

**Issue by AbbottEverett** [microsoft/vscode#146473] opened 2022-03-31 20:13 UTC
Issue Type: <b>Bug</b>

- Have a project open with TypeScript 4.6.3.
- Open a .ts file and hover over a variable name to attemp to get intellisense. 
- TS Server will never start and you will get the following error:

"The TypeScript language service died 5 times right after it got started. The service will not be restarted."

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 14, 10|
|Memory (System)|32.00GB (3.29GB free)|
|Process Argv|--crash-reporter-id 67acdead-62a4-4bbd-8948-4df60fb5cc07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
vscode-markdownlint|Dav|0.46.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
gc-excelviewer|Gra|4.2.54
vscode-colorize|kam|0.11.1
unity-code-snippets|kle|1.3.0
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.1
vscode-typescript-tslint-plugin|ms-|1.3.3
code-spell-checker|str|2.1.11
gitblame|wad|8.1.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrc:30451274
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment] 2022-03-31 21:47
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by micleyman** [comment] 2022-04-04 16:59
Disabling the TSLint extension fixed this for me, after it started popping up a few days ago.
Looks like it's deprecated anyway.

**Comment by mandrade2** [comment] 2022-04-05 20:39
Awesome, was having the same problem and this fixed it for me. Thanks @micleyman !

**Comment by mjbvz** [comment] 2022-04-13 23:31
Closing as we need more info from the original poster but tslint is the most likely root cause

**Closed by mjbvz** 2022-04-13 23:31 UTC
Labels: needs more info
