### ISSUE TITLE
When writing a custom debug adapter, variables won't clear on the test client.

### ISSUE THREAD

**Issue by harold-b** [Microsoft/vscode#3382] opened 2016-02-24 05:50 UTC
I've been writing a custom debug adapter for vscode and have been running into the following issue:

When deploying your extension in server mode ( at least I haven't tested on extension host mode ), and the you drop stop the client abruptly, for any reason, whilst the front-end is still awaiting a request that affects the variables debug view, then even after the client has stopped, whatever values were in the view remain there and become locked. Starting a new debug session does not clear them, you have to open a new window with the project in order for them to clear.

These screenshots illustrate :

> While debugging on the client, at the same time I have the adapter project being debugger on server mode, and paused while there is still a scopesRequest or variablesRequest response unfulfilled.
<img src="https://cloud.githubusercontent.com/assets/11462418/13276706/90a40976-da98-11e5-94ec-646f19645ef0.gif" width="600" />

> I've stopped the server without completing the request. The client's variables view remains locked with whatever was last in it.
<img src="https://cloud.githubusercontent.com/assets/11462418/13276707/924df264-da98-11e5-810d-954ccbb5765e.gif" width="600" />

It's happened both in the January and insider's build.

**Comment by minggo** [comment] 2016-02-25 13:45
@harold-b
I am writing a debug adapter too, and can not show variables on the test client. I created #3455 for it. Could you please give me some advise?

Thanks.

**Comment by weinand** [comment] 2016-03-09 12:59
this is a duplicate of #3666

**Closed by weinand** 2016-03-09 12:59 UTC
