### ISSUE TITLE
Visual Studio Code - Insiders top bar not existed

### ISSUE THREAD

**Issue by liuliangsir** [Microsoft/vscode#53427] opened 2018-07-02 07:16 UTC
- VSCode Version: 1.25.0-insider(6ca99aca80e80224f1c0bd4370c6ec4941c3bc54 x64)
- OS Version: Win10 pro(17134.81)

Steps to Reproduce:

1. launch Visual Studio Code - Insiders
2. take a look at the top bar

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Here is a couple of screenshots

![image](https://user-images.githubusercontent.com/8049878/42149799-35ddc0f0-7e0a-11e8-93cf-bf517eb10c98.png)

As the title says, you could not see the tabs within the top bar, such as File, View and so on

**Comment by jrieken** [comment] 2018-07-02 07:45
cc @bpasero

**Comment by bpasero** [comment] 2018-07-02 09:04
@liuliangsir did you maybe configure your settings to hide the menu?

**Comment by liuliangsir** [comment] 2018-07-02 09:50
@bpasero you are absolutely right. Oddly enough, The following configuration item is appended to User Settings configuration file. But I am sure I never do that thing.

Here are some configuration items

```
 "window.menuBarVisibility": "visible"
```

**Comment by bpasero** [comment] 2018-07-02 09:58
@liuliangsir so if you remove that setting, everything should be fine?

**Comment by liuliangsir** [comment] 2018-07-02 10:17
@bpasero if I remove that setting(`"window.menuBarVisibility": "toggle"`) or change the value of `window.menuBarVisibility` to `visible`, everything is fine.

**Comment by bpasero** [comment] 2018-07-02 10:44
@liuliangsir so for which value do you think there is a bug then?

**Comment by liuliangsir** [comment] 2018-07-02 11:01
I have no idea. But I would like to say, After setting `"window.menuBarVisibility": "toggle"`, It appears not to work. Namely, I’m not sure the moment of `window.menuBarVisibility` toggled.

**Comment by bpasero** [comment] 2018-07-02 12:22
@liuliangsir `"window.menuBarVisibility": "toggle"` means you need to press the `Alt` key to show the menu. This is working as intended.

**Comment by sbatten** [comment] 2018-07-03 21:15
@liuliangsir Since the setting is working as intended, I will close this issue `as-designed`. If you find that the menubar visibility setting changes again without you doing so, please open a separate issue. thanks

**Closed by sbatten** 2018-07-03 21:15 UTC
Labels: as-designed
