### ISSUE TITLE
Color routine skip the function name token for SQL string's

### ISSUE THREAD

**Issue by dragahassan** [microsoft/vscode#103506] opened 2020-07-28 17:12 UTC
**Issue Type:** Bug.
**VS Code version:** Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
**Insider:** No.
**OS version:** Windows_NT x64 10.0.18363

It's not a big deal!, but it's seem the color routine skip the function name token for SQL string 
`"SELECT ... '" . myfunction() ." ... "`
while it's working fine for regular string (without SELECT).

![color_bug](https://user-images.githubusercontent.com/61518789/88698095-fa102a00-d0db-11ea-9be4-35d030050078.png)

See the screenshot.
Thank you,

**Comment by alexr00** [comment] 2020-08-27 15:08
Can you please provide a full copy/pastable example where the issue happens?

**Comment by dragahassan** [comment] 2020-08-27 15:16
Just like the screenshot

```
echo " ... '". foo() ."' ...";
echo " SELECT ... '". foo() ."' ...";
```

I'm using theme `Dark+ (default dark)`

**Comment by alexr00** [comment] 2020-08-31 14:54
Thanks for the example. It looks like the SQL scope is leaking.

![image](https://user-images.githubusercontent.com/38270282/91733592-03445900-ebaa-11ea-977f-545baf3e2fa8.png)

I think this is a duplicate of https://github.com/atom/language-php/issues/336

**Closed by alexr00** 2020-08-31 14:54 UTC
Labels: languages-basic, needs more info
