### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by lemaguilera** [microsoft/vscode#103201] opened 2020-07-23 20:58 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200717

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102521:161)
    at resolveModuleNamesWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102741:26)
    at resolveModuleNamesReusingOldState (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102891:19)
    at processImportedModules (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104314:35)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104050:17)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104284:21
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at processLibReferenceDirectives (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104279:16)
    at findSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:104047:21)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:85
    at getSourceFileFromReferenceWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103846:34)
    at processSourceFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103879:13)
    at processRootFile (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:103702:13)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:60
    at Object.forEach (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:102621:16)
    at synchronizeHostData (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143149:26)
    at Object.getProgram (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:143237:13)
    at InferredProject.Project.updateGraphWorker (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:148058:53)
    at InferredProject.Project.updateGraph (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:147991:42)
    at updateProjectIfDirty (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:149359:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151500:41)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:97
    at Object.flatMap (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:151773:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:152754:46)
    at /home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:88
    at IOSession.Session.executeWithRequestId (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154600:28)
    at IOSession.Session.executeCommand (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154609:33)
    at IOSession.Session.onMessage (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:154633:35)
    at Interface.<anonymous> (/home/hogar/.vscode/extensions/ms-vscode.vscode-typescript-next-4.0.20200717/node_modules/typescript/lib/tsserver.js:156848:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 x 2926)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|4.76GB (1.20GB free)|
|Process Argv|tkeron --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.5.1
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-deno|den|1.25.0
markdown-formatter|mer|0.8.8
xml-format|mik|1.0.2
csharp|ms-|1.22.1
vscode-typescript-next|ms-|4.0.20200717

</details>

**Comment by mjbvz** [comment] 2020-07-23 23:59
Duplicate of https://github.com/denoland/vscode_deno/issues/89

Caused by the deno extension

**Closed by mjbvz** 2020-07-23 23:59 UTC
