### ISSUE TITLE
Can't find microsoft's C/C++ Extension in marketplace

### ISSUE THREAD

**Issue by shaileshaanand** [microsoft/vscode#108704] opened 2020-10-15 03:05 UTC
I am unable to search and install microsoft's [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) on Archlinux's [code](https://www.archlinux.org/packages/community/x86_64/code/) package from official repo.
Searching for "C/C++" gives other results but not the microsoft one.
![vsc-1](https://user-images.githubusercontent.com/26682202/96072122-31170000-0ec1-11eb-870d-286411f850f2.png)
Searching for `@id:ms-vscode.cpptools` says "No extensions found".
![vsc-2](https://user-images.githubusercontent.com/26682202/96072130-35431d80-0ec1-11eb-9f42-c983172efedb.png)
Searching for `ms-vscode.cpptools` shows only Language Packs.

VS Code version: Code - OSS 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-07T20:28:07.702Z)
OS version: Linux x64 5.8.14-arch1-1

Steps to Reproduce:

1. Open Code - OSS
2. Goto Extensions
3. Search for C++ extension.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tamuratak** [comment] 2020-10-15 06:44
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by shaileshaanand** [comment] 2020-10-15 07:02
Looks like it is related to ArchLinux changing code-oss's marketplace to Open VSX.
The workaround mentioned in https://github.com/microsoft/vscode/issues/107997#issuecomment-703252446 works.

**Closed** 2020-10-15 07:02 UTC
