### ISSUE TITLE
bug in markdown syntax when line break included in emphasis

### ISSUE THREAD

**Issue by 18kimn** [microsoft/vscode#139470] opened 2021-12-19 15:36 UTC
Issue Type: <b>Bug</b>

```
*this whole sentence
should have italic formatting in vscode*

_this sentence 
should have it too_

**and this sentence should
be bolded**
```

But currently they show as regular text, and only when the entire string is placed on the same line does the formatting show up.

Here's a [commonmark](https://spec.commonmark.org/dingus/?text=*this%20whole%20sentence%0Ashould%20have%20italic%20formatting%20in%20vscode*%0A%0A_this%20sentence%20%0Ashould%20have%20it%20too_) link showing that this works, and two examples in the spec that have this formatting: [one](https://spec.commonmark.org/0.30/#example-422) [two](https://spec.commonmark.org/0.30/#example-493)

Github supports it too, so you could try it out on a comment.

Not a huge issue of course, since most parsers seem to support this syntax, but just nice to have editor highlighting for it too :)

VS Code version: VSCodium 1.62.3 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-08T22:09:41.030Z)
OS version: Linux x64 5.11.0-43-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (0.53GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
css-theme-completions|con|0.0.4
vscode-markdownlint|Dav|0.45.0
vscode-eslint|dba|2.2.2
gitlens|eam|11.7.0
prettier-vscode|esb|9.0.0
shell-format|fox|7.1.1
gc-excelviewer|Gra|4.0.45
r|Iku|2.3.4
path-autocomplete|ion|1.17.1
latex-workshop|Jam|8.22.0
vscode-edit-csv|jan|0.6.4
svg|joc|1.4.1
volar|joh|0.29.5
zotero|mbl|0.1.10
vscode-docker|ms-|1.18.0
vsliveshare|ms-|1.0.2902
color-highlight|nau|2.5.0
nebula-oni-theme|psu|1.4.0
marky-stats|rob|0.7.0
mdx|sil|0.1.0
svelte-vscode|sve|105.7.0
vscode-icons|vsc|11.8.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2022-04-06 22:05
Duplicate of https://github.com/microsoft/vscode-markdown-tm-grammar/issues/36

**Closed by mjbvz** 2022-04-06 22:05 UTC
Labels: bug, markdown, grammar
