### ISSUE TITLE
Typescript Intellisense slow when using yarn workspaces

### ISSUE THREAD

**Issue by charlie632** [microsoft/vscode#72690] opened 2019-04-21 23:52 UTC
- VSCode Version: 1.33.1 (User)
- OS Version: Window 10

Steps to Reproduce:

1. Created a simple Yarn workspaces project with nextjs
2. Intellisese was way too slow
3. Disabled all extensions. No improvement.
4. Reinstalled VSCode. Still, no improvement.
5. Switched to another project (Large project without Yarn Workspaces): Intellisense worked perfectly.

I used to work on a project with Lerna and was not having this kind of issue. Maybe is a yarn related issue?

Does this issue occur when all extensions are disabled?: Yes

**Comment by fabb** [comment] 2019-04-24 11:10
Our whole team experiences very slow indexing, autocompletion and code hinting for our TypeScript next.js project since updating to VSCode 1.33.1 as well. It worked multiple times faster in the previous version of VSCode. Something is wrong.

**Comment by codepunkt** [comment] 2019-04-26 08:54
I can confirm this. It is borderline unusable in the current version, i reverted back to 1.32.x

**Comment by fabb** [comment] 2019-04-26 10:18
Btw we don‘t use yarn but npm.

**Comment by fabb** [comment] 2019-04-26 11:16
Maybe related to #72472?

**Comment by fabb** [comment] 2019-04-26 11:30
Here is my collected performance data: 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    82	 99785	code main
    6	   213	 99787	   gpu-process
    0	   410	 99788	   window (theme.tsx — Yet Another Project Name)
    0	     0	   225	     /bin/bash -l
    0	    16	 39063	       npm
    0	     0	 39065	         sh -c ./local-proxy/run_proxy.sh && cross-env PORT=3002 npm run dev:no-proxy
    0	    16	 39093	           node /path/to/my/project/node_modules/.bin/cross-env PORT=3002 npm run dev:no-proxy
    0	    16	 39094	             npm
    0	    16	 39095	               node /path/to/my/project/node_modules/.bin/cross-env NODE_ENV=development nodemon ./server.ts
    0	    16	 39096	                 node /path/to/my/project/node_modules/.bin/nodemon ./server.ts
    0	   606	 39098	                   node /path/to/my/project/node_modules/.bin/ts-node -r tsconfig-paths/register --project tsconfig.server.json --files ./server.ts
    5	   311	 39419	                     /Users/me/.nvm/versions/node/v10.15.3/bin/node --max-old-space-size=2048 /path/to/my/project/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
    0	   164	 99789	   window (package.json — wh-components)
    0	     0	   689	     /bin/bash -l
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (somefile.js — Project Name)
|  Window (package.json — Other Project Name)
|  Window (theme.tsx — Yet Another Project Name)
|    Folder (Tealium_BBX_OEWA): 13 files
|      File types: js(6) json(5) gitignore(1) md(1)
|      Conf files: package.json(1) settings.json(1)
|    Folder (wh-components): 539 files
|      File types: html(128) js(122) svg(74) ts(62) tsx(51) less(47) json(13)
|                  xml(11) DS_Store(10) npmrc(2)
|      Conf files: package.json(2) gulp.js(1) jsconfig.json(1)
|                  tsconfig.json(1) tslint.json(1) webpack.config.js(1)
|                  launch.json(1) settings.json(1) tasks.json(1)
|    Folder (Yet Another Project Name): 497 files
|      File types: tsx(155) ts(86) less(58) js(39) svg(31) json(31) map(29)
|                  html(19) xml(11) jpg(6)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|10.4.3
scratchpads|bue|0.0.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.6.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.9.0
duplicate|gee|1.0.1
todo-tree|Gru|0.0.130
bats|jet|0.1.3
vscode-styled-components|jpo|0.0.26
intellij-idea-keybindings|k--|0.2.31
brittany|Max|0.0.6
vscode-less|mrm|0.6.3
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
vscode-docker|Pet|0.6.1
java|red|0.43.0
vscode-sort-json|ric|1.13.0
partial-diff|ryu|1.4.0
stylelint|shi|0.49.0
vscode-java-debug|vsc|0.18.0
vscode-icons|vsc|8.6.0
quokka-vscode|Wal|1.0.209
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
</details>

**Comment by mjbvz** [comment] 2019-04-26 17:31
@fabb Please open a separate issue to track your problem

@charlie632 Do you have `@types/styled` components installed under `node_modules`?  See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

**Comment by charlie632** [comment] 2019-04-26 17:40
@mjbvz I have `@types/styled-components`.

But I changed my monorepo out from yarn workspaces to a Lerna monorepo and the performance was significantly better. Below is my current pacakage.json.

```json
 "dependencies": {
    "@material-ui/core": "4.0.0-alpha.8",
    "@material-ui/styles": "4.0.0-alpha.8",
    "@zeit/next-typescript": "^1.1.1",
    "@zeit/webpack-asset-relocator-loader": "^0.4.1",
    "firebase": "5.7.1",
    "next": "^8.1.0",
    "next-compose-plugins": "^2.1.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-spring": "^8.0.19",
    "remcalc": "^1.0.10",
    "styled-components": "^4.2.0",
    "styled-theming": "^2.2.0"
  },
  "devDependencies": {
    "@types/next": "^8.0.3",
    "@types/react": "^16.8.14",
    "@types/react-dom": "^16.8.4",
    "@types/styled-components": "^4.1.14",
    "@types/styled-jsx": "^2.2.8",
    "babel-plugin-styled-components": "^1.10.0",
    "typescript": "^3.4.4"
  }
```

**Comment by mjbvz** [comment] 2019-04-26 17:47
When you changed repo structure, is it possible that you also installed a newer version of `@types/styled-components`. See DefinitelyTyped/DefinitelyTyped#34391 for a possible root cause of this

**Comment by charlie632** [comment] 2019-04-26 18:06
Let me see my old commits

**Comment by fabb** [comment] 2019-04-26 18:32
Thanks for the hint on `styled-components`, that might affect me too. I‘ll investigate some more before I create a new issue.
Unfortunately I‘m stuck with `@types/styled-components@4.1.8` because of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

**Comment by roniemeque** [comment] 2019-05-03 03:38
> Our whole team experiences very slow indexing, autocompletion and code hinting for our TypeScript next.js project since updating to VSCode 1.33.1 as well. It worked multiple times faster in the previous version of VSCode. Something is wrong.

Started having the same issue and fresh install/plugin cleaning didn't work, had to rollback to 1.30.

**Comment by Bobvantpadje** [comment] 2019-05-03 09:27
We're having the same issue. For us it's related to `@types/styled-components`. If we remove this package or rollback to VSCode 1.30 the intellisense is fast again.

**Comment by mjbvz** [comment] 2019-05-03 23:27
@Bobvantpadje Did you try updating to the latest @types/styled-components? see DefinitelyTyped/DefinitelyTyped#34391

**Comment by fabb** [comment] 2019-05-04 05:42
For our project, updating to the latest `@types/styled-components` did not help, just rolling back to 3.3 helped a bit.

**Comment by focux** [comment] 2019-05-19 00:47
For me, updating  `@types/styled-components` to `4.1.15` worked, thank you.

**Comment by mjbvz** [comment] 2019-05-21 18:00
@charlie632 Can you please test this again in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) too?

**Comment by imoby** [comment] 2019-05-22 03:15
Upgrading to the latest version of styled-components didnt work for me

**Comment by mjbvz** [comment] 2019-05-29 00:03
Closing as we need more info from the original poster.

Based on the description, this is like a duplicate of microsoft/TypeScript#30819

**Closed by mjbvz** 2019-05-29 00:03 UTC
Labels: needs more info
