### ISSUE TITLE
You cannot rename elements that are defined in a node_modules folder

### ISSUE THREAD

**Issue by yannxaver** [microsoft/vscode#161677] opened 2022-09-24 10:40 UTC
Type: <b>Bug</b>

1. Try to use F2 to rename a html tag (e.g. `<div>`) in a `.tsx` file.
2. See error 'You cannot rename elements that are defined in a node_modules folder'
3. Wonder if this is expected behavior or a bug? 
4. Google for results and find nothing - so assume bug
5. Turning off extensions did nothing

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id d6eba629-f8f7-40ca-acdb-c9c4fc057b7b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.13.0
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
classdiagram-ts|Ale|0.1.67
jsdoc-markdown-highlighting|bie|0.0.1
markdown-mermaid|bie|1.15.2
mermaid-markdown-syntax-highlighting|bpr|1.4.1
vscode-tailwindcss|bra|0.8.7
indented-block-highlighting|byi|1.0.7
path-intellisense|chr|2.8.1
vscode-github-actions|csc|0.24.2
vscode-mjml|Dan|2.4.10
search-under-cursor|Dav|0.1.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.2
prettier-vscode|esb|9.9.0
vscode-firefox-debug|fir|2.9.8
copilot|Git|1.46.6822
vscode-pull-request-github|Git|0.50.0
todo-tree|Gru|0.0.215
vscode-drawio|hed|1.6.4
customize-ui|ioc|0.1.64
monkey-patch|ioc|0.1.19
vscode-env|Iro|0.1.0
remove-comments-vscode|jin|1.0.6
svg|joc|1.4.20
open-in-vim|jon|0.6.0
i18n-ally|lok|2.8.1
rainbow-csv|mec|3.1.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.30
vsliveshare|ms-|1.0.5723
incrementor|nms|1.0.3
material-icon-theme|PKi|4.20.0
prisma|Pri|4.3.1
matchit|red|2.0.1
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.9
toggle-boolean|sil|0.10.0
vscode-bolt-language|smk|1.0.1
vscode-field-lights|sve|0.0.11
markdowntable|Tak|0.10.2
vsfire|tob|1.4.1
sort-lines|Tyr|1.9.1
learn-vim|vin|0.0.28
vim|vsc|1.23.2
volar|Vue|0.40.13
fig|wit|0.0.6
JavaScriptSnippets|xab|1.8.0
viml|Xad|2.1.2
luahelper|yin|0.2.19
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by mjbvz** [comment] 2022-09-26 16:14
Duplicate of #159534

**Closed by mjbvz** 2022-09-26 16:14 UTC
