### ISSUE TITLE
Create directory on opening directory

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode#137386] opened 2021-11-17 19:33 UTC
It would be great if a directory can be created while opening a directory.
Currently the user gets an error message that the specified directory doesn't exist.
Adding an action to quickly create that directory (and entering/selecting it) would be a nice timesaver.

**Comment by JacksonKearl** [comment] 2021-11-17 20:35
I'm not sure what you mean here, is this the native OS's folder picker? A screen recording would help.

\gifPlease

**Comment by strarsis** [comment] 2021-11-17 21:18
@JacksonKearl: Ah right. The WSL picker, not the native OS dialog.

**Comment by gjsjohnmurray** [comment] 2021-11-17 23:06
Related to #137368

**Comment by alexr00** [comment] 2021-11-18 08:35
Duplicate of #137368

**Closed by alexr00** 2021-11-18 08:35 UTC
Labels: needs more info
