### ISSUE TITLE
Scrolling markdown preview with touch doesn't work

### ISSUE THREAD

**Issue by lzybkr** [Microsoft/vscode#16236] opened 2016-11-29 18:57 UTC
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|vim|vscodevim|0.1.10|

---

Steps to Reproduce (probably requires touchscreen, maybe repros with a mouse?):

1. Open a markdown file
2. Open the preview to the side (Ctrl+K V)
3. Press and hold, then drag the markdown preview. It doesn't scroll. Scrolling works fine with up/down arrows though.

**Comment by mjbvz** [comment] 2016-12-01 02:00
Closing as duplicate of #16236

**Closed by mjbvz** 2016-12-01 02:00 UTC
Labels: bug, duplicate, webview
