### ISSUE TITLE
Markdown preview doesn't work on version 1.28.0-insider

### ISSUE THREAD

**Issue by NatoBoram** [Microsoft/vscode#58277] opened 2018-09-09 03:09 UTC
Issue Type: <b>Bug</b>

1. Open a `.md` file
2. Click on *Open Preview to the Side*

The preview loaded correctly a few minutes ago, before I updated. After the latest update, the preview doesn't load anymore.

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3468)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\natob\Documents\GitHub\Eldarya-Tax-Calculator|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.20
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.6.1
beautify|Hoo|1.4.2
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
Go|ms-|0.6.89
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.0
vscodeintellicode|Vis|1.0.3

</details>

**Comment by NatoBoram** [comment] 2018-09-09 03:12
Thank you bot, but it seems like you haven't found any duplicate. However, #2766 is a damn fine proposition.

**Comment by Astrantia** [comment] 2018-09-09 05:41
@mjbvz I was actually referring to this issue in #58118

**Comment by mjbvz** [comment] 2018-09-10 06:36
Duplicate of #58203

**Closed by mjbvz** 2018-09-10 06:36 UTC
Labels: insiders
