### ISSUE TITLE
Cannot open markdown preview on Edge

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#86468] opened 2019-12-06 11:05 UTC
This error in the console:
```
Refused to frame 'https://9c923512-20dc-4c2b-8db7-535cda8ac983.vscode-webview-test.com/0d728c31ebdf03869d2687d9be0b017667c9ff37/fake.html?id=9c923512-20dc-4c2b-8db7-535cda8ac983' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by bpasero** [comment] 2019-12-06 15:05
@mjbvz oh this might be the answer why you cannot reproduce, I am selfhosting on Edge!

**Comment by mjbvz** [comment] 2019-12-06 22:05
Duplicate of #86399

**Closed by mjbvz** 2019-12-06 22:05 UTC
