### ISSUE TITLE
`code-insiders --telemetry` not working

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#229864] opened 2024-09-26 18:01 UTC
![Image](https://github.com/user-attachments/assets/87d3527d-f20f-40cf-b245-ea15b47e71a3)

Not sure why, but `code-insiders --telemetry` returns an error for me. I'm on windows.
```
Version: 1.94.0-insider (user setup)
Commit: c43f508b732d24b0c4732de9db2b38b4c5b88b8a
Date: 2024-09-26T05:04:07.935Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by lramos15** [comment] 2024-09-26 18:04
@connor4312 Do you own the CLI and if so do you have any ideas?

**Comment by connor4312** [comment] 2024-09-26 18:18
Kind of 😛 

Not sure what's up here, I don't repro on my Windows machine also use a user install. This should be pretty deterministic, wonder if a update failed. Do other CLI commands work?

**Comment by andreamah** [comment] 2024-09-26 18:20
just tried `code-insiders --status` and it worked. Also, commands like `code-insiders --disable-extensions` that launch the editor also work.

**Comment by connor4312** [comment] 2024-09-26 18:25
Could you try running that command in JS debug terminal with "pause on caught exceptions" and "pause on uncaught exceptions" turned on to try and diagnose where that's coming from?

**Comment by bpasero** [comment] 2024-09-26 19:14
This looks like https://github.com/microsoft/vscode/issues/228043 which was fixed 2 weeks ago 🤔 . And btw I cannot reproduce with latest insiders. Any chance thats an old version?

**Comment by justschen** [comment] 2024-12-15 03:26
closing, but maybe @andreamah can let us know if she still sees this 👋🏻

**Closed by justschen** 2024-12-15 03:26 UTC
Labels: bug, author-verification-requested
