### ISSUE TITLE
Web: Path picker does not handle Enter correctly on Linux Firefox

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83575] opened 2019-10-29 19:04 UTC
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Chrome, before Enter:

![image](https://user-images.githubusercontent.com/4033249/67800214-27905000-fa44-11e9-8596-59602373529a.png)

Chrome, after Enter, `Desktop` is completed to the path with a slash, prompting more options:

![image](https://user-images.githubusercontent.com/4033249/67800241-2eb75e00-fa44-11e9-8ed8-61c2cbeeca32.png)

Firefox Linux, after Enter, `ext` is marked in red with white background. `extensions/` is not completed.

![image](https://user-images.githubusercontent.com/4033249/67800310-4989d280-fa44-11e9-979f-625a87998257.png)

**Comment by alexr00** [comment] 2019-10-30 08:44
duplicate of https://github.com/microsoft/vscode/issues/83292

**Closed** 2019-10-30 08:44 UTC
Labels: *duplicate, bug, firefox, simple-file-dialog, web
