### ISSUE TITLE
status bar overflow by extension description

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#87857] opened 2019-12-29 22:41 UTC
- VSCode Version: 1.41.1
- OS Version: 10.14.6

Steps to Reproduce:

1. Open the extension panel and choose an extension to show its description

Notice how the extension description appears above the status bar, partially hiding it.

![vscode-overflow](https://user-images.githubusercontent.com/199648/71563727-9c0f5b80-2a94-11ea-9fa9-637c6bcfc1cb.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-12-30 05:56
Duplicate of #83209

**Closed by mjbvz** 2019-12-30 05:56 UTC
