### ISSUE TITLE
Follow Link tooltip for urls in markdown files encode query string unnecessarily

### ISSUE THREAD

**Issue by jcmoore** [microsoft/vscode#108819] opened 2020-10-16 17:45 UTC
Issue Type: <b>Bug</b>

- Open a new file
- **(!important)** Set file type to Markdown
- Create a markdown link with a query string name-value pair containing an equals sign ("=") like `[example](https://www.example.com?encoded=unnecessarily)`
- Hover over the url (i.e. "https://www.example.com?encoded=unnecessarily") to engage the Follow Link tooltip
- Click "Follow link" link
- Observe that the browser address bar shows an encoded equals sign ("=") in the url (i.e. "https://www.example.com/?encoded%3Dunnecessarily")

I cannot reproduce this issue with online monarch-editor (https://microsoft.github.io/monaco-editor/index.html) if that helps.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (19.88GB free)|
|Process Argv|--crash-reporter-id 482ad8b0-81a6-4635-87db-d66b654487d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.145.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15

</details>

**Comment by andrew-maust** [comment] 2020-10-17 18:41
Hello, I would like to work on this bug. I have done a small amount of investigating so far, I am concluded that this only happens with the prompt and not when the command/control click shortcut is used. I also concluded that this only happens with markdown and not other extensions. This leaves me to believe that the issue lies within the "markdown-language-features" extension. I was hoping I might be able to get some guidance on how to find the code responsible for executing after the prompt is clicked on. I am thinking that I need to work on `openDocumentLink.ts` or `documentLinkProvider.ts` but from the debugging I have conducted so far I cant get any breakpoints to break. Thank you!

**Comment by jeanp413** [comment] 2020-10-20 04:40
I think this is a duplicate of https://github.com/microsoft/vscode/issues/106097

**Comment by peter-fb** [comment] 2020-11-18 12:21
YouTube links in Markdown don't longer work because of this bug. YouTube will redirect you to their homepage because it can't find the video.

**Comment by chenjigeng** [comment] 2020-12-16 17:49
The reason for this problem is that if you pass in a URI link, it'll call the toString function to display it .And the toString function of the URI will by default encode.
https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L372

![image](https://user-images.githubusercontent.com/14784326/102385844-4c110800-4009-11eb-8504-15d6f68f7fcc.png)
![image](https://user-images.githubusercontent.com/14784326/102386097-9a260b80-4009-11eb-8862-addbdfef05a7.png)
So is there a need for encode? If not, we can solve this problem by toString(true). @mjbvz 
![image](https://user-images.githubusercontent.com/14784326/102386373-f426d100-4009-11eb-85e2-7ddbc579a866.png)

**Closed** 2020-12-18 08:17 UTC
Labels: bug, help wanted, markdown
