### ISSUE TITLE
Add account function

### ISSUE THREAD

**Issue by Belive-pc** [Microsoft/vscode#35688] opened 2017-10-06 07:57 UTC
- VSCode Version: 1.17.0
- OS Version: windows 10 专业版

Steps to Reproduce:

1.When the development environment is changed, the editor configuration is changed and can only be configured again. It's better to be able to join accounts and synchronize settings,

2.It is hoped that you can synchronize the configuration and plug-ins of the editor

Reproduces without extensions: Yes/No

**Comment by Toxhorn** [comment] 2017-12-04 12:16
I've came here to do this request.
I dream with this functionality and I hope this will be implemented some day.

Thanks!!

**Comment by mjbvz** [comment] 2018-03-08 06:07
Duplicate of #2743

**Closed by mjbvz** 2018-03-08 06:07 UTC
Labels: config, feature-request
