### ISSUE TITLE
There is not a API to listen the scrolling of the activetexteditor

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#10055] opened 2016-08-03 02:04 UTC
- VSCode Version:1.3.1
- OS Version:win10

As the above ,the preview extension (like markdown preview) cannot achieve the Scroll Synchronization.
Any Help will be appreciated！！

**Comment by jrieken** [comment] 2016-08-04 07:35
Yes - such API does not exist yet

**Comment by jrieken** [comment] 2016-08-12 09:43
Closing this as duplicate of #588 which is about exposing the viewport and hence emitting scroll events etc

**Closed by jrieken** 2016-08-12 09:43 UTC
Labels: api, duplicate, feature-request
