### ISSUE TITLE
IntelliSense and error detection not working 

### ISSUE THREAD

**Issue by patchaminfantschool** [Microsoft/vscode#13575] opened 2016-10-12 08:07 UTC
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14931
- Extensions: ms-vscode.typescript-javascript-grammar-0.0.4

This build has removed all IntelliSense and error detection for me on both my surface pro 4 and workstation.
I have only tried .js and .ts but both broken 

I have uninstalled all plugins, reinstalled some , uninstalled Vscode and reinstalled it and still no joy.

this is not showing an error in javascript or Typescript file anymore
```
const tt = 'fff';
tt=44;
```
Vscode is now like using notepad for me/

Is there a way to get a previous version back?

**Comment by isidorn** [comment] 2016-10-12 08:11
Sounds like a regression, adding important to raise awarness

**Comment by dbaeumer** [comment] 2016-10-12 08:45
@patchaminfantschool which version have you updated from. The fact that you don't see errors in js files is due to the switch of using Salsa as our new JS lanaguag engine. However that switch happened a long time ago.

Using your test case as TS correctly reports an error for me:

![capture](https://cloud.githubusercontent.com/assets/1931590/19303329/81899db2-9068-11e6-848a-0b14d20e5f37.png)

To further understand what could cause this for you could you enable tracing to see what happens to the TS language service. Do so by adding `"typescript.tsserver.trace": "verbose"` to your workspace setting and restarting VSCode. Then go to the Output panel and select the TypeScript channel. Post the output here.

Mine is
```
[Info  - 10:44:32 AM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Trace - 10:44:32 AM] Sending request: open (0). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/13575/test.ts",
    "fileContent": "const tt = 'fff';\r\ntt=44;"
}
[Trace - 10:44:32 AM] Sending request: geterr (1). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "p:/mseng/VSCode/Playgrounds/bugs/13575/test.ts"
    ]
}
[Trace - 10:44:33 AM] Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/13575/test.ts",
    "diagnostics": []
}
[Trace - 10:44:33 AM] Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/13575/test.ts",
    "diagnostics": [
        {
            "start": {
                "line": 2,
                "offset": 1
            },
            "end": {
                "line": 2,
                "offset": 3
            },
            "text": "Left-hand side of assignment expression cannot be a constant or a read-only property."
        }
    ]
}

```

**Comment by patchaminfantschool** [comment] 2016-10-12 09:09
Hi thanks for your quick response,
here your are
```
[Info  - 10:03:45] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js
[Trace - 10:03:46] Sending request: open (0). Response expected: no. Current queue length: 0
Arguments: {
    "file": "c:/Dev/2016/brokenVSCode/app/index.ts",
    "fileContent": "const tt =='fff';\r\ntt=44;\r\n"
}
[Trace - 10:03:46] Sending request: geterr (1). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "c:/Dev/2016/brokenVSCode/app/index.ts"
    ]
}
```

**Comment by dbaeumer** [comment] 2016-10-12 09:27
This looks like a problem in the tsserver. It never send diagnostic results back hence we don't render any.

**Comment by dbaeumer** [comment] 2016-10-12 09:45
Could you please enable server logging as well by opening a terminal and setting the environment variable `TSS_LOG="-level verbose -file c:\tmp\server.log"`. Then start code from this terminal and provide the server.log file, You might need to adjust the path in the env. Thanks.

**Comment by patchaminfantschool** [comment] 2016-10-12 12:12
ran in powershell and got:

```
C:\dev\2016>TSS_LOG="-level verbose -file c:\tmp\server.log"
'TSS_LOG' is not recognized as an internal or external command,
operable program or batch file.
```
uninstalled Typescript via npm, uninstalled code then reinstalled code, got the error then opened up a new folder and it stopped working again!! then reinstalled typescript still no joy.

I seem to have tsserver installed, not that I know anything about it.
At the command line I typed tsserver then g and enter and get the following:
```
C:\dev\2016\Therm>tsserver
g
Content-Length: 803

{"seq":0,"type":"response","command":"unknown","request_seq":0,"success":false,"message":"Error processing request. Unex
pected token g in JSON at position 0\nSyntaxError: Unexpected token g in JSON at position 0\n    at Object.parse (native
)\n    at IOSession.Session.onMessage (C:\\Users\\phils\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\tsserver.
js:51745:36)\n    at Interface.<anonymous> (C:\\Users\\phils\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\tsse
rver.js:53940:27)\n    at emitOne (events.js:96:13)\n    at Interface.emit (events.js:188:7)\n    at Interface._onLine (
readline.js:239:10)\n    at Interface.<anonymous> (readline.js:376:12)\n    at Array.forEach (native)\n    at Interface.
_normalWrite (readline.js:375:11)\n    at ReadStream.ondata (readline.js:107:10)"}
```

**Comment by dbaeumer** [comment] 2016-10-12 12:53
@patchaminfantschool you need to set TSS_LOG as an environment variable in the terminal you use. If you use PowerShell then you need to do:
```
$env:TSS_LOG="-level verbose -file c:\tmp\server.log"
```
Then start code form the PowerShell command prompt on the workspace you see the issue.

And please don't forget to adopt c:\tmp\server.log to your environment as well.

**Comment by patchaminfantschool** [comment] 2016-10-12 14:04
Just tried it in visual studio, and that works fine, just thought I would try that instead.

here is the output from vscode and server.log

```
const tt =='fff';
tt=44;

tt='RRRR';
tt=55;
tt=false;
```
gives me

```
Info 0    request: {"seq":0,"type":"request","command":"open","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","fileContent":"const tt =='fff';\r\ntt=44;\r\n\r\ntt='RRRR';\r\ntt=55;\r\n"}}
Info 1    Search path: c:/Dev/2016/brokenVSCode/app
Info 2    Config file name: c:/Dev/2016/brokenVSCode/tsconfig.json
Err 3     Add recursive watcher for: c:/Dev/2016/brokenVSCode
Err 4     Add recursive watcher for: c:/dev/2016/brokenvscode/app
Err 5     Add recursive watcher for: c:/dev/2016/brokenvscode/test
Err 6     Exception on executing command {"seq":0,"type":"request","command":"open","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","fileContent":"const tt =='fff';\r\ntt=44;\r\n\r\ntt='RRRR';\r\ntt=55;\r\n"}}:
watch c:/dev/2016/brokenvscode/test ENOENT
Error: watch c:/dev/2016/brokenvscode/test ENOENT
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Object.watchDirectory (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:1651:32)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:52869:58
    at Object.reduceProperties (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:495:22)
    at ProjectService.openConfigFile (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:52865:61)
    at ProjectService.openOrUpdateConfiguredProjectForFile (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:52695:49)
    at ProjectService.openClientFile (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:52681:31)
    at IOSession.Session.openClientFile (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51346:46)
Info 7    response: {"seq":0,"type":"response","command":"open","request_seq":0,"success":false,"message":"Error processing request. watch c:/dev/2016/brokenvscode/test ENOENT\nError: watch c:/dev/2016/brokenvscode/test ENOENT\n    at exports._errnoException (util.js:1026:11)\n    at FSWatcher.start (fs.js:1439:19)\n    at Object.fs.watch (fs.js:1466:11)\n    at Object.watchDirectory (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:1651:32)\n    at c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:52869:58\n    at Object.reduceProperties (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:495:22)\n    at ProjectService.openConfigFile (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:52865:61)\n    at ProjectService.openOrUpdateConfiguredProjectForFile (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:52695:49)\n    at ProjectService.openClientFile (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:52681:31)\n    at IOSession.Session.openClientFile (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:51346:46)"}
Info 8    request: {"seq":1,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 9    Async elapsed time (in milliseconds): 0.4134
Info 10   request: {"seq":2,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":5,"offset":7,"endLine":5,"endOffset":7,"insertString":"\r\n"}}
Perf 11   Async elapsed time (in milliseconds): 0.2538
Info 12   request: {"seq":3,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 13   Async elapsed time (in milliseconds): 0.1508
Info 14   request: {"seq":4,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":1,"endLine":6,"endOffset":1,"insertString":"t"}}
Perf 15   Async elapsed time (in milliseconds): 0.1639
Info 16   request: {"seq":5,"type":"request","command":"completions","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":2}}
Err 17    Exception on executing command {"seq":5,"type":"request","command":"completions","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":2}}:
No Project.
Error: No Project.
    at Errors (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:50793:32)
    at ts.server.ts.server (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:50795:11)
    at ts (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51775:7)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51776:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
Info 18   response: {"seq":0,"type":"response","command":"completions","request_seq":5,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Errors (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:50793:32)\n    at ts.server.ts.server (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:50795:11)\n    at ts (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:51775:7)\n    at Object.<anonymous> (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:51776:3)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)"}
Info 19   request: {"seq":6,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":2,"endLine":6,"endOffset":2,"insertString":"t"}}
Perf 20   Async elapsed time (in milliseconds): 0.0458
Info 21   request: {"seq":7,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 22   Async elapsed time (in milliseconds): 0.0881
Info 23   request: {"seq":8,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":3,"endLine":6,"endOffset":3,"insertString":"="}}
Perf 24   Async elapsed time (in milliseconds): 0.1138
Info 25   request: {"seq":9,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 26   Async elapsed time (in milliseconds): 0.0855
Info 27   request: {"seq":10,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":4,"endLine":6,"endOffset":4,"insertString":"f"}}
Perf 28   Async elapsed time (in milliseconds): 0.0726
Info 29   request: {"seq":11,"type":"request","command":"completions","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":5}}
Err 30    Exception on executing command {"seq":11,"type":"request","command":"completions","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":5}}:
No Project.
Error: No Project.
    at Errors (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:50793:32)
    at ts.server.ts.server (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:50795:11)
    at ts (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51775:7)
    at Object.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib\tsserver.js:51776:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
Info 31   response: {"seq":0,"type":"response","command":"completions","request_seq":11,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Errors (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:50793:32)\n    at ts.server.ts.server (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:50795:11)\n    at ts (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:51775:7)\n    at Object.<anonymous> (c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\extensions\\typescript\\server\\typescript\\lib\\tsserver.js:51776:3)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)"}
Info 32   request: {"seq":12,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":5,"endLine":6,"endOffset":5,"insertString":"a"}}
Perf 33   Async elapsed time (in milliseconds): 0.0747
Info 34   request: {"seq":13,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":6,"endLine":6,"endOffset":6,"insertString":"l"}}
Perf 35   Async elapsed time (in milliseconds): 0.0484
Info 36   request: {"seq":14,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 37   Async elapsed time (in milliseconds): 0.0729
Info 38   request: {"seq":15,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":7,"endLine":6,"endOffset":7,"insertString":"s"}}
Perf 39   Async elapsed time (in milliseconds): 0.0534
Info 40   request: {"seq":16,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 41   Async elapsed time (in milliseconds): 0.0884
Info 42   request: {"seq":17,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":8,"endLine":6,"endOffset":8,"insertString":"e"}}
Perf 43   Async elapsed time (in milliseconds): 0.0686
Info 44   request: {"seq":18,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 45   Async elapsed time (in milliseconds): 0.0770
Info 46   request: {"seq":19,"type":"request","command":"change","arguments":{"file":"c:/Dev/2016/brokenVSCode/app/index.ts","line":6,"offset":9,"endLine":6,"endOffset":9,"insertString":";"}}
Perf 47   Async elapsed time (in milliseconds): 0.0470
Info 48   request: {"seq":20,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/Dev/2016/brokenVSCode/app/index.ts"]}}
Perf 49   Async elapsed time (in milliseconds): 0.0805
```

**Comment by dbaeumer** [comment] 2016-10-12 20:02
@patchaminfantschool does the workspace you have contain a tsconfig.json file ?

**Comment by dbaeumer** [comment] 2016-10-12 20:03
This seems to be a problem in the tsserver. Moving to the TS team.

**Comment by dbaeumer** [comment] 2016-10-12 20:04
This issue was moved to Microsoft/TypeScript#11568

**Closed by dbaeumer** 2016-10-12 20:04 UTC
Labels: important, js, needs more info, typescript

**Comment by dbaeumer** [comment] 2016-10-12 20:06
@patchaminfantschool please continue commenting here: Microsoft/TypeScript#11568 since this is a TS issue.
