### ISSUE TITLE
new siplit window should not replace current one

### ISSUE THREAD

**Issue by 956237586** [microsoft/vscode#140265] opened 2022-01-07 10:12 UTC
Issue Type: <b>Bug</b>

When using REST Client v0.24.6 execute http request by Ctrl + Alt + R, from second times, response result should always show in split window in right window, the feature has been broken by recent version updates, response result will replace current window now, please fix it.  downgrade vscode will be effective but it will auto upgrade default.

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.44GB free)|
|Process Argv|--crash-reporter-id e81b4973-7481-401b-a59b-14e3e58b1767|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
transformer|dak|1.12.0
xml|Dot|2.5.1
vscode-swan|efe|0.1.0
code-runner|for|0.11.6
vscode-javac|geo|0.2.39
vscode-drawio|hed|1.6.3
rest-client|hum|0.24.6
plantuml|jeb|2.17.0
prettify-json|moh|0.0.3
mongodb-vscode|mon|0.6.14
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.13
hexeditor|ms-|1.8.2
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.29.0
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
vscode-nginx-format|tec|0.0.6
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by 956237586** [comment] 2022-01-07 10:28
downgrade to below version  1.61.2   is effective, so the feature is broken between (1.61.2, 1.63.0]

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.45GB free)|
|Process Argv|--crash-reporter-id e81b4973-7481-401b-a59b-14e3e58b1767|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
transformer|dak|1.12.0
xml|Dot|2.5.1
vscode-swan|efe|0.1.0
code-runner|for|0.11.6
vscode-javac|geo|0.2.39
vscode-drawio|hed|1.6.3
rest-client|hum|0.24.6
plantuml|jeb|2.17.0
prettify-json|moh|0.0.3
mongodb-vscode|mon|0.6.14
vscode-docker|ms-|1.18.0
vscode-language-pack-zh-hans|MS-|1.63.3
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.0
jupyter|ms-|2021.11.1001550889
jupyter-renderers|ms-|1.0.4
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.13
hexeditor|ms-|1.8.2
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.29.0
java|red|1.2.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.2
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
vscode-nginx-format|tec|0.0.6
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.9
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.1
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.8.0
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.4.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-01-07 11:04
See https://github.com/Huachao/vscode-restclient/issues/940 where the extension author @Huachao points to #138914 as the likely cause. This is assigned to @mjbvz and scheduled to be fixed in the next VS Code release.

**Comment by mjbvz** [comment] 2022-01-11 20:18
Duplicate of #138914

**Closed by mjbvz** 2022-01-11 20:18 UTC
