### ISSUE TITLE
How to disable TypeScript for JS files

### ISSUE THREAD

**Issue by Kureev** [Microsoft/vscode#24582] opened 2017-04-12 08:44 UTC
Hi there,

I have `"javascript.validate.enable": false` in my config, but I still receive type suggestions (from TS?):

![img_2326-min](https://cloud.githubusercontent.com/assets/2273613/24949149/eb4d8270-1f6c-11e7-8a50-d2afe096c3c1.jpg)

- VSCode Version: 1.11.1
- OS Version: Sierra 10.12.4

**Steps to Reproduce:**

1. Disable validation
2. Open JS file
3. Hover variable / flowtype definition

**Desired outcome:**

- Display only flowtype suggestion (hide `Specification: (unknown)`)

**Comment by jrieken** [comment] 2017-04-12 08:50
You have disabled validation, not the hover

**Comment by Kureev** [comment] 2017-04-12 08:54
@jrieken If I disable hover at all, then I won't have flowtype hint

**Comment by jrieken** [comment] 2017-04-12 09:08
Is it that you want to disable the builtin TypeScript/JavaScript extensions? Or only a partial disablement?

**Comment by Kureev** [comment] 2017-04-12 09:12
As it outlined in the issue description, I want to get rid of `Specification: (unknown)` string at the bottom of the hint.

**Comment by jrieken** [comment] 2017-04-12 09:18
> Unfortunately it isn't obvious if this part of the hint relates to TS or any other built-in plugin.

I'd say neither because I don't find that string in our code base

**Comment by Kureev** [comment] 2017-04-12 09:21
That's strange, because I just run `code . --disable-extensions` and I still see the modal with type suggestions in javascript files.

**Comment by Kureev** [comment] 2017-04-12 09:24
Here is how it looks like:
![image](https://cloud.githubusercontent.com/assets/2273613/24950818/9210263a-1f72-11e7-8cd0-d44b28fd4b8b.png)

So seems it's a pre-built feature that I want to disable.

**Comment by jrieken** [comment] 2017-04-12 09:41
> Display only flowtype suggestion (hide Specification: (unknown))

Which is somewhat contradicting. The `hide Specification` isn't from TypeScript or another built-in extension. The `type Specification`-hover from the first screenshot is like the second screen shot from TypeScript. What do you want to disable?

**Comment by Kureev** [comment] 2017-04-12 10:01
Ok, now I understood my mistake here. I thought these notifications I got from the flow, not typescript. Therefore, I think disabling TypeScript is what I want for now. Is there an option / workaround for that?

**Comment by jrieken** [comment] 2017-04-12 10:20
>  Is there a way to do that?

Sorry, not yet but you aren't the first to ask

**Comment by jrieken** [comment] 2017-04-12 10:21
I am closing this as a dupe of #17068

**Closed by jrieken** 2017-04-12 10:21 UTC
Labels: needs more info
