### ISSUE TITLE
Auto import changed to dynamic import in JS ES6+

### ISSUE THREAD

**Issue by tobiastimm** [Microsoft/vscode#60847] opened 2018-10-13 17:28 UTC
- VSCode Version: 1.28.1
- OS Version: macOS Mojave

When I try to let vscode auto-import a js module, it imports the module in dynamic import syntax.

For example `Query` from the `react-apollo` module.

Before: 

`import { Query } from 'react-apollo`

Now: 

`import('react-apollo').Query`

Steps to Reproduce:

1. Open a .js file 
2. Let vscode auto-import a js module

Does this issue occur when all extensions are disabled?: Yes

**Comment by tiaaaa123** [comment] 2018-10-14 20:47
This issue is getting on my nerve! Is there a way to disabled it in the setting?

**Comment by barkermn01** [comment] 2018-10-15 11:34
Confirmed as occurring in Windows 1.28.1 and agree with @tiaaaa123 This is horrible behavior and needs some method to tell VSCode to use ES6 imports again.

**Comment by hamza-hajji** [comment] 2018-10-15 14:50
Is there any temporary solution while it's being fixed? I have to import everything manually now. Very frustrating

**Comment by jmsstudio** [comment] 2018-10-15 16:37
I have the same problem here, after the last update (versions 1.28 and 1.28.1) it stopped working
I tried using some extensions to do the job, but it conflicts with vscode import

I am using the OS Ubuntu 16.04

**Comment by Nick-Lucas** [comment] 2018-10-15 16:53
Also have this problem.

VSCode 1.28.0

I use auto-imports constantly so this is a real workflow breaker.

**Comment by mjbvz** [comment] 2018-10-15 18:36
Duplicate of #60216

Already fixed in insiders and we're looking into backporting a fix to a 1.28.2

**Closed by mjbvz** 2018-10-15 18:36 UTC
Labels: new release
