### ISSUE TITLE
Timeline does not work with directories that are setup as junctions

### ISSUE THREAD

**Issue by mprather** [microsoft/vscode#97109] opened 2020-05-07 00:01 UTC
- VSCode Version: 1.44.2
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. Setup a folder as a junction (mklink /j shortname longpath) of an existing folder
2. git clone a repo into the new folder
3. open a file from repo in vscode
4. View time line.

Result:
Timeline reports "no timeline information was provided"

Additional notes:
* If the git clone is created in a standard (non-junction) folder, timeline works properly. 
* junction-based folders are a common setup of our dev environments

Does this issue occur when all extensions are disabled?: Yes

**Comment by widoz** [comment] 2023-10-21 13:22
This would be really interesting. For instance, let's say you create a file in a directory, you don't commit / push the changes, you delete the file. You would expect that highlighting a folder Timeline would give you the history of the directory and the files that where in there in the past but that does not happen.

The only way you have to bring the history for certain files for a directory is to recreate the files but you might have forgot the name of the file and or you have files in multiple subdirectories.

**Comment by lszomoru** [comment] 2023-12-12 12:38
@mprather, are you still able to reproduce this issue since we have added support to open repositories that have a symbolic link on their path. I will go ahead and optimistically close this issue but please feel free to reopen it in case you are still able to reproduce the issue with the latest version of VS Code. Thanks!

**Closed** 2023-12-12 21:06 UTC
Labels: bug, timeline, timeline-git
