### ISSUE TITLE
sync settings

### ISSUE THREAD

**Issue by mshzsh** [microsoft/vscode#87822] opened 2019-12-28 19:48 UTC
**I have two suggestions for you:**

1. the settings of vscode be synced by email. Then when we use a new device we do not need to adjust the settings again.
2. Adding the shortcut key Ctrl + D for duplicate line (like pycharm).

**Comment by wizzard0** [comment] 2019-12-29 01:52
Can we use something like Git repo for this?

Would really like to avoid yet-another-account-to-register-and-maintain, and also to keep ability to sync settings over restricted corp networks

**Comment by IllusionMH** [comment] 2019-12-29 03:49
/duplicate of #2743 (already on draft of January iteration plan)

In the meantime you can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

As for shortcut: <kbd>Ctrl</kbd>+<kbd>D</kbd> is already assigned to another action since release, so it doesn't make any sense to break that.
You can always reassign it yourself or use https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings for most of Idea keybindings

**Closed** 2019-12-29 03:49 UTC
Labels: *duplicate
