### ISSUE TITLE
Integrated terminal's width not adjusted correctly when window is maximized

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#19378] opened 2017-01-25 16:13 UTC
- VSCode Version: 1.9.0-insider
- OS Version: Windows 10 14986

Steps to Reproduce:

1. Open VSCode (restored)
2. Open integrated terminal (I am using WSL Bash in it, not sure if it matters)
3. Maximize the window
4. Type a long line in the integrated terminal.

As a result, the line will wrap at that point where it would have wrapped in the non-maximized window, but it won't even wrap into the next line, but just start at the left side of the same line again.

Screenshot: https://i.imgur.com/XXy0nl5.png

Note that resizing the window while it is not maximized will work fine.

**Comment by mousetraps** [comment] 2017-01-26 01:13
Thanks for reporting! I can't seem to reproduce the issue, but looks like a duplicate of: https://github.com/Microsoft/vscode/issues/17609

**Closed** 2017-01-26 01:14 UTC
Labels: duplicate
