### ISSUE TITLE
Import is discarded by imports organizer despite being used

### ISSUE THREAD

**Issue by jagomf** [Microsoft/vscode#47305] opened 2018-04-06 10:21 UTC
Issue Type: <b>Bug</b>

1. Clone project in [github.com/jagomf/countries-map](github.com/jagomf/countries-map)
2. Open file (just use Ctrl + P) **countries-map.component.ts**
3. Use [Ctrl + Shift + P] > **Organize imports**

<b>Result</b>: One of the imports (`@jagomf/countrieslist`) is gone despite being used.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|Memory (System)|7.72GB (2.16GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment] 2018-04-06 18:32
Duplicate of https://github.com/Microsoft/TypeScript/issues/22743

Already fixed in TypeScript@next and will be fixed in next release of VS Code when we move organize imports out of preview. Follow these instructions to upgrade the current build to typescript@next: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2018-04-06 18:32 UTC
Labels: javascript
