### ISSUE TITLE
VS Code not showing files with errors in red in some folders

### ISSUE THREAD

**Issue by Jackilion** [microsoft/vscode#110184] opened 2020-11-08 18:00 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10

I'm working on a flutter project with VS Code. Today, VS code suddenly stopped highlighting files that contain errors in red, which is really annoying. Restarted everything, doesn't matter.

The funny thing is, files inside lib/Bloc/ do get highlighted, other lib/ folders don't. Any ideas?

Does this issue occur when all extensions are disabled?: It can't because there's no error analysis without the dart extension.

**Comment by isidorn** [comment] 2020-11-10 08:32
Sounds like a duplicate of https://github.com/microsoft/vscode/issues/110188
Due to file casing @jrieken

**Closed by isidorn** 2020-11-10 08:32 UTC

**Comment by jrieken** [comment] 2020-11-10 09:50
@isidorn Unsure... diagnostics from extensions are passed through the uri identity service and I believe the explorer is doing the same. With that both should talk about the same uri casing

**Comment by isidorn** [comment] 2020-11-10 09:52
Yeah, explorer is also using the `identityService`
@Jackilion do you maybe have a repository which we can clone and easily reproduce this?
