### ISSUE TITLE
Custom Editor, contribute to the context menu?

### ISSUE THREAD

**Issue by WaynePhillipsEA** [microsoft/vscode#128436] opened 2021-07-11 17:48 UTC
For my form designer custom editor, I was hoping to add commands to the right-click context menu, but this doesn't seem to be possible at the moment?   

<img width="790" alt="tb_formDesignerContextMenu" src="https://user-images.githubusercontent.com/25738109/125205086-6138d700-e278-11eb-9bc3-9097239498a2.png">

If you have no plans to allow us to contribute to this menu, can we at least disable it so that we can provide a custom version inside the webview?   At the moment, it doesn't appear to be possible to customize it, nor disable it.

**Comment by mjbvz** [comment] 2021-07-14 02:47
Duplicate of #54285

**Closed by mjbvz** 2021-07-14 02:47 UTC
