### ISSUE TITLE
CSS Emmet with percentage as unit doesn't show up in suggestion list

### ISSUE THREAD

**Issue by whatifhappen** [Microsoft/vscode#32277] opened 2017-08-11 03:23 UTC
- VSCode Version: 1.15.0
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. setting.json 
2. emmet.preferences css.unitAliases

Reproduces without extensions: Yes/No

The lastest version had removed emmet preference. emmet used to support setting `css.unitAliases` to custom unit variables like set the defualt `rem` to less recaculate variable `@rem`. For example: 
```
 "emmet.preferences": {
    "css.unitAliases": "p:%, r: / @rem"
  },
```

Then i type `w100p` and `tab` could expand to `width: 100%`;

How to accomplish this feature now?

**Comment by ramya-rao-a** [comment] 2017-08-11 05:01
@whatifhappen Thanks for logging the issue. 

I am making a list of commonly used emmet.preferences, so that I can propose the same to be supported by Emmet 2.0

Do let me know if there are any other preferences you use.

Until then, please use [user snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) or [custom emmet snippets](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_using-custom-emmet-snippets) for your most frequently used values.

**Comment by ramya-rao-a** [comment] 2017-08-11 05:48
@sergeche This can be implemented as addons correct? There are no css addons at the moment though.

**Comment by sergeche** [comment] 2017-08-11 07:29
Unit aliases are supported but not allowed to be customized yet: https://github.com/emmetio/css-snippets-resolver/blob/master/index.js#L11

Need an option to pass them to snippets resolver.

Also, as stated in original issue, `w100p` is broken in VS Code, as well as multiple values in CSS: `p10-5`, it works in Atom.

**Comment by ramya-rao-a** [comment] 2017-08-11 14:58
Thanks @sergeche 

I see what the problem is.

Running the `Emmet: Expand Abbreviation` command from the command pallet or via a keyboard shortcut expands `w100p` to `width: 100%`

But in the suggestion list that item gets filtered out by viscose's internal filtering system since `w100p` doesn't fuzzy match with `width: 100%`.

@whatifhappen Until I come up with a way to get around this, bind a keyboard shortcut for the emmet command `editor.emmet.action.expandAbbreviation` and use it when suggestion list doesn't give you expected emmet suggestion

**Comment by ramya-rao-a** [comment] 2017-08-11 15:00
The other 3 css units work as expected

![cssemmet](https://user-images.githubusercontent.com/16890566/29218884-28d076d6-7e6b-11e7-9da4-fe8a93b33151.gif)

**Comment by whatifhappen** [comment] 2017-08-14 07:32
Just before this version updated, css custom unit is working as expected, like this one:
`w100r` -> `width: 100 / @rem;'
![](https://ws2.sinaimg.cn/large/006tNc79gy1fijaaidivmg30ag01p0st.gif)

**Comment by ramya-rao-a** [comment] 2017-08-15 05:11
@sergeche I can add the option needed to customize the unit aliases. Would you prefer this option to be set via the `addon` or the `format` option?

**Comment by ramya-rao-a** [comment] 2017-08-15 05:12
@whatifhappen Customizing unitAlias is not supported in VS Code 1.15, but I'll get the feature in the Insiders soon.

**Comment by ramya-rao-a** [comment] 2017-08-30 23:35
Customizing the unit alias is now possible in the latest Insiders. See

`w100p` or an abbreviation using the percentage unit not showing up issue will be fixed in tonight's (Aug 31) Insiders

You can get the Insiders from https://code.visualstudio.com/insiders.

**Closed by ramya-rao-a** 2017-08-30 23:35 UTC
Labels: bug, emmet, new release
