### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by farhanhoti** [Microsoft/vscode#25307] opened 2017-04-25 15:50 UTC
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.1.9|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.9.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment] 2017-04-26 09:39
@farhanhoti Can you please provide some steps that we could try to reproduce?

**Comment by PunchyRascal** [comment] 2017-05-05 11:32
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393

Happening repeatedly after update to April update.

**Comment by kieferrm** [comment] 2017-05-06 00:23
@PunchyRascal Pls describe the setup when it happens in more detail. For example: Do you have a folder open when this happens? Is the folder a git repository? What files have you open? etc.

**Comment by PunchyRascal** [comment] 2017-05-06 06:58
A folder is open, which is a git repository, with some files open too.

**Comment by egamma** [comment] 2017-05-08 18:31
This looks like a duplicate of #26053, let's continue to collect information about this issue over there.

**Closed by egamma** 2017-05-08 18:31 UTC
Labels: duplicate, needs more info
