### ISSUE TITLE
No debug adapter, can not send 'terminate'

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#103522] opened 2020-07-28 22:52 UTC
Issue Type: <b>Bug</b>

Various issues after performing File|Save Workspace As...

To reproduce, use the following steps

- Open a Workspace
- With Debug UI docked, start
- Two C# sessions
- One Chrome client 
- Ensure debugging is working
- Go to File|Save Workspace As...
- Rename Workspace

Expected:

The running debug sessions should be shutdown. 

Actual:

- Chrome client is still running but entry in Debug dock is absent
- Terminate button for C# session displays message
**No debug adapter, can not send 'terminate'**

- Must now shutdown and restart VSCode

Note:
1. In previous releases of VSCode, changing the active workspace would terminate running sessions. I've come to rely on this behaviour -- has it changed?
2. I'm not sure if this is reproducible without docking the Debug UI, which has had its problems. 

---
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment] 2020-07-29 08:20
@dfdumaresq thanks for filling this issue. However let's try to destill it into smaller issues.
First of all docking the debug toolbar should have no effect on this.
Second can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please try to find a minimal reproducable steps for one of these issues. Once we tackle that we can look into the rest. Thanks

**Comment by dfdumaresq** [comment] 2020-07-29 16:28
@isidorn - thanks. I am unable to reproduce the issue with the vscode-insider. To clarify, after launching my debug sessions with the Debugger docked, I can switch workspaces and the running sessions are closed. No error message is displayed.

What to do now? I would like to switch to the insiders version to avoid this bug. However, it seems like a huge task to include all of my settings and extensions. 

Is it possible keep my original vscode and switch update channels? Or is there a way to import my settings and extensions into the insiders version?

**Comment by isidorn** [comment] 2020-07-29 16:56
@dfdumaresq you can also wait for the next vscode stable release.
Or ideally - you can disable your extensions one by one since probably one of the extensoins is causing an issue.

Since there is nothing we can do to fix this - since it works in insiders I will close this.

You can easily import your settings and extensions using settings sync. We should hit stable release soon I think.

**Closed by isidorn** 2020-07-29 16:56 UTC
Labels: debug, needs more info

**Comment by dfdumaresq** [comment] 2020-07-29 17:03
Sounds good, @isidorn. Unfortunately I was unable to reproduce with my original install this morning. At least I have options now. All the best.
