### ISSUE TITLE
JavaScript Intellisense stop working after +- 5 minutes of coding

### ISSUE THREAD

**Issue by Bram-Zijp** [Microsoft/vscode#46025] opened 2018-03-17 13:36 UTC
- VSCode Version: 1.21.0
- OS Version: Windows 10

Steps to Reproduce:

1. Work with JavaScript files
2. After +- 5 minutes the intellisense just keeps loading forever

Does this issue occur when all extensions are disabled?: Yes/No
No
When I disable all installed extensions from the Interface, restart the app, the issue does still occur.

**Comment by TurtleGamingFTW** [comment] 2018-03-17 14:30
I can second this while working in node.js

**Comment by zeloru** [comment] 2018-03-18 05:13
I encountered this problem too. Intellisense usually stoped after failing to complete `import module 'some-js-module'`

**Comment by physihan** [comment] 2018-03-19 06:31
me too,it may be disabled only in new version.

**Comment by stereokai** [comment] 2018-03-19 14:46
Happened to me since version 1.21.0. I thought I was going crazy - happy to see  it's not only me.

**Comment by TurtleGamingFTW** [comment] 2018-03-19 18:11
I installed @typed/node and it fixed it for me

**Comment by Bram-Zijp** [comment] 2018-03-19 18:20
I don't use TypeScript. I'd rather have TypeScript complete turned off/deinstalled

**Comment by TurtleGamingFTW** [comment] 2018-03-20 01:01
As far as I know, VSC uses typescript to do the intellisense

**Comment by Bram-Zijp** [comment] 2018-03-23 08:52
I also managed to break intellisense within 20 seconds doing some imports that are invalid.

**Comment by Bram-Zijp** [comment] 2018-03-26 22:45
@mjbvz 
Could I send you my log in private?

**Comment by mjbvz** [comment] 2018-03-26 23:01
Yes, you can either use the VS Code secure log uploader to upload your session logs:

1. With `"typescript.tsserver.log": "verbose"` enabled
1. Restart vscode
1. Reproduce the problem
1. Run `code --upload-logs` and follow instructions (`code-insiders --upload-logs`)
1. Share the log file ID

Or email it to me (matb at microsoft.com)

**Comment by sheetalkamat** [comment] 2018-03-30 21:35
@Bram-Zijp I am not sure from the tsserverlog you shared with @mjbvz  what the issue is. Does the tsserver log you shared had issue reproed? 

I noticed something odd in the log though:
Do you have any modules included that are actually symbolic links eg. installed using ```npm link``` The log shows some types are being resolved from typescript installation's node_modules folder getting resolved. 
```
Info 176  [0:42:15.137] DirectoryWatcher:: Added:: WatchInfo: [typescriptInstallationLocation/node_modules] 1 Project: yours jsconfig.json WatchType: Directory of Failed lookup locations in module resolution
```
Can you try getting me the log with ```"traceResolution": true``` in jsconfig file's compiler options.
Apart from this you can also try adding ```"preserveSymlinks": true``` in your jsconfig file's compiler options and see if that helps and reduces number of files in your project? (note that this may not be actually what you want but just to investigate this would help.

**Comment by sheetalkamat** [comment] 2018-03-30 23:13
More update:
Found this in the log:
```
Info 267  [0:42:17.859] Finishing updateGraphWorker: Project: yourproject/jsconfig.json Version: 1 structureChanged: true Elapsed: 2871ms
....
Info 274  [0:42:17.877] Project 'yourproject/jsconfig.json' (Configured) 0
Info 274  [0:42:17.878] 	Files (217)

.......

Info 2401 [0:42:32.416] Finishing updateGraphWorker: Project: yourproject/jsconfig.json Version: 21 structureChanged: true Elapsed: 4295ms <<<notice how the program size changed here and added so much time>>>
Info 2402 [0:42:32.416] Running: *ensureProjectForOpenFiles*
Info 2403 [0:42:32.416] Structure before ensureProjectForOpenFiles:
Info 2404 [0:42:32.416] Project 'yourproject/jsconfig.json' (Configured) 0
Info 2404 [0:42:32.417] 	Files (1811)
```

I think we are including too many d.ts files for your unresolved imports: 

Can you try this with ```"maxNodeModuleJsDepth": 1``` and ```"maxNodeModuleJsDepth": 0``` in the compiler options and see if the issue gets resolved. I think adding these files is the cause of your issue.

**Comment by Bram-Zijp** [comment] 2018-03-31 07:53
@sheetalkamat 
In the previous log I actually managed to hit the lag within 5 seconds of typing unexisting imports. The project has allot of node_modules. The src, my workarea, is still fairly small. My computer is pretty beefy for what it mathers.

I notice when I write some bad imports the lag fades away after 20-30 seconds. The issue also has occured after working for an hour, writing perfectly fine code and having no response from the intellisense at all. It does get less nowadays.

I just uploaded my logs using the code-insiders --upload-logs ; ID: 659668248

Gonna work today, will upload logs when/if I get the permanent lag.

jsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "experimentalDecorators": true,
        "maxNodeModuleJsDepth": 1
    },
    "traceResolution": true,
    "include": ["src/**/*"]
}
```

**Comment by Bram-Zijp** [comment] 2018-03-31 11:54
I managed to freeze the intellisense completely. The log should be huge but full of data. It froze at the end. Before that it sometimes froze temporary which was resolved after waiting for 30 sec while CTRL + Space was pressed.

jsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "experimentalDecorators": true
    },
    "traceResolution": true,
    "include": ["src/**/*"]
}
```

Log ID:  3704565005

**Comment by sheetalkamat** [comment] 2018-04-02 23:21
@Bram-Zijp Thank you for the logs. I am looking into them and will keep you posted.

**Comment by andreasgruenh** [comment] 2018-04-06 06:37
This could be the same problem as mentioned (here)[https://github.com/Microsoft/TypeScript/issues/23183]

**Comment by mjbvz** [comment] 2018-04-17 22:32
@Bram-Zijp Were you able to share the project code? Please also try testing this in typescript@next to see if @sheetalkamat's PR fixed the issue: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by byteskw** [comment] 2018-04-18 09:39
me to, im using react native for my vscode, after 2 minutes - 10 minutes always infinite loading my intellisense vscode,

please fix this

**Comment by Bram-Zijp** [comment] 2018-04-18 11:40
@mjbvz The TypeScript v ^2.9.0-dev.20180418 does not help.
@sheetalkamat How can I hand over a project in private?

**Comment by benduran** [comment] 2018-04-18 16:32
I can concur that this issue has been plaguing VSCode for me for the past few weeks on both the Stable and Insiders builds. I decided to check the TypeScript output, to see what the engine is trying to do when it fails, and I received the following stack trace dump in the console:

```
[Error  - 9:28:28 AM] 'occurrences' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.isThrowStatement (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:10556:21)
    at aggregateOwnedThrowStatements (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70331:20)
    at aggregateOwnedThrowStatements (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70335:171)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70359:29
    at visitNodes (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:13224:30)
    at Object.forEachChild (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:13423:24)
    at NodeObject.forEachChild (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83853:23)
    at flatMapChildren (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70358:18)
    at aggregateOwnedThrowStatements (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70337:58)
    at getReturnOccurrences (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70530:24)
    at useParent (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70324:56)
    at getHighlightSpans (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70288:28)
    at getSyntacticDocumentHighlights (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70279:34)
    at Object.getDocumentHighlights (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:70258:118)
    at getDocumentHighlights (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:84767:42)
    at Object.getOccurrencesAtPosition (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:84752:31)
    at IOSession.Session.getOccurrences (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:91217:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90823:61)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92147:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92138:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92147:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92167:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:93368:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

For the record, I'm not using TypeScript at all in my project, or any of my other projects when this issue occurs.

**Comment by sheetalkamat** [comment] 2018-04-18 17:55
@Bram-Zijp you can email it to shkamat at microsoft dot com

**Comment by sheetalkamat** [comment] 2018-04-18 17:56
@benduran Having the tssever log from your session would help in diagnosing the issue.  https://github.com/Microsoft/vscode/issues/46025#issuecomment-376310837 mentions how to get the logs.

**Comment by pocesar** [comment] 2018-05-06 18:40
for me it stops working with:

```
[Error  - 13:56:05] 'completions' request failed with error.
Error processing request. Debug Failure. .
Error: Debug Failure. .
    at isValidTrigger (C:\nodejs\node_modules\typescript\lib\tsserver.js:72949:37)
    at Object.getCompletionsAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:71415:38)
    at Object.getCompletionsAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:87545:35)
    at IOSession.Session.getCompletions (C:\nodejs\node_modules\typescript\lib\tsserver.js:94234:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\nodejs\node_modules\typescript\lib\tsserver.js:93281:61)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:94726:88
    at IOSession.Session.executeWithRequestId (C:\nodejs\node_modules\typescript\lib\tsserver.js:94717:28)
    at IOSession.Session.executeCommand (C:\nodejs\node_modules\typescript\lib\tsserver.js:94726:33)
    at IOSession.Session.onMessage (C:\nodejs\node_modules\typescript\lib\tsserver.js:94746:35)
    at Interface.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsserver.js:95951:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mjbvz** [comment] 2018-05-07 16:04
@pocesar That is an unrelated issue and should be fixed in the next vscode insiders

**Comment by mjbvz** [comment] 2018-05-08 22:26
Closing this issue since we haven't heard back

The latest VSCode insiders builds have fixed a few similar issues. If you are still seeing this problem, please open a new issue

**Closed by mjbvz** 2018-05-08 22:26 UTC
Labels: javascript, needs more info

**Comment by foxbunny** [comment] 2018-05-17 06:01
I've run into this with three of the recent releases. 

I use Jest (previously with TypeScript, now with Babel/ES6). I've got over 400 tests that, when executed, use quite a bit of CPU (100% usage on all of the 8 threads). While test are running, the entire OS generally becomes less responsive, which is understandable.

When the tests are run in the built-in terminal, JavaScript language service stops working soon after the tests are started. This is especially true if many tests are breaking (e.g., because I break some dependency that is used in many places). When I run the tests in the command prompt, the language service runs in the exact same scenario. This is nothing scientific, just an observation.

**Comment by brownbl1** [comment] 2018-05-24 12:45
I'm seeing this pretty consistently as well under the same circumstances listed above. Maybe as a workaround, I've found that restarting the language service works without restarting vscode itself.

![image](https://user-images.githubusercontent.com/2136925/40486278-d3e54e76-5f2e-11e8-975a-572f4d59be43.png)

**Comment by foxbunny** [comment] 2018-05-24 13:17
Yeah, restarting the TS server works, while a bit annoying. Stragely, when intellisense stops working, it stops working for all the things, including snippets. I've disabled all extensions and will see how it goes. Will report here with the findings.

**Comment by foxbunny** [comment] 2018-05-26 18:49
I've used vs code with all exts disabled. Then enabled extensions one by one. ESLint seems to be the one causing intellisense issues. I've heard there'd been an update, so I'll give it another spin next week.

@TurtleGamingFTW, look up documentation about the JavaScript language service in vs code. It doesn't normally work out of the box.

**Comment by stereokai** [comment] 2018-05-27 09:53
@foxbunny what are you referring to?

**Comment by foxbunny** [comment] 2018-05-27 10:06
@stereokai If you mean the "not work out of the box" bit, I'm referring to the JS language service mentioned [here](https://code.visualstudio.com/Docs/languages/javascript).
