### ISSUE TITLE
Can't redo after saving the file.

### ISSUE THREAD

**Issue by eliot36** [Microsoft/vscode#19881] opened 2017-02-03 22:22 UTC
- VSCode Version: 1.9.0
- OS Version: Win 10

Hello All,

I'm not sure it did happen also in 1.8.0 version, but I just realized this issue after I updated to 1.9.0.
I frequently edit the code back and forth for check up the result of changes from the web browser.
I **undo** some part and **save** it, then check the browser. I want to **redo** after it, but I can't redo anymore after saving it.

It doesn't matter how many steps I undo it. It happens with even single undo/redo as well. I tried to remove personal setting in **setting.json** and **re-setup** the whole VS code also does not solve the problem at all. I'm going to test with downgrading VS code to 1.8.0, but I asked to my friend who has Mac is okay with both version.

Is anyone know why this happen? It makes me freak out that I lost lot of code before I post this. =\

**Comment by bpasero** [comment] 2017-02-04 07:45
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by eliot36** [comment] 2017-02-05 07:44
I think you are right. I removed all the personal settings including files and folders in Windows user folder which contains the extensions I installed ( Sadly, I already did this before I saw your comment =( Thanks for letting me know the better way to do it. ).

Anyways, the editor back to normal and I re-setup the extensions, but this guy ([**htmltagwrap**](https://marketplace.visualstudio.com/items?itemName=bradgashler.htmltagwrap)). All this happening occurred after set up this guy I think.

**Comment by bpasero** [comment] 2017-02-05 08:02
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Closed by bpasero** 2017-02-05 08:02 UTC
Labels: needs more info
