### ISSUE TITLE
Save dialog under Linux/GNOME does not show files that do not have an extension

### ISSUE THREAD

**Issue by akilan27** [microsoft/vscode#152793] opened 2022-06-21 20:39 UTC
Version: 1.68.1 ( 30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z )
OS: Linux x64 5.13.0-41-generic (Ubuntu Focal, running GNOME desktop)

Steps to Reproduce:

1. Press Ctrl+S on a new file or Ctrl+Shift+S on an open file
2. navigate to a folder with files that do not have extensions (eg: Dockerfile, Makefile)
3. The file dialog would not show the files without extension.

Note that this issue does not occur under KDE. I haven't tested it under other desktops.
Note 2: File open dialog does show all the files.

**Comment by bpasero** [comment] 2022-06-22 04:32
Duplicate of https://github.com/microsoft/vscode/issues/107246 ?

**Comment by akilan27** [comment] 2022-06-22 20:54
It seems related but I don't think this bug is same as that one. This bug occurs on save dialog whereas the 'hidden files reset' bug is on the open dialog. I don't see any Electron bug for this or the other bug. If it is indeed Electron issue I'm happy to open a bug report on their repo.

**Comment by deepak1556** [comment] 2022-12-13 13:10
Unable to repro with latest stable `1.74`

**Closed by deepak1556** 2022-12-13 13:10 UTC
Labels: upstream, linux, electron, native-file-dialog
