### ISSUE TITLE
Cannot drag and drop files from File Explorer to VSCode - Windows 11

### ISSUE THREAD

**Issue by Kentakoong** [microsoft/vscode#139773] opened 2021-12-26 16:54 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 11

Steps to Reproduce:

1. Drag and drop files from file explorer to VSCode

**Comment by JacksonKearl** [comment] 2022-01-04 05:05
Duplicate of #164

**Closed by JacksonKearl** 2022-01-04 05:05 UTC
