### ISSUE TITLE
Git File Discard Changes Button Not Present

### ISSUE THREAD

**Issue by mhermher** [microsoft/vscode#79239] opened 2019-08-15 17:59 UTC
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
Can't reproduce

Does this issue occur when all extensions are disabled?: Yes

In one case in a repo, the 'Discard Changes' Button in the Git window next to the changed files does not appear. Not does it appear in the context menu. It only allows me to stash or stage. 

![no-revert](https://user-images.githubusercontent.com/10067803/63114981-10fd5100-bf4b-11e9-9cd2-43b304311e9c.png)

In other repos, I have this option:

![yes-revert](https://user-images.githubusercontent.com/10067803/63115016-1d81a980-bf4b-11e9-9917-5bdee3655150.png)

I made changes to the same repo on a mac version, and the button does appear. So it seems something either specific to the Windows version or possible the state of my git repo on my Windows machine. I haven't found any indication for why that button would not appear. 

I am able to revert the changes from command line (git checkout ...), and I am also able to revert on a 'block-by-block' basis inside the editor using the controls there (clicking on the green indicators on the left edge of the changes, etc.). 

It might have something to do with the existence of sub-modules in this repo (throwing out a guess), since that changes the appearance of the git window. If there is a bug, it may be related to that.

**Comment by mhermher** [comment] 2019-08-15 18:21
Additional information. There are errors in the git output window. Pasted below. This might be possibly be related to how I cloned the repo. I cloned a non-master branch directly, then updated the submodule on a branch called 'master'. Not sure if that is related at all to the complaints about 'ambiguous master' in the error log.

Looking for git in: C:\Program Files\Git\bin\git.exe
Using git 2.22.0.windows.1 from C:\Program Files\Git\bin\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: c:\Users\mherm\git\ibn-ibn
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git show :IBN/R/api.R
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
Failed to watch ref 'c:\Users\mherm\git\ibn-ibn\.git\refs\remotes\origin\master', is most likely packed.
Error: ENOENT: no such file or directory, watch 'c:\Users\mherm\git\ibn-ibn\.git\refs\remotes\origin\master'
	at FSWatcher.start (internal/fs/watchers.js:164:26)
	at Object.watch (fs.js:1232:11)
	at Object.t.watch (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:6950)
	at E.updateTransientWatchers (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:97463)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:227)
	at T.updateModelState (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:114843)
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: c:\Users\mherm\git\ibn-ibn\IBN\tests\canon
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git check-ignore -v -z --stdin
> git rev-parse --show-toplevel

I'm going to try just recloning directly onto master and see if that makes a difference.

**Comment by mhermher** [comment] 2019-08-15 18:48
A couple of updates. That submodule was never actually cloned. The git submodule update failed for some authentication reason, so I just cloned it directly into another location and forgot about the submodule. It does not seem related though. 

Additionally, it seems like re-cloning fixed the issue, but I am totally sure why. I can't really reproduce. 

re-cloning : works as expected
re-cloning --branch non-master : works as expected
re-cloning --single-branch --branch non-master : works as expected

I didn't mess with the submodules though. I don't know. You can close the ticket if you would like, unless you can figure something out from that git output. The issue seems related to my git state. 

Still seems like a bug to me though that the button disappears even though the action it would perform is still allowed. I can't reproduce though, so I'll let you guys decide if you want to keep it open. Willing to trying other things if it would help.

**Comment by ZxBing0066** [comment] 2019-08-16 08:24
I have the same problem

**Comment by joaomoreno** [comment] 2019-08-30 11:34
@mhermher The error is not related.

Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by mhermher** [comment] 2019-09-04 23:23
Hi Joao, the issue persists with the Insider version. Opening the same repo, the button does not appear.

Version: 1.39.0-insider (system setup)
Commit: 109add76dad3dd1cbe05215d26cb62be6dbfdc47
Date: 2019-09-04T05:26:28.454Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment] 2019-09-05 11:38
Can you reproduce with `code --disable-extensions`?

**Comment by mhermher** [comment] 2019-09-06 18:45
Can reproduce with code --disable-extensions
Can NOT reproduce with other repos.

**Comment by joaomoreno** [comment] 2019-09-10 09:39
Hm.. can you try to find out what's special about that repository that you can't reproduce this in other repositories?

**Comment by mhermher** [comment] 2019-09-10 17:16
I'm really not sure and not sure I know enough about git to figure it out. I don't think it is something in the repository per se, but rather the state it is in. Particularly because re-cloning the repo in a separate location fixes the problem. I have just been working there, but keep this broken version for the sake of this ticket. The git status looks totally normal. I'm willing to try anything you can think of, but I am sort of at the limit of my understanding of git. 

I took a look at the git config of the two clones to see if there are any differences. For documentation:

- Bad version
cloned with SourceTree
cloned directly into non-master branch
tried to clone submodules, but broke for some authentication reason

- Good version
cloned with git clone ... from terminal (PS)
cloned into master
did not do anything with submodules

I was having trouble with submodules (which might be related to this issue??), so I was messing around with SourceTree to see if it could do it. I don't remember all my exact steps, but it was something like the above.

Anyway the differences in the git config -l are the following:

remote.origin.url
is of the form https://myusername@.... in the bad version
is of the form git@... in the good version

the bad version has a bunch of entries of the form
submodule.REPONAME/X/Y.active (all set to `true`)
submodule.REPONAME/X/Y.url (all set to some form of `git@...)

The order for a couple of things was different, but I don't think that means anything. There is one duplicate entry : `core.symlinks=false`. Not sure why it is duplicate (in both repos), but don't think it matters.

Otherwise, they are the same. Not sure if there are any hints in any of the things I said.

**Comment by rcjsuen** [comment] 2019-09-11 17:52
I can also reproduce this with `code --disable-extensions` on 1.38.

**Comment by joaomoreno** [comment] 2019-09-13 08:01
> Particularly because re-cloning the repo in a separate location fixes the problem.

I would just with this workaround for now and leave the ticket here in case more people hit it.

@rcjsuen Does the issue also go away for you when re-cloning the repo?

**Comment by rcjsuen** [comment] 2019-09-13 15:11
@joaomoreno I haven't tried but it appears to apply to all the Git repositories in my VS Code workspace. I'll just also point out that I'm not using submodules or anything of that nature.

**Comment by joaomoreno** [comment] 2019-09-17 07:21
@rcjsuen If you use the `Developer: Show Developer Tools`, can you inspect the DOM and see if the action is there but the icon is just missing?

**Comment by 1475142232** [comment] 2019-09-17 07:39
> @rcjsuen If you use the `Developer: Show Developer Tools`, can you inspect the DOM and see if the action is there but the icon is just missing?

Don't know why again good，Thank you all the same.

**Comment by rcjsuen** [comment] 2019-09-17 13:00
@joaomoreno No, the action is not there.
```HTML
<div class="monaco-icon-label file-icon xxx.py-name-file-icon py-ext-file-icon ext-file-icon python-lang-file-icon monaco-decorations-style-8"
    title="~/xxx/xxx.py • Untracked">
    <div class="monaco-icon-label-description-container">
        <a class="label-name">xxx.py</a>
        <span class="label-description">customer-router</span>
    </div>
    <div class="actions">
        <div class="monaco-action-bar animated">
            <ul class="actions-container" role="toolbar">
                <li class="action-item" role="presentation">
                    <a class="action-label icon menu-item-action-item-icon-7" role="button" title="Open File" tabindex="0"></a>
                </li>
                <li class="action-item" role="presentation">
                    <a class="action-label icon menu-item-action-item-icon-6" role="button" title="Stage Changes" tabindex="0"></a>
                </li>
            </ul>
        </div>
    </div>
</div>
```

**Comment by 1475142232** [comment] 2019-09-18 00:16
> @rcjsuen If you use the `Developer: Show Developer Tools`, can you inspect the DOM and see if the action is there but the icon is just missing?

<div
  class="monaco-icon-label file-icon index.js-name-file-icon js-ext-file-icon ext-file-icon javascript-lang-file-icon monaco-decorations-style-11"
  title="D:\pro">
  <div class="monaco-icon-label-description-container"><a class="label-name">index.js</a><span
      class="label-description">pro</span></div>
  <div class="actions">
    <div class="monaco-action-bar animated">
      <ul class="actions-container" role="toolbar">
        <li class="action-item" role="presentation"><a class="action-label icon menu-item-action-item-icon-9"
            role="button" title="打开文件" tabindex="0"></a></li>
        <li class="action-item" role="presentation"><a class="action-label icon menu-item-action-item-icon-8"
            role="button" title="暂存更改" tabindex="0"></a></li>
      </ul>
    </div>
  </div>
</div>

It's not going to work.

**Comment by 1475142232** [comment] 2019-09-18 00:21
> @rcjsuen 
It's not going to work.

menu-item-action-item-icon-7
menu-item-action-item-icon-8
The two icons used

**Comment by joaomoreno** [comment] 2019-09-18 09:21
@rcjsuen Thanks! Can you try to run with a different `--user-data-dir`?

**Comment by rcjsuen** [comment] 2019-09-18 17:14
@joaomoreno Sadly, it didn't help.

From what I can tell, it's available in the beginning and in the top of `SOURCE CONTROL: GIT` I can see a blue line moving and moving. Then when it's done it they disappear. So I would say within 30 seconds of booting up they go away.

I have about 30 Git repositories in my one VS Code workspace.

**Comment by cha0s** [comment] 2019-09-19 06:18
I have this same issue, only in one workspace. In other workspaces it works fine.

I have the same `Failed to watch ref '[...]/.git/refs/remotes/origin/master', is most likely packed.
Error: ENOENT: no such file or directory, watch '[...]/.git/refs/remotes/origin/master'` error in my logs.

**Comment by cha0s** [comment] 2019-09-19 06:28
I think I cracked it. The other error: 

```
git rev-parse master
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I also had this in my logs. I had 4 repos in my workspace. Running `git rev-parse master` in all of them narrowed it down to a single one that threw that error on the command line. At least in my case, **the reason this happened is because the repo was `git init`d but had nothing actually added or committed to the repository**.

Once I removed that repo's folder from my workspace and restarted vscode, the discard button reappeared.

@rcjsuen can you try following the same steps to determine which exact repo is causing this and check whether it's a repo that has been `git init`d but had nothing added or committed to it?

Either way, that's one way you can repro this issue.

**Comment by joaomoreno** [comment] 2019-09-20 07:32
The revert action can't show if there aren't yet any commits in the current branch. Glad to know you've found the cause.

**Comment by cha0s** [comment] 2019-09-20 08:00
You closed this prematurely. **This bug removes the revert icon from ALL repositories in the workspace, not just the empty one**.

**Comment by rcjsuen** [comment] 2019-09-20 11:02
@joaomoreno Please reopen this. As @cha0s mentioned, this issue causes the icon to be removed from all the repositories.

**Comment by joaomoreno** [comment] 2019-09-20 18:31
Oh! My bad 👍 will investigate. Thanks for the ping @cha0s & @rcjsuen

**Comment by mhermher** [comment] 2019-09-20 18:40
Just to check in on this. The solution makes sense for me. The main repo that is open does indeed have commits in it. It is the submodules that are problematic after all, since they did not clone properly.

**Closed** 2019-09-23 10:00 UTC
Labels: bug, git

**Comment by joaomoreno** [comment] 2019-09-23 10:01
Verification:

1. Have a workspace with two folders: one git repo (A) and one non git repo (B)
2. Run `git init` on the B folder
3. Select repo A in the SCM view
4. The Discard Changes action should be visible
