### ISSUE TITLE
Setting Cmder.exe as integrated shell still opens in separate window

### ISSUE THREAD

**Issue by jjacode** [Microsoft/vscode#12006] opened 2016-09-14 07:44 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. In user settings add `"terminal.integrated.shell.windows": "C:\\Program Files (x86)\\cmder\\Cmder.exe",`
2. Press `ctrl` + `backtick`
3. Notice Cmder opens in separate window after trying to open in integrated spot.

**Comment by Tyriar** [comment] 2016-09-14 17:42
cmder is a full-blown terminal emulator, not a psuedo terminal/shell which is what you need to specify there. Think of it that cmder is basically what the VS Code integrated terminal is, you cannot attach VS Code's integrated terminal to cmder for example. So this is a duplicate of #6935

I think [Clink](https://mridgers.github.io/clink/) is cmder's underlying shell, however I believe there are some issues with using Clink and git bash which make it less than ideal such as #7345

**Closed by Tyriar** 2016-09-14 17:42 UTC
Labels: integrated-terminal

**Comment by jjacode** [comment] 2016-09-15 02:22
@Tyriar, thank you for that explanation. That makes more sense.

**Comment by popey456963** [comment] 2017-04-19 21:21
@Tyriar @jjacode Reference the bash executable within Cmder and you appear to get the full Cmder shell, for example:

    terminal.integrated.shell.windows": "C:\\Users\\Popey\\Downloads\\Cmder2\\vendor\\git-for-windows\\bin\\bash.exe",

**Comment by JCMais** [comment] 2017-04-20 01:38
@popey456963 worked perfectly here. Thank you.

**Comment by jjacode** [comment] 2017-04-20 06:30
@popey456963 Thanks! That worked for me as well!

**Comment by Jarvid** [comment] 2017-05-22 09:31
This is approach only running the git bash and missing some of cmders settings. Giving me some problems with the the codeset and other things. If you want the full cmder shell as you are used to, set the following in the settings(of course adapt you paths and choose the 32bit cmd.exe if required):

 `   "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\cmd.exe",
    "terminal.integrated.shellArgs.windows" : ["/K","C:\\cmder\\vendor\\init.bat"]
`

Thanks a lot @thinkOfaNumber. 
Without his post in http://stackoverflow.com/questions/43363254/in-visual-studio-code-how-do-you-inject-clink-into-the-integrated-terminal I would never have known, I have to pass the arguments in this way.

**Comment by thinkOfaNumber** [comment] 2017-05-23 01:16
You're welcome, thanks for the attribution! Feel free to upvote the SO post if you think it's useful ;-)

**Comment by Morkowski** [comment] 2017-06-15 21:00
There is also different trick - opening your text editor in cmder ;) https://medium.com/@WMorkowski/protip-integrating-cmder-with-text-editor-7f08a6e76de7

**Comment by johnkors** [comment] 2017-07-13 08:56
I only get cmder / clink to work OK inside Code if I launch Code from cmder _first_. Launching Code directly and navigating to the integrated terminal just gives me Clink errors. Any idea..? Looks like the path to clink is wrong somehow when launching Code directly from the start menu.

Terminal output when launching Code
```
Generating clink initial settings in C:\config\settings
Additional *.lua files in C:\config are loaded on startup.
The system cannot find the path specified.
Creating intial aliases in C:\config\aliases
File not found - C:\config\aliases
```

**Comment by kemotoe** [comment] 2017-07-15 14:56
@johnkors I was having the same problem. Create a file in the root of your cmder folder "whatever".bat. I named mine vscode.bat. With the following code.
`@echo off`
`SET CMDER_ROOT=C:\cmder` (your path to cmder)
`"%CMDER_ROOT%\vendor\init.bat"`

Then in your vscode settings add the following to your settings.json

`"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\cmd.exe",`
`"terminal.integrated.shellArgs.windows": ["/K", "C:\\cmder\\vscode.bat"]`

Works perfect for me now

**Comment by johnkors** [comment] 2017-07-17 08:02
Confirmed working! Thanks, @kemotoe !

**Comment by Cipfahim** [comment] 2017-07-17 14:36
@popey456963 Thank you man :) it's working.

**Comment by Tyriar** [comment] 2017-07-17 16:16
Locking so solutions don't get buried.

**Comment by Tyriar** [comment] 2018-09-12 01:05
Updates:

- There's an official guide on our website for configuring the cmder shell: https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows
- Cmder also has one on their wiki https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration
