### ISSUE TITLE
Associate vscode editor to an account

### ISSUE THREAD

**Issue by boussadjra** [microsoft/vscode#80312] opened 2019-09-04 10:12 UTC
I would like if we could associate a google or microsoft account to own vscode editor in which we could save our preferences when we change the environment.

**Comment by IllusionMH** [comment] 2019-09-04 12:31
/duplicate of #2743

In mean time you can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

If you are sure that this is not a duplicate - please provide details.

**Closed** 2019-09-04 12:31 UTC
Labels: *duplicate
