### ISSUE TITLE
JavaScript auto import suggestions not working with new files (sometimes)

### ISSUE THREAD

**Issue by Jiia** [microsoft/vscode#129031] opened 2021-07-20 08:13 UTC
**Summary:**

Javascript auto-import suggestions only seem to work reliably for files that existed when the project was created. Sometimes they do not work at all from and inside files that were created after the project was opened. The issue has been going on for at least a year and is also happening for all of my colleagues who use macOS.

Does this issue occur when all extensions are disabled?: Yes

**Steps to Reproduce:**

1. Open a project that already has a file `existing.js` in project root that contains `export const doFirst = () => null`
2. From the VScode explorer create a new file `new.js` in project root
3. In `new.js` Start typing `doFir`
4. Remove what you were typing
5. Add `export const doSecond = () => null` in `new.js`
6. In `existing.js` start typing `doSeco`

**What should happen:**

Auto-import suggestions work on steps 3  and 6 every time.

**What actually happens:**

Auto-imports are not always suggested on steps 3 and 6. Auto import suggestions from and inside new files seems to be broken about 50% of the time you open a project in VScode. If the issue did not manifest, close the project, remove `new.js` and try doing the steps again.

During testing this issue, I found that the issue manifests less often if you first create a new export in `existing.js` and only then do steps 2-6.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (2.26GB free)|
|Process Argv|. --disable-extensions --crash-reporter-id 6a2be834-0dba-4d89-927b-d316ac578072|
|Screen Reader|no|
|VM|0%|

**Comment by mjbvz** [comment] 2021-07-20 15:32
Please try collecting the TS Server log for this:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log`  that can help us investigate this


 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Jiia** [comment] 2021-07-26 10:27
@mjbvz Hey! After fully closing all other projects running on my machine I couldn't reproduce the minimal test case anymore. The error reproduces reliably with any of the bigger projects I have so I obtained the TS server log for one of the big projects.

However since it's private project I would not want to share the tsserver.log publicly.

**Comment by mjbvz** [comment] 2021-07-29 20:12
Ok, can you share the logs privately? You can email them to matb at microsoft

**Comment by Jiia** [comment] 2021-08-03 13:04
Sent the logs last week by email.

**Comment by mjbvz** [comment] 2021-08-05 23:56
Thanks for the logs. I'll look at them with the TypeScript team but can you also please test in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) to make sure this issue has not already been fixed. The insiders build has a new version of TypeScript with a few fixes for auto imports

**Comment by mjbvz** [comment] 2021-08-16 21:45
Did you get a chance to test in insiders? It should be using TypeScript 4.4

**Comment by Jiia** [comment] 2021-08-17 06:18
I will get a chance to test it next week, sorry for the delay.

**Comment by mjbvz** [comment] 2021-09-27 22:45
Closing as we need more information to investigate this further. There wasn't anything obvious in the logs but if you are still seeing this, try it again using TypeScript@next  by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Closed by mjbvz** 2021-09-27 22:45 UTC
Labels: needs more info, javascript

**Comment by jespertheend** [comment] 2021-11-05 09:04
I can reproduce this in Insiders. I'll create a new issue since this one is closed.
