### ISSUE TITLE
No names helper when inside string template

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#35616] opened 2017-10-05 09:01 UTC
- VSCode Version: lasts insiders
- OS Version: Windows 10

Not sure if it is vscode of TS issue:

Whey you just type you get helpers about variables that satisfy.
![image](https://user-images.githubusercontent.com/736697/31218401-9dc12088-a9d3-11e7-9e91-65d6300bcc24.png)

But when you type inside string template you get no such helper, not very convenient.

![image](https://user-images.githubusercontent.com/736697/31218534-11d16294-a9d4-11e7-8a7a-afa91d51e121.png)

**Comment by mjbvz** [comment] 2017-10-09 18:15
Duplicate of https://github.com/Microsoft/vscode/issues/34857

As a workaround, you still should be able to manually trigger suggestions using <kbd>ctrl</kbd><kbd>space</kbd>

**Closed by mjbvz** 2017-10-09 18:15 UTC
Labels: duplicate, typescript
