### ISSUE TITLE
Please support large files in VS Code editor

### ISSUE THREAD

**Issue by IvanBorek** [Microsoft/vscode#25610] opened 2017-04-28 08:46 UTC
Please enable VS Code to open large files (e.g. size about 100 MB).  It is needed for  working with log files (in debugging and tuning activities). The support for binary files would be appreciated as well. Thank you. Ivan

- VSCode Version: 1.11.2
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Open a large text file 
2. You will get message "The file will not be displayed in the editor becouse it is either binary, very large or uses an unsupported text encoding." insted of the file's content.

**Comment by kieferrm** [comment] 2017-05-01 20:58
This is a duplicate of #6474.

**Closed by kieferrm** 2017-05-01 20:58 UTC
