### ISSUE TITLE
Installing Extensions behind proxy fails

### ISSUE THREAD

**Issue by digitaldrummerj** [Microsoft/vscode#2260] opened 2016-01-25 23:47 UTC
On Windows, when I am behind a proxy server I am able to get the list of possible extensions to install but every time I try to install one of them it gives an error that it can't find the proxy server.  

Note in the error message that I replaced the real address with the text proxyAddress.  I did notice that some of the message has the port number appended twice.  

I tried using both the system environment variable for http_proxy and https_proxy as well as setting it just in the VS Code settings.json file.   Same error on both.

```
getaddrinfo ENOTFOUND proxyAddress:911 proxyAddress:911:911: Error: getaddrinfo ENOTFOUND proxyAddress:911 proxyAddress:911:911,    at errnoException (dns.js:25:10),    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

About screen version info:

![image](https://cloud.githubusercontent.com/assets/708423/12568443/2ddf7a7c-c383-11e5-94ee-9bf0287b0de5.png)

**Comment by vilinski** [comment] 2016-01-26 10:36
workaround available [here] (https://github.com/Microsoft/vscode/issues/69#issuecomment-168948274)

**Comment by joaomoreno** [comment] 2016-01-26 10:49
Thanks @vilinski.

Duplicate of #69.

**Closed by joaomoreno** 2016-01-26 10:49 UTC
