### ISSUE TITLE
Running a cell affects (and doubles) the undo stack

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117945] opened 2021-03-02 04:35 UTC
In this Gif, I pressed undo 8 times (since I ran the cell 4 times) to get back to the actual editor undo. You can see the counter in `[]` update for each undo stop.

![notebook](https://user-images.githubusercontent.com/641685/109598089-907b5280-7ae6-11eb-8404-afed5da1945b.gif)

**Comment by rebornix** [comment] 2021-03-02 15:04
This is a typical thing to happen but we should explore how to improve it

* Users run cell
* Kernel resets execution count
* Kernel sets start time
* Kernel sets run state finsih
* Kernel sets execution count

For every edit, kernel applies workspace edit, which will introduce a unique undo point, which makes undo hard as users have to go through every change, even if it's invisible or less-noticeable.

**Comment by rebornix** [comment] 2022-12-30 02:30
Execution state is now out of metadata so we will have fewer undo/redo points. However users might still have multiple undo/redo points as there might be multiple cell model updates within one single execution. Maybe we could consider merging all of them before execution finishes. Leaving it to @roblourens .

**Comment by roblourens** [comment] 2022-12-30 20:15
Model updates for what? Output updates won't be undoable

**Comment by DonJayamanne** [comment] 2024-12-17 00:05
Duplicate of https://github.com/microsoft/vscode/issues/207523

**Closed by DonJayamanne** 2024-12-17 00:05 UTC
Labels: under-discussion, notebook-undo-redo
