### ISSUE TITLE
Unable to select a desired keyboard shortcut due to keyboard layout

### ISSUE THREAD

**Issue by jansensan** [Microsoft/vscode#9751] opened 2016-07-26 08:57 UTC
- VSCode Version: Version 1.3.1 (1.3.1)
- OS Version: 10.10.5 (14F1808)

Steps to Reproduce:

- Have a French Canadian keyboard
- Go to Preferences > Keyboard Shortcuts
- Look for this shortcut:
```
{ "key": "cmd+/",                 "command": "editor.action.commentLine",
                                             "when": "editorTextFocus" }
```
- Try to use the desired shortcut (`cmd + /`), shortcut doesn't work because keyboard layout takes precedence over actual keycode.

I am trying to change the "editor.action.commentLine", however the keys are already appropriate. Upon further investigation, the editor detects my keyboard (French Canadian) and forces "⌘+é" rather than the displayed (and desired) "⌘+/"

![image](https://cloud.githubusercontent.com/assets/1410355/17131893/a9477b70-531f-11e6-93df-64df70ff62af.png)

How can I force the editor to use "⌘+/" instead? The "é" key is totally not what I want to use, and if I type "/", no change occurs. Is there a way to force the use of a keycode rather than the character the key types?

**Comment by zhmur** [comment] 2016-08-01 19:06
Think it's duplicate of #7723.

**Comment by tobia** [comment] 2016-08-02 11:10
@zhmur I don't think this should be considered a duplicate of #7723, because that issue explicitly mentions "multiple keyboards layouts configured in OS," while this bug happens even with a single keyboard layout configured in the OS.

@jansensan has a French Canadian keyboard. In my case I installed Programmer Dvorak on OS X [following these instructions](http://www.kaufmann.no/roland/dvorak/macosx.html) (including the piece of bash code to force it to be the only layout installed in the OS.) I logged out and back in, and in fact it is the only layout selected in Input Sources:

![screen shot 2016-08-02 at 12 59 57](https://cloud.githubusercontent.com/assets/48756/17326357/263f6e9e-58b1-11e6-924a-be5fb2427378.png)

Then I proceeded to open VS Code and found that this bug is still there in the keyboard shortcuts:

![screen shot 2016-08-02 at 13 02 48](https://cloud.githubusercontent.com/assets/48756/17326405/74fe8d94-58b1-11e6-87a0-323b04907215.png)

If I type `"cmd+,"` (or leave it there from the defaults) **that's what I want to type,** not some other random combination, such as ⌘w (which is particularly inappropriate, being the shortcut used to close the current editor.)

**Comment by tobia** [comment] 2016-08-02 11:25
By the way, the docs have an [entire section](https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts) devoted to this "feature." Honestly, I cannot see how this could be considered a feature and not a bug.

I tried using the "Define Keybinding widget" mentioned there (⌘K ⌘K) but both ⌘-comma and ⌘W generate `"cmd+w"`, so that's hopeless too.

**Comment by jansensan** [comment] 2016-08-02 11:28
After reading @tobia's comments, I wanted to make sure I indeed had only the French Canadian keyboard in my setting, and indeed I do:

![image](https://cloud.githubusercontent.com/assets/1410355/17326939/faee5e54-58b4-11e6-894c-6704219c5d2e.png)

**Comment by jansensan** [comment] 2016-09-12 14:16
May I ask what would be the status for this?

**Comment by thierryskoda** [comment] 2016-10-05 15:03
+1

**Comment by alexandrudima** [comment] 2016-10-05 15:59
We don't ship with keyboard layout based keybindings yet. That is tracked in #1240

In the meantime you can define your keybindings as you wish by pressing the key combination you wish:

![comment-line](https://cloud.githubusercontent.com/assets/5047891/19121082/7082fc36-8b25-11e6-9ff8-56c27d086ed8.gif)

**Comment by jansensan** [comment] 2016-10-09 21:59
@alexandrudima Is this (`⌘+K`) a new command in the custom keybinding file? It wasn't there when I started this issue. With that feature, I was able to get what I needed. When typing what I actually want to use as a shortcut (`⌘+/`) it entered `"key": "cmd+numpad_divide"`, which allows me to work as I expect.

@tobia Would this feature also help you? If so, I would say this could allow to close the issue.

**Comment by alexandrudima** [comment] 2016-10-27 20:06
@jansensan Yeah, it's there since a long time ... maybe a year already :)

:+1: Let's close for now.

There's also an entire page on keyboard shortcuts and quite a large section on keyboard layouts at http://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts

**Closed by alexandrudima** 2016-10-27 20:06 UTC
Labels: keybindings
