### ISSUE TITLE
Extension appears twice when limited in restricted mode and virtual workspaces

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#129628] opened 2021-07-27 21:14 UTC
Testing #129421

When in a virtual workspace the "TypeScript and JavaScript Language Features" extension appears in both the `Limited in Restricted Mode` and `Limited in Virtual Workspaces` sections:

![Screen Shot 2021-07-27 at 1 47 44 PM](https://user-images.githubusercontent.com/51720070/127228064-13fa40e2-c7fd-4c7c-be3d-aec6ced2f80c.png)

**Comment by lszomoru** [comment] 2021-07-28 18:54
This is expected behaviour as limitations for restricted mode, and virtual workspaces is being tracked independently. For example the TypeScript extension has different limitations depending on the environment (you can access these in the hover):
* restricted mode - The extension requires workspace trust when the workspace version is used because it executes code specified by the workspace.
* virtual workspace - In virtual workspaces, resolving and finding references across files is not supported.

**Closed by lszomoru** 2021-07-28 18:54 UTC
Labels: workspace-trust
