### ISSUE TITLE
When can you support Microsoft account login, please

### ISSUE THREAD

**Issue by Ryuurock** [Microsoft/vscode#43153] opened 2018-02-08 02:00 UTC
I want to sync my Settings and extension

**Comment by V-ed** [comment] 2018-02-08 03:34
There is already an extension that does exactly that using your own GitHub Gists : [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync).

**Comment by mjbvz** [comment] 2018-02-08 09:06
Duplicate of #2743

**Closed by mjbvz** 2018-02-08 09:06 UTC
Labels: extensions
