### ISSUE TITLE
.JS files no longer open as Javascript after latest update

### ISSUE THREAD

**Issue by mostergaard** [Microsoft/vscode#11878] opened 2016-09-12 11:13 UTC
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open a .js file
2. In the bottom-right corner it appears as "Plain Text"
3. If I click on the "Plain Text" link and choose "Configure File Association for '.js'" a settings.json tab appears. I can click save, but it doesn't appear to have any effect.

So now I need to manually choose "JavaScript" for each .js file I open.
The project I work with also have JavaScript React files (.jsx) and they correctly open as React.

This used to work with the previous version and only started appearing as I upgraded to 1.5.1.

**Comment by mostergaard** [comment] 2016-09-12 11:17
I solved it. I deleted the settings.json in %appdata%\Code\User with the current contents:

// Place your settings in this file to overwrite the default settings
{
        "files.associations": {"*.js": "JavaScript"}
}

**Comment by mostergaard** [comment] 2016-09-12 11:33
I seems that it should be "javascriptreact" and not "JavaScript React" in the settings.json. That was not clear to me. Maybe previous versions just ignored this and resolved to the default association, whereas the new version goes to "Plain text".

**Comment by polizz** [comment] 2016-09-12 16:17
Thanks, that also fixed it for me.

Prefer the old naming convention personally...

**Comment by mostergaard** [comment] 2016-09-13 07:27
Yeah, so do I. That's the name you see in the UI. I found the new name only when editing the file in Code with IntelliSense.

**Comment by bpasero** [comment] 2016-09-13 13:13
You should not need to associate any *.js to JavaScript as this is the default. Remove that association and you should be good. Closing.

Also I cannot reproduce with this setting:
```

"files.associations": {
		"*.js": "javascript"
	}
```

**Closed by bpasero** 2016-09-13 13:13 UTC

**Comment by mostergaard** [comment] 2016-09-13 13:46
I think my problem was different casing of "javascript" - I had previously written "JavaScript", which had seemed to work with previous versions. So this might have been a breaking change with this new version.

**Comment by polizz** [comment] 2016-09-13 13:59
In my case, I associate JSX files to Javascript React, otherwise interpolated strings are not color coded deeply enough for my tastes.
