### ISSUE TITLE
Outline becomes scrambled when Markdown file has at least 11 subheaders

### ISSUE THREAD

**Issue by ansiblejunky** [Microsoft/vscode#63040] opened 2018-11-13 17:11 UTC
- VSCode Version: 1.29.0
- OS Version: MacOS 10.14

Steps to Reproduce:

1. Save the provided markdown text to `test.md`
2. Notice the outline is scrambled up and in the wrong order. But if you remove 1 header from the file, the outline is correct. It appears we need 32 headers to produce this problem. 

Does this issue occur when all extensions are disabled?: Yes, this is caused by the internal markdown reader.

Load the following markdown text to reproduce the problem:
```
# Test Outline Bug

## 1

## 2

## 3

## 4

## 5

## 6

## 7

## 8

## 9

## 10

## 11

## 12

## 13

## 14

## 15

## 16

## 17
test

## 18

## 19

## 20

## 21

## 22

## 23

## 24

## 25

## 26

## 27

## 28

## 29

## 30

## 31

## 32
```

Should result in the following outline
![image](https://user-images.githubusercontent.com/14311849/48430389-127fbb80-e724-11e8-8532-e251f380f7a5.png)

**Comment by ansiblejunky** [comment] 2018-11-13 17:36
It seems it happens even with 11 subheadings. 
```
# Test Outline Bug

## 1

## 2

## 3

## 4

## 5

## 6

## 7

## 8

## 9

## 10

## 11
```

Result in outline...
![image](https://user-images.githubusercontent.com/14311849/48431801-79eb3a80-e727-11e8-944e-97eeee345601.png)

**Comment by jrieken** [comment] 2018-11-14 07:59
/duplicate of https://github.com/Microsoft/vscode/issues/50834

**Closed** 2018-11-14 08:00 UTC
Labels: *duplicate, new release, outline

**Comment by ansiblejunky** [comment] 2018-11-14 17:24
@jrieken That issue seems to be just an enhancement request. This is a bug for sure. The sorting is messed up when you have more than 10 subheadings.
