### ISSUE TITLE
 Uncaught TypeError: Cannot set property '1' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#28987] opened 2017-06-19 05:31 UTC
Issue Id: <b>f2d49273-e522-15ac-32ce-be3a26f762aa</b><br /><br />*Versions* <br />- 1.13.0<br />-  379d2efb5539b09112c793d3d9a413017d736f89<br />-  f977399d58f7b64db35047fafe0c6e59e15f11d5<br />*Stack* <br />TypeError: Cannot set property '1' of undefined<br />[/vs/base/common/filters.ts#L533:34 (score)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/base/common/filters.ts#L533:34 (score))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L152:16 (fuzzyScore)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/editor/contrib/suggest/browser/completionModel.ts#L152:16 (fuzzyScore))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L98:8 (_createCachedState)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/editor/contrib/suggest/browser/completionModel.ts#L98:8 (_createCachedState))<br />[/vs/editor/contrib/suggest/browser/completionModel.ts#L67:7 (_ensureCachedState)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/editor/contrib/suggest/browser/completionModel.ts#L67:7 (_ensureCachedState))<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L420:28 (items)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L420:28 (items))<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L321:9 (onNewContext)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L321:9 (onNewContext))<br />[/vs/base/common/async.ts#L533:3 (runner)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/base/common/async.ts#L533:3 (runner))<br />

**Comment by jrieken** [comment] 2017-06-19 08:06
dupe of #26511

**Closed by jrieken** 2017-06-19 08:06 UTC
Labels: error-telemetry
