### ISSUE TITLE
Cannot click on link when skip is in-line with it

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#111834] opened 2020-12-03 17:59 UTC
While verifying #111706

I had the editor zoomed in and the panel up, so 'Skip' showed up on the same line as the 'Essentials' link, and then I couldn't click 'Essentials'

![skipbar](https://user-images.githubusercontent.com/7199958/101068715-eb37f900-354d-11eb-8790-31f1c1e2f91f.PNG)

Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by JacksonKearl** [comment] 2020-12-03 18:44
Will close as duplicate of #111702 for general small window behaviour.

**Closed by JacksonKearl** 2020-12-03 18:44 UTC
Labels: bug
