### ISSUE TITLE
Unable to installation expansion(VSIX) 

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode#48796] opened 2018-04-27 05:57 UTC
most extensions can not be installed(VSIX installation)
VSCODE info:
![0000](https://user-images.githubusercontent.com/20437381/39346781-76399c26-4a22-11e8-8ef3-de4c7c1aaced.png)

installation( installation prompts manual download and installation)
![0001](https://user-images.githubusercontent.com/20437381/39346798-83c684bc-4a22-11e8-8296-eec527f2d8dc.png)

VSIX installation(lack of file packages)
![0002](https://user-images.githubusercontent.com/20437381/39346800-842a323c-4a22-11e8-806e-5ccfdad121be.png)

**Comment by sandy081** [comment] 2018-04-27 09:30
Duplicate of #48373

**Closed** 2018-04-27 09:31 UTC
Labels: *duplicate, extensions
