### ISSUE TITLE
"let" colorization on Javascript (ES6) changed with update to Version 0.10.10 (0.10.10)

### ISSUE THREAD

**Issue by contreras-jorgev** [Microsoft/vscode#3927] opened 2016-03-09 17:57 UTC
After I got the update to Version 0.10.10 (0.10.10) for OSX, the Javascript "let" keyword is now white (used to be blue, recognized as a reserved word).

I tried adding back the jsconfig.json (which I understand is no longer needed to enable ES6) and the colorization is still no good.

I wonder if other keywords are being colorized incorrectly.

**Comment by aeschli** [comment] 2016-03-10 09:35
duplicate of https://github.com/Microsoft/vscode/issues/3903

**Comment by aeschli** [comment] 2016-03-10 09:45
Workaround is to switch to the Light+/Dark+ themes

**Closed** 2016-03-10 09:44 UTC
