### ISSUE TITLE
Opening from command-line in empty folder creates debug.log file

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#20325] opened 2017-02-09 16:09 UTC
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. `mkdir test && cd test`
2. `code .`
3. See the `debug.log` file:

```
[0209/110457:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6004
[0209/110457:ERROR:node_debugger.cc(86)] Cannot start debugger server
```

4. Now delete the `debug.log` file
5. The file is immediately created again (you have to refresh the explorer pane to see it, but you can see it in Windows Explorer or command line immediately)

This does not happen if you have a window open and open the folder through the UI

**Comment by Tyriar** [comment] 2017-02-09 18:06
This doesn't happen on Linux, is the Windows CLI creating an output file in the cwd?

**Comment by jdforsythe** [comment] 2017-02-09 22:00
This doesn't happen on Mac, either.  I did some more digging. It seems the file is only written out if the folder you open doesn't have a `.vscode/tasks.json` - the file doesn't even have to be the correct format.

Try this:
```sh
mkdir test1
cd test1
code .
```

The file gets written on any disk access (load the project, save a file, delete the log file, etc.)

Now try this:
```sh
mkdir test2
cd test2
mkdir .vscode
echo 2>.vscode\tasks.json
code .
```

Even as a 0-byte file, the `tasks.json` file stops the log file from being written.

**Comment by joaomoreno** [comment] 2017-02-10 10:31
Wow.

**Comment by dbaeumer** [comment] 2017-02-10 13:26
OK. I can reproduce this but since there is no tasks.json the task framework didn't do anything yet (and the task framework is not writing a debug.log file). 

Does also not happen if I start code with --disableExtensions

**Comment by dbaeumer** [comment] 2017-02-10 13:27
Strange. I can only reproduce this once on a workspace folder.

**Comment by dbaeumer** [comment] 2017-02-10 13:32
Now I can't even reproduce with a new workspace folder.

@isidorn @weinand  since the file is called debug.log do you have any idea who could write this. I have no idea how the task framework could trigger this.

**Comment by dbaeumer** [comment] 2017-02-10 13:32
@jdforsythe any additional information? Which extensions do you have installed?

**Comment by dbaeumer** [comment] 2017-02-10 13:35
The port 6004 is used by language server. So this might be a problem.

**Comment by dbaeumer** [comment] 2017-02-10 13:39
OK. Found it. The HTML server is started with --debug=6004 also the extension host is not started in debug mode. When a second workspace is opened the port is already taken and the file is written by the html server not being able to open the port.

Two interesting observations: 
- why is the html server running on startup without having an html file open :-)
- why is the html server started in debug mode in production.

**Comment by dbaeumer** [comment] 2017-02-10 13:45
@aeschli None of the other language servers are started in debug mode so I think it is not a problem of the language client library. Any idea ?

**Comment by dbaeumer** [comment] 2017-02-10 13:53
The reason for the HTML server to be started is the welcome page.

**Comment by dbaeumer** [comment] 2017-02-10 13:55
If I later create html file the server is started in debug mode. If I create a json file the json server is started in NON debug mode.

**Comment by weinand** [comment] 2017-02-10 13:56
@roblourens does node2 create a `debug.log` file?

**Comment by dbaeumer** [comment] 2017-02-10 14:03
OK. I found this. the htmlMain.ts started a language server with forceDebug set to true.

Moving to @aeschli

**Closed** 2017-02-16 15:14 UTC
Labels: bug, html

**Comment by octref** [comment] 2017-04-27 01:44
Also carried over to vetur...https://github.com/octref/vetur/issues/162

Maybe I should read through all bugs in `extensions/html` so I can prevent them all 😆
