### ISSUE TITLE
terminal select Git Bash can’t input Chinese

### ISSUE THREAD

**Issue by hqzh** [microsoft/vscode#117122] opened 2021-02-20 10:13 UTC
- VS Code Version: v1.53.2
- OS Version: windows_NT x64 10.0.17763
- Node.js: 12.18.3
- gitbash: 

Steps to Reproduce:

1. terminal select Git Bash
2. Can’t input Chinese

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment] 2021-02-21 15:27
Maybe a duplicate of #115814

What IME do you use and does it work for other shells?

**Comment by hqzh** [comment] 2021-02-22 07:09
Windows PowerShell  same won't work，I use the vscode previous version and both can be type

**Comment by hqzh** [comment] 2021-02-22 07:14
#117157

**Comment by meganrogge** [comment] 2021-02-22 16:39
Duplicate of #115814

**Closed** 2021-02-22 16:39 UTC
Labels: *duplicate, integrated-terminal
