### ISSUE TITLE
Dirt (defocused cursor) in the terminal.

### ISSUE THREAD

**Issue by matheusjones** [microsoft/vscode#123288] opened 2021-05-07 13:28 UTC
- VS Code Version: 1.56.0
- OS Version: Ubuntu 20.10 x86_64

Steps to Reproduce:

1. Open the Terminal.
2. Execute some command. Example: **npm run test**
3. See dirt (defocused cursor) in the terminal.

![image](https://user-images.githubusercontent.com/68508018/117454822-ede3b380-af1c-11eb-96a3-f5fe2b1dfe18.png)

- Before I managed to solve the problem by setting **"terminal.integrated.rendererType": "dom"** in **settings.json**.
- In the latest version (1.56.0), this configuration has been removed. This makes it impossible for me to correct this nasty problem viewing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by debopamgupta** [comment] 2021-05-07 16:32
![image](https://user-images.githubusercontent.com/51162936/117480471-45b30680-af7f-11eb-9bc0-a4d122b5c834.png)

OS: Windows 10 1903
VSCode Version:  1.56.0

Same issue, the dirt doesn't go even on `clear` - ing and remains.

**Comment by meganrogge** [comment] 2021-05-07 18:07
Duplicate of #106981

**Closed** 2021-05-07 18:07 UTC
Labels: *duplicate, new release
