### ISSUE TITLE
C# Code Highlighting - declaring positional record

### ISSUE THREAD

**Issue by kkoziarski** [microsoft/vscode#158175] opened 2022-08-15 14:15 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a *.cs file
2. past the following code:
```csharp
class MyFirstColouredClass { }
record MyRecord(int Value);
class MySecondNotColouredClass {}
```
![image](https://user-images.githubusercontent.com/6848262/184651341-1bd5e75e-4c8b-4c80-a2aa-23d4a44b9ab8.png)

**Comment by yume-chan** [comment] 2022-08-15 17:02
Duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/242

If you are using the C# extension, see https://github.com/OmniSharp/omnisharp-vscode/issues/4512

**Comment by RedCMD** [comment] 2022-08-16 07:43
Should make report to https://github.com/jeff-hykin/better-cpp-syntax
as that is what VSCode uses

@jeff-hykin

**Comment by alexr00** [comment] 2022-08-22 11:40
This is indeed a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/242.

**Closed by alexr00** 2022-08-22 11:40 UTC
