### ISSUE TITLE
Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#42162] opened 2018-01-25 18:46 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.0.0

Debug Console's output:
```
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at ChromeDebugAdapter.<anonymous> (C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:575:61)
    at Generator.next (<anonymous>)
    at C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:10:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:6:12)
    at details.forEach (C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:566:48)
    at Array.forEach (native)
    at ChromeDebugAdapter.<anonymous> (C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:566:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Deilan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:7:58)
```

---

Steps to Reproduce:

1. Angular CLI 1.6.5 project
2. `npm start`
3. Launch debugger

**Comment by roblourens** [comment] 2018-01-26 17:40
This implies that sourcemaps are messed up in a strange way. Can you share the project with me? Or should I see it with a clean angular CLI project?

**Comment by Deilan** [comment] 2018-01-27 10:06
@roblourens here you are: https://github.com/Deilan/vscode-issue-42162

1. `npm install`
2. `npm start`

I am able to reproduce it on 2 different Windows 10 x64 computers.

**Comment by roblourens** [comment] 2018-01-28 20:52
Thanks for the sample project. It's caused by a script in the sourcemap with a weird name - `["/Users/roblou/Documents/vscode-issue-42162/node_modules/moment/locale ^\\.\\/.*$"]`. Looking at your build, I have no idea where the pattern at the end comes from. But it exposes a slight problem with how source paths are handled.

**Comment by roblourens** [comment] 2018-03-09 22:53
Fixed by https://github.com/Microsoft/vscode-chrome-debug-core/commit/c8b3814d64a379320a514c5f5aa43b93cf9bfe9c

**Closed by roblourens** 2018-03-09 22:53 UTC
Labels: bug, debug
