### ISSUE TITLE
Improve word Based Suggestions for short words (`it` in particular)

### ISSUE THREAD

**Issue by csalvato** [microsoft/vscode#71693] opened 2019-04-03 23:46 UTC
Word based suggestions currently auto-completes for words of at least 2 characters.

This is problematic for writing tests in many languages because `it` is only two characters.

When I am programming in RSpec or writing JavaScript tests and creating `it` blocks, the word complete comes up before my snippets.

![image](https://user-images.githubusercontent.com/1158152/55520125-1743fe00-5638-11e9-93d7-4f08cc0346db.png)

Snippets make my test-writing much faster, whereas word complete does not in this case.  But if I turn off Word Complete globally, then I miss out on a great function that helps with writing code in general.

Right now I am leaving Word Complete on, but having to press the Down Arrow key every time I write an it block which feels nasty.

Would love if I could have my snippets at the top of the list by either ignoring 2-letter word completion, making snippets take priority or letting me exclude some words from Word Complete.

**Comment by jrieken** [comment] 2019-04-04 07:09
> auto-completes for words of at least 2 character

Is that just arbitrary? Would you have suggested 3 characters if your favourite snippet is 3 characters long?

**Comment by csalvato** [comment] 2019-04-04 21:45
> Is that just arbitrary? Would you have suggested 3 characters if your favourite snippet is 3 characters long?

You quoted the part of my question that's stating the fact that this is how word complete currently works.

For example:

![image](https://user-images.githubusercontent.com/1158152/55589955-e1ae1c00-56ee-11e9-9ae3-b992f49e4463.png)

But maybe were actually contending my suggestion here...?

> Would love if I could have my snippets at the top of the list by either **ignoring 2-letter word completion**, making snippets take priority or letting me exclude some words from Word Complete.

If that's the case, then it's not arbitrary.  My rationale is that two letter word completes don't make sense because the string is so short. Word completion is more valuable as the length of words increases, and becomes a hindrance as the words get shorter (as shown in this example).

This contrasts to where snippets are most useful – when their code is short thus saving keystrokes.

Let's use `it` as an example. If all I care about is typing the word `it`, then typing `i`+`t` + `space` is the same amount of keystrokes as `i`+`t`+`tab`...so having word complete of 2 letters just makes no sense.

Also, since the word is so short, and most snippet libraries will use two letter abbreviations, any word that is structured to have `i` + `any letter before t` will come to the top of that list hiding any two letter snippets, which are more valuable.

That said, limiting word complete to a certain string length is only one suggestion of three, and it's personally my least favorite resolution to improving this UX. 

I would personally prefer if:

* Intellisense would learn that I keep using the snippet and don't want to word complete (right now it just keeps forcing the word to the top)
* Snippets taking priority over word complete
* I could teach it reserved words to ignore

But I don't care about the exact implementation as much as the fact that my snippets come to the top over two letter words.

**Comment by csalvato** [comment] 2019-04-05 02:19
Thinking about this further, another frame came to mind....

I don't think it makes sense that if the word matches a snippet exactly, that the word completion wins for the top spot on the list like this:

![image](https://user-images.githubusercontent.com/1158152/55599808-a6274800-5716-11e9-80f5-d8212f535d80.png)

![image](https://user-images.githubusercontent.com/1158152/55599839-c951f780-5716-11e9-9dda-70b3a6a52429.png)


I've already completed the word...so in all likelihood, if I wanted the word, I would just push `space` and carry on typing. I believe in these cases, what the user really wants is the snippet...so that should be on top if the strings are identical, imo.

**Comment by jrieken** [comment] 2019-06-06 07:39
> I don't think it makes sense that if the word matches a snippet exactly, that the word completion wins for the top spot on the list like this:

closing this as dupe of #74213 then

**Closed** 2019-06-06 07:39 UTC
Labels: *duplicate, suggest, under-discussion

**Comment by csalvato** [comment] 2019-06-06 16:01
Thanks @jrieken ! Seems like there's room for improvement on how we order what comes to the top of the list. What wins (and how we determine that), still seems up for debate...
