### ISSUE TITLE
El host de extensiones finalizó inesperadamente

### ISSUE THREAD

**Issue by BsoftGraphql** [microsoft/vscode#176559] opened 2023-03-08 20:47 UTC
Type: <b>Bug</b>

:(

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz (6 x 3300)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.67GB (7.64GB free)|
|Process Argv|--crash-reporter-id e6e71fb0-34a8-4e2a-8764-086ee4399598|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-end-tag-labels|ant|0.11.0
jsoncrack-vscode|Ayk|1.0.8
vscode-tailwindcss|bra|0.9.7
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.77.9225
copilot-labs|Git|0.12.791
vscode-pull-request-github|Git|0.60.0
vscode-graphql|Gra|0.8.6
vscode-graphql-syntax|Gra|1.1.0
todo-tree|Gru|0.0.224
rest-client|hum|0.25.1
emotionsnippets|iJS|1.1.2
path-autocomplete|ion|1.23.1
svg|joc|1.5.0
vscode-gutter-preview|kis|0.30.0
node-module-intellisense|lei|1.5.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
inline-fold|moa|0.2.3
vscode-docker|ms-|1.24.0
vscode-language-pack-es|MS-|1.76.2023030809
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.10
remote-wsl|ms-|0.76.1
powershell|ms-|2023.2.1
sublime-keybindings|ms-|4.0.10
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.5.0
material-icon-theme|PKi|4.24.0
vscode-react-refactor|pla|1.1.3
vscode-css-peek|pra|4.2.0
prisma|Pri|4.11.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.5.0
vscode-rapidapi-client|Rap|1.9.3
java|red|1.15.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1426
markdown-preview-enhanced|shd|0.6.8
indenticator|Sir|0.7.0
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
code-spell-checker|str|2.19.0
code-spell-checker-spanish|str|2.1.7
vscode-styled-components|sty|1.7.5
vscode-stylelint|sty|1.2.4
react-proptypes-generate|sum|1.7.6
vscode-pets|ton|1.22.0
errorlens|use|3.7.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-java-test|vsc|0.38.1
vscode-maven|vsc|0.40.4
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
vscodedisable:30660115
pythonb192:30669360
funwalk2cf:30676044

```

</details>

**Comment by bpasero** [comment] 2023-03-09 04:45
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by isidorn** [comment] 2023-03-15 10:59
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.
If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue

**Closed by isidorn** 2023-03-15 10:59 UTC
Labels: info-needed, freeze-slow-crash-leak, extension-host, sandbox
