### ISSUE TITLE
When i paste code it keeps auto closing the first line

### ISSUE THREAD

**Issue by julim1** [microsoft/vscode#229793] opened 2024-09-26 06:36 UTC
When I paste a perfectly good chunk of code, the first line e.g. div, will get auto completed with /div, despite the div being closed in the later part of the pasted code. I have been removing them when it happens, but when it slips my notice, it results in bugs.

**Comment by aeschli** [comment] 2024-09-26 09:05
duplicate of https://github.com/microsoft/vscode/issues/227859

**Closed by aeschli** 2024-09-26 09:05 UTC
