### ISSUE TITLE
Webview View does not have `enableFindWidget` capability

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#233045] opened 2024-11-05 01:45 UTC
We have a number of Webviews that can display both as a WebView and a WebViewView. We take advantage of the built-in `enableFindWidget` functionality for WebViews and would like the same capability when the same view is implemented to be hosted as a WebViewView.

**Comment by mjbvz** [comment] 2024-11-05 19:13
Duplicate of #173643

**Closed by mjbvz** 2024-11-05 19:13 UTC
