### ISSUE TITLE
since the last update, i have to login to github several times after i reload the window or start up vscode

### ISSUE THREAD

**Issue by asg0451** [microsoft/vscode#171294] opened 2023-01-13 22:22 UTC
Type: <b>Bug</b>

Steps to Reproduce:

1. launch vscode
2. have to sign in to sync settings and for github extensions that require it (pull requests and copilot)
3. reload the window or relaunch vscode
4. again

happens even with all extensions disabled. 

using remote over ssh.

VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-1022-gcp
Remote OS version: Linux x64 5.15.0-1022-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|--crash-reporter-id 27a3d0db-9236-42b5-b822-bc0d17ee513e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: frankelbot-east|
|OS|Linux x64 5.15.0-1022-gcp|
|CPUs|AMD EPYC 7B12 (64 x 2249)|
|Memory (System)|251.88GB (243.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: frankelbot-east|
|OS|Linux x64 5.15.0-1022-gcp|
|CPUs|AMD EPYC 7B12 (64 x 2249)|
|Memory (System)|251.88GB (243.33GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.5.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3
command-server|pok|0.8.2
cursorless|pok|0.26.557
parse-tree|pok|0.24.0
default-keys-windows|smc|0.0.9
emacs|vsc|0.1.3
vscode-ruby|win|0.28.0
vscode-bazel|Baz|0.7.0
markdown-mermaid|bie|1.17.3
vscode-markdownlint|Dav|0.49.0
vscode-highlight|fab|1.6.0
foam-vscode|foa|0.20.5
copilot|Git|1.67.7944
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.0
jsonnet|hep|0.1.0
magit|kah|0.6.36
center-editor-window|kai|2.3.0
vscode-typescript-next|ms-|5.0.202301100
go-doc|msy|1.0.1
vscode-paste-image|mus|1.0.4
cursorless|pok|0.26.557
parse-tree|pok|0.24.0
talon|pok|0.2.0
rust-analyzer|rus|0.3.1361
trailing-spaces|sha|0.4.1
vscode-fileutils|sle|3.5.2
even-better-toml|tam|0.19.0
vscode-pets|ton|1.21.0
vscode-lldb|vad|1.8.1
org-mode|vsc|1.0.0
markdown-all-in-one|yzh|3.5.0
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by TylerLeonhardt** [comment] 2023-01-13 23:20
Can you follow these steps so that we can get more information on what's going on?

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* Choose `Trace`
* _Wait for the issue to happen..._
* Open the Output pane
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Main` Output channel

**Comment by asg0451** [comment] 2023-01-17 15:24
i opened a new window and it made me log in again, captured: https://pastebin.com/nr87fD9Q

**Comment by asg0451** [comment] 2023-01-17 17:19
also, vscode has been crashing a lot. may be related? annoying as that is though, that issue predates this one. you may see the crashes in the main log. (if we could fix that as well that would be amazing!)

**Comment by asg0451** [comment] 2023-01-18 17:25
hey @TylerLeonhardt have you had a chance to look at this yet? 🙏

**Comment by TylerLeonhardt** [comment] 2023-01-19 23:20
Hi @asg0451 👋 I looked through your logs and unfortunately, it's a duplicate of https://github.com/microsoft/vscode/issues/130156 something that has been really hard to track down because of the rarity of this issue.

I'll close this as a dupe of that one, but maybe give some of those ideas a try and see how it goes. I can say that in the coming months, we'll be doing some drastic changes in this space that _should_ resolve this in the future.

**Closed by TylerLeonhardt** 2023-01-19 23:20 UTC

**Comment by asg0451** [comment] 2023-01-19 23:35
thanks @TylerLeonhardt . fwiw i have managed to resolve the issue (for now) by `rm -rf`ing `~/.vscode-server` on the remote machine.
