### ISSUE TITLE
Typescript broken hightlights

### ISSUE THREAD

**Issue by kitsoRik** [microsoft/vscode#100638] opened 2020-06-20 10:12 UTC
Bug with typescript hightlights when use new line in templates, types is not hightlights green color

Single line
![image](https://user-images.githubusercontent.com/48686795/85200671-190fe500-b302-11ea-8c1e-f7d03b85dc8f.png)

Multiline
![image](https://user-images.githubusercontent.com/48686795/85200665-0f867d00-b302-11ea-993a-60f370db2987.png)

- VSCode Version: 1.46.0
- OS Version: Windows 10

Steps to Reproduce:

1. Copy and paste to *.ts file

**Comment by IllusionMH** [comment] 2020-06-20 12:06
Duplicate of other issues that has https://github.com/microsoft/TypeScript-TmLanguage/issues/479 as root cause.

This kind of problem is handled by `"editor.semanticHighlighting.enabled": true`. Do you have it enabled?
![image](https://user-images.githubusercontent.com/1312662/85201325-3dba8b80-b307-11ea-8015-3f5bb268db42.png)

Example without semantic highlight
![image](https://user-images.githubusercontent.com/1312662/85201382-883c0800-b307-11ea-9269-46248b9abb4b.png)

**Closed** 2020-06-23 00:56 UTC
Labels: *duplicate, grammar, typescript

**Comment by kitsoRik** [comment] 2020-06-23 13:46
> Duplicate of other issues that has [microsoft/TypeScript-TmLanguage#479](https://github.com/microsoft/TypeScript-TmLanguage/issues/479) as root cause.
> 
> This kind of problem is handled by `"editor.semanticHighlighting.enabled": true`. Do you have it enabled?
> ![image](https://user-images.githubusercontent.com/1312662/85201325-3dba8b80-b307-11ea-8015-3f5bb268db42.png)
> 
> Example without semantic highlight
> ![image](https://user-images.githubusercontent.com/1312662/85201382-883c0800-b307-11ea-9269-46248b9abb4b.png)

Hello, sorry for late reply.
