### ISSUE TITLE
Show number of selected lines in status bar

### ISSUE THREAD

**Issue by PleasedSkin** [Microsoft/vscode#15344] opened 2016-11-11 11:25 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|xml|DotJoshJohnson|1.6.0|
|ejs-language-support|QassimFarid|0.0.1|
|smalltalk|PleasedSkin|0.0.1|
|theme-panda|tinkertrain|0.5.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. Select one or more lines
2. In the status bar, the number of chars selected is displayed but not how many lines are selected.

It would be nice to be able to see both just like in Notepad++ or Sublime Text.

**Comment by mlewand** [comment] 2016-12-29 15:59
Duplicate of #932.

**Closed** 2017-01-02 17:06 UTC
Labels: extension-candidate, feature-request, workbench
