### ISSUE TITLE
Multiple accounts UI

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#94036] opened 2020-03-31 19:13 UTC
If a user signs in with multiple accounts, can we indicate or highlight here which one they are currently in? 

![image](https://user-images.githubusercontent.com/9721254/78065987-27351180-7362-11ea-83bb-dce73654377a.png)

**Comment by RMacfarlane** [comment] 2020-04-01 17:28
Closing as a duplicate of https://github.com/microsoft/vscode/issues/94076

**Closed by RMacfarlane** 2020-04-01 17:28 UTC
