### ISSUE TITLE
command panel keybindings

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#40206] opened 2017-12-14 10:06 UTC
VSC 1.18.1 OSX 

When in command panel you can still execute key bindings that happen in the background like for example  `command key + ?` this potentially introduce accidental edit's without noticing because the panel keeps focused with no visual indication something happened in the background
 
![image](https://user-images.githubusercontent.com/863731/33985718-b487593a-e0bb-11e7-9d5d-d6fc4eb41003.png)

**Comment by bpasero** [comment] 2017-12-15 05:55
I am closing this as designed, there are people that keep the command palette open even when it has no focus and in that case I would not want to block all keybindings only because of that.

**Closed by bpasero** 2017-12-15 05:55 UTC
Labels: workbench
