### ISSUE TITLE
Make debugger tooltip able to be floating

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#43380] opened 2018-02-10 09:41 UTC
### Issue Type
Feature Request

### Description
Make debugger tooltip (which appears on hover over variables) able to be floating.

**Comment by isidorn** [comment] 2018-02-12 09:31
Let's treat this as a duplicate of https://github.com/Microsoft/vscode/issues/43326
And make that one more general

**Closed** 2018-02-12 09:31 UTC
Labels: *duplicate, debug, feature-request
