### ISSUE TITLE
File Menu Shortcut Key Clash

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#38017] opened 2017-11-10 02:29 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.20
cpptools|ms-|0.14.2

File menu have 2 sub menu used "S" key for shortcut key.
One is "将工作区另存为(S)",  another is "保存(S)  Ctrl + S".
In English is "Save To Workspace" and "Save".

---

Steps to Reproduce:

1. Alt + F -> S, can not save current file now
2. Check the File menu, will find 2 sub menu used same key("S"), Save to workspace and Save
3. Save to workspace is first match menu.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment] 2017-11-10 17:12
I can reprodcue this. There is also a clash with the "O" key.
@bpasero do you mind if I change these 2 mnemonics?

**Comment by isidorn** [comment] 2017-11-10 17:42
Ok actually a duplicate of https://github.com/Microsoft/vscode/commit/f8a0b7dcc5e42d841d5f31f9d4d19faae6d27083

@bpasero keep in mind that there seems to be one more clash. The one with `O`

**Comment by isidorn** [comment] 2017-11-13 09:45
Closing this one as @bpasero you already closed the other.

**Closed by isidorn** 2017-11-13 09:45 UTC
Labels: new release, workbench
