### ISSUE TITLE
Debugger looses UI state on step

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16031] opened 2016-11-24 16:05 UTC
See attached screen capture. In more than 50% of the cases stepping collapsed variables I have manually expanded.

![nov-24-2016 17-00-03](https://cloud.githubusercontent.com/assets/1794099/20604721/249487bc-b268-11e6-8a8f-543ba5fe20b7.gif)

**Comment by isidorn** [comment] 2016-12-29 15:36
Experimented with this and the tree nicely has api `getExpandedElements`, however when these elements get passed into `tree.expandAll` only the first parent element is expended. I believe that the problem lies that `expandAll` does not support expending nested elements.
Assigning to @joaomoreno for `expandAll` to support expanding nested elements

**Comment by joaomoreno** [comment] 2017-01-03 14:45
@isidorn With that you're telling the tree to expand elements it doesn't know yet. It's up to you to understand the semantics behind each element you give the tree and ask the tree to expand them in the correct order.

**Comment by kraigb** [comment] 2017-01-13 05:33
I'm experiencing a similar case to this using some code in python:
- Set a breakpoint in a function and invoke code to stop at the breakpoint.
- Locals in the debugger pane is automatically expanded, Arguments is collapsed.
- Expand Arguments
- Do Step Over
- Arguments get automatically collapsed, while Locals remains opens.

Because I have intentionally expanded Arguments, Step Over should not collapse. Nor should Step Into or Step Out for that matter.

In my case, I'm trying to debug modifications I'm making to an input object in the python function, and with Arguments collapsing automatically, I can't see the change that's actually being made. I have to remember the previous value and then expand Arguments again, which is quite annoying.

**Comment by yay** [comment] 2017-03-06 14:38
Consider debugging the following recursive function:

<img width="928" alt="screen shot 2017-03-06 at 11 09 46" src="https://cloud.githubusercontent.com/assets/1799756/23605562/83174316-025d-11e7-9b9e-6b07d2f34717.png">

## Actual behavior

The `arguments` section is collapsed on each recursive call.

<img width="261" alt="screen shot 2017-03-06 at 11 09 12" src="https://cloud.githubusercontent.com/assets/1799756/23605625/bc40c090-025d-11e7-82e3-b4cf0f449170.png">

## Expected  behavior

The `arguments` section keeps its expanded or collapsed state.

<img width="261" alt="screen shot 2017-03-06 at 11 09 22" src="https://cloud.githubusercontent.com/assets/1799756/23605630/c2c11500-025d-11e7-83cc-b7b5988b0eaf.png">

This happens on any function call, recursion is just a good example, where the signature stays the same and you definitely don't want to hide the arguments on every call.

**Comment by mirao** [comment] 2017-03-09 12:00
I have the same issue when debugging PHP script with XDebug. Whenever I call the action "Step Into", an object or class with its properties is collapsed in Locals.
Used SW: VScode 1.10.2, PHP debug 1.10.0

**Comment by DatGuyJonathan** [comment] 2017-09-28 22:54
@isidorn , my debugger extension has this issue as well with variables that has children variables.

![variablesviewreset](https://user-images.githubusercontent.com/7286437/30993722-269606ae-a465-11e7-9593-775a3ac4bd4d.gif)

I think it's possible for vscode to remember the variables tree state because I don't see this issue when developing my extension. I want to run vscode out of source, drop my .vsix in, and figure out what my debugger extension is sending incorrectly to vscode. Could you suggest some places to set breakpoints?

**Closed** 2017-10-03 10:19 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2017-10-03 10:21
I have pushed a fix for this. Now we are always trying to preserve the previous variable expansion state by passing sequentally a list of previously expanded elements to the tree. On top of that I have refined the id computation of scopes and variables to not take into account the reference. This now works nicely now for the node debugging.

An insider version which contains this fix should be available at the end of this week (early next week). For those who would like to try it out immediatly you can simply build out of source.

@DatGuyJonathan let me know if this fixes the issue for your debugger once you try it out. Thanks

**Comment by DatGuyJonathan** [comment] 2017-10-03 23:47
@isidorn , I built master branch out of source and the variable is still auto-collapsing for me. Were you able to try it out with Python and PHP debuggers that had the same issue?

**Comment by isidorn** [comment] 2017-10-04 08:05
@DatGuyJonathan thanks for trying it out. Let me go a bit more into details into our tree implementation: it will preserve the expansion state of elements if the id of those elements does not change. So the key thing here is for the id to be stable, let's look at how the id of a variable is computed [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L285): `variable:${parent.getId()}:${name}`
So it is dependendent on the parent chain which can be another variable or a scope. 

* `Scope` gets its id like this: `scope:${stackFrame.getId()}:${name}:${index}`
* `StackFrame` like this: `stackframe:${this.thread.getId()}:${this.frameId}:${this.index}`
* `Thread` like this `thread:${this.process.getId()}:${this.threadId}`
* `Process` has a stable internal vscode id.

When you put all of that together you get something like this:
`variable:scope:stackframe:thread:685902b5-509d-4265-87cb-3dced318dfb8:1:1000:0:Local:0:myMap`

So the following must be kept stable by all adapters in order for the tree expansion to be preserved: 
* `Variable`: `name`
* `Scope`: `name` and index in the collection of stack frames
*  `StackFrame`: `frameId` and index in the collection of stack frames (e.g 1st stack frame from top)
* `thread`: `threadId`

If the adapter is changing any of those between step events than the expansion can not be preserved since those variables are treated as different variables on the vscode side.
To debug this you can always print out or brekpoint when vscode gets the variables ids [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L650)

Node debug adapter is respecting this thus the expansion state now properly works for it.

**Comment by DatGuyJonathan** [comment] 2017-10-04 22:55
Thanks for the detailed explanation, @isidorn . I added some console.log() to VariablesDataSource.getId(), then I did some expanding and stepping. The IDs look stable.

[variableIds.txt](https://github.com/Microsoft/vscode/files/1357546/variableIds.txt)

I was debugging through the constructor in VariablesView (where you made your fix). I had breakpoints on line [71](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L71) & [76](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L76). Sometimes, my variables tree does remember its expanded state. The issue is only __always__ reproduce-able if I'm not debugging VS Code source. Could there be a timing issue?

**Comment by isidorn** [comment] 2017-10-05 08:42
@DatGuyJonathan there might be some timing issue which I am unaware of. To investigate furhter I propose that you put breakpoints [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L73) and check the `expanded` array. Does it nicely reflect what should be expanded? Do the ids inside that array equeal to the new ids just obtained in the new step call.
You can also print out the id computation [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L650)

If all of this does not provide any useful information that I propose that you give me exact reproducable steps on how to setup your debugger on my mac and then I can look into it.

**Comment by guw** [comment] 2017-10-13 13:45
@isidorn Sorry for the long reply. I'm working with @DatGuyJonathan and what I discovered is the following behavior.

I added some log output to trace what's going on. 
```
// Use scheduler to prevent unnecessary flashing
this.onFocusStackFrameScheduler = new RunOnceScheduler(() => {
	// Always clear tree highlight to avoid ending up in a broken state #12203
	this.tree.clearHighlight();
	console.log(`onFocusStackFrameScheduler: clearHighlight`);
	const expanded = this.tree.getExpandedElements();
	expanded.forEach(e => console.log(`found expandedElement: ${e.id}`));
	this.tree.refresh().then(() => {
		const stackFrame = this.debugService.getViewModel().focusedStackFrame;
		return sequence(expanded.map(
			e => () => {
				console.log(`expanding: ${e.id}`);
				return this.tree.expand(e);
			}
		)).then(() => {
			this.tree.getExpandedElements().forEach(e => console.log(`restored expandedElement: ${e.id}`));
			// If there is no preserved expansion state simply expand the first scope
			if (this.tree.getExpandedElements().length === 0) {
				if( stackFrame) {
					console.log(`no expandedElements`);
					return stackFrame.getScopes().then(scopes => {
						if (scopes.length > 0 && !scopes[0].expensive) {
							console.log(`expanding first scope: ${scopes[0].getId()}`);
							return this.tree.expand(scopes[0]);
						}
						return undefined;
					});
				} else {
					console.log(`no stackFrame`);
				}
			}
			return undefined;
		});
	}).done(null, errors.onUnexpectedError);
}, 400);
```

When expansing is ok, I see the following trace:
```
onFocusStackFrameScheduler: clearHighlight
found expandedElement: scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0
found expandedElement: variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this
found expandedElement: variable:variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this:someType
expanding: scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0
expanding: variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this
expanding: variable:variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this:someType
restored expandedElement: scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0
restored expandedElement: variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this
restored expandedElement: variable:variable:scope:stackframe:thread:c6136ea5-31cf-4a48-ac44-38c5db926dcb:1:1000:0:Local:0:this:someType
```

When expansion is **not** ok, the trace output looks like this:
```
onFocusStackFrameScheduler: clearHighlight
found expandedElement: scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0
found expandedElement: variable:scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0:this
found expandedElement: variable:variable:scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0:this:someType
expanding: scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0
expanding: variable:scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0:this
expanding: variable:variable:scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0:this:someType
no stackFrame
onFocusStackFrameScheduler: clearHighlight
no expandedElements
expanding first scope: scope:stackframe:thread:12ef9a99-b899-4b6c-b75c-c97bfa76e63d:1:1000:0:Local:0
```

It looks like the refresh is done at a time when no `stackFrame` is available. Thus, I think the tree does not contain all the elements yet that need to be restored. Any chance to delay the clear/refresh and restore during stepping, till a stackFrame is available?

**Comment by isidorn** [comment] 2017-10-13 14:08
@guw we already delay by 400ms, please try to change these 400 ms [here](https://github.com/Microsoft/vscode/blob/isidorn/compositeBar/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L86)
Build vscode out of source with your changes and verify if that fixes the issue. Thanks

**Comment by guw** [comment] 2017-10-13 14:39
If I change to a high number (eg., 4000) that it works but the UI becomes weird. It takes quite a lot time till the tree is updated.

However, a smaller change (eg., 600) did not help.
https://drive.google.com/file/d/0B4LUtM5m58RmUFRSUGI1ZFl4RnM/view

**Comment by guw** [comment] 2017-10-18 08:31
@isidorn I tried a couple things but none of them is really satisfying. I also tried changing out debug adapter to pre-fetch the stack before signaling that it stopped as part of stepping. It didn't help. The tree is still flashing, i.e. it goes empty and then comes back without expanded elements being restored.

I've experimented with the delays and implemented a strategy which will use a longer when the focused stack frame because undefined. This seems to work well for our debugger (which needs to do remote communication).

https://github.com/guw/vscode/commit/1406a0a5390e949e2d34aa34d74a1afcbba62a2a
```
if (!this.tree.getContentHeight() || sf.explicit) {
	console.log(`onDidFocusStackFrame: schedule onFocusStackFrameScheduler immediately (explicit=${sf.explicit}, contentHeight=${this.tree.getContentHeight()})`);
	this.onFocusStackFrameScheduler.schedule(0);
} else if (!viewModel.focusedStackFrame) {
	console.log("onDidFocusStackFrame: schedule onFocusStackFrameScheduler waiting while stepping");
	this.onFocusStackFrameScheduler.schedule(2000);
} else {
	console.log("onDidFocusStackFrame: schedule onFocusStackFrameScheduler immediately when stopped stepping");
	this.onFocusStackFrameScheduler.schedule(0);
}
```

Another strategy that I have in mind is persisting the list of expanded elements and then restoring it when stepping is done. Ideally the flashing, i.e. blank tree in between stepping, should be avoided. Can you advice on alternate options? I'm happy to work on a PR.

**Comment by isidorn** [comment] 2017-10-18 08:56
@guw thanks for looking into this. The code snippet you provided looks hacky and I am not sure if this will work nicely for all adapters. Also it might slow down how the call stack tree is being refreshed. Due to that I propose that you tryout your alternative idea of persiting the list of expanded elements and then restoring it once step is done However your idea of persiting the list of expanded elements is exactly what I am currently doing [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViews.ts#L70). I think what might be missing is "if there are no expanded elements try expanding what was expanded in the previous step". So just try keeping the expaned array globaly and update it only if there is something.
I also propose that you create a PR where we can continue our communication since this issue is fixed for all other adapters.

**Comment by guw** [comment] 2017-10-18 15:47
Thanks will do!

Re: "fixed for all others" - I have been told that the Java debugger is also still affected by this. However, I haven't verified this because I don't use VS Code for Java debugging.
