### ISSUE TITLE
Run Code Actions On Save: Organize Imports

### ISSUE THREAD

**Issue by DMEvans** [Microsoft/vscode#49961] opened 2018-05-16 08:59 UTC
Issue Type: <b>Bug</b>

I've used the new feature to clean up my imports introduced in VSCode 1.23.1 and it's been very helpful for cleaning up dead references.  

"[typescript]": {
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
},

However, it's causing lint errors in our angular projects because my company has a policy in our tslint.json that lines must be less than 140 characters.  When VSCode organizes the imports it ignores this restriction and places all imported classes for a given namespace in a single line.

import { Component, OnInit, TemplateRef, ViewChild, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah, Blah } from '@angular/core';

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
githistory|don|0.4.1
EditorConfig|Edi|0.12.1
prettier-vscode|esb|1.3.1
angular-essentials|joh|0.3.2
Angular2|joh|6.1.1
vscode-github|Kni|0.28.1
mssql|ms-|1.3.1
csharp|ms-|1.15.2
team|ms-|1.133.0
debugger-for-chrome|msj|4.4.3
angular2-inline|nat|0.0.17

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2018-05-16 17:38
Duplicate of https://github.com/Microsoft/TypeScript/issues/22991

**Closed by mjbvz** 2018-05-16 17:38 UTC
