### ISSUE TITLE
VSCode is not honoring the order in which I return symbols

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#14240] opened 2016-10-24 00:02 UTC
- VSCode Version: 1.6.1
- OS Version: Windows 10 1607 (14393.321)

Steps to Reproduce:

I can't give you a repro until we update the PowerShell extension and release it.  But I can describe what is going on.  I open a file with lots of functions in it.  I want to see the list of symbols so I press `Ctrl+Shift+O`.  I see this VSCode/extension exchange in our log:

```
    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 4,
      "method": "textDocument/documentSymbol",
      "params": {
        "uri": "file:///c%3A/Users/Keith/GitHub/PowerShell/Plaster/src/InvokePlaster.ps1"
      }
    }

    WRITE MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": "4",
      "result": [
        {
          "name": "AreFilesIdentical { }",
          "kind": 12,
          "location": {
            "uri": "c:/Users/Keith/GitHub/PowerShell/Plaster/src/InvokePlaster.ps1",
            "range": {
              "start": {
                "line": 647,
                "character": 8
              },
              "end": {
                "line": 659,
                "character": 9
              }
            }
          },
          "containerName": "InvokePlaster"
        },
        {
          "name": "ColorForOperation { }",
          "kind": 12,
          "location": {
            "uri": "c:/Users/Keith/GitHub/PowerShell/Plaster/src/InvokePlaster.ps1",
            "range": {
              "start": {
                "line": 1228,
                "character": 0
              },
              "end": {
                "line": 1240,
                "character": 1
              }
            }
          },
          "containerName": "InvokePlaster"
        },
        {
          "name": "ConvertToDestinationRelativePath { }",
          "kind": 12,
          "location": {
            "uri": "c:/Users/Keith/GitHub/PowerShell/Plaster/src/InvokePlaster.ps1",
            "range": {
              "start": {
                "line": 1179,
                "character": 0
              },
              "end": {
                "line": 1191,
                "character": 1
              }
            }
          },
          "containerName": "InvokePlaster"
        },
```
Note that I have updated the PowerShell extension to return Symbols in sorted order (by name).  Yet this is what VSCode shows in the UI:
![image](https://cloud.githubusercontent.com/assets/5177512/19630545/e76fd3a0-9949-11e6-986c-40d81ab31e9a.png)

It appears to me that VSCode is trying to preserve the symbol order based on the position of the symbol in the file.  VSCode should really honor the order returned by the extension.  For instance, when I'm searching for a particular function, I couldn't give a flying flip about the relative position of the symbol in the file.  As we learned in Algorithms 101, searching a **SORTED** list is a helluva lot quicker than an unsorted list.  :-)

Please provide a way for symbols to be displayed in the order the extension supplies them to VSCode.

**Comment by dbaeumer** [comment] 2016-10-24 12:34
@jrieken assigning to you. I simply pass on that list to the document symbol provider without changing the order. Could be @bpasero as well.

**Comment by jrieken** [comment] 2016-10-24 13:00
We do sort entries by start position on purpose and because of these reasons:

* multiple providers can provide document symbols, the results are merged, and therefore the relative order of one result set becomes obsolete
* when you navigate symbols with arrow keys we highlight/reveal them and it would be very weird if that jumps up and down while selecting a linear list of items.

**Comment by jrieken** [comment] 2016-10-24 13:02
closing as designed unless the above reasons for re-sorting become obsolete.

**Closed by jrieken** 2016-10-24 13:02 UTC
Labels: as-designed

**Comment by rkeithhill** [comment] 2016-10-24 14:34
OK I kind of get the multiple providers issue but you could sort the resulting, merged set by name.  RE:

> when you navigate symbols with arrow keys we highlight/reveal them and it would be very weird if that jumps up and down while selecting a linear list of items. 

That I think might need to have some usability data to support that conclusion. There's this little IDE called Visual Studio - you know, VSCode's namesake - that's been around for decades and it always sorts symbol lists alphabetically e.g.:  :-)

![image](https://cloud.githubusercontent.com/assets/5177512/19649827/767bc9f8-99c4-11e6-8345-6dbf25547eeb.png)

I assure that the type members are **not** in that order in the file.

**Comment by jrieken** [comment] 2016-10-24 14:43
Does VS reveal/highlight the entries when navigating the list? Like this

![oct-24-2016 16-41-27](https://cloud.githubusercontent.com/assets/1794099/19650279/fa983e80-9a08-11e6-96f9-505a79812c0a.gif)

**Comment by rkeithhill** [comment] 2016-10-24 15:33
No, VS doesn't do that.  When you select the item from the dropdown, the dropdown closes and then VS navigates to the function.  While the feature you show above (live navigation while browsing) is cool looking I'm not sure how useful it is.  I don't typically use the Symbols list to scroll through my source code.  Even if you do use it for this reason, if your functions are big enough this list is still going to appear "jumpy".

**Comment by jrieken** [comment] 2016-10-24 15:55
My understanding of the VS feature you are referring to is that it is breadcrumb UI, showing the current scope and allowing you to jump to a sibling/parent symbol. This is not what 'Go to Symbol in File...'-feature of VS Code is about. There the focus is about quickly navigating to a symbol by typing parts of its name. That behaviour is aligned with other parts of VS Code (command palette, open editor etc) and also with other editors like Sublime Text, Chrome Dev Tools etc.
