### ISSUE TITLE
Testing markdown link rename: prompt looks awkward

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#164637] opened 2022-10-25 18:46 UTC
Testing #164522

When trying to rename something, I get this prompt:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/31675041/197856040-b2b02bab-1b8b-462f-89b6-85b6312cdfd1.png">

I think that the really long first and third button make it sort of weird to look at (maybe it seems like the buttons have a lot to read?). Is this how we usually show prompts that have an always/never + yes/no question? 

Feel free to close this if it's how it's supposed to be.

**Comment by mjbvz** [comment] 2022-10-25 19:01
Duplicate of #164556

**Closed by mjbvz** 2022-10-25 19:01 UTC
