### ISSUE TITLE
Unexpected Auto-running

### ISSUE THREAD

**Issue by ZephyrSober** [microsoft/vscode#205290] opened 2024-02-15 14:12 UTC
Type: <b>Bug</b>

When I start my vscode IDE, it would automaticly start my wsl.exe.And this would lead to a opening of a pop-up window named 'cmd: C:/windows/system32/wsl.exe. But I have not even install a wsl version or 'remote wsl'. So I wonder how to ban this pop-up window.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.26052
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (9.01GB free)|
|Process Argv|--crash-reporter-id 3c0836f2-74f7-45f9-bdf2-068035bb8dc1|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
codeium|Cod|1.6.33
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.9
modelarts-vscode-toolkit|hua|1.2.2
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.11.0
json|Mee|0.1.2
vscode-docker|ms-|1.29.0
vscode-language-pack-zh-hans|MS-|1.85.2024021409
autopep8|ms-|2023.8.0
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.2
jupyter|ms-|2024.1.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.17.15
cpptools|ms-|1.18.5
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
vsliveshare|ms-|1.0.5905
autodocstring|njp|0.6.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
7j2b6412:30964151
e3gdj431:30958358

```

</details>

**Comment by aeschli** [comment] 2024-02-19 13:49
duplicate of #205270

**Closed by aeschli** 2024-02-19 13:49 UTC
