### ISSUE TITLE
保存时,格式自动整理后和eslint规则冲突的问题求助

### ISSUE THREAD

**Issue by junmaqiang** [Microsoft/vscode#32279] opened 2017-08-11 03:41 UTC
![vscode](https://user-images.githubusercontent.com/1819457/29200691-e7e24c84-7e89-11e7-824e-5d90f8361a45.png)

**Comment by ToMakeSense** [comment] 2017-08-11 05:06
you can install an extension called **EditorConfig** , default setting as below:

> \# Editor configuration, see http://editorconfig.org
> root = true
> 
> [*]
> charset = utf-8
> indent_style = space
> indent_size = 4
> **insert_final_newline = true**
> trim_trailing_whitespace = true
> 
> [*.md]
> max_line_length = off
> trim_trailing_whitespace = false

**Comment by kzhui125** [comment] 2017-08-11 05:24
how about setting "editor.formatOnSave": false

**Comment by junmaqiang** [comment] 2017-08-11 05:37
@kzhui125  我喜欢保存时自动整理格式的功能, 只是想这格式肯定是有规则配置的吧? 
知道修改那个配置可以实现最后一行空白不被删除 就行了!

**Comment by weinand** [comment] 2017-08-11 06:52
I cannot read Chinese. Please provide a translation in English.

**Comment by kzhui125** [comment] 2017-08-11 07:20
translate:
With the setting "editor.formatOnSave": true, VSCode will delete the last line on saving the js file.
He want to use formatOnSave, but he doesn't want VSCode to delete the last line

**Comment by junmaqiang** [comment] 2017-08-11 08:29
@kzhui125  yeah

**Comment by CnSimonChan** [comment] 2017-08-11 10:02
Add `"files.insertFinalNewline": true` to your settings, Code will insert a blank line when saving.

**Comment by ToMakeSense** [comment] 2017-08-11 10:20
@junmaqiang Did you see my reply?

**Comment by junmaqiang** [comment] 2017-08-11 13:08
@ToMakeSense   I tried to install it, but then I deleted it and it didn't work

**Comment by ToMakeSense** [comment] 2017-08-11 14:05
@junmaqiang 

> [Wiki](http://editorconfig.org/) For Windows Users: To create an .editorconfig file within Windows Explorer, you need to create a file named .editorconfig., which Windows Explorer will automatically rename to .editorconfig.
<br>
A very useful tool with 5 stars. If you only  install it with no config file in your workspace, it won't work.

**Comment by mjbvz** [comment] 2017-08-17 05:45
This problem is caused by the eslint an extensions. If you still see the final new line in the file being delated, please set `"files.insertFinalNewline": true` and then disabling all other extensions to make sure one of these is not causing this issue. 

Closing as caused by extension

**Closed by mjbvz** 2017-08-17 05:45 UTC
Labels: caused-by-extension, javascript
