### ISSUE TITLE
Could not create TS service. Service state:{"type":0}

### ISSUE THREAD

**Issue by slepovron** [microsoft/vscode#111132] opened 2020-11-22 15:40 UTC
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic snap

OS Version: Linux Mint 19.3 Cinnamon
Full system information: https://termbin.com/kj158

Steps to Reproduce:
create file somename.js
select language mode javascript
start typing 
result error report of The TypeScript language service died 5 times right after it got started. Could not create TS service. Service state:{"type":0}

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2020-11-24 08:00
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by slepovron** [comment] 2020-11-25 10:35
Not so. I use the usual VSCode, but "yes" all installed applications are disabled now.

**Comment by slepovron** [comment] 2020-11-25 10:52
As far I see, my problem close to issues like #84618 or #88163 and other.


notificationsAlerts.ts:40 The TypeScript language service died 5 times right after it got started. The service will not be restarted.
onDidChangeNotification @ breadcrumbsModel.ts:39
mainThreadExtensionService.ts:65 [[object Object]]Could not create TS service. Service state:{"type":0}
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 Error: Could not create TS service. Service state:{"type":0}
	at T.service (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at T.executeImpl (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at T.executeWithoutWaitingForResponse (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at m.close (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at v.close (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at _.closeResource (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at _.onDidCloseTextDocument (/snap/code/50/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1)
	at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:719
	at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at b.acceptDocumentsAndEditorsDelta (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:723)
	at b.$acceptDocumentsAndEditorsDelta (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:722)
	at g._doInvokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876)
	at g._invokeHandler (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876)
	at g._receiveRequest (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875)
	at g._receiveOneMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874)
	at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872
	at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066
	at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at v.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256)
	at t.PersistentProtocol._receiveMessage (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261)
	at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258
	at l.fire (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at p.acceptChunk (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253)
	at /snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253
	at Socket.t (/snap/code/50/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263)
	at Socket.emit (events.js:223)
	at addChunk (_stream_readable.js:309)
	at readableAddChunk (_stream_readable.js:290)
	at Socket.Readable.push (_stream_readable.js:224)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181)
$onExtensionRuntimeError @ host.ts:10

**Comment by mjbvz** [comment] 2020-12-01 00:29
Did you try in insiders?

**Comment by mjbvz** [comment] 2020-12-01 20:27
Insiders tracks the next VS Code release

Closing since not reproducible in insiders (although perhaps worth checking if a simple re-install fixes the problem)

**Closed by mjbvz** 2020-12-01 20:27 UTC
Labels: needs more info

**Comment by slepovron** [comment] 2020-12-02 10:55
Re-installation (via snap store) did not help, but for now I will use the existing solution.
Thank you.

**Comment by mjbvz** [comment] 2020-12-02 23:39
Thanks for testing. Let me know if this happens again when the next release comes out (1.52)

**Comment by omril1** [comment] 2020-12-08 12:42
Had the same issue, the server crashes right after it starts, using insiders seems to work.

**Comment by w1ndy** [comment] 2020-12-18 07:02
This issue still appeared on 1.52.1, but I managed to resolve it with a complete reinstall. Just make sure that all settings are deleted.
