### ISSUE TITLE
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined   Code: -32603 

### ISSUE THREAD

**Issue by handsomepear** [Microsoft/vscode#32045] opened 2017-08-05 00:48 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment] 2017-08-07 21:10
Duplicate of #32059.

**Closed by kieferrm** 2017-08-07 21:10 UTC
