### ISSUE TITLE
Open URL links with custom protocol schema

### ISSUE THREAD

**Issue by BenceSzalai** [microsoft/vscode#170455] opened 2023-01-03 13:45 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2 (but reasonable to assume it affects all previous versions as well)
- OS Version: macOS 10.14 (may not be dependent on OS version)

Steps to Reproduce:

1. Grab a file that offers clicking on links. It can be a `@link {url}` tag in a PHP PHPDoc tag, an ```[link]({url})``` in MD file (where `{url}` is the actual url) or any similar.
2. Create a link using a protocol other than `file:`, `http:`, `https:` or `mailto:`, that is registered in the OS. A good example can be the fairly common `ftp:`, but there are many to try, such as `bitcoin:`, `ldap:`, `rtsp:`, `sip:`, `smb:` etc. See a list of well known protocols [here](https://en.wikipedia.org/wiki/List_of_URI_schemes).

Expected behaviour:
The clicked link should be opened by using the applications registered in the OS to handle the given protocol. Browsers usually do it perfectly for any protocol.

Actual behaviour:
VSCode ignores the protocol and tries to resolve the path as a file, which may succeed in some cases, but fails most the time. But even when succeeds, it results in the file being opened in VSCode editor instead of the associated URL handler program registered in the OS.

Ideal behaviour would be:
Anything matched by `/[\w][\w\d-+\.]*:\S*/gm` (or maybe a bit more sophisticated matching respecting [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) completely) should be clickable, regardless of protocol, and the protocol handling should be handed over to the OS if VSCode does not understand it.

The same issue has been closed without resolution before. See #104429.

**Comment by mjbvz** [comment] 2023-01-09 18:41
Duplicate of #133278

**Closed by mjbvz** 2023-01-09 18:41 UTC
