### ISSUE TITLE
ShellExecution changes working directory drive letter to lowercase on Windows

### ISSUE THREAD

**Issue by ChaosinaCan** [microsoft/vscode#70004] opened 2019-03-08 00:50 UTC
- VSCode Version: 1.32.0
- OS Version: Windows 7 (Windows_NT x64 6.1.7601)

I have a project that uses [Waf](https://waf.io) as a build system, and Waf treats paths as case-sensitive, even on a case-insensitive file system. I'm trying to write an extension that provides tasks for some common Waf commands, but Waf will run a (long) reconfigure process whenever it thinks the project has been moved to a different location. Running commands from a terminal (uppercase drive letter) and vscode (lowercase driver letter) tricks Waf into thinking the project was moved because the case of the drive letter in the working directory changed.

I'm trying to work around this by setting the `cwd` option of the `ShellExecution` to `vscode.workspace.rootPath` but with the drive letter fixed to uppercase, but vscode changes it back to lowercase when running the task. The case of the rest of the path does not appear to be modified.

Steps to Reproduce:

1. Create an extension that uses `registerTaskProvider()` to provide a task that explicitly sets the working directory to a path with an uppercase drive letter:

```typescript
function getTask() {
    const taskDef = {
        type: 'shell'
    };
    const execution = new vscode.ShellExecution('chdir', {
        cwd: 'C:\\Windows\\System32'
    }); 
    return new vscode.Task(taskDef, 'print_cwd', 'myext', execution);
}

export function activate(context) {
    context.subscriptions.push(vscode.tasks.registerTaskProvider('myext', {
        provideTasks: () => [getTask()],
        resolveTask(_task: vscode.Task): vsocde.Task | undefined => undefined,
    });
}
```

2. Debug the extension and run the "myext: print_cwd" task.

**Expected output:** C:\Windows\System32
**Actual output:** c:\Windows\System32

**Comment by alexr00** [comment] 2019-03-08 11:03
Task I used for testing:
````json
        {
            "type": "shell",
            "command": "chdir",
            "problemMatcher": [],
            "label": "Test Task",
            "options": {
                "cwd": "C:\\Windows\\System32"
            }
        }
````
The URI that Tasks passes into terminal has an uppercase drive letter for `path` but for `fsPath` the drive letter is lowercase. This appears to be by design: https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L580

@Tyriar, it looks like somewhere the terminal is using fsPath for the cwd which is losing the upper case drive letter.

@ChaosinaCan, are you using cmd.exe? It might be worth trying PowerShell.exe instead to see if it ignores case like that. It seems like it might since running `Get-Location` shows an uppercase drive letter.

**Comment by ChaosinaCan** [comment] 2019-03-08 15:53
I am using cmd.exe. I've always been running Waf's configure step manually from the integrated terminal until now:

```shell
D:\projects\test>waf.py configure
Setting top to                           : D:\projects\test
Setting out to                           : D:\projects\test\build
Checking for program 'git'               : C:\Program Files\Git\cmd\git.exe
...
```

I've used a task in tasks.json to start a build with Waf, but it looks like that just uses the cached paths from the configure step and doesn't care what the working directory is, so building works fine when run from either a task or the integrated terminal.

I just tried adding a task to tasks.json to run the configure step, and I'm seeing the same problem using either `type=shell` with cmd.exe as the shell or with `type=process`. Both of these give the same result:

```json
        {
            "label": "configure",
            "type": "shell",
            "command": "python waf.py configure",
            "problemMatcher": []
        }
```

```json
        {
            "label": "configure",
            "type": "process",
            "command": "python",
            "args": [
                "waf.py",
                "configure"
            ],
            "problemMatcher": []
        }
```

Output:

```
> Executing task: C:\Python27\python.exe waf.py configure <

invalid lock file in d:\projects\test
Setting top to                           : d:\projects\test
Setting out to                           : d:\projects\test\build
Checking for program 'git'               : C:\Program Files\Git\cmd\git.exe
```

Changing the task to use PowerShell as the shell _does_ work, so it looks like PowerShell is fixing the drive letter back to uppercase:

```json
{
            "label": "configure",
            "type": "shell",
            "command": "python waf.py configure",
            "problemMatcher": [],
            "windows": {
                "options": {
                    "shell": {
                        "executable": "powershell.exe"
                    }
                }
            }
        }
```

I'll try making my extension run tasks in PowerShell if on Windows. If vscode is intentionally normalizing all paths to have lowercase drive letters, it might be easier for me to patch Waf itself to fix drive letters to match the case on the file system instead of trying to modify my tasks in vscode to work around that. It would make things a lot easier though if vscode just normalized drive letters to uppercase to match how they're normally used in Windows.

**Comment by Tyriar** [comment] 2019-03-08 17:56
There's a lot of history here, some programs on Windows break when lowercase, some break when uppercase...

**Comment by hyurl** [comment] 2019-04-24 09:37
The same thing happened to me when debugging a project required a certain path with an uppercase driver letter, which is the default behavior and runs OK in CMD, PowerShell and WSL, however, the debugger changed the letter to lowercase, the project got broken done, now I have to set 'useWSL' in the `launch.json` to debug my project, which is very inefficient since sometimes the WSL could not be started.
@Tyriar The best choice would be not to modify any user preference and the system's default behavior.

**Comment by Tyriar** [comment] 2019-10-09 14:19
Closing as out of scope as there are issues with not changing it (which is why we started). You should report a bug to WAF for treating c:\ and C:\ differently if that's still a problem.

**Closed** 2019-10-09 14:19 UTC
Labels: *out-of-scope, integrated-terminal
