### ISSUE TITLE
Clicking and dragging in the minimap should cause it to scroll the editor.

### ISSUE THREAD

**Issue by jpoehls** [Microsoft/vscode#21915] opened 2017-03-03 18:03 UTC
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.4.0|
|vs-code-xml-format|fabianlauer|0.1.4|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|docomment|k--kato|0.0.14|
|Go|lukehoban|0.6.49|
|vscode-todo-parser|minhthai|1.8.7|
|vscode-elixir|mjmcloug|0.1.1|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|RustyCode|saviorisdead|0.19.1|
|vscode-wakatime|WakaTime|1.1.3|;

---

Steps to Reproduce:

1. Enable the minimap.
2. Open a file large enough to need scolling.
3. Click inside the minimap outside of the region currently visible in the editor (i.e., something you need to scroll to see). Without releasing your click, move your cursor up and down.

The click moves the editor to the region clicked but I'd expect further cursor movements before releasing the click to cause the selected region in the minimap to scroll with your cursor. That is, I'd expect it to behave the same as when you initially click the currently visible editor region in the minimap and move your cursor - how the editor scrolls with you.

**Comment by maxime4000** [comment] 2017-03-03 19:48
Just posting a resume of my duplicate here :

Idea : 
* Minimap opacity 50% and when your selecting some text and your mouse is interacting with the text on the minimap. (Setting ?)
* Enable/Disable scrolling with the minimap (Disable interaction with the minimap so it like interacting with the text).
* Changing the Opacity of the minimap.

![issue](https://cloud.githubusercontent.com/assets/4070713/23564759/3548eeb4-0019-11e7-8980-15bce365befc.gif)

**Comment by Tekbr** [comment] 2017-03-04 00:12
-- Sorry for the English, I used Google Translator --

I said something similar at #21822  and @alexandrudima  said it is duplicate of #21729 . I believe this one too, no?

**Comment by alexandrudima** [comment] 2017-03-06 10:12
@maxime4000 @Tekbr I think @jpoehls refers to something slightly different, where the first mouse down occurs on the minimap, but outside of the minimap slider:

> 3. Click inside the minimap outside of the region currently visible in the editor (i.e., something you need to scroll to see). Without releasing your click, move your cursor up and down.

@jpoehls Clicking on the minimap does not necessarily mean the minimap slider will move to where the click happened. I try to explain this by-design limitation in #21708.

**Closed by alexandrudima** 2017-03-06 10:12 UTC
