### ISSUE TITLE
Add support for hiding the folding controls.

### ISSUE THREAD

**Issue by aminroosta** [microsoft/vscode#82652] opened 2019-10-16 05:09 UTC
<img width="599" alt="Screen Shot 2019-10-16 at 1 05 49 PM" src="https://user-images.githubusercontent.com/2920178/66889729-155eec80-f016-11e9-90ac-6b5eca420333.png">

I'd want to hide the folding controls, permanently.
something like this, which is not supported at the moment.
```
    "editor.showFoldingControls": "never",
```

**Comment by gvsakhil** [comment] 2019-10-16 13:19
I am working on it @aminroosta

**Comment by aeschli** [comment] 2019-10-21 20:32
duplicate of #58708

**Closed by aeschli** 2019-10-21 20:32 UTC
