### ISSUE TITLE
High priority of recently declared variables in Intellisense

### ISSUE THREAD

**Issue by alnorris** [Microsoft/vscode#15631] opened 2016-11-17 10:35 UTC
Most of the code I see has the following pattern a lot of the time - the variables are used shortly after they are declared. My request is that we take this into account when ordering variables in Intellisense. 

Screenshot below should show externalFileID immediately after entering just 'e' since it was just declared.
<img width="674" alt="screen shot 2016-11-14 at 11 45 53" src="https://cloud.githubusercontent.com/assets/882627/20385786/bd85c2f0-acb0-11e6-83fa-151cb4b8524e.png">

Same goes with controller variable in this example
<img width="787" alt="screen shot 2016-11-17 at 10 24 11" src="https://cloud.githubusercontent.com/assets/882627/20385842/fa85224a-acb0-11e6-8f5b-8406d0447add.png">

**Comment by jrieken** [comment] 2016-11-18 08:38
dupe of #7273

**Closed by jrieken** 2016-11-18 08:38 UTC
Labels: suggest
