### ISSUE TITLE
warn "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

### ISSUE THREAD

**Issue by wqhk** [Microsoft/vscode#20110] opened 2017-02-07 08:28 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.0.1|

---

Steps to Reproduce:

1.
![ts-error](https://cloud.githubusercontent.com/assets/13541662/22683317/5ed6163c-ed52-11e6-9d4e-ac924103149d.png)

2.

**Comment by rmunn** [comment] 2017-02-07 16:26
Sounds like yet another duplicate of https://github.com/Microsoft/TypeScript/issues/13874.

**Comment by mjbvz** [comment] 2017-02-07 19:58
@wqhk Does the warning message mention something about not being able to find a `typescript/...` file? It's cut off in the screenshot

**Comment by mjbvz** [comment] 2017-02-10 00:49
Please check the `C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\typescript\node_modules\typescript\lib` path. There should be a `tsserver.js` file there. We've seen a few reports of over enthusiastic anti-virus softer deleting these files however.

If the file is missing, you can [use a custom typescript install with `typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). You can also reinstall vscode to restore the files. Be sure to exclude the typescript directory from antivirus to prevent this from happening again. Our official downloads ship the standard npm typescript package

**Closed by mjbvz** 2017-02-10 00:49 UTC
Labels: duplicate, External, needs more info, typescript
