### ISSUE TITLE
 Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#47257] opened 2018-04-05 21:28 UTC
Issue Id: <b>44dc5406-86ef-2ec0-ebd5-24bf5680277c</b><br /><br />*Versions* <br />- 1.21.1<br />-  9a199d77c82fcb82f39c68bb33c614af01c111ba<br />-  a903bd38fbe9006c076d218ff69fe1ee0160f815<br />-  b813d12980308015bcd2b3a2f6efa5c810c33ba5<br />*Stack* <br />TypeError: Cannot read property 'id' of undefined<br />[/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#130:84](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#L130:84)<br />    at Array.map (native)<br />[/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#128:22 (onComplete)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#L128:22 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1579:0 (then)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1579:0 (then))<br />[/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#127:4 (onComplete)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#L127:4 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0 (_notify)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1183:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#865:0 (enter)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L865:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#1081:0 (_run)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1081:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#1049:0 (onComplete)](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1049:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#1183:0](https://github.com/microsoft/vscode/blob/79b44aa704ce542d8ca4a3cc44cfca566e7720f1/src/vs/base/common/winjs.base.raw.js#L1183:0)<br />

**Comment by ramya-rao-a** [comment] 2018-04-05 21:30
@sandy081 As you mentioned in https://github.com/Microsoft/vscode/issues/45811#issuecomment-373318527, there is no reason why a local extension would not have the identifier. This is a similar case.

Also, we have a user reporting the same errors in #47200

**Comment by sandy081** [comment] 2018-04-06 08:39
Duplicate of #45811

**Comment by sandy081** [comment] 2018-04-06 08:40
@ramya-rao-a Yes. Added a check in management service to filter out such extensions. This fix is available in 1.22 release.

**Closed** 2018-04-06 08:39 UTC
Labels: *duplicate, error-telemetry
