### ISSUE TITLE
processes in terminal are slow after the recent update to 1.90

### ISSUE THREAD

**Issue by CoreyMcCoy** [microsoft/vscode#214552] opened 2024-06-07 05:37 UTC
Type: <b>Bug</b>

When cd-ing into folders, using git, or any other process in the terminal, it takes between 5 and 10 seconds. The process has always beed instant.

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.72GB free)|
|Process Argv|--crash-reporter-id e7589f9e-7396-46ac-b77a-b484c6475dcb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-color|ans|0.4.5
vscode-tailwindcss|bra|0.10.5
vscode-eslint|dba|2.4.4
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|10.4.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-language-babel|mgm|0.0.40
autopep8|ms-|2024.0.0
debugpy|ms-|2024.6.0
python|ms-|2024.8.0
vscode-pylance|ms-|2024.6.1
remote-wsl|ms-|0.88.2
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0
tailwind-snippets|Zar|1.0.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by orangesharing** [comment] 2024-06-07 05:57
I have the same issue and can confirm this was probably caused by the update. I logged in to my work laptop this morning to find exactly the same issue as described here. My private laptop was still in the previous version and worked fine, when I updated to 1.90 the same issue appeared.

* this slowness only seems to impact "Git Bash" terminal (running "Command Prompt" terminal, for example, shows no slowness)
* at the same time external (non-VSC) Git Bash terminal works without any delays
* the command is executed, but after it is completed, the terminal freezes for about 5-10s
* this slowness is around 5-10s delay after pretty much every action (after accepting the command with "Enter" and having it executed)
* any command, whether it uses Git functionality or not, is delayed; however, running Git commands results in an additional line  being printed to the console after the "freeze time" ends - in my case this was "form_tests)\x1b[0m\x0d\x0a$" (where "form_tests" is the suffix of the current branch name - "terraform_tests")
* starting the terminal is also delayed - a new terminal sub-window in the editor is created, around 5s passes, and only then the current directory location, branch, and command prompt appear (the terminal is unresponsive until then)

**Help/About section details:**

Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**System information:**

CPUs | 12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 63.64GB (51.80GB free)
Process Argv | --crash-reporter-id 0cbf98b0-e45c-4b35-8545-80df0b95ff43
Screen Reader | no
VM | 0%

**Extensions:**

terraform | 4op | 0.2.5
terraform | has | 2.30.2
azure-pipelines | ms- | 1.228.0
vscode-azureresourcegroups | ms- | 0.9.1
vscode-docker | ms- | 1.29.1
vscode-kubernetes-tools | ms- | 1.3.16
remote-ssh | ms- | 0.110.1
remote-ssh-edit | ms- | 0.86.0
remote-wsl | ms- | 0.88.2
azure-account | ms- | 0.12.0
powershell | ms- | 2024.2.2
remote-explorer | ms- | 0.4.3
fabric8-analytics | red | 0.9.4
java | red | 1.31.0
vscode-xml | red | 0.27.1
vscode-yaml | red | 1.14.0
intellicode-api-usage-examples | Vis | 0.2.8
vscodeintellicode | Vis | 1.3.1
vscode-java-debug | vsc | 0.57.0
vscode-java-dependency | vsc | 0.23.6
vscode-java-pack | vsc | 0.27.0
vscode-java-test | vsc | 0.41.1
vscode-maven | vsc | 0.44.0

**A/B experiment info:**

vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

**Comment by orangesharing** [comment] 2024-06-07 06:10
OK, after commenting on this issue (the most up to date one) I have found at least two other fresh ones that report exactly the same problems - #214448 and #214407. The latter one proposes to set "terminal.integrated.shellIntegration.enabled" to OFF - this seems to have fixed the issue for me (both the slowness, and injection of unnecessary characters after Git commands).

I think this one can be marked as duplicate.

**Comment by TomaszKowalik** [comment] 2024-06-07 07:16
I have exact same issue after todays update

```
Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by TomaszKowalik** [comment] 2024-06-07 09:24
> It happened to me. I can't even launch my Spring boot App while using Git Bash as console in my `launch.json` file

I also had that terminal bug, but as mentioned above: disabling `terminal.integrated.shellIntegration.enabled` fixed that issue for me

**Comment by iwangbowen** [comment] 2024-06-07 09:30
It happened to me. I can't even launch my Spring boot App while using Git Bash as console in my `launch.json` file

> > It happened to me. I can't even launch my Spring boot App while using Git Bash as console in my `launch.json` file
> 
> I also had that terminal bug, but as mentioned above: disabling `terminal.integrated.shellIntegration.enabled` fixed that issue for me

disabled the feature and It worked👍

**Comment by meganrogge** [comment] 2024-06-07 16:56
There's a fix for this that will be available in the next insider's and will be released as a recovery candidate to stable next week.

/duplicate https://github.com/microsoft/vscode/issues/212090

**Closed by meganrogge** 2024-06-07 16:56 UTC
Labels: new release
