### ISSUE TITLE
Tab sizes should be a fixed size

### ISSUE THREAD

**Issue by karai17** [Microsoft/vscode#38594] opened 2017-11-17 08:45 UTC
- VSCode Version: 1.18
- OS Version: Fedora 26

![image](https://user-images.githubusercontent.com/590332/32938152-9d6c566c-cb51-11e7-8d00-e76411abc96b.png)

In my above screenshot I have several tabs open, all of them being a variable length. This can cause some frustration when trying to close several tabs as you generally cannot just click `X` a few times and have tabs disappear, you must continuously re-position the cursor which is both frustrating and times unnecessary time.

I think managing tabs in a similar fashion to how Google Chrome does it would be handy. All tabs are the same size and the more tabs fill up your screen, the smaller they get to accommodate. Then, if you start closing tabs, they stay the same, shrunken size until you move your cursor off of the tab bar, at which they resize to fill the space.

It would also be handy if all tabs had an `X` on them, not just the current selected tab.

**Comment by bpasero** [comment] 2017-11-17 13:15
I would say this is a duplicate of https://github.com/Microsoft/vscode/issues/15048

**Comment by StefanScherer** [comment] 2017-12-23 09:09
First, thanks for improving and letting the user choose the behaviour with `workbench.editor.tabSizing`!
It was difficult to google for it as most hits are about the tab sizes IN the editor itself :-)

I now tried this new user setting in VSCode 1.19.1 with `"workbench.editor.tabSizing": "shrink"`, but this is still not what is described here.
Open some files with different long file names. Then try to close some tabs by just tapping on touch pad multiple times. I can do this in Safari, in Chrome, in Atom. But in VSCode it doesn't feel "right" as I often miss the next close button in the tab due to the different size of each tab (eg. when there's a very short file name).

So I wouldn't say this is a duplicate. It's more a suggestion to add `"workbench.editor.tabSizing": "fixed"` to make more users happy.

**Comment by StefanScherer** [comment] 2017-12-23 09:59
@bpasero So do I understand this right that adding `.tab.sizing-fixed` and `.tab.sizing-fixed.tab.close-button-off` and the `fixed` option and description in a similar way to https://github.com/Microsoft/vscode/pull/39176/files#diff-7cd861a374426e39c37cb48fd70bbc65R53  could help for this issue?

Now I have to learn to go from user to developer mode and start building vscode from source to test this so I can try to send a PR for that... :-)

**Comment by bpasero** [comment] 2017-12-23 13:44
@StefanScherer see EW7764

**Comment by bpasero** [comment] 2017-12-28 07:58
Reopening to capture the idea of chromes tab model where each tab has the same size and never shows a scrollbar (all tabs shrink in the same way).

**Comment by BinaryBen** [comment] 2018-07-06 06:29
I came to suggest the Chrome tab model be implemented and adopted by default. Glad to see an issue already opened. Having to reposition the mouse to close a lot of tabs is getting to be a tad annoying. :)

**Comment by bpasero** [comment] 2018-09-14 11:51
I feel this is a duplicate of https://github.com/Microsoft/vscode/issues/40290 (which I have renamed now too). Making each tab same size will not solve this issue because there can be a variable number of actions showing up in the editor toolbar that can push tabs around.

**Closed by bpasero** 2018-09-14 11:51 UTC
Labels: feature-request, workbench-tabs
