### ISSUE TITLE
vscode unable to open files, change settings. Dev tools explode with errors with every action.

### ISSUE THREAD

**Issue by Hamilsauce** [microsoft/vscode#95024] opened 2020-04-11 22:50 UTC
- VSCode Version: 1044 user setup
- OS Version: Windows 10 Home 18362

Steps to Reproduce:

1. I don't know how to reproduce it. I believe it started after i changed a color setting, but hard to imagine that has resulted in a meltdown

Does this issue occur when all extensions are disabled?: Yes/No Yes. 

Program fires off with errors in the dev tools with every move. It can't locate any file I try to open, sometimes can't open UI menus (sometimes it can),  and eventually just freezes up and asks to be reloaded. I've tried uninstalling and reinstalling with 3 different versions from the site, but each time loads up like it never was uninstalled (I thought I deleted all the residual files after uninstall). Also, the the install on a different account for this computer works just fine.

Don't know what else to tell you specifcally, but I have plenty of logs and error reports.  Let me know if you need anything else and appreciate any help.

[-1586643907344.log](https://github.com/microsoft/vscode/files/4465599/-1586643907344.log)
[-1586643745720.log](https://github.com/microsoft/vscode/files/4465600/-1586643745720.log)
[renderer1.1.log](https://github.com/microsoft/vscode/files/4465590/renderer1.1.log)
[main.log](https://github.com/microsoft/vscode/files/4465591/main.log)

**Comment by RMacfarlane** [comment] 2020-04-12 15:58
Duplicate of https://github.com/microsoft/vscode/issues/94931

**Closed** 2020-04-12 15:57 UTC
Labels: *duplicate
