### ISSUE TITLE
VSCodeInsider_RemoteExplorer_Keyboard:Tooltip is not accessible by the keyboard.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/vscode#89090] opened 2020-01-22 13:31 UTC
**Environment Details:​**
VSCode Version: 1.42.0-insider (System setup)
Operating System: MacOS
Mac version: 10.15.1 (19B88)

**Repro Steps:​**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer" and click on it.
4. Navigate till "Remote Explorer" control .
5.  Navigate to (?) icon present in the screen.
6. Check tooltip is  accessible by the keyboard or not.

**Actual:**
Tooltip is not  accessible by the keyboard.Here it available whenever user mouse over on that icon.

**Expected:​**
Tooltip  should be accessible by the keyboard. When (?) icon receives the keyboard focus the tooltip should be visible.

**Same issue observed for the below scenario:**
**1.VS ONLINE**
1. Open VS Code insider 
2. Navigate till "Extension" button and search for the "Visual Studio Online"
3. Click on "Visual Studio Online" and navigate till "Remote Explorer"
4. Navigate till "VS ONLINE" control .
5. Check the tooltip is accessible or not for the below control.

**2.Extension_VisualStudioOnline**
1.Open VS Code insider 
2.Navigate till "Extension" button and search for the "Visual Studio Online"
3.Navigate  right panel till "Extension: Visual Studio Online"

**User Impact:​**
Keyboard only user does not get tooltip information if it is not visible when keyboard focus present on the (?) icon control.

**Comment by isidorn** [comment] 2020-01-22 14:06
Duplicate of https://github.com/microsoft/vscode/issues/52016

**Closed by isidorn** 2020-01-22 14:06 UTC
