### ISSUE TITLE
Provide "Filter" API in custom views

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#54323] opened 2018-07-14 22:30 UTC
Just like the new **Outline** view has, that _Filter_ inputbox would be really handy for extensions to use. 

Better yet if the filter was _"automatic"_, just like the `QuickPick` today.

![image](https://user-images.githubusercontent.com/3781424/42728875-4cff94ca-879c-11e8-9679-53a56cde7fe1.png)

Thanks for your help

**Comment by eamodio** [comment] 2018-07-15 04:58
This is a duplicate of https://github.com/Microsoft/vscode/issues/50062

**Closed** 2018-07-15 10:16 UTC
