### ISSUE TITLE
Mac: click-through from other app should focus on the editor area that was clicked

### ISSUE THREAD

**Issue by zneak** [Microsoft/vscode#32152] opened 2017-08-08 17:47 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. Open Terminal area
2. In Code, click the code area to focus it
3. Switch to another app
4. Click terminal area in Code through another app

The expected behavior for click-through on macOS is that focus goes to the area that you've clicked. For instance, if I have a (standard) Terminal window with two tabs open and the Finder is the foreground program, clicking on a tab on that terminal window will both bring the Terminal app in focus and switch to the tab that I've clicked.

With Code, the actual behavior is that the program goes to the foreground but the focus within the app stays with whatever was focused at the time Code was put to the background.

This frequently causes me to start typing commands in my editor view.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment] 2017-08-14 21:36
Duplicate of https://github.com/Microsoft/vscode/issues/24634

**Closed by Tyriar** 2017-08-14 21:36 UTC
Labels: integrated-terminal
