### ISSUE TITLE
 Cannot read property 'getViewLineMinColumn' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93305] opened 2020-03-24 13:04 UTC
Issue Id: <b>9e77471a-087b-95f6-04fb-36f45f00436b</b><br /><br />*Versions* <br />- 1.43.1<br />-  e5834d3280fcd04898efeac32b9cf1b893f9b127<br />*Stack* <br />TypeError: Cannot read property 'getViewLineMinColumn' of undefined<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#770:31 (getViewLineMinColumn)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/common/viewModel/splitLinesCollection.ts#L770:31 (getViewLineMinColumn))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#550:20 (getLineMinColumn)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/common/viewModel/viewModelImpl.ts#L550:20 (getLineMinColumn))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#456:29 (getCompletelyVisibleViewRange)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/common/viewModel/viewModelImpl.ts#L456:29 (getCompletelyVisibleViewRange))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#406:32 (getVisibleRanges)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/common/viewModel/viewModelImpl.ts#L406:32 (getVisibleRanges))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#452:35 (getVisibleRanges)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/browser/widget/codeEditorWidget.ts#L452:35 (getVisibleRanges))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#86:21 (_readVisibleRangesFromCodeEditor)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/api/browser/mainThreadEditor.ts#L86:21 (_readVisibleRangesFromCodeEditor))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#31:55 (readFromEditor)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/api/browser/mainThreadEditor.ts#L31:55 (readFromEditor))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#203:34 (_updatePropertiesNow)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/api/browser/mainThreadEditor.ts#L203:34 (_updatePropertiesNow))<br />[/vs/workbench/api/browser/mainThreadEditor.ts#268:9 (call)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/api/browser/mainThreadEditor.ts#L268:9 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#1555:66](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/editor/browser/widget/codeEditorWidget.ts#L1555:66)<br />    at s.emitScrollChang<br />

**Comment by alexdima** [comment] 2020-05-25 10:11
Duplicate of #97447

**Closed by alexdima** 2020-05-25 10:11 UTC
Labels: error-telemetry
