### ISSUE TITLE
launch.json configuration's autocomplete (snippet) not displaying extension configurations

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#80601] opened 2019-09-10 00:54 UTC
Issue Type: <b>Bug</b>

1. Install Microsoft C/C++ extension
2. Create a simple cpp file (e.g. main.cpp)
```
int main(void)
{
   return 0;
}
```
3. Create a launch.json file
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    ]
}
```
4. Try to insert a snippet into the configurations array and the dropdown list does not list the C++ extension configurations.

Note: The configurations will be shown if you use the ```"Add Configuration..."``` button on the lower right hand corner.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (4.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.21.3
azure-pipelines|ms-|1.152.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
mssql|ms-|1.6.0
remote-containers|ms-|0.59.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
cpptools|ms-|0.25.1
csharp|ms-|1.20.0
mono-debug|ms-|0.15.8
vscode-node-azure-pack|ms-|0.0.9
azurerm-vscode-tools|msa|0.6.0
code-spell-checker|str|1.7.17
azure-iot-toolkit|vsc|2.9.0

</details>

**Comment by isidorn** [comment] 2019-09-11 09:00
I can not reproduce this with latest vsocde insiders https://code.visualstudio.com/insiders/

@WardenGnaw what are you doing differently than me in this screenshot (note that I triggered inteli-sense via `cmd + space`)? Can you reproduce with an empty user-data-dir and no other extensions?

fyi @jrieken in case we changed something in snippets

![Screenshot 2019-09-11 at 10 58 35](https://user-images.githubusercontent.com/1926584/64683240-2e0e3c80-d483-11e9-9ad9-f66a3bd23fb0.png)

**Comment by isidorn** [comment] 2019-09-11 09:07
Actually I can reproduce this with stable. But is fixed in insers. So we seem to have pushed some fix for this.

**Comment by isidorn** [comment] 2019-09-11 09:15
I take it back. I can not reproduce this with stable. If I activate the extension first (click on a .cpp file).

@WardenGnaw @steevegl-axes can you please provide more information on what is different compared to previous stable? And let me know what you are doing differently than me?

**Comment by isidorn** [comment] 2019-09-11 09:20
@steevegl-axes I can actually reproduce this issue with Python. But not with any other extension due to that I believe it is a python issue, can you please create an issue in the python extension repository https://github.com/microsoft/vscode-python
fyi @DonJayamanne 

@WardenGnaw for C++ please answer my questions from above. Thanks

**Comment by steevegl-axes** [comment] 2019-09-11 12:58
> @steevegl-axes I can actually reproduce this issue with Python - it is not the same as the C++ I accidently merged them together. But not with any other extension due to that I believe it is a python issue, can you please create an issue in the python extension repository https://github.com/microsoft/vscode-python
> fyi @DonJayamanne
> 
> @WardenGnaw for C++ please answer my questions from above. Thanks

For reference, one issue has already been open: https://github.com/microsoft/vscode-python/issues/7304

**Comment by WardenGnaw** [comment] 2020-01-27 23:25
@isidorn I'm not sure if this is the same issue but the configurations are also missing in `*.code-workspace`. Both `ctrl (or cmd) + space` do not display the C++ configurations in the `configuration` section. 

I added a DocumentSelector for .code-workspace and registered it as a completionItemProvider but it also does not show snippets. 

Since there is no `Add Configuration` for `.code-workspace` there is no way to provide launch configurations there. 

![image](https://user-images.githubusercontent.com/3953714/73222799-001b5300-4119-11ea-889d-bd8ce621efa2.png)

Related: https://github.com/microsoft/vscode-cpptools/issues/4891

**Comment by isidorn** [comment] 2020-01-28 09:54
Yes, I believe this is the same issue.

**Closed** 2020-07-30 15:55 UTC
Labels: *out-of-scope, debug, under-discussion
