### ISSUE TITLE
VS Code hangs on the CentsOS 7 right after started

### ISSUE THREAD

**Issue by ipizhenko** [microsoft/vscode#121298] opened 2021-04-14 15:06 UTC
- VS Code Version: 1.55.2
- OS Version: CentOS 7 with KDE4 desktop with latest updates

Steps to Reproduce:

1. Start VS Code
2. Try to click on some UI element or resize window

There is no reaction. Also after window is resized, for example maximized, content of window is not redrawn.
This started to happen after update (not sure which version was there before, but it was installed this year and was working good)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2021-04-14 16:39
/duplicate of #115784

New Electron versions don't support CentOS 7. See linked issue for details and probable workarounds

**Closed** 2021-04-14 16:40 UTC
Labels: *duplicate, new release

**Comment by ipizhenko** [comment] 2021-04-14 17:29
From here https://github.com/microsoft/vscode/issues/115784#issuecomment-817187000
Here's a solution that worked for me ...

install ghettoforge repo for CentOS 7
yum --nogpg install https://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
install gcc10-libstdc++.x86_64
yum install gcc10-libstdc++.x86_64
create link to new libstdc++ where VSCode will find it at runtime
 ln -s /opt/gcc-10.2.1/usr/lib64/libstdc++.so.6 /usr/share/code/
