### ISSUE TITLE
Insiders -  Custom title bar font size too small

### ISSUE THREAD

**Issue by varadero** [Microsoft/vscode#54796] opened 2018-07-21 15:39 UTC
Issue Type: <b>Bug</b>

Just upgraded VSCode Insiders and noticed that custom toolbar menus font size became too small. Context menu inside code windows has reasonable font size. The strange thing is that if I start decreasing the font size of code windows (by pressing ```CTRL + -```), the size of custom menus starts increasing, when I increase the font size of code windows (by pressing ```CTRL + =```),the size of custom menus starts decreasing    - see animated .gif file.

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:39.569Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.80GB (3.96GB free)|
|Process Argv|C:\Users\Svincho\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
githistory|don|0.4.2
tslint|eg2|1.0.34
vscode-mocha-sidebar|mat|0.20.12
vscode-icons|rob|7.24.0

</details>

![insiders-custom-menu-font-size-too-small](https://user-images.githubusercontent.com/7610713/43037321-2d54c90a-8d15-11e8-95b3-994c9743b533.gif)

This is my settings file:
```json
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "editor.dragAndDrop": false,
    "explorer.enableDragAndDrop": false,
    "git.autofetch": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/node_modules": true
    },
    "extensions.autoUpdate": false,
    "window.zoomLevel": 2,
    "editor.minimap.enabled": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "window.titleBarStyle": "custom"
}
```

**Comment by LubosMertak** [comment] 2018-07-22 16:56
I have the same issue.

**Comment by sbatten** [comment] 2018-07-23 18:32
dupe of #54575

**Closed by sbatten** 2018-07-23 18:32 UTC
Labels: menus
