### ISSUE TITLE
Source Control menu showing wrong branches of worktrees contained in bare repository

### ISSUE THREAD

**Issue by iferc** [microsoft/vscode#164363] opened 2022-10-23 06:38 UTC
Does this issue occur when all extensions are disabled?: *Yes*

- VS Code Version: 1.73.0-insider
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Clone a bare repository. (ex: `git clone --bare git@github.com:microsoft/vscode.git`)
2. Go into the directory of the cloned bare repository. (ex: `cd vscode.git`)
3. Create a `trees` folder in the bare repository folder. (ex: `mkdir trees`)
4. Add a worktree for multiple valid branches (ex: `git worktree add trees/1.70 release/1.70; git worktree add trees/1.71 release/1.71; git worktree add trees/1.72 release/1.72`)
5. Add the folders `trees/1.70`, `trees/1.71`, and `trees/1.72` to a VSCode workspace.
6. Open the Source Control menu.
8. See that each each worktree folder shows up as a distinct repository, but that they all show the primary branch as though it were the branch that is checked out instead of their actual checked out branch. (ex: all would be `main` but should be `release/1.70`, `release/1.71`, and `release/1.72`)

Screenshot included is from the example instructions above where none of these folders have `main` checked out, yet all show `main` as their checked out branch:

<img width="1020" alt="Screen Shot 2022-10-23 at 2 35 28 AM" src="https://user-images.githubusercontent.com/26846430/197377796-e9f4bb1f-3859-4294-8db3-bdfac9a1e00f.png">

I can confirm that the correct branch names were displayed at least as of 1.70.2 but I have not yet tried more versions in-between.

**Comment by jarrodldavis** [comment] 2022-11-02 21:11
I'm having the same issue with a non-bare repository. I have an additional worktree and today's VSCode update is showing the checked out branch of the main worktree instead of the current directory's worktree. This worked fine in v1.72, and is now broken in v1.73. This also messes up the GitHub Pull Requests extension since it is using the wrong branch to get PR information.

**Comment by bluemonkmn** [comment] 2022-11-02 21:24
This was working correctly in the prior version, but today when I applied the newly available v1.73 I am seeing this problem is all my secondary worktrees.

**Comment by jarrodldavis** [comment] 2022-11-02 21:43
This appears to be caused by #162572, specifically here where it's getting the `HEAD` branch from the filesystem (instead of using `git` commands):

https://github.com/microsoft/vscode/blob/9c802415e11bf11230720bc4a93397c338121da8/extensions/git/src/git.ts#L2086

`this.dotGit.commonPath` seems to refer to the main worktree's `.git` path, and `this.dotGit.path` is the current working directory's `.git` path. This should be checking `path` before `commonPath`:

```diff
diff --git a/extensions/git/src/git.ts b/extensions/git/src/git.ts
index 7c49b545f8c..1538a356a31 100644
--- a/extensions/git/src/git.ts
+++ b/extensions/git/src/git.ts
@@ -2083,7 +2083,7 @@ export class Repository {
 	}
 
 	async getHEADFS(): Promise<Ref> {
-		const raw = await fs.readFile(path.join(this.dotGit.commonPath ?? this.dotGit.path, 'HEAD'), 'utf8');
+		const raw = await fs.readFile(path.join(this.dotGit.path ?? this.dotGit.commonPath, 'HEAD'), 'utf8');
 
 		// Branch
 		const branchMatch = raw.match(/^ref: refs\/heads\/(?<name>.*)$/m);
```

**Comment by Patrick-Ze** [comment] 2022-11-03 07:55
I have the same problem with VS Code 1.73.0. This issue also breaks GitLab extension since it gets wrong branch

**Comment by brainz80** [comment] 2022-11-04 09:33
Can the builtin extensions be updated independently from updating vscode? In that case this shouldn't be hard to fix.

**Comment by lszomoru** [comment] 2022-11-04 09:44
@brainz80, it cannot. I am looking at having this fixed in Insiders early next week.

**Comment by crossan007** [comment] 2022-11-04 13:40
I'm having this same issue in 1.73.0 (user setup).

I've got 3 repositories each having 4 active git-worktrees in a multi-root workspace, and each worktree seems to indicate the same checked out branch.

**Comment by jportner** [comment] 2022-11-04 13:52
I'm also having a problem in 1.73.0 that appears to be the same root cause.
I have a single repo with three working trees checked out, and VS Code always thinks that I'm on the primary working trees.

This is causing problems for the GitHub Pull Requests and Issues extension (I can only review PRs when using the primary working tree).

**Comment by f4n0** [comment] 2022-11-04 15:46
yep, me too!

**Comment by dmy147** [comment] 2022-11-05 05:56
same issue

**Comment by lszomoru** [comment] 2022-11-05 07:41
The fix will be included into Monday's Insiders release. Apologies for the inconvenience.

**Comment by iferc** [comment] 2022-11-05 20:26
I appreciate the quick fix! Thank you.

**Comment by SimonHarrisonSH** [comment] 2022-11-07 08:41
@lszomoru  Any idea when this will be in the regular release? I'd rather not have to switch to the insiders build.

**Closed** 2022-11-09 10:16 UTC
Labels: bug, git, candidate

**Comment by lszomoru** [comment] 2022-11-09 12:33
Verification steps:
```
mkdir main && cd main
git init .
echo a >> a
git commit . -m 'init'
git worktree add -b dev ../dev # important!
code ../dev
```

Expected: VS Code status indicator should show `dev` as the branch name
