### ISSUE TITLE
Custom coloring for picked color theme

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/vscode#17654] opened 2016-12-21 09:39 UTC
It would be great if there section in user settings appear where user can define custom coloring for picked color theme and those override or extend existing. Because now if I want to add just different color for function color i have to create new theme from scratch.

**Comment by egamma** [comment] 2016-12-21 15:10
FYI @aeschli

**Comment by aeschli** [comment] 2017-01-19 18:06
duplicate of #11556

**Closed by aeschli** 2017-01-19 18:06 UTC
Labels: feature-request, themes
