### ISSUE TITLE
Javascript syntax highlighting fails in import statement in jsx file when it comes after an import ending with a comment

### ISSUE THREAD

**Issue by granmoe** [Microsoft/vscode#32426] opened 2017-08-13 18:23 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-styled-components|jpo|0.0.8
org-mode|too|0.1.3
vim|vsc|0.9.0

---

Steps to Reproduce:

1. Create a jsx file
2. Import something without binding it to a name
3. Add a comment on the end of the line
4. Go to next line, import something and bind it to a name

Reproduces without extensions: Yes

![vs code bug](https://user-images.githubusercontent.com/5620706/29252342-9f017a2e-802a-11e7-8e24-99f6c1bcf0f3.PNG)

![vs code no bug](https://user-images.githubusercontent.com/5620706/29252346-a3cac060-802a-11e7-9274-62c156247a07.PNG)

**Comment by granmoe** [comment] 2017-08-13 18:29
Actually, looks like it's happening with a named import, too.

![vs code bug with named import](https://user-images.githubusercontent.com/5620706/29252376-5fe86298-802b-11e7-97e5-b795bc388ad1.PNG)

**Comment by granmoe** [comment] 2017-08-13 18:32
Also, appears to go away when a semicolon is added after the first import:

![vs code no bug with semicolon](https://user-images.githubusercontent.com/5620706/29252393-cead6322-802b-11e7-8a91-88a5e4a86376.PNG)

**Comment by mjbvz** [comment] 2017-08-16 20:54
I believe this is a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/485

Please try updating to VS Code 1.15 which includes this fix

**Closed by mjbvz** 2017-08-16 20:54 UTC
Labels: grammar, javascript, upstream

**Comment by granmoe** [comment] 2017-08-16 20:56
Thank you for your work on the best editor out there :-)
