### ISSUE TITLE
Support borders in editor decorations

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#41958] opened 2018-01-22 10:20 UTC
- VSCode Version:  1.19.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Select a section of text
![image](https://user-images.githubusercontent.com/2784308/35215778-56218358-ffa0-11e7-86cb-3c186053aaf0.png)

The same color is too close after the same match, although we can customize the background color(see #1636), but we can't solve the problem fundamentally. I think it should be to modify the highlighting style, for example, you can customize it to border.

Sublime Text：

![image](https://user-images.githubusercontent.com/2784308/35215924-c9cb2cd2-ffa0-11e7-9e0b-10409dae7f12.png)

**Comment by alexandrudima** [comment] 2018-01-22 15:39
Duplicate of #41908

**Closed by alexandrudima** 2018-01-22 15:39 UTC
Labels: editor-rendering, feature-request
