### ISSUE TITLE
Open Terminal in External Window broken

### ISSUE THREAD

**Issue by srvance** [microsoft/vscode#126261] opened 2021-06-14 15:35 UTC
Issue Type: <b>Bug</b>

1. Command-Shift-P
1. Try to launch "Open Terminal in External Window"
1. No terminal launches and you see the following in the console
```
ERR Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at It.spawnTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:31:151)
    at It.openTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:30:79128)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```

VS Code version: Code 1.57.0 (Universal) (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (10.41GB free)|
|Process Argv|--crash-reporter-id 532c07cc-df37-4bcc-b7cf-3b92c61cd904|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.23.0
gitlens|eam|11.5.1
vscode-great-icons|emm|2.1.77
prettier-vscode|esb|6.4.0
endwise|kai|1.4.2
ruby-rubocop|mis|0.8.5
vscode-gem-lens|nin|0.3.1
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by meganrogge** [comment] 2021-06-14 18:49
/duplicate of #125985 will be fixed in the recovery build we release very soon

**Closed by meganrogge** 2021-06-14 18:49 UTC
