### ISSUE TITLE
Copy all when markdown document is collapsed is incomplete

### ISSUE THREAD

**Issue by sixeyes** [microsoft/vscode#83985] opened 2019-11-05 14:14 UTC
We have written 
Issue Type: <b>Bug</b>

I tried to attach the document but .md isn't allowed. Tried to attach as .txt but it failed, so it's inline.

If the document is collapsed (Ctrl+K, Ctrl+0) and Ctrl+A to select all, the copied text does not include the WaveRecord onwards, it is only copied as far as the #Data Structures (line 6)

```
# (APIBlueprint document)

# Introduction
This is my introduction

# Data Structures

## WaveRecord (object)

+ mailingId: 103 (number, required) - The mailing identifier.
+ waveId: 253 (number, required) - The wave identifier.
+ name: `Initial Test` (string, required) - The wave name.
+ portion: 500 (number, required) - The wave portion of the mailing (1 - 10000), 10000 represents the whole mailing.
+ status: `Processed` (enum, required) - The wave status.
    + Members
        + `Draft` - The wave has been created but not queued.
        + `Processed` - The wave has been processed.
        + `Queued` - The wave has been queued but not processed.
+ createDate: `2016-07-30T16:28:22` (string, required) - The create date (UTC).
+ modifyDate: `2016-07-31T07:49:18` (string, required) - The last modified date (UTC).
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|17.58GB (8.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-guid|hea|1.4.19
apib|Jar|0.0.2
csharp|ms-|1.21.5
vscode-apielements|vnc|0.6.7
maple|yjt|1.2.8

(9 theme extensions excluded)

</details>
the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment] 2019-11-06 08:53
Duplicate of #41744

**Closed by aeschli** 2019-11-06 08:53 UTC
Labels: bug
