### ISSUE TITLE
github.vscode-pull-request-github' wants API proposal 'treeItemCheckbox'

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#186291] opened 2023-06-27 09:25 UTC
Testing #186164

```
WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'treeItemCheckbox' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
```

**Comment by alexr00** [comment] 2023-06-27 09:43
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4963

**Closed by alexr00** 2023-06-27 09:43 UTC
Labels: bug
