### ISSUE TITLE
Window doesn't relocate from detached monitor

### ISSUE THREAD

**Issue by addestroyer24** [microsoft/vscode#83667] opened 2019-10-30 15:02 UTC
Issue Type: <b>Bug</b>

When using multiple monitors:
1.  Open VSCode, move it to a secondary display, minimize VSCode
2.  Disconnect computer from secondary displays.
3.  Attempt to restore VSCode

Expected:
VSCode window restores on the primary monitor

Actual:
VSCode window does not display.  Task bar indicates that the window has restored and has focus (focus is taken from previously focused window), but window cannot be located or moved.  If minimized from the task bar, I can briefly see the window collapse animation coming from offscreen where the window was located prior to disconnecting secondary monitors.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (23.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
xml|Dot|2.5.0
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.1
csharp|ms-|1.21.5
shell-launcher|Tyr|0.3.0

</details>

**Comment by bpasero** [comment] 2019-10-31 06:03
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by bpasero** [comment] 2019-10-31 06:29
Unclear to me yet if this is an issue in our code or upstream. Needs investigation, up for grab.

**Comment by bpasero** [comment] 2019-10-31 10:59
I cannot reproduce, so my initial comment is true:

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-31 10:59 UTC
Labels: upstream, windows
