### ISSUE TITLE
Slow performance resizing the panel when editors are showing

### ISSUE THREAD

**Issue by yangwen2** [Microsoft/vscode#25924] opened 2017-05-04 19:24 UTC
- VSCode Version: 1.12.0
- OS Version: MacOS Sierra 10.12.4
- Resolution: 2560x1440 @ 60Hz . with the editor at full screen size.  When resized to ~half of the screen, the UI issue below does not occur.

Steps to Reproduce:

1.  Open vsc with opened editors
2.  Open integrated terminal
3.  Resize integrated terminal and experience the unresponsive UI refresh.
4.  Open a few files
5.  Enable split editor and resize the different columns to experience the unresponsive UI refresh.

**Comment by kieferrm** [comment] 2017-05-04 22:12
@yangwen2 Do you by any chance start code with `--disable-gpu`?

**Comment by yangwen2** [comment] 2017-05-04 22:18
The issue occurs sans the --disable-gpu option.  I just tried it with disable gpu and there is tremendous frame dropping effect (flashing black frames) when resizing the panes.  However the lagginess does seem to go away in that mode.  The perceived smoother fps may be due to actual frame dropping going on.

**Comment by bpasero** [comment] 2017-05-05 15:24
@yangwen2 did this happen with 1.11? can you share a video how this looks for you?

**Comment by yangwen2** [comment] 2017-05-05 15:56
Issue did not occur with 1.11

[https://gfycat.com/ElderlyGreenDarklingbeetle](url)

**Comment by bpasero** [comment] 2017-05-05 16:07
@yangwen2 can you open another of the panels (e.g. "Output"), then restart VS Code and then see if the same slow performance can be seen? I am trying to find out if this could be a regression from the integrated terminal or not.

**Comment by yangwen2** [comment] 2017-05-05 16:11
It's still slow with the Output panel.  Dragging the boundary between the split editors also exhibit this UI issue.  However, it's not nearly as laggy as resizing the terminal

settings.json: 
`{
    "window.zoomLevel": 0,
    "typescript.check.tscVersion": false,
    "editor.cursorStyle": "block",
    "editor.cursorBlinking": "solid",
    "vsicons.projectDetection.autoReload": true,
    "git.confirmSync": false,
    "workbench.colorCustomizations": {
        "activityBar.foreground": "#c8cace",
        "activityBarBadge.background": "#da291c",
        "statusBar.background": "#2185C5",
        "tab.activeBackground": "#385666",
        "tab.inactiveForeground": "#D1D1D1",
        "editor.selectionBackground": "#29404A",
        "editorCursor.foreground": "#FFEE00",
        "editor.lineHighlightBackground": "#37424A",
        "contrastActiveBorder": "#FFEE00",
        "editor.selectionBackground": "#393D66",
        "input.foreground": "#fff",
        "editorLineNumber.foreground": "#999",
        "editor."
    },
    "workbench.colorTheme": "Atom One Dark",
    "workbench.iconTheme": "vscode-icons",
    "files.exclude": {
	"**/.git": true,
	"**/.DS_Store": true,
	"**/*.js.map": true,
	"**/*.js": {"when": "$(basename).ts"}
},
"tslint.enable": true,
"tslint.autoFixOnSave": true,
"terminal.integrated.shellArgs.osx": ["-l"]
}`

**Comment by bpasero** [comment] 2017-05-05 16:13
@yangwen2 does it reproduce when all editors are closed?

**Comment by yangwen2** [comment] 2017-05-05 16:18
With all editors closed, terminal, output panels no longer exhibit laggy UI when resizing, even whilst at full screen.

**Comment by bpasero** [comment] 2017-05-05 16:22
@yangwen2 ok good to know. I think what would help is to get a performance profile when you resize. This is possible from within VS Code by using the profiler tools:
To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by yangwen2** [comment] 2017-05-05 16:27
[VSC_Issue25924.txt](https://github.com/Microsoft/vscode/files/979708/VSC_Issue25924.txt)

**Comment by bpasero** [comment] 2017-05-05 16:34
@yangwen2 thanks for the prompt reply!

@alexandrudima not sure if anything pops to your mind that could possibly make resizing slower between 1.11 and 1.12 when editors are open. To me this seems to be a duplicate of https://github.com/Microsoft/vscode/issues/16845 and not a 1.12 regression (e.g. Electron related).

**Closed** 2017-05-24 18:41 UTC
Labels: needs more info, perf, workbench
