### ISSUE TITLE
add React JSX label fold

### ISSUE THREAD

**Issue by hqzh** [Microsoft/vscode#53474] opened 2018-07-03 07:05 UTC
![1](https://user-images.githubusercontent.com/26128706/42203792-7846e228-7ed2-11e8-9cec-bf8a44e49183.png)
![2](https://user-images.githubusercontent.com/26128706/42203798-7adbeca4-7ed2-11e8-9db9-bdaf5a9fceb7.png)
I can't fold tags in React component,not perfect

**Comment by mjbvz** [comment] 2018-07-03 18:32
Duplicate of #51266

See that issue for root cause and workaround

**Closed by mjbvz** 2018-07-03 18:32 UTC
Labels: editor, editor-folding
