### ISSUE TITLE
CLI: After piping input to stdin, on closing the file, the contents of the temp file should be sent to stdout

### ISSUE THREAD

**Issue by st0le** [microsoft/vscode#92105] opened 2020-03-05 18:19 UTC
I want to use code like a editor buffer for the pipeline. For instance, I want to be able to execute `git branch | code - | % { git branch -D $_ }` to delete branches I pick in the editor.

Currently the output when we do a "code -" is a line of this pattern.

Reading from stdin via: `C:\Users\<username>\AppData\Local\Temp\code-stdin-lxk.txt`

Expected:
Contents of the Temporary file.

I feel this is a general expectation from any tool that accepts stdin. Of course, you can find exceptions but vscode doesn't have to be one.

**Comment by bpasero** [comment] 2020-03-10 08:03
@st0le it would be relatively simple to just print the contents of the file we use for stdin reading when it closes by adding something like `console.log(fs.readFileSync(stdinFilePath).toString());` right before:

https://github.com/microsoft/vscode/blob/2697ae50402a713965cf075054cc309378959a0c/src/vs/code/node/cli.ts#L346

However I see 2 issues:
* you only want this printed to `stdout` if another command is waiting for input I guess, because otherwise you would always flood the users console with the contents of that file. so we would need a similar solution as `hasStdinWithoutTty` for `stdout` and possibly also want another CLI argument to force this, similar to the "`-`" we require for reading stdin
* worse than that: it seems to me that invoking Code with another pipe does immediately execute the other program and does not wait. for example doing this: `ps aux | grep code | code - | code-insiders -` starts both Code and Code Insiders for me. the second Code does not wait for the first to close. I can actually reproduce this even with Sublime. This would probably be a major problem to support this feature at all...

**Comment by st0le** [comment] 2020-03-10 19:48
I can confirm your second point, I'm not sure why the second process starts before the first ends. Although the second process is still reading the stdin.

For instance, running `cat - | code -` in cmd.exe starts the editor but shows nothing. In the console If I type text and I Hit Ctrl+D, the text appears in the editor. 

I guess we can suppress displaying the editor until we have read something from stdin. But overall, this doesn't seem like a trivial change as I expected. 

I understand if this gets closed/dropped. There are always alternatives and we don't need to shoehorn this in.

My intention was using `code` similar to tools like `fzf` (https://github.com/junegunn/fzf), heatseeker (https://github.com/rschmitt/heatseeker).

In Powershell, similar to  `Out-GridView -PassThru`

**Comment by bpasero** [comment] 2020-03-11 06:20
Ok thanks for the reply, I think I am going ahead and close this as I see now easy way to get there.

**Closed** 2020-03-11 06:20 UTC
Labels: *out-of-scope, feature-request, workbench-cli

**Comment by alomew** [comment] 2023-10-03 15:40
FYI you can get this functionality using `vipe` a tool in the `moreutils` package available in many unix package managers. 

Example use:
``` shell
export EDITOR='code -nw'
echo "hello world" | vipe | cat -
```
will print out whatever the state of the file is after vs code quits.
