### ISSUE TITLE
Intellisense suggestions are awful. Unintuitive ordering, poor completions, and tons of irrelevant snippets.

### ISSUE THREAD

**Issue by oshalygin** [Microsoft/vscode#61763] opened 2018-10-24 23:08 UTC
This is literally a dupe of https://github.com/Microsoft/vscode/issues/17796 

Not sure why it was closed but it describes the issue very well.

Is there anything the community can do to help with this effort?  I dont mind taking a stab if the contributors feel this is still an issue.

**Comment by weinand** [comment] 2018-10-25 06:47
#17796 was closed as a duplicate of #16109 and #23643.

/duplicate of #17796

**Comment by oshalygin** [comment] 2018-10-25 18:37
@weinand both of those are closed as well?

#16109 and #23643 

16109 - The last reply is in 2016 and has the comment of `Let's give it a try in January`
23643 - The last reply from a contributor is discussing something about scoring

Should I just open up another issue since you closed this one? Can we as a community help contribute to this or does everything related to this just get auto closed without discussion?

**Comment by mjbvz** [comment] 2018-10-26 00:30
Please identify specific cases where intellisense could be improved. `Intellisense suggestions are awful` is not actionable. What is "awful" and how do we measure when are no longer "awful"?

**Comment by jrieken** [comment] 2018-10-28 09:57
> Can we as a community help contribute to this

Yes, you can help by contributing actionable information instead complaining.

**Closed** 2018-11-04 10:12 UTC
Labels: needs more info, suggest

**Comment by cipri-tom** [comment] 2018-11-07 10:54
Here is an example:

<img width="966" alt="screenshot 2018-11-07 at 11 43 21" src="https://user-images.githubusercontent.com/2991890/48126995-99431d00-e27a-11e8-8930-a21b4cec0a2f.png">

(not sure if it's clear, my cursor is just before the closing `)` at the end of the line

It would make sense to have the variables on top, not a snippet. `startswith` should score higher than `fuzzy_match`. And `extensions` (plural) should be before `extension` since I have tab-completed it before, so it is more recent/frequent.
