### ISSUE TITLE
"Select Environment" doesn't work with static `initialConfigurations`

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#68129] opened 2019-02-07 16:49 UTC
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create an extension with this in `package.json`:

    ```json
    "contributes": {
        "debuggers": [
            {
                "type": "foo",
                "initialConfigurations": [
                    {
                        "name": "Foo",
                        "type": "foo",
                        "request": "launch"
                    }
                ]
            }
        ]
    }
    ```

2. Make sure the current workspace doesn't already have a `launch.json`. 
3. Start Debugging to open the "Select Environment" dialog:

    ![](https://i.imgur.com/RjhevnN.png)

4. Select the `foo` debugger.
5. Nothing happens - no `launch.json` is created and there's no error in the dev console.

It seems this may only affect debuggers using the static `initialConfigurations` in `package.json`, as opposed to using the API.

According to @ncannasse this has broken somewhat recently, but was already broken in 1.30.x.

**Comment by isidorn** [comment] 2019-02-20 10:52
This is by design.
We now only show the launch.json if the adapter explicitly returned `null`. Code pointer https://github.com/Microsoft/vscode/blob/e4a80dd449d765b38ff07cb61706119f56e259b6/src/vs/workbench/contrib/debug/electron-browser/debugService.ts#L409

If the user clicks on the configure button it will nicely work.

If you would like the launch.json to be opened also when the user click on the start action you have to implement the confiuration resolver which will return `null`.

Closing.

**Closed by isidorn** 2019-02-20 10:52 UTC
Labels: debug

**Comment by Gama11** [comment] 2019-02-20 11:37
Fair enough, we can implement a configuration resolver if required.

Still, shouldn't there at least be _some_ kind of feedback (_"Debug adapter \<name\> hasn't registered a configuration resolver"_ or similar)? Clicking a button and it silently doing nothing feels a bit broken to me.

It's not like it attemps to start a debug session with the config `initialConfigurations` either, as far as I can tell.
