### ISSUE TITLE
Git branch name mangling in integrated Terminal

### ISSUE THREAD

**Issue by cpheps** [Microsoft/vscode#60310] opened 2018-10-09 12:09 UTC
When running `git branch` inside the integrated terminal the branch name is mangled, where it takes the first letter of the branch name and just repeats it for every letter in the branch.

ex: branch name is `master` vscode is showing `mmmmmm`

Visual output from vscode for `git branch`:

```
   lpu-support
* mmmmm
  master-api-update
  remove-pairing-dependency
```

Visual output from iTerm for `git branch` for the same repo:

```
  lpu-support
* master
  master-api-update
  remove-pairing-dependency
```

What's odd too is if I highlight and copy the incorrect branch name from vscode's terminal then paste it somewhere the pasted branch name is correct and does not match what was copied.

This started after the last update Insider's from October 8th 2018.

- VSCode Version:
```
Version: 1.29.0-insider
Commit: 5bd6ebe2dbc4dee510699020a25f70a69784ce8c
Date: 2018-10-09T09:24:52.091Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- OS Version:
```
macOS High Sierra
10.13.6
```

Steps to Reproduce:

1. Open integrated terminal in VS Code Insiders
2. run `git branch`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2018-10-09 16:32
@cpheps does it fix itself up if you scroll? Could you provide a screenshot?

I suspect it will be fixed by doing cmd++, cmd+- as all the textures get redrawn.

**Comment by Tyriar** [comment] 2018-10-09 16:32
Potentially related to https://github.com/Microsoft/vscode/issues/55981

**Comment by cpheps** [comment] 2018-10-09 16:42
Not sure if it's related to that issue but here's a screen shot. Iterm is on top and vscode is on the bottom.

![screen shot 2018-10-09 at 12 39 57 pm](https://user-images.githubusercontent.com/11877763/46684446-d30ffd80-cbc0-11e8-849a-90b12bed43cb.png)

**Comment by Tyriar** [comment] 2018-10-09 17:51
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1737

**Closed** 2018-10-09 18:52 UTC
Labels: bug, integrated-terminal, upstream

**Comment by Tyriar** [comment] 2018-10-09 18:53
Looks like this was a regression in insiders only

**Comment by cpheps** [comment] 2018-10-10 11:28
Just wanted to follow up this is fixed in:

```
Version: 1.29.0-insider
Commit: cc5e2b41c3add18a31e87f84b5d6162566a38d6e
Date: 2018-10-10T05:10:57.005Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
