### ISSUE TITLE
Add provider API for language-aware "smartSelect" actions

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#14882] opened 2016-11-02 22:17 UTC
VS Code provides a couple of useful commands for expanding (`editor.action.smartSelect.grow`) and shrinking (`editor.action.smartSelect.shrink`) the user's selection based on the tokens of the language being edited.  Currently, this is calculated using the language's syntax grammar definition.

It would be great to have a new provider API to enable a language extension to provide the new selection range!  This would allow language servers to override the default behavior and use their native parsers to intelligently set the selection.

**Comment by usernamehw** [comment] 2019-01-26 14:36
@jrieken Is this a duplicate of #63935 ?

**Closed** 2019-01-28 09:00 UTC
Labels: *duplicate, api, feature-request
