### ISSUE TITLE
Notification Buttons do same function (close) when empty

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#65162] opened 2018-12-16 14:27 UTC
As per the following small video, I have shown that by clicking the notifcation bell, then the arrow, closes it. I haven't been able to test what happens if there are notifications (probably expand, I rarely check there).

As there aren't any notifications, my suggestion is to disable that button, or remove it unless there is one present. Having 2 buttons do essentially the same thing is pointless.

A possible suggestion might be also to make un-focusable. ie: click out of box returns focus to editor or whatever

![notifications](https://user-images.githubusercontent.com/30497573/50054866-c1a61d00-013e-11e9-9fe3-2528a8e1a8f6.gif)

**Comment by beastdestroyer** [comment] 2018-12-16 14:30
#61934 possibly related.

EDIT: Nevermind, I was looking at it wrong

**Comment by bpasero** [comment] 2018-12-17 06:08
@beastdestroyer yeah, let's close as duplicate of that one. My point for not changing the behaviour is that it is very easy to dismiss the notification center with one click, so I would not want to have that button on the far right disabled conditionally.

**Closed by bpasero** 2018-12-17 06:08 UTC
