### ISSUE TITLE
Integration test failure:  webviews should have real view column after they are created, #56097:

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#152173] opened 2022-06-15 10:44 UTC
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174342&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=6deb3bba-8048-5d4c-6830-21c0d15f92a9

**Comment by mjbvz** [comment] 2022-08-03 23:48
Duplicate of #153066

**Closed by mjbvz** 2022-08-03 23:48 UTC
Labels: integration-test-failure
