### ISSUE TITLE
rg.exe processes slow down the cpu significantly at load

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#63161] opened 2018-11-14 18:24 UTC
Issue Type: <b>Bug</b>

When opening a large project (10000+ files), the MS CppTools (and maybe other extensions) spawn several RipGrep instance that parse the whole project, slowing down significantly the computer. 

This seems similar to Microsoft/vscode-cpptools#1118

Shouldn't the rg.exe instances be spawned with a lower priority, as to not hog the machine resources ?

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (16 x 2998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (37.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
workbench|and|0.1.7
emojisense|bie|0.4.1
regex|chr|0.2.0
vscode-svgviewer|css|1.4.7
gitlens|eam|8.5.6
graphviz-preview|EFa|1.3.0
graphscript|Fro|1.0.7
vscode-power-mode|hoo|2.2.0
searchy|mal|0.0.2
python|ms-|2018.10.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.954
preview-vscode|sea|1.4.6
perforce|sle|3.1.0
shader|sle|1.1.4
vscode-3dviewer|sle|0.1.0
vscode-autohotkey|sle|0.2.2
vscode-fbassist|sle|0.2.0
vscode-hexdump|sle|1.7.2
vscode-link|sle|1.0.0
vscode-zipexplorer|sle|0.3.1
dot|Ste|0.0.1
unity-debug|Uni|2.6.6

</details>

**Comment by sean-mcmanus** [comment] 2018-11-15 01:20
Our C/C++ extension doesn't spawn RipGrep or rg.exe.

You can change the parsing of background files to a lower priority by setting C_Cpp.workspaceParsingPriority (affects Microsoft.VSCode.Cpp.Extension.exe ).

**Comment by stef-levesque** [comment] 2018-11-15 01:36
I must have miss that setting. Will try it.

Thanks for the info.

**Comment by gauravsaini** [comment] 2018-12-05 01:44
So the rg.exe instances are not closing if you type in a new keyword. 
Ideally if you type in new text in the search box the old rg.exe should close and new thread should spawn.

**Comment by mjw10086** [comment] 2018-12-28 06:04
i disable all extensions one by one, finally  found the 'Css Peek' make 6 rg.exe. when i disable this,there are no rg.exe.
that's maybe extensions error.


![image](https://user-images.githubusercontent.com/26508537/50504572-70384f00-0aa9-11e9-9eb5-3f5516826851.png)
![image](https://user-images.githubusercontent.com/26508537/50504583-85ad7900-0aa9-11e9-8c3a-23f136256884.png)

**Comment by roblourens** [comment] 2018-12-31 07:15
Extensions can spawn rg processes when vscode starts up, but they are limited to running for 5s. They can also spawn rg processes to search for files, so this is by design. This might have looked worse due to the windows antimalware issue which is fixed by now.

I can't repro the issue @gauravsaini describes - the rg process from a search should be killed when a new search starts. Please open a new issue if it still reproduces in 1.30.

**Closed by roblourens** 2018-12-31 07:15 UTC
