### ISSUE TITLE
Terminal command broken from macOS Monterey 12.3 onwards 

### ISSUE THREAD

**Issue by m-haug** [microsoft/vscode#143524] opened 2022-02-21 08:11 UTC
Issue Type: <b>Bug</b>

When I use `code` in a terminal, I would expect VS Code to open a new window or focus one of my existing windows. Instead, I get the following error output: 

```
/usr/local/bin/code: line 6: python: command not found
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
```

Reading through the release notes for macOS Monterey 12.3 Beta 3, I found the following note:

> Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)

This means that the `python` command is no longer available. Installing Python 3 by default only creates a `python3` command.

Symlinking `python3` to `python` works as a workaround. But perhaps it would be possible to fix the script so that it works with either command or without Python at all?

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 5dea8d4b-108e-4472-bd6e-c5497805e2f7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment] 2022-02-21 08:19
/duplicate of #134635 which is fixed in upcoming 1.65

**Closed** 2022-02-21 08:20 UTC
Labels: *duplicate
