### ISSUE TITLE
scripts\npm.bat install no longer installs extensions's deps

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8796] opened 2016-07-06 10:35 UTC
```
c:\Alex\src\vscode>scripts\npm.bat --version
3.10.4
```

I had to go to npm version `3.10.4` to get the latest `node-gyp` that can compile native modules with the headless C++ compiler

**Comment by alexandrudima** [comment] 2016-07-06 10:37
It is unclear to me if the semantics of the `postinstall` has changed, because if I run `scripts\npm.bat run postinstall` manually this works. I'm thinking that `fsevents` fails to compile and then `npm` no longer runs the `postinstall` script.

**Comment by joaomoreno** [comment] 2016-07-06 11:02
There's a known issue in which `npm >=3.9.0` returns -1 when failing to install optional dependencies: #7874 Might very well be a duplicate...

**Comment by joaomoreno** [comment] 2016-07-06 11:03
Might also be: npm/npm#12698

**Comment by alexandrudima** [comment] 2016-07-06 11:04
Yes, even worse, the rest of the native modules don't get compiled after `fsevents` fails. I had to manually install `oniguruma` and `native-keymap` at the correct versions.

**Comment by joaomoreno** [comment] 2016-07-06 12:43
Yeah afaik npm stops at the first error.

**Comment by chaten** [comment] 2016-07-07 23:01
As a workaround, you can delete the "fsevents" object from npm-shrinkwrap.json before doing npm install. npm will only fail if the optional package has been shrinkwrapped.

**Comment by joaomoreno** [comment] 2016-07-12 07:35
Closing as duplicate of #7874

**Closed by joaomoreno** 2016-07-12 07:35 UTC
Labels: bug
