### ISSUE TITLE
Configuration.update with undefined value throws if key no longer exists in package.json fails

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#42844] opened 2018-02-02 19:35 UTC
### Issue Type
Bug

### Description

While I can understand not wanting to allow the updating settings that aren't registered at all, but removing an old setting should be allowed IMO.

Currently even when setting the value to `undefined` (to remove the old setting) it still throws `Unable to write to User Settings because <setting name> is not a registered configuration`

Is there another way to delete an old configuration setting?

FYI, the scenario here is that in GitLens I have reworked many of the settings and during the migration process, I want to delete the old ones.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (7636a7d6f7d2749833f783e94fd3d48d6a1791cb, 2018-02-02T11:23:29.189Z)
OS version: Windows_NT x64 10.0.17083

Reproduces only with extensions

**Comment by sandy081** [comment] 2018-02-05 10:05
Duplicate of #30165

**Closed** 2018-02-05 10:06 UTC
Labels: *duplicate, config
