### ISSUE TITLE
Output spam when running code from command line

### ISSUE THREAD

**Issue by gstar42** [Microsoft/vscode#9920] opened 2016-07-28 20:13 UTC
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. type name of .yaml file on command line
2. opens but cmd window has this:

D:\temp\CasportMock\Casport\App_Data>
[12328:15996:0728/130946:VERBOSE1:crash_service_main.cc(68)] Session start. cmdl
ine is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --app
lication-name=VSCode --v=1]
[12328:15996:0728/130946:VERBOSE1:crash_service.cc(142)] window handle is 002107
D4
[12328:15996:0728/130946:VERBOSE1:crash_service.cc(290)] pipe name is \.\pipe\V
SCode Crash Service
dumps at c:\Temp\VSCode Crashes
[12328:15996:0728/130946:VERBOSE1:crash_service.cc(294)] checkpoint is c:\Temp\V
SCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[12328:15996:0728/130946:VERBOSE1:crash_service_main.cc(84)] Ready to process cr
ash requests
[12328:4872:0728/130946:VERBOSE1:crash_service.cc(323)] client start. pid = 6984

[12328:4872:0728/130947:VERBOSE1:crash_service.cc(323)] client start. pid = 1474
4
[23748:23240:0728/130947:VERBOSE1:crash_service_main.cc(68)] Session start. cmdl
ine is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --app
lication-name=VSCode --v=1]
[23748:23240:0728/130947:VERBOSE1:crash_service.cc(142)] window handle is 00510F
D6
[23748:23240:0728/130947:VERBOSE1:crash_service.cc(290)] pipe name is \.\pipe\V
SCode Crash Service
dumps at c:\Temp\VSCode Crashes
[23748:23240:0728/130947:VERBOSE1:crash_service.cc(294)] checkpoint is c:\Temp\V
SCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[23748:23240:0728/130947:ERROR:crash_service.cc(301)] could not start dumper

**Comment by kieferrm** [comment] 2016-08-02 01:41
@gstar42 can you please clarify the first step? Does that mean that you start vscode with `code myfile.yaml` ?

**Comment by gstar42** [comment] 2016-08-02 02:25
yes


________________________________

**Comment by kieferrm** [comment] 2016-08-02 21:17
Can't reproduce. @bpasero does the stack trace indicate that the electron crash reporter could not launch correctly?

**Comment by gstar42** [comment] 2016-08-02 21:32
I don't know. This is what I type and I get the messages in that dos window. Meanwhile, the file opens in VSCode.

D:\temp\CasportMock\Casport\App_Data>casport_data.yaml

D:\temp\CasportMock\Casport\App_Data>
[9600:2184:0802/142753:VERBOSE1:crash_service_main.cc(68)] Session start. cmdlin
e is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --appli
cation-name=VSCode --v=1]
[9600:2184:0802/142753:VERBOSE1:crash_service.cc(142)] window handle is 000C11E8

[9600:2184:0802/142753:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSC
ode Crash Service
dumps at c:\Temp\VSCode Crashes
[9600:2184:0802/142753:VERBOSE1:crash_service.cc(294)] checkpoint is c:\Temp\VSC
ode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[9600:2184:0802/142753:VERBOSE1:crash_service_main.cc(84)] Ready to process cras
h requests
[9600:16172:0802/142753:VERBOSE1:crash_service.cc(323)] client start. pid = 1536
8
[9600:16172:0802/142754:VERBOSE1:crash_service.cc(323)] client start. pid = 1629
2
[1028:12028:0802/142754:VERBOSE1:crash_service_main.cc(68)] Session start. cmdli
ne is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --appl
ication-name=VSCode --v=1]
[1028:12028:0802/142754:VERBOSE1:crash_service.cc(142)] window handle is 0002121
6
[1028:12028:0802/142754:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VS
Code Crash Service
dumps at c:\Temp\VSCode Crashes
[1028:12028:0802/142754:VERBOSE1:crash_service.cc(294)] checkpoint is c:\Temp\VS
Code Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[1028:12028:0802/142754:ERROR:crash_service.cc(301)] could not start dumper




________________________________

**Comment by bpasero** [comment] 2016-08-06 10:08
The issue is that there is output showing up in the console even though our code script should prevent that. Moving to @joaomoreno

**Comment by joaomoreno** [comment] 2016-08-08 09:39
@gstar42 Can you show me your `%PATH%` variable?

**Comment by gstar42** [comment] 2016-08-08 16:04
C:\>path
PATH=D:\app\gstar\product\11.2.0\client_1;D:\app\gstar\product\11.2.0\client_1\b
in;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\
;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\
Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
;d:\bin;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools
\;%BPADir%;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Mi
crosoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\11
0\Tools\Binn\;D:\cpe\database\bin;D:\cpe\DLLs;D:\Program Files\Microsoft Network
 Monitor 3\;D:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\W
indows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Windows Resource
Kits\Tools\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\
;D:\Telos\DM;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit
\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Fi
les\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel
\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
 Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SDKs\TypeScri
pt\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (
x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\
110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\Managem
entStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program
Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Micros
oft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Common Files\Acronis\SnapA
PI\;c:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Git\cmd;
D:\Telos\Amhs\Bin\;;D:\bin\Sysinternals;C:\Users\GStar.AMHSCENTRAL\AppData\Local
\Code\bin;D:\Program Files\7-Zip;d:\Program Files (x86)\Microsoft VS Code\bin;c:
\PROGRA~2\MI1FF4~1;;C:\Program Files (x86)\Common Files\Acronis\TibMounter64

C:\>



________________________________

**Comment by joaomoreno** [comment] 2016-08-09 07:38
Which command line are you using? Command Prompt, PowerShell? Can you try the latest version, 1.4.0?

**Comment by gstar42** [comment] 2016-08-09 13:05
Win 7 command prompt.

I'm off the rest of the week so ask me again on Monday...


________________________________

**Comment by joaomoreno** [comment] 2016-09-28 08:29
@gstar42 ping

**Comment by gstar42** [comment] 2016-09-28 13:28
BTW, it still happens. Used it yesterday from WIn7 command line



________________________________

**Comment by joaomoreno** [comment] 2016-09-28 14:29
Which version? Can you try the latest?

**Comment by gstar42** [comment] 2016-09-28 14:59
I updated a few days ago



Sent from my tablet


-------- Original message --------

**Comment by joaomoreno** [comment] 2016-09-28 15:03
Please give me a version number.

**Comment by gstar42** [comment] 2016-09-29 21:02
[cid:977cfe3d-0aaf-497d-a370-aa0232384fd0]


________________________________

**Comment by joaomoreno** [comment] 2016-09-30 07:30
Let's try again: what is your current VS Code version?

**Comment by gstar42** [comment] 2016-09-30 12:54
Didn't you get my last email? 1.5.3


________________________________

**Comment by joaomoreno** [comment] 2017-04-26 07:48
This seems fixed.

**Closed by joaomoreno** 2017-04-26 07:48 UTC
Labels: bug
