### ISSUE TITLE
remote debugging - remote server is different OS from local server

### ISSUE THREAD

**Issue by Loreton** [Microsoft/vscode#44932] opened 2018-03-02 15:47 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 7

Steps to Reproduce:

1. prepare code on linux using netiface module
2.run debug from windows to remote linux
When the local module (windows), in my case "netifaces", has different characteristics from remote module (linux) we get error reading the network interface caracteristics. Why?  It should run remote code and not local code.
Regards

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment] 2018-03-02 15:56
Sounds like a potential duplicate of the wsl issues, forwarding to @weinand

**Comment by weinand** [comment] 2018-03-02 15:58
@Loreton How does your launch config look like?

**Comment by Loreton** [comment] 2018-03-05 11:04
# my __main__.py code

```python
# ####################################
# #### R E M O T E  - Linux OS #############
# ####################################

# ******** D E B U G *********************************
import ptvsd
ptvsd.enable_attach("my_secret", address=('localhost', 3000))
ptvsd.wait_for_attach() # only in the remote node
# ******** D E B U G *********************************


import sys; sys.dont_write_bytecode = True
import  Source as Prj

myLibName = ['LnPyLib', 'DDNS_v2018-02-27.zip'] 
LnLib     = Prj.SPE.LibPath(myLibName, fDEBUG=False)



# ####################################
# #### L O C A L    Windows OS ############
# ####################################

# ******** D E B U G *********************************
import ptvsd
ptvsd.enable_attach("my_secret", address=('localhost', 3000))
# ptvsd.wait_for_attach() # only in the remote node
# ******** D E B U G *********************************


import sys; sys.dont_write_bytecode = True
import  Source as Prj

myLibName = ['LnPyLib', 'DDNS_v2018-02-27.zip']   **_<=== BreakPoint_**
LnLib     = Prj.SPE.LibPath(myLibName, fDEBUG=False)
```

# Problem
When I start the debugger I can STEP just the first two line and the I get an error regarding a missing feature of netifaces module (AF_PACKET). 

  File "y:\GIT-REPO\Python3\DDNS\__main__.py", line 79, in <module>
    Prj.Main(gv.args.firstPosParameter)
  File "y:\GIT-REPO\Python3\DDNS\Source\Main\DDNS_Main.py", line 83, in Main
    interfaces     = Ln.getInterfaces(dictType=Ln.Dict)
  File "y:\GIT-REPO\Python3\DDNS\LnPyLib\Net\InterfacesCl.py", line 418, in getInterfaces
    ifc = Interfaces(ifcName)
  File "y:\GIT-REPO\Python3\DDNS\LnPyLib\Net\InterfacesCl.py", line 116, in __init__
    self.arpPing(self._gatewayIpAddress)
  File "y:\GIT-REPO\Python3\DDNS\LnPyLib\Net\InterfacesCl.py", line 319, in arpPing
    macAddressHex   =  bytes.fromhex(self._MAC_address.replace(':',''))
AttributeError: 'NoneType' object has no attribute 'replace'

But this feature is missed just in windows module and not in linux one.
In any case:
1. it doesn't stop in the breakpoint line.
2. the TCP connection to remote machine NOT starts







# launch extract configuration
```python
   "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                // "WaitOnAbnormalExit",
                // "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "args": [
                "update",
                "--profile",
                "LnPi23"
            ]
        },
    ....
    i have the following tunnel ssh -L 3001:destMaschine:3000 
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/pi/GIT-REPO/Python3/DDNS",
            "port": 3001,    
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
```

Kind Regards

**Comment by weinand** [comment] 2018-03-05 11:44
This issue was moved to Microsoft/vscode-python#948

**Closed by weinand** 2018-03-05 11:44 UTC
Labels: debug, needs more info
