### ISSUE TITLE
C++ syntax highlighting bug on strings containing semicolon

### ISSUE THREAD

**Issue by keldon85-avasopht** [Microsoft/vscode#5130] opened 2016-04-10 13:55 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 7 Professional (x64)

Steps to Reproduce:

1. Create new file with C++ language
2. Add the following code:

        void fn() {
          f(";", value); // Line must begin with at least 1 space.
        }

Syntax highlighting for string begins from the second double-comma
![visual-studio-code_0 10 11_cpp-syntax-highlighting-bug](https://cloud.githubusercontent.com/assets/1532557/14410590/fff3137e-ff2a-11e5-9c9c-0e560dd3f8b1.png)

This was discovered when trying to view the muse-sequencer's [main.cpp](https://github.com/muse-sequencer/muse/blob/fbd4c3f10fa780f689c4681e4ef96ddffc216629/muse3/muse/main.cpp) (line 137).

This is an odd bug for sure because it's so easy to trigger!

**Comment by matheusmonte** [comment] 2016-04-11 04:52
the current production version happens, but not happens development version. I think in the next build everything will be ok, I execute the development version and this is the
![testecpp](https://cloud.githubusercontent.com/assets/5808206/14417140/ac23c414-ff7f-11e5-93b8-a39a6787f6df.PNG)
 results:

**Comment by aeschli** [comment] 2016-04-11 16:31
duplicate of #4769

**Closed by aeschli** 2016-04-11 16:31 UTC
