### ISSUE TITLE
New terminal in editor area will not open in an empty pane

### ISSUE THREAD

**Issue by AllanJard** [microsoft/vscode#146420] opened 2022-03-31 11:04 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: OpenSUSE Tumbleweed - up to date as of 31st March 2022

Steps to Reproduce:

1. Assign a command to create a new terminal in the editor area (`workbench.action.createTerminalEditor`) - I have mine set to be alt + enter.
2. Setup the editor to have at least one empty workspace, no files open and one with a file open.
3. Click the workspace without any files open (showing just the VSCode logo)
4. Press the key combination to create a new editor terminal set in (1)
5. Note that the terminal is in fact opened in the area with the file open rather than the one that was clicked on.

Given that it is the area with the VSCode logo that has focus, I would have expected the terminal to open there.

**Comment by Tyriar** [comment] 2022-03-31 14:35
Can reproduce both with terminal editor keybinding and ctrl+n as well:
![Recording 2022-03-31 at 07 35 25](https://user-images.githubusercontent.com/2193314/161080869-ab34fd85-19e9-43db-b5f3-6664b523d583.gif)

Since it affects new file as well I think this is not a terminal problem as well.

**Comment by bpasero** [comment] 2022-03-31 14:49
@Tyriar at least the first thing you show where a terminal opens in the wrong group seems a terminal issue to me, are you sure you are not passing in a group id when this command runs?

The second issue can be explained: the side group is locked (you can tell by the lock icon), so "New file" will not target the locked group.

**Comment by bpasero** [comment] 2022-03-31 14:49
Oh, you started with a locked group, so it has nothing to do with "New File"...

**Comment by Tyriar** [comment] 2022-03-31 14:50
Oh right, forgot about locked groups 🤦

**Comment by Tyriar** [comment] 2022-03-31 14:52
@bpasero this may be by design actually, there are 2 things going on here which I'm not 100% on what the designed behavior is:

- Closing the last editor in the group does not unlock the group, causing the "problem"
- Opening a terminal editor when the locked group is focused does not open it in the locked group

**Comment by AllanJard** [comment] 2022-03-31 14:55
Sorry for the dribble of information - I'm finding out loads from your comments. There is a _Workbench > Editor: Auto Lock Groups_ option which has the `terminalEditor` enabled by default - not the others. That explains the second last point form @Tyriar - unchecking it allows it to work as expected.

**Comment by bpasero** [comment] 2022-03-31 15:07
@Tyriar the command can control this, if you actually pass the group id of the active group from the command you can "force" it to open even in a locked group. Maybe terminals should do that because this feature was mainly build for terminals.

As for the behaviour of preserving the lock when you close the editor, I recall we had a design discussion around this and decided it was good behaviour as long as the group is a side group and not the primary group that cannot be locked anyway.

**Comment by meganrogge** [comment] 2022-05-06 21:06
Was there a change made to address this? I cannot reproduce the issue - for either a keybinding associated with creating a terminal editor or the new file
https://user-images.githubusercontent.com/29464607/167216534-83800621-2668-48ea-b940-ffd2878ab386.mov

**Comment by AllanJard** [comment] 2022-05-06 21:24
As far as I'm aware, there was no change. My viewport had been locked, which I didn't even know was a thing, which caused the issue. Can probably be closed off.

**Comment by meganrogge** [comment] 2022-05-06 21:34
Great, so you can no longer repro the issue either then @AllanJard ?

**Closed** 2022-05-06 21:46 UTC
Labels: bug, workbench-editors

**Comment by AllanJard** [comment] 2022-05-07 06:18
I can - but only by locking the viewport. It was effectively a misunderstanding of a feature on my part.

**Comment by aeschli** [comment] 2022-05-31 13:48
Can I verify anything here? Or should the milestone be removed?
