### ISSUE TITLE
Navigate through explorer by typing start of file/folder name

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#10026] opened 2016-08-01 17:00 UTC
- VSCode Version: Any
- OS Version: Any

**Feature Proposal**
When opening a folder containing hundreds of items (for example: `node_modules`) There is no easy way to get to a child folder/file without scrolling around.

Would it be possible to allow the file viewer to navigate down to let's say the first file of the next letter keypressed?

```
node_modules (folder is highlighted)
    ( letter L is hit )
    ---- automatically scrolls down within node_modules to folders beginning with "L"
       +++ Folders shown:
       +  Lodash / etc
```

Just an idea, would help navigating large filesystems a bit easier.

**Comment by Tyriar** [comment] 2016-08-01 17:19
I'd also love to have this, anything that makes it easier to navigate the explorer using only the keyboard would be awesome. This is how Ubuntu handles it in its "Files" program:

Type 's' and you get a filter box that pops up at the bottom of the file explorer:

![image](https://cloud.githubusercontent.com/assets/2193314/17302396/e3d7d8ec-57d0-11e6-8e47-e4cc4aab3323.png)

At this point down and up only allow navigation between files starting with an 's'. Pressing escape will clear the filter and allow free navigation again.

I believe Windows on the other hand maintains a search string and keeps a timeout for when the search expires. As such, typing "sr" in quick succession will focus the `src` directory, pressing "c" before the timeout expires will keep focus on `src`, if it's after the timeout expires then `CONTRIBUTING.md` will be focused. up/down are not restricted on Windows.

**Comment by MarkPieszak** [comment] 2016-08-01 17:28
Oh well that'd be an even better implementation! If it narrowed down and only showed folders/files with the letter(s) you typed that'd be incredible. :+1:

**Comment by bpasero** [comment] 2016-08-06 09:38
Related: https://github.com/Microsoft/vscode/issues/9373

**Comment by Tyriar** [comment] 2016-08-08 18:07
Haha, of course I already reported this in #4763 :stuck_out_tongue:

**Comment by dougrosenfeld** [comment] 2016-08-25 15:38
This is a great request. We too are working with thousands of files in hundreds of folders on multiple network shares. Finding and navigating with a mouse and scrolling through a large folder structure to find the file and manually selecting the file is burdensome - especially when the Explorer jumps around when clicking on a file in the Open Editors pane.

We kindly request that finding files in the Explorer be easier. The standard Windows Explorer is a good example.

For example, provide a box where you can start typing in the file name and the folders/files displayed in the Explorer are limited to names that match - even if the folders are "closed". Please support wild cards. This search needs to be very fast. 

Another example, a simple goto file would be helpful. 

Another example, allow typing in the Explorer to jump to a file. But don't limit it to the current folder.

**Comment by ConstantineK** [comment] 2016-12-06 15:25
Agreed with @dougrosenfeld, as soon as I opened my first folder in the Explorer menu I intuitively looked for the bar that I could click to filter the items within the window, mainly because it is available in many code editors. 

I have had multiple people ask me this same question when I introduced Code to them, and when working with larger directories with many files this would simplify the mental overhead of dealing with all of the folders.

**Comment by Tyriar** [comment] 2016-12-06 21:55
It would make sense to tackle this when we look at adding multi-select in https://github.com/Microsoft/vscode/issues/1023

**Comment by bpasero** [comment] 2017-01-16 17:20
Updated this summary: this feature asks for filtering the explorer while typing whereas https://github.com/Microsoft/vscode/issues/10839 would cover the request of selecting the next element in the tree that matches a specific key that was pressed.

**Comment by thekalinga** [comment] 2017-02-03 12:59
@bpasero Is there a plan on which release this will be included in (feb/march/e.t.c)?

**Comment by bpasero** [comment] 2017-02-03 14:22
**Backlog** means it is not planned for an iteration.

**Comment by thekalinga** [comment] 2017-02-03 16:32
Wanted to check if the item is in the potential items that you might consider in this/next release?

**Comment by bpasero** [comment] 2017-02-03 17:01
I think it is.

**Comment by gulshan** [comment] 2017-02-05 05:27
Isn't `ctrl+p` and `ctrl+e` kind of doing this already?

**Comment by Tyriar** [comment] 2017-02-05 06:30
@gulshan my main need:

1. Open `./node_modules/`, which is excluded by default
2. Click on the explorer and start typing the name

Right now you need to scroll down and find it, which can be a pain with hundreds of modules.

**Comment by Tyriar** [comment] 2017-02-13 02:01
@bpasero FYI I rolled https://github.com/Microsoft/vscode/issues/10839 into this one as it's confusing to switch the issue purpose (especially when people have voted for it). AFAIK no one has asked for actual filtering of the tree, both issues ask for the same thing; typing to go to the 'next match' in the explorer.

**Comment by metasong** [comment] 2017-07-19 09:13
what's the current status of this feature request, we need it!!!!
what's the current status of this feature request, we need it!!!!
what's the current status of this feature request, we need it!!!!

**Comment by msafi** [comment] 2017-08-25 19:53
Alternatively, provide Explorer API for extension authors to achieve the same thing

**Comment by mostr** [comment] 2017-09-05 09:13
Are there any time plans for this one, or is there any extension for that? I'm missing it a lot :(

**Comment by quasarea** [comment] 2017-09-12 14:05
I manage to replace this functionality by using ctrl +p and typing name. It's not the same but in some ways more convinient even as you don't have to start from beginning of filename and you don't need mouse to switch.

**Comment by mmayors** [comment] 2017-09-16 02:19
I'm so glad I found this feature request.  For someone who works exclusively on Mac which gives you this for free in the Finder this would be a huge improvement.

**Comment by azaparov** [comment] 2017-10-24 14:31
Please implement

**Comment by Skura23** [comment] 2017-11-27 06:47
It's still not a feature now, sad.

**Comment by rossjs** [comment] 2017-11-28 19:34
Would love for this to also be included into the **workbench.action.quickOpen** command (⌘ + P / Ctrl + P) as well!

**Comment by sandos** [comment] 2017-12-12 06:33
I would love the feature as in Visual Studio, where a keypress both focuses on the "solution explorer" and then filters if you type more. I believe the "focusing" bits are already in code. There is some overlap in functionality with ctrl+P. Still a useful feature.

**Comment by ivanvoznyakovsky** [comment] 2017-12-14 09:37
that would be awesome to have this feature implemented. no idea why this is still On Deck, hence under consideration. 
found a quick hack for it https://github.com/karabaja4/vscode-explorer-search

**Comment by lousyd** [comment] 2017-12-15 15:30
"Me too". I would like to be able to search the vertical list of filenames by just pushing a key when the pane is in focus. But instead of just the first letter, it'd be nicer if it visually filtered the list in realtime, and searched for the string I typed anywhere in the filename. So if my list includes "Get-MyFunction", "Set-MyFunction", and "Do-TheFunThing", typing "Func" would filter out the last one and show just the first two. (I forget sometimes what verb I used for my personal scripts collection.) The command palette sort of works this way. Having it in the Explorer pane, and limited to the string typed, would be really useful.

**Comment by vsizov** [comment] 2018-01-10 14:23
This is the only feature I miss to call VScode the greatest editor of all time :)

**Comment by wongjiahau** [comment] 2018-01-20 04:47
Me too!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hiredgun** [comment] 2018-01-30 18:44
omg, why is it still not implemented :(

**Comment by hoegge** [comment] 2018-02-05 16:00
Yes it is really painful to navigate a medium sized `node_modules` folder without a way to search by entering text, It should just work like this:
1. Press CTRL+SHIFT+E to set focus to the explorer
2. Start typing and it searches - jumping to the next folder that match the typed letters - just like searching a folder in Outlook

**Comment by jasonslyvia** [comment] 2018-02-06 01:39
one whole year passed since last member responded 🤔 just curious what's the current status and what can we do to help out

**Comment by hiredgun** [comment] 2018-02-06 10:32
@hoegge I have exactly the same use case, it's really annoying. I really like VS Code despite so many missing features and probably I'm the only person using it in my company :D Sometimes I try to convince my colleagues to try it but when I realize that you can't even select multiple files and move it to another directory or delete them then I just give up and start to think that maybe it's time to move to another IDE :(

**Comment by ivanvoznyakovsky** [comment] 2018-02-06 10:52
@hiredgun I think multi select is already in insider and is coming in w/ next release (see #1023). what is more annoying is that usages are not updated when you move files around. you have to go and search for usages of every single file moved and fix path.

**Comment by wongjiahau** [comment] 2018-02-10 04:43
@hiredgun The select multiple file feature is already rolled out. https://code.visualstudio.com/updates/v1_20?source=techstories.org#_multi-select-in-the-explorer

**Comment by rakeshpmali** [comment] 2018-03-01 09:06
If you have used Source Insight, it has a search bar just above file explorer window where we can type filename and it instantly shows the file below. I would request something like this in the explorer pane.

Thanks for this wonderful IDE ! Cheers ! and Keep up the Good Work !

**Comment by gulshan** [comment] 2018-03-01 09:54
Does this issue relate to accessibility in some way?

**Comment by sgon00** [comment] 2018-03-27 08:25
+1

**Comment by sgon00** [comment] 2018-03-28 11:01
I just figured out `Ctrl-p` is not only a list of recently opened files, but also I can search through all files in the project even if it's not in the list. Just for reference. I am not sure if I am the only one who don't know this.

**Comment by elektronik2k5** [comment] 2018-03-28 12:59
@sgon00, that excludes files, which are ignored by version control.
The original issue explicitly states the need to search through `node_modules`, which is typically ignored by version control. What you're describing doesn't work for such files/directories.

**Comment by Legends** [comment] 2018-04-03 04:33
When?

**Comment by Legends** [comment] 2018-04-04 07:03
What about? 

![image](https://user-images.githubusercontent.com/966368/38293241-0d77a608-37e7-11e8-970c-b76cc7b83aca.png)

**Comment by lopugit** [comment] 2018-04-07 15:09
when's this gonna be implemented? 

Could you give some direction to what code needs to be added where to get this working? 

I will have a look, it's crucial

**Comment by Corps-Yan** [comment] 2018-04-13 07:36
Still not implemented!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ambichetan** [comment] 2018-05-16 23:42
Eagerly waiting for this feature!!!

**Comment by tarzier** [comment] 2018-05-21 02:54
If you are used to maintaining a large codebase, this could easily be at the top of your must-have feature list. One use case for me is to be able to scan or delete dozens of "*-tmp" suffixed filenames (for example) without having to wade through dozens of folders.

**Comment by levani** [comment] 2018-05-23 12:02
Webstorm handles this really well...

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/184472/40423168-b044e9d6-5ea2-11e8-8b8a-67dac4a5aa56.gif)

**Comment by prashantpalikhe** [comment] 2018-05-31 21:15
Also in desperate need of this feature.

**Comment by zersiax** [comment] 2018-06-01 19:17
Bump. Not having this is seriously killing my productivity. I can't scroll with a mouse as I'm a screen reader user, I have to go file by file by file by file by file by ...you get the idea. Imagine finding a file in the resources/views/auth/login/ folder all the way from the top of the file tree just by pressing arrow down and arrow right, feel my pain.

**Comment by crazyxhz** [comment] 2018-06-04 13:39
this is the only missing feature that kept me from switching to vscode from webstorm

**Comment by hiredgun** [comment] 2018-06-04 13:45
If you want temporary solution then check [this extension](https://marketplace.visualstudio.com/items?itemName=jasonnutter.search-node-modules)

**Comment by AdamModus** [comment] 2018-06-07 14:02
bumping for notoriety cuz i'd reeeeeeaaaaally love this feature in vscode!

**Comment by EmTee70** [comment] 2018-06-14 16:14
Maybe I should repost two known solutions for files not excluded by .gitignore
a: **ctrl-p**  was new for me thanks to [sgon](https://github.com/sgon00) in this thread.
At first I only found the hint to ctrl-, which was wrong...
b: Use **ctrl-shift-f** to search for content and open the files to include dialog (the tree dots below) with file globbing and place a pattern in files to include you should know only one common char than you may find all related files. Sure this dos not help if you want to view files excluded via .gitignore.

**Comment by vedmant** [comment] 2018-06-21 19:57
I mostly use PHPStorm and so much used to this function, it's pity there is no such a simple but helpful thing in VSCode.

**Comment by 5argon** [comment] 2018-06-27 14:10
VSCode is so smart at everything and I don't expect this function to be missing at all !!

**Comment by empurium** [comment] 2018-07-10 16:24
Coming from Webstorm and absolutely loving so many things about VS Code, but I can already feel how painful this is going to be.. The Explorer desperately needs this functionality. Nobody wants to use the mouse to navigate a large project, and while the Command Palette is great, it certainly doesn't replace the ability to simply browse the filesystem while hunting for a file. :(

**Comment by gulshan** [comment] 2018-07-10 19:04
Can this be marked as an accessibility issue as per the comment https://github.com/Microsoft/vscode/issues/10026#issuecomment-393983106? @isidorn

**Comment by killjin** [comment] 2018-07-13 21:16
还没有解决

**Comment by garkin** [comment] 2018-07-15 06:18
With out it is specially painfull to navigate inside a blown up `node_modules`.

**Comment by kamechb** [comment] 2018-07-19 03:56
still waiting...

**Comment by vedmant** [comment] 2018-07-19 07:34
Maybe it makes sense just to create a plugin? I can work on that when have more time.

**Comment by irek02** [comment] 2018-07-19 15:47
@vedmant you would pretty much need to create a replacement of the explorer in that case.

**Comment by vedmant** [comment] 2018-07-19 15:49
@irek02 So there is no way to extend explorer functionality?

**Comment by irek02** [comment] 2018-07-19 15:54
@vedmant, I assumed that there is no API for this kind of enhancement but you should definitely give it a try!

**Comment by korneevaed** [comment] 2018-08-07 07:58
+1

**Comment by LiPengfei19820619** [comment] 2018-08-13 11:02
+1

**Comment by baartho** [comment] 2018-08-14 01:42
+1

**Comment by alexreg** [comment] 2018-08-14 20:02
Still not implemented? Gosh, this has been open a long time.

**Comment by LiPengfei19820619** [comment] 2018-08-20 08:34
Expecting this feature.

**Comment by zhengminhui** [comment] 2018-08-28 04:11
Please add this feature...

**Comment by MrChriZ** [comment] 2018-08-28 11:44
+1

**Comment by b00tsy** [comment] 2018-08-28 12:08
+1

**Comment by ex7r3me** [comment] 2018-08-31 10:39
+1

**Comment by demisx** [comment] 2018-09-02 16:15
Please make this happen. Just an input text above project files where we can enter partial name and have the project tree auto filtered out would be a great plus for VSCode.

**Comment by lavgl** [comment] 2018-09-04 02:10
+1

**Comment by gaurav-abbhi** [comment] 2018-09-05 15:37
Please add this feature....................

**Comment by newcrazy99** [comment] 2018-09-06 18:17
+1

**Comment by lumodon** [comment] 2018-09-06 19:48
+1

**Comment by robertmirro** [comment] 2018-09-09 15:56
+1

**Comment by lovegehlin** [comment] 2018-09-10 10:38
+1

**Comment by dev1null** [comment] 2018-09-10 12:15
For the love of God please stop +1ing! Github has added reactions just for this! Your eagerness doesn't help anyone but just annoys everyone subscribed to this issue who're waiting to hear some actual progress. If you want to subscribe yourself there's a button up there. And please don't bother getting offended and replying with more useless noise.

**Comment by lopugit** [comment] 2018-09-10 12:16
You though

**Comment by flkc** [comment] 2018-09-14 11:31
+1

**Comment by vkovic** [comment] 2018-09-14 11:32
+1

**Comment by dontsave** [comment] 2018-09-17 18:54
+1

**Comment by llezenelrahc** [comment] 2018-09-19 02:18
+1

**Comment by rain84** [comment] 2018-09-24 00:02
+1

**Comment by pedall** [comment] 2018-09-24 09:02
+1

**Comment by g-patel** [comment] 2018-09-24 20:05
any update on this? This has been sitting for two years 😞

**Comment by Yanpas** [comment] 2018-09-25 15:08
Currently `workbench.action.quickOpen` hasfollowing cons:
* it doesn't respect selected text, text could be the path or pattern
* there is no way to explore folder like in shell (no autocompletion)

I like the way folder navigation is implemented in Dolphin:
![peek 2018-09-25 18-04](https://user-images.githubusercontent.com/7345761/46023744-f8dfd180-c0ed-11e8-8132-73cc827d43bd.gif)

Same interface, but with files support would be appreciated!

**Comment by nc-jfkh** [comment] 2018-10-02 07:20
Any update here?

**Comment by AistrCyrill** [comment] 2018-10-05 16:16
It will be realy helpful

**Comment by omerosaienni** [comment] 2018-10-10 08:40
Agreed, WebStorm can do it and I am evaluating VS Code, which cannot do this.

**Comment by tanftw** [comment] 2018-10-13 01:34
I use Ctrl + Shift + E to jump to Explorer and use arrow keys to navigate between files and folders, it's great to have a shortcut key to move to parent folder (like Ctrl + ←), and the next sibling folder (like Ctrl + →). Do I have to create a new issue for this?

**Comment by metasong** [comment] 2018-10-17 03:33
request this feature!!!!

**Comment by metasong** [comment] 2018-10-17 03:35
+1

**Comment by rozzzly** [comment] 2018-10-17 22:07
Conspiracy Theory: Microsoft bought GitHub to add this feature just so the vscode team could ignore #10026 & #10121

![useless comments](https://pbs.twimg.com/media/DpvgLFLU0AAdD1G.jpg:large)

**Comment by vedmant** [comment] 2018-11-06 07:17
Still no any progress here? This is basically the main reason why I prefer using PHPStorm over VSCode.

**Comment by andyl** [comment] 2018-11-11 04:07
intellij has a really elegant solution - if your "Ctrl-P" search string ends in a '/' character, you search on directory names.

**Comment by vedmant** [comment] 2018-11-11 09:18
> intellij has a really elegant solution - if your "Ctrl-P" search string ends in a '/' character, you search on directory names.

No, that doesn't work, for example I wanted to find all boots* folders in node_moudles, https://screencast.com/t/2OowBWSovCoa

**Comment by MartinNuc** [comment] 2018-11-11 10:17
Guys please stick to the topic. This issue is not about searching for a directory. It's about navigating through explorer by typing the name of folder.

**Comment by wongjiahau** [comment] 2018-11-13 05:41
It's been 2 years . . .

**Comment by HeathLee** [comment] 2018-11-13 05:54
any progress???

**Comment by Panajev** [comment] 2018-11-26 11:07
Being able to only show a subset of files in the file explorer would be massively useful!

**Comment by andyl** [comment] 2018-11-26 13:56
Is there a way to do this with a code extension?  Is it possible to build a custom 'ctrl-p' plugin?

**Comment by potatoqualitee** [comment] 2018-11-26 18:05
So trying that myself @andyl - I'd like to switch from PowerShell Studio to VS COde and this is the one last thing. Here's how PSS does it.

![filter](https://user-images.githubusercontent.com/8278033/49032942-30caca00-f1ae-11e8-833a-3bb3a30846ec.gif)

**Comment by andyl** [comment] 2018-11-26 22:59
@potatoqualitee - it's can't be that hard right?  Just a simple regex match.  

Does anyone know: is there a VsCode call that brings up the file explorer with a specific folder highlighted?

**Comment by andyl** [comment] 2018-11-27 20:33
Here's a quick and dirty way to search for directories in `vim` using `fzf` and `NERDTree`:

    :call fzf#run({'source': 'fd -t d', 'sink': 'NERDTreeFind'})

- `fd -t d` is a command that returns a list of all child directories
- `fzf` is a fuzzy-finder that works on the command line and in vim
- `NERDTreeFind` is a command that opens `vim/NERDTree` on a specific file or directory

Is it possible to do something like this in VsCode?  I haven't been able to find a VSC command that opens a folder in the explorer as is done by `NERDTreeFind`.

**Comment by rozzzly** [comment] 2018-12-03 07:10
f@%k guys people are suggesting vim plugins because no action's being taken

**Comment by andyl** [comment] 2018-12-05 16:40
I took a crack at a VsCode Plugin to search for a directory.  Here's a gist with the code:

https://gist.github.com/19885ea9ba13b77a160aa075ff9443a9

With the extension you can bring up a fuzzy search for a directory name
![image](https://user-images.githubusercontent.com/90030/49528097-2375a580-f868-11e8-9c6b-1a504d469a96.png)

You can drill-down into sub-directories
![image](https://user-images.githubusercontent.com/90030/49527320-823a1f80-f866-11e8-9d3c-851f46be311b.png)

When you find a directory, the plugin changes the root directory of the explorer using `vscode.OpenFolder`.  
![image](https://user-images.githubusercontent.com/90030/49527381-a39b0b80-f866-11e8-823f-7b00d4684bcb.png)

I really want to open the current explorer on the given folder, without changing the explorer root.  There doesn't seem to be a VsCode api that does this.  :-1: 

The vim one-liner works fantastic BTW.

**Comment by bjankord** [comment] 2018-12-10 20:18
Would be great to have this feature in VSCode. I mainly need it for quickly navigating in node_modules when I don't feel like navigating in the terminal.

**Comment by LarsDenBakker** [comment] 2018-12-13 08:13
+1

**Comment by MichaelHindley** [comment] 2018-12-13 21:06
@isidorn I see you're on top of things doing a great job in the vscode repo, since you seem to be assigned to this issue as well and the last update was in may, in the grand scheme of things, is it feasible that it will be up for review within the next couple of minor versions?

**Comment by andyl** [comment] 2018-12-14 01:40
@isidorn would you respond to financial inducement?  I see that you have some free time on your weekends.  I will organize a fundraising effort if you will block out a Saturday afternoon to fix this for us.  Name your asking price, and I will try to raise the funds.  :money_with_wings:

**Comment by isidorn** [comment] 2018-12-14 09:08
I am already working on this https://github.com/Microsoft/vscode/pull/65008
Assigning this to december milestone, so if everything goes as planned should be available in the next 2 months, or as soon as we merge that PR in insiders.

No financial inducment needed, I enjoy my Saturdays more than money.

**Comment by RMPR** [comment] 2018-12-16 18:32
Thanks😁😁

Le ven. 14 déc. 2018 à 10:09, Isidor Nikolic <notifications@github.com> a
écrit :

**Comment by wAISw** [comment] 2018-12-17 07:34
maybe exist any plugin for it?

**Comment by BalintFarkas** [comment] 2019-01-05 11:10
Cool, looking forward to this!

**Closed** 2019-01-14 15:09 UTC
Labels: accessibility, feature-request, file-explorer

**Comment by isidorn** [comment] 2019-01-14 16:42
Navigating through file explorer by typing file/folder names will be available in tomorrow's vscode insiders.
The filtering as described in this comment https://github.com/Microsoft/vscode/issues/10026#issuecomment-236646211 we will treat as a seperate feature request and that will proabably come in the next milestone (February).
Here's a pointer to that one https://github.com/Microsoft/vscode/issues/66497

**Comment by rozzzly** [comment] 2019-01-17 17:26
hallelujah <3 my faith has been restored!

**Comment by letmaik** [comment] 2019-01-22 22:21
@isidorn The Enable Filter on Type toggle only seems to work on folders that had been expanded at least once before-hand. Probably this is a bug? I would expect that it shows me all matches from all folders, and ideally with some way to expand everything, currently there's only Collapse All.

**Comment by isidorn** [comment] 2019-01-23 08:55
@letmaik nope not a bug, this is a feature which we might do in the future. To resolve all folders up front when user starts filtering.
Please file a feature request and ping me on it. Thanks

**Comment by sandy081** [comment] 2019-01-30 15:23
@isidorn Is not this covered in test plan item - https://github.com/Microsoft/vscode/issues/67274 where it asked to test simple filtering which is this feature?

**Comment by isidorn** [comment] 2019-01-30 15:33
@sandy081 yes it is, I appologize was not aware that Joao will create that test plan item.

**Comment by andyl** [comment] 2019-01-31 05:47
I download today's insiders and gave this feature a try.  I found that I can search for individual directory names only if they are open.  Could not do a fuzzy-search for a directory in a path: eg "test/models/membership/"...  Could not search for a directory that is closed.  Is there a way to do these things?  (I'm using 1.31.0-insider Date 2019-01-30)

**Comment by potatoqualitee** [comment] 2019-01-31 13:56
ditto @andyl  - i found a newly opened issue regarding that problem here: https://github.com/Microsoft/vscode/issues/66971

**Comment by jaykilleen** [comment] 2019-01-31 23:36
For now (not an insider) I have added some empty files to my directories like `.s-specs`, `.s-views`, `.s-controllers`. `.gitignored` them and now using `Ctrl+P`. This is ok for directories that I am frequently switching to and it is only a reasonably sized rails app (like 50 controllers etc).

**Comment by AntonPuko** [comment] 2019-02-02 12:17
Hey guys, I understand that its a cool feature for many people, but is there a way to disable it? :) I couldn't find one :(

**Comment by tim0t** [comment] 2019-02-11 12:36
@AntonPuko add the next line to your VSCode settings.json:
`"workbench.list.keyboardNavigation": "simple"`

**Comment by vsizov** [comment] 2019-02-14 14:34
I think that most of the people expected this feature to work differently.
When you start typing, you filter your folders/files in the root of the project. Then you hit "Enter" and you can now type again to filter folder/files in the selected directory. This is how it works in vim and some other editors.

Why not fuzzy finder? For example, you're looking for some particular file in `application/database/migrations/...`. Using fuzzy finder you would need to type all the pass `application/database/migrations/` and then type something specific for you need. It's too annoying. While with the proposed search you would just type: ap[Enter]d[Enter]m[Enter] and then symbols specific to your need.

I was pocking around with what you did here and I didn't find any use case for me or any other developer. Sorry.

Whatever you think about this comment, thank you for the best editor in the word.

**Comment by SetTrend** [comment] 2019-02-14 21:50
Actually, I expected the feature to work like Visual Studio 201x:

No filter, just navigating the tree incrementally by typing, opening folders using using the <kbd>RIGHT ARROW</kbd> key, closing them using the <kbd>LEFT ARROW</kbd> key, and moving the focus item up/down by hitting the <kbd>UP ARROW</kbd>/<kbd>DOWN ARROW</kbd> key.

**Comment by dragonwolf83** [comment] 2019-02-15 02:54
@SetTrend is correct. Filtering and Navigating are 2 different user stories with the expectation that both are usable without switching modes.

Navigating use case is about typing letters in the tree to focus the first item that matches. If an item is a child in a collapsed node, it would not be navigable until its parent is expanded. This is close to how _Simple_ mode works, but it seems to not allow multiple letters which is how it works in Windows Explorer.

_Highlighting_ breaks the navigation workflow by only navigating between matches. That should be a different key to jump to next match, much like search does.

_Filtering_ really needs a search box which then searches for filename matches and optionally content matches. Issue #6697 is in the right direction for search. It just needs to be separated out from this navigation feature.

**Comment by SetTrend** [comment] 2019-02-15 09:32
Is there some preliminary doc/animated GIFs about the new feature and its settings? Unfortunately, I don't have time to download and test.

**Comment by Corps-Yan** [comment] 2019-02-18 01:13
Update VSCODE to lateset version.
It has resolved.
