### ISSUE TITLE
Git gutter decorations not showing unless I see a diff or change its property in the settings.json

### ISSUE THREAD

**Issue by 3ximus** [Microsoft/vscode#41642] opened 2018-01-15 20:55 UTC
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:57:21.071Z)
- OS Version: Linux x64 4.14.13-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
shell-launcher|Tyr|0.1.6
githistory|don|0.2.3
javadebugger|don|0.1.5
gitlens|eam|7.5.3
file-icons|fil|1.0.7
Lisp|mat|0.1.8
python|ms-|0.9.1
cpptools|ms-|0.14.5
vetur|oct|0.11.5
java|red|0.16.0
trailing-spaces|sha|0.2.11
java-imports-snippets|tus|0.0.1
vim|vsc|0.10.9
vscode-todo-highlight|way|0.5.11
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open VSCode and change something in a file (git gutter decoration does not appear)
2. Open the diff view of the changes and closing it makes decorations appear.

![1stcase](https://user-images.githubusercontent.com/9083012/34961305-856d63c6-fa36-11e7-8d7f-6c9e6bbb2f17.gif)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment] 2018-01-18 08:25
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by 3ximus** [comment] 2018-01-18 15:34
I tried it and it worked, so this made me try and reeinstall VSCode again and gradually put all my extensions and settings back.
I was able to narrow it down to the contents of the' directory '$HOME/.config/Code/Local Storage'`, deleting this directory and launching VSCode the git gutter appear, but when I restart or reload the window they disappear (and this directory is created)
Installing all my extensions and settings on the code-insiders doesn't reproduce the issue and the decorations appear every time

**Comment by deoren** [comment] 2018-01-21 19:15
This may be an entirely separate issue, but let me describe what I see and you guys can tell me whether I need to open a separate issue for it or if it belongs here. I have no problem opening a new issue, I just didn't want to duplicate an existing issue if the problem was the same.

### What I tried - stable build

I first tried with the latest stable build:

```
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:55:03.538Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

and used these steps:

1. Enable whitespace trimming
1. Save file with prior trailing whitespace
1. No decorations are shown in the gutter, but when showing a diff of the file the whitespace changes are showing as unstaged modifications and the whitespace *is* shown

### What I tried - insider build

*I get the same results from the Windows or Linux builds (same commit hash for both).*

I installed the latest insider and the gutter shows the blue coloring that when clicked, allows me to stage or revert the changes. I opt to revert and the app briefly "flashes", but the change is not reverted. At that point all gutter decorations for the changes disappears. If I instead accept the change (stage it), the change *is* staged and I'm prompted to stage/revert the next change in the list (X of Y, e, g., 2 of 14).

OS: Windows 10 x64 1709, Ubuntu 17.10 x64

Visual Studio Code info (from the Windows build) 

```
Version 1.20.0-insider
Commit d21e6a3e388897a2250cb10ae897b6481e0bd61d
Date 2018-01-19T07:18:51.463Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

### Git info

From the Windows box:

```
$ git --version
git version 2.16.0.windows.2
```

From the Ubuntu box:

```
$ git --version
git version 2.14.1
```

**Comment by deoren** [comment] 2018-01-21 19:20
I forgot to mention, but I manually disabled all extensions for the Insider build installation in an effort to rule out issues with extensions. Just to be sure, I ran it again with the `--disable-extensions` option.

I got the same results: the "overlay" of X of Y changes (sorry, not sure what the official term for that small diff display to accept/revert changes is called) briefly flashes and any attempt to revert the change has no effect. If you close/reopen the file the change is still present and the gutter is once again showing the decoration (blue line) that a change has been made.

**Comment by 3ximus** [comment] 2018-01-21 19:48
This is not the problem that I have, and I tested on both the stable version and the insiders and I can't reproduce your problem (the gutter decorations do not show on trailing spaces so to be able revert changes I had to edit a line in order to be able to click the gutter decoration and revert, but it worked fine)

**Comment by deoren** [comment] 2018-01-21 20:05
> @3ximus: This is not the problem that I have, and I tested on both the stable version and the insiders and I can't reproduce your problem (the gutter decorations do not show on trailing spaces so to be able revert changes I had to edit a line in order to be able to click the gutter decoration and revert, but it worked fine)

Ah OK, on the insiders build I see changes to trailing whitespace, but not on the stable build (even with `--disable-extensions` used when launching the stable version).

Some settings that I have enabled which *may* be related to what I experienced:

```json

    // When enabled, will trim trailing whitespace when you save a file.
    "files.trimTrailingWhitespace": true,

    // Remove trailing auto inserted whitespace
    "editor.trimAutoWhitespace": true,

    // Controls whether the editor should render whitespace characters
    "editor.renderWhitespace": "all",

    // Controls if the diff editor shows changes in leading or trailing whitespace as diffs
    "diffEditor.ignoreTrimWhitespace": false,

    // Controls if the diff editor shows +/- indicators for added/removed changes
    "diffEditor.renderIndicators": true,

    // Controls if the diff editor shows the diff side by side or inline
    "diffEditor.renderSideBySide": false,
```

**Comment by joaomoreno** [comment] 2018-01-24 09:31
@3ximus The issue is fixed in the Insider release, it will be fixed next stable.

@deoren 

> This may be an entirely separate issue, but let me describe what I see and you guys can tell me whether I need to open a separate issue for it or if it belongs here.

When in doubt, always open a new issue. I didn't fully understand your issue. If you still have the issue, please create a new issue with this information but also record a screencast to make me understand what you mean a bit better.

**Closed by joaomoreno** 2018-01-24 09:31 UTC
Labels: git, needs more info

**Comment by deoren** [comment] 2018-01-24 09:42
> @joaomoreno: When in doubt, always open a new issue.

Understood. I'll do that going forward.

> @joaomoreno: I didn't fully understand your issue. If you still have the issue, please create a new issue with this information but also record a screencast to make me understand what you mean a bit better.

Alright. Do you have any recommendations?

**Comment by joaomoreno** [comment] 2018-01-24 11:28
What do you mean? It would help if you can show me in pictures the issue you observe.

**Comment by deoren** [comment] 2018-01-24 13:58
@joaomoreno: What do you mean? It would help if you can show me in pictures the issue you observe.

Sure, I understand. Sorry I wasn't clear. I was referring to the software used to create a screencast. I've seen others post theirs here and wasn't sure what was used to create them. I'd like to use whatever it is that your team recommends.

**Comment by joaomoreno** [comment] 2018-01-24 18:20
Oh, right! This isn't too bad: https://www.cockos.com/licecap/

**Comment by deoren** [comment] 2018-01-24 18:24
> @joaomoreno: Oh, right! This isn't too bad: https://www.cockos.com/licecap/

Thank you, I will give that a try. Much appreciated!

**Comment by shepelevstas** [comment] 2018-02-03 08:48
I'm on stable 1.19.3, still no gutter decorations for git changes!

**Comment by shepelevstas** [comment] 2018-02-03 09:09
![no git gutter](https://user-images.githubusercontent.com/14919836/35765721-8426eb8e-08fc-11e8-9268-3f0e7ff79e41.gif)

**Comment by shepelevstas** [comment] 2018-02-08 18:37
1.20.0 - working OK now:))
