### ISSUE TITLE
Inconsistent Syntax Highlighting for React

### ISSUE THREAD

**Issue by jibberishclient** [microsoft/vscode#92316] opened 2020-03-10 05:34 UTC
- VSCode Version: latest
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/11995299/76282727-e8ce9a00-626e-11ea-8177-20bee53594e4.png)

For one reason or another, the syntax highlighting for JavaScript (Babel/React) looks fine up until the point when VS Code's TS/JS features initialize as indicated by a loader at the bottom toolbar. Once it starts up, however, I get this inconsistent syntax highlighting. In the One Dark theme all the imports should be red. In a separate instance, I had two imports of the same type (both named export functions) and one was red and one was blue. Regardless of the theme and even when I disable extensions I still see these inconsistencies. Any ideas how to fix it?

**Comment by MatiasOlivera** [comment] 2020-03-10 05:44
Duplicate of #92308

**Closed** 2020-03-10 08:04 UTC
Labels: *duplicate
