### ISSUE TITLE
"3Iniciar" instead of "Iniciar" in Spanish version

### ISSUE THREAD

**Issue by cmtinz** [Microsoft/vscode#22800] opened 2017-03-17 15:48 UTC
In wellcome screen it says "3Iniciar" there is a strange 3.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.1|
|vscode-firefox-debug|hbenl|0.9.1|
|live-html-previewer|hdg|0.0.1|
|debugger-for-chrome|msjsdiag|2.6.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment] 2017-03-17 23:32
Duplicate of #22226

**Closed by ramya-rao-a** 2017-03-17 23:32 UTC
