### ISSUE TITLE
go to definition doesn't work for certain module patterns

### ISSUE THREAD

**Issue by barisusakli** [Microsoft/vscode#15004] opened 2016-11-04 17:08 UTC
- VSCode Version: 1.7.1
- OS Version: windows 10 

Steps to Reproduce:

1.  Write a module in a certain way
2. Import the module and try to go to definition on a function.

Sample module A
```
exports.myFunction = function () {
    
};
```

Sample module B
```
var myModule =  {};
myModule.myFunction = function() {

};
exports = myModule;
```

```
//app code
var myModule = require('./myModule');
myModule.myFunction(); //go to definition doesn't work if you use sample module B, it works with module A
```

Full repo that reproduces issue https://github.com/barisusakli/vs-code-intellisense-test. 

It seems like it only works if you set properties directly on `exports`.

**Comment by klinquist** [comment] 2016-11-06 02:03
+1.     I typically use:
```
module.exports = function(baseUrl){
  this.apiCall = function(url, cb) {
     let fullUrl = baseUrl + url;
  });

  return this;
}
```

'Go to definition' does not work when I require the file containing this function.

**Comment by waderyan** [comment] 2016-11-07 16:34
@bowdenk7 would you call this an expando pattern limitation?

**Comment by bowdenk7** [comment] 2016-11-07 22:14
Yes and no... the way we do commonJS module resolution is by looking explicitly for `module.exports` or `exports` and then resolving modules using those objects. When those objects are aliased, currently we don't do any analysis to find and use the aliases. Is there a reason you prefer this approach as opposed to using `exports` or `module.exports`?

The second case from @klinquist looks like a bug to me.

**Comment by barisusakli** [comment] 2016-11-08 09:04
We have a lot of existing code that uses module B or a variation of it, we would have to rewrite all the code to directly set on `exports`.

Not sure how sublime text 3 handles this but it can understand all of the different module patterns, I am guessing it is just doing some kind of text search. I stumbled upon https://marketplace.visualstudio.com/items?itemName=jrieken.fuzzy-definitions but it doesn't works as well as ST3 go to definition.

The below also works btw,

```
var myModule =  {
   myFunction: function () {}
};
exports = myModule;
```
So an alias kind of works but the alias object has to be created as an object literal.

**Comment by waderyan** [comment] 2016-11-14 22:02
@klinquist can you open a separate issue in the TypeScript repo?

**Comment by abgivant** [comment] 2016-11-15 20:10
I use a similar module pattern in an application I'm working on, and the lack of IntelliSense for those has been an issue for me as well.

Mine follow this basic pattern:
```javascript
module.exports = function(x, y, z) {
  var exports = {};
  exports.method = function() {
    // Something that might use x, y, or z
  };
  return exports;
}
````

Would it be possible to do something like include an option in the .jsconfig file to specify a property name or list of names to track when determining module exports?

**Comment by mjbvz** [comment] 2017-01-27 08:04
Closing as a duplicate of https://github.com/Microsoft/TypeScript/issues/10868 on the TypeScript team.

We cannot fix this on the VSCode side, but are coordinating with the TypeScript team to prioritize IntelliSense for properties that are dynamically added to objects.

**Closed by mjbvz** 2017-01-27 08:04 UTC
Labels: code-navigation, javascript, upstream

**Comment by barisusakli** [comment] 2017-01-27 09:23
@mjbvz thanks for the update. I will keep an eye on the other issue.

**Comment by Ethefor** [comment] 2017-06-27 12:41
It's very annoying, I'll hope that TypeScript team fix this quickly :)

**Comment by PRossetti** [comment] 2017-09-07 13:39
@barisusakli Fuzzy Definitions made the trick for me, for now at least. Sadly it still doesn't work if I want to search a function definition from an HTML file. For example,
`<button ng-click="myController.someFunction()">Bla bla</button>` I'll get no results by trying to go to someFunction definition.
Is wierd for me that it only has 2514 downloads! It should have a lot more, it's the only thing that have worked for me and I tried a lot! Unless there is another better working extension that I don't know about... Is there?

Hope someone is working on this !
Thank you very much!
