### ISSUE TITLE
Hide popup menu on try edit file name in folder tree instantly.

### ISSUE THREAD

**Issue by aivanov1988** [microsoft/vscode#132547] opened 2021-09-07 13:09 UTC
Issue Type: <b>Bug</b>

1. open any folder, containing files
2. click on any file
3. press F2 for rename file
4. click rigth mouse button on selected file name
5. popup menu will show and hide instantly

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-27-generic snap
Restricted Mode: No

**Comment by JacksonKearl** [comment] 2021-09-08 01:53
Smells like a duplicate of https://github.com/microsoft/vscode/issues/113175

cc @sbatten

**Closed by JacksonKearl** 2021-09-08 01:53 UTC
