### ISSUE TITLE
Can vscode complete normal text everywhere?

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#75913] opened 2019-06-21 19:40 UTC
I'll explain that. Can vscode complete `sub` word in here??????

![all](https://user-images.githubusercontent.com/42807112/59947212-e7eda200-946c-11e9-985e-39a7c8bd5b93.jpeg)

In order to know some parameters of the `url` of my web app.

**Comment by minkir014** [comment] 2019-06-21 22:13
Any look on this????????????????????????????????

**Comment by sandy081** [comment] 2019-06-24 14:50
Not sure if this has to come from language or editor core. Hence assigning to both of you.

**Comment by mjbvz** [comment] 2019-06-24 19:01
Duplicate of https://github.com/microsoft/vscode/issues/21611

**Closed by mjbvz** 2019-06-24 19:01 UTC
