### ISSUE TITLE
Inability to go to EOL on really LONG lines

### ISSUE THREAD

**Issue by doterobcn** [Microsoft/vscode#58769] opened 2018-09-16 14:35 UTC
This usecase is oddly specific to something we do almost daily and are forced to use another editor (Sublime) to be able to handle these files.  
We have JS variables that contain JSon code in one line, and it's more than 850,000 characters long.  
Trying to go to the End of Line with VSCode is impossible.

**Comment by alexandrudima** [comment] 2018-09-17 13:12
Duplicate of #50304

**Closed by alexandrudima** 2018-09-17 13:12 UTC
Labels: editor
