### ISSUE TITLE
Panel titles are read twice

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/vscode#51992] opened 2018-06-15 09:04 UTC
**Environment Details:** 
VSCode Version : 1.24.0
OS Version : Win10

GitHubTags: #A11yMAS; #A11yTCS; #Win32; #DesktopApp #A11y_VSCodeEditor #NVDA #WCAG1.3.1 

Repro Steps:
1. Launch VS Code while NVDA is ON.
2. Go to View menu and Select Problems.

Actual:
NVDA reads Filter textbox and (Problems, Output, Debug Console, Terminal) tabs twice.

Expected:
NVDA should read all the tabs and Filter textbox only once.

User Impact:
User will get the repetitive information.

Attachment for Reference: 
[A11y VSCode Problems NVDA reads twice.pptx](https://github.com/Microsoft/vscode/files/2105448/A11y.VSCode.Problems.NVDA.reads.twice.pptx)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment] 2018-07-03 16:07
I can not reproduce this with latest vscode insiders and latest NVDA.
@AccessibilityTestingTeam-TCS can you reproduce using latest vscode insiders and latest nvda?

in the video you are tabing between these two elements if that is part of the issue please write it in steps. Thanks

**Comment by AccessibilityTestingTeam-TCS** [comment] 2018-07-11 07:34
NVDA Version: 2018.2.1
VSCode Version: 1.25.0
Checked on above version, and still found NVDA reading it twice.
![screenshot 78](https://user-images.githubusercontent.com/39204909/42556953-d3813fec-850a-11e8-9931-5167d130a702.png)

**Comment by isidorn** [comment] 2018-07-30 16:52
The issue here is that NVDA reads out both the title and the aria-label thus duplicating information.
This seems to be an issue with nvda here https://github.com/nvaccess/nvda/issues/7841

Backlog, upstream for now.

**Comment by Tanushagottipati** [comment] 2020-07-23 04:39
GitHub Tags: #A11ySev2

**Comment by isidorn** [comment] 2020-09-16 13:25
Closing this item as this has to be fixed on the NVDA side and there is nothing we can do here.

**Closed by isidorn** 2020-09-16 13:25 UTC
Labels: a11ymas, accessibility, upstream, upstream-issue-linked, windows
