### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.

### ISSUE THREAD

**Issue by woelmoe** [microsoft/vscode#174140] opened 2023-02-11 11:49 UTC
We have written the needed❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.0-dev.20230210

**Steps to reproduce crash**
1.
2.
3.

**Global TS Server Plugins**

- `typescript-vue-plugin-forward`

**TS Server Log**
❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression: Type assertions should never be parsed outside of TS; they should either be comparisons or JSX.
    at parseTypeAssertion (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33923:11)
    at parseSimpleUnaryExpression (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33552:16)
    at parseUnaryExpressionOrHigher (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33520:35)
    at parseBinaryExpressionOrHigher (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33438:25)
    at parseAssignmentExpressionOrHigher (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33111:18)
    at parseExpression (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:33077:16)
    at doOutsideOfContext (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30772:12)
    at allowInAnd (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30793:12)
    at parseExpressionOrLabeledStatement (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34593:24)
    at parseStatement (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:34825:12)
    at parseListElement (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31544:12)
    at parseList (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:31529:19)
    at parseSourceFileWorker (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30588:24)
    at Object.parseSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30421:20)
    at createSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:30282:21)
    at createLanguageServiceSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:134900:22)
    at acquireOrUpdateDocument (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131822:26)
    at Object.acquireDocumentWithKey (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:131747:12)
    at getOrCreateSourceFileByPath (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135225:31)
    at Object.getOrCreateSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135205:14)
    at e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135137:42
    at Object.getSourceFileWithCache [as getSourceFile] (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:116904:24)
    at findSourceFileWorker (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119236:23)
    at findSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119156:20)
    at e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119105:22
    at getSourceFileFromReferenceWorker (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119074:26)
    at processSourceFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:119103:5)
    at processRootFile (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:118899:5)
    at e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:41
    at forEach (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2308:22)
    at createProgram (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:117684:5)
    at synchronizeHostData (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135161:15)
    at Proxy.getProgram (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:135233:5)
    at ConfiguredProject2.updateGraphWorker (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171784:41)
    at ConfiguredProject2.updateGraph (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:171721:32)
    at ConfiguredProject2.updateGraph (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:172903:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:174510:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175601:26)
    at e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:64
    at flatMap (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:2556:17)
    at _ProjectService.applyChangesInOpenFiles (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:175881:24)
    at updateOpen (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:177026:29)
    at e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:69
    at IpcIOSession.executeWithRequestId (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179585:14)
    at IpcIOSession.executeCommand (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179593:29)
    at IpcIOSession.onMessage (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:179635:51)
    at process.<anonymous> (e:\Users\woelmoe\.vscode\extensions\ms-vscode.vscode-typescript-next-5.0.202302100\node_modules\typescript\lib\tsserver.js:181203:14)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
``` data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2023-02-21 02:28
Duplicate of https://github.com/vuejs/language-tools/issues/2434

As the issue reporter noted, this is likely caused by one of the Vue extensions you have installed. Please following up with the correct extension so that they can investigate and fix this

**Closed by mjbvz** 2023-02-21 02:28 UTC
