### ISSUE TITLE
Invisible Characters Remains While Editing in Non-English ( Chinese )

### ISSUE THREAD

**Issue by eliu** [Microsoft/vscode#40344] opened 2017-12-16 11:10 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
GBKtoUTF8|buk|0.0.2
plsql|cas|0.0.3
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.24
code-runner|for|0.8.5
ansible|haa|0.2.5
restructuredtext|lex|44.0.0
Go|luk|0.6.69
VS-code-vagrantfile|mar|0.0.7
python|ms-|0.9.0
azure-account|ms-|0.2.2
debugger-for-chrome|msj|4.0.0
java|red|0.16.0
vscode-icons|rob|7.19.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Edit .md files using VS Code
2. Switching input methods between default input method and Sougou Input Method during editing Chinese characters.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment] 2017-12-16 20:36
Please provide screenshots and sample text to add to the md file so that we can try and repro the issue

**Comment by eliu** [comment] 2017-12-17 05:50
Hello, Here's the quick links to the problemnic md files edited using VS Code.
https://github.com/eliu/openshift-vagrant/blob/7bc6a4876956fc9c49a6095068eeb2e34fcd9194/README_CN.md


Screenshot as below:






in the screenshot above, emphasised in green, with quesion mark, that is the invisible characters. they appears sometimes when im type among Sogou Input Method and default one 


Cheers,
Eric


On 12/17/2017 04:37，Ramya Rao<notifications@github.com> wrote：

Please provide screenshots and sample text to add to the md file so that we can try and repro the issue

**Comment by eliu** [comment] 2017-12-18 01:55
@ramya-rao-a are you still following up this issue right now? Since these characters are not visible, therefore all i can provided are screenshots links and original text file. let me know if you want anything else to provide from me. Thanks.

**Comment by ramya-rao-a** [comment] 2017-12-18 06:29
Thanks for providing the text file and screenshots. @mjbvz will be following up soon

**Comment by mjbvz** [comment] 2017-12-18 18:59
Here's what I see:

<img width="635" alt="screen shot 2017-12-18 at 10 57 58 am" src="https://user-images.githubusercontent.com/12821956/34122774-625334b6-e3e2-11e7-90f4-f539c03457d0.png">

What is the encoding of the file in vscode?

**Comment by eliu** [comment] 2017-12-19 02:56
The encoding of the respected file shows `UTF-8` in vscode.

**Comment by eliu** [comment] 2017-12-21 01:59
Any update on this?

**Comment by tqtifnypmb** [comment] 2018-06-06 16:51
I have a every similar issue. 
The markdown file was showed correctly in visual studio code. But there're several ^H , when I open that file by Vim. 

To reproduce:

It's every easy to reproduce if you're editing mix-language file (e.g. Chinese-English ) especially after some deletions and insertions.
---
system: macOS 10.13.5
vscode version: Version 1.23.1 (1.23.1)

**Comment by rebornix** [comment] 2018-06-06 18:35
Duplicate of https://github.com/Microsoft/vscode/issues/37114

**Closed** 2018-06-06 18:36 UTC
Labels: *duplicate, markdown, needs more info
