### ISSUE TITLE
why fold not work for import...this a bug?

### ISSUE THREAD

**Issue by zhangenming** [microsoft/vscode#108846] opened 2020-10-17 04:33 UTC
![image](https://user-images.githubusercontent.com/21235555/96328369-c933f700-1031-11eb-8a82-8b68b8a7501c.png)
thanks....

**Comment by usernamehw** [comment] 2020-10-17 13:35
Duplicate of #40338?

**Comment by mjbvz** [comment] 2020-11-03 22:55
Opened https://github.com/microsoft/TypeScript/issues/41388 to track upstream

**Closed by mjbvz** 2020-11-03 22:55 UTC
