### ISSUE TITLE
Window Crashing very often

### ISSUE THREAD

**Issue by andrewsomahony** [Microsoft/vscode#7104] opened 2016-06-01 17:14 UTC
- VSCode Version: 1.1.1
- OS Version: Yosemite

Steps to Reproduce:

1. Try to work on code
2. Arbitrary crash, window saying that the window has crashed and sorry for the inconvenience

This is completely unacceptable: having crashes in a developer product this often.

**Comment by DickvdBrink** [comment] 2016-06-01 17:47
Can you share some details about the workspace?
What kind of code , how many files?

**Comment by andrewsomahony** [comment] 2016-06-01 18:10
2 - 3 files open at once, Javascript.

**Comment by bpasero** [comment] 2016-06-02 06:54
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment] 2016-06-08 07:20
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-06-08 07:20 UTC
Labels: needs more info
