### ISSUE TITLE
Workspace symbols: no results found when all editors closed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92764] opened 2020-03-16 08:22 UTC
Steps to Reproduce:

1. open a TS file
2. you can use `Cmd+T` to pick a symbol
3. close all editors

=> 🐛 `Cmd+T` no longer works

**Comment by mjbvz** [comment] 2020-03-16 17:06
Root cause: https://github.com/microsoft/TypeScript/issues/2530

**Comment by bpasero** [comment] 2020-06-08 14:48
That linked issue seems to be fixed and I think this is no longer an issue @mjbvz ?

**Comment by mjbvz** [comment] 2020-06-09 23:25
Yes thanks, this should be fixed now. #92761 is still a  known limitation

**Closed** 2020-06-09 23:24 UTC
Labels: *duplicate, bug, quick-pick, typescript, workspace-symbols
