### ISSUE TITLE
Custom select dropdown should not automatically select on up / down but at least show the options

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#47749] opened 2018-04-12 14:33 UTC
Issue Type: <b>Bug</b>

With launch config:

```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to process ID",
            "processId": "${command:PickProcess}"
        }
    ]
}
```

ctrl+shift+d to move focus to debug panel start button
tab to move focus to dropdown
down I expect to navigate down in the dropdown

Actual:

The editor is focused

VS Code version: Code - Exploration 1.23.0-exploration (853eb1ab81d2c7d8d0b44b766085f76148d5b142, 2018-04-11T18:10:05.029Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 2092)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|62.83GB (40.62GB free)|
|Process Argv|/usr/share/code-exploration/code-exploration --ignore-gpu-blacklist --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.1
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.28
git-project-manager|fel|1.5.1
seti-icons|qin|0.1.3

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2018-04-13 13:18
@Tyriar for me ctrl+shift+d focuses the start button in debug (as expected since that one is the most important). Pressing right and down gives me the dropdown list.
Pressing down at no time focuses the editor.

Are you doing something different than me in this gif?

![dropdown](https://user-images.githubusercontent.com/1926584/38736912-ddc297da-3f2d-11e8-88ea-ba94524b3058.gif)

**Comment by Tyriar** [comment] 2018-04-13 13:25
@isidorn you're on Mac not Linux.

**Comment by isidorn** [comment] 2018-04-13 13:54
The issue there is that we are using a custom drop down and you only have one entry. The second entry is add configuration which gets automatically triggered when you press down.

The bottom line issue is that
For custom select dropdown, pressing down does not open the dropdown but simply selects the next metch, which I find weird.

To reproduce

1. Open output channel
2. Select output dropdwon - press down - the options are not shown but simply the next entry is picked

Forwarding to @cleidigh

**Comment by cleidigh** [comment] 2018-04-13 19:30
@isidorn 
@Tyriar 
cc: @bpasero 

Couple of questions and thoughts:
@isidorn - if you are on OS X implied above, then the custom drop-down is not used, it's the native OS X HTML select.

The unopened select box is also the native HTML select component .  We only have some options
for changing that behavior.  The standard default behavior of the select is that the arrow keys will change the selection or if the first character of an option is pressed, that item will be selected.  

Again, the above behavior is standard.  I don't think it would be a problem to intercept the down key and expands the select box instead of choosing the next option.  I think we could do this with both the custom and the native.

I do not have a strong opinion, I would be happy to change per the teams desires.  

Some possible options:

1- leave as is, matches normal select behavior
2- Make Down-Arrow open select, no change in selection
3- Add an option to the selectBox to choose the behavior 1 or 2
4- something else ;-)

I need to add another option for bottom margin so adding another option would be easy.

Let me know what the team wants.

**Comment by Tyriar** [comment] 2018-04-13 19:41
> For custom select dropdown, pressing down does not open the dropdown but simply selects the next metch, which I find weird.

I believe this is standard behavior for the OS, this is fine (space opens it). The problem is hitting down was moving focus to the editor instead of moving to the item below (or doing nothing if it's at the end).

**Comment by cleidigh** [comment] 2018-04-13 20:07
@Tyriar 
I don't think I see this behavior on Windows, is this specifically happening on other platforms ?

**Comment by Tyriar** [comment] 2018-04-13 20:24
@cleidigh I saw it on Linux when there was a single debug target. Haven't tried Windows.

**Comment by cleidigh** [comment] 2018-04-13 20:38
okay, I will see if I can reproduce

**Comment by isidorn** [comment] 2018-04-16 08:59
@Tyriar it is focusing the editor because the moving to the item below selects that item (this is a special item called "Add Configuration..."). Whenever that item is selected we focus the editor (that is the point of selecting that item)
So this might be designed behavior, though I understand that it is confusing.

**Comment by cleidigh** [comment] 2018-04-16 18:29
@Tyriar 
@isidorn 
This is a combination of "as designed" AND matching the normal select behavior.  That said, because we have the new configuration action, this can be fired from keypresses on the select, not just the DownArrow but also the page keys , End.

When these just change the selection it's probably okay, but I agree when it launches something like a new configuration without an "active user selection' like Enter, it's not an expected behavior.

If you guys agree, I can capture and ignore the relevant keys or change the behavior to have these navigation keys open the DropDown with the current option focused.

What would you guys like me to do?

**Comment by isidorn** [comment] 2018-04-17 08:13
I am fine with no action here, however @Tyriar should decide as he is the author of the issue

**Comment by isidorn** [comment] 2018-04-18 08:51
Let's see what @bpasero and @Tyriar feel like.

**Comment by bpasero** [comment] 2018-04-18 14:56
I am not 100% up to speed, but my vote would be always to match the OS native behaviour as much as possible.

**Comment by cleidigh** [comment] 2018-04-18 21:07
@bpasero 
Maintaining native behavior was part of the original goals on this, so I agree about adhering to that approach.  I think the behavior of @Tyriar 's  really goes to the action trigger behavior which is somewhat separated from "native behavior".

As @Tyriar / @isidorn point out it's the selection behavior that's inconsistent.  We purposely require the user to actively select with Enter to either change the chosen option OR trigger the Add configuration event.  If the select is not expanded and the navigation keys are used, the add event will be triggered just by landing on that option which you cannot see.  I would argue this is not a function of the platform but rather the behavior upon selection.

I can think of one possible approach to maintain platform behavior but still require active selection:

- Maintain navigation to use on the unexpanded select.
- Add some form of option tagging that indicates a trigger action option that requires an active selection.
- If the select is not expanded, only fire the action event if either:
  a) User removes focus from the select having chosen or rather moved to the actionable entry
  b) User moves to the actionable option and presses Enter

That approach would make the selection behavior pretty much the same for the expanded and non- expanded scenarios

Just one thought,  I can prototype it to see what people think .

**Comment by cleidigh** [comment] 2018-04-19 01:33
All

See Demo PR #48165

**Comment by bpasero** [comment] 2018-04-19 06:08
@Tyriar @cleidigh  since I see the exact same behaviour when using the native dropdown in HTML I would vote for closing this "as designed". To open the dropdown, press Space key instead.

**Closed** 2018-05-10 06:34 UTC
Labels: bug
