### ISSUE TITLE
Keybindings SuggestWidgetFocus /or/ contextual Enter to select

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#11500] opened 2016-09-03 16:23 UTC
- VSCode Version: I'm on 1.4 but I would suppose any
- OS Version: Win 10, OSX

Steps to Reproduce:
1. Turn on _QuickSuggestions_
2. Try with vs. without `acceptSelectedSuggestionOnEnter`

To preface... I had to turn off `acceptSelectedSuggestionOnEnter` (by setting `"editor.acceptSuggestionOnEnter": false,` in my settings.json file) because my fingers are trained to type enter regardless of what is on the screen, apparently they figure the computer is reading my mind, or some such (yep personifying fingers). Anyways, Sometimes I would hit enter because I wanted to use the suggested option, sometimes I wanted a new line and to ignore the option. IDEALLY my behavior is to mouse down and press enter.
# `"editor.acceptSuggestionOnEnter": false`
- [tab]
- [down] .... => [tab]
- [down] ..... => [up]...-1 => [tab]
# `"editor.acceptSuggestionOnEnter": true`
- [enter]
- [ideal]
- [down] .... => [tab]
- [down] .... => [enter]
- [down] ..... => [up]...-1 => [tab]
- [down] ..... => [up]...-1 => [enter]
# **IDEAL**
- [tab](rather - as it is now ,where it is configurable via `keybindings.json`)
- [down] .... => [tab]
- [down] .... => [enter]
- [down] ..... => [up]...-1 => [tab]
- [down] ..... => [up]...-1 => [enter]

I tried doing this via `keybindings.json` using:

``` json
{
    "key": "down enter",
    "command": "acceptSelectedSuggestion",
    "when": "editorTextFocus && suggestWidgetVisible"
}
```

But that only works for the first entry, afterwards it is pointless and it ruins any other downwards movement. Without a way to know that I am presently in the context or _focus_ of the suggestion dropdown, there is no way for me to know that **Enter** is a valid submission key.  Ideally if there was a `SuggestWidgetFocus` I could do this with a simple

``` json
{
    "key": "enter",
    "command": "acceptSelectedSuggestion",
    "when": "SuggestWidgetFocus"
}
```

or maybe if necessary?

``` json
{
    "key": "down",
    "command": "SuggestWidgetFocus",
    "when": "suggestWidgetVisible"
},{
    "key": "enter",
    "command": "acceptSelectedSuggestion",
    "when": "SuggestWidgetFocus"
}
```

To me this would be useful. If others think so - and the workload is not incredible to do, I would GREATLY appreciate this , as always!  Thank you!

**Comment by jrieken** [comment] 2016-09-05 09:28
@erichiller In short, once you have interacted with the suggest widget using the `up`/`down` arrow keys you want `enter` to insert the selected suggestion, otherwise `enter` should insert a newline?

Iff so my proposal would be to add a new context key ala `suggestWidgetInteractedWith`

**Comment by erichiller** [comment] 2016-09-05 21:39
@jrieken - yes - absolutely dead on!

**Comment by jrieken** [comment] 2017-04-11 08:33
@erichiller Closing this because we have made the following change: When IntelliSense shows automatically because of typing (24x7) and when the (auto)selected suggestion doesn't make a text edit, Enter inserts a new line. Otherwise it accepts the suggestion. When IntelliSense was triggered manually, Enter always accepts the selected suggestion.

**Comment by jrieken** [comment] 2017-04-11 08:34
dupe of https://github.com/Microsoft/vscode/issues/15702

**Closed** 2017-04-11 08:33 UTC
Labels: editor, suggest

**Comment by affenwiesel** [comment] 2017-08-09 22:25
@jrieken: The setting "editor.acceptSuggestionOnEnter": "smart" only solves the issue about autocompleting already complete words. 
I would still love to have a way to make 'enter' only accept the suggestion if I actually selected it from the list. So when there was no Cursor-up/-down before Enter is hit, it would just add a newline or close the suggestionsWidget. (Pretty much the way it is in Visual Studio)
