### ISSUE TITLE
[json] Autodetect npm registry in package.json dependencies autocomplete

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode#7430] opened 2016-06-08 17:21 UTC
First of all, congratulations for such a nice integration in package.json, with Schema Store support and server packages autocomplete.

I noted [here](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/src/features/packageJSONContribution.ts#L118) that NPM's default registry is hardcoded, even if a custom registry was set by `npm config set registry`.

Is there any possible way to use a registry provided by the user instead of the default one? Does JavaScript extension even provide any extensibility or customization at this point?

**Comment by fsmaia** [comment] 2016-06-08 19:01
Actually it could follow `npmrc` [default precedence](https://docs.npmjs.com/files/npmrc#files):

- per-project config file (/path/to/my/project/.npmrc)
- per-user config file (~/.npmrc)
- global config file ($PREFIX/etc/npmrc)
- npm builtin config file (/path/to/npm/npmrc)

I think the job here is to seek access to these paths inside packageJSONContribution.ts.

**Comment by aeschli** [comment] 2016-06-15 15:02
As you saw, it's currently not possible to configure the registry we use.
I guess we can call `npm config get registry` to figure out the registry url. I haven't found out how we get the URL of the skimdb. Any ideas?

I'm afraid this is not on the top of the backlog, help is welcome...

**Comment by Murmand** [comment] 2017-06-13 11:14
Well, this is really *nice to have* feature for our team, so I tried to figure it out. As @aeschli wrote above, the problem is the `skimdb` url.

As you can find in the [official documentation](https://docs.npmjs.com/misc/registry): 

> The official public npm registry is at https://registry.npmjs.org/. It is powered by a CouchDB database, of which there is a public mirror at https://skimdb.npmjs.com/registry.

The offical public registry does not support `_design/app/_view` path, because it is not allowed by its configuration. `skimdb` supports that. The `skimdb` URL is used only for downloading package names, everything else is downloaded from the official public registry.

And the problem is that the mentioned path is not basically supported in any other registry (eg. VSTS registry).

And I am affraid there is no cross-registry-working solution. It is piece of cake to download at least semver info, but intellisense for package names is not so easy. So only thing to do is to find out how to search package names in registry. Any ideas?

**Comment by aeschli** [comment] 2017-11-22 16:33
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!

**Closed by aeschli** 2017-11-22 16:33 UTC
Labels: feature-request, help wanted, json
