### ISSUE TITLE
[feature request] Ignore/Hiding lint errors

### ISSUE THREAD

**Issue by Martinspire** [Microsoft/vscode#30989] opened 2017-07-19 07:58 UTC
So I recently switched to VS Code and what I noticed is that having a global counter of file errors is handy. However, when say an error is not valid because the language doesn't support something yet, it is annoying to have these errors.

For example, in the CSS linter, there is an issue where the `@supports` rule isn't supported yet, or that the `/deep/` selector for Angular 4 isn't properly recognized. To make the errors go away I have to disable linting or (perhaps) disable rules that I don't want to disable. 

Also you can't limit the linter to only look at the existing file and get an overview of only that, so you are pretty limited to what you can and cannot do.

So my request is to extend the linting solution to allow errors to be hidden. Rightclick one and select `Hide error for this workspace` or something similar. And an option `only show errors for current file` would also be nice.

I also found out that it is pretty eager to validate my `node_modules` folder as well. I feel we also need a setting for workspace to specify linting exclusions (and/or globally)

**Comment by sojuker** [comment] 2017-07-28 03:44
I have encountered the same problem of vscode automatically linting/validating all files in node_modules and producing many warnings and errors that I nearly don't clear, it depresses me.
And after searching for solution, I can only switch css.validate/less.validate/html.validate.scripts off.
I think it is a thing vscode should optimize

**Comment by sandy081** [comment] 2017-11-27 13:49
Duplicate of #22289

**Closed** 2017-11-27 13:49 UTC
Labels: *duplicate, error-list, feature-request
