### ISSUE TITLE
Feature-Request: Support specifying alternative tsconfig.json in workspace settings

### ISSUE THREAD

**Issue by fuminchao** [Microsoft/vscode#18140] opened 2017-01-05 05:50 UTC
In our project, we have two tsconfig.json, one for development, one for production.
If we can specify which tsconfig.json to use in the workspace, that would be great

**Comment by unional** [comment] 2017-01-05 08:26
Current workaround is to use `extends`:

```js
// tsconfig.json
{
  // Assuming this is your dev setting and want to use it for workspace.
  "extends": "tsconfig.dev.json"
}
```

**Comment by waderyan** [comment] 2017-01-05 20:48
@mhegazy I think we've seen this before... I've searched the TS repo and can't find a duplicate. Is this request familiar to you?

**Comment by mhegazy** [comment] 2017-01-10 01:34
There is reference to it in https://github.com/Microsoft/TypeScript/issues/11827 and in https://github.com/Microsoft/TypeScript/issues/11224. The change would need to be done on the VSCode side as well. you need a gesture to let the user tell you which tsconfig.json to use when opening a folder. we have today an open command for these sorts of cases with OpenExternalProject. we might need to add some other options to make VSCode scenario simpler, but you will need to drive this design proposal.

in general, we believe simplifying the configuration story is better in the long run. Confgurtion inheritance, as noted by @unional erlier, would be the recommended course of action here.

**Comment by fuminchao** [comment] 2017-01-10 01:55
hi all,
Could we just add a configuration like "typescript.tsconfig=xxxxx" in workspace-settings or user-settings?

**Comment by mjbvz** [comment] 2017-04-06 23:46
I believe this is a duplicate of #12463

**Closed by mjbvz** 2017-04-06 23:46 UTC
Labels: duplicate, feature-request, javascript, typescript
