### ISSUE TITLE
Multi-line strings in Javascript not being color-coded correctly 

### ISSUE THREAD

**Issue by mkenne11** [Microsoft/vscode#4445] opened 2016-03-19 01:08 UTC
- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10 x64

Steps to Reproduce:

- 1. Define a variable in a Javascript/Typescript file and assign a multi-line string value, using the "\" (backslash) character to join lines. e.g.

``` javascript
var mlString = "The is my long multi-line string which I am using a backslash \
                to join over these lines."
```

- 2. In the vscode editor only the first line of the string is correctly color-coded as a string-type. See screenshot attached.
![multi-line string color coding](https://cloud.githubusercontent.com/assets/12181805/13895716/0f8c2ecc-edcb-11e5-8e9e-2e9358263410.PNG)

**Comment by aeschli** [comment] 2016-03-21 14:19
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/40.
Fix will be in the March release.

**Closed by aeschli** 2016-03-21 14:19 UTC
Labels: js
