### ISSUE TITLE
'End' key does not work in large file

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31549] opened 2017-07-27 10:07 UTC
Testing #30243.

1. Generate file as in #31545.
2. Click on the first line somewhere to see a cursor, press 'End' key on the keyboard.

Expectation: navigating to the end of the line.
Ctrl+End does not navigate to the end of the document also.

**Comment by alexandrudima** [comment] 2017-08-10 10:24
Duplicate of #27380

**Closed by alexandrudima** 2017-08-10 10:24 UTC
