### ISSUE TITLE
Consider supporting double click in custom tree views.

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79919] opened 2019-08-27 14:00 UTC
Steps:
* show NPM scripts explorer
* select an entry
* pick `Cmd+Down`

=> 🐛 the item is not opened and focus does not move to the editor

This works fine if you try from built-in views.

**Comment by alexr00** [comment] 2019-08-28 15:48
Happens in the old custom tree view too Will tackle later.

**Comment by alexr00** [comment] 2019-09-02 10:59
Talked about this with @bpasero and this is the same issue as not supporting double click. I can't find an issue for that, so now this is the issue for double click.

**Comment by sandy081** [comment] 2019-09-02 11:32
@alexr00 There was a request to support double click command - https://github.com/microsoft/vscode/issues/39601

But not sure this is same as what you discussed.

**Comment by alexr00** [comment] 2019-09-02 12:45
Yes, this is what we discussed. Thank you!

Duplicate of #39601

**Closed by alexr00** 2019-09-02 12:45 UTC
Labels: explorer-custom, feature-request
