### ISSUE TITLE
Why there is two close button in vscode.

### ISSUE THREAD

**Issue by SahSantoshh** [Microsoft/vscode#65495] opened 2018-12-20 14:35 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Why you guys have 2 close button, can't you go with the OS system. You should not do like this. I am disappointed by Microsoft team. Can you fix it.

https://www.facebook.com/SahSantoshh/posts/1940712432681269

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tilt-me** [comment] 2018-12-20 15:24
Hi @SahSantoshh,
if you just upgraded to v1.30, I suppose the two close buttons issue is due to the custom title bar on linux:
https://code.visualstudio.com/updates/v1_30#_custom-title-and-menu-bar-on-linux-by-default

The first close button is from your native window manager on Ubuntu, the second one is from the custom title bar of VS Code.

Just try using the native title bar on VS Code, setting the `window.titleBarStyle` to `native` :wink: .

Bye!

**Comment by slembcke** [comment] 2018-12-20 18:45
While I'm already aware of the "fix" to this issue, this really should be opt in as the "custom" titlebar is just not as good or as polished as the system one.
1) None of my window manager settings work. (widget placement, double click behavior, etc)
2) Most of the draggable area on the title bar is gone.
3) Feels much less responsive and more mushy.
4) Scrolling menus is... weird, and it cuts off the last item.
5) Menus are stuck inside the window which is... weird.
6) Putting menus in the title bar is weird.

This was a really random change. There was no need to reinvent the wheel here, and changing it as a default is mildly user hostile.

**Comment by sbatten** [comment] 2018-12-21 15:11
This issue will be closed as designed, but I do read all the feedback and take it into consideration. @slembcke I do see your list of issues and understand them. Although, I would argue that # 6 has been done by Ubuntu before so it isn't that strange.

**Closed by sbatten** 2018-12-21 15:11 UTC
Labels: extensions
