### ISSUE TITLE
Allow Visual Studio Code to run on Windows 10 Mobile in Continuum mode

### ISSUE THREAD

**Issue by marknoble** [Microsoft/vscode#19239] opened 2017-01-24 17:43 UTC
- VSCode Version: Latest
- OS Version: 10.10.14393.693

Steps to Reproduce:

1. Navigate to http://code.visualstudio.com/docs/?dv=win using Windows 10 Mobile device running Edge in Continuum mode.
2. Download Visual Studio Code
3. Install Visual Studio Code
4. Currently nothing happens because the platform is unsupported.

**Comment by mousetraps** [comment] 2017-01-25 00:58
Hey, great idea! This looks like a duplicate of #10759, so please follow that issue for updates.

**Comment by tim-weis** [comment] 2017-03-03 12:12
This does not appear to be a duplicate. The proposed duplicate #10759 has been resolved (see #15820). The result of the investigation produced knowledge, that VS Code can be converted to a **Windows Store App** using Project Centennial. This does not make it available to any non-Win32 UWP platforms (like Windows 10 Mobile).

This issue should therefore be re-opened (or linked to an appropriate duplicate if one exists).

**Comment by marknoble** [comment] 2017-03-03 13:37
I'd agree with @tim-weis on this at this point, @mousetraps . While UWP conversion is generally understood to make an app available across the Windows ecosystem (potentially including HoloLens, Xbox, and Mobile - which would all be neat places to use VS Code) this request was specific to use in Continuum.  Until it works in that scenario, this issue should remain open, though the intermediate steps to get it there would involve making VS Code a UWP app and making said app available on Mobile.

**Comment by saschanaz** [comment] 2018-08-12 06:45
Windows 10 Mobile is dead (as there are no more version updates or new devices), so probably this can be closed.

**Comment by tim-weis** [comment] 2018-08-12 16:05
@saschanz: This isn't about popularity of platforms. My previous comment was meant to illustrate *your* biased opinion on what is and what isn't a dead platform. Windows 10 Mobile will receive updates for another 2 years. That's a contractual guarantee.

Continuum is a unique feature of Windows 10 Mobile. This feature request is asking to make VS Code available on Windows 10 Mobile, since that is the only mobile platform, where using a code editor does indeed make sense (providing a fullsize display, keyboard and mouse input).

You haven't made a convincing point, why this feature request should be closed, or more importantly, for what reason.

**Comment by saschanaz** [comment] 2018-08-12 23:59
>This isn't about popularity of platforms.

Actually it is, because human resource is limited and we cannot do everything we want.

**Closed** 2019-05-02 04:55 UTC
Labels: *out-of-scope, feature-request, install-update
