### ISSUE TITLE
Add Information About Themes Shown In Release Notes

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode#86464] opened 2019-12-06 10:13 UTC
It would be great if the release notes that have images showing various, not-standard/not-included includes also include a small bit of info under each image that links to, or states, the theme used in the pictures. It's nice to see all the different setups in the release notes that people have, but it's hard to try to track down some of the ones seen to use for yourself if you see something you like.

For example, in the latest 1.40.x notes, the theme here:

![](https://code.visualstudio.com/assets/updates/1_40/scm-highlight.gif)
![](https://code.visualstudio.com/assets/updates/1_40/untracked.gif)

I'd love to find that theme and check it out. I have the Insider version of VSCode as well but this theme doesn't look to be a default/included theme.

**Comment by atom0s** [comment] 2019-12-06 10:33
Managed to track down the theme, if anyone else wants it:

 * GitHub Sharp Theme
 * GitHub Plus Theme

It seems the Insider version of the release notes does include the exact thing I am requesting here, but the main VSCode release notes does not. Would be nice to include this information on the main notes as well. :)

**Comment by gjsjohnmurray** [comment] 2019-12-06 12:39
/duplicate of https://github.com/microsoft/vscode-docs/issues/3226

**Closed** 2019-12-06 12:39 UTC
Labels: *duplicate, themes
