### ISSUE TITLE
The code fold icons (minus/plus)  are not synchronous

### ISSUE THREAD

**Issue by Evoque** [Microsoft/vscode#39978] opened 2017-12-10 09:06 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393 
 
Steps to Reproduce: 
1.  open splitter screen using one file
2. switch other files arount  

Reproduces without extensions: Yes

PS: Here is the screen shot:
![splitter](https://user-images.githubusercontent.com/3809046/33803477-7c98db8a-ddcc-11e7-9d8f-3a0f3bff4ad8.png)

**Comment by aeschli** [comment] 2017-12-13 09:35
duplicate of #38527

**Closed by aeschli** 2017-12-13 09:35 UTC
Labels: editor, editor-folding
