### ISSUE TITLE
Add Command: Focus on panel action bar drop-down

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#26962] opened 2017-05-19 19:20 UTC
All OS'

For keyboard users/disabled using Tab to get to the panel action bar it's a bit of a journey.
While there are several focus or show commands including individual commands for multiple terminals,
Extensions and some other items need to be selected from the drop-down. DirectFocus
would be great and would also make it easier to get to the other action items with arrows

**Comment by Tyriar** [comment] 2017-05-19 19:34
@isidorn thoughts on a `workbench.action.focusPanelActionBar` command that would focus the first item in the action bar, be it a button or a dropdown? Can you add other relevant people to the issue?

**Comment by cleidigh** [comment] 2017-05-19 20:14
@Tyriar 
@isidorn 
I am free labor, am happy to do a PR - just want to know I'm not duplicating something if someone else  starts to work on it or the command is not acceptable to the team.

**Comment by isidorn** [comment] 2017-05-19 20:29
I am against this due to:
* An action like `focusDropdown` does not make sense as it is too specifc, while `focusActionBar` makes sense however to focus the action bar currently a user just needs to press `shift + tab`
* Adding a new command is not discoverable, IMHO users using only they keyboard for accessibility reasons are used to using the tab key for this

Due to the reasons above I am closing this issue as designed.
I will reopen it of course if there are good reasons which I am missing.

Thank you

**Closed by isidorn** 2017-05-19 20:29 UTC
Labels: debug-console, feature-request, integrated-terminal, output

**Comment by Tyriar** [comment] 2017-05-22 03:48
> while focusActionBar makes sense however to focus the action bar currently a user just needs to press shift + tab

@isidorn this is not true for the terminal, you need to hit ctrl+m (enable tab mode), shift+tab, otherwise the terminal will eat the tab. Discoverability may be an issue but this would be pretty frustrating if I could not use a mouse.

Maybe vscode-docs should have a page on optimizing VS Code for use with only a keyboard?

**Comment by isidorn** [comment] 2017-05-22 08:05
@Tyriar you are right. Then I feel this is a terminal specific issue, and not a panel issue.

I like the idea for vscode-docs.
ping @gregvanl and @chrisdias that we should push for this and have a page for VS Code used only via keyboard.

**Comment by Tyriar** [comment] 2017-05-22 17:52
> Maybe vscode-docs should have a page on optimizing VS Code for use with only a keyboard?

/cc @waderyan
