### ISSUE TITLE
Windows: Core dump in integration tests (remote)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#175563] opened 2023-02-27 18:03 UTC
From: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=204288&view=results

Crash: 
[9036c30f-5d44-49df-b417-7dd208b62480.dmp.zip](https://github.com/microsoft/vscode/files/10842733/9036c30f-5d44-49df-b417-7dd208b62480.dmp.zip)

**Comment by rzhao271** [comment] 2023-02-27 22:26
[symbolicated.log](https://github.com/microsoft/vscode/files/10844829/symbolicated.log)

Duplicate of #171655

**Closed by rzhao271** 2023-02-27 22:26 UTC
Labels: freeze-slow-crash-leak, integration-test-failure
