### ISSUE TITLE
Trying to open a folder in the extension host quits without an apparent crash

### ISSUE THREAD

**Issue by nrc** [Microsoft/vscode#23516] opened 2017-03-29 04:45 UTC
- VSCode Version: 1.10.2 (also reproduces on insiders downloaded 28-03-2017)
- OS Version: Linux, Ubuntu 15.04

Steps to Reproduce:

1. open an extension in VSCode
2. F5 to debug
3. extension host opens, if there is a project previously loaded, the extension (in this case the Rust RLS) runs fine. If there is no project loaded, this still works from the 'welcome' screen
4. Open folder > pick any folder (not necessarily one that has a project relevant to the extension, e.g., I can open a Typescript project), open it.
5. extension host instance of VSCode immediately quits.

* there is no info in the primary VSCode window's debugger, output panel, or anywhere else I can see.
* running with --verbose I get the following messages in my terminal:
```
[main 17:40:40] Lifecycle#unload() 2
[main 17:40:40] IPC#vscode:broadcast /home/ncameron/rustls_vscode vscode:extensionTerminate true
[main 17:40:40] Lifecycle#window-before-close 2
[main 17:40:40] Lifecycle#unload() 2
[main 17:40:40] IPC#vscode:broadcast /home/ncameron/rustls_vscode vscode:extensionTerminate true
[11539:0329/174040:INFO:CONSOLE(142)] "Cannot read property 'configuration' of undefined: TypeError: Cannot read property 'configuration' of undefined
    at t.onSessionEnd (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:19747)
    at t.onBroadcast (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:2434)
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26989)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30524)
    at EventEmitter.<anonymous> (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:135:25974)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)", source: file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (142)
[11539:0329/174040:WARNING:x11_util.cc(1409)] X error received: serial 12419, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_GetWindowAttributes)
[11539:0329/174040:WARNING:x11_util.cc(1409)] X error received: serial 12471, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_GetWindowAttributes)
[main 17:40:40] Lifecycle#window-before-close 2
[main 17:40:40] Lifecycle#window-close 2
[electron event]: fail to load,  OK
[11567:0329/174041:WARNING:ipc_message_attachment_set.cc(57)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
```

This is a new problem - I haven't tried this for a week or two, but the last time everything worked fine. There is nothing visually different about VSCode and nothing significant has happened to my system. The last time I reproduced I was using 2.5G of 8G ram.

I have tried:

* reinstalling VSCode
* using an insiders build of VSCode
* nuking all VSCode in my .config directory
* restarting my VM
* running VSCode with no other applications running

**Comment by nrc** [comment] 2017-03-29 04:46
Oh, and I don't have any extensions installed.

**Comment by aeschli** [comment] 2017-03-29 07:29
'onSessionEnd' is in debugService, moving to @isidorn for further investigations.

**Comment by isidorn** [comment] 2017-03-29 07:40
Probably duplicate of https://github.com/Microsoft/vscode/issues/23390

**Comment by isidorn** [comment] 2017-03-29 14:11
Yes dup of #23390 seldomly happens to me - not every time, as for the null exception it has been fixed previous week and should no longer happen.

**Closed by isidorn** 2017-03-29 14:11 UTC
Labels: bug, debug

**Comment by nrc** [comment] 2017-03-29 19:51
Great, thanks for investigating! When can I expect https://github.com/Microsoft/vscode/pull/23586 to hit the insiders distributable?

**Comment by isidorn** [comment] 2017-03-30 07:31
@nrc it is in today's insiders

**Comment by nrc** [comment] 2017-03-30 20:20
Confirmed fixed in today's insiders. Thank you!
