### ISSUE TITLE
Pasting text into the integrated pwsh removes diacritical marks

### ISSUE THREAD

**Issue by michaelts1** [microsoft/vscode#228678] opened 2024-09-15 18:16 UTC
Type: <b>Bug</b>

Steps to reproduce:
1. Open PowerShell from the integrated terminal (In my case it's PowerShell 7.4.5).
2. Paste into the integrated terminal some text with diacritical marks. For example, paste `cat Àtest.txt`.

Expected behaviour:  `cat Àtest.txt` is pasted into the terminal.
Actual behaviour: `cat Atest.txt` is pasted into the terminal, without the accent on the A.

Notes:
* This bug occurs even when running vscode with extensions disabled.
* This bug only happens with `pwsh`. I tested with the integrated CMD, the integrated WSL terminal etc. but all of them work correctly. Only when pasting to the integrated `pwsh` terminal does this bug occur.
* This bug is probably not with powershell itself - pasting `cat Àtest.txt` into a standalone `pwsh` instance (outside of vs-code) works as expected.

VS Code version: Code - Insiders 1.94.0-insider (f4746c94726e157c9b6534f1355d163ca4efcb38, 2024-09-13T05:04:25.154Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.63GB free)|
|Process Argv|C:\\Users\\Michael\\Downloads\\test|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment] 2024-12-11 20:37
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Additionally, soon we plan on shipping [conpty v2](https://github.com/microsoft/vscode/issues/224488) with VS Code which should bring our behavior in line with Windows Terminal. Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2024-12-11 20:37 UTC
Labels: bug, windows, confirmation-pending, terminal-input
