### ISSUE TITLE
Jupyter Notebook - Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by pigeonhands** [microsoft/vscode#124306] opened 2021-05-20 22:35 UTC
Issue Type: <b>Bug</b>

VSCode fails to both open and create any Jupyter Notebooks after updating. This issue happens when all extensions are disabled (with Bisect).

Steps to reproduce:
1. run `>Jupyter: Create new blank notebook `

This is the output from the log window:
```
[2021-05-21 10:23:23.804] [renderer1] [error] Can't apply edits to unknown notebook model: file:///c%3A/src/NOTEBOOKS/relay_notebook.ipynb: Error: Can't apply edits to unknown notebook model: file:///c%3A/src/NOTEBOOKS/relay_notebook.ipynb
    at Ur.$applyEdits (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2296:13227)
    at n._doInvokeHandler (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1770:11977)
    at n._invokeHandler (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1770:11661)
    at n._receiveRequest (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1770:10331)
    at n._receiveOneMessage (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1770:9117)
    at file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1770:7218
    at a.fire (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at o.fire (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16186)
    at i._receiveMessage (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21444)
    at file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18330
    at a.fire (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at u.acceptChunk (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13551)
    at file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12899
    at Socket._ (file:///C:/Users/smackenzie/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2710:116730)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) 
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.64GB free)|
|Process Argv|--crash-reporter-id e804f0fd-ccac-4451-b6c7-f332a1e291da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
go|gol|0.25.0
gc-excelviewer|Gra|3.0.41
beautify|Hoo|1.5.0
hex-fmt|ker|1.0.0
dotnet|leo|1.3.0
cortex-debug|mar|0.3.12
rust-analyzer|mat|0.2.599
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
dotnet-interactive-vscode|ms-|1.0.2256020
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-wsl|ms-|0.56.2
azure-account|ms-|0.9.8
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
vsliveshare|ms-|1.0.4272
vscode-react-native|msj|1.4.2
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.3
vscode-icons|vsc|11.4.0
change-case|wma|1.0.0
material-theme|zhu|3.10.14
vscode-proto3|zxh|0.5.4

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2021-05-20 22:41
Duplicate of #122951

**Closed by mjbvz** 2021-05-20 22:41 UTC
