### ISSUE TITLE
Switching document tab makes 'Remove Unnecessary Usings' pops up.

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/vscode#20524] opened 2017-02-13 02:58 UTC
_From @antonkudin on February 8, 2017 0:31_

- VSCode Version: Code - Insiders 1.10.0-insider (87fd1dde6d2d2b0d84c3fe56fabc174e888b0024, 2017-02-07T07:05:01.586Z)
- OS Version: Darwin x64 16.4.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharpfixformat|Leopotam|0.0.9|
|unity-tools|Tobiah|0.1.9|
|unity-snippets|YclepticStudios|0.1.2|
|csharp|ms-vscode|1.6.2|
|theme-actual-obsidian|zehfernando|2.1.0|

---

Switching document tab makes 'Remove Unnecessary Usings' pops up.

![2017-02-07 22_21_43](https://cloud.githubusercontent.com/assets/8632082/22717955/f4af5e3c-edae-11e6-8764-75585ad42c61.gif)

It also seems like having top line in a document be one of the unused 'using'-s makes it appear (it appears underlined in green). Doesn't happen if top 'using' is actually important for this document's code.

Tested it by adding unnecessary 'using' to a c# document, at the top line, and pop up started to appear when switching to that document.

Steps to Reproduce:
Click other tab, cmd+alt+direction to switch or cmd+number to create new window.

_Copied from original issue: OmniSharp/omnisharp-vscode#1203_

**Comment by DustinCampbell** [comment] 2017-02-13 02:58
Hmmm... this strikes me as issue for VS Code itself rather than C# for VS Code. After all, the C# extension just provides a CodeActionProvider, it doesn't do anything to actually show the lightbulb menu. What do you think @jrieken?

**Comment by jrieken** [comment] 2017-02-15 07:57
dupe of #20306

**Closed by jrieken** 2017-02-15 07:57 UTC
