### ISSUE TITLE
Can't push action workflow files to GitHub

### ISSUE THREAD

**Issue by Zingo21** [microsoft/vscode#190881] opened 2023-08-21 13:55 UTC
Type: <b>Bug</b>

I cannot push my workflow files to Github. When I do that, I'm greeted with an error and in the output log it says ! [remote rejected] automations -> automations (refusing to allow an OAuth App to create or update workflow `.github/workflows/workflow_file.yml` without `workflow` scope).

## Steps to Reproduce:
1. Clone a repository or make a .github/workflows folder containing an yml file
2. Make some changes to the file
3. Commit and push

An error pop-up and message will show up as soon as you push to GitHub

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 7, 7|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 32038472-23da-4d4c-ab49-4e25654c066a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
TabOut|alb|0.2.2
language-mcfunction|arc|0.18.0
markdown-mermaid|bie|1.19.0
markdown-preview-github-styles|bie|2.0.2
discord-tools|Dar|1.5.0
dart-code|Dar|3.70.0
flutter|Dar|3.70.0
vscode-github-actions|git|0.26.1
vscode-pull-request-github|Git|0.70.0
vscord|Leo|5.1.17
fluent-icons|mig|0.0.18
csdevkit|ms-|0.3.21
csharp|ms-|2.0.376
vscode-dotnet-runtime|ms-|1.7.0
vscodeintellicode-csharp|ms-|0.1.26
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.3
cpptools-extension-pack|ms-|1.3.0
datapack-language-server|SPG|3.4.16
swift-lang|ssw|1.5.0
icons|tal|3.7.0
cmake|twx|0.0.17
vscode-lldb|vad|1.9.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by lszomoru** [comment] 2023-08-21 14:50
@Zingo21, how are you authenticating against GitHub? Are you signed in with you GitHub account in VS Code? Do you have any git credential manager configured? Thanks!

**Comment by Zingo21** [comment] 2023-08-21 15:26
@lszomoru 
I'm signed in to my GitHub account in VS Code. For the git credential manager, I'm unsure if it's configured but I will look into that.

**Comment by lszomoru** [comment] 2023-08-21 17:00
Looking at the code, I can confirm that the GitHub token that is issues by the GitHub built-in extension does have the `workflow` scope - https://github.com/microsoft/vscode/blob/a29a3782af70d01cedacf77e850e451066128f7f/extensions/github/src/auth.ts#L30C64-L30C64. What happens if you try to commit from the Terminal? Are you getting the same error message?

**Comment by Zingo21** [comment] 2023-08-22 10:27
When I try to commit and push from the terminal in VS Code I get the same error message.

**Comment by lszomoru** [comment] 2023-08-22 11:15
What about using an external terminal? Are you still getting the same error? This seems to indicate that the problem is not related to VS Code, but it's related to the authentication configuration in git.

**Comment by Zingo21** [comment] 2023-08-22 22:41
I have the same problem in an external terminal and I agree now with you that it might be the authentication configuration in git that is the culprit.

**Comment by lszomoru** [comment] 2023-08-23 07:05
@Zingo21, thank you very much for the update. 
Given that the issue is not related to VS Code, I will go ahead and close it.

**Closed by lszomoru** 2023-08-23 07:05 UTC
Labels: git, github
