### ISSUE TITLE
Integrated terminal in WSL does not wrap to newline when command is long.

### ISSUE THREAD

**Issue by Waghabond** [microsoft/vscode#116029] opened 2021-02-07 13:04 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

This problem is exclusive to the cmd and bash terminals (powershell doesn't have it). It also only happens when thhe vscode window is opened in WSL using the Remote-WSL extension. The bash and cmd shells wrap lines properly if the current vscode window is not connected to WSL.

The problem is that when these conditions are met (vscode is connected to WSL and the shell being used in the integrated terminal is bash or cmd). If a command exceeds the length of the terminal window the terminal doesnt make a new line, it glitches and starts overwriting the same line from the start of the window. The command still works fine but its a visual bug.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.21301
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.81GB free)|
|Process Argv|--crash-reporter-id 8fae03f6-de6e-4b3c-a8e2-85883a1aadbd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|7.60GB (7.18GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
helium-icon-theme|hel|1.0.0
better-c-syntax|jef|1.13.0
better-cpp-syntax|jef|1.15.5
vscode-valgrind|kro|0.0.1
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
ayu|tea|0.20.1
vscode-ruby|win|0.28.0
material-theme|zhu|3.9.13
vscode-erb-beautify|ali|0.2.0
vscode-intelephense-client|bme|1.6.3
solargraph|cas|0.21.1
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
prettier-vscode|esb|5.9.1
vscode-postgresql|ms-|0.3.0
cpptools|ms-|1.2.0
ruby|reb|0.28.1
vscode-yaml|red|0.14.0
vscodeintellicode|Vis|1.2.11
vscode-ruby|win|0.28.0
txt-syntax|xsh|0.1.4
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Waghabond** [comment] 2021-02-23 02:46
is there any updates on this?

**Comment by AndreaPi** [comment] 2021-03-02 12:07
I _think_ it's the exact same bug as the one I opened https://github.com/microsoft/vscode/issues/117917 , which was just closed as a duplicate of this other one https://github.com/microsoft/vscode/issues/116174

**Comment by Waghabond** [comment] 2021-03-02 12:17
yes it does appear to be the same issue, but it has not been solved in #116174

**Comment by AndreaPi** [comment] 2021-03-02 13:04
indeed it hasn't. I was just informing you that if you're looking for updates, you'd better follow that issue.

**Comment by Waghabond** [comment] 2021-03-02 13:07
thanks a lot for the mention in the other isse

**Closed** 2021-04-24 00:20 UTC
Labels: bug, integrated-terminal, remote
