### ISSUE TITLE
openEditors.visible

### ISSUE THREAD

**Issue by 8lbiasian** [Microsoft/vscode#47906] opened 2018-04-15 12:31 UTC
Issue Type: <b>Settings Search Issue</b>

if i make the visible to be 0 its still appering !

VS Code version: Code - Insiders 1.23.0-insider (7c62e560a2e494a1b0b4d39561dc5c1d837a5263, 2018-04-13T05:17:33.810Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.4.8
python|ms-|2018.3.1
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.3.0
vscode-icons|rob|7.22.0
vscode-react-native|vsm|0.6.6

</details><details><summary>Results</summary>

Setting|Extension|Score
---|---|---
explorer.openEditors.visible|core|2.004

</details>

Query: openEditors
Literal matches: 1

**Comment by joshstevens19** [comment] 2018-04-15 13:13
https://github.com/Microsoft/vscode/issues/7755 - i think this issue was raised back in 2016. I think it was designed to behave as it is!

**Comment by isidorn** [comment] 2018-04-17 14:15
Exactly, duplicate of #7755 
Works when you open a folder.

As an alternative you can right click on the open editors section to hide it always and that is the recommendad way to do this

**Closed** 2018-04-17 14:15 UTC
Labels: *duplicate
