### ISSUE TITLE
TypeError: Cannot set property 'theme' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30748] opened 2017-07-15 05:07 UTC
Seeing this when starting up running "out of sources":

```
Cannot set property 'theme' of null: TypeError: Cannot set property 'theme' of null
    at Themable.onThemeChange (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/common/theme.js:338:24)
    at CallbackList.invoke (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:91:40)
    at WorkbenchThemeService.applyTheme (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/themes/electron-browser/workbenchThemeService.js:339:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/themes/electron-browser/workbenchThemeService.js:297:38
    at Object.notifySuccess [as _notify] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.enter (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.derive._creator._run (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.derive._creator._completed (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1036:18)
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
```

**Comment by bpasero** [comment] 2017-07-15 05:08
Actually this does only reproduce if I enable to show the release notes by commenting out this if statement here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/update/electron-browser/update.ts#L212

Still, not sure why that would trigger the exception?

**Comment by aeschli** [comment] 2017-07-17 06:41
@bpasero With 'out of sources' you mean running out of a the dev workspace?
I can't reproduce the issue. Maybe you can debug it in your workspace?

**Comment by aeschli** [comment] 2017-08-09 15:04
Closing, I can't reproduce.

**Closed by aeschli** 2017-08-09 15:04 UTC
Labels: bug

**Comment by aeschli** [comment] 2017-08-14 08:49
duplicate of #32385
