### ISSUE TITLE
Copy/Cut then Paste doesn't preserve or fix indentation #6392

### ISSUE THREAD

**Issue by micahcourey** [microsoft/vscode#47161] opened 2018-04-03 19:40 UTC
Copy/Cut then Paste doesn't preserve or fix indentation #6392

This issue was never fixed but was closed and it won't allow me to comment on it so making an issue to tell y'all to reopen it.

**Comment by shepelevstas** [comment] 2018-04-04 13:17
I've just published extension to cope with it as I also don't understand why it could not be done for more than two years. So I did it myself. The extension name is [Dumb Copy-paste](https://marketplace.visualstudio.com/items?itemName=shepelevstas.dumb-copy-paste)

**Comment by toddlucas** [comment] 2019-02-11 19:59
Here is an example of the issue with a simple, plain HTML file that was formatted by VS Code. The editor.formatOnPaste is set to the default value of false. When I paste a single 'p' element into another nesting level (the 'div'), the formatter not only indents it incorrectly, but it also messes up the indentation of the surrounding 'div', which was not part of the pasted content.

![html-paste-fail](https://user-images.githubusercontent.com/313882/52588746-06be9680-2df2-11e9-873a-652f3696b517.gif)

The only two workarounds seem to be hitting Ctrl+Z to undo the silent formatting step, as the folks in issue #6392 suggest, or to set editor.formatOnPaste to true, which, ironically, appears to stop any formatting. It seems like formatOnPaste flag does the opposite of what the boolean value would suggest. When it it is set to false, formatting is applied (which often doesn't work) and when set to true, there is no formatting.

There is a helpful button on the settings page called 'Show matching extensions', but I don't see any that apply to HTML.

**Comment by glen-84** [comment] 2019-03-23 14:55
Duplicate of #32320. (?)

**Closed** 2020-11-05 02:07 UTC
Labels: *duplicate, bug, editor-autoindent
