### ISSUE TITLE
Zen Mode Resize Cursor on Left

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#15675] opened 2016-11-17 21:32 UTC
- VSCode Version: Insiders
- OS Version: macOS

Regarding test item #15647 

![img_0902](https://cloud.githubusercontent.com/assets/11839736/20408384/156604b2-acca-11e6-81f7-82ecdd219189.JPG)

Steps to Reproduce:

1. Drag cursor to far left
2. Note the resize cursor.
3. Also, I'm not sure if this by design, but while this resize cursor is present, sometimes you can drag the Explorer viewlet out and other times you can't.

**Comment by isidorn** [comment] 2016-11-18 09:41
This is by design - it is the same behavior when you are not in zen mode and you just hide the sidebar.
Closing as it has been like that forever before the introduction of zen mode

**Closed by isidorn** 2016-11-18 09:41 UTC
