### ISSUE TITLE
Underscores not showing up in completions or rename in Linux mint

### ISSUE THREAD

**Issue by andy-ms** [microsoft/vscode#46879] opened 2018-03-28 21:04 UTC
Issue Type: <b>Bug</b>

Open an empty TypeScript file and type:
```ts
const a_b_c_d_e_f_g = 0;
a_b_c_d
```
and see completions.

![underscores](https://user-images.githubusercontent.com/19274678/38056275-ee852a82-3290-11e8-981e-0b8cd605fa0d.jpg)

VS Code version: Code - Insiders 1.22.0-insider (95b0cffe72a9d32e6ef3780dcc050a336e7b2968, 2018-03-28T15:42:46.044Z)
OS version: Linux x64 4.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|Load (avg)|2, 1, 1|
|Memory (System)|7.63GB (0.38GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by dbaeumer** [comment] 2018-03-29 06:46
Works for me with latest insider on Windows. So this is not a problem with TS in general. Will that work using a different font ?

![capture](https://user-images.githubusercontent.com/1931590/38074042-b2641e3a-332d-11e8-98a0-d439a22d3b61.png)

**Comment by dbaeumer** [comment] 2018-03-29 06:47
@joaomoreno assigning to you because of the list / tree rendering.

**Comment by andy-ms** [comment] 2018-03-29 14:49
Can confirm that this works on windows.

**Comment by joaomoreno** [comment] 2018-04-03 09:53
![image](https://user-images.githubusercontent.com/22350/38242666-a6f8d76e-3735-11e8-809f-e9b27de864e7.png)

Seems to work fine here. Can you show us your user settings?

**Comment by andy-ms** [comment] 2018-04-16 16:17
@joaomoreno This is marked "needs more info" but I don't know what more I can provide -- this only reproduces for me on linux, not on windows, so that explains why you don't see the error.

**Comment by andy-ms** [comment] 2018-04-16 18:30
> Does this happen in the latest stable version of 1.22.2?

Yes.

> Can you try a few different themes and see if this happens in all themes?

This happens in all default themes. (Abyss, Dark, Dark+, Kimbie Dark, Monokai, Monokai Dimmed, Red, Solarized Dark, Tomorrow Night Blue, High Contrast)

> Can you hit Ctrl+Space when the completions show up to open the side docs view and see of the side view has the same problem?

That fixes the problem on the right side (since it increases the height) but not on the left.
![completion](https://user-images.githubusercontent.com/19274678/38827986-710ad6aa-4169-11e8-95fb-358b2808d1af.jpg)

**Comment by andy-ms** [comment] 2018-04-24 19:41
This also happens wen renaming:
![rename](https://user-images.githubusercontent.com/19274678/39210195-d21b6028-47bc-11e8-9ccd-0449799fa2d9.jpg)
(I typed `x_y_z`)

**Comment by ramya-rao-a** [comment] 2018-04-24 19:57
Thanks for that info @andy-ms 
I still cannot repro even on an ubuntu parallel
@Tyriar Can you try and repro this?

**Comment by andy-ms** [comment] 2018-04-24 20:06
I'm running Linux Mint 18.3, installed about a month ago. Might not happen in ubuntu.

**Comment by ramya-rao-a** [comment] 2018-04-24 22:27
@bpasero Any chance this can be an electron issue?

**Comment by bpasero** [comment] 2018-04-25 05:00
@ramya-rao-a unlikely, but @andy-ms could see if this reproduces with our newer Electron builds: https://az764295.vo.msecnd.net/exploration/5e0fbe54562b6291114d1219f8bf5bbcb77af1b1/code-exploration-1.23.0-1524549314_amd64.tar.gz

**Comment by andy-ms** [comment] 2018-04-25 16:01
Doesn't work with `code-exploration` either.

**Comment by andy-ms** [comment] 2018-04-25 17:26
@bpasero Do you have a URL for that?

**Comment by bpasero** [comment] 2018-04-25 17:36
@andy-ms https://microsoft.github.io/monaco-editor/

**Comment by andy-ms** [comment] 2018-04-25 17:39
OK, the error still reproduces there.

**Comment by ramya-rao-a** [comment] 2018-06-08 01:56
@andy-ms In auto-completions, does this occur only for the item that has focus? Can you try with an example where the completion list has more than 1 item and the item without focus is also contains underscores?

cc @jrieken as he recently worked on the HighlightedLabel control that might be related.

**Comment by jrieken** [comment] 2018-06-08 06:41
> as he recently worked on the HighlightedLabel control that might be related.

Unlikely, I added a title attribute and the possibility to escape new lines. So, I'd no

**Comment by andy-ms** [comment] 2018-06-08 17:28
@ramya-rao-a With two items, underscores show correctly for the top item but are clipped for the bottom item.

![top](https://user-images.githubusercontent.com/19274678/41171768-929c20e6-6b06-11e8-8827-1af06ec641b4.jpg)

![bottom](https://user-images.githubusercontent.com/19274678/41171779-990dc394-6b06-11e8-9375-2a00036e1f2b.jpg)

**Comment by ramya-rao-a** [comment] 2018-06-08 17:44
Ok, that confirms that the issue is not related to the focused item, but is for the last item in the list.

Can you try with `a_b_c_d_a_b_c_d` and `e_f_h_e_f_h` ? This is to confirm if the issues are with specific letters or the number of letters

**Comment by andy-ms** [comment] 2018-06-08 17:50
Still missing underscores with `a_b_c_d_a_b_c_d` and `e_f_h_e_f_h`.

**Comment by jrieken** [comment] 2019-04-30 13:13
closing because no actionable information is present

**Comment by Tyriar** [comment] 2019-07-03 20:52
Looks like someone is seeing this in the rename dialog: https://github.com/microsoft/vscode/issues/35901#issuecomment-508233507

From my experience dealing with https://github.com/microsoft/vscode/issues/35901, one some Linux distros the underscore is drawn below where the expected bounds of the font is, I would expect if the container's size was increased by 2px downwards it would fix the issue, It's a bit of a weird problem though as Chromium shouldn't be letting us draw this imo (provided that the container is sized by its contents, not explicitly).

Reopening as this is definitely a bug, this will likely be reproducible with the exact distro that it repro'd on and the same settings.

**Comment by welkie** [comment] 2019-07-04 17:22
I'm the one who encountered the issue with the rename dialog. Posting here to provide more info.

For me, it affects the terminal:
![vscode-underscores-terminal](https://user-images.githubusercontent.com/7719209/60681582-d38ea980-9e5d-11e9-9360-b3885b0e0829.gif)

And the rename dialog:
![vscode-underscore-rename](https://user-images.githubusercontent.com/7719209/60681641-0e90dd00-9e5e-11e9-831d-95bcf344d0b0.gif)

But not the Intellisense/autocompletion:
![vscode-underscore-autocompletion](https://user-images.githubusercontent.com/7719209/60681739-5a438680-9e5e-11e9-8466-f0b15ffd7e5b.gif)

It also does not affect renaming files:
![vscode-underscore-renamefile](https://user-images.githubusercontent.com/7719209/60681794-8f4fd900-9e5e-11e9-927d-38301148d7d7.gif)

I'm not sure what else to test at this point, but I can test more if someone wants me to.

My system info:

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

VS Code info:

```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-20-generic
```

**Comment by brysonthor** [comment] 2019-07-18 16:41
I'm running VScode on Ubuntu 19.04 I was also having issues not seeing underscores. interestingly those issues went away when I upgraded to a 4k monitor. This may be a clue for whoever gets around to fixing this, or it could be a fluke on my machine. Cheers.

**Comment by fenchu** [comment] 2019-08-04 14:53
If I change font/fontsize it works for me on mint 19.2, must be some scaling when rendering fonts.

**Comment by Tyriar** [comment] 2019-10-09 22:38
Let's close this as we can't really action it, the underlying cause is because Chromium renders some Linux fonts shifted down a little. I'm not sure whether it's Chromium's problem, the font or the OS but it's definitely not VS Code/monaco as it would happen on other platforms then. The terminal-specific issue is still tracked in https://github.com/microsoft/vscode/issues/35901

**Closed** 2019-10-09 22:38 UTC
Labels: *out-of-scope, help wanted, linux, suggest, upstream, ux
