### ISSUE TITLE
Format selection inconsistencies

### ISSUE THREAD

**Issue by cmj91uk** [Microsoft/vscode#15459] opened 2016-11-14 12:24 UTC
- VSCode Version: 1.7.1 (2016-11-03T13:53:14.822Z)
- OS Version: Windows 10 - Version 1607

Steps to Reproduce:

1.  Within a javascript file create three lines that have incorrect indentation.
 - The first should be a code line
 - The second should be a comment line
 - The third should be another code line.
2. Highlight the top two lines and press Ctrl + K, Ctrl + F to format the selection.
Notice that the comment line isn't indented along with the code line
3. Undo the changes and highlight all three lines. Once again press Ctrl + K, Ctrl + F to format the selection
Notice that the comment line is now indented correctly.
4. Undo the changes and use Shift + Alt + F to format the document. The comment line is now indented as with (3).

It seems like if the last line of a selection is a comment it doesn't correctly pick up the indentation settings.

An example file is this one.

    d3.tsv("/test.tsv", (err, data) => {
        data.forEach(function (element) {
            console.log("test");
            //this is a comment
            console.log("Hello world");
        }, this);
    });

**Comment by waderyan** [comment] 2016-11-17 00:04
This looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11500

@mhegazy can you confirm?

**Comment by mhegazy** [comment] 2016-11-17 07:23
The commment is indented with the line that follows it. So this sounds right to me.

**Comment by waderyan** [comment] 2016-11-17 16:05
Hmm.. I agree with OP that the behavior seems strange. I did a quick check to see what other editors do. 

Atom (using Beautifier plugin) - Will indent the comment to the line above (in OP's scenario 1)
WebStorm - Will indent the comment to the line above (in OP's scenario 1)
Sublime Text (using JS Format plugin) - Will indent the comment to the line above (in OP's scenario 1)

Do we have a reason to not have the same behavior?

**Comment by waderyan** [comment] 2016-11-17 16:05
Moving to TS repo to continue discussion.

**Comment by waderyan** [comment] 2016-11-17 16:06
This issue was moved to Microsoft/TypeScript#12327

**Closed by waderyan** 2016-11-17 16:06 UTC
Labels: format, js
