### ISSUE TITLE
Hex Editor: Unclear in multi-selection that Data Inspector still showing first item not highlighted item

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#115180] opened 2021-01-27 04:29 UTC
Testing #114952

If you shift+right arrow to multi-select in the hex editor, the Data Inspector keeps the data for the first item in the selection and not the highlighted item. It is unclear in the Data Inspector view which item it is reporting on.

**Comment by lramos15** [comment] 2021-01-27 14:30
Duplicate of https://github.com/microsoft/vscode-hexeditor/issues/207

**Closed by lramos15** 2021-01-27 14:30 UTC
