### ISSUE TITLE
Vibration occurs when autocomplete items are selected.

### ISSUE THREAD

**Issue by Eronana** [Microsoft/vscode#23982] opened 2017-04-06 04:01 UTC
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quick-open-file|AlanWalk|0.1.0|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:
Please see this video: http://take.ms/J7Gka

**Comment by mjbvz** [comment] 2017-04-06 06:25
This looks like a duplicate of #23840

**Closed by mjbvz** 2017-04-06 06:25 UTC
Labels: duplicate
