### ISSUE TITLE
Some shells cannot read commands in vscode

### ISSUE THREAD

**Issue by steve02081504** [microsoft/vscode#182427] opened 2023-05-14 11:52 UTC
Does this issue occur when all extensions are disabled?: Yes

version info:
```
版本: 1.79.0-insider (system setup)
提交: 2575777b9d3cdb865d61f9f1dfaac1fea9e1bde6
日期: 2023-05-12T05:21:06.392Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
沙盒化: Yes
```

________

I'll be brief, I've written a shell to interact with a program and execute expressions for development purposes
The source code is at https://github.com/ukatech/ghost_terminal and the part of the shell that handles the logic is at https://github.com/steve02081504/my-gists/blob/115cd2173048ecc4e6e13d3b1a775ab2076bcb01/windows/shell_base.cpp
And I configured it in my workspace like this: https://github.com/Taromati2/ghost/blob/master/.vscode/settings.json

This program uses `_getwch` to read data from the input and `GetConsoleScreenBufferInfo` to find out the current position of the cursor and `SetConsoleCursorPosition` to move the cursor to redraw the command, it also uses `CreateConsoleScreenBuffer` to create a command line buffer that is not used for output and to calculate the width of a string or character
And the program worked fine in windows terminal or a traditional command line window until it under vscode, which for some reason does not accept keystrokes other than function keys such as enter and tab, which means I cannot use it in vscode.

Steps to Reproduce:
Given that this application needs to be linked to other applications, I can't provide some simple steps to reproduce it without installing and config something new
Hopefully the introduction to the principles I have provided will help find the problem.

______

我得先简明扼要的说一下，我写了一个shell用于和某个程序交互并执行表达式，便于开发
其源代码在https://github.com/ukatech/ghost_terminal ，shell逻辑处理的部分在https://github.com/steve02081504/my-gists/blob/115cd2173048ecc4e6e13d3b1a775ab2076bcb01/windows/shell_base.cpp
并且我在我的工作区中这样配置它：https://github.com/Taromati2/ghost/blob/master/.vscode/settings.json

这个程序使用`_getwch`从输入端读取数据，并通过`GetConsoleScreenBufferInfo`获知光标现在的位置、以及使用`SetConsoleCursorPosition`移动光标来实现命令的重绘，它还使用了`CreateConsoleScreenBuffer`创建一个不被用于输出的命令行缓冲区，用于计算字符串或字符的宽度
并且这个程序在windows terminal或传统命令行窗口中都工作良好，直到其遇到了vscode，不知为何它无法接受到除了回车、tab等功能按键以外的按键键入，这意味着我不能在vscode中使用它。

复现步骤：
考虑到这个程序需要和其他程序联动，我无法提供不需要安装和配置新东西的简单的复现步骤
希望我提供的原理相关介绍能帮助找到问题。

**Comment by Tyriar** [comment] 2023-05-16 11:41
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by Tyriar** 2023-05-16 11:41 UTC
