### ISSUE TITLE
VS code requires a restart after installing ftp-simple

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#17124] opened 2016-12-13 16:40 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro Version 1607 Build 14393.479

VS code requires a restart after installing ftp-simple before the startup instructions (at https://github.com/humy2833/FTP-Simple)  become applicable; the ftp-simple commands don't show up until after a restart. Don't know if this is a VS Code problem or ftp-simple problem.

VS Code version:  1.7.2
FTP-simple: 0.4.14

related: https://github.com/humy2833/FTP-Simple/issues/22

**Comment by kieferrm** [comment] 2016-12-13 18:59
Duplicate of #5675.

**Closed by kieferrm** 2016-12-13 18:59 UTC
Labels: duplicate
