### ISSUE TITLE
Notebook cell not found during render after openWith

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#113933] opened 2021-01-06 21:03 UTC
- VSCode Version: 1.53.0-insider
- OS Version: Win10

(Ported from dotnet/interactive#961)

Steps to Reproduce:

1. Download the file https://github.com/EverybodyKurts/corrupted-dotnet-interactive-notebook/blob/main/clean-code-with-ces.ipynb locally.
2. Install the [.NET Interactive notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
3. Ctrl+Shift+P to execute the command ".NET Interactive: Open notebook" and open the file downloaded in step 1.

Does this issue occur when all extensions are disabled?: N/A

The user is shown the error `Cannot read property ``rendererId`` of undefined`, but using the developer tools, it appears the issue is really coming from [here](https://github.com/microsoft/vscode/blob/d21a51c233d31e9f2b4b9485ee287ceaeb054411/src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts#L678); the index returned is outside of the bounds.

**Comment by jrieken** [comment] 2021-01-28 10:06
I have revert this change because has caused a severe regression https://github.com/microsoft/vscode/issues/115293

**Comment by rebornix** [comment] 2021-01-28 18:35
Fixed via https://github.com/microsoft/vscode/commit/3fe4b0eb2f7d80255fa93eb1fc413058788c431a

**Closed by rebornix** 2021-01-28 18:35 UTC
Labels: bug, notebook
