### ISSUE TITLE
adding a file to the current project

### ISSUE THREAD

**Issue by x7testingx7** [microsoft/vscode#116811] opened 2021-02-16 22:05 UTC
Issue Type: <b>Feature Request</b>

i would like to add a file that shows on the activity bar(left) of the vscode

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment] 2021-02-17 00:17
Maybe a duplicate of #45177

**Closed** 2021-02-17 05:29 UTC
