### ISSUE TITLE
now cpu 100%

### ISSUE THREAD

**Issue by Eightglasses** [Microsoft/vscode#38048] opened 2017-11-10 09:40 UTC
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
typings-autoinstaller|jvi|1.2.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.0
view-in-browser|qin|0.0.5
easysass|spo|0.0.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment] 2017-11-10 10:08
First don't create multiple issues. Duplicate of #38047.
Second give us a test case which we can reproduce and try to disable the extensions. 
Thanks :)

**Comment by Eightglasses** [comment] 2017-11-10 10:24
I don't know what to do about test cases
sorry:(

**Comment by maxibanki** [comment] 2017-11-10 10:29
Disable extension by extension so you can see if an extension is the cause of it. First you can try to disable all of them by launching VS Code with the `--disable-extensions` parameter.

**Comment by Eightglasses** [comment] 2017-11-10 10:38
thanks,Give you a high praise
i will test

**Comment by bpasero** [comment] 2017-11-11 11:20
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Eightglasses** [comment] 2017-11-13 02:52
hellow,
I know what the reason is
Git has more than 100 files,there are a lot of pictures. Vscode opens and loads a very hard card

**Comment by Eightglasses** [comment] 2017-11-13 03:46
@maxibanki @bpasero

**Comment by bpasero** [comment] 2017-11-13 05:45
@Eightglasses what are the exact steps that lead to the 100% CPU? Is it right on startup?

**Comment by Eightglasses** [comment] 2017-11-13 06:45
Vscode comes with git. I have too many files not submitted (more than 100). After submission, the CPU100% problem returned to normal.

**Comment by bpasero** [comment] 2017-11-13 06:48
Adding @joaomoreno

**Comment by joaomoreno** [comment] 2017-11-13 10:57
Can you use http://processhacker.sourceforge.net/ to show us the exact  Command Line of the running processes which take more CPU?

**Comment by Eightglasses** [comment] 2017-11-14 02:10
rg. exe takes up CPU especially high. 
I found a solution from Baidu:Node-moduls cnpm install --by=npm. 
It is also suggested that the rollback version be recommended. Maybe it's my cnpm problem.
I don't know how to use processhacker, sorry

**Comment by bpasero** [comment] 2017-11-14 06:50
Moving to @roblourens

**Comment by Eightglasses** [comment] 2017-11-14 09:24
CPU is normal, but the computer is always unresponsive.
 I gave up.
 I'm going to use another editor.
bye

**Comment by joaomoreno** [comment] 2017-11-14 09:35
@roblourens Please check this user's issue about `rg.exe`.

**Comment by roblourens** [comment] 2017-11-14 18:46
@Eightglasses If you are using `cnpm` and seeing high CPU, then you are probably hitting an issue with rg.exe and large numbers of symlinks. Workaround: set `"search.followSymlinks": false`. This is tracked in https://github.com/Microsoft/vscode/issues/35659

**Closed by roblourens** 2017-11-14 18:46 UTC
Labels: freeze-slow-crash, needs more info, new release, search
