### ISSUE TITLE
Alt-F-S doesn't save the current file

### ISSUE THREAD

**Issue by Fozzy0007** [Microsoft/vscode#5556] opened 2016-04-20 16:24 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. edit a file (VSCode marks it as needing to be saved)
2. Alt+F+S

file doesn't save.  in any other windows program, chording Alt+F (let go of F, keep holding Alt) + S will save the file.  

if you let go of "Alt" between F and S, it works.  my muscle memory is messing with me.

**Comment by Tyriar** [comment] 2016-04-20 17:15
This is an Electron issue https://github.com/atom/atom/issues/10732

**Comment by Treit** [comment] 2016-11-23 03:05
The discussion in issue atom/atom#10732 concludes that this is something different and _not_ the same issue as atom/atom#10732.

**Comment by Tyriar** [comment] 2016-11-28 20:04
As mentioned in the atom issue, the underlying issue is related to electron, not vscode.

**Comment by Treit** [comment] 2016-11-28 22:50
Is there an active Electron issue tracking this? I couldn't find one. I read through the issues described here (https://github.com/electron/electron/issues/2504) but none of them quite seem to match the behavior this issue is talking about, which is that a three-character combination like Alt+F+S does not do anything and you have to release the Alt key to make it work.

**Comment by Tyriar** [comment] 2016-11-29 19:40
That does look like the upstream issue as it tracks a bunch of problems with it.

**Comment by SteveALee** [comment] 2017-05-08 07:53
It's seems to be specific to ALT+F, S as other mnemonics in the file menu like A (Save AS)  P (prefs sub menu) work fine

**Comment by myfairsyer** [comment] 2017-07-24 10:47
> other mnemonics in the file menu like A (Save AS) P (prefs sub menu) work fine
Not for me.

**Comment by WereDev** [comment] 2017-07-28 19:19
I am having a similar issue.  In fact, none of the Alt+ key combinations work for opening a menu.  For instance, Alt+F should open the file menu, but it does nothing on my machine.  I have no idea why this is an issue as it works in my other applications.

Win10, VSC 1.14.2

**Comment by JackTrapper** [comment] 2017-11-14 18:02
> As mentioned in the atom issue, the underlying issue is related to electron, not vscode.

It may be *because* of electron; but vscode is the one that decided to *use* electron.

If electron is the problem, and it's unsolvable, then its try to move to a different UI framework - one based on native controls.

**Comment by jasenf** [comment] 2017-11-16 21:25
I swear this was working. 

It's always been my preferred way of saving files.  But now, in the FIle menu, save Workspace has taken over the "S" spot for a shortcut key.  Maybe if we could just change the shortcut keys around?

**Comment by WereDev** [comment] 2017-11-17 00:20
@JackTrapper @jasenf 

This was updated in another ticket, thought it was here too.  The problem was Scroll Lock.  When it's enabled, the Alt key menu stuff doesn't work right.  Everything is fine when it's disabled.  Not sure if you're experiencing the same thing or if you've come across something different.

**Comment by jasenf** [comment] 2017-11-17 00:39
I think my issue is new.  The Alt-F then S sequence is now taken by Save Workspace.  Pretty sure until a recent release the S was to save a file.

**Comment by JackTrapper** [comment] 2017-11-21 01:59
It's something different. 

- Press `Alt`
- Press `F`
- Release `F`
- Press `S`
- Release `S` *(no save)*
- Release `Alt`

The problem is that people don't read the **Steps to Reproduce**, and just scroll through; thinking they get the gist.

**Comment by bpasero** [comment] 2018-07-05 14:36
We should support this with the new custom menu implementation.

**Comment by sbatten** [comment] 2018-07-05 20:16
related #52935

**Comment by bpasero** [comment] 2018-08-17 05:29
Duplicate of https://github.com/Microsoft/vscode/issues/52935

**Closed by bpasero** 2018-08-17 05:29 UTC
Labels: accessibility, electron, upstream, workbench-menu
