### ISSUE TITLE
allow ⌘-` as "quick switch window" keybinding

### ISSUE THREAD

**Issue by boneskull** [microsoft/vscode#77013] opened 2019-07-09 19:02 UTC
This is a macOS-only concern.

I run VSCode exclusively in native fullscreen mode.  _By default_ macOS' system-level "shortcut" for "Move focus to next window" is bound to ⌘-`:

![image](https://user-images.githubusercontent.com/924465/60914950-7751ce00-a23f-11e9-8852-8799a2719b0a.png)

"Move focus to next window" _does nothing_ when apps run in native fullscreen.  When focused on a fullscreen window, macOS will _not_ switch between "spaces" to access a different window (fullscreen or not) from the same app.  Each native fullscreen window is considered its own "space."

However, VSCode's "quick switch window" keybinding (`workbench.action.quickSwitchWindow`) does just that; it will switch between these native fullscreen windows.  But binding it to ⌘-` is disallowed by VSCode's "keyboard shortcuts"  GUI.  Hand-editing the JSON is possible--but it doesn't actually create the binding.

I am not sure if there's a technical reason for this, or just a "recommendation" from Apple that apps don't allow binding to the shortcut.  I _do_ know that in JetBrains' IDEs, ⌘-` works akin to "quick switch window" with multiple native fullscreen windows, so there either a) isn't an OS-level embargo on using the shortcut, or b) JetBrains found some way to trick macOS into switching across spaces.

If a VSCode window is _not_ run in native fullscreen, and a user uses ⌘-` to switch windows, I would expect that VSCode would either a) override macOS' system-level shortcut, or b) delegate to it.  I don't know what's preferred, as long as VSCode exhibits the behavior expected by the user.

Please let me know if this is an Electron-specific issue; if so, please close this.

**Comment by shutterfreak** [comment] 2020-03-17 09:06
I think many apps on macOS have difficulty when using **Cmd-\`** in full-screen context. For MS Office apps for instance, typing the **Cmd-\`** chord when in full-screen will switch to the first window **on the first screen**.

However, I seem to remember that there was a time when **Cmd-\`** was correctly switching between open windows (not in full-screen though) and that after a VSCode update the chord stopped working.

I see the following possibilities:
1. The key binding library misses the chord and just parses the backtick (or it has been instructed not to process that particular chord in the current context)
1/ The **Cmd-\`** chord may contain a hidden **Compose** modifier
1. The backtick could be mapped to different glyphs in different keyboard layouts (e.g. grave accent on French and Dutch keyboards), which effectively hides the chord to the application when in non-US-ASCII mode due to "if modifier unexpected, assume no modifier" behaviour.

For instance, in Safari on macOS you also can't switch to the next window with **Cmd-\`** if a text control is currently active (e.g., the username control is active). Instead, a backtick glyph is displayed and it behaves as a regular backtick (awaiting if it can be composed with te following glyph).

**Comment by alexdima** [comment] 2021-10-19 12:45
@deepak1556 Is there any way to investigate if a keybinding reaches Electron, but Electron decides to "swallow it" vs. a keybinding that never reaches Electron because the OS "swallows it"?

**Comment by bpasero** [comment] 2022-02-01 07:03
Ping.

**Comment by natewaddoups** [comment] 2022-02-08 02:23
Hoisting up the text of the aforementioned duplicate bug, for more visibility. As a recent Windows -> Mac migrant, Mac's busted cmd-tab feature is a persistent thorn in my side, and VS Code's missing hotkey just aggravates the pain.

--

Command-Backtick is a standard shortcut for cycling through an application's windows on Mac.

It is desperately needed in VS Code on Mac because the Mac "equivalent" to alt-tab is broken. And has been for years, so there is no hope of a system-level fix to that problem.

On Windows, if you have two VS Code windows running, you can use alt-tab to switch to the one you want. On Mac, you'll only have on VS Code icon in the cmd-Tab UI, and you never really know which one is going to come to the front when you release the cmd-Tab keys. So you often need another hotkey to cycle within an application's windows. Cmd-backtick is that hotkey.

If you've never used Mac you might not understand. As someone who used Windows for years and recently switched to Mac (due to a new job) I assure you that cmd-backtick is NOT OPTIONAL, because cmd-tab alone is not sufficient. It only does half of what alt-tab does; cmd-backtick does the other half.

**Comment by alexdima** [comment] 2022-02-16 14:16
Here are some observations from my latest tests (ANSI keyboard / U.S. keyboard layout):
* when having two VS Code windows, using <kbd>⌘</kbd>-<kbd>`</kbd> correctly switches between the two windows
* when having two VS Code windows, and entering fullscreen with one of them (the green button), <kbd>⌘</kbd>-<kbd>`</kbd> does not switch between the windows anymore.

I have tested Safari and it behaves 100% like VS Code. @bpasero could you please also try out Safari? Perhaps <kbd>⌘</kbd>-<kbd>`</kbd> not having an effect when in fullscreen is a macOS wide behavior and not one specific to us?

**Comment by bpasero** [comment] 2022-02-16 16:14
@alexdima yes I can confirm that a fullscreen window on macOS refuses to run the `Cmd+Backtick` for switching windows. 

I think the ask here is whether we could allow for the `Cmd+Backtick` window as a configurable keybinding in VSCode. This seems hard to achieve given the keybinding is reserved globally in macOS. I do not think the keybinding is magically unbound once a window is in fullscreen mode, so it probably is always delegated to the OS.

However, once I uncheck this default keybinding in the settings, I can actually assign `Cmd+Backtick` within VSCode.

![image](https://user-images.githubusercontent.com/900690/154308012-ab5fa311-21b4-48e5-a250-323d03a13310.png)

I do not think we can do this automatically though, at least I am not aware of an Electron API to do so.

**Comment by natewaddoups** [comment] 2022-02-18 19:41
Zoom will cycle through windows using cmd-` even if one of those windows is maximized. 
Chrome and Edge however do not.

And this thread taught me that VSCode does honor cmd-` **_if_** the foreground window is not maximized.

So I agree that this is probably a Mac problem rather than a VS Code problem.

I detest Mac UX a little bit more with each passing day. :) Who thought it would be a good idea to have maximized windows break hotkey navigation? Am I holding it wrong?

**Comment by deepak1556** [comment] 2022-12-12 15:14
>  Is there any way to investigate if a keybinding reaches Electron, but Electron decides to "swallow it" vs. a keybinding that never reaches Electron because the OS "swallows it"?

@alexdima nope, we will have add some trace logs in the relevant code path of runtime.

Closing as issue is not addressable in the runtime.

**Closed by deepak1556** 2022-12-12 15:14 UTC
Labels: upstream, keybindings, macos
