### ISSUE TITLE
Incorrect notebook error rendering on non Chromium browsers

### ISSUE THREAD

**Issue by msujew** [microsoft/vscode#227678] opened 2024-09-05 10:36 UTC
Type: <b>Bug</b>

#### Steps to Reproduce:

1. Open VS Code on a non-Chromium browser (FireFox/Safari), using the server version of VS Code.
2. Open a python (or any other) notebook and add a cell with a syntax error.
3. Execute the cell.
4. The cell output contains erroneously rendered error results:

![image](https://github.com/user-attachments/assets/63230e8d-3d02-4008-a403-f3b5c33d5692)

*(screenshot taken on FireFox)*

#### Expected result:

The output should look just like in the desktop version of VS Code. It does so when opening the server URL on Chrome:

![image](https://github.com/user-attachments/assets/7b9dd8ad-695e-4f42-89d5-bdd0a8849cef)

*(screenshot taken on Chrome, same application as the screenshot above)*

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (13.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by amunger** [comment] 2024-11-23 00:06
duplicate of https://github.com/microsoft/vscode/issues/206111

**Closed by amunger** 2024-11-23 00:06 UTC
Labels: notebook-output
