### ISSUE TITLE
Problems after last update (1.5.2) with less files and autocompiler

### ISSUE THREAD

**Issue by rockandthemes** [Microsoft/vscode#12023] opened 2016-09-14 14:06 UTC
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. One less file with more than 2000 lines
2. CTRL+S to save and autocompile... vscode hangs
3. Need to kill the process and restart vscode

**Comment by aeschli** [comment] 2016-09-15 07:31
@rockandthemes What do you mean my auto-compile? Do you have a watch process in the background?

**Comment by rockandthemes** [comment] 2016-09-15 12:03
I have Easy LESS v1.2.5 extension running in VSCode, but I think is not a issue with this extension, because VSCode also hangs when saving a LESS file without the extension.

**Comment by aeschli** [comment] 2017-02-07 16:18
Closing as I'm not able to reproduce. Please speak up if you still see this with all extension disabled.

**Closed by aeschli** 2017-02-07 16:18 UTC
Labels: freeze-slow-crash
