### ISSUE TITLE
Snippet variable `$LINE_COMMENT` is incorrect when inside JSX

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#102403] opened 2020-07-13 16:30 UTC
- VSCode Version: latest
- OS Version: macOS latest

Steps to Reproduce:

1. Create a snippet with config
   ```json
   {
     "TODO": {
       "prefix": "todo",
       "body": "$LINE_COMMENT TODO: "
     }
   }
   ```
2. Inside JSX, run the snippet (place cursor after `todo`, open suggestions, then execute)
   ```jsx
   <div>
       todo
       hello, world!
   </div>
   ```

Actual:

```jsx
<div>
    // TODO: 
    hello, world!
</div>
```

Expected:

```jsx
<div>
    {/* TODO */}
    hello, world!
</div>
```

This is how the "add line comment" works, so I would expect the snippet variable to behave similarly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment] 2020-07-14 04:09
In a `.jsx` file:

![jsx line comment](https://user-images.githubusercontent.com/31813701/87382811-1006e200-c555-11ea-9b7a-aa62ea74176a.gif)

Sorry for the huge gif.  As you can see it works as you expected for me.  Are you doing anything differently than what I did?

**Comment by jrieken** [comment] 2020-07-14 07:59
@OliverJAsh Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by OliverJAsh** [comment] 2020-07-14 08:48
@ArturoDent @jrieken Sorry I got my expected/actual mixed up. I've updated the original issue description now to correct this, essentially by swapping expected/actual.

**Comment by jrieken** [comment] 2020-07-14 08:57
Can you run "F1 > Inspect Editor Tokens and Scopes" at the insert position and check what language is selected at the position? This usually depends on the grammar and is sometimes wrong

**Comment by OliverJAsh** [comment] 2020-07-14 09:07
![image](https://user-images.githubusercontent.com/921609/87407287-dddb9b80-c5b9-11ea-9448-2706ba861aee.png)

**Comment by jrieken** [comment] 2020-07-14 09:16
Roger. The problem is that the comments variables are resolved against the document language, not against the language at the current position. 

<img width="1150" alt="Screenshot 2020-07-14 at 11 15 51" src="https://user-images.githubusercontent.com/1794099/87408171-63177e00-c5c3-11ea-9435-72532fafb00b.png">

**Comment by jrieken** [comment] 2020-07-14 09:26
I have pushed a change that makes sure we resolve variables against the language at the current position. However, the snippet you have shared won't work because the jsx-tags language doesn't define a line comment token

**Comment by OliverJAsh** [comment] 2020-07-14 09:31
> the jsx-tags language doesn't define a line comment token

Is this something which needs fixing separately?

I'm surprised it doesn't work because if I run the "add line comment" command at the same position, it does use the correct syntax. I would have thought the snippet would use the same mechanism as this command.

**Comment by jrieken** [comment] 2020-07-14 09:39
> Is this something which needs fixing separately?

Yeah, that's a separate issue. Assuming line comment token exists in that language. 

> . I would have thought the snippet would use the same mechanism as this command.

I doesn't because it has much less context as snippet variables are resolved in-place

**Closed** 2020-07-14 09:40 UTC
Labels: bug, snippets

**Comment by OliverJAsh** [comment] 2020-07-14 09:44
> Yeah, that's a separate issue. Assuming line comment token exists in that language.

Should I file another bug?

**Comment by OliverJAsh** [comment] 2020-07-14 23:14
I thought about filing another bug but the description would be identical to the one I posted here. Can we just re-open this until the expected behaviour is achieved?

**Comment by OliverJAsh** [comment] 2020-07-15 15:45
https://github.com/microsoft/vscode/issues/102609
