### ISSUE TITLE
Debug action icon does not reflect the current session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#40090] opened 2017-12-12 11:42 UTC
Create some concurrent debug sessions:
- start a "launch" debug session
- start a "attach" debug session

Observe: terminate action shows "plug" icon (for attached state)

- switch to "launch" debug session

Observe: terminate action still shows "plug" icon

- press "plug" icon terminates the "launch" session.

(I saw this with my Cluster prototype)

**Comment by isidorn** [comment] 2017-12-12 11:47
The issue here is that the actions update on the focused process update. However in this case the process can not be focused since it has no stack frame. This is basically a duplicate of https://github.com/Microsoft/vscode/issues/18426

**Closed by isidorn** 2017-12-12 11:47 UTC
Labels: bug, debug
