### ISSUE TITLE
VS Code Intellisense breaks on big projects

### ISSUE THREAD

**Issue by VladimirMikulic** [microsoft/vscode#103800] opened 2020-08-02 21:55 UTC
- VSCode Version: 1.47.3
- OS Version: Kubuntu 20.04

Steps to Reproduce:

1. Open a project and use module bundler to generate the build (JS)
2. Congrats, no more IntelliSense.

Joke aside, the problem is when I build the project it generates a bundle.js file and VS Code IntelliSense suddenly breaks. I guess it's because it is indexing the newly created bundle file, but it shouldn't.

![Screenshot_20200802_234808](https://user-images.githubusercontent.com/35997844/89133384-abb7bc80-d51b-11ea-9d67-68fbf474d8a5.png)

Infinite loading...

How can I resolve this?

Does this issue occur when all extensions are disabled?: Yes/No
No, but default IntelliSense is not that great with extensions disabled.

Thank you.

**Comment by mjbvz** [comment] 2020-08-03 20:27
Closing as caused by extension per issue notes.

Please try tracking down which extension causes this and file an issue against them

**Comment by VladimirMikulic** [comment] 2020-08-05 22:43
Hi @mjbvz.
The extension that is causing the issue is actually the built-in one - TypeScript and JavaScript Language Features.

**Comment by mjbvz** [comment] 2020-08-05 22:53
So you still see this issue when all non built-in extensions are disabled?

**Comment by VladimirMikulic** [comment] 2020-08-05 22:58
Unfortunately, yes I do. It doesn't occur on small bundle sizes < ~200kb but everything above that becomes an issue.

**Comment by mjbvz** [comment] 2020-08-05 23:00
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) too? Can you share an example project that demonstrates the issue?

**Comment by VladimirMikulic** [comment] 2020-08-06 09:19
It does.

![Screenshot_20200806_110234](https://user-images.githubusercontent.com/35997844/89513259-a0db8100-d7d4-11ea-9252-a2e64dad0734.png)
 
I have an example dummy project for you [here](https://filebin.net/1ejte42wi842tr56) that reproduces the issue.
**Steps**:
1) `npm i` -> install dependencies
2) Open a few files in `dist` for a few seconds (scroll a bit trough them)
3) After opening a few heavy files in `dist` open `test.js` and try to get autocomplete (sometimes the whole autocomplete breaks and sometimes the autocomplete breaks only for specific dependencies -> like that Parcel object in `test.js`)

Thanks.

**Comment by mjbvz** [comment] 2020-08-06 21:22
Thanks but I can't reproduce this this using that project. Which specific files are you opening?

**Comment by VladimirMikulic** [comment] 2020-08-06 21:27
@mjbvz please try opening `dist/index0200.js`. It is the largest one (~500Kb).
If you still can't reproduce it then my guess is that your machine is more powerful than mine so indexing large files don't represent the issue to it.

**Comment by mjbvz** [comment] 2020-08-06 21:41
Hmm, that could be the case. However it's pretty instant for me, even when I tested the project in a Ubuntu dev container:

![Aug-06-2020 14-38-39](https://user-images.githubusercontent.com/12821956/89585401-a3e56a00-d7f2-11ea-9b36-a478effd2eb1.gif)

Are you on very low power hardware?

It may also help if you could collect the TS Server log. This would include information about how long each operation takes:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share the log from the example project, I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by VladimirMikulic** [comment] 2020-08-06 22:22
Hi @mjbvz.
Actually, I might have identified why this occurs.
The machine is mid-ranger (i7 2.2GHz - 4.3GHz, 8GB RAM, Nvidia 1050, Kubuntu 20.04)

Earlier this year I identified Linux abusing my CPU at system startup so I disabled optional turbo.
After enabling it and opening the VS Code again, the issue doesn't occur anymore.

Maybe it is time to finally switch to Mac!

**Closed** 2020-08-06 22:22 UTC
Labels: *caused-by-extension

**Comment by VladimirMikulic** [comment] 2020-08-06 22:24
Closing this, since this is not directly the problem of VS Code.
Thanks a bunch for your help!
