### ISSUE TITLE
Importing @types/lodash by QuickFix does not let the error go away

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37345] opened 2017-10-31 21:30 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37181

Steps to Reproduce:

1. Just testing #37181.
2. I have to reload the window to make it disappear, reloading the TS project does not help.

**Comment by chrmarti** [comment] 2017-10-31 21:30
![import-error](https://user-images.githubusercontent.com/9205389/32249995-1504088a-be48-11e7-803b-c21e2aaa6168.gif)

**Comment by mjbvz** [comment] 2017-10-31 21:50
Does it actually install the typings into node_modules them if you refresh the view?

**Comment by chrmarti** [comment] 2017-10-31 22:40
Yes, these were installed.

**Comment by mjbvz** [comment] 2017-10-31 22:53
Duplicate of #37345

**Closed by mjbvz** 2017-10-31 22:53 UTC
Labels: typescript
