### ISSUE TITLE
Commands fired through the debug welcome view don't activate the extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#92125] opened 2020-03-05 23:54 UTC
https://github.com/microsoft/vscode-js-debug/issues/346

js-debug has `onCommand:extension.pwa-node-debug.createDebuggerTerminal` in its activationEvents. However, which firing that command from a welcome view button, nothing happens and an error is logged in the console. If I run that command from the command palette, it works.

![](https://memes.peet.io/img/20-03-1d096607-7001-4fae-b9f3-a4fb0079b894.png)

This should be reproducible in upcoming js-debug nightly.

\+ with this it would be nice to show a busy state on the debug view while the extension is activating to give feedback to the user, since it can take a moment or two the first time around 🙂

**Comment by isidorn** [comment] 2020-03-06 17:14
Ok, looked a bit into this, and the issue is [here](https://github.com/microsoft/vscode/blame/ef26b31ab9a8863acd3c3ae281d096aa2d919a09/src/vs/editor/browser/services/openerService.ts#L32)
Basically the opener service comlpains that the command is not known.
I believe the `openerService` should first try to activate extensions that relly on that command like the `commandService` does. Or should not throw since there is a chance like here that the `commandService` will actually activate the extension.

If I remove the throwing it just works.
Though let's also assign to @jrieken to get his feedback on what is the best way to fix this

**Comment by jrieken** [comment] 2020-03-09 08:48
@isidorn Thanks for the looking into this. Removing the check in the opener sound like the right fix - the command service will do the right thing and will also bail out in case the command doesn't exist (after all activation and such)

**Comment by isidorn** [comment] 2020-03-09 08:53
@jrieken thanks. I will remove the check.

**Closed** 2020-03-09 08:54 UTC
Labels: bug, debug
