### ISSUE TITLE
Primary sidebar always opens on app open

### ISSUE THREAD

**Issue by reidma** [microsoft/vscode#231729] opened 2024-10-19 14:34 UTC
Type: <b>Bug</b>

Starting a few weeks ago, the Primary Sidebar now always opens when I open VS Code. This is despite toggling it off in the View > Appearance menu prior to closing the app. It always happens when I open the app. It happens even after disabling all extensions.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500 (20 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (23.10GB free)|
|Process Argv|--crash-reporter-id c6b5618b-b43c-4f5b-a7bf-a6e8a783b319|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tab-jumper|Chr|1.0.5
wordcount|ms-|0.1.0
command-server|pok|0.10.1
cursorless|pok|0.29.1288
parse-tree|pok|0.31.3
talon|pok|0.2.0
vscode-fileutils|sle|3.10.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilotcf:31161678
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-19 19:53
/duplicate of https://github.com/microsoft/vscode/issues/230575

**Closed** 2024-10-19 19:54 UTC
Labels: *duplicate
