### ISSUE TITLE
On exit with modified file, "don't save" and "cancel" actions are swapped

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#1398] opened 2015-12-17 03:00 UTC
I see this in 0.10.4.  If I press `Cancel` the app exits (the don't save case).  If I press `Don't Save` the dialog closes but VSCode stays running (the cancel case).

**Comment by gregvanl** [comment] 2015-12-17 06:22
Duplicate of #1330 which has been fixed.

**Closed by gregvanl** 2015-12-17 06:22 UTC
