### ISSUE TITLE
Explore to update to Electron 2.0.x

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#45542] opened 2018-03-12 05:39 UTC
Hey!

We are in the process of updating VSCode’s Electron version to a new major release (from 1.7.x to 2.0.x). For that reason we would like to get some testers onto this version, which we currently not plan to distribute via insiders but as a separate install that can be run side-by-side with other installs. This install is separate with regards to everything (settings, keybindings, extensions), so it will not touch any of your existing configuration.

**Best way of testing** is to just use this build for daily development and look out for suspicious things happening 👍 . Visually there should be no difference to stable or insiders (except for the orange icon 🔶).

**Builds**
* Windows x64: [Download](https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCodeSetup-x64-1.24.0-exploration.exe)
* Windows ia32: [Download](https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCodeSetup-ia32-1.24.0-exploration.exe)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCode-darwin-exploration.zip)
* Linux (deb): [Download](https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/code-exploration_1.24.0-1526535091_amd64.deb)
* Linux (rpm): [Download](https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/code-exploration-1.24.0-1526535241.el7.x86_64.rpm)

Feel free to file issues as you see them, thanks 👍

**Comment by bpasero** [comment] 2018-03-13 16:10
I created a side-by-side install (with orange icon :large_orange_diamond:!) so that we do not tamper with `stable` or `insiders` data. It even supports auto-updates (except for Linux) as we push more changes to our adoption branch. These bits are from last week friday and should be as stable as our insider releases:
Windows x64: https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/VSCodeSetup-x64-1.22.0-exploration.exe
Windows ia32: https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/VSCodeSetup-ia32-1.22.0-exploration.exe
macOS: https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/VSCode-darwin-exploration.zip
Linux (deb): https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/code-exploration_1.22.0-1520951054_amd64.deb
Linux (rpm): https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/code-exploration-1.22.0-1520951202.el7.x86_64.rpm

**Comment by l0k1verloren** [comment] 2018-03-13 16:15
How do I test this thing? I just upgraded to Nvidia 390.42 and this seems to have fixed my X crash issue but I'm keen to help test out this branch. Is there a tag or branch to check out to get these builds? I run Arch so debs and rpms are not relevant to my system.

**Comment by smlombardi** [comment] 2018-03-13 17:10
What's the main difference(s), to look out for?

**Comment by smlombardi** [comment] 2018-03-13 17:12
Works for me, so far, with all my favorite extensions, themes, and user settings. 

Where would I copy over snippets etc. from Insiders to this one?

**Comment by bpasero** [comment] 2018-03-13 17:20
@l0k1verloren this build is from branch https://github.com/Microsoft/vscode/tree/tyriar/electron-2.0.x. Best way to test it is to use it for daily development and report back if you encounter any issues 👍 

@smlombardi visually nothing should change really. On Linux, since GTK3 is now used (over GTK2) some file dialogs and menus will likely look different.

You will have to manually copy settings and keybindings over to this build as nothing is shared. Just open the files in one instance and copy the contents over to the other.

**Comment by l0k1verloren** [comment] 2018-03-14 05:38
I switched to the tyriar/electron-2.0.x branch and built and ran it and it seemed normal (exceept nice gtk3 file dialog) but then when it opened a folder nothing rendered and the menus didn't respond.

**Comment by bpasero** [comment] 2018-03-14 05:41
@l0k1verloren on what Linux distribution are you? can you show a screenshot or video what you see?

**Comment by l0k1verloren** [comment] 2018-03-14 06:19
`uname -a` Linux monolith 4.15.9-1-ck #1 SMP PREEMPT Tue Mar 13 11:27:38 EET 2018 x86_64 GNU/Linux
Antergos Linux (Arch), fully up to date as at right now.

Initial startup:

![image](https://user-images.githubusercontent.com/20619963/37386247-474f06b0-2760-11e8-95fd-c02f28f91470.png)

After opening a (golang) repository folder:

![image](https://user-images.githubusercontent.com/20619963/37386283-60ba1ae0-2760-11e8-9344-a1917be0ceb0.png)

**Comment by bpasero** [comment] 2018-03-14 06:25
+ @Tyriar on this GTK2 vs GTK3 issue if you have any ideas.

@l0k1verloren and this works fine with VS Code stable? Do you see any output in the developer console (Help > Toggle Developer Tools > Console) when you bring up the dialog?

**Comment by K900** [comment] 2018-03-14 11:13
Something is off with the menu bar colors for me - it's white on light grey with the Breeze GTK3 theme.

**Comment by bpasero** [comment] 2018-03-14 12:01
@K900 this Electron update comes with a change of GTK2 to GTK3, so I am expecting visual changes in native menus and file dialogs. Can you share a screenshot? Does it look different from other application menus?

**Comment by K900** [comment] 2018-03-14 13:40
![image](https://user-images.githubusercontent.com/386765/37405659-437fe720-27a6-11e8-809b-a3492a8748e2.png)

It's not an issue in, say, gtk3-demo:

![image](https://user-images.githubusercontent.com/386765/37405715-6c079b8e-27a6-11e8-9435-22209b1495ec.png)

**Comment by bpasero** [comment] 2018-03-14 13:56
@K900 can you confirm that you are not seeing this with Code stable?

**Comment by K900** [comment] 2018-03-14 14:12
Everything is fine on stable (GTK2), yeah.

![image](https://user-images.githubusercontent.com/386765/37407515-e253d326-27aa-11e8-863a-8e6fedba0ed8.png)

**Comment by bpasero** [comment] 2018-03-14 14:36
@K900 have you seen this issue with other applications on your machine?

**Comment by bpasero** [comment] 2018-03-14 14:37
@l0k1verloren do you have Chrome installed? I wonder if you could try the file dialog there to see if it fails too (File > Open File).

**Comment by K900** [comment] 2018-03-14 14:40
Chrome doesn't have a menu bar, does it? Firefox does have a menu bar, but it uses the Firefox theme colors. All the GTK3 demo apps use the correct colors.

**Comment by bpasero** [comment] 2018-03-14 15:13
@K900 yeah good point, how does the context menu in VSCode look like, is it also using bad colors?

**Comment by K900** [comment] 2018-03-14 15:14
The context menu is fine, it's just the menu bar that's using the wrong font color.

**Comment by bpasero** [comment] 2018-03-14 17:34
@K900 does it also reproduce if you are not using any special theme?

**Comment by bjornharrtell** [comment] 2018-03-14 19:51
Happy to report it (2018-03-13T14:22:28) seems to work very nicely on Debian testing with Adwaita Dark themed GTK3 and it's nice to see the old GTK2 parts gone. The only minor cosmetic thing I noticed is that the editor background color is dark greyish on lines with text and a few more after file end but then turns black. The same applies to the line number pane. Looking forward to this major update of this excellent editor.

**Comment by K900** [comment] 2018-03-14 19:59
@bpasero what do you mean by "special" theme? Just default Adwaita?

**Comment by bpasero** [comment] 2018-03-15 05:39
@K900 I thought "Breeze GTK3 theme" was a special theme you enabled

@bjornharrtell can you show me a screenshot of that?

**Comment by K900** [comment] 2018-03-15 05:41
Breeze is just a GTK theme like any other, it's styled to look like the default KDE Breeze style for Qt. I can try it with the default GTK3 theme that GNOME uses.

**Comment by bpasero** [comment] 2018-03-15 05:50
@K900 yes please. any hints how I can install that theme into Ubuntu 17 or 16?

**Comment by K900** [comment] 2018-03-15 05:54
You should be able to just `apt install breeze-gtk` IIRC, though it's been a while since I last used Ubuntu on a desktop. I'll test with some other themes later and see what I can find.

**Comment by bpasero** [comment] 2018-03-15 09:45
@K900 what Linux distribution are you on?

**Comment by K900** [comment] 2018-03-15 09:49
Arch testing, everything up to date. Also, it does look correct (dark background, light text) with the default GTK3 theme, so it might be a Breeze bug.

**Comment by MaleDong** [comment] 2018-03-15 11:29
@basarat ：Nice to accept the beta version!

Well……I wanna know more about this (NOT ONLY listed below):

1) Are you willing to upgrade Nodejs to version 8.9.X? Or have you got a similar plan to publish a new version of re-writing Electron with the big changed version of Nodejs (example: When the specific version of Nodejs isn't maintained, that's the time maybe you will consider upgrade VSC)?

2) Any other new plans of new features/big changes?

**Comment by bpasero** [comment] 2018-03-16 06:07
@MaleDong this update (Electron 2.0.x) is coming with node.js `8.9.3`. As for other plans you can always check our [Roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap).

**Comment by HendrikThePendric** [comment] 2018-03-16 10:03
Looking forward to this update making it into the insiders / stable build because it fixes the font rendering issues I have been facing on Linux (I'm using Ubuntu 18.04). The text is much crisper and I no longer see  blue lines between the characters (see screenshots).

I haven't really used this version for doing any work, but the menus look fine.

**Exploration version:**
![exploration](https://user-images.githubusercontent.com/353236/37514699-f010c06e-2908-11e8-8ea3-6e497387ed1c.png)
**Insiders version:**
![insiders](https://user-images.githubusercontent.com/353236/37514837-4586e3a2-2909-11e8-840a-7f7fa7cacf9a.png)

**Comment by bjornharrtell** [comment] 2018-03-16 10:26
@HendrikThePendric the font rendering issue can be traced back to https://bugs.chromium.org/p/skia/issues/detail?id=6663 and I think it has been fixed on electron 1.7.x series so that issue should hopefully go away before vscode migrates to electron 2.x.

**Comment by bpasero** [comment] 2018-03-16 10:29
@HendrikThePendric @bjornharrtell yes this will come in through the Electron 1.7.12 update that I just [merged](https://github.com/Microsoft/vscode/commit/14aa73c448e94c8af8f0bfbd97ed888e6d039213).

**Comment by HendrikThePendric** [comment] 2018-03-19 19:54
@bpasero I saw insiders is now running on electron 1.7.12. It looks a lot better indeed. Fonts are sharp but colors are still a bit flat. In this electron 2.0 branch the colors are looking much better:
**Insiders on electron 1..7.12**
![after_update](https://user-images.githubusercontent.com/353236/37618706-67defe70-2bb7-11e8-83c5-759b486dbead.png)
**Exploration version**
![exploration](https://user-images.githubusercontent.com/353236/37618757-8ba60592-2bb7-11e8-808a-1d12cf581c80.png)

**Comment by bpasero** [comment] 2018-03-20 05:49
@HendrikThePendric interesting, I was not aware of any color changes in fonts to be honest.

**Comment by arshubham** [comment] 2018-03-21 05:47
Looking forward to full gtk3 support. Much better integration with the system. Why trying this build I noticed an issue with spacing in dialog boxes. 
![screenshot from 2018-03-21 11 04 12](https://user-images.githubusercontent.com/14235191/37695846-50bc95d0-2cf8-11e8-8b4d-7492f64695ef.png)
I feel the buttons are too large. And Primary and secondary text should be aligned. And maybe use suggested Icon style for Restart button. 
Here is an example following elementary HIG (Gnome also follows a similar approach) 
![image](https://user-images.githubusercontent.com/14235191/37695893-b9c77ea0-2cf8-11e8-87c7-c92a7e026137.png)

Finally one more thing I would like to see is csd support. 

OS Info: 
elementaryOS 0.4 Loki 
(Default theme)

**Comment by bpasero** [comment] 2018-03-21 06:15
@arshubham thanks for the feedback. the dialogs are not under VSCode control though and I suggest you report this over at Electron repository so that we get attention from there: https://github.com/atom/electron

**Comment by bpasero** [comment] 2018-03-21 14:54
@K900 @l0k1verloren can you retry the issues you saw with our new drop: https://az764295.vo.msecnd.net/exploration/51470c58bd748e1689ba3d82811fe3df9efa72d4/code-exploration-1.22.0-1521641787_amd64.tar.gz

**Comment by K900** [comment] 2018-03-21 15:13
The toolbar coloring issue seems to be fixed for me. Thanks!

**Comment by l0k1verloren** [comment] 2018-03-22 03:00
![image](https://user-images.githubusercontent.com/20619963/37748648-509c2436-2d8d-11e8-94d8-478fedbc0b6f.png)

I love the gtk3! :) Though oddly the file/folder open doesn't allow me to create sidebar shortcuts. I think there might be more than a few issues you guys wanna raise with the electrum 2 repo.

I should also just add that my issues with crashing electron apps was completely solved by rolling back my arch distro to the current packages as at december 31. I suspect nvidia but it could also be the kernel causing the X crash issue. Nvidia is the prime suspect for me now, after just fixing a friend's son's gaming machine that had started completely bombing out and restarting during GPU accelerated apps - probably the linux kernel handles the driver fault more gracefully only dropping me back to lightdm but I'm not upgrading my nvidia driver for quite some time now as a result. The issue is very serious and it was distracting me terribly from doing my work.

**Comment by bpasero** [comment] 2018-03-24 06:51
Closing, thanks for feedback (still keep it coming if any). We plan to merge this work early in next months sprint.

**Comment by bpasero** [comment] 2018-04-07 09:07
Reopening as this continues for April via https://github.com/Microsoft/vscode/pull/47289. The exploration builds are running again with Electron `2.0.0-beta.7`.

**Comment by jens1o** [comment] 2018-04-07 10:52
@bpasero Can we expect performance improvements?

**Comment by farid-fari** [comment] 2018-04-08 17:46
The build download links are dead, any new ones?

**Comment by bpasero** [comment] 2018-04-09 05:05
@farid-fari I fixed the links, please try again

**Comment by cra0zy** [comment] 2018-04-18 19:58
Integrated terminal is bugged a bit, the more text it has the slower it gets, To repro it just type in `help` and try to use it, it becomes very unresponsive. (This was tested on Fedora 27 x64)

**Comment by cra0zy** [comment] 2018-04-19 08:17
> @cra0zy and you are not seeing this in Code stable?

Not seeing it in stable.

**Comment by bpasero** [comment] 2018-04-19 08:28
This seems to be the Linux manifestation of https://github.com/electron/electron/issues/12042 then.

**Comment by cra0zy** [comment] 2018-04-19 08:54
Tested on another Linux device and the same thing occurs there, so its a global Linux x64 problem it seems.

**Comment by bpasero** [comment] 2018-04-19 09:05
@cra0zy any difference if you run "`code --disable-gpu`" from the command line?

**Comment by cra0zy** [comment] 2018-04-19 09:11
None.

**Comment by Geobert** [comment] 2018-04-21 21:10
Is Electron 2.0 supposed to bring capabilities of theming on menu bar and context menu in order to have them dark when using dark theme? If yes, it's not working:
![image](https://user-images.githubusercontent.com/72570/39088813-bcc96aca-45b0-11e8-87c8-a333d2fde1a5.png)

**Comment by bpasero** [comment] 2018-04-22 14:27
@Geobert no

**Comment by l0k1verloren** [comment] 2018-04-22 14:32
@Geobert the effect relating to dark themes is for a system running a GTK+3 theme, not for Windows. On windows Electron uses the windows file and other dialogs and windows menus. On Linux this issue of mixed theming is because of the main GUI running GTK+3 but Electron using GTK+2 and is a common issue. There is ways to override the GTK+2 theme with dark but it does not flip on the 'dark theme' toggle, which only affects GTK+3

**Comment by Geobert** [comment] 2018-04-22 14:35
Thanks for the explanation!

**Comment by tushar-singh** [comment] 2018-05-17 22:09
This will fix the High sierra native tabs issue. https://github.com/electron/electron/issues/10657#issuecomment-382007214

**Comment by christianvoigt** [comment] 2018-05-18 11:35
Hi, could you please update the exploration builds so that they are based on the April release? I would like to use the exploration version to develop an extension with a webview and a dependency that requires node 8. Currently the webview api is missing from these builds and node 8 is missing from the stable release.

**Comment by bpasero** [comment] 2018-05-18 14:08
@christianvoigt the exploration build is really up to date. It should get updated automatically. What OS are you on?

**Comment by christianvoigt** [comment] 2018-05-18 14:34
ah ok. That's strange. Because if I run the webview-sample I get "Running the contributed command: 'catCoding:start' failed." And the Output Log (Extension Host) shows the following error: 

`[error] TypeError: vscode.window.createWebviewPanel is not a function`

Running the webview-sample in my normal VS Code installation works fine. I am on OSX.

**Comment by bpasero** [comment] 2018-05-18 15:37
@christianvoigt this is the link to the latest exploration build on macOS: https://az764295.vo.msecnd.net/exploration/163e64ca7bbd0a69c727cfd9f5610e7546207a71/VSCode-darwin-exploration.zip

**Comment by christianvoigt** [comment] 2018-05-18 15:53
Thank you! With the latest build it is working. So I for some reason the automatic update did not work I guess.

**Comment by johnelm** [comment] 2018-05-29 19:15
I downloaded this exploration build and took it for a spin.  Specifically, I wanted to check out the native tabs on High Sierra.  The Native Tabs functionality is not fixed, even with Electron 2 in the build*.

I tested the contributed [phoenixgao](https://github.com/Microsoft/vscode/issues/35361#issuecomment-365923941) build some time ago and it worked.  @bpasero I'm recalling some comments over there - is the key here that the Electron package must be built on a High Sierra machine?  If so, how can this ever be fixed properly?

High Sierra 10.13.2 (17C88)
Version 1.24.0-exploration (1.24.0-exploration)

*  (not exactly the same as before either, now the native 'Add New Tab' plus sign doesn't show on the far right of the bogus full-width tab).

**Comment by bpasero** [comment] 2018-05-30 04:42
@johnelm Electron did NOT fix this issue properly. As soon as a new macOS version is released, the issue will show up again. I would suggest to join me in blaming the "fix" here: https://github.com/electron/electron/issues/10657#issuecomment-382054649

**Comment by bpasero** [comment] 2018-06-08 16:33
Merged to master.

**Comment by bpasero** [comment] 2018-06-25 07:34
Reverted this change again, too many bugs...

**Comment by LiPengfei19820619** [comment] 2018-06-25 14:20
@bpasero In my opinion, Would you please think about update to Electron 3.x directly?
Electron 3.0.x is now in beta , I think there is no need to take time to adopt 2.0.x.
Thanks.

**Comment by Tyriar** [comment] 2018-06-25 14:30
@LiPengfei19820619 we're looking at that as well, it's probably a little naive to assume there won't be just as many issues adopting it too though.

**Comment by LiPengfei19820619** [comment] 2018-06-25 15:48
@Tyriar Yes, I Know. I don't think it would be an easy work. I appreciate all your job, 
As I have been using VS Code for a long time, and I wish VS Code would be  better and better.

**Comment by jens1o** [comment] 2018-07-06 13:22
@bpasero @Tyriar  So how do you want to handle this issue differently than the approach of the last iteration?

**Comment by Tyriar** [comment] 2018-07-25 18:21
Merged into master, the latest Insiders is on 2.0.5 https://github.com/Microsoft/vscode/pull/54873

**Closed** 2018-07-25 18:22 UTC
Labels: plan-item
