### ISSUE TITLE
Ctrl+Shift+E enters the letter e instead of opening the sidebar Explorer

### ISSUE THREAD

**Issue by karln-create** [microsoft/vscode#99508] opened 2020-06-06 04:36 UTC
Linux Mint 19.3, Visual Studio Code 1.45.1

Issuse: When pressing the shortcut combo Ctrl+Shift+E, instead of opening File Explorer from the sidebar (which can still be activated with Ctrl+B), the program enters as input the letter e highlighted.

Strangely the shortcut combo does function like normal when CAPLOCKS is activated.

---
CPUs | AMD Ryzen 5 2600X Six-Core Processor (12 x 3204)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 0, 0, 0
Memory (System) | 15.64GB (8.00GB free)
Process Argv | --no-sandbox --unity-launch
Screen Reader | no
VM | 0%
---
path-intellisense | chr | 2.2.0
-- | -- | --
c-cpp-compile-run | dan | 1.0.11
gitlens | eam | 10.2.1
vscode-gnu-global | jay | 0.3.3
cmake-tools | ms- | 1.4.0
cpptools | ms- | 0.28.2
material-icon-theme | PKi | 4.1.0
cmake | twx | 0.0.17
vscodeintellicode | Vis | 1.2.7

**Comment by connor4312** [comment] 2020-06-08 15:23
Can you please look through this section of our keybinding troubleshooting guide and let us know? Thanks! https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-generic-keybindings

/needsMoreInfo

**Comment by wstucco** [comment] 2020-06-18 09:38
I have the same problem, I recently switched to Gnome from KDE5 Plasma, I can't say if the two things are related.

I attached the output of Inspect key mappings and a small video of what happens
![Screencast 2020-06-18 11:34:04](https://user-images.githubusercontent.com/2199894/85004642-15d8f580-b158-11ea-9588-b7faf44d4867.gif)

[key_mappings.txt](https://github.com/microsoft/vscode/files/4797711/key_mappings.txt)

**Comment by connor4312** [comment] 2020-06-18 15:21
Does setting `"keyboard.dispatch": "keyCode"` in your user settings fix the issue?

**Comment by wstucco** [comment] 2020-06-19 09:59
@connor4312 I tried, but unfortunately it doesn't.

**Comment by koden-km** [comment] 2020-07-21 11:34
This just started happening to me since the recent VS Code update. I think it was the June update which I got about a week ago. I'm on Ubuntu 18.04.4 LTS.

VS Code - Help -> About:
```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T00:13:57.513Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-62-generic snap
```

I tried the suggested `"keyboard.dispatch": "keyCode"` and it didn't help.

I also tried the key shortcut with CAPSLOCK activated and that makes it work like normal.

**Comment by alexdima** [comment] 2020-07-21 12:17
@koden-km 
What does VS Code detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by koden-km** [comment] 2020-07-21 12:41
It says "unknown" when I press `e`. I went through every key with `Ctrl+Shift+<...>` and it seems to also say "unknown" for `Ctr+Shift+u`. Every other `Ctrl+Shift+<...>` key combo said what the key was.

![Screenshot from 2020-07-21 22-35-26](https://user-images.githubusercontent.com/1037307/88056060-47077400-cba3-11ea-9838-2906a118f15a.png)

**Comment by wstucco** [comment] 2020-07-21 12:55
@alexdima 

in my case it detect CTRL+SHIFT but as soon as I press the `e` it changes to "chord to"

![image](https://user-images.githubusercontent.com/2199894/88057318-3387e900-cb62-11ea-93e2-12575d07fd9d.png)

**Comment by alexdima** [comment] 2020-07-21 13:12
See https://developer.gnome.org/gtk3/stable/GtkIMContextSimple.html
  ![image](https://user-images.githubusercontent.com/5047891/88058816-4a2f3f80-cb64-11ea-81a5-c6befbcb006c.png)

See https://github.com/microsoft/vscode/issues/56473#issuecomment-413790018
  ![image](https://user-images.githubusercontent.com/5047891/88058868-5b784c00-cb64-11ea-9c0e-fb48f77aa802.png)

The workaround is https://github.com/microsoft/vscode/issues/72642#issuecomment-485951777
  ![image](https://user-images.githubusercontent.com/5047891/88059056-98dcd980-cb64-11ea-8d8e-f57a794760b4.png)


This appears to be a duplicate of:
https://github.com/microsoft/vscode/issues/48480
https://github.com/microsoft/vscode/issues/56473
https://github.com/microsoft/vscode/issues/70277
https://github.com/microsoft/vscode/issues/72947
https://github.com/microsoft/vscode/issues/72642
https://github.com/microsoft/vscode/issues/102571

**Closed by alexdima** 2020-07-21 13:12 UTC
Labels: keybindings, linux, needs more info
