### ISSUE TITLE
Can't debug VSCode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110304] opened 2020-11-10 10:54 UTC
![image](https://user-images.githubusercontent.com/22350/98665088-7bb65b80-234b-11eb-8013-20b461929bec.png)

**Comment by isidorn** [comment] 2020-11-10 11:01
Seems to reproduce only when being connected to remote.
Tryting to repro with containers on my machine...

**Comment by isidorn** [comment] 2020-11-10 11:05
I can repro the following issue locally (which is probably the same issue):
If the launch.json is created after vscode is started the debug view gets stuck in welcome -> investigating...

**Comment by isidorn** [comment] 2020-11-10 11:22
I believe I have pushed a fix for this.
I will 100% be sure a bit later since I can not run containers out of source - pinged Christof for help.

I have triggered a build with this fix
@joaomoreno let me know if you would like me to release it, or you can wait for tomorrow

**Closed** 2020-11-10 11:21 UTC
Labels: bug, debug, important

**Comment by isidorn** [comment] 2020-11-10 14:48
I have verified that this indeed fixes the issue with running containers out of source.
