### ISSUE TITLE
Code Blocks in Markdown Preview Don't Sync with Theme

### ISSUE THREAD

**Issue by 1chooo** [microsoft/vscode#214732] opened 2024-06-09 16:06 UTC
Does this issue occur when all extensions are disabled?: Yes (But without extensions we cannot find this issue)

- VS Code Version: 1.90.0 (Universal)
- OS Version: Darwin x64 23.4.0

Steps to Reproduce:

1. Select the [GitHub Theme] as the Color Theme
2. Open `*.md` and paste the code in the below:

    ```c
    int n;

    buffer = n;             // each can hold one item
    semaphore mutex = 1;
    semaphore empty = n;
    semaphore full = 0;
    ```
3. It happened, the code blocks in Markdown preview don't sync with GitHub Theme

[GitHub Theme]: https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme

In the Markdown Preview, no matter how I change the Color Theme in VSCode, the code blocks in the Markdown Preview do not reflect the selected theme. I have tried various themes, including GitHub and Nord, but the preview colors remain in the default scheme. 

Could you please advise on how to make the code blocks in Markdown Preview sync with the chosen Color Theme? This would greatly improve the experience of writing Markdown, as currently, I have two different syntax color schemes on my screen.

Screenshots:

![Screenshot 2024-06-09 at 10 28 44 PM](https://github.com/microsoft/vscode/assets/94162591/5fe81c43-4b34-4ae2-ba35-ff8fcd02e6b7)

related: #174090

Thanks a lot !!!

**Comment by mjbvz** [comment] 2024-07-03 23:19
Duplicate of #91279 (from already linked issue)

**Closed by mjbvz** 2024-07-03 23:19 UTC
