### ISSUE TITLE
Visual glitches (squares) on Terminal with Zoom < 100%

### ISSUE THREAD

**Issue by MurzNN** [microsoft/vscode#119751] opened 2021-03-24 07:02 UTC
Issue Type: <b>Bug</b>

VS Code have too large interface font size by default, so I use it with Zoom < 100% (at 80%).
And after last couple of updates (from version 1.51 maybe or earlier) the Terminal starts to show the visual gliches, here is screenshot:
![image](https://user-images.githubusercontent.com/336662/112268491-1c1c7500-8c88-11eb-9dab-c1548a26143e.png)

If I change terminal window size, or touch the Zoom (in or out) - they are immediately disappearing, but shows again after some later interactions. With Zoom = 100% this issue is not reproducible.

Clearing terminal via `clear` or `reset` commands didn't help.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-45-generic
Remote OS version: Linux x64 4.15.0-20-generic
Remote OS version: Linux x64 5.4.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4360 CPU @ 3.70GHz (4 x 3691)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.54GB (0.43GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id bc4064db-5144-4d00-b73a-13a771c022a6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: brick-k|
|OS|Linux x64 4.15.0-20-generic|
|CPUs|Intel Xeon E5 (Sandy Bridge) (12 x 2399)|
|Memory (System)|23.54GB (0.88GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dgd|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (2 x 2095)|
|Memory (System)|7.78GB (0.75GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
quasar-snippets|abd|1.0.0
systemd-unit-file|coo|1.0.6
drupal-8-snippets|dss|0.0.2
vscode-firefox-debug|fir|2.9.2
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
dotenv|mik|1.0.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
jinjahtml|sam|0.16.0
svg-preview|Sim|2.8.3
rewrap|stk|1.14.0
twig|wha|1.0.2
vscode-intelephense-client|bme|1.6.3
vscode-mysql-client2|cwe|3.6.0
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
php-debug|fel|1.14.11
gitlab-workflow|Git|3.15.0
escape-quotes|mil|1.10.0
language-gettext|mro|0.2.0
vetur|oct|0.33.1
indent-rainbow|ode|7.5.0
vscode-gitweblinks|red|2.4.0
change-case|wma|1.0.0
php-sniffer|won|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by meganrogge** [comment] 2021-03-29 16:50
Duplicate of #106981

**Closed** 2021-03-29 16:51 UTC
Labels: *duplicate, bug, integrated-terminal
