### ISSUE TITLE
Mac a11y: VO+Shift+M for context menu no longer works

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode#116083] opened 2021-02-08 07:39 UTC
Issue Type: <b>Bug</b>

1. Turn on VoiceOver, focus the Explorer sidebar and select a file.
2. Press CTRL+Option+Shift+M.

Expected: Context menu opens.
Actual: Nothing happens.

This worked in the 1.53 release, got broken very recently in Insider builds, Friday or so. Other side bars like source control management are also affected.

VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:23:20.010Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 4ea43554-4a6d-4f7c-b2fb-6de1a3610d98|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.9.1
vscode-pull-request-github|Git|0.23.0
beautify|Hoo|1.5.0
jstl|jsx|1.0.4
flutter-intl|loc|1.13.0
vscode-docker|ms-|1.9.1
vscode-edge-devtools|ms-|1.1.3
python|ms-|2021.2.529263813-dev
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
debugger-for-edge|msj|1.0.15
nunjucks|ron|0.3.0
vscode-webhint|web|1.5.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by MarcoZehe** [comment] 2021-02-08 07:41
CC @isidorn

**Comment by gjsjohnmurray** [comment] 2021-02-08 08:30
@joaomoreno is it possible that the change you made recently instead of my PR #112168 could have caused this?

**Comment by isidorn** [comment] 2021-02-08 10:59
@marcozehe are you sure the shortcut was `CTRL+Option+Shift+M`, since it also does not seem to work for me in the current stable? 
@joaomoreno sounds like this is coming from the tree thus also assigning to you

**Comment by MarcoZehe** [comment] 2021-02-08 11:15
Yes, the VoiceOver shortcut to open the context menu is CTRL+Option+Shift+M. Or if you have changed the VoiceOver modifier to be the CapsLock key instead, it's CapsLock+Shift+M. At least that's the *default* assignment for the OpenShortcutsMenu action in VoiceOver. And it definitely still worked late last week since I frequently used the menu to choose "Stage changes" from the SCM panel on some changed files before committing. So the regression is fairly recent, and it worked when Insiders were still 1.53.

**Comment by isidorn** [comment] 2021-02-08 13:05
@MarcoZehe thanks, I can reproduce the issue. I was not aware it is VoiceOver specific (I thought we have a VS Code shortcut for that)

**Comment by joaomoreno** [comment] 2021-02-09 10:44
@isidorn Can you check on your macOS machine whether https://github.com/microsoft/vscode/commit/73c5b484f340039de733343f6e6de811cb9fd6d8 broke it?

**Comment by joaomoreno** [comment] 2021-02-09 10:44
@MarcoZehe Does <kbd>Shift+F10</kbd> still work?

**Comment by isidorn** [comment] 2021-02-09 10:51
@joaomroeno yes shift+f10 still works
Yes, that commit broke it. If I revert it all works fine

**Comment by gjsjohnmurray** [comment] 2021-02-09 11:11
@joaomoreno maybe my original PR https://github.com/microsoft/vscode/pull/112168 for that issue solves it without causing this breakage?

**Closed** 2021-02-25 15:22 UTC
Labels: accessibility, bug

**Comment by isidorn** [comment] 2021-02-26 08:17
Works nicely in latest insiders adding verified label
