### ISSUE TITLE
Show which extension has produced an error/warning

### ISSUE THREAD

**Issue by curusarn** [microsoft/vscode#90908] opened 2020-02-18 18:36 UTC
There seems to be no way to find out which extension is producing warnings/errors in the "problems" panel. To find out which extension is producing a certain problem user has to disable extensions one by one until the problem disappears.

It would be useful to have each problem labeled with the name of an extension that produced it.

**Comment by usernamehw** [comment] 2020-05-13 06:47
Possible duplicate of #96837

**Closed** 2020-05-13 11:21 UTC
Labels: *duplicate, error-list
