### ISSUE TITLE
Image preview zooming issue

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#43388] opened 2018-02-10 15:35 UTC
- VSCode Version: 1.21.0-ins
- OS Version: win7x64

When you try to zoom an image, using "Ctrl + Mouse Wheel scrolling"....

scrolling it up (outwards) - will make an image zoomed out...
scrolling it down (to you) - will make an image zoomed in..

How come?
Why do we need this inversion?

**Comment by mjbvz** [comment] 2018-02-12 20:52
Duplicate of #43138

**Closed by mjbvz** 2018-02-12 20:52 UTC
Labels: editor, editor-core
