### ISSUE TITLE
command Replace in files is gone

### ISSUE THREAD

**Issue by spearmootz** [microsoft/vscode#166134] opened 2022-11-11 18:55 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: Ventura 13.0.1

Steps to Reproduce:

1. cmd + shift + p
2. type "replace"
3. no replace in files command is found

**Comment by ArturoDent** [comment] 2022-11-13 00:30
Was there ever such a command?  `Search: Find in Files` is there.

**Comment by spearmootz** [comment] 2022-11-13 00:32
@ArturoDent that's exactly the one I'm talking about. I looked it up in 3 computers and only found the command in the one I update vscode the least. I'm going to see if it's any plugin I have.

I recall using it very recently and the only thing I remember adding or updating was vscode itself

**Comment by ArturoDent** [comment] 2022-11-13 00:36
`Search: Find in Files` is in the Command Palette of both Stable v1.73.1 and Insiders v1.74 for me.

**Comment by spearmootz** [comment] 2022-11-13 00:38
@ArturoDent ok, thanks for verifying. I am going to validate, report my findings and close the ticket when I get home

**Comment by spearmootz** [comment] 2022-11-14 15:54
@ArturoDent the command i was looking for is a different one.  it is like "Search: Replace in files" and what it used to do is switch to the search tab and automatically open the replace box like the following screenshot.

the pc that had the command automatically updated, i was going to show the screenshot but it was too late :(. the command was no longer there

![Screenshot 2022-11-14 at 10 53 13 AM](https://user-images.githubusercontent.com/19737290/201705061-8f1237e4-d3c6-475f-ad3f-ad7a5a0356bb.png)

**Comment by spearmootz** [comment] 2022-11-14 15:57
@ArturoDent it was this one. found it in another laptop i no longer used. i disabled wifi to prevent auto updating.

![WhatsApp Image 2022-11-14 at 10 56 13 AM](https://user-images.githubusercontent.com/19737290/201705886-eb7fe6a6-f109-431a-bc54-0b86d2319689.jpeg)

**Comment by andreamah** [comment] 2022-11-15 16:30
@spearmootz what version is the `Search: Replace in Files` still visible?

**Comment by spearmootz** [comment] 2022-11-15 16:42
@andreamah I saw it in the latest version as of two weeks ago.  I got the screenshot from 1.71.2

**Comment by andreamah** [comment] 2022-11-15 17:55
Caused by a regression in https://github.com/microsoft/vscode/pull/162778, will fix after https://github.com/microsoft/vscode/pull/165538 is merged

**Closed** 2022-11-17 18:56 UTC
Labels: bug, search

**Comment by spearmootz** [comment] 2022-12-08 16:44
this was released in 1.74.0
