### ISSUE TITLE
Navigation does not work

### ISSUE THREAD

**Issue by alexpermyakov** [Microsoft/vscode#71810] opened 2019-04-05 16:06 UTC
Issue Type: Bug

Update the VSCode to the latest version.
Try to use CMD + click to navigation to the function definition.
Nothing happens, it stays on the same line.

VS Code version: Code 1.33.0 (0dd516d, 2019-04-04T15:14:28.026Z)
OS version: MacOS Mojave (10.14.3)

No Extensions.

**Comment by mjbvz** [comment] 2019-04-05 19:02
What language are you using?

/needsMoreInfo

**Comment by alexpermyakov** [comment] 2019-04-05 19:35
@mjbvz TypeScript (+React). Looks like, if I wait long enough it will finally open the file, but it takes like 10+ seconds.

**Comment by mjbvz** [comment] 2019-04-05 22:41
Duplicate of #71751

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

@alexpermyakov If that doesn't solve the issue for you, please let me know

**Closed by mjbvz** 2019-04-05 22:41 UTC
Labels: new release
