### ISSUE TITLE
extension to collapse and expand code

### ISSUE THREAD

**Issue by gabrielmaximo** [Microsoft/vscode#43570] opened 2018-02-13 10:03 UTC
- VSCode Version: 1.20.0
- OS Version: Windows 10  x64

Hi Guys, I need a help with the famous collapse and expand VS code, I would like to know if someone knows an extension that improves this tool, because by default it is very bad, I researched the marketplace but I did not find an extension that would help me in this. As the image shows, is an ugly and disorganized pattern that ends up generating line pollution.

![im1](https://user-images.githubusercontent.com/36315328/36144096-259a12d6-1094-11e8-8df3-75d04e147788.png)
![im2](https://user-images.githubusercontent.com/36315328/36144097-25cab314-1094-11e8-8f48-7a2e02f0e004.png)

**Comment by aeschli** [comment] 2018-02-13 11:51
The folding controls are not customizable by extensions.
Can you explain what you don't like about the current controls?

**Comment by aeschli** [comment] 2018-02-13 11:52
Is it a duplicate of https://github.com/Microsoft/vscode/issues/3352 ?

**Comment by gabrielmaximo** [comment] 2018-02-13 18:36
I do not like how the organization gets, it gets ugly, it skips from the standards of other text editors, as shown in the image, there's an extra "" line, and this takes unnecessary lines by minimizing the scope.

**Comment by aeschli** [comment] 2018-02-14 08:46
marking as duplicate of #3352

**Closed by aeschli** 2018-02-14 08:46 UTC
