### ISSUE TITLE
Grey boxes appearing where code and cursor aren't present

### ISSUE THREAD

**Issue by TidyLuke** [microsoft/vscode#95675] opened 2020-04-20 08:36 UTC
- VSCode Version: 1.44.2
- OS Version: Windows_NT x64 10.0.18362

Every file I open which has text in it is surrounded by large grey boxes. These boxes appear to the right of the editor and below. If I place my cursor into a section the grey box will be removed from a portion. To make this clearer, I've uploaded a screen recording for you to view: https://streamable.com/i3pvk8 

The strange thing is, this only happens on one monitor. Both monitors are of a very similar quality. Here are two screenshots.

Monitor 1: https://imgur.com/awhSbKD
Monitor 2: https://imgur.com/Vl2Wca8

Another strange issue with monitor 2 is that VS seems to have a "dull" filter over the application (and only this application), all colours are much duller than appear on monitor 1 (if anything the difference most applications see are colours being brighter on monitor 2). If I screenshot monitor 2 and view the screenshot in photoshop (still on monitor 2), the colours appear as expected.

**Comment by TidyLuke** [comment] 2020-04-20 08:53
Fixed. This was fixed by going to 'Windows Settings -> System -> Windows HD Colour settings -> Play HDR games and apps'. Turn off 'Play HDR games and apps'.

Both the "dull" filter and the grey boxes have now gone.

**Comment by deepak1556** [comment] 2020-04-20 15:37
Thanks for the details, this is duplicate of https://github.com/microsoft/vscode/issues/88491. You can use the workaround mentioned in https://github.com/microsoft/vscode/issues/88491#issuecomment-600288632 scoped to the vscode application rather than turning off hdr.

**Closed by deepak1556** 2020-04-20 15:37 UTC
Labels: new release
