### ISSUE TITLE
[folding] in scss fails for a while loop having multiple lines

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#46736] opened 2018-03-27 17:58 UTC
Testing #46535

Folding fails below
```
$i: 6;
@while $i > 0 {
  .item-#{$i} { width: 2em * $i; }
  $i: $i - 2;
}
```

Folding is fine below
```
$i: 6;
@while $i > 0 {
  $i: $i - 2;
}
```

```
$i: 6;
@while $i > 0 {
  .item-#{$i} { width: 2em * $i; }
}
```

**Comment by aeschli** [comment] 2018-03-28 21:03
The problem is caused by the interpolation. Duplicate of #46738

**Closed by aeschli** 2018-03-28 21:03 UTC
Labels: bug, css-less-sass, editor-folding
