### ISSUE TITLE
[Feature] Action to copy branch name

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#198772] opened 2023-11-21 13:58 UTC
I think I would find it useful to have an action to copy the branch name, because I often want to do that in order to switch back to the branch from the command line later on

**Comment by lszomoru** [comment] 2023-12-14 16:08
Closing as duplicate of https://github.com/microsoft/vscode/issues/148069

**Closed by lszomoru** 2023-12-14 16:08 UTC
Labels: feature-request, git
