### ISSUE TITLE
Hang, requiring restart

### ISSUE THREAD

**Issue by lgreenlee** [Microsoft/vscode#10850] opened 2016-08-23 16:55 UTC
Version 1.4.0
Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
Date 2016-08-04T16:49:32.489Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Linux ubuntu 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Start VSCode
2. Code for a while ( 30 - 90 minutes )
3. The UI will freeze and vs code will need to be restarted. Only affects the current editor window, so if there is more than one project open the one not in use is not affected.

I wish I could provide more helpful feedback, but there is no consistent cause for this.

**Comment by sandy081** [comment] 2016-08-24 07:18
@lgreenlee Very sorry to hear that VS Code is crashing. In order to know the root cause for it would you let us know

- What kind of project are you are coding. How big is it?
- Is it a Git repository
- Do you have a special setup?

When this happens would you be able to run a CPU profile from the developer tools (help > toggle developer tools) to see where we spend so much time?

Also, did this not happen with the previous release?

And finally, since this might be related to an extension, does it reproduce when you run with extensions disabled (code --disable-extensions from the command line)?

**Comment by lgreenlee** [comment] 2016-08-29 11:52
@sandy081 Hello! Thanks for getting back to me. The project is relatively small less than 50 classes, it is a C# project. It is in a private git repo, I will be unable to share it as it is company confidential. I have nothing that would be considered "special". I have a handful of extensions and I tried disabling all of the extensions (except the c# extension, which I need) however, this action did not seem to alleviate the problem. I did not see the hang behavior with the last release. I will try profiling today and see what I find.

**Comment by lgreenlee** [comment] 2016-08-29 13:31
I am having some difficulty collecting the CPU profile. The UI remains partially responsive, resizing works however the panels in the UI do not refresh. After this happens the ability to stop and save the profile goes away. I will keep trying.

**Comment by dbaeumer** [comment] 2016-08-30 09:37
@lgreenlee do you see any unusual CPU activity. If so could you provide the process that consumes most of the CPU.

**Comment by lgreenlee** [comment] 2016-08-30 16:46
Yes, can I send you a screen shot of my processes?

**Comment by dbaeumer** [comment] 2016-08-31 07:44
@Igreenlee most useful is the command line of the process with high CPU activity.

**Comment by bpasero** [comment] 2016-09-10 07:15
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-09-10 07:15 UTC
Labels: freeze-slow-crash, needs more info

**Comment by lgreenlee** [comment] 2017-03-08 15:42
An update: I resolved this issue by turning off 3D Acceleration in my VM. It appear that VM Ware's acceleration was causing the problem. This is not great the VM uses a lot more CPU but that's better than crashing all the time! Thank you!
