### ISSUE TITLE
Add config to use old brackets/quotes overtyping

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#78833] opened 2019-08-09 21:04 UTC
#37315

It's a breaking change. And very noticeable at that.

**Comment by alexandrudima** [comment] 2019-08-12 09:11
@usernamehw I've changed the editor to overtype only quotes and parens auto-inserted by the editor. Would you like to have the old behaviour of overtyping even characters that were not auto-inserted or have you maybe run into a special case in HTML/css/etc.?

**Comment by usernamehw** [comment] 2019-08-12 09:17
No special cases. Old behavior.

**Comment by haymez** [comment] 2019-08-12 17:20
Obviously a lot of people requested the new behavior but I would agree with @usernamehw in that the new behavior is quite jarring and I'm a little surprised that the default behavior changed instead of a setting being added to support the new behavior for those that wanted to switch. Having the editor _sometimes_ swallow closing tags but other times not is kinda frustrating although I can see the reasoning behind it.

**Comment by patrickodacre** [comment] 2019-08-14 10:31
I miss the old behavior. I'm constantly deleting extra characters now =\ I'll be rolling back my version until this feature is added back. Thanks for all the hard work, folks!

**Comment by larsnystrom** [comment] 2019-08-15 07:58
The problem is that not all auto-inserted brackets are considered auto-inserted in the new implementation. If I write (PHP) `array_key_l` and use tab to auto-expand to `array_key_last()` the editor inserts the parenthesis for the function and puts the cursor in between them, but typing `)` won't overtype the ending parenthesis, since I auto-completed the entire function name and not just the parenthesis. The closing parenthesis is not considered auto-inserted because it was inserted as part of the function autocompletion feature and not the autoClosingBrackets feature. 

This means I have to keep track of how the brackets was auto-inserted in order to know when typing a closing bracket which will overwrite the auto-inserted one, or just insert a new character.

**Comment by gjsjohnmurray** [comment] 2019-08-15 08:09
> The problem is that not all auto-inserted brackets are considered auto-inserted in the new implementation. 

@larsnystrom this is #78975

**Comment by tabennett** [comment] 2019-08-17 17:51
This is making this editor nearly unusable for me. The old behavior is consistent with previous editors I was using (atom, sublime text) before coming to VS Code. Pretty frustrating/jarring to have BC changes like this come though.

**Comment by rhyek** [comment] 2019-08-20 13:36
The new behavior should've been opt-in. The way it worked before seemed more intuitive and I think most people had gotten used to it from using VSC or other editors.

**Comment by levilansing** [comment] 2019-08-25 16:22
Agree with everyone in this issue. Frankly I'm surprised such a small collection of people were able to change the default behavior of such a standard function of the IDE. Their opinion is valid, but it's a matter of preference, not something that should have changed the default behavior for everyone else. At the very least we need an option to restore the old behavior.

In the last couple weeks I have had so much keyboard frustration that I'm on the verge of writing an extension just to restore the old behavior.

**Comment by rhyek** [comment] 2019-08-25 16:41
How long will we have to wait for this option? Doesn't look like there's even a PR for it. Looks like it'll be at least another month to get a new version with the fix.

I really don't even understand what this change was trying to do or what the justification for it was. Previously, if you typed a closing parenthesis before an existing one and it got swallowed, the caret would now be positioned past that existing one and typing a new closing parenthesis will work and not get swallowed. Such a minor inconvenience that like 3 people in the world cared about and now it's an inconvenience for literally everyone else.

Sort of like this issue: https://github.com/microsoft/TypeScript/issues/29238

I think they should make it a rule where if you are a contributor and you are introducing a *feature* change that alters the fundamental editing experience, code an option to disable it. You can even make it opt-out, but have the option mentioned clearly in the release notes.

**Closed** 2019-08-26 13:59 UTC
Labels: editor-autoclosing, feature-request

**Comment by alexandrudima** [comment] 2019-08-26 14:01
Starting with tomorrow's Insiders build, you can use `"editor.autoClosingOvertype": "always"` to always type over closing quotes or brackets, even in the case of those characters that were not automatically inserted by the editor.

**Comment by julianlam** [comment] 2019-09-05 15:02
@alexandrudima You must feel like you are stuck between a rock and a hard place with this config option!

FWIW I am a fan of the over-typing and was very confused this past week because it seemed like it worked _sometimes_ but _not all of the time_, because occasionally I'll write half a conditional, fix some other line, and return to the conditional only to find my bracket overtyping no longer worked :confused: I suppose I simply got used to the overtyping, and because it was **consistent**, this was ok in my books.

I'll just leave this here: https://xkcd.com/1172/

**Comment by rhyek** [comment] 2019-09-05 15:15
I agree it should default to always. Several people at my work complained about this issue, but are too busy to investigate the cause and fix. I don't believe the new option was even mentioned in the latest release notes.
