### ISSUE TITLE
It is not possible to select multiple file from the file explorer

### ISSUE THREAD

**Issue by sajibsrs** [Microsoft/vscode#9478] opened 2016-07-19 11:29 UTC
- VSCode Version: 1.3.1
- OS Version: Win 10 x64

Steps to Reproduce:

It is not possible to select multiple file from the file explorer of vs code like ctrl+click or shift+click. To perform operation as delete, copy etc.

**Comment by kieferrm** [comment] 2016-07-20 22:05
Duplicate of #1023.

**Closed by kieferrm** 2016-07-20 22:05 UTC
Labels: duplicate
