### ISSUE TITLE
Release Notes Doesn't Retain Scroll Position

### ISSUE THREAD

**Issue by calendee** [microsoft/vscode#115828] opened 2021-02-05 05:59 UTC
Issue Type: <b>Bug</b>

When reading the release notes, it often lists new settings features.  A user will often discover these features as they scrolled down through the release notes.

The user then might open the settings tab to adjust for the new options. When the user clicks back to the Release Notes tab, the scroll position is lost and the user is back to the top of the release notes.

See this video: https://watch.cloudflarestream.com/081964d7237d045663c43445fa51c1cb

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_30276830 --crash-reporter-id e6bed93b-dfae-4b13-a937-b05d7455ce20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
jelly-language-support|Act|0.9.0
vscode-icalendar|af4|1.0.1
vscode-tailwindcss|bra|0.5.8
vscode-expo|byC|0.1.2
cacher-vscode|Cac|1.1.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.1
easy-snippet|inu|0.6.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.3
polacode|pnp|0.3.4
prisma|Pri|2.16.0
synthwave-vscode|Rob|0.1.8
html5-boilerplate|sid|1.1.1
rewrap|stk|1.13.0
highlight-matching-tag|vin|0.10.0

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment] 2021-02-05 06:54
/duplicate of #115791

Problem has existed in previous versions too.

**Closed** 2021-02-05 06:55 UTC
Labels: *duplicate, new release
