### ISSUE TITLE
activationEvents.workspaceContains doesn't seem to trigger for a multi-root workspace when globs are used

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/vscode#36001] opened 2017-10-10 19:33 UTC
- VSCode Version: 1.18.0-insider
- OS Version: macOS 10.13

Steps to Reproduce:

I haven't looked too deeply into why this is happening, but it can be repro'd with C# for VS Code. This extension defines several activationEvents.workspaceContains triggers using globs. For example:

```JSON
{
    "activationEvents": {
        "workspaceContains:*.csproj"
        "workspaceContains:**/*.csproj"
    }
}
```

When open a multi-root workspace where a folder contains files matching these globs, the extension does not trigger. It does appear to work when globs are not used.

**Comment by bpasero** [comment] 2017-10-12 04:56
@DustinCampbell I cannot reproduce with a simple sample. Can you try to reproduce from a hello world extension (via `yo code`) and attach the sample here?

**Comment by DustinCampbell** [comment] 2017-10-12 19:50
Sure! Here's a simple extension that reproduces the situation.

[vscode-repro.zip](https://github.com/Microsoft/vscode/files/1380116/vscode-repro.zip)

1. Unzip `vscode-repro.zip`, `npm i`, and open in VS Code Insiders
2. Open `package.json` -- note that there are two additional `workspaceContains` activation events for `*.csproj` and `**/*.csproj`.
3. <kbd>F5</kbd> to launch the extension under the debugger
4. In the debuggee, open `test-workspace`, which is included in `vscode-repro.zip`. This contains two projects, each of which contains a `*csproj` file.
5. Note that the extension **does not** activate (it prints a message to the Debug Console when it activates).
6. Stop debugging.
7. Open `package.json` and add another `workspaceContains` activate event: `"workspaceContains:project1.csproj"`
8. <kbd>F5</kbd> to launch the extension under the debugger.
9. Note that the extension **does** activate, printing a message to the Debug Console.

**Comment by chrmarti** [comment] 2017-10-13 03:00
This might be fixed in the next insiders build. (https://github.com/Microsoft/vscode/commit/b5f41b98022df299ec8c99143be38bb8f7dae063#diff-ed16d18d1171d29df0c5c221fa1e48f1R239)

**Comment by bpasero** [comment] 2017-10-13 08:05
Yes, I can no longer reproduce with latest.

**Closed by bpasero** 2017-10-13 08:05 UTC
Labels: multi-root, needs more info

**Comment by DustinCampbell** [comment] 2017-10-13 13:19
Cool. I'll take a look.

**Comment by DustinCampbell** [comment] 2017-10-13 16:47
I just updated insiders this morning and can verify that this appears to be working now. Thanks!
