### ISSUE TITLE
The specified task cannot be tracked

### ISSUE THREAD

**Issue by haniamr** [microsoft/vscode#92814] opened 2020-03-17 00:53 UTC
- VSCode Version: 1.43.0
- OS Version: Windows 10 1909

**Steps to Reproduce:**
Complete steps here: https://github.com/microsoft/vscode-docker/issues/1756

The problem only happens if using VS Code 1.43.0, I don't see it if I downgrade to 1.42.0. Are there any changes that we should accommodate for in the Docker extension?

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment] 2020-03-17 16:06
Looks like a duplicate of https://github.com/microsoft/vscode/issues/92792. I can't get the complete repro steps to work, but seems likely to be the same issue.

**Comment by alexr00** [comment] 2020-03-19 11:32
This ended up being a separate issue. It affects tasks with dependsOn, where one of the dependsOn fails. The next time the task is run, it will get stuck.

**Closed** 2020-03-23 16:08 UTC
Labels: bug, candidate, tasks

**Comment by alexr00** [comment] 2020-03-24 14:09
To verify, add the following to a launch configuration:
```
"preLaunchTask": "depends task"
```
And these tasks: 
```
		{
			"label": "depends task",
			"problemMatcher": [],
			"command": "echo hello",
			"type": "shell",
			"dependsOn": "fails task"
		},
		{
			"label": "fails task",
			"problemMatcher": [],
			"type": "shell",
			"dependsOn": "sleep task",
			"command": "exit 1"
		},
		{
			"label": "sleep task",
			"command": "timeout 11", // or sleep 11 if not on windows
			"problemMatcher": [],
			"type": "shell"
		}
```

Run the launch config twice. Verify that _both_ times you get the same dialog that says the task has terminated. Verify that you _never_ see a dialog saying that the task cannot be tracked. 
Then, change the "exit 1" command in the "fails task" to "exit 0" and run the launch config again. Verify that it succeeds.
