### ISSUE TITLE
CTRL+<Right|Left> arrow is not working in integrated console

### ISSUE THREAD

**Issue by rchaganti** [Microsoft/vscode#9048] opened 2016-07-11 05:02 UTC
- VSCode Version: 1.3.0
- OS Version: Windows 10

In the editor, and in general many consoles, Ctrl+Right or Left arrow moves the cursor left or right by a word. This functionality is immensely helpful within the integrated console too. At the moment, in the integrated console, this key combination results in inserting '5D'. 

Steps to Reproduce:

1. Open Integrated Console
2. Type a command and then try Ctrl+Left

**Comment by Tyriar** [comment] 2016-07-11 17:47
Duplicate of #7077

**Closed by Tyriar** 2016-07-11 17:47 UTC
Labels: duplicate
