### ISSUE TITLE
Intellisense autoimport of React components not working

### ISSUE THREAD

**Issue by F1nnM** [microsoft/vscode#126914] opened 2021-06-22 15:08 UTC
Issue Type: <b>Bug</b>

I created a basic react app with the CRA utility and added another file Test.js:
```
export default function Test({}) {
    return <>Test</>
}
```
While Intellisense recognizes this file and offers completion when I type `<T` somewhere else, it doesn't auto-import it, when selected. 
![image](https://user-images.githubusercontent.com/12767947/122950118-7d81dc00-d37c-11eb-923e-34d9eb916c6e.png)

This also applies to installed components like Bootstrap for React or MDBReact. The correct completions are shown, but it doesn't import them.
![image](https://user-images.githubusercontent.com/12767947/122950298-a0ac8b80-d37c-11eb-9443-1154319f4d3f.png)

It used to work, but today it suddenly doesn't work anymore. Neither on new projects nor on old ones, where it definitely did work. I don't recall updating VSCode, but I guess I did that recently, based on the version below. I also updated Node and NPM, should that be important.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-73-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|15.50GB (0.96GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 1fc55df9-b43f-42d8-9dfd-4fb61e8710bc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-table-prettify|dar|3.4.0
gitlens|eam|11.5.1
vscode-npm-script|eg2|0.3.22
rest-client|hum|0.24.5
latex-workshop|Jam|8.19.2
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
vetur|oct|0.34.1
vscode-scss-formatter|sib|2.2.2
vscode-ltex|val|10.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615cf:30323120

```

</details>

**Comment by NatanCieplinski** [comment] 2021-06-24 14:53
I'm having the same problem, the correct completion are shown but the autoimport doesn't work.

**Comment by F1nnM** [comment] 2021-06-25 13:16
Very likely related to this: If I import for rexample ReducerAction (I don't know wether it makes sense at this point in the code, I just tried random things), it actually import ist. But like this...
![image](https://user-images.githubusercontent.com/12767947/123430172-26704700-d5c8-11eb-86b8-2b60f07afe58.png)
After I press enter:
![image](https://user-images.githubusercontent.com/12767947/123430218-3556f980-d5c8-11eb-85b4-859571734062.png)

**Comment by a-type** [comment] 2021-06-25 18:23
Same issue here, and sometimes the proper imports don't show up at all - unless I close the intellisense and then `Ctrl+Space` again to reopen it.

![CleanShot 2021-06-25 at 14 19 50](https://user-images.githubusercontent.com/2829772/123468985-7b0fc400-d5c0-11eb-9d92-220fc851b017.gif)

In fact the one I ended up committing (the first suggestion) came from the wrong place - it used to properly default to import items from `@material-ui/core`, not sub-directory modules, as the first suggestion.

Often when I try to import React components I also get the first suggestion as some kind of 'shadow import' which has the right apparent typings but doesn't add an import line.

If it matters, you can see I'm using TypeScript `paths` to alias directories.

**Comment by F1nnM** [comment] 2021-06-25 19:48
> Same issue here, and sometimes the proper imports don't show up at all - unless I close the intellisense and then `Ctrl+Space` again to reopen it.

Can confirm, that's also a issue I'm facing.

However I don't get those "shadow imports". For me it just shows it once, and that doesn't add imports. Also no "Auto-Import" - label shows on the suggestion for me, so I guess the entry does what it's supposed to do (which is nothing), but the Auto-Import entries don't show up.

**Comment by risenforces** [comment] 2021-06-26 20:14
I faced this today.

https://user-images.githubusercontent.com/35740512/123524583-d33fe680-d6e4-11eb-95e4-c31e893bbe42.mp4

**Comment by hotfix519** [comment] 2021-06-26 20:42
I'm seeing something like this.  But it's only one specific project.

This project is working correctly.
![Screen Shot 2021-06-26 at 4 32 44 PM](https://user-images.githubusercontent.com/2013324/123525099-7b7d8d00-d69c-11eb-8f1b-096163f8b803.png)

This project is not.
![Screen Shot 2021-06-26 at 4 34 41 PM](https://user-images.githubusercontent.com/2013324/123525101-7c162380-d69c-11eb-831c-da5e3bcc8bf2.png)

I have NO idea why one would work and one wouldn't.  I already spent a good bit of my afternoon trying to figure out what the cause could be w/o much luck.  I had been approaching this from a project specific issue, so I was trying things like editing configs, settings, clearing node_modules, lock files, etc.  And nothing had an effect.  And I can confirm that non JSX exports are importing properly.

Would be glad to provide any more info, or dig deeper if pointed in the right direction.

**Comment by vricop** [comment] 2021-06-27 09:41
Same here. This happens to me since last update.

**Comment by joshuajung** [comment] 2021-06-29 10:39
This is likely related to https://github.com/microsoft/TypeScript/issues/44657 and the related PR https://github.com/microsoft/TypeScript/pull/44724. The issue is already fixed in `typescript@next`, so if you point your VSCode there, you may be fine.

**Comment by hotfix519** [comment] 2021-06-29 12:46
I just pointed my project to `typescript@next` and I can confirm that auto-imports are working now.  Thanks for the info!

**Comment by mjbvz** [comment] 2021-06-29 21:57
Duplicate of https://github.com/microsoft/TypeScript/issues/44657

**Closed by mjbvz** 2021-06-29 21:57 UTC
