### ISSUE TITLE
Text in debug console doesn't stay selected

### ISSUE THREAD

**Issue by rob-ubnt** [Microsoft/vscode#57702] opened 2018-08-31 16:25 UTC
- VSCode Version: **1.26.1**
- OS Version: **macOS High Sierra 10.13.4**

Steps to Reproduce:

1. Start a debug session.
1. Try to select only a portion of the debug console output.

Result: Part of what you selected becomes unselected. It's maddening.

![text-select-bug](https://user-images.githubusercontent.com/38537959/44924299-1cd70f80-ad08-11e8-9356-cb38d2c7e95b.gif)

Does this issue occur when all extensions are disabled? **Yes**

**Comment by isidorn** [comment] 2018-09-19 16:15
Sorry for the slow response I was on vacation.

I can not reproduce this with a simple exmaple.
Can you please try with latest vscode insiders https://code.visualstudio.com/insiders/
If you can reproduce can you write a simple JS program which outputs the text which you can not select.
Thanks a lot

**Comment by rob-ubnt** [comment] 2018-09-26 17:55
This is very easy to reproduce. Just add this code to a file, start a debug session, and double-click on the numbers as they appear in the console. They become selected for a moment, then the console "refreshes" and the selection goes away.

```js
let count = 1

setInterval(() => {
    console.log(count++)
}, 1000)

```

I've also attached a video of the issue:

[console.mov.zip](https://github.com/Microsoft/vscode/files/2420956/console.mov.zip)

**Comment by isidorn** [comment] 2018-09-27 14:48
Thanks for clariyfing. The issue here is that we are using a tree for the debug console, not the editor. Bascially a duplicate of https://github.com/Microsoft/vscode/issues/11462

**Closed by isidorn** 2018-09-27 14:48 UTC
Labels: debug, debug-console, needs more info
