### ISSUE TITLE
python syntax highlight, intellisense, and other feature stop working

### ISSUE THREAD

**Issue by moatazasd** [microsoft/vscode#190397] opened 2023-08-14 09:30 UTC
Type: <b>Bug</b>

when i open a file in jupyter notebook in vs code, sometimes the following state occurs:
1- the syntax coloring stops working, all text is white except strings and comments, (no colors for variables)
2- i cant hover and ctrl+ click on a variable, its like it is not recognize as anything, or the interpreter/kernel? is frozen
3- intellisense also does not work, when i type a variable it does not recognize it as an already defined variable above, so color is white, and when trying to apply on it something it does not give suggestion, even when clicking ctrl+space it keeps on searching without results

I tried restarting the kernel, selecting different kernel, closing and reopening the notebook, closing and reopening vs code, deleting and reinstalling vscode,  usually it does not work.
i created a new notebook and started filling it with same cells, it fills normally without the issue, but i cant keep doing that every while

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.19GB free)|
|Process Argv|--crash-reporter-id b64a845e-1ccc-4c3d-8b11-05fe54bf5ac9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
doxdocgen|csc|1.4.0
vscode-mysql-client2|cwe|6.6.9
vscode-html-css|ecm|1.13.1
code-runner|for|0.12.0
codespaces|Git|1.14.15
gc-excelviewer|Gra|4.2.57
better-cpp-syntax|jef|1.17.2
vsc-python-indent|Kev|1.18.0
vscode-clang|mit|0.2.4
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.20.1
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.2.0
black-formatter|ms-|2023.4.1
isort|ms-|2023.10.1
python|ms-|2023.15.12191008
vscode-pylance|ms-|2023.8.20
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.304.0
remote-ssh|ms-|0.102.0
remote-wsl|ms-|0.81.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2023.6.0
remote-explorer|ms-|0.4.1
remote-server|ms-|1.4.0
material-icon-theme|PKi|4.29.0
vscode-css-peek|pra|4.4.1
sqlite-viewer|qwt|0.3.13
vscode-xml|red|0.26.1
LiveServer|rit|5.7.9
cmake|twx|0.0.17
lorem-ipsum|Tyr|1.3.1
errorlens|use|3.13.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
footsteps|Wat|0.5.0
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.5.1
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by jzazo** [comment] 2023-08-14 10:26
This happens to me too. I normally hit `ctrl` + `shift` + `p`, and type `Developer: reload window`. Then intellisense starts working again until it stops.

**Comment by rebornix** [comment] 2023-08-23 01:06
/duplicate of https://github.com/microsoft/pylance-release/issues/4742

**Closed by rebornix** 2023-08-23 01:06 UTC
