### ISSUE TITLE
regression in new IntelliSense sorting

### ISSUE THREAD

**Issue by fr1zle** [Microsoft/vscode#26306] opened 2017-05-09 12:28 UTC
- VSCode Version: 1.12
- OS Version: any

Steps to Reproduce:

1. Create an extension with a snippet `do`
2. The extension should also supply different autocompletes containing the letters `d` and `o` (eg. `defoverridable`)
3. When typing `do` in a document, the first autocomplete item should (and used to) be the exact match (snippet `do`) instead the keyword autocomplete is the first item:
![image](https://cloud.githubusercontent.com/assets/311019/25850728/a30ede2a-34c3-11e7-82c0-c8be77a5fc3c.png)

This makes it very hard to use the elixir extension. Is there any way to work around this regression?

https://github.com/fr1zle/vscode-elixir/issues/64

**Comment by egamma** [comment] 2017-05-09 13:06
duplicate of #26182. A fix for this will be included in the next recovery build.

**Closed by egamma** 2017-05-09 13:06 UTC
Labels: duplicate
