### ISSUE TITLE
Windows issue with git

### ISSUE THREAD

**Issue by e-molochko** [microsoft/vscode#100400] opened 2020-06-17 15:42 UTC
Hey. 
1. Run VScode on windows
2. Git init(open project)
3. Add changes in some files so they will appear in VCS
4. Try to add/remove files into/from commit via plus button in VCS
5. "Git Fatal: File is outside repository"
 All git func works well via console

Think this is the issue with backslashes and forwardslashes in paths for Windows

**Comment by gjsjohnmurray** [comment] 2020-06-17 16:17
/duplicate of #99881 and others (search for 'outside repository')

People have reported resolving this by updating their local Git.

**Closed** 2020-06-17 16:18 UTC
Labels: *duplicate
