### ISSUE TITLE
Permission for microphon

### ISSUE THREAD

**Issue by HoBu23** [microsoft/vscode#118768] opened 2021-03-11 23:46 UTC
missing permission for microphon an mac big sur

**Comment by TylerLeonhardt** [comment] 2021-03-12 00:16
Can you provide a bit more of an explanation? Perhaps a screenshot?

/needsMoreInfo

**Comment by yume-chan** [comment] 2021-03-12 03:04
#95062 ?

**Comment by TylerLeonhardt** [comment] 2021-03-12 04:35
Yeah, I think you're right @yume-chan. Dupe of #95062

**Closed by TylerLeonhardt** 2021-03-12 04:35 UTC
Labels: needs more info

**Comment by HoBu23** [comment] 2021-03-13 11:21
> Yeah, I think you're right @yume-chan. Dupe of #95062

Thank's @yume-chan . for your link :)
