### ISSUE TITLE
Grupo de Extenção

### ISSUE THREAD

**Issue by AlisonAO-RV** [microsoft/vscode#142076] opened 2022-02-03 12:39 UTC
Issue Type: <b>Feature Request</b>

Hello, a suggestion that can facilitate the use of VSCode is the creation of groups for the extensions
In my case, I work with several paradigms and several frameworks, and I don't always use the same extensions in projects, having to manually enable and disable extensions.
With this function, we can configure which group should be activated in each project, thus avoiding extension conflicts. (automatic translation: PT -> EN)

Example:
- GLOBAL_GROUP
- ANGLE_GROUP
- REACT_GROUP
- PYTHON_GROUP
- DJANGO_GROUP
- C_GROUP

Thanks for listening

Alison

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by IllusionMH** [comment] 2022-02-03 12:46
Looks like direct duplicate of #139747 which should be covered by issues linked there.

**Closed** 2022-02-04 10:23 UTC
Labels: *duplicate
