### ISSUE TITLE
Some command titles are shown as UUIDs instead of names

### ISSUE THREAD

**Issue by neongreen** [microsoft/vscode#210248] opened 2024-04-12 15:49 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.88.1
- OS Version: macOS 14.4.1

Steps to Reproduce:

1. Search for "Outline" or "workbench" either in command search (Cmd+Shift+P) or in keyboard shortcuts
2. See a weird name

<img width="476" alt="image" src="https://github.com/microsoft/vscode/assets/1523306/639d8296-8ac2-473b-b353-a28ab65b3b87">

<img width="655" alt="image" src="https://github.com/microsoft/vscode/assets/1523306/64531287-2843-4ed1-8c9c-36e5bc108300">

Copied in full here: `workbench.views.service.panel.4df521c3-693a-4245-8c78-243cb5a7f7d1: Focus on Outline View`

This occurs with extensions disabled. I think it only started occurring after today's upgrade and didn't happen eg. one month ago, but not 100% sure.

**Comment by gjsjohnmurray** [comment] 2024-04-12 16:08
Looks like #201085 and #202086

**Comment by neongreen** [comment] 2024-04-12 21:26
Looks like, yeah. Anything I can do to help with debugging?

**Comment by benibenj** [comment] 2024-04-15 10:30
Closing as duplicate of #201085. If you have reliable reproducible steps please add them to #201085. After trying this quickly I was not able to reproduce.

**Closed by benibenj** 2024-04-15 10:30 UTC
