### ISSUE TITLE
Major ergonomics issues with RxJS v7 and VS Code auto imports

### ISSUE THREAD

**Issue by benlesh** [microsoft/vscode#119007] opened 2021-03-15 18:34 UTC
- VS Code Version: any
- OS Version: any

Steps to Reproduce:

1. Create a project and install `npm rxjs@7.0.0-beta.13` or `rxjs@next`.
2. Type something like `mergeMap` and let auto-import do it's thing.
3. Observe that the added import is **not** from `rxjs/operators`, rather from `rxjs/dist/types/operators`, which is really incorrect.

Does this issue occur when all extensions are disabled?: Yes

There is additional discussion of the problem here: https://github.com/ReactiveX/rxjs/issues/6067

We're uncertain what we can do about it, but it's definitely a bad UX we want to fix as soon as we can.

**Comment by mjbvz** [comment] 2021-03-15 23:13
Duplicate of https://github.com/microsoft/TypeScript/issues/43034

**Closed by mjbvz** 2021-03-15 23:13 UTC
