### ISSUE TITLE
Since installing MacOS Big Sur, scrolling and typing have become jerky

### ISSUE THREAD

**Issue by giltayar** [microsoft/vscode#113391] opened 2020-12-24 14:56 UTC
Issue Type: <b>Performance Issue</b>

Run VSCode, and just type in the terminal. You will see the jerkiness immediately.

This also happens when typing and scrolling in editor windows.

I disabled all extensions, and it still happens, so I guess it's not an extension problem.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id 6db746cd-9e7a-41d3-804d-b6dfa8a20732|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   131	 13188	code main
    0	    82	 13191	   gpu-process
    0	    33	 13193	   utility
   93	   131	 14112	   shared-process
    0	     0	 18973	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   262	 18459	   window (rollup.config.mjs — metacritic (Workspace))
    0	     0	 18460	     /bin/zsh -l
    0	   213	 18468	     extensionHost
    0	    98	 18882	       electron_node tsserver.js 
    0	   295	 18883	       electron_node tsserver.js 
    0	    66	 18890	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 18886	       electron_node server.js 
    0	    66	 18930	       electron_node eslintServer.js 
    0	    33	 18935	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=18468
    0	    33	 18865	     watcherService
    0	    33	 18903	     searchService
    1	    66	 18971	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (rollup.config.mjs — metacritic (Workspace))
|    Folder (.bilt): 2 files
|      File types: yaml(2)
|      Conf files:
|    Folder (onboarding): 1 files
|      File types: md(1)
|      Conf files:
|    Folder (design): 8 files
|      File types: excalidraw(2) md(2) png(2)
|      Conf files:
|    Folder (console-tesktit): 28 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (pino-testkit): 29 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (http-commons): 32 files
|      File types: json(6) ts(5) js(3) map(3) md(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (log-request-fastify-plugin): 29 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (mocha-commons): 29 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (request-id-logger-fastify-plugin): 30 files
|      File types: json(6) ts(4) md(2) js(2) map(2) base(1) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (register-jsdom): 29 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (functional-commons): 32 files
|      File types: json(7) ts(5) js(3) map(3) md(2) gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: node
|    Folder (request-id-fastify-plugin): 30 files
|      File types: json(6) ts(4) md(2) js(2) map(2) base(1) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (promise-commons): 32 files
|      File types: json(7) ts(5) js(3) map(3) md(2) gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: node
|    Folder (webdriverio-testkit): 29 files
|      File types: json(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (pino-global): 43 files
|      File types: ts(8) json(6) js(6) map(6) md(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (rollup-testkit): 37 files
|      File types: json(6) ts(4) js(4) md(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1) mjs(1) html(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (text-component): 37 files
|      File types: json(6) js(6) md(2) html(2) mjs(2) css(2) base(1)
|                  eslintignore(1) gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (url-commons): 34 files
|      File types: json(6) ts(5) js(3) map(3) md(2) eslintignore(1)
|                  gitignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (scripting-commons): 34 files
|      File types: json(6) ts(4) txt(3) md(2) js(2) map(2) gitignore(1)
|                  prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (docker-compose-testkit): 37 files
|      File types: json(7) ts(4) md(2) js(2) html(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1) yml(1)
|      Conf files: package.json(2) launch.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (kubernetes-testkit): 41 files
|      File types: json(6) yaml(6) ts(4) md(2) js(2) map(2) eslintignore(1)
|                  gitignore(1) prettierrc(1) gitkeep(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (dependencies-commons): 51 files
|      File types: json(8) ts(7) js(5) map(5) gitignore(2) md(2) txt(2)
|                  eslintignore(1) prettierrc(1)
|      Conf files: package.json(3) launch.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (metacritic-product-catalog): 75 files
|      File types: ts(13) js(12) map(11) json(7) md(2) yaml(2) base(1)
|                  dockerignore(1) eslintignore(1) gitignore(1)
|      Conf files: package.json(2) launch.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (kdeploy): 110 files
|      File types: yaml(22) ts(9) js(7) map(7) json(6) gitignore(2) md(2)
|                  gitkeep(2) eslintignore(1) prettierrc(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node
|    Folder (create): 144 files
|      File types: js(37) json(16) ts(6) md(5) base(5) yaml(4) eslintignore(3)
|                  gitignore(2) prettierrc(2) html(2)
|      Conf files: launch.json(2) tsconfig.json(2) package.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
lit-html|bie|1.11.1
vscode-excalidraw|bri|0.0.5
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.1.0
prettier-vscode|esb|5.8.0
code-runner|for|0.11.1
vscode-pull-request-github|Git|0.22.0
search-node-modules|jas|1.3.0
vscode-docker|ms-|1.9.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-yaml|red|0.13.0
vscode-javascript-booster|sbu|14.0.1
open-in-browser|tec|2.0.0
vscode-java-debug|vsc|0.30.0
vscode-icons|vsc|11.0.0
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30236574
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt875:30239451
vsjup459:30237187

```

</details>

**Comment by meganrogge** [comment] 2020-12-25 03:06
Duplicate of #105446

**Closed** 2020-12-25 03:07 UTC
Labels: *duplicate, integrated-terminal
