### ISSUE TITLE
Git push doesn't ask for authentication

### ISSUE THREAD

**Issue by himanshub16** [Microsoft/vscode#5391] opened 2016-04-16 13:47 UTC
- VSCode Version:1.0.0
- OS Version:Debian Stretch

Git push should ask for authentication, but vs-code reports error : 

> Authentication failed on git remote.

**Comment by joaomoreno** [comment] 2016-04-18 06:59
Duplicate of #1796

**Closed by joaomoreno** 2016-04-18 06:59 UTC
