### ISSUE TITLE
Extension API: onDidRenameFiles listener is invoked for every file of one rename/move operation

### ISSUE THREAD

**Issue by Geometror** [microsoft/vscode#113634] opened 2020-12-31 17:37 UTC
- VSCode Version: 1.52.1 (and latest 1.53 Insider-Build)
- OS Version: Windows 10 Pro (20H2)

Prior to VSCode version 1.52 the listener was called once per move/rename operation when the user tried to move several files at once. All affected file URIs were passed to the listener in an array(`files` property[`ReadonlyArray`] of `FileRenameEvent`). Since version 1.52 it is executed for each file, even when moving folders together with individual files. 
As the length of the `files` array is always 1 I assume this isn't a desired behavior.

Steps to Reproduce:

1. Create new VSCode extension
2. Subscribe to the rename event with onDidRenameFiles(some listener function) and print out the files list of the passed event object (movedFileEvt.files):
```
...
vscode.workspace.onDidRenameFiles(this.onDidRenameFiles,this)
...

public onDidRenameFiles(movedFileEvt: vscode.FileRenameEvent): void {
        console.log("Invoked, file list length:" + movedFileEvt.files.length)
        for (let movedFile of movedFileEvt.files) {
            console.log(movedFile.oldUri.fsPath)
        }
 }
```

Does this issue occur when all extensions are disabled?: Yes (all other)

**Comment by jrieken** [comment] 2021-01-04 08:32
/duplicate of https://github.com/microsoft/vscode/issues/111867

**Closed** 2021-01-04 11:20 UTC
