### ISSUE TITLE
COPILOTE NOT WORKING

### ISSUE THREAD

**Issue by Nisal-N-Narasinghe** [microsoft/vscode#176643] opened 2023-03-09 14:43 UTC
Type: <b>Bug</b>

Copilote stopped working 3 or 4 times

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.44GB free)|
|Process Argv|--crash-reporter-id 4a74fb39-a6d6-44c0-a01b-fffa71013f14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.4.4
doxdocgen|csc|1.4.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
c-cpp-runner|fra|5.1.2
duplicate|gee|1.0.2
vscode-javac|geo|0.2.45
classroom|git|0.0.3
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.60.0
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.17.2
kite|kit|0.147.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.37
icie|mik|1.0.0
vscode-html-format|moh|0.0.5
vscode-docker|ms-|1.24.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2023.4.0
vscode-pylance|ms-|2023.3.20
jupyter|ms-|2023.2.1000592019
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.282.0
remote-ssh|ms-|0.98.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.76.1
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5834
live-server-preview|neg|0.1.4
subtitles-editor|pep|1.1.7
vscode-css-peek|pra|4.2.0
java|red|1.15.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
bash-debug|rog|0.3.9
bash-beautify|sha|0.1.1
js-jsx-snippets|sky|11.0.1
css-auto-prefix|spo|0.1.7
autoimport|ste|1.5.4
tabnine-vscode|Tab|3.6.41
vscode-status-bar-format-toggle|tom|3.1.1
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.8
vscode-maven|vsc|0.40.4
vscode-spring-initializr|vsc|0.11.2
div|vsc|0.1.4
vscode-icons|vsc|12.2.0
quokka-vscode|Wal|1.0.527
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsccsb:30677849
vscodeenable:30660116
pythonb192:30669360
funwalk2:30676043
pythonms35:30680984

```

</details>

**Comment by isidorn** [comment] 2023-03-15 11:18
Thank you very much for opening this issue. We are currently investigating Copilot causing crashes and we are consolidating all the findings in https://github.com/microsoft/vscode/issues/176562
We believe this is an out of memory issue, and we can not yet reproduce it on our side. Thus it would be super helpful if you can share reproducible steps (what type of file opened, does this happen when Copilot is suggesting) here https://github.com/microsoft/vscode/issues/176562

Due to the consolidation I am closing this as a duplicate.

If you can reproduce this issue after disabling Copilot do let us know and we can reopen this issue.

**Closed by isidorn** 2023-03-15 11:18 UTC
Labels: freeze-slow-crash-leak, extension-host, triage-needed
