### ISSUE TITLE
Build task not found sometimes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#173384] opened 2023-02-03 22:24 UTC
* Install Java extension pack
* Open VS Code repo
* Cmd+Shift+B
* 🐛 Java extension prompts error and the task detection never finishes

**Comment by meganrogge** [comment] 2023-02-06 12:35
We have to wait for extensions to be registered before reading the tasks because of task contributions from extensions. I don't think we can change this. @alexr00 thoughts?

**Comment by alexr00** [comment] 2023-02-06 13:12
We could have a timeout per task provider. If a task provider doesn't provide tasks for 3 minutes after we ask for tasks then it's likely it will never provide tasks. That would let us show the tasks for all the other extensions except the slow one.

**Comment by meganrogge** [comment] 2023-03-08 20:26
I will try to get to this in March, no logs are needed as we understand how this could happen

**Comment by meganrogge** [comment] 2023-05-04 13:10
Original repro steps still work 👍🏼

**Comment by meganrogge** [comment] 2023-06-22 21:37
Steps still work

**Comment by meganrogge** [comment] 2023-06-23 19:22
Alright, getting closer to an answer - the consistent repro for me is when there's a multi-root workspace. 

When that's the case, `findWorkspaceTasks` yields none, so `taskGroupTasks` gets set = to `findWorkspaceTasksInGroup` with the comment `// If no globs are found or matched fallback to checking for default tasks of the task group`

https://github.com/microsoft/vscode/blob/841b784f0024074a0b19d84f77fc02204f9bfa3b/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2949

https://github.com/microsoft/vscode/blob/841b784f0024074a0b19d84f77fc02204f9bfa3b/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3002

It returns no tasks for the group because the predicate always fails because none of the tasks have a `group` property set yet. 

So enters here 
https://github.com/microsoft/vscode/blob/841b784f0024074a0b19d84f77fc02204f9bfa3b/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3000-L3003

and by that time, the group is defined
![Screenshot 2023-06-23 at 12 19 00 PM](https://github.com/microsoft/vscode/assets/29464607/94cf99b4-6d56-4d78-bde5-fda9d9e35969)

but `isDefault` isn't yet set, so it can't be filtered to just the default one(s)
![Screenshot 2023-06-23 at 12 21 17 PM](https://github.com/microsoft/vscode/assets/29464607/a32aec35-0c72-41a2-9cdf-199ef7f20223)

and since there are many, this gets called and shows the quick-pick. https://github.com/microsoft/vscode/blob/841b784f0024074a0b19d84f77fc02204f9bfa3b/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3011

**Comment by meganrogge** [comment] 2023-06-23 19:31
Then it enters `handleMultipleTasks` and concatenates non-defaults to the defaults. I don't think we want to do that.

![Screenshot 2023-06-23 at 12 31 10 PM](https://github.com/microsoft/vscode/assets/29464607/ada9dc66-018f-465f-96c7-66351db697b9)

**Comment by meganrogge** [comment] 2023-06-23 19:36
the fix is when there are `defaults`, to only show those

![Uploading Screenshot 2023-06-23 at 12.35.55 PM.png…]()

**Comment by meganrogge** [comment] 2023-06-23 19:43
the fix is to only get the defaults and show those. we don't care about the others here. 

![Screenshot 2023-06-23 at 12 36 33 PM](https://github.com/microsoft/vscode/assets/29464607/cb8cef3f-a8bd-4e9c-b7a5-e2f14f639af4)

**Comment by meganrogge** [comment] 2023-06-23 19:45
Regression introduced by #88106, but there's also the timing component

**Comment by meganrogge** [comment] 2023-06-23 19:56
I think we should be awaiting `readTasks` before registering the task commands

https://github.com/microsoft/vscode/blob/1ddfa65f9dfcbec2bb0276490c91d235515e304f/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1002

**Comment by meganrogge** [comment] 2023-07-03 19:43
ok in an OSS where I'm reproducing, I see this pending promise

![Screenshot 2023-07-03 at 12 41 42 PM](https://github.com/microsoft/vscode/assets/29464607/4960f222-2467-4977-acef-19d91070aef0)
![Screenshot 2023-07-03 at 12 42 01 PM](https://github.com/microsoft/vscode/assets/29464607/3b050151-e4ad-4337-8d9a-7a8098cf18c6)

**Comment by meganrogge** [comment] 2023-07-03 19:49
only the `ContributedTasks` are used here

![Screenshot 2023-07-03 at 12 49 07 PM](https://github.com/microsoft/vscode/assets/29464607/970bd8e7-3336-428d-bed9-a5cb04369755)

**Comment by meganrogge** [comment] 2023-07-03 19:50
so the issue is the `ConfiguredTasks` aren't resolved in this case on time

![Screenshot 2023-07-03 at 12 50 31 PM](https://github.com/microsoft/vscode/assets/29464607/57aee99f-3c46-48c4-9a72-7faf0cad871e)

**Comment by meganrogge** [comment] 2023-07-03 19:56
I think `contributed` here should have a size > 0

![Screenshot 2023-07-03 at 12 56 08 PM](https://github.com/microsoft/vscode/assets/29464607/7a1e7368-eaa5-4b72-a379-3bb60284d76d)

**Comment by meganrogge** [comment] 2023-07-03 20:13
this is interesting - I have the settings editor open here, no other editor.
![Screenshot 2023-07-03 at 1 11 59 PM](https://github.com/microsoft/vscode/assets/29464607/184f53be-56e1-47b7-bb5f-99f87f743588)

**Comment by meganrogge** [comment] 2023-07-03 20:18
interesting - I wonder if this is the issue
![Screenshot 2023-07-03 at 1 18 24 PM](https://github.com/microsoft/vscode/assets/29464607/1e78ec3d-81ec-44a9-96e2-7aeb9cb2ae8c)

**Comment by meganrogge** [comment] 2023-07-03 20:44
worked:
![Screenshot 2023-07-03 at 1 43 08 PM](https://github.com/microsoft/vscode/assets/29464607/27550971-fe66-41a0-91f0-4b091df5e327)

failed:
![Screenshot 2023-07-03 at 1 44 02 PM](https://github.com/microsoft/vscode/assets/29464607/dd61e3a2-1743-42a0-9987-803ff1b5f0f3)

**Comment by meganrogge** [comment] 2023-07-03 20:47
so I think what's happening is if I trigger the build task before folder open, the promise is set but the tasks for that folder aren't parsed. then we return that promise indefinitely. 

I think checking if the `runSource` is `folderOpen` is in order here and in that case, we want to update the workspace tasks instead of returning the promise

**Comment by meganrogge** [comment] 2023-07-03 20:48
yep - I believe that works. 

![Screenshot 2023-07-03 at 1 48 34 PM](https://github.com/microsoft/vscode/assets/29464607/146b0747-3040-4245-9457-60f0df03fc80)

So the repro is to run the build task before the folder opens.

**Comment by meganrogge** [comment] 2023-07-05 16:34
Just reproduced twice. When I did, both times it said this:

```
Warning: npm tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: gulp tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: npm tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: process tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Warning: shell tasks are unavailable in the current environment.

Workspace folder was undefined
Workspace folder was undefined
```

**Comment by meganrogge** [comment] 2023-07-05 20:15
still happens in the build I created with the latest fix. note that i don't see extensions getting activated in the status bar here at all 🤔 

I also don't see the workspace folder undefined message anymore, but still see that the tasks are unavailable in the current environment.

https://github.com/microsoft/vscode/assets/29464607/da0664a3-d8bd-4935-8917-40f9cb89dbd9

**Comment by meganrogge** [comment] 2023-07-05 20:33
the moment I change the `tasks.json` file, it starts to work. IE when this is called

```
return this._updateWorkspaceTasks(TaskRunSource.ConfigurationChange);
```

**Closed** 2023-07-06 18:20 UTC
Labels: bug, tasks, confirmed, papercut :drop_of_blood:

**Comment by meganrogge** [comment] 2023-07-06 18:44
While it's possible (extremely rare) that a user will still hit this if they run the build task before a particular execution context has been set, this fix will prevent that from reproducing.

To verify, open VS code (typically a restart) and run the build task. If you do see the quickpick instead of the default build task getting, run, then the next time you run the build task, you should not see it.

The above should be hard to reproduce though - and only possible if you time it just right. Before, this would happen more frequently and was reproducible until window reload.
