### ISSUE TITLE
Menu items are constantly highlighted and the first menu item always has a black border with the newly custom title bar style enabled

### ISSUE THREAD

**Issue by NearAutomata** [Microsoft/vscode#53744] opened 2018-07-06 19:04 UTC
- VSCode Version: Code 1.25.0
- OS Version: Windows 10

Quick gif showing the issue:

![Gif](https://i.imgur.com/VVdD8c8.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment] 2018-07-10 21:45
duplicate of #52933 and #52911

**Closed by sbatten** 2018-07-10 21:45 UTC
