### ISSUE TITLE
Quick opened files should be kept open, not previewed

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#11789] opened 2016-09-09 17:46 UTC
- VSCode Version: 1.4.0
- OS Version: macOS
### Desired behavior

When you use Quick Open (<kbd>Cmd</kbd> + <kbd>P</kbd>) to open a file, that file should stay open (i.e. it shouldn't be a preview tab).
### Current behavior

Current behavior opens it as a preview tab, which can be undesirable.  If you open a lot of files up front through quick open, you have to double click the tab or run command "Keep Open" for each file.  It makes it very slow to open a lot of files from Quick Open.

![sep-09-2016 10-42-30](https://cloud.githubusercontent.com/assets/11839736/18396775/2bd6b2f4-767a-11e6-8ab7-540aa0be74a1.gif)

Since some people may want to rapidly preview a lot of files, then we should do what Sublime does in their version of Quick Open: upon keyboard focus or hover of any file in Quick Open, a preview tab is shown.  Only when you press Enter or click does it keep it as an editor and close the Quick Open.

If we click away from or press <kbd>Esc</kbd>in Quick Open, then this preview tab would close, unless there already was a preview tab open before using Quick Open (in that case the previously previewed file would appear as if nothing had ever happened, so we don't leave a mess).

**Comment by bpasero** [comment] 2016-09-09 17:53
The setting `workbench.editor.enablePreviewFromQuickOpen` controls this. Otherwise this looks like a duplicate of https://github.com/Microsoft/vscode/issues/8939

**Closed** 2017-01-05 07:39 UTC
Labels: feature-request, ux
