### ISSUE TITLE
Update WATCH area from debugger

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#114990] opened 2021-01-05 14:56 UTC
I have the following problem:
There is data in the WATCH area. This is updated on every debug step.
So far, so good.

How is it possible to update this programmatically.

In my case the user has the possibility to change data in a memory dump in a WebView.
When he does so the WATCH area is not updated because it is not informed to do so.

Is there any possibility to update the WATCH area initiated by the extension?
Is there a message I can send via the debug adapter protocol to do so?

**Comment by isidorn** [comment] 2021-01-26 10:18
@maziac thanks for providing feedback. As @connor4312 has mentioned an invalidated event should hopefully just work.
Also make sure to send to send the `areas = ['variables']` as part of your invalidated event.
Here's how we handle that in vscode https://github.com/microsoft/vscode/blob/fc5f18691dcfd22952c4c2d7cdfb2ae5102535eb/src/vs/workbench/contrib/debug/browser/debugSession.ts#L1021

If this still does not work, it would be great if you create a fork of `mock-debug` that reproduces this problem, so I can simply clone your fork of `mock-debug` and investgiate more on my machine.
Thanks!

**Comment by maziac** [comment] 2021-01-26 19:06
Yes, ['variables'] seems to do the trick.
Do you have some explanation for it?
I would guess that invalidate without an info would update 'all'. Why does it work if I narrow the request?
And why do I have to use 'variables' and not 'watch'?

From the docs: "If this property is missing, empty, or if values are not understand the client should assume a single value 'all'"
I tried also a value of 'all' and that does not work either.

What other areas do exist? The documentation does not mention them.

**Comment by isidorn** [comment] 2021-01-27 08:42
Yeah, the code here is the reason https://github.com/microsoft/vscode/blob/f434f853aafc3f768bc5d34cff0305576cf61e96/src/vs/workbench/contrib/debug/browser/debugSession.ts#L1022

I can change it to also handle the 'watch' as the area. Thus assigning to January

**Closed** 2021-01-27 11:31 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2021-01-27 11:32
I have pushed a change that now you can aslo send  `watch` as part of the areas.
The reason why we handle it like that is that if the area is not specified that means a "hard refresh" and we will refatch the threads. I would guess that for your debug adapter refatching threads changes some ids and thus it is no longer possible to expand some watch values.

However I would not be happy making more changis in this area since Java debugger depends on this behavior, thus closing this for now, and I suggest that you simply send the `areas` array.
