### ISSUE TITLE
Microsoft Authentication's token refresh fails when signed into multiple extensions.

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#126269] opened 2021-06-14 17:20 UTC
Issue Type: <b>Bug</b>

The Microsoft authentication provider fails to refresh the token on reloading the window if user is signed into multiple extensions.

Repro steps:
1. Create two empty extensions named `aad-auth-1` & `aad-auth-2` through the yo code generator. [See this tutorial.](https://code.visualstudio.com/api/get-started/your-first-extension)
2. Register two AAD apps to act as two resources. [See this.](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/4-AdvancedGrants/1-call-api-graph#register-the-service-app) You can skip 8th step here.
3. Add the VS Code AAD client (Id: aebc6443-996d-45c2-90f0-388ff96faa56) as trusted client for the user_impersonation scope in the above two AAD apps.
4. In 1st extension, package.json, change the hello world command title to `Hello World 1` . Then update the command execution to 
```
let disposable = vscode.commands.registerCommand('aad-auth-1.helloWorld1', async () => {
    // The code you place here will be executed every time your command is executed

    // Display a message box to the user
    vscode.window.showInformationMessage('Hello World from aad-auth-1!');
    try {
        await vscode.authentication.getSession('microsoft', [
            'api://cd96451f-9709-4a95-b1f5-79da05cf8502/user_impersonation',
            'offline_access',
            ], { clearSessionPreference: false, createIfNone: true })
            .then((session: vscode.AuthenticationSession) => {
                console.log(session);
            });
    } catch (error) {
        console.log(error.message);
    }
});
```
5. In 2nd extension, do same as above, but request `user_impersonation` scope for the 2nd AAD app. 
6. Compile, package and install the two extension.
7. Run the command `Hello World 1` sign in into 1st extension. Then run command `Hello World 2` and sign into 2nd extension.
8. Now reload the window. Notice that the when you run 'Hello World 1', you will be prompted for a sign in again. Same for 'Hello World 2'. So both the sessions are lost after reload.
9. If you disable aad-auth-1, sign in into aad-auth-2 and reload window, then the session is preserved and you don't get a sign in prompt when you run 'Hello World 2'.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (4.81GB free)|
|Process Argv|--crash-reporter-id 1e7fa2ad-4532-4c0a-9475-8f16bd6b778e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.4.0
azure-account|ms-|0.9.8
powershell|ms-|2021.5.1
aad-auth-2|sag|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833cf:30267465
vshan820:30294714
vscus158cf:30286554
vscod805cf:30301675

```

</details>

**Comment by TylerLeonhardt** [comment] 2021-06-18 16:22
@samrat-gavale Can you share what's in the Microsoft Authentication Output pane?
![image](https://user-images.githubusercontent.com/2644648/122590558-93a73980-d016-11eb-9ece-34467bcd9fc8.png)

**Comment by samrat-gavale** [comment] 2021-06-18 16:30
@TylerLeonhardt - the output in Microsoft Authentication pane is `[Error  - 16:27:27.734] Getting token failed: Error: Unable to transform input.` This error isn't output immediately, but ~2 minutes after the editor is reloaded. The accounts menu on bottom left is suck in 'Loading..' state for that 2 minutes duration.

**Comment by TylerLeonhardt** [comment] 2021-06-18 20:27
This is a duplicate of #117362

**Closed by TylerLeonhardt** 2021-06-18 20:27 UTC
Labels: authentication, bug
