### ISSUE TITLE
renameOnType does not work with multiple cursors

### ISSUE THREAD

**Issue by jjspace** [microsoft/vscode#100977] opened 2020-06-24 19:28 UTC
- VSCode Version: 1.46.1
- OS Version: Fedora 30

Steps to Reproduce:

1. Create a new HTML file and paste the code below
    ```
    <div class="test"></div>
    <div class="test"></div>
    ```
2. create a cursor at the same place in both opening or closing tags
3. Change the tag in any way
4. The first div's tags are updated for each cursor, the second div's tags are not. This functionality worked with the `Auto Rename Tags` extension

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2020-06-25 09:00
duplicate of https://github.com/microsoft/vscode/issues/88127

**Closed by aeschli** 2020-06-25 09:00 UTC
Labels: editor-synced-region
