### ISSUE TITLE
New windows do not respect `recentlyUsedByPrefix`

### ISSUE THREAD

**Issue by boringwong** [Microsoft/vscode#59691] opened 2018-09-30 08:46 UTC
- VSCode Version: 1.27.2
- OS Version: macOS 10.14

Steps to Reproduce:

1. Type `if` in a `.js` file
2. Select the second suggestion (`if` statement)
3. Type `if` again in another place, see the second suggestion is selected automatically
4. Open a new window (<kbd>⌘</kbd> <kbd>Shift</kbd> <kbd>N</kbd>)
5. Do step 1, the selected suggestion is the first one

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment] 2018-10-01 07:09
/duplicate of https://github.com/Microsoft/vscode/issues/55834

**Closed** 2018-10-01 07:09 UTC
Labels: *duplicate, editor, editor-brackets
