### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by child-duckling** [microsoft/vscode#133048] opened 2021-09-14 01:52 UTC
Issue Type: <b>Bug</b>

Was just working on some JS when my intelliSense died. I restarted VS Code and it didn't last 2 minutes before dying again. Tried it on VS Code Insiders and it did the same thing.

I don't really know how to reproduce it since I was just doing normal JS things and using an node.js CLI tool

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 7, 5|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id f9a7647b-0469-4871-9faf-bf64b623704d|
|Screen Reader|no|
|VM|0%|

macOS Version: 12.0 (Monterey) Beta (21A5506j)
VS Code Version: `
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
`
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
namespace|adr|1.1.2
Bookmarks|ale|13.2.1
project-manager|ale|12.4.0
copy-relative-path|ale|0.0.2
shaderlabvscodefree|aml|1.2.8
electron-snippets|ant|1.0.3
vscode-tailwindcss|bra|0.6.14
simple-react-snippets|bur|1.2.4
unity-code-snippets|cem|0.1.0
npm-intellisense|chr|1.4.0
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
githistory|don|0.6.18
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
eppz-code|epp|1.2.52
vsc-material-theme-icons|equ|2.2.0
prettier-vscode|esb|8.1.0
discode|eve|1.1.3
unity-dev-pack|fab|2.4.1
git-project-manager|fel|1.7.1
vscode-solution-explorer|fer|0.4.4
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
unity-pack-vs-code|fra|0.0.4
auto-using|Fud|0.7.15
vscode-pull-request-github|Git|0.30.0
todo-tree|Gru|0.0.214
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
applescript|idl|0.21.0
monkey-patch|ioc|0.1.15
sf-symbols|j-f|2.1.0
webpack|jer|2.2.0
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.20
vscode-codemetrics|kis|1.24.0
unity-code-snippets|kle|1.3.0
vscode-github|Kni|0.30.6
electron-debug|kod|18.11.1
unity-snippets-modified|lio|0.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.35
fluent-icons|mig|0.0.12
vscode-nbt|Mis|0.6.2
vscode-filesize|mkx|3.1.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
vscode-typescript-next|ms-|4.5.20210913
vsliveshare|ms-|1.0.4836
vscode-react-native|msj|1.6.1
color-highlight|nau|2.5.0
vscode-streamdeck|nic|4.1.6
indent-rainbow|ode|8.0.0
minecraft-essentials-extension-pack|pah|1.0.1
vscode-versionlens|pfl|1.0.9
unity-toolbox|pix|1.0.6
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
vscode-unitymeta|PTD|0.0.7
explorer-exclude-vscode-extension|Red|1.2.0
c-sharp-utilities|rev|0.3.2
LiveServer|rit|5.6.1

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by child-duckling** [comment] 2021-09-14 02:04
Log
```
[2021-09-13 18:45:14.341] [renderer1] [error] write EPIPE: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at v.write (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:465297)
    at d.write (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:453678)
    at d.sendRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:456093)
    at d.sendNextRequests (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:455874)
    at dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:454343)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:453377
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at m.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:464128)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:463775)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-09-13 18:48:26.718] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
    at w.service (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:492121)
    at w.executeImpl (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500654)
    at w.executeAsync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500525)
    at new S (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:443896)
    at Function.executeGetErrRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:444085)
    at b.sendPendingDiagnostics (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:448462)
    at t.Delayer.task (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:447802)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:507565
    [2021-09-13 18:54:53.526] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
    at w.service (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:492121)
    at w.executeImpl (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500654)
    at w.execute (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500184)
    at o.provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:363847)
    at w.provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:167276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:192125
    at xe._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:187656)
    at xe.$provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:192103)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11838)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
    at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-09-13 18:54:54.088] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
    at w.service (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:492121)
    at w.executeImpl (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500654)
    at w.executeAsync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500525)
    at new S (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:443896)
    at Function.executeGetErrRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:444085)
    at b.sendPendingDiagnostics (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:448462)
    at t.Delayer.task (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:447802)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:507565
[2021-09-13 18:54:55.227] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
    at w.service (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:492121)
    at w.executeImpl (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500654)
    at w.execute (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:500184)
    at o.provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:363847)
    at w.provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:167276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:192125
    at xe._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:187656)
    at xe.$provideDocumentHighlights (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:192103)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11838)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
    at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    ```

**Comment by mjbvz** [comment] 2021-09-14 22:10
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?


If so, please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by matschaffer** [comment] 2021-09-15 05:57
I've been running into something a little like this. Specifically when coding on https://github.com/elastic/kibana over a Remote-SSH connection.

![Screen Shot 2021-09-15 at 14 55 26](https://user-images.githubusercontent.com/690/133378614-7f941dba-79a0-4133-8f21-938ee7d3236b.png)

I'll set `"typescript.tsserver.log": "verbose"` and see if anything interesting turns up.

**Comment by matschaffer** [comment] 2021-09-15 06:05
One thing I noticed initially is that I seem to have two tsserver.js instances running:

```
[Info  - 06:00:02.86] Using tsserver from: /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 06:00:02.88] <syntax> Log file: /home/matschaffer/.vscode-server/data/logs/20210915T055956/exthost1/vscode.typescript-language-features/tsserver-log-VXsl3n/tsserver.log
[Info  - 06:00:02.88] <syntax> Forking...
[Info  - 06:00:02.96] <syntax> Starting...
[Info  - 06:00:02.98] <semantic> Log file: /home/matschaffer/.vscode-server/data/logs/20210915T055956/exthost1/vscode.typescript-language-features/tsserver-log-hDNY3m/tsserver.log
[Info  - 06:00:02.98] <semantic> Forking...
[Info  - 06:00:02.105] <semantic> Starting...
```

```
$ ps wuax | grep lib/tsserver.js
matscha+   84950  0.9  0.1 674188 125432 ?       Sl   06:00   0:02 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=3072 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1001/7d449336a67e0f933dd1/tscancellation-3834cc85a5d59d2fcd6c.tmp* --logVerbosity verbose --logFile /home/matschaffer/.vscode-server/data/logs/20210915T055956/exthost1/vscode.typescript-language-features/tsserver-log-VXsl3n/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
matscha+   84956 19.6  1.5 1586988 1049184 ?     Sl   06:00   0:45 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=3072 /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1001/7d449336a67e0f933dd1/tscancellation-9f0ba43f70531ccc21d1.tmp* --logVerbosity verbose --logFile /home/matschaffer/.vscode-server/data/logs/20210915T055956/exthost1/vscode.typescript-language-features/tsserver-log-hDNY3m/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /home/matschaffer/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

Is this expected?

**Comment by mjbvz** [comment] 2021-09-15 23:32
@matschaffer Yes it is expected. If you are seeing crashes, please follow the steps to collect the logs and then open a new issue with them so we can investigate

**Comment by matschaffer** [comment] 2021-09-16 00:23
Will do! I turned them on, restarted both vscode and killed the remote ssh server. Will post if/when I see it happen again with logs in hand this time. I don't think removing all extensions is feasible since I can't effectively use vscode for work without the extensions.

**Comment by matschaffer** [comment] 2021-09-16 06:58
Hey @mjbvz it finally happened at the end of the day. I have the log but even zipped it's 4GB. Is there a microsoft upload server I could put them on for you?

**Comment by jakub-g** [comment] 2021-09-21 10:53
It just happened to me, check if this isn't your issue: https://github.com/microsoft/vscode/issues/133515

**Comment by mjbvz** [comment] 2021-09-27 18:33
Closing as we need logs/steps to reproduce from the original poster

**Closed by mjbvz** 2021-09-27 18:33 UTC
Labels: needs more info
