### ISSUE TITLE
Drop support for macOS 10.11 and 10.12

### ISSUE THREAD

**Issue by veriotis** [microsoft/vscode#123374] opened 2021-05-08 23:30 UTC
- VS Code Version: 1.56.0
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:

1. Try to start Code on OSX 10.11.6 (El Capitan)

Does this issue occur when all extensions are disabled?: Yes

See the attached **crash_report.txt** file
[crash_report.txt](https://github.com/microsoft/vscode/files/6446704/crash_report.txt)

**Comment by JohnLukeBentley** [comment] 2021-05-09 11:21
I've been getting Visual Studio Code freezes too which may be Electron related.

* OS Version: Windows 10 Pro 64bit, 20H@, 19042.928
* Visual Studio Code: 1.56.0

My symptoms are that VSC works fine for some days then, all of a sudden, freezes on startup. After killing it via task manager rerunning results in a freeze on startup. The uninstaller freezes (so that I can't uninstall it). The installer freezes (so that I can't reinstall it, over an existing install). Another electron based app, Typora, opens but menu command can't work (so Typora sort of freezes too).

Other parts of Window become frozen. For example (Win Search > "Restore" > "Create a restore point" > The  "System Properties" Dialog becomes frozen).

Restarting Windows doesn't resolve this. Instead, as a temporary work around, I've had to:
* Restore Windows to an earlier restore point that avoids going through "System properties" (Windows Start > Settings > Update & Security > Recovery > Advanced Start-up [Restart now] > {Once restarted choose to recover from a restore point}); and
* Immediately upon restart uninstall my Electron apps (Visual Studio Code and Typora).

My suspicions are there is some interaction that is causing the freeze, between one or more of the following:

* Electron.
* Windows Update.
* The Powershell extension (this was recently installed).
* The Visual Studio Code terminal (when it tries to load a Powershell session).
* That my version of Powershell is installed via the Store.
* Windows Terminal, Preview edition.

I've tried opening VSC with `code --disable-gpu`, as advised at https://code.visualstudio.com/docs/supporting/faq#_vs-code-gets-unresponsive-right-after-opening-a-folder. That didn't work. I'm on Nvidia drivers 456.71 with a GTX 1660 TI. And downloading to the latest drivers is something I'm about to do.

These problems occur on one of my machines (my desktop) but not another (my laptop)

So, just as for @veriotis's post, there's not much to go on to help anyone who isn't experiencing a freeze to be able to reproduce the problem. And my freezes might have a different cause to the one @veriotis is experiencing. But hopefully I've provided some clues that someone else experiencing a freeze might pick up on. That is, to help us narrow in on a cause.

**Comment by deepak1556** [comment] 2021-05-11 12:47
@veriotis can you attach the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

**Comment by deepak1556** [comment] 2021-05-11 12:48
@JohnLukeBentley can you please open a separate issue, I am gonna track this for the crash on macOS `10.11`

**Comment by deepak1556** [comment] 2021-05-11 13:13
The original issue posted here is a crash on startup due to `SIGILL` which is different from the issue you are experiencing. To get logs specific to your issue, it is better to track them separately. Thanks for understanding.

**Comment by JohnLukeBentley** [comment] 2021-05-11 13:21
@deepak1556, ok noted that they are separate issues (trusting what you can see and without, myself, knowing what `SIGILL` is). I'll post as separate issue, with logs. But that will occur in the fullness of time: at the moment I'm in the middle of something which requires me to avoid the borking of my machine this issue causes.

**Comment by veriotis** [comment] 2021-05-11 19:11
@deepak1556 Here you have the dmp-file based crash report as a zip-file, see the supplied zip attachment.

VSC v1.56.0 always crashes under MacOS 10.11.6 (El Capitan) on startup, no matter if with or without enabled plugins. - The previous version 1.55.x worked fine instead. The MacOS generated crash report always tells that Elecron crashes the new v1.56.0!  

[crash_report-vsc_1.56.0.zip](https://github.com/microsoft/vscode/files/6461444/crash_report-vsc_1.56.0.zip)

**Comment by veriotis** [comment] 2021-05-12 15:52
@deepak1556

- VS Code Version: 1.56.1
- OS Version: OSX El Capitan 10.11.6
- For the DMP-file see the attached zip file

[vsc-1.56.1-crash.zip](https://github.com/microsoft/vscode/files/6467379/vsc-1.56.1-crash.zip)

It looks like the Electron crash reason is always associated with **spdlog.node** logging!

**Comment by schroef** [comment] 2021-05-12 17:04
> @veriotis can you attach the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

Im also seeing instant crash using 10.11.6
after using this code i get this prompted in the terminl
```
[0512/130304.252922:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7fff577e0000, 0x2000): (os/kern) invalid address (1)
[0512/130304.935965:ERROR:http_transport_mac.mm(283)] A server with the specified hostname could not be found. (NSURLErrorDomain -1003)
```

**Comment by deepak1556** [comment] 2021-05-12 21:51
@veriotis can you try with the latest insiders https://code.visualstudio.com/insiders/ which has updated spdlog version.

@schroef it should either be `code --crash-reporter-directory /tmp/vscode-crash` or `open -b com.microsoft.VSCode --args --crash-reporter-directory /tmp/vscode-crash`

**Comment by veriotis** [comment] 2021-05-12 22:53
@deepak1556 I've just tried with the latest insiders release, but it's the same behavior and crashing too in the **_spdlog.node_** context ...

[vsc-insiders-crash.zip](https://github.com/microsoft/vscode/files/6469436/vsc-insiders-crash.zip)

> Operating system: Mac OS X
>                   10.11.6 15G22010
> ...
> 
> Crash reason:  EXC_BAD_INSTRUCTION / EXC_I386_INVOP
> Crash address: 0x11a2a44c3
> Process uptime: 1 seconds
> 
> Thread 0 (crashed)
>  0  spdlog.node + 0xa4c3
>     rax = 0x0000000000000001   rdx = 0x0000000000000000
>     rcx = 0xffffffffffffff01   rbx = 0x00007fa960c8d6f0
>     rsi = 0x0000000000000038   rdi = 0x0000000116b04a00
>     rbp = 0x00007fff51712c90   rsp = 0x00007fff51712c40
>      r8 = 0x0000000000000010    r9 = 0x00000000fffffe00
>     r10 = 0x0000000000000009   r11 = 0x00007fa960c00000
>     r12 = 0x00007fa960c8d700   r13 = 0x000000011a2dc0f8
>     r14 = 0x0000000000000000   r15 = 0x9ae16a3b2f90404f
>     rip = 0x000000011a2a44c3
>     Found by: given as instruction pointer in context
>  1  spdlog.node + 0x9eb8
>     rbp = 0x00007fff51712d20   rsp = 0x00007fff51712ca0
>     rip = 0x000000011a2a3eb8
>     Found by: previous frame's frame pointer
>  2  spdlog.node + 0x8ac3
>     rbp = 0x00007fff51712d50   rsp = 0x00007fff51712d30
>     rip = 0x000000011a2a2ac3
>     Found by: previous frame's frame pointer
>  3  ...

**Comment by digital-pers0n** [comment] 2021-06-06 18:16
The problem is with binary node modules located in VSCode.app/Contents/Resources/app/node_modules.asar.unpacked/
spdlog, native-keymap and vscode-sqlite3 were compiled with SSE4.2 optimizations and crash VSCode on older macs that can't upgrade beyond macOS 10.10 and 10.11 due to lack of SSE4 support
Node modules must be rebuild with -mcpu=core2 or macOS 10.10 / 10.11 (10.12 probably too) support should be removed.
Rebuild may be complicated for universal binary, but should be easy for x86_64-only build.

**Comment by veriotis** [comment] 2021-06-16 07:52
@digital-pers0n If a build/compilation with SSE4.2 optimizations is the cause of evil here, then the responsible people for the VSCode Mac related build processes should take this into account. Otherwise VSCode isn't OSX 10.11.6 compliance at all any more and thus not usable on these MacOS systems.

@deepak1556 You should cross-check this (_SSE4.2 optimizations_) with the Mac related build process settings, since it probably influences the overall app behavior for Mac OS systems <= 10.12 then here.

BTW nothing changed in this behavior so far for VSCode v.1.57, same sort of crashing, thus actual VSCode versions are unusable on OSX 10.11.6 (El Capitan) systems!

**Comment by ThakurKarthik** [comment] 2021-09-19 07:06
@veriotis just checking since the issue is `> 4 months` old, are you still facing the issue in the latest build ? If not we can close this I guess.

**Comment by JohnLukeBentley** [comment] 2021-09-19 07:26
Noting I'm not the OP and @deepak1556's earlier request to me was reasonably to open a separate issue (given I'm on Windows rather than the OP's OSX), I'll mention that I tracked my issues down, about those 4 months ago, to a Sync problem. That is, I got so far as establishing that turning on Sync Settings caused the freeze (both under VSC and Preview VSC). Since then, out of fear and a need to spend my time elsewhere, I've kept Sync Settings off.

So if anyone was highly motivated to try to reproduce a freeze with Sync Settings on, they'd be doing us all a great service. But, with respect to this sync issue, it would be reasonable to close the current issue on the grounds it's encumbent on me to open a new one and try to reproduce the freeze under the latest version(s) of VSC.

**Comment by headkit** [comment] 2021-11-25 20:45
Still (or again) crashes on BIg Sur 16'' Macbook Pro. 

When I start VSCode from within Applicatiosn folder, it crashes after startup. If I start it from another folder, it runs - how comes?

**Comment by headkit** [comment] 2021-11-25 20:49
Still (or again) crashes on BIg Sur 16'' Macbook Pro. 

When I start VSCode (1.6.1) from within Applicatiosn folder, it crashes after startup. If I start it from another folder, it runs - how comes?

**Comment by deepak1556** [comment] 2023-01-17 11:22
With Electron 22, `LSMinimumSystemVersion` is 10.13. Following are the action items for dropping support 

**January milestone:**

- [ ] Push EOL message via top status bar and notification
- [ ] Make relevant changes in VSCode and Server to push the above message but do not state it is the last release
- [ ] (Optional) Make the changes generic to allow for future version updates
- [ ] @isidorn to help with updating requirements and FAQ section in the website

**February milestone:**

- [ ] Flip switch in update server to disable updates

**Closed** 2023-03-22 07:59 UTC
Labels: debt, vscode-website, electron-22-update
