### ISSUE TITLE
4 VS Code instances when launching from Dock on Mac OS

### ISSUE THREAD

**Issue by zomars** [microsoft/vscode#139588] opened 2021-12-21 17:42 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Open VSCode from Mac OS Dock or `code` command.
2. 4 instances are opened each time.

https://user-images.githubusercontent.com/3504472/146974687-027c7ebe-ef03-42eb-84a2-83f83bf08085.mov

**Comment by IllusionMH** [comment] 2021-12-21 18:00
Looks like duplicate of #138712

**Comment by zomars** [comment] 2021-12-21 18:26
It's not, this is happening without any extensions running @IllusionMH

**Comment by zomars** [comment] 2022-01-19 19:16
It's getting worse! 

![image](https://user-images.githubusercontent.com/3504472/150198862-927c6cb1-885d-4671-a4ad-c7297e5b9759.png)

Every couple of minutes another instance just magically appears.

**Comment by zomars** [comment] 2022-01-19 19:27
This is what Log (Main) shows:

```
[2022-01-19 12:21:10.836] [renderer1] [error] [Extension Host] (node:18464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
[2022-01-19 12:21:33.049] [renderer1] [warning] UNRESPONSIVE extension host, 'vscode.typescript-language-features' took 28% of 1590.663ms, saved PROFILE here: 'file:///var/folders/_6/lkh477rx2fj076xzrzv32rd80000gn/T/exthost-ae069e.cpuprofile' [{"id":"christian-kohler.npm-intellisense","total":880,"percentage":0},{"id":"gc","total":40095,"percentage":3},{"id":"jpoissonnier.vscode-styled-components","total":2233,"percentage":0},{"id":"Orta.vscode-jest","total":217124,"percentage":14},{"id":"program","total":891,"percentage":0},{"id":"self","total":324205,"percentage":20},{"id":"sissel.shopify-liquid","total":13363,"percentage":1},{"id":"VisualStudioExptTeam.vscodeintellicode","total":23722,"percentage":1},{"id":"vscode.microsoft-authentication","total":83198,"percentage":5},{"id":"vscode.npm","total":30732,"percentage":2},{"id":"vscode.typescript-language-features","total":447434,"percentage":28},{"id":"yzhang.markdown-all-in-one","total":231014,"percentage":15},{"id":"Zignd.html-css-class-completion","total":175228,"percentage":11}]
[2022-01-19 12:21:44.387] [renderer1] [warning] UNRESPONSIVE extension host, 'wix.vscode-import-cost' took 58% of 2568.695ms, saved PROFILE here: 'file:///var/folders/_6/lkh477rx2fj076xzrzv32rd80000gn/T/exthost-72a6ca.cpuprofile' [{"id":"ban.spellright","total":66368,"percentage":3},{"id":"gc","total":38808,"percentage":2},{"id":"kortina.vscode-markdown-notes","total":165917,"percentage":6},{"id":"program","total":40317,"percentage":2},{"id":"self","total":40543,"percentage":2},{"id":"sissel.shopify-liquid","total":885,"percentage":0},{"id":"vscode-icons-team.vscode-icons","total":714259,"percentage":28},{"id":"vscode.typescript-language-features","total":14877,"percentage":1},{"id":"wix.vscode-import-cost","total":1485819,"percentage":58}]
[2022-01-19 12:21:51.857] [renderer1] [warning] UNRESPONSIVE extension host, 'esbenp.prettier-vscode' took 66% of 3657.454ms, saved PROFILE here: 'file:///var/folders/_6/lkh477rx2fj076xzrzv32rd80000gn/T/exthost-994371.cpuprofile' [{"id":"eamodio.gitlens","total":1010709,"percentage":28},{"id":"esbenp.prettier-vscode","total":2412513,"percentage":66},{"id":"gc","total":224949,"percentage":6},{"id":"self","total":8253,"percentage":0}]
[2022-01-19 12:21:52.548] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:21:53.905] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:01.141] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:05.700] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:05.782] [renderer1] [warning] UNRESPONSIVE extension host, 'esbenp.prettier-vscode' took 37% of 4577.363ms, saved PROFILE here: 'file:///var/folders/_6/lkh477rx2fj076xzrzv32rd80000gn/T/exthost-25e29d.cpuprofile' [{"id":"ban.spellright","total":4435,"percentage":0},{"id":"bierner.markdown-mermaid","total":1320,"percentage":0},{"id":"bradlc.vscode-tailwindcss","total":3545,"percentage":0},{"id":"dbaeumer.vscode-eslint","total":46855,"percentage":1},{"id":"eamodio.gitlens","total":209642,"percentage":5},{"id":"esbenp.prettier-vscode","total":1693843,"percentage":37},{"id":"gc","total":208776,"percentage":5},{"id":"GitLab.gitlab-workflow","total":108196,"percentage":2},{"id":"GraphQL.vscode-graphql","total":576,"percentage":0},{"id":"kortina.vscode-markdown-notes","total":314764,"percentage":7},{"id":"ms-vscode-remote.remote-containers","total":58130,"percentage":1},{"id":"Orta.vscode-jest","total":456159,"percentage":10},{"id":"program","total":175027,"percentage":4},{"id":"self","total":820861,"percentage":18},{"id":"VisualStudioExptTeam.vscodeintellicode","total":7377,"percentage":0},{"id":"vscode-icons-team.vscode-icons","total":6880,"percentage":0},{"id":"vscode.git","total":155376,"percentage":3},{"id":"vscode.github-authentication","total":47657,"percentage":1},{"id":"vscode.json-language-features","total":183352,"percentage":4},{"id":"vscode.merge-conflict","total":478,"percentage":0},{"id":"vscode.typescript-language-features","total":1275,"percentage":0},{"id":"vsls-contrib.gitdoc","total":6456,"percentage":0},{"id":"wix.vscode-import-cost","total":201,"percentage":0},{"id":"yzhang.markdown-all-in-one","total":3204,"percentage":0},{"id":"Zignd.html-css-class-completion","total":62772,"percentage":1}]
[2022-01-19 12:22:09.175] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:11.221] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:12.952] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:14.469] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:16.025] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:17.683] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:19.069] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:20.606] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:22.189] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:23.633] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:25.117] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:26.621] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
[2022-01-19 12:22:28.125] [renderer1] [error] ENOENT: no such file or directory, open 'rendererLog': Error: ENOENT: no such file or directory, open 'rendererLog'
```

**Comment by zomars** [comment] 2022-01-21 17:42
Seems like the extension host is running on another instance:

https://user-images.githubusercontent.com/3504472/150574748-e775533c-64cd-4940-a1ca-faa7d6a77fd4.mov

**Comment by hazarek** [comment] 2022-02-22 11:07
All extensions are disabled and the new icon is still bouncing when a file is opened with the terminal in the same workspace. disappears in a few seconds

**Comment by deepak1556** [comment] 2022-12-07 11:45
Can you check if the issue is present with latest insiders https://code.visualstudio.com/insiders/ ?

**Closed** 2022-12-08 03:00 UTC
Labels: info-needed
