### ISSUE TITLE
Git doesnt' load at all when clicking on the Git icon in the activity bar.

### ISSUE THREAD

**Issue by Juansero29** [Microsoft/vscode#23265] opened 2017-03-27 09:23 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Install Git version 2.12.0.windows.1
2. Install Visual Studio Code.
3. Click on the Git icon on the activity bar.

It shows a forever-turning [infinite loading animation](https://gyazo.com/7d1fcb43cfc4c31f06a534e94677c1a8). I can't access git via this icon but I can do it from the console.

**Comment by joaomoreno** [comment] 2017-03-28 06:49
Was it working before? Did it stop working all of a sudden?

If you open the `Developer Tools`, do you see any errors?

If you try our [insider release](https://code.visualstudio.com/insiders), does it work?

**Comment by Juansero29** [comment] 2017-03-28 17:02
It was working about a month ago. It stopped working all of a sudden.
I analyzed some elements from the Developer Tools window but it doesn't show any particular errors. [Here's proof](https://gyazo.com/86d19d22903e320b7db726f488302395).

With the insider release it does actually work, I think I will continue to use it. (It would be good however to look into this problem and avoid other people to have it).

**Comment by joaomoreno** [comment] 2017-03-29 07:34
The next stable (which will be released next week) is coming with a brand new Git story. This is what currently runs in the Insiders. So if that works out for you, I'll close this as a duplicate of #22131

**Closed by joaomoreno** 2017-03-29 07:34 UTC
Labels: needs more info
