### ISSUE TITLE
Explorer: undo/redo/undo leaves files empty when deleting

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111162] opened 2020-11-23 07:26 UTC
Steps to Reproduce:

1. delete file(s) from explorer
2. undo
3. redo
4. undo

=> 🐛  file(s) is empty

**Comment by isidorn** [comment] 2020-11-23 09:23
Thanks. I can reproduce.

**Comment by isidorn** [comment] 2020-11-23 09:52
The reason for this is the `undoesCreateOperation` from [here](https://github.com/microsoft/vscode/blob/0a78fe165a37e264e8ade282cdb2f3d340968baa/src/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.ts#L167).
I am not 100% sure why we have that check. I have verified that removing it, this issue gets fixed.
Maybe there was a concern that we do not store too many contents in memory.

Let's also assign to @jrieken to see what he says

**Comment by jrieken** [comment] 2020-11-24 08:32
That flag was added for https://github.com/microsoft/vscode/issues/107379. Things are complex and depends on auto-save and such but the essence is that a delete knows if it undoes create (empty) operation and in that case its undo doesn't restore the contents.

**Comment by isidorn** [comment] 2020-11-24 08:49
@jrieken ok, I also got a sense that it was introduced on purpose. So it seems to be a designed limitation to fix that other issue.
If there is no better way to fix that other issue, I am fine with living with the limitation explained in this issue.

**Comment by jrieken** [comment] 2020-11-25 11:14
I can push a better fix for https://github.com/microsoft/vscode/issues/107379 so that this also works

**Closed** 2020-11-25 11:16 UTC
Labels: bug, file-explorer, undo-redo

**Comment by isidorn** [comment] 2020-11-25 11:17
Great, thanks!
