### ISSUE TITLE
Import auto type bug.

### ISSUE THREAD

**Issue by Hoodgail** [microsoft/vscode#130252] opened 2021-08-06 11:02 UTC
LOL WHAT IS THIS 😂😂
![image](https://user-images.githubusercontent.com/45743294/128500933-11096892-bcad-4c5d-9833-93d02c14b63d.png)

`c:` wouldn't even work

but why didn't it just type `../index.js`

**Comment by CodeCrazy-ywt** [comment] 2021-08-08 03:54
If I got it right, this user seems to be asking a feature -- import relative paths instead of absolute paths.

**Comment by mjbvz** [comment] 2021-08-09 20:58
Please fill in the issue template and share steps to reproduce the issue

**Comment by mjbvz** [comment] 2021-08-16 21:44
Closing as not actionable without a minimal example that demonstrates the issue

**Closed by mjbvz** 2021-08-16 21:44 UTC
Labels: needs more info
