### ISSUE TITLE
Git - un(stage) selected ranges does not respect file encoding setting

### ISSUE THREAD

**Issue by martinhoess** [microsoft/vscode#169745] opened 2022-12-21 14:03 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.74.0 (system setup)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Settings -> "files.encoding": "windows1252" (either workspace or user or both)
2. open/create new file with encoding windows1252
3. enter some umlauts (äöüßÄÖÜ and some text)
![image](https://user-images.githubusercontent.com/47973549/208922624-6f8adafd-e289-4de0-a9e9-b1f13ace7bb8.png)
4. stage the changes
5. open changes in diff
6. mark some of the changes and select "unstage selected ranges"
7. now the content of the staged changes is trash because the file got reencoded
![image](https://user-images.githubusercontent.com/47973549/208923243-be64b620-ba6a-451d-aaff-a05188aaef1b.png)

**Comment by martinhoess** [comment] 2024-04-16 15:57
❗ The problem has become even more prominent with 1.88.1 ("Diff Editor Stage/Revert Selection Buttons") because the button  for staging is now in the differ UI which has the same problem as described above

**Comment by lszomoru** [comment] 2024-12-18 15:24
Closing as duplicate of [#111915](https://github.com/microsoft/vscode/issues/111915)

**Closed by lszomoru** 2024-12-18 15:24 UTC
Labels: bug, git
