### ISSUE TITLE
Very High Memory  与vscode 版本有关

### ISSUE THREAD

**Issue by k0204** [Microsoft/vscode#71587] opened 2019-04-02 07:59 UTC
vscode 1.31.1 版本内存正常释放.  常驻内存:400mb
vscode 1.32 版本内存不能正常释放. 常驻内存:1.5G+

在vscode 早期版本也出现过 .
这不是一个插件存在这个问题.应该是vscode内部处理内存释放有关!

**Comment by mjbvz** [comment] 2019-04-02 17:29
> Vscode 1.31.1 version memory is released normally.
> Resident Memory: 400mb Vscode version 1.32 memory does not release properly.

> Resident Memory: 1.5G+
> Earlier versions of Vscode also appeared. This is not a plug-in that has this problem. should be vscode internal processing memory release related!

**Comment by mjbvz** [comment] 2019-04-02 17:29
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by k0204** [comment] 2019-04-02 17:36
同样的插件代码,为什么在不同版本内存会这么大的不同.  插件中添加了很多的 CompletionItem 如果api有修改在哪可以找到对应的文档?

**Comment by mjbvz** [comment] 2019-04-02 17:39
> The same plug-in code, why the memory in different versions will be so different.
A lot of CompletionItem have been added to the plug-in if the API has been modified where can I find the corresponding document?

Can you please test using the insiders build. If this only shows up when extension are enabled, please file an issue against that extension

**Comment by k0204** [comment] 2019-04-02 17:46
insiders build 同样存在此问题.

**Comment by k0204** [comment] 2019-04-02 17:49
我明天提供一个工程 复现这个问题吧！

**Comment by k0204** [comment] 2019-04-03 11:15
是否和 Electron version  有关呢!
https://github.com/electron/electron/issues/17213

**Comment by mjbvz** [comment] 2019-04-03 17:57
Can you please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by aeschli** [comment] 2019-04-15 15:24
Closing due to lack of additional information.

**Closed by aeschli** 2019-04-15 15:24 UTC
Labels: needs more info
