### ISSUE TITLE
VS Code lagging while loading/opening.

### ISSUE THREAD

**Issue by ManiChandana1215** [microsoft/vscode#181646] opened 2023-05-05 16:06 UTC
Type: <b>Performance Issue</b>

In my laptop all other apps are loding well without any lagging. Only VS Code is not loading properly.It is loading very slowly to the point my laptop is showing whether I want to close this app due to slow loading.I have uninstalled it and installed again hoping I could get rid of this problem but it still remains the same.So I request you to give me a solution.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.75GB free)|
|Process Argv|--crash-reporter-id fd1ce338-eb13-48fa-8632-2552748f6edb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	  2532	code main
    1	   163	  9488	   gpu-process
    0	   198	  9536	window [1] (Welcome - javaf - Visual Studio Code)
    0	    27	 14128	   crashpad-handler
    0	    79	 16056	fileWatcher [1]
    0	    87	 20124	window [2] (Issue Reporter)
    0	   155	 23768	shared-process
    0	    84	 10972	     ptyHost
    0	     5	 21864	       "C:\Program Files\Git\bin\bash.exe" --login -i
    0	    11	 16356	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    0	     6	 24552	       console-window-host (Windows internal process)
    1	   124	 23916	extensionHost [1]
    0	    77	 20108	     electron-nodejs ("C:\Users\manic\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\manic\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=23916)
    0	     5	 22520	     "C:\Program Files\Git\cmd\git.exe" rev-parse --show-toplevel
    0	     2	  3848	       git.exe rev-parse --show-toplevel
    0	    10	  5340	       console-window-host (Windows internal process)
    0	    48	 24316	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - javaf - Visual Studio Code)
|    Folder (javaf): 22 files
|      File types: class(11) java(10)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
auto-rename-tag|for|0.1.10
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.10
java|red|1.18.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30731978

```

</details>

**Comment by chibyk101** [comment] 2023-05-05 19:34
I uninstalled my VSCode a few minutes ago.
After updating to 1.78.0 It kept on crashing and froze my laptop, even when I force shutdown and boot up again, once I opened VScode my system crashed again

**Comment by mjbvz** [comment] 2023-05-09 18:44
Duplicate of #178962

**Closed by mjbvz** 2023-05-09 18:44 UTC
Labels: triage-needed
