### ISSUE TITLE
php user snippets don't work in format example.blade.php

### ISSUE THREAD

**Issue by NoOorZ24** [Microsoft/vscode#24017] opened 2017-04-06 08:47 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-scss|P-de-Jong|0.0.42|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|php-intellisense|felixfbecker|1.1.4|
|laravel-blade|onecentlin|1.8.1|
|preview-vscode|searKing|1.1.5|
|ab-html-formatter|zovorap|0.0.2|;

---

Steps to Reproduce:

1. naming file _example_.blade.php will cause php snippets not to show up on autocomlete while naming 
note: disabling _|laravel-blade|onecentlin|1.8.1|_ doen't make any difference

**Comment by chrmarti** [comment] 2017-04-06 16:51
Could you attach your snippet file and the php file?

**Comment by NoOorZ24** [comment] 2017-04-07 05:45
File doesn't matter because snippet should be used in empty Laravel view file *.blade.php and snippet just should be associated with php extension so what's in it doesn't really matter as well. I solved problem associating *.blade.php file with HTML (in this case works even better than PHP) by:
{
    "files.associations": {
        "*.blade.php": "html"
    }
}

**Comment by jrieken** [comment] 2017-04-11 15:00
@NoOorZ24 what does the lower left corner show when you open these files? how are you trying to add the snippet? Via 'Insert Snippet' or when typing via the suggest ux?

**Comment by jrieken** [comment] 2017-04-13 13:42
This work for me nicely. @NoOorZ24 Please help me further to reproduce this

<img width="571" alt="screen shot 2017-04-13 at 15 40 06" src="https://cloud.githubusercontent.com/assets/1794099/25007098/7cf4c5a6-205f-11e7-88ca-427d447ca88c.png">

**Comment by jrieken** [comment] 2017-04-24 13:14
Closing because this issue is without actionable information.

**Closed by jrieken** 2017-04-24 13:14 UTC
Labels: needs more info, snippets
