### ISSUE TITLE
Setting Sync keeps prompting to Sign In

### ISSUE THREAD

**Issue by VasuInukollu** [microsoft/vscode#118656] opened 2021-03-10 16:47 UTC
Issue Type: <b>Bug</b>

Not able to figure out why this is happening. I have tried relogin multiple times but no luck.

The logs show nothing broken. Everything seem ok.

Output from Microsoft Authentication
```
[Info  - 16:07:57.960] Refreshing token...
[Info  - 16:07:59.124] Token refresh success
[Info  - 16:07:59.138] Token available from cache, expires in 3598986 milliseconds
[Info  - 16:13:15.220] Token available from cache, expires in 3282904 milliseconds
[Info  - 16:13:16.874] Token available from cache, expires in 3281250 milliseconds
[Info  - 16:13:27.566] Token available from cache, expires in 3270558 milliseconds
[Info  - 16:14:17.962] Token available from cache, expires in 3220162 milliseconds
```

VS Code version: Code - Insiders 1.55.0-insider (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f, 2021-03-08T05:13:14.184Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.18GB free)|
|Process Argv|--crash-reporter-id 9d87ec80-aa09-4bab-b1b1-5ba3b7443c05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|11.2.5
vscode-eslint|dba|2.1.16
docs-markdown|doc|0.2.84
xml|Dot|2.5.1
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.17
vs-code-http-server-and-html-preview|Fli|2.2.2
auto-rename-tag|for|0.1.6
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.2.636928669
jupyter|ms-|2021.4.625511240
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.2
azure-account|ms-|0.9.7
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3912
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.4.0
vscode-yaml|red|0.16.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30268769
vscoresta800cf:30265948
vspre833:30267464

```

</details>

**Comment by IllusionMH** [comment] 2021-03-10 17:00
/duplicate of #117903

And fix should be available with next VSCode insiders release (however there were none in last two days)

**Closed** 2021-03-10 17:01 UTC
Labels: *duplicate
