### ISSUE TITLE
"Go Back" changes different window on split view/cloned editors

### ISSUE THREAD

**Issue by pbrezina** [microsoft/vscode#130663] opened 2021-08-12 10:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-1.58.2-1626302881.el8.x86_64
- OS Version: Fedora 34

Steps to Reproduce:

1. Open a file and put cursor on a specific line (line 50)
2. Open the same file in a split view (say right pane) and put cursor to different location (line 10)
3. Open another file in right pane
4. Run "Go Back"

Expected result: The editor from step two is focused on line 10
Actual result: The editor from step one is focused on line 10.

Sometimes I need to have the same file opened in a split view and I want to keep specific location visible in the left editor while working on the file in the right editor. This behavior keeps changing the left view.

**Comment by IllusionMH** [comment] 2021-08-12 10:39
Looks like duplicate of #45233

**Comment by pbrezina** [comment] 2021-08-12 11:06
If I understand correctly the description #45233 wants to have separate history for each editor group. It is similar but not the same. What I see is just unexpected behavior where the history is `File1_A -> File1_B -> File_2` but "Go back" goes to `File1_A` instead of `File1_B`.

#45233 seems to be a feature requests where this ticket is a bug report.

**Comment by pbrezina** [comment] 2021-08-16 10:43
falsefalseI tried to set revealIfOpened to false, but it did not help. The behavior is still the same (at least with the steps from this issue description).

I think both mentioned issues look similar but different in the core.

- https://github.com/microsoft/vscode/issues/45233 is similar but feels very different to me
- https://github.com/microsoft/vscode/issues/9526 looks very similar, but the expectation is different (my expecation to step back in history would be to select line 4 in editor 2; but the report wants to go back in the history of the selected editor only)

**Comment by bakhtiyarneyman** [comment] 2021-09-16 23:53
`revealIfOpened` didn't help. Put explicitly, I would like the global navigation history to record the id of the editor and the editor group that it went from to the new location. Then when "go back" is being executed, it should try to go to that particular editor. If it fails, it should reopen the editor in the same group which owned the now unavailable editor.

**Comment by hmijail** [comment] 2021-09-23 02:49
Possibly related: when starting a C# debugging session with split editors open, a breakpoint / exception causes the editor to scroll to the triggering source line. This scrolling happens in all split editors at once, which reduces the usefulness of having multiple editors.

**Closed** 2021-10-18 02:31 UTC
Labels: feature-request, workbench-history
