### ISSUE TITLE
Normal hover sticks even after releasing alt and moving cursor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107698] opened 2020-09-29 13:17 UTC
Testing #107156

- Start debugging and hit a breakpoint
- Hover on any variable to get debug hover
- Press `alt` - you see normal hover
- release `alt` 🐛 normal hover sticks for a while and does not got off even after moving cursor.

**Comment by isidorn** [comment] 2020-09-29 13:19
Yeah duplicate of https://github.com/microsoft/vscode/issues/107667

**Closed by isidorn** 2020-09-29 13:19 UTC
