### ISSUE TITLE
CustomExecution task never scan task output doesn't work

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#71217] opened 2019-03-26 18:37 UTC
https://github.com/Microsoft/vscode/issues/71089

Version: 1.33.0-insider (user setup)
Commit: b9bcca2b9830df592892d63201704026c18dcbe5
Date: 2019-03-26T08:13:10.146Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18860

---

I hit never scan task output and it created an invalid task.json and didn't actually work when I tried to run the task again:

![image](https://user-images.githubusercontent.com/2193314/55023922-0aca0080-4fbb-11e9-9e4d-d6d17b443f7e.png)

![image](https://user-images.githubusercontent.com/2193314/55023891-01d92f00-4fbb-11e9-9b92-5c75c335c3c9.png)

**Comment by alexr00** [comment] 2019-03-27 08:31
Duplicate of https://github.com/Microsoft/vscode/issues/71179

**Closed** 2019-03-27 08:31 UTC
Labels: *duplicate
