### ISSUE TITLE
Settings editor: Right editor does not update font size on-the-fly

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53298] opened 2018-06-29 06:21 UTC
Issue Type: <b>Bug</b>

- Open (old) settings editor
- Change font size
- Observe: Only the left editor changes its font size, the right one does not.

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:11:09.274Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
rest-client|hum|0.19.0
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-cosmosdb|ms-|0.7.2
azure-account|ms-|0.4.1
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
debugger-for-chrome|msj|4.7.0
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0

</details>

**Comment by sandy081** [comment] 2018-06-29 07:36
Duplicate of #52105

**Closed** 2018-06-29 07:37 UTC
Labels: *duplicate, settings-editor
