### ISSUE TITLE
Unable to hide the ugly sidebar with the buttons

### ISSUE THREAD

**Issue by Silvery-Corgan** [Microsoft/vscode#64988] opened 2018-12-13 11:24 UTC
- VSCode Version: 1.30.0
- OS Version: MacOS Mojave or Windows 10

Steps to Reproduce:

1. Launch VSCode

![6624dde0-43bd-11e6-8595-c81885ba0dc2](https://user-images.githubusercontent.com/1902795/49935622-d336bd00-fed1-11e8-9143-0d37e8424f4a.png)

2. Sidebar is to the left. Can be moved to the right. Cannot hide it. Settings don't give you the option to do so.

<img width="737" alt="screen shot 2018-12-13 at 12 21 23" src="https://user-images.githubusercontent.com/1902795/49935660-e8135080-fed1-11e8-84ba-010a08e6283c.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment] 2018-12-13 11:49
`activitybar`

**Comment by usernamehw** [comment] 2018-12-13 11:53
/duplicate of https://stackoverflow.com/questions/36314664/how-do-i-hide-the-vs-code-view-bar

**Closed** 2018-12-13 11:53 UTC
Labels: *duplicate, new release
