### ISSUE TITLE
CSS Suggestion Improvment 

### ISSUE THREAD

**Issue by rajnishcoder** [Microsoft/vscode#37887] opened 2017-11-09 06:34 UTC
- VSCode Version:1.17.2
- OS Version: Fedora 26

Steps to Reproduce:

1. Assume I'm writing code in CSS and I'm using width for every class and whenever i typed "wi" It has to show me "width" property first in suggestion instead of "windows" property.
Because it is irritating to type "wi" and select from #3 in suggestion list.
2. It should be in every language. 

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment] 2017-11-09 10:58
duplicate of #22839

**Closed by aeschli** 2017-11-09 10:58 UTC
Labels: css-less-sass, suggest
