### ISSUE TITLE
VSCode does not check for modified files on load which conflicts with it's auto saving of modified files

### ISSUE THREAD

**Issue by greggman** [Microsoft/vscode#42701] opened 2018-02-01 05:29 UTC
- VSCode Version: 1.19.3
- OS Version: N/A

Steps to Reproduce:

1.  Load an exiting file
2. Modify the file
3. Quit VSCode (Cmd+Q or Alt+F4, without saving)
4. Modify the file some other way (echo, cat, **git pull**)
5. Load VSCode

What should happen:

Either:
   Get notified that files on disk are modified. 
Or:
   At Quit time you are told you have modified files and if you don't save them they're lost (prefered)

What happens instead:

You nearly silently lose work.

At this point unlike all other apps and editors I've ever used VSCode has versions of modified files BEFORE step 3 which it magically saved in some temp place.  No message is given that the files on disk changed during that time. This leads to a situation where if you are not ridiculously diligent you'll lose work. For example you start editing and save not realizing vscode didn't load the current version of the file of the disc when it started.

**Comment by bpasero** [comment] 2018-02-01 06:08
Duplicate of https://github.com/Microsoft/vscode/issues/15749 (@Tyriar fyi)

**Closed by bpasero** 2018-02-01 06:08 UTC
Labels: hot-exit
