### ISSUE TITLE
install isort extension (release version) will remove python and pylance extension

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#189836] opened 2023-08-07 12:32 UTC
```
2023-08-07 12:23:13.142 [info] Getting Manifest... ms-python.isort
2023-08-07 12:23:13.612 [error] Failed to install extension. ms-python.isort
2023-08-07 12:23:13.612 [error] Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1590:19)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-08-07 12:23:21.071 [info] Downloaded extension to file:///root/.vscode-server/data/CachedExtensionVSIXs/234d6318-b665-4d1a-b472-f63129db1a0e
2023-08-07 12:23:21.076 [info] Installing extension: ms-python.python
2023-08-07 12:23:21.076 [info] Installing the extension without checking dependencies and pack ms-python.python
2023-08-07 12:23:21.143 [info] Deleted existing extension from disk ms-python.python /root/.vscode-server/extensions/ms-python.python-2023.14.0
2023-08-07 12:23:21.957 [info] Extracted extension to file:///root/.vscode-server/extensions/ms-python.python-2023.14.0: ms-python.python
2023-08-07 12:23:21.960 [info] Renamed to /root/.vscode-server/extensions/ms-python.python-2023.14.0
2023-08-07 12:23:21.966 [info] Extracting extension completed. ms-python.python
2023-08-07 12:23:21.968 [info] Extension installed successfully: ms-python.python
2023-08-07 12:23:21.972 [info] Marked extension as uninstalled ms-python.python-2023.14.0
2023-08-07 12:23:27.961 [info] Downloaded extension to file:///root/.vscode-server/data/CachedExtensionVSIXs/5e7eeb0a-caf7-4790-a0d7-46d553577c2b
2023-08-07 12:23:28.147 [info] Installing extension: ms-python.vscode-pylance
2023-08-07 12:23:28.147 [info] Installing the extension without checking dependencies and pack ms-python.vscode-pylance
2023-08-07 12:23:28.170 [info] Removed the extension from uninstalled list: ms-python.vscode-pylance
2023-08-07 12:23:28.251 [info] Deleted removeExisting extension from disk ms-python.vscode-pylance /root/.vscode-server/extensions/ms-python.vscode-pylance-2023.8.10
2023-08-07 12:23:29.334 [info] Extracted extension to file:///root/.vscode-server/extensions/ms-python.vscode-pylance-2023.8.10: ms-python.vscode-pylance
2023-08-07 12:23:29.340 [info] Renamed to /root/.vscode-server/extensions/ms-python.vscode-pylance-2023.8.10
2023-08-07 12:23:29.341 [info] Extracting extension completed. ms-python.vscode-pylance
2023-08-07 12:23:29.343 [info] Extension installed successfully: ms-python.vscode-pylance
2023-08-07 12:23:29.346 [info] Marked extension as uninstalled ms-python.vscode-pylance-2023.8.11
2023-08-07 12:23:30.144 [info] Downloaded extension to file:///root/.vscode-server/data/CachedExtensionVSIXs/996a3a74-ba23-4c5d-adfa-bdb39dbb59e6
2023-08-07 12:23:30.152 [info] Installing extension: ms-python.isort
2023-08-07 12:23:30.152 [info] Installing the extension without checking dependencies and pack ms-python.isort
2023-08-07 12:23:30.178 [info] Removed the extension from uninstalled list: ms-python.isort
2023-08-07 12:23:30.198 [info] Deleted existing extension from disk ms-python.isort /root/.vscode-server/extensions/ms-python.isort-2023.10.1
2023-08-07 12:23:30.259 [info] Extracted extension to file:///root/.vscode-server/extensions/ms-python.isort-2023.10.1: ms-python.isort
2023-08-07 12:23:30.260 [info] Renamed to /root/.vscode-server/extensions/ms-python.isort-2023.10.1
2023-08-07 12:23:30.260 [info] Extracting extension completed. ms-python.isort
2023-08-07 12:23:30.262 [info] Extension installed successfully: ms-python.isort
```
I see `Deleted existing extension`, `Removed the extension from uninstalled list: ms-python.vscode-pylance`, `Marked extension as uninstalled`. After that, python and pylance extensions are gone.

When I switch to preview version, bug disappears.

**Comment by alexdima** [comment] 2023-08-08 21:22
I could not reproduce. I have tried with the following steps:
* I install the Python and Pylance extensions
* I quit and restart VS Code
* I install the isort extension
* Python and Pylance are still installed and working
* I quit and restart VS Code
* Python and Pylance are still installed and working

Is there anything more to it? Do you have more special setups? Are you using VS Code Remote Extensions or profiles or something more special?

**Comment by alexdima** [comment] 2023-08-08 21:35
I've also tried the steps above in a remote window using Dev Containers, but I still wasn't able to reproduce. Do you have any other hints towards trying to reproduce?

**Comment by chaoedu** [comment] 2023-08-09 08:59
I have the same issue.

**Comment by bpasero** [comment] 2023-08-09 17:40
Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

**Comment by ladyrick** [comment] 2023-08-09 18:38
> Are profiles involved here? Possibly with the option to "Apply extension to all profiles"?

No. Just the default profile. No other profiles. It happens on the ssh-remote environment. And not only “python” and “pylance”. Installing pre-released isort solves python and pylance, but there are still other extensions bothering me and I have not found the workaround solution.

**Comment by joyceerhl** [comment] 2023-08-10 00:46
This may be a duplicate of https://github.com/microsoft/vscode/issues/189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

**Comment by chaoedu** [comment] 2023-08-10 02:20
> This may be a duplicate of #189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

It‘s fixed, thanks a lot.

**Comment by ladyrick** [comment] 2023-08-10 04:39
> This may be a duplicate of #189877. Can you please try out the latest VS Code Insiders and let us know whether it's fixed there: https://code.visualstudio.com/insiders

It's fixed. Thanks.

**Closed** 2023-08-10 06:24 UTC
Labels: info-needed, remote
