### ISSUE TITLE
MacOS 12.0.1: Visual Studio Code Needs To Be Updated

### ISSUE THREAD

**Issue by mahdi-farnia** [microsoft/vscode#136586] opened 2021-11-06 20:49 UTC
Issue Type: <b>Bug</b>

As i run this command in integrated terminal this prompt pops up
```
$ code package.json
```

<img width="372" alt="Screen Shot 1400-08-16 at 00 00 55" src="https://user-images.githubusercontent.com/65429393/140623382-7e1c4fd3-6955-40d1-9b19-0beeb4b46a2e.png">

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:24:41.297Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.59GB free)|
|Process Argv|--crash-reporter-id 3abd098e-8913-45d9-9e68-58217d58edc2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by weinand** [comment] 2021-11-08 11:55
Most likely a duplicate of #134635

**Closed** 2021-11-08 15:33 UTC
Labels: *duplicate
