### ISSUE TITLE
[Custom Editors API] onDidDispose is not always called on WebviewPanel

### ISSUE THREAD

**Issue by KevinWuWon** [microsoft/vscode#88229] opened 2020-01-07 18:55 UTC
- VSCode Version: Built from hash f29b55cc5d20ee2025444c5406655e64e4836963
- OS Version: Mac OS 10.14.6 (18G103)

Steps to Reproduce:

1. Clone https://github.com/mjbvz/vscode-experimental-webview-editor-extension
2. Apply the patch:
```
diff --git a/src/abcEditor.ts b/src/abcEditor.ts
index fe0d5be..1803d64 100644
--- a/src/abcEditor.ts
+++ b/src/abcEditor.ts
@@ -40,6 +40,7 @@ export class AbcEditorProvider implements vscode.WebviewCustomEditorProvider, vs
                 return
             }
             entry.delete(editor);
+            console.log(`removed an entry, ${entry.size} left`)
             if (entry.size === 0) {
                 this.editors.delete(resource.toString());
                 this.models.delete(resource.toString());
@@ -167,7 +168,7 @@ class AbcEditor extends Disposable {
             }
         }));

-        this._register(panel.onDidDispose(() => { this.dispose(); }));
+        this._register(panel.onDidDispose(() => { console.log('onDidDispose'); this.dispose(); }));

         this.update();
     }
```
3. Build and run the extension
4. Open a `test.abc` file
5. Run the Split Editor Right command
6. Close the newly opened pane. Expect `onDidDispose` in the log.  Observe that it doesn't.
7. Close the first pane. Expect "removed an entry, 0 left" in the log.  Observe "removed an entry, 1 left".  As a result, the entry is not deleted from `this.editors` or `this.models`

**Comment by mjbvz** [comment] 2020-01-23 01:32
@bpasero Need your workbench advice on this problem. Here's the root cause of the issue:

1. We don't `dispose` of the split web view input due to this code which checks to see if any matching editor input is still around:
    https://github.com/microsoft/vscode/blob/5e09466b85f2752e875e702d596d06a515ec49c8/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L521

1. A custom editor input match if they have the same resource and view type. However in this case, we always want to dispose of the closed input

Should I try using [`onDidCloseEditor`](https://github.com/microsoft/vscode/blob/714ba18975ceeb2fc0ebb7bbd3964700f1f0c111/src/vs/workbench/browser/parts/editor/editor.ts#L148) to monitor when custom editor inputs close, or do you know of a better approach?

**Comment by bpasero** [comment] 2020-01-23 06:08
@mjbvz it is intentional that `EditorInput's` are not disposed by the workbench if multiple editors are opened with the same matching editor input because the editor does not know if the input is is shared between multiple editors. For example: every file and every untitled editor input is the exact same instance in multiple editors (otherwise each time you click on a file in the explorer a new input would have to be created). So we cannot dispose it unless really the last editor was closed.

If you need to track an editor closing, `onDidCloseEditor` is a good event to check for.

**Closed** 2020-01-24 23:44 UTC
Labels: bug, custom editors
