### ISSUE TITLE
${fileBasenameNoExtension} doesn't get substitued if nested in argument

### ISSUE THREAD

**Issue by bayesrule** [Microsoft/vscode#15937] opened 2016-11-23 03:34 UTC
Hi,

The newly added variable ${fileBasenameNoExtension}  (https://github.com/Microsoft/vscode/issues/1104) is not working, please check.

Many thanks!

**Comment by isidorn** [comment] 2016-11-25 09:40
Reproducable steps please. What is the file that you have open, what are you expecting to get returned, what actually gets returned?

Thanks

**Comment by bayesrule** [comment] 2016-11-25 12:03
Hi @isidorn , many thanks for replying. I simply used it in a build task.

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "clenv.bat",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["${file} ${fileBasenameNoExtension}"]
        }
    ]
}
```

Output:
"c:\Users\bayesrule\Desktop\codes\program.c ${fileBasenameNoExtension}" 

${file} = c:\Users\bayesrule\Desktop\codes\program.c

${fileBasenameNoExtension} cannot be recognised at all.

**Comment by isidorn** [comment] 2016-11-25 13:55
That is the expected result of ${fileBasenameNoExtension}, that is program.c without the extension, thus program.
As to why it is not recognized I have no idea - depends on you build task

Closing as designed - let me know if I misunderstood stomething here

**Comment by bayesrule** [comment] 2016-11-25 17:06
@isidorn sadly you misunderstood me again. I meant ${fileBasenameNoExtension} should be 'program', but it is not.

Like I presented in the quoted line, it displayed as ${fileBasenameNoExtension}, which clearly shows that it is not working...

**Comment by xin053** [comment] 2016-11-26 04:23
I have this problem too.Using '${fileBasenameNoExtension}' in 'tasks.json' produces '${fileBasenameNoExtension}.exe' , it seems ${fileBasenameNoExtension} doesn't work.

task.json:

```json
{
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "showOutput": "always",
    "args": ["-g","${file}","-o","${fileBasenameNoExtension}.exe"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
```

**Comment by Renkin42** [comment] 2016-11-26 13:57
${fileBasenameNoExtension} is doing the same thing for me, it should be getting "style.min.css" out of this but instead it literally sends "${fileBasenameNoExtension}.min.css": 
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "sass",
    "isShellCommand": true,
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "compile css",
            "args": [
                "${relativeFile}",
                "${fileBasenameNoExtension}.css"
            ]
        },
        {
            "taskName": "minify css",
            "isBuildCommand": true,
            "args": [
                "${relativeFile}",
                "${fileBasenameNoExtension}.min.css",
                "--style",
                "compressed"
            ]
        }
    ]
}
```

**Comment by isidorn** [comment] 2016-11-28 09:21
Ok looking at all your examples it seems like the issue is that the substition does not work if the variable is nested inside an argument.
My guess is that it will get substiuted if you have it top level in launch.json

Reopening to investigate

**Comment by isidorn** [comment] 2016-11-29 15:05
This has been fixed in the insiders, please verify with vscode insiders this works fine for you now.
It will be a part of the next stable release in a couple of weeks.

**Closed by isidorn** 2016-11-29 15:05 UTC
Labels: bug

**Comment by isidorn** [comment] 2016-11-29 15:07
By the way, the original feature https://github.com/Microsoft/vscode/issues/1104 is assigned to November which means it got fixed in the november release and will be available in the november vscode. Which gets released mid december - more details https://github.com/Microsoft/vscode/issues/15099
