### ISSUE TITLE
Set workbench.editor.closeOnFileDelete to false by default

### ISSUE THREAD

**Issue by testworksau** [Microsoft/vscode#47930] opened 2018-04-16 06:17 UTC
Issue #24328 introduced a setting to allow VS Code to keep a file open after it was deleted from disk. This was implemented after a VS Code user experienced data loss when the file containing their code was accidentally deleted from the file system. 

Unfortunately, this setting is disabled by default.

Many text editors or IDEs have implemented behavior where files will remain open if they are not closed via the editor itself. They will usually have a prompt asking what to do with these orphaned files. 

workbench.editor.closeOnFileDelete should default to false, not true, to allow the possibility of the VS Code user being able to recover changes. This would help those, like me, who didn't have the foresight to:

a) know that the default behavior is to close the orphaned file
b) know that there is a setting which controls this, and its name
c) know that this setting is currently set to a destructive value 

- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:
1. Install VS Code for the first time
2. Open a file, make some changes, and save it
3. Delete the file off the hard disk accidentally (bonus points for doing this in the same script as the one you have been making changes to all day)
4. Die a little bit inside when you realize the file cannot be recovered and VS Code has closed it

Does this issue occur when all extensions are disabled?: Yes

**Comment by bhelyer** [comment] 2018-05-11 03:31
Seconding this. This is absurd. I've seen @bpasero's comments about this being as designed, to save resources (?), and help language servers (as an author of a language server, I'll gladly endorse changing this default) and that doesn't ring true to me. I believe I've lost work twice to this (no idea why I didn't set the setting the first time), and I know I'm not the only one. This may be 'as designed', but your design is flawed.

**Comment by noah-potter** [comment] 2018-05-16 19:49
Another common scenario I face is:
1. Working in one feature branch with a bunch of new files open as I work on that feature
2. Get assigned to review a PR
3. Switch to another branch to review PR in more depth
4. Switch back to work on feature
5. Lose place in workflow since vscode thinks those files were deleted

**Comment by iamzhout** [comment] 2018-06-04 21:48
Just lost my days of work by accident for type "rm -rf", and just shocked to find out that all open editor window for deleted files are automatically closed in vscode. 😱

Thanks vscode for the great default value of `workbench.editor.closeOnFileDelete`, that gives me the chance to rewrite the code from scratch, and congurations for the merge of github & microsoft. 🌹

**Comment by JD342** [comment] 2018-07-28 05:05
I'm just going to include myself along with the others.

So I was working on a custom script that should run at boot up after the BIOS and make fancy effects, because it's cool. To test what was made, I wrote on terminal as root the usual command to update the system script folder. The command looked like this:

```
rm -r /usr/share/[...]/example cp -r /home/[...]/example /usr/share/[...]/example
```

This time I forgot to put `&&` before `cp`. That little mistake resulted in the removal of everything in `/usr/home/[...]/example`, thus the loss of all the progress that was made this day. What was left was what remained on the version control.

Yes, I know, I'm a moron. Had I been more careful this wouldn't have happened. And I guess I learned a valuable lesson to triple check the commands before running them. But mistakes do happen, we're not robots (yet), and little did I know that this editor wanted to be special.

You can call me a spoiled junior, but I never used an editor that closed the file I was writing on without my explicit instruction. Had I been using Sublime Text, this wouldn't have happened. Golly, had I been using Windows Notepad this wouldn't have happened!

I guess I have to add this quirk on the long term memory storage of my brain, as something to keep in mind when installing VSCode in a new system every time. But I believe it would be more common sense to change this default. Because I don't think any newcomer expects this behavior.

Other than that, you guys at Microsoft are making a great piece of technology here for free. Thanks a lot for that.

###### <i><small> I'm still not going to forgive you for binning the Aero design in Windows 10 though.</small></i>

**Comment by bpasero** [comment] 2018-08-08 16:02
My reasoning for not changing this default is that it could be seen as annoying if tabs show up as "deleted on disk" in these situations:
* you change a branch in source control and as a result files got deleted or renamed
* you rename a file externally

The rename case is ugly. We currently have no way to detect a rename that happens outside of VSCode (or even from within the integrated terminal), so every time you rename a file that is opened, it will show as deleted.

Another thing to keep in mind: even if the default changes to keep files open when deleted, this will not work for files that are opened as tab but have not been clicked on during the running session. We only store the contents of the file in memory if you clicked on a tab once during the session. In other words, we cannot preserve the contents of a file if it has been deleted and has not been opened during the session.

For August we will conduct an experiment where the default of this setting is changed to gather more feedback from our insider users and see if it is being seen as annoying or not.

**Closed** 2018-08-15 13:59 UTC
Labels: feature-request, workbench-editors
