### ISSUE TITLE
Crash when try to open a folder or load some file

### ISSUE THREAD

**Issue by fabiokiatkowski** [microsoft/vscode#102534] opened 2020-07-14 21:40 UTC
Issue Type: <b>Bug</b>

Try to open a folder in Majaro Linux.
Installed by snap.

With I tried to load a workspace that have some opened files VSCODE crashes too.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 4.19.126-1-MANJARO snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2909)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|15.58GB (11.24GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by IllusionMH** [comment] 2020-07-14 22:13
Most likely duplicate of #100940

**Closed** 2020-07-14 22:55 UTC
Labels: new release
