### ISSUE TITLE
The default extension for untitled files is not .txt

### ISSUE THREAD

**Issue by danilort** [microsoft/vscode#115860] opened 2021-02-05 11:30 UTC
- VSCode Version: 1.53.0 (updated from 1.52)
- OS Version: Windows 10 version 1909 build 18363.1316

Steps to Reproduce:

1. create a new empty file
2. file > save

The proposed extension is the first in the list (example Untitled-1.**bat**).
Expected result: Untitled-1.**txt**

![immagine](https://user-images.githubusercontent.com/16148184/107028128-69fb1d80-67ad-11eb-803b-4e471edb5d9a.png)

Does this issue occur when all extensions are disabled?: Yes

.

**Comment by zawys** [comment] 2021-02-05 11:36
Why proposing an extension at all?

**Comment by gjsjohnmurray** [comment] 2021-02-05 11:37
@danilort do you think this is a change since 1.52?

**Comment by danilort** [comment] 2021-02-05 11:38
Yes, up to version 1.52, the default was .txt

**Comment by danilort** [comment] 2021-02-05 11:46
> 
> 
> Why proposing an extension at all?

VScode always proposes an extension based on the content of the file (example: Untille-1.php).
But if the content is unknown, it should propose .txt, which is the most common, not .bat.
Until version 1.52 it worked like this.

**Comment by gjsjohnmurray** [comment] 2021-02-05 11:55
Workaround is to make the first line of your new file look like this:
```
a.txt
```

**Comment by danilort** [comment] 2021-02-05 11:58
If I enable an extension (eg Autohotkey), the proposed extension changes (eg .ahk).
But it is always the first extension on the list.

![immagine](https://user-images.githubusercontent.com/16148184/107030584-26a2ae00-67b1-11eb-91a1-f45964a9adef.png)


![immagine](https://user-images.githubusercontent.com/16148184/107030654-4043f580-67b1-11eb-85b3-aac481510de2.png)

**Comment by gjsjohnmurray** [comment] 2021-02-05 12:08
@lramos15 spotted this in https://github.com/microsoft/vscode/issues/114264#issuecomment-769289875

Looks like it was caused by PR #114487

cc @bpasero

**Comment by isidorn** [comment] 2021-02-05 12:46
Aslo related to https://github.com/microsoft/vscode/issues/114307
@bpasero feel free to lose as dupe or assign to me

**Comment by lramos15** [comment] 2021-02-05 14:19
My expectation was always it would default to "All Files" instead of attempting to detect the language mode that way when I save I could just type`filename.txt` or `filename.js` and that is what would then set the language of my untitled file.

**Comment by danilort** [comment] 2021-02-05 14:57
I went back to version 1.52.1.

When the new file (untitled) contains php code, when I save it, it offers me Untitled.php  (OK)
When the new file is empty (or unknown code), when I save it, it offers me Untitled.txt (OK)
This behavior was consistent, and that's what I expect from 1.53

**contains php code**

![immagine](https://user-images.githubusercontent.com/16148184/107049482-6e81ff00-67ca-11eb-8f81-499460232aa7.png)

![immagine](https://user-images.githubusercontent.com/16148184/107049495-7477e000-67ca-11eb-9488-7ac760df0214.png)



**empty**

![immagine](https://user-images.githubusercontent.com/16148184/107049510-7a6dc100-67ca-11eb-9f27-23b949b114b0.png)

![immagine](https://user-images.githubusercontent.com/16148184/107049520-7e014800-67ca-11eb-869f-00abc6d0c0a1.png)

**Comment by akbyrd** [comment] 2021-02-05 19:50
This is definitely a behavior change from 1.52 and an undesirable one.

I have `"files.defaultLanguage": "plaintext",` in my settings file. When I open a new, untitled document the editor is set to Plain Text, as indicated at the bottom of the window. When I save the file it defaults to a .bat extension. If I change the language to C++ and save it defaults to .cpp.

If I change the default language to C++, opening a new document and saving it works as expected. However, if I open a new document and manually change the language to plain text it again defaults to .bat.

vscode chooses the file extension based on the current language of the editor. The issue looks to be that for the plain text language specifically it simply gets the default wrong.

**Comment by bpasero** [comment] 2021-02-09 10:08
Will fix as part of a recovery release to restore the previous behaviour.

**Closed** 2021-02-10 05:54 UTC
Labels: bug, candidate, regression
