### ISSUE TITLE
Ionide Send to F# Interactive terminal window produces garbage output in vscode 1.9.0

### ISSUE THREAD

**Issue by pgus** [Microsoft/vscode#19946] opened 2017-02-04 22:56 UTC
Something broke when updating to 1.9.0. I don't know if you or Ionide folks need to fix this.

- VSCode Version: 1.9.0
- OS Version: OSX El capitan 10.11.6

Steps to Reproduce:

1. Install Ionide-fsharp extension
2. Send any fsharp code line to Interactive window with option + /
3. you get garbage chars at the terminal prompt after command executes
3. Next time you send your command will fail due to the garbage chars

From terminal - F# interactive  
```
> type PersonType = {First:string; Last:string}
- ;;

type PersonType =
  {First: string;
   Last: string;}

> ^?^? <-- Garbage chars
```

**Comment by Tyriar** [comment] 2017-02-06 19:52
This is likely a duplicate of https://github.com/Microsoft/vscode/issues/19766

@pgus can you try adding this to your settings and let me know if it fixes it?

```
"terminal.integrated.flowControl": false
```

/cc @Krzysztof-Cieslak

**Closed by Tyriar** 2017-02-06 19:52 UTC

**Comment by pgus** [comment] 2017-02-06 20:21
Yes, setting flowControl false solved it. Thanks
