### ISSUE TITLE
Resizing terminal window causes misalignment on right side

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#153603] opened 2022-06-28 20:31 UTC
Testing #153400

After playing around with the size of the terminal I end  up with the right side no longer resizing and fixed to a certain length:
![image](https://user-images.githubusercontent.com/12758612/176279094-dcd9edd0-9503-4300-a5a4-998112442688.png)

The lines afterwards are a little bit dynamic until they also stop resizing: 
![image](https://user-images.githubusercontent.com/12758612/176279231-b99d0da5-7529-414d-9ecb-5a5ca5c16a7c.png)

**Comment by Tyriar** [comment] 2022-06-28 20:36
This is actually working by design as your right prompt there is fixed in place absolutely, not aligned to the right or anything so it will not move around dynamically on resize. Outside of the current prompt line anyway that gets redrawn

**Closed by Tyriar** 2022-06-28 20:36 UTC
