### ISSUE TITLE
coecompletion is not working correctly

### ISSUE THREAD

**Issue by rabol** [Microsoft/vscode#22284] opened 2017-03-09 09:39 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|php-pack|felixfbecker|1.0.1|
|vscode-tfs|ivangabriele|0.6.0|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.2|;

---

Steps to Reproduce:

1. create a PHP file
2. Create a simple class
3. add this: protected $fillable "hit tab"

the result is then this:

protected <1fillable></1fillable>

**Comment by ramya-rao-a** [comment] 2017-03-09 18:37
cc @felixfbecker

**Comment by felixfbecker** [comment] 2017-03-09 18:39
This is emmet triggering inside PHP code, so not an issue of my extension.

**Comment by ramya-rao-a** [comment] 2017-04-02 05:35
Duplicate of #7913

To disable emmet for php you can add the following setting:

``` json
"emmet.excludeLanguages": ["php"]
```

**Closed by ramya-rao-a** 2017-04-02 05:35 UTC
Labels: emmet
