### ISSUE TITLE
Undo of cell creation loses Notebook focus

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#99151] opened 2020-06-02 17:03 UTC
Issue Type: <b>Bug</b>
Testing https://github.com/microsoft/vscode/issues/98991

1. Open a new `.github-issues` file and type in the first cell
2. Add a new cell below this and type some text into it
3. Undo repeatedly

The text from the new cell is removed, then the new cell itself, then undo stops working. I expected undo to remove text from the first cell at that point. If I focus the first cell and try to undo again, it does work.

VS Code version: Code - Insiders 1.46.0-insider (1bfa086adb9271ff56be11821da686e4cfffb672, 2020-06-02T08:10:00.819Z)
OS version: Darwin x64 18.7.0

**Comment by alexdima** [comment] 2020-06-03 17:01
The root cause is hat the cell creation undo leads to the focused editor being disposed, which leads to the focus going to the body (and leaving the notebook). Once clicking anywhere inside the notebook, undo works again.

**Comment by rebornix** [comment] 2020-06-11 23:59
Now that the cells and notebook list share the same undo/redo stack, the issue should be gone now.

**Comment by RMacfarlane** [comment] 2020-07-01 23:20
I'm still seeing this in today's insiders

**Comment by rebornix** [comment] 2020-08-03 23:10
@RMacfarlane are you still seeing this in Insiders now?

**Comment by RMacfarlane** [comment] 2020-08-03 23:22
Undo now works, but the focus indicator seems to get lost:
![notebook_undo](https://user-images.githubusercontent.com/3672607/89236467-7b1c6500-d5a5-11ea-95f6-a29e0db63ea1.gif)

**Comment by rebornix** [comment] 2020-08-14 23:07
Pushed a fix which fixes this issue partially.

**Comment by roblourens** [comment] 2020-08-29 01:18
This happens when focus is in the editor, and when we delete the focused dom element, focus doesn't get reset to the list. We can't anything specifically for 'undo' because it happens in the model, but really we want to prevent this from happening for any cell modification. So I pushed a change to ensure that no list splice causes the list to lose DOM focus. Please take a look at the change @rebornix to check that this makes sense.

**Closed** 2020-08-29 01:17 UTC
Labels: notebook, polish
