### ISSUE TITLE
For long completion items, truncate the start of the string instead of the end

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#76855] opened 2019-07-08 09:40 UTC
Raised at https://github.com/Dart-Code/Dart-Code/issues/1837, if the completion items are really long, VS Code truncates them at the end:

<img width="648" alt="Screenshot 2019-07-07 at 20 31 34" src="https://user-images.githubusercontent.com/3372058/60771916-29ca4980-a0f7-11e9-8240-21c34c790229.png">

I'll see if we can change this completion so it doesn't include the full path, but it seems like VS Code could maybe be smart here - the visible characters of all the completions here are the same thing as is visible in the document (which is being used to filter) so it would be much better to truncate from the start than the end (for ex., if the label starts with the text being used to filter, then truncate from the start).

**Comment by octref** [comment] 2019-10-22 18:02
Duplicate of #29126. I folded your comment into there.

**Closed by octref** 2019-10-22 18:02 UTC
Labels: *duplicate, feature-request, suggest, ux
