### ISSUE TITLE
Auto import not working correctly

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#42744] opened 2018-02-01 15:15 UTC
- VSCode Version: 1.19.3
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Have a file with .mjs extension
2. Watch auto import dropdown fail.

Does this issue occur when all extensions are disabled?: Yes
![screen shot 2018-02-01 at 10 14 08 pm](https://user-images.githubusercontent.com/9585787/35685841-61b01e1e-079d-11e8-8cb0-cf4270772087.png)

**Comment by jpike88** [comment] 2018-02-01 15:20
Also, if I type in taskUtil (which has the exact same sort of file and extension as caseUtil, the dropdown doesn't suggest it. Looks like it's not just poorly suggesting a name but it's flaky in whether it suggests something at all.

**Comment by mjbvz** [comment] 2018-02-12 19:15
@jpike88 I believe the root cause is that we don't fully support mjs files yet (see https://github.com/Microsoft/TypeScript/issues/18442) They will not get picked up by `jsconfig.json` projects, which probably explains why `taskUtil` is not being suggested in your second example

Closing this as a duplicate of https://github.com/Microsoft/TypeScript/issues/18442

**Closed by mjbvz** 2018-02-12 19:15 UTC
Labels: javascript
