### ISSUE TITLE
Open Walkthough does not show all available walkthroughs

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode#144621] opened 2022-03-07 19:30 UTC
1. I installed a new version of the Bicep extension as a vsix. This version includes the new getting started walkthrough
2. Hit Ctrl + Shift + P and Open Walkthrough. I only was able to see 3 Visual Studio specific walkthroughs available excluding Docker extension for VS Code and Bicep extension.
3. Since I know the workaround to this bug, I then simply hit ESC and ran the command again. This time both my Bicep walkthrough and Docker extension walkthrough popped up

**Comment by JacksonKearl** [comment] 2022-03-07 20:36
Duplicate of #135487, should be fixed in Insiders already.

**Closed by JacksonKearl** 2022-03-07 20:36 UTC
