### ISSUE TITLE
Settings on small viewport break sidebar until re-render

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#232209] opened 2024-10-24 23:36 UTC
Type: <b>Bug</b>

Open Settings on a small viewport. Search a word.
🐛 Broken sidebar pops up.

![Image](https://github.com/user-attachments/assets/e6509b73-59e8-48c2-a637-a315ab435fb8)

Goes away when switching to another tab.

VS Code version: Code - Insiders 1.95.0-insider (a030b0cd0b81acb028d2bca640d085e5f0e3ad8d, 2024-10-24T17:04:47.386Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (0.25GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rzhao271** [comment] 2024-10-24 23:58
Duplicate of #196468

**Closed by rzhao271** 2024-10-24 23:58 UTC
Labels: bug, settings-editor, papercut :drop_of_blood:
