### ISSUE TITLE
Background task from Git panel and Debugging panel blocked in loading position

### ISSUE THREAD

**Issue by fsimonAramis** [microsoft/vscode#236485] opened 2024-12-18 15:21 UTC
Type: <b>Bug</b>

After launching the debugger or modifying the code, the source control and the Run and Debug sections switch to a loading version (with the clock icon), and it becomes impossible to restart the debugger or have extensions like Copilot working. You have to restart VSCode for it to work again.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 6.8.0-49-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 517)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.31GB (7.12GB free)|
|Process Argv|--crash-reporter-id cb1f3462-285f-414a-a93c-bd613c214383|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
shell-debugger|mni|0.0.2
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by cubesnyc** [comment] 2024-12-18 16:44
Also started seeing this problem yesterday.

**Comment by roblourens** [comment] 2024-12-18 17:49
So you do see it in 1.96? What language are you debugging? 

Can you share a screenshot? Not totally clear what you see..

**Comment by fsimonAramis** [comment] 2024-12-18 17:59
I'm working on my vscode project with or without the debugger turned on.
After several code modifications, the source control becomes pending, and
then it is impossible to restart the debugger, to have copilot inline or in
chat, and the source control never recovers as it should without restarting
VSCode completely.

Sometimes source control and debugger are in pending status, it depends.
But each time I need to reboot VSCode.

I tried to uninstall / reinstall VSCode, remove cache from VsCode, but the
problem persists.

[image: image.png]

**Comment by roblourens** [comment] 2024-12-18 22:41
Can you try disabling extensions (eg F1 > "Reload With Extensions Disabled") and see if it still happens?

It sounds lik this happens even when just editing files, not using the debugger, right?

I'm guessing that some extension has the extension host process stuck. Do you see a process stuck with high CPU when this happens? You can check Help > Open Process Explorer to see

**Comment by fpedd** [comment] 2024-12-19 08:40
I think I am experiencing something similar. It "started to happen" some time this week, I believe. 

I was on an earlier version of code 1.8*, and in an effort to circumvent this, upgraded to 1.96, where this is still happening. I am super confused and have never seen something like this before. Let me go into some more detail:

When this "happens", my VSCode all of a sudden partially freezes up. What I mean by this is:
- If I had a debugger or pytest test running, it gets stuck. The debugger becomes unresponsive, and any tests I ran, with or without debugger, also get stuck.
- I can still interact with the UI, in general, and explore files via the file explorer.
- However, the Source Control view and the Search view freeze up. They don't show any results, besides files already opened. 
- Practically all panels, besides Open Editors, File Explorer, and Extensions become unresponsive or are stuck in an endless loading loop.
- Checking with the Process Explorer, there is no particular process showing abnormal CPU or memory usage.

Reloading the window via `Developer: Reload Window` makes this go away for 5 minutes or so, until, after normal use, it gets stuck again.

I am using code on my local machine (Ubuntu 22.04) to connect to a remote server via SSH. On the remote server I have a docker container running, to which I connect again, and where I work in. I work in a mostly Python (and some C++ files environment). 

```
CPUs	12th Gen Intel(R) Core(TM) i7-1280P (20 x 2586)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off webnn: disabled_off
Load (avg)	1, 1, 1
Memory (System)	30.95GB (23.67GB free)
Process Argv	--crash-reporter-id 8408bc37-eb04-4eeb-a630-a703fb1444cb
Screen Reader	no
VM	0%

Remote	SSH: <redacted>
OS	Linux x64 5.15.0-113-generic
CPUs	12th Gen Intel(R) Core(TM) i7-12700 (20 x 1873)
Memory (System)	31.02GB (20.08GB free)
VM	0%
Remote	<redacted>
OS	Linux x64 5.15.0-113-generic
CPUs	12th Gen Intel(R) Core(TM) i7-12700 (20 x 1025)
Memory (System)	31.02GB (20.08GB free)
VM	0%
```

I use the following extensions:
```
Extension	Author (truncated)	Version
jupyter-keymap	ms-	1.1.2
remote-containers	ms-	0.394.0
remote-ssh	ms-	0.116.1
remote-ssh-edit	ms-	0.87.0
remote-wsl	ms-	0.88.5
remote-explorer	ms-	0.4.3
scala	sca	0.5.8
pdf	tom	1.2.2
pythoncpp-debug	ben	0.3.0
cmake-format	che	0.6.11
vscode-markdownlint	Dav	0.57.0
githistory	don	0.6.20
gitlens	eam	16.0.5
shell-format	fox	7.2.5
copilot	Git	1.253.0
copilot-chat	Git	0.23.2
vscode-pull-request-github	Git	0.102.0
vscode-docker	ms-	1.29.3
black-formatter	ms-	2024.4.0
debugpy	ms-	2024.14.0
flake8	ms-	2023.10.0
isort	ms-	2023.10.1
mypy-type-checker	ms-	2024.0.0
python	ms-	2024.22.0
vscode-pylance	ms-	2024.12.1
jupyter	ms-	2024.11.0
jupyter-keymap	ms-	1.1.2
jupyter-renderers	ms-	1.0.21
vscode-jupyter-cell-tags	ms-	0.1.9
vscode-jupyter-slideshow	ms-	0.1.6
cmake-tools	ms-	1.19.52
cpptools	ms-	1.22.11
cpptools-extension-pack	ms-	1.3.0
makefile-tools	ms-	0.11.13
vscode-yaml	red	1.15.0
scala	sca	0.5.8
vscode-fileutils	sle	3.10.3
vscode-zipexplorer	sle	0.3.1
code-spell-checker	str	4.0.21
even-better-toml	tam	0.19.2
cmake	twx	0.0.17
clang-format	xav	1.9.0
vscode-proto3	zxh	0.5.5
```

Since I rely on some of these extensions to be able to reach the environment where I can reproduce this issue, I can't run without extensions.

I tested this connecting to a different server, and connecting also from a different machine (Ubuntu 20.04), just to ensure that it's not something wrong with either machine.

This is my VSCode, but this definitely also happened on an earlier version.
![Image](https://github.com/user-attachments/assets/41f21c07-9c92-4648-ad1f-3e280d66fcfe)

**Comment by fpedd** [comment] 2024-12-19 10:33
I think there might be a number of related issues
https://github.com/microsoft/vscode/issues/236390
https://github.com/microsoft/vscode/issues/236411
https://github.com/microsoft/vscode-python/issues/24633

**Comment by roblourens** [comment] 2024-12-19 23:48
Looks like this should be fixed via https://github.com/microsoft/vscode-python/issues/24633

**Closed by roblourens** 2024-12-19 23:48 UTC
Labels: info-needed
