### ISSUE TITLE
VSCode asks git https password when using ssh (Node 16.2 NPM 7.13)

### ISSUE THREAD

**Issue by rubencallewaert** [microsoft/vscode#124349] opened 2021-05-21 10:37 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Mac OS Big Sur 11.2.3

Steps to Reproduce:

1. Have a package.json using a ssh git url for a dependency
Example: ```"mypkg": "git+ssh://git@bitbucket.org/myuser/mypkg.git#develop",```

2. Make sure your public key is authorized to connect to the repository

3. when using npm install or npm ci with a terminal inside vscode using node 16.2 and npm 7.13, vscode will ask for a password to connect to https://bitbucket.org

Extra info:

- When executing npm ci or install in a terminal **outside of vscode**, there is no password prompt
- When revering back to node 14 and npm 6 vscode does not prompt for a password

**Comment by Ravi-Rajpurohit** [comment] 2022-05-12 10:53
+1

**Comment by lszomoru** [comment] 2024-12-12 20:14
Duplicate of [#161406](https://github.com/microsoft/vscode/issues/161406)

**Closed by lszomoru** 2024-12-12 20:14 UTC
Labels: bug, git
