### ISSUE TITLE
Extract The Code Editor

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/vscode#3188] opened 2016-02-20 03:25 UTC
The actual code editor should be extracted and made into its own separate project outside of VSCode itself. The editor would be massively useful in a variety of other projects that need to embed an editor and many could benefit from this separation. It would also provide a nice 3rd alternative to the other two well-established editors of Ace and CodeMirror.

**Comment by egamma** [comment] 2016-02-20 14:55
Duplicate of #446

**Closed by egamma** 2016-02-20 14:55 UTC
