### ISSUE TITLE
Hebrew

### ISSUE THREAD

**Issue by alive2** [microsoft/vscode#92767] opened 2020-03-16 09:31 UTC
Issue Type: <b>Bug</b>

Marking Hebrew (RTL) characters has become weird with the last update.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.86GB free)|
|Process Argv|C:\Users\arbel\Desktop\Priority Client|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-eslint|dba|2.1.1
prettier-vscode|esb|3.20.0
php-intellisense|fel|2.3.14
php-cs-fixer|jun|0.1.129
php-namespace-resolver|Meh|1.1.8
react-proptypes-intellisense|OfH|1.0.3

</details>

**Comment by alexdima** [comment] 2020-03-16 15:46
Duplicate of #92373

**Closed by alexdima** 2020-03-16 15:46 UTC
