### ISSUE TITLE
Manual resolution is still appearing as conflict?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162309] opened 2022-09-29 07:59 UTC
Here in this case I see a "manual resolution" as one of the conflicts, but I am a bit confused: if the conflict was automatically manually resolved, why is it still appearing as conflict?

<img width="645" alt="image" src="https://user-images.githubusercontent.com/900690/192974680-02a872bc-31a5-48ff-af10-b43d402fdd08.png">

[merge.json.zip](https://github.com/microsoft/vscode/files/9672409/merge.json.zip)

**Comment by hediet** [comment] 2022-09-29 12:09
I'm quite sure this goes away with `"mergeEditor.diffAlgorithm": "experimental",`.

**Comment by bpasero** [comment] 2022-09-29 12:47
I tried, and it is the same:

![image](https://user-images.githubusercontent.com/900690/193035221-c4ecd8ab-d80f-4e47-b285-950153f1de17.png)

**Comment by hediet** [comment] 2022-09-30 11:29
This is probably because the result file does not have conflict markers anymore.
Can you add `<<<<<<<<<<<<<<\n>>>>>>>>>>>>>>` to the result file and try again?

**Comment by hediet** [comment] 2022-09-30 14:01
Closing as duplicate of #160801

**Closed by hediet** 2022-09-30 14:01 UTC
Labels: bug, merge-editor
