### ISSUE TITLE
Code snippet function is not available

### ISSUE THREAD

**Issue by rambuild** [microsoft/vscode#173248] opened 2023-02-03 06:13 UTC
Type: <b>Bug</b>

After updating to v1.75.0, the code snippet feature is not available

Expected behavior.
After entering the set code snippet prefix, the suggestion bar displays the pre-configured code snippet

Actual behavior.
No results are displayed

The following special cases can display the code snippet normally.
1. when the set code snippet prefix has only one letter.
2. When all the code snippets are prefixed by copying and pasting.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.60GB free)|
|Process Argv|--crash-reporter-id 4b2c4611-77db-4657-a9b1-35d141bc0f2a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-tailwindcss|bra|0.9.7
path-intellisense|chr|2.8.4
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.4
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
todo-tree|Gru|0.0.223
vscode-elm-jump|joe|0.0.1
cmderrunner|jus|0.1.2
vscode-leetcode|Lee|0.18.1
easy-less|mrc|1.7.4
vscode-docker|ms-|1.23.3
vscode-language-pack-zh-hans|MS-|1.75.2023020109
live-server|ms-|0.4.5
vetur|oct|0.36.1
material-icon-theme|PKi|4.23.1
LiveServer|rit|5.7.9
fuxi-less-autocomplete|Sca|0.0.6
code-settings-sync|Sha|3.4.3
vue-helper|she|2.4.7
errorlens|use|3.6.0
highlight-matching-tag|vin|0.10.1
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
pythonsymbol12:30657548
vscup:30628656

```

</details>

**Comment by trinhtoanh** [comment] 2023-02-03 07:29
I also had a similar problem. Did someone have a workaround? This makes my job really bad.

**Comment by kythuattech5s** [comment] 2023-02-03 07:41
I also had a similar problem.

**Comment by antichris** [comment] 2023-02-03 08:02
Duplicate of #173244

**Closed** 2023-02-03 08:31 UTC
Labels: new release
