### ISSUE TITLE
Tsc task output limited in osx

### ISSUE THREAD

**Issue by JakeGinnivan** [Microsoft/vscode#18067] opened 2017-01-04 01:03 UTC
- VSCode Version: 1.8.1
- OS Version: MacOS 10.11.6

We are converting a project over to TypeScript at the moment and have a strange issue which is causing some confusion. When any team member using macos builds through VSCode they get somewhere between 50-150 build errors shown in the `Tasks` output and problem window, on windows machines we get the full ~1300

It seems that VSCode on Mac just doesn't capture all of the output from the `tsc` process. Any ideas on what to try?

**Comment by waderyan** [comment] 2017-01-05 21:01
@JakeGinnivan Thank you for opening this issue. Can you share a workspace so we can try on our end?

**Comment by waderyan** [comment] 2017-01-11 19:28
Thank you for creating that repo @luke-john. Makes this much easier. 

To make sure I understand you correctly ... 

1. I ran through the steps in the README and see no errors in VS Code's error console. 
2. I ran the `tsc` in the terminal and I see numerous errors. 

Is this correct?

@dbaeumer can I pull you in here? Where does this land? Is this a tsserver thing? Doesn't seem like a language service issue as much as a task -> error console relationship issue. Please advise.

**Comment by luke-john** [comment] 2017-01-12 03:36
@waderyan 
on the devices we're running here we are actually seeing some errors after running the build task

So after running the following
> * Run build task shift + command + b

We'll see errors are present down the bottom left of the vscode interface.

However the error number is incorrect (missing a lot of errors), it will also change between build task runs (so if you run `shift` + `command` + `b`  again there will be a different number of errors)

It seems unlikely to be a tsserver thing as it's the build task thats failing which is calling tsc, and when you open a file it does give the errors for that file.

**Comment by dbaeumer** [comment] 2017-01-12 08:45
This is not a tsserver bug. I will investigate.

**Comment by jrieken** [comment] 2017-01-12 08:57
with latest insiders on macOS 10.12.2

![screen shot 2017-01-12 at 09 56 31](https://cloud.githubusercontent.com/assets/1794099/21883057/854d4a24-d8ad-11e6-8d7c-9abdddbcaed7.png)

**Comment by dbaeumer** [comment] 2017-01-12 09:09
OK. On Mac we have a total of 136 errors whereas on Windows we do have 423. Even the number for demo.ts is different.

**Comment by dbaeumer** [comment] 2017-01-12 09:18
@luke-john I need to investigate why this is happening. You could do one thing to workaround this. We usually trigger compile via an npm script and never saw problems with that. Something like this in the package.json file:

```
	"scripts": {
		"compile": "tsc -p ."
	}
```

and in the tasks.json something like this:

```
{
	"version": "0.1.0",
	"command": "npm",
	"isShellCommand": true,
	"args": ["run", "compile"],
	"showOutput": "always",
	"problemMatcher": "$tsc"
}
```

Does that improve things?

**Comment by luke-john** [comment] 2017-01-12 09:42
Unfortunately that seems to have the same behaviour @dbaeumer.

I added the changes you suggested to a topic branch of the previous reproduction repo.

https://github.com/luke-john/vscode-18067-repro/tree/expoloration/npm-script

**Comment by dbaeumer** [comment] 2017-01-23 20:13
@luke-john I implemented a new task execution engine. Task will in the future be executed in a terminal instead of a output window which should fix this issue besides adding new capabilities. In the next drop tasks.json can opt in into the terminal execution by specifying `"_runner": "terminal"`. Local testing shows that this should address the problem.

I don't plan to fix this in the old runner (output window based) since it has too many limitations and the new story will be terminal based.

**Comment by dbaeumer** [comment] 2017-02-17 17:11
@luke-john more work has happend for the terminal execution, but I still haven't switch it to be the default. Moving the issue until terminal is the default.

**Comment by dbaeumer** [comment] 2017-03-24 14:52
Current plan is to make the new terminal final in April and then switch. We added task API to vscode which we need to have a little while in proposed.

**Comment by dbaeumer** [comment] 2017-04-13 08:21
Moving due to shifted priorities.

**Comment by dbaeumer** [comment] 2017-06-01 08:18
You can opt into task v2.0.0 using a tasks.json of the form for April.

```
{
    "version": "2.0.0"
}
```

Will close the issue when task 2.0.0 will be the default.

**Comment by dbaeumer** [comment] 2017-11-08 10:54
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200

**Closed by dbaeumer** 2017-11-08 10:54 UTC
Labels: bug, tasks

**Comment by luke-john** [comment] 2017-11-09 03:24
Thank you very much for this @dbaeumer.

Really appreciate the great work yourself an the rest of the typescript and vscode teams do.
