### ISSUE TITLE
Function breakpoints should have glyphs

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#7262] opened 2016-06-06 19:38 UTC
Currently, VSCode doesn't show any kind of graphical feedback of where function breakpoints have bound to.

Visual Studio and other IDEs show some graphical feedback to show the function breakpoint has bound to some specific locations / the debugger is in break mode at a particular line because of a function breakpoint.
It would be great for VSCode to support this in the case when debug adapters report the line(s) where the function breakpoint has been bound.

This helps users determine that
- there is a breakpoint that will be hit at some locations
- a breakpoint has been hit when stopped at a function breakpoint.

@weinand @isidorn

**Comment by isidorn** [comment] 2016-10-06 15:06
This sounds interesting to me. Especially since it would also solve our issue on how to add condition or hit counts to function breakpoints

**Comment by isidorn** [comment] 2017-11-17 15:23
Somewhat a duplicate of https://github.com/Microsoft/vscode/issues/3388

**Comment by isidorn** [comment] 2018-02-14 10:36
In february we will tackle https://github.com/Microsoft/vscode/issues/3388 and as part of that we will show function breakpoint glyphs in the debug viewlet.

Showing function breakpoint glyphs in the editor margin is not possible since this is not supported by the debug adapter protocol, and I am not sure which debuggers could support this funcionality. 

Since the first part of this issue is covered by another issue and the second part we do not plan to work on I have decided to close this issue.

**Closed by isidorn** 2018-02-14 10:36 UTC
Labels: debug, feature-request
