### ISSUE TITLE
Javascript attributes like a "onerror" or "onclick" break the document format process

### ISSUE THREAD

**Issue by EddiG** [Microsoft/vscode#17303] opened 2016-12-15 13:36 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T18:03:00.506Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.6.2|
|format-php|Kasik96|1.1.2|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-scss|mrmlnc|0.6.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|vs-keybindings|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|4.1.0|
|wordpress-snippet|tungvn|1.1.1|

---

Steps to Reproduce:

1. Create the html element with the "onerror" or "onclick" attribute
2. Try to format document

**Comment by aeschli** [comment] 2016-12-31 02:41
duplicate of #17849

**Closed by aeschli** 2016-12-31 02:41 UTC
Labels: format, html
