### ISSUE TITLE
VS Code Crash when switching between preview and markdown files

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#224643] opened 2024-08-02 21:07 UTC
Version: 1.93.0-insider (user setup)
Commit: 3b27f1f74bc09fe2e2068997fcd42768be44a4e3
Date: 2024-08-02T05:03:53.254Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Open a remote repository with GH
2. Open a markdown file
3. Open the preview of the markdown file in the same editor group
4. Use the find widget in the preview to find anything (don't dismiss)
5. Click the markdown file tab
6. Click back to the preview tab

🐛 => VS COde Crashes

**Comment by mjbvz** [comment] 2024-08-02 21:13
Duplicate of #213147. I believe there's an issue with either the electron apis or how we use them

**Closed by mjbvz** 2024-08-02 21:13 UTC
