### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Suyashtnt** [microsoft/vscode#102680] opened 2020-07-16 08:11 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1. Create new angular app
2. Install the language server
3. Crash

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99915:161)
    at resolveModuleNamesWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100282:19)
    at processImportedModules (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101695:35)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101438:17)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101665:21
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101660:16)
    at findSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101435:21)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101234:34)
    at processSourceFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101267:13)
    at processRootFile (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101090:13)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:60
    at Object.forEach (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:100014:16)
    at synchronizeHostData (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138753:26)
    at Proxy.getProgram (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146608:44)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:97
    at Object.flatMap (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147790:46)
    at c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149544:28)
    at IOSession.Session.executeCommand (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149553:33)
    at IOSession.Session.onMessage (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:149577:35)
    at Interface.<anonymous> (c:\Users\Home\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18956

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.4
vscode-custom-css|be5|3.0.10
path-intellisense|chr|2.2.1
regex|chr|0.2.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.8
vscode-deno|den|1.25.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
vscode-svelte-snippets|fiv|0.5.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-to-hastebin|Ham|0.1.1
helium-icon-theme|hel|1.0.0
svelty-snippets|ice|0.2.7
discord-vscode|icr|3.16.0
svelte-vscode|Jam|0.9.3
webpack|jer|2.2.0
Angular2|joh|9.1.2
deno-std-lib-snippets|lau|0.0.8
vsls-whiteboard|los|0.0.11
vscode-postgresql|ms-|0.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
angular-console|nrw|12.0.0
vetur|oct|0.24.0
svelte-autoimport|piv|1.0.4
material-icon-theme|PKi|4.2.0
heroku-command|pko|0.0.8
tsimporter|pmn|2.0.1
vscode-yaml|red|0.9.1
angular-cli|seg|0.0.17
prettier-vscode|Sim|2.0.7
vscode-velociraptor|umb|0.2.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-07-16 20:27
Duplicate of https://github.com/denoland/vscode_deno/issues/89

Cause by the deno extension

**Closed by mjbvz** 2020-07-16 20:27 UTC
Labels: new release
