### ISSUE TITLE
Multi-cursor glitching while typing quotes 

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#11627] opened 2016-09-07 11:05 UTC
- VSCode Version: 1.5-insider
- OS Version: Win10

Steps to Reproduce:
1. Type this in a new file:

```
<span
  id="abc.line1
/>
<span
  id="abc.line2
/>
<span
  id="abc.line3
/>
<span
  id="abc.line4
/>
<span
  id="abc.line5
/>
<span
  id="abc.line6
/>
```
1. Set language mode as "javascript" or "javascript (babel)" or "javascript react"
2. Now, select first `abc`, then **Select all occurences of Find Match**, then press <kbd>End</kbd>, and type `"` (double-quotes) or `'` (quotes).

A mismatching number of quotes are put on selections with odd indices, and matching pair on even indices.

Curiously, this bug doesn't occur with braces or brackets (which are also 'autocompleted' by vscode)

**Comment by waderyan** [comment] 2016-09-12 20:29
@kumarharsh thank you for opening this issue. 

@dbaeumer this bug is confirmed. I cannot reproduce this with other languages.

**Comment by dbaeumer** [comment] 2016-09-13 15:09
@alexandrudima this is a multi cursor behavior. Please move back if you think otherwise.

**Comment by alexandrudima** [comment] 2017-04-26 13:21
This has been fixed in the meantime. All cursors will now type the same thing.

**Closed by alexandrudima** 2017-04-26 13:21 UTC
Labels: bug, editor-brackets, javascript
