### ISSUE TITLE
Zen mode should center page content or have configurable margins in percent of viewing area

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/vscode#17297] opened 2016-12-15 12:36 UTC
The purpose of Zen mode is to get rid of all distractions and make it easy to read/write/scroll through code (most often a single file). Sadly without centering on large screens the current implementation is not fulfilling that purpose for me. 

It is not adding a margin or centering the defined number of columns on screen or inside the tab area thus I have to constantly turn my head left to read. 

On my 30 Inch main monitor this is how zen mode can be configured to look in Sublime:

![image](https://cloud.githubusercontent.com/assets/231889/21224091/bcd51a7e-c2ca-11e6-90ef-3eaf0b03d32c.png)

this is it under vs code

![image](https://cloud.githubusercontent.com/assets/231889/21224127/db754d32-c2ca-11e6-9a00-a96adb11876f.png)

PS: Keep up the good work :) great editor all in all.

**Comment by mjbvz** [comment] 2016-12-15 18:53
Closing as a duplicate of #15684 which was opened with zen mode in mind.

Thanks

**Closed by mjbvz** 2016-12-15 18:53 UTC
Labels: duplicate

**Comment by matthiasg** [comment] 2016-12-15 18:56
@mjbvz sorry did a search for zen first but did not see that issue.

**Comment by mjbvz** [comment] 2016-12-15 19:15
No problem. Glad to see that lots of people are also interested in this feature.
