### ISSUE TITLE
Breakpoint messages no longer shown when hovering the breakpoint indicator

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33480] opened 2017-08-30 05:02 UTC
- Debug a node app or extension with node2, but mess up the sourcemaps or something so the breakpoints are gray
- You should see a message when you hover the cursor over the breakpoint decoration, but you don't. I do see it when I hover over the breakpoint entry in the sidebar, but not the editor margin decoration.

**Comment by isidorn** [comment] 2017-08-30 13:03
Via bisect I have found that commit 0614806c12b156959acfcddebf6bd226ef492573 has broken this
Forwarding to @jrieken to investigate further since those util methods might break other stuff as well

Easier repro steps: add a conditional breakpoint, hover over it -> it should show the condition, it does not

**Comment by jrieken** [comment] 2017-08-30 13:54
Most likely a dupe of #33486 

@isidorn How do you create your hover messages? Do you use a `string`or something like `{language: foo, value: fool_and_code}`?

**Comment by isidorn** [comment] 2017-08-30 13:56
In one of the two ways, both do not seem to work
`const glyphMarginHoverMessage = new MarkdownString().appendCodeblock(modeId, condition);`
`new MarkdownString().appendText(breakpoint.message);`

More details https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugEditorModelManager.ts#L309

**Closed** 2017-08-30 14:04 UTC
Labels: bug, debug
