### ISSUE TITLE
The hover service should hide the hover when the element it's tied to is clicked

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119330] opened 2021-03-19 14:24 UTC
This is currently done by consumers of the hover service (https://github.com/Microsoft/vscode/blob/a255250be89b8208dd219e778f0b2743e198e371/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L232-L235), but could be moved into the hover widget.

**Comment by Tyriar** [comment] 2021-03-19 14:25
Repro:

Hover a link in the terminal and then click the link (no ctrl), the hover should hide immediately.

**Comment by bpasero** [comment] 2024-04-26 08:30
I think we are doing this now @benibenj ?

**Comment by benibenj** [comment] 2024-04-26 09:41
@bpasero This is the case for the managed hover (updateable hover), but I don't think it is the case when using `HoverService.show()` directly.

**Comment by Tyriar** [comment] 2024-04-26 12:02
Related: https://github.com/microsoft/vscode/issues/204965

**Comment by Tyriar** [comment] 2024-06-20 17:55
This isn't so black and white since we also want to support selecting text, especially -but not exclusively- when the hover is locked. Closing as designed for now. @benibenj let me know if you have ideas

**Closed by Tyriar** 2024-06-20 17:55 UTC
Labels: polish, workbench-hover
