### ISSUE TITLE
Comment code autocomplete is way too aggressive

### ISSUE THREAD

**Issue by proteriax** [microsoft/vscode#52741] opened 2018-06-24 02:09 UTC
I have a problem that has been bothering me since VSCode first came out.

- VSCode Version: 1.24.1
- OS Version: High Sierra

**Steps to Reproduce:**

### Problem 1:
Switch to TypeScript, type the following code then place the cursor at the position of `|` (but don’t actually type this symbol in).
```ts
/*|
 * comment here.
 */
```
Enter `*`.

This is what you get:
```ts
/** */
 * comment here.
 */
```

### Problem 2:
Type the following code then place the cursor at the position of `|` (don’t type the actual symbol).
```ts
/**
 * comment here.|*/
```
Press Enter.

This is what you get:
```ts
/**
 * comment here.
 * */
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by atitoa93** [comment] 2018-10-04 22:58
@mjbvz I would like to work on this, insights to start will be appreciated.

According to the issue itself, I can see the problem with the first issue mentioned, but for the second I think this is the correct behavior. What do you think?

**Comment by mjbvz** [comment] 2018-10-05 00:01
Problem 1 is caused by our bracket matching logic. I don't think it can be easily addressed but @rebornix should be able to confirm that.

Problem 2 comes from our [javascript and typescript `onEnter` rules](https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/languageConfiguration.ts)

These are pretty complex but the one that is applying here is the ` e.g.  * ...|` one. Adding an `afterText` regex could probably fix it

**Comment by atitoa93** [comment] 2018-10-19 05:40
@mjbvz @rebornix, I'm looking for more assistance on this issue. I spent some time discovering the code around the comments and the auto closing pairs and now, I'm kind of familiar with what is happening. First, It would be perfect splitting the issue into two separate issues as they don't relate to each other. Second, for `problem 1` the solution comes to my mind is adding another condition for the jsDoc auto close pair that it must be in a block comment opened but not closed, what do you think?

**Comment by mjbvz** [comment] 2020-10-14 08:04
Closing due to the lack of further user interest expressed in the issue over the past 2 years

**Closed by mjbvz** 2020-10-14 08:04 UTC
Labels: bug, help wanted, javascript, typescript
