### ISSUE TITLE
VS Code Helper CPU overload

### ISSUE THREAD

**Issue by nickkooper** [Microsoft/vscode#36537] opened 2017-10-19 08:47 UTC
- VSCode Version: Version 1.17.1 (1.17.1)
- OS Version: macOS 10.12.6

Steps to Reproduce:
1. VSCode Helper overload CPU even when I have restarted OS and just opened IDE to work
2. Exclude files, watch files, exclude search files settings was added, as it offered from other issues description.
3. VSCode overload CPU and OS kills other app processes to get CPU space.

Reproduces without extensions: Yes

**Comment by bogdansoare** [comment] 2017-10-19 12:06
same issue, really disappointed in VS Code, will switch back to Sublime

**Comment by mjbvz** [comment] 2017-10-19 16:55
What language are you working with? Can you also please share the full command line arguments of the process that has the high cpu usage. To see this, run:

```bash
$ ps aux | grep -i code
```

**Comment by nt1m** [comment] 2017-10-22 00:35
@mjbvz VS code consumes a lot of resources on my machine as well. I have only 1 file open and VSCode uses 117% of my CPU, 2.3GB of memory, and has a very bad energy impact.

This is quite disappointing, since I like some of VSCode's features. Unfortunately, the resource usage makes me want to use Sublime Text
Here's what `ps aux | grep -i code` shows:
```
tinguyen-35352:mozilla-inbound tinguyen$ ps aux | grep -i code
tinguyen          3403 111.8 14.1  5528360 2361332   ??  R     1:26AM   4:23.56 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
tinguyen          3063   0.0  0.2  3223916  36852   ??  S     1:14AM   0:00.36 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/tinguyen/Library/Caches/typescript/2.5 --enableTelemetry
tinguyen          2992   0.0  0.7  3310356 112308   ??  S     1:14AM   0:11.11 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart.js /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/zy/33xlylhn3p9dj35mn1cxhtkm0000gn/T/vscode-tscancellation-b544662cc91713d534fa.sock*
tinguyen          2990   0.0  0.6  3256892 103016   ??  S     1:14AM   0:19.64 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/tinguyen/.vscode/extensions/dbaeumer.vscode-eslint-1.3.2/client/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/tinguyen/.vscode/extensions/dbaeumer.vscode-eslint-1.3.2/server/out/server.js --node-ipc
tinguyen          2989   0.0  0.2  3224960  34768   ??  S     1:14AM   0:00.21 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
tinguyen          2987   0.0  0.5  3271476  82120   ??  S     1:14AM   0:06.49 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
tinguyen          2986   0.0  0.0  2482532   3148   ??  S     1:14AM   0:00.01 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --no-rate-limit --no-upload-gzip --database=/var/folders/zy/33xlylhn3p9dj35mn1cxhtkm0000gn/T/VSCode Crashes --metrics-dir=/var/folders/zy/33xlylhn3p9dj35mn1cxhtkm0000gn/T/VSCode Crashes --url=https://rink.hockeyapp.net/api/2/apps/21a48a66799e47fea4f52c0ff81e803d/crashes/upload --handshake-fd=61
tinguyen          2837   0.0  0.4  3393252  71072   ??  S     1:14AM   0:01.31 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=E2FD65A32F37857CB7F068510AAFDCD2 --lang=en-US --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --service-request-channel-token=E2FD65A32F37857CB7F068510AAFDCD2 --renderer-client-id=6
tinguyen          2836   0.0  1.5  4426460 248096   ??  S     1:14AM   1:46.29 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=B693E73BE637D8D29C9CD2787E48B201 --lang=en-US --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#171717 --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --service-request-channel-token=B693E73BE637D8D29C9CD2787E48B201 --renderer-client-id=4
tinguyen          2835   0.0  0.5  2978568  88912   ??  S     1:14AM   0:28.70 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=0,1,10,23,25,36,39,40,47,53,61,63,64,65,66,68,73,74,76,84,85,86,89,92 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x1002 --gpu-device-id=0x67ef --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x191b --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x191b --service-request-channel-token=489BED0FA3552C8B60956DF0AAD0177C
tinguyen          2833   0.0  0.7  3633408 109420   ??  S     1:14AM   0:42.38 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
tinguyen          2493   0.0  0.1  2552412  17380   ??  Ss   12:12AM   0:26.19 /System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService
root               207   0.0  0.0  2516984   5116   ??  Ss   11:19PM   0:00.17 /System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper
tinguyen          3561   0.0  0.0  2433828    808 s001  S+    1:29AM   0:00.00 grep -i code
```

**Comment by nt1m** [comment] 2017-10-22 00:41
@mjbvz I'm also using macOS 12.12.6 and VSCode 1.17.1. I work mainly with JavaScript, but also with haskell.

**Comment by mjbvz** [comment] 2017-10-23 20:33
Thanks @nt1m!

Looks like the watch service has the high cpu usage here. @Tyriar Can you please take a look. Could this be #36307?

**Comment by nickkooper** [comment] 2017-10-23 20:36
@mjbvz  I am working with js. Project is on ember.js. Project is not big.

**Comment by mjbvz** [comment] 2017-10-23 20:40
@nickkooper Can you also please collect the process status by running `ps aux | grep -i code` on the terminal

**Comment by Tyriar** [comment] 2017-10-28 08:15
I think #36307 might be Linux only. @nickkooper is there anything particularly special about the folder or its files that you're aware of?

**Comment by PrimerFender** [comment] 2017-10-31 02:35
I appear to have a similar issue but not sure if exact same. I opened my home (~/) folder because I couldn't figure out how to open ~/.ssh folder, and used terminal (bash) to test some SSH config settings. Anywho, came back after a while and notice it was running high CPU (>= 100%). I first did Close Folder, no change, so I then Quit VSCode altogether (Cmd+Q). "Code Helper" is still taking about 100% CPU. After doing a bit of online googling and finding this thread, "Code Helper" finally disappeared from top output.

I'll try to reproduce but if there is some logging or debug tools output I could get you that would be great. I'm not super familiar with macOS troubleshooting.

**Comment by dogmatic69** [comment] 2017-11-02 08:56
I constantly have similar issues for the past 6 weeks at least. Having to restart vscode multiple times per day. Have already uninstalled numerous plugins but nothing fixes this issue.

Even after closing vscode the CPU remains high, this is after closing the vscode window. 

Usually I get 6+ hours on my laptop, but this reduces to 30 minutes.

(running ubuntu 17.04)

![image](https://user-images.githubusercontent.com/94674/32317363-e834babc-bfb3-11e7-922f-8e0e829e1829.png)

**Comment by nt1m** [comment] 2017-12-02 13:38
@mjbvz Any news on this? The resource usage keeps killing other system process (like Python), and renders my mac unusable until I close VS code

**Comment by mjbvz** [comment] 2017-12-08 22:43
Closing this issue as we need more info to investigate this.

@nickkooper Can you please try the latest vscode insiders to see if you are still hitting this. If this is still happening, let us know which process has the high cpu usage

Everyone who is not @nickkooper, please open new issues

**Closed by mjbvz** 2017-12-08 22:43 UTC
Labels: needs more info
