### ISSUE TITLE
Please allow window tiles - the same as with Visual Studio Pro

### ISSUE THREAD

**Issue by ianfinlay-csiro-au** [microsoft/vscode#103446] opened 2020-07-28 00:47 UTC
Issue Type: <b>Feature Request</b>

Having a multi creen system, I find qwirky was new windows are created odd.  

can VS code adot same type of windo ti;ling as visual Studio Pro
so I can drag a window to the screen I want 

would improve developer productivity 100%

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

**Comment by yume-chan** [comment] 2020-07-28 00:56
Duplicate of #10121

**Closed** 2020-08-12 10:57 UTC
Labels: *duplicate
