### ISSUE TITLE
FR: add ability to be notified when selection in the Explorer changes

### ISSUE THREAD

**Issue by jeffb-sfdc** [microsoft/vscode#139313] opened 2021-12-16 17:24 UTC
I'm working on an extension for VS Code, and I'd like the ability to be notified when the selection in the Explorer's tree changes.  Also, I'd like to not only be notified that it has changed, but would liken to know what the currently selected files & folders are (either pass in a list of selected files to the event handler, or provide an API to get the list)

**Comment by JacksonKearl** [comment] 2021-12-16 18:45
Duplicate of #3553.

**Closed by JacksonKearl** 2021-12-16 18:45 UTC
