### ISSUE TITLE
Attach to Node Process not working with PowerShell on Windows 10

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode#46704] opened 2018-03-27 14:06 UTC
Testing #46582

Windows 10, NodeJS: v8.9.4

1. Create a simple script like:
```
setInterval(() => {
    console.log('a');
}, 500)
```

2. Launch the script in PowerShell: ```node --inspect=1500 foo.js ```
3.  Use the 'Attach to Node Process' command or use the following launch.json:
```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
       {
        "type": "node",
        "request": "attach",
        "name": "Attach to Process via pid or port",
        "processId": "${command:PickProcess}"
    }
    ]
}
```

Expected: Picker shows my process
Actual: Picker shows "There are no entries to pick from"

Note that it works with fine with cmd. This is a Powershell specific issue.

**Comment by weinand** [comment] 2018-03-27 14:54
problem is: PowerShell launches programs with a full path whereas command prompt uses a relative path:

PowerShell:
![2018-03-27_16-48-36](https://user-images.githubusercontent.com/1898161/37975330-58421cb2-31df-11e8-962c-2a48388bcee2.png)

Command.exe:
![2018-03-27_16-50-21](https://user-images.githubusercontent.com/1898161/37975365-6f248230-31df-11e8-8b04-df9b931701e7.png)

**Comment by weinand** [comment] 2018-03-27 15:17
No, the analysis from above is wrong. I'm handling the full path correctly.

The issue is in fact another duplicate of #46672

**Closed by weinand** 2018-03-27 15:17 UTC
Labels: bug, debug

**Comment by tsalinger** [comment] 2018-03-29 08:32
Tested on latest insiders and works fine.

**Comment by weinand** [comment] 2018-03-29 08:38
@tsalinger thanks! 

Till confirmed (and showed me) that both the "Attach Process Picker" and the "Auto Attach" work for him on Windows. 


@sbatten  @RMacfarlane so for some (in ZRH) it seems to work on Windows. What is difference in Redmond?
