### ISSUE TITLE
TS autoimport should provide qualification to make imported entries unique

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37241] opened 2017-10-31 10:53 UTC
Testing: #37177 

- JS project
- file provide1.js
```js
export function foo() {
}

export function foo1() {
}
```
- file provide2.js
```js
export function foo() {
}

export function foo2() {
}
```
- file consume.js
```js
function bar() {
}
```

- inside body bar type foo1, select the symbol. Notice import generated correctly
- inside body bar type foo2, select the symbol. Notice import generated correctly
- inside body bar type foo

Observe:
- there is only one foo
- IMO there should be two, each qualified with the file exporting it
- select foo
- an import is added. I couldn't come up with a rule which on is taken.

**Comment by dbaeumer** [comment] 2017-10-31 11:23
Same happens with TS.

**Comment by mjbvz** [comment] 2017-11-01 00:11
Duplicate of #37283

**Closed by mjbvz** 2017-11-01 00:11 UTC
Labels: javascript
