### ISSUE TITLE
VS Code rendering problem causing low mouse accuracy...

### ISSUE THREAD

**Issue by nvrnight** [Microsoft/vscode#18964] opened 2017-01-21 03:34 UTC
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04 64bit on VirtualBox with Guest Additions installed.

Steps to Reproduce:

1. Open file with content
2. Click on a specific place in the text
3. Your cursor will be to the left and up a bit from where you originally clicked
4. The window appears to actually be larger than what's being rendered on the screen

![image](https://cloud.githubusercontent.com/assets/1048286/22171645/ea6e96e6-df57-11e6-8ba8-64b804fdd909.png)

In the screenshot, the middle of the green circle is where I actually have to click in order to resize the window. So if I click where the corner is actually rendered at, it will register the click just above the smiley face. The same distance from where the corner is rendered at to where it actually is.

**Comment by nvrnight** [comment] 2017-01-21 03:54
My problem appears to have gone away after restarting the virtual machine.

**Comment by simonmurdock** [comment] 2017-01-21 10:18
This is a very common issue with VirtualBox. I switched to different VM host software.

**Comment by dbaeumer** [comment] 2017-01-21 15:08
Closing the issue since the problem is gone and according to @simonmurdock this is a very common issue with VirtualBox

**Closed by dbaeumer** 2017-01-21 15:08 UTC
