### ISSUE TITLE
"Loading "gc-signals" failed"

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#26950] opened 2017-05-19 16:24 UTC
- VSCode Version: 1.12.2 (checked out from tag "1.12.2")
- OS Version: Windows 7 x64

- Visual Studio 2015 update 3
- Node.js: 7.9.0 (compiled from source)
- Python 2.7.1 (32-bit)

**Related to** https://github.com/Microsoft/vscode/issues/26935

Steps to Reproduce:

1. Compile Vscode 1.12.2 with node 7.9.0, per https://github.com/Microsoft/vscode/issues/26935, get error

```
C:\Acme\Dev\projects\vscode1.12>scripts\code.bat
[15:43:36] Using gulpfile C:\Acme\Dev\projects\vscode1.12\gulpfile.js
[15:43:36] Starting 'clean-electron'...
[15:43:36] Finished 'clean-electron' after 2.91 ms
[15:43:36] Starting 'electron'...
[15:43:40] Finished 'electron' after 3.83 s
[15:43:45] Using gulpfile C:\Acme\Dev\projects\vscode1.12\gulpfile.js
[15:43:45] Starting 'clean-electron'...
[15:43:45] Finished 'clean-electron' after 68 ms
[15:43:45] Starting 'electron'...
[15:43:49] Finished 'electron' after 3.84 s

[8108:0519/154353.910:INFO:CONSOLE(201)] "Loading "gc-signals" failed", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (201)
[8108:0519/154353.912:INFO:CONSOLE(202)] "Detail: ", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (202)
[8108:0519/154353.912:INFO:CONSOLE(204)] "Error: The module '\\?\C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\build\Release\gcsignals.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (C:\Acme\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:67:3)", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (204)
[8108:0519/154353.913:INFO:CONSOLE(206)] "Here are the modules that depend on it:", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (206)
[8108:0519/154353.913:INFO:CONSOLE(207)] "vs/workbench/api/node/mainThreadHeapService", source: file:///C:/Acme/Dev/projects/vscode1.12/out/vs/loader.js (207)
```

2. Try refreshing `gc-signals`
```
npm install "gc-signals"
```

3. Get error on running dev version:

```
C:\UBS\Dev\projects\vscode1.12>scripts\code.bat

[13812:0519/181826.230:INFO:CONSOLE(201)] "Loading "gc-signals" failed", source: file:///C:/UBS/Dev/projects/vscode1.12/out/vs/loader.js (201)
[13812:0519/181826.230:INFO:CONSOLE(202)] "Detail: ", source: file:///C:/UBS/Dev/projects/vscode1.12/out/vs/loader.js (202)
[13812:0519/181826.231:INFO:CONSOLE(204)] "Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\UBS\Dev\projects\vscode1.12\node_modules\gc-signals\build\Release\gcsignals.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\UBS\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (C:\UBS\Dev\projects\vscode1.12\node_modules\gc-signals\src\index.js:67:3)", source: file:///C:/UBS/Dev/projects/vscode1.12/out/vs/loader.js (204)
[13812:0519/181826.232:INFO:CONSOLE(206)] "Here are the modules that depend on it:", source: file:///C:/UBS/Dev/projects/vscode1.12/out/vs/loader.js (206)
[13812:0519/181826.232:INFO:CONSOLE(207)] "vs/workbench/api/node/mainThreadHeapService", source: file:///C:/UBS/Dev/projects/vscode1.12/out/vs/loader.js (207)
```

**Comment by Tyriar** [comment] 2017-05-19 18:34
You need to use the npm wrapper script which will build gc-signals against Electron's version of V8 which is newer than what is shipped in node:

```
scripts\npm.bat install
```

**Comment by Tyriar** [comment] 2017-05-22 18:16
@dbaeumer I'm running into this when trying to build on windows too. I hit it after doing the following:

```
git pull
rimraf node_modules
scripts\npm.bat install
npm run watch
```

```
scripts\code.bat
```

**Comment by roblourens** [comment] 2017-05-22 18:57
I've seen that error - "was compiled against a different Node.js version..." - when electron versions change and I don't delete node_modules. Maybe an npm cache needs to be cleared.

**Comment by Tyriar** [comment] 2017-05-22 20:34
An `npm cache clean` didn't fix it.

**Comment by mrkafk** [comment] 2017-05-23 09:05
@roblourens 

I clean npm cache every time I build, in fact that's done by the script:

```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

set PYTHON=C:\Program Files (x86)\Python271\python.exe

set PATH=%PATH%;C:\Program Files\7-Zip


call npm.cmd config set loglevel silly

mkdir tmp

call npm.cmd config set cache %~dp0tmp --global

call npm.cmd cache clean

echo Building VSCode.

scripts\npm install
```

**Comment by dbaeumer** [comment] 2017-05-23 18:54
@Tyriar I got it working again. The key for me was to delete .build folder and do an script\npm install in the vscode workspace. I have no idea why that made starting the terminal fail. All the other native modules worked for me without deleting .build.

**Comment by Tyriar** [comment] 2017-05-24 00:11
@dbaeumer strange.. That takes a load off my mind though 😛

**Comment by roblourens** [comment] 2017-05-25 17:48
Did deleting `.build` work for you @mrafk?

**Comment by buzzzzer** [comment] 2017-05-26 12:23
The same error.

1. git pull
2. git clean -xfd
3. scripts\npm install
4. npm run watch
5. Launch VS Code from vscode debug

degug console:
```cmd
Loading "gc-signals" failed
Detail: 
Error: Cannot find module '../build/Release/gcsignals'
Error: Cannot find module '../build/Release/gcsignals'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (d:\Serge\Bases\!Git\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...vscode\node_modules\gc-signals\src\index.js:8:18)
    at Object.<anonymous> (...vscode\node_modules\gc-signals\src\index.js:67:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
Here are the modules that depend on it:
......
```

p.s.deleting .build does not help

**Comment by mrkafk** [comment] 2017-05-28 12:47
@roblourens No, it did not - but I've deleted entire `node_modules` and after resolving other problems I managed to build.

**Comment by mrkafk** [comment] 2017-05-28 12:47
@buzzzzer Try moving/deleting entire `node_modules`.

**Comment by sandy081** [comment] 2017-05-29 11:44
@mrkafk Since the problem is resolved after cleaning `node_modules` folder, I am closing this issue.

**Closed by sandy081** 2017-05-29 11:44 UTC
Labels: question
