### ISSUE TITLE
Can't create new file/folder on unresolved folder using context menu action

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66484] opened 2019-01-14 14:26 UTC

**Comment by isidorn** [comment] 2019-01-14 15:59
Ok, this one is a bit tricky. The issue is that the explorer item gets the fake placeholder child and only then gets resolved. The resolving ovewrites all children including the fake placeholder child which was just added.

**Comment by isidorn** [comment] 2019-01-15 11:52
Toughest bug of the milestone thus far

**Closed** 2019-01-15 11:51 UTC
Labels: bug
