### ISSUE TITLE
Peek definition should highlihght the line number

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6772] opened 2016-05-24 10:07 UTC
#6655

Peek definition should highlihg the exact line where the definition is, as in some cases it is not clear as to what exact line the user should be looking at, as in this case:

![screen shot 2016-05-24 at 12 05 22](https://cloud.githubusercontent.com/assets/1926584/15500188/dbfca74c-21a7-11e6-9ab1-f885b6f0dfbc.png)

**Comment by jrieken** [comment] 2016-05-25 11:09
We actually would color them but the problem is that definition ranges get folded to their start position. That's because TypeScript select the full type not just the identifier when finding a definition...

**Comment by jrieken** [comment] 2016-05-25 11:12
<img width="532" alt="screen shot 2016-05-25 at 13 12 18" src="https://cloud.githubusercontent.com/assets/1794099/15538091/5849323e-227a-11e6-98a9-ff8f308c9d4d.png">

it would look like this...

**Comment by jrieken** [comment] 2016-05-25 11:13
@dbaeumer do you know if TypeScript is doing that on purpose of by accident?

**Comment by dbaeumer** [comment] 2016-05-25 12:53
@jrieken actually I don't know. I see the need for both. So instead of convincing them to change this I would try to convince them to add the identifier range and the full declaration range.

One reason I can think of having the full range is that types don't need to have names. So no identifier range.

**Comment by jrieken** [comment] 2017-03-14 09:53
This got fixed in TypeScript and we should now do this

**Closed** 2017-03-14 09:54 UTC
Labels: feature-request
