### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by docsa** [microsoft/vscode#102902] opened 2020-07-19 17:16 UTC
We have written the needed data into your clipboard because 
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:99915:161)
    at resolveModuleNamesWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:100282:19)
    at processImportedModules (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101695:35)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101438:17)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:100014:60
    at Object.forEach (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:100014:16)
    at synchronizeHostData (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:138753:26)
    at Proxy.getProgram (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:146608:44)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:146927:97
    at Object.flatMap (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:147790:46)
    at /home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/home/alain/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: debian|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2201)|
|Memory (System)|15.90GB (5.98GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.4
ng-template|Ang|0.1000.4
scratchpad|awe|0.1.0
turbo-console-log|Cha|1.4.0
vscode-eslint|dba|2.1.8
vscode-deno|den|1.25.0
prettier-vscode|esb|5.1.3
mongodb-vscode|mon|0.1.0
vscode-azurefunctions|ms-|0.23.0
vscode-language-pack-fr|MS-|1.47.3
azure-account|ms-|0.8.11
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>
it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2020-07-19 19:23
Duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-07-19 19:23 UTC
