### ISSUE TITLE
Unusable due to slow startup.  Fresh install win 32, no extensions, startup > 10  Minutes!

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Microsoft/vscode#29798] opened 2017-06-28 21:26 UTC
- VSCode Version: 1.13

- OS Version: Windows 7 32 bit

NOTE: I also have Visual studio 2012 installed on this computer and it's running in a virtual machine.
Visual studio 2012 opens within seconds, there is almost no noticeable delay running in this fast virtual machine.

Steps to Reproduce:

1. Download and install VS code on Windows 7 32 bit
2. Runs fast first time after installation and opens up to the welcome screen
3. Close, go to command prompt and run again Code --disable-extensions
4. Nothing happens, open task manager and it's showing Code.exe and cpu is pegged at 99% 
5. Start a stopwatch, wait 10 minutes cpu varies between 99% and rarely dips to 97%.
6. Give up.  No visible Code editor onscreen anywhere, just the task manager process is the only evidence it's doing anything; stop the process.

I left it to start one time as I had to go out, came back about half an hour later and it was opened so at some point it *does* actually complete the startup but I have no idea how long it took.

Same thing happens when I run it without disabling extensions by the way and I've tried it through several reboots uninstalls etc.  

Reproduces without extensions: Yes

I've used Code on Linux previously (64bit Debian in virtual machine on same host computer) and it runs very fast and is very useful, however I wanted to consolidate all my work to my windows dev machine and ran into this issue.

This is a clean install, I'm guessing my difference from others may be that I have vs 2012 installed already?  Only thing I can think of that might have some possibility of interfering with it.

**Comment by jrieken** [comment] 2017-06-29 07:03
@WhatFreshHellIsThis Please start VS Code with `--prof-startup` flag. That will create CPU profile of the startup sequence. Please attach those profiles here.

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 16:06
Cool, coming right up!

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 16:35
Ok, here they are. Please take note that it started up far faster with the profile flag than it does with the disable extensions flag.  With the profile flag the first screen draw happened in 1 minute and 42 seconds, with the disable extensions flag I waited over 6 minutes before finally killing the task and saw nothing drawn on screen.
[e430_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1112792/e430_main.cpuprofile.txt)
[e430_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1112793/e430_renderer.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-06-29 16:43
Wow, crazy. It takes roughly ~1.5 for the app ready event to be delivered. Any AV software installed?

<img width="1189" alt="screen shot 2017-06-29 at 18 42 33" src="https://user-images.githubusercontent.com/1794099/27699504-cfa4489e-5cfa-11e7-91bf-1b64f5898db9.png">

**Comment by jrieken** [comment] 2017-06-29 16:45
I am closing this as dupe of #22087. Sad, but it is a known issue that electron can start very slow on windows, that is the signal of the app being ready is delayed, often by anti virus software. This is an extreme case of this...

**Closed by jrieken** 2017-06-29 16:45 UTC
Labels: needs more info, perf-profile

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 17:07
This *is* with the Microsoft anti virus disabled real time protection and to be on the safe side I also  specifically excluded Code.exe process as well. Anti Virus is not the culprit unless it's doing something even when turned off and that process excluded.  

This issue is not caused by anti-virus to the best of my ability to ensure that.

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 17:10
Also, why does it start the first time after installation quickly every single time?  
On a fresh install it triggers start up and it typically takes just a few seconds after I click on the last installer dialog.

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 17:12
I'm going to go ahead and uninstall the Microsoft AV completely just to put this to rest either way.  I'll report back shortly.

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 17:25
Uninstalled Microsoft Security Essentials, clean reboot.
I have no anti virus software at all installed for this profile.
Result is absolutely no change, still took 1 minute and 45 seconds to the first draw, here are the profiles:

[ea83_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1112942/ea83_main.cpuprofile.txt)
[ea83_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1112941/ea83_renderer.cpuprofile.txt)

**Comment by WhatFreshHellIsThis** [comment] 2017-06-29 17:26
I'm going back to Debian now, I hope this gets sorted out at some point, Code is awesome on Debian, I wish it was as good on Windows.
