### ISSUE TITLE
[meta issue] 1.40 update: Font/Color rendering degradation (macOS, Linux, Windows)

### ISSUE THREAD

**Issue by KeWang323** [microsoft/vscode#84154] opened 2019-11-07 20:04 UTC
- VSCode Version:
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
- OS Version: 10.15.1 (19B88)

Steps to Reproduce:

1. open vscode
2. open a file
3. tried solution in https://github.com/Microsoft/vscode/issues/51132
4. on non-retina displays
![image](https://user-images.githubusercontent.com/19617543/68423214-8184ca00-0156-11ea-8747-0b3488500262.png)

**Comment by Geobert** [comment] 2019-11-07 20:07
Not only MacOS, colors are dimmed on Windows as well:
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bhughes339** [comment] 2019-11-07 20:24
My setup is identical to @Geobert, I just wanted to add a gif to make the problem more obvious:

![video](https://user-images.githubusercontent.com/16418739/68424760-b0a93480-0172-11ea-9eba-73b486e25904.gif)

**Comment by dhowden** [comment] 2019-11-07 20:26
Also seeing this after update to 1.40.0 (running 10.14.6 MacOS Mojave).

Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by AAulicino** [comment] 2019-11-07 20:47
I'm having the opposite effect in macOS Mojave 10.14.6. 

I had to downgrade to 1.39 because the new font intensity is giving me headaches.

![vscode-font](https://user-images.githubusercontent.com/6969647/68426197-5d40e180-0186-11ea-9a30-517410d097ed.gif)

**Comment by dhowden** [comment] 2019-11-07 21:07
@AAulicino That looks like an anti-aliasing/font-smoothing change rather than just a colour change.

**Comment by KeWang323** [comment] 2019-11-07 22:00
are we able to downgrade it to the previous release?

**Comment by AAulicino** [comment] 2019-11-07 22:06
@KeWang323 You can find and download previous versions through the [Visual Studio Code updates page](https://code.visualstudio.com/updates/v1_39).

**Comment by deepak1556** [comment] 2019-11-07 22:16
There are two different issues here, for macOS users just to confirm do you have any of the workaround from https://github.com/microsoft/vscode/issues/59887 that disables the font smoothing ? If so can you undo them to compare ?

For windows users can you report your findings on https://github.com/microsoft/vscode/issues/82733 , does this only happen with a particular theme ?

**Comment by KeWang323** [comment] 2019-11-07 22:26
@deepak1556 
I just tried done and undone the following workarounds form https://github.com/microsoft/vscode/issues/59887, but nothing changed:
```
defaults write com.microsoft.VSCode CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper.EH CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper.NP CGFontRenderingFontSmoothingDisabled 0
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

**Comment by deepak1556** [comment] 2019-11-07 22:49
Thanks @KeWang323 

@bpasero is there a web version prebuilt that @KeWang323 can you use to comapre with chrome ? Just want to make sure if this a regression in Catalina so that it can be tracked under https://bugs.chromium.org/p/chromium/issues/detail?id=1013130

**Comment by mathieupothier** [comment] 2019-11-07 23:00
I have the exact same behavior on windows. And the other ticket mentioned does not seem to be that related As the issue for this particular user was also present in 1.39 while here, going back to 1.39.2 fixes this. I’ve switched themes but the issue persist. If you are sure you want the findings there, well, I can proceed to send them there too.

**Comment by offbeatful** [comment] 2019-11-08 00:00
Thanks, Microsoft! Downgrading...

**Comment by dhowden** [comment] 2019-11-08 00:09
I'm running on Mojave (not Catalina) and seeing the text dimming in the entire interface since upgrading to 1.40.0 (not sure this is a smoothing issue in my case at least).

1.40.0:
<img width="1453" alt="Screen Shot 2019-11-08 at 11 02 35 am" src="https://user-images.githubusercontent.com/2822/68438226-8fe6ea80-0217-11ea-8c52-b1b41d9ab4d9.png">
1.39.2:
<img width="1453" alt="Screen Shot 2019-11-08 at 11 02 22 am" src="https://user-images.githubusercontent.com/2822/68438227-8fe6ea80-0217-11ea-982b-db323f1b9fb6.png">

**Comment by deepak1556** [comment] 2019-11-08 00:16
@dhowden is this with retina or non-retina display ?

**Comment by dhowden** [comment] 2019-11-08 00:23
@deepak1556 Retina.

**Comment by varxzy** [comment] 2019-11-08 01:31
This problem also occurred after the 1.40 version was upgraded. The file theme color is darkened and the theme is Dark+ (default dark). I am running on the macOS Sierra system version, which is the Retina screen.

Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 16.7.0

**Comment by zhoubhin** [comment] 2019-11-08 04:47
yep, it's seem more darker or pale after upgrade to 1.40
Version: 1.40.0
OS: macOS Mojave 10.14.6 (18G1012)

**Comment by trananhmanh89** [comment] 2019-11-08 06:59
seem on vscode 14, windows 10

**Comment by bpasero** [comment] 2019-11-08 07:44
@deepak1556 yes, people can follow our [setup instructions](https://github.com/microsoft/vscode/wiki/How-to-Contribute) and then simply run "`yarn web`" to get VSCode open in the browser.

**Comment by afarkas128** [comment] 2019-11-08 09:19
Hope they will fix this soon, as for now I am switching back to sublime until they fix this or another hackie-fix is found

**Comment by David-Else** [comment] 2019-11-08 10:21
NIGHTMARE!!! In Linux 1.40.0 has turned off or messed up the sub pixel rendering, now the fonts look much worse... this must be fixed urgently!! I have made a GIF, make it full screen (so there is no resizing going on) and watch for a while.

To view the GIF properly on my system you need to download it first (click and save image as) then view it using something other than a browser. The browser seems to do something to it and make it all slightly blurry so you cant really see the issue properly.

Try and focus on the `m` in `jsdom` on line 2... watch how it goes weak and hard to read. See the `m` in `import` too. Look at line 14, the rendering of `a` in `available` and the `=` in the comments seems to move out of place too.

If this is not solved in the recovery release I will go into a deep depression!
![vscode140-subpixel-rendering-bug](https://user-images.githubusercontent.com/12832280/68468657-624a7300-0210-11ea-8199-17c76e348354.gif)

**Comment by Roman-Popov** [comment] 2019-11-08 11:33
same here :(
vscode 1.40
windows 10
theme: one dark pro vivid

**Comment by bpasero** [comment] 2019-11-08 11:44
Out of curiosity, we recently started to build VSCode with the latest Electron 7.x that comes with Chrome 78. Does something change in those versions?

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)

**Comment by nklmilojevic** [comment] 2019-11-08 11:50
Just tried it, doesn't change a thing.

**Comment by jccit** [comment] 2019-11-08 12:18
Here's what I'm seeing across 1.39.2, 1.40.0 and this new build. My colours are a lot more desaturated ever since electron was upgraded. I'm using a DCI-P3 retina screen which might be the cause of the issue. I've noticed that Firefox's colours look more saturated compared to Chrome's when I'm using this type of monitor

* Theme: BeardedTheme Anthracite
* Font: Fira Code
* OS: macOS 10.15.1


### 1.39.2
<img width="616" alt="stable-1 39 2" src="https://user-images.githubusercontent.com/38790449/68475836-19e78100-0221-11ea-9d6a-2f14423bb29c.png">

### 1.40.0
<img width="623" alt="stable-1 40 0" src="https://user-images.githubusercontent.com/38790449/68475837-19e78100-0221-11ea-8e14-0c933b261c45.png">

### 1.41.0 Exploration
<img width="631" alt="exploration-1 41 0" src="https://user-images.githubusercontent.com/38790449/68475835-19e78100-0221-11ea-9e53-bbb4826c9a32.png">

**Comment by sseremelis** [comment] 2019-11-08 12:19
I have the same issue after updating to 1.40.0
Version: 1.40.0
OS: Mac OS Catalina 10.15.1
Theme: Night Owl
Non-retina display

**Comment by andreyjamer** [comment] 2019-11-08 13:11
I have the same on exploration build.
Windows 10

**Comment by bpasero** [comment] 2019-11-08 13:11
Another try (for macOS users ONLY!): 
* open command palette
* pick "configure runtime arguments"
* comment out this line: `"disable-color-correct-rendering": true
* save
* restart

![image](https://user-images.githubusercontent.com/900690/68478651-aa798d80-0230-11ea-8d2a-88d7688651a2.png)

![image](https://user-images.githubusercontent.com/900690/68479040-ac901c00-0231-11ea-94f8-a740ee2dc14a.png)

Also related: does it change if you configure `"disable-hardware-acceleration": true`?

**Comment by jccit** [comment] 2019-11-08 13:26
Just tried the above fix, commenting that line out didn't work for me. However if I set `"disable-color-correct-rendering": false`, the colours return to their pre 1.40.0 state. Disabling hardware acceleration does not have any effect.

So it seems that a quick fix for any macOS users is to set `"disable-color-correct-rendering": false`

**Comment by jirsbek** [comment] 2019-11-08 13:35
I can confirm @bpasero and @jccit solution – setting `"disable-color-correct-rendering": false` in `argv.json` works for me on macOS Catalina. Colors are bright again.

**Comment by varunj166** [comment] 2019-11-08 13:39
It seems to me the issue isn't with color vibrancy or brightness, but rather it's with text sharpness. An analogy would be paint bleed if you've used poor painter's tape. That is, on my screen, the colors are the same from 1.39.2 to 1.40.0; it's just that the text is slightly fuzzier/less sharp.

Screenshots:

1.39.2
![vs-code-1 39 2](https://user-images.githubusercontent.com/42119852/68480598-35dc2a00-0203-11ea-924d-504d4ad2a08c.png)

1.40.0
![vs-code-1 40 0](https://user-images.githubusercontent.com/42119852/68480610-3b397480-0203-11ea-975b-510f85b42dc5.png)

**Comment by bpasero** [comment] 2019-11-08 13:41
@jccit @jirsbek thanks a ton for trying. I am still a bit puzzled why simply commenting out the line does not help. Can you do this for me: configure the setting as:

`"disable-color-correct-rendering": "active"`

(ignore the error in the editor).

Does that also help after restart?

**Comment by jccit** [comment] 2019-11-08 13:44
@bpasero Just tested, setting it to `"active"` has the same effect as `false` for me. Colours are vibrant again

**Comment by bpasero** [comment] 2019-11-08 13:45
@varunj166 I have reopened https://github.com/microsoft/vscode/issues/84214 so that we can discuss blurry font rendering separate from this issue.

**Comment by jirsbek** [comment] 2019-11-08 13:48
@bpasero I can confirm the same as @jccit , `"disable-color-correct-rendering": "active"` works as well.

**Comment by offbeatful** [comment] 2019-11-08 14:19
@bpasero Thank you!!!! I can confirm the issue is resolved: "disable-color-correct-rendering": false
Windows 10.

The moment you realized that not everything can be easily covered with automated tests...

**Comment by somq** [comment] 2019-11-08 14:24
Same here

VSCode Version: 1.40.0
OS: Windows 10

**Comment by TheDutchCoder** [comment] 2019-11-08 14:45
Neither of hese solutions work for Mac OS Mojave on a non-retina (external) display, colors are still washed out.

**Comment by Geobert** [comment] 2019-11-08 16:29
`"disable-color-correct-rendering": false ` didn't work for me on Win 7, I'll test Win 10 once at home

**Comment by trananhmanh89** [comment] 2019-11-08 16:33
> `"disable-color-correct-rendering": false ` didn't work for me on Win 7, I'll test Win 10 once at home

Same, value are "active" or "false", both don't work.

windows 10,
here is screenshot, right is vscode 14, left is sublime 3
![2019-11-08_233329](https://user-images.githubusercontent.com/20571336/68493987-29e27d80-0280-11ea-8ee3-944a74f633c3.png)

**Comment by Geobert** [comment] 2019-11-08 18:23
> 
> 
> `"disable-color-correct-rendering": false ` didn't work for me on Win 7, I'll test Win 10 once at home

Win 10, doesn't help neither

**Comment by nklmilojevic** [comment] 2019-11-08 18:32
> Another try (for macOS users ONLY!):
> 
>     * open command palette
> 
>     * pick "configure runtime arguments"
> 
>     * comment out this line: `"disable-color-correct-rendering": true`
> 
>     * save
> 
>     * restart
> 
> 
> ![image](https://user-images.githubusercontent.com/900690/68478651-aa798d80-0230-11ea-8d2a-88d7688651a2.png)
> 
> ![image](https://user-images.githubusercontent.com/900690/68479040-ac901c00-0231-11ea-94f8-a740ee2dc14a.png)
> 
> Also related: does it change if you configure `"disable-hardware-acceleration": true`?

Tried on my my Mac, the fonts are still very thin and nowhere near the 1.39.2 version.

**Comment by KeWang323** [comment] 2019-11-08 19:06
`"disable-color-correct-rendering": false` doesn't work for my mac catalina
how do you guys set up those? @jjyyxx @jccit 
```
defaults write com.microsoft.VSCode CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper.EH CGFontRenderingFontSmoothingDisabled 0
defaults write com.microsoft.VSCode.helper.NP CGFontRenderingFontSmoothingDisabled 0
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

**Comment by dhowden** [comment] 2019-11-08 19:44
@bpasero @deepak1556 (Mojave, retina).  Using `"disable-color-correct-rendering": false` (or `"active"`) does improve things in 1.40, but it is still dimmer than the colour in 0.39.2:

1.40 (`"active")`:
<img width="1431" alt="1 40 0" src="https://user-images.githubusercontent.com/2822/68505565-a8104580-02bb-11ea-9516-1b86aa37a705.png">

1.39.2
<img width="1431" alt="1 39 2" src="https://user-images.githubusercontent.com/2822/68505566-a8104580-02bb-11ea-91c4-7d906d1a7b1c.png">

**Comment by deepak1556** [comment] 2019-11-08 20:43
Can everyone with the color profile issue try the latest insiders from https://code.visualstudio.com/insiders/ , which has a potential fix for the issue. Thanks!

**Comment by svipas** [comment] 2019-11-08 21:02
I don't know if that helps, but I took screenshots on my macOS.

- macOS Catalina 10.15.1 (19B88)
- MacBook Air (Retina, 13-inch, 2018)

# 1.39.2

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

<img width="1552" alt="1 39 2" src="https://user-images.githubusercontent.com/10441177/68510005-1680e380-027b-11ea-9615-4f4d55960f63.png">

# 1.40.0

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

<img width="1552" alt="1 40 0" src="https://user-images.githubusercontent.com/10441177/68510212-9018d180-027b-11ea-83c8-11d46eb764d0.png">

**Personally for me 1.40.0 is way better than 1.39.2**

**Comment by Geobert** [comment] 2019-11-08 21:06
> 
> 
> Can everyone with the color profile issue try the latest insiders from https://code.visualstudio.com/insiders/ , which has a potential fix for the issue. Thanks!

Still have the issue, Windows 10

**Comment by deepak1556** [comment] 2019-11-08 21:10
@Geobert I think the windows issue you are facing should be same as https://github.com/microsoft/vscode/issues/84214 , can you try https://github.com/microsoft/vscode/issues/84214#issuecomment-551842176 ?

**Comment by Geobert** [comment] 2019-11-08 21:12
> 
> 
> @Geobert I think the windows issue you are facing should be same as #84214 , can you try [#84214 (comment)](https://github.com/microsoft/vscode/issues/84214#issuecomment-551842176) ?

No luck (up is 1.39.2, down is insider):
![image](https://user-images.githubusercontent.com/72570/68510846-7623c280-026c-11ea-919a-f2794ec5c14d.png)

**Comment by SnosMe** [comment] 2019-11-08 21:19
![vscode](https://user-images.githubusercontent.com/4292308/68511189-0c141900-027e-11ea-960d-f07d691ad6af.gif)

**Comment by dhowden** [comment] 2019-11-08 21:48
> Can everyone with the color profile issue try the latest insiders from https://code.visualstudio.com/insiders/ , which has a potential fix for the issue. Thanks!

@deepak1556 (Mojave, retina) Insiders build is the same as setting `"disable-color-correct-rendering": "active"` in 1.40 for me (so better, but still not the same as 1.39.2 https://github.com/microsoft/vscode/issues/84154#issuecomment-551964831)

**Comment by deepak1556** [comment] 2019-11-08 21:56
Thanks for trying it out, the color profile should be same as 1.39.2 with insiders and this fix will land in our recovery stable build soon, as the for the thin icon sizes on macOS we are looking into it currently, will get back if needed more info on this. And for the blurred font rendering on windows and linux would like to follow up on https://github.com/microsoft/vscode/issues/84214

**Comment by tgani-msft** [comment] 2019-11-09 00:49
This looks like the same issue I've been seeing #82733 

Files I added to the original issue seem to have compression artifacts but I have new ones at:

https://i.imgur.com/pTQt24d.png
https://i.imgur.com/65TNmYv.png

It's easy to see the fuzziness in the VS Code rendering compared to VS. In fact if the Zoom dropdown (lower left corner) is used in VS, I get rendering identical to VS Code. I suspect ClearType antialiasing (I'm on Windows) is not being used by VS Code while VS does use it unless zoomed.

**Comment by nvmnghia** [comment] 2019-11-09 03:10
Did anyone notice the rendering of powerline font in the terminal isn't accurate anymore? I'm using 1.40 on Mojave.

![Screen Shot 2019-11-09 at 10 09 01 AM](https://user-images.githubusercontent.com/22721156/68522000-10b9eb00-02d9-11ea-85ba-103d2fae2a08.png)

**Comment by enkia** [comment] 2019-11-09 05:10
Insiders seems to fix the desaturated color issue on macOS Catalina 10.15.1 Retina.

1.40.0:
![image](https://user-images.githubusercontent.com/255730/68523307-3917fa00-0285-11ea-8b6c-9d18f92bf222.png)

Insiders:
![image](https://user-images.githubusercontent.com/255730/68523312-48974300-0285-11ea-9260-8c5e7593a19b.png)

**Comment by dhowden** [comment] 2019-11-09 05:43
@enkia Can you do a comparison to the rendering from 1.39.2?  Although it's not as bad, the colours for me still get dimmer moving from 1.39.2 -> 1.41 (insiders).

**Comment by enkia** [comment] 2019-11-09 14:50
> @enkia Can you do a comparison to the rendering from 1.39.2? Although it's not as bad, the colours for me still get dimmer moving from 1.39.2 -> 1.41 (insiders).

Yes, I downgraded last night, heh. Edited comment to reflect 1.39.2, but the PNGs don't do justice to the drastic change in color *on screen* from 1.40 to Insiders/1.39.2, though. I'm tabbing right now through both Insiders and 1.39.2 and can't tell the difference.  I feel like I could tell in a heart beat because I've obsessed over every color in ever corner of the theme I'm using for a couple months.

**Comment by bhughes339** [comment] 2019-11-09 20:22
> 
> 
> Can everyone with the color profile issue try the latest insiders from https://code.visualstudio.com/insiders/ , which has a potential fix for the issue. Thanks!

Windows 10, Insiders 1.41.0-insider looks exactly the same as 1.40.0 as shown in my comment https://github.com/microsoft/vscode/issues/84154#issuecomment-551248418

**Comment by nguyentanphu** [comment] 2019-11-10 03:59
Definitely the color seems to be dimmer. Any workaround except downgrading? :(

**Comment by extratype** [comment] 2019-11-10 08:42
For Windows users add these settings

```json
{
  "editor.disableLayerHinting": true,
  "window.titleBarStyle": "native",
}
```
It's being discussed in #84214.

**Comment by nklmilojevic** [comment] 2019-11-10 15:00
Can we have a separate issue for the font problems for macOS (Catalina)? Seems like most of these fixes are related only for Windows/or color degradation.

**Comment by bpasero** [comment] 2019-11-10 15:18
I am going to close this issue as a fix has been rolled out both to our recovery release (coming this week) as well as insiders where the fix can be tested. 

Nevertheless, there are still issues floating around from the Electron 6 update that are either independent from this issue or just another regression that we have not fully understood yet. The most likely issue you are still seeing is captured in https://github.com/microsoft/vscode/issues/84214 where fonts appear blurry. I suggest to move the discussion over to that issue for users seeing it.

If you think that your issue is not captured by https://github.com/microsoft/vscode/issues/84214 and still not fixed in latest insider release (https://code.visualstudio.com/insiders/) then I ask you to please report a new issue and be as descriptive as possible. 

Thanks 👍

**Comment by nklmilojevic** [comment] 2019-11-10 15:20
Btw. I was able to replicate old font settings from 1.39.2 on 1.40 by installing vscode-custom-css and loading this custom css:

```body,
.editor {
  -webkit-text-stroke: .05em;
}```

I would hate to use this hack all the time, but it would be really nice if we can set text-stroke option via VSCode directly.

**Comment by Geobert** [comment] 2019-11-10 16:06
Testing insider and I don't agree that the issue is fixed:
up is 1.39.2 and down is 
Version: 1.41.0-insider
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1
Date: 2019-11-08T19:12:35.358Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
![image](https://user-images.githubusercontent.com/72570/68546930-fb75b700-03d3-11ea-8883-cfd96403b901.png)

The color is still dimmed compared to 1.39.2.

**Comment by dhowden** [comment] 2019-11-10 21:45
@bpasero @deepak1556 1.39.2 and 1.41-insider are not the same colour profile on my machine, the 1.39.2 rendering is still brighter.  How are you checking that they are the same?  Can I reproduce that on my machine?

1.39.2

<img width="1401" alt="Screen Shot 2019-11-11 at 8 38 49 am" src="https://user-images.githubusercontent.com/2822/68551232-e7c36280-045e-11ea-8f8f-6502a4d4f3d2.png">

1.41-insider
<img width="1400" alt="Screen Shot 2019-11-11 at 8 41 39 am" src="https://user-images.githubusercontent.com/2822/68551278-543e6180-045f-11ea-8099-4607ef884ee2.png">


```
Version: 1.41.0-insider
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1
Date: 2019-11-08T19:11:22.061Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by bpasero** [comment] 2019-11-11 06:35
Maybe I should have been clearer: VSCode has always been setting the following Chrome command line argument: `disable-color-correct-rendering` [1]. Unfortunately due to some changes I pushed during the milestones, this flag was no longer applied correctly (see https://github.com/microsoft/vscode/pull/84320 for more context). Meanwhile insiders got a fix to bring back this flag properly as it used to be. 

Closing this issue means we have a chance to signal that a change was made and that we can verify it. It does not mean (as I stated in my comment before) that all the regressions from the Electron 6 update are solved yet. As such, I asked for creating new issues for the remaining color/font problems you see. Thanks!

[1] More context:
* https://github.com/Microsoft/vscode/issues/51791
* https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40/edit
* https://github.com/electron/electron/issues/10732

**Comment by jesperjohansson** [comment] 2019-11-11 08:36
Temp. font color issue fix for MacOS:
* Open command palette and type "Configure Runtime Arguments" to open the `argv.json` file
* Set `"disable-color-correct-rendering"` to `false` and save
* Restart VSCode entirely (not just reload window)
```jsonc
// argv.json
{
  "disable-color-correct-rendering": false
}
```

**Comment by MariuzM** [comment] 2019-11-11 11:54
So color is one thing what about getting thin font rendering?

**Comment by rmtracey** [comment] 2019-11-11 16:19
It's good that there's still an open issue for the blurriness, but is there an open issue for the colors anywhere? None of the suggestions in this thread have fixed the dull colors for me, and they're still dull on the Insiders build as well. Or do the dull colors and blurriness have the same root cause (as in fixing the blurriness will fix the colors)?

**Comment by MariuzM** [comment] 2019-11-11 16:24
> It's good that there's still an open issue for the blurriness, but is there an open issue for the colors anywhere? None of the suggestions in this thread have fixed the dull colors for me, and they're still dull on the Insiders build as well. Or do the dull colors and blurriness have the same root cause (as in fixing the blurriness will fix the colors)?

This fixed the colors   "disable-color-correct-rendering": false

**Comment by rmtracey** [comment] 2019-11-11 16:27
> > It's good that there's still an open issue for the blurriness, but is there an open issue for the colors anywhere? None of the suggestions in this thread have fixed the dull colors for me, and they're still dull on the Insiders build as well. Or do the dull colors and blurriness have the same root cause (as in fixing the blurriness will fix the colors)?
> 
> This fixed the colors "disable-color-correct-rendering": false

In the argv.json? I tried that, didn't work for me. Going by the comments in this thread it seems like that only fixes the issue for some people, not all.

**Comment by bpasero** [comment] 2019-11-11 16:30
@rmtracey can you try how it looks like on insiders?

**Closed by bpasero** 2019-11-11 16:30 UTC
Labels: bug, candidate, electron, electron-6.0.x-update, font-rendering, mac, regression, upstream

**Comment by rmtracey** [comment] 2019-11-11 16:34
@bpasero Yup, I've tried insiders. 1.41.0-insider, Windows 10 1809. Colors are still dull and blurry compared to 1.39.2, no matter what I set `disable-color-correct-rendering` to. I've tried `true`, `false`, and `"active"`, no difference.

**Comment by bpasero** [comment] 2019-11-11 16:43
@rmtracey (any anyone else), it is crucial that you keep the file as it used to be for this to work, the only correct value is:

`"disable-color-correct-rendering": true`

So please anyone that is still seeing this issue in insiders, make sure you have it configured as such.

**Comment by MariuzM** [comment] 2019-11-11 16:48
> @rmtracey (any anyone else), it is crucial that you keep the file as it used to be for this to work, the only correct value is:
> 
> `"disable-color-correct-rendering": true`
> 
> So please anyone that is still seeing this issue in insiders, make sure you have it configured as such.
> 
> Finally please feel free to report a new issue if you can still reproduce and we can follow up there.

? For my only using in 1.40 "disable-color-correct-rendering": false fixed the washed out colors.
Only issue I'm still having is thin fonts.
Mojave

**Comment by bpasero** [comment] 2019-11-11 16:54
We still have https://github.com/microsoft/vscode/issues/82109 for thin font rendering. 

I think this thread is going into weird directions, I am going to lock it and put one last comment:

**You can benefit from a fix now if you use VSCode Insiders (https://code.visualstudio.com/insiders/) and configure `"disable-color-correct-rendering": true` (this should be the default). If you change this value, it is only applied after a restart.

This fix will roll out to VSCode stable this week. 

If you still see an issue where colors look washed out, feel free to report as new issue.**
