### ISSUE TITLE
Closing comment broken by regexp */

### ISSUE THREAD

**Issue by inuyaksa** [Microsoft/vscode#55632] opened 2018-08-02 08:06 UTC
- VSCode Version: 1.25.1
- OS Version: Windows Version 10.0.17134.165

Steps to Reproduce:

1. comment area with regexp that includes "*/" token (tested on PHP file)

Does this issue occur when all extensions are disabled?: Yes/No
No extensions implied

![code_issue1](https://user-images.githubusercontent.com/444506/43570869-c07faf18-963b-11e8-9c99-3c1190aad715.png)

**Comment by aeschli** [comment] 2018-08-02 12:45
Reproduced with
```php
<?php

/*

$e = '*/';

var x

*/
```

**Comment by aeschli** [comment] 2018-08-02 13:00
Syntax highlighting is acyually fine here, the comment really ends as soon as `*/` occurs. The content inside a comment is just considered as bare text, regardless if it looks like string or regex literal, just text.

Our 'add block comment' code is not looking at the text it comments if it contains a `*/` sequence.  It's up to the user to undo the action and use `add line comment instead.

Duplicate of #29015

**Closed by aeschli** 2018-08-02 13:00 UTC
Labels: extensions
