### ISSUE TITLE
有中文字符时 Tab键对齐代码有Bug

### ISSUE THREAD

**Issue by 1988wj** [Microsoft/vscode#9105] opened 2016-07-12 00:31 UTC
- VSCode Version: 1.1
- OS Version: win7 sp1

Steps to Reproduce:
------------显示效果如下-------------
CREATE TABLE `Place`(
	`ID`                        int                         NOT NULL,
	`Comment`            varchar(512)         NULL,
	`UpdateTime`        timestamp            NOT NULL,
	`地名`                  varchar(64)          NOT NULL,
	`全名`                  varchar(64)          NOT NULL,
	`行政区划`               varchar(64)            NOT NULL,
	`地址`                   varchar(128)       NOT NULL,
	`关键字`                  varchar(128)        NOT NULL,
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=utf8 COMMENT='地址地名模型(数据库)8';

**Comment by bingzheyuan** [comment] 2016-07-12 08:24
O.O 居然用中文做列名....

**Comment by ZCShou** [comment] 2016-07-12 08:55
发了这么多次英文，终于见到直接中文反馈的了！！！

**Comment by Treri** [comment] 2016-07-12 09:31
You should use english, and best have a screenshot for the problem code.

**Comment by TWOWhite** [comment] 2016-07-12 09:32
666,一大片英文里面出了个中文

**Comment by rebornix** [comment] 2016-07-12 09:42
@1988wj @ZCShou 没关系，我刚好不是老外 :) 不过你能提供更多信息吗，比如截屏和重现的步骤。我编辑 sql 文件，逐行添加以上 sql 语句，并未见到对齐的问题。

We can mark it as Need More Info as there is still no repro steps.

**Comment by weinand** [comment] 2016-07-12 09:47
@1988wj please provide detailed steps (in English).

**Comment by ZCShou** [comment] 2016-07-12 10:05
@rebornix (⊙o⊙)…  枉发了好几次英文的！！ 不知道，他说的问题是不是 说 在SQL 中，Tab 对齐时，空位只有其他的一半！

**Comment by 1988wj** [comment] 2016-07-13 04:36
在"记事本"中可以实现 数据类型,及后面关键字 多行垂直对齐
而在"VSCode"中有中文的行和没中文行(或中文字数不同)是无法实现 多行垂直对齐的
(英文太差只能用中文描述问题,
用中文可以很容易用固定字数做字段名,在程序中批量赋值完全对齐更美观,
更关键是没这么多英文词汇来命名字段或变量)
--------谢谢大家的回复

2016-07-12 18:06 GMT+08:00 ZCShou <notifications@github.com>:

**Comment by weinand** [comment] 2016-07-13 08:10
bing translate:

In the "Notepad" data type can be realized and a keyword line vertical alignment
And in "VSCode" in Chinese and not Chinese lines in (or Chinese words different) cannot be achieved multiple lines of vertical alignment
(English is too poor in Chinese only description of the problem,
Can easily be fixed in Chinese Word field name batch assignment in your program aligns perfectly beautiful,
More key English vocabulary is not so much to rename fields or variables)
--------Thank you all for your replies

**Comment by eriawan** [comment] 2016-07-13 08:25
@weinand 

Let me help you to translate some of this issue. The title means:
"A **bug**: when we use **Tab** key when there are Chinese characters".

The steps are not detailed enough. He/she seems to use VS Code to edit a SQL script. Too bad the issue poster don't provide us the plugin he/she used and what the bug really is.

**Comment by weinand** [comment] 2016-07-13 08:28
@eriawan thanks a lot for your help. Since the issue is about tabs and alignment, I don't think that this is affected by an extension he is using. It sounds more like a general issue with tabs and alignment in Chinese.

**Comment by alexandrudima** [comment] 2016-07-13 08:45
Hi, I would kindly appreciate some steps, written like for dummies :)

Here are some good examples when it comes to input in different languages. I would very much appreciate if someone could help me and formulate the bug in a style similar to the test steps at https://github.com/Microsoft/vscode/wiki/IME-Test

> Note how all the steps are entirely spelled out and supporting images/gifs are used to explain what should happen, etc.

Thanks!

**Comment by rebornix** [comment] 2016-07-13 08:58
I understand his problem now. What he wants is aligning words vertically the same way as Column in Table. When the words are all English, we can use Tab to archive this target while if you put some Chinese characters in the line, the vertical is not pixil perfect 

Besides he mentioned the vertical alignment for words works perfectly in Notepad, but no luck with VS Code. I'm not sure if it's true and I will provide screenshots once I recevied my Windows laptop tonight.

**Comment by alexandrudima** [comment] 2016-07-13 09:03
@rebornix Thank you! In that case, it could be a dup of #1727

**Comment by rebornix** [comment] 2016-07-13 15:21
![image](https://cloud.githubusercontent.com/assets/876920/16808734/3dd082f2-4950-11e6-9a31-8bbfa2578e81.png)

@alexandrudima see above image and the last line of code, it's a dup of #1727 indeed.

@1988wj Please refer to #1727 for further update and thanks for your reporting.

**Closed by rebornix** 2016-07-13 15:21 UTC
Labels: needs more info

**Comment by eriawan** [comment] 2016-07-14 06:49
@rebornix you are right! It is actually a duplicate of #1727

:+1:
