### ISSUE TITLE
ERROR in update-localization-extension

### ISSUE THREAD

**Issue by okineadev** [microsoft/vscode#201711] opened 2024-01-03 10:52 UTC
WHY is this command not working?!

`@okineadev ➜ /workspaces/vscode $ npm run update-localization-extension -- --location="../vscode-translations-import/uk" uk`

```
> code-oss-dev@1.86.0 update-localization-extension
> node build/npm/update-localization-extension.js --location=../vscode-translations-import/uk uk

Importing translations for uk form '../vscode-translations-import/uk' to '../vscode-loc/i18n/vscode-language-pack-uk/translations' ...
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at /workspaces/vscode/build/npm/update-localization-extension.js:76:56
    at Array.map (<anonymous>)
    at /workspaces/vscode/build/npm/update-localization-extension.js:76:32
    at Array.forEach (<anonymous>)
    at update (/workspaces/vscode/build/npm/update-localization-extension.js:48:16)
    at Object.<anonymous> (/workspaces/vscode/build/npm/update-localization-extension.js:106:2)
    at Module._compile (node:internal/modules/cjs/loader:1356:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.0
```

**Comment by TylerLeonhardt** [comment] 2024-01-11 15:58
marking as a duplicate of https://github.com/microsoft/vscode-loc/issues/1535 for now... since we really just need better docs.

**Closed by TylerLeonhardt** 2024-01-11 15:58 UTC
