### ISSUE TITLE
Editor context menu is hard to close

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#137831] opened 2021-11-24 23:07 UTC
On the latest Insiders on Windows 10:

1. Open an editor
2. Right-click on it. A context menu should appear
3. Click on part of the editor that's not the context menu
4. :bug: The context menu is still there
5. Press the escape key while the mouse is not over the context menu
6. :bug: The context menu is still there
7. Press the escape key while the mouse is over the context menu
8. The context menu finally closes

![Screencap](https://user-images.githubusercontent.com/7199958/143323788-c610f763-358d-4fab-9596-01899777402e.gif)

**Comment by gjsjohnmurray** [comment] 2021-11-24 23:24
/duplicate of #137785 and fixed ready for tomorrow.

**Closed** 2021-11-24 23:24 UTC
Labels: *duplicate
