### ISSUE TITLE
[BUG] Marketplace extension page goes over title bar

### ISSUE THREAD

**Issue by roberthmiller** [microsoft/vscode#84321] opened 2019-11-08 21:25 UTC
Issue Type: <b>Bug</b>

Go to python extension page: `ms-python.python`.

View overlap of page content on top of bottom bar.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.3.0-19-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3342)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|31.09GB (20.76GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.6
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
vscode-pull-request-github|Git|0.12.0
git-graph|mhu|1.18.0
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
remote-containers|ms-|0.83.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
Go|ms-|0.11.9
vsliveshare|ms-|1.0.1123
gi|rub|0.2.11
quokka-vscode|Wal|1.0.259

(4 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/23535075/68511539-334df480-0244-11ea-8cd0-02a714b2558a.png)

**Comment by mjbvz** [comment] 2019-11-08 22:58
Duplicate of #83209

**Closed by mjbvz** 2019-11-08 22:58 UTC
Labels: new release
