### ISSUE TITLE
File path not pasted from file manager in Linux

### ISSUE THREAD

**Issue by hengwang322** [microsoft/vscode#155453] opened 2022-07-18 02:53 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Copy a file from Nautilus in Ubuntu
2. Paste into VSCode

Expected Behaviour: 
The full file path is pasted, as is the behaviour prior to 1.66.0, and standard in most Linux environment

Actual Behaviour:
Only the file name is pasted. 

Related issue: [#146770](https://github.com/microsoft/vscode/issues/146770)

**Comment by mjbvz** [comment] 2022-07-21 23:35
Is the file you are coping part of the currently opened workspace?

**Comment by hengwang322** [comment] 2022-07-22 00:08
> Is the file you are coping part of the currently opened workspace?

No, it is not. It affects any file from anywhere on the drive.

**Comment by Rio-Proton** [comment] 2022-08-15 18:28
Ubuntu 22.04, code v70, nautilus file manager.
The only viable daily use workaround I've found is to revert to code v65 which deprives my use of later versions. In testing code v70, I had to copy from nautilus, paste to gedit then copy from gedit to code demonstrating that nautilus is picking up the full path and that code is not pasting what was copied.

Perhaps the ideal solution would be to have code provide two alternatives: paste fullpath; paste filename only. This would add flexibility that would help in my situation writing documentation because quoting the fullpath once can usually be followed by a second reference using filename only. An option might be offered as a code setting (use one, the other, both) for a context menu choice or user defined keyboard shortcuts.

**Comment by Rio-Proton** [comment] 2022-09-02 21:31
Ubuntu 22.04, code v71, nautilus file manager.
In nautilus I can select a file or folder, right click, Copy. Then switch to code, open Terminal in code and paste to the command line and the full path copy, as desired, is pasted. Just another example that the problem is narrowed to not being able to paste the full path, in my case, to code "Plain Text" and "Shell Script" documents.

**Comment by mjbvz** [comment] 2022-09-21 20:31
Duplicate of #159525 based on the description

**Closed by mjbvz** 2022-09-21 20:31 UTC
Labels: info-needed
