### ISSUE TITLE
Powershell is always the default/first terminal

### ISSUE THREAD

**Issue by EdSF** [microsoft/vscode#133014] opened 2021-09-13 17:25 UTC
Issue Type: <b>Bug</b>

1) Start VS Code
2) Open a folder or workspace (any)
3) The terminal that first comes up is Powershell
4) Change your default terminal settings (e.g. bash)
5) Exit and start at step1

Result:
No change, Powershell still comes up.

Additonal:
- close powershell (or the trash can)
- start a *new* terminal - this is where your "default" settings start working (e.g. if bash then its a bash terminal)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (19.56GB free)|
|Process Argv|--crash-reporter-id 97406e11-8f3f-4c10-9bfb-0d2d3b0be9c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.43.2
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.15
docs-build|doc|0.3.6
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.97
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.11
docs-visual-areas|doc|0.2.1
docs-yaml|doc|0.2.7
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.191.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.613
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
mssql|ms-|1.10.1
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2021.9.417
powershell|ms-|2021.9.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.2
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
vetur|oct|0.34.1
vscode-jest|Ort|4.1.2
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
code-spell-checker|str|2.0.4

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by olivier-b-be** [comment] 2021-09-13 17:31
Same here, very annoying

**Comment by c-shubh** [comment] 2021-09-13 17:35
Duplicate of #132150.

**Closed** 2021-09-13 18:18 UTC
Labels: *duplicate

**Comment by EdSF** [comment] 2021-09-13 20:50
Sorry about that - used VS Code submit issue feature (didn't have a chance to search first.)..

Thank you!
