### ISSUE TITLE
Visual Studio Code Webview Resources not loading in the latest Insiders release

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#139544] opened 2021-12-21 00:38 UTC
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.64.0-insider (system setup)
提交: 807bf598bea406dcb272a9fced54697986e87768
日期: 2021-12-20T07:18:13.749Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22523

https://github.com/mhutchie/vscode-git-graph/issues/604#issuecomment-998355043

>and I believe  there is something related to vscode-insiders.
>I have two PC, and both of them have same problem within vscode-insider and both of them work well within vscode-stable
>BTW, we could see the full view of git-graph and after some view-switching, git-graph crash randomly.
there is a screen-record gif:
>![git-graph](https://user-images.githubusercontent.com/1876302/146847794-db3d6070-faa6-4b2a-9106-d0df5654277e.gif)
>hope that will help to debug

**Comment by mhutchie** [comment] 2021-12-21 01:24
I'm the author of the Git Graph extension.

The behaviour observed occurs when Visual Studio Code Insiders doesn't provided the necessary JavaScript & CSS resources that the extension requests when the [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview) is loading / reloading. What you see in this screenshot is the base HTML of the Webview - as soon as the required Javascript and/or CSS are provided by Visual Studio Code, the interface would immediately be rendered as expected.

![image](https://user-images.githubusercontent.com/1876302/146793991-5a01685c-329d-4080-834c-9f18e32f0c47.png)

When the user first opens the Git Graph View (Webview), or it becomes visible again, the extension sets the HTML of the Webview. Based on the screen recording from @heartacker, it clearly indicates that the JavaScript & CSS resources that are requested by Git Graph do exist on the file system. There must be an issue introduced into Visual Studio Code Insiders 1.46 when Webviews are restored, where Visual Studio Code doesn't provide the requested resources.

I can't manage to replicate the same behaviour using the same Visual Studio Code Insider build, so this issue only affects some users in the latest Insiders build.

**Comment by Fuahi** [comment] 2021-12-26 09:54
![image](https://user-images.githubusercontent.com/96672063/147404721-059fa7ff-6a7a-4037-87bb-2da4ee0cc37f.png)
same problem

please


版本: 1.64.0-insider (system setup)
提交: 7b9e5c32a053669d4e72f998e4fa217090c32f59
日期: 2021-12-22T05:15:28.225Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by mjbvz** [comment] 2022-01-03 23:04
I can't reproduce this. If you are seeing this issue, please run `Toggle Developer tools` and share the logs from the developer tools console so we can investigate the issue

**Comment by heartacker** [comment] 2022-01-04 02:07
[vscode-app-1641261558406.log](https://github.com/microsoft/vscode/files/7804962/vscode-app-1641261558406.log)
seem that there is no effective information when WebView  crash

**Comment by BradL-Msft** [comment] 2022-01-04 19:49
+1 repro for this.

**Comment by heartacker** [comment] 2022-01-05 15:18
[vscode-app-1641395653341.log](https://github.com/microsoft/vscode/files/7815845/vscode-app-1641395653341.log)
I have provided two log when git -graph crash
@mjbvz what can I do more now.

**Comment by heartacker** [comment] 2022-01-06 08:21
maybe same issue
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/560

**Comment by heartacker** [comment] 2022-01-11 16:06
seems that  this issue is disappeared
with the version

版本: 1.64.0-insider (system setup)
提交: 00f1ca47ada2fda8ee1437e17b27af5b4002cecb
日期: 2022-01-11T09:15:49.397Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22523

**Comment by heartacker** [comment] 2022-01-11 16:06
@mjbvz

**Comment by mjbvz** [comment] 2022-01-11 20:53
Thanks for testing. Fixed by #140351

**Closed by mjbvz** 2022-01-11 20:53 UTC
Labels: needs more info

**Comment by mjbvz** [comment] 2022-01-29 00:35
@heartacker Can you please verify that this has been fixed in the latest insiders?

**Comment by heartacker** [comment] 2022-01-29 04:59
YES, It works well 👯

**Comment by heartacker** [comment] 2022-02-25 12:06
![image](https://user-images.githubusercontent.com/1876302/155712246-c8bdcc9e-b24e-45d2-bc00-c3a25da29093.png)

this issue reappears;

版本: 1.65.0-insider (system setup)
提交: 8440b8f47231147823ba9696913d642e5f2d9d58
日期: 2022-02-25T05:17:33.544Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393

@mjbvz
