### ISSUE TITLE
Inline PHP tag brokes HTML highlight

### ISSUE THREAD

**Issue by evsar3** [Microsoft/vscode#15247] opened 2016-11-09 16:35 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Create a new PHP file
2. Insert an inline php tag into a `<script>` tag
3. Insert some HTML code

It brokes the highlight of the HTML code.

![screenshot_vscode_issue1](https://cloud.githubusercontent.com/assets/1992754/20146076/9d95436c-a689-11e6-9b1e-26941f2e15fa.jpg)

![screenshot_vscode_issue2](https://cloud.githubusercontent.com/assets/1992754/20146080/a311a3bc-a689-11e6-8202-6a228500d9de.jpg)

**Comment by aeschli** [comment] 2016-11-09 19:05
@evsar3 Can you paste the code snippet that shows this? Thanks!

**Comment by evsar3** [comment] 2016-11-09 19:36
Absolutely!
[vscode_issue_snippet.txt](https://github.com/Microsoft/vscode/files/581678/vscode_issue_snippet.txt)

**Comment by aeschli** [comment] 2016-11-24 09:41
duplicate of Microsoft/vscode#15792

**Closed by aeschli** 2016-11-24 09:41 UTC
