### ISSUE TITLE
Terminal: broken text layout

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#19665] opened 2017-02-01 09:38 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (fcac9b686abe4292e69a774f61c8c4ce17768bf5, 2017-01-31T00:57:46.157Z)
- OS Version: Windows_NT ia32 10.0.15019
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|theme-dracula|dracula-theme|1.2.5|
|vscode-great-icons|emmanuelbeziat|1.1.38|
|Theme-azure|gerane|0.0.2|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.3.2|
|Theme-MaterialKit|ms-vscode|0.1.1|
|view-in-browser|qinjia|0.0.4|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|eval|Stormspirit|0.0.5|
|omnipascal|Wosi|0.12.0|

---

Steps to Reproduce:

1. running grunt test to run unit testing should produce this output: (here in cmd.exe)

![terminal_cmd](https://cloud.githubusercontent.com/assets/199648/22501588/be167170-e869-11e6-9d5b-5b45814172a8.png)

Here is what I got in VSCode integrated terminal:

![terminal_code](https://cloud.githubusercontent.com/assets/199648/22501601/ca04d54e-e869-11e6-8118-b8800dd19df7.png)

Note that the first time I ran it, the layout of the prompt was also broken, instead of the cursor directly following the prompt, like:

![cursor_ok](https://cloud.githubusercontent.com/assets/199648/22501740/6eab812e-e86a-11e6-94d6-4a05dbee6e98.png)

I was having:

![cursor_bad](https://cloud.githubusercontent.com/assets/199648/22501749/741d99bc-e86a-11e6-9cc5-ffa44f343061.png)

(and I could not move the cursor more on the left)

**Comment by Tyriar** [comment] 2017-02-01 16:04
What's in your settings.json file and was there any errors in the dev tools console?

**Comment by warpdesign** [comment] 2017-02-01 16:18
There were no errors in the console.

My settings.json file:

```
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.lineHeight": 1.3,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.openFilesInNewWindow": false,
    "window.reopenFolders": "one",
    "typescript.check.tscVersion": false,
    "workbench.sideBar.location": "left",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",
    "terminal.integrated.rightClickCopyPaste": false
}

```

**Comment by warpdesign** [comment] 2017-02-01 16:26
Here is what the inspector looks like (note the prompt that seems to get shifted to the right (the begining of the prompt's tech is in the previous div). Hope this helps.

![bugterminalvscode](https://cloud.githubusercontent.com/assets/199648/22515684/9ba69450-e8a3-11e6-88f4-8a707b4307bf.png)

**Comment by warpdesign** [comment] 2017-02-03 09:57
More information: this didn't happen with VSCode 1.8.1, but happens with the latest final 1.9 build as well.

Running a simple `sudo apt-get install package` is enough to trigger the problem:

![bug_terminal](https://cloud.githubusercontent.com/assets/199648/22586918/90b6ac08-e9ff-11e6-86c6-9c2a84076fe5.png)

**Comment by CaselIT** [comment] 2017-02-03 13:10
I have the same issue, when using `mocha` to test something.
If needed I can add a simple repo to reproduce

Below is my configuration:
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.15019
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|docthis|joelday|0.3.10|
|PowerShell|ms-vscode|0.9.0|
|typescript-javascript-grammar|ms-vscode|0.0.18|

**Comment by CaselIT** [comment] 2017-02-03 13:40
I've noticed that both @waderyan and me are running Windows 10 preview 15019.
I've tried to reproduce it on a normal version of windows 10 and could not. So the fault may be in the preview of windows.

Below is the configuration of my other machine where I could not reproduce the bug
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.6|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|docthis|joelday|0.3.10|
|vscode-filesize|mkxml|1.0.0|
|PowerShell|ms-vscode|0.9.0|
|typescript-javascript-grammar|ms-vscode|0.0.18|

**Comment by CaselIT** [comment] 2017-02-03 18:16
I'm able to reproduce it on another pc with windows 15019

**Comment by Tyriar** [comment] 2017-02-04 00:05
This could be related to the terminal not printing unicode characters correctly https://github.com/Microsoft/vscode/issues/19763? If you can reproduce what locale are you using? Could you also post a screenshot of VS Code terminal bad output via good output in cmd?

**Comment by CaselIT** [comment] 2017-02-04 00:34
My locale is us. The normal terminal works fine
![image](https://cloud.githubusercontent.com/assets/16175304/22613383/31587ae2-ea78-11e6-9d43-af9782b84a71.png)
I've noticed that the problem occurs only when the terminal is larger than about 1200px see images:
Here is fine and the terminal is 1208px
![image](https://cloud.githubusercontent.com/assets/16175304/22613497/0cc75e68-ea79-11e6-9ce5-6df56280e710.png)
here it does not render correctly, the size is 1240px
![image](https://cloud.githubusercontent.com/assets/16175304/22613554/8404b66a-ea79-11e6-97da-7d8b20a9be76.png)

Let me know if you need some other tests

**Comment by CaselIT** [comment] 2017-02-04 00:39
Also resizing the window horizontally causes multiple times randomly problems
In the output below is should be as in the images in the previous post
![image](https://cloud.githubusercontent.com/assets/16175304/22613691/b37051a6-ea7a-11e6-9b90-84cb28a89fcd.png)

**Comment by Tyriar** [comment] 2017-02-04 01:09
Do you see the problem only after resizing? Maybe related to https://github.com/Microsoft/vscode/issues/8336

**Comment by CaselIT** [comment] 2017-02-04 01:18
The one in the last image yes. 
The other problems are always there if the terminal is larger than about 1200px. (I don't know if the measure is connected to the screen resolution)

**Comment by CaselIT** [comment] 2017-02-04 10:29
I've tried on my other pc, that has a screen of 1600x900px and the behavior is the same, above about 1200px the terminal begins to have problems.

**Comment by CaselIT** [comment] 2017-02-09 09:23
I've updated on v1.9.1 and the issue is still there.

**Comment by warpdesign** [comment] 2017-02-10 14:50
Update: I'm still having the problem with latest VSCode insider (2017-02-10T07:10:40.518Z) & latest Windows 10 insider build (15031).

**Comment by asvetliakov** [comment] 2017-02-10 23:51
Actually the terminal is pretty unusable for me:
![capture](https://cloud.githubusercontent.com/assets/8881674/22848363/21b2d584-eff4-11e6-8cb3-2281be5f1376.PNG)

**Comment by fess932** [comment] 2017-02-13 12:14
Actually the terminal is unusable for me too:
![r4d4h2c 1](https://cloud.githubusercontent.com/assets/17965077/22883017/190b877a-f1ff-11e6-8b59-a359410c5150.png)

**Comment by CaselIT** [comment] 2017-02-13 12:21
@fess932 @asvetliakov are you both using win 10 preview like me and @warpdesign ?

**Comment by fess932** [comment] 2017-02-13 12:31
@CaselIT Yes. This problem is only in win 10 preview?

**Comment by CaselIT** [comment] 2017-02-13 12:36
It appears to be from the people on this issue. Also I've tries using same vscode version and the same terminal command and on the preview I have the problem while on the normal win10 version I have not.

**Comment by warpdesign** [comment] 2017-02-13 12:57
@CaselIT @fess932 I am using win 10 preview too.

Note that with cmd.exe there are no such problems.

**Comment by CaselIT** [comment] 2017-02-13 13:05
>Note that with cmd.exe there are no such problems.

Sadly I have them also using cmd.

**Comment by warpdesign** [comment] 2017-02-28 10:31
@Tyriar What's the status of this bug? Do you need more information?

It really makes the terminal difficult to use since most commands will break the output like this.

It seems to happen only in insider builds but the final "Creators Update" update is supposed to be released in a few weeks only.

**Comment by Tyriar** [comment] 2017-03-01 18:58
@warpdesign I haven't been able to repro, if it's related to Insiders then that's the reason.

@miniksa @bitcrazed any idea what this could be related to? It only appears to happen on Window Insiders.

**Comment by bitcrazed** [comment] 2017-03-01 19:27
@Tyriar This also appears to repro in 14393 as per @CaselIT's report [above](https://github.com/Microsoft/vscode/issues/19665#issuecomment-277248806).

Struggling to repro here. 

Can someone pipe command output into a file that can be echoed locally to repro? Or perhaps provide a minimalist repro?

**Comment by CaselIT** [comment] 2017-03-01 19:31
@bitcrazed I've just tried on 15042 and it still has the problem.

Regarding how to reproduce the mocha output always breaks it for me, so it should be sufficient to run write some fake tests. If you can't reproduce it, I'll try to set up a repo to reproduce later or tomorrow

**Comment by CaselIT** [comment] 2017-03-01 20:38
I've added a repo
https://github.com/CaselIT/vscode-bug-19665

As mentioned before and also in the repo readme if the terminal windows is smaller than ~1200px everything works fine

**Comment by CaselIT** [comment] 2017-03-02 08:53
Just tried vscode 1.10.1 and I have the same issue

**Comment by warpdesign** [comment] 2017-03-02 13:04
@bitcrazed Here is an exemple file.

I ran `sudo apt-get install <some non existing package>` and this was enough to break the layout.

Here is the output of the command (doing cat test.txt is enough to break the layout here).

[test.txt](https://github.com/Microsoft/vscode/files/813829/test.txt)

**Comment by warpdesign** [comment] 2017-03-02 16:02
Here is a screenshot of the problem, running `cat test.txt` on VSCode terminal and cmd.exe:

![cmdterminal](https://cloud.githubusercontent.com/assets/199648/23515240/dd6ef1de-ff69-11e6-84fb-0544e782c367.png)

I confirm that depending on the VSCode window size the problem may not appear. With cmd.exe it always works as expected, no matter the size of the window.

**Comment by warpdesign** [comment] 2017-03-02 16:11
More information: looking at the test.txt file, it seems the ellipsis utf8 charcater is encoded using 3 bytes (0xE280A6), see [http://www.fileformat.info/info/unicode/char/2026/index.htm](url)

And this may be the problem: pasting this character several times directly in the VSCode terminal is enough to trigger the problem.

Simply try to copy/paste this `………………………………` and you'll see the cursor gets shifted to the right.

**Comment by bitcrazed** [comment] 2017-03-03 01:58
This definitely looks like something for @Tyriar & the VSCode team to take a look at.

**Comment by Tyriar** [comment] 2017-03-03 17:00
Thanks for looking into it @bitcrazed :smiley:

**Comment by Tyriar** [comment] 2017-03-12 20:20
I can repro, I found this only happens when the terminal really wide.

**Comment by Tyriar** [comment] 2017-03-12 20:28
Here's a snapshot of what's send to xterm.js (looks like the problem is in node-pty):

Narrow:

![image](https://cloud.githubusercontent.com/assets/2193314/23835619/ce17f242-0727-11e7-85fe-12741422b2a6.png)

Wide: 

![image](https://cloud.githubusercontent.com/assets/2193314/23835622/d22f1162-0727-11e7-952c-eb256ed8bcba.png)

**Comment by Tyriar** [comment] 2017-03-12 20:36
This was introduced in v1.9 where the big Windows improvements came in https://code.visualstudio.com/updates/v1_9#_integrated-terminal-improvements, this is probably an upstream issue.

**Comment by Tyriar** [comment] 2017-03-12 20:46
It appears to happen when the terminal is sized to **160 characters wide or more**. @rprichard I'm guessing this is related to winpty, does this number have any significance in winpty? I could restrict the size of the terminal to <= 159 characters but would prefer to fix the root cause if possible.

**Comment by Tyriar** [comment] 2017-03-12 20:51
Search of '160' in winpty: https://github.com/rprichard/winpty/search?utf8=%E2%9C%93&q=160

**Comment by Tyriar** [comment] 2017-03-12 20:56
I capped terminal cols at 159 characters on Windows for the time being, you should get this workaround in the next Insiders build.

**Comment by rprichard** [comment] 2017-03-12 21:52
@Tyriar winpty has to change the console font's size to allow for terminals that are especially narrow or wide, because Windows doesn't allow windows narrower than about 140px (assuming ordinary DPI), and it also doesn't allow console windows wider than the display the (hidden) window is on.

Resizing from 159 columns to 160, with a non-CJK code page, I think winpty switches from a size 3x5 Lucida Console font to a size 2x4 font.

I suppose I'll have to reproduce this issue to see what's happening.

**Comment by rprichard** [comment] 2017-03-12 23:16
I tried to reproduce the issue by running `npm start` (after `npm install`) in the bug repository above, and it worked fine.  I also tried catting the `test.txt` file with WSL bash and Cygwin, and that worked too.  I used a VSCode terminal of varying widths above 160 columns.

Maybe the DPI of the monitor is relevant?  I only have ordinary DPI displays available, but maybe I can configure a VM somehow.

The `winpty-debugserver.exe` output might be helpful.  (See the https://www.github.com/rprichard/winpty repo for details.)

**Comment by Tyriar** [comment] 2017-03-13 05:12
Hmm, I only have a standard dpi monitor too, were you using the default powershell?

**Comment by Tyriar** [comment] 2017-03-13 15:23
@rprichard I was testing on the creator's update too (Windows Insiders).

@bitcrazed I notice the issue you called out above actually says it was tested on 15019 *not* 14393. So it may be related to Windows Insiders. I did discover that it only happens when the terminal is 160 or more characters in width.

**Comment by bitcrazed** [comment] 2017-03-13 16:22
@Tyriar - Apologies, you're right - I mis-read the report.

**Comment by Tyriar** [comment] 2017-03-13 16:44
No worries :smiley:

**Comment by CaselIT** [comment] 2017-03-13 18:16
@rprichard Yes, it appears to only be broken on windows 10 insiders. I also do not have any problem with the normal version of win10.

**Comment by Tyriar** [comment] 2017-03-14 21:15
Sometimes the width may not matter though? https://github.com/Microsoft/vscode/issues/22572

**Comment by Tyriar** [comment] 2017-03-15 18:41
Can anyone verify that the workaround that caps the terminal width fixes the issue?

**Comment by sgtoj** [comment] 2017-03-15 19:14
@Tyriar I cannot confirm if it did fix it, yet. I will confirm that I have this issue on Windows Insider builds. Currently, using 15048 at home and 15055 at work.

**Comment by rprichard** [comment] 2017-03-16 22:20
I wasn't able to reproduce the issue with 15014, but I *can* reproduce it with 15048.  The underlying winpty console looks fine (e.g. after setting `WINPTY_SHOW_CONSOLE=1`), which is interesting.  I'll keep looking into it.

**Comment by rprichard** [comment] 2017-03-17 02:19
This issue appears to be a regression in the Windows console having something to do with its support for single-vs-double-column characters.  It doesn't involve colors at all.

It's easy to break ConEmu as well as winpty.  Just place this text into a file (and save it UTF-16 LE with BOM):
```
-２-
-２-
-２-
```

Then use the `type` command in PowerShell/CMD, and you'll see the same issue as with winpty/VSCode.  Yet, the console buffer looks fine if you press Ctrl-Win-Alt-Space:

![winbug-conemu](https://cloud.githubusercontent.com/assets/1572855/24026137/1b97322c-0a8d-11e7-957e-5ec6f7b9924e.png)

The special character here is [U+FF12 (FULLWIDTH DIGIT TWO)](https://codepoints.net/U+FF12), which is unambiguously a double-column character.

In previous versions of Windows, the `ReadConsoleOutput` API would return two `CHAR_INFO` records, both of them with `CHAR_INFO.Char.UnicodeChar` equal to 0xFF12.  The first would have attribute `COMMON_LVB_LEADING_BYTE` and the second would have `COMMON_LVB_TRAILING_BYTE`, which allows winpty (and probably ConEmu as well) to recognize that there's only a single U+FF12 character in two cells.  Now Windows only returns a single `CHAR_INFO` record, the the LVB attributes are unset.

I wrote a larger test case here: https://github.com/rprichard/winpty/blob/6360ec6a5bcdc2c16eba7acc3c2d8e72af605407/misc/winbug-15048.cc

I'm not sure I'm going to do anything more on this.  I *think* Microsoft needs to restore the original behavior.

**Comment by Tyriar** [comment] 2017-03-17 02:55
@rprichard thanks heaps for looking into this!

@bitcrazed could your team check this out? I've seen this reported quite a bit recently so it's a pretty big impact bug.

**Comment by miniksa** [comment] 2017-03-17 15:59
I'm trying to look at this issue this morning.

**Comment by miniksa** [comment] 2017-03-17 18:08
@rprichard, I'm looking at your test case there with the 3 examples you gave at the top in https://github.com/rprichard/winpty/blob/6360ec6a5bcdc2c16eba7acc3c2d8e72af605407/misc/winbug-15048.cc

I have commentary for Case 2 & Case 3, but still looking into Case 1.

### Case 2: 0x221A takes 1 column usually in Lucida Console unless font is small.
0x221A is an ambiguous width character according to http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt so we base the number of columns on how many pixels wide GDI says that the character is going to render versus the number of pixels wide that a '0' character is. If it starts failing when you use too small of a font, the only solution we have is to use a larger size font or a different font that works for you.

### Case 3: 0xFF12 in 'Lucida Console'.
0xFF12 isn't in Lucida Console and the console code hasn't supported font fallback ever, so it displays incorrectly on our window, but shouldn't impact you (I don't think). If you are scraping the contents of our buffer and can do font fallback, you should be able to substitute an appropriate two column character into that space. We want to support font fallback eventually, but it'll just take time.

### Case 1: 0x3044 Hiragana I in MS Gothic
I think this is the one that is causing everyone trouble and I'm still looking. Will report back when I figure out what's up. I can reproduce the issue, but now I have to dig in.

**Comment by miniksa** [comment] 2017-03-17 20:40
OK, I have Case 1 logged in MSFT:10187355 which is a work item we have been using to greatly expand the test coverage and compatibility with the legacy console for single-byte vs double-byte, single-width vs double-width, Western vs. CJK, Raster font vs TrueType font coverage across ReadConsoleA/W ReadFileA/W ReadConsoleOutputA/W WriteConsoleA/W WriteFileA/W WriteConsoleOutputA/W WriteConsoleOutputCharacterA/W WriteConsoleOutputAttributeA/W and the CRT projections of those (printf, putc, putchar, etc.).

It should be solved when we get that one finished up and out the door.

**Comment by rprichard** [comment] 2017-03-17 21:35
@miniksa Thanks for looking at this!  Yeah, I may have to stop using such tiny fonts in winpty (e.g. for case 2).

Aside: For determining a character's width in columns, I noticed that [the PSReadLine library uses `TEXTMETRIC.tmMaxCharWidth`](https://github.com/lzybkr/PSReadLine/blob/7a35e212257712302573fc71af6fa07f09dc3694/PSReadLine/ConsoleLib.cs#L779) rather than the width of the '0' character.  My impression was that PSReadLine was replicating the console's internal behavior.  Intuitively, comparing against '0' makes more sense.

Aside 2: Out of curiosity, is there a goal of handling code points outside the BMP?  The API doesn't seem to allow for it -- a program could write a UTF-16 surrogate pair with `WriteConsoleW`, but the region I/O functions `{Read,Write}ConsoleOutputW` expect a single 16-bit value for each buffer cell.

**Comment by miniksa** [comment] 2017-03-17 22:00
@rprichard 

re: Aside 1:
Well... we were using `TEXTMETRIC.tmMaxCharWidth` for a while, but it turned out to be unreliable for some fonts. It turns out that text metrics are a mixed bag and sometimes either GDI or the font metadata itself fumbles hard and gives us something really unreasonable when we use that. So I think we're rallying around the size of a '0' until something/someone gives us a better metric. I'm hoping that when we eventually get the time to do DirectWrite that things are sunnier in terms of column measurement in that world than they are in the GDI world, but I don't think I'll know until we try.

re: Aside 2:
There is a goal to handle UTF-16 surrogate pairs. We're working on breaking bad assumptions internal to the console to try to enable full UTF-8 support and full UTF-16 support with surrogate pairs at some point in the future. This issue is a symptom of this work happening internally to prepare for one day having this sort of support.

**Comment by Tyriar** [comment] 2017-04-03 14:36
> It should be solved when we get that one finished up and out the door.

@miniksa when do you expect the issue to be fixed?

**Comment by be5invis** [comment] 2017-04-07 20:49
@rprichard 
I've observed that they supported IMEs under no-DBCS codepages, they maybe also changed the layout algorithm that no longer simulates 1980s Hanka (汉卡) behavior that uses two cells to store one character.

ps. I've heard that they are going to make a new CJK typeface and replace the current terminal font (which is in BITMAP!) with it's monospaced version...

**Comment by the1900** [comment] 2017-04-17 15:00
yeah same as me. what are these `&nbsp`? where are they from?
![001](https://cloud.githubusercontent.com/assets/10105141/25092702/d68bc7c8-23c9-11e7-851c-081fa2d22d12.png)

- VScode ver: 1.11.2
- OS ver: Windows 10 x64

**Comment by miniksa** [comment] 2017-04-17 15:38
There's a known issue. We're trying to figure out what we can do about it. Please be patient. I don't have anything else to share at this time.

**Comment by the1900** [comment] 2017-04-17 15:52
I hope to fix this problem. I'll use external terminal until handle this situation without it VScode is great insofar as I moved from sublime text 3.

**Comment by be5invis** [comment] 2017-04-17 17:28
@miniksa Is it because the `ReadConsoleOutput` no longer duplicate FW characters?
cc. @maximus5

**Comment by Tyriar** [comment] 2017-04-17 17:34
This may work as a workaround for PowerShell? From @Roscoe93 in https://github.com/Microsoft/vscode/issues/24737#issuecomment-294126600

> temporarily solved by adding this config(when using powershell or cmd as integrated terminal):
> 
> ```javascript
> "terminal.integrated.shellArgs.windows": [
>   "-NoExit",
>   "/c",
>   "chcp.com 65001"
> ]
> ```

**Comment by be5invis** [comment] 2017-04-17 17:40
@Tyriar I think the problem is that...

- In earlier Windows, Console **duplicates** FW characters under, and only under DBCS CPs and put the duplicated in the `ReadConsoleOutput`.
- In RS2 they removed duplication but WINPTY is still expecting that...
- In CP65001 there is no duplication (causing FW characters being incorrectly layouted), so changing CP “fixes” this bug.

**Comment by rprichard** [comment] 2017-04-17 23:31
I suspect that enabling the legacy console would also work around this issue: https://www.isunshare.com/windows-10/enable-use-legacy-console-for-command-prompt-in-windows-10.html.

**Comment by zphhhhh** [comment] 2017-04-18 09:10
I'm using windows 10 Creator version and meet the same problem, is Any way there to solve it ? 
VScode version: 1.11.2

**Comment by t7yang** [comment] 2017-04-18 09:17
@zphhhhh 
as @rprichard  reply, enable the legacy console can solve this problem. Confirm here in Windows 10 creator update and VS code 1.11.2.

**Comment by eos3tion** [comment] 2017-04-23 13:31
The terminal will be correct when I change my system locale to English(us).
But when I set locale to Chinese(cn),the terminal will broken.

I change "terminal.integrated.shell.windows" to "cmd.exe" "powershell.exe"
the terminal broken.
but "bash.exe" is ok.

**Comment by rprichard** [comment] 2017-04-24 06:32
There are two separate issues here w/ winpty:
1. `ReadConsoleOutput` previously represented a double-width character as two `CHAR_INFO` records using the LVB attributes, and now it only fills one `CHAR_INFO` record, which breaks the documented 2D-array property of the API's output buffer.
2. Perhaps winpty shouldn't use fonts smaller than some threshold, because they encourage the console to make unreasonable half-vs-full-width decisions.

I'm waiting to hear whether Microsoft can do something about issue 1.

I looked into issue 2 a bit today on Windows v15063.  I noticed that WSL Midnight Commander (`mc`) wasn't laying its text out correctly once mintty->winpty expanded beyond 160 columns, which reduced the font size to 4.  The issue was that [U+2500 BOX DRAWINGS LIGHT HORIZONTAL](https://codepoints.net/U+2500) was treated as full-width.  With a Lucida Console font, it seems to be treated that way at least with sizes 2, 4, 7, and 39.  It's also full-width with Consolas at sizes 2, 3, 5, 7, 9, and 24.  (I stopped testing after 24.)  If the user uses a console with any of those font-size combos, then `mc` will be broken.

It seems that the console is trying to use the "unpadded" width of a character, so even for characters that are unambiguously half-or-full-width in a particular font, the console sometimes makes the opposite determination.  e.g. The "Western" fonts (Lucida Console, Consolas) all think that U+2500 should be half-width--the glyph is half-width, and `GetCharWidth32` for U+0030 and U+2500 are equal.  Somehow the console decides that it's full-width instead.  My current guess is that it's using `GetCharABCWidths` and noticing that the "B" width is larger than some metric (`GetCharWidth32` of "0"?).  When U+2500 is full-width, I see that the "C" padding width is -1.  Otherwise, U+2500's "A" and "C" paddings are 0.

Some of the CJK fonts treat some of the line-art characters as full-width.  (How is a program like `mc` ever supposed to work portably?  Is the Unix situation any better?)  When U+2500 is full-width in a font, I think the console always decides, "full width".  OTOH, the console will always(?) think [U+2502 BOX DRAWINGS LIGHT VERTICAL](https://codepoints.net/U+2502) is half-width, because it's all padding.

It's 10 years old, but this commentary on `wcwidth` is interesting: http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c.  It *seems* like the character widths should be more standardized, but I'm guessing that hasn't happened.

Maybe the console could at least make its character width decision independently of the font size?

**Comment by be5invis** [comment] 2017-04-24 06:47
@rprichard Is it related to hinting?
U+2500, GID574, lucon.ttf @ 4ppem

![image](https://cloud.githubusercontent.com/assets/240091/25325193/d98a3076-28fc-11e7-80b3-4041ba1854b8.png)

**Comment by be5invis** [comment] 2017-04-24 06:57
@rprichard Perhaps you are right. Maybe they are comparing against `OS/2.xAvgCharWidth`.

**Comment by rprichard** [comment] 2017-04-24 07:52
@Tyriar I think you disabled the temporary 160 column limit, but in any case, I committed a fix to winpty master tonight ("Stop using fonts smaller than 5px in height") that obsoletes the 160 column workaround.  The workaround prevented winpty from reducing the height to 4px, but that won't ever happen with my recent change.

**Comment by Tyriar** [comment] 2017-04-24 17:59
@rprichard thanks for letting me know, yes I removed the 160 column workaround as people were still seeing the issue and it impacted other users, particularly those using tmux on Windows.

**Comment by Hypnoes** [comment] 2017-05-05 02:57
@eos3tion Because the default encoding of bash is utf-8 and others are not. As someone above have said, while you change the powershell to utf-8 using `chcp 65001`  , this bug can be fixed manually.

**Comment by eos3tion** [comment] 2017-05-05 03:06
@Hypnoes thx,I will try.

**Comment by eos3tion** [comment] 2017-05-05 03:15
@Hypnoes 
After I typed `chcp 65001`,  the first line is ok,but when i execute cmd,it will broken again like this ↓
![20170505111420](https://cloud.githubusercontent.com/assets/8804051/25732610/1f2215ec-3184-11e7-9421-9b72b8d866df.jpg)

**Comment by pboymt** [comment] 2017-05-06 08:25
I think it's a bug of Windows Creator Update, not VSCode. All of Terminal software in Windows Creator Update have this problem.

**Comment by mysticatea** [comment] 2017-05-06 11:37
- version 1.12.1
- commit f6868fce3eeb16663840eb82123369dec6077a9b
- date 2017-05-04T21:26:50.689Z
- shell 1.6.6
- renderer 56.0.2924.87
- node 7.4.0
- Windows 10 Pro

Full-width characters seem to mess text layout of the integrated terminal. `chcp 65001` does not resolve this problem.

![image](https://cloud.githubusercontent.com/assets/1937871/25772013/88c276f0-329b-11e7-8aed-07aab03082ff.png)

**Comment by whitecolor** [comment] 2017-05-08 07:58
@Tyriar 
Enabling `legacy` brings other problems. So I still wonder what makes so difficult this bug to be fixed?

**Comment by loganmzz** [comment] 2017-05-08 15:26
@pboymt I have the problem only on insider version. See #25126

**Comment by Tyriar** [comment] 2017-05-08 19:00
@whitecolor it's an issue in Windows not VS Code, so the difficult part is deploying the fix. I believe it's coming in the next Windows patch.

**Comment by StarpTech** [comment] 2017-05-08 19:38
I also run into this issue windows 10 and Vscode 1.12.1

**Comment by StarpTech** [comment] 2017-05-08 19:39
@pboymt thx good to know.

**Comment by whitecolor** [comment] 2017-05-08 20:13
@Tyriar Well I'm on windows insiders preview, don't see this comming yet.

**Comment by Tyriar** [comment] 2017-05-08 20:17
@whitecolor I'm not super clear on the details but it may hit Insiders after or around the same time as Stable.

**Comment by louisun** [comment] 2017-05-09 15:25
I find the problem is fixed in Windows 10 Insider Preview 16188.1000.

**Comment by whitecolor** [comment] 2017-05-09 15:39
BTW I installed today some updates on windows insiders and it seem that console in VSCode works fine now.

**Comment by Tyriar** [comment] 2017-05-09 17:41
Woo! 🎉

**Comment by fillippeyton** [comment] 2017-05-10 23:17
I'm having the same issue. This is happening to me with WSL + Webpack watch. Here's my info:

VSCode Version:  1.12.1 (f6868fc)
Node: 7.4.0
OS Version: Windows 10 Enterprise 64-bit (Version: 1607; OS Build: 14393.1066) (Using WSL for Bash)
Extensions: 

Ext | Author | Version |
---------|-----------|------------------
Auto Close Tag | Jun Han |  0.3.12
C# | Microsoft | 1.9.0
Docker | Microsoft | 0.0.13
ESLint | Dirk Baeumer | 1.2.8
npm Intellisense | Christian Kohler | 1.3.0
One Dark Pro | zhuangtongfa | 2.7.0
VSCode Great Icons | Emmanuel Beziat | 2.0.3

![image](https://cloud.githubusercontent.com/assets/4128489/25909368/d3eb3db0-3561-11e7-8dc1-0af229012301.png)

**Comment by King66** [comment] 2017-05-12 21:16
meet this issue after Windows 10 1703 creators update yesterday..
looks like it will fix in future stable Windows, looking forward to it..
![1](https://cloud.githubusercontent.com/assets/11925432/26017143/bbf2cd46-379a-11e7-8843-5ffe71248a9f.gif)

**Comment by Kenya-West** [comment] 2017-05-16 03:05
Same here, man. It happens on different sizes of window.

Specs:
Windows 10 Creators Update x64
VS Code up-to-date
bash (Ubuntu on Windows)/Powershell/Whatever
![e47f0b7a-39c6-11e7-99f5-ad3fbef6a6eb 1](https://cloud.githubusercontent.com/assets/12271104/26088086/f3664798-3a2f-11e7-9dc3-b8a0cceeed4e.gif)

**Comment by KostiaChorny** [comment] 2017-05-16 08:17
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.1.4|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.9.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

There is the same issue with cmd and PowerShell
![default](https://cloud.githubusercontent.com/assets/10374335/26096246/29711cf2-3a29-11e7-8690-f0ecfac34561.png)

**Comment by Guema** [comment] 2017-05-17 11:48
i have bug with terminal too. It is unusable at the moment.

**Comment by guimou** [comment] 2017-05-19 14:16
Easy to trigger here: one or more backspaces when typing, then return, and you get a "one space" offset. Repeat to add more...
Workaround: cls command resets everything.

**Comment by jose-villegas** [comment] 2017-05-21 22:28
I just added a unicode symbol to my PS1 in Bash For Windows (it's the terminal I call from VS), and yeah it's related to that, it seems to add spaces somewhere depending on the number of special characters.

**Comment by Emeryao** [comment] 2017-05-26 06:24
Hi all
I think this issue is gone since [KB4020102](https://support.microsoft.com/en-us/help/4020102/windows-10-update-kb4020102) has been released which fixes the non-unicode issue for windows10

VS Code terminal now works well on my machine with Windows10 ‪15063.332‬

VS Code Version 1.13.0-insider
Commit 770206ab9c6357943a2145bd3ea49b667f3ff539
Date 2017-05-26T05:14:23.944Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by AndreiGorlov** [comment] 2017-05-26 08:40
KB4020102 partially fixed issue for me.

Windows 10 RUS:
![1](https://cloud.githubusercontent.com/assets/13963009/26486897/bc56c948-4205-11e7-9c90-ab0d6ccf21ba.PNG)
Windows 10 RUS + ENG lang pack:
![2](https://cloud.githubusercontent.com/assets/13963009/26486896/bc543782-4205-11e7-8813-645a1906f2ce.PNG)
Windows 10 RUS + ENG lang pack with cyrillic characters in terminal:
![3](https://cloud.githubusercontent.com/assets/13963009/26486895/bc53d512-4205-11e7-9a92-d1fc28548c37.PNG)

Locale in all cases is ru-RU, only windows gui language is different.

**Comment by Kenya-West** [comment] 2017-05-26 09:55
@Emeryao @AndreiGorlov when will this update be shipped on Windows 10? I'm afraid to install it manually.
And I check and Settigs app - there's no such update.

**Comment by StarpTech** [comment] 2017-05-26 10:09
yes update KB4020102 also fixed it for me but I couldn't install it at the first time. You have to do drive through a real microsoft experience 💃 https://www.drivereasy.com/knowledge/windows-update-error-0x80248007-in-windows-10/

**Comment by miniksa** [comment] 2017-05-26 15:10
OK, MSFT:10187355 like I mentioned way up above in this thread transformed into MSFT:11721571 and was packaged as a part of the KB4020102 update yesterday as some of you have already discovered. The fix included in the KB repaired some of the API calls to retrieve console buffer output to match their "Legacy console" or v1 behaviors. Hopefully this resolves some of the issues you all are experiencing.

For a bit of insight as to why this is such an enormously complicated problem and why it took a while to fix, you can check out https://github.com/rprichard/winpty/issues/105#issuecomment-303516064.

**Comment by xakep139** [comment] 2017-06-07 10:50
Similar issue that was fixed in Jest: https://github.com/facebook/jest/pull/3626

**Comment by leitwolf** [comment] 2017-06-09 02:19
KB4020102  fixed it for me, thanks.

**Comment by kidlj** [comment] 2017-06-09 06:15
KB4020102 fixed it for me, thanks +1

**Comment by BetaMee** [comment] 2017-06-10 06:56
I have been concerned about this issue for a  long time. This afternoon I updated new VS Code Version and I found intergrated terminal is OK . Is this issue fixed by VS Code team or OS update (KB4020102 )  ? 
@Tyriar

**Comment by Tyriar** [comment] 2017-06-12 19:57
@BetaMee the issue was caused by the Windows Creators Update and fixed in KB4020102 (see https://github.com/Microsoft/vscode/issues/19665#issuecomment-304308207)

**Comment by Tyriar** [comment] 2017-06-26 22:10
Reports of this issue have slowed down significantly so I'm assuming that means most people have received the Windows patch and all is well. Thanks @miniksa for handling this :smiley: 

If you are still experiencing this issue, please make sure you fully update Windows 10 before reaching out to us.

**Closed by Tyriar** 2017-06-26 22:10 UTC
Labels: bug, integrated-terminal, windows
