### ISSUE TITLE
Javascript intellisense and ctrl + click navigation is not working for JavaScript Object annotation with module.exports

### ISSUE THREAD

**Issue by viveking** [Microsoft/vscode#31706] opened 2017-07-29 10:43 UTC
- VSCode Version: 1.12
- OS Version: MacOS sierra 10.12.5

Steps to Reproduce:

1. Create a first.js Javascript file with following code:

// In this file create an object p with two properties "hello" and "world". and export the object using module.exports like following code.i.e. one property with direct assignment and another is added after main object is created.

```
let p = {
    "world":"world"
};
p.hello = "hello";
module.exports = p;

```
2. In the second file, import the first.js file.

but intellisense is not showing "hello" property. I am able to see the "world" property in intellisense menu. Following code is attached.

```
const first = require("./first");

//Able to see world property in intellisense menu.
console.log(first.world);

//Not able to see hello property in intellisense menu.
console.log(first.hello);

```
3. Same issue is with Javascript functions as well.

4. Also while clicking on the "world" property in the second file, it can navigate to first file. But it is not working with "hello" property.

Reproduces without extensions: Yes

**Comment by vkyadav998** [comment] 2017-07-29 10:49
yes i m also facing the same issue while navigating.

Kindly fix this issue.

**Comment by ganesh1993** [comment] 2017-07-29 11:01
hi
i am using windows 7 OS and facing the same issue

**Comment by mjbvz** [comment] 2017-07-31 16:18
Duplicate of https://github.com/Microsoft/TypeScript/issues/10868

**Closed by mjbvz** 2017-07-31 16:18 UTC
Labels: duplicate, javascript, upstream
