### ISSUE TITLE
Can no longer sync extensions by copying extensions folder because of new extensions.json file

### ISSUE THREAD

**Issue by UttermostUsername** [microsoft/vscode#168827] opened 2022-12-12 07:10 UTC
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.74.0
- OS Version: 2 Windows machines with different extension paths and/or usernames.
- This more than likely replicates as an issue on non-windows machines but I haven't tested it.

Steps to Reproduce:

1. Copy `%userprofile%\.vscode\extensions` from one machine to another. Both with active vscode installations.
2. Launch vscode on secondary machine.
3. The machine with the copy of the extensions folder doesn't load any extensions.
4. Close vscode on secondary machine.
5. Change all instances of the `fsPath` property in `%userprofile%\.vscode\extensions\extensions.json` to match the new machine's username ex `"fsPath":"c:\\Users\\USER1\\.vscode\\extensions\\author.extensionID"` into `"fsPath":"c:\\Users\\USER2\\.vscode\\extensions\\author.extensionID"`
6. Re-launch vscode on second machine.
7. Note that extensions now load correctly.

I don't know when this `extensions.json` file was added but previously doing this copy paste procedure of the extensions folder simply copied all installed extensions without issue. Now the newly added `extensions.json` file must be altered for it to work. This makes syncing extensions to a machine by USB or file-sync significantly more annoying.

**Comment by ctf0** [comment] 2022-12-12 07:22
actually this is the case for the past 4~5 versions on insiders as well.

**Comment by sandy081** [comment] 2022-12-12 08:38
`extensions.json` was introduced to support our upcoming profiles feature and we made sure to support all existing scenarios like picking up the extension when copy/pasted manually. Did you try copying the extensions in the destination folder while VS Code is up and running on the second machine?

**Comment by UttermostUsername** [comment] 2022-12-12 20:15
Based on your comment I tried the following:
1. Delete extensions folder on machine 2.
2. Open vscode on machine 2.
3. Wait for extensions folder to be re-created with empty `extensions.json`.
4. Paste all extensions into extensions folder but don't copy `extensions.json` file from machine 1.
5. The same 2 extensions are consistently added to the `extensions.json` while the rest (~21 others) are not. These two are always `azemoh.theme-onedark` and `valentjn.vscode-ltex`.
6. Leaving vscode off when doing the copy results in no extensions being added to `extensions.json`

- There are many extensions that are not detected and added to the `extensions.json`.
- Vscode should not have to remain open when copying extensions files.
- I don't know how this profiles system is supposed to work, but vscode should be smart enough to realize that there are extensions in the extension folder that are not detected as installed and should add them to this new `extensions.json` so that they may work correctly.
- Is the proper procedure not to copy this new `extensions.json` file?

**Comment by keck9939** [comment] 2022-12-13 00:43
You don't even need to change machines. Just move the vscode folder to another location on the same machine and you loose the extensions. This is at odds with the current documentation for a portable install and is exceedingly annoying.

**Comment by sandy081** [comment] 2022-12-13 08:19
@UttermostUsername Just to confirm, when you copied 21 extensions, only 2 of them are added ? Does VS Code is open all the time during that?

> Vscode should not have to remain open when copying extensions files.

Agreed. I will look into fixing this.

**Comment by sandy081** [comment] 2022-12-13 08:20
> You don't even need to change machines. Just move the vscode folder to another location on the same machine and you loose the extensions. This is at odds with the current documentation for a portable install and is exceedingly annoying.

Can you please elaborate your scenario? Are you using portable VS Code? Can you please provide steps to reproduce?

**Comment by antounas** [comment] 2022-12-13 11:08
I am using VS Code portable and came across this problem. I used to install the extensions in VSCode portable in data/extensions directory and afterwards pack and transfer VSCode portable to another path or computer. Now, the extensions list is empty probably because the original paths are hardcoded in extensions.json.

**Comment by sandy081** [comment] 2022-12-13 13:13
I think you are hitting this - https://github.com/microsoft/vscode/issues/165447

**Comment by keck9939** [comment] 2022-12-13 13:14
@sandy081 If you follow exactly the instructions at https://code.visualstudio.com/docs/editor/portable#_migrate-to-portable-mode to migrate to portable mode, the extensions vanish. (I'm using Windows 10, VSCode 1.74.0). I did _move_ rather than _copy_ the **data** and **code** directories. This may be important, otherwise it might find things in the original location.
In addition, if you re-install the extensions in the portable installation after following the referenced instructions, and then move the whole portable directory from say d:\vscode to e:\vscode, the extensions will vanish again.

**Comment by sandy081** [comment] 2022-12-13 14:51
@keck9939 Agreed. Filed a separate bug https://github.com/microsoft/vscode/issues/169006 for this.

**Comment by UttermostUsername** [comment] 2022-12-13 22:23
@sandy081
> @UttermostUsername Just to confirm, when you copied 21 extensions, only 2 of them are added ? Does VS Code is open all the time during that?

- I copied 22 (previous number was a guess now I have counted) extensions from machine 1's extension folder into machine 2's extension folder and only 2 of them were added to the `extensions.json` (which as a consequence meant only those 2 worked in the vscode on machine 2).
- Vscode was open the entire time the copying happened and I selected the "reload window" option when it indicated that it detected extensions changed on disk (the copying was finished when this popup appears). When vscode is not open 0 extensions are detected so clearly it is doing something different when active.
- I retried this procedure multiple times and, as indicated prior, the same 2 extensions were the only ones detected. I know the other extensions aren't broken because copying the `extensions.json` from machine 1 into machine 2 and then using find-and-replace to fix all the paths in `extensions.json` on machine 2, results in all the extensions (that were copied over and not detected) being detected correctly.

**Comment by sandy081** [comment] 2022-12-26 12:51
Fix for https://github.com/microsoft/vscode/issues/169006 also fixes this issue. `extensions.json` file now stores the relative path of the extension in the extensions folder. So when you copy the extensions folder across machines, this will work. Hence closing this as fixed.

**Closed** 2022-12-26 12:51 UTC
Labels: bug, extensions, author-verification-requested

**Comment by UttermostUsername** [comment] 2022-12-28 22:45
I tested the Visual Studio Code Insiders version [1.75.0-insider](https://code.visualstudio.com/insiders/).

It appears to correctly migrate extensions between different machines with different paths even when vscode is not on during the copy. The copy includes all extension files including the `extensions.json` file. It also appears that the `fspath` property is now `location` and the value is relative as you indicated.

I can confirm the issue appears fixed on the insiders version indicated. I look forward to the new version release. Thank you.

**Comment by epernia** [comment] 2023-01-02 20:21
I also tested the Visual Studio Code Insiders version [1.75.0-insider](https://code.visualstudio.com/insiders/). And works by move vscode folder to another location.

**Comment by sandy081** [comment] 2023-01-03 12:21
Adding verified tag as the fix is confirmed by the users
