### ISSUE TITLE
Expand select does not work with multiple cursors

### ISSUE THREAD

**Issue by ZNackasha-intrepid** [Microsoft/vscode#54762] opened 2018-07-20 17:46 UTC
- VSCode Version: 1.25.1
- OS Version: windows 7

Steps to Reproduce:
1. add multiple cursors 
2. then try to "expand select" action(default alt+shift+rightarrow)

Issue  only the first cursors applies the selection and the others are simply removed.

**Comment by alan-cole** [comment] 2018-08-06 00:11
Duplicate of #41838

**Closed** 2018-08-06 07:57 UTC
Labels: *duplicate, editor-multicursor, feature-request, smart-select
