### ISSUE TITLE
Markdown cell height calculation is wrong after pressing escape

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#118001] opened 2021-03-03 00:51 UTC
- VS Code Version: 1.54-Insiders
- OS Version: macOS

* Open a GitHub issue notebook
* Edit a markdown cell
* Escape

https://user-images.githubusercontent.com/876920/109735296-62921e80-7b77-11eb-9e24-75dd1a02c863.mov

Note that the init height is also wrong.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2021-03-05 21:32
I believe this is a duplicate of #117735

**Closed by mjbvz** 2021-03-05 21:32 UTC
Labels: bug, notebook-markdown
