### ISSUE TITLE
Handle case-sensitivity of file name better

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#38536] opened 2017-11-16 17:49 UTC
- VSCode Version: Code - Insiders 1.19.0-insider (3ac890f6ed9b5a7ff9bfd222fe59d1bec9d3ddf7, 2017-11-13T12:40:01.309Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Have a workspace with `test.YAML`.
2. Rename that file to `test.yaml`.

Bugs:

- Two files can be opened in tabs / Open Editors view
- Cmd + P always show both files

![f](https://user-images.githubusercontent.com/4033249/32906816-f8bda18c-cab2-11e7-9639-70a2d8d3fa96.gif)

**Comment by octref** [comment] 2017-11-16 23:07
This seems to happen because Git is insensitive to file name case changes. @joaomoreno 
For example, if you change test.YAML (commited and tracked) to test.yaml, it's still test.YAML in Git.

**Comment by joaomoreno** [comment] 2017-11-17 08:51
I don't think this specific bug is related to Git.

**Comment by bpasero** [comment] 2017-11-17 14:10
@octref you are running macOS with a case sensitive filesystem????

**Comment by octref** [comment] 2017-11-17 17:26
@bpasero Just the default macOS. Didn't do anything to change the FS. I guess it's case-insensitive. How can I check though?

I mentioned Git since it seems when I change filename from `test.txt` to `TEST.txt`, no change is registered. But through test it seems `fs.readFile` etc are also case-insensitive...

Tried Windows & Linux but does not repro. Only happens to macOS.

**Comment by octref** [comment] 2017-11-17 17:29
diskutil info
```
$ diskutil info /dev/disk1
   Device Identifier:        disk1
   Device Node:              /dev/disk1
   Whole:                    Yes
   Part of Whole:            disk1
   Device / Media Name:      APPLE SSD SM0512L

   Volume Name:              Macintosh HD
   Mounted:                  Yes
   Mount Point:              /

   Content (IOContent):      Apple_HFS
   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
   Journal:                  Journal size 40960 KB at offset 0x1a388000
   Owners:                   Enabled
```

**Comment by octref** [comment] 2017-11-18 01:14
https://apple.stackexchange.com/a/22304

**Comment by bpasero** [comment] 2017-11-18 08:27
@octref oh I see, no it is the same file after all. Marking as duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2017-11-18 08:27 UTC
Labels: bug, insiders, needs more info, quick-pick
