### ISSUE TITLE
'vscode.executeHoverProvider' can return hover info from git lens

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode#107412] opened 2020-09-25 06:02 UTC
Issue Type: <b>Bug</b>

**Bug**
1. Install git lens
1. With an extension that executes `vscode.executeHoverProvider` at the current cursor position

    You can use [this extension](https://github.com/mattbierner/vscode-docs-view/blob/ac3574abc229ca48cac396bccbeb9fa9668b3876/src/docsView.ts#L225) to test this. It requests and displays hovers at the current cursor position (although it does have some caching so it will not always make new requests.

1. Open a tracked js file in a repo. Edit the file to have a line:

```js
Array.from
```

1. Place your cursor on this line so that the git lens inline decorator shows up
1. Now request the hover contents at the end of the line (this would be a position such as ` {_line: 0, _character: 10}`)

    In the linked extension, you can make this request just by moving the cursor to the end of the line (again, the cursor must already be on the line so that the git lens inline decorater is showing)

**Expected**
Only hover contents from the code itself are returned

**Actual**
The contents from gitlens are also included (see the gravatar link):

<img width="833" alt="Screen Shot 2020-09-24 at 11 00 43 PM" src="https://user-images.githubusercontent.com/212305/94231930-d427bb80-feb9-11ea-9f0c-44ab2785a111.png">

VS Code version: Code - Insiders 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210, 2020-09-23T05:28:07.760Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|40.00GB (0.77GB free)|
|Process Argv|-psn_0_5326100 --crash-reporter-id cefe23df-690f-4b1b-9ce9-e004d3be2745|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment] 2020-09-25 10:52
This is somewhat expected. We query all hover providers and return a joined result, there is no validation of the results. What we could add is a check that the hover range actually includes the given position - but for end of line positions that can get tricky...

@eamodio I assume that gitlens is a normal hover provider, right?

**Comment by eamodio** [comment] 2020-09-25 15:06
@jrieken  Yeah, GitLens uses HoverProviders for its hovers.

**Comment by mjbvz** [comment] 2020-09-26 00:07
@eamodio What range does it use? I know you can hover over the decoration itself to trigger the hover, which I wouldn't expect to work with a HoverProvider since the decorations are not part of the file's normal text content

**Comment by eamodio** [comment] 2020-10-07 18:01
@mjbvz it depends on your settings (and current mode). You can choose to have the hovers always show over the whole line (then the range is for the full line), see here:

![image](https://user-images.githubusercontent.com/641685/95369557-922d4b00-08a5-11eb-9d41-892f1396a8c1.png)

**Comment by jrieken** [comment] 2020-10-15 10:53
Closing as designed then

**Closed by jrieken** 2020-10-15 10:53 UTC
Labels: editor-hover, under-discussion
