### ISSUE TITLE
I cannot open an image using the link in a markdown.

### ISSUE THREAD

**Issue by PiWebswiss** [microsoft/vscode#171502] opened 2023-01-17 14:02 UTC
Type: <b>Bug/issue</b>

I cannot open an image using the link in a markdown. When I run the cell nothing just black!

I'm running the link in a ``.ipynb`` file.

Link syntax : ``![Alt text](file_name.png)``

What can I do to fix this issue (syntax problem)?

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.38GB free)|
|Process Argv|--crash-reporter-id f49ea5f8-6340-4c8a-9016-10ae6c49c204|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-eslint|dba|2.2.6
antidote|dru|1.0.19
gc-excelviewer|Gra|4.2.56
isort|ms-|2022.8.0
python|ms-|2022.20.2
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.13
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
printcode|nob|3.0.0
vscode-print|pdc|0.10.20

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by PiWebswiss** [comment] 2023-01-17 17:53
YES yesterday I had no problem and today it doesn't work. I did no update.

**Comment by mjbvz** [comment] 2023-01-17 18:35
Please share an example project that shows the problem

**Comment by PiWebswiss** [comment] 2023-01-17 19:18
Screenshots of vs code:

photo 1: I set the title page and paste the link by dragging and prodding in the cell.

photo 2: I  run the cell (all is black and no title?)

photo 3:  if I press expand black again

![photo1](https://user-images.githubusercontent.com/81098558/212991212-a233b547-5b91-4f45-bcbc-54320b1f2dc2.png)
![photo2](https://user-images.githubusercontent.com/81098558/212991217-a2f531d3-f0c6-4a28-a091-777666285c42.png)
![photo3](https://user-images.githubusercontent.com/81098558/212991220-8e4a2c2f-73c0-422b-81bd-238953562db4.png)

**Comment by mjbvz** [comment] 2023-01-17 21:15
Can you please share a small project that shows this too. This can just be a notebook file and the relevant image file

**Comment by PiWebswiss** [comment] 2023-01-18 16:11
Check first cell.
Repository:
https://github.com/PiWebswiss/Ridge-regression.git

**Comment by PiWebswiss** [comment] 2023-01-18 16:15
It's interesting GitHub can ride the image but not my computer. Why?

**Comment by mjbvz** [comment] 2023-01-19 19:06
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12568

**Closed by mjbvz** 2023-01-19 19:06 UTC
Labels: bug
