### ISSUE TITLE
Markdown Preview doesn't copy text with right-click Copy

### ISSUE THREAD

**Issue by aidanwhitehall** [microsoft/vscode#148035] opened 2022-04-25 10:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a Markdown (.md) file in Visual Studio Code.
2. Command Palette > Markdown: Open Preview
3. Select text > right-click > Copy
4. Open Notepad > Edit > Paste
5. Copied content is not correctly pasted

Workaround:

1. Return to Markdown Preview
2. Select text > Ctrl+C
3. Open Notepad > Edit > Paste
4. Copied content is correctly pasted

**Comment by mjbvz** [comment] 2022-05-10 20:25
Duplicate of #141080

**Closed by mjbvz** 2022-05-10 20:25 UTC
Labels: markdown, webview
