### ISSUE TITLE
Terminal does not support delete word to left / right

### ISSUE THREAD

**Issue by Ash258** [Microsoft/vscode#62898] opened 2018-11-10 18:44 UTC
Issue Type: <b>Bug</b>

While using terminal you should be able to use common shortcuts for manipulating with text.

Vscode:

![Integrated terminal](https://i.imgur.com/1EFYePm.gif)

Standalone powershell

![Powershell](https://i.imgur.com/AotjFlO.gif)

`CTRL + Delete` is return D instead of W

VS Code version: Code - Insiders 1.29.0-insider (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-10T00:34:03.196Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-markdownlint|Dav|0.21.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
vsc-material-theme|Equ|2.5.1
vscode-terminals|fab|1.12.4
vscode-pull-request-github|Git|0.2.3
latex-workshop|Jam|5.15.1
intellij-idea-keybindings|k--|0.2.28
PowerShell|ms-|1.9.0
project-snippets|reb|0.5.0
vscode-yaml|red|0.1.0
code-settings-sync|Sha|3.2.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by usernamehw** [comment] 2018-11-10 19:52
/duplicate of #59071 which is a duplicate of #45693

**Closed** 2018-11-10 19:52 UTC
Labels: *duplicate, insiders
