### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by shawnoster** [microsoft/vscode#125217] opened 2021-06-02 05:36 UTC
LIke [Hanselman says](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main):

> You might say, "I'm all for not using master in master-slave technical relationships, but this is clearly an instance of master-copy, not master-slave."
>
> So we see that while the word master doesn't always connote slave, for many, it's evocative via basic word-association and they just don't want to look at the word on their prompt all day. Choice is cool.

Logically understanding that the context is different is like arguing with your partner about feelings they've already experienced, unless you have a TARDIS you have to deal with the present feelings rather than spending time explaining why they shouldn't feel that way to begin with.

Unless there's a strong reason to keep the primary branch `master` I suggest renaming it to `main`. If anything to get that word off of people's powerline/oh-my-posh prompts. Happy to submit a PR but unsure of internal dependencies. 🤘

**Comment by IllusionMH** [comment] 2021-06-02 08:19
Where do you want rename branch?

This repo already has `main` as default branch https://github.com/microsoft/vscode/issues/116341

**Comment by rebornix** [comment] 2021-06-02 21:04
duplicate of https://github.com/microsoft/vscode/issues/116341

**Closed** 2021-06-02 21:04 UTC
Labels: *duplicate
