### ISSUE TITLE
Code collapse icon style error

### ISSUE THREAD

**Issue by Ice-Wang** [Microsoft/vscode#60730] opened 2018-10-12 04:50 UTC
Code collapse icon style error, larger than previous version, corresponding CSS needs to be optimized

**Comment by usernamehw** [comment] 2018-10-12 05:30
Duplicate of #59695

**Comment by egamma** [comment] 2018-10-12 06:48
@usernamehw thanks for you help. Closing as duplicate.

**Closed by egamma** 2018-10-12 06:48 UTC
