### ISSUE TITLE
Space in anonymous function when formatting JavaScript code

### ISSUE THREAD

**Issue by karaxuna** [Microsoft/vscode#3913] opened 2016-03-09 14:16 UTC
Version 0.10.10

In previous versions formatting was adding space in anonymous function like this:

    function() {}

Became:

    function () {}

Now it works vice versa. Is there any way to configure it?

**Comment by busfahren** [comment] 2016-03-09 14:24
+1

**Comment by weinand** [comment] 2016-03-09 14:37
duplicate of https://github.com/Microsoft/vscode/issues/1533

**Closed by weinand** 2016-03-09 14:37 UTC
