### ISSUE TITLE
Opens two different copy of same file

### ISSUE THREAD

**Issue by goyaltushar92** [Microsoft/vscode#40381] opened 2017-12-17 14:47 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
debugger-for-chrome|msj|4.0.0

---
I am working on Angular 4 project and while working with TS files. VS code opens 2 different copy of same file which are out of sync.
Steps to Reproduce:

1. open a file from explorer in left.
2. search for a symbol from same file using command palette. or using go to definition.
3. it will open another copy of same file. you can edit and save both files, editing one does not reflects in second, which cause conflict with disk copy.
4. similar behavior is also noted, when using light bulb to resolve references (Auto Import). new import statement is added to file opened using symbol search (not to file open using explorer). or if not already opened. opens a copy.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment] 2017-12-17 18:25
I can't seem to repro it.
Can you share your settings?

**Comment by goyaltushar92** [comment] 2017-12-19 13:23
following are my user settings:
```
{
    "files.autoSave": "off",
    "editor.minimap.enabled": false,
    "git.ignoreMissingGitWarning": true,
    "typescript.implementationsCodeLens.enabled": true,
    "typescript.referencesCodeLens.enabled": true
}
```

and following are my workspace settings:
```{
    "typescript.tsdk": "node_modules\\typescript\\lib"
}
```

also these are my project dependencies:
```
"dependencies": {
    "@angular/animations": "^4.3.5",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngx-translate/core": "^7.1.0",
    "@ngx-translate/http-loader": "^1.0.0",
    "@types/jquery": "^3.2.12",
    "angular-highcharts": "^4.0.4",
    "angular-material": "^1.1.5",
    "angular2-google-place": "^2.0.2",
    "angular2-highcharts": "^0.5.5",
    "angular2-tooltip": "^3.1.0",
    "angularic-ionicon": "^1.1.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highcharts": "^6.0.2",
    "ionic-angular": "^3.5.3",
    "ionicons": "^3.0.0",
    "mydatepicker": "^2.0.27",
    "ng-pick-datetime": "^5.0.0-beta.5",
    "ng2-auto-complete": "^0.12.0",
    "ng2-bootstrap": "^1.6.3",
    "ng2-datepicker": "^1.8.3",
    "ng2-daterangepicker": "^2.0.7",
    "ng2-datetime": "^1.4.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-location-autocomplete": "^1.0.0",
    "ng2-pagination": "^2.0.2",
    "ng2-table": "^1.3.2",
    "ng2-toasty": "^4.0.3",
    "ngx-cookie-service": "^1.0.7",
    "ngx-toastr": "^6.1.2",
    "primeng": "4.2.2",
    "rxjs": "^5.4.1",
    "xlsx": "^0.11.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/highcharts": "^5.0.8",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
```

**Comment by mjbvz** [comment] 2017-12-19 21:38
@goyaltushar92 Looks like are using an old version of TS. Does this happen if you use TS 2.6.2+ (VS Code's version) in your workspace?

**Comment by goyaltushar92** [comment] 2017-12-20 07:45
@mjbvz, I was able to reproduce same issue after switching to VS Code's version of TS.

**Comment by mjbvz** [comment] 2017-12-21 00:21
@goyaltushar92 Is this happening in any project you open or just one? Can you share the full path of the two files using `Copy Path`, or at least the diff of the two paths? I suspect the paths differ only in their cases

**Comment by goyaltushar92** [comment] 2017-12-21 06:55
yes, you are right, both files paths are different in path. 'orpak-client-app' folder is small case in our directory tree. but here file opened from symbol search, has change case of folder. while file opened with Explorer has same case as in directory tree.

> D:\OrpakIsr\Source Code\Orpak-Loyalty-Web\orpak-client-app\app\components\customers\customer-leads\customer-leads-list\customer-leads-list.component.ts

> D:\OrpakIsr\Source Code\Orpak-Loyalty-Web\Orpak-Client-App\app\components\customers\customer-leads\customer-leads-list\customer-leads-list.component.ts

**Comment by mjbvz** [comment] 2018-01-04 20:00
Root cause is #12448 Following up to see if any workaround is possible.

Closing as duplicate of #12448

**Closed by mjbvz** 2018-01-04 20:00 UTC
Labels: needs more info, typescript

**Comment by goyaltushar92** [comment] 2018-01-10 06:46
thanks @mjbvz i was able to find root cause of the problem. it was that in my tsconfig.json, and few imports in individual .ts files were using `Orpak-Client-App` instead of `orpak-client-app` so finally changing them, I was able to keep old small case name for my directory without any issue.
