### ISSUE TITLE
File will shutdown program

### ISSUE THREAD

**Issue by Matamoica** [microsoft/vscode#230873] opened 2024-10-09 07:00 UTC
Type: <b>Bug</b>

When I try open folders or just go file place program wil shutdown. So I can't use code-insiders now.

VS Code version: Code - Insiders 1.95.0-insider (a3cf6b8bcb57cf77ed546a4636be6ca068bfc0d8, 2024-10-08T08:51:16.008Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 3984)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|30.99GB (24.76GB free)|
|Process Argv|--crash-reporter-id 2bec8998-c6fb-4284-b75b-d094482a6fc7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jg8ic977:31013176
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by albertosantini** [comment] 2024-10-09 08:12
Is the pinned issue https://github.com/microsoft/vscode/issues/230454 your scenario?

**Comment by maherkhalil07** [comment] 2024-10-09 09:49
same issue here in fedora. vs code crashed if I pressed on the file menu

**Comment by albertosantini** [comment] 2024-10-09 10:32
It seems this a duplicate of the pinned issue #230454. 
Please, you have any news, comment there and close this issue.
Thanks.

**Comment by gpertea** [comment] 2024-10-09 12:11
May be related to #230604, if the crash is on attempting to access the `File` menu itself (if that's what "go to file place" meant)

**Closed** 2024-10-09 23:28 UTC
Labels: triage-needed
