### ISSUE TITLE
a bug with “Open in Integrated Terminal“

### ISSUE THREAD

**Issue by huihuilovekuikui** [microsoft/vscode#132478] opened 2021-09-06 15:03 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.0
- OS Version:Win10

Steps to Reproduce:
I have set git bash as the default terminal, but when I execute "open in integrated terminal", the open terminal is still PowerShell.
![image](https://user-images.githubusercontent.com/66559869/132235037-f5a92e41-2cff-44f9-a4c0-811421fc39c5.png)
![image](https://user-images.githubusercontent.com/66559869/132235036-d8a77d06-440e-4f76-b719-b62f3c404efa.png)
![image](https://user-images.githubusercontent.com/66559869/132235051-d6a18e1d-ccbb-4ddf-b9a6-8fcb2a44b679.png)

**Comment by gjsjohnmurray** [comment] 2021-09-06 16:40
/duplicate of #132150 and will be fixed in upcoming recovery release.

**Closed** 2021-09-06 16:41 UTC
Labels: *duplicate
