### ISSUE TITLE
Login like in Visual Studio IDE to preserve keybinding and other settings

### ISSUE THREAD

**Issue by ahmad2smile** [Microsoft/vscode#22618] opened 2017-03-14 17:23 UTC

**Comment by seanmcbreen** [comment] 2017-03-14 18:28
Hi this is a dupe of another request sloe closing this one but please up vote the other one to help us prioritize :)

#22111

**Closed by seanmcbreen** 2017-03-14 18:28 UTC
Labels: duplicate

**Comment by ahmad2smile** [comment] 2017-03-14 19:11
ohh sorry!! got it !! I actually did a quick search for "login" ty
