### ISSUE TITLE
Window edges cropped when full-screen

### ISSUE THREAD

**Issue by tim-stasse** [microsoft/vscode#85964] opened 2019-12-02 22:00 UTC
Issue Type: <b>Bug</b>

Making the window full-screen on an external monitor (it doesn't affect my laptops main display) makes the edges of the applications window become greater than the full width and height of the monitor, cutting off the edges of the applications window.

I found this issue here: https://github.com/microsoft/vscode/issues/84164 which talks about what I think is the same issue, however the last comment 10 days ago says it was fixed, and would be included in the latest release, which is when I started to notice this issue myself. I also have insiders, and hadn't updated it to the latest version in awhile, so when I first opened it, there was no issue with the insiders edition, but I immediately upgraded my insiders to find the update introduced the issue with the insiders edition as well.

I assume then that the fix mentioned in the other issue, is now causing the issue to appear for myself.

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.73GB (1.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.73GB (1.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.73GB (1.73GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|3.2.0
dotenv|mik|1.0.1
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.3
vscode-remote-extensionpack|ms-|0.17.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
gitlens|eam|10.2.0
prettier-vscode|esb|3.11.0
vscode-peacock|joh|3.2.0
vscode-styled-components|jpo|0.0.27
chat|kar|0.29.0
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.3.1
vsliveshare|ms-|1.0.1293
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4

</details>

**Comment by tim-stasse** [comment] 2019-12-02 22:01
The duplicate issue detection is normally pretty good, but that one I'm sorry is no where near 😅

**Comment by IllusionMH** [comment] 2019-12-03 11:32
Is it Full screen or maximized (when you see window controls minimize, restore, close)?

Most likely duplicate of #85595 and #85592

**Comment by sbatten** [comment] 2019-12-04 19:20
@tim-stasse can you detail your monitor setup with the number of monitors, their resolution settings, their scaling settings and which is the primary monitor?

Also, please confirm if you are referring to full screen or maximized window state.

**Comment by tim-stasse** [comment] 2019-12-04 21:36
Yes, technically it's maximised and not full screen.

It could potentially be a duplicate of #85592, I'll let you decide though 🙂

I have 2 external monitors, their resolutions are both 1920x1080 scaled at 100%. I then also have the built-in laptop screen which is my main display, and it has a resolution of 3840x2160 scaled at 225%.

**Comment by sbatten** [comment] 2019-12-04 22:15
yes i believe this is a duplicate, thanks for reporting and all the info.

**Closed by sbatten** 2019-12-04 22:15 UTC
Labels: needs more info
