### ISSUE TITLE
SimSun font's spaces are double as wide

### ISSUE THREAD

**Issue by PowerfulCat** [Microsoft/vscode#66066] opened 2019-01-05 00:18 UTC
perhaps i'm second one report this confuse.
you known. I have severe obsessive-compulsive disorder.
SimSun is my only love font. I try lot's of other bitmap fonts, but the problem still existed.
I agree with alexandrudima.
"This is something driven by the font. We respect whatever width Chromium decides to render for a space, and I believe Chromium respects whatever the font instructs. I don't believe this is a bug."
but I'm more in favor of good compatibility as an integral part of a product.
maybe that's why windows 10 hasn't replaced windows 7 and xp yet.

**Comment by egamma** [comment] 2019-01-05 09:05
I agree with @alexandrudima. This issue is a duplicate of https://github.com/Microsoft/vscode/issues/37100, nothing we can do to address this on the VS Code side.

**Closed by egamma** 2019-01-05 09:05 UTC
