### ISSUE TITLE
SCM - Shorten branch name in Source Control view to always have the changes indicator visible when using multi root workspace

### ISSUE THREAD

**Issue by benzman81** [microsoft/vscode#207551] opened 2024-03-13 08:00 UTC
Hi,  i could not find any request like this. We are using multi root workspaces and quite long branch names. The issue is, that the changes indicator next to the branch name in source control view is not visible for long branch names until you resize the source control view and make it wide enough. This is pretty enoying.
As a feature, I would like to have the branch names shortened using an ellipsis just like the projekt names. The full branch name remains visible in the tooltip. The goal is to always be able to see the changes indicator no matter how many chars the branch or project name is.

**Comment by nistre** [comment] 2024-06-12 14:48
Just a thought, would it also work to move the indicator to the left?  This is something I've thought about too with dealing with a similar scenario so thank you for suggesting the feature.

**Comment by lszomoru** [comment] 2024-12-20 16:37
Duplicate of [#207814](https://github.com/microsoft/vscode/issues/207814)

**Closed by lszomoru** 2024-12-20 16:37 UTC
Labels: bug, ux, scm
