### ISSUE TITLE
Terminal with PowerShelll never loads

### ISSUE THREAD

**Issue by Kralizek** [Microsoft/vscode#63309] opened 2018-11-16 14:39 UTC
Issue Type: <b>Bug</b>

When opening the integrated terminal, PowerShell never completes loading and gets stucked at
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
```

I tried with an empty `$PROFILE.CurrentUserAllHosts` but it didn't help!

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.73GB (5.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.15
cake-vscode|cak|0.11.4
gitlens|eam|8.5.6
dotnet-test-explorer|for|0.6.0
csharpextensions|jch|1.3.0
docomment|k--|0.1.2
vscode-github|Kni|0.30.0
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.1.0
msbuild-project-tools|tin|0.2.46

</details>

**Comment by Kralizek** [comment] 2018-11-16 14:41
Apparently the bot is right! I just noticed that I have loads of blank lines like in #59893

**Comment by alexr00** [comment] 2018-11-16 15:18
Duplicate of #59893

**Closed by alexr00** 2018-11-16 15:18 UTC
Labels: new release
