### ISSUE TITLE
Option to sort installed extensions by date of installation/update

### ISSUE THREAD

**Issue by KillyMXI** [Microsoft/vscode#40781] opened 2017-12-24 14:08 UTC
Restarting VSCode is a mandatory step between extension installation and activation. But it makes it rather difficult to find newly installed/updated extensions again when I want to configure them and check them in use.

**Comment by sandy081** [comment] 2018-09-24 09:29
Duplicate of #53405

**Closed** 2018-09-24 09:29 UTC
Labels: *duplicate, extensions, feature-request
