### ISSUE TITLE
When using the default input method to enter Chinese under windows10, if Pinyin is used, the last letter will appear in a shadow

### ISSUE THREAD

**Issue by binzaq** [microsoft/vscode#73023] opened 2019-04-29 08:27 UTC
- VSCode Version:1.33.1
- OS Version:windows 10 17134.706

Steps to Reproduce:

1.Switch input method to Microsoft Pinyin
2.Enter any Chinese

Does this issue occur when all extensions are disabled?: Yes
![56847905-974a4480-6914-11e9-8082-b4e0727fc499](https://user-images.githubusercontent.com/23167015/56884180-8ed04600-6a9b-11e9-9da3-715132342182.png)

**Comment by rebornix** [comment] 2019-04-29 16:26
I can't reproduce with the same set up, would love to see if anyone else can reproduce.

**Comment by Excited-ccccly** [comment] 2019-05-05 14:27
Can't reproduce either.

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by binzaq** [comment] 2019-05-06 08:21
![image](https://user-images.githubusercontent.com/23167015/57213742-53dd8d80-701a-11e9-8edd-b3fd03816080.png)
To reproduce this problem, just switch to the Microsoft Pinyin input method and enter three consecutive ds in the insert mode, but do not press the space bar.

**Comment by rebornix** [comment] 2019-07-29 17:23
I still fail to reproduce this issue. 

> in the insert mode

I'm wondering if you are using Vim extension as we don't have Insert mode in vanilla VS Code.

Close it for now and we can reopen once we have more info.

**Closed by rebornix** 2019-07-29 17:23 UTC
Labels: editor-ime, help wanted, needs more info
