### ISSUE TITLE
Lightbulb always brings error: "Running the contributed command:'extension.emmetMe' failed.' failed"" 

### ISSUE THREAD

**Issue by SerenoShen** [Microsoft/vscode#18642] opened 2017-01-17 09:04 UTC
- VSCode Version: 1.8.1
- OS Version: macOS

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment] 2017-01-17 09:24
@SerenoShen can you please provide steps or a screen cast demonstating the problem. In which context does this happen. Can you reproduce this with all extensions disabled?

**Comment by egamma** [comment] 2017-01-17 20:55
@SerenoShen This action is not contributed by the VS Code emmet support. It must come from an extension.

**Comment by kuncevic** [comment] 2017-01-18 02:44
This one have hapend to me and after. VS Code was shoving same warn message once I clicked tab. 
The error coming from [Angular 2 TypeScript Emmet](https://marketplace.visualstudio.com/items?itemName=jakethashi.vscode-angular2-emmet) extension. So once I disabled this one all good now.

**Comment by egamma** [comment] 2017-01-26 07:42
closing as a duplicate of https://github.com/jakethashi/vscode-angular2-emmet/issues/5

**Closed by egamma** 2017-01-26 07:42 UTC
Labels: needs more info
