### ISSUE TITLE
Opening last session with multiple windows and files

### ISSUE THREAD

**Issue by bash-j** [microsoft/vscode#161210] opened 2022-09-19 01:20 UTC
Type: <b>Performance Issue</b>

This issue occurs when opening vscode where the last session had multiple windows open and each window has multiple files open. The selected or active file on open never displays, just a blank page. I have to close the file and reopen for it to display the file correctly. These are ipynb files.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.54GB free)|
|Process Argv|--crash-reporter-id 740acbc4-af67-4dff-8571-0e5fffb36158|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot-nightly|Git|1.45.6799
vscode-pull-request-github|Git|0.50.0
vsc-python-indent|Kev|1.17.0
auto-save|mcr|1.0.3
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.20
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-data-preview|Ran|2.3.0
reorder-python-imports|the|0.2.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment] 2022-09-23 21:37
/duplicate of https://github.com/microsoft/vscode/issues/161520

**Closed by rebornix** 2022-09-23 21:37 UTC
