### ISSUE TITLE
split screen horizontally and vertically simultaneously

### ISSUE THREAD

**Issue by WLLR9505** [Microsoft/vscode#33532] opened 2017-08-30 16:17 UTC
![panes](https://user-images.githubusercontent.com/22595227/29883086-816719de-8d85-11e7-80fe-03fc70727038.png)
like atom

**Comment by robbiespeed** [comment] 2017-09-10 23:33
I believe this is a duplicate of #14909

**Comment by mjbvz** [comment] 2017-11-03 22:22
Duplicate of #14909

**Closed by mjbvz** 2017-11-03 22:22 UTC
Labels: duplicate, feature-request, workbench
