### ISSUE TITLE
when inactive vscode uses a tiny bit of CPU

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#89666] opened 2020-01-29 22:59 UTC
Version : 1.41.1
Validation : 26076a4de974ead31f97692a0d32f90d735645c0
Date : 2019-12-18T14:57:51.166Z
Électron : 6.1.5
Chrome : 76.0.3809.146
Node.js : 12.4.0
V8 : 7.6.303.31-electron.0
OS : Darwin x64 19.2.0

- OS Version: All OSes

Steps to Reproduce:

1. Open VSCode
2. use another application for a while
3. See CPU Usage of vscode is quite low. Expected 0

Does this issue occur when all extensions are disabled?: Haven't tried

Just for reference I only noticed the CPU usage on a test machine that has a very poor CPU,  VSCode was using around 30% of CPU idling. On other machines that I use actively it's nearly 0, but not exactly 0.

**Comment by robertrossmann** [comment] 2020-01-30 11:19
For reference, I have a MacBook Pro from 2017 with `2,8 GHz Quad-Core Intel Core i7` and VS Code consumes around 5% of CPU time while in the background. GPU reports 1 frame per second so it is probably not animation-related.

> PS. I have noticed this on many Electron-based apps, like Atom, Slack, VS Code etc. The worst was Trello app, which consumed 10% at idle. 🤷‍♂ It might not be VS Code-specific, but it is definitely worth looking into. Consider all the coal that we need to burn to get that amount of electricity... 😇

**Comment by bpasero** [comment] 2020-02-01 07:08
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by graph** [comment] 2020-02-08 20:59
```
[81606:0208/155055.479516:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS Version:       Linux x64 5.4.0-12-generic
CPUs:             Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (4 x 978)
Memory (System):  7.66GB (0.81GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  unavailable_off
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    55	 37324	code main
    0	     0	 37327	   zygote
    0	   102	 37365	   gpu-process
    0	    47	 37471	   shared-process
    0	     0	 81623	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 81624	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    94	 37515	   window (ideas - parser.hpp - vscode)
    0	    63	 37535	     extensionHost
    0	     0	 37581	       /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0	     0	 37626	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 37581 0
    0	     0	 37543	     /bin/bash
    0	     0	 38134	       zsh
    0	     0	 37559	     watcherService
    0	   220	 46887	   window (depender - README.md - vscode)
    0	    86	 46909	     extensionHost
    0	    47	 46956	       /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0	   337	 70584	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 46956 20
    0	   306	 70658	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 46956 22
    0	   353	 70862	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 46956 23
    0	    24	 47357	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=46909
    0	     0	 46910	     /bin/bash
    0	    16	 46934	     watcherService
    0	     0	 58715	     /bin/bash
    0	   204	 66431	   window (cpprun - builder.cpp - vscode)
    0	    86	 66452	     extensionHost
    0	   126	 66499	       /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
    0	    63	 71959	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 66499 2
    0	    31	 73520	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 66499 3
    0	     8	 69975	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=66452
    0	     0	 66453	     /bin/bash
    0	    24	 66475	     watcherService
    0	   118	 79428	   window (Welcome - vscode)
    0	    47	 79450	     extensionHost

Workspace Stats: 
|  Window (cpprun - builder.cpp - vscode)
|  Window (depender - README.md - vscode)
|  Window (ideas - parser.hpp - vscode)
|    Folder (ideas): 5 files
|      File types: md(2) gitignore(1) hpp(1)
|      Conf files:
|    Folder (cpprun): 181 files
|      File types: o(39) cpp(19) hpp(18) cmake(10) txt(6) teaspec(6) bin(5)
|                  c(4) ninja(4) out(4)
|      Conf files: cmake(10)
|    Folder (depender): 877 files
|      File types: obj(89) o(78) cpp(74) h(65) png(54) cmake(36) js(28)
|                  html(28) hpp(26) teaspec(26)
|      Conf files: cmake(36) makefile(5) launch.json(1) settings.json(1)
|                  tasks.json(1)
|      Launch Configs: cppdbg
```


I'll try to do it on a test machine where the cpu will be exagurated by how slow that machine is. Here it just shows 0% with a loadavg of 1. According to htop there are 2 processes using less than 1% of CPU but above 0%. A code process with `--inspect-port=0` and this one:


```
/proc/self/exe --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=6363126759408170600,4017249700537656166,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=fr --standard-schemes --secure-schemes=vscode-resource --bypasscsp-schemes --cors-schemes=vscode-resource --fetch-schemes=vscode-resource --service-worker-schemes --app-path=/usr/share/code/resources/app --node-integration --webview-tag --no-sandbox --no-zygote --background-color=#070303 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=3907203038638050303 --renderer-client-id=12 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

**Comment by robertrossmann** [comment] 2020-02-10 08:26
During my personal investigation, I noticed that the process using the CPU was probably the extension host but I am not certain. I have also noticed that when I disable some extensions, the CPU usage at idle drops a little with every extension I disable. I noticed that all the extensions most likely have a shared trait - they either implement the language server protocol or provide a relatively complex UI. These are the packages which contributed the most to the CPU drops I observed:

```
mads-hartmann.bash-ide-vscode
ms-azuretools.vscode-docker
ms-vscode.go
mtxr.sqltools
mauve.terraform
```

Note: starting VS Code with all extensions disabled resolves the whole issue, but then again, if the problem really is in the Extension Host process this behaviour is to be expected.

**Comment by bpasero** [comment] 2020-02-27 17:01
@graph 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by graph** [comment] 2020-02-28 19:03
I was careful not to move my mouse on the vscode window. Periodically it consumes CPU. Below is from vscode started with `code --disable-extensions`. Also "Shared process" occasionally jumps to 5. In this one it just happens to be 0. When extensions are enabled CPU is definitely more so some extensions are definitely also consuming CPU when they should be inactive.


```
C:\Users\XXXX>code --status
Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)
Memory (System):  7.47GB (3.70GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       disabled_off
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled
CPU %   Mem MB     PID  Process
    0       75   11232  code main
    0      114    9748     gpu-process
    0       14   10752     electron-crash-reporter
    0      179   10812     window (lint.cpp - XXXX - Visual Studio Code)
    0       11    4580       watcherService
    0       11    9312         console-window-host (Windows internal process)
    0       57    8848       extensionHost
    0        6    9908       winpty-process
    1       11    1844         console-window-host (Windows internal process)
    0       71   10084         "C:\Program Files\PowerShell\6\pwsh.exe"
    0       73   11076     shared-process
Workspace Stats:
|  Window (lint.cpp - XXX - Visual Studio Code)
|    Folder (XXX): 2049 files
|      File types: h(368) cpp(276) xml(150) py(86) obj(83) tpl(65) cmake(55)
|                  txt(54) png(48) doc(43)
|      Conf files: cmake(55) makefile(6) launch.json(1) tasks.json(1)
|                  project.json(1)
```

**Comment by bpasero** [comment] 2020-02-29 06:35
Thanks but this trace does not tell me any process with increased CPU.

**Comment by graph** [comment] 2020-02-29 15:01
the cpu usage is very low, and it's periodic. It will be very hard on your end to debug. In the above stats I let vscode settle down for about 10min, being carefull not to put mouse on top. Moving the mouse on vscode raises CPU usage more than the period processing it's doing. For me the priority of this issue is low. Performance of vscode is very good overall, given the technology you are using I'm really amazed how well you guys managed to optimize vscode. **This ticket is a nitpick ticket, the amount I care about it is low**, but I do like seeing exactly 0 CPU usage for something I haven't used for 10+min. I can see the c++ extension is also periodically using low amounts of cpu. @bpasero are you able to reproduce the issue? For me reproducing is very easy, task manager has tiny blips periodically. Debugging I can see will be extremely hard to find out what is currently running periodically. printf every settimeout/interval :rofl: .

**Comment by bpasero** [comment] 2020-03-01 08:18
I have reported https://github.com/electron/electron/issues/22459. Closing.

**Closed by bpasero** 2020-03-01 08:18 UTC
Labels: needs more info
