### ISSUE TITLE
Snippet eats backslash

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#61043] opened 2018-10-16 12:48 UTC
Issue Type: <b>Bug</b>

1. create a user snippet with content `\\\\` (e.g. for Markdown langauge)
2. insert that snippet
3. see `\`

![image](https://user-images.githubusercontent.com/7588612/47017405-0e26a980-d14a-11e8-9fc2-76848caeb953.png)

![image](https://user-images.githubusercontent.com/7588612/47017367-fc450680-d149-11e8-9011-31972176931b.png)

VS Code version: Code - Insiders 1.29.0-insider (a0b91c2c5dff3ad25aab867f4692d08c700d5c10, 2018-10-16T07:33:17.566Z)
OS version: Windows_NT x64 10.0.18252

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment] 2018-10-22 12:00
/duplicate of 
https://github.com/Microsoft/vscode/issues/33933#issuecomment-328793257

**Closed by jrieken** 2018-10-22 12:00 UTC
Labels: insiders, snippets
