### ISSUE TITLE
Need Env Variables for DataDir and ExtensionDir

### ISSUE THREAD

**Issue by DavidWang88** [microsoft/vscode#49306] opened 2018-05-06 14:58 UTC
Currently, we can only get a few env variables when refer to the mannual [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_env).
So other extensions may access the path of extension and data dir in their code like this:

>  let settingsPath = path.join(process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE, 'commandbar.json');

And we can run vscode with command-line parameters [here](https://code.visualstudio.com/docs/editor/command-line).

If we specify the following options(for example, we can make it portable), we may change the extension and data dir settings.
> --extensions-dir \<dir>	Set the root path for extensions.
--user-data-dir \<dir>	Specifies the directory that user data is kept in, useful when running as root.

But other extensions cann't realize the changes, so it may fails. This issue may be solved when env variables of extension-dir and data-dir exposed.

---------------
VSCode v1.23.0 x64(on Win10)

**Comment by shanalikhan** [comment] 2018-07-22 18:47
I need to support Settings Sync as portable mode.
It would be great if you guys just expose these paths, currently i'm looking to solution that is not feasible though but will work

**Comment by tmeckel** [comment] 2018-11-22 09:49
Settings sync doesn't still work with VSCode when the `--user-data-dir=` command line parameter is used.

```Javascript
Error: ENOENT: no such file or directory, stat 'C:\Users\ee022a6\AppData\Roaming\Code'
	at fs.statSync (fs.js:954:11)
	at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
	at Object.statSync (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\node_modules\graceful-fs\polyfills.js:297:22)
	at new Environment (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\environmentPath.js:114:24)
	at Sync.<anonymous> (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:32:25)
	at Generator.next (<anonymous>)
	at C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:3:12)
	at Sync.bootstrap (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\sync.js:31:16)
	at C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\extension.js:18:14
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\ee022a6\AppData\Local\Apps\VSCodePortable\Data\extensions\shan.code-settings-sync-3.2.0\out\src\extension.js:4:58)
	at <anonymous>
```

**Comment by jrieken** [comment] 2020-11-10 10:31
/duplicate of https://github.com/microsoft/vscode/issues/2741

**Closed** 2020-11-10 10:32 UTC
Labels: *duplicate, api, feature-request
