### ISSUE TITLE
Configure workspace trust vs Manage workspace trust confusion

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127618] opened 2021-06-30 09:01 UTC
F1 > type "workspace trust"
You get two commands which have a very similar name but a very different outcom (one opens workspace trust editor, other opens settings).

I suggest to either:
1. Remove the one that opens the settings 
2. Rename so that the distinction is clearer

![Screenshot 2021-06-30 at 11 00 03](https://user-images.githubusercontent.com/1926584/123933138-605b9780-d992-11eb-9d04-67dfb7be46f6.png)

**Comment by lszomoru** [comment] 2021-06-30 09:04
Duplicate of #127303

**Closed by lszomoru** 2021-06-30 09:04 UTC
