### ISSUE TITLE
Opening a GH issues notebook tries to auth twice and fails

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105604] opened 2020-08-28 17:03 UTC
```
Version: 1.49.0-insider (user setup)
Commit: 21ebf4d282accd98b58bc118bff9b38d562309b4
Date: 2020-08-28T11:17:07.484Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

I've been hitting this issue for some time, I'm not sure if it's just my setup but it's quite frustrating.

Steps to Reproduce:

1. Open a VS Code window with a Github issues notebook.
   - 🐛  This dialog seems to show up almost constantly, although I've used github notebooks and signed in many times before
        ![](https://memes.peet.io/img/20-08-bdbd073e-ca70-4bf3-8af8-1fafce0a926d.png)

   - 🐛 after hitting allow or cancel, it pops up again
        - If I allow both of them, causing two browser tabs to be open, both authorizations fail with https://memes.peet.io/img/20-08-a2ff1553-00eb-437b-8aca-f1e5853538f5.png
        - If I cancel the second one, I can open a page and auth there

Does this issue occur when all extensions are disabled?: N/A

**Comment by connor4312** [comment] 2020-09-02 21:38
This is what I need to do right now to get github issue notebooks to work: https://memes.peet.io/img/20-09-bd1e433b-5975-4a59-9dae-4bb9cc86a8b1.webm

Not sure how much is a result of the auth provider versus the notebook implementation itself, cc @jrieken

**Comment by RMacfarlane** [comment] 2020-10-23 18:13
Closing as a duplicate of https://github.com/microsoft/vscode/issues/106014

**Closed by RMacfarlane** 2020-10-23 18:13 UTC
Labels: authentication, bug
