### ISSUE TITLE
Problems view filter box overflows header in panel

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97010] opened 2020-05-05 15:41 UTC
Two different themes shows the issue:

![image](https://user-images.githubusercontent.com/22350/81085581-ac7a8b80-8ef7-11ea-93c2-9603c271cc00.png)

![image](https://user-images.githubusercontent.com/22350/81085587-aedce580-8ef7-11ea-91e2-10470c2891e2.png)

**Comment by jeanp413** [comment] 2020-05-11 03:29
Duplicate of #96726
Also created #97438 that fixes it

**Closed** 2020-05-11 11:11 UTC
