### ISSUE TITLE
Inconsistency in reporting hotkey for Format Selection (Ctrl+K, Ctrl+F)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#14883] opened 2016-11-02 22:34 UTC
- VSCode Version: Code - Insiders 1.7.0-insider (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T05:39:07.207Z)
- OS Version: Windows_NT ia32 10.0.14955
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.2|

---

Steps to Reproduce:

1. Select some source code
2. Right click
3. Observe no hotkey listed for Format Selection.

![image](https://cloud.githubusercontent.com/assets/494055/19949949/d470bdee-a111-11e6-8448-f732a130be91.png)

1. Select some source code
2. Ctrl+Shift+P (Command Palette)
3. Type: "Format"
4. Observe hotkey listed in Command Palette.

![image](https://cloud.githubusercontent.com/assets/494055/19949959/e0f920ce-a111-11e6-8ada-b66fd49c1f15.png)

**Comment by jrieken** [comment] 2016-11-03 15:14
dupe of #14622

**Closed by jrieken** 2016-11-03 15:14 UTC
