### ISSUE TITLE
Preview Browser not shown

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#124084] opened 2021-05-18 07:06 UTC
Latest insiders I get the following when clicking 'Preview in Editor' instead of the preview browser:
![image](https://user-images.githubusercontent.com/9205389/118606750-0fb02680-b7b8-11eb-888a-8e9422fd9742.png)

Version: 1.57.0-insider
Commit: 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
Date: 2021-05-18T05:12:52.309Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by alexr00** [comment] 2021-05-18 09:10
@mjbvz the URI that get's passed to the simple browser opener still looks good to me.

**Comment by mjbvz** [comment] 2021-05-19 19:50
@chrmarti Is this when connected to a remote?

**Comment by chrmarti** [comment] 2021-05-20 08:42
@mjbvz Yes.

**Comment by mjbvz** [comment] 2021-05-20 19:38
This has the same root cause as #123751

**Comment by mjbvz** [comment] 2021-05-20 21:27
Should be fixed by 18ea5ac15e6c109184d70eb5d15eeee1a3ca096f

Let me know if you still see this in the next insiders build

**Closed by mjbvz** 2021-05-20 21:27 UTC
Labels: bug
