### ISSUE TITLE
Variables, Watches not updated when changed from debug console

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#2399] opened 2016-01-26 22:16 UTC
when I update a variable in the debug console while in break mode, the updated value is not reflected in the Variables or Watch panes of the debug viewlet.
- open a simple node/javascript workspace
- add some code such as

`var x = 10;`
- set a breakpoint on that line, launch app under debugger
- when broken, change x from the debug console prompt

result -> the value is not updated in the Variables/Local tree or the Watch tree (if you set up a watch).

found while testing https://github.com/Microsoft/vscode/issues/2171

**Comment by isidorn** [comment] 2016-02-02 11:30
The values will be updated once you do a step.
I am not a big fan of re-evaluating all watch expressions once you evaluate anything in the console, though we could do that. But this would cause the whole variables and watch pane to flicker once you evaluate something in the console.

I would close this as designed. @weinand opinions?

**Comment by weinand** [comment] 2016-02-02 11:33
@isidorn what's the behaviour in Chrome dev tools, node-inspector, or VS?

**Comment by isidorn** [comment] 2016-02-02 11:36
Chrome and node-inspector do not update it, they behave same as we do -> closing as deigned

**Comment by weinand** [comment] 2016-02-02 11:37
+1

**Comment by chrisdias** [comment] 2016-02-02 16:04
As a user, the expectation is that these values change when I change them in the console.  Visual Studio does this - it will update the watch, floating data tips, etc. when changing values during break mode. This is the experience we are striving for.

**Comment by isidorn** [comment] 2016-02-02 16:06
This is a valid feature request but it will cause the variables pane and watch pane to flicker every time you evaluate something in the console

**Comment by chrisdias** [comment] 2016-02-02 16:14
I guess I don't know why there is no flicker on step.  I suggest then that we fix the flicker to make the desired experience great!

**Comment by isidorn** [comment] 2016-02-02 16:22
You are right, because we preserve the tree element ids the flicker might not be big. Worth experimenting with, so on each evaluate from the repl I would refresh all the variables and all the watch expressions

**Comment by isidorn** [comment] 2016-02-05 17:47
Will add this only if more users ask for it

**Comment by csholmq** [comment] 2016-02-05 19:52
+1 

My remote GDB debugging would really benefit from having Watches update continuously when doing not using breakpoints. This works with GDB in Eclipse where variables are polled over and over again also on hover.

**Comment by harold-b** [comment] 2016-02-24 05:13
+1 
I was actually surprised it did not update when changing them in the console. Since there is no way to change values by clicking them on the tree, this would be most useful.

**Comment by tdorsey** [comment] 2016-04-08 15:02
+1

I'm less concerned about the watch windows than I am the value updating in the debug console, which DOES occur in chrome. We frequently use this to quickly set flags while in development, and this is currently not possible.

**Comment by isidorn** [comment] 2016-05-02 21:42
We are now updating the watch expressions on each evaluation in the debug repl.
However updating the variables is a bit more tricky (such that the expansion state of the tree is preserved).

**Comment by isidorn** [comment] 2016-05-03 16:10
@delmyers here's the issue I mentioned during the meeting

**Comment by isidorn** [comment] 2016-07-08 10:42
Discussions in #8118

Bottom line is that the variables view can be stale after evaluations. Setting this to july to investigate how to tackle this issue.

**Comment by gregg-miskelly** [comment] 2016-08-09 16:01
@isidorn you might already know this by now, but since you asked -- VS will reevaluate all watch expressions, and re-ask the backend for locals whenever:

* An evaluation happens in the repl
* A new watch window item is added
* An assignment happens

**Closed** 2016-11-15 15:23 UTC
Labels: debug, debug-console, feature-request

**Comment by isidorn** [comment] 2016-11-15 15:33
VSCode is now properly refreshing the UI however node and node2 debug adapters are providing stale variables which in practice means the variables view does not get refreshed.
Though this is captured in https://github.com/Microsoft/vscode/issues/15520
For debug adapters that do not do caching it should work fine now.
