### ISSUE TITLE
Markdown preview is only showing on part of the screen

### ISSUE THREAD

**Issue by aligneddev** [Microsoft/vscode#20662] opened 2017-02-15 15:13 UTC
For some reason, the Markdown previewer is only using part of the screen real estate available. I've had 
this issue for a long time now.

![vscodemdpreviewer](https://cloud.githubusercontent.com/assets/1636977/22980347/c2d1ca98-f35e-11e6-8397-25dac2dec807.png)
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.2.4|
|vscode-aurelia-snippets|behzad88|0.0.16|
|vscode-markdownlint|DavidAnson|0.6.2|
|vscode-eslint|dbaeumer|1.2.6|
|vscode-jasmine-es5|deerawan|1.0.1|
|githistory|donjayamanne|0.1.5|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|tslint|eg2|0.8.1|
|nuget4code|fforjan|0.0.2|
|JSDocTagComplete|HookyQR|0.0.2|
|Angular2|johnpapa|2.0.3|
|typelens|kisstkondoros|1.4.1|
|vscode-codemetrics|kisstkondoros|1.1.6|
|refactorix|krizzdewizz|0.3.2|
|Angular2Tests|MarinhoBrandao|0.7.2|
|mssql|ms-mssql|0.2.1|
|csharp|ms-vscode|1.7.0|
|PowerShell|ms-vscode|0.9.0|
|vs-keybindings|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|2.5.3|
|csharp2ts|rafaelsalguero|0.0.10|
|typescript-hero|rbbit|0.12.0|
|vscode-icons|robertohuertasm|7.2.0|
|code-settings-sync|Shan|2.4.3|

---

Steps to Reproduce:

1. Create a .md file with some text
2. click the preview button
bug/request: I'd like to see the preview use the full window.

**Comment by mjbvz** [comment] 2017-02-15 21:28
Duplicate of #5745

**Closed by mjbvz** 2017-02-15 21:28 UTC
Labels: duplicate, webview
