### ISSUE TITLE
On OS X 11.6 on launch bouncing VSCode icon for each open editor window

### ISSUE THREAD

**Issue by jboxman** [microsoft/vscode#139439] opened 2021-12-18 19:02 UTC
Does this issue occur when all extensions are disabled?: Yes/No; I'll check.

- VS Code Version: 1.63.1
- OS Version: OS X 11.6

Steps to Reproduce:

1. Download Nov or Dec release of VSCode.
2. Launch.
3. I have 1 VSCode instance and two additional instances bouncing in my dock. They keep bouncing and bouncing for awhile until whatever isn't happening times out and OS X gives up, I guess.

Isn't in issue in 1.61.2, so I downgraded. Have this issue on two different OS X systems.

**Comment by resistorsoftware** [comment] 2021-12-19 16:22
I have this too, on MacOS 12.0.1. Lots of bouncing instances in the dock that all lock-up after time passes.

**Comment by kimmoahokas** [comment] 2021-12-20 05:58
Might be duplicate of #138712

**Closed** 2021-12-21 21:15 UTC
Labels: *duplicate, triage-needed
