### ISSUE TITLE
Why can't I sort the installed extensions list?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12910] opened 2016-09-28 17:31 UTC
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
#12647

It seems odd to me that it's disabled on the installed extension list, particularly when the current order is a bit wacky. Sorting by name would make more sense when whatever it's sorting by here:

![image](https://cloud.githubusercontent.com/assets/2193314/18924897/b476d77e-8566-11e6-8f5c-4c34443f98a3.png)

**Comment by pauljlucas** [comment] 2016-12-01 03:40
This issue seems like it can be closed with the PR referenced above:

https://github.com/Microsoft/vscode/pull/13399

**Comment by joaomoreno** [comment] 2016-12-01 06:56
@pauljlucas This issue refers to arbitrary sorting, while #13399 picks a better default sorting.

**Comment by GerardoGR** [comment] 2016-12-12 20:47
@joaomoreno isn't the this issue (arbitrary sorting), solved by picking a better default sorting (from #13399)?

**Comment by joaomoreno** [comment] 2016-12-13 08:00
Arbitrary as in deliberate, not as in random.

**Comment by ishanjain28** [comment] 2016-12-15 05:56
I see the problem mentioned by @Tyriar fixed in version 1.8, Shouldn't this issue be closed now? I was searching for an issue where I can help, This issue is open but the problem is already fixed. 

If there is any thing that I can do to improve what has already been implemented I'd like to help! :)

**Comment by joaomoreno** [comment] 2017-04-11 13:32
Fixed by #20881

**Closed by joaomoreno** 2017-04-11 13:32 UTC
Labels: beginner, bug, extensions, help wanted
