### ISSUE TITLE
Move window view down in .py jupyter notebooks

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode#148916] opened 2022-05-06 14:59 UTC
This is a small issue, but would actually be a pretty big quality-of-life increase for me.

I usually write code in jupyter notebooks with `.py` files, and have a running jupyter notebook going with the `#%%` mechanism so that I can test out code as I write it.

However, when I tab over to the interactive part, write out python code, and press enter, the window doesn't automatically scroll down so that I can see the output - I have to do it manually. This seems small, but when I'm testing out a lot of code, it actually gets quite annoying to have to scroll down every time I want to see output of something random I'm testing.

So the feature request would be to have the interactive part in `.py` files with the `#%%` mechanism scroll down automatically so that the user can see output.

Below is a picture of what I mean.
<img width="474" alt="Capture" src="https://user-images.githubusercontent.com/12386450/167159191-d6f18323-2d31-4ebd-a0dc-b031df35f5cf.PNG">

**Comment by gjsjohnmurray** [comment] 2022-05-06 15:09
Is this a duplicate of #145353?

**Closed** 2022-05-09 19:05 UTC
Labels: *duplicate
