### ISSUE TITLE
Search and Replace in multiple (XML) files broken

### ISSUE THREAD

**Issue by W4RH4WK** [Microsoft/vscode#40908] opened 2017-12-28 16:26 UTC
- VSCode Version: 1.19.1
- OS Version: Windows 10 (1709)

It appears that there is a bug with the search and replace functionality. It is encountered when editing multiple XML files. I have recorded a screen capture to illustrate the issue.

https://youtu.be/ehuqer244S4

Content of one XML file:

```xml
<assets>
	<output mode="c" filename="../../../assetlist/_generated/I_NOTE_HELP000/header.h" rcname="../../../assetlist/_generated/I_NOTE_HELP000/assetR" fileList="g_fileNames" pathprefix="data/"/>
	<asset source="%ED8_PSV%/data/images/note/help/note_help000foo" symbol="I_NOTE_HELP000"/>
</assets>

```

Steps to Reproduce:

1. Open a folder containing a bunch of XML files.
2. *Search and replace* a string as shown in the video.
3. Observe the changes done to the XML files.

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-12-28 18:10
Weird. Great soundtrack though.

- Could you upload one of the files here, in case it's an issue of hidden characters or an unusual encoding?
- Can you show the output of the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

- Does any query match the beginning of those files, or just that particular one?
- Do you see these wrong matches in any other files?

**Comment by W4RH4WK** [comment] 2017-12-28 18:49
Upon further investigation, yes it seems like it has something to do with the encoding. When I copy-paste the content from my first post to a new file, everything works as intended.

Here is one of the files with which I can reproduce this:
[40908-1.zip](https://github.com/Microsoft/vscode/files/1591869/40908-1.zip)

This is the output of search pane:
```
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Users/w4rh4wk/Desktop/help2/**/.git' -g '!/Users/w4rh4wk/Desktop/help2/**/.svn' -g '!/Users/w4rh4wk/Desktop/help2/**/.hg' -g '!/Users/w4rh4wk/Desktop/help2/**/CVS' -g '!/Users/w4rh4wk/Desktop/help2/**/.DS_Store' -g '!/Users/w4rh4wk/Desktop/help2/**/.stack-work' -g '!/Users/w4rh4wk/Desktop/help2/**/node_modules' -g '!/Users/w4rh4wk/Desktop/help2/**/bower_components' --max-filesize '17179869184' --follow --fixed-strings -- 'ass' 'c:\Users\w4rh4wk\Desktop\help2'
 - cwd: c:/
 - Sibling clauses: {}
```

Any pattern that matches at least once triggers this behavior it seems.
All of them match the beginning of the content.
Although, everything seems to be fine if that file is open in the editor.

So far this is the first time I encountered this issue, and it may indeed be due to the file encoding. I have not experienced this with other files.

PS: [link to the soundtrack](https://www.youtube.com/watch?v=AlHyQzWfa4g), artists are listed in the description.

**Comment by W4RH4WK** [comment] 2017-12-28 18:53
It seems like it's because these files use only CR (`\r`) as their line-endings.

**Comment by roblourens** [comment] 2017-12-28 19:05
That's right - there was another issue for this but I can't find it. We don't support CR-only line endings well in general - https://github.com/Microsoft/vscode/issues/35797, I'll call this a dupe of that for now.

Is that on purpose? I can't really tell how common it is.

**Closed** 2017-12-28 19:05 UTC
Labels: *duplicate, needs more info, search

**Comment by W4RH4WK** [comment] 2017-12-28 19:33
I don't think it is that common.

Whether this was intentional for these files I don't know.

**Comment by W4RH4WK** [comment] 2017-12-28 19:36
Side note: It appears that mac OS used CR only as line-ending until version 9 (src: <http://vim.wikia.com/wiki/File_format>).
