### ISSUE TITLE
Terminal windows don't show after reloading window, but tasks still keep running

### ISSUE THREAD

**Issue by rodgobbi** [Microsoft/vscode#30861] opened 2017-07-17 14:09 UTC
- VSCode Version: 1.14.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1.  Start a server with npm in an integrated terminal window.
2.  Install an extension, then reload window.

The server still keeps working. I've tried closing vscode and then opening it but the server still keeps running.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/3410227/28271386-bdb6bc74-6ade-11e7-95c6-b1ac79b99633.png)

**Comment by Tyriar** [comment] 2017-07-17 14:41
Duplicate of https://github.com/Microsoft/vscode/issues/26807

**Closed by Tyriar** 2017-07-17 14:41 UTC
Labels: integrated-terminal, new release
