### ISSUE TITLE
Syntax highlight for template literals in JavaScript/TypeScript stopped working after the update to 1.7.1

### ISSUE THREAD

**Issue by petrlyapin** [Microsoft/vscode#15353] opened 2016-11-11 13:12 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-mocha|Compulim|0.1.1|

---

Steps to Reproduce:

1. Use any literal template in you js/ts code. For instance: var i = 0; var text = \`Number = ${i}\`;
2. Before vscode 1.7.1 the ${i} would part of the template was highlighted as a normal js code, not it is not (looks like a plain text with the same color as text part "Number =");

**Comment by aeschli** [comment] 2016-11-11 20:20
duplicate of #13166

**Closed by aeschli** 2016-11-11 20:20 UTC
