### ISSUE TITLE
Git - editor could not be opened if a file have conflict with added by us

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#153639] opened 2022-06-29 04:09 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: MACOS 12.4

Steps to Reproduce:

1. create a merge conflict and some file is added by us
2.open the file change

`CONFLICT (file location):/path/to/file added in HEAD inside a directory that was renamed in dev, suggesting it should perhaps be moved to /path/to/file`

<img width="862" alt="image" src="https://user-images.githubusercontent.com/13031838/176349504-3478b899-d2fd-4fbc-a1c7-5c9192957a9e.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/13031838/176349518-38b3491e-f97c-4b2a-92e4-634cd71174b5.png">

**Comment by lszomoru** [comment] 2022-07-27 11:59
@zWingz, sorry for not getting back to you on this. Could you please provide the complete steps that you have followed in order to create the merge conflict and how you have resolved that said conflict. That should help me reproduce and investigate this issue. Thanks!

**Comment by zWingz** [comment] 2022-07-28 02:13
- clone https://github.com/zWingz/dev.git
- git checkout a
- git checkout b
- git merge a
<img width="577" alt="image" src="https://user-images.githubusercontent.com/13031838/181405322-bc028af8-0dca-4920-bb86-c9dea0a806ae.png">

**Comment by lszomoru** [comment] 2022-07-28 07:57
@zWingz, thank you very much! I am able to reproduce the problem and will investigate further next milestone.

**Comment by samdenty** [comment] 2022-08-30 17:11
@lszomoru i'm getting this and it's blocking me for merging

**Comment by amarnath-cohesive** [comment] 2022-09-26 10:39
Facing the same issue right now

**Comment by alexbu92** [comment] 2022-09-27 12:18
same

**Comment by kpierce8** [comment] 2022-10-07 22:07
same here as well

**Comment by danielearwicker** [comment] 2022-11-14 12:56
I hit this and find that if I click the file name under _Merge Changes_, I get the above error. But if I click the "Open file" icon on that line, it opens the file as if to let me see the conflicts, but there are no conflicts.

There is the usual button bottom/right to open the Merge UX and that opens to show me the current branch on the left and incoming on the right, but the incoming panel is like an empty file.

**Comment by MartyMcFlyInTheSky** [comment] 2023-04-21 05:29
Also got this issue. "Open File" button works but It doesn't display the changes.

**Comment by grenik** [comment] 2023-05-31 07:41
I was able to solve the issue the following way:
1. Right-click the file in the Source Control view and choose Reveal in Explorer View
2. Open a file as usual from the Explorer View
3. You will see the "Resolve in merge editor" button
4. In a three-window view, directly choose "Resolve conflicts"
5. Repeat with other files

**Comment by Odafe88** [comment] 2023-08-01 13:53
Can you please share more info.

**Comment by Semerbl4** [comment] 2023-08-02 12:53
This bug turns me insane. Usually its happening then some files was moved from the one place of the project to another. I tried that grenik wrote earlier, but that doesn't work for me.

**Comment by lszomoru** [comment] 2024-12-20 14:27
Apologies for not getting back to you on this until now. I just went through the steps and I am unable to reproduce this with the latest VS Code Insiders release. I will go ahead and close this issue but if you are still able to reproduce please reopen the issue. Thanks!

**Closed by lszomoru** 2024-12-20 14:27 UTC
Labels: bug, git

**Comment by Semerbl4** [comment] 2024-12-20 14:32
> Apologies for not getting back to you on this until now. I just went through the steps and I am unable to reproduce this with the latest VS Code Insiders release. I will go ahead and close this issue but if you are still able to reproduce please reopen the issue. Thanks!

Afrer some updates its seems fine to me and i nevar saw it again

**Comment by 2af** [comment] 2025-02-03 12:08
VSCODE INSIDERS.
hit me today, none of the solutions worked.
Update to a newer version (through vscode menu) worked.
happy coding
