### ISSUE TITLE
Extension editor no longer tracks focus when clicked

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71774] opened 2019-04-05 08:24 UTC
* open an extension from the extension viewlet (open it in preview-mode)
* open a text file to the side of it
* select a file in the explorer -> the text editor is changed
* :bug: click on the extension editor, select a file in the explorer -> the text editor is changed, I expect that the extensions editor is changed

**Comment by bpasero** [comment] 2019-04-05 08:59
@mjbvz it looks like clicking into the webview no longer transfers focus into that editor, that sounds like a regression to me, possibly a candidate if that reproduces in stable. Did you change something?

**Comment by bpasero** [comment] 2019-04-05 09:00
Reproduces in stable, but interestingly only with the extension editor, not a markdown preview.

**Comment by mjbvz** [comment] 2019-04-05 21:13
I don't think this is webview specific; even if you click on the extensions title area (which is not part of the webview) the focus doesn't switch properly

**Comment by mjbvz** [comment] 2019-04-05 22:01
Having some trouble tracking down what is going on here. I believe that the dom focus tracker should be detecting when the user clicks back into the extensions page but it doesn't fire in this case

**Comment by sandy081** [comment] 2019-04-08 08:43
Checked in previous stable and not a regression.

**Comment by bpasero** [comment] 2019-04-08 10:33
I can take this.

**Comment by bpasero** [comment] 2019-04-08 10:43
This was due to 2 reasons:
* editors in the workbench that rely on the default focus tracking need `tabIndex=0` (which I now added)
* the `webview` within would not trigger a focus change, so I added a listener on the focus event from the `webview` to carry it to the outside

@mjbvz please check if the listener disposable is properly wired in, I was not sure about the content disposable array.

**Closed by bpasero** 2019-04-08 10:43 UTC
Labels: bug, extensions, webview

**Comment by konradw86** [comment] 2019-04-08 10:45
sob., 6.04.2019, 00:02 użytkownik Matt Bierner <notifications@github.com>
napisał:

**Comment by konradw86** [comment] 2019-04-08 10:45
Jak wykonać polecenia


pon., 8.04.2019, 10:44 użytkownik Sandeep Somavarapu <
notifications@github.com> napisał:

**Comment by mjbvz** [comment] 2019-04-08 18:33
Thanks @bpasero! Webview related changes look good to me
