### ISSUE TITLE
Tab Key Moves Focus

### ISSUE THREAD

**Issue by JasonGoemaat** [microsoft/vscode#235448] opened 2024-12-06 01:37 UTC
I know from searching this will remain enabled by default, but could we add a command or setting to disable it?   I don't mess with keybindings and I had to find a github issue to figure out how to disable it.    I had no idea it was even a keybinding, I don't generally mess with keybindings.   The annoying thing kept turning on, starting yesterday for me for some reason.   I don't remember ever hitting CTRL+M and didn't know what turned it on.   I think I saw the keybinding when I used CTRL+SHIFT+P to search for the text that I finally noticed at the bottom after restarting VSCODE the first several of times because I didn't know what was happening and after I searched for a setting to disable it and came up empty.  Even then it wasn't obvious to me how to disable that 'feature' entirely.

**Comment by JasonGoemaat** [comment] 2024-12-06 01:58
Clicking in the code window should disable it also.  If I understand, this is meant for accessibility for people without mice.   When my keyboard got hijacked by it I couldn't figure out what was happening.   Clicking in the code window and typing just moved it around.

**Comment by meganrogge** [comment] 2024-12-07 18:19
This is by design, thus closing. We have a command to help you troubleshoot keybindings that might help you in the future, `Developer: Toggle Keyboard Shortcuts Troubleshooting`

**Closed by meganrogge** 2024-12-07 18:19 UTC
