### ISSUE TITLE
Icons in labels

### ISSUE THREAD

**Issue by meowWhat** [microsoft/vscode#131068] opened 2021-08-18 08:21 UTC
how to use `File Theme Icon` in  label  like => [icon in labels](https://code.visualstudio.com/api/references/icons-in-labels)

**Comment by aeschli** [comment] 2021-08-18 15:18
It's currently not possible to use file icons in labels.
File icons don't have an identifier but are selected based on a resource (name and content). So we would need a notation that specifies a resource in a label

Something like `This is is icon for TypeScript files: &(hello.ts)`.

For a theme like the minimal theme, you would only see a generic file icon here. So not sure that is extremely useful.

**Comment by meowWhat** [comment] 2021-08-18 15:28
> It's currently not possible to use file icons in labels.
> File icons don't have an identifier but are selected based on a resource (name and even content). We would need a notation that specifies the resource name. Something like `This is the icon for TypeScript files: &(hello.ts)`.
> 
> For a theme like the minimal theme, you would only see a generic file icon there. So not sure that is extremely useful.
> 
> What is your use case? Note there are already ways to use file icons in the UI, e.g. in a tree item, by specifying a resource name. There are feature requests to allow this at more places.

My use case is to do a file jump in a `Quick Pick item` It's going to look like this
![image](https://user-images.githubusercontent.com/59830413/129926380-1f24b030-2a74-4162-ac40-e58049d9d499.png)
I hope the copy I show can be the same as `CTRL + P,` with file icon, so that it will be more beautiful
![image](https://user-images.githubusercontent.com/59830413/129926555-0796962b-4ddb-4fb0-afca-f5aa2a124f75.png)

**Comment by aeschli** [comment] 2021-08-18 16:09
that's #59826. Ok if I close this as a duplicate?

**Comment by igorskyflyer** [comment] 2021-08-18 18:01
> > It's currently not possible to use file icons in labels.
> > File icons don't have an identifier but are selected based on a resource (name and even content). We would need a notation that specifies the resource name. Something like `This is the icon for TypeScript files: &(hello.ts)`.
> > For a theme like the minimal theme, you would only see a generic file icon there. So not sure that is extremely useful.
> > What is your use case? Note there are already ways to use file icons in the UI, e.g. in a tree item, by specifying a resource name. There are feature requests to allow this at more places.
> 
> My use case is to do a file jump in a `Quick Pick item` It's going to look like this
> ![image](https://user-images.githubusercontent.com/59830413/129926380-1f24b030-2a74-4162-ac40-e58049d9d499.png)
> I hope the copy I show can be the same as `CTRL + P,` with file icon, so that it will be more beautiful
> ![image](https://user-images.githubusercontent.com/59830413/129926555-0796962b-4ddb-4fb0-afca-f5aa2a124f75.png)

Yes, exactly the use-case for which I need this feature, as well. 👍

**Comment by meowWhat** [comment] 2021-08-19 02:05
> that's #59826. Ok if I close this as a duplicate?

ok , thanks for your reply.

**Comment by aeschli** [comment] 2021-08-19 08:27
duplicate of #59826.

**Closed by aeschli** 2021-08-19 08:27 UTC
Labels: feature-request, needs more info, themes
