### ISSUE TITLE
Code incorrectly colored after /* in string starting with @$

### ISSUE THREAD

**Issue by bryanjhogan** [microsoft/vscode#109544] opened 2020-10-27 23:06 UTC
- VSCode Version: 1.50.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create a C# file. 
2. Add the following - 
```C# 
string text = @$"any text as long as there is a new line
/*";
```
Here is the how it looks. 

![image](https://user-images.githubusercontent.com/5768871/97371404-7ce58400-1887-11eb-8a60-e45ff9f88933.png)

If you reverse the @ and $, the problem does occur - 
``` 
string text = $@"this does not cause the problem.
/*";
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment] 2020-10-28 13:03
Looks like a duplicate of the following bugs:
https://github.com/dotnet/csharp-tmLanguage/issues/171
https://github.com/dotnet/csharp-tmLanguage/issues/162
https://github.com/dotnet/csharp-tmLanguage/issues/158

**Closed by alexr00** 2020-10-28 13:03 UTC

**Comment by bryanjhogan** [comment] 2020-10-28 17:44
The cause may be the same, but I think the symptom I described is different and should be included in any tests when fixing the problem.
