### ISSUE TITLE
Ctrl + Shift + G does not focus on Message

### ISSUE THREAD

**Issue by elibroftw** [microsoft/vscode#141332] opened 2022-01-24 22:11 UTC
Does this issue occur when all extensions are disabled?: Yes
(follow the steps twice and you will get the following)
![image](https://user-images.githubusercontent.com/21298211/150873668-039f58ef-6bb6-4db2-b0ef-0f2ec09eae3d.png)

- VS Code Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. ![image](https://user-images.githubusercontent.com/21298211/150873270-8cf5417a-234c-4370-bf60-1e004f80eda6.png)
2. Press Ctrl + Shift + G
3. ![image](https://user-images.githubusercontent.com/21298211/150873319-b15c9d5d-481c-4ce7-97ed-ba6d06a5161b.png)
4. Type `my message`
5. ![image](https://user-images.githubusercontent.com/21298211/150873453-8371e0f0-3a37-424c-a55e-9c2615cebdda.png)

Expected:
![image](https://user-images.githubusercontent.com/21298211/150873490-a3f302a0-b8ea-42f7-b5f2-bd06e921e472.png)

**Comment by lszomoru** [comment] 2022-12-09 13:40
@elibroftw, apologies for not getting back to you on this until now.  I am unable to reproduce this issue with the latest Insiders build. I will go ahead and close this issue but please feel free to reopen in case you are still able to reproduce it. Thank you very much!

**Closed by lszomoru** 2022-12-09 13:40 UTC
Labels: bug, scm
