### ISSUE TITLE
Consistent TS server crashes 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#143135] opened 2022-02-15 20:04 UTC
Not sure of an exact repro, but whenever I have the `webview-query-tokens` branch opened in vscode insiders (update, even on `main` I still see this), I get consistent crashes. Nothing too interesting in the TS log: 
```
[Info  - 19:40:22.63] Starting TS Server 
[Info  - 19:40:22.63] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:40:22.64] <syntax> Forking...
[Info  - 19:40:22.66] <syntax> Starting...
[Info  - 19:40:22.66] <semantic> Forking...
[Info  - 19:40:22.68] <semantic> Starting...
[Info  - 19:58:05.580] TSServer exited. Signal: SIGABRT
[Info  - 19:58:05.581] Starting TS Server 
[Info  - 19:58:05.581] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:58:05.596] <syntax> Forking...
[Info  - 19:58:05.597] <syntax> Starting...
[Info  - 19:58:05.598] <semantic> Forking...
[Info  - 19:58:05.600] <semantic> Starting...
[Info  - 19:58:27.423] TSServer exited. Signal: SIGABRT
[Info  - 19:58:27.423] Starting TS Server 
[Info  - 19:58:27.423] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:58:27.426] <syntax> Forking...
[Info  - 19:58:27.427] <syntax> Starting...
[Info  - 19:58:27.428] <semantic> Forking...
[Info  - 19:58:27.429] <semantic> Starting...
[Info  - 19:58:49.751] TSServer exited. Signal: SIGABRT
[Info  - 19:58:49.751] Starting TS Server 
[Info  - 19:58:49.751] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:58:49.753] <syntax> Forking...
[Info  - 19:58:49.754] <syntax> Starting...
[Info  - 19:58:49.754] <semantic> Forking...
[Info  - 19:58:49.756] <semantic> Starting...
[Info  - 19:59:04.753] TSServer exited. Signal: SIGABRT
[Info  - 19:59:04.753] Starting TS Server 
[Info  - 19:59:04.753] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:59:04.754] <syntax> Forking...
[Info  - 19:59:04.755] <syntax> Starting...
[Info  - 19:59:04.755] <semantic> Forking...
[Info  - 19:59:04.756] <semantic> Starting...
[Info  - 19:59:19.159] TSServer exited. Signal: SIGABRT
[Info  - 19:59:19.159] Starting TS Server 
[Info  - 19:59:19.159] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:59:19.160] <syntax> Forking...
[Info  - 19:59:19.162] <syntax> Starting...
[Info  - 19:59:19.163] <semantic> Forking...
[Info  - 19:59:19.165] <semantic> Starting...
[Info  - 19:59:36.686] TSServer exited. Signal: SIGABRT
[Info  - 19:59:36.686] Starting TS Server 
[Info  - 19:59:36.686] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:59:36.687] <syntax> Forking...
[Info  - 19:59:36.688] <syntax> Starting...
[Info  - 19:59:36.688] <semantic> Forking...
[Info  - 19:59:36.690] <semantic> Starting...
[Info  - 19:59:51.301] TSServer exited. Signal: SIGABRT
[Info  - 19:59:51.301] Starting TS Server 
[Info  - 19:59:51.301] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 19:59:51.302] <syntax> Forking...
[Info  - 19:59:51.303] <syntax> Starting...
[Info  - 19:59:51.303] <semantic> Forking...
[Info  - 19:59:51.304] <semantic> Starting...
[Info  - 20:00:05.686] TSServer exited. Signal: SIGABRT
[Info  - 20:00:05.686] Starting TS Server 
[Info  - 20:00:05.686] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:00:05.686] <syntax> Forking...
[Info  - 20:00:05.687] <syntax> Starting...
[Info  - 20:00:05.687] <semantic> Forking...
[Info  - 20:00:05.690] <semantic> Starting...
[Info  - 20:00:20.385] TSServer exited. Signal: SIGABRT
[Info  - 20:00:20.385] Starting TS Server 
[Info  - 20:00:20.385] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:00:20.386] <syntax> Forking...
[Info  - 20:00:20.387] <syntax> Starting...
[Info  - 20:00:20.387] <semantic> Forking...
[Info  - 20:00:20.390] <semantic> Starting...
[Info  - 20:00:36.549] TSServer exited. Signal: SIGABRT
[Info  - 20:00:36.549] Starting TS Server 
[Info  - 20:00:36.549] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:00:36.550] <syntax> Forking...
[Info  - 20:00:36.551] <syntax> Starting...
[Info  - 20:00:36.551] <semantic> Forking...
[Info  - 20:00:36.553] <semantic> Starting...
[Info  - 20:00:55.629] TSServer exited. Signal: SIGABRT
[Info  - 20:00:55.629] Starting TS Server 
[Info  - 20:00:55.629] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:00:55.630] <syntax> Forking...
[Info  - 20:00:55.632] <syntax> Starting...
[Info  - 20:00:55.632] <semantic> Forking...
[Info  - 20:00:55.634] <semantic> Starting...
[Info  - 20:01:10.874] TSServer exited. Signal: SIGABRT
[Info  - 20:01:10.874] Starting TS Server 
[Info  - 20:01:10.874] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:01:10.875] <syntax> Forking...
[Info  - 20:01:10.876] <syntax> Starting...
[Info  - 20:01:10.876] <semantic> Forking...
[Info  - 20:01:10.877] <semantic> Starting...
[Info  - 20:01:25.116] TSServer exited. Signal: SIGABRT
[Info  - 20:01:25.116] Starting TS Server 
[Info  - 20:01:25.116] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:01:25.117] <syntax> Forking...
[Info  - 20:01:25.118] <syntax> Starting...
[Info  - 20:01:25.118] <semantic> Forking...
[Info  - 20:01:25.119] <semantic> Starting...
[Info  - 20:01:38.843] TSServer exited. Signal: SIGABRT
[Info  - 20:01:38.843] Starting TS Server 
[Info  - 20:01:38.843] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:01:38.844] <syntax> Forking...
[Info  - 20:01:38.845] <syntax> Starting...
[Info  - 20:01:38.845] <semantic> Forking...
[Info  - 20:01:38.846] <semantic> Starting...
[Info  - 20:01:54.266] TSServer exited. Signal: SIGABRT
[Info  - 20:01:54.266] Starting TS Server 
[Info  - 20:01:54.266] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:01:54.266] <syntax> Forking...
[Info  - 20:01:54.267] <syntax> Starting...
[Info  - 20:01:54.268] <semantic> Forking...
[Info  - 20:01:54.269] <semantic> Starting...
[Info  - 20:02:11.833] TSServer exited. Signal: SIGABRT
[Info  - 20:02:11.833] Starting TS Server 
[Info  - 20:02:11.833] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:02:11.834] <syntax> Forking...
[Info  - 20:02:11.835] <syntax> Starting...
[Info  - 20:02:11.835] <semantic> Forking...
[Info  - 20:02:11.837] <semantic> Starting...
[Info  - 20:02:28.802] TSServer exited. Signal: SIGABRT
[Info  - 20:02:28.802] Starting TS Server 
[Info  - 20:02:28.802] Using tsserver from: /Users/jkearl/Developer/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 20:02:28.803] <syntax> Forking...
[Info  - 20:02:28.804] <syntax> Starting...
[Info  - 20:02:28.804] <semantic> Forking...
[Info  - 20:02:28.807] <semantic> Starting...
```

dev tools also doesn't have anything.

**Comment by mjbvz** [comment] 2022-02-15 20:45
@JacksonKearl I see you are on typescript 4.5.4. Can you test this using the latest typescript insiders builds and share the logs from that if it is still crashing

Not sure where the `SIGABRT` is coming from. From the logs it doesn't seem like we're killing the server due to an error

**Comment by JacksonKearl** [comment] 2022-02-15 22:08
<img width="712" alt="image" src="https://user-images.githubusercontent.com/8586769/154157723-579e702c-4e6b-415e-b2a3-4645ba502f4c.png">
I don't believe I'm on 4.5.4? 

And this reproduces reliably when I open a file from a PR in the PR view, but I see it in other areas too

**Comment by mjbvz** [comment] 2022-02-15 22:12
Oh sorry, looked at the wrong log file. Can you quickly also try uninstalling/disabling the tslint extensions and possibly the intellicode extension too?

**Comment by JacksonKearl** [comment] 2022-02-15 22:30
Disabling tslint resolves it 👍

**Comment by mjbvz** [comment] 2022-02-15 22:40
Thanks. Looks like a duplicate of https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/148

**Closed by mjbvz** 2022-02-15 22:40 UTC
