### ISSUE TITLE
webview in sidebar position wrong

### ISSUE THREAD

**Issue by johnsen-zhang** [microsoft/vscode#126797] opened 2021-06-21 03:13 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: macOS Big Sur 11.4

I need sidebar item rich element,  like extension items, but treeItem is single. use webview position is wrong

Steps to Reproduce:

1. create multi-webviews in sidebar
2. change visible or collapsed some times, webview sidebar iframe’s parent(div) position not change

![image](https://user-images.githubusercontent.com/14013459/122701705-66f65a80-d280-11eb-89c7-85f220626fb4.png)

![image](https://user-images.githubusercontent.com/14013459/122701718-6c53a500-d280-11eb-84be-f23168a58c74.png)

![image](https://user-images.githubusercontent.com/14013459/122701728-71b0ef80-d280-11eb-9512-2a9847cee6dc.png)

**Comment by mjbvz** [comment] 2021-07-14 02:56
Duplicate of #110450

**Closed by mjbvz** 2021-07-14 02:56 UTC
