### ISSUE TITLE
--wait released if split editor is closed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#134299] opened 2021-10-01 18:56 UTC
Testing https://github.com/microsoft/vscode/issues/133124

1. Open a file with `--wait`
2. Split it to the right
3. Close the right-hand editor
4. 🐛 wait is released even though one editor for the file is still open

**Comment by connor4312** [comment] 2021-10-15 17:30
I'm still able to repro this: https://memes.peet.io/img/21-10-218a34c3-1935-45fe-92b3-11df9ce3e9f1.mp4

**Comment by bpasero** [comment] 2021-10-16 05:42
Oh wow, I totally misunderstood the issue, I had thought and actually fixed an issue when you select "Split in editor group" (the new feature I added recently). I was not aware you split to the right.

In that case, releasing the editor I think works as intended because you are closing the file. We have no concept of tracking multiple editors of the same file when `--wait` is used and I think it goes a bit beyond what this feature was meant to be...

**Closed** 2021-10-18 06:46 UTC
Labels: needs more info, under-discussion
