### ISSUE TITLE
Code Folding Toggles should be smaller

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#59695] opened 2018-09-30 17:09 UTC
Issue Type: Bug/UI

- VSCode Version: 1.28.0-insiders
- OS Version: Windows 10 1803 17134.320

Steps to Reproduce:

1. Hover to gutter
2. See code folding toggles, too large

I like that the code-folding buttons are now larger and more clickable, as the previous ones were too small. However they are now abnormally large. They are larger than the line numbers and get cut off by gutter decorations. They should be smaller, perhaps inline with numbers' heights. Screenshot to show:
![largefold](https://user-images.githubusercontent.com/30497573/46260293-ef82aa80-c4db-11e8-9b59-48f2cb091a12.png)

The red lines indicate height with relation to line number. Font size of 14 but any size has this issue. They are very off, and I can also see how off-centered it is by about 3px down. It is also very off in that the distance to the actual editor itself is smaller than distance between itself and line number is. The red lines show this:
![smalldistancefold](https://user-images.githubusercontent.com/30497573/46260226-05dc3680-c4db-11e8-8fa2-794f7527c6e9.png)

And when it comes to gutter decorations, it gets really off:
![decoroverfold](https://user-images.githubusercontent.com/30497573/46260248-6b302780-c4db-11e8-9133-07668569a373.png)

Whilst it is large enough so that it is clickable, imo it seems poorly thought of. Especially since you can hover over the gutter decoration and click the button at the same time. Suggestion: shrink the size by like 3 - 5px (my opinion, idk how much it actually is) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment] 2018-10-02 08:37
I'm able to reproduce by changing the line height to 30.
@beastdestroyer Is that the setting you have? Any other settings that you have?

@misolori I guess this got introduced by https://github.com/Microsoft/vscode/commit/615fd2c63813c9f6f561ba80a841c3ac9bfc8625

**Comment by beastdestroyer** [comment] 2018-10-02 16:15
Yh I have my line height to I think 35 or 36, the lowest I've gone is around 30 but haven't checked below

**Comment by misolori** [comment] 2018-10-02 16:31
Yea, I was using the height of the row to determine the size of the icons. I'll need to revisit my solution so that it works in both `editor.fontSize` and `editor.lineHeight`.

**Comment by beastdestroyer** [comment] 2018-10-02 17:41
What if you make it like say like 60 - 80% of the line height at maximum. It would be more fitting (not saying it's an exact figure)

**Comment by misolori** [comment] 2018-10-04 16:46
@beastdestroyer the problem is we're using the icon as a background image, which doesn't respect `font-size` or `line-height`.

@isidorn FYI, this problem also occurs on breakpoints:
![image](https://user-images.githubusercontent.com/35271042/46489455-45946e00-c7ba-11e8-8050-da526a06f87b.png)

**Comment by beastdestroyer** [comment] 2018-10-04 16:59
After changing my `line-height` values one-by-one from 20 - 35, I've noticed that the SVG (which the icon seems to be) scales up quicker than the actual line height is doing. 

Would it be possible to create a function that changes the width and height based on the editor's `font-size`, and then injecting the change into CSS? That way if the `line-height` does change, it'd still be respective of the font?

**Comment by andyunleashed** [comment] 2018-12-13 13:59
Hi @rebornix / @misolori - this can be rectified by applying `background-size: 100%;` to the `.cldr.folding` class. Could also target `.folding.collapsed` also.

**Comment by andyunleashed** [comment] 2019-02-08 10:28
Have done a PR for the fix for this, just removing the "auto" from the .folding class.

[PR #68226](https://github.com/Microsoft/vscode/pull/68226)

**Comment by misolori** [comment] 2019-02-08 17:05
@andyunleashed thanks for taking a look, left some comments in the PR.

**Comment by gjsjohnmurray** [comment] 2019-08-17 13:46
> 
> 
> Have done a PR for the fix for this, just removing the "auto" from the .folding class.
> 
> [PR #68226](https://github.com/Microsoft/vscode/pull/68226)

Maybe this issue and the above PR from @andyunleashed have been rendered obsolete by recent icon changes.

**Comment by equinusocio** [comment] 2019-08-20 20:07
@gjsjohnmurray The isse still there. To fix this, I think the `background-size` css property can just set the size.

**Comment by gjsjohnmurray** [comment] 2019-08-21 09:44
@equinusocio looks like that PR from @andyunleashed hasn't been merged. Maybe @misolori plans to fix the issue another way.

**Comment by Xeronic** [comment] 2019-08-26 14:13
Is it possible to change the folding icon somehow? I would like the icon to be a triangle like Textmate has.

**Comment by misolori** [comment] 2019-09-19 02:45
Pushed a fix via https://github.com/microsoft/vscode/commit/8b6e0efc0a98639085fabeb5226a516785424796 that uses our new icon font and allows font-size and line-height variations to be respected. Here's a quick before and after:

![folding-icon](https://user-images.githubusercontent.com/35271042/65209323-9b563a80-da4c-11e9-86dd-a679b268159b.gif)

**Closed by misolori** 2019-09-19 02:45 UTC
Labels: bug
