### ISSUE TITLE
The shortcut to close the window appears to be wrong

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#90839] opened 2020-02-17 17:28 UTC
In the file menu there is an option to close the editor and an option to close the window.
Both options have the same associated shortcut, ctrl + w.
I may be mistaken, but I think the correct shortcut to close the window should be ctrl + shift + w.

**Comment by IllusionMH** [comment] 2020-02-17 17:45
It's actually one of two possible shortcuts (even if it has conditions)
![image](https://user-images.githubusercontent.com/1312662/74675944-76155600-51bd-11ea-84d9-dc083f6ccfb5.png)

And looks like duplicate of #40389

**Comment by gjsjohnmurray** [comment] 2020-02-17 17:46
/needsMoreInfo What platform? What version of VS Code?

Here's what my 1.42.1 on Windows has:

![image](https://user-images.githubusercontent.com/6726799/74676211-655ce400-51ad-11ea-9f7f-e8c706463584.png)

**Comment by jvesouza** [comment] 2020-02-17 18:43
OOPS!

Version: 1.43.0-insider
Commit: 6ec6f9e3f4d17f0cef0480688a1f350b9141e567
Date: 2020-02-17T05:36:33.659Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.4-arch1-1

**Closed** 2020-02-17 19:45 UTC
