### ISSUE TITLE
terminal isn't working 

### ISSUE THREAD

**Issue by shivraj19** [microsoft/vscode#102554] opened 2020-07-15 02:43 UTC
terminal section remains blank in vscode. plz tell how can i solve this......
i am beginner.learning to code

**Comment by phistuck** [comment] 2020-07-15 07:19
Not sure whether it is the same issue, but I use the bash terminal, on Windows 10.
When I create a new terminal (or just go to the terminal), I see a blank terminal. It is actually scrolled down. If I type something without scrolling up, it will process my typed command. If I first scroll up, it will ignore anything I type (the caret will not show up at all).
![image](https://user-images.githubusercontent.com/184400/87515140-0cbe4400-c684-11ea-99c7-4704295b916a.png)
After scrolling up -
![image](https://user-images.githubusercontent.com/184400/87515319-5a3ab100-c684-11ea-9a86-ecb2fe875b43.png)
However, pressing Enter will fix it.

I also have an seemingly unrelated issue (but it is not so new, a few months) where the colors of the bash terminal change after some time, usually to black on black. I can copy the text to an editor to see what it written there, so the content is there, but I cannot see it in the terminal itself.

**Comment by phistuck** [comment] 2020-07-15 07:23
Reproduces in 1.47.1 as well.

**Comment by thijsputman** [comment] 2020-07-16 13:45
I _\*think\*_ I'm experiencing the same issue:

![vscode](https://user-images.githubusercontent.com/4418373/87677161-ba5f4f00-c779-11ea-8a0e-6772a9068240.png)

Occasionally when opening VS Code (I'd say about one in five times), the bottom pane (which contains the terminal) remains empty. Trying to toggle the terminal (`ctrl`+`` ` ``) doesn't have any effect (nor trying to open anything else in the bottom panel for that matter).

Closing and reopening the window resolves the issue.

Started noticing this behaviour recently &ndash; I'd say since 1.47. Currently running 1.47.1 which also exhibits the issue.

```
CPUs              Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)
GPU Status        2d_canvas: enabled
                  flash_3d: enabled
                  flash_stage3d: enabled
                  flash_stage3d_baseline: enabled
                  gpu_compositing: enabled
                  multiple_raster_threads: enabled_on
                  oop_rasterization: disabled_off
                  protected_video_decode: enabled
                  rasterization: enabled
                  skia_renderer: disabled_off_ok
                  video_decode: enabled
                  viz_display_compositor: enabled_on
                  viz_hit_test_surface_layer: disabled_off_ok
                  webgl: enabled
                  webgl2: enabled
                  Load (avg)	undefined
                  Memory (System)	15.85GB (5.41GB free)
                  Process Argv	
                  Screen Reader	no
VM                0%
--------------------------------------------------------------------------------
Remote	WSL:      Ubuntu
OS                Linux x64 4.19.104-microsoft-standard
CPUs              Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2903)
Memory (System)   7.77GB (4.60GB free)
VM                0%
```

**Comment by Tyriar** [comment] 2020-08-03 17:59
Closing as OP is non-responsive.

**Closed by Tyriar** 2020-08-03 17:59 UTC
Labels: needs more info

**Comment by Tyriar** [comment] 2020-08-03 21:00
@shivraj19 for your particular issue it's likely related to Windows 10 being out of date (<=1809, build number <= 10.0.18362)
