### ISSUE TITLE
Regex search does not work with \n or \r

### ISSUE THREAD

**Issue by nmohamad** [Microsoft/vscode#5199] opened 2016-04-12 18:30 UTC
- VSCode Version: 0.10.11
- OS Version: Win 7 , SP 1

Steps to Reproduce:
Assume you have a document with the following lines: 
// 1
// 2
// 3

1. Open search window (ctrl+f) and activate search with regex ( alt+R) 
2. type in search box : //\s1
Expected Result : One match 
3. add \n or \r to the end of search regex (now search regex will be : //\s1(\n|\r)
Bug: No Result!!

**Comment by Tyriar** [comment] 2016-04-14 02:15
Duplicate of https://github.com/Microsoft/vscode/issues/313

**Closed by Tyriar** 2016-04-14 02:15 UTC
