### ISSUE TITLE
Following characters disappear upon suggestion selected.

### ISSUE THREAD

**Issue by kaleidocli** [microsoft/vscode#82410] opened 2019-10-12 03:51 UTC
Issue Type: <b>Bug</b>

1. Type something (e.g. int)
https://pasteboard.co/IBzwRQC.png

2. Either hit ENTER or TAB or click on the suggested word. (e.g. int) And then the a few characters following disappear.
https://pasteboard.co/IBzxMDk.png

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:44:05.506Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (19.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by usernamehw** [comment] 2019-10-12 07:28
duplicate of #82324 ?

**Closed** 2019-10-14 07:18 UTC
Labels: *duplicate
