### ISSUE TITLE
Goto definition on event no longer goes to definition

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119304] opened 2021-03-19 09:17 UTC
Steps to Reproduce:

1. open `extensionsWatcher.ts`
2. in the `constructor` add the following code

```ts
fileService.onDidFilesChange(e => {

});
```
3. ctrl-click into `onDidFilesChange`

=> 🐛 you end up in 

https://github.com/microsoft/vscode/blob/0627cf0a2d2e8097bb1e0b585fbf699f5c65ec98/src/vs/base/common/event.ts#L17-L17

**Comment by mjbvz** [comment] 2021-03-19 21:27
Duplicate of https://github.com/microsoft/TypeScript/issues/43276

As far as I know, this is not a regression. I see this as far back as 3.0. What's changes is that we added options to go directly to the first definition instead of always showing the list if there are multiple definitions

**Comment by bpasero** [comment] 2021-03-22 07:51
@mjbvz there is still something wrong here I think, see this example:

![recording](https://user-images.githubusercontent.com/900690/111956902-a085c100-8aeb-11eb-8a86-d8b78e2e1504.gif)

According to the setting description: "Go to the primary result..."

But this is by no means the "primary" result.

You can see how it puts focus on the right primary result when this setting is not enabled:

![image](https://user-images.githubusercontent.com/900690/111957019-c9a65180-8aeb-11eb-98e1-a4ed815f785f.png)

//cc @jrieken

**Comment by mjbvz** [comment] 2021-03-22 21:02
TS has no concept of a "primary" definition, it just returns a list of definitions. In the first example, the definition you want happens to be first in the list. In the second example, it is not 

The upstream issue tracks improving this

**Comment by jrieken** [comment] 2021-04-06 14:25
very likely due to https://github.com/microsoft/vscode/pull/117424

**Comment by jrieken** [comment] 2021-04-06 14:26
/duplicate of https://github.com/microsoft/vscode/issues/119086

**Closed** 2021-04-06 14:27 UTC
Labels: *duplicate, papercut :drop_of_blood:, typescript, upstream-issue-linked
