### ISSUE TITLE
Cannot input Chinese on the terminal

### ISSUE THREAD

**Issue by longshihui** [microsoft/vscode#116030] opened 2021-02-07 13:14 UTC
Issue Type: <b>Bug</b>

Under windows, no matter how to switch the input method, switch the terminal, the Chinese cannot be input.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.17GB free)|
|Process Argv|--crash-reporter-id 88bfc35a-e9f1-4dad-a207-82dd560d8fd8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.1
font-switcher|eva|3.1.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.23.0
todo-tree|Gru|0.0.196
vscode-nginx-conf-hint|han|0.1.0
npm-dependency-links|her|1.2.0
vue-snippets|hol|1.0.4
vue|jcb|0.1.5
webpack|jer|2.2.0
Lua-Nginx-Snippets|jie|0.0.4
Lua|key|0.0.9
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.28.0
vscode-exec-node|mir|0.5.3
vscode-language-pack-zh-hans|MS-|1.53.2
debugger-for-chrome|msj|4.12.12
gulptasks|nic|1.3.1
vetur|oct|0.32.0
vscode-gitignore-generator|pio|1.0.2
material-icon-theme|PKi|4.5.0
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
vscode-css-peek|pra|4.0.2
nginx-formatter|ray|0.0.11
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.14.0
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
sonarlint-vscode|Son|1.20.1
open-in-browser|tec|2.0.0
vscode-counter|uct|2.2.2
win-ca|uko|3.3.0
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by yume-chan** [comment] 2021-02-07 13:18
Duplicate of #115814

**Closed** 2021-02-08 10:54 UTC
Labels: *duplicate, new release

**Comment by Lyun92** [comment] 2021-02-09 07:29
same question ,..
