### ISSUE TITLE
saved files are not displying in the source control tab

### ISSUE THREAD

**Issue by chamodSamajith** [microsoft/vscode#104422] opened 2020-08-11 09:38 UTC
when I saved files with some changes, those files are not displayed in the source control tab,  need to find that file again and double save the same files to display on the tab
worked fine on the previous update

- VSCode Version: 1.47.3
- OS Version: Windows 10 pro

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gaston-senac** [comment] 2020-08-12 03:10
I have been editing PowerShell files and the same happened to me, some files not showing on the list of changed files. These file changes were uploaded to Github though, so they got recognized by git.

**Comment by bpasero** [comment] 2020-08-13 08:45
This could also be the file watcher not working properly. To confirm:
* you open a file
* you make changes
* you save
* the file does not appear in changes until you reload?

**Comment by gaston-senac** [comment] 2020-08-14 02:55
@bpasero I think you might be correct.
I will post a gif with two file changes that I did and then saved the file. Even though the Source Control tries to reload it's not showing those two files as changed.
![vscode source control](https://user-images.githubusercontent.com/41843454/90208907-18955580-de3e-11ea-9096-b012d33f394b.gif)

**Comment by bpasero** [comment] 2020-08-14 07:13
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Especially look for file watcher entries at the time you save the file. If no entry appears, this would signal that file watcher is not working for that file.

Thanks!

**Comment by gaston-senac** [comment] 2020-08-17 00:14
[3632:0817/120440.980:INFO:CONSOLE(1679)] "%cTRACE color: #888 [storage state.vscdb] Trace (event): END TRANSACTION", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.015:INFO:CONSOLE(1679)] "%cTRACE color: #888 CommandService#executeCommand type", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.026:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.026:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - new versionId 1 file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.027:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.028:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.032:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] clearing pending backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.033:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.360:INFO:CONSOLE(1679)] "%cTRACE color: #888 CommandService#executeCommand type", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.362:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.362:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - new versionId 2 file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.362:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.363:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] clearing pending backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120441.363:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120442.365:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] running backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source:
file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.447:INFO:CONSOLE(1679)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.files.save", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.448:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] save() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.449:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] doSave(2) - enter with versionId 2 file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.454:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.454:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - new versionId 3 file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.455:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.455:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.458:INFO:CONSOLE(1679)] "%cTRACE color: #888 telemetry/workbenchActionExecuted [object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120446.474:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] doSave(3) - before write() file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.460:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] running backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source:
file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.481:INFO:CONSOLE(1679)] "%cTRACE color: #888 [File Watcher (C#)] [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.481:INFO:CONSOLE(1679)] "%cTRACE color: #888 [File Watcher (C#)] [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.485:INFO:CONSOLE(1679)] "%cTRACE color: #888 [File Watcher (C#)] [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.489:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] handleSaveSuccess(3) - setting dirty to false because versionId did not change file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.489:INFO:CONSOLE(1679)] "%cTRACE color: #888 [backup tracker] discarding backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.495:INFO:CONSOLE(1679)] "%cTRACE color: #888 telemetry/filePUT [object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.496:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] save() - exit file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.602:INFO:CONSOLE(1679)] "%cTRACE color: #888 [File Watcher (C#)]  >> normalized [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120447.611:INFO:CONSOLE(1679)] "%cTRACE color: #888 [text file model] load() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120448.904:INFO:CONSOLE(1679)] "%cTRACE color: #888 [Decorations] keepItem -> CANCEL previous vscode.git [object Object] [object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120449.009:INFO:CONSOLE(1679)] "%cTRACE color: #888 [Decorations] getOrRetrieve -> RESULT vscode.git [object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)
[3632:0817/120449.010:INFO:CONSOLE(1679)] "%cTRACE color: #888 DecorationsService#getDecoration#getOrRetrieve vscode.git [object Object] false [object Object]", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1679)

**Comment by gaston-senac** [comment] 2020-08-17 00:16
TRACE [storage state.vscdb] Trace (event): END TRANSACTION
log.ts:173 TRACE CommandService#executeCommand type
log.ts:173 TRACE [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - new versionId 1 file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] clearing pending backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE CommandService#executeCommand type
log.ts:173 TRACE [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - new versionId 2 file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] clearing pending backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] running backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE CommandService#executeCommand workbench.action.files.save
log.ts:173 TRACE [text file model] save() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] doSave(2) - enter with versionId 2 file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - new versionId 3 file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [text file model] onModelContentChanged() - model content changed and marked as dirty file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] scheduling backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE telemetry/workbenchActionExecuted 
{id: "workbench.action.files.save", from: "keybinding", VSCode.ABExp.Features: "", abexp.assignmentcontext: ""}
log.ts:173 TRACE [text file model] doSave(3) - before write() file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] running backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
3
log.ts:173 TRACE [File Watcher (C#)] [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1
log.ts:173 TRACE [text file model] handleSaveSuccess(3) - setting dirty to false because versionId did not change file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [backup tracker] discarding backup file:///d%3A/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE telemetry/filePUT 
{mimeType: "text/x-powershell, text/plain", ext: ".ps1", path: -1196584284, reason: 1, whitelistedjson: undefined, …}
log.ts:173 TRACE [text file model] save() - exit file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [File Watcher (C#)]  >> normalized [CHANGED] d:\GitHub\CT_Exchange\testing\string.ps1
log.ts:173 TRACE [text file model] load() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1
log.ts:173 TRACE [Decorations] keepItem -> CANCEL previous vscode.git 
u {scheme: "file", authority: "", path: "/d:/GitHub/CT_Exchange/Libraries/get-user.ps1", query: "", fragment: "", …}
 
{weight: 2, bubble: true, color: "gitDecoration.modifiedResourceForeground", tooltip: "Modified", letter: "M"}
log.ts:173 TRACE [Decorations] getOrRetrieve -> RESULT vscode.git 
u {scheme: "file", authority: "", path: "/d:/GitHub/CT_Exchange/Libraries/get-user.ps1", query: "", fragment: "", …}
log.ts:173 TRACE DecorationsService#getDecoration#getOrRetrieve vscode.git 
{weight: 2, bubble: true, color: "gitDecoration.modifiedResourceForeground", tooltip: "Modified", letter: "M"}
 false 
u {scheme: "file", authority: "", path: "/d:/GitHub/CT_Exchange/Libraries/get-user.ps1", query: "", fragment: "", …}
log.ts:173 TRACE telemetry/resolveProxy 
{count: 0, duration: 0, errorCount: 0, cacheCount: 0, cacheSize: 0, …}
log.ts:173 TRACE [text file model] load() - enter file:///d:/GitHub/CT_Exchange/testing/string.ps1

**Comment by gaston-senac** [comment] 2020-08-17 04:19
The bug it's not there all the time and I think it happens mainly if the file was already opened (tab) when I open VS code
Most of the time if I open any other file from the explorer view, then it behaves as it should.

**Comment by bpasero** [comment] 2020-08-17 06:52
@gaston-senac is `d:\GitHub\CT_Exchange\testing\string.ps1` the file you edit that does not appear in the changes view?

**Comment by gaston-senac** [comment] 2020-08-17 07:01
I've noticed the issue with many files, but yes, that one "string.ps1" is the one not showing on the test I did today and when I posted the logs.
________________________________

**Comment by bpasero** [comment] 2020-08-17 07:11
Ok thanks, then I do not think this is a file watcher issue given the log.

**Comment by bpasero** [comment] 2020-08-17 07:11
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2020-09-10 11:23 UTC
Labels: needs more info, scm
