### ISSUE TITLE
Side Bar/Explorer: Collapse All Panels

### ISSUE THREAD

**Issue by KyleKing** [Microsoft/vscode#66668] opened 2019-01-17 14:28 UTC
- [x] Searched issues and didn't find a duplicate (let me know if there is one!)

It would be great to have a command palette option to collapse all panels in the Explorer view. Right now it looks like the only way to collapse panels is to click the collapse arrow circled in red:

![collapseme](https://user-images.githubusercontent.com/3784339/51325032-15f03580-1a3a-11e9-8c25-5d703e26fec5.png)

Alternatively, could the Explorer: Focus command collapse-all except for the select option?

```
>Explorer: Focus on Folders View
```

---

PS: I don't actually have that many panels open at once :smile: Usually just toggling between code map and folders view. I opened a related issues on the plugin VS-CodeMap to toggle that panel specifically as another alternative (https://github.com/oleg-shilo/codemap.vscode/issues/8)

**Comment by isidorn** [comment] 2019-01-17 14:49
@sandy081 giving to you. Also look at all the clutter in the explorer - everything I mentioned in the standup just now

**Comment by sandy081** [comment] 2019-01-18 10:52
@isidorn I know but this is because extensions wanted their views to be in the explorer and user wanted to have it. Having another default viewlet will not make the product better in regards to cluttering.

**Comment by sandy081** [comment] 2019-01-18 10:53
Duplicate of #34972

**Closed** 2019-01-18 10:53 UTC
Labels: *duplicate, explorer-custom, feature-request
