### ISSUE TITLE
Provide a extension api option to set the word-wrap state of a document upon opening.

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#136928] opened 2021-11-11 04:26 UTC
As an extension developer, I would like to have my extension open and show my user a document to edit with the word wrap 'already toggled' on. (Similar to having toggled word-wrap with [alt+z] right after having opened a file in an editor with focus on it)

Simply opening and displaying a file in an editor for the user is easy with vscode.workspace.openTextDocument( some_uri ) and / or vscode.window.showTextDocument( the_document, options )  But the options of showTextDocument **do not allow to provide a starting word-wrap state** - only viewColumn, preserveFocus, preview and selection range.

Since I know the alt-z 'toggle word wrap' command exists, (that's what I'm trying to prevent the user from having to do in those specific cases for my extension) I'm tempted to think it would be possible have the word-wrap state offered as an option when opening a document with the extension API, for the user to have it in an editor already toggled on (or off). 

_Use case: my extension displays some files to the user, sometimes it would be nice to show it with word wrap turned on, sometimes off. I know about specific filetype configurations which could set wrap states for specific file types, but my extension does so with abstract/arbitrary filetypes. (for some documentations files where wrapping is desired.)_

Sorry for my english (second language) & Thanks for reading my feature request! 

(edit: typo)

**Comment by jrieken** [comment] 2021-11-11 08:20
/duplicate of https://github.com/microsoft/vscode/issues/136927

**Closed** 2021-11-11 08:21 UTC
Labels: *duplicate
