### ISSUE TITLE
can vscode add Data Breakpoints protocol ?

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#47117] opened 2018-04-03 04:01 UTC
When I debug C program in visual studio, I like to set data breakpoint to monitor memory change. But I find this function is absent in vscode.

I explore the related issue in  [vscode-cpptools #1410](https://github.com/Microsoft/vscode-cpptools/issues/1410) and [vscode-debugadapter-node #38](https://github.com/Microsoft/vscode-debugadapter-node/issues/38). 

So I want to know is there a plan to add data breakpoint function?? I think many people will need it.

ps: 

> Input '-exec watch xx' in Debug Console can add data breakpoint like debugging in gdb. But this experience is actually bad.

**Comment by weinand** [comment] 2018-04-03 08:34
this is a duplicate of https://github.com/Microsoft/vscode-debugadapter-node/issues/38

**Closed by weinand** 2018-04-03 08:34 UTC
Labels: debug, feature-request
