### ISSUE TITLE
markdown preview in zoom-in mode does not expand to fill all the available space

### ISSUE THREAD

**Issue by rgl** [Microsoft/vscode#21828] opened 2017-03-02 20:25 UTC
At zoom-level 0:

![image](https://cloud.githubusercontent.com/assets/43356/23525331/042f6896-ff86-11e6-932d-075cf79a04c4.png)

At zoom-level 1 (press ctrl++):

![image](https://cloud.githubusercontent.com/assets/43356/23525374/2edca6bc-ff86-11e6-81b3-8695a01ae585.png)

As you can see the preview does not use all the available space.

**Comment by mjbvz** [comment] 2017-03-02 20:50
Thanks. This is a duplicate of #5745

**Closed by mjbvz** 2017-03-02 20:50 UTC
Labels: duplicate, webview
