### ISSUE TITLE
Settings: include file

### ISSUE THREAD

**Issue by Mr-Tin-25** [microsoft/vscode#133265] opened 2021-09-16 16:31 UTC
Hi,

right now it's possible to exclude file, they aren't visible at Explorer.
If I want to see only specific files, I have to exclude all file. The exclude file list will belong.
I would like to have an include setting. Only file that are list at this are visible at Explorer. E.g.:
If I like to see only C# files I will only see C# file and no other. Just bei adding "**/*.cs".
If I also like to see text file I can add "**/*.txt". 
With including I don't have to care about, what kind of files will be put into the project folder. I don't have to exclude them. Can focus on my work.

Thanks

**Comment by IllusionMH** [comment] 2021-09-16 17:09
/duplicate of #869

Whether it's negated exclude patterns or separate key.

**Closed** 2021-09-16 17:10 UTC
Labels: *duplicate
