### ISSUE TITLE
Can't install VScode v1.3 Source Code from Scratch.

### ISSUE THREAD

**Issue by Wernthaler** [Microsoft/vscode#9039] opened 2016-07-10 22:57 UTC
- VSCode Version: 1.3
- OS Version:  Fedora Workstation 4.6.3-300.fc24.x86_64

I have some trouble to install 'vscode' after cloning and installing the project from Github.
I use a fresh Fedora Workstation Installation (fc24.x86_64) virtualized on VMware.

Please see the attached screen dump:

![vscode_install_error](https://cloud.githubusercontent.com/assets/20271294/16716623/20d6d322-4702-11e6-9801-055925081bb1.png)

Steps to Reproduce:
1. Clone 'vscode' Branch 'release/1.3.0' to a local repository (git clone https://github.com/microsoft/vscode)
2. cd vscode
3. ./scripts/npm.sh install --arch=x64

Please help.

Thanks for your support.

**Comment by Tyriar** [comment] 2016-07-10 23:10
@Wernthaler the errors are from the option dependency and it says skipping afterwards, did you try run it after installing? What happens when you run:

```
./scripts/npm.sh install --arch=x64
npm run watch
# in new term
./scripts/code.sh
```

**Comment by Wernthaler** [comment] 2016-07-11 07:43
@Tyriar Thanks for helping me.

When I run the command `npm run watch`, I get some errors about missing files:

![npm_run_watch](https://cloud.githubusercontent.com/assets/20271294/16722763/1515f2ba-4749-11e6-9547-b2ce8034451a.png)

Nevertheless when I run `./scripts/code.sh` in a new term session, the application launches, but I get an error message and some info messages in that console:

![code sh](https://cloud.githubusercontent.com/assets/20271294/16723032/cb5ec2f8-474a-11e6-9b54-4af729b227ac.png)

How can I update/upgrade the deprecated marked modules when I run `./scripts/npm.sh install --arch=x64`

Again thanks for helping.

**Comment by Tyriar** [comment] 2016-07-11 17:57
Any ideas on why this would fail @joaomoreno? I only see an optional dep fail in the npm install output.

**Comment by joaomoreno** [comment] 2016-07-12 07:35
Duplicate of #7874 and npm/npm#12698. Install the dependencies with npm < 3.9.

**Closed by joaomoreno** 2016-07-12 07:35 UTC
Labels: linux
