### ISSUE TITLE
REGRESSION: IME disabled with code (>= 1.47) snap

### ISSUE THREAD

**Issue by 330k** [microsoft/vscode#104753] opened 2020-08-16 13:34 UTC
Issue Type: <b>Bug</b>

On Ubuntu 18.04 with snap, VSCode >= 1.47 cannot input any Japanese characters even when IME is enabled.
IME worked until 1.46.1, so formally I can "snap revert code --revision 35",  but snap registry deleted this version.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 4.15.0-111-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3518)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 2|
|Memory (System)|15.54GB (0.20GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.36.3
vscode-language-pack-ja|MS-|1.48.3

</details>

**Comment by jaydeedub** [comment] 2020-08-16 22:07
I have another issue (not yet submitted) that may be related, because my issue involves input, and it accurs starting with version 1.47.0-1594283939 on Debian Buster on Intel® Core™ i7-4770/

The issue is that when debugging a Python program which uses the input() method, execution hangs at the input() statement. as simple as:
```python
while True:
    x = input("Input something (q to quit): ")
    if x == 'q':
        break
    print(x)
```

Execution does not contnue past the input statement.  After I use the Code "Stop" button, the shell in the terminal complains:
bash: q: command not found
Indicating that he input is in a buffer, but it gets passed to the shell,

**Comment by rebornix** [comment] 2020-08-17 15:37
Can you verify if you are also seeing similar issues with deb packages downloaded directly from https://code.visualstudio.com/#alt-downloads ?

**Comment by denialmx** [comment] 2020-08-17 23:28
I can confirm this issue.
It broke all my inputs. I downloaded Windows version from URL provided above and still experience issues. It seems as if the input instead of saving it to a variable, it sends it back to the terminal.

Below is what it shows after stopping the debugger. I use remote SSH. Previous version worked fine.

daniel@linux1:/opt/netarsenal$ source /opt/netarsenal/venv/bin/activate
(venv) daniel@gpiptclinux1:/opt/netarsenal$ show version
The program 'show' can be found in the following packages:
 * mailutils-mh
 * nmh
Try: sudo apt install <selected package>
(venv) daniel@gpiptclinux1:/opt/netarsenal

**Comment by 330k** [comment] 2020-08-18 00:06
> Can you verify if you are also seeing similar issues with deb packages downloaded directly from https://code.visualstudio.com/#alt-downloads ?

IME works in deb package.

**Comment by rebornix** [comment] 2020-08-31 22:51
/duplicate of https://github.com/microsoft/vscode/issues/96041

**Closed by rebornix** 2020-08-31 22:51 UTC
Labels: needs more info
