### ISSUE TITLE
Auto-completing React Native tags

### ISSUE THREAD

**Issue by sercanov** [Microsoft/vscode#10935] opened 2016-08-25 07:41 UTC
- VSCode Version: 1.4.0
- OS Version: OS X Yosemite

I've already opened an issue in vscode-react-native repo but I think it's related to vscode itself.

Microsoft/vscode-react-native#247

When I need to insert a component or any tag, I have to write both opening and closing tags. Auto completion on these could be great to have.

Similar behavior is available on React with double TAB.

Example behavior on ; https://atom.io/packages/react

Thanks

**Comment by jrieken** [comment] 2016-08-25 10:42
The completion framework allows you to do that. @aeschli is this something the html-language should do? be configured to do?

**Comment by rod-stuchi** [comment] 2016-08-25 22:31
That would be great!
[Demo videos **atom-react**](https://orktes.github.io/atom-react/)

**Comment by lshaf** [comment] 2017-08-29 03:23
will be really helpful

**Comment by mjbvz** [comment] 2017-11-02 21:22
Closing as duplicate of #34307

**Closed by mjbvz** 2017-11-02 21:22 UTC
Labels: extension-candidate, feature-request
