### ISSUE TITLE
[INSIDERS] After 2020-10-09 upgrade this error happens when logging in using MS acct: "Writing login information to the keychain failed with error 'Error during CryptAcquireContext.'."

### ISSUE THREAD

**Issue by pmsjt** [microsoft/vscode#108424] opened 2020-10-09 21:19 UTC
Version: 1.51.0-insider (user setup)
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:54.647Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1.Star CODE-INSIDERS
2.Login with MS account

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2020-10-09 22:09
Thank you, closing as a duplicate of https://github.com/microsoft/vscode/issues/108362

**Closed by RMacfarlane** 2020-10-09 22:09 UTC
Labels: *duplicate
