### ISSUE TITLE
Settings TOC does not expand to full when the VS Code window is resized

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#143920] opened 2022-02-24 22:14 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.65.0-insider Commit: 3112460dc48ce7e557ea9feeaae04b912164b48b
- OS Version: macOS Big Sur 11.6.3

Steps to Reproduce:

1. Open the settings view, resize the VS Code window until the TOC disappears
2. Resize the window back to its original size, observe that the TOC did not re-expand fully:

https://user-images.githubusercontent.com/51720070/155616329-560a5a24-427a-4c94-ad6a-aef6081ff264.mp4

**Comment by rzhao271** [comment] 2022-02-24 23:13
Duplicate of https://github.com/microsoft/vscode/issues/143690

**Closed by rzhao271** 2022-02-24 23:13 UTC
