### ISSUE TITLE
Broken URL in bower tooltip

### ISSUE THREAD

**Issue by domoritz** [Microsoft/vscode#15415] opened 2016-11-13 01:09 UTC
- VSCode Version: 1.7.1
- OS Version: Mac OS 10.12

Steps to Reproduce:

1. Open a bower.json file
2. Hover over an entry to see the URL. You can see that vscode added a `\` in front of the `.`

<img width="350" alt="screen shot 2016-11-12 at 17 04 11" src="https://cloud.githubusercontent.com/assets/589034/20243032/93ea094c-a8fa-11e6-9bba-9f4e11ce7660.png">

**Comment by aeschli** [comment] 2016-11-14 09:07
duplicate of #14968

**Closed by aeschli** 2016-11-14 09:07 UTC
