### ISSUE TITLE
Custom Editor Tabs Are Buggy When The Text Editor Is Also Opened

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#112006] opened 2020-12-07 10:02 UTC
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a file with a custom editor (and don't close it)
2. Now, open the file again with the default text editor
3. Click on the tabs of the editors to switch between them

# Actual Result
It always jumps to the custom editor tab.

# Expected Result
The default text tab should be shown if clicked on its tab.

![52d31b0e-d5ac-4ec9-a5af-e156c57cf6eb](https://user-images.githubusercontent.com/2931520/101337138-9d87fd00-387b-11eb-81a8-7055e91fa8ef.gif)

**Comment by mjbvz** [comment] 2020-12-18 00:08
Duplicate of #111474

**Closed by mjbvz** 2020-12-18 00:08 UTC
