### ISSUE TITLE
vscode reports reachable "unreachable code" after an IIFE

### ISSUE THREAD

**Issue by ljharb** [microsoft/vscode#99726] opened 2020-06-10 05:37 UTC
- VSCode Version: 1.45.1
- OS Version: Mac OS 10.14.5

Steps to Reproduce:

add this code:
```js
var noThrowOnStrictViolation = (function () {
	try {
		delete [].length;
		return true;
	} catch (e) {
		return false;
	}
}());
```

before a bunch of other code. see how vscode grays out and incorrectly marks "ts(7027)" on the following code.

If it's changed to this code:
```js
var noThrowOnStrictViolation = (function () {
	try {
		delete [].length;
		return true;
	} catch (e) {
	}
	return false;
}());
```
the bug does not occur.

**Comment by mjbvz** [comment] 2020-06-10 06:54
Duplicate of https://github.com/microsoft/TypeScript/issues/36828

Already fixed in VS Code insiders

**Closed by mjbvz** 2020-06-10 06:54 UTC

**Comment by ljharb** [comment] 2020-06-10 06:59
Thanks, any idea when it will be released?
