### ISSUE TITLE
Extension host not starting in new windows open in vs code.

### ISSUE THREAD

**Issue by jhonnatangomes** [microsoft/vscode#164298] opened 2022-10-21 21:19 UTC
Type: <b>Bug</b>

When opening a new window in vs code from the terminal, it launches with the extension host disabled. The logs under developer tools show this: 
```
Error received from starting extension host (kind: LocalProcess)
```
```
Error: listen EADDRINUSE: address already in use /var/folders/q3/7k44dy2j0mg2mbg1n68z697c0000gn/T/com.apple.WorkflowKit.BackgroundShortcutRunner/vscode-ipc-aa0e8d86-503e-4810-8f7e-d05e6a9e4468.sock
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:563:12)
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at nativeLocalProcessExtensionHost.ts:57:20
    at new Promise (<anonymous>)
    at h.prepare (nativeLocalProcessExtensionHost.ts:52:10)
    at async Promise.all (index 1)
    at async s._startWithCommunication (localProcessExtensionHost.ts:208:92)
```

I noticed this issue does not occur when I open another window from vs code's builtin terminal. The problem persists even after reloading the newly opened window. Sometimes it remains even after I close all windows and reopen one of them, forcing me to quit vs code process that remains in the background in MacOs in order for everything to start working again. The extension host problem does not affect windows that were previously working, it only happens in new windows opened from this point.  

I tried launching new windows with all extensions disabled or restart the extension host, but the problem persists.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.35GB free)|
|Process Argv|. --crash-reporter-id 4235772d-4da7-4765-8413-5a631cc7e99a|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|2.2.6
vscode-styled-components|die|0.1.33
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
go|gol|0.35.2
todo-tree|Gru|0.0.219
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.21.0
vscode-thunder-client|ran|1.20.1
ruby|reb|0.28.1
scheme|reb|0.0.2
java|red|1.11.0
LiveServer|rit|5.7.9
vscode-nand2tetris-hdl|rob|0.1.1
markdown-preview-enhanced|shd|0.6.3
vscode-status-bar-format-toggle|tom|3.1.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
vscode-wakatime|Wak|20.0.0
quokka-vscode|Wal|1.0.508
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0
fig|wit|0.0.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by alexdima** [comment] 2022-10-24 14:13
Duplicate of https://github.com/microsoft/vscode/issues/139570

**Closed by alexdima** 2022-10-24 14:13 UTC
