### ISSUE TITLE
Quick fix menu does not work

### ISSUE THREAD

**Issue by piaorlm** [microsoft/vscode#77169] opened 2019-07-11 05:02 UTC
Issue Type: <b>Bug</b>

1. When there is an issue in the code, such as  can not find a Java class, then hoverring on the issue area, the quick fix popup is shown.
2. Clicking the quick fix link, there will be an popup menu containing all the suggestions, such as "import ****", "create ***" and so on.
3. when clicking any of them, nothing happens.

Notes: 
1. This issue only happens when the quick fix menu is invoked by clicking with mouse. If use Ctrl + 1 and clicking the menu item could work well. 
2. This could work find in previous VS code.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.84GB (10.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-eclipse-keybindings|alp|0.10.0
vscode-lombok|Gab|0.9.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
omt|OPP|1.1.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.8.1
vscode-manifest-yaml|Piv|1.8.1
vscode-spring-boot|Piv|1.8.1
vscode-jsp|pth|0.0.2
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5

</details>

**Comment by mjbvz** [comment] 2019-07-11 17:53
Duplicate of #77018

**Closed by mjbvz** 2019-07-11 17:53 UTC
Labels: new release
