### ISSUE TITLE
Markdown preview no longer shows images with root relative path

### ISSUE THREAD

**Issue by vsudakov** [microsoft/vscode#110812] opened 2020-11-17 15:21 UTC
- VSCode Version: 1.51.1
- OS Version: on both Fedora 32 and Linux Mint 20

Steps to Reproduce:

1. git clone git@github.com:vsudakov/issues_vscode_1_40_0_markdownPreviewRootRelativeImg.git
2. cd issues_vscode_1_40_0_markdownPreviewRootRelativeImg
3. code .
4. Image doesn't display in readme.md:

![Screenshot from 2020-11-17 17-50-50](https://user-images.githubusercontent.com/6968702/99406651-3243ae80-28ff-11eb-91ec-7c3a27010bc6.png)

Does this issue occur when all extensions are disabled?: Yes

This issue had already occurred in past: https://github.com/microsoft/vscode/issues/84728
In the latest insiders vs-code build - it's not fixed as well.

**Comment by jeanp413** [comment] 2021-01-06 16:16
@mjbvz I took a look at this and found that the issue is that the resource uri is invalid, is missing `/file///` before `/home/jeanpierre/...`

I was looking how to fix it but I can't find the place where the `img.src` gets mapped to a `vscode-webview-resource`

```
<img src="/home/jeanpierre/Desktop/issues_vscode_1_40_0_markdownPreviewRootRelativeImg/assets/2019-11-13_16_36_37.png" alt="" class="" id="image-hash-904852482">
```
```
vscode-webview-resource://74f85878-6ad4-475b-bf60-b0c1370666e2/home/jeanpierre/Desktop/issues_vscode_1_40_0_markdownPreviewRootRelativeImg/assets/2019-11-13_16_36_37.png
```

can you give some code pointers?

**Comment by bartholomew-gander** [comment] 2021-01-12 22:12
@jeanp413  here is my quick and dirty fix for this issue:
https://github.com/bartholomew-gander/vscode/commit/0214f9137d69074eba3549a679b3ffbf2c715e3f

**Comment by mjbvz** [comment] 2021-01-13 07:06
@jeanp413 Start by looking in the markdown link normalizer

https://github.com/microsoft/vscode/blob/f732547a3d548a640e5120eca4bfb59cbedc3c48/extensions/markdown-language-features/src/markdownEngine.ts#L229

I believe this is passed the raw image links and tries to transform them into url that VS Code can render in the preview

**Comment by jeanp413** [comment] 2021-01-19 04:44
Thanks @mjbvz and @bartholomew-gander after spending some more time looking at this I think I found a proper fix for it

**Closed** 2021-01-19 22:21 UTC
Labels: help wanted, markdown
