### ISSUE TITLE
JS Formatter removes space in init() function

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15827] opened 2016-11-21 18:15 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (4ac353bfb3c3598338dad6ce8e162c67650cf2cc, 2016-11-21T07:05:04.218Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.3|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.1.15|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.6.0|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|7.6.0|
|HTMLHint|mkaufman|0.0.3|
|vscode-stylefmt|mrmlnc|2.1.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|stylelint|shinnn|0.19.0|
|theme-tesla|smlombardi|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

Code snippet:
```
      function init () {
        _this.billingCurrencyType = _this.currencyTypes[0];
        _this.pricingCurrencyType = _this.currencyTypes[0];
      }
```
run "format code"

you get:
```
      function init() {
        _this.billingCurrencyType = _this.currencyTypes[0];
        _this.pricingCurrencyType = _this.currencyTypes[0];
      }
```
and eslint flags the missing space between `init` and the `()`

**Comment by mjbvz** [comment] 2016-11-22 19:03
This looks like a duplicate of #15386, which itself is now being tracked in the TypeScript project: https://github.com/Microsoft/TypeScript/issues/12234 

Once this feature is implemented on the Typescript side, we should be able to pick it up in VSCode without much work. Thanks.

**Closed by mjbvz** 2016-11-22 19:03 UTC
Labels: duplicate, javascript
