### ISSUE TITLE
Toggle Minimap to View menu

### ISSUE THREAD

**Issue by mikkoh85** [Microsoft/vscode#28341] opened 2017-06-09 12:50 UTC
Hi! Do you have plans on adding `Toggle Minimap` on View menu and Command Palette? Or am I missing something? I can't find any way to take the minimap next to scrollbar off, or any way to resize it. That would be great when having limited desktop space on laptops for example.

**Comment by dolphy01** [comment] 2017-06-09 15:27
it looks like this can be changed via settings:
`  "editor.minimap.enabled": true,`

**Comment by gregvanl** [comment] 2017-06-09 20:40
Consider an editor context menu item to hide/show the minimap.
It could also just be a content menu on the visible minimap itself.

**Comment by alexandrudima** [comment] 2017-06-13 09:26
Duplicate of #22423

**Closed by alexandrudima** 2017-06-13 09:26 UTC
Labels: editor-minimap
