### ISSUE TITLE
Settings Search-Exclude no longer works on Windows

### ISSUE THREAD

**Issue by linvi** [Microsoft/vscode#32627] opened 2017-08-16 09:48 UTC
Hello, I would like to report a bug that occurred when I updated my Windows VSCode to the July 2017 update.

- VSCode Version: 1.15.0 (x86)
- OS Version: Windows 10
- Reproduces without extensions: Yes

Steps to Reproduce:

1. Create a folder named testme
2. Create a file name hello.js with 'hello world' as content
3. Create a workspace settings and set it to:

``` json
{
    "search.exclude": {
        "**/testme": true
    }
}
```

4. Search for 'hello' 
5. The result `hello.js` is displayed even though it should not

Cheers

**Comment by roblourens** [comment] 2017-08-16 15:30
Is hello.js open? If so, it will still get searched, due to https://github.com/Microsoft/vscode/issues/31819

**Comment by danbrakeley** [comment] 2017-08-16 17:08
I'm seeing this as well. Specifically, I've had a `**/output` sitting in the "files to exclude" field for weeks now, and after upgrading, suddenly my search results include results like "output/browser-stats.json", "output\build\server.js", etc.

This is on Windows 10 Pro running VS Code x64 version 1.15.0.
This does reproduce after disabling all extensions.

**Comment by roblourens** [comment] 2017-08-16 17:24
That one is https://github.com/Microsoft/vscode/issues/32325, fixed in Insiders and the incoming 1.15.1. As a workaround, the `**` is redundant, `output` will exclude all `output` folders.

**Comment by linvi** [comment] 2017-08-16 22:38
@roblourens 

> Is hello.js open? 

No

> As a workaround, the ** is redundant, output will exclude all output folders.

I already tried this and various other matching patterns, all failed.

**Comment by roblourens** [comment] 2017-11-23 03:01
Lots has changed here. Still an issue? If so, please provide the text from the search output pane.

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Closed by roblourens** 2017-11-23 03:01 UTC
Labels: needs more info, search
