### ISSUE TITLE
documentationLabel does not accept carriage return

### ISSUE THREAD

**Issue by jefflevinson** [Microsoft/vscode#8005] opened 2016-06-22 14:36 UTC
- VSCode Version: Latest
- OS Version: Windows 10

per Erich

this suggestSupport snippet does not respect any character I could possibly use for the section [should be carriage return here]. I've tried various combinations of html tags and of the construction of the label itself with no luck.

type: 'operator',
label: 'ge',
codeSnippet: 'ge',
documentationLabel: "Greater Than or Equal To [should be a carriage return here] StoryPoints ge 8"

**Comment by joaomoreno** [comment] 2016-07-06 10:39
Duplicate of #1920

**Closed by joaomoreno** 2016-07-06 10:39 UTC
Labels: bug, ux
