### ISSUE TITLE
Right click file highlight suggestion

### ISSUE THREAD

**Issue by Adrianilloo** [microsoft/vscode#108792] opened 2020-10-16 11:25 UTC
Issue Type: <b>Feature Request</b>

Hi,

One of the caveats I noticed already time ago and I've just thought to have enhanced is that when you right click on a file on the left tree explorer, its file name is not highlighted, not only causing confusion on whether an operation like renaming it would affect that file or the previous selected one (you can only left-click to select/highlight files), but also simply put making it less visually appealing. Althought the operations finally affect the right-click selected file.

Right clicking on a file on left tree should immediately highlight it just as left clicking. Note: highlight seems to be applied after pressing ESC key, though.

EDIT: I could rather have referred to the formal "opening the contextual menu" but you get the point - the habit ;)

Thanks.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by usernamehw** [comment] 2020-10-16 12:41
Duplicate of #70966 ?

**Comment by Adrianilloo** [comment] 2020-10-16 16:35
> Duplicate of #70966 ?

Issue #83643 shows the situation more clearly

**Closed** 2020-10-22 10:49 UTC
Labels: *duplicate
