### ISSUE TITLE
Auto closing tags - Bug with undoing changes - deletes the history of changes!

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#125276] opened 2021-06-02 13:00 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.10.7-arch1-1

Steps to Reproduce:

1. enable `html.autoClosingTags` option (It is the default in vscode)
2. open some html file
3. follow the gif actions:
![auto closing tags bug](https://user-images.githubusercontent.com/16800535/120482252-3920a300-c3b1-11eb-90dd-8a88202b6fe2.gif)
Just typing `<span>` works just as bad as gif `ctrl + v`.
4. Undo gets stuck - I can't undo or redo changes
It deleted the history of changes!

This is very painful because, for example, I check the previous version of something (undo), then I want to go back to the newest (redo) and they can't, my work has been wasted!

I checked that auto closing Brackets (`editor.autoClosingBrackets`) does not have this bug.

There was this problem in the Template String Converter extension too, but it was fixed:
https://github.com/meganrogge/template-string-converter/issues/47

**Comment by VirkSaab** [comment] 2021-06-07 15:54
I have the same issue. The same issue occurs when I display the output of a variable (by simply typing the variable name at the last line in the cell) and edit & run the markdown cell.

**Comment by aeschli** [comment] 2021-09-08 09:40
underlying issue is https://github.com/microsoft/vscode/issues/52777. Closing as dup

**Comment by aeschli** [comment] 2021-09-16 16:05
duplicate of #34484

**Closed by aeschli** 2021-09-16 16:05 UTC
