### ISSUE TITLE
Pressing the "Right arrow" -key does not move the cursor in code editor

### ISSUE THREAD

**Issue by markusylisiurunen** [microsoft/vscode#105578] opened 2020-08-28 10:59 UTC
Issue Type: <b>Bug</b>

I updated to the latest Insider build and the "Right arrow" -key stopped working in the code editor. It seems to happen in every file I try to open and is not file type specific.

1. Open any file in code editor
2. Try pressing the "Right arrow" -key

VS Code version: Code - Insiders 1.49.0-insider (bd2a40195f1c904a0cc0dd161371c0e3e3957052, 2020-08-28T09:16:08.002Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.62GB free)|
|Process Argv|--crash-reporter-id bd7811b0-233c-4cc0-bb92-c80fb9a73382|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by SimonSiefke** [comment] 2020-08-28 11:21
related: https://github.com/microsoft/vscode/issues/105576

**Comment by 8enSmith** [comment] 2020-08-28 11:26
I too get this behaviour!

**Comment by SimonSiefke** [comment] 2020-08-28 11:35
I fixed it by
- Click on Settings gear
- Open Keyboard Shortcuts
- Search for "RightArrow"
- Right Click on entry that says "Notebook: UnFold Cell" & remove that keybinding

**Comment by dillonparfitt** [comment] 2020-08-28 11:37
@SimonSiefke thank you!

**Comment by jrieken** [comment] 2020-08-28 11:49
/duplicate of https://github.com/microsoft/vscode/issues/105576

new insiders in on its way, sorry for the hassle

**Comment by kotot** [comment] 2020-08-28 11:51
me too！

**Closed** 2020-08-28 11:50 UTC
Labels: *duplicate
