### ISSUE TITLE
Portuguese (Brazil) Keyboard Layout: IntlRo appears as 'unknown' key on Keyboard Shortcuts

### ISSUE THREAD

**Issue by allanesquina** [Microsoft/vscode#24147] opened 2017-04-06 22:04 UTC
I'm not able to toggle line comments in js files, also, it's not possible to bind the shortcut again, I'm getting `unknown` when pressing key `/` in keybinding mode.

#24047 @alexandrudima 

- VSCode Version:  1.11.1
- OS Version: Ubuntu 16.04 LTS
- No extensions 
- Keyboard layout: Portuguese (Brazil) https://en.wikipedia.org/wiki/File:KB_Portuguese_Brazil.svg
- Unknown key: 
```
{
    key: '/',
    keyCode: 47,
    charCode: 47,
    code: 'IntlRo'
}
```
Steps to Reproduce:

1. Open Keyboard Shortcuts 
2. Add a keybinding 
3. Press the key

![screenshot from 2017-04-06 18-57-18](https://cloud.githubusercontent.com/assets/3584636/24777310/2e829e7a-1afb-11e7-9817-1c1463035a34.png)

**Comment by alexandrudima** [comment] 2017-04-07 08:19
@allanesquina Is it possible this is a duplicate of #24107

i.e. https://bugs.chromium.org/p/chromium/issues/detail?id=709242 -- the scan codes we are receiving appear to sometimes be incorrect

To go back to `keyCode` based dispatching, please use the following setting `"keyboard.dispatch": "keyCode"`.  Restart VS Code.

I will try to reproduce this on a Linux machine as soon as I'm back in the office and will ping for more information if I cannot reproduce.

**Comment by allanesquina** [comment] 2017-04-07 14:05
@alexandrudima Seems to be a related issue but more keys are failing in this case. 

Backing to `keyCode` the problem was solved for me, maybe keeping this config as default could help the  users with the same problem at least for while. 

I'm glad to help you with more information if you need.
Thanks for the quick reply :+1:

**Comment by melloc01** [comment] 2017-04-07 14:34
This bug was introduced by this last update.

changing the setting to `keyCode` solves it.

**Comment by phouverneyuff** [comment] 2017-04-09 02:36
Same here with Fedora 25. Changing to keyCode solves too

**Comment by alexandrudima** [comment] 2017-04-10 09:04
Lots of folks where scan codes are incorrect reported using some form of remote desktoping software.

Are you using a linux installation on real hardware and typing on a keyboard attached to it or are you using some form of remote desktoping ?

**Comment by melloc01** [comment] 2017-04-10 12:39
@alexandrudima real Linux, with real keyboard and real mouse very physical

More details on linux:
![image](https://cloud.githubusercontent.com/assets/4994258/24862029/5bcf6cb8-1dd1-11e7-9bb3-29b49df29f3c.png)

**Comment by phouverneyuff** [comment] 2017-04-10 12:57
@alexandrudima I'm using all real, all physical

**Comment by allanesquina** [comment] 2017-04-10 16:24
@alexandrudima real Linux, all physical as well.

**Comment by MarcosEllys** [comment] 2017-04-10 18:08
Hi,

I'm facing the same problem when commenting a code, the Ctrl + / shortcut does not work.

My keyboard is Brazilian standard ABNT2

**Closed** 2017-04-11 12:38 UTC
Labels: bug, keybindings, keyboard-layout, linux

**Comment by andreas-andrade** [comment] 2017-04-27 14:54
Thanks to @allanesquina and @alexandrudima for the help. Change "keyboard.dispatch" to "keyCode" resolve my problem.

**Comment by alexandrudima** [comment] 2017-04-27 18:34
Since this is very hard for us to verify in our team, as it appears one needs to buy a Brazilian keyboard to get 104 keys (https://w3c.github.io/uievents-code/#keyboard-104 ) we would very much appreciate if you could try to verify that the bug is fixed in the Insiders Channel -- https://code.visualstudio.com/insiders.

Thank you!

**Comment by delmarwichnieski** [comment] 2017-05-04 22:57
I have the same problem with Toggle Line Comment when trying to switch from Ctrl +; To Ctrl + / getting ctrl + unknown

Windows 10 Pro
Versão 1607
Build SO 14393.1066
x64

Visual Studio Code
Version 1.12.0
Date 2017-05-04T16:18:34:633Z
Shell 1.6.6
renderer 56.02924.87
Node 7.4.0

Keyboard Pt-Br
ABNT2

https://jsfiddle.net/v1gz5c5m/1/
	/ on Firefox 54.0b4 (64-bit)
		keydown --- code: IntlRo, keyCode: 191, key: /
	/ on Chrome Versão 58.0.3029.96 (64-bit)
		keydown --- code: IntlRo, keyCode: 193, key: /
	/on Edge Microsoft Edge 38.14393.1066.0
		keydown --- code: undefined, keyCode: 193, key: /

/ on Visual Studio hint as image
![vscode_togglelinecomment](https://cloud.githubusercontent.com/assets/5343722/25728184/cb09d01a-3103-11e7-9cbb-3da2a156de03.png)
