### ISSUE TITLE
Visual Studio-like Synchronization Across Devices in VSCode

### ISSUE THREAD

**Issue by Chiramisu** [Microsoft/vscode#52739] opened 2018-06-24 00:24 UTC
I know this is been asked before, but it's been a couple years and I would very much like to revisit this request; particularly because I don't believe the need has been adequately represented. Namely, the ability to sign-in with a Microsoft or GitHub account / token and have our VSCode configurations (especially Extensions, User Settings, and Themes) synced between environments. _I care not how it is implemented on the backend, as long as it works._ :)

The extensibility of VSCode via Extensions is something that was sorely needed in a code-first text-based editor for a long time, but this kind of functionality should be native. Even extensions such as [Settings Sync](https://github.com/shanalikhan/code-settings-sync) fall short and do not implement proper merging, but instead overwrite configurations that should instead be merged. The popularity of this extension showcases how much of a demand there is for this feature, as does the many requests for it over the last few years.

**If denied again** and this request gets Closed, I would very much like a reasonable explanation as to why.

The Visual Studio dev team obviously valued this highly enough to build it directly into Visual Studio as early as 2013 and have been improving it ever since. I would like this same sign-in functionality to also be ported to VSCode, with the additional option of authenticating with our GitHub account / tokens.

Please reconsider native support for Syncing in some future build.

Additional reading:

- [The Story of Synchronized Settings](https://blogs.msdn.microsoft.com/visualstudio/2013/07/03/the-story-of-synchronized-settings/) by Radhika Tadinada, Program Manager
- [Welcome. Sign in to Visual Studio](https://blogs.msdn.microsoft.com/visualstudio/2013/06/28/welcome-sign-in-to-visual-studio/) by Anthony Cangialosi, Lead Senior Program Manager
- [What's New in Visual Studio 2015](https://msdn.microsoft.com/en-us/library/bb386063.aspx#Anchor_1)
- [Signing in to Visual Studio](https://msdn.microsoft.com/en-us/library/dn457348.aspx)

**Comment by chrmarti** [comment] 2018-06-25 12:39
Thanks for the detailed request. We are currently tracking this as #2743. Make sure you add your 👍 on that issue's description, that is something we look at when deciding which feature requests to address next.

I'm going to close this issue as a duplicate of the mentioned issue to keep our issues tidied up.

**Closed by chrmarti** 2018-06-25 12:39 UTC

**Comment by Chiramisu** [comment] 2018-06-26 01:44
@chrmarti Thank you sir. I've already done that as well. The reason I didn't consider it a duplicate is because that thread is arguing for better Extension support for this functionality while I'm arguing that it should rather be built-in. 😉

**Comment by kilasuit** [comment] 2018-07-23 09:41
I 100% agree with @Chiramisu on this that this should be native to VSCode and not implemented as an externally developed extension that is limited in functionality.

**Comment by Chiramisu** [comment] 2018-07-23 17:13
@kilasuit Thanks! If you would kindly add your support also to issue #2743 referenced above that would be great. I have made comments there as well.
