### ISSUE TITLE
Markdown Extension: Contribute preview action to editor title area

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#7064] opened 2016-05-31 15:33 UTC
From #6106:

we currently do not have support to contribute actions to the context menu of the explorer or to the editor title area, but we have actions there to open a preview from a markdown file in both places and we also have an action to jump back to the source from a markdown preview

**Comment by jrieken** [comment] 2016-05-31 15:44
let's treat this as a duplicate of #3192

**Closed** 2016-05-31 15:44 UTC
Labels: api, duplicate, markdown

**Comment by kieferrm** [comment] 2016-05-31 15:56
@jrieken: Why do you want to treat the editor title are the same as the context menu?  It seems to me that a context menu entry is added to context that the extension does not necessarily own (such as the explorer). The editor title area could be considered "private" to the editor (with some common extensions the workbench provides per default.). So, the API implication/restrictions around the two seem quite different.

<img width="560" alt="screen shot 2016-05-31 at 8 52 11 am" src="https://cloud.githubusercontent.com/assets/4674940/15681314/8820b0ee-270d-11e6-8cde-f52605ad265c.png">

**Comment by jrieken** [comment] 2016-06-01 07:10
#3192 evolved into a general menu/context menu issue. The current feeling is that we will only allow editor title menu. If have updated the title of the issue accordingly
