### ISSUE TITLE
Integrated terminal renders fonts incorrectly since 1.17.1

### ISSUE THREAD

**Issue by xpl** [Microsoft/vscode#36160] opened 2017-10-12 18:47 UTC
- VSCode Version: 1.17.1
- OS Version: MacOS Sierra

"Monaco" font on my MacOS now looks like this in the integrated terminal (with `"terminal.integrated.fontFamily": "Monaco"`)

<img width="577" alt="screen shot 2017-10-12 at 21 45 24" src="https://user-images.githubusercontent.com/1707/31513325-b05efdaa-af96-11e7-88e8-526f07d79228.png">

This is how it looks in the Terminal.app (i.e. how it should look):

<img width="575" alt="screen shot 2017-10-12 at 21 44 23" src="https://user-images.githubusercontent.com/1707/31513271-8b64b314-af96-11e7-9452-5c05e3703319.png">

Steps to Reproduce:

1. Set `"terminal.integrated.fontFamily": "Monaco"` in the Settings
2. Open Integrated Terminal, compare rendering to Terminal.app (with the same font settings chosen)

Reproduces without extensions: Yes

**Comment by alohaninja** [comment] 2017-10-12 22:15
just saw this - opened a similar issue here: https://github.com/Microsoft/vscode/issues/36172

**Comment by svictoreq** [comment] 2017-10-13 17:42
I have the same problem, but in the Insiders version, the font rendering is better. For example, here's the stable version: 
![image](https://user-images.githubusercontent.com/29575744/31558721-15ede1b0-b01c-11e7-9d88-10a54542b67a.png)

And here's the Insiders version:
![image](https://user-images.githubusercontent.com/29575744/31558764-3d13276e-b01c-11e7-9c57-feba5031dbef.png)

The font used is Fira Code.

**Comment by migueldemoura** [comment] 2017-10-16 08:36
Can reproduce this on Ubuntu as well, having the exact same issue since 1.17.1

**Comment by emelent** [comment] 2017-10-16 14:24
Yep, having the same here on macOS(Sierra)
![screen shot 2017-10-16 at 4 23 06 pm](https://user-images.githubusercontent.com/16001218/31616951-60cb8e48-b28e-11e7-8845-ee4f37ac03e9.png)

**Comment by Tyriar** [comment] 2017-10-17 23:33
Duplicate https://github.com/Microsoft/vscode/issues/35991

Should be fixed in 1.17.2 that released today.

**Closed by Tyriar** 2017-10-17 23:33 UTC
Labels: integrated-terminal
