### ISSUE TITLE
中文出现乱码了

### ISSUE THREAD

**Issue by lxp521125** [Microsoft/vscode#7868] opened 2016-06-19 08:47 UTC
- VSCode Version:1.2.1
- OS Version: win7 x64

命令行 不能正常显示中文

**Comment by xiaopai** [comment] 2016-06-19 15:29
VSCode Version 1.2.1
OS Version OSX 10.10.5

In terminal  the Chinese characters were garbled

**Comment by bingzheyuan** [comment] 2016-06-20 07:32
This should be the same with #7036.

**Comment by Tyriar** [comment] 2016-06-21 17:58
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-21 17:58 UTC
Labels: bug, integrated-terminal
