### ISSUE TITLE
vscode is slow when the project has 100+ .ts files

### ISSUE THREAD

**Issue by sanmmm** [microsoft/vscode#130806] opened 2021-08-14 05:38 UTC
Issue Type: <b>Bug</b>

It takes 2 seconds from modifying the file to getting the sematic diagnosis response。

```
Info 741  
[13:29:33.280] request:
    {"seq":40,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"d:/code/work/graphql/platform/backend/resolvers/researcher/recruit/recruit.ts","textChanges":[{"newText":"// ","start":{"line":157,"offset":9},"end":{"line":157,"offset":9}}]}],"closedFiles":[],"openFiles":[]}}
Perf 742  [13:29:33.281] 40::updateOpen: elapsed time (in milliseconds) 0.5790
Info 743  [13:29:33.281] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":40,"success":true,"body":true}
Info 744  [13:29:33.388] request:
    {"seq":41,"type":"request","command":"geterr","arguments":{"delay":0,"files":["d:/code/work/graphql/platform/backend/resolvers/researcher/recruit/recruit.ts"]}}
Perf 745  [13:29:33.388] 41::geterr: async elapsed time (in milliseconds) 0.2618
Info 746  [13:29:33.404] Starting updateGraphWorker: Project: d:/code/work/graphql/platform/backend/tsconfig.json
Info 747  [13:29:33.454] Finishing updateGraphWorker: Project: d:/code/work/graphql/platform/backend/tsconfig.json Version: 6 structureChanged: false structureIsReused:: Completely Elapsed: 50.40809999965131ms
Info 748  [13:29:33.454] Different program with same set of files
Info 749  [13:29:33.455] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"d:/code/work/graphql/platform/backend/resolvers/researcher/recruit/recruit.ts","diagnostics":[]}}
Info 750  [13:29:35.426] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"d:/code/work/graphql/platform/backend/resolvers/researcher/recruit/recruit.ts","diagnostics":[{"start":{"line":159,"offset":22},"end":{"line":159,"offset":31},"text":"找不到名称“recruitId”。你是否指的是“Recruit”?","code":2552,"category":"error"},{"start":{"line":161,"offset":17},"end":{"line":161,"offset":19},"text":"找不到名称“pn”。","code":2304,"category":"error"},{"start":{"line":161,"offset":22},"end":{"line":161,"offset":27},"text":"找不到名称“limit”。","code":2304,"category":"error"},{"start":{"line":161,"offset":35},"end":{"line":161,"offset":40},"text":"找不到名称“limit”。","code":2304,"category":"error"}]}}
Info 751  [13:29:35.430] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"d:/code/work/graphql/platform/backend/resolvers/researcher/recruit/recruit.ts","diagnostics":[{"start":{"line":154,"offset":17},"end":{"line":154,"offset":21},"text":"已声明“args”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":155,"offset":16},"end":{"line":155,"offset":23},"text":"已声明“context”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":167,"offset":16},"end":{"line":167,"offset":23},"text":"已声明“context”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":179,"offset":16},"end":{"line":179,"offset":23},"text":"已声明“context”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":189,"offset":16},"end":{"line":189,"offset":23},"text":"已声明“context”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":203,"offset":61},"end":{"line":203,"offset":70},"text":"已声明“recruitId”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":205,"offset":16},"end":{"line":205,"offset":23},"text":"已声明“context”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true},{"start":{"line":247,"offset":61},"end":{"line":247,"offset":70},"text":"已声明“recruitId”，但从未读取其值。","code":6133,"category":"suggestion","reportsUnnecessary":true}]}}
Info 752  [13:29:35.430] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":41}}
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.47GB free)|
|Process Argv|--crash-reporter-id baaa8c5f-d9c5-4450-ba33-1cf2a08daff6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.2.3
gitlens|eam|11.6.0
auto-close-tag|for|0.5.12
vscode-graphql|Gra|0.3.16
path-autocomplete|ion|1.17.1
vscode-language-pack-zh-hans|MS-|1.59.3
vscode-typescript-next|ms-|4.5.20210813
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-08-14 06:51
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by sanmmm** [comment] 2021-08-14 11:08
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

I tried to disable all extensions, but the problem still exists

**Comment by mjbvz** [comment] 2021-08-16 21:41
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment] 2021-08-23 21:03
Closing as needs more info

**Closed by mjbvz** 2021-08-23 21:03 UTC
Labels: needs more info
