### ISSUE TITLE
Minimap display problem

### ISSUE THREAD

**Issue by dy55** [microsoft/vscode#85902] opened 2019-12-02 03:00 UTC
Issue Type: <b>Bug</b>

1. Create or open a file.

2. Type in some non-English characters (such as Chinese or Japanese).

3. Use *Consolas* as the primary font in font family.

4. Turn on the minimap and scale it to level 3 to make it clear to see the characters in it.

Then it will show that all non-English characters are not able to be displayed correctly. I guess it is the problem of the switch between fonts in the minimap.

---

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
docs-yaml|doc|0.2.4
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.3
vscode-firefox-debug|fir|2.5.3
vscode-pull-request-github|Git|0.13.0
minify|Hoo|0.4.3
jquery-snippets|Hri|1.0.0
rest-client|hum|0.23.0
svg|joc|1.0.5
vscode-peacock|joh|3.2.0
minifyall|jos|1.7.2
Angular-BeastCode|Mik|8.1.2
vscode-language-pack-ja|MS-|1.40.2
vscode-language-pack-zh-hans|MS-|1.40.2
vscode-edge-devtools|ms-|1.0.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.11.50794
vscode-ai|ms-|0.6.7
remote-wsl|ms-|0.40.3
azure-account|ms-|0.8.7
cpptools|ms-|0.26.2-insiders
csharp|ms-|1.21.8
Go|ms-|0.11.9
powershell|ms-|2019.11.0
typescript-javascript-grammar|ms-|0.0.53
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1293
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.2
subtitles-editor|pep|1.0.4
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.13.0
vscode-manifest-yaml|Piv|1.13.0
vscode-spring-boot|Piv|1.13.0
ruby|reb|0.26.0
java|red|0.53.1
vscode-xml|red|0.9.1
vscode-yaml|red|0.6.1
svg-snippets|sid|1.0.1
js-jsx-snippets|sky|10.0.0
unity-debug|Uni|2.7.2
usql-vscode-ext|usq|0.2.15
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-ruby|win|0.26.0

</details>

**Comment by alexandrudima** [comment] 2019-12-02 20:13
Duplicate of #84226

**Closed by alexandrudima** 2019-12-02 20:13 UTC
