### ISSUE TITLE
"Install Extensions" does not cache list

### ISSUE THREAD

**Issue by jwulf** [Microsoft/vscode#923] opened 2015-12-02 13:25 UTC
Each time I do `Cmd-Shift-P` and `Install Extensions` it takes ages for the list of extensions to come up. Like literally a minute or more. 

And it doesn't seem to cache the result. It's like it has to download them each time, even if it's only a second or two after I last pulled it up.

Frustrating - like using yum in Fedora used to be. 

apt-get in Ubuntu would cache results and was always more perfomant and responsive, with a slight cost in synchronisation with the latest available packages. 

It would work for me if it downloaded the latest package list when requested - and continued to download it even when it loses focus and closes. And then uses that cached list until the program is restarted, or does the same background load if it is opened again after ten minutes. 

That way I have a delay the first time I open it, but I can keep working. At the moment I have to literally stop working _on_anything_ and wait for the list to load.

**Comment by joaomoreno** [comment] 2015-12-02 15:26
I hate it too, will address it asap. Duplicate of #439.

**Closed by joaomoreno** 2015-12-02 15:26 UTC
