### ISSUE TITLE
Find references window overflowing when line-height too high, can't scroll

### ISSUE THREAD

**Issue by jordyvandomselaar** [microsoft/vscode#159347] opened 2022-08-26 20:45 UTC
Type: <b>Bug</b>

1. Set font line-height to 6
2. Hyper click on a symbol with multiple usages
3. An empty window spawns
4. Set font-height to 2
5. Hyper click on a symbol with multiple usages
6. A window with references spawns

Gif: 
![vscode references bug](https://user-images.githubusercontent.com/12712484/186988076-ecf6f770-dee4-4ff1-b9c3-684c5b50c9cd.gif)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:38:59.695Z)
OS version: Darwin arm64 22.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 13, 12|
|Memory (System)|32.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id 0b428673-b177-412a-b196-c6b434dcb359|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|12.6.1
vscode-apollo|apo|1.19.11
gitstash|art|5.1.0
django-html|bib|1.3.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
flow-for-vscode|flo|2.2.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.43.6621
gitlab-workflow|Git|3.48.1
vscode-graphql|Gra|0.7.4
vscode-graphql-syntax|Gra|1.0.4
intellij-idea-keybindings|k--|1.5.2
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
live-server|ms-|0.2.13
indent-rainbow|ode|8.3.1
vscode-jest|Ort|4.6.0
vscode-coverage-gutters|rya|2.10.1
multi-command|ryu|1.6.0
vscode-styled-components|sty|1.7.4
rainbow-tags|vol|0.4.1
vscode-icons|vsc|11.15.0
quokka-vscode|Wal|1.0.498

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by jordyvandomselaar** [comment] 2022-12-05 19:58
Hi @jrieken thanks for the reply!

Example code:

```





const myVariable = true;
console.log(myVariable);
console.log(myVariable);
console.log(myVariable);
```

( Yes the whitespace is required )

Admittedly not my proudest moment for not figuring it out sooner, but if you move your mouse outside of the box, you can scroll. The issue seems to be that the modal where it lists usages, spawns too high up.


https://user-images.githubusercontent.com/12712484/205731323-7c056b13-ab79-4ba9-bfee-363fe48af7d2.mp4

**Comment by jrieken** [comment] 2022-12-08 14:13
/duplicate of https://github.com/microsoft/vscode/issues/151888

Strikes again... The peek widget will reveal the line below the one being pointed at. In some cases this can cause it to move up and out

**Closed by jrieken** 2022-12-08 14:13 UTC
Labels: info-needed, editor-symbols
