### ISSUE TITLE
excuse me, can you tell me how to set two or more backgroundImages in my IDE's

### ISSUE THREAD

**Issue by HuRainMan** [Microsoft/vscode#36434] opened 2017-10-17 16:51 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-10-17 17:25
Please provide more information about this issue. What is the expected behavior? Can you provide a screenshot?

**Comment by atian25** [comment] 2017-10-18 02:13
sound something like this:  https://marketplace.visualstudio.com/items?itemName=shalldie.background

but this will change vscode to warning, maybe support as config?

**Comment by mjbvz** [comment] 2017-10-18 05:25
Yes, what that extension does is not officially supported and may break things. The ability to set background images for the editor is tracked by #17219

**Comment by mjbvz** [comment] 2017-10-24 18:21
Closing as duplicate of #17219

**Closed by mjbvz** 2017-10-24 18:21 UTC
Labels: needs more info
