### ISSUE TITLE
Focused view doesn't show when focusing the extensions view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#191748] opened 2023-08-30 07:43 UTC
Testing #191341

1. Append `${separator}${focusedView}` to the `window.title` setting
2. Focus the Extensions view

🐛 It doesn't show the view's name in the title. It seems to work for all other views.

https://github.com/microsoft/vscode/assets/22350/00728a91-b72f-4cea-b494-22afe31c88e5

**Comment by meganrogge** [comment] 2023-08-30 15:32
@sandy081 since you own both the views service and extensions editor, could you pls take this one as I'm not sure if it's by design?

**Comment by sandy081** [comment] 2023-08-30 16:05
Search input is not part of any view, hence there is no view in focus. If there is no view in focus, we should show the view container in focus.

**Comment by sandy081** [comment] 2023-08-30 16:10
@meganrogge Moving this back to you, since you have implemented this feature. I am happy to review.

**Comment by meganrogge** [comment] 2023-11-10 23:10
This now works - it shows `Installed` by default

**Closed by meganrogge** 2023-11-10 23:10 UTC
Labels: bug, accessibility
