### ISSUE TITLE
VSCode 1.43 messed up my theme color codes

### ISSUE THREAD

**Issue by MariuzM** [microsoft/vscode#92359] opened 2020-03-10 14:02 UTC
The color codes for various JS names/object/var's and so on are different. The color style is different compared to previews version of VSCode.

**Comment by MariuzM** [comment] 2020-03-10 14:06
Not duplicate this looks like a different issue that VSCode is not setting colors properly you BOT

**Comment by MariuzM** [comment] 2020-03-10 14:09
For a split second when i open this new version colors look ok but then they change:
Good colors:
<img width="1440" alt="Screenshot 2020-03-10 at 14 08 59" src="https://user-images.githubusercontent.com/36937039/76320560-c7a29380-62d8-11ea-8266-312fa7fd54db.png">

Bad colors
<img width="1440" alt="Screenshot 2020-03-10 at 14 09 00" src="https://user-images.githubusercontent.com/36937039/76320571-cbceb100-62d8-11ea-897d-59ee990071c2.png">

**Comment by dhershman1** [comment] 2020-03-10 14:10
+1 to this

I was looking into this because the themes I built had whackiness going on, it's reading certain functions as variables now instead which is totally blocking my custom changes. There's nothing I can really change to address this either. So if we could go back to the old way that'd be cool, or maybe what I should do to migrate correctly?

**Comment by MariuzM** [comment] 2020-03-10 14:15
I love the VSCode team you done amazing job, but lately i feel it's becoming like Microsoft that ships windows updates with full of bugs. VSCode team please do longer testing before shipping new version. I personally don't need most of these new features that you have apart from and hoping some performance improvements, so from my point please take more time to test your app.

**Comment by jeancarlos-cpu** [comment] 2020-03-10 14:18
Same here. Both on Ubuntu and Windows after the update.

**Comment by giubatt** [comment] 2020-03-10 14:21
Same here

**Comment by syd619** [comment] 2020-03-10 15:05
+1 class names in general and when extending in class definition, require, class getters & setters and others seem to have wrong colors

**Comment by syd619** [comment] 2020-03-10 15:07
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

![vscode2](https://user-images.githubusercontent.com/5445023/76310254-1cdda580-62d7-11ea-8c0d-e29d4d731355.PNG)
![vscode](https://user-images.githubusercontent.com/5445023/76310256-1e0ed280-62d7-11ea-9504-fc6170a17fc7.PNG)

**Comment by MatiasOlivera** [comment] 2020-03-10 15:10
Duplicate of #92308

**Comment by rebornix** [comment] 2020-03-10 16:48
thank you all for feedback, let's track this issue in https://github.com/microsoft/vscode/issues/92308 and for now you can turn off the semantic syntax highlighting feature by changing below setting:

```
"editor.semanticHighlighting.enabled": false
```

**Closed** 2020-03-10 16:49 UTC
Labels: *duplicate
