### ISSUE TITLE
Mac, Integrated Terminal is slow when copy pasting

### ISSUE THREAD

**Issue by j4t1nd3r** [microsoft/vscode#111234] opened 2020-11-24 14:41 UTC
- VSCode Version: 1.51.1
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Copy / Paste anything into integrated terminal.
2. See Code be pasted in very slowly.
Video example: https://drive.google.com/file/d/1hpo2HjJKLA0kUjczRssqMKMfuz0h83He/view?usp=sharing

Does this issue occur when all extensions are disabled?: No, integrated terminal not available if all extensions disabled.
Issue occurs when using PowerShell or PowerShell Preview extension.

**Comment by Jason3S** [comment] 2020-11-29 10:25
Is this issue related to #108590 ?

Typing in the terminal can become v.e.r.y. s.l.o.w.

**Comment by Jason3S** [comment] 2020-11-29 14:09
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

I'm not using powershell. Just the standard Mac OS zsh.

I tried:
```
    "terminal.integrated.allowChords": false,
    "terminal.integrated.drawBoldTextInBrightColors": false,
    "terminal.integrated.experimentalLinkProvider": false,
    "terminal.integrated.rendererType": "auto"
```

But it didn't seem to make a difference.

**Comment by j4t1nd3r** [comment] 2020-11-30 10:17
> Is this issue related to #108590 ?
> 
> Typing in the terminal can become v.e.r.y. s.l.o.w.

Its exactly the same issue but I do not think it is. The user mentions he/she has the issue in all terminals, bash, zsh... I only have the issue in integrated PowerShell terminals. I do not have this issue in bash, zsh or manually switching to a PowerShell 7.1.0 session. They all copy and paste instantly.

**Comment by Jason3S** [comment] 2020-11-30 12:48
For me copy/paste works fast enough, but typing stops and starts. I can get way ahead with just a few keystrokes. I am using zsh, not PowerShell.

**Comment by Jason3S** [comment] 2020-11-30 12:54
Changing `Terminal > Integrated: Render Type` from `auto` to `canvas` seems to work for me.

![image](https://user-images.githubusercontent.com/3740137/100612551-77aaa780-3313-11eb-837a-874e782ff7a5.png)

**Comment by j4t1nd3r** [comment] 2020-11-30 13:19
Solution / Workaround: I has discovered the source of the issue. In bash / zsh, copy paste is done via command key + c or v.

In the integrated terminal you can do this either via ctl or command. Using ctrl though, the paste happens much slower where as using command its instant. 

As my background is windows until 2 months ago, I been using ctrl to copy paste instinctively without realising it and command when ctrl copy paste fails such as in bash or zsh.

**Comment by mayankkapoor** [comment] 2020-12-13 06:33
I also have this issue, integrated terminal is very laggy while typing. Changing renderer type didn't help. I tried auto, canvas and dom. I think the issue still exists and should remain open.

**Comment by j4t1nd3r** [comment] 2020-12-22 14:34
As requested, reopened. 
This issue is also not resolved for me. I thought it was resolved but it turns out the issue is inconsistent.
Sometimes using the right click menu  copy / paste function works over cmd c / v being slow, sometimes both don't work.

**Comment by Jason3S** [comment] 2020-12-22 14:44
I think it is a duplicate of #105446

**Comment by pcgeek86** [comment] 2021-03-22 16:01
Same problem here. Pasting text into the Integrated Terminal is slow in VSCode, but much faster in Microsoft Windows Terminal on Windows 10.

* Dell XPS 9350
* Windows 10 20H2 64-bit
* VSCode 1.54.3

I captured a video of the performance problem, comparing Windows Terminal below.

https://user-images.githubusercontent.com/466713/112019978-353cee80-8aed-11eb-8d52-6f118a317587.mp4

**Closed** 2021-03-30 17:41 UTC
Labels: *as-designed, integrated-terminal, mac

**Comment by johnsen9000** [comment] 2021-04-09 12:26
But that doesn't really fix the problem though? Is there a fix to stop the slowness and fix the truncation?
