### ISSUE TITLE
Folding based on code scope for C-style languages in VSCode

### ISSUE THREAD

**Issue by duong2179** [Microsoft/vscode#28678] opened 2017-06-14 02:23 UTC
- VSCode Version: 1.13.0
- OS Version: macSierra 10.12.5

Steps to Reproduce: Please refer to [SO question](https://stackoverflow.com/questions/44534198/folding-based-on-code-scope-for-c-style-languages-in-vscode)

**Comment by BrodyB** [comment] 2017-06-22 23:58
We use a LOT of C# `#region` sections in our code where I work, so this would be incredibly appreciated!

**Comment by wsmelton** [comment] 2017-06-29 14:38
#3422

**Comment by duong2179** [comment] 2017-07-28 06:13
Using preprocessor directives - that are usually aligned to beginning of line - would break all folding scopes :(

**Comment by aeschli** [comment] 2017-08-09 14:49
duplicate of #3422

**Closed by aeschli** 2017-08-09 14:49 UTC
Labels: editor-folding
