### ISSUE TITLE
Use workspace/folder settings when file is opened outside of workspace

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#30841] opened 2017-07-17 08:35 UTC
Given a workspace `foo`, if file `foo/bar` is opened in VSCode standalone (not inside the `foo` workspace`), any settings in `foo/.vscode/settings.json` will not be picked up.

This matters when [using VSCode as a git mergetool](https://github.com/Microsoft/vscode/issues/5770). VSCode will open a file an editor to present the merge conflict, but the editor will not respect workspace settings. One example is where this is significant is formatter settings (like Prettier). Formatting the file will not respect project settings.

I understand workspace settings are specifically related to workspaces in VSCode, but I can't help but wonder if it makes sense to have "folder" settings which can be inherited from any parent folder for a given file. Has this idea been discussed?

**Comment by sandy081** [comment] 2017-11-17 12:15
Duplicate of #32693

**Closed by sandy081** 2017-11-17 12:15 UTC
Labels: config, feature-request
