### ISSUE TITLE
window title is not fully displayed

### ISSUE THREAD

**Issue by barrychen38** [microsoft/vscode#113407] opened 2020-12-25 06:20 UTC
Issue Type: <b>Bug</b>

Steps:

1. open vs code normally (**not in full screen**)
2. double click right empty place to create a untitled file
![image](https://user-images.githubusercontent.com/12877711/103122475-63ac5880-46bb-11eb-813d-5d8948fc6d6e.png)
3. now you will see the window title is not fully displayed (util open another file or resize code window size)
![image](https://user-images.githubusercontent.com/12877711/103122565-ba199700-46bb-11eb-9d73-4c0c88a67603.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (13.54GB free)|
|Process Argv|./ --crash-reporter-id ab5d0960-bbde-4268-9bf3-e7f9b0b9bd20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
vscode-docker|ms-|1.9.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
gitblame|wad|6.0.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by sbatten** [comment] 2021-01-04 14:52
duplicate of https://github.com/microsoft/vscode/issues/106001

**Closed by sbatten** 2021-01-04 14:52 UTC
Labels: bug, titlebar
