### ISSUE TITLE
highlight does not work in js

### ISSUE THREAD

**Issue by lv7777** [Microsoft/vscode#2939] opened 2016-02-11 15:24 UTC
<img width="224" alt="dd" src="https://cloud.githubusercontent.com/assets/8572307/12980205/b012acaa-d11e-11e5-9c9f-f2e463fdb8fa.PNG">

**Comment by aeschli** [comment] 2016-02-11 16:55
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Closed by aeschli** 2016-02-11 16:55 UTC
