### ISSUE TITLE
When staging changes on Source Control, all closed Git repositories are opened again

### ISSUE THREAD

**Issue by KevLehman** [microsoft/vscode#85319] opened 2019-11-21 17:39 UTC
Issue Type: <b>Bug</b>

- Open a folder with multiple Git Repositories
- Close some repositories
- Change 1 file on an open repository
- Stage change

When refreshing git status, all git repositories are re-opened

VS Code version: Code - Insiders 1.41.0-insider (2014f5adccbce83d347e714206903f2bbee40dcb, 2019-11-18T09:37:06.552Z)
OS version: Linux x64 5.0.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2764)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.59GB (0.58GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.0
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.8.0
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
vscode-postgresql|ms-|0.2.0
Go|ms-|0.11.9
typescript-javascript-grammar|ms-|0.0.53
vsliveshare|ms-|1.0.1293
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.13.0
vscode-manifest-yaml|Piv|1.13.0
vscode-spring-boot|Piv|1.13.0
material-icon-theme|PKi|3.9.1
java|red|0.53.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by gjsjohnmurray** [comment] 2019-11-21 18:39
Possibly a duplicate of #85247

**Comment by KevLehman** [comment] 2019-11-22 00:32
Well, I'm not sure if it's an exact duplicate, but the issue appears to be related

**Comment by joaomoreno** [comment] 2019-11-22 14:56
> Close some repositories

How do you close them?

**Closed** 2019-11-29 15:14 UTC
Labels: needs more info
