### ISSUE TITLE
Code lens does not show references on const arrow functions (Typescript) - no intellicode problem

### ISSUE THREAD

**Issue by Hmve** [microsoft/vscode#109355] opened 2020-10-26 08:52 UTC
I had already filed this bug on the intellicode issue page with the response that this seams to be an vscode problem ([https://github.com/MicrosoftDocs/intellicode/issues/240]). Perhaps one of you can find the cause of th problem.

- VSCode Version:
- OS Version:

Steps to Reproduce:
1. create an empty file e.g. test.ts
2. write code as follows:

``` javascript
const foo = () => {
  console.log('do something');
};

const bar = () => {
  foo();
};`

function foo2() {
  console.log('do something');
}

function bar2() {
  foo2();
}
```
3. Result:
![image](https://user-images.githubusercontent.com/73341358/97151968-86c89380-1770-11eb-967c-62ced3247438.png)

for "normal" functions references will be shown for const arrow functions not.

**Comment by mjbvz** [comment] 2020-10-27 00:28
Duplicate of https://github.com/microsoft/TypeScript/issues/29036

Also note that the references on `function` only show up when you enable `javascript.referencesCodeLens.showOnAllFunctions`

**Closed by mjbvz** 2020-10-27 00:28 UTC

**Comment by Hmve** [comment] 2020-10-27 09:19
Thank you for linking to the typescript issue and looking at problem. The ```javascript.referencesCodeLens.showOnAllFunctions``` option is enabled. It does not change anything. The Problem still exists as described above. But if you say that this a typescript problem, I'll believe you and I hope it will be fixed soon.
