### ISSUE TITLE
Type information is not picked up from .mjs files for "IntelliSense"

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#35332] opened 2017-09-28 17:06 UTC
- VSCode Version: 1.16.1
- OS Version: *

Steps to Reproduce:

1. Create `a.mjs`:

```
    /** @param {string} name */
    export default function a(name) {
      return 'hi'
    }
```

2. Create `use-it.js`:

```
    import a from './a.mjs'

    // Then...
```

3. ...type `a(`
4. No useful "IntelliSense"
5. Renaming `a.mjs` to `a.js` results in useful "IntelliSense"

Reproduces without extensions: Yes

**Comment by mjbvz** [comment] 2017-09-28 17:45
Duplicate of https://github.com/Microsoft/TypeScript/issues/11367 / https://github.com/Microsoft/TypeScript/issues/10939

We currently don't support project intellisense for non *.js or *.ts file extensions. This would require support from TypeScript and I don't think we can do anything on the VS Code side the support this case

Closing as upstream

**Closed by mjbvz** 2017-09-28 17:45 UTC
Labels: duplicate, javascript, upstream
