### ISSUE TITLE
Change side in diff mode with a key shortcut

### ISSUE THREAD

**Issue by joelazar** [microsoft/vscode#78792] opened 2019-08-09 11:58 UTC
I hope I don't duplicate any issues here but after a reasonable amount of time I couldn't find the answer for how to change sides in diff mode with a key shortcut.

Is this even feasible yet? If it's not could it be requested?

For proving my search attempts I found this unanswered StackOverflow [question](https://stackoverflow.com/questions/51599482/key-shortcut-to-switch-between-diff-splits-in-visual-studio-code) with the same request.

Thank you in advance.

**Comment by rebornix** [comment] 2019-09-04 20:42
/duplicate of https://github.com/microsoft/vscode/issues/20958

**Closed** 2019-09-04 20:42 UTC
Labels: *duplicate
