### ISSUE TITLE
Format html/handlebars messes up on meta tags

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12964] opened 2016-09-29 01:09 UTC
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:

1. Have a block of handlebars code with metadata (this should also apply to html; it seems to already be a bug in the existing stable build for html)
2. Format this block of code.
3. Note that sometimes metadata tags are orphaned onto their own lines of code.

Before formatting
<img width="754" alt="screen shot 2016-09-28 at 6 04 02 pm" src="https://cloud.githubusercontent.com/assets/11839736/18937602/91fa1432-85a6-11e6-8dbe-b3f031f1d723.png">

After formatting
<img width="767" alt="screen shot 2016-09-28 at 6 05 03 pm" src="https://cloud.githubusercontent.com/assets/11839736/18937603/93d36e34-85a6-11e6-98e3-0b57411b22e4.png">

Does not match the output of http://jsbeautifier.org/
<img width="679" alt="screen shot 2016-09-28 at 6 07 34 pm" src="https://cloud.githubusercontent.com/assets/11839736/18937597/884fda20-85a6-11e6-9e56-f93575e87c7f.png">

**Comment by dbaeumer** [comment] 2016-09-29 09:17
According to @bgashler1 no regression. Moving to October.

**Comment by aeschli** [comment] 2016-10-11 11:59
@bgashler1 Can you still have the example code. Can you paste it here?

**Comment by aeschli** [comment] 2016-10-11 14:52
I reproduced with
```
{{#section 'metatags'}}
<meta name="test" content="vas adbasdv adv hasdsad jaasd  asds asdsd asd asd as ad sdasd  jadasdd asdasdas dasdasd asdas das dsdasd jasdasd " />
<meta name="test2" content="test" />
{{/section}}
```

The line break is added as our default settings specify:
`html.format.wrapLineLength": 120,`

Closing as not a bug.

**Closed by aeschli** 2016-10-11 14:52 UTC
Labels: bug, format
