### ISSUE TITLE
Blocked access to certain local files from webview after 1.31 update

### ISSUE THREAD

**Issue by bghgary** [Microsoft/vscode#68186] opened 2019-02-08 01:47 UTC
Issue Type: <b>Bug</b>

1. Install the [glTF Tools](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode) extension.
2. Load any glTF model with textures (e.g. download [BoxTextured](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTextured/glTF))
3. Open the glTF and preview the model with (e.g. Alt+G)

    (See https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/152 for original bug report)

There are two issues that occur:
1. The svg icon on the bottom left of the preview window no longer loads. The console shows an error
    ```
    Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
    ```
    I can't explain why this doesn't work anymore.
2. The preview window when using Babylon.js loads images using XHR, puts the result of the XHR into a Blob, creates an object URL from the Blob, then uses IMG element to load the object URL, and finally passes the IMG object to texImage2D. This results in
    ```
    Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    ```

These used to work in the previous release. I'm assuming some security policy has changed such that this no longer works (perhaps from the Chromium update). I can narrow it down to a simpler repro, but I'm filing this first to see if this is a known issue and/or have a workaround/solution.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

**Comment by dbaeumer** [comment] 2019-02-08 08:17
@bpasero because of 

> These used to work in the previous release. I'm assuming some security policy has changed such that this no longer works (perhaps from the Chromium update).

**Comment by jdoklovic** [comment] 2019-02-08 17:28
Not only does it show the error above, but vscode actually sends a message using postMessage to the webview with the contents: 'vscode-did-block-svg'  so it seems more intentional than just a security policy setting in chrome or something.

Also, we definitely see this for svgs, but we also get the console error without the postMessage for certain network image requests, although some of them still work so we're trying to figure out what's differetn between the good and bad requests

**Comment by mjbvz** [comment] 2019-02-09 00:32
Duplicate of #68033

**Closed by mjbvz** 2019-02-09 00:32 UTC
Labels: electron-3.0.x-update, new release, webview

**Comment by bghgary** [comment] 2019-02-09 01:01
@mjbvz Is the second issue a duplicate? I can understand how the SVG not rendering is a duplicate. Perhaps I should have filed two issues.

**Comment by bghgary** [comment] 2019-02-09 01:02
The second issue has nothing to do with SVGs. It is loading either PNGs or JPGs.

**Comment by mjbvz** [comment] 2019-02-09 01:05
Yes, please open a new issue for that with some example code so that we can investigate

**Comment by bghgary** [comment] 2019-02-09 01:08
Ok, will do. It might take a bit of time to create a small repro.

**Comment by bghgary** [comment] 2019-02-09 02:50
While trying to create the min repro, I figured out what is causing the problem.

Here is the HTML that I tried:
```javascript
<html>
<head>
</head>
<body>
    <div><canvas id="renderCanvas"></canvas></div>
    <div><button onclick="foo()">foo</button></div>
    <script>
        function foo() {
            var request = new XMLHttpRequest();
            request.open("GET", "vscode-resource:c:/GitHub/glTF-Sample-Models/2.0/BoxTextured/glTF/CesiumLogoFlat.png", true);
            request.responseType = "arraybuffer";
            request.onreadystatechange = function () {
                if (request.readyState === 4) {
                    var blob = new Blob([request.response], { type: undefined });
                    var url = URL.createObjectURL(blob);
                    var img = new Image();
                    img.onload = function () {
                        URL.revokeObjectURL(url);
                        var canvas = document.getElementById("renderCanvas");
                        var gl = canvas.getContext("webgl2");
                        var texture = gl.createTexture();
                        gl.bindTexture(gl.TEXTURE_2D, texture);
                        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, img);
                        console.log("done");
                    };
                    img.src = url;
                }
            };
            request.send();
        }
    </script>
</body>
</html>
```

The problem code is `URL.revokeObjectURL(url);`. If this gets called before the `img` is uploaded to the texture via `gl.texImage2D`, then it throws the CORS security exception. This is not obvious at all. The fix is simply to make sure that the URL is not revoked until after the `img` is uploaded.

I'm not sure what changed that caused this. Should I still file an issue for this or is this expected behavior?

**Comment by mjbvz** [comment] 2019-02-09 03:14
@bghgary Thanks for investigating.

I see the same error if you open that html file using the `file:` protocol in chrome, but not if I serve the page from a simple http server. It also fails if I use a data uri:

```
data:text/html;charset=utf-8;base64,PGh0bWw+DQoNCjxoZWFkPg0KPC9oZWFkPg0KDQo8Ym9keT4NCiAgICA8ZGl2PjxjYW52YXMgaWQ9InJlbmRlckNhbnZhcyI+PC9jYW52YXM+PC9kaXY+DQogICAgPGRpdj48YnV0dG9uIG9uY2xpY2s9ImZvbygpIj5mb288L2J1dHRvbj48L2Rpdj4NCiAgICA8c2NyaXB0Pg0KICAgICAgICBmdW5jdGlvbiBmb28oKSB7DQogICAgICAgICAgICB2YXIgcmVxdWVzdCA9IG5ldyBYTUxIdHRwUmVxdWVzdCgpOw0KICAgICAgICAgICAgcmVxdWVzdC5vcGVuKCJHRVQiLCAiaHR0cHM6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvY29tbW9ucy8wLzBiL0NhdF9wb3N0ZXJfMS5qcGciLCB0cnVlKTsNCiAgICAgICAgICAgIHJlcXVlc3QucmVzcG9uc2VUeXBlID0gImFycmF5YnVmZmVyIjsNCiAgICAgICAgICAgIHJlcXVlc3Qub25yZWFkeXN0YXRlY2hhbmdlID0gZnVuY3Rpb24gKCkgew0KICAgICAgICAgICAgICAgIGlmIChyZXF1ZXN0LnJlYWR5U3RhdGUgPT09IDQpIHsNCiAgICAgICAgICAgICAgICAgICAgdmFyIGJsb2IgPSBuZXcgQmxvYihbcmVxdWVzdC5yZXNwb25zZV0sIHsgdHlwZTogdW5kZWZpbmVkIH0pOw0KICAgICAgICAgICAgICAgICAgICB2YXIgdXJsID0gVVJMLmNyZWF0ZU9iamVjdFVSTChibG9iKTsNCiAgICAgICAgICAgICAgICAgICAgdmFyIGltZyA9IG5ldyBJbWFnZSgpOw0KICAgICAgICAgICAgICAgICAgICBpbWcub25sb2FkID0gZnVuY3Rpb24gKCkgew0KICAgICAgICAgICAgICAgICAgICAgICAgVVJMLnJldm9rZU9iamVjdFVSTCh1cmwpOw0KICAgICAgICAgICAgICAgICAgICAgICAgdmFyIGNhbnZhcyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJyZW5kZXJDYW52YXMiKTsNCiAgICAgICAgICAgICAgICAgICAgICAgIHZhciBnbCA9IGNhbnZhcy5nZXRDb250ZXh0KCJ3ZWJnbDIiKTsNCiAgICAgICAgICAgICAgICAgICAgICAgIHZhciB0ZXh0dXJlID0gZ2wuY3JlYXRlVGV4dHVyZSgpOw0KICAgICAgICAgICAgICAgICAgICAgICAgZ2wuYmluZFRleHR1cmUoZ2wuVEVYVFVSRV8yRCwgdGV4dHVyZSk7DQogICAgICAgICAgICAgICAgICAgICAgICBnbC50ZXhJbWFnZTJEKGdsLlRFWFRVUkVfMkQsIDAsIGdsLlJHQkEsIGdsLlJHQkEsIGdsLlVOU0lHTkVEX0JZVEUsIGltZyk7DQogICAgICAgICAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygiZG9uZSIpOw0KICAgICAgICAgICAgICAgICAgICB9Ow0KICAgICAgICAgICAgICAgICAgICBpbWcuc3JjID0gdXJsOw0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH07DQogICAgICAgICAgICByZXF1ZXN0LnNlbmQoKTsNCiAgICAgICAgfQ0KICAgIDwvc2NyaXB0Pg0KPC9ib2R5Pg0KDQo8L2h0bWw+
```

VS Code's webview content behave more like a `data:` protocol html page and I suspect that Chrome places some additional CORS limitations on these (or it could be a bug). Since there is a workaround and our behavior is consistent with Chrome, and since I'm not sure if this is a bug or the designed behavior, I don't think we'd spent much time looking into fixing this in VS Code unless more api users start reporting similar problems

**Comment by bghgary** [comment] 2019-02-09 03:55
Ok, that's fine. It's easy to fix from my side anyways.
