### ISSUE TITLE
Format Document Resulting in Error

### ISSUE THREAD

**Issue by hariram1975** [Microsoft/vscode#36513] opened 2017-10-18 19:43 UTC
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Click on Format Document (Alt+Sht+F)
2.

Reproduces without extensions: Yes/No

**Comment by hariram1975** [comment] 2017-10-18 19:45
![image](https://user-images.githubusercontent.com/26047377/31739216-3ae98b7e-b41b-11e7-8acc-98331f538b5d.png)

After Click on Format Document, I don't have any editorconfig file as well in my react project.
![image](https://user-images.githubusercontent.com/26047377/31739260-57e852b4-b41b-11e7-983f-580f97ad4b55.png)

**Comment by mjbvz** [comment] 2017-10-19 04:21
Does this still happen if you disable all extensions? To do this, run the `Extensions: Disable all extensions` command in vscode and then restart the editor

**Comment by hariram1975** [comment] 2017-10-19 21:15
thanks disable HookyQR.beautify fixed the issue

**Comment by mjbvz** [comment] 2017-10-20 03:03
Thanks for the followup. Closing as caused by extension

**Closed by mjbvz** 2017-10-20 03:03 UTC
Labels: caused-by-extension, new release
