### ISSUE TITLE
VScode close Automatically in Archlinux (Manjaro 20.0.1)

### ISSUE THREAD

**Issue by moacirandretti** [microsoft/vscode#107037] opened 2020-09-18 18:04 UTC
- VSCode Version: 1.4

- OS Version:

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.7.19-2-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 1600 Six-Core Processor
Memory: 7.8 GiB of RAM
Graphics Processor: GeForce GTX 1650/PCIe/SSE2

Steps to Reproduce:

1. Open the VS Code then click on the blue button "Open folder".
2. After that the window of the VSCode automatically close without any error or message.
The same occurs when I  click on any menu dialogue opened with "ctrl + shift + p". (list of commands)

I ran `code --verbose` at the terminal and after that I clicked on the blue button "Open folder". The bug occurs again and at this time the terminal gave me a message:

```
[32689:0918/144354.534314:INFO:CONSOLE(1705)] "%cTRACE color: #888 telemetry/views.welcomeAction [object Object]", source: file:///var/lib/snapd/snap/code/44/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (1705)
[32689:0918/144354.535064:INFO:CONSOLE(1705)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.files.openFolder", source: file:///var/lib/snapd/snap/code/44/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (1705)
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
(code:32689): GdkPixbuf-WARNING **: 14:43:54.604: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
(code:32689): Gtk-WARNING **: 14:43:54.604: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
(code:32689): GdkPixbuf-WARNING **: 14:43:54.604: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:/build/gtk+3.0-24RAPQ/gtk+3.0-3.22.24/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
/dev/fd/3: Arquivo ou diretório inexistente
Server response:
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment] 2020-09-18 18:12
/duplicate of #100940

Also check comment https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395 if workaround described here helps.

**Closed** 2020-09-18 18:12 UTC
Labels: *duplicate

**Comment by moacirandretti** [comment] 2020-09-18 21:55
I found the solution here ([100940](https://github.com/microsoft/vscode/issues/100940)):

sudo mkdir /usr/lib/x86_64-linux-gnu/
sudo ln -s /usr/lib/gdk-pixbuf-2.0 /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
