### ISSUE TITLE
Output channel highlighting is broken with removed text/x-code-output mimetype

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#13502] opened 2016-10-11 12:46 UTC
- VSCode Version: 1.7
- OS Version: OSX

We are highlighting the output from our extension by creating a language + grammar and associating it with `text/x-code-output` mimetype:

```
  "contributes": {
    ...
    "languages": [
      {
        "id": "wallaby-output",
        "mimetypes": [
          "text/x-code-output"
        ]
      }
    ],
    "grammars": [
      {
        "language": "wallaby-output",
        "scopeName": "wallaby.output",
        "path": "./wallaby-output.tmLanguage"
      }
    ]
  },
```

![screen shot 2016-08-26 at 6 31 37 pm](https://cloud.githubusercontent.com/assets/979966/17999152/5feb3a20-6bbb-11e6-8e69-9dc2e5633170.png)

In 1.7 our extension's output highlighting is broken because `mimetypes` were removed, so now it's not possible anymore to apply some language to an output channel. Until [there's the proper solution](https://github.com/Microsoft/vscode/issues/11005) via API, is there any workaround to fix the highlighting for output channels?

/cc @bpasero

**Comment by isidorn** [comment] 2016-10-11 14:11
Assigning to october since this looks like a regression in the insiders channel.
I was not aware that we remove mime types for output. Since the insider release only has new commits from last and this week it should not be too hard to find what is to blame for this breakage.

**Closed** 2016-10-13 07:45 UTC

**Comment by jrieken** [comment] 2016-10-26 14:33
verified by reviewing commit
