### ISSUE TITLE
max single line length for some language colorizers is 20K characters (20000) and breaks subsequent line coloring.

### ISSUE THREAD

**Issue by pr-yemibedu** [Microsoft/vscode#36777] opened 2017-10-23 20:34 UTC
- VSCode Version: 1.17.2 ia32
- OS Version: Windows 10 Version 1703 (Build 15063.674)

Hello, I was looking at a CSS file `C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css` and It seems that only line 14 all of the color is off. All lines after show as though the are commented out.

Steps to Reproduce:

1. Open C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css
2. Look at line 14 (all uncolored).
3. if you add line 15 and start typing, only the comment **green** coloring continues until you do another block comment end "*/"

This will happen also for langauages JavaScript and C#. It was not happening for Clojure nor CoffeeScript. with the same length line.

It is related to #5303

The editor should let the developer know that their is a break between what they are seeing and the true **kind** of data being represented.
A warning pointing to this issue or a general message would suffice. 
Also of consideration, can this be offloading to an async Promise?

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment] 2017-10-25 07:52
@pr-yemibedu this is by design (e.g. the limit of characters we color on a line)

I let @alexandrudima comment on the fact that subsequent coloring of lines is broken.

**Comment by alexandrudima** [comment] 2017-10-25 10:49
Duplicate of #5303

See the code where this limit is enforced - https://github.com/Microsoft/vscode/blob/d34c2cc33df4a7687c8efc961767e94f1f726989/src/vs/workbench/services/textMate/electron-browser/TMSyntax.ts#L348

* there is no language specific discrimination, so any language will have this limitation (css, JavaScript, C#, Clojure and CoffeeScript)
* a warning is printed to the developer console. other editors that do not tokenize lines above certain limits do not prompt this fact in the UI, so we decided to also not prompt in the UI.

**Closed by alexandrudima** 2017-10-25 10:49 UTC
Labels: editor, editor-core
