### ISSUE TITLE
Release-Notes panel not sized correctly when zoomed in

### ISSUE THREAD

**Issue by armin77** [Microsoft/vscode#23985] opened 2017-04-06 05:09 UTC
When using the zoom function for the UserInterface "window.zoomLevel": 1 or the according shortcuts
cmd++ and cmd+- the panel that contains the release-notes is getting smaller and smaller. not taking up the whole space in the editor. (please see the attached screenshot)

![screen shot 2017-04-06 at 07 06 20 copy](https://cloud.githubusercontent.com/assets/7791321/24738717/dbdee146-1a97-11e7-9d4a-6da34886d782.jpg)

- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|
|project-manager|alefragnani|0.13.5|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|docthis|joelday|0.4.3|
|vscode-todo-parser|minhthai|1.8.9|
|atom-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|remote-vscode|rafaelmaiolla|1.0.1|
|guides|spywhere|0.7.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. just open the release-notes
2. use cmd++ to zoom the editor-UI

**Comment by mjbvz** [comment] 2017-04-06 05:10
Duplicate of #5745

**Closed by mjbvz** 2017-04-06 05:10 UTC
Labels: duplicate, webview
