### ISSUE TITLE
last version(1.2.6) break down  on archlinux

### ISSUE THREAD

**Issue by JSLeo** [Microsoft/vscode#56350] opened 2018-08-14 13:04 UTC
Issue Type: <b>Bug</b>

she break when startup

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.14-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.11GB (11.97GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
comments|Ale|1.0.3
better-comments|aar|1.2.6
vue-material|abh|0.0.2
code-gnu-global|aus|0.2.2
copy-django-model-fields|bat|0.0.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
django|big|1.0.0
mapfile|chi|0.0.1
vscode-astyle|chi|0.9.0
npm-intellisense|chr|1.3.0
doxdocgen|csc|0.3.3
arm|dan|0.2.0
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
fileheadercomment|doi|0.0.3
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
pip-packages|etm|0.4.3
vue-inline-template|fai|1.0.1
git-project-manager|fel|1.6.1
vscode-npm|fkn|3.3.0
abnf|for|1.0.0
vscode-import-formatter|hen|0.1.8
beautify|Hoo|1.3.2
nbpreviewer|jit|1.0.0
65816-assembly|jos|0.0.5
vue-designer|kts|0.6.1
autoconf|mae|0.0.7
font-awesome-codes-html|med|0.0.7
Arduino|moo|0.0.4
vscode-pugbeautify|mrm|1.0.2
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.7.1
cpptools|ms-|0.17.7
Go|ms-|0.6.86
sublime-keybindings|ms-|4.0.0
vetur|oct|0.12.6
quicktype|qui|12.0.36
bash-debug|rog|0.2.1
git-merger|sha|0.4.1
bash-beautify|sha|0.1.1
todo-show|suy|0.2.1
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
JavaScriptSnippets|xab|1.7.0
clang-format|xav|1.6.2
markdown-all-in-one|yzh|1.6.0
swig|zhu|0.0.5
vscode-pug-template-literal|zok|0.1.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment] 2018-08-14 17:04
Possibly a duplicate of https://github.com/Microsoft/vscode/issues/55934

@JSLeo 
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bpasero** [comment] 2018-08-17 06:14
Duplicate of https://github.com/Microsoft/vscode/issues/55934

**Closed by bpasero** 2018-08-17 06:14 UTC
Labels: needs more info
