### ISSUE TITLE
High CPU Load from Built-in Extension markdown-language-features 

### ISSUE THREAD

**Issue by shaunclimbon** [microsoft/vscode#197868] opened 2023-11-09 22:39 UTC
Type: <b>Bug</b>

High CPU load (near 100%) from "Code Helper (Plugin)" as reported by Acitivy Monitor.  Narrowed in on markdown-language-features based on the following command:

```
$ ps aux | grep 79131
user         79131 100.0  0.3 1211061764  46720   ??  R     1:50pm   0:17.88 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=79041
```

After disabling only this built-in extension the problem went away.  Did this by searching extensions for "@builtin markdown" and then disabling the corresponding extension.

With the extension enabled and any *.md file open the "Code Helper (Plugin)" process would eventually hit ~100% and remain there.  Even after quitting VS Code this process would persist at ~100% until forcibly killed. As a workaround, now using a non-built-in MD extension.

VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 093ff7a7-7a24-43a2-afc9-21d6a39e463b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
remote-ssh|ms-|0.107.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
markdown-all-in-one|yzh|3.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30882110
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc017:30880892
dsvsc018cf:30880895
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment] 2023-11-15 20:33
Duplicate of #195487

**Closed by mjbvz** 2023-11-15 20:33 UTC
