### ISSUE TITLE
[Lua] vs code pushs left all "end" blocks

### ISSUE THREAD

**Issue by LaevusDexter** [Microsoft/vscode#68876] opened 2019-02-17 17:46 UTC
Issue Type: <b>Bug</b>

Well, that's it.
```lua
function t()
	if true then
            -- ... typing end ...
            for i=1, 100 do
                -- ... typing end ...
                while false do
                    -- ... typing end ...
end -- it appears here
end -- it appears here
end -- it appears here
end
```

Happens since last vc code update.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.93GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
rust|rus|0.5.3

</details>

**Comment by alexr00** [comment] 2019-02-18 15:22
@rebornix and @alexandrudima did something change in the auto indenting? The built in lua extension hasn't changed in months.

**Comment by alexandrudima** [comment] 2019-02-18 15:50
@alexr00 Yes, I tried to fix something a month ago -- https://github.com/Microsoft/vscode/commit/7a835ad2642760345b02d4c8c7b899559926f4c8

**Comment by alexandrudima** [comment] 2019-02-19 15:57
Duplicate of #66873

**Closed by alexandrudima** 2019-02-19 15:57 UTC
Labels: editor-autoindent
