### ISSUE TITLE
Save VSCode User Preferences by Logging in

### ISSUE THREAD

**Issue by Matteoo7** [Microsoft/vscode#23723] opened 2017-03-31 05:29 UTC
It'd be great to be able to login and save user preferences and be able to work with the same settings at a different work station.

**Comment by aeschli** [comment] 2017-03-31 06:18
duplicate of #7311. 

Note that there's a extension that uses github to sync settings:
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Closed by aeschli** 2017-03-31 06:18 UTC
