### ISSUE TITLE
Terminal not reading .profile in bash ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#87045] opened 2019-12-16 01:43 UTC
I'm using the `terminal.integrated.shellArgs.linux:[-1]` setting but terminal is not reading the `.profile` from bash in WSL ?

**Comment by Tyriar** [comment] 2019-12-30 18:00
Looks like a duplicate of https://github.com/microsoft/vscode/issues/87088

**Closed by Tyriar** 2019-12-30 18:00 UTC
Labels: integrated-terminal
