### ISSUE TITLE
Using RegEx `` `(.*)+` `` in File Search crashes VSCode. 

### ISSUE THREAD

**Issue by Tarang74** [microsoft/vscode#128330] opened 2021-07-09 16:05 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Windows_NT x64 10.0.19043
Steps to Reproduce:

1. Open File Search [Ctrl + Shift + F]
2. Type: `` `(.*)+` `` - or: `` `(.*)+?` ``
3. As soon as the last backtick is typed, VSCode freezes and the popup: `The window is not responding` appears.
4. Clicking: `Reopen` displays: `The window has crashed (reason: 'crashed', code: '2')` (for a split second, before the dialog box disappears without letting the user choose between `Reopen` and `Close`.

**Comment by Tarang74** [comment] 2021-07-09 16:09
Hi, sorry that the RegEx in the title is not displaying properly.

I am trying to type: `` `(.*)+` ``

**Comment by IllusionMH** [comment] 2021-07-09 17:45
/needsMoreInfo

Do you have any editors opened at that time?
If yes - it's duplicate of #30874

**Comment by Tarang74** [comment] 2021-07-10 05:20
Hi, yes, so the file where the RegEx finds matches has to be open for the app to crash.

**Comment by IllusionMH** [comment] 2021-07-10 21:54
/duplicate of #30874
You should avoid patterns that cause catastrophic backtracking like `(.*)+` which is "match anything and repeat this match many times"
You should either remove `*` or `+` or make capture group more specific than `.*` so there won't be fight for repetitions

**Closed** 2021-07-10 21:55 UTC
Labels: *duplicate, needs more info, new release
