### ISSUE TITLE
Linux Middle click in explorer's editor list pastes buffer content to active editor 

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#68645] opened 2019-02-13 18:24 UTC
Issue Type: <b>Bug</b>

See gif 
![peek 2019-02-13 21-24](https://user-images.githubusercontent.com/7345761/52734233-b9028380-2fd5-11e9-9419-01a2082f6c9d.gif)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.18.0-14-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.35GB (6.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
blamer-vs|bea|0.4.0
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
doxdocgen|csc|0.4.1
vscode-eslint|dba|1.8.0
vscode-dash|dee|2.0.0
java-decompiler|dgi|0.0.2
xml|Dot|2.4.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
prettier-vscode|esb|1.8.1
file-icons|fil|1.0.16
code-runner|for|0.9.7
kotlin|fwc|0.1.13
kotlindebug|fwc|0.2.2
todo-tree|Gru|0.0.118
perl-outline|hit|0.0.4
code-file-nav|jak|0.7.2
svn-scm|joh|1.47.1
language-haskell|jus|2.5.0
favorites|kdc|2.4.5
saltstack|kor|0.0.5
sftp|lix|1.9.3
bash-ide-vscode|mad|1.3.3
vscode-todo-parser|min|1.9.1
vscode-remote-workspace|mkl|0.41.0
vscode-language-pack-ru|MS-|1.31.4
vscode-kubernetes-tools|ms-|0.1.16
python|ms-|2019.1.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
gradle-language|nac|0.2.3
printcode|nob|3.0.0
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.5.2
java|red|0.38.0
vscode-yaml|red|0.2.1
vscode-sort-json|ric|1.13.0
bash-debug|rog|0.3.3
rust|rus|0.5.3
bash-beautify|sha|0.1.1
emmylua|tan|0.2.2
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
sort-lines|Tyr|1.8.0
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-maven|vsc|0.14.2
debug|web|0.22.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment] 2019-02-18 14:32
Can you reproduce this with latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by Yanpas** [comment] 2019-02-18 15:57
Yes

**Comment by isidorn** [comment] 2019-02-19 08:54
I can also reproduce this.
@alexandrudima the issue here is the following, mouse middle click in the open editors area will close the editor. Once an editor closes, another editor becomes active and gets focus. Now since that editor is focused the middle click will also paste content into the editor.
Should the editor listen only on middle clicks that are in the editor area?
I tried preventing the default and stopping the propagation of the event but that did not seem to fix the issue

**Comment by alexandrudima** [comment] 2019-02-19 12:46
@isidorn On Linux, when pressing the middle click, Electron/Chromium will automatically generate a `paste` event from the selection clipboard, so the editor receives a `paste`, not a mouse down (it doesn't listen to middle clicks outside of the editor area).

My best guess is that Electron/Chromium will emit a paste after each and every middle click and will send that event to whatever has focus.

**Comment by isidorn** [comment] 2019-02-19 15:51
Thanks Alex. 
The issue here is that the middle click we close the editor. Whenever an editor is closed we focus the editor area (probably @bpasero knows the reason for this).
Now since the editor area has focus and because of timing the paste event comes in a bit late and the content is pasted.
A fix for this would be that @bpasero exposes a `preserveFocus` option to the `editorService.closeEditor`

**Comment by bpasero** [comment] 2019-02-19 16:06
@isidorn good point, I actually think we should fix this: if I close an editor from the "open editors" view using the mouse and focus was in the tree, we loose focus currently. Your suggestion makes sense to me.

**Comment by bpasero** [comment] 2019-02-20 08:45
@isidorn `closeEditor`/`closeEditors` now allows to pass in `{ preserveFocus: boolean }` as option.

**Comment by isidorn** [comment] 2019-02-20 08:56
@bpasero fantastic. It now works great. Also clicking X also works weirdly!
@Yanpas try it out in Thursdya vscode insiders and let us know if this is fixed for you. Thanks

**Closed** 2019-02-20 08:56 UTC
Labels: bug

**Comment by bpasero** [comment] 2019-02-20 08:58
> Also clicking X also works weirdly!

This would probably have to be added to the command that closes the editor as some context. Needs to be carefully done because the command is likely used from many places. Not sure how important that one is though.

**Comment by isidorn** [comment] 2019-02-20 09:07
It **works** already by some magic. 
So no action needed yeey

**Comment by Yanpas** [comment] 2019-02-21 09:27
@isidorn still reproduces
![peek 2019-02-21 12-27](https://user-images.githubusercontent.com/7345761/53158159-08e3da80-35d4-11e9-9440-f8cee7d0cc64.gif)

**Comment by isidorn** [comment] 2019-02-21 09:41
@Yanpas please do try when there is no modal dialog. The focus shoudl stay in the open editors list.

**Comment by Yanpas** [comment] 2019-02-21 10:39
If I close editor without modifications then everything goes well.

But if I close current editor that has modifications then text from the buffer is inserted. As you see on a screencast I'm fouces on editor list but still the content of a buffer is pasted inside an editor. Here is another screencast:

![peek 2019-02-21 13-38](https://user-images.githubusercontent.com/7345761/53162884-01c1ca00-35de-11e9-995b-67ed4303aa7f.gif)

**Comment by isidorn** [comment] 2019-02-21 12:57
Got it. That we can not fix - sorry.
Modal dialog steals focus. And when focus is back it goes to the editor.
@bpasero do you already have an issue for this that the model dialog should return focus to where focus was before it stole it?

**Comment by bpasero** [comment] 2019-02-21 14:51
There is no issue for that, but I would think it is on Electron to restore focus to the last element that had focus. I do not think we should be doing something special.

**Comment by Yanpas** [comment] 2019-02-21 15:13
Can you please open an issue at electron project? I'm afraid my description will be unclear due to lack of experience in electron platform and gui development in general.

**Comment by isidorn** [comment] 2019-02-21 15:20
I am sorry but we have other 68644 issues to look at :)
We do not have time to do things like that.

**Comment by Yanpas** [comment] 2019-02-21 15:58
Opened
https://github.com/electron/electron/issues/17087
