### ISSUE TITLE
How to configure VS Code on Windows to run a task in WSL?

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#16797] opened 2016-12-07 08:57 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro 1607

I want to run a task in WSL to run 'make', so I defined the task as:

    {
        "version": "0.1.0",
        "command": "c:/Windows/sysnative/bash.exe",
        "isShellCommand": true,
        "args": ["-c 'cd /mnt/c/myproj/trunk/software/Source/; make'"],
        "showOutput": "always"
    }

when I run it I see:

    error 0x80070057

interspersed with '?' characters in the output window.  

What is wrong with my task definition?

**Comment by dbaeumer** [comment] 2016-12-07 17:24
Actually I haven't found a way yet to make this work.

Dups: https://github.com/Microsoft/vscode/issues/6579

**Comment by networkfusion** [comment] 2016-12-13 15:28
I am also getting this when calling an external batch file that is then calling bash, e.g.:

`
@echo off
set "SystemPath=%SystemRoot%\\System32"
IF EXIST %WINDIR%\\sysnative\\reg.exe (
  set "SystemPath=%SystemRoot%\Sysnative"
  echo. "32-bit process..."
)

set env="/usr/local/libdragon"

IF %1.==. (
  echo. "no parameter"
  %SystemPath%\\bash --verbose -c "export N64_INST=%env%; make"
) ELSE (
  echo. "parameter: %1"
  %SystemPath%\\bash --verbose -c "export N64_INST=%env%; make %1"
)
`

`
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "build",
    "isShellCommand": true,
    "args": [],
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        { 
            "taskName": "Release",
            "args": []
        },
        { 
            "taskName": "Debug",
            "args": ["debug"]
        },
        { 
            "taskName": "Clean",
            "args": ["clean"]
        }
    ]
}
`

from a quick search on google, error 0x80070057 is caused by using legacy console... Is VS code using a legacy console for tasks?!

**Comment by dbaeumer** [comment] 2017-04-26 14:00
Closing as dup.

**Closed** 2017-04-26 14:00 UTC
Labels: duplicate, tasks

**Comment by DavidA2014** [comment] 2017-04-26 14:02
Which is the duplicate issue?

**Comment by dbaeumer** [comment] 2017-04-26 14:23
#6579
