### ISSUE TITLE
Accessibility: Extension list items in the installed extensions treeview are in the tab order.

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#51496] opened 2018-06-08 22:27 UTC
_Learnings from NVAccess testing:_

Items in the   installed extensions treeview are in the tab order. This is not necessary as   you can get to them by using the arrow keys when focused on the treeview.   Having them in the tab order makes keyboard navigation very innefficient

**Comment by ramya-rao-a** [comment] 2018-06-11 15:32
There are multiple actions for each item in the extension list
- Click on item opens extension details in an editor
- Click on Install button (for uninstalled extension) or the Manage button (for installed extension). 
- Click on Reload button 
- Click on Update button along with Manage button

So we need to have these buttons in the tab order.
If we remove them from the tab order, how can they every be reached?

**Comment by auchenberg** [comment] 2018-06-18 18:55
Reopening.

**Comment by ramya-rao-a** [comment] 2018-06-19 00:05
Expected behaviour:

- From the search box, tab should go to the entire extensions list. Next tab should take us out of the viewlet and into the editor space
- From the search box, tab should go to the entire extensions list. Arrow keys from this point can be used to traverse the list. 
- Once a list item has focus
    - Enter/Space on any list item should open the extensions editor
    - Tab at this point will go trough the actionable items in the item (Install/Update/Reload/Manage etc)
    - Arrow keys will still let you traverse the list

Open question:
- What should happen when we press tab after the last action item in the list item has focus?

**Comment by misolori** [comment] 2018-06-19 01:04
@ramya-rao-a if I’m on the last actionable item and hit tab, I would expect to go to the beginning of the actionable items.

**Comment by JacksonKearl** [comment] 2018-07-30 20:53
We currently have no support for dynamically updating tab indices as this would require. It could be done, but would require opening up the action bar and action item interfaces. Not sure if thats something we want to do.

**Comment by ramya-rao-a** [comment] 2018-10-16 18:03
Fixed with https://github.com/Microsoft/vscode/commit/f3eb7ada7422f2fd4cbd7570cd3d6c92edaf72dc

**Closed by ramya-rao-a** 2018-10-16 18:03 UTC
Labels: accessibility, bug, extensions

**Comment by chrmarti** [comment] 2018-11-01 15:03
Not working as described as expected behavior above:
- "From the search box arrow keys can be used": Up/down arrow keys don't do anything when in the search box.
- "Enter/Space on any list item should open the extensions editor": Space doesn't open the editor.
- "If I’m on the last actionable item and hit tab, I would expect to go to the beginning of the actionable items.": It goes to the next section, which appears to be fine, because that's more consistent with general Tab behavior.

Marking for verification steps needed.

**Comment by ramya-rao-a** [comment] 2018-11-01 18:53
Verification Steps:

- From the search box, Ctrl+down-arrow (Cmd+down-arrow in Mac) to step into the list just like the Search Viewlet. From there on up and down arrow to traverse the list
- From the search box, tabbing shouldnt go over list items or the actionable items in the list items
- When Focus is on any item, Enter opens extension editor
- When Focus is on any item, tab moves focus to the actionable item in the item
