### ISSUE TITLE
Horizontal scroll bar disappears when scrolling up text output in the interactive window 

### ISSUE THREAD

**Issue by natwille1** [microsoft/vscode#137896] opened 2021-11-25 12:00 UTC
## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Anaconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

The horizontal scroll should be pinned to the bottom of the interactive window once text output is rendered

## Actual behaviour

The horizontal scroll bar disappears so it's not possible to scroll up to see the text output AND scroll horizontally

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. df = pd.read_csv("longfile.csv")
2. df.head(200)
3. Run cell and show output in interactive window

![image](https://user-images.githubusercontent.com/36617813/143438121-ec988684-d15e-4007-962d-64388f0530a2.png)

Horizontal scroll bar is not present 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment] 2022-08-16 17:23
duplicate of https://github.com/microsoft/vscode/issues/143915

**Closed by amunger** 2022-08-16 17:23 UTC
Labels: bug, notebook-output, interactive-window
