### ISSUE TITLE
Rename stops at destructuring

### ISSUE THREAD

**Issue by cdeutsch** [Microsoft/vscode#66547] opened 2019-01-15 15:53 UTC
- VSCode Version: 1.30.2 (1.30.2)
- OS Version: macOS 10.14.2 (18C54)

Steps to Reproduce:

1. Rename a variable and it stops at any destructuring.

![jan-15-2019 09-45-42](https://user-images.githubusercontent.com/404765/51191998-30e06f80-18ab-11e9-8279-f324215e9241.gif)

Does this issue occur when all extensions are disabled?: Yes

This behavior was recently changed:
https://code.visualstudio.com/updates/v1_30#_renames-handle-jsts-destructuring-properly

It makes sense if you're doing the rename at the point of destructuring, but when making it "above" the point of destructuring it doesn't.

I'd request to support both scenarios, or add a flag to turn off the updated rename so it works like the previous version.

**Comment by mjbvz** [comment] 2019-01-15 18:30
Duplicate of #65518

**Closed by mjbvz** 2019-01-15 18:31 UTC
Labels: editor-contrib
