### ISSUE TITLE
Not all windows restored after File -> Exit

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15131] opened 2016-11-07 22:11 UTC
- VSCode Version: Code - Insiders 1.8.0-insider (c2418f46d20464a893dc5db6449e9d79766eadc4, 2016-11-07T21:40:57.134Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.7|
|python|donjayamanne|0.5.0|
|tslint|eg2|0.5.39|

---

Steps to Reproduce:

1. Open two windows on folders
2. File -> Exit
3. Start: Only one window is restored

**Comment by Tyriar** [comment] 2016-11-07 22:22
Did both windows have dirty files? The way this is meant to work is that the restore logic for the `"window.reopenFolders"` setting is determined (all, none, one) and then workspaces with backups associated with them are restored in addition to them.

So if you had workspaces a and b and only b had dirty files:

- If you triggered file > exit on b, then only b would be restored
- If you triggered file > exit on a, both b and a would be restored (since `"window.reopenFolders": "one"` is the default).

**Comment by chrmarti** [comment] 2016-11-07 23:19
You're right, this is quite confusing. Can we make `"window.reopenFolders": "all"` the default?

**Comment by Tyriar** [comment] 2016-11-07 23:21
Maybe `"window.reopenFolders": "all"` should be implied if hot exit is enabled? /cc @bpasero

**Comment by bpasero** [comment] 2016-11-08 05:55
I do not see how hot exit and restoring all folders are related? We already restore multiple windows if they contain dirty files, no?

**Comment by Tyriar** [comment] 2016-11-08 07:44
I believe File > Exit will only restore windows that were dirty unless `"window.reopenFolders": "all"`.

**Comment by bpasero** [comment] 2016-11-08 08:01
Yes, and that is how I would expect it to work.

**Comment by chrmarti** [comment] 2016-11-08 14:56
@bpasero This seemed confusing. I get some (the last and dirty ones), but not all of the windows back by default. It would be easier to understand and anticipate if just all windows were restored by default.

**Comment by bpasero** [comment] 2016-11-08 18:33
I would wait for more users to complain about this and then we can tweak it 👍

**Comment by Tyriar** [comment] 2016-11-08 18:38
Closing as designed for the time being, will track incoming feedback.

**Closed by Tyriar** 2016-11-08 18:38 UTC
Labels: hot-exit, ux
