### ISSUE TITLE
Builtin Markdown Preview does not show an image file

### ISSUE THREAD

**Issue by kamtungc** [Microsoft/vscode#45635] opened 2018-03-13 07:05 UTC
Issue Type: <b>Bug</b>

![imageFile](imageFile.jpg) does not show in the buildin Visual Studio Markdown preview.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|Memory (System)|7.91GB (2.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-sequence-diagrams|Ale|0.2.1
markdown-nomnoml|amo|0.0.2
graphviz-markdown-preview|gee|0.0.7
mdmath|goe|2.1.0
vscode-plot|hen|0.1.0
mssql|ms-|1.3.0
java|red|0.20.0
markdown-preview-enhanced|shd|0.3.3
vscode-scope|vic|0.0.12
vscode-java-debug|vsc|0.6.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.4.0
vscode-maven|vsc|0.5.2
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|1.1.0

</details>
Reproduces only with extensions

**Comment by kamtungc** [comment] 2018-03-13 07:13
![builtinpreview](https://user-images.githubusercontent.com/22105300/37327381-48fa1c88-2653-11e8-981b-6f0237da8197.JPG)
![builtinpreview2](https://user-images.githubusercontent.com/22105300/37327382-49139f00-2653-11e8-92bf-16fbdf483d14.JPG)

**Comment by mjbvz** [comment] 2018-03-13 17:10
Duplicate of #45155

**Closed by mjbvz** 2018-03-13 17:10 UTC
Labels: markdown
