### ISSUE TITLE
Emmet problem with intellisense list with speed write

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#20495] opened 2017-02-12 03:47 UTC
With speed write it very bad when i press tab it set first item of intellisense list.

We can use intellisense when user select item with arrows keys and Emmet without select any item.

The main problem is vscode select first item by default.

![ks](https://cloud.githubusercontent.com/assets/17777237/22859493/0a2e0e68-f0e6-11e6-8c00-f029e5612ffa.gif)

**Comment by egamma** [comment] 2017-02-20 14:39
This is a duplicate of #20531. 

Pls see this comment for a work around https://github.com/Microsoft/vscode/issues/20531#issuecomment-281091406

**Closed by egamma** 2017-02-20 14:39 UTC
