### ISSUE TITLE
Support loading images in markdown preview from other root folders in multi root workspace

### ISSUE THREAD

**Issue by jaimeo** [microsoft/vscode#91296] opened 2020-02-24 17:37 UTC
Issue Type: <b>Bug</b>

Open a Markdown file that includes a properly formatted and accurate image call. Open Preview to Side.

Expected: linked image appears.
Observed: broken link

Same Markdown file displays images properly when built in GitHub.

Possibly related: the "Insert Media" button in Gauntlet also doesn't work anymore. If you select it, it opens the dialog to enter alt text--if you enter some and the press ENTER as directed, it just reopens the dialog and does nothing else.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:46:03.121Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.70GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
gauntlet|Mic|2.6.0

</details>

**Comment by mjbvz** [comment] 2020-02-24 19:18
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jaimeo** [comment] 2020-02-24 20:24
Yes.
vv
J.O.

**Comment by mjbvz** [comment] 2020-02-24 21:06
Please share example markdown and steps to reproduce the issue

**Comment by jaimeo** [comment] 2020-02-24 21:13
Repro steps are right at the beginning of this very thread:

Open a Markdown file that includes a properly formatted and accurate image call. Open Preview to Side.
Expected: linked image appears.
Observed: broken link
Same Markdown file displays images properly when built in GitHub.

Example markdown:

![Battery pane: predicted battery life per device model in upper left, top energy consumers (by app) in upper right, insights table across the bottom. Documentation link in upper right.](../../media/insights_battery.png)

(That media folder that the image call refers to has been added to my workspace. Also, this repros for me with all of the Preview security settings disabled. Also, I have colleagues experiencing the same behavior, so it's not just me.)

**Comment by mjbvz** [comment] 2020-02-24 21:17
What folder are you opening in VS Code? Does it contain both the markdown and image you are trying to include?

**Comment by jaimeo** [comment] 2020-02-24 21:20
No. The Markdown file calling the image file are not in the same folder. We reorganized our files so that all media for the whole repo is in one media folder at the top of the repo. This is why my image call above pops up a couple of levels with ../../ before dropping into the media folder. It's also why I added that top media folder to my workspace, hoping that would allow VSCode to find the image file.

**Comment by mjbvz** [comment] 2020-02-24 21:23
Can you share what your project looks like on disk and which specific folders you have opened in VS Code?

**Comment by jaimeo** [comment] 2020-02-24 21:31
![vscode_workspace](https://user-images.githubusercontent.com/14114136/75192846-ebc37980-5709-11ea-9b5f-d874ce12f33a.png)
![vscode_filestructure](https://user-images.githubusercontent.com/14114136/75192851-ef570080-5709-11ea-8fa1-8ede123284f7.png)

**Comment by mjbvz** [comment] 2020-02-24 21:35
Does this work if you open a common root folder for both `media` and the markdown file? (i.e. opening `microsoft-365` instead of `managed-desktop`)

**Comment by jaimeo** [comment] 2020-02-24 21:54
OK that does resolve it. That introduces other problems, since the entire repo has zillions of files in it. So, for example, searching for a string finds thousands and thousands of hits in files one is not working on....

**Comment by mjbvz** [comment] 2020-02-24 22:25
Thanks for testing. 

I don't think we've supported this previously so marking as a feature request with help wanted

**Comment by blueworrybear** [comment] 2020-03-04 16:10
@mjbvz @jaimeo
It seems to me that we could add all opened workspace into `localResourceRoots` .
Please refer to my commit [b21512b](https://github.com/blueworrybear/vscode/commit/b21512ba1c2fac0a429841bd84471ae61408bc68) for the detail.

If there is no concern, may I create a pull request?

**Comment by jaimeo** [comment] 2020-03-04 16:52
If you're asking my opinion, it seems fine to me, but I'm no expert on the ins and outs of VSCode, so I don't know what implications there might be arising from your proposal.

**Comment by mjbvz** [comment] 2020-03-04 23:38
@blueworrybear Code change looks good (we should get rid of existing `getWorkspaceFolder` call above however). Please submit a pr

**Closed** 2020-03-09 19:56 UTC
Labels: feature-request, help wanted, markdown
