### ISSUE TITLE
'Hostname could not be found' error always pops up when on a LAN without internet

### ISSUE THREAD

**Issue by ZKjellberg** [Microsoft/vscode#22860] opened 2017-03-19 21:13 UTC
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Connect to a LAN without internet
2. Open VS Code to see **Error: A Server with the specified hostname could not be found.**

![vs code no internet](https://cloud.githubusercontent.com/assets/143709/24084753/b120ad88-0cc6-11e7-85c7-20166bc1cf08.png)

**Comment by weinand** [comment] 2017-03-19 21:18
@ZKjellberg It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ZKjellberg** [comment] 2017-03-20 12:09
@weinand The command `code --disable-extensions` is not a valid command on my Mac. I searched inside the VS Code package and could not find any binaries I could directly call, so I booted up VS Code and disabled my extensions.

Upon a clean restart of VS Code (after disabling all extensions and reloading), I still encounter the error regarding the hostname being unable to be found.

Is there a method for me to boot up VS Code with verbose output? Also, where is this `code` binary stored so I can add it to my PATH? This seems to be a bug as many documentation pages refer to this binary as being automatically available after an install.

**Comment by weinand** [comment] 2017-03-20 12:14
@ZKjellberg you can install code on your PATH within VS Code itself. Just press 'F1' and type 'shell'. Then run the 'Shell Command: Install...".

In a terminal you can then run 'code' directly:
![2017-03-20_13-14-37](https://cloud.githubusercontent.com/assets/1898161/24099382/2e899dd6-0d6f-11e7-88f1-ff87b9562f2c.png)

**Comment by weinand** [comment] 2017-03-20 12:17
Does your problem only occur if you open the markdown file?

**Comment by ZKjellberg** [comment] 2017-03-20 12:51
Thanks for the instructions for enabling the shell commands. I see now the documentation does mention this, but I overlooked it.

When running with `code --disable-extensions`, it opens an empty document and shows the Hostname erorr.

**Comment by weinand** [comment] 2017-03-20 13:24
But the document has a name, and should not be empty?
If you open another document and then shutdown VS Code and open it again, will it open the other document but still show the error?

**Comment by ZKjellberg** [comment] 2017-03-20 13:30
My original screenshot is a poor example. Presently, I am running the command `code --disable-extensions` and it launches the editor with a window titled **Untitled-1** which is an empty file.

If I open a file such as a markdown file, close the editor and re-open using the command, it will not restore my previous session.

**Comment by chrmarti** [comment] 2017-04-04 22:14
@ZKjellberg Does the console in the devtools (Help > Toggle Developer Tools) show more details?

**Comment by ZKjellberg** [comment] 2017-04-05 14:30
@chrmarti Thanks for the heads up on the Developer Tools.

![error](https://cloud.githubusercontent.com/assets/143709/24709844/45eaaaca-19e9-11e7-8ef5-29fc1f6bf2ec.png)

The notification is launched on line 103 of **workbench.main.js** I reviewed the Javascript and wasn't able to find more information on the cause. While the debug console does show **ERR_NAME_NOT_RESOLVED** for the marketplace, this error pops up about 10 seconds later. This was ran using `code --disable-extensions`. See below for a second screenshot of the line printing out the error message (after prettifying the code). If you can guide me on how to debug this further, I can try to share more information.

![debug](https://cloud.githubusercontent.com/assets/143709/24710279/a91826c6-19ea-11e7-84bf-0aed186b9979.png)

**Comment by chrmarti** [comment] 2017-04-05 14:43
The URL shown in the screenshot might be enough to track this down, thanks.

**Comment by joaomoreno** [comment] 2017-04-24 10:13
Dupe of #21601

**Closed by joaomoreno** 2017-04-24 10:13 UTC
Labels: bug, marketplace
