### ISSUE TITLE
Typescript Intellisense is not working

### ISSUE THREAD

**Issue by vvt-wiz** [microsoft/vscode#176018] opened 2023-03-03 06:48 UTC
Type: <b>Bug</b>

1) create a nextjs project
2) include typescript and eslint in it 
3) create files in pages directory, not app directory

it was working fine until a couple of days ago, when typescript intellisense started to malfunction, and the system started heating up . Even after quitting the application process multiple times, this problem has persisted. 

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 21.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 3|
|Memory (System)|16.00GB (8.35GB free)|
|Process Argv|--crash-reporter-id 9c8f7e9f-5bbc-4d84-a115-b14adc3df66a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.7
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.10.4
go|gol|0.38.0
vscode-docker|ms-|1.24.0
remote-containers|ms-|0.282.0
vs-code-prettier-eslint|rve|5.0.4
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
pythonb192cf:30669361
funwalk2cf:30676044

```

</details>

**Comment by mjbvz** [comment] 2023-03-06 16:55
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by vvt-wiz** [comment] 2023-03-07 06:38
Yes . It does. What could be causing this issue ?

**Comment by mjbvz** [comment] 2023-03-07 16:26
Please share a minimal example project that demonstrates the issue so we can take a look

**Comment by vvt-wiz** [comment] 2023-03-08 05:02
Actually I was able to identify the problem yesterday , it was related to this issue:
https://github.com/react-hook-form/react-hook-form/issues/4237

It caused the intellisense to crash.

**Comment by mjbvz** [comment] 2023-03-08 22:31
Thanks. Closing since it sounds like an issue with that package's typings (which should be fixed now t00)

**Closed by mjbvz** 2023-03-08 22:31 UTC
Labels: info-needed
