### ISSUE TITLE
Wrong string interpolation parsing when string contains quotes

### ISSUE THREAD

**Issue by sochka** [Microsoft/vscode#1080] opened 2015-12-07 18:45 UTC
Please look at the self-explaining screenshot.
![2015-12-07 2](https://cloud.githubusercontent.com/assets/822771/11636183/6d7bf95c-9d23-11e5-9456-19f2c772eeac.png)

**Comment by aeschli** [comment] 2015-12-08 09:18
Duplicate of #133.
Fix will be in the End of December release.

**Closed by aeschli** 2015-12-08 09:18 UTC
Labels: bug, js
