### ISSUE TITLE
Still running slow, high CPU

### ISSUE THREAD

**Issue by jrodbshaw** [Microsoft/vscode#72519] opened 2019-04-17 21:37 UTC
Issue Type: <b>Performance Issue</b>

Occurs once loading project, code --status is showing window (project)/ extensionHost/ electron_node tsserver.js/ electron_node typingsInstaller.js tsserver.js typesMap.js/ npm has a CPU % of 71...
All extensions are disabled at time of code --status!

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 6|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv|/private/var/folders/gk/dqxc1_3n6hj5xpbbrtg1ssy80000gn/T/AppTranslocation/BE44C725-6DF6-4AC2-BCF3-A8FDA2B03A02/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   123	  1769	code main
    2	    41	  1770	   gpu-process
    0	    98	  2166	   shared-process
    0	   197	  3888	   window (onecloud)
    0	    57	  3891	     extensionHost
    0	   172	  3894	       electron_node tsserver.js 
    0	    49	  3911	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    41	  3892	     watcherService
    5	    82	  3986	   window (Issue Reporter)
    9	     0	  3987	   (ps)
    4	     0	  3988	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (onecloud)
|    Folder (onecloud): 39 files
|      File types: js(21) json(5) DS_Store(4) gitignore(2) md(2) lock(2)
|                  env(1) ico(1) html(1)
|      Conf files: package.json(2) settings.json(2);
```

</details>
Extensions: none

**Comment by mjbvz** [comment] 2019-04-17 22:13
Are you on VS Code 1.27? If so, please upgrade using the 1.33.1 release

**Comment by j0b0sapi3n** [comment] 2019-04-19 06:02
I've been having this same issue, with tsserver using up to 300% CPU. I've disabled all extensions and I still get the problem.

**Comment by 0x80** [comment] 2019-04-19 12:52
I updated yesterday to 1.33.1 and since then things are super slow with the helper running at 100% cpu a lot of the time. Most notably is tslint visual feedback takes ages to pick up changes and jumping to a type definition by clicking takes seconds.

**Comment by alexdevero** [comment] 2019-04-19 13:04
I also have this issue. VS Code often runs ~30-50% CPU and takes ~1.9 GB Ram .

![vscode-issue-1](https://user-images.githubusercontent.com/4237724/56425372-37b8bd00-62b4-11e9-92bd-37a94bfbe4c1.PNG)
![vscode-issue-2](https://user-images.githubusercontent.com/4237724/56425373-38515380-62b4-11e9-92b1-060299a1dea1.PNG)

Specs:
```
Version: 1.34.0-insider
Commit: 3d67364fbfcf676d93be64f949e9b33e7f1b969e
Date: 2019-04-15T05:21:42.563Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```

**Comment by mjbvz** [comment] 2019-04-29 18:34
Duplicate of #72472

**Closed by mjbvz** 2019-04-29 18:34 UTC
Labels: needs more info
