### ISSUE TITLE
JS Intellisense Loading forever/indefinitely

### ISSUE THREAD

**Issue by Venipa** [microsoft/vscode#88319] opened 2020-01-09 00:18 UTC
Issue Type: <b>Bug</b>

Current Issue (and it stays like that): ![](https://i.mavis.moe/f/8vq2jSUvLd/code-2020-01-09-01-12-25png.png)
My TS Server Log: [tsserver.log](https://i.mavis.moe/f/w69HyWdSHe/2020-01-09-01-15-18txt.txt)

I've tried reloading with disabled extensions, also deleted cache.
All has resulted in failure

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|2.0.5
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
Bookmarks|ale|10.6.0
ng-template|Ang|0.900.3
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.3.7
vscode-tailwindcss|bra|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.7.1
vscode-markdownlint|Dav|0.33.0
jshint|dba|0.10.21
vscode-eslint|dba|2.0.13
netcore-extension-pack|dog|0.10.0
xml|Dot|2.5.0
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
vsc-material-theme|Equ|31.12.0
prettier-vscode|esb|3.18.0
vscode-flutter-i18n-json|ess|0.28.0
vue-inline-template|fai|1.0.1
php-debug|fel|1.13.0
php-pack|fel|1.0.2
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.1
vscode-angular-html|gha|1.5.0
vue-snippets|hol|0.1.11
discord-vscode|icr|3.13.0
composer|ika|0.7.1
vscode-react-typescript|inf|1.3.1
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.0.6
angular-essentials|joh|0.6.3
Angular2|joh|8.3.0
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.8
node-module-intellisense|lei|1.5.0
csharpfixformat|Leo|0.0.84
twig-language-2|mbl|0.9.0
vscode-language-babel|mgm|0.0.25
Angular-BeastCode|Mik|8.1.2
dotenv|mik|1.0.1
vscode-scss|mrm|0.8.1
vscode-azurefunctions|ms-|0.20.1
mssql|ms-|1.8.0
python|ms-|2020.1.57204
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-wsl|ms-|0.41.7
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1456
debugger-for-chrome|msj|4.12.4
vscode-react-native|msj|0.13.2
angular2-inline|nat|0.0.17
php-docblocker|nei|2.1.0
vetur|oct|0.22.6
laravel-blade|one|1.20.0
vscode-react-native-storybooks|Ort|2.7.1
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
quicktype|qui|12.0.46
Csharp-ASPNETCore|rah|1.11.0
java|red|0.55.1
vscode-yaml|red|0.6.1
vscode-essentials-snippets|rob|2.0.0
sass-indented|rob|1.5.1
blazorsnippets|Sco|1.2.1
swdc-vscode|sof|1.3.9
autoimport|ste|1.5.3
sass-indented|syl|1.7.3
serverless-ide-vscode|Thr|0.5.12
vscode-laravel-assist|tia|0.1.7
msbuild-project-tools|tin|0.3.3
lorem-ipsum|Tyr|1.2.0
vscode-maven|vsc|0.20.1
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.26.0
vscode-import-cost|wix|2.12.0
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.2.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2020-01-09 00:40
Where is your code stored? Is it on a drive besides the c: drive?

**Comment by Venipa** [comment] 2020-01-09 00:41
Code ist stored on C,
My project on another sad drive

**Comment by mjbvz** [comment] 2020-01-09 00:43
Duplicate of https://github.com/microsoft/TypeScript/issues/35512

To workaround this, upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by netcore-jroger** [comment] 2020-01-09 00:43
I have this problem too.
vscode: 1.41.1 (user setup)

**Closed by mjbvz** 2020-01-09 00:43 UTC
Labels: javascript

**Comment by Venipa** [comment] 2020-01-09 08:16
installing the typescript@next version via vscode extension has fixed the issue
