### ISSUE TITLE
Inaccurate Error

### ISSUE THREAD

**Issue by solusrassus** [microsoft/vscode#116236] opened 2021-02-09 22:26 UTC
Issue Type: <b>Bug</b>

Hello, I am currently typing up a program fro my class, and within the hpp file, there is a #include <string>. There is nothing wrong with this line of code, but somehow VS Code is telling me that there is.

It says "#include errors detected. Please update your includepath"

I'm not sure how to resolve this, so anything would be helpful. Thank you.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.29GB free)|
|Process Argv|--crash-reporter-id dd3f999a-82b3-4ccf-81b1-5199f22c7bfa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589
core-portspanelcf:30255214

```

</details>

**Comment by meganrogge** [comment] 2021-02-09 22:38
Duplicate of #116237

**Closed** 2021-02-09 22:38 UTC
Labels: *duplicate
