### ISSUE TITLE
Rebooting the computer while Zen mode is enabled breaks normal mode

### ISSUE THREAD

**Issue by rklasen** [microsoft/vscode#110821] opened 2020-11-17 19:56 UTC
- VSCode Version: 1.51.1
- OS Version: Ubuntu 20.04

This seems to be identical to #67059. But that one was never looked into and closed as stale.

Steps to Reproduce:

1. Go into Zen mode
2. Do a system reboot (i.e. `sudo reboot` from any terminal, I guess shutdown etc also work ) *without closing* VSCode or exiting Zen mode first
3. After reboot, Zen mode seems to be embedded into the normal main code window, see screenshot:

![image](https://user-images.githubusercontent.com/13201731/99440753-4c898680-2917-11eb-8e6a-22ae38a7f237.png)

Please note the large empty regions next to the code pane.

*Then* entering Zen mode works normally, but the window is still broken upon exiting Zen mode. This seems to be saved to the project somewhere, as other projects are not affected. Still, I can't find the setting in this project. I am certain this is caused by not properly exiting Zen mode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rklasen** [comment] 2020-11-17 20:00
Thanks to the automatic duplicate finder, i found this bug is also identical to #107868. The fix https://github.com/microsoft/vscode/issues/107868#issuecomment-702003584 also fixed this for me, but I had no way of knowing that centered mode even existed.

**Comment by isidorn** [comment] 2020-11-18 08:43
I understand the issue, however I followed your exact steps and I could not reproduce.
The problem seems to be that we store the centered mode in storage, but not that zen mode is active.

Since there is an easy workaround closing this. However will open if someone has repro steps that also work for me or if more users hit this

**Comment by rklasen** [comment] 2020-12-17 14:09
Hi, I just just hit by this issue again. This time because my desktop session froze and I had to reset the computer. I forgot to mention the last time that I use KDE Plasma, not Gnome which is standard in Ubuntu. It is possible KDE is handling shutdowns differently than Gnome. I just tried my steps to reproduce from the first post again, and the issue is reproducible this way (at least on my machine).

**Comment by rklasen** [comment] 2020-12-17 14:16
Sorry for the double post, but I just found a simpler way to trigger the issue:

- Enter Zen Mode
- Open a Terminal and `pkil -15 code`
- Restart vscode

VSCode is now in the aforementioned superposition of not-in-zen-mode and zen mode. [F1] -> "Toggle center mode" fixes this.

There must be some setting that is stored to the project settings which is not correctly cleared if the IDE crashes.

**Comment by isidorn** [comment] 2020-12-17 14:53
Ok, let's reopen so I can investigate more. Thanks

**Comment by rklasen** [comment] 2020-12-17 14:55
Thank you! Were you able to reproduce the issue with `kill -15`?

**Comment by isidorn** [comment] 2020-12-17 14:58
Not yet, I am working on other things. I will try it probably after holidays.

**Closed** 2021-01-07 16:58 UTC
Labels: bug, workbench-zen

**Comment by isidorn** [comment] 2021-01-07 16:59
@rklasen thanks for reporting this. I can reproduce this.
Seems to be a timing issue.

As a workaround fix, I have changed the default value of the `zenMode.restore` setting to be true. So now when VS Code is closed and opened again zen mode will be preserved. I think this is fair behavior since all our other UI state preserves across reloads. And this also fixes the issue.
Try it out and let me know what you think from tomorrows vscode insiders. Thanks

**Comment by isidorn** [comment] 2021-01-22 14:54
Verifications steps:
* Enter Zen Mode
* Open a Terminal and pkill -15 code
* Restart vscode

Start VS Code again, VS Code should still be in Zen mode, not in a half baked state (only centered mode, not zen)

**Comment by rklasen** [comment] 2021-01-22 15:42
Thank you so much!

**Comment by isidorn** [comment] 2021-01-22 15:45
I will take that as you tried it and it works as expected. Adding verified label

**Comment by rklasen** [comment] 2021-01-22 16:00
I did now, sorry if my previous post was too enthusiastic :sweat_smile: . Just tested on code-insiders (1.53.0-1611306361).
- going to zen mode 
- `pkill -15 code-insiders`
- restart `code-insiders`

VSCode now starts in full screen but not Zen Mode. And certainly not some weird superposition of Zen and normal. So it's not 100% what you described (doesn't restart in Zen), but it's good enough for me.
