### ISSUE TITLE
Random placement for Snippets in autocomplete

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1970] opened 2016-01-13 02:26 UTC
The CSS snippets always show up in the auto-complete suggestions. This isn't ideal for CSS when completing values as they insert a bunch of properties, which isn't valid in that context. This isn't terrible as they're hidden at the end of the list, but in the latest code, they are included randomly, with one of them mostly (always?) showing first in the list:

See gradient, border and transition dispersed through the list, with border as the first completion
![screen shot 2016-01-12 at 6 21 47 pm](https://cloud.githubusercontent.com/assets/465069/12283201/5c619c7e-b959-11e5-9a7e-96dee55dcd9b.png)

They should be last like the old behaviour, and ideally not show up for value completions in CSS (although perhaps there could be snippets that are valid to be inserted in that position?)

Ideally there would be some kind of weighting or ordering to the list of initial completions, as they seem random currently. They're not in defined order in the source file or alphabetical. In an ideal world, I’d like the CSS wide keywords to be kept together and listed last and property specific features first (they're added that way when generating the file)

**Comment by jrieken** [comment] 2016-01-27 14:25
duplicate of #2343

**Closed by jrieken** 2016-01-27 14:25 UTC
Labels: css-less-sass
