### ISSUE TITLE
only last task in tasks.json can be run

### ISSUE THREAD

**Issue by guntern** [Microsoft/vscode#65359] opened 2018-12-19 08:15 UTC
- VSCode Version: 1.31.0-insider 
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Ctrl+P
2. type "tasks " (including space)
3. the list of tasks should be provided, but only the last in tasks.json is shown

It is the same behavior when going via Ctrl+Shift+P and selecting Tasks:Run Task. Configure Tasks however shows the list of all tasks in tasks.json.

I tested my tasks.json file on a windows machine with the same VSCode version (same number and commit id). On windows the full list of tasks (4) in the tasks.json is shown.

On Linux I removed all tasks except the first from tasks.json: The task is shown in the list as expected.
I then added a second task again. Now only the second tasks is shown. Added all four tasks again: Only the last one is shown in the list.

This issue was not there before updating VSCode yesterday. 

btw: The tasks are build tasks for a C-project. They call make (build, rebuild) or copy the resulting binary to a remote machine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by guntern** [comment] 2018-12-19 08:19
Did not find issue #65263 when searching. Apparently this is the exact duplicate for my issue.

**Comment by alexr00** [comment] 2018-12-19 08:43
Yes, duplicate of #65263.

**Closed** 2018-12-19 08:44 UTC
Labels: *duplicate, tasks
