### ISSUE TITLE
Cannot copy/paste text in built-in browser

### ISSUE THREAD

**Issue by ukalwa** [microsoft/vscode#160232] opened 2022-09-06 21:43 UTC
Type: <b>Bug</b>

Run a webserver serving some html content and navigate to the page from built-in browser. Try to copy text from it or paste any copied text into a form.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1089-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id e7dbd8d2-23d4-4973-aea7-529c42e745a6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1089-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (2 x 2793)|
|Memory (System)|3.84GB (1.90GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.10.4
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
prettier-vscode|esb|9.8.0
codespaces|Git|1.10.4
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by gjsjohnmurray** [comment] 2022-09-06 22:21
Maybe #141080. Can you copy using keyboard shortcut Cmd/Ctrl + C?

**Comment by ukalwa** [comment] 2022-09-06 22:49
No, that's what I actually tried. Mouse right click doesn't even bring up a context menu to select any options. Here is a screenshot of the form I am trying to paste text into.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/11986128/188753796-305f906a-d1b5-4bb5-9625-c3b5c725aea0.png">

**Comment by mjbvz** [comment] 2022-09-23 03:14
Duplicate of #129178

**Closed by mjbvz** 2022-09-23 03:14 UTC
