### ISSUE TITLE
Queuing project folders configurable

### ISSUE THREAD

**Issue by pgrycz** [Microsoft/vscode#34533] opened 2017-09-17 06:48 UTC
like it is in e.g Atom

**Comment by alexandrudima** [comment] 2017-09-18 08:19
@pgrycz I'm sorry I don't know exactly what you mean. Can you perhaps describe what you'd want in greater detail ?

**Comment by pgrycz** [comment] 2017-09-18 09:58
Hi,
It's like to make every new folder added in Code (or added via mouse drag
from system window to Code window) as another work project which You can
see at the left tab panel to make it editable via mouse drag so one folder
You can bring up while others down, same with every file inside folders -
You can order them as You want. Currently Code is somehow rigid
and unintuitive and not able to do this naturally (Atom is a great example
for how it would work, but Atom is generaly slow).
Hope it helped You :-)

Cheers
Pawel

2017-09-18 10:19 GMT+02:00 Alexandru Dima <notifications@github.com>:

**Comment by isidorn** [comment] 2017-09-18 12:56
Duplicate of https://github.com/Microsoft/vscode/issues/29715 and #396

**Closed by isidorn** 2017-09-18 12:56 UTC
Labels: needs more info, workbench
