### ISSUE TITLE
Changing icon theme is very expensive on the explorer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#67442] opened 2019-01-29 18:14 UTC
https://github.com/Microsoft/vscode/issues/66485

Repro:

1. Change icon theme command
2. Press down several times, it dropped to 2 fps for the worst case

![image](https://user-images.githubusercontent.com/2193314/51930070-91dd6c80-23ae-11e9-81d9-98474fb8d50a.png)

**Comment by isidorn** [comment] 2019-01-29 20:08
@Tyriar can you also reproduce this with vscode stable?

**Comment by joaomoreno** [comment] 2019-01-29 20:49
Moving to @isidorn to Explorer and @aeschli to Themes.

**Comment by Tyriar** [comment] 2019-01-29 20:49
Stable:

![image](https://user-images.githubusercontent.com/2193314/51939424-4635bd80-23c4-11e9-8dc2-660fb06c8290.png)

Insiders:

![image](https://user-images.githubusercontent.com/2193314/51939389-31f1c080-23c4-11e9-83ef-826718e86f6b.png)

**Comment by joaomoreno** [comment] 2019-01-29 20:49
@Tyriar Can you send over the cpu profiles?

**Comment by Tyriar** [comment] 2019-01-29 21:33
Sent

**Comment by isidorn** [comment] 2019-01-30 15:38
@joaomoreno did you find something in the CPU profile?
DId you actually change how we are reacting to file icon change event compared to stable?

**Comment by joaomoreno** [comment] 2019-01-31 07:58
Did not find anything interesting in the CPU profile. Also didn't change how file icon changes work.

Also, this is my machine:

![image](https://user-images.githubusercontent.com/22350/52040016-64232f80-2536-11e9-80fb-f149aba3f0ed.png)

**Comment by isidorn** [comment] 2019-01-31 08:58
Nothing for the endgame, assigning to February to investigate then

**Comment by Tyriar** [comment] 2019-01-31 17:04
@joaomoreno I think I was on Windows

**Comment by isidorn** [comment] 2019-03-15 16:12
Moving to backlog since I believe we were also behaving like this and nothing changed wrt how we apply file themes..
@aeschli if you want to investigate feel free.

**Closed** 2019-10-08 14:11 UTC
Labels: *out-of-scope, perf, themes, under-discussion
