### ISSUE TITLE
Special characters not correctly displayed in integrated terminal

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#53769] opened 2018-07-07 03:58 UTC
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Open git folder in VSCode
2. Open the integrated terminal
3. Run `tig` and see the special characters not correctly shown if the row is not selected

<img width="254" alt="image" src="https://user-images.githubusercontent.com/4662568/42406572-e8f69a9c-81dc-11e8-9edf-27c02919f294.png">

If a row is selected, then the characters seem correct.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/4662568/42406577-fe91a608-81dc-11e8-9b80-1b7b415c573f.png">

**Comment by Tyriar** [comment] 2018-07-09 12:54
Weird, seems to work fine for me:

<img width="955" alt="screen shot 2018-07-09 at 5 53 45 am" src="https://user-images.githubusercontent.com/2193314/42451582-802e723a-833c-11e8-8ece-99ee119951dc.png">

Could you setup the xterm.js demo and see if you can reproduce there? https://github.com/xtermjs/xterm.js#linux-or-macos

**Comment by Tyriar** [comment] 2018-07-09 12:55
It could be a font problem as well, try changing your font (I'm using [Hack](https://sourcefoundry.org/hack/)).

**Comment by renkun-ken** [comment] 2018-07-09 13:16
I tried Menlo (VSCode default for macOS) and Monaco (macOS default), both not working.

**Comment by Tyriar** [comment] 2018-07-09 16:41
Could you try setup the xterm.js demo and see if it reproduces over there? https://github.com/xtermjs/xterm.js/wiki/Contributing#linux-or-macos

After you get it setup you can enable debug move and view exactly what is being sent to the terminal by the pty. This will help identify at which point the problem is occurring. https://github.com/xtermjs/xterm.js/wiki/Contributing#enabling-debug-mode

**Comment by Tyriar** [comment] 2018-07-12 15:02
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1565

**Comment by Tyriar** [comment] 2018-07-12 15:10
I couldn't repro as I was using the dynamic texture atlas, see https://github.com/xtermjs/xterm.js/issues/1565 for more info.

**Comment by Tyriar** [comment] 2018-07-12 15:31
The fix for this will come in with the July build, in the meantime this setting should workaround the problem:

```
"terminal.integrated.experimentalTextureCachingStrategy": "dynamic"
```

This setting should be stable and will also be the default in the next release.

**Closed** 2018-07-12 15:50 UTC
Labels: bug, integrated-terminal, mac, upstream

**Comment by renkun-ken** [comment] 2018-07-12 15:56
Thanks! `terminal.integrated.experimentalTextureCachingStrategy` does work for me.
