### ISSUE TITLE
Print margin or similar

### ISSUE THREAD

**Issue by mkoske** [Microsoft/vscode#1836] opened 2016-01-06 19:52 UTC
Hello,

is there a print margin? I mean that line at specified column. Or anythin similar.

If not, then this is a feature request to add it.

BR,
Miika

**Comment by tucker-m** [comment] 2016-01-06 23:40
There isn't, yet. Issue #1673

**Comment by joaomoreno** [comment] 2016-01-07 08:24
Duplicate of #1673

**Closed by joaomoreno** 2016-01-07 08:24 UTC
