### ISSUE TITLE
Unable to open the file because the associated text model is undefined..

### ISSUE THREAD

**Issue by florindaneliuc-cs** [Microsoft/vscode#9865] opened 2016-07-27 18:17 UTC
- VSCode Version: 1.4.0-insider, Commit 825a1e71a436007d88796cb1cf0bad85ad534e53, Shell 0.37.6, Renderer 49.0.2623.75, Node 5.10.0
- OS Version: 6.3.9600

Steps to Reproduce:

Don't have repro steps, it just stopped working **for some files** during the evening. The console log is below. Let me know if I can help with reproducing it

```
messageService.ts:119 
Unable to open 'index.js': Unable to open the file because the associated text model is undefined..: Error: Unable to open 'index.js': Unable to open the file because the associated text model is undefined..
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:104:9516)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:104:9122
    at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:8153)
    at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:11658)
    at i.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:12979)
    at i.Class.define._chainedError (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:12338)
    at i (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:10161)
    at i.Class.define.then (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:13788)
    at Object.P.enter (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:10230)
    at i.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:12979)
    at i.Class.define._setCompleteValue (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:12673)
```

**Comment by rukaelin** [comment] 2016-07-28 11:39
this error is shown when you try to access a file that is existing but being modified.

**Comment by kieferrm** [comment] 2016-07-28 22:15
@rukaelin What exactly do you do when you "open a file two times in the same tab" ?

**Comment by alxdarksage** [comment] 2016-07-29 18:52
I get this error opening a single html file (version 1.3.1 ). I have similar html(ish) files that open fine, and I created this file with an earlier version of MS Code. I can't attach an HTML file, the file causing issues can be found here: https://github.com/Sage-Bionetworks/BridgeResearcherUI/blob/develop/app/src/pages/participant_report/participant_report.html

**Comment by rukaelin** [comment] 2016-07-30 07:01
heres my code for opening and showing the file:
```typescript
let resource = vscode.Uri.file(filePath);
vscode.workspace.openTextDocument(resource).then((doc) => {
  vscode.window.showTextDocument(doc, vscode.ViewColumn.Two);
  }, (reason) => {
    console.log(reason);
});```

between opening the file, I change the content of the file, and also show an html preview in the same tab.

**Comment by rukaelin** [comment] 2016-07-30 08:05
checkig if vscode.workspace.textDocuments contains the document already and only opening it when needed fixed the problem for me

**Comment by TryingToImprove** [comment] 2016-08-02 16:12
Got the same problem... Can't repro, but worked after restarting VS Code

**Comment by kieferrm** [comment] 2016-08-02 20:59
Seems there are two aspects here:
1. @rukaelin has an extension that caused the issue originally but doesn't anymore when he checks if the document is already contained in `vscode.workspace.textDocuments`
1. @florindaneliuc-cs @alxdarksage @TryingToImprove see a similar issue (but not always) just be using the UI.

**Comment by bpasero** [comment] 2016-08-06 10:07
@rukaelin can you share the code of the full extension that causes this?

@florindaneliuc-cs @alxdarksage @TryingToImprove please help us reproducing this if you can find reliable reproducible steps.

**Comment by kmanley** [comment] 2016-08-06 23:20
I get this error consistently whenever I have a lot of tabs open and I press and hold ctrl-w to close them quickly (being careful not to close the final tab which exits vscode)
![text-model-undefined](https://cloud.githubusercontent.com/assets/1238202/17459551/cd70e466-5c0a-11e6-89b3-1fb1ef0a7fe6.png)

**Comment by bpasero** [comment] 2016-08-07 07:07
@kmanley Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by kmanley** [comment] 2016-08-07 16:43
@bpasero yup it happens even if I --disable-extensions. (For reference the only 2 extensions I use are Go 0.6.39 and Code Beautifier 1.1.1)

**Comment by bpasero** [comment] 2016-08-07 16:55
@kmanley so to recap you can always reproduce this by opening a bunch of *.go files and then rapidly closing? anything else involved?

**Comment by kmanley** [comment] 2016-08-07 16:57
@bpasero correct, except the file type doesn't matter. It's always been that way for me with every version of VSCode. Nothing else is involved. Can you dupe?

**Comment by bpasero** [comment] 2016-08-07 17:01
@kmanley oh yeah, I see it 👍

**Comment by kmanley** [comment] 2016-08-07 17:03
@bpasero Cool

**Comment by rukaelin** [comment] 2016-08-08 07:48
Here is a link to my source code: [Viper IDE](https://bitbucket.org/viperproject/viper-ide)
I only get the error when opening the file for the second time. the first time works fine.
after getting the error once the file is "broken", in that the error also occurs when I manually open the file though vscode's file explorer

**Comment by psnider** [comment] 2016-08-09 19:57
Visual Studio Code: 1.4.0
Mac OSX: El Capitan 10.11.6  

I'm seeing this error when I open several files, then select **Close all** from a context menu on one of the edit pane tabs that is **not selected**..

The error seems to happen every time.  

It doesn't occur if there is only one edit pane open, because that edit pane is always selected.

**Comment by bpasero** [comment] 2016-08-10 06:04
Steps to verify: https://github.com/Microsoft/vscode/issues/9865#issuecomment-238054021

**Closed** 2016-08-10 06:04 UTC
Labels: bug, workbench

**Comment by Lywangwenbin** [comment] 2016-08-29 15:47
VS Code V1.4, Mac OS X EI Captian 10.11.6. suddenly pop up with "Unable to open the file because the associated text model is undefined.。"Then I restart the visual code, there is no wrong.

**Comment by miparnisari** [comment] 2016-09-07 12:21
Why is this issue closed? I'm getting this error as well on Windows 10. My repro steps (roughly):

1. Open VS Code in a folder with a small project..
2. Open two files, switch rapidly between the two by double clicking them in the Explorer menu. 
3. While switching, I got a progress bar on top for one of the files. The file itself looked empty.
4. After some time of "loading" I got this error.
