### ISSUE TITLE
Python linting: Hovering over an underlined (pylint, pycodestyle, etc.) issue DOES NOT display the details.

### ISSUE THREAD

**Issue by sverzakov** [microsoft/vscode#137335] opened 2021-11-16 23:30 UTC
According to documentation python linting should work like "Issues are shown in the Problems panel and as underlines in the code editor. Hovering over an underlined issue displays the details."

Issues are in Problems, underlines are present, but "hovering over" does not work for pylint, pycodestyle, etc. However, "hovering over" works for Pylance issues.

Problem occurs only in October release. Reverting to September release resolves the issue.

**Comment by roblourens** [comment] 2021-11-18 23:10
Can you include a screenshot/gif?

Sounds like the problems show up in the problems view, but hovering doesn't work, which makes me think it might be on vscode's end, do you own hovering problems @sandy081?

**Comment by sandy081** [comment] 2021-11-23 08:35
/duplicate

Seems duplicate of https://github.com/microsoft/vscode/issues/136711

**Closed** 2021-11-23 08:36 UTC
Labels: *duplicate
