### ISSUE TITLE
can not Markdown preview an image file that contains a space in the file name

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#7871] opened 2016-06-19 16:45 UTC
- VSCode Version: 1.3.0 Insiders 2016-06-17T05:01:41.413Z
- OS Version: OS X 10.11.5（15F34）

If there is a space in the file name of the image file can not be displayed in the Markdown preview.
It can be displayed if you use the HTML img tag

```
* NG: `![alt](http://link)`

![alt](/Users/satokaz/Gits/advanced-vscode/markdown-it-extension/images/test 1.png)

* OK: HTML img tag
<img src="/Users/satokaz/Gits/advanced-vscode/markdown-it-extension/images/test 1.png">
```

<img width="1476" alt="2016-06-20 1 30 34" src="https://cloud.githubusercontent.com/assets/13635244/16178563/0cd46cbc-3687-11e6-842f-0dc2589b1146.png">

Steps to Reproduce:

1. If there are spaces in the file name or folder name
2. write `![alt](http://link)` and Markdown preview

**Comment by rebornix** [comment] 2016-06-20 05:59
We've already moved to markdown-it and it's using commonmark, so this is expected. You can take a look at the same issue on markdown-it repo https://github.com/markdown-it/markdown-it/issues/147 and the commonmark related spec http://spec.commonmark.org/0.21/#link-destination . Unfortunately spaces in links are not allowed.

BTW, we are still open to community's opinions about the markdown render selection. Before we do move to any other md renderer, you can mitigate the issue by replacing the spaces by `&#32;`, for instance, `![alt](/Users/satokaz/Gits/advanced-vscode/markdown-it-extension/images/test&#32;1.png)`

**Comment by satokaz** [comment] 2016-06-21 23:06
@rebornix, Thank you for explanation. I understand.

> you can mitigate the issue by replacing the spaces by &#32;

I was able to display! thanks!

**Comment by mjbvz** [comment] 2016-09-21 18:45
Closing as by design since we are currently targeting the commonmark specification.

**Closed by mjbvz** 2016-09-21 18:45 UTC
Labels: as-designed, markdown
