### ISSUE TITLE
Error when attempting to sign in to github pull requests

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99505] opened 2020-06-06 02:30 UTC
Click on "Allow" in "the extension github pull requests nightly build wants to access the github account":
![image](https://user-images.githubusercontent.com/8586769/83934102-f3f86f80-a762-11ea-9adc-33de5f339e0b.png)

See:
![image](https://user-images.githubusercontent.com/8586769/83934079-c90e1b80-a762-11ea-9037-4a32b76bc580.png)

Oh no! An error occurred!
Please restart the sign in process from the editor.
Error code 801

**Comment by JacksonKearl** [comment] 2020-06-06 02:31
Seem like it eventually worked. I wouldn't expect to need to go though external github auth flow given I was already signed in to preferences sync?

**Comment by RMacfarlane** [comment] 2020-06-08 15:38
Yeah, the reason for the additional auth is that preferences sync and GHPR have different permissions, so a new, different token is needed.

Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1221

**Closed by RMacfarlane** 2020-06-08 15:38 UTC
