### ISSUE TITLE
Custom views: Updating the label of a node isn't reflected until the node gets repainted (e.g. goes out of view and comes back)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#77000] opened 2019-07-09 15:31 UTC
Issue Type: <b>Bug</b>

Since the change to the new tree, updating the label of a node isn't reflected until the node gets repainted (e.g. goes out of view and comes back). Where as before the change would be reflected immediately.

//cc @alexr00 

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment] 2019-07-10 14:39
This is fixed by https://github.com/microsoft/vscode/issues/77072 since they have the same root cause.

**Comment by eamodio** [comment] 2019-07-11 16:17
@alexr00 I can still reproduce this issue even though #77072 is fixed

**Comment by alexr00** [comment] 2019-07-12 09:26
I've tested using https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/jsonOutline.ts#L26 and it is working well for me. What are the repro steps?

**Comment by eamodio** [comment] 2019-07-12 17:20
This happens in many places in the GitLens views, but one of the easiest to repo is on the compare node under a repository:
![image](https://user-images.githubusercontent.com/641685/61146211-7cb15180-a4a7-11e9-86dc-aadc184229c8.png)

You can see there, that I've expanded the node and its children (_commits_ & _files changed_) have no count at the start (since it is a delayed calculation). But this delayed update usually happens very quickly and if you cause the nodes to scroll out of view (to force them to be repainted) they will have the counts.

![image](https://user-images.githubusercontent.com/641685/61146369-d7e34400-a4a7-11e9-8bad-e258d85cf022.png)

**Comment by hbenl** [comment] 2019-07-20 14:17
I have the same issue with my [Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer), not just with the label but iconPath and description as well.
To reproduce: install the [Mocha Test Explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) extension, clone that extension's [repository](https://github.com/hbenl/vscode-mocha-test-adapter), run `npm install` and open it in VS Code. Then open the Test Explorer and run the tests.

This is what it should look like (and does in 1.36.1):
![Peek 2019-07-20 16-03](https://user-images.githubusercontent.com/16060807/61579715-237d9980-ab09-11e9-9f62-b92580bc4aec.gif)

This is what it looks like in Insiders from 2019-07-19:
![Peek 2019-07-20 16-01](https://user-images.githubusercontent.com/16060807/61579734-59bb1900-ab09-11e9-80db-ccad9b873a4b.gif)

**Comment by hbenl** [comment] 2019-07-20 14:21
I also looked at the communication between the Test Explorer and VS Code (the onDidChangeTreeData events and the getTreeItem and getChildren calls) and VS Code *does* get the updated data from my extension. It just doesn't get rendered.

**Comment by hbenl** [comment] 2019-07-20 14:31
Another observation: updating the entire tree (i.e. sending an onDidChangeTreeData event without an argument) works reliably for me (this could be a workaround, but it's probably bad for performance in some situations). Looking at the animated gif above it looks like the first node update after the update for the entire tree also works, but then nothing is rendered anymore until the entire tree is updated again (at the end of the test run).

**Comment by eamodio** [comment] 2019-07-25 14:56
@alexr00 Any update on this one? I'm honestly getting a little concerned that end-game is coming up soon, and this issue causes LOTS of problems for GitLens as it breaks many UI updates which makes GitLens seem very broken. I've almost gone back to stable, because it impacts GitLens functionality so much.

**Comment by alexr00** [comment] 2019-07-29 14:20
I just got back from vacation and took another look at this. It looks like you aren't firing `onDidChangeTreeData` after the node updates. 

I put a break-point in the only place I see it fired in gitlens: https://github.com/eamodio/vscode-gitlens/blob/master/src/views/viewBase.ts#L279
And another on https://github.com/eamodio/vscode-gitlens/blob/master/src/views/nodes/resultsFilesNode.ts#L84
so I could see when the node was updated. After the node was updated, I didn't see `onDidChangeTreeData` get fired again.

**Comment by alexr00** [comment] 2019-07-29 14:24
@sandy081 when we talked about this before we had said that `onDidChangeTreeData` must be fired when there is a change for it to be rendered. Is this not the case?

**Comment by sandy081** [comment] 2019-07-29 15:40
Yes any change on the node should trigger the change event to get updated.

**Comment by eamodio** [comment] 2019-07-29 16:00
@alexr00 The first place you linked, its the central place GitLens uses to fire that event. So in response to file system or git events, a the repository node will trigger a refresh (https://github.com/eamodio/vscode-gitlens/blob/bf48a26c1dd402803261663e4cf291c4199f5474/src/views/nodes/repositoryNode.ts#L270)

Which causes the tree to call the `getTreeItem` of the node, and then `getChildren`, which updates all the children. But I don't send the `onDidChangeTreeData` for any of the updated children, since the tree is calling to get these updates.

**Comment by alexr00** [comment] 2019-07-29 16:31
I see what you're saying now. I'm looking into it.

**Closed** 2019-07-30 08:48 UTC
Labels: bug, explorer-custom

**Comment by sandy081** [comment] 2019-07-31 12:19
@alexr00 Are there any steps to repro it?

**Comment by alexr00** [comment] 2019-07-31 12:27
https://github.com/microsoft/vscode/issues/78222 is actually a duplicate of this bug. Since that bug is verified, this bug is also verified.

**Comment by eamodio** [comment] 2019-07-31 14:12
Yeah, GitLens works again! Thank you!

**Comment by eamodio** [comment] 2019-08-01 21:02
@alexr00 While this seems almost completely fixed, there still seems to be an issue if the node being updated changes its `collapsibleState` -- I think specifically between None and either Collapsed or Expanded.

I don't have a great repro case yet (working on it), but wanted to mention it.

**Comment by eamodio** [comment] 2019-08-01 22:49
@alexr00 if you clone https://github.com/eamodio/vscode-simple.git you will see the issue above.

**Comment by eamodio** [comment] 2019-08-01 23:00
Although worse than the above, I've also found that my "Show More..." actions in the trees also no longer work (they work fine in stable):

![image](https://user-images.githubusercontent.com/641685/62332701-a2ba8800-b48e-11e9-9fbe-83580b873ac2.png)

Trying to isolate it.

**Comment by alexr00** [comment] 2019-08-02 07:58
Investigating the Show more issue.
