### ISSUE TITLE
[regression] Extension preview codeblock formatting broken

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#205331] opened 2024-02-16 06:40 UTC
View a codeblock within a extension preview inside VSCode
[Example extension](https://marketplace.visualstudio.com/items?itemName=RedCMD.lag-syntax-highlighter)

1.76: ✅
![image](https://github.com/microsoft/vscode/assets/33529441/b2ef4a4f-eab7-4e7e-b417-31a0bc64f99e)

1.81: Codeblock lost its background colour block ❌
![image](https://github.com/microsoft/vscode/assets/33529441/57f7c770-55b4-47dc-8c64-a2677a76f6bb)

1.85: Weird artifacts show up before and after the codeblock ❌
![image](https://github.com/microsoft/vscode/assets/33529441/d446f3a1-cb26-4ff8-bb9d-3cf73165ded8)

````
### For more information

```json
{
	"json": "value"
}
```
````

however the builtin markdown extension preview feature works correctly ✅
![image](https://github.com/microsoft/vscode/assets/33529441/f8aef9fb-a47c-4ae5-8e10-b6ab3458da2c)

**Comment by mjbvz** [comment] 2024-02-21 21:39
Duplicate of #205129

**Closed by mjbvz** 2024-02-21 21:39 UTC
Labels: bug
