### ISSUE TITLE
Releases after 1.64 fail to deploy to Azure Web App Services

### ISSUE THREAD

**Issue by richardwebs** [microsoft/vscode#147133] opened 2022-04-09 09:28 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Use latest version of VS Code (> 1.64) Use the Azure extension to deploy a simple (angular LTS) website to an Azure App Service (Linux or Windows)
2. It just fails, give some weak excuse of connection failure after a few minutes. No luck after trying dozens of times.
3. When I reverted VS code to 1.64 then it worked.

see https://docs.microsoft.com/en-us/answers/questions/796560/not-able-to-deploy-app-on-azure-app-services-using.html that was made by someone else.

**Comment by richardwebs** [comment] 2022-04-09 09:28
yes

**Comment by lszomoru** [comment] 2022-04-11 10:34
Closing this as duplicate of https://github.com/microsoft/vscode/issues/146470.

**Closed by lszomoru** 2022-04-11 10:34 UTC
