### ISSUE TITLE
Provide a way for extensions to get a list of the opened editors

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#21474] opened 2017-02-27 08:18 UTC
- VSCode Version: Code - Insiders 1.10.0-insider (b2a55bd66eb60af11c60ddd61b7581538b216051, 2017-02-24T20:30:00.778Z)
- OS Version: Darwin x64 16.4.0

I'm building a new extension [Restore Editors](https://marketplace.visualstudio.com/items?itemName=eamodio.restore-editors) to be able to save the current set of editors to be re-opened at a later time. Currently I am employing some [serious hackery](https://github.com/eamodio/vscode-restore-editors/blob/master/src/documentManager.ts#L57) to get a list of the opened editors.

It would be great if there was an api that an extension could use to get at that information. Ideally this would provide even more information than is accessible now -- in addition to the `uri` and `viewColumn`, it would be great if there was an `position` that would tell the order of the editors inside a column.

**Comment by jrieken** [comment] 2017-02-28 14:17
dupe of #15178

**Closed by jrieken** 2017-02-28 14:17 UTC
