### ISSUE TITLE
Python interactive terminal freezes

### ISSUE THREAD

**Issue by calbaker** [microsoft/vscode#110270] opened 2020-11-09 22:26 UTC
- VSCode Version: 1.51.0
- OS Version: Windows 10.0.18363 Build 18363

Steps to Reproduce:

1. Install fastsim from [https://www.nrel.gov/transportation/fastsim.html](https://www.nrel.gov/transportation/fastsim.html)
2. Run tests/test26veh3cyc.py by opening it in VSCode, selecting all the text, and hitting \<Shift\> + \<Enter\> to run in interactive python terminal.  
3. Repeat until the interactive terminal becomes unresponsive to keyboard input.  

Does this issue occur when all extensions are disabled?: N/A since it relies on the extensions.  

Output of `code --list-extensions | % { "code --install-extension $_" }`:
```
code --install-extension apommel.matlab-interactive-terminal
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension eamodio.gitlens
code --install-extension Gimly81.matlab
code --install-extension Ikuyadeu.r
code --install-extension julialang.language-julia
code --install-extension mdickin.markdown-shortcuts
code --install-extension mishkinf.goto-next-previous-member
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension RandomFractalsInc.vscode-data-preview
code --install-extension rebornix.ruby
code --install-extension SimplyDanny.modelica
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wingrunr21.vscode-ruby

```

**Comment by Tyriar** [comment] 2020-11-10 20:05
What does `tests/test26veh3cyc.py` do exactly?

**Comment by andycraig** [comment] 2020-11-10 23:10
Possible duplicate of https://github.com/microsoft/vscode-python/issues/14685 and https://github.com/microsoft/vscode-python/issues/14670

**Comment by meganrogge** [comment] 2020-11-11 18:37
@rebornix Was able to reproduce this using [these ](https://github.com/microsoft/vscode-python/issues/14685) steps. The dev console has these errors:

`[Embedded Page] Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
webviewElement.ts:150 [Embedded Page] Failed to construct 'Worker': Script at 'vscode-webview-resource://7dd82fa4-b79f-4b27-ac57-808eec56f265/file///c%3A/Users/Megan/AppData/Local/Programs/Microsoft%20VS%20Code/editor.worker.js' cannot be accessed from origin 'vscode-webview://7dd82fa4-b79f-4b27-ac57-808eec56f265'.`

I noticed that after a certain amount of time (a min or two), the ability to enter input in the interactive terminal returns.

**Comment by rebornix** [comment] 2020-11-11 19:30
It's a duplicate of https://github.com/microsoft/vscode-python/issues/14670 and the log @meganrogge is seeing is webview related, cc @mjbvz

**Closed by rebornix** 2020-11-11 19:30 UTC
Labels: bug, confirmed, notebook

**Comment by calbaker** [comment] 2020-11-11 19:33
@meganrogge, in my case, the ability to enter input returned sometimes but not every time.  I could not find anything that I was doing differently associated with inconsistency.
