### ISSUE TITLE
Scaling over multiple displays stops rendering characters

### ISSUE THREAD

**Issue by bgraeb** [Microsoft/vscode#51576] opened 2018-06-11 07:07 UTC
- VSCode Version: 1.25.0 Insiders 28d5806
- OS Version: W7x32

Steps to Reproduce:

1. Open multiple files in a project
2. Snap VScode to the left side of your leftmost display
3. Drag the right border to the right side of your next display
4. Stop seeing characters in the code windows

Does this issue occur when all extensions are disabled?: Yes

**Comment by bgraeb** [comment] 2018-06-12 05:53
It's quite hard to get some kind of rule from it. In a horizontal way (as in screenshots 3,4), it's quite easy for me to replicate. It even occurs, if the 3rd tile is split again (like screenshot 1,2).

![still good](https://user-images.githubusercontent.com/28475078/41272445-6b65a148-6e15-11e8-82e7-925dbbd82307.png)
![already bad](https://user-images.githubusercontent.com/28475078/41272446-6b802392-6e15-11e8-879f-cdb8a211874f.png)



![good](https://user-images.githubusercontent.com/28475078/41272326-fc10d42a-6e14-11e8-917e-e332734d5079.png)
![bad](https://user-images.githubusercontent.com/28475078/41272327-fc2e776e-6e14-11e8-902e-1f5a319e15b6.png)

I could not figure out, who it works if I go and stack the tiles vertically. It stop redenering once, but I could not redo it.

**Comment by bpasero** [comment] 2018-06-12 05:59
@bgraeb does this reproduce in our stable release too?

**Comment by bgraeb** [comment] 2018-06-12 06:02
@bpasero No, does not seem to.

**Comment by bpasero** [comment] 2018-06-12 06:42
@bgraeb does it reproduce if you run `code --disable-gpu` ?

**Comment by bgraeb** [comment] 2018-06-12 06:46
@bpasero It's extremely slow, if I rescale the windows (like 15 seconds to rearrange the sidebar), but it the characters are rendered. So it's in a way usable.

**Comment by bpasero** [comment] 2018-06-12 06:55
@bgraeb how about "`code --disable-accelerated-2d-canvas`" instead?

**Comment by bgraeb** [comment] 2018-06-12 06:59
@bpasero Characters vanish again. Interestingly, not on the right hand side.

The rescaling time is back to normal

**Comment by bpasero** [comment] 2018-06-12 07:16
@bgraeb do you have another more modern OS to try with, like Windows 10?

**Comment by bgraeb** [comment] 2018-06-12 07:19
I could try MacOs or a W10-VM later this day.

**Comment by bgraeb** [comment] 2018-06-12 15:16
@bpasero Same issue on MacOS. Need to verify on Windows too?

**Comment by bpasero** [comment] 2018-06-12 15:39
@bgraeb crazy, I cannot reproduce on Windows 10 so far. Can you show me a screenshot how this looks for you on macOS (just one please). Also, what are your settings?

**Comment by bgraeb** [comment] 2018-06-13 14:31
Just updated: Looks like it got worse.
![screenshot 2018-06-13 um 16 30 07](https://user-images.githubusercontent.com/28475078/41357757-2429a406-6f27-11e8-8bc6-f6102691bd79.png)

Settings are:
```Json
{
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "files.autoSave": "onFocusChange",
    "files.associations": {
        "*.xaml": "xml"
    },
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "files.defaultLanguage": "shellscript",
    "terminal.integrated.shell.osx": "zsh",
    "editor.cursorStyle": "line",
    "editor.cursorBlinking": "expand",
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.shell.windows": "powershell.exe",
    "terminal.integrated.rightClickCopyPaste": true,
    "editor.minimap.renderCharacters": false,
    "terminal.external.windowsExec": "powershell",
    "terminal.external.osxExec": "Terminal.app",
    "git.confirmSync": false,
    "editor.showFoldingControls": "always",
    "workbench.activityBar.visible": true,
    "extensions.autoUpdate": true,
    "editor.smoothScrolling": true,
    "workbench.panel.location": "right",
    "material-icon-theme.showUpdateMessage": false,
    "markdownlint.config": {
        "MD029": false
    },
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true,
        "suppressUpdateNotice": true,
        "suppressWelcomeNotice": true
    },
    "gitProjectManager.baseProjectsFolders": [
        "~/Tresors"
    ],
    "gitProjectManager.maxDepthRecursion": 3,
    "gitlens.keymap": "chorded",
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.copyOnSelection": true,
    "workbench.list.multiSelectModifier": "alt",
    "extensions.showRecommendationsOnlyOnDemand": true,
    "gitlens.historyExplorer.enabled": true
}

```

**Comment by bpasero** [comment] 2018-06-13 15:02
@bgraeb does it also reproduce if you run "`code-insiders --user-data-dir <some dir>`" to really start a fresh session of VS Code?

**Comment by bgraeb** [comment] 2018-06-14 05:49
I foul out, that the rendering stops, when the powershell console below is about 686 in bufferSize, maybe this helps you. If I expand it a little more, it breaks. (btw. Console rendering keeps working.

If I have the window opened like that and expand the file explorer view, the max-buffer size "scale" drops to around 651.

If I open the settings view, only this stops rendering. You can see that below.

![mosaic capture 2018-06-14 at 07 44 28](https://user-images.githubusercontent.com/28475078/41393589-d1f935cc-6fa6-11e8-9cef-7f56f3e68fd6.png)


About your question:
Just tried it, same issues arise. Interestingly, the welcome-screen stays rendered.

![mosaic capture 2018-06-14 at 07 48 39](https://user-images.githubusercontent.com/28475078/41393730-621c68b8-6fa7-11e8-80fd-5fb94f61da60.png)

**Comment by bpasero** [comment] 2018-06-14 15:00
@bgraeb so do you say it does not reproduce if you do not have a terminal open in VS Code?

**Comment by bgraeb** [comment] 2018-06-14 15:50
Terminal does not seem to change a thing. Some of the screenshot show the broken rendering, whilst rendering in the console is intact.

**Comment by bpasero** [comment] 2018-06-14 15:54
@bgraeb some things to try on those editors where no characters are rendered:
* does resizing make them appear eventually (when you make the editor small)
* does zooming in (via View menu) changes anything?
* does it change when you change the font used for the editor?
* does it change when you disable the minimap?

**Comment by bgraeb** [comment] 2018-06-15 05:47
Thank you, for still trying to figure it out.

| Question                                                     | W7   | MacOs |
| ------------------------------------------------------------ | ---- | ----- |
| does resizing make them appear eventually (when you make the editor small) | yes  | Yes   |
| does zooming in (via View menu) changes anything?            |   No   | No    |
| does it change when you change the font used for the editor? |   No   | No    |
| does it change when you disable the minimap?                 |   No   | No    |

I'm still trying to figure out, if there is a scheme in editor count or orientation.

My findings so far: 

- Welcome-Pages, Markdown-Previews, console and Sidebar do not show this issue.
- The window has to be big (like 4000px+)
- It does not occur, if only two editor-panes are opened.
- it seem to occur, if I add at least 3 panes in horizontal order
- It does make a difference, if two of these 3 panes are also split vertically. If I have 1 on the left, 1 on the lower right and 2 above this lower right, these two will stop to render.
- If I only have 1 on the left, one on the lower right and the settings-pane above it (in the split-view like style), only the settings view is not rendered.
- If I have only 3 panes in horizontal order, they will stop rendering, but only if I expand the window way further

**Comment by bpasero** [comment] 2018-06-15 06:13
@bgraeb thanks for the response. I am still trying to understand if this is a general problem with the UI framework we are using or not. Can you give Atom Beta a try (https://atom.io/beta) to see if you see the exact same thing? They are also shipping with the same version of Electron that we are.

**Comment by bpasero** [comment] 2018-06-15 06:34
@bgraeb if you are up for a little experiment, can you:

* quit any running VSCode Insiders
* open `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\main.js`
* find the place where it reads `app.commandLine.appendSwitch("disable-mojo-local-storage");`
right after paste this: `app.commandLine.appendSwitch('force-color-profile', 'srgb');`
* save (you will need to save as admin I guess)
* start VSCode Insiders again
=> does the issue still reproduce?

**Comment by bgraeb** [comment] 2018-06-15 06:49
The change in main.js didn't fix it... I'll try if atom behaves the same, later this day. If you want, maybe we could give it a shot via Skype or something.

**Comment by bpasero** [comment] 2018-06-15 07:09
@bgraeb thanks for suggesting. in what timezone are you in? I could do a call in the afternoon (Swiss time) probably.

**Comment by bgraeb** [comment] 2018-06-15 07:11
Germany, so not way different, as far as I know ;-)

**Comment by bpasero** [comment] 2018-06-15 09:16
@bgraeb how does 4 PM sound today? My Skype alias is `bpasero`

PS: are you able to setup your machine to run VSCode out of its sources as outlined here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

That would probably make debugging a bit easier.

**Comment by bgraeb** [comment] 2018-06-15 09:59
Should work. I'll try to setup the build process.

**Comment by bpasero** [comment] 2018-06-15 14:19
Thanks, I can reproduce now. Steps:
* configure "Displays have separate spaces" to be unchecked
* log out and log in
* use the highest resolution on the mac display
* connect a secondary display
* open a VSCode window over 2 monitors all the way to the end
* open 3 splits
* make the last editor almost at the end
* notice how characters are not drawn

![image](https://user-images.githubusercontent.com/900690/41472846-edf5db56-70b7-11e8-841d-5061d8a50387.png)

**Comment by bgraeb** [comment] 2018-07-03 19:10
@bpasero Hey! Do you have an update on this?

**Comment by bpasero** [comment] 2018-07-04 06:16
No

**Comment by bpasero** [comment] 2018-07-12 15:50
Filed to Electron as https://github.com/electron/electron/issues/13648

**Comment by bpasero** [comment] 2018-08-10 17:07
Happy to say this appears to be fixed with Electron 3.0.x. Build to verify: [Download](https://az764295.vo.msecnd.net/exploration/198d785facf747b1f26234807376c6b3da09ef7a/VSCode-darwin-exploration.zip)

**Comment by attilaferencz** [comment] 2018-10-15 06:51
Downloaded new VSCode version1.28 for Windows (VSCodeUserSetup-x64-1.28.1.exe). I do not use Electron just VSCode.... Issue still persists... Does it means that actual bug was not yet fixed? Please advise.

**Comment by bpasero** [comment] 2019-01-25 16:23
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Closed by bpasero** 2019-01-25 16:23 UTC
Labels: electron, electron-2.0.x-update, fixed-in-electron-3.0.x, upstream

**Comment by attilaferencz** [comment] 2019-01-26 02:00
Great! Thanks! Works very well!
