### ISSUE TITLE
Startup Editor: newUntitledFile

### ISSUE THREAD

**Issue by georgeok** [Microsoft/vscode#72293] opened 2019-04-14 13:59 UTC
Issue Type: <b>Bug</b>

On macOS when the Workbench:Startup Editor setting seems to have no effect when set to "newUntitledFile". The result is that vscode opens with an empty editor without a new empty file. When the setting is set to the default value "welcomePage" the welcome page opens fine.

Steps to Reproduce:

1. Change settings.json to
```
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.colorTheme": "Default Light+"
}
```
2. Restart the editor
3. See the empty workbench

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (5.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aeschli** [comment] 2019-04-15 12:57
duplicate of https://github.com/Microsoft/vscode/issues/71837

This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed by aeschli** 2019-04-15 12:57 UTC
Labels: new release
