### ISSUE TITLE
JavaScript code formatting not working properly after v0.10.10

### ISSUE THREAD

**Issue by mlakmal** [Microsoft/vscode#3796] opened 2016-03-08 00:47 UTC
We are extensively using javascript auto format code feature in vs code to reduce js lint errors.
Ex: spaces after function and function name etc ...

after updating to v0.10.10 above formatting is not working any more and it reset all the formatted functions without spaces.

Can someone help or give information how to override this rule ?

var test = function() { }; //this is what new version format js code to.

but we are expecting and previously worked before like below.
var test = function () { };

**Comment by egamma** [comment] 2016-03-09 10:38
This is a duplicate of Microsoft/TypeScript#6700.

**Comment by egamma** [comment] 2016-03-10 10:26
Moving to Salsa

**Comment by egamma** [comment] 2016-03-10 10:26
This issue was moved to Microsoft/TypeScript#7459

**Closed by egamma** 2016-03-10 10:26 UTC
