### ISSUE TITLE
why vscode doesn't support large file?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#29519] opened 2017-06-27 03:16 UTC
- VSCode Version: May 2017 (version 1.13)
- OS Version: Win10

Steps to Reproduce:

1. Open a large size file, such as watch a log.
2. It report 
![image](https://user-images.githubusercontent.com/12682063/27569338-a8ec6ca4-5b29-11e7-888a-ee8ab88aaca0.png)

Reproduces without extensions: Don't care

It's really a pity, could it support edit on stream mode?

**Comment by alexandrudima** [comment] 2017-06-27 06:56
Duplicate of #6474

**Closed by alexandrudima** 2017-06-27 06:56 UTC
Labels: editor
