### ISSUE TITLE
The terminal is incorrectly detecting file URI scheme of windows paths.

### ISSUE THREAD

**Issue by jimmylab** [microsoft/vscode#137684] opened 2021-11-22 22:17 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.3 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

![vscode file uri bug](https://user-images.githubusercontent.com/6056953/142942151-25e954ee-fe86-421e-a4b5-55bcf96aa345.png)

**Comment by meganrogge** [comment] 2021-11-30 21:17
what are you expecting? that looks fine to me

**Comment by jimmylab** [comment] 2021-12-01 10:21
> what are you expecting? that looks fine to me

Are you serious?
Look at the link (underlined), the cursor (I forgot to include in screenshot) is hovering above the link.
The path should be started with drive letter **D:/abc/bcd** or **file:///D:/abc/bcd** not **/abc/bcd**. Look, it's not a linux path, okay?
It works on drive C in anyways, but it's a potential bug, click it will junp to a new tab rather than existing tab since the path has sligtly difference.
As a contrast, chrome inspector works like a charm.
![2021-12-01 18-10-52 snapshot](https://user-images.githubusercontent.com/6056953/144215358-26ed585f-4bf3-4874-a25b-8c20694ca229.png)

**Comment by meganrogge** [comment] 2021-12-01 17:12
Thanks for the additional info.
/duplicate of #129457

**Closed** 2021-12-01 17:13 UTC
Labels: needs more info, *duplicate
