### ISSUE TITLE
PowerShell ArgumentOutOfRangeException in terminal

### ISSUE THREAD

**Issue by donnie-msft** [microsoft/vscode#78967] opened 2019-08-12 16:09 UTC
Issue Type: <b>Bug</b>

Pasting this string into the Terminal causes an error: 
`RunFunctionalTests.ps1 -PMCCommand "Run-Test -Exclude Silverlight.ps1 -Verbose *>&1" | Tree-Object C:\apps\temp\artifacts\EndToEnd\FullLog_5.3.0.6131.txt" -PMCLaunchWaitTimeInSecs 30 -EachTestTimoutInSecs 600 -NuGetDropPath C:\apps\temp\artifacts -FuncTestRoot C:\apps\temp\artifacts -RunCounter 5.3.0.6131 -VSVersion 16.0`

Closed issue appears related: https://github.com/microsoft/vscode/issues/75778

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 15.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.8.29288
csharp|ms-|1.21.0
powershell|ms-|2019.5.0

</details>

**Comment by Tyriar** [comment] 2019-08-13 15:32
Same question:

> Does this also happen in the Windows Terminal preview? https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab

**Comment by donnie-msft** [comment] 2019-08-13 15:40
@Tyriar Just installed and tested, and there's no issue pasting this command into the Windows Terminal.

**Comment by Tyriar** [comment] 2019-08-13 15:43
Can you share your settings.json file?

**Comment by donnie-msft** [comment] 2019-08-13 15:49
New to VSCode... guessing what you're looking for is: C:\Users\username\AppData\Roaming\Code\User\settings.json
```
{
}
```

**Comment by Tyriar** [comment] 2019-08-13 15:53
@donnie-msft when testing with Windows Terminal can you make it quite small to match the approx dimensions of the vscode terminal?

**Comment by donnie-msft** [comment] 2019-08-13 16:00
Still works in Windows Terminal

![image](https://user-images.githubusercontent.com/49205731/62956945-d1efc400-bdc1-11e9-879d-a662ca8f0ac3.png)

**Comment by carruthe** [comment] 2019-09-16 14:11
I have the same issue.  Windows Terminal works fine for me as well.

**Comment by Tyriar** [comment] 2019-09-16 14:16
FYI @TylerLeonhardt, I've seen this reported a few times. It's likely related to xterm.js reporting something badly, eg. we report cursor position here https://github.com/xtermjs/xterm.js/blob/191932cce27ba07c687795f519186bfef6426f5b/src/InputHandler.ts#L1811-L1816

**Comment by Tyriar** [comment] 2019-09-16 14:29
From https://github.com/microsoft/vscode/issues/80987

>Microsoft Windows [Version 10.0.18362.356]

**Comment by Cobster** [comment] 2019-09-19 05:18
I was able to get around this issue by increasing the Screen Buffer Size - Width within the PowerShell console properties.  Then created a new PowerShell terminal window within VS Code.  Commands would then wrap within the terminal window instead of throwing the reported error.

**Comment by TylerLeonhardt** [comment] 2019-09-19 14:20
> Then created a new PowerShell terminal window within VS Code

This is because of the PSReadLine module that is not yet active in the stable version of the PowerShell extension (only available in the Preview I mentioned above).

**Comment by Tyriar** [comment] 2019-09-19 14:59
@donnie-msft @Cobster does this only happen in the "PowerShell Integrated Console" and not when running a plain powershell.exe/pwsh.exe terminal?

**Comment by Cobster** [comment] 2019-09-19 15:09
Yeah @donnie-msft that may have been a bad test on my part.  The error only occurred in the PowerShell Integrated Console.  After changing the buffer size I opened a plain powershell terminal window.  I'll try again.

**Comment by Cobster** [comment] 2019-09-19 15:49
Unable to reproduce, I'm not sure how I got a PowerShell Integrated Console running in the VS Code terminal.

**Comment by Tyriar** [comment] 2019-09-19 17:00
@Cobster that's the that the powershell extension provides, you can try out the preview as @TylerLeonhardt suggested to see if that fixes it https://github.com/microsoft/vscode/issues/78967#issuecomment-531813187

**Comment by Cobster** [comment] 2019-09-19 17:13
Okay @Tyriar, my misunderstanding.  The name of the terminal in Terminal drop down was PowerShell Integrated Console when I encountered the issue.  But now I only get powershell, and this doesn't seem to have a problem with line length.

![image](https://user-images.githubusercontent.com/573704/65265223-486c9980-dac5-11e9-807b-61b5a7c93056.png)

**Comment by donnie-msft** [comment] 2019-09-19 17:24
> @donnie-msft @Cobster does this only happen in the "PowerShell Integrated Console" and not when running a plain powershell.exe/pwsh.exe terminal?

This screenshot shows what I was using (Integrated Console)
https://github.com/microsoft/vscode/issues/78967#issuecomment-520897170

**Comment by Cobster** [comment] 2019-09-19 17:28
Okay, I found a way to reproduce.

1. Open VS Code
1. Open any .ps1 file (this automatically opens a terminal window titled PowerShell Integrated Console)
1. Enter a line of powershell script that exceeds the width of the terminal window. (should suceed)
1. Maximize the VS Code window
1. Enter an even longer line of text that exceeds the width of the window. (should fail)

If it doesn't repro, just keep alternating between resizing the window and entering long lines.

![image](https://user-images.githubusercontent.com/573704/65266580-2e808600-dac8-11e9-989d-e1ebd59db71a.png)

Now that I have a repro, I'll try out that fix.

**Comment by Tyriar** [comment] 2019-09-19 17:29
@TylerLeonhardt I think it's isolated to the PS extension, should we close as you say it's fixed in preview?

**Comment by TylerLeonhardt** [comment] 2019-09-20 00:30
Yeah I'm fine with that.

**Closed** 2019-09-25 19:37 UTC
Labels: bug, integrated-terminal, integrated-terminal-conpty, windows

**Comment by zionyx** [comment] 2019-10-28 12:28
For those who are hunting, the issue is described here: https://github.com/PowerShell/vscode-powershell/issues/702
