### ISSUE TITLE
Maximize window button is not working

### ISSUE THREAD

**Issue by specialforest** [microsoft/vscode#160437] opened 2022-09-08 17:49 UTC
Type: <b>Bug</b>

I cannot maximize Visual Studio Code window because the maximize button is not working.

![image](https://user-images.githubusercontent.com/581410/189191360-dac62174-4088-4501-9952-3a2181127cae.png)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.85GB free)|
|Process Argv|--crash-reporter-id d24056d4-8f5e-4caa-9100-aaefa57177cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.13.0
markdown-mermaid|bie|1.15.2
LinkCheckMD|bla|0.3.1
mermaid-markdown-syntax-highlighting|bpr|1.4.1
vscode-markdownlint|Dav|0.48.1
docs-article-templates|doc|0.2.12
docs-authoring-pack|doc|0.1.16
docs-build|doc|0.3.12
docs-images|doc|0.0.10
docs-linting|doc|0.0.12
docs-markdown|doc|0.2.113
docs-metadata|doc|1.0.8
docs-preview|doc|0.3.59
docs-scaffolding|doc|0.0.15
docs-yaml|doc|0.2.8
gitlens|eam|12.2.2
copilot|Git|1.44.6735
azure-pipelines|ms-|1.208.0
vscode-bicep|ms-|0.9.1
vscode-docker|ms-|1.22.1
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
azure-account|ms-|0.11.1
powershell|ms-|2022.8.5
azurerm-vscode-tools|msa|0.15.7
ruby|reb|0.28.1
vscode-yaml|red|1.10.1
markdown-preview-enhanced|shd|0.6.3
code-spell-checker|str|2.7.2
usql-vscode-ext|usq|0.2.15
vscode-mermaid-preview|vst|1.6.3
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by rzhao271** [comment] 2022-09-08 23:14
Duplicate of https://github.com/microsoft/vscode/issues/159851

**Closed by rzhao271** 2022-09-08 23:14 UTC
