### ISSUE TITLE
Curly braces (brackets) not auto-completing in JSX tags.

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#35197] opened 2017-09-27 04:00 UTC
- VSCode Version: 1.17.0-insider
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Create a JS file.
2. Insure 'JavaScript' is set as the file type.
3. Write a function that returns a JSX (React) component.
```jsx
const Component = () =>
  <div>
  </div>
```
4. Add an attribute to the tag, like `className`.
```jsx
const Component = () =>
  <div className={>
                  ^ Should auto-complete the curly brace, here.
  </div>
```
5. Auto-complete of curly brace also not working in interpolated strings:
```jsx
const Component = () =>
  <div className={`${`}>
                     ^ Should auto-complete the curly brace, here.
  </div>
```

Reproduces without extensions: Yes

**Comment by hnordt** [comment] 2017-09-28 09:46
Worth noting that if you type an space after `className=`, then move the cursor 1 char back and then type `{` it autocomplete the curly brace currently.

Looks like the bug happen only with props next to `>`.

**Comment by Panoplos** [comment] 2017-09-28 11:10
The second case still fails...

**Comment by Panoplos** [comment] 2017-09-28 11:16
Additionally, do you know if there is a way to set auto-completion of curly braces (or parentheses) to automatically put a space in the completion, like follows?

```
{| -> { | }
```

**Comment by mjbvz** [comment] 2017-09-30 16:19
@alexandrudima Can you please take a look at this issue? I believe it is a more general problem with autoclosing brackets. 

Here's in an html file for example:

![sep-30-2017 10-17-23](https://user-images.githubusercontent.com/12821956/31047469-33318332-a5c0-11e7-9bed-1ff7e511f074.gif)

When typing `{` immediately before the `>`, we don't autoclose the `}`. Elsewhere in the file we do

**Comment by Panoplos** [comment] 2017-10-01 04:18
Autoclose also fails in interpolated strings.

```es6
const testing = `${`
                   ^ Should complete, here.
```

**Comment by alexandrudima** [comment] 2017-10-02 07:01
Auto-closing brackets are language agnostic and use heuristics to try to do what's right. That means there will always be cases where they don't work as one would expect. Currently, a closing bracket is inserted if:
* there is no more text on the line after the cursor
* the next character is a space or a tab
* in rare circumstances, if the next character is the closing brace of another auto-closing pair which is non-symmetric.

I am open to PRs if you have good ideas on how to improve the language-agnostic heuristics of auto-closing brackets without regressing in all the other issues we closed around them. Relevant code for the auto insertion of the closing bracket:

Any change in the auto insertion of a closing bracket (`autoClosingOpenChar`) should also be reflected in the *over-type* case (`autoClosingCloseChar`)
* `_isAutoClosingOpenCharType`
* `_runAutoClosingOpenCharType`
* `_isAutoClosingCloseCharType`
* `_runAutoClosingCloseCharType`

https://github.com/Microsoft/vscode/blob/f31c369c3bd686d494cb0f01a4ed051b5e9956d0/src/vs/editor/common/controller/cursorTypeOperations.ts#L485

**Comment by Adobe-Android** [comment] 2017-10-15 18:01
I am also running into this same issue and would really love for this to be worked on!

**Comment by leozhao0709** [comment] 2017-10-19 05:36
same issue here, wish it can be fixed.

**Comment by Panoplos** [comment] 2017-10-19 05:46
I noticed that it is not just curly braces, either. single quotes, double quotes, anything really.
![autocomplete_issue](https://user-images.githubusercontent.com/2549985/31755960-3d9f387a-b4dc-11e7-9ac1-409ce45c5927.gif)

**Comment by riccoski** [comment] 2017-10-27 04:28
Indeed i'm having the same issue... It will be great if the brackets and quotes issues are fixed. Thanks

**Comment by Glitches** [comment] 2017-11-14 19:54
I think that doesn't never closes curly braces, also in plain JS.
Am I right?

**Comment by paragonbliss** [comment] 2017-11-26 13:11
Same issue. Is there any 3rd party extension that fixes this, while we wait for them to work on it?

**Comment by etiennejcharles** [comment] 2018-03-02 14:35
Has anyone found a temporary work around this issue ?

**Comment by ogzA** [comment] 2018-03-10 18:15
Nobody?

**Comment by Toisen** [comment] 2018-03-12 22:09
It's really annoying when you have to put extra space just for autocompletion. Looks like the whole autocompletion breaks: I tried to write an Angular property and Angular Language Service extension doesn't show autocompletion for it.

**Comment by Arns** [comment] 2018-03-22 04:17
I'm looking for this as well.

**Comment by Toisen** [comment] 2018-03-26 22:14
Now I'm using following keybindings while waiting for fix:
`{
        "key": "[",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus",
        "args": {
          "snippet": "[$1]"
        }
      },
      {
        "key": "shift+[",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus",
        "args": {
          "snippet": "{$1}"
        }
      }`
Same can be used for quotations. They are also not working...

**Comment by zachgibson** [comment] 2018-03-29 19:43
@Toisen your keybinding is nice but it deletes characters inside curlies if you select them and *then* press curly brace—which personally I do pretty often.

**Comment by Toisen** [comment] 2018-03-29 20:02
@zachgibson well, unfortunatelly it's far from perfect. If you need to surround selected text, then try extension called [Embrace](https://marketplace.visualstudio.com/items?itemName=mycelo.embrace). Looks like it does exactly what you want.

**Comment by fadhilfathi** [comment] 2018-04-10 08:15
@Toisen  i'm using the same keybindings as yours, do you know how to auto close "", cz its error when i use { "snippet": ""$1"" }, thx before

**Comment by chakrihacker** [comment] 2018-05-16 05:48
Can we create braces for every prop after "=", webstorm does that and it's really handy instead of typing braces by yourself

**Comment by dericgw** [comment] 2018-06-06 17:55
Until this is resolved, a snippet will have to work:
```json
"Create React prop with brackets": {
    "prefix": "pb",
    "body": [
      "${1}={${2}}",
    ],
    "description": "Create a prop with brackets"
  },
  "Create React prop with quotes": {
    "prefix": "pq",
    "body": [
      "${1}=\"${2}\"",
    ],
    "description": "Create a prop with quotes"
  }
```

**Comment by noinkling** [comment] 2018-07-06 08:41
@Panoplos 
> Additionally, do you know if there is a way to set auto-completion of curly braces (and/or parentheses) to automatically put a space in the completion, like follows?

You may be interested in the [Spaces Inside Braces](https://marketplace.visualstudio.com/items?itemName=AiryShift.spaces-inside-braces) extension.

(sorry to everyone else for only being tangentially related)

**Comment by MrLoh** [comment] 2018-07-06 16:54
Still no fix included in vscode 1.25, this is so frustrating, how can such an essential feature take so long to get fixed. I really love all the functionality vscode provides and all the effort put into it, but this is annoying every single day and there is no good workaround and all other editors, get this right. Please do something about it!

**Comment by JacksonKearl** [comment] 2018-07-10 17:44
@MrLoh we're currently discussing the best userflow for configuring when autoclosing is enabled. Right now, its only when the cursor is to the left of whitespace. #52634 as is would give the end user full control on a per language basis in their settings file. But we are also considering allowing the language extension to configure when its enabled, as this configuration is couples strongly with each language's syntax. If you have input one way or the other please do comment on that PR.

**Comment by VhMuzini** [comment] 2018-07-10 18:12
+1 on this

**Comment by BrodaNoel** [comment] 2018-07-11 16:18
+1

**Comment by Toisen** [comment] 2018-07-23 11:30
@JacksonKearl it's kinda strange that you think about thing that is already a standard in all IDEs. WebStorm doesn't ask me if I need a closing quotes, it just insert them which is totally fine. Who is that "genius" who considered that to insert space, then move a symbol back to get valuable code suggestions, is a perfect usability? Obviously it's not a feature, it's a bug.

**Comment by lavandongen** [comment] 2018-07-23 12:35
I'd like to also say that this is unexpected behaviour, and therefore a bug. I'd much rather have it always auto close. Regardless of the genius intend, and be able to turn it to only doing so with a whitespace on a per language base. Not the other way around.

Most, if not all of the language I use are much better off with auto closing tags regardless of the spaces and characters around it. This has been a constant annoyance while using VS Code. I certainly wish VS Code would react the same way as many other popular IDE's in this regard.

**Comment by peterromfeldhk** [comment] 2018-07-24 06:03
i actually stopped using vscode because of this issue (not auto closing because of trying to be smart but ending up being stupid)

**Comment by PaulPCIO** [comment] 2018-07-28 20:55
+1

**Comment by karibertils** [comment] 2018-07-29 04:05
+1

**Comment by cconcise** [comment] 2018-07-31 16:32
Coming from Webstorm I would really like to see this feature. It's def not enough to keep me from taking advantage of the awesomeness of VSCode, but it would also be really nice to see

**Comment by ashrafhadden** [comment] 2018-08-09 20:41
### Alternative Solution
`keybindings.json`
```
  {
    // wrap a selection with double quotes (")
    "key": "shift+'",
    "command": "editor.action.insertSnippet",
    "when": "editorHasSelection && editorTextFocus",
    "args": { "snippet": "\"${0:${TM_SELECTED_TEXT}}$0\"" }
  },
  {
    // wrap a selection with curly braces ({)
    "key": "shift+[",
    "command": "editor.action.insertSnippet",
    "when": "editorHasSelection && editorTextFocus",
    "args": { "snippet": "{${0:${TM_SELECTED_TEXT}}$0}" }
  }
```
_Inspired by #8536_ 
\***Caveats:** Obviously this is a global hack.

**Closed** 2018-08-22 10:38 UTC
Labels: editor-autoclosing, feature-request

**Comment by JacksonKearl** [comment] 2018-08-23 16:25
In the latest insiders, you'll find a new option for `editor.autoClosingQuotes`: `languageDefined`. This is the new default, and it uses language extensions to determine when to apply auto-closing quotes. The current heuristic is that if the following character would tend not to start expressions in a particular language, we should auto-close before it. For JS and TS we have set this to ```;:.,=}])>` \n\t```, but we may update this as feedback comes in.

**Comment by yowify** [comment] 2018-09-10 17:55
@JacksonKearl Just found the editor.autoClosingBrackets on settings. Just change it from 'languageDefined' to 'always' to make it work on react files.
