### ISSUE TITLE
MediaPlayPause

### ISSUE THREAD

**Issue by mikevanilla** [microsoft/vscode#83467] opened 2019-10-28 20:31 UTC
Issue Type: <b>Bug</b>

Using the tree navigation, select a file. Using a Pause/Play button on keyboard to pause or play media recognized by Windows OS the editor sets a search value in the tree view as 'MediaPlayPause'.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.88GB free)|
|Process Argv|C:\ccidev_data\workspaces\pmt_dev|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
path-intellisense|chr|1.4.2
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
sort-typescript-imports|mic|1.4.1
remote-wsl|ms-|0.39.9
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.1
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.9.1
vscode-icons|vsc|9.5.0
vscode-import-cost|wix|2.12.0

(2 theme extensions excluded)

</details>

**Comment by usernamehw** [comment] 2019-10-28 22:22
Duplicate of #78330

**Closed** 2019-10-29 11:03 UTC
Labels: *duplicate
