### ISSUE TITLE
javascript.suggestionActions should respect jsconfig.json

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#49243] opened 2018-05-04 19:52 UTC
- VSCode Version: 1.23.0
- OS Version: Win10x64

This is basically a continuation of #47299 but since @mjbvz locked it - I'm forced to open a new issue. I'm not asking how to disable ``suggestionActions`` altogether (maybe I need them). I want this particular one (``[js] File is a CommonJS module; it may be converted to an ES6 module.``) be disabled when it is clearly out of place like in case when I have ``"target": "es3"`` in ``jsconfig.json``.

Thank you.

**Comment by mjbvz** [comment] 2018-05-04 21:15
Duplicate of https://github.com/Microsoft/TypeScript/issues/23391

Insiders builds only enable this suggestion when you configure `module` to something other than `commonJS`

**Closed by mjbvz** 2018-05-04 21:15 UTC
Labels: new release
