### ISSUE TITLE
After i used the new version 10 mins , i download back my old brown version

### ISSUE THREAD

**Issue by MBWu** [Microsoft/vscode#39224] opened 2017-11-28 03:20 UTC
**# old brown version**
![2017-11-28 11 11 56](https://user-images.githubusercontent.com/23426359/33300871-91c1fd46-d42d-11e7-9c0b-ee3813c87854.png)

**# new blue version**
![2017-11-28 11 12 54](https://user-images.githubusercontent.com/23426359/33300904-bf5d818a-d42d-11e7-8871-5aba518c1aaa.png)

 **# old brown version**
![2017-11-28 11 13 16](https://user-images.githubusercontent.com/23426359/33300920-d9d4cce4-d42d-11e7-93f5-20e2eadc61bd.png)

**# new blue version**
![2017-11-28 11 15 04](https://user-images.githubusercontent.com/23426359/33300930-e4ac4552-d42d-11e7-970a-8eb7eda3a39b.png)

using old version , i don't need to find some tags props, if i use new version , i will work slowly

**Comment by mjbvz** [comment] 2017-11-28 17:48
Please share some example code and some steps to reproduce the problem. Also does this reproduce if you disable all of your installed extensions?

**Comment by mjbvz** [comment] 2017-12-05 17:46
Closing as not actionable without more information on what the problem is and how to reproduce it

**Closed by mjbvz** 2017-12-05 17:46 UTC
Labels: needs more info
