### ISSUE TITLE
Can't `Go to Definition` for a module path inside script tag

### ISSUE THREAD

**Issue by ris58h** [microsoft/vscode#191465] opened 2023-08-28 14:15 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.1
- OS Version: macOS Ventura 13.4.1

Steps to Reproduce:

1. Open a HTML file with script tag that imports something from other module.
2. Try to  perform `Go to Definition` action for the specified module path.

Example:

```JavaScript
<script type="module">
  import * as foo from "./bar.js"
</script>
```

`Go to Definition` action on `./bar.js` string doesn't work and the string is not highlighted when it's hovered with `Cmd` (`Ctrl`) pressed.

**Comment by aeschli** [comment] 2023-08-29 09:25
Yes, the built-in HTML support does not follow import.

Duplicate of https://github.com/microsoft/vscode/issues/114115

**Closed by aeschli** 2023-08-29 09:25 UTC
