### ISSUE TITLE
Minimap disappears on window resize

### ISSUE THREAD

**Issue by Thomastasa** [Microsoft/vscode#44287] opened 2018-02-23 17:15 UTC
Resizing the window causes the minimap content to disappear if the window size is larger than the initial size.  If you resize it back smaller, it reappears.  Also if you Toggle Word Wrap OFF, the minimap isnt hiding the overflow of text.

Initial window size shows minimap content, with Word Wrap: ON:
![screen shot 2018-02-23 at 9 05 55 am](https://user-images.githubusercontent.com/3993456/36606550-e4037136-1878-11e8-9803-83a460b8e562.png)

Resized window doesn't show minimap content, with Word Wrap: ON:
![screen shot 2018-02-23 at 9 06 05 am](https://user-images.githubusercontent.com/3993456/36606551-e427e958-1878-11e8-93ec-e82cc0d65532.png)

On a resized window, with Word Wrap: OFF, overflowed text is still visible underneath the minimap
![screen shot 2018-02-23 at 9 11 00 am](https://user-images.githubusercontent.com/3993456/36606741-7c42eb5c-1879-11e8-8aab-c15ce8a9a193.png)

---

- VSCode Version: Version 1.20.1 (1.20.1)
- OS Version: OSX El Capitan - Version 10.11.6

Steps to Reproduce:
1. Resizing vscode window larger than initial size
2. Toggle Word Wrap

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment] 2018-02-26 08:19
@Thomastasa I cannot reproduce:

![kapture 2018-02-26 at 9 17 14](https://user-images.githubusercontent.com/5047891/36659790-efd28cb8-1ad5-11e8-8ba9-b26f950f1fc1.gif)

Does this always reproduce for you? 
Do you have an exception in the console? `F1 > Developer: Toggle Developer Tools`
Do you have an exception in your logs? `F1 > Developer: Open Logs Folder`

**Comment by Thomastasa** [comment] 2018-02-26 19:57
Yes the bugs are still being reproduced for me. 
There are no errors in the developer tools console.
Im not too familiar with the vscode logs, but nothing said exception.  
I even triple checked to make sure all extensions were disabled. It even glitches on the auto-generated log files.

Let me know if you need to to try anything else, or send u any other info.  This is a weird bug, and im not sure why its happening, but it has been happening in the past a few months for me.

**Comment by Thomastasa** [comment] 2018-02-26 22:38
Playing around with the window size, i found that it starts glitching when at least 30 lines tall.  

The width and height it glitches seems to be different each time.  I've counted the breaking point to be 118 characters wide on one, and 82 characters wide on another. I've also counted breaking heights of 48 lines tall, and 36 lines tall.

@alexandrudima, your test was only 20 lines tall, can you see if it glitches when you make the window taller?

**Comment by alexandrudima** [comment] 2018-02-27 13:04
@Thomastasa this is most weird. I cannot reproduce, even when using a very small font size (75 lines tall viewport)

Logically, painting the minimap can be influenced by various things:
1. file content
2. theme
3. minimap settings from user settings.

So, I wonder if this reproduces with any file, with any theme, and with default minimap settings ?

Otherwise, it might have something to do with GPU memory. The minimap is backed by a canvas, which requires GPU memory... Does this reproduce when launching `code --disable-gpu` ?

**Comment by Thomastasa** [comment] 2018-02-27 21:12
Still glitchy.
I tested with gpu disabled, made new files, nothing in my User Settings, and on multiple themes.
I might just have to live with a glitchy minimap. -_-

**Comment by alexandrudima** [comment] 2018-02-28 09:48
@Thomastasa 

Does this reproduce also when using Chrome on your machine if you look at the editor at https://microsoft.github.io/monaco-editor/ or https://microsoft.github.io/monaco-editor/playground.html ?

**Comment by Thomastasa** [comment] 2018-02-28 20:51
Nope, it doesn't glitch when using either of those sites.

**Comment by alexandrudima** [comment] 2018-03-01 09:43
I'm running out of ideas...

Here is an upstream bug I found, but that was on Linux -- https://bugs.chromium.org/p/chromium/issues/detail?id=483515&q=canvas%20empty&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

In there they are asking if a page reload helps. For us, you can try `F1 > Reload Window`.

**Comment by Thomastasa** [comment] 2018-03-01 20:46
No luck.  Reloading the window didn't change anything.

**Comment by Thomastasa** [comment] 2018-03-02 21:16
I think we figured out the source of the problem.
According to the FPS meter my GPU Raster is ``off(device)``.  After some quick googling, i found that chrome has issues with my graphic card (as seen in the second image) and therefore has disabled some features of rastering. I'm guessing those features are being used by vscode to render the minimap.

Please let me know if there is any other ideas you have now that we know this tidbit of info.
Thanks again for all your help @alexandrudima :) 

![screen shot 2018-03-02 at 1 07 57 pm](https://user-images.githubusercontent.com/3993456/36921875-ca7cc382-1e1a-11e8-8932-fc112af14614.png)



![screen shot 2018-03-02 at 1 06 26 pm](https://user-images.githubusercontent.com/3993456/36921820-92293d3a-1e1a-11e8-9ee0-4c5bdd62b3e4.png)

**Comment by alexandrudima** [comment] 2018-03-05 11:07
@Thomastasa 

I think you should open an issue against [Chromium](https://bugs.chromium.org/p/chromium/issues/list) and ask them for guidance. IMHO, `<canvas>` elements should be painted fine even if GPU acceleration is disabled/not used, but they can confirm or infirm that. i.e. I believe they have a fall-back software renderer which might have a bug in this case.

But it is difficult if you don't have a case that reproduces in Chrome. Do these websites which make heavy use of `<canvas>` run fine for you? e.g. http://brm.io/matter-js/demo/#sprites

I will close this for now, as there is nothing I can do on our side to fix this.

**Closed by alexandrudima** 2018-03-05 11:07 UTC
Labels: editor-minimap, mac, needs more info

**Comment by Thomastasa** [comment] 2018-03-05 20:36
I will just live with it for now. 

Canvas is working fine in chrome (neat link btw) and vscode hasn't had any issues with the minimap on any of my other 3 computers (macbook pro, win10 laptop,  win10 desktop).  

Thanks again for all your help @alexandrudima 
Keep up the good work :)
