### ISSUE TITLE
`editor.experimentalEditContextEnabled` doesn't work well with Google IME's suggestion handling

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#228627] opened 2024-09-14 10:28 UTC
Version: 1.94.0-insider
Commit: f4746c94726e157c9b6534f1355d163ca4efcb38
Date: 2024-09-13T05:04:25.154Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Set `"editor.experimentalEditContextEnabled": true`
2. Enable Google IME for Japanese.
3. Type `sennseikonnnitiha`
4. Type `Space` repeatedly.
5. The result is unexpected one. Suggestions by Google IME repeats, and VS Code Insiders doesn't handle it properly. The expected one is just `先生今日は`.

https://github.com/user-attachments/assets/9cb8fa6b-a826-42a1-9f45-c4f6de4e6119

**Comment by aiday-mar** [comment] 2024-09-18 14:40
I tried to install Google IME on Mac but it does not show up in the keyboard inputs after installation. I am on Sonoma 14.6.1. Instead I verified this issue happens on Windows where I had Google IME configured. Since I dont speak Japanese it was a bit difficult to know what results are expected on typing `sennseikonnitiha`. On the latest Insiders on Windows I see the following. I don't speak Japanese, so I can't comment on the results, but the insertions of text seem to be correct.

Perhaps I am not reproducing correctly. Could I ask you if you could do the following?

- Test on the latest Insiders with Google IME
- If the above does not work, then what you are seeing could be a chromium bug. In that case could you:
  - go to Chrome (the browser)
  - upgrade Chrome to the latest version
  - go to insiders.vscode.com
  - verify if the bug is reproduced?

VS Code is based on Chromium which backs Chrome and on you updated browser, most chromium bugs relative to the EditContext should be fixed. 

https://github.com/user-attachments/assets/5dbf6a7a-62eb-4db7-a831-739dd57e7f0a

**Comment by tamuratak** [comment] 2024-09-18 22:42
I can reproduce the issue on `insiders.vscode.dev` on macOS with the latest Google Chrome. However, I can NOT reproduce it on `insiders.vscode.dev` on Windows 10. So, the behavior of EditContext might be different on platforms.

Version: 1.94.0-insider
Commit: 4f485cf59847506bc1ba2aaab127d31dcbe2c9dc
Date: 2024-09-18T09:24:10.356Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

Google Chrome: 129.0.6668.59（Official Build） （arm64）
ProductName:		macOS
ProductVersion:		13.7
BuildVersion:		22H123

The result is totally wrong. For example, you can see the number of tha last character `は` increases, which should never happen.

https://github.com/user-attachments/assets/3ce29dee-5c79-44ce-92f1-4b909db75c89

**Comment by tamuratak** [comment] 2024-09-18 22:53
I can reproduce the similar issue with macOS Japanese IME.

Version: 1.94.0-insider
Commit: 4f485cf59847506bc1ba2aaab127d31dcbe2c9dc
Date: 2024-09-18T09:24:10.356Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

Google Chrome: 129.0.6668.59（Official Build） （arm64）
ProductName:		macOS
ProductVersion:		13.7
BuildVersion:		22H123
IME: macOS Japanese IME

1.  Set `"editor.experimentalEditContextEnabled": true`
2. Enable Google IME for Japanese.
3. Type `sennseikonnnitiha`
4. Type ↑ and ↓ repeatedly.

When the number of characters of the suggested item changes, from 2 to 4, and from 4 to 2, the issue seems occur.

https://github.com/user-attachments/assets/e217fa8d-8bc4-4f76-994e-f168e5c8625a

**Comment by aiday-mar** [comment] 2024-09-19 09:53
Hi, I have finally been able to configure IME on MacOS Sonoma with the link: https://support.google.com/gboard/thread/295827358/%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E5%8F%AF%E8%83%BD%E3%82%82%E4%BD%BF%E3%81%88%E3%81%AA%E3%81%84%E3%80%82?hl=ja

I have chosen Google Japanese Hiragana, and have enabled the edit context. After reloading, I type `sennseikonnitiha` and get the following input. I use the up and down arrow keys, the text edits seem to be correct? Not sure about the results however.
 
https://github.com/user-attachments/assets/35d4a73e-b5c3-4d8d-9c92-9b9a4a2e8c27

**Comment by aiday-mar** [comment] 2024-09-19 09:56
On Insiders I get the following which also seems to be correct?

https://github.com/user-attachments/assets/f0fb095a-b96b-4e55-b9d3-1ce668ffd7b1

**Comment by aiday-mar** [comment] 2024-09-19 09:57
Perhaps this is related to the Google IME version you have installed on your macos

**Comment by tamuratak** [comment] 2024-09-19 12:59
You have to type `sennseikonnnitiha`, not `sennseikonnitiha`. Type `n` three times after `o`.

My Google IME Version is `2.30.5590.1`, which is the latest one:

https://support.google.com/gboard/thread/297446227/macos%E7%94%A8%E3%81%AEgoogle%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B%E3%81%AE%E6%9B%B4%E6%96%B0?hl=ja&sjid=10171189176188130155-AP

**Comment by aiday-mar** [comment] 2024-09-19 13:19
I see thank you. Typing with three still seems to work. I have installed japanese google ime yesterday so I suppose its the latest (not sure where to find the version number within the config dialog). 

https://github.com/user-attachments/assets/e41ccc1d-1769-4301-a856-bbf3099b3b29

**Comment by aiday-mar** [comment] 2024-09-20 15:01
Hi @tamuratak today I have been working on an issue that VS Code Vim users were seeing with the edit context enabled. While working on a fix, I have noticed some strange behavior in the editing experience while doing composition. The following PR which aims to fix the issue with VS Code Vim users, also fixes the composition issues I was seeing : https://github.com/microsoft/vscode/pull/229129. I am thinking that perhaps with this PR, I may have fixed the bug you described in this issue. When the next Insiders release comes out, could you let me know if you continue seeing issues on composition?

**Comment by tamuratak** [comment] 2024-09-23 00:02
Version: 1.94.0-oss-dev
Commit: 684f9d47a4a97d7ea747915f4d1595f86f98aaad
Date: Sat Sep 21 18:10:48 2024 -0700
Electron: 30.5.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

I checked the OSS build from the repository. The PR seems fix the issue. However, it has introduced a different issue:

1.  Set `"editor.experimentalEditContextEnabled": true`
2. Enable Google IME for Japanese.
3. Type `sennseikonnnitiha`
4. Type `Space`.
5. Type → repeatedly.


https://github.com/user-attachments/assets/bbecdb0d-b7b9-49d2-b4f4-47102adf09bc

The following patch seems fixed the new issue although I cannot say I understand the whole logic.

```diff
diff --git a/src/vs/editor/browser/controller/editContext/native/nativeEditContext.ts b/src/vs/editor/browser/controller/editContext/native/
nativeEditContext.ts
index 0c12ff5fe6f..5b33019510d 100644
--- a/src/vs/editor/browser/controller/editContext/native/nativeEditContext.ts
+++ b/src/vs/editor/browser/controller/editContext/native/nativeEditContext.ts
@@ -188,14 +188,14 @@ export class NativeEditContext extends AbstractEditContext {
 
                const previousSelectionStartOffset = this._previousEditContextSelection.start;
                const previousSelectionEndOffset = this._previousEditContextSelection.endExclusive;
-
+               const cursorStart = this._context.viewModel.getCursorStates()?.[0].viewState.selection.startColumn - 1;
                let replaceNextCharCnt = 0;
                let replacePrevCharCnt = 0;
                if (e.updateRangeEnd > previousSelectionEndOffset) {
                        replaceNextCharCnt = e.updateRangeEnd - previousSelectionEndOffset;
                }
-               if (e.updateRangeStart < previousSelectionStartOffset) {
-                       replacePrevCharCnt = previousSelectionStartOffset - e.updateRangeStart;
+               if (e.updateRangeStart < cursorStart) {
+                       replacePrevCharCnt = cursorStart - e.updateRangeStart;
                }
                let text = '';
                if (previousSelectionStartOffset < e.updateRangeStart) {
```

- https://github.com/tamuratak/vscode/tree/fix_editcontext_leftright_b

**Comment by aiday-mar** [comment] 2024-09-23 07:52
Hi thanks for letting me know of this new issue. Unfortunately we can not use directly the selection start column because this would break extension authors like VS Code Neovim. I will have try to reproduce this issue and find a fix.

**Comment by tamuratak** [comment] 2024-09-23 08:17
I see. I can reproduce the same issue with the latest VS Code Insiders:

Version: 1.94.0-insider
Commit: 1926933184de3f77ac7176e9fc302c54bd9634b0
Date: 2024-09-23T05:12:01.964Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

**Comment by aiday-mar** [comment] 2024-09-23 08:56
Hi thanks a lot again for the issue. I believe I have found a fix for your given issue here https://github.com/microsoft/vscode/pull/229347, that should both fix your issue and keep extensions working correctly. With this fix could I ask you later if you could verify if the edit context works correctly? Thanks again.

**Comment by tamuratak** [comment] 2024-09-23 10:11
I have confirmed that both issues are fixed. Thank you.

**Comment by aiday-mar** [comment] 2024-09-23 10:44
Thank you. I will close this issue.

**Closed by aiday-mar** 2024-09-23 10:44 UTC
Labels: bug, editor-edit-context
