### ISSUE TITLE
Destructured arrow function arguments not recognized on multiple lines

### ISSUE THREAD

**Issue by markypython** [Microsoft/vscode#69203] opened 2019-02-22 11:27 UTC
Issue Type: <b>Bug</b>

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.26
vscode-eslint|dba|1.8.0
es7-react-js-snippets|dsz|2.0.1
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.25
python|ms-|2019.1.0
java|red|0.39.0
vscode-icons|rob|8.2.0
code-settings-sync|Sha|3.2.5
trailing-spaces|sha|0.2.11
vscode-checkstyle|she|1.0.0
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

Steps to Reproduce:

1. Create an arrow function with arguments destructured on multiple lines
2. Inspect TM scopes of destructured arguments
3. Note that arguments are scoped as `variable.other.readwrite.js` rather than `variable.parameter.js`.

_Note: This does not occur when using the `function` keyword_ 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2019-02-22 20:53
Please share some example code. This is likely a duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/540

**Comment by markypython** [comment] 2019-02-23 01:43
The following code demonstrates my issue.  It occurs for both JavaScript and TypeScript.

```js
const fn = ({
  arg
}) => {
  console.log(arg)
}

const fn = ({ arg }) => {
  console.log(arg)
}
```

**Comment by mjbvz** [comment] 2019-02-25 22:13
Thanks. Yes I believe this is a duplicate of [Microsoft/TypeScript-TmLanguage#540](https://github.com/Microsoft/TypeScript-TmLanguage/issues/540) which has been marked wont fix upstream

**Closed by mjbvz** 2019-02-25 22:13 UTC
Labels: needs more info
