### ISSUE TITLE
Hide __proto__ during JavaScript debugging

### ISSUE THREAD

**Issue by dandv** [microsoft/vscode#60478] opened 2018-10-10 08:55 UTC
I wanted to :+1: #19950 (because I've never needed to see the `__proto__` in 10+ years of debugging JS), but the issue wasn't just closed, it was locked.

I understand the idea behind keeping the number of issues maintainable, but locking issues leads to unnecessary duplicates like this one.

**Comment by bittnkr** [comment] 2019-09-04 01:06
Thumbs up.
It would be wonderfull to hide [[StableObjectId]] altogether. Both are just two annoying distractions when debugging node/js with vscode.

**Comment by roblourens** [comment] 2019-10-07 18:35
/duplicate of https://github.com/microsoft/vscode/issues/54125

**Closed** 2019-10-07 18:35 UTC
Labels: *duplicate, debug, feature-request
