### ISSUE TITLE
version number in .rpm file name

### ISSUE THREAD

**Issue by cg-cnu** [Microsoft/vscode#7289] opened 2016-06-07 03:19 UTC
Is it possible to have a version number and release tag for the .rpm files. 
Makes it easy to keep track and update the versions.

**Comment by Tyriar** [comment] 2016-06-07 07:39
@cg-cnu the insiders build should be available with the version number tomorrow I think :)

Closing as duplicate of https://github.com/Microsoft/vscode/issues/6587

**Closed by Tyriar** 2016-06-07 07:39 UTC
