### ISSUE TITLE
Electron Helper draws 100% CPU

### ISSUE THREAD

**Issue by troplin** [Microsoft/vscode#7558] opened 2016-06-11 11:48 UTC
- VSCode Version: 1.2.0
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Start VS Code
2. Open project folder

Electron Helper process draws 100% CPU as soon as I open a project folder. GUI is still responsive though.

Somehow I suspect that this has something to do with the git pane (**the project is managed by mercurial, not by git!**):

- Open the project -> CPU usage goes to 100% for ~3 minutes
- Git icon shows badge "99+" -> CPU usage falls down to a reasonable level
- After some seconds, CPU usage rises again to 100% for ~4 minutes
- CPU usage is again at a reasonable level

Then, after a make any modification to a file, the git badge switches to a clock icon and after a few seconds it starts again drawing 100% CPU.

**Comment by bpasero** [comment] 2016-06-11 15:07
@troplin we have received some reports on this issue already and have some advice and questions:

* can you please let us know if this reproduces in Code 1.1 already (download from: https://az764295.vo.msecnd.net/stable/def9e32467ad6e4f48787d38caf190acbfee5880/VSCode-darwin-stable-unsigned.zip)
* you can verify this is git by quickly disabling git from settings (`git.enabled` and a restart of Code)
* do you happen to have a `.git` folder somewhere in the parent chain of the folder you are opening?

Thanks!

**Comment by troplin** [comment] 2016-06-11 15:22
1. Will try the old version later, but I just updated to 1.2 and I think I would have noticed if it behaved like this before.
2. Yes, if I disable git it goes away.
3. Yes, the parent directory contains a `.git` folder. That's strange because this doesn't make any sense, I must have created it by accident.

**Comment by troplin** [comment] 2016-06-11 15:44
The orphaned `.git` directory was the culprit. I've deleted it and now everything is fine. It probably also explains the problems that I have with the mercurial plugin in Atom Editor sometimes working and sometimes not.

Thanks a lot for the hint!

Still, VS Code should not consume so much CPU. A `git status` on the parent directory is instantaneous. Do you scan the entire file tree on each file modification?

**Comment by bpasero** [comment] 2016-06-11 16:54
@troplin yes we are working on a fix for this. what is not so clear is what changed in 1.2 that makes this more obvious...

**Comment by joaomoreno** [comment] 2016-06-13 10:25
Closing as duplicate of #6026, moving the discussion there

**Closed by joaomoreno** 2016-06-13 10:25 UTC
Labels: candidate, freeze-slow-crash, git, important
