### ISSUE TITLE
在提交git更改的时候不能打字，只能reload

### ISSUE THREAD

**Issue by evilArsh** [microsoft/vscode#113804] opened 2021-01-05 08:36 UTC
Issue Type: <b>Bug</b>

cannot type when using Chinese PinYin

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|20%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|12.1.0
vscode-markdownlint|Dav|0.38.0
githistory|don|0.6.14
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.64
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
code-runner|for|0.11.1
vscode-pull-request-github|Git|0.22.0
go|gol|0.20.1
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.52.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
vscode-typescript-tslint-plugin|ms-|1.3.2
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
material-icon-theme|PKi|4.4.0
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.12

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/20971355/103624084-fe3a5080-4f73-11eb-932a-0f14e37f76b3.png)
when i am inputing some message before commit a change,the input box cannot be focus and i cannot typing, i am using Chinese Pinyin

**Comment by evilArsh** [comment] 2021-01-05 09:04
when i am inputing some message before commit a change,the input box cannot be focus and i cannot typing, i am using Chinese Pinyin

**Comment by yume-chan** [comment] 2021-01-05 17:16
Duplicate of #112621

**Closed** 2021-01-08 03:19 UTC
Labels: *english-please, needs more info, translation-required-chinese-simplified
