### ISSUE TITLE
Japanese IME doesn't work well with bold styles

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#156940] opened 2022-08-02 22:47 UTC
Version: 1.70.0-insider (Universal)
Commit: e9bda7aa4ff76648cfccc1a7bde465443803da71
Date: 2022-08-02T16:58:00.575Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0

Japanese IME doesn't work well with bold styles.

Steps to Reproduce:

1. Open a markdown file.
2. Enable a Japanese IME.
3. Write `****`
4. In the middle of `****`, input `senseikonnnitiha`

The issue occurs with Apple Japanese IME and Google IME.

https://user-images.githubusercontent.com/10665499/182485905-7fba2dea-3fcc-477d-9da7-d3caf2e91bb8.mov

**Comment by aiday-mar** [comment] 2024-09-05 10:48
Hi are you still seeing this issue? I assume the issue is that there is a blinking effect. I am currently not able to reproduce this issue. 

https://github.com/user-attachments/assets/7f1c1cce-b6a8-45ca-925f-a7c479e87cc1

**Comment by tamuratak** [comment] 2024-09-05 14:08
I still see the issue.


https://github.com/user-attachments/assets/c5a80203-2831-44ef-ad7a-f5bb974d68e8



Version: 1.93.0-insider
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:13:15.344Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

**Comment by aiday-mar** [comment] 2024-09-09 11:41
Hi @tamuratak thank you for filing this issue. I suppose the issue is that the text is blinking as you are typing, please correct me if I am wrong. If this is indeed the issue then this should be fixed now with the experimental setting `editor.experimentalEditContextEnabled`. This issue will be closed.

**Closed by aiday-mar** 2024-09-09 11:41 UTC
Labels: bug, info-needed, editor-input-IME

**Comment by tamuratak** [comment] 2024-09-09 22:21
I confirm that the issue is fixed with `editor.experimentalEditContextEnabled : true`. Thank you.

Version: 1.94.0-insider
Commit: dc9412125d4e0a480593962ae2687e74e64af728
Date: 2024-09-09T17:10:54.809Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
