### ISSUE TITLE
Not all presentationoptions are honored on task api

### ISSUE THREAD

**Issue by kevindiclemente** [Microsoft/vscode#67321] opened 2019-01-29 06:44 UTC
In the repro below, reveal, focus and isbackground are not honored when set, and the terminal is displayed to the ui:

                       let shellOptions: vscode.ShellExecutionOptions = {
				executable: metaData.terminalPath,
				shellArgs: [
					"/c",
				]
			};

			let buildTask = new vscode.Task(
				buildDefinition,
				folders[0],
				'sample name',
				'sample source',
				new vscode.ShellExecution(
					"echo hello",
					shellOptions
				)
			);

			buildTask.isBackground = true;
			buildTask.presentationOptions = {
				echo: true,
				reveal: vscode.TaskRevealKind.Never,
				focus: false,
				panel: vscode.TaskPanelKind.Shared,
				showReuseMessage: false,
				clear: true
			};

			vscode.tasks.executeTask(buildTask);

**Comment by alexr00** [comment] 2019-01-29 10:44
Are you using the stable release or the insiders release? If stable, this is a duplicate of #66749 which is fixed in insiders.

**Closed** 2019-01-29 10:44 UTC
Labels: *duplicate, tasks

**Comment by kevindiclemente** [comment] 2019-01-29 16:08
Woo! I’ll try on insiders later today :) thanks!
