### ISSUE TITLE
VSCode fails to clear errors after they are fixed

### ISSUE THREAD

**Issue by jwmurray** [microsoft/vscode#63244] opened 2018-11-15 22:04 UTC
- VSCode Version: 1.30.0-insidere
- OS Version: Windows 10 Professional 
connected to Linux server

Steps to Reproduce:

1. Mount a Linux server's code directory as a mapped drive on Windows 10 (e.g. z:\code\bash_development)
2. Create a bash shell script which calls a second bash shell script
e.g. Make.sh which calls mysrcript.sh
3. Create a bug in myscript.sh
4. Use a tasks.json file with build task which makes an ssh call from windows to the Linux server to run Make.sh which then calls the buggy myscript.sh.
5. Confiugure the tasks.json task to scan for the problems in the terminal output -- which then locates the bug in myscript.sh and allows the user to click on the bug line and to be take directly to the offending line in myscript.sh.
6. Fix the bug
7. Rerun the build task
8. The problems list still shows the bug, but there is no bug.

The same would happen if the line were deleted from myscript.sh.

----------------tasks.json----------------------------

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "windows": {
                "command": "c:/code/bash_development/make.sh"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner" : "cpp"
                ,"fileLocation": [
                    "relative"
                    ,"${workspaceFolder}"
                ]
                ,"pattern": {
                    "regexp": "(.*?): line (\\d+)(.*)['`\"]*"
                    ,"file": 1
                    ,"line": 2
                    ,"message": 3
                }
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new",
                "showReuseMessage": true
            }
        }

    ]
}
`
-------------------Make.sh---------------------
`    #/bin/env bash

    ./myscript.sh`

------------------myscript.sh-----------------------

`#!/bin/env bash

setup ()
{
        echo "Inside setup"
}

foo =10
echo ${foo} 
echo $((2 +2))

setup5  #  Run once like this, go to the problems tab, then remove teh '5' and run again and go to the problems tab.

foo =10
echo ${foo} 
echo $((2 +2))

setup`
------------------ end of files -------------

Does this issue occur when all extensions are disabled?: Yes

**Comment by jwmurray** [comment] 2018-11-15 22:12
No. This relates to a script that calls script.  The second script is not properly accounted for in the problems tab once a bug in the second script has been fixed.

This relates to a windows version of VSCode calling the script via an ssh call to a Linux server, locating the bug i the terminal output, then parsing that output to locate the bug in the problems tab.

**Comment by alexr00** [comment] 2019-03-28 14:12
Here's what I used:
-------myscript.sh--------
````shell
setup()
{
    echo "Inside setup"
}
setup5
setup
````
--------Make.sh-------
````shell
./myscript.sh
````
------task----
````json
{
            "label": "build",
            "type": "shell",
            "command": "${workspaceFolder}/Make.sh",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}"
                ],
                "pattern": {
                    "regexp": "(.*?): (\\d+)(.*)['\"]*",
                    "file": 1,
                    "line": 2,
                    "message": 3
                }
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new",
                "showReuseMessage": true
            }
        }
````
I ran once, saw the problem with `setup5`. I fixed the problem, then ran again. Problem was cleared from Problems pane.
I was not able to reproduce the issue. Do you have any other repro steps?

**Comment by robrecord** [comment] 2019-04-08 10:26
This is happening for me in JSON

Literally as I type, it checks for problems and reports a new one with the latest version of what I typed. I can see my typing history in the problems view, and it is not cleared.

<img width="353" alt="Screenshot 2019-04-08 at 11 26 03" src="https://user-images.githubusercontent.com/38916/55717379-22f54300-59f1-11e9-8e74-a99a8123cbec.png">

You can see I was typing the word "description" above.

**Comment by alexr00** [comment] 2019-05-21 14:37
@robrecord, please file a separate issue for that since it is not related to tasks.

**Comment by alexr00** [comment] 2019-05-21 14:38
Closing since I cannot reproduce with a script that runs another script.

**Closed by alexr00** 2019-05-21 14:38 UTC
Labels: bug, needs more info, tasks
