### ISSUE TITLE
The `Explorer` icon disappeared after going to `Debug`

### ISSUE THREAD

**Issue by qzhou1607** [Microsoft/vscode#41833] opened 2018-01-18 23:14 UTC
- VSCode Version: 1.19.2
- OS Version: Windows 10 build 16299

Steps to Reproduce:

1. Open an existing folder in VS code
2. Click on `Debug` icon on the left

The `explorer` icon is gone, and unless the `CTRL + Shift + E` shortcut is used, there is not way to get back to the folder structure. Is this an intended change?

![vscode](https://user-images.githubusercontent.com/20218531/35126374-fc5d9438-fc61-11e7-8418-58dcec988d2e.PNG)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment] 2018-01-19 02:03
please try to right-click on the space under the Debug icon, a menu should appear to allow you to choose which icons to show.

**Comment by isidorn** [comment] 2018-01-19 09:51
@qzhou1607 yes please use the right click to bring back the explorer
This is a duplicate of a fixed issue, so once you bring back the views it should no longer happen since you have vscode that has the fix. Sorry about that

**Closed by isidorn** 2018-01-19 09:51 UTC
Labels: *duplicate, workbench-layout
