### ISSUE TITLE
Font in hover for custom trees is too large

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#109444] opened 2020-10-27 08:21 UTC
Please see the screenshot below

![image](https://user-images.githubusercontent.com/172399/97275042-bc838000-1835-11eb-814e-652feb2e5f54.png)

**Comment by alexr00** [comment] 2020-10-27 10:24
@Tyriar in case you have any suggestions for what to do here.

@misolori I think the font size in the hover is consistent with the font size in all hovers. I'm not sure how to reconcile that with the tree font size.

**Comment by egamma** [comment] 2020-10-27 10:54
@alexr00 

>I'm not sure how to reconcile that with the tree font size.

I haven't described my perception correctly, my perception is less that the font size is not aligned with the font size of the tree item. My perception is that the font of the issue hover description is too large. The description in a Code hover appears to use a smaller font. Therefore I suggest to use the same font size as in the code hover.

![image](https://user-images.githubusercontent.com/172399/97292061-0a56b300-184b-11eb-8b0c-1b686a27a76d.png)

**Comment by misolori** [comment] 2020-10-27 15:08
Duplicate of https://github.com/microsoft/vscode/issues/107278?

**Comment by alexr00** [comment] 2020-10-27 15:18
Yes, duplicate of https://github.com/microsoft/vscode/issues/107278, thanks!

**Closed** 2020-10-27 15:18 UTC
