### ISSUE TITLE
"ext install" broken on Insiders build

### ISSUE THREAD

**Issue by zethon** [Microsoft/vscode#8021] opened 2016-06-22 21:18 UTC
- VSCode Version: b985edc9f5441678cf071fc7925a569e623e7431
- OS Version: OSX

Experienced this on 2 different Macs today. Got the usual notice asking me to if I wanted to "Update Now" by restarting Visual Code. Restarted and once I restart, I'm asked the same question again. Once again, I restarted Visual Code. After this "ext install" says "No results found" even if I try extensions I know should work ("ext install c++", "ext install cmake"). 

I noticed this by luck on one Mac earlier this morning. I thought I had screwed up my install somehow, but now that I see it on two different Macs I believe it's a bug with Visual Studio Code.

**Comment by ismail** [comment] 2016-06-23 04:59
Possibly a duplicate of #8023

**Comment by joaomoreno** [comment] 2016-06-23 07:56
Definitely a duplicate.

**Closed by joaomoreno** 2016-06-23 07:56 UTC
Labels: extensions
