### ISSUE TITLE
Red dot from debug works weird in 1.18.0

### ISSUE THREAD

**Issue by ZZYSonny** [Microsoft/vscode#37914] opened 2017-11-09 10:05 UTC
- VSCode Version:1.18.0
- OS Version: Windows 10 16299.19 and Mac OS 10.13.1
Reproduces without extensions: To show the issue,  I have to launch my program.

Steps to Reproduce:
1. add breakpoints before debugging
2. The issues mostly happens when deleting breakpoints when the program stops at any breakpoints. Deleting breakpoints when the program is not running sometimes trigger this issues.

It also deletes one of the other breakpoints( mostly next line). Usually for my Windows. 
The breakpoints are deleted and program no longer stops there. But the dots are still shown. Usually for my Mac, sometimes for my Windows.

When I restart VSCode, the dots are not showing any more.

The points are still shown with no breakpoint on the left side
The issues happens on both C++ and Java, so it shouldn't be the problem of extensions.
![image](https://user-images.githubusercontent.com/28442838/32599427-797a4d48-c577-11e7-8462-b1c713e97fd1.png)
![image](https://user-images.githubusercontent.com/28442838/32600049-448c438c-c579-11e7-89a1-37251ae489bb.png)

**Comment by weinand** [comment] 2017-11-09 12:01
duplicate of #37880

**Closed** 2017-11-09 12:02 UTC
Labels: bug, debug, duplicate
