### ISSUE TITLE
[Explorer] Project tree structure is broken when opening multiple projects and switching projects from status bar.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#3999] opened 2016-03-11 08:49 UTC
OS: Windows10
Build#: 0.10.12-alpha
Node: 4.1.1

Steps:
1. Create multiple projects (I created "Web application" and Empty Application) using yeoman.
>Yo aspnet
2. Open folder into VS code which contains multiple projects.

Note: Resolve all the error to get project count in the status bar.
run commands > "dnu restore" and "dnx web" in node command prompt and open folder in VS code.

3. verify status bar should show correct project count.(In my case it is showing 2)
4. Try to navigate to different projects by clicking on project count (showing in the status bar).

Actual: Project tree structure in the explorer is broken.
Expected: Tree structure should be displayed properly and it should not break with user's action.
![treestructurebroken](https://cloud.githubusercontent.com/assets/17735796/13697335/94fd3d72-e721-11e5-85c3-7765641f7b16.jpg)

**Comment by bpasero** [comment] 2016-03-11 15:54
@v-pavanp does it fix when you resize the window and or sidebar? something in the chrome console?

**Comment by pavanp31** [comment] 2016-03-14 09:06
No, It goes away only when we perform refresh on explorer.

**Comment by bpasero** [comment] 2016-03-15 14:50
@v-pavanp are you running in some VM maybe?

**Comment by v-pavanp** [comment] 2016-03-16 20:32
No, it was on my physical machine. This issue is intermittent so keep it low priority.

**Comment by bpasero** [comment] 2016-03-17 07:18
@jrieken can you point me to what the C# extension does when you click on the status bar? I don't think it would do something with the explorer because it is an extension?

**Comment by jrieken** [comment] 2016-03-17 08:26
`restore` and `run` are the same commands as typed in the console.

**Comment by bpasero** [comment] 2016-03-17 09:10
@jrieken talking about this "Try to navigate to different projects by clicking on project count (showing in the status bar)."

@v-pavanp can you show me a screenshot of how "Try to navigate to different projects by clicking on project count (showing in the status bar)." works?

**Comment by jrieken** [comment] 2016-03-17 09:27
It shows the drop down / quick pick with the project files. Selection those will open the file.

**Comment by bpasero** [comment] 2016-03-17 09:29
@jrieken ok thanks

**Comment by bpasero** [comment] 2016-03-17 09:29
@v-pavanp please attach a video of this issue if you are able to reproduce, given I never saw this I will move it to April.

**Comment by bpasero** [comment] 2016-03-24 06:57
Closing this as I do not understand the steps, the attached screenshot shows the project switcher and it does not change anything in the explorer:

<img width="644" alt="screen shot 2016-03-24 at 07 56 36" src="https://cloud.githubusercontent.com/assets/900690/14010508/0396cf7c-f196-11e5-8708-a8b4769e7478.png">

**Closed by bpasero** 2016-03-24 06:57 UTC
Labels: bug, needs more info, v-test
