### ISSUE TITLE
Integrated terminal: Shell args not honored on Windows

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8429] opened 2016-06-28 19:02 UTC
Testing #8222 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Using the following settings:
        "terminal.integrated.shell.windows": "E:\\cygwin64\\bin\\bash.exe",
        "terminal.integrated.shellArgs.windows": ["-v"]
2. Bash should echo all lines read, open terminal and run: echo 123
3. "echo 123" isn't echoed (only "123" is)

**Comment by Tyriar** [comment] 2016-06-29 02:16
Going to investigate for June, may not be able to get a fix though.

**Comment by Tyriar** [comment] 2016-06-30 18:45
Upstream issue: https://github.com/chjj/pty.js/issues/137, going to remove the config for the time being.

**Comment by Bigous** [comment] 2016-07-12 22:06
just to help, 
The issue is that on windows there is no shellArgs on settings (linux and osx have).
version 1.3.1 is still lacking this option.

**Comment by Bigous** [comment] 2016-07-12 22:07
One can use bash from git too so you can test it without having to install cygwin.

**Comment by Tyriar** [comment] 2016-07-12 22:33
@Bigous I removed the setting as it doesn't work in the library we're using. So this needs to be fixed in pty.js before we can add it back.

**Comment by Bigous** [comment] 2016-07-28 14:55
Workaround: Create a batch file and set it as your windows shell. Mine is [this](https://gist.github.com/Bigous/ab5403c4fe1bf23166308035edbecdcf).

**Comment by the-ress** [comment] 2016-10-10 23:01
I've created a pull request with the fix here: chjj/pty.js#175

**Comment by Tyriar** [comment] 2016-10-11 00:52
@the-ress awesome! I'll test this out on [vscode's fork](https://github.com/Tyriar/pty.js) soon and if all works well it should land in v1.7.

**Closed** 2016-10-12 19:26 UTC
Labels: bug, help wanted, integrated-terminal, upstream, windows

**Comment by Tyriar** [comment] 2016-10-12 19:28
Fixed thanks to @the-ress's pull request! You can try this out in the [Insiders build](https://code.visualstudio.com/insiders) tomorrow or in stable v1.7.

**Comment by daviwil** [comment] 2016-10-12 19:31
That is awesome news, will save me a ton of trouble.  Thanks a lot @the-ress!

**Comment by daviwil** [comment] 2016-10-14 19:11
This is working perfectly for me now with the Terminal API in today's Insiders build.  Thanks again @the-ress!

**Comment by bagofmice** [comment] 2017-06-10 05:13
I notice that this is still a problem for terminals in 1.13. I've created a batch file workaround in an extension here:
https://marketplace.visualstudio.com/items?itemName=bagonaut.mongogo

**Comment by wycats** [comment] 2017-09-04 23:01
I've hit this issue on the latest stable (1.15) and reverted back to cmd as my default shell. Any idea why it was believed to be solved but regressed?
