### ISSUE TITLE
Javascript Colouring in Editor

### ISSUE THREAD

**Issue by metasophiea** [Microsoft/vscode#15739] opened 2016-11-18 21:10 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.9.7|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1. type something like "var num = 1/(2);  var num = 1/(2);"
although the code works fine, the colouring is incorrect in the editor

**Comment by ramya-rao-a** [comment] 2016-11-18 23:05
Closing as duplicate of #15334. The fix would be in in the insiders build by tomorrow. Please give it a try

**Closed by ramya-rao-a** 2016-11-18 23:05 UTC
