### ISSUE TITLE
Powershell is used ignoring settings

### ISSUE THREAD

**Issue by salos1982** [microsoft/vscode#132631] opened 2021-09-08 09:21 UTC
I've updated it to version 1.60 and by default powershell is used unless I defined to use git bash shell. Git bash shell still is defined in settings for internal and external terminal for windows

"terminal.external.windowsExec": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.automationShell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

**Comment by razvanbh** [comment] 2021-09-08 09:33
I'm also having the same issue after updating to 1.60, the terminal that is opened while starting the app is PowerShell. If I open a new terminal then the terminal that I set as my default is opened.

**Comment by salos1982** [comment] 2021-09-08 10:19
I have a more important issue. When I start npm script from NPM SCRIPTS VIEW it starts in PowerShell and cannot be executed.

**Comment by albertosantini** [comment] 2021-09-08 10:41
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Closed** 2021-09-08 12:32 UTC
Labels: *duplicate
