### ISSUE TITLE
"This setting cannot be applied now" should not be a warning

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#77462] opened 2019-07-16 10:11 UTC
When I open folders in a multiroot workspace I get loads of "This setting cannot be applied now" warnings, which fill my problems view.

These should be "information" diagnostics, or not shown at all.

**Comment by sandy081** [comment] 2019-07-17 14:55
When are you seeing this? while opening the UI editor or file?

**Comment by Gruntfuggly** [comment] 2019-07-17 15:06
When opening the file (using the {}) button, then selecting "Folder".

**Comment by sandy081** [comment] 2019-07-17 15:19
Ok I thought so. This is as designed in MR workspace to inform users why some settings are not getting applied. Since there is UI now we can revisit this.

**Comment by sandy081** [comment] 2019-07-22 21:01
Since there is a specialised settings UI editor, showing warnings for unknown or unsupported settings would be a noise. Hence they will be shown as hints

![image](https://user-images.githubusercontent.com/10746682/61665133-91c28780-acd4-11e9-9e80-d945c313d5eb.png)

![image](https://user-images.githubusercontent.com/10746682/61665160-9d15b300-acd4-11e9-8b12-231e03709c7f.png)

**Comment by sandy081** [comment] 2019-07-22 21:19
Fixed by https://github.com/microsoft/vscode/commit/e6d00a52ebcc19937f1aff52a7da724cd40e0b61

**Closed** 2019-07-22 21:19 UTC
Labels: config, feature-request
