### ISSUE TITLE
Feature Request: Add Task Tags such as TODO, NOTE, HACK, FIXME, etc

### ISSUE THREAD

**Issue by anthonyborell** [Microsoft/vscode#11510] opened 2016-09-04 05:35 UTC
Couldn't find any documentation on this or any good extensions. Would be amazing if we could have task tags, something that could be user defined/customizable inside settings.json

Similar to:
``` 
editor.taskTags: [
    { name: "TODO", color: "#00FF00" },
    { name: "BUG", color: "#FF0000" },
    { name: "NOTE", color: "#0000FF" }
]
```

``` javascript
// TODO: Find out why click event is undefined...
event.target.click();
```

The TODO comment would then be highlighted in the color chosen in the settings file, for this example "Green".

**Comment by glen-84** [comment] 2016-09-04 18:28
Duplicate of #9899 (?)

**Comment by alexandrudima** [comment] 2016-09-05 06:53
Let's track in #9899

**Closed by alexandrudima** 2016-09-05 06:53 UTC
Labels: editor
