### ISSUE TITLE
fonts with plus sign in their names won't render.

### ISSUE THREAD

**Issue by serkanyersen** [Microsoft/vscode#30347] opened 2017-07-10 18:37 UTC
- VSCode Version: 1.13.1
- OS Version: macos 10.12.5

Steps to Reproduce:

1. Install this patched font from here https://github.com/gabrielelana/awesome-terminal-fonts/blob/patching-strategy/patched/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf
2. this font's name is `SourceCodePro+Powerline+AwesomeRegular` go to your settings.json and try to activate this font by setting the `editor.fontFamily: "SourceCodePro+Powerline+AwesomeRegular"`
3. You'll see that step 2 will not work.
4. now try setting the font like this
```
"editor.fontFamily": "\"SourceCodePro+Powerline+AwesomeRegular\"",
```

What's happening is that VSCODE won't put quotation marks around font name if there are no spaces in it. but this font name has plus signs in the name, chromium accepts that as space and won't render the font.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment] 2018-04-18 19:03
@serkanyersen I believe this has been fixed in the meantime with one of our Electron updates. i.e. I cannot reproduce anymore on the Insiders Build (https://code.visualstudio.com/insiders/):

![kapture 2018-04-18 at 21 02 41](https://user-images.githubusercontent.com/5047891/38952415-df586472-434b-11e8-9869-4ae6eb8472be.gif)

**Comment by alexandrudima** [comment] 2018-04-18 19:08
I can reproduce after reloading the window

**Closed** 2018-04-18 19:16 UTC
Labels: bug, editor-rendering
