### ISSUE TITLE
Make DocBlock insertion configurable, or at least disable'able

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#81562] opened 2019-09-27 17:19 UTC
Right now, I can't find how to configure or at least turn off the intrusive DocBlock formatting functionality native to VS Code.
It inserts docblocks misaligned, breaking interoperability with editors that do not support random indentation within the same source file.

**Comment by chrmarti** [comment] 2019-09-27 19:45
Could you provide an example? Is this with a specific language?

**Comment by AnrDaemon** [comment] 2019-09-28 08:08
This is with both JS and PHP.
![image](https://user-images.githubusercontent.com/6532485/65813564-bad52c00-e1df-11e9-87a1-91d2aef98f1e.png)

**Comment by chrmarti** [comment] 2019-09-29 19:23
Could you explain what the problem is? What should it look like instead?

**Comment by AnrDaemon** [comment] 2019-09-29 20:17
It should have same indent through all lines. Not random 4-to-5-with-intent-for-7.

**Comment by mjbvz** [comment] 2019-10-01 20:51
I don't understand. Please share a screenshot of what you expect it to look like

**Comment by AnrDaemon** [comment] 2019-10-02 11:25
What you don't understand in "random line indentation"?
What I expect is this at the very least. Or no useless stars in between comment delimiters.
![20191002-142351](https://user-images.githubusercontent.com/6532485/66040517-50debe80-e520-11e9-81c5-0885e9016ac9.png)

**Comment by mjbvz** [comment] 2019-10-02 18:11
Duplicate of #21042

This is configured per language. Open a separate issue for php

**Closed by mjbvz** 2019-10-02 18:11 UTC
Labels: needs more info

**Comment by AnrDaemon** [comment] 2019-10-02 23:17
WHERE it is configured per language?
