### ISSUE TITLE
Typescript Intellisense hangs after Code has been open for awhile

### ISSUE THREAD

**Issue by craxal** [Microsoft/vscode#27862] opened 2017-06-01 16:18 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|PowerShell|ms-vscode|1.1.0|;

---

Steps to Reproduce:

1. Open VS Code with a project containing several hundred Typescript files.
2. Leave Code open for a long time (several days).
3. Hover over various symbols or press Shift-F12 to find all references.

I expect Intellisense/Code Lens to work normally. Instead, I get "Loading..." tooltips or windows that never resolve.

**Comment by mjbvz** [comment] 2017-06-01 23:01
First please try out the current insiders builds to see if the issue has been resolved: https://code.visualstudio.com/insiders You may be running into a memory usage issue that is crashing the typescript server. In VSCode 1.12, sometimes we did not restart the server properly after a crash

If you still see this issue in the current insiders builds, please try collecting the typescript server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Thanks

**Comment by soheilpro** [comment] 2017-06-04 20:41
I have the exact same problem in version 1.12 but it seems to be fixed in the Insiders build. TypeScript IntelliSense stops working after a few minutes and I have to restart VSCode to get it working again.

Here is the output from the TypeScript section:
```
[Trace - 10:34:43 PM] TypeScript Service: trying to cancel ongoing request with sequence number 5099
[Trace - 10:34:44 PM] TypeScript Service: canceled request with sequence number 5100
[Trace - 10:34:44 PM] TypeScript Service: canceled request with sequence number 5101
[Trace - 10:34:49 PM] TypeScript Service: canceled request with sequence number 5102
[Trace - 10:34:49 PM] TypeScript Service: canceled request with sequence number 5103
[Trace - 10:34:49 PM] TypeScript Service: canceled request with sequence number 5104
[Trace - 10:34:50 PM] TypeScript Service: canceled request with sequence number 5105
[Trace - 10:34:51 PM] TypeScript Service: canceled request with sequence number 5109
[Trace - 10:34:54 PM] TypeScript Service: canceled request with sequence number 5121
[Trace - 10:34:55 PM] TypeScript Service: canceled request with sequence number 5129
[Trace - 10:35:06 PM] TypeScript Service: canceled request with sequence number 5143
[Info  - 10:35:07 PM] TSServer exited
[Info  - 10:35:07 PM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Trace - 10:35:07 PM] TypeScript Service: canceled request with sequence number 5144
[Trace - 10:35:11 PM] TypeScript Service: canceled request with sequence number 5151
```

**Comment by mjbvz** [comment] 2017-06-05 17:39
@soheilpro  Yes there was an issue in 1.12 that could cause restart to fail after cancellation. Let me know if you see this in the insiders builds

**Closed** 2017-06-12 18:31 UTC
Labels: javascript, needs more info, typescript

**Comment by craxal** [comment] 2017-06-16 16:56
Reproducing the error is tricky, and I don't have a lot of time to do that. However, I recently reproduced, and I have some trace information to share, but it's really long. How can I share it?
