### ISSUE TITLE
Drag and Drop selected code

### ISSUE THREAD

**Issue by aliyazdi75** [Microsoft/vscode#18595] opened 2017-01-16 08:18 UTC
- VSCode Version:
- OS Version:

Steps to produce:

1. Drag and Drop selected code

**Comment by alexandrudima** [comment] 2017-01-21 14:07
Please use the github issue search functionality before creating a new issue. This will allow me to focus my time on programming and not on searching for duplicates. Duplicate of #1046

**Closed by alexandrudima** 2017-01-21 14:07 UTC
