### ISSUE TITLE
If terminal.integrated.shell doesn't have a matching terminal.integrated.profiles entry the shell path will be ' '

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#121760] opened 2021-04-20 17:50 UTC
- VS Code Version: 1.55.1
- OS Version: Windows 10 20H2 build 19042.867

Hello 👋 The Python extension uses [the content of the `terminal.integrated.shell.<os>` setting](https://github.com/microsoft/vscode-python/blob/main/src/client/common/terminal/shellDetectors/settingsShellDetector.ts#L30-L51) to determine which shell is currently used and which virtual environment activation command should be sent.

However, as reported in https://github.com/microsoft/vscode-python/issues/15919#issuecomment-820354564, if the path specified in `terminal.integrated.shell.<os>` does not have a corresponding `terminal.integrated.profiles.<os>` entry, the value returned by `terminal.integrated.shell.<os>` will be '', and terminal type detection will fail.

Steps to Reproduce:

1. Install Powershell 7 in a non-standard path (for example, outside of the system drive)
2. Add the path to the newly installed shell to `terminal.integrated.shell.windows`
3. Retrieve the value of `terminal.integrated.shell.windows` using `workspace.getConfiguration()`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2021-04-22 20:16
shell/profiles have changed a lot in the upcoming version, but the python extension should not be doing this (definitely in 1.56) as there's a `env.shell` extension API for this purpose which should work. In fact that extension was added specifically for the Python extension so I'm a bit confused https://github.com/microsoft/vscode-python/issues/6050

**Comment by kimadeline** [comment] 2021-04-22 22:33
Oh sorry I linked to the wrong file! We do use the `env.shell` API you mention (in [VSCEnvironmentShellDetector](https://github.com/microsoft/vscode-python/blob/9f95296ebec353e2a7786c3ff42ad151e8fd409b/src/client/common/terminal/shellDetectors/vscEnvironmentShellDetector.ts#L24-L36)), but for some reason the shell path being detected goes from '' to `bash.exe`, and never `F:\\Program Files\\PowerShell\\7\\pwsh.exe`:

> Info 2021-04-15 16:39:05: Shell path ''
> Info 2021-04-15 16:39:05: Shell path identified as shell 'other'
> Info 2021-04-15 16:39:05: Terminal name '' identified as shell 'other'
> Info 2021-04-15 16:39:05: [object Object]. Shell identified as other (Terminal name is )
> Info 2021-04-15 16:39:05: Shell path 'C:\Program Files\Git\bin\bash.exe'
> Info 2021-04-15 16:39:05: Shell path identified as shell 'bash'
> Info 2021-04-15 16:39:05: Terminal shell path 'C:\Program Files\Git\bin\bash.exe' identified as shell 'bash'
> Info 2021-04-15 16:39:05: [object Object]. Shell identified as bash (Terminal name is )
> Info 2021-04-15 16:39:05: Shell identified as 'bash'

Although here the API works as intended, so there's probably something else going on. Let me close it and dig a little bit further on the extension side, especially since shells and profiles are being revamped 🙂 Thank you!

**Comment by Tyriar** [comment] 2021-04-23 10:50
I don't totally understand how profiles would interact with shell in stable but we've made some major changes in this area and introduced a new defaultProfile setting in Insiders. I'll double check that all plays nice with env.shell.

**Comment by meganrogge** [comment] 2021-04-29 02:09
Also of interest - when I set `"terminal.integrated.shell.windows"` to a valid executable path, and don't have `"terminal.integrated.defaultProfile.windows"` set, II get `The terminal process failed to launch: Path to ___ does not exist` when I click the plus to create a new default terminal

**Comment by meganrogge** [comment] 2021-04-29 02:29
Can you try this on Insider's? I believe this issue has been fixed.

**Comment by meganrogge** [comment] 2021-04-29 18:27
Closing because I think this has been resolved

![recording - 2021-04-29T112154 362](https://user-images.githubusercontent.com/29464607/116600040-b2723500-a8dd-11eb-8a54-592b35f9c37f.gif)

**Comment by meganrogge** [comment] 2021-04-29 18:29
to verify:

using the extension terminal sample, log the values of `env.shell` and `getConfiguration().get('terminal.integrated.shell.windows')`

these should be non-null and reflect what you've set `terminal.integrated.shell.windows` to, regardless of whether or not that path is found in `terminal.integrated.profiles.windows`.

**Comment by Tyriar** [comment] 2021-05-10 12:16
I suspect this isn't fixed

**Comment by karrtikr** [comment] 2021-05-12 00:56
`vscode.env.shell` returns the value of `terminal.integrated.shell.windows` instead of using `terminal.integrated.defaultProfile.windows` in combination of `terminal.integrated.profiles.windows` as the shell path, is this expected?

**Comment by karrtikr** [comment] 2021-05-12 18:01
Following up regarding https://github.com/microsoft/vscode-python/issues/16175#issuecomment-839718867,
- This also means that such users won't be able to change their default shell using the `Terminal: Select default profile` command, which can be confusing.
- Currently the API `vscode.env.shell` doesn't use `terminal.integrated.defaultProfile` even if the shell setting is not specified, and returns the default value instead. Does that also change with https://github.com/microsoft/vscode/pull/123174? I expect it to fallback on the profile setting instead.

**Comment by Tyriar** [comment] 2021-05-12 20:00
@karrtikr you're right, https://github.com/microsoft/vscode/pull/123174 won't fix that because it's actually quite a big change to make that happen which I've been working on most of today, I believe this is too risky to try to get into the recovery build as it involves moving a bunch of stuff around to live under different processes. It's unfortunate that users may get confused and I'm not happy at all with the issues that came with default profiles.

I suggest once the recovery build ships (tomorrow?), in the Python extension check if the user has set `defaultProfile` but not `shell` or `shellArgs` and warn them that the default profile won't be used in this case. Since https://github.com/microsoft/vscode/pull/123174 will be in the recovery build, that should catch all the bad cases

**Comment by karrtikr** [comment] 2021-05-14 23:01
@Tyriar Thanks for the quick fix, although I'm still having some issues with the `vscode.env.shell` API when trying the latest insiders build. Steps to repro on windows:

1. Make sure settings related to `shell` and `defaultProfile` are clean.
2. Observe API detects the default shell type correctly.
3. Change default profile to `Command prompt` and quickly open a new terminal which triggers an event.
4. API still detects the shell as powershell.
5. Open another terminal .
6. API is now detecting the shell type correctly.

It seems it takes some time for the terminal change to be propagated to to the API. If a wait a bit before opening the terminal, the problem does not happen.

**Comment by aravindvnair99** [comment] 2021-05-14 23:10
@karrtikr Same here as well. Sometimes on reopening VS Code, the settings seem to vanish as well.

**Comment by meganrogge** [comment] 2021-06-05 03:12
@connor4312 is this verification-found?

**Comment by connor4312** [comment] 2021-06-05 05:28
I did not try to verify, but after reading the thread reopened from @karrtikr's report of continued problems.

**Comment by Tyriar** [comment] 2021-06-07 12:24
@connor4312 it takes up to 2 seconds after changing a profile to apply the changes by design.

**Closed by Tyriar** 2021-06-07 12:24 UTC
Labels: api, bug, regression, terminal, terminal-profiles

**Comment by ejizba** [comment] 2021-06-16 18:59
> it takes up to 2 seconds after changing a profile to apply the changes by design.

This is true for changes to "terminal.integrated.defaultProfile.windows", but no matter how long I seem to wait, `env.shell` is not updated after changes to "terminal.integrated.shell.windows". The only way I see it updated is if I reload the window

Version: 1.58.0-insider (user setup)
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:17:51.956Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Tyriar** [comment] 2021-07-06 21:23
@ejizba created https://github.com/microsoft/vscode/issues/128079 for that, thanks
