### ISSUE TITLE
Syntax errors when using file association "*.es": "javascriptreact"

### ISSUE THREAD

**Issue by sleepwalky** [Microsoft/vscode#19549] opened 2017-01-28 18:02 UTC
- VSCode Version: 1.8.1 (clean, without extensions)
- OS Version: Windows 10

![Image of issue](https://pp.vk.me/c626519/v626519720/4a0bf/0h13n9SwKpo.jpg)

Steps to Reproduce:

1. Create file association ("*.es": "javascriptreact") in user settings
2. Paste some React code

I have no errors with same code in ".js" file.

**Comment by mousetraps** [comment] 2017-01-28 21:17
Thanks for reporting! Looks like this is a duplicate of https://github.com/Microsoft/vscode/issues/15460, so I'm going to go ahead and close this issue. Let me know if you think otherwise, and we'll be happy to reopen. Happy coding!

**Closed by mousetraps** 2017-01-28 21:17 UTC
Labels: duplicate
