### ISSUE TITLE
[Suggestion] minimap: ability to drag and drop the "window"

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#21020] opened 2017-02-21 21:51 UTC
It would be great if:

 - it was possible to click and drag the "selection window" to move onto the minimap: releasing the mouse would show the text at current position
 - the minimap didn't scroll and was showing the whole document: right now, depending on the document size, you first have to scroll a little to view the part where you want to navigate to, and then only you make click on the position you want to move the view

What I call "window" is the highlighed square that indicates what part of the document is currently visible:

![window](https://cloud.githubusercontent.com/assets/199648/23186680/35443100-f888-11e6-8cf4-c345b276e242.png)

**Comment by alexandrudima** [comment] 2017-02-27 15:47
Duplicate of #20935

**Closed by alexandrudima** 2017-02-27 15:47 UTC
