### ISSUE TITLE
Editor hovers are not showing up in today's insiders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111761] opened 2020-12-02 18:14 UTC
GitLens hovers aren't showing up in today's insiders -- there are no visible errors.

**Comment by misolori** [comment] 2020-12-02 18:17
Got the same thing in launch configs, hovering highlights the property but not hover appears:

![image](https://user-images.githubusercontent.com/35271042/100914192-929e2880-3487-11eb-8401-39d5e3fd21c5.png)

**Comment by rami3l** [comment] 2020-12-02 18:55
The same with `rust-analyzer`. Seems like a problem with hover showing.

**Comment by alexdima** [comment] 2020-12-02 19:33
@eamodio @misolori Does this reproduce only on a certain platform? Do the hovers render on errors? Do the hover render when using `F1 > Show hover` ?

**Comment by ntdog22** [comment] 2020-12-02 19:34
Encountered a similar issue with hovering for JSDoc comments:

![image](https://user-images.githubusercontent.com/6867405/100922073-44daed80-3492-11eb-9a02-02399b50ee3e.png)

**Comment by alexdima** [comment] 2020-12-02 19:34
By the way, hovers show up for me:

![Kapture 2020-12-02 at 20 33 54](https://user-images.githubusercontent.com/5047891/100922092-bdb36700-34dd-11eb-9d99-bc00bc856e57.gif)

**Comment by alexdima** [comment] 2020-12-02 19:35
They don't show up for me in JSON.

**Comment by ntdog22** [comment] 2020-12-02 19:43
@alexdima In TypeScript, I am not able to see JSDoc comment information on hover as I was able to yesterday (and prior):

**VSCode Insiders About:**
![image](https://user-images.githubusercontent.com/6867405/100922718-13aeed00-3493-11eb-950d-15f37bddb0f9.png)


**Example:**

![image](https://user-images.githubusercontent.com/6867405/100922627-f8dc7880-3492-11eb-9d31-1f1112fd9c82.png)


**Expected Result:** **_from this [Doc](https://code.visualstudio.com/docs/languages/typescript#_hover-information)_**

![image](https://user-images.githubusercontent.com/6867405/100922926-4d7ff380-3493-11eb-9b5f-10e644c55864.png)

**Comment by alexdima** [comment] 2020-12-02 19:44
Duplicate of https://github.com/microsoft/vscode/issues/111741

**Comment by alexdima** [comment] 2020-12-02 19:45
It looks like #111741 was a problem with the type converters that might impact any hover provider from the ext host.

**Closed by alexdima** 2020-12-02 19:44 UTC
Labels: needs more info
