### ISSUE TITLE
Support the worktree options in the source control command menu

### ISSUE THREAD

**Issue by abhijit-chikane** [microsoft/vscode#190958] opened 2023-08-22 10:10 UTC
Support the worktree options in the source control command menu

![image](https://github.com/microsoft/vscode/assets/50770619/2e4f26eb-1678-402a-bed1-7d8816021673)

It will be much easier to add, remove and do all the operations on worktree
submenu should have these options

git worktree list
git worktree lock
git worktree move
git worktree prune
git worktree remove
git worktree repair
git worktree unlock

and I would also like to see this worktree view inside source control panel like this

![image](https://github.com/microsoft/vscode/assets/50770619/1b261f25-a9e1-4ca7-b3c4-e958f160c1e4)

**Comment by lszomoru** [comment] 2023-12-14 15:50
Closing as duplicate of https://github.com/microsoft/vscode/issues/68038

**Closed by lszomoru** 2023-12-14 15:50 UTC
Labels: feature-request, git
