### ISSUE TITLE
Font MesloLGS NF corrupted in terminal - MacOS 

### ISSUE THREAD

**Issue by lambasoft** [microsoft/vscode#111679] opened 2020-12-01 21:36 UTC
- VSCode Version: Version: 1.51.1 | Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- OS Version: MacOS BigSur 11.0.1 (20B29)

Steps to Reproduce:

My settings.json:
```
{
    "window.zoomLevel": 0,
    "python.pythonPath": "/usr/local/bin/python3",
    "workbench.iconTheme": "vscode-icons",
    "[html]": {
        "editor.defaultFormatter": "lonefy.vscode-JS-CSS-HTML-formatter"
    },
    "terminal.integrated.fontFamily": "MesloLGS NF",
}
```

My Terminal when I changed font to MesloLGS NF:
![image](https://user-images.githubusercontent.com/15126305/100799287-7d94ab80-342d-11eb-9971-d01acc7e8378.png)

Output of:
```printf '\uE0B0\n'```
![image](https://user-images.githubusercontent.com/15126305/100799384-a1f08800-342d-11eb-99b0-41cee7dd6cc1.png)

I installed the font from:

- [MesloLGS NF Regular.ttf](
    https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf)
- [MesloLGS NF Bold.ttf](
    https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf)
- [MesloLGS NF Italic.ttf](
    https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf)
- [MesloLGS NF Bold Italic.ttf](
    https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf)

![image](https://user-images.githubusercontent.com/15126305/100799563-f3991280-342d-11eb-8f81-dd8be37aa3d9.png)

What have I done wrong in the font integration?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment] 2020-12-02 01:09
have you tried changing the renderer type, IE `"terminal.integrated.rendererType"`?

**Comment by lambasoft** [comment] 2020-12-02 01:12
@meganrogge Yes, I've tried all the options and unfortunately it did not work.

**Comment by meganrogge** [comment] 2020-12-02 01:13
but it works fine with other fonts?

**Comment by lambasoft** [comment] 2020-12-02 01:17
@meganrogge Yes, the problem happened when I installed powerlevel10k and ohmyzsh. 
On iTerm2 the terminal works perfectly:
![image](https://user-images.githubusercontent.com/15126305/100815580-f35c3f80-344c-11eb-87c4-a736fb4207ef.png)

**Comment by meganrogge** [comment] 2021-03-30 17:12
Duplicate of #73879

**Closed** 2021-03-30 17:12 UTC
Labels: *duplicate, bug, integrated-terminal, macos-big-sur
