### ISSUE TITLE
[json] No intellisense for `"$defs"` keyword of JSON Schema `draft/2020-12` 

### ISSUE THREAD

**Issue by GabenGar** [microsoft/vscode#208561] opened 2024-03-25 08:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows 10

Steps to Reproduce:

1. Clone the repository:
   ```sh
   git clone https://github.com/GabenGar/repros
   ```
2. Switch to the repro folder:
   ```sh
   cd vscode/defs-keyword-no-suggestions
   ```
3. Open VSCode:
   ```sh
   code .
   ```
4. Look at the `entity.schema.json`
   - its schema is implicitly set to `"https://json-schema.org/draft/2020-12/schema"` from `.vscode/settings`.
   - `$dynamicRef` warning at the top level is expected.
   - `definitions` is warned as being deprecated, however it gets all suggestions inside it just fine.
   - `$defs` (a more formalized keyword for storing internal references in the later specs), however, does not.

**Comment by aeschli** [comment] 2024-03-25 11:13
The `$defs` specification is part of the  `2020-12/schema` schema, located in a vocubulary. However, we are not yet able to fully load that schema as it uses the `vocabulary` feature which we have not yet implemented.

So this is a duplicate of https://github.com/microsoft/vscode/issues/165219

**Closed by aeschli** 2024-03-25 11:13 UTC
Labels: feature-request, json
