### ISSUE TITLE
Dirty font on Ubuntu 17.10

### ISSUE THREAD

**Issue by hexrcs** [Microsoft/vscode#37669] opened 2017-11-05 14:40 UTC
- VSCode Version: 1.17.2
- OS Version: Ubuntu 17.10 64-bit (GNOME3 + Wayland)

The font rendering gets dirty (see the image) after zooming in. I have tested multiple fonts and this happened to all of them.

![screenshot from 2017-11-05 15-34-19](https://user-images.githubusercontent.com/26751752/32415792-c8b421b2-c23f-11e7-8909-278dd93d1591.png)

Steps to Reproduce:

1. Have "_Large Text_" option toggled on in Ubuntu "_System Settings/ Universal Access_"
2. Open VS Code and have some text displayed in the editor
3. Use `Ctrl-+` to zoom in a bit

Reproduces without extensions: Yes

**Comment by maxibanki** [comment] 2017-11-05 17:57
Duplicate of #35675

**Comment by hexrcs** [comment] 2017-11-05 18:21
Downgrading libfreetype6 from 2.8.1 to 2.8 fixed the problem.

**Comment by maxibanki** [comment] 2017-11-05 18:35
Then please close the issue, :)

**Closed** 2017-11-05 18:40 UTC
Labels: electron, linux, upstream, workbench
