### ISSUE TITLE
HTML syntax coloring problem

### ISSUE THREAD

**Issue by nalply** [Microsoft/vscode#34224] opened 2017-09-12 11:38 UTC
- VSCode Version: 1.16 (August 2017)
- OS Version: MacOS 10.11.6

Write this in an editor:
```
<script>const x = 0</script>
<body lang=en>
  some content here...
</body>
```

![image](https://user-images.githubusercontent.com/172290/30323696-76067c72-97be-11e7-916a-d7dfae221082.png)

Note: Wrap `en` in quotes or remove `const` and syntax coloring works as expected.

![image](https://user-images.githubusercontent.com/172290/30323879-3891d836-97bf-11e7-9c2d-e77f4a02efdd.png)
![image](https://user-images.githubusercontent.com/172290/30323863-20396394-97bf-11e7-9db8-6f4704a71f6c.png)

Reproduces without extensions: Yes
(with `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-extensions`)

**Comment by myfonj** [comment] 2017-09-12 19:20
Incorrect `</script>` highlight is produced even for (syntactically invalid) `<script>const</script>` without apparent syntax error (as seen in OPs report).
Instead of `const` you can use also `var`, `let`, `function`, or `class`; for `import`, `export`, the syntax error (underline) is properly marked.

**Comment by aeschli** [comment] 2017-09-13 08:46
This is an inherent problem with the way text mate works. The html grammar includes the JavaScript grammar which is designed for standalone JavaScript files. It is not aware of '</script>' as an end patters while inside a rule.

#13112 is a similar issue

**Comment by aeschli** [comment] 2017-09-13 08:54
duplicate of #20488

**Closed by aeschli** 2017-09-13 08:54 UTC
Labels: grammar, html, new release
