### ISSUE TITLE
Editing a `.json` file causes file dirty/save loop

### ISSUE THREAD

**Issue by dennisroche** [Microsoft/vscode#13462] opened 2016-10-11 03:08 UTC
- VSCode Version: 1.6
- OS Version: Windows 10 x64 Insider Slow (Build 14931)

Steps to Reproduce:

1. Edit any `.json` file
2. Save

Opened `procmon` and didn't see any disk writing activity, so believe this is a display state bug.

![vscode-bug](https://cloud.githubusercontent.com/assets/4949392/19257532/e7823ef6-8fa2-11e6-9c5d-be09cbfd5f34.gif)

**Comment by isidorn** [comment] 2016-10-11 08:53
@dennisroche I can not reproduce this. Do you also see this if you run with  `--disable-extensions`?
What save settings do you have for your workspace?

**Comment by dennisroche** [comment] 2016-10-11 09:04
@isidorn I cannot reproduce when running with `--disable-extensions`.

**Comment by isidorn** [comment] 2016-10-11 09:18
@dennisroche this means that one of the extensions is causing this. You can try to figure out which one it is by uninstalling them one by one and trying to reproduce. Once you find the extension which is the cause it would be great to file this issue to the repo of that particular extension.
There is nothing that can be done on the vscode side, thus closing this issue

**Closed by isidorn** 2016-10-11 09:18 UTC
Labels: needs more info

**Comment by maroy1986** [comment] 2016-10-11 14:11
I just tried again with disabling extension and I can't reproduce somehow... Before submitting the issue I really launch VSCode with the `--disable-extensions`, 110% sure of this but now, I can't reproduced. Furthermore, I narrowed it down to editorConfig extension. Sorry for the duplicate, I search before posting this one but didn't see it... You can close the issue I guess.
