### ISSUE TITLE
HTML syntax highlighting broken for elements with a hyphen

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#12510] opened 2016-09-23 11:17 UTC
- VSCode Version: 1.6.0-insider from 23.09.

![image](https://cloud.githubusercontent.com/assets/10532611/18784086/ff4bdad6-818f-11e6-894f-891d4a6a6d94.png)

```html
<div id="nav-wrapper">
    <v-accordion class="nav">
        <v-pane class="nav-item">
            <v-pane-header><a ui-sref="dashboard"><i class="fa fa-home"></i><span>Dashboard</span></a></v-pane-header>
            <v-pane-content></v-pane-content>
        </v-pane>
        <v-pane class="nav-item">
            <v-pane-header>
                <a href><i class="fa fa-users"></i><span>Accounts</span></a>
            </v-pane-header>
            <v-pane-content>
                <ul>
                    <li><a ui-sref="users"><i class="fa fa-caret-right"></i><span>Overview</span></a></li>
                    <li><a ui-sref="login-attempts"><i class="fa fa-caret-right"></i><span>Login Attempts</span></a></li>
                </ul>
            </v-pane-content>
```

Technically not valid HTML, but valid XML and Angular uses it everywhere.

Worked yesterday.

**Comment by aeschli** [comment] 2016-10-17 15:40
duplicate of #13448

**Closed by aeschli** 2016-10-17 15:40 UTC
Labels: bug, html
