### ISSUE TITLE
Command-line `code` command slow when called via SSH (~1 sec delay)

### ISSUE THREAD

**Issue by joliss** [microsoft/vscode#141297] opened 2022-01-24 15:48 UTC
Issue Type: <b>Bug</b>

The `code` (or `code-insiders`) command-line tool incurs a roughly 1-second delay when called via SSH. [Update: More generally it happens whenever stdin is not a terminal, `code < /dev/null`.]

```
$ time /usr/local/bin/code-insiders test.txt

real	0m0.158s
user	0m0.078s
sys	0m0.037s

$ ssh localhost 'time /usr/local/bin/code-insiders test.txt'

real	0m1.142s
user	0m0.082s
sys	0m0.037s
```

Note that we're calling `time` inside the SSH command here, so it's not due to SSH being slow to establish the connection. I just freshly re-installed the `code-insiders` command from within the editor, so it should be up-to-date as well.

Can anybody reproduce this? Or if not, is there anything I can run to help track down the cause of this delay?

----------

VS Code version: Code - Insiders 1.64.0-insider (2c967bf892d52550fabae08347faae57a4539b03, 2022-01-24T05:26:28.455Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|test.txt --crash-reporter-id 5bedd228-a602-4962-b587-56869604957d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30421357
vscop804:30404766
vscop940:30404999
vsclayoutctrc:30405799
azactmsalcf:30409288
pythonvsnew555:30426298
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by roblourens** [comment] 2022-01-27 05:17
Is it the same if you run `ssh localhost` then in that interactive session, `time ...`?

**Comment by joliss** [comment] 2022-01-28 10:14
Hm, no, when I run `ssh localhost` and then type the command in the interactive session, the delay doesn't happen.

```
$ ssh localhost
Last login: Fri Jan 28 10:11:58 2022 from 127.0.0.1
$ time /usr/local/bin/code-insiders test.txt

real	0m0.148s
user	0m0.076s
sys	0m0.038s
```

**Comment by roblourens** [comment] 2022-01-28 17:33
This has got to be an artifact of how SSH invokes that command, right? vscode doesn't know whether's it's being run through ssh. Since the time isn't included in `user`, our process is not running for that extra time.

**Comment by joliss** [comment] 2022-02-05 21:36
I have some more details as to what's going on.

I looked at `/usr/local/bin/code-insiders`, and it simply generates a command to run:

```bash
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$CONTENTS/MacOS/Electron"
CLI="$CONTENTS/Resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
exit $?
```

If I expand the second-to-last line manually, like so:

```
$ ssh localhost "time ELECTRON_RUN_AS_NODE=1 '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/cli.js' --ms-enable-electron-run-as-node test.txt"

real	0m1.105s
user	0m0.090s
sys	0m0.023s
```

then I get the same ~1.1 second delay.

But if I drop the `ELECTRON_RUN_AS_NODE=1` environment variable, the delay goes away.

```
$ ssh localhost "time '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/cli.js' --ms-enable-electron-run-as-node test.txt"

real	0m0.358s
user	0m0.221s
sys	0m0.171s
```

My hypothesis is that this is happening because VS Code keeps some stdout/stderr file descriptor open for a while, and this interacts with SSH in some way, but it could well be something else.

Any chance this issue can be reopened?

**Comment by roblourens** [comment] 2022-02-07 18:13
Any idea @deepak1556?

**Comment by joliss** [comment] 2022-02-15 22:03
After some more testing, it looks like the delay happens whenever stdin is not a pipe. This is the case when called via SSH, but it can more easily be reproduced by simply redirecting stdin:

```
$ time code-insiders test.txt

real	0m0.122s
user	0m0.084s
sys	0m0.030s

$ time code-insiders test.txt < /dev/null

real	0m1.121s
user	0m0.099s
sys	0m0.032s
```

With the second command, the VS Code window is foregrounded almost immediately, but the `code` command then blocks for another 1 second before returning.

**Comment by roblourens** [comment] 2022-12-06 17:27
Interesting fine, but this has just got to be the time it takes to decide whether code should be reading from stdin and displaying it, or something like that

**Comment by deepak1556** [comment] 2023-12-12 12:13
The delay comes from https://github.com/microsoft/vscode/blob/91a4378f47544a3eedb0bba8f7d6e7cb7c08e633/src/vs/code/node/cli.ts#L244 which happens when stdin tty is not found. Closing as designed.

**Closed by deepak1556** 2023-12-12 12:13 UTC
Labels: bug, upstream, macos, electron, confirmation-pending, :apple: si, ssh
