### ISSUE TITLE
File System Watcher has double slashes `//` as path separator

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode#210517] opened 2024-04-16 22:29 UTC
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Add the following in your extension activation:
```typescript
        const fileSystemWatcher = workspace.createFileSystemWatcher("**/*", true, false, true);
        fileSystemWatcher.onDidChange(uri => {
            console.log(`Changed file: ${uri.fsPath}`);
        });
```

Now this prints:
```
Changed file: /Users/aboyko/git/vscode-spring-boot-dashboard/test/projects/spring-petclinic//src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
extensionHostProcess.js:146
Changed file: /Users/aboyko/git/vscode-spring-boot-dashboard/test/projects/spring-petclinic//target/classes/org/springframework/samples/petclinic/owner/OwnerController.class
```

Note the `//` in both URIs: `petclinic//src` and `petclinic//target`

**Comment by bpasero** [comment] 2024-04-17 04:30
I cannot reproduce, you would have to tell me exactly how your setup looks like (folder path you run from, etc.). 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by martinlippert** [comment] 2024-04-17 07:25
I can reproduce the issue with the latest nightly insiders build as well. No idea yet what exactly triggers this though.
The `didSave` event contains the correct URI, whereas the `didChangeWatchedFiles` event contains a URI with the duplicated `/` at the position of the folder that I opened.

In the example above from @BoykoAlex the folder that got opened in VSCode is `/Users/aboyko/git/vscode-spring-boot-dashboard/test/projects/spring-petclinic`, the `src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java` is the path inside the project. So it looks to me like the duplicated `/` shows up between the workspace folder and the path inside the workspace.

**Comment by bpasero** [comment] 2024-04-17 07:34
👋 Martin

I wonder if some other extension installs a watcher that ends up with this double slash. Does it reproduce with all extensions disabled except for the one that creates the watcher?

Specifically, I would try with disabling the Java extension and friends.

**Comment by martinlippert** [comment] 2024-04-17 11:20
👋 Ben! Long time, no see... :-)

You are right, once I have this extension active: `vscjava.vscode-java-dependency`, the events from the file watcher have the double slashes problem. Without that extension active, the events look fine.

**Comment by bpasero** [comment] 2024-04-17 12:40
Ok thanks for confirming, we document that `baseUri` cannot have trailing slashes:

https://github.com/microsoft/vscode/blob/a7d0bc898241b7c049ccdf628b9af4a6242e6a29/src/vscode-dts/vscode.d.ts#L2221-L2226

I will go ahead and close this issue.

**Closed by bpasero** 2024-04-17 12:40 UTC
Labels: info-needed, file-watcher, confirmation-pending
