### ISSUE TITLE
Output ID passed in `experimental_registerHtmlRenderingHook` is sometimes incorrect

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#189488] opened 2023-08-02 16:38 UTC
Does this issue occur when all extensions are disabled?: Yes (requires Jupyter/Python)

- VS Code Version: 1.80.2
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Clone https://github.com/pwang347/vscode-renderer-test/tree/pawang/outputIdBug
2. Build and run the extension (should be able to just press the play button, may need to `npm install` first)
3. Open the provided `example.ipynb` file in the repo
4. Open the debug tools for console logs (or check debug console)
5. Observe that for some cells, the output ID is sometimes incorrect when executing multiple times (the first time is correct, but not subsequent runs)

**Comment by pwang347** [comment] 2023-08-05 00:27
FYI @DonJayamanne, seems like downgrading Jupyter to `v2023.4.1011241018` also fixes it

**Comment by DonJayamanne** [comment] 2023-08-08 22:50
Sorry, I haven't had a chance to look at this, will look at this tomorrow

**Comment by DonJayamanne** [comment] 2023-08-11 11:58
Looks like this is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13957
This is an issue in VS Code renderers, the previous output item is not disposed.
  
The fault is either here or elsewhere 
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts#L282
```typescript
spliceNotebookCellOutputs(splice: NotebookCellOutputsSplice): void {
    // 
}
```

In this method we have code to dispose the previous outputs when
* We delete output items
* Or when we end up adding new outputs that is less than previous outputs
However we do not have any code to dispose previous outputs when they are replaced
At least thats what I think.
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts#L585
```typescript
private _renderNow(splice: NotebookCellOutputsSplice, context: CellOutputUpdateContext) {
```

**Comment by DonJayamanne** [comment] 2023-08-11 12:00
The only reason it works in previous version of Jupyter is because the code in teh previous version was fractionally slower,
te new version ends up `clearing` previous output and replacing it with new output in the same operation.
Previously we would end up with clearing output and then sending that and then inserting the new output (which happened one after the other but with a few ms of delay, enough for the two actions to run separately).

Now things are much faster in Jupyter and both operations are happening together, but we seem to have hit an issue in existing code of VS Code.

**Comment by DonJayamanne** [comment] 2023-08-17 00:41
@paul-cheung0607 Plese can you create a sample without the use of Github issues, I'd like to try this with a different sample, that would be much simpler. Github issues notebook doesn't work in OSS and trying to set that up takes more effort.
E.g. why not create a simple notebook controller that emits some output.

Basically I have a fix for a related issue and would like to check whether that fix addresses this as well,
https://github.com/microsoft/vscode/pull/190614

**Comment by DonJayamanne** [comment] 2023-08-17 00:53
I can now confirm this is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13957

**Comment by pwang347** [comment] 2023-08-17 16:44
Great, thanks for confirming!

**Comment by DonJayamanne** [comment] 2023-08-22 03:06
Not a duplicate of https://github.com/microsoft/vscode-jupyter/issues/14161

**Comment by DonJayamanne** [comment] 2023-08-22 03:16
@pwang347 I'm  closing this issue as @rebornix mentioned that this  is by design
Basically if you run a cell, and the output mime type is the same then the renderer is called again with the same output item, instead of generating a whole new output item.

This explains why the post render is called again but with the same output item.

The reason it used to work in older versions of Jupyter extension is because we'd first clear the output and then render the new output in two separate steps, as a result when the new item is added we need to create a whole new outputitem object.
Now the Jupyter extension is more performant (faster) and the clear and update output operations happen to get batched up and processed in VS Code at the same time.

**Closed by DonJayamanne** 2023-08-22 03:16 UTC

**Comment by pwang347** [comment] 2023-08-22 17:44
@DonJayamanne @rebornix I see - so in general, we should not expect that the rendered item's ID is up-to-date (whereas the one in the extension side will have a new ID).

Would you have any recommendations on associating a particular output renderer to a cell? Would it be safe to cache the matching cell in the renderer assuming that on the first render both the renderer and the extension side will always have the same ID?

Thanks!

**Comment by rebornix** [comment] 2023-08-22 18:25
> Would you have any recommendations on associating a particular output renderer to a cell
> Would it be safe to cache the matching cell in the renderer assuming that on the first render both the renderer and the extension side will always have the same ID

It's safe to cache the matching cell, the renderer won't get a render request from another cell on a re-render.

**Comment by pwang347** [comment] 2023-08-25 23:48
> > Would you have any recommendations on associating a particular output renderer to a cell
> > Would it be safe to cache the matching cell in the renderer assuming that on the first render both the renderer and the extension side will always have the same ID
> 
> It's safe to cache the matching cell, the renderer won't get a render request from another cell on a re-render.

Thinking some more, caching won't work because the cache will be broken whenever the output is actually re-rendered into something else (e.g. loading a different dataset). Unless we also check the content, which seems to be very over-engineered for just checking which cell the output originated from.

Would it be safe to depend on the execution count in the output item metadata to figure out which cell the output came from?

**Comment by pwang347** [comment] 2023-08-30 17:20
@DonJayamanne @rebornix small ping on the above - thanks!

**Comment by DonJayamanne** [comment] 2023-08-30 21:22
> Would it be safe to depend on the execution count in the output item metadata to figure out which cell the output came from

yes
