### ISSUE TITLE
JSON - no completion proposals inside quotes

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31476] opened 2017-07-26 19:26 UTC
(not sure whether this is a regression)

OK - completion proposals on empty attribute:
![image](https://user-images.githubusercontent.com/172399/28639549-e8ff5988-7248-11e7-80b9-90fc7f59f6ec.png)

NOK - no completion proposal inside string
![image](https://user-images.githubusercontent.com/172399/28639543-e41a03dc-7248-11e7-98cc-1aeca22e2750.png)
![image](https://user-images.githubusercontent.com/172399/28639599-12a5ce34-7249-11e7-89ec-b948902b99a6.png)

**Comment by aeschli** [comment] 2017-08-02 15:42
duplicate of #12848

**Closed by aeschli** 2017-08-02 15:42 UTC
Labels: json
