### ISSUE TITLE
integrated terminal cannot open if the folder is Chinese

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#7052] opened 2016-05-31 10:15 UTC
- VSCode Version: 1.2.0-insider
- OS Version: Win10

Steps to Reproduce:

as the title says

**Comment by Tyriar** [comment] 2016-06-27 21:23
Duplicate of https://github.com/Microsoft/vscode/issues/7727

**Closed by Tyriar** 2016-06-27 21:23 UTC
Labels: bug, i18n, integrated-terminal
