### ISSUE TITLE
macOS ⌘H and ⌘M don’t work for Hide and Minimize

### ISSUE THREAD

**Issue by babramczyk** [microsoft/vscode#130194] opened 2021-08-05 18:06 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.58.2
- OS Version: macOS 11.5

Steps to Reproduce:

Randomly, many times on macOS the ⌘H and ⌘M commands don’t work for the Hide and Minimize actions.

This has been reported as others in [this issue](https://github.com/microsoft/vscode/issues/71800), which may not be getting enough attention, as it’s mis-labled at this point.

I have verified that it happens even when extensions are disabled, and that none of my keyboard shortcuts are conflicting here.

Sometimes happens, sometimes doesn’t. If I quit VS Code and re-open it, it typically fixes it

**Edit:** Some extra context: currently (and I think this is the case frequently), this is only a problem for **1** window. i.e. all VS Code windows can Hide and Minimize properly, except for one. (it could be the first one I opened..? But that’s just a guess)

**Comment by lramos15** [comment] 2021-08-05 18:12
Does yours happen when it's not in a webview?

**Comment by babramczyk** [comment] 2021-08-05 18:44
Yes, doesn’t matter what’s open (a file, a webview, nothing).

Some extra context: currently (and I think this is the case frequently), this is only a problem for **1** window. i.e. all VS Code windows can Hide and Minimize properly, except for one. (it could be the first one I opened..? But that’s just a guess)

**Comment by gjsjohnmurray** [comment] 2021-08-05 18:47
@babramczyk 1.59 shipped. If you're able to update to that it'd be useful to know whether the problem still exists.

**Comment by douira** [comment] 2021-08-05 18:51
Still doesn't work, just tried it with 1.59.

**Comment by babramczyk** [comment] 2021-08-05 18:52
Updated just now. It works fine for now, but like I said in the issue
description, restarting VS Code typically fixed this issue anyway, so
not sure if the update itself fixed it or the restart.

Will report back in a few days 🙂 (or the next time it happens, if it
does)

On August 5, 2021, GitHub Notifications ***@***.***>
wrote:
> @babramczyk <https://github.com/babramczyk> 1.59 shipped. If you're
> able to update to that it'd be useful to know whether the problem
> still exists.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vscode/issues/130194#issuecomment-
893697220>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AEA2LRYUNF4KNDCCGJJDAJTT3LMEVANCNFSM5BULLC7A>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.

**Comment by babramczyk** [comment] 2021-08-05 18:54
Update: just ran into it again, so 1.59 doesn’t appear to have fixed it 😕

**Comment by jacobweber** [comment] 2021-08-05 19:02
It still happens for me with the latest release. It happens when I open a webview like Git Graph, and then continues even after I close it.

**Comment by lramos15** [comment] 2021-08-05 19:22
> It still happens for me with the latest release. It happens when I open a webview like Git Graph, and then continues even after I close it.

Thanks for this, I'm going to close this as duplicate of #71800 but clarify it in the issue

**Closed** 2021-08-05 19:22 UTC
Labels: *duplicate
