### ISSUE TITLE
Settings sync is buggy

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#158904] opened 2022-08-23 13:47 UTC
For whatever reason safari decides that the timeline view should sit in its original location (inside the explorer) and no matter how often I drag it into the bottom panel it eventually reappears inside the explorer

* desktop: drag timeline view into bottom panel
* safari: connect to settings sync (for some reason I need to do that frequently... 🤷 despite using vscode.dev with safari daily)
* desktop: the timeline view reappears in the old location
* repeat...

**Comment by jrieken** [comment] 2022-08-23 13:55
The logs show that safari has pushed this changes (as expected). I think there is a fundamental flaw in that a new or re-connecting client is allowed to push updates which it shouldn't

**Comment by sandy081** [comment] 2022-08-24 08:47
After debugging, I figured out the steps to reproduce this:

- On Machine 1, Move Timeline view to Secondary Sidebar
- Sync Machine 1
- Open vscode.dev and turn on Sync. Make sure Timeline view is in Secondary Sidebar
- Close the vscode.dev window
- Go to Machine 1 and Reset Timeline view (moves to Explorer)
- Move the Timeline view again to Secondary Sidebar
- Make sure it is Synced (wait for a min)
- Go to browser and open vscode.dev and let the sync finish
🐛 Timeline view gets reset to Explorer

On the browser (in the last step) Settings Sync syncs down the data correctly, but the view management is not handling resetting of the timeline view (in the desktop) properly and moving it back to explorer. When desktop resets the timeline view, the view container id of the timeline view changes. The browser has timeline view in the old view container id. View management is not handling this change. This is a bug in view management code which got surfaced by settings sync.

**Comment by sandy081** [comment] 2022-08-24 08:49
Could be related - https://github.com/microsoft/vscode/issues/154090

**Comment by jrieken** [comment] 2022-08-24 09:18
Thanks for investigation ❤️

**Comment by sandy081** [comment] 2022-08-24 19:31
Too early to celebrate 😞 . Above steps are not consistent. When I wrote those steps, I could reliably repro but now I could not. So continuing investigating.

**Comment by sandy081** [comment] 2022-08-25 07:36
@jrieken When it happens next time, can you please the settings sync log of the device that resets the location of the timeline view? I am also self hosting on this set up and keeping an eye on it. 

I am suspecting that this could be similar to #154090. But let's see what the data says. Thanks.

**Comment by sandy081** [comment] 2022-08-27 12:12
I hit this issue today. My views on the desktop got reset to their original locations. This change was pushed by insiders.vscode.dev (safari). I looked at the logs and sync history. Some interesting observations:

1. Even though my system is in sleep, settings sync was running in the web (vscode.dev).
2. Strangely, settings sync is pushing local data to the remote. `[2022-08-27 03:28:17.761] [settingssync] [info] GlobalState: Updated remote ui state`
3. During one sync, there is a big change that all my UI state (only UI state not other user data) got reset. Workspace Trust banner started showing up. All repos, I trusted before are no longer trusted. View locations got reset. This also confirmed by the sync history. @bpasero any idea why the global state got reset? 

I will be trying the same - keeping the machine in sleep - and check again later. This time I have the window opened with trace log and see what it reports.

**Comment by bpasero** [comment] 2022-08-27 15:04
> any idea why the global state got reset?

No, but isn't it your code that applies the global state? I think the storage service is not providing that functionality, maybe a bug there?

**Comment by sandy081** [comment] 2022-08-29 08:30
I read the global state from the storage service and it seems the global state got reset, not by the settings sync but by the browser - I am suspecting either indexedDB got cleared or there is an error reading data from indexedDB.

**Comment by bpasero** [comment] 2022-08-29 09:52
Interesting, that should appear in the logs though right?

**Comment by sandy081** [comment] 2022-08-31 07:33
product logs did not have any info and I missed the dev tool logs as that session was no longer available.

**Comment by sandy081** [comment] 2022-09-02 08:20
I have refactored how views state is stored in this issue - https://github.com/microsoft/vscode/issues/154090. I am hoping that this will also fix any strange behaviour caused by the settings sync. Please use latest insiders (Desktop and vscode.dev) and try again. If you see this issue, please share me with the state resource in the settings sync data view that reset the views. It will be also useful to share the state resources before and after the above state resource. I will also keep looking for it. Thanks.

**Comment by sandy081** [comment] 2022-09-27 17:13
@jrieken May I know if you have seen this issue again after changes mentioned in the above comment?

**Comment by jrieken** [comment] 2022-09-28 10:04
Yes - setting sync is still buggy. I just had it reset all my view customisations, e.g the SCM panel is again full of unwanted views (all git lens), the buttom panel again has the comments panel

**Comment by sandy081** [comment] 2022-09-28 17:24
>  the SCM panel is again full of unwanted views (all git lens), the buttom panel again has the comments panel

May I know how did you configure gitlens views? Have you used the setting from gitlens for default position?

**Comment by jrieken** [comment] 2022-09-29 06:38
I use no gitlens settings, I use the built-in view management via right-click > hide. Also note that the same is happening to the comments panel

**Comment by sandy081** [comment] 2022-10-03 07:34
Closing this and tracking the gitlens issue here - https://github.com/microsoft/vscode/issues/162438

**Closed by sandy081** 2022-10-03 07:34 UTC
Labels: bug, important, papercut :drop_of_blood:
