### ISSUE TITLE
sideways scrolling in jupyter notebooks also scrolls page

### ISSUE THREAD

**Issue by oopsShouldntHaveDoneThat** [microsoft/vscode#122582] opened 2021-04-28 20:34 UTC
Issue Type: <b>Bug</b>

When I have a big plot in a jupyter notebook I can press shift to scroll sideways through the plot. However, the notebook also still scrolls, which is annoying and obviously not the desired behaviour.

Steps to reproduce:
- Create jupyter notebook
-Create very wide plot using pyplot (wider than the vscode window)
-Press shift and scroll while hovering over the plot.

VS Code version: Code - Insiders 1.56.0-insider (9a4d524f909e09079fec7abb82f2efde2172da7c, 2021-04-27T06:13:35.200Z)
OS version: Linux x64 5.11.0-7614-generic

**Comment by rebornix** [comment] 2021-08-05 19:04
/duplicate of https://github.com/microsoft/vscode/issues/115084

**Closed** 2021-08-05 19:03 UTC
Labels: bug, *duplicate, notebook, notebook-output
