### ISSUE TITLE
Too many sync request for settings sync when toggling through themes.

### ISSUE THREAD

**Issue by ShahanM** [microsoft/vscode#138857] opened 2021-12-10 15:23 UTC
Issue Type: <b>Bug</b>

1. Try to change themes by toggling through them and selecting to see the changes.
2. Settings tries to sync on every call.
3. Sync crashes because of too many requests in a short time.

Expectation: The sync shouldn't be sending a request on every change.

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.13.0-7620-generic
Restricted Mode: No

**Comment by gjsjohnmurray** [comment] 2021-12-10 21:34
/duplicate of #91286

Maybe this new 1.63 feature avoids the problem (untested by me):

https://code.visualstudio.com/updates/v1_63#_preview-themes-before-installing

**Closed** 2021-12-10 21:35 UTC
Labels: *duplicate

**Comment by ShahanM** [comment] 2021-12-11 07:30
> /duplicate of #91286
> 
> Maybe this new 1.63 feature avoids the problem (untested by me):
> 
> https://code.visualstudio.com/updates/v1_63#_preview-themes-before-installing

Thanks! I am sorry for the duplicate report. I used the report feature directly from VSCode. I will check out the patch.

**Comment by sandy081** [comment] 2022-01-20 15:04
@ShahanM Can you able to repro this? If so can you please share the following log:

> F1 > Open View... > Log (Settings Sync)
