### ISSUE TITLE
`collapseExplorerFolders` has no effect when sidebar is closed

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#117391] opened 2021-02-23 13:33 UTC
- VS Code Version: 1.53.2
- OS Version: macOS 11.2.1

Steps to Reproduce:

1. Open some files to expand the folder tree in the explorer
2. Run command `View: Close Side Bar` (`workbench.action.closeSidebar`)
3. Run command `Collapse Folders in Explorer` (`workbench.files.action.collapseExplorerFolders`)
4. Open the sidebar again

Expected: the folders in explorer are collapsed

Actual: the folders in explorer are not collapsed

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2021-02-23 15:41
Yes I can reproduce this.
The issue is that the `ViewPane` action [here](https://github.com/microsoft/vscode/blame/main/src/vs/workbench/browser/parts/views/viewPane.ts#L611) only takes the active view.
I believe the viewPane action should take the view even if it is not active. Thus also assigning to @sandy081 

Alternative would be that the `Collapse Folders in Explorer` is not a `ViewPane` action which would be strange

**Comment by sandy081** [comment] 2021-02-24 11:31
@isidorn It is expected that  `ViewAction` is scoped to active view ie., when view is visible. We cannot assume view is available or functional when it is not visible because, for eg., views can dispose some functionality when they are not visible and retain when they are made visible again. 

In this case this action seems like a global action that user can perform even when view is not visible. I would suggest to register this as a regular Action2 and use `IViewsService.getViewWithId` api I just added for this case.

**Comment by isidorn** [comment] 2021-02-24 11:57
@sandy081 that's fair. I will change to `Action2`

**Closed** 2021-02-24 14:52 UTC
Labels: bug, file-explorer
