### ISSUE TITLE
Integrated Terminal frozen at launch, showing only cursor

### ISSUE THREAD

**Issue by willielee** [Microsoft/vscode#36098] opened 2017-10-11 22:28 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (3ffa14e5ed86b3489f86d9f8d966ae3076f94a61, 2017-10-11T05:26:57.467Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Launch Code
2. Launch Integrated Terminal

Developer Tools > Console :  

`2C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
quickOpenScorer.ts:114 [Violation] 'keydown' handler took 795ms
`

![vscodeintegratedterminal](https://user-images.githubusercontent.com/14075798/31469899-a44d768a-aeb1-11e7-88fc-e5b25c3f2f2c.PNG)

Also reproduced in VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)

`2C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event 
![vscodeintegratedterminal](https://user-images.githubusercontent.com/14075798/31469889-9a4074da-aeb1-11e7-85b7-ca095eb1fb96.PNG)
handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] 'setTimeout' handler took 846ms`

No User Settings
Using Default Setting:
`  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",`

**Comment by Tyriar** [comment] 2017-10-12 15:12
I believe this is a duplicate of https://github.com/Microsoft/vscode/issues/34554, tomorrows Insiders should have the fix for that and it would be great if you could validate it 😃

**Closed by Tyriar** 2017-10-12 15:12 UTC
Labels: duplicate

**Comment by willielee** [comment] 2017-10-12 15:22
Thank you for looking into this.
It doesn't seem like a duplicate of #34554 because I tried to resize the window, but it did not help.  I also tried to reinstall Code.  I even deleted the $HOME\AppData\Roaming\Code folder after uninstalling.
I will try tomorrow's Insiders.
    On Thursday, October 12, 2017, 11:13:47 AM EDT, Daniel Imms <notifications@github.com> wrote:  
 
 
I believe this is a duplicate of #34554, tomorrows Insiders should have the fix for that and it would be great if you could validate it 😃

**Comment by willielee** [comment] 2017-10-14 04:19
I tried today's Insiders and problem still exists.


Developer Tools > Console message:
`C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1381 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1381 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules\xterm\lib\Terminal.js:1381 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
quickOpenScorer.ts:114 [Violation] 'keydown' handler took 811ms`

![vscodeintegratedterminal2](https://user-images.githubusercontent.com/14075798/31572485-370169ae-b075-11e7-93c8-cb78aba5795c.PNG)

Thank you for looking into this.
