### ISSUE TITLE
Cannot search for new line character using find

### ISSUE THREAD

**Issue by holyman2k** [Microsoft/vscode#4894] opened 2016-04-04 01:02 UTC
- VSCode Version: 0.10.11 (0.10.11)
- OS Version: OSX 10.11.4 (15E65)

Steps to Reproduce:

1. open code 
2. in a new file type "hello
world" (hello [new line]world)
3. edit -> find
4 in search box type "\n" and select regular express

nothing is found but there is a new line character in the text file

**Comment by alexandrudima** [comment] 2016-04-04 07:52
Thank you for filing this. Duplicate of #313

**Closed by alexandrudima** 2016-04-04 07:52 UTC
