### ISSUE TITLE
Dropdown rendering issue on first use

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#37405] opened 2017-11-01 12:53 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
python|don|0.7.0
pgsql|dou|0.0.8
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.0.5
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|3.4.0
code-spell-checker|str|1.4.12

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open the Output panel.
2. Open the dropdown.

![image](https://user-images.githubusercontent.com/1658949/32275579-112cd088-bf0c-11e7-821c-6be2da6451cc.png)

**Comment by isidorn** [comment] 2017-11-01 14:53
Duplicate of a well known issue. Please search our repository for it.
It is bascially coming from electron,

**Closed by isidorn** 2017-11-01 14:53 UTC
Labels: workbench
