### ISSUE TITLE
Starting VS Code got slower

### ISSUE THREAD

**Issue by cherchyk** [Microsoft/vscode#4325] opened 2016-03-16 16:09 UTC
- VSCode Version: 0.10.11
- OS Version: w7

is it just me?
I found VSC very slow after previous update

**Comment by bpasero** [comment] 2016-03-16 17:06
@cherchyk what specifically feels slower?

**Comment by mohsen1** [comment] 2016-03-16 18:32
For me, startup is slow. Even if I have an instance of Code open, opening another instance takes a good 5 seconds. I'm on a MacBook Air

**Comment by bpasero** [comment] 2016-03-16 18:39
@mohsen1 is F1 > Reload Window also slow? because if yes, we could do some profiling.

**Comment by mohsen1** [comment] 2016-03-16 18:57
Yes, it's slow when reloading as well. From CLI, opening the shell takes another 2~3 seconds on top of this

Screen capture
https://gfycat.com/NeighboringGloomyDassie

**Comment by bpasero** [comment] 2016-03-16 19:21
@mohsen1 can you open dev tools (Help > Toggle Developer Tools), click on the Profiles tab, click on the "Start" button, run the "Reload Window Action" and then press stop and then "Save" on the left hand side and attach the file (as zip is fine) here?

**Comment by mohsen1** [comment] 2016-03-16 19:34
[CPU-20160316T123357.cpuprofile.zip](https://github.com/Microsoft/vscode/files/176742/CPU-20160316T123357.cpuprofile.zip)

**Comment by bpasero** [comment] 2016-03-16 19:46
@mohsen1 any extensions installed? does it reproduce with starting from the command line with "--disable-extensions"?

**Comment by cherchyk** [comment] 2016-03-16 19:50
moving cursor up and down is slow for me.

**Comment by mohsen1** [comment] 2016-03-16 19:58
I have a couple of extensions

![Uploading Screen Shot 2016-03-16 at 12.54.29 PM.png…]()

Can't try without extensions since my `code` alias does not accept an argument...

**Comment by bpasero** [comment] 2016-03-16 21:01
It should...

**Comment by mohsen1** [comment] 2016-03-16 21:27
It's the same speed. I used this command:

```
open -n -b "com.microsoft.VSCode" --args --disable-extensions
```

I use fish. I am too lazy to fix the alias to pass flags to actual executable...

**Comment by bpasero** [comment] 2016-03-17 06:16
Can you guys please double check that the speed is indeed faster with the previous release: https://github.com/Microsoft/vscode/wiki/Previous-Releases

Also attach the profile for the previous release?

**Comment by bpasero** [comment] 2016-03-17 07:07
@cherchyk @mohsen1 got a better idea, can you do this for Code 0.10.8 and latest:
* reboot your machine to have a fresh start
* go into the folder where code.exe lives
* run `code.exe -p`
* in the window type `Ctrl+Shift+P` and pick `Developer: Startup Performance`
* attach a screen shot of the numbers showing (see below for example)

![image](https://cloud.githubusercontent.com/assets/900690/13838845/5abda43a-ec17-11e5-9d82-d69d732e436b.png)

**Comment by bpasero** [comment] 2016-03-18 11:04
@cherchyk @mohsen1 ping

**Comment by mohsen1** [comment] 2016-03-18 19:39
@bpasero I'll do it today. I want to do it on my slower machine (MacBook Air) since on my Mac Pro it's pretty fast

**Comment by cherchyk** [comment] 2016-03-19 03:20
looks like it my machine

**Comment by bpasero** [comment] 2016-03-19 06:34
@cherchyk sorry, what does your comment mean?

@mohsen1 thanks!

**Comment by mohsen1** [comment] 2016-03-19 18:27
@bpasero should I pass `-p` to `Electron` executable on my Mac?

**Comment by mohsen1** [comment] 2016-03-19 18:33
I can't pass `-p` to the executable in OS X. Tried:

```
open -a 'Visual Studio Code' --args '-p' .
```

or 
```
/Applications/Visual Studio Code.app/Contents/MacOS/Electron -p
```

with no luck.

**Comment by bpasero** [comment] 2016-03-20 09:00
@mohsen1 you still need to invoke the action "Developer: Startup Performance" from the command palette.

**Comment by csholmq** [comment] 2016-03-20 11:19
OS X 10.11.3 running VSCode Insiders 0.10.12.

`code-insiders -p`

Then executed `>Developer: Startup Performance`.

![screen shot 2016-03-20 at 12 18 21](https://cloud.githubusercontent.com/assets/1297882/13904110/e3e05764-ee95-11e5-93af-51643772260d.png)

**Comment by csholmq** [comment] 2016-03-20 11:39
OS X 10.11.3 running VSCode 0.10.11.

`code -p`

Then executed `>Developer: Startup Performance`.

![screen shot 2016-03-20 at 12 38 21](https://cloud.githubusercontent.com/assets/1297882/13904199/aa6b79ac-ee98-11e5-8a61-df0dba9c7028.png)

**Comment by csholmq** [comment] 2016-03-20 11:53
OS X 10.11.3 running VSCode 0.10.10.

`code -p --disable-extensions`

Then executed `>Developer: Startup Performance`.

![screen shot 2016-03-20 at 12 52 16](https://cloud.githubusercontent.com/assets/1297882/13904258/9d031ffc-ee9a-11e5-8133-6965a4aafa4f.png)

Wasn't able to install 0.10.9 to PATH so I stopped at 0.10.10.

**Comment by bpasero** [comment] 2016-03-21 09:20
@csholmq thanks much, the numbers though do not show any slowdown. the interesting number is "Total" which is the time it takes until all things are loaded. Can you see that after ~3 seconds the UI has loaded?

**Comment by csholmq** [comment] 2016-03-21 21:57
@bpasero From what I can determine, it seems to correlate.

**Comment by bpasero** [comment] 2016-03-22 05:59
Closing, as the numbers do not show any slowdown.

**Closed by bpasero** 2016-03-22 05:59 UTC
Labels: bug, important, needs more info

**Comment by ggwilly** [comment] 2016-11-13 19:11
VsCode version 1.7 VmWare VM 4.0GB ram, W7 32Bits OS
[https://dl.dropboxusercontent.com/u/108342291/Captura.PNG](url)

**Comment by jaichaturvedi88** [comment] 2016-12-27 04:58
I got same issue. Can you please check. Below is the screenshot of startup performance measurement.
I did as instructed above. I restarted my system then captured the logs

![image](https://cloud.githubusercontent.com/assets/14929140/21490937/f5f6e71c-cc1e-11e6-977d-490fe89fb0f3.png)

**Comment by bpasero** [comment] 2017-01-02 09:31
@jaichaturvedi88 is that a single CPU machine?
