### ISSUE TITLE
contributes.breakpoints support providing language as a document selector

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#50532] opened 2018-05-27 17:42 UTC
Hi,

I'm developing a debug adapter for assembler files.
I have a contribute section in package.json which allows to set breakpoint in various files (extensions).
Everything is working as expected when I debug the debug-adapter. I.e. I can set breakpoints in .asm files.
But when I create a package (vsix) and install it in vscode I'm not able to set breakpoints anymore in .asm files.

Here is the json:
```json
"contributes": {
		"languages": [
			{
				"id": "asm-collection",
				"extensions": [
					".list",
					".a80",
					".asm",
					".inc",
					".s"
				],
				"aliases": [
					"Assembler file"
				]
			}
		],
		"breakpoints": [
			{
				"language": "asm-collection"
			}
		],
		"commands": [],
```

I'm still able to set breakpoints in .list files but not in .asm files.

**Comment by isidorn** [comment] 2018-05-30 09:13
The file extensions should nicely get merged and if you enable breakpoints for `.a80` via the breakpoint contribution that should work.
If it does not, disable other extensions one by one until you find a nice reproducable case so I can just install two extensions and see the behavior your are seeing.

Make sure you are using vscode insiders

**Comment by maziac** [comment] 2018-05-30 16:32
Yes, the problem exists also on insiders.

You can do the following to reproduce:
1. Install my extension v0.1.0 from here: https://github.com/maziac/z80-debug/releases
(Make sure you install version 0.1.0, the higher versions have an ugly workaround for this problem.)
2. Create an empty asm file, e.g. test.asm with a few empty lines and save it.
3. Hover over the breakpoint area, you should see a red dot following the mouse cursor. Or click in the breakpoint area. The red dot appears persistently.
4. Now install the "Z80 Macro-Assembler" extension v0.3.1 (the current one) from the market place
5. Try hovering or setting breakpoints in test.asm.
Result: Setting breakpoints does not work anymore.

**Comment by isidorn** [comment] 2018-05-31 08:55
@maziac thanks for providing nice reproducable steps this is really helpful.
The issue is not with the debug contribution but with the language contribution, both your extension and the other extension contribute a language for the `.asm` files. Your extension calls it "asm-collection" the other extension calls it "z80-macroasm"
As for which extension wins in the language override battle the best would be @jrieken 
to answer, but I believe this is designed behavior.

As a workaround you can either use a same langauge name or you can update your extensions `package.json` to have the following breakpoints section

```json
"breakpoints": [
		{
			"language": "asm-collection"
		},
		{
			"language": "z80-macroasm"
		}
	]
```

**Comment by maziac** [comment] 2018-05-31 09:02
Yes, this is the "ugly" workaround I'm using at the moment.
Of course I can include all the language names of other extension that might use same file extensions, but
a) how do I find all extensions. I.e. can I search extensions for file extension contributions and
b) what if I really included everything and later a new extension comes up with another language name. This would break my functionality.
I think there should be some better solution to this problem, an extension should not depend on other extensions in this respect.

**Comment by isidorn** [comment] 2018-05-31 09:17
Unfortunetly not sure if there is something better we can do since that is the only language identifier we are getting from the editor model - and that identifier can be overwritten by various extensions.
Maybe @jrieken or @weinand have a better suggestion

**Comment by weinand** [comment] 2018-05-31 09:36
If a file extension (e.g. ".asm") is shared by many languages, an extension cannot "know" all those languages. 
The only way around this is to support "breakpoints" contributions based on extensions, e.g. something like:
```json
"breakpoints": [
	{
		"language": "asm-collection"
	},
	{
		"extension": ".asm"
	}
]
```

**Comment by isidorn** [comment] 2018-05-31 09:42
@weinand thanks for the suggestion, I also had something like that in mind, but the `.asm` is not exposed via `editor.getModel()` afaik. I can only get the "asm-collection" as the identifier.

**Comment by weinand** [comment] 2018-05-31 09:44
Yes, that's the reason why Ive asked Alex to chime in.

**Comment by alexandrudima** [comment] 2018-05-31 09:58
@isidorn The URI of the buffer is at `editor.getModel().uri`, so if you wanted to support something like targeting certain extensions (as sketched in https://github.com/Microsoft/vscode/issues/50532#issuecomment-393474134), you could potentially use the model's URI and match it against the rules.

From an API point of view, this reminds me of document selectors, but document selectors are in code and never showed up in JSON. cc @jrieken if he has any ideas how to make things more similar.

**Comment by jrieken** [comment] 2018-05-31 10:12
Yeah, smells like document selectors. Currently we only use them in code but they are kind of constant and they can be written as json. So, the `breakpoints` contribution point should simply interpret the value as document selector

**Comment by isidorn** [comment] 2018-05-31 10:18
Reopening this as a feature request and renaming

**Comment by maziac** [comment] 2018-08-23 17:42
Any idea when there will be a solution for this?

**Comment by isidorn** [comment] 2018-08-24 07:10
This is not on our immediate plan. So no idea.

**Closed** 2018-09-20 16:02 UTC
Labels: *out-of-scope, debug, feature-request

**Comment by maziac** [comment] 2018-09-20 17:56
Sorry to hear that.
Please re-consider your decision.
The reason why this does not get so many upvotes is that the current way of selection seems to work unless you install another extension which uses similar file extensions.
And the other problem is that there is no language defined for assembler and the developer has to do it himself.
So for all the other extension provider developers there is no problem. Only for the assembler extensions.
And the real bad thing is: there is not any usable workaround. The one described here works only partly and disables functionality in the other extension which is also not a good idea.
**The simplest way would be to provide a language ID for assembler. This, I guess, shouldn't be too much effort.**

It simply does not make sense to me to develop for vscode (and I love to do that) if the extension cannot be used by anyone afterwards.
It's very common to install several extensions for one language, e.g. I need another extension for highlighting.
Now I have to decide: Do I want to have syntax highlighting or do I want to use my debug-adapter.
