### ISSUE TITLE
files.include setting OR a [^] "not" character class in files.exclude setting

### ISSUE THREAD

**Issue by bovorasr** [Microsoft/vscode#32039] opened 2017-08-04 21:15 UTC
My use case is that VS Code is great for markdown. I want to be able to open a root folder and *only* show markdown or image files, but ignore everything else. 

Currently, with project settings, you can exclude certain files, but I essentially want the opposite: a setting that will only show files that matter for editing w/in VS Code (in this case, the markdown files). 

As an example, imagine wanting to document your 'My Documents' folders, or your Dropbox folder, etc. with markdown, but not actually wanting to open all files at the root of 'My Documents' in the context of VS Code. You just want to see the overlayed markdown  as use it as a "local wiki", which may or may not contain links to those files.

**Comment by mjbvz** [comment] 2017-08-04 22:09
Duplicate of #869

**Closed by mjbvz** 2017-08-04 22:09 UTC
Labels: duplicate, workbench
