### ISSUE TITLE
Angular's "::ng-deep" breaks syntax highlighting in scss files

### ISSUE THREAD

**Issue by ilyakonrad** [microsoft/vscode#208881] opened 2024-03-27 09:35 UTC
It's all in the title. The issue is pretty old. Here's [the original one](https://github.com/microsoft/vscode/issues/55099) that [has been moved](https://github.com/atom/language-sass/issues/254) to a recently archived language-sass repo.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows_NT x64 10.0.22631

<br>
<img width="245" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/e858e923-509a-49be-945e-d66ee42f1c9f">
<br>
<img width="250" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/7bec1de3-6b8c-470f-a6a7-56ee858ede1a">
<br>
<img width="254" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/4502ccdb-df68-4e68-bee4-6c7cdc4388b1">
<br>
<img width="517" alt="image" src="https://github.com/microsoft/vscode/assets/25200186/6270ff26-c53d-4cf6-a633-1cc670dbe954">

Steps to Reproduce:

1. Just use `::ng-deep` 😄

**Comment by aeschli** [comment] 2024-03-27 10:20
Unfortunately we still don't have an alternative to https://github.com/atom/language-sass

**Comment by alexr00** [comment] 2024-03-27 12:01
Yep, we need to find a new scss grammar. Marking as a duplicate of https://github.com/microsoft/vscode/issues/81038, so that when we find a new option we can check on this issue.

**Closed by alexr00** 2024-03-27 12:02 UTC
