### ISSUE TITLE
Create an API for embedding a native window inside a panel

### ISSUE THREAD

**Issue by GinoMan** [microsoft/vscode#100616] opened 2020-06-20 01:11 UTC
### The use case:
I'm working on learning Flutter development and I have the emulator up while I work on my code. I'm however noticing that the emulator can be set to always be on top, but that covers part of the window. It wouldn't be so bad though if I could embed the emulator as a pane in VSCode off to the side. 

I'm thinking of something that would look like this:
![Embedded Emulator Sample](https://user-images.githubusercontent.com/528834/85187848-e36eeb80-b270-11ea-959c-0eec9f82f8e8.png)

### Options:
One way of doing this would be to create an API for embedding an arbitrary native UI Into a pane. This would allow the embedding of many applications in the same window for such a use case. 

Another way would be to set up a transparency area under which the native UI would run and pass input through to it. 

Thoughts?

**Comment by alexr00** [comment] 2020-06-22 15:12
Duplicate of https://github.com/microsoft/vscode/issues/83911

**Closed by alexr00** 2020-06-22 15:12 UTC

**Comment by GinoMan** [comment] 2020-07-11 02:36
I disagree that this is per-se a duplicate. 

#83911 is only a "custom webview" which would work for embedding say another electron app's content. This instead would allow native windows for the OS. Though given the design I described in the contrived screenshot above, it would likely depend upon that feature request being implemented to host it for the buttons. I doubt a "custom webview" would allow you to embed the android emulator for example as described above.

**Comment by alexr00** [comment] 2020-07-13 08:47
@GinoMan I see what you're saying (arbitrary native applications, not arbitrary UI). Embedding native applications inside VS Code isn't something we plan on doing. While I understand why it would be useful, it is out of scope for VS Code.

**Comment by BinToss** [comment] 2023-05-11 23:08
This may be a requirement for implementing an equivalent to "Blend for Visual Studio".

**Comment by edgardozoppi** [comment] 2024-01-06 17:16
I agree that this feature will bring a lot of new possibilities to VS Code extensions and allows it to integrate even further with already existing external apps implemented using other technologies.
In particular will improve the flow of game console development by allowing emulators to be embedded right inside the VS Code GUI. Also mobile app development using emulators.
