### ISSUE TITLE
clicking the heading in the outline will not jump

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#122482] opened 2021-04-28 00:22 UTC
@hainingpan commented on [Tue Apr 27 2021](https://github.com/microsoft/vscode-jupyter/issues/5657)

## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.788523236
-   Python Extension version (available under the Extensions sidebar): v2021.5.771128439-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10.0.19042 x64 using WSL 2
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

Previously, clicking the headings in the Outline will jump to the corresponding section. 

## Actual behaviour

After recent updates, it fails to jump. However, other types of files are still working properly.  Only ipynb does not work.

## Steps to reproduce:

1. Create a markdown cell and write `# Title 1` 
2. Create another markdown cell with `# Title 2`
3. Insert a long cell in-between to make sure two markdown cells are separated by more than one pages
4. Click the headings in the outline on the left , and nothing happens.
5. Click the headings on the top of the jupyter notebook UI, and it can jump.

![vscode_jupyter](https://user-images.githubusercontent.com/22186947/116317771-c99c1000-a781-11eb-830d-1d5a4856779d.gif)

## Logs

Nothing is generated.

---

@IanMatthewHuff commented on [Tue Apr 27 2021](https://github.com/microsoft/vscode-jupyter/issues/5657#issuecomment-828045515)

@hainingpan Thanks for filing this. I repro the same thing. I believe that VS Code core would own this navigation, so I'm going to move this bug over to their repo.

**Comment by gjsjohnmurray** [comment] 2021-04-28 05:57
Looks like a duplicate of #122480

**Comment by jrieken** [comment] 2021-04-28 07:36
Yeah, /duplicate

**Closed** 2021-04-28 07:37 UTC
Labels: *duplicate, notebook
