### ISSUE TITLE
Problem links to files in WSL are broken?

### ISSUE THREAD

**Issue by Quatrixx** [microsoft/vscode#96950] opened 2020-05-04 23:19 UTC
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. follow [this tutorial](https://code.visualstudio.com/docs/cpp/config-wsl) except with own source code instead of the helloworld
2. have an error in your code
3. switch to the "Problems" panel
4. click the listed Problem to jump to it
<details>
<summary>5. this happens: (expand for image)</summary>

![image](https://user-images.githubusercontent.com/61820125/81022749-b3a98700-8e6e-11ea-9b70-d810f70b571d.png)

</details>

There are 2 versions of the same file listed in the Problems panel, but one of them has a part of the filepath duplicated, so VScode can't find it. Any idea how to fix this? It's really confusing as someone just getting started with this. Also, I hope this wasn't completely the wrong place to post this... Thanks

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18362 (i have no idea why it thinks this, I am on Win10 Pro 1903)
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.22GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/alex/projects/b --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3501)|
|Memory (System)|15.87GB (9.22GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.27.1
remote-wsl|ms-|0.44.2

</details>

**Comment by sandy081** [comment] 2020-05-05 16:28
Forwarding to you as this looks path related issues. Could be also an issue with in the extension/

**Comment by aeschli** [comment] 2020-05-05 19:58
The problem has a wrong resource path ('/home/alex/projects/b` is repeated).
Maybe a problem matcher issue? @alexr00 

@Quatrixx When you run the build (https://code.visualstudio.com/docs/cpp/config-wsl#_running-the-build) with the error, what does the terminal show?

**Comment by Quatrixx** [comment] 2020-05-05 20:34
I didn't have the old file anymore, but I mean I get the issue regardless of the file so I used another one. Here's the output when I don't have any errors in the code:

```
> Executing task: /usr/bin/gcc -g /home/alex/projects/password/password_checker.c -o /home/alex/projects/password/password_checker <


Terminal will be reused by tasks, press any key to close it.
```

<details>
<summary>here's one where I deleted some characters from the file so it has a Problem to show, but that's basically the same, right?</summary>

```
> Executing task: /usr/bin/gcc -g /home/alex/projects/password/password_checker.c -o /home/alex/projects/password/password_checker <

/home/alex/projects/password/password_checker.c: In function ‘main’:
/home/alex/projects/password/password_checker.c:40:9: warning: implicit declaration of function ‘pri’ [-Wimplicit-function-declaration]
         pri("\n Wrong Password \n");
         ^~~
/tmp/ccOWA3GY.o: In function `main':
/home/alex/projects/password/password_checker.c:40: undefined reference to `pri'
collect2: error: ld returned 1 exit status
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

</details>

**Comment by aeschli** [comment] 2020-05-06 07:52
Thanks @Quatrixx. I think that's a dup of #80108

**Comment by alexr00** [comment] 2020-05-06 07:57
It is a duplicate of #80108 .
You should be able to update your task in tasks.json to include:
```
"problemMatcher": {
				"base": "$gcc",
				"fileLocation":"absolute"
			}
```
To solve it.

**Closed** 2020-05-06 07:56 UTC

**Comment by Quatrixx** [comment] 2020-05-06 10:36
That's it! Thank you guys so much
