### ISSUE TITLE
Terminal.open was called on an element that was not attached to the DOM

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#88529] opened 2020-01-13 09:10 UTC
* hide panel
* run rename with preview
* accept or discard changes
* the message below shows on the console

```
/Users/jrieken/Code/vscode/node_modules/xterm/lib/xterm.js:1 xterm.js: Terminal.open was called on an element that was not attached to the DOM

e._log | @ | /Users/jrieken/Code/…term/lib/xterm.js:1
-- | -- | --
  | e.warn | @ | /Users/jrieken/Code/…term/lib/xterm.js:1
  | t.open | @ | /Users/jrieken/Code/…term/lib/xterm.js:1
  | e.open | @ | /Users/jrieken/Code/…term/lib/xterm.js:1
  | (anonymous) | @ | terminalInstance.js:457
  | Promise.then (async) |   |  
  | _attachToElement | @ | terminalInstance.js:445
  | attachToElement | @ | terminalInstance.js:436
  | SplitPane | @ | terminalTab.js:164
  | _addChild | @ | terminalTab.js:89
  | split | @ | terminalTab.js:35
  | (anonymous) | @ | terminalTab.js:296
  | attachToElement | @ | terminalTab.js:296
  | TerminalTab | @ | terminalTab.js:207
  | _createInstance | @ | instantiationService.js:88
  | createInstance | @ | instantiationService.js:59
  | createTerminal | @ | terminalService.js:527
  | (anonymous) | @ | terminalPanel.js:73
  | fire | @ | event.js:458
  | setVisible | @ | composite.js:97
  | showComposite | @ | compositePart.js:164
  | doOpenComposite | @ | compositePart.js:69
  | openComposite | @ | compositePart.js:42
  | openPanel | @ | panelPart.js:238
  | openComposite | @ | panelPart.js:37
  | resetActiveComposite | @ | compositeBar.js:167
  | hideComposite | @ | compositeBar.js:107
  | hideComposite | @ | panelPart.js:170
  | onDidChangeActiveViews | @ | panelPart.js:128
  | (anonymous) | @ | panelPart.js:101
  | fire | @ | event.js:458
  | async function (async) |   |  
  | _previewEdit | @ | VM286 bulkEdit.contribution.js:44


```

**Comment by jrieken** [comment] 2020-01-13 09:12
When happens behind the scenes is that the preview panel hides via context key changes and that it hides the panel unless it was showing before. I guess that in-between these two steps the terminal starts to render

**Comment by Tyriar** [comment] 2020-01-13 14:50
> run rename with preview

Not sure how to do this? I tried rename and it didn't happen.

The stack is showing that it's happening when you split a terminal, are you sure this log didn't appear from doing something else?

**Comment by jrieken** [comment] 2020-01-13 14:53
You need latest, latest insider. Rename and you'll see the flow for refactor preview, e.g Shift+Enter
<img width="436" alt="Screenshot 2020-01-13 at 15 53 20" src="https://user-images.githubusercontent.com/1794099/72265451-d3e1db80-361c-11ea-9207-899315f85efb.png">

**Comment by Tyriar** [comment] 2020-01-13 15:05
@jrieken hmm, I'm on latest and tried on both WIndows/Mac and it still didn't happen. I also tried focusing terminal, hiding panel and reloading and it didn't make a difference.

@isidorn @sandy081 @sbatten why in the trace above would `openComposite`/`showComposite` end up being triggered by a call to `hideComposite`? My guess is this problem is happening because the panel is showing and hiding very quickly but understanding what `CompositeBar` is doing might make it easier to reproduce.

**Comment by sandy081** [comment] 2020-01-14 06:59
This is because `refactor preview` panel got removed and panel part is trying to open the default panel which is terminal panel.

**Comment by Tyriar** [comment] 2020-01-14 15:28
@sandy081 seems like a flaw in the panel system to me. Opening and closing (removing) the refactor panel should not show the terminal panel as that creates a process.

**Comment by jrieken** [comment] 2020-01-14 15:31
@Tyriar idk... I could programmatically and thereby very quickly show and hide the terminal and I have a strong feeling that exactly this would happen then.

**Comment by Tyriar** [comment] 2020-01-14 16:01
@jrieken sure, I should add a check too I guess. Note this is just a warning and it's not a big deal, it is revealing a problem in that a terminal process is being created when it shouldn't though. Moving that discussion to https://github.com/microsoft/vscode/issues/88613

**Comment by sandy081** [comment] 2020-01-14 17:48
@Tyriar I don't think so. It is expected and this is same in side bar.

**Comment by Tyriar** [comment] 2020-01-14 20:10
@sandy081 why trigger setVisible(true) followed immediately by setVisible(false)?

**Comment by sandy081** [comment] 2020-01-15 10:28
@Tyriar can you please check what is triggering `setVisible(false)` ? Could be somebody is hiding the panel?

**Comment by Tyriar** [comment] 2020-01-15 15:09
@sandy081 looks like the panel doesn't hide anymore so it's no longer a problem.

**Comment by Tyriar** [comment] 2020-04-10 14:53
This warning is mostly harmless now anyway, I changed it to debug level in https://github.com/xtermjs/xterm.js/pull/2825. Will close this when xterm is updated

**Closed** 2020-04-11 00:15 UTC
Labels: bug, integrated-terminal, upstream, upstream-issue-linked

**Comment by jrieken** [comment] 2020-04-30 10:25
haven't seen this anymore
