### ISSUE TITLE
Reindent HTML ugly

### ISSUE THREAD

**Issue by donnygunawan93** [Microsoft/vscode#17241] opened 2016-12-15 05:56 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.3.6|

---

Steps to Reproduce:
still good...
![1](https://cloud.githubusercontent.com/assets/10414213/21213237/a2cda2c2-c2c5-11e6-9e6e-99ebdec4c283.png)
auch...
![2](https://cloud.githubusercontent.com/assets/10414213/21213240/a4c3fa04-c2c5-11e6-8542-72f8a1ab4837.png)

**Comment by chriswoodle** [comment] 2016-12-15 23:17
#17213

**Comment by kieferrm** [comment] 2016-12-16 01:17
Duplicate of #17241.

**Closed by kieferrm** 2016-12-16 01:17 UTC
