### ISSUE TITLE
Notebook language icons missing for .NET

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#115120] opened 2021-01-26 19:00 UTC
Testing #114902

Unsure if this something the extensions have to set, but python has their language icon for code cells:

![image](https://user-images.githubusercontent.com/35271042/105891489-8d5fe480-5fc5-11eb-8a2c-eca2b4a1c262.png)

And .NET has the default:

![image](https://user-images.githubusercontent.com/35271042/105891521-98b31000-5fc5-11eb-8b49-00285b914aec.png)

![image](https://user-images.githubusercontent.com/35271042/105891539-9d77c400-5fc5-11eb-96aa-cbbdaa3af134.png)

**Comment by jrieken** [comment] 2021-01-27 08:02
I will take a look but it's like that no icon is defined that therefore the default icon is used. Outline simply uses the theme service for this

**Comment by jrieken** [comment] 2021-01-27 15:20
Adding @aeschli 

The same issue can be observed for with GH issue notebooks, which also have a special icons. What's special with notebooks is that they don't have file names from which to derive an icon but the use the language name, e.g [getIconClassesForModeId](https://github.com/microsoft/vscode/blob/23579d815faa6712bf7c628bad25d4a4eb4a2dbc/src/vs/editor/common/services/getIconClasses.ts#L58-L58), and I am unsure if that has a bug or if themes must do something here


<img width="257" alt="Screenshot 2021-01-27 at 16 19 12" src="https://user-images.githubusercontent.com/1794099/106012170-6edc1500-60bb-11eb-90d2-d7b5186b0a1a.png">

**Comment by aeschli** [comment] 2021-01-27 22:35
@misolori What exact theme are you using? Some themes don't define icons for language ids, but just for file extensions.

**Comment by misolori** [comment] 2021-01-27 22:56
@aeschli I'm using default (seti)

**Comment by aeschli** [comment] 2021-01-28 07:56
Can you inspect what the class names for label node are?

**Comment by jrieken** [comment] 2021-01-28 15:32
> Can you inspect what the class names for label node are?

@aeschli you can check that yourself when using GH issue notebooks

**Comment by aeschli** [comment] 2021-02-02 23:11
We don't have a language called `github-issues`.. But Seti has an icon icon for the file extension `github-issues`.

This can be fixed by adding a language `github-issues`, and regenerate the seti-theme. 

However, having a language `github-issues` probably doesn't make much sense except for the icon case.
Therefore I'll add that language just in the seti font build script where I have a list of ["nonBuiltIn" languages.](https://github.com/microsoft/vscode/blob/a105ccb436397b701a39edcab351f6c1383e3016/extensions/theme-seti/build/update-icon-theme.js#L14)

Fixed as as part of cba8232d778fe751d69edab7536bf89b66906caa

**Comment by aeschli** [comment] 2021-02-02 23:13
Still need to check what's the problem with .net notebook.

**Comment by jrieken** [comment] 2021-02-03 08:23
> However, having a language github-issues probably doesn't make much sense except for the icon case.

@aeschli that language exists but it is contributed by an extensions: https://github.com/microsoft/vscode-github-issue-notebooks/blob/27bf6ea885bdb983567013fa4d6489995c014c09/package.json#L41

**Comment by aeschli** [comment] 2021-02-03 10:52
The C# interactive notebook uses `dotnet-interactive.csharp` as language, which of course is not known to the seti-theme.
Couldn't/shouldn't they use csharp as language for the cell?

**Comment by aeschli** [comment] 2021-02-22 20:55
The issue is in the C# extension, closing the issue

**Closed by aeschli** 2021-02-22 20:55 UTC
Labels: themes

**Comment by aeschli** [comment] 2021-02-22 21:03
To verify, open the outline for a Github notebook as described [here](https://github.com/microsoft/vscode/issues/115120#issuecomment-768358185) and verify that you see the Github Icon
