### ISSUE TITLE
Double character when typing accents on macOS

### ISSUE THREAD

**Issue by verekia** [Microsoft/vscode#35733] opened 2017-10-06 15:11 UTC
- VSCode Version: 1.16.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. Long press a button like E
2. Press 2 to select "é" for instance
3. The editor writes `eé` instead of just `é`

This is a problem to type string content in languages using accents and other character alterations.

What happens is pretty clear, the first character is immediately written on "keyDown", when it should probably wait for something like "keyUp".

**Comment by bestvow** [comment] 2017-10-06 15:22
In my Mac is properly
<img width="159" alt="2017-10-06 11 21 46" src="https://user-images.githubusercontent.com/24888709/31285155-3c833998-aa80-11e7-9f27-cc34118975ed.png">

**Comment by verekia** [comment] 2017-10-06 15:27
@bestvow What is your VSCode and OS version? :)

**Comment by alexandrudima** [comment] 2017-10-06 15:46
Duplicate of #34826

**Closed by alexandrudima** 2017-10-06 15:46 UTC
Labels: editor, editor-input
