### ISSUE TITLE
Add TM_FILEPATH_RELATIVE snippet variable

### ISSUE THREAD

**Issue by volosovich** [Microsoft/vscode#34592] opened 2017-09-18 21:18 UTC
- VSCode Version: all
- OS Version: all

I have a lot of snippets for my projects and I often use variables.
`TM_FILEPATH` - it's good, but sometimes project has very long path, something like:
`/home/user/Documents/work/project1/frontEnd/bestUi/src/component/modal/utils/view.js`
My root folder in vsCode is `bestUi` I don't need to print or use all path, just path from root-folder to file:
`/bestUi/src/component/modal/utils/view.js`,
My proposal is to add new variable, called `TM_FILEPATH_RELATIVE`, which return, only path from root-folder to file.
If this proposal is being interesting for community, I can implement it, added test for that, add support for multi root-folders and so on,
Just one question, I cannot understand - Where is vsCode saving information about root folder of project?
Thanks a lot for all discussions.

**Comment by jrieken** [comment] 2017-09-19 06:59
We will add snippet variable transformations in September. That will enable you do insert paths as you wish

**Comment by jrieken** [comment] 2017-09-19 07:00
closing as dupe of https://github.com/Microsoft/vscode/issues/6920

**Closed by jrieken** 2017-09-19 07:00 UTC
Labels: snippets

**Comment by volosovich** [comment] 2017-10-24 23:32
hello @jrieken I read about Variable Transforms, but I cannot understand how I can implement idea about FILEPATH_RELATIVE
Ok, I can get full path to file and use regexp with hardcoded name of root folder. But what if I load new project (or vscode with multi root). I would need to change my snippet and hardcode new root folder name. And do it every day.
Maybe implement FILEPATH_RELATIVE it's not bad idea.
Thank you for your support and patience.
