### ISSUE TITLE
Template literal functions do not collapse and expand

### ISSUE THREAD

**Issue by lyskos97** [Microsoft/vscode#51338] opened 2018-06-07 10:19 UTC
- VSCode Version: 1.24.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Launch React JS project featuring functions with template literals
![image](https://user-images.githubusercontent.com/23356069/41093464-34f38ed2-6a6d-11e8-9d80-55f3533c83a0.png)
![image](https://user-images.githubusercontent.com/23356069/41093918-5c29407c-6a6e-11e8-8f1d-a156caefd263.png)

No expand/collapse buttons, although yesterday before 1.24.0 update I could see and use them.
Collapsing still works with Components, Life cycle methods and regular functions though.

2. Try to collapse or expand

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment] 2018-06-07 16:00
Duplicate of https://github.com/Microsoft/TypeScript/issues/23382

See https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts for an explanation of this change and a workaround

**Closed by mjbvz** 2018-06-07 16:00 UTC
Labels: new release
