### ISSUE TITLE
Very first F5 from dirty launch.json does not start debug session for me

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3669] opened 2016-03-03 10:26 UTC
- generate hello world TS extension
- open it and make launch.json dirty
- F5

=> file is saved but for me debug does not start. When I hit F5 again it works.

**Comment by isidorn** [comment] 2016-03-03 22:58
This is happening because there is a `preLaunchTask`, and for some reason I do not get the `inactive` event from the `taskService` in this case.
Forwarding to Dirk as the issue seems to be in the tasks land. If not, he will have an idea what I am doing wrong here.

**Comment by dbaeumer** [comment] 2016-03-09 14:35
@isidorn have you verified if the task is trigger at all?

**Comment by isidorn** [comment] 2016-03-09 14:38
@dbaeumer I have verified I call the run on the taskService, how can I check if the task is actually triggered?

**Comment by dbaeumer** [comment] 2016-03-09 15:05
@isidorn: you can have a handler on the returned promise. If the task can't be run or fails to start the promise resolves in an error. Could that be the case?

**Comment by isidorn** [comment] 2016-03-09 16:03
@dbaeumer just checked that is not the case, the promise simply does not return. Neither the success, nor the error case trigger

**Comment by isidorn** [comment] 2016-03-10 10:38
@dbaeumer I looked a bit into this and it is not connected to debug. 
1. create a new extension
2. make tasks.json dirty
3. run npm task through tasks framework - the spinner in the status bar always spins and never finishes

**Comment by dbaeumer** [comment] 2016-03-11 10:41
@isidorn thanks. Was able to reproduce. Lets look to fix this for March

**Comment by dbaeumer** [comment] 2016-12-06 10:58
Will ensure that we do better with the new task runner implementation planned for Jan 2017.

**Comment by dbaeumer** [comment] 2017-01-23 20:31
I re-implemented the task execution engine for Jan to use the terminal instead of the output window. But I didn't have time yet to address this.

**Comment by dbaeumer** [comment] 2017-02-17 17:12
This will be fixed when the terminal is the default engine since the terminal doesn't have 'state' as the output runner does.

**Comment by dbaeumer** [comment] 2017-03-23 20:42
I rewrote the output runner for making the task stuff API. This got fixed since the output runner doesn't hold any state anymore and hot reacts to changes of the tasks.json file.

**Closed by dbaeumer** 2017-03-23 20:42 UTC
Labels: bug, tasks
