### ISSUE TITLE
SCM: Support past commit messages navigation

### ISSUE THREAD

**Issue by gotofritz** [microsoft/vscode#26952] opened 2017-05-19 16:59 UTC
- VSCode Version: 1.13.0-insider
- OS Version: any

This is a feature request. 

In the search boxes (both local and multifile) you can use ALT-↑ to navigate through your search history. I suggest the same is implemented for the commit message box in the git sidebar. This should be no cheap `git log` substitute - you should only see the (last X?) commit messages you have entered yourself on that machine, in the order in which you have entered them. Just a local history of what was entered in that box.

This is somewhat similar to https://github.com/Microsoft/vscode/issues/6190, but different - it has no relation to undoing a commit, it should be there in the commit message box even if there is nothing to commit.

Thanks

**Comment by jnachtigall** [comment] 2018-01-03 08:44
Even worse, when you (cursor) are in the scm's "Message" input and press ALT-↑ as you are used to it from search input then the text lines in the *editor* are moved (changed) albeit the text editor is not focussed. To me this makes it an UX bug not just a feature request.

**Comment by grabantot** [comment] 2018-02-11 18:03
I think I can implement it for commit message input using `HistoryNavigator` as in the search widget (`SearchWidget` -> `RepositoryPanel`, `SearchViewlet` -> `SCMViewlet`, `searchActions` -> hardcoded keys in `RepositoryPanel`). But still have no idea how to fix lines movement in editor though.
Not sure how should I go about it though. Just fork and make a pr?

**Comment by grabantot** [comment] 2018-02-11 18:09
This issue is related to #29445 (request for a way to get the last commit message).

**Comment by grabantot** [comment] 2018-02-11 21:12
Created a branch: https://github.com/grabantot/vscode/tree/26952-commit-message-history
Problems with it: 
1. `ALT-↑` gets intercepted by the editor so I used `CTRL-↑`;
2. Don't know how to add a new entry to the history on commit. For now a new entry can be added by pressing `CTRL-↑` as in the search widget;
3. Hotkeys are hardcoded.
Any suggestions are welcome.

**Comment by wildeyes** [comment] 2018-03-07 14:17
Can we also track https://github.com/Microsoft/vscode/issues/45204 here? it was marked as duplicate although it isn't.

**Comment by ssotomayor** [comment] 2018-10-05 15:14
+1 on this

**Comment by ssotomayor** [comment] 2018-10-08 13:28
Any reason why you don't make a PR with that change @grabantot ? I didn't test it but this feature would be quite useful as i usually have to re-type the ticket number when there's JIRA integration :/

**Comment by roonie007** [comment] 2018-11-14 09:22
+1

**Comment by jkatnik** [comment] 2018-11-17 11:11
+1

**Comment by klemensz** [comment] 2018-11-21 19:21
Until this is implemented, the SCM integration of VSCode is not really usable.

**Comment by madprops** [comment] 2019-02-09 20:35
I often make commits that are basically the same than the previous commit but I just append "More" to it. Right now there's no way to quickly fill the commit message with the previous commit, so I have to type it again. Would be nice to have history support like in terminals with up and down arrows. Or maybe have an icon that displays a list of clickable text items of past commits that when clicked fill the commit message input.

**Comment by grabantot** [comment] 2019-02-13 21:29
sorry. I don't see a way I can do this in foreseeable future. The job and my own projects take too much time. Anyone who is willing to work on the issue is welcome to use my pr in any way that helps

**Comment by jbruns2015** [comment] 2019-05-22 20:59
+1

**Comment by alex473x** [comment] 2019-05-29 12:16
+1

**Comment by alex473x** [comment] 2019-05-29 12:43
Found this extension which do the trick: Git Last Commit Message (GLCM)

**Closed** 2020-10-29 19:50 UTC
Labels: feature-request, help wanted, on-testplan, scm

**Comment by zbianca** [comment] 2020-11-19 22:07
This feature is extremely annoying, specially on projects that require long commit messages (co-authors, etc). 
I was searching how to turn it off, when I found the release note and this issue. Good thing is that now I learned I can use cmd + arrows so that I don't go to a previous commit message. But wouldn't it be more intuitive to let the default behavior of the arrow as expected (go up and down on the textarea), and use cmd + arrows to navigate git history?

**Comment by djbrown** [comment] 2020-11-22 10:45
@zbianca for me the message changes to previous/next only when the caret is on the very start/end. else the arrow keys (up/down) work as usual..
Also `ALT` + up/down already lets you turn regardless of where the caret is.

**Comment by zbianca** [comment] 2020-11-22 15:13
@djbrown And when you're in the middle of the first line what does the up-arrow do? On my setup (VSCode on Mac) one press it goes to the beginning of the line and then on the second it goes to the next commit. Now my question to you is: when you navigate a long text, do you count how many times to press the arrows? Or do you hold the keys and have an intuition (internal calculation of speed) of when to stop pressing the key? I can only suposse the use case for longer commit messages was not tested enough (usability).

**Comment by madprops** [comment] 2020-11-22 17:11
Before this I was using the extension mentioned here. 
It provides a button above the input that I click to put the last commit message in the input.

![2020-11-22_11-09](https://user-images.githubusercontent.com/206498/99910365-2ebf7700-2cb3-11eb-8406-4959605f3847.png)

Maybe instead of the arrows something like this can be used.
Like show a list of recent messages to choose from.
Also I prefer that changing the input places the caret at the end instead of at the start.

**Comment by chrisant996** [comment] 2020-12-01 02:23
The implementation that got released is very disruptive -- now when I use the up arrow to go up to edit the first line of a commit, I almost always overshoot and it starts cycling through commit history.

It should not cycle history on a simple Up arrow with no modifier key, at least not when the commit message edit box is dirty.

This should look and feel like a normal edit box, unless the user does exceptional things.  Pressing a simple Up arrow key is not an exceptional gesture, but for example pressing Alt+Up would be exceptional because it's not a key combination normally recognized by edit boxes.
