### ISSUE TITLE
Remote SSH - Search in files fails on ARM hosts

### ISSUE THREAD

**Issue by bashimao** [microsoft/vscode#184400] opened 2023-06-06 09:10 UTC
**Client**
- VS Code Version: 1.78.2
- OS Version: Windows 11
- Architecture: x86_64

**Host**
- OS Version: Ubuntu 20.04
- Architecture: AArch 64

**Steps to Reproduce:**
1. Use Remote SSH extension to connect to host and let VS code bootstrap VS code server.
2. Open project directory.
3. `CTRL + Shift + F`
4. Make sure the `Search only in Open Editors` option is `UNSELECTED`.
5. Enter some `word` that you know exists in some code file.
6. Note that the search doesn't yield anything. -> **That is the ERROR**
7. Open some file that contains the respective `word`.
8. Refresh search.
9. Now the result shows up.

To conclude, with an ARM host, search in files is somehow always restricted to open files, regardless of whether the option is selected or not.

**Comment by andreamah** [comment] 2023-06-06 15:15
If you do the following, what logs do you get when you perform a search on the buggy linux arch?
1. run `Developer: Set Log Level`  in the command palette and set `Trace`
2. do a search
3. In the bottom panel, check logs in the `Extension Host (Remote)` channel in the `Outputs` tab
This might be a duplicate of https://github.com/microsoft/vscode/issues/179907

**Comment by bashimao** [comment] 2023-06-07 09:16
```
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:14:54.601 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:15:10.274 [trace] [eamodio.gitlens] INVOKE provider 'te=>te.provideCodeLenses(o.URI.revive(q),Y)'
2023-06-07 09:15:10.275 [trace] [vscode.merge-conflict] INVOKE provider 'te=>te.provideCodeLenses(o.URI.revive(q),Y)'
2023-06-07 09:15:10.275 [trace] [eamodio.gitlens] provider DONE after 1ms
2023-06-07 09:15:10.275 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:15:10.275 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:15:10.275 [trace] [vscode.merge-conflict] provider DONE after 0ms
2023-06-07 09:15:11.922 [trace] [eamodio.gitlens] INVOKE provider 'te=>te.provideCodeLenses(o.URI.revive(q),Y)'
2023-06-07 09:15:11.922 [trace] [vscode.merge-conflict] INVOKE provider 'te=>te.provideCodeLenses(o.URI.revive(q),Y)'
2023-06-07 09:15:11.922 [trace] [eamodio.gitlens] provider DONE after 0ms
2023-06-07 09:15:11.923 [trace] ExtHostCommands#executeCommand setContext
2023-06-07 09:15:11.923 [trace] ExtHostCommands#executeCommand _setContext
2023-06-07 09:15:11.923 [trace] [vscode.merge-conflict] provider DONE after 1ms
2023-06-07 09:15:20.995 [debug] RipgrepSearchEH#search provideTextSearchResults License, {"folder":"file:///home/mlanger/proj","excludes":["**/.git","**/.svn","**/.hg","**/CVS","**/.DS_Store","**/Thumbs.db","**/.classpath","**/.project","**/.settings","**/.factorypath","**/node_modules","**/bower_components","**/*.code-search"],"includes":["**/proj/**"],"useIgnoreFiles":true,"useGlobalIgnoreFiles":false,"useParentIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxResults":20000,"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
2023-06-07 09:15:20.995 [debug] RipgrepSearchEH#search /home/mlanger/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node_modules/@vscode/ripgrep/bin/rg --hidden --ignore-case -g '**/proj/**' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/.classpath' -g '!**/.project' -g '!**/.settings' -g '!**/.factorypath' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'License' '.'
 - cwd: /home/mlanger/proj
2023-06-07 09:15:20.999 [debug] RipgrepSearchEH#search <jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed

2023-06-07 09:15:21.055 [debug] RipgrepSearchEH#search No data from stdout
2023-06-07 09:15:21.055 [debug] RipgrepSearchEH#search No result from parser
2023-06-07 09:15:21.055 [debug] RipgrepSearchEH#search 
2023-06-07 09:15:21.283 [debug] RipgrepSearchEH#search provideTextSearchResults License, {"folder":"file:///home/mlanger/proj","excludes":["**/.git","**/.svn","**/.hg","**/CVS","**/.DS_Store","**/Thumbs.db","**/.classpath","**/.project","**/.settings","**/.factorypath","**/node_modules","**/bower_components","**/*.code-search"],"includes":["**/proj/**"],"useIgnoreFiles":true,"useGlobalIgnoreFiles":false,"useParentIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxResults":20000,"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
2023-06-07 09:15:21.283 [debug] RipgrepSearchEH#search /home/mlanger/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node_modules/@vscode/ripgrep/bin/rg --hidden --ignore-case -g '**/proj/**' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/.classpath' -g '!**/.project' -g '!**/.settings' -g '!**/.factorypath' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'License' '.'
 - cwd: /home/mlanger/proj
2023-06-07 09:15:21.286 [debug] RipgrepSearchEH#search <jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed

2023-06-07 09:15:21.340 [debug] RipgrepSearchEH#search No data from stdout
2023-06-07 09:15:21.340 [debug] RipgrepSearchEH#search No result from parser
2023-06-07 09:15:21.340 [debug] RipgrepSearchEH#search 
````
Yes, at least the jemalloc error can be seen.

**Comment by bashimao** [comment] 2023-06-07 09:30
![image](https://github.com/microsoft/vscode/assets/7855770/36be0fc6-8014-44b3-8a15-60ba5ceb383b)

The word `License` is in the header of hundreds of files in this repo. So would expect thousands of hits. But, as can be seen, despite not having selected `search only in open editors`, the search is restricted to the currently opened files. Works fine if the remote machine is `x86`.

Page size setup:
```
/proc/1$ grep -i pagesize smaps
KernelPageSize:       64 kB
MMUPageSize:          64 kB
```

**Comment by bashimao** [comment] 2023-06-07 09:48
Also, @andreamah , I switched to the Insiders build: `1.79.0-insider`. Unlike suggested in the other thread, the problem is **NOT** resolved.

```
2023-06-07 09:46:21.230 [debug] RipgrepSearchEH#search provideTextSearchResults license, {"folder":"file:///home/mlanger/proj","excludes":["**/.git","**/.svn","**/.hg","**/CVS","**/.DS_Store","**/Thumbs.db","**/node_modules","**/bower_components","**/*.code-search"],"includes":["**/merlin-kv/**"],"useIgnoreFiles":true,"useGlobalIgnoreFiles":false,"useParentIgnoreFiles":false,"followSymlinks":true,"encoding":"utf8","maxResults":20000,"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}
2023-06-07 09:46:21.230 [debug] RipgrepSearchEH#search /home/mlanger/.vscode-server-insiders/bin/aee52551e25d98391f9064996196cd83a9fc8669/node_modules/@vscode/ripgrep/bin/rg --hidden --ignore-case -g '**/merlin-kv/**' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/Thumbs.db' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --no-ignore-parent --follow --crlf --fixed-strings --no-config --no-ignore-global --json -- 'license' '.'
 - cwd: /home/mlanger/proj
2023-06-07 09:46:21.234 [debug] RipgrepSearchEH#search <jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```

**Comment by andreamah** [comment] 2023-06-07 14:48
Yes, the issue had been reopened. 

/duplicate https://github.com/microsoft/vscode/issues/179907

**Closed** 2023-06-07 14:48 UTC
Labels: info-needed, *duplicate
