### ISSUE TITLE
createFileSystemWatcher dose not fire for simple path

### ISSUE THREAD

**Issue by liximomo** [Microsoft/vscode#57475] opened 2018-08-29 07:27 UTC
- VSCode Version: 1.26.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
```js
vscode.workspace.createFileSystemWatcher(
    new vscode.RelativePattern(vscode.workspace.workspaceFolders[0], 'styles/style.css'),
    false,
    false,
    false
  );
```
This will not fire any event. Change to this will.

```js 
vscode.workspace.createFileSystemWatcher(
    new vscode.RelativePattern(vscode.workspace.workspaceFolders[0], 'styles/style.{css}'),
    false,
    false,
    false
  );
```

FYI, both will fire on Mac OS X.

**Comment by bpasero** [comment] 2018-08-29 13:15
@chrmarti moving to you (this is not a recent regression it seems), this seems to fall through one of our optimizations we have (that is why the second case works where we do not optimize).

This test demonstrates the issue:

```typescript
test('relative pattern - #57475', function () {
	if (isWindows) {
		let p: glob.IRelativePattern = { base: 'C:\\DNXConsoleApp\\foo', pattern: 'styles/style.css', pathToRelative: (from, to) => path.relative(from, to) };
		assertGlobMatch(p, 'C:\\DNXConsoleApp\\foo\\styles\\style.css');
		assertNoGlobMatch(p, 'C:\\DNXConsoleApp\\foo\\Program.cs');
	} else {
		let p: glob.IRelativePattern = { base: '/DNXConsoleApp/foo', pattern: 'styles/style.css', pathToRelative: (from, to) => path.relative(from, to) };
		assertGlobMatch(p, '/DNXConsoleApp/foo/styles/style.css');
		assertNoGlobMatch(p, '/DNXConsoleApp/foo/Program.cs');
	}
});
```

The issue is that in https://github.com/Microsoft/vscode/blob/fc6067f53e269ed234ad10220d2d8b6558c360e2/src/vs/base/common/glob.ts#L412 we seem to compare with the native path and not the one we pass in.

**Comment by chrmarti** [comment] 2018-09-05 14:12
The thought here is that comparing the native paths against the (once) normalized-to-native pattern is faster than normalizing all paths to slashes to then compare against the original pattern. I'll remove the normalization of the paths as fix.

**Closed** 2018-09-05 14:13 UTC
Labels: bug, file-glob
