### ISSUE TITLE
VSCode will freeze when opening this JSON file

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#13766] opened 2016-10-14 14:55 UTC
- VSCode Version: Code - Insiders 1.7.0-insider (bbda59212ba3c603addfaa4854b35801fe04d92e, 2016-10-14T06:11:29.547Z)
- OS Version: Windows_NT ia32 10.0.14946
- Extensions: donjayamanne.python-0.4.2, ms-vscode.latex-0.1.3, redhat.java-0.0.5, seanmcbreen.MDTools-1.0.0, seanmcbreen.Spell-0.8.6, Shan.code-settings-sync-2.3.1

Steps to Reproduce:

1. download this [file](https://gist.githubusercontent.com/neilsustc/4d170cb1a4cd9ce23bdb22f01c4ae816/raw/2076a78c86fcbe477c2f9ccd25ab589ad48582d6/something.json)
2. right click it and open it with vscode
3. vscode will freeze until it says "not responding"

It seems that something with JSON colorizer is to blame.

**Comment by aeschli** [comment] 2016-10-16 19:47
Can't reproduce on Linux (elementary OS 0.3.2 Freya (64-bit))

**Comment by neilsustc** [comment] 2016-10-17 01:45
Can it be reproduced on Windows?

In my Windows 10, if I directly open the file in a new window, I find the code is not colorized, and not editable too.
It's quite similar to this previous issue #6677

What's more, I find that if you open a simple JSON file at first, for example,
```json
{
  "foo": "bar"
}
```
this simple file will be colorized as we expect, then open the relatively large file I provided (in the same window, by dragging or `File > Open File`), it then will work well.

**Comment by aeschli** [comment] 2016-10-17 08:17
I can reproduce on Windows 10 bbda592, but no longer on c613e1bddce6a544fdf7fcfe2fc0a59626d8195d	
Looks like a duplicate of #13667

**Closed by aeschli** 2016-10-17 08:17 UTC
