### ISSUE TITLE
Cannot open source files from within file manager (Thunar)

### ISSUE THREAD

**Issue by majid4466** [microsoft/vscode#212125] opened 2024-05-06 21:00 UTC
Type: <b>Bug</b>

After the most recent update when I double click source files (*.php, *.js, etc.) a new instance of VS code is spawned and nothing is opened, neither in the already open vs code instance nor in the new one.

Files could be opened by dropping them on VS code window and by using the explorer as well as using search results.

My dev box has Xubuntu 20.04 and the file manager I use is Thunar.
Here is the version information from the "About" dialog:

Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.4.0-177-generic

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 5.4.0-177-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8500Y CPU @ 1.50GHz (4 x 2949)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.65GB (3.81GB free)|
|Process Argv|--unity-launch --crash-reporter-id e0cccab9-1704-45d5-9a6d-97943ca924da|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.10.4
prettier-vscode|esb|10.4.0
copilot|Git|1.187.0
copilot-chat|Git|0.15.2024043005
todo-tree|Gru|0.0.226
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.1.0
php-debug|xde|1.34.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by bpasero** [comment] 2024-05-07 04:56
This does not sound like a bug in VS Code but an issue with your setup, but leaving this issue open to see if others hit it as well.

**Comment by majid4466** [comment] 2024-05-07 07:30
If there's something I can do to test which one is the case, I am more than willing to try. 

I could think of one test, which is not conclusive but seems to suggest the issue _is_ related to VS Code: 
I changed the `Open With` association of `.js` files from **Visual Studio Code** to **Sublime Text.** Double clicking `.js` files opened them in Sublime Text without an issue. I then changed the association back to **VS Code** and the issue was back. 
I repeated that with **Mousepad** with the same results (working with Mousepad and failing with VS Code.)

**Comment by bpasero** [comment] 2024-05-07 08:54
So you cannot reproduce when you install `1.88.1`?

```
VS Code Build: e170252f762678dec6ca2cc69aba1570769a5d39

cli-alpine-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_alpine_arm64_cli.tar.gz
cli-alpine-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_alpine_x64_cli.tar.gz
cli-darwin-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_darwin_arm64_cli.zip
cli-darwin-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_darwin_x64_cli.zip
cli-linux-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_linux_arm64_cli.tar.gz
cli-linux-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_linux_armhf_cli.tar.gz
cli-linux-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_linux_x64_cli.tar.gz
cli-win32-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_win32_arm64_cli.zip
cli-win32-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/vscode_cli_win32_x64_cli.zip
darwin: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCode-darwin.zip
darwin-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCode-darwin-arm64.zip
darwin-universal: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCode-darwin-universal.zip
linux-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-stable-arm64-1712770481.tar.gz
linux-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-stable-armhf-1712770492.tar.gz
linux-deb-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code_1.88.1-1712770538_arm64.deb
linux-deb-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code_1.88.1-1712770545_armhf.deb
linux-deb-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code_1.88.1-1712771838_amd64.deb
linux-rpm-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-1.88.1-1712770627.el8.aarch64.rpm
linux-rpm-armhf: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-1.88.1-1712770623.el8.armv7hl.rpm
linux-rpm-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-1.88.1-1712771932.el8.x86_64.rpm
linux-snap-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-stable-x64-1712773445.snap
linux-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code-stable-x64-1712770462.tar.gz
win32-arm64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCodeSetup-arm64-1.88.1.exe
win32-arm64-archive: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCode-win32-arm64-1.88.1.zip
win32-arm64-user: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCodeUserSetup-arm64-1.88.1.exe
win32-x64: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCodeSetup-x64-1.88.1.exe
win32-x64-archive: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCode-win32-x64-1.88.1.zip
win32-x64-user: https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/VSCodeUserSetup-x64-1.88.1.exe
```

**Comment by ferby88** [comment] 2024-05-08 06:47
I'm also experiencing the same issue with the Dolphin file manager after the last update, opening a file with the "Open file" dialog o dragging it to an opened Code window works fine.

Code is installed through the snap package manager.

These are the information displayed in the About dialog:

Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-28-generic snap

**Comment by bpasero** [comment] 2024-05-08 06:49
Please downgrade and see if its not reproducible then: https://github.com/microsoft/vscode/issues/212125#issuecomment-2097789123

**Comment by ferby88** [comment] 2024-05-08 08:06
I can confirm that reverting Code with the "snap revert" command resolved the issue, the current installation details are the following:

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-28-generic snap

**Comment by bpasero** [comment] 2024-05-08 10:33
Interesting, can you add a `--verbose` to the command line invocation or configure VS Code runtime arguments and add:

```
"log-level": "trace"
```

<img width="530" alt="image" src="https://github.com/microsoft/vscode/assets/900690/7a77fa23-0cbc-4cf3-abe7-7a3149a86cac">

And then attach the logs folder with a clean startup via your finder.

**Comment by bpasero** [comment] 2024-05-08 10:34
@majid4466 are you also on Snap?

Does this reproduce when not using Snap but Deb?

**Comment by majid4466** [comment] 2024-05-08 14:53
Yes, I have VS Code installed as a Snap package. 

I am hesitant to experiment with my development machine by uninstalling VS Code and testing the deb version. If I get the chance to install the deb version on another machine I will report the result here.

**Comment by bpasero** [comment] 2024-05-08 14:57
Thanks

**Comment by bpasero** [comment] 2024-05-08 18:26
But it would still be interesting to get at the verbose logs when it works vs when it does not work.

**Comment by ferby88** [comment] 2024-05-09 08:59
I tried to reproduce the issue on another workstation and a virtual machine but the snap package 1.89.0 works fine.
It seems to be an issue with the snap refresh process and not with the version itself.

If I find some time today I will retry to upgrade Code again on the pc that presented the issue and let you know the result.

**Comment by bpasero** [comment] 2024-05-09 09:26
Yeah I am not expecting a regression in VS Code but a setup/install issue.

**Comment by ferby88** [comment] 2024-05-09 09:41
I attached the log generated by opening a file from file manager with both Code versions.
[version-1.88.1-logs.zip](https://github.com/microsoft/vscode/files/15260534/version-1.88.1-logs.zip)
[version-1.89.0-logs.zip](https://github.com/microsoft/vscode/files/15260535/version-1.89.0-logs.zip)

**Comment by bpasero** [comment] 2024-05-09 09:53
Yeah, as expected, in version `1.89` the instance receives the following argument for opening:

```
args: {"_":["/home/fabio/Downloads/New Folder/test.txt"]
```

And in `1.90`:

```
args: {"_":[]
```

**Comment by bpasero** [comment] 2024-05-09 09:55
Moving to Daniel and Deepak as this seems Snap install related, I doubt we changed something how we create the Snap file, but I am not sure either.

**Comment by yukina3230** [comment] 2024-05-12 06:40
I have the same issue on Gnome Nautilus, double click on the file in the file manager launches a new empty instance of VSCode. I'm using Arch and VSCode is installed through AUR.

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.9-arch1-2

**Comment by Sherevv** [comment] 2024-05-15 15:44
> have the same issue on Gnome Nautilus, double click on the file in the file manager launches a new empty instance of VSCode. I'm using Arch and VSCode is installed through AUR.
same for me

**Comment by leukipp** [comment] 2024-05-20 12:13
Same problem with thunar file manager on ubuntu:

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-76-generic

Installed through the deb package from apt repo `http://packages.microsoft.com/repos/code stable main`.

**Comment by leukipp** [comment] 2024-05-20 12:46
> I can confirm that reverting Code with the "snap revert" command resolved the issue, the current installation details are the following:

---

After downgrading to **1.89.0** the issue still exists:
```bash
# downgrading code from 1.89.1-1715060508 to 1.89.0-1714530869
sudo apt install code=1.89.0-1714530869
```

### First buggy version (.deb)

Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:08:25.066Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-76-generic

---

A further downgrade to **1.88.1** fixes the problem:
```bash
# downgrading code from 1.89.0-1714530869 to 1.88.1-1712771838
sudo apt install code=1.88.1-1712771838
```

### Last working version (.deb)

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-76-generic

**Comment by leukipp** [comment] 2024-06-25 07:05
Same problem with the latest version **1.90.2**:

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:33:48.698Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-76-generic

@bpasero: Any news on that?

**Comment by deepak1556** [comment] 2024-07-22 07:41
Based on the affected versions, seems like a regression from https://github.com/microsoft/vscode/commit/0da22a226000adc62cf7b8a83b045668fb8a9296

**Comment by leukipp** [comment] 2024-09-13 07:03
The issue still exists on the latest version:

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-76-generic

@Tyriar  Any news or workarounds for this?

**Comment by rzhao271** [comment] 2024-09-13 21:32
I removed the `--unity-launch` flag back in April but did not realize it had to be substituted with another flag such as `--new-window`.
I'll put up a PR soon.

Additional verification steps once a new Insiders is out: https://github.com/microsoft/vscode/issues/21133#issuecomment-282107689

**Comment by majid4466** [comment] 2024-09-14 00:43
Based on the latest posts here and pointing to a regression from [0da22a2](https://github.com/microsoft/vscode/commit/0da22a226000adc62cf7b8a83b045668fb8a9296) I found a workaround. I am on an Xubuntu machine with XFCE and Whiskers menu. Here is what I did:

1. I found the VS code's icon in Whiskers menu, right clicked it and from the selected "Edit Application ..."
2. In the "Edit Launcher" window I had this in the "Command" field: `/usr/share/code/code --unity-launch %F`
3. I removed the `--unity-launch` flag and saved.

That was it! The issue gone.

**Comment by rzhao271** [comment] 2024-09-14 01:29
Thanks @majid4466,
In that case, it sounds like the current post-install script does not successfully update the .desktop file.
As for the "Command" field, does changing it to `/usr/share/code/code --new-window %F` work as well as or better than `/usr/share/code/code %F`?

**Comment by majid4466** [comment] 2024-09-14 01:43
Changing the command to `/usr/share/code/code --new-window %F` results in having each opened file open in a new window not as a tab in the already opened VS Code instance. So, in my case at least I am better off without it.

**Comment by rzhao271** [comment] 2024-09-16 22:56
I manually downloaded and installed VS Code 1.87 with `sudo dpkg -i <package-name>.deb` on Ubuntu (not Xubuntu), then used `sudo apt-get update && sudo apt-get upgrade code` to upgrade it to 1.93. I confirmed that the `code.desktop` file did not have the `--unity-launch` flag after.

@majid4466 my current assumption is that your update process left the `--unity-launch` flag in the `code.desktop` file or another file involved in launching `code`. I'm wondering what steps you use to update the `code` package?

@leukipp do you also see a `--unity-launch` flag in your `code.desktop` file? If yes, does removing that flag help? The `code.desktop` file in my case is under `/usr/share/applications`.

**Comment by leukipp** [comment] 2024-09-17 01:25
@rzhao271 
I updated code the last time to version 1.93.1 on 2024-09-13 via apt. The current .desktop file(s) looks like this:
```bash
ls -lah /usr/share/applications/code*

-rwxrwxr-x 1 root root 708 Sep 11 20:06 /usr/share/applications/code.desktop
-rw-rw-r-- 1 root root 312 Sep 11 20:06 /usr/share/applications/code-url-handler.desktop
```

```bash
cat /usr/share/applications/code*

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code %F
Icon=vscode
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=TextEditor;Development;IDE;
MimeType=application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Name[de]=Neues leeres Fenster
Name[es]=Nueva ventana vacía
Name[fr]=Nouvelle fenêtre vide
Name[it]=Nuova finestra vuota
Name[ja]=新しい空のウィンドウ
Name[ko]=새 빈 창
Name[ru]=Новое пустое окно
Name[zh_CN]=新建空窗口
Name[zh_TW]=開新空視窗
Exec=/usr/share/code/code --new-window %F
Icon=vscode
[Desktop Entry]
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --open-url %U
Icon=vscode
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
``` 

No `--unity-launch` flag and the executable points to `/usr/share/code/code` which is a binary file.

---

When running code from the terminal, `which` gives:
```bash
which code

/usr/bin/code
```

```bash
ls -lah /usr/bin/code*

lrwxrwxrwx 1 root root  24 Sep 13 09:00 /usr/bin/code -> /usr/share/code/bin/code
```

This is a symlink and the executable points to `/usr/share/code/bin/code` which is a shell script.

---

Running `/usr/share/code/code SOMEFILE.txt` or `/usr/share/code/bin/code SOMEFILE.txt` from the terminal opens the file in a new tab as expected.

Double clicking the file opens an empty code window and the process output shows:
```bash
ps -fC code

UID          PID    PPID  C STIME TTY          TIME CMD
user      107051       1  1 02:55 ?        00:00:01 /usr/share/code/code --unity-launch /home/user/SOMEFILE.txt
```

The `--unity-launch` flag is present there. So somewhere it must still be added, which is likely the root cause of the problem.

**Comment by rzhao271** [comment] 2024-09-17 23:31
Is the `~/.local/share/applications` folder managed by Xubuntu or by hand? I'm unable to find a code pointer where the VS Code Debian package post-install script writes to that directory.

I can document on the VS Code website the issue of `code.desktop` files outside of `$XDG_DATA_DIRS/applications` not being updated automatically, but I'd like the issue to be filed upstream if it is specific to a distribution's package update process.

**Closed** 2024-09-28 11:26 UTC
Labels: info-needed, install-update, linux, workbench-os-integration, regression
