### ISSUE TITLE
can't type in the terminal

### ISSUE THREAD

**Issue by SaraSadounAyoub** [microsoft/vscode#214726] opened 2024-06-09 11:54 UTC
Type: <b>Performance Issue</b>

hte terminal not showing the path of the current folder and i cannot type in the terminal wether it is cmd or the other types

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 6.0.6000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   172	  1928	code main
    0	   106	  4544	ptyHost
    0	    18	  7212	     winpty-agent
    0	     9	  9412	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    66	 27844	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    18	 21032	     winpty-agent
    0	     9	 11412	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     6	 19120	       C:\WINDOWS\System32\cmd.exe
    0	    18	 21936	     winpty-agent
    0	     9	 11912	       C:\WINDOWS\system32\conhost.exe 0x4
    0	     6	 24020	       C:\WINDOWS\System32\cmd.exe
    0	    18	 23752	     winpty-agent
    0	    66	 21044	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     9	 29116	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   195	  7328	window [1] (Welcome - byan - Visual Studio Code)
    0	   178	 14620	   gpu-process
    0	   103	 17324	shared-process
    0	   121	 19276	extensionHost [1]
    0	   118	 21176	window [2] (Issue Reporter)
    0	   102	 22640	   window
    0	    95	 23460	fileWatcher [1]
    0	    57	 28152	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - byan - Visual Studio Code)
|    Folder (byan): 4 files
|      File types: png(2) html(1)
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
fa862199:31048878

```

</details>

**Comment by SaraSadounAyoub** [comment] 2024-06-09 11:58
![Screenshot 2024-06-09 145717](https://github.com/microsoft/vscode/assets/160773617/3e46aa9b-00ef-4572-9c44-e5a2cb7493fb)

**Comment by sonk33** [comment] 2024-06-09 15:55
To ensure that the problem is not caused by one of the settings or one of the extensions.
close all vscode instances.
then run vscode with this command `code --disable-extensions --user-data-dir <directory>`  where <directory> is an empty folder.

**Comment by SaraSadounAyoub** [comment] 2024-06-09 16:16
thanks for the help @sonk33 but i sill can't type in the vscode terminal

**Comment by meganrogge** [comment] 2024-06-10 16:24
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by SaraSadounAyoub** [comment] 2024-06-12 15:23
the settings.json file 
![Screenshot 2024-06-12 182155](https://github.com/microsoft/vscode/assets/160773617/732cdb2d-528d-43fa-a4b6-7c37d9f5dfee)

**Comment by meganrogge** [comment] 2024-06-12 20:08
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by meganrogge** [comment] 2024-06-12 20:09
looks like it's probably a permissions issue - can you also go to `Help -> toggle developer tools -> console` and screenshot any errors that are present there?

**Comment by SaraSadounAyoub** [comment] 2024-06-13 09:47
toggle developer tools 
![Screenshot 2024-06-13 124649](https://github.com/microsoft/vscode/assets/160773617/4e132285-038b-4005-881f-7eb8da1b08c3)

**Comment by SaraSadounAyoub** [comment] 2024-06-13 09:53
trace log

[terminal.log](https://github.com/user-attachments/files/15817375/terminal.log)

**Comment by SaraSadounAyoub** [comment] 2024-06-13 09:56
settings.json

[settings.json](https://github.com/user-attachments/files/15817426/settings.json)

**Comment by meganrogge** [comment] 2024-06-13 14:44
you need to click the `Console` tab in dev tools, also the trace log didn't work

**Comment by SaraSadounAyoub** [comment] 2024-06-14 14:28
![Screenshot 2024-06-14 172704](https://github.com/microsoft/vscode/assets/160773617/a22a22fe-c33b-4918-99b3-62701604d818)

**Comment by meganrogge** [comment] 2024-06-14 15:17
i'd try uninstalling and reinstalling vscode

**Comment by SaraSadounAyoub** [comment] 2024-06-15 16:50
thanks for the help, but i've already tried uninstalling and reinstalling but the problem remains

**Comment by meganrogge** [comment] 2024-08-28 20:53
I cannot repro, thus closing this since it's impossible to investigate further

**Closed by meganrogge** 2024-08-28 20:53 UTC
Labels: info-needed, terminal
