### ISSUE TITLE
New typescript files are not added to project

### ISSUE THREAD

**Issue by realh** [microsoft/vscode#88787] opened 2020-01-16 16:25 UTC
Issue Type: <b>Bug</b>

When I add a .ts file, Code doesn't consider it to be part of a Typescript project until I make some sort of trivial change to tsconfig.json and save it.

My tsconfig.json contains this:

    "include": [
        "./client/*.ts",
        "./client/ui/*.ts",
        "./client/wui/*.ts"
    ]

and most of the files I'm adding at the moment are either in ui or wui, but I don't know whether it's the folder structure that's causing the problem. It's supposed to search for tsconfig.json recursively up from a source file isn't it?

I'm having this problem with Insiders and the current stable version, and it doesn't seem to make a difference whether the project is a workspace or not.

This seems to be the same as issue #50329. I'm reluctant to use the workaround suggested there (use Workspace TS server) because I'm using a Mac to edit a project on a headless Linux server, using a sshfs mount, so using a Workspace TS server might slow it down further or cause compatibility issues because of involving two different OSs.

VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T08:53:57.100Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.69GB free)|
|Process Argv|-psn_0_4699259|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
python|ms-|2020.1.58038
cpptools|ms-|0.26.3-insiders3
lit-plugin|run|1.1.9
cmake|twx|0.0.17
vim|vsc|1.12.4

</details>

**Comment by mjbvz** [comment] 2020-01-16 19:42
Thanks for the issue report. 

This seems like a duplicate of https://github.com/microsoft/TypeScript/issues/35794

Closing as upstream

**Closed by mjbvz** 2020-01-16 19:42 UTC
Labels: typescript
