### ISSUE TITLE
Closing vscode does not kill child processes, preventing upgrades

### ISSUE THREAD

**Issue by DanielHeath** [microsoft/vscode#175811] opened 2023-03-01 22:34 UTC
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.76.0
- OS Version: Linux 5.15.0-60-generic # 66-Ubuntu SMP x86_64 GNU/Linux

Steps to Reproduce:

1. Use vscode for awhile with any of the many extensions which start a background job (eg the `go` or `sorbet` extensions)
2. Close vscode
3. Attempt to update vscode via `sudo snap refresh`

Expected behavior: Updates are installed
Actual behavior: `snap` refuses to update a package which still has a running binary.

Technically this is an extension issue, but it happens _every time_ I try to update vscode - I have to hunt down the errant processes and kill them manually.

Is there any interest in a vscode feature that stops child processes before exiting (or reports which extensions are preventing it from fully closing)?

**Comment by joaomoreno** [comment] 2023-03-02 14:55
> Technically this is an extension issue

Absolutely correct. 

> Is there any interest in a vscode feature that stops child processes before exiting

This might not be ideal since you might run in data loss. The extensions themselves have the knowledge on how and when to kill their child processes. I'm afraid the best course of action is to give issues to each extension.

**Comment by AndrewGuenther** [comment] 2023-03-23 20:12
This problem isn't exclusive to extensions, the integrated terminal also frequently leaves dangling processes open which prevent snap refreshes as well.

**Comment by tamuratak** [comment] 2023-03-23 22:46
Might be duplicate of #174956

**Comment by piano1029** [comment] 2023-03-30 21:18
This is a major issue on MacOS when running the integrated terminal on an external disk. To be able to eject the disk I use this workaround:

1. Get the process PID(s) by running `lsof | grep DiskName`
2. Force quit the processes using Activity Monitor
3. Re-attempt ejecting the disk

**Comment by bpasero** [comment] 2023-03-31 06:36
To see if https://github.com/microsoft/vscode/issues/174956 is the reason, you could try to use VS Code insiders and verify the issue is addressed:

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Closed** 2023-05-05 11:24 UTC
Labels: info-needed
