### ISSUE TITLE
Bug: Css reported unkown rule when using @supports

### ISSUE THREAD

**Issue by JosepSalvia** [Microsoft/vscode#32374] opened 2017-08-12 13:24 UTC
- VSCode Version: 1.15 32bits version
- OS Version: Windows 10 64 bits last version

Steps to Reproduce:

1. Open css (blank)
2. Paste the following code (that I'm using in my project);
`
@supports (grid-area: auto) {
    @media screen and (min-width: 768px) {
        .me {
            display: grid;
            justify-content: center;
            align-content: space-between;
            grid-template-columns: 60% 40%;
            grid-template-areas: "left right";
            align-items: center;
        }
        .me-text {
            grid-area: left;
        }
        .me-image {
            grid-area: right;
        }
        .gridport {
            display: grid;
            grid-template-rows: 1fr 1fr;
            grid-template-columns: 1fr 1fr;
            grid-template-areas: "upleft upright" "downleft downright";
            justify-content: space-between;
            align-content: space-between;
            grid-column-gap: 20px;
            grid-row-gap: 20px;
        }
        .upleft {
            grid-area: upleft;
        }
        .upright {
            grid-area: upright;
        }
        .downleft {
            grid-area: downleft;
        }
        .downright {
            grid-area: downright;
        }
        .around {
            display: grid;
            grid-template-columns: 1fr 1fr;
            justify-content: space-between;
            align-content: space-between;
            grid-template-areas: "up down";
        }
        .about {
            grid-area: up;
        }
        .web {
            grid-area: down;
        }
        @media screen and (min-width: 2200px) {
            .content {
                margin: 90px 20% 0px 20%;
                max-width: 80%;
                width: auto;
            }
            @media screen and (min-width: 3840px) {
                .content {
                    margin: 90px auto 0px auto;
                    max-width: 2648px;
                }
                .gridport {
                    grid-template-rows: auto;
                    grid-template-columns: 1fr 1fr 1fr 1fr;
                    grid-template-areas: "upleft upright downleft downright";
                }
            }
        }
    }
}`

3: We can see two bugs:
1- Unexpected unkown rule and expected {} in random parts of the code. Code is perfectly fine and working as expected. See: http://i.imgur.com/TcID5QV.png

2- Grid-area not being colored properly. See; http://i.imgur.com/GNpVAU3.png

Reproduces without extensions: Yes

**Comment by praveenpuglia** [comment] 2017-08-13 06:16
Ref - https://github.com/Microsoft/vscode-css-languageservice/issues/39

I am taking a look at this today.

**Comment by JosepSalvia** [comment] 2017-08-13 09:40
Make sure to check out the second part of the report that - i believe - has nothing to do with @supports, it has to do with css grid.

**Comment by aeschli** [comment] 2017-08-14 08:26
duplicate of #1505

**Closed by aeschli** 2017-08-14 08:26 UTC
Labels: new release

**Comment by JosepSalvia** [comment] 2017-08-14 18:16
The second part of the report was ignored, I should've opened two tickets for every bug. So I did now, the Css grid display error can be found in #32499
