### ISSUE TITLE
"window.titleBarStyle": "custom" on windows triggers the menu shortcuts even if another shortcut exists

### ISSUE THREAD

**Issue by fxlemire** [Microsoft/vscode#53743] opened 2018-07-06 18:35 UTC
Issue Type: <b>Bug</b>

With `"window.titleBarStyle": "custom"`, the following shortcut doesn't work. Instead, it opens the `Help` menu.

```
{
    "key": "alt+h",
    "command": "cursorLeft",
    "when": "editorTextFocus"
}
```

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by MarkusAmshove** [comment] 2018-07-07 09:11
#53718 is the same issue

**Comment by sbatten** [comment] 2018-07-10 21:42
duplicate of #53654

**Closed by sbatten** 2018-07-10 21:42 UTC
Labels: workbench-title
