### ISSUE TITLE
The terminal's lines get duplicated on extending it.

### ISSUE THREAD

**Issue by misaghi** [microsoft/vscode#232353] opened 2024-10-27 04:46 UTC
Type: <b>Bug</b>

1. Extend the terminal to the top.
2. Scroll down.
3. There will be duplicated lines.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.16GB free)|
|Process Argv|--crash-reporter-id ba4db443-4f34-4f3e-b279-85535db3ac6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-django|bat|1.15.0
auto-close-tag|for|0.5.15
vscode-test-explorer|hbe|2.22.1
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
autopep8|ms-|2024.0.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
cpptools|ms-|1.22.10
test-adapter-converter|ms-|0.2.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.12.0
vscode-yaml|red|1.15.0
r|REd|2.8.4
LiveServer|rit|5.7.9
comment-divider|sta|0.4.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by meganrogge** [comment] 2024-10-28 15:42
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed** 2024-12-10 13:26 UTC
Labels: upstream, windows, terminal-conpty
