### ISSUE TITLE
SplitLineCollection attempt to access a newer model

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37812] opened 2017-11-08 10:19 UTC
Sorry @alexandrudima I have no steps, just the stack trace and I can not reproduce
Feel free to close, opening more as a FYI

```
SplitLinesCollection: attempt to access a 'newer' model: Error: SplitLinesCollection: attempt to access a 'newer' model
    at SplitLinesCollection._ensureValidState (file:///Users/isidor/Development/vscode/out/vs/editor/common/viewModel/splitLinesCollection.js:82:23)
    at SplitLinesCollection.getViewLineMinColumn (file:///Users/isidor/Development/vscode/out/vs/editor/common/viewModel/splitLinesCollection.js:403:18)
    at ViewModel.getLineMinColumn (file:///Users/isidor/Development/vscode/out/vs/editor/common/viewModel/viewModelImpl.js:286:31)
    at new ViewportData (file:///Users/isidor/Development/vscode/out/vs/editor/common/viewLayout/viewLinesViewportData.js:20:92)
    at View._actualRender (file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:275:32)
    at file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:252:56
    at safeInvokeNoArg (file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:418:20)
    at View._renderNow (file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:252:13)
    at View._flushAccumulatedAndRenderNow (file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:127:18)
    at View.render (file:///Users/isidor/Development/vscode/out/vs/editor/browser/view/viewImpl.js:367:22)
```

**Comment by alexandrudima** [comment] 2018-04-18 21:59
Duplicate of #44805

**Closed by alexandrudima** 2018-04-18 21:59 UTC
Labels: bug
