### ISSUE TITLE
Problem using strange words with accent like 'atualização'

### ISSUE THREAD

**Issue by leonelcmd** [microsoft/vscode#163658] opened 2022-10-14 14:37 UTC
The main point is when I want to create a link from a tittle in a summary to a topic on the same page. I'm using Vuepress and Markdown language.
When I create a summary topic, for example [Novas atualizações] (novas-atualizacoes)  to link this item with the topic I need to remove all accents on the word, but when I save (ctrl + s) then the link turns into [Novas atualizações] (novas-atualizações). I tried a sort of configurations of the intelliSense and others of the editor but nothing was succesfull

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 11.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.26GB free)|
|Process Argv|--crash-reporter-id f234e821-b0e5-482b-bcc3-6185717e9df4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-enhanced|shd|0.6.3
vscode-cy-helper|She|1.2.2
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by mjbvz** [comment] 2022-10-14 15:58
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by leonelcmd** [comment] 2022-10-14 16:14
@mjbvz So I desabled the following setting "TOC: Update on Save" of the Markdown extension settings and the problem apparently was solved. Thanks for your support 🥇  
![image](https://user-images.githubusercontent.com/63571686/195892696-2dc20db1-09fe-4fe0-82fa-c08ff58a4cba.png)

**Comment by mjbvz** [comment] 2022-10-14 17:08
Glad you found the cause. Closing as cause by extension. Please file an issue against that extension to get this fixed

**Closed by mjbvz** 2022-10-14 17:08 UTC
Labels: info-needed, new release
