### ISSUE TITLE
Scss `follow link` doesn't work in some cases.

### ISSUE THREAD

**Issue by Aliaksei-Martsinkevich** [Microsoft/vscode#65078] opened 2018-12-14 12:06 UTC
Issue Type: <b>Bug</b>

With the following file structure:

```
scss
  - main.scss
  - crash.scss
  - valid-example.scss
```

and with content of `main.scss`:

```scss
@import './crash.scss';
@import './valid-example.scss';
```
Now, when I try to click the `crash.scss` link and move to imported file I get an error:
Unable to open '_crash.scss': File not found (file:///.../sass/_crash.scss).
But if I click `valid-examle.scss` everything works perfect.

But if I change my file structure to following:

```
scss
  - main.scss
  - _valid.scss
  - _crash-example.scss
```

and `main.scss`

```scss
@import 'valid';
@import './valid.scss';
@import './valid';

@import 'crash-example';
@import './crash-example.scss';
@import './crash-example';
```

Now all `_valid.scss` imports are succesfully resolved unlike `_crash-example.scss`.
Last one fails with the following error:
Unable to open '_crash-example': File not found (file:///.../sass/_crash-example).

Also, imports with leading '_' (`e.g. @import '_valid.scss';`) symbol cannot be resolved in any case with the following error:
Unable to open '__valid.scss': File not found (file:///.../sass/__valid.scss

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by octref** [comment] 2018-12-14 21:56
Sorry about that. Duplicate of #58204. Please track it there.

**Closed by octref** 2018-12-14 21:56 UTC
