### ISSUE TITLE
Provides hint in the task to disable/enable "Save all files before execute task"

### ISSUE THREAD

**Issue by cheahkhing** [microsoft/vscode#33904] opened 2017-09-06 16:39 UTC
#17016 as what @dbaeumer mentioned, hopefully this can be a feature request.

I would like to see this feature implemented soon.
Thanks.

**Comment by dbaeumer** [comment] 2017-09-07 07:54
As always things get speed up by a pull request.

**Comment by alexr00** [comment] 2019-10-16 10:48
duplicate of https://github.com/microsoft/vscode/issues/21342

**Closed** 2019-10-16 10:49 UTC
Labels: *duplicate, feature-request, tasks
