### ISSUE TITLE
Cursor pointing to unexpected column

### ISSUE THREAD

**Issue by manutero** [Microsoft/vscode#19843] opened 2017-02-03 14:13 UTC
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|theme-realgithub|NoHomey|1.0.9|
|vscode-docker|PeterJausovec|0.0.11|
|project-manager|alefragnani|0.13.2|
|vscode-color|anseki|0.2.3|
|npm-intellisense|christian-kohler|1.2.1|
|vscode-svgviewer|cssho|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|LogFileHighlighter|emilast|1.0.1|
|Theme-8-Colour-Dark|gerane|0.0.2|
|vscode-sort|henriiik|0.2.5|
|rest-client|humao|0.12.1|
|path-autocomplete|ionutvmi|1.4.1|
|md-navigate|jrieken|0.0.1|
|indentation-level-movement|kaiwood|1.1.1|
|Go|lukehoban|0.6.53|
|5-colors-dark|manutero|0.2.1|
|vscode-todo-parser|minhthai|1.8.6|
|Theme-1337|ms-vscode|0.1.2|
|Theme-3024Kit|ms-vscode|0.1.1|
|theme-quietlight-vsc|onecrayon|1.0.1|
|tsimporter|pmneo|1.2.13|
|better-merge|pprice|0.5.1|
|vscode-nginx|shanoor|0.3.0|
|vscode-apielements|vncz|0.6.0|
|gitblame|waderyan|1.3.0|

---

relevant personal config: 
1. `"editor.cursorStyle": "block"`
2. `"editor.cursorBlinking": "blink"`

---

Steps to Reproduce:

1. type a line 
2. press enter 
3. Cursor will be pointing at a unexpected column (see img)

Since: `1.9`
![vsc-bug](https://cloud.githubusercontent.com/assets/2211052/22594428/555ed774-ea23-11e6-9982-728ff6f8a85c.gif)

**Comment by bpasero** [comment] 2017-02-03 17:40
I think this got fixed for a 1.9.1 release.

**Comment by alexandrudima** [comment] 2017-02-03 18:15
Duplicate of #19808

**Closed by alexandrudima** 2017-02-03 18:15 UTC
