### ISSUE TITLE
VScode does not ask for credentials when pulling from https git repo

### ISSUE THREAD

**Issue by Fulvia1989** [microsoft/vscode#137298] opened 2021-11-16 11:41 UTC
Issue Type: <b>Bug</b>

VS code suddenly stopped showing the usual authentication pop-up when pulling/pushing from a git repository, cloned via https.
Any action ends inevitably with an "authentication failed" error.
I've tried to uninstall VS code, but nothing changed. I've already cleared every credentials in the .gitconfig file , and unset the credential.helper . I've also never chanded the defaut config in VS code.

VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:51:30.084Z)
OS version: Linux x64 5.11.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.30GB (4.54GB free)|
|Process Argv|--unity-launch /home/fulvia/Scrivania/miur-concorsi/cpd2021-istituti-web --crash-reporter-id 93a93ebb-544e-40b4-abbe-4daa8b91db64|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular2|joh|12.0.0
vscode-docker|ms-|1.18.0
vscode-language-pack-it|MS-|1.62.3
remote-containers|ms-|0.205.2
vetur|oct|0.35.0
material-icon-theme|PKi|4.10.0
java|red|1.0.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.18.6
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.1

</details>

**Comment by PINHOf** [comment] 2021-11-16 12:28
Same happens to me. Plus, I'm unable to push any commit into github, I always receive the error `fatal: Authentication failed for 'https://github.com/...';`.

**Comment by gjsjohnmurray** [comment] 2021-11-16 12:44
/duplicate of #137183 which is scheduled to be fixed in upcoming recovery release (1.62.3)

**Closed** 2021-11-16 12:44 UTC
Labels: *duplicate, new release
