### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by elrumordelaluz** [microsoft/vscode#138334] opened 2021-12-02 10:50 UTC
Issue Type: <b>Bug</b>

Don't know a specific way to reproduce, since happens in different projects. 

After the message shared in the title of this issue:

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

when clicking in "Report issue" shows another popup

> Please update your TypeScript version. The workspace is using an old version or TypeScript (undefined). Before reporting an issue, please update the workspace to use the latest stable TypeScript release to make sure the bug has not already been fixed.

but don't know if and where to update TS ws version.

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.2.0
prettier-vscode|esb|9.0.0
nunjucks-template|ese|0.4.2
vscode-peacock|joh|4.0.0
vscode-mdx|Jou|0.2.3
vscode-styled-components|jpo|1.6.6
twig-language-2|mbl|0.9.2
vscode-mjml|mjm|1.0.5
vscode-docker|ms-|1.18.0
python|ms-|2021.11.1422169775
vscode-pylance|ms-|2021.11.2
jupyter|ms-|2021.10.1101450599
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
language-liquid|nei|0.1.1
vscode-nunjucks-formatter|oki|0.1.3
html-to-jsx|ria|0.0.1
postcss|ric|2.0.0
nunjucks|ron|0.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2021-12-06 17:44
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by LeonardoGentile** [comment] 2021-12-09 00:23
@mjbvz yes it does.
I had this problem on the stable version and I've just verified the same with the latest insider with all extension disabled.
This is a copy of the report suggested by vscode.

----

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57005:22)
    at getPropertyOfType (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:57665:24)
    at resolveESModuleSymbol (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49811:54)
    at getTargetOfNamespaceImport (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48996:28)
    at getTargetOfAliasDeclaration (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49230:28)
    at resolveAlias (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at getSymbol (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47833:38)
    at resolveNameHelper (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48125:34)
    at resolveName (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:48108:20)
    at resolveEntityName (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49447:42)
    at getTargetOfExportSpecifier (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49187:17)
    at getTargetOfAliasDeclaration (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49237:28)
    at resolveAlias (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49275:30)
    at resolveSymbol (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:49265:67)
    at mergeSymbol (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47619:42)
    at /Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at mergeSymbol (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47643:21)
    at /Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47734:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47732:20)
    at initializeTypeChecker (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:84991:21)
    at Object.createTypeChecker (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:47390:9)
    at Object.getTypeChecker (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114385:79)
    at synchronizeHostData (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159863:21)
    at Object.getProgram (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159984:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164998:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164927:42)
    at ConfiguredProject.updateGraph (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165920:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167644:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:168727:44)
    at /Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169067:97
    at Object.flatMap (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:169067:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:170225:46)
    at /Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172158:88
    at IOSession.Session.executeWithRequestId (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172149:28)
    at IOSession.Session.executeCommand (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172158:33)
    at IOSession.Session.onMessage (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172184:35)
    at Interface.<anonymous> (/Applications/Coding/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174789:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by zsytssk** [comment] 2021-12-09 03:59
I had the same issue in mac vs code 1.63.0 stable

版本: 1.63.0
提交: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
日期: 2021-12-07T05:15:48.091Z 
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by Gu-Miao** [comment] 2021-12-09 04:16
I have the same too.

Version: 1.63.0 (system setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

TSServer log:
```log
Err 108   [12:05:06.671] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"e:/Projects/changjiu/src/shims-assets.d.ts","fileContent":"declare module '*.avif' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.bmp' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.gif' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.jpg' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.jpeg' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.png' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.webp' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.svg' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n\r\ndeclare module '*.mp4' {\r\n  const src: string;\r\n  export default src;\r\n}\r\n","projectRootPath":"e:\\Projects\\changjiu","scriptKindName":"TS"}]}}:

    Cannot read property 'flags' of undefined

    TypeError: Cannot read property 'flags' of undefined
        at getPropertyOfObjectType (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57005:22)
        at getPropertyOfType (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:57665:24)
        at resolveESModuleSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49811:54)
        at getTargetOfNamespaceImport (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48996:28)
        at getTargetOfAliasDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49230:28)
        at resolveAlias (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
        at getSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47833:38)
        at resolveNameHelper (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48125:34)
        at resolveName (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48108:20)
        at resolveEntityName (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49447:42)
        at getTargetOfAliasLikeExpression (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49204:29)
        at getTargetOfExportAssignment (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49193:28)
        at getTargetOfAliasDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49240:28)
        at resolveAlias (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
        at resolveSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49265:67)
        at resolveExternalModuleSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49757:36)
        at getTargetOfNamespaceExportDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49180:28)
        at getTargetOfAliasDeclaration (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49242:28)
        at resolveAlias (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49275:30)
        at tryResolveAlias (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:49291:24)
        at getCandidateName (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72927:33)
        at Object.getSpellingSuggestion (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1873:33)
        at getSpellingSuggestionForName (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72917:23)
        at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72858:24
        at resolveNameHelper (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48416:30)
        at getSuggestedSymbolForNonexistentSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72840:26)
        at resolveNameHelper (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48438:42)
        at resolveName (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:48108:20)
        at getGlobalSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58878:20)
        at getGlobalTypeSymbol (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58860:20)
        at getGlobalType (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:58881:26)
        at initializeTypeChecker (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85034:52)
        at Object.createTypeChecker (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:47390:9)
        at Object.getTypeChecker (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:114385:79)
        at synchronizeHostData (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159863:21)
        at Object.getProgram (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159984:13)
        at AutoImportProviderProject.Project.updateGraphWorker (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164998:53)
        at AutoImportProviderProject.Project.updateGraph (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164927:42)
        at AutoImportProviderProject.updateGraph (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165772:70)
        at Object.updateProjectIfDirty (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166409:45)
        at ConfiguredProject.Project.getPackageJsonAutoImportProvider (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165547:32)
        at ConfiguredProject.Project.updateGraph (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164965:26)
        at ConfiguredProject.updateGraph (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165920:63)
        at ProjectService.createLoadAndUpdateConfiguredProject (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167644:25)
        at ProjectService.assignProjectToOpenedScriptInfo (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168727:44)
        at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169067:97
        at Object.flatMap (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
        at ProjectService.applyChangesInOpenFiles (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169067:41)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170225:46)
        at d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172158:88
        at IOSession.Session.executeWithRequestId (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172149:28)
        at IOSession.Session.executeCommand (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172158:33)
        at IOSession.Session.onMessage (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:35)
        at Interface.<anonymous> (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174789:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by yanstars** [comment] 2021-12-09 04:45
There was a problem in **vscode-insider** a few days ago, and the update of **vscode-stable** today also has a problem.

I found that it seems to be related to part of the **echarts** library. There is repo here . thanks !

[repo](https://github.com/yanstars/vscode-bug-report)

**Comment by yanstars** [comment] 2021-12-09 04:56
It seems to be related to some **echarts** libraries

both of latest VS Code insiders build with all extensions disabled and VS code Stable 

there is a [repo](https://github.com/yanstars/vscode-bug-report) for this bug , thanks for   help

**Comment by QQCif** [comment] 2021-12-09 05:31
> It seems to be related to some **echarts** libraries
> 
> both of latest VS Code insiders build with all extensions disabled and VS code Stable
> 
> there is a [repo](https://github.com/yanstars/vscode-bug-report) for this bug , thanks for help

I can confirm this. After adding echarts to a fresh CRA project, vscode 1.63.0 stops working.  vscode 1.62.3 works properly.

**Comment by StefanoMagrassi** [comment] 2021-12-09 10:28
I tried to open an issue on the ECharts repository but it seems they don't like it...

> This issue is not created using issue template so I'm going to close it. speak_no_evil
> Sorry for this, but it helps save our maintainers' time so that more developers get helped.
> Feel free to create another issue using the issue template.
>
> If you think you have already made your point clear without the template, or your problem cannot be covered by it, you may re-open this issue again.

**Comment by elrumordelaluz** [comment] 2021-12-09 11:22
@StefanoMagrassi could you please try reopening?

**Comment by StefanoMagrassi** [comment] 2021-12-09 11:25
> @StefanoMagrassi could you please try reopening?

I already tried twice without success (as you can see by issue mentions)...

**Comment by StefanoMagrassi** [comment] 2021-12-09 11:36
@elrumordelaluz the second issue (apache/echarts#16198) was re-opened (it seems they have some trouble with their bot)

**Comment by Ovilia** [comment] 2021-12-10 09:20
Hi. I'm from Apache ECharts team. I have no experience developing VSCode. Can anyone from VSCode give some clue where we should look into?

**Comment by mjbvz** [comment] 2021-12-10 21:14
This seems like duplicate of #138794

**Closed by mjbvz** 2021-12-10 21:14 UTC
Labels: needs more info

**Comment by nbili** [comment] 2021-12-13 09:25
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

![image](https://user-images.githubusercontent.com/22109673/145785797-c8068845-8b16-46a9-8711-dce47017bad4.png)
