### ISSUE TITLE
Statusbar path truncation cuts off graphemes

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#99306] opened 2020-06-03 18:02 UTC
Paths are not truncated too well in the status bar. For example, an "n" gets rendered like "r".

Also, no ellipsis is present to help distinguish between true paths versus truncated paths.

- VSCode Version: 1.45.1
- OS Version: macOS 10.14

Steps to Reproduce:

1. Open a long directory path.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment] 2020-06-04 06:06
Maybe dupe of https://github.com/microsoft/vscode/issues/84258

**Closed** 2020-06-04 08:32 UTC
Labels: *duplicate, workbench-status
