### ISSUE TITLE
vscode not being able to open files and folders

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#101274] opened 2020-06-29 11:02 UTC
- VSCode Version: 1.44.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a folder in VSCode using terminal. `code .` after moving to that folder.
2. Delete that folder using the terminal. I did `rm -r folder_name`
3. Now, try opening any other folder using VSCode through the terminal. It will not be able to open any folder from the PC. (Make sure you keep that old VSCode window open).

Additional:
This gets fixed when I close the old VSCode window but it is still a bug, I guess.

Does this issue occur when all extensions are disabled?: Yes

**Comment by qt1** [comment] 2020-07-01 21:53
Same here

Reinstalled, them done
```
killall code
```

then it works again..

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-39-generic

**Comment by Tyriar** [comment] 2020-07-07 19:51
A lot of things will break when you delete the folder that's opened.

**Comment by qt1** [comment] 2020-07-08 07:40
`code .`  Works most of the time.

But sometimes it just opens the last opened folder instead.

This is confirmed yesterday and it is definitely not as expected. It is hard to believe that unpredictable behaviour is by design..

**Comment by Tyriar** [comment] 2020-07-08 13:11
You're right, it is a little weird. See repro below:

![recording (4)](https://user-images.githubusercontent.com/2193314/86922662-d3189680-c0e1-11ea-8f3c-29c5d051648c.gif)

Note that when I open the first window using `code temp` is _does not_ reproduce.

**Comment by Tyriar** [comment] 2020-07-08 13:12
In console:

![image](https://user-images.githubusercontent.com/2193314/86922786-fb07fa00-c0e1-11ea-9942-a98c6a9b8f49.png)

**Comment by bpasero** [comment] 2020-07-08 14:39
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Closed by bpasero** 2020-07-08 14:39 UTC
Labels: *duplicate, nodejs
