### ISSUE TITLE
git extension: modify renamed file show `R` in  working tree

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#175665] opened 2023-02-28 16:11 UTC
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
Steps to Reproduce:

1. change a file to other name, for example `a.ts -> b.ts`
2. stage `b.ts`
3. modify `b.ts` content
4. It show `R` rather than `M`

I think user would pay more attention on modified file, also we should show the latest status to user.

<img width="465" alt="Screenshot 2023-03-01 at 00 02 09" src="https://user-images.githubusercontent.com/20318608/221910201-b275f2dd-8411-4070-a835-740f77b6cea4.png">

**Comment by lszomoru** [comment] 2023-12-13 11:25
Thank you very much for filing this issue. The root cause of the problem is that file decorations (ex: R, M) are associated to a particular URI. In this case, the file in the "staged changes" and "changes" resource groups is the same hence both resources are showing the "R" decoration. Fixing this issue would require us to have different URI for the file in the two resources groups, which is doable but it is quite an undertaking so for the time being I will go ahead and close this issue as "won't fix".

**Closed by lszomoru** 2023-12-13 11:25 UTC
Labels: bug, git, confirmed
