### ISSUE TITLE
GlobPattern requires case-sensitive drive letters on Windows

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#104387] opened 2020-08-10 17:53 UTC
I am using the file watching API via the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles) for the [Go language server](https://golang.org/s/gopls).

It seems that the API requires the drive letter in the GlobPattern to always be lowercased. We have noticed that the rootURI in the language client's initialize request always has a lowercase drive letter on Windows, but due to underlying tooling that preserves case, we do not always have lowercased drive letters in the server itself.

When the server sends a file watch request for a GlobPattern with an uppercased drive letter, we do not get any notifications. When we lowercase the drive letter, we do receive notifications.

Is this expected behavior? It seems like this should work no matter the case of the drive letter, especially since VS Code is itself changing the letters to be lowercase.

**Comment by bpasero** [comment] 2020-08-12 10:00
Slightly related: https://github.com/microsoft/vscode/issues/101042

**Comment by bpasero** [comment] 2020-08-12 14:54
Actually this is likely a duplicate of #101042. I would assume that the language server protocol is using the `IRelativePattern` support which will trigger #101042.

As long as we have not adopted `URI` support down to the glob level, this issue persists. The workaround is to ensure that drive letters are lowercased.

**Closed by bpasero** 2020-08-12 14:54 UTC
Labels: debt, file-glob, file-watcher

**Comment by stamblerre** [comment] 2020-08-12 15:01
Thanks for the explanation! I'm curious--will the fix for #101042 also work for absolute paths? Are absolute paths supported in the GlobPattern?

**Comment by bpasero** [comment] 2020-08-12 15:05
If you must include absolute paths in the glob you should use `IRelativePattern` as it will take care of all the things. If your pattern simply puts file paths within, you may hit an issue where glob paths are actually case sensitive: https://github.com/microsoft/vscode/issues/10633

**Comment by stamblerre** [comment] 2020-08-12 15:32
I don't have access to `IRelativePattern`, since the language server I'm working on is written in Go.

The reason I ask is that it's not clear from the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles) if GlobPatterns support absolute paths or not. It's currently not an issue for us because of #100870, but other clients may support watching files outside of a user's workspace, and I'm not sure how to correctly provide those paths in the GlobPattern.

**Comment by bpasero** [comment] 2020-08-12 15:36
Yeah, we evaluate the pattern against the full file path for file events, so it should be fine.

**Comment by stamblerre** [comment] 2020-08-12 15:37
Thanks for the clarification!
