### ISSUE TITLE
Git: commit input field looses its text when switching views

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#48827] opened 2018-04-27 13:27 UTC
Steps to Reproduce:

1. type some text in the input field
2. click on the explorer
3. click back

=> the text is gone

**Comment by yume-chan** [comment] 2018-04-28 09:10
duplicate of #41232 :-)

**Comment by joaomoreno** [comment] 2018-06-27 09:44
This seems fixed now.

**Closed by joaomoreno** 2018-06-27 09:44 UTC
Labels: bug, git
