### ISSUE TITLE
Space in wrapped line marked as duplicated

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode#79267] opened 2019-08-16 03:42 UTC
Issue Type: <b>Bug</b>

Set `"editor.renderWhitespace": "boundary"` in settings. Or `"editor.renderWhitespace": "selection"`.  Set word wrap.

Open a markdown file. Take any long line that wraps with only one space between words.

Add characters at the beginning of line till a space appears at the beginning of the wrapped line.

Note the character is marked as duplicated (centered pale dot).

This is incorrect because it is not a duplicated space.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
spellright|ban|3.0.46
github-markdown-preview|bie|0.0.2
markdown-yaml-preamble|bie|0.0.4
vscode-toggle-quotes|Bri|0.3.2
refactorix|chr|0.3.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|9.9.3
vscode-great-icons|emm|2.1.47
vscode-todo-plus|fab|4.14.0
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.5
todo-tree|Gru|0.0.141
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.12.1
prettify-json|moh|0.0.3
notepadplusplus-keybindings|ms-|1.0.3
leaper|Onl|0.5.3
vscode-jscpd|pau|0.3.4
bib|phr|0.3.0
vscode-javascript-booster|sbu|0.11.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.4.3
unique-window-colors|stu|1.0.51
highlight-matching-tag|vin|0.9.3
vscodeintellicode|Vis|1.1.9
highlight-bad-chars|wen|0.0.3
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by alexandrudima** [comment] 2019-08-16 09:28
Here is how it looks:
![Kapture 2019-08-16 at 11 28 17](https://user-images.githubusercontent.com/5047891/63158178-fa253000-c018-11e9-8ec5-eab990804023.gif)

**Comment by crystalfp** [comment] 2019-08-16 09:54
It happens if the very last character of a line is a comma.
![Annotation 2019-08-16 114854](https://user-images.githubusercontent.com/865866/63159596-34440100-c01c-11e9-9d3f-df83bb09deef.jpg)

Try this text: `Non ci vuole molta fantasia a convincersi che queste capacità sono fondamentale per lavorare, come me, nel supercalcolo.` adjust the width until the comma after `lavorare` becomes the last character of the line.

**Comment by crystalfp** [comment] 2019-08-16 09:57
It happens for `,` and `;` but not for `.` or `:`

The font is "editor.fontFamily": "iA Writer Mono S, monospace"

Hope it helps
mario

**Comment by crystalfp** [comment] 2019-08-16 10:05
`?` happens, `!` not happens

**Comment by crystalfp** [comment] 2019-08-20 13:32
Just for completeness, it happens also with other fonts. I tried Consolas, Fira Code, Operator Mono Book

**Comment by alexdima** [comment] 2020-01-17 23:45
Duplicate of #47990

Fixed with the fix for #33366

**Closed by alexdima** 2020-01-17 23:45 UTC
Labels: bug, editor-render-whitespace
