### ISSUE TITLE
Markdown (Pre-)View Default Options

### ISSUE THREAD

**Issue by jcgerhard** [microsoft/vscode#82331] opened 2019-10-11 08:21 UTC
# Markdown (Pre-)View Default Options

## Motivation

First of all: I really really like VSCode! I tried a lot of other editor/IDEs before, but none of them felt so comfortable and smooth like this. So I dropped all other apps and started to go my way with VSCode as my "everyday-swiss-army-knife" for coding, texting, writing, note-taking and everything else that needs a text editor.

My job as a solution engineer requires a very good information- and note-taking concept and managment.
One of the most done things day in day out is to take notes.
So I started to find a good suitable note-taking app that supports standard markdown without any (properitary) encoding or something like that.

There are some good alternatives out there, but the biggest problems I have with all of them are:
* I have to use a second application with another file/folder structure
* I have to leave VSCode to look for my notes
* I can't use my beloved VSCode workspaces for a "wiki folder"
* No suitable or adaptable shortcuts
* Oftentimes a bad search function

And many other little things that makes the daily work disruptive and uncomfortable.

VSCode supports markdown out-of-the-box (perfectly fine!) but with an unpleasant behavior when it comes to read-only markdown files in preview mode.

It always opens the markdown code view first and then you have to open the preview mode in addition. And that not instead of the code view but in addition to the current file as a side-by-side view. It is absolutely ok, that you have this option, but this is very uncomfortable if you want to read-only your markdown files/notes and/or use them as presentation slides!

**But that is what you want most of the time...just read your markdown files in preview mode!**

## Related (but closed/locked) Issue
I found the following feature request I joined...
* https://github.com/Microsoft/vscode/issues/54776

...but that was locked a few days ago with the following comment:
> Locking as none of the comments are anything but fancy +1s.
> If you are actually interested in working on this feature
> and have ideas on how to implement it, please let me know
> (just open a separate issue and reference this one)

Because the annotator is completely right, I'll go to try my luck here with this brand new feature request including a (hopefully) sufficient description of what I (and by the way, a lot of other users) am/are obviously missing as a feature.

## Feature Description

The idea is to have the option to choose the default view of markdown files that will be open in VSCode.

This setting could be named like:
* Markdown > Preview > Default

This option should be available as a general user **and** as a workspace setting.

### User and Workspace settings

![01_vscode_markdown_preview](https://user-images.githubusercontent.com/29855366/66635881-59b24d00-ec10-11e9-9aa1-bbcffdd4e1fb.jpg)

You could have 3 option to choose:
* Preview Mode
* Editor Mode
* Side-By-Side Mode

![02_vscode_markdown_preview_options](https://user-images.githubusercontent.com/29855366/66635915-6b93f000-ec10-11e9-8540-8c3b242f7c2e.jpg)

In addition you can toggle between both modes with a button and a customizable key shortcut.

"Preview Mode" opens markdown files always in preview mode, "Editor Mode" opens markdown files always in the code view and "Side-By-Side Mode" opens always both views next to each other.

### Toggle Button

Whatever mode you choose as "default" you can always toggle between the views with a toggle button.

![04_vscode_markdown_preview_animation](https://user-images.githubusercontent.com/29855366/66635936-764e8500-ec10-11e9-88a1-0719a2c91939.gif)

But switching between modes means to switch the view within the same window.
For reference: this behavior is perfectly integrated in apps like...

* Notable
* Typora
* Joplin

### Keyboard shortcuts
The keyboard shortcuts definition could be like that:

![03_vscode_markdown_preview_toggle](https://user-images.githubusercontent.com/29855366/66635999-941bea00-ec10-11e9-973a-184bcaa5db72.jpg)

## Conclusion

VSCode is IMHO the best editor/IDE on the market right now. I know this is a very subjective opinion and I don't want to start another editor war here.
Such a tightly integrated feature as described above would kick out a lot of other apps and would make VSCode much more powerfull and versatile! And it would also make the lifes easier for a lot of ppeople that need to use (markdown) notes day in day out.

You can stay in VSCode most of the time and you can use the very powerful find and search options you have right now. VS Code would getting a perfect note-taking app!

**Thanks for reading this request and to all of the developers and contributors! All of you are doing a great job!**

**Comment by mjbvz** [comment] 2019-10-11 16:03
Duplicate of #54776

Thanks for the writeup. The problem is not that we don't understand the feature request but that we are looking for help implementing it. if you are interested in trying this, start by taking a look at the builtin markdown extension: https://github.com/microsoft/vscode/blob/36aa903d5a98ba5cf1d46b84c0a8fb3c2106bd8a/extensions/markdown-language-features

**Closed by mjbvz** 2019-10-11 16:03 UTC

**Comment by jcgerhard** [comment] 2019-10-18 13:02
Thanks @mjbvz for your reply!
I would really like to contribute but at the end I have to admit, that I am not that good as a programmer to do this. Maybe you could leave this issue (re-)open for the future? Maybe some other contributor has the time and knowledge to do this?
