### ISSUE TITLE
TypeScript and JavaScript Language Features crashes extension host

### ISSUE THREAD

**Issue by geniodellavittoria** [microsoft/vscode#84842] opened 2019-11-14 15:46 UTC
Issue Type: <b>Bug</b>

When enabling the builtin "TypeScript and JavaScript Language Features" extension the Extension Host crashes and i dont have any language support for Typescript. I already tried a complete reinstall of VS Code and using VS Code insiders but got never rid of that issue. 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![image](https://user-images.githubusercontent.com/18641619/68872537-799ccb00-06fe-11ea-881a-81f5878e77cf.png)

console of VS Code
![image](https://user-images.githubusercontent.com/18641619/68872586-920ce580-06fe-11ea-8225-ed1acd50cb6b.png)

**Comment by mjbvz** [comment] 2019-11-14 17:45
Do you have any other extensions installed?

**Comment by mjbvz** [comment] 2019-11-14 17:52
Duplicate of #84803

**Closed by mjbvz** 2019-11-14 17:52 UTC
