### ISSUE TITLE
TypeScript Syntax Highlighting Broken

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/vscode#56706] opened 2018-08-17 17:01 UTC
Issue Type: <b>Bug</b>

I updated to latest version 1.26.1 and now code that was viewed properly before no longer has proper syntax highlighting

![image](https://user-images.githubusercontent.com/2856501/44278950-774e7700-a204-11e8-8a64-a5687359424c.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (16.45GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
gc-excelviewer|Gra|2.1.25
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
python|ms-|2018.7.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.3
debugger-for-chrome|msj|4.8.2
code-spell-checker|str|1.6.10
vscode-adaptivecards|tom|1.1.3

</details>

**Comment by gluons** [comment] 2018-08-18 14:43
Subscribed!

I also face the same problem. Color looks weird and inconsistent.

![default](https://user-images.githubusercontent.com/4688092/44300333-9695f300-a32f-11e8-9019-3d61956ec754.png)

**Comment by mattmazzola** [comment] 2018-08-20 15:44
Here is a link to the file I had screenshot from above:
https://github.com/Microsoft/ConversationLearner-SDK/blob/c0c4f4a511b754c595e6368fcbd7e6b585665898/src/CLRunner.ts#L259

Interestingly I noticed the syntax highlighting on this file is also broken in almost the same locations with same affects on GitHub as it is in VSCode.  Perhaps this can be clue to fix the issue.

**Comment by mjbvz** [comment] 2018-08-20 16:17
Seems fixed in latest insiders build
![screen shot 2018-08-20 at 6 14 50 pm](https://user-images.githubusercontent.com/12821956/44352621-2c06c380-a4a5-11e8-8a69-d91dd7bd59e5.png)

Let me know if you still see this issue in the current insiders

**Closed by mjbvz** 2018-08-20 16:17 UTC
Labels: needs more info, new release

**Comment by mjbvz** [comment] 2018-08-20 16:31
@gluons Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/653 for that

In the future please open a separate issue as it makes tracking and management easier

**Comment by mattmazzola** [comment] 2018-08-20 16:37
Hmm. I just downloaded the insiders and still see the error. Even disabled all extensions.  Was the version below the one you were using?  Is there a better way for me to verify?

VS Code version: Code - Insiders 1.27.0-insider (6e559261f677793fea424c6eb5cb13d0301ffff1, 2018-08-20T08:36:52.887Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (15.03GB free)|
|Process Argv|C:\Users\mattm\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment] 2018-08-20 16:49
Oh yeah format on paste fixes this if you copy it from github. Caused by a trailing space messing up syntax highlighting. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/654 to track this
