### ISSUE TITLE
Make F5 refresh when files explorer focused

### ISSUE THREAD

**Issue by ryanwilliams83** [Microsoft/vscode#41065] opened 2018-01-03 01:15 UTC
Suggestion to include this in the default key binds

{ "key": "f5",                    "command": "workbench.files.action.refreshFilesExplorer",
                                     "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus" }

**Comment by isidorn** [comment] 2018-01-03 09:10
Thanks for the suggestion however F5 should always start debugging, no metter where the focus is.
A lot of our users come from Visual Studio and that is the default behavior there.
Also we would be breaking a lot of users who are used to hitting F5 while focus in explorer to just start debug.

Due to that I am closing this as designed and you can always customize the keybinding as it suits you.

**Closed by isidorn** 2018-01-03 09:10 UTC
Labels: file-explorer
