### ISSUE TITLE
code-alpha --install-extension lets me install the same extension twice

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6799] opened 2016-05-24 13:25 UTC
Testing #6099
```
> code-alpha --install-extension aeschli.vscode-css-formatter
Found 'aeschli.vscode-css-formatter' in the marketplace.
Installing...
Extension 'aeschli.vscode-css-formatter' v0.0.2 was successfully installed!
> code-alpha --install-extension aeschli.vscode-css-formatteR
Found 'aeschli.vscode-css-formatteR' in the marketplace.
Installing...
WARNING: Promise with no error callback:14
{ exception: null,
  error: [ , , [ [Object] ] ],
  promise:
   { _oncancel: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function],
        cancel: [Function: r],
        done: null,
        then: null,
        _completed: [Function: r],
        _error: [Function: r],
        _notify: [Function: h],
        _progress: [Function: r],
        _setCompleteValue: [Function: r],
        _setErrorValue: [Function: r] },
     _listeners: null,
     _value: [ , , [Object] ],
     _isException: false,
     _errorId: 14,
     done: [Function],
     then: [Function] },
  handler: undefined,
  id: 14,
  parent: undefined }

C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\code\node\cli.js:5
enter:function(e){if(e.done=z.prototype.done,e.then=z.prototype.then,e._listeners)for(var t,n=[e];n.length;)t=n.pop(),t._state._notify(t,n);e._setState(I)},cancel:r,done:null,then:null,_completed:r,_error:r,_notify:h,_progress:r,_setCompleteValue:r,_setErrorValue:r},I={name:"error",enter:function(e){e.done=z.prototype.done,e.then=z.prototype.then,e._cleanupAction()},cancel:r,done:null,then:null,_completed:r,_error:r,_notify:h,_progress:r,_setCompleteValue:r,_setErrorValue:r};var H,V=t.Class.define(null,{_listeners:null,_nextState:null,_state:null,_value:null,cancel:function(){this._state.cancel(this),this._run()},done:function(e,t,n){this._state.done(this,e,t,n)},then:function(e,t,n){return this._state.then(this,e,t,n)},_chainedError:function(e,t){var n=this._state._error(this,e,a,t);return this._run(),n},_completed:function(e){var t=this._state._completed(this,e);return this._run(),t},_error:function(e){var t=this._state
,,Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\martinae\.vscode-alpha\extensions\aeschli.vscode-css-formatter-0.0.2\node_modules\js-beautify'
```

**Comment by joaomoreno** [comment] 2016-05-24 14:03
Duplicate of #6732

**Closed by joaomoreno** 2016-05-24 14:03 UTC
