### ISSUE TITLE
Setting open file in new tab (not replaced current tab)?

### ISSUE THREAD

**Issue by SiriusGuo** [Microsoft/vscode#4820] opened 2016-03-31 09:49 UTC
- VSCode Version: 0.10.11
- OS Version: Windows 10

How can I setting open file in new tab when I select it from folder/file tree just like sublime text?(not replaced opened tab.)
I can't find where to config this.
Could anybody help me please?
Thx!

**Comment by Tyriar** [comment] 2016-03-31 17:05
Do you mean when navigating the explorer with the keyboard?

**Comment by bpasero** [comment] 2016-03-31 17:20
I am marking this as duplicate of #224 because today you cannot use tabs in vscode.

@SiriusGuo as a workaround you can Ctrl+click on a file to open it to the side of the file, so that you do not replace the file.

**Closed by bpasero** 2016-03-31 17:20 UTC
Labels: needs more info, workbench

**Comment by Afolayan** [comment] 2017-07-19 08:58
After a year, you now have tabs in vscode. To have a new tab, press Ctrl+Shift+P, type Preference: Open User Settings, look for workbench.editor.enablePreview, set the value to false.
That should fix it.
