### ISSUE TITLE
IntelliSense for keybindings.json's 'when'

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14866] opened 2016-11-02 17:54 UTC
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Just that: Add IntelliSense for keybindings.json's 'when' attribute.

**Comment by gregvanl** [comment] 2016-11-02 21:16
Duplicate of https://github.com/Microsoft/vscode/issues/9303

**Closed** 2016-11-03 08:46 UTC
Labels: duplicate, feature-request, keybindings
