### ISSUE TITLE
[json] self referencing definitions cause endless loop

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64225] opened 2018-12-03 15:54 UTC
1. Start vscode out of source. Open a `tasks.json` file
2. Reload the window
3. Quick vscode

Notice helper processes lying around.
I can repro this 100% of the time on my mac os. Let me know if you can not repro and need more details
Adding important since this slows down my cpu considerably

**Comment by bpasero** [comment] 2018-12-03 15:58
@isidorn I cannot reproduce:
* open vscode out of sources, has a TS file
* reload window
* quit
* check htop for the process

Whats the full command line of the OSS helper process?

**Comment by isidorn** [comment] 2018-12-03 16:00
So maybe open a .json file, than reload and let me know if you can repro

➜  vscode git:(master) ps aux | grep 19457
isidor           19457  99.4  0.3  5071436  54500 s002  R     4:58PM   0:38.17 /Users/isidor/Development/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper.app/Contents/MacOS/Code - OSS Helper --nolazy --inspect=18224 /Users/isidor/Development/vscode/extensions/json-language-features/server/out/jsonServerMain --node-ipc --clientProcessId=19446
isidor           19500   0.0  0.0  4279300    720 s002  R+    4:58PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 19457

**Comment by bpasero** [comment] 2018-12-03 16:08
I cannot reproduce. This looks like an extension not shutting down properly, moving to @alexandrudima (since @aeschli is out for the JSON extension which probably did not change).

**Comment by isidorn** [comment] 2018-12-03 16:11
Let me know if you need more details from my side.
Also if I am the only one seeing this feel free to remove important label.

**Comment by bpasero** [comment] 2018-12-03 16:16
@isidorn yeah like:
* does it reproduce with any JSON file
* does it reproduce from a fresh user data dir (empty settings)

**Comment by bpasero** [comment] 2018-12-03 16:29
@isidorn yes sir, reproduces

**Comment by alexandrudima** [comment] 2018-12-04 09:40
Ok, here are my findings:
* This has nothing to do with the extension host
* The JSON language server spins at 100% CPU for any file called `tasks.json`
* IMHO there is something in the schema of `tasks.json` that leads to the JSON language server to spin at 100%
* That process is not using the C++ watchdog module

I suggest we:
* fix the issue in JSON next milestone (@aeschli)
* fix the issue in the `tasks.json` schema now (@alexr00 @dbaeumer)

**Comment by alexr00** [comment] 2018-12-04 14:31
I think this should be fixed as a result of fixing #64207. That one caused ALL json files opened after tasks.json to have no intellisense.

**Comment by dbaeumer** [comment] 2018-12-04 14:34
@alexr00 thanks for looking into it.

**Comment by isidorn** [comment] 2018-12-04 14:48
Yes this is probalby fixed. However my [comment](https://github.com/Microsoft/vscode/issues/64225#issuecomment-443775805) still holds.

So should we simply move this to december and remove the important to reflect that?

**Comment by alexr00** [comment] 2018-12-05 10:47
Since this is an issue that has probably been around for a while it can probably wait until @aeschli can do it.

**Comment by aeschli** [comment] 2019-01-28 14:17
fixed

**Closed by aeschli** 2019-01-28 14:17 UTC
Labels: bug, confirmed
