### ISSUE TITLE
Crash after clicking on Open Folder

### ISSUE THREAD

**Issue by elviraToumasi17** [microsoft/vscode#230938] opened 2024-10-09 15:26 UTC
Type: <b>Bug</b>

1. Click on File
2. Click on Open Folder
Result: Visual Studio Code crashes immediately

However, I can drag a folder to the app and it will load it with no issue.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2307)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|6, 2, 1|
|Memory (System)|15.25GB (12.18GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 0690cf3c-0f77-4aaa-b2cd-316fb9d40a25|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|3.0.5
vscode-protractor-snippets|dee|1.0.5
gitlens|eam|15.6.0
vscode-pull-request-github|Git|0.98.0
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
chai-snippets|nwh|0.1.0
code-spell-checker|str|3.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
showbadge:31153266
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-10-09 15:36
/duplicate of pinned issue https://github.com/microsoft/vscode/issues/230454

**Closed** 2024-10-09 15:37 UTC
Labels: *duplicate, new release
