### ISSUE TITLE
Typescript IntelliSense Error

### ISSUE THREAD

**Issue by phoenixzw** [Microsoft/vscode#26620] opened 2017-05-14 13:41 UTC
- VSCode Version: 1.12.1
- OS Version: MacOS: 10.12.4 (16E195)

I am using VSCode for D3js visualization development. The problem is using the newest (1.12.1) VSCode, I find the IntelliSense is missing in Typescript. When I reopen the project, the IntelliSense appears but disappears some time later (several minutes).  The bug is strange, because it only appears in some of my projects. I do not know why. Now, I rollback to 1.11.2, the problem is missing. Is there anyone who could help me resolve this issue? Thanks.

Steps to Reproduce:
It is hard to reproduce the problem. So I only show one of the code that causes this problem.

```ts
///<reference path="GlobalData.ts" />
///<reference path="ImgGallery.ts" />
///<reference path="ScatterPlotSeries.ts" />

namespace UIs {
    export class ScatterPlot {
        private dataItems: Array<{x:number, y:number, fre:number, xVal:number, yVal:number}>;
        private emptyDataItems: Array<{x:number, y:number}> = [];
        private coorXYMapper: Array<Array<Array<RectData>>>;
        private imgGallery: ImgGallery;
        private imgThreshold: number;
        private scatterPlotSeries: ScatterPlotSeries;
        private attrX: string;
        private attrY: string;
        private globalData: GlobalData;
        private zoomThreshold = 12;
        private zoomStatus = 0;
        private selectedRectIDs: number[];
        private clickedPoint = {this: null, opacity: 0};

        public svgMain: d3.Selection<any, any, any, any>;
        public svgZoom: d3.Selection<any, any, any, any>;
        private gridLength: number;
        private gridNum: number = 60;
        private xScale: d3.ScaleLinear<number, number>;
        private yScale: d3.ScaleLinear<number, number>;
        private xAxisScale: d3.ScaleLinear<number, number>;
        private yAxisScale: d3.ScaleLinear<number, number>;
        private svgWidth: number = 800;
        private svgHeight: number = 800;
        private width: number;
        private height: number;
        private margin = {top: 20, left: 70, bottom: 20, right: 40};
        // private opacityScale: d3.ScaleQuantile<number>;
        private opacityScale: d3.ScaleLinear<number, number>;
        private epsilon: number = 0.000007;
        private svgTemp: d3.Selection<any, any, any, any>;

        private xAxis: d3.Axis<any>;
        private yAxis: d3.Axis<any>;
        private svgXAxis: d3.Selection<any, any, any, any>;
        private svgYAxis: d3.Selection<any, any, any, any>;

        constructor(_data: Array<RectData>, _globalData: GlobalData, _scatterPlotSeris: ScatterPlotSeries, _svgMain: d3.Selection<any, any, any, any>) {
            this.globalData = _globalData;
            this.scatterPlotSeries = _scatterPlotSeris;
            this.svgMain = _svgMain;
            this.Initialization(_data);
            this.dataItems = this.DataTransform(_data);
            this.Draw();
            CustomizedCrossFilter(_globalData.scatterPlotData, _globalData.attrX, _globalData.attrY, this.scatterPlotSeries.currentState);
        }

        private Initialization(_data: Array<RectData>) {
            this.imgThreshold = this.scatterPlotSeries.imgThreshold;
            this.svgWidth = this.scatterPlotSeries.svgWidth;
            this.svgHeight = this.scatterPlotSeries.svgHeight;
            this.attrX = this.scatterPlotSeries.attrX;
            this.attrY = this.scatterPlotSeries.attrY;

            this.height = this.svgHeight - this.margin.top - this.margin.bottom;
            this.width = this.svgWidth - this.margin.left - this.margin.right;
            this.gridLength = this.width / this.gridNum;
            let xDataExtent = d3.extent(_data, (d) => { return d.xVal; } );
            let yDataExtent = d3.extent(_data, (d) => { return d.yVal; } );

            this.xScale = d3.scaleLinear()
                .range([0, this.gridNum - 1])
                .domain(xDataExtent);
            this.xAxisScale = d3.scaleLinear()
                .domain(xDataExtent)
                .range([0, this.width]);

            this.yScale = d3.scaleLinear()
                .range([this.gridNum - 1, 0])
                .domain(yDataExtent);
            this.yAxisScale = d3.scaleLinear()
                .domain(yDataExtent)
                .range([this.height, 0]);

            // let opacitySteps = [0.1], step = 0.1;
            // for (let i = 0; i < Math.floor(0.9/step); i++)
            //     opacitySteps.push(opacitySteps[i] + step);
            // this.opacityScale = d3.scaleQuantile()
            //     .range(opacitySteps);
            this.opacityScale = d3.scaleLinear()
                .range([0.1, 1]);
        }

        private DataTransform(_data: Array<RectData>) {
            let dataItems: Array<{x: number, y:number, fre: number, xVal:number, yVal: number}> = [];
            let opacityExtent = [Infinity, -Infinity];
            this.coorXYMapper = [];
            for (let i = 0; i < this.gridNum; i++) {
                this.coorXYMapper.push([]);
                for (let j = 0; j < this.gridNum; j++)
                    this.coorXYMapper[i].push(null);
            }

            for (let i = 0; i < _data.length; i++) {
                let x = Math.floor(this.xScale(_data[i].xVal));
                let y = Math.floor(this.yScale(_data[i].yVal));
                if (this.coorXYMapper[x][y] == null)
                        this.coorXYMapper[x][y] = [];
                this.coorXYMapper[x][y].push(_data[i]);
            }

            for (let i = 0; i < this.gridNum; i++)
                for (let j = 0; j < this.gridNum; j++)
                    if (this.coorXYMapper[i][j] != null) {
                        dataItems.push({x: i, y: j, fre: this.coorXYMapper[i][j].length,
                            xVal: this.coorXYMapper[i][j][0].xVal,
                            yVal: this.coorXYMapper[i][j][0].yVal });
                        for (let k = 0; k < this.coorXYMapper[i][j].length; k++)
                            this.coorXYMapper[i][j][k].rectIdx = dataItems.length - 1;
                        opacityExtent[0] = Math.min(opacityExtent[0], this.coorXYMapper[i][j].length);
                        opacityExtent[1] = Math.max(opacityExtent[1], this.coorXYMapper[i][j].length);
                    } else this.emptyDataItems.push({x: i, y: j});
                    
            opacityExtent[0] -= this.epsilon;
            this.opacityScale.domain(opacityExtent);
            // this.opacityScale.domain(Array.from(dataItems, (d) => { return d.fre} ));
            return dataItems;
        }

        private LoadImgs(selectedRectIDs: number[], prefix: string) {
            this.svgZoom.append("g")
                .selectAll(".images")
                .data(selectedRectIDs).enter()
                .append("pattern")
                .attr("id", (d, i) => { return "ScatterMeanImg" + i; } )
                //10 is also OK, but 20 is a little blur and this.gridSize is very blur.
                //I guess with the increase of width, it becomes blurer I cannot understand it.
                .attr("width", 1)
                .attr("height", 1)
                .append("image")
                .attr("xlink:href", (d, i) => { return "static/temp_data/" + prefix + "scatter_mean_img_" + i + ".jpg"; } )
                .attr("width", this.gridLength)
                .attr("height", this.gridLength);
            for (let i in selectedRectIDs) {
                let rect = d3.select("#Rect" + this.scatterPlotSeries.currentState + 'd' + selectedRectIDs[i]);
                rect.style("fill-opacity", 1)
                    .style("fill", "url(#ScatterMeanImg" + i + ")");
                if (this.dataItems[this.selectedRectIDs[i]].fre > 1)
                    rect.style("stroke-width", 0.1)
                        .style("stroke", "red");
            }
        }

        private Draw() {
            let zoomController = d3.zoom()
                .scaleExtent([0.37, this.gridNum / 1.2])
                .on("zoom", this.Zoom());

            this.svgZoom = this.svgMain.append("g")
                .attr("transform", "translate(" + this.margin.left + "," + this.margin.top + ")");

            // let svgBackground =  this.svgZoom.append("svg:rect")
            //     .attr("class", "border")
            //     .attr("width", this.width)
            //     .attr("height", this.height)
            //     .style("stroke", "black")
            //     .attr("pointer-events", "all")
            //     .style("fill", "none");

            this.svgZoom.append("clipPath")
                .attr("id", "RectsClip")
                .append("rect")
                .attr("width", this.width)
                .attr("height", this.height);

            let svgTemp1 = this.svgZoom.append("g")
                .attr("clip-path", "url(#RectsClip)")
                .append("g");
            this.svgTemp = svgTemp1.append("g");
            this.svgTemp.selectAll(".rects")
                .data(this.dataItems).enter()
                .append("rect")
                .attr("class", "RectGroups" + this.scatterPlotSeries.currentState)
                .attr("id", (d, i) => { return "Rect" + this.scatterPlotSeries.currentState + 'd' + i; } )
                .attr("x", (d) => { return d.x * this.gridLength; } )
                .attr("y", (d) => { return d.y * this.gridLength; } )
                .on("mouseover", function() {
                    if (d3.select(this).style("fill").indexOf("url") == -1)
                        d3.select(this).style("fill", "red").style("fill-opacity", 1);
                } )
                .on("mouseout", this.RectMouseOut() )
                .on("click", this.ScatterPlotClick() )  //No need to write like this
                .attr("width", this.gridLength)
                .attr("height", this.gridLength)
                .style("fill-opacity", (d) => { return this.opacityScale(d.fre); })
                .style("fill", "blue")
                .append("title")
                .text((d) => { return this.attrX +  ": " + d.xVal + ";\n" + this.attrY + ":" + d.yVal + ";\n#Samples: " + d.fre; });
            this.svgTemp.selectAll(".emptyRects")
                .data(this.emptyDataItems).enter()
                .append("rect")
                .attr("x", (d) => { return d.x * this.gridLength; } )
                .attr("y", (d) => { return d.y * this.gridLength; } )
                .style("fill-opacity", 0)
                .attr("width", this.gridLength)
                .attr("height", this.gridLength);

            this.DrawAxes();
            // Translation
            // this.svgMain.call(zoomController)
            //     .call(zoomController.translateBy, this.margin.left, this.margin.top);
            svgTemp1.call(zoomController);
        }

        private DrawAxes() {
            //Draw X,Y Axises
            this.xAxis = d3.axisBottom(this.xAxisScale);
            this.yAxis = d3.axisLeft(this.yAxisScale);

            this.svgXAxis = this.svgZoom.append("g")
                .attr("transform", "translate(0," + this.height + ")")
                .attr("class", "x axis")
                .call(this.xAxis);
            this.svgXAxis.append("text")
                .attr("x", this.width)
                .attr("dy", "0.71em")
                .attr("fill", "#000")
                .text("X Dim");
            this.svgYAxis = this.svgZoom.append("g")
                .attr("class", "y axis")
                .call(this.yAxis);
            this.svgYAxis.append("text")
                .attr("dy", "0.71em")
                .attr("fill", "#000")
                .text("Y Dim");
        }

        private Zoom() {
            return () => {
                this.svgTemp.attr("transform", d3.event.transform);
                this.svgXAxis.call(this.xAxis.scale(d3.event.transform.rescaleX(this.xAxisScale)));
                this.svgYAxis.call(this.yAxis.scale(d3.event.transform.rescaleY(this.yAxisScale)));

                let selectedRect: Array<{x: number, y: number}> = [];
                let selectedRectIDs: number[] = [];
                if (d3.event.transform.k > this.zoomThreshold && this.zoomStatus == 0) {
                    this.zoomStatus = 1;
                    for (let i = 0; i < this.dataItems.length; i++) {
                        let x = this.dataItems[i].x * this.gridLength * d3.event.transform.k + d3.event.transform.x;
                        let y = this.dataItems[i].y * this.gridLength * d3.event.transform.k + d3.event.transform.y;
                        if (x >= 0 && x <= this.width && y >= 0 && y <= this.height) {
                            selectedRect.push({x: this.dataItems[i].x, y: this.dataItems[i].y});
                            selectedRectIDs.push(i);
                        }
                    }
                    this.selectedRectIDs = selectedRectIDs;
                    let dataSent = Array.from(selectedRect, (d) => { return Array.from(this.coorXYMapper[d.x][d.y], (e) => { return e.idx; } ); });
                    let xhttp = new XMLHttpRequest();
                    xhttp.onreadystatechange = () => {
                        if (xhttp.readyState == 4 && xhttp.status == 200) {
                            let prefix: string = xhttp.responseText.substring(1, xhttp.responseText.length - 2);
                            this.LoadImgs(selectedRectIDs, prefix);
                        }
                    };
                    xhttp.open("POST", "/scatter_mean_img", true);
                    xhttp.setRequestHeader("Content-Type", "application/json");
                    xhttp.send(JSON.stringify(dataSent));
                }

                if (this.zoomStatus == 1 && d3.event.transform.k < this.zoomThreshold) {
                    this.zoomStatus = 0;
                    for (let i in this.selectedRectIDs) {
                        let rect = d3.select("#Rect" + this.scatterPlotSeries.currentState + 'd' + this.selectedRectIDs[i]);
                        rect.style("fill-opacity", this.opacityScale(this.dataItems[this.selectedRectIDs[i]].fre))
                            .style("fill", "blue");
                        if (this.dataItems[this.selectedRectIDs[i]].fre > 1)
                            rect.style("stroke-width", 0);
                    }
                }
            };
        }

        private RectMouseOut() {
            let This = this;
            return function(d: {x:number, y:number, fre:number, xVal:number, yVal:number}) {
                if (This.clickedPoint != this) {
                    if (d3.select(this).style("fill").indexOf("url") != -1)
                        return;
                    d3.select(this)
                        .style("fill-opacity", This.opacityScale(d.fre))
                        .style("fill", "blue");
                }
            };
        }

        private ScatterPlotClick() {
            let This = this;
            return function(d: {x:number, y:number, fre:number, xVal:number, yVal:number}, i) {
                console.log("Hello", i);
                if (This.clickedPoint.this) {
                    d3.select(This.clickedPoint.this)
                        .style("fill-opacity", This.opacityScale(This.clickedPoint.opacity))
                        .style("fill", "blue");
                }
                d3.select(this)
                    .style("fill-opacity", 1)
                    .style("fill", "red");
                This.clickedPoint = {this: this, opacity: d.fre};
                if (This.coorXYMapper[d.x][d.y].length > This.imgThreshold) {
                    console.log(This.imgThreshold);
                    This.scatterPlotSeries.NewScatterPlot(This.coorXYMapper[d.x][d.y]);
                } else {
                    This.imgGallery = new ImgGallery(This.coorXYMapper[d.x][d.y], This.globalData);
                }
            };
        }
    }
}

declare function CustomizedCrossFilter(_data: Array<UIs.RectData>, _attrX: string, _attrY: string, _index: number): void;
```

**Comment by mjbvz** [comment] 2017-05-16 03:51
Please try collecting a trace of the TypeScript server which powers our IntelliSense:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode and reproduce the issue.
3. Open the output panel and share the output at the `TypeScript` section.

Look for messages about canceled requests or errors in the output panel

**Comment by tariknz** [comment] 2017-05-16 07:35
I'm having issues with VSCode with D3 also. It seems like the syntax checking and autocompletion dies completely.

Here is the output from typescript:

```
[Error - 7:33:18 PM] TSServer exited with code: 3
[Error - 7:33:18 PM] 'completions' request failed with error.
Error: Service died.
    at Object.keys.forEach (d:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:687:45)
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (d:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:686:37)
    at ChildProcess.childProcess.on (d:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:479:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 7:33:18 PM] Using tsserver from: d:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Trace - 7:33:37 PM] TypeScript Service: canceled request with sequence number 21
[Trace - 7:35:18 PM] TypeScript Service: canceled request with sequence number 25
[Trace - 7:35:18 PM] TypeScript Service: canceled request with sequence number 23
[Trace - 7:35:19 PM] TypeScript Service: canceled request with sequence number 29
[Trace - 7:35:21 PM] TypeScript Service: canceled request with sequence number 32
```

**Comment by mjbvz** [comment] 2017-05-17 01:12
I believe the failure of TS to restart after exiting is a duplicate of https://github.com/Microsoft/vscode/issues/25807 . Please try out the latest insiders builds which should fix this.

To see why TypeScript is crashing in the first place, can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue
3. Run the `Open TSServer log File` command and view the `tsserver.log` file

This log will display all the files that are being included in your projects. You can scan through these file lists to see if any unexpected files are being included. If nothing stands out, please share the log so that we can take a look

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

Thanks

**Comment by tariknz** [comment] 2017-05-17 02:06
@mjbvz I can confirm it is working fine in the Insiders build (1.13.0)

Not much happening in the output:

```
[Info  - 1:54:13 PM] Using tsserver from: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 1:54:13 PM] TSServer log file: C:\Users\tarik\AppData\Local\Temp\vscode-tsserver-log-u6BAcK\tsserver.log
[Info  - 1:54:13 PM] Forking TSServer
PATH: undefined

```

Is there any other information you need?

**Comment by mjbvz** [comment] 2017-05-17 18:14
Thanks @tariknz. Glad to hear things appear to be working in the current insiders

If you see the intellisense stop working again, please try collecting the logs and we can reopen this issue

**Comment by mjbvz** [comment] 2017-05-17 18:17
Whoops, original issue was actually from @phoenixzw

@phoenixzw Can you please try out the insiders builds as well and collecting a trace if you see the issue

**Comment by phoenixzw** [comment] 2017-05-17 18:56
Hi Matt,

Since I am traveling, really sorry for the late response.
I have tried the insider build version and it works well.

Following is the collected information:

[Info - 2:54:36 PM] Using tsserver from: /Applications/Visual Studio Code -
Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info - 2:54:36 PM] Forking TSServer
PATH:
/Users/zhongwen/anaconda2/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/local/texlive/2014/bin/x86_64-darwin
[Trace - 2:54:36 PM] Sending request: configure (0). Response expected:
yes. Current queue length: 0
Arguments: {
"hostInfo": "vscode"
}
[Trace - 2:54:36 PM] Response received: configure (0). Request took 352 ms.
Success: true
[Trace - 2:54:36 PM] Sending request: compilerOptionsForInferredProjects
(1). Response expected: yes. Current queue length: 3
Arguments: {
"options": {
"module": "CommonJS",
"target": "ES6",
"allowSyntheticDefaultImports": true,
"allowNonTsExtensions": true,
"allowJs": true,
"jsx": "Preserve",
"checkJs": false
}
}


Best Regards
--

Wen Zhong


2017-05-17 14:18 GMT-04:00 Matt Bierner <notifications@github.com>:

**Comment by mjbvz** [comment] 2017-05-17 21:38
Ok, please let me know if you hit this issue again

**Closed by mjbvz** 2017-05-17 21:38 UTC
Labels: needs more info, typescript
