### ISSUE TITLE
workbench.action.focusRightGroup not focusing all editor groups

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#50694] opened 2018-05-29 16:33 UTC
VS Code version: Code - Insiders 1.24.0-insider (41a7c4976ebd1f6ced20c034485300f46ab1829f, 2018-05-29T06:09:34.618Z)
OS version: Windows_NT x64 10.0.16299

---

#50458

Keybinding:

```json
{ "key": "alt+right",       "command": "workbench.action.focusRightGroup", "when": "editorTextFocus" },
```

Start state:

![image](https://user-images.githubusercontent.com/2193314/40672257-16fad85a-6323-11e8-9585-45f2d73adb6c.png)

Pressing alt+right 5 times results in:

1. Top-right focused
2. Bottom-left focused
3. Top-right focused (moves the cursor to a seemingly random position)
4. Bottom-left focused 
5. Nothing

**Comment by bpasero** [comment] 2018-05-30 09:09
Treating as duplicate of https://github.com/Microsoft/vscode/issues/50679. I would not expect the focus to change once you are on the right hand side of the grid and continue to invoke this action. The fix is to implement these commands within the grid widget.

**Closed by bpasero** 2018-05-30 09:09 UTC
Labels: bug, insiders, workbench-grid
