### ISSUE TITLE
High CPU / maxed out / VSCode not responding after new install of VSCode on new Mac running OSX Catalina 10.15.4

### ISSUE THREAD

**Issue by chrisckc** [microsoft/vscode#95801] opened 2020-04-21 21:46 UTC
Issue Type: <b>Performance Issue</b>

VSCode not responding about 20 mins after launching, brand new install, no extensions, no activity, nothing loaded other than settings.json

This is on a new macbook pro 16inch, nothing has been installed yet other than Homebrew, python, git, iTerm2

To reproduce:
Install Latest VSCode on OSX Catalina 10.15.4, open the settings page and also the settings.json, leave it sat there for about 20 minutes doing nothing.

Suddenly notice the fans kick in and the CPU maxed out on both "code helper (renderer)" and "electron helper (renderer)" stays like this for a while until i decide not to cook the new Mac and so kill the processes. However this does not solve the issue as the CPU is still maxed out running "crashpad_handler" so have to kill that also.

I had issues on previous Mac running OSX Mojave and earlier with Code helper regularly maxing out the CPU and having to be killed off, but like most of the Github issues seem to suggest, assumed it was an issue with an extension and i never bothered to spend much time investigating.

This is the same issue but on on a brand new install with no extensions added, no file open other the the settings.json

These are the settings i added, in case it matters:

{
    "telemetry.enableTelemetry": false,
    "editor.tabSize": 2,
    "editor.rulers": [80],
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "workbench.editor.enablePreview": false
}

The issue seems very similar to this:
https://github.com/microsoft/vscode/issues/88779#issuecomment-598064880

The following Issue reporter output was generated after restarting VSCode and without the issue being present, i will try to run it again when it next occurs, but it i don't think that will be possible as VSCode was in a hung state, not responding.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (6.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	    98	 28243	code main
    0	    66	 28245	   gpu-process
    0	    33	 28247	   utility
    0	   262	 28248	   window (settings.json)
    0	    66	 28302	     extensionHost
    0	    66	 28303	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=28302
    1	    98	 28306	   shared-process
    0	     0	 28316	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	    66	 28312	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by chrisckc** [comment] 2020-04-21 22:04
Ill run `code -status` next time this happens, that will show the process info.

**Comment by mjmasn** [comment] 2020-04-22 07:00
Getting the same issue on Catalina 10.15.4 on the latest stable VSCode release. I think it's after saving a file, CPU of `Code Helper (Renderer)` goes to 100%, intellisense dies (ie doesn't appear when you start typing, or takes a very long time to appear), tslint messages take a minute or two to update after editing a file. Exiting and reopening VSCode works for a few minutes then we're back to the same issue again. Didn't happen until the recent VSCode update 1.44 (I'm currently on 1.44.2).

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

```
Version:          Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)
Memory (System):  16.00GB (1.12GB free)
Load (avg):       2, 2, 4
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	   115	 90560	code main
    1	    66	 90561	   gpu-process
    0	    16	 90563	   utility
    1	   360	 90564	   window (REDACTED)
    0	   115	 90565	     extensionHost
    0	    82	 90568	       electron_node tsserver.js
  115	  1163	 90569	       electron_node tsserver.js
    0	    66	 90591	         electron_node typingsInstaller.js typesMap.js
    0	    33	 90572	       electron_node eslintServer.js
    0	    33	 90624	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=90565
    0	    66	 90566	     watcherService
    0	    33	 90567	     searchService
    0	   115	 90570	   shared-process
    0	     0	 90965	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (REDACTED)
|    Folder (REDACTED): more than 28435 files
|      File types: hpp(9616) h(2666) flat(786) m(461) timestamp(432) pcm(431)
|                  tsx(281) xml(269) png(248) ts(190)
|      Conf files: package.json(3) tsconfig.json(1) tslint.json(1)
```

**Comment by bpasero** [comment] 2020-04-23 06:23
`115	  1163	 90569	       electron_node tsserver.js`

**Comment by mjmasn** [comment] 2020-04-23 12:14
Interestingly it seems fine today, I wonder if it was related to a particular file I was working on as it kept occurring even after killing all VSCode processes and re-opening. Today I've had no issues, working in same project but different files. Haven't rebooted or anything either.

If it happens again I'll make a note of the files I have open and see if that is the trigger. Of course it may be a different issue to the OPs anyway.

**Comment by mjmasn** [comment] 2020-04-29 10:10
Just to update on our specific case - it turned out to be caused by code similar to the following:

styles1.ts
```ts
import {StyleSheet} from 'react-native'

const styles1 = {
  thing1: {
    color: 'blue',
  },
  thing2: {
    color: 'red',
  },
}

export default styles1 as StyleSheet.NamedStyles<typeof styles1> 
```

styles.ts
```ts
import styles1 from './styles1'
import styles2 from './styles2'
import styles3 from './styles3'

export default StyleSheet.create({
  ...styles1,
  ...styles2,
  ...styles3,
  someOtherStyle: {
    color: 'pink',
  },
})
```

other.tsx
```ts
import styles from './styles'

type Props = {}

export const Other = (props: Props) => <View style={styles.view1} />

const styles = StyleSheet.create({
  view1: {
    ...styles.thing1,
    ...styles.someOtherStyle,
  },
})
```

As the number of spreads into the view1 style increased, the CPU usage would increase. I think above 5 or 6 and it would start hanging. This would only happen if using styles from the sub-files (i.e. styles1/2/3) and would happen with or without the `export as StyleSheet.NamedStyles...` cast in those files. Spreading styles from the base styles file (e.g. ...styles.someOtherStyle) worked fine.

The solution in our case was to change styles1/2/3.ts to:

```ts
import {StyleSheet} from 'react-native'

const styles1 = StyleSheet.create({
  thing1: {
    color: 'blue',
  },
  thing2: {
    color: 'red',
  },
})

export default styles1
```

**Comment by mjbvz** [comment] 2020-10-14 09:12
Closing as we have not seen recent reports of this issue

**Closed by mjbvz** 2020-10-14 09:12 UTC
Labels: freeze-slow-crash-leak, typescript
