### ISSUE TITLE
After the update - tabing after writing commit dosen't go to commit (accessibility)

### ISSUE THREAD

**Issue by Parthvsquare** [microsoft/vscode#200984] opened 2023-12-15 16:34 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

Steps to Reproduce:

1. write a commit 
2. try tabing to commit button
[link]: https://imgur.com/a/2qF9Len

**Comment by lszomoru** [comment] 2023-12-16 14:15
@Parthvsquare, thank you very much for the recording. Will investigate and get back to you.

**Comment by lszomoru** [comment] 2024-01-31 12:32
Adding @joaomoreno as this is caused by the fact that list DOM elements do not respect the visual order.

**Comment by Parthvsquare** [comment] 2024-02-06 21:44
not sure, which update fixed it but its working as expected. should i close it?

**Comment by lszomoru** [comment] 2024-02-07 11:47
@Parthvsquare, thank you very much for the update. The issue only gets triggered in certain cases in which the order of the DOM elements does not match the visual order of the elements in the list. We have pushed a fix to address the underlying issue couple of hours ago so starting with tomorrow's VS Code Insiders release things should work consistently.

I will go ahead and close this issue but please feel free to reopen it in case you are still able to reproduce the issue with the latest VS Code Insiders release. Thank you very much!

**Closed by lszomoru** 2024-02-07 11:47 UTC
Labels: bug, list-widget

**Comment by eleanorjboyd** [comment] 2024-02-21 22:19
Currently it takes 2 "tabs" to get to the commit button, the first one goes to the sparkle icon if present from copilot. Is this the desired behavior?

**Comment by Parthvsquare** [comment] 2024-02-22 10:15
I also would link to point out, the sparkle button for copilot is not actually disabled after commit; we can still over over it and cause accidental click on top of that as it's not in disabled state tabing to push now need an extra key press of tab as it focus over disabled sparkle button.

**Comment by lszomoru** [comment] 2024-02-22 15:05
> Currently it takes 2 "tabs" to get to the commit button, the first one goes to the sparkle icon if present from copilot. Is this the desired behavior?

Yes, this is the desired behaviour based on my understanding. @isidorn, @meganrogge please correct me if I am wrong.

**Comment by lszomoru** [comment] 2024-02-22 15:06
> I also would link to point out, the sparkle button for copilot is not actually disabled after commit; we can still over over it and cause accidental click on top of that as it's not in disabled state tabing to push now need an extra key press of tab as it focus over disabled sparkle button.

Could you please file a separate issue for this? Thank you!
