### ISSUE TITLE
Zooming the editor breaks webviews

### ISSUE THREAD

**Issue by edasaki** [Microsoft/vscode#24132] opened 2017-04-06 19:46 UTC
![example pic](http://i.imgur.com/BMXZzQh.png)

Steps to Reproduce:

1. Zoom in
2. Open up a webview

Zooming in the entire editor seems to mess up webviews. Other parts of VSCode scale properly, but a weird padding is added to the webview (or rather, the height and width properties are too small for the now-zoomed pane)

Changing the width and height of the webview (which are both manually styled in the HTML as 100%) to, for example, 120% if you've zoomed once, then it "fixes" it, but this has to be done manually for every webview which is obviously a big pain haha.

**Comment by mjbvz** [comment] 2017-04-06 19:51
Duplicate of #5745

**Closed by mjbvz** 2017-04-06 19:51 UTC
Labels: duplicate, webview
