### ISSUE TITLE
The terminal header cuts the top of the console

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#10076] opened 2016-08-03 12:06 UTC
- VSCode Version: 1.3.1
- OS Version: Fedora 24

Steps to Reproduce:

1. Use ZSH shell
2. Open a terminal by pressing " Ctrl + ` "

![screenshot from 2016-08-03 15-03-32](https://cloud.githubusercontent.com/assets/13297000/17364921/c9bac34a-598b-11e6-8214-9adfb927f827.png)

**Comment by Tyriar** [comment] 2016-08-03 21:52
This is a duplicate of https://github.com/Microsoft/vscode/issues/8219, it's because of the unicode characters being used. Fix coming soon in v1.4.0, available now in Insiders.

**Closed by Tyriar** 2016-08-03 21:52 UTC
