### ISSUE TITLE
Terminal focus issue

### ISSUE THREAD

**Issue by usmannajib** [Microsoft/vscode#44089] opened 2018-02-21 06:28 UTC
### Issue Type
Bug

### Description

1) Start VS Code
2) Press shortcut for opening terminal (ctrl + ~)
3) Focus is not set in the terminal
4) Close using shortcut (ctrl + ~) and open again with the same shortcut
5) Focus is now set

Details: only happens first time when VS code is started

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|Memory (System)|15.48GB (11.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.1.0

(2 theme extensions excluded)

</details>
Reproduces without extensions

**Comment by RMacfarlane** [comment] 2019-04-29 18:26
Sorry for the extreme delay in looking at this issue - for some reason this issue only just showed up now in our query for issues that need triaging.

Looks like this is a duplicate of https://github.com/Microsoft/vscode/issues/19400 and has already been fixed.

**Closed by RMacfarlane** 2019-04-29 18:26 UTC
