### ISSUE TITLE
Terminal: first line not fully visible

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34201] opened 2017-09-12 07:40 UTC
I am using zoom level of 1 and TMUX:

![image](https://user-images.githubusercontent.com/900690/30313658-66e94a3c-979e-11e7-9e59-070c7c31a48e.png)

I see the first line not fully revealed.

My config:

```json
{
    "editor.lineNumbers": "on",
    "window.zoomLevel": 1,
    "workbench.editor.showTabs": true,
    "workbench.editor.showIcons": true,
    "search.quickOpen.includeSymbols": false,
    "debug.inlineValues": true,
    "workbench.editor.enablePreview": false,
    "editor.codeLens": false,
    "workbench.statusBar.visible": true,
    "editor.dragAndDrop": true,
    "git.enableSmartCommit": true,
    "editor.renderIndentGuides": false,
    "editor.minimap.enabled": false,
    "workbench.tips.enabled": true,
    "workbench.commandPalette.preserveInput": true,
    "workbench.startupEditor": "newUntitledFile",
    "files.autoSave": "off",
    "files.autoSaveDelay": 1000,
    "files.trimTrailingWhitespace": true
}
```

**Comment by Tyriar** [comment] 2017-09-13 05:39
Duplicate of https://github.com/Microsoft/vscode/issues/34243, let me know if it still repros.

**Closed by Tyriar** 2017-09-13 05:39 UTC
