### ISSUE TITLE
Integrated Terminal is no longer themed to match the rest of Code

### ISSUE THREAD

**Issue by jordanmaslyn** [Microsoft/vscode#51774] opened 2018-06-13 15:17 UTC
- VSCode Version: 1.25.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Toggle Integrated Terminal to be visible

Does this issue occur when all extensions are disabled?: Yes

--------------------------------------------------------------

Using default theme, custom themes, using CMD or Powershell, I had the issue in each case where the integrated terminal was white text on black rather than matching the rest of the window.

![image](https://user-images.githubusercontent.com/1475091/41360667-4baeb8bc-6efb-11e8-9a1e-5aa844b21735.png)

**Comment by FadeZhanger** [comment] 2018-06-13 15:45
It also messes up the the text color:
![image](https://user-images.githubusercontent.com/30360288/41362147-a25632fa-6efe-11e8-968a-540e3677e9e1.png)
This seems to occur only when "terminal.integrated.rendererType" is set to "canvas"

**Comment by ShroomKing** [comment] 2018-06-13 17:07
Similar thing happens when using MSYS as integrated terminal: 
![unnamed](https://user-images.githubusercontent.com/26014865/41365755-87d13178-6f3a-11e8-99b6-b809107fa924.png)
The text colors are fine, but the background is pitch black.

* VSCode Version: 1.25.0-insider
* OS Version: Windows 7 64bit

As FadeZhanger already said:
> This seems to occur only when "terminal.integrated.rendererType" is set to "canvas"

**Comment by jordanmaslyn** [comment] 2018-06-13 17:42
Can confirm, the integrated terminal is fine when "dom" is chosen for "terminal.integrated.rendererType" but "canvas" and "auto" (assuming auto is resolving to canvas for me) both result in the discoloration issue.

**Comment by yume-chan** [comment] 2018-06-14 06:55
Duplicate of #51749

It's already been fixed in today's insiders version.

**Closed** 2018-06-14 07:10 UTC
Labels: *duplicate, integrated-terminal
