### ISSUE TITLE
vscode can't not open multi same folder instance. 

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#45455] opened 2018-03-10 02:53 UTC
vscode can't not open multi same folder instance. 

Previously, i submit a issue that can provide multi search view in vscode. when i want to compare different search result . but was told that use regex search instance .but it still not so convenient。

and then i want to open multi-instance of then same folder.. it seems just jump to the previous instance of this folder.

i know i can solve this problem by other way. such as use portable version ,or open an other parent level folder of the target folder i want to search.

i just want to say why make it more convenient...

no offense.

btw. the replace view is very beautiful.

**Comment by roblourens** [comment] 2018-03-12 05:08
This sounds like a duplicate of https://github.com/Microsoft/vscode/issues/16488, let me know if I misunderstood.

**Closed by roblourens** 2018-03-12 05:08 UTC
Labels: search
