### ISSUE TITLE
[css] prioritize CSS properties by usage/value

### ISSUE THREAD

**Issue by chrisfay** [microsoft/vscode#50240] opened 2018-05-21 20:50 UTC
Issue Type: <b>Bug</b>

e.g. when I type 'back' I get background-attachment as the first suggestion instead of background. Similarly if I type 'align' I get 'align-content' over the more used 'align-items'. Atom correctly prioritizes these properties and this is my biggest complaint after switching to VCS as I'm constantly inserting the wrong properties when writing css/sass.  

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3273503|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.2
jslint|ajh|1.2.1
vscode-eslint|dba|1.4.9
gitlens|eam|8.3.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.29
ecdc|mit|0.12.0
python|ms-|2018.4.0
debugger-for-chrome|msj|4.4.3
vscode-icons|rob|7.23.0
vscode-sass-format|sas|1.1.4
JavaScriptSnippets|xab|1.6.0

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment] 2018-05-29 08:47
@aeschli - given equal prefix-match-scores the logic falls back to the provider sort order.

**Comment by aeschli** [comment] 2019-10-09 14:32
duplicate of #3145

**Closed by aeschli** 2019-10-09 14:32 UTC
Labels: css-less-scss, feature-request
