### ISSUE TITLE
my f1 key does not work well and its shows an error when i write view in the browsers

### ISSUE THREAD

**Issue by oggyoggy448** [Microsoft/vscode#18703] opened 2017-01-18 04:39 UTC
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment] 2017-01-18 07:41
@oggyoggy448 can you please provide details about what is not working and how to reproduce the problem. A screen cast demonstrating the problem is also a help.

I will close the issue since in its current from there is nothing we can do to understand the problem.

**Closed by dbaeumer** 2017-01-18 07:41 UTC
Labels: needs more info
