### ISSUE TITLE
Disable space converstion to tabs

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#36632] opened 2017-10-20 11:20 UTC
Upon pressing enter, Visual Studio Code will convert `\t\t_____` to `\t\t\t_` (underscore means space) if your tab size is set to 4.  When I say "2 tabs and 5 spaces" I mean "2 tabs and 5 spaces" and I don't want VS Code replacing some of my spaces with tabs.  I am using tabs for indentation and spaces for alignment.  There should be an option to prevent VS Code from converting spaces to tabs when determining indentation upon pressing enter.

**Comment by rcjsuen** [comment] 2017-10-21 07:14
@jez9999 What kind of files are you editing? Regular text files? JavaScript files?

**Comment by jez9999** [comment] 2017-10-21 09:47
TypeScript files.

**Comment by mjbvz** [comment] 2017-10-23 20:38
@jez9999 Does this reproduce if you disable your installed extensions and restart VS Code?

**Comment by jez9999** [comment] 2017-10-23 21:03
Yes.

**Comment by mjbvz** [comment] 2017-10-23 22:03
Thanks. This looks language agnostic in my testing

Closing as a duplicate of #33407 which tracks the same issue

**Closed by mjbvz** 2017-10-23 22:03 UTC
Labels: duplicate, editor, editor-core
