### ISSUE TITLE
No (obvious?) way of turning off notifications (especially annoying since they keep reappearing on app refreshes)

### ISSUE THREAD

**Issue by Murtaya** [Microsoft/vscode#63460] opened 2018-11-20 00:12 UTC
Whenever I change the style, cause a reload, or hit Ctrl+'-' or Ctrl+'-' (trying to go back or forward in code like in regular VS, but in this one it zooms in or out...still trying to figure that out), I get notifications in the bottom right saying I'm not connected to something, or don't have something loaded, etc.  It would be nice to disable those so they don't get as obnoxious as they are now.  Little things like that make this IDE really annoying to use

**Comment by roblourens** [comment] 2018-11-20 01:18
>  I get notifications in the bottom right saying I'm not connected to something, or don't have something loaded, etc.

I don't know what notification you're talking about. Please include exact steps with enough info for me to reproduce the issue. It may be from an extension, check whether this happens when you start with `--disable-extensions`

**Comment by bpasero** [comment] 2018-11-20 06:17
@Murtaya the notification (when you expand it) should show a "Source" that hints to the extension, maybe you could attach a screenshot.

**Comment by usernamehw** [comment] 2018-11-20 14:45
Duplicate of #46676? 

Issue about recently added network error notification: #62824

**Comment by Murtaya** [comment] 2018-11-20 18:05
To repro, I can hit Ctrl + ‘-‘, and the messages come up.  Right now I’m prototyping in a test app so I really don’t care about what they have to say and would just like to kill them once and for all.

[cid:image003.png@01D480B8.93798720]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Murtaya** [comment] 2018-11-20 18:05
To repro, I can hit Ctrl + ‘-‘, and the messages come up.  Right now I’m prototyping in a test app so I really don’t care about what they have to say and would just like to kill them once and for all.

[cid:image003.png@01D480B8.992FEE20]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by roblourens** [comment] 2018-11-20 23:08
#46676 for disabling all notifications. I don't know what you're seeing, it's probably from an extension.

**Closed by roblourens** 2018-11-20 23:08 UTC
Labels: needs more info
