### ISSUE TITLE
Deleting virtual environment fails silently

### ISSUE THREAD

**Issue by burhan** [microsoft/vscode#103914] opened 2020-08-04 08:03 UTC
Issue Type: <b>Bug</b>

1. Activate a virtual environment `python -m venv venv` in a folder currently open.

2. Make sure VSCode is using the same environment.

3. The environment  folder will show up in the Explorer view.

4. Right click on that folder and select Delete (or click on it, and hit the Delete key on your keyboard). A popup opens for confirmation to move to the recycle bin. Confirm.

Result:

1. Folder disappears from the Explorer view in VS Code

Actual Result:

1. Folder remains on disk, because VS Code is still using it (remember, its still pointing to the now deleted environment).

If you try to delete the folder from the Windows Explorer (`explorer.exe`), you will get an error that the file is open in a program, which is correct as its being used by VSCode.

Expected Result:

I am not sure what to expect, but either:

1. Warning that you are deleting the current environment, and on confirmation, let VSCode use the default Python environment; but this seems like a very difficult thing to implement correctly. Especially if users are running from WSL2. However, if this can be done, then the folder can be deleted correctly.

Some issues I see with this that this could still fail if there is some process using the directory (something as simple as its open in a Terminal window will cause this to fail).

2. Offer the same Explorer-like warning, that the directory cannot be deleted because it is currently in use (could be enhanced to say its currently being used by VSCode as an environment).

However, it shouldn't disappear from the Explorer view.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|10%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sql-formatter|adp|1.4.4
swagger-viewer|Arj|3.0.1
azds|azu|2.0.220200723
better-toml|bun|0.3.2
vscode-postgres|cko|1.1.11
bracket-pair-colorizer|Coe|1.0.61
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.13.1
flutter|Dar|3.13.1
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
azure-storage-explorer|for|0.1.2
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.18.0
go|gol|0.16.0
cloudcode|goo|1.4.1
gc-excelviewer|Gra|3.0.39
terraform|has|2.1.1
output-colorizer|IBM|0.1.2
vscode-gist|ken|3.0.3
Lua|key|0.0.9
restructuredtext|lex|129.0.0
rainbow-csv|mec|1.7.0
dotenv|mik|1.0.1
file-downloader|min|1.0.0
mindaro|min|0.1.120200723
terraform-snippets|min|2.1.0
vscode-apache|mrm|1.2.0
vscode-azureappservice|ms-|0.18.0
vscode-cosmosdb|ms-|0.14.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
vscode-aks-tools|ms-|0.0.6
vscode-kubernetes-tools|ms-|1.2.1
vscode-postgresql|ms-|0.3.0
python|ms-|2020.7.96456
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2020.7.3117
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
sqltools|mtx|0.22.11
sqltools-driver-pg|mtx|0.1.0
vetur|oct|0.25.0
vscode-vault|owe|2.2.0
material-icon-theme|PKi|4.2.0
java|red|0.65.0
vscode-yaml|red|0.9.1
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|1.17.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
vscode-icons|vsc|10.2.0
vscode-ansible|vsc|0.5.2
HCL|who|0.0.5

</details>

**Comment by isidorn** [comment] 2020-08-04 08:19
Yes, we should handle the delete that failed better. Closing as a duplicate of https://github.com/microsoft/vscode/issues/43819

**Closed by isidorn** 2020-08-04 08:19 UTC
