### ISSUE TITLE
Multi select context menu should have only common actions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#42574] opened 2018-01-30 23:30 UTC
Testing #41473

- Multi select a few files (one of them being a markdown file)
- Right click on the markdown file to bring up the context menu. There is an menu item for `Open Preview`

The `Open Preview` menu item is specific to markdown files. Its confusing that it appears in the context where it doesnt apply to the other files

**Comment by ramya-rao-a** [comment] 2018-01-30 23:40
Same can be said of the folder related actions showing up when multi selecting a mix of folder and files

**Comment by ramya-rao-a** [comment] 2018-01-31 00:21
Same applies to menu options contributed by extensions. The `when` clause of the menu item should be satisfied by all the multi selected items for the command to show up in the context menu

**Comment by isidorn** [comment] 2018-01-31 12:21
@ramya-rao-a thank you for this suggestion. However in the design process and in the standup discussions of this feature we have decided otherwise.
More about this decisions can be found here https://github.com/Microsoft/vscode/pull/41461
Due to that closing this as designed

**Closed by isidorn** 2018-01-31 12:21 UTC

**Comment by ramya-rao-a** [comment] 2018-01-31 16:52
@isidorn #41461 covered the decision for commands from extensions keeping backward compatibility in mind. But what about commands from the core like `New File`, `New Folder` that applies only to folders?

**Comment by isidorn** [comment] 2018-02-01 14:46
@ramya-rao-a there are commands which only work on a single context, like the rename and the ones you mentioned. For those we choose to behave like Windows Explorer and Sublime, the explorer most of our users are acustomted to and one of the most popular text editors. That is we only execute those commands on the resources the user has exactly cliked on (even if there might be multtiple items selected).

**Comment by ramya-rao-a** [comment] 2018-02-01 18:07
fair enough
thanks for the clarification

**Comment by isidorn** [comment] 2018-02-02 08:28
@ramya-rao-a you are welcome
