### ISSUE TITLE
Updating a keyboard shortcut requires a restart for the visual confirmation on macOS

### ISSUE THREAD

**Issue by revolter** [microsoft/vscode#118134] opened 2021-03-04 20:35 UTC
Issue Type: <b>Bug</b>

- Open the Keyboard Shortcuts preferences view
- Change the shortcut for a command

The new keybinding doesn't appear in the `Keybinding` column, nor in the app's menu bar. You also can't reset it, because the context menu also thinks that no keybinding was added, so the respective menu is greyed out.

VS Code version: Code 1.54.0 (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-03T02:17:59.499Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 155b0ce3-be01-4055-936a-2d654c76ce4e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.5.9
vscode-eslint|dba|2.1.14
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.163.0
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
vetur|oct|0.33.0
platformio-ide|pla|2.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by revolter** [comment] 2021-03-04 20:38
This happens when removing or resetting a keybinding too.

**Comment by revolter** [comment] 2021-03-04 20:42
Actually, the shortcut itself doesn't work either without a restart.

**Comment by masaki9** [comment] 2021-03-04 21:16
FYI, I am running macOS 11.2.2, and key bindings can be updated without a restart as expected in v1.54.0.

![image](https://user-images.githubusercontent.com/40445257/110030932-28e22480-7ceb-11eb-863c-f8393195669c.png)
![image](https://user-images.githubusercontent.com/40445257/110031223-7ced0900-7ceb-11eb-8e85-bf97e46bbf59.png)
![image](https://user-images.githubusercontent.com/40445257/110031284-91c99c80-7ceb-11eb-8206-be69d804682c.png)

**Comment by sandy081** [comment] 2021-03-05 14:53
@revolter Can you please open the underlying keybindings.json file and check if the update is writing into that file? Also try to update that file and test?

**Comment by revolter** [comment] 2021-03-05 14:58
> Can you please open the underlying keybindings.json file and check if the update is writing into that file?

Yes, it does. And simply saving it, without even changing anything, causes the regular view to update with the previously entered keybinding.

> Also try to update that file and test?

So yes, this works.

**Comment by sandy081** [comment] 2021-03-05 15:11
Is there anything special with your keybindings.json file? Is it on a mapped network drive ?

**Comment by revolter** [comment] 2021-03-05 15:43
Know, I didn't even know it exists (I just recently started using Visual Studio Code). Here it is:

```json
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+tab",
        "command": "-workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "-workbench.action.quickOpenLeastRecentlyUsedEditorInGroup"
    },
    {
        "key": "ctrl+tab",
        "command": "workbench.action.nextEditor"
    },
    {
        "key": "alt+cmd+right",
        "command": "-workbench.action.nextEditor"
    },
    {
        "key": "shift+cmd+]",
        "command": "-workbench.action.nextEditor"
    },
    {
        "key": "shift+cmd+[",
        "command": "-workbench.action.previousEditor"
    },
    {
        "key": "alt+cmd+left",
        "command": "-workbench.action.previousEditor"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "workbench.action.previousEditor"
    },
    {
        "key": "f5",
        "command": "-workbench.action.debug.continue",
        "when": "inDebugMode"
    },
    {
        "key": "f5",
        "command": "-workbench.action.debug.start",
        "when": "debuggersAvailable && debugState != 'initializing'"
    },
    {
        "key": "f5",
        "command": "workbench.action.debug.stepOver",
        "when": "debugState == 'stopped'"
    },
    {
        "key": "f10",
        "command": "-workbench.action.debug.stepOver",
        "when": "debugState == 'stopped'"
    },
    {
        "key": "f6",
        "command": "-workbench.action.debug.pause",
        "when": "debugState == 'running'"
    },
    {
        "key": "f6",
        "command": "-workbench.action.focusNextPart"
    },
    {
        "key": "f6",
        "command": "workbench.action.debug.stepInto",
        "when": "debugState != 'inactive'"
    },
    {
        "key": "f11",
        "command": "-workbench.action.debug.stepInto",
        "when": "debugState != 'inactive'"
    },
    {
        "key": "cmd+r",
        "command": "-workbench.action.reloadWindow",
        "when": "isDevelopment"
    },
    {
        "key": "ctrl+cmd+r",
        "command": "workbench.action.debug.run",
        "when": "debuggersAvailable && debugState != 'initializing'"
    },
    {
        "key": "ctrl+f5",
        "command": "-workbench.action.debug.run",
        "when": "debuggersAvailable && debugState != 'initializing'"
    },
    {
        "key": "cmd+r",
        "command": "workbench.action.debug.start"
    }
]
```

**Comment by sandy081** [comment] 2021-03-08 15:51
Can you please enable log level to trace `F1 > Set Log Level > Trace` and retry changing the keybinding from the UI. After that please provide us the window logs available through `F1 > Open View > Log (Window)`

**Comment by sandy081** [comment] 2021-03-11 13:22
@revolter Thanks this correct. I do not see a file change events here.

Can you please record the logs similarly when changing the keybinding by opening the file in the editor?

**Comment by revolter** [comment] 2021-03-12 08:45
I also switched to the regular Keyboard Shortcuts tab at the end:

```
[2021-03-12 10:43:48.729] [renderer1] [trace] MainThreadTreeViews#$refresh liveshare.contacts undefined
[2021-03-12 10:43:48.856] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2021-03-12 10:43:48.934] [renderer1] [trace] MainThreadTreeViews#$refresh liveshare.contacts undefined
[2021-03-12 10:43:49.658] [renderer1] [trace] KeybindingService#dispatch ⌘V editor.action.clipboardPasteAction
[2021-03-12 10:43:49.658] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardPasteAction
[2021-03-12 10:43:49.667] [renderer1] [trace] CommandService#executeCommand paste
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - new versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - model content changed and marked as dirty vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.673] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.675] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.675] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.994] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2021-03-12 10:43:50.558] [renderer1] [trace] KeybindingService#dispatch ⌘S workbench.action.files.save
[2021-03-12 10:43:50.558] [renderer1] [trace] CommandService#executeCommand workbench.action.files.save
[2021-03-12 10:43:50.558] [renderer1] [trace] [text file model] save() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] doSave(1) - enter with versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] doSave(1) - before write() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] handleSaveSuccess(1) - setting dirty to false because versionId did not change vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [backup tracker] discarding backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:50.560] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:50.561] [renderer1] [trace] [text file model] save() - exit vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.730] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.731] [renderer1] [debug] User data changed
[2021-03-12 10:43:50.731] [renderer1] [debug] Keybindings file changed
[2021-03-12 10:43:50.731] [renderer1] [trace] [text file model] load() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.731] [renderer1] [trace] [text file model] loadFromFile() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.783] [renderer1] [debug] User keybindings changed
[2021-03-12 10:43:51.761] [renderer1] [trace] KeybindingService#dispatch ⌃⇧Tab workbench.action.previousEditor
[2021-03-12 10:43:51.761] [renderer1] [trace] CommandService#executeCommand workbench.action.previousEditor
[2021-03-12 10:43:53.200] [renderer1] [trace] KeybindingService#dispatch ⇧⌘P workbench.action.showCommands
[2021-03-12 10:43:53.201] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2021-03-12 10:43:54.061] [renderer1] [trace] CommandService#executeCommand workbench.action.setLogLevel
```

**Comment by revolter** [comment] 2021-03-12 08:47
Waaait, I think I know why. I'm using [mackup](https://github.com/lra/mackup), so that file is a symlink:

```
Permissions Size User   Group Date Modified    Name
drwxr-xr-x     - revolt staff 2021-03-12 10:44 globalStorage/
drwxr-xr-x     - revolt staff 2021-02-06 16:39 sync/
drwxr-xr-x     - revolt staff 2021-02-25 00:42 workspaceStorage/
lrwxr-xr-x    83 revolt staff 2021-02-13 13:57 keybindings.json -> /Users/revolt/Dropbox/Mackup/Library/Application Support/Code/User/keybindings.json
lrwxr-xr-x    80 revolt staff 2019-07-03 20:33 settings.json -> /Users/revolt/Dropbox/Mackup/Library/Application Support/Code/User/settings.json
lrwxr-xr-x    75 revolt staff 2019-07-03 20:33 snippets -> /Users/revolt/Dropbox/Mackup/Library/Application Support/Code/User/snippets
```

**Comment by sandy081** [comment] 2021-03-16 18:21
@bpasero Please check below logs

## Changing from Keyboard Shortcuts UI

```
[2021-03-08 20:57:33.259] [renderer1] [trace] [text file model] load() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.259] [renderer1] [trace] [text file model] loadFromFile() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.266] [renderer1] [trace] [text file model] loadFromContent() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.266] [renderer1] [trace] [text file model] doCreateTextModel() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.281] [renderer1] [trace] [text file model] onModelContentChanged() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.281] [renderer1] [trace] [text file model] onModelContentChanged() - new versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.281] [renderer1] [trace] [text file model] onModelContentChanged() - model content changed and marked as dirty vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.282] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-08 20:57:33.286] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-08 20:57:33.287] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-08 20:57:33.288] [renderer1] [trace] [text file model] save() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.289] [renderer1] [trace] [text file model] doSave(1) - enter with versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.291] [renderer1] [trace] [text file model] doSave(1) - before write() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.321] [renderer1] [trace] [text file model] handleSaveSuccess(1) - setting dirty to false because versionId did not change vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.321] [renderer1] [trace] [backup tracker] discarding backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-08 20:57:33.321] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-08 20:57:33.323] [renderer1] [trace] [text file model] save() - exit vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-08 20:57:33.324] [renderer1] [trace] [text file model] dispose() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
```

- Here keybindings editor UI writes into the file underneath. Check that there are no file change events triggered.


## Changing `keybindings.josn` file directly

```
[2021-03-12 10:43:49.658] [renderer1] [trace] CommandService#executeCommand editor.action.clipboardPasteAction
[2021-03-12 10:43:49.667] [renderer1] [trace] CommandService#executeCommand paste
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - new versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.672] [renderer1] [trace] [text file model] onModelContentChanged() - model content changed and marked as dirty vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:49.673] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.675] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.675] [renderer1] [trace] [backup tracker] scheduling backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:49.994] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2021-03-12 10:43:50.558] [renderer1] [trace] KeybindingService#dispatch ⌘S workbench.action.files.save
[2021-03-12 10:43:50.558] [renderer1] [trace] CommandService#executeCommand workbench.action.files.save
[2021-03-12 10:43:50.558] [renderer1] [trace] [text file model] save() - enter vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] doSave(1) - enter with versionId 1 vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] doSave(1) - before write() vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [text file model] handleSaveSuccess(1) - setting dirty to false because versionId did not change vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [backup tracker] discarding backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:50.560] [renderer1] [trace] [backup tracker] clearing pending backup vscode-userdata:/Users/revolt/Library/Application%20Support/Code/User/keybindings.json
[2021-03-12 10:43:50.561] [renderer1] [trace] [text file model] save() - exit vscode-userdata:/Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.730] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.731] [renderer1] [debug] User data changed
[2021-03-12 10:43:50.731] [renderer1] [debug] Keybindings file changed
```

- When changed by opening the file (with `vscode-userdata` scheme) directly, change events from file watcher are shown. 

May I know if there is anything special in second approach of writing into the file that it triggers the change events?

**Comment by bpasero** [comment] 2021-03-17 06:00
@sandy081 the keybindings editor is using `ITextFileService` for writing or `IFileService` or `IJSONEditingService`?

Anyhow, since file watchers are really just observing files for changes, it shouldn't matter how the file is changed as long as the contents are written into the file. So I would not expect any difference depending on what editor you are using.

The file watcher here seems to be one for out of workspace files (node.js), likely because the file is inside the settings dir. Where is the watcher setup? Does this reproduce always?

**Comment by sandy081** [comment] 2021-03-17 08:51
@bpasero Yes, I can reproduce it locally. Here are steps:

- Symlink your keybindings.json to a file at some other location
- Open VS Code and change keybindings

🐛  Keybindings are not updated.

It seems the file service is not triggering the change event. Here is the code how I watch the file 

https://github.com/microsoft/vscode/blob/3022afaeaa291fec298ffa86cefff6893ddb192c/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L679-L689

**Comment by bpasero** [comment] 2021-03-17 10:14
Possible that we do not support symlinks for file watching, but if you can do some `console.log` in `src/vs/platform/files/node/watcher/nodejs/watcherService.ts#startWatching()` you should be able to see if the watcher is hit.

**Comment by sandy081** [comment] 2021-03-17 15:34
> Possible that we do not support symlinks for file watching

```
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
[2021-03-12 10:43:50.559] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /Users/revolt/Library/Application Support/Code/User/keybindings.json
```

But there are file change events when updating the file from editor ?

**Comment by bpasero** [comment] 2021-03-17 16:15
@sandy081 the automated watching for changes is something that needs a `resource` on the editor input:

![image](https://user-images.githubusercontent.com/900690/111500340-2c8e9600-8744-11eb-92db-c81572392af9.png)

Looks like the keybindings editor does not provide any resource, so the file is not automatically watched in here:

https://github.com/microsoft/vscode/blob/c72d7612b412031d8b6003acac58a0554ea1ca09/src/vs/workbench/services/editor/browser/editorService.ts#L185-L216

I would actually argue that the keybindings editor should setup the file watching itself if possible because it expresses an interest to handle file changes.

**Comment by sandy081** [comment] 2021-03-19 11:28
@bpasero 

- `KeybindingsEditor` listens on keybindings model changes and updates the UI. 

https://github.com/microsoft/vscode/blob/d4b5298cd6236407bb25a3c73dc569292309438d/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts#L122-L122

- Keybindings model listen to `keybindings.json` file changes and updates the model

https://github.com/microsoft/vscode/blob/3022afaeaa291fec298ffa86cefff6893ddb192c/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L679-L689

It is similar to settings editor, not sure if it is right approach that these virtual editors listen on underlying file given that they are built on top of other models. 

So the root cause here is that keybindings model listener is not getting called when the file changed - Please see that the model is watching the folder and I think any changes to the immediate children of the folder shall be triggered. Let me know if I am doing anything wrong here.

**Comment by bpasero** [comment] 2021-03-19 12:29
@sandy081 got it, I think the underlying issue really is the fact that you watch on `dirname(keybindingsResource))` which will not support symbolic links and in the other case we explicitly watch on the file itself, which does support symlinks.

If possible, can you just watch on the actual resources instead? Or is that not possible because the file might not exist?

**Comment by sandy081** [comment] 2021-03-19 14:00
> Or is that not possible because the file might not exist?

Yes. I have to manage when file does not exist and also when file is deleted. File service handles it nicely now.

**Comment by bpasero** [comment] 2021-03-19 14:25
I think this is stretch, if someone wants to create symlinks for files inside our own user data dir, then some things might not work. I would close as wontfix.

**Comment by sandy081** [comment] 2021-03-22 21:45
I see it is not trivial for the watcher, but since it used to work before - I was watching the file and dir both to cover all cases. I would probably do the same now.

**Comment by sandy081** [comment] 2021-03-25 09:23
I also now watch the resource in addition to watching the dir.

**Closed** 2021-03-25 09:23 UTC
Labels: bug, keybindings-editor
