### ISSUE TITLE
Syntax highlighting is broken for JS

### ISSUE THREAD

**Issue by Eurkidu** [Microsoft/vscode#56522] opened 2018-08-16 02:28 UTC
- VSCode Version: Code 1.26.0 (4e93618, 2018-08-13T16:20:44.170Z)
- OS Version: macos high sierra 10.13.6

![default](https://user-images.githubusercontent.com/13271070/44183776-e82b5b80-a13e-11e8-8889-c8b09ccde6c2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment] 2018-08-20 10:18
Please share the text of the code along with screenshots

**Comment by SpaceOtterInSpace** [comment] 2018-08-21 17:09
Also having a syntax highlighting issue. 
![screen shot 2018-08-21 at 11 09 14 am](https://user-images.githubusercontent.com/6878194/44417416-b3e6df00-a532-11e8-99b4-f829ac84103e.png)

**Comment by SpaceOtterInSpace** [comment] 2018-08-21 17:16
```import _ from "lodash";
import { Content as ModalContent } from "../../../../_js/001-app/000-modal";
import FormForm from "../../../../_js/001-app/000-form/000-form";
import DI from "../../../../_js/000-core/001-bottle";
import InputReactSelect from "../../../../_js/001-app/000-input/002-reactSelectNew";
import InputRadioGroup from "../../../../_js/001-app/000-input/001-radioGroup";
import InputBoolean from "../../../../_js/001-app/000-input/001-boolean";
import InputHidden from "../../../../_js/001-app/000-input/001-hidden";
import FormPartial from "../../../../_js/001-app/000-form/000-partial";
import { EditFieldModalFields } from "../../../_js/002-modal/011-fieldAdmin";
import InputText from "../../../../_js/001-app/000-input/001-text";
import FormGroup from "../../../../_js/001-app/000-form/000-group";
class FieldManagerFieldModals extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            field_type:     props.field_type,
            component_type: props.component_type,
            id:             props.id
        };

        this.toggleContextSearch = this.toggleContextSearch.bind(this);
        this.updateComponentType = this.updateComponentType.bind(this);

    }

    getDatabaseColumnField() {
        return (
            <FormGroup
                label="Database Column Name"
                note="The database column name must be 60 characters or less and must be unique.
                If you leave this field blank then the column name will be created based on the field label below
                with capitalization removed and spaces replaced with underscores. To avoid validation errors make
                sure the field label is also unique.">
                <InputText
                    name = "name"
                    disabled = {this.props.editing}
                    attrs = {{
                        placeholder: "Leave blank for system generated column name (recommended)",
                        'maxLength': 60
                    }}
                />
            </FormGroup>
        );
    }

    getBaseFields() {
        return EditFieldModalFields();
    }

    /**
     * Handle a change in the field's value
     */
    toggleContextSearch() {
        const context_search = _.get(this.state, 'context_search', false);
        this.setState({
            context_search: !context_search
        });

        if (context_search) {
            let context_filter = this.refs.form.refs.modal_content.refs.partial.refs.contextfilter.refs.context_filter;
            context_filter.setValue(context_filter.props.default_value);
        }
    }

    /**
     * Get Base Fields for Modal
     *
     * This function returns the fields for the modal, rendering
     * some fields as readonly, etc, based on whether or not we're
     * editing vs adding a new field.
     *
     * @returns {XML}
     */
    getFieldManagerFields() {
        const context_filter_disabled = !_.get(this.state, 'context_search');

        const base_fields = (
            <FormPartial
                ref='partial'>
                <InputHidden name="field_config_id"/>

                <FormGroup
                    label="Must Include"
                    note="Field must be included in all form sets">
                    <InputBoolean
                        name="must_include"
                        default_value={false}
                        input_config={{
                            input_type: 'radio',
                            true_label: 'Yes',
                            false_label: 'No'
                        }}/>
                </FormGroup>

                <FormGroup
                    label="Context - Search"
                    note="Can this field be placed on search forms?">
                    <InputBoolean
                        name="context_search"
                        default_value={false}
                        disabled={this.props.editing}
                        events={{
                            onChange: this.toggleContextSearch
                        }}
                        input_config={{
                            input_type: 'radio',
                            true_label: 'Yes',
                            false_label: 'No'
                        }}/>
                </FormGroup>

                <FormGroup
                    label="Context - Entry"
                    note="Can this field be placed on intake forms?">
                    <InputBoolean
                        name="context_entry"
                        default_value={true}
                        disabled={this.props.editing}
                        input_config={{
                            input_type: 'radio',
                            true_label: 'Yes',
                            false_label: 'No'
                        }}/>
                </FormGroup>

                <FormGroup
                    ref="contextfilter"
                    label="Context - Filter"
                    note="Can this field be used for filtering data? (Context - Search must be set to Yes)">
                    <InputBoolean
                        name="context_filter"
                        default_value={false}
                        disabled={context_filter_disabled}
                        input_config={{
                            input_type: 'radio',
                            true_label: 'Yes',
                            false_label: 'No'
                        }}/>
                </FormGroup>

                {
                    // If you're not root then you pick the dataset
                    // Otherwise, use the dataset from the database table name you're on
                    (this.props.root) ?
                        (
                            <FormPartial>
                                <InputHidden
                                    name="dataset_id"
                                    value={this.props.active_dataset.id}/>
                                <p><strong>Dataset</strong> {this.props.active_dataset.label}</p>
                            </FormPartial>
                        ) : (
                        <InputHidden name="dataset_id"/>
                    )
                }

                {
                    // If you're not root then you pick the fieldset
                    // Otherwise, use the dataset from the database table name you're on
                    (this.props.root) ?
                        (
                            <FormPartial>
                                <InputHidden
                                    name="fieldset_id"
                                    value={this.props.active_fieldset.id}/>
                                <p><strong>Fieldset</strong> {this.props.active_fieldset.label}</p>
                            </FormPartial>
                        ) : (
                        <InputHidden
                            name="fieldset_id"
                            value={this.props.active_fieldset.id}/>
                    )
                }

                {
                    // If you're not root then you pick the fieldset
                    // Otherwise, use the dataset from the database table name you're on
                    (this.props.root) ?
                        (
                            <FormGroup label="VisionLink Only">
                                <InputRadioGroup
                                    name="root_only"
                                    default_value="false"
                                    input_config={{
                                        options: [
                                            {
                                                value: 'true',
                                                label: 'Yes'
                                            },
                                            {
                                                value: 'false',
                                                label: 'No'
                                            }
                                        ]
                                    }}
                                />
                            </FormGroup>
                        ) : null
                }

                <FormGroup
                    label="Field Type"
                    note="Choose a field type most consistent with the type of data you wish to collect">
                    <InputReactSelect
                        name="field_class_id"
                        disabled={this.props.editing}
                        input_required={true}
                        events={{
                            onChange: this.updateComponentType
                        }}
                        input_config={{
                            options: this.state.fieldtypes,
                            clearable: false
                        }}/>
                </FormGroup>

                <FormGroup
                    label="Add Minimum Age?"
                    note="">
                    <InputBoolean
                        name="has_minimum_age"
                        default_value={false}
                        disabled={this.props.editing}
                        input_config={{
                            input_type: 'radio',
                            true_label: 'Yes',
                            false_label: 'No'
                        }}/>
                </FormGroup>

                <FormGroup
                    label="Minimum Age"
                    note="Enter a number in years">
                    <InputText
                        name = "minimum_age"
                        disabled = {this.props.editing}
                        attrs = {{
                            'maxLength': 3
                        }}
                    />
                </FormGroup>

                {
                    // root users can make any field impotent so that it's not saved to the database
                    // this type of field could be used for triggering other fields
                    (this.props.root) ? (
                        <FormGroup
                            label="Make Field Impotent"
                            note="This field should not save to the database">
                            <InputBoolean
                                name="impotent"
                                default_value={false}
                                disabled={this.props.editing}
                                input_config={{
                                    input_type: 'radio',
                                    true_label: 'Yes',
                                    false_label: 'No'
                                }}/>
                        </FormGroup>
                    ) : null

                }

            </FormPartial>
        );

        return base_fields;
    }

    getSnapshotOptions() {
        const radio_options = {
            options: [
                {
                    value: 'true',
                    label: 'Yes'
                },
                {
                    value: 'false',
                    label: 'No'
                }
            ]
        };
        if (this.props.active_fieldset.snapshot) {
            return (
                <FormPartial>
                    <FormGroup label="`Snapshot is Editable` is configurable in Formbuilder"
                                    note={'This setting allows the `Snapshot is Editable` field setting to be configured on a Formbuilder Formset'}>
                        <InputRadioGroup
                            name="options[is_editable_snapshot]"
                            default_value={false}
                            input_config={radio_options}/>
                    </FormGroup>
                    <FormGroup label="`Snapshot is Editable` Default"
                                    note={'This setting defines a default value for the `Snapshot is Editable` field setting'}>
                        <InputRadioGroup
                            name="options[is_editable_snapshot_default]"
                            default_value={false}
                            input_config={radio_options}/>
                    </FormGroup>
                </FormPartial>
            );
        }
        return null;
    }

    getInputConfigFields(component_type, id) {
        if (!_.isUndefined(this.state.component_type)) {
            const is_field_manager = true;
            const fco = _.get(DI.container, 'getFieldConfigOptions.' + component_type);
            return _.isFunction(fco)
                ? fco(
                    _.extend({}, this.props, this.state.field_type, { options: this.state.options }),
                    this.props.is_new_field,
                    is_field_manager
                )
                : null;
        }
    }

    updateComponentType(id, type) {
        if (!_.isUndefined(type) && !_.isEmpty(type)) {
            this.setState({
                field_type: type[0],
                component_type: type[0].component_type
            });
        }
    }

    setStoredValues(values) {
        this.setState(values, function () {
            this.refs['form'].setStoredValues(values);
            this.filterFieldClass();
        }.bind(this));
    }

    filterFieldClass() {
        _.each(this.state.fieldtypes, function (fieldtype) {
            if (fieldtype.value === this.state.field_class_id) {
                this.setState({
                    field_type: fieldtype,
                    component_type: fieldtype.component_type
                });
            }
        }.bind(this))
    }

    componentWillMount() {
        const url = '/formbuilder/fieldconfig/getfieldclasses' + (!_.isUndefined(this.props.active_dataset) ? '/dataset_id/' + this.props.active_dataset.id : '') + (!_.isUndefined(this.props.active_fieldset) ? '/fieldset_id/' + this.props.active_fieldset.id : '');
        $.ajax({
            url: url,
            dataType: 'json',
            success: function (results) {
                this.setState({
                    fieldtypes: results.data.field_classes
                })
            }.bind(this)
        });
    }

    render() {
        let export_button = null;
        if (this.props.root && _.get(this.props, 'id')) {
            export_button = (
                <p><a
                    href={"/formbuilder/fieldconfig/export/id/" + this.props.id}
                    className="btn btn-default">Export</a></p>
            )
        }

        return (
            <FormForm
                ref           = "form"
                action        = "/formbuilder/fieldconfig/save"
                handleSuccess = {this.props.add_field_success}
                handleInvalid={
                    function(result){
                        if (result.result === 'invalid') {
                            DI.container.notification_warning("Please address validation errors.");
                        }
                    }
                }>
                <ModalContent title={this.props.title} ref="modal_content">
                    {this.getDatabaseColumnField()}
                    {this.getBaseFields()}
                    {this.getSnapshotOptions()}
                    {this.getFieldManagerFields()}
                    {this.getInputConfigFields(this.state.component_type, this.state.field_config_id)}
                    {export_button}
                </ModalContent>
            </FormForm>
        );
    }
}

export default FieldManagerFieldModals;```

**Comment by Eurkidu** [comment] 2018-08-23 02:37
This is the code text @mjbvz 
```js
// broken
let xhr = $.ajaxSettings.xhr() // test
if (typeof xhrOnProgress.onprogress !== 'function') return xhr

// broken
var a = 1 // test
if (a === 1 || a === 3) {
}

// ok
let xhr = $.ajaxSettings.xhr() // test

if (typeof xhrOnProgress.onprogress !== 'function') return xhr
// ok or
let xhr = $.ajaxSettings.xhr()
if (typeof xhrOnProgress.onprogress !== 'function') return xhr
```

**Comment by mjbvz** [comment] 2018-08-23 08:34
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/646

Should be fixed in next insiders build

**Closed by mjbvz** 2018-08-23 08:34 UTC
Labels: needs more info

**Comment by pqvst** [comment] 2018-08-23 09:58
I also noticed that extra spaces before the newline of a multi-line statement also causes issues. Is this related?

<img width="244" alt="screenshot 2018-08-23 11 47 51" src="https://user-images.githubusercontent.com/4990657/44518925-e1b35b80-a6cb-11e8-9152-320da7981691.png">
