### ISSUE TITLE
Error: user denied permission to use Service Worker

### ISSUE THREAD

**Issue by FuzzyPhilip** [microsoft/vscode#176265] opened 2023-03-06 16:15 UTC
Hi, on starting up a new GitHub CodeSpace I wasn't asked for any permissions, and yet I got this error on loading the CodeSpace:

> Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope ('https://16tql5litpt3l8qs44akjh1nebhrkui8dbdkd7klqetftkjb83n7.vscode-cdn.net/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://16tql5litpt3l8qs44akjh1nebhrkui8dbdkd7klqetftkjb83n7.vscode-cdn.net/stable/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority=codespaces+fuzzyphilip-stunning-goldfish-rwwwj4w977g2xv59'): The user denied permission to use Service Worker..

How do I grant this permission?

TIA!

Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment] 2023-03-06 16:52
What browser are you using? Are you using private mode?

**Comment by FuzzyPhilip** [comment] 2023-03-07 19:56
Thanks for the quick response @mjbvz , and sorry for not providing these obvious details.

I'm on Chrome (110.0.5481.177, 2023-02-23), using normal browsing mode. I'll try private more and report back when I'm back at my desk.

**Comment by FuzzyPhilip** [comment] 2023-03-07 19:57
P.S. Windows 10, fully updated.

**Comment by FuzzyPhilip** [comment] 2023-03-09 14:43
I've just tried private (Incognito on Chrome) and it's the same. However, on Edge (110.0.1587.56 (Official build) (64-bit)), it loads just fine. The only difference appears to be the initial display of the README.md for the project being opened - in Chrome it's blank (with the above error), but in Edge it comes up OK.

**Comment by mjbvz** [comment] 2023-03-14 20:32
Likely duplicate of #176218. Please make sure third party cookies are enabled and that content blockers are not enabled on the site

**Closed by mjbvz** 2023-03-14 20:32 UTC
Labels: info-needed
