### ISSUE TITLE
Web: missing built-in gramamars and themes extensions 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114414] opened 2021-01-15 13:09 UTC
When I open https://vscode-web-test-playground.azurewebsites.net/?enter=true on my native Apple SI machine, I see no colors in the editor:

![image](https://user-images.githubusercontent.com/900690/104730962-44916b80-573b-11eb-9c57-4c645eea258b.png)

Unfortunately I am not seeing any error in devtools. I wonder if this could be a WASM problem in the browser I use (Chrome, Edge).

This could be upstream, but I thought I would report it anyway.

**Comment by bpasero** [comment] 2021-01-15 13:10
Interestingly the scopes seem to be there though:

![image](https://user-images.githubusercontent.com/900690/104731058-730f4680-573b-11eb-9ca3-855c15ca425b.png)

**Comment by alexdima** [comment] 2021-01-15 21:22
@bpasero Maybe we can do some screen sharing to investigate. Are there any errors in the console? Are there `<span>`s with `mtk` colors in the DOM? Are you using a custom font family?

**Comment by bpasero** [comment] 2021-01-16 07:17
This is so bizarre, once I switched to stable it started to work again, even in insiders. But I can still reproduce from an incognito session. 

No errors in the console as far as I can tell. Settings are all empty due to incoginto.

DOM nodes when it does not work (Python file):

![image](https://user-images.githubusercontent.com/900690/104805838-368f2980-57d3-11eb-8eee-8f0fc0404df4.png)

And when it works:

![image](https://user-images.githubusercontent.com/900690/104805843-427aeb80-57d3-11eb-8e5a-79a3da98ba6f.png)

**Comment by alexdima** [comment] 2021-01-18 09:49
cc @aeschli this might be themeing related.

@bpasero How does the minimap look like? So if stable works it means it is not a native Apple SI specific problem? Or can you consistently reproduce on the native Apple SI machine and not on a regular machine? It is possible that the native Apple SI machine has different timing characterstics which might expose a timing bug, but otherwise I would expect for things to always fail or to always work.

Can you repro from sources?

**Comment by bpasero** [comment] 2021-01-18 09:52
Oh, I can reproduce on my intel based MBP running Big Sur as well, so it indeed seems Si unrelated. 

Here is a screenshot including minimap which is also not colored it seems:

![image](https://user-images.githubusercontent.com/900690/104899470-2f0a8480-597b-11eb-91a9-32ed4cf2673c.png)

**Comment by bpasero** [comment] 2021-01-18 09:53
Here with this machine I actually reproduce this even after trying out stable once and going back to insiders (stable works fine). This is using Edge.

**Comment by alexdima** [comment] 2021-01-18 09:53
I can reproduce on Windows as well, so this is definitely a logical bug.

**Comment by alexdima** [comment] 2021-01-18 09:56
The root problem is :
![image](https://user-images.githubusercontent.com/5047891/104899934-beb03300-597b-11eb-8c4e-f4d143dd0a5a.png)

This might be caused by the extraction of the extensions from the core.

**Comment by alexdima** [comment] 2021-01-18 09:57
Yes, it looks like the web bits are missing builtin extensions:

![image](https://user-images.githubusercontent.com/5047891/104900082-e901f080-597b-11eb-87ed-0429eb57c79b.png)

@joaomoreno I once figured out exactly how the extension inlining in the web bit works, so we can talk if you need help.

**Comment by bpasero** [comment] 2021-01-18 09:58
Yup, that's it, didn't even think about checking the language...

**Comment by joaomoreno** [comment] 2021-01-18 11:02
Unrelated to this problem, I just saw this on my terminal:

```
➜  vscode-distro git:(distro) yarn gulp vscode-web      
yarn run v1.22.4
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-web
[11:59:27] Using gulpfile ~/Work/vscode-distro/gulpfile.js
[11:59:27] Starting 'vscode-web'...
[11:59:27] Starting clean-out-build ...
[11:59:28] Finished clean-out-build after 677 ms
[11:59:28] Starting compile-build ...
[11:59:31] Starting compilation...
[12:01:56] Finished compilation with 0 errors after 144867 ms
[12:01:56] Finished compile-build after 148144 ms
[12:01:56] Starting clean-web-extensions-build ...
[12:01:56] Finished clean-web-extensions-build after 47 ms
[12:01:56] Starting bundle-web-extensions-build ...
Failed to parse dependency: emmet@https://github.com/rzhao271/emmet.git#1b2df677d8925ef5ea6da9df8845968403979a0a
```

@rzhao271 You might wanna investigate.

**Comment by joaomoreno** [comment] 2021-01-18 11:04
Related to this, here's the problem:

https://github.com/microsoft/vscode-distro/blob/d577c4b18dab088bb55faf48309f65380684aa61/build/lib/extensions.ts#L240-L242

I wonder if we should instead have an _opt out_ list, instead of an _opt in_ list? Those usually stand the test of time more often than not.

**Comment by alexdima** [comment] 2021-01-18 11:39
@joaomoreno :+1: I agree this is fragile.

It would be even better if we could somehow contain this information in the json directly. Like `"forWeb": true` directly in the `product.json` for the ones that should be included.

**Comment by joaomoreno** [comment] 2021-01-18 13:39
Yeah. Doing an easy fix for now.

**Comment by joaomoreno** [comment] 2021-01-18 14:01
I even found out that web is recompiling extensions: https://github.com/microsoft/vscode/issues/114530

**Comment by joaomoreno** [comment] 2021-01-18 14:03
Fixed by: https://github.com/microsoft/vscode/commit/911a54273ce76db30adc591d9c230cf5ff764aa2

**Closed by joaomoreno** 2021-01-18 14:03 UTC
Labels: important, web
