### ISSUE TITLE
TypeScript language server crashing

### ISSUE THREAD

**Issue by galloppinggryphon** [microsoft/vscode#189734] opened 2023-08-05 22:17 UTC
Type: <b>Bug</b>

TypeScript language server started crashing after update to 1.81.0 -- everything was working prior to update.

**Error messages**
> TypeScript language server exited with error. Error message is: write EPIPE

> TypeScript language server exited with error. Error message is: Channel closed

> The JS/TS language service immediately crashed 5 times. The service will not be restarted.

**Edit**
Tried deleting `%appdata%\Code` and resynced VSCode with cloud. Problem persists.

**Edit 2**
Disabled all extensions, problem persists.

**Edit 3**
Clean install of vscode fixed it. Can I suggest a reinstall ability to cut down the effort a bit? Make it easier to do a clean reinstall and cut down on the number of bug reports.

---

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (4.43GB free)|
|Process Argv|--crash-reporter-id 048e732f-921b-4cb2-b1de-30b0ce339375|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
json-parse-validator|Adr|1.1.2
project-manager|ale|12.7.0
vscode-color|ans|0.4.5
statusbar-commands|anw|2.7.0
vscode-zipfs|arc|3.0.0
color-info|bie|0.7.2
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.2
typescript-notebook|don|2.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-commands|fab|1.4.3
auto-rename-tag|for|0.1.10
html-slim-scss-css-class-completion|gen|1.7.8
lintlens|ghm|7.4.2
beautify|Hoo|1.5.0
vscode-phpfmt|kok|1.1.11
vscode-language-babel|mgm|0.0.39
vscode-deploy-reloaded|mkl|0.89.0
minecraft-debugger|moj|1.1.0
vscode-scss|mrm|0.10.0
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
rich-markdown-editor|pat|1.0.2
phpdoc-comment-vscode-plugin|rex|1.3.0
LiveServer|rit|5.7.9
todolist|sab|0.2.50
vscode-scss-formatter|sib|3.0.0
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
cmake|twx|0.0.17
vscode-icons|vsc|12.4.0
markdown-editor|zaa|0.1.10
multi-rename|zar|0.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by mjbvz** [comment] 2023-08-09 20:18
Closing since this no longer seems to happen. Hard to know what caused this. Often if a reinstall fixes the problem it could have been caused by a poorly behaved antivirus tool

**Closed by mjbvz** 2023-08-09 20:18 UTC
