### ISSUE TITLE
windows.restore: all does not behave as expected

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55059] opened 2018-07-25 13:56 UTC
Refs: #54864

Have mutliple vscode windows open. Set `"windows.restore": "all"`
Right click taskbar -> close all
Start vscode again -> only one window is opened 🐛
I would expect all windows to be restored due to the setting I just set

**Comment by GandalfSaxe** [comment] 2018-07-25 14:08
I was also confused by this behavior initially, but it's actually expected behavior. It all comes down to the sad little fact that Windows don't have a nice simple keyboard shortcut for **Quit App** as Mac does with `Cmd+Q`.

All windows will be restored if you quit by clicking File -> Exit. With the keyboard you can do: `Alt+F, X` (the closest Windows get to `Cmd+Q`.

The windows will not be restored if you:

* Press Alt+F4 - this simply closes the current window.
* Right click app, then click "Close all" - Windows / VSCode will simply interpret this as you wanting to close all windows, not _quit_ the app and save the state to restore next time. This command essentially is the same as clicking the red X in the corner of all the open windows.

So yeah on Mac, it's very natural to press Cmd+Q too close. On windows you have to be careful how you close it, because it needs to be File->Exit. You can also assign a keyboard shortcut for this. The command is `workbench.action.quit`, and is assigned to `Cmd+Q` on Mac, but unassigned on Windows.

**Comment by GandalfSaxe** [comment] 2018-07-25 14:12
As an aside, I really think `"window.reopenFolders": "all"` should be default, but that's another thing.

**Comment by sandy081** [comment] 2018-07-25 17:05
Thanks @GandalfSaxe for your confirmation. Yes this is expected and it works like this.

**Comment by GandalfSaxe** [comment] 2018-07-25 17:10
I also agree that it would be a better default to restore if it was closed with right click + code all windows. If one really wants to close all windows without restoring, this is a much more uncommon need, and would be served fine by closing windows individually. So I completely agree with your sentiment. The question is if the team agrees, and if it's easily technically feasible.

**Comment by bpasero** [comment] 2018-08-06 12:38
This works as designed, the "Close All" from the task bar is identical to closing each window individually. Use File > Exit to reopen all windows.

**Closed by bpasero** 2018-08-06 12:38 UTC
Labels: windows

**Comment by GandalfSaxe** [comment] 2018-08-06 19:11
@ Is there a keyboard shortcut for that as there is Cmd+Q on the Mac? The best ice found is Alt+F, X which feels a little awkward.

**Comment by bpasero** [comment] 2018-08-06 19:39
@GandalfSaxe `workbench.action.quit` can be configured to any key.

**Comment by GandalfSaxe** [comment] 2018-08-06 20:14
Thanks I’ll have a look. Kind of puzzling that windows don’t have a conventional shortcut for that actually.
