### ISSUE TITLE
WorkspaceEdit doesn't support creating new files

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#30801] opened 2017-07-16 11:06 UTC
Not sure if this is a bug or just a missing feature!

I'm using `WorkspaceEdit` in my Code Actions provider but noticed that when a code action requires a new file (eg. creating a file from an import statement) it crashes because it can't find the file to modify (for both `insert` and `replace`).

I can't see anything on the API for allowing creation of new files, nor an easy way to detect if a file exists. I could obviously us node's `fs` class for this, but it seems a little weird to start doing that separate from the nice `WorkspaceEdit` class.

Is it valid to have `WorkspaceEdit` support creation of new files were required or is creating the files "manually" the expected way? I had a quick look at some other extensions (like TypeScript) but it seems like they don't handle it either (presumably none of their code actions need to create new files yet?).

**Comment by jrieken** [comment] 2017-07-17 14:23
Closing as dupe of #10659

**Closed by jrieken** 2017-07-17 14:23 UTC
Labels: api, feature-request
