### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#15170] opened 2016-11-08 13:11 UTC
at time editor should be align horizontaly and verticaly and also by aligning drag and drop

**Comment by aeschli** [comment] 2016-11-08 13:31
@MandarSant It's not clear to me what you suggest. Can you add more explanations?

**Comment by MandarSant** [comment] 2016-11-08 13:48
@aeschli  have u used atom

**Comment by aeschli** [comment] 2016-11-08 14:29
@MandarSant Yes, but it still not clear to me (and probably to others) what exactly you like to see in VSCode. Please describe the interactions, where to click, where to drag, how is it shown...

**Comment by MandarSant** [comment] 2016-11-08 15:19
@aeschli in atom when u want to align editor u just drag the tab in desired way same feature in vscode

**Comment by aeschli** [comment] 2016-11-08 18:35
Is this a duplicate of #14909?

**Comment by MandarSant** [comment] 2016-11-09 03:44
@aeschli 40% similar

**Comment by aeschli** [comment] 2016-11-09 07:29
@MandarSant Please a animated gif or screenshots that describe the feature you imagine.

**Comment by MandarSant** [comment] 2016-11-09 12:15
@aeschli  i dont know how to create gif

**Comment by aeschli** [comment] 2016-11-14 09:56
Closing due to lack of information. @MandarSant  Please reopen with more details such as screenshots.

**Closed by aeschli** 2016-11-14 09:56 UTC
Labels: needs more info
