### ISSUE TITLE
so many powershell.exe has been launch but never exit

### ISSUE THREAD

**Issue by wellingfine** [Microsoft/vscode#61014] opened 2018-10-16 02:47 UTC
Issue Type: <b>Bug</b>

After runing vscode.exe , powershell.exe is created every five or ten minutes. Even in idle state ,powershell.exe created all the time . If exit vscode.exe ,all powershell processes are ended.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by arnauldvm** [comment] 2018-10-17 07:17
Same problem here. Had to kill them with `taskkill /F /IM powershell.exe` and recovered over 1GB of memory!

They of course come back gradually after a while.

At first impression, it seems a new process is spawned each time the "Settings Sync" extension is running, at least in my case. (Don't know if it's limited to this extension, or if it's a general issue, though.)

**Comment by JosepMaJAZ** [comment] 2018-10-17 11:03
Just wanted to add a "me too" here.

This capture is 8 minutes after launching VScode. Previous launch had more than 50 powershells opened (maybe even 100).
![image](https://user-images.githubusercontent.com/9913727/47082043-b43ae800-d20c-11e8-8523-b9586c284224.png)

**Comment by ramya-rao-a** [comment] 2018-10-17 17:17
Thanks for reporting, this issue is being tracked in #60585

We have a fix which we will be releasing soon, but we would greatly appreciate if any of you can help use verify the fix as well. To do so, close all instances of VS Code, and download VS Code from one of the below links to see if the problem is now fixed.

- [64 bit user setup](https://az764295.vo.msecnd.net/stable/7f3ce96ff4729c91352ae6def877e59c561f4850/VSCodeUserSetup-x64-1.28.2.exe) 
- [64 bit system setup](https://az764295.vo.msecnd.net/stable/7f3ce96ff4729c91352ae6def877e59c561f4850/VSCodeSetup-x64-1.28.2.exe) 
- [32 bit user setup](https://az764295.vo.msecnd.net/stable/7f3ce96ff4729c91352ae6def877e59c561f4850/VSCodeUserSetup-ia32-1.28.2.exe)
- [32 bit system setup](https://az764295.vo.msecnd.net/stable/7f3ce96ff4729c91352ae6def877e59c561f4850/VSCodeSetup-ia32-1.28.2.exe)

**Comment by JosepMaJAZ** [comment] 2018-10-17 17:44
An quick test after installing shows the problem is fixed (no more powershell processes spawned by code.exe), although VScode detects that it is not the "stable" version and downloads 1.28.1 to reinstall it after it is restarted. I am just guessing that this is the normal behaviour, but reporting it just in case.

I will run a longer test tomorrow.

**Comment by ramya-rao-a** [comment] 2018-10-17 18:05
Thanks for verifying @JosepMaJAZ!

> although VScode detects that it is not the "stable" version and downloads 1.28.1 to reinstall it after it is restarted. 

That is just because we havent yet released 1.28.2 yet.

Closing this issue as /duplicate of #60585

**Closed by ramya-rao-a** 2018-10-17 18:05 UTC

**Comment by wellingfine** [comment] 2018-10-18 03:14
In my case , problem solved after updating vscode to 1.28.2 just now.Thanks @ramya-rao-a
