### ISSUE TITLE
File icons aren't Displayed

### ISSUE THREAD

**Issue by yc9274** [microsoft/vscode#76946] opened 2019-07-09 08:15 UTC
Issue Type: <b>Bug</b>

Icons not coming at the side bar

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18932

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
prettier-vscode|esb|1.9.0
sass-indented|rob|1.5.1

</details>

**Comment by d1vanloon** [comment] 2019-07-09 16:35
Which icon set do you have selected? Possible duplicate of #76925?

**Comment by misolori** [comment] 2019-07-09 17:57
Duplicate of #76925 (thanks @d1vanloon)

**Closed by misolori** 2019-07-09 17:57 UTC
