### ISSUE TITLE
Visual Studio always uses significant energy

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#16963] opened 2016-12-09 08:33 UTC
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.4|
|swift|Kasik96|0.0.2|
|python|donjayamanne|0.5.2|
|vscode-lua|gccfeli|0.1.2|
|CSSfmt|ilich8086|0.0.3|
|Go|lukehoban|0.6.51|
|HTMLHint|mkaufman|0.0.3|
|prettify-json|mohsen1|0.0.3|

---

Steps to Reproduce:

Open any file and do some changes, open the terminal or write Go code, vscode always consumes too much energy. This is the reason I have to use some light weight editor like Geany or vi. I'd love it if vscode uses less energy than what it does now.

**Comment by strrchr** [comment] 2016-12-09 14:05
I encounter the similar problem.
Are there tips or options to reduce cpu usage?

**Comment by thewhitetulip** [comment] 2016-12-10 04:55
I started using `vi`because despite the fact that this is an amazing text editor, it eats up my battery within 2-3hrs of usage. using vi, my battery stays four times upto 8hrs!

**Comment by kieferrm** [comment] 2016-12-13 06:00
//cc @egamma

**Comment by egamma** [comment] 2016-12-22 13:18
The Go extension isn't shy to spawn new processes, e.g., on hover, which can result in increase memory consumption.

@thewhitetulip can you confirm that you only saw this problem when developing Go code?

Assigning to @ramya-rao-a for further investigation in the Go extension.

**Comment by thewhitetulip** [comment] 2016-12-23 04:41
@egamma Well, I use Code only for Go programming :-) So I can't say for sure. But I will confirm by writing a python project using VScode too

**Comment by thewhitetulip** [comment] 2016-12-25 07:15
@egamma I am sorry for the delay, yes, writing Go code marks VSCode as using high energy, tested thrice writing JS and writing Go, JS has no issues, Go has issues.

Also, thought you might want to know:

Code Helper eats 11% CPU for every single edit of any file (Go or not)
Code itself takes 1.4% CPU and 43MB when it is in background (it is updating to the new version, and has 1 open JS file)

92+28+26+59+23 MB is the system memory Code Helper eats even if it is idle (there are that many instances of the service) contrast that with iTerm, I had 10 tabs and a server running, still iTerm takes .4% CPU 43MB Memory

Do let me know if you need more information.

**Comment by egamma** [comment] 2016-12-25 16:50
@thewhitetulip thanks for following up, I move the issue to the Go Issue repository for further investigation.

**Comment by egamma** [comment] 2016-12-25 16:51
This issue was moved to Microsoft/vscode-go#698

**Comment by thewhitetulip** [comment] 2017-02-04 05:27
I am now editing a markdown book and VSCode is taking significant energy, I do not think it is because of the Go extension.

**Comment by thewhitetulip** [comment] 2017-02-04 05:28
I am now editing a markdown book and VSCode is taking significant energy, I do not think it is because of the Go extension. @egamma @ramya-rao-a I just have the welcome screen on, not even a single document opened. I just updated every extension and the Go plugin's dependencies.

**Comment by egamma** [comment] 2017-02-06 09:08
Reopening the issue

@thewhitetulip do you still observe the high energy consumption when you disable the extensions? To disable an extension pls see this [doc](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension)

**Comment by thewhitetulip** [comment] 2017-02-06 16:06
@egamma I disabled all extensions permanently, I have my mac connected to wifi and Vscode is "using significant energy"

CPU consumed varies between 9% to 12% without extensions of any kind, with split window, one of markdown and another of a 100line python program
Energy impact is 12!!

5 processes costing me 240MB RAM @ramya-rao-a

**Comment by ramya-rao-a** [comment] 2017-02-06 17:02
@bpasero thoughts?

**Comment by bpasero** [comment] 2017-02-06 17:08
Maybe worth checking if a process is running with high CPU in that setup.

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by thewhitetulip** [comment] 2017-02-06 17:22
I will do that, I would just like to know that am I the only one who is getting "significant energy usage"? I mean is there an issue with my mac(some weird local thing)?

**Comment by egamma** [comment] 2017-02-07 07:59
@thewhitetulip we had [some energy issues](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+energy+is%3Aclosed) in the past, but most of them are closed by now.

**Comment by thewhitetulip** [comment] 2017-02-07 17:00
@egamma Yes, it takes somewhat CPU
wow, Code takes way less power on the Mac you are using, I am editing a markdown tutorial I am writing related to Python without any extension and this is the screenshot, 
![screen shot 2017-02-07 at 10 28 39 pm](https://cloud.githubusercontent.com/assets/6261877/22701896/01bfcd0c-ed85-11e6-9cf2-ffe45d9b83d0.png)

**Comment by bpasero** [comment] 2017-02-07 17:17
@thewhitetulip is there a constant 21.7% hit on the process or only when you typeß

**Comment by thewhitetulip** [comment] 2017-02-07 17:39
Only when I type, if I have the window active, then it is 7% around, when I type, it goes up slowly, 14, then 21. If the window is inactive, then it goes down to 0

**Comment by bpasero** [comment] 2017-02-08 06:03
Maybe it would make sense to run a CPU profile to see where time is spend while typing. Can you run it and type a lot and then stop it and attach the results here?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by chuckdries** [comment] 2017-02-23 08:52
I'd like to chime in that I am also having a similar issue. I've disabled every plugin and still my VSCode spins my fans all the way up like jets even when I'm not doing anything. The thing is, if I look under energy settings in activity monitor, it doesn't look that bad. Energy impact fluctuates around 30 and none of the child processes seem to use more than 30% CPU.
<img width="1409" alt="screen shot 2017-02-23 at 1 40 57 am" src="https://cloud.githubusercontent.com/assets/1351436/23251175/83701e0c-f969-11e6-8761-71c213650e1d.png">
<img width="1409" alt="screen shot 2017-02-23 at 1 42 26 am" src="https://cloud.githubusercontent.com/assets/1351436/23251178/86786f50-f969-11e6-962e-5ba8b150ade9.png">

But the laptop still sounds like a jet and drains faster than the charger can provide power. So I tab over to CPU and holy guacamole it tells a different story.

<img width="1409" alt="screen shot 2017-02-23 at 1 39 50 am" src="https://cloud.githubusercontent.com/assets/1351436/23251209/a46c3c4e-f969-11e6-8cc3-fe8cccd3e75b.png">

Those two code helper processes at the top are almost always pinned at 100%. Here's "open files and ports" for one of them:

`cwd
/
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
txt
/usr/lib/libexpat.1.dylib
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/usr/lib/dyld
txt
/usr/share/icu/icudt57l.dat
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
/dev/null
1
/dev/null
2
/dev/null
3
->(none)
4
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
5
->0xc49da5209de57871
6
->0xc49da5209de556b1
7
->(none)
8
count=3, state=0x8
9
->0xc49da5209de564f1
10
->0xc49da5209de54db1
11
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
12
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
13
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
14
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/locale.pak
15
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak
16
/dev/urandom
17
->0xc49da5209de54ab1
18
->0xc49da5209de54c31
19
->0xc49da5209de565b1
20
->(none)
21
/Applications/Visual Studio Code.app/Contents/Resources/electron.asar
22
->0xc49da5209de54b71
23
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
24
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
25
/dev/urandom
26
/dev/null
27
->(none)
28
/var/folders/28/fxhx9rvn12v4ndv1kn5sb_zm0000gn/T/vscode-62760ababaa6937b722666596dc367287c50ad67.sock
29
->0xc49da520aa027b81
30
/var/folders/28/fxhx9rvn12v4ndv1kn5sb_zm0000gn/T/vscode-62760ababaa6937b722666596dc367287c50ad67.sock
31
->0xc49da520aa028b21
32
->0xc49da520aa029b89
33
->0xc49da520aa028671
35
->0xc49da520aa029ac1
`

The kicker is, their PIDs change every few minutes. It's like they're dying off and being immediately re spawned before I notice.

I used activity monitor to take a sample of one of them as well. I don't know what to do with it, but it can't hurt to attach right?

[Sample of Code Helper.txt](https://github.com/Microsoft/vscode/files/795943/Sample.of.Code.Helper.txt)

I also profiled vscode Main and workerMain.js#editorWorkerService. The workerMain profile is the one that ends in 54.

Wait github won't let me upload the .cpuprofile vscode saved? How should I get that to you?

**Comment by chuckdries** [comment] 2017-02-23 09:05
After reading through that other issue thread, running code with `code --disable-extensions` worked.

Now the thing is how to figure out which one(s) are the culprit.

It seems like this problem of runaway extensions is a common enough issue, perhaps a faq or documentation entry is in order. Maybe even a tool in vscode to tell which extensions are misbehaving?

**Comment by ramya-rao-a** [comment] 2017-02-23 20:55
@chuckdries You mentioned 

>"I've disabled every plugin and still my VSCode spins my fans all the way up.." 

as well as 

>"running code with `code --disable-extensions` worked"

If both statements are true, then disabling extensions manually and running code with --disable-extensions are giving you 2 separate results. Can you confirm?

**Comment by chuckdries** [comment] 2017-02-24 03:57
Indeed I did, though I did notice that the runaway background processes stayed open after I quite VScode, I had to manually kill them. Perhaps they accounted for my initial assessment of disabling extensions not working.
On Feb 23, 2017, at 1:56 PM, Ramya Rao <notifications@github.com> wrote:

@chuckdries <https://github.com/chuckdries> You mentioned

"I've disabled every plugin and still my VSCode spins my fans all the way up.."

as well as

"running code with code --disable-extensions worked"

If both statements are true, then disabling extensions manually and running code with --disable-extensions are giving you 2 separate results. Can you confirm?

**Comment by simonhaenisch** [comment] 2017-09-26 21:43
I'm having issues with this as well on a Mid-2010 MacBook Pro (which can switch between Intel HD Graphics and a NVIDIA GeForce GT 330M).

I launched code from the command line via

```sh
code --disable-extensions --disable-gpu
```

and it doesn't use much energy when in idle, but in the activity monitor it still says that it requires the high performance GPU:

![image](https://user-images.githubusercontent.com/3410759/30885291-23baaeae-a36f-11e7-8240-2da2952407dc.png)

What exactly is the `--disable-gpu` flag supposed to do? The help text says:

> Disable GPU hardware acceleration.

I know that Electron is based on Chromium and I'm quite sure that will already enable the high performance GPU on my Macbook (at least Chrome always needs it). Just might be helpful to have an info about what exactly that flag does, as I was expecting it to prevent using the high perf GPU for me.

**Comment by ramya-rao-a** [comment] 2017-09-27 04:04
cc @bpasero @jrieken

**Comment by thewhitetulip** [comment] 2017-10-05 02:42
@ramya-rao-a how did the bot close it? :open_mouth:

**Comment by ramya-rao-a** [comment] 2017-10-12 17:22
The bot closes issues with the label "needs-more-info" if there has been no additional info provided in the past 7 days.

I just went through the whole thread and here is the summary:

- This issue is no longer restricted to Go
- @thewhitetulip is yet to respond to https://github.com/Microsoft/vscode/issues/16963#issuecomment-278237490
- @chuckdries doesn't see the issue with extensions disabled
- @simonhaenisch has a question on the --disable-gpu flag. @bpasero Can you respond to this?

**Comment by thewhitetulip** [comment] 2017-10-13 03:28
@ramya-rao-a  Someone else posted a profile of their VSCode that is why I did not! Give me some time, I'll comment it as soon as I can.

**Comment by cvburgess** [comment] 2018-01-03 17:25
<img width="728" alt="screen shot 2018-01-03 at 12 23 52 pm" src="https://user-images.githubusercontent.com/2141199/34531642-06412cfe-f081-11e7-905e-a16f4d8eb0d7.png">

VSCode has been wrecking my macbook for the last two weeks or so... it can drain the battery in 2-3 hours on a new MBP. If there's anything I can do to help, please let me know!

**Comment by ramya-rao-a** [comment] 2018-01-04 01:34
@cvburgess Please log a new issue. Read through [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to see what you can share with us to help with your problem

**Comment by bonovski** [comment] 2018-02-15 21:00
Well, vscode is unusable on battery because of code helper cpu usage even after vscode is fully closed. Multiple code helpers can still stay running after that and eat away your battery with high cpu usage.

The problem seems to be extension quality and integration into vscode or lack of.

Every time an extension crashes (and you mostly don't know since there is absolutely no message or alert, you just notice that something doesn't work) code helpers go crazy.

It's back to atom for me. Although it's slower it works without any annoying problems for me and my needs.

**Comment by smxsm** [comment] 2018-05-23 12:52
Yep, I can confirm that VSCode really sucks out the battery ... :( I have quite some extensions installed, so it'll be hard to find out which ones cause the major problems... what can we do?
There are also lots of nested CodeHelper Threads running, and you can see the high energy usage even compared to Chrome and Docker:

![image](https://user-images.githubusercontent.com/1737182/40425505-dbaf2f50-5e98-11e8-9a33-753d5d4bdcf9.png)

**Comment by ramya-rao-a** [comment] 2018-05-25 05:43
@smxsm Read through [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to see what you can share with us to help with your problem

**Comment by smxsm** [comment] 2018-05-25 06:37
Hi @ramya-rao-a thanks for the performance debugging info - since I saw some indications in my status bar that the [PHPCS extension](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs) was constantly checking files and I also was in my process list that a LiveShare process was [consuming lots of CPU](https://github.com/MicrosoftDocs/live-share/issues/355) I have disabled both extensions yesterday and now I am down from 80-90% battery usage for VSCode to approx. 20% :) I see if I can do some profiling later for the PHPCS extension.

**Comment by bpasero** [comment] 2018-09-10 15:59
I am closing this issue and ask to file individual issues to act on. Thanks for understanding.

**Closed by bpasero** 2018-09-10 15:59 UTC
Labels: perf
