### ISSUE TITLE
markdown preview in Remote SSH not woking properly

### ISSUE THREAD

**Issue by Subratappt** [microsoft/vscode#82439] opened 2019-10-12 18:11 UTC
Issue Type: <b>Bug</b>

code formatting and styling in markdown preview is not working properly.

1. Preview of file in local
![Screen Shot 2019-10-12 at 11 33 22 PM](https://user-images.githubusercontent.com/40207448/66705864-bb2a0700-ed49-11e9-89ed-11753d5914f6.png)

2. Preview of file in Remote-SSH
![Screen Shot 2019-10-12 at 11 32 13 PM](https://user-images.githubusercontent.com/40207448/66705869-c11fe800-ed49-11e9-9402-d9ecea75c43b.png)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|-psn_0_360536|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
fortran-ls|han|0.6.0
latex-workshop|Jam|8.2.0
linter-gfortran|krv|2.1.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.25.1
material-icon-theme|PKi|3.9.1
vscodeintellicode|Vis|1.1.9

(2 theme extensions excluded)

</details>

**Comment by thijsputman** [comment] 2019-10-14 15:19
Seem to be running into a similar issue with a WSL-remote.

All of the "advanced" features appear to be broken (such as the preview locking and my custom theme for the Markdown preview). Doing the same in a non-WSL vscode window works without issues.

The following error is generated about a dozen times on the development tools console while in the WSL-remote:

``resourceLoader.ts:39 h: Unable to read file (Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"))
    at v.readFileStream (file:///C:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1539:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)``

**Comment by mjbvz** [comment] 2019-10-14 21:23
Duplicate of #82336 

Fixed in insiders. Should be fixed a 1.39.2 build early this week

**Closed by mjbvz** 2019-10-14 21:23 UTC
Labels: new release
