### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by danitetus** [microsoft/vscode#104275] opened 2020-08-07 22:21 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.9.6

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
```
Error: Debug Failure.
    at actualResolveModuleNamesWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:99915:161)
    at resolveModuleNamesWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100133:26)
    at resolveModuleNamesReusingOldState (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100282:19)
    at processImportedModules (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101695:35)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101438:17)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101665:21
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at processLibReferenceDirectives (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101660:16)
    at findSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101435:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:85
    at getSourceFileFromReferenceWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101234:34)
    at processSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101267:13)
    at processRootFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101090:13)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100014:60
    at Object.forEach (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:100014:16)
    at synchronizeHostData (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138753:26)
    at Proxy.getProgram (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138845:13)
    at ConfiguredProject.Project.updateGraphWorker (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143337:53)
    at ConfiguredProject.Project.updateGraph (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143280:42)
    at ConfiguredProject.updateGraph (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144074:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145727:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146608:44)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:97
    at Object.flatMap (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146927:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147790:46)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.7.9-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3695)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.60GB (1.56GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by mjbvz** [comment] 2020-08-08 00:00
Duplicate of https://github.com/denoland/vscode_deno/issues/89

**Closed by mjbvz** 2020-08-08 00:00 UTC
