### ISSUE TITLE
Our built in views should have icons for activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94900] opened 2020-04-10 12:03 UTC
For example here I dragged out all debug views to be top level view containers and they seem to not have good icons, same for "opened editors":

![image](https://user-images.githubusercontent.com/900690/78989511-193a7a00-7b34-11ea-9f25-643bf2e63f4d.png)

**Comment by misolori** [comment] 2020-04-10 15:30
Duplicate of https://github.com/microsoft/vscode/issues/93964

**Closed by misolori** 2020-04-10 15:30 UTC
Labels: layout
