### ISSUE TITLE
Terminal command default decoration always renders one line too high after running `ls`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143798] opened 2022-02-23 18:50 UTC
Testing #143433

Other commands don't have this issue--seems to only be `ls` so far.

![image](https://user-images.githubusercontent.com/30305945/155387185-46ceb2cd-a0d7-4d0f-a1f4-f3510e9d0305.png)

**Comment by meganrogge** [comment] 2022-02-23 19:54
Was `ls` the exact command you ran? I cannot repro this on mac/pwsh

**Comment by joyceerhl** [comment] 2022-02-23 20:09
Yes, `ls` on Windows/pwsh

**Comment by joyceerhl** [comment] 2022-02-23 20:10
Oh, this only happens if I run `clear` first. Probably a duplicate of https://github.com/microsoft/vscode/issues/143784

**Comment by Tyriar** [comment] 2022-02-23 20:45
This is an issue with Windows only, very easy to reproduce with multi-line prompt:
![Recording 2022-02-23 at 12 44 45](https://user-images.githubusercontent.com/2193314/155405150-450f5131-e491-4a65-9c47-e5b5b38d5afa.gif)

It happens because conpty doesn't guarantee the cursor will be in the right position when outputting the command start sequence, so we need some extra smarts to try catch this case for windows ptys only.

**Closed** 2022-02-23 22:10 UTC
Labels: bug, windows, terminal-shell-integration, terminal-command-decoration
