### ISSUE TITLE
Auto import creates duplicate text in react components

### ISSUE THREAD

**Issue by TriStarGod** [microsoft/vscode#85314] opened 2019-11-21 16:37 UTC
- VSCode Version: 1.40.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open JSX file
2. Add new react component
3. Place cursor anywhere before the end of the component (ie `<CssBa|seline />` -  | symbolizes cursor position)
4. Press CTRL + SPACE BAR
5. Wait for (~2 secs) and choose auto import option.

Result: Import is successfully found and placed at the top of the JSX file but react component contains duplicate text. (ie `<CssBaselineseline| />`)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

I did search to see if there are any other similar reports on this issue but I couldn't find them.
I also tried with "javascript.implicitProjectConfig.checkJs": true . This makes the light bulb provide the import option and it works as expected.

**Comment by IllusionMH** [comment] 2019-11-21 16:44
> react component contains duplicate text. (ie )

@TriStarGod looks like example of what is result not pasted, but I guess that this is duplicate of #10266

**Comment by TriStarGod** [comment] 2019-11-21 16:55
@IllusionMH It is similar but I missed it completely since I was using the Auto Import function.

**Comment by IllusionMH** [comment] 2019-11-21 17:39
/duplicate of #10266

Auto import - is just suggestion from other module that has corresponding update text (import statement) and range.

**Closed** 2019-11-21 17:39 UTC
Labels: *duplicate
