### ISSUE TITLE
Ability to handle multiple extension for different environment.

### ISSUE THREAD

**Issue by Sharma121** [microsoft/vscode#100494] opened 2020-06-18 12:46 UTC
Hii .
You have done great job.
But there is issue in it with extension .
If i have to work on different coding environment (like shifting from php to python) . Then i have to first disable all the previous extension which i am using for php and then enable all the python extension one by one. If i have to switch frequently then i have done this multiple time.
If i not disable the previously used extensions then vscode become too heavy and its performance slows down. 

There are some extension available in market that save the environment. But what they doing is completely uninstall the previous extension therefore when i come back then they reinstall it and it takes time sometime too much depending on net speed and extension size.

I have a suggestion if you can provide the functionality that i can create the group of extensions . Like when i have to work on python can enable the python's extension and rest will be disabled which are downloaded and i can also create the global plugins so that they are available for every project.

It would be very helpful if you provide the solution for this issue.
Thanx from a coder.

**Comment by yume-chan** [comment] 2020-06-18 13:20
Duplicate of #57548

**Comment by gjsjohnmurray** [comment] 2020-06-18 14:00
/duplicate

@yume-chan thanks for identifying the dupe

**Closed** 2020-06-18 14:01 UTC
Labels: *duplicate
