### ISSUE TITLE
Debugger tooltip layout broken

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#30855] opened 2017-07-17 12:43 UTC
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0

---

Steps to Reproduce:

1. Hover over a variable while debugging. Sometimes the layout is broken and only shows a single data member:

![image](https://user-images.githubusercontent.com/1658949/28268290-fa6a2920-6afd-11e7-8eb6-ef7d6bb00a22.png)

Manually scrolling the scrollbar indicates that there is more content hidden behind the broken layout:

![image](https://user-images.githubusercontent.com/1658949/28268320-261f5f54-6afe-11e7-8674-c59d4237be1d.gif)

This doesn't seem to happen for every variable, but the behavior seems to be consistent for any given variable. So it might be related to the data itself.

When I evaluate the variable in the Debug Console, it is displayed just fine.

**Comment by isidorn** [comment] 2017-07-17 13:54
@oliversalzburg thanks for reporting.
Can you constantly reproduce this? If yes can you share a simple javascript sample for which you can get this consistently. We would need that in order to investigate further since I can not reproduce this behavior on my side. Thanks

**Comment by oliversalzburg** [comment] 2017-07-17 15:12
@isidorn It keeps happening, but I can't repro at will. I just tried the same debugging session again where I recorded the GIF, but now it works perfectly.

Next time it happens, I will investigate more. If you have any suspicions, I'd be happy to hear and verify them.

**Comment by oliversalzburg** [comment] 2017-07-18 07:37
This happened again yesterday at home (so on another machine as well). I didn't see how to repro it, but I noticed more details.

While the debugger is paused, I hover over variables and they all appear as you would expect. But then one tolltip suddenly looks different for a brief moment. This tooltip does not list the properties in the familiar tree view, but it is simple one line of text with a sort of summary of the object's properties.

This tooltip will switch to the more familiar view within a few moments. This view will then have the display issue seen in the original report. Triggering more tooltips of other variables seems to help "snap out" of the problematic display issue even for the variable where it originally happened.

So I can not confirm that this seems to be related to the data in the object. Maybe it's something to do with how I have my systems set up.

**Comment by isidorn** [comment] 2017-07-18 08:25
@oliversalzburg thanks for providing more details, however after trying it more on my machine I was still unable to reproduce this.
However looking at the code I changed the order how the editor layouts the widget and only then we will scan the dom node for the size that is needed for the scrollable element. In theory this should fix it, however I can not check since I can not repro.

You can try it out in tomorrow's inisder build and let us know if it fixed the issue for you

**Comment by oliversalzburg** [comment] 2017-07-18 08:51
Awesome. Thanks a lot. I'll probably wait for the next milestone release as I had some bad experiences with the Insiders build in the past and I don't want to have any negative impact on productivity right now.

**Comment by oliversalzburg** [comment] 2017-07-18 11:54
For completeness sake, here's a screenshot of the initial state of the tooltip I was talking about earlier:

![image](https://user-images.githubusercontent.com/1658949/28315826-7cf777cc-6bc0-11e7-83e4-80521ea5cb6a.png)

In this state, the tooltip does not change by itself, as suggested earlier. The tooltip will only change after mouse movement.

**Comment by oliversalzburg** [comment] 2017-08-10 19:47
FYI, this is not fixed in the July update.

**Comment by oliversalzburg** [comment] 2017-08-11 10:41
If anything, this has gotten worse. Can someone point me to a resource (if one exists) that explains how to set up VS Code for active development? I'd be happy to do some debugging on my own but at this point I have no idea where to start.

**Comment by weinand** [comment] 2017-08-11 11:17
What exactly has gotten worse?
What do you mean by "set up VS Code for active development"?

**Comment by oliversalzburg** [comment] 2017-08-11 11:19
The problem is happening more frequently. From 80% working, 20% error it went to 80% error and 20% working.

I would like to run Code itself with a debugger attached, then open my projects in Code and drill down with the debugger when I'm seeing the issue.

**Comment by weinand** [comment] 2017-08-11 11:55
You can use the "toggle developer tools" action from the Help menu to open the Chrome Dev tools.

**Comment by oliversalzburg** [comment] 2017-08-11 12:23
Well, that was a very brief period of debugging fun :P

I opened `workbench.main.js` in the DevTools and that caused DevTools to freeze. Now, whenever I reopen DevTools, they try to open the same file and DevTools freeze again.

**Comment by isidorn** [comment] 2017-08-30 14:54
@oliversalzburg sorry for the slow response, I was on vacation.
I am still unable to reproduce this and none of the other users complained. 

Here's how you can setup vscode for running out source. Once you do that you will be able to debug unminified code. 
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

The file you would be interested in is this one https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L33

Let me know if you find something useful. Thanks

**Comment by oliversalzburg** [comment] 2017-08-30 15:20
Awesome. Thanks a lot, I will look into this. I have this issue on two workstations and all other developers on my team are seeing it on their machines as well.

Maybe it's our code 😆 I'll let you know once I have more input.

**Comment by oliversalzburg** [comment] 2017-09-05 13:01
This is really impossible to debug. As soon as you have any debugging going on, everything is slowed down just enough that this issue does not happen.

When I'm in a spot where I see the broken tooltip left and right, I open the DevTools and that instantly "fixes" all tooltips.

**Comment by oliversalzburg** [comment] 2017-09-05 13:30
![image](https://user-images.githubusercontent.com/1658949/30063370-ce21d840-924e-11e7-876e-66c93ec6e4eb.png)

This is the closest I could get so far. The tree seems to only contain 1 item. I don't understand how the tooltip is *supposed* to work and debugging is also near impossible with the transpiled sources, unless I put a breakpoint on every single line in the code.

**Comment by isidorn** [comment] 2017-11-13 18:58
@oliversalzburg is this still an issue in the latest vscode stable?

**Comment by oliversalzburg** [comment] 2017-11-14 10:02
@isidorn I don't recall it happening recently.

**Comment by isidorn** [comment] 2017-11-14 11:16
@oliversalzburg glad to hear. Closing for now and let us know if it happens agains and we will reopen.

**Closed by isidorn** 2017-11-14 11:16 UTC
Labels: bug, debug, needs more info
