### ISSUE TITLE
Integrated terminal env settings in workspace stopped working in vscode 1.5.6 SSH remote

### ISSUE THREAD

**Issue by karthikeyann** [microsoft/vscode#123146] opened 2021-05-06 15:35 UTC
- VS Code Version: 1.5.6
- OS Version: Windows 10 Enterprise, (With Remote SSH on Ubuntu 18.04)

Steps to Reproduce:

1. Take vscode session in windows using remote ssh connection on a workspace in linux host (ubuntu 18.04)
2. Settings defined in workspace are not reflected in integrated terminal 
`terminal.integrated.env.linux` defined in workspace in linux remote.
```
"terminal.integrated.env.linux": {
            "MYVAR": "8",
        },
```
3. Open terminal and execute `echo $MYVAR`

Does this issue occur when all extensions are disabled?: No

**Comment by meganrogge** [comment] 2021-05-06 18:01
Duplicate of #123142

**Comment by meganrogge** [comment] 2021-05-06 18:12
Duplicate of #122104

**Closed** 2021-05-06 18:13 UTC
Labels: *duplicate
