### ISSUE TITLE
Despite the latest version, a "Please update your TypeScript version" dialog appears when selecting "Report Problem".

### ISSUE THREAD

**Issue by manjuu-eater** [microsoft/vscode#173360] opened 2023-02-03 19:06 UTC
Type: <b>Bug</b>

I am using the latest version of TypeScript, but when I selected "Report Problem", a "Please update your TypeScript version" dialog appears.

1. Analysing .js file crashes.
2. Dialog below appears.
"The JS/TS language service immediately crashed 5 times. The service will not be restarted."
(Screen shot is attached below)
3. Select "Report Issue" button.
4. Dialog "Please update your TypeScript version" appears.
(Screen shot is attached below)

I saw this Dialog with these versions:
- TypeScript 4.9.5 (VSCode bundled version)
- TypeScript 4.9.5 (manually installed version)
- TypeScript 5.0.0-dev.20230203

Screenshots of 2.:
![](https://user-images.githubusercontent.com/88940383/216686795-912726cd-b890-4a9b-b2f9-aff6bb57194c.png)
![](https://user-images.githubusercontent.com/88940383/216686799-42d360b7-9721-46b2-a1cb-42149ee01b6b.png)

Screenshots of 4.:
![](https://user-images.githubusercontent.com/88940383/216686801-b0adff47-d4b1-4665-a458-f5de4d5c7590.png)
![](https://user-images.githubusercontent.com/88940383/216686804-0fedfc2a-8b0e-414e-a845-622d2cef8300.png)

Maybe related code:
https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/typescriptServiceClient.ts#L657

----

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.09GB free)|
|Process Argv|. --disable-extensions --crash-reporter-id 9963c767-2656-4ecc-b62b-9405d4b964a1|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by mjbvz** [comment] 2023-02-06 21:29
Duplicate of #133818

**Closed by mjbvz** 2023-02-06 21:29 UTC
