### ISSUE TITLE
Typescript Auto-import pulls in invalid syntax

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#60116] opened 2018-10-08 03:10 UTC
- VSCode Version: 1.27.2
- OS Version: MacOS Mojave

Steps to Reproduce:

1. Try to auto-import a dependency
2. It pulls in invalid syntax

![screen shot 2018-10-08 at 10 09 24 am](https://user-images.githubusercontent.com/9585787/46591055-3f67ff80-cae2-11e8-927c-f5ecfcef63d0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment] 2018-10-08 03:12
Duplicate of https://github.com/Microsoft/vscode/issues/59506

**Closed by RMacfarlane** 2018-10-08 03:12 UTC
