### ISSUE TITLE
Lastest 1.11.1 update wiped out the contens of my unsaved tabs.

### ISSUE THREAD

**Issue by algonzalez** [Microsoft/vscode#24116] opened 2017-04-06 18:03 UTC
Lastest 1.11.1 update wiped out the contens of my unsaved tabs. Tabs were still there, but not 
content.

---

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|Bookmarks|alefragnani|0.13.0|
|vscode-select-line|andreaskian|0.0.3|
|javadebugger|donjayamanne|0.0.2|
|gitlens|eamodio|3.2.0|
|macros|geddski|1.2.0|
|asciidoctor-vscode|joaompinto|0.3.3|
|Kotlin|mathiasfrohlich|1.2.0|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1. Had multiple unsaved tabs open
2. Allowed latest update to happen 
3. VS Code came back up with all the tabs, but no content in any of them.

**Comment by chrmarti** [comment] 2017-04-06 22:20
Did you first update to 1.11.0?

**Comment by Tyriar** [comment] 2017-04-07 01:05
I would expect the fix in 1.11.1 to pick up both backups from 1.11.0 and before https://github.com/Microsoft/vscode/commit/7fad6ea2d8ab23cd5317fbe2723ffccd441e40d4#diff-5234db1cd587e59c15b1f7428b5c0bb3R206

@algonzalez could you check the contents of the director(ies) in `%APPDATA%\Code\Backups\` to see if the backups are present?

**Comment by algonzalez** [comment] 2017-04-07 02:21
I've been pretty good about taking updates when the editor offers them, but I can't swear to having done 1.11.0.

This is on a Mac, so I looked in ~/Library/Application Support/Code/Backups and all I see is 81byte workspaces.json. The contents of that is an array with a single folder path assigned to "folderWorkspaces" and an empty array assigned to "emptyWorkspace".

I suppose it could have wiped that when I exited the editor.

**Comment by bpasero** [comment] 2017-04-07 04:39
Yes, this is https://github.com/Microsoft/vscode/issues/23999. Sorry for that, a restart would clear the backups unfortunately. A time machine backup (if any - see https://github.com/Microsoft/vscode/issues/23999#issuecomment-292246795) could still contain them.

Marking as duplicate of #23999. Let me know if you see it again otherwise 👍

**Closed by bpasero** 2017-04-07 04:39 UTC
Labels: important, needs more info
