### ISSUE TITLE
Moving extension icons 'clicks' them

### ISSUE THREAD

**Issue by GerbenRampaart** [Microsoft/vscode#68605] opened 2019-02-13 09:55 UTC
- VSCode Version: Latest
- OS Version: Any supported by vscode

Steps to Reproduce:

1. Have the default/new install of vscode.
2. Try to change the order of the 'Explorer', 'Search' or 'Source Control' icon on the left panel by click+hold+drag.
3. Notice that you can change the ordering of the icons but you also 'click' the one you're dragging (so the content of the left view changes)

Does this issue occur when all extensions are disabled?: Yes/No
Yes. But more extension icons make the problem more obvious.

The described behavior could be by design but in general in UIs when you're dragging and dropping it doesn't select the dragged item.

**Comment by sandy081** [comment] 2019-02-18 10:01
@bpasero I think this behaviour was introduced by you. Was there any reason behind this?

**Comment by bpasero** [comment] 2019-02-18 11:26
@sandy081 I am not seeing this behaviour on macOS at least but it is possible that it was added to improve perceived performance (aka we open the view on mousedown vs on mouseup).

**Comment by sandy081** [comment] 2019-02-19 09:22
@bpasero You will see the viewlet getting active when you start dragging it, not when mouse down.

https://github.com/Microsoft/vscode/blob/9ef682db65812bfbd5c45cc4472db73eb1855ba0/src/vs/workbench/browser/parts/compositeBarActions.ts#L509-L512

**Comment by bpasero** [comment] 2019-02-19 09:28
@sandy081 oh yeah now I see it. I do not recall why this was added.

**Comment by sandy081** [comment] 2019-02-19 10:03
Do you think it makes sense to remote this behaviour? I do not think viewlet needs to be enabled while being dragged?

**Comment by bpasero** [comment] 2019-02-19 10:11
@sandy081 if I understand the comment correctly this was added because people clicked on the activity icon, accidentally started to drag and then wondered why the click would not activate the viewlet.

**Comment by sandy081** [comment] 2019-02-21 18:13
Ok then closing this as designed.

**Closed** 2019-02-21 18:14 UTC
Labels: *as-designed, needs more info
