### ISSUE TITLE
Aliasing GUI when using on linux kernel 4.14

### ISSUE THREAD

**Issue by annguyen8247** [Microsoft/vscode#40276] opened 2017-12-15 09:03 UTC
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.14.0-parrot2-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|1.0.3
gitlens|eam|6.4.0
indent-rainbow|ode|0.7.2
laravel-blade|one|1.10.0
---

It's happen on 1.17 to 1.19(newest version)
Present Im using mate desktop enviroment

But i think it still happen on another

![image](https://user-images.githubusercontent.com/13550814/34034477-520ce882-e1b1-11e7-9c1b-9e85ddb7177c.png)

**Comment by bpasero** [comment] 2018-03-17 06:35
Likely a duplicate of https://github.com/Microsoft/vscode/issues/35675

**Closed by bpasero** 2018-03-17 06:35 UTC
Labels: electron, font-rendering, linux, upstream
