### ISSUE TITLE
Configure extensions-dir setting in the user settings file

### ISSUE THREAD

**Issue by jltgroup** [Microsoft/vscode#58519] opened 2018-09-12 13:52 UTC
# REQUEST
Add the ability to configure the location of the VS Code extensions directory in the user's settings file.

# BACKGROUND
There can be a variety of reasons why the default location of the VS Code extension directory is not appropriate for users, including:

- Limited disk space in user profile
- Windows group policies restricting which executables can run (i.e. only certain directories permitted).

To circumvent this, users can specify an alternative directory location for the extensions from the command line (i.e. `code --extensions-dir "path\to\dir").

While this command line option works, it is less convenient, particularly when starting VS Code using the Windows Explorer context menu "Open With Code", or using `code .` from the command line.

# PROPOSAL
Add a new configuration setting (e.g. `extensions.directory`) in the user settings file, which allows the user to specify the directory of the VS Code extensions directory. The command line option should remain for backwards compatibility.

On startup, VS Code should look for the extensions directory setting in the following order
1. Command line (`--extensions-dir`)
2. Workspace settings
3. User settings
4. If the setting is not specified, use default setting:
   - Windows `%USERPROFILE%\.vscode\extensions`
   - macOS `~/.vscode/extensions`
   - Linux `~/.vscode/extensions`

**Comment by joaomoreno** [comment] 2018-09-13 06:59
@sandy081 Hard to do since CLI doesn't know about settings. I'd mark it as out of scope.

**Comment by sandy081** [comment] 2018-09-13 10:59
Duplicate of #53154

**Closed** 2018-09-13 11:00 UTC
Labels: *duplicate, extensions

**Comment by jltgroup** [comment] 2018-09-14 09:56
Duplicate of #17691
