### ISSUE TITLE
Path translation C:\User\ <-> /c/User

### ISSUE THREAD

**Issue by yves-chevallier** [microsoft/vscode#79402] opened 2019-08-18 20:43 UTC
As a teacher, I am running on Windows working with WSL and MinGW

I always use my WSL terminal on vscode which is very convenient, but I do not start remote sessions because it is way slower than regular sessions. 

I would like create tasks that run into my chosen terminal. For example the following does not work because the `pwd` is given in the Windows form, not the POSIX one. 

```json
    "tasks": [
        {
            "type": "shell",
            "label": "Build",
            "group": "build",
            "command": "gcc",
            "args": [
                "-g",
                "${relativeFile}",
                "-o",
                "${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "shell": {
                    "executable": "C:\\Program Files\\Git\\bin\\bash.exe",
                    "args": ["-l"]
                }, "cwd": "${fileDirname}"
            },
```

I would like a way to automatically translate all paths such as `fileDirname` either in the Windows or the POSIX form. for instance: 

- `windows`:  `C:\User\Foo\`
- `mingw`: `/c/User/Foo/`
- `cygwin`: `/cygdrive/c/User/Foo/`

I think it is enough if I can configure this way: 

- `"slashMode": "forward"`
- `"pathPrefix": "/cygdrive"`
- `"letterFormat": "{lowerCaseLetter}"`

**Comment by alexr00** [comment] 2019-08-20 16:17
Duplicate of https://github.com/microsoft/vscode/issues/38381

**Closed** 2019-08-20 16:17 UTC
Labels: *duplicate, tasks
