### ISSUE TITLE
quick open menu, open all listed files command.

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#60083] opened 2018-10-07 07:04 UTC
I think a command that would open all currently listed files in the quick open (ctrl+p) drop down list, would be a super convenient feature.

If I have 4 files currently showing in the quick open drop down listed, hitting the shortcut for (the proposed) quickOpenAllFiles command, would open all 4 of those files in the editor.

The convenience comes from the fact that the quick open file search leverages regex control group behaviour under the hood.

So if I search "Foo.xml", it will match for "Foo_bar.xml" since it treats the "Foo", the "." and the "xml" as regex capture groups.

Concrete example:

I have 4 layout xml files in my project....

LayoutMain.xml
LayoutSaveFile.xml
LayoutLoadFile.xml
LayoutExport.xml

In addition, I have a bunch of other source files of various types.

Now I want to open all my layout files.....

1. Hit ctrl+p.
2. Type "Layout.xml"
3 Hit quickOpenAllFiles command.

Voila.

If I wanted to open all the nested .gitignore files in my entire project. This is a good example as .gitignore can be recursively nested all throughout your project (a pain to open in file tree)
2. Type ".gitignore"
3 Hit quickOpenAllFiles command.

You get the idea.

In my opinion, this is a super killer feature.

The drawback is that if you have a large list, you could potentially open up a huge number of files at once. It might be reasonable to have a configurable maximum value, that is defaulted to something reasonable.

**Comment by RMacfarlane** [comment] 2018-10-07 15:57
Duplicate of https://github.com/Microsoft/vscode/issues/55146

**Closed by RMacfarlane** 2018-10-07 15:57 UTC
