### ISSUE TITLE
Handle double-click for mirrored cursors in HTML tags

### ISSUE THREAD

**Issue by Elarcis** [microsoft/vscode#86950] opened 2019-12-13 17:22 UTC
Mirrored cursors allow for the same changes to be made on corresponding pairs of tags.

When double-clicking on a word in an opening or closing tag, only the clicked word is selected, without mirroring. It’d be nice for the other word to be selected and mirrored as well.

```html
<!-- For example, if I want to modify that tag, I’m tempted 
to double click one word and type text to replace it -->
<my-tag></my-tag>

<!-- Currently, double-clicking `tag` and typing
`element` gives that annoying result. -->
<my-element></my-tag>

<!-- Instead, it should have selected the matching text 
on the closing element and modified it as well. -->
<my-element></my-element>
```

**Comment by octref** [comment] 2019-12-13 17:34
Duplicate of #86052.

**Closed** 2019-12-13 17:34 UTC
Labels: *duplicate

**Comment by Elarcis** [comment] 2019-12-13 17:38
Whoops sorry! It didn’t show up in my prior search, guess I should have tried more keywords :P
