### ISSUE TITLE
VS Code cannot handle network drives when run as Administrator

### ISSUE THREAD

**Issue by justinTM** [microsoft/vscode#75361] opened 2019-06-12 18:49 UTC
Steps to reproduce: run VS code as administrator. attempt to open any folder or file on a mapped network drive (e.g., 'Y:\'). VS Code stalls/hangs/does nothing.

Cannot install things using terminal because VS Code doesn't have admin rights, but running as admin means I can no longer access my files... completely screwed by this and can't find a way around it.

**Comment by justinTM** [comment] 2019-06-12 18:50
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Network Share Unavailable As Admin (#64768)](https://www.github.com/microsoft/vscode/issues/64768)

It's an issue, and it hasn't been fixed yet, therefore a new one will be created. I'm not going to +1 an issue, I'm going to make my frustration known. Thanks though, bot.

**Comment by V-ed** [comment] 2019-06-13 14:17
> It's an issue, and it hasn't been fixed yet, therefore a new one will be created. I'm not going to +1 an issue [...]

@justinTM, does this mean you advocate that whenever a user as a problem, no matter if that problem was reported, it should be reported again? So if 200 users face a general problem, there should be 200 issues on a repo about this same problem? Are you seriously this dense? Don't you understand that when you have a backlog of issues, having duplicates is a complete waste of time since you need to triage them all, which at the scale of 5600+ issues and 100+ issues / day is a time vortex that prevents you from actually fixing these issues?

> I'm going to make my frustration known.

Yes, it can be frustrating to stumble upon a bug into a program that you use. It may very well be frustrating. What prevents you from sharing your frustrations in the comments of the already existing issue, therefore making the issue heavier and more prone to be fixed earlier? Having two issues of the same time is simply annoying - having one big issue is a pressure to actually act upon.

You could respond with "I didn't know the issue existed before" - fine, then I could say that you should've searched before. Maybe your search was unsuccessfull then? Sure, then proactively make your voice heard on the initial issue, close your own, and fix what then would be your mistake.

Closing thought : in general, when you demand something, don't be sassy. "Thanks though, bot." - how does that help your cause? The maintainers (Microsoft, in this case) of any repo has no obligations toward you, you are not a special snowflake. Or maybe you are, but it wouldn't be in a positive way...

This issue is a **direct** duplicate of #64768 and should therefore be closed as such.

**Comment by bpasero** [comment] 2019-10-15 14:47
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Closed by bpasero** 2019-10-15 14:47 UTC
Labels: nodejs, upstream
