### ISSUE TITLE
[typescript]: "implements" keyword not highlighted properly

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2737] opened 2016-02-05 15:02 UTC
Using 0.10.7-insider on Windows 7

The implements keyword isn't highlighting correctly

![capture](https://cloud.githubusercontent.com/assets/563860/12849759/7150423c-cc75-11e5-9890-c46607820cbc.PNG)

**Comment by aeschli** [comment] 2016-02-09 10:14
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/38

**Closed by aeschli** 2016-02-09 10:14 UTC
