### ISSUE TITLE
My debugger stopped working

### ISSUE THREAD

**Issue by Dodo995** [microsoft/vscode#100681] opened 2020-06-21 08:10 UTC
Issue Type: <b>Bug</b>

After the update that I made yesterday my debugger stopped working even after I changed the configurations.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by tekdj7** [comment] 2020-06-23 04:48
same issue on mac with Python

**Comment by unbornchikken** [comment] 2020-06-25 08:21
Same issue on Mac with Node.js 14.4.0 app.

Details:

Debugger works fine, until I hit "Run Without Debugging". After this point, it seems VS Code stuck with this command, it launches "Run Without Debugging" command despite I choose "Run Debugging (F5)".

Workarounds:

- Restart VS Code
- Reload Window
- Modify something in launch.json file (weird but works for me) 

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by weinand** [comment] 2020-06-25 08:51
@isidorn sounds related to the "persisted launch config" issue

**Comment by isidorn** [comment] 2020-06-25 09:58
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by unbornchikken** [comment] 2020-06-25 11:50
@isidorn Just tested with Insiders of:

Version: 1.47.0-insider
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:38:28.751Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

The above issue is not present, but it has its own issues:

- "Run Without Debugging" doesn't work, debugger attaches itself no matter what
- "args" from launch.json doesn't propagate correctly. If I have an argument with space it resolves as is instead of between quotes. So for args ["a b", "c d"] i get `node app.js a b c d` instead of `node "a b" "c d"`
- Debugger doesn't stop when the application quits, I have to stop it manually with the button

Fist two of the above is reproducible in regular 1.46.1, if I choose preview debugger in VS Code configuration.

**Comment by isidorn** [comment] 2020-06-25 13:23
Thanks so closing this issue since it is fixed in insiders.
As for issues that are not working please file new issues. Though we are aware of Run Without Debugging and I believe @connor4312 is looking into this

**Closed by isidorn** 2020-06-25 13:23 UTC
Labels: debug, needs more info
