### ISSUE TITLE
Support for () and || for "when" expression in keybindings.json

### ISSUE THREAD

**Issue by Leon99** [microsoft/vscode#13232] opened 2016-10-05 06:12 UTC
I'm trying to make a key binding that only works for certain file types. It works fine with just one file type, but the moment I put something like 
`... && (editorLangId == 'json' || editorLangId == 'js')`
it's not working any longer.

**Comment by mjbvz** [comment] 2019-09-23 23:14
Duplicate of #22778

**Closed by mjbvz** 2019-09-23 23:14 UTC
Labels: feature-request, keybindings
