### ISSUE TITLE
Error formatting code when using inline style atributtes

### ISSUE THREAD

**Issue by marpereira** [Microsoft/vscode#17309] opened 2016-12-15 14:46 UTC
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.2.0|
|vscode-svgviewer|cssho|1.2.0|
|Angular2|johnpapa|1.0.2|
|debugger-for-chrome|msjsdiag|2.4.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. produce HTML code
2. \t < table class="info-obj bottom" style="border-top: 0">
    \t\t\t\t(not indent) <tr *ngIf="response">
3. use shortcut: { "key": "shift+alt+f", "command": "editor.action.formatDocument", "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" },

Expect: 
\t < table class="info-obj bottom" style="border-top: 0">
\t\t(cool format) <tr *ngIf="response">

Actual Result:
\t < table class="info-obj bottom" style="border-top: 0">
(no tabs/spaces) <tr *ngIf="response">

**Comment by marpereira** [comment] 2016-12-15 14:50
Duplicated: #17267

**Comment by kieferrm** [comment] 2016-12-15 19:23
Duplicate of #17267.

**Closed by kieferrm** 2016-12-15 19:23 UTC
