### ISSUE TITLE
Feature: I hope that vscode can support the working mode

### ISSUE THREAD

**Issue by jingyuexing** [microsoft/vscode#170815] opened 2023-01-09 02:29 UTC
A lot of people install a lot of stuff on their vscode because they are heavy users of vscode. 
- Such as front-end development,
- embedded development,
- back-end development 
- and so on. 
They can't manually close some of the installed plug-ins one by one by themselves, so that they can concentrate on the development in a certain direction.

So I hope that vscode can have a work mode option. For example, in the back-end work mode, some plug-ins related to the back-end are automatically enabled, and in the front-end development mode, the front-end related plug-ins are automatically enabled. The same is true for other working modes, only the plug-ins in that mode are enabled, but some plug-ins do not belong to any mode, such as editorconfig.such plug-ins should work in global mode

**Comment by gjsjohnmurray** [comment] 2023-01-09 06:49
I suggest you look at the new feature called Profiles, which is currently in preview.

https://code.visualstudio.com/updates/v1_74#_profiles

**Comment by jingyuexing** [comment] 2023-01-09 11:08
> I suggest you look at the new feature called Profiles, which is currently in preview.
> 
> https://code.visualstudio.com/updates/v1_74#_profiles

The closest introduction in this link may be extension-authoring, but what I expect is to have a drop-down option to directly switch the working mode, and directly turn on or off the plug-in in the workspace according to the working mode.

**Comment by gjsjohnmurray** [comment] 2023-01-09 11:29
After enabling the `workbench.experimental.settingsProfiles.enabled` setting and performing the required restart of VS Code, look for a "Profiles" option in the context menus of the Accounts icon and the Settings icon.

**Comment by sandy081** [comment] 2023-01-10 16:53
/duplicate

Duplicate of the upcoming profiles feature - which we are planning to make it available by default in next release

**Closed by sandy081** 2023-01-10 16:53 UTC
