### ISSUE TITLE
Duplicate entries in Javascript quick outline view

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5225] opened 2016-04-13 14:57 UTC
- VSCode Version: 1.0.0
- OS Version: Linux

Steps to Reproduce:

1. Smoke test (clone https://monacotools.visualstudio.com/DefaultCollection/Samples/_git/vscode-smoketest-express)
2. open bin/www
3. Show quick outline. Note that several entries are duplicated
![image](https://cloud.githubusercontent.com/assets/6461412/14497738/197eff32-0198-11e6-93c8-173dca8eb027.png)

**Comment by egamma** [comment] 2016-04-13 18:19
Duplicate of Microsoft/TypeScript#6566

**Closed by egamma** 2016-04-13 18:19 UTC
