### ISSUE TITLE
Terminal not in a good state initially on Windows Insider builds

### ISSUE THREAD

**Issue by ricardosantos9521** [Microsoft/vscode#57803] opened 2018-09-03 10:17 UTC
Issue Type: <b>Bug</b>

Initial header of any terminal(powershell, exe) appears transparent, only after execution an command the terminal header starts to appear again.

https://imgur.com/a/5KgBNvA

Steps to reproduce:
open terminal on vscode in a latest insider build 1809

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17751

**Comment by Tyriar** [comment] 2018-09-04 13:16
@ricardosantos9521 haven't seen this one before, does it show again when you resize the terminal panel? That will force a redraw.

Could you also try changing the value of `terminal.integrated.rendererType` to see if it shows up then?

**Comment by ricardosantos9521** [comment] 2018-09-04 17:33
@Tyriar Nop the problem still ocurres. 

PS: This only happens in windows insider builds (redstone 5).

https://imgur.com/a/grzLARr

**Comment by GordonSmith** [comment] 2018-09-06 18:40
Just a "me too" here.  This is what I see:
1. Open new terminal instance:  Looks good - but no blinking cursor:
![image](https://user-images.githubusercontent.com/966863/45178013-78bffd80-b20c-11e8-9fd4-45939e21ea16.png)
2. As soon as you start to type, terminal goes blank and resets somewhere near the top:
![image](https://user-images.githubusercontent.com/966863/45178053-9db47080-b20c-11e8-9abc-ddec873e33b4.png)
3. Pressing enter on the command all seems to be good again:
![image](https://user-images.githubusercontent.com/966863/45178103-bde42f80-b20c-11e8-8dcb-eca6bdb68845.png)

**Comment by MeikTranel** [comment] 2018-09-08 18:43
@Tyriar, got the same issue. Same OS background. Using RS5 Insider Builds

![2018-09-08_20-38-37](https://user-images.githubusercontent.com/6466560/45257472-3a127a80-b3a7-11e8-81ca-e8cf36504299.gif)

The whole terminal experience in VSCode on Windows Insiders is pretty rough right now. Output Buffers overwriting and regular terminal inputs like CTRL+Backspace printing command characters... issues like that have been increasingly visible to me since RS5.

**Specs for reference:**

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17755

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe D:\Development\wallboard|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
cake-vscode|cak|0.11.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.4
docs-preview|doc|0.3.12
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.38
vscode-solution-explorer|fer|0.2.33
dotnet-test-explorer|for|0.5.2
beautify|Hoo|1.4.2
rest-client|hum|0.19.1
theme-monokai-pro-vscode|mon|1.1.8
DocFX|ms-|0.1.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.4
debugger-for-chrome|msj|4.10.0
gradle-language|nac|0.2.3
chef|Pen|0.7.0
vscode-docker|Pet|0.2.0
java|red|0.30.0
vscode-icons|rob|7.25.0
vscode-coverage-gutters|rya|2.1.1
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.39
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0


</details>

**Comment by Tyriar** [comment] 2018-09-10 13:59
@bitcrazed FYI, not sure if there have been any changes in this area on your side that could be causing this?

**Comment by bitcrazed** [comment] 2018-09-11 23:15
Not that I know of. @zadjii-msft Are you aware of anything that could cause this issue?

**Comment by zadjii-msft** [comment] 2018-09-11 23:58
Honestly I have no idea. I'm not really sure how winpty gets at the console to get that text.

I'd certainly have a better idea if it were conpty 😝

**Comment by Tyriar** [comment] 2018-09-12 01:29
@bitcrazed @zadjii-msft I've also noticed some weirdness on Windows Insiders where the shell is blank at the start, hitting enter will then show the prompt.

**Comment by Tyriar** [comment] 2018-09-12 19:43
This is what I see:

![image](https://user-images.githubusercontent.com/2193314/45449231-6f5de780-b689-11e8-8ba8-1a971b97f141.png)

Resizing panel reveals:

![image](https://user-images.githubusercontent.com/2193314/45449221-666d1600-b689-11e8-9d1f-39fd7a2ad169.png)

Pressing enter:

![image](https://user-images.githubusercontent.com/2193314/45449256-800e5d80-b689-11e8-983c-1e22d6e7db0c.png)

**Comment by zadjii-msft** [comment] 2018-09-12 19:59
Yikes, that's certainly pretty bad. No idea why that might be, and we're too close to the final signoff on this Windows version to be able to fix that for this release :(

Presumably this'll go away when node-pty picks up conpty, so for RS4 and below they'll still work fine, and RS5+ will get fixed by conpty. There'll just be this awkward middle phase where RS5 is broken.

I still don't know *why* this might be happening in the first place - maybe @rprichard might know more?

**Comment by rprichard** [comment] 2018-09-13 09:15
I can reproduce it, but I don't know what's going wrong yet. When I debug it by setting the `WINPTY_SHOW_CONSOLE=1` environment variable, I see the same sort of broken output in the console window that I see in the terminal window. If there's a `HKCU\Console` entry for the path to the `winpty-agent.exe` binary, then the problem doesn't reproduce. Somehow the lack of that entry, combined with winpty's startup code, is leaving the console in a bad state when the cmd/powershell process starts.

FWIW: I'm thinking of having winpty itself use conpty when it can: https://github.com/rprichard/winpty/issues/152. I'm happy with node-pty using conpty directly, though.

**Comment by GoaLitiuM** [comment] 2018-09-17 14:08
Same issue here, persists in latest insider build 17760.1.

**Comment by jpalo** [comment] 2018-09-21 14:18
Same here on 17763.1 with VS Code 1.27.2, but has been several earlier Windows Insider builds. I usually just press enter once to see the command prompt in terminal, or lately I've just ignored the fact that there is no prompt and just type in the command, as it works nicely.

**Comment by ericblade** [comment] 2018-10-04 16:48
noting also occurs in ConsoleZ https://github.com/cbucher/console/issues/501

**Comment by MeikTranel** [comment] 2018-10-04 16:55
Same goes for zeit/Hyper. After the active dev windows insider ring was lifted onto 19H1, i can also report that the issue persists with the 19H1 prerelease, too.

**Comment by Tyriar** [comment] 2018-10-04 18:22
Upstream issue: https://github.com/Microsoft/console/issues/270

For people experiencing this issue, the way I work around it in the meantime is to just press enter which shows the prompt. You can also just type a command and it will run fine, it's just that the initial prompt doesn't display correctly.

**Comment by szerner** [comment] 2018-10-09 16:31
I have this issue too on my Windows 10 Pro 1809, Build 17764.1, when opening a new terminal window.

Actually it depends on the size resp. height of the terminal window, whether or how the issue shows up:

- Terminal window maximized: no issue with new terminals
- Terminal height below around 22 lines: no cursor, when typing jumps to top with a number of spaces before it
- Teminal height below around 12 lines: no text and no cursor at all (cursor shortly flashes before disappearing)

After pressing <ENTER> everything is ok.

**Comment by aarcoraci** [comment] 2018-10-15 16:31
Guys, this may not be related to VS at all. I'm also a user of Android Studio and when I open the terminal tab in the lower panel I get the same issue.

**Comment by MeikTranel** [comment] 2018-10-15 17:38
It's related to XTerm.js, winpty and the windows console since 1809. We've got that far already.

**Comment by zadjii-msft** [comment] 2018-10-15 17:45
Before I get 100 more pings on this thread: as stated in Microsoft/console#270, the issue is a bug in the console codebase. It's already fixed internally, and bubbling it's way out to Insiders. Should be fixed in 3-4 weeks.

**Comment by Tyriar** [comment] 2018-10-15 18:53
I'm locking this for now as we know about the problem and it's fixed upstream. It will just take some time to get to us.

**Closed** 2018-12-21 20:45 UTC
Labels: important, integrated-terminal, upstream, windows

**Comment by Tyriar** [comment] 2018-12-21 20:52
ConPTY support is landing in the next Insiders build, this uses a new backend for the terminal on WIndows 10 build number 17692+, this is expected to fix many bugs in the terminal on Windows as we're adopting Microsoft's official pty API. For earlier versions winpty will still be used a many bugs will still remain (unless they're fixed in that project).

If you find any issues with conpty please report them to https://github.com/Microsoft/console (the team who own ConPTY) or this repo (if you think it's an integration issue). You can opt out of conpty by adding this setting:

```
"terminal.integrated.windowsEnableConpty": false
```

**Comment by Tyriar** [comment] 2019-02-11 12:13
ConPTY support got pushed back to 18309+ as opt in with v1.31 due to stability concerns.
