### ISSUE TITLE
vs code insiders arm64 “extension host terminated unexpectedly”

### ISSUE THREAD

**Issue by emanuelefavero** [microsoft/vscode#113680] opened 2021-01-02 08:22 UTC
- VSCode Version: vs code insiders arm64 (last version from yesterday)
- OS Version: mac OS Big Sur on M1 (Macbook Air)

Steps to Reproduce:

1. if enabled, half of my extensions give me this problem on the new M1 mac.
2. Do you need the full list of extensions that cause this problem?

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by k0pernicus** [comment] 2021-01-03 09:58
Is this a duplicate of https://github.com/microsoft/vscode/issues/113658 ?

**Comment by emanuelefavero** [comment] 2021-01-03 17:05
I don't think so.

**Comment by ehamwey** [comment] 2021-01-04 17:42
The following steps worked for me, after upgrading from an x86 build of vscode-insiders to Darwin arm64 (`version 1.53.0-insider`) I got the behavior described above.

1. Remove the folder: `/Users/[your-home-folder]/.vscode/`
2. This will remove all extensions and any vscode configurations from your system!
3. Reinstall vscode and any extensions

I think the issue may stem from the fact that certain architecture-specific definitions or other files are not removed during an uninstall/reinstall process. Removing the .vscode folder in your home folder clears them.

**Comment by deepak1556** [comment] 2021-01-05 20:34
I have mistaken this with the other startup crash issue which has a different root cause. What is the best way to repro this issue ?

**Closed** 2021-01-13 12:04 UTC
Labels: :apple: si, bug, needs more info
