### ISSUE TITLE
没有斜体选项

### ISSUE THREAD

**Issue by TKF12** [microsoft/vscode#96049] opened 2020-04-24 09:50 UTC
Issue Type: <b>Bug</b>

字体没有斜体，请把斜体开放出来

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
cssrem|cip|0.1.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.5
jquerysnippets|don|0.0.1
auto-rename-tag|for|0.1.2
vscode-atom-javascript-snippet|glu|0.2.1
canvas-snippets|hol|0.3.2
path-autocomplete|ion|1.13.6
js-snippet|jsc|1.1.0
vscode-gutter-preview|kis|0.26.1
easy-less|Lem|0.15.0
vs-color-picker|lih|1.0.0
HTMLHint|mka|0.6.0
easy-less|mrc|1.6.3
vscode-language-pack-zh-hans|MS-|1.44.2
python|ms-|2020.4.74986
vscode-css-peek|pra|3.0.2
java|red|0.60.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.3
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|2.8.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2020-04-27 07:31
Duplicate of #96050

**Closed** 2020-04-27 07:56 UTC
Labels: *duplicate, *english-please, needs more info, translation-required-chinese-simplified
