### ISSUE TITLE
User Snippets Error

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode#32212] opened 2017-08-10 04:29 UTC
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
vscode-color|ans|0.4.5
theme-verdandi|be5|1.5.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vsc-material-theme|Equ|1.0.2
beautify|Hoo|1.1.1
vscode-gutter-preview|kis|0.10.0
HTMLHint|mka|0.3.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|2.1.0
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
stylelint|shi|0.28.0
ayu|tea|0.4.0

(16 theme extensions excluded)

---

I have created some snippets for JavaScript, I am a beginner, and I have followed the guide in the documentation for creating snippets. These are the snippets: 
`	"Case": {
		"prefix": "case",
		"body": [
			"case ${1:expression}:",
			"\t$2",
			"\tbreak;",
			"$0"
		],
		"description": "A case statement"
	},
    "Switch Statement": {
		"prefix": "switch",
		"body": [
			"switch(${1:expression}) {",
			"\tcase ${3:expression}:",
			"\t\t$4",
			"\t\tbreak;",
			"\t$5",
			"default:",
			"\t$2",
			"}$0"
		],
		"description": "A switch statement"
	},
     "Print to console": {
		"prefix": "log",
		"body": "console.log(\"$1\");$0",
		"description": "Log input to console"
	}
`

Steps to reproduce:
1. Use the new switch snippet.
2. Create a new case statement with the new snippet.
3. Use the log snippet inside the new case statement.
4. When writing inside console.log() parentheses, it also writes in the new line created by the case snippet.

![js_snippets_bug](https://user-images.githubusercontent.com/29575744/29154677-25209780-7d64-11e7-922c-c80d07af3861.gif)

Expected behaviour: edit only inside the parentheses.

Reproduces without extensions: Yes

**Comment by jrieken** [comment] 2017-08-14 09:46
Hm, unable to reproduce with that... @svictoreq Can you boil things down to a smaller repo case or provide more info?

**Comment by svictoreq** [comment] 2017-08-14 15:59
I am a beginner, so I'm sorry if there is a lack of information...

I've created a three snippets:
A custom console.log
`"Print to console": {
		"prefix": "log",
		"body": "console.log(\"$1\");$0",
		"description": "Log input to console"
	},`

A custom Switch statement.
`"Switch Statement": {
		"prefix": "switch",
		"body": [
			"switch(${1:expression}) {",
			"\tcase ${3:expression}:",
			"\t\t$4",
			"\t\tbreak;",
			"\t$5",
			"default:",
			"\t$2",
			"}$0"
		],
		"description": "A switch statement"
	},`

And a custom case statement:
`"Case": {
		"prefix": "case",
		"body": [
			"case ${1:expression}:",
			"\t$2",
			"\tbreak;",
			"$0"
		],
		"description": "A case statement"
	}`

The problem occurs when I use the `log` snippet, which is inside the `case` snippet inside the `switch` snippet.

**Comment by jrieken** [comment] 2017-08-21 15:16
Very confident this is actually #32211, fix will be in tomorrows insiders build.

**Closed by jrieken** 2017-08-21 15:16 UTC
Labels: needs more info, snippets
