### ISSUE TITLE
Copy pasting folded code

### ISSUE THREAD

**Issue by developomp** [microsoft/vscode#128323] opened 2021-07-09 15:22 UTC
Currently, copy-pasting a folded code in vscode unfolds it, requiring programmers to re-fold it each time. This is not only time-consuming but frustrating. Instead, vscode should remember which part of the code was folded and should retain that state after a copy-paste.

**Comment by aeschli** [comment] 2021-07-12 07:40
duplicate of #16082

**Closed by aeschli** 2021-07-12 07:40 UTC
