### ISSUE TITLE
Can't search for extensions

### ISSUE THREAD

**Issue by KKrajevska** [Microsoft/vscode#57864] opened 2018-09-04 12:50 UTC
Issue Type: <b>Bug</b>

When i search for example for a python extension it says no extensions found.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.78GB free)|
|Process Argv|C:\Users\Kristina\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by haskellcamargo** [comment] 2018-09-04 12:58
Duplicate of #57863

**Comment by igorbb** [comment] 2018-09-04 16:04
https://blogs.msdn.microsoft.com/vsoservice/?p=17405

Also this seems to be a duplicate of :

#57851

**Closed** 2018-09-04 17:48 UTC
Labels: *duplicate, extensions
