### ISSUE TITLE
npm: command not found after vscode update

### ISSUE THREAD

**Issue by jpSimkins** [microsoft/vscode#229071] opened 2024-09-19 14:51 UTC
When running any NPM Script in vscode, I now get this:
```
Executing task: npm run npm-version 

/usr/bin/bash: line 1: npm: command not found

 *  The terminal process "/usr/bin/bash '-c', 'npm run npm-version'" failed to launch (exit code: 127). 
```

I can run this fine in vscode terminal:

```
$ npm run npm-version 

> @pcn/devops@0.1.0 npm-version
> npm --version

10.8.2
```

This worked fine a few weeks ago.

I updated vscode recently and now I cannot use the NPM Scripts. 

I have node and npm installed using NVM.

I already tried fully removing node, npm and NVM. I even removed and reinstalled vscode but this issue still persists.

I use this script to install NVM:

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
```

Then I run:

```
nvm install --lts
nvm use --lts
```

I even ran this as others online said this worked for them (years ago):

```
nvm alias default v20.17.0
```

Current version:

```
node --version
v20.17.0
```

```
$ npm --version
10.8.2
```

Which:
```
$ which npm
/home/jpsimkins/.nvm/versions/node/v20.17.0/bin/npm
```

`.bashrc` contains:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
````

I even tested moving that snippet to `.bash_profile` with no change.

Since vscode was updated, NPM Scripts are broken.

I also tried installing older versions since when I run in bash I see this:

```
/usr/bin/bash npm --version
/home/jpsimkins/.nvm/versions/node/v20.17.0/bin/npm: npm: line 2: syntax error near unexpected token `'../lib/cli.js''
/home/jpsimkins/.nvm/versions/node/v20.17.0/bin/npm: npm: line 2: `require('../lib/cli.js')(process)'
```

I tried `v18.20.4`:
```
nvm install v18.20.4
nvm use v18.20.4
nvm alias default v18.20.4
```
Same issue.

Even  `v16.20.2`:
```
nvm install v16.20.2
nvm use v16.20.2
nvm alias default v16.20.2
```
Same issue.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.93.1
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. Have this working with a previous version of vscode
2. Update to latest

**Comment by jpSimkins** [comment] 2024-09-20 01:38
I believe the issue is due to this:

```
/usr/bin/bash npm --version
/home/jpsimkins/.nvm/versions/node/v20.17.0/bin/npm: npm: line 2: syntax error near unexpected token `'../lib/cli.js''
/home/jpsimkins/.nvm/versions/node/v20.17.0/bin/npm: npm: line 2: `require('../lib/cli.js')(process)'
```

It is missing the `-c` for the command. It works as expected when I use `-c`:

```
$ /usr/bin/bash -c "npm --version"
10.8.2
```

**Comment by Tyriar** [comment] 2024-09-24 14:23
This can change depending on whether you launched from a terminal and whether you launched from the OS dock/start bar. Closing all windows and reopening from a terminal might solve the problem for you? Beyond that you would need to see where you're injecting npm/node into the PATH and diff the environments of the terminals to determine the root cause.

**Closed by Tyriar** 2024-09-24 14:23 UTC

**Comment by jpSimkins** [comment] 2024-09-24 15:21
Interesting, I can confirm this works when I open vscode from the terminal. 

So this is not a bug? I mean, this worked fine until I updated vscode. So now opening it via the dock leaves it in a broken state. 

I did compare the $PATH of both launches and they match. 

It is strange it works from launching with terminal so I will do that for now.

**Comment by Tyriar** [comment] 2024-09-24 15:25
Do you have any settings related to "automation profile" by chance?

> I did compare the $PATH of both launches and they match.

When launched from the dock, VS Code will source a "development shell environment" here:

https://github.com/microsoft/vscode/blob/1e80dd664a0e5346012ebe4097a3d32079ac050c/src/vs/platform/shell/node/shellEnv.ts#L132-L151

So maybe something is going wrong there, say if you tweaked your default shell, shell init scripts, etc. When you launch a terminal it will run your regular dev setup so I'm not surprised it would be the same there. Printing the PATH var in a task will give you the interesting one since tasks do not normally run init scripts, but `bash -c`.
