### ISSUE TITLE
[Feature Request] Sticky Tabs

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#34591] opened 2017-09-18 21:00 UTC
I'd like to stick a tab somehow. In the way that I could close all tabs, but the sticky ones. 

Maybe even we could manage groups of tabs, but that could be beyond this. :P. With the stick ability I'll work fine. Thanks! (And sorry if this is someone duplicate, I tried to search for it).

**Comment by ramya-rao-a** [comment] 2017-09-18 21:53
Duplicate of #12622

**Closed by ramya-rao-a** 2017-09-18 21:53 UTC
Labels: workbench
