### ISSUE TITLE
Some extensions will not update / show new version

### ISSUE THREAD

**Issue by jnz86** [microsoft/vscode#210321] opened 2024-04-13 23:48 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.1
- OS Version: Linux Mint 21.3

Steps to Reproduce:

1. Check my extensions, see they're old and new ones are available.
2. Click update. Says Up To Date. 
3. Lies.
4. Some extensions update fine. Others are way back.

Is there a log for the extension search I can check?

**Comment by thany** [comment] 2024-04-16 08:38
Had this problem just now with [Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar).

It was on 2.0.8 for me and VScode insisted that all extensions were up to date. They were quite definitely not. Uninstalling & reinstalling this particular extension brought it to 2.0.10, but as one can see on the extension marketplace page, this one should've installed/updated to version 2.0.12.

**Comment by sandy081** [comment] 2024-04-18 16:30
Can you please share the screenshot of what you are seeing? How are you checking that there is a new version? Can you please open dev tools and see in the network tab and let us know requests the client is making when you check for extension updates.

**Comment by ypresto** [comment] 2024-04-19 13:57
> Had this problem just now with [Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar), also on VScode 1.88.1.

I had issue for this extension today.

Suddenly Vue extension causes too many false-positive TypeScript errors (it turned out it was caused by ["hybrid mode" feature](https://github.com/vuejs/language-tools/pull/4206#issue-2225083853))
So I tried to reinstall the extension.

After reinstall and reload vscode, I got weird view state of extension list.
Although I forgot to take screenshot, but both of activation time and "Install" button was shown like this:

<img width="66" alt="image" src="https://github.com/microsoft/vscode/assets/400558/f76f86e4-ab5b-4865-b3de-ed6e3e19af89">
<br />
<img width="56" alt="image" src="https://github.com/microsoft/vscode/assets/400558/0774e788-c0ce-4f2e-b995-2f7793cf2488">

Remove -> Reload -> Install -> Reload does not solve this.

I found both `.vscode/extensions/vue.volar-2.0.10` and `.vscode/extensions/vue.volar-2.0.12` are exists in my home directory. I `rm -rf`-ed both then reinstalled the plugin, and I got 2.0.10 installed. The "Install" button had been gone after this.

<img width="632" alt="image" src="https://github.com/microsoft/vscode/assets/400558/081ecaaa-6808-4a2c-b02c-180dda58304c">

**Comment by sandy081** [comment] 2024-04-25 10:28
@ypresto Looks like your issues is not related to the reported issue. I will request you to file a separate issue for yours with necessary steps to reproduce.

I am closing this issues as we have not received requested information. Please provide the requested information for reopening this.

Thanks.

**Closed by sandy081** 2024-04-25 10:28 UTC
Labels: info-needed
