### ISSUE TITLE
syntax highlighting on #ifdef <define name> 

### ISSUE THREAD

**Issue by 3DdeepAI** [Microsoft/vscode#72100] opened 2019-04-10 20:51 UTC
Issue Type: <b>Feature Request</b>

// C++ Code Highlighting
```
#if 1
   const unsigned int u = 0;
#endif

#if 0
   const bool this_is_commented = true;
#endif

//#define THIS_IS_A_TEST

#ifdef THIS_IS_A_TEST
   int r = 0;                // this line could be grayed
#endif

```
Please add simple Syntax highlighting for defined/undefined identifiers

![define_syntax_highlighting1](https://user-images.githubusercontent.com/28405357/55931014-27ee0880-5c24-11e9-9d3b-c558f5404734.jpg)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.14393

**Comment by alexr00** [comment] 2019-04-11 10:08
This is outside the capabilities of TextMate, which we use for syntax highlighting (See discussion in the C++ grammar here. Duplicate of #50140

**Closed** 2019-04-11 10:22 UTC
Labels: *duplicate
