### ISSUE TITLE
Use VS Code 3 Way Merge Editor as git merge tool

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153340] opened 2022-06-27 16:59 UTC
This should be supported:
```
git config --global merge.tool vscode
git config --global mergetool.vscode.cmd 'code --merge $BASE $LOCAL $REMOTE $MERGED'
```

So that in a case of a merge conflict
```
git mergetool
```

Can be used.

**Comment by jrieken** [comment] 2022-06-27 17:18
Yeah, that should be similar to the `--wait` command line flag that we already have

**Comment by bpasero** [comment] 2022-06-28 04:48
💯 

I think this is a duplicate of https://github.com/microsoft/vscode/issues/5770

This probably needs a combination of `--wait` on the result file and support to pass in an argument to enforce opening the merge editor. We do something similar with `--diff` so I would try to go from there: with `--diff` you pass in 2 paths and we end up opening a diff editor instead of opening the 2 paths as editors separately.

https://github.com/microsoft/vscode/blob/e7751367f79f327b8103bee33a07c16817a2c7cd/src/vs/platform/window/common/window.ts#L241

A little challenge is that merge editor is a `contrib` while handling of arguments currently does not have a contribution model so we might want to think about moving the merge editor to core or would have to add a hack to call a contributed command.

**Comment by joaomoreno** [comment] 2022-07-05 14:18
Let's use #5770 for this, so all those people get pinged.

**Closed by joaomoreno** 2022-07-05 14:18 UTC
Labels: feature-request, merge-editor, merge-editor-workbench
