### ISSUE TITLE
Cannot download a VSCode instance for testing

### ISSUE THREAD

**Issue by kysewtts** [microsoft/vscode#120171] opened 2021-03-30 11:53 UTC
While downloading a VSC instance from https://vscode-update.azurewebsites.net/api/releases/stable to run some tests, an error pops in with code 404. It says "Cannot GET /api/releases/stable"

**Comment by IllusionMH** [comment] 2021-03-30 12:21
/duplicate of #119822
See https://github.com/microsoft/vscode/issues/119822#issuecomment-806489621 for details and migration steps

**Closed** 2021-03-30 12:21 UTC
Labels: *duplicate
