### ISSUE TITLE
Better Support for ESNext

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/vscode#4078] opened 2016-03-13 03:56 UTC
At present, using ESNext features such as decorators, async/await, class instance fields, etc. results in the editor drawing red squiggles. In the very least, it would be nice if there was an easy way to stop VSCode from complaining about these features in a normal .js file.

Perhaps some thought needs to go into how VSCode will handle the evolution of ES in general. With developers using tools like Babel, and opting into stage-n features before they are finalized as a norm, I think this is going to crop up more and more. Not to mention that popular frameworks like Aurelia, React, Ember and Angular 2 are using these features more.

As for me, I have a hard time recommending VSCode to anyone that isn't doing TypeScript or sticking strictly to ES2015. It gets ugly pretty quick otherwise. I'm looking forward to seeing this improve. It's the only thing really holding me back. Thanks for all the great work so far!

**Comment by egamma** [comment] 2016-03-14 08:42
@EisenbergEffect thanks for the feedback.

>At present, using ESNext features such as decorators

Actually decorators are supported and you can enable them in the jsconfig.json pls see https://github.com/Microsoft/TypeScript/issues/6872#issuecomment-190288631

>async/await, class instance fields, etc. results in the editor drawing red squiggles.

We will add support for disabling the built-in diagnostics, pls see the discussion in  #3804 and I'm closing this issue in favor of this one.

**Comment by egamma** [comment] 2016-03-14 08:43
closing as a duplicate of #3804

**Closed by egamma** 2016-03-14 08:43 UTC

**Comment by EisenbergEffect** [comment] 2016-03-14 13:56
@egamma Nice to see you here :)
Thanks for looking into these features. Regarding decorators, it's actually broken on my VSCode instance with the latest release.

**Comment by egamma** [comment] 2016-03-15 11:37
@EisenbergEffect this works for me. Tested in 0.10.11:

Error without the `experimentalDecorators` property:

![image](https://cloud.githubusercontent.com/assets/172399/13776408/3cdbba6a-eaaa-11e5-9c4e-9eeee6030d81.png)

No error when `experimentalDecorators` is true:

![image](https://cloud.githubusercontent.com/assets/172399/13776422/4c9d5a12-eaaa-11e5-92f4-4ee6ef751c59.png)

**Comment by EisenbergEffect** [comment] 2016-03-15 12:16
Check this out:

![screen shot 2016-03-15 at 8 07 50 am](https://cloud.githubusercontent.com/assets/131485/13777242/42eaea86-ea85-11e5-99a9-b2a6d7ed9345.png)

One thing that is different from your example above is my folder structure. I have something like this:

![screen shot 2016-03-15 at 8 15 16 am](https://cloud.githubusercontent.com/assets/131485/13777373/294bb85c-ea86-11e5-9caf-897717a0fc9a.png)

**Comment by egamma** [comment] 2016-03-15 13:03
I also see that you have both a jsconfig.json and a tsconfig.json. Is it a mixed .js and .ts project? If yes then you can set allowJS to true in the tsconfig.json and then you can delete the jsconfig.json.

**Comment by EisenbergEffect** [comment] 2016-03-15 13:37
If I remove the tsconfig, the problem goes away :)

It's not a mixed project per se. I was working on a sample app for an Aurelia workshop I'm going to be running. I included the tsconfig because I suspect some students will want to use TS instead of Babel. So, it was there out of a convenience for them. However, I should probably provide them with a complete TS setup separate from this one. Having both clearly causes the issue and probably doesn't make sense.

Thanks!

**Comment by egamma** [comment] 2016-03-16 14:41
:+1: on separate .ts and .js setup.
