### ISSUE TITLE
Debug console does not stick to bottom of feed

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#136204] opened 2021-11-01 04:43 UTC
Issue Type: <b>Bug</b>

regularly the debug console stops autoscrolling. Launching the application gives a whole bunch of output messages. The console auto scrolls for a bit then stops, and i have to manually scroll to the bottom.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (4.51GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.92GB (2.09GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remote-containers|ms-|0.202.5
remote-wsl|ms-|0.58.4
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
restore-terminals|Eth|1.1.6
vscode-graphql|Gra|0.3.18
vscode-docker|ms-|1.17.0
vsliveshare|ms-|1.0.5065
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
prisma|Pri|3.3.0
indenticator|Sir|0.7.0
language-stylus|sys|1.13.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by roblourens** [comment] 2021-11-01 18:05
Hm, I haven't seen that. I wonder whether there is something different about messages that cause this, for example is the output logging expandable objects, or just plain text, or wrapping? Could you share a screenshot?

**Comment by Hadakajime** [comment] 2021-11-01 22:23
here i restart the debugger.
console has paused scrolling at this point:

![image](https://user-images.githubusercontent.com/20448845/139749740-59b85639-390f-4386-baa8-6aadb79a60f7.png)

the next message, after scrolling, is:

![image](https://user-images.githubusercontent.com/20448845/139749773-d602d193-1cd9-4c11-8f4f-99e2ab8ca214.png)

it will happen multiple times even if i manually scroll to the bottom.

**Comment by Hadakajime** [comment] 2021-11-01 22:26
for example, i restart the debugger again, then once the autoscroll fails the first time, i manually scroll to the bottom. It may follow the tail for a bit, but this is the next instance it stops following:

![image](https://user-images.githubusercontent.com/20448845/139750165-42791c50-cabe-4692-98cb-3d16933333a9.png)

the next message is:

![image](https://user-images.githubusercontent.com/20448845/139750188-4bb088b9-8257-4e04-acc2-d78b5dbfd675.png)

**Comment by roblourens** [comment] 2021-11-02 00:25
We do have https://github.com/microsoft/vscode/issues/117674 which sounds pretty relevant but I don't see wrapped text in your sample, is there wrapped text somewhere else?

**Comment by Hadakajime** [comment] 2021-11-02 06:27
No, as we can see in my screenshots above,  the debug console is quite wide (maybe around 1500px), and no wrapping is occurring due to a constrained width. 

Looks like it mostly happens with the "debugger attached" or "waiting for debugger to disconnect" messages.

**Comment by roblourens** [comment] 2021-11-03 03:34
@isidorn just wondering whether this sounds familiar to you

**Comment by isidorn** [comment] 2021-11-04 09:15
It only sounds familiar to #117674 which you already linked to.

**Comment by roblourens** [comment] 2021-11-04 16:55
I think this is probably a dupe of #117674 even though we don't see wrapped text here

**Closed by roblourens** 2021-11-04 16:55 UTC
Labels: needs more info, debug
