### ISSUE TITLE
Re-implement "open derived source" feature

### ISSUE THREAD

**Issue by Seikho** [Microsoft/vscode#3546] opened 2016-02-29 03:14 UTC
Hi team,

In the early days of VSCode, there was a feature that I adored that allowed me to open the compiled output of my TypeScript files. By simply right clicking the source `.ts` file and clicking `Open derived output` I could view my `.js` output.

This feature was pulled due to not being able to find the compiled output if it was in a different directory.
There are many workarounds for this, but none as effective as this feature. I would love to see this re-added.

Thanks

**Comment by mjbvz** [comment] 2018-03-08 05:44
Duplicate of #21018

**Closed by mjbvz** 2018-03-08 05:44 UTC
Labels: feature-request
