### ISSUE TITLE
VSCode 1.4.2 Explorer does not fully display content VSCode 1.4.1 Explorer can fully display content

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#88653] opened 2020-01-15 04:53 UTC
VSCode 1.4.2 Explorer does not fully display content
![VSCode 1 4 2](https://user-images.githubusercontent.com/27546390/72405836-34942400-3795-11ea-8ae6-2d2bec99a38d.png)
![VSCode 1 4 2](https://user-images.githubusercontent.com/27546390/72405863-5392b600-3795-11ea-931c-6d2845241ac8.png)

VSCode 1.4.1 Explorer can fully display content
![VSCode 1 4 1](https://user-images.githubusercontent.com/27546390/72405903-72914800-3795-11ea-8408-9992a3bbe28f.png)
![VSCode 1 4 1](https://user-images.githubusercontent.com/27546390/72405933-8ccb2600-3795-11ea-8aae-5e0b3a752482.png)
Do you see the problem? do you understand?
Hope you can fix it when VSCode 1.4.2 is released, thank you!

**Comment by deitry** [comment] 2020-01-15 08:30
I guess this is actually duplicate of https://github.com/microsoft/vscode/issues/88521

@395053994 Instead of creating similar issues, please try to reword problem accurately to make it clear and do this in the same issue. If my suggestion (https://github.com/microsoft/vscode/issues/88521#issuecomment-574545696) on your problem is right, please confirm it.

**Comment by isidorn** [comment] 2020-01-15 08:43
Yes, it is a duplicate, thanks!

**Closed** 2020-01-15 08:43 UTC
Labels: *duplicate

**Comment by 395053994** [comment] 2020-01-15 10:27
Your analysis is very correct. Thank you!
Just in VSCode 1.4.2 preview release Explorer does not fully display content
But Explorer can fully display content in the official release of VSCode 1.4.1
What is the cause of this? Will you fix it in time?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dmitriy Vornychev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 下午4:30
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] VSCode 1.4.2 Explorer does not fully display content VSCode 1.4.1 Explorer can fully display content (#88653)




I guess this is actually duplicate of #88521
 
@395053994 Instead of creating similar issues, please try to reword problem accurately to make it clear and do this in the same issue. If my suggestion (#88521 (comment)) on your problem is right, please confirm it.

**Comment by 395053994** [comment] 2020-01-15 11:03
See attachment ...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dmitriy Vornychev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 下午4:30
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] VSCode 1.4.2 Explorer does not fully display content VSCode 1.4.1 Explorer can fully display content (#88653)




I guess this is actually duplicate of #88521
 
@395053994 Instead of creating similar issues, please try to reword problem accurately to make it clear and do this in the same issue. If my suggestion (#88521 (comment)) on your problem is right, please confirm it.
