### ISSUE TITLE
 Uncaught Error: [UriError]: Scheme contains illegal characters.

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#93220] opened 2020-03-23 09:06 UTC
Issue Id: <b>c4f719ec-d13a-d06f-0d30-bc150f492d80</b><br /><br />*Versions* <br />- 1.43.1<br />-  e5834d3280fcd04898efeac32b9cf1b893f9b127<br />-  0eebaf9ad23748baca2afc0da425650922bc23de<br />*Stack* <br />Error: [UriError]: Scheme contains illegal characters.<br />[/vs/base/common/uri.ts#23:8 (this)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/common/uri.ts#L23:8 (this))<br />[/vs/base/common/uri.ts#171:16 ([object Object])](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/common/uri.ts#L171:16 ([object Object]))<br />[/vs/base/common/uri.ts#393:0](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/common/uri.ts#L393:0)<br />[/vs/base/common/uri.ts#268:9 (parse)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/base/common/uri.ts#L268:9 (parse))<br />[/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#301:14 (_getLinkHoverString)](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L301:14 (_getLinkHoverString))<br />[/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#120:71](https://github.com/microsoft/vscode/blob/fe22a9645b44368865c0ba92e2fb881ff1afce94/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L120:71)<br />    at o.tooltipCallback (\node_modules.asar\xterm\lib\xterm.js:1:177286)<br />    at t._onTooltip (\node_modules.asar\xterm\lib\xterm.js:1:199334)<br />    at \node_modules.asar\xterm\lib\xterm.js:1:199193<br />

**Comment by jmbockhorst** [comment] 2020-03-24 06:57
I believe it is a duplicate of #91479, which has a simple fix in #91615.

**Closed** 2020-04-06 11:55 UTC
Labels: bug, integrated-terminal
