### ISSUE TITLE
TS Server fatal error:  Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by MelvIsntNormal** [microsoft/vscode#134210] opened 2021-09-30 13:37 UTC
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.4.3

**Steps to reproduce crash**
1. Open VS Code
2. Open any `.ts` file

**Expected**: TS language service starts without issues
**Actual**: TS language service terminates unexpectedly

**TS Server Log**
[tsserver.log](https://github.com/microsoft/vscode/files/7259889/tsserver.log)

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:2064:20)
    at isNodeModulesOrScopedPackageDirectory (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19715:65)
    at guessDirectorySymlink (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19703:17)
    at processResolution (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19692:22)
    at /opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19683:162
    at Map.forEach (<anonymous>)
    at Object.setSymlinksFromResolutions (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:19683:123)
    at ConfiguredProject.Project.getSymlinkCache (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161084:35)
    at Object.getSymlinkCache (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114006:29)
    at Object.host.compilerHost.realpath (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114071:36)
    at realPath (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:41680:42)
    at Object.resolveTypeReferenceDirective (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:41044:74)
    at /opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162443:112
    at Object.map (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:455:29)
    at Function.AutoImportProviderProject.getRootFileNames (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162443:42)
    at Function.AutoImportProviderProject.create (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162475:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162277:77)
    at ConfiguredProject.Project.updateGraph (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161700:26)
    at ConfiguredProject.updateGraph (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:162644:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164368:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165451:44)
    at /opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:97
    at Object.flatMap (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:519:25)
    at ProjectService.applyChangesInOpenFiles (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:165791:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:166949:46)
    at /opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/opt/visual-studio-code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.61.0-insider (4fbe0344a0cedaf2a04edef728c9a3f27777cc6c, 2021-09-29T05:26:17.262Z)
OS version: Linux x64 5.14.8-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.53GB (10.79GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 51739e49-589a-4e68-807c-5b6e19939b01|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797

```

</details>

**Comment by IllusionMH** [comment] 2021-09-30 14:25
/duplicate of microsoft/TypeScript#44953

Fix should be available if you use https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next with night TS version

**Closed** 2021-09-30 14:26 UTC
Labels: *duplicate
