### ISSUE TITLE
open file dialog starts in wrong folder

### ISSUE THREAD

**Issue by blushingpenguin** [microsoft/vscode#216978] opened 2024-06-24 09:57 UTC
Type: <b>Bug</b>

- launch vs code and open a folder (e.g. code ~/project)
- open a file by clicking on a file in the explorer tree
- choose File->Open
- file dialog opens, but in the home directory (expect it to be the same directory as the previously opened file)

This is a regression -- doing the same thing with vscode 1.89.1-1715060508 results in the open file dialog starting in the same directory as the last opened file.

This behaviour is the same in the current insiders build (1.91.0-1719209898) and also with extensions disabled.

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:33:48.698Z)
OS version: Linux x64 6.5.0-41-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|62.47GB (42.71GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 25570409-2e66-4393-8933-423b4d356fa3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by rottmann** [comment] 2024-07-04 08:11
Electron problem, view https://github.com/microsoft/vscode/issues/213780

**Comment by lramos15** [comment] 2024-07-08 13:16
Duplicate of #213780

**Closed by lramos15** 2024-07-08 13:16 UTC
