### ISSUE TITLE
[folding] Spontaneous "Unfold All"

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [microsoft/vscode#137890] opened 2021-11-25 15:41 UTC
Issue Type: <b>Bug</b>

I had this problem before - you guys told me that it was probably a faulty plug-in.   I removed all the plugs-ins I could.  The problem seemed to go away -- and now it returned -- (VS Code just updated a few days ago).

I'll be working in a large file that is mostly folded and with normal acitvity -- the code suddenly does an "Unfold All" and just opens up the entire file.  This is infuritating because I have to do a "Fold All" and then open up the section that I'm working on all over again.  It is a miserable bug that I don't know how to reproduce.

I only have 3 plug-ins still running:

1) C/C++
2) C/C++ Extension Pack
3) Espressif IDF

There has to be a way to log a trail of activity on this to lock down the reason for this UI bug?

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.24GB free)|
|Process Argv|--crash-reporter-id 69d7eaf8-b6a9-48d5-a6a5-6a2c96b9c224|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
esp-idf-extension|esp|1.2.0
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.1.0

</details>

**Comment by PieterBranderhorst** [comment] 2021-11-27 05:56
I have a possible explanation of what is happening here.

When this happens do you know whether the "chevron" icons for folding also momentarily disappeared? It might be impossible to say if you don't have the "Editor: Show Folding Controls" option set to "Always".

It seems that when the folding "range provider" for the language returns a set of ranges which don't include a currently collapsed range then vscode uncollapses that range.

With the default typescript provider you can see this behaviour by opening some typescript code, folding a section of the code which doesn't include any /\* or */, and then typing "/\*" on a new line above the folded section. The folded section will unfold without you doing anything else.

So if a folding range provider temporarily omits some or all previously defined ranges from what it returns, folded ranges can pop back into view. In the worst case if the provider through some error occasionally returns an empty set of ranges then all current folds will be expanded.

I don't think this is desirable behaviour. Folding providers might be temporarily faked out by opening comments or quotation marks or deletions of comment ends or closing quotation marks. And they might have bugs which occasionally result in bad returned data. My preference would be that the current state of folds, i.e. the set of collapsed regions, be entirely divorced from what the folding range provider returns. Maintained separately and only uncollapsed by the user. This would create some potential conflicts when a calculated range overlaps a collapsed range but some rules of thumb could be invented to address those. On the plus side, removing a relationship between collapsed and foldable would enable adding a feature to allow users to select an arbitrary group of lines and fold them.

**Comment by aeschli** [comment] 2021-11-29 08:17
The example you mention (having `/**` but not `*/`for a short time) is in-deed a problematic case.
Keeping the folded ranges is tricky. I'm worried it can lead to very strange folding ranges sticking around.

The current approach is to always autocomplete `/**` with a `*/`, so that you don't end up commenting out a full document.

@SolidStateLEDLighting If you could pin this down to reproducible steps that would be great.

**Comment by SolidStateLEDLighting** [comment] 2021-11-29 08:24
I followed the suggestion from the first response -- I changed the setting to keep the chevrons in view in the left column.   I had a global unfold all happen once -- but I did not notice the chevrons disappearing before the expansion.

The second thing that I noticed is that this file has been taken from other code -- and it was full of /*     */ comments -- and I prefer all // comments.

So, I did find a few orphaned */ at the end of some of the comments that I had changed over.   I removed them.


I have had only one incident of "unfold all" happen since that point (when I copied and paste a variable into that file).

I'm trying to find reproducible occurrences of this problem -- but so far -- I don't see them.   I suspect most of the anomaly has gone away, a few more days working in that file will be more conclusive.

Keith


________________________________

**Comment by aeschli** [comment] 2021-11-29 08:53
It could also have been caused by a slow extension startup.
When VS Code starts up, it restores all previous folding ranges and waits around 10 seconds for the extension that provided these ranges to report ranges again.
If that takes too long, we give up and unfold the ranges. The problem is that we don't know if the extension will ever come alive (maybe it was disabled/uninstalled).
The fix for that would be on the extension side, to prioritize folding range requests without waiting e.g for validation to complete.

**Comment by SolidStateLEDLighting** [comment] 2021-11-29 09:05
I only have 3 plug-ins running... and my expansion problems happens at different times over many hours of working in the project.
________________________________

**Comment by SolidStateLEDLighting** [comment] 2021-12-06 01:19
After another week of testing -- I still have this problem.     The spontaneous unfold all happens when I click into the file and make it active.   Typically, this happens after I return back from working in another file.

The chevrons in the left column do NOT disappear before the action occurs.



________________________________

**Comment by Metalit** [comment] 2021-12-16 03:15
I've been having almost this exact issue as well relatively frequently, along with being unable to find a way to reproduce it on demand. C++ also, although I have a few more extensions.

**Comment by SolidStateLEDLighting** [comment] 2021-12-16 05:11
I continue to have this problem.

I mostly see it when I copy from another file first -- or when I change a variable manually in another file -- when click back over to my working area - then I get a full spontaneous expansion.
________________________________

**Comment by SolidStateLEDLighting** [comment] 2021-12-16 17:12
I just experience the problem again --- I copied from another file -- selected the tab of my working file -- hovered over the text without any action and 1 or 2 seconds later, the file unfolded all.

I am forced now to stop everything -- fold all -- and then unfold the areas that I'm working in again.

K.


________________________________

**Comment by SolidStateLEDLighting** [comment] 2021-12-16 21:24
I have a pattern....    If I copy a variable from an .hpp header file -- and just before I paste it into the corresponding .cpp file -- that file will unfold all.

It doesn't happen every time, but this is the circumstance where I see the automatic expansion occur.

Incidentally, this is involves pasting into a switch statement.  (I do a lot state transition work with switch/case statements)
________________________________

**Comment by PieterBranderhorst** [comment] 2021-12-17 08:49
That the problem happens after switching back to the code from another file is significant. That's a time when collapsed state information is reloaded from a save area and then resynchronized with the folding range provider. (C++ specific extension in this case.)

It seems to me that the key to the problem is that vscode discards collapsed regions when they aren't present in a set returned by the range provider. That could be triggered by a bug in either vscode or the range provider. Perhaps a subtle timing bug. Regardless of the exact cause I think the solution should be to hold onto already collapsed regions regardless of what the range provider returns.

I understand the concern about that being tricky. But not doing it seems wrong. Not just for this case and not just to allow for errors in range providers. Even when there are no bugs the current approach causes all collapsed regions below a line where we temporarily delete an end-of-comment to unfold.

I'm not on the vscode team. But I'm digging into the code to see if I can propose a fix which Microsoft might accept. I'm thinking that it will include adding a small checksum to folding memento's to ensure that what gets collapsed on restarts is what the user intended.

**Comment by aeschli** [comment] 2021-12-17 10:09
So yes, I suspect it's the cpp folding provider not being consistent, or too slow. Adding traces could be a first  good step to understand that.
@PieterBranderhorst Your help is very welcome and if you want to give it a try with keeping the folded ranges longer, I'd love to see such a solution

**Comment by SolidStateLEDLighting** [comment] 2021-12-18 15:16
Another case.

I had just returned from editing the hpp to the cpp of the same class --- and had my mouser point over the terminal window to "control click" and vector to an error in the cpp.  When I touched the ctrl button, it triggered an unfold all.   I had not even clicked into the cpp file yet.


________________________________

**Comment by SolidStateLEDLighting** [comment] 2021-12-20 23:52
Another case...

I just copied and pasted a section of code in a single .cpp file.   The unfold all triggered when I did a right moused click and selected "format document".   The document formatted and then expanded all.

Incidentally, I copied and pasted inside a case and switch statement which I expanded manually before that operation.

This is a massive headache.  I now have to fold all and re-expand my working area again... .and again... and again.
________________________________

**Comment by PieterBranderhorst** [comment] 2021-12-22 04:17
@aeschli I'm working on it. Of course this won't fix the underlying issue which is probably in the C++ range provider but it will make vscode's folding tolerant of such issues in range providers. I'm adding a command (ctrl K + ctrl .) to fold a selected range of lines at the same time rather than later because it will make testing this change easier.

**Comment by SolidStateLEDLighting** [comment] 2021-12-22 08:35
New info -- When I pasted code into the center of a switch statement -- I realized now that I was missing a bracket.    So, I can understand if the code expanded on that switch statement and beyond in protest of the error.   The parser should probably expand out all the code it thinks in involved with an error -- but that should have not include any code before that error.
________________________________

**Comment by PieterBranderhorst** [comment] 2021-12-27 01:03
I've finished code which should fix this issue and have submitted a pull request.

@aeschli You can look at the code I'm proposing in #139779.

**Closed** 2022-07-25 19:22 UTC
Labels: editor-folding, on-testplan
