### ISSUE TITLE
Search and replace (in multiple files), the replacement text input box lost the scrollbar and hides the rest of the search-and-replace options/output

### ISSUE THREAD

**Issue by jihu** [microsoft/vscode#105421] opened 2020-08-26 13:42 UTC
- VSCode Version: 1.48.2
- OS Version: Windows 10

I often use the search and replace feature (the one where you search for files in the whole project), and often replace content in multiple lines in one go. Earlier this caused no problem. If the search text or replacement text was long, the box just got a scrollbar. But recently (not sure exactly from what version) the replacement text box never gets a scrollbar, no matter how long the text is, and no matter if the replacement text is one long line or multiple lines. So if the replacement text is too long (I often do this with 50-100 lines) the replacement text box takes up all available space. This makes it impossible to access the rest of the configuration (like files to include), as well as the search results.

Steps to Reproduce:

1. Input a long text into the search replacement text box on the main search (not the in-editor-search). Try about 50-100 lines of regular text.
2. Notice that the other input boxes under the search replacement box, as well as the search results, are hidden and inaccessible

Does this issue occur when all extensions are disabled?: Yes

**Comment by jihu** [comment] 2020-08-26 13:49
I would say that [ticket #64311](github.com/microsoft/vscode/issues/64311) ("Search: find, replace input boxes miss scrollbar") is describing the same problem, but since that ticket hasn't been touched since 2018 and my problem only happened recently (say in some version release the last few months) I would say that this ticket is not a duplicate of that ticket.

**Comment by roblourens** [comment] 2020-09-01 18:04
Can you share a screenshot so I'm clear on the issue? This works for me. It should hit a max height of like 250px and be scrollable after that (but with no scrollbar)

**Comment by jihu** [comment] 2020-09-02 06:36
Sure thing.
Replacement with 60 lines:
![image](https://user-images.githubusercontent.com/5556460/91939958-fbde9600-ecf6-11ea-8c57-3875d9e9a5c4.png)

Replacement with 70 lines:
![image](https://user-images.githubusercontent.com/5556460/91940144-48c26c80-ecf7-11ea-8ed0-d7ce6613fe10.png)

**Comment by roblourens** [comment] 2020-09-10 17:58
So strange! Are you pasting the text in or typing and inserting newlines?

**Comment by jihu** [comment] 2020-09-10 18:05
Most of the time I paste content, but now I tried inserting newlines using Shift+Enter, and the result was the same.

**Comment by roblourens** [comment] 2020-09-12 22:48
Are you using an IME or international keyboard?

Otherwise all I can ask is for you to try debugging it, if you are up for it.

- Help > "Toggle developer tools"
- Open the Sources tab
- ctrl+p, type "inputbox.ts" and open that file
  - You may have to wait a minute for devtools to load the sources
- Set a breakpoint at the top of the `layout()` method and resize the sidebar horizontally to trigger it

![image](https://user-images.githubusercontent.com/323878/93006279-e1d75b80-f51f-11ea-9a3f-a3efb5a4aa1a.png)

What _should_ happen is that we compute some large height for the input, then reduce it based on maxHeight. It's possible that maxHeight doesn't get initialized properly or that something goes wrong inside this function. But I can't imagine what the problem is. You can also find the textarea element and see whether it has a height set on it at all.

**Comment by Simran-B** [comment] 2020-09-15 11:26
Same problem here, the search box has a limited height and can be scrolled with the mouse wheel, but not the replace box. VSCode v1.49.0 on a German Windows 10 with standard German keyboard settings:

![image](https://user-images.githubusercontent.com/7819991/93202289-bd16fa00-f752-11ea-89eb-82d42985ba8e.png)

I set the breakpoint on line 572 and dragged the sidebar. In the local scope pane, I find the following values:

- previousHeight: undefined
- this: t.historyInputBox
  - cachedContentHeight: 654
  - cachedHeight: 134
    - element:
      - clientHeight: 134
      - offsetHeight: 136
  - maxHeight: 134
  - height: 134

Stepping through the layout code, previousHeight gets set to 654, cachedContentHeight as well (same as before). Then there is a second call to layout() where it's 600 and here:

    this.cachedHeight = Math.min(this.cachedContentHeight, this.maxHeight);

maxHeight is Infinity. That doesn't seem right?

The textarea ends up with an inline `style="height: 600px"`. If I manually change that to 134px, then it has a proper height limit and is scrollable.

**Comment by roblourens** [comment] 2020-09-15 20:43
Thanks for checking that @Simran-B. I guess my reading comprehension is not good because I missed that this was just about the replace input, not the search input. Should be fixed now.

**Closed** 2020-09-15 20:42 UTC
Labels: bug, search

**Comment by Simran-B** [comment] 2020-09-16 14:53
Thank you @roblourens, just tested the fix with insiders build 9e505675670d65138405321a60b0df4ddec28799 and I can confirm that it's working as expected now.
