### ISSUE TITLE
TreeView pagination

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#55983] opened 2018-08-08 06:11 UTC
Issue Type: <b>Feature Request</b>

I am developing an extension using `TreeView` to show list data.

I have to request and get data from API.

and there is the problem: **How to pagination in the tree view?**

after all. I don't need to request and get all item.

should I implement an empty tree view item for click and get next page or will the official support it?

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

->

**Comment by sandy081** [comment] 2018-08-13 11:07
Duplicate of #34151

**Closed by sandy081** 2018-08-13 11:07 UTC
Labels: *duplicate, explorer-custom
