### ISSUE TITLE
In language C, the absence of blank lines between #if 0 and #endif can cause syntax highlighting issues.

### ISSUE THREAD

**Issue by StarainGan** [microsoft/vscode#196670] opened 2023-10-26 03:38 UTC
Type: <b>Bug</b>

An exception occurs in my code when the following precompiled code appears, which causes all subsequent code to be incorrectly identified as a comment:

1. A comment starting with "//" appears after '#if 0'

2. #if 0 and #endif have no blank lines

```C
#if 0 //some notes
#endif
func1();
func2();
```

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.23565
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (6.32GB free)|
|Process Argv|D:\\WinFile\\Desktop\\T5L51-master-20230913 --crash-reporter-id 12cc6299-cad1-4491-b698-f581c052498c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|3.1.7
todo-tree|Gru|0.0.226
hex-fmt|ker|1.0.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.83.2023101109
hexeditor|ms-|1.9.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859726
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by alexr00** [comment] 2023-11-16 10:41
Duplicate of upstream issue: https://github.com/jeff-hykin/better-c-syntax/issues/4

**Closed by alexr00** 2023-11-16 10:41 UTC
