### ISSUE TITLE
CLI can't use stdin in Windows

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#59481] opened 2018-09-26 18:48 UTC
Issue Type: <b>Bug</b>

1. Install an outdated extension by VSIX
2. Using CLI, attempt to update that extension using `--install-extension <extension-id>`
:bug: => Fails and reports "Unknown stdin file type"

Example
```
PS C:\Users\UserName\Source\vscode> code-insiders --install-extension C:\Users\UserName\Downloads\Go-0.6.87.vsix
Extension 'Go-0.6.87.vsix' was successfully installed!
PS C:\Users\UserName\Source\vscode> code-insiders --install-extension ms-vscode.go
Unknown stdin file type
```

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:32:21.753Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment] 2018-09-26 21:57
This is happening only on windows and also on stable.

@joaomoreno Prompts are not working in CLI.

**Comment by sandy081** [comment] 2018-09-26 22:02
@bpasero Could be an Electron issue?

**Comment by bpasero** [comment] 2018-09-27 05:43
Not sure, never seen that.

**Comment by joaomoreno** [comment] 2018-09-27 07:50
Definitely sounds Electron.

**Comment by joaomoreno** [comment] 2018-09-27 08:27
Yup, this seems to be a regression of either Electron or of some changes in cli.

@bpasero What were the changes to stdin wrt Electron 2?

**Comment by bpasero** [comment] 2018-09-27 08:49
@joaomoreno dunno, you will have to figure it out. Might be a node.js change: https://github.com/nodejs/node/blob/master/CHANGELOG.md

**Comment by joaomoreno** [comment] 2018-09-27 08:51
@bpasero Yeah let me try that.

**Comment by joaomoreno** [comment] 2018-09-27 08:59
Repros in exploration build (Electron 3).

**Comment by joaomoreno** [comment] 2018-09-27 09:42
This is not Electron related. Seems to be broken at least since 1.21.

We need to steer away from using Electron to develop our CLI and find an alternative way to do this. Shipping our own CLi handler would do the trick, we could have a very fast CLI handler which has total control over stdio and can return simple CLI requests very very fast.

Moving to backlog.

**Comment by sandy081** [comment] 2018-09-27 09:54
We can also avoid using prompts in CLI until then and use `--force` to override.

**Closed** 2018-12-03 14:52 UTC
Labels: bug, cli, windows

**Comment by sandy081** [comment] 2018-12-03 14:53
Removed the prompts and use `--force` option to update or downgrade the extension.
