### ISSUE TITLE
Sometimes, the contents of a specific directory don't appear, even though VSCode recognizes the directory as non-empty

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#77821] opened 2019-07-23 14:46 UTC
I have no idea what's causing this issue, so I will provide as many details as possible as I don't know for certain what is relevant or not:

### Background
I have a Python workspace defined by a `.code-workspace` file that contains one directory (folder) with several files and subfolders. In that folder is a folder called `modules`. This folder contains no individual files, just several folders, each containing a single Python module that is installed on my machine in "[editable](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs)" mode with Pip. 

Here's the file structure in a more visual form:

* workspace
  * .vscode
  * folder
    * Python files that depend on modules A, B, and C
  * modules
    * module_a
      * .git
      * \_\_pycache\_\_
      * module_a
      * module_a.egg-info
      * setup.py
      * other files
    * module B
      * same as module A
    * module C
      * same as module A
  * other files

### Problem
This `modules` folder is _usually_ unable to be expanded in the VSCode directory tree. I say "usually" because sometimes it works just fine, but typically it does not. It doesn't behave like an empty folder - I can still toggle the small triangle next to the folder (see screenshot). However, nothing happens when I do that.

![screenshot showing the modules folder with an 'expanded' folder icon but no files below it](https://user-images.githubusercontent.com/2294248/61720701-47252780-ad35-11e9-8611-bcc61f8d2d8d.png)

Because I have code that depends on code in that folder, I _can_ <kbd>ctrl</kbd>+click on a method imported from one of those modules and VSCode will open that file. This does not cause the folder in the directory tree panel to work properly, however, I can then access the contents of the `modules` folder by using the breadcrumbs:

![screenshot showing the contents of the modules folder expanded in the breadcrumbs widget](https://user-images.githubusercontent.com/2294248/61721096-ec400000-ad35-11e9-9f68-44dba057b1cd.png)

### Other Notes

1. If I create a new file in the folder (by right-clicking the folder and clicking "New File"), that file appears until I close the editor tab that opened when creating that file. Then it disappears even though it dos exist on the disc.
2. Nothing happens if I attempt to rename the folder (though this could be because Pip is preventing it as it would break imports).
3. If I copy and paste the folder (creating `modules copy`) the new folder works fine.
4. Reloading the window does not make a difference.
5. Reloading with extensions disabled does not make a difference.
6. This has been happening since I first set up this project approximately a month and a half ago. I've been on Insiders the entire time, and that doesn't imply the issue didn't exist before that as I never tried this before then.

### System Information
Version: 1.37.0-insider (user setup)
Commit: e1d3dd53d17fb1529a002e4d6fb066db0a0bd385
Date: 2019-07-23T05:23:48.960Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by isidorn** [comment] 2019-07-31 10:55
Looks like a duplicate of https://github.com/microsoft/vscode/issues/76031
Can you please put your info there (maybe in a more concise fashion)
Getting exact repro steps would be great

**Closed** 2019-07-31 10:55 UTC
Labels: *duplicate, file-explorer
