### ISSUE TITLE
Secondary side bar actions can move out of view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147902] opened 2022-04-22 07:27 UTC
![Recording 2022-04-22 at 09 27 05](https://user-images.githubusercontent.com/900690/164627502-e255043d-2921-4426-94f8-b37b8d3e5f19.gif)

**Comment by sbatten** [comment] 2022-04-22 16:18
essentially a duplicate of https://github.com/microsoft/vscode/issues/87347

**Closed by sbatten** 2022-04-22 16:18 UTC
Labels: bug, layout
