### ISSUE TITLE
Go to definition is not working 

### ISSUE THREAD

**Issue by DinkarSingh** [microsoft/vscode#107514] opened 2020-09-26 19:18 UTC
Issue Type: <b>Bug</b>

In my VS code I am not able to go on defined method is not displaying (even F12 is not working)

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.55GB free)|
|Process Argv|--crash-reporter-id a8dd6646-ed33-4816-96b7-86beadf2dce5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.0.1
java|red|0.67.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>

**Comment by Its0nlyFuN** [comment] 2020-09-26 22:02
I am having the same issue in C++. If I create a simple class in a header and source file and include/use it in my main.cpp I am not able to go to the definition of, for example, a class method. There is nothing more to add to this. I just installed it on arch using pacman. It's the standard configuration, without anything being changed. IntelliSense for c++ does work (for example auto-complete).

**Comment by mjbvz** [comment] 2020-09-28 18:58
@DinkarSingh What language is this for? Please provide steps to reproduce the issue

/needsMoreInfo

**Comment by DinkarSingh** [comment] 2020-09-30 07:10
I'm using javascript and even I have tried with java too but Go to function is not working. Well, I have simply open the vs code and write the javascript code but I'm not able to map the method (Go to function). Please if you have any solution please let me know I have tried to install lower version of vs code too but result remain same.

Thank You.
Best Regards,

Dinkar Singh KARANVANSHI
Mob : (+33) 6 29 25 48 28
skypeId: dinkarsingh3
LinkedIn : <https://fr.linkedin.com/in/dinkar-singh-k-46193670> https://fr.linkedin.com/in/dinkarsinghk<https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile>
________________________________

**Comment by mjbvz** [comment] 2020-10-14 07:47
Please share the example javascript code you are using

**Comment by DinkarSingh** [comment] 2020-10-14 09:08
Hello Matt,

I am sending my code Screenshot and I would like to tell you that when I right click on my method I can see the go to definition method.

Thanks a lot.

Thank You.
Best Regards,

Dinkar Singh KARANVANSHI
Mob : (+33) 6 29 25 48 28
skypeId: dinkarsingh3
LinkedIn : <https://fr.linkedin.com/in/dinkar-singh-k-46193670> https://fr.linkedin.com/in/dinkarsinghk<https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile>
________________________________

**Comment by mjbvz** [comment] 2020-10-14 09:11
Please use GitHub to post replies. Attachments don't work and your emails replies are posting your contact info, including phone number, publicly

Also instead of posting screenshots, share the code as text

**Comment by DinkarSingh** [comment] 2020-10-14 09:15
Hi,

Okay fine here is the my code.

var arr = [70,115,15,30];
var max = arr[0];
for (i=0; i< arr.length; i++){
    if(arr[i] >= max){
        max = arr[i];
    }
}
console.log(max);

var func = function(){
    console.log('Hello');
}

func();


Thank You.
Best Regards,

Dinkar Singh KARANVANSHI
Mob : (+33) 6 29 25 48 28
skypeId: dinkarsingh3
LinkedIn : <https://fr.linkedin.com/in/dinkar-singh-k-46193670> https://fr.linkedin.com/in/dinkarsinghk<https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile>
________________________________

**Comment by mjbvz** [comment] 2020-10-14 19:17
What doesn't work? Where are you pressing f12?

(And again, don't use email to reply because it's posting your phone number and contact info publicly)

**Comment by mjbvz** [comment] 2020-10-20 03:36
Closing as not actionable without more information about how to reproduce this

**Closed by mjbvz** 2020-10-20 03:36 UTC
Labels: needs more info
