### ISSUE TITLE
Go Back & Go Forward key step.

### ISSUE THREAD

**Issue by shenguanjiejie** [microsoft/vscode#172750] opened 2023-01-30 04:10 UTC
![image](https://user-images.githubusercontent.com/900690/179468382-e473acd2-f105-4f97-9e3d-c16083de7748.png)

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/155457#issuecomment-1186886857_
            
I have used "Go Back in Navigation Locations" for six months. Poor experience! 
I go to the definition using "command + left click", then "Go Back in Navigation Locations" often back to the wrong location. and "Go Forward in Navigation Locations" does not work. 

If anyone has used Xcode, hope vscode can have "Go back" & "Go forward" like Xcode. Thanks All.

**Comment by bpasero** [comment] 2023-01-30 04:52
What are the steps that show the issue you see?

**Comment by shenguanjiejie** [comment] 2023-01-30 07:18
https://user-images.githubusercontent.com/9425605/215408830-948697ee-037d-431b-92b2-b2ba3af77128.mp4


In this video, "command + control + Z" == "Go Back in Navigation Locations", "command + control + X" == "Go Forward in Navigation Locations"  I wanna this pipeline:

"command + left click" Debug -> Debug definition; 
"command + left click"  Sprintf -> Sprintf definition

"command + control + Z" Sprintf definition -> Sprintf
"command + control + Z" Sprintf -> Debug

"command + control + X" Debug -> Sprintf
"command + control + X" Sprintf -> Sprintf definition

Why does vscode jump to AddFields method when I "command + control + Z"?

**Comment by bpasero** [comment] 2023-01-30 18:53
Yeah this is strange. Is it possible for me to debug on the same sources, so that I can follow along the video as you did?

Btw to rule out any keybinding issues, can you use the command palette to pick the "Go back in navigation locations" command?

**Comment by shenguanjiejie** [comment] 2023-02-01 08:55
I have used the command palette to pick the "Go back in navigation locations" command.
It works well.

So it might be a keybinding bug.

**Comment by bpasero** [comment] 2023-02-01 08:56
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by shenguanjiejie** [comment] 2023-02-01 09:07
I have tried. I open a project without extensions, it can not jump to the definition of the method when I "command + left" click.

**Comment by shenguanjiejie** [comment] 2023-02-01 09:14
And I have changed the keybinding of "Go back in navigation locations" to "command + control + left arrow", not work for me.

**Comment by bpasero** [comment] 2023-02-01 09:35
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2023-02-01 10:24
I wonder if it is related to the keybinding picked, can you do different ones to see?

**Comment by shenguanjiejie** [comment] 2023-02-01 10:26
https://github.com/microsoft/vscode/issues/172750#issuecomment-1411713941 I have tried. not work.

**Comment by bpasero** [comment] 2023-02-02 06:24
Oh, I actually found a real regression while testing your flow: https://github.com/microsoft/vscode/issues/173109

However, I think you are not hitting that regression so the fix for it will not help you I believe.

Even after my fix, I tried to reproduce what you see in other sources using keyboard shortcuts and was not able to. So I still would need help how to reproduce your setup with your sources and extensions.

**Comment by shenguanjiejie** [comment] 2023-02-03 02:44
This are my extensions:

[vscode_extensions.sh.zip](https://github.com/microsoft/vscode/files/10575108/vscode_extensions.sh.zip)

All of my project have this problem, so I guess it is not about my code, any project of Golang can be test this bug.

**Comment by bpasero** [comment] 2023-02-03 05:51
I would still like to test on the same code you shared in your video for ease of reproduction.

**Comment by shenguanjiejie** [comment] 2023-02-06 08:50
I test again with my open source project "workwork":
https://github.com/shenguanjiejie/workwork

I used the command palette to pick the "Go back in navigation locations" command.
It has this bug too.

You can clone [workwork](https://github.com/shenguanjiejie/workwork) for the test.

https://user-images.githubusercontent.com/9425605/216926467-1073cc29-b3ba-4890-a934-d85955212e84.mp4

**Comment by bpasero** [comment] 2023-02-06 08:58
@shenguanjiejie did you test with the latest VS Code insiders version where my fix is included? Because if you try with stable it would suffer from the issue https://github.com/microsoft/vscode/issues/173109 which is only fixed in insiders.

**Comment by bpasero** [comment] 2023-02-06 09:30
I played around with the sources and it seems fine for me:

![Recording 2023-02-06 at 10 29 33](https://user-images.githubusercontent.com/900690/216935675-e869e860-ca79-4615-bdf0-3ace8a7e67be.gif)

**Comment by shenguanjiejie** [comment] 2023-02-06 11:20
https://user-images.githubusercontent.com/9425605/216958625-e49d45f8-7220-4e4e-82c0-479212d3facd.mp4

Only installed Go extensions.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/9425605/216958763-353632e0-9ef1-4f0d-8592-aba0618c951b.png">

**Comment by bpasero** [comment] 2023-02-06 11:54
@shenguanjiejie that looks decent to me. but maybe the confusion here is that you do not expect the source of a navigation to appear in the navigation?

To explain how it works: when you ctrl+click goto definition on a symbol, we actually add 2 entries to the navigation history, one for the origin and one for the target.

**Comment by shenguanjiejie** [comment] 2023-02-06 12:10
I just hope it can be easy to use. 
In the last video I recorded. I can not back to "tools.Slogln(err)", the beginning of all the steps.
I hope the pipeline just include key step as this comment : https://github.com/microsoft/vscode/issues/172750#issuecomment-1408107118

All in all, Just "goto & back". 
Thank you very much.

**Comment by shenguanjiejie** [comment] 2023-02-06 12:38
When we learn with a project, we often should ctrl+click goto definition many times. then I want to go back to the beginning of I'm seeing the code line with the shortcut key, rather than using the mouse.

**Comment by bpasero** [comment] 2023-02-06 13:19
I am sorry I cannot reproduce. It is also quite time consuming for me having to figure out what you do exactly from the video. If you have steps in text I can follow and then see an issue, we can reopen this issue.

**Closed by bpasero** 2023-02-06 13:19 UTC
Labels: info-needed, workbench-history
