### ISSUE TITLE
"source control repositories" about auto hide function.

### ISSUE THREAD

**Issue by zszen** [microsoft/vscode#179343] opened 2023-04-06 02:15 UTC
Type: <b>Feature Request</b>

Can you support git "source control" list (multi project in one workspace) auto hiden feature. It can hide when git sync done. And it show when some local changed.

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by vvkdev** [comment] 2023-04-11 18:32
#120250

**Comment by vvkdev** [comment] 2023-04-11 18:39
Duplicate of #120250

**Closed** 2023-04-26 15:23 UTC
