### ISSUE TITLE
Ridiculously slow at handling files without line breaks (e.g. minified js, css...)

### ISSUE THREAD

**Issue by coolheinze** [Microsoft/vscode#17528] opened 2016-12-19 10:54 UTC
- VSCode Version: 1.8.0
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open a minified file
2. Try stuff like scrolling, select all, paste...

**Comment by coolheinze** [comment] 2016-12-19 10:54
Particularly bad when more files are open

**Comment by egamma** [comment] 2016-12-19 15:54
This looks like a duplicate of #17208, that will be addressed in 1.8.1.

**Closed by egamma** 2016-12-19 15:54 UTC
Labels: duplicate
