### ISSUE TITLE
The Work Space UI BUG

### ISSUE THREAD

**Issue by DiogerChen** [microsoft/vscode#92847] opened 2020-03-17 13:41 UTC
Issue Type: <b>Bug</b>

When I remove the only one filefolder from the work space, there will be no folders in it and show "No opened folders". The work space tab will be **auto-closed** but the **UI below the work space tab** will **still show**, which let me add a folder into the work space. Then the UIs will be in a mess with the tabs under work space.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (11.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
matlab-formatter|Aff|2.4.12
code-gnu-global|aus|0.2.2
rainbow-highlighter|cob|0.0.9
lex-flex-yacc-bison|fau|0.0.3
gc-excelviewer|Gra|2.1.34
vscode-power-mode|hoo|2.2.0
crane|Hvy|0.3.8
csharpextensions|jch|1.3.1
rainbow-end|jdu|0.7.5
mips|kda|0.0.5
vscode-sshfs|Kel|1.16.3
csharpfixformat|Leo|0.0.84
vscode-language-pack-zh-hans|MS-|1.43.7
csharp|ms-|1.21.14
mssql|ms-|1.9.0
python|ms-|2020.2.64397
remote-containers|ms-|0.106.0
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-ssh-explorer|ms-|0.50.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.27.0-insiders3
Go|ms-|0.13.1
veriloghdl|msh|1.0.4
indent-rainbow|ode|7.4.0
java|red|0.58.0
pdf|tom|0.5.1
vscodeintellicode|Vis|1.2.6
rainbow-tags|vol|0.3.1
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1
vscode-icons|vsc|10.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by isidorn** [comment] 2020-03-17 17:11
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

If yes please attach a picture since I have no clue what you are talking about

**Comment by DiogerChen** [comment] 2020-03-17 18:32
I'm sorry for committed the issue without a picture because I don't know how to add a picture at first.
When I remove a folder, the tab "NO FOLDER OPENED" sometimes **closed**. There will be two "Open Folder" button showing. This picture is not the reproduction of the bug but modified by me because I can't reproduce successfully, just want to show you what I saw.
![20200318021511](https://user-images.githubusercontent.com/32814028/76889110-f9f75680-68bf-11ea-843f-e04ae915b706.png)

And this is the normal situation:
![20200318021529](https://user-images.githubusercontent.com/32814028/76889266-4347a600-68c0-11ea-99d9-2b50fe6de0c1.png)

I have met this bug twice in recent two days. I will show you if I meet again.

**Comment by isidorn** [comment] 2020-03-17 18:37
This should be fixed in latest insiders, are you sure you are on latest?
Also please try to find exact reproducable steps. Thank you!

**Comment by DiogerChen** [comment] 2020-03-17 18:51
Maybe you fix the bug in insiders, I can't reproduce it.
I just see it again on VScode(not insider), just open it, without any operations (This is the picture of UI with Chinese (Simplified) Language Pack):
![20200318023838](https://user-images.githubusercontent.com/32814028/76890562-93276c80-68c2-11ea-9bd4-6bc3fa767e3b.png)

And I am sorry for the mistakes in my memory, there is only one "Add Folder" button.
If this bug fixes in insiders, the issue comment can be closed soon. Sorry to bother you, have a nice day!

**Comment by isidorn** [comment] 2020-03-18 08:25
Yes, it hsould be fxied in insiders. Thus closing.
Sorry for the issue, and if it is blocking you please use VS Code insiders.

**Closed by isidorn** 2020-03-18 08:25 UTC
Labels: file-explorer, needs more info
