### ISSUE TITLE
Can’t scroll in Notebooks on iPad if cursor looses focus

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#131736] opened 2021-08-26 18:15 UTC
Does this issue occur when all extensions are disabled?: N/A

Version: 1.60.0-insider
Commit: b71e20ceba833fcb2efada1a4765929ff96ccbb1
Date: 2021-08-26T05:12:47.321Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15

Steps to Reproduce:

1. Click on a notebook (in my case the endgame notebook in the vscode repo)
2. Attempt to scroll. It doesn't work
3. Click in a code cell
4. Scroll works
5. Now scroll all the way down so that the cursor is off screen and wait a sec
6. Scroll doesn't work anymore

Here's a video... the long pauses are when I was trying to scroll:
https://user-images.githubusercontent.com/2644648/131014266-0a8669e0-93e7-4f6f-bf2a-a212b19a2021.MOV

**Comment by rebornix** [comment] 2021-08-30 21:27
@TylerLeonhardt are you able to scroll in other list views?

**Comment by TylerLeonhardt** [comment] 2021-08-31 00:48
nice catch @rebornix. I am unable to scroll in the settings editor either... unless I have focus in the "Search settings" box.

cc @roblourens

**Comment by isidorn** [comment] 2021-09-03 08:51
Might this be a duplicate of https://github.com/microsoft/vscode/issues/126212

**Closed** 2021-09-26 11:25 UTC
Labels: needs more info, ios-ipados, notebook
