### ISSUE TITLE
Debug: on break should focus the editor

### ISSUE THREAD

**Issue by felipeek** [microsoft/vscode#118493] opened 2021-03-09 01:09 UTC
- VS Code Version: 1.54.1
- OS Version: Ubuntu

Steps to Reproduce:

1. Set a breakpoint
2. Open a windowed application that disables the cursor in debug mode
3. Breakpoint hit

I have a hard time debugging applications that disable the OS cursor (when locking it to the application camera, for example), because Visual Code does not restore the cursor automatically when the breakpoint is hit.

**Comment by isidorn** [comment] 2021-03-09 08:47
We would need electron support to re-enable the cursor.
@deepak1556 might there be such an electron option?

**Comment by weinand** [comment] 2021-03-09 08:52
@isidorn Just setting a cursor in VS Code is not enough?

**Comment by isidorn** [comment] 2021-03-09 10:42
@weinand aha, now I fully understand this request.
It is on breakpoint hit to focus the editor (thus making the cursor visible).
However I would not change that, since editor stealing focus on breakpoint hit might not be the best accessibility experience.
If more users request for this we can introduce an option.

**Comment by weinand** [comment] 2021-03-09 14:38
@isidorn In the previous comment you said:
> since editor stealing focus on breakpoint hit might not be the best accessibility experience

but today when debugging an application (e.g. a VS Code extension), on hitting a breakpoint the focus moves from the debuggee to the debugger. So we are already "stealing focus" (an we have no setting for this, right?)

Shouldn't this be the default behavior in all breakpoint-hitting cases?

**Comment by weinand** [comment] 2021-03-09 14:54
@isidorn this is not true as the following screen recording shows

![2021-03-09_15-52-19 (1)](https://user-images.githubusercontent.com/1898161/110489363-a0e78a80-80ef-11eb-9862-6698e2c2a097.gif)

The focus is transferred to the debugger while typing in the debuggee.

**Comment by isidorn** [comment] 2021-03-09 14:58
You are right, we actually do focus it. We can stop doing it.
However it is configurable via `debug.focusWindowOnBreak` setting so users can configure this behaviour.

**Comment by isidorn** [comment] 2021-03-09 15:18
Anyways I am open to change this, let me know if you have suggestions.

**Comment by weinand** [comment] 2021-03-09 15:23
So if this issue's author has set "debug.focusWindowOnBreak" to true, VS Code's debugger should get the focus and a cursor that was disabled in the debuggee, should become visible again.

So the remaining questions are:
- does VS Code correctly receive the focus and if this is the case,
- why does electron not re-enable the cursor (bug or by design).
- and if this is in fact a bug of Electron, could we find a workaround, e.g. forcing a cursor change by always setting the cursor when hitting a breakpoint and receiving "focus gained".

**Comment by felipeek** [comment] 2021-03-13 21:21
@weinand @isidorn Thanks for jumping into this issue. I tested the "debug.focusWindowOnBreak" option and the only thing it does is automatically switching the focus to VSCode when the breakpoint hits (or not switching the focus). In fact, it was already enabled to me. This is not directly related to the issue though. The issue is that if the cursor is hidden in the application, the cursor does not become visible again when the breakpoint hits, regardless whether the focus was shifted to VSCode or not.

I'm developing in Ubuntu and this is a major pain because there is no easy way to make the cursor visible again, at least not under Ubuntu's default window manager. I'm not sure if the same occurs in Windows though. I thought the easiest solution would be making VSCode always force the cursor to be visible again when the breakpoint is hit, but I may be missing something.

Thanks

**Comment by isidorn** [comment] 2021-03-15 14:41
@felipeek just to clarify, once VS Code has focus if you click on the editor does the cursor appear?
Or if you do not use the mouse if you `F1 > focus first editor group`? Does the cursor appear then?

**Comment by felipeek** [comment] 2021-03-15 17:03
@isidorn Neither option makes the cursor reappear :(

**Comment by felipeek** [comment] 2021-03-15 17:05
What does make the cursor reappear is killing the process (the process being debugged, not the IDE)

**Comment by felipeek** [comment] 2021-03-15 17:11
I just tested the behavior in OS X and the cursor does reappear when the breakpoint is hit. So I think this behavior only occurs in Ubuntu

**Comment by isidorn** [comment] 2021-03-15 17:20
Yeah, so this is some specific OS ubuntu cursor behavior which we can not control from Electron.
For now I can leave this issue open and maybe someone from the community has an idea. Though currently no action planned here.

**Comment by felipeek** [comment] 2021-03-15 17:34
Workaround for future readers:

```
setxkbmap -option grab:break_actions
xdotool key XF86Ungrab
```

On Ubuntu, XF86Ungrab is bound to 'Ctrl'+'Alt'+'Numpad /'

When the breakpoint hits, pressing this combination will make the cursor reappear

original solution: https://unix.stackexchange.com/a/40472/305333

**Closed** 2021-05-04 18:34 UTC
Labels: *out-of-scope, debug, feature-request
