### ISSUE TITLE
Refactor > Move to a file

### ISSUE THREAD

**Issue by lcswillems** [microsoft/vscode#107957] opened 2020-10-02 08:30 UTC
I have a TypeScript codebase. Often, I define a function `f` in a specific file `X` but later I want this function to move to an already existing file `Y`.

What I do is: locate all calls to `f`. Move `f` to `Y`, replace all calls to `f` when it was in `X` by calls to `f` in `Y`. This is time-consuming and I would think it can be automated with a refactor.

**Comment by mjbvz** [comment] 2020-10-14 07:45
Duplicate of https://github.com/microsoft/TypeScript/issues/29988

**Closed by mjbvz** 2020-10-14 07:45 UTC
