### ISSUE TITLE
Debug hover: does not seem to work so well when in file inlined from source map

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2307] opened 2016-01-26 11:06 UTC
I am debugging an extension and I step into code from the plugin host, which now nicely works and shows the source code from the source map! However, the debug hover only seems to work on the current active line, not when I move around in the editor.

![hover](https://cloud.githubusercontent.com/assets/900690/12579069/62fd5dda-c425-11e5-8fda-ea2640411c4b.gif)

**Comment by isidorn** [comment] 2016-01-26 11:15
What do you see in the variables view? The hover tkaes the data from there and if nothing useful is there hover will not show anything

**Comment by bpasero** [comment] 2016-01-26 11:39
Variables shows me the names without sourcemap support I guess:

![image](https://cloud.githubusercontent.com/assets/900690/12579642/c6538612-c429-11e5-900c-83f5df4ae0f2.png)

**Comment by isidorn** [comment] 2016-01-26 11:41
So the problem is not with the hover, since the variables view does not show good names.
Do you have source maps turned on or is this a source map issue?

**Comment by bpasero** [comment] 2016-01-26 13:07
I use a bare bone hello world typescript extension with sourcemaps: true and out dir enabled.

**Comment by isidorn** [comment] 2016-01-26 13:25
Forwarding to @weinand then, should the variables have proper names in this case Andre?

**Comment by weinand** [comment] 2016-01-26 13:56
@isidorn no, they shouldn't.

**Comment by bpasero** [comment] 2016-01-26 13:59
Well I am fine with that, but the actual issue is that the hover does not popup when used in this case except for the current line.

**Comment by isidorn** [comment] 2016-01-26 14:02
Well the problem is that the hover goes to the variables and tries to match the hovered value. Since all the values have short names he does not match it against any I do not see what I can do smarter here.
Node debug adapter does not support evaluate on hover so I have to do this variable name matching which does not work for this case

**Comment by weinand** [comment] 2016-01-26 14:07
@isidorn evaluate on hover would only work if node-debug would be able to map source names to generated names. But this information is typically not available in source maps.

**Comment by isidorn** [comment] 2016-02-03 11:07
There is nothing to do here on my end IMHO. Forwarding to Andre so he can decide whether to close this bug or if there is some workaround.

**Comment by weinand** [comment] 2016-02-03 16:53
doing something here would require more sophisticated architecture and debug protocol enhancements.

**Comment by pflannery** [comment] 2016-11-26 17:15
Chrome had the same issue and was [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=327092#c33) earlier this year 

Looking at the recent source it looks like they perform a [reverse look up](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/sources/SourceMapNamesResolver.js#L253)

[reverseMapTextRange](https://github.com/ChromeDevTools/devtools-frontend/blob/9b94a2ac7cdd053479d8ab2cbe767a742eb6f77c/front_end/sdk/SourceMap.js#L520)
[reverseMappings lookup](https://github.com/ChromeDevTools/devtools-frontend/blob/9b94a2ac7cdd053479d8ab2cbe767a742eb6f77c/front_end/sdk/SourceMap.js#L372)

**Comment by weinand** [comment] 2017-04-05 10:39
The underlying issue is covered by this feature request: https://github.com/Microsoft/vscode/issues/12066

**Closed by weinand** 2017-04-05 10:39 UTC
Labels: debug, feature-request
