### ISSUE TITLE
Starting via Ubuntu menu is not loading extensions and is slow

### ISSUE THREAD

**Issue by adrian-dinu** [Microsoft/vscode#67247] opened 2019-01-28 15:23 UTC
- VSCode Version: 1.30.2 x64
- OS Version: Ubuntu 18.04.1 LTS

Running vscode from the command line using the code command in terminal is loading vscode fast and extensions menu is working ok and when I exit code it exists all processes.

Running vscode from icon will load vscode quite slow, will not load the extension menu, it will just hang with the clock sign and moving line, and when exiting will leave processes on that can only be killed with -9.

I have tried to remove the --unity-launch from code.desktop as suggested here https://github.com/Microsoft/vscode/issues/45666 with no success (I can see it remove --unit-launch from the process when running ps but it doesn't improve the situation).

Not sure what info to provide to debug this, here is the output of ps aux, maybe it helps:

from the icon:
```shell
adrian    28463  4.2  1.5 1647376 127976 tty1   Sl+  17:06   0:01 /usr/share/code/code
adrian    28467  0.0  0.5 378568 41616 tty1     S+   17:06   0:00 /usr/share/code/code --type=zygote --no-sandbox
adrian    28505  1.9  1.1 577916 96580 tty1     Rl+  17:06   0:00 /usr/share/code/code --type=gpu-process --disable-features=ColorCorrectRendering --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=9,27,84 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --disable-accelerated-video-decode --gpu-vendor-id=0x15ad --gpu-device-id=0x0405 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=CEF5EDF206A6B45EE52E07E3E3CB6A52
adrian    28512  8.4  2.9 1329756 238056 tty1   Sl+  17:06   0:02 /usr/share/code/code --type=renderer --js-flags=--nolazy --disable-mojo-local-storage --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=48DEEEE1CE7AB8AC9ACBEF2A8F3FE9B7 --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --context-id=2 --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553 --disable-accelerated-video-decode --enable-gpu-async-worker-context --service-request-channel-token=48DEEEE1CE7AB8AC9ACBEF2A8F3FE9B7 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101
adrian    28529  0.0  0.0  29988  3920 ?        Ss   17:06   0:00 /bin/bash -ilc '/usr/share/code/code' -p '"11383958e893" + JSON.stringify(process.env) + "11383958e893"'
adrian    28574  4.4  1.2 1067100 99568 tty1    Sl+  17:06   0:00 /usr/share/code/code --nolazy --inspect=42757 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
```

from the cli:
```shell
adrian    28645 11.8  1.5 1641204 129176 ?      Ssl  17:08   0:00 /usr/share/code/code
adrian    28647  0.1  0.5 378568 41580 ?        S    17:08   0:00 /usr/share/code/code --type=zygote --no-sandbox
adrian    28685  4.1  1.2 581020 99484 ?        Sl   17:08   0:00 /usr/share/code/code --type=gpu-process --disable-features=ColorCorrectRendering --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=9,27,84 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --disable-accelerated-video-decode --gpu-vendor-id=0x15ad --gpu-device-id=0x0405 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=29B60105B93A8DD152B9BD98014F8626
adrian    28692 26.0  3.0 1344432 249636 ?      Sl   17:08   0:01 /usr/share/code/code --type=renderer --js-flags=--nolazy --disable-mojo-local-storage --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=CD4640D1B43CE624BCDC745D7C2AC434 --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --context-id=2 --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553 --disable-accelerated-video-decode --enable-gpu-async-worker-context --service-request-channel-token=CD4640D1B43CE624BCDC745D7C2AC434 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101
adrian    28721  9.6  1.2 1067104 99568 ?       Sl   17:08   0:00 /usr/share/code/code --nolazy --inspect=57704 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
adrian    28739 19.7  1.4 1161676 120176 ?      Sl   17:08   0:00 /usr/share/code/code --type=renderer --js-flags=--nolazy --disable-mojo-local-storage --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=C80139F879E17CA2BEE3A5E66E1FCEEC --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --context-id=2 --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553 --disable-accelerated-video-decode --enable-gpu-async-worker-context --service-request-channel-token=C80139F879E17CA2BEE3A5E66E1FCEEC --renderer-client-id=6 --shared-files=v8_natives_data:100,v8_snapshot_data:101
```

Let me know if I can provide more info.

LE: I have done a purge and reinstalled, also deleting the files from .config and .vscode just to make sure this is a fresh install.

**Comment by bpasero** [comment] 2019-01-29 09:51
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by adrian-dinu** [comment] 2019-01-29 10:04
I have done the following:

```shell
sudo apt-get purge code
rm -r .config/Code
rm -r .vscode
sudo dpkg -i Downloads/code-insiders_1.31.0-1548742718_amd64.deb
```

Icon is now green, but the same issue happens, it take some time to load from icon (~20 secs), extensions menu doesn't work, it looks like it just keeps loading but nothing appears.

The following processes are running:
```shell
adrian    60310  3.8  1.4 1601624 121572 tty1   Sl+  11:57   0:05 /usr/share/code-insiders/code-insiders --unity-launch
adrian    60314  0.0  0.4 370896 38796 tty1     S+   11:57   0:00 /usr/share/code-insiders/code-insiders --type=zygote --no-sandbox
adrian    60349  4.5  1.2 600628 98164 tty1     Sl+  11:57   0:05 /usr/share/code-insiders/code-insiders --type=gpu-process --disable-features=ColorCorrectRendering --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=736D761CBB6776242165C299C63270A1
adrian    60363 10.0  2.4 1292604 197304 tty1   Sl+  11:57   0:13 /usr/share/code-insiders/code-insiders --type=renderer --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=B6E35FB7DF614AB1842746E0FDE184A8 --lang=en-US --app-path=/usr/share/code-insiders/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=B6E35FB7DF614AB1842746E0FDE184A8 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
adrian    60386  0.0  0.0  29988  3892 ?        Ss   11:57   0:00 /bin/bash -ilc '/usr/share/code-insiders/code-insiders' -p '"450f7283d952" + JSON.stringify(process.env) + "450f7283d952"'
adrian    60428  0.4  1.1 1135608 94660 tty1    Sl+  11:57   0:00 /usr/share/code-insiders/code-insiders --nolazy --inspect=42441 /usr/share/code-insiders/resources/app/out/bootstrap-fork --type=extensionHost
```

After I quit the following processes remain active:
```shell
adrian    60310  4.0  1.5 1296128 124176 tty1   Sl+  11:57   0:07 /usr/share/code-insiders/code-insiders --unity-launch
adrian    60314  0.0  0.4 370896 38796 tty1     S+   11:57   0:00 /usr/share/code-insiders/code-insiders --type=zygote --no-sandbox
adrian    60386  0.0  0.0  29988  3892 ?        Ss   11:57   0:00 /bin/bash -ilc '/usr/share/code-insiders/code-insiders' -p '"450f7283d952" + JSON.stringify(process.env) + "450f7283d952"'
```

Doing a kill on them kills 2 but this one remains active and is only kill-able with a kill -9:
```shell
adrian    60386  0.0  0.0  29988  3892 ?        Ss   11:57   0:00 /bin/bash -ilc '/usr/share/code-insiders/code-insiders' -p '"450f7283d952" + JSON.stringify(process.env) + "450f7283d952"'
```

Running code-insiders from the terminal: loads almost instant, extension menu works perfect, the following processes are running:

```shell
adrian    60703  2.8  1.5 1645212 126864 ?      Ssl  12:02   0:01 /usr/share/code-insiders/code-insiders
adrian    60705  0.0  0.4 370896 39008 ?        S    12:02   0:00 /usr/share/code-insiders/code-insiders --type=zygote --no-sandbox
adrian    60740  1.6  1.2 610284 103248 ?       Sl   12:02   0:00 /usr/share/code-insiders/code-insiders --type=gpu-process --disable-features=ColorCorrectRendering --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=F6146A03A9E7469507FE7350D72C2920
adrian    60753  8.4  2.6 1340288 219572 ?      Sl   12:02   0:03 /usr/share/code-insiders/code-insiders --type=renderer --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=ECB8281CD930FF4ACF7BE3F60C0C5A06 --lang=en-US --app-path=/usr/share/code-insiders/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=ECB8281CD930FF4ACF7BE3F60C0C5A06 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
adrian    60790  1.4  1.1 1135612 94800 ?       Sl   12:02   0:00 /usr/share/code-insiders/code-insiders --nolazy --inspect=55107 /usr/share/code-insiders/resources/app/out/bootstrap-fork --type=extensionHost
adrian    60811  2.9  1.4 1195976 118472 ?      Sl   12:02   0:01 /usr/share/code-insiders/code-insiders --type=renderer --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=97EC090F1A612C14A70847716490A9B7 --lang=en-US --app-path=/usr/share/code-insiders/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=97EC090F1A612C14A70847716490A9B7 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

When I hit the close button all processes are closed, nothing lingers.

Let me know if I can provider further info.

**Comment by adrian-dinu** [comment] 2019-01-29 10:09
Removing unity-launch from code.desktop has no effect and spawns this processes:
```shell
adrian    61107  4.6  1.5 1626384 124148 tty1   Sl+  12:07   0:01 /usr/share/code-insiders/code-insiders
adrian    61111  0.0  0.4 370896 38948 tty1     S+   12:07   0:00 /usr/share/code-insiders/code-insiders --type=zygote --no-sandbox
adrian    61145  3.3  1.2 600628 98840 tty1     Sl+  12:07   0:00 /usr/share/code-insiders/code-insiders --type=gpu-process --disable-features=ColorCorrectRendering --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=1F62E8ACAA861C97854B1766FEFEB025
adrian    61162 15.3  2.4 1308964 197272 tty1   Sl+  12:07   0:03 /usr/share/code-insiders/code-insiders --type=renderer --no-sandbox --disable-features=ColorCorrectRendering --service-pipe-token=7B521C5167C48BFA8C3A6E7E34B9851F --lang=en-US --app-path=/usr/share/code-insiders/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=7B521C5167C48BFA8C3A6E7E34B9851F --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
adrian    61185  0.0  0.0  29988  3920 ?        Ss   12:07   0:00 /bin/bash -ilc '/usr/share/code-insiders/code-insiders' -p '"54cffaa704b7" + JSON.stringify(process.env) + "54cffaa704b7"'
adrian    61225  4.8  1.1 1135576 94528 tty1    Sl+  12:08   0:00 /usr/share/code-insiders/code-insiders --nolazy --inspect=22932 /usr/share/code-insiders/resources/app/out/bootstrap-fork --type=extensionHost
```

Still takes long to load, extensions menu not working, etc.

**Comment by bpasero** [comment] 2019-01-29 10:13
No clue, @Tyriar any idea?

**Comment by adrian-dinu** [comment] 2019-01-29 19:06
I observed that the main difference between running from icon and command prompt is this sub-process:
```shell
adrian    60386  0.0  0.0  29988  3892 ?        Ss   11:57   0:00 /bin/bash -ilc '/usr/share/code-insiders/code-insiders' -p '"450f7283d952" + JSON.stringify(process.env) + "450f7283d952"'
```

It's also the process that hangs and needs to be killed with -9, I tried a few things and the one that fixed the issue was removing some parts of the bashrc that included some recording with the script command for my day to day usage history.

To permanently fix the issue for me and any future conflict that may happen I would suggest using something like this instead:

```shell
/bin/bash --noprofile --norc -ilc '/usr/share/code-insiders/code-insiders'
```

I am not sure what part of vscode runs that command or if it needs a code change or a setting somewhere.

**Comment by bpasero** [comment] 2019-01-30 09:40
@joaomoreno moving to you

**Comment by joaomoreno** [comment] 2019-01-30 10:31
We can't use `--noprofile --norc` because loading the profile and rc files is exactly what we are doing there, it's the whole point we spawn that process.

How long does it take in your case? Any ideas of what in your .bashrc (et al) might be causing it?

**Comment by Tyriar** [comment] 2019-01-30 15:55
I'd say this is fixed then, good to know for the future that this is likely the cause of these sorts of reports.

**Closed by Tyriar** 2019-01-30 15:55 UTC
Labels: freeze-slow-crash, needs more info
