### ISSUE TITLE
No import autocomplete with Typescript 

### ISSUE THREAD

**Issue by Ikderrr** [Microsoft/vscode#30632] opened 2017-07-13 16:26 UTC
In new release, there's no path autocomplete on modules like it used to be on September 2016 release.

- VSCode Version: 1.14.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Create a Typescript project with `"baseUrl": "./"` in compiler options
2. Create some basic module
3. Try `import Foo from "folder/module"`. There's no autocomplete

Reproduces without extensions: No

**Comment by mjbvz** [comment] 2017-07-14 20:57
If you manually trigger suggestions using <kbd>ctrl</kbd><kbd>space</kbd> (`editor.action.triggerSuggest` keybinding) do you see the suggestions?

**Comment by Ikderrr** [comment] 2017-07-14 22:42
@mjbvz Yes I do. Isn't there a way to automatically show them for `import `?

**Comment by mjbvz** [comment] 2017-07-14 22:49
Thanks @Ikderrr. This is a duplicate of #23962

Try setting:

```json
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```

to restore the old behavior. You may still have to manually trigger suggestions if you have not yet typed any characters of the import path

**Closed by mjbvz** 2017-07-14 22:49 UTC
Labels: duplicate, needs more info, new release, typescript

**Comment by henrikra** [comment] 2017-09-01 18:44
I am not getting path suggestions when typing relative import path with this config: I can only get suggestions when manually pressing `ctrl` + `space` after every folder :/ Any idea? @mjbvz 
```
{
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  }
}
```
Here is also my `jsconfig`
```
{
  "compilerOptions": {
    "target": "es6"
  },
  "include": ["src/**/*"]
}
```
