### ISSUE TITLE
CPU of Node Process

### ISSUE THREAD

**Issue by WuHeartGod** [microsoft/vscode#101126] opened 2020-06-26 12:46 UTC
Issue Type: <b>Performance Issue</b>

When Use vscode-WSL, the CPU of Node Progress is very High. And is high  all the time. I dont know what it is doing.

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T06:20:06.931Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (7.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3500)|
|Memory (System)|14.95GB (7.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3500)|
|Memory (System)|14.95GB (7.95GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   121	 30916	code-insiders main
    0	   344	 22180	   window (xhttp_request_impl.cpp - Common [WSL: Ubuntu-20.04] - Visual Studio Code - Insiders)
    0	    60	 29840	     extensionHost
    0	    31	 32336	       electron_node wslDaemon.js 
    0	     6	 29524	         C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 6c235c723cb2d8defb840f732eac620f54aa8b9d insider .vscode-server-insiders 0  '
    0	     5	 24384	           C:\WINDOWS\System32\lxss\wslhost.exe {2c8f27aa-8beb-4c94-b24e-c0845b696399} 476 484 488
    0	    13	 30592	             console-window-host (Windows internal process)
    0	    11	 29312	           console-window-host (Windows internal process)
    0	    78	 23700	   shared-process
    0	    26	 26548	   utility
    0	   243	 29652	   window (HttpFileUploadRequest.cc - drogon [WSL: Ubuntu-20.04] - Visual Studio Code - Insiders)
    0	    54	 24540	     extensionHost
    0	    28	 25296	       electron_node wslDaemon.js 
    2	    66	 30504	   window (问题报告程序)
    0	   346	 30728	   gpu-process
    0	    15	 31404	   electron-crash-reporter
    0	    27	 32148	   "D:\Program Files (x86)\sogoupinyin\9.5.0.3517\SGTool.exe" -daemon
Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: sleep: cannot read realtime clock: Invalid argument

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: sleep: cannot read realtime clock: Invalid argument

```

</details>
<details>
<summary>Workspace Info</summary>

```

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: sleep: cannot read realtime clock: Invalid argument

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: sleep: cannot read realtime clock: Invalid argument
;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
lex-flex-yacc-bison|fau|0.0.3
vscode-language-pack-zh-hans|MS-|1.47.0
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
vscode-language-pack-zh-hans|MS-|1.47.0
cmake-tools|ms-|1.4.1
cpptools|ms-|0.28.3
cmake|twx|0.0.17

</details>

**Comment by aeschli** [comment] 2020-06-29 08:57
duplicate of https://github.com/microsoft/vscode-remote-release/issues/3244

It's a problem with WSL1 and the Ubuntu 20 distro. 
The recommendation is to use a different distro (or switch to WSL2, if you can)

**Closed by aeschli** 2020-06-29 08:57 UTC

**Comment by WuHeartGod** [comment] 2020-07-02 14:06
Thank you for your reply.

**Comment by WuHeartGod** [comment] 2020-07-02 14:08
Thank you for your reply.
