### ISSUE TITLE
Extension Recommendation: close event not fired

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33409] opened 2017-08-29 14:43 UTC
Testing: #33298 

- Section Testing Telemetry for the Recommendation Pop up
- item 5: close the pop up

I didn't receive any event.  Verified by setting a break point in TelemetryService#publicLog.

**Comment by dbaeumer** [comment] 2017-08-29 14:45
Esc does trigger a 'cancel' event.

**Comment by ramya-rao-a** [comment] 2017-08-29 15:24
Duplicate of #33335

**Closed by ramya-rao-a** 2017-08-29 15:24 UTC
Labels: extensions
