### ISSUE TITLE
Can't open extension or install any extension

### ISSUE THREAD

**Issue by BenMaruchu** [Microsoft/vscode#13583] opened 2016-10-12 09:31 UTC
- VSCode Version: 1.6
- OS Version: Ubuntu-gnome 16.04

Steps to Reproduce:

1. Click extension sidebar icon
![screenshot from 2016-10-12 12-28-37](https://cloud.githubusercontent.com/assets/7030859/19304973/802cdbbe-9077-11e6-8d84-e5b412a4bb8a.png)

**Comment by joaomoreno** [comment] 2016-10-12 13:33
Duplicate of #13561

**Closed by joaomoreno** 2016-10-12 13:33 UTC
