### ISSUE TITLE
No immediate notification that side-loaded extension was successfully installed.

### ISSUE THREAD

**Issue by bnookala** [Microsoft/vscode#9639] opened 2016-07-22 20:34 UTC
- VSCode Version: 1.3.1
- OS Version: 10.11.3

Side-loading an extension through the `File -> Open` interface does not show any notification in the interface that installation was successful. Only the extensions tab shows that the installation was successful.

Steps to Reproduce:
1. Select `File - Open`
2. Select a `.vsix` file in the file picker
3. Observe that the interface does not show any notification.

Gif of me installing a side loaded extension, `KiteCode`:
![kitecode](https://cloud.githubusercontent.com/assets/87996/17070452/df40d774-5010-11e6-8e53-586d7ce6bfa2.gif)

**Comment by joaomoreno** [comment] 2016-07-25 14:52
Duplicate of #8075

**Closed by joaomoreno** 2016-07-25 14:52 UTC
