### ISSUE TITLE
[json] no quick suggestions when in a string literal

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#32480] opened 2017-08-14 14:44 UTC
- VSCode Version: 1.15
- OS Version: win7x64

Suggestions in settings - pretty nice idea. BUT. There will be no suggestions after you will remove 1 or more letters after typing something.

For example, I type "snipp", then remove one letter to "snip", and that's it! VS Code will not show you any suggestions after this. Until you will remove everything including quote marks. That's annoying, guys!

![settings - suggestions](https://user-images.githubusercontent.com/24613274/29276499-7a363444-8117-11e7-95f8-0d87c60bec56.gif)

**Comment by jrieken** [comment] 2017-08-15 07:59
Yeah, we made that change because we got the opposite feedback at one point... In general suggestion will start again immediately after typing but JSON uses a very stupid word definition which is responsible for not triggering suggestions again.

**Comment by aeschli** [comment] 2017-08-31 13:25
I created #33591 to allow the JSON language to control better where quick suggestion should appear. Currently, by design, quick suggestion does not appear when inside a word/symbol.
JSON could allow that as completions are able to replace the full work/symbol.

**Comment by tomitrescak** [comment] 2018-02-13 06:05
What about quick suggestion after "." I tried everything and it is not firing for my new language.

```js
const i = this.createDefinitions(props.i);

    if (this.previous) {
      this.previous.dispose();
    }
    this.previous = this.monaco.languages.registerCompletionItemProvider('*', {
      provideCompletionItems: function(model: any, position: any) {
        // find out if we are completing a property in the 'dependencies' object.
        let textUntilPosition = model.getValueInRange({
          startColumn: 1,
          endLineNumber: position.lineNumber,
          endColumn: position.column
        });
        if (textUntilPosition.match(/i\.$/)) {
          return i;
        }
...
```

**Comment by mchancloud** [comment] 2021-12-20 20:18
I'm trying to implement snippets/quick suggestions that appear in string literals.  Is there any work around for this? If not, can we revive this bug, since it directly affects string literals which is widely used in json files?

**Comment by feltcute** [comment] 2022-02-10 02:28
I'm developing an extension for using snippets inside strings to quickly place markup and semi-complex structures. This bug has been a major roadblock to this extension, and no amount of configuring editor.quickSuggestions, snippetSuggestions, or any other setting related to suggestions was capable of making it behave predictably.

33591 was called by a duplicate of 32201, which was claimed to be fixed by 53945. This was not the case, the issue with snippets inside json strings is very much so alive and present.

**Closed** 2022-06-13 12:36 UTC
Labels: feature-request, json, suggest
