### ISSUE TITLE
var color

### ISSUE THREAD

**Issue by zawiasam** [Microsoft/vscode#4202] opened 2016-03-14 19:23 UTC
- VSCode Version: [Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:38:23.764Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

- OS Version: Windows 10

Steps to Reproduce:

1. name variable dbTypes.varchar
2. word var is colored as key word but it's just a part of other word

![image](https://cloud.githubusercontent.com/assets/7436990/13756897/5330c2c0-ea22-11e5-9b14-b13ffd96c901.png)

**Comment by aeschli** [comment] 2016-03-14 20:04
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

**Closed** 2016-03-14 20:06 UTC
