### ISSUE TITLE
Changing the theme on an extension readme breaks the font

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31992] opened 2017-08-03 19:03 UTC
![aug-03-2017 12-01-49](https://user-images.githubusercontent.com/323878/28938654-8fe8801c-7843-11e7-8241-1f21e08aeec5.gif)
- Click on some extension to view the readme
- Change the theme
- See that the font changes to Times New Roman or something
- Changing the theme again doesn't fix it but reopening the extension readme does.

Assigning to @mjbvz but it doesn't repro on other markdown preview pages.

**Comment by mjbvz** [comment] 2017-08-03 21:16
Duplicate of #25370

**Closed by mjbvz** 2017-08-03 21:16 UTC
Labels: duplicate
