### ISSUE TITLE
Keybindings get locked to selected keyboard when opening program

### ISSUE THREAD

**Issue by stevenmwade** [Microsoft/vscode#24118] opened 2017-04-06 18:10 UTC
I use Dvorak-QWERTY which maps the keyboard to QWERTY keybindings when pressing CMD. As of my update today, the bindings get locked to whatever keyboard you have open.

- VSCode Version: 1.11.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open VSCode with Dvorak QWERTY keyboard selected
2. CMD+v == CMD+k
2. Change to US keyboard and CMD+v == CMD+k
3. Quit VSCode
4. Open with US keyboard selected
5. CMD+v == CMD+v on all keyboards

Reverted to v1.10.2

**Comment by alexandrudima** [comment] 2017-04-06 22:57
Duplicate of #23964

**Closed by alexandrudima** 2017-04-06 22:57 UTC
