### ISSUE TITLE
Input box focus not appearing fully

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117570] opened 2021-02-24 11:47 UTC
Testing #117250

The input box focus is not appearing fully:

![image](https://user-images.githubusercontent.com/900690/108996298-813b7580-769e-11eb-8418-694576fe14ce.png)

**Comment by alexr00** [comment] 2021-02-24 13:17
duplicate of https://github.com/microsoft/vscode/issues/117385

**Closed by alexr00** 2021-02-24 13:17 UTC
