### ISSUE TITLE
TypeScript types autocomplete stopped working

### ISSUE THREAD

**Issue by ddwwcruz** [Microsoft/vscode#30763] opened 2017-07-15 13:04 UTC
Autocomplete on types doesn't work in typescript files.

- VSCode Version: 1.14.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open typescript file
2. Declare the type of a variable

Reproduces without extensions: Yes

**Comment by cantsdmr** [comment] 2017-07-15 14:12
This problem exists on Windows 10 too, even for JavaScript.

**Comment by Zorbing** [comment] 2017-07-15 22:54
This might be related to #30716.

**Comment by hanpari** [comment] 2017-07-16 04:48
I can confirm on Win10. 
I tried insider version and disabled all extensions. 
It is not working at all.

For instance:

function (x:st...) should bring string but nothing has happened.

**Comment by MartinHaeusler** [comment] 2017-07-17 19:59
Can confirm this for VSCode 1.14 on Windows 10 too. It's super annoying, I hope this gets fixed soon... Only types seem to be affected though, other autocompletions (e.g. variable names) work just fine.

**Comment by Ikderrr** [comment] 2017-07-18 16:15
I also confirm this, Windows 10 with VS Code 1.14.1

**Comment by SDSLeon** [comment] 2017-07-18 21:59
I also confirm this, Windows 10 (build.15063) with VS Code 1.14.1 or VS Code 1.15-insiders and typescript 2.4.1 or 2.4.2-insiders.

For typescript 2.3.4 all works fine.

**Comment by mjbvz** [comment] 2017-07-19 21:35
This is a duplicate of #30580. I'm working with the TS team to get a fix out soon

**Closed by mjbvz** 2017-07-19 21:35 UTC
Labels: duplicate, new release, typescript
