### ISSUE TITLE
Locks up when restarting build task

### ISSUE THREAD

**Issue by pedro-w** [microsoft/vscode#76235] opened 2019-06-27 10:03 UTC
Issue Type: <b>Bug</b>

I am working on a JS project which is using webpack and eslint. One of my build tasks is `webpack --watch`. I am finding that if I start the task and later restart the task (from Terminal|Restart running task...) then VSCode will lock up. The menus still drop down but no action occurs and the main screen is unresponsive. Eventually I get the "The Window is no longer responding" dialog and I have to close it.
I have put together a minimal project which can be used to show the problem here: https://github.com/pedro-w/webpack-check.git
I'm not sure where the problem lies exactly so any help/advice would be appreciated.

I am using 
Node: v10.16.0
webpack: 4.35.0
eslint: 5.16.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
python|ms-|2019.6.22090
cpptools|ms-|0.23.1
debugger-for-chrome|msj|4.11.5
vscode-hexdump|sle|1.7.2
markdown-pdf|yza|1.2.0

</details>

**Comment by alexr00** [comment] 2019-06-27 10:59
Duplicate of #71966

**Closed** 2019-06-27 10:59 UTC
Labels: *duplicate, tasks
