### ISSUE TITLE
JSX coloring, this not colorized in Dark+ but it is colorized in Monokai

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2955] opened 2016-02-12 07:59 UTC
In the following snippet `this` should be colorized
![image](https://cloud.githubusercontent.com/assets/172399/13001496/ad147ad6-d166-11e5-8986-4357fefee8bc.png)

It is colorized when I use the monokai theme
![image](https://cloud.githubusercontent.com/assets/172399/13001499/cc18324c-d166-11e5-9f08-a408ff10009c.png)

@aeschli since `this` is colorized in monokai,this hints that this is an issue with the Dark+ theme?

**Comment by aeschli** [comment] 2016-03-07 15:37
It's not a problem of the themes, but caused by our flattening of text mate scopes (#3008).
The tokenizer actually returns quite detailed scopes on the source code, but the theme ends up matching against a parent scope.

duplicate of #3008

**Closed by aeschli** 2016-03-07 15:37 UTC

**Comment by aeschli** [comment] 2016-03-07 15:48
```
return 
    <View>
        <Text> {JSON.stringify(this.state.connectionInfoHistory)} </Text>
    </View>;
```
