### ISSUE TITLE
Should shrinkwrap files be ignored?

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode#31307] opened 2017-07-24 08:40 UTC
pulled in latest from master, ran `./scripts/npm install` and I see a bunch of shrinkwrap files that got modified. 

I am not sure what to do with them when sending a PR. Should those be ignored?
```
        modified:   ../../configuration-editing/npm-shrinkwrap.json
	modified:   ../npm-shrinkwrap.json
	modified:   npm-shrinkwrap.json
	modified:   package.json
	modified:   ../../emmet/npm-shrinkwrap.json
	modified:   ../../emmet/package.json
	modified:   ../../extension-editing/npm-shrinkwrap.json
	modified:   ../../git/npm-shrinkwrap.json
	modified:   ../../git/package.json
	modified:   ../../grunt/npm-shrinkwrap.json
	modified:   ../../grunt/package.json
	modified:   ../../gulp/npm-shrinkwrap.json
	modified:   ../../gulp/package.json
	modified:   ../../html/npm-shrinkwrap.json
	modified:   ../../html/package.json
	modified:   ../../html/server/npm-shrinkwrap.json
	modified:   ../../jake/npm-shrinkwrap.json
	modified:   ../../jake/package.json
	modified:   ../../javascript/npm-shrinkwrap.json
	modified:   ../../javascript/package.json
	modified:   ../../json/npm-shrinkwrap.json
	modified:   ../../json/package.json
	modified:   ../../json/server/npm-shrinkwrap.json
	modified:   ../../markdown/npm-shrinkwrap.json
	modified:   ../../merge-conflict/npm-shrinkwrap.json
	modified:   ../../merge-conflict/package.json
	modified:   ../../npm-shrinkwrap.json
	modified:   ../../npm/npm-shrinkwrap.json
	modified:   ../../npm/package.json
	modified:   ../../php/npm-shrinkwrap.json
	modified:   ../../php/package.json
	modified:   ../../typescript/npm-shrinkwrap.json
	modified:   ../../typescript/package.json
	modified:   ../../vscode-api-tests/package.json
	modified:   ../../vscode-colorize-tests/package.json
	modified:   ../../../npm-shrinkwrap.json
	modified:   ../../../package.json
```

**Comment by praveenpuglia** [comment] 2017-07-24 12:59
I didn't realize I was on node 8+ and NPM 5+ and it looks like vscode doesn't support them yet? Please confirm this and close.

**Comment by mjbvz** [comment] 2017-07-24 17:57
Yes, we do not support npm 5 currently and are tracking support with #30134

Closing as a duplicate of #30134

**Closed by mjbvz** 2017-07-24 17:57 UTC
Labels: duplicate, engineering, json
