### ISSUE TITLE
can we please get a Android version of VSCODE i would really love to code on my Tab s7+ instead of my laptop and i would also really like to code on Visual studios  code instead of other code editors like A code please give us a native code editor

### ISSUE THREAD

**Issue by mynameish4r01d** [microsoft/vscode#143483] opened 2022-02-20 06:25 UTC

**Comment by asifurrahaman754** [comment] 2022-02-20 07:06
Of course, you can use the web version of vs code from any device. visit https://vscode.dev/

**Comment by chrisdias** [comment] 2022-02-22 20:39
dupe of #126147

**Closed by chrisdias** 2022-02-22 20:39 UTC
