### ISSUE TITLE
Intellisense triggering after typing comma, space inside a string literal

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#4908] opened 2016-04-04 10:42 UTC
- VSCode Version: Feb release + March Insiders
- OS Version: Mac OS X Yosemite

Steps to Reproduce:
1) Enter the following code
```
it('Hello', () => {

});
```
2) Put your cursor after Hello but within the string and type comma then space, the intellisense will kick in (even though you are inside a string literal)

**Comment by massimocode** [comment] 2016-04-04 10:47
Sorry this assumes you have mocha.d.ts

**Comment by jrieken** [comment] 2016-04-04 16:01
Today, the scopes or token types aren't known to extensions. Because of that we cannot prevent this yet. The same is true other cases, like IntelliSense inside comments. Closing as duplicate of #719

**Closed by jrieken** 2016-04-04 16:01 UTC
