### ISSUE TITLE
Code refactoring with optional chaining syntax

### ISSUE THREAD

**Issue by Qunapi** [microsoft/vscode#88088] opened 2020-01-04 16:02 UTC
Issue Type: <b>Bug</b>

If I try to refactor any code, which contains new optional chaining syntax, i get an error. 
Steps to reproduce:
- write some code with `?` operator
`const a = {
  b: 4,
};
console.log(a?.c);`
- try to extract function to in global scope

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3397)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|7.66GB (0.52GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|

**Comment by mjbvz** [comment] 2020-01-06 17:15
Duplicate of https://github.com/microsoft/TypeScript/issues/35372

**Closed by mjbvz** 2020-01-06 17:15 UTC
