### ISSUE TITLE
"nested" updates from non-admin account crash vscode insiders installation? (now fixed but unexplained)

### ISSUE THREAD

**Issue by haristz** [Microsoft/vscode#36255] opened 2017-10-14 00:28 UTC
- VSCode Version: Code - Insiders 1.18.0-insider (f1ee80be081b0d47f4423b9dc5f41a65c36146da, 2017-10-13T08:55:13.465Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
gnuplot|har|0.0.1
gc-excelviewer|Gra|1.1.15
r|Iku|0.4.8
language-julia|jul|0.7.0
mlab|har|0.0.1
pascal|har|0.0.1
vscode-icons|rob|7.15.0
ActiveFileInStatusBar|Ros|1.0.3
vscode-open|san|0.1.0
pdf|tom|0.2.0

Hi There, 
I have been using vscode-insiders for some months now and am very happy with it.
I am writing about a possible bug  I faced with vscode-insiders updates on the 1st week of October. I use vscode from an account that has no admin privileges, so to update to the newest version each day I need to go through giving permission with an admin password. During the period I mention, 2 things happened:
-Clicking on "restart to update" became less reponsive (had to click it 2x)
- After entering the admin password a 1st time I would be asked to enter it again, ie systems permissions dialog reappeared, and not because the password was wrong (it felt as if the update was relaunching itself twice?).
- Complying with the 1st and declining the 2nd password request resulted in a correct update.
- On the one occasion I decided to enter the admin password both times requested,the update broke and rollback would not fix it (I unfortunately have not been able to find the record of the specific error message in the system logs to paste here, from memory it was something about not having access to a file ).
So I ended up having to completely uninstall vscode-insiders and then reinstall it (Oct 7th). This worked fine. I also replaced my input device (trackball connected to usb hub) because I had noticed that some of my clicks seemed to not be recorded (but this was an issue I have had for months and I never had a problem with vs code insider until now).
I have not had any problems since.
The reason I am posting this is because:
- At one level this feels like the problem came from some kind of "nested updates" (ie update being initiated within an update somehow?) but I am not sure how this happened as even if there was a problem with the input device, shouldn't the application have allowed only one such process to run at a time, as it was initiated from the "restart to update" button? 
- Can you see any potential for additional problems having been caused by this?(ie: uninstall/reinstall seems to have corrected the issue but is there anything else this can have affected on my windows 10 pro system? - does the update only change files/directories in the vscode install folder or is there anything else I should check?)
Many thanks,
Haris 
PS in all installs I always choose to have the app registered in the path after restart (final options screen)
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment] 2017-10-18 13:04
So... when you click it twice, the update runs twice.

Where do you actually click it? Can you show me a screenshot?

**Comment by haristz** [comment] 2017-10-18 20:04
This is what it looked like. I should point out that the second click would come several seconds after the first as it looked as if nothing had happened.
![insiders_issue_mrk_ht](https://user-images.githubusercontent.com/32783572/31739997-87080d5e-b458-11e7-87f7-be3a98887158.png)

**Comment by joaomoreno** [comment] 2017-10-18 20:11
Duplicate of #36244

**Comment by joaomoreno** [comment] 2017-10-18 20:15
> Clicking on "restart to update" became less reponsive (had to click it 2x)

@haristz Would you say that the menu came up again after the first click?

**Comment by haristz** [comment] 2017-10-18 21:58
@joaomoreno No, I am pretty sure the menu only showed up once. The 2nd admin access dialog seemed to come "out of nowhere", or more specifically as if it was triggered by the first dialog. I do use a laptop but my pointing device is a usb trackball with buttons, so I never tap. One thought I had was that this has something to do with the transition from v 1.17 to v1.18 as it was early October, but I unfortunately did not pinpoint the exact version update this started happening at.

**Comment by joaomoreno** [comment] 2017-10-19 07:08
Please be sure. When you say _had to click it 2x_, I believe the first click actually was successful but the menu came back up again, appearing as if the click didn't do anything.

**Comment by haristz** [comment] 2017-10-19 17:26
It is possible that the menu came back again instead of no responsiveness, but in that case I did not see any screen refresh, ie there were no visual signs that this had happened. Also, the 2nd click was immediately responsive.

**Comment by joaomoreno** [comment] 2017-10-27 10:18
OK good to know. We've fixed this in `master`. Thanks for reporting!

**Closed by joaomoreno** 2017-10-27 10:18 UTC
Labels: install-update, needs more info

**Comment by haristz** [comment] 2017-11-03 22:41
@joaomoreno Thanks for looking into it. Is there anything I should patch/check on my system (apart from updating vscode)?

**Comment by joaomoreno** [comment] 2017-11-04 23:04
Nope, just get the next update. 👍

**Comment by haristz** [comment] 2017-11-05 20:33
OK -Thanks !
