### ISSUE TITLE
Request for editors to have a different theme than the rest of the UI.

### ISSUE THREAD

**Issue by ssilverman** [microsoft/vscode#44450] opened 2018-02-26 22:45 UTC
Would be nice to have the editor be able to use a different theme than the rest of the UI. For example, I like to edit in Solarized Light, but use Dark+ for the rest of the UI.
[Feature request]
[Apologies if this is a duplicate, I didn't find a similar request.]

VSCode Version: 1.20.1
OS Version: OSX 10.13.3

**Comment by usernamehw** [comment] 2018-02-26 23:13
Duplicate of #25986 ?

**Comment by ssilverman** [comment] 2018-02-26 23:25
Thanks for pointing out that other issue. I don’t think its the same because for me, the editor includes not just syntax highlighting, but layout, feel, backgrounds, etc.

**Comment by rebornix** [comment] 2018-02-27 00:47
Luckily I know the way to make it work, add below customization to your settings and then you have what you want. The trick here is I borrow the settings from https://github.com/Microsoft/vscode/blob/master/extensions/theme-solarized-light/themes/solarized-light-color-theme.json , removed some editor related ones.

```
	"workbench.colorCustomizations": {
		"background": "#FDF6E3",
		"foreground": "#657B83",
		"focusBorder": "#D3AF86",

		"input.background": "#DDD6C1",
		// "input.border": "",
		"input.foreground": "#586E75",
		"input.placeholderForeground": "#586E75AA",
		"inputOption.activeBorder": "#D3AF86",

		"badge.background": "#B58900AA",
		"progressBar.background": "#B58900",

		"dropdown.background": "#EEE8D5",
		// "dropdown.foreground": "",
		"dropdown.border": "#D3AF86",

		"button.background": "#AC9D57",
		// "button.foreground": "",

		"selection.background": "#CCC4B0",

		"list.activeSelectionBackground": "#DFCA88",
		"list.activeSelectionForeground": "#6C6C6C",
		"list.focusBackground": "#DFCA8866",
		"list.hoverBackground": "#DFCA8844",
		"list.inactiveSelectionBackground": "#D1CBB8",
		"list.highlightForeground": "#B58900",

		// Workbench: Editors
		// "editorGroupHeader.noTabsBackground": "",
		"editorGroup.border": "#DDD6C1",
		"editorGroup.background": "#FFFBF2",
		"editorGroup.dropBackground": "#DDD6C1AA",
		"editorGroupHeader.tabsBackground": "#D9D2C2",

		// Workbench: Tabs
		"tab.border": "#DDD6C1",
		"tab.activeBackground": "#FDF6E3",
		"tab.inactiveForeground": "#586E75",
		"tab.inactiveBackground": "#D3CBB7",
		// "tab.activeBackground": "",
		// "tab.activeForeground": "",
		// "tab.inactiveForeground": "",

		// Workbench: Activity Bar
		"activityBar.background": "#DDD6C1",
		"activityBar.foreground": "#584c27",
		"activityBar.dropBackground": "#EEE8D5",
		"activityBarBadge.background": "#B58900",
		// "activityBarBadge.foreground": "",

		// Workbench: Panel
		// "panel.background": "",
		"panel.border": "#DDD6C1",
		// "panelTitle.activeBorder": "",
		// "panelTitle.activeForeground": "",
		// "panelTitle.inactiveForeground": "",

		// Workbench: Side Bar
		"sideBar.background": "#EEE8D5",
		"sideBarTitle.foreground": "#586E75",
		// "sideBarSectionHeader.background": "",

		// Workbench: Status Bar
		"statusBar.foreground": "#586E75",
		"statusBar.background": "#EEE8D5",
		"statusBar.debuggingBackground": "#EEE8D5",
		"statusBar.noFolderBackground": "#EEE8D5",
		// "statusBar.foreground": "",
		"statusBarItem.prominentBackground": "#DDD6C1",
		"statusBarItem.prominentHoverBackground": "#DDD6C199",
		// "statusBarItem.activeBackground": "",
		// "statusBarItem.hoverBackground": "",

		// Workbench: Debug
		"debugToolBar.background": "#DDD6C1",
		"debugExceptionWidget.background": "#DDD6C1",
		"debugExceptionWidget.border": "#AB395B",

		// Workbench: Notifications
		"notification.background": "#999178",
		// "notification.foreground": "",

		// Workbench: Quick Open
		"pickerGroup.border": "#2AA19899",
		"pickerGroup.foreground": "#2AA19899",

		// Extensions
		"extensionButton.prominentBackground": "#b58900",
		"extensionButton.prominentHoverBackground": "#584c27aa",

		// Workbench: Terminal
		// Colors sourced from the official palette http://ethanschoonover.com/solarized
		"terminal.ansiBlack": "#073642",
		"terminal.ansiRed": "#dc322f",
		"terminal.ansiGreen": "#859900",
		"terminal.ansiYellow": "#b58900",
		"terminal.ansiBlue": "#268bd2",
		"terminal.ansiMagenta": "#d33682",
		"terminal.ansiCyan": "#2aa198",
		"terminal.ansiWhite": "#eee8d5",
		"terminal.ansiBrightBlack": "#586e75",
		"terminal.ansiBrightRed": "#cb4b16",
		"terminal.ansiBrightGreen": "#586e75",
		"terminal.ansiBrightYellow": "#657b83",
		"terminal.ansiBrightBlue": "#839496",
		"terminal.ansiBrightMagenta": "#6c71c4",
		"terminal.ansiBrightCyan": "#93a1a1",
		"terminal.ansiBrightWhite": "#eee8d5"


	},
```

**Comment by ssilverman** [comment] 2018-02-27 01:10
Thank you for the workaround. I know how to do that already, I was just suggesting that the separation of editor and workspace be an option. I’m used to using other IDE’s l, Eg. IntelliJ IDEA, which allows you to easily do this. This is my workaround in the meantime.

**Comment by ssilverman** [comment] 2018-02-27 04:04
Or maybe it *is* a duplicate? I just looked at what Atom calls it and there's "UI Theme" and "Syntax Theme".

**Closed** 2019-10-10 10:25 UTC
Labels: *duplicate, feature-request, themes

**Comment by ssilverman** [comment] 2019-11-05 07:55
Which issue is this a duplicate of?
