### ISSUE TITLE
Upgrading to Catalina makes Code use wrong italic font on non-default font weights

### ISSUE THREAD

**Issue by Kataract** [microsoft/vscode#82122] opened 2019-10-08 21:36 UTC
Issue Type: <b>Bug</b>

1. Starting on macOS Mojave, have a default font for your workspace/editor that has an italic weight and oblique weight installed (I use Victor Mono: https://rubjo.github.io/victor-mono/), along with a theme that supports italics (currently using Night Owl).  Italics should render with cursive by default.
2. Use a different font weight than the default (I use 700 because the default is too thin to see for me)
3. Upgrade from Mojave to Catalina
4. Files in editor no longer use the italic weight and instead use the oblique weight - I noticed this because it wasn't showing in cursive anymore
5. Set font weight to "normal" (default), observe that the right italic font is used

Screenshots:

Default font weight:
![default font weight with cursive font](https://user-images.githubusercontent.com/5710080/66435353-a3bde780-e9f2-11e9-9a84-0e4124904c63.png)

Font weight 700:
![font weight 700 with fake italics](https://user-images.githubusercontent.com/5710080/66435380-b1736d00-e9f2-11e9-9b05-dd412bf3460a.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
vscode-pull-request-github|Git|0.11.2
MagicPython|mag|1.1.0
vscode-less|mrm|0.6.3
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
material-icon-theme|PKi|3.9.1
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment] 2019-10-09 08:08
Duplicate of #82109

**Comment by sschultze** [comment] 2019-10-10 06:50
I have referenced this issue in https://bugs.chromium.org/p/chromium/issues/detail?id=1005969  ("Narrow kerning of system font in macOS Catalina")  because this seems to be the underlying issue of #82109. Not sure whether they are really related though.

**Comment by rubjo** [comment] 2019-10-15 05:45
Are you sure this is a duplicate of #82109?

Issues shown in screen recording:
- Oblique style chosen over italic style for all weights apart from 600.
- Weights 200 and 300 are wrong for the oblique text, seems to use 100.
- Weights 100 and 200  are wrong for the normal text, seems to use 300.

(Weights 800 and 900 are not installed, so that's fine.)

**Comment by alexandrudima** [comment] 2019-10-15 10:30
No, you're right, I'm not sure it is a duplicate... But it is similar...

**Comment by rubjo** [comment] 2020-02-26 20:49
On latest macOS 10.15.4 beta (19E234g) with latest VS Code Insiders (1.43.0-insider), this has become decidedly less weird.
 
<img width="844" alt="Skjermbilde 2020-02-26 kl  21 42 03" src="https://user-images.githubusercontent.com/42270947/75385895-f8e69100-58e0-11ea-9f64-b003c8c7a785.png">

Everything works for me now, apart from this: weights 100, 200 and 300 all seem to employ the 100 (thin) variant.

**Comment by coltborg** [comment] 2020-03-12 14:27
For me, font weight `600` is applying `oblique` instead of the correct `italic` face:

https://www.loom.com/share/03f0417b445e4296ada958ddf747d14c

**Comment by deepak1556** [comment] 2020-11-05 09:12
Is this still an issue with latest stable ?

**Comment by Kataract** [comment] 2020-11-09 17:36
I'm no longer having this issue, no

**Comment by deepak1556** [comment] 2020-11-09 18:40
Thanks for confirming, closing per above comment.

**Closed by deepak1556** 2020-11-09 18:40 UTC
Labels: font-rendering, needs more info
