### ISSUE TITLE
Slow laggy window resize performance

### ISSUE THREAD

**Issue by Elie77350** [microsoft/vscode#165835] opened 2022-11-08 16:51 UTC
Does this issue occur when all extensions are disabled?: Yes/No

When I resize the window of vscode, the status bar is unhooked from the body of the vscode, is this a normal operation?
- VS Code Version: Code 1.73.0 (https://github.com/microsoft/vscode/commit/8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:33:40.745Z)
- OS Version: Darwin arm64 22.1.0

Steps to Reproduce:

1. the window of vscode is no on fullscreen
2. resize the window like you see on the clip

https://user-images.githubusercontent.com/75457081/200623535-ccd5ccc4-d7e7-4279-afda-f08a32f97a57.mov

**Comment by Elie77350** [comment] 2022-11-08 16:56
![Capture d’écran 2022-11-08 à 17 53 46](https://user-images.githubusercontent.com/75457081/200626845-3a8b0aaf-c68e-4858-8527-9eef5303c871.png)

I work on a Mac Studio computer with 32gb of ram, with 5 open windows, two browsers and three files

**Comment by bpasero** [comment] 2022-11-09 04:01
From my memories of looking into this I came to the conclusion that it is just how Electron behaves. For example while I can reproduce this for VS Code on desktop, I cannot reproduce it on https://insiders.vscode.dev.

For example: https://github.com/electron/electron/issues/23980

Moving to Deepak for comment, maybe there is a more recent issue. Would be great to understand what is causing the difference to the Chrome browser.

**Comment by Elie77350** [comment] 2022-11-09 19:25
I just tested on vscode insiders desktop (not the web version) and the problem does not occur!

**Comment by Elie77350** [comment] 2022-11-09 19:29
we can close the topic! I also just tested it on the non-insider vscode version, on the 1.73.1 update, there is no problem anymore

**Closed** 2022-11-09 19:59 UTC
Labels: freeze-slow-crash-leak, electron

**Comment by jackpopo** [comment] 2022-12-15 09:19
I'm still having this issue with VSCode 1.74.1 for mac intel.

VSCode Version: 1.74.1
Mac version: MacBook Pro 16" 2019 base model. macOS 13.1

as seen in this clip:
[https://youtu.be/v0PooTM42jE](url)

**Comment by bpasero** [comment] 2022-12-15 11:10
Yup, we still seem to have an issue, see related:
https://github.com/microsoft/vscode/issues/165835
https://github.com/microsoft/vscode/issues/168547
https://github.com/microsoft/vscode/issues/165441
https://github.com/microsoft/vscode/issues/169142

**Comment by deepak1556** [comment] 2022-12-16 11:14
Please follow https://github.com/microsoft/vscode/issues/169142 for updates on this issue.
