### ISSUE TITLE
[cpp] support cpp block comment as an auto-closing pair

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode#72801] opened 2019-04-24 10:40 UTC
**Description**

Currently, when editing a `cpp` file, the command <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>a</kbd> (toggle block comment) generates the following comment placeholder `/* */`.

https://github.com/Microsoft/vscode/blob/1cf51f4f5b970384a4cccd3df5d5d00fa9178468/extensions/cpp/language-configuration.json#L4

I wonder if it might be also wise to include this as an auto-closing pair so that when users attempt to write `/*` the closing `*/` is automatically added like other languages (ex: Typescript).

https://github.com/Microsoft/vscode/blob/1cf51f4f5b970384a4cccd3df5d5d00fa9178468/extensions/cpp/language-configuration.json#L11-L16

```ts
{ "open": "/*", "close": "*/", "notIn": ["string"] }
```

**Comment by vince-fugnitto** [comment] 2019-04-24 12:35
@jrieken I'm not quite sure as to who or where the owner is for the extension. 
Looking at the [file history](https://github.com/Microsoft/vscode/commits/master/extensions/cpp/language-configuration.json) I noticed multiple past updates to support additional features.
Isn't the proposed feature request present in the issue similar to those past updates?

**Comment by jrieken** [comment] 2019-04-24 12:39
Oh, you are right. This part is us, not the extension. Sorry for the confusion...

**Comment by alexr00** [comment] 2019-04-24 13:24
Looks like a good change to me. Feel free to make a pull request.

**Comment by deepak1892** [comment] 2019-04-24 15:05
Not able to reproduce ctrl+shift+a not having any effect.

**Comment by vince-fugnitto** [comment] 2019-04-24 15:20
> Not able to reproduce ctrl+shift+a not having any effect.

I assume you are editing a `cpp` file, but sorry the keybinding I mentioned is for Linux, on macOS for example the keybinding is `option + shift + a`. 

The easiest way to test is to simply run the command `Toggle Block Comment` from the
 menu `Edit` 🡒 `Toggle Block Comment` :)

**Comment by deepak1892** [comment] 2019-04-24 15:52
> > Not able to reproduce ctrl+shift+a not having any effect.
> 
> I assume you are editing a `cpp` file, but sorry the keybinding I mentioned is for Linux, on macOS for example the keybinding is `option + shift + a`.
> 
> The easiest way to test is to simply run the command `Toggle Block Comment` from the
> menu `Edit` 🡒 `Toggle Block Comment` :)

Got it, in windows it is Shift+Alt+A.

**Comment by cedric05** [comment] 2019-05-04 03:22
landed in https://github.com/theia-ide/theia/pull/4977.
this issue can be closed

**Comment by vince-fugnitto** [comment] 2019-05-15 14:19
I forgot to mention I won't be able to submit a PR myself due to my company policy. 
If anyone would like to take on the issue, please feel free to do so :)

**Comment by Daniel-McCarthy** [comment] 2019-05-16 19:07
@vince-fugnitto
In that case, I am more than happy to make a pull request for this. Thanks for the information.
I will submit one soon.

**Comment by vince-fugnitto** [comment] 2019-05-16 21:04
@Daniel-McCarthy thank you!

**Closed** 2019-05-21 10:35 UTC
Labels: editor-autoclosing, feature-request, help wanted, languages-basic
