### ISSUE TITLE
Explorer file tree randomly collapses

### ISSUE THREAD

**Issue by berkeleybross** [microsoft/vscode#116190] opened 2021-02-09 12:25 UTC
Issue Type: <b>Bug</b>

When opening files by selecting them in the explorer file tree, it sometimes randomly collapses the tree, up to the workspace folder. E.g. given files of this structure:

Workspace 1
  - File a
  - Folder b
    - File c
    - File d

Workspace 2
  - File e

Selecting File C will open it, but also collapse Workspace 1 (leaving just workspace 2 open and File e visible). Clicking the "refresh" button at the top of the tree correctly expands the tree with the current file selected.

It takes flicking back and forth between two files several times to reproduce, but it happens randomly during the course of normal usage.

This happens with and without extensions enabled. My current machine is Ubuntu 20.04, but my colleagues have experienced it on Windows and on Mac, for the same workspace.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.8.0-38-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3990)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.01GB (3.93GB free)|
|Process Argv|--disable-extensions --no-sandbox --crash-reporter-id 5cae6add-27ba-4a49-bdfc-595bfadb227f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment] 2021-02-09 15:35
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Jason3S** [comment] 2021-02-17 09:30
I have the same issue. For me it is related to parts of the folder structure changing in the background through a build process.

It is very annoying to have the explorer tree close randomly while exploring. Even the folder for the file currently opened in the editor gets closed.

Note: This seems to be mostly fixed in the insiders build, but not completely. The whole tree jumps around a lot making navigation challenging, but the folders do stay open.

If you wish to see it happen:
- clone repo: [streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell)
- open `cspell.code-workspace` in VS Code
- open a terminal `cspell-monorepo`
- `npm i` - to cause everything to build
- try navigating while the build takes place.

**Comment by isidorn** [comment] 2021-02-17 09:41
Since you say this is almost fixed in insiders then there is no need to look into this since it sounds like it is better in latest.

**Comment by Jason3S** [comment] 2021-02-17 12:05
It is not exactly fixed. The workspace folder ONLY stays expanded if you have one of the files open in the editor.
If you do not, it will collapse. See gif below:

![screen-recording](https://user-images.githubusercontent.com/3740137/108201877-a53c0b80-7120-11eb-9cb1-6f42b49b17fc.gif)

**Closed** 2021-05-04 18:17 UTC
Labels: *out-of-scope, file-explorer, needs more info

**Comment by proimage** [comment] 2022-03-10 11:57
I'm getting a very similar issue, where clicking a folder that is not highlighted will collapse the top-most parent of that folder, and then the click will get registered on whatever folder or file is beneath the mouse cursor (now that the intended target has been collapsed out of view). New issue, or similar enough to reopen this?
