### ISSUE TITLE
Typing a '(' inside another () pair marks the existing ')' as paired with the new '('

### ISSUE THREAD

**Issue by Arshia001** [microsoft/vscode#74347] opened 2019-05-26 06:42 UTC
Issue Type: <b>Bug</b>

1. Enter this code into the editor:
`console.log(something);`

2. Start to add a function call inside `log`:
`console.log(String(something)`

3. Now the existing `)` is highlighted. Even if you skip over `something` and type a `)`, it'll be ignored. To type the second closing parenthesis you need to type two `)`s.

I'd expect the editor to leave the existing `)` alone in this case, since it's already matched to another `(`; and to be able to type the second `)` by typing it just once.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yume-chan** [comment] 2019-05-28 02:15
duplicate of #37315

**Comment by octref** [comment] 2019-05-28 10:23
Duplicate of #37315.

**Closed** 2019-05-28 10:23 UTC
Labels: *duplicate
