### ISSUE TITLE
8GB of Cache files in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by AlanRosenthal** [microsoft/vscode#113421] opened 2020-12-25 15:13 UTC
- VSCode Version:
```
code -v      
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Running Ubuntu 20.04 and I checked my disk usage.
Looks like there are lots of cache files from the cpptools extension.
A) There's multiple folders of cache files, is this expected?
B) Cache files are in **XDG_CONFIG_HOME** and not **XDG_CACHE_HOME**

![image](https://user-images.githubusercontent.com/1288897/103137726-66965180-4699-11eb-9a66-4e1165dfd443.png)

**Comment by sean-mcmanus** [comment] 2020-12-30 17:33
I think this is a duplicate of https://github.com/microsoft/vscode/issues/3884

**Closed** 2021-01-04 08:41 UTC
Labels: *duplicate
