### ISSUE TITLE
"Publish Branch" button gets stuck in loading state

### ISSUE THREAD

**Issue by levrik** [microsoft/vscode#234410] opened 2024-11-22 10:41 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 (started happening after update to 1.95.0)
- OS Version: macOS Sonoma 14.7.1

Steps to Reproduce:

1. Create new branch
2. Make a commit
3. Click "Publish Branch" button

It gets stuck after pushing successfully. The state resets after I make a commit manually through the `git` CLI.

![Image](https://github.com/user-attachments/assets/72cb1079-5c83-45fe-a46c-e4eb6385343d)

Logs during and after the push:

```
2024-11-22 11:45:55.562 [info] > git push -u origin bisect-test-2 [1873ms]
2024-11-22 11:45:55.562 [info] remote: 
remote: Create a pull request for 'bisect-test-2' on GitHub by visiting:        
remote:      https://github.com/<REDACTED>/pull/new/bisect-test-2       
remote: 
To github.com:<REDACTED>.git
 * [new branch]        bisect-test-2 -> bisect-test-2
2024-11-22 11:45:55.615 [info] > git config --get commit.template [52ms]
2024-11-22 11:45:55.684 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/bisect-test-3 refs/remotes/bisect-test-2 [120ms]
2024-11-22 11:45:55.720 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [32ms]
2024-11-22 11:45:55.825 [info] > git status -z -uall [139ms]
2024-11-22 11:45:55.847 [info] > git merge-base refs/heads/bisect-test-2 refs/remotes/origin/bisect-test-2 [20ms]
2024-11-22 11:45:55.889 [info] > git diff --name-status -z --diff-filter=ADMR 7435a71f2251837b70023e0e91ef850b0a452d8f...refs/remotes/origin/bisect-test-2 [41ms]
```

**Comment by lszomoru** [comment] 2024-11-30 16:28
@levrik, are you saying that the branch gets published successfully (at least I am not seeing any errors in the logs) but the SCM action button remains as "Publish Branch"? Are you able to reproduce this in one repository or any of your repositories? Are you able to reproduce every time you try to publish a branch? Thanks!

**Comment by levrik** [comment] 2024-11-30 19:04
@lszomoru Yep, the "Publish Branch" button remains in the disabled loading state but the branch gets published successfully. I think it happens in any of my repositories but let me confirm this when I'm back on my work MacBook on Monday. And yes, it reproduces every time.

**Comment by lszomoru** [comment] 2024-12-02 08:42
@levrik, could you please download and install the latest VS Code Insiders release (version details below) as I have added some more logging hoping that it will help track down the root cause. After you install the latest VS Code Insiders release could you please follow these steps:
1. In the main menu choose View -> Output
2. Use the channel picker on the right side of the panel and choose "Git"
3. Use the gear icon on the right side of the panel and choose "Trace"
4. Use the gear icon on the right side of the panel and choose "Set as Default"
5. Open the folder/workspace, create a new branch and publish it
6. Share the contents of the Git output window along with the screen recording

```
Version: 1.96.0-insider
Commit: 2ed1e9b48c8f55e1b92322a992c6c12b1e86e444
Date: 2024-12-02T05:06:23.390Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

**Comment by levrik** [comment] 2024-12-02 09:25
@lszomoru I can confirm that it also happens in other workspaces/repos. I'll give the latest Insiders version a try and follow up with the logs here.

**Comment by lszomoru** [comment] 2024-12-02 09:51
Thank you! This is a duplicate of https://github.com/microsoft/vscode/issues/231108. I am working on a fix now.

**Closed** 2024-12-02 09:51 UTC
Labels: bug, info-needed, git, *duplicate

**Comment by levrik** [comment] 2024-12-02 10:16
@lszomoru Awesome. Somehow I didn't find this issue when I was searching for existing ones.
