### ISSUE TITLE
Terninal powershell 'cls' command operation result suggest

### ISSUE THREAD

**Issue by CyanGlory** [Microsoft/vscode#34829] opened 2017-09-22 11:48 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
markdown-toc|Ala|1.5.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
es7-react-js-snippets|dsz|1.1.0
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|1.3.0
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
code-runner|for|0.7.1
beautify|Hoo|1.1.1
useful-react-snippets|igo|1.0.9
path-autocomplete|ion|1.6.1
docthis|joe|0.4.8
mdhelper|jos|0.0.11
vs-color-picker|lih|0.6.0
vscode-todo-parser|min|1.9.1
vscode-extension-auto-import|mop|1.3.3
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.13.0
autoimport|ste|1.2.2
react-beautify|tai|0.3.0
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.🥇open ternimal with powershell
2.🥈 input cls and enter it
3.🥉 It not clear the panel, and just the slider slides down when the content is too nuch.

---

![b4 fmq2c7yq4or8ywii7eho](https://user-images.githubusercontent.com/22830374/30742874-d644f390-9fcd-11e7-8414-5d0a16847cfe.png)

```js
// this is not a serious problem, but nobody will be willing to clear them's panel by close it.
// thanks for your attention, my friends. —— a 😋 vscode user.
```

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment] 2017-09-26 06:50
Duplicate of sourcelair/xterm.js#106

It's currently by design. If you want to truly clear the console, use the `Terminal: Clear` command (the default keybinding is <kbd>Ctrl/Command</kbd> + <kbd>K</kbd>).

**Comment by Tyriar** [comment] 2017-09-28 13:52
Thanks @yume-chan, closing as duplicate of https://github.com/sourcelair/xterm.js/issues/106

**Closed by Tyriar** 2017-09-28 13:52 UTC
Labels: integrated-terminal
