### ISSUE TITLE
Debug console launches on Run

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode#212918] opened 2024-05-16 17:54 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  
- OS Version:  all

Submitting feedback from Diary study conducted, watching participants attempting to run their projects while learning C#.

Steps to Reproduce:

1. Create a new C# project (I've reproduced this in other languages as well)
2. Select to Run (happens when using menu and the run button.
3. Debugger console launches and sends user into debug session.

**Comment by webreidi** [comment] 2024-05-16 17:55
@isidorn This is the debug on run issue we talked about today.

**Comment by WardenGnaw** [comment] 2024-05-16 18:18
This should be a C# Dev Kit experience issue.

This should be resolved with https://github.com/microsoft/vscode/pull/209893

**Comment by webreidi** [comment] 2024-05-16 21:16
No, this should not be a C# Dev Kit experience issue. Isidor was mentioning that there is a part when you run for the first time, that it could call the debugger when it shouldn't, which is why Isidor asked me to open this issue.

**Comment by isidorn** [comment] 2024-05-16 23:13
The gist of the issue is that here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugService.ts#L607
We should check if user is in debug mode. And if they are in Run mode, we do not open debug console. I can fix this in June if Rob agrees with the change.

**Closed** 2024-12-10 10:43 UTC
Labels: bug, debug
