### ISSUE TITLE
Implement conditional function breakpoints

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#9106] opened 2016-07-12 00:32 UTC
- VSCode Version: 1.3.0
- OS Version: All

The debugging protocol for VSCode [supports](https://github.com/Microsoft/vscode-debugadapter-node/blob/c7e7fbd601913ec42102533ba428a0123387341f/protocol/src/debugProtocol.ts#L780) conditional function breakpoints.

However, I don't see how this can be achieved through the VSCode UI, since adding a condition is done through the glyph in the editor, but function breakpoints don't have a glyph:

![screen shot 2016-07-11 at 5 28 19 pm](https://cloud.githubusercontent.com/assets/637952/16751284/feba8a0a-478c-11e6-82ac-0adb86ba594b.png)

A solution to match the current experience for line breakpoints would be to implement https://github.com/Microsoft/vscode/issues/7262.

Is there a reason why there is no action to add a condition to a breakpoint from the Breakpoints panel?

@weinand @isidorn

**Comment by f111fei** [comment] 2016-07-12 02:00
![4](https://cloud.githubusercontent.com/assets/7069719/16752828/3e9a75ce-4817-11e6-804a-39d0fe97968f.png)

Right click on line number. `Edit BreakPoint` is conditional function breakpoints. this is similar to `chrome`

**Comment by weinand** [comment] 2016-07-12 09:44
The '+' action adds function breakpoints:

![2016-07-12_11-44-11](https://cloud.githubusercontent.com/assets/1898161/16762710/faa5e93e-4825-11e6-9754-630d7fa6ca45.png)

**Comment by edumunoz** [comment] 2016-07-12 16:49
@f111fei, function breakpoints don't show a glyph on the line number (and hence referencing issue #7262).

@weinand, how do you add a condition to function breakpoints? I don't see a way.

**Comment by weinand** [comment] 2016-07-12 19:58
@edumunoz oh I see, the question was about how to add the 'condition' and not how to add the 'function breakpoint'. Sorry, I missed that.

**Comment by weinand** [comment] 2016-07-12 20:01
@isidorn I don't see a reason why a context action 'Edit Condition' in the breakpoints view wouldn't work, right?

**Comment by isidorn** [comment] 2016-07-19 10:05
The UI for editing breakpoints is bound to the editor, thus if a breakpoint is in file a.txt, then editing that breakpoint would open that file and show the breakpoint widget on top of the line where the breakpoint is. That is the reason why we did not include 'edit breakpoint' in the viewlet, but only in the editor.

The issue here is that function breakpoints are not tied to an editor or a line, so I am not sure where to show the breakpoint widget in that case. We could just show it on top of the active editor, though then it is not in pair with the regualr edit breakpoint experience.

Suggestions welcome

**Comment by weinand** [comment] 2017-04-05 10:15
duplicate of #3646

**Closed by weinand** 2017-04-05 10:15 UTC
Labels: debug, feature-request
