### ISSUE TITLE
Make keybindings accept multiple commands (macro support)

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode#177492] opened 2023-03-17 15:45 UTC
In `keybindings.json`, we can add keyboard shortcuts that will perform *one* action. Example:

```json
{
  "key": "ctrl+k l",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "langId": "typescript",
    "name": "Log copied variable"
  }
}
```

However, VSCode would be much, *much* more powerful if one keybinding could perform multiple actions at the same time.

```json
{
  "key": "ctrl+k l",
  "when": "editorTextFocus",
  "macro": [
    { "command": "editor.action.clipboardCopyAction" },
    { "command": "cursorEnd" },
    {
      "command": "editor.action.insertSnippet",
      "args": { "langId": "typescript", "name": "Log selected variable" }
    }
  ]
}
```

**Comment by ulugbekna** [comment] 2023-03-17 16:07
Duplicate of https://github.com/microsoft/vscode/issues/871

**Closed by ulugbekna** 2023-03-17 16:07 UTC
