### ISSUE TITLE
Tasks print "Terminal will be reused" even when presentation.panel set to "new"

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#35642] opened 2017-10-05 20:07 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.13.4-200.fc26.x86_64

---

This is just a little nitpick. When running a task with

```json
	"presentation": {
		"panel": "new"
	}
```

the terminal prints

```
Terminal will be reused by tasks, press any key to close it.
```

But that terminal will never be reused as I've disabled that in my tasks.json.

**Comment by dbaeumer** [comment] 2017-11-08 15:38
To verify under Windows. Tasks.json
```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
    "windows": {
        "options": {
            "shell": {
                "executable": "${env:windir}/System32/WindowsPowerShell/v1.0/powershell.exe",
                "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
            }
        }
    },	
	"tasks": [
		{
			"label": "dir",
			"type": "shell",
			"command": "dir",
			"presentation": {
				"panel": "new"
			},
			"problemMatcher": []
		}
	]
}
```
When executed the terminal prints
```
Press any key to close the terminal.
```

**Comment by roblourens** [comment] 2017-12-06 01:09
If I have a watch task, and kill it with `^C`, it still writes "Terminal will be reused by tasks..." in this case. Is that by design?

**Comment by dbaeumer** [comment] 2017-12-06 10:02
@roblourens no it should not. Will reopen and have a look.

**Comment by dbaeumer** [comment] 2017-12-06 20:27
I retested it and it write `Press any key to close the terminal.` to the terminal which is expected. I will close the issue again.

**Closed by dbaeumer** 2017-12-06 20:27 UTC
Labels: bug, tasks, verified

**Comment by kamenlitchev** [comment] 2017-12-08 09:14
The complaint is that the message should NOT be there.

**Comment by dbaeumer** [comment] 2017-12-11 08:49
This message is by design. Why would you not see it.

**Comment by NathanUr** [comment] 2017-12-16 09:48
It is a problem for me to, because I would like to have some command to be executed with a shortcut key, so will busy, just type the key combination and go on. This way I have to close the terminal every time while the purpose was to automate tasks.

**Comment by dbaeumer** [comment] 2017-12-18 09:54
@NathanUr then you should not use 'new'. If you always want to use the same terminal simple use 'dedicated'

**Comment by ShaunTennant** [comment] 2018-01-01 13:11
Long time reader first EVER GitHub comment so apologies in advance.

I would like to suppress (perhaps optionally) the terminal message(s) "Press any key to close the terminal." / "Terminal will be reused by tasks, press any key to close it." etc. for the following reasons:
1. Mixing a user's program’s output with the IDE’s output is inappropriate and like a "Separation of Concerns" issue.
2. Particularly in the cases of "panel": "shared" and "dedicated" the user has indicated the intent to continue to use the panel in the future. Hence a reminder to close then panel does not match the users intent i.e. use case.
3. It is redundant as there already is a "Trash Can" icon at the top of the terminal window to perform the same function.
4. There are many keyboard shortcuts in the IDE but apart from menu items, very few have a full sentence dedicated to them to remind the user i.e. not consistent with the rest of the IDE’s interface
5. "version": "0.1.0" of tasks.json did not have this behaviour.
6. Other people see https://stackoverflow.com/questions/47946868/how-to-get-rid-of-terminal-will-be-reused-by-tasks-press-any-key-to-close-it

Possible solutions:
a) Turn-off reminder message(s) completely – my preferred solution.
b) Turn-off reminder message(s) for "panel": "shared" and "dedicated" use cases - a compromise.
c) Add option to suppress reminder message(s) in the "presentation" group of tasks.json - flexible but adds unnecessary complexity.
