### ISSUE TITLE
Workspace edits from chat participants can't be opened or applied

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#210700] opened 2024-04-18 23:06 UTC
I recently tried to generate workspace edits in `/fixTestFailure`. I can verify the URI being given to `stream.textEdit` is valid: it matches the URI I had open already (in a diff editor from the SCM view):

![Image](https://github.com/microsoft/vscode/assets/2230985/37022a15-ba36-4c0b-9632-d6e80b83d2f6)

The edits show up correctly in the Refactor preview. It has the original line contents in the edit preview, so it's able to access the resource...

![Image](https://github.com/microsoft/vscode/assets/2230985/e8cc163e-15e8-4879-bc2a-fb4ab600063c)

However, applying them does nothing and clicking on the file leads to:

![Image](https://github.com/microsoft/vscode/assets/2230985/c706261f-2020-4ca2-b188-f9c2c4efbfb9)

**Comment by connor4312** [comment] 2024-04-18 23:16
Comes from here, looks like @aiday-mar touched this area recently:

![Image](https://github.com/microsoft/vscode/assets/2230985/972135e5-d56d-447f-98ea-596b6a4f90b7)

**Comment by connor4312** [comment] 2024-04-18 23:44
Oh, I think this might be due to the workspace edit have overlapping ranges. I've not fixed that yet, but this failure mode is very unclear. There were no errors thrown into the console, I had to debug VS Code to figure out the cause.

**Comment by aiday-mar** [comment] 2024-04-19 07:13
Hi @connor4312 this looks like it could be caused by the recent work on opening the multi diff editor from the refactor view pane. Could you please share the code you used to reproduce this error? I'll dig into the code. Thank you.

**Comment by jrieken** [comment] 2024-04-19 17:29
> I recently tried to generate workspace edits in /fixTestFailure. 

@connor4312 this is really poorly supported at the moment because of the provider to participant migration. Participants don't support workspace edits yet. Until now only /tests used workspace edits and only its specific use-case is supported right now

**Comment by connor4312** [comment] 2024-04-19 18:01
I verified this was fixed when I corrected the bug that led to overlapping edits in `fixTestFailure`. I'll leave it open if we want to make this failure mode more explicit.

**Comment by aiday-mar** [comment] 2024-12-12 09:34
This should be fixed now. Since there was no further activity on this thread, I will close this issue.

**Closed by aiday-mar** 2024-12-12 09:34 UTC
