### ISSUE TITLE
When closing the Code, the running `bash` will not exit properly and not save the history 

### ISSUE THREAD

**Issue by CastleStar14654** [microsoft/vscode#179833] opened 2023-04-13 02:29 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

1. Open Code, launch the terminal inside
2. Run whatever command in this terminal
3. Directly and properly close the whole VS Code
4. `~/.bash_history` has not been appended with what we just did in the Code terminal
5. If, however, logout the terminal (e.g. by `Ctrl + D`) first, then `~/.bash_history` is updated as expected

The same problem also exists on Windows version (1.77.3, Windows 11 Home 22H2 22621.1555) for the `bash` with SSH- or WSL-Remote.

**Comment by CastleStar14654** [comment] 2023-04-13 02:46
Since both `gnome-terminal` on Linux or the Windows Terminal could handle the close of the window by logging out all sub-shells, I suppose that it is also possible for VS Code.

**Comment by akpircher** [comment] 2023-04-14 23:45
I think VSCode _used_ to exit the shell properly and save the command history. 

My `terminal.integrated.persistentSessionReviveProcess` setting is set to `"never"`, because opening VSCode with a clean/fresh terminal helps me stay focused on whatever I need to work on **now**, which is not necessarily where I left off. (In a similar vein, it would be nice to have a setting where I could open up a workspace and not have all of the previously opened files open)

The whole point of an interactive shell's exit process is so that programmers don't have to remember to call the `history` to manually save terminal history to the `$HISTFILE`, or to specifically run "exit" when closing a program.

Is it VSCodes' intention to have their users rely solely on the programs cache or nothing at all? That would make VSCode completely unusable for me, and if this is the case then I need to find another IDE.

**Comment by david-fong** [comment] 2023-04-19 05:26
Duplicate of #151105? (I'm in favour of changing that one's title to be non-windows specific)

**Closed** 2023-04-19 17:05 UTC
