### ISSUE TITLE
shellscript syntax highlighting broken after update to v1.76.0

### ISSUE THREAD

**Issue by kikodn** [microsoft/vscode#175837] opened 2023-03-02 05:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0
- OS Version: Linux Mint 21.1 Cinnamon

Steps to Reproduce:

1. Update vscode to latest version 1.76.0

There was a similar issue with the update from v1.74.3 to v1.75.0. Then it was fixed in v1.75.1 and now it shows up again in v1.76.0.
Please dedicate some time to make it work properly, or don't touch it otherwise. There are people, such as myself that work with shell scripts on a day to day basis and rely on the syntax highlighting.

**Comment by frypf** [comment] 2023-03-02 19:23
`"${variable}"` is no longer being highlighted within VSCode when used as an argument to a command or function.

Furthermore, every unquoted `${variable}` loses correct highlighting of its opening and closing bracket (from the colouring, they look like they are being are being bracket matched).

I enabled better-shell-syntax extension to see if any improvements were made in the upstream version. While it does improve the highlighting of variables inside strings, case statements no longer correctly recognise that they should be part of an `unmatchedBracketScope` and every `punctuation.definition.case-pattern.shell` within turns red.

**Comment by connorwehrum** [comment] 2023-03-03 16:23
Commenting for visibility. seeing similar issues.

![image](https://user-images.githubusercontent.com/125694861/222772957-ab0451a3-7e59-49c5-b07b-f8545094bbf4.png)
All variables in ${} should be highlighted and aren't.

**Comment by alexr00** [comment] 2023-03-07 15:40
Duplicate of https://github.com/microsoft/vscode/issues/176190

**Closed by alexr00** 2023-03-07 15:40 UTC
