### ISSUE TITLE
Hard lock / crash when opening a header file with a c++ macro

### ISSUE THREAD

**Issue by jseward** [microsoft/vscode#80734] opened 2019-09-11 17:49 UTC
Issue Type: <b>Bug</b>

Opening the following file with the contents below will hard lock and crash vs.code.

`enum.h`

```
#define DEFINE_ENUM(EnumName, ...)                                                                                                         \
                                                                                                                                           \
	enum class EnumName : int                                                                                                              \
	{                                                                                                                                      \
		__VA_ARGS__                                                                                                                        \
	};                                                                                                                                     \
```

This seems to be a regression, as I'm sure I've opened this file many times before in the past.

I have verified this happens on other machines (fresh install of vs.code)

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|2.2.2
gc-excelviewer|Gra|2.1.32
jbockle-format-files|jbo|3.0.0
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34911
powershell|ms-|2019.5.0
tabnine-vscode|Tab|2.1.11
hlsltools|Tim|1.0.4
vscode-lua|tri|0.12.4
vscode-icons|vsc|9.3.0
vscode-proto3|zxh|0.3.0

</details>

**Comment by matter123** [comment] 2019-09-11 20:17
@alexr00 This is likely the same root cause as #78769 (class/enum declaration inside of a macro)

@jseward You can fix this now by installing the upstream C++ grammar https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax

**Comment by jseward** [comment] 2019-09-12 05:44
Thanks @matter123 . Installing that linked extension did indeed resolve my issue.

**Comment by alexr00** [comment] 2019-09-12 07:29
Duplicate of https://github.com/microsoft/vscode/issues/78769 
@jseward You can also use VS Code insiders to get the fix there!

**Closed** 2019-09-12 07:54 UTC
Labels: *duplicate

**Comment by alexr00** [comment] 2019-09-16 10:28
Updated with https://github.com/microsoft/vscode/commit/8601a47040ef5338f9bbd9b0aeb8454538c93f04
@matter123 thank you for pointing that out!
