### ISSUE TITLE
Add API to set language mode in an editor without modifying settings json files

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#78968] opened 2019-08-12 16:13 UTC
This request is specifically to allow the following issue with the C++ plugin to be resolved in an acceptable way: https://github.com/microsoft/vscode-cpptools/issues/722

**Problem**
Users workspace settings are constantly being modified by the C++ extension purely to allow the extension to be enabled for standard library headers since they don't have file extension. It adds entries to `files.associations` to set the language to `cpp`.

This is problematic because 1) it bloats workspace settings to the point that the *majority* of the file becomes this clunky workaround to get language support in a *standard header*. 2) it causes frequent noise in version control and can easily conflict.

**Request**
Allow extensions to specify the language mode for an editor they open. When I go to definition on an identifier or a `#include` that leads to a standard library header the extension knows the destination file is a C++ file and should be able to treat it as such without changing the users settings files.

VS Code already has support for setting the language mode of an editor in-memory, without changing settings files so it should be a relatively small step to enable this functionality. (For example, when creating a new, untitled, unsaved file the language can still be set.)

**Comment by usernamehw** [comment] 2019-08-12 16:18
```ts
vscode.languages.setTextDocumentLanguage(document, languageId);
```

**Comment by sean-mcmanus** [comment] 2019-08-12 20:22
The problem is that our extension doesn't control the opening of the files in the Go to Def, Find All References, etc. scenarios -- we just return the file locations and there's no APIs for telling VS Code that those file locations should be treated as a particular language when the locations are clicked in the VS Code UI to trigger the file opening.

**Comment by jrieken** [comment] 2019-08-13 10:32
> When I go to definition on an identifier or a #include that leads to a standard library header the extension knows the destination file is a C++ file and should be able to treat it as such without changing the users settings files.

I am I correct that you only know a file is C++ once it's being "referenced/included" by a true C++ file? E.g you don't know that `foo.bar` is C++ until it occurs as a Go to Def, Find Ref etc result?

> Allow extensions to specify the language mode for an editor they open. 

Nit but this decision is made when opening a document, not showing a document inside an editor. Then, assuming the document (or an editor for it) is already open, using *fooLang*, then I assume you want to change the language, right? I think that would make `setTextDocumentLanguage` a workable solution, right? Remember the files that need "special language id treatment" and once they appear use above API to set the language.

**Comment by akbyrd** [comment] 2019-08-13 16:50
@sean-mcmanus Are you able to get the document reference after it is opened? If so, it looks like the first API to change the language mode of an existing document might work?

@jrieken I *think* it'd be possible to know they are C++ files since they're in the include paths set for the project, but that seems to be orthogonal. From what Sean says you can't feed the language through the APIs that end up opening the document. In any case, your recommendation sounds plausible.

**Comment by sean-mcmanus** [comment] 2019-08-13 19:09
Yeah, thanks for the info -- we can try using setTextDocumentLanguage instead of adding files to files.associations.

**Comment by jrieken** [comment] 2019-08-14 07:20
Alright, closing as *dev-question. Ping me here when there are questions left

**Closed** 2019-08-14 07:20 UTC
Labels: *dev-question, editor-symbols, needs more info
