### ISSUE TITLE
folder rename does not result in updated path

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#164562] opened 2022-10-25 10:35 UTC
Testing #164522

Given this setup:

<img width="917" alt="CleanShot 2022-10-25 at 12 31 35@2x" src="https://user-images.githubusercontent.com/1898161/197751037-d94a83a4-98ae-4a93-a205-fc257d84b30b.png">

renaming folder "foo" to "bar" does trigger the prompt but the path "/foo/file_2.md" is not updated (and gets broken).

**Comment by joyceerhl** [comment] 2022-10-27 18:05
Still repros for me: 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/30305945/198365410-a2b85354-6d96-41ab-82f5-eb4ffa8c1f3e.png">

**Comment by andreamah** [comment] 2022-10-28 20:08
Still repros for me

[![Image from Gyazo](https://i.gyazo.com/74aa01810f6d2d53f3357c5059884f36.gif)](https://gyazo.com/74aa01810f6d2d53f3357c5059884f36)

**Comment by mjbvz** [comment] 2022-10-28 23:49
Ugh this bug :/ I'm marking it as a candidate because I'm pretty sure the root cause (#164942) effects other markdown features too

**Closed** 2022-10-31 16:32 UTC
Labels: bug, markdown, verification-found, candidate
