### ISSUE TITLE
ctrl-D encountered consequent results and next would find the 2 results together  

### ISSUE THREAD

**Issue by yukuan1988** [Microsoft/vscode#23720] opened 2017-03-31 04:06 UTC
For example, in my text, there are a log of numbers, say, 0.

> 0 0 0 00 0 0 

If I select 2nd 0 and press ctrl-D, it will find the 3rd, next 4th, next 5th, but stop here. Because next it would find 00 together.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|QML|bbenoist|1.0.0|
|relative-path-and-line|bgse|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-angular2-component-generator|dbaikov|0.0.1|
|vscode-new-file|dkundel|2.1.0|
|python|donjayamanne|0.5.8|
|vs-code-xml-format|fabianlauer|0.1.4|
|Go|lukehoban|0.6.52|
|vscode-jsp|pthorsson|0.0.2|
|vscode-format|ryannaddy|0.0.6|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment] 2017-03-31 07:19
Duplicate of #6661

**Closed by alexandrudima** 2017-03-31 07:19 UTC
Labels: editor-multicursor
