### ISSUE TITLE
Explorer: broken after enabling settings sync

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114994] opened 2021-01-26 09:19 UTC
I had a workspace open (with 3 folders) and enabled settings sync. After clicking on the explorer I see now files:

![image](https://user-images.githubusercontent.com/900690/105825478-ec225f80-5fbf-11eb-9f38-5ea70ae33979.png)

And the exception is:

```
bootstrap-window.js:262 TypeError: Cannot read property 'element' of undefined
    at l.element (listView.ts:634)
    at listWidget.ts:221
    at Array.map (<anonymous>)
    at o.splice (listWidget.ts:221)
    at splice.ts:17
    at Array.forEach (<anonymous>)
    at t.splice (splice.ts:17)
    at listWidget.ts:1306
    at d.bufferEvents (event.ts:851)
    at F.splice (listWidget.ts:1306)
    at I.runner (openEditorsView.ts:103)
    at I.doRun (async.ts:732)
    at I.onTimeout (async.ts:726)
```

//cc @joaomoreno

**Comment by bpasero** [comment] 2021-01-26 09:21
It works fine after a restart.

**Comment by isidorn** [comment] 2021-01-26 10:01
The error seems to be coming from the Open Editors view since that one uses the list widget, and you can see it in the call stack. So it is not related to explorer being broken.

I can not reproduce this. Here are my steps:
1. Have a MR workspace with 3 folders (`vscode`, `vscode-distro` and `vscode-docs`)
2. Save that MR workspace as `test.code-workspace`
3. Turn on Settings Sync -> Sign in using GitHub and choose to sync all the data
4. Settings sync is turned on and Explorer works nicely

Do you always see this? If yes do you some other errors or exceptions from the Explroer?

**Comment by bpasero** [comment] 2021-01-26 10:08
@isidorn the explorer being broken in the sense that the view is not showing up. Independent from any errors a view might be throwing that should not have any impact on other views right?

Maybe this is a more general workbench views issue that we need to make sure a runtime exception from one view should not make the other view disappear.

//cc @sandy081

**Comment by isidorn** [comment] 2021-01-26 10:09
@bpasero it should not be possible to hide the Explorer.
So I think you are right this sounds like a general views issue. Let's also assign to @sandy081 he might have ideas

**Comment by sandy081** [comment] 2021-01-27 09:25
Yeah, I can make views rendering resilient but it cannot be handled everywhere - meaning there will be still inconsistent behaviour or errors in the console as the model goes out of sync. 

To improve the experience I can skip rendering the misbehaving view but not all other rippled errors.

**Comment by bpasero** [comment] 2021-01-27 09:28
I wonder if you could leave the view visible so that the layout is not touched but simply render the contents of the view empty or with an error text?

**Closed** 2024-12-12 09:50 UTC
Labels: debt
