### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by olive004** [microsoft/vscode#204668] opened 2024-02-08 00:09 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.86.0
- OS Version: MacOS Darwin x64 20.6.0

Steps to Reproduce:

1. Create a docker container
2. Try to "Attach to running container"
3. Docker container working in terminal, but not connecting in VSCode with this error: `Command in container failed: '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'`

**Comment by IllusionMH** [comment] 2024-02-08 00:19
Looks like duplicate of #204611
What is your container OS?

**Comment by olive004** [comment] 2024-02-08 13:49
Using Ubuntu 22.04 for the container, pulling from the nvidia repo with this command in the Dockerfile

FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 AS workdir_build

Looks indeed like a duplicate of [204611](https://github.com/microsoft/vscode/issues/204611)

**Comment by chrmarti** [comment] 2024-02-08 15:52
The fix for that will be in the next Insiders build (https://code.visualstudio.com/insiders/). Please give that a try and let us know if your problem still occurs.

**Comment by AnElectricalEngineer** [comment] 2024-02-10 08:41
The issue still occurs for me on the 1.86.1 release. The container is based on Gentoo Linux - it works fine on 1.85.2, but I cannot connect to the container when using 1.86.1, and it fails with: `Command in container failed: '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'`

**Comment by AnElectricalEngineer** [comment] 2024-02-12 18:19
@chrmarti After researching the issue further, it looks like it is due to the fact that my container includes two different libstdc++ versions, and the script that checks for libstdc++ in VS Code 1.86.1 currently does not know how to handle this situation. I tried to connect to the same container using the latest Insiders version of VS Code, and the problem does not occur. Looks like a12d9f44fc5f89cb5db5d3e50a5869f2ba5515f0 solved the issue.

If you'd still like me to append the Dev Containers log, please let me know, but I think for now I can consider my issue resolved.

**Closed** 2024-02-13 14:49 UTC
Labels: info-needed
