### ISSUE TITLE
Ability to detect whether a theme is light/dark programatically

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#46940] opened 2018-03-29 14:06 UTC
This has been requested before (#7589) but I don't believe the suggest solution covers all cases (as suggested in the last comment).

I'm trying to insert images into hovers for icons like this:

![](https://user-images.githubusercontent.com/1442874/36900652-e4859276-1e02-11e8-940f-4428b0b17e3b.png)

I have URLs for where the icons live like this:

https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_favourite_white_24px.svg
https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_favourite_black_24px.svg

However without knowing whether the theme is Dark or Light, I can't tell which if the colours to insert.

**Comment by aeschli** [comment] 2018-04-03 10:02
duplicate of #32813 (not exactly, I agree, but it, in the end, it goes in the same direction).

Did you try 'currentColor' in your svg?
(https://css-tricks.com/cascading-svg-fill-color/)

**Closed by aeschli** 2018-04-03 10:03 UTC
Labels: feature-request, themes

**Comment by DanTup** [comment] 2018-04-03 10:47
@aeschli That issue is about access colours; I don't want to know the colour, only if Code considers it light or dark.

I don't think currentColor helps - these SVGs are remotely hosted and I need to choose between the black or white one (I can't modify them unless I pull them all down locally).

**Comment by DanTup** [comment] 2018-04-18 06:45
@aeschli Is it possible this can be reconsidered? I don't think the "duplicate" case is going to help me, I need to know whether to use the black or white version of my image :(

**Comment by aeschli** [comment] 2018-04-18 08:03
Sorry, there are currently no plans for new API in that area.

**Comment by DanTup** [comment] 2018-04-18 08:13
@aeschli Are there any workarounds or other ways I could handle do this? It's frustrating that Code has knowledge of the theme but extensions can't make decisions based on it. On a light theme my white images aren't visible, it looks really bad.

**Comment by aeschli** [comment] 2018-04-18 09:34
Sorry, I'm not aware of any other tricks. Using images in hover is possible but not really the intended usage of hovers.

**Comment by DanTup** [comment] 2018-04-18 09:39
@aeschli The problem is the same wherever I put it. Users have asked for the icon previews in the gutter (this is where IntelliJ shows them) but it's the same issue - we don't know when to use the dark/light versions.

Would you accept a PR that added this somewhere if I could figure out how to do it?

**Comment by aeschli** [comment] 2018-04-18 14:13
In the gutter you can provide both a light and dark version of your icon
