### ISSUE TITLE
Markdown preview doesn't work correctly when zoomed in

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15542] opened 2016-11-15 22:52 UTC
While smoke testing 1.7.2 eb1f17eff8393fa2ab0b1bd7d12bd63fc99146b6

![md](https://cloud.githubusercontent.com/assets/4033249/20327679/04510b00-ab43-11e6-8b5f-ab455606f214.gif)

**Comment by mjbvz** [comment] 2016-11-15 23:56
Thanks. This is a duplicate of #5745, which is tracking general webview zoom problems.

**Closed by mjbvz** 2016-11-15 23:56 UTC
Labels: duplicate
