### ISSUE TITLE
Can't focus on second notification for screen reader

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#188808] opened 2023-07-25 16:27 UTC
Testing #188528

- Open VS Code repo to trigger 2 notifications
- Screen reader reads first notification aloud
- :bug: Screen reader starts reading first notification a second time, then stops seemingly randomly once it gets to `Source...`
- :bug: I click the second notification several times to try to focus it, but the screen reader does not read it. It either reads nothing or something else
- :bug: I realize it was reading the editor content behind the notification. I close that editor, re-select the second notification, and now the second notif is read aloud 
- :bug: Though even with this second notification, it stops part way through (the first time it's read). It gets to the `Install` button but doesn't read aloud `Show Recommendations`

![image](https://github.com/microsoft/vscode/assets/25310137/4d528309-6c19-4eed-bb18-3d171d66a01b)

**Comment by meganrogge** [comment] 2023-07-26 16:24
I should've clarified that this feature should be tested as if you are a screen reader user - using only the keyboard.

I think all of the mouse clicking could be the problem in addition to misunderstanding the expected behavior of a screen reader.

@bamurtaugh could you pls retest using only the keyboard?

**Comment by meganrogge** [comment] 2023-07-26 16:59
EDIT: 

I believe same root cause as #188763, so closing as a duplicate

**Closed by meganrogge** 2023-07-26 16:59 UTC
Labels: info-needed
