### ISSUE TITLE
 Cannot read property 'close' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#53320] opened 2018-06-29 10:10 UTC
Issue Id: <b>bcd612dd-16c7-97df-ba1a-e0ba30e1c1bb</b><br /><br />*Versions* <br />- 1.25.0-insider (6/27/2018 5:14:55 AM)<br />-  07d89abf1522a67f0e8105770505077f454ab021<br />-  368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8<br />*Stack* <br />TypeError: Cannot read property 'close' of null<br />[/vs/platform/issue/electron-main/issueService.ts#81:22](https://github.com/microsoft/vscode/blob/f2fa6bea46bde9856e6a593e4d4c5af2b303ac66/src/vs/platform/issue/electron-main/issueService.ts#L81:22)<br />    at emitOne (events.js:101:20)<br />    at BrowserWindow.emit (events.js:191:7)<br />

**Comment by RMacfarlane** [comment] 2018-07-02 21:03
Duplicate of https://github.com/Microsoft/vscode/issues/51521

**Closed by RMacfarlane** 2018-07-02 21:03 UTC
Labels: issue-reporter
