### ISSUE TITLE
Package.json doesn't autocomplete newest dependency version

### ISSUE THREAD

**Issue by BMorearty** [microsoft/vscode#95130] opened 2020-04-13 16:01 UTC
Issue Type: <b>Bug</b>

When adding a dependency to package.json in a Node project:

* Go to the "dependencies" or "devDependencies" section.
* Start adding a dependency, e.g.:

```
    "typescript
```

* Pause a moment for the package list to appear, then hit the autocomplete character (e.g. Tab or Enter) to complete the statement.

**RESULT**: VSCode autocompletes with a version that is not the newest version of the package.
**EXPECTED**: VSCode autocompletes with the newest version.

The behavior is correct for some packages and incorrect for others. E.g., it's incorrect for the `typescript` and `jest` packages. At the time of this writing, the newest version of typescript is 3.8.3 but the autocomplete fills in `"typescript": "3.4.3"`. And the current newest version of jest is 25.3.0 but the autocomplete fills in `"jest": "25.2.7"`.

Reproduced on two different computers.

Note that the tooltip that appears when you hover over the `typescript` or `jest` package name in the dependencies does show the _correct_ newest version. But the automplete chooses a version that's not the newest.

<img width="455" alt="typescript version hint" src="https://user-images.githubusercontent.com/16927/79136108-5174cf00-7d65-11ea-907a-341c17f32225.png">

![typescript chooses old version](https://user-images.githubusercontent.com/16927/79136099-4c178480-7d65-11ea-9cbb-96d12f32c0c6.gif)

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.2
prettier-vscode|esb|4.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
autolaunch|phi|2.0.3
vscode-graphql|Pri|0.2.14
ruby|reb|0.27.0
vscode-ruby|win|0.27.0

</details>

**Comment by mattacosta** [comment] 2020-04-14 00:03
This is due to npms.io using stale data, which was itself caused by a configuration error on NPM's side. That was fixed in October, and most packages do seem to be getting eventual updates now (they all used to be several months out of date). The notable exception is obviously TypeScript, which is still stuck on the version that was available back then for some reason.

See also: #81280.

**Comment by BMorearty** [comment] 2020-04-14 01:38
You’re right, this looks like a duplicate of #81280.

**Comment by egamma** [comment] 2020-04-27 07:07
Closing as a duplicate of #81280.

**Closed by egamma** 2020-04-27 07:07 UTC
