### ISSUE TITLE
[csharp] Unused variable warning, but variable is written

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2916] opened 2016-02-11 03:02 UTC
![image](https://cloud.githubusercontent.com/assets/12577765/12968515/14730ad4-d041-11e5-9206-c75112175524.png)

I wanted to title this "It's not just a mouthwash!" but...
Anyway, this brought me back to making sure I knew about scope - when I have a variable outside of the if statement, and then reference it inside the if statement, the system shouldn't complain about that. It's perfectly valid syntax. Why does VSCode think my variable is unused? 

This is a C# file (which the little info in the bottom info bar agrees with), running 0.10.8, on Mac OS X Yosemite. This appears to be a new issue.

**Comment by Tyriar** [comment] 2016-02-11 03:10
The variable is *assigned* but not *used*, a warning is expected because technically the variable is still doing nothing.

`var` should be colored though, I can reproduce it. It looks like it's a problem with the "Dark (Visual Studio)" and "Light (Visual Studio)" themes.

**Comment by aeschli** [comment] 2016-02-11 07:37
Moving to OmniSharp for commenting on the warning on the variable.
@Tyriar Let's have a separate issue for the 'var' coloring.

**Comment by aeschli** [comment] 2016-02-11 07:38
This issue was moved to OmniSharp/omnisharp-vscode#34

**Closed by aeschli** 2016-02-11 07:38 UTC
Labels: themes

**Comment by aeschli** [comment] 2016-02-11 07:40
I created #2919 for the coloring issue.
