### ISSUE TITLE
Make move lines multi cursor aware

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7179] opened 2016-06-03 09:12 UTC
At first, moving lines up and down didn't seem to work at all, but then I found a stranger issue. Notice how line 6 becomes a mix of lines 5 and 7:

![bug](https://cloud.githubusercontent.com/assets/22350/15774263/c4dca018-297b-11e6-807a-319997effbfe.gif)

Here's the buffer, notice the first line is empty, so you can move the lines up.

```

        if (this.mergeDecorator) {
            this.mergeDecorator.dispose();
            this.mergeDecorator = null;
        }

        if (!this.contextService || !this.gitService) {
            return;
        }
```

Steps:
- Put cursor right before the first `if`
- Duplicate cursor down 5 times
- Move lines up

**Comment by alexandrudima** [comment] 2017-03-02 10:51
The move lines are not multi-cursor aware. Each cursor tries to move its line up and edit collision hell ensues.

**Comment by mjbvz** [comment] 2017-11-09 00:34
Duplicate of #11809

**Closed by mjbvz** 2017-11-09 00:34 UTC
Labels: editor-contrib, feature-request
