### ISSUE TITLE
Multilayers nested snippets Tapstops bug

### ISSUE THREAD

**Issue by clPointer** [microsoft/vscode#117338] opened 2021-02-23 09:39 UTC
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Use this snippet: 
`"test":{
        "prefix": "j",
		"body": [
        "$ $1 $ $0"
		],
    },`
2. Use it for 18 times or more:
    I record it in a gif, copy it in the address bar( in github you can't see this gif)
     http://anki20201112.xuexihaike.com/mpic/20210223/HNkzczkExe1d.gif

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by clPointer** [comment] 2021-02-24 10:49
It is the same bug in #111284
I'm disappointed because this bug won't be fixed. 
I use vscode for taking notes in markdown. If one needs to write math formula, it's certain that he will find this bug.
I expected I can do the same thing as this guy Gilles Castel. He takes math notes using vim and latex. 
Actually his experience is easy to reproduce in vscode. He use ultisnips to fasten his input, and we have hypersnips which can almost do the same thing. However, this bug appears. 
Now I use another way to takes math notes, by using extensions jump-to-rightbacket and hypersnips. It works anyway but the experience sucks.
Vscode is a nice editor, but it has a long long way to be the best.

**Comment by jrieken** [comment] 2021-02-24 13:17
The actual duplicate is https://github.com/microsoft/vscode/issues/87226. As already said "help-wanted", I am happy to review a PR for this

**Comment by jrieken** [comment] 2021-02-24 13:17
/duplicate of https://github.com/microsoft/vscode/issues/87226

**Closed** 2021-02-24 13:18 UTC
Labels: *duplicate
