### ISSUE TITLE
Autocomplete / suggestions of files and folders in workspace

### ISSUE THREAD

**Issue by sujan-s** [Microsoft/vscode#43405] opened 2018-02-11 01:53 UTC
It'd be great to have autocomplete for filenames I'm including in my HTML page.

For example, for, lets say adding an icon, if I type `src="as`, it should suggest my `assets` folder, I hit tab or return, and again when I type `src="assets/icon-` it should bring up all the files whose names start with the `icon-` prefix.

**Comment by octref** [comment] 2018-02-13 05:34
Duplicate of #2037

**Closed by octref** 2018-02-13 05:34 UTC
