### ISSUE TITLE
Clearing Integrated Terminal not behaving as expected

### ISSUE THREAD

**Issue by thnk2wn** [Microsoft/vscode#49538] opened 2018-05-09 14:09 UTC
Issue Type: <b>Bug</b>

With prior bash output in the Integrated Terminal, run "clear" or hit Ctrl+K. 

#### Expected Behavior
Output is cleared, scrolling doesn't show past output

#### Actual Behavior
Past output is still shown after clear. This creates confusing behavior when rerunning scripts since you see the past output and then the new output together.

[2018-05-09_06-59-25.mp4.zip](https://github.com/Microsoft/vscode/files/1988101/2018-05-09_06-59-25.mp4.zip)

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 5|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.10.1
vscode-npm-script|eg2|0.3.4
csharp|ms-|1.14.0
PowerShell|ms-|1.7.0
vetur|oct|0.11.7

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment] 2018-05-10 06:25
For the `clear` part: duplicate of sourcelair/xterm.js#106

For the <kbd>Ctrl</kbd> + <kbd>K</kbd>: duplicate of #49162, it will be reverted in 1.23.1

**Closed** 2018-05-10 15:44 UTC
Labels: *duplicate, integrated-terminal
