### ISSUE TITLE
markdown preview 无 scroll bar

### ISSUE THREAD

**Issue by 4781121** [Microsoft/vscode#17808] opened 2016-12-25 06:46 UTC
- VSCode Version: 1.8.1
- OS Version: win10

Steps to Reproduce:
1. settings.json 设置 "window.zoomLevel": -1 // 非0
2. preview 无 scroll bar

**Comment by mjbvz** [comment] 2016-12-29 00:27
I believe this is a duplicate of #5745

**Closed by mjbvz** 2016-12-29 00:27 UTC
Labels: duplicate, markdown
