### ISSUE TITLE
Gnome 3.28 : VSCode opens a new window instead of minimizing/maximizing

### ISSUE THREAD

**Issue by jamesst20** [Microsoft/vscode#51023] opened 2018-06-03 00:26 UTC
Hi,

The VSCode icon in my Ubuntu App Menu / Dock is not behaving correctly. 
Please note that this is a clean Ubuntu 18.04 LTS (Gnome 3.28.1) install from today.

I would be expecting VSCode to minimize or maximaze when I click the icon when there is an opened window. 

Multiple click on the dock opens multiple instance instead of minimizing/maximizing :

![ezgif-1-29a2c84504](https://user-images.githubusercontent.com/490234/40881952-87455a04-66a2-11e8-8346-ce9fe7041a80.gif)

If I set the focus on another window and click VSCode in the dock, instead of focusing the already opened window, it opens a new one :

![ezgif-1-eb287c181a](https://user-images.githubusercontent.com/490234/40881989-26466602-66a3-11e8-80f2-82c71e3dbd15.gif)

Thank you

**Comment by jamesst20** [comment] 2018-09-13 19:33
The issue still happens

**Comment by nealot** [comment] 2019-02-08 21:35
This is a duplicate of https://github.com/Microsoft/vscode/issues/65460.

**Closed** 2019-03-31 05:41 UTC
Labels: bug, help wanted, linux
