### ISSUE TITLE
Column breakpoints under Linux only rarely accepted

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#21142] opened 2017-02-22 14:45 UTC
Testing #20192

My test JavaScript program is
```java
console.log(x); console.log(x + 1); console.log(foo()); console.log(foo() + foo());
x1 = 9; x1= 10;
```

and I try to set column breakpointbetween statements, on the statement, on expressions.
![image](https://cloud.githubusercontent.com/assets/6461412/23216293/c4135a54-f915-11e6-859b-2030a02726c6.png)
but when running they are mostly rejected:
![image](https://cloud.githubusercontent.com/assets/6461412/23216329/dad7448a-f915-11e6-84cb-0566106bd6a1.png)

**Comment by weinand** [comment] 2017-04-06 09:43
duplicate of https://github.com/Microsoft/vscode/issues/23659

**Closed by weinand** 2017-04-06 09:43 UTC
Labels: debug
