### ISSUE TITLE
"Directly committed to branch" popover can't be discarded for good

### ISSUE THREAD

**Issue by InDieTasten** [microsoft/vscode#146262] opened 2022-03-29 16:49 UTC
The popover warning about directly committing to some branch includes a link/button to "Don't show again".
Hovering over that link/button doesn't display a pointer cursor, and the expected functionality also doesn't happen:

Clicking on it discards the message, but also unfocuses the commit message input. Once the input is selected again, the popover appears.

The popover is actually pretty annoying, because I usually click into the input and want to think about what this commit is about. The popover then hides some of the staged files which would be helpful to see for coming up with a good commit message.

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55
Embedder: github.dev

**Comment by joyceerhl** [comment] 2022-03-31 16:18
This is https://github.com/microsoft/vscode-remote-repositories-github/issues/120. 'Don't Show Again' is a command link but doesn't do anything.

As a temporary workaround you can disable this popover in settings:
![image](https://user-images.githubusercontent.com/30305945/161102600-e366ff6f-01be-4524-9b1f-249583e8b70a.png)

**Comment by joyceerhl** [comment] 2022-11-07 15:43
Closing as duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/120

**Closed by joyceerhl** 2022-11-07 15:43 UTC
Labels: bug, git, web
