### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by debby12345** [microsoft/vscode#106342] opened 2020-09-09 11:47 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?**: Yes**/No

Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:94 [hb7] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ workbench.desktop.main.js:94
workbench.desktop.main.js:94     at new e (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6919:208)
    at d._createInstance (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1661:888)
    at d.createInstance (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1661:309)
    at ce.getSecondaryActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7039:34)
    at i.getSecondaryActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5842:641)
    at e.collectCompositeActions (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:861)
    at e.onTitleAreaUpdate (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:290)
    at e.<anonymous> (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5898:589)
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at i.updateTitleArea (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3040:438)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5842:94
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:92:235
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6562:789
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at S.onDidChangeContext (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5943:483)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5936:776
    at c.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:482
    at t.PauseableEmitter.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.PauseableEmitter.fire (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:539)
    at _.setContext (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1861:237)
    at m.set (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1859:658)
    at ce.doSearch (file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7041:111)
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7039:536
    at file:///C:/Users/Nosa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:128:302
check @ workbench.desktop.main.js:94
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:7003 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:7003
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:2989 Error: XHR failed
    at XMLHttpRequest.r.onerror (workbench.desktop.main.js:446)
onDidChangeNotification @ workbench.desktop.main.js:2989
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by sandy081** [comment] 2020-09-15 08:10
Seems proxy related.

**Comment by chrmarti** [comment] 2020-09-15 11:28
Could you start VS Code with --log-net-log=netlog.json, retry the failing feature and then post the created netlog.json here?

**Comment by chrmarti** [comment] 2020-09-16 05:24
Duplicate of https://github.com/microsoft/vscode/issues/106341.

**Closed by chrmarti** 2020-09-16 05:24 UTC
Labels: needs more info, proxy
