### ISSUE TITLE
Ctrl+C/Ctrl+V doesn't work in Explorer after Electron 8 update in Insiders builds

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#100797] opened 2020-06-22 22:31 UTC
Issue Type: <b>Bug</b>

This is basically #98425 but I haven't found any open tracking issues.

Steps to reproduce:

1. Select file in Explorer (e.g. `filename.ext`)
1. Press <kbd>Ctrl</kbd>+<kbd>C</kbd> and then <kbd>Ctrl</kbd>+<kbd>V</kbd>
1. Nothing happens

Expected result: `filename copy.ext` is created

/cc @bpasero @deepak1556 

VS Code version: Code - Insiders 1.47.0-insider (269f0fdd83f1e6611dd0c6d225a1685719eafedb, 2020-06-22T05:53:42.894Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment] 2020-06-23 03:44
Thanks @IllusionMH

**Comment by bpasero** [comment] 2020-06-23 06:00
I can reproduce with bare Electron and this looks like an Electron 8 bug @deepak1556 

https://github.com/electron/electron/issues/24253

**Comment by joaomoreno** [comment] 2020-07-16 10:54
This also reproduces using the mouse context menu: so the entire copy/paste flow is broken.

**Comment by dlong500** [comment] 2020-07-16 17:15
It looks like a fix for the electron bug was merged into all the relevant branches (8.x, 9.x, and 10.x) about 8 days ago.  Hopefully a new release will come soon.

**Comment by IllusionMH** [comment] 2020-07-16 17:17
But last Electron release was 9 days ago, so fix should be only in the next build.

**Comment by dlong500** [comment] 2020-07-16 17:18
> 
> 
> But last Electron release was 9 days ago, so fix should be only in the next build.

Yeah, I know.  I meant hopefully a new Electron release will be out soon.

**Comment by trickymast3r** [comment] 2020-07-19 06:43
still error vscode 1.48.0-insider can't copy paste with remote wsl

**Comment by JetLua** [comment] 2020-07-22 15:27
Looks like we'll have to wait for Electron to upgrade to 9.1.1

**Comment by deepak1556** [comment] 2020-08-28 20:54
Should be fixed in latest insiders, please check. Thanks!

**Closed by deepak1556** 2020-08-28 20:54 UTC
Labels: bug, electron-9-update, fixed-in-electron-9, regression

**Comment by IllusionMH** [comment] 2020-08-30 16:48
Thanks! Works as expected in:
Version: 1.49.0-insider (user setup)
Commit: 6384e3246884694cbc34eacc70281ada15e2c7f2
Date: 2020-08-28T16:02:44.602Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment] 2020-08-31 07:41
Thanks for letting us know, adding verified label.
