### ISSUE TITLE
"Install from vsix" seems to fail silently when no internet connection is available

### ISSUE THREAD

**Issue by donid** [Microsoft/vscode#39188] opened 2017-11-27 13:44 UTC
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---

---

Steps to Reproduce:

1. Use newly installed VSCode on a Windows machine with no internet connection
2. Choose "Install from vsix" in the "..." menu of the Extensions-View and select e.g. PeterJausovec.vscode-docker-0.0.22.vsix
3. Nothing (visible) happens, even if you wait several minutes
4. Connect the machine to the internet
5. Repeat step 2.
6. After approx. one minute a hint appears that the extension has been installed.

Reproduces without extensions: Yes

**Comment by adamrushuk** [comment] 2017-11-27 14:46
I'm also seeing this, but dont have the luxury of an internet connection for this offline network, so is there another workaround for this?

**Comment by adamrushuk** [comment] 2017-11-29 19:43
This bug makes this version unusable for air-gapped systems, so is there another way to install extensions other than loading .vsix files?

**Comment by sandy081** [comment] 2017-12-03 21:01
Duplicate of #37973

**Closed** 2017-12-03 21:02 UTC
Labels: *duplicate, extensions
