### ISSUE TITLE
When I open js file the server crash

### ISSUE THREAD

**Issue by BrayanAMSA** [microsoft/vscode#151346] opened 2022-06-06 15:58 UTC
Issue Type: <b>Bug</b>

When I try open a js file, it says Activating extensions, then lose the connection with the server and drop the server, in my case I use AWS, E2C. Finally I need to reset my instance. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-1025-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.07GB free)|
|Process Argv|--crash-reporter-id 6e36190e-7738-4b2d-8506-443abfc9f0e0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aws-amsaCotton|
|OS|Linux x64 5.13.0-1025-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 x 2400)|
|Memory (System)|0.95GB (0.07GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jquerysnippets|don|0.0.1
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by BrayanAMSA** [comment] 2022-06-06 16:03
I forgot say I'm Using remote-ssh by Microsoft, and it happens when connect my remote server AWS and try open js file

**Comment by yume-chan** [comment] 2022-06-06 16:45
Possibly duplicate of microsoft/vscode-remote-release#2692

Do you have enough (>4GB) of RAM on your AWS instance?

**Comment by mjbvz** [comment] 2022-06-06 19:55
You can configure the memory limits using `typescript.tsserver.maxTsServerMemory` but in general 1GB is not going to be enough

**Closed by mjbvz** 2022-06-06 19:55 UTC
