### ISSUE TITLE
Images in Webviews do not work as of 1.31

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#68177] opened 2019-02-07 22:49 UTC
We have an extension using webviews, and we load an SVG into the page. As of 1.31, this is broken, with an error `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`. The same code worked on 1.30 and before, so this likely has to do with the electron update. I am using `vscode-resource` properly. A script loaded from the same place does seem to work correctly, just not the image.

- VSCode Version: 1.31
- OS Version: Windows 10 Pro 1809

Steps to Reproduce (With our extension):

1. Install https://marketplace.visualstudio.com/items?itemName=wpilibsuite.vscode-wpilib
2. Run the `WPILib: Create a new project` command
3. Our icon should show at the top, but instead the failure to load icon shows up, and the developer tools shows the errors.

Steps to Reproduce (Without our extension):

1. Create an extension with a webview, and an SVG in the extension resource path.
2. Load that SVG in the webview
3. SVG does not load properly. 

Does this issue occur when all extensions are disabled?: N/A, its an extension function.

**Comment by mjbvz** [comment] 2019-02-07 23:37
Duplicate of #68033

**Closed by mjbvz** 2019-02-07 23:37 UTC
Labels: extensions
