### ISSUE TITLE
Wrong (zero) default indentation in lines inserted at the beginning of a function

### ISSUE THREAD

**Issue by php4fan** [microsoft/vscode#198783] opened 2023-11-21 15:58 UTC
Does this issue occur when all extensions are disabled?: Don't know, don't care

- VS Code Version: 1.84.2
- OS Version: Manjaro Linux

Imagine you want to write a function that you already know ends with a statement and you don't want to forget putting that statement at the end.

Steps to Reproduce:

1. In a new PHP file, type this:

```
<?php

function whatever() {
```
and hit Enter a few times, let's say 4 times. This will be autocompleted to:
```
<?php

function whatever() {



    //<--- the cursor is here, as expected
}
```

2. Now write a statement at the end of the function, e.g. like this:

```
<?php

function whatever() {



    return "Done!";//<-- the cursor is here, so far so good
}
```
3. Move the cursor up to go to the beginning of the function and start writing code. So in our case, move up 3 lines, i.e. hit the arrow-up key 3 times.

Expected behavior:

```
<?php

function whatever() {
    //<-- the cursor should be here, indented


    return "Done!";
}
```
The line should be indented as shown above, OR at least, as soon as I start typing, the indentation should be added.

Observed behavior:
```
<?php

function whatever() {
//<-- the cursor is here, with zero indentation


    return "Done!";
}
```
Even if I hit the End key, the cursor stays at the very beginning of the line with no indentation.
Even if I start typing, no indentation is added.

If I write a full line of code and hit enter, I get this code, wrongly indented:
```
<?php

function whatever() {
echo "something";


    return "Done!";
}
```

I've never seen any other code editor get this wrong.

**Comment by aiday-mar** [comment] 2024-03-28 16:14
HI @php4fan thank you for posting this issue. It is a duplicate of the issue here https://github.com/microsoft/vscode/issues/40115. This issue will be closed and you can track the state of this issue there.

**Closed by aiday-mar** 2024-03-28 16:14 UTC
Labels: php, editor-autoindent, under-discussion
