### ISSUE TITLE
Previously opened files in tabs do not render properly after starting vscode-insiders

### ISSUE THREAD

**Issue by christopherwolf1** [Microsoft/vscode#60592] opened 2018-10-11 05:45 UTC
Files that have been previously opened in Visual Studio Code Insiders will display according to whichever file last had the focus in the editor window(s), but the rendering will not update correctly; see attached animated GIF. In it, after starting vscode-insiders, I am switching between an HTML file and a JSON file. However, as can be seen, only the JSON file remains rendered because it was the first to resume focus after starting. 

![vscode-insiders-opening_bug](https://user-images.githubusercontent.com/15132959/46783172-2330b200-ccde-11e8-8b52-70f97a8c3faf.gif)

Closing all the tabs and re-opening the files one by one fixes the issue, much like the terminal prompt bug. I also went through several times with all extensions disabled; the bug behavior remained unchanged. 

Version: 1.29.0-insider (user setup)
Commit: f151c46b1783cf4f9a4ca934a85f78846f08688e
Date: 2018-10-11T05:19:51.895Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

CPUs | Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.89GB (5.35GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
npm-intellisense | chr | 1.3.0
vscode-eslint | dba | 1.6.0
vscode-docker-syntax | dun | 0.1.5
tslint | eg2 | 1.0.40
vscode-npm-script | eg2 | 0.3.5
beautify | Hoo | 1.4.4
python | ms- | 2018.9.0
vsliveshare | ms- | 0.3.788
vsliveshare-audio | ms- | 0.1.38
debugger-for-edge | msj | 1.0.6
vscode-docker | Pet | 0.3.1
remote-vscode | raf | 1.1.0
vscode-icons | rob | 7.27.0

**Comment by bpasero** [comment] 2018-10-12 07:14
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/60163

@christopherwolf1 can you reproduce this from a fresh session if you close all files and then open them again?

**Closed by bpasero** 2018-10-12 07:14 UTC

**Comment by christopherwolf1** [comment] 2018-10-13 06:16
@bpasero I just tried it again, with the new update, and can confirm that it does not occur anymore. 

Version: 1.29.0-insider (user setup)
Commit: 931c22033db3cc8d5dff265889307ed4076ac2d3
Date: 2018-10-12T05:17:15.739Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
