### ISSUE TITLE
Problems with git commands and vscode

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#7963] opened 2016-06-22 07:38 UTC
- VSCode Version: ANY
- OS Version: Windows 10 (should be any)

When I try to run commands such as `git checkout`, `git rebase`, or even `git stash pop` from the command line (powershell), many times it fails to complete the command, failing with this error, or an equivalent:
```
fatal: cannot create directory at 'src/app/...': Permission denied
``` 
The command also fails and thus leaving me to do a lot of manual cleaning up to restore to previous version.

It seems to me that vscode locks up the files and doesn't let Windows access them creating this problem.

Probable Steps to Reproduce: (I can't reproduce it completely reliably, but it's a start)

1. In a git repo, create a new folder and move an existing (tracked) file into that folder
2. Now stash your changes with a `git stash -u`
3. Now, apply your stash.
4. Fail

---

1. Make some changes to your code.
2. Pull from upstream.
3. Try a rebase
4. Fail (70% of the time)

**Comment by dbaeumer** [comment] 2016-06-22 07:54
@kumarharsh this might be caused by a bug we know exists in TS server which holds locks onto directories. However this should only affect renaming or deleting folders, not creating them. Can you reproduce the problem with normal text files?

**Comment by kumarharsh** [comment] 2016-06-23 14:21
Here are more errors:

```
warning: unable to access 'src/app/NEW_FOLDER/folder1/.gitattributes': Permission denied
Using index info to reconstruct a base tree...
warning: unable to access 'src/app/NEW_FOLDER/folder2/.gitattributes': Permission denied
warning: unable to access 'src/app/NEW_FOLDER/file1': Permission denied
Falling back to patching base and 3-way merge...
error: cannot stat 'src/app/NEW_FOLDER/file2': Permission denied
error: cannot stat 'src/app/NEW_FOLDER/file3': Permission denied
error: Failed to merge in the changes.
Patch failed at 0006 <<COMMIT_NAME>>
```

Basically, here is what I did:

1. Had a folder earlier in  `x/y/z`
2. Moved it to `a/b`
3. Committed this.
4. Did a `git pull --rebase`
5. Failed
6. Closed vscode
7. Ran `git pull --rebase` again
8. Success

**Comment by joaomoreno** [comment] 2016-06-24 10:08
This doesn't seem to be a problem with VS Code at all, but with git and your machine. If you run those commands from the command line, do you get the same behaviour? If you shutdown Code and run them, do you get the same behaviour?

**Comment by kumarharsh** [comment] 2016-06-28 09:43
@joaomoreno Yes, if I run it from the command line, I get the same issue - but only till vscode is open. As soon as I close vscode, it starts working 'as expected'

**Comment by joaomoreno** [comment] 2016-07-04 14:08
@bpasero could the file watching lock files or directories?

**Comment by bpasero** [comment] 2016-07-04 14:11
@joaomoreno no, not that I am aware of. I think only the node.js file watcher locks directories if you watch them, but we only watch files with it. Is this for files within a workspace or outside a workspace (we use different watchers in that case).

**Comment by kumarharsh** [comment] 2016-07-04 17:52
It is for files within a workspace. It also happens with both files and directories. within the workspace. It happens with directories when I've created a new directory in a commit, and am rebasing the branch containing that directory.

**Comment by joaomoreno** [comment] 2016-07-05 07:13
Do you see this on any other machine?

What git version do you have installed?

**Comment by joaomoreno** [comment] 2016-07-05 14:13
Closing as duplicate of #901

**Closed by joaomoreno** 2016-07-05 14:13 UTC
Labels: bug, git
