### ISSUE TITLE
Building in Centos 7 container fails at vscode-linux-x64-prepare-rpm due to dependencies list

### ISSUE THREAD

**Issue by xandris** [microsoft/vscode#149114] opened 2022-05-09 20:12 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: Centos 7

Steps to Reproduce:

1. `scl enable devtoolset-7`
2. `git clone https://github.com/microsoft/vscode.git --depth 1 --branch 1.67 && cd vscode`
3. `yarn && yarn gulp vscode-linux-x64-min`
4. `yarn gulp vscode-linux-x64-build-rpm`

```
[18:41:59] 'vscode-linux-x64-build-rpm' errored after 465 ms
[18:41:59] Error: The dependencies list has changed. Printing newer dependencies list that one can use to compare against referenceGeneratedDeps:
ca-certificates
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.2.5)(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
libX11.so.6()(64bit)
libXcomposite.so.1()(64bit)
libXdamage.so.1()(64bit)
libXext.so.6()(64bit)
libXfixes.so.3()(64bit)
libXrandr.so.2()(64bit)
libasound.so.2()(64bit)
libatk-1.0.so.0()(64bit)
libatk-bridge-2.0.so.0()(64bit)
libatspi.so.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.11)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.16)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.6)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libcairo.so.2()(64bit)
libcups.so.2()(64bit)
libcurl.so.4()(64bit)
libdbus-1.so.3()(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libdrm.so.2()(64bit)
libexpat.so.1()(64bit)
libgbm.so.1()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgdk_pixbuf-2.0.so.0()(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgmodule-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgtk-3.so.0()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libnspr4.so()(64bit)
libnss3.so()(64bit)
libnss3.so(NSS_3.22)(64bit)
libnssutil3.so()(64bit)
libpango-1.0.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libpthread.so.0(GLIBC_2.3.3)(64bit)
libpthread.so.0(GLIBC_2.3.4)(64bit)
libsecret-1.so.0()(64bit)
libsmime3.so()(64bit)
libssl3.so(NSS_3.28)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.19)(64bit)
libstdc++.so.6(GLIBCXX_3.4.5)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libutil.so.1()(64bit)
libutil.so.1(GLIBC_2.2.5)(64bit)
libxcb.so.1()(64bit)
libxkbcommon.so.0()(64bit)
libxkbfile.so.1()(64bit)
rpmlib(FileDigests) <= 4.6.0-1
xdg-utils
    at Object.getDependencies (/root/vscode/build/linux/rpm/dependencies-generator.js:57:19)
    at /root/vscode/build/gulpfile.vscode.linux.js:179:49
    at /root/vscode/build/lib/task.js:45:28
    at new Promise (<anonymous>)
    at _doExecute (/root/vscode/build/lib/task.js:34:12)
    at _execute (/root/vscode/build/lib/task.js:25:11)
    at result (/root/vscode/build/lib/task.js:64:19)
    at async _execute (/root/vscode/build/lib/task.js:25:5)
    at async result (/root/vscode/build/lib/task.js:64:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I place the above list into dep-lists.js, the build succeeds.

**Comment by xandris** [comment] 2022-05-09 20:13
This is the dep-lists.js I had to use:

https://gist.github.com/xandris/b80a50a3c72a36e58715eb2a60c0dfcf

**Comment by AA1HSHH** [comment] 2022-08-03 04:10
@xandris do you slove this problem to make an rpm package?

**Comment by xandris** [comment] 2022-08-03 07:38
> @xandris do you slove this problem to make an rpm package?

I'm using the official vscode rpms again.

**Comment by rzhao271** [comment] 2022-08-11 22:50
Duplicate of https://github.com/microsoft/vscode/issues/156784#issuecomment-1210379678.
The best action for now is to set the constant `FAIL_BUILD_FOR_NEW_DEPENDENCIES` to false.

**Closed** 2022-08-11 22:50 UTC
