### ISSUE TITLE
The "Git: Stage Selected Ranges" command stages changes twice for nested repos when the parent repo is also open

### ISSUE THREAD

**Issue by dslatkin** [microsoft/vscode#188967] opened 2023-07-26 19:09 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.1
- OS Version: Mac (Darwin arm64 22.3.0) and Linux (all versions I've tested in dev containers)

Nested repos look to be supported in VS Code from [#37947](https://github.com/microsoft/vscode/issues/37947) and [#159291](https://github.com/microsoft/vscode/pull/159291).

### Why this bug is impactful

When working in a dev container or Codespace, whenever you rebuild the container, everything gets wiped except the main repository that was opened in the container. If you use this repo to manage other repos, the only way to save your work in the other repos is to manage it in a subdirectory of the main repo opened in the container.

### Steps to recreate

1. Clone [dslatkin/vscode-issue-nested-repos](https://github.com/dslatkin/vscode-issue-nested-repos) (or create a repo locally with at least one commit)
2. Inside that repo, run the following commands to create a child repo:

```bash
mkdir child_repo
cd child_repo
git init
```

3. Create a file named `child_repo_file` inside the nested repo:

```bash
cat << EOF > child_repo_file
child_file_line_one
child_file_line_two
child_file_line_three
child_file_line_four
child_file_line_five
EOF
```

4. Add that file and commit (make sure you're committing to the child repo by using it as your working directory):

```bash
git add .
git commit -m "add child repo file"
```

5. Using VS Code, open that file and modify its contents to include a couple more lines:

```
child_file_line_one
child_file_line_two
FIRST_CHANGE
child_file_line_three
child_file_line_four
SECOND_CHANGE
child_file_line_five
```

6. Highlight between lines `child_file_line_two` and `child_file_line_five` to include the changes in the cursor's selection.
7. Using the VS Code command pallete (Ctrl/Cmd+Shift+P), run the `Git: Stage Selected Ranges` command.
8. **Notice the main issue captured in the screenshot below where the new lines have been staged twice.**
9. You can unstage the incorrect changes with no damage to the file.
10. If you right click the parent repo in the "Source Control Repositories" panel in the source control sidebar and [choose "Close Repository"](https://github.com/microsoft/vscode/assets/9263640/1c01b513-f059-4f67-a8be-91b3f28dab88), the issue no longer presents itself.

![image](https://github.com/microsoft/vscode/assets/9263640/cf07cd80-0e13-4fc4-b3f3-7cf8cdf82c09)

**Comment by brenocandido** [comment] 2023-08-11 18:41
I'm also encountering the same problem when using submodules. As a workaround, usually I'll manually stage changes using `git add -p`.

**Comment by lszomoru** [comment] 2023-09-01 07:16
@dslatkin, thank you very much for the detailed problem description. I followed the steps and I was able to reproduce the issue locally.  What I have noticed (also visible in your screenshot) is that after the command is executed, the file appears both in the "Staged Changes" and "Changes" groups. 

If you click on the file in the "Staged Changes" group you will see the lines added twice:
![Image](https://github.com/microsoft/vscode/assets/3372902/a039e5af-8e44-4342-913f-92c5474e9738)

If you click on the file in the "Changes" group you will see a deletion:
![Image](https://github.com/microsoft/vscode/assets/3372902/c02b9217-d29a-45f9-8c0c-d300118d1edd)

If you stage the file from the "Changes" group then (at least in this particular case) you will end up with the desired changes. Having said that, this does seem like a bug and I will investigate and will update the issue with my findings.

**Comment by lszomoru** [comment] 2023-09-01 12:57
@brenocandido, could you please provide the steps to reproduce this issue using submodules? Thanks!

**Comment by brenocandido** [comment] 2023-09-01 13:36
Sure thing!

1. Initialize a git repository with a submodule:
```
mkdir submodule
cd submodule
echo "Test" >> test_submodule.txt
git init .
git add .
git commit -m "First commit"
cd ..
mkdir top-module
cd top-module
echo "Top module" >> test_top_module.txt
git init .
git submodule add ../submodule submodule
git add .
git commit -m "First commit"
```

2. Open the top-module folder using using VSCode;
3. Add a new line to test_submodule.txt and save:
![image](https://github.com/microsoft/vscode/assets/28601412/2d25bf72-7a13-45b7-8791-2ca24502a6df)
4. Highlight the change in test_submodule.txt and enter `Git: Stage Selected Range`;
5. Duplicated text will be staged in `Staged Changes`:
![image](https://github.com/microsoft/vscode/assets/28601412/b06d0405-0a83-48d9-a1e9-5839bf671db7)
6. `Changes` will report deleted words that weren't there in the first place:
![image](https://github.com/microsoft/vscode/assets/28601412/0530c2bb-2f6d-4f93-a374-16461ca00764)

For reference, this was reproduced in VSCode version 1.81.1 running with `--disable-extensions`.

**Comment by brenocandido** [comment] 2023-09-01 13:48
@lszomoru If I follow the steps above, staging directly from the "Changes" group as you mentioned, it works as expected and there are no duplicate data.

**Comment by lszomoru** [comment] 2023-09-04 07:17
@brenocandido, thanks for the steps. I can confirm that the fix for this issue also resolves the problem that you outlined.

**Comment by lszomoru** [comment] 2023-09-08 11:31
The latest Insiders release (2023-09-08) contains a fix for this issue. @dslatkin, @brenocandido, could you please install the latest Insiders release and verify that this issue has been resolved. Thank you very much for your help!

**Comment by brenocandido** [comment] 2023-09-11 14:01
@lszomoru, this is weird, but when I initially tried to repro the issue it still displayed the same behaviour, but after I restarted code-insiders it wouldn't happen anymore.

Before restart:
![image](https://github.com/microsoft/vscode/assets/28601412/e304b842-7375-4a04-93b3-ffbda3d3cd7b)

After restart:
![image](https://github.com/microsoft/vscode/assets/28601412/030fcfbb-787b-4bca-bde8-65216ddb9180)

It seems that now it's working as expected.

Using a fresh install of what I assume is the latest version of code-insiders, launched with `code-insiders .`:
![image](https://github.com/microsoft/vscode/assets/28601412/4bbd357b-143a-4672-ad64-154026ff1be0)

**Comment by dslatkin** [comment] 2023-09-21 17:47
Thank you for fixing this! 😄 @lszomoru Do you still want me to test, or would you prefer I hold off for now since it's been reopened?

**Comment by lszomoru** [comment] 2023-10-26 09:15
@dslatkin, yes, please go through the test steps that you have provided and confirm that the issue has been resolved.

**Comment by lszomoru** [comment] 2023-10-26 09:41
@brenocandido, I went though the steps again in a clean folder and I am unable to reproduce the issue even the first time the folder is being opened. Could you please confirm that you are still able to reproduce this with the latest Insiders release? Thank you!

**Comment by brenocandido** [comment] 2023-10-26 11:58
@lszomoru It appears to be fixed in the latest Insiders release even on a newly created folder. Thank you!

**Closed** 2023-10-26 14:00 UTC
Labels: bug, git, confirmed

**Comment by dslatkin** [comment] 2023-10-31 19:30
Just tested and it's working now. Thank you @lszomoru! 😄
