### ISSUE TITLE
can't set a breakpoint on the line due to inline chat decoration

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#198373] opened 2023-11-15 23:19 UTC
I want a breakpoint on this exact line and cannot click the gutter to add one

![Screenshot 2023-11-15 at 3 18 38 PM](https://github.com/microsoft/vscode/assets/29464607/c0dd24ae-e4c9-46ae-81a7-24d04cc769ea)

**Comment by aiday-mar** [comment] 2023-11-16 08:41
Also in relation to the breakpoints and the sparkle in the editor gutter @aeschli

**Comment by aiday-mar** [comment] 2024-12-05 10:43
The icon in the gutter has been removed, so the issue is no longer relevant. Closing it.

**Closed by aiday-mar** 2024-12-05 10:43 UTC
Labels: bug, inline-chat
