### ISSUE TITLE
Unreadable text in Process Explorer

### ISSUE THREAD

**Issue by JakubDrozd** [microsoft/vscode#136694] opened 2021-11-08 20:23 UTC
Issue Type: <b>Bug</b>

Steps: It is easy to reproduce the bug. Just open the Help menu and click on the "Open Process Explorer" button. You will see some gibberish text on the top of the columns. You can see it on the screenshot. The columns aren't even resizable! That's quite bad. Could you fix the gibberish text and add resizable columns in the Process Explorer, please? I would really appreciate.

![Bug](https://user-images.githubusercontent.com/70533786/140812631-1d1d7728-33f3-4dd9-8616-e5d95ce96212.png)

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.48GB free)|
|Process Argv|--crash-reporter-id f667050e-cd55-4c9b-8828-622f51c58fbd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.2.2
copilot|Git|1.7.3689
vscode-pull-request-github|Git|0.32.0
better-cpp-syntax|jef|1.15.10
vscode-language-pack-pl|MS-|1.62.2
cpptools|ms-|1.7.1
markdown-preview-enhanced|shd|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by gjsjohnmurray** [comment] 2021-11-08 20:42
/duplicate of #136510 which you previously opened. Please be patient.

**Closed** 2021-11-08 20:43 UTC
Labels: *duplicate
