### ISSUE TITLE
Markdown Code Block Syntax highlighting: Highlighting doesn't work at certain indentations.

### ISSUE THREAD

**Issue by amithm7** [Microsoft/vscode#24824] opened 2017-04-15 15:15 UTC
- VSCode Version: 1.11.2

![capture](https://cloud.githubusercontent.com/assets/7036770/25064655/4bf847f2-221c-11e7-9908-9ad6ddeab50e.PNG)
![capture1](https://cloud.githubusercontent.com/assets/7036770/25064657/4d156ee4-221c-11e7-9d36-d9de12d5a17c.PNG)

**Comment by mjbvz** [comment] 2017-04-17 18:34
Duplicate of  #22185

**Closed by mjbvz** 2017-04-17 18:34 UTC
Labels: duplicate, languages basic, markdown
