### ISSUE TITLE
Run Script in External PowerShell console

### ISSUE THREAD

**Issue by mpearon** [Microsoft/vscode#19873] opened 2017-02-03 20:08 UTC
The ability to execute the active script in an external PowerShell console would be great.  Coming from PowerGUI, this was an awesome feature. It eliminated the ISE-ish differences, and let me see exactly what the end user would.

- VSCode Version: 1.90
- OS Version: Win 10

**Comment by Tyriar** [comment] 2017-02-06 20:00
Duplicate of https://github.com/Microsoft/vscode/issues/19375#issuecomment-277404381

The `workbench.action.terminal.runActiveFile` command is coming in v1.10

**Closed by Tyriar** 2017-02-06 20:00 UTC

**Comment by mpearon** [comment] 2017-02-08 01:33
@Tyriar I'm not quite sure this is an exact duplicate - but I might be misunderstanding.
The behavior I'm after is an action to launch an external PowerShell session and pass the script (auto-saved as temporary, if necessary), to that console.  This was a great feature of PowerGUI, as the integrated console of ISE was a bit flaky.

Correct me if I've misread the other thread.

**Comment by Tyriar** [comment] 2017-02-08 18:43
There may be an [extension for this](marketplace.visualstudio.com/vscode), otherwise you could create your own. This sort of thing is very specific and would therefore cause bloat in the product.

**Comment by mpearon** [comment] 2017-05-12 12:48
Just so it is recorded on this thread, this was accomplished by the vscode-PowerShell team:
[#705](https://github.com/PowerShell/vscode-powershell/issues/705)
