### ISSUE TITLE
Unable to open <link /> href using CTRL + Click functionality in VS Code

### ISSUE THREAD

**Issue by knowltonGitHub** [Microsoft/vscode#42897] opened 2018-02-03 19:15 UTC
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1.  In Visual Studio Code, open a file in the "Explorer".
2.  File opens fine.
3.  Find same file referenced as a LINK href  in a HTML file using CTRL + Click.
  <link rel="stylesheet" href="hover-min.css" />
4.  VS Code will report:

Unable to open 'hover-min.css': File not found (file:///hover-min.css).  "Create File" }  "Cancel"

Screen recording:
https://www.youtube.com/watch?v=9IGDvcDbyqw

Tried a few things, none of them worked:

1)  Closed VS Code.  Deleted the hidden vscode folder.  Re-opened VS Code.  Tried above steps.  Still able to reproduce problem.
2)  Tried removing "read only" attribute for the parent folder:

C:\xampp\htdocs\ukfnew\

Still able to reproduce problem afterwards.  I was not even sure this would work, it was a total WAG, but decided to try it.

TEMPORARY WORKAROUND:  Just open the needed file using VS Code Explorer.

I request steps to fix this if this is not a bug or able to be resolved simply.

**Comment by aeschli** [comment] 2018-02-05 11:56
duplicate of https://github.com/Microsoft/vscode/issues/38469
This is fixed in insiders. New stable is out soon.

**Closed by aeschli** 2018-02-05 11:56 UTC

**Comment by knowltonGitHub** [comment] 2018-02-05 20:44
What is insiders?

**Comment by aeschli** [comment] 2018-02-07 14:44
https://code.visualstudio.com/insiders/
