### ISSUE TITLE
Typescript language features keeps crashing

### ISSUE THREAD

**Issue by mostinho7** [microsoft/vscode#207559] opened 2024-03-13 09:28 UTC
Type: <b>Bug</b>

typescript language features keeps crashing and restarting while using vscode. I tend to lose intellisense features like viewing all references to a variable or going to source/definition for an interface for example. searching for referenecs manually is also too slow.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 7b20d8fc-b4fa-4ebe-9422-f9efac86a23a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
vscode-markdownlint|Dav|0.54.0
vscode-eslint|dba|2.4.4
gitlens|eam|14.9.0
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.72
vscode-graphql-syntax|Gra|1.3.4
open-file-from-path|jac|1.3.4
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.0
debugpy|ms-|2024.2.0
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.1
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
markdown-preview-enhanced|shd|0.8.12
teams-dyson|tea|0.0.2024011001
alphabetical-sorter|ue|2.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30958157
dsvsc020:30976470

```

</details>

**Comment by mjbvz** [comment] 2024-03-13 22:21
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jmoses** [comment] 2024-03-14 16:07
I'm seeing something something similar, as well, since yesterday's insiders build.  The tsserver kept crashing for me with a "code: null, signal: sigterm", but not errors in the log.  I get intellisense on "in file" defined objects, and the normal "native node" objects (array, etc), but nothing else in the project (my files or deps).

I can email a ts-server log to somebody, but nothing jumps out.  It did stop crashing for me yesterday (and isn't crashing for me today) but it's also not working.

It also constantly says "(loading)" the the type popups

![screenshot 2024-03-14 at 12 06 09@2x](https://github.com/microsoft/vscode/assets/6078/5a39cc38-f658-4f26-a315-044cc78839c7)

but no errors in the file properties

![screenshot 2024-03-14 at 12 06 41@2x](https://github.com/microsoft/vscode/assets/6078/23e87eff-b3a2-454f-a516-b0cc15e8163a)

**Comment by zoontek** [comment] 2024-03-14 17:46
Same behaviour here (for me and my colleagues).
We are using GQL codegen, which output a quite large types file, but it was not an issue before.

**Comment by jmoses** [comment] 2024-04-01 15:48
I just created an empty `jsconfig.json` file, and got a notification from vs-code that it was "Enabling JS/TS features", and now my intellisense works as expected.

**Comment by invative** [comment] 2024-04-09 01:02
I can confirm that @jmoses is correct. Creating an empty `jsconfig.json` also seems to have fixed this problem for me. This was never a requirement before. Something must have changed in the recent release.

**Comment by mjbvz** [comment] 2024-06-26 23:26
Closing as we need information from the original poster. I suspect that this was caused either by an extension or by yarn

If you're still seeing a similar crash, please open a new issue so we can investigate

**Closed by mjbvz** 2024-06-26 23:26 UTC
Labels: info-needed
