### ISSUE TITLE
Auto Indent with props in JSX not working 

### ISSUE THREAD

**Issue by bexoss** [Microsoft/vscode#60860] opened 2018-10-14 00:37 UTC
- VSCode Version: 1.25.1
- OS Version: OS X High Sierra

Steps to Reproduce:

![oct-14-2018 09-50-07](https://user-images.githubusercontent.com/12633102/46911437-a9771d80-cf96-11e8-939f-22c4355105f4.gif)

Auto Indent works well without prop component, but it has some props, it won't work. 

I think this is a critical bug. Did I do something wrong?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2019-04-09 21:28
Duplicate of #65955

Should be fixed in current insiders build

**Closed by mjbvz** 2019-04-09 21:28 UTC
Labels: bug, editor-autoindent, javascript
