### ISSUE TITLE
Tasks: possible to run multiple of the same task -> broken terminal dropdown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35048] opened 2017-09-26 09:58 UTC
Refs: #34953

1. Follow the test plan, run the watch task in a multi folder workspace
2. Delete that entry from tasks.json, run that task again
3. Notice you have two of the same tasks running now (which you are prohibitin in other places)
4. Now terminate one of those tasks, with the task: terminate action (terminate the second one if the first one is shown in the terminal)
5. Notice the terminal dropdown becomes blank and looks broken

There might be some other breakage with having two of the same tasks running, this is the one I noticed.

![screen shot 2017-09-26 at 11 57 29](https://user-images.githubusercontent.com/1926584/30854450-f0cd7cc8-a2b1-11e7-9eba-c15a777b0d88.png)

**Comment by dbaeumer** [comment] 2017-09-27 07:49
This is not related to multi workspace setups. The problem is that deleting the task from the tasks.json file make the contributed task the `primary` task and hence it will not match the already running task. Need to see how to better compare them.

**Comment by dbaeumer** [comment] 2017-09-27 07:50
Will investigate the broken terminal drop down for September since it is annoying.

**Comment by dbaeumer** [comment] 2017-09-27 14:21
Can't reproduce with a gulp watch task. Need to test npm

**Comment by dbaeumer** [comment] 2017-09-27 14:27
Ok. Was able to reproduce this with npm watch task as described in the test plan but I am not able to reproduce the empty drop down. Could this be the old drop down not initializing problem?

Here is what I see:

<img width="285" alt="capture" src="https://user-images.githubusercontent.com/1931590/30919074-ab00bd82-a3a0-11e7-811f-2cd5ad2db4a9.png">

@isidorn can you reproduce this if you opened the drop down before running any tasks ?

**Comment by isidorn** [comment] 2017-09-29 10:56
@dbaeumer now when following the exact steps from above I get a `Cannot read property 'toString' of undefined`
Here's where it explodes: 

![screen shot 2017-09-29 at 12 55 38](https://user-images.githubusercontent.com/1926584/31013255-87e18e96-a515-11e7-8e19-1fab49abe09b.png)

**Comment by dbaeumer** [comment] 2017-09-29 11:52
Already fixed by: https://github.com/Microsoft/vscode/commit/2e4b6ce1c2427ee64fb3f17e13186fe2b1764d50

**Comment by isidorn** [comment] 2017-09-29 12:40
I agree that the null exception is fixed, just verified, however I still get the broken terminal dropdown following the exact steps from my first comment.
Reopening.
IMHO this is not critical for September.

**Comment by dbaeumer** [comment] 2017-09-29 13:34
@isidorn good catch. I thought since you can't run twice the problem doesn't show up again. But two tasks can be named twice.

**Comment by dbaeumer** [comment] 2017-10-27 09:37
Got fixed by having a qualified name in the task drop down.

**Closed by dbaeumer** 2017-10-27 09:37 UTC
Labels: bug, tasks

**Comment by isidorn** [comment] 2017-11-02 15:44
Verified that the names are now qualified in the task drop down
