### ISSUE TITLE
Is there a 64-bit version of VSCode for Windows?

### ISSUE THREAD

**Issue by HoWingYip** [Microsoft/vscode#22383] opened 2017-03-10 11:34 UTC
- VSCode Version: 1.10.2
- OS Version: Windows 10 Version 1607

I was just wondering - is there a 64-bit version of Visual Studio Code for Windows? After all, Electron 64-bit is out...

**Comment by mrmlnc** [comment] 2017-03-10 11:37
Duplicate of https://github.com/Microsoft/vscode/issues/507

**Comment by ramya-rao-a** [comment] 2017-03-10 19:35
Thanks @mrmlnc 
Closing as duplicate

**Closed by ramya-rao-a** 2017-03-10 19:35 UTC
