### ISSUE TITLE
Bug with "Restore Undo Stack" option

### ISSUE THREAD

**Issue by dubrovkin** [microsoft/vscode#230995] opened 2024-10-10 05:53 UTC
Type: <b>Bug</b>

I always have the "Restore Undo Stack" option disabled. This worked fine. But since version 1.94 (version 1.94.1 does not fix this), when opening a file, I can use Ctrl + Z to undo previous actions.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment] 2024-10-10 06:27
/duplicate of https://github.com/microsoft/vscode/issues/230453 which is fixed in 1.94.2,expected to release today.

**Closed** 2024-10-10 06:27 UTC
Labels: *duplicate
