### ISSUE TITLE
Unable to see installed extentions in v1.3 from Extensions 

### ISSUE THREAD

**Issue by aptro** [Microsoft/vscode#8897] opened 2016-07-08 06:25 UTC
- VSCode Version: 1.3
- OS Version: ubuntu 16.4 LTS

Steps to Reproduce:

1. Click on the extentions icon. and the click more
2. Click the "show Installed extensions"

**Comment by ryanbowden** [comment] 2016-07-08 07:21
Same bug! 

Ubuntu 14.04 LTS

Can't see installed extensions and can't update them.

**Comment by svarogg** [comment] 2016-07-08 07:37
Same here.
On fresh installation of Ubuntu 16.04 xenial.

**Comment by KnisterPeter** [comment] 2016-07-08 07:49
Same on Debian Testing

**Comment by RobertoMalatesta** [comment] 2016-07-08 08:01
Same on Kubuntu 14.04 LTS

**Comment by ryanbowden** [comment] 2016-07-08 08:03
Is there anywhere i can download the 1.2.1 again?  Until 1.3 is fixed?

**Comment by Jackson-soft** [comment] 2016-07-08 08:20
Same bug!

Fedora 24

Can't see installed extensions and can't update them.

**Comment by haoliangwu** [comment] 2016-07-08 08:27
Same on ubuntu 14.04 LTS.

**Comment by joaomoreno** [comment] 2016-07-08 08:31
Here are the 1.2.1 as a temporary workaround:

- [32bit archive](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/VSCode-linux-ia32-stable.zip)
- [32bit deb](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-i386.deb)
- [32bit rpm](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-i386.rpm)
- [64bit archive](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/VSCode-linux-x64-stable.zip)
- [64bit deb](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-amd64.deb)
- [64bit rpm](https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-x86_64.rpm)

**Comment by joaomoreno** [comment] 2016-07-08 08:31
Closing as duplicate of #8877

**Closed by joaomoreno** 2016-07-08 08:31 UTC

**Comment by joaomoreno** [comment] 2016-07-08 08:50
Everyone, can you still reproduce with the downloadable archive?

[32bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-ia32-stable.zip)
[64bit](https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-x64-stable.zip)

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:04
Yes, since the 64 bit zip you link is byte-by-byte the same I downloaded this morning.

Do you have another zip build?

**Comment by joaomoreno** [comment] 2016-07-08 09:08
@RobertoMalatesta Do you have any extensions installed? If so, which? Can you zip up the `extensions` folder and send me?

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:14
wiped clea everything.
.vscode in ~ as well.

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:15
besides, the zip is the same that was giving problems at first.
do you have some *new* zip build?
--R

**Comment by joaomoreno** [comment] 2016-07-08 09:17
No. You mean you still have the issue **after** you wiped `~/.vscode`?

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:18
yep.
after a *clean* install after wiping everything

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:24
`
this is the version that you mentioned. I wgetted it as VSCode-linux-x64-stable.zip.1 

wget `https://az764295.vo.msecnd.net/stable/e724f269ded347b49fcf1657fc576399354e6703/VSCode-linux-x64-stable.zip` --> VSCode-linux-x64-stable.zip.1 


rw-rw-r--   1 robi robi 48264181 lug  8 09:46 VSCode-linux-x64-stable.zip   *** older one
-rw-rw-r--   1 robi robi 48264181 lug  7 19:02 VSCode-linux-x64-stable.zip.1  *** yours

diff VSCode-linux-x64-stable.zip VSCode-linux-x64-stable.zip.1 

`

They are the same.

Even on a newly wiped clean system I would expect the same outcome, do you agree  ?

-- R

**Comment by joaomoreno** [comment] 2016-07-08 09:26
@RobertoMalatesta I meant it as opposed to the `deb` and `rpm` packages.

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:30
On my side the issue appeared on the zip version.

**Comment by joaomoreno** [comment] 2016-07-08 09:33
@RobertoMalatesta Can you run from the terminal and run with `--verbose` and see if there are any errors? What about in the Developer Tools?

**Comment by RobertoMalatesta** [comment] 2016-07-08 09:49
Good news.
I run it with --verbose, installed an extension (c#) and it went seemingly ok.
I run it from desktop as usual and then extensions showed and seemed to be installable.

Running verbose fixed some silent bug.

**Comment by joaomoreno** [comment] 2016-07-08 09:51
Wow. And running again without `--verbose`?

**Comment by joaomoreno** [comment] 2016-07-08 10:22
@RobertoMalatesta Would you be willing to do a live Skype debugging call with me?

**Comment by svarogg** [comment] 2016-07-08 10:38
@joaomoreno - I can do it in case @RobertoMalatesta is unavailible.
I'll just need to install Skype and make sure everything works. So let me know if it's needed or not.

I am on a clean Ubuntu 16.04, installed Code 1.2 yesturday, and today morning upgraded to 1.3 using the deb file.
Plugins installed are fshap and amVim... I think that's it.

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:38
Sorry @joaomoreno I'm filled up with work.
@svarogg thank you.

--R

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:39
@svarogg be aware that in Unity you could have some issues with menus and themes

**Comment by svarogg** [comment] 2016-07-08 10:40
@RobertoMalatesta No worries, I'm not on unity, I'm on Awesome with GNOME, and Code looks awesome in it :)

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:41
@joaomoreno anyway after the --verbose run everything seems to be working OK.
(apart that VSC still has no Typescript Class Inspector and forces me to use Webstorm :smile: )

--R

**Comment by RobertoMalatesta** [comment] 2016-07-08 10:50
@joaomoreno one last thing:
**Damn how much I like this NEW MICROSOFT !**
:cake:

**Comment by svarogg** [comment] 2016-07-08 11:02
@joaomoreno Well, I'm waiting for you on Skype. Will be here for at around 2-3 more hours.

I can't see a way on github to send you a PM, and want to publicize my Skype account, so please give me yours, or create another channel through which we can connect.

**Comment by RobertoMalatesta** [comment] 2016-07-08 11:17
One more thing: @joaomoreno @svarogg 
Be sure that node.js is **not** pulled from a standard DEB.
I've had soo many issues on everything with official packages that now I think that official deb repository should be **deprecated**.

**Comment by joaomoreno** [comment] 2016-07-08 11:52
@svarogg Awesome, let's do this! Can you join this? https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode

**Comment by joaomoreno** [comment] 2016-07-08 11:53
@RobertoMalatesta Thanks for all your findings! It's so odd that after a single `--verbose` run the problem was fixed for you.

**Comment by svarogg** [comment] 2016-07-08 11:59
@joaomoreno I have clicked the link, it's stuck on "Requesting to join the video call..."

**Comment by RobertoMalatesta** [comment] 2016-07-08 12:03
@joaomoreno either that or the wiping of the whole ./vscode dir or a combination of them.

**Comment by joaomoreno** [comment] 2016-07-08 13:19
To whoever still sees this issue:

- Shutdown Code
- Run `ps ax | grep code` in a terminal, do you see any Code process still running?

**Comment by ryanbowden** [comment] 2016-07-08 13:24
@joaomoreno 
Shut down Code got the following
` 4248 ?        Ssl    0:04 /usr/share/code/code
 4250 ?        S      0:00 /usr/share/code/code --type=zygote --no-sandbox
 4295 ?        Sl     0:11 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=SharedProcess
 4352 ?        Sl     0:00 /usr/share/code/code ./terminalProcess
 4494 ?        Sl     0:00 /usr/share/code/code ./terminalProcess
19893 pts/13   S+     0:00 grep --color=auto code
`

**Comment by joaomoreno** [comment] 2016-07-08 13:35
Excellent, can you kill those and see whether that fixes it for you?

**Comment by ryanbowden** [comment] 2016-07-08 13:39
@joaomoreno 

Restarted my machine and yes that fixed it. It must have been the situation after the upgrade it broke and got stuck so restart fixes it and why the others don't see errors after that. 

The classic turn it off and on again......

**Comment by joaomoreno** [comment] 2016-07-08 13:39
Good to know. It should not have happened any way... I'm currently looking into why it did.

**Comment by ryanbowden** [comment] 2016-07-08 13:41
Okay then, Thank you for you help.

**Comment by RobertoMalatesta** [comment] 2016-07-08 14:29
forgot to explicit I did a **pkill -9 code** and a **pkill -9 node** before the big wipeout to start it clean.
There are cases in which the remain hanging.

**Comment by aptro** [comment] 2016-07-11 08:36
@RobertoMalatesta  @joaomoreno  killing node and code and restarting os worked for me too.

**Comment by joaomoreno** [comment] 2016-07-11 08:39
https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408
