### ISSUE TITLE
Cannot see app icon on the Dock of Mac

### ISSUE THREAD

**Issue by sriharsha-sammeta** [microsoft/vscode#77429] opened 2019-07-15 21:26 UTC
<img width="2513" alt="image" src="https://user-images.githubusercontent.com/6239997/61250416-766fdf00-a70c-11e9-9e98-2c31cc804e83.png">

**Comment by misolori** [comment] 2019-07-15 21:43
Duplicate of https://github.com/microsoft/vscode/issues/63068, usually running `killall Dock` in the terminal will fix this.

**Closed by misolori** 2019-07-15 21:43 UTC

**Comment by sriharsha-sammeta** [comment] 2019-07-15 22:31
Yup, that worked. However, this is the first time I encountered such an issue with an app.

**Comment by misolori** [comment] 2019-07-15 22:38
It seems to be an odd Mojave issue, thanks for letting us know that worked.
