### ISSUE TITLE
A Extension Back-Up

### ISSUE THREAD

**Issue by Chawki726** [Microsoft/vscode#64704] opened 2018-12-10 01:38 UTC
Hello VSCode...
**All of us has the the situation of Uninstalling VScode due to moving to new PC/or resetting current PC**
I too had a situation to reset my PC and after i re-install VSCode i lose my all extension which i had install previous,due to that i wanna install previous extensions again
_Please Try to Update this feature..._
**Thank you.**

**Comment by usernamehw** [comment] 2018-12-10 10:34
```
code --list-extensions > extensions.list
```

**Comment by usernamehw** [comment] 2018-12-10 10:35
Install list of extensions #42994

**Comment by sandy081** [comment] 2018-12-10 10:58
Duplicate of #2743

**Closed by sandy081** 2018-12-10 10:58 UTC
Labels: extensions
