### ISSUE TITLE
The warning of "The Typescript language service died unexpectedly 5 times in the last 5 Minutes" keeps flashing on top of the window in the Visual Studio Code

### ISSUE THREAD

**Issue by laurayang321** [Microsoft/vscode#22936] opened 2017-03-21 05:35 UTC
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment] 2017-03-21 16:24
Dup of https://github.com/Microsoft/vscode/issues/21956 .

**Comment by mjbvz** [comment] 2017-03-21 19:57
Yes, this is likely a duplicate of #21956. Please upgrade to VSCode 1.10+ and also make sure your antivirus program is not deleting the tsserver.js file that we ship in VSCode

**Closed by mjbvz** 2017-03-21 19:57 UTC
Labels: duplicate, typescript
