### ISSUE TITLE
VSCode always found the same update after each of my update

### ISSUE THREAD

**Issue by budarin** [microsoft/vscode#187270] opened 2023-07-07 13:14 UTC
Type: <b>Bug</b>

After each update and reboot of the IDE, it finds the same update again and so it goes on endlessly

I deleted VS Code and installed it again - it didn't help

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3512)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.90GB (11.01GB free)|
|Process Argv|--crash-reporter-id db8247ca-9b13-487a-a022-6636eb0e2750|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-preview-github-styles|bie|2.0.2
dscodegpt|Dan|2.1.14
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.19.0
css-stacking-contexts|fel|1.0.15
vscode-jest-runner|fir|0.4.60
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.2
playwright|ms-|1.0.13
remote-containers|ms-|0.299.0
color-highlight|nau|2.5.0
gitpatch|par|0.2.1
vscode-react-refactor|pla|1.1.3
deoptexplorer-vscode|rbu|1.1.2
vscode-stylelint|sty|1.2.4
typograf|sve|3.0.1
non-breaking-space-highlighter|vik|0.0.3
vscodeintellicode|Vis|1.2.30
vscode-todo-highlight|way|1.0.5
pretty-ts-errors|yoa|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495

```

</details>

**Comment by kayhayen** [comment] 2023-07-07 13:19
I am seeing the sme thing, Windows 11 latest.

**Comment by kayhayen** [comment] 2023-07-07 13:22
Duplicate of #187229

**Comment by joaomoreno** [comment] 2023-07-07 15:29
https://github.com/microsoft/vscode/issues/187229#issuecomment-1625579951

**Closed by joaomoreno** 2023-07-07 15:29 UTC
Labels: new release
