### ISSUE TITLE
Virtual Document for Custom Document Editor as Binary Viewer

### ISSUE THREAD

**Issue by daiyousei-qz** [microsoft/vscode#149784] opened 2022-05-18 00:53 UTC
Custom Document Editor is a great feature! But its presentation limited to the WebView. Would it possible that instead of a WebView we could use a read-only virtual document to present the custom document? I think this could be very useful to make any binary viewer extension.

**Comment by mjbvz** [comment] 2022-05-18 16:45
Duplicate of #106916

**Closed by mjbvz** 2022-05-18 16:45 UTC
Labels: custom-editors
