### ISSUE TITLE
Path - new task input variable type

### ISSUE THREAD

**Issue by maciejmatczak** [microsoft/vscode#122921] opened 2021-05-04 12:47 UTC
I would like to propose adding a new type of an input for tasks, a path input.

The proposed input could be either a directory of file, existing or not (all configurable if possible) with autocompletion for nested directories.

**Comment by alexr00** [comment] 2021-05-04 13:54
Duplicate of https://github.com/microsoft/vscode/issues/71461

**Closed by alexr00** 2021-05-04 13:54 UTC
