### ISSUE TITLE
Code helper spawning "find processes" and making the OS unresponsive

### ISSUE THREAD

**Issue by MihkelBaranov** [Microsoft/vscode#32829] opened 2017-08-19 15:53 UTC
- VSCode Version: 1.15.1 (1.15.1)
- OS Version: Sierra 10.12.3

Steps to Reproduce:

Im working with NativeScript and while trying to run the project vscode starts to spawn "find" processes 

![image](https://user-images.githubusercontent.com/3790782/29488178-35622792-850e-11e7-996f-d254fd81b85b.png)

![image](https://user-images.githubusercontent.com/3790782/29488169-18fa4d5a-850e-11e7-84ee-284fd8b2540f.png)

1. Launch vscode through terminal
2. Run `tns run ios`

Reproduces without extensions: Yes

**Comment by chrmarti** [comment] 2017-08-31 14:57
@roblourens This seems to be fixed in the latest. I see it in 1.15.1, but couldn't pinpoint the change that fixed it. Closing for verification.

**Comment by roblourens** [comment] 2017-09-01 18:38
Under what conditions do you see this in 1.15.1? I don't see it.

**Comment by chrmarti** [comment] 2017-09-01 20:13
I see a similar set of `find` processes with insiders:
- Install (or uninstall + reinstall) the C# extension
- Open on a large folder (I use the one containing all my repositories)
-> `find` process show up

The difference in 1.15.1 is that they at some point go to 0% CPU and then just idle. In insiders they exit.

**Comment by roblourens** [comment] 2017-09-01 20:21
It looks possible that the C# extension could call `findFiles` a lot, do you think that's what's happening? https://github.com/OmniSharp/omnisharp-vscode/blob/6013d9214d58d5ee34a539a62ab7074d56fad547/src/omnisharp/launcher.ts#L47

**Comment by roblourens** [comment] 2017-09-01 20:29
I still see this in Insiders:

```
robmac:Documents roblou$ ps aux | grep find
roblou           61094   0.0  0.0  2497332   7488   ??  S     1:27PM   0:10.45 find -L . -type f
roblou           61092   0.0  0.0  2497332   7488   ??  S     1:27PM   0:10.42 find -L . -type f
roblou           61091   0.0  0.0  2498356   7628   ??  S     1:27PM   0:10.35 find -L . -type f
root             14882   0.0  0.0  2542032   3792   ??  Ss   Thu11AM   0:00.26 /usr/libexec/findmydeviced
roblou           63178   0.0  0.0  2451236    828 s002  S+    1:28PM   0:00.00 grep find
roblou           61098   0.0  0.0  2498356   7504   ??  S     1:27PM   0:10.53 find -L . -type f
roblou           61097   0.0  0.0  2497332   7484   ??  S     1:27PM   0:10.33 find -L . -type f
roblou           61096   0.0  0.0  2497332   7484   ??  S     1:27PM   0:10.38 find -L . -type f
roblou           61095   0.0  0.0  2498356   7708   ??  S     1:27PM   0:10.39 find -L . -type f
```

We should use ripgrep :)

**Comment by roblourens** [comment] 2017-09-01 20:38
Actually when I normally start the same process on the same folder in a terminal, it finishes in about 30s.

**Comment by roblourens** [comment] 2017-09-01 20:40
🔥 

```
robmac:code roblou$ time rg --files --follow > rgfiles.txt

real	0m3.137s
user	0m2.293s
sys	0m6.566s
robmac:code roblou$ time find -L . -type f > files.txt

real	0m20.901s
user	0m0.968s
sys	0m10.374s
```

**Comment by chrmarti** [comment] 2017-09-01 23:10
@roblourens How do you get the processes to stay around?

**Comment by roblourens** [comment] 2017-09-01 23:14
I don't do anything unusual

**Comment by chrmarti** [comment] 2017-09-25 20:49
Duplicate of #34434

**Closed by chrmarti** 2017-09-25 20:49 UTC
Labels: bug, search

**Comment by roblourens** [comment] 2017-09-25 21:01
I totally forgot about this one. How was I getting the processes to stick around at 0 CPU? I never saw that when investigating #34434.

**Comment by chrmarti** [comment] 2017-09-26 05:16
Have we seen that with `rg` as well or only with `find`?

**Comment by roblourens** [comment] 2017-09-26 16:34
Jo reported it in #34434 but I've never seen it.
