### ISSUE TITLE
CSS formatting is behaving weirdly...Deleting curly braces, making enormous whitespaces...

### ISSUE THREAD

**Issue by Valentyn-Lyaskovskiy** [microsoft/vscode#174937] opened 2023-02-21 14:59 UTC
Type: <b>Bug</b>
```
@media (max-width: 1080px) {
  .main__wrapper {
    flex-wrap: wrap;
  
  .main__left,
  .main__right {
    margin: 0 auto;
  }

  .main__right {
    max-width: 80%;
  }

  .main__subtitle:not(:last-child) {
    margin: 0 0 20px;
  }

  .main__text_second:not(:last-child) {
    margin: 0 0 40px;
  }

  .main__title:not(:last-child) {
    margin: 0;
  }

  .main__link {
    margin-bottom: 50px;
  }

  .main__text {
    max-width: 100%;
  }
}

@media (max-width: 970px) {
  .header__menu {
    margin-right: 0;
  }
}

@media (max-width: 830px) {
  .mr__list {
    flex-wrap: wrap;
    row-gap: 22px;
    font-size: 16px;
    margin-top: 25px;
  }
}

@media (max-width: 768px) {
  .header__wrapper {
    display: block;
    text-align: center;
  }

                                .menu__list {
                                  margin-top: 50px;
                                  justify-content: center;
                                }

                                .menu__link {
                                  font-size: 18px;
                                  padding: 20px 0;
                                }

                                .main__title {
                                  font-size: 40px;
                                }

                                .main__title:not(:last-child) {
                                  margin: 0 0 12px;
                                }

                                .main__link {
                                  padding: 20px 40px;
                                  width: 100%;
                                }
}

@media (max-width: 560px) {
  .menu__list {
  flex-direction: column;
  }

    .menu__link {
  padding: 42px 10px;
  

    .main__left {
      text-align: center;
    }
}
```
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.15.0-60-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 3204)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.51GB (11.56GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6397ae5e-edbd-4d2c-a047-910bc3718943|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-end-tag-labels|ant|0.10.0
All-Autocomplete|Ati|0.0.26
htmltagwrap|bra|0.0.7
ecsstractor-port|diz|0.0.3
css-flexbox-cheatsheet|dzh|3.3.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.12.0
live-sass|gle|6.0.2
google-translate|han|1.2.7
vscode-gutter-preview|kis|0.30.0
google-fonts|lio|0.0.1
compare-folders|mos|0.22.3
css-responsive|mre|1.1.2
color-highlight|nau|2.5.0
vscode-css-navigation|puc|1.13.3
LiveServer|rit|5.7.9
js-snippets|run|0.2.6
px-to-rem|sai|1.3.1
html-to-css-autocompletion|sol|1.1.2
sass-indented|syl|1.8.24
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30662992
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by IllusionMH** [comment] 2023-02-22 00:53
You forgot to wrap code in ` ``` ` so it's not formatted correctly and makes it harder to use your example. Also it's better to provide list and places of problems - just code doesn't make it obvious in all cases

**Comment by aeschli** [comment] 2023-02-22 15:51
Pasting your code in an editor in CSS mode shows that there are syntax errors due to missing closing brackets on line 4 and 85
Adding these brackets and running the formatter gives a nice result.

Closing the issue. Please speak up if you still have problems.

**Closed by aeschli** 2023-02-22 15:51 UTC

**Comment by Valentyn-Lyaskovskiy** [comment] 2023-02-22 17:33
They are missing due to weird behavior: when I change focus they are
deleted...
Linux mint 21...

Ср, 22 лют. 2023 16:51 користувач Martin Aeschlimann <
***@***.***> пише:

**Comment by Valentyn-Lyaskovskiy** [comment] 2023-02-22 22:30
They are (brackets) missing due to weird behavior: when I change focus, after pasting copied code, they are deleted (on line 4 and 85)...
Linux mint 21...
I'll provide more meticulous details...coming soon...
Thank you
 [Andrii Dieiev](https://github.com/IllusionMH)
 &
 [Martin Aeschlimann](https://github.com/aeschli)
 for your time!
 I appreciate it.

**Comment by Valentyn-Lyaskovskiy** [comment] 2023-02-22 22:34
...running the formatter on Windows 10 gives a nice result,
but Linux Mint is causing the issue(((

**Comment by aeschli** [comment] 2023-02-23 10:47
Is this caused by 'format on save'?

**Comment by Valentyn-Lyaskovskiy** [comment] 2023-02-23 12:06
Seems it is.
Maybe some extensions have conflicts...
![Selection_008](https://user-images.githubusercontent.com/92991058/220901065-a72bb5b4-5460-42f2-b475-563cb375b328.png)

Not long ago everything was smooth.

**Comment by Valentyn-Lyaskovskiy** [comment] 2023-02-23 15:21
Solved...
A workaround...
https://www.loom.com/share/57604d60d2614c2e8f2d2ed552ccedee
