### ISSUE TITLE
Error to update VSCode on Linux DEB

### ISSUE THREAD

**Issue by hack-git-0** [microsoft/vscode#230749] opened 2024-10-07 23:26 UTC
Does this issue occur when all extensions are disabled?: No

 
- VS Code Version: code_1.94.0-1727878498_amd64.deb
- OS Version: Debian 11 (5.10.223-1)

Steps to Reproduce:

  1. The system says that have an update disponible;
  2. It's make the update command "$ sudo apt update && sudo apt list --upgradable " and the command output show "code/ stable 1.94.0-1727878498 amd64.deb [upgradable from : 1.93.1-1726079302]"
  3. When is make the upgrade process, using "$ sudo apt upgrade -y" is showed that will be updated but isn't upgraded, showing an error :  "dpkg-deb: error: the archive '/var/cache/apt/archives/code_1.94.0-1727878498_amd64.deb' uses unknow compression for member 'control.tar.zst',  aborting..."
4.  How can be seen, it's impossible update.

![upgrade-code](https://github.com/user-attachments/assets/1b6904dc-d931-4e00-b008-e9b7c7b07fdc)
![update-code](https://github.com/user-attachments/assets/33471a77-1451-4e73-8e62-ae6024742630)

**Comment by gjsjohnmurray** [comment] 2024-10-08 01:03
/duplicate of https://github.com/microsoft/vscode/issues/230418 which is milestoned for an upcoming recovery release.

**Closed** 2024-10-08 01:04 UTC
Labels: *duplicate
