### ISSUE TITLE
ctrl+f - 'Find' rendering problem

### ISSUE THREAD

**Issue by art40100** [microsoft/vscode#85272] opened 2019-11-21 07:45 UTC
![ohnoo2](https://user-images.githubusercontent.com/33236770/69317351-77c59100-0c43-11ea-9444-536f8bb3e85d.PNG)

![omgz](https://user-images.githubusercontent.com/33236770/69317321-68464800-0c43-11ea-83be-bfce6bdf88d0.PNG)

- VSCode Version:
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:
It is related to breadcrumbs, there seems to be some interference when the breadcrumbs are long.
![bread](https://user-images.githubusercontent.com/33236770/69319541-0a682f00-0c48-11ea-8357-c9c49f130c0d.PNG)
I also tested this with "breadcrumbs.enabled": false and then it renders correctly.

It must have been the most recent updates as I had not noticed it before.

**Comment by Garisons** [comment] 2019-11-21 08:35
Is that font ClearType problem?

**Comment by art40100** [comment] 2019-11-21 08:49
> Is that font ClearType problem?

Tested with ClearType disabled in W10 settings. Does not resolve the issue.

**Comment by rebornix** [comment] 2019-12-02 19:25
/duplicate of https://github.com/microsoft/vscode/issues/85589

**Closed** 2019-12-02 19:25 UTC
Labels: *duplicate
