### ISSUE TITLE
Editor viewport should scroll when multiple cursors are going off screen

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17814] opened 2016-12-25 13:55 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (04f541160e0d41be95df9a964b1b570aec549157, 2016-12-20T07:18:37.536Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.3.0|
|vscode-eslint|dbaeumer|1.2.2|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|typescript-javascript-grammar|ms-vscode|0.0.13|
|sass-indented|robinbentley|1.3.0|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Open a file with a lot of text
2. Add a cursor below the current line
3. Press down until the cursor(s) are off the screen

It would make a lot of sense for the viewport to follow the cursors in this case as both cursors were in the viewport previously.

**Comment by alexandrudima** [comment] 2017-11-24 15:27
Duplicate of #6995

**Closed by alexandrudima** 2017-11-24 15:27 UTC
Labels: editor-core, editor-multicursor, feature-request
