### ISSUE TITLE
Formatting document breakes indentation for multilined parameters in functions chain

### ISSUE THREAD

**Issue by alexey-kozlenkov** [Microsoft/vscode#33901] opened 2017-09-06 15:44 UTC
- VSCode Version: 1.15.1
- OS Version: macOs 10.12.6

When you have a function and trying to call it with parameters going one-per-line, the indentation is fine after document formatting:
![image](https://user-images.githubusercontent.com/8117458/30120930-e6b6bd1e-9332-11e7-8214-680c8d0e35ad.png)

But if you try to format document with a function chain and multilined parameters, they will lost the indentation relatively to parent level:
![image](https://user-images.githubusercontent.com/8117458/30121165-9e033218-9333-11e7-9cbb-d8eaeb61c231.png)

**Comment by alexey-kozlenkov** [comment] 2017-09-07 14:08
The same behaviour happens to me with multiline objects:

![image](https://user-images.githubusercontent.com/8117458/30167460-29752b2e-93ef-11e7-9042-2395fb434c25.png)
![image](https://user-images.githubusercontent.com/8117458/30167473-31a92516-93ef-11e7-90ac-bd4535e442fe.png)

**Comment by rebornix** [comment] 2017-09-09 02:27
@alexey-kozlenkov what formatter you are using? It looks like a formatter issue to me.

**Comment by alexey-kozlenkov** [comment] 2017-09-09 13:26
@rebornix a default VSCode "format document" command.

**Comment by alexey-kozlenkov** [comment] 2017-09-19 19:18
Any updates on this?
@rebornix maybe you need any more details?

**Comment by pbwuxus** [comment] 2017-10-09 07:27
this is a big problem for me too
+1
![image](https://user-images.githubusercontent.com/15231723/31328185-f2c803e6-acd3-11e7-9ec3-017986dffc51.png)

**Comment by rebornix** [comment] 2017-12-01 18:13
@mjbvz it looks like a TS formatter issue.

**Comment by alan-agius4** [comment] 2018-01-03 17:39
Any update re this? I recently updated to use rxjs 5.5.x and I am encountering this issue as it uses function chaining

**Comment by mjbvz** [comment] 2018-04-17 23:05
The original issues @alexey-kozlenkov reported is https://github.com/Microsoft/TypeScript/issues/5830. It seems fixed in my testing even though the issue is still open. There may be other edge  cases

The multiline object literal case also seemed fixed. Values now have an extra indent

```ts
const z = {
    ['aaafdsafdsafadsfdasfadsfdsa']:
        'aaafdsafdsafadsfdasfadsfdsa'
}
```

The one @pbwuxus mentioned is https://github.com/Microsoft/TypeScript/issues/16043. It has not been fixed yet

Closing as upstream

**Closed by mjbvz** 2018-04-17 23:05 UTC
Labels: under-discussion
