### ISSUE TITLE
Cannot run vscode as sudo user with --no-sandbox

### ISSUE THREAD

**Issue by aoweis** [microsoft/vscode#151187] opened 2022-06-03 02:58 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

NOTE: I know this was mentioned in previous issues (e.g. #146847 and #146836), but the previous reports were closed as "will not fix". I just want to present my use case because I didn't see it mentioned in the previous bug reports.

1. Start VS Code from terminal using: sudo code --user-data-dir="~/vscode-root" --no-sandbox
2. I got a white window.

My use case: I'm working on srsRAN (https://github.com/srsran/srsRAN), and its eNB program requires sudo so that it can start high priority threads. In order to debug the code, I have to start VS Code with sudo, other wise I cannot debug it. If someone can show me another way to debug the code without starting VS Code with sudo, please do.

I was able to start VS Code with sudo till very recently when this issue occurred in a new release. It seems my only option is to roll back to a previous version. 

![image](https://user-images.githubusercontent.com/24617048/171775770-2aa73cc2-e82f-472e-95da-42db9c341b98.png)

**Comment by qq906907952** [comment] 2022-08-21 06:03
I think it is not a bug. if you have gpu and use vscode 1.66+ and run in root should add '--disable-gpu-sandbox' arg, for example: 

```bash
code --no-sandbox --disable-gpu-sandbox --user-data-dir=/root/.vscode/
```

**Comment by cwhgraham** [comment] 2022-08-23 07:50
I'm from issue#148680.
I could see the content after adding '--disable-gpu-sandbox'.

Thanks,
Graham

**Comment by yglsaltfish** [comment] 2022-11-15 03:20
This worked for me too!
`sudo code --no-sandbox --disable-gpu-sandbox --user-data-dir=/root/.vscode/`
* VS Code Version:  1.73.1
* OS Version: Ubuntu 20.04.2 LTS

**Comment by deepak1556** [comment] 2023-06-14 11:47
@Mr-7r0j4n the issue is addressed in https://github.com/microsoft/vscode/issues/184687

**Comment by deepak1556** [comment] 2023-06-22 10:21
This should now be addressed with https://github.com/microsoft/vscode/issues/184687

**Closed by deepak1556** 2023-06-22 10:21 UTC
Labels: bug, upstream, linux, confirmed, chromium, sandbox, mitigated
