### ISSUE TITLE
Links in markdown are broken if url contains encoded parameters

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#79474] opened 2019-08-19 22:19 UTC
Issue Type: <b>Bug</b>

In the latest VSCode release (1.37.0) there seems to be a regression in markdown rendering feature, in that some of the URL parameters are incorrectly getting encoded .  

Repro steps

1. Create a markdown file and put following url  content in it and save the file:
```
<!-- Begin markdown -->
[Sample Link](https://myhost.com/Redirect?url=http%3A%2F%2Fwww.bing.com%3Fsearch%3Dtom)
<!-- End markdown -->
```

2. Click this link in markdown, see that the URL that is passed to browser is:

https://myhost.com/Redirect?url=http://www.bing.com%253Fsearch=tom 

Notice that the %3F in the _url_ parameter in the markdown link has been further encoded into %253F

Expected: 
The URL that is passed to browser is either for the two below
1. https://myhost.com/Redirect?url=http%3A%2F%2Fwww.bing.com%3Fsearch%3Dtom
2. https://myhost.com/Redirect?url=http://www.bing.com?search=tom

This issue is true for other surfaces of markdown as well, like the 'Details' tab of installed extensions and the hover popup set through text decorations, via the vscode.DecorationOptions class.

This issue does not repro in older version of VSCode (1.36.0 and prior).

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18963

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
devinsights|Mic|2019.1.25-6
vscode-nmake-tools|Mic|2.0.190801001
cpptools|ms-|0.24.1
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7

</details>

**Comment by rbrishabh** [comment] 2019-08-20 08:05
Hey! I would like to take this up! Could you please help me get started by pointing me to the directory (or file) where I should be making the changes? 

Thanks!

**Comment by hypercubestart** [comment] 2019-08-21 15:27
@mjbvz pull request #79552  only fixes the hover popup, however I am not sure if preserving the query string is the best way to fix this issue

**Comment by jrieken** [comment] 2019-08-22 10:09
Sorry, this isn't a good first issue because it's a bit of a bottom-less whole. 

@mjbvz The underlying issue is that `Uri.parse` decodes its input and then re-encodes when calling `toString`. That (re)encoding is needed because `toString` is mostly used to create comparable strings for storing things in maps, `toString` isn't primarily designed to create externalised uri-strings for exchange. 

Let's come up with a fix together. An idea that worth exploring is to use `uri.with`, e.g start with "some" uri and then transform it into the uri you want. However, that requires that you are able to break the uri into its components...

**Comment by jrieken** [comment] 2019-10-24 10:29
fixed via #83060

**Comment by jrieken** [comment] 2019-10-30 09:59
re-opened via 58479e80ab899402283b522da173c34867d7c78f

**Comment by jrieken** [comment] 2019-10-30 10:10
/duplicate of #83645

Closing this as a duplicate of #83645 which is all about finding a way out of the URI nightmare.

**Closed** 2019-10-30 10:10 UTC
Labels: *duplicate, bug, markdown, uri, webview
