### ISSUE TITLE
[Bug] In Diff-View Cannot Remove Line Comment Using Keyboard Hotkeys

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#100675] opened 2020-06-21 03:31 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open a file in diff view (e.g. from source control view)
2. Add line comment using keyboard hotkeys (e.g. Ctrl + K + Ctrl + C on windows as default key mapping)
3. Remove line comment using keyboard hotkeys (e.g. Ctrl + K + Ctrl + U on windows as default key mapping)

Same actions through command palette to "add line comment" then "remove line comment" works without issues in diff view.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.45GB free)|
|Process Argv|.\MY_LOCAL_PATH_XXXXXXXXXX\|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.5
gitlens|eam|10.2.2
pig|Gan|2.2.0
gc-excelviewer|Gra|2.1.35
rainbow-csv|mec|1.7.0
dotenv|mik|1.0.1
python|ms-|2020.6.89148
azure-account|ms-|0.8.11
azure-hdinsight|msh|1.1.10
sas|pvp|0.0.1
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1

</details>

**Comment by eamodio** [comment] 2020-06-22 14:24
Duplicate of #99011

**Closed** 2020-06-22 14:24 UTC
Labels: *duplicate, new release
