### ISSUE TITLE
Incorrect shortcut to "no option" when close a file

### ISSUE THREAD

**Issue by patrickmaciel** [microsoft/vscode#129984] opened 2021-08-02 18:25 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows 11 Pro x64 

Steps to Reproduce:

1. Create a new file and type anything
2. Click to close the tab/file
3. The shortcut select "No option" is "ã" instead of "n"

![Captura de tela 2021-08-02 150608](https://user-images.githubusercontent.com/671670/127906717-8241ad0a-c36b-468c-8f36-c979a9d6015f.png)

**Comment by v-mholloway** [comment] 2021-08-16 13:10
unable to track down that string in vscode translations
@patrickmaciel can you confirm the culture is Spanish-Spain (es-es)

**Comment by v-mholloway** [comment] 2021-08-20 11:29
this issue looks to be  dupe of https://github.com/microsoft/vscode/issues/119222

**Comment by v-mholloway** [comment] 2021-08-25 10:40
https://github.com/microsoft/vscode/issues/119222 no completed - closing this dupe

**Closed** 2021-08-25 10:40 UTC
Labels: L10N
