### ISSUE TITLE
Can't use git "Revert Change" on 1.76.0

### ISSUE THREAD

**Issue by dudukk1312** [microsoft/vscode#176266] opened 2023-03-06 16:16 UTC
Type: <b>Bug</b>

Hello everyone,

I got an issue on 1.76.0 version that couldn't use the "Revert Change" feature when showing a change in-line opened file.
![image](https://user-images.githubusercontent.com/33556384/223167952-f154594b-f82e-47f9-92b4-70fb15a72637.png)
After I click the "Revert Change" button, instead of reverting the change, it created many similar code blocks.
I downgrade to 1.75.1 version and this issue has gone.
I saw that the change counted to 10 even though I just change 2 lines of code.
![image](https://user-images.githubusercontent.com/33556384/223166967-5bcce0b1-3427-4906-9703-2cb30e3ee2f2.png)

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment] 2023-03-06 19:10
Looks like a duplicate of #176051

**Comment by larshp** [comment] 2023-03-06 19:18
also duplicate #175535

**Comment by lszomoru** [comment] 2023-03-09 12:33
Closing as duplicate of https://github.com/microsoft/vscode/issues/176051

**Closed by lszomoru** 2023-03-09 12:33 UTC
