### ISSUE TITLE
code uses all RAM and crashes

### ISSUE THREAD

**Issue by bardware** [Microsoft/vscode#54062] opened 2018-07-11 14:38 UTC
- VSCode Version: 1.25.0
- OS Version: Win 10 1709 (16299.431)

Steps to Reproduce:

1. change into project directory
2. start code using individual extension dir  `code . --extensions-dir "C:\vscode\cfml\exts" --new-window`

Does this issue occur when all extensions are disabled?: No

I've used `code` like this for a couple weeks and it has always worked perfectly. Today, code starts, fills up all RAM, and crashes.
When I use a different extension dir (specify none) code works.

I called code using the `--verbose` switch and look at the output.

```
[59244:0711/162835.927:INFO:CONSOLE(270)] "%c[Extension Host] %cWARNING: Promise with no error callback:4 %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:907)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
[59244:0711/162835.929:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
[59244:0711/162835.929:INFO:CONSOLE(270)] "%c[Extension Host] %cTypeError: Cannot read property 'split' of undefined
    at getComponentNameFromDotPath (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\entities\component.js:305:16)
    at Object.parseComponent (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\entities\component.js:166:33)
    at vscode_1.workspace.openTextDocument.then (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\features\cachedEntities.js:268:53)
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
    at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:1000)
    at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:394)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:693)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
    at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:996)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
[59244:0711/162836.570:INFO:CONSOLE(1376)] "%c  ERR", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1376)
[59244:0711/162836.871:INFO:CONSOLE(270)] "%c[Extension Host] %cNo editors associated with document: d:\projects\semiro\.vscode\settings.json %c(at DocumentDecoration.updateDecorations (C:\vscode\cfml\exts\coenraads.bracket-pair-colorizer-1.0.59\out\src\documentDecoration.js:313:21))", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
[59244:0711/162837.135:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[59244:0711/162924.232:INFO:CONSOLE(3041)] "%c[Extension Host] %cdebugger inspector at %cFATAL ERROR: Committing semi%c space failed. Allocation failed - process out of memory
", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (3041)
[59244:0711/162924.932:INFO:CONSOLE(3041)] "%c[Extension Host] %cdebugger inspector at %c
<--- Last few GCs --->

[60436:0000012E7DA58980]    33162 ms: Scavenge 347.9 (406.9) -> 332.9 (406.9) MB, 5.3 / 0.0 ms  allocation failure
[60436:0000012E7DA58980]    43607 ms: Scavenge 348.7 (407.4) -> 336.2 (407.4) MB, 18.2 / 0.0 ms  allocation failure
[60436:0000012E7DA58980]    68761 ms: Scavenge 349.9 (407.4) -> 338.8 (379.9) MB, 23.5 / 0.0 ms  allocation failure
[60436:0000012E7DA58980]    76946 ms: Scavenge 341.2 (379.9) -> 339.1 (376.4) MB, 22.6 / 0.0 ms  allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003392D52B959 <JS Object>
    0: builtin exit frame: stringify(this=000003392D510771 <a JSON with map 0000025026D86199>,000003B553B82311 <undefined>,000003B553B82311 <undefined>,000003456C07F1D1 <JS Array[3]>)

    1: arguments adaptor frame: 1->3
    2: _remoteCall [c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:~658] [pc=000002ACCFD610C3](this=000002664131F589 <a e wit...

", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (3041)
[59244:0711/162924.961:INFO:CONSOLE(3136)] "Extension host terminated unexpectedly. Code: ", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (3136)
[59244:0711/162934.322:INFO:CONSOLE(2364)] "Der Erweiterungshost wurde unerwartet beendet.", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (2364)[main 16:31:38] Lifecycle#window-before-close 1
[main 16:31:38] Lifecycle#unload() 1
[59244:0711/163138.149:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[59244:0711/163138.152:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 16:31:38] Lifecycle#unload(): unload continues without veto 1
[59244:0711/163138.154:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[59244:0711/163138.627:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 16:31:38] Lifecycle#onBeforeWindowClose.fire()
[main 16:31:38] Lifecycle#window-before-close 1
[main 16:31:38] Lifecycle#window-close 1
[main 16:31:38] Lifecycle#window-closed 1
[main 16:31:38] Lifecycle#onShutdown.fire()
[main 16:31:38] Lifecycle#window-all-closed
[main 16:31:38] Lifecycle#before-quit
[main 16:31:38] Lifecycle#onBeforeShutdown.fire()
[main 16:31:38] App#will-quit: disposing resources
```
I see no pointer to the failing extension. Every error line reads `workbench.main.js`.
I would love to find out which extension causes this behaviour.

**Comment by bardware** [comment] 2018-07-11 14:48
I uninstalled two extensions and now the verbos loggin ends so:
```
[65304:0711/164503.495:INFO:CONSOLE(1376)] "%c  ERR", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1376)
[65304:0711/164504.008:INFO:CONSOLE(1375)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1375)
[main 16:45:07] update#checkForUpdates, state =  idle
[main 16:45:07] update#setState checking for updates
[main 16:45:07] RequestService#request https://vscode-update.azurewebsites.net/api/update/win32-x64/stable/0f080e5267e829de46638128001aeb7ca2d6d50e
[main 16:45:08] update#setState idle
[main 16:46:11] [VS Code]: render process crashed!
[main 16:46:17] Lifecycle#window-closed 1
[main 16:46:17] Lifecycle#onShutdown.fire()
[main 16:46:17] Lifecycle#window-all-closed
[main 16:46:17] Lifecycle#before-quit
[main 16:46:17] Lifecycle#onBeforeShutdown.fire()
[main 16:46:17] App#will-quit: disposing resources
```

**Comment by charlesartbr** [comment] 2018-07-11 15:23
This is happening with me and all my teammates.

I tried to uninstall and install again with no success.

I think that there is something related to marketplace, when I open a simple project there is no problem, when open an Angular project the VS Code freeze, it raises the memory usage to more than 3 Gb and start to show lots of extensions recomendations for every type of file (ex. .def, .m4, .gnu, .disabled).

![vscode](https://user-images.githubusercontent.com/12157011/42582187-e0b58dd6-8504-11e8-8efd-3b01d8a1d381.png)

**Comment by mjbvz** [comment] 2018-07-11 16:53
@bardware Seems to be caused by the CFML extension so I'm going to close this issue. Let me know if you think the VS Code itself is to blame

@charlesartbr Try following [these steps](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to investigate which extension may be causing this. Please open a new issue against that extension or against VS Code if this happens even with all extensions disabled

**Closed by mjbvz** 2018-07-11 16:53 UTC

**Comment by bardware** [comment] 2018-07-12 08:33
I just realize the were files named `debug.log` generated
They contain something like:
```
[0711/101101.770:ERROR:icu_util.cc(180)] Couldn't mmap icu data file
[0711/101101.771:FATAL:icu_util.cc(292)] Check failed: result. 
Error initializing symbols (8).  Dumping unresolved backtrace:
	00007FF6D546AF15
	00007FF6D54DAFD3
	00007FF6D5462B64
	00007FF6D5461BA3
	00007FF6D51B8DCC
	00007FF6D842F4F7
	00007FFC4E861FE4
	00007FFC512DF061
```
