### ISSUE TITLE
code formatting not working good with JS

### ISSUE THREAD

**Issue by zaher88abd** [Microsoft/vscode#15216] opened 2016-11-08 23:24 UTC
- VSCode Version: 1.7.1
- OS Version: Win 10 Education

**Comment by aeschli** [comment] 2016-11-09 09:50
@zaher88abd Please add a code snippet that demonstrates the problem.

**Comment by zaher88abd** [comment] 2016-11-09 16:18
<script>
	  var app = angular.module("MyApp", []);
	  app.controller("MinesweeperController", ["$scope", function($scope) {
          var mineField={};
          mineField.rows=[];
          $scope.mineRow=0;
          $scope.mineColumn=0;
          var placeRedomeMine=function(){
            var row=Math.round(Math.random()*0);
            var colum=Math.round(Math.random()*0);
            var spot=getSpot(mineField.row.spots[row,column]);
          }

      	  var createMinerFilede=function(){
          for(var i=0;i<9;i++)
            {
              var row={};
              row.spots=[];
              for(var j=0;j<9;j++)
              {
                var spot={};
                spot.isMine=false;
                spot.isHidden=true;
                spot.isCovered=false;
                row.spots.push(spot);
              }
              mineField.rows.push(row);
            }
            return mineField;
                    }
                    $scope.changeSpot=function(spot){
                      if(spot.isHidden){
                        if(!spot.isMine){
                        spot.isHidden=false;
                        spot.isCovered=true;
                      }
                
                      
                    }}
                    $scope.mineField=createMinerFilede();
                    $scope.placeRedomeMine();
      }]);
      </script>

**Comment by zaher88abd** [comment] 2016-11-09 17:01
this is the code 
[https://github.com/zaher88abd/Minesweeper-with-AngularJS/blob/master/index-basic.html](url)

**Comment by aeschli** [comment] 2016-11-09 19:26
Ah, this is about embedded JS. Duplicate of #12972

**Closed by aeschli** 2016-11-09 19:26 UTC
Labels: js, needs more info
