### ISSUE TITLE
VSCode crashed when problems panel shows too many items.

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/vscode#56304] opened 2018-08-14 06:38 UTC
- VSCode Version:1.25.0
- OS Version:Windows 10 1803

Steps to Reproduce:
1. Open a project with many diagnostics message
2. Click the Problems panel

We tried to open Elasticsearch project by VSCode with Java Language Server, and the language server returned too many diagnostics messages(about 160k). As a result,  when we clicked the  problems panel, vscode crashed. So is there any solutions to fix this bug? or language server should set a limitation for message number?

Does this issue occur when all extensions are disabled?: Yes/No 
No (I'm not sure will vscode have such an amount of error message without any extension)

**Comment by sandy081** [comment] 2018-08-29 14:18
@Flanker32 Is it possible to get any stack traces of crash?

**Comment by Flanker32** [comment] 2018-08-31 02:56
In the main.log of vscode ,it shows 
```
[2018-08-31 10:48:05.911] [main] [error] [VS Code]: detected unresponsive
[2018-08-31 10:49:03.756] [main] [error] [VS Code]: render process crashed!
```
And vscode shows The windows is no longer responding, you can reopen or close the window or keep waiting.
To reproduce the error, you may download elasticseach V6.3.2(they seems to fix some bug in the latest release). Runs `./gradlew eclipse` and open the folder by vscode with java language server.
@sandy081

**Comment by sandy081** [comment] 2018-08-31 08:10
@Flanker32 May I know how many problems are being generated? If I know the number I can generate them using a sample extension and try?

**Comment by sandy081** [comment] 2018-09-11 14:30
Duplicate of #25581

**Comment by sandy081** [comment] 2018-09-18 10:08
There are two performance issues

1. Rendering large number of diagnostics in problems view
2. Collapse all 

Since this issue is specific to rendering the view, will provide a fix for that here. And leave the other issue for collapse all. 

Problem is that I am auto expanding every file in the view and this is very costly. Also expanding the file from outside the tree infra is also impacting the performance. Hence applied the similar style of Search view, auto expand only if there are < 10 entries and use the tree data source auto expand api.

File is auto expanded when the corresponding file is opened and auto reveal is enabled.

**Comment by sandy081** [comment] 2018-09-18 10:11
To verify:

- Create a sample extension with large number of diagnostics

```ts
export function activate(context: vscode.ExtensionContext) {
    const diagnosticsCollection = vscode.languages.createDiagnosticCollection('test');
    for (let i = 0; i < 1000; i++) {
        const diagnostics: vscode.Diagnostic[] = [];
        for (let j = 0; j < 1000; j++) {
            diagnostics.push(new vscode.Diagnostic(new vscode.Range(new vscode.Position(1, 1), new vscode.Position(1, 10)), `Message ${j}`, vscode.DiagnosticSeverity.Error));
        }
        diagnosticsCollection.set(vscode.Uri.file(`/foo/bar/package${i}.json`), diagnostics);
    }
}
```

Make sure that Problems view is reponsive

**Comment by sandy081** [comment] 2018-09-18 12:44
This is not completely fixed. Hence I am reopening this. We always want to expand every file entry in the problems view and this will have the performance impact. The underlying tree has to fixed to scale well.

**Comment by sandy081** [comment] 2018-10-22 19:30
This no longer hangs UI with new tree. Thanks @joaomoreno

**Closed by sandy081** 2018-10-22 19:30 UTC
Labels: bug, error-list, perf, tree

**Comment by alexr00** [comment] 2018-11-02 11:21
Reminder to wait to test this until the @joaomoreno has the array splice fix in.
