### ISSUE TITLE
Suggestion: persist TypeScript version choice to workspace settings

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#30069] opened 2017-07-03 20:13 UTC
When selecting a version of TypeScript through the "Select TypeScript Version" command, it would be good if this was persisted to the workspace settings.

I understand this is persisted to local storage, but that will not survive the boundaries of machines, nor a project rename.

**Comment by mjbvz** [comment] 2017-07-03 21:00
We support setting `typescript.tsdk` in the workspace settings but for security reasons we always require that users opt into using the workspace version of typescript. That's where local storage comes into play.

It's an configuration extra step, but we do need do it this way to ensure that opening workspaces from unknown sources is a safe operation. Closing as by design. Please let me know if you have any questions about the current design or thoughts on a better opt in style flow for selecting the typescript version.

**Closed** 2017-07-03 21:07 UTC
Labels: as-designed, typescript
