### ISSUE TITLE
Javascript string template collapse

### ISSUE THREAD

**Issue by cbertozzi** [microsoft/vscode#82140] opened 2019-10-09 06:43 UTC
Issue Type: <b>Feature Request</b>

Javascript strig teplates such as:
```javascript
`this is a hello world defined as a string template
with a new line that unfortunately does not collapse
:(`
```
that allows new lines by design, is impossible to collapse with icons on the left side of the editor

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment] 2019-10-09 15:11
Duplicate of https://github.com/microsoft/TypeScript/issues/23382

**Closed by mjbvz** 2019-10-09 15:11 UTC
