### ISSUE TITLE
update new VSCode 1.12.1.

### ISSUE THREAD

**Issue by zhoujinshi** [Microsoft/vscode#26000] opened 2017-05-05 07:59 UTC
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|pascal|alefragnani|0.8.0|
|vscode-javascript-snippets|codepunkt|1.0.0|
|file-icons|file-icons|1.0.3|
|vscode-javac|georgewfraser|0.0.41|
|vue|jcbuisson|0.1.5|
|copy-markdown-as-html|jerriepelser|1.0.0|
|mdhelper|joshbax|0.0.9|
|format-php|Kasik96|1.1.2|
|csharp|ms-vscode|1.9.0|
|sublime-keybindings|ms-vscode|2.0.1|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|vetur|octref|0.6.4|
|vue-beautify|peakchen90|2.0.4|
|material-icon-theme|PKief|2.0.5|
|vscode-jsp|pthorsson|0.0.2|
|Material-theme|zhuangtongfa|2.7.0|;

---

Steps to Reproduce:

1.<script id="cart-list" type="text/html">
2.update VSCode this script tag info input html heightlight display is error.

**Comment by mjbvz** [comment] 2017-05-05 08:06
Duplicate of #25920

**Closed by mjbvz** 2017-05-05 08:06 UTC
Labels: duplicate
