### ISSUE TITLE
Tab wrapping automatic adjust affect mouse selection

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#115126] opened 2021-01-26 19:17 UTC
Testing #114827

* Create two editor groups with a lot of tabs which need wrapping
* Clicking between the two will trigger the tab height to change as editor toolbar width changes, which will then mess up with mouse click 

![recording (6)](https://user-images.githubusercontent.com/876920/105893541-12e49400-5fc8-11eb-8e97-830846bc4ab5.gif)

As shown in above gif, single mouse click becomes selection.

**Comment by yume-chan** [comment] 2021-01-27 00:02
Duplicate of #113818

**Closed** 2021-01-27 08:13 UTC
