### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by lyubok** [microsoft/vscode#95210] opened 2020-04-14 11:00 UTC
Searching for any string in the project/workspace files (Ctrl+Shift+F) is not returning any results and the search can run for hours. Same with Ctrl+P.

Version: 1.44.0 (user setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chrmarti** [comment] 2020-04-15 07:18
Is there anything in the console? (`Help` > `Toggle Developer Tools`)

Did this work with VS Code 1.43? Could your virus scanner be interfering with the `rg.exe` we use to search (for) files?

**Comment by roblourens** [comment] 2020-04-15 14:19
Most likely a duplicate of https://github.com/microsoft/vscode/issues/94928, if you have a workspace folder that uses a filesystem provider extension.

**Closed** 2020-04-23 11:22 UTC
Labels: needs more info, search
