### ISSUE TITLE
source control (Git)

### ISSUE THREAD

**Issue by erwindenboer** [microsoft/vscode#157628] opened 2022-08-09 11:37 UTC
Type: <b>Bug</b>

I use an SSH protected Git repository. Whenever I want to commit and push my changes, I need to type my password. However, this is not possible in VS Code itself. The workaround is going to the file explorer → opening git bash → type `git push` → type password and the changes will be pushed.

Is it possible to implement a way such that I can type the password in VS Code without the workaround. I already asked this [question](https://stackoverflow.com/questions/72972408/git-works-using-git-bash-in-terminal-but-not-in-vs-code) on stackoverflow with screenshots and the like. From the comments, I get the impression that more people have the same problem 
[problem 1](https://github.com/microsoft/vscode/issues/115371).
[problem 2](https://github.com/microsoft/vscode-remote-release/issues/4244).
[problem 3](https://github.com/microsoft/vscode/issues/13680).

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.93GB free)|
|Process Argv|--crash-reporter-id af79616c-e594-4fd6-93d3-be9ff531ba8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.4.0
githistory|don|0.6.19
gitlens|eam|12.1.2
code-runner|for|0.11.8
matlab|Gim|2.3.1
vscode-pull-request-github|Git|0.48.0
latex-workshop|Jam|8.28.0
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5683
vsliveshare-audio|ms-|0.1.91
terminal-command-keys|pet|0.3.0
vscode-yaml|red|1.9.1
manim-sideview|Ric|0.0.13
vscode-modern-vhdl-support|rjy|1.0.6
gurulang|Sha|0.14.1
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscode-ltex|val|13.1.0
maple|yjt|1.2.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253

```

</details>

**Comment by lszomoru** [comment] 2022-08-24 10:17
Closing this as duplicate of https://github.com/microsoft/vscode/issues/13680. Please subscribe to that issue to follow the progress.

**Closed by lszomoru** 2022-08-24 10:17 UTC
