### ISSUE TITLE
${env:VARIABLE} does not work on linux

### ISSUE THREAD

**Issue by Nibblesh** [microsoft/vscode#75471] opened 2019-06-14 04:06 UTC
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-21-generic

Steps to Reproduce:

1. Set Environment Variable for vs code
settings.json:
```json
{
    "terminal.integrated.env.linux": {
        "TESTVAR": "somestring"
    }
}
```

2. set tasks JSON using environment reference
```js
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
      {
        "type": "shell",
        "label": "test",
        "command": "echo ${env:TESTVAR}"
      },
      {
        "type": "shell",
        "label": "test2",
        "command": "echo $TESTVAR"
      }
  ]
}
```

expected behaviour:

expect task "test" to echo envar

actual behaviour:

only task "test2" works, task "test" returns empty string

variable is not injected, and the reference becomes empty string and is ignored

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment] 2019-06-17 12:42
Duplicate of https://github.com/microsoft/vscode/issues/74375

**Closed** 2019-06-17 12:42 UTC
Labels: *duplicate, tasks
