### ISSUE TITLE
conhost.exe is not terminated when VSCode exits

### ISSUE THREAD

**Issue by CrendKing** [microsoft/vscode#188227] opened 2023-07-19 01:15 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.80.1, Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Install fresh copy of VSCode.
2. Put this tasks.json in a workspace or in user data directory:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Test 1",
            "type": "shell",
            "command": "cmd /c pause",
            "problemMatcher": [],
        },
        {
            "label": "Test 2",
            "type": "shell",
            "command": "cmd /c start pause",
            "problemMatcher": [],
        },
    ]
}
```
3. Run task Test 1, notice the integrated terminal is opened and paused with the `pause` command. Keep it that way, and open Task Manager. Expand the process tree of VSCode, and find the child "Console Window Host" process (conhost.exe). Write down its PID.
4. Without pressing any key in the terminal, close VSCode. In Task Manager, you will find the cmd.exe process is gone as expected, but the conhost.exe process stays forever as an orphan.
5. Repeat the process with Test 2, notice Code.exe's child conhost.exe process terminates automatically in a few seconds, even the external console is still paused. No conhost.exe process leaks.
6. I believe the conhost is necessary for capturing process output for problem matcher, but this issue still exists even we have setting `"task.problemMatchers.neverPrompt": { "shell": true }`.
7. This issue only exists when using the ConPTY option. Setting `terminal.integrated.windowsEnableConpty` to false solves the problem, but ConPTY is recommended.

**Comment by meganrogge** [comment] 2023-07-19 16:35
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

If you cannot reproduce in Windows Terminal, chances are it's fixed in a later version of Windows. You can read more about [how we consume conpty here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label upstream terminal-conpty windows

**Closed by meganrogge** 2023-07-19 16:35 UTC

**Comment by CrendKing** [comment] 2023-07-19 19:24
When I run any console app (including cmd.exe) in Windows Terminal, there is no conhost.exe spawned at all. Instead there is the OpenConsole.exe. It seems might be some architectural differences, but I'm not sure where to proceed next.
