### ISSUE TITLE
Missing ffmpg.dll

### ISSUE THREAD

**Issue by Bazmundi** [microsoft/vscode#110799] opened 2020-11-17 11:45 UTC
- VSCode Version: 1.51.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Install 1.51.1 ages ago
2. Install various extensions over a long time and have a good time
3. Find an extension for jupyter and get excited
4. Find you must install 1.52.0 insider to use jupyter extensions
5. Reluctantly uninstall perfectly good 1.51.1
6. Install 1.52.0 insider per instructions for jupyter extension
7. Find it isn't happy to run apl kernel that you've been running 
8. Find it also has not picked up all the other extensions you meticulously set up under 1.51.1
9. Opt to uninstall 1.52.0 insider and re-install 1.51.1
10. run code fails with report of missing dll
11. Error message reports a reinstall might fix the problem
12. re-install 1.51.1 again
13. run code fails with report of missing dll

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment] 2020-11-17 11:56
Step 5 wasn't necessary. Insiders happily coexists with Stable

Does message at step 11 come from one of your extensions? It's likely you need to reinstall whichever extension requires ffmpg.dll

**Comment by IllusionMH** [comment] 2020-11-17 17:46
May be duplicate of #100599 because VSCode doesn't ship full ffmpeg library.

**Comment by Bazmundi** [comment] 2020-11-17 20:46
Fail is on start. Code does not otherwise run. So it means ripping
everything out and reinstalling the lot?

**Comment by gjsjohnmurray** [comment] 2020-11-18 03:45
Try launching code.exe with the CLI argument that disables all extensions. Does that succeed?

**Comment by roblourens** [comment] 2020-11-18 18:25
What is the actual error? Which dll? And yes please try disabling extensions.

**Comment by Bazmundi** [comment] 2020-11-19 10:30
Rob. Read title and the initial report.

**Comment by gjsjohnmurray** [comment] 2020-11-19 11:08
> 
> 
> Try launching code.exe with the CLI argument that disables all extensions. Does that succeed?

@Bazmundi did you do this yet?

```
code,exe --disable-extensions
```

**Comment by Bazmundi** [comment] 2020-11-20 05:02
@John Murray. The bug report asks you to do that and answer yes or no
to the question does problem still occur with widgets disabled yes?

**Comment by gjsjohnmurray** [comment] 2020-11-20 05:33
@Bazmundi thanks for confirming that the startup crash happens even with extensions disabled.

Please review https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and submit the extra details. Do this directly on the GitHub site, not via email.

**Comment by Bazmundi** [comment] 2020-11-20 23:31
No, I did not.  @John Murray I have already ripped out all of my extensions
by deleting .code directory to start building my environment again.
Sorry.  Consider this closed.

**Closed** 2020-11-21 19:19 UTC
Labels: needs more info
