### ISSUE TITLE
Selecting item from Settings-Render Whitespace option list is erratic

### ISSUE THREAD

**Issue by csaba-f-kiss** [Microsoft/vscode#69306] opened 2019-02-24 12:32 UTC
Issue Type: <b>Bug</b>

**Issue**
Options page, drop-down item selection list for "Editor: Render Whitespace" behaves erratically, choosing a new item from the list is not possible.

**Steps to reproduce**
Open (User) Settings page, change the default option for "Editor: Render Whitespace" to "boundary". Next try to change again this time to "none" or "all". The drop-down list displays OK, but when the cursor is moved to select an item the list shifts downwards, moving cursor further down the list of items moves back upwards. Issues persist even after resetting option. List selection is completely erratic.

![image](https://user-images.githubusercontent.com/25961497/53299241-f23dbd80-3837-11e9-86d7-2459edf4c21d.png)

When moving cursor to select from the shifted list:
![image](https://user-images.githubusercontent.com/25961497/53299261-1d281180-3838-11e9-83dc-a114cbe9e751.png)
list changes and the description will be shifter under the cursor, making a selection impossible.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (52.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
xml|Dot|2.3.2
gitlens|eam|9.4.1
language-cython|guy|0.0.5
vscode-cudacpp|kri|0.1.1
linter-gfortran|krv|2.0.2
restructuredtext|lex|103.0.0
Angular-BeastCode|Mik|7.0.29
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
vscode-docker|Pet|0.5.2
java|red|0.38.0
vscode-yaml|red|0.1.0
arduino-vscode|ste|0.2.2
vscodeintellicode|Vis|1.1.3
vscode-arduino|vsc|0.2.23
pyqt-integration|zho|0.2.0

</details>

**Comment by roblourens** [comment] 2019-02-25 23:53
Hm, this is probably related to https://github.com/Microsoft/vscode/issues/67462#issuecomment-460509851 somehow

**Comment by roblourens** [comment] 2019-03-06 23:23
Calling this a duplicate of #69297

**Closed by roblourens** 2019-03-06 23:23 UTC
Labels: bug, settings-editor
