### ISSUE TITLE
How to rebind navigation in "Reference Search"?

### ISSUE THREAD

**Issue by cryptomaniac512** [Microsoft/vscode#35828] opened 2017-10-08 12:19 UTC
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.13_1
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-eslint|dba|1.3.2
python|don|0.7.0
gitlens|eam|5.4.1
vetur|oct|0.9.10
language-stylus|sys|1.7.3
vim|vsc|0.10.1
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---
Usually, I need to navigate with Ctrl+p and Ctrl+n instead of UpArrow and DownArrow. How can I bind it in Reference Search popup?
![image](https://user-images.githubusercontent.com/10251687/31316734-81e2f99a-ac76-11e7-8b77-455d9ace4744.png)
![image](https://user-images.githubusercontent.com/10251687/31316741-aad0a2ee-ac76-11e7-9f24-d896af28a5bc.png)

**Comment by jrieken** [comment] 2017-10-10 07:30
@bpasero Did you make tree navigation keyboard accessible at one point?

**Comment by bpasero** [comment] 2017-10-11 08:04
Dupe of https://github.com/Microsoft/vscode/issues/21692

**Closed by bpasero** 2017-10-11 08:04 UTC
Labels: editor-contrib, feature-request
