### ISSUE TITLE
C/C++ code highlighting in Markdown breaks in many ways

### ISSUE THREAD

**Issue by Ristarg** [Microsoft/vscode#54932] opened 2018-07-24 11:23 UTC
Issue Type: <b>Bug</b>

For C/C++ code spans in Markdown, the highlighting in the editor breaks depending on newlines, indentation, current planet alignment and god knows what else. Preview highlighting is not affected. Other C-like languages (Rust, JS, Go, Java) are not affected, from my limited testing.

## Steps to reproduce:
1. Open a new file with Markdown highlighting.
1. Create a C or C++ highlighted code span (\`\`\`c etc.)
1. Put valid C code inside the code span.
### Expected:
- C code is correctly highlighted in the editor.
### Actual:
- Highlighting breaks ostensibly arbitrarily.

## Some examples

Highlight completely bails after left paren:
```c
int x = 123 + (234 - 345);
int y = x + 10;
```
![image](https://user-images.githubusercontent.com/18281341/43134613-c7dd0902-8f6c-11e8-84fb-3986d6baf4c4.png)

Can be worked around if you put closing paren on a newline:

```c
int x = 123 + (234 - 345
);
int y = x + 10;
```
![image](https://user-images.githubusercontent.com/18281341/43134624-d141921a-8f6c-11e8-9404-251226e51865.png)

But only if it is not indented:

```c
int x = 123 + (234 - 345
 );
int y = x + 10;
```
![image](https://user-images.githubusercontent.com/18281341/43134633-d9837eac-8f6c-11e8-892c-bdc03c2f1296.png)

If you insert a newline after the left paren, the next line is highlighted in one color and the rest breaks:
```c
int x = 123 + (
    234 - 345);
int y = x + 10;
```
![image](https://user-images.githubusercontent.com/18281341/43134645-e39bc7a0-8f6c-11e8-9d84-e0687404894c.png)

Similar thing occurs for well-indented functions:
```c
int foo() {
    if (3 > 5) {
        return 2;
    } else {
        return 123;
    }
}
```
![image](https://user-images.githubusercontent.com/18281341/43134655-eadcd0fe-8f6c-11e8-8ee1-0a32a64e5759.png)

However, if you remove the newline after the first curly brace, the highlight bails again until matching closing brace:
```c
int foo() {if (3 > 5) {
        return 2;
    } else {
        return 123;
    }
}
```
![image](https://user-images.githubusercontent.com/18281341/43134663-f5729af8-8f6c-11e8-8be5-c4b56c18d86d.png)

### Side note
Somewhat tangentially related is improper pound directive highlighting:
```c
#define TRUE 1
#define FALSE 0
```
![image](https://user-images.githubusercontent.com/18281341/43134914-d2e91a42-8f6d-11e8-8e51-1bf04a9506a5.png)

Works as intended with an extra newline in between:
```c
#define TRUE 1

#define FALSE 0
```
![image](https://user-images.githubusercontent.com/18281341/43134964-01c6c7c4-8f6e-11e8-9b0d-d63ab91212e3.png)

Apologies if this isn't the right place to report this.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\afili\Downloads\discord\messages\89965538633064448\channel.json|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|8.5.2
vsc-material-theme|Equ|2.3.0
gc-excelviewer|Gra|2.1.24
beautify|Hoo|1.3.2
discord-vscode|icr|2.7.0
vscode-ebnf|igo|1.0.3
cpptools|ms-|0.17.7
rust|rus|0.4.9
crates|ser|0.2.4
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by mjbvz** [comment] 2018-07-24 18:04
Duplicate of #34525

See that issue for more details. Not fixable on our side using the current approach to grammars

**Closed by mjbvz** 2018-07-24 18:04 UTC
Labels: editor, editor-autoindent
