### ISSUE TITLE
Emmet is working(only p is not working)

### ISSUE THREAD

**Issue by wikilike7** [Microsoft/vscode#20531] opened 2017-02-13 07:53 UTC
- VSCode Version:  19.1
- OS Version: Win 7 x64

Steps to Reproduce:

1. when i enter `p` then press `tab` only `doctype` apprea
2. if i use `p*1` is working, other code like `h1 h2 div` etc also.

![image](https://cloud.githubusercontent.com/assets/3377226/22875075/9c0cfe1a-f204-11e6-88ff-5eb8c94125ca.png)

**Comment by egamma** [comment] 2017-02-20 14:21
Actually emmet expands properly you can see this when you expand `p` using the comments `Emment: Expand Abbreviation` from the command palette. The issue is that `p` has word/quick suggestions (e.g. `DOCTYPE`) and pressing `TAB` commits the suggestion. To avoid this problem you can disable quick suggestions in html by adding the following setting:
```json
    "[html]": {
		"editor.quickSuggestions": false
    }
```

@ramya-rao-a this is an open issue, one idea would be that emmet abbreviations are also shown in the suggestion pop-up.

**Comment by ramya-rao-a** [comment] 2017-02-20 19:49
Adding emmet abbreviations to suggestion pop-up would be much simpler to do if emmet integration was done as an extension. This is what is the plan for Emmet 2.0 

Regardless, I'll take a look at what it takes to add emmet abbreviations to suggestion pop-up in the current design.

#1952 is tracking this exact issue of suggestion items overlapping with emmet expansions, and the suggestion item winning. 

#20716 is tracking the same for any snippet vs suggestion item.

Therefore closing this in favor of #1952

**Closed by ramya-rao-a** 2017-02-20 19:49 UTC

**Comment by egamma** [comment] 2017-02-23 09:31
@ramya-rao-a regarding

>Adding emmet abbreviations to suggestion pop-up would be much simpler to do if emmet integration was done as an extension. This is what is the plan for Emmet 2.0

Rather than adding all emmet abbreviations to the completions list, we could add a single item "Expand emmet abbreviation" to the completion list. This is similar to what is done now for JSDoc expansions. See below. This should be doable with the existing emmet version.

![image](https://cloud.githubusercontent.com/assets/172399/23252985/1cdec32e-f9b3-11e6-9f70-7daeb0ae1cdd.png)

**Comment by ramya-rao-a** [comment] 2017-02-23 20:51
I didn't mean to add all emmet abbreviations to the completion list. I meant adding just a single one like your example, choosing which the abbreviation will be expanded.

As far as I know, the cleanest way to contribute to the completion list is via extension using the APIs exposed to extensions. The jsdoc expansions are done via the typescript extension. 

Of course, there are textual completions that are coming from the core code.

@jrieken Is it recommended to contribute to completion list directly in the core code?

**Comment by ramya-rao-a** [comment] 2017-06-01 05:33
See https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464 to get emmet abbreviations in the completion list
