### ISSUE TITLE
Extensions can't work with large files

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#3147] opened 2016-02-19 02:55 UTC
VS Code doesn't provide the document element of the editor when a large file is open. This means that extensions can't get any file information at all.

Editing still works fine, even a (large number of) find/replace functions work.

Using `registerTextEditorCommand` fails to enter the callback function at all (presumably the exception is thrown when the arguments to the callback are created) and trying to access the document via the activeTextEditor in `registerCommand` fails (throws) when attempting to access the `.document` getter of the `TextEditor` object. Inspecting the activeTextEditor object shows that `_documentData` is `undefined`

I've had this failure with a 6MB file. Yet editing, and highlighting (JSON) work on a 16MB file.

**Comment by egamma** [comment] 2016-02-20 15:29
// @jrieken

**Comment by alexandrudima** [comment] 2016-02-22 08:09
Indeed, this is our current strategy for handling large files:
* files < 5 MB get synced everywhere
* files < 20MB get only colorization and don't get synced to the extension host (invisible to extensions), nor to web workers (no diff)
* files > 20MB don't get colorization and don't get synced.

**Comment by jrieken** [comment] 2016-04-29 10:22
closing this cos this it is by design.

**Closed by jrieken** 2016-04-29 10:22 UTC
Labels: editor
