### ISSUE TITLE
"File > Save all" bug that put a file into another

### ISSUE THREAD

**Issue by lainz** [Microsoft/vscode#22330] opened 2017-03-09 21:28 UTC
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|delphi-keybindings|alefragnani|0.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.6.0|;

---

Steps to Reproduce:

1. You need to have 2 unsaved files, I tested it with an html (configuracion.html) file and a javascript file (configuracion.controller.js). Place the cursor in the javascript file and then go to File > Save all menu. See the attached gif.
![saveallproblem](https://cloud.githubusercontent.com/assets/4131395/23771425/aa329bd6-04f5-11e7-9c29-a82a4cea6990.gif)

2. Then you will have the html file inside the javascript file.

**Comment by ramya-rao-a** [comment] 2017-03-09 21:47
Can you try again after running `code --disable-extensions`  ? This is just to ensure that the extensions are not interfering with the Save action

**Comment by lainz** [comment] 2017-03-09 22:48
Hi, I disabled the extensions and then I can't replicate it again.

When I enabled the extension JS-CSS-HTML Formatter by lonefy it happens again. I've checked all these three extensions I have one by one so I'm sure that is specific to that extension.

**Comment by lainz** [comment] 2017-03-09 22:55
Hi again, I quickly went to the extension repository and find that there's already a bug reported related to this, but instead of Save All they report Close All. 
#21993

**Comment by ramya-rao-a** [comment] 2017-03-09 23:50
Thanks @lainz 

@bpasero Should we investigate how the extension affects us in such a way to prevent future issues?

**Comment by bpasero** [comment] 2017-03-10 05:15
YES!

**Comment by jrieken** [comment] 2017-03-10 08:02
According to https://github.com/Microsoft/vscode/issues/22330#issuecomment-285508779 it is the JS-CSS-HTML-formatter.

**Comment by jrieken** [comment] 2017-03-10 08:03
closing as dupe of https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/53

**Closed by jrieken** 2017-03-10 08:03 UTC
Labels: caused-by-extension, workbench

**Comment by ramya-rao-a** [comment] 2017-03-10 19:14
@jrieken We determined that this is https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/53 already. See https://github.com/Microsoft/vscode/issues/22330#issuecomment-285510423 

Question for us is if we can do anything from our side to prevent such incidents?

**Comment by jrieken** [comment] 2017-03-13 07:35
Unfortunately not, the extension implements a formatter that confuses different documents. The extension seems to be abandoned and we can just hope for natural regulation: bad experience, bad ratings, less installed, less problems...

**Comment by jrieken** [comment] 2017-03-13 07:35
Tho, I did offer our help (https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/53#issuecomment-285607513) and fixing this major annoyance should be trivial. That's the sad part...

**Comment by ramya-rao-a** [comment] 2017-03-13 17:42
thanks @jrieken
