### ISSUE TITLE
Launching extension development with --disable-extensions flag disables source map resolution

### ISSUE THREAD

**Issue by viktomas-gitlab** [microsoft/vscode#138330] opened 2021-12-02 09:42 UTC
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.63.0-insider
- Commit: b9cf83f70bb6b4697b544a97c7056dfd28fccc5f
- Date: 2021-11-30T05:15:31.929Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Linux x64 5.15.5-arch1-1

During extension development, when I launch a bundled extension (webpack or esbuild), VS Code fails to resolve source maps and shows stack trace pointing to the one bundled source file. This only happens when I use `--disable-extensions` CLI argument. This makes the extension development more difficult because I develop my extensions with the `--disable-extensions` argument on.

#### Videos showing the issue

| stacktrace without --disable-extensions (works well) | stack trace with --disable-extensions (bug) |
| -- | -- |
|  https://user-images.githubusercontent.com/78416057/144396318-5b9599b4-db39-4373-8c08-bd5d374d4df7.mp4 | https://user-images.githubusercontent.com/78416057/144396488-c07b3d34-9063-4ae5-8f56-a21e1a8143a6.mp4 |

#### Steps to Reproduce:

1. Use `yo code` to generate a new TS extension bundled with webpack
2. Add `throw new Error('test');` at the end of the `activate()` method
3. Launch the extension, run `Hello World` command, and see that the stack trace points to `extension.ts` (correct)
4. Open `.vscode/launch.json` and add `--disable-extensions` to your configuration's `arg` field.
5. Launch the extension, run `Hello World` command, and see that the stack trace points to the bundled `dist/extension.js` (incorrect)

I created a test project here: https://gitlab.com/viktomas/test-source-maps-extension

The two-line change that simulates the problem (described in steps to reproduce): https://gitlab.com/viktomas/test-source-maps-extension/-/commit/3eead22a42f21c08f67b283dee32c4d9a11fe6c7

**Comment by alexdima** [comment] 2021-12-03 16:20
@deepak1556 Is it possible that`--disable-extensions` is also interpreted by Electron/Chromium/Chrome Dev Tools and results in them disabling source mapping?

**Comment by deepak1556** [comment] 2021-12-04 04:21
`--disable-extensions` when passed down to the runtime will only disable the chrome extension system but we don't build with that feature so it has no effect in our product build. Also, if you check the cli flags for the devtools/renderer process `--disable-extensions` is not present.

QQ: isn't the error stack generated by the extension host, so the problem here would be extension host not resolving the source maps right ?

**Comment by alexdima** [comment] 2021-12-06 08:10
> QQ: isn't the error stack generated by the extension host, so the problem here would be extension host not resolving the source maps right ?

AFAIK it is Chrome Dev Tools that renders the stack trace of a console.log message. I don't know why Chrome Dev Tools would opt to use source maps most of the times but then chose not to use source maps when Electron is invoked with `--disable-extensions`. Given you confirm that `--disable-extensions` is something Chromium parses, I think this might change some internal state in Chromium that results in the console.log messages no longer using source maps.

**Comment by weinand** [comment] 2021-12-06 09:02
removed "debug" assignments because this issue is a Chrome devtool issue.

**Comment by viktomas-gitlab** [comment] 2021-12-06 09:03
@alexdima @weinand the source-map problem is not specific to the `console` in Chrome Dev Tools. When I log the error stack trace into an [output channel](https://code.visualstudio.com/api/references/vscode-api#OutputChannel), there is the same problem. I added a commit to the example project to illustrate that https://gitlab.com/viktomas/test-source-maps-extension/-/commit/8b96d43efb5bf63ebe90dba77d255ab0f0be7ad0

I'm not too experienced with how VS Code handles source maps, but my guess is that this is the configuration of the extension host node process.

**Comment by weinand** [comment] 2021-12-06 09:35
VS Code does not handle source maps at all. Only the js-debug extension deals with source maps.

**Comment by viktomas-gitlab** [comment] 2021-12-06 10:12
@weinand Thank you for clarifying :pray: . I phrased my last paragraph badly. I don't think that VS Code itself implements source map resolution. However, I believe that node (starting with v14) can handle source maps if you configure it that way ([Source maps in Node.js](https://nodejs.medium.com/source-maps-in-node-js-482872b56116)). And maybe when VS Code starts the Extension Host process, it uses a different configuration with the `--disable-extensions` flag on or off.

**Comment by weinand** [comment] 2021-12-06 10:35
@viktomas-gitlab yes, we are on the same page - and that's the reason why I have removed the "debug" label: it is not a VS Code debugger issue but a node.js configuration issue.

**Comment by deepak1556** [comment] 2021-12-06 12:40
@alexdima , To clarify the flag `--disable-extensions` in our insiders/stable build will not be respected by the runtime because the component responsible for parsing that particular flag is disabled at build time.

Also https://gist.github.com/deepak1556/4243f85684fd77247a06ec62295b85d7 tests that source maps are respected in devtools with/without the `--disable-extensions` flag.

**Comment by alexdima** [comment] 2021-12-07 19:58
@viktomas-gitlab I'm trying to reproduce but unfortunately I never get sourcemaps for the tested extension. Even when commenting out `--disable-extensions` in the `launch.json`, sourcemaps never work for me:
<img width="1666" alt="Screen Shot 2021-12-07 at 20 54 16" src="https://user-images.githubusercontent.com/5047891/145097225-d506c399-72f1-4694-8bc0-558501399ea7.png">


I see them working in your video, but I don't understand what would be different on my machine. I do have source maps enabled in DevTools:

![image](https://user-images.githubusercontent.com/5047891/145097409-c5430943-d55a-4e1c-a829-004fd2c7bade.png)

@weinand @connor4312 given your extra insights regarding source maps, could you please also try to reproduce? Are source maps working for you? Why would they not be working for me?

**Comment by weinand** [comment] 2021-12-08 11:48
@alexdima I could not get sourcemaps to work for Chrome Devtools (with or without "--disable-extensions").

@viktomas-gitlab do we need to pass the "--enable-source-maps" option to node.js for this?
Since VS Code uses Electron's built-in Node.js, we have no simple way to pass command line options to the runtime.
 
BTW, VS Code's built-in debugger has no problems with finding and using sourcemaps...

**Comment by viktomas-gitlab** [comment] 2021-12-08 15:34
@weinand @alexdima I want to sincerely appologize for wasting your time. I've spent more time debugging the issue after both of you said that you can't reproduce it.

I found that when I disable all extensions manually (by clicking on disable) the sourcemaps don't work. 🤦 With binary halving I found out that the [vscodevim.vim extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) enables the source map support. Digging deeper, the vim extension enables it this way: https://github.com/VSCodeVim/Vim/blob/master/extension.ts#L18

Here is a video showing the difference:

https://user-images.githubusercontent.com/78416057/145235544-f42e9fec-66e2-4e85-9bda-d168cfa5fc6a.mp4

I tried it on multiple laptops before reporting, but my method of eliminating sideffects was incomplete and the `--disable-extensions` was just a symptom, not a cause. I even run the extension with the `code --disable-extensions .` to avoid some extension causing the issue, but the extensions got re-enabled when I triggered the development mode.

I'm sorry once more.

I really like the VS Code project and I appreciate that you offered me the support. This issue can be closed.

**Comment by weinand** [comment] 2021-12-08 16:04
@viktomas-gitlab no problem, now we've all learned a new trick of the vim extension ;-)

**Comment by alexdima** [comment] 2021-12-08 16:16
@viktomas-gitlab No worries, thank you for figuring it out! ❤️

**Closed by alexdima** 2021-12-08 16:16 UTC
Labels: needs more info
