### ISSUE TITLE
Incorrect format on paste for blank line inside js function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29896] opened 2017-06-29 22:58 UTC
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:07:31.424Z)
- OS Version: Darwin x64 16.6.0

---

Steps to Reproduce:

1. Enable format on paste
1. Copy the js code:

```js
function abc() {

}
abc
```

note that the blank line has no whitespace on it. It is empty

3. Paste the code into a blank js file

**Expected**
Retained formatting:

```js
function abc() {

}
abc
```

**Actual**
Code is indented

```js
function abc() {
  
  }
  abc
```

**Comment by rebornix** [comment] 2017-11-28 00:32
https://github.com/Microsoft/vscode/issues/36294, https://github.com/Microsoft/vscode/issues/29896, https://github.com/microsoft/vscode/issues/38833 share the same root cause: empty lines are not handled gracefully. I pushed a fix which makes this specific case work but it may not work for all cases ;)

**Closed by rebornix** 2017-11-28 00:32 UTC
Labels: bug, editor-autoindent, javascript
