### ISSUE TITLE
Automatic type acqusition for javascript projects not working anymore

### ISSUE THREAD

**Issue by twilson90** [microsoft/vscode#230581] opened 2024-10-05 11:39 UTC
Does this issue occur when all extensions are disabled?: Yes

Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

For the last week or so VSCode has stopped automatic type acqusition for javascript projects.

I have a folder %LOCALAPPDATA%\Microsoft\TypeScript\5.5\node_modules, whenever I installed a package from npm in any project,  vscode would automatically get the type definitions from the @types npm repo and store them here.

For the last week or so, there's a new directory in the TypeScript folder, 5.6.
This folder is empty except for a bare package.json.
Since the creation of that folder, and presumably a TypeScript version update, automatic type acquisition has stopped working entirely.
I've tried reinstalling vscode, uninstalling all addons, erasing all settings and deleting %Appdata%/Roaming/Code
Nothing works.
Really frustrating.
Please help!

[TypeScript.zip](https://github.com/user-attachments/files/17266014/TypeScript.zip)

**Comment by twilson90** [comment] 2024-10-05 11:51
Just rolled back to August 2024 (version 1.93) and the problem is not present.

**Comment by IllusionMH** [comment] 2024-10-07 05:23
May be related to https://github.com/microsoft/TypeScript/issues/60156
You can try to install TS 5.5 somewhere locally and point VS Code there. Should fix problem while fix is not released.

**Comment by kkocdko** [comment] 2024-10-08 02:06
also hit this bug in my machine

**Comment by kkocdko** [comment] 2024-10-10 17:13
this is fixed in 1.94.2 , consider close this issue?

**Comment by mjbvz** [comment] 2024-10-29 20:59
Duplicate of https://github.com/microsoft/TypeScript/issues/60156

**Closed by mjbvz** 2024-10-29 20:59 UTC
