### ISSUE TITLE
Can not move to trash on Gnome 3.30

### ISSUE THREAD

**Issue by charlesg99** [Microsoft/vscode#59350] opened 2018-09-25 15:18 UTC
On Arch Linux x64, gnome 3.30, when deleting a file and pressing "move to trash" the following message appears:

![image](https://user-images.githubusercontent.com/33044886/46024048-f6f91c80-c0b3-11e8-8b1f-f68936a6d65b.png)

Not sure if this is caused by vscode 1.27 or gnome 3.30 as I updated both at the same time, but deleted files were correctly moved to the trash on vscode 1.26 and gnome 3.28.

**Comment by isidorn** [comment] 2018-09-25 15:27
We did not change anything in that area in the latest release. So my bet would be gnome.
However we officialy do not support Arch Linux afaik so closing this
Also I would try to repro this issue using node and file an issue in their repository

**Comment by charlesg99** [comment] 2018-09-25 15:50
I think you were a bit fast to close this issue. If the problem is with gnome 3.30, you'll see this problem again [soon enough](https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseSchedule). Consider this as a head-ups then :)

**Comment by isidorn** [comment] 2018-09-25 16:01
Let's reopen and see if more users complain. Thanks for the heads up

**Comment by juliuswz** [comment] 2018-09-30 20:49
I can confirm the same behavior running XFCE on Arch Linux.
I think the issue is with `gvfs-trash` since it has been deprecated. Since `1.37.2`, gvfs completely removes support for `gvfs-trash`. 
The `gio trash` is used now.
Maybe a [Electron](https://github.com/electron/electron/pull/9518) issue?

**Comment by ccaspers** [comment] 2018-10-04 16:08
I had the same problem (running Arch with Gnome 3.30) and created the file `/usr/local/bin/gvfs-trash` with the following contents: 
````sh
#!/bin/sh
gio trash $@
````
After making it executable (`sudo chmod +x /usr/local/bin/gvfs-trash`), vscode was able to move my files to my trash folder.

**Comment by charlesg99** [comment] 2018-10-04 17:28
Thanks ccaspers! It works as a workaround, but I had to change the content of gvfs-trash to:
```
#!/bin/bash
/usr/bin/gio trash "$@"
```

**Comment by eli-schwartz** [comment] 2018-10-07 22:32
Since commenting on https://github.com/electron/electron/pull/9518 has not gotten anywhere, I've submitted a new bug report for electron: https://github.com/electron/electron/issues/15011

**Comment by David-Else** [comment] 2018-11-28 09:52
Fix works on Fedora 29, cheers!

**Comment by bpasero** [comment] 2019-01-25 16:31
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ccaspers** [comment] 2019-01-28 09:42
I removed my shim for gfvs-trash and can no longer reproduce the bug :tada:

- GNOME Shell 3.30.2
- vscode
  Version: 1.31.0-insider
  Commit: 1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c
  Date: 2019-01-28T06:14:17.311Z
  Electron: 3.1.2
  Chrome: 66.0.3359.181
  Node.js: 10.2.0
  V8: 6.6.346.32
  OS: Linux x64 4.20.3-zen2-1-zen

**Closed** 2019-01-28 10:02 UTC
Labels: electron, fixed-in-electron-3.0.x, linux, upstream
