### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by RaghunathSenthilnathan** [microsoft/vscode#139491] opened 2021-12-20 04:51 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:57011:22)
    at getPropertyOfType (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:57671:24)
    at resolveESModuleSymbol (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49817:54)
    at getTargetOfNamespaceImport (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49002:28)
    at getTargetOfAliasDeclaration (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49236:28)
    at resolveAlias (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49281:30)
    at getSymbol (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47838:38)
    at resolveNameHelper (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:48131:34)
    at resolveName (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:48114:20)
    at resolveEntityName (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49453:42)
    at getTargetOfExportSpecifier (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49193:17)
    at getTargetOfAliasDeclaration (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49243:28)
    at resolveAlias (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49281:30)
    at resolveSymbol (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:49271:67)
    at mergeSymbol (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47624:42)
    at c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47737:20)
    at mergeSymbol (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47648:21)
    at c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47739:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47737:20)
    at initializeTypeChecker (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:85010:21)
    at Object.createTypeChecker (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:47395:9)
    at Object.getTypeChecker (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:114404:79)
    at synchronizeHostData (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:159898:21)
    at Object.getProgram (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:160019:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:165033:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:164962:42)
    at ConfiguredProject.updateGraph (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:165955:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:167679:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:168762:44)
    at c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:170260:46)
    at c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (c:\Users\63700\Documents\cognito-integration\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.95GB free)|
|Process Argv|--crash-reporter-id dab14a98-0bfd-4f7f-9b9f-5f3ce42bf45b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.6.0
prettier-vscode|esb|9.0.0
ts-extension-pack|loi|0.3.0
vscode-language-babel|mgm|0.0.35
vscode-react-snippet|Nic|0.0.6
tsimporter|pmn|2.0.1
java|red|1.2.0
vscode-javascript-booster|sbu|14.0.1
sonarlint-vscode|Son|3.1.0
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.15
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.20.0
vscode-java-test|vsc|0.33.0
vscode-maven|vsc|0.34.1
beauty|yhp|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30405998
py55gd98:30411514
vscexrecpromp3t2:30407763

```

</details>

**Comment by aaliakseyenka** [comment] 2021-12-20 12:47
hey @mjbvz, any thoughts on that? I have same issue and seems tried everything to fix it locally, but with no success

**Comment by IllusionMH** [comment] 2021-12-21 09:21
/duplicate of https://github.com/microsoft/TypeScript/issues/47179

TS team needs a way to reproduce this issue. Please provide code that can help to reproduce this crash in issue linked above.

**Closed** 2021-12-21 09:21 UTC
Labels: *duplicate
