### ISSUE TITLE
The application freeze when i paste a regexp on the search field

### ISSUE THREAD

**Issue by emonto15** [Microsoft/vscode#56498] opened 2018-08-15 19:29 UTC
Issue Type: <b>Bug</b>

When I design a 23-term regexp on the editor and try to paste it on the search field to find matches, the application exits!

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.62GB (3.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
live-html-previewer|hdg|0.3.0

</details>

**Comment by roblourens** [comment] 2018-08-15 21:46
Sorry about that, if you can reproduce it, can you paste the regex here?

**Comment by roblourens** [comment] 2018-08-15 21:46
Was this in the search viewlet or the editor's ctrl+f find widget?

**Comment by kobi2187** [comment] 2018-08-18 08:39
I get similar freezes when the editor's ctrl+f widget is opened (the javascript regex)
in large files - thousands or tens of thousands lines.
it could be related to the instant update - when you edit the regex and new matches are highlighted in the text. perhaps while editing, everything matched, so it consumed a lot of memory? this is just a silly guess, I don't know what really happens there.

**Comment by rebornix** [comment] 2018-09-04 23:27
I have a feeling that it's a duplicate of https://github.com/Microsoft/vscode/issues/30874 . Close this in favor of https://github.com/Microsoft/vscode/issues/30874 and we can reopen if that's not the case.

**Closed by rebornix** 2018-09-04 23:27 UTC
Labels: editor, editor-find, needs more info
