### ISSUE TITLE
Update to 1.47.1  

### ISSUE THREAD

**Issue by JSchatral** [microsoft/vscode#102633] opened 2020-07-15 20:00 UTC
We have
Issue Type: <b>Bug</b>

Update 1.47.1 imported - after that our debug runtime environment for our node server no longer works
Error message:
Error: Cannot find module '"c: / Users / js / AppData / Local / Programs / Microsoft'
    at Function.Module._resolveFilename (internal / modules / cjs / loader.js: 636: 15)
Here is the launch config for starting debugging:
 {
      "name": "Dev Server ts-node-dev",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "cwd": "$ {workspaceRoot}",
      "runtimeExecutable": "$ {workspaceRoot} /node_modules/.bin/ts-node-dev",
      "args": [
        "$ {workspaceRoot} /src/server.ts"
      ],
      "restart": true,
      "env": {"AlanGoHome": "AlanGoHome", "NODE_ENV": "development"},
    },

We tried it twice (Hyper-V Client Restore) in both cases the same error occurs again..
What is going wrong? Thank you - Greeting from Germany  - J. Schatral

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
vscode-eslint|dba|2.1.7
emulate|Die|1.4.0
vscode-babel-coloring|dza|0.0.4
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.16.1
sass-indented|rob|1.5.1

</details>
 written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment] 2020-07-15 20:55
Looks like a duplicate of #102035 for which a fix is due shortly in 1.47.2.

https://github.com/microsoft/vscode/issues/102069#issuecomment-656610397 offers a possible workaround.

**Comment by connor4312** [comment] 2020-07-15 22:26
Indeed, see here for the fix (just ignore the electron part of it) https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666

/duplicate

**Closed** 2020-07-15 22:28 UTC
Labels: *duplicate, debug, new release

**Comment by connor4312** [comment] 2020-07-16 21:25
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
