### ISSUE TITLE
Open linked file from terminal in existing window

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#74451] opened 2019-05-28 09:41 UTC
Apologies if the title is unclear. Here's the situation:

1. Split the screen into three: a terminal, a JS module, and a JS test.

1. When the test fails, it reports 'error at line X in test.js' -- CTRL+click the link

1. The test is opened in a new tab of the module editor.

1. VSC now has open a terminal, and two tab-groups showing the test.

1. Would it be possible to check if a tab-group already open contains the file, and switch to that instead of opening another tab for it?

**Comment by Tyriar** [comment] 2019-05-31 01:54
I think it opens in the last active editor group, @bpasero probably a duplicate of one of your issues.

**Comment by bpasero** [comment] 2019-05-31 04:46
Try with setting `workbench.editor.revealIfOpen: true`

**Closed by bpasero** 2019-05-31 04:46 UTC
