### ISSUE TITLE
Wording: "Show Tunnels View"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107905] opened 2020-10-01 17:00 UTC
* follow steps of https://github.com/microsoft/vscode/issues/107904
* I think the working "Show Tunnels View" is confusing, esp since the actual view then talks about ports

**Comment by alexr00** [comment] 2020-10-02 08:14
Fixed 10 days ago, duplicate of https://github.com/microsoft/vscode-remote-release/issues/3710

**Closed by alexr00** 2020-10-02 08:14 UTC
