### ISSUE TITLE
Settings sync fails with the code 431

### ISSUE THREAD

**Issue by wboleksii** [microsoft/vscode#104495] opened 2020-08-12 14:08 UTC
Version: 1.48.0-insider (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-11T23:21:50.282Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Log in into MS account
2. Try syncing settings

```
[2020-08-12 09:04:51.286] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-12 09:04:51.286] [userDataSync] [info] Auto Sync is disabled.
[2020-08-12 09:11:34.298] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":431,"execution-id":"5a7fb20e-ec1c-4f4d-a2d8-49c464dbfa90"}

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment] 2020-08-14 15:26
Did this not come with a notification? This means what you're trying to sync was too large.

**Comment by wboleksii** [comment] 2020-08-14 15:33
@Tyriar what notification? I don't really have much to sync, just a few addons.

**Comment by sandy081** [comment] 2020-08-17 11:05
@Tyriar `431` is sent when request header is too large not with payload. We do not show any notification for `431`. 

Seems related to auth - https://github.com/microsoft/vscode/issues/92705

**Comment by RMacfarlane** [comment] 2020-08-17 22:16
This looks like a duplicate of the issue you linked, #92705

**Closed by RMacfarlane** 2020-08-17 22:16 UTC
