### ISSUE TITLE
Unlocalized `Tasks` string

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4750] opened 2016-03-29 14:35 UTC
![image](https://cloud.githubusercontent.com/assets/22350/14111729/22735afc-f5cc-11e5-87f5-079df57618cb.png)

Flagging `important` just to catch your attention.

**Comment by dbaeumer** [comment] 2016-03-29 15:06
@bpasero if I localize this and a user switches between English and German what will happen with the drop down. Will we have two entries one with Tasks and one with 'Aufgabe'. Would we need an Id and a label for a output channel.

**Comment by bpasero** [comment] 2016-03-29 15:19
@dbaeumer yes this would require an additional identifier next to the label for a channel which I think would make sense but is a larger change, not a one liner.

**Comment by bpasero** [comment] 2016-03-29 15:23
@dbaeumer actually I just tested this: I switched to "Tasks", then shutdown and renamed this to "Aufgaben" and started up again. I lost my last selected output channel, but there are no duplicate entries in the list.

@isidorn can you confirm that we are not using the stored output channel name otherwise?

If so, I think we could just translate the output channel names too.

**Comment by grazies** [comment] 2016-03-29 15:26
Sent using CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.9.8&pv=9.2.1&source=email_footer_2>

**Comment by isidorn** [comment] 2016-03-29 15:35
@bpasero just checked code, once there is new output the active channel will be set to that, however if there is no output comming the active channel can be in a broken state read out from the storage service (e.g. "Aufgaben"). In that case we use the wrong identifier in a lot of places. Just find all references in `outputServices.getActiveChannel()`
Not sure if this breaks anything though.

**Comment by bpasero** [comment] 2016-03-29 15:36
Right. I would think having identifier + label is a cleaner solution anyway.

**Comment by isidorn** [comment] 2016-03-29 16:05
Yup I can add the identifier.

**Comment by bpasero** [comment] 2016-03-29 16:36
I also think this is not a candidate.

**Comment by dbaeumer** [comment] 2016-03-30 07:50
@bpasero I marked it as a candidate to translate the string.

@bpasero & @isidorn what is your advice. What is the harm caused by translating it. It is not clear to me from the last comments.

**Comment by isidorn** [comment] 2016-03-30 08:34
@dbaeumer the potential harm by translating this is that we use that label as the id we store for the active channel. There might be some consequences before the first input of some channel comes to the user.
All in all if you decide to translate this and ship as part of 1.0 please test that nothing gets broken in output switching by starting vscode in one language and then starting it in another language

Also try on a workspace with no git source control.

**Comment by bpasero** [comment] 2016-03-30 08:47
From the screen shot it looks that one channel was already translated (the "Extensions" output channel)? So we already ship with this, I suggest to translate them all (including the "Git" one).

**Comment by dbaeumer** [comment] 2016-03-30 08:53
Talked to @egamma  and decided not to translate those for 1.0 since we don't understand the consequences. 

Opened #4794

**Comment by dbaeumer** [comment] 2016-04-19 12:12
Got addressed by @isidorn refactoring around output channels.

**Closed by dbaeumer** 2016-04-19 12:12 UTC
Labels: bug, i18n
