### ISSUE TITLE
Extension recommendation for .git files appearing when no .git file is opened

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#86427] opened 2019-12-05 21:17 UTC
Issue Type: <b>Bug</b>

- Open any git repo in VS Code
- Open any file in the repo

I get the below prompt:

![image](https://user-images.githubusercontent.com/16890566/70274658-6612dc00-1761-11ea-986a-b0d1247fe9fe.png)

One would expect this prompt if a `.git` file was manually opened in the editor and no VS Code extension was installed that could serve .git files. But in my case, no such file was opened.

VS Code version: Code - Insiders 1.41.0-insider (bbf00d8ea6aa7e825ca3393364d746fe401d3299, 2019-12-05T06:56:28.532Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Wowol** [comment] 2019-12-09 23:39
I could reproduce, let me look at it and I will try to make a PR soon :)

**Comment by joaomoreno** [comment] 2019-12-10 11:52
Great catch, this will go into candidate.

**Comment by chrmarti** [comment] 2019-12-10 15:06
Reopening, the PR is not merged yet.

**Comment by sandy081** [comment] 2019-12-10 16:08
Follow up issue - https://github.com/microsoft/vscode/issues/86676

**Closed** 2019-12-10 16:07 UTC
Labels: bug, candidate, git

**Comment by Wowol** [comment] 2019-12-10 16:09
What about [this](https://github.com/microsoft/vscode/commit/794330fb6b56311876daf9dce386e7859782030a) commit into master? Do we want it to stay there?

**Comment by sandy081** [comment] 2019-12-10 16:09
Steps to verify:

- Start with fresh user data and extensions dir
- Open any git repo
- Open any file in the repo
- Make sure recommendations pop up for `.git` files is **not** shown

**Comment by sandy081** [comment] 2019-12-10 16:10
> What about [this](https://github.com/microsoft/vscode/commit/794330fb6b56311876daf9dce386e7859782030a) commit into master? Do we want it to stay there? 

No, I will merge into master also because this impacts our insiders.
