### ISSUE TITLE
launch.json environment variables not being passed to Python scripts

### ISSUE THREAD

**Issue by duncanw** [microsoft/vscode#78979] opened 2019-08-12 18:55 UTC
This is an intermittent issue so not sure how easy it will be to reproduce. In my launch.json I have: 
```
"configurations": [
        {
            "name": "Python: current jobs",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/beany/beany/util/reporting/weeklywip.py",
            "console": "integratedTerminal",
            "env" : {
                "SANDBOX" : 1
            }    
        }
]
```

When debugging this, sometimes the command line includes the SANDBOX environment variable:
```
PS D:\workspace\vscode> cd 'd:\workspace\vscode'; ${env:SANDBOX}='1'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'd:\workspace\vscode\beany\env\Scripts\python.exe' 'c:\Users\dunca\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '50043' 'D:\workspace\vscode/beany/beany/util/reporting/weeklywip.py'
```

...but sometimes it doesn't, and the environment variable isn't available to the script:
```
PS D:\workspace\vscode> & 'd:\workspace\vscode\beany\env\Scripts\python.exe' 'c:\Users\dunca\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '50035' 'D:\workspace\vscode/beany/beany/util/reporting/weeklywip.py'
```
If I edit and save weeklywip.py before running it seems more likely to include the environment variable as desired, but I haven't figured out a clear pattern. This only started happening since Visual Studio Code updated to version 1.37.0 on 2019-08-08.

OS: Windows 10
Python version: 2.7.13

**Comment by isidorn** [comment] 2019-08-13 09:03
Potentially duplicate of https://github.com/microsoft/vscode/issues/77119

**Comment by weinand** [comment] 2019-08-13 09:42
This unrelated to #77119.

**Closed** 2019-08-13 09:43 UTC
Labels: *caused-by-extension
