### ISSUE TITLE
Python interactive doesn't working in visual studio code

### ISSUE THREAD

**Issue by FelipeAmaral13** [microsoft/vscode#100980] opened 2020-06-24 19:43 UTC
- VSCode Version: 1.47.0
- OS Version: Windows 10

Steps to Reproduce:

1. Select the python code in your program.
2. Press Shift+enter

Expected behavior:

1. Open a new window in VSC and execute that python code, like a jupyter cell.

Actual behavior:

1. New window opens, but nothing happens.

![Capturar](https://user-images.githubusercontent.com/5797933/85620152-c3a54200-b639-11ea-8f3a-7a216c822946.PNG)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment] 2020-06-25 02:36
Duplicate of #100879

**Closed by mjbvz** 2020-06-25 02:36 UTC

**Comment by storopoli** [comment] 2020-06-25 15:35
I don't think is a duplicate of #100879 because it has nothing to do with markdown, it fails to create a connection to Jupyter and execute a cell.
