### ISSUE TITLE
Emmet: Keep suggested href on Enter when using 'Wrap with Abbreviation'

### ISSUE THREAD

**Issue by ajaykarwal** [microsoft/vscode#69829] opened 2019-03-05 09:33 UTC
When you wrap an email address or URL with an anchor using 'Wrap with Abbreviation", it shows a preview of suggested href but hitting enter removes it.

There should an option to accept the suggested href (perhaps via cmd+enter).

Originally posted this on twitter - https://twitter.com/ajaykarwal/status/1094915554203389959
Here's a larger version of the video - https://video.twimg.com/tweet_video/DzHrTCvW0AYGtto.mp4

**Comment by sbatten** [comment] 2020-09-04 16:05
duplicate of #54711

**Closed by sbatten** 2020-09-04 16:05 UTC
Labels: bug, emmet
