### ISSUE TITLE
No "entity.name.function-call" scope under "editor.tokenColorCustomizations" in settings.json

### ISSUE THREAD

**Issue by nidongde10086** [microsoft/vscode#93456] opened 2020-03-26 04:22 UTC
- VSCode Version: 1.43.2
- OS Version: Windows 10 1909

Steps to Reproduce:

1. In settings.json, add "editor.tokenColorCustomizations": { "textMateRules": [ { "scope": "entity.name.function-call", "settings": { ... } } ] }
2. Save json file, nothing changed in theme.

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment] 2020-03-26 19:10
What is the input file?
You can use the `Developer: Inspect Editor Tokens and Scopes` command to find out more what scopes are used.

**Comment by nidongde10086** [comment] 2020-03-27 02:59
Hi aeschli,

Thanks for the command! I was able to find out that is going on.
I am using One Monokai theme and would like to tweak it a little bit. I saw in their github that they were using "entity.name.function-call" to color function calls, then I tried that and ended up here.

After inspect I found it is actually "meta.function-call.generic". I tried "meta.function-call" from code suggestion which does not tell me there is a "generic" attribute and it colored parentheses after functions as well, so I thought it was the wrong one.

**Comment by aeschli** [comment] 2020-03-27 08:16
We have code assist for some of the common scopes, but unfortunately TextMate scopes are not standardized and diverge significantly per language. We consider customizing textMateRules as an expert feature. We have a set of  a simplified categories, such as `comments` and `functions`. Does `functions` not work for you?

**Comment by aeschli** [comment] 2020-03-27 08:51
Closing the issue as it's not a bug in VSCode

**Closed by aeschli** 2020-03-27 08:51 UTC
Labels: needs more info, new release
