### ISSUE TITLE
Extensions with console-like behavior

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#1222] opened 2015-12-12 20:09 UTC
Currently with the extensions API, we have access to output channels (creation and access through `vscode.window.createOutputChannel()`).  And likewise, we can get adhoc user input through `vscode.window.showInputBox`.

I think what would be really helpful is if the extensions API included the capability to have a console-like experience, much like the **debug console** has (input part of the experience with the output).  Not necessarily for "debugging" purposes, but for a more consistent and extended user experience exchange for ongoing for **user input creation**, then **VS Code output consumption**, followed by more **user input creation**, ... so on and so forth.

At the moment, the `showInputBox()` functionality with the output channel can seem like a one-time exchange, without the continuity of a input/output console (like the debugger console).

**Comment by daviwil** [comment] 2016-01-05 22:34
Here's an earlier issue filed for the same feature request: https://github.com/Microsoft/vscode/issues/1222

**Comment by jrieken** [comment] 2016-04-29 10:33
closing as duplicate of #547

**Closed by jrieken** 2016-04-29 10:33 UTC
Labels: api, feature-request
