### ISSUE TITLE
Explorer display gets corrupted when 'New File' input field scrolls out of display.

### ISSUE THREAD

**Issue by happou31** [Microsoft/vscode#41592] opened 2018-01-14 08:48 UTC
- VSCode Version:  
```
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T16:16:25.767Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```
- OS Version:  Windows 10 Home ver1709 Build 16299.125

Steps to Reproduce:

1. Right click in Explorer, open 'New File' or 'New Folder' input field.
1. Scroll up or down until input field out of display.
1. The input field closes.
1. Then after that, unexpected behavior of the directory tree and file list scrolling.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment] 2018-01-15 09:17
Duplicate of https://github.com/Microsoft/vscode/issues/22269

**Closed by isidorn** 2018-01-15 09:17 UTC
