### ISSUE TITLE
Extensions break Intellisence in large multi-project folders (64bit version, TypeScript 2.5)

### ISSUE THREAD

**Issue by amos-ortal** [Microsoft/vscode#34413] opened 2017-09-15 00:11 UTC
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87rb25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.1.0
vscode-generate-getter-setter|DSK|0.4.2
tslint|eg2|1.0.6
prettier-vscode|esb|0.23.1
code-runner|for|0.7.1
vscode-react-typescript|inf|1.0.8
docthis|joe|0.4.8
PowerShell|ms-|1.4.3
typescript-javascript-grammar|ms-|0.0.23
javascript-typescript|sou|0.0.4
code-spell-checker|str|1.3.9
comment-snippets|Tob|0.2.0

IntelliSense and type navigation for both basic type (e.g. Array, Number, String) and project specific types (interface Foo1) simply doesn't work in large projects.
This is especially apparent in multi-project folders .
We use rush (https://github.com/Microsoft/web-build-tools/blob/master/apps/rush/README.md) to manage a large repo with multiple projects.
If I open code on a single projects IntelliSense and type navigation works, however if I open in the root both operations becomes so slow they are virtually broken.

Reproduces without extensions: No

**Comment by mjbvz** [comment] 2017-09-15 00:31
So if you disable all extensions, you don't see this issue? You have a few JS/TS extensions installed that could be causing this

**Comment by amos-ortal** [comment] 2017-09-15 00:46
Played with it a bit and it seems that they are causing the problem.
Vscode should probably detect extensions with bad performance and flag them to the user, otherwise it seems like vscode issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mjbvz** [comment] 2017-09-15 03:15
Ok, closing this as caused by extension

I agree it is currently difficult to determine if vscode or an extension is the root cause of issues like this. We are looking into ways to let users know when an extension is misbehaving

**Closed by mjbvz** 2017-09-15 03:15 UTC
Labels: caused-by-extension, needs more info, new release, typescript

**Comment by amos-ortal** [comment] 2017-09-15 05:24
👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
