### ISSUE TITLE
ID don't show in CSS file 

### ISSUE THREAD

**Issue by adonikh** [Microsoft/vscode#45898] opened 2018-03-15 18:25 UTC
Hello everyone, this is my first post here so I'm kinda new on how to give all details about my issue. 
So I tried disabling all extensions I have to try it out but still doesn't work. I noticed that the first few seconds it does work and show me the names of all my ID and classes, but then it just stop working.
The extensions installed are : 
   - [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)
   - [IntelliSense for CSS class names in HTML](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)
 And others but that has nothing to do with css or html. 

![2018-03-15_1849544](https://user-images.githubusercontent.com/31285702/37483288-2d59e2a8-2886-11e8-8e05-924f4a938d0a.gif)

As you can see I've also already used an ID, but it just don't show, class work normally. 

Thank you all in advance!
And sorry if that was posted already.

- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Created ID do not show when I press Crlt+Space, but shows the class.

Does this issue occur when all extensions are disabled?: Yes

**Comment by adonikh** [comment] 2018-03-15 18:41
This is an other gif to show that it does work for few seconds and then it just put "no suggestions" 
![2018-03-15_1936175](https://user-images.githubusercontent.com/31285702/37484308-74f417e4-2888-11e8-8cab-9d55927921cc.gif)
![2018-03-15_193617-1](https://user-images.githubusercontent.com/31285702/37484405-b094f2dc-2888-11e8-9148-d0d6cfb5830d.png)

**Comment by aeschli** [comment] 2018-03-16 06:52
duplicate of #43365

**Closed by aeschli** 2018-03-16 06:52 UTC
Labels: css-less-sass
