### ISSUE TITLE
Unhappy editor-state while loading a slow file

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#34697] opened 2017-09-20 13:40 UTC
* open a file from disk
* open a file that is slow to load (because it is huge or because it loads from a remote source)
* 🐛  the (tab-)title updates, the editor still shows the old content

**Comment by bpasero** [comment] 2017-09-20 13:57
Yeah this is a bit tricky, I do not want to always null out the editor model on each tab open because that results in flicker. Though maybe we should timeout after certain ms and set the model to null if it is slow to load (e.g. when the progress kicks in).

**Comment by bpasero** [comment] 2018-01-08 17:21
**Another case:**
* have 2 files open that are slow loading
* scroll both to the end (the second being much longer)
* jump to second editor and then quickly back to first

=> the second editor will wrongly save the view state of the first editor because the model has not changed yet (as reported in https://github.com/Microsoft/vscode/issues/40114).

**Comment by akbyrd** [comment] 2018-01-08 17:27
Note on the 'slow loading' condition:

I regularly repro this while working on 200 line files on an NVMe SSD.

**Comment by bpasero** [comment] 2018-01-09 10:20
@akbyrd I think I can fix your issue without requiring the fix for this one.

**Comment by gjsjohnmurray** [comment] 2021-11-12 16:07
> 
> 
> Yeah this is a bit tricky, I do not want to always null out the editor model on each tab open because that results in flicker. Though maybe we should timeout after certain ms and set the model to null if it is slow to load (e.g. when the progress kicks in).

@bpasero if you aren't able to address this in the current iteration but are willing to consider a PR from me, a pointer would be welcome and I'll have a go.

**Comment by bpasero** [comment] 2021-11-12 16:23
I am actually not so concerned about the change to do this but rather the consequences. Yes, the current way it works is not ideal for this case of a slow loading file but it is actually very well suited for files that load fast which is happening in most cases. The switch from one file model to the next is without a `null` model (= flicker) in between. 

A fix would probably involve some kind of timeout that `null`s out the text editor model after some time if the new file cannot be resolved quickly enough and then visually you would see an empty text editor.

What was your idea how to fix it?

**Comment by gjsjohnmurray** [comment] 2021-11-12 17:40
That was my idea exactly.

**Comment by bpasero** [comment] 2021-11-13 06:56
Yeah if you want to start a PR, feel free. I cannot make promises as when I get to it though, typically that is only during issue grooming iterations.

**Comment by bpasero** [comment] 2021-11-21 13:07
More thinking about it, I feel that anything but calling `clearInput` before `setInput` when the input changes would be wrong because we would force every editor to adopt this. 

I have pushed https://github.com/microsoft/vscode/commit/2e636ded90fd03c8fbcd0553f550325c01cbcc60 with a setting to turn this off in case there are regressions. 

For text editors this means, every time `setInput` is called, the model in the text editor is first set to `null`.

**Comment by gjsjohnmurray** [comment] 2021-11-22 10:26
@bpasero many thanks for doing this. Today's Insiders is behaving so much better with my slow FileSystemProvider.

Only glitch I have seen so far is a minor one affecting the Outline pane. Using the modded fsprovider-sample I gave in #137057 here's how it behaves:

![junk](https://user-images.githubusercontent.com/6726799/142844252-824aa2f8-6957-4d51-9a08-6d297f1c78fe.gif)

Notice how when the second tab appear (now without continuing to display the editor from the first tab :+1: ) the Outline pane clears (good) but its message still mentions the file whose outline it previously showed (the one belonging to the first tab).

When the slow read of file contents for the second tab completes, the Outline updates correctly to show its outline. If I open one that can't produce an outline (e.g. file.txt) the message updates to show the correct filename.

**Comment by bpasero** [comment] 2021-11-22 10:31
Thanks for testing this. I am not sure how the outline decides to update but the editor change event for the active editor changing is very likely only firing after the editor has finished loading so that interested parties have a consistent picture to work with and not a partially loaded editor.

**Closed** 2021-11-22 10:32 UTC
Labels: bug, remote, workbench-editors
