### ISSUE TITLE
Terminal in an Column

### ISSUE THREAD

**Issue by mariosffx** [microsoft/vscode#111906] opened 2020-12-04 18:23 UTC
Is it possible to make the terminal be a column?
This will be especially useful for Ultra Wide Monitors
For example:
![Code_201204_453](https://user-images.githubusercontent.com/42849343/101200165-97710100-366e-11eb-85cc-4f5a2b1df89a.png)

**Comment by meganrogge** [comment] 2020-12-04 19:24
Duplicate of #10546

**Closed by meganrogge** 2020-12-04 19:24 UTC
Labels: feature-request, integrated-terminal
