### ISSUE TITLE
Emmet tab-key not working

### ISSUE THREAD

**Issue by setuun** [Microsoft/vscode#18445] opened 2017-01-12 11:31 UTC
As soon as i activate emmet...
`  { "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                      "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus" }
`
...the tab-key stop working.

Here a small video, where u can see, what i do and which expansions i use:
https://youtu.be/RDxf_KdAMRU

> Note: I use windows 10, VSCode 1.8.1 portable

**Comment by ramya-rao-a** [comment] 2017-01-12 19:44
Can you check your settings to ensure `emmet.triggerExpansionOnTab` is not set to false?

When you have the cursor at the end of the abbreviation does running the command `Emmet: Expand Abbreviation` from the command pallete work for you?

**Comment by setuun** [comment] 2017-01-13 09:32
`emmet.triggerExpansionOnTab` is enabled (true). When i run the command `Emmet: Expand Abbreviation`, an unknown error appears and it says, there are more details in the log, but i could not find the lod. Where is it?

**Comment by ramya-rao-a** [comment] 2017-01-13 18:39
Can you add a screenshot of the error that you see which says "more details in the log"?
It might refer to the console or something else.

**Comment by ramya-rao-a** [comment] 2017-01-23 00:42
@setuun Any updates?

**Comment by setuun** [comment] 2017-01-24 08:35
Sorry for my late response, but i was sick. After i started the portable version on another pc, the emmet suddenly is working again. I try to reproduce the error again. When i get it, i will immediately post it here.

**Comment by ramya-rao-a** [comment] 2017-01-24 17:48
Sorry to hear that, hope you feel better.
Closing this issue for now.
Do get back to us if you see any more issues

**Closed by ramya-rao-a** 2017-01-24 17:48 UTC
Labels: emmet, needs more info

**Comment by chrisdothtml** [comment] 2017-05-27 21:40
@ramya-rao-a I'm also getting this issue. `emmet.triggerExpansionOnTab` is enabled, but tab key just inserts a tab into the editor. Running `Emmet: Expand Abbreviation` expands as expected.

---

**OS**: macOS Sierra v10.12.5
**vscode**:  v1.13.0-insider

**Comment by chrisdothtml** [comment] 2017-05-27 22:21
Looks like the `emmet.suggestExpandedAbbreviation` setting was removed from the default settings in my version, and the emmet tab keybinding references it in its conditional:

```
{
  "key": "tab",
  "command": "editor.emmet.action.expandAbbreviation",
  "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !config.emmet.suggestExpandedAbbreviation && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus"
}
```

I removed `&& !config.emmet.suggestExpandedAbbreviation` from that keybinding and tab started working again:

```
{
  "key": "tab",
  "command": "editor.emmet.action.expandAbbreviation",
  "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus"
}
```

**Comment by ramya-rao-a** [comment] 2017-05-28 05:46
@chrisdothtml what is the date on your insiders? I had fixed this on Thursday (25th May) https://github.com/Microsoft/vscode/commit/92be0f0723b79f984bf5ad2102fb9dcd074ab894

**Comment by chrisdothtml** [comment] 2017-05-28 07:37
@ramya-rao-a 

> 2017-05-25T05:03:42.642Z

No updates available

**Comment by ramya-rao-a** [comment] 2017-05-29 02:27
Ah, The time zone difference. My fix should have been picked up for the Friday 26th. Looks like there was no build out then. There will be one on Monday. Can you check again then?

**Comment by chrisdothtml** [comment] 2017-05-29 19:53
Yep, got the update. It's fixed in the default keybindings now 👍

**Comment by ramya-rao-a** [comment] 2017-05-30 17:10
Thanks @chrisdothtml for reporting this.

**Comment by vinaydate** [comment] 2017-08-04 11:54
My project is in ReasonML. I have configured settings like:
```
"emmet.includeLanguages": {
    "ocaml": "html",
    "reason": "html"
  }
"emmet.useNewEmmet": false,
```

I can use _tab_ to expand tags in _jsx_ file but not in Reason _.re_ file. _Tab_ is treated to move cursor ahead.

**Comment by ramya-rao-a** [comment] 2017-08-04 12:59
@vinaydate 

`emmet.includeLanguages` is a new setting used when `emmet.useNewEmmet` is set to `true`.
Any reason you have set `emmet.useNewEmmet` to `false`?

**Comment by vinaydate** [comment] 2017-08-04 13:24
Somewhere else I read that _useNewEmmet_  being _true_ makes _tab_ key not to work. So I made it clear that the setting is so (which is the default value, and I did not change that).

Now the next scenario is:

```
"emmet.includeLanguages": {
    "ocaml": "html",
    "reason": "html"
  },
  "emmet.useNewEmmet": true,
  "emmet.showExpandedAbbreviation": "always"
```
These settings make me at least `ctrl-space` at the _tag_ and get suggestion, which when clicked, expands the _tag_ in .re file. Still in this lates scenario, _tab_ does not work

**Comment by ramya-rao-a** [comment] 2017-08-04 20:18
Do you have `editor.quickSuggestions` turned off? If not, then you should be able to get emmet suggestions without pressing `ctrl+space` explicitly

We are deprecating the "expand emmet on tab" feature. Please read https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list to know more about why we are doing this.

A workaround is to use the suggestion list or bind a new keyboard shortcut for the emmet expand command `editor.emmet.action.expandAbbreviation`

**Comment by vinaydate** [comment] 2017-08-05 07:32
```editor.quickSuggestions``` settings have default values
```
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
```
And not getting suggestion in` .re` files **unlike**` .js` files

And, I will bind a new keyboard shortcut.

Thanks :)

**Comment by ramya-rao-a** [comment] 2017-08-06 02:15
@vinaydate Great, Happy Coding!

**Comment by Jujunol** [comment] 2017-08-22 14:48
Just got the newest update yesterday and now experiencing this bug.
When I remove `config.emmet.triggerExpansionOnTab &&` in the `when` clause everything works.

**Comment by ramya-rao-a** [comment] 2017-08-22 15:36
@Jujunol Have you set `emmet.triggerExpansionOnTab` to true?

**Comment by bowtiebeej** [comment] 2017-08-28 03:16
Why was the default emmet.triggerExpansionOnTab changed to false? I've been using it since it first came out and it's always defaulted to true. This has caused no end of frustration this evening.

**Comment by ramya-rao-a** [comment] 2017-08-28 04:08
@bowtiebeej You can read about the why's and the how's in the [Release Notes for 1.15](https://code.visualstudio.com/updates/v1_15#_emmet-20) or the  [Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

For current state of affairs with Emmet in VS Code read the new docs page we have set up at https://code.visualstudio.com/docs/editor/emmet

**Comment by Jujunol** [comment] 2017-08-30 19:15
@ramya-rao-a Thanks for the suggestion. I just switched to Sublime Text and installed the emmet extension. Pretty much the same key shortcuts so it's a fantastic alternative!

**Comment by atilkan** [comment] 2017-09-01 14:22
Default emmet setting is false.
"emmet.triggerExpansionOnTab": false,

**Comment by bowtiebeej** [comment] 2017-09-08 03:51
So a bit of a new problem I have the emmet.triggerExpansionOnTab set to true but sometimes when I have content in the {} it throws an error "Failed to expand abbreviation". This has happened a few times, it's not consistent or at least not that I can find. It usually happens when I past information into the {} in something like a p{}. But it doesn't always error and if I do p{} with nothing in the {} it works.

**Comment by ramya-rao-a** [comment] 2017-09-08 07:00
@bowtiebeej even if you can share the contents inside the `{}` that causes the error, that can help. If you do find it, then please log a new issue and I can look into it

**Comment by bowtiebeej** [comment] 2017-09-08 14:40
Is there a limit on how much can be in the {}? That might the issue. I didn't look at it from that perspective. It's rather large but I can post it. When I copied smaller amounts of text it has worked.

**Comment by ramya-rao-a** [comment] 2017-09-08 16:43
Are you able to repro it consistently with the large text?

**Comment by bowtiebeej** [comment] 2017-09-08 17:55
Yes, though I didn't think about that being the cause at the time so I didn't test to find out how large the text amount needed to be. I'll test again when I get home tonight and let you know. Should I log a new issue or report that here?

**Comment by ramya-rao-a** [comment] 2017-09-08 19:17
Log a new one
