### ISSUE TITLE
ENOENT: no such file or directory, lstat '/snap/code'

### ISSUE THREAD

**Issue by 02infiinity** [Microsoft/vscode#65217] opened 2018-12-17 16:08 UTC
Issue Type: <b>Bug</b>

ENOENT: no such file or directory, lstat '/snap/code'

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.18.0-12-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-3330MX APU with Radeon(tm) HD Graphics (2 x 828)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 2, 2|
|Memory (System)|3.34GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
prettier-vscode|esb|1.7.2
dart-import|lua|0.1.0
ayu|tea|0.17.0

</details>

**Comment by mjbvz** [comment] 2018-12-17 19:17
Duplicate of #65095

**Closed by mjbvz** 2018-12-17 19:17 UTC
