### ISSUE TITLE
Picking a suggestion with Enter introduces a new line

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24420] opened 2017-04-10 09:25 UTC
![kapture 2017-04-10 at 11 24 05](https://cloud.githubusercontent.com/assets/22350/24854915/4a24efc4-1de0-11e7-9618-86bf0023dbf3.gif)

**Comment by jrieken** [comment] 2017-04-10 09:27
Yes, that is on purpose and a new feature. When the selected suggestion isn't making a textual change Enter inserts a newline, not accepting and doing nothing

**Comment by jrieken** [comment] 2017-04-10 09:28
See https://github.com/Microsoft/vscode/issues/15702 and https://github.com/Microsoft/vscode/issues/11944

**Comment by joaomoreno** [comment] 2017-04-10 11:55
Well, the real fix for #15702 is to introduce a `neverSuggestFullSuggestion` setting.

And #11944 makes sense because it refers to the repl. You said it perfectly:

> Surely this isn't a default for the normal text editor

**Comment by jrieken** [comment] 2017-04-10 11:57
We have discussed this in last weeks standup and came to this. Feel free to bring it up again.

**Comment by neilsustc** [comment] 2017-04-18 08:22
🙌 can't agree more with @joaomoreno.

And it would be great to have a setting for this.

**Comment by seancheung** [comment] 2017-05-07 06:33
Same here. This seems to be annoying as I always have to DELETE the line-break character to continue typing here and there. For me it's not a feature but a nightmare... There should be a setting or something to disable this.

**Comment by neilsustc** [comment] 2017-05-07 08:20
Could you please reopen this as a feature request (which is providing a setting to choose the behavior)?

**Comment by songtm** [comment] 2017-05-08 08:36
1. I get used to using "enter" key to accept a suggestion, but this feature lets me think If I should press a "space" or "enter".It's hard to recognize if I'm not making a textual change.
2. There are two ways to accept a suggestion, use "tab" or "enter".But right now when the suggestion list appears the "tab" key has one meaning(accept suggestion) while the "enter" key has 2(accept or new line).It is inconsistent.
3.I think It's very unusual to insert a new line when the suggestion list appears. If there are a few people need this unusual feature, I think you should give them an option without touch the existing working ones.

**Comment by Thaina** [comment] 2017-05-10 05:37
This should be reopened. The behaviour might not be good for some people. But it also expectation of previous behaviour some other people (like me) too

In short this is breaking change in behaviour and it should add more setting to control it instead of just silently changed

I was always using enter to accept suggestion. It make me feel natural to close suggestion box with enter by default

And actually people who would go as far as setting `acceptSuggestionOnEnter` to true would not mind another setting to switch

On the other hand people who felt that they got stolen `Enter` key by suggestion box should not set `acceptSuggestionOnEnter` to true from the first place

To tell you true. Enter to close suggestion box would making newline is really annoying

**Comment by Thaina** [comment] 2017-05-10 05:39
@jrieken Seriously you should stop closing all issue of this behaviour

THIS IS SERIOUSLY A BUG AND IT NOT SOLVED FOR MONTH

**Comment by Thaina** [comment] 2017-05-10 05:44
@joaomoreno The problem is sometimes we have many words that start with the same word

```C#
var a = "";
var a0 = "0";
```

Should we just close suggestion box for `a` because it actually is complete word or not?

**Comment by jrieken** [comment] 2017-05-10 08:33
Yes, we close all duplicates of this issue to have one central place for a mature and insightful discussion. I don't think having one place for a discussion is a bad thing.

@Thaina You (as everyone else) is invited to join this discussion. We constantly look at feedback and make our decisions based on that. Indeed that's the reason we made this change in the first place. So far around 5 people have complained about this change, some more and some less emotional. 

Again: The motivation for this change is that 24x7 IntelliSense aggressively shows and that users complained about Enter being 'stolen'. Therefore we made a change that 'Enter' inserts a new line when: (1) suggestions have been triggered just by typing (not 24x7 IntelliSense, not by a trigger character) and (2) when the suggestion doesn't change text already typed (is not a snippet, has no command nor additional text edits). We think it was defensive enough. Also, this is just a keybinding configuration which can be changed. 

Next steps: 
* Think about yet another setting ala 'enter is enter when suggest does nothing'
* Teach people how to customise their keybindings (see below)


To re-store the old enter behaviour add this to your `keybindings.json`

```json
{
  "key": "enter",
  "command": "acceptSelectedSuggestion",
  "when": "editorTextFocus && suggestWidgetVisible"
}
```

**Comment by Thaina** [comment] 2017-05-10 08:42
@jrieken If you decide that this issue would be a place to track but you don't open it then everyone who got this problem will come and cannot find open issue about their problem so they would create new duplicate issue again and again

And it was the evidence that you really shove it under the rug by keep mentioning the closed issue while closing the newer reported issue. I got emotional not because the changed but because this behaviour

**Comment by jrieken** [comment] 2017-05-10 08:54
Reopening to collect feedback on the workaround below: 

To re-store the old enter behaviour add this to your `keybindings.json`

```json
{
  "key": "enter",
  "command": "acceptSelectedSuggestion",
  "when": "editorTextFocus && suggestWidgetVisible"
}
```

@Thaina @songtm @seancheung @neilsustc Can you verify that above keybindings-customization does restore the previous enter-behaviour?

**Comment by Thaina** [comment] 2017-05-10 08:57
I try it for 1 minute with and seem like that keybinding work

**Comment by Thaina** [comment] 2017-05-10 09:04
Aside from this problem I actually want to report it for so long that suggestion box stole my tab key

I use tab as another kind of space but then vscode from v1 stole it from me

But I just accept that people like it and make keybinding for myself. I was not look in that way before

Until you say that people who use enter to newline felt that enter key was stolen from them

If you think that we should satisfied by keybinding fix like this. I would like to have tab not be a default accept key too and people should also fix it by keybinding

**Comment by SchneMa** [comment] 2017-05-10 11:27
That works for me thx !

**Comment by neilsustc** [comment] 2017-05-10 15:51
It works for me too. 👍 

But, IMHO, the behavior in old version makes more sense in UX. Introducing newline if there won't be textual change is a good **feature**, but not a commonly seen **default behavior**.
So I'd like to vote for a `neverSuggestFullSuggestion` setting and default to `false`.

**Comment by zigfreid5** [comment] 2017-05-19 04:53
I'd like to give a +1 vote to reverting back to the previous behavior. To insert a new line on accepting an autocomplete suggestion is an odd default behavior in my opinion. Maybe as a Shift+Enter behavior, but please don't hijack the default.

**Comment by jrieken** [comment] 2017-05-19 07:11
I will enrich the `"editor.acceptSuggestionOnEnter": true` setting from `true` or `false` to some tri-state.

**Comment by jrieken** [comment] 2017-05-24 07:23
The `editor.acceptSuggestionOnEnter`-setting now accepts `on`, `off` and `smart`. The default is `on`, fyi @isidorn for the latter and the debug console.

**Closed by jrieken** 2017-05-24 07:23 UTC
Labels: suggest, under-discussion

**Comment by joaomoreno** [comment] 2017-05-24 07:38
@jrieken The default seems to be `smart` right now in source.

**Comment by jrieken** [comment] 2017-05-24 08:44
@joaomoreno Not so sure about that: https://github.com/Microsoft/vscode/commit/2b7051efd815ac0afb9b1e7ba021760c8a306fc3

**Comment by isidorn** [comment] 2017-05-24 08:54
@jrieken thanks for the heads up

**Comment by joaomoreno** [comment] 2017-05-24 08:58
I hadn't pulled. 🤦‍♂️

**Comment by regs01** [comment] 2017-06-08 12:29
Will this change go to may update? As this is really desperately annoying.

**Comment by jens1o** [comment] 2017-06-08 17:34
As the milestone says, yes. It will be released tomorrow.
