### ISSUE TITLE
Syntax highlight inside HTML <script> tag is broken

### ISSUE THREAD

**Issue by szmarci** [Microsoft/vscode#26534] opened 2017-05-12 08:57 UTC
- VSCode Version: 1.12.1
- OS Version: Windows 10 Enterprise, version 1607, OS Build: 14393.1198 

Steps to Reproduce:

1. Open an index.html file
2. Write a `<script>` tag with attribute `type="text/x-template"` or `type="text/html"`
3. Inside `<script>` write some HTML
4. Result: 
![vscode-script-highlight](https://cloud.githubusercontent.com/assets/1974290/25990856/8c977284-3701-11e7-9817-9fa43a57ac7c.PNG)

Note: until this build of VSCode it was working properly.

**Comment by egamma** [comment] 2017-05-12 10:02
Duplicate of #25920, will  be in the next recovery build.

**Closed by egamma** 2017-05-12 10:02 UTC
Labels: duplicate
