### ISSUE TITLE
Java import colors hurt my eyes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4365] opened 2016-03-17 14:20 UTC
It was always like this, no regression, just looks bad

![screen shot 2016-03-17 at 15 19 48](https://cloud.githubusercontent.com/assets/1926584/13848810/ca45bc8e-ec53-11e5-89bf-866989648014.png)

**Comment by aeschli** [comment] 2016-03-17 14:29
duplicate of #2987

**Closed by aeschli** 2016-03-17 14:29 UTC
