### ISSUE TITLE
Visual Studio Code is not Light Enough

### ISSUE THREAD

**Issue by HolyOne** [Microsoft/vscode#14109] opened 2016-10-20 16:01 UTC
Visual Studio Community Edition is a free editor and I work with it on desktop.

So the purpose of VS Code should be to open code files in server enviroments, or PC's without VS Installed.
It should be like notepad++ does but with full syntax support.

It is great but it still takes 10 seconds to start up on a fast PC. I think you should load less necessary features on demand.

Also I need to be able to start and debug a sln or csprj file. It just displays me inner xml, no run button.
So I get no useful feature of IDE. All I have is a very slow loading text editor with syntax highlight support

Of course it has much more features but please focus on the most basic use cases

**Comment by roblourens** [comment] 2016-10-20 18:19
10 seconds is slow... is it any faster if you launch with `--disable-extensions`? Debugging C# projects is provided by the C# extension.

**Comment by bpasero** [comment] 2016-10-23 08:27
@HolyOne are you on Windows? Do you have a screen with touch support?

**Comment by HolyOne** [comment] 2016-10-25 18:31
--disable-extensions makes no difference, Actually it takes about 5 seconds
after executing a second time in a I7-2600 processor

I didnt know it allowed debugging thanks

**Comment by HolyOne** [comment] 2016-10-26 15:39
I am on windows server, I am trying to use it as an editor from remote
desktop, server side.

**Comment by weinand** [comment] 2016-10-26 21:38
You seem to run VS Code remotely on a server. Before we try to investigate why you see this slowness on a remote server, could you try to run VS Code on your local computer to get a feel what 'normal responsiveness' of VC Code means?

**Comment by onewhitey** [comment] 2016-10-27 01:01
For me (using VS Code 1.5.3) it takes 5 seconds to view a 65kb JSON file.
The same file opens instantly on Notepad++

This is locally on a i7-3740QM, 16GM RAM, 64 bit Windows 7 Enterprise version of Windows.

**Comment by bpasero** [comment] 2016-10-27 05:50
This could be https://github.com/Microsoft/vscode/issues/13882

**Comment by alexandrudima** [comment] 2016-10-27 14:47
@HolyOne @onewhitey Can you please do the following:

### JavaScript profile

* `Help > Toggle Developer Tools`
* Go to the Profiles tab
* Start profiling
* focus back in VSCode `F1`
* run `Reload Window`
* stop profiling
* try to save the cpu profile (if that doesn't work, Electron has recently had issues with that), then please try to send our way some sort of high-res screenshot where you maybe hover over the long methods

### Startup times

* Run `Code.exe --performance`
* `F1` > `Developer: Startup performance`
* Open the developer tools and share the numbers

This would help us find out where the time is spent

**Comment by onewhitey** [comment] 2016-10-27 22:10
@alexandrudima please find attached the CPU profile and a screenshot below..   Hope this helps shed some light on this.  

![image](https://cloud.githubusercontent.com/assets/17079068/19787385/20826782-9cee-11e6-92fc-e391ce813e01.png)

[CPU-20161028T090030.zip](https://github.com/Microsoft/vscode/files/557151/CPU-20161028T090030.zip)

**Comment by alexandrudima** [comment] 2016-11-07 17:49
@onewhitey From looking at the CPU profile, it looks like spawning a process is very slow on your machine. Very soon when VS Code is started up we spawn two processes:
* the extension host
* also in this case the crash reporter

It appears that this is very very slow (block for 600ms on your machine). I cannot tell at this time what might cause this, but given VS Code sits on Electron, that makes us have a fat 62MB exe, is it possible that perhaps you have some antivirus that decides to jump in and scan the 62 MB exe every time we "fork"?.

**Comment by onewhitey** [comment] 2016-11-07 23:57
@alexandrudima Thanks for the reply.  It could very well be a virus scan that occurs due to our strict working environment.  However, it is installed to the same area as Notepad++, which is very fast.
I might try starting VSCode on my home machine, which I have more control over to see if there is a delay in starting.

**Comment by pflannery** [comment] 2016-11-08 10:43
Running `code --performance --disable-extensions app.js` 
Where app.js is a 2kb file. 
Tested with a local Windows 10 64 bit install, i7 2.3ghz quad, PC
Took six seconds to load. 

I see a long pause after the shell is loaded and the file being shown.

![image](https://cloud.githubusercontent.com/assets/1727302/20095830/01c771fc-a59f-11e6-84be-2fce8e20ca79.png)
```shell
$ npm version
{ Code: '1.7.1',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '51',
  node: '7.0.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.4.500.36',
  zlib: '1.2.8' }
```

**Comment by alexandrudima** [comment] 2016-11-08 14:47
@pflannery Indeed, the times are pretty large.

I'm sitting on a Surface Book with Windows 10, i7 2.6 ghz quad

| What | My measurements | Yours | 
|-------|----------------------|-------|
| Time until renderer process starts | 783 ms | 1771 ms
| Time to load code in the renderer | 989 ms | 2333 ms
| Restoring Editor(s) | 1950 ms | 1697 ms
| Grand Total | 4495 ms | 6131 ms

On my machine it is a bit faster, but definitely not as fast as I'd like it and I believe we have regressed in this area.

Can you also include a CPU profile -- maybe something pops up -- at least code loading should be on par as it is unrelated to the folder being opened.

**Comment by pflannery** [comment] 2016-11-08 17:54
@alexandrudima I just tried to save the cpu profile but the file is always 0 bytes which looks related to issue https://github.com/Microsoft/vscode/issues/13704

**Comment by alexandrudima** [comment] 2016-11-09 09:00
@pflannery Thanks for trying. Yes, we are still on Electron 1.3.8 which prevents cpuprofiles being saved on Windows (0 bytes). If you wish to proceed, you could post some screenshots of where the time is spent (i.e. look at the Chart view, the Heavy (bottom up) view ).

**Comment by pflannery** [comment] 2016-11-09 11:24
@alexandrudima here you go

![image](https://cloud.githubusercontent.com/assets/1727302/20136782/939a94a4-a66e-11e6-8f7d-51f3f2500584.png)

![image](https://cloud.githubusercontent.com/assets/1727302/20136852/f4483874-a66e-11e6-8fa2-11dcef744e1f.png)

**Comment by bpasero** [comment] 2016-11-17 06:50
@HolyOne @pflannery I recently pushed a new command to insider builds to trace where time is spend on startup. Would love if you could give it a try:
* download latest insider build: http://code.visualstudio.com/Download#insiders
* start it
* when done F1 > Startup performance
* send the contents of developer console into here

Thanks!

**Comment by pflannery** [comment] 2016-11-17 18:27
Results from running `code-insiders --performance --disable-extensions app.js`

First time I tried " F1 > Startup performance" I got this error
![first-perf-insiders](https://cloud.githubusercontent.com/assets/1727302/20401703/cdc9493e-acf1-11e6-95a2-ebacbbefd7da.png)

I then ran " F1 > Startup performance" again 
![second-perf-insiders](https://cloud.githubusercontent.com/assets/1727302/20401736/e9e2c55a-acf1-11e6-8278-b70c90148334.png)

However, when I started my laptop this morning my system control icon appeared (its usually hidden and not seen it for many months) 

![image](https://cloud.githubusercontent.com/assets/1727302/20401906/7942a486-acf2-11e6-8a45-00ad7719f067.png)

Turns out I must of changed my laptop performance to "entertainment mode" many months ago and had completely forgotten.
So after switching to "performance mode " and running `code-insiders --performance --disable-extensions app.js` I now see

![third-perf-insiders](https://cloud.githubusercontent.com/assets/1727302/20401949/a71d6da0-acf2-11e6-92e7-2faad924e96e.png)

 under 3 seconds! :)

**Comment by bpasero** [comment] 2016-11-17 19:10
@pflannery thanks, that crash you see should meanwhile be fixed. what I wonder is why you do not see any performance numbers in the output. This is how it should look like:

![image](https://cloud.githubusercontent.com/assets/900690/20403644/edf180d6-ad01-11e6-82c2-ff428d87e303.png)

Great to hear you found the reason for your slowness 👍

**Comment by vingtcent** [comment] 2017-01-11 21:46
yes, same here, I found that the starting time is far too long than notepad ++ or sublime
all these two are much smaller.
But for chrome, is  much bigger, it starts very quickly. 
`(index)TopicTook (ms)0"[main] start => window.loadUrl()"5901"[renderer] window.loadUrl() => begin to require(workbench.main.js)"5322"[renderer] require(workbench.main.js)"12813"[renderer] create extension host => extensions onReady()"10214"[renderer] restore viewlet"4425"[renderer] restore editor view state"16"[renderer] overall workbench load"7437"------------------------------------------------------"8"[main, renderer] start => extensions ready"34929"[main, renderer] start => workbench ready"3162`

**Comment by xeonx1** [comment] 2017-01-15 05:56
I agree that VSCode takes way to long too open, to make it a feasible alternative to Notepad++ for opening text and code files.
It takes 11+ seconds for a cold startup and 7-8 seconds for Reload Window after that with fast SSD and CPU (Intel® Core™ i7-6700HQ, PCIe® NVMe™ M.2 SSD exclusively, 16GB RAM, Win 10 x64) with all extensions disabled, even with vscode added excluded by Webroot and Anti-Malware.
As a workaround, it would be very helpful if could launch VSCode on Windows startup, minimized to tray, as proposed for #11723

**Comment by weinand** [comment] 2017-01-15 17:57
Interesting, on my MacBook Pro with 2.9 GHz Intel Core i7 and 16GB RAM and SSD a cold startup takes under 2 seconds and a Reload Window under 1 second.

**Comment by xeonx1** [comment] 2017-01-16 00:32
According to others, startup is, ironically, much slower on Windows than on Mac: #15108
Many others seem to be reporting major issues with slow startup time (#15455) and requesting workarounds for it (#11723)

**Comment by bpasero** [comment] 2017-01-16 06:35
@xeonx1 we have a command to trace where most time is spend, can you run it and then attach the results here? They are printed to the developer console

![image](https://cloud.githubusercontent.com/assets/900690/21973100/6538653e-dbbe-11e6-8106-c01de3163a52.png)

**Comment by xeonx1** [comment] 2017-01-17 07:36
@bpasero  @jrieken  
Here is the saved log file contents after starting up with --performance command line option and then printing the results via F1 > Developer: Startup Performance, as requested:

(Note: I also posted this, as was also requested, as a comment for related issue #15455 )

Is it supposed to be show "OS" as win32 (as seen in the log) as opposed to win64, due to it being a 32-bit process on Windows 10 64-bit? 
Is there no 64-bit version available for Windows?

Overwriting extension <<.bas>> to now point to mime <<text/x-vba>>
[C:/Users/Dan/.vscode/extensions/abhiagr.livs-1.0.2]: Command `extension.launchInVS` appears multiple times in the `commands` section.
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41003  for  extension.toggleRegexPreview
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41004  for  code-runner.run
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41001  for  code-runner.runCustomCommand
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41000  for  code-runner.runByLanguage
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  41003  for  code-runner.stop
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40995  for  PowerShell.ExpandAlias
Conflict detected, command `extension.toggleRegexPreview` cannot be triggered by ctrl+alt+m due to code-runner.stop
[Extension Host] [C:/Users/Dan/.vscode/extensions/abhiagr.livs-1.0.2]: Command `extension.launchInVS` appears multiple times in the `commands` section.
Startup Performance Measurement
OS: win32 (10.0.14393)
CPUs: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System): 15.96GB (10.59GB free)
Memory (Process): 123.81MB working set (164.63MB peak, 97.02MB private, 36.12MB shared)
Initial Startup: true
Screen Reader Active: false
Empty Workspace: true

Startup Performance Measurement
OS: win32 (10.0.14393)
CPUs: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)
Memory (System): 15.96GB (10.59GB free)
Memory (Process): 123.81MB working set (164.63MB peak, 97.02MB private, 36.12MB shared)
Initial Startup: true
Screen Reader Active: false
Empty Workspace: true
(index)TopicTook (ms)0"[main] start => window.loadUrl()"19071"[renderer] window.loadUrl() => begin to require(workbench.main.js)"15942"[renderer] require(workbench.main.js)"7173"[renderer] create extension host => extensions onReady()"32914"[renderer] restore viewlet"05"[renderer] restore editor view state"17126"[renderer] overall workbench load"31097"------------------------------------------------------"8"[main, renderer] start => extensions ready"75769"[main, renderer] start => workbench ready"7343Array[10]

**Comment by csholmq** [comment] 2017-01-23 14:24
I reckon this can be closed in favor of https://github.com/Microsoft/vscode/issues/15455.

**Comment by jrieken** [comment] 2017-01-23 15:51
check. closing as dupe of #15455

**Closed by jrieken** 2017-01-23 15:51 UTC
Labels: freeze-slow-crash, needs more info
