### ISSUE TITLE
Some repos don't show in the SOURCE CONTROL window, and cannot operate on them

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#82917] opened 2019-10-20 05:49 UTC
- VSCode Version: 1.39.2 zip 64 bit installer
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder which contains **many** different Git repos.
2. Open one file from each repo, so in the **`SOURCE CONTROL`** window, it will show all those repos.
3. When the number of repos shown in the **`SOURCE CONTROL`** window is big enough, some repos aren't able to display in the **`SOURCE CONTROL`** window. Because there is **no scrolling bar** for the **`SOURCE CONTROL`** window, thus they aren't able to be clicked on and operated on.

For example in the below screenshot, there are many repos in the **`SOURCE CONTROL`** window, but only 12 of them can display in this window. The rest cannot be seen in the **`SOURCE CONTROL`** window, so I cannot operate on them at all which is annoying.
![image](https://user-images.githubusercontent.com/19678455/67155369-57679580-f36a-11e9-92aa-847f06e215a4.png)

**Comment by gjsjohnmurray** [comment] 2019-10-20 09:04
/duplicate of #71578 which in turn is pointing to #70888, now closed in favour of #64188

**Closed** 2019-10-20 09:04 UTC
Labels: *duplicate, new release
