### ISSUE TITLE
delayed app-ready event

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#22087] opened 2017-03-06 17:00 UTC
We see traces in which Electron takes a very long time to to receive the `app-ready` event. Because we cannot do anything useful before that happens it blocks startup badly. AV software is suspected to be causing this.

**Comment by jrieken** [comment] 2017-03-06 17:01
The issue for electron is https://github.com/electron/electron/issues/1487

**Comment by ramya-rao-a** [comment] 2017-03-06 19:04
The upstream issue was closed saying that there is nothing they can do https://github.com/electron/electron/issues/1487#issuecomment-169332681

So what are we expecting here?

**Comment by jrieken** [comment] 2017-03-06 20:00
I wanted something in our repo to point to... This comes up frequently and should be the central point for information around this.

**Comment by jrieken** [comment] 2017-11-02 16:16
Unfortunately this has gotten worse with the version of Electron,  v1.7.2v that VS Code is currently using... We hope to make the jump to 1.8.x soon because it doesn't show this behaviour.

**Comment by bpasero** [comment] 2017-11-14 17:29
@jrieken isn't this fixed after defender update on windows?

**Comment by jrieken** [comment] 2017-11-15 07:54
Yes and no. This is a general issue on windows which happens with AV software

**Comment by bpasero** [comment] 2017-11-15 09:10
Ok, removing the electron label as I do not think they can be blamed for it.

**Comment by easyveazie** [comment] 2018-01-24 14:59
I'm experiencing this as well. First load in 20-30 seconds, subsequent loads are 7-10 seconds. We have Symantec Endpoint Protection - working on getting an exception to uninstall it temporarily to see if it helps. This seems to only happen when starting code with a folder opened already.

SEP enabled:
`code --performance

extensionHost.ts:282 [Extension Host] Could not find a free port for debugging
(anonymous) @ extensionHost.ts:282
actions.ts:332 Startup Performance Measurement
actions.ts:334 OS: win32 (10.0.14393)
actions.ts:335 CPUs: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
actions.ts:336 Memory (System): 15.79GB (7.49GB free)
actions.ts:337 Memory (Process): 193.14MB working set (195.93MB peak, 164.73MB private, 43.78MB shared)
actions.ts:338 VM (likelyhood): 0%
actions.ts:339 Initial Startup: true
actions.ts:340 Screen Reader Active: false
actions.ts:341 Empty Workspace: false
actions.ts:349 
actions.ts:354 Loader: Load Script
actions.ts:354 Loader: (Node) Load Script
actions.ts:354 Loader: Eval Script
actions.ts:354 Loader: (Node) Eval Script
actions.ts:362 Extension Activation Stats
actions.ts:371 
actions.ts:374 Raw Startup Timers (CSV)
actions.ts:381 Name	Start	Duration
loadWorkbenchMain	0	827
restore:editors	1081	98
restore:viewlet	1179	27
handleExtensionPoint:commands	13611	42
handleExtensionPoint:menus	13653	4
handleExtensionPoint:jsonValidation	13657	1
handleExtensionPoint:problemPatterns	13658	1
handleExtensionPoint:problemMatchers	13659	1
handleExtensionPoint:colors	13660	0
handleExtensionPoint:taskDefinitions	13660	2
handleExtensionPoint:configurationDefaults	13662	0
handleExtensionPoint:configuration	13662	93
handleExtensionPoint:keybindings	13755	8
handleExtensionPoint:languages	13763	6
handleExtensionPoint:grammars	13769	1
handleExtensionPoint:iconThemes	13770	1
handleExtensionPoint:themes	13771	1
handleExtensionPoint:debuggers	13772	14
handleExtensionPoint:breakpoints	13786	1
handleExtensionPoint:views	13787	0
handleExtensionPoint:snippets	13787	0
`

**Comment by bpasero** [comment] 2018-09-10 15:59
Closing as upstream (issue reported).

**Comment by devils2ndself** [comment] 2020-11-28 19:43
so I've been having having this issue with delayed appready event (it has been taking around 16-17 seconds as the startup performance was saying) for quite some time and I've been struggling with finding a correct solution (it didn't even go away after I uninstalled every bit of AV software on my laptop). but thank god, eventually I found what the problem was. apparently, if you have a somewhat recently released laptop, it will most probably have "nahimic" audio drivers. I actually haven't found a way to uninstall it (maybe installing a different audio driver will do but I haven't tried yet) but ending the "nahimicService" task in the task manager solves the problem for me.

**Comment by douglasparker** [comment] 2020-12-18 08:44
> so I've been having having this issue with delayed appready event (it has been taking around 16-17 seconds as the startup performance was saying) for quite some time and I've been struggling with finding a correct solution (it didn't even go away after I uninstalled every bit of AV software on my laptop). but thank god, eventually I found what the problem was. apparently, if you have a somewhat recently released laptop, it will most probably have "nahimic" audio drivers. I actually haven't found a way to uninstall it (maybe installing a different audio driver will do but I haven't tried yet) but ending the "nahimicService" task in the task manager solves the problem for me.

Thanks for sharing this information. I've been really struggling with this too. It's a huge pain because I use VSCode as my default editor for everything and the delayed startup is horrible even on my high end workstation.

Nahimic is the confirmed culprit for me.

**Comment by landonth** [comment] 2021-07-13 22:52
I also have this issue. Nahimic Service is enabled by default on many Asus computers, and other makes. Disabling a service manually is not really an acceptable solution and in my case it gets reenabled regularly by system updates. And it can't be uninstalled without also removing your onboard audio drivers. (manually extracting installing .inf drivers to work around this isn't a real solution either as aside from being super hacky and disables many features, it's impossible to unpack the inf files from many installers these days.) Very strange that it would cause this kind of interference though Nahimic Service is known to cause issues with other applications, e.g. it can cause SideFX Houdini to crash at random.

Even if there is nothing that can be done to eliminate this issue directly from the VScode developers (I have no idea if where the onus lies), it should be clearly documented as a possible issue (as it is in SideFX Houdini troubleshooting docs) and perhaps even a warning issued in vscode if the Nahimic Service is detected since it is so detrimental, it makes vscode nearly unusable as there is a 10 second delay with EVERY file opened, it's not just a delay of initial app startup which is bad enough.

This was also reported ~8 months ago in this issue https://github.com/microsoft/vscode/issues/113360

Very likely that this often goes unreported as it doesn't completely block VScode from working, it just gives the (very false) impression that VScode and/or the user's computer is a stinking hot unoptimized piece of garbage. So it's work looking into to try and remedy that false perception alone on every single Asus computer in existence and any others that have Nahimic bundle with their audio drivers. Again i'm not blaming VScode for this, it's more likely something nasty that Nahimic is doing but it is also puzzling why certain applications like VScode are somehow severely affected and interfered with while most others are not.

Cheers

**Comment by douglasparker** [comment] 2021-07-13 23:14
This issue just keeps being swept under the rug. I stopped even trying to get them to address it because they'll just close and lock issues.

**Comment by landonth** [comment] 2021-07-13 23:58
> This issue just keeps being swept under the rug. I stopped even trying to get them to address it because they'll just close and lock issues.

This is the master issue, and is "Open," it's the duplicate issues that are getting closed and locked. And it is apparently some problem between Electron and Nahimic, the VScode devs can't resolve it directly even if they wanted to.

**Comment by douglasparker** [comment] 2021-07-14 00:06
> > This issue just keeps being swept under the rug. I stopped even trying to get them to address it because they'll just close and lock issues.
> 
> This is the master issue, and is "Open," it's the duplicate issues that are getting closed and locked. And it is apparently some problem between Electron and Nahimic, the VScode devs can't resolve it directly even if they wanted to.

Ah, I see. It might be better if someone raises this issue with the Electron team then. I'm surprised nobody from the VS Code team mentioned this sooner. Anyways, thanks for the useful information.

**Comment by deepak1556** [comment] 2023-12-12 02:10
Closing as the master issue isn't helpful, slow startup can vary depending on the users setup and I am triaging them on a case by case basis.

**Closed by deepak1556** 2023-12-12 02:10 UTC
Labels: upstream, windows, perf, electron, perf-startup, upstream-issue-linked

**Comment by douglasparker** [comment] 2023-12-12 10:19
> Closing as the master issue isn't helpful, slow startup can vary depending on the users setup and I am triaging them on a case by case basis.

So you guys spend 5 years closing issues as duplicates and now you want us to create individual issues again? 😡
