### ISSUE TITLE
Light+ theme activity bar looks wrong

### ISSUE THREAD

**Issue by JVimes** [microsoft/vscode#92097] opened 2020-03-05 17:21 UTC
Issue Type: <b>Bug</b>

The Light+ theme activity bar has a dark theme. It looks like a bug to users: [1][1], [2][2], [3][3]. Suggest making the Light+ theme's activity bar light. Including a buggy-looking theme in the core product gives the appearance of carelessness.

![image](https://user-images.githubusercontent.com/6148201/76005272-047d1d80-5ec8-11ea-9564-811388099257.png)

[1]: https://github.com/microsoft/vscode/issues/85410
[2]: https://github.com/microsoft/vscode/issues/54900
[3]: https://github.com/microsoft/vscode/issues/21938

VS Code version: Code - Insiders 1.43.0-insider (b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0, 2020-03-05T00:59:24.612Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by usernamehw** [comment] 2020-03-05 18:18
Well, it's 4 people that don't like it and potentially thousands that don't care/like it.

You can customize each color per every theme from `settings.json`:

```js
"workbench.colorCustomizations": {
    "[Default Light+]": {
        "activityBar.background": "#fff",
        "activityBar.foreground": "#000",
        "activityBar.activeBackground": "#f3f3f3",
    },
},
```

**Comment by JVimes** [comment] 2020-03-05 23:36
I don't believe that's true. For each person that takes the time to report the problem, there are a number who agree but don't make the effort.

Alexander (@usernamehw), make sure you're following the [code of conduct](https://opensource.microsoft.com/codeofconduct/) to be "friendly, patient, welcoming, respectful". Being dismissive and making up numbers like "thousands" is not okay.

**Comment by aeschli** [comment] 2020-03-06 08:23
@JVimes Thanks for the input. We currently have no plans to change the appearance of the activity bar for the built-in light theme which is as-designed.

Marking as duplicate of #85410.

**Closed by aeschli** 2020-03-06 08:23 UTC
