### ISSUE TITLE
auto save happening even when off

### ISSUE THREAD

**Issue by runfaj** [microsoft/vscode#80323] opened 2019-09-04 15:03 UTC
Issue Type: <b>Bug</b>

I have tried every possible setting related to auto-save, including disabling extensions and vscode still saves by itself. This started happening recently, maybe just since the last update. It is incredibly annoying, because I can't have pending code changes without the risk of it auto saving within a few seconds, thus causing my entire webpack build to recompile.

There is definitely something in the editor that isn't respecting the auto save as "off". My co-workers that also use vscode don't appear to have this same issue, most having the same or similar setup with extensions, settings, and linting, so not sure what could be the issue.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 8, 6|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.9
vscode-pull-request-github|Git|0.10.0
atom-keybindings|ms-|3.0.6
debugger-for-chrome|msj|4.11.7
color-highlight|nau|2.3.0
vscode-svg-previewer|vit|0.5.0
better-align|wwm|1.1.6

(1 theme extensions excluded)

</details>

**Comment by runfaj** [comment] 2019-09-04 17:07
I also set this to the afterDelay for 20 minutes and it completely ignores that setting. I have absolutely no idea what could be triggering this, as it seems to happen when the window is focused or not and seems to happen at random time intervals - always 1 minute or less.

**Comment by bpasero** [comment] 2019-09-05 04:46
@runfaj can you share your settings file and explain under which condition the file is saved exactly?

**Comment by runfaj** [comment] 2019-09-06 14:52
@bpasero Here's my current settings file:

```
{
  "alignment.surroundSpace": {
      "colon": [-1, 1], // The first number specify how much space to add to the left, can be negative.
      "assignment": [1, 1], // The same as above.
      "arrow": [1, 1], // The same as above.
      "comment": 2 // Special how much space to add between the trailing comment and the code.
      // If this value is negative, it means don't align the trailing comment.
  },
  "editor.cursorStyle": "line-thin",
  "editor.detectIndentation": false,
  "editor.formatOnPaste": true,
  "editor.minimap.enabled": false,
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.rulers": [120],
  "editor.showFoldingControls": "always",
  "editor.tabSize": 2,
  "editor.wordWrapColumn": 120,
  "explorer.autoReveal": false,
  "git.confirmSync": false,
  "search.exclude": {
    "**/.git": true,
    "**/dist": true
  },
  "search.showLineNumbers": true,
  "workbench.colorTheme": "One Dark Pro Bold",
  "workbench.list.openMode": "doubleClick",
  "workbench.startupEditor": "newUntitledFile",
  "workbench.tree.indent": 12,
  "editor.foldingStrategy": "indentation",
  "javascript.validate.enable": false,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 1200000
}
```

The behavior also happens with `"files.autoSave": "off",`. The file is saved automatically in all these conditions:
dirty file is focused
dirty file is unfocused, but window is still focused (e.g. another file pane is focused)
window is unfocused (e.g. browser on separate screen is focused)

All of which seem to save at random intervals. Sometimes it is within seconds of the file becoming dirty, sometimes up to a minute. I've seen it a couple times slightly over a minute as well. I have changed the auto saving setting to everything I can think of and it appears to just ignore those settings. I also disabled every possible saving keyboard shortcut (except cmd-s) thinking maybe some random process might be somehow triggering a key command. No luck.

**Comment by runfaj** [comment] 2019-09-09 19:22
Closing - it looks like completely restarting the computer has fixed it. Not sure what the issue was, but isn't persisting anymore.

**Comment by runfaj** [comment] 2019-09-10 20:01
Reopening - happening again - same situation. It wasn't happening for awhile, but after working in it for several hours, it started happening to where it would autosave even mid-typing.

**Comment by frevds** [comment] 2019-09-24 19:53
Yes, you're not imagining it. It also happens with 1.38.1, but I'm not able to pinpoint it. It appears to happen only while typing, but it is certainly not a known keyboard combination for saving. I was waiting quite a while with unsaved documents now and nothing happened. 
Now I was typing, in a comment in Typescript, the string " of ", then immediately afterwards using Ctrl+Backspace to delete the "of ". All (3) dirty files were saved, and the current file was dirtied again (i.e. my last input came afterwards). I cannot reproduce this though, but I'm not pressing any Ctrl+Shift+S here now anything that could trigger that. Really hard to figure out, seems to sporadically coming, I'm always unprepared (but have to suffer the 1 minute of webpacking my project whenever that happens). 
Extensionwise, I'm having merely the built-in Reference Search, ViewVisual Studio Intellicode, as well as Material Icon Theme and gitflow.

**Comment by frevds** [comment] 2019-09-24 22:22
Now again all my files got saved (after the closing bracket while typing a block of { followed by enter, then } then immediately pressing Ctrl+Down for scrolling, again not reproducible. I'm using US international keyboard, so there was no weird key sequence involved. 
The status bar read "TS/JS language features" or similar, not sure whether it is involved or coincidentally decided to reinitialize intellisense, but could well be. This time the file I was currently typing in did not become dirtied again, so after saving there was no further input. 
My guess is that some language server saves all files in order to rebuild intellisense, which is triggered only when intellisense wants to show something during typing, maybe even snippets.

**Comment by dwelle** [comment] 2019-09-30 15:50
Started happening to me too since `1.38.1` (or possibly `1.38.0`). Not sure what triggers it.

**Comment by frevds** [comment] 2019-09-30 16:39
I had it happening even without typing during reference search, so it's not the input at all, it's happening when some system needs some data and decides to recompile internally, apparently files get saved then.

**Comment by runfaj** [comment] 2019-10-01 19:25
> I had it happening even without typing during reference search, so it's not the input at all, it's happening when some system needs some data and decides to recompile internally, apparently files get saved then.

I have also noticed this. It seems to happen less often, or sometimes not at all when I'm not running webpack/pm2/node, but happens very frequently when I'm running my project.

**Comment by dwelle** [comment] 2019-10-02 18:05
On a hunch I've disabled the official [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) extension and the bug didn't reoccur yet. This may be a total coincidence. Can you guys check if you have it installed & enabled, and if so, try disabling it to see if it solves the problem? If some of you don't have it installed/enabled then we can rule this one out.

**Comment by frevds** [comment] 2019-10-02 18:21
Nope: 

![image](https://user-images.githubusercontent.com/5341447/66070610-ee061b00-e551-11e9-838f-507c527a08cb.png)

Interestingly, I remember having deactivated the Java stuff. Sneaked back in somehow. I'll try deactivating all except Gitflow (might as well be that though), Icons and Reference Search (likely it's that one).

**Comment by runfaj** [comment] 2019-10-02 19:08
My extensions are all passive except for "color highlight" and "gremlins tracker" so pretty sure it isn't extension-based.

**Comment by bpasero** [comment] 2019-10-07 20:27
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by frevds** [comment] 2019-10-14 21:43
The issue is most likely not caused by an extension since it only occured with a recent version of VSC and my extensions were not changed.

**Comment by runfaj** [comment] 2019-10-15 03:38
@bpasero Same comment as @frevds. This wasn't an issue a couple months ago - it was recent on a vscode change. I have noticed it happens most frequently when running a node/pm2 server from a terminal, which is a completely separate process from extensions.

**Comment by dwelle** [comment] 2019-10-15 09:09
I'm using pm2, too. Anyone else?

**Comment by frevds** [comment] 2019-10-15 09:36
Is there any way to detect the origin of the saveAll call? How can we debug VSC and insert a breakpoint?

**Comment by frevds** [comment] 2019-10-17 19:15
I'm getting this definitely during changes without active key combinations (was using cursor keys). At some arbitrary point the status bar always reads `Initializing JS/TS language features...` (good string to search for in the code base and go from there). All files are being saved (and my watcher runs, I'm using gulp in my project). I would say it happens only ever when the TS intellisense needs to update after changes to the types. 
@bpasero Please reopen the ticket or I'll create a new one :).

**Comment by bpasero** [comment] 2019-10-18 06:33
@frevds yeah this can be debugged, put a breakpoint here: https://github.com/microsoft/vscode/blob/93bc26d074f73ace50770afe9f4a264cbe717c6d/src/vs/workbench/services/textfile/electron-browser/nativeTextFileService.ts#L162

**Closed** 2019-10-25 07:30 UTC
Labels: needs more info
