### ISSUE TITLE
brackets in html

### ISSUE THREAD

**Issue by tjy-gitnub** [microsoft/vscode#173455] opened 2023-02-05 02:14 UTC
Type: <b>Bug</b>

In new version,brackets "<" and ">" are highlighted,it's useless and strange.

VS Code version: Code - Insiders 1.76.0-insider (c4a609f94329b17d91cd13a4fd113d1abfe5ec1f, 2023-02-03T05:23:17.202Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by tjy-gitnub** [comment] 2023-02-05 02:16
![image](https://user-images.githubusercontent.com/71509955/216798061-6a58fa84-f7b3-45b6-a125-a0b839adae11.png)

**Comment by lorand-horvath** [comment] 2023-02-06 13:45
Another issue (is probably the same bug) I see the bracket pairs colorized in .txt files as well - they shouldn't be.

**Comment by hediet** [comment] 2023-02-06 14:26
Thanks for reporting! Should be fixed in tomorrows insider build.
It would be awesome if you could verify the bugfix!

**Closed** 2023-02-06 14:40 UTC
Labels: bug, bracket-pair-colorization

**Comment by lorand-horvath** [comment] 2023-02-07 08:04
@hediet I confirm the issue with bracket colorization seems to be fixed in today's Insiders 1.76. Thanks!

**Comment by tjy-gitnub** [comment] 2023-02-08 10:33
yes,the brackets' color in html is back to normal,
but, why are others without colors?
![image](https://user-images.githubusercontent.com/71509955/217504414-bf86bec5-cd88-40c3-958a-6b500644350c.png)
![image](https://user-images.githubusercontent.com/71509955/217504177-a300a747-bc19-4166-8106-29c2c346cf05.png)
(-_-?||

**Comment by hediet** [comment] 2023-02-08 13:26
@tjy-gitnub which version of vscode do you use? And which language is that? Can you check your settings?

**Comment by lorand-horvath** [comment] 2023-02-08 15:46
@hediet I think @tjy-gitnub is working with JS, most probably this snippet from one of his repos: https://github.com/tjy-gitnub/win12/blob/main/sw.js#L61
Could it be caused by the language being used in that file (chinese)? Strange, nonetheless.

**Comment by tjy-gitnub** [comment] 2023-02-09 01:42
No only in js but others
Do yours have the same problem
![image](https://user-images.githubusercontent.com/71509955/217693584-3213e821-0eff-404c-b3e6-93ce0af8af00.png)

It may be my personal problem...

**Comment by blaise80** [comment] 2023-02-09 01:55
N'envoyez jamais de messages sur cet email
