### ISSUE TITLE
Suggest widget: does not allow to resize when limited space

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109466] opened 2020-10-27 11:41 UTC
Testing #109394

A bit of a corner case.

1. Have the suggest widget that it is rendered **above** the cursor
2. Hold the up sash to resize it, hold it all the way below the suggest widget. Still holding it try to move it all the way up -> stops resizing at some point

![recording (2)](https://user-images.githubusercontent.com/1926584/97296955-ac799980-1851-11eb-8b68-ec7dbcbbce49.gif)

**Comment by jrieken** [comment] 2020-10-28 10:38
🤦 I filed a duplicate of that: https://github.com/microsoft/vscode/issues/109569. At least I have fixed it...

**Comment by jrieken** [comment] 2020-10-28 10:38
/duplicate of https://github.com/microsoft/vscode/issues/109569

**Closed by jrieken** 2020-10-28 10:38 UTC
Labels: bug, suggest
