### ISSUE TITLE
wrong z-index order of function tooltip and Jupyter notebook cell in split editor

### ISSUE THREAD

**Issue by schl3ck** [microsoft/vscode#129769] opened 2021-07-29 11:13 UTC
Issue Type: <b>Bug</b>

I noticed when writing Python code in a split editor view with a normal Python file on the left and a Jupyter notebook on the right that the tooltip with details of the method overlaps with a Jupyter notebook cell, but the cell borders and the help text at the bottom of the cell are drawn on top of the tooltip.

![vscode-tooltip-zindex](https://user-images.githubusercontent.com/42554556/127482247-9ed3b8d3-a263-47b3-ac6c-fa9864c84fd1.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (2.45GB free)|
|Process Argv|--crash-reporter-id 0acff1e8-2250-4e84-846e-c8db1fdf8de2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment] 2021-07-29 19:44
:eye:

**Comment by rebornix** [comment] 2021-08-05 20:11
/duplicate of https://github.com/microsoft/vscode/issues/125235

**Closed** 2021-08-05 20:11 UTC
Labels: bug, *duplicate, notebook
