### ISSUE TITLE
I drag&drop a floder in to VSCode then it make me come here.

### ISSUE THREAD

**Issue by C0618C** [Microsoft/vscode#22038] opened 2017-03-06 01:22 UTC
- VSCode Version: <code>Code - Insiders 1.11.0-insider (4db944bc08e34fb15c5805927d9cb67470776606, 2017-03-02T07:10:18.838Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3392)</code>
- Memory (System): <code>7.95GB (2.26GB free)</code>
- Memory (Process): <code>134.82MB working set (134.93MB peak, 98.67MB private, 32.98MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|22|
|main|app.isReady => window.loadUrl()|272|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|281|
|renderer|require(workbench.main.js)|678|
|renderer|create extension host => extensions onReady()|1566|
|renderer|restore viewlet|239|
|renderer|restore editor view state|565|
|renderer|overall workbench load|1908|
|main + renderer|start => extensions ready|2963|
|main + renderer|start => workbench ready|3181|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\*****\bf99_main.cpuprofile.txt`
-`C:\Users\*****\bf99_renderer.cpuprofile.txt`
[bf99_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/819948/bf99_renderer.cpuprofile.txt)
[bf99_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/819949/bf99_main.cpuprofile.txt)

**Comment by jrieken** [comment] 2017-03-06 16:50
closing as dupe of #22086 and #21963

**Closed by jrieken** 2017-03-06 16:50 UTC
Labels: perf-profile
