### ISSUE TITLE
tsserver and yarn consumes a whole CPU core 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#95679] opened 2020-04-20 09:48 UTC
* using ts 3.9.0-dev.20200413
* open vscode sources, work with typescript
* run `yarn && yarn watch`
* 🔥 after a while tsserver will consume a CPU core

**Comment by mjbvz** [comment] 2020-04-20 18:24
Duplicate of https://github.com/microsoft/TypeScript/issues/37653

**Closed by mjbvz** 2020-04-20 18:24 UTC
