### ISSUE TITLE
Updates not working

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/vscode#106258] opened 2020-09-07 22:02 UTC
Copy of #102040 which is locked, but still an issue. See https://github.com/microsoft/vscode/issues/102040#issuecomment-663160453 for `--verbose` logs.

- VSCode Version: 1.46.1 and others
- OS Version: macOS 10.15.5

When I try to apply an update, VS Code doesn't restart and after a manual restart the update hasn't been applied and VS Code offers the update again.

Steps to Reproduce:

1. Choose "Restart to update"
2. VS Code doesn't restart
3. Restart manually
4. Update isn't applied

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment] 2020-09-08 20:45
Seems like a duplicate of https://github.com/microsoft/vscode/issues/100990

Can you check the permissions of `ShipIt_stderr.log`, `ShipIt_stdout.log` under `Library/Caches/com.microsoft.VSCode.ShipIt/` and make sure they are owned by the current user.

**Closed** 2020-09-16 11:23 UTC
Labels: install-update, mac, needs more info

**Comment by callmeberzerker** [comment] 2020-09-17 07:27
Hi @deepak1556 ,

I don't have that `com.microsoft.VSCode.ShipIt` directory path neither in my `/Library/Caches/` nor `~/Library/Caches.

Where else can I look for the logs?

P.S. I am on Catalina and you can see the full info on this related issue I created? https://github.com/microsoft/vscode/issues/106742
