### ISSUE TITLE
Cursor moves to last occurrence of the page while save it , can't type the code in Auto save option enable 

### ISSUE THREAD

**Issue by omprakash-web** [Microsoft/vscode#47380] opened 2018-04-07 08:40 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment] 2018-04-07 23:04
Can you give exact steps for us to reproduce this issue?

**Comment by omprakash-web** [comment] 2018-04-09 05:11
step 1 : enable the option autosave .()
step 2 : now type new code in codebase (lets define a new class and methods give a small lag while type a method )

Then cursor automatically moves to last occurrence of the page ..

Note : i have installed beautify 1.3.0 extension

**Comment by roblourens** [comment] 2018-04-09 05:43
Do you have formatOnSave enabled?

**Comment by omprakash-web** [comment] 2018-04-09 06:17
yes

**Comment by alexandrudima** [comment] 2018-04-09 09:03
@omprakash-web What programming language are you using. i.e. between step 1 and step 2, what file type do you create. Can you also give a complete example of the code you type.

**Comment by omprakash-web** [comment] 2018-04-09 11:34
Programming language : nodeJs  
file type : .js

**Comment by alexandrudima** [comment] 2018-04-09 12:44
@omprakash-web I cannot reproduce. Here are the complete steps I am doing:
1. install `HookyQR.beautify`
2. change the user settings:
```js
{
	"editor.formatOnSave": true
}
```
3. create a new javascript file.
4. type some code in it. e.g:
```js
var x={a:3}
```
5. press cmd+s (to save)

![kapture 2018-04-09 at 14 43 34](https://user-images.githubusercontent.com/5047891/38498354-7808ccf6-3c04-11e8-850c-2036bdb21db7.gif)

Are there more steps to it?

**Comment by omprakash-web** [comment] 2018-04-10 07:49
1. install HookyQR.beautify
2. change the user settings:
 {
    "editor.formatOnSave": true
 }
3. edit a existing javascript file.
Here is my example 

Actually here am manually giving ctrl + s   (though i have enabled option  "editor.formatOnSave": true)
you can able to see two things 

1. Cursor moves to last occurrence
2. minimised functions are getting elaborated 

![peek 2018-04-10 13-07](https://user-images.githubusercontent.com/36755596/38542943-cfcaf9fc-3cc0-11e8-8fd1-f6a011e822a6.gif)

**Comment by alexandrudima** [comment] 2018-04-10 14:09
Thank you for the steps.

Duplicate of #47382

**Closed by alexandrudima** 2018-04-10 14:09 UTC
Labels: needs more info
