### ISSUE TITLE
Region folding does not work in C++

### ISSUE THREAD

**Issue by xinthose** [microsoft/vscode#91157] opened 2020-02-21 15:22 UTC
Steps to Reproduce:

**test.cpp**
```
int main (void) {
    /* #region */
    int tiny = 0;
    /* #endregion */
}
```
`tiny` will not fold in the editor.

**Comment by aeschli** [comment] 2020-03-02 14:46
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/407

**Closed by aeschli** 2020-03-02 14:46 UTC
