### ISSUE TITLE
Contributed problemMatchers can't use Command variables

### ISSUE THREAD

**Issue by elonmallin** [Microsoft/vscode#69622] opened 2019-02-28 22:26 UTC
package.json `contributes.problemMatchers` can't use command variables like `${command:myextension.mycommand}`.

Steps to Reproduce:

1. Create an extension with a problem matcher like:
```
"problemMatchers": [
      {
        "name": "myproblemmatcher",
        "owner": "php",
        "fileLocation": "relative",
        "pattern": [
          {
            "regexp": "^${command:myextension.mycommand}$"
          },
          {
            "regexp": "error: ${command:myextension.mycommand}(.*):(\\d+)",
            "file": 1,
            "line": 2
          }
        ]
     }
]
```
2. Use the problem matcher and notice this doesn't find problems.

What I'm trying to achieve is replace part of the `file` based in my `myextension.mycommand` command so that the `relative` file location becomes correct.
I'm aware this usually doesn't happen but this is a scenario where I'm running a command in a docker container and the path mapping then becomes completely wrong and I need to be able to replace part of the path dynamically.

**Comment by alexr00** [comment] 2019-03-01 12:58
It sounds like what you really want here is to contribute a problem matcher that reads the terminal output and does something with it instead of just a regex. Duplicate of https://github.com/Microsoft/vscode/issues/11663

**Closed** 2019-03-01 12:58 UTC
Labels: *duplicate, tasks

**Comment by elonmallin** [comment] 2019-03-01 16:54
@alexr00 Well, not sure. I would be fine with just being able to use a command variable in my contributed problemMatchers regex.

I thought this was possible since problemMatchers are defined in tasks.json normally. And the [docs](https://code.visualstudio.com/docs/editor/variables-reference) say that command variables can be used in tasks.json.

So the bug would be that problemMatchers that are contributed can't use command variables but problemMatchers defined in tasks.json can I guess.

**Comment by elonmallin** [comment] 2019-03-01 22:50
It's not only command variables that doesn't work in contributed problem matchers regex but also environment and config variables.

**Comment by alexr00** [comment] 2019-03-04 08:47
I will update the documentation to make it clear that variable substitution is not supported in the problem matchers section of tasks.json. The way to make more complex problem matchers will be with the API changes required by #11663.
