### ISSUE TITLE
Freeze after stopping running task `dotnet run watch`

### ISSUE THREAD

**Issue by m4ss1m0g** [microsoft/vscode#110151] opened 2020-11-07 18:54 UTC
## System Info:

- VSCode Version: 1.51.0
- OS Version: Windows 10 Version 2004 (OS Build 19041.572)

## Steps to Reproduce:

1. Create a simple ASP.NET Core 3.1 application
2. Create a Task to run with watch (code below)
3. F1 - Run Task (select watch)
4. Change something on source code to trigger recompilation
5. After the recompilation F1 - Stop Task (watch)

The VSCode freeze and after a while ask for close or wait

Does this issue occur when all extensions are disabled?: **Yes**

## Task Code

```
{
    "version": "2.0.0",
    "tasks": [
         {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run"
            ]
        }
    ]
}
```
Tried to [generate report](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues) without no luck

**Comment by alexr00** [comment] 2020-11-09 10:26
Does the issue still occur if you use the following setting?
```
	"terminal.integrated.windowsEnableConpty": false,
```

Do you have any task or terminal settings set?

**Comment by m4ss1m0g** [comment] 2020-11-09 11:16
> Does the issue still occur if you use the following setting?
> 
> ```
> 	"terminal.integrated.windowsEnableConpty": false,
> ```
> 
No the issue has been fixed, what do the setting ?

> Do you have any task or terminal settings set?

I have this terminal settings
`"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",`

**Comment by alexr00** [comment] 2020-11-09 14:04
Since the issue does not occur with `windowsEnableConpty` set to false, this is a duplicate of https://github.com/microsoft/vscode/issues/76548

**Closed by alexr00** 2020-11-09 14:04 UTC
Labels: needs more info
