### ISSUE TITLE
cpu run 100% when open the vscode

### ISSUE THREAD

**Issue by 673800357** [Microsoft/vscode#36395] opened 2017-10-17 08:08 UTC
![bug2](https://user-images.githubusercontent.com/20512530/31653496-528b86fe-b355-11e7-8aa5-e59c174cd2fe.png)
Hello , when i have updated the vscode to 1.17.1,it seems to have some question.Everytime  i open the vscode when i first turn on the computer

- VSCode Version:1.17.1
- OS Version:14393.1770

Steps to Reproduce:

1.Turn on the computer
2.Then i open the vs
![bug1](https://user-images.githubusercontent.com/20512530/31653483-4d6ef11a-b355-11e7-8de6-fb9fb38438d6.png)
code 

![bug1](https://user-images.githubusercontent.com/20512530/31653504-5d4c0816-b355-11e7-93d7-f86faf0f397b.png)

Reproduces without extensions: No

**Comment by chrmarti** [comment] 2017-10-17 21:27
Are you using cnpm (or similar that uses symlinks) by any chance?

**Comment by 673800357** [comment] 2017-10-18 10:56
But i seems to have thie same  question  when i unstall the cnpm.

**Comment by chrmarti** [comment] 2017-10-19 15:15
It comes from how cnpm uses symlinks in the `node_modules` folder. To work around it you can delete you `node_modules` and then either use npm or `cnpm install --by=npm` to avoid the symlinks. Duplicate of #35659

**Closed by chrmarti** 2017-10-19 15:15 UTC
Labels: needs more info, search
