### ISSUE TITLE
Default integrated terminal profile setting being ignored at start

### ISSUE THREAD

**Issue by krzysztofjeziorny** [microsoft/vscode#123278] opened 2021-05-07 11:15 UTC
Issue Type: <b>Bug</b>

Version 1.56 doesn't respect the setting `"terminal.integrated.defaultProfile.osx"` at the start

<img width="695" alt="Screenshot 2021-05-07 at 12 48 01" src="https://user-images.githubusercontent.com/872730/117441679-0f04ce00-af36-11eb-9efb-da40c688a431.png">

1. Set `"terminal.integrated.defaultProfile.osx": "fish"`
2. Launch VSCode with an integrated terminal turned on
3. The active profile is zsh
4. Kill the terminal and launch it again or just launch a new terminal
5. The profile in the new terminal is correctly set to fish

Does this issue occur when all extensions are disabled?: No
Start Extension Bisect didn't find the issue

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|40.00GB (9.94GB free)|
|Process Argv|--crash-reporter-id 36dace93-2126-427e-9754-26ae69a743d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
django|big|1.0.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
auto-rename-tag|for|0.1.6
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
svg|joc|1.4.6
svn-scm|joh|2.13.5
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.811652604
vetur|oct|0.33.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.6.0
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
sass-indented|syl|1.8.16
shellcheck|tim|0.14.1
vscodeintellicode|Vis|1.2.13
vim|vsc|1.20.2
material-theme|zhu|3.10.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by meganrogge** [comment] 2021-05-07 18:09
Duplicate of #123188 /duplicate

**Closed** 2021-05-07 18:09 UTC
Labels: new release
