### ISSUE TITLE
Extensions do not update

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#53484] opened 2018-07-03 10:24 UTC
Issue Type: <b>Bug</b>

Launch VS Code. New Extensions will begin to auto-update. The tag next to the extension will say "Installing". Then it will change to "Update to <version>".

I'm seeing it currently with VS Live Share. It's trying to update to 0.3.379 and will not. If I restart VS Code it will show as updated. This has happened with other extensions.

VS Code version: Code - Insiders 1.25.0-insider (6ca99aca80e80224f1c0bd4370c6ec4941c3bc54, 2018-06-29T08:52:20.365Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.30GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
json-to-ts|Mar|1.5.5
angulardoc-vscode|Ang|6.0.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
githistory|don|0.4.1
tslint|eg2|1.0.33
auto-rename-tag|for|0.0.15
csharpextensions|jch|1.3.0
Angular2|joh|6.1.1
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.379
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.1
autoimport|ste|1.5.3

(3 theme extensions excluded)

</details>

**Comment by beastdestroyer** [comment] 2018-07-03 11:20
I had this issue, the solution provided by one of the devs is to:
1. Go into the extensions folder and find the folder that belongs to the bugged extension (usually in format of ```extensionAuthor.extensionName``` )
2. Delete the contents and the folder itself
3. Restart VSCode
4. Reinstall extension from VSIX or marketplace

It should install without any problem and with the latest version.
Hope this helps!

**Comment by sandy081** [comment] 2018-07-03 15:58
Duplicate of #53426

**Closed by sandy081** 2018-07-03 15:58 UTC
Labels: *duplicate, extensions
