### ISSUE TITLE
Terminal Clear Powershell not working

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/vscode#81626] opened 2019-09-30 08:12 UTC
To start I apologize in advance to @Tyriar as there are a _bunch_ of issues related to terminal clearing that are flagged by you as duplicates, and this one _may_ be as well.  The reason I'm creating a new issue is because all of the duplicates eventually resolve to either #75141 or a closed issue.  This issue is _not_ specific to Python, like #75141 discusses and it is a _new_ issue (just started happening for me), so shouldn't be closed.  Also, this problem appears to affect several different shells (tested with 5 different shell).

- VSCode Version:
```
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
- OS Version: Windows 10 version 1903

Steps to Reproduce:
1. Set default terminal to Powershell.
1. Open a new integrated terminal window.
1. Press enter a few times.
1. Execute the Terminal Clear operation.
1. Type **3** letters (note, bug doesn't reproduce after 1 or 2 letters).
1. --> Notice that the entry feed jumps down, though the prompt doesn't.

Repeat the process with the new PowerShell (pwsh 6.2.3).

Repeat the process with Git Bash.  Notice that typing 3 letters doesn't reproduce the problem, however pressing enter once does.

Repeat the process with Command Prompt.  Notice that the problem reproduces on enter, not on 3 letter input (similar to Git Bash).

Repeat the process with WSL Bash.  Notice that the problem **does not** reproduce.  However, notice that if you change the default shell after clearing, the clear state resets.  This also happens if you change shell tabs.

Does this issue occur when all extensions are disabled?: Yes

----

I just updated to WIndows 1903 last night and immediately noticed the problem today.  It was not present yesterday.  I do not believe I received a VSCode update overnight.  The Windows Update also included a .NET update of some kind (I didn't pay close attention).

**Comment by Tyriar** [comment] 2019-09-30 17:52
Yes this is a duplicate of that issue too, the reason it happens in everything except WSL is because WSL doesn't do the Windows Console API emulation stuff but instead works just like it would in Linux or Mac.

/duplicate #75141

**Closed by Tyriar** 2019-09-30 17:52 UTC

**Comment by MicahZoltu** [comment] 2019-10-01 04:06
@Tyriar A very similar bug is _also_ present in WSL, it just is _triggered_ differently than the others.  Does that also apply to #75141?

**Comment by Tyriar** [comment] 2019-10-01 14:51
@MicahZoltu this stuff is all related to conpty, you'd be better off trying to repro in Windows Terminal and following up in https://github.com/microsoft/terminal/issues as they own the backend that we use.

**Comment by MicahZoltu** [comment] 2019-10-08 06:37
@Tyriar How does one replicate the "Terminal Clear" command that VSCode sends to the terminal, but outside of VSCode?  If the problem is in another project, I would love to report it there and work towards resolution, but I don't know what exactly VSCode is doing under the hood.

**Comment by MicahZoltu** [comment] 2019-10-08 07:04
Oh, actually if I press `ctrl-l` in the VSCode terminal the screen clears correctly!  The problem only appears when I use the VSCode "Terminal Clear" command.  This returns me to my previous question, what is VSCode doing when I do Terminal Clear?  It isn't sending the equivalent of ctrl-l (which works at clearing the terminal!)?

**Comment by Tyriar** [comment] 2019-10-08 13:45
@MicahZoltu Terminal: Clear clears out the buffer purely on the terminal side, so when conpty decided to redraw the buffer it restores it since it's view of the world didn't change. I don't think we can send ctrl+l as that wouldn't work all the time (eg. if an application is running and doesn't handle it).
