### ISSUE TITLE
Terminal erratic behavior + duplicate path after updating VSCode

### ISSUE THREAD

**Issue by abigwonderful** [Microsoft/vscode#28558] opened 2017-06-12 18:49 UTC
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: macOS Sierra - 10.12.5
- **using ZSH**

Steps to Reproduce:

1. updated to latest VSCode version
2. open terminal instance
3. look at path (see image)
![vscode-path](https://user-images.githubusercontent.com/1163408/27049687-47535b50-4f6d-11e7-8bfb-a631f64e02d2.jpg)
4. when interacting with terminal (typing/clicking) there is a flicker and text flashes while the path looks to correct itself... but always returns to its duplicated state.

**Comment by chrisj-skinner** [comment] 2017-06-12 19:26
Same here : https://github.com/Microsoft/vscode/issues/28562

**Comment by ramya-rao-a** [comment] 2017-06-12 19:42
Duplicate of #26038

@Tyriar would the fix for #26038 also fix the flicker/flash issue?

**Closed by ramya-rao-a** 2017-06-12 19:42 UTC
Labels: new release

**Comment by Tyriar** [comment] 2017-06-12 19:49
@ramya-rao-a yep, the flicker happens whenever the terminal is "refreshed", for example when a keypress enters a char.
