### ISSUE TITLE
installed some extensions 

### ISSUE THREAD

**Issue by albertsmus** [Microsoft/vscode#10760] opened 2016-08-21 12:45 UTC
- VSCode Version:1.4
- OS Version:ubuntu 16.04

Steps to Reproduce:

1. installed some extensions and i get this message: "Run VS Code with admin privileges so the changes can be applied."
2.

**Comment by alexandrudima** [comment] 2016-08-22 07:53
@albertsmus I have searched our code base for "Run VS Code with admin privileges" and did not find any results. I believe this message is coming from one of the extensions you have installed. Perhaps you can track down which one shows this message?

**Comment by shanquan** [comment] 2016-08-26 09:14
seems to be caused by '[vscode-icons](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)'. see the solution [here](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons#windows-users)

**Comment by alexandrudima** [comment] 2016-08-26 10:14
Closing in this case.

**Closed by alexandrudima** 2016-08-26 10:14 UTC
Labels: needs more info
