### ISSUE TITLE
Notebook diff editor screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114915] opened 2021-01-25 15:09 UTC
<img width="1136" alt="Screenshot 2021-01-25 at 16 06 58" src="https://user-images.githubusercontent.com/1794099/105723819-82567700-5f27-11eb-9242-7eb27170330d.png">

* opened internal back
* pull
* got the usual conflict dialog
* selected overwrite
* open diff from SCM viewlet

fyi - I have both version locally, cannot attach to this issue

**Comment by rebornix** [comment] 2021-01-25 18:47
Not sure which commit triggers it but the root cause is https://github.com/microsoft/vscode/commit/7468a060129fb55c50635d534c828473b2887828. Reverting this.

**Comment by rebornix** [comment] 2021-01-25 19:39
Fixed via 7468a060129fb55c50635d534c828473b2887828.

**Closed by rebornix** 2021-01-25 19:39 UTC
Labels: bug, important, notebook

**Comment by jrieken** [comment] 2021-01-26 14:36
I now see different screen cheese...
