### ISSUE TITLE
Replacing lots of content sometimes fails

### ISSUE THREAD

**Issue by hughbe** [microsoft/vscode#73432] opened 2019-05-07 18:26 UTC
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: OSX 10.14.4 (18E226)

Steps to Reproduce:

1. `git clone https://github.com/dotnet/winforms`
2. `cd winforms`
3. `code .`
4. Open Search
5. With regex search enabled, type `*(///|//) <include file=.*/> *\n` (notice there are 8396 results)
6. Replace all occurrences with the empty string.
7. Sometimes this fails - files are modified but are opened without being saved

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment] 2019-05-08 01:25
You can use the "Save All" command, but there is an issue for this here: https://github.com/microsoft/vscode/issues/36600

You also might want to try enabling auto save.

**Comment by hughbe** [comment] 2019-05-08 01:31
@roblourens my point is that sometimes it stops halfway, leaves all the half-edited tabs open and finishes.
Other times, it succeeds and all files are saved automatically and no new tabs are opened

**Comment by roblourens** [comment] 2019-05-08 01:56
@sandy081 Actually this is supposed to save all the files automatically right?

**Comment by roblourens** [comment] 2019-05-08 01:57
Possible that https://github.com/microsoft/vscode/issues/66953 is involved too

**Comment by sandy081** [comment] 2019-05-08 10:06
Looks to me duplicate of https://github.com/Microsoft/vscode/issues/73276

**Comment by roblourens** [comment] 2019-10-08 01:29
Possibly fixed by https://github.com/microsoft/vscode/issues/66953, let me know if it still happens

**Closed by roblourens** 2019-10-08 01:29 UTC
Labels: search
