### ISSUE TITLE
Failure to detect full file system

### ISSUE THREAD

**Issue by slhussey** [Microsoft/vscode#73038] opened 2019-04-29 14:05 UTC
Issue Type: <b>Bug</b>

Have a directory/folder open in VS Code that resides on a SMB share hosted on a server running Ubuntu 18.04 LTS and the file system is full
Create a new file
Enter text in the file
Save the file

NO ERROR MESSAGE. . . no indication that the file was not saved.

I am reporting this from a different machine than where it occurred, thus not including system information or enabled extensions.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

**Comment by RMacfarlane** [comment] 2019-04-29 15:29
Duplicate of https://github.com/Microsoft/vscode/issues/34915

**Closed by RMacfarlane** 2019-04-29 15:29 UTC
