### ISSUE TITLE
useIgnoreFilesByDefault not honored in a multi root folder setup

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#37289] opened 2017-10-31 13:50 UTC
Testing #37179

1) enabled search.useIgnoreFilesByDefault as user setting
2) open a multi root folder workspace, one of the root folders excludes a folder ("server")
3) open quick open, the file server.js is still proposed

Setup
![image](https://user-images.githubusercontent.com/172399/32227070-803f9a22-be4a-11e7-8243-df5e55e867b6.png)

server.js is proposed
![image](https://user-images.githubusercontent.com/172399/32227091-92be9586-be4a-11e7-8756-606d2cd87b69.png)

Enabling search.useIgnoreFilesByDefault as workspace setting has the same issue.

**Comment by chrmarti** [comment] 2017-11-01 18:36
The editor history does not apply the ignore files exclusions. Duplicate of #37215

**Closed by chrmarti** 2017-11-01 18:36 UTC
Labels: search
