### ISSUE TITLE
HttpError: t.headers is not iterable

### ISSUE THREAD

**Issue by adam248** [microsoft/vscode#163214] opened 2022-10-10 07:11 UTC
- Extension version: 0.50.0 (Have tried 0.48.0 & pre-release as well)
- VSCode: 1.72.0 (user setup)
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Try to access any authenticated Github API calls eg: via Publish Branch button in Source Control or Open Remote Repo
2. Get an error in VSCode saying "Error: t.headers is not iterable"
3. DevTools shows the following error... (see below)
4. The similar thing is happening when I try to use the [Choose a License extension](https://github.com/ultram4rine/vscode-choosealicense) 
5. I first noticed this issue when first trying the Choose a License extension...
6. Have closed VSCode and reopened it in different folders.
7. Have tried disabling extensions with no joy as well....

```
 ERR [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
workbench.desktop.main.js:87 [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
```

**Comment by adam248** [comment] 2022-10-11 02:42
whoops... thank you @alexr00 my mistake

**Comment by adam248** [comment] 2022-10-11 02:44
whoops again... wow I am having a bad day

**Comment by joaomoreno** [comment] 2022-10-11 09:13
@adam248 Are you authenticating against github.com? Or GitHub Enterprise?

**Comment by jangita** [comment] 2022-10-11 09:28
I seem to be having the same problem, I just set up a new machine and got the error, and now all my installs in different computers seem to be having the same problem. I'm authenticating against github.com and the error occurs in Dev Containers: Clone Repository in Container Volume > Clone from Github
Git Clone > Clone from Github

**Comment by joaomoreno** [comment] 2022-10-11 09:46
Very strange, I still am unable to reproduce. 
Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by jangita** [comment] 2022-10-11 10:30
Yes it does. However I have noticed that it does not happen with a clean install or with remote development extension installed.
However after doing a settings sync which installs all my extensions, I do get the error. So it may be caused by an extension or doing a settings sync. PS: my settings sync is with Github.

My extensions list is
```
code --install-extension 2gua.rainbow-brackets
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.codespaces
code --install-extension GitHub.copilot
code --install-extension GitHub.remotehub
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-repositories
code --install-extension PKief.material-icon-theme
code --install-extension RapidAPI.vscode-rapidapi-client
code --install-extension redhat.vscode-xml
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
```
I'm now trying to remove them one by one to see what cures it.

**Comment by jangita** [comment] 2022-10-11 10:53
Hello again,

It seems `RapidAPI.vscode-rapidapi-client` breaks it. After uninstalling and restarting it works fine. Hi @adam248 would you also be running this extension? If so then I think we found our culprit.

**Comment by adam248** [comment] 2022-10-11 10:54
WOW! Yes, I am trying now...

**Comment by adam248** [comment] 2022-10-11 10:56
Yes. Just disabled it and now Github API calls working fine.
Do we move this issue to RapidAPI now??? or what...

**Comment by adam248** [comment] 2022-10-11 11:08
I also just tried opening a remote Repo via the GitHub Repositories extension
fails with RapidAPI enabled and works when disabled.

The only thing that works is syncing to a Github repo branch once the local git is published to Github...
strange behaviour

**Comment by adam248** [comment] 2022-10-11 11:14
> @adam248 Are you authenticating against github.com? Or GitHub Enterprise?

github.com as well

**Comment by joaomoreno** [comment] 2022-10-11 11:40
Closing as issue comes from another extension.

**Closed by joaomoreno** 2022-10-11 11:40 UTC
Labels: info-needed

**Comment by estruyf** [comment] 2022-10-27 14:51
I have been looking into the issue, and it seems related to `node-fetch`. Inside the `github` extension `@octokit/request` makes use of `globalThis.fetch`. If any extension uses another version of `node-fetch` this seems to cause the issue.

Doing a bit more analysis on this, but for now that is what I already found.
