### ISSUE TITLE
Gnome fractional scaling not supported - blurry UI

### ISSUE THREAD

**Issue by LennyPenny** [microsoft/vscode#72759] opened 2019-04-23 10:48 UTC
- VSCode Version: 1.34.0-insider
- OS Version: fedora 30-beta

Steps to Reproduce:

1. Use gnome fractional scaling on a monitor
2. Open vs code

Top is vs code file browser, bottom is nautilus launched directly from gnome
![image](https://user-images.githubusercontent.com/4027243/56575269-9be5c480-65c5-11e9-84ee-dd64f549f224.png)

According to https://gitlab.gnome.org/GNOME/mutter/issues/566 and https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1825625 this is an issue with vs code not having support for fractional scaling. 

Is this a problem I should forward to the electron repo or is vs code the right place?

**Comment by bpasero** [comment] 2019-04-23 12:40
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by LennyPenny** [comment] 2019-04-23 15:15
Sadly I am on fedora linux  and use the `.rpm` builds, are these available as well?

**Comment by bpasero** [comment] 2019-04-23 15:19
@LennyPenny https://az764295.vo.msecnd.net/exploration/a872a905cad7185d9bf55603aa95436df2df3601/code-exploration-1.34.0-1555567602.el7.x86_64.rpm

**Comment by carwyn** [comment] 2019-04-24 00:57
This issue effects anything that's based on chromium including current Google Chrome.

@LennyPenny are you using Wayland on Fedora 30 by any chance? I'm guessing you are as I believe Gnome 3.32 fractional scaling is only available on Wayland. Anything that has to use XWayland (which I think includes current Chromium) ends up blurry as it's not using optimal scaling compared to toolkits like Gtk and Qt that have native Wayland support.

There is some work on chromium Wayland support, much of it here https://github.com/Igalia/chromium with some already upstream.

Until there is proper fractional scaling support It may be possible to force UI scaling off in chromium and instead use font scaling that would at least not be blurry. Widgets however won't be scaled.

**Comment by LennyPenny** [comment] 2019-04-24 09:49
@carwyn yes, gnome fractional scaling is wayland only, which I am using

**Comment by bpasero** [comment] 2019-10-09 18:39
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by LukeCarrier** [comment] 2019-10-09 19:20
@bpasero there's no change; see the link @khvn26 already posted above for the upstream Chromium effort: https://bugs.chromium.org/p/chromium/issues/detail?id=578890

**Comment by hedgepigdaniel** [comment] 2019-11-11 06:10
This is the same underlying issue as https://github.com/microsoft/vscode/issues/41345

**Comment by WhyNotHugo** [comment] 2020-02-27 11:00
Note that this is not Gnome-specific. It affect any modern Linux system running on Wayland (instead of Xorg).

**Comment by pmhoudry** [comment] 2020-03-13 02:59
Any update on this ? The lack of fractionnal support from vscode under wayland seems like a pretty big deal...

**Comment by otaviomad** [comment] 2020-11-05 20:13
Electron has [recently added wayland support](https://github.com/electron/electron/pull/26022) and it will _probably_ be shipped with Electron 12 (which should happen in a few weeks if you go by their schedule). As is stated in #109176, VSCode will consume the new binaries when released and this issue will finally go away.

**Comment by paidhi** [comment] 2020-11-21 17:19
I can’t wait for this annoying issue to finally go away. 4K displays are not a rarity anymore theses days. Especially with Developers and IT engineers. I have switched from Chrome back to Firefox because of this. Wayland is working stable with Fedora+GNOME+fractional-scaling already. The upcoming Fedora 34 will switch also KDE/Plasma’s default to Wayland. This issue is pretty much the last problem keeping me from fully adopting a Linux workstation.
As for the JVM based Jetbrains IDE’s (PyCharm, IntelliJ) - I don’t care anymore about their shortcomings with HiDPI/scaling on Linux because VSCode has become so good.

**Comment by theGeekyLad** [comment] 2020-12-26 18:17
@paidhi Chrome's 87.x builds' Wayland support is quite telling. `--enable-features=UseOzonePlatform` and `--ozone-platform=wayland` enables transitory support for Wayland and thankfully super smooth scrolling (missed this on X) with 4k.

Loving it on my XPS 15! Hope Electron's roll out v12 soon.

**Comment by fosskers** [comment] 2021-03-04 22:21
Electron 12 was recently released.

**Comment by Saverio-Angelicola** [comment] 2021-04-01 17:04
Hello, is there a version of vscode that is available with electron 12 support for native wayland support to download.

**Comment by otaviomad** [comment] 2021-04-01 17:33
> Hello, is there a version of vscode that is available with electron 12 support for native wayland support to download.

Not yet (at list not officially), but almost there. It seems like I vastly overestimated how soon electron 12 would release. You can check the ongoing PR at #120034.

**Comment by Royal-lobster** [comment] 2021-05-02 13:11
1.56 is on electron 12 but still it looks blurry on wayland fractional scaling.

**Comment by adamcstephens** [comment] 2021-05-02 13:21
You need to pass the CLI args: https://github.com/microsoft/vscode/issues/109176#issuecomment-826082341

**Comment by Gaetan-LeGac** [comment] 2021-05-02 13:22
> 1.56 is on electron 12 but still it looks blurry on wayland fractional scaling.

Adding the `--enable-features=UseOzonePlatform --ozone-platform=wayland` arguments solved the issue in my case.
But there are still some bugs (mouse cursor not scaled)

**Comment by carwyn** [comment] 2021-05-04 08:09
For me the mouse image seems scaled, but the targeting, i.e. the part of the mouse cursor that registers as a "click" doesn't seem right, perhaps as if the region that's used for the targeting is the pre-scaled area?

**Comment by Gaetan-LeGac** [comment] 2021-05-04 12:38
> For me the mouse image seems scaled, but the targeting, i.e. the part of the mouse cursor that registers as a "click" doesn't seem right, perhaps as if the region that's used for the targeting is the pre-scaled area?

This issue seems to be solved since I upgraded Ubuntu from 20.10 to 21.04

**Comment by carwyn** [comment] 2021-05-04 12:42
> > For me the mouse image seems scaled, but the targeting, i.e. the part of the mouse cursor that registers as a "click" doesn't seem right, perhaps as if the region that's used for the targeting is the pre-scaled area?
> 
> This issue seems to be solved since I upgraded Ubuntu from 20.10 to 21.04

Oh, yes, an update to Fedora 34 seems to have fixed this too. Thanks for mentioning it.

**Comment by PHLAK** [comment] 2021-05-07 15:55
Does VS Code (or Electron) have anything like [`chrome-flags.conf`](https://wiki.archlinux.org/title/chromium#Making_flags_persistent) for persisting flags?

**Comment by carwyn** [comment] 2021-05-07 16:07
> > For me the mouse image seems scaled, but the targeting, i.e. the part of the mouse cursor that registers as a "click" doesn't seem right, perhaps as if the region that's used for the targeting is the pre-scaled area?

> Update: After few hours of usage, the problem carwyn mentioned is back.

Yup, I thought it had gone but it's definitely still there in fully updated Fedora 34 (Gnome 40).

**Comment by alex-voodoo** [comment] 2021-05-18 04:54
> Placing something like the following in `~/.local/share/applications/code-wayland.desktop` will give an app launcher icon that will use the correct arguments:

This doesn't work for me on Fedora 34 and vscode version 1.56.2 installed from the Microsoft's repository.  Running `code --enable-features=UseOzonePlatform --ozone-platform=wayland` shows a couple of warning like 'these flags are unknown, but we pass them to Electron/Chromium', and then the process ends silently.

**Comment by augustozanellato** [comment] 2021-05-26 09:48
You'll also need to add `"window.titleBarStyle": "custom"` in your config.json if you're missing the title bar while running vscode under wayland, see electron/electron#11907, electron/electron#27016, electron/electron#27522

**Comment by rapgenic** [comment] 2021-12-22 17:11
> This doesn't work for me on Fedora 34 and vscode version 1.56.2 installed from the Microsoft's repository. 

I'm on Fedora 35, Vscode version 1.63.2 and I'm experiencing the same problem. I've managed to solve it by adding the `--disable-gpu` option to the command line:

```
$ code --enable-features=UseOzonePlatform --ozone-platform=wayland --disable-gpu 
```

**Comment by tomjxyz** [comment] 2021-12-26 15:16
Can confirm that fixed it for me on version 1.63.2.

**Comment by mirao** [comment] 2022-01-11 13:13
I can see the same issue with fractional scale `175%` with screen resolution `3840x2160` on Dell 27", Ubuntu 21.10 (Wayland), VSCode 1.63.2.
A solution for me was disabling of fractional scaling, then setting of scale to `200%` and decreasing of scaling factor for fonts to  `0.90` (default is 1) in Tweaks tool.

**Comment by carwyn** [comment] 2022-01-11 16:47
Those of you that are having to add `--disable-gpu` to get this to work, which GPU are you using? I'm using the `amdgpu` driver on Fedora 35 with VSCode 1.63.2 and the `--enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox` arguments are still sufficient.

Seems to launch ok without `--no-sandbox` too (which isn't in the Exec line of the RPM version of the .desktop file), I'll leave that off and see if it misbehaves.

**Comment by LukeCarrier** [comment] 2022-02-02 00:22
Hey @carwyn, I guess this may be related to [a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1125485) which may be causing GPU acceleration to erroneously use a discrete graphics card over an integrated one.

**Comment by a9udn9u** [comment] 2022-02-07 05:58
A note to Ubuntu users: if you installed vscode via snap, the above workaround (`--enable-features=UseOzonePlatform --ozone-platform=wayland`) will instantly crash on start. It works if install vscode from the `.deb` file.

**Comment by arianvp** [comment] 2022-03-11 11:29
It works but my mouse is super small in the Electron window.

**Comment by dieseltravis** [comment] 2022-04-09 02:57
I installed directly from the deb and I get this error in Pop!_OS
```
❯ code --version
1.66.1
8dfae7a5cd50421d10cd99cb873990460525a898
x64

❯ code --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by loafee** [comment] 2022-04-11 04:23
I'm getting these as well on plain Ubuntu. I've been searching around on a lot of these threads, tried the commands listed, I haven't been able to get vscode to not be blurry.

**Comment by qyb** [comment] 2022-04-11 11:23
> 

upgrade to ubuntu 22.04 beta?

**Comment by Kobtul** [comment] 2022-04-11 11:27
On Pop OS 20.04 launching code  --enable-features=UseOzonePlatform
--ozone-platform=wayland > /dev/null 2>&1 & disown &exit works fine

po 11. 4. 2022 v 6:23 odesílatel loafee ***@***.***> napsal:

**Comment by loafee** [comment] 2022-04-11 23:37
unfortunately im not sure where i saw the suggestion first, but if i start ubuntu with xorg now (available with the little gear in the bottom right that shows up after you've selected a user but before you've logged in) my vscode scaling issues go away. in "about" it says that im using x11, this was true before and i had scaling problems, but now the issues are fixed? im not really sure what has happened, but that could be an option for some other folks.

**Comment by 8Keep** [comment] 2022-04-23 20:38
On Fedora 35. Running `code --enable-features=UseOzonePlatform --ozone-platform=wayland` returns:
```
> code --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
>
```
And nothing happens, no window pops up. Any way to debug this?

**Comment by Kobtul** [comment] 2022-04-23 21:25
This is fine, these parameters are passed to Electron and they work. The
text is no longer blurry on the Wayland session on fractional scaling.

so 23. 4. 2022 v 22:38 odesílatel Davis Rollman ***@***.***>
napsal:

**Comment by paritosh9199** [comment] 2022-04-24 16:20
> On Fedora 35. Running `code --enable-features=UseOzonePlatform --ozone-platform=wayland` returns:
> 
> ```
> > code --enable-features=UseOzonePlatform --ozone-platform=wayland
> Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
> Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
> >
> ```
> 
> And nothing happens, no window pops up. Running code without these params opens normally, blurry. Any way to debug this?

Facing the same issue on Fedora 36 as well.

**Comment by 8Keep** [comment] 2022-04-24 16:34
Hey @paritosh9199 I fixed it by installing vscode insiders. I am also on Fedora. Apparently there is a bug in the electron version stable vscode is on right now.

**Comment by paritosh9199** [comment] 2022-04-24 16:35
> Hey @paritosh9199 I fixed it by installing vscode insiders. I am also on Fedora. Apparently there is a bug in the electron version stable vscode is on right now. 

I see. I'll install vs code insiders right away. So is the scaling working correctly now?

**Comment by 8Keep** [comment] 2022-04-24 16:47
Yes, seems to be working for me. There is a bug dragging and dropping files in the project view, it crashes. See #146850

**Comment by faern** [comment] 2022-05-07 10:18
I still have a blurry UI when I run VSCode natively under wayland (`--ozone-platform=wayland`) with fractional scaling (1.2). I have verified that the program actually runs via Wayland (xeyes can't see the window). The same blur happens on both stable code and insider (both are at 1.67 in the fedora repos right now). The thing is that the menu bar at the top is sharp! So that's great, that's properly scaling! But all the contents of the editor is blurry.

**Comment by darkbasic** [comment] 2022-05-07 10:39
Fractional scaling in gnome **is** blurry. Only QT apps in X were not blurry with fractional scaling.

**Comment by darkbasic** [comment] 2022-05-07 10:41
See https://www.reddit.com/r/kde/comments/pfvl9j/wayland_fractional_scaling_may_be_sort_of_a for more info.

**Comment by 8Keep** [comment] 2022-05-07 11:31
Fractional scaling works great with all gnome apps out of the box. I use it every day

**Comment by faern** [comment] 2022-05-07 13:54
Work fine in all other programs that run under Wayland. Including other Electron apps such as Signal.

**Comment by cbrnr** [comment] 2022-05-24 07:53
Is this really limited to *fractional* scaling? I have blurry fonts even when I scale to 200%.

**Comment by elvisangelaccio** [comment] 2022-05-26 12:30
> Is this really limited to _fractional_ scaling? I have blurry fonts even when I scale to 200%.

Same here on archlinux with KDE Plasma wayland and 200% scaling on a 4k 27'' monitor.

`code --enable-features=UseOzonePlatform --ozone-platform=wayland` fixes only the text in the top menus. Text in the actual editor is still blurred for me:

![immagine](https://user-images.githubusercontent.com/7082518/170487794-38b4f0bd-a622-463b-b574-2ee6766672b6.png)

**Comment by kumibrr** [comment] 2022-06-06 14:26
> > Is this really limited to _fractional_ scaling? I have blurry fonts even when I scale to 200%.
> 
> Same here on archlinux with KDE Plasma wayland and 200% scaling on a 4k 27'' monitor.
> 
> `code --enable-features=UseOzonePlatform --ozone-platform=wayland` fixes only the text in the top menus. Text in the actual editor is still blurred for me:
> 
> ![immagine](https://user-images.githubusercontent.com/7082518/170487794-38b4f0bd-a622-463b-b574-2ee6766672b6.png)

The only way I could fix this is changing any of the displays' scale. The text will render clear, and then I revert that change and stays clear.

It's not optimal because anytime I open a new vscode window I have to do that scale thing again.

**Comment by vially** [comment] 2022-06-14 17:59
> This is my experience as well: crisp top menu and file dialogs (provided by electron) but blurry application area (the regions drawn by vscode itself).
> - Sway/wlroots
> - HiDPI laptop display with scale 2x

For what it's worth, I'm also on sway and I'm **not** experiencing this issue. I have a very similar setup (4k displays configured with a scale of 2).

I've been keeping an eye on this issue and when I saw the previous reports about blurry content I assumed it must be compositor specific (either KDE or GNOME). But now it turns out some users are experiencing this on sway which is strange as I've been using VSCode on Wayland using sway for a year or so and I *never* had this issue. Maybe it's GPU specific (I'm using the `AMDGPU` Mesa driver)?

**Comment by edrex** [comment] 2022-06-14 18:23
@vially I have a mixed-scale setup (`outputs.eDP-1.scale =2`, `outputs.DP-1.scale=1`). Maybe that's what's needed to trigger this?

**Comment by vially** [comment] 2022-06-14 18:26
> Maybe that's what's needed to trigger this?

Seems like a good candidate. It might be worth disconnecting one of the displays to see if fixes the issue. I would also test to see if it's specific to VSCode or if it happens in upstream projects too (e.g.: electron and chromium).

**Comment by edrex** [comment] 2022-06-14 18:36
> It might be worth disconnecting one of the displays to see if fixes the issue.

Yes, unplugging my `scale = 1` external display causes text to crisp on the `scale = 2` display. Replugging the `scale = 1` display preserves the crispness on 2, but now moving the window to 1 results in the surface being downscaled by the compositor, when what should happen is that the client notices the surface is on a different scale display and sets the buffer scale accordingly.

>  I would also test to see if it's specific to VSCode or if it happens in upstream projects too (e.g.: electron and chromium).

This issue is vscode-specific, but it's a type of issue that all wayland clients have had at some point: heterogeneous scaling requires special handling by the code that manages the wayland surfaces. Here, vscode is managing its own surface, and isn't calling `wl_surface.set_buffer_scale` at the correct times/with the correct values.

**Comment by edrex** [comment] 2022-07-05 22:59
@cbrnr I have definitely seen rendering at the wrong resolution when moving a window between outputs with other Electron apps, and even occasionally still with Chromium. There are other electron apps, such as Obsidian, which show no resolution issues in the current version. I don't know the root cause, but i would guess that either:

 - Obsidian and other apps that work are tracking the relevant events and triggering a refresh intentionally
 - They are calling something frequently or at the right moment that as an unintended side effect is triggering a refresh in Chrome.

**Comment by cbrnr** [comment] 2022-07-06 07:06
Then this works better with your setup than mine. Electron apps are always blurry, even after switching scale. Obsidian is no exception, it's blurry like all the others. I use GNOME with Wayland and the latest NVIDIA binary drivers on Arch Linux.

Where would the right place to report this issue be? It seems like there's nothing VS Code devs can do here (other than point us to the relevant upstream project).

**Comment by sedax90** [comment] 2022-07-11 07:13
Version 1.69.0 still has the problem... Why is so difficult to implement?

**Comment by cbrnr** [comment] 2022-07-11 10:01
As discussed in previous comments, it seems like support for Wayland needs to be either specifically enabled on a per-app basis. For example, the following command works for Chrome and gets rid of all blurriness:

```
google-chrome-stable --ozone-platform-hint=auto
```

Visual Studio code has a different flag:

```
code --ozone-platform=wayland
```

Indeed, this fixes the blurry rendering, but it also gets rid of the window decorations... However, setting `"window.titleBarStyle": "custom"` in the VS Code settings works. So I guess this is fine for me.

In other apps, such as Signal, the `--ozone-platform=wayland` flag also fixes the blurriness, but there is no option to enable custom window decorations (I think), so this is not really an ideal fix.

**Comment by edrex** [comment] 2022-07-11 17:22
@cbrnr the `--ozone-platform=wayland` flag is necessary in order for vscode to act as a native wayland client - otherwise it acts as an X11 client, which indeed results in issues for mixed resolution displays, but that isn't what this issue is about. This is about blurry rendering with native wayland rendering.

**Comment by cbrnr** [comment] 2022-07-11 17:35
Are you sure that's what the issue is about? I reread the OP and it doesn't mention that this is specific to Wayland. I think there might be several different issues being mixed up here.

**Comment by edrex** [comment] 2022-07-11 19:42
@cbrnr from the first few comments:

>@LennyPenny are you using Wayland on Fedora 30 by any chance? I'm guessing you are as I believe Gnome 3.32 fractional scaling is only available on Wayland. Anything that has to use XWayland (which I think includes current Chromium) ends up blurry as it's not using optimal scaling compared to toolkits like Gtk and Qt that have native Wayland support.
> @carwyn yes, gnome fractional scaling is wayland only, which I am using

**Comment by edrex** [comment] 2022-07-11 21:35
yes and the point is this issue isn't about xwayland, and we're just blowing up the thread with OT comments.

**Comment by cbrnr** [comment] 2022-07-12 05:21
@edrex I read the whole thread again, and to me it seems like you (and some others) are having a different problem (crisp menu text, blurry UI). This is not what the OP reported, and many others (including me) could solve their blurry VS Code with the CLI flags (although this is still not working by default, which it should, and I couldn't get the app icon to show up, and GPU drivers seem to play a role as well).

Maybe it would be a good idea to create a new issue on what you're seeing? If you want, I can also open a new issue on providing a setting to switch to Wayland, fix the icon, and maybe do that by default on Wayland. But again, I believe that the *original* issue is more or less fixed, and you are reporting a new (different) one.

**Comment by edrex** [comment] 2022-07-12 05:42
@cbrnr rereading the thread carefully, I see you are right. The original report is from well before Wayland suppport landed in Electron, and instead it's about when running under xwayland. 

The issue I'm seeing seems to be that windows aren't updated with the current output scale: dis+enabling the hidpi display with blurry vscode windows crisps them up. I'm not ready to file but someone can feel free to, or link an upstream issue here.

**Comment by cbrnr** [comment] 2022-07-12 07:17
To summarize the fix and remaining issues (VS Code devs might want to follow up, @deepak1556 maybe?):

- VS Code does not support Wayland out of the box. This leads to blurry UI for scalings ≠ 1 (so even integers scalings like 2 are problematic).
- Wayland support must be manually enabled with the command line argument `--ozone-platform=wayland`.
- Using Wayland, native window decorations are not rendered, so the `"window.titleBarStyle": "custom"` setting in VS Code has to be enabled.
- Unfortunately, the app icon is not rendered anymore (at least on GNOME). This needs to be fixed.
- If the icon issue is fixed, I think Wayland support should be enabled by default when running on Wayland.

**Comment by sedax90** [comment] 2022-07-15 11:51
@cbrnr this pr is locked until 2021 https://github.com/microsoft/vscode/pull/135191 and it should solve all the problems. How can we improve it?

**Comment by cbrnr** [comment] 2022-07-15 12:23
Yes, #135191 should fix most problems. Like I said, I think it would be nice if Wayland was enabled by default if running on Wayland. The only remaining issue I see is the missing app icon, but maybe this is just an artifact of the flags that are not properly integrated now. Is anything still missing in this PR?

**Comment by kumibrr** [comment] 2022-08-16 09:46
> The only way I could fix this is by changing any of the displays' scale. The text will render clear, and then I revert that change and stays clear.
> 
> It's not optimal because anytime I open a new vscode window I have to do that scale thing again.

Just got back from vacation and this solution stopped working with my monitor setup. I have two monitors, my main 4K display (150% scale) and a 1080p secondary (100% scale). The only way I could solve this is by setting my 1080p scale to 125%.

**Comment by ashishlotake** [comment] 2022-09-21 04:59
I found a work around,
1. copy the `code.desktop`, `cp /usr/share/applications/code.desktop ~/.local/share/applications`
2. edit `Exec=/usr/share/code/code --ozone-platform=wayland --unity-launch %F`,  my [code.desktop file](https://pastebin.com/GDt90mkf)
3. This will make sure that vscode launch via wayland from desktop launcher icon, you won't get blurry screen 
4. next add this line `alias code='code --ozone-platform=wayland'` to your `~/.zshrc` or `~/.bashrc` file.This will ensure that when your run `code` or `code .` command from terminal, wayland is used, and won't get blurry screen.
5. Restart, cause sometime log out doesn't work

**Comment by sedax90** [comment] 2022-09-22 08:35
> I found a work around,
> 
> 1. copy the `code.desktop`, `cp /usr/share/applications/code.desktop ~/.local/share/applications`
> 2. edit `Exec=/usr/share/code/code --ozone-platform=wayland --unity-launch %F`,  my [code.desktop file](https://pastebin.com/GDt90mkf)
> 3. This will make sure that vscode launch via wayland from desktop launcher icon, you won't get blurry screen
> 4. next add this line `alias code='code --ozone-platform=wayland'` to your `~/.zshrc` or `~/.bashrc` file.This will ensure that when your run `code` or `code .` command from terminal, wayland is used, and won't get blurry screen.
> 5. Restart, cause sometime log out doesn't work
> 6. You may not see vscode window title bar, so go to setting in vscode, and set the `"Window: Title Bar Style": "custom"`

does not work with ubuntu 22.04

**Comment by ashishlotake** [comment] 2022-09-25 04:57
i am using fedora 36, try launching vscode from terminal, using `code . --enable-features=UseOzonePlatform --ozone-platform=wayland`.
And also check the .desktop file directory,

**Comment by v-tibi** [comment] 2022-10-19 07:37
There's a strange bug which does not happen with other electron apps. When I use a second screen and it is positioned above the primary screen, even if I use the Wayland flag, text is blurry until I reload the window or disable then enable 2nd screen.

**Comment by andrsbtrg** [comment] 2022-10-21 17:36
> I found a work around,
> 
>     1. copy the `code.desktop`, `cp /usr/share/applications/code.desktop ~/.local/share/applications`
> 
>     2. edit `Exec=/usr/share/code/code --ozone-platform=wayland --unity-launch %F`,  my [code.desktop file](https://pastebin.com/GDt90mkf)
> 
>     3. This will make sure that vscode launch via wayland from desktop launcher icon, you won't get blurry screen
> 
>     4. next add this line `alias code='code --ozone-platform=wayland'` to your `~/.zshrc` or `~/.bashrc` file.This will ensure that when your run `code` or `code .` command from terminal, wayland is used, and won't get blurry screen.
> 
>     5. Restart, cause sometime log out doesn't work
> 
>     6. You may not see vscode window title bar, so go to setting in vscode, and set the `"Window: Title Bar Style": "custom"`

This worked for me but opening via terminal or app drawer launches 'Visual Studio Code - URL Handler' instead:
![image](https://user-images.githubusercontent.com/63083862/197255804-201c89d1-17c8-4ea5-bddc-5de1fb3bdff7.png)

**Comment by deepak1556** [comment] 2022-12-12 14:57
@cbrnr thanks for summarizing the issue thread in https://github.com/microsoft/vscode/issues/72759#issuecomment-1181405397. Wayland support is available in the runtime and as mentioned in this issue thread multiple time, it can be enabled either with

```
--ozone-platform=wayland

or

--ozone-platform-hint=auto
```

We cannot add `--ozone-platform-hint=auto` as default at this time since it is not the default even for [Chrome](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/about_flags.cc;l=406-417). Hopefully it will be the right default in the Electron runtime moving forward.

Also, known [wayland issues](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Awayland) in VSCode are tracked in this repo. If there is a issue missing for something you encountered with latest version of VSCode, please file one with repro steps. Thanks for understanding.

**Closed by deepak1556** 2022-12-12 14:57 UTC
Labels: upstream, electron, workbench-electron, upstream-issue-linked

**Comment by cbrnr** [comment] 2022-12-12 16:55
The duplicate app icon and the missing drop shadow issues should also be fixed before Wayland becomes the default. Are these issues already tracked or should I open new issues?

Chrome at least has a setting to enable Wayland (as opposed to a command line flag), and it doesn't have the duplicate icon issue. Maybe something to consider?

**Comment by darkbasic** [comment] 2022-12-13 09:44
Arch Linux has a setting to enable Wayland on Electron apps as well, it's just a matter of how you package Electron.

**Comment by pstorozenko** [comment] 2022-12-13 12:34
I'm working under Ubuntu 22.04.1 with Gnome 42.5 and VSCode 1.74.0.
If I run in terminal any of
```
code --enable-ozone --ozone-platform=wayland
code --enable-ozone --ozone-platform=auto
code --enable-features=UseOzonePlatfom --ozone-platform=wayland
code --enable-features=UseOzonePlatfom --ozone-platform=auto
```
nothing happens, i.e., no window appears, no errors displayed in the terminal.

If I run just `code --enable-ozone` VS Code starts normally, but is blurred.
Any ideas why vscode doesn't start with those flags?

**Comment by cbrnr** [comment] 2022-12-13 12:57
@pstorozenko are you sure you are running Wayland and not X.org?

**Comment by pstorozenko** [comment] 2022-12-13 13:02
I think so 
![image](https://user-images.githubusercontent.com/9080845/207325111-690bd23a-3c85-4336-929f-6f61027e60ec.png)

**Comment by deepak1556** [comment] 2022-12-14 06:38
@cbrnr the app icon issue is tracked in https://github.com/microsoft/vscode/issues/129953

**Comment by v-tibi** [comment] 2022-12-21 11:18
I still have to reload the window as in this previous  [comment:](https://github.com/microsoft/vscode/issues/72759#issuecomment-1283564330l)

**Comment by pstorozenko** [comment] 2022-12-28 07:14
I (somehow) solved the problem!

**For some reason I had to remove vscode installation from `snap` and install it through `deb` file.** Then flag ` --ozone-platform=wayland` worked without problems.
 
When I run `code-insiders --ozone-platform=wayland --verbose` (the error is the same as with `code`, I have `code-insiders` still installed through `snap`) I get the following errors:
```
[1228/080651.090038:ERROR:http_transport_libcurl.cc(118)] dlopen:/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcurl.so)
[1228/080651.090070:ERROR:http_transport_libcurl.cc(118)] dlopen:/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
[1228/080651.090083:ERROR:http_transport_libcurl.cc(118)] dlopen:/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcurl-nss.so.4)
[1228/080651.090093:ERROR:http_transport_libcurl.cc(118)] dlopen:/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcurl.so.4)
```
Of course I have glibc installed on my machine, but the `code` installed by `snap` couldn't see it.

The same _solution_ helped with the `slack` electron application.
So the issue is still there somewhere, but I hope it will be useful for someone.

**Comment by LilXhan** [comment] 2023-01-21 01:28
same problem in fedora look:
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
help me :(

**Comment by BBaoVanC** [comment] 2023-01-21 01:59
> There's a strange bug which does not happen with other electron apps. When I use a second screen and it is positioned above the primary screen, even if I use the Wayland flag, text is blurry until I reload the window or disable then enable 2nd screen. Flag work fine if 2nd screen is in default position.

I'm getting this same issue, I'm on sway (wayland) but my two monitors are just side by side. Neither is primary because that's not a thing in wayland
