### ISSUE TITLE
add cloud account and sync plus

### ISSUE THREAD

**Issue by MephistoSun** [Microsoft/vscode#34918] opened 2017-09-25 02:14 UTC
please add cloud account and login account vscode sync plus

**Comment by yume-chan** [comment] 2017-09-25 04:59
Duplicate of #2743

Multiple developers of Code had suggested the [CodeSync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extensions.

**Comment by sandy081** [comment] 2017-09-25 14:01
@MephistoSun Is your request similar to #2743

**Closed** 2017-10-02 14:51 UTC
Labels: needs more info
