### ISSUE TITLE
Snippet wont appear after restart

### ISSUE THREAD

**Issue by nbaghm** [Microsoft/vscode#33811] opened 2017-09-04 17:50 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
php-formatter|Sop|0.2.4
jupyter|don|1.1.3
python|don|0.7.0
php-cs-fixer|jun|0.1.39
ci-snippets|sec|0.0.2
php-ci|sma|0.2.2

---

Steps to Reproduce:
I have an issues with Visual Studio Code, I add a new snippet to html, as below,
`	"php tags in html":{
		"prefix": "php",
		"body": ["<?php $1;?>"],
		"description": "print php tag in html"
	}`
When I test it it work perfectly, however when the app is restarted, it wont appear in editor when I enter php., however when the app restarted, it wont work. To make it work again I should open the html snippet, and make a change, anything like adding a space, and save it again, it work again, but when the app restart it wont work again.

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-09-04 18:04
Are you using it in a php file or html?

**Comment by nbaghm** [comment] 2017-09-04 18:28
I added to php i did not work, so I added it to html it worked.

**Comment by roblourens** [comment] 2017-09-04 20:25
I don't understand. The snippet is in your html snippets - are you trying to use the snippet in an html file or a php file?

**Comment by nbaghm** [comment] 2017-09-04 21:06
I added it to html snippet, to use it in a .php file. the .php file is view, contains many html tags. i wanted to create a sinppet to print php tag , <?php ?>.

The reason I put it in html snippet is the snippet did not work when I put it in php snippet..

**Comment by roblourens** [comment] 2017-09-04 21:12
html snippets should show up in the file if you are outside a `<?php ?>` tag. If you are inside that tag, then PHP snippets should show up.

**Comment by nbaghm** [comment] 2017-09-04 21:16
Yes that is true, and it works well, but when I close the app and open it again it won't work, unless I open the html snippet,make some changes,and save it again, and the snippet appears..

**Comment by roblourens** [comment] 2017-09-04 21:34
Is there any way you can record a gif of this process to make sure I understand?

**Comment by jrieken** [comment] 2017-09-05 07:33
Could be a dupe of #33158. @nbaghm does the snippet show up when you use `F1 > Insert Snippet` in a HTML file or in a PHP file? Iff so in which does it show up?

**Comment by nbaghm** [comment] 2017-09-05 08:42
![2017-09-05-111744_1366x768_scrot](https://user-images.githubusercontent.com/4522358/30052467-37d0b0de-922e-11e7-9d60-5b208ebac96d.png)
the snippet wont appear.
![2017-09-05-111818_1366x768_scrot](https://user-images.githubusercontent.com/4522358/30052481-42685178-922e-11e7-81b8-5f43d37acbec.png)
I must open the html snippet, and make some changes like adding a space, and saced it again.
![2017-09-05-111924_1366x768_scrot](https://user-images.githubusercontent.com/4522358/30052485-46587934-922e-11e7-8ecd-9ada247ba63d.png)
Then the snippet will appear again.
![2017-09-05-111934_1366x768_scrot](https://user-images.githubusercontent.com/4522358/30052490-49a5b322-922e-11e7-8ed7-e254c6f6e955.png)
However, I must do this every time I close the app and open it again.

**Comment by jrieken** [comment] 2017-09-05 08:52
Ok, thanks. This is a duplicate of #33158

**Closed by jrieken** 2017-09-05 08:52 UTC
Labels: needs more info, new release, php, snippets

**Comment by nbaghm** [comment] 2017-09-05 16:38
@jrieken  nothing happens when I use `F1 > insert snippet`.
it is very weird that it is only works when I open the snippet file again and make some changes, anything, and save it again, it works without any problem. BUT it wont work when I close the app and open it again. I need to do same process again to work.
