### ISSUE TITLE
When openFiles and openFolders are both true, everything is pickable

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#35193] opened 2017-09-27 00:11 UTC
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34821.

When openFIles and openFolders are both set to true, both files / folders are pickable.

This is the same behavior as when both are false. One of them should error out I think.

Maybe a better approach is to rename the two options to showFiles and showFolders, both default to true.

Both true -> show all
Only showFiles false -> show folders only, similarly for showFolders
When both are false -> error out

And currently the word "open" is overloaded with two different meanings in the API, as openLabel and openFiles are totally different. Might cause some confusion.

**Comment by jrieken** [comment] 2017-09-27 07:41
> When openFIles and openFolders are both set to true, both files / folders are pickable.

That's the idea/design

> This is the same behavior as when both are false. One of them should error out I think.

That's not the design... If both are false we fallback to open files

```ts
		if (!options.openFiles && !options.openFolders) {
			options.openFiles = true;
		}
```

**Comment by jrieken** [comment] 2017-09-27 10:39
> This is the same behavior as when both are false. One of them should error out I think.

I cannot reproduce that.

**Comment by jrieken** [comment] 2017-09-27 12:50
Closing this as with #35141 this can been clarified. The idea is to allow both, the options have been renamed to `canSelectFiles` (defaults to true) and `canSelectFolder` (default to false).

**Comment by jrieken** [comment] 2017-09-27 12:50
closing as dupe of #35141

**Closed by jrieken** 2017-09-27 12:50 UTC
Labels: api, needs more info
