### ISSUE TITLE
Git - diff textconv is broken on unstaged changes

### ISSUE THREAD

**Issue by Quadrubo** [microsoft/vscode#227201] opened 2024-08-30 11:57 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.91.0
- OS Version: NixOS 24.05 Stable

I'm using ansible vault files and the diffs are broken in unstaged changes only.

For ansible vault files, I'm using this `.gitattributes` config to make sure the diffs are clean when re encrypting a file with the same content twice.

```
vault.yml diff=ansible-vault merge=binary
```

```
diff.ansible-vault.textconv = "ansible-vault view";
```

However VsCode only seems to support this when staging the changes, not when the changes are unstaged. To me this seems to be a bug.

Screenshot unstaged:

![image](https://github.com/user-attachments/assets/01efb910-3b85-4405-b6e7-b17909f22d18)

Screenshot staged:

![image](https://github.com/user-attachments/assets/5aa00fb3-0274-420c-8d1e-9292547335e0)

The file also shows up as modified even though there haven't been any changes when using the diff strategy defined in the .gitattributes file.

Git Diff doesn't have this problem.

**Comment by Quadrubo** [comment] 2024-09-01 11:25
> The latest stable release is 1.92.2. Please try upgrading to the latest version and checking whether this issue remains.

The issue remains on the latest version.

**Comment by Teufeuleu** [comment] 2024-11-27 22:53
Still happening in 1.95.3.
My use case is using Ableton's [maxdiff](https://github.com/Ableton/maxdevtools/tree/main/maxdiff) to show meaningful diffs for Cycling 74 Max patchers (which are essentially JSON files). It works well on staged and commited changes, but unstaged changes takes forever to open (or sometimes never do, for bigger ones), and only the old (left) version of the file has the textconv applied.

**Comment by lszomoru** [comment] 2024-12-12 12:30
Closing as duplicate of [#206612](https://github.com/microsoft/vscode/issues/206612)

**Closed by lszomoru** 2024-12-12 12:30 UTC
Labels: bug, git

**Comment by Quadrubo** [comment] 2024-12-16 13:25
I don't see how this is not just a bug but fine if the feature request is being looked at.
