### ISSUE TITLE
Changing extensions publisher resulted in it disappearing/being uninstalled for some users

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#41894] opened 2018-01-20 07:25 UTC
Yesterday the extension `dart-code` was transferred from the publisher `DanTup` to one named `Dart-Code` by the marketplace team. It was understood that existing users wouldn't be impacted, but it seems like there may be some issues here.

After the transfer was complete, I opened up VS Code on my MacBook and then the extensions list to see how it displayed and noticed that Dart Code had completely vanished from the installed extensions list. I opened a Dart project and it had no highlgihting, etc.

I tried it on my Windows desktop and everything was fine; the upgrade was seamless. A few other people confirmed it also upgraded fine for them (though one reported seeing both extensions for a period and had to restart 3 times for it to fix itself).

I assumed something was just wonky about my MacBook (it's where I dev the extension, so maybe there's something unusual), however another user reported the same thing overnight:

> Weird issue, I'm not sure if it's from dart-code itself or vscode:
> I just closed a folder that had a flutter project [ctrl+k f], opened a [non-flutter] dart project, and dart-code wasn't being detected by vscode anymore.
> It wouldn't show up in the list of installed extensions, restarting vscode didn't make a difference, searching for the extension and installing it again worked fine.
> Can't reproduce this, but I just thought I'd mention it in case someone has seen it before as well.

I don't know how many people have had this (hopefully not many) and I suspect you'll struggle to repro, but it seems like there may be an issue to investigate.

At the time, I think my MacBook was on the latest Code (January) and my PC was on the previous version.

**Comment by DanTup** [comment] 2018-01-23 03:56
How do I find the local extensions folder? I have since installed the extension, so I'm not sure looking there will help?

What happened was:

- I had `DanTup.dart-code` installed from Marketplace
- `DanTup.dart-code` was changed to `Dart-Code.dart-code` by marketplace team
- I opened VS Code and clicked the extensions tab (to check that the extension appeared with the new metadata)
- However, extension was not listed at all
- Restarted VS Code several times; no change
- Tried opening a Dart project - no language integration
- Manually installed the new `Dart-Code.dart-code` and everything back to normal

We think that for most users the rename actually worked fine (and it did on my PC). However since at least one other user has reported the same issue as me (the extension just disappeared and needed installing again) I think something is wrong. For me, the issue was on Mac OS and for this other user it was Linux.

**Comment by sandy081** [comment] 2018-01-25 17:33
@DanTup You can use following command to open the folder where extensions are installed

![image](https://user-images.githubusercontent.com/10746682/35402509-1a46bbb4-01fd-11e8-8da8-a0d134004c86.png)

We read all extensions from the extensions installed folder and show all of them unless user uninstalled the extension.

Above flow is a very trivial case which should not have issues with rename. I am sorry that I am not helpful here and I am also not able to reproduce this from my side.

Will close this as there is no action can be done without more information. I will reopen it if I come across such issue again and is able to reproduce.

**Closed by sandy081** 2018-01-25 17:33 UTC
Labels: extensions, needs more info

**Comment by DanTup** [comment] 2018-01-28 19:57
@sandy081 I understand it's hard to proceed based on this info; but I am 100% positive I did not uninstall the extension (and the fact that another user reported the exact same issue on the same day seems to reinforce that something is not right).

It's not likely to affect me again so it's not something of great concern but I thought it was worth providing info in case you wish to investigate and/or others see it in future and can add more info to the case.

**Comment by sandy081** [comment] 2018-01-29 17:19
@DanTup I really appreciate you brought it to me. Thanks a lot.

I will revisit this if I get any other hunch or similar issue reported (hoping for consistent steps to repro).

**Comment by DanTup** [comment] 2018-02-08 14:15
@sandy081 I think this may be unrelated to the publisher change - I saw someone else complaining about this in your Gitter a while back, and I saw #42945 and also today someone @xqwzts reported this to me:

> @DanTup I saw the dissapearing dart-code extension issue from a while ago again. It's... weird:
open vscode before a dart-code update is pushed [it was open for a day or two I guess]
> - don't update dart-code
> - open a new window: ctrl+shift+n
> - new window is missing dart-code extension
> - switch to original window: it shows the update/reload button on dart-code
> 
> iirc last time, I didn't switch back to the original window [pretty sure I had closed it] so my only option was to re-install dart-code, since any new windows don't see the extension there.
> 
> This time I alt-tabbed back in and was able to update in the first window

Interestingly, I had a version of Code open in the background at the time we renamed the publisher - possibly there's something going on there?

**Comment by DanTup** [comment] 2018-02-21 08:47
I've just seen it again - I installed a beta version of my extension from a vsix for testing and a few mins later closed Code. When I next opened it I saw "Marketplace has extensions for dart files" so I opened up extensions list and my vsix version of Dart Code has gone.

**Comment by sandy081** [comment] 2018-02-21 16:56
@DanTup Are you able to reproduce it again by following the steps you mentioned? Is it possible to get the logs (shared process) from the sessions when you saw the extension is not appearing and the one before it? You can get the logs of previous sessions by opening logs folder `Developer: Open Logs Folder`

**Comment by DanTup** [comment] 2018-02-26 11:41
No luck reproducing so far :(

**Comment by DanTup** [comment] 2018-03-05 10:29
@sandy081 Just seen this again :(

I created a beta version of my extension as a vsix and uploaded to GitHub. I then installed it myself locally from vsix - it prompted me "this version is older" (because I already have -dev installed and this was -beta.1). I said yes and it installed. I closed Code. 10 mins later I opened Code and Dart Code is missing.

I've checked the logs and there's no mention of Dart Code in any of the log files (I guess they are recreated on startup and the extension was already gone?).

**Comment by sandy081** [comment] 2018-03-05 14:55
@DanTup I have added logs few weeks back and they are available in insiders and for 1.21 release. 

You can see the previous logs by opening the logs folder `Developer: Open Logs Folder`

**Comment by DanTup** [comment] 2018-03-05 15:11
@sandy081 Aha, sounds good. Am I right in thinking 1.21 is due soon? I'll be sure to get logs if I see it after the upgrade (my use of Insiders is fairly sporadic as I tend to use Stable to see my extension as my users will).

**Comment by sandy081** [comment] 2018-03-06 09:51
@DanTup 1.21 is planned to release this week.

**Comment by DanTup** [comment] 2018-03-09 07:54
Oh, just saw this comment, maybe it's the reason?

https://github.com/Microsoft/vscode/issues/45111#issuecomment-371001505
