### ISSUE TITLE
When I use chinese input method write comments in code. The input method box will keep jumping!

### ISSUE THREAD

**Issue by Ha0ran2001** [microsoft/vscode#145188] opened 2022-03-16 07:06 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows_NT x64 10.0.22000
- My OS Version: Windows 11 Family Chinese Version 21H2

Steps to Reproduce:
![QQ录屏20220316150540](https://user-images.githubusercontent.com/73927445/158535514-ad3219da-90fb-431b-a8e6-85bb44c8442d.gif)

**Comment by Ha0ran2001** [comment] 2022-03-18 11:12
When I uninstalled completely, including all the plugins, and redownloaded it, there was no problem.

**Comment by hediet** [comment] 2022-03-18 11:24
If you cannot reproduce this issue anymore, can we close it then?

**Closed** 2022-03-18 16:16 UTC
