### ISSUE TITLE
window.newWindowDimensions maximized not working

### ISSUE THREAD

**Issue by gianlucaborello** [Microsoft/vscode#66166] opened 2019-01-07 19:36 UTC
- VSCode Version: Version 1.31.0-insider (1.31.0-insider)
- OS Version: Mac OS Mojave

This behavior started a couple Insider releases ago. I have `"window.newWindowDimensions": "maximized"`, but if I start the editor from scratch, the window is not maximized anymore, it's resized at a distance of about 50 pixels from the bottom and from the right, forcing me to manually maximize it every time I start the program.

I don't have any external monitor or anything particular in my setup, just the standard laptop display, and this definitely used to work before.

These are my related settings:

```
        "window.nativeTabs": true,
        "window.newWindowDimensions": "maximized",
        "window.openFoldersInNewWindow": "on",
        "window.restoreWindows": "all",
        "window.zoomLevel": 0,
```

**Comment by gianlucaborello** [comment] 2019-01-07 19:51
This is the behavior, as you can see the window is not maximized upon start:

![image](https://user-images.githubusercontent.com/4187028/50789989-88128e80-1272-11e9-9d84-5353b291bad4.png)

**Comment by RMacfarlane** [comment] 2019-01-07 22:22
Looks like this is a duplicate of https://github.com/Microsoft/vscode/issues/65280

**Closed by RMacfarlane** 2019-01-07 22:22 UTC
