### ISSUE TITLE
Could not install typings file for JavaScript language features. Please ensure that NPM is installed and is in your PATH

### ISSUE THREAD

**Issue by balupton** [Microsoft/vscode#26896] opened 2017-05-18 23:57 UTC
- VSCode Version: 1.12.2
- OS Version: mac 10.12.5

Steps to Reproduce:

Open vscode, wait a while, get the error message in the title.

I use a the fish shell with nvm, so npm isn't available in my path until I run `npm`, `node`, or `nvm`. I've setup a script at `~/bin/npm` to work around this, but no way to specify vscode to use it, as that is a custom path that my dotfiles adds.

---

If vscode uses node, it may benefit from [safeps](https://github.com/bevry/safeps/blob/0e7cff711aeea93bafbf5d35869dd9c1271226c9/source/index.js#L1075-L1140) which has code in there to determine an executables path across many different environments.

**Comment by romulof** [comment] 2017-05-22 22:01
Same problem here.
VS Code is not properly initializing shell to retrieve PATH env var.

**Comment by mjbvz** [comment] 2017-05-23 00:19
This is a duplicate of #24961.

Can you please try the latest insiders build. I've added a debug message to see if `npm` is on the path. Just open a ts/js file and then go to the `TypeScript` section of the output window. There should be a message like this at the top:

![screen shot 2017-05-22 at 5 17 45 pm](https://cloud.githubusercontent.com/assets/12821956/26333460/b653e260-3f12-11e7-9c03-e31e5d674f4a.png)

For VSCode 1.13, we are planning to allow you to explicitly configure the path to npm. We are also exploring removing the dependency on npm entirely in the future

**Comment by balupton** [comment] 2017-05-25 01:42
```
[Info  - 9:40:38 AM] Using tsserver from: /Users/balupton/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:40:38 AM] Forking TSServer
PATH: /usr/bin:/bin:/usr/sbin:/sbin
```

![screen shot 2017-05-25 at 9 41 34 am](https://cloud.githubusercontent.com/assets/61148/26432432/64f6d8aa-412e-11e7-8585-669cfb293196.png)

---

```
> echo $PATH
/Users/balupton/bin /Users/balupton/.cache/gems/bin /Users/balupton/.homebrew/bin /Users/ba
lupton/.scripts/commands /usr/local/bin /usr/bin /bin /usr/sbin /sbin
>
```
![screen shot 2017-05-25 at 9 42 09 am](https://cloud.githubusercontent.com/assets/61148/26432446/7db59c96-412e-11e7-9f6f-61cef1ffd533.png)

**Comment by balupton** [comment] 2017-05-25 01:45
As I use nvm, here is the path:

```
> which npm
/Users/balupton/.nvm/versions/node/v4.4.6/bin/npm
```

```
> which node
/Users/balupton/.nvm/versions/node/v4.4.6/bin/node
```

My shell loads them to the path when they are called:

```
> echo $PATH
/Users/balupton/.nvm/versions/node/v4.4.6/bin /Users/balupton/bin /Users/balupton/.cache/gems/bin /Users/balupton/.homebrew/bin /Users/balupton/.scripts/commands /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

However, as I've said in the original post, I've also added symlinks at `$HOME/bin` for them.

**Comment by mjbvz** [comment] 2017-05-26 20:47
@balupton Thanks. Yes it looks like we don't have the correct PATH when starting the TS server.

The PATH you see in the TSServer trace is the path that vscode has picked up from the environment when VSCode was started.  @joaomoreno may be able to clarify this but I believe VSCode gets the environment from your login shell (such as `.bash_profile). In your case, the VSCode detected environment does not match the terminal environment

One possible fix is to make sure the nvm environment is setup in the login shell too. You can also do a global install of npm so that TypeScript can find some npm to use for typings acquisition

On our side, we are going to add a setting so that you can explicitly say where npm is installed on your system. Longer term, we are also looking to remove the dependency on npm entirely.

Closing as a duplicate of #24961

**Closed by mjbvz** 2017-05-26 20:47 UTC
Labels: duplicate, javascript

**Comment by romulof** [comment] 2017-05-27 01:07
The problem is that VSCode is having problems detecting fish environment.
My fish equivalent to `.bash_profile` init NVM (and other stuff) that adds more paths to PATH envvar, but VSCode is showing just the default ones.

**Comment by balupton** [comment] 2017-05-27 01:30
> My fish equivalent to .bash_profile init NVM (and other stuff) that adds more paths to PATH envvar, but VSCode is showing just the default ones.

Not having the same issue, as my custom fish path stuff was detected by VSCode. Just not NVM, as I don't want the 1 second delay every time I start a script, that a `nvm use` in my dotfiles does.

These are the files in my dotfiles setup for path setting:

- https://github.com/balupton/dotfiles/blob/08b639ca26482691749f002ec6c7215f707897db/.scripts/init.fish#L6-L12
- https://github.com/balupton/dotfiles/blob/08b639ca26482691749f002ec6c7215f707897db/.scripts/commands/paths_commands
- https://github.com/balupton/dotfiles/blob/08b639ca26482691749f002ec6c7215f707897db/.scripts/sources/var.fish

**Comment by balupton** [comment] 2017-05-27 01:32
> On our side, we are going to add a setting so that you can explicitly say where npm is installed on your system. Longer term, we are also looking to remove the dependency on npm entirely.

Cool. I'll wait for that then. As I don't want nvm being active at shell load time, as that is a 1 second delay every time a login shell starts.

**Comment by romulof** [comment] 2017-06-12 18:25
The latest release has fixed this for me. Thanks!

**Comment by akresiliocom** [comment] 2017-08-02 07:20
VSCode Version: 1.13, VSCode Version: 1.14.2 same problem if use NVM.
Could not install typings files for JavaScript language features. Please ensure that NPM is installed or configure 'typescript.npm' in your user settings

**Comment by volosovich** [comment] 2017-09-06 09:12
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

I use the NVM
Have the same problem

**Comment by Hyzeta** [comment] 2017-10-05 16:53
I think the reason that the reason this problem occurred was that the application on Mac cannot read the bash setting such as .bash_profile and .bashrc properly. It reminds me that we got the same issue on Sublime Text on macOS that the application cannot get the correct bash settings.

**Comment by miqmago** [comment] 2017-10-17 18:17
Same problem here.
- vscode: 1.17.1
- osx 10.12.6
- node 7.8.0

I've specified the path in user settings but the problem persists. Tried with different options (don't really know what should I specify...):

```json
{
    "typescript.npm": "/Users/<user>/.nvm/versions/node/v7.8.0/bin",
    "typescript.npm": "/Users/<user>/.nvm/versions/node/v7.8.0/bin/npm",
    "typescript.npm": "/Users/<user>/.nvm/versions/node/v7.8.0/lib/node_modules/typescript/bin",
    "typescript.npm": "/Users/<user>/.nvm/versions/node/v7.8.0/lib/node_modules/typescript/bin/tsc",
}
```

**Comment by Robert-at-GE** [comment] 2017-10-24 14:10
Same problem here.
- vscode: 1.17.2
- Windows 10 Pro (64bit)

I installed: 
- node v6.11.4
- npm 3.10.10

I tried specifying the path in user settings to npm executable:
      "typescript.npm": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin",

and then tried pathname of the npm executable (although that just is a script):
      "typescript.npm": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm.cmd",

No change to symptoms.

Visual Studio Code reports (in Help dialog):
Node 7.9.0

Visual Studio Code reports (in OUTPUT window)
[Info  - 8:55:20 AM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 8:55:20 AM] Forking TSServer
PATH: C:\Users\212023874\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\IBM\RationalSDLC\common;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\Perforce;C:\Program Files\Perforce\DVCS\;C:\Program Files\PuTTY\;C:\Program Files\Collaborator Client;C:\Program Files (x86)\IBM\RationalSDLC\common;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\bin;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\bin;C:\Program Files (x86)\IBM\gsk8\lib;C:\Program Files (x86)\IBM\gsk8\bin;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\RemoteClient\cteapis;C:\bin;C:\Program Files\nodejs\;C:\Users\212023874\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin

Visual Studio Reports: (In "Warn" message)
Could not install typings files for JavaScript language features. Please ensure that NPM is installed or configure 'typescript.npm' in your user settings
