### ISSUE TITLE
Word Wrap feature not working

### ISSUE THREAD

**Issue by ToniSHernandez** [microsoft/vscode#108326] opened 2020-10-08 16:46 UTC
Issue Type: <b>Bug</b>

I attempted to use [alt]Z and [alt]z tp get word wrap to work.  When this failed, I clecked on View > Toggle Word Wrap.  In either situation, the feature did not work.  

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.09GB free)|
|Process Argv|--crash-reporter-id 470139ae-9e22-47f5-9264-1f8c13641922|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
beautify-blade|api|1.0.1
es7-react-js-snippets|dsz|3.0.0
vscode-npm-script|eg2|0.3.13
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.8
vue-snippets|hol|0.1.12
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-wsl|ms-|0.44.5
debugger-for-chrome|msj|4.12.11
vetur|oct|0.28.0
laravel-blade|one|1.24.0
vue-beautify|pea|2.0.4
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.2
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
eno|Wsc|2.3.20
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-10-08 16:58
Does the problem also happen after you run the Command Palette command to reload with all extensions disabled?

**Comment by DarkLite1** [comment] 2020-10-12 06:48
We're having the same issue, not all files will wrap their text at 80 characters but some do. Triggering a reload of the window, `ALT` + `Z` or something else does not wrap the text either.

**User settings:**

![image](https://user-images.githubusercontent.com/10828570/95713416-cb2f3c00-0c66-11eb-8230-e671bbbb91da.png)

**Workspace settings:**

![image](https://user-images.githubusercontent.com/10828570/95713728-527caf80-0c67-11eb-8b2a-2c9087d2c5a7.png)
=

Both  `User\Settings.json` and `project.code-workspace.json` show ``"editor.wordWrap": "wordWrapColumn"` but not the value `80`.

**project.code-workspace.json**
```json
{
	"folders": [
		{
			"path": "PowerShell"
		},
		{
			"path": "T:\\Prod"
		},
		{
			"path": "C:\\Program Files\\WindowsPowerShell\\Modules"
		}
	],
	"settings": {
		"editor.wordWrap": "wordWrapColumn"
	}
}
```

The thing I've noticed is that wrapping only works in the first folder `PowerShell` within my vs code project but for files within the other 2 folders. Maybe that helps to narrow it down.

```
Version: 1.50.0 (system setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.14393
```

**Comment by DarkLite1** [comment] 2020-10-12 06:49
> Does the problem also happen after you run the Command Palette command to reload with all extensions disabled?

Just tried this, yes the problem remains when reloading without extensions.

**Comment by alexdima** [comment] 2020-10-12 14:59
@DarkLite1 Word wrapping can be influenced by folder level settings, and it appears you are using a workspace file with further word wrapping settings. To eliminate the complicated settings setup, could you please create a separate new folder on your machine, open that folder and open a powershell file in that folder. What is the behavior? What settings do you have in your user settings?

Except via settings, word wrapping is disabled when:
* configuring the editor to be in accessibility mode (like attaching a screen reader or configuring `editor.accessibilitySupport`): the root cause is that we cannot at this time efficiently transmit the difference between a wrapping point and a new line to screen readers, the solution is to use `"editor.accessibilitySupport": "off"`. When this occurs, there is a status bar message indicating this.
* when a very large file is opened (we do this to save memory), but this can be forced via `"editor.largeFileOptimizations": false`. When this occurs, a prompt is shown informing you.

@ToniSHernandez @DarkLite1 Do you perhaps run into one of the two cases I outlined above?

**Comment by DarkLite1** [comment] 2020-10-15 09:02
Thank you for getting back to me. I've tried your suggestion to create a new folder, add a ps1 file and check what happens:
- The ps1 file is correctly having its lines wrapped at 80 chars as desired
- The User Settings:
![image](https://user-images.githubusercontent.com/10828570/96101406-b60c1480-0ed5-11eb-8a93-174c91a44943.png)

To get back to the two exceptions you suggested, this is not he case for us. It's a small ps1 file and we don't have anything special configured.

**Comment by jabcross** [comment] 2020-10-16 17:44
I'm having a similar issue. I have VSCode opened on a folder with no special configuration, and wordWrapColumn set to 80. It doesn't work on bounded mode, either.

![image](https://user-images.githubusercontent.com/6402237/96291228-1d04f880-0fbe-11eb-82c0-e783233529d6.png)

**Comment by alexdima** [comment] 2020-10-26 13:59
@sandy081 IMHO word wrapping works correctly (or as configured). The problem is that folks have a hard time configuring it.

In the first case, @DarkLite1 is using a multi-folder workspace and has trouble configuring word wrapping. I believe there are workspace level settings and folder level settings at work, but I don't understand from the provided steps what exactly is misconfigured where. 🤷‍♂️ 

In the second case I believe @jabcross is trying to configure word wrapping at 80, but the default markdown language specific settings override the user settings.

IMHO both of these are UX problems, i.e. the setting works as configured, but the people have a hard time to configure it how they want it.

**Comment by jabcross** [comment] 2020-10-26 14:20
@alexdima It does, in fact, only happen in Markdown mode. But a default that overrides an explicit setting is a bug. Especially if it doesn't automatically create a field in settings.json to change it back if wanted.

**Comment by sandy081** [comment] 2020-10-29 11:30
Assigning to @roblourens to see if there can be any UX improvements can be done with our settings editor for these scenarios.

**Comment by roblourens** [comment] 2020-11-04 18:40
Thinking this is https://github.com/microsoft/vscode/issues/79273 and https://github.com/microsoft/vscode/issues/74195

**Closed by roblourens** 2020-11-04 18:40 UTC
