### ISSUE TITLE
Custom typedefs not highlighting.

### ISSUE THREAD

**Issue by datalus** [Microsoft/vscode#66295] opened 2019-01-09 16:50 UTC
Can we reopen #56199? It was closed based on being a now closed Atom issue, but that was resolved using the treesitter integration they released in 1.32. Is there any plans for this in VS Code?

**Comment by RMacfarlane** [comment] 2019-01-09 23:03
Hey @datalus, this looks like a duplicate of https://github.com/Microsoft/vscode/issues/50140. Please leave any feedback there, thanks!

**Closed by RMacfarlane** 2019-01-09 23:03 UTC
