### ISSUE TITLE
Build task is running forever in background and not displaying any message in the output window.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4666] opened 2016-03-25 03:13 UTC
- VSCode Version: 0.10.12-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open a folder which contains .ts ile.
2. Press F1 and insert command "Configure Task Runner".
3. Verify task.json is generated with some default setting.
4. Update default setting for command args for your .ts file like below:
"args": ["testme.ts"],
5. Press ctrl+shift+B to build.

Actual:
1. testme.js is created and task runner icon is showing forever.
2. No message display in output window.
![image](https://cloud.githubusercontent.com/assets/17735796/14036973/e9637716-f1fb-11e5-8499-73adb6e4dbf3.png)

Expected:
1. Looks like task is running in background in infinite loop
2. When build is successful it should display message in the output window so that user can understand task status.
![image](https://cloud.githubusercontent.com/assets/17735796/14037016/7b5c35d6-f1fc-11e5-8028-987607a206ce.png)
3. When User try to rebuild again by pressing Ctrl+Shift+B then it is sowing warning message like:
"**There is an active running task right now. Terminate it first before executing another task."**

**Comment by dbaeumer** [comment] 2016-03-29 09:28
I can't reproduce this using the latest alpha build. 

![bug](https://cloud.githubusercontent.com/assets/1931590/14103642/62633cac-f5a1-11e5-938c-f755dfd26128.gif)

Any additional steps / Info

**Comment by v-pavanp** [comment] 2016-04-06 21:06
Looks like the issue is with build indicator icon in the task bar. It is keep moving all the time and no clue to the user when build task gets over.

Can you try with the project placed at https://github.com/v-pavanp/ForTestingCode/blob/master/TypeScript.zip  and follow the below repro steps:

Steps:
1. Update the tasks.json with below args value:
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["app.ts"],
	"showOutput": "silent",
	//"cwd":"${workspaceRoot}/TypeScriptTypes/",
	"problemMatcher": "$tsc"
}

2. Now build it and verify error message in oup-put window.
error TS5007: Cannot resolve referenced file: 'app.ts'.
3. Now update tasks.json again for args value as below and build it.
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["${workspaceRoot}/TypeScriptTypes/app.ts"],
	"showOutput": "silent",
	//"cwd":"${workspaceRoot}/TypeScriptTypes/",
	"problemMatcher": "$tsc"
}

I could see the build icon is keep moving all the time. No clue when it is going to stop.

![image](https://cloud.githubusercontent.com/assets/17735796/14332023/a38ffd62-fbfc-11e5-9685-7ee0de7e7d4f.png)

**Comment by dbaeumer** [comment] 2017-11-07 10:35
Closing the issue. With the new terminal runner I changed the strategy and the spinner is only shown when a build task is active. I tested it and I couldn't break it.

**Closed by dbaeumer** 2017-11-07 10:35 UTC
Labels: tasks
