### ISSUE TITLE
Python highlighting for back-slash in raw string 

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode#84027] opened 2019-11-06 06:08 UTC
Issue Type: <b>Bug</b>

The back-slash in Python raw string will still be highlighted.
![image](https://user-images.githubusercontent.com/16792948/68272522-e54bbc00-009e-11ea-9ee8-d2de1134002e.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.14393
Remote OS version: Linux x64 4.15.0-1041-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: GCRAZGDL302|
|OS|Linux x64 4.15.0-1041-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (6 x 2593)|
|Memory (System)|110.17GB (13.36GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
unique-lines|bib|1.0.0
vscode-markdownlint|Dav|0.31.2
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.32
kite|kit|0.99.0
vscode-language-pack-zh-hans|MS-|1.39.3
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
cpptools|ms-|0.26.1
csharp|ms-|1.21.5
powershell|ms-|2019.11.0
team|ms-|1.149.2
python-docs|Muk|0.8.3
vscode-hexdump|sle|1.7.2
tabnine-vscode|Tab|2.1.11

</details>

**Comment by OneMoreSecond** [comment] 2019-11-06 06:15
At least don't highlight it for something like a Windows path.

**Comment by alexr00** [comment] 2019-11-06 09:05
duplicate of https://github.com/MagicStack/MagicPython/issues/155
But that is closed for historical reasons as stated here https://github.com/MagicStack/MagicPython/issues/149
recommendation from that issue is to use `R` instead of `r`

**Closed** 2019-11-06 09:06 UTC
Labels: *duplicate
