### ISSUE TITLE
Allow cursor to stay still when typing in Find

### ISSUE THREAD

**Issue by HugeCrab** [Microsoft/vscode#66328] opened 2019-01-10 10:51 UTC
Can we have a boolean option to control if we want the cursor to jump when we type in Find?

**Comment by RMacfarlane** [comment] 2019-01-11 01:15
Hey @HugeCrab, this looks like a duplicate of https://github.com/Microsoft/vscode/issues/65286, let's track it there. Please leave any feedback on that issue. Thanks!

**Closed by RMacfarlane** 2019-01-11 01:15 UTC
Labels: editor-find
