### ISSUE TITLE
C# references displayed incorrectly

### ISSUE THREAD

**Issue by darrenparkinson** [Microsoft/vscode#15088] opened 2016-11-07 11:01 UTC
- VSCode Version: 1.7.1 
- OS Version: Windows 10

Steps to Reproduce:

1. dotnet new
2. open folder
3. open .cs file
4. references displayed as in attached screen shot.

![image](https://cloud.githubusercontent.com/assets/4262917/20055499/4a0490ba-a4d9-11e6-866e-dc4bed8d18cf.png)
![image](https://cloud.githubusercontent.com/assets/4262917/20055515/58f0ee20-a4d9-11e6-8df2-2d806769fa19.png)
![image](https://cloud.githubusercontent.com/assets/4262917/20055524/6694a648-a4d9-11e6-86bf-e6d748ccf3b8.png)

**Comment by jrieken** [comment] 2016-11-07 11:53
@darrenparkinson Please attach the list of extensions you are using

**Comment by jrieken** [comment] 2016-11-07 13:24
@joaomoreno Just talked about this

**Comment by darrenparkinson** [comment] 2016-11-07 14:43
I guess it's actually the C# extension that shows this information and has the issue?  I'm using v1.4.1 of that and it isn't suggesting there is an update available.  Should I register this issue elsewhere?

Thanks.

**Comment by joaomoreno** [comment] 2016-11-07 14:44
No, @darrenparkinson, we got it.

Duplicate of #14949

**Comment by darrenparkinson** [comment] 2016-11-07 14:44
Cool, thanks.

**Closed by joaomoreno** 2016-11-07 14:44 UTC
