### ISSUE TITLE
Should CallHierarchyItemProvider have overloads with CallHierarchyItem

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#81748] opened 2019-10-01 13:02 UTC
Testing https://github.com/microsoft/vscode/issues/81655

Currently `CallHierarchyItemProvider` has position based provider functions. If we have a function `resolveCallHierarchyItem` or `prepareCallHierarchy` shouldn't there be an overload for `provideCallHierarchyIncomingCalls` and `provideCallHierarchyOutgoingCalls` that take a `CallHierarchyItem` instead of a document and a position.

**Comment by jrieken** [comment] 2019-10-01 13:20
Unsure, today we use the uri/position of an item to make the next request. That helps us to prevent sending these items around and also aligns nicely with other language APIs. I feel like adding an overloads doesn't help but makes things more complicated. Either have uri/position or have a prepare-method and items as args but not both

**Comment by dbaeumer** [comment] 2019-10-01 13:40
I agree on the not both argument.

**Comment by jrieken** [comment] 2019-10-08 10:53
/duplicate of https://github.com/microsoft/vscode/issues/81753

**Closed** 2019-10-08 10:53 UTC
Labels: *duplicate, callhierarchy, editor-symbols, under-discussion
