### ISSUE TITLE
CSS auto adds semicolon EVEN when disabled

### ISSUE THREAD

**Issue by fireball2016** [microsoft/vscode#101208] opened 2020-06-28 03:42 UTC
Issue Type: <b>Bug</b>

See title. Fix this shit!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
remote-wsl|ms-|0.44.4
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0

</details>

**Comment by gjsjohnmurray** [comment] 2020-06-28 05:26
Please use Command Palette to reload with all extensions disabled, then retest.

**Comment by aeschli** [comment] 2020-06-29 08:25
duplicate of https://github.com/microsoft/vscode/issues/100684

**Closed by aeschli** 2020-06-29 08:25 UTC
