### ISSUE TITLE
Indication of a japanese characters are piled at a integration terminal.

### ISSUE THREAD

**Issue by ishisaka** [Microsoft/vscode#7443] opened 2016-06-09 00:06 UTC
- VSCode Version:1.2.0
- OS Version:Windows 7 SP1, Windows 10 th2

Steps to Reproduce:

1. Set up japanese locale.
2. Launch Visual Studio Code
3. Run integration terminal.
4. Run "DIR" command at a integration terminal.

![vscode](https://cloud.githubusercontent.com/assets/589304/15915080/3eb902c4-2e21-11e6-884d-40e61558fe8c.PNG)

Indication of a japanese characters are piled at a integration terminal.

**Comment by kekyo** [comment] 2016-06-09 00:12
:+1:

**Comment by Tyriar** [comment] 2016-06-09 01:07
Duplicate of https://github.com/Microsoft/vscode/issues/7062

**Closed by Tyriar** 2016-06-09 01:07 UTC
