### ISSUE TITLE
Multiple Emmet Selections only expands the first one

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#17051] opened 2016-12-11 22:49 UTC
- VSCode Version: 1.7.2
- OS Version: Windows 7 x64

#### Steps to Reproduce:

Video: https://youtu.be/pc2wjBBF2p0

1. Select a word/tag multiple times using Ctrl+D
2. Press Tab or use `Emmet: Expand` from the Quick Menu.

**Comment by egamma** [comment] 2016-12-12 14:39
Duplicate of #9571

**Closed by egamma** 2016-12-12 14:39 UTC
Labels: duplicate, emmet

**Comment by ramya-rao-a** [comment] 2017-06-01 05:20
Set `emmet.useNewEmmet` to `true` (in the latest Insiders dated 6/1 or above and eventually in the stable release of 1.13 and higher) to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

In your example, after selecting multiple words, press `Ctrl+Space` to trigger the suggestion list and then choose from the list.

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464
