### ISSUE TITLE
C# intellisense broken in constructors (0.10.5)

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#1509] opened 2015-12-20 17:14 UTC
For regular C# functions, intellisense works as expected:
![screen shot 2015-12-20 at 18 13 01](https://cloud.githubusercontent.com/assets/594564/11918988/59a01e0a-a745-11e5-8d09-fb4790af69d8.png)

However, no intellisense shows up for constructors:
![screen shot 2015-12-20 at 18 12 21](https://cloud.githubusercontent.com/assets/594564/11918989/6dd4fb48-a745-11e5-8736-55dd50bb501a.png)

**Comment by geirsagberg** [comment] 2015-12-20 17:20
On a related note, intellisense parameter documentation seems not quite right; note the cutoff XML:
![screen shot 2015-12-20 at 18 19 14](https://cloud.githubusercontent.com/assets/594564/11919000/3f02b5ac-a746-11e5-9bd0-da459a1ee4b6.png)

**Comment by jrieken** [comment] 2016-01-20 09:29
duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/355

**Closed by jrieken** 2016-01-20 09:29 UTC
Labels: bug, c#
