### ISSUE TITLE
Some keys like "[" (left bracket) not working in terminal (German keyboard layout)

### ISSUE THREAD

**Issue by bluenote10** [microsoft/vscode#140263] opened 2022-01-07 09:19 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 10 Enterprise (build 19042.1415)

Steps to Reproduce:

1. Open the terminal in VSCode with a German Keyboard Layout
2. Try typing keys like "[" (which is `<AltGr>` + `8` on a German keyboard). It is not working at all.

I noticed a few other issues:
- The closing bracket "]" also doesn't work 100% correctly. The character appears immediately, but pressing e.g. `<ENTER>` immediately after isn't recognized anymore, i.e., it is necessary to press `<ENTER>` twice to be recognized.
- The `ß` key doesn't work either. It gets translated into the characters `^\`.
- The `\` also gets translated to the character `^\`.
- The `€` sign doesn't work at all.

At least the "[" used to work fine until the update to 1.63.2. Currently the terminal is not usable for coding, because typing "[" is required much too often to have it missing.

Note: The keys work correctly in the regular editor window.

**Comment by meganrogge** [comment] 2022-01-07 19:25
/duplicate of https://github.com/microsoft/vscode/issues/133597

Can you pls confirm this is fixed for you in Insider's?

**Closed by meganrogge** 2022-01-07 19:25 UTC

**Comment by bluenote10** [comment] 2022-01-13 17:32
@meganrogge Thanks for the feedback, and sorry for the delay :wink:

Even though the linked issue describes a quite different manifestation of the problem (I actually don't have to press `<ENTER>` multiple times after a quote, and not having the `[` key available at all is much more limiting as a coder) it seems to have the same root cause: I can confirm that in the Insider's version everything seems to work fine for me.

Is there a way to track when the fix get included into an official release?

**Comment by meganrogge** [comment] 2022-01-18 15:47
yes, it will be released the first week in February.
