### ISSUE TITLE
Faster "Goto Symbol in Workspace"

### ISSUE THREAD

**Issue by hyrious** [microsoft/vscode#158351] opened 2022-08-17 09:05 UTC
VSCode's "Goto Symbol in Workspace" has a debounce timeout and is not as fast as "Goto Symbol in Editor", maybe we can improve that by borrowing some ideas from Sublime Text. It achieves this feature with 2 major steps from my guess:

1. It builds index for each project, it may be slow at first run but will be fast once opened some folder. Generally the index is a `symbol -> file` map.
2. It provides two-step search in "Goto any Symbol", so symbols with same name will only take over one row, letting people find what their want more efficient.

I'll post some images to add details to what I said:

VSCode:

<p align="center"><img width="361" alt="vscode_1" src="https://user-images.githubusercontent.com/8097890/185075014-e113ed17-1849-4a8c-ba5d-a6bbc3431cdf.png"></p>

- It refreshes at a debounce time of about 1 seconds.
- Same name symbols are all displayed here, which may make target symbol be far away from top of the list.

Sublime Text:

<p align="center"><img width="576" alt="subl_1" src="https://user-images.githubusercontent.com/8097890/185077133-36c11672-0fc8-465b-a4f4-357936c7ea42.png"></p>

<p align="center"><img width="344" alt="subl_2" src="https://user-images.githubusercontent.com/8097890/185077787-df59d907-15d8-4e12-a90b-31a7226918bf.png"></p>

- It shows unique symbol names first, with its source file languages (it was extracted from syntax highlighting during the indexing step).
- When you <kbd>enter</kbd> one name, it then shows source paths and you can jump to that file quickly (it even doesn't wait your next <kbd>enter</kbd> to show the file, it creates a phantom view to quickly check out the source contents without actually open it in editor).

**Comment by jrieken** [comment] 2022-08-17 11:45
The typing debounce is vscode is ~200ms but it is up to extensions to build and persist an index or not. We don't make assumptions about that. The https://github.com/microsoft/vscode-anycode does that but other might. What language/extension are you seeing this with?

**Comment by hyrious** [comment] 2022-08-17 13:05
I'm viewing a TypeScript project in vscode screenshot above, with the built-in TypeScript language support. The main point here is not setting a smaller debounce time, but the experience of "Goto Symbol in Workspace" _feels_ more slower than "Goto Symbol in Editor". The latter works almost instantly.

Another annoying thing from the screenshots above is that vscode searches symbols in global paths (`/Applications/Visual Studio Code.app/...`) where people normally don't expect that. Maybe I was missing some configurations, maybe that's why it was slow.

I respect that vscode gives out every small function to extensions to make it more powerful, so I'm not expecting vscode to repeat what sublime has done (many features are powered by extracting info from syntax-highlighting). But I still want vscode to think the ways to improve user experience.

**Comment by jrieken** [comment] 2022-08-17 14:44
forwarding to @mjbvz since this is TS (but in reality this is for each language extension)

> Another annoying thing from the screenshots above is that vscode searches symbols in global paths (/Applications/Visual Studio Code.app/...) where people normally don't expect that. Maybe I was missing some configurations, maybe that's why it was slow.

That's because TypeScript ships symbols like `console` of common JS environments, like browsers, and those symbols happen to live in files inside the extension which is inside the app.

**Comment by mjbvz** [comment] 2022-08-17 20:08
Duplicate of #46718

**Closed by mjbvz** 2022-08-17 20:08 UTC
Labels: info-needed
