### ISSUE TITLE
Exclusion rules don't work in SEARCH function

### ISSUE THREAD

**Issue by cmondola** [Microsoft/vscode#32642] opened 2017-08-16 14:17 UTC
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-simpler-icons|dav|1.3.0
jshint|dba|0.10.15

---

Steps to Reproduce:

1. Click on the Magnifying Glass on the Activity Bar 
2. Insert some word in the search input text
3. Click on the "three dots" under the search input text 
4. Insert some complex rule with star characters (\*) in the file to exclude input text (for example "**/*.min.js" )
5. Click the enter button to begin the search

RESULT --> **Visual Code gives search results also for exclusion files**

Reproduces without extensions: Yes

**Comment by roblourens** [comment] 2017-08-16 15:17
Dupe of https://github.com/Microsoft/vscode/issues/32325, fixed in Insiders and the upcoming 1.15.1

**Comment by roblourens** [comment] 2017-08-16 15:18
As a workaround, just `*.min.js` excludes the same files.

**Closed by roblourens** 2017-08-16 15:17 UTC
Labels: new release, search

**Comment by cmondola** [comment] 2017-08-16 17:00
I tried, but it doesn't work.
I wait the new release with the fix.
Thanks
