### ISSUE TITLE
Create path if it doesn't exist on saving a file within WSL

### ISSUE THREAD

**Issue by loftwah** [microsoft/vscode#90500] opened 2020-02-12 02:33 UTC
I'd like to request a feature that creates a path if it doesn't already exist when saving a file within VSCode using WSL remotely. I have attached a screenshot to explain what I mean a bit better if it doesn't make sense. I would like an option there, possibly another button that allows me to create the path so I can save the file.

Cheers
Loftwah
![2020-02-12_10h27_59](https://user-images.githubusercontent.com/19922556/74297854-064d3880-4d83-11ea-9a40-816225b18717.png)

**Comment by avnevatia** [comment] 2020-02-12 13:39
I want to work on the issue,, seams legitimate. 
Will this be approved if I will submit a pull request?

**Comment by alexr00** [comment] 2020-02-17 14:49
Duplicate of https://github.com/microsoft/vscode/issues/71425

Before submitting a PR for that issue, can you provide some UI suggestions for where the "Create folder" button would go and what the flow for creating a new folder would look like? Currently the quick pick doesn't support more blue buttons (and I think that's good, two is enough.

**Closed** 2020-02-17 14:50 UTC
Labels: *duplicate

**Comment by avnevatia** [comment] 2020-02-18 05:40
![image](https://user-images.githubusercontent.com/37414168/74707109-d8626b00-523e-11ea-836c-5b0288b1b7e1.png)

We can have a button next to the error message. 
"The Path does not exist." Create Folder.

In this way we don't have to mess up with quick pick.

**Comment by alexr00** [comment] 2020-02-18 10:22
We don't have anywhere else where we show an input box validation message with a button in it, so that doesn't fix well with our UX. It also isn't something that the existing quick pick supports. The quick pick does support some action buttons above the input box to the right, so using those is one option.

**Comment by aeschli** [comment] 2020-02-18 10:47
It would be nice if the regular OK button just stays enabled. Show a info instead of an error: `The path does not exist. Folder 'nothere` will be created`
