### ISSUE TITLE
Organize imports removes needed import

### ISSUE THREAD

**Issue by AMerkuri** [Microsoft/vscode#47310] opened 2018-04-06 11:24 UTC
Issue Type: <b>Bug</b>

Organize Imports will remove following needed import from code `State as RootState`.

```typescript
import { State as RootState, NavigationState } from 'store';
import { ActionContext } from 'vuex';
import { getStoreAccessors } from 'vuex-typescript';

type NavigationContext = ActionContext<NavigationState, RootState>;
```

https://gyazo.com/c3491828db7c7157f844cda2e1338cad

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|Memory (System)|23.88GB (8.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Vue2|duc|0.1.3
gitlens|eam|8.2.0
vue-snippets|hol|0.1.5
vue|liu|0.1.5
code-beautifier|mic|2.0.3
debugger-for-chrome|msj|4.3.0
vetur|oct|0.11.7
LiveServer|rit|3.2.1
markdown-pdf|yza|0.1.8
markdown-all-in-one|yzh|1.1.2

(1 theme extensions excluded)

</details>

**Comment by raido** [comment] 2018-04-06 17:59
I can confirm same issue with example of imports like so:

```
import { and, alias } from '@ember/object/computed';
import { computed } from '@ember/object';
import Service, { inject as service } from '@ember/service';
import RSVP from 'rsvp';
```

It will remove `{ inject as service}`.

**Comment by mjbvz** [comment] 2018-04-06 18:31
Duplicate of https://github.com/Microsoft/TypeScript/issues/22743

Already fixed in TypeScript@next and will be fixed in next release of VS Code when we move organize imports out of preview. Follow these instructions to upgrade the current build to typescript@next: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Closed by mjbvz** 2018-04-06 18:31 UTC
Labels: javascript
