### ISSUE TITLE
Emmet not working on multi-line editing

### ISSUE THREAD

**Issue by sunlihao3000** [Microsoft/vscode#14652] opened 2016-10-28 10:23 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: danwahlin.angular2-snippets-0.10.13, NoHomey.angular-io-code-0.0.6

Steps to Reproduce:

using "emmet" for edit html file, when I selected multi-lines. the emmet is not working.
for example, I select two lines and typing "h2", when I tap the "tab", I should have two h2 element (like <h2> </h2>), but it's not. I only the two text "h2", not the html elements. which mean the Emmet plugin in not working in the multi-lines.
thanks
![screenshot_9](https://cloud.githubusercontent.com/assets/5240002/19803495/ead147d0-9d00-11e6-91b7-26f30fce0b94.png)

**Comment by sunlihao3000** [comment] 2016-10-28 10:24
![screenshot_9](https://cloud.githubusercontent.com/assets/5240002/19803520/0feca398-9d01-11e6-8a28-a3f225080d87.png)

**Comment by ramya-rao-a** [comment] 2017-02-11 23:21
Closing this as duplicate of #9571

**Closed by ramya-rao-a** 2017-02-11 23:21 UTC
Labels: emmet

**Comment by ramya-rao-a** [comment] 2017-06-01 05:19
@sunlihao3000 

Set `emmet.useNewEmmet` to `true` (in the latest Insiders dated 6/1 or above and eventually in the stable release of 1.13 and higher) to get emmet abbreviation expansions in the suggestion list.
This will work in multi cursor too

For details on this setting read https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464

**Comment by sunlihao3000** [comment] 2017-06-09 15:58
thanks, it work!!!
