### ISSUE TITLE
Menu bar items not translated in latest alpha

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6079] opened 2016-05-03 22:04 UTC
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Change language to German or French
2. Observe the file, edit, etc. menus

It seems some translations regress after alpha updates. Is this expected?

**Comment by bpasero** [comment] 2016-05-04 05:23
@vsccarl did you restart?

**Comment by vsccarl** [comment] 2016-05-04 18:08
@bpasero Yes, even after restart they are not translated.

**Comment by v-pavanp** [comment] 2016-05-04 23:43
I observed this behavior across all the platforms Mac\Linux\Windows. 

![image](https://cloud.githubusercontent.com/assets/17735796/15032568/25aad378-1217-11e6-8722-3b42bc859dbd.png)

**Comment by dbaeumer** [comment] 2016-05-09 10:52
@joaomoreno move the files to a new location. Since translations a scoped per file/folder location the files need to go through a translation cycle to get the menu translation back.

**Comment by v-pavanp** [comment] 2016-05-27 20:47
I am  able to repro this with latest alpha build. 

![image](https://cloud.githubusercontent.com/assets/17735796/15620806/681c9258-2411-11e6-90d0-30952df37edb.png)
![image](https://cloud.githubusercontent.com/assets/17735796/15620831/896c08bc-2411-11e6-8494-fb877b02fb87.png)

**Comment by Tyriar** [comment] 2016-05-27 20:50
Duplicate of https://github.com/Microsoft/vscode/issues/6927

**Closed by Tyriar** 2016-05-27 20:50 UTC
Labels: i18n, v-test, verified
