### ISSUE TITLE
How to increase the font size of IntelliSense panel?

### ISSUE THREAD

**Issue by lednhatkhanh** [Microsoft/vscode#11845] opened 2016-09-11 14:25 UTC
Hi, I want to increase the font size of the IntelliSense panel (I don't know exactly what's its name so I will call that, you can see more details in the image) but I don't know how because my current font size is quite small, does vscode have an option for that?

![Font size too small](http://i.imgur.com/Hm6F2Lm.png)

**Comment by ramya-rao-a** [comment] 2016-09-11 15:59
@alexandrudima Increasing font-size via `editor.fontSize` setting does not increase the font size of the text inside the suggestion/autocomplete box. Bug?

**Comment by joaomoreno** [comment] 2016-09-12 12:47
Actually I just pushed changes such that the intellisense text scales along with `editor.fontSize` now. Coincidence. Nevertheless:

Duplicate of #2465

**Closed by joaomoreno** 2016-09-12 12:47 UTC
Labels: duplicate, editor
