### ISSUE TITLE
"potential lister LEAK detected" before extension host crash

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74390] opened 2019-05-27 08:35 UTC
I'm investigating a severe bug that's been reported recently where the editor gets slower over time and eventually the extension host crashes. I experienced it myself yesterday (see the bottom part here, out of memory).

![code perf issues](https://user-images.githubusercontent.com/1078012/58406530-b944fd00-8061-11e9-83cc-08f3de9faf99.png)

[Here's the output of `code --status`](https://github.com/microsoft/vscode/files/3222563/code_perf.txt) just before the crash. The extension host is using a lot of CPU. Unfortunately before I could get a profile, it crashed.

I suspect a bug in my extension, but the reason I'm opening this issue is the "potential listener LEAK detected" message points to `workbench.main.js` and I'm not sure if this is a VS Code issue or my extension and the call stack just isn't great (so I'm trying to debug, but figured it's worth posting the info here too). The line/column points to this code here (I had to by the screenshot after, since it was late when this happened, so sadly I didn't get the position in ts code):

![code](https://user-images.githubusercontent.com/1078012/58406863-7899b380-8062-11e9-8b01-a5e7f847e720.png)

Let me know if you have any ideas of there's anything more I can do to help debug. I'll try and get some CPU profiles from the extension host if I can repro again.

**Comment by jrieken** [comment] 2019-05-27 09:25
I need the commit id of the build that causes this. Only then I can make sense of the (full) stack trace. However, 308 listener doesn't sound like much. Leaks that causes hangs are usually in the range of 100000 listeners...

**Comment by DanTup** [comment] 2019-05-27 09:33
It's current stable I saw it in (a622c65b2c713c890fcf4fbf07cf34049d5fe758). I did wonder whether these numbers were that large, but since it was writing warnings I thought it worth bringing up.

It's very possible the crash and this error are unrelated (I think I'm leaking memory, I'm just profiling to figure out where) and it's just coincidence they're in the logs when I was looking at the crash.

**Comment by jrieken** [comment] 2019-05-27 09:58
Leaking editor cancellation tokens have coincidently been fixed via https://github.com/Microsoft/vscode/commit/499a38b1ecf12b4735b97a285a5086a3e1cb30a3. Our default warn threshold is set to max 250 listener per event-emitter so that we see those early. Closing this as dupe of that commit as it unrelated to the extension host process

**Closed by jrieken** 2019-05-27 09:58 UTC
Labels: needs more info
