### ISSUE TITLE
Add CodeAction interface

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#34597] opened 2017-09-18 22:26 UTC
Part of #33555

**Problem**
Code actions are currently just a list of `Command`.  These commands provide have no information about what the code action actually does. We'd like to be able to do the following:

- Sort code actions so that fixes for errors show up first
- Group code actions by type / by the error they fix
- Provide a better UI for code actions that tells users which actions address which problems in the code

**Proposal**
Introduce a new `CodeAction` interface that defines additional information about a code action. To start, I propose we add two  additional field to this interface: a type and a list of diagnostics:

```ts
enum class CodeActionType {
    // Standard type. Would be used for existing CodeActionProviders that return Commands
    Default = 0 ,

    // Fixes a diagnostic in the CodeActionContext
    QuickFix = 1,    

    // Perform a refactorng
    Refactoring  =2
}

interface CodeAction {
    // Command the performs the action
    command: Command

    type: CodeActionType

    // List of diagnostics this code action resolves
    diagnostics?: Diagnostic[]
}
```

// cc @jrieken

**Comment by jrieken** [comment] 2017-09-19 07:08
CodeAction type yes, in that shape probably not. Folks also want a preview of the textual changes, so instead/in addition to a command we should support text edits or a workspace edit. This needs proper thinking. @mjbvz What are your scenarios?

**Comment by mjbvz** [comment] 2017-09-19 23:02
@jrieken Kai and I talked about this today and I've put together a more complete proposal based on that discussion: #34664

That proposal also would not provide workspace/text edits in its current form, but has been designed so that they could be accommodated in the future

**Comment by jrieken** [comment] 2017-09-20 07:41
ok, closing this as dupe of #34664

**Closed by jrieken** 2017-09-20 07:41 UTC
Labels: api, code-actions, feature-request, under-discussion
