### ISSUE TITLE
Use consistent wording for log points

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#48963] opened 2018-04-30 18:31 UTC
The command ID is `editor.debug.action.toggleLogPoint` but the command text is "Debug: Add Logpoint..." (notice the "P").

Another part the word is used:

<img width="238" alt="screen shot 2018-04-30 at 11 33 22 am" src="https://user-images.githubusercontent.com/2193314/39443724-568d990a-4c6a-11e8-9a41-27ff1cd48c5d.png">

**Comment by roblourens** [comment] 2018-04-30 22:13
We just changed from "log point" to "logpoint" but changing the command ID is probably a breaking change? I assume they are case-sensitive.

**Comment by isidorn** [comment] 2018-05-02 07:53
@Tyriar thanks for the suggestion however I chose not to change this due to the reasons @roblourens specified.
We have much bigger inconsistencies when it comes to command ids and we choose not to change them for backwards compatibility.

Due to the reaons above I will not change this. Closing as designed

**Closed by isidorn** 2018-05-02 07:53 UTC
Labels: debug
