### ISSUE TITLE
C# syntax highlighting missing

### ISSUE THREAD

**Issue by mvanbeusekom** [Microsoft/vscode#5414] opened 2016-04-17 12:39 UTC
- VSCode Version: 1.0.0
- OS Version: OS X El Capitan 10.11.4

No syntax highlighting for C#. Also unable to select C# from the languages menu.

Steps to Reproduce:

1. Open a .cs file in Visual Studio Code

Expected:
- Syntax highlighting for C# supported.

Actual:
- File is recognised as Plain Text

<img width="770" alt="screen shot 2016-04-17 at 14 37 53" src="https://cloud.githubusercontent.com/assets/13098888/14587000/137ff43c-04aa-11e6-9cd3-cb8348dac83f.png">

Try to set language to C#

1. Click on "Plain Text" on the bottom right
2. "Select Language Mode" dialog opens

Expected:
- Entry listing C#

Actual:
- C# language is missing from the list.

<img width="636" alt="screen shot 2016-04-17 at 14 38 10" src="https://cloud.githubusercontent.com/assets/13098888/14587001/13a334ec-04aa-11e6-84d7-1eabd205deef.png">

**Comment by egamma** [comment] 2016-04-17 12:51
duplicate of #5403

**Closed by egamma** 2016-04-17 12:51 UTC
