### ISSUE TITLE
Weird Spaces in terminals

### ISSUE THREAD

**Issue by akshitgupta29** [microsoft/vscode#121070] opened 2021-04-12 06:09 UTC
Issue Type: <b>Bug</b>

On Opening the terminal, I am getting weird spaces which makes the terminal look so unpresentable and I cannot work on it.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.81GB free)|
|Process Argv|--crash-reporter-id 3fea3863-c02f-4904-ba88-d0033b651013|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.76.220.62|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2397)|
|Memory (System)|31.25GB (5.42GB free)|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: 10.76.220.62|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2397)|
|Memory (System)|31.25GB (5.42GB free)|
|VM|33%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
aws-toolkit-vscode|ama|1.22.0
gitlens|eam|11.4.0
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.5.702919634
vscode-sanddance|msr|3.1.1
java|red|0.76.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

![image](https://user-images.githubusercontent.com/12370891/114348107-b84ce400-9b83-11eb-8d9c-589cf8fd79d9.png)

**Comment by meganrogge** [comment] 2021-04-14 15:49
Resizing the terminal should fix this issue

Duplicate of #120004

**Closed by meganrogge** 2021-04-14 15:49 UTC

**Comment by akshitgupta29** [comment] 2021-04-17 05:17
Thanks, @meganrogge.
