### ISSUE TITLE
not consistent in sidebar apperance

### ISSUE THREAD

**Issue by liuyji** [Microsoft/vscode#60634] opened 2018-10-11 12:56 UTC
Issue Type: <b>Bug</b>

When clicking git button on sidebar there will be a tiny blue line on the left, which would not be found at any other sidebar button. Does it has some special meaning? Or just a minor bug?

![code-3](https://user-images.githubusercontent.com/43626829/46805572-fe007a00-cd97-11e8-8f3b-e95315ef1286.PNG)
The git button has a tiny blue line on the left
![code-4](https://user-images.githubusercontent.com/43626829/46805609-14a6d100-cd98-11e8-8a9d-aeb1bd85b6b2.PNG)
Other buttons such as search has no line

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

**Comment by liuyji** [comment] 2018-10-11 12:58
The bot is so stupid this time!

**Comment by misolori** [comment] 2018-10-11 15:53
That's our focus state for the activity bar (you can tab through them with your keyboard), all other focus treatments use an outline/border

![gif](https://user-images.githubusercontent.com/35271042/46817008-04a8d600-cd33-11e8-8079-c5a25737c678.gif)

**Comment by liuyji** [comment] 2018-10-11 22:46
> That's our focus state for the activity bar (you can tab through them with your keyboard), all other focus treatments use an outline/border
> 
> ![gif](https://user-images.githubusercontent.com/35271042/46817008-04a8d600-cd33-11e8-8079-c5a25737c678.gif)

Do not use the tab key, just click the sidebar icon, you may find only the git button has a line on its left like me.
Tab key is ok for me, too. All the focused button on has the line.
It's somewhat Interesting😂

**Comment by liuyji** [comment] 2018-10-11 22:52
![code-5](https://user-images.githubusercontent.com/43626829/46838309-4a28da00-cdeb-11e8-800f-f9bcef0b9115.gif)
I use Windows.

**Comment by liuyji** [comment] 2018-10-12 00:10
This will only be happen when git is disabled on your opened folder. When git is enabled on your project, line disappear.
And I misunderstood what misolori say. Tab does not equals click. Click=Tab+Enter.
I'd like to know whether it is a bug or on purpose.

**Comment by misolori** [comment] 2018-10-12 18:36
I see the issue now, thanks for the screenshot/gif. This definitely looks like a bug.

**Comment by joaomoreno** [comment] 2018-10-15 19:57
<img width="767" alt="screenshot 2018-10-15 at 12 56 05" src="https://user-images.githubusercontent.com/22350/46974754-be78ad00-d079-11e8-943e-eb0a5de364ad.png">

**Comment by bpasero** [comment] 2018-10-16 04:54
If there is nothing to focus within the view it makes sense to show a blue border on the activity icon because that indicates it still has focus. I do not see a way to fix this without loosing the focus indicator in the first place. Closing as designed (@joaomoreno I am not sure what you are pointing at).

**Closed by bpasero** 2018-10-16 04:54 UTC

**Comment by bpasero** [comment] 2018-10-17 06:03
> the border appears after a small timeout

That is the first time I hear that and your screenshot was not pointing into that direction. The only timeout I see is [here](https://github.com/Microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/browser/ui/actionbar/actionbar.ts#L140).

**Comment by bpasero** [comment] 2018-10-22 17:06
The delay is actually coming from https://github.com/Microsoft/vscode/blob/53d48f4c2c8fa4eeabd85301b3e3e8e446895625/src/vs/workbench/browser/parts/compositeBarActions.ts#L206 and is a way to prevent showing the blue focus outline everytime you click an icon in the activity bar. I would not want to remove it, though there might be a smoother solution.

**Comment by joaomoreno** [comment] 2018-10-22 18:06
> a way to prevent showing the blue focus outline everytime you click an icon in the activity bar

Why do we want to prevent that? Seems like it would be OK...

**Comment by bpasero** [comment] 2018-10-23 05:47
@joaomoreno same reason we do it for pretty much every clickable thing, including action bar. It results in very hectic flicker on each click.

**Comment by joaomoreno** [comment] 2018-10-23 15:34
> @joaomoreno same reason we do it for pretty much every clickable thing, including action bar. It results in very hectic flicker on each click.

If this is a focus affordance, it should just be rendered immediately, the same way the border of an input field gets a border color as soon as it is focused. Am I missing something here?

**Comment by joaomoreno** [comment] 2018-10-23 15:36
Yes, I am missing something here, that you conveniently left out: the focus decoration used to be rendered on `mousedown`, which meant that on `mouseup`, whatever is inside the viewlet would grab focus, and the user would see a brief flashing focus affordance in the viewlet action.

Saying that we delay focus affordances on every clickable thing is a **long** stretch.
