### ISSUE TITLE
Adding folder to empty explorer: Data tree node not found

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99051] opened 2020-06-02 10:36 UTC
```
 ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchCompressibleAsyncDataTree.getDataNode (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:461:23)
    at WorkbenchCompressibleAsyncDataTree.expand (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:364:31)
```

Steps:
* empty workspace
* File > Add Folder

**Comment by isidorn** [comment] 2020-06-02 10:39
Ah the good old data tree node not found error. 
After you get this error does everything work or all is broken?

I can not reproduce this. My steps. Have an empty workspace with no folders, File > add folder to workspace and choose a folder -> all good.

**Comment by bpasero** [comment] 2020-06-02 10:59
@isidorn nothing seems broken. I can reproduce from a fresh user data dir, using macOS

**Comment by isidorn** [comment] 2020-06-02 16:35
Assigning to may to investigate.

**Closed** 2020-06-03 13:25 UTC
Labels: file-explorer

**Comment by isidorn** [comment] 2020-06-03 13:26
I could not reproduce. However there might be some tree timing issue.
Decided to just swallow the error if something fails in expadning roots. That way you should no longer see the error. And not auto expanding roots is not critical.
