### ISSUE TITLE
Can't select text on Linux when using Ibus Pinyin input method

### ISSUE THREAD

**Issue by touuki** [microsoft/vscode#70483] opened 2019-03-14 13:26 UTC
- VSCode Version: 1.32.2
- OS Version:  Linux x64 4.16.0-kali2-amd64

Steps to Reproduce:
I can't select text in editor via holding the mouse click and dragging when I run VSCode as root, but it works fine running as a normal user.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zsc347** [comment] 2019-03-27 15:25
This issue also occur when I run vscode as normal user.
But it's gone after I switch to a new user or run as root.
Try uninstall along with remove .vscode in user home dir and then reinstall won't fix the bug. So I guess some config in other place cause this issue.

**Comment by zsc347** [comment] 2019-03-27 15:36
Since it's related with Ibus Pinyin input method. When I switch input method to `en`. This prblem has gone.

**Comment by zsc347** [comment] 2019-03-27 15:56
For users meet same problem in Ubuntu 18.04 using ibus pinyin， try turn it off and user fcitx-google-pinyin instead. It fix my prolem.

If only there is a team like vscode mataining a Chinese input method for linux!

**Comment by TangHHH** [comment] 2019-03-28 06:00
> Seems it's related with Ibus Pinyin input method. When I switch input method to `en`. This prblem has gone.

@zsc347 Oh, thx. It really solved my problem : )

**Comment by jypjypjypjyp** [comment] 2019-08-01 03:03
@zsc347 same with you.

**Comment by bpasero** [comment] 2019-10-18 13:42
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by touuki** [comment] 2019-10-20 12:06
@bpasero I just tried it, but it still doesn't work.

**Closed** 2021-11-05 11:26 UTC
Labels: needs more info, upstream, electron, editor-input-IME
