### ISSUE TITLE
Cannot launch Developer Tools when VSCode is running elevated [Windows]

### ISSUE THREAD

**Issue by grahamm78** [microsoft/vscode#111317] opened 2020-11-25 18:34 UTC
Issue Type: <b>Bug</b>

I checked this on a few machines.  Windows pre-release build 21268 and retail 19042. 

Repro Steps
1. launch vscode as administrator, open a project
2. click Help -> Toggle Developer Tools (or ctrl+shift+i)

Expected result: The dev console appears
Result: The console does not appear

It works fine if I launch vscode without elevating.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.21268

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (11.33GB free)|
|Process Argv|--crash-reporter-id 7dd2d561-081d-4b47-a2b0-2e055dd17a8e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
git-tree-compare|let|1.10.0
syntax-project-pbxproj|mar|0.1.3
devinsights|Mic|2020.10.15-1
tdpcode|Mic|1.6.3
vscode-nmake-tools|Mic|3.0.201105003
sarif-viewer|MS-|3.0.2
remote-wsl|ms-|0.51.4
cpptools|ms-|1.1.2
source-depot|sup|0.0.2
gitblame|wad|6.0.0

</details>

**Comment by yume-chan** [comment] 2020-11-27 07:21
Duplicate of #104395

**Comment by deepak1556** [comment] 2020-12-09 18:21
Merging to https://github.com/microsoft/vscode/issues/104395

**Closed by deepak1556** 2020-12-09 18:21 UTC
