### ISSUE TITLE
Text wiggles while scrolling while zoomed

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode#103277] opened 2020-07-24 20:50 UTC
Issue Type: <b>Bug</b>

On my Mac, when I scroll slowly, the lines of text wiggle. I took two screenshots at slightly different scroll positions, then aligned the first line of code in each screenshot.

![ezgif-1-f234342ad3a8](https://user-images.githubusercontent.com/108767/88434027-494d1680-cdcd-11ea-8264-19c93b4b46ce.gif)

I can't remember this happening previously. With macOS's inertial scrolling, it is a bit nauseating because almost any amount of scrolling ends with wiggling text as the scroll position eases to a stop.

The UI is zoomed in one step from default scale. At default zoom level I do not notice this, though it might be happing.

```
    "window.zoomLevel": 1,
```

The font is Apple's SF Mono (which may need to be installed from inside Terminal.app or wherever it lives now). I have a Retina display set to default scaling. 

```
    "editor.fontFamily": "SF Mono",
    "editor.fontWeight": "500",
    "editor.fontSize": 12,
```

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_352342|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.1.8
vscode-dash|dee|2.4.0
vscode-codeql|Git|1.3.1
vscode-test-explorer|hbe|2.19.1
r|Iku|1.4.3
linter-gfortran|krv|2.2.1
restructuredtext|lex|129.0.0
nc-gcode|ML|0.13.0
vscode-docker|ms-|1.4.1
vscode-ros|ms-|0.6.4
python|ms-|2020.7.96456
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.1
cpptools|ms-|0.29.0
debugger-for-chrome|msj|4.12.9
java|red|0.65.0
vscode-xml|red|0.13.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0

</details>

**Comment by alexdima** [comment] 2020-09-03 21:22
This is due to using `window.zoomLevel`. I recommend to use `editor.fontSize` for pixel perfect rendering. The `window.zoomLevel` is implemented outside of our control and even if we render rectangles at integer coordinates that perfectly touch each-other, the zooming might introduce rounding errors and create such artefacts.

Duplicate of #91686 and many others

**Closed by alexdima** 2020-09-03 21:22 UTC
Labels: zoom
