### ISSUE TITLE
Error installing extensions

### ISSUE THREAD

**Issue by Twizzledrizzle** [Microsoft/vscode#319] opened 2015-11-20 08:13 UTC
I am on windows 7, latest vscode, behind a corporate proxy, but have specified in in settings. I get a list of all extensions, but when I try and install for example magicpython I get the following error:

`getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443`

Any ideas?

**Comment by joaomoreno** [comment] 2015-11-20 08:16
Duplicate of #69

**Closed by joaomoreno** 2015-11-20 08:16 UTC
