### ISSUE TITLE
Syntax highlighting broken for long wrapped lines in Typescript

### ISSUE THREAD

**Issue by majelbstoat** [Microsoft/vscode#51920] opened 2018-06-14 17:56 UTC
Similar to https://github.com/Microsoft/vscode/issues/48858, long variable lines break syntax highlight in Typescript files.

- VSCode Version: 1.24.1
- Typescript: 2.9.1
- OS Version: OSX 10.13.4

With this code:

```
this._addPositionOperations = promisify<
      PositionChangeSetResponse,
      AddPositionOperationsRequest,
      Metadata
    >(this.client.addPositionOperations.bind(this.client))

this._setPositionSummary = promisify<BooleanResponse, SetPositionSummaryRequest, Metadata>(
      this.client.setPositionSummary.bind(this.client)
    )
```

Compare:

<img width="836" alt="screenshot 2018-06-14 10 54 27" src="https://user-images.githubusercontent.com/425787/41429233-57ea6916-6fc1-11e8-808e-9e9562125aae.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by Geobert** [comment] 2018-06-14 18:29
https://github.com/Microsoft/vscode/issues/51157

**Comment by mjbvz** [comment] 2018-06-14 18:58
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/479

This issue has been marked as wontfix upstream. See that thread for more details

**Closed by mjbvz** 2018-06-14 18:58 UTC
Labels: new release
