### ISSUE TITLE
Make markdown links without protocol (iE /README.md) map to file system

### ISSUE THREAD

**Issue by fbehrens** [Microsoft/vscode#17486] opened 2016-12-18 12:33 UTC
Yes, in markdown i can set file links using the `file://path/to/my/file.md` syntax to create file links. However, this depends on where i cloned the repo on my computer.

When I write documentation in markdown, I can link between documents in the following way

```
linked from /doc/documentation.md
* [back](../README.md) 
* [back absolute](/README.md)
```
As expected, a relative link is relative to the current file, an absolute link is resolved to the project root

Here are working examples on [github](https://github.com/fbehrens/doc-example/blob/master/doc/documentation.md) and [gitlab](https://gitlab.com/fbehrens/doc-example/blob/master/doc/documentation.md)

It would be very useful, if those links would also work in VSCODE, because this would make it possible to set and follow the links while writing the documentation in the editor.

There is a related closed issue #11518

**Comment by mjbvz** [comment] 2016-12-19 20:45
I believe this is a duplicate of #989

**Closed by mjbvz** 2016-12-19 20:45 UTC
Labels: duplicate, markdown
