### ISSUE TITLE
Mac: Undo, Redo, Select All not working in native dialogs (use roles for those?)

### ISSUE THREAD

**Issue by kaiye** [Microsoft/vscode#797] opened 2015-11-29 16:14 UTC
Please check the screenshot below, it should select all the text include the file extension, however it was not working.

![select-all-not-working](https://cloud.githubusercontent.com/assets/344283/11458218/f4f5f3c0-96f6-11e5-84ea-00b3efabfc90.png)

**Comment by bpasero** [comment] 2016-03-24 09:56
This change brings back the "role" attribute to undo, redo and selectAll. From my testing this is not causing any harm because it seems to me using the keybindings within the workbench never reaches the menu. However, when you are in dev tools or in the native file dialog and invoke the keybindings, the menu to the top quickly flashes blue and indicates the action is used from there. Suggest we run with this change for a sprint and watch out for regressions.

**Comment by bpasero** [comment] 2016-03-29 07:56
This was causing https://github.com/Microsoft/vscode/issues/4717, reverting my change.

**Comment by bpasero** [comment] 2016-03-29 07:57
Marking as upstream. Imho this should work without special code from our end, or if any we have API to find out if a native dialog is opened or not.

**Comment by bpasero** [comment] 2016-08-31 15:12
https://github.com/Microsoft/vscode/issues/8439

**Closed by bpasero** 2016-08-31 15:12 UTC
Labels: bug
