### ISSUE TITLE
Default File Saving Location

### ISSUE THREAD

**Issue by Elivius** [microsoft/vscode#178805] opened 2023-03-31 13:23 UTC
Type: <b>Feature Request</b>

Dear Microsoft Team,
I would like to suggest and upvote a feature which is allow users to config their default .txt file saving location instead of default saving it in %userprofile%. That will be great and amazing if we are able to select our own folder to save the file such as desktop folder. 

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by lramos15** [comment] 2023-03-31 14:09
Similar to https://github.com/microsoft/vscode/issues/178216

**Comment by lramos15** [comment] 2023-03-31 14:09
Similar to https://github.com/microsoft/vscode/issues/178216

**Comment by bpasero** [comment] 2023-03-31 16:05
Duplicate of https://github.com/microsoft/vscode/issues/115730

**Closed** 2023-03-31 17:55 UTC
Labels: feature-request, file-io
