### ISSUE TITLE
not able to create a file by right clicking on folder.

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#47972] opened 2018-04-16 14:48 UTC
Issue Type: <b>Bug</b>

right click on the folder
select create new file

VS Code version: Code - Insiders 1.23.0-insider (dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b, 2018-04-16T05:17:45.591Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (2.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
jshint|dba|0.10.18
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.1
EditorConfig|Edi|0.12.1
tslint|eg2|1.0.28
python|ms-|2018.3.1
PowerShell|ms-|1.6.0
typescript-javascript-grammar|ms-|0.0.39
vscode-react-native|vsm|0.6.6

</details>

**Comment by carboneater** [comment] 2018-04-16 16:07
The same bug also happens when using the create new file in the project bar under the project explorer.

**Comment by eamodio** [comment] 2018-04-16 19:26
Same for New Folder

**Comment by LouieK22** [comment] 2018-04-17 02:30
Issue still exists, Win10 latest insiders version.

**Comment by perlun** [comment] 2018-04-17 05:00
Duplicate of #47937.

**Closed** 2018-04-17 08:04 UTC
Labels: integrated-terminal
