### ISSUE TITLE
markdown.preview.scrollPreviewWithEditorSelection is invalid

### ISSUE THREAD

**Issue by wpp2014** [Microsoft/vscode#28482] opened 2017-06-12 03:12 UTC
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. File > Preferences > Settings (Code > Preferences > Settings
2. "markdown.preview.scrollPreviewWithEditorSelection": true,
3. Did not achieve the desired effect

**Comment by mjbvz** [comment] 2017-06-12 16:38
What is the desired effect?

**Comment by wpp2014** [comment] 2017-06-13 00:32
When mouse points to a place, the preview will be transferred to the corresponding place. This is done through a click event, which I want to do with scrolling.

**Comment by mjbvz** [comment] 2017-06-13 00:35
Thanks. This sounds like a duplicate of #19459

**Closed by mjbvz** 2017-06-13 00:35 UTC
Labels: needs more info, new release
