### ISSUE TITLE
Inconsistent handling of multiple TextEdits on the same line

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#19694] opened 2017-02-01 21:56 UTC
- VSCode Version:1.8.1 & 1.9.0-insider (Validation 27240e71ef390bf2d66307e677c2a333cebf75af, Date 2017-02-01T11:43:14.109Z)
- OS Version: OSX 10.12.2, Ubuntu 16.10

Steps to Reproduce:
Using the [vscode-java extension](https://marketplace.visualstudio.com/items?itemName=redhat.java)
1. open a Java file
2. Type `Object o = new O`(+`ctrl+space`) to get autocompletion for the contructor `Object()`
3. select `Object()` and  press `Enter`

The inserted text is `O()`, instead of `Object()`.  See:
![inconsistent-textedit-behavior](https://cloud.githubusercontent.com/assets/148698/22527225/5f6875a0-e89c-11e6-9a38-2c196d8ef0d2.gif).

If you revert the change (`Ctrl+z`), you can see the complete constructor string was applied first, before being overridden by `()`.

Tracing the messages exchanged with the Java Language server, it seems the text edits returned by a call to `completionItem/resolve` are correct. As can be seen from L7225, from the [complete message log generated during the above recording](https://github.com/Microsoft/vscode/files/746256/autocompleting-object.txt):

```
[Trace - 14:58:25] Sending request 'completionItem/resolve - (113)'.
Params: {
    "label": "Object()",
    "detail": "java.lang.Object",
    "kind": 4,
    "sortText": "zzzzzzigdf",
    "data": {
        "decl_signature": "Ljava.lang.Object;",
        "signature": "()V",
        "name": "Object",
        "pid": "0",
        "rid": "44",
        "uri": "file:/home/fbricon/Dev/souk/test/src/main/java/A.java"
    }
}


[Trace - 14:58:25] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "2017-02-01 13:48:38 >> document/resolveCompletionItem"
}


[Info  - 14:58:25] 2017-02-01 13:48:38 >> document/resolveCompletionItem
[Trace - 14:58:25] Received response 'completionItem/resolve - (113)' in 4ms.
Result: {
    "label": "Object()",
    "kind": 4,
    "detail": "java.lang.Object",
    "sortText": "zzzzzzigdf",
    "textEdit": {
        "range": {
            "start": {
                "line": 1,
                "character": 20
            },
            "end": {
                "line": 1,
                "character": 20
            }
        },
        "newText": "()"
    },
    "additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 19
                },
                "end": {
                    "line": 1,
                    "character": 20
                }
            },
            "newText": "Object"
        }
    ]
}


[Trace - 14:58:27] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/fbricon/Dev/souk/test/src/main/java/A.java",
        "version": 18
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 19
                },
                "end": {
                    "line": 1,
                    "character": 20
                }
            },
            "rangeLength": 1,
            "text": "Object"
        }
    ]
}


[Trace - 14:58:27] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/fbricon/Dev/souk/test/src/main/java/A.java",
        "version": 19
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 1,
                    "character": 20
                },
                "end": {
                    "line": 1,
                    "character": 25
                }
            },
            "rangeLength": 5,
            "text": "()"
        }
    ]
}

```
The ranges for the `()` are wrong. 

On extremely rare occasions the inserted text is correct, but I'm unable to find a pattern to reproduce the working case.  Moreover, it seems the Orion IDE, using the same Java server, is not affected. Which makes me think this is definitely a vscode issue.

A second bug can be seen on the screencast, which could be a side-effect of this issue: after the proposals are displayed, typing the next letter to narrow down the selection actually deselect the 1st `Object()` proposal, only the new letter is highlighted. If it's unrelated, I'll open another issue. 

See also https://github.com/redhat-developer/vscode-java/issues/143

 cc @gorkem

**Comment by jrieken** [comment] 2017-02-02 11:30
Ok, I can reproduce and describe what happens and I wonder why you use the API that way. The suggestion describes a main edit (insert `()` at the cursor position) and an addition text edit (replace `O` with `Object). This is what happens

1. text is `O|` (where `|` is the cursor/selection)
2. *first* the additional text edit is inserted which results in `|Object|`. Note how the selection grew.
3. Now the *main text edit* which isn't merged with the former is inserted, that results in `O()|`

There are some things we need to clarify on our side, like not growing the selection in step 2. However, this is an unexpected use of additional text edits and when text around the cursor is to be modified the primary edit should be used. 

> A second bug can be seen on the screencast, which could be a side-effect of this issue: after the proposals are displayed, typing the next letter to narrow down the selection actually deselect the 1st Object() proposal, only the new letter is highlighted. If it's unrelated, I'll open another issue.

This can be explained with the primary text edit because it starts *after* the `O` only its text (`()`) is used to filter and rank suggestions. 

@fbrion How come you use the API this way and why doesn't our main text edit describe the replace operation (replace `O` with `Object()`)? When we added additional text edits we had things like adding imports etc in mind but not composing an edit at the cursor location from multiple smaller edits.

**Comment by fbricon** [comment] 2017-02-02 13:21
Ok your explanation makes sense.

Well, we're simply mapping the proposals returned by Eclipse's completion engine: The main proposal's text is `()` and it has a _required_ proposal of `Object`. This is exactly what we return.

I'll see if I can change something on the server side, to merge edits on the same line, but I think this use case should also be properly handled at the vscode level.

**Comment by fbricon** [comment] 2017-02-02 19:48
Indeed, returning only 1 textedit fixes both issues. 

I'll leave this ticket open since vscode should still better handle multiple textedits on the same line.

**Closed** 2018-09-11 09:05 UTC
Labels: *out-of-scope, suggest, under-discussion

**Comment by filipw** [comment] 2019-06-23 07:59
@jrieken in the more complex completions in Roslyn's case, where Roslyn needs to heavily modify the entire document (i.e. additional using import on completion), Roslyn will actually compute all the changes into a single text change - new text string + range to apply it.

With the current VS Code architecture, it's very difficult to use such a change because we need to manually "uncollapse" which edit happens on current line (`insertText`) and which happens on other lines (i.e. those extra imports or any other changes). This is very error prone, and especially Roslyn already does an excellent job in simply providing new text and range to apply it over, it feels backwards and unnecessary. Would be extremely beneficial if we could do one of the following:

 - use `insertText` + `Range` over multiple lines
 - have a switch that would allow us to apply `additionalTextEdits` after the insertion is done. This way we would still do the insertion of the `insertText` but then simply overwrite everything via a big edit from `additionalTextEdits` (the one provided from Roslyn)

Is there any possible solution you could advise?

**Comment by jrieken** [comment] 2019-06-24 14:45
We do run `additionalTextEdits` first because `insertText` can be a snippet and we don't really know how/when you leave that. That's kind of a given there. You can do the 'after' trick with a completion command which is always run after the insertion happened, BUT outside the undo stops and async so that will likely result in a bad feel. 

The challenge is that `range` is used to select the portion of text that's used to rank/filter completions. So, making that arbitrary large will likely break that - for once if you don't update `filterText` and another problem is that we didn't design the ranking to work off a large prefix (limit ~100 characters). 

I didn't try this but what if you have a "proper" range and filterText (for ranking/filtering), an "identify  insert text" (whatever is selected by range), and then additional text edits for the real edit? If that works it would be the best I believe...
