### ISSUE TITLE
Breakpoints View Panel is Missing with no clear way to restore it

### ISSUE THREAD

**Issue by n8sabes** [microsoft/vscode#102799] opened 2020-07-17 16:14 UTC
Visual Studio Code Debugger Breakpoints View is missing with no clear way to restore it.

- VSCode Version: 1.48.0-insider
Commit: 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
Date: 2020-07-16T13:10:40.625Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

- OS Version: macOS Catalina v10.15.5 (19F101)

- Language being debugged: TypeScript / JavaScript

Steps to Reproduce: UNKNOWN

![Missing Debug Panel 1](https://user-images.githubusercontent.com/10445528/87807203-d6600080-c80c-11ea-9930-a4d6d2cc0beb.png)
![Missing Debug Panel 3](https://user-images.githubusercontent.com/10445528/87807227-dcee7800-c80c-11ea-935d-86aa5f5ce0ac.png)
![Missing Debug Panel 2](https://user-images.githubusercontent.com/10445528/87807218-d9f38780-c80c-11ea-906f-a3e82cec1cdb.png)

Does this issue occur when all extensions are disabled?: YES

**Comment by gjsjohnmurray** [comment] 2020-07-17 16:53
If you check that Views menu when you aren't debugging, does the Breakpoints entry appear?

**Comment by n8sabes** [comment] 2020-07-17 16:55
@gjsjohnmurray, Breakpoints View does not appear regardless of debugging mode or not. I have trued every mode, context, and setting I can think of.

I've also posted on the [StackOverflow](https://stackoverflow.com/questions/62955049/visual-studio-code-breakpoints-view-panel-is-missing-how-to-get-it-back), but no viable solutions yet.

**Comment by n8sabes** [comment] 2020-07-18 15:27
@gjsjohnmurray, yes -- kind of.

The issue was the Breakpoints View was under its own icon in the Sidebar which is not automatically selected during debugging sessions, making it not obvious. To fix this:

**SOLUTION:**

1. CMD+SHIFT+P to bring up the Show Command Palette
2. Enter and run "Focus on Breakpoints View"
3. Right-Click Breakpoints header, and choose "Reset Location"

![Breakpoints in Sidebar](https://user-images.githubusercontent.com/10445528/87855890-2a7fe900-c8d0-11ea-97f3-c5ab5d865dbd.png)

Thanks to everybody, and various forums/resources to figure this out!!

**Comment by weinand** [comment] 2020-07-20 08:51
This is a general problem with views that are dragged out of their regular "home".
This break some assumptions, e.g.:
- the debug viewlets badge shows the sessions, but when activating the viewlet, it does not show any sessions because they live in another viewlet.
- when hitting a breakpoint, the debug viewlet is activated but it does not show anything useful

See here:

<img width="857" alt="2020-07-20_10-45-26" src="https://user-images.githubusercontent.com/1898161/87918363-9d2ac900-ca76-11ea-971d-b41ab157f1a0.png">

Either we forbid dragging out of specific views, or we will have to become smarter in finding the correct viewlet for a given view.

/cc @misolori

**Comment by sbatten** [comment] 2020-07-20 15:35
The infrastructure should all be there for this to happen more smoothly.

1. We may want some new icons for each debug view instead of only relying on the debug viewlet icon.

2. @sandy081 and just recently @joaomoreno for scm, did work to make the badging tied to the view instead of the container. I assume debug just needs to adopt this behavior.

**Comment by weinand** [comment] 2020-07-21 14:34
@sbatten thanks for this info.
We will update VS Code debug accordingly.

**Comment by isidorn** [comment] 2020-07-27 12:29
Isn't this somewhat a duplicate of https://github.com/microsoft/vscode/issues/101016
But yes on top of this there are things we could improve on the debug side.

**Comment by weinand** [comment] 2020-07-27 13:26
@isidorn yes, the original issue is about restoring a view and that can be considered a duplicate of #101016.

But the other issues of moving views to other containers are equally important.
If users have deliberately moved a view somewhere else, they expect them to work there too.

So I suggest to close this as a duplicate and create a new issue for the necessary tasks that we have to do for debug:
- We may want some new icons for each debug view instead of only relying on the debug viewlet icon.
- badging must be done for the correct container
- we have to activate the correct debug viewlet when a breakpoint is hit or a debug sessions has started.

**Comment by isidorn** [comment] 2020-07-27 14:36
@weinand makes sense. Created this one https://github.com/microsoft/vscode/issues/103414
And closing this one

**Closed by isidorn** 2020-07-27 14:36 UTC
Labels: debug
