### ISSUE TITLE
When "Release Notes" is the active tab, Cmd-M can't minimise the window on macOS

### ISSUE THREAD

**Issue by gchappell99** [microsoft/vscode#108364] opened 2020-10-09 07:30 UTC
Issue Type: <b>Bug</b>

* Use Help>Release Notes to open the Release Notes tab and make it the active tab
* Push Cmd+M
* Expected result: window minimises to Dock
* Actual result: window does not minimise
* Close Release Notes tab or switch to another tab
* Cmd+M
* Actual result: window minimises

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_6952609 --crash-reporter-id 1dca76ad-2cbf-479c-8709-451f528e590a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
terraform|4op|0.1.10
vscode-base64|ada|0.1.0
cform|aws|0.0.24
xml|Dot|2.5.1
gitlens|eam|10.2.2
go|gol|0.17.2
vscode-cfn-lint|kdd|0.15.0
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.9.114305
azure-account|ms-|0.9.3
azurerm-vscode-tools|msa|0.13.0
indent-rainbow|ode|7.4.0
vscode-yaml|red|0.11.1
vscode-sort-json|ric|1.18.1
indenticator|Sir|0.7.0
vscode-ansible|vsc|0.5.2
markdown-pdf|yza|1.4.4

</details>

**Comment by mjbvz** [comment] 2020-10-14 00:09
Duplicate of #98246

**Closed by mjbvz** 2020-10-14 00:09 UTC
