### ISSUE TITLE
Please do not auto close the ext install window.

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#727] opened 2015-11-27 00:51 UTC
Please do not auto close the ext install window.
the first run ext install was very slow. but if miss focus, the window will be closed .
Terrible experience.
would you please do not auto close the window?

You can provide a close button, let us control when to close the window or not.
we want to install the extension.but not want reopen the window again and again

**Comment by joaomoreno** [comment] 2015-11-27 09:45
Duplicate of #637.

**Closed by joaomoreno** 2015-11-27 09:45 UTC
