### ISSUE TITLE
Allow to disable sashes that border the screen when full screen

### ISSUE THREAD

**Issue by oltodosel** [microsoft/vscode#137121] opened 2021-11-13 15:19 UTC
In v1.61 right sidebar was introduced. It, just like others, has a sash attached to it to pull it into view.

Because the sash of the new panel is right beside scroll-bar, taking up rightmost pixels of the screen, now I can't simply put the cursor just to the right to scroll, because sash pixels(even if reduced to 1px) take precedence, and have to carefully aim at the scrollbar.

This is an issue only in fullscreen.

I want an option to disable the right sidebar or make its sash 0px.

**Comment by gjsjohnmurray** [comment] 2021-11-13 15:59
The Appearance submenu of the View menu has a Show Side Panel option.

**Comment by usernamehw** [comment] 2021-11-13 16:07
I don't see it:

<img width="400" src="https://user-images.githubusercontent.com/9638156/141650714-67767dbf-ce94-4080-a814-83a42489b625.png">

This issue is probably a duplicate of https://github.com/microsoft/vscode/issues/134629 which was closed without any explanation.

**Comment by gjsjohnmurray** [comment] 2021-11-13 16:36
@usernamehw that option appears when you set `"workbench.experimental.sidePanel.enabled": true`

I overlooked that the OP said it only happens in fullscreen mode. I agree it is the same as #134629

@sbatten you closed that issue as "as designed". Will you reconsider supporting a way for users to opt out of side panel completely, and carry that forward even when `workbench.experimental.sidePanel.enabled` is removed? Perhaps make it `workbench.sidePanel.enabled` and make fullscreen mode respect it, not offering the sash if the setting is false. At the moment the experimental session doesn't have that effect, so a fullscreen user who hasn't set `"workbench.experimental.sidePanel.enabled": true` gets the sash and can drag it left to reveal an empty space which displays nothing and cannot have other views (e.g. Outline) dragged onto it. This feels like a bug.

**Comment by sbatten** [comment] 2021-11-16 17:29
this issue is actually a duplicate of https://github.com/microsoft/vscode/issues/136451

**Closed** 2022-01-17 02:32 UTC
Labels: feature-request, layout, sash-widget
