### ISSUE TITLE
Open file dialog is not showing

### ISSUE THREAD

**Issue by dpetukhov** [microsoft/vscode#180108] opened 2023-04-17 09:08 UTC
Type: <b>Bug</b>

When I press Ctrl + O, nothing happens. When I select Open file from top menu, nothing happens. Open workspace from file is not working either.

But Open folder dialog is working fine. 

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.4.0-146-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 4100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.15GB (19.99GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment] 2023-04-17 09:38
Probably a duplicate of https://github.com/microsoft/vscode/issues/146422

**Comment by deepak1556** [comment] 2023-04-24 07:44
Merging to https://github.com/microsoft/vscode/issues/178978

**Closed by deepak1556** 2023-04-24 07:44 UTC
