### ISSUE TITLE
Visual Studio Code - Insiders: "Timed out waiting for browser connection"

### ISSUE THREAD

**Issue by Ashesh3** [microsoft/vscode#190189] opened 2023-08-10 05:58 UTC
Note: This only happens when working on remote SSH, local browser debug works fine.

When launching the following debug config, an error message in shown.

Debug config:
```
{
            "type": "msedge",
            "request": "launch",
            "name": "edge",
            "url": "http://localhost:4000",
            "webRoot": "${workspaceFolder}"
}
```

Error message:
```
[Window Title]
Visual Studio Code - Insiders

[Content]
Unable to launch browser: "Timed out waiting for browser connection"

[Open 'launch.json'] [Cancel]
```

Shared logs
```
2023-08-08 11:53:45.816 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at w.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4767)
    at w.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4182)
    at c.value (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:3578)
    at y.w (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1902)
    at y.x (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1972)
    at y.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:2188)
    at MessagePortMain.ie (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:40517)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-08 11:53:45.831 [info] [SharedProcessTunnelService] Created tunnel 7: localhost:53374 (local) to localhost:53374 (remote).
2023-08-08 11:53:45.843 [info] Creating a socket (renderer-Tunnel-c9f2b742-3ada-4da7-a0ab-f7d5eb7c70f9)...
2023-08-08 11:53:45.923 [info] Creating a socket (renderer-Tunnel-c9f2b742-3ada-4da7-a0ab-f7d5eb7c70f9) was successful after 79 ms.
2023-08-08 11:53:50.751 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at w.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4767)
    at w.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4182)
    at c.value (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:3578)
    at y.w (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1902)
    at y.x (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1972)
    at y.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:2188)
    at MessagePortMain.ie (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:40517)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)

```

Extension host logs:
```
2023-08-08 11:55:29.422 [error] Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-08-08 11:55:29.923 [error] Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-08-08 11:55:30.444 [error] Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-08-08 11:55:30.816 [error] Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2023-08-08 11:55:32.128 [error] Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

---
Vscode version:

Version: 1.82.0-insider (user setup)
Commit: 39e5dafcd66adab6f2d2ba65f6d6bde5eeb3767e
Date: 2023-08-07T18:31:10.893Z
Electron: 25.4.0
ElectronBuildId: 22901934
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Windows_NT x64 10.0.19045
JavaScript Debugger: Tried with both v2023.8.417 and v1.81.0

**Comment by alexr00** [comment] 2023-08-10 16:56
Not known. @Ashesh3 can you try on the latest insiders?

**Comment by Ashesh3** [comment] 2023-08-10 17:05
> Not known. @Ashesh3 can you try on the latest insiders?

Doesn't work on the latest insider, I updated just now. :/ 

Downgrading works every time but when I re-upgrade, the same issue. 

Note again that this does not happen when opening a local folder, everything works fine on latest insider.
The issue happens only when a remote SSH host is opened, and browser debug is attempted. 

Forwarding any other arbitrary port has no issues, only browser debug.


Version having this issue:
```
Version: 1.82.0-insider (user setup)
Commit: d62534a60f7eb4280bcbee66bbd84a2e15f13765
Date: 2023-08-10T05:33:20.243Z
Electron: 25.4.0
ElectronBuildId: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Windows_NT x64 10.0.19045
```

Full debug config. (Only `edge` config fails)
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "npm dev",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run", "dev","--","--","--host"],
            "skipFiles": ["<node_internals>/**"],
            "serverReadyAction": {
                "pattern": "listening on|started on",
                "uriFormat": "http://localhost:4000",
                "action": "debugWithEdge"
            },
            "restart": true
        },
        {
            "type": "msedge",
            "request": "launch",
            "name": "edge",
            "url": "http://localhost:4000",
            "webRoot": "${workspaceFolder}"
        }
    ],
    "compounds": [
        {
            "name": "Run npm dev and Launch Edge",
            "configurations": ["npm dev", "edge"]
        }
    ]
}
```

Error:
```
[Window Title]
Visual Studio Code - Insiders

[Content]
Unable to launch browser: "Timed out waiting for browser connection"

[Open 'launch.json'] [Cancel]
```
*The browser window does open and remains opened, but vscode fails to connect to it.*

Shared log:
```
2023-08-10 22:34:33.069 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:36.004 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:36.283 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at w.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4767)
    at w.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4182)
    at c.value (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:3578)
    at y.w (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1902)
    at y.x (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1972)
    at y.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:2188)
    at MessagePortMain.ie (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:40517)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-10 22:34:36.295 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:38.331 [info] [SharedProcessTunnelService] Created tunnel 6: localhost:53803 (local) to localhost:53803 (remote).
2023-08-10 22:34:38.336 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:38.337 [info] Creating a socket (renderer-Tunnel-d0fb6951-8cf6-47dd-a580-b3913bc42067)...
2023-08-10 22:34:38.379 [info] Creating a socket (renderer-Tunnel-d0fb6951-8cf6-47dd-a580-b3913bc42067) was successful after 42 ms.
2023-08-10 22:34:41.163 [error] [uncaught exception in sharedProcess]: Cannot read properties of undefined (reading 'then'): TypeError: Cannot read properties of undefined (reading 'then')
    at w.s (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4767)
    at w.q (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:4182)
    at c.value (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:26:3578)
    at y.w (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1902)
    at y.x (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1972)
    at y.fire (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:2188)
    at MessagePortMain.ie (c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:40517)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-10 22:34:41.621 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:42.063 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
2023-08-10 22:34:47.351 [error] [uncaught exception in sharedProcess]: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter: TypeError: Cannot set property pluginVersionString of #<AppInsightsCore> which has only a getter
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24624
    at c:\Users\Ashesh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:64:24461
```

**Comment by connor4312** [comment] 2023-08-10 18:27
Top of the stack is this line -- for some reason the error was not picked up on the errors website. Also unfortunately the cause is not that obvious...

https://github.com/microsoft/vscode/blob/40037a96987c2705c00d4d23188658bb08135632/src/vs/base/parts/ipc/common/ipc.ts#L428

**Comment by Ashesh3** [comment] 2023-08-15 17:19
Update:

Still having the issue on the latest release:
```
Version: 1.82.0-insider (user setup)
Commit: cb94a70e1f43b4115e86907165c80d7870f10e18
Date: 2023-08-15T05:33:34.188Z
Electron: 25.4.0
ElectronBuildId: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Windows_NT x64 10.0.19045
```

Reiterating, no issues on the previous release:
```
Version: 1.81.0-insider (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:36:29.806Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by thehsansaeed** [comment] 2023-08-16 08:07
Hey there! VS Code (Insiders) when trying to launch a debug session with Microsoft Edge. 

First, make sure your firewall or antivirus software isn't blocking the connection between VS Code and the browser. Sometimes, security software can cause communication issues. A quick restart of both VS Code and Edge might do the trick. Sometimes, issues like this can be resolved with a simple refresh.
Double-check that your Microsoft Edge browser is installed correctly and up to date. Outdated or corrupt installations can cause unexpected errors. Browser extensions can sometimes interfere with VS Code's connection to the browser. Try disabling any extensions temporarily and see if the problem persists.
Being on the latest version of VS Code Insiders is important. Updates often bring bug fixes and improvements. Make sure you're up to date.
If you're using remote SSH, ensure your network connection is stable. Sometimes, network issues can lead to timeouts. Review your debug configuration carefully. Even a small typo can lead to connection problems. Your config seems fine, but it's worth a double-check. 
As a test, consider using a different browser in your debug configuration. This will help determine if the issue is related to Microsoft Edge specifically.

**Comment by stephenstack** [comment] 2023-08-18 09:16
Port forwarding a vite run dev session from remote SSH server not working on latest insiders for me since last update. Port 5173. Had to go back to stable version to get some work done. Happy to debug/ troubleshoot if steps can be shared. Note, exact same network, machines etc.. involved

**Comment by bdentino** [comment] 2023-08-18 13:26
I had the same experience as @stephenstack this week working on a node app via remote ssh. Had to switch from insiders to stable. Everything looked normal from the UI but requests on the forwarded port would just hang without making it to the remote.

**Comment by alexr00** [comment] 2023-08-23 15:15
This looks to be the same as https://github.com/microsoft/vscode/issues/190859#issuecomment-1689113819, which is where we're tracking the fix.

**Closed by alexr00** 2023-08-23 15:15 UTC
Labels: bug
