### ISSUE TITLE
Parameter Hint & Trigger Characters should respect suggestions delay

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/vscode#98381] opened 2020-05-22 14:13 UTC
I enjoy the power of "quick suggestions" and "parameter hints" in VSCode, but I find them popping up a little too much - I'd like them not to pop up unless I _pause_ for some length of time.  However, this is not possible today...

- Setting `editor.quickSuggestionsDelay` allows you to specify a "pause" before inline suggestions show up while typing, but does not affect the "trigger character" pause.

- The solution is to disable `editor.suggestOnTriggerCharacters`, but now if I pause after typing a period (`.`), the suggestion _never_ shows up!  I don't want to completely disable the list of suggested methods, I just don't want it to show up until I pause.

- Disabling `editor.suggestOnTriggerCharacters` also essentially disables parameter hints (i.e. after typing `(`).  Again, I want them, but I only want them after I pause.

The solution I'd like is that if `suggestOnTriggerCharacters` is disabled, it only disables the _immediate_ popup - it still respects `quickSuggestionsDelay`.

If that's not possible, then I suppose I'm asking for 2 additional "delay" settings (one for parameter hints to pop up on their own, the other for post-trigger-character suggestions to pop up).

**Comment by jrieken** [comment] 2020-05-26 07:16
/duplicate of https://github.com/microsoft/vscode/issues/88104

**Closed** 2020-05-26 07:16 UTC
Labels: *duplicate, suggest
