### ISSUE TITLE
Error while starting Settings Sync: Server returned 502

### ISSUE THREAD

**Issue by ayush987goyal** [microsoft/vscode#108635] opened 2020-10-14 02:30 UTC
- VSCode Version: 1.50.0
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Start Settings Sync
2. This error is thrown

```
[2020-10-14 00:05:49.157] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-10-14 00:05:49.157] [userDataSync] [info] Auto Sync is disabled.
[2020-10-14 07:43:17.549] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":500,"execution-id":"7802fe27-ac9c-4814-a6f4-6b5cb2d23a37","operation-id":"0e0d89792da647f9818a0b48425c611e"}
[2020-10-14 07:43:33.350] [userDataSync] [info] Did reset the local sync state.
[2020-10-14 07:45:33.585] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","status":502,"execution-id":"26071d44-38a7-4ddf-8aa8-1c38afb0e329"}
[2020-10-14 07:48:11.436] [userDataSync] [info] Did reset the local sync state.
[2020-10-14 07:50:12.520] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/snippets/latest","status":502,"execution-id":"bc471761-7b90-48ab-91d1-416d82a3cc9b"}
[2020-10-14 07:50:12.526] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-10-14 07:50:12.527] [userDataSync] [info] Keybindings: Stopped synchronizing keybindings.
[2020-10-14 07:55:41.352] [userDataSync] [info] Did reset the local sync state.
[2020-10-14 07:57:41.602] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","status":502,"execution-id":"a01d35b2-e212-4927-ad7a-69efa158cd42"}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamondo2** [comment] 2020-10-17 15:29
- VSCode Version: 1.51.0-insider (user setup) (Commit 89c002ab02f87102d91efc83c191ef1174756c6a)
- OS Version: Windows 10 Pro ( 19041.572 )

Can confirm the same result as @ayush987goyal, when starting VSC I attempt to enable Settings Sync and I get the following log:
```
[2020-10-17 11:14:11.664] [userDataSync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2020-10-17 11:14:11.664] [userDataSync] [info] Auto Sync is disabled.
[2020-10-17 11:16:20.686] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/manifest","status":502,"execution-id":"3769cd8c-e1e1-4452-a58b-0f6a2daa21d2"}
[2020-10-17 11:16:27.403] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/settings","status":502}
[2020-10-17 11:16:27.409] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/globalState","status":502}
[2020-10-17 11:16:27.409] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/snippets","status":502}
[2020-10-17 11:16:27.410] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/keybindings","status":502}
[2020-10-17 11:16:27.411] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/extensions","status":502}
[2020-10-17 11:16:27.411] [userDataSync] [info] Request failed {"url":"https://vscode-sync-insiders.trafficmanager.net/v1/resource/machines/latest","status":502}
```

I have tested with both the insiders and standard version of sync, with both MS and GitHub as auth. sources.

**Comment by sandy081** [comment] 2020-10-19 14:13
Assigning to @lszomoru for initial investigation on 502 error from server.

Please reassign it to me if there is anything needs to be done on client side.

**Comment by lszomoru** [comment] 2020-10-19 14:47
@ayush987goyal, @eamondo2 - apologies for the inconvenience. The errors that you have seen were caused by one of the Azure App Services getting into a bad state due to which it was unable to connect to the CosmosDB backend. We have mitigated the error by restarting the App Service and we are working with our Azure partner teams to track down the root cause, and put improvements in place to avoid this error condition in the future.

@ayush987goyal, could you please try to re-enable settings sync and let me know if you run into any issues. Thanks!

**Comment by iyashpal** [comment] 2020-10-27 11:36
Having the same error while logged in with github:
![image](https://user-images.githubusercontent.com/19922707/97296482-beb9fe80-1876-11eb-8d69-fabdbaed558b.png)

**Comment by aaryanporwal** [comment] 2020-10-27 12:17
I reinstalled VSCode and when trying to turn on setting sync, I got the same error (MacOS 11.0 Beta):
```[2020-10-27 17:41:53.689] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-10-27 17:41:53.689] [userDataSync] [info] Auto Sync is disabled.
[2020-10-27 17:42:09.674] [userDataSync] [info] Did reset the local sync state.
[2020-10-27 17:44:10.356] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest","status":502,"execution-id":"191eb9f7-12b1-44fa-8f4c-37474c112340"}
[2020-10-27 17:44:10.368] [userDataSync] [info] Settings: Stopped synchronizing settings.
```
![image](https://user-images.githubusercontent.com/54525904/97300362-5b32cf80-187c-11eb-9516-0aaeb6d3a3f4.png)

**Comment by NIRVANALAN** [comment] 2020-10-27 12:33
```
[2020-10-27 20:26:50.859] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-10-27 20:26:50.859] [userDataSync] [info] Auto Sync is disabled.
[2020-10-27 20:27:56.565] [userDataSync] [info] Did reset the local sync state.
[2020-10-27 20:29:00.952] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/manifest","status":502,"execution-id":"cb69b70c-94b1-41c1-9207-2ba5599103e4"}
[2020-10-27 20:29:56.705] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest","status":502,"execution-id":"b4edbc47-6c31-4166-a004-9a4630a7296e"}
[2020-10-27 20:29:56.719] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-10-27 20:31:01.590] [userDataSync] [info] Did reset the local sync state.
```
Same result here. Tried GitHub as well as Microsoft account.

**Comment by aliyyousuff** [comment] 2020-10-27 13:02
`[2020-10-27 18:51:31.396] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-10-27 18:51:31.396] [userDataSync] [info] Auto Sync is disabled.
[2020-10-27 18:51:44.152] [userDataSync] [info] Did reset the local sync state.
[2020-10-27 18:51:45.122] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/extensions/latest","status":500,"execution-id":"2270b00d-77aa-4600-93f2-8cadabe46805","operation-id":"e19f11cd353749b59d9eb469c4764bc8"}
[2020-10-27 18:51:45.139] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-10-27 18:51:45.142] [userDataSync] [info] Keybindings: Stopped synchronizing keybindings.
[2020-10-27 18:51:45.143] [userDataSync] [info] Snippets: Stopped synchronizing snippets.
[2020-10-27 18:51:45.148] [userDataSync] [info] GlobalState: Stopped synchronizing globalstate.
[2020-10-27 18:55:07.819] [userDataSync] [info] Did reset the local sync state.
[2020-10-27 18:57:07.998] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","status":502,"execution-id":"10de2065-1df9-4a44-8a9c-b5d863d07449"}
[2020-10-27 18:58:06.841] [userDataSync] [info] Did reset the local sync state.
[2020-10-27 19:00:07.501] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/snippets/latest","status":502,"execution-id":"d464b784-99cb-4999-bc36-2f2595098e99"}
[2020-10-27 19:00:07.513] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2020-10-27 19:00:07.514] [userDataSync] [info] Keybindings: Stopped synchronizing keybindings.`

Here I am facing the problem.

**Comment by lszomoru** [comment] 2020-10-27 13:32
Sorry about that. I am taking a look at the service-side telemetry now and will circle back with my findings.

**Comment by lszomoru** [comment] 2020-10-27 13:46
It looks like one of the App Services has gotten into a bad state. I am working on mitigating the issue.

**Comment by lszomoru** [comment] 2020-10-27 13:58
We have mitigated the issue at **2020-10-27T13:50:00 UTC**. Could you please re-enable settings sync and let me know if you are still seeing any errors. I will follow up with our Azure partner teams to get to the bottom of the reason why the App Service instance has gotten into a bad state. Apologies for the inconvenience.

**Comment by aliyyousuff** [comment] 2020-10-27 14:16
It worked. Thanks.

**Comment by aaryanporwal** [comment] 2020-10-27 14:30
Worked for me too,
Thanks!

**Closed** 2020-10-28 10:23 UTC
Labels: settings-sync, settings-sync-server

**Comment by matangover** [comment] 2020-10-28 21:12
Still happening for me:
```
[2020-10-28 22:08:59.580] [userDataSync] [info] Did reset the local sync state.
[2020-10-28 22:10:59.887] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest","status":502,"execution-id":"5d6b31fe-17e5-4b7c-a7be-97a9402d7949"}
[2020-10-28 22:10:59.891] [userDataSync] [info] Settings: Stopped synchronizing settings.
```

**Comment by lucamauri** [comment] 2020-10-28 21:55
> We have mitigated the issue at **2020-10-27 13:50:00 UTC**. Could you please re-enable settings sync and let me know if you are still seeing any errors. I will follow up with our Azure partner teams to get to the bottom of the reason why the App Service instance has gotten into a bad state. Apologies for the inconvenience.

I also recently ran into this error: unfortunately it seems it is still happening on 2020-10-28:
```
[2020-10-28 22:30:59.916] [userDataSync] [info] Did reset the local sync state.
[2020-10-28 22:32:59.961] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/settings/latest","status":502,"execution-id":"91aeb1f4-311e-41f5-96d7-36f63cc40818"}
```
Thanks for keep looking into this

**Comment by zloadmin** [comment] 2020-10-28 22:09
I've got same error 
```
[2020-10-29 01:00:31.356] [userDataSync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
[2020-10-29 01:02:39.636] [userDataSync] [info] Did reset the local sync state.
[2020-10-29 01:04:39.888] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest","status":502,"execution-id":"71548532-7021-440f-a9d8-9966d0df301d"}
[2020-10-29 01:04:39.894] [userDataSync] [info] Settings: Stopped synchronizing settings.
```

**Comment by symonxdd** [comment] 2020-10-28 23:03
I get the same error bois...

**Comment by Ahmeed2m** [comment] 2020-10-28 23:26
same error here sometimes 500 and others 502

**Comment by jlopez994** [comment] 2020-10-29 00:13
Hello, same error here:

```
[2020-10-29 01:08:40.040] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-10-29 01:08:40.040] [userDataSync] [info] Auto Sync is disabled.
[2020-10-29 01:08:57.378] [userDataSync] [info] Did reset the local sync state.
[2020-10-29 01:10:57.530] [userDataSync] [info] Request failed {"url":"https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest","status":502,"execution-id":"f4f2f6d1-5b28-4332-a02a-9d40deceb6f8"}
[2020-10-29 01:10:57.537] [userDataSync] [info] Settings: Stopped synchronizing settings.
```

**Comment by lszomoru** [comment] 2020-10-29 11:38
Unfortunately last night we have had a reoccurrence of this in one of the European App Service instances. The issue has been mitigated at **2020-10-29T06:06:00Z**. Can you please go ahead and re-enable settings sync and let us know if you are still seeing any errors.

This morning I have also received an update from the Azure team that they have tracked down the root cause of these network issues, and a fix for it is already checked in and will be included in the next release train. Until the fix is rolled out, we are exploring a potential workaround to avoid another reoccurrence. Apologies for the inconvenience.

**Comment by Larswa** [comment] 2020-10-29 19:21
I am in Denmark, and are still seeing this on both my laptop and my desktop pc. Could there still be Azure outages causing this?

**Comment by lszomoru** [comment] 2020-10-29 19:33
Sorry about that @Larswa. Yeah, it looks like another reoccurrence. Restarting the App Service now.

**Comment by Larswa** [comment] 2020-10-29 19:41
Hey @lszomoru  Thanks for the update. Will test and revert shortly.

**Comment by reznord** [comment] 2020-10-29 19:44
Hey @lszomoru I am still getting the same error. I just tried to sync just now and it isn't syncing properly.

I am in Lisbon, Portugal.

**Comment by Larswa** [comment] 2020-10-29 19:49
> Sorry about that @Larswa. Yeah, it looks like another reoccurrence. Restarting the App Service now.

And I can confirm that its working again for me.  Thanks @lszomoru !!!

**Comment by reznord** [comment] 2020-10-29 19:54
> Hey @lszomoru I am still getting the same error. I just tried to sync just now and it isn't syncing properly.
> 
> I am in Lisbon, Portugal.

I can confirm that it is working again for me now 😄 . Thanks @lszomoru 🙇‍♂️

**Comment by lszomoru** [comment] 2020-10-29 19:58
Thanks @Larswa and @reznord for the confirmation. Apologies for the inconvenience.

**Comment by lucamauri** [comment] 2020-10-29 21:49
> Sorry about that @Larswa. Yeah, it looks like another reoccurrence. Restarting the App Service now.

I can confirm it works now as well. Thanks a lot
