### ISSUE TITLE
vscode ctrl+p show matched string: shows files but not able to see matched strings when file paths are long

### ISSUE THREAD

**Issue by sant527** [microsoft/vscode#123383] opened 2021-05-09 03:59 UTC
In vs code i am trying to search for files using : eg `ctrl+p` and search `django contrib auth`

[![enter image description here][1]][1]

It does not show the search terms it focuses main on the files

where as in sublime text: i can see the matched strings also

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/PNlVA.png
  [2]: https://i.stack.imgur.com/8bOCn.png

this is important for me, because i want to see the where the terms are matching

How to get this feature in vscode

**Comment by gjsjohnmurray** [comment] 2021-05-09 04:35
Looks like a duplicate of #120660

**Comment by thedamon** [comment] 2021-06-12 03:14
> Looks like a duplicate of #120660

it does indeed, but that one didn't get enough likes to be cool. maybe this one will?

It's too bad all the kewl hipster coders aren't stuck in platforms with really long file paths to files of the same names because this would clearly have been solved years ago if so. it just seems like such an obvious, solvable issue 🙃

**Closed** 2021-07-13 02:31 UTC
Labels: feature-request, quick-open, search
