### ISSUE TITLE
Cannot use LOCALLY (work space) installed typescript version

### ISSUE THREAD

**Issue by rydergillen-compacSort** [Microsoft/vscode#39432] opened 2017-12-01 19:07 UTC
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code (1.18.1)
2. npm install typescript
3. Tasks --> Run Build Task
4. The term 'tsc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.

Reproduces without extensions: Yes

Please do not waste time sending links on how this is 'supposed' to be supported. I have viewed 100's of them, none of the outlined steps ACTUALLY work.

Also any solution using PATH is not acceptable. In REAL development environments it is never practical to assume a single TypeScript version for all projects. Typescript must be installed locally to the project.

https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

https://stackoverflow.com/questions/35369501/tsc-is-not-recognized-as-internal-or-external-command

**Comment by mjbvz** [comment] 2017-12-01 19:14
This will use the local tsc if available. What does your project structure look like?

**Comment by rydergillen-compacSort** [comment] 2017-12-01 19:17
![image](https://user-images.githubusercontent.com/30268100/33499268-2c80f69a-d689-11e7-8041-e89e1ac19418.png)

**Comment by mjbvz** [comment] 2017-12-01 19:20
/duplicate of #30754

1.18 only looks for tsc at the root folder. VS Code 1.19 (current insiders build) fixes #30754 by first looking for tsc next to the `tsconfig.json`, then in the root folder, before finally falling back to global

**Closed** 2017-12-01 19:20 UTC
Labels: *duplicate, needs more info, typescript

**Comment by rydergillen-compacSort** [comment] 2017-12-01 19:22
Excellent, thank you! I tried looking for a related issue first, guess I missed this one.
