### ISSUE TITLE
[Bug] The 'Open' button in the open file dialog can open a workspace, not a file, if you enter a path

### ISSUE THREAD

**Issue by ljusten** [Microsoft/vscode#13235] opened 2016-10-05 07:58 UTC
- VSCode Version: 1.5.3
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:
1. Open some workspace, e.g. a fresh typescript extension that has been created with yo.
2. Hit CTRL+O to open a file and navigate to the base folder (the folder that contains src).
3. Enter 'src/extension.ts' and click the 'Open' button (important: it must contain '/', a simple file works as expected).
4. Click the 'Open' button (just hitting the Return key works as expected).

Expected result: The file opens.
Actual result: VS Code opens a new workspace, sometimes I end up in the .git folder, sometimes in src.

**Comment by Tyriar** [comment] 2016-10-05 17:05
Cannot reproduce on Ubuntu 16.04, could this be an issue with Ubuntu 14? Just to clarify, you are talking about the location bar here right?

![image](https://cloud.githubusercontent.com/assets/2193314/19123371/3ca62e20-8ae3-11e6-815e-5d1b9fa433de.png)

**Comment by ljusten** [comment] 2016-10-05 17:45
Yes, that looks correct. When I click the 'Open' button in that dialog it
takes me out of my workspace. Pressing Return works fine.
I can't rule out the possibility that it's a 14.04-only issue. I'll see if
I can repro it on someone else's computer.

Thanks,

- Lutz

**Comment by Tyriar** [comment] 2017-04-21 04:07
Closing as it looks like an OS issue.

**Closed** 2017-04-21 04:07 UTC
Labels: linux, needs more info

**Comment by ljusten** [comment] 2017-04-21 15:50
I can't reproduce it in 1.11.2 anymore, anyway. Looks like it got fixed along the way!
