### ISSUE TITLE
VSCode is very slow on my system

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#12087] opened 2016-09-15 16:10 UTC
- VSCode Version: 1.5.2
- OS Version: Windows 8.1 Enterprise 64-bit

Steps to Reproduce:
1. Please try to run vsCode faster than now.
2. Enable drag selected text to move it (See this: http://stackoverflow.com/questions/33858029)

**Comment by bpasero** [comment] 2016-09-19 04:56
@mghhgm can you share more details about 1. and create a separate issue for 2. please

**Comment by bpasero** [comment] 2016-09-24 06:05
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by mghhgm** [comment] 2016-09-24 21:31
Hi dear Benjamin!
Excuse me for the delay in response.
Details for problem 1:
- for example when I running vscode, after 14 sec ready to use... .
- when I openning some files and switch between them, after 2 sec ready to use... .
- when I selecting some characters by mouse in files, this process have delay.

I compare vscode by notepad++. I programming by notepad++ for 6 years. now I use vscode for best user interface and nice themes and some features. But I like the load speed of vscode, such as notepad++.

**Comment by bpasero** [comment] 2016-09-25 05:53
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by mghhgm** [comment] 2016-09-25 06:22
I instead of disable extensions, **delete them** and select _default color theme_ but now after 12 sec vscode is ready. Please check this.
I before installed this extensions:
1. HTML Class Suggestions
2. Color Picker
3. beautify
4. PHP Symbols
5. vscode-icons
Thank you

**Comment by bpasero** [comment] 2016-09-25 06:51
@mghhgm can you open Code window and select "Reload Window" from the command palette (press F1) and see how fast the window is loading then?

**Comment by mghhgm** [comment] 2016-09-25 21:25
@bpasero after "Reload Window", after 9~10 sec vscode is ready. (extensions are disable)
How long after, the vscode is available for you?

**Comment by bpasero** [comment] 2016-09-26 05:00
Ok good to hear because this makes sense to be profiled and find out where most time is spend. Can you follow below steps and after starting profiling to the reload action and when everything is loaded stop the profiling?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by mghhgm** [comment] 2016-09-27 07:28
I do this:
[CPU-20160927T104738.cpuprofile.txt](https://github.com/Microsoft/vscode/files/494805/CPU-20160927T104738.cpuprofile.txt)

Thank you

**Comment by bpasero** [comment] 2016-09-27 07:44
@mghhgm thanks so much for the report, we have an idea what it could be.

@joaomoreno fyi

**Comment by chrmarti** [comment] 2016-09-27 16:23
Any way to tell if #12503 is related?

**Comment by bpasero** [comment] 2016-09-27 17:40
@chrmarti telling users to run a profile helps:

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by isidorn** [comment] 2016-09-30 08:08
Not a regression, impact quite low, risky to change in endgame pushing to october

**Comment by miladghiravani** [comment] 2016-09-30 08:49
I think vs code is slowly because this user interface is HTML. When I open _Toggle Developer Tools_ and select an element in the page to inspect it, see all things on vs code user interface is HTML tags ... .
![ashampoo_snap_2016 09 30_12h13m04s_001_](https://cloud.githubusercontent.com/assets/5067331/18986080/100f492a-8708-11e6-8edf-72e112c898fa.jpg)

**Comment by joaomoreno** [comment] 2016-09-30 12:04
@miladghiravani The entire VS Code interface is HTML.

We know what the cause for your issue is and will fix it next month.

**Comment by miladghiravani** [comment] 2016-10-14 16:02
Hi,
In version 1.6.1 , vs code is ready after 7 sec. (~ 46% better)
Is possible better than this?
I can't send CPU profile because [this](https://github.com/Microsoft/vscode/issues/13704).
Thank you

**Comment by joaomoreno** [comment] 2016-10-21 15:14
Nothing really changed in the code path specific to the problem your CPU profile indicated.

**Comment by joaomoreno** [comment] 2016-10-27 09:40
@miladghiravani Can you take a screenshot of a recent CPU profile?

Is there anything special about your system? Is it a VM? Is it an enterprise managed machine?

**Comment by miladghiravani** [comment] 2016-10-27 13:59
@joaomoreno CPU profile have very lines (more than 80 fullscreen images) but I select all and copy them.
**See this: [cpu.txt](https://github.com/Microsoft/vscode/files/556028/cpu.txt)**
My system is [Sony laptop](http://www.sony.com.my/support/product/VPCCW18FG) and I have Windows 8.1 Enterprise 64-bit.
_(For example Photoshop cc 2015 after 11 ~ 12 seconds is ready.)_

**Comment by joaomoreno** [comment] 2016-10-27 14:22
Seems to be much faster now. Do you still experience the 7 seconds of lag as previously mentioned?

I'd like us to try something. Make sure you have Node 6.5 for this. Create a `ssl.js` file with the following contents:

```es6
'use strict'
const https = require('https');
const startTime = new Date().getTime();
https.get('https://marketplace.visualstudio.com', res => {
  console.log(res.statusCode);
  console.log(new Date().getTime() - startTime);
});
```

Then, from the command line, run it with the `--prof` flag:

```
node --prof ssl.js
```

What was the output or running that?

This command will also generate a `isolate-*-v8.log` file. Create a profiling report from it with:

```
node --prof-process isolate-*-v8.log > profile.txt
```

And send me the contents of `profile.txt`.

Here's mine, as a reference point: [profile.txt](https://github.com/Microsoft/vscode/files/556107/profile.txt)

**Comment by miladghiravani** [comment] 2016-10-27 15:42
@joaomoreno I told _"in version 1.6.1 , vs code is ready after 7 sec. (~ 46% better)"_
My Node is v6.5.0
After `node --prof ssl.js` , see this:
200
1927

And profile: [profile.txt](https://github.com/Microsoft/vscode/files/556343/profile.txt)

**Comment by joaomoreno** [comment] 2016-10-27 16:31
You somehow missed the `--prof-process` step. Nevermind, I did it. Here it is for reference:

[profile2.txt](https://github.com/Microsoft/vscode/files/556438/profile2.txt)

I will run the same on another Windows machine so we can compare.

**Comment by joaomoreno** [comment] 2016-10-27 16:34
And here is my profile:

[profile_joao.txt](https://github.com/Microsoft/vscode/files/556467/profile_joao.txt)

**Comment by joaomoreno** [comment] 2016-10-27 16:36
The profiles don't tell us much except that my script runs in 68 ticks while yours takes 1459 ticks. Both show that most of the time is spent inside `ntdll.dll`.

Are you inside a corporate network?

**Comment by miladghiravani** [comment] 2016-10-27 16:44
@joaomoreno 
`Are you inside a corporate network?`
No. I use home network but Xampp is running on my system.

New profile: [profile.txt](https://github.com/Microsoft/vscode/files/556492/profile.txt) is correct?

**Comment by bpasero** [comment] 2016-11-17 08:45
@miladghiravani can you try our latest insider build (http://code.visualstudio.com/Download#insiders), start it and then from the command palette run "Startup performance" and send the output from the console?

**Comment by joaomoreno** [comment] 2016-11-30 08:43
Closing as duplicate of #16065

**Closed by joaomoreno** 2016-11-30 08:43 UTC
Labels: bug, freeze-slow-crash
