### ISSUE TITLE
very slow to process data

### ISSUE THREAD

**Issue by gensysweb6** [microsoft/vscode#164953] opened 2022-10-29 07:51 UTC
Type: <b>Bug</b>

code completion not working well, its take too much time to show the suggestions. and VS Code take too much processor and ram when i change small bit of code after that come back to normal.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (3.67GB free)|
|Process Argv|--crash-reporter-id 3480eab0-ac9b-437c-9349-6b12345dfc72|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
jquerysnippets|don|0.0.1
gitlens|eam|13.0.3
vscode-html-css|ecm|1.13.1
jquery-snippets|Hri|1.0.0
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.0
remote-containers|ms-|0.255.4
vs-keybindings|ms-|0.2.1
es6-css-minify|olb|3.3.3
LiveServer|rit|5.7.9
code-spell-checker|str|2.10.1
tabnine-vscode|Tab|3.6.18
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscodeintellicode-completions|Vis|1.0.20
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
vscutility:30590829
2e4cg342:30596373

```

</details>

**Comment by mjbvz** [comment] 2022-11-02 07:46
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by gensysweb6** [comment] 2022-11-03 06:40
i don't know that yet. but sometimes it will happen and the code suggestions are gone for long.

**Comment by gensysweb6** [comment] 2022-11-03 06:47
i never close the VS code window in my system. i just minimize and go. is that causing this issue?
this issue is happening to me for 2 weeks before.

**Comment by mjbvz** [comment] 2022-11-03 19:20
Please  on insiders with extension disabled

**Comment by gensysweb6** [comment] 2022-11-05 06:26
how to do that?

**Comment by mjbvz** [comment] 2022-11-10 21:23
My comment linked to the insiders install and steps to disable extension

I'm closing since this report is too vague without. You can follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem

**Closed by mjbvz** 2022-11-10 21:23 UTC
Labels: info-needed
