### ISSUE TITLE
API to create custom Activity Bar items and Panels with Extensions

### ISSUE THREAD

**Issue by iBourgeois** [Microsoft/vscode#32970] opened 2017-08-22 17:05 UTC
I have been unable to find any information on whether or not vs code has any plans to support the functionality to allow extensions to create new activity bar items and/or side bar panels. 

Would be useful for creating many types of extensions (team chat, project/time management, sql explorers, cli tool integration (docker, npm, composer, webpack, vagrant, etc...), even less obvious things like music players and documentation). I'm aware that a lot of these extensions exist, but they aren't easily accessible (open command palette, search for extension, select option, enter command...). 

This type of functionality would potentially allow myself and many other developers to work in vs code without ever having to open another tool or leave the editor. 

If this is something that would be considered, I would be willing to work on it. Thanks!

**Comment by Tyriar** [comment] 2017-08-22 18:31
Duplicate of https://github.com/Microsoft/vscode/issues/1833

**Closed by Tyriar** 2017-08-22 18:31 UTC
Labels: feature-request, workbench
