### ISSUE TITLE
Working with md files preview cant split the screen with Drag&Drop

### ISSUE THREAD

**Issue by dbranco** [Microsoft/vscode#34037] opened 2017-09-08 16:52 UTC
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.0
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-simpler-icons|dav|1.4.0
vscode-eslint|dba|1.3.0
angular-extension-pack|dog|0.7.7
git-extension-pack|don|0.1.3
githistory|don|0.2.3
vscode-generate-getter-setter|DSK|0.4.2
gitlens|eam|4.4.3
EditorConfig|Edi|0.10.1
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
rest-client|hum|0.15.2
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.1.4
search-node-modules|jas|1.1.1
docthis|joe|0.4.8
Angular2|joh|2.7.0
refactorix|kri|0.3.6
vs-color-picker|lih|0.6.0
json-to-ts|Mar|1.5.3
Angular-BeastCode|Mik|4.3.15
PowerShell|ms-|1.4.2
typescript-javascript-grammar|ms-|0.0.23
tsimporter|pmn|1.2.14
vscode-icons|rob|7.12.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.4.1
markdown-all-in-one|yzh|0.8.3
vscode-open-in-github|ziy|1.2.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open the markdown preview
2. Click and drag the tab of the preview
3. Try to find a place to drop and create a splitted view.

Reproduces without extensions: Doesn't happen when disabling extensions

**Comment by roblourens** [comment] 2017-09-08 17:40
I can repro, basically we can't drag to create a split view on top of the markdown preview.

**Comment by mjbvz** [comment] 2017-09-08 18:10
Duplicate of #32654

**Closed by mjbvz** 2017-09-08 18:10 UTC
Labels: duplicate, markdown, new release
