### ISSUE TITLE
Loading last tooooo long

### ISSUE THREAD

**Issue by rostamiani** [microsoft/vscode#78452] opened 2019-08-04 15:48 UTC
Issue Type: <b>Bug</b>

When autocompleting in Angular, the list is loading for minutes!

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
ng-template|Ang|0.801.1
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
jsrefactor|cms|2.18.2
angular-schematics|cyr|1.23.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.9.0
angular-extension-pack|dog|7.2.0
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.9.0
bootstrap-4-cdn-snippet|eve|1.2.0
auto-rename-tag|for|0.1.0
minify|Hoo|0.4.3
icon-fonts|idl|2.1.5
angular2-switcher|inf|0.2.0
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
Angular2|joh|8.1.1
vscode-phpfmt|kok|1.0.30
refactorix|kri|0.3.6
sftp|lix|1.12.7
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|8.0.10
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
partial-diff|ryu|1.4.0
html5-boilerplate|sid|1.0.3
numbermonger|sof|0.5.0
move-ts|str|1.11.5
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|9.2.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2019-08-04 21:42
Have you tried to disable some all extensions and see if problem appears?
If it doesn't happen with all extension disabled try to enable them one-by-one to see which one causes slowdown.

**Comment by mjbvz** [comment] 2019-08-11 09:54
Closing as more information is needed. Likely caused by an extension

**Closed by mjbvz** 2019-08-11 09:54 UTC
