### ISSUE TITLE
[Getting Started] Jittering opening animations in Getting Started while VS Code loads

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#124696] opened 2021-05-26 15:32 UTC
Saw this both in clean install and my working instance. The animation for the active element keeps re-opening

https://user-images.githubusercontent.com/8599/119688269-b02bc980-bdfc-11eb-96a9-f334994f9cc0.mp4

Looks like some UI update re-triggers the animations.

**Comment by JacksonKearl** [comment] 2021-05-28 22:26
Duplicate of #124531

**Closed by JacksonKearl** 2021-05-28 22:26 UTC
Labels: getting-started
