### ISSUE TITLE
Install extension fails with EPERM: operation not permitted

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62607] opened 2018-11-05 16:48 UTC
From @VarCharMax, in https://github.com/vuejs/vetur/issues/944.

---

- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: octref.vetur-0.13.0
- VS Code version: 1.28.2

## Problem
Attempting to install vetur in VS Code always fails with message "Failed to install 'octref.vetur"
## Reproducible Case

Attempting to install manually produces the error message 
EPERM: operation not permitted, open 'C:\Users\<username>\.vscode\extensions\.octref.vetur-0.13.0\server\node_modules\stylint\src\checks\noImportant.js'

Attempting to run the install as administrator either through VS Code or via command line produces the same error message.

**Comment by sandy081** [comment] 2018-11-06 09:08
@octref @VarCharMax

Can you please enable the logging level to `trace` using the command `Set Log Level` and share us the Shared Process logs before and after reproducing this? You can find Shared process logs in the Output channel.

**Comment by VarCharMax** [comment] 2018-11-06 23:07
Sorry I need you to be more explicit. Where do I type the command "Set Log level"? Is the Output channel the Output pane of the console? Does the log get saved to a file somewhere?

**Comment by octref** [comment] 2018-11-06 23:18
@VarCharMax Try Ctrl+P (or F1) then type `Set Log Level`:

![image](https://user-images.githubusercontent.com/4033249/48100240-3f3d4b80-e1d7-11e8-8b4d-f06a40d1e4b2.png)

**Comment by sandy081** [comment] 2018-11-08 09:56
@VarCharMax Looks like there is an issue with renaming. May I know if you have Defender running on your system? Can you please try disabling and try?

**Comment by VarCharMax** [comment] 2018-11-08 22:54
I have Defender (I am running Windows 7) but it is disabled via a policy so it is not running.

**Comment by VarCharMax** [comment] 2018-11-12 00:19
Having looked into this further, it appears my PC has a problem creating a file specifically called "important.js". For some reason a system policy is disallowing it. I had a similar problem with the stylehacks library which also has a module called important.js. I thought the library was corrupted but it appears that the problem is with my local machine.

**Comment by sandy081** [comment] 2018-11-12 15:13
@VarCharMax Thanks for confirming. Closing this as it is problem with your system.

**Closed by sandy081** 2018-11-12 15:13 UTC
Labels: extensions, needs more info
