### ISSUE TITLE
Split color themes into UI and Syntax themes

### ISSUE THREAD

**Issue by astamataris** [Microsoft/vscode#22443] opened 2017-03-11 12:08 UTC
I come from Sublime and Atom where you have the option to have a separate theme for the UI (File explorer, tabs etc.) and a different theme for the editor. This allows me to have a light(white) UI and material syntaxt for example. I believe it adds a lot to the customisability of the editor and at least brings it on par with Atom and Sublime.

Good work with what you've done so far!

**Comment by ramya-rao-a** [comment] 2017-03-11 23:33
@bpasero @aeschli Do you want to track this separately or cover this in #3112?

**Comment by bpasero** [comment] 2017-03-12 07:13
I would close this as duplicate of #3112 but I let Martin decide.

**Comment by aeschli** [comment] 2017-03-13 07:31
closing as duplicate of #3112

**Closed by aeschli** 2017-03-13 07:31 UTC
Labels: themes
