### ISSUE TITLE
[Indent][Lua] code indentation failed

### ISSUE THREAD

**Issue by liyu34** [microsoft/vscode#70015] opened 2019-03-08 04:34 UTC
- VSCode Version: 1.32.1 (system setup)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Write some code
2. Insert some blank lines inside the code
3. Move one line up or down to see the auto indent failed

Does this issue occur when all extensions are disabled?: Yes

![lua 2](https://user-images.githubusercontent.com/12342277/54007698-fe157200-419d-11e9-85e2-794f216319bf.gif)

**Comment by rebornix** [comment] 2020-11-03 18:02
/duplicate of https://github.com/microsoft/vscode/issues/54829

**Closed** 2020-11-03 18:02 UTC
Labels: *duplicate, bug, editor-autoindent
