### ISSUE TITLE
Tasks with same name from different workspaces conflict in multi-root workspace environment

### ISSUE THREAD

**Issue by focorner** [microsoft/vscode#93908] opened 2020-03-31 12:12 UTC
- VSCode Version: 1.43.2
- OS Version: macOS Catalina Version 10.15.4

Steps to Reproduce:

1. Create a folder called `vs-code-potential-bug`
2. Then, create `vs-code-potential-bug/project-1` and `vs-code-potential-bug/project-2`
3. Inside each project folder, create a TypeScript project
4. Create a multi-root workspace configuration file; e.g. `vs-code-potential-bug/default.code-workspace`
5. Open that new workspace with VS Code
6. Launch a TypeScript watch task for `project-1`
7. Try launching a TypeScript watch task for `project-2` while the previous watch task is still running.

On my system, that last step prompts a warning box saying: `The task 'tsc: watch - tsconfig.json (Project #1)' is already active.`

![vscode-warning-box-tsc-watch](https://user-images.githubusercontent.com/12765575/78023975-f935da00-732d-11ea-8846-8e963bccf9a3.png)

Does this issue occur when all extensions are disabled?: Yes

## Additional notes

- As far as I can tell, this occurs for any task that has the same name as a task inside another project inside the same multi-root workspace.
- I started noticing this behaviour about two months ago, but, if I recall correctly, I used, with earlier versions of VS Code, to be able to run those "same-named tasks" without problem.

Thank you for your time and support. :)

**Comment by alexr00** [comment] 2020-03-31 12:35
@focorner I fixed something that looks exactly like this recently. Can you try with the insiders build? It installs side by side with stable, so it won't change your current install. https://code.visualstudio.com/insiders/

**Comment by focorner** [comment] 2020-03-31 12:48
@alexr00 I just tried with [Visual Studio Code - Insiders](https://code.visualstudio.com/insiders/) as you recommended and it worked! The problem is no longer there. Great job!

Do you know if this fix will be shipped with the next release?

Thank you very much for your time and support. A+

**Comment by alexr00** [comment] 2020-03-31 13:04
@focorner Thanks for trying it! It is planned to be in the next release.

**Comment by alexr00** [comment] 2020-03-31 13:05
duplicate of https://github.com/microsoft/vscode/issues/93398

**Closed by alexr00** 2020-03-31 13:05 UTC
