### ISSUE TITLE
Extension Testing: Connection Error Downloading VS Code 1.68.0

### ISSUE THREAD

**Issue by Jason3S** [microsoft/vscode#151684] opened 2022-06-10 06:05 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: Mac OS Darwin

Steps to Reproduce:

As part of CI/CD process for [streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker) it runs a simple integration test to ensure the spell checker starts up and finds a spelling issue.

The problem is that downloading VS Code to the test environment has started failing.

```text
Downloading VS Code 1.68.0 from https://update.code.visualstudio.com/1.68.0/darwin/stable
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

- This problem occurs on both Azure and Github Actions. 
- It is only failing for Darwin.
- It fails about 75% of the time needing multiple restarts.

**Comment by chrmarti** [comment] 2022-06-10 09:19
Does it download on the same machine from the browser? Which version of NodeJS are you running the download with?

**Comment by joaomoreno** [comment] 2022-06-10 09:49
Dupe of https://github.com/microsoft/vscode/issues/151588

**Closed by joaomoreno** 2022-06-10 09:49 UTC
Labels: new release
