### ISSUE TITLE
Not able to install in MacOS Catalina (10.15)

### ISSUE THREAD

**Issue by Ravi448** [microsoft/vscode#82271] opened 2019-10-10 17:41 UTC
I just updated my OS to Catalina, and it broke down, I un-installed the editor and trying to re-install it, but that is not able to install.

![Screenshot 2019-10-10 at 11 10 14 PM](https://user-images.githubusercontent.com/29150136/66592714-3c02ca80-ebb3-11e9-8081-82c573b51ece.png)

**Comment by misolori** [comment] 2019-10-10 21:03
Duplicate of #74782

**Closed** 2019-10-10 21:03 UTC
Labels: *duplicate
