### ISSUE TITLE
File gives hints on every line

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#47500] opened 2018-04-09 14:33 UTC
Issue Type: <b>Bug</b>

In a fresh, empty folder, create a file called `features.js`:
```
module.exports = {
    accessibilityHelp: {
      entry: 'vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp',
      worker: undefined,
    },
    bracketMatching: {
      entry: 'vs/editor/contrib/bracketMatching/bracketMatching',
      worker: undefined,
    },
    caretOperations: {
      entry: 'vs/editor/contrib/caretOperations/caretOperations',
      worker: undefined,
    },
    clipboard: {
      entry: 'vs/editor/contrib/clipboard/clipboard',
      worker: undefined,
    },
    codelens: {
      entry: 'vs/editor/contrib/codelens/codelensController',
      worker: undefined,
    },
    colorDetector: {
      entry: 'vs/editor/contrib/colorPicker/colorDetector',
      worker: undefined,
    },
    comment: {
      entry: 'vs/editor/contrib/comment/comment',
      worker: undefined,
    },
    contextmenu: {
      entry: 'vs/editor/contrib/contextmenu/contextmenu',
      worker: undefined,
    },
    coreCommands: {
      entry: 'vs/editor/browser/controller/coreCommands',
      worker: undefined,
    },
    cursorUndo: {
      entry: 'vs/editor/contrib/cursorUndo/cursorUndo',
      worker: undefined,
    },
    dnd: {
      entry: 'vs/editor/contrib/dnd/dnd',
      worker: undefined,
    },
    find: {
      entry: 'vs/editor/contrib/find/findController',
      worker: undefined,
    },
    folding: {
      entry: 'vs/editor/contrib/folding/folding',
      worker: undefined,
    },
    format: {
      entry: 'vs/editor/contrib/format/formatActions',
      worker: undefined,
    },
    gotoDeclarationCommands: {
      entry: 'vs/editor/contrib/goToDeclaration/goToDeclarationCommands',
      worker: undefined,
    },
    gotoDeclarationMouse: {
      entry: 'vs/editor/contrib/goToDeclaration/goToDeclarationMouse',
      worker: undefined,
    },
    gotoError: {
      entry: 'vs/editor/contrib/gotoError/gotoError',
      worker: undefined,
    },
    gotoLine: {
      entry: 'vs/editor/standalone/browser/quickOpen/gotoLine',
      worker: undefined,
    },
    hover: {
      entry: 'vs/editor/contrib/hover/hover',
      worker: undefined,
    },
    inPlaceReplace: {
      entry: 'vs/editor/contrib/inPlaceReplace/inPlaceReplace',
      worker: undefined,
    },
    inspectTokens: {
      entry: 'vs/editor/standalone/browser/inspectTokens/inspectTokens',
      worker: undefined,
    },
    iPadShowKeyboard: {
      entry: 'vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard',
      worker: undefined,
    },
    linesOperations: {
      entry: 'vs/editor/contrib/linesOperations/linesOperations',
      worker: undefined,
    },
    links: {
      entry: 'vs/editor/contrib/links/links',
      worker: undefined,
    },
    multicursor: {
      entry: 'vs/editor/contrib/multicursor/multicursor',
      worker: undefined,
    },
    parameterHints: {
      entry: 'vs/editor/contrib/parameterHints/parameterHints',
      worker: undefined,
    },
    quickCommand: {
      entry: 'vs/editor/standalone/browser/quickOpen/quickCommand',
      worker: undefined,
    },
    quickFixCommands: {
      entry: 'vs/editor/contrib/quickFix/quickFixCommands',
      worker: undefined,
    },
    quickOutline: {
      entry: 'vs/editor/standalone/browser/quickOpen/quickOutline',
      worker: undefined,
    },
    referenceSearch: {
      entry: 'vs/editor/contrib/referenceSearch/referenceSearch',
      worker: undefined,
    },
    rename: {
      entry: 'vs/editor/contrib/rename/rename',
      worker: undefined,
    },
    smartSelect: {
      entry: 'vs/editor/contrib/smartSelect/smartSelect',
      worker: undefined,
    },
    snippets: {
      entry: 'vs/editor/contrib/snippet/snippetController2',
      worker: undefined,
    },
    suggest: {
      entry: 'vs/editor/contrib/suggest/suggestController',
      worker: undefined,
    },
    toggleHighContrast: {
      entry: 'vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast',
      worker: undefined,
    },
    toggleTabFocusMode: {
      entry: 'vs/editor/contrib/toggleTabFocusMode/toggleTabFocusMode',
      worker: undefined,
    },
    transpose: {
      entry: 'vs/editor/contrib/caretOperations/transpose',
      worker: undefined,
    },
    wordHighlighter: {
      entry: 'vs/editor/contrib/wordHighlighter/wordHighlighter',
      worker: undefined,
    },
    wordOperations: {
      entry: 'vs/editor/contrib/wordOperations/wordOperations',
      worker: undefined,
    },
  };
  
```

Observe: each line has a refactoring hint and the lightbulb is permanently visible
![image](https://user-images.githubusercontent.com/5047891/38503918-a71b0ca2-3c13-11e8-8ce8-b5c8188bf473.png)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

**Comment by jrieken** [comment] 2018-04-09 14:43
Is this just one decoration spawning many lines or actually on per line?

**Comment by mjbvz** [comment] 2018-04-09 14:55
Duplicate of #47346. It's a single hint, the rendering is just off. Probably should look into this for the recovery build

**Closed by mjbvz** 2018-04-09 14:55 UTC
Labels: needs more info
