### ISSUE TITLE
Extension Pack - Optionally loading extension dependencies

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#48873] opened 2018-04-28 03:57 UTC
An extension pack itself is also an extension which can have some code logic. When a pack is activated as an extension, all the extensions listed in the ```extensionDependencies``` are automatically activated. This behavior may not be ideal because the pack's role is to install several extensions together but not necessarily load them all at the same time when the pack is loaded.

The documentation also echos that:
https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_extension-packs
The extensions listed in extensionDependencies will be installed. But there is no clear statement of lifecycle, e.g. extension dependencies being activated whenever the pack extension is activated.

Here to request that vscode provide a mechanism of optionally activating these dependencies. Here's one scenario to consider:
1. The pack extension tries to show a welcome page of the packed extensions.
2. The pack extension needs to be loaded to show the welcome page, WITHOUT loading the dependency extensions.
3. When some logic on the welcome page is triggerred, e.g. creating a new project, the pack then call a command from a specific extension, and this is when the extension is activated.

**Comment by sandy081** [comment] 2018-05-02 08:43
@akaroml What is the activation event for the pack?

**Comment by akaroml** [comment] 2018-05-10 03:53
@sandy081 the pack is activated when a command is triggered.

**Comment by sandy081** [comment] 2018-05-15 08:29
@alexandrudima May I know if activating an extension also activates its dependencies?

**Comment by alexandrudima** [comment] 2018-05-15 10:36
If an extension `A` mentions extension `B` as an `extensionDependency`, then it is guaranteed that extension `B` is installed and activated (correctly) before activating `A`.

If `B` is not installed or if `B` fails to activate, then `A` will not be activated.

I understand extension packs make use of `extensionDependency`, but the guarantee above is in our system since before we had extension packs and we cannot remove or relax it. I suggest extension packs use a different mechanism than `extensionDependency` if the intent is just to install another extension.

**Comment by akaroml** [comment] 2018-05-22 06:19
@alexandrudima thanks for the info. So does vscode have a mechanism to achieve what you described? That behavior is exactly what we want. I see lots of extension packs use extensionDependency as the underlying mechanism and I'm not aware of other choices.

**Comment by sandy081** [comment] 2018-05-22 08:53
@akaroml Only supported mechanism to define extensions in an extension pack is by `extensionDependency`

**Comment by akaroml** [comment] 2018-05-24 06:37
@sandy081 thanks for the confirmation.

Then I would like to ask for a mechanism to allow installation-only extension dependency. This will be super useful for the extension pack scenario. Most packs' purpose is to recommend extension combinations and they do not necessarily need to have runtime dependency on those extensions.

I'd like to borrow the concept of peer dependency from npm but give it a new name peerExtensions. An extension would only work when all the peer extensions are ***installed***.

**Comment by chrisdias** [comment] 2018-06-20 14:51
isn't this then a dupe of https://github.com/Microsoft/vscode/issues/48430?

**Comment by sandy081** [comment] 2018-06-20 15:01
Yes. it is.

**Closed** 2018-06-20 15:02 UTC
Labels: *duplicate, extensions, under-discussion
