### ISSUE TITLE
Key remapping using xkbd options broke with the keybinding changes in 1.11

### ISSUE THREAD

**Issue by lorenz** [Microsoft/vscode#24220] opened 2017-04-07 12:32 UTC
- VSCode Version: 1.11.0
- OS Version: Ubuntu 16.10

I originally commented in #24057 but was told to open a separate issue.

I use the xkb option `caps:swapescape` to map my ESC key to the caps lock key in my keyboard layout because I like to use Vim mode for editing in VSCode. Since 1.11.0 VSCode caps lock does nothing (not even switch capitalization). The ESC key actually acts as an ESC key in VSCode but switches captitalization.

Since 1.11 can now read the keyboard layout it probably just does not handle options on it and therefore gets the key mapping wrong.

**Comment by dsifford** [comment] 2017-04-07 14:57
Same issue here!

**Comment by mcfletch** [comment] 2017-04-07 14:59
This interferes with any custom keyboard layout mapping for X11 using e.g. xmodmap. For instance, remappings that fix inappropriate/broken keyboard layouts. The key-mappings remain available across the bulk of MSCode (dialogs, etc), but *not* in the text editor window. (I'm on Kubuntu 16.10 w/ MSCode 1.11.0)

Test case (assumes a regular US-english keyboard layout):
$ xmodmap -e "keycode 105 = End"

Now your right-control key should be remapped to act like the End key (test to be sure before proceeding, if not, use xev to discover the keycode of your right-control key). Start MSCode, open a text file and you'll find it doesn't act as an End key in the text editor.

**Comment by dsifford** [comment] 2017-04-07 15:02
@mcfletch Confirmed here.. I use xmodmap to map my esc key to caps lock.

Distro: Arch Linux

**Comment by chrmarti** [comment] 2017-04-07 15:12
Is this all with U.S. English keyboard layouts?

**Comment by mcfletch** [comment] 2017-04-07 15:17
@chrmarti the keyboard layout shouldn't change the behaviour, it just controls the keycode's used in setting up the test case for replication. In my case, yes, us-english XPS 15.

**Comment by Wehrdo** [comment] 2017-04-07 16:56
I just want to add that this also affects the default Colemak keyboard layout on Ubuntu 16.04, which assigns the caps lock key to backspace. I'm not sure how Ubuntu handles that under the hood, but it's at least another datapoint to check.

**Comment by hstefan** [comment] 2017-04-07 18:59
Also having the same problem as @Wehrdo, but on Arch Linux with Cinnamon.

**Comment by lorenz** [comment] 2017-04-07 21:24
Affects Swiss and US keyboard layouts here.

**Comment by hstefan** [comment] 2017-04-10 02:24
It may already be known, but I bisected throw 1.10.2 and 1.11.1 and found out that commit d1023963 introduced this problem.
I'll have a look myself and see if I contribute fixing it, but as I have zero experience with the stack I can't make any promises, which is why I'm focusing on sharing what I've found out so far.

**Comment by alexandrudima** [comment] 2017-04-10 08:34
Duplicate of #23991. A workaround is detailed in https://github.com/Microsoft/vscode/issues/23991#issuecomment-292336504

**Closed by alexandrudima** 2017-04-10 08:34 UTC
