### ISSUE TITLE
VSCode consumes all RAM if opening a huge directory

### ISSUE THREAD

**Issue by ksamuel** [Microsoft/vscode#46529] opened 2018-03-26 08:36 UTC
- VSCode Version:

Version 1.21.1

- OS Version:

Ubuntu 16.04

Steps to Reproduce:

1. Open a huge directory with vscode. E.G: the system root
2. VSCode will complain it can't open enough file descriptors, and offer you to follow a link to solve this, which tells you to do something on the line of `sysctl -w vm.dirty_bytes=50331648`
3. Ropen the same directory with vscode and wait while it tries to crawl the entire directory tree
4. See it consumes all RAM, swap and forces you to kill it to prevent a machine freeze

Does this issue occur when all extensions are disabled?: Yes/No

I really don't want to try and freeze my whole machine again to check this.

**Comment by dbaeumer** [comment] 2018-03-26 11:38
Not sure who bests owns this :-)

**Comment by bpasero** [comment] 2018-03-26 12:26
Duplicate of https://github.com/Microsoft/vscode/issues/3998

**Closed by bpasero** 2018-03-26 12:26 UTC
