### ISSUE TITLE
Markdown file formating breaks when file is added into git staging area

### ISSUE THREAD

**Issue by Stephanevg** [Microsoft/vscode#31432] opened 2017-07-26 06:54 UTC
Hi guys,

I have an issue that breaks the formating of a markdown file as soon as we add it into a git repository.

The gif here under shows what the issue is, and how to reproduce it.
![2017-07-25_14-17-20](https://user-images.githubusercontent.com/6302961/28608076-376bb338-71df-11e7-8828-ee83d289a294.gif)

The Gist of the readme.md is available here --> https://gist.github.com/Stephanevg/dc3e11a64c89047e0e8794a3816a442b

I double checked, the file  format with a PS function. It was **'ASCI'** before **and** **after** I added it to the staging area.

System Details

Operating system name and version: seen on Windows 10 (Issue also

$pseditor.EditorServicesVersion

1.14.1
2648980a697a4c8fb5777dcfb2ab110cec8a2f58

code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.1

$PSVersionTable
$PsVersionTable:

Name Value

PSVersion 5.0.10586.962
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.10586.962
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Comment by mjbvz** [comment] 2017-07-26 19:08
Does this happen with other file types or just markdown? Does it repo if you disable all extensions by starting code with the `--disable-extensions` command line flag

**Comment by Stephanevg** [comment] 2017-07-26 19:38
Yes

**Comment by mjbvz** [comment] 2017-07-27 05:06
@Stephanevg Yes it happens for other file types and with extensions disabled?

**Comment by Stephanevg** [comment] 2017-07-27 07:23
yes it does for both:

on other file types (.ps1 here in the example)

![image](https://user-images.githubusercontent.com/6302961/28658758-13ba8922-72ad-11e7-8d98-df6051db3683.png)

and when I launch code using the following line from the command line:

`code --disable-extensions`

**Comment by mjbvz** [comment] 2017-07-27 15:31
@joaomoreno Can you please take a look since this seems an issue with encoding with a git

**Comment by joaomoreno** [comment] 2017-07-27 20:01
What is your `files.encoding` setting value?

**Comment by Stephanevg** [comment] 2017-07-27 20:18
In the the files.encoding I have
`  "files.encoding": "utf8",`

If I check the file in format in the status bar, I have UTF16-LE

![image](https://user-images.githubusercontent.com/6302961/28690363-2f677966-7319-11e7-8ff5-3728a030019a.png)

When I create a new file (wihtout extension), it indeed creates a utf8.

**Comment by joaomoreno** [comment] 2017-07-28 06:29
Interesting. Git will pick up whatever you have set in `files.encoding` and use that, so that explains what you're seeing.

Duplicate of #21146

**Closed by joaomoreno** 2017-07-28 06:29 UTC
Labels: needs more info

**Comment by Stephanevg** [comment] 2017-07-28 07:40
ok, but format should it be, to avoid to have these weird symbols in my files?

**Comment by joaomoreno** [comment] 2017-07-28 07:47
Oh, save it as UTF-8 and you'll be fine. 👍
