### ISSUE TITLE
Button to ignore excludes should not be persisted in storage

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#62256] opened 2018-10-31 09:47 UTC
I just wondered why a search would always ignore my exclude rules and only after a while I figured out that this button was not checked:

![image](https://user-images.githubusercontent.com/900690/47779835-5b824980-dcfa-11e8-9420-f22f61cf0652.png)

I think we should:
* either not store this in storage so that after a reload this button is checked again
* show a warning that the exclude rules are ignored

**Comment by roblourens** [comment] 2018-10-31 16:23
I expand the query details when starting up if that button is toggled off to make sure you see it. But why should it be different from other buttons in terms of persistence? It would be annoying to untoggle it every time.

**Comment by roblourens** [comment] 2018-10-31 16:24
But this is a common issue so I agree re: warning. https://github.com/Microsoft/vscode/issues/46353

**Comment by bpasero** [comment] 2018-10-31 16:59
Well, even I as a long time Code user thought this was a bug in search, so maybe a warning or some stronger indicator would be wise.

**Comment by roblourens** [comment] 2018-10-31 17:14
Closing as dupe of #46353 (and I added it to november)

**Closed** 2018-10-31 17:17 UTC
