### ISSUE TITLE
Menu clipped in settings editor with few results

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#164725] opened 2022-10-26 16:52 UTC
1. Have large window
2. Open settings editor and search for a modified setting
3. With only 1 result and a huge window, there should be a lot of whitespace below
4. Click gear menu for setting

<img width="136" alt="image" src="https://user-images.githubusercontent.com/6561887/198086971-be234c0f-e6a4-4026-9ee3-a1b53e75d10e.png">

🐛 => menu is clipped by the list container not occupying the full space of the window. this is caused as the dropdown menu is a child of the gear icon element for focus reasons.

**Comment by rzhao271** [comment] 2022-10-26 17:21
Duplicate of #164602

**Closed by rzhao271** 2022-10-26 17:21 UTC
