### ISSUE TITLE
Sticky scroll messes with dirty diff scroll position

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#176941] opened 2023-03-13 08:27 UTC
I am opening a simple one line change in dirty diff.

Here's sticky scroll disabled:

<img width="753" alt="Screenshot 2023-03-13 at 09 21 42" src="https://user-images.githubusercontent.com/22350/224646650-ab37ea99-daa3-462e-834b-d34bac2e1183.png">

Here's sticky scroll enabled:

<img width="776" alt="Screenshot 2023-03-13 at 09 21 23" src="https://user-images.githubusercontent.com/22350/224646639-a66bfd8e-a200-4731-b765-75d129f00183.png">

**Comment by aiday-mar** [comment] 2024-12-13 17:56
duplicate of https://github.com/microsoft/vscode/issues/227750

**Closed by aiday-mar** 2024-12-13 17:56 UTC
Labels: bug, diff-editor, editor-sticky-scroll
