### ISSUE TITLE
Emmet abbreviations don't expand unless there is a space after it

### ISSUE THREAD

**Issue by diogocorrea** [Microsoft/vscode#32478] opened 2017-08-14 14:13 UTC
Emmet abbreviations don't expand when writing single line CSS.

![emmet](https://user-images.githubusercontent.com/546959/29275449-80dbdd52-80e1-11e7-9745-0d8bdb3a672c.gif)

- VSCode Version: 1.16.0-insider (1.16.0-insider)
- OS Version: macOS 10.12.6

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Ciantic** [comment] 2017-08-14 14:26
This is not related to CSS only, the bug happens with JSX too:

type e.g. `{div|}` (cursor is the pipe) and press the expand abbreviation. Nothing happens.

The bug is related that there is character after the word.

**Comment by ramya-rao-a** [comment] 2017-08-14 16:27
Root cause is that we try to look ahead when extracting abbreviation out of current text.

See https://github.com/emmetio/extract-abbreviation/blob/master/index.js#L28

This helps with emmet suggestions For eg: You can keep typing inside the `{}` in the abbreviation `.hello{My name is|}` and the emmet suggestion preview will keep getting updated.

But when running the command `Emmet: Expand Abbreviation` explicitly, this messes things up.
In case of `.foo{dib|}` instead of `dib` getting extracted as an abbreviation, `.foo{dib}` gets extracted.
In case of `{stuff.map(t => div|)}` instead of `div`, `{stuff.map(t => div|)}` gets extracted

This look ahead is not required when explicitly running the `Emmet: Expand Abbreviation` command as one would always run the command with cursor at the end of the abbreviation.

**Comment by ramya-rao-a** [comment] 2017-08-14 21:10
Thanks for reporting @diogocorrea and @Ciantic 

This will be fixed in tomorrow's Insiders build and will be released in the July Recovery Build of 1.15.1 in a few days

**Closed by ramya-rao-a** 2017-08-14 21:10 UTC
Labels: bug, candidate, emmet, insiders
