### ISSUE TITLE
TS Server fatal error:  Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/vscode#135311] opened 2021-10-18 17:53 UTC
We have written the needed dat
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.0-dev.20211017

**Steps to reproduce crash**
1. 
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:56857:22)
    at getPropertyOfType (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:57507:24)
    at tryGetQualifiedNameAsValue (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49319:26)
    at resolveEntityName (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49376:133)
    at getSymbolOfPartOfRightHandSideOfImportEquals (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49299:24)
    at getTargetOfImportEqualsDeclaration (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:48756:28)
    at getTargetOfAliasDeclaration (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49118:28)
    at resolveAlias (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49167:30)
    at resolveSymbol (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:49157:67)
    at mergeSymbol (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47516:42)
    at c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47631:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47629:20)
    at mergeSymbol (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47540:21)
    at c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47631:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47629:20)
    at initializeTypeChecker (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:84750:21)
    at Object.createTypeChecker (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:47287:9)
    at Object.getTypeChecker (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:114100:79)
    at synchronizeHostData (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:159306:21)
    at Object.getProgram (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:159427:13)
    at AutoImportProviderProject.Project.updateGraphWorker (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:164437:53)
    at AutoImportProviderProject.Project.updateGraph (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:164366:42)
    at AutoImportProviderProject.updateGraph (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:165211:70)
    at Object.updateProjectIfDirty (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:165848:45)
    at InferredProject.Project.getPackageJsonAutoImportProvider (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:164986:32)
    at InferredProject.Project.updateGraph (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:164404:26)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:166543:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:168232:26)
    at c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:168506:97
    at Object.flatMap (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:168506:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:169664:46)
    at c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:171597:88
    at IOSession.Session.executeWithRequestId (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:171588:28)
    at IOSession.Session.executeCommand (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:171597:33)
    at IOSession.Session.onMessage (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:171623:35)
    at Interface.<anonymous> (c:\Users\louis\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211017\node_modules\typescript\lib\tsserver.js:174228:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code - Insiders 1.62.0-insider (729d81623815a428160b93e930054a1a2a5403ef, 2021-10-18T05:21:09.596Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.12GB free)|
|Process Argv|--crash-reporter-id a9b9765c-4084-42ad-bf63-ecfbebd2ab2b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
string-converter|ada|0.1.2
vscode-javascript-snippet-pack|aka|0.1.6
to-typescript|ale|0.3.0
assemblyscript-lang|bat|0.3.2
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.44.4
vscode-quick-select|dba|0.2.9
githistory|don|0.6.18
vscode-wasm|dts|1.3.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
code-runner|for|0.11.6
vscode-pull-request-github|Git|0.31.0
rest-client|hum|0.24.5
vscode-text-pastry|jkj|1.3.0
pwa-tools|joh|0.1.0
azure-pipelines|ms-|1.191.0
vscode-apimanagement|ms-|1.0.3
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.5.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.8.1
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.1008
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.17.0
vscode-dotnet-runtime|ms-|1.3.0
vscode-edge-devtools|ms-|1.3.1
mssql|ms-|1.10.1
python|ms-|2021.10.1336267007
vscode-pylance|ms-|2021.10.1
jupyter|ms-|2021.10.1001353885
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
vscode-ai-remote|ms-|0.4.0
remote-containers|ms-|0.202.4
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.9
azurecli|ms-|0.5.0
cpptools|ms-|1.7.0
js-debug-companion|ms-|1.0.15
js-debug-nightly|ms-|2021.10.1317
makefile-tools|ms-|0.2.2
powershell|ms-|2021.10.0
typescript-javascript-grammar|ms-|0.0.55
vscode-node-azure-pack|ms-|0.2.1
vscode-typescript-next|ms-|4.5.20211017
vsonline|ms-|1.0.3076
team|ms-|1.161.1
azurerm-vscode-tools|msa|0.15.4
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.7.1
platformio-ide|pla|2.3.3
qub-textedits|qub|1.0.0
typescript-hero|rbb|3.0.0
text-marker|ryu|1.11.0
vba|spe|1.7.1
addDocComments|ste|0.0.8
ms-teams-vscode-extension|Tea|2.7.0
html-preview-vscode|tht|0.2.5
designeditor|tiz|1.1.0
tizenweb|tiz|1.1.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
azure-iot-toolkit|vsc|2.16.6
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.4.6
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0
vscode-icons|vsc|11.6.0
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
debug|web|0.25.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30382699
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis400:30381677
vsaa593:30376534

```

</details>

a into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment] 2021-10-18 22:57
Duplicate of https://github.com/microsoft/TypeScript/issues/45874

**Closed by mjbvz** 2021-10-18 22:57 UTC
