### ISSUE TITLE
Click on text selection does nothing

### ISSUE THREAD

**Issue by Neptilo** [Microsoft/vscode#48270] opened 2018-04-20 12:16 UTC
Issue Type: <b>Bug</b>

* Select a portion of text in an editor.
* Click somewhere on the selection (or somewhere outside of the highlighted text but on the same line, before the beginning and the end of the selection). The user may want to do this for example to deselect or the create another selection.
* Nothing happens. The previous selection remains.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|Memory (System)|31.92GB (20.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment] 2018-04-23 07:51
If you would like to disable drag & drop in the editor you can use `"editor.dragAndDrop": false`.

**Comment by Neptilo** [comment] 2018-04-23 16:02
I'll try this as a workaround, but obviously the bug needs to be fixed. In
most text editors I can think of, both clicking on the selection to
deselect, and drag-and-drop are possible at the same time.

**Comment by rebornix** [comment] 2018-09-06 21:34
@Neptilo did you click on the selection and then immediately release the mouse? If so the selection will shrink to a single cursor.

**Comment by Neptilo** [comment] 2018-09-07 07:47
@rebornix Yes, that's what I do and your description is what I would expect but that doesn't happen for me.
The bug still happens in version 1.27.1.

**Comment by rebornix** [comment] 2018-09-07 17:19
![dnd-click](https://user-images.githubusercontent.com/876920/45233287-148e4f80-b287-11e8-9222-eed34a0ea5ac.gif)

Above is what I see with drag and drop and some clicking, what I did 

* Double click to select a word, then single click on the selection, the selection shrinks
* Double click to select a word, then single click on text before the selection, the selection shrinks
* Double click to select a word, then single click on text after the selection, the selection shrinks
* Double click to select a word, then single click on selection and hold mouse click, drag a bit and release the mouse, the selection doesn't change

The results are all as expected. Could you please share similar gifs to help troubleshoot? I'm trying to find a good reproduce for this issue and thanks for your help!

**Comment by Neptilo** [comment] 2018-09-10 09:44
This is exactly what I was doing and the selection didn't shrink in any of those cases.
However I have installed VS Code on another machine (Windows 7) and the bug didn't occur. It must be a problem with my specific configuration.
I'm on vacation now and don't have access to the machine where the bug occurs, but I'll try re-installing VS Code and test again as soon as I get back, on the 21st.

**Comment by rebornix** [comment] 2018-09-10 21:00
@Neptilo no hurries and enjoy your vacation.

**Comment by rebornix** [comment] 2018-09-11 23:41
I think this issue shares the same root cause as https://github.com/Microsoft/vscode/issues/58117#event-1838652209 where we fail to fall back to mouse clicking if we click on the whitespace area near the selection. From tomorrow's Insider, this fix is in and we can verify.

**Closed by rebornix** 2018-09-11 23:41 UTC
Labels: editor-drag-and-drop, needs more info, under-discussion

**Comment by Neptilo** [comment] 2018-09-21 08:52
Hello @rebornix , I updated from 1.27.1 to 1.27.2 and the bug still occurred, then deinstalled and reinstalled VS code (but it said it was keeping my settings) and I think the bug still occurred, but after playing around with selections and drag-and-drops for a bit, I must have reset something and am not able to reproduce the bug anymore.
