### ISSUE TITLE
ExtensionHost high CPU usage

### ISSUE THREAD

**Issue by zendu** [microsoft/vscode#165869] opened 2022-11-08 21:46 UTC
Type: <b>Bug</b>

ExtensionHost is constantly consuming ~20% of CPU.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.21GB free)|
|Process Argv|--crash-reporter-id 9a72daf1-1874-4d6f-a4f9-6a0336de31d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-sequence-diagrams|Ale|0.4.7
ng-template|Ang|14.2.0
previewseqdiag-vscode|ari|0.4.1
markdown-mermaid|bie|1.15.2
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.0.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
vscode-firefox-debug|fir|2.9.8
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.220
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.7.2
rainbow-csv|mec|3.3.0
azure-pipelines|ms-|1.208.0
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
sarif-viewer|MS-|3.3.1
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.2
azurecli|ms-|0.5.0
live-server|ms-|0.4.3
powershell-preview|ms-|2022.10.2
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5762
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.8
vscode-mscgen|msc|1.2.0
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
kuskus-kusto-language-server|ros|1.0.28
kuskus-kusto-syntax-highlighting|ros|1.1.21
angular-spec-generator|Tho|1.3.0
vscode-bond|yiw|0.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce2:30605431
iaj6b796:30604794
dbltrim-noruby:30604474

```

</details>

**Comment by zendu** [comment] 2022-11-08 21:48
For some reason, this also causes Antimalware service and UevAppMonitor.exe processes to consume lot of CPU. My system is stuck at 100% CPU usage. Even after restarting.

**Comment by joyceerhl** [comment] 2022-11-08 22:24
Does CPU usage remain high after disabling all extensions? If so you can use `Help: Start Extension BIsect` to identify the extension that's causing the problem.

**Comment by zendu** [comment] 2022-11-10 00:38
Disabling all extensions helps. But bisect did not help. It shows following message after first iteration.

Extension Bisect

[Content]
Extension Bisect is done but no extension has been identified. This might be a problem with Code.

**Comment by alexdima** [comment] 2022-11-25 22:35
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by alexdima** [comment] 2022-11-28 10:03
Thank you for your prompt answer. This indicates either that this is not a vscode issue, or that it was a vscode issue fixed in the meantime (past month), so there is nothing to do on our side. 

---

In my experience, the high CPU usage of the extension host process is never caused by vscode, but by an installed extension. If you want to try to find out which one it is and create an issue against it, you can try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Closed by alexdima** 2022-11-28 10:03 UTC
Labels: info-needed
