### ISSUE TITLE
Enable auto closing the } bracket inside string templates

### ISSUE THREAD

**Issue by lidderupk** [Microsoft/vscode#28053] opened 2017-06-05 17:44 UTC
This is an enhancement request. 

- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Type ```console.log(`this is ${`)```
2. Enable vscode to insert '}' and place cursor between {}.

```console.log(`this is ${|}`)```

**Comment by mjbvz** [comment] 2017-10-12 00:32
This may depend on #34857

**Comment by mjbvz** [comment] 2017-12-19 23:43
Auto-closing works in cases such as:

```
`a ${ a`
```

but not in cases like:

```
`a ${a`
`a ${`
```

The root cause is detailed #18120.

Our current behavior is consistent with sublime, but Atom has the described auto-closing behavior in the `a ${` case

**Comment by mjbvz** [comment] 2018-03-06 04:40
Closing as duplicate of #18120

**Closed by mjbvz** 2018-03-06 04:40 UTC
Labels: editor-autoclosing, feature-request, javascript, languages basic, typescript
