### ISSUE TITLE
[Feature Request] VSC explorer isolate folder

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [microsoft/vscode#148486] opened 2022-04-30 18:59 UTC
When we have a lot of folders, we need to simplify view for better concentrate and orientation
![image](https://user-images.githubusercontent.com/38717657/166119137-447f4116-1a3a-464a-bab9-a06b115b51b6.png)

**Comment by albertosantini** [comment] 2022-04-30 19:23
Did you try https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree?

**Comment by AmelianceSkyMusic** [comment] 2022-04-30 20:12
> Did you try https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree?

Can I filter only folders?
When I'm trying to filter folder, files inside needed folder also hides
https://streamable.com/km3h91

**Comment by JacksonKearl** [comment] 2022-05-03 16:57
You can configure `files.exclude` to hide the other folders, otherwise duplicate of #41860

**Closed by JacksonKearl** 2022-05-03 16:57 UTC
