### ISSUE TITLE
TASK: with "args" ,build command error

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#79269] opened 2019-08-16 04:37 UTC
Issue Type: <b>Bug</b>

'dotnet build' /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
dotnet build: command not found

VS Code version: Code - Insiders 1.38.0-insider (8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b, 2019-08-15T07:37:38.653Z)
OS version: Windows_NT x64 10.0.18956
Remote OS version: Linux x64 4.4.0-18956-Microsoft

the command should be :

dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
dotnet build: command not found

![Uploading tas with args error.png…]()

**### with the args, the command is 'dotnet build', shouldn't with ''.**

here is the task file:
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet build",
            "type": "shell",
            "args": [
                // Ask dotnet build to generate full paths for file names.
                "/property:GenerateFullPaths=true",
                // Do not generate summary otherwise it leads to duplicate errors in Problems panel
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}`

**Comment by alexr00** [comment] 2019-08-16 09:02
Duplicate of https://github.com/microsoft/vscode/issues/78976

**Closed** 2019-08-16 09:02 UTC
Labels: *duplicate, tasks

**Comment by kinglionsz** [comment] 2019-08-16 10:06
> Duplicate of #78976

tks.

I noticed that issue  (#78976) before I disclosed #79269. I thought it explained to me NOT  clearly.It's no matter with the dotnet extensions.

and now I have updated VS CODE and build the task,there is no any build information in the terminal,why?
pls check.

  tks.  @alexr00 

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "shell",
            "args": [
                "build",
                // Ask dotnet build to generate full paths for file names.
                "/property:GenerateFullPaths=true",
                // Do not generate summary otherwise it leads to duplicate errors in Problems panel
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
`

<img width="623" alt="tas with args error now ok or not" src="https://user-images.githubusercontent.com/51827261/63160472-6e2efa80-c050-11e9-8865-5af7b354286f.png">

**Comment by kinglionsz** [comment] 2019-08-16 14:22
btw,if without any args,it's ok to build task with the “default ” command "dotnet build"  😃😃😃
@alexr00 @doudou @threeve @AArnott 

![image](https://user-images.githubusercontent.com/51827261/63173997-a8f65a00-c073-11e9-853d-12619b8e2b47.png)
