### ISSUE TITLE
TypeScript file needs to be open for symbol search to work

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#17393] opened 2016-12-16 13:53 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (89bdb7c35a89535612d386199ee33e6bd74ee068, 2016-12-15T07:11:14.563Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.2|
|githistory|donjayamanne|0.1.4|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|typescript-javascript-grammar|ms-vscode|0.0.12|
|vscode-subword-navigation|ow|1.1.5|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|4.1.0|
|annotator|ryu1kn|0.10.1|
|cucumber|stevejpurves|0.9.6|

---

Steps to Reproduce:

1. Open a typescript project
2. Make sure all files are closed
3. Search for a symbol - nothing will come up
4. Open a typescript file
5. Search for a symbol - the results will show, even if that symbol is not related to the currently opened file

**Comment by mjbvz** [comment] 2016-12-16 19:53
@dbaeumer I sent out a PR #17412 to make the TS extension activate when the workspace contains a jsconfig or tsconfig file, but this alone will not fix this issue. We'll still need to update the workspaceSymbolProvider to be smarter about finding a ts file for the `navto` request. Right now, it only looks in `workspace.textDocuments`

**Comment by dbaeumer** [comment] 2016-12-18 20:10
@mjbvz without good support for this from TSServer this will never be a nice experience so I stayed away from doing workarounds here. For example the contains tsconfig.json (or jsconfig.json) only works if these files are in the root. It doesn't if in a sub folder. So adding this might cause more confusion than it helps.

In addition it is very hard to pick the right TS file for the NavTo request (consider that case where you have 2 tsconfig.json files in one workspace folder). IMO we need to ask the TS team to provide us with a request without a file and they do the smartness of opening and scanning the projects. 

As said I would push the TS team for better support here.

**Comment by waderyan** [comment] 2016-12-19 18:29
FYI I have this prioritized on my end.

**Comment by massimocode** [comment] 2016-12-20 09:19
Thank you everyone for your responses.

Just to give some feedback as a user, I would feel comfortable being asked to provide something in the workspace config to tell VSCode how to treat the project. I feel like that's a little similar with how I have to specify a tasks.json file to tell VSCode how to build the TypeScript.

But as always, if it could `automagically` do it that would be awesome. Although it would be interesting to see how it would handle more complex use cases such as opening a folder that contains several different typescript projects (i.e. maybe something like a Node JS backend and an Angular 2 front end that use different compiler options and different Node packages).

**Comment by mjbvz** [comment] 2017-04-25 00:47
I believe this is a duplicate of #17022

**Closed by mjbvz** 2017-04-25 00:47 UTC
Labels: duplicate, feature-request, javascript, typescript
