### ISSUE TITLE
Compare editor is not reused when "Open Mode" is set to "doubleClick"

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode#95921] opened 2020-04-22 21:16 UTC
- VSCode Version:
- OS Version:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a workspace with 2 or more changes/staged changes to a git repo.
1. In the "Source Control" sidebar, single click on a change to open it
1. Single click on a second change. Note **the compare editor is reused**.
1. close all editors and change preference to `"workbench.list.openMode": "doubleClick",`
1. Double-click on a change
1. Double-click on a second change.  **Another compare editor is opened**. even though the first editor's tab was display with italics.

The compare editor should be reused when double-clicking the same as it was when using single-click mode.

**Comment by joaomoreno** [comment] 2020-04-27 14:42
Strange, it seems that when opening the second change, the first one gets pinned.

**Comment by dinofx** [comment] 2020-10-06 19:44
"agora parece que piorou"

Now the behavior might be worse.  With doubleClick open mode, I can't get an editor to open in "preview" mode from the Explorer or the Source Control views.  Having things expand/collapse, or staying selected when you right click on something else in a tree, is really unintuitive.

**Comment by joaomoreno** [comment] 2020-11-02 14:21
> Now the behavior might be worse. With doubleClick open mode, I can't get an editor to open in "preview" mode from the Explorer or the Source Control views. Having things expand/collapse, or staying selected when you right click on something else in a tree, is really unintuitive.

Yeah I can confirm this. Unfortunately closing as designed, since preview mode aligns better with the single click action. When double clicking, it's assumed the user really wants to open the file. Sorry about that!

**Closed by joaomoreno** 2020-11-02 14:21 UTC
Labels: bug, help wanted, list, scm

**Comment by dinofx** [comment] 2020-11-02 15:14
Joao, given that preview mode no longer exists with "doubleClick", could we just get a new preference to reuse open compare editors?  I know you can set an editor limit for VS Code in general, but viewing an outgoing delta is a special activity that really only needs an editor limit of 1 (unless the document is dirty).

You can find similar features in other tools like eclipse ("Reuse open compare editor")

**Comment by joaomoreno** [comment] 2020-11-02 16:06
@bpasero For comments.
