### ISSUE TITLE
Always show message about workspaceFolder variable

### ISSUE THREAD

**Issue by jsrrosario** [microsoft/vscode#95138] opened 2020-04-13 18:17 UTC
Issue Type: <b>Bug</b>

First step
create a wokspace with multiple root project

Second step
Create a launch.json file configuration  with debug information.

third step
just create any file or just change and save a file that already exists

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|15.45GB (0.32GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eclipse-keybindings|alp|0.10.0
ng-template|Ang|0.901.0
vscode-color|ans|0.4.5
vscode-toggle-quotes|Bri|0.3.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.7.1
html-slim-scss-css-class-completion|gen|1.5.23
rest-client|hum|0.23.2
expand-region|let|0.1.4
vscode-cosmosdb|ms-|0.12.2
azure-account|ms-|0.8.9
debugger-for-chrome|msj|4.12.6
vscode-yaml|red|0.7.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.2
vscode-icons|vsc|10.1.1
complete-statement|wea|0.0.2016

</details>

**Comment by gjsjohnmurray** [comment] 2020-04-13 18:47
/duplicate of #94725 for which a fix is due in the upcoming 1.44.1 recovery release.

**Closed** 2020-04-13 18:48 UTC
Labels: *duplicate
