### ISSUE TITLE
Tab Key Moves Focus

### ISSUE THREAD

**Issue by nickclasener** [Microsoft/vscode#38280] opened 2017-11-14 05:52 UTC
Any time i hit tab my file loses focus to the ui
There is a setting called "Tab Key Moves Focus" "ctrl+m", to my understanding this should turn this on and of.
I have deleted any and every file of vscode installed a number of versions.
It is turned on and i cant turn it on no matter if i press ctrl+m or not

- VSCode Version: 1.18.0
- OS Version: Fedora 
 OS: Fedora release 26 (Twenty Six) x86_64
Kernel: 4.13.11-200.fc26.x86_64

Steps to Reproduce:

1. Install vscode
2. open anyfile
3. hit tab

Reproduces without extensions: Yes

**Comment by nickclasener** [comment] 2017-11-14 06:32
RIght my bad it had to do with linux xkb
This did the trick
```
"keyboard.dispatch": "keyCode",
```

**Comment by alexandrudima** [comment] 2017-11-14 08:37
Marking as duplicate of #23991 or perhaps one of the items at https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Closed by alexandrudima** 2017-11-14 08:37 UTC
Labels: keybindings, new release
