### ISSUE TITLE
No snapping layouts for Windows 11

### ISSUE THREAD

**Issue by jiahliu** [microsoft/vscode#146988] opened 2022-04-07 09:23 UTC
Issue Type: <b>Bug</b>

Hover the mouse over the window's maximize button, no snapping layouts for Windows 11

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by yume-chan** [comment] 2022-04-07 09:51
Duplicate of #127449

**Closed** 2022-04-07 09:58 UTC
Labels: *duplicate
