### ISSUE TITLE
Command palette does not show extension commands

### ISSUE THREAD

**Issue by djohnst10** [Microsoft/vscode#32673] opened 2017-08-16 23:20 UTC
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
aurelia|Aur|0.3.4
cake-vscode|cak|0.8.1
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|0.17.0
beautify|Hoo|1.1.1
classic-asp|ili|0.0.2
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|2.33.0
Ionide-Paket|Ion|1.7.3
Angular2|joh|2.4.0
VBScript|lug|0.0.2
Go|luk|0.6.63
mssql|ms-|1.1.0
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.1.8
vscode-docker|Pet|0.0.16
vscode-icons|rob|7.12.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1. I uninstalled the 32 bit version of Code and installed the 64 bit version.
2. While using Code to edit and run SQL Server scripts I noticed that the command palette no longer listed commands prefixed by MS SQL. These are commands added to the command palette specific to the mssql extension.
![image](https://user-images.githubusercontent.com/2738319/29389247-03f8f202-82b7-11e7-9553-1af1b255bb03.png)
3. I checked PowerShell scripts and there are no longer PowerShell specific commands in the command palette.
4. The commands are still available and bound to key bindings. I can type Ctrl+Shift+C when in SQL script and it will still show the SQL Server Connect UI.
![image](https://user-images.githubusercontent.com/2738319/29389324-61709020-82b7-11e7-8576-275c23bd0f30.png)
5. I uninstalled the 64 bit version and re-installed the 32 bit version but this has not fixed the issue.

Reproduces without extensions: N/A

**Comment by MangelMaxime** [comment] 2017-08-17 08:28
Same problem here.

- VSCode Version: Code 1.15.1 (41abd21, 2017-08-16T18:05:38.342Z)
- Architecture: x64 (I have the same problem with the 32bits)
- OS Version: Windows Pro x64 (Problem also occur under my Ubuntu laptop)
- Node: 7.4.0
- Extensions:

| Extension  | Authors  | Versions
|---|---|---|
| rainbow-brackets | 2gua | 0.0.6 |
| toml | be5invis | 0.0.3 |
| gitlens | eamodio | 0.19.1 |
| EditorConfig | EditorConfig | 0.9.4 |
| Ionide-FAKE | Ionide | 1.2.3 |
| Ionide-fsharp | Ionide | 2.33.0 |
| Ionide-Paket | Ionide | 1.7.3 |
| vshaxe | nadako | 1.9.1 |
| vscode-versionlens | pflannery | 0.19.1 |
| material-icon-theme | PKief | 2.1.0 |
| sass-indented | robinbentley | 1.4.1 |
| guides | spywhere | 0.8.4 |
| codedox | wiggin77 | 1.2.5 |
| Material-theme (One Dark Pro) | zhuangtongfa | 2.10.8 |

Also, I notice that some defaults commands of VSCode are not shown too.
For example, I can't do : Ctrl+P > Preview markdown

**Comment by ser1us** [comment] 2017-08-17 08:34
Same problem , for me the issue seems to be the `ionide-fsharp` package. As soon as I disable it it works fine.

**Comment by MangelMaxime** [comment] 2017-08-17 08:34
I removed my extension one by one and seems like the problem occur when I have **ionide-fsharp** installed.

**Comment by Krzysztof-Cieslak** [comment] 2017-08-17 09:26
Achievement unlocked: "Brake whole VSCode with Your extension"

**Comment by aeschli** [comment] 2017-08-17 10:20
Marking as dup of https://github.com/ionide/ionide-vscode-fsharp/issues/499

@Krzysztof-Cieslak Please let us know what caused the issue so we can look into this.

**Comment by MangelMaxime** [comment] 2017-08-17 10:24
@aeschli It's seems to be an error in a command name.

It's generate a warning in the dev console but also cause others extension to break.

> *Translated from french*
> `[C:\Users\mange\.vscode\extensions\Ionide.ionide-fsharp-2.33.0]: Element of menu make reference to command 'fsharp.explorer.refreesh' which is not defined in section 'commands'.
> `

PR Fixing the issue: https://github.com/ionide/ionide-vscode-fsharp/pull/500

**Comment by jrieken** [comment] 2017-08-17 10:42
Is there anything on the dev tools console? Do other extension commands work? Check with the TypeScript commands, hit F1, type `TypeScript` and you should see three commands. 

@daviwil Is there anything special to how powershell registers commands? Do you guys depend on the architecture of our processes?

**Comment by MangelMaxime** [comment] 2017-08-17 10:50
@jrieken The message I translated is from the dev tools console.

![image](https://user-images.githubusercontent.com/4760796/29409001-a52581b6-834a-11e7-921e-c9baf7e0095a.png)

**Comment by jrieken** [comment] 2017-08-17 11:01
That's Ionide which I believe is tracked in https://github.com/ionide/ionide-vscode-fsharp/pull/500 but @djohnst10 and @MangelMaxime mention MS Sql and Powershell. I just tested 32bit to 64bit and at least Powershell commands are still there...

**Comment by Krzysztof-Cieslak** [comment] 2017-08-17 11:11
I believe my Ionide bug stops other commands from being registered

**Comment by MangelMaxime** [comment] 2017-08-17 11:13
Yes the problem, is if you have Ioinide version 2.33.0 installed with VSCode 1.15.1 (didn't test any other versions). Then you got this warning.

And when you got this warning every commands coming from others extensions disappear. I made a little gif to show you the problem.

![ionide_bug](https://user-images.githubusercontent.com/4760796/29409673-a30dcc64-834d-11e7-9c71-fffa82469e5f.gif)

So yes the PR should fix the current bug caused by Ionide.

But I believe there is a bug into VSCode too because this warning should not break other extensions command registrations. Indeed any extension having a typo between it's declaration under the `commands` node and it's usage later in `menus.commandPalette" would break others extension commands.

**Comment by jrieken** [comment] 2017-08-17 12:34
Thanks, I now understand. The problem occurs when filtering in the command palette. Thing go south when hitting a command that isn't there

```
TypeError: Cannot read property 'id' of undefined
    at class_1.exports.MenuRegistry.class_1._appendImplicitItems (actions.js:103)
    at class_1.exports.MenuRegistry.class_1.getMenuItems (actions.js:95)
    at menu.js:27
    at Promise_ctor.CompletePromise_then [as then] (winjs.base.raw.js:1566)
    at new Menu (menu.js:26)
    at MenuService.createMenu (menuService.js:24)
    at commandsHandler.js:355
    at InstantiationService.invokeFunction (instantiationService.js:48)
    at CodeEditor.CommonCodeEditor.invokeWithinContext (commonCodeEditor.js:101)
    at CommandsHandler.getResults (commandsHandler.js:355)
```

**Closed** 2017-08-17 12:38 UTC
Labels: bug, extensions, important
