### ISSUE TITLE
Make `Refactor` for Java accessible via right mouse click menu

### ISSUE THREAD

**Issue by accuware** [microsoft/vscode#77984] opened 2019-07-26 09:58 UTC
Right now there is a way to refactor Java code via `F2`. But there is also a right mouse click menu, which offers a Refactor action, which leads to "nothing to refactor" (or similar)

![image](https://user-images.githubusercontent.com/30668077/61943832-9caf3d80-af9c-11e9-86c0-d6940c5549ca.png)

Would be great, if this right mouse click action would trigger the `F2` action in Java

**Comment by rebornix** [comment] 2019-07-26 17:43
Assigned to @mjbvz to help decide whether it's a VS Code issue or just an extension issue.

**Comment by mjbvz** [comment] 2019-08-12 17:55
This is caused by the Java extension which contributes this. Please file an issue against them

**Closed by mjbvz** 2019-08-12 17:55 UTC

**Comment by mjbvz** [comment] 2019-08-12 17:57
Actually nevermind; we contribute the menu items. What you are looking for is `rename symbol` though. We split this out of the refactor menu as it is such as common operation
