### ISSUE TITLE
VSCode Insider build for ARM

### ISSUE THREAD

**Issue by rpourzia** [Microsoft/vscode#73255] opened 2019-05-03 21:24 UTC
I would like to install  VSCode insider and remote debugging extension pack on raspberry pi.  Is there a build available that would work on raspberry pi? Or do shall I rebuild on raspberry pi using the tar.gz file

**Comment by mjbvz** [comment] 2019-05-03 23:08
Duplicate of #6442

**Closed by mjbvz** 2019-05-03 23:08 UTC
