### ISSUE TITLE
Error produced from Find / Replace interface

### ISSUE THREAD

**Issue by mikeerickson** [Microsoft/vscode#70427] opened 2019-03-13 20:44 UTC
Issue Type: <b>Bug</b>

As of v1.33, I am receiving an error when selecting Edit | Replace in Files (as well as the keymap)

See the associated screenshot of error.

![image](https://user-images.githubusercontent.com/183153/54313213-10285380-4596-11e9-8183-db550354191e.png)

Note: I can still select Search item in the Find pane and it does work

VS Code version: Code - Insiders 1.33.0-insider (c1d001a915fe85cac93492393ea69fdb0c49ec0d, 2019-03-13T06:14:16.471Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 8, 7|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (130)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
open-in-macdown|Cod|1.0.0
output-colorizer|IBM|0.1.2
indenticator|Sir|0.6.0
better-comments|aar|2.0.3
vscode-file-peek|abi|1.0.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.2.2
numbered-bookmarks|ale|6.1.0
project-manager|ale|10.3.2
vscode-sqlite|ale|0.6.0
copy-relative-path|ale|0.0.2
jest-snippets|and|1.7.0
vscode-twig-pack|baj|1.0.0
color-info|bie|0.5.0
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.1.16
vscode-toggle-quotes|Bri|0.3.2
cacher-vscode|Cac|1.0.5
better-phpunit|cal|1.4.0
vscode-yarn-script|car|0.0.1
snippets-for-react-redux-typescript|Cel|0.0.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-select|chu|2.0.1
open-html-in-browser|cod|0.1.21
bracket-pair-colorizer|Coe|1.0.61
dakara-foldplus|dak|1.3.2
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.25.0
vscode-eslint|dba|1.8.2
vscode-dash|dee|2.1.0
vscode-new-file|dku|4.0.2
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.1.1
Vue2|duc|0.1.3
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
RunOnSave|eme|0.0.18
LogFileHighlighter|emi|2.4.3
vscode-great-icons|emm|2.1.47
react-native-react-redux-snippets-for-es6-es7-version-standard|EQu|1.0.3
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
vscode-todo-plus|fab|4.11.4
php-debug|fel|1.13.0
open-in-marked|fmo|1.0.8
auto-close-tag|for|0.5.6
code-runner|for|0.9.7
docker-explorer|for|0.1.6
vscode-mysql|for|0.3.0
macros|ged|1.2.1
lintlens|ghm|2.3.0
sass-lint|gle|1.0.4
vscode-mocha-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.6.0
vue-snippets|hol|0.1.11
icon-fonts|idl|2.1.5
useful-react-snippets|igo|1.5.4
vscode-react-typescript|inf|1.1.0
path-autocomplete|ion|1.13.1
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-peacock|joh|1.2.1
php-cs-fixer|jun|0.1.96
vscode-colorize|kam|0.8.8
auto-comment-blocks|kev|1.0.1
git-indicators|lam|2.1.1
vscode-js-annotations|lan|0.11.0
expand-region|let|0.1.2
vscode-opn|lfu|1.1.2
vs-color-picker|lih|1.0.0
vue|liu|0.1.5
string-manipulation|mar|0.3.1
rainbow-csv|mec|1.0.0
vscode-wrap-console-log|mid|1.7.2
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.1
graphql|mqu|0.1.2
vscode-attrs-sorter|mrm|2.1.0
debugger-for-chrome|msj|4.11.3
vscode-open-iterm2|mus|0.0.4
vscode-mocha-two|Mys|3.0.0
color-highlight|nau|2.3.0
php-docblocker|nei|1.7.0
snippet-creator|nik|0.0.5
vetur|oct|0.16.2
indent-rainbow|ode|7.3.0
react-proptypes-intellisense|OfH|1.0.3
advanced-new-file|pat|1.2.0
vscode-docker|Pet|0.6.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|3.6.3
vscode-css-peek|pra|2.2.0
view-in-browser|qin|0.0.5
subtle-brackets|raf|3.0.0
show-offset|ram|0.0.4
vscode-yaml|red|0.3.0
vscode-icons|rob|8.2.0
nunjucks|ron|0.2.3
shebang-snippets|rpi|0.1.3
multi-command|ryu|1.3.0
vscode-workspace-switcher|sad|1.9.0
vscode-open|san|0.1.0
vue-vscode-extensionpack|sdr|0.2.0
preview-vscode|sea|2.0.3
code-settings-sync|Sha|3.2.7
stylelint|shi|0.48.0
html5-boilerplate|sid|1.0.3
vscode-fileutils|sle|2.13.5
es6-mocha-snippets|spo|0.2.2
guides|spy|0.9.3
addDocComments|ste|0.0.8
vscode-status-bar-format-toggle|tom|1.5.0
sort-lines|Tyr|1.8.0
highlight-matching-tag|vin|0.8.6
vscodeintellicode|Vis|1.1.4
nodejs-extension-pack|wad|0.1.9
vscode-wakatime|Wak|1.2.13
quokka-vscode|Wal|1.0.193
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.1.1
html-css-class-completion|Zig|1.18.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment] 2019-03-13 20:53
Duplicate of #70385

**Closed by mjbvz** 2019-03-13 20:53 UTC
Labels: editor-find
