### ISSUE TITLE
Bracket pair colorization

### ISSUE THREAD

**Issue by AlonsoGalicia** [microsoft/vscode#132491] opened 2021-09-06 19:13 UTC
Issue Type: <b>Bug</b>

If I use the following lines of code:
<v-text-field
        v-model="phoneInput"
        :append-icon="index > 0 ? 'mdi-trash-can' : 'mdi-cellphone'"
        label="Phone"
        @click:append="deleteInd"
      />
The "bracket" is closed inside the "append" comparison, instead of the line where contains "/>"

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (0.68GB free)|
|Process Argv|--crash-reporter-id 11f9c232-04ae-4bcc-a4db-4e14ee750adc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.6.0
vscode-eslint|dba|2.1.23
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-es|MS-|1.60.2
mssql|ms-|1.10.1
vetur|oct|0.34.1
vscode-css-peek|pra|4.2.0
vs-code-prettier-eslint|rve|3.0.4
vue-vscode-snippets|sdr|2.2.1
bootstrap4-vscode|the|6.1.0
vuetify-vscode|vue|0.2.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by IllusionMH** [comment] 2021-09-06 19:41
Please use code blocks for code as currently firmatting and code us list in your report. Also please include screenshots if result.
````
```
Code
```
````


Also note that there are couple of requests to remove `<>` from coloring if it helps.

**Comment by IllusionMH** [comment] 2021-09-06 20:36
With #132476 marked for September release this might be "fixed" by removing colorization for `<>` by default.
Unless @hediet see other action items here.

/assign @hediet

**Comment by hediet** [comment] 2021-09-07 07:51
Closing as duplicate of https://github.com/microsoft/vscode/issues/132476.

**Closed by hediet** 2021-09-07 07:51 UTC
