### ISSUE TITLE
When opening a file from problem view, the file is opened again in a new tab.

### ISSUE THREAD

**Issue by martincohen** [Microsoft/vscode#18684] opened 2017-01-17 18:15 UTC
I'm using MSVC 2015 and `cpptools`. When I click on errors in problem view, I get the file opened as a duplicate with path "." (for example lib.h opens again as `lib.h .`) This later causes errors with saving files (as Code detects that the file is "newer" on the disk) and I've already lost several hours of work due to this bug.

- VSCode Version:
1.8.1 (with freshly installed cpptools)
- OS Version:
Windows 10

Steps to Reproduce:

This happens quite random

1. Open files from the Explorer sidebar.
2. Create a file with compile errors.
3. Compile.
4. Hit `F8` (and if it actually works, as it's buggy) and the file is opened in another tab.

**Comment by martincohen** [comment] 2017-01-17 23:19
This also happens from `cpptools` callstack. The files simply have different case in the paths (which is natural for Windows). 

- `W:\Work\Projects\lever\development\runtime.c` (opened from *Explorer*)
- `W:\work\projects\lever\development\runtime.c` (opened from *Call Stack* in *Debug* mode)

**Comment by dbaeumer** [comment] 2017-01-18 08:07
@bpasero I start this with you. When we compare file inputs are we comparing them case insensitive under Windows? If we do then this sounds like a cpptools problem then.

**Comment by bpasero** [comment] 2017-01-18 09:21
This should be reported to the C++ extension, otherwise, duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2017-01-18 09:21 UTC
Labels: workbench

**Comment by martincohen** [comment] 2017-01-18 10:38
I've already reported this issue to `cpptools` and been sent by the guys there to report it here. However, yah, it sounds like duplicate of #12448 and also my recent one #18718 (requested by @isidorn to be filed separately as it might contain more info).

**Comment by isidorn** [comment] 2017-01-18 11:07
@martincohen might be a dup of #12448, @bpasero would know best. Sorry for making you file a new issue that turns out to be a dup!

**Comment by martincohen** [comment] 2017-01-18 11:09
@isidorn no problem at all, hopefully it adds more visibility to the issue and helps you guys. I would love to take a look at the issue myself, but I'm still trying to find my way around the source code.
