### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23619] opened 2017-03-29 20:37 UTC
![image](https://cloud.githubusercontent.com/assets/22350/24475410/06638d40-14d0-11e7-8cb8-f06574479a7d.png)

```
Request json/colorSymbols failed with message: Cannot read property 'schema' of null
```

I simply opened this file:

```json
{
	"rules": {
		"no-unused-expression": true,
		"no-unreachable": true,
		"no-duplicate-variable": true,
		"no-duplicate-key": true,
		"no-unused-variable": true,
		"curly": true,
		"class-name": true,
		"semicolon": [
			true,
			"always"
		],
		"triple-equals": true
	}
}
```

**Comment by aeschli** [comment] 2017-03-30 06:37
duplicate of #23424

**Closed by aeschli** 2017-03-30 06:37 UTC
Labels: bug, json
