### ISSUE TITLE
Multi Cursor Backspace only effects first line

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/vscode#76484] opened 2019-07-02 21:28 UTC
Issue Type: <b>Bug</b>

Get multiple cursors in any way (Either Alt-Ctrl or Ctrl-Click)

Arrow keys and typing works but deleting text only affects the first line.

Video of error:
I create multiple cursors, demonstrate moving it around with keys, demonstrate typing, then press backspace and it only affects first / top line.

http://recordit.co/f802edHci4

I also tried and reproduced this after the "Disable all Installed Extensions" 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (18.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-markdownlint|Dav|0.28.0
docs-article-templates|doc|0.2.5
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.9
docs-preview|doc|0.3.23
docs-yaml|doc|0.2.3
gitlens|eam|9.8.2
dotenv|mik|1.0.1
python|ms-|2019.6.22090
csharp|ms-|1.20.0
debugger-for-chrome|msj|4.11.6
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17

</details>

**Comment by mattmazzola** [comment] 2019-07-02 22:32
Wanted to mention the work-around I'm using is you have to first select the text and press Delete key instead of pressing Backspace key.

E.g. `Shift + Left Arrow  Delete`

The used to work and I looked for other similar issues but couldn't find any. Is there some setting I have enabled this behavior if no one else is seeing it?

**Comment by mattmazzola** [comment] 2019-07-03 16:10
Another very strange thing is that the multi-cursor backspace works for me on a different editor. 
And neither of these repos/folder have any `.vscode/settings.json` files to control workspace settings so I can't understand why they behave differently unless it has to do with the specific type of text i'm selecting.

**Comment by mattmazzola** [comment] 2019-07-03 16:17
I've now confirmed even within the same/single editor. This backspace issue occurs on Markdown `.md` files but multi-cursor seems to work correctly on other file types. I'm not sure how file extension has an effect since I would think editing text is independent of the purpose of the text. They're both utf-8 text files.

**Comment by rebornix** [comment] 2019-07-18 00:12
@mattmazzola do you still run into this issue with latest Stable 1.36? Unfortunately I can' reproduce this issue on both macOS and Windows

**Comment by mattmazzola** [comment] 2019-07-18 15:54
Yes, the issue still occurs on:

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

[OK] [Copy]
```

![http://g.recordit.co/xuycUeJvkO.gif](http://g.recordit.co/xuycUeJvkO.gif)

**Comment by rebornix** [comment] 2019-07-29 18:00
/duplicate of https://github.com/microsoft/vscode/issues/74625

**Closed** 2019-07-29 18:01 UTC
Labels: *duplicate, editor-contrib, needs more info
