### ISSUE TITLE
Feature Request: Custom screen reader description for built-in product icons

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode#158541] opened 2022-08-19 00:19 UTC
Is it feasible to add a custom description field that we could populate specifically for the screen reader so that it could override reading of the default IDs listed [here](https://code.visualstudio.com/api/references/icons-in-labels#icon-listing).  

Background:  We received an issue in one of our extensions stating that the screen reading of the built-in icons don't match closely enough with the actions that need performing.  It's unfortunate because from a visual perspective, these are a nice addition to the UI to set apart certain commands, but because of how the screen reader is reading the icons, we become very restricted in which icons we can realistically incorporate.  Not 100% sure how to address this one, any input is appreciated.  Thank you! :)

**Comment by isidorn** [comment] 2022-08-19 11:43
@MicroFish91 ok I understand the issue. I can not reproduce this with VoiceOver. So the first thing to figure out is why does NVDA or Jaws decide to read the codicon, and from what exact HTML attribute does it deduce what to read.

@leonardder when you find time can you follow these steps:
1. Open VS Code, install this extension https://marketplace.visualstudio.com/items?itemName=MicroFish.accessibility-testkit
2. F1 > "Select UI feature from menu for accessibility" command
3. Show quick picks
4. Down arrow -> NVDA reads "git-merge Quick Pick One"

The "git-merge" part of reading is because of the icon that is in front of the label. But I am not sure how does NVDA actually compute the "git-merge" name. The actual codicon class name is `codicon-git-merge`.

@misolori might have ideas.
@MicroFish91 even if we do figure out why the screen reader reads this, making the product name customisable is something I am not sure if we will open for extensions. @misolori might know more.

**Comment by MicroFish91** [comment] 2022-08-19 16:38
> @MicroFish91 even if we do figure out why the screen reader reads this, making the product name customisable is something I am not sure if we will open for extensions.

That's fair, would the possible alternative be to explore ways to prevent the screen reader from reading the icon description then?

**Comment by isidorn** [comment] 2022-08-19 17:56
@MicroFish91 yes, for that we need some smarts from the screen reader authors. Thus I pinged @leonardder :)

**Comment by leonardder** [comment] 2022-08-20 16:50
It looks like the icon description (e.g. "git-merge" is part of the accessible name, therefore part of the label of the item. I'm not sure how to explore the HTML generated by VS Code, as that's a long time ago.

**Comment by isidorn** [comment] 2022-08-22 08:52
@misolori is there some property on the codicon that would explain how the git-merge label is generated? I guess we can mot make this property name controlled by extensions?

**Comment by misolori** [comment] 2022-08-29 16:54
This is coming from the aria label on the quick pick item (likely created by the quick pick component)

![CleanShot 2022-08-29 at 09 52 00@2x](https://user-images.githubusercontent.com/35271042/187253179-fbdfc320-52fc-47c6-846e-e26dfb052960.png)

I would assume that it's reading the title from the source where do `$(git-merge) Quick Pick One` and it translates to `git-merge Quick Pick One`. We could add a "description" property to the codicon library and then have the quick pick pick that one up instead? cc @TylerLeonhardt @aeschli

**Comment by aeschli** [comment] 2022-08-30 08:08
I think we should skip icon names when generating the aria label. Even better would be if the QuickPickItem API allows to set an aria label. 

I don't think adding the icon descriptions will make things better. In fact, our product icons have descriptions ([example](https://github.com/microsoft/vscode/blob/e9d0bed9e577617a5a13b631c33d54807bcb1af1/src/vs/workbench/contrib/remote/browser/remoteIcons.ts#L14)), and the extension should probably define such a product icon ([docs](https://code.visualstudio.com/api/extension-guides/product-icon-theme#adding-a-new-product-icon-theme)) instead of directly reference a codicon, but still the description would not be useful in the aria label as it is was defined for other contexts such as the product icon documentation.

**Comment by isidorn** [comment] 2022-08-31 10:15
@aeschli I agree. So the right way to fix this is https://github.com/microsoft/vscode/issues/133169
@TylerLeonhardt maybe we reopen that one since that seems to help with multiple cases and feels like the right thing to do? What do you think?

**Comment by misolori** [comment] 2022-08-31 16:46
The only time icons are useful is if they denote a certain meaning (like in the branch picker where some are private) but I think you could convey that if the item sets the quick pick item

<img width="195" alt="CleanShot 2022-08-31 at 09 45 24@2x" src="https://user-images.githubusercontent.com/35271042/187733833-e3fc460e-e2cc-4af4-a211-088abaabbbb0.png">

**Comment by TylerLeonhardt** [comment] 2022-08-31 16:55
@isidorn yeah I'm not sure why that was ever closed as I think it's a great feature request to align with our other APIs

**Comment by isidorn** [comment] 2022-08-31 17:30
Then let's close this one as out of scope. And let's tackle the other one when time permits.

**Closed by isidorn** 2022-08-31 17:30 UTC
Labels: accessibility, under-discussion
