### ISSUE TITLE
Global Find&Replace BOM Encoding issue

### ISSUE THREAD

**Issue by SavchukSergey** [microsoft/vscode#65694] opened 2018-12-26 14:45 UTC
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. Create *fileBOM.txt* and *file.txt*
2. Update *fileBOM.txt* encoding to **UTF-8 with BOM** and *file.txt* encoding to **UTF-8**
3. Set both file content to:
```test```
```test```
4. Close both files. (Seems to be important step)
5. Find&Replace globally string ```test``` to ```Atest```. 
6. As result FIRST STRING of *fileBOM.txt* is replaced to ```tAtest```. Original letter ```t``` is repeated in front of expected result string

See screenshots below:

![file](https://user-images.githubusercontent.com/5380903/50449051-67bb0980-092d-11e9-96bd-a1c8c955013f.png)

![filebom](https://user-images.githubusercontent.com/5380903/50449055-6db0ea80-092d-11e9-8697-0c559b0e0b81.png)

![replaceall](https://user-images.githubusercontent.com/5380903/50449058-74d7f880-092d-11e9-9168-4be7fdc385f0.png)

![filereplaced](https://user-images.githubusercontent.com/5380903/50449061-7a354300-092d-11e9-95c0-ed1fe5f5ab30.png)

![filebomreplaced](https://user-images.githubusercontent.com/5380903/50449065-7f928d80-092d-11e9-9c3b-aaffad8f7d78.png)

**Comment by roblourens** [comment] 2018-12-31 06:43
@sandy081 do you know whether we are supposed to be compensating for the BOM offset somewhere?

**Comment by sandy081** [comment] 2019-01-03 14:43
@roblourens If I remember correctly, old search used to consider this but not sure. @bpasero might give us better insight here.

**Comment by sandy081** [comment] 2019-01-10 14:37
Replace edits are computed from the matches that search provides. I do not have idea if BOM offset is considered while applying edits. I use the bulk edit api from @jrieken, may be he knows ?

**Comment by roblourens** [comment] 2019-10-09 17:51
It seems like the bulk edit api should account for this. "column 0" means the first character. The search results can't compensate for it.

**Comment by jrieken** [comment] 2019-10-09 18:09
Bulk edit has no chance of doing this, what I receive is a text model (which is normalised?) on which the operations are carried out. No clue when the carnage happens.

**Comment by bpasero** [comment] 2019-10-10 13:03
I cannot reproduce.

Before:

![image](https://user-images.githubusercontent.com/900690/66571000-020fd500-eb6f-11e9-8d82-694ada5efb7f.png)

After:
![image](https://user-images.githubusercontent.com/900690/66571031-0dfb9700-eb6f-11e9-9c52-85e5f248150b.png)

If someone has ideas please update, otherwise I am going to close this as not reproducible.

**Comment by bpasero** [comment] 2019-10-10 13:03
Oh wow, this is old, closing.

**Closed by bpasero** 2019-10-10 13:03 UTC
Labels: *not-reproducible, needs more info
