### ISSUE TITLE
Triggererd breakpoints are not resetting on restart

### ISSUE THREAD

**Issue by FMorschel** [microsoft/vscode#228963] opened 2024-09-18 15:51 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Pro

Originally from https://github.com/Dart-Code/Dart-Code/issues/5277.

**To Reproduce**
1. Create an empty dart project (can be any language, this is just the one I use of course)
2. Add the code below
3. Add breakpoints on both `foo` and `bar` print calls
4. Make the breakpoint on the `foo` trigger only after the one at `bar` (screenshot)
5. Run the code and make sure the `foo` breakpoint stops
6. Restart the program
7. See that `foo` triggers before `bar`

```dart
void main() {
  foo();
  bar();
  foo();
}

void foo() {
  print('foo');
}

void bar() {
  print('bar');
}
```

**Expected behavior**
For the triggered breakpoint to wait again on restart.

Also note that there are two ways to restart a debug session too - a full restart handled by VS Code (which is what happens for Dart above), and a restart that is delegated to the debug adapter (which we use for Flutter to do Hot Restart, so it's faster than a cold restart by VS Code). In both cases, this state should be reset.

**Screenshots**
![2024-09-18_07h39_19](https://github.com/user-attachments/assets/e51f6def-3343-41f7-a157-5a96ce24c11b)

<details>

<summary> Relevant debugging log part </summary>

```console
// First session, only the first breakpoint is sent
[3:17:41 PM] [DAP] [Info] ==> {"command":"setBreakpoints","arguments":{"source":{"name":"dartcode_5277.dart","path":"c:\\Dev\\Test Projects\\dartcode_5277\\bin\\dartcode_5277.dart"},"lines":[12],"breakpoints":[{"line":12}],"sourceModified":false},"type":"request","seq":3}
[3:17:41 PM] [DAP] [Info] <== {"seq":3,"type":"response","body":{"breakpoints":[{"id":100000,"verified":false}]},"command":"setBreakpoints","request_seq":3,"success":true}

// When the breakpoint is hit, the breajpoints are updated to include both
[3:17:41 PM] [DAP] [Info] ==> {"command":"setBreakpoints","arguments":{"source":{"adapterData":{"type":"@Script","id":"libraries/@18078730/scripts/file%3A%2F%2F%2FC%3A%2FDev%2FTest%2520Projects%2Fdartcode_5277%2Fbin%2Fdartcode_5277.dart/192057efd2f","fixedId":true,"uri":"file:///C:/Dev/Test%20Projects/dartcode_5277/bin/dartcode_5277.dart"},"name":"bin\\dartcode_5277.dart","path":"c:\\Dev\\Test Projects\\dartcode_5277\\bin\\dartcode_5277.dart"},"lines":[8,12],"breakpoints":[{"line":8},{"line":12}],"sourceModified":false},"type":"request","seq":11}
[3:17:41 PM] [DAP] [Info] <== {"seq":73,"type":"response","body":{"breakpoints":[{"id":100001,"verified":false},{"id":100002,"verified":false}]},"command":"setBreakpoints","request_seq":11,"success":true}

// Debug session is restarted
[3:17:48 PM] [DAP] [Info] ==> {"command":"terminate","arguments":{"restart":true},"type":"request","seq":22}
[3:17:48 PM] [DAP] [Info] Stopping debug session cdbee24a-544f-4a9c-a042-c9fea94439f3
[3:17:48 PM] [DAP] [Info] Starting debug session cdbee24a-544f-4a9c-a042-c9fea94439f3

// Both breakpoints are sent immediately
[3:17:48 PM] [DAP] [Info] ==> {"command":"setBreakpoints","arguments":{"source":{"adapterData":{"type":"@Script","id":"libraries/@18078730/scripts/file%3A%2F%2F%2FC%3A%2FDev%2FTest%2520Projects%2Fdartcode_5277%2Fbin%2Fdartcode_5277.dart/192057efd2f","fixedId":true,"uri":"file:///C:/Dev/Test%20Projects/dartcode_5277/bin/dartcode_5277.dart"},"name":"bin\\dartcode_5277.dart","path":"c:\\Dev\\Test Projects\\dartcode_5277\\bin\\dartcode_5277.dart"},"lines":[8,12],"breakpoints":[{"line":8},{"line":12}],"sourceModified":false},"type":"request","seq":3}
[3:17:48 PM] [DAP] [Info] <== {"seq":3,"type":"response","body":{"breakpoints":[{"id":100000,"verified":false},{"id":100001,"verified":false}]},"command":"setBreakpoints","request_seq":3,"success":true}
```

</details>

---

// CC: @DanTup

**Comment by DanTup** [comment] 2024-09-18 16:29
Interestingly, I cannot reproduce this with JavaScript using an equivalent file:

```js
function main() {
	foo();
	bar();
	foo();
}
main();

function foo() {
	console.log('foo');
}

function bar() {
	console.log('bar');
}
```

Unfortunately I don't think it uses DAP and I don't know if there's a way to get a log of what's happening there. It's not clear to me how it could be working there given the DAP traffic captured for Dart. Someone familiar with the implementation of Triggered Breakpoints or the JS debugger might be able to explain what's going on.

**Comment by FMorschel** [comment] 2024-09-18 16:43
I can on python:

```py
def foo():
    print("Foo")

def bar():
    print("Bar")

foo()
bar()
foo()
```

**Comment by firelizzard18** [comment] 2024-10-04 21:08
I am also running into this isue

**Comment by connor4312** [comment] 2024-10-04 21:25
> Interestingly, I cannot reproduce this with JavaScript using an equivalent file:

This is probably because the JS debugger has each debugee as its own, child session, and when restarting JS you will retain the parent session (handled by the DA) but get a new child session that doesn't have the data set.

**Comment by firelizzard18** [comment] 2024-10-04 21:44
I am debugging Go. I don't remember seeing it with other languages but I also only rarely run anything other than Go.

**Comment by connor4312** [comment] 2024-10-04 21:52
yea, it's reproducable with Python too. Fixed in Monday's Insiders.

**Closed** 2024-10-04 22:13 UTC
Labels: bug, debug
