### ISSUE TITLE
Default settings not filled for linux distro

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#12557] opened 2016-09-24 07:58 UTC
Some (not sure which/how many) default settings are not filled when requesting workspace configuration:
https://travis-ci.org/HookyQR/VSCodeBeautify/jobs/162387489

The line is trying to work with   "html.format.extraLiners", which is defaults to "head, body, /html" on OS X, but returns `null` on Linux.

This puts unnecessary weight on extension developers.

**Comment by chrmarti** [comment] 2016-09-26 19:58
Any chance your test needs to wait for all extension metadata to load?

**Comment by bpasero** [comment] 2016-09-27 08:35
@HookyQR I can reproduce when running the tests from the command line but not when running from VS Code. Would you be able to provide an isolated test that show the issue? I also notice that you seem to use timeouts and slow in the test, so this looks like a race condition.

**Comment by bpasero** [comment] 2016-09-27 08:53
Btw I see the tests failing with 1.4.x already but also with our insider release, so it is not a regression.

**Comment by HookyQR** [comment] 2016-09-27 18:50
The problem is definitely default settings not being used as the error goes away with the second line changed::
```javascript
const html = vscode.workspace.getConfiguration('html.format');
options.extra_liners = html.extraLiners.split(',').map(s=>s.trim());
// change to:
options.extra_liners = (html.extraLiners || "head, body, /html").split(',').map(s=>s.trim());
```

ie. setting the defaults manually.

But I don't have to do this for OSX, and I shouldn't have to do it for any OS.

**Comment by bpasero** [comment] 2016-09-28 06:02
@HookyQR when I add a `console.log(JSON.stringify(html))` to that area of code I see the following returned:

```json
{
	"wrapLineLength": 120,
	"unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt, var",
	"indentInnerHtml": false,
	"preserveNewLines": true,
	"maxPreserveNewLines": null,
	"indentHandlebars": false,
	"endWithNewline": false,
	"extraLiners": "head, body, /html"
}
```

For me this seems like THE default settings being returned. Would you agree?

**Comment by bpasero** [comment] 2016-10-04 13:24
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Closed by bpasero** 2016-10-04 13:24 UTC
Labels: needs more info
