### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

### ISSUE THREAD

**Issue by diegobvision** [microsoft/vscode#182633] opened 2023-05-16 14:04 UTC
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230509

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
    at getDocumentRegistryEntry (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133014:11)
    at Object.releaseDocumentWithKey (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133111:19)
    at getOrCreateSourceFileByPath (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141789:30)
    at Object.getOrCreateSourceFile (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141773:14)
    at /private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141705:42
    at Object.getSourceFileWithCache [as getSourceFile] (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117879:24)
    at findSourceFileWorker (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120247:23)
    at findSourceFile (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120167:20)
    at /private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120116:22
    at getSourceFileFromReferenceWorker (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120100:69)
    at processSourceFile (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120114:5)
    at processRootFile (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119911:5)
    at /private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:41
    at forEach (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2324:22)
    at createProgram (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118690:5)
    at synchronizeHostData (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141729:15)
    at Object.getProgram (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141801:5)
    at InferredProject2.updateGraphWorker (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174359:41)
    at InferredProject2.updateGraph (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174211:32)
    at _ProjectService.assignOrphanScriptInfoToInferredProject (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176601:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178219:12)
    at /private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:64
    at flatMap (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2572:17)
    at _ProjectService.applyChangesInOpenFiles (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178449:24)
    at updateOpen (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179629:29)
    at /private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182193:14)
    at IpcIOSession.executeCommand (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182201:29)
    at IpcIOSession.onMessage (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182243:51)
    at process.<anonymous> (/private/var/folders/h8/j4lvrq6n7x73dt9j1h8msl2m0000gn/T/AppTranslocation/898E6C43-C7C2-41E2-B86A-68F9741F38B0/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:958:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code - Insiders 1.79.0-insider (Universal) (02298ef4180f2a5db39e0cb6288382860b96a596, 2023-05-11T05:26:00.234Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 2d878d87-834d-4b5f-abfd-b342780f8a7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
atlascode|atl|3.0.3
tailwind-docs|aus|2.0.0
vscode-styled-jsx|bla|2.1.1
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
postcss|css|1.0.9
hex-to-rgba|dak|1.0.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.12.0
copilot-chat|Git|0.1.2023051601
copilot-nightly|Git|1.86.92
vscode-pull-request-github|Git|0.64.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
nbpreviewer|jit|1.2.2
vscode-colorize|kam|0.11.1
vscode-language-babel|mgm|0.0.39
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.20
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.1
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-powertoys|ms-|0.0.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.293.0
live-server|ms-|0.4.8
material-icon-theme|PKi|4.27.0
vscode-yaml|red|1.12.2
LiveServer|rit|5.7.9
smart-css-autocomplete|sai|1.5.3
js-jsx-snippets|sky|11.0.1
open-in-browser|tec|2.0.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.15.13
html-css-class-completion|Zig|1.20.0
p5-resources|zsa|2.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
cai9j608:30680470
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by mjbvz** [comment] 2023-05-16 18:17
Duplicate of #182526

**Closed by mjbvz** 2023-05-16 18:17 UTC
