### ISSUE TITLE
[Insiders] .tsx files Syntax Highlighter broken

### ISSUE THREAD

**Issue by visualcookie** [microsoft/vscode#89075] opened 2020-01-22 10:19 UTC
Issue Type: <b>Bug</b>

1. Open VSCode Insiders
2. Open any .tsx file
3. Switch the color theme
4. See the syntax highlighting work but shortly after it gets white again

Video of this issue: https://streamable.com/pefag

Short description: This issue occurs, AFTER language features have been initialized.

VS Code version: Code - Insiders 1.42.0-insider (68615717819b3731705d92ec06b52edd47665291, 2020-01-22T05:26:38.760Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv|-psn_0_2753184|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.9.1
jest-snippets|and|1.7.0
i18n-ally|ant|1.11.4
vscode-intelephense-client|bme|1.3.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
vscode-eslint|dba|2.0.15
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.5.0
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.4
vscode-firefox-debug|fir|2.6.1
flow-for-vscode|flo|1.5.0
vscode-yarn|gam|1.7.0
helium-icon-theme|hel|1.0.0
docthis|joe|0.7.1
Angular2|joh|8.3.0
vscode-styled-components|jpo|0.0.28
chat|kar|0.31.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.9.0
sublime-keybindings|ms-|4.0.6
vsliveshare|ms-|1.0.1510
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
vscode-extension-auto-import|Nuc|1.4.3
vscode-jest|Ort|3.1.1
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.2
vscode-graphql|Pri|0.2.2
vscode-xml|red|0.10.1
vscode-javascript-booster|sbu|0.11.0
vscode-fileutils|sle|3.0.1
errorlens|use|2.9.0
vscode-fintory|vis|1.0.1
vscodeintellicode|Vis|1.2.4
vscode-import-cost|wix|2.12.0

(3 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-01-22 10:27
/duplicate of #88911

Solution: disable semantic highlights with `"editor.semanticHighlighting.enabled": false` in `settings.json`

**Closed** 2020-01-22 10:28 UTC
Labels: *duplicate, integrated-terminal
