### ISSUE TITLE
Process Picker: Cannot connect to runtime process

### ISSUE THREAD

**Issue by gushuro** [Microsoft/vscode#46770] opened 2018-03-27 21:50 UTC
Testing #46582

Steps to Reproduce:

1. `node --inspect-port=1234 test.js`
2. Debug: Attach to Node Process

Outcome: 
<img width="415" alt="cannotconnect" src="https://user-images.githubusercontent.com/5607882/37996820-d261c0b8-31cd-11e8-80fc-d8e89990acce.png">

Replacing step 1 for `node --inspect=1234 test.js` makes it work, so I'm not sure why its failing.

**Comment by weinand** [comment] 2018-03-27 21:52
duplicate of #46664.
Fixed in next Insiders.

**Closed by weinand** 2018-03-27 21:52 UTC
Labels: debug
