### ISSUE TITLE
"Go to Definition " and F12 does not work 

### ISSUE THREAD

**Issue by yanivgn** [Microsoft/vscode#66486] opened 2019-01-14 14:34 UTC
Issue Type: <b>Feature Request</b>

"Go to Definition " and F12 does not work to me from file to another file in project in Visual Studio Code.
I have a folder with lots of js files and one file uses a function that is defined in another file.
The goal is to understand the code and get to the functions easily.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment] 2019-01-14 16:25
Please share some example code or small example project that has this issue

**Comment by yanivgn** [comment] 2019-01-15 06:50
JS file - 
 
```
function myFunction(){
     console.log("Hello World");
}
```

HTML file - 

```
<script src="main.js><script>
<script>
myFunction();
<script>
```
I want to jump from HTML to function definition in the JS file.

**Comment by mjbvz** [comment] 2019-01-15 19:03
Duplicate of #26338

We don't support intellisense between script blocks and js files

**Closed by mjbvz** 2019-01-15 19:03 UTC
Labels: javascript, needs more info
