### ISSUE TITLE
Let User change the UI Font

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/vscode#123397] opened 2021-05-09 10:11 UTC
![image](https://user-images.githubusercontent.com/77537933/117568230-d521fc00-b0dc-11eb-9acd-906fae0aeb9d.png)

## I want to change the UI Font by default for windows I guess it is Segoe UI. but I want to change it I searched a lot but haven't find any answers. So please in your next UPDATE add this feature. 🚀🚀

**Comment by yume-chan** [comment] 2021-05-11 02:58
Duplicate of #519

**Closed** 2021-05-11 06:52 UTC
Labels: *duplicate
