### ISSUE TITLE
JSDoc panels no longer show up when hovering over symbols in TypeScript

### ISSUE THREAD

**Issue by BlueGhostGH** [microsoft/vscode#111776] opened 2020-12-03 00:23 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Create an empty TypeScript project (no tsconfig or such)
2. Create a TypeScript file
3. Create a simple function and document it using JSDoc
4. Hover over the function's name

Actual result:
Just the type definition of the function shows up

![actual](https://user-images.githubusercontent.com/17652623/100947527-7a252100-350e-11eb-95db-658833ecd390.png)

Expected result:
A panel with the JSDoc comment would show up, along with the type definition of the function

VS Code version: Code - Insiders 1.52.0-insider (f4187f22026ff6537f2ca8132ad3209fceb5071f, 2020-12-02T13:21:33.226Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.90GB free)|
|Process Argv|--crash-reporter-id f19d9a33-fd27-4bbc-8e98-25bb8f4db9e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
commit-message-editor|ada|0.14.4
codesnap|adp|1.2.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.3
prettier-vscode|esb|5.8.0
haskell|has|1.2.0
rest-client|hum|0.24.4
discord-vscode|icr|4.0.0
language-haskell|jus|3.3.0
graphql-for-vscode|kum|1.15.3
rust-analyzer|mat|0.2.400
rainbow-csv|mec|1.8.0
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-docker|ms-|1.8.1
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.152.0
angular-console|nrw|15.0.0
ide-purescript|nwo|0.23.3
language-purescript|nwo|0.2.4
material-icon-theme|PKi|4.4.0
prisma|Pri|2.12.1
vscode-yaml|red|0.13.0
synthwave-vscode|Rob|0.1.8
lit-plugin|run|1.2.1
rust|rus|0.7.8
preview-vscode|sea|2.2.5
fm|Sun|0.2.0
ayu|tea|0.20.1
move-ts-js|tnr|1.11.13
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vscode-wakatime|Wak|4.0.9
vscode-import-cost|wix|2.13.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by mjbvz** [comment] 2020-12-03 02:36
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? 

Some of your installed extensions, such as IntelliCode, modify VS Code's JavaScript and TypeScript IntelliSense

**Comment by BlueGhostGH** [comment] 2020-12-03 02:54
Just checked. Yes, it does also reproduce with all extensions disabled(I've made sure to restart my editor).

**Comment by gjsjohnmurray** [comment] 2020-12-03 05:22
Probably duplicate of #111741

Please retest when next Insiders arrives

**Comment by yume-chan** [comment] 2020-12-03 10:45
Happened to me several hours ago. Can confirm it works after an update.

![image](https://user-images.githubusercontent.com/1330321/100999233-75587f80-3597-11eb-847c-a1bf23c0c8fb.png)

<details>
<summary>Version Info</summary>

<pre>
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
</pre>
</details>

**Comment by Bewinxed** [comment] 2020-12-03 15:45
Fixed in latest update, hover works now!

> Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Closed** 2020-12-04 00:35 UTC
Labels: *duplicate
