### ISSUE TITLE
[bug] The column selection (Alt + select) is incorrect (offset by 3 characters)

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#78425] opened 2019-08-03 11:09 UTC
- VSCode Version: 1.37.0-insider
- OS Version: Win10 1903

Steps to Reproduce:

1. Try to select something with column selection (alt + left mouse click)
2. There is an error in the selected line - offset by 3 characters

Gif example below:
![66](https://user-images.githubusercontent.com/30685349/62411169-79fdd400-b5ef-11e9-95b0-62af3aa6e05d.gif)

Does this issue occur when all extensions are disabled?: Yes

Information that may come in handy:
1. I have set `"editor.multiCursorModifier":` to `"ctrlCmd"`
2. I have set `"editor.insertSpaces":` to `false` _(i prefer tabs)_
2. I don't use zoom
3. Keybindings are default

**Comment by IllusionMH** [comment] 2019-08-03 20:14
/confirmed

Looks like there is problem when you use Tabs for indentation and only for selection with a mouse.
Offset between selection cursor and mouse is basically `(Tab size - 1) * Indent level`.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.18950

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kanlukasz** [comment] 2019-08-04 14:55
So can we talk about it like about a bug?

**Comment by IllusionMH** [comment] 2019-08-04 19:56
Yes, looks like it is bug specific to indentation with Tabs. At least I highly doubt that it is expected behavior. 

In meantime you can use keyboard for precise multi-line selection. I also haven't noticed this problem when file is indented with spaces.

**Comment by alexandrudima** [comment] 2019-08-05 09:09
Duplicate of #78262

**Closed by alexandrudima** 2019-08-05 09:09 UTC
