### ISSUE TITLE
closing bracket is not working in 1.58

### ISSUE THREAD

**Issue by LazyCoder26** [microsoft/vscode#128361] opened 2021-07-10 03:04 UTC
after new relese note of 1.58.0 
auto closing bracket in pyhon is not working
whenever i type (
expected result is () but bracket 
doesn't close and showing like this (

plz help : )

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.42GB free)|
|Process Argv|--crash-reporter-id 8ce6b6b6-25b4-4e2d-9044-87dc3da3e09e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
beardedicons|Bea|0.11.0
file-browser|bod|0.2.10
vscode-pytest|Cam|0.1.1
npm-browser|den|1.1.0
vscode-great-icons|emm|2.1.79
vscode-firefox-debug|fir|2.9.4
copilot|Git|1.1.1959
vscode-test-explorer|hbe|2.20.4
helium-icon-theme|hel|1.0.0
vscode-python-test-adapter|lit|0.6.8
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
test-adapter-converter|ms-|0.0.12
ayu|tea|0.20.1
material-theme|zhu|3.10.14

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

**Comment by hediet** [comment] 2021-07-12 14:54
This is caused by the Copilot extension. We're currently working with them to fix this issue.

**Comment by LazyCoder26** [comment] 2021-07-15 03:49
> 
> 
> This is caused by the Copilot extension. We're currently working with them to fix this issue.
> 
> Note that you can override this setting by yourself:
> 
> ```json
> "[javascript]": {
>     "editor.autoClosingBrackets": "languageDefined"
> },
> "[typescriptreact]": {
>     "editor.autoClosingBrackets": "languageDefined"
> },
> ...
> ```
> 
> However, this could lead to a degraded Copilot experience.

thanks for help
: )

**Comment by hediet** [comment] 2021-07-15 07:05
Duplicate of #127739.

**Closed** 2021-07-15 07:06 UTC
Labels: *duplicate
