### ISSUE TITLE
Cannot read property 'node' of null

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#45912] opened 2018-03-15 20:24 UTC
Issue Type: <b>Bug</b>

Simple to reproduce:
* Open an empty file
* Ctrl-shift-f to open find-all panel
* Type "abc" and hit enter to search

VS Code version: Code - Insiders 1.22.0-insider (ec3c083444c084394ee0cd936074019c1bc0b321, 2018-03-14T06:14:24.748Z)
OS version: Linux x64 4.4.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2868)|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (1.25GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders src|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by jde1** [comment] 2018-03-15 22:10
As a workaround, use regex search.

**Comment by roblourens** [comment] 2018-03-16 05:07
/duplicate of https://github.com/Microsoft/vscode/issues/45892

**Closed** 2018-03-16 05:07 UTC
Labels: *duplicate
