### ISSUE TITLE
Code intellisense should provide the variables in scopes or nearly first

### ISSUE THREAD

**Issue by mosluce** [Microsoft/vscode#14584] opened 2016-10-27 08:54 UTC
- VSCode Version: 1.7.0-insider（1.7.0-insider）9d472850269c3f7ff1043b86f823115927af1982
- OS Version: macOS 10.12

Steps to Reproduce:

1. in a express.js route 
2. input res
3. can not find req in first page of list

![2016-10-27 4 50 22](https://cloud.githubusercontent.com/assets/1487051/19760827/058d966e-9c66-11e6-9217-a7c0b8aa6202.png)

**Comment by weinand** [comment] 2016-10-27 10:42
The sorting of the proposals is alphabetically because we get the proposals from different sources and we have to sort them somehow. May be we need a better sorting strategy that takes relevance into account.

/cc @jrieken

**Comment by jrieken** [comment] 2016-10-27 12:54
this is regression from a 'fix' I made yesterday. closing as dupe of #14583

**Closed by jrieken** 2016-10-27 12:54 UTC
