### ISSUE TITLE
Profile template changes theme

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#183237] opened 2023-05-23 16:09 UTC
I created a Profile from the default Python template, and it switched my color theme (from light to dark). I wouldn't expect this Profile to affect my theme - not sure if it's a way to distinguish Profiles visually more?

**Comment by isidorn** [comment] 2023-05-24 21:38
I agree, this is subset of https://github.com/microsoft/vscode/issues/156144
So let's close it as a duplicate of that one.

**Closed by isidorn** 2023-05-24 21:38 UTC
Labels: user-profiles
