### ISSUE TITLE
Smart file/folder rename. When file is renamed VScode should find usage and update paths

### ISSUE THREAD

**Issue by liesislukas** [Microsoft/vscode#46339] opened 2018-03-22 12:33 UTC
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

Nodejs project.

1. create file `a.js`
2. create another file `b.js`
3. in `b.js` require `a.js`
4. rename `a.js` to `new_name.js`

`b.js` is broken now while it can't find required file anymore.

Does this issue occur when all extensions are disabled?: Yes

**Comment by liesislukas** [comment] 2018-03-22 12:37
it is not covered by suggested issue #42859

**Comment by mjbvz** [comment] 2018-03-22 18:35
Duplicate of #19439

**Closed by mjbvz** 2018-03-22 18:35 UTC
Labels: javascript
