### ISSUE TITLE
Ability to select multiple TreeItems

### ISSUE THREAD

**Issue by JohnstonCode** [microsoft/vscode#56344] opened 2018-08-14 11:48 UTC
Hi, I would like to be able to select multiple TreeItems and run context commands on the selected items. As if you currently want to make changes to multiple TreeItems you have to right click them one by one.

This would behave the same as with the file explorer and SourceControlResourceStates.

**Comment by alexr00** [comment] 2019-09-02 10:56
duplicate of #76941

**Closed by alexr00** 2019-09-02 10:56 UTC
Labels: explorer-custom, feature-request
