### ISSUE TITLE
Cannot find runtime 'node' on PATH.

### ISSUE THREAD

**Issue by UVk** [Microsoft/vscode#10876] opened 2016-08-24 08:05 UTC
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Open VS
2. Launch Project

Cannot debug node application. Reinstalled node and VS, added node to PATH. nothing worked.

**Comment by weinand** [comment] 2016-08-25 13:28
@UVk could you please launch the 'integrated terminal' in VS Code and  run `where node` in it. What does it show?

**Comment by moimikey** [comment] 2017-02-01 22:02
#14229

**Comment by wprater** [comment] 2017-02-14 21:09
Im getting this issue now as well.  

```

**Comment by weinand** [comment] 2017-02-15 10:12
@wprater could you please launch the 'integrated terminal' in VS Code and run `where node` (Windows) or `which node` in it. What does it show?

**Comment by mnannola** [comment] 2017-03-01 22:55
Getting this issue as well.

1. Launch VSCode 1.10.0
2. Click the 'Start Debugging' button on the Debug tab

Mac OSX 10.11.5
Using /bin/zsh as my default shell
Using nvm
Using /bin/zsh in my "terminal.integrated.shell.osx" User Settings.

Doing a `which node` in the integrated terminal results in : `/Users/MNannola/.nvm/versions/node/v4.5.0/bin/node`

**Comment by devmao** [comment] 2017-03-09 21:09
Same issue on Linux Ubuntu using nvm.
`which node`
/home/mao/.nvm/versions/node/v6.9.1/bin/node

**Comment by sebsto** [comment] 2017-03-13 17:45
same issue with VS Code 1.10.2 on MacOS Sierra 

```
$ which node 
/usr/local/bin/node
```

**Comment by weinand** [comment] 2017-03-13 21:17
@sebsto @devmao what shell are you using?

**Comment by JamesBewley** [comment] 2017-03-29 10:41
@sebsto @devmao @weinand I think the problem is that VS Code doesn't load a fresh environment (eg. run ~/.bash_profile) for each instance of VS Code.  Even when you close all instances of VS Code it will use a cached environment unless you right-click->quit the application.

If you have changed the node version using a manager such as NVM you need to do either of the following:

1. Quit VS Code completely and re-launch.
2. Go to the integrated terminal (View->Integrated Terminal) and run the following:
`source ~/.bash_profile`

I would say this is a bug as you would expect VS Code to reload the environment every time you launch a new window.

**Comment by joaomoreno** [comment] 2017-03-30 07:23
VS Code does the right thing. It reads the environment from `.bashrc`. Verify this by opening `Developer Tools` and running `process.env` from the Console.

**Comment by JamesBewley** [comment] 2017-03-30 07:40
@joaomoreno Yes is does the right thing (read .bashrc) but wrongly only does this once at startup and not for every new window?

**Comment by joaomoreno** [comment] 2017-03-30 07:44
Got it. Duplicate of #15452

**Closed by joaomoreno** 2017-03-30 07:44 UTC
Labels: needs more info

**Comment by JamesBewley** [comment] 2017-03-30 07:48
@joaomoreno I don't believe this ticket covers this issue.

The ticket explicitly accepts the current behaviour and states "_that [new] window will inherit the current process env (which is normal OS X behaviour)_".  

Although this is not normal behaviour; when you open a new tab on any terminal program you get a fresh environment.

**Comment by joaomoreno** [comment] 2017-03-30 07:51
Note that Code isn't a terminal program.

But sure: created an issue for this #23649

**Comment by NimaSoroush** [comment] 2017-07-03 11:01
I am using nvm and I fixed the issue by adding

`"runtimeExecutable": "/Users/x/.nvm/versions/node/v8.1.3/bin/node",`

to `launch.json`.

to find nvm node executable path run `which node`

**Comment by tluanga34** [comment] 2017-10-25 10:30
Above solution work for me.
