### ISSUE TITLE
Allow outline to have a separate view and activity bar icon

### ISSUE THREAD

**Issue by staffann** [Microsoft/vscode#53658] opened 2018-07-06 06:49 UTC
With VSCode 1.25, the outline feature is shown in the explorer view. That view is already used to show open editors and the full folder tree. Having the outline there as well makes it a bit cluttered and each piece of information gets very little screen area.
The Code Outline extension (which is now deprecated and doesn't seem to work anymore in 1.25) used a separate view, selected by an icon on the activity bar. Please make that possible also for the new, built-in outline feature.

**Comment by jrieken** [comment] 2018-07-06 07:11
/duplicate of https://github.com/Microsoft/vscode/issues/49923

**Closed** 2018-07-06 07:11 UTC
Labels: *duplicate, feature-request, outline
