### ISSUE TITLE
Smoke: CSS test fails with exception

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57331] opened 2018-08-28 07:55 UTC
- VSCode Version: run out of sources
- OS Version: macOS

Steps to Reproduce:
* cd `test/smoke`
* run `tsc` to compile them
* run `npm run smoketest`
* wait for the CSS test `verifies that warning becomes an error once setting changed`

=> you see an error showing up in the dev tools

```
TypeError: Cannot read property 'style' of null
    at MarkersFilterActionItem.adjustInputBox (markersPanelActions.js:225)
    at MarkersFilterActionItem.render (markersPanelActions.js:131)
    at actionbar.js:486
    at Array.forEach (<anonymous>)
    at ActionBar.push (actionbar.js:468)
    at toolbar.js:99
    at Array.forEach (<anonymous>)
    at toolbar.js:98
    at compositePart.js:185
    at CompletePromise_ctor.CompletePromise_then [as then] (winjs.base.js:1587)
    at PanelPart.CompositePart.showComposite (compositePart.js:164)
    at compositePart.js:89
    at CompletePromise_ctor.CompletePromise_then [as then] (winjs.base.js:1587)
    at PanelPart.CompositePart.doOpenComposite (compositePart.js:71)
    at PanelPart.CompositePart.openComposite (compositePart.js:56)
    at panelPart.js:122
    at CompletePromise_ctor.CompletePromise_then [as then] (winjs.base.js:1587)
    at PanelPart.openPanel (panelPart.js:122)
    at ToggleMarkersPanelAction.TogglePanelAction.run (panel.js:85)
    at actions.js:80
    at <anonymous>
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment] 2018-08-28 07:59
Duplicate of #57292

**Closed** 2018-08-28 07:59 UTC
Labels: *duplicate, bug, error-list, smoke-test
