### ISSUE TITLE
Git blame - emoji support

### ISSUE THREAD

**Issue by grahamrobbo** [microsoft/vscode#236424] opened 2024-12-18 00:09 UTC
I make use of github markdown emoji in my commit messages. 😎  It would be great if these were rendered in the Git Blame decoration and commit details.

**Comment by gjsjohnmurray** [comment] 2024-12-18 01:31
/duplicate of #235825 which is apparently already fixed in Insiders.

**Closed** 2024-12-18 01:32 UTC
Labels: *duplicate

**Comment by grahamrobbo** [comment] 2024-12-18 02:29
Thanks - I should have searched closed issues for it - not just open ones. Sorry. 🙏
