### ISSUE TITLE
Add EOL option

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3124] opened 2016-02-18 15:48 UTC
fyi @dbaeumer

**Comment by dbaeumer** [comment] 2016-02-18 15:58
+1

**Comment by egamma** [comment] 2016-02-19 11:55
Very compact description :smile:. Is this related to #2957

**Comment by glen-84** [comment] 2016-02-20 18:50
Duplicate of #1546?

**Comment by egamma** [comment] 2016-02-21 10:35
yes, closing in favor of #2957 and moving the labels and milestone over to this issue.

**Closed by egamma** 2016-02-21 10:35 UTC
Labels: editor, feature-request, important
