### ISSUE TITLE
Linux: implement a different watcher that does not require file handles per file in the workspace folder

### ISSUE THREAD

**Issue by GregoryLundberg** [microsoft/vscode#45295] opened 2018-03-08 13:36 UTC
- VSCode Version: 1.21.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Run 'code' from command line or click menu item to run it.

Does this issue occur when all extensions are disabled?: Yes

Dialog message indicates the web page has help. It does not.

Bumped (soft) open file limit from 1024 to 4096: no help.

**Comment by Stigjb** [comment] 2018-03-08 14:19
I just got this myself when opening a new folder in a window I had open. I clicked the button to see instructions, but nothing happened.

VS Code version: 1.21.0
OS version: Linux Mint 18.2 Sonya 64-bit.

**Comment by bpasero** [comment] 2018-03-08 16:49
@GregoryLundberg @Stigjb the button should open a browser pointing to these instructions: https://code.visualstudio.com/docs/setup/linux#_error-enospc

Did no browser open?

**Comment by GregoryLundberg** [comment] 2018-03-08 17:21
It opened for me, but there is nothing there about running out of file handles, only about running out of disk space. Neither are true and I clicked to never see the notification again because it's a obviously a false-positive.

**Comment by bpasero** [comment] 2018-03-08 17:26
@GregoryLundberg so you did not see https://code.visualstudio.com/docs/setup/linux#_error-enospc open in your browser? What page did open for you then?

**Comment by GregoryLundberg** [comment] 2018-03-08 17:42
YES the browser opened. YES it showed that page. NO it does not speak about how to fix your program bug claiming it ran out of FILE handles.

ENOSPC means out of space on the drive. I am not.

The notification says it's out of FILE handles. It is not. I increased the limit from 1024 to 4096 to no effect.

As I read the web page, it's about running out of some other sort of handles so it's not about FILE handles and does not apply to the notification.

I clicked to ignore the error because it's obviously a false positive since there are plenty of file handles.

I thought perhaps I could re-enable it to post a screen shot but I don't see a settings option for it. Where did you hide the options? There doesn't look to be anything under File|Preferences|Settings or <gear>|Settings.

**Comment by GregoryLundberg** [comment] 2018-03-08 17:57
OK I read what that page says and half a million file "watches" won't do. If it's really a problem you'll either need to clean up your code or document that VS Code is only for small to moderate sized projects.

My project tree has far more than half-a-million files, and there is no reason for you to "watch" every single one of them, which is, I guess, what that error is about.

I guess your notification meant "out of file-watch handles" and someone omitted the qualifier.

Perhaps the breakage is you're trying to watch everything when you really only need to watch files which are actually open in the editor (which, at the time the notification appeared was one: your release notes, which automatically appears).

**Comment by Stigjb** [comment] 2018-03-08 23:59
The browser did not open for me.

**Comment by bpasero** [comment] 2018-03-09 06:04
@GregoryLundberg we should probably update the documentation so that its clear that the ENOSPC error is in fact the same error for running out of file handles. 

Currently we have no other way than requiring you to change the limit in your config file to make it work. 

@Stigjb that is weird. if you have a http link in the editor and you ctrl+click it, does it also not open any browser?

**Comment by GregoryLundberg** [comment] 2018-03-09 06:14
You're serious? What in the world do you need more than 4096 open files for? If you're trying to open every file in my project, I doubt I can set the limit that high.

I suppose I could try bumping to 32K. It won't come close to opening every file, but it sounds sufficiently insane. Not that I can tell if it has an effect because I don't know how to re-enable the notification, so it seems sort of pointless.

**Comment by bpasero** [comment] 2018-03-09 06:18
@GregoryLundberg two things we can try. First, we have a setting  `"files.useExperimentalFileWatcher"`, can you try setting that to `true`, restart and then see if it happens still?

**Comment by GregoryLundberg** [comment] 2018-03-09 06:29
How do I re-enable the notification? Not much point in testing if I can't see the results.

**Comment by bpasero** [comment] 2018-03-09 06:37
@GregoryLundberg that notification shows up per workspace, so if you just rename the folder you open it should show again.

**Comment by GregoryLundberg** [comment] 2018-03-09 06:38
Sorry. No can do.

**Comment by bpasero** [comment] 2018-03-09 06:42
@GregoryLundberg no problemo, an easier way of doing it: from the command line run `code --user-data-dir <some folder>`. This will open a fresh version of Code with no prior state. That also means that you will have to change the setting I mentioned in this case again and restart once.

**Comment by GregoryLundberg** [comment] 2018-03-09 07:09
Too bad there's no way to re-enable the notifications properly. Probably should open a new issue for that. Seems like a pretty serious design flaw.

Using a forced directory, I see the notification, again.
I switched to your experimental watcher and still see the notification.
I set the max open file handles to the limit of 4096 (can't set it higher) and still see the notification.

Are you sure the message is not incorrect and it's not about file handles at all? The documentation says file WATCH handles. Maybe the documentation is correct and the notification message is wrong?

Well, whatever is wrong, it seems the correct option is to ignore it. You don't seem to need whatever you're complaining about.

**Comment by bpasero** [comment] 2018-03-09 08:42
For resetting the notification preference, we have https://github.com/Microsoft/vscode/issues/24815

The message is correct and it is about file handles. The file watcher we have needs 1 file handle per file on Linux to support the watching (unfortunately). When the list of file handles exceeds the OS limit, VS Code will still function but some file events will not be recorded and be missing. E.g. if you delete a file in the Linux explorer, you will not see that file go away from the VS Code explorer.

Another thing to try is to configure `files.watcherExclude` setting. The idea is that you can exclude parts of the workspace from watching that contain many files. You can do that back when you run normally and when you set back to "`files.useExperimentalFileWatcher: false`".

Is there a particular large folder that you hide, e.g. some `out` folder with compiled contents?

**Comment by GregoryLundberg** [comment] 2018-03-09 13:47
So problem is simply bad design on your part.

Since you use one file handle per file, you have a limit on project size of 4096 files.

You should clearly document, therefore, that VS Code is only usable for small projects. Since my project has over 8000 files just for the primary C++ headers and footers, there is no way for you to work without error.

I've not used inotify(7) but would have assumed it was more efficient than you're implying.

**Comment by bpasero** [comment] 2018-03-09 15:10
@GregoryLundberg yeah it is bad design on our part, we should only watch what is actually needed by having an API where you opt-in to specific paths that should be watched as opposed to watching everything. 

I do not think there is a way to watch files on Linux recursively without requiring a file-handle per file in the workspace. On Windows and macOS however, file watchers do NOT require any file handles per file. So this issue is actually only showing up on Linux unfortunately.

**Comment by GregoryLundberg** [comment] 2018-03-09 20:19
According to the man page, one file-watcher handle per directory should do for all files and directories within that directory. It does not say recursive, so, I'd assume (not tested) that creating, renaming or deleting a directory would get a notification event on the directory where it appears.

As I said, though, I've never actually used inotify and am not sure I could throw together a test case.

**Comment by sagebind** [comment] 2018-03-13 03:04
I'm also noticing this. I'm much more curious to hear why this is suddenly a new problem. Why did 1.20 not complain about file handles? Was it just silently ignored? I've used Code on workspaces with 10,000+ files before with no obvious issues or loss in functionality.

**Comment by bpasero** [comment] 2018-03-13 05:38
@sagebind yes it was silently ignored and you would see no file watching support without actually understanding what is going on.

**Comment by HankB** [comment] 2018-03-13 12:16
I think I'm running into the same issue. On startup I get a warning "Visual Studio Code is running out of file handles. Please follow the instructions link to resolve this issue" and the "instructions" link goes to `https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc` I see the following:
    hbarta@yggdrasil:~/Documents/shell/shell_scripts$ cat /proc/sys/fs/inotify/max_user_watches
65536
    hbarta@yggdrasil:~/Documents/shell/shell_scripts$ find .|wc -l
256

I've opened code with a single file which is a shell script. I don't have any extensions for this file. I've disable all installed extensions and restarted  code and get the same warning.

The file browser window starts with my home directory. I hope it is not trying to watch all personal files on the PC.  I thought the last time I looked, the file directory tree started with the current directory when opened.

Applying the fix from the web page eliminates the warning but it seems odd that code requires that many handles to monitor files in a working directory that has 256 files (mostly from git.) There are actually 13 project files and no subdirectories (aside from .git.)

Correction, the fix does not work. It just takes longer for the warning to show up. This is on a fairly powerful laptop:
    Lenovo Y-50
    I7-4710HQ
    16GB RAM
    SATA SSD (Samsung 850 EVO 1TB)
During this time 'top' reports over 100% CPU usage and about 12% memory usage. After a some time (5-10 minutes I think) the CPU usage and RAM usage both drop to a couple percent.

**Comment by bpasero** [comment] 2018-03-13 14:03
@HankB we meanwhile fixed this issue that we would open your home directory. If you do not want to wait for the fix to reach stable, you can use our insiders release:  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Stigjb** [comment] 2018-03-15 08:27
@bpasero A bit late to answer ­­­­– no, HTTP links in files do not open for me when I Ctrl+click. So it must probably be unrelated to this issue.

**Comment by thierer** [comment] 2018-03-15 17:43
@bpasero thanks for clarifying that it's a new notification. I also wondered why I never got that message with prior versions of vscode. That said, I now also regret disabling the warning. Is there a practical way to manually reset it before #24815 gets resolved? Permanently renaming the directory isn't really a viable solution for me neither.

**Comment by otono** [comment] 2018-03-16 14:20
For me works solution from this page https://code.visualstudio.com/docs/setup/linux#_error-enospc

> When you see this notification, it indicates that the VS Code file watcher is running out of handles because the workspace is large and contains many files.

> The limit can be increased to its maximum by editing /etc/sysctl.conf and adding this line to the end of the file:

`fs.inotify.max_user_watches=524288`

> The new value can then be loaded in by running sudo sysctl -p.

**Comment by GregoryLundberg** [comment] 2018-03-16 14:52
The 'solution' on the web page is just a hack to hide the problem.

Any solution requiring sudo is sub-optimal. It presumes that the reader actually has the required privileges, which may not be the case.

A true solution would be to improve efficiency by, for example, watching entire directories, instead of individual files. (OK, this won't completely solve the issue but it moves it far, far away before it re-appears.)

An alternative would be to fall back to the old tried-and-true method of re-scanning the entire project every now and then.

And, for those of us who know our projects don't add/remove/rename while we're using Code (or know precisely when they do), falling back to disabling automatic scans and only using manual scans, is marginally acceptable.

This is the point we're sort-of at now: if your project is large enough to tickle this bug, and you don't or won't hack your system (or the hack won't help), disabling the message so we don't have to hear the feature has been disabled, and manually re-starting Code when we need a re-scan is only slightly more hassle than having a UI feature for the operation.

So, I see three issues:

- the error message is wrong. It is not file handles which have exhausted, it is file-watcher handles: a different thing entirely.

- once suppressed, there is no way (other than mucking around in Code internals or renaming your project's directory) to re-enable the notification.

- the file-watching implementation is deficient. 

I believe I've seen action on some of these.

**Comment by 4creators** [comment] 2018-03-17 22:49
> The 'solution' on the web page is just a hack to hide the problem.

> Any solution requiring sudo is sub-optimal. It presumes that the reader actually has the required privileges, which may not be the case.

This is not the question about sub-optimal solution or sudo usage it is installer bug. Since quite a bit of ppl are using VS Code to work on MSFT repos like coreclr and corefx they hit this problem first time thay update to newest version. It should be labeled as bug or installer bug and fixed asap.

**Comment by d1sco** [comment] 2018-03-20 05:28
just got this error but ignored it, best solution for new seems to hide it like GL suggests

**Comment by MelAbgrall** [comment] 2018-03-27 13:04
hello, so I have the same issue
but i'm not using as much files as you:
I've 600 images in a subfolder, a virtualenv & my scripts

this issue however does not happen when i'm opening folders with only a few files (<10)

I'm on Fedora 26
On windows 10, I don't have this issue

**Comment by caub** [comment] 2018-04-08 21:40
I've the same `running out of file handles` error, in a directory with 25510 files in total (most are in `node_modules/**`. The big issue is that webpack hot-reload doesn't work anymore when vscode is running, because vscode consumes all the file watchers.

I didn't increase the watches limit, I'd prefer a more solid fix like mentioned in this thread

**Comment by markonyango** [comment] 2018-04-12 13:17
I have run into this problem as well. I use nodemon in my environment to restart a nodeserver. Since VS Code hogs all the filewatch handles all that's left to me is to manually start and execute my gulp and nodemon tasks.
Are you sure that the re to ignore node_modules works as it is supposed to? Once I added node_modules to files.exclude and restarted, I was able to start nodemon again from VS Codes internal terminal.

**Comment by Teebo** [comment] 2018-04-25 19:31
zx

**Comment by caub** [comment] 2018-04-27 17:50
@jasonbeach there's `files.watcherExclude`, `search.exclude`, `files.exclude` that probably fit your need

@Teebo we know that, but it's not the best way to handle it, and doesn't work well

@markonyango's thanks, what you said seems to work so far, since a week or so I tried

**Comment by skylize** [comment] 2018-05-01 16:01
@caub 
>  even if files.watcherExclude contains node_modules/**' by default, it's not helping

The glob pattern for `watcherExclude` needs to be an absolute path. Add some stars to the front of your glob to get it to ignore all node modules.
```
"files.watchExclude":  {
   "**/node_modules/**": true
}
`

**Comment by dotnetCarpenter** [comment] 2018-07-21 17:20
@markonyango nailed it! This appears to be a bug in the handling code of `files.watcherExclude` pref.

`"**/node_modules/**": true,` is a correct globing pattern but it does not work.

My file structure is:
```
project root
    |_frontend(
    |   |_ node_modules/
    |_server/
        |_ node_modules/
```

Running:
```sh
echo "MAX file watches allowed on system"
cat /proc/sys/fs/inotify/max_user_watches

echo "Current files in project - excluding node_modules"
find . -type f -not -path '**/node_modules/**' | wc -l

echo "Current files in project - including node_modules"
find . -type f | wc -l
```
outputs:
```
MAX file watches allowed on system
8192
Current files in project - excluding node_modules
149
Current files in project - including node_modules
31705
```

Current workaround is to add the following to your user settings:
```json
{
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "**/node_modules": true
    }
}
```
_Thanks to @markonyango_

vscode: 1.25.1 1dfc5e557209371715f655691b1235b6b26a06be x64
os: Linux dotnet-Aspire-ES1-311 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by acrixl** [comment] 2018-08-01 10:52
> Current workaround is to add the following to your user settings:

this solution not work for me

vscode: Code - OSS
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-26T23:50:00.463Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

debian buster/sid

**Comment by AdrienHorgnies** [comment] 2018-08-02 09:46
I encountered the same bug. It doesn't exclude the `node_modules` folder.

There should be only 55 files to watch, well under the limit : 
```bash
$ find . -not -path "**/node_modules/**" -not -path "**/.git/objects/**" -not -path "**/.git/subtree-cache/**" -type f | wc -l
55
```
But well over the limit if you don't exclude files : 
```bash
$ find . -type f | wc -l
31596
```
I'm sharing my project if you want to reproduce the bug.
It is an Angular project from a tutorial.
[The resources][official-resources] are available for free on the official site but you are supposed to create an account (choose start from scratch, extract archive then run `npm install` and the bug will appear)... So for your convenience, I uploaded a [63MB archive][archive] with node_modules already present.

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
O.S.: Ubuntu 18.04.1 LTS

I've added the following to my user settings to work around : 
```json
{
    "files.watcherExclude": {
        "./.git/objects/**": true,
        "./.git/subtree-cache/**": true,
        "./node_modules/**": true
    }
}
```

[official-resources]: https://angular-exercises.ninja-squad.com/api/packs/30/exercises/1/downloads/INSTALL
[archive]: https://files.fm/u/5fczr7m4

**Comment by acrixl** [comment] 2018-08-02 13:46
also good idea to stop use node and npm this solve problem with node_modules

**Comment by AdrienHorgnies** [comment] 2018-08-02 14:33
I've come from [an issue](https://github.com/Microsoft/vscode/issues/50417) which was marked as duplicated of this issue. The issue being the exclude pattern failing to match some directories. The work around I offered is to specify the relative path from the root to the directory to exclude. I thought it was pertinent as someone in this thread indicated the workaround of copy-pasting the default settings to the user settings didn't work.
Node and NPM is only my personal issue, I hoped that it could help people solve the more general issue being the exclude pattern not working for this setting item. I suppose you can exclude your dependency manager directory whatever it may be.
Of course, if your first-class assets number exceeds the limit, you're indeed without a work-around. But it seems very high, can't you exclude some files based on their extension ?

**Comment by acrixl** [comment] 2018-08-02 18:37
i like to start package/dependency managers holy-war, but here more interesting stuffs
is someone can check windows platform and insiders build have same problems?

**Comment by kennedybaird** [comment] 2018-08-05 03:37
@bpasero, re: https://github.com/Microsoft/vscode/issues/45295#issuecomment-372676016

Hi, using kubuntu 18.0.4 with latest kernel (4.18 rc) I am having this issue still, with insiders release `1.26-insider`

`code -v`

```
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
```

**Comment by dotnetCarpenter** [comment] 2018-08-26 15:03
This doesn't appear to be a linux _only_ issue.

#40898 is the exact same issue but on Windows 10.

`"files.watcherExclude"` just does not work...

**Comment by dotnetCarpenter** [comment] 2018-08-26 15:09
If anyone is up for fixing this, here is a good overview of which files that needs to be debugged: https://github.com/Microsoft/vscode/search?q=%22files.watcherExclude%22&unscoped_q=%22files.watcherExclude%22

The glob patterns seems to be the culprit - e.i. they do not match the correct paths.

For linux/unix, the `ignored` variable should be examined: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/unix/watcherService.ts#L111

**Comment by dotnetCarpenter** [comment] 2018-08-27 10:48
@GregoryLundberg most people who have posted here, does not have too many files in their project folder(s) but the glob patterns doesn't work, so they get the issue with no possible work-aroud.

Say you wanted a workaround so vscode at least was useable to you and you could run other programs that watch files at the same time, you would need to set `"files.watcherExclude"` for your project.

Currently you **can't**. Fixing the glob patterns is a first step to fix your originale, 500000 files in a project, problem.

**Comment by lucafaggianelli** [comment] 2018-09-28 23:00
Any update on this bug?

**Comment by Belar** [comment] 2018-11-16 21:06
I run into watcher issues a few weeks ago, seemed exactly like the problem described in https://github.com/Microsoft/vscode/issues/50417 which led me to this issue and its references; all of which fit the pattern with `node_module`, `watcherExclude` and so on.

Here are 2 observations which I didn't see mention anywhere, although behind the scenes (just a guess, I'm not familiar with VS Code code base) they "feel" like related to multi-root workspace (https://github.com/Microsoft/vscode/issues/40898)

1. Noticed with VS Code's `settings.json` (when opening using "Open Settings (JSON)"); Opening file from outside the root of workspace breaks watcher
2. Opening different directory in a new window breaks watcher

If those are expected behaviors, then you can skip the rest of the post, which is reproduction steps.

Test objects are 2 clean projects (`App1`, `App2`) generated with `create-react-app` (`npm create-react-app <project_name>` is all that's needed). After running @dotnetCarpenter script from https://github.com/Microsoft/vscode/issues/45295#issuecomment-406810939 we get:
```
MAX file watches allowed
8192
Current files in project - excluding node_modules
52
Current files in project - including node_modules
27741
```
Max file watchers count is the default one, and each project, without `node_modules`, has 52 files.

First case

`App1` can be opened in VSC without problems, `npm start` will run just fine (file changes will be recorded by VSC and the dev mode watcher). However, after opening e.g. `settings.json` with `> Preferences: Open Settings (JSON)` familiar pop-up shows up and `npm start` on `App2` will render watcher error (that's theoretically on 104 files - non `node_modules` elements from `App1` and `App2`). 
Running apps isn't necessary, a "reliable", minimal reproduction is to open `App1`, open `src/App.js`, open `settings.json`, do changes with saving to the `src/App.js` and switch tabs to `settings.json` - should suffice for pop-up to show up (although it's not 100%, more like 85), `npm start` will render watcher errors.

Second case

Open `App1` in VSC, run it (order doesn't matter), changes will be recorded correctly e.g. correctly reflected in VSC's git tool. Open new VSC window (`Ctrl + Shift + N`), open `App2`. Familiar pop-up  may (should, but not always) show up now, and if you try to run `App2` (`npm run start`) there will be no watchers available.

When working in single directory and files within, the exclusion seems to be working as expected (at least I couldn't find a minimal reproduction; same when paying attention in real life projects). Also, didn't notice above issues (out of watchers when trying to run app in dev mode) with other editors.

I hope above helps at least a bit.

VS Code info at the time of writing:
- v1.29.1
- clean settings or `"files.useExperimentalFileWatcher": false` in global settings (which is default Linux, but in other reports it was suggested to set it explicitly)
- all extensions disabled

**Comment by natlibfi-arlehiko** [comment] 2018-12-03 06:02
Also experiencing this on Ubuntu 18.04.

**Comment by jhanschoo** [comment] 2018-12-24 10:10
To help with diagnosing this issue, I came up with this script that prints files being watched in a workspace or folder (remember to change the `workspace` variable in this zsh script)

```shell
#!/usr/bin/env zsh
# this script prints a series of paragraphs:
# - each paragraph corresponds to an inotify instance
# - the first line prints the process owning that inotify instance
# - each line in the rest of the paragraph corresponds to a file being
#   watched by the inotify instance

workspace=${HOME}/src/writerite/frontend-react

# create an associative array of inodes to their paths in the workspace
typeset -A inode_map
# list all the files in the workspace, then pass all the paths to ls to obtain
# their corresponding inodes, then sort these lines to uniquify the inodes in case
# duplicate hard links are present; then for each line
find ${HOME}/src/writerite/frontend-react -exec ls -di {} + | sort -nu -k1,1 | while read line
do
  # split it into words by the word-separator, then initialize an array with these words
  line_arr=(${=line})
  # the first word is the inode, so assign it as the key, whereas the other words form the path
  inode_map[$line_arr[1]]="$line_arr[2,-1]"
done

# for each inotify instance (found through iterating through each
# file descriptor opened by each process and seeing if it is an
# inotify file descriptor)
find /proc/*/fd/* -type l -lname 'anon_inode:inotify' 2> /dev/null |
while read line
do
  # print the process name for later printing
  process=$(sed -e 's@^/proc/\([[:digit:]]*\)/fd/[[:digit:]]*@\1@' <<< $line)
  cat "/proc/${process}/cmdline"
  echo

  # for each path to the file descriptor
  echo $line |
  # modify it to a path to the file descriptor info file
  sed -e 's@/fd/@/fdinfo/@' |
  # and print its contents
  xargs cat |
  # filter for the lines containing information about the files
  # watched in this instance (one line corresponds to one watch)
  grep inotify |
  # extract the hex-encoded inode of the file being watched
  sed -e 's/^.*ino:\([[:xdigit:]]*\) .*$/0x\1/' |
  while read line
  do
    # if the inode corresponds to a file in the workspace
    if [[ $inode_map[$((line))] ]]
    then
      # echo the file path
      echo "$inode_map[$((line))]"
    fi
  done
  echo
done

# the following one-liner simply echos the number of watches in the workspace

# find /proc/*/fd/* -type l -lname 'anon_inode:inotify' 2>/dev/null |
# sed -e 's@/fd/@/fdinfo/@' |
# xargs cat |
# grep inotify |
# sed -e 's/^.*ino:\([[:alnum:]]*\) .*$/0x\1/' |
# while read line; do find src/writerite -inum $(($line)); done;
```

**Comment by kid1412621** [comment] 2019-03-21 08:28
> @GregoryLundberg two things we can try. First, we have a setting `"files.useExperimentalFileWatcher"`, can you try setting that to `true`, restart Code and then see if it happens still?

work for me! lifesaver

**Comment by GitMensch** [comment] 2020-12-22 16:35
Was the experimental watcher activated by `files.useExperimentalFileWatcher` dropped or made the non-changeable default?

**Comment by cha0s** [comment] 2021-02-09 10:35
It doesn't work. I tried `files.useExperimentalFileWatcher`, but the issue persists. See: https://github.com/microsoft/vscode/issues/40898

**Comment by bengtj** [comment] 2021-04-14 13:44
As this still cause lots of issues for us (large repo) after setting kernel limits to max I wonder if the Linux possibilities has been investigated properly. I'm no expert at inotify() and I agree that there is probably no recursive flag like bWatchSubtree like for Windows. But to me it looks like there could be a workaround by watching directories instead.

From "man inotify":
When a directory is monitored, inotify will return events for the directory itself, and for files inside the directory.

Using this would probably mean some framework where when you want to add a file watch you would instead add an entry into the parent directory watcher that will handle forwarding for file events. But to me it sounds doable. (Not knowing vscode internals at all.)

Is there maybe already some method to get vscode to refresh directory contents whenever you expand a directory? This would be very useful to not have to remember to hit the refresh button for those folders that we are excluding from being watched. When a file is renamed or similar.

**Comment by awilkins** [comment] 2021-09-23 13:55
From `inotify(7)` man page :

> Inotify  monitoring  of  directories is not recursive: to monitor subdirectories under a directory, additional
watches must be created.  This can take a significant amount time for large directory trees.

> If monitoring an entire directory subtree, and a new subdirectory is created in that tree or an  existing  directory  is renamed into that tree, be aware that by the time you create a watch for the new subdirectory, new files (and subdirectories) may already exist inside the subdirectory.  Therefore, you may  want  to  scan  the contents  of the subdirectory immediately after adding the watch (and, if desired, recursively add watches for any subdirectories that it contains).

VSCode has 2 bits of code that mention `inotify`

- `src/vs/platform/files/node/watcher/unix/chokidarWatcherService.ts`
- `src/vs/platform/files/node/watcher/nsfw/nsfwWatcherService.ts`

The `unix` service (which uses `chokidar`) is marked deprecated (as is the `WindowsWatcherService`), so I presume the direction of travel (and maybe previously the "experimental" one) is `nsfw`.

Watcher creation is handled in `diskFileSytemProvider.ts` ; this confirms that the "legacy" watchers (Windows and Unix) are only used ...

- If you have polling enabled
- If you have legacy watching enabled

The setup code passes a list of _folders_ to the watcher.

`nsfw` as a package (and a *very* cursory flick over the code) seems to be aware that the right way to watch a directory tree in Linux is to put `inotify` watches on the folders and not the files, and similarly is aware that you use `ReadDirectoryChangesW` on Windows.

What `nsfw` doesn't seem to be aware of that Watchman does, is that the inotify events queue will overflow if there are a lot of events*. Users with high file update rates may wish to consider deepening `/proc/sys/fs/inotify/max_queued_events`. Watchman catches overflows and assumes every file in that folder changed if they occur.

What also doesn't seem to be the case is that (correct me if I'm wrong here devs... ) `nsfw` doesn't have a facility for ignoring subdirectories. Any paths you set in `files.watcherExclude[]` are handled in VSCode after events return from the watcher service - this means that globs that exclude folders that would never match like `**/.git/objects/**` or `**/node_modules/**` still return events from `nsfw` which are then subsequently ignore, whereas you could actually just never register a `inotify` user watch on these folders. Whether this improves performance a great deal I don't have numbers to support, but I'd expect that marshalling big wodges of events from a C++ program to be handled by a JS program is probably less efficient than just never doing that.

My suggestion for an improvement would be to put a callback in `nsfw` that offers up every folder that it's intending to watch to the client code, and allow the client to cancel that watch before establishing it, or to just add an extra event type to the existing callback that does this.

---

\* This assumption is based entirely on it lacking the string "overflow" in it's code tree. If

**Comment by bpasero** [comment] 2021-10-11 12:26
We will be shipping an new file watcher (https://github.com/microsoft/vscode/issues/132483) starting in insiders tomorrow that allows to exclude folders natively from watching via the `files.watcherExclude` setting. This has the advantage that you will not be running into file handle issues on Linux when you exclude large folders that need to be recursively watched.

I do not see a solution on Linux to watch a folder recursively without requiring a file handle per folder in the tree, so I will go ahead and close this issue. Recursive watching is a requirement of VS Code that we cannot lift because extensions rely on file events from any file within the opened workspace.

**Closed by bpasero** 2021-10-11 12:26 UTC
Labels: feature-request, upstream, linux, file-watcher
