### ISSUE TITLE
Background color rendered different on sides on new version

### ISSUE THREAD

**Issue by ragokan** [microsoft/vscode#154407] opened 2022-07-07 21:10 UTC
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.69.0
- OS Version: MacOS Monterey 12.4 (M1)

Steps to Reproduce:

1. Just use the editor.

![image](https://user-images.githubusercontent.com/63511519/177871655-55dc7cf5-f7b6-43d8-8ed5-014453197b3b.png)

![image](https://user-images.githubusercontent.com/63511519/177871722-0894ac5e-f642-40b5-a0e1-6762804a8263.png)

https://user-images.githubusercontent.com/63511519/177871786-3f96a763-4e60-4157-94a5-28f3584cacfb.mov

I tried this on my Windows laptop, there were no problem. I am also having the same problem while using VSCode portable without any extension/settings. Also I tried disabling all extensions, did not help.

This problem started in **VSCode Insiders** like weeks ago, and today, with the new update, **VSCode** also got this. I don't know if it is a bug or not but I tried many settings, nothing changed it.

**Comment by lucasfcm9** [comment] 2022-07-07 21:14
I'm with the same bug, and my laptop it's the same as yours! :(

**Comment by ragokan** [comment] 2022-07-07 21:15
> I'm with the same bug, and my laptop it's the same as yours! :(

So I think the problem is for MacOS?

**Comment by lucasfcm9** [comment] 2022-07-07 21:16
> > I'm with the same bug, and my laptop it's the same as yours! :(
> 
> So I think the problem is for MacOS?

Maybe

**Comment by tomasz-tomczyk** [comment] 2022-07-07 21:22
I've got the same issue ever since the update, I'm on MacOS Monterey 12.3.1 - tried several themes

**Comment by Igorgro** [comment] 2022-07-07 21:22
Duplicate of https://github.com/microsoft/vscode/issues/152816

**Comment by deepak1556** [comment] 2022-07-08 02:36
Merging to https://github.com/microsoft/vscode/issues/152816

**Closed by deepak1556** 2022-07-08 02:36 UTC
Labels: triage-needed, new release
