### ISSUE TITLE
Copy on drag drop not working

### ISSUE THREAD

**Issue by mika76** [microsoft/vscode#24000] opened 2017-04-06 06:59 UTC
- VSCode Version: 1.11.0
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. The release notes show "unassigned" for the osx key. (this happened the moment I upgraded, no keybindings were changed) and closing/reopening vscode does not help.
![screen shot 2017-04-06 at 08 53 24](https://cloud.githubusercontent.com/assets/229311/24741572/c8157a1c-1aa6-11e7-8cb7-97e10bceb3ac.png)
2. As far as I can see all my keybindings are set to default (I have never changed them)
3. I see from the release notes online the assigned key should be option - if I use option it just ignores drag drop totally and re-selects the text to the cursor. Not even move drag drop happens. If I do not use the option key then normal drag drop move works.

**Comment by chrmarti** [comment] 2017-04-06 15:38
@mika76 Is this with a U.S. keyboard layout?

**Comment by mika76** [comment] 2017-04-06 16:16
Yes, US layout

**Comment by rebornix** [comment] 2017-04-06 18:33
@mika76 the `unknown` key might be an issue with our release note but the option key should work. The only catch is you need to drag selection first and then press Option key, otherwise it runs into our multi cursor mode.

**Comment by mika76** [comment] 2017-04-06 18:46
Nope, I tried all kinds of combinations and it doesn't work. Normal drag and move works, but copy not at all.

**Comment by mistajay** [comment] 2017-04-07 12:22
Mac on Sierra, US layout, version 1.11.1, Drag and Drop doesn't work for me by itself, nor with `Command`, `Option (alt)`, or `Control` being pressed and being held( before and while dragging). The selected text does move with `Option + Up` and `Option + Down`. This feature is one I've been waiting for since I tried VS Code last year.

Thank you for such an amazing editor, I install it on everything I can.

**Comment by rebornix** [comment] 2017-04-11 17:52
@mistajay do you mean the drag and drop feature doesn't work at all? Is `editor.dragAndDrop` set to `true`?

**Comment by mistajay** [comment] 2017-04-11 18:21
@rebornix I'm dumb, the option was set to `false`.  Changing it to `true` in user settings made it work, and the `Option` key copies selected text like it is supposed to for me now.

**Comment by rebornix** [comment] 2017-04-11 18:22
@mistajay I'll say our discoverability is not that good :)

@mika76 can you provide a gif for me to troubleshoot.

**Comment by mika76** [comment] 2017-04-11 19:15
Hi @rebornix 

Here it is. Funny enough the release notes now Say `option` when before they said `unassigned` (even after restrating vscode a couple of times), but the copy drag still does not work.

In the following gif I do drag-move once to the bottom, then again to the top, and then I try with holding the `option` key and it just keeps selecting the text.

![vscode_copy_drag](https://cloud.githubusercontent.com/assets/229311/24926375/a7695e10-1efb-11e7-9a72-f82aef8b740e.gif)

If there's any code I can run to debug this please just send me the instructions.

Thanks

**Comment by mika76** [comment] 2017-04-11 19:21
Hah I see why the `option` key shows now: https://github.com/Microsoft/vscode-docs/commit/380fe679cce9f12c73888cb12f7999b2203a4b73

A bit of smoke 'n mirrors 🤣

**Comment by rebornix** [comment] 2018-09-07 22:59
The copy&drop works when we press option key and drag the selection, but not clicking. Option+Click will still shrink the selection.

**Comment by Enpega** [comment] 2020-05-19 19:35
Same problem here. OSX 10.11
VSCode
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 15.6.0

I may add that every now and then  (very now and then) when I press the Option key the cursor changes to show the green circle with the plus sign, but when I start dragging it disappears and just keeps selecting text.

**Comment by rebornix** [comment] 2020-11-11 22:58
> I may add that every now and then (very now and then) when I press the Option key the cursor changes to show the green circle with the plus sign, but when I start dragging it disappears and just keeps selecting text.


This is because we have `alt` also for multi cursor selection, which conflicts with the drag and drop. Please check if 

* select a piece of text
* start dragging
* press alt key
* move to a position and drop

I tested again in macOS Catalina with latest Insiders and it works so I'm closing it for now but we can reopen if you can still reproduce.

**Closed by rebornix** 2020-11-11 22:58 UTC
Labels: bug, editor-drag-and-drop

**Comment by mika76** [comment] 2020-11-12 05:18
Wow old bug. Yup testing it myself (on stable) and it seems to work if pressing option after starting a drag.
