### ISSUE TITLE
Input sources panel's position is wrong when begin to type

### ISSUE THREAD

**Issue by kaiye** [Microsoft/vscode#896] opened 2015-12-02 02:14 UTC
I use __Pinyin - Simplified__ to input Chinese character .

<img width="718" alt="Pinyin - Simplified Input Source" src="https://cloud.githubusercontent.com/assets/344283/11520152/a4c67190-98db-11e5-99ec-d1ed8b85226f.png">

When I begin typing,  the input sources panel positioned unexpectedly.

![input-panel-error](https://cloud.githubusercontent.com/assets/344283/11520226/64285f44-98dc-11e5-8854-4ef9b94d85cd.gif)

It should perform like  Sublime Text.

![input-panel-correct](https://cloud.githubusercontent.com/assets/344283/11520263/cb3e7fec-98dc-11e5-8e36-c9098ec3930c.gif)

**Comment by alexandrudima** [comment] 2015-12-02 08:12
The underlying problem is the textarea is positioned in the top left corner until we get the first composition start event

**Comment by alexandrudima** [comment] 2016-07-04 16:01
Duplicate of #356

**Closed by alexandrudima** 2016-07-04 16:01 UTC
Labels: bug, mac
