### ISSUE TITLE
Allow getting path of a non-textual file

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode#17703] opened 2016-12-21 22:55 UTC
- VSCode Version: 1.8.1
- OS Version: Win10

Unless I'm missing something it's impossible to get file object (or simply file path as string) in extension if you have a non-textual file open.

The use case here is that you open let's say an image file, or docx file in vscode, and you want to provide a hotkey for opening this file in your default app associated with given extension. This is a case that I wanted to fix in a small extension sandcastle/vscode-open#2.

For text file it's simple because you could simply get `vscode.window.activeTextEditor.document`, but that's not a case in case of any format unsupported by VSCode.

I tried to get a inspiration using `workbench.action.files.copyPathOfActiveFile` command, so it took me to [`GlobalCopyPathAction`](https://github.com/Microsoft/vscode/blob/e179ec75abb7c3cb225001269561d4a31fe9b673/src/vs/workbench/parts/files/electron-browser/electronFileActions.ts#L89) class, but it uses `editorService` which  I believe is not exposed to extensions API.

**Comment by mlewand** [comment] 2016-12-21 23:00
I fear that the proper solution would only be implemented with #2582, but I hope I'm just missing something in your API. :)

**Comment by jrieken** [comment] 2016-12-27 09:02
Yes - binary files have no representation in the API atm. Closing as dupe of #2582

**Closed by jrieken** 2016-12-27 09:02 UTC
Labels: api
