### ISSUE TITLE
Default new window position and size

### ISSUE THREAD

**Issue by youurayy** [Microsoft/vscode#17105] opened 2016-12-13 09:53 UTC
When I open a new window in VS Code (Ctrl/Cmd+Shift+N), the new window takes about 1/3 of the screen and I need to manually resize it to make it bigger.  (On Windows this may not be a huge issue since there's the maximize button. But on a Mac, laborious manual resizing is needed to keep windows in the same space.)

Wanted behavior: The window is sized and positioned with the size and position taken from the last user-sized and the last user-positioned window.

Possible workaround if this is hard to implement: add an option to specify new default window size and an option to specify a new default window position, both in pixels.

This is **NOT** a duplicate of #9534 **nor** a duplicate of #422.

**Comment by bpasero** [comment] 2016-12-13 17:33
@youurayy but duplicate of https://github.com/Microsoft/vscode/issues/10864

**Comment by kieferrm** [comment] 2016-12-13 18:41
Duplicate of #10864.

**Closed by kieferrm** 2016-12-13 18:41 UTC
Labels: duplicate

**Comment by youurayy** [comment] 2016-12-13 20:23
did not find it in a search, thanks.
