### ISSUE TITLE
Changes to file language and indentation type do not presit

### ISSUE THREAD

**Issue by eladts** [Microsoft/vscode#4703] opened 2016-03-28 04:11 UTC
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open a file and change the language and/or indentation type.
2.  Close the window.
3. Reopen the window.

The file will be loaded again but it will have the default language and indentation type.

**Comment by Tyriar** [comment] 2016-03-28 18:58
Duplicate of https://github.com/Microsoft/vscode/issues/3612

More convenient persisting of language modes are coming in the March release, available currently in the insiders build code.visualstudio.com/Download

As for the indentation, I think this is as designed. Open a new issue if you want to look in to that. I recommend the [editorconfig extension on the marketplace](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) for handling indentation settings across file types for you.

**Closed by Tyriar** 2016-03-28 18:58 UTC
