### ISSUE TITLE
Wrong JS references

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25139] opened 2017-04-21 12:12 UTC
- VSCode Version: 1.11.2
- OS Version: Linux Ubuntu 16.04

Hello, I think there's problem with JS references... I have `class Server` and it shows 2 references, but it's only 1.

![screenshot from 2017-04-21 15-11-06](https://cloud.githubusercontent.com/assets/10441177/25276852/e3d6456a-26a4-11e7-8067-2525df1d10ec.png)

P.S. I have `jsconfig.json` in my root, you can check whole project here: [svipben/react-boilerplate](https://github.com/svipben/react-boilerplate).

**Comment by svipben** [comment] 2017-04-21 12:27
Weird, but after VS Code restart everything again correct, shows 1 reference, but I noticed this in the past, but forgot to open the issue.

**Comment by mjbvz** [comment] 2017-05-03 22:45
Please let me know if you have a small project or code example that reliably reproduces this problem. I've seen this sort of things reported while switching branches sometimes.

Do you remember if editing the file caused the reference count to be correctly updated?

**Comment by svipben** [comment] 2017-05-04 14:40
@mjbvz No, updating file doesn't update references, only VS Code restart. Right now I just turned off references, since I saw it was distracting for me and I wasn't using them, but this is still bug which is hard to track.

**Comment by mjbvz** [comment] 2017-06-02 00:05
I just tried loaded up an old commit from your example project with TS 2.4, and the reference count now appears to be correct. Here's how to test this out yourself https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

From the error logs, I believe this may have been a duplicate of https://github.com/Microsoft/TypeScript/issues/15814

We don't plan on bundling TS 2.4 with VSCode until 1.14

**Closed by mjbvz** 2017-06-02 00:05 UTC
Labels: bug, javascript, needs more info, typescript
