### ISSUE TITLE
 Model is disposed!

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#27252] opened 2017-05-25 10:11 UTC
Issue Id: <b>a49f9e26-237e-18ae-5ba8-5da5d9fd87ba</b><br /><br />*Versions* <br />- 1.12.2<br />*Stack* <br />Error: Model is disposed!<br />[/vs/editor/common/model/textModel.ts#L116:9](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/common/model/textModel.ts#L116:9)<br />[/vs/editor/common/model/textModelWithTokens.ts#L404:7 (_assertNotDisposed)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/common/model/textModelWithTokens.ts#L404:7 (_assertNotDisposed))<br />[/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L95:23 (getWordAtPosition)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L95:23 (getWordAtPosition))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1813:0 (complete)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1813:0 (complete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1838:0 (argDone)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1838:0 (argDone))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />

**Comment by jrieken** [comment] 2017-06-19 08:21
dupe of #27248

**Closed by jrieken** 2017-06-19 08:21 UTC
Labels: error-telemetry
