### ISSUE TITLE
When an extension is downgraded to an earlier version manually by user, it shouldn't get auto-updated to latest version automatically

### ISSUE THREAD

**Issue by ronakg** [microsoft/vscode#103585] opened 2020-07-29 20:47 UTC
I ran into this issue today. I had to manually downgrade the [vscode-java extension](https://marketplace.visualstudio.com/items?itemName=redhat.java) because of incompatibility. This manual action from user should indicate that I don't want to auto-update the extension to latest version. So this extension should be taken off the list of auto-updating extensions. When the user clicks the suggested action of updating to the latest version from the extensions window, it can be put back on the auto-update list.

- VSCode Version: 1.47.3
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Downgrade any extension from latest to an earlier one manually from the extension settings
2. Wait for the extension auto-upgrade routine to kick-off

Does this issue occur when all extensions are disabled?: NA, the issue is about the extension management

**Comment by sandy081** [comment] 2020-07-30 07:10
@ronakg I cannot reproduce it and I am on 1.47.3. I have auto updates on and I downgraded the TS Lint extension and it did not get auto updated

<img width="714" alt="image" src="https://user-images.githubusercontent.com/10746682/88892057-7b82cc00-d244-11ea-90b1-ce7c47f51abb.png">

**Comment by ronakg** [comment] 2020-07-30 07:19
It happened for me two days in a row. I'll update here if it happens again.

**Comment by sandy081** [comment] 2020-10-19 14:11
Waiting for user info.

Closing this. Please reopen this with necessary steps and information.

**Closed by sandy081** 2020-10-19 14:11 UTC
Labels: needs more info
