### ISSUE TITLE
Installing plugins behind corp proxy is broken

### ISSUE THREAD

**Issue by hipertracker** [Microsoft/vscode#1853] opened 2016-01-07 15:00 UTC
* For Visual Studio Code 0.10./6
* And for Windows 7 Enterprise SP1
* When in the cmd I `type %HTTP_PROXY%`
* Then I get "http://proxy.mydomain.com:8083"
* And when I try do install any extension, e.g. PureScript language supports.
* Then I get the error: `getaddrinfo ENOTFOUND proxy.ml.mydomain:8083 proxy.mydomain.com:8083:8083`

My User Settings  is `{ "http.proxyStrictSSL": false }`

My Workspace Settings is `{..."http.proxy": ""...}`

WTF? And why the port is duplicated??? 

I get the same error even when I overwrite "http.proxy" with explicit value in my User Settings.

**Comment by joaomoreno** [comment] 2016-01-07 15:08
Duplicate of #69 

There is a workaround in #69 that will get you the support you want. The proper fix will come in January.

**Closed by joaomoreno** 2016-01-07 15:08 UTC
