### ISSUE TITLE
Replace dialog doesn't fully go away if contains multiple lines

### ISSUE THREAD

**Issue by puzzlexx** [microsoft/vscode#81946] opened 2019-10-04 09:48 UTC
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Open replace dialog box ("Edit-Replace" or Ctrl+H)
2. Select "replace with" input box (bottommost)
3. Type in several words, separated with Ctrl+Enter or Shift+Enter
4. Close dialog (Esc)

Actual result: dialog moves up but part of the dialog remains visible
Extected result: dialog moves up and fully hides itself

![Screenshot_3](https://user-images.githubusercontent.com/10653234/66198419-96d58700-e6c6-11e9-8c4f-6fda9ebfa3fb.png)
![Screenshot_4](https://user-images.githubusercontent.com/10653234/66198431-9d63fe80-e6c6-11e9-8700-4de4518236b1.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.1.7601

**Comment by rebornix** [comment] 2019-10-23 18:11
/duplicate of https://github.com/microsoft/vscode/issues/82978 and fixed in master.

**Closed** 2019-10-23 18:11 UTC
Labels: *duplicate, bug, editor-find
