### ISSUE TITLE
Intellisense for `scope` in global snippets file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#42541] opened 2018-01-30 20:04 UTC
Testing https://github.com/Microsoft/vscode/issues/42330

Would be useful to have intellisense for registered language IDs in `scope`, so I don't have to remember exactly what they are, and don't typo them.

**Comment by jrieken** [comment] 2018-01-31 08:10
dupe of https://github.com/Microsoft/vscode/issues/42537

**Closed by jrieken** 2018-01-31 08:10 UTC
