### ISSUE TITLE
Go forward and back randomly apply to different split views

### ISSUE THREAD

**Issue by nkaretnikov** [microsoft/vscode#137964] opened 2021-11-27 02:32 UTC
Issue Type: <b>Bug</b>

I use `View: Split Editor Down` to open two views of the same file. One of the views is in focus.
When I navigate back and forth in history, sometimes the other view changes. Happens with multiple splits too.

I'm used to vim. And the way it works there is that all navigation actions apply only to the current split view. Unless you change focus.

I've actually seen this problem in Visual Studio too. So maybe I'm misunderstanding how it's supposed to be used. Or it's a bug in multiple products. I wonder if it's due to me looking at the same file and vscode just has no way of knowing which is which.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-89-generic

**Comment by nkaretnikov** [comment] 2021-11-27 02:34
Maybe there's a different way of accomplishing the same task, not sure. I use splits because that's what the vim mode in vscode uses too.

**Comment by nkaretnikov** [comment] 2021-11-27 14:00
@bpasero hi, what issue does this one duplicate? i couldn't find anything similar when i opened this one.

**Comment by bpasero** [comment] 2021-11-27 16:25
I had initially thought any of these: https://github.com/microsoft/vscode/labels/workbench-history

But changing an editor in a group that is not active and not moving focus there sounds like a new issue to me. Can you record a video of how this looks like?

/gifPlease

**Comment by nkaretnikov** [comment] 2021-11-27 23:50
@bpasero sorry, the link you posted doesn't seem to work for me. i also can't figure out how to upload my gif anywhere because it's 10 mb. i uploaded it to my dropbox. live preview fails there, but you should be able to download and view it locally.

```
https://www.dropbox.com/s/wiz4mgze0vh45x0/vscode_demo.gif?dl=0
```

in the video:
- i have the same file opened
- the right side is the current one
- i use f12 to `Go to Definition` two times (this is fine)
- then i `Go Back` and the left view is updated instead of the current one (this is not what i expect).

**Comment by nkaretnikov** [comment] 2021-11-27 23:53
@bpasero note: i also use this `Download` button, the other one doesn't seem to work for me:

<img width="628" alt="Screen Shot 2021-11-28 at 02 44 24" src="https://user-images.githubusercontent.com/10469885/143723761-987b44ff-61e6-4e5f-b725-02f980f59d73.png">

**Comment by bpasero** [comment] 2021-11-28 07:02
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment] 2021-11-28 07:04
@nkaretnikov understood, one thing I had forgotten: when an editor to navigate to is already opened in any of the opened editor groups, we prefer to navigate to that editor so that we prevent opening/revealing an editor in the current group.

So I still believe that this issue is a duplicate of https://github.com/microsoft/vscode/issues/9526 and https://github.com/microsoft/vscode/issues/45233

**Comment by nkaretnikov** [comment] 2021-11-28 17:03
@bpasero maybe, i'm not familiar with vscode internals/terminology to say for sure. feel free to ping me later once this is addressed, i can test again. ty!

**Closed** 2021-11-29 06:55 UTC
Labels: needs more info, *duplicate, workbench-history
