### ISSUE TITLE
commands contributed to debug/callstack/context are not called

### ISSUE THREAD

**Issue by hbenl** [microsoft/vscode#80921] opened 2019-09-14 12:19 UTC
- VSCode Version: 1.38.1 / 1.39.0-insider (2019-09-12)
- OS Version: Arch Linux (64bit)

My [extension](https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug) contributes a command to the `debug/callstack/context` menu. But when I click on that menu item, my command isn't called. This contribution did work in the past, I haven't tried it for a while, so I don't know in which VSCode version it broke.

From my `package.json`:
- in `contributes.commands`:
```
      {
        "command": "extension.firefox.toggleSkippingFile",
        "title": "Toggle skipping this file"
      },
```
- in `contributes.menus`:
```
      "debug/callstack/context": [
        {
          "command": "extension.firefox.toggleSkippingFile",
          "when": "inDebugMode && debugType == 'firefox' && callStackItemType == 'stackFrame'"
        }
      ],
```

**Comment by isidorn** [comment] 2019-09-16 14:25
Your command should not be called, it should just be seen in the Context menu when the user right clicks on the stack frame.

I can not reproduce this with Node debug since it also contributes a Restart Frame command on stackFrame call stack as seen [here](https://github.com/microsoft/vscode-node-debug2/blob/master/package.json#L499)

Can you please create a reproducable case using the [Mock Debug](https://github.com/microsoft/vscode-mock-debug). Craete a fork and give me the link so I can investigate more. Thanks

**Comment by hbenl** [comment] 2019-09-17 16:17
> Your command should not be called, it should just be seen in the Context menu when the user right clicks on the stack frame.

OK, what I meant was that the command shows up in the context menu, but when I click that menu entry, my code for the command is not called.

Here's my testcase: https://github.com/hbenl/vscode-mock-debug/commit/8a3c17bb482b1aeb93d717a4bc562ede16e827df
It adds 2 commands: the second one ("dummy") can be called via the palette and shows an information message. The first one ("toggleSkippingFile") can be called via the stack frame context menu and should also show an information message but doesn't and if you add a breakpoint in the `sendCustomRequest()` function that both commands call, that breakpoint will only get hit when you call the "dummy" command.

**Comment by isidorn** [comment] 2019-09-19 15:34
Great catch and great steps. 
Sorry for the breakage, I have pushed a fix and you can find it in tomorrow's vscode insiders. Try it out and let me know how ti behaves.

**Closed** 2019-09-19 15:33 UTC
Labels: debug, needs more info

**Comment by hbenl** [comment] 2019-09-20 10:31
Just tried with the latest insiders build and now it works as expected. Thanks!

**Comment by isidorn** [comment] 2019-09-20 10:33
Thanks, adding verified label per your comment.
