### ISSUE TITLE
Window maximizes non properly after exiting from zen mode

### ISSUE THREAD

**Issue by PogromistDev** [microsoft/vscode#85504] opened 2019-11-24 19:58 UTC
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Enter Zen Mode
2. Exit Zen Mode
![Zen-Mode](https://user-images.githubusercontent.com/12221569/69500642-42a49180-0f16-11ea-92be-91276de26a81.png)

**Comment by gjsjohnmurray** [comment] 2019-11-24 20:35
/duplicate of #83456 which is fixed in the imminent recovery release

**Closed by gjsjohnmurray** 2019-11-24 20:35 UTC
Labels: *duplicate
