### ISSUE TITLE
Unable to find some extensions.

### ISSUE THREAD

**Issue by yololftw** [microsoft/vscode#109274] opened 2020-10-24 01:44 UTC
- VSCode Version:  1.49.1
- OS Version: Manjaro Linux; Build ID: **rolling**

Steps to Reproduce:

1. Install VS Code
2. Search for extensions : React Native Tools
3 Observe that the microsoft React Native Tools extension is not visible
**
![image](https://user-images.githubusercontent.com/16657803/97064998-ee8faa80-15c7-11eb-8caa-6c98527ecc16.png)
**
4 Do the same with pylance 
5 Observe that this one is also not available 
![image](https://user-images.githubusercontent.com/16657803/97065034-226ad000-15c8-11eb-96f0-3a8c9943b652.png)
6 Try Using the `ext install ms-python.vscode-pylance` with the quick open, observe the same
7 Had the same issue with react native tools as well.

Note :  Work around is to download the extensions from the extensions website and manually install the VSIX

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tamuratak** [comment] 2020-10-24 02:05
Duplicate of #107997. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Closed** 2020-10-26 14:45 UTC
