### ISSUE TITLE
Refactoring to turn single line arrow function into multi-line and back

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode#51737] opened 2018-06-13 03:23 UTC
Could not find a dup. Sorry if it is.

I find myself converting between these 2 very very often:
```typescript
f(x => compute(x))
```

```typescript
f(x => {
    return compute(x);
}
```

Can I please suggest an automatic refactoring for this? I guess this applies to both JS and Typescript.

Prior art: Resharper and C#
https://www.jetbrains.com/help/resharper/ConvertToLambdaExpression.html

**Comment by mjbvz** [comment] 2018-06-13 17:20
Thanks. Duplicate of https://github.com/Microsoft/TypeScript/issues/23299

**Closed by mjbvz** 2018-06-13 17:20 UTC
Labels: typescript
