### ISSUE TITLE
[Typescript] Useless hover

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#37085] opened 2017-10-28 18:34 UTC
1. Import something from another module
2. Hover over
3. See that it shows you `import "thingy"`

![import eglist](https://user-images.githubusercontent.com/9638156/32137316-203bc52c-bc26-11e7-9d9e-dd0b5e7edb41.png)

The expected behavior happens when you hold modifier key for `follow link`. 
![good](https://user-images.githubusercontent.com/9638156/32137376-342cdba6-bc27-11e7-8682-8644d53137e9.png)

Wouldn't it be better to show types by default?

**Comment by mjbvz** [comment] 2017-10-30 17:39
Duplicate of https://github.com/Microsoft/TypeScript/issues/5515

**Closed by mjbvz** 2017-10-30 17:39 UTC
Labels: typescript, upstream

**Comment by usernamehw** [comment] 2017-10-30 18:27
Maybe it's better to leave 1 opened issue in vscode repository (for upstream ones). I don't usually search in closed issues (and, I think, not many people do).
