### ISSUE TITLE
Pending breakpoint not saved across restarts

### ISSUE THREAD

**Issue by ivanhernandez13** [microsoft/vscode#103165] opened 2020-07-23 14:13 UTC
Issue Type: <b>Bug</b>

1. git clone https://github.com/ivanhernandez13/vscode-mock-debug.git
1. open and run the mock debug extension.
1. start a debug session with any markdown file.
1. set a breakpoint anywhere.
1. close the extension development host in under 5 seconds.
1. reopen extension development host and notice breakpoint is gone.

The vscode-mock-debug fork includes a small change to delay the setBreakpoint response by 5 seconds to keep the breakpoint pending during that time.  You can also repro by running `Developer: Reload Window` from the command palette during that time.

This issue came up due to a crash in VS Code shortly after a breakpoint was set that caused all breakpoints to go away. I was able to repro with the simpler case above that causes all my breakpoints to be removed, even the ones that were set before the session. I can't repro losing ALL breakpoints with vscode-mock-debug so likely the debugger extension I'm using is contributing to that problem but vscode-mock-debug does still lose any pending breakpoints.

Setting breakpoints without a debug session, as well as setting and waiting until the breakpoint has been confirmed both result in breakpoints being persisted across restarts.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

**Comment by weinand** [comment] 2020-07-23 14:54
Could you please change the setting `"debug.javascript.usePreview"` to `false` and see whether this makes a difference.

**Comment by ivanhernandez13** [comment] 2020-07-23 14:59
Added and restarted VS Code, It did not make a difference.

**Comment by weinand** [comment] 2020-07-27 08:18
@isidorn this might be related to https://github.com/microsoft/vscode/issues/103111.
There is some risk losing breakpoints from persistent storage if a DA doesn't "behave well".

**Comment by isidorn** [comment] 2020-07-28 09:08
@ivanhernandez13 thanks for the great steps, however can you reproduce with latest vscode insiders since we pushed a fix for a related issue #103111
If you can repro with insiders then it is unrelated and I can investigate further.
https://code.visualstudio.com/insiders/

**Comment by ivanhernandez13** [comment] 2020-07-28 13:06
I can repro with code-insiders.

Version: 1.48.0-insider
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:40:03.139Z (2 hrs ago)
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

**Comment by isidorn** [comment] 2020-07-28 14:46
Ok, thanks. Assigning to July so invesitgate further this week.

**Comment by isidorn** [comment] 2020-07-29 13:28
@ivanhernandez13 I pushed a fix for this. It would be great if you could try it out with vscode insiders starting from Thursday. Thanks!

**Closed** 2020-07-29 13:28 UTC
Labels: bug, debug

**Comment by ivanhernandez13** [comment] 2020-07-30 20:10
Updated insiders today and can no longer reproduce, thanks!

**Comment by isidorn** [comment] 2020-07-31 07:16
Thanks for letting us know, adding verified label.
