### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by cydhhp** [microsoft/vscode#183546] opened 2023-05-26 14:17 UTC
Type: <b>Bug</b>

VSCode can't login

Step:
click login > microfoft > edge > login > success,
But always not!

Here is log
====
2023-05-26 21:57:58.847 [error] Network failure: Error: Network failure
at f.G (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:2:556571)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at f.F (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:2:555729)
at f.p (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:2:549116)
at f.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:2:548195)
at Object.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:2:988955)

2023-05-26 22:13:36.139 [error] SyntaxError: Unexpected token '�', "��p[*��PC"... is not valid JSON
at JSON.parse (<anonymous>)
at e.MainThreadSecretState.$getPassword (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:48130)
====

VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 16, 19|
|Memory (System)|16.00GB (6.32GB free)|
|Process Argv|--crash-reporter-id 3a3c6acc-bce6-471a-9cf0-cac58cb899dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
swagger-viewer|Arj|3.1.2
vscode-combine-scripts|Bat|2.0.5
zh-hans-tt-hant-vscode|cip|1.0.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.64.0
flutter|Dar|3.64.0
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
gitlens|eam|13.6.0
json-tools|eri|1.0.2
prettier-vscode|esb|9.13.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
fortify-extension-for-vs-code|for|22.1.0
live-sass|gle|6.0.5
go|gol|0.38.0
beautify|Hoo|1.5.0
rest-client|hum|0.25.1
ilspy-vscode|ics|0.15.0
copy-filename|jac|2.3.2
vscode-edit-csv|jan|0.7.6
autofilename|Jer|0.1.3
regionfolder|map|1.0.22
Kotlin|mat|1.7.1
vscode-language-babel|mgm|0.0.39
gitignore|mic|1.0.1
compare-folders|mos|0.22.5
hg|mrc|1.9.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.25.1
vscode-language-pack-zh-hant|MS-|1.78.2023051009
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.19.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.1.1
isort|ms-|2022.8.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.40
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
color-highlight|nau|2.5.0
vetur|oct|0.37.3
subtitles-editor|pep|1.1.7
quicktype|qui|12.0.46
java|red|1.18.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.13.0
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.6.8
code-eol|soh|0.3.3
code-spell-checker|str|2.20.4
email-viewer|Tom|5.0.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.50.0
vscode-java-dependency|vsc|0.22.0
vscode-java-pack|vsc|0.25.11
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0
vscode-icons|vsc|12.4.0
quokka-vscode|Wal|1.0.542

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by TylerLeonhardt** [comment] 2023-05-28 05:35
This looks identical to https://github.com/microsoft/vscode/issues/182790. I'm going to mark this as a duplicate of that one. Can you please head over to that issue and respond to my ask here: https://github.com/microsoft/vscode/issues/182790#issuecomment-1565752361

**Closed by TylerLeonhardt** 2023-05-28 05:35 UTC
