### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by khesehang** [microsoft/vscode#116569] opened 2021-02-12 17:49 UTC
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.1.5

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:109644:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:109679:29)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:109416:50)
    at InferredProject.Project.updateGraphWorker (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151529:38)
    at InferredProject.Project.updateGraph (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:151463:42)
    at updateProjectIfDirty (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152932:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155109:41)
    at c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:97
    at Object.flatMap (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:155395:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:156413:46)
    at c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:88
    at IOSession.Session.executeWithRequestId (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158277:28)
    at IOSession.Session.executeCommand (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158286:33)
    at IOSession.Session.onMessage (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158310:35)
    at Interface.<anonymous> (c:\Users\Aspire\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160520:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.40GB free)|
|Process Argv|--crash-reporter-id d8073558-4107-4d93-b02a-e5b0c2a26017|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|12.1.4
change-tab-size|alt|0.2.1
html-class-suggestions|And|1.0.7
vscode-color|ans|0.4.5
shell-syntax|bma|1.0.1
repository|bra|0.1.3693
prettier-vscode-standard|bys|0.22.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.38.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
vscode-deno|den|2.3.3
divider|din|2.3.1
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
auto-type|eee|0.1.0
vscode-npm-script|eg2|0.3.15
auto-import|Ele|0.3.12
prettier-vscode|esb|5.9.2
vscode-browser-refresh|fab|1.2.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
cloudcode|goo|1.8.0
openvpn|idl|0.2.2
package-plus-plus|jun|0.0.1
vscode-deno|jus|1.34.0
kite|kit|0.138.0
multisearch|Mik|2.0.0
file-downloader|min|1.0.9
mindaro|min|1.0.120210126
vscode-docker|ms-|1.9.1
vscode-kubernetes-tools|ms-|1.2.4
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-wsl|ms-|0.53.4
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
reload|nat|0.0.6
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
auto-rename-tag|pra|0.1.5
vscode-yaml|red|0.15.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
zsh-debug|rog|0.1.3
css-auto-prefix|spo|0.1.7
autoimport|ste|1.5.3
tabnine-vscode|Tab|3.2.7
netcool-rules|the|0.0.1
vscode-conventional-commits|viv|1.13.0
vscode-icons|vsc|11.1.0
quokka-vscode|Wal|1.0.342
vscode-todo-highlight|way|1.0.4
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
vscode-units|yas|0.3.0
go-snippets|zsh|0.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by khesehang** [comment] 2021-02-12 17:49
please help me

**Comment by mjbvz** [comment] 2021-02-12 18:53
Duplicate of #116565

**Closed by mjbvz** 2021-02-12 18:53 UTC
Labels: new release
