### ISSUE TITLE
Green (+) Mouse Appearance Appears Incorrectly

### ISSUE THREAD

**Issue by ezfe** [microsoft/vscode#78921] opened 2019-08-12 02:14 UTC
Issue Type: <b>Bug</b>

Type in something that causes the blue suggestion baloon to appear, like:

```js
function a({ x }) {

}
```

Clicking on the `x` to get it to appear. Click the suggestion balloon and then click away to dismiss it. Hold down the option key and observe the green (+) mouse.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
html-leaf|Fra|0.1.3
vsc-prolog|art|0.8.23
vscode-database|baj|2.2.0
better-toml|bun|0.3.2
arm|dan|0.5.0
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
eml|lei|0.3.2
rainbow-csv|mec|1.2.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.29288
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.24.1
vscode-typescript-tslint-plugin|ms-|1.2.2
java|red|0.47.0
sass-indented|rob|1.5.1
llvm|RRe|0.0.3
rust|rus|0.6.1
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1

</details>

**Comment by isidorn** [comment] 2019-08-12 08:21
Can you reproduce this with all extension disabled?
If yes can you please provide a gif / picture showing the issue?

**Comment by ezfe** [comment] 2019-08-12 15:40
Here's a video:

https://www.youtube.com/watch?v=M8cTEjWf2Rs

Note that my recording software did not capture my pressing option, however when the mouse turned to the green (+) I was pressing option.

**Comment by mjbvz** [comment] 2020-10-15 00:51
Closing this due to low impact and lack of further user interest in this issue over the past year

**Closed by mjbvz** 2020-10-15 00:51 UTC
Labels: bug, confirmed
