### ISSUE TITLE
PHP snippets not working

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#113476] opened 2020-12-27 19:34 UTC
I'm running Code 1.52.1 and Code Insiders 1.53.0 on MacOS (Big Sur).

If I create a PHP snippet in `php.json` it doesn't appear when I then do **F1: Insert Snippet**

If I add the snippet to the global snippets file, it only appears if I remove the "scope" property.

Steps:

1. Install Code Insiders
2. F1: Preferences: Configure User Snippets 
3. Select PHP
4. Uncomment example snippet and save
![image](https://user-images.githubusercontent.com/376658/103178405-7f119200-487a-11eb-8321-227c853b7416.png)
5. Create a new file and set it's type to "PHP" from the activity bar
6. F1: Insert Snippet
![image](https://user-images.githubusercontent.com/376658/103178393-5db0a600-487a-11eb-88d9-4d233d5c1f64.png)

**Comment by jrieken** [comment] 2021-01-04 09:54
That's because an empty php file is classified as html. That's something the grammar decides 

<img width="988" alt="Screenshot 2021-01-04 at 10 53 18" src="https://user-images.githubusercontent.com/1794099/103522725-10849380-4e7b-11eb-8ede-0513f6b563ec.png">

**Comment by alexr00** [comment] 2021-01-05 10:29
@Gruntfuggly I think this is intentional on the part of the grammar. If you disagree that an empty PHP file shouldn't be classified as HTML, I recommend filing an issue over in https://github.com/atom/language-php

@jrieken this does seem a bit unexpected though. Would it make sense to have snippets look at the language the file is set to?

**Comment by Gruntfuggly** [comment] 2021-01-05 10:55
It's not a very nice user experience. I would expect to be able to define a template snippet for an empty PHP file and be able to insert it. An empty dropdown for something I've literally just added through the GUI makes it look broken.

Is there a work around?

**Comment by jrieken** [comment] 2021-01-05 12:40
> Is there a work around?

You can define a snippet for html and php files using "global" snippets (F1 > Configure Snippet > New Global Snippets)

**Comment by alexr00** [comment] 2021-01-05 14:05
@jrieken I still think that is confusing for users. The grammar will likely not change, as an empty php file is html. It isn't clear that you must also define your php snippet for html. Is it possible to have snippets consider the language of the file, and not just the language that the grammar says?

**Comment by jrieken** [comment] 2021-01-05 14:21
Unsure, wouldn't that enable html-snippets inside JS script tags? That's something we avoid by todays restriction. The grammar says "This part of the html file is JavaScript" and we pick JS snippets, not html snippets.

**Comment by KapitanOczywisty** [comment] 2021-01-07 12:29
@jrieken Is there a way to specify snippet per filename (grep)? Setting to `*.php` would solve this particular problem. And I'm guessing there are some uses when language is common, but filename is distinct. For example you may want to have some snippets for `*.d.ts` file to overwrite some module. Currently you can do that only with `.json` files using schemas.

**Comment by jrieken** [comment] 2021-01-07 12:41
@KapitanOczywisty that is tracked here: https://github.com/microsoft/vscode/issues/75955

**Comment by alexr00** [comment] 2021-01-07 15:29
Since both the grammar and the snippet are technically doing the right thing I will call this a duplicate of #75955.

**Closed by alexr00** 2021-01-07 15:29 UTC

**Comment by JLDesignNetwork** [comment] 2021-01-14 14:55
Hello, I have been following this post since it was created and honestly I am a bit confused here. This issue was created by @Gruntfuggly due to an issue I noticed with an autosnippet extension that he created. To be honest, the extension he created works fine, apart a newly created php file (which is empty, obviously). He provided a work around for me, but we both agree the issue is not the extension. The issue is here with vscode. So, I did some research to understand a bit more about the details of the php extension.  The reason for that research was because of something that was said here.

> @jrieken I still think that is confusing for users. The grammar will likely not change, as an empty php file is html. It isn't clear that you must also define your php snippet for html. Is it possible to have snippets consider the language of the file, and not just the language that the grammar says?

To be clear, from my research, an empty php file ***is not*** an html file. While it is true that php is an html embedded language, it is not html. I am providing links for reference. Additionally, every extension serves multiple purposes, one of those is to identify the syntax of the language used inside the file. 

By this reckoning any php file, empty or not, should be recognized as such. Just as an html file (empty or not) is recognized as html.

I also have another question concerning this issue in terms of the 'grammer'. 

> @Gruntfuggly I think this is intentional on the part of the grammar. If you disagree that an empty PHP file shouldn't be classified as HTML, I recommend filing an issue over in [atom/language-php](https://github.com/atom/language-php)

Why would it be necessary to raise an issue with atom? Is vscode and atom not separate entities? I am confused here because, I thought they were distinctly separate from each other. I admit that I haven't researched the code bases of the two programs.

**References**
[PHP.net](https://www.php.net/manual/en/faq.general.php#faq.general.what)
[Zend](https://www.zend.com/blog/php-development-using-php-extensions)

**Comment by alexr00** [comment] 2021-01-15 09:22
We are a relatively small team of developers so we can't be experts in all programing languages. Because of this, we get our grammars for syntax highlighting from the community. It just so happens that we get our PHP grammar from  https://github.com/atom/language-php

**Comment by KapitanOczywisty** [comment] 2021-01-15 09:38
Technically everything outside of php is treated as html so It's fair assumption that language of empty file is also html. No code outside `<?php` is executed by php. It could be named html-php or something, but still you would need to include `<?php` in suggestion for it to make sense.
