### ISSUE TITLE
Re-opening WebViewPanel with search box crashes VS Code

### ISSUE THREAD

**Issue by TobiasFaller** [microsoft/vscode#212544] opened 2024-05-12 13:14 UTC
Does this issue occur when all extensions are disabled?: Yes (Integrated markdown extension is affected by issue too)

Related Markdown extension bug:
- https://github.com/microsoft/vscode/issues/201478

- VS Code Version: Tested with 1.85.1 and 1.89.1
- OS Version: Windows 10 x64 22H2 (Build 19045.4291)

Steps to Reproduce:

1. Create a WebViewPanelwith the search widget enabled.
2. Search some text inside the WebViewPanel, don't close the search box.
3. Close the WebViewPanel.
4. Open another WebViewPanel.
5. VS Code Crashes with an Access Violation (0xc0000005).

---------------------------------------------------------------------------------------------

# Minimal working code to easily reproduce the issue (without Markdown extension):

1. Run the extension code.
2. Run the `sandbox.experiment1` command.
3. Search for a word inside the WebView (Ctrl + F, "Hello").
4. Close the WebView.
5. Run the `sandbox.experiment1` command again.
6. VS Code Crashes with an Access Violation (0xc0000005).

src/extension.ts
```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const commandExperiment1 = async(): Promise<void> => {
		const panel = vscode.window.createWebviewPanel('sandbox.experiment1', 'Experiment 1', vscode.ViewColumn.Active, {
			enableFindWidget: true
		});
		context.subscriptions.push(panel);
		panel.webview.html = 'Hello world';
	};
	context.subscriptions.push(vscode.commands.registerCommand('sandbox.experiment1', commandExperiment1, null));
}
```

package.json
```json
{
  "name": "sandbox",
  "displayName": "Sandbox",
  "description": "Sandbox",
  "version": "0.0.1",
  "publisher": "tobiasfaller",
  "author": "Tobias Faller",
  "icon": "images/icon.png",
  "repository": { },
  "engines": {
    "vscode": "^1.67.0"
  },
  "categories": [],
  "keywords": [],
  "main": "./out/extension.js",
  "contributes": {
    "commands": [
      {
        "title": "Experiment 1",
        "shortTitle": "Experiment 1",
        "category": "Sandbox",
        "command": "sandbox.experiment1",
        "icon": "play"
      }
    ]
  },
  "dependencies": {},
  "devDependencies": {
    "@types/node": "^18.11.18",
    "@types/vscode": "^1.74.0",
    "@typescript-eslint/eslint-plugin": "^5.48.0",
    "@typescript-eslint/parser": "^5.48.0",
    "eslint": "^8.31.0",
    "typescript": "^4.9.4"
  },
  "scripts": {
    "vscode:prepublish": "npm run compile",
    "compile": "tsc -p ./",
    "lint": "eslint . --ext .ts,.tsx",
    "watch": "tsc -watch -p ./"
  }
}
```

tsconfig.json
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2019",
		"lib": ["ES2019"],
		"outDir": "out",
		"sourceMap": true,
		"rootDir": "src",
		"strict": true
	},
	"exclude": ["node_modules", ".vscode-test"]
}
```

.vscode/launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Extension",
          "type": "extensionHost",
          "request": "launch",
          "args": [
              "--disable-extensions",
              "--extensionDevelopmentPath=${workspaceFolder}"
          ],
          "outFiles": [
              "${workspaceFolder}/out/**/*.js"
          ],
          "preLaunchTask": "npm: watch"
      }
  ]
}
```

**Comment by mjbvz** [comment] 2024-08-02 21:27
Duplicate of #177046

**Closed by mjbvz** 2024-08-02 21:27 UTC
