### ISSUE TITLE
Latex - Equation environment in markdown does not work

### ISSUE THREAD

**Issue by almhu** [microsoft/vscode#141905] opened 2022-01-30 13:45 UTC
The formula 

\begin{equation}
\begin{split}
a = b \\\\
c = c
\end{split}
\end{equation}

does not compile, but instead shows 

ParseError: Katex parse error: Expected & or \\ or \cr or \end at end of input: ...= c \end{split}

\end{equation}

In Jupyter Notebook, this works well. 

## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

**Comment by greazer** [comment] 2022-01-31 21:09
We believe this may be a regression after recent changes to the markdown renderer in core code.

**Comment by DonJayamanne** [comment] 2022-02-03 23:01
Also if you try the following cell, it will not work in VS Code 
& now that we use vscodes renderer `text/latext` this will no longer work (when it used to)

Hence marking as regression

```
%%latex
\begin{equation}
\begin{split}
a = b \\
c = c
\end{split}
\end{equation}
```

**Comment by mjbvz** [comment] 2022-02-04 00:03
@DonJayamanne  Any way we could have detected this earlier?

**Comment by mjbvz** [comment] 2022-02-04 00:10
Reopening to track shipping this in the recovery

Fix should already be in the next insiders build

**Comment by Lemmingh** [comment] 2022-02-04 15:36
@mjbvz

Jupyter actually does not count, and does not care whether the environments are nested. It just runs MathJax 2 in the browser, and looks for the nearest matching pair.

---

You can take this simple notebook with 3 cells as a test case.

```json
{"cells":[{"metadata":{},"cell_type":"markdown","source":"afi\n\\begin{pmatrix}\n\\begin{bmatrix}\n<a>\n\\end{bmatrix}\n\\end{pmatrix}\nafi"},{"metadata":{},"cell_type":"markdown","source":"afi\n\\begin{pmatrix}\\begin{bmatrix}<a>\\end{bmatrix}\\end{pmatrix}\nafi"},{"metadata":{},"cell_type":"markdown","source":"afi\n\\begin{pmatrix}\n\\begin{pmatrix}\n<a>\n\\end{pmatrix}\n\\end{pmatrix}\nafi"}],"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"},"language_info":{"name":"python","version":"3.6.15","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat":4,"nbformat_minor":2}
```

```text
afi
\begin{pmatrix}
\begin{bmatrix}
<a>
\end{bmatrix}
\end{pmatrix}
afi
```

```text
afi
\begin{pmatrix}\begin{bmatrix}<a>\end{bmatrix}\end{pmatrix}
afi
```

```text
afi
\begin{pmatrix}
\begin{pmatrix}
<a>
\end{pmatrix}
\end{pmatrix}
afi
```

**Comment by Lemmingh** [comment] 2022-02-04 17:25
**Jupyter indeed has a lot of quirks**, perhaps partially caused by [Marked](https://www.npmjs.com/package/marked).

---

It does not comply with CM's "block parsing first" strategy:

``````text
fi\begin{align}
a
```
\end{align}
```
``````

**is** an equation.

---

It does not allow blank line inside an equation:

``````text
\begin{align}
a

\end{align}
``````

is **not** an equation.

**Closed** 2022-02-09 22:27 UTC
Labels: bug, important, candidate, notebook-markdown, nb-golden, notebook-regression
