### ISSUE TITLE
Powershell starts instead of default terminal

### ISSUE THREAD

**Issue by jonasfeld** [microsoft/vscode#132454] opened 2021-09-06 12:13 UTC
Issue Type: <b>Bug</b>

I prefer to use git bash over Windows Powershell, so I've set Git Bash as the default. But lately (ever since 2 updates or so) Powershell still opens instead of my default terminal, which is git bash.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.39GB free)|
|Process Argv|--crash-reporter-id 1321def7-04db-4126-b24a-af9bd233c4c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
language-mcfunction|arc|0.18.0
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
jshint|dba|0.11.0
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
php-debug|fel|1.17.0
auto-close-tag|for|0.5.12
go|gol|0.27.2
ftp-simple|hum|0.7.6
latex-workshop|Jam|8.20.2
vsc-python-indent|Kev|1.14.2
kite|kit|0.147.0
flutter-intl|loc|1.16.0
syntax-project-pbxproj|mar|0.1.3
jvm-bytecode-viewer|mnx|0.3.1
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
color-highlight|nau|2.4.0
material-icon-theme|PKi|4.10.0
java|red|0.81.0
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
language-pde|Tob|1.4.6
latex-support|tor|3.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by Gliptal** [comment] 2021-09-06 12:44
Same issue.

**Comment by Jaid** [comment] 2021-09-06 12:47
Duplicate of:
https://github.com/microsoft/vscode/issues/132150

Likely to be addressed in the next recovery patch:
https://github.com/microsoft/vscode/issues/132426

**Closed** 2021-09-06 14:19 UTC
Labels: *duplicate
