### ISSUE TITLE
OSError: raw write() returned invalid length in integrated terminal

### ISSUE THREAD

**Issue by chendongbox** [Microsoft/vscode#39149] opened 2017-11-26 12:04 UTC
- VSCode Version:1.18.1
- OS Version:Windows 10 1709 update

Steps to Reproduce:
The problem is the probability of occurrence。
1. python 3.5.4
2. run python in vscode terminal.integrated.shell, such as "python aaa.py'
3. the problem only appear in vscode integrated terminal，no problem in windows cmd or powershell

Error like this：
OSError: raw write() returned invalid length 318 (should have been between 0 and 159)
OSError: raw write() returned invalid length 8 (should have been between 0 and  4)
OSError: raw write() returned invalid length 130(should have been between 0 and 65)
Please note： 318=159x2  8=4x2  130=65x2

Reproduces without extensions: Yes

**Comment by LlianeFR** [comment] 2017-11-27 08:28
Got the exact same issue since today, never before, so I think it might be related to a recent Windows 10 update. I have Version 1709 (OS Build 16299.64)

I thought it might be the returned value for unicode characters (double the normal length) ?

I can actually reproduce this bug in an external powershell.exe as well so this is not VSCode-related per se.

**Comment by jxskiss** [comment] 2017-11-27 17:36
Got this too with pycharm integrated console.
OS version 16299.64, did windows upgrade? I never got any notice about that.

**Comment by LlianeFR** [comment] 2017-12-07 14:49
I suggest to close this issue as it doesn't involve vscode, it seems to be between python and the console stdout stream. 

I've solved it by modifying this function in python's Modules/_io/bufferedio.c

In _bufferedwriter_raw_write 

Replaced

`if (n < 0 || n > len) {`

by

`if ((n < 0 || n > len) && n != len * 2) {`

It's very dirty and probably has side effects but it works for me...

**Comment by BronsonD** [comment] 2017-12-07 19:35
I am not sure if this may be related, but it just happened to me after many days of receiving the message in the thread. Today, I printed a pandas dataframe and the prompt appeared on the same line as the last row:

![image](https://user-images.githubusercontent.com/9971552/33734931-708f9a7a-db53-11e7-8d27-d4369934efd8.png)

**Closed** 2017-12-11 17:56 UTC
Labels: integrated-terminal

**Comment by pablocastilla** [comment] 2017-12-19 09:15
Hi!

I don't know if this helps, but I can isntall from cmd but not from VS code. I don't know if it is not a VSC problem.

Thanks

**Comment by arvindpdmn** [comment] 2018-01-10 09:52
Does this mean that we need to wait for next Windows update, which may or may not fix this issue?

**Comment by Tyriar** [comment] 2018-01-12 20:28
Yes you need to wait for the Windows update unfortunately, see https://github.com/Microsoft/vscode/issues/36630 for details.

@pablocastilla it's expected that this works fine in cmd.exe but not vscode due to the underlying mechanism vscode uses to communicate with the shell.

**Comment by Kilgore661** [comment] 2018-01-16 22:35
I have this problem when using cmd.exe (Python 3.4.4, Windows 10 - not sure how to be any more specific than that.)

**Comment by Tyriar** [comment] 2018-01-18 00:04
This issue is fixed but it's in Windows and needs time to roll out, see https://github.com/Microsoft/vscode/issues/36630
