### ISSUE TITLE
There is no Find text option in CSV preview

### ISSUE THREAD

**Issue by ksr11** [Microsoft/vscode#30471] opened 2017-07-12 07:33 UTC
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.install Excel preview plugin(Powered by Wijmo)
2. Click on preview button in right hand side while opening a csv file.
3. CSV file opens in Grid view fashion. But  press Ctrl+F button  
4. You can observe that Find dialog box never appear. 
Result is  could not able to scroll to right cell . 

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment] 2017-07-12 07:47
Likely duplicate of #2187 since I believe the CSV preview uses a webview. Also try filing an issue against the CSV extension to track this

**Closed by mjbvz** 2017-07-12 07:47 UTC
Labels: duplicate
