### ISSUE TITLE
Rename files in the editor 

### ISSUE THREAD

**Issue by sansentrailles** [microsoft/vscode#134779] opened 2021-10-11 08:03 UTC
Issue Type: <b>Bug</b>

The rename files in the editor do not work well. Often the file renaming is reset. 

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.29GB free)|
|Process Argv|. --crash-reporter-id 075aa21f-65d2-40fe-9e7a-ea2d211ce8da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
alignment|ann|0.3.0
vscode-color|ans|0.4.5
vscode-django|bat|1.6.0
django-html|bib|1.3.0
django|big|1.0.2
vscode-svgviewer|css|2.0.0
githistory|don|0.6.18
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.12.0
vscode-great-icons|emm|2.1.79
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
beautify|Hoo|1.5.0
vscode-gutter-preview|kis|0.27.1
git-indicators|lam|2.1.2
Arduino|moo|0.0.4
vscode-language-pack-ru|MS-|1.61.3
python|ms-|2021.10.1317843341
vscode-pylance|ms-|2021.10.0
jupyter|ms-|2021.9.1001312534
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
sublime-keybindings|ms-|4.0.10
color-highlight|nau|2.5.0
vetur|oct|0.34.1
indent-rainbow|ode|8.2.0
phpdoc-comment-vscode-plugin|rex|1.3.0
sass-indented|rob|1.5.1
rust|rus|0.7.8
vue-vscode-snippets|sdr|2.2.1
preview-vscode|sea|2.2.5
trailing-spaces|sha|0.3.1
php-formatter|Sop|0.2.4
Align|ste|0.2.0
vscode-djaneiro|the|1.4.2
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details>

**Comment by sansentrailles** [comment] 2021-10-11 17:36
> 
> 
> Could it be the case that files are being created/deleted from your working directory during the rename? There is an open issue for this.

No

**Comment by JacksonKearl** [comment] 2021-10-11 17:38
\gifPlease

**Comment by sansentrailles** [comment] 2021-10-15 09:44
![recording](https://user-images.githubusercontent.com/1174444/137467686-82a16a1f-0f6e-4d10-9850-bab6bc81f8b6.gif)

**Comment by JacksonKearl** [comment] 2022-01-11 19:17
@sansentrailles I believe this is a duplicate of #112293 which should be fixed in VS Code Insiders. Could you please try the latest insiders and see if you can reproduce the issue there?

**Closed** 2022-01-19 11:26 UTC
Labels: needs more info, file-explorer
