### ISSUE TITLE
Seti theme icons only show half of the icon

### ISSUE THREAD

**Issue by Monkey-1976** [Microsoft/vscode#17277] opened 2016-12-15 09:06 UTC
- VSCode Version: Code - Insiders 1.9.0-insider (89bdb7c35a89535612d386199ee33e6bd74ee068, 2016-12-15T07:11:14.563Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.4.2|
|tslint|eg2|0.7.1|
|restructuredtext|lextudio|0.0.19|
|gitignore|michelemelluso|1.0.1|
|cpptools|ms-vscode|0.9.3|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|vscode-docker|PeterJausovec|0.0.10|
|vscode-icons|robertohuertasm|4.1.0|
|yo|samverschueren|0.9.3|
|python|tht13|0.2.3|
|rst-vscode|tht13|1.3.0|

---

Steps to Reproduce:

1.  Load a project:

![seti_theme](https://cloud.githubusercontent.com/assets/13338401/21217729/9b943ae0-c2a5-11e6-84ba-7f17820eafcc.png)

**Comment by kieferrm** [comment] 2016-12-15 23:08
@Monkey-1976 do you see the same issue in an installation without the vscode-icons extension?

**Comment by Monkey-1976** [comment] 2016-12-16 10:09
yes I have uninstalled the vscode-icons extension and it is still the same.

**Comment by aeschli** [comment] 2016-12-29 03:18
duplicate of #17252,
I verified its fixed in the latest insider builds

**Closed by aeschli** 2016-12-29 03:18 UTC
