### ISSUE TITLE
Breakpoint line numbers don't update in UI when sending a `changed` BreakpointEvent (part deux)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#62264] opened 2018-10-31 10:48 UTC
This is a continuation of #59984. Some changes have been made in current Insiders, but I'm still having issues doing what I need.

cc @isidorn.

Until now, Dart has just always pretended that all breakpoints were always resolved (and potentially shown incorrect locations for breakpoints added to non-executable lines) so I'm trying to fix that by sending `BreakpointEvents`.

There are two possible scenarios:

1. When `setBreakPointsRequest` is called, my VM already has running threads and I can send the breakpoints, get the IDs and send them back as the response to `setBreakPointsRequest`
2. When `setBreakPointsRequest` is called, my VM does not have any threads, in which case I cannot send it any breakpoints yet, but I will do so as the threads spawn (in this case, I am unable to send breakpoints back with IDs in the response to `setBreakPointsRequest` and I am assuming it's ok to return an empty list)

This code simulates scenario 2. I send an empty list back in response to `setBreakPointsRequest` then later send a `new` breakpoint (when the VM accepts it) on line 13 and later again, a `changed` breakpoint (when the VM resolved it to a different location) to update it to line 14.

In order to ensure `setBreakPointsRequest` is called I have a breakpoint in the editor on line 13.

```ts
protected async setBreakPointsRequest(
	response: DebugProtocol.SetBreakpointsResponse,
	args: DebugProtocol.SetBreakpointsArguments,
): Promise<void> {

	setTimeout(() => {
		this.sendEvent(
			new BreakpointEvent("new",
				{
					column: undefined,
					id: 2,
					line: 13,
					source: new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart"),
					verified: false,
				} as DebugProtocol.Breakpoint,
			),
		);
	}, 2000);
	setTimeout(() => {
		this.sendEvent(
			new BreakpointEvent("changed",
				{
					column: undefined,
					id: 2,
					line: 14,
					source: new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart"),
					verified: true,
				} as DebugProtocol.Breakpoint,
			),
		);
	}, 4000);

	response.body = { breakpoints: [] };
	this.sendResponse(response);
}
```

After 4 seconds, I would expect the breakpoint to show line 14 in the editor, however it remains on line 13.

**Comment by isidorn** [comment] 2018-10-31 10:52
Thanks, not for endgame week, assigning to November so I investigate next week.

**Comment by DanTup** [comment] 2018-10-31 10:53
Ok, I found something interesting. If I put my breakpoint (the one in the editor to ensure `setBreakPointsRequest` is fired) on a *different line* then the new breakpoints work as expected.

So maybe there is some issue with sending a `new` breakpoint for a line that already had a breakpoint on it. I can't really just send `changed` though, as VS Code would be unable to match the breakpoints by ID.

I'm wondering what the intention is if I can't provide `id`s at the time that `setBreakPointsRequest` is called. Should I delay sending the response? Should I return an empty list?

**Comment by isidorn** [comment] 2018-11-09 15:37
Yes. So you can not send a `new` breakpoint on a line which already has a breakpoint that is not supported.
As a workaround you can send a `new` breakpoint on the same line, but which has a different `column`. So please try that.
If that does not work you can first remove the old breakpoitn with a `removed` event and than add it.

As for the corner case that you can not provide breakpoint `id`s for the response of the `setBreakpoints` call that is fine, you do not have to return `id` as they are optional. However for breakpoints that do not have ids we do not support the change event

As for the protocol I have created this item to clarify this https://github.com/Microsoft/debug-adapter-protocol/issues/15

Since there are no changes required on the vscode side I am closing this.

**Comment by DanTup** [comment] 2018-11-09 15:52
@isidorn In the code example above I'm returning an empty set from `setBreakPointsRequest` so I can create the breakpoint with a `new` event later, but still the `changed` event does not work.

**Comment by isidorn** [comment] 2018-11-09 16:06
Than I suggest you put a breakpoint [here](https://github.com/Microsoft/vscode/blob/e839e4560c19ce53c717d6f3078fd01e35c737a2/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L699) try to figure out what is the issue and provide a PR with a fix.
Unfortunetly I will not have time to look into this in November.

**Comment by DanTup** [comment] 2018-11-09 16:17
I did spend many hours debugging this between this and the other case, and provided code that easily reproduces the issue. I'm not sure I know enough about how this works to properly diagnose and fix the issue.

As something that seems to be a bug it seems a little unfair to suggest it's my responsibility to fix it and leave the issue closed ☹️

**Comment by DanTup** [comment] 2018-11-09 16:37
Thanks - I don't mind doing more debugging when I get a sec, I just don't know if I know enough to fix it myself (or at least, in a reasonable timeframe).

I'd take a stab at it being related to returning the empty list - because the breakpoint doesn't disappear for the two seconds between `setBreakPointsRequest` returning the empty list and my sending `new` two seconds later. It's possible this is expected (the empty array is ignored) but if that's deliberate, it makes it very difficult to correctly resolve breakpoints if you can't provide the ID at the time that `setBreakPointsRequest` is called (at least, without fabricating IDs and then maintaining my own mapping).

**Comment by DanTup** [comment] 2018-11-12 09:31
@isidorn I did more digging, and found that any breakpoints not returned from `setBreakPointsRequest` are just left as-is. This means if you return an empty (or partial) array, it does not remove the extra breakpoints.

I've come up with a workaround that seems to work and that is to send `removed` events for every breakpoint within `setBreakPointsRequest`. Is this supported?

```ts
protected async setBreakPointsRequest(
	response: DebugProtocol.SetBreakpointsResponse,
	args: DebugProtocol.SetBreakpointsArguments,
): Promise<void> {

	// Tell VS Code to remove all of the breakpoints because
	// we will re-create them with IDs later.
	args.breakpoints.forEach((b, i) => this.sendEvent(
		new BreakpointEvent("removed",
			{
				column: b.column,
				line: b.line,
				source: new Source(args.source.name, args.source.path),
			} as DebugProtocol.Breakpoint,
		),
	));

	response.body = { breakpoints: [] };
	this.sendResponse(response);

	// Send requests to VM that will result in new/changed events that have IDs later
}
```

And then if breakpoints are created later with IDs, they can be changed as required:

```ts
	// Later, create new breakpoints with IDs.
	setTimeout(() => {
		args.breakpoints.forEach((b, i) => this.sendEvent(
			new BreakpointEvent("new",
				{
					column: undefined,
					id: i,
					line: b.line,
					source: new Source(args.source.name, args.source.path),
					verified: false,
				} as DebugProtocol.Breakpoint,
			),
		));
	}, 2000);

	// Later still, resolve the breakpoints to new locations with their IDs.
	setTimeout(() => {
		args.breakpoints.forEach((b, i) => this.sendEvent(
			new BreakpointEvent("changed",
				{
					column: undefined,
					id: i,
					line: b.line + 1,
					source: new Source(args.source.name, args.source.path),
					verified: true,
				} as DebugProtocol.Breakpoint,
			),
		));
	}, 4000);
```

**Comment by DanTup** [comment] 2018-11-12 09:52
This solution isn't perfect, it has two issues:

- The breakpoints all flicker every time you add a new one (because they're removed and then immediately re-added)
- All resolved breakpoints show breakpoint indicators for the columns, even though the user added them as line-breakpoints

**Comment by isidorn** [comment] 2018-11-12 10:11
Ok, thanks for investigating. Here's some answers:
1. It is not supported to return less breakpoints in the breakpoints [response](https://github.com/Microsoft/vscode/blob/723ea47d62939f848a7cd133c888280e92156a06/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L480). You can not remove brekapoints like this. A reason for that is that the order has to be respected 
2. The brekapoints are shared between debug sessions, so Dart should not remove some breakpoints which the user set for C++ files. Dart should only make sure they are invalid, and they will properly be displayed in the UX
3. In theory you can send a removed event whenever you want, however the brekapoints response has to respect the order of the arguments recieved. So the best would be to send the removed after the response has been sent out

Is there anything else that needs to be done on the vscode side.
Everything here is behaving as designed imho

**Comment by DanTup** [comment] 2018-11-12 10:49
> The brekapoints are shared between debug sessions, so Dart should not remove some breakpoints which the user set for C++ files

Ok, so what should an extension do for breakpoints in `setBreakPointsRequest` that are not for its own source files? We have to return a `Breakpoint[]` but we were provided with a `SourceBreakpoint[]`. Are we supposed to map them? Or does it not matter, because the changes made by this request are scoped to the session (and only the new/changed/removed events are persisted?)

> In theory you can send a removed event whenever you want, however the brekapoints response has to respect the order of the arguments recieved. So the best would be to send the removed after the response has been sent out

Ok, so if in `setBreakPointsRequest` I map all the `SourceBreakpoints` to `BreakPoints` and just return them as-is and then send the `remove`s immediately after sending the response, that should all be fine and supported? If so, I think that'll solves my problems :-)

**Comment by isidorn** [comment] 2018-11-12 12:57
1. The changes you make will only be scoped to your session. So just return an array of breakpoints  and for those that are invalid for you return [`verified: false`](https://github.com/Microsoft/vscode/blob/723ea47d62939f848a7cd133c888280e92156a06/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1464) and everything else you should be able to leave out.
2. Yes, that should be fine.

Glad to hear that solves your problems. Since there is no work planned on my side. Closing this for now

**Closed by isidorn** 2018-11-12 12:57 UTC
Labels: *dev-question, debug
