### ISSUE TITLE
The code expands automatically

### ISSUE THREAD

**Issue by ali-sajed** [microsoft/vscode#151330] opened 2022-06-06 11:52 UTC
```
var_ = ()
if True:
    pass
if False:
    pass
if True:
    pass
....
```

If `var_ = ()` is mistakenly converted to `var_ = (` all subsequent ifs are expanded
And this is very annoying. Is there no way to prevent this from happening?

**Comment by aeschli** [comment] 2022-06-07 13:45
duplicate of https://github.com/microsoft/vscode/issues/137890

**Closed** 2022-06-08 12:55 UTC
