### ISSUE TITLE
Goto definition in hovers

### ISSUE THREAD

**Issue by sharedrory** [microsoft/vscode#132500] opened 2021-09-07 00:11 UTC
![image](https://user-images.githubusercontent.com/85806407/132266937-322410d6-f690-408e-ab82-923d30a3fc3d.png)

It would be nice to be able to click "SetStateAction" in the screenshot above and vscode treating it as if it was in an editor and someone held ctrl while clicking it or used the context menu to trigger the action.

Perhaps have a setting to enable such behavior. Additionally, another setting to make it default behaviour without holding the keybind for "gotoDefinition".

Obviously, I am not asking for recursive hovers for obvious reasons.

**Comment by mjbvz** [comment] 2021-09-15 23:41
Duplicate of #64566

**Closed by mjbvz** 2021-09-15 23:41 UTC

**Comment by sharedrory** [comment] 2021-09-16 00:03
It's not a duplicate but it is related to it.
