### ISSUE TITLE
[Extension] Allow users to use custom icons over sets?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#25070] opened 2017-04-20 08:09 UTC
Hi there,

I’ve published an icon set (https://marketplace.visualstudio.com/items?itemName=emmanuelbeziat.vscode-great-icons). I had a feature request by a user: https://github.com/EmmanuelBeziat/vscode-great-icons/issues/46

Basically, he asks me if it would be possible for him to define custom icons that would override my list. I’m giving it a real thought, because I think it would be a great improvement.

I now that it wouldn’t be possible to just define some custom file and folder, as the update process of vscode is to remove the old extension folder and create a new one.

I don’t see if there’s a way to use (contributes.configuration)[https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration] and define custom files for some icons, and then kindda "import" theses adds in my script? At this point, I’m just wondering if this is possible in any way or not.

The user suggested this:

> I guess another option is to have a piece of code that runs offline to merge the new and old versions. Is there any way to run code on installation, ala Squirrel? 

I need confirmation about this, ’cause I didn’t find anything relevant on the doc: is this possible to run a script before the installation / update of a plugin?

Thanks for your thoughts :)

**Comment by aeschli** [comment] 2017-04-25 21:10
Extending or customizing an icon theme is currently not possible.
duplicate of #14662 or #11556

**Closed by aeschli** 2017-04-25 21:10 UTC
