### ISSUE TITLE
FileSystemProvider Does Not Update Open Tabs

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#81776] opened 2019-10-01 17:07 UTC
I'm reporting a couple of issues with how FileSystemProvider interacts with open tabs.

Steps to Reproduce:

1. Create a FileSystemProvider.
2. Open a file from the FileSystemProvider.
3. Have the FileSystemProvider delete the open file (without user interaction). Tab will have the `(deleted)` prefix.
4. Have the FileSystemProvider add a new file with the same name as the deleted file (again, without user interaction). `(deleted)` prefix will disappear. 

(Bug 1)
**EXPECTED**:
FileSystemProvider's `readFile` should be called and the contents of the open tab should be replaced with what it returns.

**ACTUAL**:
`readFile` is not called. Tab contents are what they were when the file was first deleted. 

I can force a call to `readFile` by saving the file.

(Bug 2)
**EXPECTED**
Contents of open tab should be replaced with what is returned by `readFile`

**ACTUAL**
Tab contents are what they were when the file was first deleted. *Sometimes* the contents of the tab will be replaced by the result of `readFile` if the tab is closed and reopened (see GIF). 

Here's a GIF demonstrating what a user would see. What's going on behind the scenes is described in the repro steps. After the FileSystemProvider readds the deleted file, `readFile` is returning `""`.

![FileSystemProviderRepro](https://user-images.githubusercontent.com/6383490/65983696-fc114a00-e432-11e9-9249-f71327986fdc.gif)

**Comment by daytonellwanger** [comment] 2019-10-01 17:07
@jrieken I think you're the one who worked on the `FileSystemProvider` APIs.

**Comment by bpasero** [comment] 2019-10-02 15:39
@daytonellwanger can you attach a minimal extension sample code for me to reproduce?

**Comment by bpasero** [comment] 2019-10-02 15:47
@daytonellwanger I cannot reproduce this, here is what I do:
* setup mem-fs sample extension (as outlined in https://github.com/microsoft/vscode/issues/78961#issue-479692308)
* create file again

=> content is updated
* open file.txt
* pick the command to delete file.txt
* file shows deleted
*

**Comment by daytonellwanger** [comment] 2019-10-03 17:42
Hey @bpasero , here's a modified version of the mem-fs sample extension that repros the issue. The modifications are removing any updates to `ctime` or `mtime` on the `FileStat` 😁... which pointed me towards the issue with my implementation of `FileSystemProvider` - I did not understand that `readFile` would be conditionally called based on the results of `stat`. So this looks like an issue with me not understanding the API, not the API itself.

GIF of behavior:
![memfsrepro](https://user-images.githubusercontent.com/6383490/66150400-f863fb80-e5c9-11e9-8c00-4f56f6fc550d.gif)
[sample.zip](https://github.com/microsoft/vscode/files/3687348/sample.zip)

**Comment by daytonellwanger** [comment] 2019-10-03 17:46
Note that this issue repros with the mem-fs sample extension (without modification) *if the tab is dirty*. Is that expected? I would have expected the contents of the document to be updated.

![dirtyrepro](https://user-images.githubusercontent.com/6383490/66150867-f5b5d600-e5ca-11e9-8262-62b1e3babf5f.gif)

**Comment by bpasero** [comment] 2019-10-04 05:18
Ok closing then. Yes, if the tab is dirty we do not overwrite its contents because that would mean we loose user typed data.

**Closed by bpasero** 2019-10-04 05:18 UTC
Labels: needs more info
