### ISSUE TITLE
delete one file and show a warming dialog

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#125890] opened 2021-06-10 02:32 UTC
Issue Type: <b>Bug</b>

select one file， then delete it, then show a dialog 

VS Code version: Code - Insiders 1.57.0-insider (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T11:49:36.076Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.73GB free)|
|Process Argv|--crash-reporter-id 6ae11958-32b1-4bba-81c7-213f3a2fe192|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by heartacker** [comment] 2021-06-10 02:34
![image](https://user-images.githubusercontent.com/1876302/121455671-756a8980-c9d7-11eb-8baa-7bf4bac1433f.png)

**Comment by isidorn** [comment] 2021-06-10 07:17
@heartacker can you please ask you to start putting a bit more effort when filling bugs?
From the description above I do not know what is the problem, or what would you like to change.
Please provide more details in a concise way. Can you reproduce with vscode insiders?

**Comment by heartacker** [comment] 2021-06-10 07:53
delete a file, then file is deleted, but show a warming dialog.(even disable all exts )

![delete1_disable_all_exts](https://user-images.githubusercontent.com/1876302/121486348-a365c300-ca03-11eb-9e7f-cc8b9e8a80ca.gif)


i believe that this issue related with https://github.com/microsoft/vscode/issues/125464

**Comment by heartacker** [comment] 2021-06-10 08:28
I install the insider to another win7 pc, and I can't reproduce this issues. So what should I do?

**Comment by isidorn** [comment] 2021-06-10 10:35
Then this is caused by an extension you have probably. I suggest to do extension bisect and determine what extension that is.
Closing this for now

**Closed by isidorn** 2021-06-10 10:35 UTC
Labels: file-explorer, needs more info
