### ISSUE TITLE
Markdown preview doesn't word wrap

### ISSUE THREAD

**Issue by bohenderson** [Microsoft/vscode#17212] opened 2016-12-14 23:31 UTC
- VSCode Version: 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d)
- OS Version: Ubuntu 14.04.5 LTS

Steps to Reproduce:

1. Open a file.md
2. Open the preview w `ctrl+k v`
3. No word wrap.. let's try toggling word wrap w `ctrl-z` or `alt-v w`
4. Still no word wrap

This problem is present in the release notes too ie `f1 s r n enter`

**Comment by mjbvz** [comment] 2016-12-14 23:32
Closing as a duplicate of #15921

**Closed by mjbvz** 2016-12-14 23:32 UTC
Labels: duplicate, markdown
