### ISSUE TITLE
When I start Visual Studio Code by using command,it will open a command line window and can't automatically close

### ISSUE THREAD

**Issue by ChaosGod** [Microsoft/vscode#8907] opened 2016-07-08 07:27 UTC
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.3.9600

When I start Visual Studio Code by using command,it will open a command line window and can't automatically close

Steps to Reproduce:
1.win+r ,enter words "code"
2.the visual studio will start and a command line window will open at the same time.
3.After a period of time,the command line window is still opened..

**Comment by joaomoreno** [comment] 2016-07-08 08:41
Duplicate of #1499

**Closed by joaomoreno** 2016-07-08 08:41 UTC
