### ISSUE TITLE
C++ Syntax Highlighting not handling multi-lines macros properly

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#11921] opened 2016-09-13 02:24 UTC
- VSCode Version: 1.5.2
- OS Version: 10.11.6, Linux ubuntu 16.04

Have some C++ with macros defined on multiple lines:

like:

```
#define INIT_WATCHABLE(name, val) \
 name(val, "MediaDecoderStateMachine::" #name)
#define INIT_MIRROR(name, val) \
  name(mTaskQueue, val, "MediaDecoderStateMachine::" #name " (Mirror)")
#define INIT_CANONICAL(name, val) \
  name(mTaskQueue, val, "MediaDecoderStateMachine::" #name " (Canonical)")

class MediaDecoder;

```

Note that class MediaDecoder; is showed as entirely blue.

The next line will be okay if you have another forward declaration.

But with more complex code it will look like so:
<img width="811" alt="screen shot 2016-09-13 at 12 22 40 pm" src="https://cloud.githubusercontent.com/assets/505748/18459439/ce55a852-79ac-11e6-91df-bdfd3a6bbff0.png">

If you rewrite the macro to be on a single line, so that \ isn't needed, then syntax highlighting will appear okay.

**Comment by djg** [comment] 2016-09-13 02:32
I think this is a dupe of issue #11335 which lead to atom/language-c#160 being created.
Removing the \ from INIT_CANONICAL fixes the highlighting.

**Comment by jyavenard** [comment] 2016-09-13 02:36
I can reproduce the issue with those 7 lines of code above...

should the issue be lodged against vscode-cpptools ?

**Comment by bpasero** [comment] 2016-09-13 10:43
Yes it should.

**Closed by bpasero** 2016-09-13 10:43 UTC
