### ISSUE TITLE
The process is taking a long time when merging other branches using source control

### ISSUE THREAD

**Issue by wangyc-pers** [microsoft/vscode#225210] opened 2024-08-09 02:54 UTC
Type: <b>Performance Issue</b>

1. Click Source Control -> Merge.
2. Select a branch to merge. 

It now takes about 10 seconds to complete the merge process. Previously, following the same steps, it would finish much faster. I noticed this issue started occurring after a recent update.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 6.8.12-3-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7735HS with Radeon Graphics (16 x 2045)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|27.10GB (16.30GB free)|
|Process Argv|--crash-reporter-id 2ee338e1-0492-40b8-b355-ccf2650b7b07|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   250	 57008	code main
    0	    28	 57011	   zygote
    0	   222	 57045	     gpu-process
    0	    28	 57012	   zygote
    0	     0	 57014	     zygote
    0	   805	 57116	window [1] (budget_fee_service.py - oa-server - Visual Studio Code)
    0	    83	 80702	window [2] (Issue Reporter)
    0	    55	 57052	   utility-network-service
    0	   777	 57135	extensionHost [1]
    0	     0	 57213	     /home/sam/.vscode/extensions/ms-python.python-2024.12.2-linux-x64/python-env-tools/bin/pet server
    0	   166	 57371	     electron-nodejs (server.js )
    0	    55	 58191	     electron-nodejs (eslintServer.js )
    0	    55	 58225	     /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=57135
    0	   721	 58240	     electron-nodejs (bundle.js )
    0	   111	 57150	shared-process
    0	     0	 80751	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    83	 57151	fileWatcher [1]
    0	    83	 57193	ptyHost
    0	     0	 57427	     /usr/bin/zsh -i
    0	     0	 58233	     /usr/bin/zsh -i
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (budget_fee_service.py - oa-server - Visual Studio Code)
|    Folder (oa-server): 3641 files
|      File types: py(1746) pyc(1232) xlsx(258) md(67) log(49) html(13)
|                  xls(12) ttf(6) png(4) pptx(3)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
vscode-css-formatter|aes|1.0.2
sourcetrail|ast|0.0.2
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.1
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
dart-code|Dar|3.94.0
flutter|Dar|3.94.0
vscode-eslint|dba|3.0.10
pep8-asm|dea|0.0.1
rust-syntax|dus|0.6.1
gitlens|eam|2024.8.805
dependi|fil|0.7.7
linter|fna|0.0.19
codespaces|Git|1.17.2
copilot|Git|1.221.1038
copilot-chat|Git|0.18.1
go|gol|0.42.0
vscode-drawio|hed|1.6.6
better-cpp-syntax|jef|1.27.1
vscode-mathpix-markdown|mat|0.1.8
vscode-docker|ms-|1.29.1
vscode-language-pack-zh-hans|MS-|1.92.2024080709
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.18.44
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
sftp|Nat|1.16.3
material-icon-theme|PKi|5.8.0
java|red|1.33.0
rust-analyzer|rus|0.3.2062
svg-preview|Sim|2.8.3
ayu|tea|1.0.5
rst-vscode|tht|3.0.1
pdf|tom|1.2.2
vscode-pets|ton|1.27.0
cmake|twx|0.0.17
vscode-counter|uct|3.5.0
vscode-mdx|uni|1.8.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.28.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
volar|Vue|2.0.10
vscode-mdx-preview|xyc|0.3.3
vue|znc|0.12.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by albertosantini** [comment] 2024-08-09 07:30
If you use `git` from command line, and not VSCode, have you the same results in terms of performance?

**Comment by kodcuserkan** [comment] 2024-08-09 08:08
Same here using Mac with M2 Processor 
![Screenshot 2024-08-09 at 10 38 50](https://github.com/user-attachments/assets/93b3d3cb-2c11-4c53-81bd-78276bf8133f)

**Comment by wangyc-pers** [comment] 2024-08-09 09:32
> If you use `git` from command line, and not VSCode, have you the same results in terms of performance?

When performing a merge using Git commands, the speed is very fast. I noticed that a recent update added a commit graph in the Source Control section, and I'm not sure if this is causing the issue.
![image](https://github.com/user-attachments/assets/b77278ee-7fec-4e01-8290-6f10f48bedd5)

**Comment by wangyc-pers** [comment] 2024-08-09 09:43
setting "scm.showHistoryGraph": false can fix this problem

**Comment by albertosantini** [comment] 2024-08-09 09:47
https://github.com/microsoft/vscode/issues/225227

**Comment by lszomoru** [comment] 2024-08-19 15:01
Closing as duplicate of https://github.com/microsoft/vscode/issues/224646

**Closed by lszomoru** 2024-08-19 15:01 UTC
