### ISSUE TITLE
White space above the title when maximized on a portrait monitor

### ISSUE THREAD

**Issue by dcatcher9** [microsoft/vscode#93044] opened 2020-03-19 20:15 UTC
Issue Type: <b>Bug</b>

Setup a monitor in portait ( vertical ) mode

Maximize vs code. There is a white space above the title. Looks bad.

Not related to extensions.

Screenshot
https://ibb.co/BKzgBKF

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (24.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.0
beautify|Hoo|1.5.0
python|ms-|2020.2.64397
partial-diff|ryu|1.4.1
vscode-icons|vsc|10.0.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment] 2020-03-19 20:28
Probably duplicate of #85655

**Comment by deepak1556** [comment] 2020-04-17 20:54
Thanks @IllusionMH , I am merging this to https://github.com/microsoft/vscode/issues/85655

**Closed by deepak1556** 2020-04-17 20:54 UTC
