### ISSUE TITLE
Recommended extensions page is overflowd bottom

### ISSUE THREAD

**Issue by MeglSiki** [microsoft/vscode#84964] opened 2019-11-16 11:55 UTC
- VSCode Version: 1.40.1
- OS Version: Windows 10 pro

Steps to Reproduce:

1. Select and open recommended extensions page.

Recommended extension page is overflowed bottom.
Overflowed height looks recommendation message's height.

Does this issue occur when all extensions are disabled?: Yes

- Normal extension page bottom.
![vscode-extension](https://user-images.githubusercontent.com/32983605/68992736-a265c180-08b2-11ea-8f01-c1b7133e0174.png)

- Recommended extension page bottom.
![vsccode-recommended-extension](https://user-images.githubusercontent.com/32983605/68992733-882be380-08b2-11ea-8a81-c250d04636e7.png)

**Comment by sandy081** [comment] 2019-11-18 08:10
Does it happens with all tabs on the extension page? Like open Contributions tab and see if it overflows too?

**Comment by MeglSiki** [comment] 2019-11-18 16:30
Page height fixed when I change tab to Contributions/Changelog.
The height did not overflow when I back details tab.
But close and reopen recommended extension page, height overflows again.

**Comment by sandy081** [comment] 2019-11-19 15:26
Seems related to markdown preview editor

**Comment by mjbvz** [comment] 2019-11-19 21:49
Duplicate of #83209

**Closed by mjbvz** 2019-11-19 21:49 UTC
