### ISSUE TITLE
Chinese characters not displayed properly in the output window

### ISSUE THREAD

**Issue by yun738243875** [Microsoft/vscode#36102] opened 2017-10-12 00:57 UTC
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
csharp|ms-|1.12.1
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.15.0

c# .net core 编译时输出窗口，中文乱码

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment] 2017-10-12 13:10
Translation: Compile the output window, the Chinese garbled

@yun738243875 can you please add a screenshot that illustrates the problem.

**Comment by isidorn** [comment] 2017-10-16 07:55
Duplicate of https://github.com/Microsoft/vscode/issues/3550 and https://github.com/Microsoft/vscode/issues/974

**Closed by isidorn** 2017-10-16 07:55 UTC
