### ISSUE TITLE
New cell doesn't show up in diff view

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#105959] opened 2020-09-02 17:27 UTC
Testing #105770

Open a notebook file and insert a cell in between two cells and save, and open diff view. The last cell does not show up in the right side of the diff view (even if I make a change in the last cell). 

![recording (9)](https://user-images.githubusercontent.com/9721254/92016218-05c8bf00-ed20-11ea-9a68-c7857a49c259.gif)

**Comment by rebornix** [comment] 2020-09-02 21:42
/duplicate of https://github.com/microsoft/vscode/issues/105778

**Comment by rebornix** [comment] 2020-09-11 18:00
Regressed when doing the text model / editing refactoring, now fixed again with via 59dcc5c9124ad82d15adc888013b2a861405d794

**Closed** 2020-09-11 17:59 UTC
Labels: *duplicate
