### ISSUE TITLE
Autocomplete (intellisense) suggestions - lower priority for code snippets

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#9122] opened 2016-07-12 11:42 UTC
- VSCode Version:1.3.0
- OS Version: Win10

Some code snippets are very usefull but extremly annoying at the same time.

In some cases, code snippets take precedence over class members, see this .tsx file for example:

<img src="http://i.imgur.com/sxd7fa2.gif" alt="http://i.imgur.com/sxd7fa2"
 />

another example is conflict between new keyword and new code snippet:
<img src="http://imgur.com/lvgXy2x.gif" alt="http://i.imgur.com/sxd7fa2"
 />

it makes intellisense quite annoying

**Comment by aeschli** [comment] 2016-07-12 16:06
@jrieken Joh, not sure why you assigned this to me.

**Comment by zeyangl** [comment] 2016-07-13 10:37
This is indeed a problem for me as well. Would really love it get this fixed.

**Comment by jrieken** [comment] 2016-07-14 15:13
closing as duplicate of #9286 which is the bucket issue for this

**Closed by jrieken** 2016-07-14 15:13 UTC
Labels: duplicate
