### ISSUE TITLE
Code helper is consuming large amount of memory

### ISSUE THREAD

**Issue by tusharnaresh** [microsoft/vscode#233329] opened 2024-11-07 13:31 UTC
Type: <b>Bug</b>

I am not sure how to repoduce.

VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|21, 16, 9|
|Memory (System)|24.00GB (2.42GB free)|
|Process Argv|--crash-reporter-id 399cfa37-14ab-40a6-b8b3-b614299398b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.13.46
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.74
copilot|Git|1.243.0
copilot-chat|Git|0.22.1
vscode-pull-request-github|Git|0.101.2024110504
playwright|ms-|1.1.11
vscode-speech|ms-|0.12.1
vsliveshare|ms-|1.0.5941
color-highlight|nau|2.8.0
vscode-yaml|red|1.15.0
react-redux-es6-snippets|tim|2.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by tusharnaresh** [comment] 2024-11-07 13:32
![Image](https://github.com/user-attachments/assets/a98a7458-cc6b-43c4-a7de-e73c7d98b151)

**Comment by mjbvz** [comment] 2024-11-07 21:38
Looks like cpu instead of memory?

Seems like a duplicate of #232699

**Closed by mjbvz** 2024-11-07 21:38 UTC
