### ISSUE TITLE
Unable to reach error message in tsconfig

### ISSUE THREAD

**Issue by michaelmaillot** [Microsoft/vscode#72048] opened 2019-04-10 07:21 UTC
- VSCode Version: 1.32.3
- OS Version: Windows 10 (1809)

Steps to Reproduce:

1. Launch VSCode with a tsconfig
2. Set a path that doesn't exists in tsconfig.json
3. Point out the underlined cursor position

![vscode_tsconfig](https://user-images.githubusercontent.com/44271458/55859108-a473df00-5b71-11e9-9f54-7199e52e3c1e.png)

As the error occurs in top of selection, the message is displayed in bottom instead of under the cursor. But it can be reached if shrinked.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment] 2019-04-10 18:16
Please test using VS Code 1.33

**Comment by michaelmaillot** [comment] 2019-04-19 08:39
I've updated VSCode to the 1.33.1 version. The error message doesn't display anymore, it occurs only on the building step. Could we consider this as "corrected" though ?

**Comment by mjbvz** [comment] 2019-04-19 23:37
Duplicate of #69880

**Closed by mjbvz** 2019-04-19 23:37 UTC
Labels: editor-contrib, needs more info
