### ISSUE TITLE
Repl doesn't scroll all the way down

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9886] opened 2016-07-28 09:24 UTC
- Type in an expression which resolves to a big object

Repl doesn't scroll all the way down.

![image](https://cloud.githubusercontent.com/assets/22350/17207651/cc9e756e-54b5-11e6-8248-b128ddbd9e30.png)

**Comment by isidorn** [comment] 2016-07-28 11:44
As designed https://github.com/Microsoft/vscode/issues/6343
If you disagree please comment on that issue

**Comment by joaomoreno** [comment] 2016-07-28 12:41
Please always reveal the *last* possible thing instead of placing the first line of the last expression aligned to the top...

![facepalm](https://m.popkey.co/f2cf5d/o0eL.gif)

**Comment by isidorn** [comment] 2016-07-28 14:40
But how would I know what is the last possible thing to reveal? I would have to measure how much space there is (in this case the last possible thing would be `HttpVersionMinor`)

**Comment by joaomoreno** [comment] 2016-07-28 14:51
`tree.setScrollPosition(1)`

**Comment by isidorn** [comment] 2016-08-24 14:04
`tree.setScrollPosition(1)` will always scroll to the very end.
I personally prefer the current behavior where the expanded element is always shown since if we always scroll to the last element the user might find this too sudden.
@weinand opinion?

**Comment by joaomoreno** [comment] 2016-08-24 14:15
Why do you even expand it actually? Have you considered doing what Chrome does?

![image](https://cloud.githubusercontent.com/assets/22350/17933851/f4f1ce4c-6a15-11e6-874e-d02df17f3bb1.png)

**Comment by weinand** [comment] 2016-08-24 14:18
Yes, not expanding would work for me.

**Comment by isidorn** [comment] 2016-08-24 14:18
That was the original behavior but some users asked for the expansion and I found it neat.

Then let me go back to not auto-expanding.

**Comment by isidorn** [comment] 2016-08-24 14:19
Here's the user request btw https://github.com/Microsoft/vscode/issues/6019

**Comment by joaomoreno** [comment] 2016-08-24 14:43
Isidor, it's not just _not expanding_. Chrome shows a few keys/values in the collapsed state. I wouldn't change it without that, do we have it?

**Comment by isidorn** [comment] 2016-08-24 14:48
No we do not have that, that is the value of the object that is coming from the adapter. Theoretically each adapter could add this snippet to the value so vscode would not need to handle this. Another option is that vscode internally expands the object and generates this snippet

**Comment by isidorn** [comment] 2016-08-26 14:58
@weinand what you think about @joaomoreno suggestion to do this computation on the vscode side? I can do it, but we have not done things like this on the vscode side so far, so I am a bit relucatant to add it.
We can also go back to auto-expanding, though I must admit I like chrome's feature.

**Comment by joaomoreno** [comment] 2016-08-29 07:47
Regardless, not expanding without a summary is a step back. So don't keep it the current way.

**Comment by isidorn** [comment] 2016-08-29 12:52
Went back to the previous behavior. Moving this to the backlog until we decide if we want to show a preview for each object.

**Comment by joaomoreno** [comment] 2016-08-29 12:54
It's also not about _if_... I think we can all agree that showing a preview is better than not showing one, in a collapsed state.

**Comment by weinand** [comment] 2016-08-29 13:51
The variableRequest already has the notion of a 'preview' for structured objects: it is the `value`attribute. And this value is already used in the REPL (and in the Variables view).
The only thing that is missing is that debug adapters return more info than just 'Object' or 'Array[5]'.

I suggest that we switch to the non-auto-expand behaviour now. We cannot wait until all debug adapters have improved their preview.

**Comment by joaomoreno** [comment] 2016-08-30 09:05
The same fix would improve the hover experience too:

![image](https://cloud.githubusercontent.com/assets/22350/18083044/a3fd7316-6ea1-11e6-9380-95afa8e73712.png)

Seeing `e` in there is annoying, I'd like to see a summary of the properties of both `_start` and `_end`.

**Comment by isidorn** [comment] 2016-10-24 13:08
This should be fixed in the latest. We also do not auto expand anymore

**Closed by isidorn** 2016-10-24 13:08 UTC
Labels: bug
