### ISSUE TITLE
X11/Org VSC follow WayLand system theme but WayLand VSC don't follow WayLand system theme

### ISSUE THREAD

**Issue by bphd** [microsoft/vscode#190423] opened 2023-08-14 15:44 UTC
Such irony

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by guyluz11** [comment] 2023-08-14 17:56
@bphd can you add images?

**Comment by bphd** [comment] 2023-08-14 18:14
Of what? A white themed VScode over a black DE? The contrary? The parameters where "Preferred Dark/High Contrast/Light Color Theme" "Auto Detect Color Scheme" are correctly set?

**Comment by daviddossett** [comment] 2023-08-21 16:07
Sorry, I don't understand what this means. Can you describe the issue in more detail?

**Comment by bphd** [comment] 2023-08-21 16:34
Of course, I'd be happy to elaborate. Let's break down the issue with X11/Org VSC (Visual Studio Code) following the Wayland system theme while Wayland VSC doesn't seem to adhere to the same principle.

X11 and Wayland are two different display protocols used in Linux environments. X11 has been around for a long time and has traditionally been the standard for graphical environments in Linux. However, Wayland is a more modern and efficient protocol that aims to address some of the limitations and security concerns of X11.

When you mention X11/Org VSC following the Wayland system theme, it means that when you're using Visual Studio Code on an X11 display server (which is often the case in traditional Linux setups), the appearance of VS Code matches the system-wide theme. This consistency is usually achieved through the cooperation of the X11 server, the desktop environment's theme settings, and the application (VS Code in this case) respecting those settings.

On the other hand, you're observing that Wayland VSC doesn't follow the Wayland system theme. This could indicate that when you run VS Code on a Wayland display server, it doesn't automatically adapt its appearance to match the system-wide theme as X11/Org VSC does on X11.

The "Preferred Dark/High Contrast/Light Color Theme" and "Auto Detect Color Scheme" parameters you mentioned are likely settings within Visual Studio Code that control how the application's appearance is determined. For instance, "Preferred Dark" might indicate that you prefer a dark theme for VS Code, while "Auto Detect Color Scheme" might mean that VS Code should try to automatically match the color scheme based on the system settings.

The irony in this situation lies in the fact that Wayland, being a more advanced and modern display protocol, might be expected to provide a more seamless and consistent experience across applications. However, if VS Code doesn't properly adapt to the system theme on Wayland, it can feel counterintuitive and somewhat contradictory.

To troubleshoot the issue further, you might want to explore VS Code's settings related to appearance and theming. You could also check if there are any known compatibility issues between VS Code and Wayland, or if there are updates or plugins that could help resolve this inconsistency.

Remember that the landscape of Linux display servers and graphical applications can be complex and may involve interactions between multiple components, including the display protocol, desktop environment, and individual application settings.

**Comment by daviddossett** [comment] 2023-08-21 17:05
I'm not familiar with Linux-related issues, but it sounds like the general issue is that VS Code isn't responding to the system theme in that environment. Adding @aeschli who may be able to help here.

**Comment by aeschli** [comment] 2023-08-23 13:33
We are relying on Electron API to listen to OS color scheme changes.

Is this a duplicate of https://github.com/electron/electron/issues/38684?

Can you give more information on how I get a `Wayland version of VSC`?

**Comment by bphd** [comment] 2023-08-23 13:36
--enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --unity-launch %F

**Closed** 2023-09-01 14:22 UTC
Labels: info-needed
