### ISSUE TITLE
Webview dev  tools can no longer load source maps

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#115440] opened 2021-01-29 23:00 UTC
- OS Version: Windows
- VSCode Version:
![image](https://user-images.githubusercontent.com/55927613/106335855-85ce6300-6285-11eb-956f-8c8f2ae26eef.png)

Steps to Reproduce:

1 - have a project with source map available and open the developer tools

![image](https://user-images.githubusercontent.com/55927613/106335837-7b13ce00-6285-11eb-973a-b426b07d04ed.png)

This problem started today randomly. I did not change anything from my building scripts, webpack or dev dependencies.

Source maps are enabled
![image](https://user-images.githubusercontent.com/55927613/106335939-b7472e80-6285-11eb-9071-398fae8f4042.png)

How did that happen? My vscode has not even updated.

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment] 2021-01-30 01:45
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by AllanOricil** [comment] 2021-02-01 09:04
@mjbvz my bad, source maps were never loaded inside the webview devtools.
But it would be nice if I could see them there. Is it possible?

**Comment by mjbvz** [comment] 2021-02-12 21:50
This electron issue tracks the root cause: https://github.com/electron/electron/issues/21699

On VS Code desktop, we load all resources inside of webviews using a custom protocol (`vscode-webview-resource`) and it looks like source maps currently do not support these protocols. There's nothing we can do on our side to work around this, so closing it as an upstream issue. Hopefully once that is fixed and VS Code picks up a new electron version, source maps will just work inside of webviews

**Closed by mjbvz** 2021-02-12 21:50 UTC
Labels: electron, needs more info, upstream-issue-linked, webview
