### ISSUE TITLE
debug hover's maximum size is too small 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#106865] opened 2020-09-16 14:49 UTC
debug hover is too small and doesn't allow for horizontal scrolling:

<img width="720" alt="2020-09-16_16-45-35" src="https://user-images.githubusercontent.com/1898161/93353427-34748880-f83c-11ea-9218-917c5830c507.png">

The hover window must adapt its size to the data that needs to be shown (within some limits).
If the size would exceed the limits, scrolling needs to be possible.

**Comment by weinand** [comment] 2020-09-16 14:54
I take it back: scrolling is possible. 
But the default maximum size of the hover is just too tiny.

**Comment by isidorn** [comment] 2020-09-16 15:55
What a coincidence just today I have assigned this bug to September with the idea to investigate furhter
Due to that closign this as duplicate of https://github.com/microsoft/vscode/issues/43326

Idealy the hover should be resizable

**Comment by weinand** [comment] 2020-09-16 17:49
@isidorn  I only agree, if you mean "automatic resizability". Manual resizability is just clumsy.

I don't want to resize hovers manually just to see the end of string.
If there is enough space on my screen to fully show the string in the hover, why should I resize the hover when VS Code can do this for me automatically.

In addition, what is the semantics of resizing? Is the size remembered for the next hover (where it might be too big and just looks ugly)? Or do I have to resize every time?

And then there is the problem that interactions with hovers are delicate because interacting with the hover's border will easily dismiss it.

As previously said, I suggest to make the hover fit its contents as long as the hover window stays within the bounds of the underlying VS Code window. And if the hover needs to become larger, there is scrolling.

**Comment by isidorn** [comment] 2020-09-17 07:49
Makes sense and I agree with your points. Let's assign to September for investigation.

**Closed** 2020-09-17 16:44 UTC
Labels: bug, debug

**Comment by isidorn** [comment] 2020-09-17 16:45
I have fined tuned the debug hover width and height to the following:
* Height is as large as needed up to the maximum of the 70% editor content height. Once max is hit there is the scroll bar.
* Width is as large as needed up to the maximum of 700px. Once max is hit, there is the scroll bar.

I have tried it out and works quite nice for me. Please try it out and let me know how it goes.

**Comment by isidorn** [comment] 2020-09-21 12:16
This item is covered by this test plan item https://github.com/microsoft/vscode/issues/107156
