### ISSUE TITLE
Close all editors defunct when invoked vis keybinding

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#17874] opened 2016-12-28 14:05 UTC
```
    {
        "key": "cmd+w",
        "command": "workbench.action.closeEditorsInGroup"
    },
```
* add above keybinding 
* open an editor, press `cmd+w`
* 🐛 nothing happens, debugger shows that the action tries to close editor at slot `-1`

<img width="479" alt="screen shot 2016-12-28 at 15 01 59" src="https://cloud.githubusercontent.com/assets/1794099/21523473/fbd09f48-cd0e-11e6-9dfa-b4efa5795223.png">

**Comment by bpasero** [comment] 2017-01-02 10:29
Caused by https://github.com/Microsoft/vscode/commit/bc46e789ac57f327f409260fb8cc1f6e40e62a7b

**Comment by isidorn** [comment] 2017-01-03 08:54
Fixed by reverting commit

**Closed by isidorn** 2017-01-03 08:54 UTC
Labels: bug, important
