### ISSUE TITLE
I would like dock toolbar to top of the sidebar

### ISSUE THREAD

**Issue by hasimyerlikaya** [microsoft/vscode#109786] opened 2020-10-31 12:25 UTC
![image](https://user-images.githubusercontent.com/7986394/97779002-48760e80-1b8c-11eb-8fc9-0f009726558e.png)

While developing Flutter applications, we are constantly working in debug mode. Therefore, the toolbar is always open and we use it to reflect the changes.

There are options to change the location of the toolbar. We can use it as docked but then it only appears above the Run window.

When used as floating, it comes over the window title and the buttons there.

Can you add the option to add docked to the top of the sidebar?

**Comment by yume-chan** [comment] 2020-11-02 02:51
Related (but not same) to #109192 #106367

**Comment by isidorn** [comment] 2020-11-02 08:55
Closing as duplicate of the linked issues, and out of scope since if we do something here we will tackle one of those.

**Closed** 2020-11-02 08:55 UTC
Labels: *duplicate, debug
