### ISSUE TITLE
Source Control Repositories -> Close repository - always show again

### ISSUE THREAD

**Issue by peter31990** [microsoft/vscode#135534] opened 2021-10-21 08:42 UTC
I close a repository by clicking `Close repository` and after a while, as soon as I navigate to an open file from this repository, the repository appears again even though I closed it a while ago.

**Comment by Dare-marvel** [comment] 2022-12-08 13:32
I'm too getting the same error......what to do?

**Comment by lszomoru** [comment] 2022-12-08 13:40
Closing as duplicate of #107398.

**Closed by lszomoru** 2022-12-08 13:40 UTC
Labels: bug, git
