### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by stromal** [microsoft/vscode#164235] opened 2022-10-21 09:49 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: Windows 10 + Ubuntu 20.04 LTS on the EC2

Steps to Reproduce:

1. start up an AWS EC2 ubuntu 20.04 LTS
2. Connect to it with you local VS code Windows 10
3. All files open no problem I can see the correct folder structure
4. Every files open just fine except: any .ipynb
5. error message from the bottom "Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."
6. I have created new  .ipynb files but they also did not open  -> NOT solved the problem
7. I have restarted VS code and reconnected multiple times -> NOT solved the problem
8. I have restarted Windows 10 -> SOLVED the problem

**Comment by jkhoogland** [comment] 2022-10-27 16:56
similar story on OSX Catalina 10.15.7

**Comment by MustakAbsarKhan** [comment] 2022-10-28 16:24
Also Facing this problem in **macOS monetery Version 12.6**.

**Comment by mjbvz** [comment] 2022-10-28 19:26
Duplicate of #125993

**Closed by mjbvz** 2022-10-28 19:26 UTC
