### ISSUE TITLE
ctrl-click in cmd shell opens second view of file

### ISSUE THREAD

**Issue by manbearian** [Microsoft/vscode#47695] opened 2018-04-11 21:21 UTC
Issue Type: <b>Bug</b>

ctrl-click in cmd shell opens second view of file

When i ctrl-click on a file reference in the cmd shell it opens a second view of the file if i already have it open. I only get one additional copy (second ctrl-click goes to exisitng file view).

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|Memory (System)|31.94GB (18.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1

</details>
Reproduces only with extensions

**Comment by Tyriar** [comment] 2018-04-12 13:55
I can not reproduce this, can you take a screenshot of the 2 files next to each other and also screenshots of what it shows when you mouse over each file tab?

Did you recently restart and not open the first file editor before clicking on the link?

**Comment by manbearian** [comment] 2018-04-12 16:31
Hi @Tyriar , my repro is simple: open vs code, open folder, open file, add syntax error, build in cmd-window, ctrl-click file, a second view of the file is opened.
I double checked the repro this morning and noticed a casing difference between the two files; i'm guessing this is the root cause? 

See screen capture below where VS Code identifies a casing difference between the two files:

![image](https://user-images.githubusercontent.com/25087458/38690923-3060032e-3e34-11e8-9b24-f6c8bb035512.png)

Is there an "ignore-case" setting for VS Code on Windows...?

**Comment by Tyriar** [comment] 2018-04-30 21:26
Pretty easy to repro still on 1.23:

![image](https://user-images.githubusercontent.com/2193314/39451157-883fcb86-4c82-11e8-8653-aa432c45ad2b.png)

**Comment by Tyriar** [comment] 2018-04-30 21:29
@bpasero `IWorkbenchEditorService` is not normalizing file path case on Windows:

https://github.com/Microsoft/vscode/blob/a287dcd89e38485c42b45186268b22791b797922/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L161

Is there a reason this isn't done by `WorkbenchEditorService`?

**Comment by bpasero** [comment] 2018-05-01 05:02
Duplicate of https://github.com/Microsoft/vscode/issues/12448

**Closed by bpasero** 2018-05-01 05:02 UTC
Labels: bug, windows

**Comment by bpasero** [comment] 2018-05-01 05:03
@Tyriar it is not so easy as you think. We had a very good OneNote page explaining the issue but that one unfortunately just got deleted :-(
