### ISSUE TITLE
`$tsc-watch` background problem matcher is locale specific

### ISSUE THREAD

**Issue by victorandree** [microsoft/vscode#46373] opened 2018-03-22 23:12 UTC
The `beginsPattern` and `endsPattern` for the `$tsc-watch` problem matcher match on lines where the time is reported in a specific format (`11:12:13 PM`). The tsc watch output, however, uses `toLocaleTimeString` which changes depending on your locale (e.g. `11:12:13 p.m.`). This results in the task never ending if your locale is wrong.

From [extensions/typescript/package.json](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L569):

```json
{
  "background": {
    "activeOnStart": true,
    "beginsPattern": {
      "regexp":
        "^\\s*(?:message TS6032:|\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)? -) File change detected\\. Starting incremental compilation\\.\\.\\."
    },
    "endsPattern": {
      "regexp":
        "^\\s*(?:message TS6042:|\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)? -) Compilation complete\\. Watching for file changes\\."
    }
  }
}
```

Output from `tsc-watch` on my machine is:

    11:41:10 p.m. - Compilation complete. Watching for file changes.

A quick test shows that this doesn't match the `endsPattern` in package.json, because my AM/PM is capitalized the way it is. If I create a custom matcher, the task finishes successfully.

Is it necessary to match the full line? If not, simply matching the end of each line might be sufficient (expressions not JSON escaped).

    beginsPattern: File change detected\. Starting incremental compilation\.\.\.$
    endsPattern: Compilation complete\. Watching for file changes\.$

It's probably not a fun project to try and build a regex capturing all different ways to format times, so maybe the liberal `^\s*(?:message TS6042:|.*? -)` could work if you want a pattern for the full line?

I'm running the latest version of relevant software:

| Component | Version |
| :- | :- |
| Visual Studio Code | 1.21.1 |
| TypeScript | 2.7.2 |
| macOS | High Sierra 10.13.3 |
| Locale | English with Swedish formats* |

\* This format seems pretty Node/v8 specific, because I really use 24 hour time and in Language & Region in System Preferences, I do have AM/PM as the chosen before/after noon markers. If run `new Date().toLocaleTimeString()` in `node`, I get the above formatting (node 9.8.0) -- but in Chrome it's 24 hour time.

Here's a full tasks.json which could work for other people:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "isBackground": true,
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
      },
      "problemMatcher": {
        "base": "$tsc-watch",
        "background": {
          "activeOnStart": true,
          "beginsPattern":
            "File change detected\\. Starting incremental compilation\\.\\.\\.$",
          "endsPattern": "Compilation complete\\. Watching for file changes\\.$"
        }
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

I'm pretty sure the diagnostic is generated by TypeScript in [createWatchStatusReporter in src/compiler/watch.ts](https://github.com/Microsoft/TypeScript/blob/17b10dc2a9782d00d60632d088418d148c698428/src/compiler/watch.ts#L47):

```typescript
export function createWatchStatusReporter(system: System, pretty?: boolean): WatchStatusReporter {
    return pretty ?
        (diagnostic, newLine, options) => {
            clearScreenIfNotWatchingForFileChanges(system, diagnostic, options);
            let output = `[${formatColorAndReset(new Date().toLocaleTimeString(), ForegroundColorEscapeSequences.Grey)}] `;
            output += `${flattenDiagnosticMessageText(diagnostic.messageText, system.newLine)}${newLine + newLine + newLine}`;
            system.write(output);
        } :
        (diagnostic, newLine, options) => {
            clearScreenIfNotWatchingForFileChanges(system, diagnostic, options);
            let output = new Date().toLocaleTimeString() + " - ";
            output += `${flattenDiagnosticMessageText(diagnostic.messageText, system.newLine)}${newLine + newLine + newLine}`;
            system.write(output);
        };
}
```

**Comment by dbaeumer** [comment] 2018-03-26 09:46
For now I will add a.m. and p.m. to the patterns. If we detect more locale variants for am / pm we need to investigate if we go with a different solution.

**Comment by victorandree** [comment] 2018-03-26 10:07
I did a quick check with the (locales found in this StackOverflow post](https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes) check using `new Date().toLocaleTimeString(locale)` on node/Chrome. Even for English, you also have `am` (`en-AU`), but then you have Arabic, Greek, Spanish (as spoken in US), Mandarin and others... Here's the different formats I saw:

* 12:06:02
* 12:06:02 ከሰዓት
* ١٢:٠٦:٠٢ م
* 12:06:02 م
* 12:06:02 ч.
* ১২:০৬:০২ PM
* 12.06.02
* 12:06:02 μ.μ.
* 12:06:02 PM
* 12:06:02 pm
* 12:06:02 p.m.
* 12:06:02 p. m.
* ۱۲:۰۶:۰۲
* 12 h 06 min 02 s
* 12:06:02 ಅಪರಾಹ್ನ
* 오후 12:06:02
* १२:०६:०२ म.उ.
* 12:06:02 PTG
* பிற்பகல் 12:06:02
* 下午12:06:02

**Comment by dbaeumer** [comment] 2018-03-27 08:54
@victorandree thanks. I will reopen the issue and see what a better solution would be.

**Comment by alexr00** [comment] 2019-01-04 16:06
Supporting localized problem matchers is more of a feature than a bug.

**Comment by alexr00** [comment] 2019-11-19 16:09
@mjbvz I've gotten a whole bunch of these issues recently. Do you think it would be safe to match on just the the [hh:mm:ss] pattern and accept any other characters before or after the times? That would capture most of these times.

**Comment by mjbvz** [comment] 2019-11-19 22:28
That sounds reasonable to me. Do you want to make the change or should I?

**Comment by alexr00** [comment] 2019-11-20 09:35
Sweet. I made the change and confirmed that English still works. I'll follow up with the people who hit this in other issues after we have an Insiders build and see if they can verify it.

**Comment by alexr00** [comment] 2020-02-04 11:54
The tsc problem matchers can't be made completely locale agnostic, but closing since this should be improved over the previous behavior.

**Closed by alexr00** 2020-02-04 11:54 UTC
Labels: feature-request, tasks

**Comment by Tyriar** [comment] 2020-02-25 01:39
@alexr00 please add a test plan or verification needed

**Comment by alexr00** [comment] 2020-02-25 11:34
To verify, make sure that problems in English can still be detected with the  $tsc-watch problem matcher. If you happen to also have a machine with a language other than English that uses one of the other separators, verify there too (not required).
