### ISSUE TITLE
How to set multi parallel background tasks as preLaunchTask

### ISSUE THREAD

**Issue by RyanLeeLY** [microsoft/vscode#86812] opened 2019-12-12 10:55 UTC
## Environment
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

## Problem
I have a multi-root workspace including multi gulp watch tasks. I create a new task call 'Watch All' by using `dependsOn` and `dependsOrder` properties.  I set  'Watch All' as a `preLaunchTask`, but the launch task doesn't run before the `preLaunchTask` terminated. Here is the `code-workspace` file content.

```javascript
"tasks": {
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "watch:name1",
        "command": "yarn",
        "options": {
          "cwd": "${workspaceFolder:name1}",
        },
        "isBackground": true,
        "problemMatcher": [
          {
            "pattern": [
              {
                "regexp": ".",
                "file": 1,
                "location": 2,
                "severity": 3,
                "code": 4,
                "message": 5
              }
            ],
            "background": {
              "activeOnStart": true,
              "beginsPattern": ".",
              "endsPattern": "."
            }
          }
        ],
        "args": [
          "watch"
        ],
        "presentation": {
          "reveal": "always"
        },
        "group": "build"
      },
{
        "type": "shell",
        "label": "watch:name2",
        "command": "yarn",
        "options": {
          "cwd": "${workspaceFolder:name2}",
        },
        "isBackground": true,
        "problemMatcher": [
          {
            "pattern": [
              {
                "regexp": ".",
                "file": 1,
                "location": 2,
                "severity": 3,
                "code": 4,
                "message": 5
              }
            ],
            "background": {
              "activeOnStart": true,
              "beginsPattern": ".",
              "endsPattern": "."
            }
          }
        ],
        "args": [
          "watch"
        ],
        "presentation": {
          "reveal": "always"
        },
        "group": "build"
      },
      {
        "label": "Watch All",
        "presentation": {
          "reveal": "always"
        },
        "group": "build",
        "dependsOrder": "parallel",
        "dependsOn": [
          "watch:name1",
          "watch:name2"
        ]
      }
    ]
  },
  "launch": {
    "configurations": [],
    "compounds": [
      {
        "name": "Debug Main",
        "preLaunchTask": "Watch All",
        "configurations": [
          {
            "folder": "main-app",
            "name": "Electron: Main"
          }
        ]
      }
    ]
  },
```

**Comment by alexr00** [comment] 2019-12-17 10:00
Looks like a duplicate of https://github.com/microsoft/vscode/issues/70283

**Closed** 2019-12-17 10:00 UTC
Labels: *duplicate, tasks
