### ISSUE TITLE
screen tearing 

### ISSUE THREAD

**Issue by yosefahab** [microsoft/vscode#118106] opened 2021-03-04 10:21 UTC
Screen looks teared while using vscode (not all the time) can be temporarily fixed by clicking/dragging the area but it tears again, later on. Not related to installed themes (happens with the default themes as well). No apparent way to reproduce the bug (sometimes alt+tab reproduces it).
Edit: moving the cursor all over the editor CAN reproduce this.
Device Drivers are up to date.
![Screenshot (46)](https://user-images.githubusercontent.com/61936188/109949427-04367e80-7ce4-11eb-80f5-2aa5f0446fe2.png)

**Comment by IllusionMH** [comment] 2021-03-04 10:57
/duplicate of #117491

See https://github.com/microsoft/vscode/issues/117491#issuecomment-785054233 for links to comments with possible workarounds.

**Closed** 2021-03-04 10:58 UTC
Labels: *duplicate
