### ISSUE TITLE
Markdown follow image link text isn't a link

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#173875] opened 2023-02-08 19:56 UTC
Follow link should be a link so you can navigate it easily without a keyboard

<img width="139" alt="image" src="https://user-images.githubusercontent.com/2193314/217637438-32756fab-b2fb-4dd9-9d1c-f8389d041cb5.png">

Version: 1.76.0-insider (user setup)
Commit: beb9ed3758624b918f918886bb904b0b62511c08
Date: 2023-02-08T12:47:14.528Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by mjbvz** [comment] 2023-02-08 19:58
Duplicate of #158996

**Closed by mjbvz** 2023-02-08 19:58 UTC
