### ISSUE TITLE
stage code block - wack a mole

### ISSUE THREAD

**Issue by josephw-ml** [microsoft/vscode#151426] opened 2022-06-07 13:08 UTC
Issue Type: <b>Bug</b>

1. start with a file where a variable is instantiated in one code block, and used in another code block
3. rename the variable (at instantiation) in one code block
4. rename the variable in another code block where it is used
5. stage the first code block's change
6. stage the second code block that uses the variable from the first code block

expected: two code blocks have been staged
actual: first code block automagically become sunstaged,
  and re-staging again causes the second code block to become unstaged.

VS Code version: Code - Insiders 1.68.0-insider (acb156d6fb0dc451f427748d5f68774f17cc96fd, 2022-05-31T05:17:03.006Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 10, 8|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 7122eb11-4af8-4241-ad24-d1b3816378d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.0.7
python|ms-|2022.7.11571005
vscode-pylance|ms-|2022.6.0
sourcery|sou|0.12.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912cf:30496797
vsclangdf:30492506

```

</details>

**Comment by DevilXD** [comment] 2022-09-06 05:26
This sounds exactly like the #147373 issue. My way of solving this is to just use the "Reload window" option, it works properly after that.

**Comment by lszomoru** [comment] 2022-12-12 15:20
Closing this as duplicate of https://github.com/microsoft/vscode/issues/147373.

**Closed by lszomoru** 2022-12-12 15:20 UTC
Labels: bug, git
