### ISSUE TITLE
Allow to bind cursor navigation keys to input fields

### ISSUE THREAD

**Issue by cyantedyu** [microsoft/vscode#65578] opened 2018-12-22 04:12 UTC
i want to **bind some key for moving cursor in quick open**, i failed, 
but i managed to bind some key in quick open to do sth like this,

`
      {
        "key": "ctrl+h",
        "command": "workbench.action.closeQuickOpen",
        "when": "inQuickOpen"
      },

`

then , i tried to bind it to cursorWordLeft, it doesnt work,

`
      {
        "key": "ctrl+h",
        "command": "cursorWordLeft",
        "when": "inQuickOpen"
      },
`

**Here are some issues I found in similar need.**

1. #11950 Support text editing keybindings customization for quick open input

2. #64694 Allow keybinds configuration in Open Search Bar (for example) or Find Widget (for another example) 

Thanks for reply in advance!

**Comment by alexandrudima** [comment] 2018-12-23 16:33
The quick open input box is a native `<input>` element. It does not support commands like e.g. `cursorWordLeft`.

**Comment by chrmarti** [comment] 2019-01-03 07:49
Using our InputBox, these should all behave the same. Is that yours @sandy081?

**Comment by sandy081** [comment] 2019-01-03 15:20
@chrmarti I do not own the InputBox widget

**Comment by russelldavis** [comment] 2019-07-22 16:38
Seems like this should be closed as a duplicate of #64694. There's a workaround that I posted as a comment there.

**Closed** 2019-08-08 11:44 UTC
Labels: feature-request, keybindings
